### ISSUE TITLE
White flashing when injured is so intense I have to alt tab

### ISSUE THREAD

**Issue by alexcroox** [acemod/ACE3#1001]
The new white flashing when injured/down is so intense I have to alt tab out as it gives me a serious headache. 

The effect is OK when you can have other things in view, ie when you are still alive. But experience a helicopter crash and have that bright white pulsing against a dark background (the ground) and I swear my eyes will start bleeding after a minute of it :)

AGM's was much easier on the eyes/dark room when it was black pulsing when down.

**Comment by PabstMirror** [comment]
Just pop some morphine before you start the mission :wink: 

Take a look in the ace settings (hit escape) and try switching pain effect mode (I think it needs a mission restart)


![image](https://cloud.githubusercontent.com/assets/9376747/7446972/4fcb56ac-f1af-11e4-80f4-f0094668cff8.png)

**Comment by KoffeinFlummi** [comment]
> (I think it needs a mission restart)

nope.
