### ISSUE TITLE
Cannot carry or drag players in MP

### ISSUE THREAD

**Issue by Glowbal** [acemod/ACE3#1002]
Animations for dragging are not being played, nothing happens. For carrying it first starts, then the unit/player is being dropped again.

**Comment by ulteq** [comment]
Could this be the cause: https://github.com/acemod/ACE3/commit/414a50fb9b9376dc671706dbfe58190c62bf4ca4?

**Comment by Glowbal** [comment]
Ensure, something to look into. I do not know what the `up` does. @PabstMirror or @commy2 might be able to help here?

**Comment by Glowbal** [comment]
Also I'd like to see if someone else could reproduce this.

Steps:
- MP session with 2 clients.
- ```[aPlayer, true, 100] call ace_medical_fnc_setUnconscious;```
- Attempt to drag/carry.

Alternative:
- MP 2 clients.
- ```[aPlayer, true] call ace_medical_fnc_addToInjuredCollection;```
- ```aPlayer setvariable ["ace_medical_heartRate", 10, true];```
- Attempt to drag/carry.

**Comment by alganthe** [comment]
Can't reproduce this, both had a build signed with the latest key last commit being f6e815fbaf2f6d54ef8bc0d95b602b2eac69b3bb

**Comment by Glowbal** [comment]
I will upload the server config later today, so it can be tested using the same settings.

**Comment by Glowbal** [comment]
> I had this issue happen with me. I was unable to pick Glowbal up whilst he had no pulse but low blood pressure. when I tried to pick cage up it started to run though the animation but as soon as he was rested on my shoulders his then was dropped back onto the ground. then when i tried to drag Glowbal I started to be able to drag him and then when he died it locked me in place and was unable to get out of the animation for some time.
