### ISSUE TITLE
CUP goggles not working with ACE Goggles Addon.

### ISSUE THREAD

**Issue by bendy101** [acemod/ACE3#10054]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.16` LATEST STABLE
- **CBA:** `3.17.1` LATEST STABLE
- **ACE3:** `3.17.1` LATEST STABLE
- **CUP Weapons** `1.18.1` LATEST STABLE
- **CUP Units** `1.18.1` LATEST STABLE

**Description:**
CUP goggles not working with the Goggles addon. No rain effects.

**Steps to reproduce:**
Test with these CUP glasses:

CUP_G_Oakleys_clr
CUP_G_ESS_BLK_Ember

actually test with any CUP glasses / goggles

**Expected behavior:**
No rain effects when raining.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**

**Comment by acknowledge14** [comment]
ACE Compat CUP Facewear
https://steamcommunity.com/sharedfiles/filedetails/?id=2614664632&searchtext=CUP+goggles+ace
