### ISSUE TITLE
ArmA III Sonic boom

### ISSUE THREAD

**Issue by damiandib** [acemod/ACE3#1005]
Guys, I am a big fan of flying planes and amazing people with it that are on the ground.
This is why I am doing a request for a Sonic Boom when breaking the sound barrier.
I hop this feature could be implemented!
Thank you

**Comment by Glowbal** [comment]
Thank you for your request, but this a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
