### ISSUE TITLE
Global Mobilization MG3 Tripod Mount not working as intended

### ISSUE THREAD

**Issue by SlumDoc** [acemod/ACE3#10066]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.16`
- **Global Mobilization cDLC:** `1.5`
- **CBA:** `3.17.1`
- **ACE3:** `3.17.1`

**Description:**
Utilizing the Global Mobilization and the MG3 Anti Air Tripod Mount (Backpack Slot), I have encountered an issue whereby I am able to succesfully assemble the tripod and mount the MG3 onto the tripod, but once I attempt actually begin to use the weapon, I find that I am unable to fire, reload, or dismount the MG3 and subsequently disassemble the tripod. This has made the ability to carry the tripod around useless. I have attempted to also load the MG3 through ammunition handling and this does not work either.

**Steps to reproduce:**

1. Open 3den or Virtual Arsenal
2. Create Machine Gunner player from West German Faction, add MG3 Tripod Mount from Backpack slot
3. Run in singleplayer/multiplayer
4. Assemble Tripod via action, then mount MG3 to Tripod via action
5. Get in MG3 and attempt to utilize as Turret Mounted Weapon
6. Dismount turret, attempt to disassemble weapon.

**Expected behavior:**
The MG3 and its mount should have been able to be fireable and able to be reloaded like normal or through ammunition handling. Also, I should have been able to dismount the MG3 for normal use and then disassemble the tripod.

**Where did the issue occur?**
-Editor (Singleplayer) [also tested in Editor (Multiplayer) / Virtual Arsenal]

**Log Files:**
- https://gist.github.com/SlumDoc/421c8ee55f6fffee00238267becb3afa

**Additional context:**
N/A - No additional context to provide

**Screenshots:**
N/A - No screenshots to provide

**Comment by rautamiekka** [comment]
Does it let you out if you use a Zeus teleport ?

**Comment by SlumDoc** [comment]
> Does it let you out if you use a Zeus teleport ?

So you can leave the weapon no issue, the problem is breaking down the weapon after you get out of it. If you were to use it in a mission, you would be left without your primary as a result, as you cant unmount the MG as you normally would in a mission without ace3 loaded.

**Comment by SlumDoc** [comment]
Also, speaking of, I noticed that even through Zues you cant add ammo to it or the opposite, its treating it as an "incomplete" vehicle if that's any way to put it. You can still change the health and interestingly the fuel percentage, but there is no option for ammo.

**Comment by johnb432** [comment]
This is not an ACE issue, not even a CBA one - it's GM that's broken. I tested with no mods loaded, went into the arsenal, got the equipment and set it up, which threw a script error about not being able to add a weapon.
