### ISSUE TITLE
Client/Server Addon Mismatch // CUP compatibility

### ISSUE THREAD

**Issue by Soapierdig** [acemod/ACE3#10078]
**Mods:**
- **Arma 3:** `2.16`
- **CBA:** `3.17.1`
- **ACE3:** `3.17.1`
- **CUP Terrains - Maps 2.0** `1.17.0`
- **CUP Terrains - Core:**  `1.17.1`
- **CUP Weapons** `1.18.1`
- **CUP Units** `1.18.1`
- **CUP Vehicles** `1.18.1`

**Description:**
Subscribed to CBA, ACE3 and CUP packages except maps 1 and CWA
Uploaded all of these files to dedicated server so all the files are the exact same, when trying to run a misison i get error that i have clientside comp files that doesnt exist anywhere when searched for

**Steps to reproduce:**
1.  Subscribe to mods on steam workshop (see screenshots for the full list)
2. upload said mods to dedicated server (my case nitrado) thru filezilla
3. Launch default mission

**Expected behavior:**
The game/server to validate that we have the exact same files as they are uploaded from my pc

**Where did the issue occur?**
- Dedicated server thru Nitrado

**Log Files:**
Client: https://pastebin.com/MMRtDDuY
Server: https://pastebin.com/6wQz72zB

**Additional context:**
I have searched my pc a couple of times, the files stated ingame that i have doesnt exist on my pc
Reinstalled mods and cleaned workshop folder, aswell as repair mods in A3 launcher

**Screenshots:**
![Skärmbild 2024-06-16 112909](https://github.com/acemod/ACE3/assets/27677862/4a7da2c7-a6ad-4b62-ba46-2a979ce33557)
![Skärmbild 2024-06-16 124246](https://github.com/acemod/ACE3/assets/27677862/967f295f-ed3b-4395-84c7-e89178364a04)
![Skärmbild 2024-06-16 125344](https://github.com/acemod/ACE3/assets/27677862/cb8d5714-11e4-4acc-b1bd-e1a6748fd3e1)

**Comment by PabstMirror** [comment]
server is only loading `-mod="@CBA_A3;@ace;@CUP Terrains - Core;@CUP Terrains - Maps 2.0;"`
missing cup weapons, units, vehicles

**Comment by Soapierdig** [comment]
> server is only loading `-mod="@CBA_A3;@ace;@CUP Terrains - Core;@CUP Terrains - Maps 2.0;"` missing cup weapons, units, vehicles

~2 hours of troubleshooting and a headache nap, cant belive that i missed that
