### ISSUE TITLE
Correctly scale all tracers according to caliber

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#1008]
The `tracerScale` parameter is completely random in Arma 3. Quick comparison with Arma 2:

![image](https://cloud.githubusercontent.com/assets/7674951/7463147/584d86f4-f28d-11e4-99a4-985bdf4e53db.png)

Furthermore ACE2 increased the tracerScale for some calibers.

**Comment by jaynus** [comment]
Is tracerScale the same magical value as the caliber? So we are scaling from the same base 1 coefficient?

**Comment by esteldunedain** [comment]
Yeah, I didn't check but it appears to be something like that.

What I did notice is that A3's tracer model is probably smaller than that of A2. For the Comanche's 20mm round, to get roughly the same size of tracer you get in Arma 2 with `tracerScale = 4` I had to set something like `tracerScale = 10`.

**Comment by jaynus** [comment]
Well that (and this ticket) are very related to #378

**Comment by esteldunedain** [comment]
:+1:
