### ISSUE TITLE
Documentation for Attach Framework has broken Table 

### ISSUE THREAD

**Issue by Andx667** [acemod/ACE3#10210]
**Mods (complete and add to the following information):**
Does not apply

**Description:**
Title. https://ace3.acemod.org/wiki/framework/attach-framework

**Steps to reproduce:**
Does not apply

**Expected behavior:**
No Broken table.

**Where did the issue occur?**
ACE Wiki

**Log Files:**
Does not apply

**Additional context:**
Does not apply

**Screenshots:**
(https://i.imgur.com/AMbNj9U.png)

**Comment by PabstMirror** [comment]
weird, it looks valid in md preview:
https://github.com/acemod/ACE3/blob/master/docs/wiki/framework/attach-framework.md#2-event-handlers
