### ISSUE TITLE
Remove animation on placing explosive but add it when attaching trigger

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#1021]
placing explosives shouldn't take that long
it's just throwing a brick of c4 on the ground

attaching the detonator  is the time consuming action

**Comment by headedhorseman101** [comment]
>placing explosives shouldn't take that long
>it's just throwing a brick of c4 on the ground
>
>attaching the detonator is the time consuming action

:thumbsup:

**Comment by esteldunedain** [comment]
I'll handle this then
