### ISSUE TITLE
Wave intensity keeps changing

### ISSUE THREAD

**Issue by Best2nd** [acemod/ACE3#1025]
ACE3 Version: 3.0.0.2-NOGIT

Mods:
•@cba_a3
•@ace3

Placed ACE3 Modules:
 None

Description:
http://youtu.be/U5Jd7dZ01ic

Steps to reproduce:
 During bad weather, observe the sea and notice how it keeps changing from calm to rough.

Where did the issue occur?
 SP editor

RPT log file:
 None

**Comment by alganthe** [comment]
can confirm tested on version 3.0.0 last commit 150a76d31f6743a416bdce5dc8c857b477b005fc

**Comment by ulteq** [comment]
I can't reproduce it yet, but I'll try some more.

**Comment by bux578** [comment]
I'm able to reproduce

**Comment by ulteq** [comment]
> During bad weather, observe the sea and notice how it keeps changing from calm to rough.
I tested it on Stratis with an overcast and rain value of 1. No bug for me.

**Comment by alganthe** [comment]
my steps to reproduce:
* place a rifleman on altis in editor
* click on the clouds+thunder icon
* approach water and notice the flickering

**Comment by bux578** [comment]
https://www.youtube.com/watch?v=P-gfVZrnfm8 Once it has processed
