### ISSUE TITLE
NVGs noisy

### ISSUE THREAD

**Issue by likeusb** [acemod/ACE3#10276]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.16.151618 stable`
- **CBA:** `3.17/1 stable`
- **ACE3:** `3.17.1 stable`

**Description:**
Disabling NVG effects (noise, fog, etc) still keeps the effects there despite the fact that the effects are gone for everyone else

**Steps to reproduce:**
1. Disable all the effects in ACE3
2. Turn on NVGs in the dark

**Expected behavior:**
No noise and clean NVGs

**Where did the issue occur?**
Singleplayer, editor, multiplayer

**Log Files:**
https://pastebin.com/PFQRjwbJ

**Additional context:**
No one apart from me is experiencing this

**Screenshots:**
![image](https://github.com/user-attachments/assets/884f6c32-1bc7-4118-8d80-cc2e7d5b29ed)
^ What I see
![image](https://github.com/user-attachments/assets/2b8741ec-9a96-493d-bf9c-721b31f0c13b)
^ What my friend sees

**Comment by rautamiekka** [comment]
Are they even the same goggles ? The blueish color is part of the `WP` (white phosphorus) variants, and it's naturally a lot clearer than the same one without.

**Comment by likeusb** [comment]
This happens to every pair of nvgs for me and none of the pairs for them, and it happens in 3den and Zeus NVG modes too

Sincerely,
Linas
________________________________

**Comment by johnb432** [comment]
> Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!

You are loading `@Fawks' Enhanced NVGs`, which might have an effect.

**Comment by likeusb** [comment]
I do have fawks, but I tested this on a complete clean modlist with just ace and CBA and it had the exact same effect.
I also remember running fawks before and having no issues

**Comment by johnb432** [comment]
> I do have fawks, but I tested this on a complete clean modlist with just ace and CBA and it had the exact same effect. I also remember running fawks before and having no issues

Please link the RPT to the clean test session, as the current has too many uncertainties.
What are your ACE nightvision CBA settings? Can you please export them?

**Comment by likeusb** [comment]
![image](https://github.com/user-attachments/assets/27c94058-508d-4b3a-9e8f-bb1e4df19e57)
https://pastebin.com/LJFADeRh

// ACE Nightvision
ace_nightvision_aimDownSightsBlur = 0;
ace_nightvision_disableNVGsWithSights = false;
ace_nightvision_effectScaling = 0;
ace_nightvision_fogScaling = 0;
ace_nightvision_noiseScaling = 0;
ace_nightvision_shutterEffects = false;

**Comment by johnb432** [comment]
Again

> Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!

Why are you still loading other mods?

---

I do not understand what you trying to convey with your latest image.

In your initial post, you say
> No one apart from me is experiencing this
and post two very different images, once from your perspective and one from your friend's.

Now you post something that looks, in terms of "graininess", exactly like your friend's...? So the issue is resolved or what?

You are trying to compare apples and pears in your original post, you need to be using a) using the same NVGs, b) using the same NVG preset in Fawks and c) looking at roughly the same thing, so that you aren't comparing at two completely different contrasts.

**Comment by likeusb** [comment]
Reason number 543 as to why I don't make bug reports anymore.
You really could have just said "Seems like you loaded mods on accident" and not gone about with this whole "How dare you make a mistake" attitude.

Now as to the issue - the NVGs continue to look noisy. Maybe not that visible in screenshots that have been compressed to high hell, so here's a close up as to what I mean.
![image](https://github.com/user-attachments/assets/a512067b-9785-4b77-adad-977a44e22cca)
vs
![image](https://github.com/user-attachments/assets/2dd38a56-b78b-4402-92cc-3fe09b3ffaa5)

There's a healthy dose of Discord compression in that second one, which I can't do anything about, but EVERYONE in my friend group sees normal except for me, who has way too much noise.

And I guess sorry for uploading the wrong rpt on accident?
And sorry for not removing every variable known to man so you can have an ideal testing environment? I thought I made it quite clear when I said "Not a problem for anyone else except for me, no matter what I do", that it is, in fact, me who is having the issue and no one else, and that there is nothing I can do to fix said issue.
https://pastebin.com/7DvjHXQQ
Here's the correct pastebin link

**Comment by johnb432** [comment]
> There's a healthy dose of Discord compression in that second one, which I can't do anything about

Why not use the image you posted just above? Because when I look at your friend's screenshot (the one in the OP), I can see just about as much grain as is in your latest screenshot.

I have the impression settings you posted above aren't being applied. I want you to screenshot the CBA settings tab for ACE Nightvision, both server and mission tabs. I also want you to run `ace_nightvision_ppeffectGrain` and report the contents of that variable back here.

**Comment by likeusb** [comment]
Yeah, sure!
Ace nightvis tab:
![image](https://github.com/user-attachments/assets/44eb1b29-36bc-4b91-ab94-0a07729e4bc4)

And if I'm understanding correctly, upon running the command in the debug menu, I got -1. Though I don't entirely know how to actually run that, it might be somewhere else.

In regards to the images, my friend is the only comparison point I have and so I kinda have to rely on that one image, the screenshot I sent of zoomed in is the same image.
As per the settings, it is possible, though when I reset everything to the start, there is a way higher amount of noise, so it might even be that this is just the lowest it goes for my client for some reason?

**Comment by johnb432** [comment]
> And if I'm understanding correctly, upon running the command in the debug menu, I got -1. Though I don't entirely know how to actually run that, it might be somewhere else.

Yea, that's where you would run it. `-1` means the effect doesn't exist/isn't running. Can you take another screenshot when it returns `-1`, with the settings above, and post it here?

If `NVG Effect Scale` is set to `0`, it shouldn't be running at all and you shouldn't be seeing any noise.

**Comment by likeusb** [comment]
![image](https://github.com/user-attachments/assets/30649994-b4db-45e2-9ae0-f6d02109c712)

**Comment by johnb432** [comment]
> ![image](https://private-user-images.githubusercontent.com/80967503/363416808-30649994-b4db-45e2-9ae0-f6d02109c712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMTE1OTEsIm5iZiI6MTcyNTExMTI5MSwicGF0aCI6Ii84MDk2NzUwMy8zNjM0MTY4MDgtMzA2NDk5OTQtYjRkYi00NWUyLTlhZTAtZjZkMDIxMDljNzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEzMzQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNDNmM2U3NmRhNGFiYTRhNDMzYWNhMzc5MGM0ODU1ODM2OWU4MzE3OTM0ZmQ1MDc3NzNiYTYwOWRkODQ1Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PqWVLEVcDQAyDq4ZNexAsANvB37KMDd3S1G95I7V7Eg)

Sorry, I meant when you are wearing NVGs.

**Comment by likeusb** [comment]
Here it is, my apologies for the delay.
I confirmed that in that specific session I got -1 as the entry
At this point I'm starting to think that this is genuinely just the default look
![image](https://github.com/user-attachments/assets/fc4d095b-f85d-473c-a6f9-4c830949b7a6)
And up close version
![image](https://github.com/user-attachments/assets/1e945010-735b-4d3a-a0ea-9b9960ff9d9d)

**Comment by johnb432** [comment]
The best would be to test without ACE and compare side by side.

**Comment by likeusb** [comment]
Completely vanilla:
![image](https://github.com/user-attachments/assets/c707a1ba-dc2e-4d9a-bdd1-8d81f8b31c09)
Zoomed in:
![image](https://github.com/user-attachments/assets/bf067417-5458-409e-8f23-b3ca7867ba97)

So honestly I'm starting to think it's some vanilla Arma thing that for some reason only affects me

**Comment by johnb432** [comment]
You could try switching profiles and see if that makes a difference.
Otherwise, try playing with your PP settings, *might* be one of those causing an issue.

**Comment by likeusb** [comment]
Seems like nothing worked, I'll just assume that this is standard vanilla minimums and is completely unchangable. It's less visible in person, I guess, so it isn't that bad, I'll just get used to it.
Thanks for all the help though! I appreciate the effort you put into this
