### ISSUE TITLE
ACE Fire fatal error when ACE Medical removed

### ISSUE THREAD

**Issue by Coji4000** [acemod/ACE3#10280]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.16` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.17.1` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.17.1` [e.g. 3.0.0 stable, commit hash]

**Description:**
When removing ACE Medical with ACE Fire enabled game load encounters a fatal error during addon load.

**Steps to reproduce:**
_Follow [this flowchart](https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp)!_

1. _Go to ..._ @ace\addons
2. _Remove ..._ \*medical\* from directory
3. _Start ..._ Arma 3 with ACE and CBA enabled
4. _See ..._ Arma 3 DEAD error for failed file load during addon initialization

**Expected behavior:**
Arma 3 would start up with ACE and CBA functional and Medical Engine removed

**Where did the issue occur?**
- Local during Game Startup

**Log Files:**
Image of troubleshooting report included below.
Sorry for lack of logs. Just reporting this as an uneducated user after the fact and only had the image remaining.

**Additional context:**
To solve the error I just removed ACE Fire as well but I couldn't find anywhere that declared ACE Medical as a dependency (nor do i see where fire is calling out to this file when I load the code into VS). I realize without the rpt it makes this weird so im sorry if this is more nuisance than helpful. I couldn't find a less official way to report this.

**Screenshots:**
![image644654654](https://github.com/user-attachments/assets/ea744ba9-cd1b-4fc9-8fad-60b6d91da12e)
![image419811](https://github.com/user-attachments/assets/4ba1fd91-0bab-40ce-9e59-a12c83e4ced9)
![Screenshot 2024-08-30 150127](https://github.com/user-attachments/assets/66c6edce-5cf9-420f-b12c-d43c04f049dc)

**Comment by PabstMirror** [comment]
Should be fixed via https://github.com/acemod/ACE3/pull/10122

**Comment by johnb432** [comment]
Yep, already fixed.
