### ISSUE TITLE
PIP Scopes - blur effects buggy when switching scope

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#1029]
ACE3 Version: 3.0.0.2-NOGIT

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
When using the RCO or MRCO PIP scope, scoping in with the magnified scope and then switching to the alternative sight on top the blur effect stays.
This also works the other way around, looking through the alternative sight and then switching to the magnified sight causes no blur on the border of the magnified scope.

**Steps to reproduce:**
* Equip the PIP RCO or MRCO
* Look through your scope, make sure you are in the magnified mode
* Go out of the scope and back in again, make sure the scope is blurry on the border
* Swich to the alternative optics on top

**Where did the issue occur?**
* Singleplayer

**RPT log file:**
http://pastebin.com/VvPL9n5F

**Comment by jaynus** [comment]
@commy2  Probably forget to add some FOV checks to determine what view the scope is at.

**Comment by commy2** [comment]
http://feedback.arma3.com/view.php?id=23741

**Comment by BaerMitUmlaut** [comment]
@commy2 not the same bug, try it for yourself.

**Comment by esteldunedain** [comment]
I'm not sure it's related, or even if it's by design, but after 1.42 I sometimes observed blurred iron sights on vanilla weapons (whithout switching any scope).

**Comment by BaerMitUmlaut** [comment]
Actually I'm wrong, it is that BI bug, I thought that part of the effect was added via script as well. Anyways, picture for reference:

![2015-05-06_00001](https://cloud.githubusercontent.com/assets/9693842/7498009/1925b220-f41e-11e4-8ccc-e2044fa2cd58.jpg)

**Comment by commy2** [comment]
>I'm not sure it's related, or even if it's by design, but after 1.42 I sometimes observed blurred iron sights on vanilla weapons (whithout switching any scope).

They actually introduced this with 1.40. Something similar happened in Alpha / Beta times and it even had a work-around (setting the same amounts of pp effects as all other optics modes to "").
That no longer works though. It now doesn't register the optic change at all.
