### ISSUE TITLE
Arma 3 Tools are required to be ran at least once before building.

### ISSUE THREAD

**Issue by sean-clayton** [acemod/ACE3#1031]
The Mikero tools will not detect the Arma 3 Tools unless the Arma 3 Tools are ran first. Unfortunately, this isn't documented anywhere :cry:

**Comment by esteldunedain** [comment]
Yep, know issue. You also need to run it once after **every update** of A3 tools.

**Comment by esteldunedain** [comment]
gj @PabstMirror!
