### ISSUE TITLE
Grenade throwing improvement.

### ISSUE THREAD

**Issue by cych** [acemod/ACE3#1033]
The current A3 vanila system to throw a grenade is very basic and pretty unrealistic. you just have to press G to throw a grenade, without any possibility to adjust throwing forces, cooking delay, avatar animation...etc

the ACE 2 grenade system, with weapon cycle, throwing animation was clearly superior.

ideally, an advanced throwing system should be the one developped by Dslyecxi.

https://www.youtube.com/watch?v=aGt8QbK61aE

**Comment by jaynus** [comment]
Please read the request and bug guidelines. #414
