### ISSUE TITLE
Adv Fatigue - Massive stamina drain on stairs or rocks

### ISSUE THREAD

**Issue by Mike-MF** [acemod/ACE3#10347]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14`
- **CBA:** `3.18.0` RC
- **ACE3:** `3.18.0` RC

**Description:**
Stamina will drain rapidly when running up stairs (couldnt repro myself, but reported by multiple people) or rocks (seen myself)

**Steps to reproduce:**
1. Find a rock formation, run over it a few times, when running over gaps watch your stamina vanish.

**Expected behavior:**
Not that.

**Where did the issue occur?**
- Dedicated

**Log Files:**
- Nothing in RPT at all.

**Comment by Drofseh** [comment]
maybe fixed by #10297 ?

**Comment by PabstMirror** [comment]
that just fixed cases where terrain lateral slope was having effect when not touching terrain
I think it's mostly just paying the penalty for moving up

you may want to turn the new `advanced_fatigue,terraingradientfactor` setting down a bit

**Comment by Mike-MF** [comment]
Just went and played with that setting, imo the default at 1 is insane.

With the default you take large chunks out of your stamina rapidly, with the setting at 0.1 it's reasonable.
