### ISSUE TITLE
Unable to combine SPACE key with other keys

### ISSUE THREAD

**Issue by riwarek** [acemod/ACE3#10358]
**Mods (complete and add to the following information):**
- **Arma 3:** last one
- **CBA:** v3.17.1.240424
- **ACE3:** 3.17.1

**Description:**
Can't bind anything with SPACE key like: space+A or space+b.
But I can do binding like space+ctrl

**Steps to reproduce:**
Just try to bind it in options->control->configure addons

**Expected behavior:**
Possibility to combine keys with SPACE key.

**Where did the issue occur?**
- always on client

**Log Files:**
- none

**Comment by johnb432** [comment]
This is not an ACE issue, keybinds are part of CBA. Similar issue exists there (https://github.com/CBATeam/CBA_A3/issues/789), so don't make a new one, it's a known issue.
