### ISSUE TITLE
Script errors from ace settings

### ISSUE THREAD

**Issue by Glowbal** [acemod/ACE3#1037]
Script error (among others) I had last night on server:
```
21:29:06 Error in expression <ce_advanced_ballistics_enabled", false] && (_bullet isKindOf "BulletBase") && (_>
21:29:06   Error position: <&& (_bullet isKindOf "BulletBase") && (_>
21:29:06   Error &&: Type Number, expected Bool
```
__Server settings values:__
http://pastebin.com/Lxbw7Fu4

__Client settings values:__
http://pastebin.com/smGCDsXB

**Comment by Glowbal** [comment]
Server config used: 
http://pastebin.com/PUuqQMCb

**Comment by jaynus** [comment]
I've edited out my portion of this ticket; it was unrelated and not an issue.

**Comment by esteldunedain** [comment]
I've been looking into this with no results. There are a lot of missing privates, but that should not be a problem unless the code is halting execution, which it shouldn't

**Comment by jaynus** [comment]
Perhaps we should give ace_server, ace_settings and ace_optionsmenu a privates sweep prior to release?

**Comment by Glowbal** [comment]
Couldn't reproduce this evening. Added missing privates to the settings framework. All code looked fine. 

I will keep an eye out for this, but for now assume fixed/cannot reproduce. Closed.
