### ISSUE TITLE
Destroy Entity keybind no longer works with ACE loaded.

### ISSUE THREAD

**Issue by Mike-MF** [acemod/ACE3#10375]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.18`
- **CBA:** `3.18.0`
- **ACE3:** `3.18.0`

**Description:**
Cannot kill units via Zeus using the End key (Destroy Entity keybind). But you can kill vehicles with it. Tested it with vanilla and it works fine, tested with just CBA still fine.

Nothing pops in RPT about it.

**Steps to reproduce:**

1. Open Zeus
2. Place any unit
3. Try to end

**Expected behavior:**
Should kill people.

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Comment by PabstMirror** [comment]
It's medical_engine
it gets a handleDamage with `_this=[unit,"",1,<NULL-object>,"",-1,<NULL-object>,"",true,0]`

I don't think anything has changed so this must be a 2.18 thing?

I guess we just manually handle this match
context == 0 and _sel = "" and _damage = 1 and _ammo = ""
unless this matches something else?
