### ISSUE TITLE
Goggles: Removing the PBO breaks NVG overlay/Adv throwing icons

### ISSUE THREAD

**Issue by Cyruz143** [acemod/ACE3#10382]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.18` [stable]
- **CBA:** `3.18` [stable]
- **ACE3:** `3.18` [stable]

**Description:**
Removing the ace_goggles.pbo causes the NVG overlay to not render and the adv grenade throwing mouse icon to vanish.

**Steps to reproduce:**
1. Grab release versions of ACE + CBA from GH
2. Remove ace_goggles.pbo + bisign
3. Editor placed NATO man with NVGs
4. Preview
5. Try throwing grenade and/or using NVGs

**Expected behavior:**
Previous versions were fine with googles removed.

**Where did the issue occur?**
- Editor (Singleplayer)

**Log Files:**
https://gist.github.com/Cyruz143/430701654fb453a9eb64e7dd52f76012

```c
10:05:56 Warning: no type entry inside class ace_interaction_RscMouseHint/controls/IconLMB 
10:05:56 Warning: no type entry inside class ace_interaction_RscMouseHint/controls/IconMMB 
10:05:56 Warning: no type entry inside class ace_interaction_RscMouseHint/controls/IconRMB 
10:05:58 Warning: no type entry inside class ace_nightvision_title/controls/Hexes 
10:05:58 Warning: no type entry inside class ace_nightvision_title/controls/Mask 
10:05:58 Warning: no type entry inside class ace_nightvision_title/controls/trippleHeadLeft 
10:05:58 Warning: no type entry inside class ace_nightvision_title/controls/trippleHeadRight 
```

**Screenshots:**
![107410_20241009101314_1](https://github.com/user-attachments/assets/4d2d4626-9643-413d-90e5-f34d9281671b)
![107410_20241009101336_1](https://github.com/user-attachments/assets/896a8d7d-7641-474d-b9c3-a0ddc26ed64a)

**Comment by PabstMirror** [comment]
i think it has to do with us defining rscPicture in rsctitles for some reason
looking into it
