### ISSUE TITLE
Rations - Consuming from Inventory Screen bugs out 

### ISSUE THREAD

**Issue by OverlordZorn** [acemod/ACE3#10403]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.18 stable`
- **CBA:** `3.18.0` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.18.0` [e.g. 3.0.0 stable, commit hash]

Still collecting data - will be completed.

**Description:**
When consuming food/water via the cba context menu, the progressbar does not stop/complete at 0 but instead keeps going to -1, -2, etc.
also did not consume the item

**Steps to reproduce:**
do the tasty through the context menu

**Expected behavior:**
Stop at 0, consume the food item, satisfaction achieved.

**Where did the issue occur?**
- Dedicated, video reproduced in SP

**Log Files:**

**Additional context:**

**Screenshots:**
![image](https://github.com/user-attachments/assets/2a6ffa6f-24fb-4bd2-bdd4-22068a6e5330)

https://youtu.be/_nEPOTI7A5Y

**Comment by OverlordZorn** [comment]
![image](https://github.com/user-attachments/assets/c49caa72-2ca9-4dbb-94da-2004db2452e5)

**Comment by OverlordZorn** [comment]
> Yep, worked just fine before the update
seems that this issue only appeared after 2.18/3.18

**Comment by OverlordZorn** [comment]
https://pastebin.com/z50u85kf

**Comment by OverlordZorn** [comment]
https://pastebin.com/fbPSeCZd
rpt from the user who made the video

**Comment by johnb432** [comment]
It's a CBA bug, fixed in https://github.com/CBATeam/CBA_A3/pull/1704.

**Comment by PabstMirror** [comment]
Will be fixed in cba 3.18.1
