### ISSUE TITLE
Problem since update 3.18.0.

### ISSUE THREAD

**Issue by korda2310** [acemod/ACE3#10412]
Hi, I have a problem since the last update it is impossible to join my missions that I created on our server. However, I have the game up to date and the update added to the server. Each time it gives me the error message like on the screen I posted. Could you help me I can't find the problem. Thank you (sorry for my English via Google translation).
![Capture](https://github.com/user-attachments/assets/1e75d9a9-2f6b-4e34-b502-f9daa3a0c6ab)

**Comment by Andx667** [comment]
try repairing the mod first, then if the issue persists, reinstall the mod and see if it works.

**Comment by PabstMirror** [comment]
This is from arma not updating
make sure the game has updated 2.18 via steam

**Comment by johnb432** [comment]
Since this is most likely a game issue, I'm closing this.
