### ISSUE TITLE
AtragMx - `Elev`: wrong value with `Gun` column and `Done`

### ISSUE THREAD

**Issue by Laid3acK** [acemod/ACE3#10421]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.18` stable, `2.19.152232` dev
- **CBA:** `3.18.0`, `3.18.1 RC1`
- **ACE3:** `3.18.0`, `3.18.1 RC1`

**Description:**
Click `Done` to the AtragMx `Gun` column updates `Elev` with wrong value, **AB enabled only** (other Ace3 options as default).
**Steps to reproduce:**
_Follow [this flowchart](https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp)!_

1. _Go to the Editor, new mission in any maps, grab an AtragMx, `ZR` = `TR`, `Atmsphr` as default._
2. _Open `Gun` column, click `Done`._
3. _See `Elev`, should be `0`._
4. _Same in all cases, If a player needs to update BH, C1, Twist, MVs ... and `Done`, `Elev` is updated with a wrong value._

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to [RPT](https://gist.github.com/Laid3acK/4fcae7959e75905d1229c940ed3758c6).

**Comment by Laid3acK** [comment]
If im not mistaken, first time i see that.
Maybe an issue with scope base angle calculation ?

**Comment by Holgerhollebolle** [comment]
yes...i Can confirm the issue...makes sniping currently not possible. Elevation is not correctly calculated.
