### ISSUE TITLE
optionals\server.pbo is being rapified and should be NOBIN

### ISSUE THREAD

**Issue by Cephel** [acemod/ACE3#1043]
It looks like the toolchain used by make.py does SOMETHING that utterly screws with the way include file paths are handled, userconfig files in particular.

I was testing the server settings via the included serversettings module, when I noticed none of my changes propagate to the ingame config, instead it kept displaying the default:
``` c++
class ACE_common_forceAllSettings {
    value = 0;
    typeName = "BOOL";
};
```
in config format. So I started a little testing run:
- Rename include file, game starts normal without errors, default values in config.
- Delete include file, see above
- Rename "userconfig" folder, see above
- Manually edited the pbo and changed the folder path, see above

Nothing I tried even remotely worked, I deleted every instance of the userconfig file from my computer, including the ones in the repository JUST TO MAKE SURE and guess what: IT STILL HAD THE DEFAULT VALUES inside the config. I have no words to even describe this.

In the end I manually recompiled the serverconfig pbo with the vanilla build tools and FINALLY it behaved like intended, changes now show up, it complains about a missing file if you move the userconfig file, etc.

**Comment by gienkov** [comment]
What is inside your serverpath/userconfig/ace/serverconfig.hpp?
Did you have ace_server.pbo running on your server?

**Comment by Cephel** [comment]
>What is inside your serverpath/userconfig/ace/serverconfig.hpp?

``` c++
class ace_medical_level {
    value = 2;
    typeName = "SCALAR";
    force = 1;
};
```
>Did you have ace_server.pbo running on your server?

Yes

**Comment by jaynus** [comment]
This is due to server.pbo being rapified, which is copying in the included userconfig from the building system. This should not be rapified/binarized to induce dynamic loading.

**Comment by Cephel** [comment]
>This is due to server.pbo being rapified, which is copying in the included userconfig from the building system. This should not be rapified/binarized to induce dynamic loading.

Well server settings should be able to change without having to recompile the pbo, but yeah, that explains all the problems I had. Nearly drove me insane.
