### ISSUE TITLE
Make.py doesn't remove old/deprecated .bisigns

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1044]
ACE3 Version: 3.0.0.2

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None*

**Description:**
*As stated in title.*

**Steps to reproduce:**
* *Build release version with other biprivatekey then build again with another one.*
* *Old bisigns don't get removed inside addons folder*

**Where did the issue occur?**
*tools folder*

**RPT log file:**
*Not needed.*

**Comment by ViperMaul** [comment]
With the latest master branch, I cannot reproduce your issue.
Are you sure you are using the latest version of make.py?
Because this feature was added in the past 30 days

**Comment by ViperMaul** [comment]
Also provide an exact filename of one of the bisign files that it is not being removed.

**Comment by alganthe** [comment]
make sure you're not on your branch while you have your issue, can't reproduce
