### ISSUE TITLE
Incorrect Ace Frag Gurney Equations

### ISSUE THREAD

**Issue by Ollieollieolllie** [acemod/ACE3#10533]
The current Gurney equation is 
_V/sqrt(2*_E) = sqrt (_chargeMass / (_metalMass + _chargeMass * _geometryCoefficient))

the correct equation is
_V/sqrt(2*_E) = sqrt ((_metalMass / _chargeMass) + _geometryCoefficient))

Func reference:
fn_getFragInfo.sqf
line: 92

I would also point out the futility of including Gurney Equations when ace frag does not disperse the fragmentation in the appropriate patterns

**Comment by lambdatiger** [comment]
Just to clarify for future searching

You are missing a inverse on the right hand side, the correct equation is [[1]](https://en.wikipedia.org/wiki/Gurney_equations#Equations)[[2]](https://apps.dtic.mil/sti/tr/pdf/AD0783941.pdf)
$$\frac{V}{\sqrt{2E}}=\left(\frac{M}{C}+G\right)^{-\frac{1}{2}}=\left(\sqrt{\frac{M}{C}+G}\right)^{-1}=\frac{1}{\sqrt{\frac{M}{C}+G}}$$
Where $$\frac{V}{\sqrt{2E}}$$ is the gurney velocity, $$M$$ is the fragmenting metal mass, $$C$$ is the charge mass, and $$G$$ is the geometry coefficient. If you then take equation and multiply both the numerator and denominator by $$\sqrt{C}$$ you get,
$$\frac{V}{\sqrt{2E}}=\frac{\sqrt{C}}{\sqrt{C}\sqrt{\frac{M}{C}+G}} =\frac{\sqrt{C}}{\sqrt{M+GC}}=\sqrt{\frac{C}{tM+GC}}$$
