### ISSUE TITLE
Gunner Down!

### ISSUE THREAD

**Issue by Tombstone222** [acemod/ACE3#10556]
Hello,

Heavy weapons guy here, alot of my unit like to perform tactical maneuvers in .50 and Mk.19 trucks.
I noticed that even though you can unload wounded crew outside the trucks via ace, there is currently no option to swap seats with a downed gunner from inside the vehicle, which is something that is trained in heavy weapons often. 

Such an option would permit vehicle based players a QOL Change that would allow them to maintain base 
of fires on their objectives Without over exposing crew to small arms.. I Ctrl+F'd to see if this has been suggested and turned up o results so far so let me know if this has already been suggested.

Thank you for your time.

**Comment by Drofseh** [comment]
#3594
