### ISSUE TITLE
Vehicle damage work items

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#1062]
Vehicle damage is coming to fruition in extP3dParser branch. This ticket is to log work items needed for VD

- [x] Code Framework
   - [x] model/vehicle/instance framework
   - [x] background threaded initialization
   - [x] dispatching and messaging arma<->ext
   - [x] SQF result work items
- [x] Model Reading
   - [x] p3d parsing
   - [x] pbo searching/in-game vehicle:model association, registration and loading
   - [x] Animation handling for vehicle state (@noubernou)
- [x] 3d physics world initiation and management
    - [x] model positional transformations (bullet, all models in same world)
- [x] Extension framework and dispatching
- [ ] penetration methods @esteldunedain 
   - [ ] long rod equations
   - [ ] missile two-stage penetration
   - [ ] bullet/shell (conical) round penetration
   - [ ] malformed fragment penetration
   - [ ] HEAT round penetration
- [ ] damage @jaynus
   - [x] vehicle-based damage logging and compounding
   - [x] damage types->hitpoint mappings
   - [ ] damage effects WIP
- [ ] crew kills
- [ ] extended ACE hitpoint definitions 
- [ ] lots of documentation and optionals compat

- [x] Optimization work items
   - [x] bullet-model optimizations
   - [x] GPU offloading vector math
   - [x] animations
   - [x] async dispatching framework

**Comment by Bummeri** [comment]
Just out of curiosity, Why isnt the [RAM](http://forums.bistudio.com/showthread.php?171586-Real-Armor-Mod) vehicle damage system an acceptable way of doing things ?

**Comment by esteldunedain** [comment]
> Just out of curiosity, Why isnt the RAM vehicle damage system an acceptable way of doing things ?

AFAIK the main issue with RAM's approach is that it requires vehicles models to be setup in an specific way, thus being incompatible with most vehicles currently out there. The second issue is that it requires changing projectile properties, which creates compatibility issues too.

**Comment by jaynus** [comment]
work items updated.

**Comment by john681611** [comment]
Is this a dead Milestone Its over a year since any development seems to have been done.
