### ISSUE TITLE
Medical - "Enabled for: Players only" does not seem to be working

### ISSUE THREAD

**Issue by Best2nd** [acemod/ACE3#1064]
ACE3 Version: 3.0.0.2-NOGIT

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* Medical Settings [ACE]
* Advanced Medical Settings [ACE]

**Description:**
Setting the medical for players only seems to have no effect, medical is still on for AI.

**Steps to reproduce:**
Set "Enabled for" to "Players only"

**Where did the issue occur?**
SP editor

**RPT log file:**
None

**Comment by Glowbal** [comment]
It's a spelling mistake in `fnc_hasMedicalEnabled`.

**Comment by Glowbal** [comment]
Thank you, fixed in #1065
