### ISSUE TITLE
addUnitLocalPerFrameHandler (Automatic locality shifting PFH)

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#1067]
jaynus [11:59 AM] 
:stuck_out_tongue:

jaynus [11:59 AM]
isnt that what we DO?

jonpas [11:59 AM] 
we run 3 headless clients (beefy machine, still not using resources it has, damned Arma), so any awesome function for it woudl be very handy

jonpas [11:59 AM]
love the abbreviation

jaynus [12:00 PM] 
i mean actually

jaynus [12:00 PM]
well wait

jaynus [12:00 PM]
@esteldunedain:

jaynus [12:00 PM]
addUnitLocalPerFrameHandler

jaynus [12:00 PM]
would be nifty

esteldunedain [12:00 PM] 
killer!

jaynus [12:00 PM] 
using _this to pass and track the PFH vars

jaynus [12:00 PM]
that could come in handy, and provides this framework too

esteldunedain [12:00 PM] 
if locality changes then remote  command the new owner to restart a new pfh (edited)

jaynus [12:01 PM] 
Yes

jaynus [12:01 PM]
if you lose locality, pass the _this pointer via an event

jaynus [12:01 PM]
have the new owner snag it

esteldunedain [12:01 PM] 
yeah make a ticket for that

jaynus [12:01 PM] 
I can see that being useful for vehicles

**Comment by PabstMirror** [comment]
WIP PR #1101
