### ISSUE TITLE
IR laser switching replace modded lasers

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#1070]
ACE3 Version: 3.0.0 last commit :

**Mods:**
* @cba_a3
* @ace3
* @rhsusf

**Placed ACE3 Modules:**
none

**Description:**
When an RHS IR laser attachment is equipped and you switch light modes (ctrl+L) the attachment get replaced by a vanilla one (IR laser red)
note that happens with every modded IR laser, and that the compat pbos are present

**Steps to reproduce:**
place a rifleman in the editor
place an RHS ammobox
equip a weapon with an RHS IR laser attachment
switch light modes (ctrl+L by default)
notice that the attachment get replaced

**Where did the issue occur?**
Editor, Multiplayer

**RPT log file:**
nothin'

**Comment by commy2** [comment]
This is due to class inheritance. RHS' laserpointer is a children of the vanilla laserpointer and therefore considered to be the same as the vanilla one.

Not sure if we want to disable inheritance for this entry just like with the titan. Opionions?

**Comment by PabstMirror** [comment]
```
    class acc_pointer_IR: ItemCore {
        ACE_nextModeClass = "ACE_acc_pointer_red";
```

Every item that inhertis from `acc_pointer_IR` will switch

**Comment by commy2** [comment]
BWA3 LLM-01 does not inherit from `acc_pointer_IR`. Therefore works fine with this.

**Comment by jaynus** [comment]
I'm started to get pissed at lazy inheritance trees. This was never a problem in A2 - people didn't use vanilla shit for random crap.

I'm starting to think fuck em
