### ISSUE TITLE
Interaction menu items are overlapping

### ISSUE THREAD

**Issue by BullHorn7** [acemod/ACE3#1080]
http://i.imgur.com/g24jyEr.png

EDITED by ed:
![image](https://cloud.githubusercontent.com/assets/7674951/7550307/d5b66f4a-f632-11e4-981d-94970de17089.png)

**Comment by esteldunedain** [comment]
I think the two entries for the microDAGR and the two for the Kestrel are excesive. IMO I'd like to have only one entry to "Show" a device, and then have a standard key to switch between modes (e.g,., Home). Either that or submenus (Equipment -> Devices maybe)

**Comment by jonpas** [comment]
Could be client side option to show big or small for each device as well. Or even better have a button as you said or an interaction menu entry like "show bigger/smaller" (only when it's shown) which will be saved and persisted through game restarts.

**Comment by esteldunedain** [comment]
Bigger/smaller is not just a matter of preference. The big version is interactive (you can press the buttons), while the smaller version is non-interactive (to see the screen while you do something else). But yeah, I think a "Show" action when it's hidden it's enough. Then you should switch big/small with a key or a contextual interact menu action.

**Comment by jonpas** [comment]
Right, forgot about interaction a bit. That would be perfect IMO as well.

**Comment by Legolasindar** [comment]
My vote is for only 1 entries for device, not need 2 entries if i can enter and press buttons for change size or others.
