### ISSUE TITLE
Disable Zeus alerts and eagle and other stupid stuff

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#1082]
Zeus currently displays a bunch of global alerts. We should hide these dialogs and sounds (if we can) to prevent immershun breaking stuff.

- [x] Zeus spawns a stupid fucking freedom bird in the sky
- [x] Zeus shows ascension messages globally
- [x] Zeus is this https://www.youtube.com/watch?v=arCITMfxvEc

**Comment by commy2** [comment]
I want ambient freedom birds and seagulls. Like the rabbits and snakes.

**Comment by SilentSpike** [comment]
Hey, I actually made an addon that does this already for the group I play with to use in-house.

If it's any use to you guys you can find it [here](https://gitlab.dicgaming.net/clear-backblast/cbb-mods-a3/tree/master/cbb_curator_modules). :+1:

**Comment by esteldunedain** [comment]
@silentspike, we don't have access to that repo. Feel free to submit the code some other way.

**Comment by jonpas** [comment]
@SilentSpike If you want to integrate it into ACE, make a pull request. If you don't, do what @esteldunedain said and someone here will work on integrating it into ACE (I would as it would give me a good starting point on developing full modules for ACE :grinning: ).

**Comment by SilentSpike** [comment]
Oh, sorry about that, I forgot it was private!

I've stuck it [on github](https://github.com/SilentSpike/ARMA-SilentCuratorModules/tree/master/cbb_curator_modules) for you guys to take a look at.

It adds a bunch of new modules too, so here's a list of the vanilla stuff that is changed:
* Remote control module wind sound removed
* Ascension message removed 
* Eagle removed
* Mine modules no longer create map markers
* Projectile module no longer gives players a warning

All the overwrite functions can be found under functions/overwrites. Everything else is relating to new modules (If you want to see how to use the curator display framework feel free to take a gander there too).

**Comment by jonpas** [comment]
Nice! What do ACE devs reckon should be in ACE from it?

> Mine modules no longer create map markers

That's very handy, what I'd do though is leave the default module and add a new one that would be without markers, that way you have a choice what to place.

**Comment by SilentSpike** [comment]
You guys can use any of it to your heart's content (goes for anyone, not just the ACE devs). If you'd like me to go ahead integrate any of it with ACE in a pull request then feel free to ask.

**Comment by alganthe** [comment]
mu freedombird shall not be stolen !!111

**Comment by whiztler** [comment]
Kill the zeusEagle:

    private ["_curPos"];
    _curPos = [];

    for "_i" from 0 to ((count allCurators) - 1) do {
    	_curPos = _curPos + [getPosASL (allCurators select _i)];
    };
    {
    	{if (typeOf _x == "Eagle_F") then {deleteVehicle _x}} forEach ((_curPos select 0)  nearEntities 25000);
    } forEach allCurators;

**Comment by jaynus** [comment]
That is the most horribly inefficient code I have seen all year.

>  nearEntities 25000

Dear god. Your basically killing the client.

**Comment by commy2** [comment]
And all freedom birds.

**Comment by whiztler** [comment]
:( You're right. Should be 25. Any way to delete the Eagle on a config level?

**Comment by SilentSpike** [comment]
Just stop it spawning in the first place by removing it from the moduleCurator function

**Comment by Karneck** [comment]
ACE3 if you are looking for no zeus. Try this.
https://www.dropbox.com/sh/ii66s87ozic08tl/AACG5UEBdLbUS2ELopbUH7mka?dl=0

**Comment by jonpas** [comment]
That does look like a cleaner solution, though an object with empty p3d will still be spawned.

**Comment by SilentSpike** [comment]
I wouldn't call it particularly cleaner (neater sure). You're editing all instances of an object rather than just removing the one instance you care about.

**Comment by Karneck** [comment]
Maybe it'll help with figuring it out, I thought I would share.

**Comment by esteldunedain** [comment]
Done in #1082
