### ISSUE TITLE
Better flash suppressor

### ISSUE THREAD

**Issue by ulteq** [acemod/ACE3#1100]
Replace the (ugly) vanilla flash suppressors (placeholders):
- [ ] \A3\weapons_f\acc\acca_mzls_H_F
- [ ] \A3\weapons_f\acc\acca_mzls_l_F
- [ ] \A3\weapons_f\acc\acca_mzls_smg_01_F

with some appropriate models.

**Comment by PabstMirror** [comment]
#3594
