### ISSUE TITLE
microdagr GUI doesn't scale properly in 1080 small UI

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#1102]
ACE3 Version: 3.0.0 last commit 2bb3a0f139374ae9e06c50b636d0b3bdb83d1f46

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
none

**Description:**
The microdagr doesn't rescale properly in 1920x1080 with a small UI, screenshot of the issue p: http://imgur.com/CLXa8Cf
NOTE THAT THE ISSUE IS NOT THE POSITION but the size

**Steps to reproduce:**
You need a 1920x1080p resolution for this issue to appear.
set your display settings to be 
```
resolution 1920x1080p
windowed fullscreen
small UI
vsync disabled
```
grab a microdagr, open it and notice you can only see half of it / it's incredibly big.

**Where did the issue occur?**
editor, SP, MP

**RPT log file:**
nothing

**Comment by jaynus** [comment]
Assigned to pabst as he is marked maintainer.

**Comment by PabstMirror** [comment]
I need to document this better, but the microdagr uses the same layout size/pos as the arma gps.
* Hit escape -> configure -> game -> layout

and look for the **GPS** box (it might be hidden under a bunch of AV Camera,Slingload,... windows)

![untitled](https://cloud.githubusercontent.com/assets/9376747/7555491/af396184-f712-11e4-87ce-f3b1d5e2bcf5.jpg)

Drag and resize (I only use the width, to keep the same aspect ratio).  Then just close and reopen the microSWAG in game and it should show up in game (don't need to restart mission).
