### ISSUE TITLE
make.py binarizes optionals with $NOBIN$

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#1107]
ACE3 Version: 3.0.0.2 d6dde3c73fb3d9031114ebfb38f315d290727253

**Mods:**
* @cba_a3
* @ace3 (btw, that account must be getting a lot of notifications by now)

**Placed ACE3 Modules:**
None

**Description:**
ACE userconfig doesn't get loaded on the server with ace_server.pbo, because ace_server.pbo gets unbinarized when packing a release build with `make.py`. Apparently this happens with optionals only, it doesn take into account to check for $NOBIN$ (look at below make.py output) but the resulted PBO contains both `config.cpp` and `config.bin` and Arma uses .bin if available.

**Steps to reproduce:**
* Run make.py
* Use userconfig\ace\serverconfig.hpp on a server
* ACE userconfig doesn't get loaded because ace_server.pbo is binarized

**Where did the issue occur?**
Multiplayer - Dedicated Server

**~~RPT log file~~ make.py output:**
```
Making server------------------------------------------------------
Missing PBO file ace_server.pbo. Building...
Building: P:\z\ace\addons\server
Destination: P:\z\ace\release\@ace\addons
$NOBIN$ Found. Proceeding with non-binarizing!
MakePbo x64UnicodeVersion 1.88, Dll 4.97 "server"
Building entries:...
$NOBIN$
config.backup
config.bin
config.cpp
script_component.hpp
/*Creating ArmA style pbo:*/
Prefix = z\ace\addons\server
$NOBIN$
config.backup
config.bin
config.cpp
script_component.hpp
Writing data blocks: .....
Written sha '3A1CBA266DAD883557A604C37CE499366AF05EF8'
```

**Comment by ViperMaul** [comment]
@jonpas, good find. 
I see the problem. 
We will get it fixed by tomorrow.
