### ISSUE TITLE
Game crashing on startup - alternate extension builds

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#1111]
ANYONE COMING TO THIS TICKET DUE TO CRASHING:

Please download the .dll files here and use them: 
https://github.com/acemod/ACE3/tree/extBuildFix

**Comment by Cephel** [comment]
I just had a gpu driver crash, don't think it's related, but still.

**Comment by jaynus** [comment]
This is currently fixed in vehicledamage branch

**Comment by SzwedzikPL** [comment]
Can you send me fixed dll to test with guy who has this problem?

**Comment by jaynus** [comment]
Later this week its going to get merged into master with the new build process. Sit tight :)

**Comment by jaynus** [comment]
Please test the extensions here and report back: 
https://github.com/acemod/ACE3/tree/extBuildFix

**Comment by SzwedzikPL** [comment]
Works :) Thank you!

**Comment by jaynus** [comment]
:thumbsup:

**Comment by enderrrrrrrrrr** [comment]
So i replaced the DLLs and now i can get into the game but for some reason my character keeps looking up.

**Comment by esteldunedain** [comment]
> So i replaced the DLLs and now i can get into the game but for some reason my character keeps looking up.

That's certainly unrelated to ACE.

**Comment by enderrrrrrrrrr** [comment]
Yes for some reason when i installed ace with the new DLLs it caused something weird to happen with my headtracking software. Disabling it fixed the issue.

**Comment by jaynus** [comment]
:)

**Comment by YobaCrucian** [comment]
https://github.com/acemod/ACE3/tree/extBuildFix - link broken :(

**Comment by jaynus** [comment]
They are the DLLs on the master branch now, we merged the changes in.

https://github.com/acemod/ACE3
