### ISSUE TITLE
Wiping Goggles always uses uses primary weapon animation

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#1122]
ACE3 Version: 3.0.0.2 ab580dd1c7bb0dba710a42f0193bb312eceac0c0

**Mods:**
* `@cba_a3`
* `@ace3`
* `@task_force_radio`

**~~Placed~~ ACE3 ~~Modules~~ userconfig:**
* Advanced Ballistics
  * Advanced Ballistics (Boolean): `Yes`
* BlueForceTracking 
  * `Enabled`
* Medical Settings
  * Medical Level (Option): `Advanced`
* MK6 Settings
  * `Enabled`

**Description:**
Wiping goggles when you have a secondary weapon equipped shows you wiping with your primary equipped.

**Steps to reproduce:**
* Take your secondary weapon
* Wipe your goggles

**Where did the issue occur?**
Multiplayer - Dedicated Server

**RPT log file:**
N/A

**Comment by jonpas** [comment]
Confirmed on ab580dd1c7bb0dba710a42f0193bb312eceac0c0 as well (latest as of time of this comment).

**Comment by commy2** [comment]
Duh. Thats the A3 gesture for you. This ticket should be on the A3 feedback tracker, imo.

**Comment by jonpas** [comment]
I agree!

**Comment by alganthe** [comment]
one day BI will decide to do a pass on it's incredibly limited animations, for this issue it's BI's fault we would need an animation for each weapon type and each pose

**Comment by jonpas** [comment]
Replaced by #3638
