### ISSUE TITLE
make.py ignores version change and skips outdated modules rebuild

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#1127]
ACE3 Version: 3.0.0.2 ab580dd1c7bb0dba710a42f0193bb312eceac0c0

**Mods:**
* `@cba_a3`
* `@ace3`

**Placed ACE3 Modules:**
N/A

**Description:**
Build with make.py doesn't take into account to verify ACE3 version number and does NOT rebuild the modules (PBOs) at all, which makes them unusable on the server since it will report that the modules are outdated.

**Steps to reproduce:**
* Build with make.py
* Change ACE3 version number
* Build with make.py again
* See that modules weren't updated with new version number and render "outdated" message on Servers

**Where did the issue occur?**
N/A

**RPT log file:**
N/A

**Comment by ViperMaul** [comment]
We just use the command-line param  __'force'__ as in __'make.py force'__ or delete the make.cache file when we change the version. knowing this, this probably won't be enhanced any time soon. But a re-write is in the making and will be considered.
