### ISSUE TITLE
make.py and build.py refuse to do their intended actions

### ISSUE THREAD

**Issue by cynaraos** [acemod/ACE3#1128]
I have followed all the steps in [the guide to set up the development environment](http://ace3mod.com/wiki/development/setting-up-the-development-environment.html). I downloaded commit ab580dd1c7, using TortoiseGit. when I use the make/build Python scripts, both pop up for only a few milliseconds, with no results other than the ones you can see in the following screenshots. 
[make.py screenshot](http://i.imgur.com/uRTgKRr.png)
[build.py screenshot](http://i.imgur.com/tcCiMEu.png)

**Comment by jonpas** [comment]
> Verify that \GIT\BIN or \GIT\CMD is in your system path or user path.

Do that and if they are not there you have to add them (TortoiseGit I am pretty sure doesn't add them).

**Comment by cynaraos** [comment]
the issue has been fixed. the system PATH was missing the \git\bin and \git\cmd directories, and MakePBO was not installed.

**Comment by rebelvg** [comment]
Can someone help, please. What variables should I create and what the values should be.
I used make.py before and it was alright until something was changed and now I have no idea what to change on my end.

**Comment by ViperMaul** [comment]
@rebelvg, make a new issue and give us an error message. I cannot guess what is wrong with your situation compared to everyone else. Based on the information you have given me, my hands are tied. I can say make sure the requirements are setup properly as referenced here: http://ace3mod.com/wiki/development/setting-up-the-development-environment.html#1.-requirements
