### ISSUE TITLE
stuck when placing explosive while prone

### ISSUE THREAD

**Issue by kripto202** [acemod/ACE3#1130]
I'm sure this is a BI fault but I had to make sure. When placing an explosive to a vehicle while your prone, you get stuck and can't move. 

steps to reproduce:
- place a vehicle
- have a demo charge and "clacker"
- attempt to place explosive under the vehicle while prone
- try to move.

video coming soon

**Comment by alganthe** [comment]
please use [this form] (http://ace3mod.com/wiki/user/how-to-report-an-issue.html) and .... that ... issue.... eerm how to say it... welp press prone again, because when you play the animation you just kneel.
