### ISSUE TITLE
Interaction menu won't pop up

### ISSUE THREAD

**Issue by Anaximandross** [acemod/ACE3#1131]
ACE3 Version: 3.0.0.3

**Mods:**
* @cba_a3
* @ace3
*RHS Escalation
*Leights Opfor
*AiA Terrain
*A few maps
*ALIVE
*TFAR

**Placed ACE3 Modules:**
None, I also tried putting down the medical modules

**Description:**
The interaction menu won't popup. The modules will show up in the editor, all of the items (medical supplies) shoow up in my inventory, but whenever I press the windows key or windows and shift nothing happens. 

**Steps to reproduce:**
Uhhh
**Where did the issue occur?**
Editor, as well as the singleplayer mission "Losis Armory" 

**RPT log file:**
http://pastebin.com/ji5jRaDR

That should be everything. Also, thanks for the quick release! I can't wait to see where this goes, and how awesome it is!

**Comment by jaynus** [comment]
Please try the interactions with only @ace and @cba loaded - that RPT is covered with RPT errors, and theres no real way to see what would be breaking it; as everything is basically broken.

Also make sure you have the latest CBA installed. Also, please check your ACE hotkeys (Settings->controls->Configur addons) to confirm the keys are set.

**Comment by Anaximandross** [comment]
I tried both of things and neither of them worked. For some reason, when I click 'configure addons' nothing appears. The menu pops up, but no mods show up.

**Comment by gienkov** [comment]
What CBA_A3 version you use?

**Comment by jaynus** [comment]
>when I click 'configure addons' nothing appears.

Your CBA installation is old or broken; Re-install your CBA installation. http://forums.bistudio.com/showthread.php?178224-CBA-Community-Base-Addons-ARMA-3

**Comment by Anaximandross** [comment]
Hm. Alright I'll do that.

**Comment by jaynus** [comment]
Please let us know after you have updated CBA if the configure addons is available.

**Comment by Anaximandross** [comment]
Well, that's a bit embarassing. My bad. The CBA fixed it. Thanks!
