### ISSUE TITLE
MenuItem respawn Template doesent load on Linux dedicated when Ace items are added

### ISSUE THREAD

**Issue by m1ndgames** [acemod/ACE3#1132]
EDIT (jaynus, adding report):

ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
- Advanced Ballistics
- Explosive System
- Hearing
- Weather
- Wind Deflection
- Interaction System
- Map
- Blue force Tracking
- Medical Settings
- Revive Settings

**Description:**
I use the MenuInventory respawn Template and ive added some ACE items to the loadouts. The respawn inventories load as intendet in the mp editor preview, but the same exported map doesent load the inventories at all, when run on my dedicated linux server.

**Steps to reproduce:**
Add Ace items to a respawn inventory in description ext, export the map and start it on a linux dedicated server.
The used map is publicly avaiable: https://github.com/m1ndgames/WarZones.Altis/tree/ACE

**Where did the issue occur?**
After player respawn in multiplayer

**RPT log file:**
Server Log: http://m1ndfuck.de/arma3-server-console.log
Client Log: http://pastebin.com/tuRfZmak

-------

I added multiple items from ace to the respawn inventory loadout in description.ext.

They load in windows mp editor preview, but on the linux dedicated server no respawn template is shown at all.

Is it because some dlls cannot be loaded (because of linux obviously) ?

 1:28:21 [ACE]: ACE is version 3.0.0.3.
 1:28:21 [ACE] ERROR: Extension ace_break_line.dll not installed.
 1:28:21 [ACE] ERROR: Extension ace_clipboard.dll not installed.
 1:28:21 [ACE] ERROR: Extension ace_fcs.dll not installed.
 1:28:21 [ACE] ERROR: Extension ace_advanced_ballistics.dll not installed.
 1:28:22 [19126,37.357,0,"XEH: PostInit Finished. State: _isClient=false, _isJip=false, _isDedClient=false, _isServer=true, _isDedServer=true, _pl                                                             ayerCheckDone=true, _sp=false, _startInitDone=true, _postInitDone=true, _mpRespawn=true, _machineType=0, _sessionId=1, _level=0, _timeOut=false, _                                                             game=3, BIS_functions=L Modules:1, group=L Modules"]

Beside of that there is no valueable rpt log

**Comment by alganthe** [comment]
please use [this form] (http://ace3mod.com/wiki/user/how-to-report-an-issue.html)

**Comment by jaynus** [comment]
Its a linux dedicated server; it doesn't need the extensions. We need RPT.

**Comment by m1ndgames** [comment]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
- Advanced Ballistics
- Explosive System
- Hearing
- Weather
- Wind Deflection
- Interaction System
- Map
- Blue force Tracking
- Medical Settings
- Revive Settings

**Description:**
I use the MenuInventory respawn Template and ive added some ACE items to the loadouts. The respawn inventories load as intendet in the mp editor preview, but the same exported map doesent load the inventories at all, when run on my dedicated linux server.

**Steps to reproduce:**
Add Ace items to a respawn inventory in description ext, export the map and start it on a linux dedicated server.
The used map is publicly avaiable: https://github.com/m1ndgames/WarZones.Altis/tree/ACE

**Where did the issue occur?**
After player respawn in multiplayer

**RPT log file:**
Server Log: http://m1ndfuck.de/arma3-server-console.log
Client Log: http://pastebin.com/tuRfZmak

**Comment by jaynus** [comment]
@commy2 all yours, RPT included.

**Comment by commy2** [comment]
I can't get that dialog to work even in Vanilla

```
enableDebugConsole = 2;
respawn = 3;
respawnTemplates[] = {"MenuInventory","MenuPosition"};
```

Am I mission something?

**Comment by alganthe** [comment]
okay so first you got some corrupted data 
``` Can't find real path "a3\map_altis\data\roads\roads.shp": "No such file or directory" ```

``` 2:27:30 "m1ndfuck/log: ERROR: [BIS_fnc_respawnMenuInventory] No respawn inventories found" ``` not ace's fault

**Comment by m1ndgames** [comment]
Well, as i said: The same Mission loads the Inventory. This message doesent show up on Windows.

About the roads.shp: I always had this error on Linux, with Ace or without it. So this cant be the issue.

I can hook you up with a shell account and you test it on the live system, if you want to.

**Comment by jaynus** [comment]
> About the roads.shp: I always had this error on Linux, with Ace or without it. So this cant be the issue.

Hes saying your core arma vahnilla files are corrupt and to verify your cache/gamefiles in steam on linux.

**Comment by m1ndgames** [comment]
Yeah ive read it, but its not true.. This error comes from a bad windows / linux migration. The folder MPmissions is mpmissions in linux. As linux differences files in upper/lower score, this error comes up when you dont place a symlink. See this topic for more details: http://forums.bistudio.com/showthread.php?169926-Linux-Dedicated-Server-feedback&p=2581720&viewfull=1#post2581720

I will resolve that issue when im back at home later, and post another rpt.

**Comment by m1ndgames** [comment]
So weird... I created the symlink and restarted the mission. Well.. the shp error is still there, but player inventories are loaded properly... I could repoduce the issue 2 days ago again and again... Today it just works without changing anything... Its so weird...

I guess the issue can be closed now, sorry if i caused additional work but i was almost sure Ace was the culprit ;)
