### ISSUE TITLE
some modules claim to be unsigned

### ISSUE THREAD

**Issue by pmc-tyler** [acemod/ACE3#1134]
I downloaded the release of ACE and put it and the bikey on 2 different dedicated servers and when I try to join it gives me an error and kicks me. It appears that only a few pbos aren't signed properly or I'm just doing something wrong. 
![image](https://cloud.githubusercontent.com/assets/8658201/7602503/6901be36-f8f3-11e4-9a08-200cadcf66c6.png)

**Comment by alganthe** [comment]
please follow [this form] (http://ace3mod.com/wiki/user/how-to-report-an-issue.html) for your issue it seems that someone repacked the mod, this is NOT the normal installation path that's why you get the issue.

**Comment by pmc-tyler** [comment]
I keep my addons in multiple folders that causes an issue?

**Comment by esteldunedain** [comment]
@pmc-tyler, you can keep the P drive mounted as long as you launch arma with the `-noFilePatching` parameter.
