### ISSUE TITLE
Request: Re-add the "invulnerable while unconscious" module option 

### ISSUE THREAD

**Issue by Jester814** [acemod/ACE3#1137]
Request: Re-add the "invulnerable while unconscious" module option 

Unless we missed it, invulnerability while unconscious is no longer an option. Some weaponry will still kill you while unconscious. Looking to return to using the same settings as we were using previously in AGM as well as in ACE2 in ArmA 2.

**Comment by jaynus** [comment]
#414

**Comment by PabstMirror** [comment]
I believe the settings you would want would be:

`Medical Settings Module`: Prevent Instant Death: Yes
`Revive Settings`: Enable Revive: Player Only

**Comment by KoffeinFlummi** [comment]
As @PabstMirror said, the revive module essentially does the same thing, preventing death while unconscious and also allowing you to do stuff like limiting revives.

**Comment by Jester814** [comment]
Yep I appreciate it guys. It was just named differently from how it was in AGM, as well as being in a separate module. Sorry to waste your guys' time, but hopefully this will help folks out if they have the same question in the future.

**Comment by esteldunedain** [comment]
Thank you @Jester814; btw, I enjoy your videos. Congrats on that.
