### ISSUE TITLE
Game Crashing with Medical Modules

### ISSUE THREAD

**Issue by scooterperpetual** [acemod/ACE3#1140]
ACE3 Version: 3.x.x

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Add the list of modules you have placed on the map. Use 'None' if the error occurs without using any modules.*
Advanced Medical Settings
Medical Settings

(Tried with everything except BLUFOR tracking and the Set Medical modules earlier with same issues)

**Description:**
*Add a detailed description of the error. This makes it easier for us to fix the issue.*

When loading into a mission the bar gets about 70% through and then the following error pops up:
Bad version 68 in p3d file 'z\ace\addons\medical\data\bandage.p3d

**Steps to reproduce:**
* *Add the steps needed to reproduce the issue.*

Im guessing run Arma with CBA and ACE3 place down the two modules about, set the difficulty to advanced and enable advanced wounds.

**Where did the issue occur?**
*A possible answer might be "Multiplayer", "Singleplayer"*

Singleplayer

**RPT log file:**
*Add a link (pastebin.com) to the client or server RPT file.*

http://pastebin.com/gcFZpkkW

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by scooterperpetual** [comment]
Updated

**Comment by PabstMirror** [comment]
Arma is "Version: 1.42.130340"

I know there was a change with binerizer, so our p3d's might not be compatible with old versions of arma (also I think we use some new commands).

Update arma in steam.

**Comment by scooterperpetual** [comment]
Yep it would appear for some reason my ArmA 3 install was not linked to Steam anymore, anyways its updating now hopefully this fixes the problem

**Comment by jaynus** [comment]
It will ;) Make sure to verify your game cache.
