### ISSUE TITLE
Basic Medical System: 250ml and 500ml bloodpacks not working (scripterror)

### ISSUE THREAD

**Issue by Grollig** [acemod/ACE3#1142]
ACE3 Version: 3.0.0.3 (Initial release)

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
ACE_moduleAssignMedicRoles ( Synced with playerunit to make him a MedicClass )
ACE_moduleMedicalSettings ( Medical Level: Basic, AI Unconsciusness: Enabled, Prevent instant death: Yes )
ACE_moduleReviveSettings ( Players & AI, Max.Revive time: -1, Max Revive lifes: -1 )

Steps to reproduce:
1. Creat new mission in Editor. Place down a playerunit, a civilian and the ACE Medical Supply Crate (Basic).
2. Place down the three ACE Modules with the above settings.
3. Start the mission and pickup a 250ml or 500ml bloodpack from the ACE Medical Supply Crate (Basic). Make sure you don't have a 1000ml bloodpack in your Inventory.
4. Unload a Clip into our poor civilian test subject.
5. Try to give him a blood transfusion: Only the 1000ml option shows up (remember you only carry a 250ml or 500ml bloodpack with you). When selecting the 1000ml option a scripterror occurs (see screenshot crop below).

Where did the issue occur?
Multiplayer (Dedicated server)
and Singleplayer

Screenshot of scripterror msg:
![ace_bug01](https://cloud.githubusercontent.com/assets/12383839/7608509/78e4c5f6-f96a-11e4-9415-e3af34bea37d.jpg)

Demo mission can be provided if necessary.

**Comment by bux578** [comment]
rpt pls

**Comment by Grollig** [comment]
http://pastebin.com/1jemG1py

**Comment by gienkov** [comment]
Assign medical roles module is not meant to be synced! You should write
medic names inside that module.
13 maj 2015 12:39 "Grollig" <notifications@github.com> napisał(a):

**Comment by Grollig** [comment]
Doesn't make a difference in this case.
I have already tried setting the necessary variable manually by adding:
this setVariable ["ACE_medical_medicClass",1,true];
to the init of the player.

**Comment by alganthe** [comment]
@Grollig please try #1145 it fixes it for me
