### ISSUE TITLE
USER ERROR, RESOLVED - Vector 21: 8. Horizontal distance and azimuth between two points, Only shows distance between two points.

### ISSUE THREAD

**Issue by NummiE** [acemod/ACE3#1143]
ACE3 Version: Latest

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None*

**Steps to reproduce:**
* *Follow instructions in WIKI article, linked below.*

**Where did the issue occur?**
*Virtual Arsenal*

**RPT log file:**
*Not neccessary IMO.*

**Description:**

http://ace3mod.com/wiki/user/getting-started.html

Following the instructions in part 8. In your wiki, I could not get the Vector 21 to show azimuth between two points while simultaneously showing the distance between them. A couple of my clanmembers could confirm they couldn't make it work either. 
Bug or a error in the wiki article?

Also, the Azimuth key does not have to be pressed down until a red pointing circle appears, as is instructed in part 2. of the manual:

"2. Azimuth, Measuring Azimuth
Press and hold the "Azimuth" key until the red pointing circle appears. Sight the circle on the object and release the key."

The azimuth is shown immediately when you press down the azimuth key, and dissapears when you release it. It works as in real life, this must be a error in the wiki-instructions?

Awesome mod guys <3

Edit: Issue resolved, user error.

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by NummiE** [comment]
Just updated, hope this helps!

**Comment by VKing6** [comment]
The wiki is correct, and I know the function works as described.
Can you show/tell what kind of readout you do get when trying this?

**Comment by bux578** [comment]
@NummiE Still missing the rpt file. sorry.

**Comment by commy2** [comment]
```
1. Press and hold azimuth key (Tab)
2. Sight first object, click distance key once (R)
3. Wait until the circle appears
4. Sight second object and release the azimuth key
```

Works for me. The manual is wrong in that the circle only appears after you press the distance key once (which makes sense), but otherwise this works fine.

**Comment by NummiE** [comment]
This issue is nonexistent indeed! I had been following the instructions wrong. 

The fact that the instructions say: 
"Press and hold the "Azimuth" key until the red pointing circle appears." was misleading because no red pointing circle appears for me when pressing and holding down the azimuth key, but when I press the distance key. I had pressed the distance key because pressing it made the red circle appear after holding it down.

I would request that the Azimuth instructions be clarified to say "Press and hold the Azimuth key" instead of "Press and hold the azimuth key until the red pointing circle appears", as this pointing circle indeed does not appear.

Sorry for taking up your time.

**Comment by bux578** [comment]
@commy2 that's mostly the text from the manual:
![image](https://cloud.githubusercontent.com/assets/1235520/7609707/234c5184-f976-11e4-9b37-862b5f72f074.png)

Is it worth changing the function to mimic the reallife counterpart?

**Comment by commy2** [comment]
No. That makes no sense. The circle doesn't appear on the azimuth mode. They most likely fucked up the IRL manual.

**Comment by bux578** [comment]
>They most likely fucked up the IRL manual.

![image](https://cloud.githubusercontent.com/assets/1235520/7609804/2659dc10-f977-11e4-9252-63c023b7e118.png)

How do you know?

**Comment by NummiE** [comment]
My clanmate confirmed that IRL it works as it does in game, so its probably a fuckup in the IRL manual.

**Comment by bux578** [comment]
> a fuckup in the IRL manual

Military grade material... 

Could you please give me the proper wording and maybe check the other functions and I'll add it to the documentation?
