### ISSUE TITLE
Captivity problems

### ISSUE THREAD

**Issue by Play4FreeUA** [acemod/ACE3#1144]
Bots are standing up when you put them in boats. Instead of using an animation of sitting in the vehicle they use the one from while on the ground. So far I've only tested this with boats, but i'm sure there are other problems with vehicles.
You can't also get them to dismount from a boat. This isn't possible when both in it and in the water.
Another thing is that it's pretty hard to put someone in a vehicle (wounded or a captive) if there are many of them around. Good solution would be to implement selecting a vehicle to put someone into or first choosing a person and then a car that you need.

**Comment by jaynus** [comment]
Please update your ticket to this format: http://ace3mod.com/wiki/user/how-to-report-an-issue.html
