### ISSUE TITLE
3d models and icon updates

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#1147]
Note that this can be discussed on #models on slack.
Boxes will be ticked off when the model is marked as done [in the google sheet tasklist](https://docs.google.com/spreadsheets/d/1QbYfT1vDS1Yh6NbEQzoetYHGqGmhE4ljGah9zryk10Y/edit?usp=sharing)
### 1.1 High priority
- [ ]  Litter bandages basic redo
- [x] Litter gloves redo (highpoly->decentpoly)
- [x] Llitter_packingbandage.p3d redo (highpoly->decentpoly)
- [x] Redo Packing bandage Object. Too highpoly and creepy Textures
- [x] Litter QuickClot redo
- [ ] Litter bandages elastic redo
- [x] Bandage QuickClot redo
- [ ] Elastic Bandage redo
- [ ] Bandage Basic redo
- [ ] Litter bloodied clothes small
- [ ] Redo Tourniquet
### 1.2 Medium priority
- [ ] ACE Medical Crates
- [ ] Litter Epi/Morphine/Atropine Redo(Less Polys)
- [ ] Narcan Pen
### 1.3 Low priority
- [ ] Surgical Kit Redo? (highpoly->decentpoly)
- [ ] Redo Atropine UV/Texture(Object Posible)
- [ ] Redo BodyBagItem UV/Texture
- [ ] Redo Epinephrine UV/Texture(Object Posible)(Remove one of two textures:D)
- [ ] Redo Morphine UV/Texture(Object Posible)
### 2.1 High priority
- [ ] M26 Clacker
- [ ] Deadman switch
### 2.2 Medium priority
- [ ] .408 Suppressor M200 Intervention Rifle
- [x] microDAGR
- [ ] mk6 mortar
- [ ] Fulton MX-993 (Blufor) Flashlight
- [ ] KSF-1 (Opfor) Flashlight
- [ ] Maglite XL50 (Indep/Civ) Flashlight
### 2.3 Low priority
- [ ] Rolatube Expeditionary Tripod 
- [ ] Rolatube Expeditionary Hog Saddle
- [ ] flash suppressors for pistols
- [ ] flash suppressors for SMGs
- [ ] flash suppressors for rifles
- [ ] Mortar Aiming Posts redo ACE2
- [ ] Modern PRM-3 mine
- [ ] POMZ-2M mine
- [ ] Spike Rocket
- [ ] Bounce Imaging Explorer
### 3.1 Medium priority
- [ ] Non Steerable Parachute/Backpack
### 3.2 Low priority
- [ ] Reserve Parachute/Backpack
- [ ] Mobilephone
- [x] Spray Paint Can

**Comment by jokoho48** [comment]
#1799 first PR is rolling

**Comment by PaxJaromeMalues** [comment]
Refference for 3D modeling tasklist updated by team https://docs.google.com/spreadsheets/d/1QbYfT1vDS1Yh6NbEQzoetYHGqGmhE4ljGah9zryk10Y/edit?usp=sharing feel free to leave comments and suggestions, thanks.

**Comment by bux578** [comment]
So, what can be ticked of in the OP?

**Comment by alganthe** [comment]
OP updated

**Comment by SpaBsoldat** [comment]
Is this still current? If the "Spike Rocket" issue is what I think it is then it is still very much a present issue... The launcher is still completely unusable beyond a certain (tiny) range.

**Comment by dedmen** [comment]
>ACE Medical Crates

We have that afaik? so seems like not current.

>Rolatube Expeditionary Hog Saddle
Why? we already have a weapon tripod that works fine?

>Modern PRM-3 mine
You mean PMR-3?

Can you please update this list? Maybe also with links to where to find the "thing"? 
I'd love to try some of these.

**Comment by PaxJaromeMalues** [comment]
Oh thats the list from back in the days when I requested the #models channel in ACE Slack. After I and Joko left, it died down pretty fast and after early 2016 there has been no work done one any of the objects on this or the pinned list in the channel. Should be heavily out of date.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
