### ISSUE TITLE
Explosive Defusal

### ISSUE THREAD

**Issue by Twelvecaliber** [acemod/ACE3#1157]
Mods:

@cba_a3
@ace3

Placed ACE3 Modules:

None

Description: When placing an explosive from zeus, or having one scripted in there is no interaction available on the explosive and it subsequently cannot be defused.

Steps to reproduce:

- Go into zeus and place down an explosive charge.
-With defusal kit equip, approach and attempt to interact with the explosive charge.

Where did the issue occur?

Singleplayer
MP Client and dedicated.

**Comment by jaynus** [comment]
Is this placing ACE explosives in the editor? Vanilla explosives?

**Comment by legman** [comment]
After doing some testing I have also noticed that ZEUS placed IEDs and Explosives cannot be interacted with.

The IEDs are from the 'Interactive' part of the ZEUS item list - so vanilla!

IEDs placed by infantry via ammo boxes can be interacted with and detonated with dead mans and cell phone.

Another thing that would be fantastic would be adding the 'Pressure Plate' to the list of supported IED triggers so people can just walk over them to set them off.

Is that as simple as adding 'Pressure Plate' to the 'supportedTriggers=[]' array for the IED configs, as my clan really requires this for out next campaign we are beginning shortly?

Thanks for all your hard work - ACE3 is everything we wanted!

**Comment by legman** [comment]
Let me know if there is any more information I can provide to make your lives easier regarding this issue!

**Comment by PabstMirror** [comment]
We're only creating the `ACE_DefuseObject` object (which has the user actions) when user's manually plants the explosive.

Explosive's placed in editor on via `createVehicle` in game won't have these attached.

**Comment by esteldunedain** [comment]
Yes, explosives placed by Zeus are not hooked up with actions yet. We need to do a similar treatment as with Zeus frags.
