### ISSUE TITLE
git\bin and git\cmd system path error

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#1161]
For some reason I can't use make.py anymore, but it worked before.
Every time I launch make.py I get this error.
http://i.imgur.com/9MxTHSD.jpg
What variables should I create and what the values should be.
Thanks.

**Comment by jaynus** [comment]
git.exe needs to be in your path.

**Comment by rebelvg** [comment]
I don't see anything about git.exe in the build guide. Where should I get it? I can only guess it's windows github client but I'm not sure. It worked before without it.
So bin should point to the folder and cmd should point to the executable file? Am I right? Thanks.

**Comment by ViperMaul** [comment]
Which client are you using, GitHub for Windows, Git Bash, GitExtensions, TortoiseGit, SourceTree?
For you I see you are getting an assert error on gitpath which seems to state that it may not exist. Therefore. Try this...
1. go to a command prompt outside git shell. 
2. Then change directory to p:\z\ace\.git
3. Then type  `git rev-parse HEAD <ENTER>`
4. Then type path <ENTER>
Take a screen shot of both the change directory, the command and the results and attach here.

Also run this
5. Then take this make_test.py file attached and run it from p:\z\ace\tools
https://www.dropbox.com/s/3qs05il3nw0c2xi/make_test.py?dl=0 
__Let me know if there is a change in error message.__

**Comment by rebelvg** [comment]
I tried Github for windows and Git SCM before.
For some reason I can't change directory to p:\z\ace.
I'm running windows 7 as administrator.
Sorry, I have no idea how to use git. Never used it before.
That's what I get.
http://i.imgur.com/6ATIk9r.jpg
And that's what I get when I try to run make_test.py
http://i.imgur.com/B6nHhMX.jpg

**Comment by ViperMaul** [comment]
@rebelvg 
Then change directory to `p:\z\ace\.git` meant you need to actually be in that directory to run the command. The screen shot showed that you changed to a different path than requested. 
1. go to a command prompt outside git shell. 
2. Type `P: <ENTER>`
2. Then type `cd p:\z\ace\.git`
3. Make sure you are now in the hidden directory `.git` that is located under `p:\z\ace`
3. Then type  `git rev-parse HEAD <ENTER>`
Take a screen shot of the results. 

If you do not have a `cd p:\z\ace\.git` directory then your project folder is not setup correctly. 
And it is recommend that you go over the setup steps again and then run setup.py from the tools folder and try the above again. 
Every repository is expected to have a .git folder

**Comment by rebelvg** [comment]
Okay, I didn't have the .git folder.
I had no idea I should download this repository via git client and not just downloading master.zip
After downloading this via git clone command from git bash the make.py seems to work now.
Thanks.

**Comment by ViperMaul** [comment]
Yw
