### ISSUE TITLE
Documentation TODO list

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#1166]
Note that you can further discuss the matter in #Documentation on slack
A little tool that will greatly help you with formatting http://dillinger.io/
If you find an error on a pull request don't forget to point it out :)
Documentation guidelines http://ace3mod.com/wiki/development/Documentation%20guidelines%20and%20tips.html

post under this with what you want to do, would help organizing the work !

## Documentation TODO list
Docs | people assigned | linked pull requests | completion
--- | --- | --- | --- |
advanced ballistics |   |   | Done
ai |   |  | Done
aircraft |   |  | Done
apl |   |   | Done
atragmx |   |   | not ganthe
attach |   |  | Done
backpacks|   |  | Done
ballistics |  |  | Done
captives |   |  | Done
common | | | Done
concertina wire | | | Done
Dagr | | | Not ganthe
difficulties |   |  | Done
disarming |   |  | Done
disposable |   |  | Done
dragging |   |  | Done
explosives |   |  | Done|
fcs |  |  | Done
flashssuppressors |   |  | Done
frag |   |  | Done
gforces |   |  | Done
goggles |   |  | Done
grenades |   |  | Done
hearing |  |  | Done
hitreactions |  |  | Done
huntIR | | | Done
interact_menu |  |  | Done
interaction |  |  | Done
inventory |  |  | Done
javelin |  |  | Done
kestrel4500 |   |  | not ganthe
laser |  |  | Done
laser_selfdesignate |  |  | Done
laserpointer |  |  | Done
logistics_uavbattery |  |  | Done
logistics_wirecutter |  |  | Done
magazinerepack |  |  | Done
map |  |  | Done
maptools |  |  | Done
markers |  |  | Done
medical system |   | |On hold
microdagr |   |   | doc pass 8
missileguidance|   |  | Done
missionmodules|   |  | Done
mk6mortar |  |  | Done
modules | | | Doc pass 8
movement|   |  | Done
mx2a| | | Done
nametags |   |  | Done  
nightvision |   |  | Done
noidle |   |  | Done
noradio |   |  | Done
norearm |   |  | Done
optics |   |  | Done
optionsmenu |   |  | Done
overpressure |   |  | Done
overheating |   |  | Done
parachute |   |  | Done
protection |   |  | Done
ragdolls |   |  | Done
rangecard |  |  | Done
realisticnames |   |  | Done
recoil |   |  | Done
reload |   |  | Done
reloadlaunchers |   |  | Done
respawn |   |  | Done
safemode |   |  | Done
sandbag | | | Done
scopes |   |  | Done
smallarms |   |  | Done
spotting scope | | | Done
switch units |   |  | Done
tacticallader | | | Done
testmissions |   |  | Done
thermals |   |  | Done
tripod | | | Done
vector |   |   | Done
vehiclelock |  |  | Done
vehicles |   |  | Done
viewdistance |  |   | Done
weaponselect |   |  | Done
weather |   |   | Done
windeflection |  |   | Done
yardage450 | | | Done
zeus |  |   | Done
classnames | | | Up to date
module list | | | Up to date

**Comment by dharmab** [comment]
I'll start on ballistics and advanced ballistics. I'll get on slack after I get the invite approved.

Header formatting and American vs English spellings are already inconsistent across docs. A simple style guide might be helpful.

**Comment by dharmab** [comment]
Ballistics/Advanced Ballistics PR #1173

**Comment by dharmab** [comment]
Going to work on weaponselect next

**Comment by BullHorn7** [comment]
I don't want to break anything so I'll take the opportunity to learn all I can about the features by reading all of your documentation edits - and try to fix typos, grammar and other mistakes.

**Comment by alganthe** [comment]
writing a guide atm

**Comment by dharmab** [comment]
Weapon Select #1210

**Comment by BullHorn7** [comment]
I'll do Wind Deflection

**Comment by BullHorn7** [comment]
I'll look into Weather next

**Comment by alganthe** [comment]
Guidelines added please look at https://github.com/alganthe/ACE3ganthe/blob/documentation/documentation/development/Documentation%20guidelines%20and%20tips.md

**Comment by BullHorn7** [comment]
I'll do Vehicles next

**Comment by esteldunedain** [comment]
I merged #1231

**Comment by BullHorn7** [comment]
@alganthe what is the "order: 19" in the guideline? For example, I created a new file \documentation\missionmaker\classnames.md - what "order" should I give it in the beginning of the file?

**Comment by alganthe** [comment]
Goal for documentation pass 3 is:
hearing to markers

**Comment by alganthe** [comment]
Today will be the mk6 mortar doc.

**Comment by BullHorn7** [comment]
I did Smallarms and a bunch of proof-reading/typo-fixing/grammar-enhancing on everything from AB till Explosives (Not including APL and AtragMX). Will PR when i feel good about everything. :)

**Comment by BullHorn7** [comment]
Created installation guide, added images
I'm trying to get ahold of the people who created ace_zeus and ace_viewdistance to add them to the list.

**Comment by jonpas** [comment]
That would be @SilentSpike and @winter respectively, @BullHorn7

**Comment by BullHorn7** [comment]
View Distance PR'd: https://github.com/acemod/ACE3/pull/1366

**Comment by alganthe** [comment]
Documentation pass 6, will focus on the vector, MicroDAGR, rangecard and getting started pages.
I'll make Overheat doc a bit clearer about the bar and what it means.
I'll also add the rangecard item(s) in the classnames list.

**Comment by Tourorist** [comment]
For consistency sake, could we perhaps conform to the shortcut styles as I [declared](http://ace3mod.com/wiki/user/shortcuts.html) them:
* <kbd>Ctrl</kbd> vs <kbd>CTRL</kbd>
* <kbd>Page Down</kbd> vs <kbd>pageDOWN</kbd>
* etc.

**Comment by bux578** [comment]
^

**Comment by AlexanderViand** [comment]
The list above indicates that medical-system documentation is on hold. Does this mean the medical documentation for 3.2.0 will be the one that is currently on master/head? 

It still contains generic real-life descriptions that are not just unmodelled in ace but sometimes actually contradictory with how the system actually works. Example: Atropine's effect is dependent on patient heart rate not 'dosage' as the wiki suggests.

**Comment by alganthe** [comment]
^^ will do, updated the list.
