### ISSUE TITLE
Release builds / Nightly builds / CI

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#117]

**Comment by jaynus** [comment]
@jaynus and @KoffeinFlummi  to complete python script for releasing/building.

**Comment by meat147** [comment]
https://github.com/meat147/Mission-Version-Tool

Maybe you want to take use of these files.

**Comment by ViperMaul** [comment]
Meat has done an outstanding job with this already.

**Comment by jaynus** [comment]
I'm going to close this for now, since we are mostly set up and integrated.
