### ISSUE TITLE
The land of the mysteriously missing interact menus

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#1171]
RPT: http://pastebin.com/VvhUzYUj
Another RPT: http://pastebin.com/1NiZ57dE

Symptoms:
- This is consistently happening across all players @ UO with the modpack. It may/may not be mod pack related, but the conflict seems common enough to warrant investigation. 
- It is random, reconnects and/or reslots fix it. This means a preinit/postinit re-run fixes it.
- Units in tests are RHS units
- It cannot be file corruption or CBA issues, as the server is signed/modpacked/verified 

Thoughts on possible causes (checkbox is ruled out):
- [x] mods using the old CBA method are corrupting the keybinds (unlikely, ACRE still works)
- [] I tested excessive XEH times; that is *not* the cuplrit.
- [ ] XEH Initialization order
- [x] Somehow the objects are not tracking their interactions correctly
- [x] Interaction cache is getting corrupted or deleted 
- [x] RHS unit related issue for XEH initializers for the actions
- [ ] ????????? @esteldunedain  help me out here bud

**Comment by esteldunedain** [comment]
My best bet is still XEH_postInit running on sched environment and getting cut off while compiling the menu (which is quite big). I'll try reusing the same menu for all men to cut down init time

**Comment by jaynus** [comment]
I ran a test with 99999 loop XEHs. They took 10+ minutes to load but interact still worked. Is XEH scheduled only on JIP?

**Comment by esteldunedain** [comment]
> Is XEH scheduled only on JIP?

As far as I understand cba code, it's only scheduled if respawn is set on the mission. There might be other conditions too.

**Comment by jaynus** [comment]
Okay. I'll run all the cases and try.

**Comment by alganthe** [comment]
the module backpacks is missing the whole interaction system it needs to be added.

**Comment by jaynus** [comment]
That has nothing to do with this bug. File a seperate one please.

**Comment by jaynus** [comment]
This is appearing to be related with CBA XEH becoming scheduled on CAManBase, and then bypassing hte player check if > 10 seconds

**Comment by jaynus** [comment]
http://bit.ly/1HcwXLX RC7 build of CBA with possible fix.

**Comment by Overlord00** [comment]
United Operations is still experiencing this issue.

**Comment by SilentSpike** [comment]
Can you be any more specific on that?

**Comment by Overlord00** [comment]
Users report not having ACE interaction at the beginning of missions. We have been able to mitigate the issue by running a piece of code provided to us by Jaynus at the beginning of every mission.

> [] call compile preprocessFileLineNumbers "\z\ace\addons\interact_menu\XEH_clientInit.sqf";

**Comment by alganthe** [comment]
latest version of CBA, ACE3 and RHS in our community here, never had those issues.
Do you have a list of the mods that you use for an easier time comparing ?

**Comment by Overlord00** [comment]
United Operations runs the following mods: 

@UOMODS_A3
@UOMAPS_A3
@CBA_A3
@ACRE2
@ACE

UOmods contains the RHS stuff and a few other in house add ons. UOmaps is mostly AllInArmaTerrainPack and a few others.

**Comment by PabstMirror** [comment]
This still may be an issue, I am hoping #2623 will fix this.

@Overlord00 
For next release, please test if you still need to manually call `interact_menu\XEH_clientInit.sqf`
If this is fixed, calling that a 2nd time may do some weird things, like possibly installing render twice.

**Comment by Overlord00** [comment]
@PabstMIrror

United Operations is currently running ACE 3.3.2, and as far as I'm aware, we have not had any issues with ACE interact since we updated. I will confirm this during today's play session.

**Comment by Overlord00** [comment]
@PabstMirror

We had 50 people on the server Friday and Saturday. I received no reports of ACE interact failing to initialize for any of our users. I believe that this issue has been resolved.
