### ISSUE TITLE
can't work make.py when using outside git shell

### ISSUE THREAD

**Issue by Arkblade2015** [acemod/ACE3#1174]
can't work make.py when using outside git shell.
path already set and "git" command will work.

error:
"subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128"

**Comment by jaynus** [comment]
git needs to be in your PATH environmental variable.

**Comment by Arkblade2015** [comment]
PATH already set. and "git" command will work.
however don't work from windows command prompt.
