### ISSUE TITLE
Missile guidance broken on A3 APC

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#1175]
ACE3 Version: master 560d6f09a02898e40c12e43f01347a4f9273f105

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None

**Description:**
`O_APC_Tracked_02_cannon_F` and `I_APC_Wheeled_03_cannon_F` both have weapon `missiles_titan` which shoots magazine `2Rnd_GAT_missiles` which is ammo `M_Titan_AT`

Missle guidance is enabled for the `M_Titan_AT`, but everything is junk data, so the missle just shoots into the sky.

**Steps to reproduce:**
* Get into `O_APC_Tracked_02_cannon_F` (BM-2T)
* Lock "Mini-Spike" on target (vanilla arma system) 
* Fire - Missle goes up into the air and never hits target

**RPT log file:**
```
fnc_onFired.sqf:13","EXPLODE_7 _this: _shooter=B Alpha 4-3:1 (Pabst Mirror) (R1), _weapon=missiles_titan, _muzzle=missiles_titan, _mode=missiles_titan, _ammo=M_Titan_AT, _magazine=2Rnd_GAT_missiles, _projectile=164280: titan_missile_at_fly.p3d"]
fnc_onFired.sqf:46","Begin guidance:  _target=any,  _seekerType=any,  _attackProfile=any"]
fnc_onFired.sqf:88","Beginning ACE guidance system: _target=any, _ammo=M_Titan_AT, _seekerType=Optic, _attackProfile=JAV_TOP"]
```

I noticed the problem with the mod @DAR_HMMWV TOW-HMMVs but the issue is reproducible in vanilla.

I'm thinking we should just create our own M_Titan_AT ammo/magazines classes specificly for the javelin/spike.

**Comment by jaynus** [comment]
Yes. This is yet another inheritance problem.
