### ISSUE TITLE
can't work make.py when using outside git shell (from window command prompt)

### ISSUE THREAD

**Issue by Arkblade2015** [acemod/ACE3#1176]
can't work make.py when using outside git shell.
path already set and "git" command will work.

error:
"Invalid symlink 'P:\z\ace': Function not implemented "
it strange. of course already have P drive and symlinks.
i suspect http://git.661346.n2.nabble.com/git-clone-doesn-t-work-in-symlink-dir-roots-on-Windows-td7593620.html is similar problem.

"subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128"

impotant:
i'm already set PATH !!! and "git" command work normally !!!
and can build normally when use build.py
and can build normally when use make.py from git shell !

however make.py don't work from windows command prompt.
of course everything fine prior https://github.com/acemod/ACE3/commit/97105c5b0761018f1424efa8e0e72e522a4b7337

**Comment by jaynus** [comment]
@ViperMaul  @KoffeinFlummi

**Comment by ViperMaul** [comment]
@Arkblade2015 
We will make this better in future versions. 
For now do the follow manual test
1. go to a command prompt outside git shell. 
2. Then change directory to p:\z\ace\.git
3. Then type  `git rev-parse HEAD <ENTER>`
copy and paste the results here.

**Comment by Arkblade2015** [comment]
>2. Then change directory to p:\z\ace.git
it didn't mean "p:\z\ace\.git" ?

screenshot is below

**Comment by ramius86** [comment]
you set both git and cmd ? what are your path system variables? check if both C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd are added

**Comment by Arkblade2015** [comment]
already tested, and doesn't help that.
to begin with, Github don't make anything to C:\Program Files (x86)\Git\bin and C:\Program Files (x86)\Git\cmd.
Github make their assets to C:\Users\<usename>\AppData\Local\GitHub\PortableGit<userid>.

**Comment by ramius86** [comment]
Mine are there ... C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd and in fact is working

**Comment by jonpas** [comment]
You're messing up Git and GitHub apparently.

**Comment by ramius86** [comment]
Ah didnt noticed you are using github software, I'm not using, is very annoying :)

**Comment by ViperMaul** [comment]
@Arkblade2015  
I am trying to discover why you get that symlink error and others do not. 
Also I currently only see one difference between the code before and after at the moment. 

__Please do the following in order.__ 
1. Go to a command prompt outside git shell.
2. Then change directory to p:\
3. Then type `dir /A:L /S <ENTER>`
4. Then type `ver <ENTER>`
5. Then type `path <ENTER>`
__Take a screen shot of the results and attach here.__ 
6. Then take this make_test.py file attached and run it from p:\z\ace\tools
https://www.dropbox.com/s/3qs05il3nw0c2xi/make_test.py?dl=0 
__Let me know if there is a change in error message.__ 

And finally show me the command or method you used to create your Symlink to your ace3 repo directory.

**Comment by Arkblade2015** [comment]
i only using official document method.
mklink /D "[Arma 3 installation folder]\z\ace" "[location of the ACE3 project]"
mklink /D "P:\z\ace" "[location of the ACE3 project]"

screenshots:
![test3](https://cloud.githubusercontent.com/assets/11951625/7665971/972ddc34-fc0b-11e4-93a3-bec769ca055e.jpg)
![test4](https://cloud.githubusercontent.com/assets/11951625/7665972/99740112-fc0b-11e4-991f-45ae7cd34f49.jpg)
![test5](https://cloud.githubusercontent.com/assets/11951625/7665973/9b468e88-fc0b-11e4-8201-441934ddadbc.jpg)

**Comment by ViperMaul** [comment]
@Arkblade2015 
GIT sometimes has a problem with symlinks I have found. 
Try recreating your sysmlinks using Junctions
`mklink /J "[Arma 3 installation folder]\z\ace" "[location of the ACE3 project]"`
`mklink /J "P:\z\ace" "[location of the ACE3 project]"`

Reference: https://github.com/msysgit/msysgit/wiki/Why-am-I-getting-fatal-Invalid-symlink-....-Function-not-supported.-error-when-initcloneing

**Comment by ViperMaul** [comment]
@Arkblade2015 
After doing some research, I love how github for windows is hard to find its location programmatically. Also try this new make_test.py https://www.dropbox.com/s/3qs05il3nw0c2xi/make_test.py?dl=0 
And screen shots the results. I hope to not have to use this version. But let me know.

**Comment by PabstMirror** [comment]
@Arkblade2015 , no reason you can't have github for windows and install a proper command line git as well http://git-scm.com/download/win

**Comment by Arkblade2015** [comment]
still can't using make_test.py.
![test1](https://cloud.githubusercontent.com/assets/11951625/7677605/7900cfb8-fd88-11e4-9b6e-44f0916ebb4a.jpg)

**Comment by Arkblade2015** [comment]
ok, new mklink method
mklink /D /J "[Arma 3 installation folder]\z\ace" "[location of the ACE3 project]"
mklink /D /J "P:\z\ace" "[location of the ACE3 project]"
made make.py and make_test.py both work.

we need to change installation documents.

**Comment by KoffeinFlummi** [comment]
Are you running Windows 8? The issue with junctions is described in the documentation: http://ace3mod.com/wiki/development/setting-up-the-development-environment.html#4.1-manual-setup

**Comment by Arkblade2015** [comment]
windows 7 64bit.
So the document is incorrect.

**Comment by rebelvg** [comment]
Can someone please help me.
I'm still getting this same error.
http://i.imgur.com/9MxTHSD.jpg
I installed git scm and checked the path variable. All paths are there and if I call git via cmd it will open.
Tried the new mklink thingy and still no progress.

**Comment by ViperMaul** [comment]
@rebelvg 
Your error message is different. You need to create a new issue. 
The trouble shooting steps given here will be the same used in your issue. 
Please create a new issue thread.

**Comment by rebelvg** [comment]
@ViperMaul I made a ticket but it was closed without any real answer.
https://github.com/acemod/ACE3/issues/1161#event-304376165
