### ISSUE TITLE
BFT frame drop on update

### ISSUE THREAD

**Issue by Astavinu** [acemod/ACE3#1181]
i got a frame drop of ~30 fps when blue force tracking updates. does anyone else experience this?
i am not able to reproduce this in the editor.

Measured using
[]spawn{frames = true;while{frames} do {hintSilent format["%1", round diag_fps];sleep 0.05;}}

Symptoms:
screen freezes for ~0.1 sec exactly when the map markers update their position

Steps to reproduce:
1. create mission with BFT Module
2. load it on a dedicated Server
3. play

**Comment by esteldunedain** [comment]
We've had a previous report of this, but it got fixed when restarting the mission and we couldn't repro anymore (@bux). My guess is that's totally unrelated to the bft (other things are calculated on 1 sec intervals too).

**Comment by esteldunedain** [comment]
BTW; please follow this instructions for reporting issues: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

Edit the report above to comply; we specially need the rpt log

**Comment by Astavinu** [comment]
is there any way to disable bft or change the update interval? tried to change ace_map_bft_interval at runtime :p

**Comment by PabstMirror** [comment]
`ace_map_BFT_markers` was never getting reset, and we added new marker string to the array each update.

With 45 groups, after 3 minutes `count ace_map_BFT_markers` = 8100 and was taking 
`4.39136s / 284 = 15.4625ms`. After an hour it would be pretty bad.

after fix, 45 groups seemed to stay arround 5.5ms.

You can change `ace_map_BFT_Interval` on the module, but can't change it at runtime because it's only used at start.

**Comment by esteldunedain** [comment]
Nice find @PabstMirror, gj!

**Comment by bux578** [comment]
That could really be the cause of the frame drops I was experiencing.

**Comment by jaynus** [comment]
> 5.5ms

Thats really bad....can you point me to this code? What is it doing? It sounds like it needs some faster string functions tbh.

**Comment by PabstMirror** [comment]
`map/functions/fnc_blueForceTrackingUpdate.sqf`
that's with 45 groups, which should be untypically high

**Comment by esteldunedain** [comment]
Yes, 5.5 ms seems high, but it's only done one frame a sec.
