### ISSUE TITLE
Opfor IFV Stalker use Mini-spike instead of anti-Nato counterpart missile.

### ISSUE THREAD

**Issue by cych** [acemod/ACE3#1182]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @RHS Escalation
* @smd_Sahrani_A3

**Placed ACE3 Modules**:
none

**Description:**
Minispike is supposed to be a Blufor Missile, why does it's been used by Opfor side ?

**Steps to reproduce**:
spawn a stalker, get in gunner, you can use Mini-Spike.

**Where did the issue occur?**
mission editor.

**RPT log file:**
-

**Comment by jaynus** [comment]
This is the way BI decided to do future.

**Comment by bux578** [comment]
> This is the way BI decided to do future.

Made me chuckle.
