### ISSUE TITLE
Cant turn on / off vehicle engines with button 1 / 2

### ISSUE THREAD

**Issue by Meiestrix** [acemod/ACE3#1187]
ACE3 Version: 3.0.0 

**Mods:**
* @cba_a3
* @ace3
*@RHS
*@TFAR
*@BWMOD

**Placed ACE3 Modules:**
* *Even with no modules, you cant turn on / off the engines*

**Description:**
When you are on the driver seat in a vehicle you cant turn on / off the egine with the number keys 1 / 2.
Everything else with the number keys works fine, like switching weapons and grenades,

**Steps to reproduce:**
* *Go in a vehicle as driver and press 1 / 2*

**Where did the issue occur?**
*On a Multiplayer server*

**Comment by nic547** [comment]
http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by PabstMirror** [comment]
canInteractWith was failing,
This also fixes issue with vehicle weapon select not working.

**Comment by Meiestrix** [comment]
Is this change not implemented in 3.0.1?

**Comment by PabstMirror** [comment]
This didn't make the hotfix, will be fixed next release.

**Comment by Meiestrix** [comment]
@PabstMirror 
Okay, thank you.
I just was confussed because the issue was closed, and nothing changed.
