### ISSUE TITLE
XM307 tripod HMG can't be zeroed at more than 1000m.

### ISSUE THREAD

**Issue by cych** [acemod/ACE3#1188]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @RHS Escalation
* @smd_Sahrani_A3

**Placed ACE3 Modules**:
none

**Description:**
-the XM307 is supposed to have an effective range of 2000m.  the zeroing should be adjustable up to this distance.

**Steps to reproduce**:
place a xm307 tripod weapon, enter it a gunner, your zeroing is limited to 1000m.

**Where did the issue occur?**
mission editor.

**RPT log file:**

**Comment by ulteq** [comment]
The vanilla class is called `GMG_01_base_F`.

The vanilla zero settings are:
```discreteDistance[] = {100,200,300,400,600,800,1000};```
```discreteDistanceInitIndex = 2;```

My attempt to fix it failed.

**Comment by esteldunedain** [comment]
I think we should give the XM307 a FCS and be done with it

**Comment by jaynus** [comment]
Doesn't it basically have a FCS?

**Comment by esteldunedain** [comment]
No, it currently only has a range finder, but it doesn't adjust range according to it.

If assigned, the ACE_FCS takes over the range adjusting keys an let's you adjust to whatever range you want, plus obviously allowing you to also adjust automatically to the rangefinder distance.

**Comment by jaynus** [comment]
Lets just do that, its a future weapon anyways. @ulteq

**Comment by ulteq** [comment]
> I think we should give the XM307 a FCS and be done with it

:+1:

**Comment by commy2** [comment]
Machine guns can't be zeroed above 1.6 or 1.7 km (can't remember which one). Might be possible if they were compatible with the FCS though.
