### ISSUE TITLE
Cannot interact with vehicles to change tyres, access gear etc.

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#1189]
ACE3 Version: 3.0.0.3tstable ( latest from pw6 14.05.2015 )

Mods:
@cba_a3
@ace3
@rhsusaf3
@rhsrfaf3
@mcc_sandbox
@aia_tp

Placed ACE3 Modules:
_center = createCenter sideLogic;
_group = createGroup _center;
_module = _group createUnit ["ACE_ModuleRespawn", [0,0,0],[],0.5,"NONE"];
_module = _group createUnit ["ACE_moduleMedicalSettings", [0,0,0],[],0.5,"NONE"];
_module = _group createUnit ["ACE_moduleTreatmentSettings", [0,0,0],[],0.5,"NONE"];

Description:
I can interact with other units. With other players and even with the ace medical boxes, but not with any vehicles.

Steps to reproduce:
next to a vehicle using the interacton key,
try to change tyres,
can't!

Where did the issue occur?*
Multiplayer, playing on dedicated Server.
Also occurs everywhere else.

RPT log file:
Don't think it's neccessary!

**Comment by xJenny99x** [comment]
Was this feature not copy - pasta from agm?

**Comment by esteldunedain** [comment]
It's not merged yet! There no vehicle repairing on ACE yet! Neither are logistics

**Comment by Neodyn** [comment]
Are you planning to impliment this option again in ACE 3?

**Comment by esteldunedain** [comment]
Sure

**Comment by xJenny99x** [comment]
T-t-t-today?
