### ISSUE TITLE
the tripod .50cal XM312 uses 600rds mag instead of 100 rds mag.

### ISSUE THREAD

**Issue by cych** [acemod/ACE3#1190]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @RHS Escalation
* @smd_Sahrani_A3

**Placed ACE3 Modules**:
none

**Description:**
the tripod XM312 has a rof of 300rpm, and ingame it's able to fire during 2 entire minutes, meaning it has a 600 rds mag. which is not at all realistic compared to the magazine size it uses. make it uses the M2 100rds mag.

**Steps to reproduce**:
place a xm312 tripod weapon, enter it a gunner, fire during 2 min.

**Where did the issue occur?**
mission editor.

**RPT log file:**
-

**Comment by ulteq** [comment]
You're right, but I don't know if we can change this without breaking other things.

**Comment by commy2** [comment]
Seems reasonable.

**Comment by commy2** [comment]
FYI: Those are 500Rnd mags.
