### ISSUE TITLE
Add different IED types, triggerable via pressure plate

### ISSUE THREAD

**Issue by legman** [acemod/ACE3#1191]
**Mods:**
@cba_a3
@ace3

**Placed ACE3 Modules:**
ace3_explosives

**Description:**
You can arm an IED with a cellphone, dead mans switch but not with a pressure plate.

**Steps to reproduce:**
Create a new mission, place a single explosives specialist unit and add a vanilla IED to his inventory - preview the mission and place it via from your inventory using the self interaction menu. From then you can only pickup the IED, but not arm with a pressure plate.

I took a look in the config and it looks like the issue could be resolved by adding 'Pressure Plate' to the 'supportedTriggers' array for each of the vanilla IED definitions that ACE3 modifies. There is currently only [Cellphone, Deadmans Switch].

**Where did the issue occur?:**
Singleplayer
MP Client and dedicated

**Comment by esteldunedain** [comment]
I think that's by design, cause pressure plates are not that usual for ieds. We probably need to add different types of IED at some point though, with different capabilities.

I'm renaming the ticket for that, but don't expect it anytime soon.

**Comment by legman** [comment]
I respect your decision - but I would like to disagree and say that the majority of IEDs are triggered with pressure plates & you would find that cellphone, major cable detonation would be secondary.

If I modified the 'supportedTriggers' array would that allow me and my clan to use pressure plates on IEDs as we require it for our upcoming campaign.

Thanks

**Comment by CorruptedHeart** [comment]
Changes you'd need to do:
```
        class ACE_Triggers {
            SupportedTriggers[] = {"Command","DeadmanSwitch", "Cellphone","PressurePlate"};
            class Command {
                FuseTime = 0.5;
            };
            class DeadmanSwitch:Command{};
            class Cellphone:Command{};
            class PressurePlate{
                displayName = "PressurePlate";
                digDistance = 0;
                ammo = "SLAMDirectionalMine_Magnetic_Ammo"; // Will need to ensure a CfgAmmo class exists for the IED type that has the correct Trigger Type according to Arma's CfgMineTriggers for pressureplate stuff.
                pitch = 0;
            };
        };
```

**Comment by esteldunedain** [comment]
@CorruptedHeart, wouldn't that mean that the ied turns into a SLAM when the pressure plate is selected?

**Comment by legman** [comment]
That is awesome *CorruptedHeart*, thanks mate!

I will create a patch mod for my lads to use until the future IEDs are implemented.

**Comment by CorruptedHeart** [comment]
@esteldunedain indeed, that's why there is a comment there
`// Will need to ensure a CfgAmmo class exists for the IED type that has the correct Trigger Type according to Arma's CfgMineTriggers for pressureplate stuff.`
The `ammo` entry needs to be set to an IED CfgAmmo class that is setup for pressure plates as part of it's trigger type.

**Comment by ESUSSanchez** [comment]
+1 @legman

**Comment by legman** [comment]
As stated above I have created a tiny patch mod that allows you to attach pressure plates to IEDs. I thought I would post this here just in case anyone finds this useful until further IED functionality is added by the ACE3 team!

https://dl.dropboxusercontent.com/u/65237306/%40lm_immersive_ieds.rar

**Comment by jonpas** [comment]
Awesome @legman I'll PR it in a bit.
