### ISSUE TITLE
Deception

### ISSUE THREAD

**Issue by sagjangi** [acemod/ACE3#1197]
This might not be possible but I think its a cool idea non the less. If you are wearing civilian clothes, rig, hat, backpack, etc.. and you do not have a weapon then rival AI factions will not engage you. A holstered (i.e. concealed) pistol could have the same effect but not a slung rifle (still visible). This could make COOPs and TvT scenarios integrating AI really interesting.

**Comment by jonpas** [comment]
#414, please follow http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
