### ISSUE TITLE
Nametag visibility at night

### ISSUE THREAD

**Issue by beiita** [acemod/ACE3#1200]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* Various maps
* Various unit/vehicle mods

**Placed ACE3 Modules:**
None

**Description:**
When using the nametags at night, with no night vision, you can observe the unit nametags at the same distance as during the day. In game, you cannot make out the unit the nametag is identifying.

**Steps to reproduce:**
Place a variety of units for nametags, set the date to a night with no moon illumination, best effect if it is also overcast/cloudy.

**Where did the issue occur?**
Multiplayer, Singleplayer

**RPT log file:**
http://pastebin.com/WzcrEeFQ

**Comment by jaynus** [comment]
#414 plus leaving it open because you took the time to follow the format at least.
