### ISSUE TITLE
nametags causing script errors

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#1201]
http://pastebin.com/wUznN0wm

**Comment by Overlord00** [comment]
Here is a fully copy of my local RPT and a copy of the .pbo

https://www.dropbox.com/s/azth5s70m55pefv/Downloads.rar?dl=0

**Comment by esteldunedain** [comment]
@PabstMirror, @jaynus, @Glowbal, this is caused by color settings being nil again. Why is this happening now while it didn't used to happen before?

**Comment by jaynus** [comment]
> Why is this happening now while it didn't used to happen before?

Because no one ever tested with the forceAllSettings = 1 for client side settings.

**Comment by esteldunedain** [comment]
> Because no one ever tested with the forceAllSettings = 1 for client side settings.

True; we fell for relying on settings existing on postinit at various places apparently

**Comment by jaynus** [comment]
Closing. This was fixed in hotfix.
