### ISSUE TITLE
[BIS_fnc_moduleExecute] cannot execute module, error found in 'ace_explosives_fnc_module'

### ISSUE THREAD

**Issue by legman** [acemod/ACE3#1212]
**Mods:**
@cba_a3
@ace3

**Placed ACE3 Modules:**
ace3_explosives

**Description:**
"[BIS_fnc_moduleExecute] cannot execute module, error found in 'ace_explosives_fnc_module'" error occurs when using ace3_explosives module in editor.

**Steps to reproduce:**
Enable 'showScriptErrors', open new editor mission, place player, place 'ace3_explosives module'. Preview the mission and error occurs.

Had a few friends try and they got the same result.

**Where did the issue occur?:**
Editor

**Comment by PabstMirror** [comment]
Module wasn't prep'ed in preInit, fixed.
