### ISSUE TITLE
ACE3 Classnames not documented/not available.

### ISSUE THREAD

**Issue by AndrewKopczynski** [acemod/ACE3#1215]
I checked the BI Studios forums, the ACE3 wiki, and the GitHub files and couldn't find any documentation for the classnames of items used in ACE3.

I read on a forum post on some random forum while Googling saying that documentation was in an excel spreadsheet inside "@ace3/documentation/references", but didn't find any such files (in both the GitHub download linked on the forums, and in the Armaholic downloads).

Where can I find a list of classnames for the items provided in ACE3?

**Comment by jaynus** [comment]
There is no documentation for this as yet, our contributors are hard at work: #1166

**Comment by 5kyw4Lk3r** [comment]
so I've been using this script , arma3.de/include.php?path=download&contentid=3238 ,which basically shows u the class names of any object in u'r inventory,so all u gotta do is go to the virtual armory load up on ace 3 based hear and vualla u got the class names. it even copies to clipboard so u don't have to re type on u'r script editor. hope I helped. g'luck

**Comment by 5kyw4Lk3r** [comment]
kinda obvious but I meant gear not hear.just looks weird.
