### ISSUE TITLE
Tank cookoff feature request 

### ISSUE THREAD

**Issue by Grrenhorn007** [acemod/ACE3#1216]
The tank cookoff from AGM was just amazing.
I want it in Ace 3, pls ;)

**Comment by jaynus** [comment]
Vehicle damage is already in the works. Please follow the feature request guidelines: #414 

https://www.youtube.com/watch?v=h_J7bSdC3LI

http://i.imgur.com/o9aWFiX.png

**Comment by sargken** [comment]
Is this compatable with mods like RHS

**Comment by jaynus** [comment]
ACE Advanced Vehicle Damage is available for mod makers and content providers to utilize to extend and refine their damage system if they choose. It will also apply, at a less detailed level, to anything utilizing the vanilla VD system. However, RHS I believe will be implementing their own system which will be incompatible.
