### ISSUE TITLE
Vector - Azimuth not working?

### ISSUE THREAD

**Issue by MrSanchez** [acemod/ACE3#1225]
ACE3 Version: 3.0.0.3 tstable

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
Noany

**Description:**
I place myself as a sniper on the editor, no modules, i use my range finder, hold R, range displays, press TAB, nothing. Hold TAB, nothing? Am I doing something wrong?

**Steps to reproduce:**
Sp editor..place as sniper...use rangefinder, hold tab and release it.
edit: spawn rangefinder using Arsenal, the vector that is.

**Where did the issue occur?**
"Singleplayer"*

**RPT log file:**
http://pastebin.com/UncJeiUJ

There ya go.

Kind regards,
Sanchez

**Comment by Winter259** [comment]
Possibly related to #1143 ?

**Comment by jonpas** [comment]
Please follow [issue reporting guidelines](http://ace3mod.com/wiki/user/how-to-report-an-issue.html).

**Comment by MrSanchez** [comment]
Updated.

**Comment by alganthe** [comment]
After testing it does work

**Comment by MrSanchez** [comment]
I'll be able to upload a video of this issue tomorrow.

**Comment by alganthe** [comment]
Follow the instructions of the wiki, it's working as intended, aka without an issue.

**Comment by esteldunedain** [comment]
@MrSanchez, I hope you are not confusing the Vector with the vanilla rangefinder. They are sepparate items.

**Comment by MrSanchez** [comment]
Ofcourse I'm not confusing the vector with the vanilla rangefinder..lol.

Holding R and releasing it works, even tapping R once and then holding it shows the range + height difference as the instructions on the wiki say. However, anything related to azimuth (TAB), is a nope.
:/

**Comment by alganthe** [comment]
you might have keybinds issues, I don't have anything on my end, nor anyone from my community.

**Comment by esteldunedain** [comment]
@MrSanchez, rebind that key to something other than `Tab` and retest please.

**Comment by MrSanchez** [comment]
Will do later tonight.
