### ISSUE TITLE
Weight and size of PAK and Surgical Kit

### ISSUE THREAD

**Issue by MeFirst** [acemod/ACE3#1226]
Not exactly a "feature" but I think the size and the weight of those two items should be adjustet. Roght now the PAK weights 0.2lb and the Surgical Kit 0.5lb. They also take minimal space in the inventory. Those items should be larger and heavier. Otherwise the option to make those items consumables is a bit pointless, because a player can carry insane ammounts of those items.

**Comment by esteldunedain** [comment]
I don't have RL data for this, but those values should probably be between 1 and 2 lb. Volume on the inventory is treated proportional to weight in arma, so increasing weight would automatically decrease the amount of those items you can carry.

I'm leaving this around, but use #414 next time.
