### ISSUE TITLE
Surgical Kit Uses

### ISSUE THREAD

**Issue by headedhorseman101** [acemod/ACE3#1227]
What exactly are the uses for the surgical kit, or have the not been implemented yet. I was unable to determine through testing (on AI only) and not on medical documents on website.

**Comment by alganthe** [comment]
First use [this form] (http://ace3mod.com/wiki/user/how-to-report-an-issue.html)
Second, the documentation is being written atm.

**Comment by headedhorseman101** [comment]
>First use this form

It isn't a bug report. It's a question. They are allowed.

>Second, the documentation is being written atm.

I know. I was just asking if surgical kits have been implemented it not.

**Comment by xJenny99x** [comment]
I think they are used to sew up wounds so they won't reopen anymore, when advanced wounds are enabled.

**Comment by headedhorseman101** [comment]
Thanks for the feedback. Is it only players, or does it work on AI as well?

**Comment by xJenny99x** [comment]
I believe that's a setting in one of the ace 3 modules
