### ISSUE TITLE
Prevent player death while unconscious

### ISSUE THREAD

**Issue by Zycorge** [acemod/ACE3#1229]
Can you add a module option to prevent the death of a Human Player while they are unconscious?

**Comment by jaynus** [comment]
Please follow the guide for feature requests: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html

#414

**Comment by PabstMirror** [comment]
Under Ace Medical, check the Revive Settings module.

That should prevent death while uncoced for a given time.
