### ISSUE TITLE
Cannot find the equivalent to AGM_Interaction_fnc_addInteraction

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#1232]
Did this get copy pasted from agm? 

How can I add mission specific actions to the ACE interaction and ACE self-interaction menus?

**Comment by esteldunedain** [comment]
Add an interaction to a class:
```
myaction = ["Talk","Talk","",{hint "Hello"},{true},{}] call ace_interact_menu_fnc_createAction;
[MyUnitClass, 0, ["ACE_MainActions"], myaction] call ace_interact_menu_fnc_addActionToClass;
```
Add a couple of Self Interactions to an specific object (the player):
```
myaction = ['TestAction 1','Test','',{hint 'test';},{true}] call ace_interact_menu_fnc_createAction;
[player, 1, ["ACE_SelfActions"], myaction] call ace_interact_menu_fnc_addActionToObject;

myaction = ['TestAction 2','Test 2','',{hint 'test 2';},{true}] call ace_interact_menu_fnc_createAction;
[player, 1, ["ACE_SelfActions", "TestAction 1"], myaction] call ace_interact_menu_fnc_addActionToObject;
```

For more details:
* Read: http://forums.unitedoperations.net/index.php/topic/25042-ace-custom-interactions/
* Hop onto the public slack chat
* Wait for proper documentation to be published

**Note**:
Adding interactions to **objects doesn't work properly on the first release version**, but it's fixed on the current master. Adding interaction to **classes works allrigth in both versions**.
