### ISSUE TITLE
Glitching items into the player moves them over the map

### ISSUE THREAD

**Issue by Raspu86** [acemod/ACE3#1234]
CE3 Version: 3.0.0
**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *class ace_common_forceAllSettings {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_frag_enabled {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_interaction_EnableTeamManagement {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_magazinerepack_TimePerAmmo {
    value = 1.5;
    typeName = "SCALAR";
    force = 0;
};
class ace_magazinerepack_TimePerMagazine {
    value = 2;
    typeName = "SCALAR";
    force = 0;
};
class ace_magazinerepack_TimePerBeltLink {
    value = 8;
    typeName = "SCALAR";
    force = 0;
};
class ace_maptools_EveryoneCanDrawOnBriefing {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_microdagr_MapDataAvailable {
    value = 1;
    typeName = "SCALAR";
    force = 0;
};
class ace_mk6mortar_airResistanceEnabled {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_mk6mortar_allowComputerRangefinder {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_mk6mortar_allowCompass {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_nametags_showCursorTagForVehicles {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_nametags_PlayerNamesViewDistance {
    value = 5;
    typeName = "SCALAR";
    force = 0;
};
class ace_nametags_PlayerNamesMaxAlpha {
    value = 0.8;
    typeName = "SCALAR";
    force = 0;
};
class ace_respawn_SavePreDeathGear {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_respawn_RemoveDeadBodiesDisconnected {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_respawn_BodyRemoveTimer {
    value = 0;
    typeName = "SCALAR";
    force = 0;
};
class ace_switchunits_EnableSwitchUnits {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_switchunits_SwitchToWest {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_switchunits_SwitchToEast {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_switchunits_SwitchToIndependent {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_switchunits_SwitchToCivilian {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_switchunits_EnableSafeZone {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_switchunits_SafeZoneRadius {
    value = 100;
    typeName = "SCALAR";
    force = 0;
};
class ace_vehiclelock_DefaultLockpickStrength {
    value = 10;
    typeName = "SCALAR";
    force = 0;
};
class ace_vehiclelock_LockVehicleInventory {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_vehiclelock_VehicleStartingLockState {
    value = -1;
    typeName = "SCALAR";
    force = 0;
};
class ace_weather_enableServerController {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_weather_useACEWeather {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_weather_syncRain {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_weather_syncWind {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_weather_syncMisc {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_weather_serverUpdateInterval {
    value = 60;
    typeName = "SCALAR";
    force = 0;
};
class ace_winddeflection_enabled {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_winddeflection_vehicleEnabled {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_winddeflection_simulationInterval {
    value = 0.05;
    typeName = "SCALAR";
    force = 0;
};
class ace_winddeflection_simulationRadius {
    value = 3000;
    typeName = "SCALAR";
    force = 0;
};
class ace_explosives_RequireSpecialist {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_explosives_PunishNonSpecialists {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_hearing_EnableCombatDeafness {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_hearing_EarplugsVolume {
    value = 0.5;
    typeName = "SCALAR";
    force = 0;
};
class ace_hearing_UnconsciousnessVolume {
    value = 0.4;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_level {
    value = 1;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_medicSetting {
    value = 2;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_enableFor {
    value = 1;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_enableOverdosing {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_bleedingCoefficient {
    value = 1;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_painCoefficient {
    value = 1;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_enableAirway {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_enableFractures {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_enableAdvancedWounds {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_enableVehicleCrashes {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_enableScreams {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_playerDamageThreshold {
    value = 1;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_AIDamageThreshold {
    value = 1;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_enableUnconsciousnessAI {
    value = 1;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_preventInstaDeath {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_enableRevive {
    value = 2;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_maxReviveTime {
    value = 120;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_amountOfReviveLives {
    value = -1;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_allowDeadBodyMovement {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_allowLitterCreation {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_litterCleanUpDelay {
    value = 1800;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_medicSetting_PAK {
    value = 1;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_medicSetting_SurgicalKit {
    value = 1;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_consumeItem_PAK {
    value = 1;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_consumeItem_SurgicalKit {
    value = 1;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_useLocation_PAK {
    value = 3;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_useLocation_SurgicalKit {
    value = 3;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_keepLocalSettingsSynced {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_healHitPointAfterAdvBandage {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_allowUnconsciousAnimationOnTreatment {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_moveUnitsFromGroupOnUnconscious {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_medical_menuTypeStyle {
    value = 0;
    typeName = "SCALAR";
    force = 0;
};
class ace_advanced_ballistics_enabled {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_advanced_ballistics_alwaysSimulateForSnipers {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_advanced_ballistics_disabledInFullAutoMode {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_advanced_ballistics_onlyActiveForLocalPlayers {
    value = 0;
    typeName = "BOOL";
    force = 0;
};
class ace_advanced_ballistics_ammoTemperatureEnabled {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_advanced_ballistics_barrelLengthInfluenceEnabled {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_advanced_ballistics_bulletTraceEnabled {
    value = 1;
    typeName = "BOOL";
    force = 0;
};
class ace_advanced_ballistics_simulationInterval {
    value = 0;
    typeName = "SCALAR";
    force = 0;
};
class ace_advanced_ballistics_simulationRadius {
    value = 3000;
    typeName = "SCALAR";
    force = 0;
};;*

**Description:**
*You are able to push yourself around and even fly while placing larger objects (e.g. satchel charge, AT-Mine) - the item glitches into the player. See https://www.youtube.com/watch?v=O33w7FbCjTU*

**Steps to reproduce:**
**1. Take satchel charge
2. Lower your weapon
3. Move mouse cursor at your feet
4. Glide over the map and have fun!.*

**Where did the issue occur?**
*Singleplayer and Multiplayer*

**RPT log file:**
*none*

**Comment by jaynus** [comment]
Confirmed a bug. This is due to not checking collision constraints, and not double-setposing the object.
