### ISSUE TITLE
Explosives won't rotate at placement

### ISSUE THREAD

**Issue by Raspu86** [acemod/ACE3#1235]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *class ace_common_forceAllSettings { value = 0; typeName = "BOOL"; force = 0; }; class ace_frag_enabled { value = 1; typeName = "BOOL"; force = 0; }; class ace_interaction_EnableTeamManagement { value = 1; typeName = "BOOL"; force = 0; }; class ace_magazinerepack_TimePerAmmo { value = 1.5; typeName = "SCALAR"; force = 0; }; class ace_magazinerepack_TimePerMagazine { value = 2; typeName = "SCALAR"; force = 0; }; class ace_magazinerepack_TimePerBeltLink { value = 8; typeName = "SCALAR"; force = 0; }; class ace_maptools_EveryoneCanDrawOnBriefing { value = 1; typeName = "BOOL"; force = 0; }; class ace_microdagr_MapDataAvailable { value = 1; typeName = "SCALAR"; force = 0; }; class ace_mk6mortar_airResistanceEnabled { value = 1; typeName = "BOOL"; force = 0; }; class ace_mk6mortar_allowComputerRangefinder { value = 0; typeName = "BOOL"; force = 0; }; class ace_mk6mortar_allowCompass { value = 1; typeName = "BOOL"; force = 0; }; class ace_nametags_showCursorTagForVehicles { value = 0; typeName = "BOOL"; force = 0; }; class ace_nametags_PlayerNamesViewDistance { value = 5; typeName = "SCALAR"; force = 0; }; class ace_nametags_PlayerNamesMaxAlpha { value = 0.8; typeName = "SCALAR"; force = 0; }; class ace_respawn_SavePreDeathGear { value = 1; typeName = "BOOL"; force = 0; }; class ace_respawn_RemoveDeadBodiesDisconnected { value = 1; typeName = "BOOL"; force = 0; }; class ace_respawn_BodyRemoveTimer { value = 0; typeName = "SCALAR"; force = 0; }; class ace_switchunits_EnableSwitchUnits { value = 0; typeName = "BOOL"; force = 0; }; class ace_switchunits_SwitchToWest { value = 0; typeName = "BOOL"; force = 0; }; class ace_switchunits_SwitchToEast { value = 0; typeName = "BOOL"; force = 0; }; class ace_switchunits_SwitchToIndependent { value = 0; typeName = "BOOL"; force = 0; }; class ace_switchunits_SwitchToCivilian { value = 0; typeName = "BOOL"; force = 0; }; class ace_switchunits_EnableSafeZone { value = 1; typeName = "BOOL"; force = 0; }; class ace_switchunits_SafeZoneRadius { value = 100; typeName = "SCALAR"; force = 0; }; class ace_vehiclelock_DefaultLockpickStrength { value = 10; typeName = "SCALAR"; force = 0; }; class ace_vehiclelock_LockVehicleInventory { value = 0; typeName = "BOOL"; force = 0; }; class ace_vehiclelock_VehicleStartingLockState { value = -1; typeName = "SCALAR"; force = 0; }; class ace_weather_enableServerController { value = 1; typeName = "BOOL"; force = 0; }; class ace_weather_useACEWeather { value = 1; typeName = "BOOL"; force = 0; }; class ace_weather_syncRain { value = 1; typeName = "BOOL"; force = 0; }; class ace_weather_syncWind { value = 1; typeName = "BOOL"; force = 0; }; class ace_weather_syncMisc { value = 1; typeName = "BOOL"; force = 0; }; class ace_weather_serverUpdateInterval { value = 60; typeName = "SCALAR"; force = 0; }; class ace_winddeflection_enabled { value = 1; typeName = "BOOL"; force = 0; }; class ace_winddeflection_vehicleEnabled { value = 1; typeName = "BOOL"; force = 0; }; class ace_winddeflection_simulationInterval { value = 0.05; typeName = "SCALAR"; force = 0; }; class ace_winddeflection_simulationRadius { value = 3000; typeName = "SCALAR"; force = 0; }; class ace_explosives_RequireSpecialist { value = 0; typeName = "BOOL"; force = 0; }; class ace_explosives_PunishNonSpecialists { value = 1; typeName = "BOOL"; force = 0; }; class ace_hearing_EnableCombatDeafness { value = 1; typeName = "BOOL"; force = 0; }; class ace_hearing_EarplugsVolume { value = 0.5; typeName = "SCALAR"; force = 0; }; class ace_hearing_UnconsciousnessVolume { value = 0.4; typeName = "SCALAR"; force = 0; }; class ace_medical_level { value = 1; typeName = "SCALAR"; force = 0; }; class ace_medical_medicSetting { value = 2; typeName = "SCALAR"; force = 0; }; class ace_medical_enableFor { value = 1; typeName = "SCALAR"; force = 0; }; class ace_medical_enableOverdosing { value = 1; typeName = "BOOL"; force = 0; }; class ace_medical_bleedingCoefficient { value = 1; typeName = "SCALAR"; force = 0; }; class ace_medical_painCoefficient { value = 1; typeName = "SCALAR"; force = 0; }; class ace_medical_enableAirway { value = 0; typeName = "BOOL"; force = 0; }; class ace_medical_enableFractures { value = 0; typeName = "BOOL"; force = 0; }; class ace_medical_enableAdvancedWounds { value = 0; typeName = "BOOL"; force = 0; }; class ace_medical_enableVehicleCrashes { value = 1; typeName = "BOOL"; force = 0; }; class ace_medical_enableScreams { value = 1; typeName = "BOOL"; force = 0; }; class ace_medical_playerDamageThreshold { value = 1; typeName = "SCALAR"; force = 0; }; class ace_medical_AIDamageThreshold { value = 1; typeName = "SCALAR"; force = 0; }; class ace_medical_enableUnconsciousnessAI { value = 1; typeName = "SCALAR"; force = 0; }; class ace_medical_preventInstaDeath { value = 1; typeName = "BOOL"; force = 0; }; class ace_medical_enableRevive { value = 2; typeName = "SCALAR"; force = 0; }; class ace_medical_maxReviveTime { value = 120; typeName = "SCALAR"; force = 0; }; class ace_medical_amountOfReviveLives { value = -1; typeName = "SCALAR"; force = 0; }; class ace_medical_allowDeadBodyMovement { value = 0; typeName = "BOOL"; force = 0; }; class ace_medical_allowLitterCreation { value = 1; typeName = "BOOL"; force = 0; }; class ace_medical_litterCleanUpDelay { value = 1800; typeName = "SCALAR"; force = 0; }; class ace_medical_medicSetting_PAK { value = 1; typeName = "SCALAR"; force = 0; }; class ace_medical_medicSetting_SurgicalKit { value = 1; typeName = "SCALAR"; force = 0; }; class ace_medical_consumeItem_PAK { value = 1; typeName = "SCALAR"; force = 0; }; class ace_medical_consumeItem_SurgicalKit { value = 1; typeName = "SCALAR"; force = 0; }; class ace_medical_useLocation_PAK { value = 3; typeName = "SCALAR"; force = 0; }; class ace_medical_useLocation_SurgicalKit { value = 3; typeName = "SCALAR"; force = 0; }; class ace_medical_keepLocalSettingsSynced { value = 1; typeName = "BOOL"; force = 0; }; class ace_medical_healHitPointAfterAdvBandage { value = 1; typeName = "BOOL"; force = 0; }; class ace_medical_allowUnconsciousAnimationOnTreatment { value = 0; typeName = "BOOL"; force = 0; }; class ace_medical_moveUnitsFromGroupOnUnconscious { value = 0; typeName = "BOOL"; force = 0; }; class ace_medical_menuTypeStyle { value = 0; typeName = "SCALAR"; force = 0; }; class ace_advanced_ballistics_enabled { value = 1; typeName = "BOOL"; force = 0; }; class ace_advanced_ballistics_alwaysSimulateForSnipers { value = 1; typeName = "BOOL"; force = 0; }; class ace_advanced_ballistics_disabledInFullAutoMode { value = 0; typeName = "BOOL"; force = 0; }; class ace_advanced_ballistics_onlyActiveForLocalPlayers { value = 0; typeName = "BOOL"; force = 0; }; class ace_advanced_ballistics_ammoTemperatureEnabled { value = 1; typeName = "BOOL"; force = 0; }; class ace_advanced_ballistics_barrelLengthInfluenceEnabled { value = 1; typeName = "BOOL"; force = 0; }; class ace_advanced_ballistics_bulletTraceEnabled { value = 1; typeName = "BOOL"; force = 0; }; class ace_advanced_ballistics_simulationInterval { value = 0; typeName = "SCALAR"; force = 0; }; class ace_advanced_ballistics_simulationRadius { value = 3000; typeName = "SCALAR"; force = 0; };;*

**Description:**
*You are unable to rotate explosives with middle mouse button while placing them.*

**Steps to reproduce:**
* *1. Take explosive
2. Try to rotate it with middle mouse button.*

**Where did the issue occur?**
*A possible answer might be "Multiplayer", "Singleplayer"*

**RPT log file:**
*none*

**Comment by jaynus** [comment]
Is this a feature request or a bug? Should they be rotatable?

**Comment by alganthe** [comment]
jayjay, there's a hint showing up on the screen indicating that you can rotate the explosive, problem it does not work, or it's INCREDIBLY small increments.
same for canceling the placement, right click should be the key but it's not working.

**Comment by jaynus** [comment]
kk. I never fuck around with explosives so didnt know. Thanks.

**Comment by pmc-tyler** [comment]
the explosives system looks to be copied from AGM and it was at one point working in AGM

**Comment by Twelvecaliber** [comment]
I have been able to rotate explosives, you have to set the modifier key in ACE controls first, then use the modifier key and middle mouse to rotate.

**Comment by VKing6** [comment]
I couldn't rotate the explosives before I rebound the modifier key, despite the key already being bound to the same key (control).

**Comment by pmc-tyler** [comment]
@VKing6 did you get the right click cancel function working? I thought the binding issue with the rotation was that show names was also bound to control I had unbound that but it didn't fix it. Unbinding and rebinding it to the same key did fix the rotation for me but not being able to cancel placing it, only way to do that is to place it and disarm it currently.

**Comment by Raspu86** [comment]
I can confirm. After rebinding the "modifier key" to the same key (CTRL) I can rotate explosives again. I am also able to cancel placement with right click.

**Comment by VKing6** [comment]
@pmc-tyler yes right-clicking to cancel placement has always worked for me.

**Comment by pmc-tyler** [comment]
@VKing6 its not working for me, using just ACE 3.0.0 and CBA. Rotation works after rebinding the key but I don't see a way to rebind the right click. When I right click while holding an explosive it just aims down my sight, seems the priority of the keybinds is wrong. I can hit my interaction key and it does the same function though.

**Comment by esteldunedain** [comment]
The RMB to cancel thing is not very reliable, cause BI broke the hack we used in AGM to capture the RMB. To fix that properly we need them to fix this:

http://feedback.arma3.com/view.php?id=23679

The "open interact menu to cancel placing" was done on purpose as a workaround

**Comment by pmc-tyler** [comment]
@esteldunedain ah alright, I just wanted to make sure that it was known that its still bugged. Some people were reporting it working and I have yet to see it work once for me.

**Comment by CorruptedHeart** [comment]
I guess this is sort of my fault and sort of CBA's fault. Because the modifier key is bound to left ctrl via the script. It doesn't fire properly. Which means the player needs to rebound the key to left ctrl to get it to work correctly.

The RMB is BIS's fault for breaking (or fixing their own issue) our "hack".

**Comment by PabstMirror** [comment]
Fixed by #2598
