### ISSUE TITLE
Unable to remove unconcious passengers from vehichle

### ISSUE THREAD

**Issue by Tyler1555** [acemod/ACE3#1237]
Issue
====
Trying to remove a passenger from a humvee that was destroyed removes them from the field for roughly 5 seconds before they get sent back into the vehicle.

To reproduce
=========
- Destroy Humvee
- Attempt to remove passenger

Mods
=====
- ACE3
- ALiVE
- AllInArmaTerrainPack
- ASDG_Attatchments
- ASDG_JR
- Blastcore
- CAF_AG
- CBA
- DAR_MaxxPro 
- EWK_HMMWV
- F16C Standalone
- FSF Sac Ventral
- Grace sway
- HAFM Humvees
- Hidden Identity Pack
- MGB Kill Houses
- MRT Accessory Functions
- RDS
- RHS: USF
- RHS: AFRF
- TFAR
- USAF

ACE Info
=======
Version: 3.0

**Comment by bux578** [comment]
That's a huge list of mods and this makes it nearly impossible to reproduce. Could you please verify that this happens with cba and ace3 only. Or if it needs the humvee then with RHS USF added to that list.

And please follow this form: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by Tyler1555** [comment]
Upon further testing, this seems to be a compatibility issue with the EWK humvee mod. Since this isn't really a problem with ACE I suppose this issue is no longer relevant. Sorry about that.

**Comment by Tyler1555** [comment]
Upon further testing, this seems to be a compatibility issue with the EWK humvee mod. Since this isn't really a problem with ACE I suppose this issue is no longer relevant. Sorry about that.

**Comment by bux578** [comment]
Please tell the mod maker about this :)

**Comment by simon84** [comment]
I have the same problems with vanilla units (car and player character), but RHS units activated.

**Comment by PabstMirror** [comment]
@simon84 - If you have an rpt please upload it

**Comment by Raspu86** [comment]
Experienced the same issue yesterday. I'll reproduce and provide an rpt.
