### ISSUE TITLE
Open / Close Door Key Broken

### ISSUE THREAD

**Issue by Waffle-SS** [acemod/ACE3#1238]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3

**Description:**
Rescent update has broken the Open / Close Door key, displays a script error from "interaction\functions\fnc_openDoor.sqf".

**Steps to reproduce:**
Press the ACE Open / Close Door key when looking at any door on a vanilla A3 map.

**RPT log file:**
http://pastebin.com/kin8jzRZ

**Comment by jaynus** [comment]
Please edit your issue to follow this guideline: http://ace3mod.com/wiki/user/how-to-report-an-issue.html
