### ISSUE TITLE
Error message: Explosive Module

### ISSUE THREAD

**Issue by deleyt** [acemod/ACE3#1240]
ACE3 Version: v3.0.0.3 (13 May 2015)

**Mods:**
* @cba_a3 (v1.1.20.150416 (17 Apr 15) = latest to date)
* @ace3 (v3.0.0.3 (13 May 2015) = latest to date)

**Placed ACE3 Modules:**
* ACE_ModuleExplosive

**Description:**
* Placing the Explosive System creates an error in the left bottom:
  * (BIS_fnc_moduleExecute) cannot execute module, error found in "ace_explosives_fnc_module"

* Explosives System does seem to work except other bugs that have been mentioned already here (IE: not rotating the object, etc.) 

**Steps to reproduce:**
* Start Arma3 > Editor > Stratis/Altis
* Place a unit > control: player
* Place Module > ACE > Explosive System (ACE_ModuleExplosive)
* Select "Preview"
  * Error will appear in left bottom of the screen

**Where did the issue occur?**
* Error occured while previewing the mission in the editor

**RPT log file:**
* No .RPT file was found

**Comment by bux578** [comment]
Thank you for reporting. This error has already been fixed :)
#1212

**Comment by deleyt** [comment]
Just noticed. My appoligies for duplicate.

**Comment by bux578** [comment]
No problem :)
