### ISSUE TITLE
Not listed in editor: MicroDAGR GPS

### ISSUE THREAD

**Issue by deleyt** [acemod/ACE3#1241]
ACE3 Version: v3.0.0.3 (13 May 2015)

**Mods:**
* @cba_a3 (v1.1.20.150416 (17 Apr 15) = latest to date)
* @ace3 (v3.0.0.3 (13 May 2015) = latest to date)

**Placed ACE3 Modules:**
* None

**Description:**
* MicroDAGR GPS is not listed in any classname section in the editor. It can not be placed as an object.
  * Expected it to be found in: UNIT > EMPTY > ITEMS > MicroDAGR GPS

EDIT: MicroDAGR GPS is not listed in ZEUS either.

**Steps to reproduce:**
* Start Arma3 > Editor > Stratis/Altis
* Place a unit > control: player
* Place UNIT > EMPTY > ITEMS > (MicroDAGR GPS not listed)

**Where did the issue occur?**
* Bug occurs in the editor

**RPT log file:**
* No .RPT file needed

**Comment by jaynus** [comment]
Are you sure you have the ACE microdagr pbo? 

https://github.com/acemod/ACE3/blob/6e2463b2d5dd60eb6a23f608130581a490195435/addons/microdagr/CfgWeapons.hpp

It is there and scope=2.

**Comment by esteldunedain** [comment]
@jaynus, he means that we don't have a CfgVehicle variant of the item, which is required when placing it on the editor. We are doing that only for the medical items and a few more. It's a CSE vs AGM thing, that we should solve at some point. Ideally all items should have thier corresponding Vehicle entry.

**Comment by deleyt** [comment]
What Esteldunedain said.
