### ISSUE TITLE
Explosive Attachment failure in MP

### ISSUE THREAD

**Issue by Twelvecaliber** [acemod/ACE3#1243]
Mods:

@cba_a3
@ace3

Placed ACE3 Modules:

None

Description: In a multiplayer environment, attaching explosives, (specifically a demoblock) to the underside of objects or the sides of them, they will not stick and the explosive just falls to the floor. In a single player environment i am able to attack a demoblock to the top of the wheel arch of the "fennek" car, in multiplayer it simply falls to the ground.

Steps to reproduce:

In multiplayer, spawn a "fennek". Attempt to attach a demoblock to the top of the wheel arch as shown below. (Screenshot taken from singleplayer editor for demonstrational purposes)

![2015-05-16_00001](https://cloud.githubusercontent.com/assets/10883422/7665916/b692affa-fbc5-11e4-8092-750cc2f86d7d.jpg)

Where did the issue occur?

MP Client and dedicated.

**Comment by esteldunedain** [comment]
Solution: switch attach method to use the same method used in ace_attach.

**Comment by Khaosmatic** [comment]
You can attach explosives to vehicles?! WHAAAAAAAAAAAAAAAAAT I did not know dis.
