### ISSUE TITLE
Zeus performance drop while flying over the map

### ISSUE THREAD

**Issue by igorkiss** [acemod/ACE3#1247]
ACE3 Version: 3.0.0

Mods:
@cba_a3
@ace3
@task force arrowhead radio

Placed ACE3 Modules:
ACE3 Map module (tested without it too)

Description:
When you fly over the map as Zeus Game Master with holded shift button (fast flying, Zeus "sprint)", performance noticeably drops (from 60-70fps to 25, according to FRAPS). I tried to turn off map calculations(ACE3 Map module), but nothing helps. It is also drops slightly (from 70 to 55fps) when you just flying without shift.
Steps to reproduce:
Just start game as Zeus Game Master.

Where did the issue occur?
Checked on Altis, Stratis, and some maps from AiA TP. Occurs in singleplayer, editor and multiplayer.

RPT log file:
No

**Comment by esteldunedain** [comment]
AFAIK that happens in vanilla Arma 3 too. I don't think this is related to ACE3 at all.

**Comment by jonpas** [comment]
@igorkiss Try doing the same without any mods (pure Vanilla).

**Comment by igorkiss** [comment]
@esteldunedain 
I used AGM before ACE3's release, it never happens to me. With ACE3 it happens everytime you hold shift and fly.

@jonpas 
I tried, everything's ok.

**Comment by alganthe** [comment]
Welcome to the splendid world of BI's issues.

**Comment by esteldunedain** [comment]
Well, we'll have to look over this in detail. We do spatially cache various things, so it's conceivable that one of them could be causing lag when the position changes greatly evey frame.

I'm not convinced that's the case yet though.

**Comment by igorkiss** [comment]
@esteldunedain 
I can make a video with and without ACE, if you need it as proof.

**Comment by esteldunedain** [comment]
@igorkiss, nah, there's no need for a video. If you do want to contribute this is what I'd really need: evaluating fps with different number of ACE pbos. That'd be incredibly usefull to pinpoint what piece of code could be producing this.

**Comment by igorkiss** [comment]
@esteldunedain
I finally found that cause this performance drop. It is Task Force Arrowhead Radio addon that i forgot to turn off. AGM+TFAR works fine, anyway.
Sorry for taking your attention, dlelete thread, please.

**Comment by esteldunedain** [comment]
@igorkiss, so TFAR + ACE lags? but not AGM + TFAR or ACE alone? Sounds very strange

**Comment by jaynus** [comment]
I thought TFR didn't have performance issues? :trollface:

**Comment by SilentSpike** [comment]
I've definitely noticed this behavior in vanilla arma before, unless ACE somehow makes it significantly worse, I don't think anything can really be done about it.

**Comment by igorkiss** [comment]
@esteldunedain 
Yes, i just tested ACE3+TFAR - performance drop happens. Only ACE3 - fps is fine, 50-70 with fast flyingr. I will test AGM+TFAR soon.

**Comment by igorkiss** [comment]
@SilentSpike 
I dont know to what mod this problem related - ACE or TFAR. I can reopen issue, if someone meet this, idk, bug.

**Comment by esteldunedain** [comment]
I see no point keeping this open unless the bug is confirmed to happen due to ace

**Comment by legman** [comment]
I can defiantly confirm a substantial drop in frame rate whilst panning around as ZEUS since swapping over to ACE3 & TFAR. We previously used AGM & TFAR and the frame drop was much less noticeable.
