### ISSUE TITLE
After using the DLL fix i am getting kicked back to multiplayer search menu

### ISSUE THREAD

**Issue by enderrrrrrrrrr** [acemod/ACE3#1258]
Version 3.0

ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *All ACE modules excluding BLUEFOR tracking

**Description:**
I was crashing when launching ace and after replacing hte DLL files i am getting kicked off the multiplier on attempting to join even after ensuring that teh version of ace on the server is essentially a copy paste of the client version i am running. Others are able to connect fine.

**Steps to reproduce:**
Use my computer an attempt to connect to a multiplayer game

**Where did the issue occur?**
Multiplayer

**RPT log file:**
Am unable to find.

**Comment by PabstMirror** [comment]
RPT can be found here: %localappdata%/Arma 3/

What I think might be happening is you uploaded new .pbo's without switching out the .bikey.

Just because they both say `ace_3.0.0.3.bikey` doesn't mean they are the same.

**Comment by enderrrrrrrrrr** [comment]
Oh ok, So is this something i should change within editor or swap out in the infrastructure of the mission file itself?

Also why would others be able to connect and not myself?

**Comment by PabstMirror** [comment]
All I can do is speculate without an RPT (server rpt wouldn't hurt either).

But you might want to try coping @ace\keys\ace_3.0.0.3.bikey for the release you are using to the server's \Keys folder.

**Comment by jaynus** [comment]
Closing due to no further info.
