### ISSUE TITLE
Possible bug with Medical Vehicles

### ISSUE THREAD

**Issue by Blackswater** [acemod/ACE3#1264]
ACE3 Version: 3.0.0 (first official Release)

**Mods:**
* @cba_a3
* @ace3
* @RHS
* @BWMod

**Placed ACE3 Modules:**
Advanced Medical System, Medical Vehicles

**Description:**
I've got an error when want to interact with the Medical Vehicle http://i.imgur.com/5SdeAJX.jpg. The Medical Vehicle is set in the Medical Vehicle Module. All other Vehicles working fine. 

**Steps to reproduce:**
Place a vehicle in the Editor. 
Set it in the Medical Vehicle as Medical Vehicle. 
Go in as Doktor and interact with the Vehicle
You need at least 2 people in the Vehicle

**Where did the issue occur?**
Multiplayer

**RPT log file:**
http://pastebin.com/BGJxYgJq (Client RPT log)

**Comment by Glowbal** [comment]
I have seen this before and may have fixed it. I will double check.

**Comment by alganthe** [comment]
I saw a similar issue that you fixed, should be somewhere in #medical archives on slack.

**Comment by Glowbal** [comment]
Found it. #1142 

Fixed in #1145
