### ISSUE TITLE
Interaction layer missing for logistics_UAVbattery

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#1269]
ACE3 Version: 3.0.3 last commit 9e8283ebabdcf8e5dab743f8d929d7c04943ba9c

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
none

**Description:**
The logistics_UAVbattery feature is missing it's interaction layer, the functions are working properly but the interaction is not here because it was never added

**Steps to reproduce:**
- Place a rifleman call him U1
- Place a darter call it D1
- Place the misc ace ammobox (containing the uav batteries)
- Take a UAV battery 
- Approach the darter and open the debug console
- Type ``` [U1, D1] call ace_logistics_uavbattery_fnc_canRefuelUAV   ```
- Note that the function return true but the interaction on the darter is missing.
- Execute ``` [U1, D1] call ace_logistics_uavbattery_fnc_refuelUAV ```
- Note that the darter is now refueled.

**Where did the issue occur?**
editor, SP, MP

**RPT log file:**
Nothin'

**Comment by PabstMirror** [comment]
Tested working now.
