### ISSUE TITLE
Discussion: Wind Direction and Speed

### ISSUE THREAD

**Issue by LorenLuke** [acemod/ACE3#1272]
Currently there's exists the wind arrow (Shift+K) for determining wind direction and speed. However, rather than using color, would it be possible to use a magnitude for the arrow for any users who may be colorblind?

**Comment by gienkov** [comment]
Idea:
**"Enable Beaufort wind force scale"** (Yes/No) in ACE Settings menu. Shows number (0 - 12) next to wind arrow.

**Comment by ulteq** [comment]
Good idea. That would be much easier than implementing variable arrow lenghts.

**Comment by esteldunedain** [comment]
I'd prefer changing the arrow scale instead of the numbers, as I think it'd convey better the fact that wind estimation is just a gut feeling, not a measurement.

**Comment by alganthe** [comment]
For numbers you have the kestrel 4500 so I'm against using numbers for it.
