### ISSUE TITLE
Server is forcing server language for settings values

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1273]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None*

**Description:**
*So it seems like even you have set your language to for example polish, while playing on the server you will see setting values in server language (in my example in english)*
http://images.akamai.steamusercontent.com/ugc/37497482120665768/9C112D557221CF612F1B4A041358358FBC42F5F3/
*As you can see on image above, only things that are translated to polish are values that are BOOL, and those that use game strings like:*
```
    class GVAR(textSize) {
        value = 2;
        typeName = "SCALAR";
        isClientSettable = 1;
        displayName = "$STR_ACE_Interact_textSize";
        values[] = {"$str_very_small", "$str_small", "$str_medium", "$str_large", "$str_very_large"};
    };    
```
This example is best:
```
    class GVAR(shadowSetting) {
        value = 2;
        typeName = "SCALAR";
        isClientSettable = 1;
        displayName = "$STR_ACE_Interact_shadowSetting";
        description = "$STR_ACE_Interact_shadowSettingDescription";
        values[] = {"$STR_A3_OPTIONS_DISABLED", "$STR_A3_OPTIONS_ENABLED", "$STR_ACE_Interact_shadowOutline"};
    };
```
***"$STR_A3_OPTIONS_DISABLED"*** and ***"$STR_A3_OPTIONS_ENABLED"*** are game strings that are being translated properly, but last option which is ***"$STR_ACE_Interact_shadowOutline"*** is using server language anyway.

**Steps to reproduce:**
* *Set game language to anything but english.*
* *Join server which has language set to english.*
* *Open settings menu and you will see that part of options (which are stringtabled) are in english, not in language you set in your game.

**Where did the issue occur?**
*Multiplayer only*

**RPT log file:**
*Not needed*

**Comment by Glowbal** [comment]
We fixed this earlier but it's probably not reliable. Should be part of the  Reliable settings framework #1214.
