### ISSUE TITLE
Separate BFT from Map.pbo?

### ISSUE THREAD

**Issue by Twelvecaliber** [acemod/ACE3#1276]
Is it possible to separate the blue force tracking module from the Map.pbo, as i have had instances where i, and my community members have wanted to use the BFT in missions, but not wanted to use the modified map, as they find it too "in your face". 

Appreciate the time to read. 

Keep up the great work. :)

**Comment by Glowbal** [comment]
We are redoing the BFT module completely. I don't think splitting it off now without the new implementation would be smart considering we have to take into account backwards compatability.
