### ISSUE TITLE
Nametags: Fireteam colors do not propagate to other clients when fireteam is assigned

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#1279]
The group leader is the only one that sets the colors locally, but these settings do not get set on the fireteam members to see their own colors.

**Comment by esteldunedain** [comment]
How are you assigning colors? AFAIK the ACE interact menu doesn't allow setting colors for other players besides yourself. For some reason it expects every player to sets his own color

**Comment by jaynus** [comment]
I suppose its a feature and a bug, then. As the colors arn't propegated regardless, and we should also be able to assign colors as a group leader, not just set your own.

**Comment by esteldunedain** [comment]
Yes, I agree.

**Comment by jaynus** [comment]
Can't we just use colors for the fireteam assignments made in the vanilla fireteam system? Do we not do that right now?
