### ISSUE TITLE
Nametags: Intersect position is not eye to eye

### ISSUE THREAD

**Issue by TinfoilHate** [acemod/ACE3#1280]
On the infrequent instance you cannot see a person's face, but can see their body, you can ID them perfectly fine. Ideally, you have to see their face to ID them.

**Comment by esteldunedain** [comment]
It can be improved, but it's currently not that bad. The line of sight is calculated between the camera origin and a position 1m above the hip of the target (my fault, I wasn't aware of the `selectionPosition` command at that time)

**Comment by J-Ziegler** [comment]
I'm not sure this is an issue, since its impossible to move bodies freely.

**Comment by TinfoilHate** [comment]
You can lean and step to the side, which is the most common place it comes up.
