### ISSUE TITLE
Cannot remove players from vehicles

### ISSUE THREAD

**Issue by 7thSim** [acemod/ACE3#1283]
Once a person is wounded and loaded into a vehicle he cannot be removed - he just bounces back in.  Making it impossible to do some treatments to the patient.

Using advanced medical.

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by jaynus** [comment]
Closing due to no further info and this being from a prior release.
