### ISSUE TITLE
No treatmentAdvanced_surgicalKit function

### ISSUE THREAD

**Issue by SzwedzikPL** [acemod/ACE3#1284]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
xxx

**Description:**
Surgical Kit does nothing because there is no treatmentAdvanced_surgicalKit function.

**Steps to reproduce:**
xxx

**Where did the issue occur?**
xxx

**RPT log file:**
xxx

**Comment by Kowgan** [comment]
Can confirm this.
Also, according to the code, the only usable region to the SurgicalKit is the Torso.

**Comment by Glowbal** [comment]
It's not implemented - I forgot to do so during the rewrite. 

The interaction is all 100% complete, it just requires the onProgress callback. Most likely got to expand the treatment framework to support dynamic treatment time as well.

**Comment by Glowbal** [comment]
Done in #1392
