### ISSUE TITLE
$STR_ACE_Medical_Wounds_Contusion doesn't update status

### ISSUE THREAD

**Issue by Kowgan** [acemod/ACE3#1287]
ACE3 Version: 3.1.0

**Mods:**
* @cba_a3
* @ace3
* @ACRE2
* @UOMaps
* @UOMods

**Placed ACE3 Modules:**
* Medical Settings
* Advanced Medical Settings
* Set Medical Class

**Description:**
* Contusion (bruise) wounds won't be updated as "bandaged", and will always leave a red icon on the wounded limb. Apparently, the bandage actually takes effect on the wound, but the visual reference doesn't update. I'm unsure about this.

* Screenshot: http://puu.sh/hRxOI/17c8560562.jpg

**Steps to reproduce:**
* Cause a contusion wound;
* Bandage that wound;
* The wound remains there.

**Where did the issue occur?**
* Multiplayer, Singleplayer

**RPT log file:**
* ---

**Comment by alganthe** [comment]
Not an actual issue, the feature is simply not fully implemented.

**Comment by Glowbal** [comment]
This is by design.

**Comment by Glowbal** [comment]
I just realised that the color on the icons is a bug, it should only display when bleeding. Fixed b43dff3

Bruises will stay though, that is by design.

**Comment by Glowbal** [comment]
Only PAKs.
