### ISSUE TITLE
Feature Request: Increase the background alpha from bodyparts card

### ISSUE THREAD

**Issue by Kowgan** [acemod/ACE3#1289]
The low alpha at the Bodyparts' Card background makes it hard to read some of the info on it, depending on the scenario.
http://puu.sh/hRxTp/069429e71c.png

My suggestion is to make that background less transparent, thus making things easier to read.
Example set to 0,0,0,50 for the ACE Hint Background color: http://puu.sh/hRyzd/61416f241d.png

**Comment by jaynus** [comment]
Please use #414 for feature requests.
