### ISSUE TITLE
Being near Campfires messes up basic medical and causes large fps lag

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#1297]
This the most stupid bug report ever, but 100% true. Painstakingly reproduced from a BIF report.

When a soldier stands < 5m from a campfire (`FirePlace_burning_F`) the engine produces tiny tiny handle damage events on them every frame. Basic medical creates a PFH to wait a couple of frames after each of this events: 

https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_handleDamage_basic.sqf#L52-L64

If you stay in that position the amount of PFH bubbles up slowly, eventually causing large fps degradation. Over 5000 of this pfh has been observed in a mission with a bunch ai units near campfires and a few minutes.

Repro steps:

1- Create a burning campfire
2- Get your unit close to it
3- Monitor the amount of pfh running by watching: `count CBA_common_perFrameHandlerArray`
4- The count goes up as you keep standing next to the fire

**Comment by Glowbal** [comment]
This may be fixed in #1303

**Comment by Glowbal** [comment]
Should be fixed now.
