### ISSUE TITLE
Ziptied players remain ziptied indefinitely after respawning

### ISSUE THREAD

**Issue by SonixApache** [acemod/ACE3#1298]
ACE3 Version: 3.0.0

**Mods:**
@cba_a3  RC6 hotfix 1
@ace3

@HLCweapons
@ACRE2
@ALiVE

**Placed ACE3 Modules:**
N/A

**Description:**
When a player dies while ziptied, they cannot be untied through any usual means after respawning.
This includes untying, re-tying, placing in a vehicle, etc.
The player can still perform certain actions like getting into vehicles in this state.

**Steps to reproduce:**
Connect two players to the server
Have one player ziptie the other
Have the ziptied player respawn
(Have the one player un-tie the ziptied player)
(Have the now 'untied' player respawn)

Repro mission:
http://a.pomf.se/ciyros.pbo
respawn = 3;
respawnDelay = 30;
respawnTemplates[] = {"Counter", "Spectator"};
respawnOnStart = 0;
respawnVehicleDelay = 240;
respawnDialog = 0;

**Where did the issue occur?**
Multiplayer, dedicated AND listen servers

**RPT log file:**
N/A

**Comment by PabstMirror** [comment]
Should be fixed, thank you for the report.
