### ISSUE TITLE
How to change medical parameters by script command?

### ISSUE THREAD

**Issue by SonixApache** [acemod/ACE3#1299]
Trying to change the ACE medical system from basic to advanced by script command to set up mission parameters. It's definitely possible, since the config exporting tool lets you change it.

I've tried the following in the debug menu;
ACE_moduleMedicalSettings setVariable ["level", 1];

ACEbaseMedModule setVariable ["level", 1]; 
(ACEbaseMedModule is the name of the module in the editor)

ACE_moduleMedicalSettings setVariable ["ace_medical_level", 1];

ACEbaseMedModule setVariable ["ace_medical_level", 1];

I suppose I'm misunderstanding propex syntax, because I can't figure it out.

**Comment by PabstMirror** [comment]
Simplest: Put down the module and change it there.  

otherwise you can put the following in description.ext:
```
class ACE_Settings {
    class ACE_medical_level {
        value = 0;
    };
};
```

**Comment by jaynus** [comment]
Or set the variable
