### ISSUE TITLE
Animating Ace_weaponselect and Ace_safety.

### ISSUE THREAD

**Issue by HopeJohnson** [acemod/ACE3#1300]
I did some minor developing with AGM back when to add in animations for AGM weapon select and weapon safety. Specifically, weapon safety/selector animation (which could be unique to the weapon) and attempted to make an animation for flipping up the GL sights on an M4. Unfortunately I couldn't get it to time properly with the animation. Ideally, I would want it to play the animation and then once it hits the correct part of the animation, it flips the sights up. 

Looking into ACE's equivalent, it seems the coding is much more intricate and beyond my knowledge. Is it possible to still have these animations in those two mods? Also, is there a resource that people can use to learn how your ACE specific coding works?

**Comment by bux578** [comment]
http://ace3mod.com/wiki/development/

**Comment by commy2** [comment]
Can this be closed?

**Comment by MikeMatrix** [comment]
Pretty sure all of the things that were asked, can be answered through the wiki.
So probably?
