### ISSUE TITLE
Player corpses cannot be successfully bodybagged while the player is respawning

### ISSUE THREAD

**Issue by SonixApache** [acemod/ACE3#1301]
ACE3 Version: 3.0.0

Mods:
@cba_a3 RC6 hotfix 1
@ace3

Placed ACE3 Modules:
N/A

Description:
When a player dies their body cannot successfully be placed in a bodybag untill that player spawns again.
Instead, a bodybag is spawned, but the corpse remains.

Steps to reproduce:
Connect two players to the server
Have one player die
Have the other played attempt to place the corpse of the first player in a bodybag
(Note how the corpse can be successfully bagged after the player has spawned again)

Repro mission:
http://a.pomf.se/ciyros.pbo
respawn = 3;
respawnDelay = 30;
respawnTemplates[] = {"Counter", "Spectator"};
respawnOnStart = 0;
respawnVehicleDelay = 240;
respawnDialog = 0;

Where did the issue occur?
Multiplayer, dedicated AND listen servers

RPT log file:
N/A

**Comment by jaynus** [comment]
This is because Arma does not release the body object until the respawn has completed. Until respawn is complete, the player object is still that body. I don't see a way around this except for moving locality of the player, which could get messy quickly.

**Comment by jonpas** [comment]
PFH that keeps trying until the player respawn/disconnects (I hope going back to lobby does release the object)? Not sure how that would work with long respawn times and when to actually performing the action or notifying the 'packer' about it though...

**Comment by jaynus** [comment]
Yah, its all hacky, and it would just be an "eventually works" - we'd also need to monitor thresholds of time and actions to wait for. A lot of work for them just needing to wait.

**Comment by jonpas** [comment]
Agreed. What I'd suggest then is a check so the body bag doesn't actually get placed before the body object is released, is that possible without hacky implementations?

**Comment by jaynus** [comment]
Good ideal, I'll do it. We can just reverse the order so its not placed on failure.

**Comment by jonpas** [comment]
:+1: 

I am pretty sure it was in idea though. :banana:

**Comment by nomisum** [comment]
what about making the body enter a bodybag vehicle as driver/gunner/whatever :D 
so both can live together peacefully. or hide the corpse at least.

just a quick idea. idk whether dead can enter vehicles tbh.

**Comment by esteldunedain** [comment]
> what about making the body enter a bodybag vehicle as driver/gunner/whatever :D 
so both can live together peacefully. or hide the corpse at least.

Mm, making the bodybag a vehicle that can have a passenger inside or not seems like a good idea.

Another alternative may be to move the corpse far away.

**Comment by Glowbal** [comment]
You cannot move dead bodies into vehicles. At least not last time I tried.

**Comment by jonpas** [comment]
No you can't, plus it wouldn't really solve this issue, as jaynus said reversing the order would fix it I think.
