### ISSUE TITLE
Question on effectivness values for bandages? They don't make sense for me...

### ISSUE THREAD

**Issue by Best2nd** [acemod/ACE3#1305]
For example QuikCloth when applied to a velocity wound it has a reopening chance of 10% and a effectiveness rating of 70%. Packing bandage has a effectiveness of 100% and logically it should have a lower reopening chance, right? Right? I, mean wiki says that applying wrong bandage will yield wound reopening... If that is the case, then why is the reopening chance for PB 50%??? Or is effectiveness not related to wound reopening in any way?

**Comment by Glowbal** [comment]
They are two separate things.

* Effectiveness is the effectiveness a bandage has on stopping the bleeding. For example bandage X patches up 50% of wound type Y.
* Reopening change is the change that the wound could open again.

Does this answer your question?

**Comment by alganthe** [comment]
For example an elastic bandage is good for stopping the reopening of ""some"" wounds but not others.

**Comment by Best2nd** [comment]
Yeah, but I never had a situation like in CMS where you fail to stop the bleeding. If adv wounds is of it doesn't really matter what bandage you apply, wound just disappear... Maybe it's not working properly? IDK. Someone should investigate it.

**Comment by Best2nd** [comment]
After some testing it turns out that wounds will always get sealed regardless of the effectiveness rating. Looks like it's b0rken.

**Comment by PabstMirror** [comment]
Fixed in #2886
