### ISSUE TITLE
MEDEVAC vehicle option breaks in-vehicle interaction

### ISSUE THREAD

**Issue by SonixApache** [acemod/ACE3#1318]
ACE3 Version: 3.0.1

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
ACE Medical settings
ACE Advanced medical settings
ACE Set Medical Vehicle

Description:
The MEDEVAC vehicle option breaks ACE interactions with other units in the MEDEVAC vehicle.

Steps to reproduce:
- Open a new scenario in the editor
- Place the ACE Medical settings module
- Place the ACE Advanced medical settings module
- Place a vehicle
- Place the Set Medical Vehicle module and link it to the vehicle
- Place some (playable) units
- Start the mission
- Order the units into the vehicle and enter it yourself
- Attempt to interact with anyone in the vehicle

Repro mission: http://a.pomf.se/upkipq.pbo
- Launch scenario
- Order AI into either medical vehicle
- Enter medical vehicle
- Attempt to interact with others in the vehicle

Where did the issue occur?
Singleplayer, multiplayer

RPT log file:
http://pastebin.com/v2pSGASW

**Comment by PabstMirror** [comment]
Thank for the excellent report and test mission.
QGVAR(medicClass) is a number, switched to use the same comparison as found in `fnc_isMedicalVehicle.sqf`

**Comment by gienkov** [comment]
I was just about to report it too. Happened on MP, same situation. Can this
fix be included as hotfix to 3.0.1 or do I have to build release myself?
20 maj 2015 01:36 "PabstMirror" <notifications@github.com> napisał(a):

**Comment by jaynus** [comment]
marked as 3.1 for metrics.
