### ISSUE TITLE
Scope Adjustment doesn't actually adjust scope

### ISSUE THREAD

**Issue by agent509** [acemod/ACE3#1319]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
When adjusting scopes, everything seems to be working properly (clicking, rotating view, etc.), but when actually firing, nothing has changed with regards to scope adjustment.

**Steps to reproduce:**
* Grab a gun and scope
* Shoot at distant target, noting the drop
* Adjust for drop, shoot again, and the drop stays the same.

**Where did the issue occur?**
Singleplayer and multiplayer

**Comment by bux578** [comment]
I'm pretty sure that scope adjustment works flawlessly

**Comment by PabstMirror** [comment]
Tested on 3.0.0 - working good for me
https://youtu.be/ZIHWu9VS_XY

What weapon/scope where you using?

**Comment by agent509** [comment]
Hmmmm I tried it out on a few different weapons/scopes. After getting a friend to help me test, it definitely appears to be just a problem with my particular game. So, no issue, thanks.
