### ISSUE TITLE
How to install ACE 

### ISSUE THREAD

**Issue by UnknownCobra** [acemod/ACE3#1320]
I am having problems trying to install ACE to arma 3. Is there a guide out there or can someone please tell. I really want to play with my friends on this mod.

**Comment by PabstMirror** [comment]
Download CBA: https://bitly.com/1DMFnMr
Download ACE: https://github.com/acemod/ACE3/releases/latest

Extract them to your aram dir - probably `C:\Program Files (x86)\Steam\steamapps\common\Arma 3`

Start game and select both addons.

**Comment by bux578** [comment]
@alganthe @BullHorn7 @dharmab 

We could use an installation guide in the documentation.

**Comment by BullHorn7** [comment]
I'll write it this evening unless someone beats me to it.
