### ISSUE TITLE
RHS Javelin missile guidance broken

### ISSUE THREAD

**Issue by Raspu86** [acemod/ACE3#1321]
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3
* @RHSAFRF
* @RHSUSF
+ ace_compat_rhs_afrf3.pbo; ace_compat_rhs_usf3.pbo

**Placed ACE3 Modules:**
none - default

**Description:**
*With the newest compatibility pbos for RHS the Javelin is able to lock targets with the ACE system but the missile guidance is broken. The missile flies straight up and is not guided. This happens with top down and direct attack.*

**Steps to reproduce:**
1. Grab RHS Javelin
2. Aquire target and shot
3. Observe missile*

**Where did the issue occur?**
*Multiplayer and Singleplayer*

**RPT log file:**
*http://pastebin.com/cunR1C5T*

**Comment by Jastreb** [comment]
Same here, confirmed. Looks like an early spike bug.

**Comment by PabstMirror** [comment]
We disable locking on their javelin:
```
class rhs_weap_fgm148 : launch_O_Titan_F {
    ace_javelin_enabled = 1;
    canLock = 0;
```

But missile guidance isn't enabled for their ammo:
magazine: `rhs_fgm148_magazine_AT`
ammo: `rhs_ammo_M_fgm148_AT`

**Comment by jaynus** [comment]
They inherit Titan directly but the ammo has a completely different inheritance chain. Glorious!

**Comment by alganthe** [comment]
meh, someone will have to fix their broken inheritances, AGAIN.

**Comment by cych** [comment]
I upgraded ACE to 3.1.1 and RHS to 0.3.8 and I still have to vanila Titan A3 version GUI style.

there is no disposable CLU, there is no selectable attack mode, there is no white crosshair style like in A2 ACE. 

do i miss something ?

**Comment by Raspu86** [comment]
do i miss something ?
####

The compatibility pbo?

**Comment by 7Hazard** [comment]
I got it to work only if we use the Javelin from far distances. Otherwise the missile just flies up in the air and doesn\t have enough time to fly down towards the RHS vehicle.

**Comment by commy2** [comment]
@7Hazard This issue was closed May 24th 2015, so over a year ago. Please don't revive old issues.
