### ISSUE TITLE
Question : save / restore medical status.

### ISSUE THREAD

**Issue by havena** [acemod/ACE3#1324]
Hi,

i try to save / restore (disconnect/reconnect) medical player status for a mission.

my question is simple, can i find all var for medical on medical_fnc_init ?

is theyre a best way for save/restore than get/set all vars?

Thx.

**Comment by jaynus** [comment]
getAllVariables

**Comment by bux578** [comment]
From now on, please use the forum for questions: http://forums.bistudio.com/showthread.php?191716-ACE3-A-collaborative-merger-between-AGM-CSE-and-ACE

**Comment by bux578** [comment]
Or hop onto the slack public chat: https://github.com/acemod/ACE3/issues/429
