### ISSUE TITLE
The Case of the Disappearing Optics

### ISSUE THREAD

**Issue by DutchVidya** [acemod/ACE3#1326]
I do not know how I would even begin to replicate this issue. Basically, the PIP optics cease to exist. I first notice their absence on the Arsenal as a member of our community was commenting on them. I assumed they were simply absent from the Arsenal itself.

I then had them appear this morning and I used them in a mission. Following a restart of Arma the unit in question no longer had his RCO PIP sight, and sure enough it was gone from Arsenal as well.

Example of them being missing from the Arsenal:

http://imgur.com/JwW6tOE

Here are the mods running currently, but please note, this issue arose on ACE3's release date when being ran on it's own as well.

```
@prkz;
@bornholm;
@allinarmaterrainpack;
@cba_a3;
@ace3;
@acre2;
@asdg_jr;
@dac_a3;
@dam;
@rhs_afrf3;
@rhs_usf3;
@rh_pistol_a3;
@fhq_accessories;
@cup;@hlcmods_core;
@hlcmods_g3;
@hlc_wp_mp5;
@k_mnp;@
@hiddenidentityv2;
@unlocked_uniforms;
```

Whilst I doubt any of these could cause this issue. If anyone else has experienced this and is running any of them. It would be good to know. Honestly I couldn't even begin to guess what's happening. It seems these optics are literally not loading into the game at all, as my loadouts for my mission relied on the optics classname existing, and it would appear it did not, as no optics were spawned at all.

At least one other person has confirmed this issue happening to them as well today.

**Comment by jaynus** [comment]
Thanks for the report. Please provide an RPT, as this sounds like a load order issue that we really cant debug/determine without the logs.

Here is the issue reporting gudelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by jaynus** [comment]
As a side note - this definitely is almost 100% a mod load order issue, something is overwriting the optics or making them not appear in VA.

**Comment by PabstMirror** [comment]
Try adding the ASDG compat pbo:
@ace\optionals\ace_compat_asdg.pbo
by moving it to to @ace\Addons

**Comment by PabstMirror** [comment]
@DutchVidya - did adding the compat pbo fix the issue for you or are they still not showing up?
