### ISSUE TITLE
All ACE3 webpages are outdated

### ISSUE THREAD

**Issue by BullHorn7** [acemod/ACE3#1334]
I wanted to point out that they are all outdated. There might be more I haven't noticed yet.

- [x] [ace3mod.com](http://ace3mod.com/index.html) - still has the same text it had before release "We're stoked you want to try ACE3!"... It doesn't even lead to any download page from the official website.

[Armaholic](http://www.armaholic.com/page.php?id=28557) - Still has 3.0.0 and even that is not really possible to download.

[Play withSIX](http://play.withsix.com/Arma-3/Mods/etoMALy4W0ih7UzPe8PYRQ/ACE3-A-collaborative-merger-between-AGM-CSE-and-ACE) - Title says 3.0.1 but download url leads to 3.0.0

[GitHub ACE3 frontpage](https://github.com/acemod/ACE3) - Still shows 3.0.0 as the latest version...

**Comment by sargken** [comment]
Bull it does get annoying because i have to explain to everyone in my unit how to change to v3.0.0qon pws.

**Comment by jaynus** [comment]
Sadly none of this is out of our control, apparently armaholic and the PWS teams are not very motivated to support us in a stable fashion. I'd recommend contacting both those teams letting them know that you'd like ACE releases to be correct.

We already have, for both releases now, with little response or action.

**Comment by BullHorn7** [comment]
I remember one of the two posting in the ACE3 thread and mentioning some sort of moderation is possible - I think they can allow you to update your own page with an Armaholic account.

**Comment by jonpas** [comment]
On PwS it's possible yes, on Armaholic not yet.

**Comment by sargken** [comment]
Can you tell PWS to set it 3.0.1 to stable version.

**Comment by jonpas** [comment]
> Sadly none of this is out of our control, apparently armaholic and the PWS teams are not very motivated to support us in a stable fashion. I'd recommend contacting both those teams letting them know that you'd like ACE releases to be correct.
We already have, for both releases now, with little response or action.

**Comment by ViperMaul** [comment]
PwS does not seem to be an issue any more. If not true. Let us know

**Comment by BullHorn7** [comment]
Can't verify because I don't use PwS but it looks good.
They also still carry [an old and unofficial version, which actually popped up first on a Google search](http://play.withsix.com/arma-3/mods/OlrE_h937UCsSGr0T6oavw/ACE-3). Should probably be deleted entirely.

**Comment by sargken** [comment]
PWS is fixed they just have the current version live.
