### ISSUE TITLE
Break out disposables to a framework for addon makers to use

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#1335]
@headedhorseman101 commented 4 hours ago
Would it be possible for the addition of a template or a function that would allow addon makers to make their launchers disposable (i.e. ace_missile_guidance)? The disposable module in its current state works really well for the NLAW , but doing this would allow addon makers to, as an example, make a javelin that you had to assemble and has a disposable tube, kinda like in ACE 2.

**Comment by sargken** [comment]
Like the RHS M136 it could use the functionality

**Comment by PabstMirror** [comment]
Handled in CBA
https://github.com/CBATeam/CBA_A3/pull/1116
