### ISSUE TITLE
Fragmentation is incorrect over water (ASL and ATL mix up)

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#1337]
Throw a grenade into the sea, and watch the shrapnel spawn as the grenade hits the water surface, without detonating.

**Comment by esteldunedain** [comment]
@jaynus, are you sure this is a problem with coordinates? I assumed it was due to `alive _projectile == false` when the projectile wets.

**Comment by jaynus** [comment]
That would do it. Thats not really workable.
