### ISSUE TITLE
Performance drops when using interact menu , especially near groups of units

### ISSUE THREAD

**Issue by SonixApache** [acemod/ACE3#1341]
ACE3 Version: 3.0.1

Mods:
@cba_a3
@ace3

**Placed ACE3 Modules:**
N/A

**Description:**
A hit to performance occurs when the interact menu is drawn.
This effect is worse the more units are near one place when trying to interact.

On my system the loss is about half a frame per second per unit, but in a recent multiplayer session the issue was reported as much greater.

**Steps to reproduce:**
Attempt to interact while looking at a group of units and observe your framerate.

Repro mission: http://a.pomf.se/upkipq.pbo

    Launch scenario
    Attempt to interact with one of the four different groups of units
    Observe framerate

**Where did the issue occur?**
Singleplayer, multiplayer

**Comment by gienkov** [comment]
Yup same issue here on our missions. More ppl closer to you - less FPS.

**Comment by BaerMitUmlaut** [comment]
I think displaying the interaction menu only for one person might not only be beneficial for performance but for clarity as well. Depending on your preferred font size, multiple interaction menus showing can be quite confusing.

**Comment by esteldunedain** [comment]
I'll recheck this, specially due to some recent features added.

@BaerMitUmlaut, I think that problem is mitigated on the current master, which implements action points oclusion.
