### ISSUE TITLE
Goggle effects removed when using sights in Firing from Vehicles position

### ISSUE THREAD

**Issue by SonixApache** [acemod/ACE3#1342]
ACE3 Version: 3.0.1

Mods:
@cba_a3
@ace3

**Placed ACE3 Modules:**
N/A

**Description:**
When using sights in a Firing from Vehicles position, the effect of goggles are cancelled out.
This is the case for any Firing from Vehicles position, including those found in trucks, helicopters and tanks.

**Steps to reproduce:**
Attempt to use your sights while in a Firing from Vehicles position.

Repro mission: http://a.pomf.se/dbikkb.pbo

    Launch scenario
    Raise weapon
    Bring up sights

**Where did the issue occur?**
Singleplayer, multiplayer

**Comment by SilentSpike** [comment]
Note to self: common,canUseWeapon
