### ISSUE TITLE
MicroDAGR map fill option not working properly

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1343]
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3
* @acre2
* @RHS
* @Leight Opfor Pack

**Placed ACE3 Modules:**
* *MicroDAGR map fill*

**Description:**
*Setting inside module "Topographical + Roads" doesn't differ from "Full satellite + Buildings". In both cases only thing you get is Topographical map with roads. MicroDAGR will never show those buildings and satellite layer.*

**Steps to reproduce:**
* *Place MicroDAGR module, set to Topographical + Roads*
* *Test, see that you have topographical map and roads are visible on MicroDAGR*
* *Switch module to Full satellite + Buildings*
* *Test, you still have only topographical and roads*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*Nothing inside of it*

**Comment by VKing6** [comment]
To see the full satellite and buildings you must click the map button on the DAGR a second time to toggle.
If the module is set to Topographical+roads, this action is unavailable.

**Comment by gienkov** [comment]
Then it should default to Satellite + Buildings. That should be included in documentation.

**Comment by VKing6** [comment]
I disagree. I prefer the clean map.
The documentation should be created, though.

**Comment by gienkov** [comment]
I mean it should default to Satellite + Buildings if module is set to this exact option, and there should be note that it still can be switched to Topographical + Roads.
