### ISSUE TITLE
Modded clothes, feet interaction underground

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#1346]
ACE3 Version: 3.0.1

Mods:
@cba_a3
@ace3
@rhs_escalation
@k_mnp
@caf_ag

Placed ACE3 Modules:
N/A

Description:
When trying to ACE interact with someone's legs then the "right leg" and "left leg" interaction points are under the ground when wearing some uniforms. On the bright side all the vanilla uniforms work.
These include but are not limited to : 
* all the RHS uniforms
* a few k_mnp uniforms
* all the caf aggressors uniforms

Steps to reproduce:
Get some ai dude or a friend to wear some rhs uniforms and try to interact with this legs, they gon' be under the ground!

Where did the issue occur?
EVERYWHERE.

PS! 
I don't really blame you guys.... but apparently people are not making mods according to correct arma 3 standards. Maybe you guys have some influence over them and can help solve this issue with the modding community :)

**Comment by jonpas** [comment]
Is known, those mods are using old BI uniform inheritance which was broken in the same way, it is up to the authors of respective mods to fix it.

**Comment by esteldunedain** [comment]
BIS units used to be broken too (and some apparently still are). Those mod makers probably based their work on BIS' errors, hence the problem. We asked BIS to provide information about the problem so mod makers can fix them, but they haven't replied yet:

http://feedback.arma3.com/view.php?id=20761

**Comment by ajvorobiev** [comment]
RHS units will have this fixed in 0.3.8 release.

**Comment by jonpas** [comment]
Awesome to hear @ajvorobiev !

**Comment by esteldunedain** [comment]
Great news @ajvorobiev! Could you give as a pointer about what needed to be fixed? Other unit packs have similar problems and we don't know what it takes to fix them.

**Comment by ajvorobiev** [comment]
Easy fix: delete all mem points and replace them with BIS Sample soldier mem points. The long story: LeftLeg and LeftUpLed (same for right) selections were missing in old setup.

**Comment by esteldunedain** [comment]
Thank you very much!

**Comment by jaynus** [comment]
SoulAssassin has provided fix details on the A3 tracker

**Comment by BullHorn7** [comment]
Is it possible to fix before 0.3.8? Like, open the .pbo and edit the lines ourselves?

**Comment by ajvorobiev** [comment]
Quite impossible. Just wait for the release. It will not be long now.
