### ISSUE TITLE
A-10-D Thunderbold II - Lasercodes - GBU guiding - Lockon

### ISSUE THREAD

**Issue by Nagrach** [acemod/ACE3#1363]
ACE3 Version: 3.0.1

**Mods:**
@cba_a3
@ace3
@Tfar (editor / Singleplayer tested without Tfar)

Placed ACE3 Modules:**
BFT
Interactions

**Description:**
Its not possible to change/select a lasercode in a A10(A164) nor lockon onto a laser

Something i found in a hurry:
22:18:47 soldier[I_Soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
22:18:56 Ref to nonnetwork object 86db4080# 1803594: pilot_f.p3d
22:18:57 Ref to nonnetwork object 86db8080# 1803602: pilot_f.p3d
22:20:38 Protocol bin\config.bin/RadioProtocolENG/: Missing word obj_LaserTarget

**Steps to reproduce:**
Place A10D (164) 
Place autonom lasermarker Nato - ( crosstest )
Place Pilot with UAV terminal + Lasermarker + Battery 
Connect UAV Terminal with marker - mark something (code 1001 and 1005 tested)
Switch to Pilot lasermarker - switching codes (working)
Enter A10 - switching code - NOT working
Start and begin a bombing run with matching directions (Mark from North to South - attack from North to South)
Try to lock the laser target - Not possible

**Where did the issue occur?**
Singleplayer - Fixed Wing Presentation
Multiplayer - Editor tested
Multiplayer Server tested

Pastebin RPT

http://pastebin.com/ye1wJcKU

**Comment by Nagrach** [comment]
i noticed that under ACE3 - Nato lasermarkers shown as hostile AIR contacts on Radar.
If i remember right - thats not right

**Comment by alganthe** [comment]
Gbu locking is disabled atm, this is a non issue.

**Comment by Nagrach** [comment]
From Reddit
_________________________________________________
"[–]jaynus 1 Punkt 1 Tag zuvor 
DAGR:
You need to turn on your laser designator first, which is inside your self interaction when in the gunner seat. The missile will not guide on anything when you do not have a laser to guide it with.
GBU:
Not enabled yet. Should just lock like regular crappy Vanilla stuff 
AA:
No changes, should just lock like regular crappy vanilla stuff" 
__________________________________________________
Vanilla locking is broken if this statement is right.
AA on A164 (A10D) and Neophon is broken too.
Only Buzzard vanilla AA are working.
F18 Wasp AA is working too.

**Comment by alganthe** [comment]
this is outdated information, after doing the doc I asked jayjay about that, he said that locking was disabled for GBUs, only AA missiles should work.

**Comment by jaynus** [comment]
I'm giving the inheritance ANOTHER pass today.

**Comment by nibbles-** [comment]
What is the reason for disabling this for GBU? 
Is it a "bug" or a design decision? 
Will it get changed/ fixed?

**Comment by alganthe** [comment]
It's more realistic that way
design decision
no

You need to approach the target from the right direction and be high enough / far enough for the GBU to lock on the laser and guide itself.

**Comment by gienkov** [comment]
Exactly.

**Comment by nibbles-** [comment]
So what is high enough and far enough? There seems to be no (visual) indicator whatsoever

**Comment by gienkov** [comment]
Try 2.5km dist. and 2km height and go from there (5km dist / 4km height and
so on).

**Comment by nibbles-** [comment]
I would asume there is some reality based fixed numbers for this?

And no indicator whatsoever?

**Comment by alganthe** [comment]
No indicator, at all.
for the distance it's mostly based on the vertical and horizontal speed of the GBU (like in vanilla, but no locking box) and the visibility of the laser for the GBU (same as vanilla but no box)

**Comment by Nagrach** [comment]
From my PoV
Disabling the GBU targeting as default setting is utterly wrong. 
Without a proper working CCIP / Targeting Pod and all the other stuff that comes with every A10 since 2011 - bombing isnt more realistic its just WW I bombing on sight.  
Removing gameplay mechanics to provide realism without providing the proper tools is just wrong. 
Specially since arma isnt realistic at all when it comes to view distance/render distance and the ability to spot targets from greater distances without the fear of a 10fps slideshow game.

May its a good start to add the Radar display from Kimis HMD and add an extra radar box for Laser signals.
And remove the lockon box with an audio signal and a new HUD element

**Comment by TheNiner** [comment]
> It's more realistic that way

That's funny, because in real life when you're using a Pave Penny (or basically any laser tracker I guess), it shows a small indicator in your HUD. 
> "It could take two to three seconds for the Pave Penny to acquire the laser energy and then present its laser spot tracking diamond in the **HUD over the target.**

A quote from the book *A-10 Thunderbolt II Units of Operation Enduring Freedom 2002-07 Page 50 (http://bit.ly/1JTMk1L)*. So please do some research before you're claiming that someting is realistic.

**Comment by zepplin1** [comment]
my community has been testing this extensively to see why our aircraft cannot pick up a laser designation. from what I understand is its still the vanilla functions (select target, lock, and drop) but without the locking box etc. So we have been trying to guess speed, altitude, aoa with no luck what so ever. it seems even the AI have had issues and was trying to just drop the bombs without locking.

has anyone had any luck!?

**Comment by lswinkels** [comment]
We have experienced the same issue. Found it was the ace_laser_selfdesignate, Ace_laserpointer and ace_missileguidance any one of those pbo's caused the issue. So we just removed them from our ace repo and all is now well. You need to remove ace_javelin also as it depends on missileguidamce. None of the above pbo's really effect out community so easy choice to remove. Not being able to laser designate effectively though was a big issue.

**Comment by Nagrach** [comment]
Atm we solved this like Iswinkel by removing any laser related *pbo from our ace.
This included the Yardrange.pbo.

**Comment by captainblaffer** [comment]
Same issue with the UAV GBU lock-on. It doesn't work. Please fix, thanks!

**Comment by JonenKone** [comment]
Would it be possible to get the ACE FCS documentation to mention correct ACE lasing procedures? Currently there is no information available and it´s hard not to consider the module broken without any instructions on how it is supposed to work (this was the only thread i found where it is explained).

**Comment by LAMBSAizen** [comment]
All they have done by disabling this is taking away the otherwise encouraged teamplay. NO realism effect at all. 
more like "hey this game is set to be taking place in near future, but bomb still works like its in 1940".

**Comment by nibbles-** [comment]
How about a 3.3.3 where #2560 is included?

**Comment by LAMBSAizen** [comment]
include GBUs geez.

**Comment by LAMBSAizen** [comment]
Atleast . and I meen ATLEAST add it as an option to turn off. Heard communities going away from ace due to this unexplainable feature alone.

**Comment by nibbles-** [comment]
@LAMBSAizen Relax the linked fix is coming in 3.4.0. I was just asking if they would release a 3.3.3 with this fix.

**Comment by Kocrachon** [comment]
So, @nibbles- mentions it is coming apparently, I would still like to understand the previous "why" to this back then? This was in no way realistic... even in the early 80s, the paveway project had little screens that were nothing but a bunch of static, and a "white area" showed up for the pilot to lock onto, and so they could know when to drop.

Combine this all with the fact that the game lacks CCRP and CCIP of any kind, you basically broke one of the best mechanics arma ever had. So I don't get the "realism" aspect this was meant to create at all. Even if something lacks a good system, such as a Mirage 2000C without a lantern pod, they still  have to tools to lock onto the laser. A-10s have had laser search function since desert storm. And since we cannot use the actual MFDs in this game, the old ArmA way of having it a lock on via hud option is not that far off from being realistic.

**Comment by BaerMitUmlaut** [comment]
> even in the early 80s, the paveway project had little screens that were nothing but a bunch of static, and a "white area" showed up for the pilot to lock onto, and so they could know when to drop

Can you post a source for that? Because that's the first time I hear of something like that and I couldn't find a source for it myself.
As far as I know (by reading up on various sites and the DCS A10C manual) the bomb locks onto the laser after it was released, or rather the laser only then gets turned on to increase the chance of a hit. There is nothing the pilot can "lock on" to at all, not without a targeting pod.

>Even if something lacks a good system, such as a Mirage 2000C without a lantern pod, they still have to tools to lock onto the laser.

Since you seem to be quite sure about that, mind explaining how?

**Comment by TheNiner** [comment]
As i wrote earlier:
> [...] it shows a small indicator in your HUD. 
>> It could take two to three seconds for the Pave Penny to acquire the laser energy and then present its laser spot tracking diamond in the **HUD over the target.**

> A quote from the book *A-10 Thunderbolt II Units of Operation Enduring Freedom 2002-07 Page 50 (http://bit.ly/1JTMk1L)*.

**Comment by BaerMitUmlaut** [comment]
The Pave Penny is a device that finds laser marks and shows them on the HUD, that does not mean anything "locks on". Additionally, by the sounds of it said mark was also used for A10 gun runs ("We strafed the target area several times..."), and not for dropping a bomb.

I am not certain but I believe laser marks still get shown in the HUD (I know they do in the Comanche), so the Pave Penny still gets "simulated".

**Comment by Kocrachon** [comment]
Without posting docs that I cant really post, I can cover this much.

First, An A-10C can lock onto a laser;s location. The targeting pod will perform an LSS which will search for a laser with the set code. At that point the TGP will lock onto the location where the laser was point at the time. From there, the TGP will lock to that location and will allow for the calculation for CCRP to know when to drop the bomb for a good hit.

If using the A-10s laser, the laser will turn on based on what the pilot set the profile to. In the case of a buddy laser, the bomb will likely lock on 3 seconds after drop. Not sure why its a practice now, but it used to be a practice to turn on the laser 7-10 seconds before impact to prevent the laser burning out (not sure thats still a problem these days, I highly doubt it)

As for the old system. I can't find any online sources, so I will try to explain the system as best as I can. The system you refer to, the Pave Penny, was nothing more than a item that could find the laser.

Anyways, the old system did not post anything onto the HUD per say. Imagine one of your MFDs was a TV of nothing but black static. Once you get in range of the laser from a buddy lase, your black static TV would have a little ball of white static, which is where the laser would be. You would need to use that ball of static to identify when to drop the bomb. The ball would need to be centered, and its size would indicate its range from the target. 

Again, this was in the 80s. Seeing as this is all supposed to be futuristic, you can imagine that the A-10D in the game SHOULD have a better laser system, or at least what we have in modern days. Especially considering the A-10 has a built in pave penny... 
https://upload.wikimedia.org/wikipedia/en/thumb/f/f8/Pavepenny.jpg/220px-Pavepenny.jpg

As for the Mirage, rom my understanding, has the same capability as the A-10s pave penny. So the old mirage 2000C did not have its own laser pod, requiring on buddy lasing. But again, this is technology from the 70s/80s. The mirage 2000D added laser pods which allowed it to deploy its own laser, but the Mirage 2000C did not. There are no copies of the manual in english, so I don't have any real documents to provide for that.

**Comment by BaerMitUmlaut** [comment]
Unfortunately, the vanilla A10 does not have a targeting pod (neither in the model nor in any technical way) even though it totally should. This is probably another thing ACE3 has to implement. The model does however have a Pave Penny - go figure!

You can find the DCS A10C manual here: https://http3.files.eagle.ru/dcs/manuals/DCS-A-10C_Flight_Manual_EN.pdf
It's of course not the real life manual, but it should give you a good starting point. The LGB stuff starts at page 549.

**Comment by nibbles-** [comment]
Is this supposed to work now?

I did a short test yesterday (AI - NATO JTAC, Me in A10 and AiA Armed Targets) 
I was not able to lock at anything using TAB and "Free firing" the GBU went soso...

**Comment by bux578** [comment]
as it is disabled, close?
