### ISSUE TITLE
Safemode script error, still works anyway

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1364]
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3
* @acre2
* @rhs
* @bwmod
* @kunduz
* @leightopforpack

**Placed ACE3 Modules:**
* *Not relevant*

**Description:**
*I am using this below to make my units do safe weapon at mission start:*
```
private ["_unit","_typeofUnit"];
_typeofUnit = toLower (_this select 0); // used for other things
_unit = _this select 1;

[...]
[removing weapons, adding weapons...]
[...]

[_unit, currentWeapon _unit, currentMuzzle _unit] call ACE_SafeMode_fnc_lockSafety;
```
It is launched from units init field like that:
```
ek = ["tl",this] execVM "ek\loadout.sqf";
```
And it gives error for some at mission start:
```
2015/05/22, 17:16:15 Error in expression <ace_safemode_actionID", _id];
};

_unit selectWeapon _muzzle;


[_unit, _weapon,>
2015/05/22, 17:16:15   Error position: <selectWeapon _muzzle;


[_unit, _weapon,>
2015/05/22, 17:16:15   Error selectweapon: Type Number, expected String
2015/05/22, 17:16:15 File z\ace\addons\safemode\functions\fnc_lockSafety.sqf, line 56
```
Weapon is added **before** this line execution.
**Important thing is:** weapon is still put into safe mode at mission start, it is just this error that shows up.
Script I use has locality check and JIP check and all that stuff, so those lines are executed only on player PC.

**Steps to reproduce:**
* *Well you can download mission I made and see for yourself, you only need to get into the briefing screen and the error will pop up*
Link here: http://steamcommunity.com/sharedfiles/filedetails/?id=447016887

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
```
2015/05/22, 17:16:15 Error in expression <ace_safemode_actionID", _id];
};

_unit selectWeapon _muzzle;


[_unit, _weapon,>
2015/05/22, 17:16:15   Error position: <selectWeapon _muzzle;


[_unit, _weapon,>
2015/05/22, 17:16:15   Error selectweapon: Type Number, expected String
2015/05/22, 17:16:15 File z\ace\addons\safemode\functions\fnc_lockSafety.sqf, line 56
```

**Comment by PabstMirror** [comment]
The error is because `currentMuzzle player` seems to return 0 when seated in a cargo position.
Our code wouldn't normally have this problem because you can't safe while inside vehicles, but it's an easy fix for people who want to externally call this func.
