### ISSUE TITLE
Empty Magazines

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#137]
We had some discussion about dealing with empty magazines.

Right now when you reload, the magazine disappears.  This is semi-reasonable from BIS perspective, because empty//partial mags have the same mass as full.

For realism, people could want to repack empty magazines.  Example would be a crate of unpacked//loose ammo that you can repack from.

Empty magaqzines don't show up in `magazines`, `magazinesAmmo` or even `magazinesAmmoFull`.  The best we can do to detect them is checking `uniformItems` and counting the difference.

Repacking (#131) can't detect them from `magazinesAmmo` so they will probably get nuked from repacking.

This is all fine for now.  But maybe down the line we would want to do something with "empty magazine sack" and a more realistic simulation of reloading.

**Comment by ulteq** [comment]
+1 on a more realistic simulation of the magazine repacking process. Maybe we can port some of what we did in CSE?

**Comment by esteldunedain** [comment]
> Maybe we can port some of what we did in CSE?

Check the current version first.

**Comment by PabstMirror** [comment]
#414

**Comment by RazorRod123** [comment]
Was recently looking at implementing something like this for my community and with the incoming  "Reloaded" event handler with Arma 3 version 1.57.
Simple Example:

```
player addEventHandler ["Reloaded",
{
	_object = _this select 0;
	_oldMag = _this select 4;
	if (_oldMag select 1 == 0) then  //Check if  the old mag is empty 
	{
		_object addMagazine [_oldMag select 0, 0];
	};
}];
```
Disclaimer: 
The above code has not been tested in the dev branch and I do believe the above example may have issues with the "throw" and "put" weapons.

In regard to checking inventory for repacking magazines I'm not sure how your implementation works but empty magazines added using the code above can be detected using the commands "uniformMagazines", "vestMagazines ", "backpackMagazines and soldierMagazines".
(commands tested in Arma 3 version 1.56)

Resources:
https://community.bistudio.com/wiki/Arma_3:_Event_Handlers/Reloaded
