### ISSUE TITLE
Port of AGM's night vision brightness adjustment is worse than CSE's implementation

### ISSUE THREAD

**Issue by ShocknAw3** [acemod/ACE3#1374]
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
none

**Description:**
Adjusting the brightness of the night vision in its current form is useless. Every setting that deviates from zero gives you a worse image. CSE pulled this off much better. Is it possible to port over CSE's solution instead, seeing as this is a merger between those mods?

**Steps to reproduce:**
1. Equip night vision
2. Adjust brightness using alt + page up and alt + page down

**Where did the issue occur?**
Tested in editor preview.

**RPT log file:**
n/a

**Comment by esteldunedain** [comment]
@Glowbal, we were never satisfied with agm's solution, but we couldn't get it to work better; how did CSE did it?

**Comment by PabstMirror** [comment]
Someone was telling me we should look into using `setAperture`, but I haven't had much luck getting any good effects with it yet.

**Comment by esteldunedain** [comment]
I tried that too once without success

**Comment by Glowbal** [comment]
CSE:
```sqf
_ppEffect_NVGAdjustBrightness ppEffectAdjust [1, _newBrightness, 0, [0, 0, 0, 0], [0, 0, 0, 1], [0, 0, 0, 1]];
```
ACE:
```sqf
GVAR(ppEffectNVGBrightness) ppEffectAdjust [1, 1, _brightness / 4, [0, 0, 0, 0], [0, 0, 0, 1], [0, 0, 0, 1]];
```

**Comment by Glowbal** [comment]
I first used `setAperture` but I only got horrible results with it.

**Comment by esteldunedain** [comment]
Well, simple enough. Definitely worth trying. If someone doesn, please make some screenshots for comparison.
