### ISSUE TITLE
Unload patient does not work

### ISSUE THREAD

**Issue by Desty84** [acemod/ACE3#1375]
ACE3 Version: 3.0.1

Mods:
@cba_a3
@ace3
@rhs escalation
@tfar

Placed ACE3 Modules:
All Modules

Description:
You can´t unload unconcious players out of a vehicle,
We tried this with multiple persons on multiple vehicles (Ghosthawk, RHS Blackhawk, RHS RG33, Hunters).

Steps to reproduce:
Get a player unconcious, load him into a vehicle.
Then try to unload him.

Where did the issue occur?
Multiplayer - Dedicated Server

**Comment by gienkov** [comment]
Yes they jump back in instantly. Encountered in MP.

**Comment by ViperMaul** [comment]
Confirmed in 3.0.1. 
This did not happen in 3.0.0

**Comment by ViperMaul** [comment]
I updated my post above as I went back to retest 3.0.0.3 
This bug was indeed there in Dedicated MP

**Comment by Glowbal** [comment]
This might be due to a locality issue.
