### ISSUE TITLE
Getting damage in the "vanilla" Medic System

### ISSUE THREAD

**Issue by Desty84** [acemod/ACE3#1377]
ACE3 Version: 3.0.1

Mods:
@cba_a3
@ace3
@rhs
@Tfar

Placed ACE3 Modules:**
All

Description:
In Vehicle crashes and damage like falling, you sometimes get damage from the vanilla medsys.
You then get a blurred screen like in vanilla and can´t threat this damage, since there are no wounds.

Steps to reproduce:
Place a unit and jump off some lower heights or get slowly pushed by a vehicle.
If does not happen very often, but after some time you will just die from this.
(it can be treated with a PAK)

Where did the issue occur?
Multiplayer - Dedicated Server

**Comment by bux578** [comment]
Duplicate #1354 

(Thanks for reporting, though)
