### ISSUE TITLE
Medics don´t have an interaction menu in a medical vehicle

### ISSUE THREAD

**Issue by Desty84** [acemod/ACE3#1379]
ACE3 Version: 3.0.1

Mods:
@cba_a3
@ace3
@rhs escalation
@tfar

Placed ACE3 Modules:
All Modules

Description:
As medic, you don´t have an interaction menu inside a medical vehicle.
Which means you can not treat anyone inside this vehicles.
Both, Medics and Vehicle got marked over synchronising them with the module.
(also tried it with naming them in the module)

Steps to reproduce:
Set 2 players, mark one as medic.
Bot get inside a vehicle that is marked as medic vehicle.
Try to interact.
The one that is not a medic is able to interact with the vehicle.

Where did the issue occur?
Multiplayer - Dedicated Server

**Comment by Glowbal** [comment]
This might already fixed on the latest master.

**Comment by Blackswater** [comment]
can confirme this bug even with the latest update. here is picture I got, I will try to get a rpt-log

http://i.imgur.com/8GHZVr5.jpg

**Comment by Glowbal** [comment]
@Blackswater Thanks for the screenshot. That error has already been fixed on the latest master. It will be included with the next release.

I'm closing this, assuming fixed. If this occurs again after 3.1 please make a new ticket and we will investigate.
