### ISSUE TITLE
Stringtable macros

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#1380]
Just a little proposal to add macros for strings in `stringtable.xml`, pointed here to post in issue by @ViperMaul to discuss name of strings and if this is something that would be contributing to the project.

The only one existing is the following one in CBA currently, which doesn't fit ACE3 (wrong order and no quotes):
`#define LSTR(var1) TRIPLES(ADDON,STR,var1)`
Example: `LSTR(banana) == ACE_Module_STR_banana`

I propose the following 2 macros:
`#define STRING(var1) QUOTE(TRIPLES(STR,ADDON,var1))` (Script String, no `$`)
Example: `STRING(banana) == "STR_ACE_Module_banana"`
`#define CSTRING(var1) QUOTE(TRIPLES($STR,ADDON,var1))` (Config String, requires `$`)
Example: `CSTRING(banana) == "$STR_ACE_Module_banana"`

If this is deemed to be useful for ACE3 and names of macros are confirmed on I will implement it and also change all of it in the entire repository (yay regex).

**Comment by NouberNou** [comment]
If it is specific to an ACE format then it should probably be added to ACE. Anything to make string tables easier.

**Comment by jonpas** [comment]
Not sure but many mods I checked do stringtables that way nowadays, could maybe be useful to be added to CBA directly (gives some standard)? 

Last question is if macro name is good or should it be something else (compatibility, readability...)?

**Comment by esteldunedain** [comment]
I think this macros would be fine. I'd say add them to ace_main. Eventually it can be moved to CBA or not. We already have various macros there that are CBA worthy but haven't been moved yet.

**Comment by jonpas** [comment]
I'll work on a PR in the next days.

To not make a new issue for it, what about macros for CBA functions?
Example: `CBA_FUNC(bananaHolder) == cba_fnc_bananaHolder`
I have the same for ACE's function in our community's repository. I don't see it being a big change though, not like CBA will ever change it's prefix. :grin: 

More important one I got an idea of is path macros.
Example: `ACE_PATH(bananaModule,script) == \z\ace\addons\bananaModule\script.hpp`
Could be used for both definition of script_component.hpp in the root of module folder and in functions folder, hence why 2 variables passed into the macro. Thoughts?

**Comment by esteldunedain** [comment]
Yeah, I don't think the CBA macro really does anything. tbh I'm not convinced about ACE_PATH either, as it has limited usability.

**Comment by jonpas** [comment]
It would make `#include`s nicer, but yeah I agree, limited usability.
