### ISSUE TITLE
MP Explosive Defusal Issue

### ISSUE THREAD

**Issue by legman** [acemod/ACE3#1381]
**Mods**
@cba_a3
@ace3

**Placed ACE3 Modules**
ace_explosives

**Description:**
Players cannot defuse other players explosives due to the defuse option in the interaction menu being drastically offset from explosive or not being present at all.

You can move around the explosive to find the interaction spot. Defusing your own explosives works absolutely fine.

**Steps to reproduce**
Join an MP dedicated server with 2 players. The first player places any explosive and arms it with timer/clacker etc. The second player grabs an ACE_DefusalKit and approaches the explosive, they will not be able to defuse it due to no interaction menu - the first player can defuse his own explosive.

**Where did the issue occur?**
MP Dedicated

**Comment by pmc-tyler** [comment]
Someone I was playing with last night was reporting the same issue.

**Comment by legman** [comment]
I hate to be a nuisance but is there any chance this bug would be fixed in time for the **3.1.0** release? Let me know if there is anything I can do to help out!

**Comment by PabstMirror** [comment]
attachTo seems to be broken for CfgAmmo
different getPos on the same defuse object

![cfgammo](https://cloud.githubusercontent.com/assets/9376747/7819256/02a835ee-03a6-11e5-939a-14a5dfd0aea8.jpg)

I think we need to switch to local defuse objects per client:

**Comment by esteldunedain** [comment]
> I think we need to switch to local defuse objects per client:

Sounds reasonable.
