### ISSUE TITLE
When placing explosives you can neither rotate them using mouse wheel nor cancel placing by RMB

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1382]
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None*

**Description:**
*When the user selects explosive to place, he gets 3 options under mouse buttons: he can place explosive (LMB), he can rotate it (scroll wheel + modifier key) and finally he can cancel placing (RMB). Thing is, you cannot rotate using mouse wheel and you cannot cancel the placing using RMB. That is the issue.*

**Steps to reproduce:**
* *Select explosive to place*
* *Try to rotate or cancel placing*
* *You cannot do this*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*Not needed*

**Comment by pmc-tyler** [comment]
The rotation can be fixed by unbinding and rebinding the modifier key in your ACE common controls. The right click issue is currently broken and reported as BIS' fault. Current workaround for canceling is to hit your interaction key.

**Comment by redstorM77** [comment]
Hey, the unbinding and rebinding fixed the rotation for me. 
But I cannot place the explosive with LMB, instead i use my weapon and shoot a few rounds.
Any solution on this?
