### ISSUE TITLE
Stuck in animation: Player dies while arrested

### ISSUE THREAD

**Issue by swissMAG** [acemod/ACE3#1384]
Good day, ACE Team.

ACE3 Version: 3.0.1
ArmA3 Stable 1.44.130654

**Mods:**
* @cba_a3
* @ace3
and quite alot more. (-> listed in the RPT)

**Placed ACE3 Modules:**
Advanced Medical

**Description:**
We noticed that when a player dies, while he is flex cuffed, he will respawn arrested again, but cannot be set free by anybody. The player has to disconnect, return to the lobby and select a new slot.

**Steps to reproduce:**
1. Arrest a player
2. Arrested players dies and respawns
3. Player will go into arrested position again, cannot move, but can use the action menu and drive arround in vehicles

**Where did the issue occur?**
Dedicated Server

**RPT log file:**
http://pastebin.com/PuwTf6ph

Just a small issue. Player is dead anyway.

Thanks for ACE. Loving it.

**Comment by PabstMirror** [comment]
Thank you for the report.
This was solved with c4e5e9a7ac6c87d61a68dff59043e478b90e079f and will be fixed in next release.
