### ISSUE TITLE
Adding frag to scripted explosives

### ISSUE THREAD

**Issue by legman** [acemod/ACE3#1385]
I have a question for the ACE team - I have been trying to make certain explosives use the ace_fragmentation system but adding the properties alone doesn't seem to work.

For example...
ace_frag_metal = 210;
ace_frag_charge = 185;
ace_frag_gurney_c = 2843;
ace_frag_gurney_k = 3/5;
ace_skip = 0;
ace_enabled = 1;
ace_force = 1;

These properties were added to IEDUrbanSmall_Remote_Ammo and seemed to make zero difference.

Could someone explain if I am missing anything in particular.

Thanks

**Comment by PabstMirror** [comment]
I don't think explosives ever get a "fired" event with our system, which is how the frag system is triggered

For tripflares I have something trigger on explosion; we might be able to adapt that to a general "explosive-went-boom" event and have frag trigger off of that for explosives?

**Comment by jaynus** [comment]
I'll take it, as frag just got reworked anyways

**Comment by esteldunedain** [comment]
@legman: it's:
```
ace_frag_enabled = 1;
ace_frag_skip = 0;
ace_frag_force = 1;
```
instead of 
```
ace_enabled = 1;
ace_skip = 0;
ace_force = 1;
```

**Comment by esteldunedain** [comment]
> I don't think explosives ever get a "fired" event with our system, which is how the frag system is triggered

That's completely true

> For tripflares I have something trigger on explosion; we might be able to adapt that to a general "explosive-went-boom" event and have frag trigger off of that for explosives?

Yeah, we may want to work on those ammo events, at least for explosives

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
