### ISSUE TITLE
[Bug] Cannot interact with players legs for healing

### ISSUE THREAD

**Issue by Khaosmatic** [acemod/ACE3#1391]
Injured either by falling or being shot and when the medic attempted to heal someone elses legs no actual option appeared in the interaction menu. Arms, torso and head were able to be healed but no option for the legs.

The standard ACE medical module was used without any changes to its settings. RHS escalation was also used during the session.

**Comment by jonpas** [comment]
Thank you for your report, but please use the following guidelines for reporting issues: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by alganthe** [comment]
It's a known issue, some people use fucked up inheritances or memory points  for uniforms and units thus the interaction points are in the ground

**Comment by jaynus** [comment]
Thanks for the report. RHS has fixed their units and this will be fixed in their next release

**Comment by Legolasindar** [comment]
For the moment, you only need look the foots for heal, the interaction point is in the foot, not in the leg.
