### ISSUE TITLE
Add wakeup feature from AGM

### ISSUE THREAD

**Issue by Kilo1-1** [acemod/ACE3#1393]
Hello,

I have looked all over the medical features and modules and I cannot figure out anything about the unconscious wakeup feature that was part of AGM medical.  This was a handy feature depending on your medical status as you could wakeup from being unconscious and use that time you are up to slowly move around to cover or eliminate some targets.  Am I missing something or is this something that can be added to both ACE3 basic medical and ACE3 advanced medical?

**Comment by bux578** [comment]
Thank you for your request, but this a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
