### ISSUE TITLE
Prevent Instant Death not working (Zeus bug?)

### ISSUE THREAD

**Issue by Soronelite** [acemod/ACE3#1395]
Hi !

I already saw their was repports about this, and they were solved. 

Yesterday I was playing Zeus with my squad, medical module on with "Prevent instand death : yes". (Module was placed on the editor).

90% of time, player were killed instant (explosions or bullets) and respawn instant at base. 

We have make some test before the zeus and their was no issues.
We'll make new test during the week, but i'd like to repport this anyway just in case ;)

Thanks

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by GitHawk** [comment]
Either the handleDamage event handler has some loop holes or BIS/CBA has.
This causes vanilla damage and if the vanilla damage is too high, the player dies.

**Comment by Soronelite** [comment]
Ok sorry Bux.
We'll make another zeus tonight so I'll check if the bug still hapen or not and let you know ;)

**Comment by Soronelite** [comment]
So after more tests I don't know what to say... Its seems to be "random"...
Sometime we do have unconscious state, sometime its instantdeath...
If you want I can take you a screen of our medical modul setting? If it can help.

**Comment by Jastreb** [comment]
I hate being a smartypants here but > http://ace3mod.com/wiki/user/how-to-report-an-issue.html

We don't know what you were running which version, were there any entries in the rpt or whatnot. I rarely play as Zeus but can you be more specific? You were playing ZGM mission and players had this issue or the game master himself or what?

**Comment by Soronelite** [comment]
So :
ACE3 Version: 3.0.1 (lasted on PWS)

**Mods:**
@cba_a3
@ace3
@RHS 
@TFAR
@AIA Terran Pack
@ARC units
@CAF Agressor
@RDS
A lot of weapons pack (RH, TF47, CUP, etc.)

**Placed ACE3 Modules:**
Nearly all of them

Medical modules :
Medical setting
Revive setting
Set medic class


**Description:**
We have played 3 missions (3 Zeus) with ACE3 so far, in two of them the uncounsious state was not working : instant death. (For players)

(BTW, with instant death and "save gear : yes" some player loosed their backpack, should I make another issue repport for that too?)

In my point of view, some module do not excute or initialized, for example we use the blufor-tracking, with options :
- Hide AI group
- Delay : 60
But in game we do see AI groups, and there is no delay.
So maybe the medical module do not excute too and keep default setting?

**Comment by Glowbal** [comment]
Please confirm your issue is also present with just CBA and ACE. Could you also provide an rtp file (preferably both server and client(s)).

Save gear and blue force tracking are separate issues, please file a separate bug report for those.

**Comment by Jastreb** [comment]
Hm, do you use 'ace_server.pbo' and '/userconfig/ace/serverconfig.hpp' ? If you do this config is used and it overrides any other setting, so modules in a mission or anything else wont work if you 'force' settings trough the server config. Check that please before anything else. And then try with just @cba & @ace3. I use @RHS, @AIATP, @TFAR & @RDS but I cant reproduce this.

**Comment by derdeagle** [comment]
I had the same problem when using FFIS (Fire-Fight Improvement System). Check your with only essential mods as Glowbal and Jastreb said.

**Comment by Kilo1-1** [comment]
My group is using FFIS and prevent instant death works fine for us, provided everyone respawns once.  Weird behavior might I add, maybe it is FFIS causing that issue.

**Comment by bux578** [comment]
close?

**Comment by commy2** [comment]
Assumed fixed. Please create new ticket if issue persists. (Probably has a duplicate somewhere already anyway)
