### ISSUE TITLE
Respawn Bug

### ISSUE THREAD

**Issue by FallenHorseman** [acemod/ACE3#1400]
ACE3 Version: 3.x.x

**Mods:**
* @cba_a3
* @ace3
* @TFAR
* @Blastcore (optional)

**Description:**
I don't know if it belongs here.
I have some issues with the current version of Ghosts Enemy Assault.
As its has an own Revival Script (which I also turned of)

If I die, i will suddenly respawn on the same position which i died,
With the default gear and an new Player name.

**Steps to reproduce:**
Download current version of Ghosts Enemy Assault, choose any settings.
Throw a grenade and watch her as near as possible.
After a few seconds:He's alive .

**Where did the issue occur?**
multiplayer.

**Comment by jonpas** [comment]
This doesn't sound like ACE3 nor does it sound like a bug, more like mission settings/configuration/setup.

**Comment by esteldunedain** [comment]
Sorry, that's due to how the mission is setup. You can't expect to just be able to run ACE flawlessly with stock missions not written for it without addapting them.
