### ISSUE TITLE
Which Ballistics information does the m2010 as .300 in the AtragMX?

### ISSUE THREAD

**Issue by enderrrrrrrrrr** [acemod/ACE3#1402]
There are 3 separate options for .300

**Comment by ulteq** [comment]
The `ace_compat_rhs_usf3.pbo` makes the XM2010 shoot the Berger Mk248 Mod 1 (220 gr SMK) bullet

**Comment by enderrrrrrrrrr** [comment]
Thank you. Additionally do you know if there is documentation on the
Advanced Ballistics module anywhere?

**Comment by jonpas** [comment]
All documentation can be found on the following page http://ace3mod.com/wiki/index.html
Go to Mission Maker and you'll see modules there.
