### ISSUE TITLE
Medical litter placed even though medical action is canceled

### ISSUE THREAD

**Issue by WadeDP** [acemod/ACE3#1403]
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None.

**Description:**
When performing a medical action, and then canceling, litter is still placed on ground.

**Steps to reproduce:**
Bandage, then cancel mid-action.

**Where did the issue occur?**
Editor, and Multiplayer.

**RPT log file:**
http://pastebin.com/Kq9SHfLx

**Comment by PabstMirror** [comment]
We call createLitter on success or failure.  I think that's by design, but we also seem to give back the item, so I'm not sure.

**Comment by jaynus** [comment]
I think this is by design - as canceling bandaging someone still means you dirtied a sterile packaged bandage.

**Comment by jonpas** [comment]
Yeah, but if the item is given back that defeats the purpose, no? Except if that item then has a chance of failure or worse heal factor or something.
