### ISSUE TITLE
Blood/saline/plasma bags seem to all transfuze 1000ml

### ISSUE THREAD

**Issue by R4ppiT** [acemod/ACE3#1407]
I was fooling around with the advanced medical system tonight and it seemed like every size of the bags transfuzed 1000ml of the substance. It atleast counted it down from a 1000ml.

Also the 250ml and 500ml saline bags weigh the same amount.

E: It says that morphine is supposed to affect for about 15 minutes for me it seemed like it only worked once and if you got shot after that the pain would come and there is no way of getting rid of it.

**Comment by PabstMirror** [comment]
Fixed on master via: d82fcd1f96c025d549014f25cefd0a638b29843e
Will be in next release
