### ISSUE TITLE
Rifles are heating up very slowly

### ISSUE THREAD

**Issue by Lumnuon** [acemod/ACE3#1413]
After 9 Magazines shot with the MX, the Rifle is heated up the the half of the Bar. It´s nearly the same with all other Assault Rifles. ARs should heat up faster probably.

**Comment by esteldunedain** [comment]
Half the bar is very hot! (around 500º), and it's physically accurate. The fx showing how hot is that and other imrpovements to overheating are almost ready and will be merged pretty soon.

**Comment by jaynus** [comment]
> Half the bar is very hot! (around 500º), and it's physically accurate. The fx showing how hot is that and other imrpovements to overheating are almost ready and will be merged pretty soon.

These will conflict with RHS.

**Comment by esteldunedain** [comment]
> These will conflict with RHS.

Whaaatt??

**Comment by jaynus** [comment]
They added barrel heat signatures and firing heat signatures hardcoded to their weapons. So, you will always have a heat affect on RHS weapons and the visual queue of overheating is useless.

**Comment by Lumnuon** [comment]
sry didn´t know half the bar is that hot :(

**Comment by esteldunedain** [comment]
@Lumnuon, don't worry about it. @commy2 complained about the exact same thing a few weeks back. Hopefully the new PR will help communicate that better.

**Comment by alganthe** [comment]
I'll update the doc tomorrow about it to make it clearer, concerning RHS harcoding their shit, welp I guess they'll have to provide a fix themselves.
