### ISSUE TITLE
.dll check appears to be broken. Getting seemingly erroneous error popup on spawn.

### ISSUE THREAD

**Issue by jungletek** [acemod/ACE3#1416]
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None

**Description:** & **Steps to reproduce:**
@ACE & @CBA are all that's needed to repro, even though my accompanying vid link and Process Monitor log show an instance where I've loaded more (vid has the whole affected repo loaded, ProcMon log has TFAR added to CBA and ACE). I've tried a million different combinations and versions, and the .rpt always has the same symptoms: it claims that the ACE .dll's aren't loaded when I spawn, and your failsafe kicks me back to the death menu / role selection.

https://www.youtube.com/watch?v=WEnmzmB1R6U

As you can see, when I repro it in the editor, I can click continue and not only bypass your failsafe .dll check, but show that they're actually loaded, and ACE is more or less working properly (with the exceptions of the animations sticking, causing me to have to hit the interact or self-interact hotkey(s) to unstick myself). The linked ProcMon log shows that the .dll's are found where they should be and actually loaded into memory, so I dunno what's going on. Been banging my head against this for 3 days now...

**Where did the issue occur?**
"Multiplayer", "Singleplayer"*

Here's the .rpt: http://pastebin.com/DxDmETi9

And the bonus ProcMon (https://technet.microsoft.com/en-us/library/bb896645.aspx) log: https://www.sendspace.com/file/nzvohu

**Comment by jonpas** [comment]
Thank you for your report, but please edit it with issue reporting guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by jungletek** [comment]
The only thing missing was the version number, and your suggested formatting...

**Comment by jonpas** [comment]
Exactly, formatting is important to make ti readable and see information right away.

**Comment by jungletek** [comment]
Version number is splattered all over the .rpt, FWIW.

**Comment by jaynus** [comment]
12:49:20 [ACE] ERROR: Extension ace_break_line.dll not installed.
12:49:20 [ACE] ERROR: Extension ace_clipboard.dll not installed.

**Comment by PabstMirror** [comment]
Very odd.
Could you verify that V:\SteamLibrary\steamapps\common\Arma 3\@ace\ contains all 4 .dll files:
```
ace_advanced_ballistics.dll
ace_break_line.dll
ace_clipboard.dll
ace_fcs.dll
```
Other thing I would love to see is if you could bypass the check and get into game and run this in a debug line and see what it spits back:
`"ace_break_line" callExtension "testtest testtest"`

**Comment by jungletek** [comment]
"ace_break_line" callExtension "testtest testtest" did nothing, not even pop an error.

As far as the DLL's being installed:
![ace](https://cloud.githubusercontent.com/assets/6620379/7866948/d7e7aa5a-0540-11e5-95b0-2c11b95221eb.png)

**Comment by jungletek** [comment]
Oh, also forgot to mention: another way we discovered you can bypass the missing dll error msg is to have another error pop over it, specifically the 'no zeus key bound' error dialog. Dismissing it also dismisses the ACE error. In case that helps this or your modification of the code that throws those errors.

**Comment by alganthe** [comment]
ace zeus was added after 3.0.1 afaik can you give us the commit hash that you were at when you build that release version ?

**Comment by esteldunedain** [comment]
> "ace_break_line" callExtension "testtest testtest" did nothing, not even pop an error.

Well, it won't pop up an error if the dll is not present. But it will return `"testtest testtest"` if the dll exists and `""` if it doesn't, so the important thing is for you to look what it is returning. Maybe do something like:

`myValue =  "ace_break_line" callExtension "testtest testtest"`

and then check monitor the value of `myValue`.

**Comment by SilentSpike** [comment]
> ace zeus was added after 3.0.1 afaik can you give us the commit hash that you were at when you built that release version ?

I think he's talking about the vanilla game error that occurs when you unbind the zeus key.

**Comment by jungletek** [comment]
>>ace zeus was added after 3.0.1 afaik can you give us the commit hash that you were at when you built that release version ?

>I think he's talking about the vanilla game error that occurs when you unbind the zeus key. Unrelated >to ace zeus.

Correct.

**Comment by jungletek** [comment]
>myValue = "ace_break_line" callExtension "testtest testtest"

>and then check monitor the value of myValue

Result was    ""

**Comment by jaynus** [comment]
This seems like it may be a symptom of the new BattlEye perhaps not allowing the extension to load? Or perhas an A/V is catching it. 

The very end of the RPT shows no extensions are being loaded. None of them - not just a few of the ACE ones, but nothing.

**Comment by jungletek** [comment]
Needs More Info. Anything I can provide?

Doing some testing last night we (teammates and I) found that adding Zeus to maps will (predictably) cause the 'no Zeus key' popup to appear, so there's at least a bit of a hacky work-around for us to use in the meantime.

I've checked the A/V angle, and if it is preventing anything (which it hadn't before), it's not popping a notification, and there's no evidence of a negative interaction. Additionally, I have had A/V and firewall exclusions on my Steam game directories for years now.

**Comment by PabstMirror** [comment]
Could you try starting up without battleye.
I belive the launcher has an option for it
or try launching the exe directly:

goto C:\Program Files (x86)\Steam\steamapps\common\Arma 3 and run:
`arma3.exe -mod=@CBA_A3;@ace;`

**Comment by jungletek** [comment]
Couldn't find it in the launcher, but I started it from a command line. Didn't make a difference, same error, etc.

**Comment by jungletek** [comment]
So it's been a month and a half, and not one follow-up post, and meanwhile I can't play in organized events unless the organizers accommodate me by adding a Zeus module (which doesn't always happen, because I'm the only person with this issue).

How much more info do you need from me? Should I just go F myself? I understand that this is an edge-case, but statistically, I can't be the only one, just the only one (apparently) to post an issue about it.

**Comment by esteldunedain** [comment]
Sorry, to be honest we don't know what's wrong on your setup or how to fix it. Your system seems to be blocking those dlls from loading. For the rest of the people who reported stuff like this problems were solved by restarting the system, disabling the antivirus, etc; certainly nothing related to ace itself.

**Comment by PabstMirror** [comment]
@jungletek - We think the issue is something with your system.

It's up to you if you want to try these drastic changes, but if I was having the issue this is what I would do:

* Uninstall all AVGs/Antimalwares
* Uninstall Arma, and delete the whole folder to remove any possible OS hooks on the files.
* Reinstall Arma and ACE and see if it works.

You could go nuclear and do clean OS install, after that there should be no reason it wouldn't work.
I know this is all a pain in the ass, but something on your system is blocking those dlls.
