### ISSUE TITLE
The navid and SPMG are missing the barrel swapping interaction

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#1419]
ACE 3.0.1   6332e035a74f5ec4c53cc194c11d28d34f6070e1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
none

**Description:**
The BLUFOR "SPMG" and OPFOR "Navid" MMGs don't have the option to swap barrels

**Steps to reproduce:**
- In the editor place a blufor or opfor `heavy gunner`
- Place the  `ace misc ammo box`
- Grab a `Spare barrel` and try to switch, you can't

**Where did the issue occur?**
Editor

**RPT log file:**
nuthin'

**Comment by alganthe** [comment]
fix'd it in #1426

**Comment by esteldunedain** [comment]
Fixed
