### ISSUE TITLE
self blood Infusion for SP (wanted)

### ISSUE THREAD

**Issue by eagleye100** [acemod/ACE3#1420]
Hi Guys, i submit request of self blood infusion for single player mode almost 15 days ago and somebody advise me to remove medical.pbo from ace mode, when i remove medical.pbo my player not getting any damage and neither vehicle but after while kills me and destroy vehicle.. please fix this issue or alternatively bring self blood infusion like in arma 2 ace.

**Comment by esteldunedain** [comment]
Request should go on #414.

**Comment by eagleye100** [comment]
When i play ace without medical.pbo even after taking shots im still not getting hurt so thats why i cant use first aid on me
