### ISSUE TITLE
Moving aimpoint, option for interaction menu

### ISSUE THREAD

**Issue by Dobakjang** [acemod/ACE3#1421]
It's really immersive and looks cool to aim person leg or limb to cure and treat them, however some people might feel dizzy and quiet hard to hold key to maintain the interaction screen to stay, it would be helpful to those people who feel hard that aimpoint moving when we have to treat the soldiers limbs, so i ask to make stay the interaction key when we click or push the key even we stay off from those keys and make aimpoint stop when we looking at interaction menu, i don't ask to change to this way 100%, I'm asking to make an option for this. my opinion came out form our clan people and me.

**Comment by jaynus** [comment]
Thanks for the suggestion, in the future all feature requests go to #414
