### ISSUE TITLE
Self Interaction menu Broken in Vanilla Campaigns with CBA RC7

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#1423]
This is reproducible. 
http://forums.bistudio.com/showthread.php?178224-CBA-Community-Base-Addons-ARMA-3&p=2943229&viewfull=1#post2943229

Apparently RC6 is fine. 
We need to isolate the issue and decide do we fix ACE or fix CBA. 
Why does this only effect Campaigns?

**Comment by ViperMaul** [comment]
It only effect self-interaction. Not interaction.

**Comment by Glowbal** [comment]
Could this be caused by some specific unit classname of the character that is used in the campaigns and XEH not running on it (anymore)?

**Comment by esteldunedain** [comment]
> Could this be caused by some specific unit classname of the character that is used in the campaigns and XEH not running on it (anymore)?

Yes, that would explain it.

**Comment by ViperMaul** [comment]
Yeah but would that alone explain why it only affects Self-Interaction but not Interaction?

**Comment by ViperMaul** [comment]
Here is one change of note in CBA RC7 
https://github.com/CBATeam/CBA_A3/commit/111ba1950f4d4823b6329243f452c2107c6fc06c
to fix https://dev.withsix.com/issues/76209

**Comment by Glowbal** [comment]
Is this reproducible on any campaign mission?

**Comment by esteldunedain** [comment]
> Yeah but would that alone explain why it only affects Self-Interaction but not Interaction?

Yes, it would explain it. Interact menu is constructed correctly for all the classes except that of the player, hence he can interact with everything except himself.

**Comment by ViperMaul** [comment]
@Glowbal 
Campaigns Tested
Prologue: Reality Check - No Repo - all is good. 
Prologue: Common Denominator - No Repo - all is good. 
THE EAST WIND: SURVIVE  - reproducible

**Comment by ViperMaul** [comment]
The East Wind campaign uses "B_Story_Protagonist_F" as the player.

**Comment by ViperMaul** [comment]
Comparing:
B_Soldier_F
http://gyazo.com/05070b7cacac7060c0616557c1dbc0d6
B_Story_Protagonist_F
http://gyazo.com/634af5f8089de613bffb3c61ada42178

**Comment by ViperMaul** [comment]
CBATeam has a solution we will just be testing it over the next 24 hours or so.

**Comment by Desty84** [comment]
We had the problem, that players as civilians had no self interaction too?
Should I post a new issue ?
The problem also occurred with the CBA update!

**Comment by ViperMaul** [comment]
Fixed in this pre-release hotfix - v1.1.22.150601 - http://bit.ly/1FpOy2Y
Official release soon.
