### ISSUE TITLE
Explosive System does not work with mine/explosive set in editor or zeus mode.

### ISSUE THREAD

**Issue by EcologUTG** [acemod/ACE3#1434]
ACE3 Version: v3.0.1 (20 May 2015)

Mods:
@cba_a3 (v1.1.20.150416 (17 Apr 15) = latest to date)
@ace3 (v3.0.1 (20 May 2015) = latest to date)

Placed ACE3 Modules:
ACE_ModuleExplosive

Description:

Explosive System does not work with mine/explosive set in editor or zeus mode. If you put the explosives in person at the game it works. What could be the problem?

Steps to reproduce:
Start Arma3 > Editor > Stratis/Altis
Place a unit "sapper"> control: player
Place Module > ACE > Explosive System (ACE_ModuleExplosive)
Place any explosives
Select "Preview" 
Explosives does not appear on the menu, with neutralization

RPT log file:
No .RPT file was found

**Comment by EcologUTG** [comment]
Sorry for my bad english.

**Comment by Glowbal** [comment]
This has been fixed for the upcoming release. 

Thank you for your report.

**Comment by SilentSpike** [comment]
I think this is a different issue glow, he means the actual mine modules

**Comment by Glowbal** [comment]
That is also fixed for next release.
