### ISSUE TITLE
AI respawns with the gear of another faction (Respawn module?)

### ISSUE THREAD

**Issue by MojoDog** [acemod/ACE3#1439]
Was playtesting a mission im working on with the ace3 respawn module active, save gear on.
One of my AI teammates died and respawned. To my amazement he now had opfor african conflict gear and uniform.
At the end of the mission, all my AI teammates except one had the african gear.

Mods active except ace3 and cba_a3:
-All of massis mods.
-MRB voice stop.
-TFAR.

**Comment by Dobakjang** [comment]
i'm having simular symptom, when i respawn i got one of my friends gear who join with me in same server

**Comment by esteldunedain** [comment]
Regarding this, apparently are missing something like if _
