### ISSUE TITLE
Interaction Cursor Jumpy When Centered

### ISSUE THREAD

**Issue by Waffle-SS** [acemod/ACE3#1446]
ACE3 Version: 3.0.1
last commit: 23d300df52
**Mods:**
* @cba_a3
* @ace3

**Description:**
When interaction cursor and keep cursor centered are enabled, the cursor "jumps" around slightly when you move the mouse as it tries to keep it centered. This only occurs in the most resent update, it stayed in the center very smoothly in previous versions.

**Steps to reproduce:**
1. *Enable "Keep cursor centered", and "Always display cursor for interaction" or "Always display cursor for self interaction" in ACE options.*
2. *Self interact or interact with an object*
3. *Move the mouse*

**RPT log file:**
No script errors

**Comment by Dobakjang** [comment]
I really like they give option to make a interaction menu as AGM or XMED did.

**Comment by PabstMirror** [comment]
#3132 Optimized Interaction menu as best I could

The problem seems to be that the game renders a frame between the mouse actually moving and the `MouseMoving` event.  I cannot find any way to solve this.

I tried v3.0.0 branch and it seemed to always have this problem.
