### ISSUE TITLE
Dirt on goggles does not adjust for darkness

### ISSUE THREAD

**Issue by TinfoilHate** [acemod/ACE3#1447]
I'm not entirely sure if this is a bug or a feature request, but, the dirt texture applied to goggles is full bright, even at night time. It should probably adjust with the ambient lighting conditions, if possible.

**Steps to reproduce:**
Wear goggles. Get them dirty. Make it nighttime.

![2015-05-30_00009](https://cloud.githubusercontent.com/assets/6508146/7899796/3cbb682a-06e7-11e5-9807-cd503989cdcf.jpg)

**Comment by nomisum** [comment]
To achieve this, texture has to be black + alpha only. Would take away the sand look.

Or you have to switch textures, which could be difficult as you have to determine when its dark enough.

**Comment by esteldunedain** [comment]
> Or you have to switch textures, which could be difficult as you have to determine when its dark enough.

Well, we do that on other places already.

**Comment by commy2** [comment]
#3996
