### ISSUE TITLE
Question/Feature Request regarding ragdoll on unconscious state.

### ISSUE THREAD

**Issue by sarge950** [acemod/ACE3#1448]
So i've been a big fan of ACE since Operation arrowhead and have been active in a series of units that have actively used it for the past 2 and a halfish years now. And while I love all of the hard work and the additional features ace has added in, one thing as always bugged me and that is when someone enters the unconscious state due to the medical system, they enter a very distinct animation. Now this was less of an issue in arma 2 due to the fact that death animations were not ragdolls but just that, animations, however now that arma 3 employs the use of ragdolls in place of death animations, it has become incredibly easy to, at a glance, see whether someone is living or dead. This only truly becomes an issue in realism communities and within communities of users who are more concerned with having the most immersive experience possible and this brings me to my request. Is it possible to make unconscious characters (both AI and player) enter a ragdoll state?
Thanks for any feedback you guys may have and keep up the great work!

Addtnl notes:
perhaps allow players to interact with the bodies but only place the unconscious players in an animation after being interacted with/dragged/carried?
Perhaps allow people to choose in the ace medical module between ragdoll unconscious state and animated depending on the level of realism people want?
Thanks again!

**Comment by Glowbal** [comment]
No, we cannot do this reliable at the moment.

**Comment by sarge950** [comment]
That's fair but i found this on another person's suggestions and am curious if this would help?

**Comment by esteldunedain** [comment]
That technique has been suggested numerous times. No, it's not reliable enough to be used on ACE.

**Comment by sarge950** [comment]
alright thanks.

**Comment by ted-hou** [comment]
I think Tactical Battlefield has a good solution to this. The unconscious unit actually dies to allow ragdoll and then respawns when revived.

**Comment by esteldunedain** [comment]
> I think Tactical Battlefield has a good solution to this. In their medical system the unconscious unit actually dies to allow ragdoll and then respawns when revived.

That's an interesting idea, but it'd probably create a huge amount of problems for ace.
