### ISSUE TITLE
Take Prisoner - Arresting unit

### ISSUE THREAD

**Issue by perfk** [acemod/ACE3#1459]
prisoner

ACE3 Version: 3.0.1
Mods:

@cba_a3
@ace3

Description:
There is no option to set "take prisoner" to enemy only.
When using the interact option on friendlys am i able to take a friendly unit prisoner there should be an option to only allow the option to be used on enemy

Steps to reproduce:
n/a

RPT log file:
n/a

**Comment by esteldunedain** [comment]
I think the "Take prisoner" option is not showing because the enemy should drop his weapon first, which the AI doesn't do. That condition should not be required for AI enemy combatants.

**Comment by perfk** [comment]
@esteldunedain I think you misunderstod what i'm asking for..

The option to Take AI/player prisoner is there. what i want is an option to disable the option for _x side.

Like, if i'm Blufor, i dont want to be able to take anyone from Blufor prisoner. But i would like to be able to take anyone that is not Blufor prisoner. :)

**Comment by esteldunedain** [comment]
Aha, ok. Yeah, that feature makes sense. Maybe it also makes sense to be able to set an object variable to override the default behaviour, so e.g. mission makers can make certain units "arrestable" for whatever reason.
