### ISSUE TITLE
INTERTNAL CAM (Cematic Camera Recordings)

### ISSUE THREAD

**Issue by JCae2798** [acemod/ACE3#1461]
When creating movies and running code "[]exec "intro.sqs"" from UNIT and/or LOGIC it never executes,  Also INIT.SQF seems to do the same.  However i can run the code from DEBUG or Trigger and it works.  Tested with vanilla CBA and ACE.  Anyone experiencing this as well?

**Comment by JCae2798** [comment]
I have a test mission to share if needed to test BUG.  Thanks

**Comment by PabstMirror** [comment]
So it works on vanilla Arma with no mods loaded?
If you can upload a test mission I can take a look.

**Comment by JCae2798** [comment]
Yes sir;  https://www.dropbox.com/s/jn0b1qapomz04m5/TESTCAm.Stratis.zip?dl=0

**Comment by JCae2798** [comment]
TY btw.  I just installed the latest CBA ver as well and no change

**Comment by PabstMirror** [comment]
Problem is optics\XEH_postInit.sqf: line 16
```
GVAR(camera) cameraEffect ["INTERNAL", "BACK", "ace_optics_rendertarget0"];
```

That is called while your camera is running and ends your camera script for some reason.
The documentation on PIP is pretty weak, but I don't think setting the render2texture should break out of a normal camera effect. (BIS fault?)

commy/BadBenson might be able to take a look.

In the meantime, just add a `~0.25` to the top of your intro.sqs to let our script finish before starting your camera.

**Comment by JCae2798** [comment]
TY Sir.  I'll do that.
