### ISSUE TITLE
Ace3 and asdg errors

### ISSUE THREAD

**Issue by fearlessxgamer** [acemod/ACE3#1462]
I have been trying to run ace3 and asdg together and I have been getting this error "ace_asdg_comp.pgo" is outdated. I looked through all the asdg files and all the ace3 files and have not found a pbo with that name. Has anyone else had this issue?

**Comment by ruPaladin** [comment]
It is in @ace\optionals\ directory. Try to copy-paste it into @ace\addons\.

**Comment by fearlessxgamer** [comment]
I have looked in the ace/optionals. directory and i dont see the file ace_asdg_comp.pbo. there is an ace_compact_asdg.pbo but not the one giving me the outdated error

**Comment by kripto202** [comment]
you copy ace_compact_asdg.pbo into the addons folder. That will fix the error if you are running asdg jr.

**Comment by ulteq** [comment]
kripto202 posted the solution.
