### ISSUE TITLE
CBA update breaks ACE on independent.

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#1467]
ACE3 Version: 3.0.1
Mods:

@cba_a3
@ace3
Placed ACE3 Modules:
NONE

Description:
Trying to play as a independent *greenfor*, The interaction menus don't open and It's all borken!!
Although in the exact same mission, playing as an BLUFOR or OPFOR player it works.

Steps to reproduce:
Place a INDEPENDENT unit and set it as the player. When previewing the mission ACE doesn't work. 

Where did the issue occur?
Editor

RPT log file:
n/a

**Comment by PabstMirror** [comment]
I couldn't reproduce, could you post full RPT and verify you aren't running any other mods.

Also what specific unit did you use.  I tried AAF rifleman ("I_soldier_F") and had no problems.

**Comment by xJenny99x** [comment]
You are absolutely right, I'll try to find out what mod is causing this.

**Comment by PabstMirror** [comment]
I've found that Leight's OPFOR pack (LOP) overwrites event handlers on some AAF//Independen units.  Which will break most mods that use CBA's XEH including ACE.

**Comment by xJenny99x** [comment]
In my case it was @CAF_AG. But that's really good to know aswell.
