### ISSUE TITLE
SwitchUnits not working

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#1468]
ACE3 Version: 3.0.1 **DEV**
last commit 47acb0f470f1f2749eb9e35f36623cb75da832ce

**Mods:**
* @cba_a3_RC6 and RC7
* @ace3

**Placed ACE3 Modules:**
SwitchUnits

**Description:**
SwitchUnits is broken, it's simply not working.
The module doesn't init, same for the player

**Steps to reproduce:**
- Place the switchunits module and enable switching to blufor
- Place a player blufor rifleman with this in his init ```this setVariable ["ACE_CanSwitchUnits", true];```
- Place some random blufor units all around the place and try to switch to them.

Note that this is working in 3.0.1 stable
**Where did the issue occur?**
Editor

**RPT log file:**
http://pastebin.com/ZWAqSUMh

**Comment by bux578** [comment]
So, what's broken exactly? Do you see the blufor units on your map? Is it just not switching?

> ACE3 Version: 3.0.1
last commit 47acb0f

So you're not on the released version? You should state that you're on `dev` then.

**Comment by alganthe** [comment]
@bux the module doesn't seem to work at all, the player should be naked when ```his setVariable ["ACE_CanSwitchUnits", true];``` is applied, I'll try to investigate what is the actual issue.

**Comment by bux578** [comment]
Can't repro. Works fine with 3.0.1 release version.

**Comment by alganthe** [comment]
issue appeared after #1433 it's currently reproducible 100% of the time on the current master.
note that this issue isn't present on stable.

**Comment by bux578** [comment]
https://github.com/acemod/ACE3/commit/9d29aa210725482ec1d136f4690b7294d1e275be
breaks the module. The module function is never called.

**Comment by bux578** [comment]
possible fix in: https://github.com/acemod/ACE3/commit/d727cb4

**Comment by bux578** [comment]
confirmed fixed.
