### ISSUE TITLE
no scopes available for the .338 marksman rifle

### ISSUE THREAD

**Issue by kripto202** [acemod/ACE3#1472]
mods:
cba
ace
asdg jr
rhs
asdg jr rhs
task force radio

I can't pull up any scopes for the "Neeren" .338 marksman rifle.

**Comment by kripto202** [comment]
after further looking, none of the scopes want to show up on the marksman rifles

**Comment by kripto202** [comment]
just found out even the mk14 ebr

**Comment by PabstMirror** [comment]
Make sure to run with ace_compat_asdg.pbo (move from /optional to /addons).

Can you replicate the issue with just CBA and ACE?

**Comment by kripto202** [comment]
it works now. I didn't see the ace_compat_asdg.pbo file
