### ISSUE TITLE
Medical Bug - Error position: _unit getvariable ["ace_medical_hasLos> 22:32:39   Error !: Type Number, expected Bool

### ISSUE THREAD

**Issue by nomisum** [acemod/ACE3#1475]
got spam of this yesterday with the slightest injury (and TFAR kicked me out of the channel).
i was the only one to get it, but repeatedly.

medical setting was BASIC.

couldnt see any damage on my body but got all the negative effects like bloodloss.
```
if (_bloodVolume < 90) then {
if !(_unit getvariable ["ace_medical_hasLos>
22:32:39   Error position: <!(_unit getvariable ["ace_medical_hasLos>
22:32:39   Error !: Type Number, expected Bool
22:32:39 File z\ace\addons\medical\functions\fnc_handleUnitVitals.sqf, line 26
22:32:39 Error in expression <es];
```

Used Mods were

ACE3	3.0.1		
AIA AllInArmaTerrainPack	2015-01-01-Hotfix		
ARC NATO Offensive – Common Pack	0.8		
ARC NATO Offensive – GER Pack	0.7		
Ares - Zeus	1.7.0		
ArmaNature	1.0	
ASDG Joint Rails	0.16	
Bornholm	1.3	
CBA Community Base addons A3	
F.A.T.A Map	1.0	
FHQ Accessories pack	1.5		
Gruppe Adler Mod	1.2	
Kunduz PKRZ	1.08	M	
Leights OPFOR Pack 	1.0.1	
MRT Accessory Functions	1.2	
RHS Rus - RHSAFRF	0.37	
RHS USA - RHSUSAF	0.37	
RHS_opt	3.0.1	
ShackTac Fireteam HUD			
ShackTac Stamina Bar			
SMA Specialist Military Arms	1.9	
Tao Folding Map	2.7.0		
TFAR Task Force Arrowhead Radio	0.9.7.3		
Unlocked Uniforms	1.0.7		
XLA FixedArsenal

**Comment by Glowbal** [comment]
I just looked into this. Judging by that script error you are running an old or custom version of ACE. That line of code got replaced on 28 Apr in f606c2485.

**Comment by nomisum** [comment]
still trying to figure out what went wrong.
most possible is some fuckup of arma3sync, which maybe took the wrong directory path with an older version. just in case anyone encounters similar problems (not very likely).

thank you very much for investigating though.
