### ISSUE TITLE
Events at mission start/loading

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#148]
Right now I think it is possible to send an event to a client during init, before they have finished registering all their event handlers?

e.g.: Mission maker wants someone to start unconscious: 
* `if (isServer) then {[this] call ace_medical_fnc_setUnconc;};`
* The server sends a "kockOut" targetEvent to the client where that unit is local.
* If they haven't finished setting up their EH, that event will be ignored.

Is this something we want to handle in the event handler system?
Just throwing out an idea I had:
We add a `GVAR(postInitDone) = true` to all modules.
Once all ACE modules have their gvars set, we signal to the server that we have finished init.
If server has event for client who hasn't finished init, it buffers and waits to send.

Or we just tell mission makers to not send events right at the start:
 `this spawn {sleep 1; doEventNow};`

**Comment by bux578** [comment]
So, what to do with this issue? 3.0.0, 3.1.0? Who's responsible?

**Comment by jaynus** [comment]
ill take it, see #889. This is a 3..0.0 item we need to test and resolve

**Comment by commy2** [comment]
I don't think this is related. This is about animations failing on init, so some additional checks have to be done to force units in unconscious / surrender / etc. animation if the functions are used by the mission maker via init-box.

**Comment by jaynus** [comment]
Singular fixes would be hacky when this could be solved properly

**Comment by commy2** [comment]
I don't think it can be solved properly though. For example ace_common_fnc_setSpeaker. BI rudely overwrites any speaker you set with `setSpeaker` after init. The only possiblity is to execute the function on CBA's initPost.
Mission makers don't have that option, because they rely on the init box.

**Comment by commy2** [comment]
So, is this question answered? I don't really know what to do now with this.
Told glowbal how to fix `[this, true] call ace_medical_fnc_setUnconscious` from initPost, so I think everything works now.

**Comment by commy2** [comment]
@PabstMirror Is this done now with `SettingsInitialized`?

**Comment by PabstMirror** [comment]
Framework to fix is done in #2355, I guess we need to think about what functions are public and might be called early my mission makers before settings are ready

For example: ace_medical_fnc_setUnconscious uses GVAR(enableUnconsciousnessAI)

**Comment by commy2** [comment]
Just so I understand what the issue is again.

FUNC(setUnconscious) etc. doesn't work when called on init?

**Comment by commy2** [comment]
The only example I can come up with is FUNC(setUnconscious). FUNC(setHandcuffed) and FUNC(setSurrender) don't rely on any settings.

**Comment by commy2** [comment]
Would this work?
```
if (GETGVAR(settingsInitFinished,false) exitWith {
    [{_this call FUNC(setUnconscious)}, _this] call EFUNC(common,runAfterSettingsInit);
};
```

**Comment by PabstMirror** [comment]
```
if (!EGVAR(common,settingsInitFinished)) exitWith {
    EGVAR(common,runAtSettingsInitialized) pushBack [FUNC(setUnconscious), _this];
};
```

**Comment by SilentSpike** [comment]
Any public function that uses the settings framework could potentially be called before settings are done, I'd probably just make them all safe to run like this as we come across them

**Comment by commy2** [comment]
setUnconscious is the only thing I know of where this particual problem causes issues.

Or rather caused issues : - )

**Comment by PabstMirror** [comment]
Also medical init for each unit was already using the settingInit system,so it ran after setUnconc and reset everything.
