### ISSUE TITLE
ACE3 appears to break BIS_fnc_findSafePos 

### ISSUE THREAD

**Issue by brokenhands** [acemod/ACE3#1482]
Calling BIS_fnc_findSafePos seems to be returning the same coordinates every time, which are 100m above the map for Altis, and 1024m in the air on Stratis.

**Comment by esteldunedain** [comment]
Please follow appropiate procedure for bug reports according to the wiki. Please also confirm that this doesn't happen on the vanilla game or only with CBA

**Comment by brokenhands** [comment]
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
none

**Description:**
BIS_fnc_findSafePos no longer works.

**Steps to reproduce:**
Open editor, call BIS_fnc_findSafePos with any set of parameters, you'll receive the same (invalid) results every time.

**Where did the issue occur?**
Multiplayer

**RPT log file:**
Unnecessary

**Comment by PabstMirror** [comment]
Can you give input that doesn't work?
I just tried `x3 = [(getpos player), 1, 10, 2, 0, 0.5, 0] call bis_fnc_findSafePos` and got good results on altis.

**Comment by brokenhands** [comment]
This issue is invalid, or possibly a symptom of another issue :D (sorry!) I was calling using local variables that were being set for map center, which are incorrectly set in ACE3. I'm guessing this is due to the map features, but since bis_fnc_findSafePos can be called without those args, I was able to use the following for my situation:

`[[], 1, -1, 2, 0, 0.5, 0] call bis_fnc_findSafePos`

Thanks for the second/third set of eyes.
