### ISSUE TITLE
Médical settings / Bulletproof vest problem.

### ISSUE THREAD

**Issue by Ebolavector** [acemod/ACE3#1483]
In advance I hope you will understand me because I do not have an excelent level of English! ^^ I havent found the same post but thank you to tell me if I'm wrong.

My problem is this: Obviously RHS units have a bulletproof vest that requires 3/4 bullet 5.56 / 6.5 to be penetrated and medical ACE 3 module does not seem to work. The damage multiplier of "medical settings" module does not seem to work or he is aware of bulletproof RHS vests. (I did not have this problem with the AGM module)

Thank you to the team and keep up the great work! ;)

**Comment by Glowbal** [comment]
Hi, could you please elaborate on what you mean with "does not seem to work"? What are the issues you experience? What is the behavior you expect and what do you observe?

Also here is a link that details on how to file bug reports for ACE: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

We cannot help you until you provide more information.

**Comment by Ebolavector** [comment]
Yes when i change the settings on medical module ( Player Damage (Number) / AI Damage (Number) ) it doesn't seems to take effect on RHS bullet proof vest equiped units. And it seems there is no way to override the bulletproof vest. In fact a RHS soldier requiere three 7.62mm bullets to kill and i want to improve the realism and make the units 1 shot out of combat ( Not necessarily killed but at least out of combat ). ONLY RHS bulletproof vest  units seem affected. I hope i can help you with my comment !

**Comment by Glowbal** [comment]
From what I understand this seems to be an issue from RHS, not ACE.

Please provide specifics though, so we can be certain. 
- What values did you use for the damage thresholds (both player and AI)? 
- What do you mean with override the bullet vest?
- Which vests from RHS are we talking about? All of them? Or specific faction vests only?
- What is the easiest way to reproduce?

Please also provide the information as detailed on this webpage: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by Ebolavector** [comment]
Ooooh a mod seems to be the problem, i try and if i found the solution i would say the mod in question was deffective. ;)

**Comment by Ebolavector** [comment]
I solved the problem , were all mod caused to CAF Agressors which supplanted the ACE 3 Medical Module ! Thanks for your time and your quick responses ! ;)
