### ISSUE TITLE
Question: build.py not working?

### ISSUE THREAD

**Issue by legman** [acemod/ACE3#1486]
Sorry but i have a quick question regarding the build.py. My second time around making a new addition to ACE3 i have found that the build.py 'fails' every attempt to build a PBO for each module.

- I have setup the P Drive
- I have cloned the ACE3 repo via git into the P Drive
- I have linked the z, x folders with the setup.py which succeeds and creates the z in my ArmA 3 install folder
- I run the build.py script and it repeats 'Failed to make [module_name]' for each one.

I have used this just recently to great success but now i seem to be having trouble!
Any help would be greatly appreciated :]

**Comment by ViperMaul** [comment]
build.py is dependent on a working makepbo.exe and proper permissions. 
Since make.py may have some more error checking, try make.py and take a screen shot of any errors.

**Comment by legman** [comment]
thanks for the help mate - i will see what i can gather when i get home from work!

**Comment by legman** [comment]
Never mind, I just started from scratch and got it working - i think i missed a few steps, but yes everything is working ok now!
