### ISSUE TITLE
Fix UAV ...Missile System

### ISSUE THREAD

**Issue by sky-one** [acemod/ACE3#1496]
I KNOW..HELLFIRE FOLLOW THE LASER..BUT .For Destroy IFV..APC..Or Tank..should Full Lock to 100% Destroyed but in ACE3 Missile Follow the laser ..and impact Near the Target.Not Direct Hit  ..See The picture TNX

FIX This......PLZ ACE 
In Reality UAV Lock On Targets..See Real Clip in Youtube
ALT:2000 M
Loiter:1250~1500

http://s6.picofile.com/file/8191858018/DSGFSDGSG.jpg

**Comment by dixon13** [comment]
http://ace3mod.com/wiki/user/how-to-report-an-issue.html
