### ISSUE TITLE
Move all drawing and marker functionality to marker.pbo

### ISSUE THREAD

**Issue by Bummeri** [acemod/ACE3#1499]
Currently Maptools has the line drawing functionality included. Move this to marker.pbo so that players can still use the map tools compass but can use any marker system they like.

Why is this an issue?:

- Need the maptools for mortar operations and other uses.
- Using another marker enhancing mod causes the map tools line drawing to overlap with the mods line drawing.
- Removing marker.pbo does not remove the line drawing.

**Comment by esteldunedain** [comment]
No, I don't think so, line drawing is needed for proper use of the map tools, e.g. for triangulation.

**Comment by SilentSpike** [comment]
@esteldunedain I took a look at the code, would it be reasonable to add a setting to outright disable it?

**Comment by esteldunedain** [comment]
I think it's probably better to have to select a color before drawing. If you select "No color" then it wouldn't draw at all. It would require adding an additional option to the pallete.

**Comment by SilentSpike** [comment]
I mean to disable the drawing with a setting

**Comment by esteldunedain** [comment]
> I mean to disable the drawing with a setting

Yeah, I know. But imo it's an unnecessary setting, that can be better acomplished by letting the user decide if he wants to draw or not at any given moment.
