### ISSUE TITLE
Respawning with FakePrimaryWeapon

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#1500]
ACE3 Dev: 2bf2b5737af3fc31eee794fa9f3c38ffb12760c1

**Mods:**
* @cba_a3
* @ace3
* @tfar

**Placed ACE3 Modules:**
* Respawn / SaveGear: Yes
* Curator Module

**Description:**
Your character respawns with a FakePrimaryWeapon
![](http://puu.sh/ic3Ds/ee6fd90973.jpg)

**Steps to reproduce:**
* Drop your primary weapon
* Become unconscious
* Open curator interface and kill yourself with e.g. a zeus lightning bolt
* You die and respawn with the FakePrimaryWeapon

**Where did the issue occur?**
MP, self hosted

**RPT log file:**
no need

**Comment by Harakhti** [comment]
Error's similar to when it appeared in Arsenal, the game probably looks for the first value instead of the "empty" parameter, and since the fake primary weapon lacks a defined name, it comes first.
