### ISSUE TITLE
Document ace_common_forceAllSettings

### ISSUE THREAD

**Issue by Bummeri** [acemod/ACE3#1501]
This is not documented anywhere. 

Perhaps add it here -> http://ace3mod.com/wiki/framework/settings.html#3.2-loading-up-the-server-config

**Comment by esteldunedain** [comment]
@alganthe, @BullHorn7

**Comment by alganthe** [comment]
see #2177

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/pull/2177/files#diff-acbffcc6781683a5c07f0f839949bd23R88
