### ISSUE TITLE
Bullet Spash not showing up when trying to spot over 1000m

### ISSUE THREAD

**Issue by enderrrrrrrrrr** [acemod/ACE3#1513]
ACE3 Version: 3.x.x
3.0.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
cba3 
ace
RHSUSAF

**Description:**
bullet splash is not showing up voer 1000m

**Steps to reproduce:**
try to spot spash over a distance of 1000m

**Where did the issue occur?**
multiplayer

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by captainblaffer** [comment]
In your graphics settings, try setting your particle quality to the highest level

**Comment by KoffeinFlummi** [comment]
Closing, since I really doubt that this has anything to do with ACE. Going to reopen if you confirm that this works with vanilla.
