### ISSUE TITLE
Leg points are not aligned with legs for rhs units.

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#1514]
ACE3 Version: 3.x.x
Dev and stable. For dev I guess it was 1777719f.

**Mods:**
* @cba_a3
* @ace3
* @rhs_afrf3
* @rhs_usf3

**Placed ACE3 Modules:**
* None

**Description:**
*Leg points are not aligned with legs for rhs units.*
http://i.imgur.com/FFCgrqc.jpg
http://i.imgur.com/et2xCWD.jpg

**Steps to reproduce:**
* *Just place any RHS unit in the editor and try to interact with him.*

**Where did the issue occur?**
*Multiplayer and Singleplayer*

**RPT log file:**
http://pastebin.com/uB4qw1GA

**Comment by Glowbal** [comment]
Hi thank you for your bug report. This is an issue with RHS. They are will fix it for their next update (or already have in their latest version?).

**Comment by rebelvg** [comment]
Oh, okay, thanks!
