### ISSUE TITLE
Blackfoot down explosives bug

### ISSUE THREAD

**Issue by Koram94** [acemod/ACE3#1516]
Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
None

Description:
Very quickly, in campaing's mission Blackfoot landed (I don't know the original name, I play it in Italian), when I have to plant the charge, it isn't cosidered attached to the wreck of the helo, so after I get and plant a second charge the mission fail, because I didn't attached, or more correctly, couldn't plant the charge. 

So, I'm stucked here with no options to complete that mission.

**Comment by esteldunedain** [comment]
Sorry for the inconvenience @Koram94, but ACE3 is not meant to be used in the single player campaigns, or in fact in any mission not specifically written for it. We cannot guarantee even basic things working at all.

**Comment by kevinfoley** [comment]
It would be very nice if the mod clearly indicated it wasn't designed to work with the campaign.

**Comment by commy2** [comment]
No mod is.
