### ISSUE TITLE
ACE 3 bugs

### ISSUE THREAD

**Issue by Kyle1245** [acemod/ACE3#1518]
When you interact with a body bag you can only drag I wish you could carry and drag and also it would be nice if we could load bodybags into vehicles, helicopters, ect... I don't know if this is a bug or just not in the mod yet but itd be nice if you fix this. Also when an IED is spawned you have to arm it in order to interact with it so maybe if it is already disarmed maybe we can just pick it up and put in in the vehicle or our inventory.

**Comment by esteldunedain** [comment]
This is not a proper bug report. Feature requests should go to #414.
