### ISSUE TITLE
M84 Flashbang has low effect radius

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1539]
ACE3 Version: 3.0.1
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None*

**Description:**
* *M84 continues to fly after explosion*
* *As you can see on video below M84 seems to have a bit too low effect radius, it should still blind me by staring at it like that I think.*

https://www.youtube.com/watch?v=ZLHWfz9rp2s&feature=youtu.be

**Steps to reproduce:**
* *Throw M84 in the air and observe.*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*Not needed I think.*

**Comment by PabstMirror** [comment]
http://en.wikipedia.org/wiki/M84_stun_grenade

Looks like the noisemaker is encased in a steel cage. 
The cage remains intact after blasting (it's non-lethal).
So I think the effect is reasonable.

As for distance, I really don't know what would be realistic.
Right now it's just a linear dropoff with a max of 15m.
`_strength = 1 - ((_x distance _grenade) min 15) / 15;`

**Comment by gienkov** [comment]
Then nevermind first one, I will ask military guy from my community about
effect radius.

**Comment by esteldunedain** [comment]
I think that the screen should go white at that range, even if the effect only lasts a few frames. I think it looks a bit weird that nothing seems to happen. An alternative would be to render a white flash using something like particles, so the explosion can be seen from afar

**Comment by gienkov** [comment]
Best info I could find:
https://books.google.pl/books?id=olk_AgAAQBAJ&lpg=SA2-PA13&ots=o8uR1Fca43&dq=m84%20stun%20grenade%20effects&hl=pl&pg=SA2-PA13#v=onepage&q&f=false

**Comment by bux578** [comment]
> IRL if you're hit by a military grade flashbang you'll suffer a (in germany called: h90/3 type) sudden hearing loss, serious loss of orientation and eye damage like if you'd do arc welding without a safety mask. This usually leads to two weaks of being unable to fight (with potential hospital stay). That wouldn't be much fun in arma ... so this needs to be balanced to still be fun.

The flashbang effect (from a gameplay perspective) in ACE2 was very well done. It even turned your unit by 180° if you were affected by the flash (to simulate looking away and being unable to react to the breaching team in a timely manner)

**Comment by Macusercom** [comment]
I have to agree with @bux578. The flashbang in ACE2 was really great. The explosion radius really depends on where you throw it. Normally it is used inside building so 15 m should be alright. However, when thrown outside it could easily be 30 or 50 m if not even more when you are directly looking at it. Moreover, I think the effect is really short. It should at least stay 30 seconds or more. Right now it's like 5 seconds.

**Comment by gienkov** [comment]
Time of white flash is ok but vision could come back with a heavy blur effect, simulating tears.

**Comment by commy2** [comment]
Edited the title because of Pabsts comment.

**Comment by commy2** [comment]
Is this still a thing?
