### ISSUE TITLE
Arsenal First Person Load Bug

### ISSUE THREAD

**Issue by jokoho48** [acemod/ACE3#1540]
ACE3 Version: 64d529ed3cbd04bee9e4c2cadf060f30cd4bddea

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
No

**Description:**
if you Load the Virtual Arsenal at Main Menu you are in first person and dont see your Charater

**Steps to reproduce:**
Start ArmA 3 with CBA and ACE3.
Click on Learn and than at Virtual Arsenal
after Loading  you Dont see your Charater(First Person).

**Steps to "Fix":**
Press Preview and go back to Arsenal and it work

**Where did the issue occur?**
Virtual Arsenal

**RPT log file:**
No RPT Error

**Video:**
https://www.youtube.com/watch?v=wPAMxDswj7k

**Comment by kripto202** [comment]
which cba? never had this happen before.

**Comment by dixon13** [comment]
Not an issue for me.

**Comment by jokoho48** [comment]
Newest CBA Version and here is a Video is now in Post
Currently it look like its same problem as #1461

**Comment by Glowbal** [comment]
Could you please provide an rtp file?

**Comment by jokoho48** [comment]
this Issue dosn's Occlude with this 6dba8b33dabacf376317554d7255192098988f10 Commit
can closed

**Comment by ulteq** [comment]
This bug is caused by what PabstMirror wrote here: https://github.com/acemod/ACE3/issues/1461#issuecomment-108198237
