### ISSUE TITLE
merged with cse/agm

### ISSUE THREAD

**Issue by dvdbrewster** [acemod/ACE3#1544]
I had AGM playing on almost all missions, We were able to unload wheels and tank tracks(spare parts, and fuel inventories with jerry can in all vehicles.  I keep looking for it.  Must  it be enabled somehow on map modules? It seems missing now.   Whats the word ?  Also the OPTIONAL server pbo.. what's its use ?     dave

**Comment by reoxdk** [comment]
i have asked the same question earlier logistic is not in ace at the moment it will come in a later version im pretty sure it will be awsome when it comes

**Comment by dvdbrewster** [comment]
Im looking for a projected dates of future releases.. any idea? and what about the optional SERVER pbo ?

**Comment by sarakgaming** [comment]
Same for AGM Fast Rope... i'ts on backlog. No due date.

**Comment by esteldunedain** [comment]
We are not making any promises regarding when will features be released.
