### ISSUE TITLE
Climbing no longer works

### ISSUE THREAD

**Issue by KRDucky** [acemod/ACE3#1547]
I was testing climbing in the VR space using all the walls you can access via Zeus. It told me on every wall over knee height that I "Could not climb here". What point is having a "climbing over walls" function if it does not work on walls over knee height. Not to mention jumping no longer works either.

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html
