### ISSUE TITLE
CCIP Needed for fixed wing aircrafts

### ISSUE THREAD

**Issue by JonenKone** [acemod/ACE3#1549]
Feature request: Fixed wing aircrafts need CCIP aiming reticle for manual bombing runs. 

There is currently a really simple mod that does its job fairly good and could work as a starting point/concept. 
http://www.armaholic.com/page.php?id=27403

http://wiki.hoggit.us/view/HUD#Continuously_Computed_Release_Point_.28CCRP.29

**Comment by esteldunedain** [comment]
Feature requests go on #414.
