### ISSUE TITLE
Framedrop with RAH-66 Commanche

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1554]
ACE3 Version: 3.0.1 Stable

**Mods:**
https://docs.google.com/spreadsheets/d/1OTjYgUqxEnQsQBAfgwmjbThDZ3unG21H1jfGkZEwO00/edit?usp=sharing

**Placed ACE3 Modules:**
http://pastebin.com/PVnhFPFF

**Description:**
*Shooting DAGR rockets is very unreliable, they often not homing into target (flying straight). They also seem to not lock onto laser designator, simply missing the target. Most annoying is framedrop you get when you try to shoot some of those rockets. I think it may be related to script error I got, as seen below and in RPT.*

http://images.akamai.steamusercontent.com/ugc/37499844262244477/FF64C479C03EC523BAADA0A55247B660E02B7D54/
Yeah, I was shooting DAGR's while on the ground, it's possible, few were homing onto target but other's kept flying straight after shot.

**Steps to reproduce:**
* *Get as gunner into Commanche*
* *Order AI or get your friend to get as pilot*
* *Try to shoot targets with laser designator turned on and off*
* *Notice framedrop*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
http://pastebin.com/1zxCt5zz

**Comment by esteldunedain** [comment]
@gienkov, the problem with the framedrop is two fold:

- part is genuine, due to laser an guidance
- but most of it is probably to to rpt spam

So the thing is to find why this is erroring., and we believe it's due to those Updating base class errors you are getting. The solution would be to retest with different addons and see what conflict is causing this. Could you do some tests adding/removing pbos?

**Comment by bux578** [comment]
http://ace3mod.com/wiki/user/how-to-report-an-issue.html

>If you've found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using only @cba_a3 and @ACE3 on a newly created mission.

:smile:

**Comment by bux578** [comment]
Still happening. 60 -> 38 fps when unloading all DAGR's

**Comment by gienkov** [comment]
Still happening on 3.2.1.

**Comment by gienkov** [comment]
Additional note: DAGR's are missing very often - they don't hit point I've targeted and lased.

**Comment by bux578** [comment]
> Still happening on 3.2.1.

Milestone is 3.3.0

**Comment by bux578** [comment]
Close in favor of #3211

**Comment by esteldunedain** [comment]
Closed in favor of #3308
