### ISSUE TITLE
Segmentation fault occurs in combination with RHS (Linux dedicated)

### ISSUE THREAD

**Issue by Dorbedo** [acemod/ACE3#1557]
ACE3 Version: 3.0.1
(stable)

**Mods:**
* @ cba_a3   (RC5 - RC7)
* @ ace3     (3.0.0 ; 3.0.1)
* @ RHSUSF (0.37)
* @ RHSAFRF (0.37)

**Placed ACE3 Modules:**
* ["Advanced Ballistics","Check PBOs","Explosive System","Friendly Fire Messages","Hearing","Interaction System","Make Unit Surrender","Map","MicroDAGR Map Fill","MK6 Settings","Name Tags","Respawn System","Weather","Wind Deflection","Basic Medical","Revive"]

**Description:**
There is a chance to produce a segfault if you are using the mod combination "CBA+ACE+RHS"
The segfault occurs on Debian 7.7.

It's easy for me to reproduce this with a headless client. Almost every time any target is shot by an RHS-Missile and when it causes penetration, the headless gets the segfault.
The windows clients are not affected. Sometimes the segfault can happen to the server too, but it is less likely.

This segfault has already happened before with AGM. 
It's not reproducible with RHS only.

**Steps to reproduce:**
1. Set up a mission with RHS and Ace
2. Let your Headless connect
3. Shoot some RHS vehicles with RHS Missiles/Rockets

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
*Log 1 - Server http://pastebin.com/CD8TnJ65*
*Log 1 - gdb http://pastebin.com/v53smXP8*
*Log 2 - Server http://pastebin.com/UnRsefDt*
*Log 2 - headless http://pastebin.com/CvJm9fYt*

**Comment by jonpas** [comment]
> It's not reproducible with RHS only.

Is it reproducible with CBA+ACE only?

**Comment by Dorbedo** [comment]
It's not.
Only when using RHS missiles, while ACE is activated.

**Comment by dixon13** [comment]
If this is an issue with RHS, then there is nothing ACE can do.

**Comment by Dorbedo** [comment]
I've already got this experience.
So there is no one who is responsible for compatibility of these modifications.
What a pity.

So it's on the users themselfs to locate and fix issues related to inter-mod compatibility.
Too bad, but i can understand the reason.

**Comment by bux578** [comment]
You could still bug the RHS guys about it. Maybe it's not in vain.

**Comment by SilentSpike** [comment]
I don't think it's wise to do so, they said all questions regarding ACE/CBA will be directed to those mods. They would probably view a developer of ACE directing questions towards them as incitement.

An unfortunate situation. :frowning:

**Comment by NouberNou** [comment]
This is a two part issue, the crash is BI (we do not run any external penetration code at the moment and it was an issue in AGM which definitely didn't do that), the implementation that causes the crash is RHS. ACE raises a situation that cause RHS content to crash, but vanilla content to not crash.

This is an RHS/BI issue, not ACE (despite ACE being the thing that exposes their crash).

Please further this problem with RHS.
