### ISSUE TITLE
ACE_SwitchUnits not functional?

### ISSUE THREAD

**Issue by captainblaffer** [acemod/ACE3#1558]
ACE3 Version: 3.0.1 

Mods:
@CHVD;@ASDG_JR;@ASDG_JM;@AllInArmaTerrainPack;@BWA3;@CBA_A3;@dariyah;@fhq_accessories;@hlcmods;@k_mnp;@ace;@stui;@tao_foldmap_a3;@task_force_radio;@rhsafrf;@rhsusf;@3cb_baf_weapons;@rhs-hlc;

Placed ACE3 Modules:
ACE_ModuleSwitchUnits
ACE_ModuleFriendlyFire
ACE_moduleReviveSettings
ACE_moduleMedicalSettings
ACE_ModuleInteraction
ACE_moduleAssignMedicalFacility

Description:
Could someone please confirm ACE_SwitchUnits is actually working already?

I converted my mission which used AGM_SwitchUnits to use the new ACE variant, but it does not seem to be working at all.

A player with the assigned variable just behaves as a normal unit.

Steps to reproduce:

1. Create a mission which included 1x player and 1x AI
2. Place down SwitchUnits module in mission.
3. In init.sqf paste: player setVariable ["ACE_CanSwitchUnits", true];	

Where did the issue occur?
"SP"

**Comment by PabstMirror** [comment]
Tried on 3.0.1 and master and it seems to be working correctly.
Please try this mission and see if it is working for you: http://www.filedropper.com/showdownload.php/aceswitchunitsteststratis_1

Only real difference is that I have `this setVariable ["ACE_CanSwitchUnits", true];` on the unit's init field in the editor instead of init.sqf.

If it is still not working, please try with just CBA/ACE and upload a copy of your .rpt.

**Comment by captainblaffer** [comment]
Pasting this setVariable ["ACE_CanSwitchUnits", true]; in the unit's init field in editor fixed the problem for me.

It's a little weird it works like this now, but survivable I guess.

One remaining potential issue, when a player joins in progress, won't the variable on the unit get reset?  As anyone runs that code (afaik).
I tried doing this: if (local this) then {this setVariable ["ACE_CanSwitchUnits", true];}; but that doesn't work for some reason.

**Comment by PabstMirror** [comment]
` setVariable` has local effects unless the optional 3rd arg is set to true, so it should be fine.
It's what the wiki says to use: http://ace3mod.com/wiki/missionmaker/mission-tools.html#2.-ace-switchunits

**Comment by captainblaffer** [comment]
Thanks for explaining. Sounds all good then!
