### ISSUE TITLE
Bullet trace not working on LRPS

### ISSUE THREAD

**Issue by enderrrrrrrrrr** [acemod/ACE3#1560]
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
all necessary ace modules including turning on the advanced ballistics modules

**Description:**
Bullet trace does not work well using the LRPS but with other rifles/scopes it does.

**Steps to reproduce:**
Use LRPS and try to check bullet trace

**Where did the issue occur?**
Multiplayer

**RPT log file:**

**Comment by gienkov** [comment]
Can't repro.

**Comment by enderrrrrrrrrr** [comment]
Just to confirm the Bullet trace effect is working on the LRPS for you?

**Comment by Benargeez** [comment]
Is it invisible in the scope or not visible at all?

**Comment by ulteq** [comment]
I tested it with all three LRPS scopes (Vanilla, 2d, PiP). I can not reproduce it.

**Comment by esteldunedain** [comment]
Maybe it's related to graphical settings?

**Comment by enderrrrrrrrrr** [comment]
I have everything set to ultra. Its strange because it works for some of
the other scopes but particularly not the LRPS.

**Comment by enderrrrrrrrrr** [comment]
Not visable at all with the LRPS.

**Comment by enderrrrrrrrrr** [comment]
Going to Close, seems to be an issue with RHS will contact them to resolve.

**Comment by bux578** [comment]
> Going to Close, seems to be an issue with RHS will contact them to resolve.

Issue with RHS? In your OP you're saying:
````
Mods:

@cba_a3
@ace3
```

**Comment by enderrrrrrrrrr** [comment]
Yep, it was my mistake i disabled the wrong mod pack well trying to remedy
the issue. My apologies.
