### ISSUE TITLE
Empty Self Interaction menu

### ISSUE THREAD

**Issue by eagleye100** [acemod/ACE3#1561]
Hi, I was trying to change keys for Self Interaction and Interaction, after changing keys self interaction keys menu is appearing but empty.

I reinstall ace mod few times including userconfig file but not able to recover self interaction menu.

Any advice?

**Comment by kripto202** [comment]
are you sure that your not hitting the wrong keys?

**Comment by PabstMirror** [comment]
Do you get a selector (red circle)?
Please take a look at: http://ace3mod.com/wiki/user/how-to-report-an-issue.html and make sure to include an RPT.

**Comment by eagleye100** [comment]
@ kripto202
 yes I'm using correct keys infact I reset the keys back to default but no success.

@PabstMirror
It gives me red selctor without any options, however i reinstall the mod but problem is still there

**Comment by gienkov** [comment]
You use CBA A3 RC7 Hotfix 2 by chance? And loads of other mods?

**Comment by eagleye100** [comment]
Yes i CBA A3 current version, everything  was working fine and smoothly but since i assign different key for Interaction and self interaction I'm only getting red empty circle

**Comment by bux578** [comment]
@vipermaul could this be fixable by using the auto xeh stuff?

**Comment by ViperMaul** [comment]
Not having all the information is really hard to guess. 
Like pabstmirror said 
Please take a look at: http://ace3mod.com/wiki/user/how-to-report-an-issue.html and make sure to include an RPT.

First try without any mods, and use only CBA and ACE3 and then
1. Reset keybinds again
2. Test using the "ACE Test Map 1" mission 
3. Try Self-interaction in that mission than Interact with another player or ammo box. 

Report back.

**Comment by eagleye100** [comment]
@bux578
 Are you experiencing same problem?

**Comment by ViperMaul** [comment]
Bux is probably not experiencing the same error. He was just commenting on the back end of an earlier conversation he and I had about documenting problems that 3rd-party mods have can have with self-interaction. Because we don't have an RPT from you or a proper report we don't even know if or what other mods you are using. 

Let me know what your results from my suggested course of action and we can see if we can fix you.

**Comment by eagleye100** [comment]
@ViperMaul 

I followed all the above steps and its working now for me. Thanks very much for all of you sound guys. Now i'm closing this issue with smile :)

Regards.

**Comment by eagleye100** [comment]
@kripto202 @ViperMaul @PabstMirror @PabstMirror @bux578 @gienkov 

Guys I'm trying to run game with my mods:
-mod=@ASDG_JR;@CBA_A3;@LEA_A3;@PG_Services;@U100;@fhq_accessories;@mcc_sandbox;@sthud;@FA18X_Black_Wasp;@compassfix;@NSS_AC;@Drift_NoFatigue;@JS_JC_FA18;@TFA;@outlw_magRepack;@MBG_Killhouse;@taw_viewdistance;@JSRS 3;@RHSAFRF;@Leights_OPFOR;@AllInArmaTerrainPackLite;@RH_M4;@MK18 Mod1;@TRYK;@hlcmods;@yoink_opfor_insurgents;@Blastcore-A3-Phoenix;@RHSUSAF;@RH_acc;@IVORY_MIG29K;@VA;@MightyGau;@Scopemode_A3;@ASR_AI3;@ACE3_no_medical;@backpackonchest;@Medium_utilility_Helo;@BlueHud;

and again i'm experiencing same issue with empy red circle, but if i run game with CBA and ACE alone it works.

Any advice

**Comment by PabstMirror** [comment]
In cba, copy `cba_enable_auto_xeh` from optional folder to addons.

I know Leights_OPFOR overwrites some eventHandlers on indfor units.

**Comment by kripto202** [comment]
ok then how about this, find out which mod in your list that could be causing the problem. That is a lot of mods there to test out. What I would do is turn a mod off one by one until the interaction system starts working again. When you find that mod, then test it with, ACE, CBA, and that one mod. There could be 2 or more mods that could be conflicting with each other and in turn conflict with ACE.

**Comment by eagleye100** [comment]
@PabstMirror
It works :) thanks a lot mate
