### ISSUE TITLE
Steam Workshop Release

### ISSUE THREAD

**Issue by Benargeez** [acemod/ACE3#1565]
Are there any plans to release ACE 3 on the steam workshop? [CBA](http://steamcommunity.com/sharedfiles/filedetails/?id=450814997) is up so I think this would be a great convenience for users who prefer using the workshop. Similar to PW6 it allows for immediate updates. As a small time mod maker who has content on the workshop, I have had no issues yet. Steam even allows the use of Arma extensions. 

EDIT: There have been quite a few people uploading mods on the workshop like these(AiA, CUP, etc...). They get pretty popular before they get taken down. That shows the demand is there. It would be great if the mod creators would upload it themselves to fill that demand

**Comment by ulteq** [comment]
Questions like this should go into the BI forum thread or our public slack.
* http://forums.bistudio.com/showthread.php?191716
* https://github.com/acemod/ACE3/issues/429

**Comment by Benargeez** [comment]
I tried asking on the public slack! Nobody even acknowledged the question! Didn't get a yes or no or even an undecided answer!
