### ISSUE TITLE
Atropine to Propranalol

### ISSUE THREAD

**Issue by DocScarle** [acemod/ACE3#1566]
Change Atropine to Propranalol as Propranalol is one of the correct counteractive drugs for high heart rate.

**Comment by gienkov** [comment]
#414

**Comment by whiztler** [comment]
Does this mean the classname also changes?

**Comment by KRDucky** [comment]
Im not following the line of reasoning here. Last I checked, my dentist never used Atropine in my mouth. He used Lidocaine. I asked a doctor if you could interchange the two and he said no. They were for two different purposes.

**Comment by KRDucky** [comment]
Maybe Lidocaine and Morphine but not Lidocaine and Atropine.

Atropine: Antidote Treatment Nerve Agent, Auto-Injector (ATNAA) (atropine and pralidoxime chloride injection)
The ATNAA Auto-Injector should be administered by military personnel who have had adequate training in the recognition and treatment of nerve agent intoxication. It is intended as an initial treatment of the symptoms of organophosphorous nerve agent poisoning; additional medical care should be sought as soon as possible. 
Individuals should not rely solely upon agents such as atropine and pralidoxime when encountering a situation of nerve agent exposure. Primary protection against exposure to organophosphorous nerve agents is the wearing of protective garments including masks designed specifically for this use. Evacuation and decontamination procedures should be undertaken as soon as possible. Medical personnel assisting evacuated victims of organophosphorous nerve agent poisoning should avoid contaminating themselves by exposure to the victim's clothing. 

In the face of life-threatening poisoning by organophosphorous nerve agents and insecticides, there are no absolute contraindications for the use of atropine.


No where is Lidocaine listed as a treatment for Nerve agents and Chemical Agents.

**Comment by DocScarle** [comment]
Im well aware of what it is used for in RL. The fact is Atropine is used to counteract overdoses of Epinephrine and Tachycardia in game needs correcting. I'm also aware of of Lidocaine use at the dentist. I am talking about using Lidocaine Hydrochloride to correct sinus rhythm.

**Comment by hypomaniac** [comment]
I'm sorry, but you're just wrong. Lidocaine is used to cardiovert ventricular rhythms, not sinus rhythms. A simple look at the ACLS algorithms would show you that. Lidocaine is specifically contraindicated in sinus rhythms. Atropine doesn't make sense being used purposely as a vagolytic but at least it causes that effect.

**Comment by DocScarle** [comment]
Atropine causes Tachycardia. We want the opposite. Propranalol is the answer here not Lidocaine Hydrochloride.

**Comment by hypomaniac** [comment]
Atropine does not cause tachycardia. It is an anticholinergic that acts on the parasympathetic nervous system. Tachycardia is a sympathetic response. Epinephrine causes tachycardia. Using a beta blocker isn't fixing things, it's causing more problems. Having medications just for the sake of countering side effects from other medications is just adding features for the hell of it.

**Comment by hypomaniac** [comment]
I think a better alternative, in the world of ACE, would be adenosine. Something to look into/think about.

**Comment by DocScarle** [comment]
In the world of ACE yes it would. Thats a good call. Id rather have something that would destroy the Epinephrine effects rather than a drug that fights against it. In the same way that Naloxone does on narcotics.

**Comment by DocScarle** [comment]
Right Im going to close this and open a new one with Adenosine.

**Comment by bux578** [comment]
#1573
