### ISSUE TITLE
Enabling RHS optionals does not activate bullet trace for M2010

### ISSUE THREAD

**Issue by enderrrrrrrrrr** [acemod/ACE3#1569]
ACE3 Version: 3.x.x
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* @cba_a3
* @ace3
* @RHSUSAF

**Placed ACE3 Modules:**
Standard Modules and ones pertaining to advanced ballistics

**Description:**
Bullet trace effect is not working for the M2010 After importing the Optional components.

**Steps to reproduce:**
Attempt to use LRPS and M2010 to view bullet trace effect. Works with other rifles from the same pack.

**Where did the issue occur?**
multiplayer

**RPT log file:**

**Comment by ulteq** [comment]
Can't reproduce on latest master. Make a new issue, if the bug is not gone with the next release.
