### ISSUE TITLE
Optinal RHS pbo does not activate mil dot system for Leopold scopes.

### ISSUE THREAD

**Issue by enderrrrrrrrrr** [acemod/ACE3#1570]
ACE3 Version: 3.0.1
(indicate if stable or dev, if dev indicate the commit the version is based on)

Mods:

@cba_a3
@ace3
@RHSUSAF
Placed ACE3 Modules:
Standard Modules and ones pertaining to advanced ballistics

Description:
Mil dot system is not used for Leopold scopes when adding the optional files for RHS into ace

Steps to reproduce:
Attempt to use the leopold scope and the pressing page up or down. It uses the vanilla arma method for zeroing as opposed to the mil dot system utilized by ace.

Where did the issue occur?
multiplayer

RPT log file:

**Comment by ulteq** [comment]
Can't reproduce on latest master.
