### ISSUE TITLE
IR Strobes lasting 5 minutes. Can't take them off once they burn out.

### ISSUE THREAD

**Issue by enderrrrrrrrrr** [acemod/ACE3#1571]
ACE3 Version: 3.0.1

Mods:

@cba_a3
@ace3

Placed ACE3 Modules:
Standard Modules 

Description:
IR strobes don't last very long and when they burn out they cant be taken off

Steps to reproduce:
Attach ir strobe. Wait a short amount of time till they burn out. Try to take it off.

Where did the issue occur?
multiplayer

RPT log file:

**Comment by kavinsky** [comment]
i can confirm this issue, the IR Strobe disappears and you cant detach it using interaction menu.

**Comment by WastedMike** [comment]
i can also confirm as well. Shouldn't they work for a few hours and not 5 minutes?

**Comment by esteldunedain** [comment]
Hey, @WastedMike, are you sure you are referring to the personal IR Strobe and not to the IR grenade (which is also attachable and has a duration of exactly 5 minutes)??

**Comment by ElectroEsper** [comment]
Had this issue with ir strobes, ir grenades and chemlights.

**Comment by SzwedzikPL** [comment]
We have this issue on 3.1.1. Example: https://www.youtube.com/watch?v=vOqOJaOceKs

Cant repro on 3.2.0
