### ISSUE TITLE
Scope: request knob click in MOA instead of mils

### ISSUE THREAD

**Issue by JoeyTong** [acemod/ACE3#1572]
Dear Developer,

The elevation and windage knob in real-life sniper scope got clicks of 1/4 MOA (minute of angle) rather than 0.1 mils. Since a lot of real-life sniping estimation and calculation tricks are based on MOA, can we update the knob into 1/4 MOA increment ? Or at least got one variation besides current mils click ones?
And pls keep the mil dots image on the scope since its good for movement leading estimation.
Thank you very much !

**Comment by ulteq** [comment]
We're not going to replace the MIL turrets, but we might allow 3rd party mod developers to add scopes with MOA turrets in the future.

> Since a lot of real-life sniping estimation and calculation tricks are based on MOA

Multiply with 3.38 and you're done.

**Comment by ulteq** [comment]
Feature requests go here: https://github.com/acemod/ACE3/issues/414
