### ISSUE TITLE
Atropine to Adenosine

### ISSUE THREAD

**Issue by DocScarle** [acemod/ACE3#1573]
Atropine is the incorrect drug to use in the correction of heart rates, in the case of Epinephrine OD. Adenosine is a better choice. It would require nothing more than a name change to Atropine as the current effect in ACE are the same.

**Comment by KRDucky** [comment]
My understanding is that Atropine was in from ACE2 days for NBC gear and chemical/bio attacks

**Comment by headedhorseman101** [comment]
>My understanding is that Atropine was in from ACE2 days for NBC gear and chemical/bio attacks

:+1:

Would love to see NBC scenarios implemented.

**Comment by Glowbal** [comment]
#3134

**Comment by bux578** [comment]
Closing in favor of ^
