### ISSUE TITLE
Impossible to unload wounded soldier from a vehicle

### ISSUE THREAD

**Issue by Sartax** [acemod/ACE3#1575]
Hi ! Awesome addon, I was waiting this since a long time !

But I have some question (because we have some problems with my team).

We are using RHS Mod (U.S Forces), and for us it's impossible to unload somebody from a vehicles if he's inconscious. If we try to unload somebody, first case, the soldier remains in the vehicle, and in the second case, he's unload, but he's teleport in the vehicle.

**Comment by ulteq** [comment]
http://ace3mod.com/wiki/user/how-to-report-an-issue.html
