### ISSUE TITLE
[Adv. Medical] Implement simulation of adrenaline

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1578]
As discussed with @ulteq on Slack here is an idea to implement adrenaline effects on player:
- Adrenaline level increases mainly when you're injured
- Big injuries suddenly increase the adrenaline level
- Adrenaline level drops slowly over time
- High adrenaline levels increase HR, suppresses pain, create tunnel vision, increase sway...
- Could be connected with Laxemann's Supression effects

**Comment by headedhorseman101** [comment]
It would allow for an increase in heart rate if a unit was sprinting for a long time or if a unit gets into a firefight or hits an IED.

**Comment by gienkov** [comment]
I can say that with 3.1.0 advanced medical is very stable and bugfree :).

**Comment by headedhorseman101** [comment]
>I can say that with 3.1.0 advanced medical is very stable and bugfree :).

Awesome! :+1:

**Comment by ulteq** [comment]
This will probably never make it into the game.
