### ISSUE TITLE
M136|BVP RHS compatibility, server crash

### ISSUE THREAD

**Issue by ArcanumSK** [acemod/ACE3#1583]
ACE3 Version: 3.0.1

**Mods:**
Server:
* @cba_a3
* @task_force_radio
* @ace3
* @ares
* @asdg_jr
* @rh_acc
* @rhs_usf3
* @rhs_afrf3
Clients:
server+
STHUD

**Placed ACE3 Modules:**
Serverside Config

class ace_common_forceAllSettings {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_frag_enabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_interaction_EnableTeamManagement {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_magazinerepack_TimePerAmmo {
    value = 1.5;
    typeName = "SCALAR";
    force = 1;
};
class ace_magazinerepack_TimePerMagazine {
    value = 2;
    typeName = "SCALAR";
    force = 1;
};
class ace_magazinerepack_TimePerBeltLink {
    value = 8;
    typeName = "SCALAR";
    force = 1;
};
class ace_map_BFT_Interval {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_map_BFT_Enabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_map_BFT_HideAiGroups {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapIllumination {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapShake {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapLimitZoom {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_map_mapShowCursorCoordinates {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_maptools_EveryoneCanDrawOnBriefing {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_microdagr_MapDataAvailable {
    value = 2;
    typeName = "SCALAR";
    force = 1;
};
class ace_mk6mortar_airResistanceEnabled {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_mk6mortar_allowComputerRangefinder {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_mk6mortar_allowCompass {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_nametags_showCursorTagForVehicles {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_nametags_PlayerNamesViewDistance {
    value = 5;
    typeName = "SCALAR";
    force = 1;
};
class ace_nametags_PlayerNamesMaxAlpha {
    value = 0.8;
    typeName = "SCALAR";
    force = 1;
};
class ace_respawn_SavePreDeathGear {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_respawn_RemoveDeadBodiesDisconnected {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_respawn_BodyRemoveTimer {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_switchunits_EnableSwitchUnits {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_switchunits_SwitchToWest {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_switchunits_SwitchToEast {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_switchunits_SwitchToIndependent {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_switchunits_SwitchToCivilian {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_switchunits_EnableSafeZone {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_switchunits_SafeZoneRadius {
    value = 100;
    typeName = "SCALAR";
    force = 1;
};
class ace_vehiclelock_DefaultLockpickStrength {
    value = 10;
    typeName = "SCALAR";
    force = 1;
};
class ace_vehiclelock_LockVehicleInventory {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_vehiclelock_VehicleStartingLockState {
    value = -1;
    typeName = "SCALAR";
    force = 1;
};
class ace_weather_enableServerController {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_useACEWeather {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_syncRain {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_syncWind {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_syncMisc {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_weather_serverUpdateInterval {
    value = 60;
    typeName = "SCALAR";
    force = 1;
};
class ace_winddeflection_enabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_winddeflection_vehicleEnabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_winddeflection_simulationInterval {
    value = 0.05;
    typeName = "SCALAR";
    force = 1;
};
class ace_winddeflection_simulationRadius {
    value = 3000;
    typeName = "SCALAR";
    force = 1;
};
class ace_explosives_RequireSpecialist {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_explosives_PunishNonSpecialists {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_hearing_EnableCombatDeafness {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_hearing_EarplugsVolume {
    value = 0.5;
    typeName = "SCALAR";
    force = 1;
};
class ace_hearing_UnconsciousnessVolume {
    value = 0.4;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_level {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_medicSetting {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableFor {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableOverdosing {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_bleedingCoefficient {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_painCoefficient {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableAirway {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableFractures {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableAdvancedWounds {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableVehicleCrashes {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableScreams {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_playerDamageThreshold {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_AIDamageThreshold {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableUnconsciousnessAI {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_preventInstaDeath {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableRevive {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_maxReviveTime {
    value = 300;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_amountOfReviveLives {
    value = -1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_allowDeadBodyMovement {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_allowLitterCreation {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_litterCleanUpDelay {
    value = 1800;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_medicSetting_PAK {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_medicSetting_SurgicalKit {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_consumeItem_PAK {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_consumeItem_SurgicalKit {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_useLocation_PAK {
    value = 3;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_useLocation_SurgicalKit {
    value = 2;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_keepLocalSettingsSynced {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_healHitPointAfterAdvBandage {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_allowUnconsciousAnimationOnTreatment {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_moveUnitsFromGroupOnUnconscious {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_menuTypeStyle {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_advanced_ballistics_enabled {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_alwaysSimulateForSnipers {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_disabledInFullAutoMode {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_onlyActiveForLocalPlayers {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_ammoTemperatureEnabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_barrelLengthInfluenceEnabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_bulletTraceEnabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_simulationInterval {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_advanced_ballistics_simulationRadius {
    value = 3000;
    typeName = "SCALAR";
    force = 1;
};;

**Description:**
When you try to shoot any version of BVP from RHS with M136 from RHS, it will crash dedicated server (log included).

**Steps to reproduce:**
Do or do not include compatibility PBOs form optional folders, it does NOT matter
Start Dedicated server
Place BVP-2 from zeus
Place US Rifleman M136
Shoot BVP2
Watch server burn
Find post on RHS tracker
http://feedback.rhsmods.org/view.php?id=501
Report to ACE team

**Where did the issue occur?**
Multiplayer (dedicated server)

**RPT log file:**
http://pastebin.com/aWJ1ipKh
Only last seconds, whole log too big.

**Comment by esteldunedain** [comment]
Sorry, nothing in that log points to ACE. All the errors shown are specific to RHS.

**Comment by PabstMirror** [comment]
Could you try removing all ACE pbo's besides main, modules and common and see if you can reproduce the crash?

**Comment by esteldunedain** [comment]
Also try disabling ace frags.

**Comment by ArcanumSK** [comment]
Sorry, issue with RHS. Posted on ther bugtracker. Resolving there.
