### ISSUE TITLE
Dragging on the top floor of a building breaks animation

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#1584]
ACE3 Version: 3.0.1
stable

**Mods:**
* @cba_a3
* @ace3
* @AiATP
* @RHS3

**Placed ACE3 Modules:**
none

**Description:**
The middle sized apartment buildings on united sahrani, the one where only the top floor and rooftop are enterable. 
Tried dragging someone in one of these buildings, on the top floor, once the dragging animation started, the player that was being dragged was set to the ground and there was no way to stop the dragging animation except to move down the stairs all the way to the ground floor and drag the downed player again.

**Steps to reproduce:**
Get into one of the apartment buildings (middle sized, with only the last floor and roof open)
Drag somone else and he will get teleported to the ground with the dragger still remaining in the animation with no "stop dragging option"

**Where did the issue occur?**
multiplayer

**RPT log file:**
-nologs was enabled during this. No logs available

**Comment by Glowbal** [comment]
Thank you for your report. The teleporting is fixed on the latest master with 4802ffe.
