### ISSUE TITLE
server pbo.

### ISSUE THREAD

**Issue by dvdbrewster** [acemod/ACE3#1590]
This might not be an issue, I could be screwed up. The FrameWork instructions were pretty clear about getting settings. They copied nicely, and I made the cfg .hpp  I made a addon folder for the .pbo and included the user cfg file. Problem is Building the command line @cba; @ace;@newserveraddon; makes the game not launch.  Removing Either  @ace or @newserveraddon the game launches.
   MayB the command line is not right as I cannot type-serverMod=@newserveraddon, as I get errors for wrong characters in line.  Whats the command line look like?  The created folder goes in the main directory with the rest of the addons.(right?) 
   And jestServers has a tcadmin panel.  An optional server cfg space is there.. I am able to write -serverMod=@newserveraddon there, plus copy the cfg file.. which then opens into a file after pasting that Is formatted like a sqm ,  and being in the panel  u could change things from right there and save 
with one-click.  So changing things  would be easy. (STILL WITH ME?)  However changing these things right now has no effect on settings in a game where default ace parameters are in play , as I tried to change some of them and relaunch,, and nothing changed inGame. So I think the pbo does not load without it (@newserveraddon) being in the commandline, and if u put it there the server wont load. So I copied the settings in txt file from notepad (no codeing..big indian etc ..Unicode..)(I guess it saved in ANSI) then I copied it to cfg and now its a hpp.  Pasted to the notepad was the Example of what it should look like.. I copied under it..Then it didnt work,, so I deleted the example..It didn't make any difference,  (both ways.  Something I did wrong,  IDK what.

**Comment by Glowbal** [comment]
In the `optionals folder` inside the ACE download folder you will find a `userconfig folder.` Inside you will find an ace folder which contains the  `serverconfig.hpp` file.

Copy this userconfig folder to your game root directory. In this case, the installation directory of your server.

Next, browse to the `serverconfig.hpp` file, now located inside the userconfig folder \ ace inside your server installation directory. Example:
`C:\program files (86)\games\arma 3\userconfig\ace\serverconfig.hpp`

You state you already know how to get the settings, so next copy them into the serverconfig.hpp file.

The final step is finding the `server.pbo` which is located also in the optionals folder inside the ACE download folder. you will want to copy this pbo file and place it in an addons folder which you load your game with. 

It is advised to create a new `@aceserver` folder with an AddOns folder inside and place the `server.pbo` file in that AddOns folder. Launch `@aceserver` like you would any other addon (or use the servermod parameter).

**Comment by kripto202** [comment]
what does server.pbo do anyway?

**Comment by Glowbal** [comment]
@kripto202 http://ace3mod.com/wiki/framework/settings

**Comment by dvdbrewster** [comment]
Its working !  Last question, (thank u)  The serverMod parameter, where would I write that ?

**Comment by Glowbal** [comment]
@dvdbrewster Have a read through this: https://community.bistudio.com/wiki/Arma_3_Startup_Parameters#Server_Options That should explain everything.

Good luck.

**Comment by dvdbrewster** [comment]
I got it.  Its really a nice thing on JestServers to allow adjusting the user parameter settings we exported..
-servermod= exports the saved file that expands in the console..to a file (notepad) in the games main directory..after save..U can opy and paste new to users cfg hpp. very neat addition.   .00.

**Comment by dvdbrewster** [comment]
I have been away for awhile,  But when I do this as described, I can get it works,(change parameters, verify in game they are changing),  But I am the only one that can join the server.  Errors in strg. according to rpt.  I tried moving the pbo to the games addons default location, and back to the games directory,  same thing.

**Comment by dvdbrewster** [comment]
The problem is this    =  23:58:43 Unsupported language English in stringtable  .   Either way u launch the server pbo mod, it works, but nobody but me can connect to the server, and this is the error that disappears if U launch ace3 without the server pbo mod. And launch the server pbo mod by itself with the user cfg, also gets the above error in RPT files.
