### ISSUE TITLE
Claymore directional mines turn to face north when they are armed by other player than the one who set it down to the ground.

### ISSUE THREAD

**Issue by Bummeri** [acemod/ACE3#1606]
To test this:

1. Have two players with Claymore directional mines and ace_clacker.
2. Player 1 sets the claymore to face the right direction.
3. player 2 connects the clacker to the directional mine and arms it.
4. The directional mine automatically turns to face north on all players and will also explode towards the north.

**Comment by PabstMirror** [comment]
This will be fixed in next release 
commit: adf29d75e3d536d21c3ab3f636a0149083d9130a
