### ISSUE TITLE
Interaction Menu causes game to freeze

### ISSUE THREAD

**Issue by Wired-Tiger** [acemod/ACE3#1610]
Version:
ACE3.0.1
CBA1.1.23.150604

Modules used:
None

Description:
I am trying to figure out how to add custom interactions to the menu. From What I've been able to tell you just have to create an interaction action, and then add it to the tree. However, when I try to do this the game freezes when I try to use the interaction menu when I try to add something.

How to reproduce:
I placed a player soldier, and then a second soldier named "civy". I then added the following two lines to the init.sqf file.

["VulcanPinch","Vulcan Pinch","selector0.paa",{hint "He is dead";},{true}] call ace_interact_menu_fnc_createAction;
[civy, 0, ["ACE_TapShoulderRight"],VulcanPinchAction] call ace_interact_menu_fnc_addActionToObject;

When I then preview the mission it works fine until I try to interact with other soldier/civilian. The game immediately freezes.

Where it happens:
Both Single and multiplayer. However, in mulitplayer it seems to only effect the client. The server keeps running.

RPT:
http://pastebin.com/84J46a8w

**Comment by Wired-Tiger** [comment]
If this is user error, and not a scripting error, I am sorry. I would appreciate a more detailed description on how to add to the interaction menu. I've spent quite a bit of time trying to figure this out.

**Comment by PabstMirror** [comment]
Confirm crash happening using your code.

I believe `VulcanPinchAction` would be nil because you don't seem to be defining it on the first line.
But we should probably do some sanity checks.

Right now we get:
`cursorTarget getVariable ["ace_interact_menu_actions", [-1]];`
= [[any,["ACE_TapShoulderRight"]]]

```
VulcanPinchAction = ["VulcanPinch","Vulcan Pinch","",{hint "He is dead";},{true}] call ace_interact_menu_fnc_createAction;

[cursorTarget, 0, ["ACE_TapShoulderRight"],VulcanPinchAction] call ace_interact_menu_fnc_addActionToObject;
```
Seems to be working

**Comment by esteldunedain** [comment]
Yeah, that's it
