### ISSUE TITLE
bullet calculation of AtragMX does not match gun performance

### ISSUE THREAD

**Issue by JoeyTong** [acemod/ACE3#1624]
The bullet calculation of AtragMX for default M200 and RHS M2010 does not match gun performance. I'm pretty sure I got every valid parameters input in the AtragMX. For M2010, at less than 700m the bullet hits much lower and at more than 900 it hits way higher.
Suspect preset gun data is invalid.
For example, both gun are NOT zeroed at 100m in the game (experimental data is between 60-70, that's wield)

**Comment by ulteq** [comment]
Did you enable the advanced ballistics module?

What gun profiles did you use?

How much was the bullet drop off?

> For example, both gun are NOT zeroed at 100m in the game (experimental data is between 60-70, that's wield)

That's a bug in the vanilla game. But you can correct for it by adjusting the scope zero via the interaction menu (equipment -> Set zero adjustment).

**Comment by JoeyTong** [comment]
I just enable ACE3 at ARMA launcher, haven't seen relative options while enabling the mod, haven't seen relative options in ACE options in ARMA main menu. Will it enable by default ?

Gun and profile used:
Gun: RHS M2010
AtragMX Profile: .300 WM Mk248 Berger

At 400m: about 20cm lower than aim point
At 1100m: about 30-40cm higher than aim point
Is this normal?

I'll check the zero adjustment in interaction menu, thank you !

**Comment by esteldunedain** [comment]
> Will it enable by default ?

No, the Advanced Ballistics code is disabled by default, so you need to add the appropiate module to the mission for it to work.

**Comment by JoeyTong** [comment]
How can I enable Advanced Ballistics? Only via mission editor?

**Comment by ulteq** [comment]
> At 400m: about 20cm lower than aim point
At 1100m: about 30-40cm higher than aim point
Is this normal?

No.

The correct ATragMX gun profile for the RHS M2010 is: `.300WM Mk248 Mod 1`
The muzzle velocity without advanced ballistics is ~870 m/s.

You can use this mission to measure your muzzle velocity (by shooting the steel targets): http://forums.bistudio.com/showthread.php?181296-SP-360-Degree-Training-Course

**Comment by JoeyTong** [comment]
I tried to adjust scope zero but can not find it in action menu.
Did I miss something? How can I enable advanced modules? I find the files are in addons folder by default but I cannot find any options to enable it.

**Comment by JoeyTong** [comment]
Got it ! Thanks Ulteq
