### ISSUE TITLE
Tweak grenade modes to make them more useful

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#1628]
The following suggestions com from Dyslyecxi:

> The 'drop grenade' feature of the ACE3 grenades could be made useful if instead of it falling immediately on ammo creation, it instead had a small velocity forward, sufficient to clear windowsills/ledges etc. Standing right up against this ledge and using it causes the grenade to land on said ledge. 

![image1](https://gyazo.com/c3f38adb550012dad6e8a5908ff2bcba.jpg)

> I guess that's relevant for @commy2 based on the source for it

> "precise throw" would also be a bit more usable if it was zeroed for something like 5-10m away from the player. Right now it's aligned with weaponDirection, so by the time it gets to a practical short-range distance, it's already fallen significantly below the crosshair. The problem with the default grenade throw is that it has that zero too far away, so it goes significantly above the crosshair/point of aim. Tweaking that a bit could make it pretty usable.

> A quick test shows that normal throw has a 13 meter zero, so probably 5m would be a good compromise.

> `_projectile setVelocity (_velocity vectorMultiply 0.45);`

> seems to be pretty good for a 'drop-esque' short lob. Lands three meters away for me when aiming level, has enough velocity to clear a ledge. Aiming up/down allows you to finesse it past that point if necessary, such as if you wanted to put a chemlight exactly on a given spot for whatever reason.

> Makes it much more viable for urban usage.

> Aiming up to cause it to land closer:

![image2](https://gyazo.com/6cd40e9735ea15f7239ae60ab3286a72.jpg)

> Aiming level:

![image3](https://gyazo.com/cb9b0029e0f4c9bb5086cf45fcd1f08b.jpg)

> In MOUT this is a big thing, particularly as a defender of a structure. Being able to drop a grenade out of a window is huge when you're being assaulted. Example usage:

![image4](https://gyazo.com/a69980c2cd0d80824a8bddaac81c9b5d.jpg)

> And on the flip side, sometimes you get in a position where you want to drop a grenade right inside a room without throwing it across the room.

![image5](https://gyazo.com/338a66fd52f0cfe9768a77eb99bc7051.jpg)

> Also dropping over walls. You get the idea. It's essentially taking the "drop" and turning it into a very short lob, with aiming high/low permitting you to make it behave the same as the existing drop functionality. 

![image6](https://gyazo.com/773a83b6c66e74d668beee4ac8d6bf82.jpg)

**Comment by PabstMirror** [comment]
I had been working on new grenade throw ("what you see is where you throw", cooking, throw power).
Still early prototype, but might have something later this week.

**Comment by BaerMitUmlaut** [comment]
Instead of having different modes, why not adjust the throwing power with the scroll wheel or something similar?

Much more intuitive than having modes in my opinion. Something like this as an indicator could be nice and should be possible (probably not stepless, but the scroll wheel isn't stepless either):
http://i.imgur.com/jEmFe87h.jpg

**Comment by VKing6** [comment]
These look really good.

An option from ACE2 to reset the grenade mode for each throw would also be welcome.

**Comment by gienkov** [comment]
Flight path could be useful too, in VBS you can see it so you know how it will fly.

**Comment by Khaosmatic** [comment]
Baer in cases where peoples mouses might bug out or what not means it may be harder to adjust like that, and also its another use of the horrible action menu. Dslyecxi has made some good points there, it would be great to see the system he mocked up in A2 where it appears in fronts and the sorts because that looked awesome!

**Comment by BaerMitUmlaut** [comment]
Oh you misunderstood me. With scroll wheel I don't mean the action menu, but just scrolling up and down. If CBA allows using the scroll wheel as a keybind you can also rebind this to a keyboard key.
