### ISSUE TITLE
CheckPBO Mode 2 (Kick) not functional

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#1632]
ACE3 Version: 3.1.0.0 Pre-Release

**Mods:**
* `@cba_a3`
* `@ace3`

**Placed ACE3 Modules:**
* CheckPBOs

**Description:**
CheckPBO module still won't kick due to usage of serverCommand and it's restriction per server and password. IIRC @commy2 was saying about replacing how this works.

**Steps to reproduce:**
* Set CheckPBOs module to mode 2
* Watch how you don't get kicked

**Where did the issue occur?**
MultiPlayer - Dedicated Server

**RPT log file:**
N/A

**Comment by esteldunedain** [comment]
@jonpas is testinga fix based on closing display 46 atm

**Comment by jonpas** [comment]
Test functional, will be pull requesting in a bit.

**Comment by Glowbal** [comment]
Fixed by #1633
