### ISSUE TITLE
Telescopic Ladder bugs

### ISSUE THREAD

**Issue by JamieGoodson** [acemod/ACE3#1637]
ACE3 Version: 3.1.0 prerelease

**Mods:**
- @cba_a3
- @ace3

**Description:**
- Ladders can be climbed from other side of wall.
- Ladder can be climbed while being deployed by someone else.

**Where did the issue occur?**
Multiplayer (not tested in SP).

Edited by @esteldunedain: Removed resolved bug.

**Comment by jonpas** [comment]
Self-Todo:
- [ ] Add `lineIntersectsSurfaces` check on base interaction point of the ladder
- [ ] Set variable "deployment", allow climbing only when NOT in "deployment" state

**Comment by jonpas** [comment]
Moving to backlog, due to not being able to hide the vanilla action we can't really fix this properly.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
