### ISSUE TITLE
Spotting scope animation is incorrect

### ISSUE THREAD

**Issue by mistergoodson** [acemod/ACE3#1638]
ACE3 Version: 3.1.0 prerelease

**Mods:**
* @cba_a3
* @ace3

**Description:**
- Spotting scope animation is incorrect - should be prone and closer to the scope.
![](http://i.imgur.com/Oxrp7mXh.jpg)

**Where did the issue occur?**
Multiplayer (not tested in SP).

**Comment by kripto202** [comment]
i think it is more of a place holder for right now. In my opinion, you shouldn't go in a gunner seat but instead get the option to look through scope and the scope would move just like a remote designator.
