### ISSUE TITLE
[Basic Medical] Allow non-medics to revive

### ISSUE THREAD

**Issue by brokenhands** [acemod/ACE3#1641]
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* ACE Basic Medical

**Description:**
My group really likes the concept of penalizing non-specialists with explosives. I'd like to request a setting to allow non-medics to revive, but at a penalized time (or chance of failure?). The same system could be expanded to Engineers, possibly AT classes to penalize lock times. 

**Steps to reproduce:**
* Operate with a small squad and one medic. With the lack of AI revive, the desire for this becomes huge.

**Comment by mistergoodson** [comment]
I would love for non-medics to be able to revive, while still giving medics a unique ability/advantage  (e.g. PAKs can be used by medics only) that doesn't involve simple time penalties.

**Comment by Neodyn** [comment]
@mistergoodson  I agree with you. This option would be greate for small groups like mine !

**Comment by Trigger81** [comment]
Absolutly confirm!  :+1:

**Comment by Dumedo** [comment]
Would be great

**Comment by Cuel** [comment]
:+1:

**Comment by Trigger81** [comment]
Do it like ace2 Medic. Bandages -> mophi, Epi for all and First aid to Medic. Also medics can all faster

**Comment by ferox113** [comment]
+1 on the non-medics to revive. I kind of like the new "basic" system, so I wouldn't change the procedure that much -but perhaps one could make this fully customizable for the mission makers out there?

IDEA IN DETAIL:
- How about implementing a fully customizable feature into the medical modules (basic as well as advanced); giving the mission maker full control of what medical equipment/procedure (epi, blood, plasma, surgery etc.) is to be restricted to a specific location (i.e. grouped objects/buildings/vehicles, of the module) and to a specific role (medic/non-medic).

- Also, please bring back the AGM function of "punishing non-medics". It makes a lot of sense having the work harder and being a bit slower, when you are not in medical training other than being the first responder of the group/fire team. Naturally it will take some more time to stop the trauma from extending, with the limited resources available.

This "punish" factor could be a "+" decimal; again, leaving it for the mission maker to decide how much of a difference he'd think be necessary. Set it to a factor of 0 (disabled), +0,5 (finishing the first-responder treatment 50% slower than extended medically trained personnel), +1 (100% slower -in other words; takes twice as long for non-medics, than medics, to treat the patient to a stabile status).

**Comment by Dumedo** [comment]
I totally agree with ferox113. In mission with revive only, medics are weakest link because if they become unconsciuos there is no way other then respawn or fail mission.

**Comment by brokenhands** [comment]
This is totally addressed by the CPR addition! Great fucking job consider this "hole" totally closed.

**Comment by Dumedo** [comment]
I don't think I've fully understand what you said in the previous post..

**Comment by SilentSpike** [comment]
Non-medics can now revive people via means of CPR

**Comment by brokenhands** [comment]
@SilentSpike I'm hoping we're seeing intended behavior then. This latest update has our non-medics able to revive via CPR on Basic Medical. If that's not working as designed, the scope of this issue should change to: "Plz keep the current revive bug with CPR and Basic Medical".

I can reopen if that's preferred, I was just trying to follow up on closing out old stuff that's been addressed.

**Comment by SilentSpike** [comment]
I'll have to defer to @Glowbal on that point. I'm not entirely up to date on our medical behaviour.

**Comment by Dumedo** [comment]
@brokenhands ok now I understand, but the problem is still there. 
If medic or anyone else need blood transfusion non-medics can't do it, so you can wake up a player maybe with CPR but if he has lost too much blood he will pass out immediately.

**Comment by Glowbal** [comment]
For basic medical: 

CPR only extends the life timer when the revive module/setting is enabled. Anyone is able to do this. You are not able to revive anyone with CPR, only extend their time alive.

Advanced medical is still the same as it has always been.

**Comment by brokenhands** [comment]
I'd like to reopen this again then, feel free to close if you feel it's too much of a feature request @Glowbal. 

If I were to phrase it as a request: Please add another option to the Revive module to include "All,Medic,Doctor" for options, or support (a) wildcard(s) for medic class. The work-around of adding individual units to the module requires manual editing on every mission. The suggested change would allow people to run missions via ace_server with this configuration, without requiring them to edit the mission and list all the player units by hand.

**Comment by ArcanumSK** [comment]
Whit revive timer, make CPR able to revive (chance) and make it work in ADVANCED and BASIC.

**Comment by Glowbal** [comment]
Next update has a setting for this
