### ISSUE TITLE
explosives

### ISSUE THREAD

**Issue by Altrecz** [acemod/ACE3#1642]
Hi, I and few my friends, we have a problem with placing the explosives . If we wish placing the explosives... we must to click on left button mouse, but we can't placing the explosives. Because if we hit left button we just only shoot.

A napíšu Vám to ještě česky protože moje angličtina stojí za houby. ;)
 Problém je v tom, že při pokládání vybušnin v armě to nabízí tu interakci otočit bombu, položit atd. Ale vůbec to nereaguje na tlačítka jednoduše střílíme a to je tak vše. Problém je v tom, že v AGM to funguje i s mody co používáme, ale bohužel ACE se s nečím očividně pere či je tam nějaký bug opravdu nevím. Byl bych vděčný za radu. Děkuji.

**Comment by esteldunedain** [comment]
Thanks. Please edit the report above following the instructions here:  [http://ace3mod.com/wiki/user/how-to-report-an-issue.html](http://ace3mod.com/wiki/user/how-to-report-an-issue.html) for details. We cannot help you find the issue without the further information indicated there.
