### ISSUE TITLE
Can you make Advanced Ballistic enabled by default?

### ISSUE THREAD

**Issue by JoeyTong** [acemod/ACE3#1644]
I found the enable method of advanced ballistic is really complex:
1. It can not be done by copy/paste or mod manager, so my teammates can not practice with it in their SP without messing with mission editor.
2. It can only enabled by mission editor, so most missions on workshop are currently not compatible.

So, why make it enabled by default? I think at least half of the ACE fans needed it badly for advanced sniping activity. 
With the scopes become mil incremental, all ACE players are forced to get used to the advanced way whether they liked or not. So make it default, stop them from struggle between advanced ballistic data in AtragMX and original gun performance that won't match.

**Comment by whiztler** [comment]
You can export ACE3 settings and embed them in a mission or have the server load them. More info:

http://ace3mod.com/wiki/framework/settings.html

**Comment by IsllEtman** [comment]
the only work around i am doing for SP is to remove the advanced ballistic pbo from ace and use the stand alone advanced ballistics mod beside ace.
