### ISSUE TITLE
Translation: medical -> STR_ACE_Medical_AdvancedMedicalSettings_painIsOnlySuppressed_Description

### ISSUE THREAD

**Issue by ShuraDE** [acemod/ACE3#1646]
https://github.com/acemod/ACE3/blob/master/addons/medical/stringtable.xml#L3244

English: Pain is only temporarily suppressed, not removed
Actual german version says: "Bandaging removes bloodstains" like (STR_ACE_Medical_healHitPointAfterAdvBandage)

It should be like "Schmerzen werden nur zeitweise unterdrückt, aber nicht entfernt."

**Comment by Glowbal** [comment]
Was fixed by 82d80359d1b
