### ISSUE TITLE
[Adv. Medical] Realistic / Roleplay friendly changes regarding dying and CPR

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1649]
This is something I was discussing about with @ulteq on Slack.

These two things I write about below are related only to advanced medical (since I don't use basic at all) and they are related to each other.
One fact for beginning - right now (or since Alpha) **it is impossible to disable ragdoll**, source: http://feedback.arma3.com/view.php?id=4063
If it were possible to disable ragdoll then those two things I write about below could be implemented far easier.
#1. CPR

Ok so first idea is to change how CPR works, since in RL you want to do CPR until your restore heart rate or until you decide to stop it. But until you decide to stop it you want to do it non-stop, right? Right now you have to restart (select CPR again from interaction menu) after each one cycle.
**Fact**: In ACE you have 2 to 12 minutes to do CPR in case of cardiac arrest. And it needs to be successful one, there is fail rate implemented already which is good.
So what if you fail to do successful _CPR cycle_ in this time? Right, player in front of you will die since ACE will execute setDead function on him, thus making him do **ragdoll animation**. At this time you _know_ that you can't do more for him and you know that he is really dead (after a while that player will propably exit server and you will see disconnect message too). This is something that definitely kills roleplay. And this is part when second change below comes in.

Summary:
- Add ACE Settings client side option to show CPR cycle notification after each completed CPR cycle, so you can count how many you have done already using visual feedback
- Change CPR so it does CPR non-stop until you succed or until you hit ESC to "give up"
- Non-stop CPR animation playing while doing CPR
#2. Dying

**1st fact**: Right now if you get enough damage at once then you will die and do ragdoll. That is good and it should stay as is.
**2nd fact**: Right now ACE will execute setDead function **immediately** when certain conditions are met. That is not good and this is when my idea comes in.

So my proposed change is to implement new medical module setting named `Do ragdoll only when no players are around`. Enabling it makes it so when dying conditions are met, and there are few for example _cardiac arrest timer_ or _blood volume level_ one, then instead of immediately executing setDead function make it so **first** player vision goes darker and darker, decreasing his tunnel vision until screen becomes completely black, lets say that this transition will last one minute so it's not suddenly black. **Second** and most important give player "**dead state**" parameter when dying conditions are met, at this time nothing, completely nothing can be done to revive player. When ACE detects that player have "dead state" parameter on, then ACE will wait with executing setDead until there are no players in vicinity of let's say 100m for at least 1 minute. After there are no players around then ACE setDead will kick in and dead player will do ragdoll.

Why this change could be useful? Look again at 1. CPR change above and think: You have person in very bad state and in cardiac arrest in front of you, you start doing CPR... 1st cycle fails, 2nd too... 3rd... and 4th... 5th (let's say at this point you were unlucky and ACE cardiac arrest timer kicks in and sets "dead state" to this player, but he is still lying as he was before so you **can't notice that** in any way) ... 6th cycle failed and so 7th too... nothing. You give up, you notice that nothing else can be done to save him so you stop doing CPR and go for a bodybag...  Roleplay friendly change.

Without this change it is now like that:
Player is in cardiac arrest, you start doing CPR... 1st cycle fails, 2nd too... 3rd... 4th... and suddenly you see him doing ragdoll since cardiac arrest timer kicked in. "Ok he have done ragdoll so I can stop doing CPR, I can do nothing, he is dead". That is bad no?

Summary:
- Can be set through module settings: `Do ragdoll only when no players are around` - `Enable` / `Disable` so people can decide if they want this level of simulation or not
- Make it so players get "dead state" when dying conditions are met
- Make it so players do ragdoll only when "dead state" is detected and no players are in vicinity of let's say 100m for minimum time of 1 minute, dead removing scripts can still work on players, if one is even used
- If above is enabled and person is in unconscious state (lying down and tunnel vision and black screen on) then if person hits dead state then his tunnel vision will became extremely blurry and get smaller and smaller until it turn completely black so he knows he is dead now and can exit server. Make it so that transition lasts minute or so.
- Change bodybag condition so you can pack people inside them only when they are in "dead state" or when they already did ragdoll (!alive is true on them)

**Comment by gienkov** [comment]
Has this been reviewed?

**Comment by bux578** [comment]
> Has this been reviewed?

I don't think so.

Pinging @Glowbal

**Comment by Thymo-** [comment]
Any updates on this?

**Comment by Arcanum417** [comment]
Would love to see this in medical-rewrite.

**Comment by dedmen** [comment]
This is on todo for medical rewrite. Bad bot.

**Comment by Arcanum417** [comment]
Bot might be growing sarcastic.

**Comment by jonpas** [comment]
Medical rewrite changes this significantly, ragdolling is also a thing. Changes we feel are good have been implemented
