### ISSUE TITLE
Expand make to automate release

### ISSUE THREAD

**Issue by Glowbal** [acemod/ACE3#1654]
Expand our make script to automate parts of the release process.

- [x] Update Version - README.MD
- [x] Update Download Link - README.MD
- [x] Update Core & Additional Features - README.MD
- [x] Update Version in 2 places - ace/mod.cpp
- [x] Update Version - ace/addons/main/script_mod.hpp
- [x] Create Zip file as ace3_<version>.zip
- [x] Create and Tag Pre-Release on GitHub

**Comment by jonpas** [comment]
Where would the version be read from? Or would you input it in make.py run?

**Comment by esteldunedain** [comment]
> Where would the version be read from? Or would you input it in make.py run?

All the require metadata could be the content of a file in the base directory.

**Comment by jonpas** [comment]
> All the require metadata could be the content of a file in the base directory.

Time to change where version is currently read from then. I have the version things almost done, will PR in a bit.

**Comment by ViperMaul** [comment]
@jonpas 
> Where would the version be read from? Or would you input it in make.py run? I suggest \z\ace\addons\main\script_mod.hpp

This is correct. The requirements are here:
https://github.com/acemod/ACE3/pull/1659#issuecomment-113028371

**Comment by ViperMaul** [comment]
Everything looks good. Thank you @jonpas.
