### ISSUE TITLE
TriageCard -> Used Medication Text after PAK/FAK

### ISSUE THREAD

**Issue by ShuraDE** [acemod/ACE3#1658]
The Triagecard output applied autoinjectors with there count.
After using a PAK the applied autoinjectors are still writen on TriageCard.

PAK resets appliedMedic
https://github.com/acemod/ACE3/blob/v3.0.1/addons/medical/functions/fnc_treatmentAdvanced_fullHealLocal.sqf#L63  (also in master branch and 3.1 tag)

I checked, Medication are correctly reset. Overdose works correctly after using PAK

Triagecard get's the info from a own array [QGVAR(triageCard), []];
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_displayTriageCard.sqf#L45

Solution maybe:
fullHeal dont clear this array
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatmentAdvanced_fullHealLocal.sqf

Like:
reset of [QGVAR(allUsedMedication), []]  on fullHeal

**Comment by Glowbal** [comment]
Will need to determine if we want to remove the complete history for medication or not.

We probably should, as a full heal means that all medication in the system will be removed.

Will pick up for 3.7.0.
