### ISSUE TITLE
Remove the instructions in the wiki about Atropine, as it is not yet implemented as it is described.

### ISSUE THREAD

**Issue by NummiE** [acemod/ACE3#1660]
"Atropine is a vagolytic and anticholinergic drug which in low dosages reduces heart rate but in high dosages increases it, countering effects of organophosphate poisoning (in NBC scenarios; anticholinesterase poisoning) and symptomatic bradycardia (in post-ROSC care and resuscitative medicine)."

This is what the Wiki tells me about Atropine. The wiki also instructs me to give more atropine to my medics and CLS's than Epinephrine or Morphine. http://ace3mod.com/wiki/feature/medical-system.html#3.1.2-vitals

Seeing as Atropine isn't working as described in the wiki, could it be possible to remove the wiki-reference to it and remove the recommendation from the medic loadouts? I don't see any use for it, and it might prove fatal in some scenarios when people use it thinking that it can raise heart rate, as all it only does is drop heart rate in-game right now. 

I googled around for half an hour to find out what Atropine actually does IRL, to write instructions for it into a mission our group was playing with Advanced Medical. 
After finding out what it does IRL, I figured that it isn't actually necessary in-game right now because there is no NBC-warfare yet. Also, we tested the heart rate thingies, it only drops heart rate, it is impossible to raise heart rate in-game with Atropine, the patient will suffer cardiac arrest before his pulse raises :smile:

**Comment by gienkov** [comment]
Atropine only lowers HR since 3.1.0 and thats all you want to know about it, pretty much.

**Comment by bux578** [comment]
pinging master of documentation @alganthe

**Comment by alganthe** [comment]
already done in #1850

**Comment by NummiE** [comment]
I still see this in the wiki:

Atropine is a vagolytic and anticholinergic drug which in low dosages reduces heart rate but in high dosages increases it, countering effects of organophosphate poisoning (in NBC scenarios; anticholinesterase poisoning) and symptomatic bradycardia (in post-ROSC care and resuscitative medicine).

**Comment by bux578** [comment]
@NummiE  #1850 hasn't been merged yet.

**Comment by alganthe** [comment]
This can be closed.

**Comment by bux578** [comment]
why?

**Comment by alganthe** [comment]
b-because the issue has been fixed ?

**Comment by bux578** [comment]
PR number please

**Comment by jokoho48** [comment]
https://github.com/acemod/ACE3/issues/1660#issuecomment-126724381 @bux578?

**Comment by bux578** [comment]
that was  25 days ago.
A possible comment could have been: "This can be closed because #1850 has been merged."
