### ISSUE TITLE
New deployable Tripod SW-KIT

### ISSUE THREAD

**Issue by wmazereeuw** [acemod/ACE3#1661]
You can't adjust the Tripod, it also tends to fall over alot. I understand this is a feature, but I feel if you would set it up on a slope you would counter the slope so its still upright.

**Comment by jonpas** [comment]
We are aware of that, some of the discussion can be found in #890

**Comment by ulteq** [comment]
Adjusting the tripod should work just fine. Try rebinding the ACE Adjustment key.

**Comment by 42nfl19** [comment]
Where can I find the Ace Adjustment key? If this could fix my problem, it could fix my problem for placing bombs, tripods, and the sandbags where I can't adjust them.

**Comment by madpat3** [comment]
no chance to solve the problem until BIS changed their "weapon-resting system"?

@42nfl19  
configure...controls...configure addons...ace3 common...modifier key

**Comment by bux578** [comment]
Close? It's working fine in 3.4.2.

**Comment by commy2** [comment]
assumed fixed
