### ISSUE TITLE
Range table for AWM FMJ bullets blank

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1662]
ACE3 Version: 3.1.1
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* @cba_a3
* @ace3
* @HLCMods, especially AWM

**Placed ACE3 Modules:**
* *Advanced ballistics*

**Description:**
*Range table doesn't generate properly for AWM FMJ bullets, screen below:*
http://steamcommunity.com/sharedfiles/filedetails/?id=463358425
That may be config error but reporting anyway.

**Steps to reproduce:**
* *Get AWM and FMJ magazine.*
* *Try to open range table, its blank*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*No script errors*

**Comment by ulteq** [comment]
I have contacted toadie2k.
