### ISSUE TITLE
HuntIR only fits vanilla GLs

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1663]
ACE3 Version: 3.1.1
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* @cba_a3
* @ace3
* @RHS
* @Leight OPFOR Pack
* @R3F Weapons
* @HLC Weapons
* @RH Weapons

**Placed ACE3 Modules:**
* *None*

**Description:**
*HuntIR rounds only fits vanilla underbarrel GL, it will not fit any other GL from other addons.*

**Steps to reproduce:**
* *Try to load HuntIR into RH M4 with GL or FN FAL with GL from HLC.*
* *You can't.*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*No script errors.*

**Comment by PabstMirror** [comment]
It's going to be up to weapon makers to include the magazine in their weapon configs.
If "magazineGroup" ever works, and they work on GL muzzles, then this will become much easier.

**Comment by headedhorseman101** [comment]
Why can't they be added to magazines[] array in the optional compatability files already in existance?

**Comment by ulteq** [comment]
They can, and I think we already did it in some cases.

**Comment by commy2** [comment]
Needs a compat pbo. Pretty simple fix that the mod makers have to do.
