### ISSUE TITLE
ACE Misc box is missing new items

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1664]
ACE3 Version: 3.1.1
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None*

**Description:**
*ACE Misc box is missing:*
* *HuntIR rounds*
* *Tacticool ladder*
* *HuntIR monitor*
* *Concertina wire*

**Steps to reproduce:**
* *Place ACE Misc box and try to get items below.*
* *They are not there*

**Where did the issue occur?**
*A possible answer might be "Multiplayer", "Singleplayer"*

**RPT log file:**
*-*

**Comment by ulteq** [comment]
The concertina wire is not an item, but I will add the rest.
