### ISSUE TITLE
ACE Tracers only work on vanilla weapons

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1666]
ACE3 Version: 3.1.1
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* @cba_a3
* @ace3
* @HLC Weapons
* @RH Weapons
* @RHS
* @R3F Weapons

**Placed ACE3 Modules:**
* *None, using optional ACE Tracers*

**Description:**
*I think title is pretty self-explanatory. For addon weapons vanilla tracers are used.*
*On the other note I must say they are very nice and FPS friendly more than vanilla ones!*

**Steps to reproduce:**
* *Use ACE Tracers pbo.*
* *Shoot vanilla weapon with tracer mag, ball tracers show up*
* *Shoot some addon weapon, vanilla tracers show up*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*-*

**Comment by ulteq** [comment]
We would need a lot of compat pbos, if we want them on non vanilla weapons as well.

**Comment by Waffle-SS** [comment]
Please make compatibility pbos, a lot of people use these weapon packs.

**Comment by jonpas** [comment]
> Please make compatibility pbos, a lot of people use these weapon packs.

Compat pbos that you can see are there as an example, mod authors themselves should add support.
