### ISSUE TITLE
Ladder issue

### ISSUE THREAD

**Issue by Dobakjang** [acemod/ACE3#1669]
add ladder to Launcher rather than backpack for inventory.

and make a option to lower the ladder, lowing ladder could use when people move from top of the building to ground.

I can see the drop option when i adjust the ladder but it's not working

---------------------

found bug, if you deploying ladder while you move forward you will get hurt or get killed

**Comment by ulteq** [comment]
> add ladder to Launcher rather than backpack for inventory

We will think about it. Another idea is to make the ladder an item which can be put inside of the backpack.

> and make a option to lower the ladder

I like that idea, I will think about ways to implement it.

> found bug, if you deploying ladder while you move forward you will get hurt or get killed

Will try to fix it.

**Comment by Khaosmatic** [comment]
I like the idea of it being visible on the back, makes a unit really distinguishable so the launcher makes sense.

Also I have noticed some problems, usually when changing the pitch of the ladder where it becomes invisible. Mainly when it is angled and able to be run on.

**Comment by esteldunedain** [comment]
I prefer it to be a backpack too.

**Comment by pastor399** [comment]
There are a few issues in the P3D that might be causing the vanishing ladder at certain angles, it happens almost all the time if you spawn a ladder backpack on the ground, you can run around and find positions it is invisible at.   If no one else is working on it, i would love to update the ladder with a improved model and some new textures.

**Comment by Khaosmatic** [comment]
It's open source I'm sure no one would say no to that Pastor!

**Comment by pastor399** [comment]
I figured that, but its also open, so if someone else was already, then why do it twice ;p

**Comment by jonpas** [comment]
> I figured that, but its also open, so if someone else was already, then why do it twice ;p

Jump on public slack and join the #models channel, there is a list of who works on what and so on.

**Comment by bux578** [comment]
>found bug, if you deploying ladder while you move forward you will get hurt or get killed

Tried it, couldn't reproduce

**Comment by Phyma** [comment]
#2174

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
