### ISSUE TITLE
Laser Pointer

### ISSUE THREAD

**Issue by dvdbrewster** [acemod/ACE3#1670]
I have laser pointer enabled (=1). in settings.  My lasers that worked in prev vers. Do not work in 3.1.1
What else turns them off?

**Comment by esteldunedain** [comment]
You need to equip day visible laser attachments from the ACE Misc. Box (they are sepparate items, we don't make all laser pointer visible cause they are usually IR only).

**Comment by dvdbrewster** [comment]
I did. They say emits visable light.  As opposed to visable light in ir mode with night Vision.
  I got them from the box.   Theres no light like they did before the update.  (mayB I can use the old pbo and bisign ?)

**Comment by dvdbrewster** [comment]
It doesn't change . I equipped with green (visible light) from ace weapons crate. No change

**Comment by PabstMirror** [comment]
Weird thing happened with privates, so `_brightness` was undefined because it was never properly passed.

In 3.1.1.1 it just throws a script error and does nothing, will be fixed next release.

**Comment by dvdbrewster** [comment]
Sayin Imn
 Not screwed up?

**Comment by Faggot16** [comment]
How do I even turn it on? THere's no obvious (or just in general) way to turn it on, and obviously not OFF because I can't seem to even turn it on in the first place.

**Comment by dvdbrewster** [comment]
ctrl+L ( or shift+L ) keybinds change the mode of the laser pointer,   then L turns it on   and  off.

**Comment by Faggot16** [comment]
Mine's in reverse. How ever the hell that happened.
