### ISSUE TITLE
MGI HUD tactical glasses addon integration

### ISSUE THREAD

**Issue by PierreMGI** [acemod/ACE3#1673]
hi, As author of MGI HUD Tactical glasses V2 ( Armaholic), I get some comments for ACE3 compatibility. Main difficulties come from your custom menu disabling native actions like put / take / chrono for explosives. My addon has also several improvements like sticking charges on vehicles, blasting doors ,making prisoners or managing group. i worked a lot for displaying hit parts of bodies or vehicles' remaining ammos, autozooming GPS, and other useful displays as zeroing/distance cursors or 3D tactical icons.
So, at this time, I wonder if you could be interested in some modules integration in your mod rather than working alone on my side. Hope we will work together soon.
Regards
Pierre MGI

**Comment by esteldunedain** [comment]
To be completely honest I don't think the HUD modifications are a good fit for ACE. Although the game is set in the near future the idea with ace was to (1) make it era agnostic (2) only include stuff that it's either currently in use, has been used in the past or is being included atm. Google Glass style interfaces don't fit that criteria as far as see, but obviously I don't have the final say about this.

As for the other features, sure. Feel free to bring them to ACE standards and make pull requests for them to be considered. Also feel free to hop into our public Slack chat for further discussion.

Regards
