### ISSUE TITLE
Indicator for "dead" players with revive enabled

### ISSUE THREAD

**Issue by ShuraDE** [acemod/ACE3#1674]
*related to medical advanced

Hi,

there is not much information about players in reviveState=true can get up without a PAK. (Bug or Feature? #1329 )
But you can bring up all vitals inclusive successfully a CPR if necessary.

It would be very nice to have a possibility to gather information about there reviveState in game to reduce the wasted time for treatment.

**Comment by GitHawk** [comment]
I can imagine a label like "Severly injured" for reviveState similar to the bleeding label in the diagnostic window. 
Or you could add another diagnostic option to the head/torso that checks the reviveState, but in my opinion the interaction menu is are already too overloaded.

**Comment by bux578** [comment]
Thank you for your request, but this a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
