### ISSUE TITLE
Remove the modifier key

### ISSUE THREAD

**Issue by Khaosmatic** [acemod/ACE3#1675]
Hi there guys, with the release of the new items in the latest update oh boy some great fun is going to be had. Something that I realized was awesome was the tactical ladder being able to just scroll to adjust the height whereas I thought it would be done in the interaction menu!

What I'm saying is, it was such easy use being able to scroll why cannot it be applied to the other rotational/adjustable placeables like explosives or the tripod. Mainly because ARMA already needs a lot of key-binds and it seems to me the modifier key cannot be bound to a lot of keys.

Would it be possible to get an option to remove the use of the modifier key?

**Comment by esteldunedain** [comment]
I'm checking the code and I agree. ACE_Modifier is currently only used in conjunction with the mouse wheel (which used not to be the case):

ACE_Dragging: lowering/raising object
ACE_Explosives: Rotating explosives
ACE_Sandbag: Rotating sandbags
ACE_Tripod: Lowering/raising tripod

So yes, I think it could be safely scraped altogether.

**Comment by SilentSpike** [comment]
:+1: I like it

**Comment by gienkov** [comment]
It should stay since tactical ladder uses modifier to rotate the ladder and mousewheel alone to adjust height of it.

**Comment by Khaosmatic** [comment]
A fair point with the tactical ladder.

**Comment by commy2** [comment]
The biggest problem with the modifier key is, that the default keybind (LCtrl) doesn't work at all.
`{ace_modifier} call ace_common_fnc_monitor`

Seems like CBA keyhandling has issues with shift / ctrl / alt as sole keybind.

**Comment by commy2** [comment]
resolved in https://github.com/acemod/ACE3/pull/2598
