### ISSUE TITLE
Using the fluid resting animation for spotting scope [Suggestion/Question]

### ISSUE THREAD

**Issue by Khaosmatic** [acemod/ACE3#1676]
So after playing around with the spotting scope I noticed you sit behind the scope when in the gunner position and it got me thinking, is it possible to use the weapon resting animation whilst prone for the user of the spotting scope?

I guess it might run into issues with turning however, but it would mean the spotter and sniper could prone and hide better then having to sit.

**Comment by esteldunedain** [comment]
Yeah, it might be possible to treat the spotting scope like a magazine-less weapon that can be rested. Of course it wouldn't be possible to place the scope on the floor anymore. If somebody makes a prototype we could evaluate which one ends up being more usefull.

**Comment by gienkov** [comment]
Right now it's treated like vehicle, well static one. And AI tend to spot vehicles faster.

**Comment by esteldunedain** [comment]
> Right now it's treated like vehicle, well static one

StaticWeapon

>  And AI tend to spot vehicles faster. 

Probably, seems like a good reason to switch

**Comment by esteldunedain** [comment]
In fact, thinking about it, it might be possible to implement both and let the user deploy it if he wants too, or use it as a rested weapon instead.

**Comment by PabstMirror** [comment]
I think we can look at tweaking the threat:
https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
>How threatening you are to unit types {Soft, Armor, Air}, respectively.
The ai for this model selects targets of opportunity, based on these values.

**Comment by Khaosmatic** [comment]
Yeah having both would be awesome!

**Comment by p1nga** [comment]
Magazines weapon would need to be in a weapon slot to work, you could do a binocular like version and gave interaction menu items to deploy it on the tripod.....you couldn't rest it though unless it was a primary weapon

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
