### ISSUE TITLE
ACE Strings are not being displayed

### ISSUE THREAD

**Issue by SuperFastBlast** [acemod/ACE3#1680]
ACE3 Version: 3.1.1
STABLE
**Mods:**
* @cba_a3
* @ace

**Placed ACE3 Modules:**
None

**Description:**
Strings for menu's and items are not loading. Not sure if its on my end or ACE.

See Screenshots for more info.

http://images.akamai.steamusercontent.com/ugc/514882136065776054/4D6215EAC8F1375D6042748604339359D44D95D6/

http://images.akamai.steamusercontent.com/ugc/514882136065775662/C1601178D48F8CB14F601F87288A4C3D2E947FCC/

**Steps to reproduce:**
Loaded up my game. Go to editor and try to spawn a module

**Where did the issue occur?**
Mulitplayer, Single player

**RPT log file:**
http://pastebin.com/hKvKr4YX

**Comment by Glowbal** [comment]
Your rtp log looks very stange. Is this a custom build? It looks like you might be running a version of ACE that got build incorrectly.

**Comment by SuperFastBlast** [comment]
Downloaded the build from armaholic. Also have used the one from the github. Same error

**Comment by SuperFastBlast** [comment]
Fixed it. Deleted my Z Folder in my arma 3 directory from previous source code builds. Issue can be closed now

**Comment by jonpas** [comment]
If you have ACE3 development environment setup then you must run `-noFilePatching` when running non-dev build.
