### ISSUE TITLE
Make.py fails to buld ace_fonts after the first time. 

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#1682]
Make.py fails to restore config.cpp from backup for z\ace\addons\fonts
This issue seems to only affect z\ace\addons\fonts

Workaround: restore config.cpp and if also missing $PBOPREFIX$
Then rebuild again.

**Comment by ViperMaul** [comment]
It also fails to restore $PBOPREFIX$ from backup

**Comment by ViperMaul** [comment]
It looks to be a bug in the $NOBIN$ handling.

**Comment by jonpas** [comment]
Fast fix! :+1:
