### ISSUE TITLE
yardage pro 450

### ISSUE THREAD

**Issue by dvdbrewster** [acemod/ACE3#1685]
Looking through the 450 yardage pro  theres no numbers for distances etc.. its blank.  ( I don't use this one myself all the time.. but mayB it would be handy...   I tried the default tabbing key..  and other keys..
  No indications while looking through it.   (speaking of keys.. when I try using engine off and on  I find I must bind to the BASE kes cfg,  any Ace cfg for engine controls... doesn't controls  the engine.  
  Same with binoculars...  (agm use to bind independently..) (need logistics setup like agm soon?)

**Comment by ulteq** [comment]
The default key to operate the Yardage 450 is 'R'
