### ISSUE TITLE
IED blows up after being walked over

### ISSUE THREAD

**Issue by kripto202** [acemod/ACE3#1687]
@ACE3.1.1
@CBA_A3 1.23

Situation:
You can set the charge off when you walk over the IED even though it is not set to go off that way.

Steps to reproduce:
- place IED (any kind)
- set trigger to cell phone
- walk over IED
- boom

**Comment by CorruptedHeart** [comment]
Most likely the ammo type hasn't set the correct mineTrigger, I believe `RangeTrigger` or similar will remove this.

Multiple ammo types might need to be created to avoid any issues with other trigger types for IEDs.

**Comment by legman** [comment]
this has already been fixed in my last pull request #1440
