### ISSUE TITLE
Passenger interaction while in a crowded vehicle is choppy

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#1690]
In a loaded transport vehicle (10+ crew) interacting with the vehicle's passengers has very noticeable pauses.  It can make selecting things difficult.

collectActiveActionTree seems to be culprit, it can take 100+ms every second.

![image](https://cloud.githubusercontent.com/assets/9376747/8256697/3d679212-166e-11e5-841b-2ddf25a4c2c8.png)

**Comment by esteldunedain** [comment]
Yeah, it's currently done on the same frame for every passenger, hence the problem. Also our action trees keep growing. Ideally:

- it could be deferred somehow so the tree isn't done all at once

- the action tree itself should be evaluated to find the most expensive branches and add extra conditions to root nodes so they quit earlier

- Some actions are probably burning time while evaluating their conditions cause they are not usually cached. These need to be found and improved.
