### ISSUE TITLE
Wounds bandaged get stacked regardless of body part

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1693]
ACE3 Version: https://github.com/acemod/ACE3/commit/5887c59c05082981ad3292fff5fe47898f0a5930
Branch fixVanillaDamageEffectsShowing

**Mods:**
* https://docs.google.com/spreadsheets/d/1OTjYgUqxEnQsQBAfgwmjbThDZ3unG21H1jfGkZEwO00/edit?usp=sharing

**Placed ACE3 Modules:**
* http://pastebin.com/yMcPiZN6

**Description:**
*Video I attached below explains everything but I will try to describe it here too. So lets say you have wounded right and left leg. You bandage left and it needs stitching now. You bandage right leg and suddenly that leg doesn't need stitching. Instead, wound of that right leg jump to left leg and show up as the same type of first wound type.*
Watch video to understand what is happening, on the video I got hit on three different bodyparts, but after bandaging only one required stitching and it was showing the same wound type three times.
http://youtu.be/l_rvxc2wM24

**Steps to reproduce:**
* *Get shoot in two different body parts*
* *Bandage first bodypart, lets say its "Large avulsion" wound, it will show up as [B] Large Avulsion*
* *Bandage second bodypart, lets say its "Small puncture wound", after bandaging that bodypart will be white as it doesn't require stitching*
* *First bodypart will show "2x [B] Large avulsion", and its wrong*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
*Add a link (pastebin.com) to the client or server RPT file.*

**Comment by Glowbal** [comment]
This has nothing to do with Stitching. It is probably caused by forgetting to take the body part ID into acount and stacking the injuries on the first available bandaged injury of the same type.

**Comment by gienkov** [comment]
Yeah this, I didn't know how to name it :).

**Comment by Glowbal** [comment]
Fixed.
