### ISSUE TITLE
Concertina wire does nothing on dedicated

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1694]
ACE3 Version: 3.1.1

**Mods:**
* https://docs.google.com/spreadsheets/d/1OTjYgUqxEnQsQBAfgwmjbThDZ3unG21H1jfGkZEwO00/edit?usp=sharing

**Placed ACE3 Modules:**
* *http://pastebin.com/yMcPiZN6

**Description:**
*It doesn't damage wheels and it should I think. Doesn't damage players too.*
https://youtu.be/G5ilD3k97Q4

**Steps to reproduce:**
* *Place concertina wire and drive over it*
* *Nothing happens*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
*Add a link (pastebin.com) to the client or server RPT file.*

**Comment by PabstMirror** [comment]
I belive this will be fixed with #1867
Please reopen if it still has problems
