### ISSUE TITLE
PAK animation is very wrong

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1695]
ACE3 Version: 3.1.1

**Mods:**
* https://docs.google.com/spreadsheets/d/1OTjYgUqxEnQsQBAfgwmjbThDZ3unG21H1jfGkZEwO00/edit?usp=sharing

**Placed ACE3 Modules:**
* http://pastebin.com/yMcPiZN6

**Description:**
*PAK animation is funny:*
https://youtu.be/sRAaX08Zfaw

**Steps to reproduce:**
* *Tell somebody to give you PAK*
* *Observe animation, with arms clipping into body*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*Add a link (pastebin.com) to the client or server RPT file.*

**Comment by Glowbal** [comment]
Is this still the case? I haven't noticed anything recently.

**Comment by gienkov** [comment]
I will double check it and let you know.

**Comment by jonpas** [comment]
@gienkov what's the status on this?

**Comment by gienkov** [comment]
I didn't played for a long time so I'm not sure if it still happens.
03.04.2016 1:36 PM "jonpas" <notifications@github.com> napisał(a):
