### ISSUE TITLE
PAK and Stitch wounds are showing even if patient doesnt require them

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1698]
Those two options will show always on patient torso even when in full health.
Writing from my phone so I will fix that issue later, wanted to report this anyway so I dont forgot to do it :).

**Comment by esteldunedain** [comment]
Yeah, I agree that interactions options that don't make sense should preferably not be displayed.

**Comment by bux578** [comment]
Is this still an issue? can't reproduce
