### ISSUE TITLE
ACE Rallypoint: OPFOR and INDI Syned Units Unable to Move Rallypoint

### ISSUE THREAD

**Issue by VeZer0** [acemod/ACE3#1699]
ACE3 Version: 3.1.1

Mods:
ACE3, CBA_A3 (1.1.23.150604 RC7 Hotfix 2)

Placed ACE3 Modules:
ACE_Rallypoint

Description:
When I sync my BLUFOR player to the ACE_Rallypoint module, in the self interaction menu it will allow me to move the waypoint after 5 seconds.

However, when I reproduce it with a synced OPFOR or INDI unit, I am unable to move its respective rallypoints. I do see the option to select "Move Rallypoint". However, it does nothing when you select that action.

Steps to Reproduce:
-Place down a player OPFOR or INDI unit
-Place down a ACE_Rallypoint_East &ACE_Rallypoint_East_Base (For OPFOR) or ACE_Rallypoint_Independent & ACE_Rallypoint_Independent (INDI) Object from Units->Empty->Ace Respawn
-Sync the unit to ACE_Rallypoint Module
-Preview in editor 
-Hit your self interaction button and select move rallypoint
-Nothing Happens

Where did the issue occur?
MP & SP

**Comment by Springster999** [comment]
Hi just to let you know we are having the same problem but this issue also effects Blufor. Before 3.1.1.1 we were able to move the rally point. now we are unable to.
