### ISSUE TITLE
Laser script error

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1701]
ACE3 Version: 3.1.1

**Mods:**
* https://docs.google.com/spreadsheets/d/1OTjYgUqxEnQsQBAfgwmjbThDZ3unG21H1jfGkZEwO00/edit?pli=1#gid=0

**Placed ACE3 Modules:**
* http://pastebin.com/yMcPiZN6

**Description:**
Got RPT spam with this:
http://images.akamai.steamusercontent.com/ugc/35249157842044349/EE514632DE8B58EE4A01214A6524E9A1C9F2CFA5/

**Steps to reproduce:**
* It just happened suddenly

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
https://www.dropbox.com/s/qf2paolyaiiccbu/arma3_2015-06-20_20-06-12.rpt?dl=0

**Comment by PabstMirror** [comment]
Should be fixed with d7717448fa349cc146c0515ad707a87bcc32fd07
