### ISSUE TITLE
Speedboats hurt players very easily, often breaking legs

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1702]
ACE3 Version: 3.1.1
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
- https://docs.google.com/spreadsheets/d/1OTjYgUqxEnQsQBAfgwmjbThDZ3unG21H1jfGkZEwO00/edit?pli=1#gid=0

**Placed ACE3 Modules:**
- http://pastebin.com/yMcPiZN6

**Description:**
_You know that it is very hard to do a full stop when driving a boat. Since last week we have played two missions that were using armed boats (that one with GL and Minigun) for sea insertion. In those two missions there was always at least few wounded, hurt when they jumped off boat. Boat itself was almost fully stopped but still moving forward._

**Steps to reproduce:**
- _Drive a boat_
- _Slow down to almost full stop, very hard to do so you will propably have your boat still moving forward or backwards_
- _Exit from passenger seat_
- _There is very big chance you will be hurt due to collision at extreme low speed with that boat_

**Where did the issue occur?**
_"Multiplayer"_

**RPT log file:**
_Add a link (pastebin.com) to the client or server RPT file._

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
