### ISSUE TITLE
DLL files with wrong version

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1703]
ACE3 Version: 3.1.1

**Mods:**
* https://docs.google.com/spreadsheets/d/1OTjYgUqxEnQsQBAfgwmjbThDZ3unG21H1jfGkZEwO00/edit?pli=1#gid=0

**Placed ACE3 Modules:**
* http://pastebin.com/yMcPiZN6

**Description:**
*Today our server crashed once and this below was included in RPT. We use newest 3.1.1 ACE on clients and server.*

**Steps to reproduce:**
* *-*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
```
Extensions:

  ace_clipboard (C:\TCAFiles\Users\accmisja\A3\@ACE3\ace_clipboard.dll) [3.0.1.0] [3.0.1.0]

  ace_fcs (C:\TCAFiles\Users\accmisja\A3\@ACE3\ace_fcs.dll) [3.0.1.0] [3.0.1.0]

  asmdll (.\asmdll.dll) [] []

  ace_advanced_ballistics (C:\TCAFiles\Users\accmisja\A3\@ACE3\ace_advanced_ballistics.dll) [3.0.1.0] [3.0.1.0]

  ace_medical (C:\TCAFiles\Users\accmisja\A3\@ACE3\ace_medical.dll) [3.0.1.0] [3.0.1.0]

  ace_break_line (C:\TCAFiles\Users\accmisja\A3\@ACE3\ace_break_line.dll) [3.0.1.0] [3.0.1.0]
```

**Comment by esteldunedain** [comment]
The dll version numbers on the 3.1.1 release are wrong (they say 3.0.1), but that doesn't create any real problem.
