### ISSUE TITLE
Weapon options in ACE controls already present in Arma 3

### ISSUE THREAD

**Issue by WadeDP** [acemod/ACE3#1707]
ACE3 Version: 3.1.1
Stable

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None.

**Description:**
Ace 3 weapon switching controls are already present in Arma 3. Added in the Marksman update.
Arma 3 weapon controls: http://i.gyazo.com/6ef830dabb468ef6be217333c8793b5a.png
Ace 3 weapon controls: http://gyazo.com/76424f62598e2474a908593c278a2dae
**Steps to reproduce:**
Configure>controls>weapons
Configure>controls>configure addons> Ace 3 Weapons

**Where did the issue occur?**
Menu

**RPT log file:**
N/A

**Comment by PabstMirror** [comment]
See #421 and #762

Our keys work a little differently than vanilla (rifle doesn't select GL)
They are unbound by default.
