### ISSUE TITLE
Weather propagation breaks wind

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#1708]
ACE3 Version: 3.1.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* ACE Weather

**Description:**
When setting ACE Weather to No (every other setting of the weather to yes), every few seconds when the value gets a adjusted it goes back to 0m/s before going to the new value. For example, if the wind strength is at 2.4m/s then it goes down to 0 and back up to 2.8m/s.
You can test this by executing the following code in the debug console:
`0 spawn {while {true} do {hintSilent str (vectorMagnitude wind); sleep 0.1}};`
I have also recorded it on video for better illustration: http://a.loveisover.me/rdpuij.webm
This does not happen with ACE Weather set to yes or weather propagation set to no. It also doesn't happen every time from my observations.

**Steps to reproduce:**
* Place down ACE Weather module
* Set ACE Weather to no
* Execute `0 spawn {while {true} do {hintSilent str (vectorMagnitude wind); sleep 0.1}};`

**Where did the issue occur?**
Editor & dedicated

**RPT log file:**
None

**Comment by ulteq** [comment]
What was your `serverUpdateInterval` weather module setting?

**Comment by BaerMitUmlaut** [comment]
`serverUpdateInterval` was left at the default 60. No setting was changed apart from ACE Weather (`useACEWeather`).

**Comment by Kilo1-1** [comment]
I've also seen this happen.  I also have seen it happen where there is heavy wind yet the Kestrel says the wind is 2.4m/s or 2.5m/s when the wind is much stronger than that.  I have also seen it where the wind gets up to 70m/s or 80m/s.  This is with the same settings that is in the OP.

It just seems the wind sync is really random at times.

**Comment by brokenhands** [comment]
I had major wind issues on my mission that I recently resolved. The map is Chernarus and we were noting winds at the freeway speeds mentioned. The easiest test for us detonating a vehicle and watching the flames burn parallel to the ground chasing the wind. 

The fix for was removing an ALiVE weather module.

**Comment by Kilo1-1** [comment]
I thought it was the ALIVE weather module too because it happened when we used that module in our missions so we have since not used it  However the issue still comes up when that module isn't used.  I am not sure what is causing it.

**Comment by ViperMaul** [comment]
Status?

**Comment by PabstMirror** [comment]
@BaerMitUmlaut 
Seems to be a known issue with `setWind` and having wind set to "Auto" in the editor.
http://feedback.arma3.com/view.php?id=19025

Turn wind off auto and wind should stay at the value we set it to.
