### ISSUE TITLE
ACE_Comanche_Test snuck back

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#1709]
ACE3 Version: 3.1.1.1

**Mods:**
* `@cba_a3`
* `@ace3`

**Placed ACE3 Modules:**
* None

**Description:**
`ACE_Comanche_Test` shows up in Zeus... again. Only in 3.1.1 Release version, on latest master it does not. This was already fixed before 3.0.0 in #943 but it's back now. Weird is it doesn't show on latest master branch either and there was nothing changed since release.

**Steps to reproduce:**
* Open Zeus, navigate to Empty -> NATO -> Air
* See `ACE_Comanche_Test`

**Where did the issue occur?**
* Singleplayer - Editor
* Multiplayer - Dedicated

**RPT log file:**
N/A

**Comment by PabstMirror** [comment]
Even though `units[] = {};` in our code,
Something in our full make tool chain adds `units[] = {"ACE_Comanche_Test"};`
So it only shows up on full builds.

Set `scopeCurator` to 0 so, it should be gone.

**Comment by jonpas** [comment]
It's probably pboProject itself that adds the missing `units[]`. Cheers!
