### ISSUE TITLE
Fragmentaion don't work in ACE 3.1.1.1

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#1710]
ACE3 Version: 3.1.1.1

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
None

Description:
Grenades don't spawn fragments after explosion. 

Steps to reproduce:
Throw fragmentation grenade, wait till explosion - there are no fragments

Where did the issue occur?
Tested in editor

RPT log file:
N/A

**Comment by PabstMirror** [comment]
Should be fixed with #1686
