### ISSUE TITLE
Screen get's whitewashed/gamma increase when in helicopters

### ISSUE THREAD

**Issue by Bolt404** [acemod/ACE3#1712]
ACE3 Version: 3.1.1.1
Stable

Mods:
@cba_a3
@TFR
@ace3
@ALiVE
@RHSUSAF
Excluding various maps

Placed ACE3 Modules:
http://pastebin.com/7ue3XikZ

Description:
Helicopter Pilots and crew are experiencing an increase in their screen gamma/brightness making everything very white/bright that then gets worse the longer time they spend in the helicopter http://imgur.com/a/0HzB0

The issue appears from starting the engine and only disappears when shutting the engine off, it's also worth mentioning that going into your settings and messing with your gamma will for a very short while reset/fix it.

Steps to reproduce:
Unknown

Where did the issue occur?
From entering a helicopter with its engine on

RPT log file:
Unavailable

**Comment by CorruptedHeart** [comment]
This is most likely caused by Goggles. But it should never occur within a vehicle.

Also the following should probably be added to the compat pbos or by RHS guys to the pilot helmets. https://github.com/acemod/ACE3/blob/master/addons/goggles/config.cpp#L232

**Comment by alganthe** [comment]
Are you SURE pilots and co-pilots are affected ? only people in a FFV / turret seat should be affected.

**Comment by Glowbal** [comment]
It is most likely a bug with the helicopters in use. I will look into it.
