### ISSUE TITLE
ace_zeus black screen on dedicated server

### ISSUE THREAD

**Issue by SilentSpike** [acemod/ACE3#1713]
It seems the changes made by ace_zeus cause the screen to go black when a player uses one of the zeus slots in the vanilla zeus mission on a dedicated server.

TODO:
- [x] Narrow down the problem circumstances. Should look into:
  - ~~Does it only occur when using the virtual zeus units (sideLogic)?~~
  - ~~Does it only occur when zeus interface is forced?~~
- [x] Fix the problem

**Comment by SilentSpike** [comment]
It seems that the edits made to the module function are somehow stopping it from correctly initializing only on dedicated servers. The screen going black is just a side effect of having the interface forced.

Time to look through the code.

**Comment by SilentSpike** [comment]
Potential causes I can think of:
- ACE settings variables are not defined before the function runs
- function `EFUNC(common,execNextFrame)` does not work or is not defined on dedicated server

Time to test both out.

**Comment by SilentSpike** [comment]
Okay, neither of those things is the issue, in fact I commented out all the ACE changes and it still didn't initialize.

Which means the problem is possibly just part of the code that doesn't run when the settings are false is required somehow (though I'd have no idea how).

Testing now.

**Comment by SilentSpike** [comment]
Okay, I set the setting to true and it still didn't initialize. :fu:

**Comment by SilentSpike** [comment]
Figured it out, someone must have changed the vanilla code to use `ACE_Time` instead of `time` at one point, which somehow broke the whole module.

**Comment by NemesisRE** [comment]
It seems that 3.2.0 still needs some time, would it be possible to release 3.1.2 with this fix?

**Comment by SilentSpike** [comment]
3.2.0 actually releases today with this fix included :+1:

**Comment by NemesisRE** [comment]
:+1:
