### ISSUE TITLE
Laser target doesn't update position

### ISSUE THREAD

**Issue by Waffle-SS** [acemod/ACE3#1715]
ACE3 Version: 3.1.2

**Mods:**
* @cba_a3
* @ace3

**Description:**
The laser target entity that all laser designators create doesn't update position.  When you first lase, the target is created and can be locked onto, but it doesn't change its position unless you turn the laser off and on again.

**Where did the issue occur?**
SP/MP

**RPT log file:**
No config/script errors

**Comment by ArcanumSK** [comment]
I can relate, still present and annoying.

**Comment by bux578** [comment]
![image](https://cloud.githubusercontent.com/assets/1235520/9412405/cbe310b8-482b-11e5-9ca2-483ad8813d1a.png)

**Comment by ArcanumSK** [comment]
That is exactly my point....
