### ISSUE TITLE
New Backpack Slots,AutoRun,VHF Homeing device

### ISSUE THREAD

**Issue by John2020** [acemod/ACE3#1717]
HI!  Checked out Asors Gear Selector and came across an item that could fit nicely into this addon;
You could use a feature they called "Spare ammo"-you can pack additional ammo apart from a full Vest .
And  another thing:Toggle a Auto Run Feature would come in Nice!   Could it be possible to add 1+1+1 rifle to the guy?One in the backpack,+2 on each side?  I would like it to be possible to add a rolled up tent ,or rifle mat to lay on on a mission.
Is this maybe a feature :Adding a ADF Homing Instrument to helicopters,to find people in dense forrests more esely?

**Comment by KoffeinFlummi** [comment]
#414
