### ISSUE TITLE
Claymore Mines and other mines placement

### ISSUE THREAD

**Issue by John2020** [acemod/ACE3#1718]
If you want to go on a stealth mission and keep you`re whereabouts secret,you will want to keep any mines attached to cars and so on out of sight ;I suggest that thera are at least one place per vehicle type where you can place it invisably onto it,Not halfway throug the bonnet.
I would suggest that this will work for the Slam-mine.We can ste it to a particualr direction,if we only want to disable something.
I also want these red triangles GONE! And the AI warning of them .I don`t want them to notice them.
I would like the trip-wire ones to be without the line-instead I want them to have a laser-gate.Just cross the-line-of -sight .Can be placed anywhere in the room.

**Comment by SilentSpike** [comment]
Feature requests go here pleaseL #414
