### ISSUE TITLE
CheckPBO doesn't kick if player joins with an ACE3 .pbo that was removed from server

### ISSUE THREAD

**Issue by BullHorn7** [acemod/ACE3#1722]
Summoning @jonpas 

ACE3 Version: 3.1.1.1 official

**Mods:**
* @cba_a3
* @ace3
* EVERYTHING else :)

**Placed ACE3 Modules:**
* None

**Description:**
We had CheckPBO set to Warn Permanently and it seemed to work very well so we decided to switch to Kick.
Later we thought we noticed an issue with ACE_protection.pbo so we removed it from the server and continued testing. A few minutes later a new player that didn't know about the removal of the protection.pbo joined with that .pbo in his modpack but he wasn't kicked, nor did he receive any warning.

**Steps to reproduce:**
* Enable CheckPBO and set it to kick
* Remove some ACE .pbos from the server's modlist
* Join the server without removing the ACE .pbos from the client

**Where did the issue occur?**
* Multiplayer

**RPT log file:**
* Client: http://pastebin.com/Sfz4raw1
* Don't have access to server, sorry.

**Comment by jonpas** [comment]
https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_moduleCheckPBOs.sqf#L23 is not even showing up in the RPT, investigating.

**Comment by jonpas** [comment]
This is caused by https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_checkFiles.sqf

It will only check version and not if the file is actually missing.

**Comment by SilentSpike** [comment]
I'm not sure there's a way to solve this without adding in a hardcoded list of ACE3 PBOs somewhere (which isn't desirable).

Shouldn't ARMA itself handle people connecting with addons that aren't running on the server?

**Comment by jonpas** [comment]
> I'm not sure there's a way to solve this without adding in a hardcoded list of ACE3 PBOs somewhere (which isn't desirable).

No, it should just compare what's on the server and what's on the client, server is the base of comparing, client must be equal to server.

> Shouldn't ARMA itself handle people connecting with addons that aren't running on the server?

No Arma doesn't handle that.

On another thought, CheckPBO should check all PBOs, if they are same on server and connecting client, not sure why it doesn't for ACE's.

**Comment by SilentSpike** [comment]
> No, it should just compare what's on the server and what's on the client, server is the base of comparing, client must be equal to server.

Well that's my point. If a PBO isn't on the server then you can't check if it's on the server using the PBOs that are on the server :stuck_out_tongue:

**Comment by SilentSpike** [comment]
Though, I suppose you could also send out the array of ace PBOs on the server and make sure the client has the same array.

**Comment by CorruptedHeart** [comment]
Technically you wouldn't want the client to do the verification. By sending the list to the client, that just screams security risk.

**Comment by SilentSpike** [comment]
It's already verifying that the version numbers match

**Comment by SilentSpike** [comment]
Besides, either way data is exchanging between client and server. If you were to send the client data to the server what's to stop the client from sending false data?

**Comment by jonpas** [comment]
CheckPBO is going to get a rewrite anyways (it needs one badly), maybe it's a good time to figure out the best flow for verifying now?

**Comment by esteldunedain** [comment]
Fixed in #1732 (once it's merged)
