### ISSUE TITLE
Ace 3.1.1 and MK6-Flares (Flares burntime increased, hand flares brightness reduced (#1477))

### ISSUE THREAD

**Issue by Halifax007** [acemod/ACE3#1730]
Hello,
I did a lot of tests with the MK6-Flares and the Ace 3.1.1. The burntime of the flares is now really better. I think the "intensity = 80000" in "ace_grenades.pbo / CfgAmmo.hpp" should be a little bit more. I say this, because I saw this kind of flares at the OP in the real army -- it was a 81mm mortar.

The issue is, that the other players can't see any flares if they are close to the target and far away from the mortar i.e. the distance is 1500 meters. If the players are close to the "flares-shutting mortar", then they can see the flares.

Does anybody else confirm this issue?

Tested with CBA V1.1.23 and Ace 3.1.1

Thanx
Halifax007

**Comment by austinjames314** [comment]
I've had issues with some players not being able to see the illum rounds, but can't confirm the details regarding players locations & distance etc. If I can confirm that part of it'll post again.

**Comment by alganthe** [comment]
I didn't touched the intensity, I guess people having that issue are the ones who have dynamic lighting on low.

**Comment by austinjames314** [comment]
For me the same players that couldn't see the Mk6 Mortar flares, would later be able to see them when we all moved around. I don't have any more details unfortunately, but it didn't seem to be a player setting problem.

**Comment by esteldunedain** [comment]
This is an issue on the engine itself. I don't think we can do anything about it.
