### ISSUE TITLE
Disabling Squad Command Keys

### ISSUE THREAD

**Issue by MrSaltyLemon** [acemod/ACE3#1731]
A system that would get rid of the sometimes annoying popups of the squad command menu especially when you use the keys for your weapon holstering and weapon drawing and what other ACE keys uses these keys.

If it was to be a similar system to that AGM where you can enable and disable it in the ACE Options.

Cheers.

**Comment by BaerMitUmlaut** [comment]
You can deactivate them in your controls, why should ACE do that for you?
![2015-06-23_00001](https://cloud.githubusercontent.com/assets/9693842/8305736/43af9538-19b2-11e5-988f-687098ff759d.jpg)
