### ISSUE TITLE
Placing explosives inside walls is possible

### ISSUE THREAD

**Issue by BullHorn7** [acemod/ACE3#1734]
This video was recorded in 3.0.1 and I made sure to test it again in 3.1.1.1 before opening the report.

* Placing explosives is possible inside walls so the enemy has no chance of ever finding it. 
* Sometimes explosives that are set inside a wall cannot be interacted with. 
* Explosives with fall over on their side when played inside a building

https://www.youtube.com/watch?v=82A6S2zhxCw (first few minutes)

**Comment by ulteq** [comment]
Probably not so easy to fix, but worth a try.

**Comment by esteldunedain** [comment]
This will be solved once the technique at #1739 is applied to explosives.
