### ISSUE TITLE
Helicopter tail rotors don't 'exactly' kill you

### ISSUE THREAD

**Issue by BullHorn7** [acemod/ACE3#1735]
This was tested in 3.0.1. I made sure to test again in 3.1.1.1 and it's even worse. The player remains alive and can move and hear others but nobody else can hear him.

https://youtu.be/82A6S2zhxCw?t=7m20s

**Comment by HTSean** [comment]
I just tried this with a friend, yeah this is definitely a thing. Can't say I didn't laugh my ass off though

**Comment by ViperMaul** [comment]
Apparently this happens in vanilla with no mods as well. 
> the thing is that it's BI related
if an animation doesn't have a transition at the end  you're fucked, ragdolls included
yep
you flop on the ground and stay there
sometimes the ragdoll end and you recover
https://ace3public.slack.com/archives/public/p1435236655006806

**Comment by BullHorn7** [comment]
Alganthe was talking about Fix Headbug, how are the two related?

**Comment by bux578** [comment]
In vanilla you simply die.

**Comment by alganthe** [comment]
depends, in vanilla if you're desyncing you kill the rotor and flop on the ground or you die.

**Comment by bux578** [comment]
In 3.2.0 a tail rotor outright kills me.

**Comment by bux578** [comment]
If this happens again open a new ticket please.
