### ISSUE TITLE
Map can't be scrolled through or zoomed while player is moving

### ISSUE THREAD

**Issue by BullHorn7** [acemod/ACE3#1736]
This video is from 3.0.1 but tested and confirmed in 3.1.1.1 too. In-map FPS drops to 5-20 when moving as well.

https://youtu.be/82A6S2zhxCw?t=8m52s

Steps to reproduce:
* Open map
* Start moving
* Attempt to zoom in/out and drag the map to any other side

**Comment by esteldunedain** [comment]
> Attempt to zoom in/out and drag the map to any other side

It's a known issue, which is not fixable with mapShake on. We can discuss if map shake should be enabled by default or not though

**Comment by Tenga** [comment]
Map shake also makes it extremely difficult to manipulate the map when you are swimming but not moving. 

Sure, you can probably argue realism, but it's a usability nightmare. You have no feedback as to what's going on as the on sea movements are very minor and the map shake can't be seem, the map just randomly locks up or makes sudden jumps.

This can probably be solved by introducing (or increasing, if it already exists) the minimum amount movement needed for the map shake to trigger.

**Comment by jonpas** [comment]
Or add an exception `isNotSwimming` and don't move it in that case.

**Comment by Tenga** [comment]
@jonpas Wouldn't that prevent it from shaking at all if you're swimming, even when you **are** moving? I'd still shake while swimming and moving, just not when you're still (waves cause micro movements, hence the problem).

**Comment by jonpas** [comment]
Yes it would, but on that note I'd prefer to totally prevent opening it when swimming. How can you look at the map when swimming? It's already almost impossible when just being still in the water (not to mention you'd get water all over the map).

**Comment by Tenga** [comment]
I'm not sure if there are things like laminated / waterproof maps and map cases for such use. 

Considering waterproof cases for gadgets already exist, I don't think it's a stretch to assume something similar exists for maps.

**Comment by jonpas** [comment]
Yep, I am of same thoughts.

**Comment by SilentSpike** [comment]
>I'm not sure if there are things like laminated / waterproof maps and map cases for such use.

Yep, they definitely exist.

**Comment by esteldunedain** [comment]
Fixed by the wonderfull @PabstMirror

**Comment by jonpas** [comment]
:+1:

**Comment by brainslush** [comment]
I actually thought this was a feature! Maybe make a module out of it?
