### ISSUE TITLE
Invisible player

### ISSUE THREAD

**Issue by BullHorn7** [acemod/ACE3#1737]
Never seen such an issue before. Switched from AGM and TFAR to ACE3.1.1.1 and ACRE2 and the issue appeared randomly just with this player.

https://www.youtube.com/watch?v=cQ87Tb1QFpQ

RPT was lost but here's an RPT from a different session with an identical modpack.

http://pastebin.com/Wy4zm7aR

**Comment by PabstMirror** [comment]
Really not much to go on.
We only use `hideobject` in 5 places and none seem like they would cause problems like this.

I feel like this might be a missing modpack / uniform issue.  If you can find a way to reproduce with just CBA/ACE please let us know.

**Comment by BullHorn7** [comment]
I noticed many Tryk errors in the RPT and his face-wear was part of Tryk, afaik. I'll make sure to tell him to remove the facewear next time too.

**Comment by Tenga** [comment]
We had similar on a 4 man coop a few nights ago affecting one of the players. The player affected and 2 others saw this happening and one player could see him normally at all times. Everyone could see his IR laser.

The player who could see him normally could use ACE interaction on him, others for whom he popped in and out of view, could not interact with him even when he was visible to them.

We did use additional mods besides ACE/CBA combo, but whatever Tryk is, it wasn't in our modpack.

The issue didn't start occurring until sometime mid mission, 45 minutes in maybe.

**Comment by Legolasindar** [comment]
In my community some times people are invisible (3 or 4 times in months), and need reenter for fix this. I not know if is because ACE3 or not, but this is own experience.

**Comment by bux578** [comment]
Still a problem?

**Comment by Tenga** [comment]
@bux578 Haven't played in a while, so I don't have any info. Maybe others can chime in.

**Comment by Legolasindar** [comment]
From my last message not see this problem again.

**Comment by commy2** [comment]
Could be either

```
21:21:38 Conflicting addon TRYK_Uniform in 'Zabb\', previous definition in 'tryk_unit\'
21:21:38 Conflicting addon TRYK_Uniform in 'Zara\', previous definition in 'tryk_unit\'
```

or

```
21:21:41 Updating base class Man->Civilian, by rds_ag_comp\africa\civilian\config.bin/CfgVehicles/Civilian_F/
```

In any case, this is most likely not caused by ACE.
