### ISSUE TITLE
Loading captive into RHS UAZ glitch

### ISSUE THREAD

**Issue by captainblaffer** [acemod/ACE3#1742]
ACE3 Version: 3.1.1 stable

**Mods:**
* @cba_a3
* @ace3
* @RHSAFRF
* @RHSUSF

**Placed ACE3 Modules:**
none

**Description:**
Loading captive into any vehicle spot which is FFV (fire from vehicle)
Observe the captive standing upright in the seat.

First observed on the RHS UAZ. The UAZ door would also constantly open & close.

**Steps to reproduce:**
Zip tie a civilian
Escort him
Load him into any vehicle seat which is FFV, e.g. RHS UAZ, AAF Wildcat, or FIA offroad.

**Where did the issue occur?**
"Multiplayer"

**RPT log file:**
n/a

**Comment by jonpas** [comment]
Please follow http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by ViperMaul** [comment]
I wonder if this only happens to RHS vehicles.

**Comment by captainblaffer** [comment]
I tried some A3 default vehicles like HUNTER, GHOSTHAWK. didn't happen there. I did not test all vehicles though. May be worth checking OFFROAD and QUADBIKE

**Comment by jonpas** [comment]
Got a feeling this is caused due to vehicle (door) animations RHS uses for getting in and out, can you maybe try vanilla Hellcat/Wildcat?

**Comment by bux578** [comment]
@captainblaffer Does this still happen?

**Comment by captainblaffer** [comment]
Still happens on ACE 3.2.0

I've tested some more, all FFV vehicle positions are affected. E.g. FIA offroad, AAF Wildcat.
