### ISSUE TITLE
ACE interact on vehicles from outside confusion

### ISSUE THREAD

**Issue by captainblaffer** [acemod/ACE3#1743]
ACE3 Version: ACE 3.1.1 stable

**Mods:**
- @cba_a3
- @ace3

**Placed ACE3 Modules:**
none

**Description:**
Issue occurs when standing outside, facing a vehicle, wanting to interact with vehicle. e.g. loading a captive

The interaction button on the vehicle is a single small point located 'randomly' somewhere in the vehicle, 3d space.

The player has to often scan the whole vehicle for this point in order to interact. Especially with large vehicles it can be difficult to find. I've had players come to me believing it's not possible to interact with vehicles at all, since they didn't notice the interact point.

It'd be great to see this interaction be improved. I liked how it worked in AGM much more: Aim anywhere at the vehicle, interaction menu appears.

Thanks!

**Steps to reproduce:**
n/a

**Where did the issue occur?**
"Multiplayer"

**RPT log file:**
n/a

**Comment by captainblaffer** [comment]
Relevant issue: The interaction spot on the FIA Offroad seems to be completely missing. ACE 3.2.0

**Comment by jonpas** [comment]
@captainblaffer #1746 - CBA issue, will be fixed in next CBA update AFAIK

**Comment by PabstMirror** [comment]
#2296

**Comment by captainblaffer** [comment]
@PabstMirror  
That looks like the perfect solution. Hope it will be implemented. Thank you!

**Comment by Salluci** [comment]
Addressed by #3342?
