### ISSUE TITLE
Q: causing damage to a specific body part through scripting

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#1744]
I'm looking for the scripting commands and variables to cause damage/bleeding to a specific body part.

I just want to cause damage for example to the left leg via scripting.

**Comment by xJenny99x** [comment]
Figured it out eventually...


			_selections = [
				"HitHead",
				"HitBody",
				"HitLeftArm",
				"HitRightArm",
				"HitLeftLeg",
				"HitRightLeg"
			];
			_hitpoint = _selections call BIS_fnc_selectRandom;
			[_lockedTarget,_hitpoint,0.3] call ace_medical_fnc_setHitPointDamage;

**Comment by Glowbal** [comment]
That works for basic medical only.

There is no public function/API for doing this for advanced medical yet.
