### ISSUE TITLE
Offroads interaction not working

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#1746]
ACE3 Version: 3.1.2.0 5e38ba9b2087c643e3f0dc17afebda524a9d1fda

**Mods:**
* `@cba_a3`
* `@ace3`

**Placed ACE3 Modules:**
* None

**Description:**
Interaction menus on Offroads doesn't work. Possibly a bug in CBA's XEH?

**Steps to reproduce:**
* Spawn an Offroad
* Go into it, see that not even the vehicle icon shows up on interaction
* Add some passengers to verify the following does not show: https://github.com/acemod/ACE3/blob/master/addons/interaction/CfgVehicles.hpp#L409-L414

**Where did the issue occur?**
Singleplayer - Editor

**RPT log file:**
N/A

**Comment by PabstMirror** [comment]
Issue is with CBA's XEH not firing
I belive they have it fixed in dev (https://github.com/CBATeam/CBA_A3/commit/fa05aac8c37c5bc8606e3906de7cc0a91444aad7).

In the meantime:
```
WORKAROUND: The latest CBA RC7 Hotfix 2, v1.1.23 has an optional PBO that you can activate to help resolve these situations. 
1. Move the cba_enable_auto_xeh.pbo and its signature file from the CBA optional folder to the CBA Addons folder
2. Restart Arma
```

**Comment by jonpas** [comment]
I thought it was that. Deserves `CBA's fault` though. :grin:
