### ISSUE TITLE
Advanced Medic: Option to allow blood transfusion for non medics 

### ISSUE THREAD

**Issue by Meiestrix** [acemod/ACE3#1750]
ACE3 Version: v3.1.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
Medical Settings
Advanced Medical Settings

**Description:**
It would be nice if you could add a option in the advanced settings where you can enable, that non medics are allowed to use blood transfusions / saline, maybe with a big punishment. (For example 4 times longer than a medic needs). When you play with a smal group of players and your only medic needs blood / saline you cant continue your mission.

**Where did the issue occur?**
 "Multiplayer"

**Comment by Meiestrix** [comment]
Sorry forgot to post this in the feature request thread.
I dont know how to delete a post.

**Comment by alganthe** [comment]
no need to delete it, just close it

**Comment by SilentSpike** [comment]
:+1:
