### ISSUE TITLE
Laser pointer not working

### ISSUE THREAD

**Issue by TheEventHorizon** [acemod/ACE3#1751]
The visible laser mode of the IR Laser pointer does not work. There is no visible laser see when activated, i tested this in both the Day and night. However; the IR laser works fine.

**Comment by alganthe** [comment]
use [this form] (http://ace3mod.com/wiki/user/how-to-report-an-issue.html) 
and that's a known issue, see https://github.com/acemod/ACE3/issues/1670

**Comment by PabstMirror** [comment]
Fixed on dev via d7717448fa349cc146c0515ad707a87bcc32fd07
Should be in next release.
