### ISSUE TITLE
advanced ballistics scope adjustment is not functioning.

### ISSUE THREAD

**Issue by df223cwo3** [acemod/ACE3#1756]
ACE3 Version: 3.1.1.1  stable

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
ace advanced ballistics: ballistics = yes   sniper = yes 
ace weather
ace wind defection

**Description:**
the scope turret adjustments (mil clicks) appears to not be working with any of the high power "Sniper" optics. Only the vanilla scope zeroing is active. 100, 200, 300, .....800, 900, ect....  and there is no windage adjustment at all.  This is true for vanilla, marksman DLC and ACE scopes. 

Even the key bindings for minor and major adjustments to elevation and windage under the ESC key / configure / controls / configure addons / ace // are not loaded up.     

**Steps to reproduce:**
equip any long range rifle, attach a long range "HIGH POWER' scope. Adj the scope windage and elevation.  only the elevation works. and then only by 'vanilla' increments. this happens in  multiplayer and editor preview.

**Where did the issue occur?**
Multiplayer custom missions on a dedicated server and new mission in editor preview. 

df223cwo3.rpt =  http://pastebin.com/embed_js.php?i=p4iEpfgp

**Comment by bux578** [comment]
I can't reproduce this at all. Scope adjustments work perfectly fine for me. Please check if you have ACE3 installed correctly.

**Comment by df223cwo3** [comment]
pulling ACE 3.1.1.1 from a custom repo via arma3sync. after a clean install from BIS/mods/ace3 i now have a good copy of ace3.1.1.1  The issue i was having must be in our repo version. i will make sure that our repo gets changed. thank you for the time and the assistance.

**Comment by bellofello** [comment]
Hello, I know this is super old, but I am having the exact same issue. It was working fine for me at first (0.1 mil clicks with PG up/dn). 

I went into the configure add-on options menu, enabled advanced ballistics, and the "overwrite client"/"server" boxes. 

Now it is doing vanilla zeroing with PG UP/DN, and no response from the minor/major scope adjustment keybinds
