### ISSUE TITLE
Unable to start most missions

### ISSUE THREAD

**Issue by jaritt** [acemod/ACE3#1758]
Hey guys, I ran into some errors while installing ACE3. Server starts up normal but once you want to start a mission it stops loading and brings you back to the mission selection screen. ACE is installed alongside with CBA and Mission Control Center (MCC). However if only those two are enabled it works fine. The full console output can be seen here: http://pastebin.com/YxYdzy3w

However I get these lines several times (object and file name change obviously):

12:02:27 Warning Message: Script x\cba\addons\xeh\init_pre.sqf not found

12:02:34 Warning Message: No entry 'bin\config.bin/CfgPatches.cba_xeh_a3'.

12:02:34 Creation of object B Alpha 3-2 failed, state LOGGED IN
12:02:34 Creation of object B Alpha 3-2:<Empty main subgroup> failed, state LOGGED IN
12:02:34 Client: Nonnetwork object 819c36a0.
12:02:34 Client: Nonnetwork object 81aab180.

All solution for this error that I found where mission related and caused by wrong mission design. This error however also comes up with the ACE testing map included in the mod and several other maps that came this the game itself.

**Comment by jonpas** [comment]
RPT is incomplete.

**Comment by alganthe** [comment]
from the RPT log
``` 12:02:34 "MCC: 0 iniDB isn't running. Can't access role selection"```

**Comment by PabstMirror** [comment]
`Warning Message: Script x\cba\addons\xeh\init_pre.sqf not found`
It sounds like you are missing something in CBA
Try deleteing @CBA folder and reinstalling the most recent version:
https://github.com/CBATeam/CBA_A3/releases/latest

Try that and if still having problem please post the full RPT.

**Comment by jaritt** [comment]
The current version of CBA doesnt include the requested file anywhere in the archive. 
CBA pulled from this link: http://www.armaholic.com/page.php?id=18767
Full log: http://pastebin.com/a5CJzsWc

**Comment by PabstMirror** [comment]
`@CBD_A3 |              @CBD_A3 |      false |            NOT FOUND`

Check your launch parameters, looks like you are trying to load "@CBD_A3" instead of "@CBA_A3"

**Comment by jaritt** [comment]
Triple checked everything and then something like is happened. Sorry for wasting your time guys.
