### ISSUE TITLE
Unable to Arm Charges While Underwater

### ISSUE THREAD

**Issue by callensm** [acemod/ACE3#1766]
ACE3 Version: 3.1.1
**Stable**

**Mods:**
@cba_a3
@ace3

**Placed ACE3 Modules:**
None.

**Description:**
While playing as any unit holding ACE compatible explosives and underwater, the user is able to place an explosive charge while underwater; however, the option to arm it via ACE interaction is no longer available. It only becomes available again if the charge is within range and the user has surfaced from the water.
![arma3 2015-06-30 12-23-13-79](https://cloud.githubusercontent.com/assets/13121516/8435986/d328a5fe-1f22-11e5-935b-68c50479d4cf.jpg)

**Steps to reproduce:**
1. Make new mission on any map with swimable water.
2. Player as Explosive Specialist (Diver) and place empty boat in the water.
3. Swim under/next to the boat and place explosive on it from underwater via ACE interaction menu.
4. Via ACE interaction menu with the explosive charge, tried to arm it.
5. Interaction options with the charge should not be available while underwater.

**Where did the issue occur?**
While testing a mission.

**RPT log file:**
N/A

**Comment by jonpas** [comment]
Fixed in 474e69430912d546be262d9dea2448e1eba0f8b7, will be in next release.
