### ISSUE TITLE
Explosives can be activated before even being placed

### ISSUE THREAD

**Issue by Tuxe99** [acemod/ACE3#1777]
It's about the M112 and probably all the other explosives.
You can do this bug only with a partner.

If you pick up a explosive like a M112 and select it in your menu the bomb will appear infront of you.
A partner can activate your bomb - your bomb will drop on the floor with his timer (example: timebomb).

The problem is... Your menu for your bomb won't dissapear but your bomb is still in front of you.
Your partner can set, thanks to your bomb infront of you, as many bombs as he wants to activate.

After that bug your menu for the bomb will block a little bit of your sight + you can't cancel your bomb anymore.

Since I know, you can only escape this bug if you reconnect to the server.

I am new on this website and you can probably tell my english is not the best, so I'm sorry if I wrote something wrong or if this bug was already reported.

Have a good day,
Tuxe

**Comment by esteldunedain** [comment]
Thanks, usually we require a certain format for bug reports (that you can find on the wiki), but this is clear enough. This will be solved once the technique at #1739 is applied to explosives, which is planned.

Thank you for you report.
