### ISSUE TITLE
Large IED doesn't damage player if standing on

### ISSUE THREAD

**Issue by JRudy** [acemod/ACE3#1780]
ACE3 Version: 3.1.2.0

Mods: 
@CBA_A3
@ACE3

While standing on the Large IED and activating it with a Cellphone, the player flies and takes no damage. 

Tested in Virtual Arsenal. 

https://youtu.be/Z7UnenooLnQ

**Comment by JRudy** [comment]
Does not occur in Multiplayer.

**Comment by esteldunedain** [comment]
Most likely you had damage disabled for being on the Virtual Arsenal. You didn't take fall damage either. I don't think it's a bug in ACE at all.
