### ISSUE TITLE
Ace Medical clashing with Vanilla Medical

### ISSUE THREAD

**Issue by Metro31stMEU** [acemod/ACE3#1784]
within the last three weeks my clan and i have experienced an issue where when hit by enemy fire we take what we call Vanilla damage it can leave us immobile or unable to fire accurately this is especially discouraging for our corpsman and our designated marksman and anyone else who doesn't want to slow walk everywhere they go.

The only fix to the problem that i have been able to come up with is to get to a medical tent,or a vehicle supported by the vanilla medical system.

**Comment by gienkov** [comment]
Its fixed already in #1692

**Comment by bux578** [comment]
Thanks for the report though :+1:
