### ISSUE TITLE
Other Mods unable to "ACE"

### ISSUE THREAD

**Issue by piggypotpie** [acemod/ACE3#1788]
Is ther e ar eason why some mods, such as R3F, PG Services, Etc, are unable to access ACE? Is this a bug or am I not laying down the correct ACE module?
Thanks

**Comment by esteldunedain** [comment]
Those mods are incompatible with CBA extended init handlers. Until the authors fix them, you can adding the optional cba_enable_auto_xeh.pbo from CBA should help.

**Comment by piggypotpie** [comment]
Thank you! Worked like a charm.
