### ISSUE TITLE
Question/Request - Limit Epi use in Basic settings

### ISSUE THREAD

**Issue by Mortified666** [acemod/ACE3#1792]
Not sure if this is a question or a feature request.

I have a mission in which I want players to be only able to be woken up next to a Huron Medical Bay. In AGM, I was able to achieve this by setting it as the Hospital. Our group uses the Basic medical settings and I can't seem to limit the use of Epi to within a distance from the bay. 

Is there a way to do this currently? Or can this feature be added with the set Medical Facility, Set Medical Vehicle and Set Medic class for Basic Medical settings to limit the use of Epi unless the parameters set in these modules are met.

Thanks in advance.

**Comment by kripto202** [comment]
I thought that epi is limited to medics or doctors in ace. In real life, injecting yourself with an epi pen is as easy as 1...2. I don't see why only medics can use them. https://www.youtube.com/watch?v=tjILFYPE3Uw

**Comment by Mortified666** [comment]
I can respect that injecting an Epi pen is easy. It is a feature that would allow the proper use of Medivac without having to use the Advanced medical system. My group has used this feature a number of times in AGM and it gives players more respect for their virtual lives. Knowing that if you go down, it could be 5 to 10 mins before you can get back into the fight. 

This changes the way that players attack situations and they are less likely to do things that would endanger them. Doesn't have to be a permanent fixture. I would just like the option to be available without having the Advanced medical settings enabled.

**Comment by bux578** [comment]
pinging @Glowbal

**Comment by Mortified666** [comment]
This makes me happy. Keep up the awesome job guys.
