### ISSUE TITLE
Akward Sitting Positions Part 1

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#1795]
@jonpas 
#1541

Arma 3 Dev: 909fbb5dc4309b15f6c34ca78917f1ffec4b80e3

**Mods:**
* @cba_a3
* @ace3

**Description:**
When leaning back while sitting, the whole body clips through the chair.
Maybe the PFH limiting rotation could limit this too.

![2015-07-04_00001](https://cloud.githubusercontent.com/assets/1235520/8507108/1b26ce30-2234-11e5-9054-2af1caac420a.jpg)

![image](https://cloud.githubusercontent.com/assets/1235520/8507137/29e867e8-2235-11e5-81e5-3f13579598c6.png)

**Steps to reproduce:**
* Grab a chair
* Sit down
* Lean back

**Comment by Khaosmatic** [comment]
So ACE is adding the feature to sit in chairs?

**Comment by jonpas** [comment]
@Khaosmatic Yes, check #1541, it's perfect for briefings and stuff like that. :)

**Comment by jonpas** [comment]
@bux578 Couldn't find a suitable way to fix that, due to no set counterpart of `eyePos`. Possibility might be controlling the leaning animation, I am not sure how that's handled. I think this can go into backlog as it's not that big of a deal (like that other issue), I'll keep looking for a fix though, but please give me ideas and I can try them! :)

**Comment by jonpas** [comment]
Another bug to add is that you can throw grenades without delay or animation.

**Comment by bux578** [comment]
You could maybe take a look at how @commy2 did it for the captive animation.

**Comment by jonpas** [comment]
@bux578 I'll look into using `CfgMoves` (which is how captives animations work as well), but it might take me some time, this is like another complicated universe of Arma. :grin: 
It will fix both issues in this report though (I'll keep the rotation limit in PFH though as it can be different for each seat, while for leaning I can just make it a bit more than vertical).

**Comment by jonpas** [comment]
This hasn't been fixed yet @Glowbal only the other issue has been, this one needs more love (and I am away from tomorrow for 10 days).

**Comment by jonpas** [comment]
This still wasn't fixed, not sure why the reference closed it, I can't seem to fix that due without creating custom animations. I'd set it to Backlog for now.

**Comment by commy2** [comment]
I fixed the leaning issue in https://github.com/acemod/ACE3/pull/2338
Doing some more improvements...

**Comment by jonpas** [comment]
That's awesome @commy2 I knew I needed you, animation master! :grinning:
