### ISSUE TITLE
Akward Sitting Positions Part 2

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#1796]
@jonpas 
#1541

Arma 3 Dev: 909fbb5dc4309b15f6c34ca78917f1ffec4b80e3

**Mods:**
* @cba_a3
* @ace3

**Description:**
When sitting down on chairs positioned in a building the body clips through the ground.
ASL ATL problem?

![image](https://cloud.githubusercontent.com/assets/1235520/8507174/2888d958-2237-11e5-9fdc-919fa2171a82.png)

**Steps to reproduce:**
* Grab a chair placed in a building
* Sit down

**Comment by bux578** [comment]
It's even more drastical when you place the chair in the first floor:
![image](https://cloud.githubusercontent.com/assets/1235520/8507184/99e587ea-2237-11e5-9756-0d8ded804836.png)

**Comment by bux578** [comment]
![image](https://cloud.githubusercontent.com/assets/1235520/8507187/a2ad374c-2237-11e5-9989-2643849f9d05.png)

**Comment by jonpas** [comment]
Looks like something I forgot to push/commit.

**Comment by gienkov** [comment]
![high](https://i.imgflip.com/nsaye.jpg)

**Comment by jonpas** [comment]
I blame @Glowbal for that one: https://github.com/acemod/ACE3/pull/1541#discussion-diff-31983607
Since it's using `modelToWorld` which gives absolute position it needs to use `setPos`.

**Comment by bux578** [comment]
@jonpas when running the chair over you keep sitting ...
![2015-07-05_00003](https://cloud.githubusercontent.com/assets/1235520/8511379/d61d5eaa-2312-11e5-8bed-29a3ffa63c30.jpg)

**Comment by jonpas** [comment]
> when running the chair over you keep sitting ...

Can easily fix that, but I found a problem if you are using editor for testing. For some reason comparing original position with current one in PFH and taking control of another unit in a car, as soon as you hit forward it will make the unit stand up. I have no idea why...
