### ISSUE TITLE
Animations on units in Zeus

### ISSUE THREAD

**Issue by sergio47** [acemod/ACE3#1801]
maybe add somemore animations for zeus？like lean or talk with other ai or somethinglike that
really need in the coopmissions，use the code in mcc sometimes doesnt work

**Comment by Winter259** [comment]
Hi!

If this is an issue (which it does not look like one...) please follow this guide: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

Otherwise if it is a feature request, you can post it in this thread rather than opening a new issue: https://github.com/acemod/ACE3/issues/414

**Comment by SilentSpike** [comment]
Feature request, see winter's comment above :+1:
