### ISSUE TITLE
[Q] How to get people up on the advanced medical?

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#1802]
I was playing with ACE 3 advanced medical, and I had people down and wounded, I gave bandaged all the wounds, applied a bloodbag, gave the guy a epi, a morphine and he still didn't get up.
Got him up by eventually using a PAK.

Is  this a bug or is this supposed to be like this?

**Comment by alganthe** [comment]
no, there's a lot of different factors to take into account.

I usually do this when checking a patient :+1: 

- does he have a pulse ? yes / no
- Is he injured ? yes / no
- Is the wound bleeding ? yes / no
- Did he lost a lot of blood ? yes / no
- is he in pain ? yes / no

If he doesn't have a pulse do CPR</br>
If he have a pulse go to step 2 and fix him up</br>
Restore what blood he lost while stabilizing his blood pressure with plasma</br>
finally if he's in pain and his pulse is stabilized give him morphine then he should wake up.</br>

**Comment by Winter259** [comment]
To add on to this, the bandage -> bloodbag -> morphine -> epi cycle is for basic, not advanced.

**Comment by BryanBoru** [comment]
I tried checking, has it ever be mentioned that epinephrine is NOT something you administer to wake someone up, it is normally carried by Combat Medics to counter [Anaphylaxis](https://en.wikipedia.org/wiki/Epinephrine#Medical_uses). Consciousness is regained with time, and/or maybe [Smelling Salts](https://en.wikipedia.org/wiki/Smelling_salts)?

**Comment by xJenny99x** [comment]
Yes. It's wierd there also seems to be a bug with the medical system where it leaves the player damage bigger than 0 resulting in a gay effect which is only curable by PAK's
