### ISSUE TITLE
Prevent Instant Death doesn't work

### ISSUE THREAD

**Issue by INCHACA** [acemod/ACE3#1805]
Hi guys.

It seems that Prevent Instant Death (2.1 Medical settings 10) has stopped working. Before the last version of ACE it worked as it says: Instead of daying, units keep unconcious, but now it seems to depend on the damage or it just random. Sometimes the unit fall unconcious and other dies.

**Comment by jonpas** [comment]
Please follow http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by naizarak** [comment]
i had this problem with basic medical, but not with advanced

**Comment by Glowbal** [comment]
You can use the revive module if you wish to keep units unconscious.

Also @jonpas already mentioned it but please follow the instructions on the page he linked.
