### ISSUE TITLE
Bloody bandage litter created even though limb was perfectly healthy and has never been wounded

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#1807]
ACE3 3.1.1

**Mods:**
* cba_a3
* ace3

**Placed ACE3 Modules:**
* None

**Description:**
Bloody bandage litter created even though limb was perfectly healthy and has never been wounded

**Steps to reproduce:**
* Place two units
* Bandage the limb of another unit (don't wound it)

**Where did the issue occur?**
* Editor

**RPT log file:**
n/a

**Comment by jonpas** [comment]
> ACE3 3.1.0

???

**Comment by bux578** [comment]
typo

**Comment by jonpas** [comment]
:banana:
