### ISSUE TITLE
Vanilla Damage in Ace

### ISSUE THREAD

**Issue by brickyardgaming** [acemod/ACE3#1810]
This still seems to be an issue.  I've pulled the latest commits and am still receiving reports of it.  It seems to be linked to leg damage. Also burns seem to do it as well.

**Comment by alexcroox** [comment]
Is there a way to disable ACE medical on that note? I want to do a mission where I can't afford people to spend a minute healing themselves, but still want to use the rest of ACE. I presume there's no disable medical module?

**Comment by kripto202** [comment]
Just remove ace medical pbo from the addons folder and your done. Keep in mind that everyone has to remove the module too.

**Comment by alexcroox** [comment]
Yer I meant on a mission basis for that reason :)

**Comment by gienkov** [comment]
Not doable without removing pbo.

2015-07-07 0:53 GMT+02:00 Alex Crooks <notifications@github.com>:

**Comment by brickyardgaming** [comment]
This does not seem to be present when using the basic medical system by the way.  at least I haven't replicated it yet.

**Comment by Glowbal** [comment]
You will have to be more specific.  What is happening? Which version (commit)? When is it happening?

What settings are you using, etc. There is a good reason we ask everyone to use the form described here: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

Without such information, it could prove difficult to find the exact issue you are experiencing and fix it.

I will leave this open for now, but please edit the original post to match the proper format and include as much information as possible.

**Comment by brickyardgaming** [comment]
I completely understand.  I will do some further testing with other addons turned off when I get home from work.

I've edited the files as explained here:
https://github.com/acemod/ACE3/pull/1692

And am still receiving reports from unit members of vanilla damage.  It causes them to be stuck walking and unable to heal (unless using a PAK)

We only used the basic medical system for a brief time, but had no issues.

My knowledge on this subject is limited, so forgive me if what I'm about to say is elementary.  We use the GEAR mod for gear.  Does the gear mitigate and distribute damage and it's possible these uniforms/vests etc are not yet compatible with aces handedamage function?  I have yet to try it with all vanilla gear or even other mods.

We're also using RHS and Robert Hammer Pistols for our weapons.

**Comment by Glowbal** [comment]
Could you define what you understand under vanilla damage?

If this:
>  It causes them to be stuck walking and unable to heal (unless using a PAK)

is your only symptom, it is actually be design. If you want that to change, enable the setting `Bandaging removes bloodstains`

**Comment by WadeDP** [comment]
Shouldn't it tell you if your injured though? When I have the vanilla effect, it says no injuries when I check myself.

**Comment by brickyardgaming** [comment]
It seems to be linked to the reopening of wounds option.  I turned that option on and it seems to have fixed it.

**Comment by bux578** [comment]
This should be fixed in 3.2.0. If it's still an issue please open a new ticket.
