### ISSUE TITLE
Mk6 Mortar charge (firing mode) resets

### ISSUE THREAD

**Issue by HTSean** [acemod/ACE3#1814]
I've been messing with the Mk6 mortar and I'm loving it. There's just two issues though:

1) The charge resets when you leave the vehicle. 
It'd be great if it remembered what charge you had selected.

2) I believe there's a way to somewhat stabilize actual mortars so you can fire from slightly uneven ground. 
I'd love to see this implemented so that it can be used from more positions (I think ACE2 had it, if I remember correctly).

If you guys don't mind, I'd also like to ask if you guys are planning on adding more mortars like the M224 and M120, including ye olde ACE2 aiming method and round prepping and such?

Keep up the awesome work, guys.

**Comment by austinjames314** [comment]
The mortars not firing accurately when on ground other than perfectly flat ground is discussed at length in #1498. 

You're right, the charge does seem to reset when you get in and out. I've taken it as just something to watch out for, but it would be nice if it were fixed.

If you've been using the mortar a lot, have you noticed problems with the smoke rounds not following the ranges as per the rangetable? No one else around here has responded to my mentioning that, and it would be nice to see if someone can confirm I'm not crazy.

**Comment by HTSean** [comment]
Oh yeah, I just tried that out and you're right. I fired a couple HE and a couple smoke using the same ELEV and such and this was the result:


![](http://i.gyazo.com/c24c571e40daf78c9940010925444b6d.jpg)

**Comment by alganthe** [comment]
smoke shells being lighter than HE wind gusts might influence them a lot more.

**Comment by HTSean** [comment]
Yeah that makes sense. It'd be great to have a separate range table for smokes.

**Comment by austinjames314** [comment]
Yeah that's what I've requested before in another issue. But I might make a new one and link to this. Thanks for that! I never had enough people to help me test and get pictures like that.

**Comment by austinjames314** [comment]
Also @alganthe, I'm pretty sure it's not crosswind. In my experience the smoke rounds land about 5-10% _farther away_ than the HE rounds.

**Comment by Waffle-SS** [comment]
I sort of question the strength of these random wind gusts...
I've had HE mortar rounds land 500+m off a 1km away target due to wind gusts...

**Comment by HTSean** [comment]
You sure you were on flat ground then?

**Comment by austinjames314** [comment]
Yeah that sounds like you were on uneven ground. Wind usually only affects things by a few meters at 1km. see #1820

**Comment by PabstMirror** [comment]
Will now save/restore last charge setting
Leveling has also been fixed. #1820

The mk6-module's goal was just to give the option of something besides point-and-click for indirect fire.  Don't worry, real stuff should be coming down the road eventually.
