### ISSUE TITLE
[RHS Compatibility] No bullet trace w/ RHS weapons

### ISSUE THREAD

**Issue by HTSean** [acemod/ACE3#1815]
While covering sniper/spotter dynamics with my buddy, we found out that when using RHS weapons, there's no bullet trace. The ballistic values seem to work though, we can get right on target, but there's just no bullet trace.

I have no idea on whether this bug is on RHS' or ACE's end, so never mind, and my apologies if this is on RHS' end.

Steps to reproduce:
1. Fire w/ the RHS SR-25
2. Observe target w/ high-powered scope, note the lack of bullet trace
3. Fire w/ the vanilla Mk14 EBR
3. Observe target w/ high-powered scope, note the bullet trace.

**Comment by gienkov** [comment]
Isnt SR-25 5,56mm ? I guess its also the caliber that matters. Or maybe
compat config is needed.
8 lip 2015 02:38 "HTSean" <notifications@github.com> napisał(a):

**Comment by HTSean** [comment]
Nope, it's 7.62x51 so it should show a bullet trace. I guess it's the config then?

**Comment by bux578** [comment]
Do you mean the optical distortion added by advanced ballistics?

**Comment by bux578** [comment]
@ulteq After testing with both RHS and vanilla snipers the bullet trace effect doesn't appear with ace 3.2.0 and Arma 3 1.48

**Comment by bux578** [comment]
The bullet trace effect from advanced ballistics works for me on RHS snipers if I add the compatibility pbo from the optionals folder to the addon folder. So maybe you're missing the compat pbo.

**Comment by HTSean** [comment]
Yeah my apologies for that, I found out about that when I downloaded the latest version of ace again.

Sorry about that.`

**Comment by bux578** [comment]
Glad it works for you.
