### ISSUE TITLE
Mortar charge overlay persists

### ISSUE THREAD

**Issue by Waffle-SS** [acemod/ACE3#1818]
ACE3 Version: 3.1.2

**Mods:**
* @cba_a3
* @ace3

**Description:**
The Mk6 Mortar charge UI overlay isn't removed on mission restart/abort in editor. When you restart the charge overlay can still be seen. Reloading the mission in editor, or getting in and out of the mortar fixes the issue.

Image: https://dl.dropboxusercontent.com/u/95262179/ArmA/ArmA%203/ACE3/arma3%202015-07-07%2023-47-15-16.png

**Steps to reproduce:**
1. Get in Mk6 Mortar
2. Restart/abort mission

**Where did the issue occur?**
SP

**RPT log file:**
No scripts/config errors

**Comment by PabstMirror** [comment]
I have no idea why I was trying to use `ctrlCreate`, but it will be fixed with #1820
