### ISSUE TITLE
82mm Range Table: Convert from MILS to degrees

### ISSUE THREAD

**Issue by Waffle-SS** [acemod/ACE3#1819]
ACE3 Version: 3.1.2

**Description:**
The Mk6 Mortar can toggle between MILS and degree mode through ACE interact. If the player is in a the Mk6, the 82mm Range Table should automatically use the unit of measurement in use by the mortar.

Image: https://dl.dropboxusercontent.com/u/95262179/ArmA/ArmA%203/ACE3/arma3%202015-07-08%2000-04-52-49.png

**Comment by bux578** [comment]
Thank you for your request, but this a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
