### ISSUE TITLE
Change code to use param/params

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#1821]
https://community.bistudio.com/wiki/param
https://community.bistudio.com/wiki/params

**Comment by PabstMirror** [comment]
Did some quick testing, for normal PARAMS it's about 50% faster, but it was fairly fast to begin with.
Much bigger improvement when replacing `DEFAULT_PARAM`, which has a function call.

```
TEST1 = {
    PARAMS_5(_a,_b,_c,_d,_e);
    DEFAULT_PARAM(5,_f,6);
};
TEST2 = {
    params ["_a", "_b", "_c", "_d", "_e", ["_f", 6]];
};
```
Test code: `[1,2,3,4,5] call testX;`
0.0496948 ms vs 0.00810547 ms.

**Comment by Waffle-SS** [comment]
Holy crap, that's about 6x faster.

**Comment by Glowbal** [comment]
@PabstMirror how does it compare vs a regular private + select? Since the `PARAMS` macro also does some additional checking.

**Comment by SilentSpike** [comment]
Started this process (because I like using regex) on new branch: `params`

So far I've done each of the PARAMS_N macros on an individual commit to break it up and I've gone through each replacement individually to make sure there were no syntax errors.

**Comment by SilentSpike** [comment]
Just to share what's been discussed in the slack:

We'll likely just update the macros themselves to use the new commands. I'll leave that branch up for the time being though in case anything changes.

Here is my PR to update the CBA macros: https://github.com/CBATeam/CBA_A3/pull/93

**Comment by Tenga** [comment]
@Glowbal I've been told params outperforms select by itself.
> [1,2,3] params ["_lol"] is faster than _lol = [1,2,3] select 0

**Comment by SilentSpike** [comment]
The CBA macros have been updated with these commands. Do we want to close this, or do we want the changes from https://github.com/acemod/ACE3/tree/params ?

**Comment by jonpas** [comment]
I think it's better to keep using macros, that way any future changes can simply be changed there as well (just like this).

**Comment by bux578** [comment]
Done in CBA. Merged in https://github.com/CBATeam/CBA_A3/pull/93
