### ISSUE TITLE
[ACE Map - Feature Request/Change] Disallow map to be viewed under NVG's by default, but add a setting in module to allow NVG viewed maps.

### ISSUE THREAD

**Issue by JollyResQ** [acemod/ACE3#1822]
In real life (unless you are super high speed and have PVS2x or higher NVG's or a special attachment for your PVS14 Night Vision, it is impossible to focus NVGs close enough to accurately view a map. In real life you'd be required to raise your NVG's and use a red-lens light source such as a flashlight or other light source in a combat situation. 

Please consider implementing the system from Little Immersion Tweaks to allow flashlights to be used by default and visibly showing. http://forums.bistudio.com/showthread.php?189775-Little-Immersion-Tweaks-Spice-Up-Arma-3-s-Night-Life

**Comment by bux578** [comment]
Feature requests should be in: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html

But you're too late. We already have a pull request for the red/white flashlight that: https://github.com/acemod/ACE3/pull/1816 :smile: 

Though, I agree on the night vision bit.

**Comment by JollyResQ** [comment]
Understood! Apologies for submitting in the wrong area. Hope you guys get around to adding it in time. Thanks.
