### ISSUE TITLE
ACE 3 - Zeus

### ISSUE THREAD

**Issue by Blitzkreigery** [acemod/ACE3#1825]
Mods:

@cba_a3
@ace3

Placed ACE3 Modules:
None

Description:
ACE 3 is conflicting with Zeus, it says "[BIS_fnc_moduleExecute] Cannot execute module, error found in 'ace_zeus_fnc_bi_moduleCurator'".

Steps to reproduce:
I used CBA and ACE3, placed down a zeus module and connected it to a player then hit previwe, and I was unable acess or use zeus.

Where did the issue occur?
Singleplayer

RPT log file:
http://pastebin.com/YcN7m41G

**Comment by bux578** [comment]
#1817 Why the duplicate?
