### ISSUE TITLE
Medical Item model textures backwards

### ISSUE THREAD

**Issue by BryanBoru** [acemod/ACE3#1827]
Medical Item bugs.

in [This image](http://i.imgur.com/TBoyQu8.jpg) you can see the Personal Care Kit, Just a black image, yet it is the skin for [Quick-Clot](http://i.imgur.com/f5dgnRK.png) backwards and top side down..

To bring my pesky report to an anal and petty level, the body bag is acually a [mirrored image](http://i.imgur.com/uoYZpYt.jpg) of one.

Multiple images available in this album: http://imgur.com/a/nIrIL

**Comment by jokoho48** [comment]
Hey thanks for Reporting The Quick-Clot is currently in Pipeline, and the is on the planed to remake. the personalAidKit has currently no Model but one is already planed

**Comment by bux578** [comment]
@jokoho48 can I close this?

**Comment by jokoho48** [comment]
yes
