### ISSUE TITLE
Request: Advanced Medical

### ISSUE THREAD

**Issue by BryanBoru** [acemod/ACE3#1828]
In Advanced Medical, We should be required to have a sphygmomanometer (Blood Pressure Cuff) in our inventory in order to accurately get a blood pressure. 
Although there are other ways, it is a light and easy to transport tool that can quickly get you a dependable reading of BPs that we are checking.
I am an EMT by trade, but was no Combat medic, so there may be one who can chime in with better info than my suggestion.

**Comment by jokoho48** [comment]
please use: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
#414

**Comment by BryanBoru** [comment]
damn it, I forgot, Thanks @Glowbal, apologies.
