### ISSUE TITLE
Backblast-Configuration in CfgMagazines instead of CfgWeapons

### ISSUE THREAD

**Issue by BlackPixxel** [acemod/ACE3#1829]
Hi,

the current implementation for AT launcher overpressure could easily be improved to allow for more authentic ammotypes and firemodes of modern AT weapons:

At the moment it only reads the overpressure-values that are defined in the weaponcfg. It would be alot better if it would be required to define them in the magazine-config.
Examples:
-M3 MAAWS and SMAW both have additional CS - rounds without the lethal overpressure next to the regular ammo
-SMAW has a built-in spotting rifle. If it is defined as a second muzzle, it will have the backblast from the primary muzzle, which is not how it should be

Changing the Overpressure-Script so that it searches for the overpressure-values in the magazine-config instead of the weapon-config would solve these issues and would allow for more authentic and realistic AT weapons!

It would be great to see this changed in ACE3!

**Comment by bux578** [comment]
adding @jokoho48 for reference.

**Comment by Glowbal** [comment]
I like the suggestion, but I'd still keep the CfgWeapons values as a back up for any non configured ammo types.

**Comment by jokoho48** [comment]
Same Issue is in Hearing

**Comment by headedhorseman101** [comment]
It may be possible to make the CfgWeapons values a modifier, similar to that of the CfgWeapons initspeed variable.

**Comment by jokoho48** [comment]
i add a proirity system

**Comment by Khaosmatic** [comment]
Yeah I've noticed that too, it deafens you as well.

**Comment by jokoho48** [comment]
fix in #2385

**Comment by Khaosmatic** [comment]
Any chance of the new update being released this week?, I am waiting so bad to make a mission with the SMAW for my group session on Friday and with RHS fleshing out the USMC gear an hour or so ago its all in place besides the blackblast issue with the spotting rifle.

I pray to all bananas that are holy.
