### ISSUE TITLE
Explosives and physics

### ISSUE THREAD

**Issue by TheRealSlimSatan** [acemod/ACE3#1830]
When placing explosives they have physics and have the ability to destroy walls vehicles and other objects, an example can be shown in the linked video.
I apologize for the poor quality as AMD's Raptr is not the best recording tool, but it was all I had open at the time.

https://www.youtube.com/watch?v=Fp_yWLgWHMA

**Comment by jonpas** [comment]
Will be fixed with #1739

**Comment by TheRealSlimSatan** [comment]
Great to hear
