### ISSUE TITLE
concerning AI command buttons 

### ISSUE THREAD

**Issue by usernameyes** [acemod/ACE3#1831]
Add an option where i can enable ARMA 3 default Ai command buttons and disable ACE 3 grenade cycling and throwing mod buttons.
Edit: i ca'nt command AI anymore with ACe installed

**Comment by jonpas** [comment]
Simply rebind keys. :)

**Comment by usernameyes** [comment]
Well...i'm not a very smart man,
 thanks

**Comment by jonpas** [comment]
No issues, feel free to hop on ACE3 Public Slack to ask more questions, ask for invite here #429 :grinning:
