### ISSUE TITLE
Fix 82mm smoke round trajectory

### ISSUE THREAD

**Issue by austinjames314** [acemod/ACE3#1838]
As I've been trying to draw attention to in #414, #1820 and #1814, smoke rounds don't follow the same trajectory as the HE rounds. I've tried asking for mortar tables for the smoke rounds as a feature request but I've had zero responses to my various posts about this.

Instead it has occurred to me that maybe it's a bug? Perhaps the ACE ballistics has only been applied to HE rounds? This would explain why the smoke rounds go further, as if my theory is true they don't have any drag.

I would do a proper bug report, but I need 3 people to be able to test it properly, take screen shots etc, and haven't had any takers yet. #1814 has a good picture of the problem.

**Comment by alganthe** [comment]
no, smoke rounds being way lighter than HE they have a different muzzle speed and thus the rangetable can't be used for them.
that's why they land way further than HE

**Comment by austinjames314** [comment]
Ah OK. If that's true then the only fix is to get another rangetable made up for the smoke rounds. They'll have a completely different ballistic path.

**Comment by PabstMirror** [comment]
`Smoke_82mm_AMOS_White` claims to have native air resistance (`airFriction`), so my safety check was failing, but it's simulation type doesn't actually apply any in game.

Will be fixed in next release.

**Comment by austinjames314** [comment]
Ahh, so I was right. Awesome! Thanks!
