### ISSUE TITLE
[Question] Cannot find an option to lock backpack

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#1840]
Looks like ACE3 have this option in ace_backpacks.pbo But cannot figure out how to use it.
I want all backpacks to be locked by default in my mission. Is it possible to do? And will player be able to unlock it in game?

**Comment by jonpas** [comment]
It seems like the actual action hasn't been added yet at all.

**Comment by PabstMirror** [comment]
AGM had lockpackpacks, for ACE we switched to a system that just notifies you when someone opens you backpack.

Listen for a rustling and a little camera shake.

6de3df64743fc2fcebdef03457366d4cd3cfcc1b

**Comment by jonpas** [comment]
Then readme.md should probably be changed.  :)
