### ISSUE TITLE
Random Behavior from Unconciousness function on AI (ace_medical_fnc_setUnconscious)

### ISSUE THREAD

**Issue by FatLurch** [acemod/ACE3#1842]
It seems there might be a bug with the behavior of the Unconsciousness function:

I have the ACE Medical Settings Module placed, and I have the AI unconsciousness field set to enabled (not disabled, nor 50/50).

However, I seem to get getting random behavior from this function. I will put the unconsciousness function call into the init line of a unit ( [this, true] call ace_medical_fnc_setUnconscious; )  and load the scenario multiple times. Each time, there's a random chance of the unit dying instead of going unconscious. 

I also copied and pasted the unit about 20 times and ran the scenario again. The result is that a random number of the AI units wind up dead instead of unconscious.

Steps to reproduce:
1. Place ACE Medical Settings Module
2. Set "AI Unconsciousness" in Medical module to "enabled"
3. Place AI units
4. Insert the following code into the init line of each unit: [this, true] call ace_medical_fnc_setUnconscious;
5. Observe random number of AI dead instead of unconscious

**Comment by PabstMirror** [comment]
Ref #148 - Events at mission start/loading 

For now, use this code in a unit's init box:
```
if (local this) then {
    nul = this spawn {
        sleep 3;
        [_this, true] call ace_medical_fnc_setUnconscious;
    };
};
```

The problem is init order:
Unit's init's run before modules are read, so the unconc function saw `GVAR(enableUnconsciousnessAI)` as "50/50" which is default and not the setting from the module.

I guess we might need something like this:
```
if (!EGVAR(common,settingsInitialized)) exitWith {
    [FUNC(setUnconscious), _this] call EFUNC(common,execNextFrame);
};
```
or
```
if (!EGVAR(common,settingsInitialized)) exitWith {
    EGVAR(common,runAtSettingsInitialized) pushBack [_this, DFUNC(setUnconscious)];
};

```
for all public functions?

**Comment by FatLurch** [comment]
Gotcha, that makes perfect sense. Thank you for the quick feedback!

**Comment by SilentSpike** [comment]
>```
if (!EGVAR(common,settingsInitialized)) exitWith {
    EGVAR(common,runAtSettingsInitialized) pushBack [_this, DFUNC(setUnconscious)];
};
```

Would be perfect in my opinion :+1:

**Comment by Glowbal** [comment]
#2361
