### ISSUE TITLE
Increased abilty to look up - Enhancement

### ISSUE THREAD

**Issue by Karneck** [acemod/ACE3#1846]
Not sure if you guys would be interested in this, but this grants the ability to be able to look more "up" and not have it look too weird. 15th MEU use's this and we've found this pretty helpful especially in MOUT. Feel free to use it if you like it.

EXAMPLE
```
class CfgVehicles
{
                                class B_Soldier_base_F;
				class MylittleSoldier : B_Soldier_base_F
				{
  					minGunElev = -80; // Allows you to look more down
  					maxGunElev = 80; // Allows you to look more up (Used to be 60, BI standard)

					side = 1;
					scope = 2;
					audible = .05;
					accuracy = 0.25;
					camouflage = 1.4;
					weapons[] = {"Throw","Put"};
					respawnweapons[] = {"Throw","Put"};
					magazines[] = {};
					respawnmagazines[] = {};

```

**Comment by jonpas** [comment]
How does this work with animations? Do they still look normal?

**Comment by Karneck** [comment]
Yes, animations still look great. We played around with the MaxGunElev until we found a spot that still looked "normal" even when firing a weapon, but still allowed players the ability to look "almost" straight up.

Currently in PvP or MOUT vs AI. Any player/AI that is above another right now has advantage because they can look straight down, whilst anyone wanting to look straight up cannot do so, they are stopped at an upwards angle. Which isn't realistic at all.

With this adjustment, now Players assaulting up are in the same level playing field.

**Comment by alganthe** [comment]
Very useful, I can finally see what is above me without having to take 10 steps back.

**Comment by Legolasindar** [comment]
+1 for this.

**Comment by jonpas** [comment]
This would best fit into `ace_movement`.

**Comment by SzwedzikPL** [comment]
:+1:

**Comment by jonpas** [comment]
PRed, only `maxGunElev` had to be changed. @Karneck can you post your email so we can add you to the authors as well?

**Comment by Karneck** [comment]
Glad to have been of service.

My email is dschultz26@hotmail.com

If you guys ever have any config questions or such, I'm a jack of all trades in it, I've poured hundreds of hours into reading up on BIS's stuff. As for scripting though, I have zero skill in it haha.

**Comment by jonpas** [comment]
Thank you!

**Comment by BryanBoru** [comment]
This makes me so happy, thanks for all of your work.

**Comment by cych** [comment]
the max elevation angle should be 90°, and the minimum -90°, whatever the animation seems broken or not.

that just absurd to not be able to aim verticaly up or down.
