### ISSUE TITLE
Weapon overheating broken for some LMGs

### ISSUE THREAD

**Issue by Lifetap** [acemod/ACE3#1853]
There appears to be an issue with the maths behind the temperature calculation for weapon overheating.  For heavier weapons, with relatively light ammo, the temperature never rises above 1.0 irrespective of the number of rounds being fired.

Examples where this occurs are CUP L110A1, CUP M249

**Comment by alganthe** [comment]
Please [follow this form](http://ace3mod.com/wiki/user/how-to-report-an-issue.html)
As for the actual issue i'm going to check if the compats include those weapons.

**Comment by Lifetap** [comment]
We were developing the new release of the 3CB_BAF_Weapons pack and noticed that our L7 and L110 did not overheat,  We added debug code to our pack to monitor the ACE_overheating_XXX variables.  We found that when the ratio of bullet mass to weapon mass approaches 1, the temperature of the weapon never rises above 1.0.  
We checked weapons outside of our pack and found that the CUP L110 and M249 exhibit the same behaviour. 
For information, both of our weapons inherit from vanilla.  We have an alternate version of our L7 which is lighter (this is the only functional difference) and this works fine with CUP overheating.

**Comment by alganthe** [comment]
@ulteq shall be whipped in a public place with bananas.

**Comment by Lifetap** [comment]
Do you require any further information?

**Comment by bux578** [comment]
I've tested the CUP M249 and yes even with the compat pbo this weapon does not get any temperature at all. Even after firing 600 rounds 
`player getVariable ["ace_overheating_cup_lmg_m249", -1]` is `[0,164.207]`  (*note: the first number is the temperature*)

Magazine used: `"CUP_200Rnd_TE1_Red_Tracer_556x45_M249"`
CfgAmmo entry: `"B_556x45_Ball_Tracer_Red"`

**Comment by bux578** [comment]
Maybe @ulteq can help

**Comment by esteldunedain** [comment]
@bux, I'm pretty sure this has to be due to the ammo not having the bullet mass parameter correctly configured. This mag didn't exist back then when the compat pbo was created, and I bet the ammo didn't as well. I'm downloading the latest version of CUP to confirm.

**Comment by esteldunedain** [comment]
Obsolete
