### ISSUE TITLE
HuntIR monitor stays open even though its removed from inventory

### ISSUE THREAD

**Issue by WadeDP** [acemod/ACE3#1856]
ACE3 Version: 3.1.1.1
Stable

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None.

**Description:**
After HuntIR is removed from someones inventory, it still stays open.

**Steps to reproduce:**
Steal IR monitor from best friend (or worst enemy) and ask him if he still sees the monitor.

**Where did the issue occur?**
Multiplayer

**RPT log file:**
N/A

**Comment by gienkov** [comment]
Trivial...
Why would one like to steal it anyway? Also you can only grab items from
other player backpack and all ACE3 devices cannot be used while being
inside backpack...

**Comment by WadeDP** [comment]
I stole the HuntIR from his backpack and he was using it while in his backpack...
We were testing it, not actually applying it to gameplay. Its just a bug report. You really wouldn't want to steal it (I wouldn't) but we ran into this bug.

**Comment by bux578** [comment]
> all ACE3 devices cannot be used while being inside backpack...

I wouldn't be so sure about that ...

**Comment by gienkov** [comment]
Well then explain why most of devices from ACE3 works only from uniform/vest and not from backpack?

**Comment by WadeDP** [comment]
Really? That's besides the point. Do I really need to? The monitor works in the backpack, and when removed, it doesn't close for the person it was on. Test it yourself if you don't believe me.
