### ISSUE TITLE
Set Medic Class Bug

### ISSUE THREAD

**Issue by brickyardgaming** [acemod/ACE3#1860]
There seems to be an issue with a medic class loading into the game, disconnecting, and reconnecting.  Options like give blood/saline are no longer available and the unit is no longer designated as a medic.

Set Medic Class module is down and synced with units..units are named "Medic1" and "Medic2" and listed as such in the set medic class list: Medic1, Medic2

Steps to replicate:
1. Create mission and set a medic class.
2. Load in and use medic features as normal.
3. Disconnect.
4. Reconnect to same slot.

Dedicated Server, ACE 3.1.1

**Comment by PabstMirror** [comment]
Synchronized objects (F6/blue lines in editor) doesn't work well with JIPs.
When the disconnected guy JIPs back in, his new unit isn't syncronized with the module, so a variable on him never gets set.

What I would do is put this in the unit's init:
`this setVariable ["Ace_medical_medicClass", 1];`

**Comment by bux578** [comment]
> Synchronized objects (F6/blue lines in editor) doesn't work well with JIPs.

Infact it doesn't work at all and is by design. Moricky told us that on the arma feedback tracker.

**Comment by brickyardgaming** [comment]
Pabst, with the init, is there a need to have the module down?

**Comment by SilentSpike** [comment]
Nope, that init is exactly what the module is doing too :)
