### ISSUE TITLE
Interaction menu not working

### ISSUE THREAD

**Issue by AlphaGamer20** [acemod/ACE3#1861]
The interaction menu is not working for me. I installed the mod yesterday and tested it everything was working fine. today the interaction menu does not want to come up. the red circle that comes up when you press the buttons shows up but I do not have any options to treat any wounds. I tried it on several different scenarios and made my own missions just to test it. I am not sure if the latest update may have something to do with it although im not sure how it would have caused the problem. but I didn't see anyone else having the same issue on the list of issues here so I am considering the fact maybe im just doing something wrong lol but I used it all day yesterday. So im not sure that its me. I do have the CBA mod and I did not delete anything from the ace mod after downloading it so the interactions pbo and everything else is still there.so unless I am doing something wrong with the buttons somehow which I don't believe I am they were working for me yesterday or the update is causing a problem I am a little stumped on this issue

**Comment by jokoho48** [comment]
please use this http://ace3mod.com/wiki/user/how-to-report-an-issue.html
