### ISSUE TITLE
Possible Conflict With Arma3 Campaign.

### ISSUE THREAD

**Issue by Dellecxi** [acemod/ACE3#1865]
ACE3 Version: 3.1.1
Arma 3 Stable Version
Mods:
 CBA Arma3; ACE 3; ASDF Joint Rail; RHS USAF; Killoch's MultiNational Packs;

Modules:
Not using any ACE 3 Modules.

Description, Reproduce, GameType:
I had encountered two issues in Arma3 Campaign while using ACE 3 but may not caused by ACE 3 alone.
 1. For some reason main characters with allowdamage disabled are still killable or suspect to being  knocked unconscious by enemies, thus freezing the mission progress.
(To Reproduce: in East Wind's very first mission Drawdown 2035, sergeant Adam should not receive any damage except via friendly fire, or any other missions involving entities set with allowdamage false)

 2. After some progress into the mission, sometimes (randomly) i suddenly experienced dramatic frame rate drops (in one case, from 50 fps down to 9 fps) while looking at ground. Tuning down object view distance are able to bring the frames back up but are very unstable.
(To Reproduce: The origin of the problem remain unknown and occur in complete randomness.)

**Comment by Dellecxi** [comment]
Since Question 2 is related to graphical issue. (in some sense)
Here's my video setting for additional info:
1920x1080; 16:9 Wide; Vsync Disabled; Brightness and Gama both set to 1.0; 
view distance: 5000
obj view distance: 2000
shadow view distance: 200
Texture: Ultra; Object: Standard; Terrain: Ultra;
PiP: Disabled; Cloud: Ultra; Particle: High; Dynamic Light: Ultra; HDR: Standard; 

All PPs are set to 0; Ambient Occlusion disabled; Caustic Enabled;
2x FSAA; All Grass+Tree; CMAA as postprocess antialiasing; Ultra Anisotropic Filtering.

**Comment by nic547** [comment]
Afaik the arma campaign has some conflicts with ace3 that are hard to fix without changing the mission files, so the only way to play the campaign is to disable ace3 for it.

not sure about issue nr. 2, does that also happen during other missions?

**Comment by bux578** [comment]
ACE3 is mainly focused on Multiplayer. Could you please try it with 3.2.0 and only cba_a3 and ace3? If this issue still exists please open a new issue.
