### ISSUE TITLE
player interaction not working for jip players

### ISSUE THREAD

**Issue by hartzie** [acemod/ACE3#1868]
ACE3 Version: 3.1.1.1

**Mods:**
* @cba_a3
* @ace
* @acre2
* @allinarmaterrainpack
* @asdg_jr
* @blastcore-tracers
* @blastcore_a3
* @caf_ag
* @ewk_m1151
* @hafm_hmmwv_a3
* @hlcmods_ak
* @hlcmods_core
* @rh_acc
* @rh_m4_a3
* @rh_pistol_a3
* @rhs_afrf3
* @rhs_usf3
* @tf47_launchers
* @3cb_baf_vehicles
* @3cb_baf_weapons
* @asdg_jm
* @smgr
* @chains_m27_law_pack
* @3cb_baf_equipment
* @etr_public_server
* @mad_resh
* @etr_assets
* @rds
* @tf47_launchers_rhs

**Placed ACE3 Modules:**
* Interaction System
* Medical Settings
* Advanced Medical Settings
* Hearing
* Wind Defelction
* Advanced Ballistics
* Respawn System
* Weather

**Description:**
The issue started today on the public server. It is a bit heavy scripted public server mission running on a linux server and headless client. Players cannot interact with other players which join in progess later. None of the options show up and tapping with CTRL + T does not work either. Any other object or class interaction is working. I do not know so far if it is related to the Arma 3 update from yesterday or not. We had small changes last night and I am not aware of any issues from yesterday.
So the big question is what can cause the player synchronization to break from other mods or missions.

**Steps to reproduce:**
Reproduction so far not successful. I created a small mission with the same modules and settings but it is not occurring which concludes me something in the mission creating the issue.

**Where did the issue occur?**
Multiplayer

**RPT log file:**
Logfile from a player machine: http://pastebin.com/13bJVDyM
Logfile seems to be clear also server and hc are not showing any warnings or errors regarding the issue ofc.

**Comment by kripto202** [comment]
Like you said before, it is a heavily scripted mission which could have conflicted with ACE interaction for JIP players. I would find which script caused the problem in the first place.

**Comment by bux578** [comment]
If you've found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using only @cba_a3 and @ACE3 on a newly created mission.

**Comment by kripto202** [comment]
@bux578 
> Reproduction so far not successful. I created a small mission with the same modules and settings but it is not occurring which concludes me something in the mission creating the issue.

He already did so it is in the mission.

**Comment by hartzie** [comment]
We found the issue. My little fairy who creates the unit addons extended the base classes in the vehicle config a bit unnecessarily. This caused the whole issue BUT that was for ever in and after the Arma 3 update it started to make the weird behavior.

**Comment by jonpas** [comment]
Good to hear it was resolved, cheers!
