### ISSUE TITLE
Vector Range Finder Lag Spike

### ISSUE THREAD

**Issue by Waffle-SS** [acemod/ACE3#1871]
ACE3 Version: 3.1.2

**Mods:**
* @cba_a3
* @ace3

**Description:**
Getting heading or range with the Vector Range Finder causes a lag spike. Normal range finders seem unaffected.

**Steps to reproduce:**
Press Tab or R (ACE range/azimuth keys) while using a Vector.
(spinning from left to right helps show the lag spike)

**Where did the issue occur?**
SP/MP

**RPT log file:**
No script/config errors

**Comment by austinjames314** [comment]
I use the Vector all the time, and I've never noticed this.

**Comment by Neax10** [comment]
Noticed it also on long range (700m+)

**Comment by PabstMirror** [comment]
@Waffle-SS can you try to reproduce this again double check RPT.

I didn't realty feel any lag and the functions seemed reasonable fast, but I was getting RPT spammed with 
```
control[ACE_ScriptedDisplayControlsGroup]: Unexpected control type [15]
```
twice per frame, depending on system, that's what I think could be causing the frame drops.
