### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by markh7991** [acemod/ACE3#1876]
I get the addons missing deleted error in my server rpt file when loading any mission with ACE in it. Other peoples missions too. Its def in my startup parameter and it works in local server multiplayer.
Missions with no ACE work fine but obviously no ACE. The menu is there when I hit escape but its blanked out.

I must have missed something obvious, please help.

Here's my mod parameter:

@CBA_A3;@mcc_sandbox;@AH64D;@HAFM_A3;@bwa3;@bw_nh90;@ALiVE;@AliveServer;@PRKZ;@MightyGau;@CAF_AG;@BWDR;@ASR_AI3;@allinarmaterrainpack;@Ares;@ace;@task_force_radio

**Comment by jonpas** [comment]
Read the following on how to submit an issue to make it easier for the developers to pinpoint http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by markh7991** [comment]
[url]http://pastebin.com/gy2eWeMr[/url]

[url]http://pastebin.com/vRKQJyKb[/url]

**Comment by Glowbal** [comment]
> Read the following on how to submit an issue to make it easier for the developers to pinpoint http://ace3mod.com/wiki/user/how-to-report-an-issue.html

We have this for a very good reason. Please take the effort to read the article and adjust your issue report.

You posted some rtp log files, neither of which you appear to be launching ACE3 with, though they do look incomplete. Either way, please re test with only CBA and ACE3.

**Comment by markh7991** [comment]
It's not an issue though. I'm just looking for some advice on what the usual hiccups can be for me the first time user.

I fixed it anyway. Once I removed BW Mod, HAFM-NH90, Nh-90 reskin & BW Dingo it worked. One of those mods is the culprit.

Thanks
