### ISSUE TITLE
ace_medical.dll not found when loaded into the game

### ISSUE THREAD

**Issue by Ajurr** [acemod/ACE3#1878]
ACE3 version: 3.1.1

Mods: 
@CBA_A3
@ace
@RHSAFRF
@RHSUSAF

Placed ACE3 Modules:
None

Desc & Steps to Reproduce:
As far as I can tell only @CBA_A3 and @ace are needed.
This isn't my problem, it's a friend's. But he's extremely irritated because he's tried fixing it the past 24 hours, so I'm making this post for him. 
Essentially, when he gets into the game itself, a popup appears with something along the lines of ace_medical.dll not found or not installed or something. Then it automatically kicks him out into the last screen he was at, i.e. if he's hosting it will boot him back into the server lobby, if he's in the editor it kicks him back into the editor screen itself again.
It works for me.

The .dll is there, we've replaced it, we've sent him our ace folders and he's replaced them, he's tried moving his medical.dll to the base Arma folder (and that actually didn't work, it legitimately wouldn't let him), he's tried numerous fixes, verified game integrity cache, and tried what's been said on another ticket which was never solved because the author's problem mysteriously disappeared.

We're at a loss. So we've rolled back to the previous version of ace3, which, curiously enough, doesn't have the medical.dll.

Where did the issue occur?
Multiplayer, singleplayer, editor.

Also, this is the exact same problem that was referenced here: https://github.com/acemod/ACE3/issues/1679

**Comment by jonpas** [comment]
> it legitimately wouldn't let him

That implies that something is blocking his DLL. Check #1416 for more information.

Please also edit the ticket according to http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by Ajurr** [comment]
Update : He's turned off his Battleye, his antivirus programs, his firewalls. No avail. Checked security permissions for the Arma 3 folder, as well as for the .dll itself, everything is fine. He's tried deleting the .dll and launching the game, still the same problem.

**Comment by Glowbal** [comment]
Any change the anti virus program used is AVG?

**Comment by Ajurr** [comment]
He used to use AVG, but uninstalled it a while back. Now he uses Avast with a combination of Windows Defender.

**Comment by kripto202** [comment]
do you even have the dll file in the correct location?

**Comment by Ajurr** [comment]
He tried. It wouldn't let him move it anywhere unless he actually cut it and pasted it. He tried that and he also made a different copy and put it in the @ace folder.

**Comment by kripto202** [comment]
How I would try to fix this problem:
- redownload the mod and make sure all the files are in the correct locations
- Check other mods such as CBA (this could cause the problem I think, I could be wrong)
- make sure to run the mod through the default ArmA 3 launcher (not programs like a3sync or playwithsix or ect)
- make sure you don't have battleeye enabled. It seems to cause a lot of problems with mods so i don't even bother with it since I'm only on my group's private server.
If he is still having trouble I can get together with him and help him out. It's hard to tell what could be the problem

**Comment by Ajurr** [comment]
Hey, thanks for the help! We didn't really think about CBA, but we've tried everything else, as well as have had Battleye disabled due to it constantly crashing my game for no reason. Thanks for the suggestions, we'll try it as soon as we can!

**Comment by kripto202** [comment]
There are some optional pbos in the optional folder, did he ever move the rhs pbos into the addons folder. That is the only thing i can think of right now. The pbos should look like:
- ace_compat_rhs_afrf3.pbo
-ace_compat_rhs_usf3.pbo

**Comment by Ajurr** [comment]
He may have moved everything in the optional folder... I'll talk to him. Thanks again!

**Comment by kripto202** [comment]
if that's the case, that may cause the problem you only need the files for the mods you are running.

**Comment by Hikinen** [comment]
I had same problem turned out that my computer was blocking .dll files in ace folder. Had to allow them manualy. Right Click "ace_medical.dll">Properties>Lower right corner>Click allow (or something similar)

**Comment by Ajurr** [comment]
I believe he has already tried that -- at least, he looked for anything in the properties of the .dll. I'll bring it up again when he wakes up.

**Comment by kripto202** [comment]
what does he use to launch arma? If he is using the arma 3 launcher, there is a option for malloc, I'm not sure what it does but it started talking about dll files. I would make sure he turned that off.

**Comment by Ajurr** [comment]
He uses the default Arma 3 launcher. malloc is the choice between memory allocation .dll files, just know that the default one is pretty garbage -- the only correlation is that both me and him use an edited, better variant of the default memory allocate .dll and the -malloc=xxx.dll launch parameter.

**Comment by bux578** [comment]
Any progress @Ajurr? Did you test it with 3.2.0?

**Comment by Ajurr** [comment]
It seems fixed -- for my friend -- with the latest update. Thanks for asking!
