### ISSUE TITLE
Body Bag/Dead Character Behavior

### ISSUE THREAD

**Issue by FatLurch** [acemod/ACE3#1880]
Hello, 
    I have a few notes on the behavior of body bags and dead characters.

1. It doesn't seem that body bags can be loaded into vehicles.
2. It does not seem that dead characters can be dragged or carried.

The main reason these features are desired is for recovery operations. 

I apologize if these are planned features that existed in a prior release of ACE; I am not familiar with the earlier versions.

Thank you!

**Comment by kripto202** [comment]
please use this http://ace3mod.com/wiki/user/how-to-report-an-issue.html

Also a lot of this stuff is already noted and its being planned with ACE Logistics

**Comment by FatLurch** [comment]
Ok, thank you for the feedback kripto.
