### ISSUE TITLE
MK6 mortar and arma 3 update 1.48

### ISSUE THREAD

**Issue by Halifax007** [acemod/ACE3#1881]
Hello
Since the arma 3 update 1.48 we are not able to hit any target by using the "ACE_RangeTable_82mm". Does anybody confirm this issue?

http://dev.arma3.com/post/spotrep-00045
[...]
Fixed: Artillery computer imprecise range detection
Fixed: Mortar now has a better center of mass
[...]

Halifax

**Comment by austinjames314** [comment]
Oh shit. My clan's servers have been down a few days, I'll jump on and do some testing as soon as I can. (We're planning a tac game this weekend using mortars...)

**Comment by Halifax007** [comment]
Hi austinjames314

I did a test with the "legacy Build 1.46" of arma3. With this build there's no problem to hit the targets...

http://dev.arma3.com/post/spotrep-00045
[...]
A Legacy Build Steam branch is available for advanced users. It contains the previous significant main branch version (1.46). It can be used to compare specific changes between major releases. The access code for this branch is: Arma3Legacy146.
[,,,]

Why are they doing such strange changes?

Halifax

**Comment by kripto202** [comment]
please use this http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by austinjames314** [comment]
Ah OK. That's good to know, thanks @Halifax007

**Comment by austinjames314** [comment]
OK, I finally got a chance to test this at first I thought it looked OK because we tested at long range, and weren't very far out. When I test with a higher elevation though, there's definitely a problem. Rounds consistently land short, and with higher elevations it's more noticeable.

**Comment by bux578** [comment]
Closing this because it's apparently fixed. #1889
