### ISSUE TITLE
No ACE interaction menu while using AAF units

### ISSUE THREAD

**Issue by Neodyn** [acemod/ACE3#1882]
ACE3 Version: 3.1.1

**Mods:**
* @AllInArmaTerrainPack
* @CAF_AG1.5
* @CAF_AG_AudioPatch
* @RHSAFRF
* @RHSUSF
* @ascz_a2_map_fixes
* @BWA3
* @cba_a3
* @CHVD
* @MightyGau
* @ace
* @task_force_radio
* @ALiVE
* @ASDG_JR
* @Leights OPFOR
* @caf_hlc-wp_replacement
* @hlcmods

**Placed ACE3 Modules:**
* *ACE Check PBO; ACE_moduleMedicalSettings; ACE_moduleReviveSettings *

**Description:**
*It is not possible to open the self / interaction menu*

**Steps to reproduce:**
* *Create mission with the mods above. Place an Vanilla AAF e.q. Rifleman and Ace medical modules.  Test it*

**Where did the issue occur?**
* Both "Multiplayer" and "Singleplayer"*

**RPT log file:**
*http://pastebin.com/ZA8wuH1d*

**Comment by bux578** [comment]
> If you've found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using only @cba_a3 and @ACE3 on a newly created mission.

**Comment by PabstMirror** [comment]
We have noticed that when using ACE with 3rd-Party mods that do not fully support CBA Extended Eventhandlers (XEH) that some units do not work with Interaction fully. You may see the cursor but no menus.

WORKAROUND: The latest CBA RC7 Hotfix 2, v1.1.23 has an optional PBO that you can activate to help resolve these situations. 
1. Move the cba_enable_auto_xeh.pbo and its signature file from the CBA optional folder to the CBA Addons folder
2. Restart Arma.

If that does not fix issue, please add full rpt.

**Comment by Neodyn** [comment]
@PabstMirror thx this Workaround is working great
