### ISSUE TITLE
Movement in Transport planes

### ISSUE THREAD

**Issue by DrunkenTee** [acemod/ACE3#1883]
!! Sorry for my english !!

I know it's hard to create it, but it would be very very cool if you can do make a new feature to walk in Planes like the C-130J from the RHS mod or the C17-Globemaster. It's also would be damn cool when you can make the same with Vehicles, so (like) I can open the Ramp and 20 Parajumpers can get in the back of the Plane and I close it, I can get the Plane in Air and they are still at their Position and when I open the Ramp that they can jump out and open their parachutes, I know it's really really hard but it would be the best Feature of the world for ArmA 3. You guys do a good Job! Keep going

**Comment by jonpas** [comment]
Feature requests should be posted in #414 as stated in http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html

:)

**Comment by DrunkenTee** [comment]
Read me through.. and I saw not the Feature above.. But I read that someone talked about dark Map in vehicle at night, what about Interior lights :)?

**Comment by bux578** [comment]
As @jonpas said this is a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
