### ISSUE TITLE
Scope Adjustment not working when resting(Vanilla Arma) weapons

### ISSUE THREAD

**Issue by ElectroEsper** [acemod/ACE3#1884]
As simple as the tittle,

scope is not adjusting in real time (visually) when my weapon is resting. However it works perfectly when not resting it.

**Comment by kripto202** [comment]
please report the issue correctly http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by bux578** [comment]
Even so ... I'm not able to reproduce. Using only cba and ace Scope Adjustment works perfectly fine while standing, kneeling, being prone, not rested or rested and even with the bipod deployed.
