### ISSUE TITLE
No interaction menu on civilian factions

### ISSUE THREAD

**Issue by brickyardgaming** [acemod/ACE3#1887]
While playing, i noticed there is no interaction menu on any civilian faction.  We are unable to restrain civilians or frisk.  Perhaps there is something I am missing.

	addOns[]=
	{
		"A3_Characters_F_BLUFOR",
		"a3_characters_f",
		"a3_map_stratis",
		"mcc_sandbox",
		"ace_common",
		"ace_advanced_ballistics",
		"ace_hearing",
		"ace_map",
		"ace_respawn",
		"ace_weather",
		"ace_medical",
		"ace_interaction",
		"A3_Modules_F_GroupModifiers",
		"rhsusf_c_troops",
		"aia_misc_e_config",
		"A3_Weapons_F_Ammoboxes"
	};
	addOnsAuto[]=
	{
		"A3_Characters_F_BLUFOR",
		"a3_characters_f",
		"mcc_sandbox",
		"ace_common",
		"ace_advanced_ballistics",
		"ace_hearing",
		"ace_map",
		"ace_respawn",
		"ace_weather",
		"ace_medical",
		"ace_interaction",
		"A3_Modules_F_GroupModifiers",
		"A3_Weapons_F_Ammoboxes",
		"a3_map_stratis"
	};

Steps to Replicate:
Make mission
Place Civilian
Attempt Interact

I've even tried to place a civilian and switch them to a different team using the Ares module.  Even if they are switched to blufor/opfor/indep, there is still no interaction menu.

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

That's a duplicate, though. That's no error of ACE3
Please look at that ticket for the fix #1882

**Comment by brickyardgaming** [comment]
Thanks for the reply and the link.  We are using CBA 1.121.  Will update!

**Comment by brickyardgaming** [comment]
Just an update.  Switching to the latest version of CBA has fixed this issue.  Thank you for the response bux.
