### ISSUE TITLE
Strange medical behavior

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#1888]
ACE3 Version: 3.1.1 and 3e420b6bf683d51e8918ff7ea404a64238fcda50

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Medical Module (AI Unconscious - Yes, Prevent instant death - Yes)*

**Description:**
*Place a unit. Shoot him in the leg or any other part. One bullet will destroy all his bones putting him unconscious, after he wakes up second bullet will kill him without going in unconscious state. Same happens in multiplayer for players and AI.*
http://i.imgur.com/EKsi7d4.jpg

**Where did the issue occur?**
*Multiplayer and Singleplayer*

**RPT log file:**
http://pastebin.com/2H2iyr80

**Comment by bux578** [comment]
@rebelvg Could you please try this with the new ACE3 version 3.2.0?

**Comment by rebelvg** [comment]
@bux578 Same for 3.2.0. First thing I tested when 3.2.0 was released. I can record a video if that can help.

**Comment by bux578** [comment]
@rebelvg Yes, please.

**Comment by SilentSpike** [comment]
This is probably related to the damage bug that was recently fixed?

**Comment by rebelvg** [comment]
@bux578 https://www.youtube.com/watch?v=qQzM6btGvI8

**Comment by paullee18** [comment]
Something similar happened today in a MP session. Some players were waking up with completely damaged body parts, but it took nearly double the amount of bandaging to heal. Healing a limb the first time resulted in the limb going back to red and having to heal the limb again.

**Comment by bux578** [comment]
This is probably fixed in https://github.com/acemod/ACE3/issues/1946.

I'm closing this issue. If it happens again after we've released 3.2.1 please open a new ticket.
