### ISSUE TITLE
Ace Mortars broken by 1.48 update.

### ISSUE THREAD

**Issue by austinjames314** [acemod/ACE3#1889]
ACE3 Version: 3.1.1
(stable version)

**Mods:**
* @AllInArmaTerrainPack
* @CBA_A3
* @RHSAFRF
* @RHSUSAF
* @ShackTacUI
* @OnlineCombatBattalion
* @ascz_aia_extensions
* @ace
* @acre2
* @Bornholm
* @isladuala
* @JS_JC_FA18
* @JS_JC_SU35
* @Leights_OPFOR
* @Panthera
* @ASR_AI3
* @PRKZ
* @USAFLite
* @L_ES

**Placed ACE3 Modules:**
* Unknown, not my mission, but occurs any time Ace Mortars with Air Resistance are enabled.

**Description:**
* As per #1881. Since 1.48, mortar rounds no longer have the same ballistic path as before. My rounds have been consistently landing short, and the difference is more noticeable on charge 2 with a higher elevation. Attacking the same target on charge 1 will get closer to the target, but still fall well short.

**Steps to reproduce:**
* Play any mission with Mk6 mortars, with Air Resistance enabled. Calculate a fire mission on charge 2 onto a target where you can observe the fall of shot in the surrounding area. Watch all the rounds fall way short.

**Where did the issue occur?**
* Singleplayer and multiplayer

**RPT log file:**
https://drive.google.com/file/d/0BxfgbiRB-sRreV9paV94d3VEZWs/view?usp=sharing

**Comment by austinjames314** [comment]
I should add, that I haven't changed any mods since the last time the mortars were confirmed as working fine. The only change was the 1.48 release. As reported in #1881, rolling back to 1.46 fixes the issue.

**Comment by bux578** [comment]
http://ace3mod.com/wiki/user/how-to-report-an-issue.html

> If you've found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using **only @cba_a3 and @ACE3 on a newly created mission**.

**Comment by austinjames314** [comment]
As I said I haven't changed my modset, and the only change was the update to 1.48. If you now of any servers that are running only CBA and ACE3, then let me know and I'll go test it, but I don't know of any.

**Comment by bux578** [comment]
> As I said I haven't changed my modset, and the only change was the update to 1.48.

That is not a valid test case, though. You still need to factor in that 1.48 could have wreaked havoc with the other loaded mods which could potentially influence your test results. To fix things in a timely fashion we need to be sure that ACE3 is really the culprit.

**Comment by austinjames314** [comment]
OK, but like I said I don't know how to find a server with just CBA and ACE3 enable to test with.

**Comment by austinjames314** [comment]
One point I forgot mention is that muzzle velocity is not affected, as time of flight is almost exactly as it should be. Time of flight is generally 0.5 - 1 second longer than it should be on charge 2. All signs point to the air resistance being increased. This would explain why the rounds fall short, and why they take slightly longer to arrive than they should.

**Comment by bux578** [comment]
Maybe @PabstMirror is willing to take a look at it.

**Comment by Halifax007** [comment]
Hello

I think, it's a BIS' fault. Have a look at http://feedback.arma3.com/view.php?id=24894

But the rangetable of ace3 is also affected. I did also tests with ACE3 Version: 3.1.1 and CBA.

I hope, they will correct this issue soon.

**Comment by Waffle-SS** [comment]
I can confirm that I've had the same exact issues only after the 1.48 update.

**Comment by PabstMirror** [comment]
#1820 mostly fixed this assuming the ground is relatively level

On a 10 degree incline, the difference should be almost nothing.
Keep in mind the guns have some built in dispersion that can be fairly significant (+/- ~0.5 degrees).

You can disable this by adding to config:
```
    class CannonCore;
    class mortar_82mm: CannonCore {
        class Single1: Mode_SemiAuto {
            artilleryDispersion = 0;
        };
    };
```
and testing shots.

Going past a 20 degree ground incline and the elevation won't be fully reliable  I have tried to replicate BIS's leveling, but it still isn't 100% correct.

Now as I said in the PR, if you are looking at the ground the gun shoots one way, and if you are looking at infinity (the sky) it shoots a radically different way.  The "sky" calculation is always right, so keep that in mind.

**Comment by austinjames314** [comment]
>On a side note, are you aware of, that you can create your own local dedicated server and join that server with a second instance of Arma 3?

Really? No, I had no idea. Even reading that I'm not how I would do it, but it sounds like I could figure it out. I'll give it a try tonight.

@PabstMirror So are you saying that this is another example of the rounds being fired on a trajectory other than the azimuth and elvation shown? Because I was testing on a dead flat surface (runway), the rounds landed short regardless of what direction I was facing, and the amount they were short by depended on the charge. This lead me to believe it was an atmoshperic drag issue.

>Keep in mind the guns have some built in dispersion that can be fairly significant (+/- ~0.5 degrees).

This is why I did all my testing with 10 round groups, and recorded the center point of the group. The rounds were falling far too short to be within the usual dispersion even if I was only firing one round anyway. @Halifax007 is right, we're talking about 200-400 meters off the target.

>Now as I said in the PR, if you are looking at the ground the gun shoots one way, and if you are looking at infinity (the sky) it shoots a radically different way. The "sky" calculation is always right, so keep that in mind.

This is a revelation. I had assumed that looking at the sky was to be avoided, not looking at the ground, based on your comment in the PR. I clearly need to do more testing to check this out for myself.

**Comment by Halifax007** [comment]
Hello
Have a look at the screenshots there. Even shooting with the mk6 scope doesn't work:

http://feedback.arma3.com/view.php?id=24894

I think with the update 1.48 they changed the game physic and it could be, that one or both fixes is / are the issue(s):

http://dev.arma3.com/post/spotrep-00045
[,,,]
Fixed: Artillery computer imprecise range detection
Fixed: Mortar now has a better center of mass
[...]

Now the question is, how long does it take til bi change the status from "new" to "resolved"?  Perhaps it would be good, that other peoples do also report this issue at http://feedback.arma3.com/

Halifax007

**Comment by austinjames314** [comment]
OK, I updated to ACE version 3.2.0 last night and did some testing by myself. All rounds are landing as expected so far with my short range tests. I need to do more testing at longer ranges and in different situations to be completely confident with them again, but they're looking fixed so far. Looks like @PabstMirror was correct. Thanks! (Also loving that smoke rounds are working now as well :smile:)
