### ISSUE TITLE
Default ArmA 3 medical is running besides ACE 3 medical

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#1890]
ACE3 Version: 3.1.1

Mods:

    @cba_a3
    @ace3

Placed ACE3 Modules:

ACE 3 Medical (advanced for players only)
ACE 3 Advanced Medical(pain suppression off)

ACE 3 Settings : pain effect was set on white flashing

Description:
Get shot and bandage, wait until pain is gone. Still have the default ArmA 3 medical wounded effect, red flashes around screen and character making weird noises. This can be cured by going to a medical tent and using the ArmA 3 action menu to heal. Using a PAK also fixes the red flashing effect.

Technical : Player setdamage 0.15; Will cause the red flashing without the player being wounded in the ACE Medical system, and this can only be cured with a PAK or using the Action menu while next to a medical vehicle or building / tent.

Where did the issue occur?
Multiplayer and Singleplayer

RPT log file:
Not required.

**Comment by gienkov** [comment]
It's fixed already so don't worry.

**Comment by xJenny99x** [comment]
in 3.1.1? Or next update?

**Comment by gienkov** [comment]
Already in master / Next update.
