### ISSUE TITLE
Greyhawk manual fire

### ISSUE THREAD

**Issue by jcdj** [acemod/ACE3#1898]
After designating a target with a laser I cant lock ok the target with the greyhawk manual fire mode . The default key un vajilla is R but with this mod doesnt work

**Comment by jonpas** [comment]
Please follow http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by bux578** [comment]
You can't lock a laser target `"LaserTargetW"` while manually controlling the uav turret. The problem is that the missiles follow the cursor rather than flying towards the laser target.
