### ISSUE TITLE
Glasses "AV_ESS_blk" is "scope = 2" and inherits identityTypes[] and displayName from "None"

### ISSUE THREAD

**Issue by foxhoundinternational** [acemod/ACE3#1899]
AV_ESS_blk (a CfgGlasses, found in addons/goggles/config.cpp) inherits from "CfgGlasses" >> "None", but does not redefine identityTypes[] or displayName, and it is "scope = 2".

Having a second "dispalyName" results in two "None" entries in the profiles glasses selection screen. Having the default identityTypes[] may also affect the random distribution of glasses in identityTypes such as "NoGlasses" and "G_NATO_default".

**Comment by CorruptedHeart** [comment]
`AV_ESS_blk` is/was glasses by another mod that was support was added for in the LHM_Glasses mod.

It probably has no place in ACE, at least not directly.

**Comment by foxhoundinternational** [comment]
Yeap, looks like it was part of this mod:

http://forums.bistudio.com/showthread.php?158193-AV_IndUs-(US-Army-inspired-units)

Which going by that thread has been largely merged into RHS in any case.

**Comment by PabstMirror** [comment]
Removed for now, we could look at adding to a compat pbo
