### ISSUE TITLE
QUESTION: Regarding Issue #1692

### ISSUE THREAD

**Issue by legman** [acemod/ACE3#1900]
#1692 

Does this fix the issue with **Prevent Instant Death** not working 100% of the time. To elaborate, even though **Prevent Instant Death** is enabled, players are still randomly one shot killed by medium - large caliber weapons.

If this issue is new to you, let me know and I will report it in the correct manner!

Thanks

**Comment by kripto202** [comment]
let me ask you this, if you get shot in the face, get shot by a 50 cal rifle or something large like that would let that person survive? No, if you get shot in the face, your dead, if you get shot by a 50 cal bullet, your going to have either a limb or a huge ass hole in your body. I don't think anyone can survive that.

**Comment by legman** [comment]
Interesting point mate - no really you are quite right.  But when we are dealing with functionality that is titled **Prevent Instant Death** one would think that this is indiscriminate of the type of bullet, wouldn't one?

Especially because this feature worked fine in the previous version of ACE3.  Maybe you didn't read my post correctly?

Thanks for your input none the less though.

**Comment by kripto202** [comment]
I know what you might be experiencing, the ai starts shooting at you and you take a few hits and suddenly your dead. In simple terms he is hitting you while your down. How the knock out system works, you turn into a civilian so the ai doesn't keep shooting you. One problem is that the ai has watched zombie land and learned to double tap. I'm guessing that the ai are shooting you twice before you fall to the ground which ends up killing you.

**Comment by Glowbal** [comment]
A second hit while in unconscious state will kill a unit while in the prevent death state. 

If you do not want to have this behaviour, you could try out the revive module, found under the `medical` module category.
