### ISSUE TITLE
Effects missing for no eye protection.

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#1903]
Missing blurring, squinting and excessive blinking effects for being subjected to dust and wind without eye protection. Clearing eyes would have same effect and button as wiping glasses.
Side note: why don't NVG's have similar effects to eye protection.

**Comment by bux578** [comment]
Thank you for your request, but this a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
