### ISSUE TITLE
Better documentation for Config Entries

### ISSUE THREAD

**Issue by audiocustoms** [acemod/ACE3#1912]
I would love to see a better documentation of Config Entries (http://ace3mod.com/wiki/development/ace3-config-entries.html), what they do, how to set them up (values) and some examples. Would be helpful for implementation in CUP

**Comment by SzwedzikPL** [comment]
+1

**Comment by alganthe** [comment]
ganthe reporting for duty

**Comment by alganthe** [comment]
This can be closed, the framework documentation pages covers what was asked on this issue.
