### ISSUE TITLE
ACE causes dedicated server crash loading Altis

### ISSUE THREAD

**Issue by oatemeal** [acemod/ACE3#1925]
Server was running fine up until about a week ago with no issues. Now whenever loading Altis with vanilla missions or even just a mission with 1 unit if ACE is loaded the server will crash. No changes were made to the server, we were just changing from one mission to another.

This only happens on Altis, other maps load fine, and this only happens with ACE included. I have tried deleting the ACE folder and reinstalling however this has not fixed it. I have also tried verifying the game files on the server and also deleted the Altis pbo files and reinstalled them, nothing seems to fix it.

I have uploaded an archive with the rpt and dmp files which you can get here https://www.dropbox.com/s/dfxm9couz0xr2ii/acealtiscrash.rar?dl=0 any help would be appreciated.

**Comment by PabstMirror** [comment]
Version 3.1.1

I'm really not sure what the problem could be.


Could you try deleting all of the .dll files in the \@ace\ folder.  They shouldn't be needed on a dedicated server.  And see if you can get a mission loaded.

**Comment by oatemeal** [comment]
Thanks for the reply just tried this but it's still crashing at the same part.

**Comment by Glowbal** [comment]
Could you try with the latest version we released yesterday? Version 3.2.0.

**Comment by oatemeal** [comment]
It seemed to work, when I added back on some other mods it started crashing again so I am going for a full reinstall of Arma and all mods.

**Comment by bux578** [comment]
> It seemed to work
