### ISSUE TITLE
dlls blocked by battleye

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#1926]
ACE3 master based on 6197a63188e30cee608af1da060cb6bdfd60aa3f

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
N/A

**Description:**
Battleye block the dlls http://puu.sh/jeR7R/c643141353.png

**Steps to reproduce:**
Launch Arma 3 and a mission with any ACE3 dependency, a window will appear showing that the dlls are blocked.

**Where did the issue occur?**
SP / MP listen

**RPT log file:**
http://pastebin.com/pWkrSjRr

**Comment by gienkov** [comment]
Since they introduced this we are forced to NOT use BE on our servers since shi*load of problems...

**Comment by alganthe** [comment]
which is not a solution for ACE3 getting them whitelisted would be better.

**Comment by ViperMaul** [comment]
This makes sense. 
But I wonder why I cannot reproduce the DLL blocking error.

**Comment by alganthe** [comment]
Do you run battleye with the game ?

**Comment by ViperMaul** [comment]
Yes I verified that I did this time. 
http://gyazo.com/9ecfdf56654a044e206972f0c8a93275
I create an MP listening server and host a mission and get boots on the ground. 

Anyway I already submitted the request. 
@alganthe Can you try again on your machine and let me know if they are still blocked?

**Comment by ViperMaul** [comment]
BattlEye Support emailed back saying our DLLs were already automatically whitelisted. 
So it should not be a blocking problem any longer. Let us know.

**Comment by alganthe** [comment]
Okay figured it out, you need to launch the arma 3 launcher first for battleye to update itself, if you launch it through command lines it doesn't give a fuck and doesn't update I'll add this to the wiki beause this is a very important thing to know.
