### ISSUE TITLE
Zip Ties

### ISSUE THREAD

**Issue by sagjangi** [acemod/ACE3#1927]
A thought on Zip Ties.

We had a situation last week where we wanted to zip tie someone but having them in a non-movable state and having to move them ourselves would have put us at a sever disadvantage.

What about having zip ties restrict certain actions instead of completely immobilizing someone?

Example.
1. Someone that has been zip tied can still walk and jog (but not run) on their own (maybe fatigue quicker?).
2. They cannot access inventories and their weapons are force holstered.
3. An icon indicates that they have been zip tied.
4. Someone that is zip tied has an action made available to break free. The percentage is extremely low and there is also a significantly higher percentage chance that there will be a visual indicator that they are trying to break free so that captors can notice it.
5. Maybe different levels of escape attempts. This way if someone does escape they can try the higher percentage escape option (simulates finding something to break free with). Higher percentage escape attempts have higher percentage visual indicators.
6. Now sure how to approach this with AI that is zip tied. Maybe the AI follows the captor and there are certain commands you can give a captor; "follow/stay", "sit/stand/kneel", "release/transfer" (allows another to take control of the AI hostage).

**Comment by kripto202** [comment]
if you want to request a feature, please comment on #414. This has been talked over multiple times and it would have to take animating the the whole stance which not very many people have time to work on that. This may be worked on in the future, but they still have to get the core things down first.

**Comment by sagjangi** [comment]
Will kripto. Thanks

I wasn't suggesting new animations. I know those are really time intensive.

**Comment by PabstMirror** [comment]
These are some great ideas.  To be honest I just ported from AGM and I have no idea how to setup the anims.

I think it can be done in arma and maybe someone who understands animatiosn better can take a look.

Closing for #414

**Comment by sagjangi** [comment]
Yeah, that last match of Quarry got me thinking. Wish I knew how to code so I could contribute to stuff like this.
