### ISSUE TITLE
Parachute cutting and reserve parachute issues

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#1932]
ACE3 Version: 3.2.0 release branch

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
doesn't matter

**Description:**
The steerable / non steerable parachutes are missing interactions for the cutting furthermore if you run the function yourself the reserve parachute isn't applied

**Steps to reproduce:**
- Place a paratrooper in the editor
- Set his altitude at 1 000 m
- Click preview
- Open the parachute and try to cut it
- Press escape and enter ```[player] call ace_parachute_fnc_cutParachute;```
- Press enter and notice that the reserve parachute isn't applied

**Where did the issue occur?**
Editor

**RPT log file:**
nothing in there

**Comment by bux578** [comment]
@jokoho48

**Comment by jokoho48** [comment]
i am on it

**Comment by alganthe** [comment]
fixed in #1933
