### ISSUE TITLE
Switching combat pace while sitting breaks sitting

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#1937]
ACE3 Version: 3.2.0 prerelease

**Mods:**
* @cba_a3
* @ace3
* tfar
* rhs

**Placed ACE3 Modules:**

**Description:**
When sitting and pressing "c" (default for combat pace) lets you stand up with the rotation limitation still applied

**Steps to reproduce:**
* sit on chair
* press "c"

**Where did the issue occur?**
Multiplayer

**RPT log file:**
n/a

**Comment by bux578** [comment]
@jonpas

**Comment by jonpas** [comment]
Can you still use self-action "Stand Up"?

**Comment by bux578** [comment]
haven't tested this again @jonpas

**Comment by jonpas** [comment]
Ok no issues, I am going to modify `CfgMoves` and use config values to limit things, will also get rid of the PFH that way (or should be able to at least) and all the bugs should be resolved (even the one that lets you spam grenades while sitting, shhh).
