### ISSUE TITLE
Standing near a campfire hurts the player

### ISSUE THREAD

**Issue by Ligthert** [acemod/ACE3#1941]
I've had this when using ACE3, basic medic and playing on A2 maps. When ALiVE Civilians put down civies with a burning campfire the civie is fine, but the player slowly starts bleeding before dying.

I am not sure which type of campfire ALiVE uses, but I assume its the default A3 campfire. So it should work on non-A2 maps.

Uploading video now, should have some youtube link in the morning.

**Comment by Glowbal** [comment]
It's a known issue. For whatever reason the handleDamage event is being triggered many times a second while standing next to a camp fire, even when standing multiple meters a way.

**Comment by Ligthert** [comment]
http://feedback.arma3.com/view.php?id=2728
http://feedback.arma3.com/view.php?id=4447

Grate fun :(

This is going to be a hard one to crack. On one side you can block damage coming from a blacklisted object or class, but on the other side you want to punish foolish players who walk through fires. This sounds like a whole lot of extra if-statements in the Damage EH that could potentially lag the game.

**Comment by bux578** [comment]
@Glowbal anything we can do about it?

If not can we close this issue?

**Comment by Glowbal** [comment]
@Ligthert pretty much summed it up. We can do something about it, but it may not be worth it. I'd require some more investigation. I will take another shot at this soon. In CSE I pretty much disabled all fire damage, it might be an option to do the same here.

**Comment by MrSanchez** [comment]
I'd rather have fire damage disabled than no fireplaces/campfires at all...On my end if a player goes within 3-4m of a campfire/fireplace he will be instantly unconscious (preventing insta death module tho)

**Comment by Ligthert** [comment]
Thinking about this issue the world punishment comes to mind.

On one hand I think all firedamage should be disabled. Players are being punished (and killed) for something they don't have control over, nor really makes sense that one gets punished for being near (not even close or on top, near) a campfire. This is something we would normally do when we are in the wild or having a barbeque. You don't expect to burn a limb to death for flipping burgers.

On the other side I do think players should be punished when walking over a campfire. With boots or shoes running past or jumping over it is fine. But standing on it should punish somebody for their stupidity.

All things considered I would opt for the former and disable (camp)fire damage for now. Since it serves nobody (except the sadist mission maker) and only hinders players in what is otherwise just simple enjoyment or immersion of the game.

**Comment by Knight1981** [comment]
Same issue here. I placed a fire place (camp fire) and we died 3m away because of the fire :-(

**Comment by Glowbal** [comment]
This seems to be a much smaller problem as in previous versions. The handleDamage triggers still when standing only near it, but the damage appears to be 0 until you stand almost right on top of it or on top of it.

**Comment by Ligthert** [comment]
Standing ~4 meter from a regular campfire hurts the player. While this is close, this is no where near "on top".

**Comment by blackwatchint** [comment]
The bug stopped occuring after updating from 3.2.1 to 3.3.2

**Comment by PabstMirror** [comment]
I think this may have been fixed a while back
I can stand directly on a campfire and nothing happens,
It still spams handleDamage with very small amounts of structural damage.

handleDamage_caching filters out selection `""`, so the damage doesn't do any pain/bleeding/hitpoint damage.

And caching also keeps doing `_unit setDamage 0;` which will clear any of the little damage in.

So I think this can be closed..... and I guess you could make a bug report that ace blocks campfire damage :smile:
