### ISSUE TITLE
Other Interaction: Option to be single point from center/torso

### ISSUE THREAD

**Issue by Tanis1973** [acemod/ACE3#1942]
Can we get the option in settings to have the "other interaction" work the same as "self interaction"?  So there is only one starting point for the radial or list menu.  

Self interaction is very smooth, where as other interaction is painful.  Having to hunt around a person to find the sweet spot to be able to interact with various body parts is tedious at best and impossible at times depending on the position of the person and other objects.  Having it as an option would be nice cause some do like the "immersion" aspect of it, but for the most part it just gets in the way of an otherwise good system.

**Comment by bux578** [comment]
Thank you for your request, but this a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
