### ISSUE TITLE
Slideshow should have failsafes when interaction is not present

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#1945]
This is more of a note for myself, but also one question, `ace_slideshow` doesn't require interaction, as you can set it to run automatically which doesn't add the actions and therefore no function to `ace_interaction` is called. Should I just add an if check for CfgMods (or whatever it's called) or is there another way this should be handled?

**Comment by PabstMirror** [comment]
`isClass (configFile >> "CfgPatches" >> "ACE_interact_menu")`

If that isn't present, you would probably want to have a failsafe number for durration if it's set to the default 0.

**Comment by PabstMirror** [comment]
And the actions only show on the server (didn't test, but probably won't work on dedicated)

`FUNC(createSlideshow)` is only called from the server module.
`EFUNC(interact_menu,addActionToObject)` only has local effect

Probably want to run the module gloably and just seperate out the code that needs to be only run on server.

**Comment by SilentSpike** [comment]
You can use EFUNC(common,isModLoaded) to neatly check for CfgPatches classes :)

**Comment by jonpas** [comment]
If someone can confirm the bug that'll be great (no access to PC for a couple more days). 

Thanks @SilentSpike !
