### ISSUE TITLE
Medical System: A bullet affects all body parts even if hit on a leg

### ISSUE THREAD

**Issue by L0rn1x** [acemod/ACE3#1946]
bug only in ver 3.2.0, not present in ver 3.1.1

wherever you hit with a bullet, all parts of the body are red and you have to use 12 bandages to heal the unit.
(also the unit most of the times revives on his own: affected players and bots)

VIDEO: 
https://www.youtube.com/watch?v=yQOMNofptAM&feature=youtu.be

Settings

class ace_medical_level {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_medicSetting {
    value = 1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_enableUnconsciousnessAI {
    value = 2;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_preventInstaDeath {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_medical_enableRevive {
    value = 2;
    typeName = "SCALAR";
    force = 0;
};
class ace_medical_maxReviveTime {
    value = 7200;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_amountOfReviveLives {
    value = -1;
    typeName = "SCALAR";
    force = 1;
};
class ace_medical_keepLocalSettingsSynced {
    value = 1;
    typeName = "BOOL";
    force = 1;
};

**Comment by rebelvg** [comment]
Yeah, same as my ticket here. https://github.com/acemod/ACE3/issues/1888

**Comment by gienkov** [comment]
Can't repro all good here.

**Comment by rebelvg** [comment]
What can possibly be wrong on our side? What variable can we watch to check if something's wrong. Because I tried first official build of ace and medical there works fine. But after 3.1.1 something went wrong and it's not working for me.

**Comment by Dorbedo** [comment]
the same issue occurs on our server.
basic medical enabled + revive.
Our settings: http://pastebin.com/WaThhr5X

**Comment by L0rn1x** [comment]
Video is taken in a local session on my PC
But the same happened in our server with a mission that had no problem with version 3.1.1
So i don't think it's something related with mod or wrong settings of ACE3 on our side

.rpt file shows no error

@gienkov  what are your settings? Can you try ours (basic medical enabled + revive)

**Comment by L0rn1x** [comment]
Maybe...
something related to line 115 of file fnc_handleDamage.sqf

if preventInstaDeath == true && _damageReturn < 0.9

In 3.1.1 exits with: _damageReturn min 0.89
In 3.2.0 exits with: 0.89

so in 3.2.0 if damage is very small the functions exits always with damage 0.89, near to death

**Comment by Jastreb** [comment]
Is this fixed and can we expect 3.2.1 cuse this is critical bug for most of the players? Pl0x

**Comment by SzwedzikPL** [comment]
> Is this fixed and can we expect 3.2.1 because this is critical bug for most of the players?

:+1:

**Comment by rpgkayak** [comment]
I see this was added as a milestone for v3.2.1 and was curious if you could offer any estimate on a timetable for when that version might be available? I'm new to the development environment, so I don't know how long this sort of thing takes. Thanks in advance!

**Comment by MrSanchez** [comment]
http://gyazo.com/a5d0961d1b549f535528e594cd6bceee

You prepare for an op, spend 5+ hours making an operation...finally playing it...30 mins into an op and dead because of ACE glitch....In this case, a friendly crashed helo, pilot still alive inside..I approach it and...dead :(

Please update soon or I'll be forced to remove ACE3 from our modpack temporarily :(

Kind regards,
Sanchez

**Comment by austinjames314** [comment]
Really hanging out for this hotfix to come out guys. We're now Zeus-ing in medical crates mid mission, resulting in scenes like this:
![Image of Medical glitching](http://www.anztac.com/uploads/monthly_2015_08/2015-08-02_00012.jpg.a2f452dd27b2137d9827080b250d6049.jpg)

**Comment by jonpas** [comment]
:grin:

**Comment by rebelvg** [comment]
Either I'm doing something wrong or it's not fixed in 3.2.1.0.

**Comment by SilentSpike** [comment]
@rebelvg Are you using the basic medical system?

**Comment by rebelvg** [comment]
@SilentSpike Yes.

**Comment by Glowbal** [comment]
@rebelvg please provide your ACE settings and the repro steps.

**Comment by rebelvg** [comment]
@Glowbal Can you clear something for me? Is it intended that after soldier is unconscious (with prevent death enabled) and there's no revive system enabled he'll die after next shot and all his bones will go red?

**Comment by PabstMirror** [comment]
As I understand the code:

Prevent instant death just prevents someone from taking lethal damage from a single event.
So, a guy gets hit with a headshot that would normally kill him, instead he will instead just fall unconscious.

That "immunity" goes away once they are unconscious.  And they will already be heavily wounded.  So it is likey that any more damage will kill them.

A feature you might be intersted in is the "Revive Settings" module.

That will allow someone to continue to be immune when unconscious and make them "unkillable".

**Comment by rebelvg** [comment]
@PabstMirror So destroyed bones just indicate that unit can't be revived and is completely dead? And about the revive option. It appears that only medics can revive using epi on normal medical. And another small thing on advanced. When you look at a body part that was damaged it says "No damage on this part" in the left upper corner for some reason.
