### ISSUE TITLE
Script errors / popups when using NLAW without disposables module

### ISSUE THREAD

**Issue by captainblaffer** [acemod/ACE3#1947]
ACE3 Version: 3.1.1

Mods:
@CBA_A3;@ace;

Placed ACE3 Modules:
none

Description:
When removing ACE disposable module from the addons folder, if any player shoots an NLAW, a popup message appears: No entry 'bin\config.bin/CfgWeapons.ACE_launch_NLAW_Used_F'.
In the RPT are other error messages related to disposables as well.

Steps to reproduce:
1. Remove ace_disposable.pbo from ACE addon folder.
2. Load a mission featuring NLAW in dedicated (didn't test SP)
3. Fire NLAW.

Where did the issue occur?
Dedicated

RPT log file:
https://drive.google.com/file/d/0B-pcqje99exHYzFMekhkSjZ3aGs/view?usp=sharing

**Comment by PabstMirror** [comment]
The only reference to `ACE_launch_NLAW_Used_F` is within ace_disposable.pbo.

I think the only way that error could happen is if someone else on the server was running with that pbo.
Or possibly if a mission made reference to that weapon classname.

If I remove ace_disposable, and shoot a NLAW, I don't get the error.

Can you try and verify that no one else was running the disposable.pbo?
There is an ACE "Check PBOs" module that should be able to kick anyone running the wrong mods.

**Comment by captainblaffer** [comment]
Thanks for your reply, I'll try to test again, making sure no one has the PBO. There is a high probability people did have the PBO when I encountered this issue first.

**Comment by Glowbal** [comment]
> If I remove ace_disposable, and shoot a NLAW, I don't get the error.

Can't reproduce.
