### ISSUE TITLE
Config export exports addon whitelist with single quotes, causing server to crash

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1948]
ACE3 Version: 3.2.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Check addons*

**Description:**
It is said that if you want to whitelist some addons (for this example while checking only ACE ones on serverside - standard settings) you must write them down inside this module like this:
``` ["ADDON1", "ADDON2", ...] ```

and when you click Export inside Config Export Menu then you will get this:

```
class ace_common_checkPBOsWhitelist {
    value = "["ace_tracers"]";
    typeName = "STRING";
    force = 1;
};
```

and guess what? Quotes. They will crash the server (cause error inside userconfig) if you leave it like this.
Should be:

```
class ace_common_checkPBOsWhitelist {
    value = "[""ace_tracers""]";
    typeName = "STRING";
    force = 1;
};
```

**Note double quotes.**
But guess what?
Script is made so it doesn't accept double quotes, when I entered them on my server like above then I got this:

![error](http://i.imgur.com/MTBxZ7L.jpg)

So it wants it in format written inside module manual. But you can't use it. You are doomed.

**Steps to reproduce:**
* *Try to whitelist an addon following Check Addons module manual.*
* *You can't*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
*-*

**Comment by Glowbal** [comment]
This probably requires two things:
- Overhaul the whitelist/blacklist functionality. `[]` is also not really useful to include. either
- Adjust the export functionality to work with array values.

**Comment by jonpas** [comment]
> `[]` is also not really useful to include. either

For backwards compatibility, both should work still, should be fairly easy by just checking the input type.
