### ISSUE TITLE
You can use self interaction menu inside Zeus

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1949]
ACE3 Version: 3.2.0 https://github.com/acemod/ACE3/commit/4f07d1c7ee3af85170e805ff8f2bbbc52a7787cd
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Zeus*

**Description:**
*You can use self interaction menu inside Zeus interface. If you start switching between self interaction menu (LCTRL+WIN) and standard interaction menu (LWIN) you can bug both menus and they both will stop working inside Zeus.*

**Steps to reproduce:**
* *Play around with self interaction/normal interaction menu inside Zeus interface.*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
*No script errors*

**Comment by PabstMirror** [comment]
I'm not entirely sure whats going on.
```
while {dialog} do {
    closeDialog 0;
};
```
runs for 10,000 cycles and doesn't actually close the dialog (I think this might be a zeus thing?)

I think we can just switch from the dialog to the same method we use normaly:

https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_keyDown.sqf#L59
Change
`createDialog QGVAR(cursorMenu);`
to
`(findDisplay 312) createDisplay QGVAR(cursorMenu);`

**Comment by SilentSpike** [comment]
That's the way it was done originally but it was changed in favour of preserving the zeus interface in the background. This will be fixed once we figure out a better method of handling keybinds in specific dialogs.

**Comment by SilentSpike** [comment]
Fixed in #2216
