### ISSUE TITLE
[Edit] Increase interaction distance for sitting

### ISSUE THREAD

**Issue by havena** [acemod/ACE3#1950]
ACE3 Version: 3.2.0 release
(indicate if stable or dev, if dev indicate the commit the version is based on)

Mods:

@cba_a3
@ace3

Placed ACE3 Modules:

ACE_ModuleCheckPBOs
ace_advanced_ballistics_ModuleSettings
ace_winddeflection_ModuleSettings
ACE_ModuleMap
ACE_ModuleExplosive
ace_finger_moduleSettings
ACE_ModuleInteraction
ACE_ModuleSitting
ACE_ModuleHearing

Description:
civilian/indepedant side can't sit.
only west side player can sitting.

Steps to reproduce:

place ACE_ModuleSitting and try to sit on a chair

RPT log file:
No script errors

**Comment by havena** [comment]
ok, i find an eventhandlers on C_man_1 in my mod.... i will fix it

**Comment by bux578** [comment]
![150730_twodudes](https://cloud.githubusercontent.com/assets/1235520/8980520/9858f752-36b1-11e5-92a1-4d23aabe7469.jpg)

**Comment by alganthe** [comment]
I highly doubt that you only have ace3 and cba running.

**Comment by havena** [comment]
its work.. but i need to I need to squat down in civilian to see action?!

**Comment by havena** [comment]
in fact, we need to squat down when u dont have a weapon in hand :)
thats why i dont find it in civilian...

**Comment by jonpas** [comment]
That's probably due to very small distance, I think it's set to 2m.  I'll up it a bit so it'll work nicely without weapons as well. 

Thanks for reporting!

**Comment by bux578** [comment]
so @jonpas ... let the fixes flow ... ;)

**Comment by jonpas** [comment]
I will when I am back at my PC (in 6 days). ;)
