### ISSUE TITLE
Mission failed with message "ace_fonts.pbo version outdated" on Windows 10

### ISSUE THREAD

**Issue by macchky** [acemod/ACE3#1953]
```
22:50:51 [ACE]: ACE is version 3.2.0.0.
22:50:51 [ACE] ERROR: File ace_fonts.pbo is outdated.
22:50:52 [ACE] Extension version: ace_break_line: 3.2.0-bf4e95e
22:50:52 [ACE] Extension version: ace_parse_imagepath: 3.2.0-bf4e95e
22:50:52 [ACE] Extension version: ace_clipboard: 3.2.0-bf4e95e
22:50:53 [ACE] Extension version: ace_fcs: 3.2.0-bf4e95e
```
On Windows 10 , arma3 may can not take ace_fonts.pbo version.

So I removed ace_fonts.pbo, I can play mission.

**Comment by ViperMaul** [comment]
Please follow the [guideline on how to report issues](http://ace3mod.com/wiki/user/how-to-report-an-issue.html) 

We have had sessions with players on Windows 10 using ace_fonts.pbo with no problems yesterday. 
We need more information.

**Comment by macchky** [comment]
Launch by Run as Administrator fixed issue.
