### ISSUE TITLE
Advanced Ballistics is killing client FPS when firefighting and after it, FPS doesnt come back up

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1962]
ACE3 Version: 3.2.0

**Mods:**
* https://docs.google.com/spreadsheets/d/1OTjYgUqxEnQsQBAfgwmjbThDZ3unG21H1jfGkZEwO00/edit?pli=1#gid=0

**Placed ACE3 Modules:**
* *http://pastebin.com/yh8vYcGd*

**Description:**
*http://pastebin.com/yh8vYcGd*

**Steps to reproduce:**
* *Placed about 30 enemy AI*
* *FPS is ~40*
* *Start firefight and killing them*
* *FPS drops*
* *Killed all AI, FPS is 16, doesn't come back up even when I respawn and delete dead bodies.*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
*Needed?*

**Comment by gienkov** [comment]
After some investigation it seems that Advances Ballistics is an issue there, because every shot creates one PFEH which doesn't get deleted at all. It comes to very high numbers, managed to get 800 PFEH running and 5 FPS...

**Comment by kripto202** [comment]
The same type of problem happened with blue force tracker. I wonder if there are other systems in ace that doesn't delete the data. That should be looked over.

**Comment by ViperMaul** [comment]
@gienkov 
As a quick troubleshooting step, can you retest using the AB.DLL from 3.1.1 and report any differences?

**Comment by jokoho48** [comment]
@ViperMaul it look like that AB add per Shot a PFH and dont delete it after the bullet is stoped(results from Slack)

**Comment by gienkov** [comment]
@jokoho48 exactly

**Comment by Cathlamet** [comment]
We got bit harrrrrd by this tonight with ~30 players on co-op.  Thanks for the report on this and prompt attention by the devs.

**Comment by Glowbal** [comment]
Should be resolved by #1967
