### ISSUE TITLE
Unconscious units wake up after 10 seconds regardless of ACE settings

### ISSUE THREAD

**Issue by rpgkayak** [acemod/ACE3#1964]
ACE3 Version: 3.2.0
(stable)

**Mods:**
* @cba_a3
* @ace3
* RHS Escalation
* Leights OPFOR
* AllinArma Terrain Pack
* Task Force Arrowhead Radio
* ALiVe
* @mad_resh (Reshmaan province map)
* @mad_build (Reshmaan dependency) 

**Placed ACE3 Modules:**
* Interaction, Medical Settings, Revive Settings.*

**Description:**
* If a unit becomes unconscious, whether through damage or scripting commands, they will awaken after approximately 10 seconds.*

**Steps to reproduce:**
* Start a game in the editor or on a multiplayer server. Place one unit of any faction. Use the ACE module in Zeus to Toggle Unconscious. The unit will enter the unconscious state for roughly 10 seconds, then stand up. Additionally, place two infantry squads from opposing sides in line of sight of one another. As they fight, some will be knocked unconscious. Observe that unconscious units awaken after just 10 seconds of unconsciousness.*

**Where did the issue occur?**
*Editor, Multiplayer server*

**RPT log file:**
*N/A*

**VIDEO**
http://youtu.be/V9zl0ZKnNPo

**Comment by SilentSpike** [comment]
Ah, thank you for reminding me to fix this :+1:

**Comment by SilentSpike** [comment]
Actually, I know what the problem is with the zeus module. @Glowbal should probably check out the other stuff.

**Comment by rpgkayak** [comment]
FYI - no Zeus module is in use. The editor uses single player as the curator and we have removed the Zeus module from multiplayer missions because of the conflict with ACE v3.1.1. Thanks for jumping on this so quick!

**Comment by SilentSpike** [comment]
I should have clarified :smile:  I can fix the toggle unconscious module behaviour

**Comment by Cyruz143** [comment]
Having this with players too, @SilentSpike  this the same issue or do you want me to make another one.

**Comment by SilentSpike** [comment]
I've fixed the zeus module, other unconscious behaviour is @glowbal's domain so he should probably answer that

**Comment by galevsky** [comment]
Hi all,

any news about it ?
This issue is the most important weird behaviour for my point of view (thus surprised to see that it is considered as a feature by others) and I am ready to help if possible (test, code, whatever...). 
Is it possible to disable no-epi wake-up via parameter at least, if some guys require the feature ?

Thank you for all your efforts :)

**Comment by Glowbal** [comment]
#2361
