### ISSUE TITLE
Ace_medical.dll blocked by Battleye, problem yes/no?

### ISSUE THREAD

**Issue by MrSanchez** [acemod/ACE3#1966]
http://gyazo.com/1d7e7c6838e6187836f6fd51eb370013

Will this cause problems? What is the dll file used for?

Kind regards,
Sanchez

**Comment by PabstMirror** [comment]
Are you starting the game through steam and the Arma Launcher app?
I believe you have to do that to update battleEye, which should then allow the dll to load.

**Comment by PabstMirror** [comment]
From #1926
>Okay figured it out, you need to launch the arma 3 launcher first for battleye to update itself, if you launch it through command lines it doesn't give a fuck and doesn't update I'll add this to the wiki beause this is a very important thing to know.

**Comment by MrSanchez** [comment]
I used play withSix to launch my game. After updating Battleye doesn't seem like the issue is still here.

I do wonder what ace_medical is generally responsible for though, yesterday we had an operation and (tbh I didn't notice any errors at that time) the medical system was kinda f*ed up. If you'd get shot once, every part of your body would be injured. Trying to bandage them, using more than 20 bandages (Basic system btw) yet still bleeding..Is it related at all to ace_medical.dll not working back then?

Kind regards,
Sanchez

**Comment by MrSanchez** [comment]
Woah what..I just updated Battleye...went into game....actually booted up a mission and got kicked out

http://gyazo.com/993c6f72aef2b7247dd5c9492463bb15

**Comment by MrSanchez** [comment]
After manually installing the battleye update I was able to play...weird stuff..never been a big fan of Battleye.

http://www.battleye.com/downloads/
