### ISSUE TITLE
Question: Which PBO does change the compass?

### ISSUE THREAD

**Issue by KGBCartman** [acemod/ACE3#1973]
I play Iron Front on A3 with ACE and I want to keep the old compass, but I couldn't find the PBO that changes it.

It would be nice if someone could point me in the right direction ;).

**Comment by PabstMirror** [comment]
I think it's "ace_map.pbo" that modifies the compass:

As far as I can tell it doesn't modify it besides changing size.

```
    // scale up the compass
    class objects {
        class Compass: RscObject {
            scale = 0.7;
            zoomDuration = 0;
        };
    };
```
