### ISSUE TITLE
Inventory: No Weight, no Name, no Rank

### ISSUE THREAD

**Issue by Blackswater** [acemod/ACE3#1975]
ACE3 Version: 3.2.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
any modules placed

**Description:**
If I press I (Inventory), I can't see my weight or name or rank. 

**Steps to reproduce:**
Press I (Inventory)
Look at the top

**Where did the issue occur?**
Multiplayer and Singleplayer

**RPT log file:**

**Comment by PabstMirror** [comment]
It should be working fine.
Could you please include a RPT file (can be found in `%localappdata%/Arma 3/` and look for the most recent file like` arma3_2015-08-01_22-17-40.rpt` and dump it on pastebin.com)

**Comment by Th3Cr0w** [comment]
you have to disable "stream friendly ui" in gameoptions

**Comment by Blackswater** [comment]
Guys, thank you very much. I didn't know that I must turn of the "Stream friendly UI". Now everythings works fine!

**Comment by SilentSpike** [comment]
Glad to hear you found the cause :+1:

**Comment by xJenny99x** [comment]
Can this not be fixed at all? I really hate to see disconnected and connected messages so I play with friendly UI, but that's why I can't see the weight in inventory screen. :0
