### ISSUE TITLE
Cannot use Ctrl+C and Ctrl+V in Zeus

### ISSUE THREAD

**Issue by Kilo1-1** [acemod/ACE3#1979]
ACE3 Version: 3.2.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None*

**Description:**
*Since the new 3.2.0 update, you cannot use Ctrl+C and Ctrl+V to copy and paste Zeus entities/objects/etc.*

**Steps to reproduce:**
* Open up Zeus and try to use Ctrl+C and Ctrl+V.  It will say you cannot climb here.

**Where did the issue occur?**
*Both Singleplayer and Multiplayer*

**RPT log file:**
*Don't have one at this time but if needed I will get one*

**Comment by SilentSpike** [comment]
Hey, already reported, but thank you :)

#1951

**Comment by Kilo1-1** [comment]
What about CTRL+C?  Is it the same issue?

**Comment by SilentSpike** [comment]
Yep, both caused by the same thing

**Comment by Kilo1-1** [comment]
Alright, good to hear.  Thanks for info.
