### ISSUE TITLE
Can't turn combat deafness off with Hearing module.

### ISSUE THREAD

**Issue by Alextwokay** [acemod/ACE3#1981]
ACE3 Version: 3.2.0
(stable)

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Hearing*

**Description:**
*Turning combat deafness off doesn't eliminate beeping/rumbling and earplugs are needed anyway.*

**Steps to reproduce:**
* *Fire a few shots with an XM312.*

**Where did the issue occur?**
*Editor and Dedicated server*

**RPT log file:**
*N/A*

**Comment by PabstMirror** [comment]
There are 2 settings, combat deafness (set via module or manual ace_settings) and disable ear ringing which is client settable.

Ear Rining will still happen even if combat deafness is off.  Which might not be clear.

Could you check your client ACE Settings for "Disable ear ringing" and make sure it is enabled and see if you still get any ringing when shooting.

**Comment by Alextwokay** [comment]
That will be it then, this behaviour is different from last patch and seems a bit more unclear.
Having the option to force disable both in the module would be good.

**Comment by MrSanchez** [comment]
Hope we'll be getting an option to force disable both.
