### ISSUE TITLE
Hearing loss is not aggressive enough (who needs earplugs?)

### ISSUE THREAD

**Issue by voiperr** [acemod/ACE3#1987]
ACE3 Version: 3.2.0

**Mods:**
- @cba_a3
- @ace3

**Placed ACE3 Modules:**
None

**Description:**
Currently, ace_hearing is wonky in its depiction of firearm-related hearing loss. Originally, in 3.0.0, a heavy caliber round would instantly drop you to about 50% deafness. With 3.2.0, it takes a far too much exposure to lose significant (noticeable) volume.

This is how 3.2.0 treats hearing with no earplugs and no helmet:

https://www.youtube.com/watch?v=Iki9QTIbBdo

A .338 Mag round (likely at least 160 dB) fired without hearing protection should instantly trigger the acoustic reflex, and thus result in lowered volume. Instead, it takes 30+ rounds to reach a 50% reduction in volume (~3 dB change in hearing; about the effect of the acoustic reflex).

A 9mm pistol round can be between 150-160dB and has a very high frequency report, and thus can be even more dangerous to hearing than some rifles. Right now you can't even fire fast enough to have hearing loss, since the hearing recovers before you've finished reloading.

For reference, the acoustic reflex is triggered around 70-100 dB (https://en.wikipedia.org/wiki/Acoustic_reflex). The ballpark for hearing damage starts at 140 dB (http://www.asha.org/public/hearing/Recreational-Firearm-Noise-Exposure/). Most guns fire at 150 dB or greater (http://keepandbeararms.com/information/XcIBViewItem.asp?ID=2052).

For gameplay reasons, it's understandable to have some leeway/unrealism with hearing loss (many missions involve insurgency units with no hearing protection, and permanent deafness is a gameplay killer). But currently in some situations hearing protection isn't even needed--as long as the player waits enough between shots, they'll never get noticeable hearing loss. It's also vastly inconsistent: pistols have no meaningful or persistent effect on hearing loss (they really, _really_ do irl), and large/high velocity calibers must be fired many times to have any noticeable effect.

First, I suggest that the instantaneous loss of volume simulated by the acoustic reflex should be brought back. This can be accomplished by adjusting 
`_loudness = (_caliber ^ 1.25 / 10) * (_initspeed / 1000) * _audibleFireCoef / 5;`
in https://github.com/acemod/ACE3/blob/master/addons/hearing/functions/fnc_firedNear.sqf to some desired level (I'm not sure which value is best to modify).

Further, if realism is the goal, I think hearing loss should follow an inverse logarithmic scale: at first, there is a lot of volume loss (to about 50-60%) accompanying damaging levels. It then takes a significant amount more trauma to reduce it further. Very, very loud spikes (explosions, rockets) should be the exception, and cause deafness for a few minutes.

**Comment by NouberNou** [comment]
Due to the fact that the values used to calculate loudness can vary across mods in a way that is not consistent its hard to get this feeling right. I do like the acoustic reflex stuff.

**Comment by Glowbal** [comment]
This has since been rewritten. #3279
