### ISSUE TITLE
Spall enabled often cause script error and framedrop

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#1990]
ACE3 Version: 3.2.0

**Mods:**
* https://docs.google.com/spreadsheets/d/1OTjYgUqxEnQsQBAfgwmjbThDZ3unG21H1jfGkZEwO00/edit?pli=1#gid=0

**Placed ACE3 Modules:**
* http://pastebin.com/4FL6sN8S

**Description:**
Shooting some heavy machineguns at buildings will sometimes cause framedrop and script error like below (it's on SMD Sahrani):
https://youtu.be/Y6yfELzyXEE

**Steps to reproduce:**
* *Enable spall and start shooting from MGs to buildings

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
https://www.dropbox.com/s/1h890uz3e9b5ppm/arma3_2015-08-03_02-27-02.rpt?dl=0

**Comment by commy2** [comment]
Dup of #2351. Closing this cause the other one has more activity.
