### ISSUE TITLE
APERS Bounding Mines don't Dig In

### ISSUE THREAD

**Issue by JoshBlack8923** [acemod/ACE3#1991]
ACE3 Version: 3.2.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None

**Description:**
APERS bounding mines placed by units don't sink in to the ground. Yet, explosives placed in the editor do.

**Steps to reproduce:**
Load a unit with an APERS Bounding mine, place, then arm the mine.

**Comment by alganthe** [comment]
Same here ACE 3.2.0 stable
