### ISSUE TITLE
Helicopter crew takes damage on vehicle bullet hit 

### ISSUE THREAD

**Issue by gsteiner89** [acemod/ACE3#1992]
ACE3 Version: 3.2.0.0 (stable)

**Mods:**
@cba_a3
@ace3

**Placed ACE3 Modules:**
Medical Settings

**Description:**
Every bullet hit on helicopter hull will do damage on crew and kill the crew inside.

**Steps to reproduce:**
Step 1: Open editor from main menu
Step 2: Place the "Medical Setting" module
Step 3: Edit the "Medical Setting" module
Step 3-1: Set "Prevent instant death" to Yes
Step 4: Add a player unit
Step 5: Add a CH-47I-Chinook
Step 6: Start mission
Step 7: Shoot on the hull of the Chinook
Check: Now all crew members should die.

**Where did the issue occur?**
Single and Multiplayer

**RPT log file:**
No log sorry.

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by dvdbrewster** [comment]
I noticed playing CTI that MG hits on the BluFor Hunter hull create some blood splatter.

**Comment by Jastreb** [comment]
I noticed something similar in ace3 3.2.0 with medical bug being a pest. A vehicle would also get all hitpoints red, as well as player on a small injury. Something has to be with locality of the vehicle the player is owner of and medical system and hitpoints. Not sure what, but it looks connected.

**Comment by Glowbal** [comment]
Does this happen in any vehicle or only the `CH-47I-Chinook` ?

**Comment by gsteiner89** [comment]
Got the problem with several helicopters. Haven't tested it with other vehicles. Maybe its already fixed in version 3.2.1, change-log: "Incorrect damage was being applied with prevent death enabled"

**Comment by Jastreb** [comment]
This may have ben a bug in 3.2.0, I cant repoduce it with 3.2.1, but I was being reported that a vehicle would get all hitpoints red if a player is even slightly injured, so I thought how it may have been connected somehow. I run with Basic medical, someone try it with advnaced so we can be sure its not there at all. Before closing of course.

**Comment by dvdbrewster** [comment]
It does not seem very apparent in new vers. (3.2.1)  I cannot detect it anymore traveling in ground vehicles..

**Comment by gsteiner89** [comment]
I tested some setups with standard and advanced medical settings and cant reproduce it in 3.2.1. Seems fixed to me.

**Comment by Glowbal** [comment]
> Step 3-1: Set "Prevent instant death" to Yes

Most likely related to this.

> I tested some setups with standard and advanced medical settings and cant reproduce it in 3.2.1. Seems fixed to me.

Good to hear. Closing.
