### ISSUE TITLE
Wall Climbing no longer works properly

### ISSUE THREAD

**Issue by KRDucky** [acemod/ACE3#1995]
ACE3 Version: 3.2.0 Stable

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* Zeus

**Description**
I was testing climbing in the VR space using all the walls you can access via Zeus. It told me on almost every wall over knee height that I "Could not climb here". 

**Steps to reproduce:**
* 1. In editor or Zeus, place one of every type of wall on the map
* 2. Try to climb over each one

**Where did the issue occur?**
* Single

**RPT Log File**
* http://pastebin.com/vB3fLV0t

**Youtube Video demonstration**
* https://www.youtube.com/watch?v=VmYanrTK_Lg

**Comment by Glowbal** [comment]
I experienced some issues with this as well.

**Comment by BryanBoru** [comment]
half of those objects have never been climbable in my experience. I just assumed they were too tall.

**Comment by KRDucky** [comment]
I remember in BCT climbing over walls that were chest-shoulder height with fixed bayonet. So, they should not be too high. A nice addition to the function could be that if there is a buddy next to you you could use the Rose menu to choose and option to 'buddy-boost' over the taller walls.

**Comment by commy2** [comment]
Not a bug. Intended, because too high to climb.

**Comment by bux578** [comment]
always cleaning up after @commy2 :joy:

**Comment by MikeMatrix** [comment]
I feel you @bux578 :shipit:

**Comment by jokoho48** [comment]
on my side of view is this a Bug and not a by Design

**Comment by bux578** [comment]
Don't have problems with objects that are supposed to be climbable:
https://www.youtube.com/watch?v=gLxAzQscoXg

The height has to be that low because there are no proper animations that make climbing OVER A WALL look any decent or climbing ON TOP of a high object.

**Comment by jokoho48** [comment]
ok than as i said in Slack to Bux need this Feature a other Name and description

**Comment by BryanBoru** [comment]
that seems a bit extreme. should it be called 'shoulder high wall climbing'? or just 'climbing'?

**Comment by KRDucky** [comment]
It should be renamed to 'Mantling' from the Rock Climbing term: to Mantle. 

[Climbing Techniques Site] (http://www.climbingtechniques.org/intermediate-moves.html)
The technique to mantling is hidden in the title. Imagine you wanted to climb onto the mantle above the fireplace. You would get up close to it, pull yourself up, rock sideways, turn your hand around and push yourself up, until you could slip a foot onto the mantle and stand up. That is exactly what you do when mantling in rock climbing. Watch small children climb onto counter tops for inspiration. You can also mantle off smaller holds and ledges to get your feet higher. Mantling is particularly important in slab climbing and in dihedrals and chimneys. You will often get better purchase by turning your hand around. 

The main issue I have with the wall climbing part is that you can not climb over the rock walls that are found all over Altis and Stratis as shown in my video. I seem to recall Arma 2 or Arma 3 mods to allow climbing over walls. Here it is: It is called Enhanced Movement. And the video clearly shows and excellent animation for climbing the stone walls. 

[Enhanced Movement Video] (https://www.youtube.com/watch?t=40&v=sXHqc7O0fvs)

**Comment by commy2** [comment]
>on my side of view is this a Bug and not a by Design after this [9633547] commit the issues are Oclude

All this commit changed is that you have to have enough room for the head to climb. It prevents climbing through very small windows.
