### ISSUE TITLE
Can't open interaction menu

### ISSUE THREAD

**Issue by DeltaDawg117** [acemod/ACE3#1996]
I've reinstalled ACE 3 twice now, each a different way, but the problem persists. The truth is, I don't really know what's causing it. I don't know if it's even a problem with ACE. Everything else with the mod works fine for me, I just can't open the interaction menu. Not the self interaction, not the other interaction. I even went into the interaction menu pbo (truthfully, I had no idea what was going on there, but I think I found what I was looking for) and everything looked fine. Is this a bug? Or am I just incredibly stupid and missing some very obvious component or something. Oh and btw, I deleted all my AGM files once I downloaded ACE, in case you needed to know (I never downloaded CSE).

**Comment by PabstMirror** [comment]
* Could you please include a RPT file (can be found in %localappdata%/Arma 3/ and look for the most recent file likearma3_2015-08-01_22-17-40.rpt and dump it on pastebin.com)
* Do you get any indication that the interaction menu is opening (red circle in center)?
* Try rebinding the keys, by default they use the windows key, which may not work for some keyboards.
* Please try adding the CBA compat pbo, and make sure you are running the most recent version of CBA.

>We have noticed that when using ACE with 3rd-Party mods that do not fully support CBA Extended Eventhandlers (XEH) that some units do not work with Interaction fully. You may see the cursor but no menus.

>WORKAROUND: The latest CBA RC7 Hotfix 2, v1.1.23 has an optional PBO that you can activate to help resolve these situations. 
1. Move the cba_enable_auto_xeh.pbo and its signature file from the CBA optional folder to the CBA Addons folder
2. Restart Arma.

**Comment by DeltaDawg117** [comment]
Ok, I left the rpt file on pastebin - file:///C:/Users/Frederick/AppData/Local/Arma%203/arma3_2015-08-03_10-54-52.rpt - (idk if you need this I've never used pastebin) and no, I did not get any indication of the menu opening, i.e. the red circle. Even when holding the ctrl windows or just windows when I was near an npc didn't work. I was still moving and looking around and firing my gun while holding the buttons.

**Comment by MikeMatrix** [comment]
You've just linked us a local file. You have to copy the content to pastebin.com and then get the link to the pastebin and link that to us.

**Comment by DeltaDawg117** [comment]
http://pastebin.com/GSDsZkgR???

**Comment by DeltaDawg117** [comment]
Just updated my CBA. Problem persisted.

**Comment by MikeMatrix** [comment]
Link works fine now.

**Comment by MikeMatrix** [comment]
@DeltaDawg117 have you tried launching Arma with just CBA and ACE to see if the problem persists?

**Comment by PabstMirror** [comment]
You have external addons in your arma's \addon folder so it may be tough to isolate to just CBA and ACE.

Please try that and then post a RPT that includes loading into a mission

**Comment by jokoho48** [comment]
one small tipp after i see your what is in your Addons folder is reinstall ArmA

**Comment by DeltaDawg117** [comment]
@MikeMatrix Ok I removed everything from my addons folder and got this repeating "please wait" message with a loading bar that just kept going up and down.

**Comment by DeltaDawg117** [comment]
Or "wait a moment", rather

**Comment by PabstMirror** [comment]
Try validating the game in steam:

http://i.imgur.com/Wfwo8Su.png

**Comment by DeltaDawg117** [comment]
@PabstMirror So it will just re-install now?

**Comment by PabstMirror** [comment]
Yeah,  \addons contains the core arma files.  Steam will be able to replace everything that should be there.

It's a good practice to use the @folders because it makes it easy to organize and add/remove mods.

**Comment by DeltaDawg117** [comment]
@PabstMirror Arma re-installed, the interaction menu now works, although I would love to know which of my many, many mods was the problem. Any way to find out?

**Comment by MikeMatrix** [comment]
@DeltaDawg117 install them one by one and test after each one (Install them over @ folders so you don't have the same issue again and can update very easily)

**Comment by dbo5118** [comment]
Hi, 

Know this post has been dead for a while, but I am looking for this file in my optionals and its not there. nor is it in the addons folder. any ideas?

**Comment by MikeMatrix** [comment]
Hi,

Not really sure what you're talking about, especially when it comes down to a close to 7 year old issue ticket being necro'd back into existence.

Best to make a new ticket regarding your specific issue you're having.
Try also taking a look at [how to report an issue](https://ace3mod.com/wiki/user/how-to-report-an-issue.html).
