### ISSUE TITLE
Range Card, Kestrel 4500 and ATragMX not working.

### ISSUE THREAD

**Issue by 111Insats** [acemod/ACE3#2001]
Whilst me and a friend were trying to find out how to properly zero a sniper rifle, we found out we needed a Range Card, Kestrel 4500 and a ATragMX. Problem: Even if we re-bound their keys, they would not pop up.

**Comment by 111Insats** [comment]
Solution found: They can't be in backpack.

**Comment by bux578** [comment]
Glad, you found the solution.
