### ISSUE TITLE
Dead Mans Switch should detonate on going unconscious, not on death. 

### ISSUE THREAD

**Issue by Ataraxic89** [acemod/ACE3#2018]
Pretty simple and obvious. Can take minutes to actually bleed out. You cant hold down the switch when you are unconscious.

**Comment by PabstMirror** [comment]
@CorruptedHeart - This seems pretty reasonable to me.

Should be easy to hook into the medical unconc event, if you think this is a good idea.

**Comment by gienkov** [comment]
+1 activates on death and unconcious.
5 sie 2015 01:32 "PabstMirror" <notifications@github.com> napisał(a):

**Comment by pmc-tyler** [comment]
It worked like that in AGM as soon as you passed out it exploded. +1

**Comment by bux578** [comment]
It's rather a bug.
