### ISSUE TITLE
Feature Requet

### ISSUE THREAD

**Issue by SgtMStonebridge** [acemod/ACE3#2019]
Hello,

I think this mod is well deserved of it's reputation.

But I have a question about it. Would it be possible to add in the ability to do the following actions?

1. Wall cover
2. Breaching charges
3. Roll left and right with animations.

Would these be possible?

**Comment by jokoho48** [comment]
Hey please read this: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
And use This #414
