### ISSUE TITLE
Players go unconscious after taking one bullet

### ISSUE THREAD

**Issue by captainblaffer** [acemod/ACE3#2023]
ACE3 Version: 3.2.1

Mods:
@ace;@CBA_A3;

Placed ACE3 Modules:
none

Description:
Players go into unconscious state very fast when taking damage.  ~~Much faster compared to ACE 3.1.1~~ Much faster compared to default A3

Steps to reproduce:
1. Shoot a player in the leg or chest(bodyarmor) from 200m with 5.56 NATO rifle
2. Observe the player going unconscious
-- In default A3 a player will still be alive and functional after one shot.

.3. Shoot a player in the chest(bodyarmor) from 15m with 9mm pistol twice
.4. Observe the player dying. 
-- In default A3 a player will die after 4 pistol shots.

Where did the issue occur?
Dedicated

RPT log file:
http://pastebin.com/Xf4hFb3L

**Comment by Jastreb** [comment]
13:14:18 [ACE]: Warning in ACE_moduleMedicalSettings module: remoteControlledAI setting is missing. Probably an obsolete version of the module is used in the mission.

Way too much errors, check your mission and recheck ace modules and its settings. Also check if zou have compatiblity addons on both server and clients, for addons you run. They are to be found in @ace\optional\ folder

**Comment by austinjames314** [comment]
One of the guys in my clan is reporting exactly this as well.

**Comment by captainblaffer** [comment]
> 13:14:18 [ACE]: Warning in ACE_moduleMedicalSettings module: remoteControlledAI setting is missing. Probably an obsolete version of the module is used in the mission.
> 
> Way too much errors, check your mission and recheck ace modules and its settings. Also check if zou have compatiblity addons on both server and clients, for addons you run. They are to be found in @ace\optional\ folder

That error in the RPT showed up in a mission played before we played the mission where we noticed the issues: PA_CO43_Insurgency_v17. We also tried a simple mission without ACE modules, same issues: mp_zgm_m13_west.

I'll check for any compatibility addons and report back

**Comment by Glowbal** [comment]
Please confirm this is an issue with only CBA_A3 and ACE 3.2.1.

**Comment by captainblaffer** [comment]
The RPT reads ACE 3.2.1
> 12:50:05                  Advanced Combat Environment 3.2.1 |               @acepa |      false |             GAME DIR | f74ee20537249bd6a082543d90bb5260fda2c83a |  4df8313e | C:\a3server\steamapps\common\Arma 3 Server\@acepa

**Comment by captainblaffer** [comment]
Tested again, using just ACE 3.2.1 and CBA_A3. No ACE optional folder either. All set up this way for players and server.

It's not just going unconcious. Players also die very fast. Compared to default A3 damage model its crazy (http://chkilroy.com/arma-3-weapon-damage-test)

Results were the same. 
One 556 in the leg:
- Player without body armor dies
- Player with body armor(NATO carrier lite) goes unconcious instantly.

9mm pistol shots in the chest:
- Player with body armor(NATO carrier lite)  dies after two shots

**Comment by captainblaffer** [comment]
Updated first post. The issue also occurs on ACE 3.1.1

**Comment by ViperMaul** [comment]
@captainblaffer 
Is this basic or advanced mode medical?
If you are willing can you attach your mission where this happens?

**Comment by alganthe** [comment]
takes me three shot at 200m to kill someone with 5.56
at close range 9mm is way too effective in basic, this bug only impact basic

**Comment by Jastreb** [comment]
@ViperMaul 

I was not trying a pistol since I rarely use it, and looks like its a bug. Two shots in chest with body armor and dead. Tried in ace test mission with AI, I will soon check in dedicated with players, and will report back.

**Comment by captainblaffer** [comment]
@ViperMaul 
> @captainblaffer
Is this basic or advanced mode medical?
If you are willing can you attach your mission where this happens?

Basic medical. Happens in any mission. With or without ACE modules placed.

**Comment by captainblaffer** [comment]
@alganthe 
> takes me three shot at 200m to kill someone with 5.56
at close range 9mm is way too effective in basic, this bug only impact basic

I can confirm this happens when in editor. Not sure about in dedicated MP.

However, in default A3 it will take 5 shots to kill at 200m, 4 at 50m
Compared to ACE3 3 shots and 2 shots

**Comment by captainblaffer** [comment]
One difference between 3.2.1 and 3.1.1 Ive noticed, is in 3.2.1 players who go unconscious will wake up by themselves after a few seconds. In 3.1.1 this doesn't happen.

**Comment by Cyruz143** [comment]
@captainblaffer 
https://github.com/acemod/ACE3/issues/1964

**Comment by dedmen** [comment]
Can also confirm that. Appeared first in 3.2.0.
Getting hit by One bullet the waking up due to #1964 and then being fully wounded.
Only on basic Medic not happening on Advanced.

**Comment by Armilio** [comment]
Well, i thought was not a bug but an ACE feature. Vanilla is unrealistic, indeed when the actual wound system of vanilla - that increased the resistance against bullets -  was implemented with a patch, 2 years ago, i remember many complain in bohemia forum. Please don't make it like the vanilla, it's one of the main reason why i use ACE. Maybe going unconscious with one bullet in the leg it's excessive, but i repeat: the vanilla can't be a yardstick.  Instead, i confirm the "resurrection" issue.

**Comment by Cyruz143** [comment]
I have no clue what you're trying to say or how it relates to this issue but it is currently a bug on a basis that there's no intent in the code to wake people up randomly without medical interaction, thus bug.

**Comment by captainblaffer** [comment]
This thread is about players going unconscious / dying too fast. There is a differen't thread about the Resurrection bug. 

I've never read anywhere in the ACE documentation, when using basic medical, players are supposed to be much less resistant to damage than vanilla. If there is such a feature I would really appreciate an option to disable it.

**Comment by alganthe** [comment]
No it's not a feature and it's currently being looked at.

**Comment by Glowbal** [comment]
This should now be fixed.
