### ISSUE TITLE
Disable team management module does not work for JIP players

### ISSUE THREAD

**Issue by captainblaffer** [acemod/ACE3#2024]
ACE3 Version: 3.1.1

Mods:
@3cb_baf_equipment;@3cb_baf_weapons;@AllInArmaTerrainPack;@PsyLandRover;@acepa;@ASDG_JR;@ASDG_JM;@BWA3;@CBA_A3;@fhq_accessories;@hlcmods;@k_mnp;@mrt_accfncs;@rhs-hlc;@rhsafrf;@rhsusf;@stui;@tao_foldmap_a3;@task_force_radio;

Placed ACE3 Modules:
	value="0";
	parentCls="ACE_ModuleInteraction";
	typeName="EnableTeamManagement";

Description:
Disable team management module does not work for JIP players. They will be able to join other player's groups.

Steps to reproduce:
1. Make mission with disable team management module.
2. Host mission on dedicated. P1 connected at mission start.
3. Have P2 JIP, in a different squad.
4. Have P2 join P1's group using ACE interaction.

Where did the issue occur?
Dedicated

RPT log file:
http://pastebin.com/vZnDFNQB

**Comment by PabstMirror** [comment]
Thanks for helpful report, fixed.
