### ISSUE TITLE
ACE Server Client Mismatch

### ISSUE THREAD

**Issue by Alec-HS** [acemod/ACE3#2025]
ACE3 Version: 3.2.1 Stable

**Mods:**
http://gyazo.com/9a84bd050c8c4f0f7b46a18899e3add1

**Description:**
When playing mission created on dedicated box clients gets server client mismatch for list of nearly all ACE addons. The server and client have identical version of ACE and this verified and testing using A3Sync and Copy Paste via RDP.

**Where did the issue occur?**
Multiplayer dedicated mission with any number of mods and modules placed (seems to have no relevance to error.

**RPT log file:**

http://pastebin.com/MPprfsSK

See line 1003.

**Comment by PabstMirror** [comment]
Would it be possible to post the RPT from the server?

ERROR missing server addon(s): ... `asdg_jointmuzzles`

This rpt never loads asdg_jointmuzzles.pbo so there may be a file mismatch.

**Comment by Jastreb** [comment]
19:42:13 [ACE_laserpointer] - ASDG Joint Rails but no ace_asdg_comp

Missing comatibility addon on client and possiblz the server. Cant reproduce the error.

**Comment by Alec-HS** [comment]
Thanks guys, don't know how I missed that. Will check once I'm back from work tonight.
