### ISSUE TITLE
(Feature Request) Blue Force Tracker Tablet

### ISSUE THREAD

**Issue by NKrukov** [acemod/ACE3#2028]
I've seen reference to the overhaul of the Blue Force Tracking Module.  Are you guys planning on porting, or creating your own version of the CSE tablet?  The Tablet in CSE was near perfect in my opinion as a commander.  Loosing that capability is rather painful, so its my hope you guys will re implement that (For me) needed asset.  We're currently using cTab, but cTab, compared to the CSE tablet is... Not... a good substitution... to say the least.

Thank you for your time, and keep up the good work with your amazing mod!

**Comment by BaerMitUmlaut** [comment]
Feature requests go here: #414
Also, a BFT system is in the works and can be found on the BFT branch.

**Comment by PabstMirror** [comment]
We are currently working on this feature

**Comment by BobsonSakamano** [comment]
Is there a status update on this?  I am in the same group as N. Krukov and loved the CSE Tablet.  Good job, and keep it up guys.
