### ISSUE TITLE
Freeze Map Zoom/Detail

### ISSUE THREAD

**Issue by Macarde** [acemod/ACE3#2030]
I'm requesting a module which will make it so that no matter how far you zoom in/out the grid lines and map detail remain the same. Right now ACE has the feature that prevents players from zooming in real close and also prevents the 10m (8 digit) grid lines from appearing. However, when a player zooms out close to max, the 100m grid lines and most of the topographic data disappears. Even roads and small towns disappear. I am requesting a module that makes the map more "static" and closer to the piece of paper it is by displaying the same grid lines and level of detail no matter how for the player is zoomed in/out. 

Ideally, it would keep the 100m (6 Digit) grid lines and that are found on most 1:25,000/50,000 maps utilized by the US and NATO. Additionally all the details such as forest, buildings, roads, towns, etc would stay visible even when zoomed out all the way. Alternatively, a simple zoom "lock" that a mission maker can chose at what zoom level the map is permanently fixed at.

**Comment by MikeMatrix** [comment]
Hey, please take a look at http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html on how to properly make a feature request.
Most of our feature requests are getting accumulated over at #414.

**Comment by PabstMirror** [comment]
Tagging for #414
