### ISSUE TITLE
ACE MapTools works only with ItemMap

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#2033]
ACE Maptools checks only ItemMap in assigned items and don't work with other maps in this slot: https://github.com/acemod/ACE3/blob/master/addons/maptools/functions/fnc_canUseMapTools.sqf
For example, there are other items that inherited from ItemMap and are maps in SWT_markers addon. Maybe in other mods too.

**Comment by PabstMirror** [comment]
Have a PR to fix.
Was trying with Sweet markers system, looks like our ace_marker conflicts, but I don't think there's much either mod can do.

Also when rotating the map tools it was dropping blue dots (ctrl-click?), so hopefully that can be turned off in sweet.

**Comment by ruPaladin** [comment]
Yes it conflict with ace_markers.pbo, you have to delete ace_markers.pbo and then SWT markers works ok. You may check the issue in Virtual Arsenal.
