### ISSUE TITLE
Slideshow does not work on dedicated server

### ISSUE THREAD

**Issue by Knight1981** [acemod/ACE3#2037]
Hey guys,

I have created a slideshow with some images on a laptop. It works very fine in the editor preview but when I play this map on a dedicated server it does not work because I do not get the option on the laptop to switch the images.

Please have a look on this, thank you :)

**Comment by PabstMirror** [comment]
@jonpas also #1945

**Comment by jonpas** [comment]
Yup yup, just got home, expect PRs tomorrow or later today. :)
