### ISSUE TITLE
No Interaction Menu on SDV when in water. 

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#2044]
@pmc-tyler reports
Interaction Menu does not work while the SDV is in the water. 
https://gyazo.com/06903f852e47f4670d91fc61cd67a9eb
Other ships are ok. 

It is desired to be able to swim under water and attach an explosive.

**Comment by gienkov** [comment]
Still when you are even deep underwater AI will be alerted if you get fairly close, same thing goes for enemy patrol boats.

**Comment by commy2** [comment]
Fixed?

**Comment by bux578** [comment]
![2016-02-19_00003](https://cloud.githubusercontent.com/assets/1235520/13175191/091ee6ac-d709-11e5-8fa8-5672842c0a74.jpg)

yep
