### ISSUE TITLE
Under certain circumstances spall causes havoc on buildings and vehicles

### ISSUE THREAD

**Issue by brainslush** [acemod/ACE3#2049]
ACE3 Version: 3.2.1

**Mods:**
- CBA v1.1.23
- ACE 3.2.1
- MBG Killhouses

**Placed ACE3 Modules:**

 http://pastebin.com/B9dqipPa

**Description:**

 Shooting corners or narrow parts of the hit lod of vehicles and buildings cause severe damage due to spall.

**Steps to reproduce:**
- Enable spall
- Use any AR with caliber 5.56 or larger and shoot from a close distance the front light of a Stomper. After one to two shoots the front tire is blown and one notices severe damage to the Stomper. Two to three more shoots cause the vehicle to blow up.
- Under certain angles shooting at walls of two adjacent buildings sometimes causes severe damage to one of the buildings

**Where did the issue occur?**
Multiplayer & Singleplayer

**RPT log file:**

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
