### ISSUE TITLE
Interaction and Self Interaction Menu not working

### ISSUE THREAD

**Issue by SquirmyCoz** [acemod/ACE3#2067]
All of ACE's features are working but the Interaction and Self Interaction menus. I have set the hotkeys for them and they don't see to work at all.

**Comment by PabstMirror** [comment]
* Could you please include a RPT file (can be found in %localappdata%/Arma 3/ and look for the most recent file likearma3_2015-08-01_22-17-40.rpt and dump it on pastebin.com)
* Do you get any indication that the interaction menu is opening (red circle in center)?
* Try rebinding the keys, by default they use the windows key, which may not work for some keyboards.
* Please try adding the CBA compat pbo, and make sure you are running the most recent version of CBA.

>We have noticed that when using ACE with 3rd-Party mods that do not fully support CBA Extended Eventhandlers (XEH) that some units do not work with Interaction fully. You may see the cursor but no menus.

>WORKAROUND: The latest CBA RC7 Hotfix 2, v1.1.23 has an optional PBO that you can activate to help resolve these situations. 
1. Move the cba_enable_auto_xeh.pbo and its signature file from the CBA optional folder to the CBA Addons folder
2. Restart Arma.

**Comment by SquirmyCoz** [comment]
http://pastebin.com/wCfKUZAx

**Comment by SquirmyCoz** [comment]
I have also had no indications like the red circle or anything else

**Comment by bux578** [comment]
The first thing I notice when looking at you rpt file is, that there's something wrong with the `-mod` arg (how you start Arma 3 with mods)

It should look like this:
```
"-mod=(optional full path\)@CBA_A3;(optional full path\)@ace"
```

But yours (line 3 of your rpt file) is looking like this:
```
"-mod=(optional full path\)@CBA_A3;(optional full path\)@ace;@CBA_A3;-malloc=tbbmalloc"
```

Two times CBA_A3 and the "-malloc" arg which shouldn't even be inside "-mod". Please, fix that and report back.

**Comment by NouberNou** [comment]
Closing due to lack of more info.

**Comment by PabstMirror** [comment]
Test with new CBA if it is still a problem, make a new issue.
