### ISSUE TITLE
medical_menu - Make blur an option

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2069]
ACE3 Version: https://github.com/acemod/ACE3/commit/493254619ce85c7ab5d6e0bd4f03f861b222eaf5

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Medical modules*

**Description:**
*By default your screen will go blurry when you open new medical menu. That should be an option - for me it hurt my eyes (amount of blur). Or at least disable blur when you select treatment and get into animation.*

**Steps to reproduce:**
* *Open medical menu.*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*-*

**Comment by NouberNou** [comment]
Should use the same option as the interact menu probably if this is felt to be warranted by you Glowbal.

**Comment by SzwedzikPL** [comment]
> Should use the same option as the interact menu probably if this is felt to be warranted by you Glowbal.

:+1:

**Comment by Glowbal** [comment]
#2361
