### ISSUE TITLE
medical_menu - Drugs are not translated on activity log

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2070]
ACE3 Version: https://github.com/acemod/ACE3/commit/493254619ce85c7ab5d6e0bd4f03f861b222eaf5

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Medical modules*

**Description:**
Title says it:
http://steamcommunity.com/sharedfiles/filedetails/?id=496490084

**Steps to reproduce:**
http://steamcommunity.com/sharedfiles/filedetails/?id=496490084

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*-*

**Comment by Glowbal** [comment]
This is actually a bug with the triage card system, not the medical menu.

**Comment by Glowbal** [comment]
fixed by #2088
