### ISSUE TITLE
medical_menu - Amount of IV to transfuse left is not displayed

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2071]
ACE3 Version: https://github.com/acemod/ACE3/commit/493254619ce85c7ab5d6e0bd4f03f861b222eaf5

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Medical modules*

**Description:**
Title says it:
http://steamcommunity.com/sharedfiles/filedetails/?id=496490084
Should display under description.

**Steps to reproduce:**
http://steamcommunity.com/sharedfiles/filedetails/?id=496490084

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*-*

**Comment by Glowbal** [comment]
Fixed by #2088
