### ISSUE TITLE
medical_menu - You still get old 3D medical menu when you enable new medical menu

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2072]
ACE3 Version: https://github.com/acemod/ACE3/commit/493254619ce85c7ab5d6e0bd4f03f861b222eaf5

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Medical modules*

**Description:**
*Title says it all, if I enable new medical menu I want to use only that one but instead I get both:*
http://steamcommunity.com/sharedfiles/filedetails/?id=496488513

**Steps to reproduce:**
* *Open medical menu.*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*-*

**Comment by SzwedzikPL** [comment]
:+1: Medical options in interaction menu should be optional. We can merge option about medic panel with this, somethink like Medical interaction: "Interaction menu" (default), "Medic panel", "Both".

**Comment by Glowbal** [comment]
#2361 You can disable the interaction option if prefered. We might change this in the future to @SzwedzikPL s suggestion.
