### ISSUE TITLE
scopes - script error

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2073]
ACE3 Version: https://github.com/acemod/ACE3/commit/493254619ce85c7ab5d6e0bd4f03f861b222eaf5

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Medical modules*

**Description:**
*Got this script error when exiting mission while in editor:*
http://steamcommunity.com/sharedfiles/filedetails/?id=496493541

**Steps to reproduce:**
* *Open editor*
* *Place player*
* *Preview*
* *Exit*
* *Script error comes up*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*http://pastebin.com/iyM7fgD3*

**Comment by Glowbal** [comment]
Already fixed on master.
