### ISSUE TITLE
medical - option's reset itself to default values

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2074]
ACE3 Version: https://github.com/acemod/ACE3/commit/493254619ce85c7ab5d6e0bd4f03f861b222eaf5

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Medical modules*

**Description:**
*I've placed medical modules and set them to Advanced (for testing), but when I enter the game I got basic, all medical settings seems to be set at default values. Watch video and see for yourself:*
https://www.youtube.com/watch?v=3fexM6VH1bc&feature=youtu.be

**Steps to reproduce:**
* *Place medical module and set it to advanced.*
* *Notice that ingame you have basic*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*http://pastebin.com/iyM7fgD3*

**Comment by PabstMirror** [comment]
Modules names where the same, should be fixed now
