### ISSUE TITLE
medical_menu - menu doesn't show which bodypart is selected on Basic medical, works on Advanced

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2075]
ACE3 Version: https://github.com/acemod/ACE3/commit/493254619ce85c7ab5d6e0bd4f03f861b222eaf5

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Medical modules*

**Description:**
*Medical menu should show up which body part is selected when you click on it. This works when you set medical level to Advanced, but will not show up on Basic at all. Watch video and see for yourself:*
https://youtu.be/270bFRDcM6U
Also notice empty option at the end of video.

**Steps to reproduce:**
* *Place medical module and set it to advanced.*
* *Open medical menu and select any bodypart, notice how it's name shows up under Description*
* *Set medical to basic*
* *Open medical menu and select bodypart. You can't tell which bodypart is selected*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*http://pastebin.com/iyM7fgD3*

**Comment by Glowbal** [comment]
fixed by #2088
