### ISSUE TITLE
medical_menu - applied tourniquet doesn't show up on description window, also shows up wrongly as "x have given IV to patient"

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2078]
ACE3 Version: https://github.com/acemod/ACE3/commit/493254619ce85c7ab5d6e0bd4f03f861b222eaf5

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Medical modules*

**Description:**
*When using medical menu, applied tourniquets will not show up on description tab. Also if you apply tourniquet then activity log tells you that you applied IV to patient. So two bugs here.*

**Steps to reproduce:**
* *Apply tourniquet on patient limb*
* *Notice how "x applied IV" information shows up - wrongly, first bug*
* *You can't tell that tourniquet is applied but you get option to remove tourniquet - second bug*

**Where did the issue occur?**
*"Singleplayer"*

**RPT log file:**
*-*

**Comment by Glowbal** [comment]
fixed by #2088
