### ISSUE TITLE
Cannot  use make.py

### ISSUE THREAD

**Issue by Hemius** [acemod/ACE3#2089]
Set up all stuff: arma 3 tools, mikero's tools, python. Downloaded 3.2.1 source and started to get all functionality that i don't need out of mod. Done it, made a test build. Worked fine this way. all that  I needed was in game.
Then tried to make a final release with make.py. Console window appears for a moment and then disappears without starting to compile mode.
What can be the issue?
Can you explain me, how do I use make.py?
P.S. I'm using Win 10 for a moment. Can it be the cause of this problem?

**Comment by jonpas** [comment]
Start the command prompt first, navigate to the tools folder and type `make.py` manually, that way console window won't disappear and you will be able to see the error.

**Comment by PabstMirror** [comment]
Take a look at: http://ace3mod.com/wiki/development/setting-up-the-development-environment.html

make.py needs a lot more to actually build, like a fully setup p:

I would recommend starting make.py from a console so it doesn't auto close and take a look at what error's it displays.

**Comment by Hemius** [comment]
Thanks will try it!

**Comment by Hemius** [comment]
Found a problem. I haven't set up Git.
How can I skip Git installation or can someone explain me the way how  I set up it right way.
Sorry for disturbing you guys, but it's really hard to learn everything on the go....

**Comment by Hemius** [comment]
Finally fixed all!

**Comment by jonpas** [comment]
Great to hear!

**Comment by tteomaster4** [comment]
Hemius, I am having the same problem, I tried adding git to my path but I don't think it is quite right. Any advice?
