### ISSUE TITLE
ACE menu problem

### ISSUE THREAD

**Issue by Przemro** [acemod/ACE3#2091]
ACE3 Version: 3.2.1

Mods:

@cba_a3
@ace3
@RHS 

Placed ACE3 Modules:
N/A

Description:
When you play on lower resolution, you can`t use some option from ACE menu.
http://sds-polska.pl/wp-content/uploads/2015/08/2015-08-09_00007-1024x640.jpg (video settings)

I know that you put a lot of work to ACE menu. But I would still prefer to have option to use menu like AGM had.

Steps to reproduce:
Set setting in screen above, and place explosive then try to detonate it.
http://sds-polska.pl/wp-content/uploads/2015/08/2015-08-09_00001-1024x640.jpg 
http://sds-polska.pl/wp-content/uploads/2015/08/2015-08-09_00002-1024x640.jpg (after this, I can`t reach for explosive itself, it is out of screen)

**Comment by gienkov** [comment]
Use "keep cursor centered" to fix that.

**Comment by Przemro** [comment]
Yes it can fix that, but it is very not intuitive imo. But fix is fix.

**Comment by PabstMirror** [comment]
Explosives is one of the few actions where the tree goes 4 deep.

Right now the best option we have the keep cursor centered.
Decreasing the interface size in video options may also help.

Tracking Issue in #1774
