### ISSUE TITLE
disposable - script error with AI

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2095]
ACE3 Version: 3.2.1
https://github.com/acemod/ACE3/commit/0c2c71e70ea80c0c83584b4bd487ec7d1ad199ed

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
*Got this error when AI grabs NLAW:
http://steamcommunity.com/sharedfiles/filedetails/?id=497119043

**Steps to reproduce:**
* *Make AI grab his NLAW and observe script error*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*-*

**Comment by Glowbal** [comment]
Fixed by e5eaefa
