### ISSUE TITLE
Switching unit in medical menu allows doing actions on any distance

### ISSUE THREAD

**Issue by SzwedzikPL** [acemod/ACE3#2097]
ACE3 Version: https://github.com/acemod/ACE3/commit/0c2c71e70ea80c0c83584b4bd487ec7d1ad199ed

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
ACE Debug data in rpt file

**Description:**
https://www.youtube.com/watch?v=KeixLyNxMiU

**Steps to reproduce:**
https://www.youtube.com/watch?v=KeixLyNxMiU

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
http://pastebin.com/fy6hJemX

**Comment by Glowbal** [comment]
#2081

**Comment by Glowbal** [comment]
^ wrong issue number in that commit. Oops?
