### ISSUE TITLE
weaponselect turns off laser when cycling through fire modes

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#210]
ACE_Dev: e7d7fa8e6c6c2a234429e8800ae1a9b010e4686c

**Mods:**
- @cba_a3_dev (RC6_v1.20.150317)
- @ace_dev

**Modules:**
- None

**Steps to reproduce:**
- Start a night mission
- Equip a MX Rifle with the "IR Laser Pointer" attachment and add some NVG to the unit
- Turn on Night Vision and the Laser
- Press the (default) <kbd>2</kbd> key to switch fire mode
- Laser is now turned off

That's different to the default behavior of the <kbd>F</kbd> key. And it just doesn't make sense. :smile:

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
