### ISSUE TITLE
ACE Medic System

### ISSUE THREAD

**Issue by LtRyan** [acemod/ACE3#2100]
I red the latest Wiki about the Medic System and found some strange stuff.
Atropin does not lower the Heart Rate it raise it. (Only very low amount of Atropin cause this)
Epinephrine is the first medicine to treat a cardial arrest and nothing else.

Heart Rate should be
Low: 55 and below
Normal: between 60 and 80 (for the average soldiers)
High: 100 and above

Where did you get those values?

**Comment by BryanBoru** [comment]
Sadly, you're interpretation of Epinephrine is mistaken but so is it's use in ACE. Specifically, It is primarily used to counter anaphylaxis, which in short is an allergic reaction. It is also used to improve return of spontaneous circulation in the vascular system, but it is a minor role compared. Either way the medical system is continuously in development and just abruptly changing it would be easier said than done. These guys on the team are actively monitoring and developing the medical system.

**Comment by LtRyan** [comment]
It isn't primarily used to counter anaphylaxis. I don't know where you get those idea but I learned this via my education as Paramedic.

**Comment by Glowbal** [comment]
Feel free to join our public Slack #429 and provide your feedback + suggestions for this in the medical channel. We try to get as much input from people in the medical field regarding advanced medical as possible.

**Comment by Pasrules** [comment]
I can provide literature papers on the use of epinephrine as a drug used to increase cardiac perfusion and increase blood pressure. It should be used during CPR especially with defibrillation.

**Comment by LtRyan** [comment]
I found nothing about a counteract reaction with epi. The only pharmacological interaction I found are with Amantadin, Chinidin, Antidepressant

**Comment by Pasrules** [comment]
@LtRyan My mistake, there is no counteraction between atropine and epi. Sorry about that.

**Comment by BryanBoru** [comment]
@LtRyan apologies to you. I feel foolish, I've reread my reply and even I couldn't understand what i meant for a moment. I perceive I must've been thinking of an epi-pen as opposed to epinephrine and just went off in a direction that makes no sense. Apologies again.

**Comment by Glowbal** [comment]
Closing to clean up our tracker. If you have more input, feel free to join us on Slack (see url I linked above) or create a new ticket :+1:
