### ISSUE TITLE
Get PAK or surgical kit in Basic medical system.

### ISSUE THREAD

**Issue by Hemius** [acemod/ACE3#2103]
Hi guys!
I'm wondering about how can I make PAK ot surgical kit used in Basic medical system to heal unconscious/conscious units full way (kind of all in one solution), one for example for unconsious and another for conscious? So like person who got it can just use it and get unconsious unit or unit in revive state fully recovered and healed just by using PAK or surgical kit.

**Comment by dvdbrewster** [comment]
Personal Aid Kit does this with Advanced Medical ( I do it)

**Comment by alganthe** [comment]
In basic you don't need to manage vitals or reopening wounds making the surgical kit and PAK useless.

**Comment by Hemius** [comment]
I see this but I wanna get a fast way of saving units lifes... like if there is MRAP near with medic MRAP comes and medic heals unit with PAK or SK. It would be nive to have this.... If it's hard to implement, then I can live without this =)

**Comment by KoffeinFlummi** [comment]
If you want to have a one-click solution you'd have to use the vanilla system. To do that, simply remove the medical PBO.
