### ISSUE TITLE
Can't bunnyhop with binoculars/no weapon

### ISSUE THREAD

**Issue by Waffle-SS** [acemod/ACE3#2105]
ACE3 Version: 3.2.0

**Mods:**
* @cba_a3
* @ace3

**Description:**
Bunny-hop animation doesn't work when sprinting with binoculars or without a weapon.

**Where did the issue occur?**
SP/MP

**RPT log file:**
No script/config errors

**Comment by dvdbrewster** [comment]
This is documented by default isn"t it ?

**Comment by PabstMirror** [comment]
I can't tell any difference between ACE and vanilla.
I'm able to vault while sprinting with either binocs or not weapon.

Can you double check the ACE keybinds and see if anything conflicts (maybe ctrl-V climb?)

**Comment by captainblaffer** [comment]
I've had this issue too. With binoculars/no weapon I am able to vault, but it does the slow vault.
When vaulting while sprinting and holding a weapon, the vault animation goes much faster(bunnyhop/ jump)
I think it's described here: http://ace3mod.com/wiki/feature/movement.html

**Comment by commy2** [comment]
There is no animation for jumping with pistol / binocular / launcher or without anything.

You have to therefore have a rifle equipped to jump.
http://github.com/acemod/ACE3/blob/master/addons/movement/CfgMoves.hpp#L34-L67

**Comment by mickeymen** [comment]
"There is no animation for jumping with pistol / binocular / launcher or without anything.
You have to therefore have a rifle equipped to jump."
if there is no animation, then make this animation! Or remove jump in general!
The possibility of jump only with a gun looks ridiculous!
Why you can't add new animations? Half of the questions for ACE closed without any attempt to fix it! I only see closed, closed, closed

**Comment by KoffeinFlummi** [comment]
> If there is no animation, then make this animation!

Good idea. My email address it on my profile. Just send me the animation when you're done.

**Comment by mickeymen** [comment]
> Just send me the animation when you're done.

Who mod maker? I or or people who make and distribute mods? We already have the animation of the jump with the rifle in his hand. Is it hard to add the same animation (legs) to the pistol binoculars also,
ACE - mod with lots of experience. Logical conclusion-they need to understand how animation works on the engine Аrma. Or am I mistaken?

**Comment by Cuel** [comment]
Anyone can be a "mod maker" for ACE, it's open source. Most contributors are currently programmers not animation riggers

**Comment by dvdbrewster** [comment]
Steal the SWITCH WEAPONS WHILE RUNNING and integrate jumping with WEAPON

**Comment by mickeymen** [comment]
My thought: don't close this ticket. Necessary solve it.
Most of the tickets are closed without trying to solve it

**Comment by commy2** [comment]
jeez. #414
