### ISSUE TITLE
Simultaneous explosive detonation

### ISSUE THREAD

**Issue by Hemius** [acemod/ACE3#2108]
Was playing with mode for a while. Found quite annoying thing about explosives - it is not possible to detonate several charges simultaneously with one player. It ruins ambushes sometimes... =(
Is it a realism feature? It would be nice if in next version there would be a menu that will pop-up on charge setup so you can assign it to different detonation groups.
The best idea is just to have a popup window after chosing detonator where you can choose radio channel used for detonation and then to have possibility to choose detonator channel.

Also have a small question about Claymore mine... is it for realism purposes that auto detonation by walking enemies is deleted?

**Comment by austinjames314** [comment]
Claymores are almost always command detonated. Unless you're playing Call of Duty or some crap.

As for daisy chaining, it has unfortunately been on the backburner for a while now: #1219

**Comment by Hemius** [comment]
I hope I gave a nice idea about chossing radio channel for explosive =)

**Comment by madpat3** [comment]
the claymore mine is a selfdefence mine, mainly use by snipers to protect themselfes against Close enemies from behind. 
if it was mainly used as a command detonate mine, the sniper needed to know an enemy is comming. that was seldom the case.
so activating the bomb via tripwire or maybe lasertrigger is necessary for this Kind of device.
further it was used to be attached to armored vehicles, driving into a pulk of enemies, and being detonatet by remote. claymoremines just being detonatet by remote makes it useless for a sniper.
it has to be passively activatet.

**Comment by austinjames314** [comment]
@madpat3 - I reiterate my above comment. To support it, this is from the first paragraph on the wikipedia page on the M18 Claymore:
"Unlike a conventional land mine, the Claymore is **command-detonated** and directional, meaning it is fired by remote-control and shoots a pattern of metal balls into the kill zone like a shotgun."
(emphasis mine)
