### ISSUE TITLE
UAV control terminal - how to use with ACE?

### ISSUE THREAD

**Issue by Hemius** [acemod/ACE3#2112]
How do I use UAV terminal? It's not possible to open it with mouse scroll or with ACE menu.... nothing else to say actually...
Hope you will help!

**Comment by PabstMirror** [comment]
If I go into editor and put down a NATO: UAV Operator, I get an action to open terminal.

We really need more information to go on, please take a look at: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

If you are running any other mods, please disable them and try just CBA and ACE.

**Comment by gienkov** [comment]
There are 3 UAV terminals, each one for one side (BLUFOR, REDFOR, INDFOR).
You can only use terminal that belongs to your side...

**Comment by Meiestrix** [comment]
No problems here with the Darter.

**Comment by jonpas** [comment]
There should really be an option to allow anyone do it and not just UAV Operators though.

**Comment by TheNiner** [comment]
Sometimes the AI inside the Greyhawk dies (Not sure if this is ACE related).

**Comment by Hemius** [comment]
Finally the problem was about different UAV terminals. They are just named the same in arsenal and it's tricky to find which one you need to use =)
