### ISSUE TITLE
No CPR option available with basic medical when revive is enabled

### ISSUE THREAD

**Issue by Glowbal** [acemod/ACE3#2114]
When using the revive module, performing CPR would extend the time a patient can stay in the revive state (when making use of the timer).

When using basic medical, the CPR action is not available.

- [x] enable CPR for basic when the revive module is active.

**Comment by captainblaffer** [comment]
This is gonna be a great feature!

Would it also be possible to add some info when diagnosing someone, telling how much time is left until they die? e.g. 'his pulse is low'

**Comment by Knight1981** [comment]
Yeah that would be awesome! :) Please add CPR in basic medical system and give an information 
- how much pain the patient has (low, high, very high etc.)
- how long the lifetime is (depents on the life-time value which is set in the module)
