### ISSUE TITLE
Ace_Hearing

### ISSUE THREAD

**Issue by KDK11** [acemod/ACE3#2115]
I am having an issue with this feature, I have it in my mission but it does not work. I have it set to "no" so that I don't get the effect, however I still get the effect and I really do not know how I am supposed to turn it off since it wont allow me to do it through the module.

**Comment by alganthe** [comment]
ACE settings > disable hear ringing.
The module only disable the deafness, the sounds around don't get muffled but you still get the ringing.

**Comment by KDK11** [comment]
ACE > Hearing > Enable Combat Deafness - Set as NO should stop the ear ringing right? but for me it does not.

**Comment by alganthe** [comment]
No, ear ringing is a different setting, combat deafness is just the reduction of the sound when high caliber weapons are fired near you.

**Comment by KDK11** [comment]
So how do I disable the ear ringing? Or can I not?.

**Comment by KDK11** [comment]
1.9 Hearing

Part of: ace_hearing

Placing this modules allows you to disable combat deafness usually triggered by loud explosions or heavy weapons in a players proximity.

That is what causes the ear ringing, when explosions or guns are fired...

**Comment by alganthe** [comment]
OK let me give you a step by step solution:
- Press escape
- Open ace settings (upper left corner)
- Scroll down to ear ringing
- Set it to no

**Comment by KDK11** [comment]
Nice! that works :) thank you.
