### ISSUE TITLE
Show the of pain in medical menu

### ISSUE THREAD

**Issue by Smoketrail** [acemod/ACE3#2117]
@glowbal

Would it be possible to have an indication of how high the pain level in the medical menu

This would help the medics to see if they have to Evac a person or just give them a cookie.

**Comment by Glowbal** [comment]
Thanks @Smoketrail

**Comment by gienkov** [comment]
Maybe something like "Patient is in light/medium/heavy(uncon) pain"?

**Comment by PabstMirror** [comment]
Just my 2 cents, but I prefer the patient just talk to the medic

Although without ACRE/TFAR it's going to be harder, and I suppose in reality you would be able to see facial expressions / moans that can't be reproduced.

**Comment by ulteq** [comment]
-> https://github.com/acemod/ACE3/commit/852f78b801fc0f6900bcf4ac468a43b4890c2d3b
