### ISSUE TITLE
Folder Structure/Naming Rules for Models/Textures/UITextures/Animations (discussion)

### ISSUE THREAD

**Issue by jokoho48** [acemod/ACE3#2119]
at the Progress of Cleanup Code in ACE i very often see different Folder Stuctures and paths and Names for Content. And I contacted Glowbal and he said that we can open a discussion about it.

here are some Ideas how it could work:
### Folder Structure:

---
##### Idea 1:

```
Module/
    data/
        RVMAT
        P3D
        PAA/PAC(for Models)
    UI/
        PAA/PAC(for UI)
        RSC
    anim/
        RTM
```

pros:
- Very Centerd Files

cons:
- Data Folder is Overfilled

---
##### Idea 2:

```
Module/
    data/
        Models/
            P3D
        Textures/
            PAA/PAC(for Models)
        UI/
            PAA/PAC(for UI)
            RSC
        Materials/
            RVMATS
        Animations/
            RTM
```

pros:
- Better over view over Paths and Textures

cons:
- modules that don't have much content, they'll have more subfolder

---
##### Idea 1:

`ace_Name.Format`  
pros:
- Better for detecting for Debugging

Cons:
- longer file names

---
##### Idea 2:

`Name.Format`  
pros:
- shoter file names

cons:
- hard to read

---

if you have more idea or more Pros and Cons feel free to add and discussed about it

**Comment by jonpas** [comment]
**Folder Structure**
I wouldn't go with idea 2, rather separate data into something like the following 2 ideas.
```
Module/
    materials/ (or mats)
        RVMAT
    models/
        P3D
   textures/
        PAA/PAC(for Models)
    UI/
        PAA/PAC(for UI)
        RSC
    anim/
        RTM
```
```
Module/
    data/
        materials/ (or mats)
            RVMAT
        models/
            P3D
        textures/
            PAA/PAC(for Models)
    UI/
        PAA/PAC(for UI)
        RSC
    anim/
        RTM
```

**File Naming**
I don't think idea 2 is hard to read, I also don't see how idea 1 is better for debugging, every time you have a file name you usually have a full path to it, no?

**Comment by jokoho48** [comment]
i think UI can be external but Anims not becaue UI is GUI/UI content and not direct in game but Animations are ingame Content(data)

**Comment by MikeMatrix** [comment]
I think @jokoho48's Folder idea 2 should be the one to go with. It has many advantages for bigger modules and the only disadvantage for small modules is, creating a few sub-folders.
If we go with a standardized resource layout like this, we can also utilize macro's to generate file paths for various resource types. This would also help improve readability of the code.

As for file names, I'm not sure if there will be a big difference between the two. Can anybody think of a situation where the prefix would actually be beneficial?

**Comment by jokoho48** [comment]
````
Module/
    data/
        materials/ (or mats)
            RVMAT
        models/
            P3D
        textures/
            PAA/PAC(for Models)
        anim/
            RTM
    UI/
        PAA/PAC(for UI)
        RSC
```

**Comment by jonpas** [comment]
Hmh, I don't see any benefit vs my second idea in that @jokoho48 , only UI is separate on it's own.

> we can also utilize macro's to generate file paths for various resource types

Yes please!

**Comment by MikeMatrix** [comment]
Quite honestly I don't think separating out the UI out of the data folder makes much sense.
I feel either you put all of the data in there or none at all. After all, afaik it's not code, so I'd classify it as data.

**Comment by jokoho48** [comment]
i would put the UI configs too

**Comment by jonpas** [comment]
> i would put the UI configs too

Hmh, that calls for longer `#include` paths since UI configs must be included in config.cpp, it would clean the includes as well though and separate them from all other includes (ACE_Settings and other non-UI configs).

**Comment by MikeMatrix** [comment]
Well I wouldn't put the configs in there. Maybe something like
```
Module/
    data/
        materials/ (or mats)
            RVMAT
        models/
            P3D
        textures/
            PAA/PAC(for Models)
        anim/
            RTM
        UI/
            PAA/PAC (for UI)
    UI/
        RSC
```
would be more appropriate and allows us to create macros, that maybe are structured in a way that you have a layered macro for the folders of the data folder.

**Comment by jokoho48** [comment]
i dont like the fact that we have 2 UI folder than in One Module

**Comment by MikeMatrix** [comment]
It would however structure it in a way, where the data folder only contains data and everything outside of it would only be code.

**Comment by jokoho48** [comment]
hmm could we call the external UI folder different?
like UIConfig? or something like that

**Comment by MikeMatrix** [comment]
I would say the structure of it would be accessible through various macros, so that you only need to know what type of resource you want and what name it has.

**Comment by jokoho48** [comment]
as small addition for Naming Files

`ace_Name_co.paa`  
`ace_Name_nohq.paa`  
`ace_Name_smdi.paa`  
`ace_Name.p3d`
`ace_Name.rvmat`
`ace_Name.rtm`
`class ace_Module_Name;`

**Comment by jonpas** [comment]
I still fail to see the need for `ace_` prefix, how exactly would we benefit?

Config names which are used for modules, settings or anything that user saves/uses cannot be changed for backwards compatibility, so for that it's best to find a standard that is mostly already used.

**Comment by MikeMatrix** [comment]
@jokoho48 Do you know of an example where not the full path would be returned, where having `ace_` would be beneficial?

**Comment by jokoho48** [comment]
@MikeMatrix good Question i dont know but the `ace_` prefix is not needed i only want to show what files there are needed for 3D models

**Comment by MikeMatrix** [comment]
In that case I'd consider going with the `ace_`-less approach, because it only creates longer filenames.

**Comment by jonpas** [comment]
> In that case I'd consider going with the ace_-less approach, because it only creates longer filenames.

:+1:

**Comment by voiperr** [comment]
We don't give any other file (except `ace_settings.hpp`) the ace_ prefix, so I don't see why it's needed for data.

If we want to standardise the data tagging (`_object`, `_item`, `_weapon`, `_optic`, `_title`, whatever), I'm all for that.

**Comment by MikeMatrix** [comment]
@voiperr that sounds like a good idea actually.

**Comment by commy2** [comment]
- There is no point in creating a data folder if the PBO only includes one or two .p3d or rtms.
- rvmats should be in the same folder as diffuse, normals, speculars etc.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
