### ISSUE TITLE
The mod needs to allow me to remap it´s keys. 

### ISSUE THREAD

**Issue by Himmuguegeli** [acemod/ACE3#2121]
I do have a simple but serious problem with the mod. There´s no way to remap the keys it´s using. And that means I can´t use the interaction system with my steel series keyboard. It only has a right windows key and no left one. And normally games do not make use of the windows keys which means that it would be very nice if you could add a config to change this. Otherwise this stays unplayable for me and the rest of the owners of this or similar keyboards. And I definitely won´t buy a new one just for this. So please try to add this on your list.

**Comment by MikeMatrix** [comment]
You can simply rebind all of your keys, by using CBA's keybind options.
Simply go under Options > Controls and you'll see "Configure Addons" in the bottom right.

**Comment by PabstMirror** [comment]
We use CBA keybinding:

>CBA Keybinding is easy to use. First, load Arma 3 with CBA and the mods you intend to use.
Then, to access the configuration page for CBA-defined mod keybindings:
1. Select Configure -> Controls from the Main Menu.
2. Click the Configure Addons button in the lower right of the dialog.
3. Select the name of the addon you'd like to configure from the drop-down menu.
4. Double click any action to change the key assigned to it.

ref: https://dev.withsix.com/projects/cca/wiki/Keybinding
