### ISSUE TITLE
Attach Backpacks to Vehicles

### ISSUE THREAD

**Issue by masterT00L** [acemod/ACE3#2125]
Do you remember the Jackals from ARMA2 BAF?
It would be great and handy if the ACE3 team adds the function to bind backpacks to cars, as is currently possible with IR strobes and Chemlights.

It would also help to bridge the time until ace_logistics is available.

**Comment by jokoho48** [comment]
please Read This: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
and use #414

**Comment by masterT00L** [comment]
Sorry! I'm used to work like this on gitlab, so i didn't pay enough attention. Thank you for the links.
