### ISSUE TITLE
Fire Control System is not working

### ISSUE THREAD

**Issue by MrFies** [acemod/ACE3#2126]
ACE3 Version: 3.2.1

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
I changed nothing , I only used the unpacked @ace3 folder

Description:
This following Feature doesnt work.
http://ace3mod.com/wiki/feature/fcs.html 

Where did the issue occur?
"Multiplayer", "Singleplayer"

**Comment by bux578** [comment]
https://www.youtube.com/watch?v=93rErjMNKjw

Can confirm!

**Comment by hello12121212** [comment]
i found that it works in thermal but not in normal vision. Tested in helicopters.

**Comment by bux578** [comment]
http://ace3mod.com/wiki/feature/fcs.html#2-1-engaging-moving-targets
Still doesn't work for tanks.

**Comment by VKing6** [comment]
Fixed the lead issue, and I didn't notice any other problems when testing it, with any tank.
