### ISSUE TITLE
Bad animation

### ISSUE THREAD

**Issue by kyren201** [acemod/ACE3#2127]
ACE3 
Stable (3.2.0) 

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
*None

**Description:**
* open arma3, instantly recloses and says 'Bad animation format in file z/ace/addons/goggles/anim/wipeglasses.rtm

**Steps to reproduce:**
* 1. open arma 3
2. Profit

**Where did the issue occur?**
* singleplayer/ opening the game

**RPT log file:**
* cant find the file???

**Comment by PabstMirror** [comment]
RPT should be found here:`%localappdata%/Arma 3/`
aka C:\Users\YourUserName\AppData\Local\Arma 3

Is it still an issue with ace 3.2.1?

Could you try verifying arma in steam

**Comment by dedmen** [comment]
Arma doesnt create the RPT that early.
It sounds like a corrupted pbo or corrupted Arma files.

**Comment by PabstMirror** [comment]
Please make a new issue if it is still happening with 3.2.1
