### ISSUE TITLE
Pause menu multiply visible nametags for a split second

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2129]
ACE3 Version: 3.2.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Name tags.*

**Description:**
*On dedicated, when you enter pause menu  then any moving player in front of you will cause something weird when you exit pause menu. What happens is for a split second you see his nametag all around (screen is filled with his nametag) and then they disappear. This looks almost like graphical artifact.*

**Steps to reproduce:**
* *Written above.*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
*-*

**Comment by PabstMirror** [comment]
I've noticed this as well.
It seems like it queues up all the draws and then does then when exiting the pause menu.

**Comment by jokoho48** [comment]
that is a Issue with DrawIcon3D BI Fault
