### ISSUE TITLE
Make the Key settings changeable. Unplayable for me this way.

### ISSUE THREAD

**Issue by Himmuguegeli** [acemod/ACE3#2131]
Currently there´s no way to change the key settings for the mod as it is compared to RHS for example. My keyboard has no left windows key, which basically means that I cannot use the interactions at all. And I am not the only one with that problem, so please give us the ability to swap keys soon. 

And thanks for your work, the mod is great already and you guys doing a nice job.

**Comment by PabstMirror** [comment]
@Himmuguegeli please look at answers in #2121

**Comment by jokoho48** [comment]
We use CBA keybinding:

    CBA Keybinding is easy to use. First, load Arma 3 with CBA and the mods you intend to use.
    Then, to access the configuration page for CBA-defined mod keybindings:
    1. Select Configure -> Controls from the Main Menu.
    2. Click the Configure Addons button in the lower right of the dialog.
    3. Select the name of the addon you'd like to configure from the drop-down menu.
    4. Double click any action to change the key assigned to it.

ref: https://dev.withsix.com/projects/cca/wiki/Keybinding
Copied by PabstMirrors Post
