### ISSUE TITLE
Can't load captives into helicopters

### ISSUE THREAD

**Issue by Ghost77788** [acemod/ACE3#2132]
ACE3 Version: 3.2.1
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* @cba_a3
* @ace3

**Pbo in question:**
ace_captives.pbo

**Description:**
You can't load handcuffed people into helicopters, this is because the "if" statement in the **doloadcaptive.sqf** checks against other variables ("helicopter_f") then **canloadcaptives.sqf** ("helicopter").

However looking into the config of arma 3 "helicopter_f" doesn't or no longer exists and is now "helicopter_base_F".

So the **doloadcaptives.sqf** will exit the script because vehicle == null.

But seeing as the **canloadcaptives.sqf** checks against empty cargo positions, why not set the nearestobjects command up with just "air", "land","ship".
Because anything that doesn't have a cargo place wouldn't even get the options to load.

Thank you for your time. And hope it helps.

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**Comment by PabstMirror** [comment]
Why can't every bug report be like this one, with the solution inside.
Thanks for the report, should be fixed in next release.

**Comment by bux578** [comment]
> Why can't every bug report be like this one, with the solution inside.

Or even with a link to the pull request fixing the bug :smile:

**Comment by jonpas** [comment]
@Ghost77788 yoi deserve a :banana: for that awesome bug report + fix!
