### ISSUE TITLE
You respawn with Laserdesignator in your hands if you had it in your inventory

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#2138]
ACE3 Version: 3.2.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Respawn Module, Save Gear Option*

**Description:**
*If you had a Laserdesignator in your inventory before getting killed you will respawn with Laserdesignator in your hands. This is a small issue but became sort of problem because we play without ace medical and we use built in arma's revive system. And the way it works is it actually respawns you on the same place in a different animation waiting for revive. So after a fast revive in a combat zone you end up holding Laserdesignator and aren't combat ready.
This happens because you have _unit selectWeapon "Laserdesignator"; in fnc_restoreGear.sqf on 162 line. Option to fix this is probably to check whether the unit has any primary, secondary or handgun weapon and to switch to it. Or to get a weapon unit held before dying and store it in that gear array and make a selectWeapon of the weapon unit held previously.*

**Steps to reproduce:**
* *Equip Laserdesignator. Press ESC and respawn. You will respawn with Laserdesignator in your hands.*

**Where did the issue occur?**
*Multiplayer and Singleplayer*

**RPT log file:**
*No need.*

**Comment by bux578** [comment]
That's actually by design. The problem is, if you have a laser designator there's no other way to reload the batteries.

**Comment by rebelvg** [comment]
Yes, I understand that. I mean, after the batteries have been reloaded you can make a switch to the weapon unit held before dying (save it in that gear array) or to any other weapon the unit has.

**Comment by bux578** [comment]
I'll have a look. Do you have a repro mission with the revive system set up?

**Comment by rebelvg** [comment]
https://mega.co.nz/#!btZWkI4K!mho5UdtZ5ZlZaFkBGvsLyRsg8h1935C9SL1g9rCKxVI

**Comment by rebelvg** [comment]
And with the revive system. https://mega.co.nz/#!n15SSJBD!v5om4LIz67rfX4XBnopD7J7jqJFhtrLnldAdw2MeLdA

**Comment by rebelvg** [comment]
Fist mission - just respawn test, second for the revive system. All must be tested in MP, to activate the revive system you must setdamage 1 to yourself, respawn button will just respawn you.

**Comment by bux578** [comment]
:+1:

**Comment by bux578** [comment]
@rebelvg could you and are you able to test this, please. It worked quite well when I tested it.

**Comment by rebelvg** [comment]
@bux578 Thanks, yeah, I can and I'll test it in a bit.

**Comment by rebelvg** [comment]
@bux578 Yep, works fine. The only side effect is that when you die in vehicle you respawn with a weapon on your back which is alright. Thanks!

**Comment by bux578** [comment]
Glad it works for you now. I must admit that I didn't test respawning from a vehicle. Though having the weapon on your back probably makes the most sense.

**Comment by bux578** [comment]
Respawning while diving and parachuting is working.

**Comment by commy2** [comment]
fixed in #2679
