### ISSUE TITLE
Allow changing position of nametags

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2153]
I know you can set it on "On cursor and modifier" or "Modifier" alone, but still they show up above player heads. Sometimes this can cause issues when you are doing close quarters combat, when you stick to your teammates and suddenly nametag show up in front of your aim - had it many times already. I think that rendering names on chest level could be better for some since they would not disturb your aim at all even when you have nametags always enabled.
Maybe new option "Render nametags: above head / chest level" or something.

Thanks!

**Comment by jonpas** [comment]
I'd add a third option which would render them 2d, like ShackTac NameTags do.

**Comment by gienkov** [comment]
Implement ST Nametags into ACE? ;D

**Comment by Glowbal** [comment]
This is a feature request @gienkov. #414
