### ISSUE TITLE
Animation is still played even if you cancel any treatment

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2156]
ACE3 Version: 3.2.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Advanced medical*

**Description:**
*Title says it. Affects mainly medical treatments animations. Canceling has no point atm since you have to wait until animation is finished, and sometimes you have to just throw everything and run.*

**Steps to reproduce:**
* *Select bandage yourself self interaction and cancel it second after it.*
* *Notice how animation is still played, making you unable to move until it's finished.*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*-*

**Comment by Glowbal** [comment]
Noticed this while working on vehicle repair as well.
