### ISSUE TITLE
Old ACE3 wiki still accessible

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#2159]
http://koffeinflummi.github.io/ACE3/ is still accessible and could cause misunderstandings.

@bux578

**Comment by KoffeinFlummi** [comment]
Since I transferred ownership of that repo to the organization I can't disable it. I sent a mail to GitHub support.

**Comment by KoffeinFlummi** [comment]
GH support said that the issue stems from an incorrect DNS configuration for ace3mod.com. While that may be true (although to be honest that seems odd), I couldn't reach @jaynus, so I just set up a repo with the same name and deleted it again. Why didn't I think of that right away...

![](http://i.imgur.com/f9FW2.gif)

**Comment by commy2** [comment]
Go Flummi!

**Comment by jonpas** [comment]
:+1:
