### ISSUE TITLE
ace_common_executePersistent cause memory crash

### ISSUE THREAD

**Issue by havena** [acemod/ACE3#2167]
CE3 Version: 3.2.1

Mods:

@cba_a3
@ace3
@rhs
@tfr
Placed ACE3 Modules: http://pastebin.com/uGuAaH8i (i have try with / without medical, wind & ballistic)

None.
Description:
since a3 1.48 / ace 3.1.1 / cba rc7 i have server crash every day.
i have a verbose cba_xeh with debug diag_log and this is the RPT results on Crash :
```
22:41:18 init_enum: _cfgEntry = bin\config.bin/Extended_InitPost_EventHandlers/All/ace_common_executePersistent
=======================================================
-------------------------------------------------------
Exception code: C0000005 ACCESS_VIOLATION at 00B5BD0C
```
```
23:20:41 init_enum: _cfgEntry = bin\config.bin/Extended_InitPost_EventHandlers/All/ace_common_executePersistent
=======================================================
-------------------------------------------------------
Exception code: C0000005 ACCESS_VIOLATION at 00B5BD0C
```

Where did the issue occur?
"Multiplayer"

RPT log file:
No need.

**Comment by PabstMirror** [comment]
Could you post full rpt?
Does the issue happen with just CBA and ACE (last line doesn't always mean it's the problem)?

Right now, Dedicated server's don't need the dlls.  If this is on a dedicated server, try removing the ace_xxx.dlls and see if it still has problems.

**Comment by havena** [comment]
I think i have already try without server dll. I will try one more time.

for ace_common_executePersistent :
i have see ace_common_execPersistentFnc increment ACE_PersistentFunctions variable.
(https://github.com/acemod/ACE3/blob/c9529a1e1c2b908def1ad2e9940ac12a9560ef3e/addons/common/functions/fnc_execPersistentFnc.sqf) but i dont find where and by whom ace_common_execPersistentFnc is call?

**Comment by havena** [comment]
Always crash without dll.
some RPT https://mega.co.nz/#!ftIj3YhT!1me7_USgfQemao8iOL1CB_kbkV3e0stG6lW47ovfLRw

**Comment by havena** [comment]
i will try to add a diag_log debug in executePersistent for see exactly when server crash

**Comment by havena** [comment]
i have add a diag_log debug in ace_common_executePersistent, but nothing was call by this fnc... look like ACE_PersistentFunctions is empty so... any idea?

```
// by commy2
#include "script_component.hpp"

PARAMS_1(_target);

{
    if (isNil "_x") then {
        diag_log text format ["[ACE] ERROR: No argument and function for remote function. ID: %1", _forEachIndex];
    } else {
        if (typeName _x == "ARRAY") then {
			diag_log format ["DEBUG ACE executePersistent === %1 - %2 call %3",_x select 0,_target,_x select 1];
            [_x select 0, _target] call (_x select 1);
        };
    };
} forEach (_target getVariable ["ACE_PersistentFunctions", []]);
```

**Comment by ViperMaul** [comment]
Also reference: 
https://github.com/CBATeam/CBA_A3/issues/126

**Comment by PabstMirror** [comment]
Sounds like it's been fixed in CBA thread.
