### ISSUE TITLE
Tactical ladder can only be set upwards

### ISSUE THREAD

**Issue by Ghost77788** [acemod/ACE3#2174]
Would it be possible to add a 3rd option of placement to the ladder.

Now the ladder can only be set from your height upwards against a wall, however when the fastroping is implemented. would it not be nice to be able to use the ladder to get off the roof if that roof doesnt have a ladder of its own or staircase.

A 3rd option where the ladder moves up and down as a whole from the position of the user of the ladder and only be able to move the height downwards as much as the ladder is extended.

Anyway just a thought. Dont know how hard it would be to implement.

**Comment by Ghost77788** [comment]
https://www.dropbox.com/s/7ubd0xum9dpwjcj/ace_tacticalladder.rar?dl=0

I wrote a example for it in here by replacing the angle adjust with the height adjust i was describing.
I added a flip ladder action to the ladder because otherwise the ladder if lowered would be facing towards the building making it impossible to climb down.
Issue 1: adding the flip ladder action to the top of the ladder or adding a setvectordir to the attachto command to flip the ladder in advance.
Issue 2: adding a second modifier to add this option to the ladder, otherwise would have to replace angle adjust.
Issue 3: Ladder going through ground when player on the ground.
Issue 4: Ladder not touching ground when ladder lowered next to building --> floating.

Hope this helps somewhat, would love to have the ability to use the ladder to make more tactical movement decisions.

**Comment by Ghost77788** [comment]
Also just realised that once you used the ladder to get up a building you cant grab the ladder, because the interaction point is add the bottom. Making it a one off item.

**Comment by Ghost77788** [comment]
Issue 1 resolved by adding setdir to attachto.
Issue 3 resolved by adding istouchingground

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
