### ISSUE TITLE
Dead man's switch doesn't work on a dedicated server

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#2175]
ACE3 Version: 3.x.x
3.2.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None.*

**Description:**
*Dead man's switch doesn't trigger the explosion when playing on a dedicated server.*

**Steps to reproduce:**
* *Place an explosive. Trigger it to the dead man's switch. Execute player setdamage 1. Nothing happens.*

**Where did the issue occur?**
*"Multiplayer", Dedicated Server.*

**RPT log file:**
*No need.*

**Comment by PabstMirror** [comment]
Will be fixed in #1902

**Comment by rebelvg** [comment]
Amazing news. Thanks you!
