### ISSUE TITLE
Character stuck when using medical actions.

### ISSUE THREAD

**Issue by Twelvecaliber** [acemod/ACE3#2178]
ACE3 Version: 3.x.x
3.2.1

Mods:

@cba_a3
@ace3

Placed ACE3 Modules:
None

Description:
When using the vanilla weapon resting system, deploy a bipod on a cover object, if player tries to interact with themselves to perform medical actions, their character becomes stuck to the wall after the action is complete.

Steps to reproduce:

Deploy bipod on top of a cover object, like a sandbag.
Apply bandage to a limb.
Enjoy being stuck.

Where did the issue occur?
"Single player", Virtual Arsenal
"Multiplayer", Dedicated Server.

**Comment by Glowbal** [comment]
I cannot reproduce this. Could you provide a video where the issue happens?

**Comment by bux578** [comment]
I can actually reproduce that.
ACE3 3.2.1

**Comment by bux578** [comment]
Once it's processed: https://www.youtube.com/watch?v=pZy0mK_d_-k

**Comment by jonpas** [comment]
BI wiki says doing `unit playMove "";` stops weapon resting/deployment. Most likely `switchMove` does also, which I guess would be best to use to fix #2156 as well.
