### ISSUE TITLE
Repair Helicopter/Tank Script Error

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#2180]
ACE3 Version: 3.2.2.0 9f3af45a8f2e56092015977c66b6b01e0d682685

**Mods:**
* `@cba_a3`
* `@ace3`

**Placed ACE3 Modules:**
* None

**Description:**
When damaging any helicopter and then trying to interact with it the following script error occurs (and interaction menu does NOT render):
```
Error in expression <lity || call _repairVeh}};
};
_return = call _return;
};
};
} forEach _locations>
   Error position: <call _return;
};
};
} forEach _locations>
   Error Generic error in expression
File z\ace\addons\repair\functions\fnc_canRepair.sqf, line 73
```
Happens on both Standard and Advanced Flight Model, rendering helicopters unable to repair.

**Steps to reproduce:**
* Load into a mission as an `Engineer` next to a helicopter
* Damage the helicopter
* Open interaction menu (or try to)
* Observe the script error

**Where did the issue occur?**
Singleplayer - Editor

**RPT log file:**
N/A

**Comment by jonpas** [comment]
Happens also on Tanks.

**Comment by PabstMirror** [comment]
Fixed via 359ee1d23b4ba9b1b392f6e7bc74d83f8ba5aeba

**Comment by Glowbal** [comment]
Nice going @PabstMirror :+1:

**Comment by jonpas** [comment]
:+1:
