### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by ElTyranos** [acemod/ACE3#2188]
ACE3 Version: 3.2.1 (stable)

**Main Mods:**
* @cba_a3
* @RHSUSF
* @RHSAFRF
* @Leights OPFOR
* @AllInArmATerrainPack

**Small Mods wich could break :**
* @UK3CB
* @ten_switchweaponswhilemoving
* @zade_boc
* @action_button_mod

**Placed ACE3 Modules:**
None

**Description:** Only log spam, no error in game.
**Steps to reproduce:** just play and look for 

**Where did the issue occur?**
*Multiplayer*

**RPT log file:**
*http://battlegroup21.com/download/arma3_2015-08-15_19-38-45.rpt*

**Comment by jonpas** [comment]
Please follow http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by ElTyranos** [comment]
My bad, updated with full RPT

**Comment by jonpas** [comment]
> If you've found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using only `@CBA_A3` and `@ace` on a newly created mission.

Do that please, if you find out that with only those 2 mods you don't get any RPT spam, a problem is with one of the other mods you are using, best way to test is adding them gradually and in different combinations.

**Comment by PabstMirror** [comment]
I believe something is weird with your ace_settings. (they are undefined or array counts are wrong??)

Open the ace settings, and hit reset and then restart the mission.

Also, please try with just CBA/ACE and then readd all mods and test. It could be a mod conflict.

**Comment by ElTyranos** [comment]
Hello,

I've done some further investigations.

Dedicated server : CBA v2.0 +  ACE3 v3.2.1
Userconfig : http://pastebin.com/fw9kmLMW
Result : spam log

LAN server : CBA v2.0 +  ACE3 v3.2.1
No userconfig
Result : no spam log

I'll try to tweak my userconfig later this day.

**Comment by ElTyranos** [comment]
Fixed with this userconfig : http://pastebin.com/9vQttfuY
It has less forced "client settings", only nametags, other are not specified. It also fixed finger pointing wich was broken with former userconfig. I hope that will help to find out some issues by comparing both files.

Thank you for your time and best regards

**Comment by PabstMirror** [comment]
The color arrays were being exported wrong
it should be fixed in next branch,

otherwise you could carefully remove all color settings when exporting on current.

**Comment by jonpas** [comment]
> it should be fixed in next branch,

:banana:
