### ISSUE TITLE
Unable to load arrested people in vehicle

### ISSUE THREAD

**Issue by Knight1981** [acemod/ACE3#2199]
ACE3 Version: 3.2.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
basic medic system

**Description:**
Hey guys,

yesterday we played a rescue mission on our dedicated server. Therefore we have arrested the person and escorted him to an evac helicopter (in this case it was a Little Bird). That worked very well, but than we were not able to load the arrested person in the vehicle because no menu / option for this appeared. Could you please check this?

Thank you very much. :)

**Steps to reproduce:**
1. Arrest AI
2. Escort to a Little Bird
3. Try to load the arrested AI into the Helicopter

**Where did the issue occur?**
Multiplayer, dedicated server

**RPT log file:**
n.a

**Comment by PabstMirror** [comment]
You have to be Escorting the captive to have the "load in vehicle" interaction show.
The action shows on the vehicle (you have to look through the captive).

There is also an action on the captive himself while escorting, but it is extremely awkward to access.


I would break this issue into 2 parts,

* Code failure: Do you think you where using it correctly and it failed to work? 

* Design: For ease of use, would it make sense to remove the "isEscorting" requirement.  IE, make it so a captive near a vehicle will just have a "load into vehicle" interaction on him. I don't see any harm, and I think it would make things cleaner and easier to use.

**Comment by Knight1981** [comment]
Thank you for your answer. It is possible that we made a mistake, I will check it later and let you know if it works as you described.

But yeah, it is a little bit confusing (4 guys didn't know how to load the captive) :D I think it would be more easier when the captive is near the vehicle and you can look at him and say "load captive into vehicle". That would be the same behaviour as for patients.

Thank you :)

**Comment by Ghost77788** [comment]
This is because the check on helicopters is broken within the doloadcaptive.sqf.
Is resolved in next update for ACE 3

**Comment by Knight1981** [comment]
Ah okay, thank you for this information :) We wait eagerly for the next ACE update because of some other hotfixes (e.g. camp fire issue, slide show broken etc.). 

When can we expect the next release?

**Comment by bux578** [comment]
> When can we expect the next release?

You won't get any ETA's from us. The version has to be ready codewise and has to be at least somewhat tested (preferably properly tested).

**Comment by Knight1981** [comment]
Okay I checked it again today and yes, it is a problem with the little bird. I can load the captive in a Hunter etc. but not in the Little Bird. I think this has nothing to do with the captive module because I get no "option" on the little bird as Ghost77788 described before.

I didn't checked it with other helicopters but I believe this is not only with the Little Bird. Thank you.

**Comment by PabstMirror** [comment]
@Ghost77788 thank you, yes it was a code problem (#2132) that will be fixed for next release; 

I still want to remove the escorting requirement, it should match the functionally of loading unconscious.

**Comment by Ghost77788** [comment]
/*
 * Author: Glowbal
 * Action for loading an captive unit in the nearest vehicle
 *
 * Arguments:
 * 0: The loader <OBJECT>
 * 1: The captive <OBJECT>
 *
 * Return Value:
 * NONE
 *
 * Public: No
 */

#include "script_component.hpp"

PARAMS_3(_caller,_target,_vehicle);
private ["_caller", "_target","_vehicle"];

if !(_target getVariable [QGVAR(isHandcuffed), false]) exitWith {
    // TODO localization
    ["displayTextStructured", [_caller], [["This person (%1) is not handcuffed and cannot be loaded", [_target] call EFUNC(common,getName)], 1.5, _caller]] call EFUNC(common,targetEvent);
};
if (_caller getVariable [QGVAR(isEscorting), false]) then {
    [_caller,_target, false] call FUNC(doEscortCaptive);
};

if (isNull _vehicle) then {
    _objects = nearestObjects [_unit, ["Car", "Tank", "Helicopter", "Boat", "Plane"], 10];
    if ((count _objects) > 0) then {_vehicle = _objects select 0;};
};

["MoveInCaptive", [_target], [_target, _vehicle]] call EFUNC(common,targetEvent);

///////////////////////////////////////////////
///The ace action ///
///////////////////////////////////////////////
				class ACE_LoadCaptive
				{
					displayName = "$STR_ace_captives_LoadCaptive";
					distance = 4;
					condition = QUOTE(_target getvariable[ARR_2(QUOTE(QUOTE(isHandcuffed)),false)] && vehicle _target == _target);
					statement = QUOTE([ARR_3(_player, _target, objNull)] call DFUNC(doLoadCaptive));
					exceptions[] = {"isNotEscorting"};
					showDisabled = 0;
					icon = "\z\ace\addons\captives\UI\captive_ca.paa";
					priority = 2.2;
					hotkey = "L";
				};

**Comment by Ghost77788** [comment]
Like this???
Hope this helps otherwise just ignore.

**Comment by kripto202** [comment]
what kind of heli were you trying to use?

**Comment by Ghost77788** [comment]
https://www.dropbox.com/s/huteenhfhmw1x4m/ace_captives.rar?dl=0

I made it now so that you can load the captive when not escorting either by interacting with captive or vehicle.
Only issue is: by removing exceptions[] = "isnotescorting"; from ACE_LoadCaptive, it no longer gives the option to load captive when escorting. so you would have to first release captive and then interact.
But i might have missed something with all the alterations.

Also sorry for not putting this in a pull request or similar.
Just not experienced with github and i modified quite a few functions.
