### ISSUE TITLE
MRCO zoomed out view is vanilla

### ISSUE THREAD

**Issue by TheConen** [acemod/ACE3#2205]
ACE3 Version: 3.2.1. dev (latest commit: 42bd8751aa8b1937e5fd4b7df187c302209fe708)

**Mods:**
- @cba_a3
- @ace3

**Placed ACE3 Modules:**
none

**Description:**
The "zoomed-out" view of the MRCO scope is the vanilla one.

**Steps to reproduce:**
Equip weapon with the MRCO scope, switch between the two optic modes. Also see attached screenshots.
![arma3 2015-08-19 03-36-00-147](https://cloud.githubusercontent.com/assets/7814881/9347142/1bf47c52-4626-11e5-81e7-1a27d14baacb.png)
![arma3 2015-08-19 03-36-02-296](https://cloud.githubusercontent.com/assets/7814881/9347143/1e6c41a4-4626-11e5-86ee-a13c294ce21d.png)

**Where did the issue occur?**
Tested only in editor, but I assume it appears everywhere.

**RPT log file:**
N/A

**Comment by PabstMirror** [comment]
I'm not seeing what the problem is.
As far as I know the 2d scopes only changed the zoomed in view.

**Comment by TheConen** [comment]
The RCO and the ARCO scope have a red dot sight mounted upon them, so changing only the zoomed in view and keep the normal red dot sight is the correct behavior. The MRCO scope however uses the same scope for zoomed in and zoomed out view, so the zoomed out view should show the same reticle as the zoomed in view (maybe zoomed in and zoomed out is the wrong description, I'm talking about changing the scope mode with STRG+RMB).

**Comment by commy2** [comment]
This is the reticle BI had for that scope before it was changed. Someone has to redraw it.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
