### ISSUE TITLE
MRCO scope has only 2D version

### ISSUE THREAD

**Issue by TheConen** [acemod/ACE3#2206]
ACE3 Version: 3.2.1. dev (latest commit: 42bd8751aa8b1937e5fd4b7df187c302209fe708)

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
none

**Description:**
There exists only a 2D version of the MRCO scope - or at least only a 2D version is shown in the arsenal and present in the ACE3 Misc items box. As there also is a PiP version of every other scope ACE3 adds, I assume this is a bug - if not, ignore this report and just close or delete it.

**Steps to reproduce:**
Try to equip your weapon with a MRCO PiP scope.

**Where did the issue occur?**
Tested only in editor, but I assume it appears everywhere.

**RPT log file:**
N/A

**Comment by commy2** [comment]
No bug. There is PIP version for this, because the assets I was given don't fit.

**Comment by commy2** [comment]
Dup of https://github.com/acemod/ACE3/issues/918 and https://github.com/acemod/ACE3/pull/919

Maybe some day.
