### ISSUE TITLE
Explosive code messages are printed in normal chat instead as ACE3 message

### ISSUE THREAD

**Issue by TheConen** [acemod/ACE3#2208]
ACE3 Version: 3.2.1. dev (latest commit: 42bd8751aa8b1937e5fd4b7df187c302209fe708)

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
none

**Description:**
When placing a trigger on an explosive, the message about the explosive code is printed in the normal chat. In our community we use an addon that completely disables/blends out the chat, and I can imagine that several communities, especially MilSim communities, completely disable the chat, too. As ACE3 has an own message system to display messages in the upper right corner of the display, I suggest to move the message to the ACE3 message system. I know this is more of a feature request/enhancement, but as it isn't a completely new feature, I felt it was no case for the feature request ticket. If I am wrong there, please correct me and I will post future enhancements there.

**Steps to reproduce:**
Place an explosive and arm it with a detonator.

**Where did the issue occur?**
Tested only in editor, but I assume it appears everywhere.

**RPT log file:**
N/A

**Comment by PabstMirror** [comment]
Yeah it is a bit jarring to see the blue "side chat".

I know channels can be disabled via desciption.ext and I'm not sure how it would work.

In any case, I think moving it to ACE's own message system makes sense.

**Comment by jonpas** [comment]
> In any case, I think moving it to ACE's own message system makes sense.

:+1:

**Comment by xJenny99x** [comment]
To disable channels.

disableChannels[]={0,1,2};

/* 0 = Global
   1 = Side
   2 = Command
   3 = Group
   4 = Vehicle
   5 = Direct
   6 = System */
