### ISSUE TITLE
All body parts start bleeding when taking minor fall damage

### ISSUE THREAD

**Issue by captainblaffer** [acemod/ACE3#2209]
ACE3 Version: 3.2.1

Mods:
@ace;@CBA_A3;

Placed ACE3 Modules:
none

Description:
All body parts start bleeding (yellow) when taking minor fall damage.
Would it be possible to improve this behavior? E.g. only legs start bleeding, or no bleeding at all?

Steps to reproduce:
1. Fall of a small height, ~2 meter. Player character should take minor damage.

Where did the issue occur?
Dedicated

RPT log file:
n/a

**Comment by NouberNou** [comment]
Are you sure you can reproduce this still in the latest version?

**Comment by Glowbal** [comment]
What are the medical settings you used?

**Comment by captainblaffer** [comment]
Can still reproduce on 3.2.1.0 , video: https://youtu.be/r7Ybdvr4tN0

using simple medical settings.

The issue doesn't always seem to happen though. Yesterday I fell off the same building as in the video, and only a few bodyparts started bleeding.

**Comment by captainblaffer** [comment]
It would be great to see this issue prioritized for a fix. Thank you!

**Comment by Cuel** [comment]
I've seen this multiple times. Agree.

**Comment by commy2** [comment]
Please don't bump old tickets with messages like "please prioritize this issue". That is not helpful and rude.

**Comment by PabstMirror** [comment]
Fixed via #3629
