### ISSUE TITLE
battle eye blocks ace 3 DLL files

### ISSUE THREAD

**Issue by SharonX4** [acemod/ACE3#2210]
work in single\multiplayer
pic:
https://embed.gyazo.com/915bce373e915884ee85629f5b6f886d.png

and then when i try join the server/open the mission
i got error file "XXX.dll" not installed

**Comment by PabstMirror** [comment]
We've seen this sometimes when using a custom launcher, the battleye dlls don't get updated:

From #1926
>Okay figured it out, you need to launch the arma 3 launcher first for battleye to update itself, if you launch it through command lines it doesn't give a fuck and doesn't update I'll add this to the wiki beause this is a very important thing to know.

If that doesn't work I think you can manually update BE: http://www.battleye.com/downloads/

**Comment by SharonX4** [comment]
i download the services and the client?

**Comment by PabstMirror** [comment]
Looks like you will need both

and then I think you place them in ArmA 3 folder / battleye:
e.g.:
`C:\Program Files (x86)\Steam\steamapps\common\Arma 3\BattlEye`

**Comment by SharonX4** [comment]
no help

**Comment by PabstMirror** [comment]
Fully delete the @ACE folder
and reinstall from https://github.com/acemod/ACE3/releases/tag/v3.2.1

**Comment by SharonX4** [comment]
nope

i found out that i lunch it from PWS with this mod list it get blocked:
     @ace3
         @allinarmaterrainpack
          @ares
         @asdg_jr
        @burnes_mk10
        @cba_a3
        @ctab
          @eods
       @hiddenidentityv2
         @isladuala_a3
         @isrtg_uniforms
       @leights_opfor
          @mcc_sandbox_a3
         @panthera_a3
        @prkz
       @rds_civpack
       @rhs_afrf3
         @rhs_usf3
          @sthud_a3
    @st_stamina_bar
         @tao_foldmap_a3
@task_force_radio

**Comment by ViperMaul** [comment]
We have an email from BattlEye, 
> Hi,
>
>It [ACE3 DLLs] was already automatically whitelisted, so it's safe for you to do releases without waiting for us in the future.
>
>Regards,
>Bastian Suter
>BattlEye Innovations

So something seems to be different with your situation.

**Comment by SharonX4** [comment]
for unknown reason the problem seen to be fixed....
