### ISSUE TITLE
Latest CBA

### ISSUE THREAD

**Issue by dvdbrewster** [acemod/ACE3#2212]
Playing BECTI Laser pointers from ACE support fail to attatch to weapons.  Just since last night, Updated this A.M.  with Latest CBA.. no other changes.  ( AIATP, RealArmor,MAO_BloodMist,ACE3}
 Also the option to switch laser modes makes a sound but there is no dialogue window to indicate the mode of the BI laser pointers;
  @ pabst  U R right it fixed the problem.

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by PabstMirror** [comment]
CBA now has JR integrated.  So for now you will want to copy the JR compat pbo from ace options to ace addons.

I believe this will be really fixed by #2212

**Comment by jokoho48** [comment]
@PabstMirror you mean #2211

**Comment by dvdbrewster** [comment]
Seems to work now
