### ISSUE TITLE
Stuck in interact screen

### ISSUE THREAD

**Issue by Alex150201** [acemod/ACE3#2215]
I wanted to change the interact key from left windows key to shift+windows key. It said double click on what you want to change and change it. When i did the key disappearing. I tried resetting it to the old settings, restarting the game, re-installing the mod, re-downloading the mod, re-installing cba, re-downloading cba and still nothing! This has really become an issue for me and as much as i want to use ace 3 i cant due to that issue. Like you said i have tried launching it alone only with cba and no other mods but nothing. I have tried logging in other maps but every time i spawn the interact screen is flashing with the cursor appearing and disappearing every 0.01 seconds. Please fix this as soon as possible because ace 3 is a mod that everyone needs for their milsim community!

I recorded a video of this issue because i thought it would be better than just a screenshot.
LINK: https://www.youtube.com/watch?v=q5zc1Mt8LPc&feature=youtu.be

**Comment by bux578** [comment]
If you really want to reset it, create a new arma 3 profile. IIRC it's in the main menu -> "Configure" -> "Profiles" (or similar).

**Comment by SilentSpike** [comment]
I don't recommend creating a new profile, however you may see here for how to fix a corrupt keybinding registry: https://github.com/CBATeam/CBA_A3/wiki/Keybinding

This is likely CBA's "fault" (really just an unfortunate edge case bug)

**Comment by Alex150201** [comment]
SilentSpike what you are telling me to do is impossible since when i am in the editor, virtual arsenal, mission anything and what is happening on the video is happening i cant press esc to go in the debug like that link says. I can only shut the game down by doing ctrl+alt+delete and using the task manager. bux578 i will attempt finding that profile save and fixing the key like that if i cant then i might have to create a new profile

**Comment by SilentSpike** [comment]
it happens in the editor too? :fearful:

**Comment by Alex150201** [comment]
The video i recorded was me pressing preview in the editor and then that happens.

**Comment by SilentSpike** [comment]
Ah right, you can access the debug console in the actual editor though (it's on the top bar)

**Comment by Alex150201** [comment]
oh wait really?

**Comment by Alex150201** [comment]
Do i just execute this in the debug of the editor and it fixed the problem?
profileNamespace setVariable ["cba_keybinding_registry", []]; saveProfileNamespace;

**Comment by SilentSpike** [comment]
It will hopefully fix the problem yeah

**Comment by Alex150201** [comment]
It doesnt fix the problem... If i go in the editor and put a unit in the Intro mode then i can press escape and check the keys, but the keys are still not there. Also i attempted on changing another key and when i double clicked it it dissapeared like the interaction key. Am I at the point where the only fix is a new profile?

**Comment by SilentSpike** [comment]
Hmm, in that case you might as well try a new profile to see if it fixes the problem. We could just be looking in the wrong place.

**Comment by kripto202** [comment]
have you tried redownloading ace and/or cba?

**Comment by kripto202** [comment]
Isnt there a location where you can change your key without going in-game and change the settings? If that is possible, I would suggest going that route.

**Comment by Alex150201** [comment]
for your first question read the post again
for the second question i tried but couldnt find the keys

**Comment by Dobakjang** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

kgino1045@naver.com 님께 보내신 메일 <Re: [ACE3] Stuck in interact screen (#2215)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by PabstMirror** [comment]
Try running:
```
profileNamespace setVariable ["cba_keybinding_registryNew", nil];
saveProfileNamespace;
```
and restarting the mission.

**Comment by NouberNou** [comment]
Make an issue on the CBA tracker if this continues to be an issue.
