### ISSUE TITLE
Can't use spaces in interaction names for Slideshow module

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2222]
ACE3 Version: 3.2.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *Slideshow*

**Description:**
*See below.*

**Steps to reproduce:**
* *Setup slideshow properly then place one image and enter interaction name:*

`Slide 1 of 2`
* *Enter game and notice that interaction is named:*

`Slide1of2`

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*-*

**Comment by jonpas** [comment]
That's because whitespaces get removed from strings in the slideshow module (same as in many other modules that take strings, eg. lists). I can add an exception for this one.

Note to self: Keep removal of whitespace after the comma.

**Comment by Glowbal** [comment]
I'd suggest to replace the removal of all whitespace by just trimming the start and end of each element.

**Comment by jonpas** [comment]
That's the idea we came up with joko last night as well. :)

**Comment by jokoho48** [comment]
CBA_fnc_trim
