### ISSUE TITLE
GBU-12  with Laser Designator

### ISSUE THREAD

**Issue by mrraymond** [acemod/ACE3#2227]
I can not see my Laser target when using GBU-12(all laser designator tested,even uav),but with AGM-65 its working.Maybe ACE3 not support?

**Comment by MikeMatrix** [comment]
Thanks for your effort of reporting this. Sadly this doesn't contain enough information to go off. Please make sure to read http://ace3mod.com/wiki/user/how-to-report-an-issue.html to give us a baseline of information, that we can use to resolve this issue.

**Comment by nibbles-** [comment]
@mrraymond https://github.com/acemod/ACE3/issues/1363
