### ISSUE TITLE
Players being to civ side/captive from bluefor with join/leave group

### ISSUE THREAD

**Issue by Glowbal** [acemod/ACE3#223]
Some people appeared to turn captive/civilian while messing around with join/leave group.

* All units where originally bluefor.
* Units were joining/leaving each others team. 
* Suddenly two players became either captive or civilian side.
* hint str side player resulted in CIV.

Fixed by running `setCaptivityStatus` and `[player] join group cursortarget` with cursortarget being a bluefor unit.

**Comment by commy2** [comment]
Related: https://github.com/acemod/ACE3/issues/527
