### ISSUE TITLE
Option Menu RTP Issue

### ISSUE THREAD

**Issue by jokoho48** [acemod/ACE3#2240]
ACE3 Version: 50e851d

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None

**Description:**
RTP Issue and no Options in Options Menu

**Steps to reproduce:**
Open Options Menu in Game

**Where did the issue occur?**
Singleplayer/Editor

**RPT log file:**
http://pastebin.com/uT7eN2pr

**Comment by Dobakjang** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

kgino1045@naver.com 님께 보내신 메일 <[ACE3] Option Menu RTP Issue (#2240)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by PabstMirror** [comment]
RPT is really weird, there is no

```
 [ACE] Settings received from server
 [ACE] Settings initialized
[ACE] Waiting on settings from server
```

This isn't just option menu, it may be critical, but I can't reproduce on master.

Can you check these 2 variables for me
`ace_common_commonPostInited`
and 
`SLX_XEH_MACHINE`

**Comment by Dobakjang** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

kgino1045@naver.com 님께 보내신 메일 <Re: [ACE3] Option Menu RTP Issue (#2240)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by jokoho48** [comment]
ace_common_commonPostInited == true;
SLX_XEH_MACHINE == [true,false,false,true,false,true,true,true,true,false,1,2,0,false,3,["Arma 3","Arma3",148,131645,"Stable",true]];

**Comment by jokoho48** [comment]
http://puu.sh/jLMLL/cb91e02457.jpg

**Comment by jokoho48** [comment]
issue was Client side i load a Mix out of 2 CBA versions
