### ISSUE TITLE
1.56 New Commands Conversion

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#2241]
- https://community.bistudio.com/wiki/selectRandom
`selectRandom _arr`
`_arr select floor random count _arr`

- https://community.bistudio.com/wiki/apply
`[1,2,3] apply {_x * 2}`
`[[1,2,3], {_this * 2}] call ACE_common_fnc_map`

- https://community.bistudio.com/wiki/select
`[1,2,3,4] select {_x > 2}`
`[[1,2,3,4], {_this > 2}] call ACE_common_fnc_filter`

- http://feedback.arma3.com/view.php?id=26682
 `["one", "two", "three"] param [[1, 2, 3] find 5, "not found"]`
`["not found", "one", "two", "three"] select (([1, 2, 3] find 5) + 1)`
Note: `param` does not set the variable to private like `params`

___________________

Direct conversions:
- [x] To `joinString` from
  - [x] `CBA_fnc_join`
- [x] To `splitString` from
  - [x] `CBA_fnc_split`
  - [x] `BIS_fnc_splitString`
- [ ] To `AGLToASL` from
  - [ ] `FUNC(positionToASL)`
  - [ ] `EFUNC(common,positionToASL)`
- [ ] To `ASLToAGL` from
  - [ ] `FUNC(ASLToPosition)`
  - [ ] `EFUNC(common,ASLToPosition)`
- [x] ~~To `#include "..\"script_component.hpp"` (inside `function` folders) from~~
  - [x] ~~`#include "\z\ace\addons\<component>\script_component.hpp"`~~
  - We won't be doing this :+1:

Other improvements (just for reference, not necessary to complete this issue):
- `lineIntersectsSurfaces` - major improvements (attach, frag, missile guideance, laser ...)
- `getAllHitPointsDamage` / `setHitIndex` / `getHitIndex` - can make repair work on sub turrets that have identical hitpoint names
- `getModelInfo` - should improve wire cutters
- `didJIP` - JIP detect in `common`
- `magazinesAllTurrets` - rearming
- `objectParent`

Add others in comments. Those checked off above are either done or not found in ACE3 codebase.

**Comment by Dobakjang** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

kgino1045@naver.com 님께 보내신 메일 <[ACE3] 1.50 New Commands Conversion (#2241)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by SzwedzikPL** [comment]
`remoteExec` :+1:

**Comment by Dobakjang** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

kgino1045@naver.com 님께 보내신 메일 <Re: [ACE3] 1.50 New Commands Conversion (#2241)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by SilentSpike** [comment]
I don't know if remoteExec is a great idea. I haven't looked into the "security" functionality of it yet, could users theoretically break code that uses it?

**Comment by jonpas** [comment]
@SilentSpike They've added a great deal of security functionality to it, from quick BIKI read you can now white-list things through `CfgRemoteExec`. I was just thinking it could be a better replacement in terms of performance for the current remote execution framework in ACE3.

**Comment by SilentSpike** [comment]
I mean to say, would the security functionality result in ACE scripts being blocked if the user configures it a certain way

**Comment by bux578** [comment]
Afaik, it would. Server admins can disable RemoteExec completely.

**Comment by jonpas** [comment]
Ah, I see.

**Comment by SilentSpike** [comment]
Kinda defeats the whole purpose of the command :stuck_out_tongue: Good job BI :star2:

**Comment by bux578** [comment]
It's for Alive, Koth, Epoch etc... servers

**Comment by PabstMirror** [comment]
Easy, drop-in stuff:
- [ ] `AGLToASL` replaces fnc_positionToASL.sqf
- [ ] `ASLToAGL` replaces fnc_ASLToPosition.sqf
- [ ] # include supports parent folders `#include "..\scriptComponent"`

Non-trivial:
- [ ] `lineIntersectsSurfaces` - amazing (attach, frag, missle guideance, laser) can all be improved
- [ ] `getAllHitPointsDamage` / `setHitIndex` / `getHitIndex` - can make repair work on sub turrets that have identical hitpoint names
- [ ] `getModelInfo` should improve wire cutters

**Comment by SilentSpike** [comment]
`isJIP` can probably be used for something in common

**Comment by SzwedzikPL** [comment]
`shownHUD`, `showHUD` for https://github.com/acemod/ACE3/pull/1857
Propably `magazinesAllTurrets` for rearming ? @GitHawk ?

**Comment by GitHawk** [comment]
Thanks @SzwedzikPL 
May make determining if a vehicle can be rearmed easier

**Comment by PabstMirror** [comment]
common's jip detect on line 320 in postInit is wrong and runs on all clients,
replace with new isJip and then verify that fixing doesn't break anything in medical which uses that event

**Comment by SzwedzikPL** [comment]
`getAllHitPointsDamage` for getHitPoints. I think it can solve https://github.com/acemod/ACE3/issues/2259

**Comment by jonpas** [comment]
Can someone confirm how **exactly** `remoteExec` works? If used from the server it should still be allowed no matter what, is that correct? And so only client execution of it can be restricted.

**Comment by SzwedzikPL** [comment]
From https://community.bistudio.com/wiki/Arma_3_Remote_Execution
>Note: Server doesn’t have any limitations at place, everything is enabled and opened for him. All limitations and rules apply only for client(s).

**Comment by SzwedzikPL** [comment]
Seems that `magazinesAllTurrets` and `shownHUD` are not available in 1.50 :|

**Comment by PabstMirror** [comment]
AGLToASL - positionToASL are not equal

Our positionToASL is wrong, it converts to ASLW.

When standing on docks:
`(player modelToWorld [0,0,0])` = `getPosASLW player` //Moves with waves (ASLW)
`(player modelToWorld [0,0,0]) call ace_common_fnc_positionToASL` returns ASLW

`getPosASL player` == `aglToAsl (player modelToWorld [0,0,0])` //Static, not moving

https://community.bistudio.com/wiki/Position#PositionAGL is a great reference.

>modelToWorld, worldToModel, modelToWorldVisual, worldToModelVisual, positionCameraToWorld, intersect, terrainIntersect, isOnRoad, drawIcon3D, drawLine3D, distance, moveTo, doMove, move, setDestination, buildingPos, screenToWorld, worldToScreen, AGLToASL, ASLToAGL

are all "AGL".

Because our function isn't right, we need to be careful when converting (EG, interaction menu expects the "wrong" value)

**Comment by jonpas** [comment]
I recommend renaming `positionToASL` to `positionToASLW` during the conversion process.

**Comment by jonpas** [comment]
#2319 #2311

**Comment by SilentSpike** [comment]
Edited OP as we won't be using the relative filepaths

**Comment by commy2** [comment]
I'll re-implement the laserpointers (for BWMod) using `lineIntersectsSurfaces` and port it then to ACE3.

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/pull/2328

**Comment by commy2** [comment]
#2893

**Comment by commy2** [comment]
Udated OP for upcoming 1.56.

**Comment by PabstMirror** [comment]
```
[{
    params ["_args"];
    diag_Log text format ["_args %1", _args];
    _args params ["_count"];
    _count = _count + 1;
    _args set [0, _count];
    (_count > 3);
},
{
    diag_Log text format ["Done %1", _this];
}, [[0]]] call ace_common_fnc_waitUntilAndExecute
```
Right now this will run forever because we make a deep copy of `GVAR(waitUntilAndExecArray)`.  Switching the implementation to
```
    GVAR(waitUntilAndExecArray) = GVAR(waitUntilAndExecArray) select {
        if ((_x select 2) call (_x select 0)) then {
            (_x select 2) call (_x select 1);
            false
        } else {
            true
        };
    };
```
Will terminate, which I think would be desired behaviour as it lets us use those params to store array references (and works just like PFEH).

**Comment by SilentSpike** [comment]
Just because I'm not sure what the status is, figure I'll mention that issue #2848 can probably now be fixed with some of the new array related commands.

(Think the HuntIR code also still needs to be looked at, but doesn't seem like a priority)

**Comment by commy2** [comment]
`param` is broken again don't use that one with `find`.
