### ISSUE TITLE
"camcreate" command non-functional while 3.2.1 is loaded

### ISSUE THREAD

**Issue by shindiggs** [acemod/ACE3#2248]
ACE3 Version: 3.2.1 Stable

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *none*

**Description:**
The "camCreate" sqs command doesn't do anything while 3.2.1 is loaded.

**Steps to reproduce:**
* Create a mission on any map
* Place a "player" unit and an object that can be used as a camera (I used a gamelogic)
* In the camera object's init, execute an "example.sqs" file
* Save the mission as a user mission
* In the mission folder create an "example.sqs"
* Edit the "example.sqs" and enter a camCreate command, example:

_camera = "camera" camCreate [0,0,0]
_camera cameraEffect ["internal", "back"]
* Save the sqs file and the mission.
* Preview the mission in editor, or export it and play it in singleplayer or multiplayer.

The custom camera will not be created and will not return any script errors.

**Where did the issue occur?**
*Singleplayer, Multiplayer*

**RPT log file:**
*http://pastebin.com/cvam1MGc*

**Comment by PabstMirror** [comment]
I think this is the same issue as #1461. Something with ace_optics messes with camera scripts.

Possible fix:
>In the meantime, just add a ~0.25 to the top of your intro.sqs to let our script finish before starting your camera.
