### ISSUE TITLE
Medical UI feedback

### ISSUE THREAD

**Issue by Glowbal** [acemod/ACE3#226]
Feedback from testers for the medical UI.

>    Medical feels unclear, patch a guy up and he's all white but I assume he isn't a 100%? Users could be confused because I am. Suggestions, below.

> *    Symbol to show where tourniquets are located.
> *    Some indication if a body part has been bandaged.
> *    UI to show blood pressure and heart rate, keep as question-marks until you know?
> *   Change menu headline INJURIES to something like STATE or OVERALL STATE.

> -Knudsen

**Comment by bux578** [comment]
Do we need this issue? we have the #medical channel in slack?!

**Comment by Glowbal** [comment]
This can be closed.
