### ISSUE TITLE
cant open the interaction menu

### ISSUE THREAD

**Issue by 123aqw** [acemod/ACE3#2266]
i dont know what the issue is but i can open the iteraction menu i get a red circle middle of my screen but nothing else can someone help i dont know if this is an issue sorry if i am at the wrong place :)

**Comment by PabstMirror** [comment]
* Could you please include a RPT file (can be found in %localappdata%/Arma 3/ and look for the most recent file likearma3_2015-08-01_22-17-40.rpt and dump it on pastebin.com)
* Does self interaction work? (ctrl-win)?
* Please try adding the CBA compat pbo, and make sure you are running the most recent version of CBA.

>We have noticed that when using ACE with 3rd-Party mods that do not fully support CBA Extended Eventhandlers (XEH) that some units do not work with Interaction fully. You may see the cursor but no menus.

>  Move the cba_enable_auto_xeh.pbo and its signature file from the CBA optional folder to the CBA Addons folder

**Comment by Faggot16** [comment]
I'm getting the same thing, but it's when I load up the/a singleplayer Campaign mission from a save. The interaction menu straight up breaks and is unusable.

I know I should put in a RPT file, but I was just looking for something breifly to see if I can fix it or if this has to be changed via an Update.

I also have a good feeling someone else has come across this, too though.

**Comment by alganthe** [comment]
It has been stated times and times that ACE3 doesn't support Singleplayer at the moment.

**Comment by Faggot16** [comment]
I see.

**Comment by Faggot16** [comment]
.

**Comment by 123aqw** [comment]
the ctrl+win  dosent work let me see if i can get a pastebin for you :)

http://pastebin.com/a2kiw09i what is CBA compat.pbo? where do i find it ?

**Comment by 123aqw** [comment]
i did reinstall cba did move the stuff from the CBA optinals to the addons that didnt work did reinstall the ace3 didnt work here is the link to the pastebin http://pastebin.com/wCfKUZAx hope u can respond as soon as possible want to play more realistics with my friends :) my friend got the same problem too :( hope u resbond soon :)

**Comment by 123aqw** [comment]
i do play multiplayer for this :)

**Comment by 123aqw** [comment]
can someone help i get a red cirlce on my screen when pressing win key and ctrl+win but i dont get menu etc :( thats my problem can someone help me? what info do u guys need?

**Comment by Shadowmarine578** [comment]
Ok did you move the keys folder into your ARMA 3 root folder and did you move the userconfig from ace into your userconfig folder? One of the guys in my unit had the same problem that fix it for him otherwise it's another mod conflicting with Ace

**Comment by PabstMirror** [comment]
@123aqw is this still an issue?
Please try the most recent versions of both mods:
https://github.com/CBATeam/CBA_A3/releases/latest
https://github.com/acemod/ACE3/releases/latest
