### ISSUE TITLE
Pressing the weapon deploy key while sitting with a deployable weapon breaks sitting

### ISSUE THREAD

**Issue by Tenga** [acemod/ACE3#2267]
ACE3 Version: 3.2.1 (Dev build 131963, probably on stable as well)

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* ACE_ModuleSitting

**Description:**
After sitting, hitting the "weapon deploy" removes you out of the sitting animation, but retains the direction locking check. You're still considered sitting and you can exit the sitting state by using the self interact.

**Steps to reproduce:**
* Place down player as regular rifleman
* Place down ACE_ModuleSitting
* Place down Empty > Objects (Camping) > Camping Chair (Land_CampingChair_V2_F)
* Sit on the chair using the ACE interaction menu
* Hit your weapon deployment key, observe the character getting deployed on the back of the chair
* Exit weapon deployment, run around and attempt to turn in circles, observe that your orientation is reset to the facing you're restricted to in the chair
* Observe that you can "Stand up" by using self interaction

**Where did the issue occur?**
* Singleplayer

**Comment by bux578** [comment]
duplicate and already fixed on master: https://github.com/acemod/ACE3/issues/1937

**Comment by Tenga** [comment]
Ha. I saw that issue, formatted the title in the same way but it never dawned on me it might be the same issue because I have combat pace and deploy on separate keys. :smile:

**Comment by bux578** [comment]
@jonpas could you check that, please?

**Comment by jonpas** [comment]
Will do.

**Comment by jonpas** [comment]
Confirmed again @bux578

**Comment by bux578** [comment]
awesome, thank!
