### ISSUE TITLE
Speedy Gon' Zalas - Quick switching (Request)

### ISSUE THREAD

**Issue by Faggot16** [acemod/ACE3#2272]
Perhaps something like "Quick Grenade Launcher Shot" for when switching between weapon modes takes too long? Perhaps the same thing for grenade throwing mode, such as <command for it here> + 1-4 or something like that?

This could go onto other things; where (it could be able to be) easily applied.

**Comment by bux578** [comment]
Thank you for your request, but this a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html

**Comment by Faggot16** [comment]
Sorry, new to this. Thanks for telling me there is such an area, I was kind of looking for that.
