### ISSUE TITLE
RHS buckshot no Damage / Wounds AdvancedMedical

### ISSUE THREAD

**Issue by Th3Cr0w** [acemod/ACE3#2274]
**ACE3 Version: 3.2.1**

**Mods:**

    @cba_a3
    @ace3
    @RHSUSAF
    ace_compat_rhs_usf3.pbo

**Placed ACE3 Modules:**

    ACE_moduleMedicalSetting
    ACE_moduleAdvancedMedicalSettings

**Description:**

"rhs_ammo_12g_00buckshot" does no damage / wounds except when hitting the head.
Triggers blood effect on clothes and short periods of unconsciousness when shot multiple times.
Only happens when    Medics setting = "Advanced"

**Steps to reproduce:**

    Equip the "rhs_weap_M590_5RD" and load "rhsusf_5Rnd_00Buck"
    Unload your ammunition all over an AI Soldier except the head.
    Check wounds.

**Where did the issue occur?**

    "Singleplayer"

**RPT log file:**

    -

***EDIT***

the parent class of  "rhs_ammo_12g_00buckshot" ["B_12Gauge_Pellets","ShotgunBase","ShotgunCore","Default"] are not listed in https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_getTypeOfDamage.sqf

maybe it is related

**Comment by Faggot16** [comment]
Looks like a classic case of mods intercepting with eachother.

**Comment by Th3Cr0w** [comment]
silly me thought, that's what the comp.pbo is for.
Even though the ammo don't uses one of your defined ammo types I thought you had a default option which uses a general scheme, so the damagehandler wouldn't fail so obvious.
