### ISSUE TITLE
Text overlapping when holding a wheel

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#2276]
ACE3 Version: 3.x.x
3.2.2 04c14b992eafa4597907f3cee2b5ce4c992feb23

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None.*

**Description:**
*Text overlapping when holding a wheel. http://i.imgur.com/vaYvTIq.jpg*

**Steps to reproduce:**
* *Pick up a wheel. Interact with it.*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*No need.*

**Comment by jonpas** [comment]
Fixed by #2185 awaiting review.

**Comment by rebelvg** [comment]
Thanks!

**Comment by PabstMirror** [comment]
Fixed by #2283
