### ISSUE TITLE
Quick Switching

### ISSUE THREAD

**Issue by Faggot16** [acemod/ACE3#2280]
Perhaps something like "Quick Grenade Launcher Shot" for when switching between weapon modes takes too long? Perhaps the same thing for grenade throwing mode, such as + 1-4 or something like that?

This could go onto other things; where (it could be able to be) easily applied.

**Comment by Faggot16** [comment]
Oh shit, is this not in the request area?

**Comment by jokoho48** [comment]
no right #414 is the request Issue
