### ISSUE TITLE
Drag bug

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2281]
ACE3 Version: https://github.com/acemod/ACE3/commit/ca991712e8f1e48541c181ac794e7101a42071d7

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *-*

**Description:**
*Interaction option "drop" is drawed on top of Interaction with object when you are carrying/dragging it.*
http://steamcommunity.com/sharedfiles/filedetails/?id=506907789

**Steps to reproduce:**
* *Drag a chest or carry a chest.*
* *Interaction menu on chest -> drop, notice how it's not "extending" as it should*

**Where did the issue occur?**
*"Singleplayer"*

**RPT log file:**
*-*

**Comment by jonpas** [comment]
Fixed in #2185
