### ISSUE TITLE
You can stop carrying/dragging from both interaction menu and mousewheel menu

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2284]
ACE3 Version: https://github.com/acemod/ACE3/commit/3db981a2c59250e90a39964ac29be2b16626a500

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *-*

**Description:**
*Like in title, you get action to drop crates under scrollwheel menu. I don't think this piece of code is longer needed since you can stop dragging under interaction menu.*

```
// add scrollwheel action to release object
_actionID = _unit getVariable [QGVAR(ReleaseActionID), -1];

if (_actionID != -1) then {
    _unit removeAction _actionID;
};

_actionID = _unit addAction [
    format ["<t color='#FF0000'>%1</t>", localize LSTRING(Drop)],
    QUOTE([ARR_2(_this select 0, (_this select 0) getVariable [ARR_2(QUOTE(QGVAR(draggedObject)),objNull)])] call FUNC(dropObject)),
    nil,
    20,
    false,
    true,
    "",
    QUOTE(!isNull (_this getVariable [ARR_2(QUOTE(QGVAR(draggedObject)),objNull)]))
];
```

**Steps to reproduce:**
* *Start carrying something.*
* *You get two options to drop it, in both mousewheel and interaction menu*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*-*

**Comment by jonpas** [comment]
That was by design in AGM where you couldn't open interaction menu in some cases (object not directly in front of you). I believe this can now be removed since you can look at the object and use the menu normally.

**Comment by alganthe** [comment]
Indeed it became redundant since you can just press the interaction key / scroll down to release the object.

**Comment by PabstMirror** [comment]
When carrying a patient on your back there is no way to access his interaction point from first person.
When dragging a patient, I can't aim low enough to access the interaction point to release.

With track IR (or holding ALT/free look), or using different interaction menu options it is possible to overcome these problems, but with default options it is difficult/impossible.

Now I hate the `addAction` menu as much as anyone, so maybe we can come up with a cleaner solution, but the user needs a clear, easily accessible way to drop what they are carrying.

**Comment by gienkov** [comment]
Keybind?

**Comment by jonpas** [comment]
That would work, I suggest `R`. And next to that display the same icon as is used in attach?

**Comment by gienkov** [comment]
R will reload your weapon. Maybe LCTRL+R ?

**Comment by SzwedzikPL** [comment]
> but the user needs a clear, easily accessible way to drop what they are carrying.

So why vanilla action menu is so bad here? I dont like vanilla menu too but in this case it works just fine.

**Comment by jonpas** [comment]
> R will reload your weapon. Maybe LCTRL+R ?

You can reload while dragging? That sounds weird, one-handed reloads! :grin:

**Comment by rebelvg** [comment]
Maybe move that option to self-interaction. That way you will always able to drop the person you are carrying.

**Comment by gienkov** [comment]
You can even throw grenades while dragging :D.

**Comment by sargken** [comment]
I agree add it to self interaction and you could add a setting in your ACE controls that way if people want to use a keybind they can.

**Comment by commy2** [comment]
I like the scroll wheel option for this. It's faster.

I'm against adding a hotkey for something you probably do only once or twice a mission.

**Comment by Khaosmatic** [comment]
You may as well leave it in the action menu Commy is right its not that often you need to use it anyway.  The maximum amount of options on the action menu will only be like 6 at a time so its no hassle.

**Comment by MikeMatrix** [comment]
Why not just make it an optional keybind, that can be assigned yourself, if you really want a keybinding? There is no need to default a key to it. Just add in the option, since it's not gonna be a lot of work anyways.
Allows everybody to use their preferred method.

**Comment by PabstMirror** [comment]
#4034 Added optional keybind
