### ISSUE TITLE
Debug Commands

### ISSUE THREAD

**Issue by Faggot16** [acemod/ACE3#2288]
This is less of a "request" more is it a "does such a thing exist in the code?" sort of thing.

I'm just trying to look for any possible "debug commands" for something like the Interaction Menus, where it fixes it to a previous state or something for when it breaks/freezes or whatever.

**Comment by NouberNou** [comment]
I am not sure what you are trying to explain?

**Comment by kripto202** [comment]
@NouberNou I think he means he wants some keys or some / command that you can type in to fix any problems you may have such as a sudden bug where you get stuck or you can't access the interaction menu. It's the same concept as the head debug.

**Comment by Faggot16** [comment]
^
