### ISSUE TITLE
Question regarding optional pbo's like ace_server.pbo

### ISSUE THREAD

**Issue by Knight1981** [acemod/ACE3#2291]
Hey guys,

I have a question regarding the "optional" pbo's. Do I need to copy them into the addons folder to make them active? Or will they also be loaded when they are stored in the optionals folder?

Is there any description what they exactly do? E.g. "ace_server.pbo". Is this file necessary when we play on dedicated servers?

Thank you :)

**Comment by jonpas** [comment]
> Do I need to copy them into the addons folder to make them active?

Correct, only do so on the server for `ace_server.pbo`, it is not advisable to have it client-side as well.

Check http://ace3mod.com/wiki/framework/settings.html and you'll see what it does.

**Comment by Knight1981** [comment]
Okay thank you. :)
