### ISSUE TITLE
feature request: more accurate and changed stamina system / movement speeds

### ISSUE THREAD

**Issue by kOepi123** [acemod/ACE3#2292]
hey guys,

first of all, sorry if I posted my request in the wrong section, please adjust it, if necessary.
at second: great work with the ACE mod, again, now in arma 3 !

---

currently observed: the player is moving too slow with fewer weight. e.g. running naked, no equipment on flat terrain about 35 seconds for a distance of 200 meters = average speed of 20,57 km/h, that is about 6 km/h less.

expected: as I tested the distance of 500 meters is on average speed ok, weight and speed levels above and below that should be slower and faster.

---

I spent some time calculating and researching for this subject, so this is what I am suggesting:
1. individual movement speeds, depending on weight, for walking, jogging and sprinting
2. constant movement speeds in casual jog and slow walk at 9 km/h and 5 km/h

---

Ideally you guys would implement the function that I came up with in my calculation table, dont know how difficult that would be, but I guess my outtakes in the table would be enough too.

The overall result of changing this to more realistic values would be seen at close distance and while maneuvering, aswell as while one is rushing, he cant go on forever, but when he is fine, his speed is a lot faster than from now.

for any tests, questions or research, go ahead and shoot it.

greetz

kOepi

attached .xls file:

![endurance 1 2](https://cloud.githubusercontent.com/assets/11195228/9527674/c49279a6-4cf0-11e5-9219-aec51fd9467d.png)

attached .jpeg file:

![endurance1 2](https://cloud.githubusercontent.com/assets/11195228/9527685/cff2a564-4cf0-11e5-9466-f6ad30868d88.jpg)

**Comment by kOepi123** [comment]
calculation table:
https://fileshack.net/4xz07wgwzmom

**Comment by kOepi123** [comment]
Do not use the calculation table, currently in review !

**Comment by mickeymen** [comment]
Totally agree with autor. The weight of the portable equipment should affect the movement speed

**Comment by Glowbal** [comment]
We have since introduced advanced stamina. Closing this.
