### ISSUE TITLE
ace_compat_bwa3.pbo crashes Arma when using NSV600

### ISSUE THREAD

**Issue by Knight1981** [acemod/ACE3#2293]
ACE3 Version: 3.2.1

**Mods:**
* @cba_a3
* @ace3
* @bwa3

**Placed ACE3 Modules:**
irrelevant

**Description:**
We are using @ace with @bwa3. When we add the optional ace_compat_bwa3.pbo to the addons folder we are not able to use the NSV600 with the ZO4x30. The game crashes when trying to look through the scope.
Without the ace_compat_bwa3.pbo it works fine.

**Steps to reproduce:**
1. Copy ace_compat_bwa3.pbo and ace_compat_bwa3.pbo.ace_3.2.1.0-1ba4de75.bisign into the @ace/addons folder
2. join on server
3. take G36 with ZO4x30 and NSV600
4. try to attach NSV600 to ZO4x30 with STRG+N
You should not be able to look through the scope and arma crashes. If you try it without the optional pbo it works fine.

**Where did the issue occur?**
Multiplayer, dedicated server

**RPT log file:**
n.a

**Comment by nic547** [comment]
Try the compat pbo inside @bwa3\compatibility. No crash for me.

**Comment by Knight1981** [comment]
I put all compat files in the addons folder but error still exists.

**Comment by jokoho48** [comment]
@commy2 i think that is more your issue

**Comment by jokoho48** [comment]
#1930

**Comment by commy2** [comment]
ace_compat_bwa3.pbo is outdated. Use the one provided with the BWMod.

I'll remove this one from the repo.

**Comment by commy2** [comment]
ref: https://git.koffeinflummi.de/bwmod-team/bwa3-public/issues/12

**Comment by Knight1981** [comment]
I have a second problem. I can't attach a chemlight or IR Strobo to myself (on my uniform). 

I can throw the chemlight (but not the IR Strobo) and attach chemlights and IR Strobo to vehicles. Does anyone else have this problem? It worked in an earlier version. Hmm.... :(

**Comment by commy2** [comment]
Doubt that has anything to do with this issue. Please make a seperate one.

**Comment by Knight1981** [comment]
okay sure, thank you for your help :) I have deleted the ace_compat_bwa3.pbo
