### ISSUE TITLE
Not able to attach Chemlight / IR Strobo to myself

### ISSUE THREAD

**Issue by Knight1981** [acemod/ACE3#2294]
ACE3 Version: 3.2.1

**Mods:**
* @cba_a3
* @ace3
* @bwa3

**Placed ACE3 Modules:**
irrelevant

**Description:**
Can't attach chemlight or IR Strobo to myself (on my uniform). Furthermore I can't select (throw) the IR strobo but the chemlight I can select and throw.
I'm able to attach chemlights or strobo to vehicles.

**Steps to reproduce:**
1. Take chemlight and IR Strobo
2. Try to attach via self interaction menu / Ausrüstung
3. Item chemlight or ir strobo does not appear (menu for attaching is not there).

**Where did the issue occur?**
Multiplayer, dedicated server, Singleplayer

**RPT log file:**
n.a

**Comment by jokoho48** [comment]
````To do this try to reproduce the issue with using only @cba_a3 and @ACE3 on a newly created mission.
```

**Comment by jonpas** [comment]
Fixed in #2236 , will be in next release.

**Comment by commy2** [comment]
Is the IR-Strobe even meant to be throwable?

**Comment by jonpas** [comment]
> Is the IR-Strobe even meant to be throwable?

Nope, it's an ordinary item, not a grenade-type.

**Comment by Knight1981** [comment]
wow, thank you for the very quick answer. Okay, IR Strobos are not throwable, that was new for me. I thought this is like a grenade.

So attaching chemlight to myself isn't working with 3.2.1 because it's a bug? Thanks for the information. I eagerly await the new version. :)

Thanks for the great support guys!

**Comment by jonpas** [comment]
> wow, thank you for the very quick answer. Okay, IR Strobos are not throwable, that was new for me. I thought this is like a grenade.

IR Grenades are the ones that are throwable, Strobes are not.

> So attaching chemlight to myself isn't working with 3.2.1 because it's a bug? Thanks for the information. I eagerly await the new version. :)

Correct, so do we. :grinning:
