### ISSUE TITLE
Night vision goggles fail to equip (Using "inventory" before a mission)

### ISSUE THREAD

**Issue by Faggot16** [acemod/ACE3#2295]
I attempted to put on NVGs BEFORE going into a mission with the inventory thing in the "team" tab (as stated above) and the item simply dissapeared, nowhere to be seen.

I attempted this with other missions/scenarios/levels/whatever and the exact same thing happened. I also attempted it with other items as well, the same thing happened. (I attempted to do this without mods on, and it worked fine.) P.S: This also only happened after they updated it to 1.50, but since this is the case, they're obviously not going to change it back. From this point on, it's simply in the hands of the people messing around with ace3 and bohemia (potentially).

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by NouberNou** [comment]
Please post in the correct format with an RPT so we can investigate this further.
