### ISSUE TITLE
Camera does not lock when I open the interaction menu.

### ISSUE THREAD

**Issue by SirPoppycock** [acemod/ACE3#2302]
When I open my interaction menu it does not stop my character from looking around. Because of this I cannot detonate explosives. It is through too many menus which results in my character looking far enough away that the menu closes.

**Comment by PabstMirror** [comment]
2 settings you can use:
"Always Display cursor for interaction"
and
"Keep cursor centered"

**Comment by alganthe** [comment]
You can also use the list style.

**Comment by SirPoppycock** [comment]
That worked, thank you.
