### ISSUE TITLE
Can't carry ace3 items

### ISSUE THREAD

**Issue by Slim57050** [acemod/ACE3#2303]
ACE3 Version: 3.2.1

Mods:

@cba_a3
@ace3

Placed ACE3 Modules:
All modules.

Description:

Altis Life problem. i added item to shop i show the items in the shop but when i buy it they not go in my inventory.

Steps to reproduce:
1. Buy an Ace3 item in a altislife shop

Where did the issue occur?

Multiplayer - dedicated server

RPT log file:
/

**Comment by PabstMirror** [comment]
* Could you please include a RPT file (can be found in %localappdata%/Arma 3/ and look for the most recent file likearma3_2015-08-01_22-17-40.rpt and dump it on pastebin.com)

There isn't anything special about ace items. So I really don't see why they wouldn't be added.

* Does the server and clients both have ACE running?
* Does the client have room to carry the item?
* What command are you using to actually add the item to player?  
* Test `player addItem "ace_x"` in the debug console.

**Comment by Slim57050** [comment]
My rpt : http://pastebin.com/Pxwt5C8g


Clients and server have both ace running.

Client have room to carry the item

Commande using to add the item to player is the carry script (by tonic)  : 

http://pastebin.com/v5UAHBFy

and player addItem "ace_x" work fine

**Comment by alganthe** [comment]
This is not an ACE issue, complain to the server owners / mission creator for help.
