### ISSUE TITLE
Drawn line is created globally for all sides on mission briefing

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2306]
ACE3 Version: 3.2.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *-*

**Description:**
*When you draw lines on mission briefing then they are created for all sides. AFAIK there is no command to set side of a marker.*

**Steps to reproduce:**
* *Set mission with player on each side.*
* *Draw line on mission briefing.*
* *It will be created for all sides.*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
*-*

**Comment by PabstMirror** [comment]
Probably can be closed as this will be added natively to game
https://forums.bistudio.com/topic/190676-line-drawing/
