### ISSUE TITLE
Secondary weapon medical treatment animation

### ISSUE THREAD

**Issue by Ghost77788** [acemod/ACE3#2309]
ACE3 Version: 3.2.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
ACE Medical basic

**Description:**
When you have your secondary weapon as current weapon and then treat a injury, the progress bar for the treatment already starts going. So when you finish switching to your primary weapon the progress bar is finished and then you do the animation.

**Steps to reproduce:**
Select your secondary weapon. and then bandage a part of your body

**Where did the issue occur?**
"Multiplayer", "Singleplayer"*

**Suggestion**
Putting in a waitUntil for the currentWeapon == primaryWeapon

**Code**
Lines 164 to 167 of fnc_treatment.sqf of the medical addon

**Comment by PabstMirror** [comment]
Should be fixed by #2183 Fix
