### ISSUE TITLE
Main Menu Version dont work after 1.51

### ISSUE THREAD

**Issue by jokoho48** [acemod/ACE3#2310]
RTP Issue: `Web address 'http://ace3mod.com/version.html/' won't be open. Current restrictions do not allowed it.`

Reason: `Fixed: htmlLoad restrictions when loading URL (allowedHTMLLoadURIs in CfgCommands or server.cfg)`

**Comment by bux578** [comment]
Can't we add just add `http://ace3mod.com/version.html` to the `allowedHTMLLoadURIs` in `CfgCommands`?

**Comment by PabstMirror** [comment]
#2428
