### ISSUE TITLE
Q : How do I access Ace 3 functions from mission's scripts ?

### ISSUE THREAD

**Issue by Kushulain** [acemod/ACE3#2323]
How do I access Ace 3 functions from mission's scripts ? (e.i. init.sqf)

I couldn't find an answer/tutorial on the net about it.
And it seems the wiki lacks this information too.
Is this even possible ?

I tried things like : 
[_curPlayer, "COPS", false] call ACE_captives_fnc_setCaptivityStatus);
[_curPlayer, "COPS", false] call fnc_setCaptivityStatus;
[_curPlayer, "COPS", false] call FUNC(fnc_setCaptivityStatus);

None of these works. Do I lack an ace3 module ?
A list of ace's functions on the wiki would be welcome too.

**Comment by jokoho48** [comment]
take a look to the coding Guildline there are the Macros declared http://ace3mod.com/wiki/development/coding-guidelines.html#4-1-module-pbo-specific-macro-usage

**Comment by PabstMirror** [comment]
[player, "cops", true] call ace_common_fnc_setCaptivityStatus

**Comment by Kushulain** [comment]
It works with :
[player, "cops", true] call ace_common_fnc_setCaptivityStatus

Thank you.
I suppose I don't need to use the macros.
