### ISSUE TITLE
[Bug Fix] Incomplete files.

### ISSUE THREAD

**Issue by vallinel** [acemod/ACE3#2325]

**Comment by bux578** [comment]
?

**Comment by vallinel** [comment]
sorry I accidentally pressed enter... -_- w8 I'm updating it

**Comment by vallinel** [comment]
ACE3 v3.2.1

Mods: 
@ace
@cba_A3

Description:
Producing save corrupt and few errors like config.bin errors, missing addons, etc.
because of incomplete files in the download link in https://github.com/acemod/ACE3/releases/tag/v3.2.1


Steps to reproduce errors:
installing directly the files in the download link.

Issue occur:
SP

Fix:
download the ACE3 main files and merge the two files. It is important to merge the two files. Renaming the main files to @ace and installing it directly to the mods folder will not fix it, instead it will be tagged as corrupt by the ARMA3 launcher.

**Comment by bux578** [comment]
Did you follow the [Installation Guide](http://ace3mod.com/wiki/user/installation-guide.html)?
They work perfectly fine for me.

**Comment by vallinel** [comment]
yes, I did the installation guide. 

currently this procedure fixed my errors whenever ace3 is used. I'm just sharing this for the sake of those who encounter errors like mine....

**Comment by jokoho48** [comment]
@vallinel could you please add a RTP file

**Comment by vallinel** [comment]
@jokoho48 here are the requested rpt files

https://www.dropbox.com/sh/8qqfwrsjz3vpurv/AAC9SDmhW9RFy9iajZ8hcddva?dl=0

**Comment by Glowbal** [comment]
What 2 files are you talking about?

**Comment by jokoho48** [comment]
@vallinel please try to reproduce the issue that you found only with ace3 and CBA

**Comment by vallinel** [comment]
@jokoho48 I did... I have installed mulitple mods and errors came up... so what I did was I deactivated all the installed mods and one by one I activated it to reproduce the error... so what happened was only with cba and ace3 enabled the error pops up...

I also noticed back then that arma launcher displays ace mod with no lock icon. I think it says "not all files are signed".

I'll try to reproduce the error again.. I'll uninstall all my mods and only ace and cba will be installed.

**Comment by vallinel** [comment]
@Glowbal the file given in the download link 56mb plus the main ace files.

**Comment by bux578** [comment]
Please provide screenshots from your installation folder and where you've placed cba and ace3. There's probably something wrong in how you "install" mods.

**Comment by commy2** [comment]
@vallinel 
Those are multiple .rpts Which one do I have to look at?

**Comment by vallinel** [comment]
![mods installation folder](https://cloud.githubusercontent.com/assets/14054009/9606560/a7ece5b6-50f6-11e5-9efc-a53eda10b487.jpg)
 this is where the installation folder of all the currently installed mods....

**Comment by vallinel** [comment]
I don't know... I just followed jokoho48s insructions...

**Comment by jokoho48** [comment]
@vallinel delete all the RTP files start arma 3 only with ace and cba and than is there ONE RTP file and this please send us

**Comment by vallinel** [comment]
sorry for the wait...

I have to do a clean reinstall of arma 3, ace, and cba mod to reproduce the error...

here is the rpt file: https://www.dropbox.com/s/w04d3b3v752q37t/arma3_2015-09-01_22-49-55.rpt?dl=0

and here is a screenshot of arma 3 launcher:
![launcher](https://cloud.githubusercontent.com/assets/14054009/9607717/4836673a-50fd-11e5-9c6c-dcd7504b713f.jpg)

I noticed that it says, "partially signed".

**Comment by commy2** [comment]
```
22:50:14 Warning Message: Addon 'ace_BWA3_Weapons_comp' requires addon 'BWA3_Weapons'
22:50:15 Warning Message: Addon 'ace_CUP_Weapons_Ammunition_comp' requires addon 'CUP_Weapons_Ammunition'
22:50:15 Warning Message: Addon 'ace_BWA3_Weapons_comp' requires addon 'R3F_Armes'
22:50:15 Warning Message: Addon 'ace_BWA3_Weapons_comp' requires addon 'R3F_Acc'
22:50:15 Warning Message: Addon 'ace_RH_acc_comp' requires addon 'RH_acc'
22:50:15 Warning Message: Addon 'ace_RH_de_cfg_comp' requires addon 'RH_de_cfg'
22:50:15 Warning Message: Addon 'ace_RH_m4_cfg_comp' requires addon 'RH_m4_cfg'
22:50:15 Warning Message: Addon 'ace_RH_PDW_comp' requires addon 'RH_PDW'
22:50:15 Warning Message: Addon 'ace_rhs_c_weapons_comp' requires addon 'rhs_c_weapons'
22:50:15 Warning Message: Addon 'ace_rhs_c_weapons_comp' requires addon 'rhs_c_troops'
22:50:15 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'rhsusf_c_weapons'
22:50:15 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'rhsusf_c_troops'
22:50:15 Warning Message: Addon 'ace_RKSL_PMII_comp' requires addon 'RKSL_PMII'
22:50:15 Warning Message: Addon 'ace_sma3_iansky_comp' requires addon 'iansky_opt'
```

You started with all compatiblity PBOs even though you didn't select the corresponding addons. You can't do that.

**Comment by vallinel** [comment]
ah ok...

I have reinstalled ace3 without copying a single file from the optional folder and no errors.. even the saves works...

I guess it's a misfire... my mistake. Sorry about that.

**Comment by jonpas** [comment]
http://ace3mod.com/wiki/user/installation-guide.html#4-2-which-optionals-should-i-use
> Only use the optional components that correspond with your mod-pack.

:)
