### ISSUE TITLE
stretcher in ace 3 ? 

### ISSUE THREAD

**Issue by ussmarines** [acemod/ACE3#2330]
I have  a question : Are you going to make a stretcher in arma 3 for ACE3 ?

I would love to be able to evacuate soldiers from the battlefield with ACE2 as in arma 2 on a stretcher and put it to the stretcher and the soldier in a vehicle such as the Black Hawk Mev mod RHS.

ussmarines

**Comment by jokoho48** [comment]
please read this: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
and than use #414 for Feature Requests
