### ISSUE TITLE
Hellcat: Miniguns cause deafness even with earplugs in

### ISSUE THREAD

**Issue by Rickyfox** [acemod/ACE3#2335]
Not sure if it's intended, but as described in the title the miniguns trigger the normal combat deafness mechanics - and pretty fast at that.

**Comment by alganthe** [comment]
it is, earplugs don`t provide full protection so high caliber, fast firing weapon systems deafen you pretty fast

**Comment by SzwedzikPL** [comment]
shouldn't be that fast in pilot helmet.

**Comment by Glowbal** [comment]
Deafness or ear ringing? Btw: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

Also could you define fast?

**Comment by headedhorseman101** [comment]
>shouldn't be that fast in pilot helmet.

:+1: 

Imo, this is really more a question of gameplay than of realism. I have never fired a minigun (much less from a helicopter), but if you go deaf after 2 seconds of firing, then it isn't very fun for the light attack heli pilots if they can't hear anything else.

**Comment by bux578** [comment]
Still an issue
