### ISSUE TITLE
Spawn Create Display crash when called from Interaction Menu

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#2342]
**Example:**
CfgVehicles (look at `statement`):
```
class CfgVehicles {
    class Air;
    class Helicopter: Air {
        class ACE_SelfActions {
            class GVAR(RatelMarker) {
                displayName = CSTRING(DisplayName);
                condition = QUOTE(_this call FUNC(canUseMarkerMenu));
                statement = QUOTE([] spawn FUNC(createMarkerMenu)); // createDisplay requires spawn for not-yet-known reasons
                showDisabled = 0;
                priority = 0;
                icon = QUOTE(PATHTOF(UI\ratelMarker_ca.paa));
            };
        };
    };
};
```
FUNC(createMarkerMenu):
```
(findDisplay 46) createDisplay QGVAR(RatelMarkerMenu);
```

Doing the following as `statement` causes a crash:
```
statement = QUOTE(call FUNC(createMarkerMenu)); 
```

When the same call is used from CBA Keybinds it works perfectly. It is to note that BI wiki says `spawn` should not be used from debug console, so I guess that's happening in the same execution environment?

**Comment by PabstMirror** [comment]
Take a look at what I did in #1977

mainly just using `EFUNC(common,execNextFrame)`

My guess is that the ACE menu display is still up when your code tries doing `(findDisplay 46) createDisplay QGVAR(RatelMarkerMenu);`

**Comment by jonpas** [comment]
That worked, thanks @PabstMirror !
