### ISSUE TITLE
ACE3 - Telescopic Ladder: Going big

### ISSUE THREAD

**Issue by Faggot16** [acemod/ACE3#2345]
I don't think this will be done for awhile if assigned or anything, but perhaps a longer, bigger telescopic ladder either requiring 2 people (sort of like static weapons if each person where to carry it by backpack) or perhaps on or requiring a vehicle or something nearby?

**Comment by Faggot16** [comment]
(this was referenced on #414 (feature requests page)

**Comment by PabstMirror** [comment]
Tagging feature requests in #414
