### ISSUE TITLE
disable noVoice

### ISSUE THREAD

**Issue by Iceman1991** [acemod/ACE3#2346]
Hi all,

is it possible to disable the "NoRadio" Funktion? I need de AI and my own Player to use the radio function. But it seems like this function ist in the basic code of ace. Is it possible to disable the noradio function?

Thanks alot!

**Comment by commy2** [comment]
Yes, you remove the ace_noradio.pbo.

**Comment by Iceman1991** [comment]
thank you for your advice. but this just works for the player himself. the AI is still not saying anything.

**Comment by commy2** [comment]
AIs are not affected by NoRadio. Something else must be wrong.

**Comment by Iceman1991** [comment]
yeah it happens as soon as i start the game with ace activated - no modules set. i think it is scripted in the main / common pbo - but i cant find it

**Comment by commy2** [comment]
I can't reproduce your issue. I just shot at a friendly AI and he radio'd me "fucking cease fire".
Could you try to reproduce it with only CBA and ACE enabled? If the issue persists, could you please upload a RPT file?

**Comment by Iceman1991** [comment]
i got the answer. it was something in the mission itself. i copied the whole mission in a new editor file and saved it aggain. now its working - thanks alot!

**Comment by JCae2798** [comment]
Is there a way to add a setting to ACE options menu to enable/disable this?

**Comment by bux** [comment]
No.

**Comment by Krokx** [comment]
The problem is the no_radio.pbo gets redownloaded every time, when ace is getting updated, although I moved the no_radio.pbo out of the addon folder. I use the steam arma 3 launcher. Is it possible somehow to enable the radio "forever"? It's annoying to exit the game every time I notice the no_radio.pbo is enabled again....

**Comment by commy2** [comment]
Don't use Steam.

**Comment by JCae2798** [comment]
Not the end of the world to copy the folder from STEAM so the above issue
doesn't happen, but i was hoping an option within the menus can be toggled
to enable/disable this.  No worries either way, and thanks for all you do!

**Comment by jonpas** [comment]
It's not possible to have a setting for config changes in-game, as has been said million times before.
