### ISSUE TITLE
[Q] ACE 3 Medical disabling leg breaking and/or fixing legs with script

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#2347]
ACE 3.2.1
Advanced medical

Ok so people have been getting broken legs (can't run only walk) for a while now and it's very annoying as we are forced to use PAK's to fix them as there seems to be no other soultion.

This is annoying as it takes a lot of time and PAK's.

I can't find the code that adds forceWalk and can't find a way to fix the legs with a script.

I want to add an ace action to fix the legs in ~10 seconds and without wasting a pak.

**Comment by xJenny99x** [comment]
[player] call ace_common_fnc_getForceWalkStatus gives me an emtpy array:

[]

**Comment by commy2** [comment]
ACE_player setHitPointDamage ["HitLegs", 0];

**Comment by Glowbal** [comment]
Should be answered by @commy2 s comment.

**Comment by SilentSpike** [comment]
Should also note this is a bug and will be fixed.
