### ISSUE TITLE
unable to release unit from Make unit surrender module

### ISSUE THREAD

**Issue by SharonX4** [acemod/ACE3#2348]
i sync but i cant to release him

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by SharonX4** [comment]
ACE3 Version: 3.x.x
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
Make Unit Surrender 

**Description:**
i sync to the unit in editor

**Steps to reproduce:**
place unit & module  sync them together preview it 

do interaction to the unit you wont see the ability to release \ carry   

**Where did the issue occur?**
*A possible answer might be "Multiplayer", "Singleplayer"*

**RPT log file:**
*Add a link (pastebin.com) to the client or server RPT file.*

**Comment by PabstMirror** [comment]
I think you're talking about an AI unit that is surrendered.

You can't carry a surrendered unit. 
What you probably want to do is add a `ACE_CableTie` and apply those on the AI.  
That will allow you to carry/release him.

**Comment by SharonX4** [comment]
didn't understand

**Comment by PabstMirror** [comment]
Escort//Carry only works on a handcuffed unit, it does not work on a surrendered unit.
So apply handcuffs/cableTies to the surrendered unit and you will be able to carry him.

The item name is `ACE_CableTie` and you apply it to the unit's hands.

**Comment by SharonX4** [comment]
handcuffed module?

**Comment by SharonX4** [comment]
but  i want to make from editor

**Comment by MikeMatrix** [comment]
You need to get the item `ACE_CableTie` to be able to tie the surrendered unit up, before you can escort or release somebody.

**Comment by PabstMirror** [comment]
There will be an module for this in 3.4
