### ISSUE TITLE
Alca AG Vikhr missiles do not seem to lock

### ISSUE THREAD

**Issue by distractor2004** [acemod/ACE3#2349]
ACE3 Version: 3.2.1 Stable
Arma 3 1.50 Stable

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
* The Alca's AG/Scalpel/Vikhr missiles cannot lock onto an enemy ground vehicle unless the addon pbo's
javelin, missile-guidance, and self-designate are removed.

**Steps to reproduce:**
* Using the full ACE3 mod, place an AAF Alca(CAS) and an enemy ground vehicle.

* Switch to the AG Scalpel/Vikhr missile and try to lock onto the target.

* Repeat steps with the javelin, missile-guidance, and self-designate pbo's removed and you should now be able to lock onto the target.

**Where did the issue occur?**
* Mission Editor/Singleplayer

**RPT log file:**
* N/A

**Comment by alganthe** [comment]
[Follow this for](http://ace3mod.com/wiki/user/how-to-report-an-issue.html) it's here for a reason, we need it.

**Comment by distractor2004** [comment]
Thanks for the link and I have formatted the feedback along those guidelines.

**Comment by distractor2004** [comment]
What further information would be helpful for me to provide?
