### ISSUE TITLE
Altitude setting for ACE 3 respawn ?

### ISSUE THREAD

**Issue by dsjasonh** [acemod/ACE3#2362]
I'm using ghost's enemy assault map as the daily training map for my team. But now we encountered a dilemma. Here's the thing: in our lately mod, we are planning to let all the players respawn on the aircraft carrier. Previously, we can position the respawn flag on the deck of the aircraft carrier( in Ghost's map, there are three respawn spot, one is near the specified flag, which can be placed any where even in the air, rest two spot is helicopter). But now we are loading the ace 3 mod. As we all know, the respawn mechanism of ace will replace the default respawn setting of the map. But there is no altitude setting for respawn of ace 3

The idea of Respawning on the deck of the aircraft carrier cannot be changed. But we do wanna use ace 3 mod. 

Is there any solution for our dilemma ?

Thanks
Jason He

**Comment by commy2** [comment]
>As we all know, the respawn mechanism of ace will replace the default respawn setting of the map

Not really. Unless you placed either a ACE rallypoint or the ACE respawn module, nothing changes at all.

**Comment by commy2** [comment]
Can't reproduce your issue. I made two simple missions on the AiA utes aircraft carrier. One is done with a respawn_west marker and the other one with the ACE rallypoints.
When I respawn, I end up on top of the carrier. With the ACE mission I can even use the rallypoints without falling through the carrier.

http://www.mediafire.com/download/diyfz7zo89i3ic1/_respawn+utes.utes.zip

**Comment by dsjasonh** [comment]
@Commy2 thanks for ur quick response. I'll make sure our mission maker get ur message and see wether this will help

**Comment by gienkov** [comment]
LHD is not a carrier, are we talking about Nimitz addon?

**Comment by SilentSpike** [comment]
Arma respawn has never had an altitude setting, mission makers have always had to set respawned players to the right height themselves.

Could be done with a simple respawn template or just using onPlayerRespawn.sqf

**Comment by dsjasonh** [comment]
@gienkov Actually both of them. we are using Nimitz and LHD.

**Comment by dsjasonh** [comment]
Supplement: I'm using the lastest Austrial Map v3.0  and the issue I posted above happens. I've tested, respawn on LHD is no problem in other maps just except the Austrial. Is that the Map problem? Can anyone who has Austrial map loaded test it?

**Comment by commy2** [comment]
I have no idea what the issue on the map is, but here is what you could do:

description.ext:
```

class Extended_Respawn_EventHandlers {
    class CAManBase {
        class MyTag_Mission {
            respawn = "(_this select 0) setPosASL (getPosASL (_this select 0) vectorAdd [0,0,<EXPERIMENTAL VALUE>])";
        };
    };
};
```
where <EXPERIMENTAL VALUE> is a positive number you have to get through testing.

**Comment by commy2** [comment]
My edcated guess about the respawn placing you in the water on that map is, that the aircraft carrier on that map is "floating" opposed to the one on Utes. The game probably is to dumb to find the highest pathway lod when respawning and therefore places you on the bottom of the ocean.

**Comment by dsjasonh** [comment]
Thanks to all of you who commented on my issue .And greatest thanks to @commy2.
My apologize for posting a non-ace 3 mod in here.
I finally find the solution by this video :https://www.youtube.com/watch?v=e47f4EYNVbk
Anyway, thanks for all and best wishes to ACE 3 team. looking forward your 3.3.0 update !

**Comment by commy2** [comment]
Hah. Placing that helipad on the right altitude is a pretty smart work-around. :+1: 
Solution found, close
