### ISSUE TITLE
About optics

### ISSUE THREAD

**Issue by Yoshinosido** [acemod/ACE3#2369]
I can't use the pip optics.

**Comment by commy2** [comment]
Well I can.

Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by Yoshinosido** [comment]
ACE3 Version: 3.2.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None

**Description:**
I can't use the pip optics. ex:LRPS(PIP) or LRPS(2D)

**Steps to reproduce:**
None

**Where did the issue occur?**
Multiplayer Singleplayer

I already fix it.
I copy the optionals file to the addons file.
But before the version doesn't need to make this step.
