### ISSUE TITLE
FCS support for Planes

### ISSUE THREAD

**Issue by SzwedzikPL** [acemod/ACE3#2378]
For https://github.com/acemod/ACE3/pull/1976

**Comment by PabstMirror** [comment]
Should be part of base game soon
1.59 dev - https://youtu.be/Pzn8oPKoc9M?t=20

**Comment by SzwedzikPL** [comment]
I thought about something similar what you have in commanche after turning laser on. Shells should hit where you aim.

**Comment by SzwedzikPL** [comment]
Done on Arma 3 DEV `Added: A Constantly Computed Impact Point (CCIP) for guns, rockets and bombs`
