### ISSUE TITLE
Usages of Mirrors

### ISSUE THREAD

**Issue by Faggot16** [acemod/ACE3#2380]
Perhaps there could be things like mirrors for peaking around corners and flashing into the sky for more pinpoint accuracy of where somebody is for locating a survivor for helicopters/blinding people potentially? This just seems too perfect for this game.

**Comment by MikeMatrix** [comment]
Thanks for the effort, but make sure you read http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html and check out #414!

**Comment by Faggot16** [comment]
This is referenced on #414.

**Comment by MikeMatrix** [comment]
Yes, because we just referenced it by typing #414.
