### ISSUE TITLE
Turn off magic zoom

### ISSUE THREAD

**Issue by Przemro** [acemod/ACE3#2381]
VTN mod have this feature, it turn off magic hold RMB* zoom in players eyes and when they aim . I don t see it realistic in any way, since human can t "zoom", you can try to focus on someting but it doesn`t zoom. So is there way to make it in module so you can force on players to turn it off.

*right mouse button

**Comment by jokoho48** [comment]
please read this:http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
and use #414
