### ISSUE TITLE
Singleplayer Compatability

### ISSUE THREAD

**Issue by Faggot16** [acemod/ACE3#2383]
This is more a feature request then an issue, but still has context towards both, really.
Attempting to countinue a mission from a save causes ace3 to FULLY BREAK DOWN. NOTHING WORKS.
Not the interaction menu, not EVEN the vehicles (ace3 reconfigures all vehicles to have it's own suspension and everything), etc.

Perhaps you could decide to make this work even AFTER campaign saves? (So far it's only been campaign saves, though I have yet to test scenario saves. I'm guessing it the exact same thing.)
Making ace3 singleplayer compatible would/will be a great thing if you choose to do so.

kthx

**Comment by Glowbal** [comment]
#1098

**Comment by KoffeinFlummi** [comment]
You have been sent the link to the issue tracker usage instructions repeatedly now. I'd suggest you read them and stop posting feature requests as new issues, before we take care of that second part for you.
