### ISSUE TITLE
Spectator external camera limited by difficulty setting

### ISSUE THREAD

**Issue by SilentSpike** [acemod/ACE3#2388]
It seems as though forcing first person via the server difficulty settings disables the spectator 3rd person camera.

My proposed fix for this is to make 3rd person an orbital camera (I was going to add this as an entirely separate camera mode, but this will work just fine) that doesn't rely on using switchCamera on a unit.

This seems like something of a big deal so I'll see how quickly I can do it and might be able to slip it in as a hotfix for 3.3.0.

**Comment by SilentSpike** [comment]
Hotfixed

**Comment by bux578** [comment]
edfb6356313303b60429a8ba47ff06d90e70b53a
