### ISSUE TITLE
Leg Damage, Stuck Walking

### ISSUE THREAD

**Issue by CodeBugd** [acemod/ACE3#2389]
Latest version of ACE 3 3.2.1.0, having issues with the player are not able to run when damaged in the leg, even when a medic heals them completely. Advanced medical is turned on.

**Comment by Shadowmarine578** [comment]
you must go to a MED hospital to fully heal. it can be placed on a object like a building or a vehicle check the modules for ACE_moduleAssignMedicVehicle and ACE_moduleAssignMedicBuilding

**Comment by Meiestrix** [comment]
You can only fix this with a Persoanl Aid Kit (PAK).
But it would be nice if there would be a message like: ( Your leg is broken )
or something similar.

**Comment by SilentSpike** [comment]
Known bug fixed in next version. Please follow issue posting guidelines in future thanks :+1:

**Comment by SilentSpike** [comment]
Actually, I don't want to close this too hastily since you weren't very specific.

I'm assuming you're talking about bruising forcing walking? Or is this something different?

**Comment by SilentSpike** [comment]
To clarify the current behaviour of advanced medical:

1. There is a setting called ace_medical_healHitPointAfterAdvBandage which does what it sounds like, the actual display name is kind of misleading, something like "remove blood stains after bandaging" (we'll likely change this to be more appropriate for the next version)
2. This setting will heal the legs (or any hitpoint for that matter) when they're fully bandaged
3. However, there's also a bug in the current version where bruises will prevent this behaviour

**Comment by Faggot16** [comment]
This sounds intentional, get shot in the leg - can't walk as fast.

**Comment by SilentSpike** [comment]
Any update on this @CodeBugd ?

**Comment by Dobakjang** [comment]
This setting will heal the legs (or any hitpoint for that matter) when they're fully bandaged

NOPE Absolutely still not healing the legs,

**Comment by PabstMirror** [comment]
This should be fixed by #2646

**Comment by Glowbal** [comment]
Should be fixed by #2646 yes. Closing this. If it occures with 3.4 again, please create a new issue.
