### ISSUE TITLE
Sitting Modual- getting Blasted to the sky when elvation is above 0 on object

### ISSUE THREAD

**Issue by Shadowmarine578** [acemod/ACE3#2391]
soooo found a bug with the siting module if a chair has a elevation any higher than 0 when you go to sit in the chair it will throw you up into the air and you will watch helplessly  as you fall to the ground.

I am placing chairs at elevation 17 on a LHD to build a briefing room. the chair is a simple camping chair Land_CampingChair_V1_F it only happens when the chair is set higher than 0 so maybe its something with the getpos on the script used

**Comment by Glowbal** [comment]
Thank you for your report. We will look into it. Mainwhile could you please edit your ticket to follow the guidelines? http://ace3mod.com/wiki/user/how-to-report-an-issue.html This will help us adress the issue. Thanks!

**Comment by commy2** [comment]
This most likely has nothing to do with the elevation, but with the first pathway lod below the chair being a PhysX GEO-Lod. I think I wrote a long explaination about this a while ago, but it basically is an engine bug / limitation / oversight with the PhysX implementation. The same issues occur with dragging (or would occur, I fixed them for the most part).
Basically the game thinks the PhysX chair collided with the PhysX building. AttachTo, which is used for sitting I belive is one of the triggers that cause a PhysX collision check / update / whatever.
The is a long, convoluted work around integrated in dragging using `allowDamage false` (which somehow influences PhysX, no idea it's somehow linked to collision damage), but I advice you to simply attach the chairs to the building.
tl-dr
PhysX sucks, nothing we can do, use `attachTo`

**Comment by jonpas** [comment]
> AttachTo, which is used for sitting I belive

Nope, sitting uses simple setPos (not ASL, because it's relative to the model/chair) and setDir with animation change.

**Comment by jonpas** [comment]
I've tested this with vanilla buildings, both those already on the map and manually placed, both work fine, this is a PhysX issue, and I don't want to add `allowDamage false` if it involves collision damage, as that would literally make people invulnerable on bigger chairs.

**Comment by Shadowmarine578** [comment]
**Mods:**
* `@CBA_A3`
* `@ace`
* `@allinarmaterainpack`
* `@ATLAS_LHD_Plus`

**Modules:**
* *1.12 Make Unit Surrender:*
* *1.13 Map:*
* *1.14 MicroDAGR Map Fill:*
* *1.17 Rallypoint System:*
* *1.17 Respawn System:*
* *1.19 Sitting:*
* *2.1 Medical Settings:*


**Description:**
* When placing chairs at elevation 17 on a LHD. the chair is a simple camping chair Land_CampingChair_V1_F it only happens when the chair is set higher than 0*

**Steps to reproduce:**
* *Place the ATLAS LHD on map, place a Camping Chair on the LHD set its elevation to 17 "it will be on the flight deck"
then place your Sitting Modual, the last thing you will need to do is place your player on the map at elevation 17 so that
he will be on the flight deck as well then preview mission try to sit in chair, you will be teleported up into the sky
where you will then fall to your death.*

**Where did the issue occur?**
* "Editor"/"Singleplayer"*

**RPT log file:**
* Add a link (pastebin.com) to the client or server RPT file.*

**Comment by Shadowmarine578** [comment]
sorry about that Glowbal first time reporting bug, although after reading  jonpas comment i am starting to think this is just a problem with the LHD, https://forums.bistudio.com/topic/176491-atlas-mod-lhd-plus/page-8, and with this i think the creator is looking for help with bug fix's and such. 

i was really hoping you guys could put your interaction menus on the LHD like for the Lifts and well deck Door and kinda clean it up hopefully the maker j0nes will contact you guys or vice verse both your ace 3 mod and J0nes's LHD are simply stunning and required mods with my arma unit it would be great if you guys could team up to make the LHD more viable.

**Comment by jonpas** [comment]
It's a problem with how the LHD is built, it's not compatible with PhysX really due to it being about 7 (IIRC) big objects put together, it has all sorts of different issues.

As of adding ACE3 interaction to it, that's totally up to the mod maker to add it and it's easiest that way, we're of course happy to help and are writing a framework documentation about it.

**Comment by Shadowmarine578** [comment]
cool thanks so much for the help guys ill just try to work around this, my guys can just take a knee or from a school circle lol,  

maybe i can beg my model makers in my unit to try to combine all 7 of those objects into one Obscenely Big object might fix the bouncing issue that jets have. but that might be asking a bit much of them as they have only made guns for us so far.

but yea if you all make a way to add the interaction menus to it that would be great, i am sure it could be something simple like referencing the addAction's used to operate the lifts and doors of the LHD to show up in the interaction menu when your close enough to it.

**Comment by jonpas** [comment]
> maybe i can beg my model makers in my unit to try to combine all 7 of those objects into one Obscenely Big object might fix the bouncing issue that jets have.

That doesn't work, Arma has a limit of a pathway LOD, that's the entire reason why it's separated into multiple pieces.

**Comment by Shadowmarine578** [comment]
then maybe make a 8th peace going over the flight deck? or is that a no go as well?

**Comment by jonpas** [comment]
The issue is with the length, so that's a definitive no-go. :)

**Comment by commy2** [comment]
>try to combine all 7 of those objects into one Obscenely Big object might fix the bouncing issue that jets have.
It wouldn't. Only BI can fix PhysX.

**Comment by Shadowmarine578** [comment]
going back to the adding ACE 3 interactions on the Atlas LHD got a link here and trying to get help with scripting here http://www.armaholic.com/forums.php?m=posts&q=32674
