### ISSUE TITLE
AI: grenades overpowered in close combat

### ISSUE THREAD

**Issue by Meiestrix** [acemod/ACE3#2396]
ACE3 Version: 3.2.1

**Mods:**
* `@CBA_A3`
* `@ace`
* `@TFAR`

**Placed ACE3 Modules:**
https://www.dropbox.com/s/bckb3c3fxiss3ub/ACE%203%20modules.txt?dl=0

**Description:**
In my and my frieds opinion grenades from enemy AI are overpowered when you fight in close combat.
We use the advanced medic system and it often happens that a whole team dies because of an enemy grenade.

Maybe there is a way to reduce the explosion and fragment / splinter damage.

**Steps to reproduce:**
Fight against AI in close combat let AI throw a grenade near you position

**Where did the issue occur?**
* Multiplayer dedicated server*

**Comment by jonpas** [comment]
I see nothing wrong with that, grenades are dangerous things after-all. Can you compare with real life grenade and see if there is a noticeable difference maybe?

**Comment by alganthe** [comment]
No shit ? Are you going to tell us that bullets are also too deadly and should behave like rubber next time ?

**Comment by Meiestrix** [comment]
Yes sure grenades are dangerous but in close combat the AI would also frag themselve.
In close range AI wont die and Player in double the distance to the grenade die because of heavy bleeding from advanced medic.

**Comment by SilentSpike** [comment]
@alganthe please don't be rude

**Comment by alganthe** [comment]
Sorry for that, however the grenades damage (RNG and RGO) are definitely fine.

**Comment by DeKugelschieber** [comment]
I agree, we experienced missions where we lost due to single granades, knocking out about 8 players at once. When this happens depends on the situation. The AI throws to much granades in close combat, this should kill them as well as us.
On distance, I think the granade damage is fair, you simply notice a granade by light damage from splints. But this does not kill you.

Does ACE modify how many granades the AI throws?

**Comment by alganthe** [comment]
No BI updated the AI behavior to make them use grenades more often in 1.48 and 1.50
If you die too many times due to grenades either reduce the skill of the ai or make your teammates aware that the enemies can also use grenades as well.

**Comment by gienkov** [comment]
And don't clusterfuck.

**Comment by Raspu86** [comment]
Adapt and overcome!

**Comment by bux578** [comment]
Yesterday evening we had a CQC session against AI and not a single grenade was thrown at us. Only UGL's have been fired at us.

**Comment by BaerMitUmlaut** [comment]
I think grenades are perfect as they are.
> knocking out about 8 players at once

An 8 man blob is impressive but in the end you were probably too close to each other.

**Comment by DeKugelschieber** [comment]
We were within a 50m radius.

**Comment by Meiestrix** [comment]
I noticed that the fragments from the explosion in some cases make multiple big wounds.
Than you are instant unconscious and die because of heavy bleeding.

Maybe it is possible to add an option to change the range / power of the fragments.

**Comment by SilentSpike** [comment]
I'd recommend testing this out again after 3.3.0 releases, at this point there have been a lot of changes to the medical code and injuries caused might behave a little differently.

**Comment by xJenny99x** [comment]
If you are using VCOM AI. Then be aware that there's a script in there that makes the ai directly face his enemy and throw grenades with pinpoint accuracy.

I had that problem, but I like to think grenades are quite realistic and provide a lot of injuries to people who are not careful.

**Comment by headedhorseman101** [comment]
Most likely the simplest way to do this would be to reduce the minDistanceProb coefficient so they are less likely to throw a grenade with someone right next to them
