### ISSUE TITLE
server.pbo, when installed causes AI units to be spawned without uniforms

### ISSUE THREAD

**Issue by dvdbrewster** [acemod/ACE3#2402]
Issue is : The server.pbo (ace3), when installed causes AI units to be spawned without uniforms.
Occurs:  Playing cti missions that use A2 importing (crCTI proman, WASP RHS, Warlords RHS,).
Detail of problems:
               Also I had all players not able to connect when using the server .pbo installed to ARMA3
               addons, U guys said it goes  in the ACE3 addons folder(on server) so I moved it.
                This causes AIs to be spawned without uniforms. (so I moved it, )   I don't know if the 
                players can connect because I removed the server.pbo because of the AI uniform problem.
                But now players can definitely connect, and the AIS have uniforms.

I ran the mods as  above in RPT files (sorry GlowBal for the paste here). (user cfg file is in main game directory and applies those settings to all missions when server.pbo is installed).

______________

  I have a problem in issue  #1590  I ALWAYS thought it was fixed, but I have  been away, and I am the only one that can join my server.  (the "jest" guys haven't even heard of it.)

**Comment by alganthe** [comment]
Could you provide a RPT and a list of the mods your were using ?

**Comment by commy2** [comment]
Yeah. This is impossible to solve without RPT and without knowing what `@newserveraddon` actually is / does.

**Comment by dvdbrewster** [comment]
This is from last night. There were several mods, 
CBA
ace3 
AiATP
rhs (east/west)
@warlords
@mao_blood_mist
The no connect problem is there with any combination of mods, Right now the server pbo is not installed like it is 
in the rpt.  THE @newservermod was just what I named the folder for the server_ace pbo. Its not named that now.
Like I said the parameters were all adjustable, like described in Getting the Settings, Just Im the only one could conncect.

**Comment by dvdbrewster** [comment]
Heres RPT with CBA, ACE3, @server_ace,
(@server ace contains the ace server pbo)

See it does not connect to steam servers.  I located the server pbo to the games main addons folder b4, and it started working, that’s when the connectivity problem occurred.

**Comment by dvdbrewster** [comment]
This is I put the server pbo in the ACE 3 addons folder.

**Comment by dvdbrewster** [comment]
AND here’s  cba , ace3,  with the server pbo in games addons folder.  See the server doesn’t connect to steam servers

**Comment by dvdbrewster** [comment]
This is last,  CBA_a3, and ACE3,  no connection

**Comment by alganthe** [comment]
First RPT: You're using ace_server wrong it should be with the rest of the pbos in ace\addons.
Second RPT: ace_server is not in there / not loading.
Third RPT: Same as the second.

**Comment by dvdbrewster** [comment]
MAde a mistake..  had a persistent mission req. in cfg server. Its moved.  sorry.  This is cba, ace 3 and @server_ace
  My ace 3 icon in multiplayer servers on steam lobby turns red. as is the @server ace icon. If I move the @server_ace out of command line, it turns green.

**Comment by alganthe** [comment]
again the ace_server.pbo need to be placed INSIDE of the original ace folder like this:
.\@ACE3_3.2.1\addons\ace_server.pbo

**Comment by dvdbrewster** [comment]
So add the server pbo in ace addons. Right? No Folder ?

**Comment by alganthe** [comment]
no folders needed, it acts the same as a compat pbo.
don't forget to move the userconfig, and again the ace_server.pbo is SERVERSIDE **ONLY**

**Comment by dvdbrewster** [comment]
Here it is,  The game server launched the game.  Server pbo is inside the ace addons folder. User cfg is in game directory.
CBA.AiATP,ACE3,RHS East/West,@Warlords,mao_bloodmist,

**Comment by dvdbrewster** [comment]
I changed user cfg to Force All Settings = 0  till joining produces no lobby, just freezes before its loaded to that point

**Comment by dvdbrewster** [comment]
Then I removed the sever pbo and running CBA, ACE3,AiATP,RHS(e/w), @warlords,@ewk,@maoblood_mist
Same “unsupported language” ?

**Comment by dvdbrewster** [comment]
You know,  the only time this ever worked was when I put @aceserver in the games Addons(not aces)
I could set settings, play game,  Just joiners was extremely spare. Lotsa disconnects on connecting. 
I work out of town mostly, but I have 3 servers(other has no ace) and ace server had mayB 6
successful joiners  since I installed ace 3   3.0 (first install)

**Comment by dvdbrewster** [comment]
So I got it loaded in ace addons folder.. It works with user cfg.  (I had removed the ace disposable.) I don’t think this solved being able to join. I have same strg errors (?) in rpt.

**Comment by alganthe** [comment]
Those string errors are minor and aren't impacting the ability to join a server.

**Comment by dvdbrewster** [comment]
I appreciate  the help

**Comment by Glowbal** [comment]
Hello @dvdbrewster, could you use http://pastebin.com/ for the rtp files instead of pasting directly into a comment? It makes it slightly easier to read. Thanks in advanced.

**Comment by dvdbrewster** [comment]
Sorry about the pastebin.   I  finally just removed the server.pbo from the ace addons.  It worked SAT for parameters, however for some missions AIs would be spawned w/o uniform, It does not do this if Using ACE w/o the server .pbo   seems missions scripted or developed from Arma 2  have troubles with keeping their clothes on. [ waspCTI RHS,,  crCTI proman, Warlords RHS, ]   BECTI doesn't seem to experience this.

**Comment by commy2** [comment]
Can you please rephrase what the actual problem is?
No offense, but the essay you wrote in #1590 is really hard to understand. The first four sentences are absolutely irrelevant. I read it multiple times and still have no idea what's going on.
Oh, and nameing an issue `"issue #1590"` is pretty confusing too.

You can format the opening post too. If you have a good issue title that actually describes what the problem is then I could edit this.

**Comment by dvdbrewster** [comment]
Issue is : The server.pbo (ace3), when installed causes AI units to be spawned without uniforms.
Occurs:  Playing cti missions that use A2 importing (crCTI proman, WASP RHS, Warlords RHS,).
Detail of problems:
               Also I had all players not able to connect when using the server .pbo installed to ARMA3
               addons, U guys said it goes  in the ACE3 addons folder(on server) so I moved it.
                This causes AIs to be spawned without uniforms. (so I moved it, )   I don't know if the 
                players can connect because I removed the server.pbo because of the AI uniform problem.
                But now players can definitely connect, and the AIS have uniforms.

I ran the mods as  above in RPT files (sorry GlowBal for the paste here). (user cfg file is in main game directory and applies those settings to all missions when server.pbo is installed).

**Comment by commy2** [comment]
Edited the title. I never heard of this issue. If uniforms disappear, then I'm almost certain that it is an error with the mission and not with @ace.
Can you upload the mission?

**Comment by dvdbrewster** [comment]
https://www.dropbox.com/sh/vr6tezays30u11j/AADiZg2dnI7l7RKQ0wmD3PlJa?dl=0
Both of these develop blufor uniform issues, and spawn problems when using ace_server pbo.
And problems with any placed modules in C) 40  WASP-rhs.

**Comment by commy2** [comment]
Currently looking through these missions.
Can this issue be reproduced on a normal mission with less (bad) scripting?

**Comment by dvdbrewster** [comment]
https://www.dropbox.com/sh/a13u3iyqzbvy6tf/AACVTRiTJn5Cj_bftvIZbCDoa?dl=0

MayB they can be repaired

**Comment by commy2** [comment]
What is that?

**Comment by dvdbrewster** [comment]
It’s the Warlords  missions.  Stratus and Altis  Rhs and regular.
http://www.armaholic.com/page.php?id=28947
