### ISSUE TITLE
Basic Medic system is still not right

### ISSUE THREAD

**Issue by BullHorn7** [acemod/ACE3#2413]
ACE3 Version: 3.3.0.1 RC on stable 1.50

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
NONE

**Description:**
There are numerous issues.

* It takes 5-8 shots to a limb for a player to go unconscious. 
* Fixing the limb with Bandages takes 10-14 to go from "Red" to "Yellow" and then 1 more Bandage to go from "Yellow" to "White". 
* Killing unit by shooting at limbs takes another 15+ bullets.
* Killing via Torso can take 3-8 shots and in most cases the unit goes into shock-unconsciousness 2-3 times, rarely into full-unconsciousness. 
* Headshots seem to be fine.

**Steps to reproduce:**
Test mission is basic: 2 units with MX. One unit shoots the other.

**Where did the issue occur?**
Multiplayer listenserver

**RPT log file:**
http://pastebin.com/TpWQTU1d

**Mission file.**
https://www.dropbox.com/s/09yfq55lq2mbv40/basic%2520ace%2520test.Altis.zip?dl=0

**Comment by bux578** [comment]
https://youtu.be/_HzhK2mnY8s

https://www.youtube.com/watch?v=uujZk9vMgYs

**Comment by BullHorn7** [comment]
The amount of bandages seems to directly correlate to the amount of hits, with a ~2:1 ratio

**Comment by bux578** [comment]
Shots to different body parts:
https://youtu.be/GtC-z0WwB7Y

**Comment by bux578** [comment]
What the leg?
https://youtu.be/WK3TpMeAeZM

**Comment by gienkov** [comment]
Moment when you realize that adv. medical is less bugged than basic XD

**Comment by zerithsmash** [comment]
Pabst has probably already relayed, but we've had 2 sessions with this RC at Bourbon Warfare and we have noticed the same issues as above.

http://forums.bourbonwarfare.site.nfoservers.com/viewtopic.php?f=7&t=2351

**Comment by Glowbal** [comment]
#2424 should adress this
