### ISSUE TITLE
"Keep Cursor Centered" causes interaction menu to fly off-screen

### ISSUE THREAD

**Issue by Zoxjib** [acemod/ACE3#2414]
ACE3 Version: 3.3.0.1 RC - occurred all the way back since 3.0.0.1. Tested on stable 1.50

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
Default ACE3 testing mission, I didn't check.

**Description:**
When using the "Keep Cursor Centered" option in the ACE menu, the interaction menu flies off the screen.

**Steps to reproduce:**
- Enable "Keep Cursor Centered"
- Interact with a unit

**Where did the issue occur?**
Multiplayer listenserver

**RPT log file:**
http://pastebin.com/usvjvZpb

**Debug:**
http://pastebin.com/cCMBctxx

**Video:**
https://www.youtube.com/watch?v=rBIooeiAp-o

**Comment by PabstMirror** [comment]
The video option "sampling" effects `setMousePosition`, and I don't think I can detech when it's changed.

EG put sampling at 50%, and `setMousePosition [0.5, 0.5]` will put it at [0.25, 0.25].

I can't see your mouse cursor in the video, but this may have been a cause.

**Comment by PabstMirror** [comment]
Made BIS Issue: http://feedback.arma3.com/view.php?id=25874

Really isn't anything we can do to fix.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
