### ISSUE TITLE
Visible laser lights up map

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#2416]
ACE3 Version: 3.3.0.1RC

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* None

**Description:**
When using a visible (daylight) laser at night, the laser brightens up the whole map.

**Steps to reproduce:**
* Make sure your weapon has the vanilla laser on it
* Make sure it's nighttime
* Enable IR laser, look at the map - it's completly dark
* Switch to daylight laser, enable laser, look at the map - it's completly bright

**Where did the issue occur?**
* Editor, most likely everywhere else too

**RPT log file:**
* None

**Comment by voiperr** [comment]
Caused by: https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_lightIntensityFromObject.sqf#L28

When the visible laser is on, `isFlashlightOn == true`.

**Comment by commy2** [comment]
It's not "caused by it" to be accurate. This script just needs another exit condition for visible lasers.
(There is a technical reason why it has to be a flashlight.)

**Comment by voiperr** [comment]
Yeah, that was a poor choice of words.
