### ISSUE TITLE
No interface menu

### ISSUE THREAD

**Issue by Wobbinwood** [acemod/ACE3#2417]
The interaction and self-interaction [Windows] button has no effect other than blurring and the screen. No menu-items appear whether one just mouse-over, or press the interaction key. the items are available but mostly unusable because I cannot see/find any menu.

No mods active other than CBA_A3 and ACE3.
All dll's copied to main ARMA3 installation folder and userconfig folder merged with existing one - no joy; the menu stays blurred and blank - the cursor also stuck when holding [Windows]-key

**Comment by alganthe** [comment]
Please follow the [issues guidelines](http://ace3mod.com/wiki/user/how-to-report-an-issue.html)
Also following the installation guide might help you [click me](http://ace3mod.com/wiki/user/installation-guide.html)

**Comment by ViperMaul** [comment]
There appears to be no more activity.
