### ISSUE TITLE
Medical flowcharts

### ISSUE THREAD

**Issue by BullHorn7** [acemod/ACE3#2418]
Ryujin created flowcharts for both Basic and Advanced medical according to the steps described in the Wiki. It might be useful to have them added to the documentation.

Basic:
http://i.imgur.com/SUebcZN.jpg

Advanced:
http://i.imgur.com/LoC3vJP.jpg

**Comment by MikeMatrix** [comment]
Github Protip: use `![Alternative Text](imageurl)` to display an image directly in the issue.
Like this:
![Cool features](http://tclhost.com/WcL14RZ.gif)

**Comment by BullHorn7** [comment]
It's huge like XBox, I left it as a URL on purpose. :)

**Comment by Glowbal** [comment]
## Basic:
![basic medical flow chart](http://i.imgur.com/SUebcZN.jpg)

## Advanced:
![advanced medical flow chart](http://i.imgur.com/LoC3vJP.jpg)

**Comment by Glowbal** [comment]
A few things:

- Wounded and/or Treat the wounds might not be the right term. Maybe use bleeding and bloodloss instead?
- CPR should not happen before any blood loss has been stopped
- Advanced does not cover any thing regarding stabalizing the vitals
- Advanced does not cover any thing related to blood pressure
- Awake is not always the end goal. The prime goal is keeping a casualty alive. The advanced flow char does not reflect this.
- Advanced does not cover potential reopening of the wounds
- Not always necessary to give an IV. You wouldn't give an IV when someone has only had minor blood loss. The system provides information about this, so an adjustment to `has lost a lot of blood` would perhaps be better.

**Comment by BullHorn7** [comment]
The charts are based on the procedures in the Wiki, this shows that they need a rework. We could use some help to improve both.

**Comment by xJenny99x** [comment]
@Glowbal 
CPR should be done when patient is unconc. and has no pulse, even if he is bleeding because that extends the revive timer.

And ALWAYS when someone is shot and no heart rate then CPR will not get him up, it will just extend his revive time and give more time for people to PAK them alive.

**Comment by SilentSpike** [comment]
Not true. CPR can revive people in the revive state, it's just bugged in 3.2.1.

In my opinion, bleeding should be stopped first, what's the point in CPRing someone if they're just going to bleed out? (Perhaps we should make CPR increase rate of bloodloss :smile:)

**Comment by BullHorn7** [comment]
I'm not knowledgeable in medical stuff but I've seen enough Dr. House to know that about 4-5 minutes of cardiac/respiratory arrest is enough to cause permanent brain damage so it should be a race to achieve both a beating heart and bleed control before the patient suffers irreversible brain damage or bleeds out.

Regardless, the flow charts are meant to represent ACE3.3+ Advanced medical behavior let's try to modify the charts to that...

**Comment by Shadowmarine578** [comment]
uh yea and you can bleed out in 10 seconds if hit in the right spot so yea just remember the ditty, STOP THE BLEEDING, START THE BEATING, DRESS THE WOUND, TREAT FOR SHOCK

**Comment by xJenny99x** [comment]
You guys are right. Turns out it was a bug. 

The first thing to do is ALWAYS stop bleeding, if there is any.

**Comment by ssgsmith51** [comment]
What I teach all the guys in my unit is regardless of cardiac arrest, if the PT is still alive ingame to toss TQs on all the injured limbs and control as much bleeding as possible on the head and chest. There is a 30-45 second window I hold them to and anything past 45 min should be 1 course of CPR, and then another 30 seconds of treatment w/ 1 epi and 1 course of cpr. once all bleeding has stopped either by TQs or being bandaged then CPR continues until you get a pulse. If there is the message for blood loss in the Triage Card then during one of the 30 second treatments throw on an IV.
