### ISSUE TITLE
ACE Medical facility module broken?

### ISSUE THREAD

**Issue by captainblaffer** [acemod/ACE3#2420]
ACE 3.2.1

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
Medical Facility

Description:
The set medical facility module appears to be broken on latest ACE version. It used to work in the past. Me and a friend both tried making a mission, syncing the module to several different objects. 
A nearby player would not be recognized as medic. E.g. I could not use epi-pens even though I had them in my inventory.

Steps to reproduce:
N/A

Where did the issue occur?
SP & Dedicated

RPT log file:
N/A

**Comment by alganthe** [comment]
the module doesn't work that way, medical facilities doesn't mean that everyone inside it are medics, it's used in pair with surgical kits and PAK limitations.

**Comment by captainblaffer** [comment]
I don't understand. I'm using only basic medical setting.
What is the purpose of this module using basic medical?

I really remember it working the way  I described in the top post. Or am I thinking of AGM days?

**Comment by alganthe** [comment]
you are surely remembering something else, for basic medical it enables the use of PAKs.

**Comment by captainblaffer** [comment]
I'm pretty sure the PAK can not be used in basic medical

**Comment by gienkov** [comment]
PAK can't be used in basic medical. This module is for PAK and stitching limitations. No use in basic again.

**Comment by captainblaffer** [comment]
Ok, I understand. So currently this set medical facility module can only be used if also advanced medical is being used.

In that case, I'd like to make a feature request, to also have the module support basic medical.
Allow any non-medic nearby the facility to use medical gear( epi-pen, blood).

One more question, what is the difference between the two modules: set medical facility & set medical vehicle?

**Comment by PabstMirror** [comment]
Should be fixed by #3138 in next release 
now an optional setting to boost training, allowing non-medics to use medic equipment.
