### ISSUE TITLE
Fire Damage Radius with RHS enabled.

### ISSUE THREAD

**Issue by blackwatchint** [acemod/ACE3#2426]
ACE3 Version: 3.2.1 stable
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* `@CBA_A3`
* `@ace`
* `@RHS`

**Placed ACE3 Modules:**
* *none - we are using a userconfig to save ace settings
http://pastebin.com/mvWeX5hK *

**Description:**
* Hi. I am part of a bigger Arma III Community. After the 1.50 update, we started to experienced some issues with campfires and destroyed vehicles on fire.
Any source of fire (campfire, destroyed vehicle) has a ridiculous radius at which player takes damage (around 10 meters) which ends in player dying. This only occurs when there is both ACE 3 and RHS enabled. I really hope you can help us resolve this issue, since its drasticaly reducing our ability to play. *

**Steps to reproduce:**
* *1. Join a server.
2. Spawn a campfire or destroy a vehicle.
3. Approach the fire from a safe distance
4. Player will die from fire while not being even close to the source.*

**Where did the issue occur?**
* Multiplayer Issue only *

**RPT log file:**
* http://pastebin.com/CcXwC8XA *

*Below some screenshots of the burn radius (These injuries are not caused by secondary explosions from the tank)

http://images.akamai.steamusercontent.com/ugc/423692186796287425/A367E64100E6FF82ED4FE5BFA952FB018AEEB423/

http://images.akamai.steamusercontent.com/ugc/423692186796287744/1A17BA2ED9856D3EFAB536CC50F8B8A131981E1D/

**Comment by blackwatchint** [comment]
Just to clarify, mods enabled:
@CBA-A3, @ACE3, @RHS,

We are using a custom Ace3 config thanks to one of your modules. Can post it here if you want me to do so.

**Comment by blackwatchint** [comment]
Got an answer from the RHS tracker:
" It's not on us as we don't change any fire effects or any other classes with fire. "

http://feedback.rhsmods.org/view.php?id=1043

**Comment by tourist79** [comment]
@blackwatchint: there is already an issue opened which pinpoints the problem to ACE itself.  I think they have even set a milestone, but not for the nexr version, I fear...  

Just look for issues with the term "fire"; I found it after some clicking through.

**Comment by blackwatchint** [comment]
@tourist79  Yea, I think that is what you are talking about:
https://github.com/acemod/ACE3/issues/1941

My issue sounds similair, but I think it is different, cause of the fact that it only happens with RHS enabled - without everything is all right, and the issue you were talking about is not happening at all.

**Comment by commy2** [comment]
Close as duplicate?
