### ISSUE TITLE
Question: ACE 3 & Stingers?

### ISSUE THREAD

**Issue by Immersi0n** [acemod/ACE3#2427]
ACE3 Version: 3.2.1 Stable

Mods:
@CBA_A3`
@ace

Placed ACE3 Modules:
Unknown not my mission file

Description:
Trying to lock onto hostile air units with a stinger (NATO) but cannot get a lock on. Have tried holding tab & using the ARMA vanilla lock on button (default T) and still nothing. Was wondering if ACE 3 had changed them as i know the javelin has to be zoomed in & FLIR turned on to be able to get a lock. 

Steps to reproduce:
Spawn hostile air asset. Try to lock on with stinger.... Nothing 

Where did the issue occur?
Multiplayer Server

RPT log file:
N/A

**Comment by alganthe** [comment]
There is no stinger in vanilla only the mini spike AA

**Comment by Immersi0n** [comment]
Ah that explains it... Feel stupid now.

**Comment by alganthe** [comment]
If you were refering to the NLAW it's a single shot fire and forget launcher, you can only lock on ground targets with it

**Comment by bux578** [comment]
Why didn't you list the other mods you're using? Just an oversight or is the "how to create an issue" page not specific enough?

**Comment by Immersi0n** [comment]
An oversight. I completely forgot the server I was on has a modpack as I just launch it through a shortcut. Nothing is wrong with what all you are doing. Apologies for the confusion.
