### ISSUE TITLE
Fragmentation: Wrong killer in events.

### ISSUE THREAD

**Issue by Aatu** [acemod/ACE3#2431]
When someone gets killed by a fragmentation grenade, the killer in "MPKilled" event is NULL-object. Killer in "onPlayerKilled" event script is the victim itself. When I was tracking the "Killed" event, I actually got it triggered twice. Once with killer being the victim and once with the actual killer. 

The "hit" event is correct, but if you get instakilled by grenade, the hit event won't fire. (This is correct behavior as per Arma 3 documentation). 

The problem with this is that I would like to have a reliable way of correctly attributing kills. Currently, with  ACE 3 fragmentation I can't.

**Comment by PabstMirror** [comment]
Similar issue with a bullet causing a death via bleeding.

As far as I know there is no way for us to tell the engine that scripted submunition ammo or scripted damage is from a player. So the `killed` events and score tracking will be wrong with ACE and there is nothing we can do about it.

We could look into tracking damage sources and trying to make a score event system of our own, but I don't see that happening anytime soon,

**Comment by Aatu** [comment]
With bleed out it is not that bad of an issue. Because if you get hit, but don't instantly die, the "hit" event gets triggered with correct enemy. This way I can save the enemy that last damaged current player, and if the player dies subsequently without defined killer, it will be attributed to player that caused last damage.

Of course, this might mean that crashing a car will get attributed to someone who shot you some time ago. I am fine with that though. 

Can I just drop the fragmentation addon and use ACE without it?

**Comment by PabstMirror** [comment]
yeah, you could delete frag or just set `ace_frag_Enabled` to false via ace_settings
http://ace3mod.com/wiki/framework/settings-framework.html

Also, if it would help, this should allow you to detect when frag kicks in
```
//Event only happens on server:
["ace_frag_frag_eh", {
    params ["", "_lastPos"];
    systemChat format ["frag near %1", _lastPos];
}] call ace_common_fnc_addEventHandler;
```

**Comment by commy2** [comment]
I don't think this can be resolved due to how this game works. Close?

**Comment by PabstMirror** [comment]
Tagging #414 - But it's probably not something we'll get to anytime soon.

**Comment by commy2** [comment]
ref #3111
