### ISSUE TITLE
Attached item will disappear if you open self-interaction while in vehicle

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#2432]
ACE3 Version: https://github.com/acemod/ACE3/commit/d3b6dd4b453c3961dc86ff138eea7462a826818a

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* *None.*

**Description:**
*That last attached items fix (https://github.com/acemod/ACE3/issues/2200) was great, thanks. But it has one small problem. If you attach a chemlight to yourself and then get into the vehicle and then open self interaction and after that get out of the car the chemlight will just disappear. The fastest work around I guess is just to detach that chemlight and put it back to the inventory when entering a vehicle. Hard way - well I don't know, find the reason why it disappears.*

**Steps to reproduce:**
* *attach a chemlight to yourself.*
* *get into the vehicle and then open self interaction.*
* *get out of the car. the chemlight will just disappear.*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*No need.*

**Comment by PabstMirror** [comment]
Thanks for the report, I added a check to handle null attached objects, but it broke when run while mounted in a vehicle.
