### ISSUE TITLE
Medical stuff

### ISSUE THREAD

**Issue by UrukCan** [acemod/ACE3#2436]
1. Looking through the ace3 files, I noticed painkillers, however I failed to find them ingame?

2. Forced to walk after any type of leg wound. Only solution to turn on healing (?) or PAK. Might be nice to have a splint or something like that. 

3. In the files you have FieldDressing and QuickClot, while ingame you use Bandage (Basic) and FieldDressing (QuickClot). Might get a little bit confusing and I'm still not 100% sure if FieldDressing is Bandage (Basic)...

4. Body bags are even larger than PAK what means that there is actually no use for them in a hot zone...

5. Quick question: what's the difference between Pasma Blood and Saline?

**Comment by BaerMitUmlaut** [comment]
1. There are no painkillers (other than morphine) currently implemented. There might be more medicine against pain coming sooner or later.
2. Enable "remove bloodstains" in the module.
3. The classname doesn't have to be the same as the name shown in game. It's not really an issue imo.
4. They don't serve they same purpose, so I don't see why you are comparing them?
5. The effects are the same. In real life I believe only saline doesn't need cooling, so it's probably the most realistic to give to medics.

**Comment by SilentSpike** [comment]
With regards to point 2: https://github.com/acemod/ACE3/issues/2389#issuecomment-139517450

A splint is still an interesting idea though

**Comment by Dobakjang** [comment]
Enable "remove bloodstains" in the module.

this thing is not working in dedicated server, i test with my friend, they still walking, what's the solution?
