### ISSUE TITLE
ACE3 RHS 0.3.9 No Interaction On Russian Units

### ISSUE THREAD

**Issue by moonmanmove** [acemod/ACE3#2437]
ACE3 Version: 3.2.1 (stable0

Mods:
@CBA_A3
@ace
@rhs 0.3.9

Placed ACE3 Modules:
none

Description:
No self interaction on russian units, cannot interact with them either.

Steps to reproduce:
place down unit from russian opfor faction
try to self interact no interaction available

Where did the issue occur?
Singleplayer

RPT log file:
http://pastebin.com/REHewrYY

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by moonmanmove** [comment]
rpt up

**Comment by PabstMirror** [comment]
Could you try moving the `cba_enable_auto_xeh.pbo` from CBA's optional folder to addons?

**Comment by moonmanmove** [comment]
@PabstMirror 
yep, that fixes it, do you want the RPT from that?

**Comment by jokoho48** [comment]
no its a mod fault we cant not fix this

**Comment by alganthe** [comment]
Mod's fault check the ACE3 team official statement here [click me](http://ace3mod.com/wiki/user/information-center.html#1-3-compatibility) about hose issues.

**Comment by moonmanmove** [comment]
http://i.imgur.com/SAV8SqI.png
well there's RHS response on the issue, is it only fixable on their end?

**Comment by PabstMirror** [comment]
```
	class SoldierGB: CAManBase {
		class EventHandlers: EventHandlers {
			init = "this setVariable [""BIS_fnc_unitHeadgear"",false];";
		};
	};
```

So this will break both RHS and AAF (`class I_Soldier_base_F: SoldierGB`) units!

In the past they've always done 
`init = "_this call SLX_XEH_EH_Init;_this spawn RHS_fnc_t80_init;....`
which kept CBA compatibility and allowed them to use their own EventHandlers without requiring CBA.

I have no idea why they've stopped offering backwards compatibility, I hope it's just a mistake that they will fix.

In any case, we really need to stress that cba_enable_auto_xeh.pbo should be added.

**Comment by SilentSpike** [comment]
Yes, only they can fix this. the auto_xeh pbo is a good workaround though :+1:

**Comment by DerekSauer** [comment]
Look like the RHS team has corrected this on their end:

https://forums.bistudio.com/topic/183435-rhs-escalation-afrf-and-usaf/?p=2913460

**Comment by PabstMirror** [comment]
Good to hear
