### ISSUE TITLE
Map stays dark even if the NVGs are on

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#2440]
ACE3 Version: 5a76fec89567b3843bd8d45bf0d0f9727b0d3428

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* *None.*

**Description:**
*Map stays dark even if the NVGs are on.*

**Steps to reproduce:**
* *Set time to night time.*
* *Put on your NVGs.*
* *Open the map. It's dark, the illumination doesn't work.*

**Where did the issue occur?**
* "Multiplayer", "Singleplayer"

**RPT log file:**
* No need.*

**Comment by voiperr** [comment]
Intended. In reality, you have to readjust your nightvision focus all the way to the shortest focus, and then all the way to infinity once you look up again. This is a lengthy process, and is rarely done. If someone with experience wants to chime in and contend that it's quick/easy/done commonly, I'm all ears.

Regardless, there's no easy way to portray this focus change to a degree that's convincing. I might be working on one in the future, but not for this version.

**Comment by rebelvg** [comment]
Oh, okay, just wanted to clear things out because it worked before. Thanks.

**Comment by alganthe** [comment]
in the meantime flashlights or chemlights all the way

**Comment by Nagrach** [comment]
problem . in reallife you got a tiny little combat light with small slits to provide light for a solider without exposing himself.
Atm we dont have any combat light that provide those features. 
http://www.green-store.ch/images/product_images/info_images/16373_0.jpg

**Comment by alganthe** [comment]
we do actually.

**Comment by captainblaffer** [comment]
Is this a bug or not? voiperr claims not, PabstMirror tagged it as a bug.

Personally I think this is going to be really annoying. Not being able to use the map without NVG was already bad enough. I can understand some people may like the realism. But I would vote for having it disabled per default. I'll definitely remove ace_map.pbo from my modset once this goes live.

having to add mod specific items to all players inventory in every single mission just to use basic features isn't the way to go imo. Imagine a feature which makes half the players screen blurry unless they have the correct glasses item in their inventory...

**Comment by rebelvg** [comment]
@alganthe How to use those flashlights? I equipped them but the map was still dark. Is there some key or how does it work?

**Comment by alganthe** [comment]
self interact -> flashlights -> on

**Comment by Nagrach** [comment]
i just tested it via editor but iam not able to find a flashlight - and i never was beside the gun flashlight. 
and then - the next question - how big/heavy is this light and does it illuminate only your map or does it work as a normal flashlight?
When this thing works like a vanilla flashlight - its useless - not because its working in the way it should - but illuminate yourself with a floodlight of a flashlight in a warzone sounds utterly stupid.
So - no - a vanilla light source to see stuff on your map is crap.

**Comment by alganthe** [comment]
First, the flashlights are available only in 3.3.0 stable or on the current master which this bug report is on.
Second it's an item working on the map only.
Third the outer glow can be disabled.

**Comment by voiperr** [comment]
The new flashlights are in the `[ACE] Miscellaneous Items` ammo box, or can by placed under `Weapon Accessories`. Classnames: "ACE_Flashlight_MX991" (NATO), "ACE_Flashlight_KSF1" (Soviet Bloc/East), "ACE_Flashlight_XL50" (Independent).

**Comment by PabstMirror** [comment]
We already have a module setting to disable map illumination.
It seems reasonable that it would be hard to read fine detail with NVGS.

If anyone has real life experience that we could use, please chime in. I could see very modern NVGS possible having better auto-focus??

**Comment by Nagrach** [comment]
I just tested the 3.3 version with the new flashlights and i wasnt able to get them to work.
Attach strobo and chemlight is working fine but the new flashlights dosnt.
So maybe map illumination should be disabled by default until fix.

**Comment by PabstMirror** [comment]
If you have a flashlight in your inventory you should get something like this when self interaction on the map:
![image](https://cloud.githubusercontent.com/assets/9376747/9916985/dec0a87c-5c84-11e5-8b31-dd088530cdf5.png)

**Comment by Nagrach** [comment]
uh! it only works on the map!?
Okay - this makes sense now. 
I didnt test it on the map - shame on me
