### ISSUE TITLE
Replaced wheels don't reapear after being fixe

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#2444]
ACE3 Version: 3.3.0 stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
- Debug output here -> [pastbin](http://pastebin.com/6xF2HpT5)

**Description:**
After being destroyed wheels are still missing the tires.

**Steps to reproduce:**
- Place a rifleman
- Place the `repair settings` module
- Set wheel repairs to not require a toolkit
- Place a vehicle
- Press preview
- Shoot a wheel and replace it, notice that the wheel is still missing.

**Where did the issue occur?**
Editor

**RPT log file:**
RPT [pastebin](http://pastebin.com/KHyp5geM)

**Comment by jokoho48** [comment]
https://www.youtube.com/watch?v=-1nzYnpKDh0&feature=youtu.be
Attach Video from LinuxMaster9 out of slack

**Comment by PabstMirror** [comment]
Should be fixed by e254af99640704e3ca8af141bed66573d0448a28

**Comment by alganthe** [comment]
issue fixed
