### ISSUE TITLE
Cargo items float 100m above the vehicles

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#2445]
ACE3 Version: 3.3.0 stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
debug here -> [pastebin](http://pastebin.com/wScGB6LY)

**Description:**
Cargo items float 100m above the vehicles they are loaded in
screenshot here -> [puush](http://puu.sh/kcFmF/b796dfcf03.jpg)

**Steps to reproduce:**
- Place a rifleman
- Place a vehicle
- Press preview
- Look up

**Where did the issue occur?**
Editor

**RPT log file:**
RPT -> [pastebin](http://pastebin.com/L2iyWf77)

**Comment by PabstMirror** [comment]
Should be fixed by e254af99640704e3ca8af141bed66573d0448a28

**Comment by alganthe** [comment]
issue fixed
