### ISSUE TITLE
Option to take prisoner does nothing

### ISSUE THREAD

**Issue by Gilatar** [acemod/ACE3#2447]
ACE3 Version: 3.3.0 stable

Mods:
@CBA_A3
@ace

Placed ACE3 Module:
ACE -> Captives Settings

Can handcuff own side: Yes
Allow surrendering: Yes
Require surrendering: No

Description:
With/without the module placed down, regardless if a unit has surrendered or not, the option to cable tie does nothing at all. 

Steps to reproduce:
Place two rifleman, one non-playable one player,
Place ACE miscellaneous box,
Place ACE Captives Module,
Preview,
Grab cable ties, 
Attempt to cable tie AI - nothing will happen

Where did the issue occur?
Editor & non-dedicated internet server

.RPT:
http://pastebin.com/dLyv4jYu

**Comment by PabstMirror** [comment]
Should be fixed by e254af99640704e3ca8af141bed66573d0448a28
