### ISSUE TITLE
On dedicated, removing wheel will don't remove it, but after action is complete a copy of wheel will show up

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2449]
ACE3 Version: 3.3.0

**Mods:**
* `@CBA_A3`
* `@ace`
* `@RHS`

**Placed ACE3 Modules:**
* *Repair.*

**Description:**
* When you try to remove wheel it will not remove it, but copy will be created anyway, after a few tries you end up with this:*
http://steamcommunity.com/sharedfiles/filedetails/?id=519020302
And not being able to remove wheel.

**Steps to reproduce:**
* *Try to remove wheel on dedicated.*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
* -*

**Comment by jokoho48** [comment]
#2444 same issue but other point of entry

**Comment by xJenny99x** [comment]
hotfix when ?

**Comment by alganthe** [comment]
soonTM
