### ISSUE TITLE
Interaction does not work.

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#2450]
I am trying to interact with an AI dude next to me and it does not twork. It just shows that red circle and that's all.I tried from every side and stuff.

I think it's pretty bad.

**Comment by PabstMirror** [comment]
* Could you please include a RPT file (can be found in %localappdata%/Arma 3/ and look for the most recent file likearma3_2015-08-01_22-17-40.rpt and dump it on pastebin.com)
* Please try adding the CBA compat pbo, and make sure you are running the most recent version of CBA.

>We have noticed that when using ACE with 3rd-Party mods that do not fully support CBA Extended Eventhandlers (XEH) that some units do not work with Interaction fully. You may see the cursor but no menus.

>WORKAROUND: The latest CBA RC7 Hotfix 2, v1.1.23 has an optional PBO that you can activate to help resolve these situations. 
1. Move the cba_enable_auto_xeh.pbo and its signature file from the CBA optional folder to the CBA Addons folder
2. Restart Arma.

**Comment by jokoho48** [comment]
please read this: http://ace3mod.com/wiki/user/how-to-report-an-issue.html and edit your Post thanks
