### ISSUE TITLE
Body Repairpoint is not on the right position on a hatchback

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#2452]
ACE3 Version: 3.3.1RC

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* None

**Description:**
![2015-09-16_00001](https://cloud.githubusercontent.com/assets/1235520/9896413/fae11d6e-5c3b-11e5-958f-a958396f67fd.jpg)

**Steps to reproduce:**
* Place Hatchback
* Shoot both right wheels
* Inflict enough damage to turn the body yellow/red
* Repair the back right wheel

**Where did the issue occur?**
* "Editor"

**RPT log file:**
not needed

**Comment by PabstMirror** [comment]
`cursorTarget selectionPosition "karoserie"` is pretty much on the right front wheel.
I don't know how much we can do if the vehicles's config is bad.

We could look into putting the body//hull repair on the mainActions tree, as it is a repair point that really doesn't have a position that would be intuitive to find.

**Comment by jonpas** [comment]
I added a framework for custom positions of hitpoints, use that.
