### ISSUE TITLE
Script error in 3.3.1RC after doing logisitcs

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#2454]
ACE3 Version: 3.3.1RC

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* None

**Description:**
After a short test of logistics and vehicle repair I have these script errors in my RPT
```
6:36:13 Error in expression <type>
 6:36:13   Error position: <>
 6:36:13   Error Invalid number in expression
```

**Steps to reproduce:**
* #2452
* #2453 

**Where did the issue occur?**
* "Editor"

**RPT log file:**
http://pastebin.com/5JeE8ErM

**Comment by PabstMirror** [comment]
Are you sure this isn't from debug console?
It switches from `Error in expression <type>` to `Error in expression <typeof>`

**Comment by bux578** [comment]
Oh, might be. Sorry, it was like 6am.
