### ISSUE TITLE
Medical bugged

### ISSUE THREAD

**Issue by burnacid** [acemod/ACE3#2455]
ACE3 Version: 3.2.1

**Mods:**
* `@CBA_A3`
* `@ace`
* `@Ares`
* `@ASR_AI3`
* `@FFISv1.25`

**Placed ACE3 Modules:**
* `Advanced Ballistics`
* `Captives settings`
* `Hearing`
* `Interaction System`
* `Map`
* `Respawn System`
* `Weather`
* `Wind Deflection`
* `Zeus Settings`
* `Medical Settings`
* `Advanced Medical Settings`
* `Revive Settings`

**Description:**
Yesterday my ace mission probably fucked up somewhere but I have no clue how.
If a player just takes the slightest damage (like a pistol shot to the foot) he will be "dead" (unconscious). All his bodyparts register as red (with basic medical system on). Trying to revive is no use.

Even if you manage to fix every part within a really short period of time. He will never wake up. Not even after administrating Epi Pen

What happened? Anyone any idea?

**Steps to reproduce:**
Explained above

**Where did the issue occur?**
Multiplayer

**RPT log file:**
Will be uploaded tonight

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by burnacid** [comment]
Changed it, will try and provide the log tonight. Where is this file located?

**Comment by gienkov** [comment]
%localappdata%/Arma 3/RPT files
16 wrz 2015 9:31 AM "Stefan Lenders" <notifications@github.com> napisał(a):

**Comment by bux578** [comment]
Could you please try to reproduce it with the newest ACE3 version 3.3.0 and only cba_a3 and ACE3.

**Comment by burnacid** [comment]
Yea saw it was just released. Will update that tonight and retry else you get the most recent logs with the new version.

**Comment by burnacid** [comment]
Oke let me add some information. Medical works On AI. If it is concerning another player 1 shot kill and unable to revive. All health stats remain white this time. Epi pen has no effect.

Just updated through workshop.

Sidenote. Diagnose in the player doesn't show anything. The screen flickers for 1 frame but it doesn't show the box anymore. The health menu which was added doesn't work either for me

http://pastebin.com/WvVziYgh

**Comment by burnacid** [comment]
Oke good news and some weird shit. It was only the Zeus player slot.....
Deleted the player in the editor and readded him. Now it is fine

**Comment by burnacid** [comment]
Oke I've done some extensive testing. Tried a lot and came to the conclusion.
If the game has no player in a Zeus slot it works fine.
When a Zeus enters the game. Everything gets weird.

What have I done so far:
* Reinstalled all mods
* Completly remade the missionfile
* Removed all mods except CBA and ACE (did not do anything)

Added latest log
http://pastebin.com/mAArJdMh

What all the time happens, I shoot someone with 1 bullet. He goes to the ground and turns on his back. Unable to heal anything and the player gets a dead timer. (this is when a Zeus is within the game)

If zeus is not in the game. 1 bullet may knock someone unconsious for a few sec but does not kill the player at all. No timers. Just a bandage and he is good to go (what you would expect)

Any clue how this is possible?

**Comment by commy2** [comment]
Is this reprocuable on a newly created mission with only CBA and ACE enabled?

**Comment by burnacid** [comment]
Do you mean reproducible for you or other players? 

I don't know. I'll have someone else try and create the missionfile and host the server.

**Comment by commy2** [comment]
I asked if you can reproduce it on a newly created mission with only CBA and ACE enabled.

**Comment by burnacid** [comment]
Well yes, but i've done the following. I asked a friend to host. Recreate the map and it worked fine. I've send him my mission file and it worked fine as long as he hosted it.

So somewhere my Arma3 is fucked up. I'm reinstalling now to see if it fixes anything. Keep you in the loop

**Comment by burnacid** [comment]
Oke I really get anoyed by this... Completely reinstalled everything.

Deleted Arma 3 in steamapps
Deleted Arma 3 in documents
Deleted Arma 3 - other profiles in documents
Deleted Arma 3 in %localappdata%

Reinstalled through steam
Mods were downloaded thought steam workshop. Only launched with ACE and CBA

And still if I host it the same map my friend did (which then worked fine) it just doesn't work. I kill everyone in 1 bullet to the foot.

**Comment by burnacid** [comment]
Oke we found out that as soon as someone joins a zeus slot everything fucks up. If no one joins zeus it works perfectly. How? Only CBA and ACE enabled

**Comment by Glowbal** [comment]
Hi,

Could you please provide an rpt log file from a session where you were able to reproduce this issue using just `CBA_A3` and `ACE3 3.3.1`?

The provided rpt log files are all from sessions with additional mods (such as cup weapons).

Also could you clarify if this issue is just for yourself in MP or are other people in your sessions experiencing the same behaviour?
----
_As a side note, you no longer require to load up `asdg_jointrails`, as it is now part of `CBA_A3`_

**Comment by burnacid** [comment]
It is in MP all players..... BUT WE FOUND IT. some players started with Curator Preset Mods. CPM has a revive system intergrated apperrently....

Took us 3 evenings to figure that out but thanks anyway. 

Closed

**Comment by commy2** [comment]
lol nice.
