### ISSUE TITLE
Heavy irrecoverable performance impact with Advanced Ballistics enabled

### ISSUE THREAD

**Issue by Raspu86** [acemod/ACE3#2456]
ACE3 Version: 3.3.0.1 RC (private build released by Glowbal on Sept. 10th)

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* *class ace_advanced_ballistics_enabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_simulateForSnipers {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_simulateForGroupMembers {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_simulateForEveryone {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_disabledInFullAutoMode {
    value = 0;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_ammoTemperatureEnabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_barrelLengthInfluenceEnabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_bulletTraceEnabled {
    value = 1;
    typeName = "BOOL";
    force = 1;
};
class ace_advanced_ballistics_simulationInterval {
    value = 0.05;
    typeName = "SCALAR";
    force = 1;
};
class ace_advanced_ballistics_simulationRadius {
    value = 1500;
    typeName = "SCALAR";
    force = 1;
};*

**Description:**
* With AB enabled (in my case only for snipers) there is a huge performance impact in multiplayer games all tough no sniper rifles or high powered scopes were used. FPS dropped from 60 frames to 15 and won't recover anymore. If AB is disabled FPS stays fine.*

**Steps to reproduce:**
* *Our testing setup:
- 4 players, Dedicated server.
- Grab MX rifles.
- Shoot a few mags and observe FPS. 
FPS will drop rapidly and stay on a very low value.*

**Where did the issue occur?**
* Multiplayer*

**RPT log file:**
* none*

**Comment by gienkov** [comment]
Its bugged in release, wait for fix.
16 wrz 2015 9:01 AM "Raspu86" <notifications@github.com> napisał(a):

**Comment by jokoho48** [comment]
#2458
