### ISSUE TITLE
Tire replacement bug

### ISSUE THREAD

**Issue by Ovenmit** [acemod/ACE3#2461]
Tires can be removed endlessly, creating a new model every time:

http://images.akamai.steamusercontent.com/ugc/683775440072475998/5CA37A2763E0AC49C14D1C2DEE0E83A766C62547/

I've also noticed that replacing a damaged tire does not change the vehicles tire model , leaves it in a damaged state. The repair animation does run, etc

Although this is an RHS truck, I did try it with the same results on a vanilla A3 FIA truck too.

**Comment by jokoho48** [comment]
allready fixed
