### ISSUE TITLE
Repair non-functional

### ISSUE THREAD

**Issue by SonixApache** [acemod/ACE3#2462]
ACE3 Version: 3.3.0

Mods:
@cba_a3 (Build 2.0.0.150817)

Placed ACE3 Modules:
N/A

Description:
None of the repair functions actually work.
Removing a wheel spawns a wheel next to you, but does not affect the vehicle. Similarly, trying to change a destroyed wheel will remove a nearby wheel, but also not affect the vehicle. Repairing other modules has no effect either.

Steps to reproduce:
Remove a wheel.
Destroy and try to change a wheel.

Repro mission:
https://www.dropbox.com/s/70bjb7afakw9wo1/brokenrepair.VR.pbo?dl=0

Where did the issue occur?
Singleplayer

RPT log file:
https://www.dropbox.com/s/5tqto61g2m64htn/arma3_2015-09-16_17-34-52.rpt?dl=0

**Comment by jokoho48** [comment]
allready fixed in https://github.com/acemod/ACE3/commit/e254af99640704e3ca8af141bed66573d0448a28
