### ISSUE TITLE
SwitchUnits: Missing english translation

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#2469]
STR_ACE_SwitchUnits_Module_Description defaults to polish right now.

**Comment by commy2** [comment]
Caused by this commit.
https://github.com/acemod/ACE3/commit/08b7110e583b2048f8c61e7770eab09bc56dec56

The commit is really weird. No idea why it was merged.
Probably messed up different stuff too.

**Comment by SilentSpike** [comment]
It looks like there was no english string before that commit either

**Comment by commy2** [comment]
Any idea why this commit is so weird and changes lines without changing them?

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/commit/2b23958fd184b81585b0d938858bc6f66e23c6c9#diff-05870c2aa40a2b4c86913a5da5ba98a6L133

Maybe there never was a english translation? This commit deleted the empty string.

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/pull/2470

**Comment by SilentSpike** [comment]
>Any idea why this commit is so weird and changes lines without changing them?

EOL characters maybe?
