### ISSUE TITLE
Medical Basic: Missing Diagnose on Torso

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#2472]
ACE3 Version: 3.3.1 A3 Stable

@CBA_A3
@ace

Placed ACE3 Modules:
Medical Settings (defaults used)
Medical Menu (Activated)

Description:
3.3.0 Announced Diagnose would be on the torso for basic Medical system.
Checking AI test buddy  no diagnose options are appearing on test buddys torso.

Steps to reproduce:
1. Set-up player and AI
2. Check AI torso for diagnose none seen.
3. Injure AI until out cold.
4. Check AI torso for diagnose none seen.

Where did the issue occur?
"Singleplayer"*

RPT log file:
No Errors

**Comment by captainblaffer** [comment]
IIRC CPR only appears with revive module on

**Comment by john681611** [comment]
Noted Edited

**Comment by Glowbal** [comment]
Basic medical only has CPR available if the revive module is enabled.

**Comment by commy2** [comment]
Isn't diagnose supposed to be on the head?

**Comment by bux578** [comment]
https://github.com/acemod/ACE3/releases/tag/v3.3.0

`Allow diagnose action on torso (#2361)`

**Comment by commy2** [comment]
I can confirm then that it is on the head only in 3.3.1.  At least in BASIC.

**Comment by burnacid** [comment]
Same here

**Comment by Dumedo** [comment]
3.3.1 basic, medical menu. We have diagnose only on head.

**Comment by PabstMirror** [comment]
Fixed Via #2557
