### ISSUE TITLE
Medical Menu Not showing.

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#2473]
ACE3 Version: 3.3.1 A3 Stable

@CBA_A3
@ace

Placed ACE3 Modules:
Medical Settings (defaults used)
Medical Menu (Activated)

Description:
Medical Menu was added in 3.3.0. but pressing the key assigned does nothing.

Steps to reproduce:
1. Set-up player and AI
2. Press show medical menu button (H) nothing happens
3. Injure AI until out cold.
4. Press show medical menu button (H) nothing happens
5. Attempt to change key, nothing.

Where did the issue occur?
"Singleplayer"*

RPT log file:
http://pastebin.com/TCbgBU0p

**Comment by commy2** [comment]
There is no hint for this. I'll port some strings from AGM.

**Comment by Glowbal** [comment]
Did you enable the menu in your client settings?

**Comment by john681611** [comment]
Err. I'll give it a second test where is the setting exactly?

**Comment by Dumedo** [comment]
Esc->ace options->all categories->use medical menu->yes

check also in 

Esc->configure->controls->configure addons->ace3 commons

on "open medical menu" you should have "H" by default

**Comment by burnacid** [comment]
I'd like to comment I have the same experience can't get the medical menu to work. The option Use medical menu doens't exist for me running 3.3.1

Even editing the key bind does nothing

**Comment by john681611** [comment]
OK confirmed working once I've found the option.
Note that its probably a good idea to put it under Medical in the options.

**Comment by ViperMaul** [comment]
It is our plan to put it under Medical. But other more important issues were targeted and fixed before release. Glad to hear you got it working.
