### ISSUE TITLE
Medical: Diagnose screen flash

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#2474]
ACE3 Version: 3.3.1 A3 Stable

@CBA_A3
@ace

Placed ACE3 Modules:
Medical Settings (defaults used)
Medical Menu (Activated)

Description:
When finishing Diagnose screen flashes as if there was a UI coming up and closing instantly

Steps to reproduce:
1. Set-up player and AI
2. Diagnose and observe screen flash right at end (just as hint shows)
3. Injure AI until out cold.
4. Diagnose and observe screen flash right at end (just as hint shows)

Where did the issue occur?
"Singleplayer"*

RPT log file:
http://pastebin.com/stfLUKqU

**Comment by commy2** [comment]
RPT "No Errors" is not sufficient for this.

**Comment by john681611** [comment]
Added but show scripting errors popped up nothing either

**Comment by commy2** [comment]
Your RPT doesn't seem to be complete. There is stuff missing at the top of the file.

**Comment by john681611** [comment]
Link updated

**Comment by commy2** [comment]
Can't reproduce. This is my mission:

http://www.mediafire.com/download/l2c2k178le70ra6/__ace+medic+menu+flashing.Stratis.zip

**Comment by john681611** [comment]
Used your mission still happens. I'm using PWS to update if that helps. went from 3.2.1 to 3.3.0 to 3.2.1.then 3.3.1

**Comment by Glowbal** [comment]
Is it possible for you to record and upload a short clip, showing what is happening?

**Comment by commy2** [comment]
I think I know what he means.

`0 spawn {sleep 2; player switchMove animationState player}`
does the same.


https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatment_success.sqf#L27-L40
`doAnimation 2` is based on switchMove. Probably want to do a sanity check to prevent switchMove'ing into the same animation. Even better would be using `doAnimation 1`, but I don't know if all possible animations allow for that.

**Comment by john681611** [comment]
more testing seems to show sudden head-movement possibly mistaken for flash. If you want I'll do a video with clips of a my issues

**Comment by commy2** [comment]
Nah. Save you that time. I identitfied the problem already.

**Comment by john681611** [comment]
Thanks guys :D
