### ISSUE TITLE
Cargo: Unload locations unsuitable 

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#2475]
ACE3 Version: 3.3.1 A3 Stable

@CBA_A3
@ace

Placed ACE3 Modules:
None

Description:
When unloading cargo from a vehicle the object unloads no where near the player who requested the cargo be unloaded. Testing with wheel I found it to be usually on another side of the vehicle (more often than not complete opposite side of vehicle) and significant distance from the vehicle or player. Shouldn't unloading items place it at the nearest available place or the requester or even better directly into the players hands. 

Steps to reproduce:
1. Set-up player and empty vehicle (hunter used)
2. Enter vehicle cargo and unload wheel.
3. Observe location of wheels unloading. (you may have to search)

Where did the issue occur?
"Singleplayer"*

RPT log file:
No Errors

**Comment by PabstMirror** [comment]
Yeah, I wanted to look at this too.
Right now we just search for a safe place, I'd like to search for several safe places and pick the one closest to the player.

**Comment by alganthe** [comment]
why not a fixed position next to the vehicle / behind it ? The players would then know where it's going to be unloaded and not stand there ?

**Comment by jonpas** [comment]
You can't rely on that alone @alganthe, ever.

**Comment by john681611** [comment]
Why not directly into the players hands?

**Comment by TheConen** [comment]
I suggest a mix of the mentioned methods: a preferred position right behind the vehicle which always get checked first, it that's not available, search for another one. Or, if possible, directly into the players hands so he can choose by himself where to put it down.

**Comment by bux578** [comment]
:+1: for player hands if the box is not too heavy

**Comment by headedhorseman101** [comment]
>Why not directly into the players hands?

If the player is to close to the vehicle and facing it or another player, it might clip with the vehicle (spontaneous combustion would be inevitable in that case) or another player might be injured or killed by the same clipping if the unloaded is not facing the vehicle.

**Comment by NemesisRE** [comment]
I noticed that the save place thing is not working that well. I used a Mi-48 Kajman and unloaded different crates. Very often they are unloaded under the front wheel and bigger crates in the middle under the heli itself.
