### ISSUE TITLE
Loading has no indication for what its loading into

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#2476]
ACE3 Version: 3.3.1 A3 Stable

@CBA_A3
@ace

Placed ACE3 Modules:
None

Description:
Loading object into a vehicle gives no indication of which vehicle its going to be loaded in. I can see this becoming a source of confusion with closely parked vehicles. simple hint or addition of vehicle name (maybe distance too) on the action would solve this.

Steps to reproduce:
1. Set-up player and vehicles in close proximity (hunters used) 
2. Unload Wheel from vehicle.
3. Move Wheel between vehicles.
4. Use interaction menu to look at the load action.
5. Observe lack of information on which vehicle it will be loaded into.

Where did the issue occur?
"Singleplayer"*

RPT log file:
No Errors

**Comment by commy2** [comment]
>There is no hint for this. I'll port some strings from AGM.
