### ISSUE TITLE
Floating spare parts

### ISSUE THREAD

**Issue by Spookeh** [acemod/ACE3#2478]
Since the spare parts were added in the last update spare tyres and track links have been floating aprox. 100 meters above every vehicle. I also run RHS, but vanilla vehicle seem to be affected as well. When a wheel or track is unloaded from the vehicle it disappears from the sky.

**Comment by jokoho48** [comment]
duplicated to #2445  allready fixed in newst version (3.3.1)

**Comment by commy2** [comment]
> floating aprox. 100 meters

It was exactly 100 meters. Fixed in 3.3.2 or 3.3.1 or whatever the newest version is.

**Comment by jokoho48** [comment]
@commy2 3.3.1
