### ISSUE TITLE
After update 3.3.1. the voice of the player is the commander disappeared.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2484]
ACE3 Version: 3.3.1 Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
When the commander-the player gives the order (e.g. move forward, backward, right, etc.) couldn't hear his voice

**Steps to reproduce:**
Order to his subordinates any move-commands (in the editor)

**Where did the issue occur?**
Editor

**RPT log file:**
not needed

**Comment by commy2** [comment]
That's a feature.
https://github.com/acemod/ACE3/tree/master/addons/noradio
ace_noradio.pbo disables the player avatar from speaker, because that is annoying and unrealistic, especially in COOP.

If you don't like this, then you can delete the ace_noradio.pbo file.

**Comment by mickeymen** [comment]
I tried to delete this, but there is no effect. The player still without a voice.

**Comment by mickeymen** [comment]
thanks my friend. this is works! but this mod feature is strange feature

**Comment by commy2** [comment]
If you ever played COOP, you'd love it.
Nothing worse than the avatars talking random stuff while you get an incoming radio message or the player unit detecting some enemy and even showing distance and direction in the chat!

**Comment by mickeymen** [comment]
thanks, understand

**Comment by CraigeJC** [comment]
Need an ACE option to disable Noradio.pbo, please.

**Comment by PabstMirror** [comment]
@CraigeJC 
Addon Options -> Ace Common -> Mute Player
