### ISSUE TITLE
Bad and not realistic effect at hit into soldier.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2485]
ACE3 Version: 3.3.1
Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
Sometimes, when the bullet hits the soldier (but not killing him) this soldier falls to the ground at a speed of 0.5 second! Example here: https://youtu.be/ku9y4-Rbmyw

It looks very bad and not realistic. Also entirely unclear, why the soldier falls to the ground? He lies on the ground face down, but not die. Maybe he loses consciousness? The player only one thing remains. To think about what I wanted to show the developers. I think, in any case this is a poorly implemented idea. This point is very spoiled any mod, especially if it's realism mod, please remove or fix this detail.

**Steps to reproduce:**
Open editor and shoot in your subordinates, as in my video example. Note! This does not always happen, and probably you will need to try several times.

**Where did the issue occur?**
Editor

**RPT log file:**
not needed

**Comment by commy2** [comment]
He is falling unconscious there. There is no better animation for us to use.

**Comment by mickeymen** [comment]
For the team of ACE3 developers no exist ways to create new animations? I think that unfortunately weak animations are a feature of vanilla ARMA. The game needs a lot of animations for special actions. For example, the installation of static weapons, setting and clearing mines,  repairing of vehicles, medical operations and etc. Also the animation hits in the vanilla game are absurd. 
If the ACE3 developers will be able to create new animations for these items, then it will be very cool!
Not possible task?

**Comment by mickeymen** [comment]
if developers team can't create a new animation, then the at loss of consciousness is better to use ragdoll (just my opinion)

**Comment by commy2** [comment]
Idealy we would just ragdoll an unconscious unit. There is no API for that though. The engine doesn't allow for it, because the necessary commands are missing.
If BI added a `forceRagdoll` command or something similar it would be implemented by us in an hour.

**Comment by mickeymen** [comment]
Try at least to make it slower. The fact that there now in my opinion unrealistic quickly. But of course I understand that your opinion may differ from my opinion

**Comment by commy2** [comment]
It can't be made slower. It is not a transitional animation.

**Comment by mickeymen** [comment]
sorry to me. Thus, not wishing to see this bad animation, the player will be forced to always disable the "loss of consciousness" through the modules?

**Comment by commy2** [comment]
`loss of consciousness` I don't think there is such a option for players. You could disable it for AIs though. Then they die instead of losing contiousness.

**Comment by mickeymen** [comment]
Thanks for the replies. Of course excuse my pickiness, but this animation I didn't like most in ACE3. It is a pity that can't be fixed(

**Comment by commy2** [comment]
Same here. No one seems to know a good alternative though.

**Comment by mickeymen** [comment]
Dear developers, this animation in ACE3 looks disgusting. Please try to use the the ragdoll effect. For example, when the loss of consciousness, with scripts for several seconds you can use death of this unit (that unit to fell like a rag doll) and then after this falling to the ground (after 2 seconds), you can spice up this unit, in state of unconsciousness/

**Comment by commy2** [comment]
Dude, I already explained you why it is not possible. We desire a better solution just as you do and are on the lookout for new methods with every patch that comes with Arma.
But it's currently not possible regardless how often we are asked about this.

**Comment by mickeymen** [comment]
Then do not close this question. I want this issue was not forgotten

**Comment by mickeymen** [comment]
Ugly animation when the soldier loses consciousnes, but most probably all like this/
