### ISSUE TITLE
Settings (size, colour) of menu interaction, cannot be saved.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2486]
ACE3 Version: 3.3.1
Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
Modify the text size and colors of interaction menu, always and always return to the standard indicators (default size and default colours).

**Steps to reproduce:**
Try to modify the interaction menu with yourself(color and size) via ACE Settings in the left upper corner. First you will see that the changes came into force, but later(after small time), the interaction menu will return to its default size and colour.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by PabstMirror** [comment]
I can't reproduce, could you hit escape and hit the debug button and then post the rpt?

**Comment by mickeymen** [comment]
you can download my rpt from here. 
https://yadi.sk/d/I9JTN8OVjAACe 
hit button - "Скачать", I hope this help you and I provided the file, which is required
