### ISSUE TITLE
Trying to reload glitches all magazines in certain animations

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#249]
Empty magazine while dragging,
Try to reload - nothing happens and it eats a magazine for each keypress

https://www.youtube.com/watch?v=aDWnC-G-IiU

**Comment by PabstMirror** [comment]
Just tested on current dev branch and it seems to be fixed.
Maybe BIS actually respects the `canReload` config.
Probably related to this from a few days ago: 
`Fixed: Reloading while on a ladder consumes a magazine from inventory`

**Comment by commy2** [comment]
Finally. To bad it happened after resting is gone.

![http://rack.2.mshcdn.com/media/ZgkyMDEzLzA2LzEyLzhjL2NyYXp5a2lkYmlyLjU4MWQyLmdpZgpwCXRodW1iCTEyMDB4OTYwMD4/f215d81f/5ce/crazy-kid-birthday-gif.gif](http://rack.2.mshcdn.com/media/ZgkyMDEzLzA2LzEyLzhjL2NyYXp5a2lkYmlyLjU4MWQyLmdpZgpwCXRodW1iCTEyMDB4OTYwMD4/f215d81f/5ce/crazy-kid-birthday-gif.gif)
