### ISSUE TITLE
After update 3.3.1.game not see my old missions (editor)

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2493]
ACE3 Version: 3.3.1
Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
After update 3.3.1.game not see old missions (editor). Probably the path to the files has been changed. In version 3.3.0 never had that problem.

**Steps to reproduce:**
Try load old mission on the Altis or Stratis. The list of missions will is empty.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by commy2** [comment]
Path is
`C:\Users\<USER>\Documents\Arma 3 - Other Profiles\<PROFILE NAME>\missions`

ACE doesn't and can't even change that. Maybe you made your mission under a different profile?

**Comment by mickeymen** [comment]
"Maybe you made your mission under a different profile?" 

Yes,Yes,Yes!  I changed the profile, when the voice of the commander disappeared . 
I thought it might solve the problem! Now I understand. 
This issue can be closed! thanks
