### ISSUE TITLE
Lockpicking not working, Status Bar Does Not Progress.

### ISSUE THREAD

**Issue by salty6924** [acemod/ACE3#2495]
ACE3 Version: 3.1.1 Stable?
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* `@CBA_A3`
* `@ace`
* `@RHS`
* `@AIATP`
* `@STHUD`

**Placed ACE3 Modules:**
Medical, Medical Options, Vehicle Lock, Revive, Map, 

**Description:**
When attempting to Lockpick, this error is thrown, and the statusbar does not move.

**Steps to reproduce:**
Try To Lockpick

**Where did the issue occur?**
Server local and Dedicated, Editor.

**RPT log file:**
* Add a link (pastebin.com) to the client or server RPT file.*
http://pastebin.com/jrd2R3n6

**Comment by jokoho48** [comment]
please read and use this: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by salty6924** [comment]
Done.

**Comment by jokoho48** [comment]
thanks i found the issue fixed in next version

**Comment by salty6924** [comment]
Thank you! My Community Thank you!.
