### ISSUE TITLE
Ace Version 3.3.1 Error ace_protection.pbo

### ISSUE THREAD

**Issue by Luca41** [acemod/ACE3#2502]
Hi everybody. Since the Version 3.3.1 for the ACE mod came out my Arma doesn't work how it should. Whenever I try to join a friends server or go to the editor to do anything, Arma gives me the Error mentioned above ( ace_protection.pbo is outdated ). I tried reinstalling and installing an older Version of the mod. I asked friends of mine if they know this problem, but none of them even has the ace_protection.pbo file.

Need help

**Comment by Magirot** [comment]
ace_protection.pbo was removed in 3.3.x. You should remove the old addon folder before updating.

https://forums.bistudio.com/topic/181341-ace3-a-collaborative-merger-between-agm-cse-and-ace/?p=2914289

**Comment by Luca41** [comment]
I thats what I did more than once, but without the new version only arma crashes

**Comment by Magirot** [comment]
I guess you should double check everything (not sure if it could cause anything like that, but have you updated CBA as well?) and add the info (i.e. list of your mods, maybe upload an .rpt file from \Users\username\AppData\Local\Arma 3) the team normally wants for an issue to improve their chances of being able to  help you.
http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by Luca41** [comment]
I checked everything more than once including any of my mods. 
My mods are: 
Cba
RHS:Armed Forces of the Russian Federtion
RHS:United States Forces
allinarmaterrainpack
BWA3
BW_Gear
Task Force Arrowhead Radio
Blastcore A3 Phoenix
F/A-18 Super Hornet pack
GPNVG-18
hiddenidentitypack
L Supress
Leights OPFOR Pack
Uss nimitz
MightyGau
Blastcore: Tracers
Ryan's Zombies & Demons
F-16C Fighting Falcon
Blastcore: Skies
FIR Airweaponsystem
A3C-Arma Map Pack-Additional Pack
Esseker
asdg_jointmuzzels
RQ-11B Raven
ASR AI3
RH acc
and of course Advanced combat environment 3.3.1

**Comment by jokoho48** [comment]
try to reproduce the issue with using only @CBA_A3 and @ace on a newly created mission.

**Comment by Luca41** [comment]
I can't even start Arma right now

**Comment by Luca41** [comment]
I'll try

**Comment by Luca41** [comment]
Ok it works

**Comment by Luca41** [comment]
but not with my mods

**Comment by PabstMirror** [comment]
Add mods one at a time, until it fails.

Also please look at http://ace3mod.com/wiki/user/how-to-report-an-issue.html
Without an RPT there isn't much we can do.

**Comment by commy2** [comment]
@Luca41 
You closed this issue. Might I ask what the solution to your problem was? It could save others with the same or similar issues a lot of time. Thanks!
