### ISSUE TITLE
Сan't order the AI to set mine or to make treatment command(in the action menu no exist)

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2506]
ACE3 Version: 3.3.1
Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
I can't find a way to order the subordinate to set/blow up a mine(for explosive specialist) or to heal yourself or another soldier(for medic). These commands have been removed from the menu of list special action.  I haven't seen the AI independently set mines or treated yourself and I don't understand why this was done in this mod?
My friends, in th ACE-mod the medic and explosive specialist turn into a useless unit:
1) The player cannot order them to use their abilities. 
2) The AI can't use their abilities on their own, regardless of the human player.
Please fix at least one item.

**Steps to reproduce:**
Open your menu of list special action.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by mickeymen** [comment]
How I can order to my bots set mines or do threatment?

**Comment by commy2** [comment]
You can't.

**Comment by PabstMirror** [comment]
I'm guessing this from messing with CfgActions >> show?
If that is the case, I don't think there is much we can do.

You could just remove medical and explosives .pbos.

**Comment by commy2** [comment]
Also note that these CfgActions are removed, because they wouldn't work with our scripted aproaches to explsosives and medical.

**Comment by mickeymen** [comment]
"You can't." 
Oh my God! Dear developers ACE3, this is a bad detail. Thus, the Medic and Explosive specialist transformed into useless units i the game, because they are not able to self-treat or to lay mines. Then Why do they carry in their backpacks these useless things?

ACE3 - a great mod and this issue prevents your mod to be better. This is break gameplay. Please find a solution to this problem.

**Comment by PabstMirror** [comment]
There is a solution, ace is modular so you can remove the pbo's that have problems with AI commanding.

Goto @ace's addons folder and delete
```
ace_medical.pbo
ace_explosives.pbo
```

**Comment by mickeymen** [comment]
@PabstMirror, If I will remove it, then there can be no problems for the interaction menu with himself?
For example set mines and threatment actions for player?

In the future, The creators of mod will not be to add these commands at interaction menu?  
Or in the standard menu?

**Comment by mickeymen** [comment]
My friends, in th ACE-mod the medic and explosive specialist turn into a useless unit:
1) The player cannot order them to use their abilities. 
2) The AI can't use their abilities on their own, regardless of the human player.
Please fix at least one item.

**Comment by jokoho48** [comment]
that more sound like a by design

**Comment by mickeymen** [comment]
not design, rather, it looks like break gameplay

**Comment by bux578** [comment]
So to wrap this up: It's not game breaking if you play the game modes ACE3 is primarily developed for which is Coop and TvT. So for us it's not "game breaking". The rest might follow eventually.

**Comment by mickeymen** [comment]
@bux578, *Please  explain to me, why in ACE3 the medic and explosive specialist carry in their backpacks all of these devices and medicines?

**Comment by mickeymen** [comment]
The player may order an engineer to repair vehicles, but cannot order the medic to heal another soldier or set mine. Game command is broken. Commanding has always been an integral and unique part ARMA!  Isn't that the gameplay is broken? Or may be gameplay improved? 

I think ACE3 is good work, but this detail is ba and should be fixed.
If this mod is realistic, then NECESSARY to either teach the AI to use those action independently or give the player to use the order for these actions.

**Comment by PabstMirror** [comment]
@mickeymen delete the following pbos

* ace_explosives.pbo
* ace_medical.pbo
* ace_medical_menu.pbo

Explosives/Medical should work just like vanilla and this won't interfere with the rest of ACE's features.

Squad level AI commanding isn't something many of us use, and I don't even know if we can add things to the AI command menu.  Anyone is free to work on this and make a pull request but it really isn't a high priority for us.

Tag for feature request thread: #414

**Comment by mickeymen** [comment]
@PabstMirror I like the medical menu in ACE3 and I like the interaction menu with explosives and I wouldn't want to remove it! Unfortunately, the problem is that to work well, player should to uninstall one of the two things/ This is not normal :(

**Comment by MikeMatrix** [comment]
@mickeymen it's called task prioritization. We have to many actual things that needs fixing/implementing, which the majority of the target audience is using, that this is actually low priority. We just can do so much at a time.
I hope we can get this fixed eventually, but right now, I hope this is a solution for you.

**Comment by mickeymen** [comment]
Thanks for your attention my friends. Please understand, It was not my whim, simply because I want ACE was the best mod! Please fix this issue as soon as possible, not only for me. Fix this for all players, because this details adds to gameplay more depth and realism and at the same time will not break the unique features of ARMA game.

**Comment by commy2** [comment]
Related: #57

**Comment by mickeymen** [comment]
"it's called task prioritization. We have too many actual things that needs fixing/implementing, which the majority of the target audience is using, that this is actually low priority"
@MikeMatrix  First you smash these abilities and now it is low priority! Is this normal?
Please fix it as soon as possible! This detail breaks the unique ability Arma3

**Comment by mickeymen** [comment]
@PabstMirror For some reason, this bug is "feauture request" ?
It is 100% a bug who crippled the unique abilities of vanilla game . You suggested me delete some files, but then I can't use the medical system, which I really like.
