### ISSUE TITLE
playerInventoryChanged eventhandler triggers when current weapon is changed

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#2513]
getAllGear contains the current weapon as element 19

**Comment by commy2** [comment]
@bux578 
https://github.com/acemod/ACE3/commit/675cfc2da720d7097ad274a8cdbcc750d5ae983a

**Comment by bux578** [comment]
what does it have to do with the getallgear function?

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/blob/master/addons/common/XEH_postInit.sqf#L224-L230

**Comment by bux578** [comment]
meh

:+1: then, good catch

**Comment by commy2** [comment]
Here is the PR. Pls review and merge, Pls
https://github.com/acemod/ACE3/pull/2515
