### ISSUE TITLE
Spectator map view is very laggy with high no. of units

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2514]
ACE3 Version: 3.3.1

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* *Spectator*

**Description:**
* On mission when there was over 200 units on map switching to map view while spectating lowers FPS to very low values (around 3-9). It may be cause of drawing unit markers in real time (no delay?).*

**Steps to reproduce:**
* *Enter map view while spectating on mission with high amount of units.*

**Where did the issue occur?**
* "Multiplayer"*

**RPT log file:**
* -

**Comment by SilentSpike** [comment]
I think the only way to alleviate this is some sort of compromise. Maybe it will only draw AI units in vicinity of the camera and then all player units.

**Comment by gienkov** [comment]
Maybe just don't draw each icon per frame as PFH is used on each one. You have 100 spectatable units - 100 PFHs - frame's drop. You don't need such precision for spectator so updating map markers let's say every 1 second could be way better and that's how other spectator scripts I used were working.

**Comment by jokoho48** [comment]
or every frame one unit

**Comment by SilentSpike** [comment]
Dude what, I don't have 100PFHs running :laughing:

**Comment by gienkov** [comment]
Maybe draw each unit marker only if you zoom enough? Otherwise only whole group marker.

**Comment by SilentSpike** [comment]
That's not a bad idea! :smile: :+1:

**Comment by SilentSpike** [comment]
Wonder what the best way is to check which units are currently on-screen on the map

**Comment by commy2** [comment]
distance of the current center of map converted to world coordinates combined with current map zoom?

**Comment by PabstMirror** [comment]
Maybe something like this, untested. I forget if it's faster to check allUnits + vechicles or do a nearEntities scan.
```
_center = _mapCtrl ctrlMapScreenToWorld [0.5,0.5];
_radius = (_mapCtrl ctrlMapScreenToWorld [safeZoneX,safeZoneY]) distance2d _center;
{
    if ((_x distance 2d _center) > _radius) then {
    draw
    };
} forEach allUnits;
```

**Comment by commy2** [comment]
(allUnits + allDeadMen to include dead units)

**Comment by SilentSpike** [comment]
We can use the array of spectatable units (or the corresponding group one - used to cut down on number of iterations for icon related stuff) anyway :smile:

`GVAR(unitList)`
`GVAR(groupList)`
