### ISSUE TITLE
Setting menuTypeStyle to Disabled doesn't disable this menu for player

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2516]
ACE3 Version: 3.3.1

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* *Medical menu - ON.*
* *menuTypeStyle - DISABLED*

**Description:**
* If you set menuTypeStyle to Disabled and enable new medical menu, so you only want to have new medical menu, it will remove treatment points from other players interactions but you will still have both medical menus inside self interaction.*

**Steps to reproduce:**
* *Described above.*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer", "Editor"*

**RPT log file:**
* -

**Comment by Glowbal** [comment]
This is intended behaviour.
