### ISSUE TITLE
Treatment animations are break in the end

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2517]
ACE3 Version: 3.3.1
Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
I noticed that the animations of treatment (self-treatment and treatment ally) in ACE3 reduced, in the end, before completion. I understand, that an injection of medications should take less time(can be reduced), but now I mean the bandaging wounds in the ACE3, not injection. The bandaging animation is interrupted before it ends. Unfortunately, It looks not good and not realistic, because too fast and because visually breaks. Probably the animation time in ACE3 was reduced intentionally, but as seems to me, this no any sense, because even the vanilla game, this animation is too fast for reality. Ideally, I would even slowed down the animation treatment (more than vanilla), because the wounded man could not do actions quickly.
Please consider this a not big issue also, because ACE3 focuses on realism.

**Steps to reproduce:**
To watch attentively the animation of self-treatment and treatment ally.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed.

**Comment by PabstMirror** [comment]
I had an idea of possibly using `setAnimSpeedCoef` in 1.54 to better sync animation to the progressBar for all treatment animations.

But that's non-trivial, I don't even know how those command sync in MP.

**Comment by PabstMirror** [comment]
Tracking on #3449

**Comment by commy2** [comment]
marking as dup then
