### ISSUE TITLE
compatibility issue with ACE 3

### ISSUE THREAD

**Issue by Leviat1001** [acemod/ACE3#2518]
ACE3 Version: 3.3.1

**Mods:**
* `@CBA_A3`
* `@ace3`
* `@allinarmastandalone`
* `@cup`

**Description:**
* When we try to open either version 3.3.0 or 3.3.1 along with @allinarmastandalone the game freezes at the title screen, though both mods do work separately but not at the same time. We downgraded @ACE to 3.2.1 and it all works just fine. 

We are a Brazilian clan focused on MilSim and we depend on these two mods to play, not to mention countless missions that would be lost if the problem persists.

Thanks for your attention.

--Leviat

**Steps to reproduce:**
*start the mods together.*

**Where did the issue occur?**
*title screen *

**RPT log file:**
* http://pastebin.com/A0Yf2M7X

**Comment by commy2** [comment]
```
22:49:49 Updating base class RifleBaseStandActions->, by MOCAP_mov\config.bin/CfgMovesBasic/Actions/RifleProneActions/
22:49:49 Updating base class NoActions->, by MOCAP_mov\config.bin/CfgMovesBasic/Actions/PistolStandActions/
22:49:49 Updating base class NoActions->, by MOCAP_mov\config.bin/CfgMovesBasic/Actions/CivilStandActions/
```

Not our fault. MOCAP_mov wrecks the whole animation config inheritance. Try removing @mocap. Your reported list of addons does not match the RPT.

**Comment by Leviat1001** [comment]
i send RPT worng sory , i test Only AiA and ACE3 i will put here the right RPT in few seconds.

**Comment by Leviat1001** [comment]
That : http://pastebin.com/sbGfCa3Y is the working one with 3.2.1
That : http://pastebin.com/YrKiHTi4 is the one thats not working with 3.3.1
The mods i used are :

@ACE3 (3.2.1 and 3.3.1)
@Allinarmastandalone
@Allinarma
@Cup
@Cup_weapons
@Cup_units
@ASDG_JR
@ARP2
@CBA_A3

like in this image: 
http://imgur.com/bVfLFzZ

We try all mods with ACE3 3.3.1 and the only who dont work is AiA.
AiA only work with ACE3 3.2.1

**Comment by jokoho48** [comment]
not a ace issue mod's fault

**Comment by PabstMirror** [comment]
CBA 2 has ASDG built in, so you can remove that

**Comment by Leviat1001** [comment]
Jokoho48 so tell me why with 3.2.1 work and with 3.3.1 not ?

**Comment by commy2** [comment]
>Please note:
>
>It's not a valid to simply remove @ace from the mod list to confirm that ACE3 is the culprit.
>
>If the error happens when using a third-party mod contact the author of the appropriate mod and >report the issue there.

http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by commy2** [comment]
First of all you should try to figure out what combination of addons exactly crashes your game.
We simply don't have the time to debug the game for everyone.

**Comment by commy2** [comment]
@Leviat1001

Any news?

**Comment by commy2** [comment]
No more activity
