### ISSUE TITLE
Advanced medical system and backblast crash game

### ISSUE THREAD

**Issue by ndfmoab** [acemod/ACE3#2519]
ACE3 Version: 3.3.1 stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* *ACE_moduleMedicalSettings*

**Description:**
* With advanced medical system activated the game will crash whenever backblast from an AT-Launcher hits something.*
*Error reads: Microsoft Visual C++ Runtime Library. [...]arma3.exe. [...] This application has requestet to terminate it in an unusual way*

**Steps to reproduce:**
* *open editor.*
* *place an AT soldier as player.*
* *place the ace_medical module and set first option to "advanced"*.
* *click "Preview.*
* *Select launcher as weapon, make sure there's an obstacle in your backblast and FIRE!.*
* *Cry because you can't use that exceptional medic system until further notice.*

**Where did the issue occur?**
* all*

**RPT log file:**
* http://pastebin.com/p4HN4Qvb*

**Comment by jokoho48** [comment]
is know fixed in next version

**Comment by commy2** [comment]
Link to commit?

**Comment by ndfmoab** [comment]
When will that be? Currently we just deleted ace_overpressure.pbo but that can't be a solution for long.

**Comment by Glowbal** [comment]
I am currently working on a proper fix for this.

Meanwhile, the work around is removing the `ace_medical.dll` until we release a fix. This means you will not have the performance improvements in medical, meaning slightly less frames upon taking damage. It will however no longer crash.

Also you will be receiving a bunch of script errors upon overpressure.

**Comment by Glowbal** [comment]
#2521
