### ISSUE TITLE
Can't handcuff unconcious different side units

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#2524]
ACE3 Version: 3.3.1 stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* Respawn

**Description:**
* You can only handcuff units that have surrendered
![2015-09-19_00002](https://cloud.githubusercontent.com/assets/1235520/9976336/55e1cf22-5ee1-11e5-9bf6-0dc8e0b1990b.jpg)
![2015-09-19_00003](https://cloud.githubusercontent.com/assets/1235520/9976341/7c818960-5ee1-11e5-8bf7-ae7b18d6da30.jpg)

**Steps to reproduce:**
* Place a CSAT
* Use "Toggle unconcious" Zeus function
* Try to handcuff him

**Where did the issue occur?**
* "Editor"

**RPT log file:**
not necessary

**Comment by commy2** [comment]
By design? I guess this would be a good feature though.

**Comment by commy2** [comment]
@PabstMirror How does it work out with animations?

**Comment by PabstMirror** [comment]
doAnimation should always respect unconc

otherwise we do checking in captives to not overwrite animations.
