### ISSUE TITLE
Wrong Interactions points for vehicles available under water

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#2525]
ACE3 Version: 3.3.1 stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* Respawn

**Description:**
* There are only the "Remove Wheel" interaction points but not the main interaction point available under water. So divers can't unload items from a submerged vehicle (which should be possible imho).
Using the "Remove Wheel" interaction doesn't do anything though. So either this fix this (does that make sense under water?) or remove the interaction points.

**Steps to reproduce:**
* As a diver drive a truck over the pier in e.g. Stratis
* Get out of the vehicle and try to interact with it or with the wheels
![2015-09-19_00004](https://cloud.githubusercontent.com/assets/1235520/9976384/bd5056fa-5ee2-11e5-9463-2929168a1de1.jpg)

**Where did the issue occur?**
* "Editor"

**RPT log file:**
not necessary

**Comment by Xerrass** [comment]
i think it woud be cool if you can get stuff out of underwater Wrecks and/or Vehicles will be a cool mission Addition to get stuf out of a crashed Plane or Boat.
