### ISSUE TITLE
When I try to set a mines/charges, the interaction menu, working not always. 

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2537]
ACE3 Version: 3.3.1

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyreSP

**Placed ACE3 Modules:**
None

**Description:**
When I try to set a mines/charges, the interaction menu,  working not always. 
First, I deploy the first mine and then, I want to install a second mine, but the player action does not happen. Sometimes I can't even set first mine without problem. I should to make several attempts, again and again, before mine will appear in the "player's hand" (i.e. in front of the player) 
Thus, the deploying mines via the interaction menu, does not work always, when the player wants it.

**Steps to reproduce:**

I noticed, this problem happens if the settings menu "DO ACTION WHEN RELEASING MENU KEY" is set - "YES". But, if set to "NO", then the problem almost never happens.
Try for reproduce this problem set "YES"

1. Deploy the player in the map as esplosive specialist. 
2. Try several times deploy several mines in the one place of the map (one after one, again and again)

**Where did the issue occur?**
Editor

**RPT log file:**
can be downloaded from here:
https://yadi.sk/d/MenNYgFpjCmYR
click the "Скачать"button

**Comment by commy2** [comment]
We need a RPT file for this one.

**Comment by mickeymen** [comment]
try download my rpt, link added

**Comment by mickeymen** [comment]
It is impossible to set mine without any problems! I try сlick on install, but nothing happens. Sometimes it takes several attempts before Mine will appear in the "player's hand". (i.e. in front of the player). So the menu does not work consistently. If the menu does not work, then I can see a slight darkening at the edges of the screen

**Comment by mickeymen** [comment]
I notised, this problem happens if the settings menu "DO ACTION WHEN RELEASING MENU KEY"  is set - "YES". But,  if set to "NO", then the problem almost never happens

**Comment by PabstMirror** [comment]
I believe this is the same core problem as #1965

I can't really reproduce it, but I believe the same solution should fix.
