### ISSUE TITLE
Overlapping IM entrys in vehicle

### ISSUE THREAD

**Issue by 0dr** [acemod/ACE3#2538]
ACE3 Version: 3.3.1 and 3.2.1

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
- ACE_moduleAdvancedMedicalSettings
- ACE_moduleMedicalSettings

**Description:**
- When many players / units are in one vehicle the IM entry's starting to overlap making it hard to find the right one
- similar things happen when advanced medical is active and you try to heal

**Steps to reproduce:**
- fill vehicle with AI/player  (> 10 Units)
- Open interaction menu -> passengers

**Where did the issue occur?**
- "Multiplayer", "Editor"

**RPT log file:**

![2015-09-20_00002](https://cloud.githubusercontent.com/assets/295577/9980512/eb0d68c0-5f9c-11e5-856a-0bd63dfceaa6.jpg)
![2015-09-20_00004](https://cloud.githubusercontent.com/assets/295577/9980513/ec98f1e6-5f9c-11e5-9b08-ff10252d131a.jpg)

**Comment by Glowbal** [comment]
For advanced medical, I'd advise to try the medical menu. It's a client setting that you have to enable.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
