### ISSUE TITLE
High zoom optics broken on all LMGs 

### ISSUE THREAD

**Issue by captainblaffer** [acemod/ACE3#2540]
ACE3 Version: 3.3.1 and 3.2.1

Mods:

    @CBA_A3
    @ace

Placed ACE3 Modules:
none

Description:

Most high zoom optics can not be used on any LMGs.
List:
- LMG_Zafir_F
- LMG_Mk200_F
- MMG_02_sand_F

When attempting to equip the scope in VA or via script, it won't appear.
Broken Scopes include:
- AMS
- DMS
- Kahila
- LRPS 
- MOS

Steps to reproduce:

Start Virtual Arsenal
Equip any lmg from list above 
Equip any of the optics above

Where did the issue occur?

    "Multiplayer", "Editor"

RPT log file:
n/a

**Comment by captainblaffer** [comment]
I've tested some more. If I completely disable ACE, and only load CBA_A3 the issue still occurs.
Issue caused by my CBA_A3??

**Comment by PabstMirror** [comment]
probably from CBA adding ASDG Joint Rails

https://github.com/CBATeam/CBA_A3

**Comment by PabstMirror** [comment]
also this might be by desgin, I'm not sure

**Comment by captainblaffer** [comment]
How can it be by design? It completely breaks existing missions. :/

**Comment by captainblaffer** [comment]
https://github.com/CBATeam/CBA_A3/issues/159

**Comment by commy2** [comment]
Not caused by ACE.
