### ISSUE TITLE
ACE3 3.2.1. and 3.3.1.

### ISSUE THREAD

**Issue by Wobbinwood** [acemod/ACE3#2553]
Doesn't work. The game doesn't even load when ACE3 is enabled. It keeps looking for files which isn't there. During launch of the game I get 2 error messages;
The first message is: "Addon 'cba_xeh_a3' requires addon CAData" (excluding the "")
The secind message: " Bad version 68 in p3d file 'z\ace\addons\attach\data\ace_irstrobe.p3d' " 
Since no such file exists, I have no idea what it is looking for.
Furthermore, the ONLY way to DISABLE ACE3 is to physically delete the ace3-folder and it's userconfig file from my hard drive and restart the game.

Apart from that, this is the buggiest and most unstable game I have played since the early 90's

**Comment by bux578** [comment]
I don't have any problems with it whatsoever.

**Comment by bux578** [comment]
Please make sure you're on the latest version. Use "Verify integrity of game cache" in steam. And follow the installation guidelines here: http://ace3mod.com/wiki/user/installation-guide.html

**Comment by PabstMirror** [comment]
We really need an RPT (it's in `C:\Users\your_name\AppData\Local\Arma 3`)

Please make sure you're running just the most recent versions of both CBA and ACE.

https://github.com/CBATeam/CBA_A3/releases/latest
https://github.com/acemod/ACE3/releases/latest

`Bad version 68` - are you running an older version of arma?

**Comment by Wobbinwood** [comment]
All done exactly as prescribed. Have ACE3 version 3.3.1. by Vipermaul and
CBA _A3 v2.0.0.150817 by the same author
 I also have the exact same issue with the CUP Weapons mod (accessed via
virtual ammobox)

And I do not use Steam

**Comment by MikeMatrix** [comment]
> And I do not use Steam

I don't think you'll get much support, running an unofficial version...
