### ISSUE TITLE
Spotting scope:Can get in when not level (animation looks weird)

### ISSUE THREAD

**Issue by PAPA-DOC** [acemod/ACE3#2554]
ACE3 Version: 3.3.1 stable

Mods: @CBA_A3 / @ACE3

Placed ACE3 Modules: None

Description: Spoter can settling when spotting-scope wasn't on his feet.

Steps to reproduce: Place spotting scope on a slopes, if he falls when you place it and if you keep scroll with mouse wheel, you can settling before the message for put spotting scope on his feet. 

RPT log file: None

![pops41](https://cloud.githubusercontent.com/assets/14343856/9999023/71f98a38-6094-11e5-90af-58be86872e45.jpg)

![pops4](https://cloud.githubusercontent.com/assets/14343856/9998440/5f459718-6091-11e5-8bbd-5c583b491665.jpg)

**Comment by alganthe** [comment]
o.... oh god

**Comment by bux578** [comment]
> even BI static items suffer from the same issue.

Aren't you auto ejected from those?

**Comment by MikeMatrix** [comment]
That's kind of the solution I was wondering if that's possible/already in game

**Comment by jonpas** [comment]
It's possible to do with a PFH for sure, I did it in sitting. But a vanilla solution would be the best of course.

**Comment by commy2** [comment]
This happens to every other static weapon looking equally stupid. Close?

**Comment by p1nga** [comment]
We need a ACE MOCAP team....
