### ISSUE TITLE
Missing module descriptions etc.

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2561]
This is a list of modules that may be missing some options description. Inside modules there is entry name (all are here), entry description on-hover (not all are here), module description when you click on Description button and last one is 2D representation on how module should be set on map (synchronize X to Y and X to Z).
It's not a big issue but as you see below module classnames are written with different capitalization, maybe something worth streamlining too?

After quick look I see that **most** module names uses this strategy for naming:
``ACE_moduleNameCanBeLong``
Below there is a list of modules that are not using this form:

* ACE_ModuleBlueForceTracking
* ACE_ModuleMap
* ace_mk6mortar_module
* ace_viewdistance_ModuleSettings
* ace_slideshow_module
* ace_weather_ModuleSettings
* ACE_ModuleLSDVehicles
* ACE_VehicleLock_ModuleSyncedAssign
* ACE_ModuleHearing
* ACE_ModuleSitting
* ace_captives_ModuleSurrender
* ACE_ModuleCheckPBOs
* ACE_ModuleExplosive
* ACE_ModuleInteraction
* ACE_ModuleRespawn
* ACE_ModuleRallypoint
* ACE_ModuleSwitchUnits
* ACE_ModuleNameTags
* ace_spectator_moduleSettings
* ace_captives_moduleSettings
* ace_finger_moduleSettings
* ace_zeus_moduleSettings
* ACE_VehicleLock_ModuleSetup
* ACE_ModuleFriendlyFire
* ace_winddeflection_ModuleSettings
* ace_microdagr_dagrModule
* ace_advanced_ballistics_ModuleSettings

Most of those require to change `M` to `m` and `ace` to `ACE`. Some names propably cannot be touched right now as changing name phrase itself could break many missions, but capitalization can be done no problem, I think, I hope. For future modules I suggest using one form for naming them.

Also some module description contains this (note Source):
```<English>Controls how much data is filled on the microDAGR items.  Less data restricts the map view to show less on the minimap.&lt;br /&gt;Source: microDAGR.pbo</English>```
It shows source of given module, maybe worth adding this to all modules?

* ACE_ModuleHearing
	* Missing on-hover description for "Disable ear ringing sound"

* ACE_ModuleSitting
	* Missing on-hover description for "Enable sitting"
	
* ace_finger_moduleSettings
	* Missing on-hover description for "Enable sitting"
	
* ACE_moduleAssignRepairFacility
	* There are no missing descriptions but this module uses list for buildings that can repair vehicles, it's about range from that building of course. There is very similiar medical module for medical buildings setup, but it uses synchronization. Maybe worth changing this or that module to be more streamlined ie. use one way for this, list or synchronization?

* ACE_moduleAssignMedicalFacility
       * Missing 2D description setup - this http://i.imgur.com/h9oGUs1.jpg

I will try to do PR that address above.
Thank you

**Comment by bux578** [comment]
Maybe once we bump ACE3 to v4.x.x we could change the module names. But yeah, I'd like to see some consistency here too :)

:+1: for the list

**Comment by MikeMatrix** [comment]
@bux578 wouldn't that be Arma 4? O_O

**Comment by PabstMirror** [comment]
If we change module names it will break old missions.
Personally I like the GVAR(moduleX) format but anything is fine.

**Comment by SilentSpike** [comment]
>Personally I like the GVAR(moduleX) format

:+1:

**Comment by Glowbal** [comment]
> wouldn't that be Arma 4? O_O

Doesn't have to be.

**Comment by MikeMatrix** [comment]
> Doesn't have to be.

[This](http://ace3mod.com/wiki/development/branching-and-release.html#1-versioning) makes it sound like it though.

**Comment by jonpas** [comment]
> Most of those require to change M to m and ace to ACE.

Module names are different, some just use prefix, some use `GVAR` macro, if we decide we will do that in a batch but we somehow have to keep backwards compatibility for a few versions at least, which would mean having 2 copies of the module (inherited) with one hidden. Not a priority. Opening another issue to keep track of only that.

> It shows source of given module, maybe worth adding this to all modules?

I don't think so, that should be documented on the pages as it has no direct meaning for the mission maker. Only captives, microDAGR and vehiclelock had it, removed in #3408. But I have no idea where this is shown Eden.

> ACE_ModuleHearing - Missing on-hover description for "Disable ear ringing sound"

Fixed in #3279 

> ACE_moduleAssignRepairFacility- There are no missing descriptions but this module uses list for buildings that can repair vehicles, it's about range from that building of course. There is very similiar medical module for medical buildings setup, but it uses synchronization. Maybe worth changing this or that module to be more streamlined ie. use one way for this, list or synchronization?

Should work since 3.4.0, fixed in #2257 

> ACE_moduleAssignMedicalFacility - Missing 2D description setup - this http://i.imgur.com/h9oGUs1.jpg

Again, no idea where this is shown in Eden.
