### ISSUE TITLE
stitching a player throws generic error

### ISSUE THREAD

**Issue by i-robat** [acemod/ACE3#2566]
ACE3 Version: 3.3.1.2 dev from 21.09.15 evening

**Mods:**
`@CBA_A3`
`@ace`

**Placed ACE3 Modules:**
AB; BFT; CaptiveSettings; CheckPbos; ExplosiveSystem; Hearing; InteractionSystem; Map; MicroDagrMapFill; MK6; NameTags; PointingSettings; Sitting; Weather; WindDeflection; ZeusSettings; RepairSettings; CargoSettings; MedicalSettings; AdvancedMS; ReviveSettings; MedicalMenuSettings;

could not try with only MedicalSettings, cause of Serverside config.

Settings:
http://pastebin.com/073cGLpK

**Description:**
When you stitch a player in MP you get a generic error in fnc_treatment_success on line 64 / line 79.
http://pastebin.com/5UvQrgiX

**Steps to reproduce:**
shoot somebody, bandage the wound and stitch it - the wound seems to be stitched but throws the error...

**Where did the issue occur?**
Multiplayer, SP with AI i couldn't reproduce (Module settings then enabled for Players & AI  of course )

**Comment by bux578** [comment]
Full RPT, please.

**Comment by i-robat** [comment]
at the Moment i can give you the screen from yesterday: 
http://imgur.com/o7tv0Gz
rpt i will give you asap.

**Comment by i-robat** [comment]
Arrgh. i cannot reproduce it anymore in MP. Seems everything fine.  ArmA... ^^.
I think you can close this issue.
