### ISSUE TITLE
Handcuff option gone in 3.3.1.2

### ISSUE THREAD

**Issue by Magirot** [acemod/ACE3#2570]
ACE3 Version: 3.3.1.2

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
Tried with both no modules, and with the Captive Settings module.

**Description:**
Handcuff option doesn't appear on hands or anywhere else that I can see.
Screenshots showing the situation: http://imgur.com/a/TZTYE

**Steps to reproduce:**
1. Add ACE_CableTie to an unit
2. Try to handcuff someone

**Where did the issue occur?**
Editor and multiplayer.

**Comment by bux578** [comment]
You can't handcuff friendly units without them having surrendered.
Related: https://github.com/acemod/ACE3/issues/2524

**Comment by PabstMirror** [comment]
Try chaning the module setting to not require surrendering:
![image](https://cloud.githubusercontent.com/assets/9376747/10020224/5bf25ed6-6107-11e5-9b35-e4e3dcb4074d.png)

**Comment by Magirot** [comment]
Ahhh I am blind. Sorry about that. Posted the info to the thread.
