### ISSUE TITLE
units from addon (CUP) take to many bullets

### ISSUE THREAD

**Issue by T-800a** [acemod/ACE3#2573]
ACE3: 3.3.1
ARMA3: 1.50 stable

**Mods:**
@CBA_A3 (2.0.0.150817)
@ACE (3.3.1)
@CUP_weapons (1.2)
@CUP_units (1.0)

**Placed ACE3 Modules:**
- Medical Settings (basic settings)
- Revive Settings (basic settings)

**Placed A3 Modules:**
- Zeus: Gamemaster

**Description:**
CUP units take to much bullets (10++) to the torso untill they go unconcious or die. The lower the caliber the worse. Shooting to the head with assault rifles most of the times kills them, smaller calibers react worse. It's not dependent on the weapons you use (vanilla or CUP), only dependent on the units.

for testing I reverted back to ACE 3.2.1, which works fine!

**Steps to reproduce:**
Place some units from Zeus / in the editor and shoot them. I tested with various opfor and blufor rifleman, vanilla and CUP.

**Where did the issue occur?**
SP(editor) / MP

**Comment by SilentSpike** [comment]
Mod's fault?

**Comment by jokoho48** [comment]
yeah think so

**Comment by bux578** [comment]
Did you install the Armor Mod?

**Comment by T-800a** [comment]
not using the Real Armor, not even installed somewhere.
if its the mods fault what has changed from ace 3.2.1 to 3.3.1 to make it the mods fault and how could one fix it?

**Comment by bux578** [comment]
It's the RHS update. They are not compatible with vanilla units anymore. So you HAVE to install the Real Armor Mod to be compatible.

**Comment by Glowbal** [comment]
This sounds like it's an issue with the hitpoint configuration from the CUP units.

**Comment by bux578** [comment]
oh... CUP ... sorry. I was reading RHS somehow

**Comment by Glowbal** [comment]
I just tried to reproduce with the mods listed but was unable to.

Could you please provide RPT log files?

**Comment by T-800a** [comment]
http://hummelhummel-ag.de/misc/arma3_2015-09-22_19-10-45.rpt
http://hummelhummel-ag.de/misc/arma3_2015-09-21_23-29-05.rpt

**Comment by T-800a** [comment]
ok, sorry, mixed sth. up here are RPT files
http://hummelhummel-ag.de/misc/arma3_2015-09-21_22-37-43.rpt
http://hummelhummel-ag.de/misc/arma3_2015-09-22_18-44-07.rpt
http://hummelhummel-ag.de/misc/arma3_2015-09-22_19-10-45.rpt

**Comment by ViperMaul** [comment]
@T-800a 
Can you give us a simple repo mission?

**Comment by T-800a** [comment]
Repomission:
hummelhummel-ag.de/misc/ace-cup-issue.Stratis.7z

Video of the issue using the mission above:
https://youtu.be/xu4KfBWBst8

RPT from the "video session":
http://hummelhummel-ag.de/misc/arma3_2015-09-22_21-39-28.rpt

**Comment by Kilo1-1** [comment]
I have noticed this too.  I have also noticed with basic medical and revive settings that the units included in Isla Duala are also affected but RHS and normal BI infantry are not affected.  To counter this, we have set our AI damage threshold to 0.02 so you can actually kill these units instead of dumping a mag or two into one guy to kill him.

I will do some more testing and report back.

**Comment by Neodyn** [comment]
@Kilo1-1 : I agree, we hat the same issue on isla duala. Wa are also using basic medical and revive settings.

**Comment by Glowbal** [comment]
Does this also happen when the units are not wearing their vests?

**Comment by T-800a** [comment]
yes, removing the vests doen't help

**Comment by commy2** [comment]
^ There we go. Nothing we can do it seems.

**Comment by T-800a** [comment]
But why is this then not an issue in 3.2.1?
There the unity take like a hit or two more to the chest then vanilla units but they die ... but in 3.3.1 they are bullet tanks?

**Comment by commy2** [comment]
Because BI changed armor values in v1.50 without saying anything and we had to adjust.

**Comment by Glowbal** [comment]
This is something CUP (and any potential other mods with the same issues) will have to adjust. 

We adjust our values to be compatible with vanilla. Those mods most likely have the hitpoint configuration from pre Arma3 v1.50.

**Comment by ChairborneIT** [comment]
sorry for digging this up but is this still relevant?
what changes did you make to adjust to new BI params?
is this still a problem considering the hitpoint changes since 1.52?

**Comment by Glowbal** [comment]
I have not looked at the latest CUP version so I don't know if it is still relevant. But if CUP uses the same hitpoint configuration structure / inheritance as vanilla units, it should all be ok.

Feel free to join us on Slack (http://slackin.ace3mod.com) if you need more info or help with anything.
