### ISSUE TITLE
40mm UGLs don't create frags

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#2583]

**Comment by bux578** [comment]
https://github.com/acemod/ACE3/issues/342

**Comment by bux578** [comment]
Status @commy2 ?

**Comment by esteldunedain** [comment]
I've taken a look. It's not a bug in the strict sense of the work; the 40mm UGL explosion parameters as defined in vanilla arma are not strong enough for the frag module to kick in.

We might want to change those parameters later. I'm pushing this back.

**Comment by bux578** [comment]
IRL they produce a shitload! of frag.
