### ISSUE TITLE
Request ability to move while switching primary and secondary weapons

### ISSUE THREAD

**Issue by KRDucky** [acemod/ACE3#2586]
It would be nice to have the ability to swap between primary and secondary weapons while moving. Of course this would not include an LMG or Rocket launcher but for the rest of the primary/secondary weapons. It would allow for a more fluid movement.

**Comment by jokoho48** [comment]
please read this: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
and use #414

**Comment by KRDucky** [comment]
I did. I mistakenly hit New issue while looking at #414 thinking it would add to #414. when I saw that was not the case, I closed the issue and posted at the bottom of #414

**Comment by jokoho48** [comment]
i only attachted it for other users so we can handle this a little bit better
