### ISSUE TITLE
Feature Request: Leaders able to check inventory on fireteam members (with illustration)

### ISSUE THREAD

**Issue by ferox113** [acemod/ACE3#2587]
So this went on armaholic the other day: http://www.armaholic.com/page.php?id=28333 ("Tab My Squad", by TECAK).

It is basically enabling the members of a squad/fire team to see the other members' inventory (and not just opening the ruck). However, it is simply unrealistic on many accounts; as one would have to take the time to open the rucksack, the vest and uniform pouches, in order to check for magazines, special equipment, etc.
In the addon listed, one is able to see a list with everyone in their squad/team by hitting one button, including icons for the equipment that they have in their inventory. This can be done even though they are no way near the individuals they are inspecting; which is wrong. The icon-menu is also more confusing than informative, in my opinion; and could be simplified by allowing access to looking through ones basic inventory menu.

As realism units using ACE3 tends to miss this feature of leaders (leaders of the grouped individuals) being able to "check" their subordinates -making sure they are not carrying anything they are not allowed to be carrying - or - that they are carrying what is vital for the mission, in terms of special equipment, I am hereby requesting this feature to be added.

- In ACE2, this was enabled, as one would be able to inspect the other individual's inventory, by the action menu.
This option would only display, if one was about <1 or 2 meters from the other person.
If going through this menu (and with the approval by the individual inspected) an inventory-menu would appear in front of the leader (the one requesting to see the inspected individual); similar to his/her own inventory, but simply with the other individual's name and his/her setup.

- In ACE3 I could imagine that this option would be available for everyone through the interaction menu, with an icon of a uniform, a vest/plate-carrier & a rucksack next to each other, with text referring to "Inspect Inventory" (see reference images below).
This could be done in two ways:

1: Each section open separate, once selected (vest in the inventory-menu, when choosing to inspect the vest, uniform, when choosing to inspect the uniform etc.):

![inspectinventoryseperate](https://cloud.githubusercontent.com/assets/8312490/10072722/16553718-62c4-11e5-8f77-aa79e8260eff.png)

2: All of the inventory open up with the basic overview of the whole equipment-layout of the inspected person:

![inspectinventory](https://cloud.githubusercontent.com/assets/8312490/10072723/1657e562-62c4-11e5-8bed-f97a9619135d.png)

Once this had been selected by the inspector, a request would be sent as a prompt to the "inspected" individual, where he/she would be able to accept or decline this option within 5 seconds -just like in ACE2.
If declined/not accepted within those 5 seconds, there would simply not appear any inventory menu, and the inspector could get a hint, stating "Inspection Declined" or similar:

![inspectrequest](https://cloud.githubusercontent.com/assets/8312490/10072721/164e5fb0-62c4-11e5-8153-c350acef139c.png)

![inspectapproved](https://cloud.githubusercontent.com/assets/8312490/10072720/164d85e0-62c4-11e5-8d67-e80f6dec5558.png)

I hope the illustrations painted the picture for you, and that you will consider this addition to an otherwise awesome mod! If you have any questions for this idea, I would be happy to elaborate on the subject.

Thanks.

**Comment by jokoho48** [comment]
please read this: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
and use #414
nice idea but wrong position
