### ISSUE TITLE
unable to edit ACE keybindings

### ISSUE THREAD

**Issue by Cpl-snafu** [acemod/ACE3#2588]
ACE3 Version: 3.3.2 stable (also version 3.3.1 stable)

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* none

**Description:**
Upon trying to edit a ACE keybinding the specific entry in the key binding menu disappears.
For a split second it shows the green text that probably tells me I can edit the binding, yet after that the entire entry disappears from the menu and can not be retrieved by reopening the menu or relaunchin the game.
I have noticed that sometimes it doesn't delete the entry but lists the bound key as "unknown code 327788" 

**Steps to reproduce:**
1. Go to the controls editing screen
2. click on configure addons
3. double click on a control to "edit"
4. issue

**Where did the issue occur?**
* any, tested in menu and singleplayer*

**RPT log file:**
http://pastebin.com/fhPJTw07

**Comment by PabstMirror** [comment]
Do you run with a controller, I believe it may be related to CBA issue https://github.com/CBATeam/CBA_A3/issues/113

If so a possible workaround may be to remove controller to bind keys.

**Comment by jokoho48** [comment]
also fixed in newest CBA Master Repo
