### ISSUE TITLE
If the player character loses hearing, it does not impact on radio talks.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2589]
ACE3 Version: 3.3.2
Stable version

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
None

**Description:**
When a player loses the hearing (the grenade explosion or the firing of the Heavy MachineGun or Launcher etc), the all the ambient and battle sounds practically disappear. However, this effect does not affect the radio talks! The player can still hear the talks as heard of before. It looks absurdly, please fix it. 
In the event of hearing loss the player, the all voices(including the voice of the player) of all negotiations, should sound like also muted as other sounds.

**Steps to reproduce:**
1) Shoot from a grenade launcher without using earplugs in combat with the enemy
2) Listen to the talks of their subordinates

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by PabstMirror** [comment]
We do 
```
_soundTransitionTime fadeSound _volume;
_soundTransitionTime fadeSpeech _volume;
```

There also is a `fadeRadio` command that should probably do what we want.

**Comment by mickeymen** [comment]
Sorry I have not understood you. I can independently solve this issue? How and where? 
Please explain

**Comment by PabstMirror** [comment]
Sorry, I'm just leaving notes for myself.

**Comment by PabstMirror** [comment]
`fadeRadio` had no effect on VON in my testing

Biki says:
>Does not affect VON - beta 17:17, 11 September 2008

Don't know how to fix without a working command.

**Comment by PabstMirror** [comment]
Command hasn't worked for 7 years, you can try making an post on BIS feedback tracker, but I wouldn't get your hopes up.

Nothing we can do.
I highly recommend looking to a real radio mod (ACRE/TFR)

**Comment by mickeymen** [comment]
Sad to me( Unfortunately realism in ACE3 does not work
