### ISSUE TITLE
Ability to put additional rifles on back

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#259]
Just thinking about stuff

With `addWeaponItem` it's now possible to restore a complete weapon set (attachments, mags with ammo) via scripting commands even with full inventory.
Issues:
- Mass / weight will be lost. The displayed weight could be adjusted, but the disappearing mass will still be noticable by the bar in the inventory and decreased fatigure. A future stamina system could take that into account though.
- We have to find a attachTo position, but also somehow prevent others from accessing the ground weapon holder.
- The attached rifle will not have the correct attachments due to no scriptng commands being able to adjust those properties inside cargo.

Especially the last point does make it not worthwhile to try anything, imo.
http://feedback.arma3.com/view.php?id=22000

**Comment by WastedMike** [comment]
This would be an awesome feature to add to ACE3, maybe they could edit the launcher slot so it could be used to hold a AT launcher or any primary weapon. Keep in mind that this feature was included with ACE2 for Arma 2 so it is highly possible the team will add it to ACE3 as well.

**Comment by commy2** [comment]
>maybe they could edit the launcher slot

It's not that simple. These slots are hard-coded and neither changes to configs nor SQF commands can change that. The behavior of these things is determined in the .exe itself, so only BI could make changes like that.

>Keep in mind that this feature was included with ACE2 for Arma 2 so it is highly possible the team will add it to ACE3 as well.

But it was rather easy to do in Arma 2. Now in A3 stuff is way more complicated due to the inventory system. There are some very important scripting commands still missing from the game to implement this feature.

**Comment by WastedMike** [comment]
Well hopefully BIS will add in the needed commands to add this feature. I always wonder why this feature is not put into the game by default since the launcher and pistol sots have areas to add bipods, attachments, and silencers even thou they don't use them.

https://www.youtube.com/watch?v=RFXxVshMOF4

**Comment by jaynus** [comment]
I hated this in 2 - dual TAC-50s all day.

**Comment by Th3Cr0w** [comment]
So whats the state of this, which commands are missing and are there any threads we can push to get things done?

**Comment by commy2** [comment]
`addWeaponItem` is added now, but still buged for launchers.

To get this to work without looking extremly stupid (especially when prone), we'd need the alternative syntax of `attachTo` from VBS:
https://resources.bisimulations.com/wiki/attachTo
(bone parameter)

**Comment by PabstMirror** [comment]
Closed by #3903 (gunbag)
