### ISSUE TITLE
Spectator still running while session is lost

### ISSUE THREAD

**Issue by Cuel** [acemod/ACE3#2592]
ACE3 Version: 3.3.2
stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Description:**
https://d.maxfile.ro/icrboxhrwk.webm

**Steps to reproduce:**
1) Join dedicated server
2) Go into spectator
3) Force-end the server

**Where did the issue occur?**
MP

**Comment by PabstMirror** [comment]
I've noticed something similar with nametags, I think draw/PFEH can continue to run after mission ended.

I should look into 

`addMissionEventHandler ["Ended",{ }];`

**Comment by commy2** [comment]
`addMissionEventHandler ["Ended", {removeAllMissionEventHandlers "Loaded"}];`

Does that mean that _Mission_ eventhandlers run after the mission has ended?

**Comment by SilentSpike** [comment]
This is interesting because the dialog's "unload" event should kill the EH

https://github.com/acemod/ACE3/blob/43cdfaecc0f59ba5bb056226a5ef9440b712cf19/addons/spectator/functions/fnc_handleInterface.sqf#L115

I suppose maybe because the mission has ended that command fails or something

**Comment by SilentSpike** [comment]
Oh wait, the actual camera and everything is still running...huh, that's a new one. I knew about the icon rendering stuff.

**Comment by SilentSpike** [comment]
Assuming it works, this could theoretically be solved with:

`addMissionEventHandler ["Ended",{ [false] call FUNC(setSpectator) }];`

**Comment by SilentSpike** [comment]
Can anyone test whether the spectatorUpdates branch fixes this? :smile:

**Comment by SilentSpike** [comment]
My unit are currently re-hosting my spectator updates and it didn't seem to persist on mission end during last weeks session.

If anyone else can also test then that'd be great, but I'll consider it a success for the time being.
