### ISSUE TITLE
Sandbags look bright white?

### ISSUE THREAD

**Issue by JonenKone** [acemod/ACE3#2595]
Sandbags are an awesome addon. 

However, they seem to be bright white thus rendering them useless if used in terrain. Maybe change/add option of color to brown, dark grey or green? 

Modern sandbags are usually of a darker tint.

**Comment by bux578** [comment]
![2016-02-20_00002](https://cloud.githubusercontent.com/assets/1235520/13196043/76c3175e-d7c3-11e5-8bc2-ba179e784a51.jpg)
![2016-02-20_00001](https://cloud.githubusercontent.com/assets/1235520/13196044/76c69b68-d7c3-11e5-97ac-1ef310de32f2.jpg)

Confirmed. It's not thaaaat bad though.

**Comment by bux578** [comment]
![2016-02-20_00003](https://cloud.githubusercontent.com/assets/1235520/13196214/6516f822-d7c8-11e5-8a6c-b18f4e91e01f.jpg)

Some improvement

**Comment by bux578** [comment]
![2016-02-20_00004](https://cloud.githubusercontent.com/assets/1235520/13196286/493e420c-d7ca-11e5-9a2e-f63f66641b31.jpg)
![2016-02-20_00005](https://cloud.githubusercontent.com/assets/1235520/13196287/493fb510-d7ca-11e5-8f97-a352f2e20f5d.jpg)


more improvements
