### ISSUE TITLE
Remove nametags and actions on hidden units

### ISSUE THREAD

**Issue by m1ndst0rm** [acemod/ACE3#2596]
ACE3 Version: 3.2.2

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* ACE_ModuleNameTags

**Description:**
Both nametags and interaction menu render for players that are hidden with [hideObject](https://community.bistudio.com/wiki/hideObject) or [hideObjectGlobal](https://community.bistudio.com/wiki/hideObjectGlobal).

Please implement [isObjectHidden](https://community.bistudio.com/wiki/isObjectHidden) on these two files. 
[interact_menu/functions/fnc_renderActionPoints.sqf](https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_renderActionPoints.sqf)
[nametags/functions/fnc_onDraw3d](https://github.com/acemod/ACE3/blob/master/addons/nametags/functions/fnc_onDraw3d.sqf)

**Steps to reproduce:**
Step 1:
Start a mission with a 2nd unit, or object which has ace actions.
otherunit hideObject true;
Step 2:
Open other interaction menu. It will show actions. In case of player it will also show the nametag (MP).

**Where did the issue occur?**
SP/MP

**RPT log file:**
//Wont add anything

**Comment by jokoho48** [comment]
feel free to do it by your self and please read http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html and use #414

**Comment by bux578** [comment]
Or formulate it as a bug report.

**Comment by m1ndst0rm** [comment]
Having some issues with my client so i'm posting the fix here. If someone has time please add.

[interact_menu/functions/fnc_renderActionPoints.sqf](https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_renderActionPoints.sqf). Line 40
From
```sqf
if (_target != ACE_player && {_target != vehicle ACE_player}) then {
```
To:
```sqf
if (_target != ACE_player && {_target != vehicle ACE_player} && {!(isObjectHidden _target)}) then {
```

[nametags/functions/fnc_onDraw3d](https://github.com/acemod/ACE3/blob/master/addons/nametags/functions/fnc_onDraw3d.sqf) Line 107

From:
```sqf
{!(_target getVariable ["ACE_hideName", false])}) then {
```

To:
```sqf
 {!(_target getVariable ["ACE_hideName", false])} &&
 {!(isObjectHidden _target)}) then {
```

**Comment by commy2** [comment]
Probably works for nametags, but there is a better way to do it for actions.
