### ISSUE TITLE
Error when editing PBO's

### ISSUE THREAD

**Issue by Mike319** [acemod/ACE3#2599]
ACE version 3.3.1.2

I was editing the ace_medical.pbo because when I enabled the prevent instant death feature, it didn't put people unconscious that were shot in the chest/head. So I went into the fn_handledamage and changed the setDead to setUnconscious. This was edited on both client and server, and this is an A3L server, and yes, CSE is removed.

When I did that it said something about missing script init_XEH or something. And when I went into the editor all of the medical modules were invisible.

Is there any way that we can keep ace modules in and also have the default altis revive system.

**Comment by Glowbal** [comment]
Hi,

Replacing a `setDead` call by `setUnconscious` in the code most likely will not work properly - Both functions behave differently (obviously) and return different values. 

The issue you describe sounds like you tried to manually build ACE3 but perhaps did not make use of our `make.py` script. If you wish to create a custom version of ACE that you modified, please read [our documentation](http://ace3mod.com/wiki/development/setting-up-the-development-environment.html) on setting up the development environment.

ACE3 currently does not support third party revive systems. We might do so in the future, but it is not a priority at the moment. If you wish to do so on a custom fork, I will give you a few pointers on where to start. However we will not support these modifications, so it's done at your own risk:

1. In `fn_setDead.sqf` in the medical addon is the code for revive handled. This is the part you will want to modify. [code](https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_setDead.sqf#L25-L72)
2. You will want to replace the above linked code and hook into X revive system. I am unfamiliar with "altis revive system" or any other revive system apart from CSE/ACE3. You will need to figure this out yourself.

Good luck!
