### ISSUE TITLE
Check CaManBase Hitpoints for 1.54

### ISSUE THREAD

**Issue by CashMonies** [acemod/ACE3#2600]
As said above, units for don't take any damage to their torso area.

I'm running ace 3.3.2 and CBA_A3 v2.0.0.150817 only. I'm currently playing in Dev branch but it is still the same issue in stable as well.

Here is a video demonstrating it.

https://www.youtube.com/watch?v=hIejXf5EYfY&feature=youtu.be

**Comment by PabstMirror** [comment]
http://ace3mod.com/wiki/user/how-to-report-an-issue.html

An RPT would be extremely helpful.

I wonder if they messed with hitpoints again...

**Comment by PabstMirror** [comment]
Looks like they changed inheritance on hitpoints again in 1.53 dev
New configs look something like this, note that there isn't any inheritance on HitPoints anymore, which I think should make things easier, but also means we have to redo a bit.
```
class B_Soldier_04_f: B_Soldier_base_F {
    class HitPoints {
        class HitFace
        class HitNeck: HitFace
        class HitHead: HitNeck
        class HitPelvis
        class HitAbdomen: HitPelvis
        class HitDiaphragm: HitAbdomen
        class HitChest: HitDiaphragm
        class HitBody: HitChest
        class HitArms
        class HitHands: HitArms
        class HitLegs
    };
};
```

There's about 19 UBC in current DEV 1.53.
1.52 hasn't even released so we don't have to worry about this for a while.

I can't reproduce in 1.50 with just CBA/ACE, are you running any other mods?

**Comment by CashMonies** [comment]
Hey, when I first noticed it about a week ago I had RHS on so that might have been contributing. But I haven't played on stable in a while so its probably just the Dev branch like you mentioned.

**Comment by commy2** [comment]
Close?
