### ISSUE TITLE
Ace Blocking Features

### ISSUE THREAD

**Issue by Mike319** [acemod/ACE3#2606]
Ever since Ace has been added in, it blocks the altis life rob feature.

What should happen, is you press Shift+G on someone with a gun out and it knocks them out and u should have the option to rob people.

What does happen is you press Shift+G on someone, you knock them out, but the rob features have disappeared.

Thanks for your help!

**Comment by PabstMirror** [comment]
There's nothing here to go on, we really can't do anything.

Try removing pbo's until you find which is the conflict (maybe medical).
