### ISSUE TITLE
ACE & Blastcore-Tracers shoot big balls

### ISSUE THREAD

**Issue by Mathieu-S** [acemod/ACE3#2608]
ACE3 Version: 3.3.2

**Mods:**
* `@CBA_A3`
* `@ace`
* `@blastcore-tracers`

**Placed ACE3 Modules:**
* None

**Description:**
* MX LSW Tracer Mag create big ball when a tracing bullet is shooting. The bug doesn't appear with only ACE or only Blastcore-Tracers.
* http://puu.sh/kp1qH/7eac2f043d.jpg

**Steps to reproduce:**
* Take a MX LSW shoot with it.

**Where did the issue occur?**
* Singleplayer and Multiplayer 

**RPT log file:**
* http://pastebin.com/R9x7nhQA

**Comment by jonpas** [comment]
From http://ace3mod.com/wiki/user/how-to-report-an-issue.html:

> If you have found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using only `@CBA_A3` and `@ace` on a newly created mission.

**Comment by PabstMirror** [comment]
Vanilla: tracerScale = 1;
ace_balistics changes it to 1.1;
blastcore changes it to 0.02; (with a new model)

It's a mod load order problem, blastcore needs to load after ACE.

blastcore needs `requiredAddons[] = {"ace_ballistics"}`

or just remove ace_ballistics.pbo

**Comment by Mathieu-S** [comment]
I modified the config file of blastcore with requiredAddons[] = {"ace_ballistics"} and it fix the bug, but I thinks it isn't allowed to do that.

Thank.
