### ISSUE TITLE
ace_server.pbo

### ISSUE THREAD

**Issue by thegeekdiver** [acemod/ACE3#2609]
So, on my dedicated i placed the ace_server file in the addon folder for @ace along with the ace server config and for some odd reason it prevents Arma3 Dedicated from loading.  Here is all the log generates:

=====================================================================
== c:\games\108_61_114_117_2302\1239056\arma3\arma3server.exe
== c:\games\108_61_114_117_2302\1239056\arma3\arma3server.exe -profiles=C:\games\108_61_114_117_2302\1239056\arma3\config -config=server.cfg -port=2302 -IP=108.61.114.117 -world=empty -gtqueryport=2304  -mod=@AliveServer;@ALiVE;@VQI_HALO;@CBA_A3;@acre2;@USAF;@Nimitz;@;@ATLAS_LHD;@EBU_Mods;@USAF;@ace;@JS_JC_FA18

Original output filename: Arma3Retail_Server
Exe timestamp: 2015/08/25 16:06:38
Current time:  2015/09/25 17:08:18

Type: Public
Branch: Stable
Version: 1.50.131969

Allocator: c:\games\108_61_114_117_2302\1239056\arma3\dll\tbb4malloc_bi.dll
=====================================================================

17:08:18 Error when creating WIC imaging factory:
	Error: 0x80040154
17:08:18 Splash window: Empty image - unable to draw the splash window
17:08:18 Splash window: Empty image - unable to draw the splash window
17:08:18 Splash window: Empty image - unable to draw the splash window
17:08:18 String STR_MOD_LAUNCHER_ACTION not found
17:08:18 Splash window: Empty image - unable to draw the splash window
17:08:18 Splash window: Empty image - unable to draw the splash window
17:08:18 Splash window: Empty image - unable to draw the splash window
17:08:18 Splash window: Empty image - unable to draw the splash window
17:08:41 Splash window: Empty image - unable to draw the splash window
17:08:41 Unsupported language English in stringtable
17:08:41 Unsupported language English in stringtable
17:08:41 Unsupported language English in stringtable
17:08:41 Unsupported language English in stringtable
17:08:41 Unsupported language English in stringtable
17:08:41 Unsupported language English in stringtable

Once the file was renamed .bak and the server restarted it worked.   I know the answer is in here just can't figure it out.

**Comment by PabstMirror** [comment]
The user config needs to go into the /userconfig folder not the @ace folder.

for you it should be: 
`c:\games\108_61_114_117_2302\1239056\arma3\userconfig\ace\serverconfig.hpp`

**Comment by thegeekdiver** [comment]
Thank you, ill test and report back. Thank you

**Comment by dvdbrewster** [comment]
Which file did you rename  .bak   ?   I might try this to correct an AI spawning w/o uniform problem.

**Comment by thegeekdiver** [comment]
Moving my serverconfig to the user folder seems to have fixed the boot up issue, thanks for the help Pabst.   dvdbrewster the two files i renamed were serverconfig.hpp and ace_server.pbo.

**Comment by PabstMirror** [comment]
Good to hear
