### ISSUE TITLE
After installing mine, the player's character informs about the detected mine.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2615]
ACE3 Version: 3.3.2
Stable version

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
None

**Description:**
After installing mine or explosive, the player's character informs about the detected mine or detected bomb. It looks at least ridiculous, because soldiers cannot discover his own mine/explosive. Please remove it

**Steps to reproduce:**
Place your in the map as explosive specialist and Instal mine.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by commy2** [comment]
I don't think thats possible. The "spotted a mine" stuff is from Arma and not from us.

**Comment by PabstMirror** [comment]
Check difficulty settings

I think "Show Detected Mines" controls showing the red triangle.

**Comment by commy2** [comment]
It's not about the triangles. It's about the avatar "spotting" his own mine (he removed NoRadio), because we `createVehicle` them instead by deploying them with the "Put" weapon.
The engine might handle that differently and don't trigger the talking / radio call with "Put".
Maybe he spots his mine even in Vanilla though, don't know and honestly don't care.

**Comment by mickeymen** [comment]
"I don't think thats possible. The "spotted a mine" stuff is from Arma and not from us"
in vanilla there is no this detail. This was added in ACE3 mod.

"honestly don't care"
Vain do not care, because this is not relistic detail. In my opinion ACE3 - mod focusing on realism.
If I'm wrong correct me/

**Comment by PabstMirror** [comment]
Running the full mod; `ace_noradio.pbo` removes this issue.

If you don't run noRadio, then your guy will call out because of how we create explosives.  This is an arma-engine limitation, as far as I know there is nothing we can do about it.

You can always remove `ace_explosives.pbo`.

**Comment by mickeymen** [comment]
bad news/
