### ISSUE TITLE
"Open Medical Menu" bind does nothing

### ISSUE THREAD

**Issue by BullHorn7** [acemod/ACE3#2619]
ACE3 Version: 3.3.2 stable
Arma 1.50 stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
Unedited ACE Stratis test mission, as well as CNTO community template mission

**Description:**
Pushing the default key to Open Medical Menu (H) does nothing. Rebinding the action to another key doesn't change it.

**Steps to reproduce:**
Attempt to open the Medical Menu

**Where did the issue occur?**
Listen server

**Comment by PabstMirror** [comment]
Do you have setting enabled?

Should be called "Use Medical Menu" or check var `ace_medical_menu_useMenu`

**Comment by BullHorn7** [comment]
I was just told that the feature isn't in the latest release so maybe it's not really a bug..

**Comment by PabstMirror** [comment]
It should be in 3.3.2

**Comment by Glowbal** [comment]
Thanks for your report @BullHorn7. I've tried it - it does work fine in the latest release. 

You will need to enable it in your client settings. By default, the menu is not available.

1. Enable the client setting called "Use Medical Menu" in your ACE settings menu.
2. It also should be enabled for your server/mission. This is a separate setting. By default, it is enabled.
3. When both settings are enabled, the default key binding to access the menu is `H`
4. Additionally, it is possible to use the interaction menu to access the medical menu. To do that, open the interaction menu. An option called `Medical Menu` should now appear. Select it to open the menu.
5. It is also possible to disable the 3d medical actions. For this, there is a client setting called `Medical Menu Style`. It provides you with 3 options: `3d selections`, `Radial` and `Disabled`.

If after following these instructions the menu still does not work for you, please provide RPT log files.

**Comment by BullHorn7** [comment]
The missing link was enabling the "Use Medical Menu" in the ACE settings...

I think this setting should be enabled by default because you still have to use a special bind to activate it.

Thanks.
