### ISSUE TITLE
Remote HMG turret stuns gunner inside.

### ISSUE THREAD

**Issue by prosiak** [acemod/ACE3#2627]
Remote HMG of hunter stuns gunner when hes firing it.
Its abnormal because its mounted outside of vehicle so it should not be loud enough to make gunner deaf when firing. There is a large amount of steel between gunner and a gun so it should not stun him as much as it does now.

The amount of stun is as high as if he was outside.

**Comment by PabstMirror** [comment]
I'll have to double check, but I think BIS's config is wrong on the hunter's gunner seat.

You can test by just getting in and you can hear ambient noise at full vol, but switch to passenger and it gets quiet.

**Comment by commy2** [comment]
Will be fixed with #2598

**Comment by commy2** [comment]
oops confused two issues.

**Comment by PabstMirror** [comment]
BIS config is fine (I think it was wrong a while back)

Getting hearing protection of a vehicle via config isn't easy. I was using `attenuationEffectType`/`soundAttenuationTurret` and got reasonable results

Maybe increase protection if the "armor" of `HitBody` is high??
