### ISSUE TITLE
ACE breaks Turret/Periscope on Strider/Fennek

### ISSUE THREAD

**Issue by Mudpig** [acemod/ACE3#2630]
Since version 3.3.2.0 neither remote controlled turret or the Commander Periscope is working. The devices can't turn left/right or up/down and you can't fire the weapons on the remote. Raising/lowering the periscope works.

**Comment by alganthe** [comment]
CBA 2.0 and ACE3.3.2
Placed a unit in editor and an empty Fennek, the turret behave as it should.

Please follow the [guidelines for reporting an issue](http://ace3mod.com/wiki/user/how-to-report-an-issue.html) 
but I highly doubt that is caused by ACE

**Comment by Mudpig** [comment]
I feel stupid now. Sorry to have you bothered. With CBA 2.0 and ACE only no Problem - I try to find the culprit. You want me post my find as a warning or something?
