### ISSUE TITLE
ACE_SandbagObject not available in editor

### ISSUE THREAD

**Issue by LckyLgs** [acemod/ACE3#2633]
ACE3 Version: 3.3.2 stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
- None

**Description:**
The sandbag object with classname "ACE_SandbagObject" - unlike its empty counterpart - is unavailable for placement in the editor.

I don't know if this is intentional or not, but in any case I hope that - especially with the Beta release of the Eden Editor - it might be considered for inclusion in the list of available assets. With the saving of custom compositions in BI's plans for Eden, I can imagine that eventually you'd be able to create your own sandbag wall templates fairly easily.

**Steps to reproduce:**
- Open the Eden Editor in Arma 3's latest dev build
- In the 'Assets' toolbar, navigate to Objects -> Props and type sandbag in the search box
- Wish for placeable PhysX-enabled sandbags

**Where did the issue occur?**
- Editor

**RPT log file:**
- n/a

**Comment by commy2** [comment]
#414 

We we please rename that thing before adding it to the editor?
`ACE_SandbagObject` is a pretty redundant classname.
Should be `ACE_Sandbag`

**Comment by esteldunedain** [comment]
Fixed in #3102
