### ISSUE TITLE
Remove Vignette present in default ARMA

### ISSUE THREAD

**Issue by moonmanmove** [acemod/ACE3#2634]
ARMA Vignette
http://i.imgur.com/A8XoAVs.png
ARMA without the vignette
http://i.imgur.com/V90cJ7O.png
is there a way ACE could remove this effect by default?

**Comment by alganthe** [comment]
Feature requests should go into #414

**Comment by jonpas** [comment]
#2368

**Comment by PabstMirror** [comment]
@moonmanmove - should be removed in next release
