### ISSUE TITLE
RHS tracked vehicles tracks cannot be repaired. 

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#2636]
There is no possibility, or tutorial to repair broken tracks. I looked up on wiki, but no luck. I can repair almost every part of tank, but no tracks.

**Comment by alganthe** [comment]
RHS vehicles are broken in that regard.

**Comment by PabstMirror** [comment]
by default (this can all be changed in module settings) this is what you need:

* be an engineer or repair specialist with a toolkit item
* have a spare track item nearby (by default there should be one in cargo of a tank)

and there should be a repair track interaction:

![2015-09-28_00001](https://cloud.githubusercontent.com/assets/9376747/10141389/daf11b0e-65d1-11e5-9839-e8e93cd35e10.jpg)

Tried on t72 and m1a1, let us know if there is a vehicle classname that doesn't work.

**Comment by vlad8011** [comment]
I havent this "right track" option.

**Comment by vlad8011** [comment]
I dont have Any "track" option.

**Comment by vlad8011** [comment]
![arma3 2015-09-28 19-59-24](https://cloud.githubusercontent.com/assets/14875602/10144068/d47b08b2-661b-11e5-9c50-b92f17f50465.png)
I dont have Any "track" option.

**Comment by vlad8011** [comment]
Problem is solved with 1.52 update.
