### ISSUE TITLE
RHS & Blastcore weapons tracers

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#2637]
ACE tracers look awesome and i wanted to use them along with RHS Escalation. Problem is the tracers from RHS weapons are big like this one from 30mm cannon.

**Comment by alganthe** [comment]
This is caused by RHS and not ACE, reference for a resolution #2608

**Comment by bux578** [comment]
> This is caused by RHS and not ACE,

It's more like an incompatibility between both mods rather the fault of either mod.

**Comment by vlad8011** [comment]
So where i need to write this dependednt "something"? I'm not an expert in arma archives.

**Comment by dvdbrewster** [comment]
@ VLAD  8011    Tell me about rhs and ACE3  If I place modules in WaspRHS, OR Warlords I get AIS
 w/o uniform...   Your setup must be better than mine.

**Comment by vlad8011** [comment]
My setup... you mean mods? I use Vanilla arma + CBA, RHS, ACE 3, mrg__unit_fx (sound mod), Mega Sound, AIA, Realistic Armor mod, Virtual arsenal anywhere, FatigueSystem, Bcombat, AI medic fsm, Replacement for CSAT and UK, ryd_li (for friendly tanks not drive on the friendly infantry).

**Comment by commy2** [comment]
Updated the title. Marked #2608 as duplicate, because it's essentially the same issue and closed even though it's unresolved.

**Comment by vlad8011** [comment]
I just tried to load mods in presented in the other ticked sequence but it not helped.

**Comment by Glowbal** [comment]
Solution is posted in #2608.
