### ISSUE TITLE
More info needed on how to use ace with scripts

### ISSUE THREAD

**Issue by serialtasted** [acemod/ACE3#2638]
I can't find how to use ACE 3 with scripted vehicles. I need to set vehicles as medcial vehicles and repair facilities but I can't find how to do it.

**Comment by PabstMirror** [comment]
`_theVehicle setVariable ["ace_medical_medicClass", 1, true];`
`_theVehicle setVariable ["ACE_isRepairFacility", 1, true];`

**Comment by serialtasted** [comment]
Thanks! So is the same as the getVariable inside the pbo. Do you know by any chance on how to add spare parts via script? I've tried this: [_vehicle, 5, "Car", true] call ace_repair_fnc_addSpareParts; but no luck

**Comment by jonpas** [comment]
`["AddCargoByClass", [_part, _vehicle, _amount]] call ace_common_fnc_localEvent;`
`_part` is part classname, either `"ACE_Wheel"` or `"ACE_Track"`
`_vehicle` is the vehicle object you want to add it to
`_amount` is, well, the amount of spare parts you want to add

**Comment by serialtasted** [comment]
And is there any list with all the available setVariable possibilities?

**Comment by jonpas** [comment]
> And is there any list with all the available setVariable possibilities?

No not yet, but all frameworks are getting (slowly) documented [here](http://ace3mod.com/wiki/framework/).

**Comment by serialtasted** [comment]
thank you very much for the help!

**Comment by jonpas** [comment]
Your script would also work, but you used `"Car"` where you should've used the spare part classname. It should be like that:
`[_vehicle, 5, "ACE_Track", true] call ace_repair_fnc_addSpareParts;` (or `"ACE_Wheel"` of course).

It's safer to use the event system though, in this case event named `"AddCargoByClass"`, safer in terms of future compatibility.

**Comment by serialtasted** [comment]
yes u r right, i went back to the sqf and saw your point. i misread the part where it sees wich type of vehicle is going for.

**Comment by commy2** [comment]
Please note that the Cargo and Repair API is not done yet and everything is subject to change.

**Comment by serialtasted** [comment]
For future reference:

NOT Working: ["AddCargoByClass", [_part, _vehicle, _amount]] call ace_common_fnc_localEvent;
Working: [_vehicle, _amount, _part, true] call ace_repair_fnc_addSpareParts;

_vehicle = Vehicle to add the parts
_ammount = Ammount of items of the specified type to add
_part = Type of part to add to the inventory ("ACE_Track" or "ACE_Wheel")
true = Force add items to the inventory (default: false)

**Comment by jonpas** [comment]
> NOT Working: ["AddCargoByClass", [_part, _vehicle, _amount]] call ace_common_fnc_localEvent;

Not sure, but it's probably due to locality, this works fine when called on the server, as it's used on mission start in the ACE3 itself. You can try `globalEvent`, but I am not sure.

**Comment by serialtasted** [comment]
Works with globalEvent
