### ISSUE TITLE
RHS launchers (m136) is used by the AI against infantry.

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#2639]
Like in the title. I didnt noticed this with RPG as i play mainly on OPFOR site.

**Comment by commy2** [comment]
This has nothing to do with us though. We are not responsible for RHS units. Please ask the RHS team about this.

**Comment by vlad8011** [comment]
its ace_vehicles fault. doesnt happen without it.

**Comment by SilentSpike** [comment]
ace_vehicles isn't making any chanes to RPG related classes

**Comment by commy2** [comment]
>its ace_vehicles fault. doesnt happen without it.

Thats wrong. I know exactly what the "issue" is and it's the `cost` value of the RPG's projectile being to low in `CfgAmmo`. There is nothing we can do, because we don't touch that class anywhere in ACE. Please stop spreading obviouly falsifiable rumors.

**Comment by vlad8011** [comment]
OK, thanks and sorry.

**Comment by commy2** [comment]
NP. I just can't stand misinformation. I hope you uderstand.
