### ISSUE TITLE
The rangefinder of CSAT not determines the distance

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2641]
ACE3 Version: 3.3.2
Stable

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
None

**Description:**
The CSAT rangefinder not determines(not show) the distance.

**Steps to reproduce:**
Place in your map the player-sniper(heavy) of OPFOR side. Try use rangefinder.

**Where did the issue occur?**
Editor, Virtual Arsenal.

**RPT log file:**
Not needed

**Comment by commy2** [comment]
Did you press `Tab`?

**Comment by PabstMirror** [comment]
http://ace3mod.com/wiki/feature/fcs.html

**Comment by mickeymen** [comment]
"Did you press Tab?" 
No... If press Tab, then it works/  As far as I remember in vanilla it worked differently, this moment led me astray.

**Comment by bux578** [comment]
Welcome to ACE3 :)
This isn't vanilla anymore.

**Comment by mickeymen** [comment]
Thanks, now I understand ;)
