### ISSUE TITLE
Virtual entity Zeus doesn't work properly with forced interface

### ISSUE THREAD

**Issue by Magirot** [acemod/ACE3#2642]
ACE3 Version: 3.3.2

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* None

**Description:**
While investigating why my Zeus camera keeps getting hung up in a weird way, I noticed that Forced Interface seems to not work when ACE is loaded. Even though the Zeus interface opens, the camera is still fixated on the eyes of the virtual entity, which can still move without turning. Assuming control of a unit and releasing it fixes the problem.

This feels really weird especially when no one else has mentioned it, and I could swear it worked fine (beside the camera problems I mentioned earlier) before.

A video showing the behaviour: https://youtu.be/PfP1JLMBQks

**Steps to reproduce:**
1. Add a Zeus virtual entity
2. Add a Game Master module
3. Start the game

**Where did the issue occur?**
Editor

**Comment by jokoho48** [comment]
@commy2 your turn

**Comment by commy2** [comment]
Damn BI
>allMissionObjects "camera"
>[39: <no shape>]

>curatorCamera
>40: <no shape>

So much for "all cameras"!

**Comment by commy2** [comment]
Fixed in branch.
