### ISSUE TITLE
Broken leg soldiers can carry wounded away at a normal pace

### ISSUE THREAD

**Issue by moonmanmove** [acemod/ACE3#2644]
ACE3 Version: 3.3.2
Stable

Mods:

@CBA_A3
@ace
Placed ACE3 Modules:
None

Description:
If you have broken legs (cannot do anything but slow walk) you can carry or drag at a normal jogging pace

Steps to reproduce:
Injure yourself in the legs 
Drag a wounded partner
notice you can drag or carry at a normal pace instead of slow walking

Where did the issue occur?
Multiplayer, editor.

RPT log file:
Not needed

**Comment by gienkov** [comment]
Option to carry/drag should not be available for units with wounded legs
cause of pain it may introduce (hey, I have 2 holes in my knee, lets carry
this guy).
Good point eh?
29 wrz 2015 02:31 "moonmanmove" <notifications@github.com> napisał(a):

**Comment by 35thForceRecon** [comment]
I second what gienkov said. Although one thing is not completely right: Carrying would be impossible with a serious wounded leg or even both legs but dragging is still possible as the weight does not directly go to the draggers legs and rather to the upper body and arms. Try it for yourselves with a box of beer or so. 

It would be a nice addition to make carrying impossible to people with heavily wounded legs and dragging impossible to people with heavily wounded torsos/arms. After all, it's the small things that make ACE so awesome, aren't they?
