### ISSUE TITLE
Medical issues involving armor

### ISSUE THREAD

**Issue by Dustin32bit** [acemod/ACE3#2647]
To preface this, I'm unsure if this is a bug or intended behavior, so any corrections are welcome.

I was testing out the new ACE 3 medical stuff in the editor, with all of the advanced options on (The ones for medics and for which medical system to use). Advanced med was enabled for all characters, not players only. This is on the latest version on Github, with latest CBA and A3.

First issue: I had a soldier die with no injuries after shooting him in his body armor 4 times with a 9x21mm pistol. After each shot to the torso, I checked his torso for injuries, and he had nothing - not even a bruise. No bloodloss or anything. After 4 hits or so, he dropped dead instantly, still with no injuries. Throughout this process, I noticed that his torso was becoming bloody, and he fell down a few times.

Second: I put a tourniquet on a soldier and shot him in the foot with advanced medical on. He sustained injuries, dying in the process, but without blood loss, or any critical change in BP or heart rate. 

I'm fairly sure the first situation is unintended, but are people supposed to instantly die to multiple shots to an appendage that isn't losing blood when advanced medical is on? I'd imagine it'd cause them a great deal of pain and unconsciousness, but not instant death.

Thanks, and sorry if this is intended or the wrong place to post this!

**Comment by bux578** [comment]
Thank you for submitting this issue. But could you please add the missing information as pointed out in this guideline: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by bux578** [comment]
Closing in favor of https://github.com/acemod/ACE3/issues/3134
