### ISSUE TITLE
BattlEye blocks loading of .dlls

### ISSUE THREAD

**Issue by narrowsoul** [acemod/ACE3#2651]
When starting the game, Battleye blocks loading of several ACE .dlls.
![screenshot 6](https://cloud.githubusercontent.com/assets/13448397/10172834/2a27f8cc-667d-11e5-9fcb-4dbffc790508.png)

Then when trying to load any map at all (including a plain map of Stratis with nothing but a vanilla rifleman placed), I get "Extension ace_advanced_ballistics.dll is not installed."
![2015-09-29_00001](https://cloud.githubusercontent.com/assets/13448397/10172859/410cffec-667d-11e5-80c0-9079267f029f.jpg)

I do in fact have the proper .dlls, and this appears to be linked to not being able to contact the BattlEye servers, as when I restarted the launcher and BattlEye could dial home everything works perfectly.

No idea if this is even your guys' problem, but I figured it was worth reporting.

**Comment by PabstMirror** [comment]
I think first line is the problem, battle eye can't update.

Try manually updating http://www.battleye.com/downloads/ (get client and service for your type of windows)

**Comment by commy2** [comment]
Apparently the battleye servers are down atm.

**Comment by vlad8011** [comment]
Battle eye is next thing that destroy whole fun for normal players. If you play in singleplayer, remember DO NOT USE BATTLE EYE!

**Comment by bux578** [comment]
And if you're part of a community you actually don't need battle eye when doing training or missions. Imho battle eye is only useful for public servers (BR, KOTH, Epoch, Wasteland ...) .

**Comment by jonpas** [comment]
What @bux578 said. :)

**Comment by alganthe** [comment]
Don't forget to start Arma 3 once through the Arma 3 launcher, BattleEye need updating and it can only be done through there for some reasons.

**Comment by NummiE** [comment]
BattleEye is also useful for matches with other clans. We at armafinland do it quite a lot and prefer to have the added safety when inviting strangers on your server.

But otherwise, yeah, don't turn on BattleEye, it screws people over.
