### ISSUE TITLE
These hysterical twitching models

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#2657]
ACE3 Version: 3.3.2.0

Mods:
 `@CBA_A3`
 `@ace`

Placed ACE3 Modules:
Advanced Ballistics, Explosive System, Map, medical "Basic".

Description:
Is it possible to correct these hysterical twitching character models in contact? It looks awful and is massive. He killed a man in the head, and he decided to jump up and dance ...

Steps to reproduce:
1)Lie once injured, at this moment our boat can stand up.
2)Shoot another wounded bot.

**Comment by commy2** [comment]
Improving ragdolls is a feature request. #414 
We currently will not touch this as BI is doing stuff on their own in dev branch / tanoa expansion pack which could cause conflicts.

**Comment by GalNa** [comment]
When I was injured, I lay down, but my body immediately stood up.

**Comment by vlad8011** [comment]
So what module i need to delete to get rid of this? ace_hitreactions and something else or just this one?
