### ISSUE TITLE
Remove daltonism from a shooting.

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#2665]
ACE3 Version: 3.3.2

Mods:
* @CBA_A3
* @ace

Description: 
Lying a solder receives daltonism during a shooting. 
Remove daltonism from a shooting. Save the effect of explosions.

**Comment by jokoho48** [comment]
this is a design decision.

**Comment by GalNa** [comment]
This is slop decision.

**Comment by alganthe** [comment]
What's the question exactly?

**Comment by PabstMirror** [comment]
daltonism = lack of color
I think this is from ace_googles.

You can remove ace_googles.pbo or wear eye protection when shooting from dusty ground.

**Comment by GalNa** [comment]
I want to this effect was absent when i shooting without eye protection. That's when the explosions, yes. Sorry for my English.
