### ISSUE TITLE
Wipe Goggle KeyBind disappeared 

### ISSUE THREAD

**Issue by brose909** [acemod/ACE3#2667]
Was attempting to change the Wipe Goggle keybind and the menu option completely disappeared after I double clicked it. Was in Configure > Controls > Mod Config > Ace 3 Common.
I successfully reinstalled the mod and the problem persist and was able to replicate it with other keybindings unfortunately. Now the character is constantly wiping the goggles and there is nothing I can do about it.

**Comment by PabstMirror** [comment]
Do you have controller plugged in? 
We've seen issues with CBA (https://github.com/CBATeam/CBA_A3/pull/155)

One option might be to remove the controller and restart the game and see if you can't rebind that key.
Or hit reset all.

**Comment by brose909** [comment]
Unplugging the Xbox controller and restarting the game seemed to have fixed it. Thank you!
Kinda imbarissed I didn't think of that lol
