### ISSUE TITLE
PLEASE remove walking when shot in the legs

### ISSUE THREAD

**Issue by tangosuckaGSC** [acemod/ACE3#2675]
it is VERY frustrating when trying to play because if you get shot in the leg once you have to either RTB or deal with it. From what i have seen people would prefer having a balance between realistic and fun and removing this feature would put this mod in the right direction

**Comment by Armilio** [comment]
Not really, no.

**Comment by jokoho48** [comment]
if you want to make a feature request read: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html and use #414
