### ISSUE TITLE
ace_spectator: 3D icons not working

### ISSUE THREAD

**Issue by voiperr** [acemod/ACE3#2676]
ACE3 Version: 3.3.2 Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* ace_spectator, with `GVAR(filterUnits) = 3`

**Description:**
* Spectator 3D icons do not draw at all. 
* Possibly because `cameraEffectEnableHUD true` is not called here?: https://github.com/acemod/ACE3/blob/master/addons/spectator/functions/fnc_transitionCamera.sqf#L51

**Steps to reproduce:**
* Send the player into spectator mode through
```
ace_spectator_fnc_setSpectator;
[player, true] call ace_spectator_fnc_stageSpectator
```

(do not call it through the debug console; it will crash the game)
* Repro mission: https://www.dropbox.com/s/f70zd9md0vmc1js/ace_spectator_bugs.Stratis.pbo?dl=0

**Where did the issue occur?**
Everywhere

**Comment by alganthe** [comment]
:+1:

**Comment by SilentSpike** [comment]
Yeah, I suspect this is a bug that I experienced early in development that has been reintroduced somewhere later on.

It seemed that icon rendering is dependent on the current switchCamera target.

**Comment by SilentSpike** [comment]
Do they not draw in *any* camera mode?

**Comment by SilentSpike** [comment]
Seems your theory was right :smile:

Working with cameras and view can be really finicky
