### ISSUE TITLE
Taking launcher from ground has problems. (near a dead soldier)

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2678]
ACE3 Version: 3.3.2
Stable version 1.52

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
None

**Description:**
For me, this Problem with taking launcher from the dead soldier, was always in the vanilla game. Most likely this bug of the vanilla game, but perhaps the ACE3, also has an impact on the problem.

In ACE3, when a player wants to take the launcher near a dead soldier, then he uses the icon with the inventory, which appears at a certain distance from the corpse. But if the player opens inventory menu, in the list of items, very often, the launcher may be absent. In this case, the player should try several times to use the icon of inventory and accurately aim at the launcher. Sometimes it takes many attempts before the player will be able to pick it up. At the moment of contact with the launcher, happens a little jump of this launcher and only after this, the launcher becomes available in the inventory for the player. Thus the fallen launcher always requires a personal contact via icons inventory. This feature complicates a simple action, espacially during battle. Please fix this issue. Make the launcher available in the inventory initially, like all other things, without problem.

**Steps to reproduce:**
Take launcher from dead AT-soldier.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by commy2** [comment]
Sadly, there is absolutely no way for us to change this behaviour, as it's completely hard-coded by the game engine.

**Comment by jokoho48** [comment]
@commy2 than close

**Comment by PabstMirror** [comment]
This issue can be really annoying when you really need that AT.

Just like we add an inventory action to cargo boxes, we could possibly add an inventory action to `WeaponHolderSimulated` or maybe even a "Pickup Weapon".

Reference, killed AT guy, AT doesn't show in list because it falls separately.

![2015-10-03_00002](https://cloud.githubusercontent.com/assets/9376747/10265720/fa8f76f2-6a01-11e5-9aa0-bb33941fd640.jpg)

**Comment by commy2** [comment]
no working add magazine command.

**Comment by mickeymen** [comment]
@commy2 It is not clear, why this may be a not solvable problem? I almost never have observed this issue with primary weapons! It happens only with the launcher

**Comment by Glowbal** [comment]
> hard-coded by the game engine.

This means it is not possible for us to make any adjustments to this.

**Comment by commy2** [comment]
>It is not clear, why this may be a not solvable problem?
We have to rely on scripting commands and config to modify this game. The behavour of these so called "ground weapon holders" is not defined in a config and cannot be changed by any existing scripting commands. You'll have to ask Bohemia Interactive to change them, as their is no way for us to do it.

**Comment by mickeymen** [comment]
Thank you for your answers. Sad to me/
