### ISSUE TITLE
Question about medical system

### ISSUE THREAD

**Issue by Reekoj** [acemod/ACE3#2687]
Hello,

I would like to use the ACE 3 medical system for Altis Life, the problem is that everybody has the interaction menu.
Do you know how i could prevent people which are not in the side Independant to have an interaction menu ?

**Comment by commy2** [comment]
`["Reekoj_notIndependent", {side group (_this select 0) != independent}] call ace_common_fnc_addCanInteractWithCondition`

**Comment by commy2** [comment]
Has to be exectuted on every machine

**Comment by SilentSpike** [comment]
I think he just means the medical menu

**Comment by Reekoj** [comment]
@commy2 
Thank you it works.
But when i spawn into independant, i don't have any interaction with players : see this pic : http://i.imgur.com/1p5nsWp.jpg

**Comment by commy2** [comment]
That was the point, wasn't it? To disable the interaction menu for units on the independant side.

**Comment by Reekoj** [comment]
No the opposite 
["onlyIndep", {playerSide == independent}] call ace_common_fnc_addCanInteractWithCondition;

For indep, i want them to be able to open the menu on them and on other sides
And for other sides, i don't want them to be able to open the menu at all.

**Comment by commy2** [comment]
Gotcha. Question answered?

**Comment by Reekoj** [comment]
The original question is answered but do you know why on the screen i don't have any option when i target the civilian ?

**Comment by commy2** [comment]
No idea. If that condition is true you should be able to interact.

**Comment by commy2** [comment]
If you look at the civilian and put this code in the debug console under "Watch:":
`getText (configFile >> "CfgVehicles" >> typeOf cursorTarget >> "Eventhandlers" >> "init")`
What does it show for you?

**Comment by Reekoj** [comment]
16:13:53 "_this call SLX_XEH_EH_Init"

**Comment by commy2** [comment]
Hmm. You should be able to interact with him. Does this happen even without the code above?

**Comment by Reekoj** [comment]
yes, it's the same without the code above, but the civilian can open his menu and has options on me.

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/issues/1171

**Comment by Reekoj** [comment]
Ok my bad omg i didn't use the right command. It's right windows for me to interact with people. 
Problem solved thank you for your help !

**Comment by commy2** [comment]
krgr
