### ISSUE TITLE
Required improve the Dragging / Carrying turrets/mortars and other.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2688]
As seems to me, for simulator game, required the more best implementation of Dragging / Carrying.
Just some points I noticed: 

1) when player drag turrets/mortars or even injured soldier, no exist any sound of dragging. You have added the sound of the opening of the backpack and I think the action of dragging in the AVE3 no less important detail.
2) when player moves the static turret/mortar, this object does not rise above ground level. I think you need to raise it higher above the ground, because he lies on the ground.
3) when carried, the static turret/mortar, located is too far(ahead) from the player. I think you need to bring it to the player, much closer.
4) During the carry there are no normal animations. The player removes primary weapon on his back and still not finished this animation, already takes the object, without using your hands! It looks bad. It may be difficult to implement a perfect animation, but any attempt to show the raised hands of the player character with more close contact with the object, greatly improve the carrying effect in ACE3.

All together these points spoil the feeling of Dragging / Carrying in the ACE3.

**Comment by jokoho48** [comment]
please Read this: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
and use #414

**Comment by mickeymen** [comment]
my friend I chose the label "feauture request". Why "closed" status? wouldn't it be easier to move this issue in "feauture request"?

**Comment by mickeymen** [comment]
apparently I did something wrong/
