### ISSUE TITLE
Atropine Logic Issue

### ISSUE THREAD

**Issue by DieKunstdesKrieges** [acemod/ACE3#2689]
ACE3 Version: 3.2.0. Stable.

Conflicting Addons: None.

Realism/Logic Issue.

Placed ACE Module: Advanced Medical. (Highest Realism Grade Possible.)

Atropine in ACE is used to lower the heart rate of the patient. In reality, Atropine is a heart rate RAISING medication. Heart Rate lowing medications are mostly administered in the form of Beta Blockers. Thus ACE is losing some realism if a medication is doing the exact opposite of its real life counterpart.

Steps to reproduce: None. Logic Issue.

**Comment by bux578** [comment]
#1573 #1566

**Comment by bux578** [comment]
Thank you for the report though :)
