### ISSUE TITLE
[Question] Laser-Guided Bombs

### ISSUE THREAD

**Issue by Blackswater** [acemod/ACE3#2690]
Hey devs, 

I have a quick question. ACE3 had in some earlier Version Laser-Guided Bombs disabled. My question is, if it is still disabled or if it now enabled. With the Laser-Designator you have the lasercode but how do I use this in an A-10?? I can't look on on the lasertarget. If it is enabled and it should work, can you tell me pls how to use it? I have nothing found for this

**Comment by madpat3** [comment]
-can't get a lock on, too. 
-reported an issue

**Comment by PabstMirror** [comment]
Ref PR #2349

In 3.2.2 locking was disabled on a base class `RocketPods`, which broke a lot of vanilla weapons that should be able to lock.

It is fixed on master and will be included in next release.

Right now an temp fix would be to remove missleGuidace, javelin, laser and laser_selfDesignate pbos.
