### ISSUE TITLE
Missing Keys

### ISSUE THREAD

**Issue by Dessoa** [acemod/ACE3#2691]
Mods:

    @CBA_A3
    @ace

Placed ACE3 Modules:

    None

Description:
Look at the picture
The keys are vanished and i dont know, how they come back.

Steps to reproduce:

i dont really know

![2015-10-04_00004 1](https://cloud.githubusercontent.com/assets/14967407/10293074/d9be2dbc-6bb2-11e5-809c-3ebe95e7518c.jpg)

Where did the issue occur?

    Editor, Multiplayer & main menu

RPT log file:

 look at the screen

**Comment by jokoho48** [comment]
https://github.com/CBATeam/CBA_A3/issues/113

**Comment by PabstMirror** [comment]
It's because of the controller, you can try removing the controller and then setup the keybinds.

It's a known issue and should be fixed in next release of CBA

**Comment by Dessoa** [comment]
okay thank you very much.
