### ISSUE TITLE
Medical System No Torso Damage

### ISSUE THREAD

**Issue by AcidKat** [acemod/ACE3#2693]
ACE3 Version: 3.3.2

Description:
While running the ACE Medical System I have discovered a game breaking bug, it seems to negate all damage to torso.
The problem always persists while running the Medical Section of ACE 3. It includes players and AI, it is persistent on Multi and Single-Player. It happens even in the Virtual Arsenal.
The Issue is also persistent across DEV and release builds of ArmA 3.

Modules:
Problem persists without placed modules.

My list of Mods:
CBA A3 2.0.0.150817
TFAR (Current)
RHS (Current, Problem Persists without this mod)
ASR AI (Current, Problem Persists without this mod)
HLC Pack, RH Pack (Current)
tao fold map (Current)
ST Mods (Current)

**Comment by AcidKat** [comment]
Just realised that this problem was addressed under "Check CaManBase Hitpoints for 1.54". My bad.

**Comment by 74NN3R** [comment]
Did this get resolved? Because I am still having this exact same issue.
