### ISSUE TITLE
Error who doesn' let me play on server "ace_protection.pbo" is outdated

### ISSUE THREAD

**Issue by Pouflex** [acemod/ACE3#2694]
Hello, I have a problem in my server check this : 
ACE3 Version: 3.3.2 stable
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* `@CBA_A3`
* `@ace`
-@Task Force radio 0.9.8
@MCC Sanbox
@RHSAFRF, @RHSUSAF
@Ares

**Placed ACE3 Modules:**
None

**Description:**
I got this when launching a mission on my server : "ace_protection.pbo" is outdated.

**Steps to reproduce:**
* *Add the steps needed to reproduce the issue.*

**Where did the issue occur?**
On multiplayer by launching a new mission.

**RPT log file:**
http://pastebin.com/KHZe09v8

**Comment by Glowbal** [comment]
Delete `ace_protection.pbo`.

**Comment by PabstMirror** [comment]
When upgrade to a new version of ACE.  It is best is to delete the old @ace folder and then extract the zip.

Just overwriting won't delete old pbo's that don't exist.
