### ISSUE TITLE
Server crashes on startup with latest version of ACE

### ISSUE THREAD

**Issue by nikolaskelset** [acemod/ACE3#2695]
Server stops loading and console crashes with the latest version of ACE at the very startup. Also no logs are displayed on the server crash log so I really don't know where to check. Previous version of ACE was fine, with this one ,server just refuses to start. Currently using Gameservers.com services. Any ideas where I should check to find out any kind of log or issue hint?

**Comment by PabstMirror** [comment]
Add `-profiles=profiles` to launch params then it will put logs in `C:\Arma3Dedicated\profiles`

Then just look for the most recent RPT.

**Comment by nikolaskelset** [comment]
I fixed it. It seems the issue was a corrupted .pbo when the new version was downloaded. So even when I uploaded again the file was still corrupted. A new download of ACE fixed it. The issue was entirely my end.

**Comment by Glowbal** [comment]
Glad you managed to fix your issue! :+1:
