### ISSUE TITLE
Rangecard empty

### ISSUE THREAD

**Issue by guare88** [acemod/ACE3#2696]
Apologize for that.

ACE3 Version: 3.3.2

**Mods:**
@CBA_A3
@ace
@RHS USAF
@RHS AFRF

**Placed ACE3 Modules:**
None

**Description:**
No values showned when open rangecard

**Steps to reproduce:**
Used weapons: M2010 (from MOD) and lynx
Added rangecard to inventory (uniform or jacket). Opened with ACE menu. No values showned

**Where did the issue occur?**
Tested in VR arsenal and Editor

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by guare88** [comment]
Apologize for that.

ACE3 Version: 3.3.2


**Mods:**
@CBA_A3
@ace
@RHS USAF
@RHS AFRF

**Placed ACE3 Modules:**
None

**Description:**
See first post

**Steps to reproduce:**
Used weapons: M2010 (from MOD) and lynx
Added rangecard to inventory. Open with ACE menu. No values showned

**Where did the issue occur?**
Tested in VR arsenal and Editor

**Comment by PabstMirror** [comment]
I can't reproduce and get no numbers on my range card, but I did find code that is throwing script errors that may cause failure.

If you could get one, it might help to post a screenshot of the error (can just drag jpgs into text box here)
