### ISSUE TITLE
CHA_LAV25 not presenting interaction option

### ISSUE THREAD

**Issue by Gezzunder** [acemod/ACE3#2697]
Link to addon http://www.armaholic.com/page.php?id=26184

No ACE interaction node appearing on the LAV25 variants by Chairborne.  Config shows Aceactions attached, but something seems to be missing or out of whack

**Comment by jokoho48** [comment]
this is a mod fault please contact the author. to fix it temporaly 
>We have noticed that when using ACE with 3rd-Party mods that do not fully support CBA Extended Eventhandlers (XEH) that some units do not work with Interaction fully. You may see the cursor but no menus.
WORKAROUND: The latest CBA has an optional PBO that you can activate to help resolve these situations.
1. Move the cba_enable_auto_xeh.pbo and its signature file from the CBA optional folder to the CBA Addons folder
2. Restart Arma.
