### ISSUE TITLE
PAK with condition stable is not possible for revive state

### ISSUE THREAD

**Issue by FettLi** [acemod/ACE3#2698]
ACE3 Version: 3.3.2

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None (medic settings done via missionConfigFile)

**Description:**
When you set the condition on when to use the personal aid kit to stable, you can't revive any person out of the revive state.
The error can be found in lines 65-69. The heart rate will allways be set to 0. So the guy in revive state will never be stable. So he will never be able to receive a personal aid kit healing.

**Steps to reproduce:**
---

**Where did the issue occur?**
Everytome

**RPT log file:**
No scripting error

**Comment by Th3Cr0w** [comment]
Stable Condition checks for blood loss and open wounds
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_isInStableCondition.sqf
heart rate of 0 shouldn't be a hindrance

**Comment by BaerMitUmlaut** [comment]
I don't know about you, but having no heart rate does not sound stable to me, this seems extremly unintuitive. I'd either rename it or add the heart rate as a condition.

**Comment by FettLi** [comment]
Thanks for the explanaiton!
My bad then...
