### ISSUE TITLE
The unconscious player continues to hear all the sounds around him.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2700]
ACE3 Version: 3.3.2
Stable version 1.52

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
None

**Description:**
The unconscious player continues to hear all sounds around him and radio talks, as heard them before. Unfortunately such detail is absurd in ACE3. In the event of loss of consciousness, it would be great to hear blurred and muffled sounds, as if from afar.

**Steps to reproduce:**
Play in ACE3

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by PabstMirror** [comment]
There should be an ace_setting that takes care of this:

Default is 0.4, drop it to 0 if you like.
```
class ACE_Settings {
    class ace_hearing_UnconsciousnessVolume {
        value = 0.4;
        typeName = "SCALAR";
    };
};
```

**Comment by mickeymen** [comment]
Please explain more precisely. Where can I change these settings?

**Comment by PabstMirror** [comment]
http://ace3mod.com/wiki/framework/settings-framework.html

You can add the above code to description.ext (make sure to reload the mission in editor)

**Comment by mickeymen** [comment]
Ok. The player can affect it. However, this is essentially a bug, can be fixed or not?

**Comment by SilentSpike** [comment]
This isn't a bug. See the response above.

**Comment by mickeymen** [comment]
"This isn't a bug" My friend, If the person is unconscious, then he can't hear any ambient sounds. In the ACE3 the player continues to hear sounds. If this is not a bug then what is it?

**Comment by SilentSpike** [comment]
A design decision, see the response above, it can be easily tweaked on a server/addon/mission basis.

**Comment by PabstMirror** [comment]
Unconsciousness is not always a complete blackout.

In many cases it's representing extreme pain, delirium; "Getting the wind knocked out of you".
So, it can be that you can't move or react, but you can still have some idea of what's going on around you.

I guess I would be fine dropping the default down to something like 0.25. But there is an ace setting that you can change to your tastes.

**Comment by mickeymen** [comment]
"So, it can be that you can't move or react, but you can still have some idea of what's going on around you." 
Yes, yes, yes! However, the player should feel the difference of sound. I before was told. it would be great to hear muffled or blurred,sounds as if from afar. Sorry, but in the ACE3, there is no difference of sound, between the conscious and unconsciousness. And for this reason this part looks like a bug. However this is only my opinion.
Thanks for your answers;)
