### ISSUE TITLE
tourniquets have effect on injected medication

### ISSUE THREAD

**Issue by ThatSnipingGamer** [acemod/ACE3#2704]
ACE3 Version: 3.3.2

Happens on Stable, Dev and RC Builds of ArmA 3

Mods:

@cba_a3
@ace3

Injected drugs still have full effect when applied to a limb with a tourniquet on it. I'm pretty sure if a tourniquet is applied correctly it would cut off all blood flow to that targeted limb, any drug applied to the targeted limb would only have local effects. I know the example I am about to list is a completely different drug, but the circulatory system is the highlight. 

May 3, 1995. Missouri. Emmitt Foster. Lethal Injection. Seven minutes after the lethal chemicals began to flow into Foster's arm, the execution was halted when the chemicals stopped circulating. . Death was pronounced thirty minutes after the execution began. According to William "Mal" Gum, the Washington County Coroner who pronounced death, the problem was caused by the tightness of the leather straps that bound Foster to the execution gurney; it was so tight that the flow of chemicals into the veins was restricted. Foster did not die until several minutes after a prison worker finally loosened the straps. The coroner entered the death chamber twenty minutes after the execution began, diagnosed the problem, and told the officials to loosen the strap so the execution could proceed.

source: http://www.deathpenaltyinfo.org/some-examples-post-furman-botched-executions

Steps to reproduce:
1) tourniquet a limb
2) apply morphine/epinephrine/atropin to the limb with a tourniquet on it

**Comment by Glowbal** [comment]
:+1:
