### ISSUE TITLE
AMV-7 Marshall Based on

### ISSUE THREAD

**Issue by matosh2** [acemod/ACE3#2705]
The name Patria AMV is correct but to a certain extent. AMV-7 Marshall was based on the Badger 8x8 Infantry Fighting Vehicle (IFV) which is, in the future, going to be used by South African National Defense Force (SANDF). Badger has, of course, Patria AMV chassis. But this vehicle will have, I guess, it's own modifications to fit SANDF's requirements and government budget. 

**Armament:**
Turret: LCT-30
Cannon: GI-30 (GI-40 for ArmA 3)
Coax: MAG 58M

**Sources:**
http://www.military-today.com/apc/badger.htm
http://www.armyrecognition.com/south_africa_african_army_wheeled_armoured_vehicle/badger_denel_8x8_armoured_infantry_fighting_vehicle_technical_data_sheet_specifications_pictures.html
http://www.denellandsystems.co.za/products/infantry-systems

**Comment by dixon13** [comment]
These are some good sources for the name. I don't know who is in charge of names, but you make good points about the name.

**Comment by madpat3** [comment]
i think BI modelled the prototype of the badger, since it is amphibious. the waterjets were removed later, when it came to production. the patria is a amv (a modular built vehicle). so basicly you can do any combination of  parts you want, with that platform.

**Comment by matosh2** [comment]
First source link is for the prototype version.

**Comment by madpat3** [comment]
so ACE Team should rename it to "Badger IFV (Prototyp)"?

**Comment by jonpas** [comment]
> I don't know who is in charge of names

https://github.com/acemod/ACE3/tree/master/addons/realisticnames#maintainers

**Comment by commy2** [comment]
So basically me.

Any objections to this rename?

**Comment by madpat3** [comment]
I wouldn't change it, cause it is a fictional constallation of the modular build patria.
indeed it exists as a prototyp, but only to develop the badger (which has NO propellers for amphibious operations).
at most you could rename it to e.g. "Patria AMV(LCT-30)", which is the turret, also being used by the badger.

**Comment by matosh2** [comment]
You should rename it, because the Badger is a designation for the South African modified version of Patria AMV, and from the obvious reasons AMV-7 Marshall was modeled after (prototype version) it.
