### ISSUE TITLE
Add support for privatizing variable with local keyword to tools

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#2706]
The following tools don't support `local` keyword yet (eg. `local _var = _x`):
- [ ] `search_privates.py`
- [ ] `search_unused_privates.py`

**Comment by jonpas** [comment]
@PabstMirror Why closed? `search_unused_privates.py` still doesn't have local support.

**Comment by PabstMirror** [comment]
if you do `local _test = 5`, it's kind of both defined and used

**Comment by jonpas** [comment]
Ah, well that's true!
