### ISSUE TITLE
Cargo >> getSizeItem always return -1 if no config for cargo is present

### ISSUE THREAD

**Issue by ShuraDE** [acemod/ACE3#2712]
getSizeItem will alway return -1 if object hasn't a proper config in cfgVehicle.
https://github.com/acemod/ACE3/blob/v3.3.2/addons/cargo/functions/fnc_getSizeItem.sqf

correct me if i'm wrong, but if like a object to be loadable with:
_obj setVariable ["ace_cargo_size", 1]; 
_obj setVariable ["ace_cargo_canLoad", 1];
like a Hedgehog i can't do this.

**Comment by PabstMirror** [comment]
Right now initObject only works on objects with proper configs:
`ace_cargo_canLoad = 1`

So everything that canLoad should also have a proper size set as well.

Right now if you want to make something loadable you'll need to modify it's config, we might be able to change that to modify per mission.
