### ISSUE TITLE
Patria & Merkava Coax Green Tracer

### ISSUE THREAD

**Issue by matosh2** [acemod/ACE3#2716]
**ACE3 Version:** 
3.3.2, STABLE

**Mods:**
@CBA_A3 (v2.0)
@ace

**Placed ACE3 Modules:**
None

**Description:**
Coax gun on Patria AMV and Merkavas shoot green tracer ammo instead of red.

Patria AMV - B_APC_Wheeled_01_cannon_F
Merkava Mk IV M - B_MBT_01_cannon_F
Merkava Mk IV LIC - B_MBT_01_TUSK_F

**Steps to reproduce:**
1. Spawn one of the above mentioned vehicles.
2. Be in the gunner position and switch to coax gun.
3. Fire and see the tracers.

**Where did the issue occur?**
Editor and Virtual Arsenal. Haven't checked in the Singleplayer and Multiplayer mode.

**RPT log file:**
N/A

**Additional Information:**
Not sure if they use green tracer ammo in real life, but in-game the NATO is using those vehicles so I'm guessing they have to use the red ones.

In vanilla ArmA3, red tracer ammo is being used.

**Comment by commy2** [comment]
Fixed in https://github.com/acemod/ACE3/pull/2708

**Comment by commy2** [comment]
Nope, not fixed.

**Comment by commy2** [comment]
fixed in https://github.com/acemod/ACE3/pull/2795
for real this time
