### ISSUE TITLE
ACE3 for linux... problem with DLL????

### ISSUE THREAD

**Issue by yves21** [acemod/ACE3#2720]
Hello,
we use a linux server and with this mod, we have some problem with... DLL...
Is it normal?

**Comment by PabstMirror** [comment]
It might say something about not finding the dll, but everything should be able to fallback to sqf.

Do you have a specific error / RPT.  Is something not working correctly?

**Comment by MikeMatrix** [comment]
On that note though, I really do think we should provide `.so` files for the linux servers as well

**Comment by Inlesco** [comment]
The playerbase of Linux and OSX combined is so small that I don't it's worth the effort to provide a coherent experience instead of improving and bugfixing the main Windows version.

Just my bastardish 0.02.

**Comment by MikeMatrix** [comment]
@Inlesco that might be true, but there are still a lot of linux servers running A3 servers out there. Having some of the optimizations that binary libraries bring to the mod on the server side might be worth considering, since server performance is quite critical in terms of Arma's architecture.

**Comment by yves21** [comment]
It's for Server... not play... :-)

**Comment by Glowbal** [comment]
Hi @yves21, what exactly are the problems you encounter? None of our extensions/dlls are required on dedicated servers.

**Comment by yves21** [comment]
hello, @Glowbal  i've a server on linux (CentOS 7) for Arma3, but with Ace, we 've some errors... It can't find some files with dll...
So, my question is : ACE3 is  compatible with Linux? And if yes, how should it did?

**Comment by PabstMirror** [comment]
ACE should work correctly on a linux server.
The server can run just fine without the .dlls.
If you have problems then please post a full issue (see http://ace3mod.com/wiki/user/how-to-report-an-issue.html)

**Comment by christopherfowers** [comment]
Can I ask for an update on the Linux optimizations? I'm hosting servers and doing so in Linux.

**Comment by commy2** [comment]
Please don't revive onths old and unrelated issues. Thank you.

**Comment by christopherfowers** [comment]
Please don't tell me what to ask questions on. Thank you. The question and issue is relevant to my current situation and I am seeking information to better it.

**Comment by commy2** [comment]
The issue is also closed since october, so please create a new one.

**Comment by bux578** [comment]
@christopherfowers I'd suggest you sometimes listen to people. Especially if they are maintaining this project ...
