### ISSUE TITLE
ACE3 + CBA won't let me rebind keys

### ISSUE THREAD

**Issue by cratman9** [acemod/ACE3#2722]
Hi, I've posted here before about how when I tried to rebind my keys they deleted them. Now i've already reinstalled A3 multiple times and on different drives and the keybinds are still deleted. Any help is appreciated!

**Comment by jokoho48** [comment]
as we say wait for the Next CBA Update that will fix it

**Comment by PabstMirror** [comment]
Do you have a controller pluged in?
If so you can try removing the controller and then setup the keybinds.

**Comment by cratman9** [comment]
I removed it when I found out.
