### ISSUE TITLE
ACE3 + CBA won't let me rebind keys 

### ISSUE THREAD

**Issue by cratman9** [acemod/ACE3#2723]
Hi, I just posted here about this issue but I already removed my controller quite a bit ago after discovering that it was deleting the keybinds. Even with it removed it still stays deleted. Sorry for posting again.

**Comment by PabstMirror** [comment]
Execute this in the debug console, (start editor and put down a unit and hit preview, then hit escape)

```
profileNamespace setVariable ["cba_keybinding_registryNew", nil];
saveProfileNamespace;
```

**Comment by cratman9** [comment]
Thanks, will try!

**Comment by cratman9** [comment]
I did what you suggested and theres no change.
