### ISSUE TITLE
Stuck in interaction menu

### ISSUE THREAD

**Issue by toby1811** [acemod/ACE3#2740]
When I press control the menu stays up even when I release it. It does this for the self interaction menu aswell. I cannot fire my weapon because of it.

**Comment by jokoho48** [comment]
thanks for reporting but could you please read this: http://ace3mod.com/wiki/user/how-to-report-an-issue.html
and make the post fitting in our standarts to help us to fix this issue thanks

**Comment by PabstMirror** [comment]
Please try with just most recent versions of CBA and ACE:
https://github.com/CBATeam/CBA_A3/releases/latest
https://github.com/acemod/ACE3/releases/latest

If you are still having problems please make a new issue with a RPT log.
