### ISSUE TITLE
Using the cargo system

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#2741]
How to I enable a custom object to be loaded into the cargo?
Can't find it http://ace3mod.com/wiki/framework/

Something simliar to http://ace3mod.com/wiki/framework/dragging-framework.html
 would be neat !

IDEA: carry stacks of money to the car and load them in.

Thank you.

**Comment by jonpas** [comment]
Already planned.

**Comment by alganthe** [comment]
I'm starting to work on it, but please note that it will be for addon makers and not mission makers.
Mission makers doc is going to come later, probably after 3.4

**Comment by commy2** [comment]
Close?
