### ISSUE TITLE
ACE Medical Damage

### ISSUE THREAD

**Issue by moonmanmove** [acemod/ACE3#2744]
ACE3 Version: 
3.3.2, STABLE

Mods:
@CBA_A3
@ace

Placed ACE3 Modules:
None

Description:
On basic medical, and advanced shots to the head (even with just a boonie on) knock people unconscious, and does not kill them.

Steps to reproduce:
place medical module
place ai and yourself
shoot ai in the head
does not die 

Where did the issue occur?
Arsenal, editor, multiplayer.
RPT log file:
N/A

Additional Information:

**Comment by headedhorseman101** [comment]
Same as #2624

**Comment by Glowbal** [comment]
This should be fixed. If this issue happens again, please create a new ticket.
