### ISSUE TITLE
Sometimes a RPG-soldier when fired, gets damages or loses consciousness(!empty and flat places of map)

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2747]
ACE3 Version: 3.3.2
Stable version 1.52

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
None

**Description:**
When the soldier(player or bot) fires from the RPG-42, SOMETIMES he takes damage or loses consciousness. If Player fires from RPG-42, then at these moments he can have extensive damages (arms, legs, torso, head) I assume that the jet may damage the player, but the player loses consciousness or receives damage even on an empty map, away from closed spaces. Probably in ACE3 was an idea, at which the RPG-soldier can be damaged, but anyway it looks is strange.

**Steps to reproduce:**
Play for a some time AT-Soldier of OPFOR-side and use the RPG-32.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by commy2** [comment]
Backblast?

**Comment by mickeymen** [comment]
Unknown reason for me. I don't understand what is going on, just a player or bot falls unconscious with damages (!after shot)

**Comment by commy2** [comment]
https://en.wikipedia.org/wiki/Backblast_area

Launcher backblast is a feature in ACE.

**Comment by mickeymen** [comment]
not Back!

**Comment by mickeymen** [comment]
Most likely the cone, which should do damage the back is not stable

**Comment by commy2** [comment]
The AT soldier get's damaged, because the object / wall / whatever behind the player reflects the backblast back to the shooter.
Wiki article says:
>In confined spaces, common in urban warfare, even the operators themselves may be at risk.

Thats what is simulated in ACE.

**Comment by alganthe** [comment]
Note that the ground can also do that, the RPG-42 not being a soft launch launcher means that if you aim too high the ground will act as a "wall" a you'll take the backblast.

**Comment by mickeymen** [comment]
No walls and no any elevations ! Once I have seen this on the Stratis airfield

**Comment by ruPaladin** [comment]
May you post a video?

**Comment by mickeymen** [comment]
"May you post a video?" Not assured. as I said this is a rare occurrence, but I will try

**Comment by Cyruz143** [comment]
Seen this happening a fair amount recently. I think a slope is involved most of the time but it seems even really shallow ones can cause it which seems a bit OTT. Will do some testing when I have the time.

**Comment by VKing6** [comment]
Perhaps backblast should be toned down slightly on balance to remove some of these little more than annoying injuries and keep the proper dangerous stuff like standing behind the tube.

**Comment by mickeymen** [comment]
Yes, backblast should be toned down in the any cases/ But the main task is to understand the reason why damages occur on an empty and flat places of map ,  when in back there are no objects

**Comment by TheGrandVizier** [comment]
I can confirm.
As Zeus, I remote control OPFOR units with RPGs pretty often, both vanilla and modded RPGs.
Once in a while, the AT guy does get wounded and goes unconscious as a result of a backblast against thin air.
Thin air = No obstacle, no slope, nothing around.

**Comment by mickeymen** [comment]
@TheGrandVizier Thank you for your report

**Comment by mickeymen** [comment]
I noticed, that while firing from the RPG-32, when the player receives damages, he sees drops of red blood around the edges of the screen or he sees the pain (pulsating white light), but after this moment, if player open the medical menu(H-button), then the indicators will not show any damages to the body parts of the player. Damages are not exist!
This is strange detail may be can useful for searching reason this problem

**Comment by headedhorseman101** [comment]
>Once in a while, the AT guy does get wounded and goes unconscious as a result of a backblast >against thin air.
>Thin air = No obstacle, no slope, nothing around.

@mickeymen @TheGrandVizier Is the rpg fired at an elevation, like @alganthe said. If the is no slope/obstacles, but you are fine at an upward angle, the ground can reflect said back last even if there is nothing around.

**Comment by mickeymen** [comment]
I never fired an RPG into a flying helicopter. Thus I had no any upward angle. I always observed the problem of directing the shot only horizontally.

PS: even if damages occur(only for adequate cause!), then damage from a RPG jet should not lead to loss of consciousness. 
I think ACE3 team, need to make only superficial damage to the skin of a soldier not more. But in ACE3, we can observe a permanent loss of consciousness, upon adequate reason and for an unknown reason also.

**Comment by jokoho48** [comment]
ever heard of  Overpresse? and please mickeymen please be nicer in your posts and accept what we say.

**Comment by mickeymen** [comment]
jokoho48 ok ;)

Do what you think is right...

**Comment by jokoho48** [comment]
yeah i think its right because you have the explosion and that create a pressure and that if its react to the ears create some kind of damage and pain

**Comment by PabstMirror** [comment]
```
fnc_getDistance.sqf:17","params: _posASL=[1823.41,5729.05,6.66627], _direction=[-0.953255,0.109689,-0.281554], _maxDistance=15"]
fnc_getDistance.sqf:44","while: _interval=7.5, _distance=15, _intersections=0, _terrainIntersect=true"]
fnc_getDistance.sqf:44","while: _interval=3.75, _distance=7.5, _intersections=0, _terrainIntersect=true"]
fnc_getDistance.sqf:44","while: _interval=1.875, _distance=3.75, _intersections=0, _terrainIntersect=false"]
fnc_getDistance.sqf:44","while: _interval=0.9375, _distance=5.625, _intersections=0, _terrainIntersect=true"]
fnc_getDistance.sqf:44","while: _interval=0.46875, _distance=4.6875, _intersections=0, _terrainIntersect=true"]
fnc_getDistance.sqf:44","while: _interval=0.234375, _distance=4.21875, _intersections=0, _terrainIntersect=true"]
fnc_getDistance.sqf:44","while: _interval=0.117188, _distance=3.98438, _intersections=0, _terrainIntersect=false"]
fnc_getDistance.sqf:44","while: _interval=0.0585938, _distance=4.10156, _intersections=0, _terrainIntersect=false"]
fnc_getDistance.sqf:49","while done: _distance=4.16016, _maxDistance=15, _terrainIntersect=false, _lastTerrainIntersect=false"]
```

get distance can fail on the terrainIntersect check, which means shots with low reflection angles aren't getting their effective distance increased.

Should probably just rewrite with `lineIntersectsSurfaces` which would also be faster
