### ISSUE TITLE
FCS for 35 mm AA gun not handling elevation correctly, cant adjust distance for Air-Burst ammo

### ISSUE THREAD

**Issue by JonenKone** [acemod/ACE3#2750]
FCS for the 35 mm Anti-Air Bardelas (Cheetah/Tigris) is not handling elevation correctly, currently you cant adjust distance for Air-Burst ammo without direct line of sight to target.

To replicate:
In Editor, place 35 mm AA unit on map and play as gunner. Also spawn fixed wing flying aerial unit close by.

Try to range and adjust elevation to fixed wing aircraft target against the sky.

**Comment by dvdbrewster** [comment]
I experienced this and had reload ammo type from scroll.  Then  range was adjustable.

**Comment by commy2** [comment]
>I experienced this and had reload ammo type from scroll. Then range was adjustable.

They have 2 magazines. One is ABM the other normal HE.
Can't reproduce. ABM works for me.

**Comment by alganthe** [comment]
Can't reproduce either, are you sure you're using ABM ?

**Comment by JonenKone** [comment]
Strange. Still getting the same issue with all 35 mm muntitions. If i press "zeroing up" it just zeros the gun for a certain distance on a ground target. If I point it at the sky and press zeoring up, then it just zeros to infinity. In Vanilla the zeoring works fine. (sorry for using wrong term, elevation->zeroing)

ACE: Zeored at ground
http://images.akamai.steamusercontent.com/ugc/398925305488664896/E22C525E522C6D829918946D0766F0D3B7020066/

ACE: Zeored at sky
http://images.akamai.steamusercontent.com/ugc/398925305488671545/311840EE2035293DBBA5412AA3AF44BFB113042F/

Vanilla: Zeored at 1500 (upper right corner)
http://images.akamai.steamusercontent.com/ugc/398925305488690176/8C0E3CE318AB41D65EF9B2798FE9CE1728CEF073/

Need to test further with my community.

**Comment by Gwynblade** [comment]
I have this problem as well, however the problem is not ABM. 
I tried to explain with this image http://imgur.com/4jJmsR9

So ABM explodes properly on the given range, but it seems it doesn't work, because the vehicle will lie to you about that range.

No mods used, except latest ACE 3.3.2 and CBA.

**Comment by commy2** [comment]
^ interesting. I'll take a look

**Comment by commy2** [comment]
I checked this and it is not the case.
Please someone with this issue provide a RPT. Otherwise there is nothing I can do.

**Comment by Gwynblade** [comment]
Hm, weird. Here's the RPT: https://www.dropbox.com/s/bwgjhmmxqplfd4w/arma3_2015-11-11_11-19-26.rpt?dl=0
