### ISSUE TITLE
Change Wheel action on front wheels of RHS BTR family are placed near interaction point

### ISSUE THREAD

**Issue by MAD-BUG** [acemod/ACE3#2751]
ACE 3.3.2 (dev RepairAllThePoints)
As said front wheels of BTRs can be normaly removed, but to place a new wheel you need to bring wheel on the other side and find action point near center of btr body.
http://images.akamai.steamusercontent.com/ugc/643245585274857141/4394434030B1A79D4E660CDFAF1CD738DD73421B/

**Comment by PabstMirror** [comment]
When the BTR's wheel takes damage, it apparently goes inside of the vehicle.
![image](https://cloud.githubusercontent.com/assets/9376747/10528100/ce1c1b5a-7359-11e5-80f1-aeb6349a68b6.png)
I had no idea Russian vehicles were so advanced.

**Comment by commy2** [comment]
bravo

**Comment by MAD-BUG** [comment]
wow, thanks for that info.

**Comment by PabstMirror** [comment]
Fixed by SilentSpike's code in #2861

`cursorTarget selectionPosition "wheel_2_1_steering"` = [0,2.38419e-007,-0.116706]
`cursorTarget selectionPosition ["wheel_2_1_steering", "HitPoints"]` = [0.681074,1.39013,-1.17215]
