### ISSUE TITLE
File ace_protection.pbo outdated?

### ISSUE THREAD

**Issue by LindavK1972** [acemod/ACE3#2752]
Hi,

I'm running a Battlezone Altis ACE3 game on my local server.
But as of late, it keeps jumping back to the lobby, because of a ace_protection.pbo file that is outdated. I'm using the Steam Workshop and the ARMA3 launcer as updaters and i am running ACE3 3.3.2.0, ARMA 3 is at 1.52.132676. What is wrong?

**Comment by PabstMirror** [comment]
Delete your @ace folder and reinstall
the pbo is not in the current release, so it must be from an old version

**Comment by commy2** [comment]
Same as :
https://github.com/acemod/ACE3/issues/2694
https://github.com/acemod/ACE3/issues/2502

**Comment by LindavK1972** [comment]
Worked...

However, don't use the Workshop version of ACE 3. Download the version on the site, unsubscribe the Workshop one...or it will overwrite the PBO's with old versions.
