### ISSUE TITLE
Disable HitEffect of MedicalSystem?

### ISSUE THREAD

**Issue by floepdi** [acemod/ACE3#2763]
ACE3 Version: 3.3.2
Stable 1.52

Mods:

@CBA_A3
@ace
@life_server

Placed ACE3 Modules:
Medical settings

Description:
Hey ACE3-Team,
sorry for asking, everytime player get hit by bullets, the white flash or blood effect applies and it destroys our hud of altis life. It would be great, if there is a possibility to disable that, or let not destroy other huds.  

Steps to reproduce:
Should be reproducable with any Altis Life HUD.

Where did the issue occur?
on Server

RPT log file:
Not needed

**Comment by commy2** [comment]
It doesn't destroy HUDs for no reason. My asumption is the following: Your HUD probably uses a `cutRSC` or `cutTitleText` with an index that was not generated by `BIS_fnc_RSCLayer`.
Nothing we can do about that then.
Every control that is used has to generate it's layer / id with that function to be compatible with other controls.

**Comment by floepdi** [comment]
Okay, thank you!
so there is no way to disable the effect?

**Comment by BaerMitUmlaut** [comment]
No, because then you would have no visual indicator if you are hurt or if you are bleeding, and in a firefight you would have to open your interaction menu every few seconds to check if you are still OK.
