### ISSUE TITLE
canTreat not working for disabled items

### ISSUE THREAD

**Issue by FettLi** [acemod/ACE3#2765]
ACE3 Version: 3.3.2

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
In missionConfigFile >> "ACE_Settings":
class ace_medical_useLocation_PAK {
        typeName = "SCALAR";
        value = 4;
        values[] = {"Anywhere", "Medical vehicles", "Medical facility", "vehicle & facility", "Disabled"};
        force = 1;
 };

**Description:**
Let's assume that canTreat doesn't evaluate to false until line 78 in fnc_canTreat.sqf.
Then, the use location is checked. As _return is initialized to true, it won't be changed, if ace_medical_useLocation_PAK ist 4.
So: the item will be able to be used allthough it should be disabled.

**Comment by FettLi** [comment]
Nice to see, that this got fixed that fast. But I have to say: the commit messa #2767 seems to be a bit specific. Is the error fixed for any item or just for the pak?

**Comment by PabstMirror** [comment]
PAK and Surgical Kit are the only Treatments that were effected because they are the only ones that have `treatmentLocations[]` set to something besides `{"All"}`
