### ISSUE TITLE
SLAM Mine after deploying slowly falls on the ground.

### ISSUE THREAD

**Issue by ghost** [acemod/ACE3#2770]
ACE3 Version: 3.3.2
Stable Version 1.52

**Mods:**
- `@CBA_A3`
- `@ace`
- `@DragonFyre`

**Placed ACE3 Modules:**
None

**Description:**
SLAM Mine after laying on the ground slowly falls on the ground. While Claymore is installed without such  glitches. Such physics is not from our planet. Please fix this nonsense.

**Steps to reproduce:**
Put the SLAM mine on the ground

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by CorruptedHeart** [comment]
It's a known issue, there's nothing that can really be done about it without access to the actual model I believe.

**Comment by mickeymen** [comment]
STILL NOT FIXED (ACE3 v 3.4.1). Not possible without BIS?

**Comment by SilentSpike** [comment]
We're aware :smile: It's what the issue tracker is here for

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 340 days without any activity.
