### ISSUE TITLE
"No injures on this body part"

### ISSUE THREAD

**Issue by Gh0st0fy0urp4st** [acemod/ACE3#2772]
There's a bug I have encountered with the advanced medical module on Ace 3. I was playing around with it earlier, I shot a civilian in the leg and ran over to him, his leg was covered in visible blood. When i pulled up the interaction menu to heal him, I went to his left leg, it said "No injured on this body part" the cross symbol on his leg also did not change color. I repeated this process over and over again to make sure it wasn't the Arma 3 engine glitching out, no success. I tried to reinstall Ace 3, but it didn't do anything. The bug isn't in the basic medical system, it still works. Does anybody have a solution to this?

**Comment by Glowbal** [comment]
Hi @Gh0st0fy0urp4st, we always like to support our users and resolve any issues they have found. But please try to use respectful language, and keep this area positive for all.

With that said, please take a look at our post on [http://ace3mod.com/wiki/user/how-to-report-an-issue.html](how to report an issue). Your bug report is lacking details that would help us diagnose the problem and fix if need be. Without the details listed in the previously linked post, this process would become a guess game.

Therefor please edit your bug report to contain the details it is currently lacking.

**Comment by Gh0st0fy0urp4st** [comment]
Sorry about my language, i was angry last night. I opened up the link but it says that the page couldn't be found.

**Comment by jonpas** [comment]
Try this: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by Gwynblade** [comment]
@Gh0st0fy0urp4st   ...Does anybody have a solution to this?

This happens when you use advanced medical system, but enable it only for players, and not the AI.

Cross symbol or medical menu will not change color on injured AI (will work on players), but you can still treat them (AI), just needs more bandages since you're pretty much guesing what to treat.

Anyway, enabling adv. medical for AI fixes this, just not sure how much of an performance impact it has?

**Comment by PabstMirror** [comment]
If advanced isn't enabled for AI, they won't get any `QGVAR(openWounds)` so nothing shows up.

I think c326bc2f87b6ce0ebaa31a3b484fa557547915d9 might fix

**Comment by PabstMirror** [comment]
For now, if you are planning to heal AI you probably want to enable advanced for AI.  Or manually enable per unit, EG to enable advanced medical for civilians put this in description.ext:
```
class Extended_InitPost_EventHandlers {
    class CAManBase {
        class civMedical {
            init = "if (side (_this select 0) == civilian) then {(_this select 0) setVariable ['Ace_medical_enableMedical', true];};";
        };
    };
};
```
