### ISSUE TITLE
ace_spectator: Vision mode can't be changed in External camera

### ISSUE THREAD

**Issue by VKing6** [acemod/ACE3#2774]
ACE3 Version: 3.3.2.0 stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
It's not possible to change the camera mode (thermal etc) in the External camera. It's possible to set it in Free camera and the change will stick when returning to External.

**Steps to reproduce:**
1. Spectate someone.
2. Attempt to change vision mode in External camera.
3. Change to Free camera, change vision mode, return to External camera.

**Where did the issue occur?**
Multiplayer, listen server
`[[0,1,2,3,4,5,6,7]] call ace_spectator_fnc_updateVisionModes` had been executed.

Reading the description of `fnc_updateVisionModes`, I'm not entirely sure if this bug is about not being able to change the mode in External camera, or if the vision modes shouldn't be retained when switching from Free camera.

**Comment by SilentSpike** [comment]
Already fixed in #2760 :smile:

**Comment by VKing6** [comment]
Promise me you'll only use your prescience for good.

**Comment by commy2** [comment]
Close then?

**Comment by SilentSpike** [comment]
Will close when I merge the PR, leave open for tracking purposes :+1:
