### ISSUE TITLE
Dragging - Crouch breaks animations

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#278]
Drag object or man.
Press X (crouch toggle)
Object is dropped and player can interact.

But animation becomes glitched and it shows as still dragging
animationState player = "helper_switchtocarryrfl"

Pressing any movement key does a 10+ second animation and then the player in stuck with arm at side: "acinpercmstpsraswrfldnon"

**Comment by bux578** [comment]
How critical is that bug @PabstMirror

**Comment by PabstMirror** [comment]
Still getting stuck in this animation:
![image](https://cloud.githubusercontent.com/assets/9376747/7378937/a9f3def8-edb6-11e4-998e-2fab19fe6ff3.png)

Cannot shoot or change stance.

Will look into either blocking stance change or detecting the bad animation and reseting.

**Comment by commy2** [comment]
Never could reroduce the issue. Probably could be changed by tweaking the animations config.
For some reason it never happens to me though.

**Comment by dixon13** [comment]
Should this be closed since it was fixed in #905 ?
