### ISSUE TITLE
Can't handcuff own side

### ISSUE THREAD

**Issue by BroderTuck** [acemod/ACE3#2782]
ACE3 Version: 3.3.2 stable

Mods:
* @CBA_A3
* @ACE3
* @ALiVE
* @dac_a3

Placed ACE3 Modules:
* ace_captives_moduleSettings

Description:
I'm trying to handcuff a helicopter pilot. I've only tested this in the editor.
Can handcuff own side: Yes. Allow surrendering: Yes. Require surrendering: No. 
I've tried linking the module to just the pilot, and both the player and the pilot.
I've tried putting "[this, false] call ACE_captives_fnc_setHandcuffed;" and "[this, true] call ACE_captives_fnc_setHandcuffed;" and neither in the pilots init field.

Steps to reproduce:
1. Place one pilot and one player character from the same faction.
2. Place the captives module and link it with either just the pilot or both characters.
3. Put "[this, false] call ACE_captives_fnc_setHandcuffed;", or "[this, true] call ACE_captives_fnc_setHandcuffed;", or neither in the pilots init field.
4.Put ACE cable-ties in the players inventory.
5. Preview.
6. If you put "[this, true] call ACE_captives_fnc_setHandcuffed;" in the pilots init field, release him.
7. No option to put cable-ties on the pilot with ACE interaction.

**Comment by bux578** [comment]
Hi, thanks for your report.

I was able to handcuff soldiers from my own side with the module settings you've provided. On a side note: you don't need to sync the module to the units.

If I don't add anything to the init line the behavior works as intended.

**Comment by bux578** [comment]
This might be related: https://youtu.be/YotT3pn7Byo

**Comment by BroderTuck** [comment]
Yeah, that happened as well. And while it is possible to handcuff him without the init line, I needed him to be a captive from mission start. But now I've found out that surrendering does what I wanted better.
