### ISSUE TITLE
AI-squad of player, never reports about his injury. (all AI-medicine destroyed)

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2786]
ACE3 Version: 3.3.2
Stable 1.52

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
Basic and Advanced Medical modules

**Description:**
Hi ACE team! 
In ACE3 the subordinate AI-squad of player, not reports about his injury and this is a last blob, which destroys all AI-medicine in the game. As a result, the player can only watch as his subordinates periodically fall dead, because during fight losing a lot of blood. How can the player know that his subordinates wounded? Or how the player has to treat them if all AI-medics are impotent?
AI does not report about injuries and there is no way to understand wounded bot or not. The player can only occasionally see, when the blood stained the uniform of the bot. But during combat or at night it is impossible to see this. 

Even if the player finds a wounded soldier in his squad, then he needs to treat injured only own hands, because the medic in the ACE3 turns in useless unit. 
He not able treat wounded independently also the player cannot order to treat another soldier. Unfortunately, AI-medicine at the ACE was completely destroyed and it looks very bad.
Please return the reports of injuries and ability medic to treat other soldiers or find any way. 
AI-Medicine should work, especially in mod, where a unit can die, if left unattended by a doctor.

**Steps to reproduce:**
Play in ACE3 with advanced medical

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by BaerMitUmlaut** [comment]
This is a feature requests and should go into #414 (AI treating each other was already requested there btw).

**Comment by mickeymen** [comment]
"FeautureRequest" lable implies low priority. This is sad to me/

**Comment by BaerMitUmlaut** [comment]
No, feature request implies feature request, which this is.

**Comment by mickeymen** [comment]
ACE team, please restore all the interaction between the player and the AI, which was destroyed in ACE3. I mean the special orders in the action menu (6) - "treatment" and "set mines/charge".
Also in the ACE3 the AI -unit (medic in the enemy squad) ceased to treat allied soldiers, as we see it in the vanilla game.

**Comment by commy2** [comment]
You could delete `ace_medical.pbo` and `ace_explosives.pbo`. Then you could still command AIs around and it would also get rid of the unconsciousness transition you don't like.

**Comment by mickeymen** [comment]
@commy2 I can't delete it, because I like ACE self-treatment, damage model (for player) and the availability of various medical supplies for the player. This is all very cool, but AI is not supported. This is sad not only for me, but and for other players. I almost don't use multiplayer, I'm trying to create a missions with lots of AI-units. In this case I face such problems in each mission
