### ISSUE TITLE
Medical menu - wrong interaction target in vehicles

### ISSUE THREAD

**Issue by SzwedzikPL** [acemod/ACE3#2787]

**Comment by PabstMirror** [comment]
3,3.2 release or master?

**Comment by SzwedzikPL** [comment]
Latest master. Global was informed about this bug before. Im only adding ticket.

**Comment by Glowbal** [comment]
This is probably the place to look; https://github.com/acemod/ACE3/blob/master/addons/medical_menu/CfgVehicles.hpp#L63-L64

I don't have the opportunity to test this though. 

@SzwedzikPL you mentioned it only happened when using the medical menu on other people inside vehicles and opened through the interaction menu, right? Could you please post the screenshot again.

**Comment by SzwedzikPL** [comment]
@Glowbal exactly

http://i.imgur.com/b737kM9.jpg

**Comment by jonpas** [comment]
So the interaction target is actually the vehicle in this screenshot? I was healing a pilot inside a little bird just last week with the medical menu and it worked fine.

**Comment by PabstMirror** [comment]
Has anyone seen this after 3.4?
I can't seem to reproduce this issue, so if anyone can find some steps to take it would be helpful.

**Comment by Glowbal** [comment]
No response. If this occures again, please create a new ticket
