### ISSUE TITLE
Ace 3.3.2, is now conflicting with the newly updated CUP Weapons packs.

### ISSUE THREAD

**Issue by FriskyLB** [acemod/ACE3#2788]
ACE3 Version: 3.3.2 stable (Github file)

Mods:

@CBA_A3
@ace
@CUP_Weapons
+ many more but removing either ace and Cup usually fixes the problem
 but I require both to be functioning at the same time.

Description: 

Whenever I have ace and CUP weapons enabled at the same time it cause a error when entering scenarios and editor .etc. The error says this: a small window appears with ACE ERROR written at the top and in the window contains this line of text: "ace_cup_weapon_ace_compat.pbo is outdated" after clicking close it sends me back to the briefing screen and if i were to restart it would show up again. I searched through the CUP and ace files as thoroughly as I could yet I could find no pbo file named this.

**Comment by Przemro** [comment]
Well you have in @ACE>optionals this ace_cup_weapon_ace_compat.pbo but even if you use it, it says that is outdated.

**Comment by alganthe** [comment]
Remove the ACE optionals pbo, it's outdated CUP has native support since last month.

**Comment by FriskyLB** [comment]
i cant seem to find it. Only ace_compat_cup

**Comment by alganthe** [comment]
That's what I meant

**Comment by acidburn101** [comment]
I didnt used the ace_compat_cup while starting arma with cba3, ace3, cup weapons/units. It still throws me the error "ace_weapon_compat_cup" outdated and kicks me out. I have tested it in multiplayer and singleplayer.
I have also added the ace_compat_cup to a seperate mod ace_cup_comp to see if it works with them but still throws same error.

**Comment by acidburn101** [comment]
Is ace relying to have the ace_compat_cup installed when using CUP Weapon Pack? Because according to @alganthe comment, CUP has allready an ACE compat in their mod included and is now its conflicting. Could that be possible?

**Comment by FriskyLB** [comment]
maybe delete the compat from ace optional folder

im going to try that now and see what happens.

**Comment by FriskyLB** [comment]
nope, still nothing

**Comment by commy2** [comment]
Upload the RPT.

**Comment by FriskyLB** [comment]
Where do I upload it because i need permissions to upload it here

**Comment by commy2** [comment]
pastebin or github gist

**Comment by FriskyLB** [comment]
https://gist.github.com/FriskyLB/b81719ba0c0784687a13

**Comment by jokoho48** [comment]
`E:\Program Files (x86)\Steam\SteamApps\common\Arma 3\@CUP_Weapons\addons\ace_cup_weapons_compact.pbo`
there is the wrong file

**Comment by FriskyLB** [comment]
THANKS !!!

**Comment by commy2** [comment]
@jokoho48 
Do you know where
`ace_cup_weapons_compact.pbo`
is from?

**Comment by FriskyLB** [comment]
I found: CUP_weapons_ACE_compat.pbo

**Comment by commy2** [comment]
Wrong file. It's `E:\Program Files (x86)\Steam\SteamApps\common\Arma 3\@CUP_Weapons\addons\ace_cup_weapons_compact.pbo` according to @jokoho48

**Comment by jokoho48** [comment]
it look like from a Japanese comunity :D this are the only result

**Comment by FriskyLB** [comment]
kk

will try now

**Comment by jokoho48** [comment]
@FriskyLB that mean delete the file and then its work

**Comment by commy2** [comment]
Weird that it's called compaCt and not compat

**Comment by FriskyLB** [comment]
found it out. That was something i accidently dropped in there

You actually need to delete: CUP_weapons_ACE_compat.pbo and it's bisign

**Comment by commy2** [comment]
good

**Comment by CarpetBurns** [comment]
I know this is closed but I hope someone gets this. I have the same issue "ace_cup_weapon_ace_compat.pbo is outdated". I have deleted cup_weapons_ace_compat.pbo as ace_cup_weapon_ace_compat.pbo doesn't exist anywhere on my system.
I have also deleted the BISIGN file of the same name but I still have the same problem.

I then removed ace_compact_cup.bpo and BISIGN files as well and still have the same problem.

Any ideas?

**Comment by jokoho48** [comment]
the only reason is that you load somewhere this PBO :D

**Comment by acidburn101** [comment]
@CarpetBurns 
Delete in the CUP Folder CUP_weapons_ACE_compat.pbo and it's bisign. 
Add the ACE CUP comp optionals to your ACE/addons Folder or run it as a seperate Mod (like @ACE_comp/addons).

**Comment by CarpetBurns** [comment]
Thank you very much acidburn. I have been stressing over this for days, tried every combination before I realised it was Ace and cup that caused the issue. Re-downloaded and did all sorts.
Thank you very much, I'm a happy man now. Just need to fix an issue with my server now.

It doesn't rain it pours.

Thanks again.

**Comment by cych** [comment]
hello, i have a question :  ACE 3 folder contains a compatibility file for @CUP.  

Is this file allow to port ACE 2 feature to the @CUP addons on A3 ?

**Comment by commy2** [comment]
No. ACE2 is dead.

**Comment by cych** [comment]
Isnt't ACE2 features supposed to be ported to ACE3  ?
