### ISSUE TITLE
Atragmx gun data not available and existing not correct.

### ISSUE THREAD

**Issue by TyrDaishi** [acemod/ACE3#2790]
ACE3 Version: 3.3.2

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
advanced ballistics
advanced medical
ace weather

**Description:**

Those are two major issues for me for some time now when it comes to the usability of the ab modul in combination with atragmx and the kestrel 4500.
1. Existing gundata seems to be wrong. For example all .338 are inaccurate on very short or very long distances. Same applys for other calibers. quadrochecked all values and made sure that all necessary modules are infact added to the testscenario.
2. No explanation on how to add custom rifledata. The values in question cannot be obtained from the ace files or any information resource. If those values can be calculated from data that can be found in the game or gamefiles there is no explanation how to do so. Please advise. 

**Steps to reproduce:**
open any scenario using ace and said modules, use rifles with mildots vanilla, vanilla+ace3 scopes, custom mod rifles+vanilla,costum or ace scopes. 

**Where did the issue occur?**
multiplayer

**RPT log file:**

last start where the error occured (with 15 mods active, but problem also happens with only cba+ace3)
https://drive.google.com/file/d/0B3UwVAEkxk4TS0dpMHpkSHozQWM/view?usp=sharing

sidenote: if someone is willing to explain to me how to get the gundata and where I can normally find this information I could create a costum file with correct data and add all the data for the big mods (bwmod rhs 3cb) for everyone.

**Comment by DanielLarusso** [comment]
Also some gun data are missing. e.g. 7.62 x 51 NATO etc.

**Comment by arv187** [comment]
this issue still since Oct 2015
What testing you need? if we can help you...

**Comment by J3aLeiNe** [comment]
@Glowbal , i think that this issue is a little bit obsolete in my opinion because :  
 - 1/ The existing gundata is correct, i checked it during this PR https://github.com/acemod/ACE3/commit/7220d0ee5da42a5dc3773b76c490396607cbeb90,                  the 7.62x51 NATO is not missing, it's the standard "7.62x51mm M80" in the GunList.

 - 2/ Outdated in my opinion, there are all informations and documentations in the "extras" folder.

Actually, the AtragMx's GunList is saved in the *.vars.Arma3Profile. For each update, the player must reset (delete) this file, i'm not sure it's a good idea, isn't it ?

**Comment by ulteq** [comment]
> For each update of the atragmx/XEH_postInit.sqf, the player must reset (delete) his .vars.profil

It's enough to empty the AtragMX gun list in-game. It will automatically repopulate itself with the latest data once you restart the mission.

> i'm not sure it's a good idea

The reason why we don't overwrite the gun list forcefully is to preserve peoples custom profile entries.

**Comment by ulteq** [comment]
ACE3 v3.9.0 will address several related issues. It will:
* Update the default gun list in the ATragMX
* Fix the scope zeroing issue
* Expand the range card output (actual bore height will be shown)

**Comment by Glowbal** [comment]
Ok, should be fixed with 3.9.0
