### ISSUE TITLE
Question: [Advanced Medical] Revive State

### ISSUE THREAD

**Issue by headedhorseman101** [acemod/ACE3#2791]
What exactly is the revive state? 
I am slightly confused on how it and car work and what the purpose of CPR is. I have read the documents many times, so no links to the feature doc please.
>Incorrect. PAK is required for units in revive state, which isn't the equivalent of cardiac arrest.

Also can someone clarify how to identify if someone is in the revive state? Is revive state a synonym for unconscious?

**Comment by Th3Cr0w** [comment]
Revive state: When enabled, player who receive damage beyond the point of dying enter the revive state instead.
Identifying the revive state: Personally I try CPR about 3-4 times. If heart rate does not stabilises he is in revive state (if blood loss and pain is taken care of).
CPR only helps if the heart rate drops too low / high and causes a cardiac arrest (either blood loss or medical od or pain or sprinting)

**Comment by headedhorseman101** [comment]
So does the revive state have the same symptoms as hypovolemic shock?

**Comment by Th3Cr0w** [comment]
Yes, afaik.

**Comment by Meiestrix** [comment]
I have a question to the revive system.
Did I unterstrand the code correct that your revive time does not increase with CPR when you are in revive state?
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatmentAdvanced_CPRLocal.sqf
I thought CPR is also a way to hold somebody alive when they have no pulse.

**Comment by Glowbal** [comment]
It does; https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatmentAdvanced_CPRLocal.sqf#L23

**Comment by Meiestrix** [comment]
Correct me if i am wrong, but when someone is in revive state, only line 20 get executed, because it says if inReviveState=false.

**Comment by Glowbal** [comment]
`false` is the default value, if the `inReviveState` variable is not set (`nil`).
