### ISSUE TITLE
several issues conserning the adv medic

### ISSUE THREAD

**Issue by UrukCan** [acemod/ACE3#2802]
1. I tried to res a guy the other day and right before he died i was able to finish a whole cpr and checked his heartrate, which was 40. Now i looked through the your functions and found this in the cpr function called fnc_treatmentAdvanced_CPRLocal.sqf
if (GVAR(level) > 1 && {(random 1) >= 0.6}) then {
    _target setvariable [QGVAR(inCardiacArrest), nil,true];
    _target setvariable [QGVAR(heartRate), 40];
    _target setvariable [QGVAR(bloodPressure), [50,70]];
};
I think that it sould be set to false but that's just my 2 cents...

2. I used several morphine/epi-pens during a mission bu none of them got used up. I was playing as surgeon. 

3. Even after enabling RemoveBloodStains some people are still forced to walk. Only way of fixing that is to use the PAK. 

4. When using the PAK it sometimes takes 5+ (max was 9) minutes to treat a patient, even though they just had 1 leg wound or so. Maybe its intentional? I don't know...

5. Both my heart rate and bloodpressure were 120+ after using 2-3 morph in a timespan of 15 min. Didn't use a single epi-pen. Got shot several times and suffered a lot of wound/lost a lot of blood. Question: why?

6. Medics and surgeons can't use saline bags on themselves. Intentional?

7. people dont wake up anymore even though they have a heart rate of 60+, blood pressure 100+, not in pain, no bleeding, more than enough blood in the system. Used to be easier, now i have to PAK them. (Revive is off btw)

**Comment by UrukCan** [comment]
7. people dont wake up anymore even though they have a heart rate of 60+, blood pressure 100+, not in pain, no bleeding, more than enough blood in the system. Used to be easier, now i have to PAK them. (Revive is off btw)
(doesn't want to update my fist post...)

**Comment by BaerMitUmlaut** [comment]
1. Doesn't reall matter if you use getVariable with a default return value, which we do.
2. You use the equipment of the units you treat first. If they had morphine and epinephrine on them, you used theirs and not yours.
3. Known bug that has already been fixed for the next version.
4. Treatment time for the PAK depends on unit damage: https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatmentAdvanced_fullHealTreatmentTime.sqf
5. Heart rate increases with blood loss because the heart has to compensate for the lost blood.
6. Yes. It's hard to give yourself and infusion.
7. Could be caused by various things, hard to say without having all the information needed.

**Comment by headedhorseman101** [comment]
Thank you for your feedback, but please use [this](http://ace3mod.com/wiki/user/how-to-report-an-issue.html) to format bug reports.

**Comment by UrukCan** [comment]
ACE3 Version: 3.3.2 stable

**Mods:**
*@ace
*@ALiVE
*@allinarmaterrainpack
*@bCombat
*@CBA_a3
*@Epoch
*@extras
*@k_mnp
*@MapBuilder
*@maps
*@rhs_afrf3
*@rhs_usf3
*@task_force_radio

**Placed ACE3 Modules:**
pretty much all of them

**Description:**
people dont wake up anymore even though they have a heart rate of 60+, blood pressure 100+, not in pain, no bleeding, more than enough blood in the system. Used to be easier, now i have to PAK them. (Revive is off btw)

**Steps to reproduce:**
Well, try to get somebody to loose a lot of blood and get unconscious and then try to stablize him. Sometimes it works, sometimes not. 

**Where did the issue occur?**
multiple times

**RPT log file:**
sry, don't have 'em anymore...

**Comment by alganthe** [comment]
Little reminder about reporting issues.

![read this](http://puu.sh/l4gl6/469ad45b67.png)

**Comment by UrukCan** [comment]
AI stuff:
*@ALiVE
*@bCombat
*@k_mnp
additional maps:
*@allinarmaterrainpack
*@maps
additional weapons:
*@rhs_afrf3
*@rhs_usf3
communication:
*@task_force_radio
were disabled (sry forgot that):
*@Epoch
*@extras
*@MapBuilder

it's definetly ace...
