### ISSUE TITLE
Ace 3.3.2, is now conflicting with the newly updated CUP Weapons packs

### ISSUE THREAD

**Issue by CarpetBurns** [acemod/ACE3#2804]
I have an issue using Ace 3 and cup together. When I try I get an error. Ace Error "ace_cup_weapon_ace_compat.pbo is outdated". 
This file does not exist on my system. I have deleted cup_weapons_ace_compat.pbo and deleted the BISIGN file of the same name but I still have the same problem.

I then removed ace_compact_cup.bpo and BISIGN files from the @ACE3 optionals folder as well and still have the same problem.

Any ideas?

**Comment by jokoho48** [comment]
#2788
