### ISSUE TITLE
Can't find the add-on in Configure Add-on menu

### ISSUE THREAD

**Issue by ShizNick** [acemod/ACE3#2806]
Hello All,

So I've tried to install AC3's latest version and all seems to have gone well however, when I add-on in the button configuration ment and click on Add-on Configuration, I do not see ACE 3 or any add-on for that matter? I've tried looking for issue in Google and have come up empty handed, any help would be greatly appreciated.  :-) 

Thanks in advance.

**Comment by PabstMirror** [comment]
I don't think that you can turn mods on and off at runtime any more.
If you are using the Launcher, add it in the mods tab.
Otherise just add it to the command line like this:
`-mod=@CBA_A3;@ace;`

**Comment by ShizNick** [comment]
I did run it from the vanilla launcher via Mods tab.

**Comment by PabstMirror** [comment]
So it looks like this:

**Comment by PabstMirror** [comment]
![image](https://cloud.githubusercontent.com/assets/9376747/10861981/b4f308da-7f63-11e5-969d-caba36502622.png)
???

Also please post rpt: (%localappdata%/Arma 3/)

**Comment by ShizNick** [comment]
It does, although I am running BlastCore Phoenix as well as the needed HopeCore 4.1 and 4.2.
What is rpt: ?

**Comment by PabstMirror** [comment]
Hit WindowsKey+R and type in %localappdata%/Arma 3/
That should take you to something like C:\Users\yourname\AppData\Local\Arma 3\
Look for the most recent file and upload it at https://gist.github.com/ and post the link back here

**Comment by ShizNick** [comment]
https://gist.github.com/ShizNick/91e97b18cdeec68c3cf7

**Comment by ShizNick** [comment]
Nvm, I'm managed to fix it. Thank You so so much for the speedy help anyhow. I do appreciate it a ton. :)
Perhaps that one error you can tell me how to fix though. No entry
'config.bin/CfgLights/FireballLight.Position'

**Comment by PabstMirror** [comment]
`No entry
'config.bin/CfgLights/FireballLight.Position'`

It's going to be from a conflicting mod.  It should't be from CBA or ACE.
You can try removing mods one at a time until it goes away.

**Comment by ShizNick** [comment]
Oh okay, thanks again for the help.

**Comment by xiadaxiaogao** [comment]
@ShizNick I have same problem here. How did you managed to fix it???? Please
