### ISSUE TITLE
ACE breaks the fire system at Abrams

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#2808]
https://youtu.be/wn-B7IUZ-h0

All classes Abrams,T72, T80, T90 (RHS)

**Comment by TheMagnetar** [comment]
If I am not mistaken RHS has its own FCS hardcoded into each of them...

**Comment by Kartaviy** [comment]
https://youtu.be/97Xt7_WtXb4

**Comment by commy2** [comment]
Since these vehicles use RHS' FCS and not ours, there is nothing we can do.
