### ISSUE TITLE
Map flashlight stays floating after forced disconnect/kick

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#2810]
ACE3 Version: 3.3.2 (stable)

**Mods:**
* `@cba_a3`
* `@ace3`

**Placed ACE3 Modules:**
N/A

**Description:**
Map flashlight emitter doesn't get deleted when a player is disconnected/kicked from the game.
http://images.akamai.steamusercontent.com/ugc/583574158732819225/DDB70630BCD4F6634261DFEE569B349569AE142A/

**Steps to reproduce:**
* Join a server
* Turn on map flashlight
* Get kicked/disconnected (without leaving map view somehow)
* Rejoin and look at the floating white light

**Where did the issue occur?**
Multiplayer - Dedicated

**RPT log file:**
N/A

**Comment by Cuel** [comment]
Maybe same solution as https://github.com/acemod/ACE3/issues/2592

**Comment by jonpas** [comment]
I think @voiperr wanted to try another solution for flashlight light emitting.
