### ISSUE TITLE
Diver Drown

### ISSUE THREAD

**Issue by CDTCR** [acemod/ACE3#2811]
Diver keeps drowning and he has all the needed diving gear.

**Comment by alganthe** [comment]
In case you didn't saw the giant warning before finishing creating the issue:
https://github.com/acemod/ACE3/blob/master/CONTRIBUTING.md

**Comment by PabstMirror** [comment]
@CDTCR - We need more to go on, please look at http://ace3mod.com/wiki/user/how-to-report-an-issue.html - but I doubt this is an ACE issue.

All you need to stay alive underwater is a rebreather vest, I tested `V_RebreatherB` in both basic and advanced medical and never took any damage or downed.

ACE does not touch any of the "Rebreather" vests.

Please try with just CBA and ACE and see if you can reproduce.
