### ISSUE TITLE
Using ace medical turns of a weapon flashlight

### ISSUE THREAD

**Issue by MysticalPony** [acemod/ACE3#2812]
Using a ace medical action such as bandaging yourself will turn of a weapon flashlight. I think this may be caused by the animation played for the medical action.

**Comment by headedhorseman101** [comment]
Thank you for your feedback @MysticalPony, but please use the [how to report an issue page](http:\\www.ace3mod.com/wiki/user/how-to-report-an-issue.html) when formatting this and future bug reports.

**Comment by PabstMirror** [comment]
It's because doing `IRLaserOn` or `GunLightOn` resets the firemode,
and `SwitchWeapon` resets the flashlight.

http://feedback.arma3.com/view.php?id=22954

Tagging for #210

**Comment by Ghost77788** [comment]
Sorry just to add to this its for any self interaction or interaction menu selection.
Even custom actions added to the menu's. Maybe a parameter that checks if the light or laser is on and if it is it turns it back on.

Dont know if this is already fixed.

If it is sorry for the uselessness of the post.

**Comment by commy2** [comment]
>and if it is it turns it back on.
That's exactly thaat part that is not possible atm.

**Comment by Ghost77788** [comment]
alright my apologies for the post.

anyway great work on the mod anyways
