### ISSUE TITLE
Player cannot crawl after falls to the ground (if suddenly was wounded during fast movement) 

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2815]
ACE3 Version: 3.3.2
Stable 1.52

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
Medical and Advanced Medical

**Description:**
In ACE3 when the player runs, and at this moment gets bullet-hit, then he falls to one side of the body(side position for firing lying down) At this moment, the player cannot exit from this position, if not go into a сrouch or full erect stance. 
At the this moment Why a player cannot crawl on the ground, it is not clear to me. This detail is more like a bug, than the initial idea. If the player falls from being hit by a bullet and not die/lose consciousness, it is likely the first thing he can do is crawl on the ground, but in any case not to stand up on his feet!  Player should crawl but not should immediately to his feet.
Please fix this nonsense.

**Steps to reproduce:**
Play in ACE3 and get bullet hit at the maximal speed movement.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by bux578** [comment]
That's not an error. It's moving you into another stance. Default bind <kbd>Ctrl</kbd> + <kbd>A</kbd> or <kbd>Ctrl</kbd> + <kbd>D</kbd> moves you into standard prone position.

**Comment by bux578** [comment]
https://youtu.be/10Fcf8Tt8NE

**Comment by mickeymen** [comment]
My friend if you like the "default", then there's no sense in doing the mod. Please note, I propose to improve ARMA and you suggest to leave it as is by default.
If the bullet makes you automatically fall to the ground, meaning the player should automatically leave their position (pressing only "W" button), without additional command (Ctrl+A, Ctrl+D)

**Comment by bux578** [comment]
This does not work, my friend!

**Comment by PabstMirror** [comment]
You can disable via settings:
```
class ACE_Settings {
    class ace_hitreactions_minDamageToTrigger {
        //Minimum mamage needed to trigger falling down while moving. Set to -1 to disable completely.
        typeName = "SCALAR";
        value = -1;
    };
};
```

**Comment by mickeymen** [comment]
"This does not work" 
It may be worth a try? 

PS: Thanks for your job, in any case

**Comment by mickeymen** [comment]
"You can disable via settings"  - I can disable fall after hit? Hmm. I like this ACE feature, just do not like the fact that after the fall the player must press the special command
