### ISSUE TITLE
Script error handleNetEvent

### ISSUE THREAD

**Issue by Glowbal** [acemod/ACE3#2820]
Version: 8f6e9be6

```
21:50:38 Performance warning: SimpleSerialization::Read 'ACEc' is using type of ,'TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
21:50:38 Error in expression <ACE_player}) then {
if (isDedicated && {local _x} && {!_serverFlagged}) then {
_>
21:50:38   Error position: <local _x} && {!_serverFlagged}) then {
_>
21:50:38   Error local: Type Text, expected Object,Group
21:50:38 File z\ace\addons\common\functions\fnc__handleNetEvent.sqf, line 57
```

Running default ACE settings with advanced medical enabled (`ace_medical_level = 2`). Occured in multiplayer, with 60+ players.

This script error might be caused by an incorrect event call. Maybe a local event using text instead of an object for the target?

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/commit/f48636e63395a8cfa0150446ec522016b4554429#diff-b895d761960809ce11f4d98a410188aaR31

**Comment by Glowbal** [comment]
Nice one @PabstMirror :+1:
