### ISSUE TITLE
[Question] Get/set weapon temperature

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#2823]
I work on this mod: https://www.youtube.com/watch?v=4mo_ww0040k
To handle it right I need to get temperature before grip (weapon) switch and set it back after. Is it possible to do?

**Comment by Glowbal** [comment]
This might help:

```sqf
_overheat = unit getvariable ["ace_overheating_weaponClassname", [0, 0]];
_overheat params ["_temperature", "_time"];
```

Replace `weaponClassname` with your weapons classname. 

reference: https://github.com/acemod/ACE3/blob/master/addons/overheating/functions/fnc_overheat.sqf#L30

**Comment by ruPaladin** [comment]
Thank you, Glowbal! I got it! Works great now.
