### ISSUE TITLE
[Hearing] Earplugs not removed on respawn *Different from #2835*

### ISSUE THREAD

**Issue by headedhorseman101** [acemod/ACE3#2837]
**ACE Version:** 3.3.2 (but noticed in previous versions going back to 3.1.0)

**Mods:**
* `@ace`
* `@CBA_A3`

**Modules:**
Ace_Respawn
    `SavePreDeathGear: false`
    `RemoveDeadBodiesDisconnected: true`
    `RemoveBodyTimer: 30`

**Steps to reproduce:*
1. Spawn as any unit as Player
2. Respawn at a preset point (I made a simple script)
3. Die (somehow; method unimportant)
4. On respawn, check if earplugs still in

**Game Type:**  Both Singleplayer Editor and Dedicated Server

**RPT:** N/A, but will replicate and provide later

_**Note:**_ Issue might possible linked to the lack of a function that handles respawn in earplugs the module (in captives module). Is there a workaround if this is the case?

**Also,** does ace affect all respawns, or would a seperate script like mine bypass the module?

**Comment by PabstMirror** [comment]
Ear plugs are a setVariable on the unit

As with #2835 we don't really handle respawn right now at all.  Should probably just set that variable false and then re run the add func.

In the meantime, you should be able to manually remove via this code on respawn

`_unit setVariable ["ACE_hasEarPlugsin", false]`

**Comment by headedhorseman101** [comment]
thank you for the workaround @PabstMirror. Much appreciated.
