### ISSUE TITLE
Referencing custom action parameters in the called script

### ISSUE THREAD

**Issue by ACyprus** [acemod/ACE3#2843]
My question relates to argument 6 (Action parameters) of **ACE_interact_menu_fnc_createAction**, highlighted below:

https://github.com/acemod/ACE3/blob/825b410ae87d421db93c37f68215a2b74d0b8cc0/addons/interact_menu/functions/fnc_createAction.sqf#L13

How would I go about accessing these in the script/function/statement assosciated with a particular action created using the above?

In my current use case, I am calling fn_createAction inside a forEach block and would like to pass the value of _x as the custom action parameter.

I've searched for a solution or example but could not find one. The closest I came was to somebody else asking a similar question at the end of this forum thread:

http://forums.unitedoperations.net/index.php/topic/25042-ace-custom-interactions/

Please and thank you :)

**Comment by commy2** [comment]
Have you tried `_this` or in case of an array params ["_a", "_b", ... "_n"];`?

**Comment by ACyprus** [comment]
I'd tried _this, yep, but I'm guessing now it was being overridden by the argument I had passed in the statement itself. I'll move everything to the custom parameters and try that. Not sure why I hadn't done that to begin with.

Thanks commy2.

**Comment by commy2** [comment]
Yeah, `_this` is overwritten after every call. You have to "relay race" `this` through all scopes.

**Comment by PabstMirror** [comment]
In statement and conditions, what's passed in will be `[_target, _player, _customParams]`

Here's an example that passes in the `_x` from a forEach loop:
Because it's an array, you can do crazy stuff like setting variables back in it (not sure if you would ever want to, but it's possible)

```
{
    _name = format ["Test%1", _x];
    _statement = {
        params ["_target", "_player", "_args"];
        _args params ["_num", "_lastTime"];
        systemChat format ["Action num %1 - Last time selected %2", _num, (floor _lastTime)];
        _args set [1, time];
    };
    _act =  [_name, _name,"", _statement, {true},{},[_x, -1], [0,0,0], 100] call ace_interact_menu_fnc_createAction;
    [typeOf player, 1, ["ACE_SelfActions"], _act] call ace_interact_menu_fnc_addActionToClass;
} forEach [0,1];
```

**Comment by ACyprus** [comment]
Gentlemen. Many thanks.
