### ISSUE TITLE
Basic medical, Revive, request for revive time remaining indicator

### ISSUE THREAD

**Issue by captainblaffer** [acemod/ACE3#2851]
ACE3 Version: 3.3.2

Mods:

@CBA_A3
@ace

Placed ACE3 Modules:
ACE Medical Revive

Description:
When using ACE3 basic medical, with revive module active, and maxReviveTime on any positive value.

When a player goes unconscious into the revive state, he will die after maxReviveTime. The issue is his teammates have no way to tell how much time is left until he dies.

It would be great to have an indicator added that displays the remaining maxReviveTime. e.g. when diagnosing the patient.

This feature would work well together with the new option to CPR unconscious players: https://github.com/acemod/ACE3/issues/2114

Steps to reproduce:
N/A

Where did the issue occur?
Multiplayer

RPT log file:
N/A

**Comment by jokoho48** [comment]
some pseudocode
```C#
["medical_onUnconscious", {
    params ["_unit", "_status"];
    if !(local _unit) exitWith {};
    if (_status) then {
        JK_unconsciousPFHID = [{
            params ["_unit"];
            _startTime = _unit getvariable ["ace_medical_reviveStartTime", 0];
            _restTime = ACE_time - _startTime - ace_medical_maxReviveTime;
            hint str _restTime;
        }, 1, [_unit]] call CBA_fnc_addPerFrameHandler;
    } else {
        if (!isNil "JK_unconsciousPFHID") then {
            [JK_unconsciousPFHID] call CBA_fnc_removePerFrameHandler;
            JK_unconsciousPFHID = nil;
        };
    };
}] call ace_common_fnc_addEventhandler;
```
but i tink this is more a FQ

**Comment by captainblaffer** [comment]
Thanks for looking into this!
