### ISSUE TITLE
first person view screen color getting changed

### ISSUE THREAD

**Issue by xdr1000** [acemod/ACE3#2853]
On Changing player view from 3rd person to first person screen color or sun light getting changed if i am using combination of  CBA & ACE, also same issue found with CBA & AGM so this issue is because of using AGM feature in ACE, i think so. Request to ACE team to look at this issue.

3rd person view --> 
![2015-11-20_00007](https://cloud.githubusercontent.com/assets/15930692/11281358/4a237090-8f20-11e5-82df-c03c8690f28f.jpg)

FP view -->

![2015-11-20_00008](https://cloud.githubusercontent.com/assets/15930692/11281371/534cc3b0-8f20-11e5-83aa-7936cbf3136a.jpg)

**Comment by jokoho48** [comment]
This are the Goggle Module you can disable that it change in the Settings

**Comment by PabstMirror** [comment]
I believe this is the goggles feature.

In ace options you can set `Show Goggle Effects in Third Person` to true to keep the effect constant in 3rd and 1st.

Or you can take off your glasses in game, or remove ace_googles.pbo

**Comment by xdr1000** [comment]
Great Help!!!! Thanks a lot my friend :-)
