### ISSUE TITLE
Request to add or update new Vehicle damage system with visual physics & effects

### ISSUE THREAD

**Issue by xdr1000** [acemod/ACE3#2858]
Current damage system of arma 3 is good but not best even with ACE mod. 

1. In current stage of arma 3 if any vehicle trip any kind of mine or ied then it just stop and explode at once and spawn of wreck LOD, thats ok but not very real, i mean if any kind of mine explode then it just not only blow vehicle it also kicks away lots of visible or very small projectiles like doors, engine parts (broken parts of vehicle or any nearest destructible object) those can create damage to player or AI players.

2. On explosion of mine or ied under vehicle, it should jump up a little bit up and half roll out on door side in case of medium size Mine  or IED , in case of large Mine and IED vehicle should jump high in air and roll out more, all this depends on vehicle weight. on side hit vehicle should react a little bit different.

3. if vehicle is moving above normal speed and driver get killed then vehicle should keep moving
 three second seconds but it depends on vehicle condition and condition depends on damage caused by kind of mine or ied or rocket or missiles and damage depends on from how close mine or ied etc exploded. Same thing if driver killed by direct bullet then vehicle should keep moving freely for 5 seconds if not get crash to building it any object.

Same above thing for all type vehicles should be done to feel virtual visual physics action and reaction and effects.

Now here is the few images to understand actual damages i really requesting from ACE team:-

Vehicle hit by small explosives :-

After hit smoke should be white and grey or black, not full fire.

![mrap ied](https://cloud.githubusercontent.com/assets/15930692/11311409/b30b4486-8ff5-11e5-8225-3c61911d13fd.jpg)

![6470712600_1443674557](https://cloud.githubusercontent.com/assets/15930692/11311418/be5c148c-8ff5-11e5-8172-499e5d2966c6.jpg)

Vehicle hit by medium explosives :-

After hit smoke should be white and grey or black, small full fire.

![sp17sn0rnmago8vh8crr](https://cloud.githubusercontent.com/assets/15930692/11311452/f80328c4-8ff5-11e5-8f56-66fae230bdb3.jpg)

![tbi4b](https://cloud.githubusercontent.com/assets/15930692/11311460/024572ba-8ff6-11e5-80ba-a108c99037a3.jpg)

Vehicle hit by large explosives :-    

After hit create full smoke , full fire.

![mrap-vehicle-wrecked-after-tripping-a-mine-stack-kapisa-province](https://cloud.githubusercontent.com/assets/15930692/11311594/da3269bc-8ff6-11e5-8b36-a72377da7000.jpg)

![jerry humvee](https://cloud.githubusercontent.com/assets/15930692/11311604/ec1a5586-8ff6-11e5-952b-aa61d6da8b55.JPG)

finally example of flying broken parts on explosion. there is two cars in pic second one on explosion jumped up 3 feet from back side.

![cx2013-0043-89](https://cloud.githubusercontent.com/assets/15930692/11311706/79034b60-8ff7-11e5-9f99-ce17613901e8.JPG)

its very humble and crazy request to ACE team to work on this. If ACE team work on this request with focus then they will see its actual explosive results in feedback and in gameplay. final request if you feel it worth to go ahead then please make it very real as requested. ;-)

Thanks!

**Comment by jokoho48** [comment]
please Read http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
and use #414

**Comment by xdr1000** [comment]
Oh! sorry! thanks for reminding me
