### ISSUE TITLE
Adding HuntIR to other weapons

### ISSUE THREAD

**Issue by MajorXAcE** [acemod/ACE3#2862]
I'm trying to add the ability to use the HuntIR to the Mk17 from this mod: http://www.armaholic.com/page.php?id=26428

I can't seem to get it to work, I used the framework and this mod: http://www.armaholic.com/page.php?id=28963 as a guide but I must be doing something wrong.

    class CfgWeapons {
	    class UGL_F;
	    class Rifle_Base_F;
	    class mk20_base_F : Rifle_Base_F {};
	    class SMA_AssaultBase : mk20_base_F {
			class  EGLM : UGL_F {
				magazines[] = {
					"1Rnd_HE_Grenade_shell",
					"1Rnd_SmokeBlue_Grenade_shell",
					"1Rnd_SmokeGreen_Grenade_shell",
					"1Rnd_SmokeOrange_Grenade_shell",
					"1Rnd_SmokePurple_Grenade_shell",
					"1Rnd_SmokeRed_Grenade_shell",
					"1Rnd_Smoke_Grenade_shell",
					"1Rnd_SmokeYellow_Grenade_shell",
					"UGL_FlareYellow_F",
					"UGL_FlareWhite_F",
					"UGL_FlareRed_F",
					"UGL_FlareGreen_F",
					"UGL_FlareCIR_F",

					//ACE3 Compatibility
					"ACE_HuntIR_M203"
				};
			};

	};
	
};

If anyone can help that would be greatly appreciated.

**Comment by jonpas** [comment]
http://ace3mod.com/wiki/framework/huntIR-framework.html

You don't need the full inheritance for starters, just do:
```
class mk20_base_F;
class SMA_AssaultBase : mk20_base_F {
    class  EGLM : UGL_F {
        magazines[] = {
        .....
```

**Comment by commy2** [comment]
You have to respect the mods class inheritance and not just add random classes. You also have to make sure your addon is loaded after the mod (via CfgPatches)

```
class CfgPatches {
    class MajorXAcE_Scar_Comp_ACE {
        units[] = {};
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = {"Scar_Arma3", "ace_huntir"};
    };
};

class CfgWeapons {
    class SMA_MK16;
    class UGL_F;

    class SMA_Mk16_EGLM: SMA_MK16 {
        class EGLM: UGL_F {
            magazines[] = {
                "1Rnd_HE_Grenade_shell",
                "1Rnd_SmokeBlue_Grenade_shell",
                "1Rnd_SmokeGreen_Grenade_shell",
                "1Rnd_SmokeOrange_Grenade_shell",
                "1Rnd_SmokePurple_Grenade_shell",
                "1Rnd_SmokeRed_Grenade_shell",
                "1Rnd_Smoke_Grenade_shell",
                "1Rnd_SmokeYellow_Grenade_shell",
                "UGL_FlareYellow_F",
                "UGL_FlareWhite_F",
                "UGL_FlareRed_F",
                "UGL_FlareGreen_F",
                "UGL_FlareCIR_F",
                "ACE_HuntIR_M203"
            };
        };
    };

    class SMA_Mk17;
    class SMA_Mk17_EGLM: SMA_MK17 {
        class EGLM: UGL_F {
            magazines[] = {
                "1Rnd_HE_Grenade_shell",
                "1Rnd_SmokeBlue_Grenade_shell",
                "1Rnd_SmokeGreen_Grenade_shell",
                "1Rnd_SmokeOrange_Grenade_shell",
                "1Rnd_SmokePurple_Grenade_shell",
                "1Rnd_SmokeRed_Grenade_shell",
                "1Rnd_Smoke_Grenade_shell",
                "1Rnd_SmokeYellow_Grenade_shell",
                "UGL_FlareYellow_F",
                "UGL_FlareWhite_F",
                "UGL_FlareRed_F",
                "UGL_FlareGreen_F",
                "UGL_FlareCIR_F",
                "ACE_HuntIR_M203"
            };
        };
    };
};
```

**Comment by MajorXAcE** [comment]
Wow, thanks a lot! Clearly I still have much to learn.
