### ISSUE TITLE
Missing explosive definitions for fragmentation system

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#2863]
ACE3 Version: 3.3.2 (stable)

**Mods:**
* `@cba_a3`
* `@ace3`

**Placed ACE3 Modules:**
N/A

**Description:**
Missing proper explosive properties definitions for fragmentation system.

**Steps to reproduce:**
* Fire a `Scalpel E2` (ammo `M_Scalpel_AT` of classes `8Rnd_LG_scalpel`/`6Rnd_LG_scalpel`/`2Rnd_LG_scalpel`) or an `ASRAAM` (ammo `M_Air_AA` of classes `2Rnd_AAA_missiles`/`4Rnd_AAA_missiles`)
* Check RPT

**Where did the issue occur?**
Multiplayer - Dedicated

**RPT log file:**
(extract only)
```
[ACE] (frag) WARNING: Ammo class M_Scalpel_AT lacks proper explosive properties definitions for frag!
[ACE] (frag) WARNING: Ammo class M_Air_AA lacks proper explosive properties definitions for frag!
```

**Comment by bux578** [comment]
https://github.com/acemod/ACE3/issues/342

**Comment by commy2** [comment]
Added  `M_Scalpel_AT` and `M_Air_AA` to the other issue.
