### ISSUE TITLE
Kaspersky Trojan Warning

### ISSUE THREAD

**Issue by Sk3y** [acemod/ACE3#2864]
Hi Team,

please check the following message from Kaspersky. Is it a canard?

http://goo.gl/lf1ks9

**Comment by commy2** [comment]
Where did you download ACE?

**Comment by PabstMirror** [comment]
False positive, check https://www.virustotal.com/en/file/ca94f89ce77c54b89973f33a917068248a40ced0ef555a14e2d408d593f32ae9/analysis/
and
https://www.metascan-online.com/#!/results/file/3de8f63cb10c4ebfa425f8ce481db339/regular

Plus you can check our source code and build it yourself.

**Comment by PabstMirror** [comment]
And like commy brought up, make sure to download from a place you trust (like https://github.com/acemod/ACE3/releases/latest).
