### ISSUE TITLE
Visualization of the injury is not consistent with the wounds in medical menu.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2866]
ACE3 Version: 3.3.2
Stable 1.52

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
Basic and Advanced Medical modules.

**Description:**
Visualization of the injury (blood stained hand or blood stained leg) is not consistent with the wounds in medical menu (H-key). For example, if the player's character according to medical  menu will injured in only one hand, but visually the player's character will be stained with blood both hands. The same thing happens also with the legs. So either the medical menu or the game-visualization show injuries is not correct.

**Steps to reproduce:**
Play in ACE3

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by gienkov** [comment]
It's engine-related and nothing can be done ATM.
21 lis 2015 22:03 "mickeymen" <notifications@github.com> napisał(a):

**Comment by commy2** [comment]
I don't think there is anything we can do about this, because those things are hard-coded AND they would require changes to a models selections, including the model.cfg, for both vanilla uniforms and every mod out there.
Close?

**Comment by SilentSpike** [comment]
Yeah, unfortunately I'd say that's the case.

**Comment by Glowbal** [comment]
Close. Nothing we can do at this time.
