### ISSUE TITLE
G-force problem, cant read instruments in fixed wing aircraft cockpit.

### ISSUE THREAD

**Issue by delevero** [acemod/ACE3#2868]
Hi.
I like to report an problem with the ace G-forces.
When choosing a fixed wing aircraft such as the a-10, then when I add full power I am pushed back into the seat. This is realistic and I like it.
But when I example no longer accelerate then the view should "return" to the std. start position and so to speak reset it self.

- The problem is that as it is today the G-forces push the pilot far back into the seat all the time while flying resulting in us not being able to read the instrument panel from that distance.

So I would like the G-forces adjusted so we can read the instrument panel. OR at least have some kind of keyboard command that allow us to reset the view to std. possition.

I would also like to request a feature so people can turn G-forces on and off.

**Comment by commy2** [comment]
Can someone who is more experienced with aircraft explain whats going on here?

**Comment by gienkov** [comment]
He described standard A3 behaviour there. Use TrackIR or zoom with RMB to
read it, ACE3 don't modify this at all.

**Comment by commy2** [comment]
I don't think there is anything we can do about this then. This behaviour seems to be hard-coded.

**Comment by bux578** [comment]
Never happened to me

**Comment by headedhorseman101** [comment]
>I don't think there is anything we can do about this then. This behaviour seems to be hard-coded.

It is BIS's fault simulated for both vehicles ground aircraft.

**Comment by commy2** [comment]
OK
