### ISSUE TITLE
Add framework code for animated 2D scopes

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#287]
- maybe not worth it, but the `cameraViewChanged` event  may help cut down the pfh. Only run the pfh when the scope is scoped (edited)
- Create some sort of framework, so the name of the function to be called on draw for a scoped scope is read from config 

That should allow different types of animated scopes to coexist. Also mods to add their own.

**Comment by dixon13** [comment]
this sounds like something for [CBA](https://github.com/CBATeam/CBA_A3)

**Comment by kymckay** [comment]
Believe this is done in CBA with PIP scopes
