### ISSUE TITLE
Driving UGV will throw out errors from nametags if you drive close to players

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2873]
ACE3 Version: 3.3.2

**Mods:**
* `@CBA_A3`
* `@ace`
* `https://docs.google.com/spreadsheets/d/1OTjYgUqxEnQsQBAfgwmjbThDZ3unG21H1jfGkZEwO00/edit?pli=1#gid=0`

**Placed ACE3 Modules:**
* Nametags

**Description:**
* Driving UGV will throw out errors from nametags if you drive close to players.*

**Steps to reproduce:**
* *Control UGV close to another player, script error spam's RPT.*

**Where did the issue occur?**
* "Multiplayer"*

**RPT log file:**
* Script error spam starts at line 2064 http://pastebin.com/8WEWV1Tq

**Comment by jokoho48** [comment]
@gienkov could you please reupload the RPT it not exist currently

**Comment by CorruptedHeart** [comment]
It does exist, the correct link is  http://pastebin.com/8WEWV1Tq

**Comment by gienkov** [comment]
Link fixed, sorry
