### ISSUE TITLE
ACE ballistics breaks configs RHS

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#2879]
You could make compatible with RHS?
RPG-7 PGO your system is not working. Reticle broken.
And much more . . . 

"ACE" global addon to be used with 100% RHS not only to him.

**Comment by SilentSpike** [comment]
I can't think how we would be breaking RHS, but there's unfortunately not enough information here to figure that out. Maybe somebody else knows more on this.

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by i3r4ndon** [comment]
The RHS RPG has never worked well for me, there's no way to zero it and the optic has never been a reliable way to fire it. Don't know why they've left it like that or if they don't know about it somehow, but yea I don't think its ACE that's messing with it.

**Comment by commy2** [comment]
"ACE ballistics breaks configs RHS"

What and how?

**Comment by commy2** [comment]
No more activity.
