### ISSUE TITLE
ACE 3: Kestrel/AtragMX

### ISSUE THREAD

**Issue by jin2335** [acemod/ACE3#2880]
So I am having an issue. I am trying to learn the ace 3 sniping system, but the atragMX and kestrel refuse to work. I've researched for about 10 hours now have all the proper mods installed prior CBA basically and I cannot get the kestrel or atragMx to show up in game. Even if i go to configure the addon and change the hotkey for it default "scroll lock" it just does nothing.. apparently alot of people had this issue but no solution as to how they fixed it.. I use mods through playwith six, please advise.. In addition I've noticed that on videos of people demonstrating the kestrel and atrag MX, it will show in their self interaction menu. Even if I have the atrax and kestrel in my back they will not show in my ace interaction menu.. so how can I get it to work?

**Comment by madpat3** [comment]
you Need to have them on your Body (like uniform or vest). in the backpack you can't take a grab on items.

**Comment by PabstMirror** [comment]
@jin2335 Are you having any luck getting the devices to open?

**Comment by commy2** [comment]
No more activity. Please create a new issue if the problem persists.
