### ISSUE TITLE
climbing

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#2885]
could you improve your climbing feature?

you can barely climb anything. only fortification's sandbags and through windows.
but there are many walls, that aren't much higher than that, and they're not climbable.
this makes the feature almost useless in combat.
good comparison is "LAxemann's Climb" mod http://www.armaholic.com/page.php?id=25996,
which looks quite similar to your animations, 
but is more useful in combat situations, since you can climb many obstacles.

speaking of climbing, from my point of view, the jump feature needs improvement, too. 
you can only jump with a rifle in hands.
not with a pistol and not even barehanded.

please :) think about it.

**Comment by commy2** [comment]
#414
