### ISSUE TITLE
Damage from a jet of the RPG-32 are not realistic and overly exaggerated.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2890]
ACE3 Version: 3.4.1
Stable 1.54

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
Advanced and Basic Medical*

**Description:**
Damage from a jet of the RPG-32 are not realistic and overly exaggerated. In ACE3, it is impossible to use this weapon in the forest, in the cities, inside houses and on the hills sides. In these locations, almost every shot serious damages the player or causes him to lose consciousness. Why the hell the soldier should to lose consciousness, even if he has received burns from a jet? The soldier not thrusts his head or face into the jet, and therefore should not receive serious damages, especially to lose consciousness. At wrong using (if behind the wall or object) the soldier should has only receive light damages, nothing more. Please fix this details/

**Steps to reproduce:**
Use RPG-32

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by gienkov** [comment]
https://youtu.be/BCN0y4BHiGs

**Comment by mickeymen** [comment]
@gienkov "Backblast Sends Soldier Flying" but no into loss of consciousness, as we can see in ACE3/

**Comment by jokoho48** [comment]
the Law in the Video Gienkov send was a Soft Launch Law. That mean that the Launcher have a Reduced Backblase but for example a RPG-7 or the AT4 or the NLAW are not everytime soft Launch Laws and that mean you have a a 30° and 15 meter a Dead zone.
http://www.inetres.com/gp/military/infantry/antiarmor/M72/M72_blast.gif

**Comment by mickeymen** [comment]
Damage for the shooter should be significantly less, than the damage to the person standing behind the Launcher. But in ACE3, we see frequent loss of consciousness after a shot from RPG. Also sometimes a loss of consciousness happens in the empty places of the map. https://github.com/acemod/ACE3/issues/2747#issuecomment-154726699
Unfortunately this all, annoys the player

**Comment by TheGrandVizier** [comment]
Honestly, as a Zeus, I sort of already expect that if I Remote Control an RPG dude, upon firing he is toast.
Yes, annoying.

**Comment by bux578** [comment]
Guys, please: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by captainblaffer** [comment]
Agree this issue needs resolving. Also makes shooting RPGs at helicopters very annoying.

**Comment by mickeymen** [comment]
Guys. Someone will fix it finally? In ACE3, you can't use RPG-32, without damaging the soldier which firing. The shooter almost always will be injured or lose consciousness, every shot like  explodes like a grenade.

Even if behind a player located wall (at distance of about 5 meters!) the player loses consciousness or receives a lot of damages. Why the hell the soldier should to lose consciousness, even if he has received burns from a jet? 
Please fix this nonsense, It annoying player

**Comment by commy2** [comment]
> Someone will fix it finally?
Open
Source
-
No
excuses
