### ISSUE TITLE
Cannot Disable Medical System

### ISSUE THREAD

**Issue by jameslkingsley** [acemod/ACE3#2894]
This is seriously not right. There needs to be an option in the mission to disable the medical system completely. Hard coding the system to be enabled it just not right and is poor coding practice.

**Comment by jokoho48** [comment]
delete the ace_medical.pbo and its disabled ;)

**Comment by jameslkingsley** [comment]
Did you not see the "option in the mission" part of what I wrote?

**Comment by jonpas** [comment]
-> #414 

> Hard coding the system to be enabled it just not right and is poor coding practice.

You are always free to write your own or even pull request to ACE3. :)

**Comment by jameslkingsley** [comment]
Or it should just be in the base ACE 3 mod... It's not like I'm asking for much...

**Comment by SilentSpike** [comment]
It's not a coding practise, we can't add an option because the medical system requires config changes.

**Comment by sargken** [comment]
Why would you want to remove the medical system regardless? Its a mainstay of the ACE mod.

**Comment by jameslkingsley** [comment]
Because I don't want to use it in a mission...

**Comment by jameslkingsley** [comment]
If there was API for handling a unit's damage then this wouldn't be an issue, but at the moment any BIS damage commands do nothing with ACE.

**Comment by licht-im-Norden87** [comment]
I know this request is a little bit old.. But i must say: jameslkingsley , you behave like a jerk

**Comment by commy2** [comment]
ref #414
