### ISSUE TITLE
[Feature request] Hide digital clocks on map screen

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#2898]
Just want to say about that small thing. You always can check time on map screen even if you don't have watches or GPS in inventory.
http://i.imgur.com/ZaTxIAw.png
Just a little immersion tweak to make item watches more significant.

**Comment by jokoho48** [comment]
please read: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
and use #414

**Comment by PabstMirror** [comment]
@ruPaladin  #2344 should have added this feature, and is part of 3.3.0

**Comment by ruPaladin** [comment]
Thank you, I closed it because made more test and found that digital clocks won't work without watches in appropriate slot. Sorry for inconvenience and your time.
