### ISSUE TITLE
Interaction menus are still accessible while waiting for respawn

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#2900]
ACE3 Version: 3.3.2

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* *None.*

**Description:**
Player can access self-interaction and interaction menus while waiting for the respawn.
Not a huge problem but i think those should not be accessible during respawn timer.
https://i.imgur.com/zUyjh0v.jpg

**Steps to reproduce:**
* *Get into the multiplayer editor.*
* *Press respawn.*

**Where did the issue occur?**
* *"Multiplayer"*

**RPT log file:**
* *No need.*

**Comment by SilentSpike** [comment]
Should be an easy fix
