### ISSUE TITLE
Flare with parachute

### ISSUE THREAD

**Issue by Xawery94** [acemod/ACE3#2901]
I have a proposition. Can you make a flare with parachute because the vanilla flare is maintained in the air very short and falls to the ground very quickly. But I have tested a Hunt IR and it has own parachute and stay in air for very long time. So it would be nice to see this flare with a similar parachute

**Comment by headedhorseman101** [comment]
@commy2 realistic values for the rounds IRL if you want the are here: [TM 43-0001-28] (http://everyspec.com/ARMY/TM-Tech-Manual/download.php?spec=TM_43-0001-28_C11_27OCT2003.013353.pdf). Page 6-37 or 606.

**Comment by commy2** [comment]
thanks

**Comment by commy2** [comment]
>The cavity contains a pyrotechnic
>flare candle assembly, and an integral
>ignition/ejection charge attached to a 20-
>inch diameter parachute. The projectile has a
>4- to 5-second delay ignition element crimped
>into the center opening of a metal delay carrier.
>The
>attached parachute deploys upon ejection to
>lower the candle at 7 feet per second. The candle
>burns for approximately 40 seconds.

**Comment by sargken** [comment]
How about a Parachute with a flare attached for units to stay in formation at night?

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
