### ISSUE TITLE
[1.54] Vests are almost impenetrable in

### ISSUE THREAD

**Issue by perfk** [acemod/ACE3#2905]
ACE3 Version: 3.3.2
stable branch: 1.54.133570
CBA 2.1.2.151016

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
none

**Description:**
Vests are almost impenetrable. Takes 1 and 4/5 of a mag from a the MX (6.5mm 30 round) shot at a Nato Rifleman´s vest from 5 meters away, before he died. (he was using the carrier lite (green) (default rifleman vest)

Tested without any mods loaded, and he dies in 1-4 shots to the vest.

**Steps to reproduce:**
place a default unit, place another default unit. shoot said unit in the vest.

**Where did the issue occur?**
n/a

**RPT log file:**
http://pastebin.com/079P9NtP

**Comment by Glowbal** [comment]
Please wait for ACE 3.4.0. This will be released shortly.

**Comment by commy2** [comment]
dup of #2768 and #2903

**Comment by commy2** [comment]
And of #2600
