### ISSUE TITLE
Cannot bring out AT whilst prone

### ISSUE THREAD

**Issue by moonmanmove** [acemod/ACE3#2907]
ACE3 Version: 3.3.2
1.54 stable

**Mods:**
@CBA_A3
@ace

Placed ACE3 Modules:
not needed

Description:
You cannot bring out AT whilst prone, forces you to stand when you try to bring it out.

Steps to reproduce:
Grab AT
Go Prone
Attempt to prep said AT

Where did the issue occur?
everywhere

RPT log file:
Not needed

**Comment by commy2** [comment]
Same as in the base game.
Nothing we can do.

http://feedback.arma3.com/view.php?id=25234
http://feedback.arma3.com/view.php?id=12599

#414
