### ISSUE TITLE
1.4.0 mod.cpp wrong version

### ISSUE THREAD

**Issue by kripto202** [acemod/ACE3#2909]
The mod.cpp file presents to the incorrect version of ace.

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/blob/release/mod.cpp show it being correct,

Where did you download from?  Try a copy from github: https://github.com/acemod/ACE3/releases/download/v3.4.0/ace3_3.4.0.zip

**Comment by kripto202** [comment]
straight from the github
