### ISSUE TITLE
Sleep inside of the per frame event handler

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#2910]
ACE3 Version: 3.4.0

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* *Check PBO.*

**Description:**
* *Sleep inside of the per frame event handler for pbo checks.*
https://github.com/acemod/ACE3/blob/825b410ae87d421db93c37f68215a2b74d0b8cc0/addons/common/functions/fnc_checkPBOs.sqf#L78
http://i.imgur.com/P8xnHqP.jpg

**Steps to reproduce:**
* *Place check PBO module.*
* *Launch a multiplayer game.*

**Where did the issue occur?**
* *"Multiplayer"*

**RPT log file:**
* *No need.*

**Comment by commy2** [comment]
Fixed in #2911
