### ISSUE TITLE
Problem with "<" and ">" in the Tag

### ISSUE THREAD

**Issue by mrpictolin** [acemod/ACE3#2912]
In first, Hellow to all the Arma and Ace community.

I'm member of Grupo Armados (Spanish military simulation group for Arma3) and our tag is `<A2>`, but if we dont put the separation this not appear in the text. We have a problem with this and the name tag of ACE3 (Yeah, the letters who appear in the top of the player). 

We don't like to change our tag becouse we has used this since OPX, soo we stay were to propose to he ACE developments solve this simple but annoying problem (That is only put some lines of code in the script).

Thanks soo much for read the propose (or problem) and we hope your answer (o solution).

Regards form Spain and Grupo Armados.

**Comment by Glowbal** [comment]
What is the problem exactly? And I understand you are suggesting a solution?

**Comment by mrpictolin** [comment]
Hi Glowbal, this is a suggesting, sorry for non indicate this in the biggining, we are now in this...

The problem is that non appear the tad and the name, like for example: <A2>Soldier.
Appear this; &Alt;A2&gt;Soldier.

Here a picture to show the problem: https://i.gyazo.com/bd3d6892b07d9f66dca594d2acea95f9.png

Thanks

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_sanitizeString.sqf#L25

We convert `>` into `&gt;` on purpose.
This is so those tags aren't interpreted as real html code in stuff like Structured Text dialogs.

I guess we could convert `>` into `]` or `)` which should look much nicer?

**Comment by commy2** [comment]
Why are the names sanitized when they are never converted to `Text` though?

**Comment by PabstMirror** [comment]
I know medical uses it:
`["displayTextStructured", [_caller], [[_output, [_target] call EFUNC(common,getName), round(_bloodPressureHigh),round(_bloodPressureLow)], 1.75, _caller]] call EFUNC(common,targetEvent);`
