### ISSUE TITLE
All units invincible, ACE Check PBOs + Medical Prevent instant death or Revive

### ISSUE THREAD

**Issue by captainblaffer** [acemod/ACE3#2913]
ACE3 Version: 3.4.0

Mods:

@CBA_A3
@ace

Placed ACE3 Modules:
ACE Check PBOs
ACE Medical Settings 
ACE Medical Revive

Description:
If a mission features the ACE Check PBOs module with empty whitelist + either
-Medical Settings Prevent instant death: ON 
-Revive module

all units are invincible.

Steps to reproduce:
1.Create new mission in editor.
2.Place NATO and CSAT dude.
3.Place module; ACE check pbo
4.Set module setting: whitelist, delete the brackets: [] , so you're left with an empty field.
5.Place module: ACE Medical settings.
6.set module setting: Prevent instant death: ON 

7.Start mission. Attempt to kill the enemy.

Where did the issue occur?
SP

RPT log file:
http://pastebin.com/rhE1VncE

**Comment by bux578** [comment]
RPT or it didn't happen

**Comment by captainblaffer** [comment]
Sorry, updated the bug with RPT and more info. Turned out there was more going on than I initially thought

**Comment by PabstMirror** [comment]
Quickly reproduced this issue, but the core problem isn't medical?  
Try changing Check PBO module to be `[]` instead of empty string and it goes away, I think the crash in common_fnc_map is the problem.

**Comment by captainblaffer** [comment]
Yes I suppose the issue can only occur if the mission maker makes the 'mistake' of removing `[]`

The thing is I loaded up my mission from before the patch and it didn't have these  `[]` in the module. Possibly the default setting got changed in a patch?

**Comment by PabstMirror** [comment]
So there error was in checkPbo, and that cascaded and broke the "SettingsInitialized" event, which meant `settingsInitFinished` was never set, so `ace_medical_fnc_setUnconscious` failed to run.

Really interesting chain, thanks a lot for RPT and reproduction steps.

**Comment by jonpas** [comment]
That's actually pretty amazing.

**Comment by commy2** [comment]
Fixed in #2911
