### ISSUE TITLE
Cannot restrict Map Marker channels anymore

### ISSUE THREAD

**Issue by adampiskorski** [acemod/ACE3#2914]
In the past I used [disableChannels[]](https://community.bistudio.com/wiki/Description.ext#disableChannels) in the description.ext in order to prevent players from not just typing messages in certain channels, but also from making markers in those channels. 
With the ACE Map marker placement window, you can use channels regardless of the [disableChannels[]](https://community.bistudio.com/wiki/Description.ext#disableChannels) setting, thus overriding it.

Probably the main example of this is to prevent players from putting down global or side markers after the mission start. This increases the value of tools like cTab.

**Comment by commy2** [comment]
`disableChannels` no longer works for side and another channel I can't remember anymore.
Will look into it.

**Comment by SilentSpike** [comment]
There is also a new `enableChannel` [command](https://community.bistudio.com/wiki/enableChannel)

**Comment by SilentSpike** [comment]
I'm not sure there's anything we can do to account for that one though

**Comment by adampiskorski** [comment]
I checked it again on my side and after checking it properly on a dedicated server in Vanilla, I found out that is Vanilla Arma that brought in the channel selection for markers. 
Sorry about that, I seldom play Vanilla Arma.

**Comment by Neefay** [comment]
There is a very simple fix for this issue. Currently I'm unable to submit a pull, but if anyone would be so kind, this is tested and works with no problems.

[Insert within `markers\XEH_preInit.sqf`, before `ADDON = true`.](http://pastebin.com/d9sFRBCa)

[Insert in `markers\functions\fnc_initInsertMarker.sqf`, within `EFUNC(common,execNextFrame)` .](http://pastebin.com/NEjE7swR)

As you can tell, the code is far from perfect but it's what came out after I found myself struggling with that issue for a while.

**Comment by commy2** [comment]
Should work better using ACE in the next version. Classifying this as feature.

**Comment by commy2** [comment]
Done in release branch, ref: #3004
