### ISSUE TITLE
range card not updated

### ISSUE THREAD

**Issue by macfifa** [acemod/ACE3#2915]
hi
arma 3 1.52
ace 3.3.1 and 3.3.2 range card stay at 6.5x39 ammo table and not change when i change my rifle 
![rangecard](https://cloud.githubusercontent.com/assets/16125957/11547556/dfc29d66-9965-11e5-9de6-a94ec8700400.jpg)

**Comment by MikeMatrix** [comment]
Please make sure this is still an issue with the 3.4.0 release of ACE.
Also make sure to read this: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by macfifa** [comment]
ACE3 Version: 3.3.2 ,3.3.1 and 3.3.0
stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
advanced ballistics

**Description:**
i have test it with arma 1.52 v and ace 3.3.2 not 3.4 becouse it did not work with arma 3 1.52
the range card stay at 6.5x39 bullet and not change

**Steps to reproduce:**
range card and change your weapon

**Where did the issue occur?**
Editor

**RPT log file:**
http://pastebin.com/raw.php?i=FE83NMiF

**Comment by bux578** [comment]
Please use steam to update your game to 1.54 and retest with ACE 3.4.0.

**Comment by PabstMirror** [comment]
@macfifa any luck with arma 1.54 and new ace release 3.4.1?

**Comment by macfifa** [comment]
no i have update to 1.54 and ace 3.4.1 and it is the same

**Comment by PabstMirror** [comment]
I still can't reproduce the problem.

 - Start with 6.5mm default gun
 - Put rangecard in vest
 - Open rangecard, it shows 6.5mm
 - Switch to Intervention / .408
 - Reload weapon (it needs a magazine in the weapon, **this might be missing step?**)
 - Open rangecard, it show .408

**Comment by macfifa** [comment]
Steps to reproduce:
i deside to use a key for the range card and suddenly the range card works fine it update itself
but when i use the self interaction menu as the first time it stay at the last update 
i dont know if it is reported befor about the self interaction menu but it seem that it is the couse of the bug

**Comment by PabstMirror** [comment]
![image](https://cloud.githubusercontent.com/assets/9376747/11794800/ca281dde-a278-11e5-9e86-dc2ee9ebc6cb.png)

Can you double check you are using `Open Range Card` (blue action) and not the open copy (green action)?

**Comment by macfifa** [comment]
i use the open range card (blue action) and it works 
what function  the other open range card have ?

**Comment by PabstMirror** [comment]
Just to confirm, it's working correctly now for you?

The blue opens a range card based on your current weapon.

You can also create a copy of rangecard for your weapon that will not change after switching to a new weapon.  You can also interact on people and create a copy for their weapon.

It's so spotters can make a rangecard for the sniper they are assisting.

**Comment by macfifa** [comment]
yes thx for your help
