### ISSUE TITLE
Cannot turn Laser/Light on

### ISSUE THREAD

**Issue by EddiePrice** [acemod/ACE3#2917]
ACE3 Version: 3.4.0

Mods: @CBA_A3, @ACE

Placed ACE3 Modules: None

Description:
Running current CBA + current ACE I can't turn lasers or lights on. I can switch between IR and Laser with Shift+L as per the ACE controls, but that's it.

Steps to reproduce:
Place unit in editor, or use arsenal to test - make it dark and equip NV. Try to turn any weapon light or laser on with L key. Notice neither work for no particular reason, smash alt-F4 until your keyboard breaks, question life.

Where did the issue occur:
Editor, Arsenal, MP, SP

RPT log file:
http://pastebin.com/NA2amMWL

**Comment by BaerMitUmlaut** [comment]
[This is somehow related to having a binocular in your inventory](https://www.youtube.com/watch?v=5bfXRO9piOs). Possibly related to #2916?

**Comment by Max255PL** [comment]
Confirmed.

**Comment by EddiePrice** [comment]
Double confirmed.

**Comment by PabstMirror** [comment]
Fixed by #2935
