### ISSUE TITLE
RHS Compatibility PBO -> Burst Fire

### ISSUE THREAD

**Issue by RSpeekenbrink** [acemod/ACE3#2918]
RHS Compatibility PBO causes errors with RHS, such as your unable to fire the m4 & m16 weapons on burst mode.

RPT (with mods: CBA 2.2.0.151130, ACE 3.4, TFAR 0.9.8)
pastebin.com/9UerihNv

How to reproduce:
1 Enable ACE RHS Compatibility PBO
2. Grab an m4 or m16
3. Put it on burst fire

**Comment by PabstMirror** [comment]
Related to #2916 / binocularMagazine
Removing that line fixes issue.
`currentWeaponMode player` is "burst", but the gun only fires single shot.

**Comment by PabstMirror** [comment]
Fixed by #2935
