### ISSUE TITLE
Shots on Extremities

### ISSUE THREAD

**Issue by Whalen207** [acemod/ACE3#2919]
ACE3 Version: 3.4.0
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
N/A

**Description:**
Damage to extremities has been reduced significantly, to the point where eight or more shots is often necessary with a 6.5mm to bring a man down, let alone kill him.

**Steps to reproduce:**
- Load up Virtual Arsenal
- Put on: Combat Fatigues MTP, Carrier Rig (Green), anything really.
- Used: MX, anything will show this problem
- Shoot AI in the chest, the head, and the extremities. Compare TTK.

**Where did the issue occur?**
- Virtual Arsenal, SP Missions

**RPT log file:**
http://pastebin.com/6EH8Ma3Y

EDIT - RPT FOR STRATIS
http://pastebin.com/rYP9xDXa

**Comment by bux578** [comment]
RPT or it didn't happen

**Comment by Whalen207** [comment]
RPT slapped up there.

**Comment by jonpas** [comment]
Things regarding damage have changed since creation of this issue, if it still happens with latest version create a new ticket.
