### ISSUE TITLE
Backblast / Overpressure with MANPADS

### ISSUE THREAD

**Issue by neurook** [acemod/ACE3#2920]
**As discussed on teamspeak with Glowbal**

ACE3 Version: 3.4.0 (latest)

**Mods:**
* `@CBA_A3`
* `@16AA_A3`
* `@ace`

**Placed ACE3 Modules:**
None (does not seem to matter if I do).

**Description:**
Backblast will injure/kill user when firing angled launchers like the Stinger. Probably because getDistance function meets the ground/player geography. Anything above about a 45 degree angle will do it.

**Steps to reproduce:**
Lean back and fire launcher.

Weapon Configuration: 

	class 16aa_stinger_launcher: Launcher_Base_F
	{
		ace_overpeessure_angle=30;
		ace_overpeessure_range=2;
		ace_overpeessure_damage=0.5;
	};

**Where did the issue occur?**
Multiplayer, Editor and Singleplayer.

**Expected behavior**

You should be able to fire the launcher without being harmed at a 65 degree inclined firing angle, even with ace_overpeessure_range set to 5 (possibly even 15).

Reference material: http://usacac.army.mil/sites/default/files/misc/doctrine/CDG/cdg_resources/manuals/fm/fm44_18_1.pdf

**RPT log file:**
No errors.

**Comment by mattiahj** [comment]
Linked manual also states that as long as there's a 30 inch space (0.762 m) behind the end of the launcher you should be good to fire, and very not good otherwise.

**Comment by mattiahj** [comment]
Clearly there is a spelling error in the 16AA weapon config, which means the weapon reverts to default values which are 60 degree backblast and 10m distance. I'm submitting a patch/bug report to their modpack as that is not an ACE thing.

However, expanding the ACE overpressure/backplast addon with separate values for "user distance to object / geometry" and "distance of third-party to backplast origin" might be warranted.

**Comment by commy2** [comment]
>overpeessure

hahaha

**Comment by mattiahj** [comment]
Heh. Fixed that (not my fault). The problem still persist with sane values of 30 degrees and 5m. It goes away if you reduce it to a meter though.

**Comment by Glowbal** [comment]
This might be fixed by #3172 and #3148.

**Comment by esteldunedain** [comment]
> #3148.

Yes.
