### ISSUE TITLE
AA & AT Lock On

### ISSUE THREAD

**Issue by TCRSmacky** [acemod/ACE3#2922]
I believe this is related to the NVG/Binocular/Laser/Flashlight issue.

With all AA launchers and almost all AT launchers, you cannot get a lock on.

With Arma 3 1.52 & ACE 3.3.2.0 > Lock on worked as expected

With Arma 3 1.54 & ACE 3.3.2.0 > Lock on worked as expected

With Arma 3 1.54 & ACE 3.4.0.0 > Problems with all AA and most AT launchers getting launch on

With Arma 3 1.54 & ACE 3.4.0.0 > If I remove the binos from the inventory slot, I can lock on without issue.

Hope this helps.

**Comment by commy2** [comment]
>I believe this is related to the NVG/Binocular/Laser/Flashlight issue.

It is. Fix soonTM.

ref: https://github.com/acemod/ACE3/issues/2916

**Comment by commy2** [comment]
Fixed with #2935
