### ISSUE TITLE
some hitlocations are impossible to hit

### ISSUE THREAD

**Issue by warzen** [acemod/ACE3#2923]
Using the getAllHitPointsDamage function, I noticed that it is impossible to damage the neck, face, abdomen, chest, pelvis (at least).
All upper hits are going to the head section, all middle hits seems to be located on the body.
 
Tested: vanilla vs CBA+ACE 3.4.0.0 only, no specific ACE config
Target: B_Soldier_F
Weapon: PO7 9mm
 
Function used: https://community.bistudio.com/wiki/getAllHitPointsDamage

**Comment by BaerMitUmlaut** [comment]
ACE only sets hitpoint damage to show blood stains on the unit and sets all other hitpoints to 0 damage on purpose. Damage and wounds are handled internally.

Not a bug.
