### ISSUE TITLE
No Advanced Ballistics Documentation

### ISSUE THREAD

**Issue by sargken** [acemod/ACE3#2926]
Hi I was looking to create a compat mod for RHS that includes the updated rifles. I seen some variables i couldn't find documentation for ACE_barrelTwist, ACE_barrelLength, ACE_twistDirection. Plus the variables in the cfgammo cfg. I have no clue how to manipulate some of them. Not sure if this is a feature request but if you guys consider it one i can post it again.

**Comment by jonpas** [comment]
Tagging @alganthe

**Comment by alganthe** [comment]
My knowledge of the subject is unfortunately too insufficient to provide proper doc :/
