### ISSUE TITLE
how do i Re enable Thermals on the laser designator?

### ISSUE THREAD

**Issue by vuther316** [acemod/ACE3#2927]
How can i re enable thermals on the laser designator?

**Comment by commy2** [comment]
You wait for me to fix ref: https://github.com/acemod/ACE3/issues/2916

**Comment by PabstMirror** [comment]
They are disabled in laser module
https://github.com/acemod/ACE3/blob/master/addons/laser/CfgWeapons.hpp#L6

**Comment by commy2** [comment]
Wait, what?

**Comment by vuther316** [comment]
What is thermal called in the arma coding language. Can't find it anywhere.

**Comment by PabstMirror** [comment]
Vanilla config is:
```
class Laserdesignator: Binocular {
    visionMode[] = {"Normal","NVG","TI"};
};
```

**Comment by vuther316** [comment]
When i replace the line with that the mod will not start.

**Comment by vuther316** [comment]
It says (file path) expected -795076085 B, got 39994 B

**Comment by BaerMitUmlaut** [comment]
How exactly did you "replace" that line? You should do this with a patch PBO, not by fiddling around with ACE3's source.

**Comment by PabstMirror** [comment]
@BaerMitUmlaut is right, best to make a patch, otherwise you will have to rebuild every time we reelease a new version.

Just throw this into a config.cpp in a folder called `acetweak_ldThermals` on your p drive and build with pboProject:
```
class CfgPatches {
    class acetweak_ldThermals {
        units[] = {};
        weapons[] = {};
        requiredVersion = 1;
        requiredAddons[] = {"ace_laser"}; //This makes the patch apply after ace_laser applies it's modification
    };
};
class CfgWeapons {
    class Binocular;
    class Laserdesignator: Binocular {
        visionMode[] = {"Normal","NVG", "TI"}; //Re add thermal vision mode to LaserDesignator
    };
};
```

**Comment by vuther316** [comment]
What folder am i supposed to map the P: drive to? Also is the file supposed to be a PBO or a cpp file?

**Comment by PabstMirror** [comment]
You can also use addon builder from arma tools.
Otherwise you can just download a build from here: http://www.filedropper.com/acetweakldthermals
