### ISSUE TITLE
ACE Laser not working when laser designators in inventory. [rhs]

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#2928]
Using a bunch of other mods as well, but latest ACE3, CBA and arma 3. (03/12/2015).

"ACE_acc_pointer_green" Attachment on "rhs_weap_m4a1_carryhandle_grip" when spawned with "Rangefinder" or "Laserdesignator".

I'm sorry no better details and poor formating. I'll report this for now, but I can do some more testing with only ace3 and cba tomorrow.

**Comment by PabstMirror** [comment]
Probably same as #2916
Having a binocular equipped will reset gunlight.

**Comment by xJenny99x** [comment]
With vanilla ace3 and cba. lasers/lights do not work if there's anything in the binoculars gear slot.

**Comment by PabstMirror** [comment]
Fixed by #2935
