### ISSUE TITLE
ACE NVG does not work when aiming down sights

### ISSUE THREAD

**Issue by PabloElKillo** [acemod/ACE3#2930]
Steps to replicate:
1. put down vanilla NATO rifleman in editor
2. turn on NVG
3. aim down sights

**Comment by BaerMitUmlaut** [comment]
This is a feature that came with 3.4.0. You cannot use those dual tube NVGs we have in Arma with a weapon sight. Use nightvision scopes or the IR lasers instead.

If you don't want this feature you can disable it via the nightvision module or the ACE settings framework.
