### ISSUE TITLE
Modded weapon bipods do not work with ace enabled

### ISSUE THREAD

**Issue by moonmanmove** [acemod/ACE3#2933]
ACE3 Version: 3.4.0
Stable 1.54

Mods:
@CBA_A3
@ace
tested with:
@rhs
@3cb weapons
@bwa3

Placed ACE3 Modules:
None

Description:
When ACE is enabled, modded weapons' bipods do not work. 
Steps to reproduce:
Launch ARMA with ace cba and weapon pack of your choosing
Deploy bipod, notice it does not deploy the actual bipod and puts you in the "rested" stance instead
Launch arma with just cba and the weapon pack
bipods work

Where did the issue occur?
Everywhere

RPT log file:
N/A

**Comment by commy2** [comment]
Same as ref: #2916

Fix soon

**Comment by freghar** [comment]
> Deploy bipod, notice it does not deploy the actual bipod and puts you in the "rested" stance instead
This is actually incorrect. If you look carefuly, your position (ie. while prone) is slightly lower than what it would be with a simple rest, the body animation is also the one from deploying a bipod + the soldier icon indicates "hard mounted" (solid line, not dashed). When shooting, you get noticeably less recoil than with a simple rest, so the bipod is actually working, it just isn't visibly animated.

Also, it affects vanilla weapons and bipods as well.

**Comment by commy2** [comment]
fixed with #2935
