### ISSUE TITLE
Aiming up/down limited while moving

### ISSUE THREAD

**Issue by Gwynblade** [acemod/ACE3#2934]
ACE3 Version: 3.4.0

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
None

**Description:**
You can't aim high or low enough **while** moving. For example if you want to check gear from a dead guy, or ace interact with unconscious teammate, and you move an inch, your aim gets kicked up to a predefined limit. You don't have to aim, your weapon needs to be in a weapon ready position (2x C)
It's a problem when you're clearing stairs, but can't actually aim high enough in case anyone is waiting on the opposite side (check the video).

**Steps to reproduce:**
https://www.youtube.com/watch?v=4T0v-1ejdp0

**Where did the issue occur?**
Everywhere

I posted this in feature request first, but after chatting with Jonpas, he said it's ok to make an issue for this.

**Comment by jonpas** [comment]
Note: highly probable this got introduced with 1.54, must be some new config entry or something but I couldn't find it in a quick skim through.

**Comment by jonpas** [comment]
@Gwynblade checked Arma 3 1.52 combined with previous versions of CBA/ACE3 and it was there already, so it's something that was overlooked apparently.

**Comment by Radeni** [comment]
Its an Arma 3 issue,not Ace.Its in unmodded aswell so that isnt an issue for the ACE 3 team but for BI,its possible that they did it on purpose.

**Comment by Gwynblade** [comment]
Which is why I posted this in feature requests first (to remove the limits), and Jonpas gave me a go to post it in here. It even says so at the end of my first post.

BI did it (from what I know) because without limits players can look weird when (for example) aiming really low, crouching, and using freelook to turn the head high. You can get some ridicolous poses like that.

I'm politely asking to remove those limits again, because gameplay in my opinion is more important than soldiers looking pretty. And they will look normal anyway unless you're playing with people that want to abuse it.

**Comment by jonpas** [comment]
Seems like there is no config entry for that, probably linked with an animation or even hardcoded in teh engine. Assigning animation/config master @commy2.

**Comment by Gwynblade** [comment]
:+1:

**Comment by commy2** [comment]
I still don't know how to solve this. Probably not possible, or I'm overlooking something.
Pushing to back log, I'll keep my eyes open though.

**Comment by BaerMitUmlaut** [comment]
Tested, fixed. Probably a vanilla issue back then?
