### ISSUE TITLE
MicroDAGR GPS appearing too large in center of screen

### ISSUE THREAD

**Issue by manthedanville** [acemod/ACE3#2936]
ACE3 Ver: 3.4.0
ArmA3 build: stable branch
Mods: CBA_A3 and ACE
Modules: none
Description: The MicroDAGR appears large in the middle of the screen regardless of if it in the configuration mode or in the viewing mode.
Reproduce: Open the editor, place a unit and give them a MicroDAGR. Hit home to pull up the MicroDAGR interface and toggle between the two modes. The size and placement of the MicroDAGR does not change.

**Comment by PabstMirror** [comment]
You can set the position and size of the non-interactive interface.

Escape -> Configure -> Game -> Layout

And then look for the GPS window

![image](https://cloud.githubusercontent.com/assets/9376747/11601271/8e5161a0-9a97-11e5-8f48-a5ceb7c24dc6.png)

Drag and Resize to whatever you like and you'll have to close and reopen the device to take effect.

I do need to add this to the documentation.

**Comment by jokoho48** [comment]
@PabstMirror i can confirm this is a Bug

Repro as Reported

**Comment by jokoho48** [comment]
fixed in release Branch look like this issue with the binocular
