### ISSUE TITLE
Test effects of CBA's zeus keybindings / events

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#2937]
Just making note for myself:

https://github.com/CBATeam/CBA_A3/pull/206

https://github.com/acemod/ACE3/blob/master/addons/interact_menu/XEH_clientInit.sqf#L83-L105

And new event may be able to replace PFEH state checker

**Comment by commy2** [comment]
>And new event may be able to replace PFEH state checker
I'm not sure how relyable the unload event is. I think closing a display via `closeDialog` doesn't trigger them, but I'm not 100% certain if that happens to all displays.
