### ISSUE TITLE
Nightvision doesn't work with (any) scopes

### ISSUE THREAD

**Issue by fratzi** [acemod/ACE3#2943]
E.g. MRCO + Nightvision active 

No issue in vanilla.

**Comment by sargken** [comment]
To what i remember this is a feature now in ace. They disabled NVG from being used in optics. Like in real life.

**Comment by jokoho48** [comment]
This is a feature that came with 3.4.0. You cannot use those dual tube NVGs we have in Arma with a weapon sight. Use nightvision scopes or the IR lasers instead.

If you don't want this feature you can disable it via the nightvision module or the ACE settings framework.

**Comment by fratzi** [comment]
Well, even iron sights don't work, what should be possible afaik

**Comment by sargken** [comment]
You cant aim down the iron sights with nvgs in real life. Turn on your ir laser.

**Comment by fratzi** [comment]
Ok, thanks and keep on the good work!
