### ISSUE TITLE
Can´t use the Interaktion Menu 

### ISSUE THREAD

**Issue by Skymaster20** [acemod/ACE3#2946]
I can´t use the Interaction Menu after the 3.4.0 update, first i thought the other mods i used caused the bug, but then i started ACE alone (+CBA) and it still didn´t work, Then i thought there was a problem with the download so i downloaded it from Armaholic, but it still doesn´t worked. All other Ace stuff is available. I also dont get options shown when i use the ,,ACE Controls,, Button in the Mainmenu, i can acces the controlls thru the default arma Controls. And because i don´t realy know where and for what i schould search in the Files. And now i need help

**Comment by BaerMitUmlaut** [comment]
Make sure you are using the newest CBA as well.

**Comment by Skymaster20** [comment]
ok CBA was the problem thank you.
