### ISSUE TITLE
Interaction menu flashes on and off on vehicles

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2947]
ACE3 Version: 3.4.0

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* *-*

**Description:**
* On dedicated trying to interact with vehicles is very hard right now. Interaction menu will basically appear and disappear randomly, making it ultra hard to select any interaction with vehicles. Did not tested with other players but from what I heard from my community it seems to happen on unit's too (need to confirm that myself.*
* I'm gonna do video with it later.*

**Steps to reproduce:**
* *Try to interact with vehicles on dedicated.*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
* -.*

**Comment by jonpas** [comment]
It seems to be distance related, going closer seems to stop the flickering. It might be related to a lot of custom checks in refuel and rearm, just a hunch.

**Comment by jonpas** [comment]
Anyone else experiencing this? Should be moved to 3.4.1 if confirmed.

**Comment by PabstMirror** [comment]
I can't reproduce on dedicated.
What vehicles does it happen on.
Any specific interaction or just the main point?
Also could you post your settings?

**Comment by jonpas** [comment]
It happened on refuel nozzle for us, I will try to reproduce it later today.

**Comment by GitHawk** [comment]
@PabstMirror It happens as soon as an additional interact point gets close to the main interact point (e.g. in refuel)

**Comment by PabstMirror** [comment]
Should be solved via #4040
