### ISSUE TITLE
NVG conflicting With all Sights

### ISSUE THREAD

**Issue by SgtMikey** [acemod/ACE3#2951]
-ACE3 v.3.4.0
-stable
-mods:@cba_A3, @ace
-Base Game sights use /w NVGs

Hello, I would Like to Report a problem that me and my group. we have been experiencing a bug in 3.4.0. When ever you have NVGs activated and aim down sights (with and optic and iron sights) the NVGs turn of as if you are using a marksman/sniper optic. I've made sure to test it without my groups other mods, and it happened with just CBA and ACE3. Hope there will be a fix soon. Great mod so far, keep up the good work.

Steps to reproduce
-play any scenario with nvgs and any sights
-turn on NVGs and aim down sights

**Comment by havena** [comment]
same here

**Comment by jokoho48** [comment]
This is a feature that came with 3.4.0. You cannot use those dual tube NVGs we have in Arma with a weapon sight. Use nightvision scopes or the IR lasers instead.

If you don't want this feature you can disable it via the nightvision module or the ACE settings framework.

**Comment by havena** [comment]
thx for reply
