### ISSUE TITLE
Bipod deploying animations didn't work

### ISSUE THREAD

**Issue by narrundo** [acemod/ACE3#2953]
ACE3 Version: 3.4.0
-

Mods:
-

@CBA_A3
@ACE
@AllinArmaTerrain
@MCCSandbox

Placed ACE 3 Modules : 
-
none

Description:
-
when deploying bipod there is no animation even bipod already deployed but in my vision the bipod stay undeployed.

Steps to reproduce:
-
Deploy bipod while prone 

Where did the issue occur?
-
"Multiplayer", "Editor" or "Singleplayer"

**Comment by narrundo** [comment]
fixed problem caused by mcc sandbox mod

**Comment by commy2** [comment]
Nope. Bug in ACE. Duplicate of https://github.com/acemod/ACE3/issues/2933

**Comment by narrundo** [comment]
oh I thought it was caused by other mod

**Comment by commy2** [comment]
Close as dup. Fix soon.
