### ISSUE TITLE
Bipod and burst-fire failure with RHS

### ISSUE THREAD

**Issue by OnkelDisMaster** [acemod/ACE3#2957]
ACE3 Version: 3.4.0
Arma Version: 1.5.4

**Mods:**
* `@CBA_A3`
* `@ace`
* `@RHSUSAF`

**Description:**
If I enable RHS with ACE and CBA, the bipods and burst-mode do not work anymore, except I start with a unit, that has a weapon with a bipod by default

**Steps to reproduce:**
- start Arma with @ace;@CBA_A3;@RHSUSAF
- place a unit with a weapon without a bipod pre-attached
- grab a weapon from arsenal with a bipod (in my case some LMG)
- go prone and try to deploy bipod

**Where did the issue occur?**
* Editor & MP

PS: 
Since I don´t know which mod causes the failure, I reported the issue to RHS aswell:

http://feedback.rhsmods.org/view.php?id=1441

Edit:
RHS dev replied: "Please contact ACE3 compatibility people."

**Comment by FadiCBB** [comment]
Duplicates of #2918 and #2933. The problem though is actually #2916
