### ISSUE TITLE
Zeus-dragging an unconscious patient out of a vehicle makes him conscious

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#2962]
ACE3 Version: 3.4.0 stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
- Respawn Module

**Description:**
- zeus-dragging an uncon. guy out of a vehicle makes him conscious

**Steps to reproduce:**
- Shoot a dude to unconsciousness
- Load the unconscious patient into a vehicle
- Switch to zeus
- drag the patient out of the vehicle
- the patient is no longer unconscious

**Where did the issue occur?**
- Editor 

**RPT log file:**
http://pastebin.com/zC1W6iVy

**Comment by bux578** [comment]
https://youtu.be/xTINtM_fWSc

**Comment by SilentSpike** [comment]
Not sure if there's anything we can do about this, I guess we could add an event call to the zeus module which hooks into the zeus move events and then medical could add code to keep a unit properly unconscious after being moved

**Comment by PabstMirror** [comment]
Fixed in rewrite
