### ISSUE TITLE
Script error when "toggling unconsciousness" in zeus

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#2963]
ACE3 Version: 3.4.0 stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* Respawn Module

**Description:**
* When you use "Toggle unconsciousness" on a unit you'll see a script error

**Steps to reproduce:**
* Enter zeus
* use "Toggle unconsciousness" on a unit 

**Where did the issue occur?**
* Editor 

**RPT log file:**
http://pastebin.com/zC1W6iVy

**Comment by bux578** [comment]
https://youtu.be/xTINtM_fWSc

**Comment by SilentSpike** [comment]
Interesting, looks like the error is in rearm's `medical_onUnconcious` event handler somewhere

**Comment by bux578** [comment]
Tested and confirmed working
