### ISSUE TITLE
Can't load patient into the co-pilot seat of an AH-6

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#2965]
ACE3 Version: 3.4.0 stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
- Respawn Module

**Description:**
- You're not able to load a patient into the co-pilot seat of an AH-6 chopper. You get the option to load the patient when close to the chopper but nothing happens after selecting it.

**Steps to reproduce:**
- Shoot a dude to unconsciousness
- Have an AH-6 nearby
- Try to load the patient via the interaction menu -> "Load patient"
- Nothing happens

-> Expected result: The patient is loaded into the co-pilot seat

**Where did the issue occur?**
- Editor 

**RPT log file:**
http://pastebin.com/zC1W6iVy

**Comment by PabstMirror** [comment]
Ops, tagged wrong issue on that commit, this is still an issue.
AH-9's copilot is a little weird and doesn't show up on `emptyPositions` and we generally don't want to load someone into a turret slot.
