### ISSUE TITLE
Unconscious animation in quad is wrong

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#2966]
ACE3 Version: 3.4.0 stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
- Respawn Module

**Description:**
- When loading an unconscious unit into a quad bike a wrong animation is used

**Steps to reproduce:**
- Shoot a dude to unconsciousness
- Have a quad nearby
- Load the patient via the interaction menu -> "Load patient"
- Wrong animation is being used

**Where did the issue occur?**
- Editor 

![2015-12-07_00005](https://cloud.githubusercontent.com/assets/1235520/11638226/0e6c0e18-9d26-11e5-98f6-1111ce370842.jpg)

**RPT log file:**
http://pastebin.com/zC1W6iVy

**Comment by PabstMirror** [comment]
Should look at https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_getDeathAnim.sqf

I think the problem is that the quads have `ejectDeadCargo = 1` (very few vehicles have this, stuff like motorcycles, static weapons, and one of the boats), so they don't have a dead anim that makes sense.

Maybe we should respect that config and both not allow loading and eject unconscious people?

**Comment by esteldunedain** [comment]
> Maybe we should respect that config and both not allow loading and eject unconscious people?

Probably yes. In that case passengers should also be ejected by ACE when falling unconscious.

**Comment by RSpeekenbrink** [comment]
I agree with @esteldunedain 

Never saw a unconsious person being able to hold himself on a quad :+1:  :)

**Comment by bux578** [comment]
> Never saw a unconsious person being able to hold himself on a quad

![image](https://cloud.githubusercontent.com/assets/1235520/12716930/7ad5ed32-c8e4-11e5-84c4-8511fda27f27.png)

Just need enough duct tape :joy:

**Comment by Glowbal** [comment]
I feel this is an acceptable issue. I think allowing quads to transport unconscious units is desired and the animation is unfortunate - but when picking between not allowing unconscious units in the cargo of the quad and some weird animation displaying, I feel the weird animation wins in this case.

**Comment by commy2** [comment]
Imo we should go with: https://github.com/acemod/ACE3/issues/2966#issuecomment-170720184
It makes sense to me.

**Comment by PabstMirror** [comment]
This seems to be automatic in 1.62.
A unit with `setUnconscious` will be auto ejected from quads.

**Comment by Glowbal** [comment]
> A unit with setUnconscious will be auto ejected from quads.

Is this still the case? If so, we should close this.

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/blob/medical-rewrite/addons/medical_engine/functions/fnc_setUnconsciousAnim.sqf#L25

Medical rewrite will use `setUnconscious` - will be fixed when #4064 is merged
