### ISSUE TITLE
Filling the FIA offroad (armed) with two unconscious patients turns it civilian and unable to act

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#2967]
ACE3 Version: 3.4.0 stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
- Respawn Module

**Description:**
- When the armed varient of the FIA offroad gets loaded with two uncoscious units it turns civilian and ignores zeus move orders

**Steps to reproduce:**
- Spawn a blufor soldier and two unconscious units
- Have a  FIA offroad (armed) nearby
- Order the blufor soldier to get in to the offroad as the driver
- manually load the unconscious units in to the hatchback
- once the gunner sear is occupied the vehicle turns civilian
- it doesn't react to zeus move orders

**Where did the issue occur?**
- Editor 

**RPT log file:**
http://pastebin.com/dq7YeHm8

**Comment by bux578** [comment]
https://youtu.be/QSc3vKoVMAY

**Comment by SilentSpike** [comment]
Isn't it probably because they're unconscious? :stuck_out_tongue:

**Comment by PabstMirror** [comment]
The gunner becomes the `effectiveCommander` of the vehicle.
And he has ai disabled because he's unconscious.

biki:
>Returns the effective commander of the vehicle. Effective commander is the player whom driver AI will listen to. So if in a tank there is a gunner and a commander and AI driver, if the effectiveCommander is gunner, then gunner pressing WASD will give AI orders to move. If gunner jumps out and then enters tank again, the effectiveCommander role most likely has changed to commander that remained in tank. Also the assignment seems to work on first come first served basis.

We already prioritize cargo seats over gunner. No clue how to fix, feels like an engine limitation....

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 167 days without any activity.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
