### ISSUE TITLE
Can't use action menu with mouse1 when weapon safety enabled

### ISSUE THREAD

**Issue by Cuel** [acemod/ACE3#2968]
ACE3 Version: 3.4.0 stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
N/A

**Description:**
Not a very critical issue since I assume most people are using mouse3 for the action menu, but when you have weapon safety ON, you can't use action menu entries with mouse1.

Weapon safety overrides DefaultAction (firing weapon / selecting from action menu), a potential fix would be to check if action menu is active?

**Steps to reproduce:**
Turn weapon safety on, use action menu with mouse1

**Where did the issue occur?**
SP/MP

**Comment by PabstMirror** [comment]
Just to clarify: you're talking about the vanilla action menu, correct?

I tried binding Prim mouse Button to "Use Selected Action" and it seemed to work correctly with or without safety on.

**Comment by Cuel** [comment]
Yes, vanilla.
Is use selected action the default binding for it?

**Comment by PabstMirror** [comment]
I added a keybind for Primary Mouse Button to "Use selected action" and it seems to be working fine.

![image](https://cloud.githubusercontent.com/assets/9376747/11676123/09b10138-9df5-11e5-9f4a-1d64ef511443.png)

**Comment by Cuel** [comment]
Sure that works. But weapon safety will still block "use default action". That's what it overrides

**Comment by commy2** [comment]
>Sure that works. But weapon safety will still block "use default action". That's what it overrides

Huh? It works and it doesn't work?

**Comment by Cuel** [comment]
Mouse1 is not bound by default to "Use selected action", so it while it works, it's a workaround.
For someone who doesn't know this and doesn't have that key binding, if they turn ACE weapon safety on it will block mouse1 clicks in the action menu. The menu still closes so it suggests an action occured but the weapon safety would've blocked that action from happening

If what @PabstMirror posted is good enough, you can close this

**Comment by commy2** [comment]
I haven't encountered this issue, but the proposed solution "check if action menu is active" unfortunately doesn't work, because there actually is no way to know if the action menu is currently shown.

**Comment by Cuel** [comment]
Most people that have played arma for a while would know to use mouse3 (or similar) to use action menu entries to avoid misfire anyway :smile: 

Alright that sucks, thought it was possible to find it the menu.
Hypothetically the weapon safey could check if it fired in the same frame as an "Action" menu click? And then not block? [inGameUISetEventHandler](https://community.bistudio.com/wiki/inGameUISetEventHandler)

Just brain storming

**Comment by commy2** [comment]
`inGameUISetEventHandler` pls no

**Comment by Cuel** [comment]
Can probably close this then :+1:

**Comment by commy2** [comment]
krgr
