### ISSUE TITLE
Player dies at one shot

### ISSUE THREAD

**Issue by Doosan123** [acemod/ACE3#2971]
@ace3

The arma3 players dies at one shot with any weapons any body so , is this error ? or this is you were mean to be? if it's mean to be make like that how do we fix it ?

**Comment by VKing6** [comment]
http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by BaerMitUmlaut** [comment]
Please make sure you are using the newest version of ACE3 and CBA. Also, as @VKing6 already said, please use the correct formatting.

**Comment by commy2** [comment]
Closing in favour of #3006
