### ISSUE TITLE
Laser pointer is too big at distance

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#2975]
ACE3 Version: 3.4.1 RC

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* Respawn Module

**Description:**
* The Laser pointer point IMHO is too big at distance

**Steps to reproduce:**
* add the "Laser Pointer (green)" attachment from the ace3 misc box to your weapon
* switch the laser pointer on
* aim at a building some meters away
* the laser point is too big visually

**Where did the issue occur?**
* Dedicated Server

**RPT log file:**
n/a
![2015-12-08_00001](https://cloud.githubusercontent.com/assets/1235520/11661799/e5dfad34-9dd3-11e5-8681-f8d672f779a7.jpg)

**Comment by Gwynblade** [comment]
I don't know if any changes have been made in the last month regarding laser pointers, but about a month ago it had couple of problems, I made a short vid, but forgot to post it.

https://www.youtube.com/watch?v=cFkYetP---A

**Comment by commy2** [comment]
Fixed in release branch
