### ISSUE TITLE
Range on interaction point "Cut fence" for "Land_New_WiredFence_10m_F" too low

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#2976]
ACE3 Version: 3.4.1 RC

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* Respawn Module

**Description:**
* There's no "Cut Fence" option on fences with type "Land_New_WiredFence_10m_F"

**Steps to reproduce:**
* Aproach the fences on Stratis at the airbase
![image](https://cloud.githubusercontent.com/assets/1235520/11662002/fa90f426-9dd4-11e5-874d-0cec00f7155b.png)
* With the wirecutter equipped try to cut them

**Where did the issue occur?**
* Dedicated Server

**RPT log file:**
n/a

![2015-12-08_00002](https://cloud.githubusercontent.com/assets/1235520/11662030/18cff360-9dd5-11e5-9242-4d8b4cefe5d3.jpg)

**Comment by bux578** [comment]
Probably trivial, but for the sake of completeness

**Comment by PabstMirror** [comment]
Fence is cuttable, but it can be tough finding the interaction point.
There is only 1 action point per 10 meters of fence.

 - Look into adding more than 1 for long fences. (maybe try boundingBoxReal to guess x/y direction?)

**Comment by bux578** [comment]
The fences left and right of the one on the image are cuttable. This (close to the toilet box) is not.
