### ISSUE TITLE
Nightvision is behaving different on ACE3 optics

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#2977]
ACE3 Version: 3.4.1 RC

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* Respawn Module

**Description:**
* When using the vanilla ARCO or RCO the nightvision setting behaves as follows:
  * Turning the night vision goggles on and looking through the scope leaves night vision on (as per this hotfix)
* When using our 2D or PiP variants the behavior is different:
  * RCO:
    * You can seperately enable night vision for normal and for the scoped view
  * ARCO:
    * You can't enable night vision for this scoped view

**Steps to reproduce:**
* Try night vision with the different mentioned optics: ARCO/RCO (vanilla), RCO (2D) or (PiP), ARCO (2D) or (PiP)

**Where did the issue occur?**
* Dedicated Server

**RPT log file:**
n/a

**Comment by bux578** [comment]
https://youtu.be/EuNzq6U3k7s

**Comment by commy2** [comment]
Working as intended. This only way to not show the night visions vignette is to add the night vision mode to the optic itself. You can enable the night vision on these optics with nvgoggles.

Screenshot:
!(http://i.imgur.com/TKZ2l3g.jpg)[http://i.imgur.com/TKZ2l3g.jpg]

Close?

**Comment by bux578** [comment]
ARCO and RCO are behaving differently. Intended?

**Comment by commy2** [comment]
Yes. The ARCO has an illuminated reticle which wouldn't work with night vision. (It would look red even though everything else would be green.)

**Comment by bux578** [comment]
> You can enable the night vision on these optics without nvgoggles.

That's so broken ...

**Comment by commy2** [comment]
Well. You can't do anything about that except for disableing night vision altogether for these scopes, which I don't want.
