### ISSUE TITLE
Weapons don't overheat / overheat too slow

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#2978]
ACE3 Version: 3.4.1 RC

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* Respawn Module

**Description:**
* Weapons don't overheat anymore
* Swapping the barrel doesn't help

**Steps to reproduce:**
* Shoot a full belt of e.g. the Stoner 99 LMG `"LMG_Mk200_F"`
* Check weapon temperatur via the self interaction menu -> equipment

**Where did the issue occur?**
* Dedicated Server

**RPT log file:**
http://pastebin.com/1j5KraUb

**Comment by bux578** [comment]
https://youtu.be/DSAwwx-lyoY

**Comment by bux578** [comment]
Seems to work (but very slow) with the LWMMG `"MMG_02_camo_F"`

**Comment by PabstMirror** [comment]
Ref  #1853 and  #2317 (has some math calculation tables), and PR #146

**Comment by xJenny99x** [comment]
If I recall correctly there was also a bug when dropping a weapon and picking it up would reset all heat.
