### ISSUE TITLE
I want only unconscious not dead

### ISSUE THREAD

**Issue by kadir6185** [acemod/ACE3#2979]
Hi. 

i want only unconscious 

How can I do ?

**Comment by headedhorseman101** [comment]
Use the parent death module in ACE_Medical

**Comment by kadir6185** [comment]
Headedhorseman101 
Thanks for help me.
More specific please.

**Comment by headedhorseman101** [comment]
Go to the 2d editor. Path to module is Modules >> ACE_Medical >> Medical Settings >> prevent death

**Comment by kadir6185** [comment]
Try 

Thanks.
