### ISSUE TITLE
Gestures and Range Card double bound

### ISSUE THREAD

**Issue by SchwererKonigstiger** [acemod/ACE3#2981]
ACE3 Version: 3.4.0 / 3.4.1 RC (Issue present in both)

Mods:
@CBA_A3
@ace

Placed ACE3 Modules:
None

Description:
By default, the range card is brought up with control+numpad 5
Now, as per v3.4.0, there is a now a gesture bound to control+numpad #

The range card's default binding should be changed, or be removed. Pressing control+numpad 5 will bring up the range card, as well as activate the gesture. 

Issue is relatively minor, as players can just rebind one of the keys.
H

Where did the issue occur?

Dedicated Server/SP (Editor)

RPT log file: Not needed

**Comment by PabstMirror** [comment]
Rangecard keys default to unbound - https://github.com/acemod/ACE3/blob/master/addons/rangecard/initKeybinds.sqf

In CBA Keybind system you should be able to hit default and it will go blank.
