### ISSUE TITLE
Night Vision disapeared when a player takes aim (right mouse button)

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2983]
ACE3 Version: 3.4.0
Stable 1.54

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
None

**Description:**
After the latest updates (Nexus update and Hotfix 1.54) I noticed that activated night vision disappears, if the player is aiming using right mouse button.

**Steps to reproduce:**
Place player in the map at night and use Night Vision. After this use aiming by means right mouse button.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by bux578** [comment]
Fixed in 3.4.1

**Comment by mickeymen** [comment]
guys, I don't have time for your updates;  Super fast work, thank you
