### ISSUE TITLE
wget should use "--continue"!

### ISSUE THREAD

**Issue by rogerxxxx** [acemod/ACE3#2984]
update_rhsusf.bat
-- wget -m -nH --cut-dirs=2 --retry-connrefused --timeout=30 ftp://ftp.rhsmods.org/beta/rhsusaf/
++ wget --continue --cut-dirs=2 --mirror --no-host-directories --retry-connrefused --timeout=30 ftp://ftp.rhsmods.org/beta/rhsusaf/

1) Added "--continue" parameter.  (For obvious reasons, stopping a download should not have to revert to downloading for the first byte!  Reduces server loads.) 
2) I also switched "-nH" short option for the long option "--no-host-directories".  The same with "-m", the long option being "--mirror".  A underlying rule for short/long options, use the short options when typing via command line for less typing, and the long options for use within script files for easier reading.
3) Alphabetized wget's used parameters.

Implementation of "--continue" should likely be the priority, versus the other changes which are basically cosmetic, but dictate good coding style. ;-)

**Comment by BaerMitUmlaut** [comment]
yes, thanks

**Comment by jokoho48** [comment]
this is the ACE Issue Tracker not the RHS Issue Tracker Please repot it to them

**Comment by rogerxxxx** [comment]
Yup.  I was just filling out another bug report and just realized this as well.  Sorry. :-/

**Comment by commy2** [comment]
hahaha
