### ISSUE TITLE
Interaction, Self-Interaction Menu and Medical Menu Not Working

### ISSUE THREAD

**Issue by Rowantrek** [acemod/ACE3#2988]
When i use any of my key binds for those menus nothing happens. When i am in a vehicle and try to use the interaction menu a cursor pops up but nothing else.

RPT Logs: http://pastebin.com/0d7zP2Xy

I have tried reinstalling ace and getting the exact same @ace file from the server i play on. Nothing has worked i have the latest CBA_A3 and i have put the auto_xeh into the addons folder. Any help will be appreciated

**Comment by bux578** [comment]
http://ace3mod.com/wiki/user/how-to-report-an-issue.html

> please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using only @CBA_A3 and @ace on a newly created mission.

**Comment by commy2** [comment]
Update your `CBA_A3` to 2.2.x and then try to reproduce again with only CBA + ACE enabled.
If that still doesn't work, then post the RPT again.

**Comment by Rowantrek** [comment]
Thanks @commy2 the update of CBA_A3 worked.
