### ISSUE TITLE
Repair vehicle

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#2991]
ACE3 Version: 3.4.0

Mods:
@CBA_A3
@ace
@:RHS
Placed ACE3 Modules:
Adds Spare Parts
Assign Engineer
Assign Repair Facility
Assign Repair Vehicle
Repair Settings

Description:
Can you make invdividual menu for vehicles ,in which you can choose separate part for repairing. And also,pls make opportunity to prohibit repairing one or another part by choice of mission maker. One looming question - when you remove the caterpillar(track),why does wheel appear? Logically it should be corrected. Finally, please rename these words "Remove Wheel" in these "Remove track".

Where did the issue occur?
Multiplayer

**Comment by headedhorseman101** [comment]
>can you make individual menu for vehicles

This is a feature request. This can be placed in #414 as I said earlier. But still, :+1: on the idea

>when you remove the track, why does wheel appear?

THIS is what we are looking for in the bug report. Thank you for your feedback. Do you have any steps to reproduce and a list of your modules and accompanying values?

**Comment by headedhorseman101** [comment]
Also, please test with only `@ACE3, @CBA_A3` Activated. Please make a reply to see if the issue persists on the vanilla vehicles.

**Comment by PabstMirror** [comment]
This happens on RHS vehicles? What vehicle name or classname?

**Comment by Kartaviy** [comment]
https://youtu.be/aDIfSISvuaU
Can't use menu
https://youtu.be/A95bPeYUGTA
Toolkit doesnt dissapear after usage.In modules,I made config of one time usage.

"when you remove the track, why does wheel appear?"
This problem disappeared after switching to 3.4.1

**Comment by Glowbal** [comment]
Was fixed in #3011
