### ISSUE TITLE
FV510 Warrior 30mm MP-T low/no dmg

### ISSUE THREAD

**Issue by herchie** [acemod/ACE3#2992]
ACE3 Version: 3.4.2.0 -stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
- None

**Description:**
- FV510 Warrior 30mm MP-T shells do almost no dmg. Only on direct hit, and even then it´s a coin toss.
  Looks like the MP-T hasn´t got no shrapnels/ explosiv effects at all (despite the animation)

**Steps to reproduce:**
- Editor---> spawn FV510 Warrior (Independent/Armored) ---> spawn enemy Soldier

**Where did the issue occur?**
- Multiplayer, Editor

**RPT log file:**
- http://pastebin.com/kpwUU9iK

**Comment by bux578** [comment]
http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by PabstMirror** [comment]
```
if((_explosive > 0.5 && {_indirectRange >= 4.5} && {_fragPower >= 35}) || {_force == 1} ) then {
```
to trigger frag, but this is what the ammo is:
`_explosive=0.6, _indirectRange=1, _fragPower=6, _force=0`

It is a MP-T round instead of HE (B_30mm_HE has a much higher inderect fire range)

We could force on frag for these 30mm rounds, but I'm not sure if that's realistic?

**Comment by herchie** [comment]
Accourding to MP-T/SD descripton there should be light blast/fragmentation effects on target....nothing High Ex. but i think at least some blast/fragmentation dmg should be appropiate?

**Comment by herchie** [comment]
Edit: .rpt has been added // Version is now 3.4.2.0. -stable

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
