### ISSUE TITLE
Some gestures don't work when binded

### ISSUE THREAD

**Issue by WadeDP** [acemod/ACE3#2999]
ACE3 Version: 3.4.1 stable

**Mods:**
* @CBA_A3
* @ace

**Placed ACE3 Modules:**
N/A

**Description:**
The unbinded gestures don't work when they are binded to something, tested with only CBA and ACE. 
**Steps to reproduce:**
Bind unbinded gestures and test if the hot key works.

**Where did the issue occur?**
Anywhere.

**RPT log file:**
N/A

Also would recommend to have a setting to remove gestures action from self-action menu.

**Comment by PabstMirror** [comment]
Will be fixed by #2987
