### ISSUE TITLE
he level of armor 1 to 5 in vest wut does that mean for and how can i fix that ?

### ISSUE THREAD

**Issue by Doosan123** [acemod/ACE3#3002]
he level of armor 1 to 5 in vest wut does that mean for and how can i fix that ? normal vest also dies in one shot at body.

**Comment by Glowbal** [comment]
I am not quite sure what you are asking. Vests have an armor level. The higher that level, the more armor it has. It's a BI value..

**Comment by Doosan123** [comment]
I mean you are saying that vest has an armor lvl right? So can we modify this armor lvl thing.

**Comment by bux578** [comment]
Maybe you should join our [public chat](http://slackin.ace3mod.com/) or ask that question on the [forum](https://forums.bistudio.com/topic/181341-ace3-a-collaborative-merger-between-agm-cse-and-ace/) so we don't abuse the github issues.
