### ISSUE TITLE
Improvements to the map marker system

### ISSUE THREAD

**Issue by kuerbisdome** [acemod/ACE3#3015]
Hey Guys,
I recently discovered swatSTEAM's Sweet Markers System and was wondering if it was possible for you guys to add similar fuctionality to the existing ACE3 marker system (e.g. drawing ellipses and rectangles, better selection for symbols and colors, changing stroke size when drawing lines, etc.). 

Maybe it would even be possible to get permission for implementing Sweet Markers System into ACE?

Cheers,
Marshal_Jud

P.S.: Armaholic Link for Sweet Markers System http://www.armaholic.com/page.php?id=27012

**Comment by jokoho48** [comment]
#414
