### ISSUE TITLE
Blasting charges using the mouse scroll menu

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#3016]
The activation codes of explosive charges using a mouse wheel is much more convenient and faster. So please do the activation code blasting using mouse scroll menu.

**Comment by vlad8011** [comment]
Agree, it was much better. Or smillar method that was in ACE 2. Dont like the detonators method, when you are placing charge it should be with detonator automaticly.

**Comment by GalNa** [comment]
Yes. smillar method that was in ACE 2.

**Comment by bux578** [comment]
Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
