### ISSUE TITLE
RHS Javelin invincible

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#3017]
Thanks to http://www.darkgovernment.com/news/javelin-fgm-148-anti-tank-weapon/ [^] For basic limitations showed on Javelin, and @Bad_Tankman from RHS bug tracker. If i stand near the wreck on fire, javeling isnt capapble of aiming me (should not be), but actually it is.

"The NVS uses the infrared naturally emitted from objects. Infrared crossover is the time at dawn and dusk that the terrain and the target are close enough in temperature to cause the target to blend in with its surroundings. If there is little difference in the amount of infrared energy between a target and its background, then neither the Javelin CLU nor the missile seeker can see the target well, thus greatly degrading the performance of the Javelin.

- This situation may last as long as an hour, until either the background or the target changes temperature enough to become detectable.

- Natural clutter is when the sun heats objects to a close enough temperature that it causes the target to blend in with the surrounding terrain.

- Artificial clutter occurs when there are man-made objects that emit large amounts of infrared (for example, burning vehicles).

- Heavy fog reduces the capability of the gunner to detect and engage targets" 

----------------------------------------------------------------------------------------------------------

For now there is no possible way to defend against javelin missle, including the lock on.

- "The gunner must have line of sight for the seeker to lock onto a target."

^Ai is shooting from vegetation (behind bushes) - i am not able to kill him, beacuse bohemia got idea to make bushes from steel (protect soldeir from every weapon when he is in/behind the bush)

- "During limited visibility (natural or man-made), rain, snow, sleet, fog, haze, smoke, dust, and night are collectively referred to as limited visibility conditions. The day FOV can be rendered useless during these conditions."

^ Actually Javeling is capable of aquiring every target at every conditio

**Comment by jonpas** [comment]
Thanks for the good description, but this is a feature request #414.

> ^Ai is shooting from vegetation (behind bushes) - i am not able to kill him, beacuse bohemia got idea to make bushes from steel (protect soldeir from every weapon when he is in/behind the bush)

This is supposed to be fixed in 1.56.
