### ISSUE TITLE
230mm Rockets and CAS not working in Zeus placed fire support

### ISSUE THREAD

**Issue by PabloElKillo** [acemod/ACE3#3019]
When using 230mm rockets and CAS in Zeus, no damage is done to units or buildings.

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by PabloElKillo** [comment]
Apologies. Turns out this is an Arma bug. I should have tested without mods first.
