### ISSUE TITLE
Self Interaction Menu and Medical Menu Not Working

### ISSUE THREAD

**Issue by WarLikesGamers** [acemod/ACE3#3024]
ACE3 Version: 3.4.1
Stable

**Mods:**
@CBA_A3
@ace
@RHSUSAF
@RHSAFRF
@task_force_radio
@AllInArmaTerrainPack
@mcc_sandbox

**Placed ACE3 Modules:**
None

**Description:**
When people go to use the self-interaction menu it wont show up but they can use other uses like gun on your back.  But they cant heal or interact. It also works in map but not character.

**Where did the issue occur?**
Multiplayer, Singleplayer

**Steps to reproduce:**
Left Ctrl+Windows

**RPT log file:**
None On It

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by WarLikesGamers** [comment]
Ok Fixed It

**Comment by WarLikesGamers** [comment]
Fixed the post I meant

**Comment by dixon13** [comment]
did you put the cba_enable_auto_xeh.pbo in the main addon folder in @CBA_A3? Give that a try because the issue sounds like one of the mods doesn't support CBA's Extended Event Handlers and so ACE won't properly initiate on players.

**Comment by PabstMirror** [comment]
Please start the game, reproduce the error and then hit escape and open ace options and hit the debug button.

Then look for the rpt log here `%localappdata%/Arma 3/` which is something like
 `C:\Users\yourName\AppData\Local\Arma 3` then just look for the most recent *.rpt.

You can upload it here: https://gist.github.com/
This log has critical debug info in them that we need.


Also please try with just CBA and ACE.  
If it works then you will want to add `cba_enable_auto_xeh` like dixon mentioned.
Also please try changing the keybind for self interaction as some keyboard may have problems with the windows key.  Do you still get a red circle indicator when self interaction?

**Comment by serialtasted** [comment]
Update CBA to latest version and try again. https://github.com/CBATeam/CBA_A3/releases

**Comment by WarLikesGamers** [comment]
I have the correct CBA but sorry for the late reply.  We all have the new versions but my ACE works but for everybody else it doesn't.  When they join my server picks up they have an older version but they updated to the newest but i will try your suggestions and get back to you.

**Comment by PabstMirror** [comment]
@WarLikesGamers are you still having issues with this?

**Comment by WarLikesGamers** [comment]
No
