### ISSUE TITLE
 MANPADS cfg

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#3035]
How can i make configuration for MANPADS missile flight?This can be done for you?
http://www.youtube.com/watch?v=pxdFtVhE3IY - impossible to get there

**Comment by VKing6** [comment]
1: The video shows an ATGM not a MANPADS.
2: You can't; SACLOS guidance for ATGMs isn't implemented yet.
3: That looks like a third-party weapon. Contact the addon maker.

**Comment by Kartaviy** [comment]
http://ace3mod.com/wiki/framework/missile-guidance-framework.html

How do I set up a shell to the "Metis-M"?

**Comment by commy2** [comment]
I don't think this belongs on the issue tracker.
Feel free to join the ACE Slack if the questions are still relevant.
slackin.acemod.com
