### ISSUE TITLE
CUP CH53 and C17 Interaction Point Position

### ISSUE THREAD

**Issue by tebsu** [acemod/ACE3#3044]
Well, i guess it is there but i am having a problem finding it on the CUP Units CH53 and the USAF C17. In Slack, someone said, the interaction point is in the middle of the bounding box. I could explain the problem with that the C17 is too wide, but i cannot drive into the C17 with my Fueltruck to refuel it if the point is somewhere there. And i dont know about the CH53 which is smaller than the C130. It would be nice, if we would have the possibility to change the interaction point location with a command

**Comment by jokoho48** [comment]
Mod Fault will be fixed from CUP

**Comment by tebsu** [comment]
and what about the USAF C17 ? and the USAF C130? I think it will be a problem to always rely on the modder. Some might not respond and then, we have a problem because we cant refuel those aircraft. Thats why there should be a function to manually change or create that interaction point if it doesnt show

**Comment by jokoho48** [comment]
Mod Fault Please Report it to the Author

**Comment by tebsu** [comment]
Developer says he contacted the ACE team but didnt get any reply.
