### ISSUE TITLE
Please make tollbox usable without backpack.

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#3053]
I'm tired of looking for deadbodies everytime i wanna repair the vehicle. In the open field, armored warfare, no infantry around - we have to get backpack just to use toolbox - its sick limitation. My suggestion is:
- Give player ability to take toolbox in the hands (same as spare track link or wheel).
- If player want repair the damaged track, wheel he need to put repair kit and the wheel in radious of damaged component in order to repair it.
- If player want to repairany other damaged component he need to have toolbox in hands or nex to himself and vehicle.

**Comment by commy2** [comment]
>Give player ability to take toolbox in the hands (same as spare track link or wheel).

I don't think this is possible.

**Comment by BaerMitUmlaut** [comment]
Not really unless we add a static object which would disable putting it into backpacks though. With that, `nearestObject` and `distance` it would possible.

Anyways, this is a feature request and should go into #414.
