### ISSUE TITLE
A bug with grenades from the studio RHS.

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#3054]
ACE3 Version: 3.4.1

Mods:
* `@CBA_A3`
* `@ace`
*`both mods @RHS`

Description:
RGN (RGO) impact grenades firing shrapnel immediately after the throw.  https://youtu.be/ZA-mEr2y0-k
The vanilla RHS without ACE this does not happen.

**Comment by jokoho48** [comment]
that more look like a "New Feature" from RHS. Please Report it the RHS

**Comment by GalNa** [comment]
This only happens if you use ACE.

**Comment by GalNa** [comment]
In the previous edition of the RHS this grenades produce sounds falling directly into during the throw. https://youtu.be/ZA-mEr2y0-k
In the current update RHS they hit silently.

**Comment by SilentSpike** [comment]
Apparently Iron Front had the same problem before

**Comment by TheConen** [comment]
Long known problem, see https://forums.bistudio.com/topic/185587-ace3xrhs-fragmentation-configs/

#3045 should fix this

**Comment by bux578** [comment]
@jokoho48 Fragmentation is an ACE3 thing

**Comment by GalNa** [comment]
But it just takes away the fragmentation.

**Comment by GalNa** [comment]
@TheConen But it just takes away the fragmentation.

**Comment by vlad8011** [comment]
Agree with ticket author. It is just like shooting from the shotgun in the way i throw grenade.

**Comment by PabstMirror** [comment]
#3045
