### ISSUE TITLE
EDEN editor camera not able to move after preview when ACE3 is loaded

### ISSUE THREAD

**Issue by VyMajoris** [acemod/ACE3#3055]
Whenever you return from previewing your mission on the Eden editor, your camera gets stuck with a color overlay. 

Mods:
ace 3.4.1;
cba 2.2.0;

This is how the editor looks like after returning to it: http://i.imgur.com/9uMT8Qi.png

Relates to this: http://feedback.arma3.com/view.php?id=25977#bugnotes

**Comment by PabstMirror** [comment]
Fixed via #3041, will be in next release.
