### ISSUE TITLE
M119

### ISSUE THREAD

**Issue by zebra1993** [acemod/ACE3#3056]
Is there a Plan to Update the M119 Howitzer to ACE3? RHS just implemented it in the last update, but it's shiped with the Artillery computer per default. The Old way to work with it was much more Intense but more Fun.

**Comment by SchwererKonigstiger** [comment]
As has been said before, any features in the old A2 version of ACE will be ported, and the artillery changes is one of them.
They are being worked on, but it will take some time. Don't expect the artillery stuff anytime soon, but a lot of modelling work and other stuff has been done by Jonpas.

**Comment by bux578** [comment]
> has been done by Jonpas 

Hm ... I don't think so :)

**Comment by jonpas** [comment]
Nope, that's not what I did. :p
You probably mean @jokoho48

**Comment by jokoho48** [comment]
no @p1nga currently did some work in that direction ;)

**Comment by p1nga** [comment]
i think i should pass it on too @NouberNou,  feels like a game of tag, where will it go next???

**Comment by commy2** [comment]
#414 close ?

**Comment by zebra1993** [comment]
thanks for the fast and good answering. I'm looking forward to the day when it'll be implemented. Thanks for the Hard work and awesome mod you are working on
