### ISSUE TITLE
TI/NVG

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#3063]
this disableTIEquipment false

Please do the possibility that if "Ti" turn off, then this place has been included "NVG".
Or you can add a night sights for armored vehicles RHS?

**Comment by BaerMitUmlaut** [comment]
If you want to disable NVG equipment, use [`disableNVGEquipment`](https://community.bistudio.com/wiki/disableNVGEquipment).

>Or you can add a night sights for armored vehicles RHS?

No, if you have an issue with RHS vehicles, please use their bugtracker.

**Comment by commy2** [comment]
Uhm, close?
