### ISSUE TITLE
Soldiers cant run

### ISSUE THREAD

**Issue by tebsu** [acemod/ACE3#3068]
We sometimes have it, that soldiers were injured and our medics heal them. Problem is, sometimes they cant run anymore and we have to use "player setDamage 0" global execute to make him run again. I am not a medic so i dont know if our medics do something wrong but i guess that is not a bug. Can someone confirm it?

**Comment by dixon13** [comment]
I believe if a player is hurt too bad, the player will not be able to run and will have limited mobility. All part of the ACE medical system. Also, for future reference please follow the guidelines on how to report an issue, which can be found [here](http://ace3mod.com/wiki/user/how-to-report-an-issue.html).

**Comment by xJenny99x** [comment]
mission_ace3_legs = true;
if (hasInterface) then {
	if (mission_ace3_legs) then {
	fix_legs = ["leg_fix","<t color='#ff0000'>Apply splint to broken leg</t>","",{[10, [], {player setHitPointDamage ["HitLegs", 0];}, {}, "Fixing Legs"] call ace_common_fnc_progressBar;},{(player getHitPointDamage "HitLegs") >= 0.5}] call ace_interact_menu_fnc_createAction;
	[typeOf player, 1, ["ACE_SelfActions"], fix_legs] call ace_interact_menu_fnc_addActionToClass;;};
};

A workaround I've been using for this. Can't be arsed to PAK somone for 5 minutes, as this seems to happen all the time.

I think if you enable heal hitpoint after bandaging, this might be avoided completely.

**Comment by TheGrandVizier** [comment]
"I think if you enable heal hitpoint after bandaging, this might be avoided completely."
This is how my group uses it to avoid excessive leg breakage.

**Comment by PabstMirror** [comment]
Please try the `ace_medical_healHitPointAfterAdvBandage` setting ("Heal fully bandaged hitpoints").

This will reset damage on hitpoints once there are no wounds on them. This makes bandaging much more like basic medical.  By default you are simply stopping the bleeding but the damage remains.

```
// If all wounds to a body part have been bandaged, reset damage to that body part to zero
// so that the body part functions normally and blood is removed from the uniform.
```

Another option is to give medicals "Personal Aid Kits" (PAKs): http://ace3mod.com/wiki/feature/medical-system.html#2-2-1-14-pak

Check the advanced medical module for setting conditions on when these can be used (can limit to only certian locations or doctors...).

These literally do `_target setDamage 0;` which sounds like what you might want.
