### ISSUE TITLE
Error ace_advanced_ballistics.dll is'nt installed

### ISSUE THREAD

**Issue by theriotrhino** [acemod/ACE3#3071]
I am trying to make a mission just for fun and every time i go to load the mission it tells me i dont have ace_advanced_ballistics.dll im not sure if it is there or not but please help me

**Comment by madpat3** [comment]
Should be in this folder:
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@ace

**Comment by theriotrhino** [comment]
See thats what i was thinking it is there but for some reason the game is
not reading it or something

The icon for it is a paper with gears on i right?

**Comment by theriotrhino** [comment]
Fixed! It was all my fault for being a noob 

i was placing the pbo files straight into the addons folder instead of putting @ace in the arma 3 folder

**Comment by theriotrhino** [comment]
nvm lol im trash

**Comment by SilentSpike** [comment]
Hey, glad to hear this was resolved :smile: :+1:

**Comment by SilentSpike** [comment]
I usually find the fixes to my problems after posting about them too, don't worry about it :wink:
