### ISSUE TITLE
Bug FCS(ace) or Bug RHS?

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#3073]
small slope surface
https://youtu.be/TFqfEAJklQk
Smooth surface
https://youtu.be/g0ch4m2QHAk

**Comment by dixon13** [comment]
Have you tried testing without RHS? Try testing with only CBA and ACE, and make sure you have the latest installed.

**Comment by dixon13** [comment]
Also, if you find nothing wrong when testing with just ACE and CBA. Try testing with RHS, ACE, and CBA; and make sure you move the RHS compatibility PBO's into the addons folder, which can be found in the optionals folder.

**Comment by Kartaviy** [comment]
Will  be test RHS+ACE+CBA

**Comment by sargken** [comment]
That is RHS fire control systems. They are built in house by them,

**Comment by commy2** [comment]
^ , not our FCS. Close?
