### ISSUE TITLE
RHS 0.4.1 cannot repair tracks again.

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#3075]
After extracting spare track link, and putting it next to the damaged track, having toolbox in backpack, action to repair track is nor appearing, other components work fine. Tested on USMC abrams.

**Comment by PabstMirror** [comment]
![2015-12-25_00001](https://cloud.githubusercontent.com/assets/9376747/12004144/94e3c17c-ab07-11e5-970a-2b33efa03784.jpg)

I couldn't reproduce, which specific tank classname was it?
Could you also post RPT.

**Comment by vlad8011** [comment]
Desert USMC Abrams, not US army.

**Comment by vlad8011** [comment]
[arma3_2015-12-26_12-42-56.zip](https://github.com/acemod/ACE3/files/72430/arma3_2015-12-26_12-42-56.zip)

**Comment by vlad8011** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=584241426

**Comment by Glowbal** [comment]
>  fault of vehicle freezenig bug

Can you elaborate on that?

**Comment by vlad8011** [comment]
It seems to be not Ace fault, but Arma 3 or AiA terrains, but who knows.
http://feedback.arma3.com/view.php?id=26397

**Comment by commy2** [comment]
https://github.com/CBATeam/CBA_A3/pull/226 : - )
