### ISSUE TITLE
Few bugs with a ladder

### ISSUE THREAD

**Issue by ivankrouglyi** [acemod/ACE3#3077]
1) While another player is on the tactical ladder, i can move the ladder with him - can run with ladder, can put it on the ground. It looks strange when there is 5 troopers on the ladder.
2) While another player is on the tactical ladder, i can take ladder to my inventory and it will break his animation - he can't do anything. If i put it back (near the player) he can choose (with mouse wheel) to climb it again and animation will be fixed

**Comment by jonpas** [comment]
Working on this now.
