### ISSUE TITLE
Stringtable error

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#3080]
ACE3 Version: 3.4.1
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**

**Description:**
Stringtable error

**Steps to reproduce:**
-

**Where did the issue occur?**
* "Multiplayer", "Editor", "Singleplayer"*

**RPT log file:**
1:35:29 Unexpected stringtable format inside `<Text ID="STR_ACE_Common_CheckPBO_Action_WarnPerm"><German>`

**Comment by jokoho48** [comment]
its allready fixed in master
https://github.com/acemod/ACE3/commit/6f0568c370eca37354dea2f1e642f56aac41467c
