### ISSUE TITLE
TriageStatus change script error

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#3087]
"\Addons\ace_medical\z\ace\addons\medical\config.cpp"

Change triagestatus an get scripterror.
For example here, look at "ace_medical_TriageCardTargetsetvariable":

class selectTriageStatusNone: selectTriageStatus
		{
			idc = 2002;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			text = "$STR_ace_medical_Triage_Status_None";
			style = 2;
			size = "(((((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
			SizeEx = "(((((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
			animTextureNormal = "#(argb,8,8,3)color(0,0,0,0.9)";
			animTextureDisabled = "#(argb,8,8,3)color(0,0,0,0.9)";
			animTextureOver = "#(argb,8,8,3)color(0,0,0,0.9)";
			animTextureFocused = "#(argb,8,8,3)color(0,0,0,0.9)";
			animTexturePressed = "#(argb,8,8,3)color(0,0,0,0.9)";
			animTextureDefault = "#(argb,8,8,3)color(0,0,0,0.9)";
			action = "[false] call ace_medical_fnc_dropDownTriageCard; ace_medical_TriageCardTargetsetvariable ['ACE_medical_triageLevel',0,true];";
		};

**Comment by commy2** [comment]
I don't see any errors here. Thats a config. Can you provide a RPT file and some repro steps?

**Comment by shukari** [comment]
action = "[false] call ace_medical_fnc_dropDownTriageCard; ace_medical_TriageCardTargetsetvariable ['ACE_medical_triageLevel',0,true];";

MUST BE

action = "[false] call ace_medical_fnc_dropDownTriageCard; ace_medical_TriageCardTarget setvariable ['ACE_medical_triageLevel',0,true];";

**Comment by shukari** [comment]
rpt log ->
12:56:54 Error in expression <ace_medical_TriageCardTargetsetvariable ['ACE_medical_triageLevel',1,true];>
12:56:54   Error position: <['ACE_medical_triageLevel',1,true];>
12:56:54   Error Fehlendes ;

**Comment by Glowbal** [comment]
It's not like that in [source](https://github.com/acemod/ACE3/blob/master/addons/medical/ui/triagecard.hpp#L134). Could you please provide a full rpt log file, including the versions from ACE with some repo steps? Is this a custom build of ACE or did it come off an official source (our github release for example)?

**Comment by shukari** [comment]
12:56:13 [ACE] (common) INFO: ACE is version 3.4.1.0.
12:56:13 [ACE] (common) INFO: Extension version: ace_break_line: 3.2.0-bf4e95e
12:56:13 [ACE] (common) INFO: Extension version: ace_parse_imagepath: 3.2.0-bf4e95e
12:56:13 [ACE] (common) INFO: Extension version: ace_clipboard: 3.2.0-bf4e95e
12:56:14 [ACE] (common) INFO: Extension version: ace_fcs: 3.2.0-bf4e95e
12:56:14 [ACE] (common) INFO: Extension version: ace_advanced_ballistics: 3.2.0-bf4e95e
12:56:14 [ACE] (nametags) INFO: TFR Detected.
12:56:14 [ACE] (common) INFO: Settings received from server.
12:56:14 [ACE] (common) INFO: Check-PBOs Module Initialized. Mode: 0.
12:56:14 [ACE] (map) INFO: Blue Force Tracking Module Initialized:
12:56:14 [ACE] (switchunits) INFO: Switch Unit Module Initialized.
12:56:14 [ACE] (hearing) INFO: Hearing Module Initialized.
12:56:14 [ACE] (map) INFO: Map Module Initialized.
12:56:14 [ACE] (interaction) INFO: Interaction Module Initialized.
12:56:14 [ACE] (map_gestures) INFO: Map Gestures Module Initialized.
12:56:14 [ACE] (nametags) INFO: Nametags Module Initialized.
12:56:14 [ACE] (respawn) INFO: Rallypoint Module Initialized.
12:56:14 [ACE] (respawn) INFO: Respawn Module Initialized.
12:56:14 [ACE] (viewdistance) INFO: View Distance Limit Module Initialized. Limit set by module: 8000
12:56:14 [ACE] (sitting) INFO: Sitting Module Initialized.
12:56:14 [ACE] (explosives) INFO: Explosive Module Initialized.
12:56:14 [ACE]: Rearm Module Initialized on level: 2
12:56:14 [ACE]: Refuel Module Initialized with flow rate: 10
12:56:14 [ACE] (cargo) INFO: Cargo Module Initialized.
12:56:14 [ACE] (repair) INFO: Repair Module Initialized.
12:56:14 [ACE] (common) INFO: Settings initialized.
12:56:14 [ACE] (common) INFO: 130 delayed functions running.
12:56:16 Fresnel k must be >0, given n=2.51,k=0
12:56:18 Ragdoll - loading of ragdoll source "Soldier" started.
12:56:18 Ragdoll - loading of ragdoll source "Soldier" finished successfully.
12:56:20 "[SETUP] initArsenal - fertig!"
12:56:20 "[SETUP] initArsenal - fertig!"
12:56:21 [ACE] (interact_menu) INFO: All compile checks passed
12:56:26 "[error pos] mapchecker aus gelaufen!"
12:56:54 Error in expression <ace_medical_TriageCardTargetsetvariable ['ACE_medical_triageLevel',1,true];>
12:56:54   Error position: <['ACE_medical_triageLevel',1,true];>
12:56:54   Error Fehlendes ;
12:56:54 Error in expression <ace_medical_TriageCardTargetsetvariable ['ACE_medical_triageLevel',1,true];>
12:56:54   Error position: <['ACE_medical_triageLevel',1,true];>
12:56:54   Error Fehlendes ;
13:11:05 Error in expression <ace_medical_TriageCardTargetsetvariable ['ACE_medical_

**Comment by shukari** [comment]
unpbo with:
ExtractPBO 2.14
PboDLL 5.24

**Comment by jokoho48** [comment]
`action = "[false] call ace_medical_fnc_dropDownTriageCard; ace_medical_TriageCardTargetsetvariable ['ACE_medical_triageLevel',0,true];";`

i can confirm that there is a issue. this is direct out of the config.
look like a Macro issue

**Comment by commy2** [comment]
add another space

**Comment by PabstMirror** [comment]
```
test1 = QUOTE(GVAR(TriageCardTarget) setVariable [ARR_3('ACE_medical_triageLevel', 3, true)];);
test2 = QUOTE(GVAR(TriageCardTarget)  setVariable [ARR_3('ACE_medical_triageLevel', 3, true)];);
test3 = QUOTE((GVAR(TriageCardTarget)) setVariable [ARR_3('ACE_medical_triageLevel', 3, true)];);
test4 = QUOTE( SETPVAR(GVAR(TriageCardTarget), QGVAR(triageLevel), 3) );

```
pboProject'ed and extracted:
```
test1 = "ace_medical_TriageCardTargetsetVariable ['ACE_medical_triageLevel',3,true];";
test2 = "ace_medical_TriageCardTargetsetVariable ['ACE_medical_triageLevel',3,true];";
test3 = "(ace_medical_TriageCardTarget) setVariable ['ACE_medical_triageLevel',3,true];";
test4 = "ace_medical_TriageCardTarget setVariable [""ace_medical_triageLevel"",3,true]";
```

make.py version of 4 works, but pboProject says there's a problem with the .cpp, and arma fails to load build.py build of it.

All this is for pboProject 1.56 Dll 5.24

**Comment by Glowbal** [comment]
#3094

**Comment by Glowbal** [comment]
It might be an idea to be on the look out for similiar issues in other places.
