### ISSUE TITLE
Error in ZeusAddon

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#3089]
ACE3 Version: 3.4.1 STABLE

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
many, i suppose all ACE modules

**Description:**
found in rpt, no steps to reproduce....

**Where did the issue occur?**
Multiplayer, on the Dedicated Server

**RPT log file:**
```
19:29:14 Error in expression <snull _logic
};
};
default {
waituntil {isplayer (missionnamespace getvariable [>
19:29:14   Error position: <isplayer (missionnamespace getvariable [>
19:29:14   Error isplayer: Type Number, expected Object
19:29:14 File z\ace\addons\zeus\functions\fnc_bi_moduleCurator.sqf, line 118
```

**Comment by commy2** [comment]
This is code from BI. Do you have a full RPT and Mission? My first guess is a collision of a vehicle var name (BI loves these) and a global variable (number).

**Comment by shukari** [comment]
This error happen at the first 10minutes... but i dont know what i do to repo that...
Also i can send you the rpt but except this and 100kk Object not found errors is nothing in there!

**Comment by commy2** [comment]
The trick is to read between the lines :eyes:

**Comment by shukari** [comment]
Here your logs, btw somethimes there was a HC connected... and more than 1 zeus ;D
http://workupload.com/file/kCmeAa4y

**Comment by PabstMirror** [comment]
What do you have for the "Owner" in the module (if possible could you upload the mission)?

I can reproduce if I put a `0` in (weird case because `0` is a variable for some reason).

**Comment by shukari** [comment]
Owner? I habe there no owner field... only Name, Init, Discription, Zeus Eagle and so on..

**Comment by jonpas** [comment]
I believe he means "Owner" of the Zeus Game Master module.

**Comment by shukari** [comment]
Have 3 Zeus, Owners are: 
ZEUS_ONLY (indepentend player)
ZEUS_ONLY2 (indepentend player)
#adminLogged

Also 2 Arma Spectators...

**Comment by jonpas** [comment]
@PabstMirror status?

**Comment by SilentSpike** [comment]
Pretty confident this isn't an ace issue and something specific to @shukari's mission setup (it's basically guaranteed since that is vanilla code and the error would be the same without ace_zeus installed).

**Comment by commy2** [comment]
^
