### ISSUE TITLE
Arma sortBy Error on Server

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#3090]
ACE3 Version: 3.4.1 STABLE

**Mods:**
* `@CBA_A3`
* `@mcc`
* `@ace`

**Placed ACE3 Modules:**
many, i suppose all ACE modules

**Description:**
found in rpt, no steps to reproduce....
Over 20k lines spam with this... i suppose everyframe so it could be in ACE_Nametags or in the other addon MCC...

**Where did the issue occur?**
Multiplayer, on the Dedicated Server

**RPT log file:**
```
22:29:07 Error in expression <


_sortedArray set [count _sortedArray,_selectedItem];
_sortedValues set [count>
22:29:07   Error position: <_selectedItem];
_sortedValues set [count>
22:29:07   Error Undefined variable in expression: _selecteditem
22:29:07 File A3\functions_f\Arrays\fn_sortBy.sqf, line 131
```

**Comment by jokoho48** [comment]
please try to reproduce without MCC because i cant not repro with only CBA and ACE

**Comment by shukari** [comment]
In 319 logs it appears in 1 log... it was more for your information.

**Comment by jokoho48** [comment]
its a MCC issue i repro with MCC

**Comment by PabstMirror** [comment]
Only place we use `BIS_fnc_sortBy` is in `ace_nametags_fnc_doShow`.
The only place that is called is in `nametag\XEH_postInit.sqf`
in a keybind after a `if (!hasInterface) exitWith {};` statement, so I don't see any way that code could run on a dedicated server.

If you can reproduce without MCC, please make a new issue.

**Comment by shukari** [comment]
@jokoho48 do you now the cause? because then you or i can report it to shay_gman the author of mcc...

**Comment by commy2** [comment]
I'll DL MCC after my other DLs are finished and then take a look.
