### ISSUE TITLE
German stringtable error

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#3091]
ACE3 Version: 3.4.1 STABLE

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
many, i suppose all ACE modules

**Description:**
found in rpt, to steps to reproduce....

**Where did the issue occur?**
Multiplayer, on the Dedicated Server

**RPT log file:**
```
17:29:02 Unexpected stringtable format inside <Text ID="STR_ACE_Common_CheckPBO_Action_WarnPerm"><German>
```

**Comment by jokoho48** [comment]
allready fixed in master #3080
