### ISSUE TITLE
Pain not shown in the optical mode and when map is open 

### ISSUE THREAD

**Issue by ghost** [acemod/ACE3#3095]
ACE3 Version: 3.4.1
Stable 1.54

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
Advanced and Basic Medical modules

**Description:**
Pain(Colour flashing) not shown in the optical mode and when map is open.
Also inside vehicles!

**Steps to reproduce:**
Get wound and to use optic or map

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by mickeymen** [comment]
Also inside vehicles I noticed this, when I use Otokar ARMA

**Comment by Glowbal** [comment]
Will be done after #3916 and #3917

**Comment by Glowbal** [comment]
Possible solution is to close the map on hit.

This can possibly be integrated into hit reactions.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
