### ISSUE TITLE
Feature Request: Attaching Explosives

### ISSUE THREAD

**Issue by RSpeekenbrink** [acemod/ACE3#3101]
I would love to see that you can attach explosives to units/objects like how you can attach chem-lights etc. Imagine the possibilities:
- Hostage with strapped bomb
- Suicide Bomber
- Successfully Blowing up objects 
etc.

I hope to see this function ;)

**Comment by Glowbal** [comment]
Hi, thanks for your feature request. We have a dedicated issue to keep track of those. #414
