### ISSUE TITLE
Server not counting killsInfantry

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#3111]
ACE3 Version: 3.4.1

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
- http://pastebin.com/qxTzniPY

**Description:**
- Since we updated ACE3 to 3.4.0 our server have stopped counting killsInfantry, entry that is visible in logfile_console.log after mission is finished, like this:

```
class Session

{
    mission="co 38 Stinger Hunters";
    island="Kunduz";
    gameType="Coop";
    duration=10995.7;

    class Player1
    {
        name="Lt_Mic";
        killsInfantry=0;
        killsSoft=0;
        killsArmor=1;
        killsAir=0;
        killsPlayers=0;
        customScore=0;
        killsTotal=3;
        killed=0;
    };

    class Player2
    {
        name="Maras";
        killsInfantry=0;
        killsSoft=1;
        killsArmor=0;
        killsAir=0;
        killsPlayers=0;
        customScore=0;
        killsTotal=2;
        killed=0;
    };
```

As you can see above, only vehicle kills are being counted, and top players are always counted first (most kills like above).

**Steps to reproduce:**
- _Make a simple mission with few enemy AI, play it on dedicated._
- _Kill those AI, finish mission with `#missions` command_
- _Check logfile_console.log for killsInfantry entry for your player_ 

**Where did the issue occur?**
- Multiplayer, Dedicated*

**RPT log file:**
- .*

**Comment by gienkov** [comment]
Further testing, only ACE3 and CBA, test mission with 3 CSAT enemy's:
```
class Session
{
	mission="test_killsInfantry";
	island="VR";
	gameType="";
	duration=19.954;

	class Player1
	{
		name="GieNkoV";
		killsInfantry=0;
		killsSoft=0;
		killsArmor=0;
		killsAir=0;
		killsPlayers=0;
		customScore=0;
		killsTotal=0;
		killed=0;
	};
};
```

**Comment by gienkov** [comment]
Vanilla A3, kills counted:
```
class Session
{
	mission="test_killsInfantry";
	island="VR";
	gameType="";
	duration=29.126001;

	class Player1
	{
		name="GieNkoV";
		killsInfantry=3;
		killsSoft=0;
		killsArmor=0;
		killsAir=0;
		killsPlayers=0;
		customScore=0;
		killsTotal=3;
		killed=0;
	};
};
```
Thus I suspect one of changes in ACE3 3.4.0 did that. As I said this started the same day I've updated ACE3 on our end to 3.4.0. Wasn't happening before.

**Comment by Glowbal** [comment]
Probably down due to the usage of `setDamage` to kill units. 

I doubt there are many ways around this. I don't think we can add kill counts to specific players either.

**Comment by kerckasha** [comment]
it's prevent instant death causing it, I turned it off and kills started counting.

**Comment by gienkov** [comment]
Then why this option affects AI in first place...?
04.01.2016 16:23 "kerckasha" <notifications@github.com> napisał(a):

**Comment by gienkov** [comment]
W8, we are using prevent instant death since like few months, it wasn't happening until 3.4.0

**Comment by PabstMirror** [comment]
Part of this did change in 3.4.0 - https://github.com/acemod/ACE3/commit/988a5c76bbcbec7c0913aa27ea6694a26ae99330#diff-46371a0c402e2cdf1f348dd5a949689bR83
But this fixed the double killed event problems from `setDamage`.  I'm not sure how it would have made things worse for the `preventInstaDeath` setting.

**Comment by nomisum** [comment]
welp, not the killed EH again :( is there any workaround? CBA stuff maybe?

**Comment by gienkov** [comment]
Any news on this?

**Comment by Radeni** [comment]
Same

**Comment by commy2** [comment]
https://forums.bistudio.com/topic/181341-ace3-a-collaborative-merger-between-agm-cse-and-ace/?p=2974238

**Comment by Glowbal** [comment]
We can provide an ACE event but I don't think we have a suitable solution for the kill count / score from the vanilla game.

**Comment by tupolov** [comment]
also impacts ALiVE as we record kills for War Room... now kills dont get registered.

**Comment by zbshadow** [comment]
I would like to bring this back to light, ACE is being used widely for many different game modes. 
We all enjoy the mod for its many different features but the most used is the Medical. The only reason many Wasteland and other mission modes are avoiding using ACE for their modded versions is this bug. I get why the team feels it minor but even myself in the Realism side of things would love this to be fixed for our Public server Insurgency.

**Comment by jonpas** [comment]
> I get why the team feels it minor but even myself in the Realism side of things would love this to be fixed for our Public server Insurgency.

You don't see the problem then, we can't "fix it", because the only way to fix it at the moment is to get rid of half the medical stuff if not all. We have to do with what tools and API are available and we would rather have a good medical system rather than correct kill counting.

**Comment by esteldunedain** [comment]
We also provided an API for mission makers to be able to detect who last damaged a unit that died, so missions specifically programmed for ACE can implement kill counts. But there's nothing we can do with with the engine internal counter, as we don't have proper scripting commands to deal with it.

**Comment by AlManiak** [comment]
Where can I find documentation of this API? I'd like to use the last damaged function, but I have not yet been able to find it in the git.

**Comment by rockurheart** [comment]
Hello, may I suggest something for the scoreboard that doesn't work with ACE?

When I play on Jigsors BMR map, it still registers the kills, and I found out that EOS has an advanced kill counter that is compatible with ACE since vanilla is not, do you think you can cooperate with producers of EOS to make this work?

**Comment by commy2** [comment]
The vanilla kill counter is hard coded and cannot be edited by us. The mission you meantioned probably uses the lastDamageSource variable we provide.

There also is the ACEX killtracker: https://github.com/acemod/ACEX/tree/master/addons/killtracker

**Comment by strider762** [comment]
I agree with @rockurheart that EOS does something that allows kills to be registered even when using ACE.  I have spent some time looking at the EOS code but I can't see what it is that allows missions using EOS with ACE to register kills when other missions don't.

**Comment by commy2** [comment]
Probably a HandleDamage eventhandler on all playable units breaking medical.

**Comment by commy2** [comment]
Sure, but this way you also break the medical system by overwriting the damage (not just halving it, overwriting it completely).
