### ISSUE TITLE
Kills not registering properly

### ISSUE THREAD

**Issue by wesley32** [acemod/ACE3#3112]
I'm having an issue where kills aren't properly registered while using ACE. Whenever I kill an enemy through headshot it works fine (a hint pops up), but when I shoot at the body armor of an enemy and kill, it doens't.
I added a killed EH and used the following code to determine the issue:

_killed = _this select 0;
_killer = _this select 1;
killerName = getText (configFile >> "cfgVehicles" >> typeOf _killer >> "displayname"); //Get the displayname of the killer
_killed addAction ["Show killer", "hint format ['Killed by: %1',killerName]"]; //Add action to body and show displayname of killer though a hint

When I headshot, the kill registers properly with killhint. I use the 'Show Killer' action on the body. It shows my own display name. This is good.
When I kill enemy through shooting at body armor and no killhint shows up, I use the 'Show Killer' action on the body. It shows the killed soldiers' own displayname. It's like the game think it killed itself.

When I try in vanilla game, this issue doesn't appear. Only when I launch with ACE.

**Comment by gienkov** [comment]
Possibly related to my issue aswell? https://github.com/acemod/ACE3/issues/3111

**Comment by DaVidoSS** [comment]
same issue #3116

**Comment by commy2** [comment]
Closing as dup
