### ISSUE TITLE
ace_advanced_ballistics.dll not installed?

### ISSUE THREAD

**Issue by LindavK1972** [acemod/ACE3#3113]
ACE3 version 3.4.1.0 stable.

When starting Battlezone Altis ACE3 we get ace_advanced_ballistics.dll not installed.

I have put the file from the optional s dir called ace_advanced_ballistics.dll into the Arma3/dll directory without effect?

**Comment by commy2** [comment]
`C:\Program Files (x86)\Steam\SteamApps\common\Arma 3\@ace\ace_advanced_ballistics.dll`

Where do you got ACE from? What ass has put the dlls in \optionals :picard:

**Comment by LindavK1972** [comment]
That worked...thanks!!!

**Comment by Dobakjang** [comment]
No this is strange, cause this thing was never happen on yesterday and it just happen today. even ace_advanced_ballistics.pbo in ace folder but it's not working and showing that message.

**Comment by Musclebust** [comment]
So Battleye is reporting it cant update because its master servers are down or unreachable. 

Then it goes on to block a set of files from Ace3 including Ace_advanced_ballistics.dll

**Comment by PabstMirror** [comment]
You can try manually updating files here: http://www.battleye.com/downloads/

But it had no effect for me, can't contact master server, and no DLLs load.

**Comment by Musclebust** [comment]
Same here, i guess i just have to wait for Battleye to sort their servers out.

**Comment by commy2** [comment]
New tag: `Battle Eyes fault`?

But please with the words seperated. Can't stand brand names corrupting languages.

**Comment by PabstMirror** [comment]
Battleye seems to be back up, please try again now.

**Comment by topper3** [comment]
I can confirm it was BE, some thing happened here and I panic and started moving files and stuff, what a mess! :(  I guess I need to stay calm next time :) if nothing changes and you get an error message then it has to be BE :)

**Comment by mickeymen** [comment]
Сan confirm this message.
Without the Internet when I try to start any mission from the editor, a message appears-. "Extension ace_advanced_ballisics.dll not installed"
Thus, it is impossible to play in Arma3 with ACE3 but without Internet!
Once the Internet turns on,  then the problem disappears and I can play. Please fix this problem.

**Comment by bux578** [comment]
Don't start with battleeye ... problem solved

**Comment by Glowbal** [comment]
If you are without internet, simply turn off BattleEye. That should get of the issue

**Comment by mickeymen** [comment]
Thanks;
