### ISSUE TITLE
Feauture Request: AI should react to a fallen grenade near to him.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#3117]
I have repeatedly informed BIS about this issue, but as I understand it BIS is in no hurry to fix it. Probably in ACE3, this issue will be higher priority.

The AI in the Arma3 never doesn't react to the fallen grenade near to him. Even in the primitive gameplay of Call of Duty, I've seen bots trying to escape, if the grenade fell next to him. 
If enemy, which threw a grenade, was detected by the AI, then this AI should try escape from the dangerous radius around this fallen grenade or do any actions for survive (for example go to prone position). 
Or even if a enemy, which threw a grenade, is not detected by AI, but this grenade falls very close to this AI and this AI detected fallen grenade visually, then this AI should try save own life also.

Steps To Reproduce: Throw a grenade in the enemy or allied AI-soldier and you will not see any reactions

**Comment by jokoho48** [comment]
did you want to troll us? #414

**Comment by mickeymen** [comment]
"did you want to troll us?" No, i dont understand how I can do feauture request tickets

**Comment by bux578** [comment]
What @jokoho48 meant:

Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html

**Comment by mickeymen** [comment]
And what has this to Troll? My message no trolling message

**Comment by bux578** [comment]
> My message no trolling message

I agree. 

We have a [special issue for feature requests](https://github.com/acemod/ACE3/issues/414).

**Comment by mickeymen** [comment]
As I understand it is FORBIDDEN to create a new tickets!!! The user can only "Feauture Request" in the comments of this ticket - https://github.com/acemod/ACE3/issues/41 

And that's all he is allowed?

**Comment by bux578** [comment]
> And that's all he is allowed?

For Feature Requests yes. 

Bugs and errors should always get a new issue.

But you can always join our public chat: http://slackin.ace3mod.com/

**Comment by mickeymen** [comment]
Ok; Thanks for quick answers!

**Comment by vlad8011** [comment]
Nice to se you here mickeymen!

**Comment by mickeymen** [comment]
mutually!
