### ISSUE TITLE
feature request: Gas and gasmasks

### ISSUE THREAD

**Issue by Athos112** [acemod/ACE3#3123]
I am not sure if there was any gas in ACE2 so I ll ask you here. Are there any for plans introducing teargas or something like this in the near future? I am working on a fire department mod and gas would be very useful for my work.

**Comment by Glowbal** [comment]
Hi, thanks for your issue post. We have a dedicated issue on our tracker to keep track of feature requests. I am closing this in favour of that ticket.

#414

Any features we had in ACE2, AGM or CSE that are not yet implemented in ACE3 are planned. We cannot give any ETA.
