### ISSUE TITLE
ACE3 on Linux clients

### ISSUE THREAD

**Issue by zacekjakub** [acemod/ACE3#3137]
Hello,

I already tried it and the mod doesn't seem to me working on Linux client, is there any chance it should be supported now or later please? I can't live without ACE mod, but I am not going to support MS neither.

Thank you!

**Comment by Glowbal** [comment]
Isn't the linux client lacking multiple A3 versions behind? ACE3 always requires the latest A3 version.

That said - we should only have to compile our extensions with for example GCC. They should all be crossplatform already. @jaynus or @NouberNou you guys looked into this, right?

Otherwise pinging @KoffeinFlummi

**Comment by commy2** [comment]
We should probably make a "Client Linux Port General / Sticky" and collect all information there.

**Comment by zacekjakub** [comment]
Something like "Client Linux Port General / Sticky" would be great. :) Thank you in advance.

**Comment by PabstMirror** [comment]
What version is the linux client on?  As far as I know they are several version behind, so you will want to use an ace version from that era (eg: https://github.com/acemod/ACE3/releases/tag/v3.0.0 should work on ~1.44)

Other issue is the DLLs (until we can build .SO)
 - ace_advanced_ballistics.dll means AB needs to be off
 - ace_break_line.dll means you need to use "show as lists" in interaction menu settings
 - ace_clipboard.dll means clipboard output won't happen (debug should still goto rpt)
 - ace_fcs.dll means FCS needs to be off
 - ace_medical.dll should be ok as it will fallback to SQF
 - ace_parse_imagepath.dll will break the "show building actions" interaction menu setting

**Comment by TheMagnetar** [comment]
I am half way through the modification of c++ files in order to achieve this. I will make a pull request once I finish it.

**Comment by zacekjakub** [comment]
Hello, thank you. I am sure all Linux community appreciate it. I'll try the described steps asap and let you know. Is possible to disable parts like AB in any concrete config file? We can help to test anything needed and in case there would be required any action from a linux side, I can help with it.

**Comment by commy2** [comment]
delete the PBOs. E.g. ace_fcs.pbo

**Comment by zacekjakub** [comment]
So, I just deleted:
- ace_advanced_ballistics.pbo
- ace_advanced_ballistics.pbo.ace_3.0.0.3-ab580dd1.bisign
- ace_fcs.pbo
- ace_fcs.pbo.ace_3.0.0.3-ab580dd1.bisign
I didn't find any files for other mentioned components.
And I am getting now: Bad version 68 in p3d file ''\ace\addons\optics\models\nwd_m22_5x.p3d'

Any idea?

Thank you very much for help.

**Comment by commy2** [comment]
>Bad version 68 in p3d file ''\ace\addons\optics\models\nwd_m22_5x.p3d'
Thats a model error. The model in ACE does not work with the games version, probably because it was made with a binarizer that didn't exist in that Arma version.
I think you need to test with an even older ACE version.

**Comment by zacekjakub** [comment]
Thank you, going to test and let you know again. :)

**Comment by commy2** [comment]
Strange. Is the legacy version of the Linux client even older than ACE3 ?

**Comment by commy2** [comment]
If that would be the case, then you can still simply delete `ace_optics.pbo`. There is nothing vital in there.

**Comment by zacekjakub** [comment]
Awesome, it seems to be working with optics deleted, thank you so much. :)

New A3 patch for Linux ( the last one ) is going to be released in a couple of days.

**Comment by zacekjakub** [comment]
Hmm, after first mission load: 

Bad version 68, this time reticle_titan.p3d

**Comment by PabstMirror** [comment]
`Bad version 68` are from compiled p3ds that were binerized with a new version of the tools than arma.

What are the versions of arma and ace?  try 3.0.0 - https://github.com/acemod/ACE3/releases/tag/v3.0.0

**Comment by zacekjakub** [comment]
As already mentioned in the thread, I am trying it with ACE 3.0.0. and Arma 1.42.

**Comment by commy2** [comment]
>Arma 1.42. Release date: April 8, 2015
Yep. To old.

**Comment by PabstMirror** [comment]
I managed to find an old build from April 17th 2015, which should put it on 1.42.  I cannot test this, and this is ancient code with tons of bugs that have been fixed, so no guarantees this will work: but you are free to try this: http://expirebox.com/download/883c1da126fca514cf20d324a81e1b95.html

**Comment by zacekjakub** [comment]
Thank you, I will try. But it seems our best bet is to wait a couple of days for the updated release anyway. I'll bother you soon again after the release if anything won't work. :)

**Comment by esteldunedain** [comment]
> But it seems our best bet is to wait a couple of days for the updated release anyway

Sounds reasonable

**Comment by zacekjakub** [comment]
Hello, so I am back once again. :) The Linux current version is 1.54, could you tell me now what is the best ACE version for our Arma version please? I will start from scratch, try to run it and if I get it working, maybe we could together create some Linux ACE guide, if you would like to. Thanks guys.

**Comment by jonpas** [comment]
3.4.2 should work on 1.54.

**Comment by PabstMirror** [comment]
I think we still need .so files or the game will not start. (.dlls compiled for linux)

**Comment by zacekjakub** [comment]
Thx jonpas, will try.
PabstMirror: Did you even read the discussion?

**Comment by zacekjakub** [comment]
Unfortunately, after the mission is loaded: "ace_parse_imagepath not installed". And the mission ends. And the file from root of ace mod ace_parse_imagepath.dll was deleted of course.

**Comment by jonpas** [comment]
> PabstMirror: Did you even read the discussion?

Of course he did, you can see he commented before, and gave you exactly the reason why it doesn't work.

**Comment by zacekjakub** [comment]
Oh sorry. I didn't notice. The last build u posted somehow worked for me after several modifications, but unfortunately, 
1) I deleted it by mistake
2) It's not able to download the file anymore
3) It was anyway for version 1.42.

But thank you guys.

**Comment by KoffeinFlummi** [comment]
Due to armake i'm currently working on this. At this point there are 2-3 issues:

- Arma3 (Linux) is one P3D version behind, on 68, compared to 70 in the main  version
- dlls obviously don't work and I haven't had any luck compiling .sos yet.
- There might be commands used in ACE that aren't yet in the linux version.

You can use 3.4.2, which should get rid of 1 & 3, 2 remains. As I said, currently working on it, will update with progress.

**Comment by zacekjakub** [comment]
Thank you very much. And some idea just of getting rid of problematic libraries? We dont care about version, it could be really older, but arma without ace is boring. :)

**Comment by zacekjakub** [comment]
Hello, still no progress? :)

**Comment by commy2** [comment]
We won't make another ACE version that works with 1.54. They have to at least update the Linux branch to 1.58. Too many differences in the game for it to work with both versions.

**Comment by zacekjakub** [comment]
Ok, we will wait for the newer version again. I just hope you will not tell us we need to wait for newer version again. Yes, Linux A3 version is and probbaly will be older than Windows, but it's not the reason not to freeze the Linux version couple of versions behind...

**Comment by commy2** [comment]
The thing is that it's really difficult to support two so different versions of the game. We are struggling to even keep CBA compatible between both.

Stuff that works in 1.54 is broken in 1.58. Stuff that exists in 1.58 didn't in 1.54. And SQF has no smart way of figuring out what version you are on before the .sqf files are preprocessed.
Some features are made to work with the 3den editor. That doesn't even exist on Linux.

**Comment by zacekjakub** [comment]
Hello, so nothing new at all? The Linux version is not going to work? Could I ask you to help me getting just one version of the game working with one version of ACE with some functions disabled? It would be absolutely greate, we really don't care about new versions, but still, we would like to play it. Thank you.

**Comment by commy2** [comment]
BI will have to update the Linux client version.

**Comment by zacekjakub** [comment]
Hello, BI did their job: Linux version is .64 with APEX. I am getting now:
bad version 8 in p3d file 'z\ace\addons\medical\data\bandage.p3d

Could you advice please? It's no issue to deactivate anything or do as you say, but we really want this to work.

**Comment by commy2** [comment]
1.64 is not new enough. `bad version 8` is due to models being binarized with tools newer than APEX being incompatible with old Arma versions. ACE will not work on the Linux port. They have to update to the current game version, not a slightly less outdated one. Sorry.

**Comment by PabstMirror** [comment]
3.8.2 should work at it was compiled for 1.64 so the p3ds would be loadable

But we still have no work done on extensions for linux which are required for clients.

**Comment by zacekjakub** [comment]
Hello, thank you very much, I am going to try the mentioned version.

**Comment by zacekjakub** [comment]
For the version 3.8.2:
Bad version 72 in p3d file 'a3\vegetation_f_exp\clutter\grass\c_grassbunch_hi.p3d'

**Comment by zacekjakub** [comment]
Hello, so it works with a legacy version, thank you very much. Seems like most of features work without any issues, even  Apex mission in multiplayer, no issues so far. It is great, we can stay on this version. :)

**Comment by zacekjakub** [comment]
Hey, one last thing to ask. :) Only bigger issue i found is, that in an interaction menu are missing texts, so I have no idea what does any picture mean. Any idea how to resolve just this problem?

Thanks!

**Comment by GetzMikalsen** [comment]
Hey, Zacejakub.
Could you tell us what legacy version you used?
Very hopeful now to get it working myself. :)

**Comment by elpasmo** [comment]
I have the same issue as Zacejakub. Using ACE3 v3.8.2 with legacy version 1.64. All works but interaction menu texts are missing.

**Comment by zacekjakub** [comment]
Hey, I am glad I am not the only one trying to convince developers of ACE that Linux matters. :)

If you still need it, I can check my settings as I get home from work, even to send you all needed files or anything. It works pretty well, but the missing texts in interaction menu is still issue that would be nice to be resolved.

**Comment by commy2** [comment]
It's not a matter of convincing us that Linux matters. But it's just not practical for us to support two different versions of the game that are essentially half a year or more in development apart. That would mean we would have to cut back in features and optimizations of the windows build and that is just not acceptable.

**Comment by elpasmo** [comment]
Thanks @zacekjakub
No need for your settings though, we seem to be at the same page :)

@commy2 I understand the problematic involving to support two different branchs and you're right. On the other hand, maybe this issue has a nice and easy workaround... maybe it involves something more. We don't lose anything reporting it and maybe it will be even useful for the master branch. Who knows if we don't report it.

Anyway, thanks a lot for this great addon, I'm enjoying it a lot even considering the missing texts :+1:

**Comment by zacekjakub** [comment]
@commy2 Hi, nobody wrote we need every published version, we know about the problems releasing Linux version, but it's something different to release a new version every half a year for Linux and maybe to change one library you are currently using for showing texts in interaction menu, and something different to ignore it totally. We are currently glad we got something we can play with and the only issue that matters is the interaction menu. If you fix it for the only one working version at this moment, we can keep the same legacy until you decide it's time to release another one after a year maybe... Does it make sense?

Thank you.

**Comment by GetzMikalsen** [comment]
Someone from the community could probably maintain a Linux build/fork of the project, shouldn't be too much work as the Linux version of Arma  3 is rarely if ever updated so dependencies breaking shouldn't be an issue.
Are you up for it?

Also, the current working version for Arma 3 on linux appears to be v3.8.2, if there are any issues then delete the pbo's noted in this thread.

**Comment by jonpas** [comment]
If you are going to do that, then just use whatever ACE3 Version works with that Arma version. If you want latest ACE3 on Linux version of Arma than it's not just that, but actual rewriting of components due to missing commands.

**Comment by zacekjakub** [comment]
In case developers could add an information about which A3 version is gonna work with which version of ACE3 somewhere, I can just create a shell script to take care of updating the ACE3 before A3 is started and if it's needed, to handle some configuration changes. It would be better than nothing and it would work for Linux newbies as well.

**Comment by GetzMikalsen** [comment]
Just compare the release dates on the Ace3 release page and the Arma 3 build tracker, this has been explained previously in the thread. Also the A3 port is updated so rarely that it won't be a whole lot of work just finding and downloading the latest version of ace which is compiled for the version of A3 which the port is. 
Currently it is v.3.8.2.

**Comment by zacekjakub** [comment]
@GetzMikalsen : I am talking here about doing it automatically so unexperienced users can do it themselves and you proposed me to use https://dev.arma3.com/ to parse it and find new versions for Linux? Are you sure you know what are you talking about? I am sorry if there is some other and parsable list of releases, but I didn't find it.

**Comment by GetzMikalsen** [comment]
@zacekjakub either that or the announcement thread on their forum here https://forums.bistudio.com/topic/188937-experimental-ports-release-announcements/
Otherwise the linux depot on steamdb could be of use, but I think it's just a waste of time as the port is so rarely updated, I would suggest just doing it manually, as the arma community has done for so many years before launchers. But I wish you the best of luck if you try to pursue your project of parsing the dates etc.

**Comment by esteldunedain** [comment]
@elpasmo, please take a look to the first few posts in this thread. There's a quick fix for the missing text on the interaction menu: select "Display interaction menus as lists" on the settings menu.

**Comment by zacekjakub** [comment]
@GetzMikalsen : That's it. Pages you sent me are not parsable at all. So if developers could automatically add info about in which version of A3 was ACE compiled, it could be totally automated on the client side.
@esteldunedain : Thank you very much, I totally forgot it was mentioned already, I will try it this evening and hopefully it helps us.

**Comment by elpasmo** [comment]
@esteldunedain Great! I've missed that and it works perfect. Thanks a lot!

**Comment by esteldunedain** [comment]
I'm glad I could help. After all it is my fault that an extension is required for the default IM.

**Comment by bux** [comment]
@zacekjakub
That is the closest we have to an ACE3 A3 version conntection:
https://github.com/acemod/ACE3/blob/master/addons/main/script_mod.hpp#L12

**Comment by zacekjakub** [comment]
Thank you @bux, I guess it will work for me.

**Comment by zacekjakub** [comment]
Hey once more, sorry to bother you again, but we are not able to find the mentioned menu "Display interaction menus as lists". There is no option like this in the ACE configuration menu. Where is it supposed to be please?

Thank you very much.

**Comment by dedmen** [comment]
#5762
ACE requiring the newest Arma version isn't an issue IMO. Just use a older ACE version. Just like you use an older Arma version and older versions of all other mods that require the latest version.
Also as Linux builds are getting closer to version parity this is getting less of a problem.

With #5762 we will have Linux compatability as much as we can possibly do.

**Comment by TYKUHN2** [comment]
Update: Linux is 1 hotpatch behind Windows as of today, however, it appears that is in the works.

**Comment by fbt** [comment]
Hi! Rn the linux version is behind A3, but not ACE3's required version. But trying to launch it, I get an error loading ace_clipboard_x64.dll, аnd it won't just tell me which addon needs it...

So the question is: which addon(s) does use this dll, and is it possible to just remove them to play ACE3?

**Comment by dedmen** [comment]
@fbt this is exactly what this issue is about. It's not Linux compatible yet. Else this issue would be closed.

**Comment by fbt** [comment]
Oh. Sorry, I misunderstood the state Linux support is in.

**Comment by dedmen** [comment]
@fbt Just found out what your problem is. There is a bug in the current port version that causes ACE to not detect that you are running on Linux. That's why it doesn't work. 
Not a ACE bug, a Arma bug.

**Comment by dedmen** [comment]
@commy2 it is. But why think of a alternative check to workaround a bug in a already horrendously bugged linux build?

**Comment by fbt** [comment]
@dedmen yeah, after hitting the issue a few days ago, I've complained about it to a friend, who remembered running ace3 on linux before, and he figured out what's the actual problem.

I've reported the issue to Bohemia Interactive and VP, should be fixed sometime in the future.

**Comment by dedmen** [comment]
Above issue was fixed with yesterdays linux patch.

**Comment by jonpas** [comment]
Closing as Linux ports are no longer supported by BI.

Useful alternative is Proton now, where our extensions work.

**Comment by addeps3** [comment]
Anyone happen to know the latest working version of ACE3 for 1.82 ports? Current 3.12 is not working so well as I would like.

**Comment by jonpas** [comment]
@addeps3 3.12.2 is the last one that doesn't require higher than 1.82, so that should work.

**Comment by addeps3** [comment]
> @addeps3 3.12.2 is the last one that doesn't require higher than 1.82, so that one should work.

It has missing text/ self interaction menu missing, unavailable. It does display menu "wheel" but not the centered options aligned in rows.
