### ISSUE TITLE
SAVE GAME TROUBLE!!!!

### ISSUE THREAD

**Issue by cashsky** [acemod/ACE3#3139]
Your mod is cost nothing , while save game is breaking the mission . You have a couple feedbacks about this trouble , but doing nothing with it . And besides this trouble is not a new . MORE INFO ABOUT TROUBLE : When mission has been saved and while game is not stopped , resuming  game is working fine . But if game was re - entered , resuming is breaking mission ; the host is not able use ACE menu , the cars is not drivable , and ACE settings in main menu is disappear at all. This trouble applied only for host .

**Comment by commy2** [comment]
>You have a couple feedbacks about this trouble
If you know that there are already older issues opened for this, then why did you open another one?
Nothing is stopping you from adding information about it there.

**Comment by PabstMirror** [comment]
I tested save/load in sp and mp and they seemed to be working.
Only issue is that it took ~5 seconds befor the key binds did anything, but that seems to be CBA's fault.

What are the problems with saved games? Do you have any reproduction steps that could help?

**Comment by cashsky** [comment]
If i could do an addons , then i don't use this mod. I am just a simple Arma gamer as most of us , who want play in perfect game with quality addons , so this addon should be compatible with the game in any aspects . First of all this addon is oriented on Arma gamers . That's why my feedback as same as yours , is important help for ACE Development team . And only one explanation why i created new ticket for this issue , because previous tickets was not consist enough information . MORE INFO ABOUT ISSUE : I am using ALIVE , CBA and ACE mods in my mission . Server is created via LAN . MAY BE THIS INFORMATION WILL BE USEFUL.

**Comment by vlad8011** [comment]
This issue is already reported on Arma 3 feedback with all repro steps and mission :
http://feedback.arma3.com/view.php?id=27127

**Comment by vlad8011** [comment]
Please someone from CUP developers to comment this ticket :
http://feedback.arma3.com/view.php?id=27127
And give some directions for BIS - for now they think its only your fault.
