### ISSUE TITLE
Patch (correct it) for RHS mod (FCS)

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#3141]
quote

Ach you've got ace_advanced_ballistisc and ace_wind_defflection enabled. This is the fault - you need to ask ACE guys to create compatibility patch (correct it) for RHS mod. For now it exclude FCS settings for RHS tanks (ace_fcs) but not from files mentioned before - thats why missle trajectory is not calculated by ballistic computer.

My theme RHS
http://feedback.rhsmods.org/view.php?id=1730

**Comment by dixon13** [comment]
I'm not sure what you are wanting? Can you describe more? I checked out the RHS ticket and it's all in Russian so I can't read it. Tried using google translator but of course it didn't work too well.

**Comment by PabstMirror** [comment]
Is this for all RHS vehicles or only specific ones?

Is the problem with ACE's FCS? or With ACE's wind deflection?

**Comment by MAD-BUG** [comment]
There said that ACE FCS interfere at RHS FCS and projectiles on long distancies does not hit right at where turret aiming. My opinion(that i already described there) that it is normal on big distances or at least it is problem of RHS FCS that can't calculate right projectile trajectory, because of ace_advanced_ballistisc and ace_wind_defflection.

**Comment by jokoho48** [comment]
wind Deflection or AB dont effect Tank Bulltes if i remeber right and i think we disable ACE FCS for every RHS vehicle

**Comment by vlad8011** [comment]
There is a problems with RHS weapons - if you leaning left or right behind the corner - rounds from rifle is going to the left or right from sight's crosshair. Same with FCS on tanks - specially noticed on alrger distances. Missle guidance seems to be affected too - AA missle "is dancing" around the flare, and missle from javelin is stucking for while in the fire when wreck is aquired. (thats from RHS bugtracker). 
From what i've seen there is no Top-atack mode in javelin in camera mode (esc, in pause menu) - you shoot missle in T-D (top-down) mode and it flies in direct mode. More - missle is starting before launcher in almost 90 degree.

**Comment by MAD-BUG** [comment]
How you exclude shells from array that needed to be calculated?

**Comment by Kartaviy** [comment]
I want to say to all either completely changes the FSS in RHS and made his calculations accurate, or finish it. M2A3 does not advance to the wind. Shells do not reach the point. It's all a problem FCS ACE or FCS RHS?I seek solutions to a problem with the tanks have 3 versions of a row, but they can not do anything with it.

**Comment by commy2** [comment]
>I want to say to all either completely changes the FSS in RHS and made his calculations accurate, or finish it.

We can't change the FCS from RHS.

These questions have to be answered or there is nothing we can do:
>Is this for all RHS vehicles or only specific ones?
>Is the problem with ACE's FCS? or With ACE's wind deflection?

I don't see how this can be caused by ACE Wind. The wind is never calculated in the ACE FCS (because wind does either not affect tank rounds at all or the effect is minimal)
It also can't be ACE Ballistics, because that only does stuff for rifles and not vehicles.

**Comment by PabstMirror** [comment]
For now you can just turn off wind deflection just for vehicles in the wind deflection module. (`ace_windDeflection_vehicleEnabled`)

**Comment by vlad8011** [comment]
Well i think its ACE 3 bug.
Test it with BMP-3.
I got disabled all ACE modules sticking to FCS.
Resoult was clear - if you shoot from BMP-3 100mm cannon with HE round at range above 600 M - ROUND WILL ALLWAYS HIT ABOVE TARGET, without ace its not hapening, same with all tanks (HE, HEAT rounds) at ranges > 1000m

Without ACE it work fine.

**Comment by commy2** [comment]
we are not responsible for compatibility with any mod

**Comment by vlad8011** [comment]
Now i know after lot of tests its not ACE 3 fault. Tested without any other addon (except RHS) and there is still problems with targets > 1500M, BUT with ACE those problems start a lot earlier. I dont know what is the fault, but i'm a little confused now.
