### ISSUE TITLE
Intercept

### ISSUE THREAD

**Issue by jameslkingsley** [acemod/ACE3#3145]
Is there a plan for ACE to be re-written with [Intercept](https://github.com/NouberNou/intercept) once Intercept's finished? Would ACE benefit from it or is it not necessary?

**Comment by Glowbal** [comment]
There are no official plans to do so at the moment. Once Intercept is closer to a complete coverage, we might consider using it.

I can definely see some benefits for ACE, but there is also a cost - C++ is a lot more complex to use compared to SQF. And not all our devs are experienced with C++.

**Comment by PabstMirror** [comment]
Just like our work on cleanups and rewrites, the key is to look for functions that are called often and have the biggest effect on performance.

Lets say ~10% of our code is responsable for 90% of the run time.

For example with Medical, we might want to convert handleDamage as it can be called many times for each hit and is fairly complex bit of SQF.  (Server could get several thousands of calls in a mission).  But something like apply bandage is rare (player might do it 3-4 times a mission)

**Comment by jameslkingsley** [comment]
> apply bandage is rare (player might do it 3-4 times a mission)

You haven't seen my missions...

But what you're saying about only doing the conversion for performance hungry tasks seems ideal. No point saving a tiny bit of performance if the majority lose out.

**Comment by esteldunedain** [comment]
This will be discussed further internally soon.
