### ISSUE TITLE
ToolKit is not removed after use

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#3153]
ACE3 Version: 3.4.2
Stable 1.54

Mods:

@CBA_A3
@ace
@ RHS
Placed ACE3 Modules:
ToolKit Modules

Description:
ToolKit It not disappears after use. Pls fix this. You promised to fix it in 3.4.2.
I set up in modules so that he disappeared after use. But he does not disappear.
https://www.youtube.com/watch?v=A95bPeYUGTA&feature=youtu.be

Where did the issue occur?
Editor/multiplayer

RPT log file:
http://rghost.ru/64pthllGT

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by Kartaviy** [comment]
up

**Comment by PabstMirror** [comment]
The video it is clear it isn't working for you, but oddly I can't reproduce at all; and I see nothing wrong in the rpt.

I've made a test mission here: https://gist.github.com/PabstMirror/567d54f33add636dbb65

This should throw up a hint with both the current setting and the number of tool kits on the player.  If you could try this mission and verify the setting number, and what happens to the "Toolkits: x" number as you pick one up, what happens as you start repairing.

Or you can just add the debug code to any existing mission:
```
    [{
        hintSilent format ["(ace_repair_consumeItem_ToolKit) = %1\nTime %2\nToolkits: %3", ace_repair_consumeItem_ToolKit, time, ({_x == "ToolKit"} count (items player))];
    }, 0.5, []] call CBA_fnc_addPerFrameHandler;
```
I cannot reproduce your full modset, if possible could you try with just CBA and ACE.

**Comment by jokoho48** [comment]
@PabstMirror it is posible that the russian transtions is flipped?

**Comment by PabstMirror** [comment]
I was so stumped I tried setting language to russian to try to match video.
`Да` is the correct setting

**Comment by jokoho48** [comment]
ok :D just a idea

**Comment by Kartaviy** [comment]
It is ok. It was my problems. closed Theme
