### ISSUE TITLE
FFV backblast seems too much

### ISSUE THREAD

**Issue by Sniperhid** [acemod/ACE3#3156]
ACE3 Version: 3.4.2
Arma 3 Version: 1.54

**Mods:**
* `@CBA_A3`
* `@ace` 

**Placed ACE3 Modules:**
None

**Description:**
Backblast seems too much when firing a launcher FFV turned out position. Particularly in the offroad.

Video: https://www.youtube.com/watch?v=1IJt2bTD5xo&feature=youtu.be

From a realism point of view I spoke to a military buddy of mine and whilst he advices against firing from a vehicle he said it is unlikely in the video below that the firer would be wounded from the backblast. He also mentioned that if the launcher has fins (i.e. AT4) they might expand and collide with the cabin though that is a different issue.

**Steps to reproduce:**
Get an RPG-42 and get into the back seat of an offroad, turnout, select the RPG and fire.

**Comment by PabstMirror** [comment]
`lineIntersectsSurfaces` takes an  "ignoreObj" param, but seems to still returning this in the array when that object is mounted in a vehicle (probably some proxy object thing)

So the shot was hitting the player making distance was ~0 and causing max damage.  Can just manually filter out `_shooter`.

**Comment by esteldunedain** [comment]
I suspected something like this was going on.

**Comment by commy2** [comment]
Thats a bug with LIS then.
