### ISSUE TITLE
Replacing FCS RHS at FCS ACE3

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#3157]
You can completely change the RHS to its own FCS ACE. Because the FCS RHS does not work well. You do it just fine! It is necessary to completely replace anywhere on your system.

**Comment by bux578** [comment]
?

**Comment by Kartaviy** [comment]
Make a patch for RHS.Where all the armored vehicles will work on your FCS ACE3.

**Comment by SzwedzikPL** [comment]
@Kartaviy this is not that simple. RHS FCS and ACE3 FCS are not compatible and adding `ace_fcs_Enabled = 0;` will not work as you think.

I've made something like this -> https://www.youtube.com/watch?v=Zm0VHJLnutw but it will be separate mod, not part of ACE.

**Comment by commy2** [comment]
^ What is that? Your own FCS or does it use the fcs.dll from ACE?

**Comment by SzwedzikPL** [comment]
Pure ACE3 FCS (dll and sqf). I've disabled RHS FCS and made RHS (for now only US) tanks compatible with ACE3 FCS.

**Comment by commy2** [comment]
And I guess it works better? I've never looked at how the RHS FCS works, but I don't have good experiences using it.

**Comment by SzwedzikPL** [comment]
My community is testing it for quite some time and it works perfectly :)

**Comment by commy2** [comment]
:+1:

**Comment by esteldunedain** [comment]
> but it will be separate mod, not part of ACE.

Care commiting that as an ACE optional pbo?

**Comment by SzwedzikPL** [comment]
> Care commiting that as an ACE optional pbo?

Sounds great if possible :) I didn't know that kind of stuff fits ACE optionals.

**Comment by esteldunedain** [comment]
> I didn't know that kind of stuff fits ACE optionals.

I think it does. There's already pbos for RHS compat, replacing some of their systems with ours. The catch with the approach is that it requires updating every time RHS releases a new version.

**Comment by SzwedzikPL** [comment]
> The catch with the approach is that it requires updating every time RHS releases a new version.

No problem. Im doing it anyway :)

**Comment by Kartaviy** [comment]
"I've made something like this -> https://www.youtube.com/watch?v=Zm0VHJLnutw but it will be separate mod, not part of ACE."

Can you give me link pls.

**Comment by SzwedzikPL** [comment]
> Can you give me link pls at the addon.

Its not public yet.

**Comment by jonpas** [comment]
If anyone is willing to do it, then it will be done. ACE Team is not responsible for 3rd party compatibility (doesn't mean someone won't do it though).
