### ISSUE TITLE
 ace_noradio no longer works since version 3.4.2

### ISSUE THREAD

**Issue by agorapolis** [acemod/ACE3#3158]
Hello,

ace_noradio no longer works since version 3.4.2
No error message related to ACE in the RPT.

Thanks for our help

**Comment by SzwedzikPL** [comment]
I can confirm that aswell.

**Comment by commy2** [comment]
Can not reproduce
![http://i.imgur.com/HLUYQuM.jpg](http://i.imgur.com/HLUYQuM.jpg)

Can I please see the RPT file for myself?

**Comment by agorapolis** [comment]
Sorry
It is a mistake to me :flushed:, mishandling with CBA.

Problem fixed.

**Comment by commy2** [comment]
@SzwedzikPL ?

**Comment by SzwedzikPL** [comment]
Sorry, my community member misunderstood how this module works and he told me this didn't worked on our last mission. False feedback, sorry again. He thought it works for playable units aswell.

**Comment by commy2** [comment]
![https://i.imgur.com/7nPIzZg.jpg](https://i.imgur.com/7nPIzZg.jpg)
