### ISSUE TITLE
Zeus unit interaction menu disappeared after 3.4.2

### ISSUE THREAD

**Issue by KurtXiang** [acemod/ACE3#3159]
WIN key does not bring up unit interaction options (stance, formation, remote control, etc) anymore while selecting an AI unit in Zeus mode.

**Comment by PabstMirror** [comment]
From #3084

https://github.com/CBATeam/CBA_A3/pull/206 was merged into cba, but has not been released.

**Comment by commy2** [comment]
So, this will solve itself once a new CBA is released?

**Comment by SilentSpike** [comment]
Correct :+1:
