### ISSUE TITLE
Make sure setPosASL has local only effect on CfgAmmo

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#316]
AB code relies on that.

**Comment by ulteq** [comment]
https://ace3mod.slack.com/archives/testing/p1428856908000634

**Comment by jaynus** [comment]
I confirmed this running a network packet test. There was a negligible packet increase when firing a mag full auto and a PFH setting the position on all rounds. This seems to be local setting and is not network propagated.

**Comment by esteldunedain** [comment]
Excellent!
