### ISSUE TITLE
Binoculars and Optics w/ range measuring functions DO NOT WORK anymore

### ISSUE THREAD

**Issue by andyyoung79** [acemod/ACE3#3160]
Binoculars and Optics w/ range measuring functions DO NOT WORK anymore that reads distance and range with 'TAB' key/

I'm guessing it stopped working since the last update(3.4.2.0) since I noticed it just today and I play nearly everyday.

Rangefinders and optics such as Nightstalker and TWS that has distance measuring functions.

I loaded the game from the launcher(STEAM) wo/ACE3 and it works just fine, but when I do load it w/ACE3, doesn't work anymore.

ADDED:
Rangefinders that doesn't work are only the ones with 'TAB' key distance measuring ones wo/laser.
The ones w/LASER measuring w/ 'left mouse button' works fine.

IT IS ONLY THE 'TAB' KEY DISTANCE MEASURING FUNCTION NOT WORKING.

Conclusion:
Whatever Optic or Binocular that measures distance w/ 'TAB' key doesn't function at all.
It is extremely stressful when you're trying to take out multiple enemies on the move, trying to measure distance changing to Vector(which seems to work fine when measuring distance since it measures it with 'R' key(and in this case, the 'TAB' key which measures elevation of the target also seems to work fine).

P.S. ALL KEY BINDING FOR BOTH ARMA3 AND ACE ARE AT ITS DEFAULT AND HAVEN'T MESSED IT WITH ANYTHING ELSE.

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/blob/master/addons/fcs/functions/fnc_keyDown.sqf#L19

Missing `FUNC`
rangefinders work with it added, but it had possibly unindended effects on vehicle FCS (the range display updates on both key down and up)

**Comment by mwpowellhtx** [comment]
So, version 1.7 (including Jets DLC) seems to have broken range finding of any sort. Whether binos, scopes, etc. NOT WORKING. What happened? Is it a new "mode", "key binding" or what have you? Doesn't seem to work passively. Thanks!

**Comment by PabstMirror** [comment]
Rangefinder, scopes are all now using the vanilla FCS system introduced in 1.70.
Check vanilla keybind  Weapons -> Laze Target (default is T)

**Comment by mwpowellhtx** [comment]
@jonpas Thanks! Yes, somehow now they are no longer "passive" but "active". So, in other words, content I paid for has been REMOVED?!

**Comment by jonpas** [comment]
It's been changed, not removed.

And we are not Bohemia Interactive, take those comments somewhere else please.
