### ISSUE TITLE
AI not able do any threatment and deploying/activation explosives.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#3161]
ACE3 Version: 3.4.2
Stable 1.54

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
Basic and Advanced Medical

**Description:**
AI in ACE3 not able do any threatment and deploying/activation explosives which he carry in their backpacks. Why this big issue continues to be ignored? 
If the player plays with the AI, then this breaks the gameplay, 
Or ACE3 mod only for human multiplayer? If this mod only for Multiplayer please inform about this/

Detailed Problems:

1) In ACE3 the subordinate AI-squad of player, not reports about his injury and  as a result, the player can only watch as his subordinates periodically fall dead, because during fight losing a lot of blood. How can the player know that his subordinates wounded? Or how the player has to treat them if all AI-medics are impotent?
AI does not report about injuries and there is no way to understand wounded bot or not. The player can only occasionally see, when the blood stained the uniform of the bot. But during combat or at night it is impossible to see this.

Even if the player finds a wounded soldier in his squad, then he needs to treat injured only own hands, because the medic in the ACE3 turns in useless unit.

2) In ACE3 the any AI medic not able heal another soldier, even not able heal even yourself!
Very stupid is the situation when the medic is not able to help themselves. If medic is impotent, then at least, every soldiers(not medic) should be able to help themselves. In ACE3, there is no any opportunities of AI threatment and the player can only see, as his subordinates again and again suddenly die from blood loss.Does this look like a realistic mod? I think - no.

3) All these heavy backpacks filled with explosives that make no sense. AI units only get tired faster if you carry them on his back. The player cannot use them via the order. All explosive specialists - and medics - only dolls.

ACE team, please give high priority to these issues.

**Steps to reproduce:**
Play in ACE3

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed.

**Comment by bux578** [comment]
ref #2506, #2786

**Comment by esteldunedain** [comment]
Bottomline: ACE focus is on multiplayer, which is what the mayority of its player base plays; hence anything related to friendly AI is very low priority. Furthermore, scripting the AI in SQF tend to be very difficult and demanding perfomance wise.

**Comment by mickeymen** [comment]
"Feauture request" --> means what user should to expect unknown what.  Again sad to me/

**Comment by commy2** [comment]
Feel free to make it yourself and submit a Pull Request. ACE is open source, it can only continue to exist when people work on it.

**Comment by mickeymen** [comment]
I don't know how to do it(

**Comment by commy2** [comment]
>I don't know how to do it

I didn't either, but I learned it.

>You broke these abilities from the vanilla game

I didn't break anything. You can always disable `ace_medical.pbo` and `ace_explosives.pbo` and then you have the behaviour of vanilla back, including AI. (And without losing any other features from ACE)

**Comment by esteldunedain** [comment]
> You broke these abilities from the vanilla game, so you have to fix them

Or you can ditch ACE altogether, nobody's forcing you to use our broken sht.

**Comment by commy2** [comment]
You'll even get a refund! 
:^)

**Comment by esteldunedain** [comment]
:smiley:

**Comment by mickeymen** [comment]
Guys, Instead of correcting mistakes, laughed at me) Keep it up, Good! ; ACE Feedback works perfectly

**Comment by esteldunedain** [comment]
Don't take it wrong @mickeymen. I would love to have this support on ACE too, but it's really complex to do and honestly I don't see it happening anytime soon.

**Comment by mickeymen** [comment]
Why is it so hard? can you explain?

**Comment by DrinktheBleach** [comment]
Its pretty hard I've been trying to figure out how to some of the stuff modders and scripters do with this game and honestly its impressive. The most I've been able to do is edit configs. I barely understand scripting its pretty hard for me to grasp. Personally if you still like some of the features and want a SP friendly experience use AGM I still prefer it over ACE. Mainly for the AI usable basic medical.

**Comment by mickeymen** [comment]
The problem is buried. 
Status cannot be resolved (is not understandable for me, because at BIS this all works)

PS: the most unpleasant problem for me, in the АСЕ3, otherwise the mod works perfectly...
