### ISSUE TITLE
Cannot repair anything except tracks (RHS)

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#3165]
On T-90A from rhs i cannot repair any part as tank commander. Prewiously i was able to repair ERA, and commander turret (cupola). Now im not.

**Comment by PabstMirror** [comment]
Repair has a setting called [Allow Repair/Разрешить ремонт] (`ace_repair_engineerSetting_Repair`) that defaults to 1 or "Engineer Only".

Before 3.4.2 this wasn't respected, so I think someone like a crewman could repair.
ref https://github.com/acemod/ACE3/pull/2995/files#diff-d7b4bf8f385a00d891afde474617e3ebL33

Try changing that setting in the module and see if it can work for you.

**Comment by vlad8011** [comment]
It helped. Is there any chance to get default setting same as in 3.4.1 (0)?  For now crewmans cannot repair almost anything without this module.....

**Comment by PabstMirror** [comment]
http://ace3mod.com/wiki/framework/settings-framework.html#3-2-loading-up-the-server-config

Best bet is going to be to use ace's `ace_server.pbo` from optionals, and put this in the userconfig/serverconfig.hpp:

```
class ace_repair_engineerSetting_Repair {
    value = 0;
    typeName = "SCALAR";
};
```

**Comment by vlad8011** [comment]
Thanks man :)

**Comment by PabstMirror** [comment]
yes, should work everywhere.  Clients do not need in MP, just the server

**Comment by vlad8011** [comment]
Sorry i write today, but havent tested this so far. This is not working. It still want me to be enginer to repair mentioned parts.

**Comment by vlad8011** [comment]
Is there any way to get repair functionality as in 3.4.1 (no need to be enginer to repair small parts like ERA, commander turret, cannon, engine) ? There is sometimes no way to put module in the mission, serverconfig variant is not working in singleplayer
