### ISSUE TITLE
ACE3 Medical: Ability to heal all bleeding wounds with one bandage

### ISSUE THREAD

**Issue by igorkiss** [acemod/ACE3#3170]
Hello! 
As far as i can remember, AGM has good feature in it's medical module - you can heal all your wounds with *one* bandage if you turned on this feature in AGM Medicine module. . 
I think it will be nice to have same feature in ACE3 too.

Is this possible?

**Comment by dixon13** [comment]
Very simple-basic medical menu, options would be...
 - Bandage
 - Morphine
 - Epinephrine
 - Apply CAT
like the old ACE2 menu but with the new ACE3 menu

**Comment by dixon13** [comment]
I guess it could be possible not sure. Might be awkward now with the new Arma 3 damage system.

**Comment by jameslkingsley** [comment]
I'm a +1 for this. It would be nice to have it as a server option or something so those that want to use the medical system but don't want the full version of it can choose the "minimal" version.

**Comment by bux578** [comment]
Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
