### ISSUE TITLE
PSO-1 from RHS with compat_rhs_afrf3

### ISSUE THREAD

**Issue by ZikiCZ** [acemod/ACE3#3171]
Vertical axis zeroing does not seem to work for the PSO-1 sight.

Try change this:

class rhs_acc_sniper_base;
    class rhs_acc_pso1m2: rhs_acc_sniper_base {
        ACE_ScopeAdjust_Vertical[] = { 0, 0 };
        ACE_ScopeAdjust_Horizontal[] = { -10, 10 };
        ACE_ScopeAdjust_VerticalIncrement = 0.0;
        ACE_ScopeAdjust_HorizontalIncrement = 0.5;
    };

 on this: (like a HLC_AK)

class rhs_acc_sniper_base;
    class rhs_acc_pso1m2: rhs_acc_sniper_base {
        ACE_ScopeAdjust_Vertical[] = { 0, 0 };
        ACE_ScopeAdjust_Horizontal[] = { -10, 10 };
        ACE_ScopeAdjust_HorizontalIncrement = 0.5;
    };

**Comment by VKing6** [comment]
AFAIK the PSO-1 doesn't have a vertical adjustment beyond zeroing.

**Comment by esteldunedain** [comment]
> AFAIK the PSO-1 doesn't have a vertical adjustment beyond zeroing.

Exactly.

**Comment by bux578** [comment]
Though, thank you for your report!

**Comment by ZikiCZ** [comment]
Rlly? Im not sure. It was in ACE2 and now in HLC's PSO-1 from hlc_ak_pack (with ACE3). 
Look here:
(Part: 5.1 Elevation turret)
http://www.ar15.com/content/webPDF/pos1.pdf

Part: Bullet Drop Compensation elevation turret
https://en.wikipedia.org/wiki/PSO-1

https://docs.google.com/document/d/1mdaHQDCFsuiw5Vq9OWucfkvyuLN6lzX-fvINqZEhTKw/edit?pref=2&pli=1#heading=h.prgm47spffui

(We talking about PSO-1M2. And pls add PSO-1M2-1 to the compat_rhs_afrf3.)

**Comment by VKing6** [comment]
I'm convinced.

**Comment by VKing6** [comment]
Okay, after investigating, the compat pbo takes this into account. The vanilla 100-1000m adjusting is still enabled. There's no satisfying way at this time to implement the PSO-style adjustment fully using the ACE scope adjust system.

For the time being, this will probably not change, but you are correct that the M2-1 is missing windage adjustment.

**Comment by esteldunedain** [comment]
> Okay, after investigating, the compat pbo takes this into account. The vanilla 100-1000m adjusting is still enabled, as there's no satisfactory way at this time to implement the PSO-style adjustment fully using the ACE scope adjust system.

That's exactly how @ulteq implemented it. You're supposed to use vanilla range adjustment for the vertical axis, and ACE system for windage.

**Comment by VKing6** [comment]
We should add a check to the scope adjustment so it doesn't do anything for the elevation adjustment if it's not enabled. Right now it'll click but not change from 0, which I believe is what caused the confusion.

**Comment by esteldunedain** [comment]
> Right now it'll click but not change from 0, which I believe is what caused the confusion.

Ups, that's certainly not good. Agreed.

**Comment by ZikiCZ** [comment]
but.... look:
page 5,  Figure 2
http://kalinkaoptics.com/manual/pso1m2_1_txt_edit_final1_letter_opt.pdf
"Elevation 
PSO-1M2-1 comes with elevation turrets of two different types:
VSS/ASS(Figure 3) and SVD(Figure 4). The only difference between the two is the scale engraved on the turretdial. The scale is given in meters of distance, where each number corresponds to 1/100th fraction of the distance, i.e.1 = 100m, 2 = 200m, 3 = 300m, etc."

Figure 15:
"Use adjustment turrets to move the mark to the point of impacts"
Wind ok. But range? now cant (with rhs_compat) (without rhs_compat cant use windage adjust).

PSO-1M2-1 have only one wedge:
http://img.auctiva.com/imgdata/6/7/4/6/2/9/webimg/576022422_o.jpg

**Comment by VKing6** [comment]
What are you talking about?
The PSOs have range adjustment through the vanilla arma system. And off course you can't use windage adjust without the compatibility pbo.

**Comment by ZikiCZ** [comment]
I have compatibility pbo (in @ace/addons of course). But with compat_rhs_afrf3 I can not move with a vertical elevation. Vannila control of the vertical axis is locked on 300 meters.

**Comment by VKing6** [comment]
Currently a bug where the adjustment won't work if you have the same key bound to ACE and Vanilla range adjustment: #3238

**Comment by ZikiCZ** [comment]
Great, thank you very much.

**Comment by GalNa** [comment]
Alt + Page Up or Alt + Page Dn 	
It enter vanilla switching.

**Comment by GalNa** [comment]
@ZikiCZ  `PSO-1M2-1 have only one wedge:
http://img.auctiva.com/imgdata/6/7/4/6/2/9/webimg/576022422_o.jpg`

http://guns.allzip.org/topic/100/820647.html
5th picture in the reference below In that means that the adjustment step of PSO-1M2-1 is 25 meters.
