### ISSUE TITLE
improve term engineer and repair specialist

### ISSUE THREAD

**Issue by Glowbal** [acemod/ACE3#3186]
> "Repair Specialists" corresponds to the assign Engineer setting, not the in-game unit called "Repair Specialists", which is confusing.

**Comment by alganthe** [comment]
Where exactly?

**Comment by commy2** [comment]
These things should probably be handled by `setUnitTrait`, but then there are bwc issues again...

**Comment by TigerDK** [comment]
As a mission maker (read: Zeus) I would love an option to assign a player as Repair specialist. Kinda missing it atm

**Comment by Glowbal** [comment]
This should be changed in string table entries and in the documentation. 

We shouldn't replace the variable names to avoid breaking missions.

We are accepting contributions / PRs for this.

**Comment by Phyma** [comment]
@PabstMirror  "Repair Specialist" to be "Advanced Engineer", does that seem to be reasonable?
and are you working on this?

**Comment by PabstMirror** [comment]
Added PR for repair wiki using old term: https://github.com/acemod/ACE3/pull/5247

I think None, Engineer, Advanced Engineer would work if it fits in 3den attribute.

I was worried about removing old translations, and making new strings to translate.
But I think we could make this a lot easier and leave the old translations in place and just tell our translators to make the changes to existing translations.
