### ISSUE TITLE
Explosives Timer

### ISSUE THREAD

**Issue by kieran-s** [acemod/ACE3#319]
The explosives timer starts from when you first place the explosive, so if you set the timer for say 5 seconds, it blows up before you finish the animation.

Not really a major issue, but still. Would be nice if it was possible to start the timer from at or near the -end- of the animation.

**Comment by CorruptedHeart** [comment]
https://github.com/acemod/ACE3/blob/master/addons/explosives/functions/fnc_startTimer.sqf#L20-L26
Probably just needs to get wrapped in
```sqf
[{
    [{
        _explosive = _this;
        if (!isNull _explosive) then {
            [_explosive, -1, [_explosive, 0]] call FUNC(detonateExplosive);
        };
    }, (_this select 0), (_this select 1), 0] call EFUNC(common,waitAndExecute);
}, [_explosive, _delay], 5, 0.5] call EFUNC(common,waitAndExecute);
```
Probably.

**Comment by esteldunedain** [comment]
Obsolete after changing the way explosives are interacted with
