### ISSUE TITLE
ace_hearing-CfgWeapons has _0 instead of _O

### ISSUE THREAD

**Issue by Pergor** [acemod/ACE3#3194]
In https://github.com/acemod/ACE3/blob/master/addons/hearing/CfgWeapons.hpp in line 21 there's an error:
class H_HelmetCrew_0: H_HelmetCrew_B {};
Should be
class H_HelmetCrew_O: H_HelmetCrew_B {};

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/commit/6b4eeedbad046f0259950bab67aee133c6063479

**Comment by commy2** [comment]
@SzwedzikPL explain yourself

**Comment by SzwedzikPL** [comment]
@commy2 sorry, happens :|
