### ISSUE TITLE
Missing overpressure zones

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#3196]
ACE3 Version: 3.4.2 Stable & Dev

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
The Merkava TUSK/LIC variant and the T100 have a missing or misconfigured overpressure zone.
Reference video: https://www.youtube.com/watch?v=TQ0TeclRYjU

**Steps to reproduce:**
* Go into the virtual garage
* Pick T100 or Merkava TUSK/LIC
* Shoot over the AI -> they receive no damage

**Where did the issue occur?**
* Virtual garage, Editor

**Comment by PabstMirror** [comment]
Fixed via  #3172

https://github.com/acemod/ACE3/pull/3172/files#diff-69e15fd96dc733e0733e2f5476a84cdcR52

still want to look at compatPBOs

**Comment by PabstMirror** [comment]
RHS tank cannons seem to inherit from `cannon_120mm` so they are picking up reasonable values
