### ISSUE TITLE
Spectator - Controller Support

### ISSUE THREAD

**Issue by jameslkingsley** [acemod/ACE3#3198]
It would be nice to have controller support for the ACE spectator. Players should be able to bind their controller to Bulldozer controls (or custom addon controls) to do things like change their zoom (fov), movement, look, altitude, toggle 3D icons etc.

**Comment by esteldunedain** [comment]
I'm afraid bounding controllers to addon controls is impossible as far as I know. However, I believe there's third party software to emulate key presses when pressing controler buttons, so that could be a solution for you.

**Comment by jameslkingsley** [comment]
Ah okay that sucks. I'll look into third-party programs; I know AutoHotKey has options to do this sort of stuff, only downside is it's not a UI based program (as far as I know).
