### ISSUE TITLE
Todo list for FCS

### ISSUE THREAD

**Issue by VKing6** [acemod/ACE3#3201]
A list of things to investigate for the FCS.
- Wind correction.
  - Additional manual windage adjustment.
- Ability to disable lead and wind correction calculation in config.
- Rewrite to enable lead calculation continuously while holding Lase. Closer to real-life AFV FCS.
  - Simplify lead calculation to use pure azimuth maths instead of positions
  - Add continuous lase option

**Comment by esteldunedain** [comment]
Interesting.

> Wind correction.

Do RL system do this? 

> Rewrite to enable lead calculation continuously while holding Lase

That should be easy.

**Comment by VKing6** [comment]
>Do RL system do this? 

Yup.
Obviously not all of them, but things like tanks definitely. A manual windage adjust could also be added as an alternative.

**Comment by dixon13** [comment]
I will try and get a tanker to chime in as well. He was in a Leopard 1 in Iraq. Also, got another guy that is going into the Marines who knows a lot about tanks, and will hopefully be a tanker.

**Comment by natrius** [comment]
https://github.com/acemod/ACE3/issues/414/#issuecomment-101989010
and
https://github.com/acemod/ACE3/issues/414/#issuecomment-186943955

Seen to late that someone mentioned it already. + cych is more accurate about this matter.
Or is this what you want to do with point 3?

**Comment by esteldunedain** [comment]
@natrius, copy the link that appears on the time above the comment to reference specific comments.

Like this: https://github.com/acemod/ACE3/issues/3201#issuecomment-191973407

**Comment by natrius** [comment]
Actually i tried exactly this. You see what came out. https: // github . com/scemod/ACE3 / issues/ 414/#issuecomment-186943955

**Comment by esteldunedain** [comment]
> Actually i tried exactly this. You see what came out. https: // github . com/scemod/ACE3 / issues/ 414/#issuecomment-186943955

That has a lot of extra spaces in between, otherwise it would work fine.

**Comment by natrius** [comment]
Yeah, i did this so GitHub does not try to change the link by themself. Weird. Without spaces, same link:
https://github.com/scemod/ACE3/issues/414/#issuecomment-186943955

**Comment by esteldunedain** [comment]
It says `scemod` instead of `acemod`

**Comment by esteldunedain** [comment]
> FCS: Improve it, as it is now, it is a bit arcade-like, its very fast to get the range - its a bit point&click, nothing else. 

What would the suggestion for improvement be?

**Comment by natrius** [comment]
*sigh* i give up. Just delete our rest whole conversation, i added 2 spaces to my "original" so its possible to copy&delete space.

**Comment by esteldunedain** [comment]
RMB -> Copy Link, then RMB -> Paste

**Comment by natrius** [comment]
> What would the suggestion for improvement be?
Actually just what cych postet, actually just add some kind of delay for "calculation time". *shrug*

> FCS limitation delay :
>when using tablock to adjust gun range, we can spam it without any limitations. On such system there is a laser calculating the correct value, this laser need several seconds to reinitialize for the next measurement. A delay of 3-4 seconds between each measures should be implemented.

**Comment by natrius** [comment]
https://github.com/acemod/ACE3/issues/414/#issuecomment-101989010

**Comment by esteldunedain** [comment]
>  A delay of 3-4 seconds between each measures should be implemented.

Is that a thing for modern systems?. Do you have a source?

**Comment by natrius** [comment]
Erm, nope. You may better ask cych about that. But as i was reading now about this, as i understood it, it is like that: You see an enemy, lock in and from this moment on everything is calctulating on the fly, also while moving. There is nothing about an initial calculation time i was able to find. 
For example, they say the Leopard2 FCS is "superior" while moving towards an enemy. Whatever this means.

A delay for about something between 2 and 4 second would add something a little bit of a challenge. You gave a shot on the tank and there is suddenly another one. Recalculate or just aim higher, whatever. As it is now its just: see, FCS, fire, see, FCS fire and the only thing is the loading time.

I hope you get what i mean.

**Comment by esteldunedain** [comment]
I understand what you mean. We could add a delay between the time the button is pushed and the range is measured, which afaik should be closer to how it works irl.

However, I'd be more inclined to do that if somebody confirmed how much that delay is actually required in real life. I think modern FCS probably got rid of that.

It might be nice to have anyway to support  mod vehicles that are a bit older.

> For example, they say the Leopard2 FCS is "superior" while moving towards an enemy. Whatever this means.

That means that it corrects for relative forward velocity in addition to lateral. Our system doesn't do that, so in fact is a little more primitive than the one in the Leopard. I think it's unrelated to the issue we are discussing.

**Comment by VKing6** [comment]
The delay has more to do with making sure the laser doesn't overheat from overuse than the time required for doing calculations, which is more or less instant.

There's no reason why we couldn't add a slight delay between lasing operations, as well.

**Comment by dixon13** [comment]
This is from a Canadian Tanker who was in a Leopard 1 and Leopard 2...
"FCS is made to make it arcade like. It is literally point and click."
Other notes from him...
 - He only checked the windage in the morning and that was it. If the wind had changed drastically, then he might check it in the middle of the day again.
- Most of the time he only fire HEAT and SABOT's so they would never really need to change the windage.
- Also, his crew could shoot 3 rounds down range within 10 seconds.

**Comment by dixon13** [comment]
He also said a that he would fire manually most of the time. When he spots a target, they would lase once and fire, then they would just fire again making slight corrections using the sight picture.

**Comment by PabstMirror** [comment]
Closing for now as we are deprecating FCS on most vehicles in favor of the vanilla FCS system
