### ISSUE TITLE
laser_selfdesignate does not measure the distance

### ISSUE THREAD

**Issue by Stolenko** [acemod/ACE3#3202]
ACE3 Version: 3.4.2 Stable
In version 3.4.1 is all right

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* None

**Description:**
* https://www.youtube.com/watch?v=d8YTECaprqg&feature=youtu.be

**Steps to reproduce:**
* Sit in a RAH-66 Comanche
* Enable laser
* Fire!

**Where did the issue occur?**
* Editor, MP

**RPT log file:**
* http://pastebin.com/mQJba7CD

**Comment by SzwedzikPL** [comment]
Can reproduce on latest master

**Comment by MinistryOfMadMen** [comment]
This issue also come up with the standard handheld rangefinder. ( No Target Distance ) - Also Laser Guidance does not work with the Laser Designator. Helicopters for eg. can´t lock onto the lasered Target.

**Comment by bux578** [comment]
Mi-48 works fine with laser guidance.

**Comment by esteldunedain** [comment]
Fixed yesterday in #3218.

Thanks for the report.
