### ISSUE TITLE
Dug-in IEDs turn into Urban

### ISSUE THREAD

**Issue by Jansgi** [acemod/ACE3#3203]
ACE3 Version: 3.4.2

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* None.

**Description:**
* When using any other trigger than PressurePlate with Dug-in IEDs the model turns into Urban IEDs

**Steps to reproduce:**
* Place Big/Small IED (Dug-in) -> select remote trigger -> model turns into Big/Small IED (Urban)

**Where did the issue occur?**
* Editor

**RPT log file:**
* -

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by VKing6** [comment]
Confirmed.
