### ISSUE TITLE
Script error when throwing flashbang into water

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#3205]
ACE3 version: 3.4.2 Stable

**Mods:**
* `@CBA_A3`
* `@ace`
* `@bwmod`
* `@taskforceradio`
* `@bw_isaf (custom mod)`
* `@DynaSound`

**Placed ACE3 Modules:**
* Revive, Respawn

**Description:**
![image](https://cloud.githubusercontent.com/assets/1235520/12510633/a3117a04-c10b-11e5-8cd1-efa302b525a9.png)

**Steps to reproduce:**
* Throw M84 into water

**Where did the issue occur?**
* Multiplayer

**RPT log file:**
* http://pastebin.com/1wnQEqU4

**Comment by esteldunedain** [comment]
The grenade doens't exist anymore when the fuze runs out. Should be simple to fix.

**Comment by VKing6** [comment]
Tried reproducing on master with no errors.

**Comment by commy2** [comment]
No point in trying to reproduce this. We don't even know the version of the game / CBA and ACE.

**Comment by PabstMirror** [comment]
This might be the cause:

In a mp environment, targetEvent has network delay, and we pass the grenade object.
If the object gets garbage collected in between event send and event receive it might cause that issue.

I think we could just send posASL instead of object.

**Comment by esteldunedain** [comment]
> In a mp environment, targetEvent has network delay

I agree

> I think we could just send posASL instead of object.

Yep, that should work.
