### ISSUE TITLE
Make.py is failing to build many of the PBOs

### ISSUE THREAD

**Issue by MajorXAcE** [acemod/ACE3#3208]
I wanted to try out some of the branches and I was pretty sure I had everything I needed to do it, but for some reason alot of the addons fail to build. At this point, I'm pretty sure I need some help to get this working.

[logs.zip](https://github.com/acemod/ACE3/files/101664/logs.zip)
![cmd](https://cloud.githubusercontent.com/assets/13529136/12527589/0b57e770-c14c-11e5-9cec-de28e5a6e647.png)

**Comment by PabstMirror** [comment]
```

**Comment by PabstMirror** [comment]
```
Warning: rapWarning: **********missing file(s)***************
Warning: z\ace\addons\aircraft\CfgAmmo.hpp Line 17: \A3\Weapons_f\Data\bullettracer\tracer_red
Warning: z\ace\addons\aircraft\Heli_Attack_01_base_F.hpp Line 914: \A3\Weapons_F_Beta\Reticle\Heli_Attack_01_Optics_Gunner_wide_F
```

Looks like you're missing a3 files on your p drive, run the mikeRo tool arma3p.bat to full extract the p:\a3 folder

**Comment by MajorXAcE** [comment]
Yep, had to download arma3p.cmd and the associated programs to get the a3 files it needed. It works just fine now, thanks for the help.
