### ISSUE TITLE
Chinook Halo Jump

### ISSUE THREAD

**Issue by CarlosHathcock** [acemod/ACE3#3209]
Dear Ace3Team

I have recently seen a video on Youtube as soldiers jumped out of a Chinook (https://www.youtube.com/watch?v=IWnHwg6zP4M). In Arma 3 it is unfortunately not possible in the helicopter around to run. Unfortunately I do not know whether it is possible to program something that you can walk around WHILE the helicopter flies. Could you mean? It is your Mod and what I've written is just a suggestion :).

by Carlos

PS: I love ACE3 :D

**Comment by esteldunedain** [comment]
Sorry, I don't think it's possible. Please post feature requests to the #414 thread instead of opening new tickets.

> I love ACE3 :D

Thanks, we do too.

**Comment by CarlosHathcock** [comment]
ok thx :)
