### ISSUE TITLE
(Ground) stabilize turrets of all vehicles

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#321]
.. where appropriate.
- [ ] UAV's
- [ ] Remaining helicopters
- [ ] Wheeled vehicles
- [ ] Tracked vehicles
- [ ] Boats

**Comment by bux578** [comment]
tagging @VKing6

**Comment by LorenLuke** [comment]
@bux 
With 1.60 and the target pods, can we close this?

**Comment by bux** [comment]
I guess so
