### ISSUE TITLE
DAGR from Commanche can't lock

### ISSUE THREAD

**Issue by Unclefu22** [acemod/ACE3#3211]
Missiles can't lock to targets and fly straight. This is a pilot and AI gunner.

**Comment by madpat3** [comment]
the Missiles are laserguided. 
you have to be gunner. turn on "laserdesignator" via ace-interaction menu. fire Missile and guide the Missile towards the target with your crosshair. 

unfortunately missiles are only guided by the onbord-laser.
so a FAC or JTAC with a laser Designator in his hands, can only mark the target. he cannot guide the Missile. 
this has to be done by the gunner himself.

**Comment by bux578** [comment]
Mi-48 works fine with laser guidance. Seems that it's just the Commanche that has those problems.

**Comment by bux578** [comment]
Related #3202

**Comment by GitHawk** [comment]
DAGR from Ka-60 Kasatka don't lock either.

**Comment by GitHawk** [comment]
#3305 will reintroduce vanilla laser locking until ace_laser is fully implemented.

**Comment by esteldunedain** [comment]
Fixed in #3305
