### ISSUE TITLE
comanche laser-designator

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#3212]
laserdesignator doesn't work with the gatling gun anymore. you hear the Sound of the shots, you can see smoke coming out of the Barrels, but no shots are fired.
when you manually set the range with TAB, everything works fine.

mods: ace, cba

**Comment by Gwynblade** [comment]
Little more info on this: When you turn on the laser with comanche, range is stuck on -0001. Shots are fired, but they are going so high, you can't see them land anywhere. That's why it looks like there are no shots coming out.

**Comment by bux578** [comment]
Thanks for the report.

Duplicate: https://github.com/acemod/ACE3/issues/3202
