### ISSUE TITLE
ACE 3 Interactions with Explosives,Sandbags,SSW,Ladders,etc.. dont work in MP

### ISSUE THREAD

**Issue by Radeni** [acemod/ACE3#3213]
As the title says the interactions with Explosives,Sandbags,SSW kits,Spotting scopes,Tactical Ladders and placeables like that dont work in multiplayer.I've tested it in singleplayer,works like a charm tho in multiplayer it doesnt work for idk what reason.Its not the whole interaction that doesnt work but just the one for placing it down/releasing it useing your prim/sec mouse button.I hope this is fixed soon because it ruins the fun of an Explosive specialist and simillar stuff. :)

**Comment by commy2** [comment]
Make sure ACE runs on the server.
If ACE is running on the server then please upload the servers RPT file

**Comment by Radeni** [comment]
It definetly is running on the server,how do i add the rpt log here tho :\

**Comment by commy2** [comment]
You can upload it to pastebin.com and post the link here. Or you create a "Gist" on Github.

**Comment by MinistryOfMadMen** [comment]
I can not confirm this. We run our servers with ACE & all objects stated above work without an issue.  So there must be something not loading on the serverside. 

The placement is a little bit off, but this may also be user error.

**Comment by Radeni** [comment]
I currently don't have the access to my server machine but i will try to get it as soon as possible for the RPT log.A few things that i didn't mention is that it works when i localhost the server but it works for me only(i will do more testing).Now to explain what is happening ill take tactical ladders for example.Using my scroll wheel allows me to properly adjust the ladders and their rotation,works perfect,tho when it comes to placing it down,clicking on my mouse(left click) triggers my gun to shoot instead of ladder to be placed.Same thing happens with right mouse click aswell,instead of dropping it triggers aiming.I have also noticed that the gun safety doesn't work(shift+`).When i use it i get the message that the gun is in safe mode but i'm still able to shoot.Tested with both unmoded and moded guns.

**Comment by esteldunedain** [comment]
ok @Radeni, I was just about to close this ticket. Get those RPT logs; there are probably other mods loaded causing a conflict.

**Comment by Radeni** [comment]
@esteldunedain I laso was stupid enough not to check the modules.I will do more testing with modules and try to replicate the issue on another dedicated server to get the RPT logs from it.If i dont manage to duplicate it on another server just close this ticket and i will open a new one once i get the RPT logs.
Cheers

**Comment by esteldunedain** [comment]
the rpt contains a list of the addons loaded, so focus on getting those.

**Comment by Radeni** [comment]
@esteldunedain Okay so ive done more testing and it all works except in one mission where alot of ace modules were used.I got the acces to the rpt files but the mission itself has so many script issues that theres thousands of lines and stuff.It seems like its not the ace or the server itself but some modules used in the mission.If you want you can close this ticket but if you want you can give me time to found out the source because i still havent found out what exactly is causing the problem.I will now try module by module until i find out which one is problematic.
