### ISSUE TITLE
Ace 3 KEYS

### ISSUE THREAD

**Issue by BreberaCZ** [acemod/ACE3#3215]
Hi, I got one little request . Is there any way , I can disable Master key for players ? Or can you just give me info , in which pbo are keys located, so I can delete It myself ? I would be very thankful. 

Cheers.

**Comment by PabstMirror** [comment]
Item is from `ace_vehiclelock.pbo`

Is the problem the Virtual Arsnel Ammo Box? I don't use it, but I was wondering if they showed up in that / should be removed from that?

**Comment by BreberaCZ** [comment]
Yea, its the virtual arsenal problem. I just want to disable it so players cant use it, so I thought the best way to do it would be by removing it from ace.

**Comment by PabstMirror** [comment]
None of the key items will show up in the VA in next release.
