### ISSUE TITLE
Bug issues with AtragMX and Kestrel4500...extra character overlay and ghost button push.

### ISSUE THREAD

**Issue by sirhc221** [acemod/ACE3#3217]
ACE3 Version: 3.x.x
Newest version of ACE3 3.4.2

**Mods:**
* `@CBA_A3`
* `@ace`
* @101_editor
* @AdvanceBallistics
* @Alive
* @AllinArmaTerrainPack
* @ASDG_JR
* @ATragMX
* @BC-Phoenix
* @Bornholm
* @British ARmed Forces fAction All in One
* @DragonFyre2.5
* @EBU_Mods
* @inidbi
* @Kestrel4500
* @NATO Russian SF Weapons
*@Optre
*@PRKZ
* @tmr
* @TOG_Jtac
* @TPW_Mods
* @xcam

**Placed ACE3 Modules:**
placed and non-placed modules, but nothing seemed to make a difference in the outcome of the problem

**Description:**

When viewing the AtragMx there is another set of characters over the unit making it impossible to read.  If you go through and click all the buttons you can get a lot of the extra numbers etc to clear off, but as soon as you close it, and open it again, its back to the double print.  When ACE3 mod is NOT enabled this is not a problem.

When viewing the Kestrel 4500 the screen always defaults back to the wind speed.  When you click the 'next' arrow to view the parameters they show up for about a 1/2 second then it switches right back to the wind speed.  Again, when ACE3 is NOT enabled this is not a problem.  

Im guessing the problem might be with the AtragMx and Kestrel itself since it only happens when ACE3 is enabled.

I have copied the cba_enable_auto_xeh.pbo  file over to the addons as well and this did not change anything in the problem.

I have updated CBA and ACE3 as well

**Steps to reproduce:**
Open AtragMx or Kestrel in Editor 'preview' mode

**Where did the issue occur?**
Editor

**Comment by esteldunedain** [comment]
Can you reproduce with only CBA+ACE?

**Comment by sirhc221** [comment]
Funny you should mention that, I had a dream last night about the print overlay and ghost buttons and in my dream someone told me..its like you got two versions running together..and i said wtf..so I got up this morning looked for an ACE Box, original Kestrel/AtragMx were in a NATO Box, and I saw the Kestrel and AtragMX in the ACE Box!  I tried those and they worked fine...even better than the other mods for some reason.

But I didn't know ACE3 came with those mods already, honestly, because I got the Kestrel/AtragMx and ballistic mods first, then months later I read about ACE3 and here we are lol

So problem solved:  delete Kestrel and AtragMX mods and use devices that are located in ACE miscellaneous Box found in editor, under AMMO

Thanks for the fast reply

**Comment by esteldunedain** [comment]
*My psychic powers are getting stronger* :wink:

**Comment by commy2** [comment]
spooky
