### ISSUE TITLE
Artillery Enhancements

### ISSUE THREAD

**Issue by CSmash** [acemod/ACE3#3220]
I'm not sure if this request is in the right area. However, my unit is attempting to form a field artillery unit. Would it be possible to create a fire direction center linked to M109 an M119 vehicles to send fire missions to them? I believe Arma 2 had the concepts right. I am in the Army field artillery and have been for over ten years, and I believe it would add more realism if these functions were added. To be exact to what I'm referring to is the field artillery has 3 different points to initiate a fire mission (the forward observer calls for fire")(the fire direction processing center"FDC")(and the point of fire" the howitzer") the forward observer send the fire mission request to the FDC and they put the gird or type of mission into the computer and send it to howitzer they are linked to "either just one gun or multiple."  if you need any assistance to developing this I would be more than happy to aid in development. This function would allow one center to control gun operated by players. Also incorporating move order to guns to move to specific grids.

**Comment by esteldunedain** [comment]
#414 Please.
