### ISSUE TITLE
ACE3 spectator over-head icons remain active if a live spectator is teleported

### ISSUE THREAD

**Issue by BullHorn7** [acemod/ACE3#3224]
ACE3 Version: 3.4.2 release

**Mods:**
* `@CBA_A3`
* `@ace`
* `MCC`

**Placed ACE3 Modules:**
* A bunch. 

**Description:**
* We have an intractable item (action menu) that allows entering and exiting the ACE3 spectator on-demand. If a player who happens to be spectating at the time is teleported using MCC's 'Teleport' feature, upon exiting the Spectator mod, the player retains the over-head icons from the Spectator mode

**Steps to reproduce:**
* Add this line to an item's init: `this addAction ["Spectate", {[true,false] call ace_spectator_fnc_setSpectator; }];`
* Interact with the item to go into Spectator mode
* Get teleported by anyone
* Exit spectator
* Enjoy all the over-head icons everywhere

**Where did the issue occur?**
* Multiplayer

**RPT log file:**
* Don't have one right now but if it's really important, let me know and I'll get it.

**Image example:**
* http://files.enjin.com.s3.amazonaws.com/821401/modules/forum/attachments/2016-01-22_00010_1453756014.jpg

**Comment by BullHorn7** [comment]
Just received a report from a player that wasn't teleported but had the issue nonetheless

Clarke said: "Nah, I respawned and used the VisCom. Pressed Esc to exit the spectator mode and for some reason the markers got stuck."

Hopefully @SilentSpike can take a look.

**Comment by SilentSpike** [comment]
Believe this is a result of an oversight in PR #3099 which has since been fixed in #3155

**Comment by BullHorn7** [comment]
Sounds good! Any suggestions for the time being, perhaps disable the over-head icons completely?

**Comment by jonpas** [comment]
Fixed by #3155, make a new issue if it's indeed not.
