### ISSUE TITLE
gunner' of vehicle class "car" cannot measure distance 

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#3227]
ACE3 Version: 3.4.2
(stable)

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* *None*

**Description:**
* gunner of the "vec_class_car" cannot measure distance any more.*

**Steps to reproduce:**
* *place an armed car of csat, aaf or nato forces on map, get in as gunner try to measure distance*

**Where did the issue occur?**
* Editor"*

**RPT log file:**
* http://pastebin.com/hi7x1GfS

**Comment by esteldunedain** [comment]
Fixed yesterday in #3218.

Thanks for the report.
