### ISSUE TITLE
RHS RGO grenades explode the instant they are thrown

### ISSUE THREAD

**Issue by NickSeafort** [acemod/ACE3#3229]
I posted this over on the RHS site, and they immediately closed it and said it was an ACE issue. Sharing here for reference: http://feedback.rhsmods.org/view.php?id=1801

**Comment by sargken** [comment]
Hey nice profile pic.

**Comment by NickSeafort** [comment]
Dammit, gerroff my shiny flybird pic xD

**Comment by sargken** [comment]
BF3 all the way man.

**Comment by PabstMirror** [comment]
Are you running the compat pbos from the optional folder?
I thought #3045 fixed this.

**Comment by NickSeafort** [comment]
Apologies, that one didn't turn up in the search for some reason - it fixes the explosion, but there's still an audible bang as you throw it so it's not a perfect fix. Ta!

**Comment by PabstMirror** [comment]
I can't reproduce the audio.  Could you try with just cba+ace+rhs+ace_rhs compat
