### ISSUE TITLE
Minor Bug prevents compilation on Linux

### ISSUE THREAD

**Issue by fr89k** [acemod/ACE3#3231]
I tried to compile ACE on Linux and I'd like to thank you that the code is mostly written, so that it works out of the box. However, there's a minor bug that prevents the code from compiling. Please see the patch below...

[ACE_Linux_compile_patch.txt](https://github.com/acemod/ACE3/files/109501/ACE_Linux_compile_patch.txt)

**Comment by jonpas** [comment]
Could you make a PR?
