### ISSUE TITLE
There is no no possibility of jump with pistol in hand.

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#3234]
ACE3 Version: 3.4.2
Stable 1.54

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
ACE3 added  in the Arma3 safely jump (V-key, durring movement)  over obstacles, but this works ONLY, if in the players hands of primary weapons. If in the hands of the player the pistol, then it doesn't work. 
Logically should be the opposite. A man with a pistol in hand must jump more easily than when in the hands of a rifle, or even machinegun!
Please fix this, jump should be independent of what is in the hands of the player.

**Steps to reproduce:**
Play in ACE3

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed.

**Comment by commy2** [comment]
Same as https://github.com/acemod/ACE3/issues/2105#issuecomment-130313764

**Comment by mickeymen** [comment]
"There is no animation for jumping with pistol / binocular / launcher or without anything.
You have to therefore have a rifle equipped to jump."
If there is no animation, then make this animation! Or remove jump in general!
The possibility of jump only with a rifle looks ridiculous!
Why you can't make and add new animations? Half of the questions for ACE closed without any attempt to fix it! I only see closed, closed, closed

**Comment by esteldunedain** [comment]
@mickeymen, you're way out of line. We work on this for free and don't owe you anything.
