### ISSUE TITLE
Sniper Mechanics on ACE 3 Mod

### ISSUE THREAD

**Issue by DeadshotCassidy** [acemod/ACE3#3237]
The sniper mechanics seem to be off for the ACE 3 mod, after about 1,000 meters or more the gun's rounds are too sporadic and inconsistent to even get a hit. I used an ATragMX and Kestrel 4500 by the way to account for all variables. I used a rangefinder to make sure the target distance was correct and used the protractor to find my inclination angle as well. I have inputted all the data, and there doesn't seem to be any accuracy for a Sniper Rifle. The scopes that ACE does support only go on the elevation adjustment to +30 MOA and -4 MOA, and the wind adjustment part of the scope only goes to +10 MOA and -1 MOA, please fix this so that both integer adjustments of MOA are the same, and that the guns can be zeroed properly. I used a M110, M24, M14, XM2010, M200 Intervention. This is absolutely ridiculous and frustrating considering the fact a sniper rifle is built for precise fire at a distance. Please explain if there could be any slight thing I've not accounted for, because I've tried to account for it all. Also please explain why the gun's data for the Range Card are not being displayed as well. Thank You.

**Comment by esteldunedain** [comment]
Please make a proper report according to the guidelines provided in the wiki first.

**Comment by BaerMitUmlaut** [comment]
>M14

With 1km you're beyond the effective range of 7.62 NATO. Using an M14 for such a distance will of course give you deciding impacts.

With for example the intervention I get very accurate results at 1km. Have you tried this with the wind turned down to 0?

**Comment by esteldunedain** [comment]
Closing due to lack of feedback.
