### ISSUE TITLE
Scopes with only windage adjustment captures keybind for range adjustment

### ISSUE THREAD

**Issue by VKing6** [acemod/ACE3#3238]
If a scope has `ACE_ScopeAdjust_Vertical[] = {0,0}` , #3178 has fixed the audiovisual cues appearing. However the adjustment keys are still being captured, which goes against the intention that if vertical adjust is disabled, vanilla range adjust should be used instead.

This isn't possible at the moment unless separate keys are bound to ACE scope adjust and vanilla range adjust.

Paging @KoffeinFlummi, @bux578, @commy2, and/or @esteldunedain.

**Comment by esteldunedain** [comment]
See #3244.
