### ISSUE TITLE
Door breach bug with claymore

### ISSUE THREAD

**Issue by BreberaCZ** [acemod/ACE3#3239]
There is problem when you are breaching doors with claymore, they open the door on explosion, but they injure everyone around. Can this be fixed ?

**Comment by brainslush** [comment]
First breaching doors with explosives isn't part of ACE. Second claymores even though they are directed charges still give off a detonation in all directions.

**Comment by bux578** [comment]
mcc maybe?

**Comment by esteldunedain** [comment]
MCC for sure, although it uses the ACE intercat menu, which is most likely the source of the confusion.

**Comment by ZikiCZ** [comment]
But this is not bad idea. Breaching kit. Or destructible doors... (for example destroyed door = opened door)
Please feature request ;-)

**Comment by commy2** [comment]
#414

**Comment by ZikiCZ** [comment]
thx
