### ISSUE TITLE
Application of Ballistic grades to 3rd party gear

### ISSUE THREAD

**Issue by Kai-Holmes** [acemod/ACE3#3240]
ACE3 Version: 3.4.2
(indicate if stable or dev, if dev indicate the commit the version is based on)

**Mods:**
* `@CBA_A3`
* `@ace`
* 'Third party armour'

**Placed ACE3 Modules:**
None

**Description:**
When using vanilla gear in ACE3 they are given various ratings which are displayed when hovering over them. 'II, III and IV'. There's no official documentation relating to how people can give these properties to 3rd party ballistic plates and, from what I can tell, I haven't found anything relating to it in the game files either. As it stands 3rd party vests are just given 'No Armour'

**Steps to reproduce:**
Hover over vanilla armour vs modded armour.

**Where did the issue occur?**
Editor

**Comment by commy2** [comment]
This are tooltips made by BI introduced in v1.54. They are completely meaningless. The entry is named `descriptionShort`. This has nothing to do with ACE. If you want to know how to configure your vests and uniforms according to the new hitpoint system from 1.54, then look into the official sample models.
If the thrid party addon works with vanilla 1.54, it will also work with ACE.

**Comment by Kai-Holmes** [comment]
Thank you very much for the reply, I'll look into the hitpoints assigned to them.
