### ISSUE TITLE
Titan Compact Lock flickering

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#3241]
ACE3 Version: 3.4.2
Stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Placed ACE3 Modules:**
- None

**Description:**
Titan missile locks can flicker on and off most commonly at moving or targets surrounded by foliage.This seems to occur in MP and may be to do with Server updating the client on location. I've yet to be able to reproduce it in SP.

During this lock flickering Its impossible to launch the missile and is incredibly annoying and leads to avoidable deaths.  

**Steps to reproduce:**
1. Join ACE3 server (preferably with slight lag and non opermal performance)
2. Take Titan Compact Launcher and AT missile
3. Attempt to target moving or semi concealed vehicle 
4. Observe Flickering

**Where did the issue occur?**
 "Multiplayer"

**Comment by kripto202** [comment]
I only see it when it tries to lock on to a heli.
