### ISSUE TITLE
advanced medic system: wound size

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#3243]
ACE3 Version: 3.4.2
stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
* *weather, repair, medic (see rpt-file for detail)*

**Description:**
* it seems, that size of the wound doesn't matter.
all wounds, if big, middle or small seem to have the values.

so i.e. if you bandage a medium wound, of the type of a "velocity wound", with one "quikclot"
and one "field dressing", the wound isn't bleeding anymore.

same result with a big wound of that type.
*

**Steps to reproduce:**
* *place medic as player on map and an other unit. place advanced-medic modules. >preview> hurt the other unit and bandage it.*

**Where did the issue occur?**
* Editor*

**RPT log file:**
* http://pastebin.com/BBPEufiL*

**Comment by Glowbal** [comment]
You are correct. We are at ~30% completeness for the overhaul of the configuration. It will make it in the next update.

**Comment by madpat3** [comment]
ur raising my heartrate :)

**Comment by bux578** [comment]
> ur raising my heartrate :)

That makes an awesome valentine card
![image](https://cloud.githubusercontent.com/assets/1235520/12732382/9550688a-c935-11e5-8470-a99c7a3718d9.png)

**Comment by Glowbal** [comment]
Comes with 3.5.0
