### ISSUE TITLE
Some AI units invulnerable in blacked out state.

### ISSUE THREAD

**Issue by neurook** [acemod/ACE3#3246]
ACE3 Version: 3.4.2.0

Some units that enter the blacked out wound state can soak up an infinite amount of damage after the fact.

https://www.youtube.com/watch?v=Szd8EW7s8ug

Not limited to RHS units. Seems to affect random AI units (not all of them). Some AI will eventually die/time out, but not even rocket artillery can hurry them along.

**Comment by Glowbal** [comment]
I have asked you already, but for good meassure: Please provide RPT log files and ACE settings. Without it there is nothing we can do.

It could very well be that the video is of an AI being in the revive state, which case that is not a bug at all.

**Comment by neurook** [comment]
ACE Debug: http://pastebin.com/Tgtcg1aP
ARMA Debug: http://pastebin.com/BN21yd7f

It's caused by revive being enabled for AI. Setting the number of lives to 0 or -1 has no effect. The invulnerable wound state is applied unevenly to wounded enemies with some dying instantly, some getting back up, and some lying there without a pulse but twitching and moaning until they time out.

**Comment by Glowbal** [comment]
After investigation:
- Video displays revive state. This shows intended behaviour.
- The number of lives setting has nothing to do with revive enabled / disabled. Using -1 will disable the live system within revive, resulting in infinte lives.
- The sometimes dying of AI units is a cause of the AI unconsciousness setting, so also intended behaviour.

In consclusion; this does not seem to be a bug. Thanks for the report @neurook
