### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by ExPooL** [acemod/ACE3#3251]
I will explain the situation. I am Russian player, I really like your mod. Before the updates everything was fine, but after the latest update I got to play ARMA 3 on the server with following mods. (List of mods: @ACE;@CBA;@RHSAFRF;@RHSUSAF;@Leights OPFOR pack official;@spectator,@swt_marker_a3;@AllInArmaTerrainPack;@ALL_Royak;@Russia_SPN;@Task_Force_radio). But recently, I am getting kicked from briefing, i.e. I am getting kicked before even the map loads. Tried of searching for solution and came to the conclusion that I will test which mods are not working right. Opened the editor, put one soldier civil gave it a module of Zeus put advanced medicine and turned her and began to remove the addon from the Assembly. And came to the conclusion that the game crashes because the mod @Leights OPFOR pack. Began to look for conflicts with this addon and came to the conclusion that it conflicts with @ACE. But as I have not decided still crashes. I reinstalled game reinstalled Addons, nothing helped.In desperation I write to you here require assistance!!!

**Comment by commy2** [comment]
You should upload a RPT file so we have something to work with.

**Comment by ExPooL** [comment]
https://yadi.sk/d/DkZmNkBSoBaLh

**Comment by commy2** [comment]
So if I understand this correctly, then this error also happens when only these mods are started
`@ACE;@CBA;@RHSAFRF;@RHSUSAF;@Leights OPFOR pack official;`
Correct?

Can you also upload a RPT of a crash with these mods only? Thank you.

**Comment by ExPooL** [comment]
https://yadi.sk/d/Y7wINR73oCrb8  Here is the file.

**Comment by ExPooL** [comment]
And accidents only happen when chaining fashion @ACE+@CBA and @LOP (Leigh's Opfor pack ).

**Comment by ExPooL** [comment]
And yesterday I had to connect to the server with the error but with another bunch of mods now will download the RTP file.https://yadi.sk/d/EtS6UqcmoCtJ8

**Comment by ExPooL** [comment]
I found a solution to this problem!!! My computer blocked the dll from your mod, I had to unlock them manually. Everything was working as before, thank you for your answers.
