### ISSUE TITLE
RHS Tanks,  an amendment to the wind

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#3252]
ACE3 Version: 3.4.2
stable

Mods:

@CBA_A3
@ace
@ RHS
Placed ACE3 Modules:

Description:

RHS Tanks, It does not make allowances for the wind.
M2A3, M1A1, M1A2 very bad shoot.

Steps to reproduce:

MP

**Comment by esteldunedain** [comment]
Our FCS doesn't currently compensate for wind in any vehicle. That's planned to be included at some point, according to: #3201. Closing this in favor of that ticket.

Thank you.
