### ISSUE TITLE
Updating Base Class Errors with Movement

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#3260]
Arma 3 RC 1.56.134250
ACE3 3.5.0 dev

**Description:**
Updating base class errors in RPT

Example:
 8:55:52 Updating base class AmovPercMwlkSlowWrflDf_ver2->AmovPercMstpSlowWrflDnon, by z\ace\addons\movement\config.bin/CfgMovesMaleSdr/States/AmovPercMwlkSlowWrflDf/

**Steps to reproduce:**
* Run latest ACE Master with CBA v2.3RC

**Where did the issue occur?**
* RPT

**RPT log file:**

https://gyazo.com/bee580c7e719a95c010df804cc48004
![https://gyazo.com/bee580c7e719a95c010df804cc48004](https://i.gyazo.com/bee580c7e719a95c010df804cc48004d.png)

**Comment by jonpas** [comment]
This was decided to get removed IIRC, as the new walk animation replaces the ACE3 fix.

**Comment by Glowbal** [comment]
@jonpas is correct.
