### ISSUE TITLE
Missing 2 functions from ace_zeus

### ISSUE THREAD

**Issue by SzwedzikPL** [acemod/ACE3#3264]
https://github.com/acemod/ACE3/blob/master/addons/zeus/XEH_preInit.sqf#L20-L21

**Comment by esteldunedain** [comment]
Yup, it happens on my machine too. Certainly something that we merged today.

**Comment by SzwedzikPL** [comment]
> Yup, it happens on my machine too. Certainly something that we merged today.

https://github.com/acemod/ACE3/commit/f1ce133d3229738835c1efd287ea6d7bd75d4286

**Comment by jokoho48** [comment]
https://github.com/acemod/ACE3/commit/f1ce133d3229738835c1efd287ea6d7bd75d4286#diff-635399c56ca1e599b78c4aa52329587cR20

this was after the release merge

**Comment by esteldunedain** [comment]
Yes, @Glowbal had to resolve conflicts and that slipped
