### ISSUE TITLE
Ace 3 Revive bug with destroyed vehicles

### ISSUE THREAD

**Issue by Radeni** [acemod/ACE3#3269]
Description:It happened alot of times that while driving a vehicle,the vehicle gets shot and destroyed tho with ace the crew can survive and/or jump out while some crew dies too.When the module "Revive" is on as you know it moves the player to an unconcious state instead of killing him.Usually the driver is the one that dies from the explosion,atleast in my case where i used the RG33 from RHS and some default vehicles.When the vehicle was destroyed the driver was moved out of the vehicle by default and is set to unconcious.This is where the issue occurs.Its a small issue but in moments like getting shot at it means alot.When the player is moved out of the destroyed vehicle by default,not by another player,he is standing up holding his gun in his hands and looking normal even tho he is fairly injured and unconcios.This makes others not notice that the player is down and makes the player wait for the bleedout timer.I hope this is possible to fix.

Modules placed:  Ace 3 Revive "On"

Mods:
@cba_a3
@ace 
@RHS:USAF

Where did the issue happen:

Anywhere,singleplayer,multiplayer,editor

How to replicate:

Place the ace revive module,drive a vehicle over a mine or something that will destroy it(Might need more people)

RPT File: Not needed

**Comment by esteldunedain** [comment]
@Radeni, thanks for the report. Please edit the ticket to comply with these guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by ivankrouglyi** [comment]
I think that's not "ace revive module" problem. It's appear everytime with ace\rhs (even on not rhs vehicles).
