### ISSUE TITLE
Unify keybindings for some global actions so we have 1 key registration in the CBA menu OR split into different sub-addons.

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#327]
Currently, we have multiple optional places where we have a unified key (like Tab for rangefinding/zeroing) which may have multiple definitions in CBA because of addKeyBind.

We should unify these keys in common, and use an ACE event to call all the child key handlers.

**Comment by NouberNou** [comment]
We need to look at how we can split the single ACE addon across multiple addons if possible to reduce over lap. This will probably be easier than describing one key used in potentially different contexts.

**Comment by Glowbal** [comment]
Closed by #930
