### ISSUE TITLE
Interaction through barriers

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#3270]
Arma 3 1.54
ACE3 most current dev 3.5.0

![image](https://cloud.githubusercontent.com/assets/1235520/12849292/3eae1dbe-cc1f-11e5-994f-4351b5fcf21b.png)

**Comment by Glowbal** [comment]
Strange. We are doing lineIntersectSurfaces with interaction, no?

**Comment by PabstMirror** [comment]
If the distance is very close, we skip the LOS check
```
        if ((_distanceToBasePoint > 1.5) && {!(_params select 4)}) exitWith {
            // If distance to action is greater than 1.5 m and check isn't disabled in params, check LOS
            lineIntersects [AGLtoASL _headPos, AGLtoASL _pos, _object, ACE_player]
        };
```
