### ISSUE TITLE
Severe performance drop

### ISSUE THREAD

**Issue by Thomas-Sev** [acemod/ACE3#3273]
**ACE Version**: 3.4.2 stable

**Mods**:
@CBA_A3
@ ace 
@ RHS: RU
@ RHS: USAF
@ AiATP
@ TFAR
@ MSKE 

**Description**: Severe performance drop when launching Arma 3 with ACE. Crosschecked other mods, only ACE gives reduced performance, especially with damage dealing like explosion or bullet hit

**Step to reproduce**: Just launch the game with every mod set that includes ACE

**Where did the issue occur**: Multiplayer, Editor, Single Player, Virtual Arsenal

**Comment by esteldunedain** [comment]
Thanks for the report. Please supply RPT logs of the session. Without further information there's nothing we can do.

**Comment by Thomas-Sev** [comment]
Here is the link to the RPT log
http://pastebin.com/fUGQpztG

**Comment by commy2** [comment]
This issue offers no useful information. I'd say we close it as dup of #823

**Comment by Thomas-Sev** [comment]
New RPT log with multiplayer server and several fps drop moment
And, with all due respect, that post was almost a year ago, new problems could have arisen by then
http://pastebin.com/2Z8BeutF

**Comment by commy2** [comment]
So? Having one ticket for one issue is better to work with.

**Comment by Thomas-Sev** [comment]
Again, with all due respect, the last helpful comment on that thread is on May 10 of 2015
Are we, me and others who got into problems like this, going to look at the comment on May 10 of 2015 in hope that the code, our hardware, the scripts or stuffs like that will repair itself by equivalent exchange?
Okay, I'm sorry, I'm in a bit of a fixed so I got kinda angry there, but please keep this as a preference for any other future updates and on?
Apology and thanks in advance

**Comment by commy2** [comment]
You could've posted your RPT there. (You don't have to now - it's linked by github magic.)
823 is set on milestone "ongoing" so there is no reason to open another issue.

**Comment by commy2** [comment]
duplictae of #823
