### ISSUE TITLE
Prioritize in-vehicle interaction based on position

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#328]
- Cargo players should have other players and the cargo as an interact priority
- Gunners should have gun/optic options as a priority
- Commander etc etc etc

Basically, we should prioritize how the interact menu is displayed based on position. We may want to add all non-priority actions to a sub-menu instead for these scenarios. 

I'm not sure how possible this is. This comes down to a discussion on uniformity vs. ease of use.

**Comment by Glowbal** [comment]
Clean up old issues.
