### ISSUE TITLE
No Self-interaction option

### ISSUE THREAD

**Issue by c1dodger** [acemod/ACE3#3281]
When i load in game, i have the interaction menu that works on other people but not self interaction. when i got into my setting i do not have an option for it at all. [http://postimg.org/image/a73lcw939/](url)
any help at all would be nice. thank you

**Comment by PabstMirror** [comment]
This is really odd, both keys are added right after eachother.

Could you make sure you have the most recent version of cba and ace: https://github.com/CBATeam/CBA_A3/releases/latest
https://github.com/acemod/ACE3/releases/latest

If you are still having issue, please make sure to upload an rpt (most recent file in %localappdata%/Arma 3/).

**Comment by PabstMirror** [comment]
Also, please try executing this in the editor (hit escape and post in big box):
`profileNamespace setVariable ["cba_keybinding_registrynew", nil]; saveProfileNamespace;`
and hit local Exec.

**Comment by c1dodger** [comment]
thank you very much. you helped me fix in issue in 2 minutes that ive had for about a month. the exec. code did the trick.

**Comment by PabstMirror** [comment]
good to hear

**Comment by jokoho48** [comment]
for reference https://github.com/CBATeam/CBA_A3/pull/155
