### ISSUE TITLE
Can't get AI to perform any medical at all. 

### ISSUE THREAD

**Issue by Emeonso** [acemod/ACE3#3284]
I'm trying to create a mission but the AI wont use any medical items to heal themselves. I've tried many different options and combinations with the modules to no avail. Am I missing something? I have no other mods installed apart from the latest CBA.

**Comment by esteldunedain** [comment]
You are correct. AI units don't use ACE medical system. Programming AI support may be one eventually , buy it's rather difficult and low priority, given ACE focus on MP.

Thanks for the report.

**Comment by Emeonso** [comment]
is there a way i can disable the medical system for the ai so they can use vanilla, or does the ai just have no healing capability with this mod full stop?

**Comment by esteldunedain** [comment]
> is there a way i can disable the medical system for the ai so they can use vanilla

Sorry, there isn't. You can remove the ace_medical pbo to emove the medical system from all units, including players.

**Comment by Emeonso** [comment]
thanks for the response. itd be great for missions makers to see some basic ai usage of the medical system.

**Comment by esteldunedain** [comment]
yup, we'd like that too.
