### ISSUE TITLE
Battleye blocking ACE 3 Dlls and all dlls that arent by BI

### ISSUE THREAD

**Issue by Radeni** [acemod/ACE3#3286]
Description:
So yesterday Ace was working perfectly,i was playing and everything.Today i wake up and try to make mission in the editor.As i make it and hit preview the mission starts loading and then an error pops out about ace3 dlls.Usually its "ace3_fnc.dll not found!".I started searching trough RPT files and realized that its Battleye blocking it.I also asked around and all my friends have the same error and the error occurs in both SP and MP aswell as the Editor.I found battleye logs and i will put em bellow.Even the malloc dlls that i have installed are blocked so this is a Battleye issue but i want to say it here for others to know.

Where does the error occur:
Singleplayer,Multiplayer,Editor

Battleye RPT:

2/7/2016 4:26:29 PM - Blocked loading of file 'G:\SteamLibrary\steamapps\common\Arma 3\@ace\ace_advanced_ballistics.dll'

2/7/2016 4:26:18 PM - Blocked loading of file 'G:\SteamLibrary\steamapps\common\Arma 3\@ace\ace_fcs.dll'

2/7/2016 4:26:08 PM - Blocked loading of file 'G:\SteamLibrary\steamapps\common\Arma 3\@ace\ace_clipboard.dll'

2/7/2016 4:25:58 PM - Blocked loading of file 'G:\SteamLibrary\steamapps\common\Arma 3\@ace\ace_parse_imagepath.dll'

2/7/2016 4:25:48 PM - Blocked loading of file 'G:\SteamLibrary\steamapps\common\Arma 3\@ace\ace_break_line.dll'

2/7/2016 4:25:20 PM - Blocked loading of file 'G:\SteamLibrary\steamapps\common\Arma 3\@ace\ace_medical.dll'

2/7/2016 4:24:02 PM - Blocked loading of file 'G:\SteamLibrary\steamapps\common\Arma 3\Dll\tbbmalloc.dll'  <-- Custom memory allocator

I know that you cant fix this as its a battleye issue but this should be here for others that get the same error!

**Comment by PabstMirror** [comment]
Working for me now, I do know the sever goes down from time to time and that will cause to to goto block all mode.

If it is still not working for you please try
 - Make sure to launch from the new launcher and not command line, as I think that's needed to trigger the update.
 - Try manually updating from http://www.battleye.com/downloads/ grab all the arma files and stick them in `C:\Program Files (x86)\Steam\steamapps\common\Arma 3\BattlEye`
 - Please take a screen shot of the battleye tab in the launcher: 
![image](https://cloud.githubusercontent.com/assets/9376747/12874024/731a408c-cd91-11e5-871c-f39dd122291a.png)

Worse case, if you just want to use the editor when battleye is down, then just launch arma3.exe from the command line to bypass battleye.

**Comment by Radeni** [comment]
Yea,i know,its ok now,their server was down only for half an hour i think
tho this thread is here to show others if they get errors whats causing
them.I know that i can just launch the game without battleye.

2016-02-07 18:55 GMT+01:00 PabstMirror <notifications@github.com>:
