### ISSUE TITLE
No name in nametag on AI

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#3289]
ACE3 Version: 3.4.2 (stable)

**Mods:**
* `@cba_a3`
* `@ace3`

**Placed ACE3 Modules:**
N/A

**Description:**
When nametags are enabled for AI only the rank icon is shown, but the name is empty.

**Steps to reproduce:**
* Put down an AI
* Enable `Show name tags for AI units` (`ace_nametags_showNamesForAI`)
* Observe

**Where did the issue occur?**
Singleplayer - Editor

**RPT log file:**
N/A

**Comment by esteldunedain** [comment]
Can't repro in current master. Nothing's changed since release though.

![2016-02-08_00012](https://cloud.githubusercontent.com/assets/7674951/12905938/381885e6-ceba-11e5-8bfb-5521c702b992.jpg)

Any more information about this @jonpas (e.g. settings)?

**Comment by jonpas** [comment]
Name Tags settings are exactly like yours on the screenshots, this time tested on current master (but as you said, no difference).

After some fiddling I noticed it only happens for Zeus spawned units, those spawned in the editor show it fine. When spawning a Zeus unit the following is logged into the RPT:
```
WARNING: Function 'name' - B Alpha 2-2:1 has empty name
```

**Comment by jokoho48** [comment]
@jonpas can you test if that occlude too with createVehicle/createUnit/createAgent(the last one i am not sure if this will work)?

**Comment by esteldunedain** [comment]
I don't think we can do much about this, short of creating a name for the units ourselves. I'd much rather wait for BIS to fix it.
