### ISSUE TITLE
Not an issue more of a suggestion Regarding Medical / revive system

### ISSUE THREAD

**Issue by onedigita** [acemod/ACE3#3291]
I would sincerely love more customization options for the revive system. 

1. the ability to turn on or off the options to still be able to talk or use radio even when your down.  this should be a option you can either enable or turn off based on the mission maker settings.

2. If down the ability to mark yourself on the map and that your not dead and your current pause.

3. I want the ability for any solider to be able to revive people, but are only able to be fully healed by a medic.

4.  Just lots of more customize-able options that missions makers can play with to get these medical settings the way they want for that particular mission.

Side note when if ever will this go on steam so players can subscribe and jump on other missions easier.

thanks for all the amazing work everyone has put into this project.

**Comment by bux578** [comment]
Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
