### ISSUE TITLE
Map Gesture not working

### ISSUE THREAD

**Issue by kamkill01011** [acemod/ACE3#3292]
ACE3 Version: 3.4.2
stable

**Mods:**
* `@CBA_A3`
* `@ace`
* `@TFAR`
* `@Ares`

**Placed ACE3 Modules:**
* Map Gestures

**Description:**
* When someone try to point something on the map nobody can see it (except him).

**Steps to reproduce:**
* Play a mission with the module Map Gestures and with someone else, move next to the other player and try to point things. The yellow point appear for you but not for the other.

**Where did the issue occur?**
* Multiplayer

**Comment by esteldunedain** [comment]
Thanks for the report. I couldn't reproduce it in current master, but I could only test on Hosted MP. Nothing in that module changes since 3.4.2 release except some stringtables, so it's either a problem on @kamkill01011 setup or only happens in dedicated.

Keep in mind that:
- You don't need any module for this to work. It's enabled by default.
- Range is rather limited by default, so you have to stay very close to each other.

**Comment by jokoho48** [comment]
@esteldunedain did you tested it with UGV/UAVs?

**Comment by esteldunedain** [comment]
> @esteldunedain did you tested it with UGV/UAVs?

No, I don't know what you mean.

**Comment by commy2** [comment]
The little persons contolling the UAVs have names (as well as all other agents with a brain), but they are not supposed to show a nametag.
I don't see how this is related to this issue though.

**Comment by jokoho48** [comment]
ups that was in the wrong issue/PR lol
wtf github i know that i sendet it in the PR you made dammed

**Comment by kamkill01011** [comment]
I tested it on hosted MP, not dedicated, I know that the range is limited I was using ST_Map_Gestuers until now because I didn't know it was intergrated in ACE 3. I just tested it on a vanilla mission "Escape from Altis" with only ACE 3 and CBA v2.2.0, still now working. Only the map is required right ? not the map tools.

**Comment by commy2** [comment]
Post RPTs

**Comment by PabstMirror** [comment]
RPTs from both clients would be helpful.
If either client is still running ST_Map_Gestures, the ace version will not work.

**Comment by kamkill01011** [comment]
Ok, so it seems that the problem was that we still had the @ST_Map_Gestures folder in the Arma 3 directory, so we deleted it and now it works, thanks everyonw for you help.

**Comment by esteldunedain** [comment]
Np, thank you.
