### ISSUE TITLE
Zeus integration not working / not available

### ISSUE THREAD

**Issue by Zakant** [acemod/ACE3#3295]
ACE3 Version: 3.4.2 stable (Steam workshop)

**Mods:**
* `@CBA_A3`
* `@ace`
* `@ace_server`

**Placed ACE3 Modules:**
None.

**Description:**
When starting the standard BIS Zeus Mission, none of the ACE3 features are working for the zeus player. So `Strg+Win` doesn't bring up any interface, neither are their any zeus modules.

**Steps to reproduce:**
* Create a multiplayer game
* Choose BIS standard zeus mission and altis.
* Choos the dedicated zeus slot.

**Where did the issue occur?**
* Local Mulitplayer
* Dedicated Multiplayer

**RPT log file:**
None

Zakant

**Comment by jokoho48** [comment]
https://github.com/acemod/ACE3/issues/3159

**Comment by SilentSpike** [comment]
Just to clarify, there are no zeus modules at all or simply no ace ones?

The ace ones won't show up if their respective addon isn't loaded, however we've had no reports of missing list entries otherwise.

**Comment by Zakant** [comment]
Hey, okay sorry is just searched the open issues for a similar one and didn't found that one.

@SilentSpike No the normal Zeus modules are still availabel. Intresting side fact: If i create a zeus mission in the editor I see the ace modules as described. However if i host the multiplayer mission they are missing.
I haven't deleted any .pbos so from my point of view they SHOULDNT missing at all.

**Comment by SilentSpike** [comment]
Did you set the zeus module to include all unofficial addons?

**Comment by Zakant** [comment]
No, i haven't... To be honest i have no idea how i could set the zeus module to load unoffical addons.
 How could i achive this? I've took a quick search at ace3mod.com but was unable to find any references to configure zeus. 
I also haven't changed any zeus related settings nor placed any zeus or ace related modules. Neither in multiplayer nor in the editor.

**Comment by commy2** [comment]
Set the Game Master module to allow all addons "including unofficial ones"

**Comment by Zakant** [comment]
In the editor scenario the setting is set to `All offical addons`. But even if i change it the result is the same. I can see the ace modules in both settings.
For the multiplayer part i cant tell, because the mission is bohemia made.

I've create a very small zeus template mission and: It's working. So obviously bohemia has disabled external addons within their classic zeus mission. So as a workaround i'll just create a zeus template by my own and juse this instead of the offical one.

**Comment by esteldunedain** [comment]
> I've create a very small zeus template mission and: It's working. So obviously bohemia has disabled external addons within their classic zeus mission. 

So typical

**Comment by Zakant** [comment]
Okay, maybe it would be an idea to offer the user the possibility to activate ace addons / all addons by an ace setting. I've tried to change https://github.com/acemod/ACE3/blob/5b85f6087bcd80ef5a7554b58551a07a53ad8b05/addons/zeus/functions/fnc_bi_moduleCurator.sqf#L67 to include allways all addons and the ace modules showed up in BIS zeus mission. This would allow users to use zeus missions that were not designed to work natively with ace.
