### ISSUE TITLE
intreaction menu dosent work

### ISSUE THREAD

**Issue by 123aqw** [acemod/ACE3#3297]
hey could you guys check and bug i have cba + ace did take userconfig to userconfig and keys to keys i dont know whats going on ;(

**Comment by Glowbal** [comment]
Hi @123aqw,

Could you explain what the issue is that you need assistance with? I'm afraid we cannot help you until we know more.

**Comment by 123aqw** [comment]
i launch up the game and everything is working fine go into editor and start messing around with stuff but the intreaction menu dosent work at all but i can go and change the keys and stuff in options plz it did work last week :) i dont know what i have done 

can it be there is a mod that is conflicting with ace3 ?

**Comment by Glowbal** [comment]
It is possible you are loading outdated versions of CBA and or ACE. Some mods are prone to cause conflicts with ACE as well. Could you provide your rpt log file? You can upload it to pastebin or as a gist on GitHub. Once we got your rpt log file, we can help you better to find out what is going on.

**Comment by commy2** [comment]
needs RPT file

**Comment by 123aqw** [comment]
here is the RPT file github gist here https://gist.github.com/123aqw/cd38072808b4c344271a

**Comment by commy2** [comment]
```
23:01:58 Error in expression <HitFace max HitNeck>
23:01:58   Error position: <HitFace max HitNeck>
23:01:58   Error Undefined variable in expression: hitface
23:01:58 Error compiling 'HitFace max HitNeck' in 'HitHead'
23:01:58 Error in expression <HitPelvis max HitAbdomen max HitDiaphrag>
23:01:58   Error position: <HitPelvis max HitAbdomen max HitDiaphrag>
23:01:58   Error Undefined variable in expression: hitpelvis
23:01:58 Error compiling 'HitPelvis max HitAbdomen max HitDiaphragm max HitChest' in 'HitBody'
23:01:58 Error in expression <HitArms>
23:01:58   Error position: <HitArms>
23:01:58   Error Undefined variable in expression: hitarms
23:01:58 Error compiling 'HitArms' in 'HitHands'
```

I wish we had 2.3.0 CBA right now :cry:

**Comment by commy2** [comment]
@123aqw
please try to reproduce with only CBA and ACE on vanilla units. Thank you.

**Comment by 123aqw** [comment]
ok soo its just the unit that is wrong or ? ok thx i hope it works i will test it tomorrow if not i will reply to this threat thx :)

**Comment by 123aqw** [comment]
it dosent work at all :(

**Comment by commy2** [comment]
post new RPT

**Comment by 123aqw** [comment]
https://gist.github.com/123aqw/508f3cf4553f7113a5bf

**Comment by commy2** [comment]
```
16:30:27                                               name |               modDir |    default |               origin |                                     hash | hashShort | fullPath
16:30:27 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
16:30:27                        @Santa Catalina Island, USA | @Santa Catalina Island, USA |      false |             GAME DIR | 7c2c0fa535befdb5de9083c67d33cc815a68eb69 |   356b8bf | D:\SteamLibrary\steamapps\common\Arma 3\@Santa Catalina Island, USA
16:30:27                                    Norwegian Units |     @norwegian_units |      false |             GAME DIR | 418bbf06b11999b39223cccb8e0610e9e6985e2f |   2533bb4 | D:\SteamLibrary\steamapps\common\Arma 3\@norwegian_units
16:30:27                         Zade's BackpackonChest-Mod |            @ZADE_BOC |      false |             GAME DIR | 4f405875924844ab210c890f306fdd215d4ac1f4 |  8017f20a | D:\SteamLibrary\steamapps\common\Arma 3\@ZADE_BOC
16:30:27                       Community Base Addons v2.2.0 |              @CBA_A3 |      false |             GAME DIR | 8a3284763c2756c80ace4bb97546dc2afe0618fe |  3a072f47 | D:\SteamLibrary\steamapps\common\Arma 3\@CBA_A3
16:30:27                  Advanced Combat Environment 3.4.2 |                 @ace |      false |             GAME DIR | 1474b031812396e4d0b4901d4c5604eea2077e67 |  54f05365 | D:\SteamLibrary\steamapps\common\Arma 3\@ace
16:30:27                                  Arma 3 DLC Bundle |            dlcbundle |       true |            NOT FOUND |                                          |           | 
16:30:27                                    Arma 3 Marksmen |                 mark |       true |             GAME DIR | bca3f585133621c38245a861ea0e695aa5f1d151 |  98bd0c48 | D:\SteamLibrary\steamapps\common\Arma 3\mark
16:30:27                                 Arma 3 Helicopters |                 heli |       true |             GAME DIR | 41e93958bcee08e6e6275a458a506af9d0d25ab6 |   6558b1b | D:\SteamLibrary\steamapps\common\Arma 3\heli
16:30:27                                       Arma 3 Karts |                 kart |       true |             GAME DIR | 4ec5b8ee3e065dc60dc98d30e948796fc01e89df |  120b6924 | D:\SteamLibrary\steamapps\common\Arma 3\kart
16:30:27                                        Arma 3 Zeus |              curator |       true |             GAME DIR | 8f6f1df09c4707fa080e397861ca67fb1a7d1f09 |  fef5ffff | D:\SteamLibrary\steamapps\common\Arma 3\curator
16:30:27                                             Arma 3 |                   A3 |       true |            NOT FOUND |                                          |           | 
```
>please try to reproduce with only CBA and ACE on vanilla units

You have to disable all other mods besides CBA and ACE.

**Comment by 123aqw** [comment]
ok 1 second

**Comment by 123aqw** [comment]
can it be the map i am on to or ?

**Comment by commy2** [comment]
Maybe.

**Comment by 123aqw** [comment]
i did just redownload ace 3 and i forgot keys and userconfig lets hope it works then i will try the map i am playing on :)

**Comment by 123aqw** [comment]
here https://gist.github.com/123aqw/3d913fb1968095cb4e69

**Comment by commy2** [comment]
Does the interaction menu work with that?

**Comment by 123aqw** [comment]
nop

**Comment by commy2** [comment]
What key is it bound to?

**Comment by 123aqw** [comment]
left control + win and just win

**Comment by commy2** [comment]
And neither self menu nor interaction menu work?

**Comment by 123aqw** [comment]
nop

**Comment by commy2** [comment]
Are you in a savegame?

**Comment by 123aqw** [comment]
no i did go in editor and made a new save

**Comment by commy2** [comment]
Can you upload the RPT file of the current session? Where you opened the keybinding menu and tried to interact?
Maybe also try a different keybind

**Comment by 123aqw** [comment]
its works with another key ingame but why is my windows button now working ?

**Comment by commy2** [comment]
I have no idea to be honest.

**Comment by commy2** [comment]
Now try it with the different keybind and your usual modset

**Comment by 123aqw** [comment]
i cant set it back to defaul bcs my windows button dosent work online :( it works on desktop

**Comment by esteldunedain** [comment]
> i cant set it back to defaul bcs my windows button dosent work online :( it works on desktop

Some program my be capturing your keypresses. This is clearly not related to ACE.

**Comment by 123aqw** [comment]
yeah but it did work last week

**Comment by commy2** [comment]
Nothing we can I am afraid.
