### ISSUE TITLE
Stryker MGS with ACE3 FCS

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#3300]
ACE Version: 3.4.2 stable

**Mods:**
@CBA_A3
@ ace 
@ RHS: RU
@ RHS: USAF
@ AiATP
@ TFAR
@ CUP

**Description:**
https://youtu.be/62OFMD3_rIU

CUP Stryker with ACE FCS
turretInfoType="RscWeaponRangeZeroing";
discreteDistance[]={100,200,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000,2100,2200,2300,2400};
				discreteDistanceInitIndex=5;
				ace_fcs_enabled=1;
				ace_fcs_minDistance=200;
				ace_fcs_maxDistance=6000;
				ace_fcs_distanceInterval=5;

**Where did the issue occur:**
 Multiplayer, Editor, Single Player, Virtual Arsenal

**Comment by Kartaviy** [comment]
1:28 distance AUTO, WTF?

**Comment by bux578** [comment]
Could you explain a little bit more, please?

**Comment by Kartaviy** [comment]
You can translate from Russian?

**Comment by bux578** [comment]
No, I cannot.

**Comment by Kartaviy** [comment]
Ok, i try)))

**Comment by Kartaviy** [comment]
FCS ACE3 should block the line
discreteDistance[]={100,200,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000,2100,2200,2300,2400};

As a result, it adds to the measured distance.

**Comment by Kartaviy** [comment]
Calculation of the wrong turns

**Comment by commy2** [comment]
>Sparfell
>Heute um 10:24 Uhr
>@commy2 already implemented in last release

**Comment by commy2** [comment]
@Kartaviy This should already be part of the current version of the CUP Vehicles compat PBO. Are you using that file?
Otherwise please upload a RPT file.

**Comment by Kartaviy** [comment]
[](http://rghost.ru/72rHzCWvM)
.rpt file
No, i use only @CUP_Weapons_ACE_compat
I can not search CUP Vehicles compat PBO.They created it?

**Comment by commy2** [comment]
Yes. There are two compat files in the latest version of CUP according to the CUP devs. You have to use both.
Close?

**Comment by Kartaviy** [comment]
I can not find the link. Could you show it?

**Comment by commy2** [comment]
https://drive.google.com/file/d/0By04o_GxOry3TktRSGQ3c3JrZlU/view?pref=2&pli=1

**Comment by commy2** [comment]
Can also be found here: http://cup-arma3.org/downloads/cup-vehicles/
