### ISSUE TITLE
Function for restore basic (ideal) ace_medical stats of player (fully healed)

### ISSUE THREAD

**Issue by ivankrouglyi** [acemod/ACE3#3301]
Hello,

We are making DTAS-game mod (something like TDM) and after each round (when time limit has been reached or one of the team totally eliminated) all players should be teleported to the new location. Without ace3 mod i can easely heal all players with something like setdamage 0 or sethit 0, but with ace_medical each person have some injures, earplugs, unconsistous state, stunning, fatigue etc.

At now i have to kill every player after each round and then respawn them. That's pretty bad for ingame statistics and performance.

Is there any way to fully "heal" person, to make it (for ace3 medical system / other ace3 modules) "like new"?

Best regards

**Comment by PabstMirror** [comment]
I belive this should work:
```
//Medical:
[_unit] call ace_medical_fnc_init; 
_unit setDamage 0;

//Hearing:
ace_hearing_deafnessDV = 0;
_unit setVariable ["ACE_hasEarPlugsin", false, true];
```

We don't touch fatigue right now (just do `_unit setFatigue 0`)

**Comment by ivankrouglyi** [comment]
Thank you very much
