### ISSUE TITLE
Broken damage system: 5 bullets in each arm and leg and player is ok.

### ISSUE THREAD

**Issue by ghost** [acemod/ACE3#3302]
Didn't find same issue.

ACE3 Version: 3.4.2 stable
**Mods:**
* `@CBA_A3` (last one: 2.2.0.151130)
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
The damage system is totaly ruined. You need 3-6 bullets in one arm or leg to kill player or bot.
Head - 1 bullet,
Body ~ 2 bullets (first bullet can kill the person or drop it to uncosistious),
Arms\Legs - each body part can withstand 3-6 bullets hit (based on weapon damage).

**Steps to reproduce:**
* Create a new mission in editor;
* Place player's unit and bot behind player (both NATO with MX for example);
* Shoot 3-4 bullets in EACH arm and leg of one bot;
* He is injured, but he is ok. 
* Now hit it in chest armor. Ok, he is uncosistous. 
* Heal both hands and torso, then use morphine.
* Now bot ready to fight. Arms are yellow, legs are red.
* Shoot arms again. 3-5 bullets more for each hand and he is alive!
* Now make the single player mission. Test it. Problem is here.
* Now make it multiplayer and ask your friend to be the target. Same thing - realy strange damage system.

**Where did the issue occur?**
Multiplayer, Singleplayer, Editor. 

**RPT log file:**
* Editor: https://yadi.sk/d/hS-kZKBSoc9oB
* Singleplayer: https://yadi.sk/d/Xjt4eOFsocA3r
* Multiplayer: https://yadi.sk/d/N6rmpRloocJjj

**Comment by commy2** [comment]
Sounds reasonable to me from the description

**Comment by Glowbal** [comment]
This is intended behaviour.

What is the for you expected behaviour? It is possible to adjust the default.

**Comment by sargken** [comment]
I think when hit in the leg there is a random chance it hits an artery and it makes you bleed out really fast. Or if u get hit in the arm random time you cant use ur gun cause your arm is broke.

**Comment by ivankrouglyi** [comment]
Thanx for reply!

Please watch the video above
https://www.youtube.com/watch?v=y9jlPaFpaXQ&feature=youtu.be

> Sounds reasonable to me from the description
Player got something like 20 shots and he's alive and can fight. That's realy "by design"?

> What is the for you expected behaviour? It is possible to adjust the default.
Well, i think player should fall in unconstistous state after 2 bullets in ANY part of the body and should be dead after 3-4 shots (ofcourse that's just an example without taking into account different weapon damage, armor etc). It there any way to adjust it in that way? 2 bullets in "any part", not "each part" :)

**Comment by esteldunedain** [comment]
> I think when hit in the leg there is a random chance it hits an artery and it makes you bleed out really fast. Or if u get hit in the arm random time you cant use ur gun cause your arm is broke.

I think the issue is that wound don't incapacitate as you expect them too. e.g. if the unit is shot multiple times you expect it to fall down, drop their weapon and experience severe pain. I think better simulating all this could be both more realistic and better for gameplay (wounds being more serious but not more lethal)

**Comment by ivankrouglyi** [comment]
@Glowbal

> It is possible to adjust the default.

Could you please tell me how to do that? Do you mean ACE_Settings mechanism?

**Comment by Glowbal** [comment]
@ivankrouglyi 
```sqf
unit setvariable ["ace_medical_unitDamageThreshold", [1,1,1], true];
```
format: `[ HEAD, TORSO, LIMBS ]`
Default values: `[1, 1, 1 * 1.7]`

Note that I have used `1` here, but it really is the damage threshold setting value that is used here. So if you have that set to 2, the default would be `[2, 2, 3.4]`

**Comment by headedhorseman101** [comment]
Would it be possible to fix  the player in prone or in the prone stances (left-right, high-low), only letting him crawl at a reduced speed? I think this would be a good way to handle leg disabling after a certain amount of damage.

**Comment by ivankrouglyi** [comment]
@Glowbal thanx for reply!
I tried your reciep and unfortenutely that's not a good solution in my situation. 
If i set it to "2" player become more "armored" versus the default value ("1"). Even with damage threshold equal "0.1" in some cases player able to get more than 5 bullets in a leg and be alive. 

I think if to make it possible to override such parameters as "increase_chance_*", "change_fatal_*" and "1.7" param in ace_settings the ace3 damage system become more flexible.

**Comment by Glowbal** [comment]
Setting those values to 2 would indeed increase the armor. You can set it lower if you wish, ie 0.5 or any other number above 0.

**Comment by ivankrouglyi** [comment]
I tried. Increased _chance_ to kill person, not a handled dmg :( so some players die with 1 shot in leg, and other with 5 shots. I'll try to patch change_fatal and increase_chance* parameters (for test), but i think that's not enough and i need to increase handled dmg to limbs.

**Comment by Faithnall** [comment]
Can confirm this Issue.

In Game we need somtimes two Magazin to kill a single enemy AI.

The Workarround with for the Unit Init didn´t help much, when you use scripts or other Addons to Spawn enemy Units (like ALiVE)

Or did we use the wrong Medical System? Wich Medical System is needet to let them die normaly. We used the simple System.

**Comment by Jacques17** [comment]
Also noticed that AI was harder to overcome, so did some testing in the same way other member did. I personally found sort of a compromise by modifying  "player damage" and "AI damage" in the medical  settings module (Currently both to 0.1 for me). I will further refine this value through the different game sessions. As I do not often post here, I take this opportunity to thank the ACE3 team for their hard work and commitment, so thank you very much for all the fun that you bring through your A3 ACE3 mod.

**Comment by esteldunedain** [comment]
> thank the ACE3 team for their hard work and commitment, so thank you very much for all the fun that you bring through your A3 ACE3 mod.

You're welcome. Thank you very much for the compliments.

**Comment by malashin** [comment]
I think I found the reason the damage system is so unreliable.
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_determineIfFatal.sqf#L46

It uses a random chance to determine if the damage is fatal or not.

In my opinion this is flawed by design. Random chance should be considered only as an OR factor, not an AND one. Every bullet can kill you by hitting your vitals, but if 50.call hit you in the face there is not chance to survive. With current system you can take a lot of headshots and survive if you a lucky enough. If damage is above the threshold unit should die, if damage is below the threshold there is a random chance of him dying with every shot taken.

**Comment by ToxaBes** [comment]
Hm, why random used here?
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_determineIfFatal.sqf#L46
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_determineIfFatal.sqf#L52
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_determineIfFatal.sqf#L57


What about using total damage instead? I mean head + body + limb damage. 
If total damage > X (0.5 for example) -> unit is unconscious
If total damage > Y (1 for example) -> unit is dead

And god tier is let users to define X and Y with own values. Make sense?

**Comment by esteldunedain** [comment]
@malashin, I do agree with you. I'll examine this closely for the next release.

**Comment by malashin** [comment]
@esteldunedain, thank you.

Adding two options to Medical Settings would be really great:
1. Turn random factor on or off.
2. Count cumulative damage of all parts or each one independently.

**Comment by jonpas** [comment]
Tagging @esteldunedain due to https://github.com/acemod/ACE3/issues/3302#issuecomment-191750643

**Comment by DLEGION** [comment]
HI all !
its my first post...so i really wish to thanks ACE team for theyr great work ! 
T H A N K S !! 
your ACE mod should be standard ARMA3...seriously...BIS should hire you !

and now....to the "problem" : 
me too has this broken limbs damage system problem...its just unrealistic you need like 20 well placed bullets ( in the perfect middle of the upper leg, of any caliber) to incapacitate or kill someone.

i dont want to argue about this, but i really wish to be able to set it somewhere like : 
examples of well placed bullets (in the middle of an arm or leg, not glancing shots) 
that should  kill or incapacitate permanently:
9mm         2 to 4 bullets
5.56mm    1 to 2 bullets  (same for 7.62x39)
7.62x51    1 bullet (maybe, and i say maybe, 1 to 2 shots, depending by the bullet type 
(example mk316 always one shot, while a standard 7.62mm takes 2 shots ) 
.338 - .408 -.50 and bigger    1 bullet

...so...i'm absolutely not expert of coding, but i can open medical.pbo and work on its functions (like
handle_damage or determineIFfatal ecc...) if you please can explain me how change it to obtain this results, or at least disable this damage system, keeping enabled the medical treatment system, would be really appreciated !

THANK FOR YOUR WORK GUYS !   ACE3 ITS WHAT MAKES ARMA3 A GOOD GAME!

**Comment by DLEGION** [comment]
HI again !
i somehow menaged to restore proper damage settings, changing some values in "determineIFfatal" and "handleDamageBasic"....
but i still have a problem....i cannot determine how damage-kill and how damage-unconscious.
i wish to set permanently unconscious the people hit, so only an external "savior" (with morphine and epinephrine) can save the wounded guy.
...i tried getting a longer time in "handleDamageBasic" but the unconscious guy does not wake up even after treating !

thanks for any help !

**Comment by DLEGION** [comment]
i found a solution to make unites wake up when treated, and stay down forver if not (will write details in this post whan all will work, to not make confusion), but still a new problem....AI and players...dont lose blood !
they just need a morphine to overcome pain and they are ready to fight !

**Comment by DLEGION** [comment]
eh...i solved also this problem...but now...in advanced mode...the AI won't stay "in pain" !
i tried every setting...but AI still gets up after few seconds of unconsciousness !!
help plz :(

**Comment by DLEGION** [comment]
good news...problem seems SOLVED !
for future review and for other people, i write here my version of the " full solution ".
i'm no expert, i can't even read the code properly, so please be patient if i did mistakes, i'm still searching a better solution! 
here is it:

PROBLEM :
In default ACE 3.5.1 too many limbs shots are needed to kill or make unconscous (both players and AI). Need to fix this to realistic values, AND want to keep the medical system enabled AND want a wounded soldier go dead or unconscious, and if unconscious stay unconscious till someone help him

SOLUTION :

easy : just remove "MEDICAL.PBO" and its BIS-KEY from ACE addons
          (medical system will not work at all, but damage will be correct)

hard : modify 3 files of "MEDICAL.PBO" ...do to it:
set up editing tools following this instructios:
http://ace3mod.com/wiki/development/setting-up-the-development-environment.html
then open the files inside MEDICAL.PBO, open the folder "functions",inside it find and open :
"fnc_determineIfFatal.sqf"
in the very last line, in the part about limbs, delete this part of code to remove the random damage:
 && {(_chanceFatal >= random(1))}
then , few lines above it, always in limb part, change the value from 10 to 199 to actually make shots more deadly like in real life:
INCREASE_CHANGE_LIMB * (_damageBodyPart - _thresholdLimbs)) * 199);
some lines above it, change a value from 1.7 to 1.3 to adjust shots lethality, both for AI and player, so do it for both code lines :
GVAR(playerDamageThreshold), GVAR(playerDamageThreshold) * 1.3]];

then save it and exit. search a file named : "Fnc_handleDamage_Basic.sqf" and open it.
change a value from 1.3 to 3.3 to adjust damage to limbs : 
if ([_unit, _part, if (_part > 1) then {_newDamage * 3.3} else {_newDamage * 2}] 
then below it change the pain value from ( /4 ) to ( *14 ) to be in line with the new damage:
_pain = _pain + (_newDamage * 14) *
beware it only works for basic medical system
for advanced we have to do some other changes, in the file named: "Fnc_handleDamage_Advanced.sqf" . 
just delete everything after the line :
//if (GVAR(enableInternalBleeding)) then {
...and then paste this code after it (it will enable and modify the pain system so a bullet to the leg will make a soldier unconscious and more important will keep him unconscious and stop him from get up in few seconds; anyway a morphine will be enought to set him conscius again):


//    [_unit,_selectionName,_newDamage,_sourceOfDamage, _typeOfDamage] call FUNC(handleDamage_internalInjuries);
//};


if (alive _unit && {!(_unit getVariable ["ACE_isUnconscious", false])}) then {
            // If it reaches this, we can assume that the hit did not kill this unit, as this function is called 3 frames after the damage has been passed.
            if ([_unit, _part, if (_part > 1) then {_newDamage * 3.3} else {_newDamage * 2}] call FUNC(determineIfFatal)) then {
                [_unit, true, 0.5+random(10)] call FUNC(setUnconscious);
            };
        
        _pain = _unit getVariable [QGVAR(pain), 0];
        _pain = _pain + (_newDamage * 4) * (1 - (_unit getVariable [QGVAR(morphine), 0]));
        _unit setVariable [QGVAR(pain), _pain min 5, true];


};


......ok thanks for reading this, hope it helps someone with my same problems. 
one thing is sure...this has to be fixed ! 
THANKS & BYE !

**Comment by DLEGION** [comment]
hello guys !
i wish to thank you for your continuous support to this great mod (i love it so much that i cant play arma whitout it !) , and congratulations for 3.6.0 release ! yeah !

now...sorry to revive this thread, i justwish to help community out there...i noticed that 3.6.0 didnt fixed the "10 shot to each limb to kill " problem (at least for me its a problem). so i fixed it myself again, and i wish to share my discover with community:
the previous fix for 3.5.1 its still good,so lets take it as template, but some numbers have to be changed: 

in fnc_handleDamage_Basic.sqf new numbers in this lines:
--------------------------------------------------------------------------------------------------------------------
_pain = _pain + (_newDamage * 24) * (1 - (_unit getVariable [QGVAR(morphine), 0]));

if ([_unit, _part, if (_part > 1) then {_newDamage * 2} else {_newDamage * 2}] call FUNC(determineIfFatal)) then {
-----------------------------------------------------------------------------------------------------------------------

while in fnc_handleDamage_Advanced.sqf some numbers have to change in this lines:
--------------------------------------------------------------------------------------------------------------------------
if (alive _unit && {!(_unit getVariable ["ACE_isUnconscious", false])}) then {
            // If it reaches this, we can assume that the hit did not kill this unit, as this function is called 3 frames after the damage has been passed.
            if ([_unit, _part, if (_part > 1) then {_newDamage * 4.9} else {_newDamage * 2}] call FUNC(determineIfFatal)) then {
                [_unit, true, 0.5+random(10)] call FUNC(setUnconscious);
            };
        
        _pain = _unit getVariable [QGVAR(pain), 0];
        _pain = _pain + (_newDamage * 6) * (1 - (_unit getVariable [QGVAR(morphine), 0]));
        _unit setVariable [QGVAR(pain), _pain min 5, true];
------------------------------------------------------------------------------------------------------------------------

and finally in fnc_determineIfFatal.sqf :
---------------------------------------------------------------------------------------------------------------------------- 
if ([_unit] call EFUNC(common,IsPlayer)) then {
    _damageThreshold =_unit getVariable[QGVAR(unitDamageThreshold), [GVAR(playerDamageThreshold), GVAR(playerDamageThreshold), GVAR(playerDamageThreshold) * 1.1]];
} else {
    _damageThreshold =_unit getVariable[QGVAR(unitDamageThreshold), [GVAR(AIDamageThreshold), GVAR(AIDamageThreshold), GVAR(AIDamageThreshold) * 1.1]];
};
------------------------------------------------------------------------------------------------------------------------

hope it helps  (...and i hope in a fix too :-)  ) , bye !

**Comment by Glowbal** [comment]
Hi @DLEGION , I have edited your comment to use code blocks - that makes it a bit easier to read.

We are going to take another look at this for 3.7.0.

**Comment by Faithnall** [comment]
Hi DLEGION, is there any chance for a Download option for your changed PBO? So that i can test you pbo?

**Comment by DLEGION** [comment]
hello !  sure man ! tonight when i get home i will upload and post a link !
its even compatible with people that have standard version !

**Comment by DLEGION** [comment]
here it is the link of the edited .pbo:

http://www.filedropper.com/acemedical

same with embed code:
<a href=http://www.filedropper.com/acemedical><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >upload files free</a></div>

**Comment by Faithnall** [comment]
Thank you very much, we will test it :)

**Comment by DLEGION** [comment]
its a pleasure to help :)
let me know about it !

**Comment by Faithnall** [comment]
So after a few test. I can confirm, this works very well. At the moment for us the best way. I have to thank you all, for this great work.

**Comment by DLEGION** [comment]
thanks man !
if ya want beta-test my ACE3-ALiVE domination mission, you all invited ! contact me on steam (D-LEGION) or skype (d-legion) !

**Comment by DLEGION** [comment]
from february.....and you close the other topic as duplication...
you know i love you and your work guys....but the wait is a bit too long for a fix !

**Comment by commy2** [comment]
>its from february
issue creation date doesn't matter. look at the milestone.

**Comment by commy2** [comment]
Same as #3167
