### ISSUE TITLE
Only the driver dies when the vehicle is destroyed.

### ISSUE THREAD

**Issue by ivankrouglyi** [acemod/ACE3#3306]
Same to this report: https://github.com/acemod/ACE3/issues/3269 but described according to the rules.

ACE3 Version: 3.4.2 stable
**Mods:**
* @CBA_A3 (last one: 2.2.0.151130)
* @ace

**Placed ACE3 Modules:**
* None

**Description:**
 Only the driver dies when the vehicle is destroyed.

**Steps to reproduce:**
* Place helicopter, place few guys in it, 
* Let the pilot fly at a height of 200 m and then let helicopter swoops down and hit the ground. 
* Pilot is dead, other guys in vehicle is alive (and a bit injured). They can eject the vehicle or they are able to sit in a burning vehicle for a long time :helicopter: :fire: :smile: 

**Where did the issue occur?** 
Multiplayer, 
can't test it in singleplayer and editor easely (bot don't want to crash the helicopter) but i think it's also true for these modes.

RPT log file:
Multiplayer: https://yadi.sk/d/0BieuLlpogx2M
Multiplayer (zeus): https://yadi.sk/d/bzgGtP5uoh5fe

Video:
https://youtu.be/NVTiBcx4kCU

**Comment by ivankrouglyi** [comment]
In situation when pilot died first (for example he was killed by machinegunner during flight) and heli crashes without pilot - one (two) other players in vehicle will die but the rest of crew will be alive.

**Comment by kripto202** [comment]
can confirm that this is true, looks like vehicle crew is more likely to die from the crash while the passengers just take some damage.
