### ISSUE TITLE
Medical system broken on missions with custom revive scripts

### ISSUE THREAD

**Issue by Hiukuss** [acemod/ACE3#3307]
ACE3 Version: 3.4.2 stable

**Mods:**
* @CBA_A3
* @ACE (with RHS optionals added)
* @CUP Terrains - Core
* @CUP Terrains - Maps
* @CUP Units
* @CUP Vehicles
* @CUP Weapons
* @RHS AFRF
* @RHS USAF
* Shacktac Mods (client-side UI)

**Placed ACE3 Modules:**
Tried mission with/without ACE medical modules

**Description:**
Playing missions with a custom-revive system (such as Arma 3: Escape) results in the ACE medical system and a few others to malfunction. Such as: wheel replacement. Upon being injured, user cannot bandage/morphine/epinephrine to any effect. User remains hurt/damaged. Tested modset on other missions without a CRS and it works just fine. Modules have had no effect on this.

**Steps to reproduce:**
Launch mission with a custom-revive script
Injure yourself
Attempt to treat (to no avail)

**Where did the issue occur?**
Multiplayer, singleplayer untested

**RPT log file:**
None. Irrelevant as there is no crash, and none is being generated.

**Comment by jokoho48** [comment]
>  None. Irrelevant as there is no crash, and none is being generated.
no that is wrong RPT get created when you starting the game and save importent information that help us to debug this.
please attach one so we can help you there better thanks

**Comment by SzwedzikPL** [comment]
> Medical system broken on missions with **custom revive scripts**

If you are using custom revive scripts so why you run ace_medical? Only for me it sounds strange?

**Comment by esteldunedain** [comment]
>  Only for me it sounds strange?

Nah, I'm pretty sure our med sys is incompatible with CRS.

**Comment by Hiukuss** [comment]
The ACE revive portion is disabled. Also, I cannot find any RPT anywhere. Not in Documents, or the game folder.

Before the current patch that I am running, ACE was fully working with the missions we play that have custom revive scripts in use. The specific mission I am talking about [is this one](https://forums.bistudio.com/topic/180080-co10-escape/)

Thanks for the quick replies, but I can't reply as fast as you. :D

**Comment by jokoho48** [comment]
@Hiukuss the RPT files are saved under `%systemdrive%/users/%username%/appdata/local/arma 3`
and there you need to fine the RPT where from the time when the issue occule

**Comment by Hiukuss** [comment]
[Here you go.](http://pastebin.com/pZvmHUuK)

**Comment by Glowbal** [comment]
This sounds like the revive script is not compatible with ace medical (or visa versa). Likely due to the fact that we do not use the arma damage (setDamage etc) but use our own implementation. Revive scripts will have to be made compatible to deal with this.

If you or someone else needs help with that, please join us on Slack or create a suppor ticket here on github and we can assist.
