### ISSUE TITLE
Drop FPS in Vehicle

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#3309]
ACE3 Version: 3.4.2 stable
**Mods:**

@CBA_A3 (last one: 2.2.0.151130)
@ace
@ RHS
**Placed ACE3 Modules:**

ACE Medical
**Description:**
When use Slef interaction menu in vehicle  FPS DROP
https://youtu.be/II0S2kySCDc
**Where did the issue occur? **
Multiplayer

**Comment by esteldunedain** [comment]
That is a known issue. In vehicles with many passengers the interaction menu for all passengers is constructed at all times, which is quite slow when the advanced medsys is used. We did many round of optimization for this problem and it improved greatly, but it's still not perfect. I hope we can improve it further eventually.

**Comment by Glowbal** [comment]
Try the medical menu and disable 3d medical interaction. That should significantly improve your fps.

**Comment by PabstMirror** [comment]
Ref #1690

**Comment by esteldunedain** [comment]
Closing in favor a that
