### ISSUE TITLE
Huron fuel Container has no visible hose

### ISSUE THREAD

**Issue by Gaspasar** [acemod/ACE3#3310]
ACE3 Version: 3.4.2.0

**Mods:**
@CBA_A3
@ace

**Placed ACE3 Modules:**
none

**Description:**
The Huron fuel container (B_Slingload_01_Fuel_F) has no visible hose.
If u drop the invisible hose on the ground its hard to find it again :(

**Steps to reproduce:**
place a huron fuel container in the Editor and try to refuel a car.

**Where did the issue occur?**
Editor, SP

**RPT log file:**
not necessery

**Comment by jokoho48** [comment]
@GitHawk

**Comment by GitHawk** [comment]
Probably bis' fault

**Comment by PabstMirror** [comment]
Seems like `createRope` needs a real vehicle for the first param. So it returns nothing on the slingloads which are a reAmmoBox.

Not sure if there is a good way to fix this. Could possibly create a dummy vehicle and attach it to the container, but that will get messy.

**Comment by GitHawk** [comment]
Yes, that's what I mean. Is the same problem, that keeps me from making refuel work with fuel stations.

**Comment by jonpas** [comment]
On dev branch yesterday they enabled ropeCreate on static objects again.

**Comment by GitHawk** [comment]
Yay, then we may be able to fix that in 1.57+ and add fuel stations.

**Comment by Gaspasar** [comment]
with the Taru fuel Pod (Land_Pod_Heli_Transport_04_fuel_F) it is working correct.
isnt it also a static box?

**Comment by GitHawk** [comment]
I can't check inheritance now but it seems like the Taru fuel pod is a vehicle.

**Comment by jonpas** [comment]
It's a vehicle yes, you can sit in it.

**Comment by jonpas** [comment]
Pushing back as it is supposed to be fixed on dev-branch.

@GitHawk can you verify on dev-branch?

**Comment by GitHawk** [comment]
Not working on dev branch for me with `ropeCreate [fuel_container, [0,0,0], player, [0,0,0], 20];`

**Comment by john681611** [comment]
Possible Bodge solution:  ATV is small enough to fit inside the fuel tank section of the container. Using the ATV as a surrogate attachedTo the container (0,0,1 is sufficient) this does look correct.

**Comment by esteldunedain** [comment]
@john681611, the proposal was to create an invisible dummy instead. But the concensus was that it's better to wait and see if BIS fixes the issue instead,

**Comment by john681611** [comment]
Is BIS aware of the issue since the feedback site is down? pretty sure if you made a tweet or ace 3 backed feedback post it would get resolved.

**Comment by esteldunedain** [comment]
>  pretty sure if you made a tweet or ace 3 backed feedback post it would get resolved.

:laughing: 

@john681611, sorry to burst your bubble, but even when they had the issue tracker they were slow to say the least.

**Comment by PabstMirror** [comment]
Not working 1.58

**Comment by GitHawk** [comment]
:-(

**Comment by jonpas** [comment]
Did some experimentation with a dummy object and a fuel bladder. Dummy object has to be PhysX and simulation enabled, or `ropeCreate` won't work (if you disable simulation after `ropeCreate` then rope will simple be static, not simulated, not moving). That also means you can't lock the dummy object in place, positioning will never be where it should be. Apart from the positioning issue, it does work, but it's also hacky with a lot of `allowDamage false` to prevent both objects from exploding (or deflating in case of fuel bladder), which also means locality is an issue.

I think it's best to leave it like it is now without the rope, less aesthetics, more "it at least works".

**Comment by PabstMirror** [comment]
Should be fixed via #5151 thanks to @tbeswick96
