### ISSUE TITLE
Make.py issues on 1.56rc

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#3311]
**Game version**:1.56.134512
**Arma 3 tools version**: latest dev branch.
**Addon builder version**: 1.4.134332
**Mikero's tools version**: latest available on devHeaven as of 2016-02-11 (open source)
**Python version**: 3.5.1
**Windows version**: win10 64 bits / KB3135173 from 2016-02-09
**Commit used**: 0df06ea4c1fc50edd0ec9d5a55f7a2169c20e606

**issue**:

Make.py simply doesn't work, the output is either lacking subfolders or binarize.exe fails.

gist including the logs: https://gist.github.com/alganthe/07986e944cc097df0fdb
output logs of pboproject: https://www.dropbox.com/sh/90aup84482jaq17/AAA_LTr7mi9pv_DCPq3pgbJLa?dl=0

**Comment by ViperMaul** [comment]
@alganthe 
I am still at work so I haven't reviewed the logs yet...

You say it simply doesn't work. 
How do you *know* it doesn't work? What is the symptoms?
Give me a screen shot of an error message please. 
Why do you think binarize.exe might be failing?

I was hoping to see an error message in this issue report before I dug into the logs

**Comment by alganthe** [comment]
http://puu.sh/n5oSg/15aafbe377.png on pboproject
and
http://puu.sh/n5oY7/22e9228214.png on addonbuilder

**Comment by ViperMaul** [comment]
Yes that is helpful and saves time thanks. 
Hell let's just take a break from work for a quick minute. 
And yes enough information seems to be in the logs. It just helps to see your screen shots. Thanks!

What I do know is the following. Binarize has apparently changed significantly in 1.55 or later. 
And apparently won't work on 1.54. PboProject uses binarize. 
So the initial fingers points to that which has changed recently. BI Binarize. 

Source: https://forums.bistudio.com/topic/169362-tools-development-branch-changelog/page-4#entry2976243
 Tom_48_97 said: Be aware: Note: Data binarized with this version can only be used with Arma 3 1.55 and newer

It would be interesting if while being on 1.56RC, if we temporarily swapped the 1.56 binarize.exe with the 1.54 binarize.exe to see how that would change things. I don't know the dependencies of binarize but it would be a cool quick test. 

I will dig more and perhaps if warranted, I will touch base with MikeRo.

**Comment by ViperMaul** [comment]
@alganthe 
Thanks again for that screenshot. I was able to reproduce the problem using the following command:
`make yardage force`

**Comment by ViperMaul** [comment]
Well I got a slightly different error probably because I am using the paid version of the MikeRo Tools. 
@alganthe are you using the open-source version of ProProject or paid version?

**Comment by alganthe** [comment]
open source version.

**Comment by ViperMaul** [comment]
CORRECTION:
I had a typo in my command.. So far using the paid version of MikeRo tools I seem to have no problem with building yardage450

**Comment by alganthe** [comment]
Found the issue, (issues actually) some of my .paa files got corrupted, they were stored on an external hard drive originally which turned out to have a fuckton of fragmentation and reading errors.
