### ISSUE TITLE
XEH_preInit.sqf not found

### ISSUE THREAD

**Issue by Povers** [acemod/ACE3#3314]
**ACE3 Version**: 3.4.2.0

**Mods:**
@CBA_A3
@ace

**Placed ACE3 Modules**:
none

**Description:**
After unpbo and repack ace_interaction, i have an error " Warning Message: Script \z\ace\addons\interaction\XEH_preInit.sqf not found" and interaction don't work correctly.
**
Steps to reproduce:**
unpbo and repack ace_interaction.pbo

**Where did the issue occur?**
Editor and MP

**RPT log file:**
unnecessary

**Comment by SzwedzikPL** [comment]
I have no problems with that. Looks like you did not binarized pbo correctly.

If addon worked before unpacking and you unpbo it and packed again and then not worked why do you report it like an issue on ACE? I can't understand that logic.

**Comment by Glowbal** [comment]
Hi @Povers 

This sounds like an issue with the prefix while repacking the pbo. How did you repack it?

**Comment by commy2** [comment]
Add `*.sqf` to files to cop directly.

**Comment by Povers** [comment]
Sorry, my question is ridiculous. 
Thanks everyone
