### ISSUE TITLE
Question/Feature Request: Scripted injuries

### ISSUE THREAD

**Issue by RSpeekenbrink** [acemod/ACE3#3315]
Is it possible to script injuries on an AI for Medical Training for example, if so, what scripting commands are used for that?

If not, is it possible to get that in the Ace 3 mod? It would be a great way for learning how to work with the medical system.

-RSpeekenbrink

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_addDamageToUnit.sqf
```
 * Example:
 * [player, 0.8, "leg_r", "bullet"] call ace_medical_fnc_addDamageToUnit
 * [cursorTarget, 1, "body", "stab"] call ace_medical_fnc_addDamageToUnit
```

Can see damage types here: https://github.com/acemod/ACE3/blob/master/addons/medical/ACE_Medical_Treatments.hpp#L631

**Comment by RSpeekenbrink** [comment]
Thank you <3
