### ISSUE TITLE
Mines/Explosives orientation resets when JIP or reconnect

### ISSUE THREAD

**Issue by Jansgi** [acemod/ACE3#3317]
ACE3 Version: 3.4.2

**Mods:**
* `@CBA_A3`
* `@ace3`

**Placed ACE3 Modules:**
* None

**Description:**
* Placed mines/explosives orientation resets to zero when joining as JIP or reconnecting

**Steps to reproduce:**
* Place mine/explosive -> JIP or disconnect and reconnect back -> mine orientation reset

**Where did the issue occur?**
* Dedicated server

**RPT log file:**
* -

**Comment by esteldunedain** [comment]
Mine orientation is set locally on each machine from an event launched after the mine placement. Those are not JIP compatible. 

Seems like an ideal use case for a `syncedEvent`, although they are only minimally used in ACE (only medical litter). @commy2, @PabstMirror, do you agree?

**Comment by commy2** [comment]
Are these CfgVehicles or CfgAmmo ? If they are CfgAmmo, game logic / variable container attached to them?

**Comment by PabstMirror** [comment]
CfgAmmo, nothing attached to them, but they can be attached to a vehicle.

**Comment by commy2** [comment]
I don't think one event for every mine is a good idea. I'd prefer one postInit event that goes through an array that is publicVariabled from the server with the following format:
`[[mine1, dirMine1], [mine2, dirMine2], ..., [mineN, dirMineN]]`
This would require the object reference to be synched correctly, which IDK if that works for mines.

**Comment by commy2** [comment]
Every time the server adds a mine to the array, it could check if the old ones are still alive and filter them out if they already exploded or were removed (objNull)

**Comment by esteldunedain** [comment]
> his would require the object reference to be synched correctly

I believe they are.

> I don't think one event for every mine is a good idea. I'd prefer one postInit event that goes through an array that is publicVariabled from the server with the following format:

Yeah, that'd work too.

> Every time the server adds a mine to the array, it could check if the old ones are still alive and filter them out if they already exploded or were removed (objNull)

Yup
