### ISSUE TITLE
Incorrect ballistics at AS Val of RHS. 

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#3320]
ACE3 Version: 3.4.2

**Mods:** 
* '@CBA_A3' 
* '@ace'
* '@RHSAFRF' 
* '@RHSUSAF'

**Placed ACE3 Modules:**
* *Advanced Ballistics*
* *Wind Deflection*
* *Weather*

**Description:** 
* The sight mark and hits not converge at AS Val rifle with PSO-1M2-1 sight. 
   https://youtu.be/65_oe42xzmw

**RPT log file:**

* [ArmaReport_Log_20160215T214054_XXXXXXXXX.zip](https://github.com/acemod/ACE3/files/131488/ArmaReport_Log_20160215T214054_XXXXXXXXX.zip)

**Comment by esteldunedain** [comment]
Thanks for the report. Please edit the ticket according to [the instructions here](http://ace3mod.com/wiki/user/how-to-report-an-issue.html).

Also please provide an RPT log of the session and screenshots showing the problem.

**Comment by GalNa** [comment]
Instead screenshot video showing the target, standing at 100 meters from the shooter. Bullets fly far above the aiming mark. 
https://youtu.be/I_xROUeWQis

**Comment by esteldunedain** [comment]
I need the RPT log to confim if you are running the compatibility pbo for RHS.

**Comment by GalNa** [comment]
The video captured on this server [http://www.gametracker.com/server_info/109.120.135.75:2604/](url) 
The compatibility pbo for RHS was running. 
https://youtu.be/65_oe42xzmw

**Comment by jokoho48** [comment]
@esteldunedain the AS Val is not configured for AB if i remeber right

**Comment by esteldunedain** [comment]
> @esteldunedain the AS Val is not configured for AB if i remeber right

Yeah, that's probably true. 

The PSO scope relies on Arma native adjustment for range corrections. But advanced ballistics might modify the initial velocity of the shot, making vanilla calculation no longer accurate. Changing the initial velocity of the AS Val in the compat patch to better match the real AB velocity would minimize the issue.

Another way to reliably fix this would be implementing the range adjustment in ACE and deprecating vanilla adjusting altogether. This isn't that hard anyway, given that ace_fcs already has an extension to do the heavy lifting. However, it would require removing native adjustment for all weapons, which might not be feasable.

**Comment by VKing6** [comment]
Cannot reproduce. The range option on the AS Val/PSO-1M2-1 appear to work properly. 
Tested using the VDV EMR Desert AS Val Marksman with nothing added to the mission. Also tested SP-6 ammunition without any issues.

Does the ranging work as expected with the PSO-1M2 scope, or with iron sights?
