### ISSUE TITLE
Chinook interaction menu not working

### ISSUE THREAD

**Issue by kamkill01011** [acemod/ACE3#3321]
ACE3 Version: 3.4.2
stable

**Mods:**
* `@CBA_A3`
* `@ace`
* `@TFAR`
* `@Ares`

**Placed ACE3 Modules:**
* None

**Description:**
* When trying to interact with the Chinook by pressing the interaction key nothing show up no matter if you are inside or outside, but the Self interaction works fine (when inside). 

**Steps to reproduce:**
* Place a Chinook with people inside and try to intercat with them while being inside or outside the Chinook. 

**Where did the issue occur?**
* Multiplayer

**Comment by PabstMirror** [comment]
Ref https://github.com/CBATeam/CBA_A3/pull/228

Will be fixed in next CBA Release. For now whatyou want to do is add the `cba_enable_auto_xeh.pbo` from CBA optionals folder to addons folder.
