### ISSUE TITLE
Fuel nozzle remains when removing vehicle

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#3327]
ACE3 3.4.2 Stable

**Mods:**
* @CBA_A3
* @ace
* @tfar
* @bwa3
* @sobmod
* @bw_isaf

**Description:**
* When deleting both the refueling vehicle and the vehicle that is getting refueled as zeus, the fuel nozzle remains on the ground and doesn't get removed.

![image](https://cloud.githubusercontent.com/assets/1235520/13089947/7175a906-d4f3-11e5-87b5-615b4beafd6f.png)

![image](https://cloud.githubusercontent.com/assets/1235520/13089958/79c18440-d4f3-11e5-851e-7eaaf609be62.png)

**Steps to reproduce:**
* Be Zeus
* Spawn a e.g. HEMTT Fuel and a second vehicle
* Edit the second vehicle and empty the fuel tank
* Connect the second vehicle using the HEMTT's fuel nozzle
* Start the refueling process
* Delete both vehicles

**Where did the issue occur?**
* Multiplayer

**RPT log file:**
https://gist.github.com/bux578/a91760d1ef6e09c3b345

**Comment by bux578** [comment]
Tagging @GitHawk

**Comment by GitHawk** [comment]
I can use the PFH players get while carrying the nozzle, but there are still loop holes.

If the player interacting with the fuel truck disconnects, no one else is running that PFH. So the Zeus can delete the vehicle and the nozzle will remain.

Anyone having a better idea? I'd love to have a pre-delete event, in which I could call fnc_reset on the fuel truck.

**Comment by esteldunedain** [comment]
> If the player interacting with the fuel truck disconnects

On the server:
```sqf
addMissionEventHandler ["HandleDisconnect", {
    params ["_disconnectedPlayer"];
    // If the player was refuelling, cleanup
}];
```

Of course you'd need to set some public variables on the refuelling unit indicating to the server what should be cleanedup.
