### ISSUE TITLE
Neither Interaction nor Self Interaction menu working

### ISSUE THREAD

**Issue by Krimzon225** [acemod/ACE3#3328]
ACE3 Version: 3.4.2

Mods:
`@CBA_A3`
`@ace`

Placed ACE3 Modules:

Varied, sometimes none, sometimes multiple, but missions with ACE modules involved are not made by me, so I don't know which modules have infact been places.

Description:

It's quite simply that nothing happens when the keys are pressed. I've reinstalled ACE3, I've reinstalled CBA, I've tried it with no mods but ACE and CBA, still doesn't work.

Steps to reproduce:

Start/Join any mission, press Interaction Key.

Where did the issue occur?

The issue is consistent throughout Singleplayer Campaign, Singleplayer Scenarios, Locally Hosted Multiplayer Servers, and Servers hosted by others.

RPT log file:
http://pastebin.com/cvDpB2zq

**Comment by esteldunedain** [comment]
Did you try rebinding the keys to some other button? The other day we received a similar reporte and it ended up being the Win key wasn't working on Arma for that person.

**Comment by TheConen** [comment]
Have you tried creating a new profile? It was the solution for a possibly related bug, @commy2 might know more about that.

**Comment by Krimzon225** [comment]
How exactly do I rebind the keys? It's been a long time since I've tinkered with a mod's binds.

**Comment by esteldunedain** [comment]
On the vanilla control bing screen there's a button calles "Addon Keybinds" or something like that.

**Comment by PabstMirror** [comment]
Bring up the vanilla controls settings and then hit "configure addons" button at the bottom.
Then under "ACE3 Common" look for the 2 interaction keybinds.

There is also a chance your keybinds are corrupted, so you could try doing
```
profileNamespace setVariable ["cba_keybinding_registrynew", nil]; saveProfileNamespace;
```
in the editor, but this will reset all CBA keybinds.

**Comment by Krimzon225** [comment]
Well, thanks guys, it's working now that I've rebound it... But that raises another question, why is my windows key suddenly not working? When I try to bind a key to it, it says "Unknown Code 91"... Any ideas?

**Comment by PabstMirror** [comment]
Some keyboards do weird things with the windows key.
I think some gaming keyboards might have switches to change the behaviour, and keyboard software might be able to do the same.

**Comment by PabstMirror** [comment]
If you still can't get it working, it's more of an issue for CBA https://github.com/CBATeam/CBA_A3
