### ISSUE TITLE
RAH-66 Commanche DAGR terrible accuracy

### ISSUE THREAD

**Issue by justbeagamer** [acemod/ACE3#3329]
With the helicopter facing the target, at around 1.5 to 2 km the dagr missiles often miss the target by 50+ meters. I have tested from various altitudes and angles without success.

**Comment by GitHawk** [comment]
With ace_laser not being fully implemented, I made PR #3305 to reenable vanilla laser locking. That will fix the accuracy issues.

**Comment by esteldunedain** [comment]
Closing this in favor of #3305.
