### ISSUE TITLE
Battleye Blocking Fresh DLLs

### ISSUE THREAD

**Issue by looterz** [acemod/ACE3#3332]
So, I'm working on an important update to the ace_clipboard extension, and after compiling for "Release" under VS2015 Battleye has started blocking my version of ace_clipboard. Is there a standard compiling process or mode I need to work with in order to get around BEService? 

You can see the source [here](https://github.com/looterz/ACE3/blob/c4996/extensions/clipboard/ace_clipboard.cpp). It's definitely not the servers being down, the DLLs from the last stable release load fine. I have also reinstalled BE, and followed the steps on the wiki.

**Comment by esteldunedain** [comment]
For testing, I'd recommend not to enable Battleye. I'm not aware of any other special procedure to prevent it blocking your extensions.

Maybe @Glowbal can offer a better perspective.

**Comment by looterz** [comment]
I suppose it could be an issue with my VS2015 compiler setup, I do notice thousands of warnings during the compilation of ACE's modules, mostly related to standard library stuff though not the modules themselves. I may try getting CMake to spit out a clang-able setup just as an alternative to msvc for testing.

**Comment by esteldunedain** [comment]
>  I do notice thousands of warnings during the compilation of ACE's modules

Yeah, that's because CMAKE is setting the /Wall flag. Changing it manually to /W3 really makes things easier. I don't think that's related to the issue though.

**Comment by jonpas** [comment]
You just have to disable BattlEye, there is also no point running it when testing.
