### ISSUE TITLE
Module has wrong values when placed with 3D Editor

### ISSUE THREAD

**Issue by Gilatar** [acemod/ACE3#3339]
**ACE3 Version:**
3.4.2.0

**Mods:**
@CBA_A3 (tested with v2.2.0 and v2.3.0, same results)
@ACE

**Description:**
There is some odd behavior with the module values in the 2D editor versus the 3D editor, specifically with the ACE Medical -> Medical Settings Module. 

[2D Editor Default Module Settings](http://puu.sh/ncLG2/d7078ddf02.png)
[3D Editor Default Module Settings](http://puu.sh/ncLbJ/65875a418d.png)

The 2D editor modules are fine and won't cause any issues, the 3D editor-placed ones, however, seem to give the wrong values for some of the settings, regardless if you make changes to the setting or not.

Looking at the mission.sqm - a 2D editor-placed [module with AI unconsciousness turned off has a value of 0](http://puu.sh/ncMa0/c8e199d486.png). A 3D editor-placed [module with AI unconsciousness turned off has a value of -1.](http://puu.sh/ncMxR/fb59a31aec.png)

Also causes some .RPT outputs listed below.

**Steps to reproduce:**
- Make a fresh mission in 3D editor
- Place player
- Place medical module (set AI unconsciousness to disabled)
- Place enemy group
- Preview
- Shoot enemies and they will still go unconscious
- Check RPT for errors below

**Where did the issue occur?**
3D Editor

**.RPT:**
http://pastebin.com/2MCdtRiY

**Excerpt from RPT:**
19:42:33 [ACE] (common) WARNING: Setting [ace_medical_medicSetting] out of bounds -1 (values[] count is 3)(
19:42:33 [ACE] (common) WARNING: Setting [ace_medical_enableUnconsciousnessAI] out of bounds -1 (values[] count is 3)(

**Comment by PabstMirror** [comment]
`_logic getVariable "medicSetting"` = -1
Unbined sqm:
```
class Attribute13 {
    property="ACE_moduleMedicalSettings_medicSetting";
    expression="_this setVariable ['medicSetting',_value,true];";
    class Value {
        class data {
            class type {
                type[]= {
                    "SCALAR"
                };
            };
            value=-1;
        };
    };
};
```

This only happens for the disabled setting, basic gets 1 and adv gets 2 as it should.

**Comment by PabstMirror** [comment]
http://feedback.arma3.com/view.php?id=28031
Reproduced in vanilla, seems like a fairly critical issue for our modules.

We might want to use a workarround like saving value as a string and parsing to number which seems to work.

**Comment by PabstMirror** [comment]
On master if you just open the ace attributes tab on a unit and close it, it will leave this in sqm:
```
property="ace_isMedic";
expression="_this setVariable [""ace_medical_medicClass"", _value];";
class Value {
    class data {
        value=-1;
```
and in game
`player getVariable "ace_medical_medicClass";` = -1

This may not reset on bis patch! This is critical and we need to think about holding off on 3den attributes as it may lead to people creating missions that will be permanently broken.

**Comment by esteldunedain** [comment]
I agree with @PabstMirror. We should comment out all traces of 3den attributes until BIS fix this, or we risk corrupting missions persistently.

Given that the BIS bug tracker is still offline I don't think we should release 3.5.0 before removing the attributes.

**Comment by esteldunedain** [comment]
Will be fixed in #3393

**Comment by PabstMirror** [comment]
#3393 only fixes the 3den attributes
The modules are still effected
ref https://forums.bistudio.com/topic/188363-3den-combo-box-is-wrong-when-value-0/
We could "patch" it's configs ourselves, but that might break once they actually fix it...

**Comment by PabstMirror** [comment]
This is fixed in dev branch, hopefully we get an arma hotfix sooner than later.

**Comment by kripto202** [comment]
there was an update today, how is it working now?

**Comment by PabstMirror** [comment]
New modules placed will be perfect.
Opening a module with the bad `-1` seems to set it to the 1st index (instead of 0) and will resave as `1`
Opening a mission and resaving without opening the module and it will continue to save `-1`.

So fixed, but mission makers should double check their modules for current missions.

**Comment by kripto202** [comment]
> So fixed, but mission makers should double check their modules for current missions.

noted. is there going to be a fix soon so we don't have to do this?

**Comment by jonpas** [comment]
No, there is not much that can be done.
