### ISSUE TITLE
ace 3 error in 3D editor + 3D editor freezes

### ISSUE THREAD

**Issue by 123aqw** [acemod/ACE3#3340]
switching back from mission testing freezes camera-view
Description	ervery time I test the Misson and switch back to eden-editor the 3D Cam View is locked... map(2d) editing is working...

after restarting eden-editor, everything is working again, until I start testing the mission... same problem again.

restatirn 3D editor works to get it fixed

RPT file
https://gist.github.com/123aqw/7fcae869ad699715b077

soo is it the mod i am using causing it or is it the 3D editor ?

**Comment by looterz** [comment]
I haven't been able to reproduce this on my end, but skimming through your RPT I did notice
```
FunnyCoolStuff.Catalina\description.ext, line 1: '.auther': Missing ';' at the end of line
FunnyCoolStuff.Catalina\description.ext, line 2: '.OnLoadName': Missing ';' at the end of line
FunnyCoolStuff.Catalina\description.ext, line 3: '.OnLoadMission': Missing ';' at the end of line
FunnyCoolStuff.Catalina\description.ext, line 5: '.OnLoadIntro': Missing ';' at the end of line
```

But I doubt that would freeze 3den's camera. So far the only thing freezing the cam for me is trying to use the arsenal. Does it happen on every map or just Catalina?

**Comment by 123aqw** [comment]
every map :( did check up 3d editor freezing thing and it was told that its ace and cbas fault


It seems you are using mods.

I can reproduce this problem with mods (CBA 2.2.0, ACE 3.4.0).

As I can't reproduce this behavior without mods, I guess this is not the right place to report the issue.

http://feedback.arma3.com/view.php?id=26136

**Comment by esteldunedain** [comment]
@123aqw are you using the 3.4.2 version of ACE? In that case please update to current master or wait for our next release (coming soon).

**Comment by commy2** [comment]
>Advanced Combat Environment 3.4.2 

If this happens with only CBA and ACE 3 , then please upload a RPT file of that.

**Comment by esteldunedain** [comment]
> Advanced Combat Environment 3.4.2

@commy2, current master shows the same afaik

**Comment by 123aqw** [comment]
ya but us there an own RPT file for ace ? 

RPT https://gist.github.com/123aqw/d373cccd9778a8039a6a

**Comment by gienkov** [comment]
All our Mission Makers do repro this.

**Comment by 123aqw** [comment]
what u mean with repro ?

**Comment by 123aqw** [comment]
i did try with just ace and cba and eden editor worked well i am confused O_o

https://gist.github.com/123aqw/3cdcfa6b194b144b361e
