### ISSUE TITLE
Player cannot repair vehicle with engine turned ON

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#3348]
Arma 3 Version:** `1.56`
(Stable)

ACE3 Version:** `3.4.2`
(Stable)*

**Mods:**
* @CBA_A3
* @ace
*  RHS Escalation

**Description:**
When engine of vehicle is turned on, you cannot repair any its part. Its very annoying, beacuse In very "realistic" arma world, player is very often forced to get out of tank when it have broken track (only on track!) straigt under enemy fire, but thats the other story, when player is forced out, there is action used "jump out" instead of "get out", so engine is still runing and player can only .... die, beacuse he cannot get back to vehicle (when he is not commander of group), cannot repair tank, and is on open field with his PDW against snipers, tanks, choppers.. 

**Steps to reproduce:**
Get a tank platon, set yourself as commander of one tank, but not group leader. Get damage on your tank to be forced out of vehicle. Now you will not be able to repair it.

**Where did the issue occur?**
Singleplayer

**Comment by esteldunedain** [comment]
> player is very often forced to get out of tank when it have broken track (only on track!) straigt under enemy fire

I don't think doing that is or should ever be a good idea.

**Comment by PabstMirror** [comment]
I actually agree with this. It's unintuitive that you can't do something like change a wheel with the engine running.

Perhaps we can just force engine off when starting repair.

**Comment by esteldunedain** [comment]
> I actually agree with this.

Yes, I'm not against repairing with the engine on either. It's just that's silly pretending to do it under firing.

**Comment by vlad8011** [comment]
Well, crew of vehicle could make covering fire, while repairing man could be more safe then

**Comment by headedhorseman101** [comment]
>Take in account, you cant turn off engine with repairing every part - for example while repairing track

You don't have to. If you use "eject" instead of "get out", the engine will not shut off.

**Comment by headedhorseman101** [comment]
>for example while repairing track, there is very useful using "gas pedal" on tank to get track straight >when repairing damaged thread and joining them together.

While that is an interesting way of realigning the track, it would be very difficult to model something like that. It would be easier to get out and pop smoke and begin repairing. It sucks, but I don't believe you can reach the track from the inside of a tank very well.

**Comment by headedhorseman101** [comment]
I agree with @vlad8011. It should be automatically turned off when you are forced out of the vehicle.

**Comment by vlad8011** [comment]
Yes but if engine is turned ON you cant repair anything (for now)

**Comment by Khaosmatic** [comment]
Could it be a module option in the Repair Module?

**Comment by vlad8011** [comment]
Nice, but auto behavior would be better, for players playing workshop's missions for example, or campaigns.
