### ISSUE TITLE
Player is forced out of vehicle when track become damaged

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#3349]
**Arma 3 Version:** `1.56`
Stable

**ACE3 Version:** `3.4.2`
I was wondering where to write this but i think its good place beacuse its a bug report, and request in one ticket.

Most annoying problem in arma armored warfare is stupid order to bail out when track become damaged. There is no logical explaination, what developers had on their minds by putting such stupid behavior in the game. Imagine situation (as i meet every day in A3) - tank is driving on the AT mine, but its well protected so its track is on "status red", but its still operational, meanwhile all around is heavy firefights with small arms and lot of infantry, tank crew could easly defend himself from the tank weapons, but instead of that, they treat track damage so serious, that they decide to jump out to die (problem of damaged track overgrowed them, i think) and they instantly die by small arms. Story over. Now tell me, is this normal in milsim? Why after months after i reported it, they act there is no problem? Why ticket on their feedback is still "new"?  I have only hope in you, beacuse you can make miracles in this game. Please, try to make realistic crew behavior.... add allowcrewinimmobile to default in all vehicles or something.... After area woul be clear (no enemies in sight) one crewman (driver) could disembark to repair vehicle. That would be finest option in armored warfare. Player is able to re-edit all missions he download, but where is joy from playing then? He will edit more than play. And steam workshop will redownload file when it will be changed. Did i mentioned campaigns?

**Comment by esteldunedain** [comment]
Thak you for your report. The issue is only a problem with AI crews, and has nothing to do with ACE. If anything this should be a request for BI.

As for feature requests for ACE, please use #414. However, I really don't see us ever dealing with this, given that our focus is currently on PvP and Coop gameplay and we are not an AI enhancement mod.

**Comment by PabstMirror** [comment]
```
class Extended_InitPost_EventHandlers {
  class Tank {
    class tankIsNowBunker { init = "(_this select 0) allowCrewInImmobile true;"; };
  };
};
```

You could stick this into a mission description.ext
or make a simple mod of it and it should fix the problem.

**Comment by vlad8011** [comment]
Thanks for this, i would very love to make addon as you write, but its out of my experience... I'm gonna try at least tomorrow, thanks again.

**Comment by vlad8011** [comment]
Hi could you check why it isnt working? I made it as addon, but crew still disembark. If you could make corrections i would learn 100 x times faster how to make addons like this. I was searching something on google but couldnt find anything good.
Here is mod version of this;

https://mega.nz/#!VIEwCQbZ
But it isnt working as i writed above, check this if you can..... please, its really matter to me.

**Comment by esteldunedain** [comment]
> Here is mod version of this;
> https://mega.nz/#!VIEwCQbZ

Your download link is password protected.

**Comment by vlad8011** [comment]
Sorry, try this one :

https://mega.nz/#!VIEwCQbZ!S8x5RUS6I2fhlSSu3pJJ_IbqWWOsTR2HOKct3QIr8Ek

**Comment by esteldunedain** [comment]
The code @PabstMirror mentioned should be pasted directly in `config.cpp`, not in a function.

**Comment by vlad8011** [comment]
ouch thanks, i'll try :)

**Comment by esteldunedain** [comment]
I'm glad to hear it @vlad8011. Enjoy your improved AI.

**Comment by vlad8011** [comment]
Hey guys, this addon was given little upgrade, so now crew of tank (driver) will repair broken component if there will be no enemy nearby. 
ALMOST as i planned, i think you could check the code and apply it to ACE, as it improve realism very much :
http://steamcommunity.com/sharedfiles/filedetails/?id=632781728

The only problem remaining is the wrecks are getting back to non destroyed models for few seconds after destroy, but with your knowledge i think its not a big problem.

**Comment by esteldunedain** [comment]
Very nice @vlad8011. I'm not sure this is within the ACE scope, but I think many people would enjoy it a sepparate addon like you did.

If you upload the source code anywhere I could take a quick look to see if I can understand why you're having that issue with the model on destruction.

**Comment by vlad8011** [comment]
0 = [] spawn {
      if (!isServer) exitWith {};
      {
       (vehicle _x)  addEventHandler ["hit",{
        _veh = _this select 0;
        _d = driver _veh;
        if (_d != _veh && alive _d && !(_veh iskindof "plane")) then {
          _d setCombatMode "COMBAT";
          _veh allowCrewInImmobile true;
          _d addBackpackGlobal "B_tacticalPack_mcamo";
          _d additemtobackpack "toolKit";
          [_d,_veh] spawn {
            _d = _this select 0;
            _veh = _this select 1;
            waitUntil {(_d findNearestEnemy _d) distance _d > 300};
            doGetOut _d;
            waitUntil {!(_d in _veh)};
            sleep 1;
            _d setVectorDir (getpos _d vectorFromTo getpos _veh);
            _d playMoveNow "Acts_carFixingWheel";
            sleep 10;
            _d switchMove "";
            _veh setDamage 0;                                    <<<<<<<<<Its gonna be somewhere here
         };
       }}];
     } foreach allUnits
    };


I already tried to add if alive _veh but it stop driver before disembarking.

**Comment by esteldunedain** [comment]
Your code is not very reliable atm, cause:

- you are running it independently every time a new hit happens. If the tank is shot many times (e.g. by a machine gun), your code will spawn a million thread degrading performance and make the driver go crazy when the tank once the enemy retreats. This thread may also collapse the arma scheduler and end up running a long time after the vehicle is repaired, dead, etc.

- You make the thread wait and then apply the next step (e..g `veh setDamage 0) without checking if the conditions still apply (e.g. the driver could die while reparing the vehicle, the vehicle is repaired anyway)

**Comment by esteldunedain** [comment]
Hold on, I'll post a couple of quick fixes.

**Comment by esteldunedain** [comment]
```sqf
0 = [] spawn {
  if (!isServer) exitWith {};
  {

   (vehicle _x)  addEventHandler ["hit",{
    _veh = _this select 0;
    _d = driver _veh;

    // Check if the vehicle is already marked for repair so it's done only once after each battle
    if (_veh getVariable ["willBeRepaired", false]) exitWith {};
    _veh setVariable ["willBeRepaired", true];

    if (_d != _veh && alive _d && !(_veh iskindof "plane")) then {
      _d setCombatMode "COMBAT";
      _veh allowCrewInImmobile true;
      _d addBackpackGlobal "B_tacticalPack_mcamo";
      _d additemtobackpack "toolKit";

      // This spawn now only happens once for each battle
      [_d,_veh] spawn {
        _d = _this select 0;
        _veh = _this select 1;
        waitUntil {(_d findNearestEnemy _d) distance _d > 300};
        doGetOut _d;
        waitUntil {!(_d in _veh)};
        sleep 1;
        _d setVectorDir (getpos _d vectorFromTo getpos _veh);
        _d playMoveNow "Acts_carFixingWheel";
        sleep 10;
        _d switchMove "";

        if (alive _d) then {
          _veh setDamage 0;
          _veh setVariable ["willBeRepaired", false];
        };
     };
   }}];
 } foreach allUnits
};
```

**Comment by vlad8011** [comment]
Thanks for fast reply, i'll test it

**Comment by commy2** [comment]
lol :angel:

**Comment by esteldunedain** [comment]
:angel::+1:

**Comment by vlad8011** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=632781728

**Comment by vlad8011** [comment]
Few days passed, people really liked the mod. I'm thinking about adding userconfig folder, but dont know how to do that, what actually this sqf file inside userconfig file should contain? I was googling this a little but cant find how to create it.

**Comment by Glowbal** [comment]
If at all possible, avoid the use of a userconfig file. A serverconfig like ACE has (optionally) is about as far as I'd go. And avoid using raw .sqf but stick to configuration (ie .hpp) only. It's both an usability and a security concern.

If you are interested in it however, join us on our Slack channel and drop me a message. I'd gladly help you out.
http://slackin.ace3mod.com/

**Comment by vlad8011** [comment]
I meet little problem. Driver disembark even if tracks are just "touched". Is there any way to get him disembark is damage of some part will be > 50% ?

**Comment by esteldunedain** [comment]
Yes, although in order to keep it simple I recommend doing that based on the overall vehicle damage instead:

```sqf
0 = [] spawn {
  if (!isServer) exitWith {};
  {

   (vehicle _x)  addEventHandler ["hit",{
    _veh = _this select 0;
    _d = driver _veh;
    // Exit if the vehicle is not damaged enough
    if (damage _veh < 0.1) exitWith {};
    ...
```

**Comment by vlad8011** [comment]
Thank you very much, as allways your the best ! :)

**Comment by vlad8011** [comment]
err, its not working,....... i puttet it like this (as you showed me - no reaction 
''' (vehicle _x)  addEventHandler ["hit",{
    _veh = _this select 0;
    _d = driver _veh;

    if (damage _veh < 0.1) exitWith {};
    _veh setVariable ["willBeRepaired", true];

    if (_d != _veh && alive _d && !(_veh iskindof "plane")) then {
      _d setCombatMode "COMBAT";
      _veh allowCrewInImmobile true;'''


Then like that : 
'''(vehicle _x)  addEventHandler ["hit",{
    _veh = _this select 0;
    _d = driver _veh;

    if (_veh getVariable ["willBeRepaired", false] damage _veh < 0.5) exitWith {};
    _veh setVariable ["willBeRepaired", true];

    if (_d != _veh && alive _d && !(_veh iskindof "plane")) then {
      _d setCombatMode "COMBAT";'''
And there is some ) missing

**Comment by esteldunedain** [comment]
The syntaxis I posted is correct. I don't know what you mean with "no reaction", but if the driver is still getting out too soon, you might try increasing the damage threshold from 0.1 to 0.2, 0.3, etc.

**Comment by vlad8011** [comment]
No reaction - i was meaning driver is not disembarking at all. 

Upper part look like this :
 '''= [] spawn {
  if (!isServer) exitWith {};
  {

   (vehicle _x)  addEventHandler ["hit",{
    _veh = _this select 0;
    _d = driver _veh;

    // Check if the vehicle is already marked for repair so it's done only once after each battle
	if (damage _veh < 0.1) exitWith {};
 
    if (_d != _veh && alive _d && !(_veh iskindof "plane")) then {
      _d setCombatMode "COMBAT";
      _veh allowCrewInImmobile true;
      _d addBackpackGlobal "B_assaultPack_khk";
      _d additemtobackpack "toolKit";
'''

**Comment by esteldunedain** [comment]
Well, I did some quick testing with the Merkava, and lowering the damage threshold to 0.05 should work. A completely busted track accounts for 0.09 total damage in that vehicle.

Another alternative is checking only the damage on the tracks, but that is a little more complicated.

**Comment by vlad8011** [comment]
Yes but i'm disapointet it totally dont work for wheeled vehicles. 
 > 0.5 - one shot in tire (from rifle) and they disembark to repair it
 < 0.5 - They sit in vehicle until you destroy 2 wheels, and then they disembark but not repairing vehicle (whole crew). Its very strange. Its like they ignoring most of script part.

**Comment by esteldunedain** [comment]
> Its like they ignoring most of script part.

It's exactly what they are doing! (by design!). I told you it was a simple solution, but probably it's not good enough.

If you really want this to work 100% properly you'll need to check for damage to individual hitpoints (tracks, wheels, etc) instead of the overall `damage`. That can be done in various ways (e.g. `getAllHitpointsDamage`). Sorry but I currently don't have the time to write a solution based on that.

**Comment by vlad8011** [comment]
if (getHitPointDamage " HitLTrack"; "HitRTrack"; "wheel_1_1_steering"; "wheel_1_2_steering"; "wheel_2_1_steering"; "wheel_2_2_steering" ) exitWith {};

?

**Comment by esteldunedain** [comment]
No, sorry; it's more complicated than that. Google `getAllHitpointsDamage` for the syntax,

**Comment by vlad8011** [comment]
still chinese to me :
    if (_veh getHitPointDamage "HitEngine" 1; "HitLTrack" 1; "HitRTrack" 1; "wheel_1_1_steering" 1; "wheel_1_2_steering" 1; "wheel_2_1_steering" 1; "wheel_2_2_steering" 1 ) exitWith {};

**Comment by vlad8011** [comment]
Number of combinations passed 30, i'm out of ideas....
Actual state:

> 0 = [] spawn {
>   if (!isServer) exitWith {};
>   {
> 
>    (vehicle _x)  addEventHandler ["hit",{
>     _veh = _this select 0;
>     _d = driver _veh;
> 
>     if getAllHitPointsDamage _veh; 
> 	[
> 		["HitEngine" , "HitLTrack" , "HitRTrack" , "wheel_1_1_steering" , "wheel_1_2_steering" , "wheel_2_1_steering" , "wheel_2_2_steering"],
> 		["Engine" , "LeftTrack" , "RightTrack" , "LeftFrontWheel" , "RightFrontWheel" , "RightRearWheel" , "LeftRearWheel"],
> 		[1 , 1 , 1 , 1 , 1 , 1 , 1]
> 	]
> 	true, exitWith {};
>     _veh setVariable ["willBeRepaired", true];
> 
>     if (_d != _veh && alive _d && !(_veh iskindof "plane")) then {
>       _d setCombatMode "AWARE";
>       _veh allowCrewInImmobile true;
>       _d addBackpackGlobal "B_assaultPack_khk";
>       _d additemtobackpack "toolKit";
> 
>       // This spawn now only happens once for each battle
>       [_d,_veh] spawn {
>         _d = _this select 0;
>         _veh = _this select 1;
>         waitUntil {(_d findNearestEnemy _d) distance _d > 1200};
> 	    sleep 5;
>         doGetOut _d;
>         waitUntil {!(_d in _veh)};
>         sleep 1;
>         _d setVectorDir (getpos _d vectorFromTo getpos _veh);
>         _d playMoveNow "Acts_carFixingWheel";
>         sleep 15;
>         _d switchMove "";
> 
>         if (alive _d) then {
>           _veh setDamage 0;
>           _veh setVariable ["willBeRepaired", false];
>         };
>      };
>    }}];
>  } foreach allUnits
> };

**Resoult:**

> > 13:00:20 Error in expression <eh = _this select 0;
> _d = driver _veh;
> 
> if getAllHitPointsDamage _veh; 
> [
> ["HitE>
> 13:00:20   Error position: <if getAllHitPointsDamage _veh; 
> [
> ["HitE>
> 13:00:20   Error if: Type Array, expected Bool
> 13:00:20 Error in expression <eh = _this select 0;
> _d = driver _veh;
> 
> if getAllHitPointsDamage _veh; 
> [
> ["HitE>
> 13:00:20   Error position: <if getAllHitPointsDamage _veh; 
> [
> ["HitE>
> 13:00:20   Error if: Type Array, expected Bool
> 13:00:20 Error in expression <eh = _this select 0;
> _d = driver _veh;
> 
> > 

Off course not working....
