### ISSUE TITLE
Mortar flips over when fired low-angle at charge 2

### ISSUE THREAD

**Issue by VKing6** [acemod/ACE3#335]
https://www.youtube.com/watch?v=kY2GbG5aX60

http://feedback.arma3.com/view.php?id=23542

Is this something we can do anything about? Reduce recoil on the mortar weapon, for example?

**Comment by ViperMaul** [comment]
Looks like this may be fixed by #384
Can we confirm and close this one?

**Comment by VKing6** [comment]
It's fixed.
