### ISSUE TITLE
RPT errors

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#3355]
**Arma 3 Version:** `1.56`

**ACE3 Version:** https://github.com/acemod/ACE3/commit/488d24bc017782f895181fb0415309d94aff0699

**Mods:**
* `@CBA_A3`
* `@ace`

**RPT log file:**
`
 1:31:38 File z\ace\addons\medical\CfgEden.hpp, line 26: '/Cfg3DEN/Object/AttributeCategories/ace_attributes/Attributes/ace_isMedicalVehicle.displayName': Missing ';' at the end of line
 1:31:38 File z\ace\addons\medical\CfgEden.hpp, line 27: '/Cfg3DEN/Object/AttributeCategories/ace_attributes/Attributes/ace_isMedicalVehicle.tooltip': Missing ';' at the end of line
 1:31:38 File z\ace\addons\medical\CfgEden.hpp, line 37: '/Cfg3DEN/Object/AttributeCategories/ace_attributes/Attributes/ace_isMedicalFacility.displayName': Missing ';' at the end of line
 1:31:38 File z\ace\addons\medical\CfgEden.hpp, line 38: '/Cfg3DEN/Object/AttributeCategories/ace_attributes/Attributes/ace_isMedicalFacility.tooltip': Missing ';' at the end of line
 1:31:40 File z\ace\addons\repair\CfgEden.hpp, line 26: '/Cfg3DEN/Object/AttributeCategories/ace_attributes/Attributes/ace_isRepairVehicle.displayName': Missing ';' at the end of line
 1:31:40 File z\ace\addons\repair\CfgEden.hpp, line 27: '/Cfg3DEN/Object/AttributeCategories/ace_attributes/Attributes/ace_isRepairVehicle.tooltip': Missing ';' at the end of line
 1:31:40 File z\ace\addons\repair\CfgEden.hpp, line 37: '/Cfg3DEN/Object/AttributeCategories/ace_attributes/Attributes/ace_isRepairFacility.displayName': Missing ';' at the end of line
 1:31:40 File z\ace\addons\repair\CfgEden.hpp, line 38: '/Cfg3DEN/Object/AttributeCategories/ace_attributes/Attributes/ace_isRepairFacility.tooltip': Missing ';' at the end of line
`

**Comment by jokoho48** [comment]
@SzwedzikPL
