### ISSUE TITLE
ACE Fire and Fire extinguishers 

### ISSUE THREAD

**Issue by WisnerArma** [acemod/ACE3#3356]
It would be awesome if you guys brought back fire damage like people catching on fire and running around. This would be awesome to have the medical system have burns in it that need something like liquid skin to treat them. Also to put out fires and vehicle fires you would need handheld or vehicle fire extinguishers. Please consider  this! Thank you!

**Comment by bux578** [comment]
Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
​

**Comment by commy2** [comment]
#414

**Comment by bux578** [comment]
^ redundant :P
