### ISSUE TITLE
Allow calling EFUNC(common,addEventHandler) before postInit

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#3360]
This should be an easy fix. Currently that functions starts like this:

```sqf
private _eventFunctions = GVAR(eventsLocation) getVariable _eventName;
```

but before postInit `GVAR(eventsLocation)` is still nill. It would be easy to prevent that either by moving its creation to preInit or initing it on the first call to `EFUNC(common,addEventHandler)` if it's not inited yet.

The rationale behind this is that we might need to use events to delay 3den initialization scripts, although that is not confirmed yet: https://github.com/acemod/ACE3/pull/3359#issuecomment-186593473

**Comment by PabstMirror** [comment]
`GVAR(eventsLocation) = createLocation ["ACE_HashLocation", [-10000,-10000,-10000], 0, 0];`
happens at  [common/preInit] (https://github.com/acemod/ACE3/blob/master/addons/common/XEH_preInit.sqf#L250)
(before the event functiosn are preped)

As common preInit is run before other preInit, we should be able to move all event handler installs to preInit.

Another way to solve this is to run eden calls through the `ace_common_fnc_runAfterSettingsInit` function as that is guaranteed to happen after all postInit's have finished, and all event handlers should be installed.

**Comment by esteldunedain** [comment]
Sorry, you are right.
