### ISSUE TITLE
inconsistency between 3DEN medical and repair integration

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#3361]
**Arma 3 Version:** `1.56`

**ACE3 Version:** https://github.com/acemod/ACE3/commit/fbcfbb92a6d87a23e99ccf7166b7a401da7341c1

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- _There is some coding inconsistency between recently added 3DEN integrations:_

repair:

**class ace_isEngineer** {
                        property = QUOTE(ace_isEngineer);
                        value = 0;
                        control = "Combo";
                        displayName = CSTRING(AssignEngineerRole_role_DisplayName);
                        tooltip = CSTRING(AssignEngineerRole_role_Description);
                        **expression = "_this setVariable ['%s',_value];";**
                        typeName = "NUMBER";
                        condition = "objectBrain";
                        defaultValue = 0;
                        class values {
                            class none {name = CSTRING(AssignEngineerRole_role_none); value = 0; default = 1;};
                            class engineer {name = CSTRING(AssignEngineerRole_role_engineer); value = 1; default = 0;};
                            class specialist {name = CSTRING(AssignEngineerRole_role_specialist); value = 2; default = 0;};
                        };
                    };
                    **class ace_isRepairVehicle** {
                        property = QUOTE(ace_isRepairVehicle);
                        value = 0;
                        control = "CheckboxNumber";
                        displayName = CSTRING(AssignRepairVehicle_role_DisplayName)
                        tooltip = CSTRING(AssignRepairVehicle_role_Description)
                        **expression = "_this setVariable ['%s',_value];";**
                        typeName = "NUMBER";
                        condition = "objectVehicle";
                        defaultValue = 0;
                    };
                    **class ace_isRepairFacility** {
                        property = QUOTE(ace_isRepairFacility);
                        value = 0;
                        control = "CheckboxNumber";
                        displayName = CSTRING(AssignRepairFacility_role_DisplayName)
                        tooltip = CSTRING(AssignRepairFacility_role_Description)
                        **expression = "_this setVariable ['%s',_value];";**
                        typeName = "NUMBER";
                        condition = "(1 - objectBrain) \* (1 - objectVehicle)";
                        defaultValue = 0;
                    };

medical:

**class ace_isMedic** {
                        property = QUOTE(ace_isMedic);
                        value = 0;
                        control = "Combo";
                        displayName = CSTRING(AssignMedicRoles_role_DisplayName);
                        tooltip = CSTRING(Attributes_isMedic_Description);
                        **expression = QUOTE(_this setVariable [ARR_2(QUOTE(QGVAR(medicClass)),_value)];);**
                        typeName = "NUMBER";
                        condition = "objectBrain";
                        defaultValue = 0;
                        class values {
                            class none {name = CSTRING(AssignMedicRoles_role_none); value = 0; default = 1;};
                            class medic {name = CSTRING(AssignMedicRoles_role_medic); value = 1; default = 0;};
                            class doctor {name = CSTRING(AssignMedicRoles_role_doctor); value = 2; default = 0;};
                        };
                    };
                    **class ace_isMedicalVehicle** {
                        property = QUOTE(ace_isMedicalVehicle);
                        value = 0;
                        control = "CheckboxNumber";
                        displayName = CSTRING(AssignMedicVehicle_enabled_DisplayName)
                        tooltip = CSTRING(Attributes_isMedicalVehicle_Description)
                        **expression = QUOTE(_this setVariable [ARR_2(QUOTE(QGVAR(medicClass)),_value)];);**
                        typeName = "NUMBER";
                        condition = "objectVehicle";
                        defaultValue = 0;
                    };
                    **class ace_isMedicalFacility** {
                        property = QUOTE(ace_isMedicalFacility);
                        value = 0;
                        control = "Checkbox";
                        displayName = CSTRING(AssignMedicalFacility_enabled_DisplayName)
                        tooltip = CSTRING(AssignMedicalFacility_enabled_Description)
                        **expression = QUOTE(_this setVariable [ARR_2(QUOTE(QGVAR(isMedicalFacility)),_value)];);**
                        typeName = "BOOL";
                        condition = "(1 - objectBrain) \* (1 - objectVehicle)";
                        defaultValue = "false";
                    };

**Comment by esteldunedain** [comment]
Do you mean about the variable names? e.g.  "ACE_isEngineer" vs "ACE_Medical_isMedicalFacility". 
That's an inconsistency in the modules themselves and not in the 3den, and I think it's to late to change that.

**Comment by gienkov** [comment]
That yes. But you could change
`class ace_isMedicalFacility` to `class ace_medical_isMedicalFacility` in 3DEN config and use `expression = "_this setVariable ['%s',_value];";`

**Comment by esteldunedain** [comment]
Yes, that's totally true. I think it's pretty minor, cause both end up working, but if anything I'd prefer using the approach you mention.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
