### ISSUE TITLE
Game crashes in random moments while using RHS + ACE

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#3377]
**Arma 3 Version:** 1.56`
Stable

**ACE3 Version:** `3.4.2`
stable

**Mods:**
* `@CBA_A3`
* `@ace`
*  @RHS

**Description:**
Game crash in random moments, most often when tank round hit some vehicle (suspected issue with module ace_repair), lot of spam in RPT files, and... you should take a look at error files, i'm sure you will find the issue.

**Steps to reproduce:**
Play some big battle tanks vs tanks (RHS)

**Where did the issue occur?**
Single player, EDEN editor in previewing mission.

**RPT log file:**

[Arma 3.zip](https://github.com/acemod/ACE3/files/139539/Arma.3.zip)

**Comment by commy2** [comment]
>11:50:24 Cannot create non-ai vehicle rhs_ammo_agm65_penetrator,

**Comment by vlad8011** [comment]
Hmmm what hint i can give more....
It happen when using tanks, and its cannon, Armor fault maybe ? Lot of spam erros refered to era hitpoints. I happen randomly, sometimes i shoot 4 rounds in one tank, and with 5th game crashes.

**Comment by vlad8011** [comment]
After further testing i cannot reproduce this issue WITHOUT ACE3, with and without ace i tested all AGM's and they work well/without error.

**Comment by esteldunedain** [comment]
This might be related to "Updating base class" errors due to ACE 3.4.2 been outdated in 1.56. I really don't see much we can do before this is reproduced on current master / 3.5.0 release.

**Comment by vlad8011** [comment]
Thanks for concrete info, i'll stick to vanilla till 3.5.0 then :)
Cheers!

**Comment by looterz** [comment]
Interesting, my group plays with ACE3 + RHS and I haven't personally had any crashes yet, but none of my missions use ace_repair modules. Have you tried reproducing the crashes without the ace_repair module placed?

**Comment by esteldunedain** [comment]
@looterz ace repair doesn't do anything until you actually try to repair a vehicle. Hence I don't think it can be responsable for the crashs @vlad8011 is reporting.

**Comment by vlad8011** [comment]
I'll wait for 3.5.0. For now it stopped crashing - maybe that was fault of CBA? I updated it to newest and problem seems to gone.

**Comment by esteldunedain** [comment]
> maybe that was fault of CBA? I updated it to newest and problem seems to gone.

Yup, that should have reduced the amount of "Updating Base Class" issues.

**Comment by vlad8011** [comment]
Problem is back ...
[Arma 3.zip](https://github.com/acemod/ACE3/files/155298/Arma.3.zip)

Totally random, on mission start.

**Comment by esteldunedain** [comment]
Man the crash happens on the audio dll. Arma recently deeply updated the audio engine and had a lots of problems with that. I think the problem is most likely in the engine.

**Comment by vlad8011** [comment]
Thanks, i'll check todays fix, hope they resolved it...

**Comment by esteldunedain** [comment]
Expired
