### ISSUE TITLE
Explosives are cumbersome to interact with while standing

### ISSUE THREAD

**Issue by Gwynblade** [acemod/ACE3#3379]
**Arma 3 Version:** `1.56`

**ACE3 Version:** `3.4.2`

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed Modules:**
None

**Description:**
It looks like the ability to interact with something depends on proximity of player's head (or upper body) to object you're trying to interact with. With default ace interaction (show cursor disabled) it causes problems, since your entire body moves while interacting (left - right / up and down). Which causes you to appear out of range, and interaction gets aborted. Even though you're close enough to original interaction point. 

Check the video below to understand better what I'm trying to say.

**Steps to reproduce:**
https://www.youtube.com/watch?v=-5PyrVKUA_Q&feature=youtu.be

**Where did the issue occur?**
Everywhere

**Comment by esteldunedain** [comment]
> It looks like the ability to interact with something depends on proximity of player's head.

Yes.

I do exactly understand what you are saying, the head seems to be a bit ahead of the pivot axis and therefore translates when you rotate. 

A possiblity would be to used this point as the interaction source for calculating distantes:

```sqf
_pos = _getPosASL (_unit);
_pos set [2, (eyePos _unit) select 2].
```

**Comment by Gwynblade** [comment]
There's something else that I forgot, when you place an explosive, you're already out of range to interact with it (even though you haven't moved). So you have to always move forward after placing it.

https://www.youtube.com/watch?v=MoaTbLNWGIo

Would you consider increasing the interaction range a tiny bit, so you can interact from the same spot you placed it from, just for convenience sake?

**Comment by esteldunedain** [comment]
> Would you consider increasing the interaction range a tiny bit, so you can interact from the same spot you placed it from, just for convenience sake?

That's actually an excellent suggestion. I always found setting up explosives a bit to cumbersome, but I've never actually paid enough attention to notice that. Thanks

**Comment by Gwynblade** [comment]
Great!

**Comment by bux578** [comment]
Hm. I've decreased the distance to 1m on purpose.

**Comment by esteldunedain** [comment]
@bux, for me placing the explosive and then having to move to be able to activate it is bad cumbersome. Sure the 1m distance is more realistic, but I think it's not worth it for this.

**Comment by esteldunedain** [comment]
I've checked in ACE and 1.5 is the minimum interaction distance used everywhere, except currently for explosives.

**Comment by Gwynblade** [comment]
Well, considering you would probably be able set up explosives before placing them on the ground, in real life (add detonator / timer). I don't think much of realism is lost. Unless there's more to it, and I'm missing something.

**Comment by bux578** [comment]
I'd be ok for placing explosives. But not for defusing.

**Comment by esteldunedain** [comment]
> I'd be ok for placing explosives. But not for defusing which was the main purpose of this change.

Ok, np with that
