### ISSUE TITLE
Add option to prevent F from switching to grenade launcher

### ISSUE THREAD

**Issue by VKing6** [acemod/ACE3#338]
In ACE2, pressing F would only toggle fire mode on a rifle with a GL.
To use the GL you would have to select it using the dedicated key.
Having this option back would be cool.

**Comment by commy2** [comment]
You can use the "Select Primary weapon" key to accomplish exactly this. I don't use F.

is that sufficient?

**Comment by VKing6** [comment]
The ACE Rifle key? Yea kinda.

**Comment by commy2** [comment]
So close?

**Comment by VKing6** [comment]
Might as well.
