### ISSUE TITLE
ACE support Crates, Ammo Crates become Disables

### ISSUE THREAD

**Issue by dvdbrewster** [acemod/ACE3#3383]
**Arma 3 Version:** `1.56`
*(stable*)

**ACE3 Version:** `3.4.2`
*(indicate if stable or dev, if dev indicate the commit the version is based on)*

**Mods:**
* `@CBA_A3`
* `@ace`
*  @mao_b;ood_mist.
*  @EWK_CIGS

**Placed Modules:**
* *Respawn, Set Med Vehicle, Spectator Settings.*

**Description:**
* *MP Mission beCTI ACE, Build a supply crate from Gear Build Menu. Access it successfully 1 Time. Then it becomes unusable. (box crates Nato Amm0, ACE Medical .ACE Medical Advanced.)*

**Steps to reproduce:**
* *Happens in any Launch Example :directly play from Steam Workshop:Play locally from MP Missions: Play on ded server using ACE Server.pbo..*

**ALTIS
* *Seems to be ok if you build crates in eden editor."*

**RPT log file:**
* * https://www.dropbox.com/s/eg5bqruvvv28s4b/arma3_2016-02-20_17-01-35.rpt?dl=0                          )*

**Comment by esteldunedain** [comment]
Sorry @dvdbrewster, but I think this is an issue with beCTI. Our supply crates are not scripted in any way, and you mention the vanilla NATO ammo crate failing too. There are plenty of beCTI errors in the RPT log too.
