### ISSUE TITLE
Disable moving object 

### ISSUE THREAD

**Issue by UpperM** [acemod/ACE3#3387]
**Arma 3 Version:** `1.56` Stable

**ACE3 Version:** `3.4.2`

Hi ,

It's possible to disable the function for moving objects like chair ?

Thank.

**Comment by jonpas** [comment]
You can use http://ace3mod.com/wiki/framework/dragging-framework.html#functions

**Comment by esteldunedain** [comment]
You can also delete the `ace_drag.pbo` to remove any trace of dragging and carrying if you so desire.

**Comment by UpperM** [comment]
Thank ! But if i delete this addons, it's possible to drag wounded ?

**Comment by esteldunedain** [comment]
> But if i delete this addons, it's possible to drag wounded ?

No

**Comment by UpperM** [comment]
Ok thank you !
