### ISSUE TITLE
Interaction Menu not opening, when win+ctrl are pressed

### ISSUE THREAD

**Issue by karlschubo** [acemod/ACE3#3394]
**Arma 3 Version:** `1.56`
*(indicate if stable, rc or dev*)

**ACE3 Version:** `3.4.2`
*(stable)*

**Mods:**
* `@CBA_A3`
* `@ace`
* `@RHS`
* `@Task Force Radio`

**Placed Modules:**
* *None*

**Description:**
* *When I try to open the interaction menu on any game it would simply not show up at all.*

**Steps to reproduce:**
* *Just install the mods wrong and don't know what you have installed wrong. xD*

**Where did the issue occur?**
* *Local Multiplayer (other scenarios not tested)*

**RPT log file:**
* **

**Comment by esteldunedain** [comment]
Did you try rebinding the action to a different key? Apparently the Win key is not working on Arma for various people.

**Comment by karlschubo** [comment]
the problem is, that i can't open the .bikey config in the @ace folder and ingame the options tab is empty :|

**Comment by Glowbal** [comment]
Hi @karlschubo,

The .bikey is a file used to validate .bisign files and their respective pbos by for example the server you play on. It is not a configuration file and should not be edited.

Did you try @esteldunedain's suggestion?

**Comment by karlschubo** [comment]
I fixed it by just reinstalling the mod like 9 times in a row. Maybe I accidently took apart a config file or so, but it is working now, but thanks to you both
