### ISSUE TITLE
Cannot load Save Games

### ISSUE THREAD

**Issue by Dshrike** [acemod/ACE3#3397]
**Arma 3 Version:** `Game version: 1.56.134627 - Main*

**ACE3 Version:** `3.4.2.0. - Stable'

**Mods:**
@CBA_A3
@ace

**Placed Modules:**
None

**Description:**
Unable to load save games with the ACE mod active. First, I receive an error: "cannot load "C:\\...\continue.arma3.save" (or whatever save file it attempts to load). Then, I receive error: "Error 0x00000001 – UNABLE_TO_INIT_DXGI"

**Steps to reproduce:**
1.) Load singleplayer/multiplayer scenario.
2.) Save while in scenario.
3.) Leave game by pressing "save & exit"
4.) Re-load scenario by pressing "resume"

**Where did the issue occur?**
Possibly after the eden editor update?

**RPT log file:**
http://pastebin.com/kfNqd4Rz

**Comment by commy2** [comment]
Can reproduce with CBA 2.3.1 and ACE 3.4.2 or ACE master
Cannot reproduce with CBA 2.3.1

I have no idea what this is. Seems to me like BI fucked up serialization.

**Comment by jokoho48** [comment]
i know this problem from a while ago i try to load a Save game from 1.3x to 1.4x and i had this same issue.

**Comment by commy2** [comment]
They are new save games.

**Comment by commy2** [comment]
Cannot repro with:
ace_common.pbo
ace_main.pbo
ace_modules.pbo

**Comment by commy2** [comment]
Can reprodue with:

- [ ] ace_apl.pbo
- [x] ace_common.pbo
- [ ] ace_interaction.pbo
- [ ] ace_interact_menu.pbo
- [ ] ace_laser.pbo
- [x] ace_main.pbo
- [ ] ace_missileguidance.pbo
- [x] ace_modules.pbo
- [ ] ace_weather.pbo

`Item count not matching: +2`

**Comment by commy2** [comment]
Error is in ace_interact_menu\CfgEventHandlers.hpp

**Comment by commy2** [comment]
Bug caused by initPost event handler in interact_menu module. (compiling interaction menues)
BI broke nested array serialization. Nothing we can do.

**Comment by Dshrike** [comment]
Just to confirm, we'll need to wait until BI decides to fix the issue on their own?

**Comment by esteldunedain** [comment]
>  we'll need to wait until BI decides to fix the issue on their own?

Probably yes. We might try to rewrite the menu after 3.5.0 in hope of preventing this, but there's no guarantee that other modules or mods might not have similar issues that will prevent saving/loading anyway.

Just to be clear, it's not that we changed anything on our side, but that serialization in the engine is not working properly anymore.

**Comment by Krags47** [comment]
Is there any sort of work around for this?

**Comment by commy2** [comment]
No

**Comment by commy2** [comment]
Well removing ACE_Iteraction.pbo and all those other modules that require it.

**Comment by maxhime** [comment]
It works for me - > https://github.com/acemod/ACE3/commit/6a58af5b33b86cde97480b20b49fa7520db5a0de

**Comment by Dshrike** [comment]
Thanks for the great work guys! I don't really know exactly how often you guys put out updates, so how soon will we be able to see the save loading fixed?

**Comment by Dshrike** [comment]
Great work guys! I can load save games now. I appreciate you guys looking into this. Being able to load save games will let me and my group of friends enjoy more scenarios.

Big thanks to Commy2, and esteldunedain for getting this all done.
