### ISSUE TITLE
Incorrect weight display.

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#3399]
**Arma 3 Version:** ``
*(rc*)

**ACE3 Version:** `3.4.2`
*(stable)*

**Mods:**
* `@CBA_A3`
* `@ace`
* `@rhsusf`
* `@RHSAFRF`
* `@CUP Terrains - Full 1.0.1`
* `@Task Force Arrowhead Radio 0.9.8`
* `@AlRayakV002`

**Placed Modules:**
* *'None'*

**Description:**
* *Showing that the PG-7VL weight of 1.18 kg, when the weight to be 2.6 kg. The pound weight of this projectile has 2.6 lb.*

**Steps to reproduce:**
* *Find the difference between the equipment with a shell and without it.*

**Where did the issue occur?**
* *"Dedicated Server", "Local Multiplayer", "Editor", or "Singleplayer"*

**RPT log file:**
* *
[ArmaReport_Log_20160223T134846_XXXXXXXXX.zip](https://github.com/acemod/ACE3/files/142670/ArmaReport_Log_20160223T134846_XXXXXXXXX.zip)
*

**Comment by jokoho48** [comment]
the PG-7VL is from RHS and they dont use accurate values for there weapons and uniforms.

i would say cant/wont fix

**Comment by GalNa** [comment]
[M67](https://en.wikipedia.org/wiki/M67_grenade) weighs 0.19 kg.

**Comment by bux578** [comment]
There's no "weight" in Arma 3. All items share a `mass` value. Which is an abstract number that kinda implies weight as well as the amount of storage space needed in uniforms, vests, backpack or vehicle inventory. ACE3 uses a magic number to approximately convert the mass to kilogram/pounds. It might fit for certain items but for others it could be horribly wrong.
