### ISSUE TITLE
Cancel explosives placement using the interaction menu or something

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#34]
Apparently BI fixed the `addActionEventHandler` for the "MenuBack" action, so we need to change explosives placement cancelling to something else than pressing RMB.

Luckily, the hack stil works for "DefaultAction", so jamming and weapon safe are fine.

**Comment by PabstMirror** [comment]
`ZoomTemp` doesn't work for me, but I added a backup cancel with 253614d44223e12bcc1b714c8b99e253fb208d75

Just opening interact_menu willl cancel placment.

**Comment by esteldunedain** [comment]
I think the current solution is good enough for now, as we can't catch the RMB yet. This should be reevaluated if http://feedback.arma3.com/view.php?id=23679 is fixed

**Comment by paul-hewson** [comment]
Can you change the text when placing an explosive ? Replace the current RMB by "interact menu" (or the key assigned to it ?).

**Comment by jonpas** [comment]
This should be added to 3.2.1 milestone.

**Comment by SilentSpike** [comment]
It's fixed by 3.3.0
