### ISSUE TITLE
No talking player avatar

### ISSUE THREAD

**Issue by Deniel05** [acemod/ACE3#3407]
**Arma 3 Version:** `1.56`

Hi there! Is possible to turn off the no talking player avatar feature? I donť like that my avatar cant speak. It looks ridiculous. I´ll be much obliged if this will be possible.

**Comment by commy2** [comment]
Yes. Remove the `ace_noradio.pbo` file from the addons folder in the @ace folder.

**Comment by Deniel05** [comment]
Thanks. :-)))

**Comment by Gwynblade** [comment]
I think there may be a bug here. On your wiki it only says this:

"1.1 Silent avatar
Mutes the player’s automatic callouts (“Enemy man, 100 meters, front!”). Does not mute AI callouts."

Which is cool, those callouts can be annoying. But it mutes all of my orders as well. Just complete silence whenever I tell an AI to do something, which feels a bit weird when you play.

Since there is no mention of this on your wikipedia, is this a bug, or just oversight in wiki?

**Comment by esteldunedain** [comment]
> Since there is no mention of this on your wikipedia, is this a bug, or just oversight in wiki?

It's by design. Given that ACE focus is on multiplayer, and it really makes no sense for your avatar to be saying anything in that context.

**Comment by Gwynblade** [comment]
But in multyplayer you won't do those orders anyway (All, regroup, or All move there), you will say them over team speak / acre to your team, so it doesn't really matter.

You only do those orders in coop to AI, and there it doesn't matter if you say it out loud.

And just to be 100% clear, I'm not talking about automatic callouts here, I'm glad those are disabled. I mean orders that you deliberately give to the team, it's a bit weird to be able to give them telepathically?

Not trying to pressure you guys into changing anything, you guys are doing an excellent job. Just making sure this is 100% not a bug.

**Comment by esteldunedain** [comment]
The goal, since the AGM days, was a "silent avatar". I see your point, but it's a feature request, not a bug.

**Comment by Gwynblade** [comment]
I see, thanks for the answer :)

**Comment by commy2** [comment]
>And just to be 100% clear, I'm not talking about automatic callouts here, I'm glad those are disabled. I mean orders that you deliberately give to the team, it's a bit weird to be able to give them telepathically?

This would be a huge PITA, because you would need a radio protocol for every speaker in the game, where you filter out all call outs that you described. And it wouldn't work with custom protocols like the russians from RHS.

**Comment by Gwynblade** [comment]
Oh, ok. I will not post it to the feature requests then, thanks for the clarification!

**Comment by mwpowellhtx** [comment]
Running TS and ACRE, the last thing I need is for the canned verbiage to muck things up. Follow on question, I see in the CBA config, there is a flag enable or disable all three, _face+voice+insig_, I am actually okay with face and insig, or at least face, but I do want to shut down the voice aspect. Is there a way to do that?
