### ISSUE TITLE
Streamline module classnames

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#3409]
Continuation of #2561 

Majority seemed to be for `GVAR(moduleX)` format.

Best way to do this seems to be:
- Rename modules
- Keep old module names as separate modules inherited from the newly named ones and hidden with `scope = 1`
- Mark them as deprecated in RPT when used (not sure how to best do that, make a check for module name in the function?)
- Remove after 2 (or 3) minor version updates

**Comment by esteldunedain** [comment]
Hold on doing this for llittle longer. We might want to scrap modules altogether for 3.6.0 and move the functionality to 3den settings/attributes. We should probably discuss it on the next meeting.

**Comment by jonpas** [comment]
You are totally correct, I forgot about that a bit.

**Comment by jonpas** [comment]
Not using modules anymore except a select few that make sense. Kind of pointless in renaming now anyways, so closing this.
