### ISSUE TITLE
Add frag definitions for remaining rockets/shells/grenades

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#342]
CBA_A3_Dev
ACE_Dev: 83c670576b8e96ce0dde5347008fcb5e02a46f93
tfar

RPT: http://pastebin.com/Y97bZDWu
- [x] Missile_AGM_01_F
- [x] Missile_AGM_02_F
- [x] M_Hellfire_AT
- [ ] M_Titan_AA_static 
- [ ] M_Titan_AA_long 
- [ ] M_Titan_AP 
- [ ] M_AT 
- [x] Rocket_03_HE_F
- [ ] R_TBG32V_F 
- [x] G_40mm_HE 
- [x] G_40mm_HEDP 
- [x] Sh_105mm_HEAT_MP_T_Red 
- [x] Sh_82mm_AMOS
- [x] Sh_120mm_HE
- [x] Sh_125mm_HE
- [x] Sh_155mm_AMOS 
- [x] R_Hydra_HE
- [ ] M_Scalpel_AT
- [ ] M_Air_AA
- [ ]  ... ?

**Comment by ViperMaul** [comment]
How close are we to completing this one?

**Comment by jaynus** [comment]
I'll get this done for release. It's just filling values

**Comment by jaynus** [comment]
Assigning this to ulteq since he was so gracious to take this over and help out.

**Comment by bux578** [comment]
edited OP

**Comment by ulteq** [comment]
https://github.com/acemod/ACE3/commit/59017ed79d3ef2de2af15fa6686d9ee8466a24f9:
* R_Hydra_HE
* Sh_120mm_HE
* Sh_125mm_HE
* Missile_AGM_02_F
* M_Hellfire_AT
