### ISSUE TITLE
Toggle MILS on Mk6 Mortar not stringtabled and not working

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#3420]
**Arma 3 Version:** `1.56`

**ACE3 Version:** https://github.com/acemod/ACE3/commit/69a3c7975626dc6994c1f0c43e226d221f9f4d03

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed Modules:**
* *Mk6 mortar*

**Description:**
Toggle MILS interaction is not stringtabled. It doesn't work correctly too:
https://youtu.be/mWp6Uj9ziVI

**Steps to reproduce:**
* *Enter Mk6 mortar.*
* *Interaction menu - select Toggle MILS*

**Where did the issue occur?**
* *"Singleplayer"*

**RPT log file:**
* *Add a link (pastebin.com) to the client and/or server RPT file. An instruction to find your RPT files can be [found here](https://community.bistudio.com/wiki/Crash_Files#Arma_3)*

**Comment by PabstMirror** [comment]
Fixed, Thanks for helping to find bugs on master before release!
