### ISSUE TITLE
Radious of spare parts placement

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#3422]
**Arma 3 Version 1.56
Stable

**ACE3 Version:** `3.4.2`
stable
**Mods:**
* `@CBA_A3`
* `@ace`
*  RHS
* CUP_Terrains

**Placed Modules:**
NONE

**Description:**
I played a lot of missions and every time i'm using unloading spare parts option, it placing spare part very far from vehicle- i must get out of cover, and unarmed (with spare part "in hands") walk few meters back to vehicle. Please decrease the range from vehicle - player - spare part. Spare part could be placed under the player as best for example.

**Steps to reproduce:**
Unload spare track link, or spare wheel from vehicle.

**Where did the issue occur?**
Single-Player

**Comment by PabstMirror** [comment]
Should be improved by #3228
It tries to find the best free spot halfway between the player and the vehicle.

**Comment by esteldunedain** [comment]
Fixed in master

**Comment by vlad8011** [comment]
Cool!
