### ISSUE TITLE
scope reticle not moving

### ISSUE THREAD

**Issue by macfifa** [acemod/ACE3#3425]
arma 3 1.56
ACE3 Version: 3.4.2
stable

Mods:

@CBA_A3 2.3.1
@ace 3.4.2

Placed ACE3 Modules:
advanced ballistics

Description:
In the old ace versions the scope reticle was moving up or down as you adjust elevation like real life
now i was tring to zero my rifle and that movment is gone.
I dont know if it is abug or not

Steps to reproduce:
mount any scope from ace on a rilfe

Where did the issue occur?
Editor

**Comment by esteldunedain** [comment]
Is your weapon rested? In that case the technique we use to move the view up and down as you adjust doesn't work. There's really no scripting commands to fix it at the moment.

**Comment by macfifa** [comment]
i tried both rested and un rested

**Comment by macfifa** [comment]
why is the bug not fixed ? i love sniping and the ace 3 is the most realistic mod in arma so plz dont take too long

**Comment by jonpas** [comment]
> why is the bug not fixed ?

@esteldunedain gave you an answer, to quote him:
> There's really no scripting commands to fix it at the moment.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 137 days without any activity.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
