### ISSUE TITLE
Surgical kit not working when set to Anywhere

### ISSUE THREAD

**Issue by austinjames314** [acemod/ACE3#3429]
**Arma 3 Version:** `1.56.134627`
*(indicate if stable, rc or dev*) - Not sure. Stable probably?

**ACE3 Version:** `3.4.2`
*(indicate if stable or dev, if dev indicate the commit the version is based on)* - Not sure. Stable probably?

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed Modules:**
* Advanced Medical Settins [ACE]
* Medical Settings [ACE]

**Description:**
With the modules set to the following setings:
http://i.imgur.com/PdPE36Y.png
http://i.imgur.com/nt1KmdO.png

When I try to use the Surgical Kit, it's not an available option. Doesn't matter if I try in the open, inside an ambulance. **Setting the surgical kit location to 'Anywhere' seems to be the same as setting it to 'Disable'.** Happens to everyone on our server. We can only use the surgical kit at all if we restrict it to ambulance / medical facility.

**Steps to reproduce:**
* Create a scenario with the modules as described as above.
* Add an Ambulance as a control, for testing.
* Add medical supplies and surgical kit to your inventory.
* Add an AI to wound, and then medic. Helps if you handcuff them.
* bandage the wound and stabilize the casualty.
* Attempt to stitch the wound.
* Discover that the surgical kit option doesn't appear.
* Try again in ambulance. Same problem.

**Where did the issue occur?**
* Dedicated server, and Editor.

**RPT log file:**
First time trying to include this, hope I got it right: http://pastebin.com/ZVGU5UT9

**Comment by Glowbal** [comment]
I know we changed something to this but I do not know if it was for 3.5.0 or if it was a fix for this exact issue. Will look into it.

**Comment by PabstMirror** [comment]
```
21:43:47 [ACE] (common) WARNING: Setting [ace_medical_medicSetting] out of bounds -1 (values[] count is 3)(
21:43:47 [ACE] (common) WARNING: Setting [ace_medical_enableUnconsciousnessAI] out of bounds -1 (values[] count is 3)(
21:43:47 [ACE] (common) WARNING: Setting [ace_medical_medicSetting_PAK] out of bounds -1 (values[] count is 3)(
...
```

Ref #3339

BIS broke modules that use drop down boxes when selection a choice with `value = 0`.
We are hoping on a arma hotfix soon. In the meantime, what you will need to do is put these settings in the description.ext

```
class ACE_Settings {
    class ace_medical_medicSetting {value = 0; force = 1;};
    class ace_medical_enableUnconsciousnessAI {value = 0; force = 1;};
    class ace_medical_medicSetting_PAK {value = 0; force = 1;};
    class ace_medical_medicSetting_SurgicalKit {value = 0; force = 1;};
    class ace_medical_consumeItem_SurgicalKit {value = 0; force = 1;};
    class ace_medical_useLocation_PAK {value = 0; force = 1;};
    class ace_medical_useLocation_SurgicalKit {value = 0; force = 1;};
    class ace_medical_useCondition_PAK {value = 0; force = 1;};
    class ace_medical_useCondition_SurgicalKit {value = 0; force = 1;};
};
```

When they do finaly fix it, you may need to delete and replace the module to save the fix in the mission.sqm
