### ISSUE TITLE
Self interaction menu doesn't work

### ISSUE THREAD

**Issue by Nathan157** [acemod/ACE3#3439]
**Arma 3 Version:** `1.56 stable`

**ACE3 Version:** `3.4.2  stable`

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed Modules:**
* *None*

**Description:**
* *Everytime I try to open self interaction menu the red circle appears and nothing else, I tried rebinding   it, nothing happened. I tried CBA_auto_xeh, no effect. Tried different profiles, nothing. Only the interaction menu works on everyone else.*

**Where did the issue occur?**
* *I found out about it in MP while having a buch of addons activated, later on, I tried it without any other addons then ACE and CBA and problem still persist, tried it in Editor too"*

**RPT log file:**
[RPT.txt](https://github.com/acemod/ACE3/files/149305/RPT.txt)
*

**Comment by jokoho48** [comment]
try to delete CBA complet and reinstall it.

**Comment by Nathan157** [comment]
Still doesn't work, red circle

**Comment by esteldunedain** [comment]
```

**Comment by esteldunedain** [comment]
@commy2:
```
10:52:24 [ACE] (interact_menu) ERROR: Compile checks bad for (classname: B_Soldier_F)(addon: ["A3_Characters_F_BLUFOR"]) B Alfa 1-1:1 (Nathan157)
10:52:24 [ACE] (interact_menu) ERROR: Compile checks bad for (classname: B_HeavyGunner_F)(addon: ["A3_Characters_F_Mark"]) B Alfa 1-2:1
10:52:24 [ACE] (interact_menu) ERROR: 2 Classnames failed compile check!!! (bad XEH / missing cba_enable_auto_xeh.pbo)
```

**Comment by Nathan157** [comment]
Where I should put the XEH file?

**Comment by Nathan157** [comment]
Tried putting it into @CBA\Addons and it keeps disapearing

**Comment by jokoho48** [comment]
if u still have a cba_enable_auto_xeh.pbo you dont have a clean install

**Comment by Nathan157** [comment]
So... I should reinstall whole Arma?

**Comment by esteldunedain** [comment]
No, just properly delete CBA and redownload it

**Comment by esteldunedain** [comment]
What @jokoho48 means is that `cba_enable_auto_xeh.pbo` is no longer present on the latest CBA release, so you shouldn't have it anymore.

**Comment by Nathan157** [comment]
Oh...I'll try downloading it from somewhere else, not Steam Workshop

**Comment by Nathan157** [comment]
Seems like I have to use the Steam Workshop, ACE depends on CBA from Workshop

**Comment by Nathan157** [comment]
Can you tell how properly can I delete CBA? I tried unsubscribing, deleting it and it still doesn't work

**Comment by esteldunedain** [comment]
Sorry, I don't use the workshop.

**Comment by commy2** [comment]
Hey @Nathan157 ,

Please open this folder:
`F:\Steam\steamapps\common\Arma 3\`
And delete the folder called:
`@CBA_A3`

Then download the latest CBA from here: https://github.com/CBATeam/CBA_A3/releases/tag/v2.3.1.160220

And move the @CBA_A3 folder from the .zip into into the main folder of Arma (same as above)

To start the game without Steam, right click on the Desktop and create a shortcut with this path:
`"F:\Steam\steamapps\common\Arma 3\arma3.exe" -mod=@ace;@CBA_A3`

To play the game, just use the shortcut. If the launcher opens, just close the launcher and double click the shortcut again.

**Comment by commy2** [comment]
Steam sucks ass and so does the launcher.

**Comment by Nathan157** [comment]
Oh, ok thanks, I'll try to do that

**Comment by Nathan157** [comment]
Great! It works! Thank you guys so much for help!

**Comment by commy2** [comment]
you're welcome
