### ISSUE TITLE
Further improvements to ACE_Hearing

### ISSUE THREAD

**Issue by nicolasbadano** [acemod/ACE3#3448]
- [ ] Calculate hearing damage of shots based on caliber, velocity, etc for better uniformity.
- [ ] Remove the high pitch beep from all the hearing loss effects except the strongest one. This would make hearing damage always start as a low pitch woosh, with actual ringing only happening for strong hearing damage.

**Comment by ulteq** [comment]
> Calculate hearing damage of shots based on caliber, velocity, etc for better uniformity.

Don't we do that already?
https://github.com/acemod/ACE3/blob/master/addons/hearing/functions/fnc_firedNear.sqf#L74-L86

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
