### ISSUE TITLE
Medical anims end abruptly on medical 

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#3449]
ACE3 3.5.0 RC

Tested in basic medical only.

https://youtu.be/ihBFQIftXAM

**Comment by esteldunedain** [comment]
@Glowbal said this is by design, to avoid some weird anims happening at the end. I think we should take a deeper look post 3.5.0 to see if we can find a better solution.

**Comment by BaerMitUmlaut** [comment]
We could parse the animation length from config, and increase the animation speed with [setAnimSpeedCoef](https://community.bistudio.com/wiki/setAnimSpeedCoef) so it fits the length of the interaction?
Could look ridiculous if sped up too much though.

**Comment by esteldunedain** [comment]
> We could parse the animation length from config...

...and adjust the progressbar accordingly

**Comment by gienkov** [comment]
Or use better healing anims that are right now in the game? VeteranMOD uses
them.

**Comment by Glowbal** [comment]
I'm ok to leave this as is. I see no real need to change it. It's done to avoid a clunky gameplay experience.

**Comment by commy2** [comment]
fixed
