### ISSUE TITLE
ace_gestures_reloadmutex is nill on mission restart on 3den, inited from DisplayLoad XEH

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#3450]
ACE3 3.5.0 RC

E.g. 
- Move forward
- Rally up
- Stop
- Cover
- etc

**Comment by jonpas** [comment]
Works fine on release 992b4190e192ea22a49b5af6c4cca048d001fbee

**Comment by esteldunedain** [comment]
tagging @commy2. In my machine the `ace_gestures_reloadmutex` was nil when testing this. That's supposed to be inited with the new event display XEH. 

Tested on an unsaved mission in 3den

**Comment by esteldunedain** [comment]
Sorry, my CBA build was probably outdated. Works fine against the CBA's current master

**Comment by esteldunedain** [comment]
@commy2, we confirmed the bug happens when restarting a mission in 3den. Apparently  this is not called again:
```

**Comment by esteldunedain** [comment]
That same event handler hooks up some things in`common, including the `ScrollWheel` handler. As far as I can tell that's not broken on mission restart, but I don't understand why.

**Comment by PabstMirror** [comment]
`ace_common_ScrollWheelFrame` is nil on restart, so that code isn't being run either
