### ISSUE TITLE
Can't open ACE menus

### ISSUE THREAD

**Issue by CosmoMomen** [acemod/ACE3#3464]
**Arma 3 Version:** `1.56.134627 Stable`
*(indicate if stable, rc or dev*)

**ACE3 Version:** `3.4.2.0 Stable`
*(indicate if stable or dev, if dev indicate the commit the version is based on)*

**Mods:**
* `@CBA_A3 2.3.1`
* `@ace 3.4.2`

**Placed Modules:**
None

**Description:**
Cannot open ACE 3 interaction menus.. re downloaded CBA and ACE. Center red open dot comes up, but no radial options  

**Steps to reproduce:**
Open any game MP, SP try to interact

**Where did the issue occur?**
Any game type

**Comment by esteldunedain** [comment]
Please supply an RPT log. Without that there's realy no way of helping you.

**Comment by CosmoMomen** [comment]
http://pastebin.com/index/DFZVaQx4

**Comment by commy2** [comment]
Delete this folder:
`C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@cba_a3`
And download again from here: https://github.com/CBATeam/CBA_A3/releases/tag/v2.3.1.160220

**Comment by commy2** [comment]
Same as: https://github.com/acemod/ACE3/issues/3439
