### ISSUE TITLE
Animation plays when checking ammo

### ISSUE THREAD

**Issue by toastfirebreath** [acemod/ACE3#3465]
ACE3 Version: 3.4.2
Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None.

**Description:**
A CPR animation plays while checking ammo while moving.

Sidenote: I think it happens same way with tap shoulder hotkey, however unable to confirm this right now. 

**Steps to reproduce:**
1. Pull out and lower primary weapon.
2. While walking forward ‘check ammo’
3. Tie someone's invisible shoe.

**Where did the issue occur?**
N/A

**RPT log file:**
N/A

**Comment by jokoho48** [comment]
this issue is in 3.5.0 allready fixed wait until release
