### ISSUE TITLE
FRIES float in the air if helicopter is deleted via zeus

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#3467]
**Arma 3 Version:** `1.56`
stable

**ACE3 Version:** `3.5.0 latest commit: 8fc4a9d901d51cedf1b622b41739004697d21dbb`
release branch

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed Modules:**
None

**Description:**
Helicopters equipped with FRIES have the FRIES float in the air if the vehicle is deleted via zeus.

**Steps to reproduce:**
- Place a helicopter and give it FRIES.
- Delete it via zeus.

**Where did the issue occur?**
SP

**RPT log file:**
nuthin' there.

**Comment by jokoho48** [comment]
@BaerMitUmlaut

**Comment by esteldunedain** [comment]
Fixed in #3463
