### ISSUE TITLE
AI local on headless client taking no damage

### ISSUE THREAD

**Issue by BeerRush** [acemod/ACE3#3469]
[bugreport.zip](https://github.com/acemod/ACE3/files/151191/bugreport.zip)
**Arma 3 Version:**  `1.56 stable`

**ACE3 Version:** `3.4.2 stable over Steam Workshop``

**Mods:**
* `@CBA_A3`
* `@ace`
* `@CUP ACE3 Compatibility Addon - Vehicles`
* `@CUP ACE3 Compatibility Addon - Weapons`
* `@CUP Terrains - Core`
* `@CUP Terrains - Maps`
* `@CUP Units`
* `@CUP Vehicles`
* `@CUP Weapons`
* `@task_force_radio`

**Placed Modules:**
* Set Medical Vehicle
* Hearing
* Advanced Ballistics
* Map
* Weather
* Interaction System
* Medical Menu
* Repair Settings
* Refuel Settings
* Rearm Settings

Medical Settings are set via 
`ace_medical_enableadvancedwounds = true; // Enable Advanced wounds - Allow reopening of bandaged wounds? (Adv only)
ace_medical_bleedingcoefficient = 1; // Bleeding coefficient - Coefficient to modify the bleeding speed
ace_medical_level = 2; // Medical Level - What is the medical simulation level? - Basic = 1, Advanced = 2
ace_medical_enablevehiclecrashes = true; // Vehicle Crashes - Do units take damage from a vehicle crash?
ace_medical_aidamagethreshold = 1; // AI Damage - What is the damage an AI can take before being killed? - number from 0 to 1
ace_medical_enablescreams = true; // Enable Screams - Enable screaming by injuried units
ace_medical_keeplocalsettingssynced = true; // Sync status - Keep unit status synced. Recommended on.
ace_medical_enablefor = 0; // Enabled for - Select what units the medical system will be enabled for (Adv only) - Players only = 0, Players and AI = 1
ace_medical_enableunsconsiousnessai = 0; // AI Unconsciousness - Allow AI to go unconscious - Disabled = 0, Enabled = 1, 50/50 = 2
ace_medical_playerdamagethreshold = 1; // Player Damage - What is the damage a player can take before being killed? - number from 0 to 1
ace_medical_preventinstadeath = true; // Prevent instant death - Have a unit move to unconscious instead of death

ace_medical_medicsetting_surgicalkit = 1; // Allow Surgical kit (Adv) - Who can use the surgical kit? - Anyone = 0, Medics only = 1, Doctors only (Adv) = 2
ace_medical_consumeitem_surgicalkit = 1; // Remove Surgical kit (Adv) - Should Surgical kit be removed on usage? - No = 0, Yes - 1
ace_medical_medicsetting = 2; // Medics setting - What is the level of detail prefered for medics? - Disable medics = 0, Normal = 1, Advanced = 2
ace_medical_maxrevivetime = (60 * 5); // Max Revive time - Max amount of seconds a unit can spend in revive state
ace_medical_medicsetting_pak = 1; // Allow PAK (Adv) - Who can use the PAK for full heal? - Anyone = 0, Medics only = 1, Doctors only (Adv) = 2
ace_medical_allowlittercreation = true; // Enable Litter - Enable litter being created upon treatment
ace_medical_uselocation_surgicalkit = 0; // Locations Surgical kit (Adv) - Where can the Surgical kit be used? - Anywhere = 0, Medical Vehicles = 1, Medical facility = 2, Vehicles & facility = 3, Disabled = 4
ace_medical_enableoverdosing = true; // Enable Overdosing - Enable overdosing of medications
ace_medical_amountofrevivelives = 100000; // Max Revive lives - Max amount of lives a unit. 0 or -1 is disabled
ace_medical_consumeitem_pak = 1; // Remove PAK on use (Adv) - Should PAK be removed on usage? - No = 0, Yes - 1
ace_medical_uselocation_pak = 3; // Locations PAK (Adv) - Where can the personal aid kit be used? - Anywhere = 0, Medical Vehicles = 1, Medical facility = 2, Vehicles & facility = 3, Disabled = 4
ace_medical_littercleanupdelay = (60 * 30); // Life time of litter objects - How long should litter objects stay? In seconds. -1 is forever`

**Description:**
When using a headlessclient in my mission on the dedicated server, AI units will not die when being shot with CUP weapons. Not tested with vanilla weapons. If the units are local on the server, everything works fine. 

**Steps to reproduce:**
Start the mission in the zipfile on a dedicated server with headless client connected and enable "Headless Client" in the mission parameters.

**Where did the issue occur?**
Dedicated Server with headless client.

[bugreport.zip](https://github.com/acemod/ACE3/files/151191/bugreport.zip)

**Comment by captainblaffer** [comment]
I believe this is because of 3DEN editor.
I had this issue occur on my new mission(saved in 3DEN). But it does not occur on my old 2d editor missions.

**Comment by jokoho48** [comment]
yes this is BI fault we cant do any thing

**Comment by commy2** [comment]
3den broke headless clients. BI fixed this in dev branch. Until then, don't use HC with 3den missions.

**Comment by commy2** [comment]
Can be confirmed by looking into the RPT files. Both client and server have this line:
`"XEH: PostInit started."`
The headless client does not, because BI broke it.

**Comment by BeerRush** [comment]
Reverting to 2D Editor solved it :) thanks
