### ISSUE TITLE
Preparing fastrope breaking roping on the orca and kajman

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#3472]
**Arma 3 Version:** `1.56`
stable

**ACE3 Version:** `3.5.0: latest commit: 8fc4a9d901d51cedf1b622b41739004697d21dbb`
release branch

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed Modules:**
None

**Description:**
Preparing the fastroping system breaks roping on the orca and Kajman, they can also deploy ropes without preparation or fries.

**Steps to reproduce:**
- Place an orca or kajman in the editor at a reasonable height for fast roping.
- In the vehicle init box type ```this disableAI "MOVE";this disableAI "FSM";```
- move your playable character inside the helo then test roping out.

**Where did the issue occur?**
SP

**RPT log file:**
nuthin' there.

**Comment by esteldunedain** [comment]
Probably fixed in #3463. @BaerMitUmlaut, can you confirm?

**Comment by alganthe** [comment]
Nope, this issue isn't fixed in #3463

**Comment by esteldunedain** [comment]
Fixed in #3463

**Comment by alganthe** [comment]
Fixed in #3463
(my previous message was before he pushed the commit fixing this)
