### ISSUE TITLE
Improve Eden Attributes descriptions

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#3481]
![image](https://cloud.githubusercontent.com/assets/1235520/13418457/c56d5d9c-df75-11e5-879c-970192ceefbf.png)

**Comment by PabstMirror** [comment]
@gienkov Also mentioned that we could look into making those 2 captive options mutually exclusive, as having both checked would make no sense.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
