### ISSUE TITLE
ACE_Box_82mm_Mo_Combo is overflowing

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#3491]
**Arma 3 Version:** `1.56 stable`

**ACE3 Version:** `3.5.0 RC3`

**Mods:**
* `@CBA_A3`
* `@ace`
* Bunch of other stuff (should not matter in this case)

**Placed Modules:**
* Mk6 Settings with ammunition handling enabled

**Description:**
* The `ACE_Box_82mm_Mo_Combo` is filled with more items than it can normally hold. Once you take a mortar round of it, you cannot put it back in.

**Steps to reproduce:**
* Place a `ACE_Box_82mm_Mo_Combo`
* Take any round from the crate
* Try puttin it back

**Where did the issue occur?**
* 3DEN

**Comment by VKing6** [comment]
Would like some input on this, since there are 48 slots and 48 magazines being added
```
class ACE_Box_82mm_Mo_Combo: ACE_Box_82mm_Mo_HE {
    displayName = CSTRING(ComboBox_DisplayName);
    transportMaxMagazines = 48;
    class TransportMagazines {
        MACRO_ADDMAGAZINE(ACE_1Rnd_82mm_Mo_HE,32);
        MACRO_ADDMAGAZINE(ACE_1Rnd_82mm_Mo_Smoke,8);
        MACRO_ADDMAGAZINE(ACE_1Rnd_82mm_Mo_Illum,8);
    };
};
```

**Comment by VKing6** [comment]
Never mind, maximumLoad is a thing apparently.
