### ISSUE TITLE
Issue when trying to move/place items (mines, tactical ladders, dragging someone...)

### ISSUE THREAD

**Issue by BlackWindowS** [acemod/ACE3#3498]
**Arma 3 Version:** `1.56` stable

**ACE3 Version:** `3.5.0` and `3.4.2`

**Mods:**
* `@CBA_A3`
* `@ace`
* `@RHSAFRF`
* `@RHSUSF`
* `@task_force_radio`

**Placed Modules:**
* None
* Tried also with modules

**Description:**
* It appears that I cannot use the explosive system, or any ACE system with placable items. I am stuck with the icons of a mouse indicating LMD for realease, RMD to cancel, etc. I've spot this issue after the last CBA update for the first time.

**Steps to reproduce:**
* Only in my mission. Try to place a mine, a tactical ladder, a trench... It won't work.

**Where did the issue occur?**
* Everytime (editor, 3D editor, MP, SP) but ONLY with one single mission.

**RPT log file:**
* http://pastebin.com/sQSkYyzz

Link to the mission https://github.com/BlackWindowS/Pushback

**Comment by esteldunedain** [comment]
@BlackWindowS, please upload the complete RPT log. The one you submited lacks the first part in which the version of each mod is displayed.

**Comment by PabstMirror** [comment]
If you could upload that mission as well it might help us reproduce.

**Comment by BlackWindowS** [comment]
Edited with link to the mission.
Full RPT
http://pastebin.com/RTZDU0kN

**Comment by PabstMirror** [comment]
scripts\systemes\surveillerJoueur.sqf
called from onPlayerRespawn.sqf

does `removeAllActions player;` which will break ace's addAction

**Comment by BlackWindowS** [comment]
The action to place a mine is an addAction ? The one with mouse icone ?

**Comment by PabstMirror** [comment]
We use addAction's to capture the mouse input, so you can left-mouse-button to place.

**Comment by BlackWindowS** [comment]
I'll try tomorrow. 
I've written this line in order to get rid of an addAction that was present but useless after a respawn.

**Comment by PabstMirror** [comment]
You may want to look at `CBA_fnc_addPlayerAction` which will add actions to the current player and re-add and cleanup after respawn or player switch.

**Comment by BlackWindowS** [comment]
Fixed by removing `removeAllActions player` !
Thank you all. You are really fast to read dirty code ! ^^
