### ISSUE TITLE
Create a sticky: recently changed strings

### ISSUE THREAD

**Issue by licht-im-Norden87** [acemod/ACE3#3503]
Since some english strings change over time for various reasons (adding new information or completely rewritten because of code changes)  it would be useful to have a sticky (just like translation) to inform everyone about it. Otherwise strings in another languages are going to be outdated and maybe misleading soon.

For example:
(as a table but I dont know how to make one in github)
02.03.2016  medical TR_ACE_Medical_Injuries  german ( [ ] ) russian (- [ ] ) .....

string updated: 
02.03.2016  medical TR_ACE_Medical_Injuries  german ( [x] ) russian ( [x] ) .....

**Comment by esteldunedain** [comment]
Policy is to delete all translations if you change the english entry. I think that's the better solution, and we should still keep it.

**Comment by jonpas** [comment]
I agree with @esteldunedain

**Comment by licht-im-Norden87** [comment]
Unfortunatly this was not always the case. But @esteldunedain is right.

**Comment by esteldunedain** [comment]
> Unfortunatly this was not always the case.

Yeah, we should be extra careful with that
