### ISSUE TITLE
Digging units RHS.

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#3505]
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHSAFRF`

**Description:**
- Add the ability to units of RHS to dig by shovels which are fixed in their vests without adding it to units inventory. [image 1](http://images.akamai.steamusercontent.com/ugc/317873200917995684/FE32FE01F06B154416C3CB9CDA894842A947AC5C/) [image 2](http://images.akamai.steamusercontent.com/ugc/317873200917996021/AA3397E87DB3EC09A2B6FB1992F4D5D462BC9693/)

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- 'None'.

**Comment by jokoho48** [comment]
#414

**Comment by GalNa** [comment]
Absurdity when one shovel in his hand, and another on the back.

**Comment by jonpas** [comment]
@GalNa those are baked into the uniform it seems, nothing we can do about it.
