### ISSUE TITLE
Is Battleye blocking ace_break_line.dll?

### ISSUE THREAD

**Issue by Radeni** [acemod/ACE3#3512]
I noticed errors and crashes with Break Line.dll i know that you guys said that some new dlls were added so they will probably be blocked by battleye till they get whitelisted.Is this the situation with ace_break_line.dll because it says that its not installed even tho its there.

**Comment by esteldunedain** [comment]
It might be Battleye or your antivirus. Please try without the later and verify the file is still where it's supposed to be.

**Comment by xZaniity** [comment]
Having the same issue.
https://gyazo.com/a8f81b7a886827aa504b5b994e110c99.jpg

**Comment by Glowbal** [comment]
All our dlls will have to be whitelisted by BattleEye again.

**Comment by Radeni** [comment]
Yep,thats what i tought.I dont use any antivirus so it must be BattlEye

**Comment by agorapolis** [comment]
I have the same problem...
I wanted to put the old version and also blocks BattlEye dll from the old version

**Comment by Astavinu** [comment]
> I wanted to put the old version and also blocks BattlEye dll from the old version
confirmed

**Comment by esteldunedain** [comment]
> I wanted to put the old version and also blocks BattlEye dll from the old version

That's weird. Well, let's hope they whitelist it soon.

**Comment by dvdbrewster** [comment]
Me too, see 12:14 approx.  Servers start ok (jest max ai).   


https://www.dropbox.com/s/motx7cyh2s3ub25/arma3_2016-03-02_12-11-40.rpt?dl=0

**Comment by jonpas** [comment]
https://twitter.com/ACE3Mod/status/705128911051628544

**Comment by BrianPothoven** [comment]
I had it aswell, I solved it by disableing Battleye, and then verifying my game cache

**Comment by agorapolis** [comment]
The new version works for a few minutes. BattlEye no longer crashes the DLL

**Comment by PabstMirror** [comment]
BE seems to have updated in the last few hours, working fine now
