### ISSUE TITLE
Can't open ACE Menu on map.

### ISSUE THREAD

**Issue by JasperRab** [acemod/ACE3#3514]
**Arma 3 Version:** `1.56`
**CBA Version:** `2.3.0.160217-c478cf23`
**ACE3 Version:** `3.5.0.0-e2c75762`

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Cant use ACE self interaction menu when on the map, to open maptools and ect.

**Steps to reproduce:**
Go to Editor open virtual world, place unit. 
Go in game. 
spawn in maptools. 
Try to open menu on the map.

**Where did the issue occur?**
Dedicated / Self-Hosted Multiplayer / Singleplayer / Virtual Arsenal

**Placed Modules:**
NONE

**RPT log file:**
http://pastebin.com/mVx30XGH

**Comment by jonpas** [comment]
Use CBA v2.3.1 and report back please.

**Comment by JasperRab** [comment]
Fixed. Thanks.
