### ISSUE TITLE
UH1Y RHS Fastroping

### ISSUE THREAD

**Issue by PunkyPL** [acemod/ACE3#3519]
**Arma 3 Version:** `1.56` 
**CBA Version:** `2.3.1` 
**ACE3 Version:** `3.5.0` 

**Mods:**
- `@CBA_A3`
- `@ace`
-@RHS AFRF
-@RHS USAF

**Description:**
- Reappeling by the rope from UH1Y from RHS MOD cause  damage to main rotor and stoping it.

**Steps to reproduce:**
SPAWN UH1Y FROM RHS MOD
GET in ad passeneger
in the 20 drop ropes
crash like russian su in syria 3months ago

**Where did the issue occur?**
- Dedicated /  Editor (Singleplayer) / Editor (Multiplayer) 

**Placed Modules:**
Ace Medical modules
TFAR radio module

**Comment by esteldunedain** [comment]
The compat pbo for RHS is not ready for fast roping yet.

**Comment by PunkyPL** [comment]
Right! but if you fastroping from UH-60 from RHS, ewerything will work fine.

**Comment by esteldunedain** [comment]
Sure, it's hit and miss at the moment, cause those choppers are not correctly configured.

**Comment by commy2** [comment]
>The compat pbo for RHS is not ready for fast roping yet.

This means that behaviour is undefined. Some might work, others might not.

**Comment by PunkyPL** [comment]
Thanks for fast reply, guys!

**Comment by jonpas** [comment]
Will be fixed with #3495

**Comment by esteldunedain** [comment]
Fixed in #3495
