### ISSUE TITLE
Question: FRIES in zeus/FRIES var?

### ISSUE THREAD

**Issue by RSpeekenbrink** [acemod/ACE3#3523]
Hello,
My question is: Is it possible to make a helicopter use the fastrope system if you put it down trough zeus?

And is there a var you can add to helicopters to enable FRIES?

**Comment by BaerMitUmlaut** [comment]
A Zeus module is planned but not available yet.
For equipping a helicopter with a FRIES, you can execute the following serverside:
```[_vehicle] call ace_fastroping_fnc_equipFRIES```
With `_vehicle` being the helicopter. Note that this is not public API (yet), so it might change with a future release.

**Comment by JHill29th** [comment]
in `init.sqf` add:
```
{
	addFRIES = _x addEventHandler ["CuratorObjectPlaced", {
		_entity = _this select 1;
		if (_entity isKindOf "Helicopter") then {
			[_entity] call ace_fastroping_fnc_equipFRIES;
		};
	}];
} forEach allCurators;
```

**Comment by RSpeekenbrink** [comment]
Thanks guys, didn't know there was a fnc for it in that way. This is very usefull!
