### ISSUE TITLE
Flying howitzer

### ISSUE THREAD

**Issue by AtomMrav** [acemod/ACE3#3528]
Arma 3 v.1.56.134787
CBA3 v. 2.3.1.160220
ACE3 v. 3.5.0
RHS Escalation v. 0.4.0.1

Mods:
- @CBA_A3
- @ace
- @rhsusf
- @rhsafrf

Description:
I have placed rhs M119 howitzer and tried to drag it or carry it, and when I select that option, suddenly, i fly in the air.

Steps to reproduce:
- add rhs M119 howitzer in the eden in VR map
- try to drag it or carry it

 [YouTbe link](https://youtu.be/SoKg1vJfb94)

**Comment by PabstMirror** [comment]
I think I remember something similar with the old explosives system.  I'm guessing the attached vehicle is too close to the player so physX goes nuts.

M119 is also about 2 tons, so I'm not sure if we should allow dragging on it.

**Comment by AtomMrav** [comment]
Some time ago, I used samo script for dragging, and i remember that I used ofset [0,0,5].
Yes, it is heavy, but that is only way to move it. My opinion is that You should leave option to drag it.
Or, maybe, to make option to attach it at the back of the truck. You can fold it, and tow it
