### ISSUE TITLE
Grunt Phone for Tanks 

### ISSUE THREAD

**Issue by Seth0351** [acemod/ACE3#3531]
**Arma 3 Version:** `1.56` (stable / rc / dev)
**CBA Version:** `2.3.1` (stable / dev + commit hash)
**ACE3 Version:** `3.5.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Feature request, Infantry can acces tank comms via grunt phone on the back of tanks. 
see:
https://farm1.staticflickr.com/738/21116704365_897c4795ab_o.jpg

If this isn't in the correct area sorry!

**Comment by bux578** [comment]
Sorry, but this is not something for the scope of ACE3. It would better fit into ACRE2 or TFAR.
