### ISSUE TITLE
ace_captives: AI placed in editor cannot be setHandcuffed on Dedicated.

### ISSUE THREAD

**Issue by OriginalHoozin** [acemod/ACE3#3532]
**Arma 3 Version:** `1.56.134627` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- setHandcuffed module, checkbox, and init code (`[this,true] call ace_captives_fnc_setHandcuffed`) do not set a unit to be handcuffed in multiplayer.  Dropping "Toggle Captive" module on units via Zeus does not cause them to become handcuffed.  Executing `ace_captive_fnc_setHandcuffed` on a unit via console, even globally, does not cause the unit to become handcuffed.  Unit also cannot be arrested with a cable tie, though the option does show up and one is removed (`_unit getVariable ["ace_captives_isHandcuffed",false]` returns `false`).

- A unit spawned via Zeus can be handcuffed via script or Zeus module.

**Steps to reproduce:**
- [Example PBO Attached.](https://github.com/acemod/ACE3/files/158083/handcufftest2.VR.pbo.zip)  Requires Dedicated environment.

1. Place unit.
2. Set Handcuffed via checkbox attribute, synced module, or init code
3. View unit in dedicated multiplayer.  Unit is not handcuffed.  Unit cannot be handcuffed.

**Where did the issue occur?**
- Dedicated (AI on Server)

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- [RPT File](https://gist.github.com/OriginalHoozin/79b62ab548c5d85687f7)
- [ACE Debug Info](https://gist.github.com/OriginalHoozin/3299ca2e67b8dc6aa9d5)

**Comment by Theowningone** [comment]
Not an expert, but if it helps someone with the tool set fix it, here's what I found:

My best guess is that the code block [here](https://github.com/acemod/ACE3/blob/master/addons/captives/XEH_postInit.sqf#L37) is after a `if (!hasInterface) exitWith {};` on line 31, therefore causing `ace_captives_captivityEnabled` to never be set to true.

**Comment by danjoo4** [comment]
So unfortunate, my clan had an OP for tonight that needs this feature :(

The dedicated AI is also broken if spawned in via a script. whether it be on init, initserver, or a custom one.
e.g.
```
_civ = creategroup EAST;
prisoner = _civ createunit ["C_man_polo_1_F", getmarkerpos rendevouz, [], 0, "CAN COLLIDE"];
prisoner setbehaviour "CARELESS";
prisoner allowdamage false;
[prisoner, true] call ACE_captives_fnc_setHandcuffed;
```

**Comment by esteldunedain** [comment]
@Theowningone, I think you're right, that's most likely the cause.
