### ISSUE TITLE
Addon 'ace_rhusf_c_weapons_comp' requires addon 'rhsusf_c_weapons'

### ISSUE THREAD

**Issue by Matchek79** [acemod/ACE3#3535]
**Arma 3 Version:** `1.56.134627` Dedicated Server Windows (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.0` (stable)
**RHS Verion:**`0.9.8` (stable)

**Mods:**
- `@CBA_A3`
- `@RHSAFRF`
- `@RHSUSAF3`
- `@ace`

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- copy those files from @ace/optionals to @ace/addons:
    ace_compat_rhs_afrf3.pbo
    ace_compat_rhs_afrf3.pbo.ace_3.5.0.0-e2c75762.bisign
    ace_compat_rhs_usf3.pbo
    ace_compat_rhs_usf3.pbo.ace_3.5.0.0-e2c75762.bisign
and start windows dedicated server.

**Where did the issue occur?**
- when starting server new window occure with Addon 'ace_rhusf_c_weapons_comp' requires addon 'rhsusf_c_weapons', when I click ok server starts.

**Placed Modules:**
- none

**RPT log file:**

```
...
14:14:41 Unsupported language English in stringtable
14:14:43 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'rhsusf_c_weapons'
14:14:45 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'rhsusf_c_troops'
14:14:45 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'rhsusf_c_m1a1'
14:14:45 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'rhsusf_c_m1a2'
14:14:45 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'RHS_US_A2_AirImport'
14:14:45 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'rhsusf_c_m109'
14:14:45 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'rhsusf_c_hmmwv'
14:14:45 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'rhsusf_c_rg33'
14:14:45 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'rhsusf_c_fmtv'
14:14:45 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'rhsusf_c_m113'
14:14:45 Warning Message: Addon 'ace_rhsusf_c_weapons_comp' requires addon 'RHS_US_A2Port_Armor'
14:14:45 Updating base class ->Base, by a3\dubbing_radio_f\config.bin/CfgHQIdentities/PAPA_BEAR/...
```

**Comment by gienkov** [comment]
Check your RHS installation. I can't repro this and it works fine for us.

**Comment by Matchek79** [comment]
I have latest version of rhs, but checked 5 min ago and still got this warrning

**Comment by PabstMirror** [comment]
Can you please upload full rpt to https://gist.github.com/ or pastebin

**Comment by Matchek79** [comment]
http://pastebin.com/9Cp0mjE4

**Comment by PabstMirror** [comment]
```
@RHSUSF |      false |            NOT FOUND |                                          |           |
@RHSAFRF |      false |             GAME DIR | 6e7688c7476e1fbe5fe80a6f331a0b419997256b |  61e1e67d | C:\Games\Arma3\@RHSAFRF
```

It's not finding `@RHSUSF`, and not loading any of the RHS-US mod pbos.
Check the name it might be `@RHSUSAF`

**Comment by AtomMrav** [comment]
You need these files on client machines, and on server machine in ace3/addons folder.
