### ISSUE TITLE
TODO createVehicle -> createSimpleObject

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#3537]
`createSimpleObject` saves on performance for non-simulated objects and could probably used for a few modules.
- [ ] Tagging (tags)
- [x] Medical (litter)

**Comment by PabstMirror** [comment]
Ref https://forums.bistudio.com/topic/187670-new-command-createobject-for-decorative-objects/

For medical we need to compare synced `createVehicleLocal` with the new command.

You can actually take physX damage from bandages if they are spawned funny, so this probably is a good thing to look at.

**Comment by commy2** [comment]
>You can actually take physX damage from bandages if they are spawned funny, so this probably is a good thing to look at.

Maybe could also be used for all those cases where trying to place bomb while being to near the vehicle makes it flip?

**Comment by PabstMirror** [comment]
Explosives are now virtual and local only (it's just a fake 3d element on your hud).

Being local also means less network traffic (I think old system was setPos each frame)

**Comment by esteldunedain** [comment]
> Being local also means less network traffic (I think old system was setPos each frame)

The old plcamente system used `createVehicleLocal`, so it didn't generate network traffic either. The new system is better though, because the virtual object doesn't collide with the objects.

**Comment by esteldunedain** [comment]
So in short; @commy2 that bug you describe has been fixed for a long time now.

**Comment by bux578** [comment]
@BaerMitUmlaut Status?

**Comment by Glowbal** [comment]
Does `createObject` have local effect?

**Comment by bux578** [comment]
[`createSimpleObject`](https://community.bistudio.com/wiki/createSimpleObject)

**Comment by Glowbal** [comment]
In that case it's not a simple switch  / replace for medical litter. We allow clients to independantly define how many litter objects can exist at any given time and for how long they can stay alive. Using a global variant will mean this would no longer be managed by clients, but the server instead.

**Comment by esteldunedain** [comment]
I think tagging is the only trivial case to implement

**Comment by bux578** [comment]
Having the setting for each client seems unnecessary complicated. `createSimpleObject` should solve performance issues.

**Comment by commy2** [comment]
^ I think we would be better off if the server created and deleted litter, even if it means the client settings about litter would have to be removed / would do nothing anymore on clients.
