### ISSUE TITLE
Replace execRemoteFnc with globalEvent and reduce to every 1s in refuel

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#3541]
```
[ACE] (common) WARNING: ace_common_fnc_execRemoteFnc is deprecated. Support will be dropped in version 3.7.0. Replaced by: ace_common_fnc_globalEvent
```

Possibly in other places as well, but refule is priority because it's a bunch of events in quick succession during refueling.

If possible, also make the globalEvent be triggered every 1 second only, to reduce network spam.

Tagging @GitHawk

**Comment by esteldunedain** [comment]
:+1: for increasing the delay between updates to 1~2 secs
