### ISSUE TITLE
Indfor pilot has no fitting ammo

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#3545]
**Arma 3 Version:** `1.56` stable
**CBA Version:** `2.3.1` stable
**ACE3 Version:** `3.5.0` dev 721aa94 (current master)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
`I_Pilot_F` has no fitting ammo for his CPW. He only has tracer mags, but the CPW does not take tracer mags. The cause is probably this:
https://github.com/acemod/ACE3/blob/825b410ae87d421db93c37f68215a2b74d0b8cc0/addons/smallarms/CfgWeapons.hpp#L180

**Steps to reproduce:**
- Place an AAF pilot
- Hit preview
- Try to shoot

**Where did the issue occur?**
- Editor

**Placed Modules:**
- None

**RPT log file:**
- Should not be needed, will be added on request.

**Comment by commy2** [comment]
This is an old ass fix that now no longer applies.
All of them (some pistols) now use these mags:
`magazines[] = {"30Rnd_9x21_Mag","30Rnd_9x21_Red_Mag","30Rnd_9x21_Yellow_Mag","30Rnd_9x21_Green_Mag","16Rnd_9x21_Mag","16Rnd_9x21_red_Mag","16Rnd_9x21_green_Mag","16Rnd_9x21_yellow_Mag"};`
