### ISSUE TITLE
ace_finger

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#3554]
**Arma 3 Version:** `1.56` (stable)
**ACE3 Version:** `3.5.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- If the commander is standing next to armored vehicles and points a finger at the goal marker crew did not see!

**Where did the issue occur?**
-  Editor (Multiplayer)

**Placed Modules:**
- ace_finger_moduleSettings

**RPT log file:**
- No

**Comment by esteldunedain** [comment]
It doesn't sound like a bug to me. I don't think tank crews would have enough visibility to be able to see where a nearby unit is pointing too.

I'm closing this for the moment. Feel free to explain the issue further and we may consider reopening it.

**Comment by Kartaviy** [comment]
The radius of the use module of 4 meters. In real life, too, sometimes suggest using infantry tanks. Shows the direction or where the enemy. That's why it was not bad and the crew saw to this effect at the monitor, too, without leaving the armored vehicles
