### ISSUE TITLE
Question: ACE_Medical_Treatments

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#3555]
i saw in your "ACE_Medical_Treatments.hpp " https://github.com/acemod/ACE3/blob/master/addons/medical/ACE_Medical_Treatments.hpp

some bandages are not completely defined, according to different types and sizes of wounds.
how do they work then? do they take the basic values defined in the basic class?

for example "class PackingBandadge" has no values for wound type "class punctureWoundMinor" (line:1057)
so does it take the values of "class punctureWound" instead, or how does it work?

**Comment by commy2** [comment]
`class punctureWoundMinor: punctureWound {};` means that `punctureWoundMinor` is a child class. It will inherit all config entries from it's parent class called `punctureWound`, unless they are overwritten with new values.

>so does it take the values of "class punctureWound" instead
Exactly.
