### ISSUE TITLE
Looking at map with NVG on

### ISSUE THREAD

**Issue by BlackHawkPL** [acemod/ACE3#3556]
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Looking at map while wearing NVG doesn't improve it's readibility. Either add green light effect or something looking like flashlight with green light to simulate using nvg.

**Steps to reproduce:**
- Night. NVG. Map.

**Where did the issue occur?**
- everywhere

**Placed Modules:**
- none

**RPT log file:**
- http://pastebin.com/R2jKHzQM

**Comment by bux578** [comment]
You can't read maps with the common infantryman NVG's IRL. They are out of focus because they are too close.

**Comment by BlackHawkPL** [comment]
Is it possible to blur it out to give player feedback that it's by design not a bug?

**Comment by bux578** [comment]
I don't think this is possible due to engine limitations. But I could be wrong here.

**Comment by BlackHawkPL** [comment]
roger, you can close this issue.
