### ISSUE TITLE
Laser Guided missles affected by wind deflection (RHS artillery)

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#3558]
**Arma 3 Version:** 1.56 stable
**CBA Version:** `2.3.1
**ACE3 Version:** `3.5.0

**Mods:**
- `@CBA_A3`
- `@ace`
- RHS

**Description:**
All laser guided missles available on RHS artillery (akacya, palladin, static too) are affected by wind deflection (propably) - rounds are missing its targets on longer range, which can happen to HE rounds, smoke rounds, actually all rounds BUT NOT LG

**Steps to reproduce:**
- use artillery support with LG rounds, note there will be no akacya artillery available again after using LG rounds 

**Where did the issue occur?**
- Single player, EDEN

**Placed Modules:**
- NONE

Repro mission :
[Desert%20Warfare.Desert_E.zip](https://github.com/acemod/ACE3/files/161767/Desert.20Warfare.Desert_E.zip)

**Comment by esteldunedain** [comment]
We don't apply wind deflections to any round, unless it's fired by the player or vehicle player. 

This is most likely not related to ACE.

**Comment by vlad8011** [comment]
So, RHS closed this (unable to reproduce), your mod dont touch this, what may be the problem?

**Comment by esteldunedain** [comment]
I don't know, sorry.
