### ISSUE TITLE
enableVehicleCrashes and preventInstaDeath make you survive vehicle explosion

### ISSUE THREAD

**Issue by SzwedzikPL** [acemod/ACE3#3559]
**Arma 3 Version:** `1.56` (stable - hotfixed)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- enableVehicleCrashes + preventInstaDeath make you survive vehicle explosion

**Steps to reproduce:**
- https://www.youtube.com/watch?v=Kr7hocSjrxU (recorded on eden preview)
- https://www.dropbox.com/s/4868h6358t727xa/ace_medical_bug_repro.Stratis.zip?dl=0 (mission used to reproduce bug)

**Where did the issue occur?**
- SP / MP

**Placed Modules:**
- http://pastebin.com/EBffXhhx

**RPT log file:**
- rpt log is clear, no errors

**Comment by Radeni** [comment]
I posted the same issue not that long ago.Usually its only the driver that dies but everyone else is preety much ok

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 163 days without any activity.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
