### ISSUE TITLE
spelling error in fn_treatmentAdvanced_bandageLocal.sqf

### ISSUE THREAD

**Issue by Pergor** [acemod/ACE3#3565]
In https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatmentAdvanced_bandageLocal.sqf there's a variable "_woundEffectivenss". 
To avoid code errors (which don't occur so far) the correct spelling should be used: _woundEffectiveness

**Comment by esteldunedain** [comment]
Fortunately, the typo is applied consistently on the whole function, so no error should occur. The mispelling could be corrected as some point though.
