### ISSUE TITLE
BattleEye suddenly blocking ACE3 .dll files

### ISSUE THREAD

**Issue by ender2078** [acemod/ACE3#3570]
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable / dev + commit hash)
**ACE3 Version:** `3.5.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Battleye suddenly blocking ACE 3 .dll files making joining a server with ACE impossible.

**Steps to reproduce:**
- Launch Arma 3, join server with ACE3 modules placed. 

**Where did the issue occur?**
- on Editor and Dedicated Server.

**Placed Modules:**
- ACE 3 Modules, w/ advanced ballistics/medical.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

Here are the files being 
![untitled](https://cloud.githubusercontent.com/assets/17556136/13648862/bea42d44-e5ef-11e5-8740-8e616ff793e0.png)

**Comment by jokoho48** [comment]
> Battleye suddenly blocking ACE 3 .dll files making joining a server with ACE impossible.

that is not true just disable battleye and its run fine

**Comment by ender2078** [comment]
We are unable to change the Battleye = 1 config setting on our server, so yes it is true. Disabling Battleye is not a reasonable solution either.

**Comment by PabstMirror** [comment]
![image](https://cloud.githubusercontent.com/assets/9376747/13648894/a86e78f2-e600-11e5-876e-b222d6ecb345.png)

**Comment by ender2078** [comment]
Thanks @PabstMirror I get those messages so often I obviously overlooked it. Ill see why it is not updating.

**Comment by ender2078** [comment]
update for my personal experience, I got battleye to disable on our server finally. Wouldnt take the first two times I tried.

**Comment by rsvirus** [comment]
You can still work around this issue. Go to your ArmA 3 folder located in your Steam directory and Launch the arma3.exe  program. Run as Administrator if you have the option to do so. Go to your Main Menu > Configure > Expansions. You will see your all your current Mods. Just Enable and Disable the Mods You want or are required (Ace3) and join the server you want. It might ask you to Restart. If it does just select OK/Restart and It will restart your game and now you can join your favorite server. Hope this helps. Have Fun!
