### ISSUE TITLE
Reduce damage from the backblast RPG-7V2.

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#3571]
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHSAFRF`

**Description:**
- Reduce damage from the back blast RPG-7V2.  It cause loss of consciousness, when his back is more than 2 meters from the obstacle behind the shooting. But in the instructions it is written, that the shooter must be placed on fences, trees at a distance of 2 meters. After 2 meters from the fence, it should not cause such damage to the soldier, what we have in the current version of the add-on.
  https://youtu.be/zdIVtQNe1xw

**Steps to reproduce:**
- Take the RPG-7V2, to move away from the fence 3 meters and shoot. Watch wounds, which should not be.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- [Advanced Medical Settings](http://ace3mod.com/wiki/missionmaker/modules.html#advanced-medical-settings)

**Comment by GalNa** [comment]
https://youtu.be/Niz-TalxlY4

**Comment by vlad8011** [comment]
Practice not equal instruction allways, as you can see on this videos, its able to shot from buildings, i saw lot of videos from Ukraine crisis, where soldiers was shooting from even smaller rooms.

**Comment by mickeymen** [comment]
#2890 agree with the author.
I think, soldiers not should lose consciousness in general, even when the distance to walls < 2 m. 
Unit should receive not big damages and not more.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
