### ISSUE TITLE
windows defender detects malware in ace_fcs.dll

### ISSUE THREAD

**Issue by kripto202** [acemod/ACE3#3572]
OS: windows 10 (stable)
windows defender detects these malware files "Trojan:Win32/Spallowz.A!plock" 
Alert level: Severe

May need to be looked at to help prevent windows defender from kicking in and deleting this file.

**Comment by Loomie** [comment]
No other program finds any malicious code in that file:
https://www.virustotal.com/de/file/3c7766fb864c455e70dacd8257c8e5eb5f90ca635ea49089ba53615d689e1662/analysis/

**Comment by Tavish101** [comment]
Yep, can confirm Windows Defender flags ace_fcs.dll as a severe threat and quarantines it.

**Comment by bux578** [comment]
False Positive.
