### ISSUE TITLE
ACE 2 possibilities for Arma3

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#3574]
Почему не можете взять большую часть разработок, созданными бывшими разработчиками АСЕ2 и перенести их на АСЕ3? К примеру мой друг реализовал систему полету ПТРК, как это было сделано в АСЕ2.
И это не предел АСЕ3.
Если у вас нету этих файлов и они были утеряны. То можем предоставить полный пак файлов.

transl.

Why you can not take much of development, created by former developers ACE2 and transfer them to ACE3? For example, my friend realized the system ATGM flight, as was done in ACE2.

And this is not the limit ACE3.
If you do not have these files, and they were lost. That can provide a full pack files.

**Comment by vlad8011** [comment]
Maybe accuracy of guiding is too high on your video, but i would love to see something between current guiding accuracy and those from this video, it would be awesome.

**Comment by Kartaviy** [comment]
Settings flights were taken from Arma 2 ACE2

**Comment by licht-im-Norden87** [comment]
Unfortunalty you can not simply "convert" ACE2  features to ACE3 for various reasons.

**Comment by Kartaviy** [comment]
Well then, why we can do it and you do not? It's not easy, but possible.

**Comment by esteldunedain** [comment]
Properly porting ACE2 content to Arma 3 is no as trivial as you appear to think. Of course you can do a straight port easily, but a lot of thing would be half broken, including physics. That level of port is not acceptable by our standards.

ACE3 focus is currently on systems, and we may or may not address porting content in the future. If we do it we'll certainly do it the right way.

On a side note, you friend has no permission to mess around with ACE2 code or assets, so please don't do that.
