### ISSUE TITLE
Question: fries-module

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#3576]
how does the fries-module work?
i've placed an "mh-littlebird" on map, place the module and synced it with the helicopter. 
pressed "preview" and tried to prepare the ropes via ace interaction menu, while sitting in the passenger's seat.-no Option.

**Comment by esteldunedain** [comment]
I think the vanilla littlebird doesn't support FRIES, hence the problem. That is by design.

**Comment by kripto202** [comment]
@esteldunedain still didnt answer the first question. how does it work exactly? Who do i sync the module to. There is no documentation on the wiki about it on how to set it up.

**Comment by bux578** [comment]
Don't revive closed tickets. If you have a question please post it on the forum or join our public chat.
