### ISSUE TITLE
Morphines increase blood pressure in advanced mode

### ISSUE THREAD

**Issue by grester** [acemod/ACE3#3579]
**Arma 3 Version:** `1.56` (stable + hotfix)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Either the wiki is outdated or the morphines have a bug. According to the wiki, morphines decrease both heart rate and blood pressure on advanced mode, however in pratice they lower heart rate but increase blood pressure.
PS: Not sure if ACE log is complete as the game crashed when I debug to clipboard.

**Steps to reproduce:**
- Setup a mission with ACE medical advanced settings enabled, check both pulse and blood pressure of a test subject
- Inject a morphine to the same test subject and watch pulse lower but blood pressre increase.

**Where did the issue occur?**
- Tested on Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- Medical Settings [ACE]
- Advanced Medical Settings [ACE]

**RPT log file:**
- [RPT Log](http://pastebin.com/rejsvvC4)
- [ACE Debug](http://pastebin.com/xwFTSzuM)

**Comment by Glowbal** [comment]
Thanks, seems we forgot a minus somewhere. Easy fix, will make it in with 3.5.1.

**Comment by Raptor6Actual** [comment]
The only thing MS does to pressure, is increase it in the cerebral area. It is an opiod analgesic, and therefore has side effects of lowering heart rate and therefore blood pressure. I don't know where you are getting your medical advice from, but Glowbal was foolish to kick some of his previous CMS advisors out of the project. 

Reference: http://www.drugs.com/pro/morphine-sulfate.html

Hypotensive Effect
Morphine Sulfate may cause severe hypotension in an individual whose ability to maintain blood pressure has already been compromised by a depleted blood volume or concurrent administration of drugs such as phenothiazines or general anesthetics. Morphine Sulfate may produce orthostatic hypotension and syncope in ambulatory patients.

Administer Morphine Sulfate with caution to patients in circulatory shock, as vasodilation produced by the drug may further reduce cardiac output and blood pressure.

**Comment by LtRyan** [comment]
What? How can it raise BP and lower HR, is completely unrealistic!
Wiki is in this case right...
