### ISSUE TITLE
Hit-Reaction/Ragdoll they are now worse, after the lates updates/

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#3582]
**Arma 3 Version:** 1.56.134787 stable
**CBA Version:** 2.3.1
**ACE3 Version:** 3.5.0

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
I always liked hit-reactions and improved ragdoll effects, which were in ACE3. But in recent updates it was removed or broken. Therefore, the user again sees the ugly vanilla animations of hits and ragdoll. Something like this:
http://www.youtube.com/watch?v=TQ8TdKuAAeQ
http://www.youtube.com/watch?v=4mNXoB-eebs

The most ugly animation happens, when the unit get hit in a crouch stance.
I don't know what happened. Probably it happened without your desire? I'm not sure.
Please return hit-reactions, which were in previous versions.
Now the player sees the same thing as in vanilla game.

Additioanal info: 
The problem is complicated, when the player sees the hit-reaction before unit will become unconscious.
I reported this before,  #2485  but as I understand, it can't be fixed.
This animation in АСЕ3 also looks ugly, thus the eyes of the player gets a double kick. Please fix at least a one problem, when I see this shit, I not want play more in ACE3/

Or tell me how the player can return old hit reactions and ragdoll effects by yourself?

**Steps to reproduce:**
Open editor and place two opposite squads.
Watch the fight carefully.

**Where did the issue occur?**
Editor

**Placed Modules:**
None

**RPT log file:**
Not needed

**Comment by mickeymen** [comment]
If anyone else has noticed this as well, please confirm

**Comment by commy2** [comment]
ragdolls tweaks were removed in favor of the reworked ones from 1.54 vanilla and are no longer part of ACE.
Close?

**Comment by mickeymen** [comment]
Why have been removed? Can't you see, that the vanilla effects look disgusting?
How can I restore the old tweaks?

**Comment by Glowbal** [comment]
Hi @mickeymen, we have explained you the problem before in detail. We are not able to properly apply ragdoll to the standards that we would like and therefor we are stuck with the solution we have in place at the moment. If you have a solution that works better, please send it to us. 

In the meantime, I'd like to ask you to try and moderate your enthusiasm about the issues you reported. We like to help and solve problems, but your wording makes it less enjoyable for us.

Thanks in advance.

**Comment by mickeymen** [comment]
@Glowbal

> we have explained you the problem before in detail

Nobody explained anything to me. At first, I was just put before the fact. What details are you saying I don't understand. 

I created more than a dozen issues, and each of them was closed, without any progress.
I see the same - closed, closed, closed...
Every problem you name is not solvable, for one reason or another. I have the impression that you either don't know how to do anything in your mod or don't want do this. Sad to me/

> I'd like to ask you to try and moderate your enthusiasm

I can't, because enthusiasm is my engine. It's even your engine also;)

**Comment by Glowbal** [comment]
@commy2 has explained why on the issue you linked (#2485). To summarize; there are no script commands available to interact with the RV engine in regards to ragdoll. We agree that the current unconscious animations are not ideal, but we are not able to create new animations for the unconscious state at this time. 
For this reason, we are stuck with the current solution until someone either provides us with a better alternative or BI povides us with the ragdoll script commands. You are able to read all this and more in the above mentioned issue.

**Comment by mickeymen** [comment]
Thank you for your answers. @Glowbal, your answers are always more meaningful. 
Excuse me if something is wrong, anyway I deeply appreciate your work. Without ACE3 Arma3 becomes pale for me
