### ISSUE TITLE
Artillery no has voice request (appear error message)

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#3587]
Arma 3 Version: 1.56.134787 stable
CBA Version: 2.3.1
ACE3 Version: 3.5.0

Mods:

@CBA_A3
@ace
@DragonFyre

Description:
When in my mission I try use artillery support via action menu(0-8), the voice of the player character (requesting support) is missing and during this moment appear error massage:

 "Error in expression <Artillery_Destroyed", BIS_SUPP_channels select ([WEST, EAST, RESISTANCE] find si"

I tried to reproduce the problem without the my mission, using only 2 units, (player as commander and mortar-gunner) but then the error message was not. However, voice of player still no exist. 

Steps to reproduce:
Use Artillery support

Where did the issue occur?
Editor

Placed Modules:
Advanced and Basic Medical

RPT log file:
https://yadi.sk/d/WEpbl7CFqBQgW

**Comment by esteldunedain** [comment]
@commy2:

```

**Comment by commy2** [comment]
I can't even use the module in vanilla. I get this error
```
 9:50:48 Error in expression <upports"};

[] spawn {
sleep 1;
{(group _x) setGroupID [localize "STR_A3_cfgmark>
 9:50:48   Error position: <_x) setGroupID [localize "STR_A3_cfgmark>
 9:50:48   Error Undefined variable in expression: _x
 9:50:48 File A3\modules_f\supports\init_common.sqf, line 31
```

**Comment by commy2** [comment]
Can you upload a repo mission, @mickeymen ? I can't get this module to work at all.

**Comment by mickeymen** [comment]
> Can you upload a repro mission, @mickeymen ? I can't get this module to work at all.

I don't clearly understand you. You say that you have this module doesn't work at all!? It is strange to me, because I have the module working, but with the lack of voice of player character and sometimes with error messages.

Reproduce:
Place in the map player as rifleman
Place in the map Mk6 mortar unit (Turrets/Mk6 Mortar)
Place in the map module - Support Provider: Artillery
Place in the map module - Support Requester
Connect them (I think you don't need to explain how it's done)

Give the order to attack a specific point. Mortar gunner will be attack.
But when the player will indicate where to attack, the gunner would say - "Be adviced  artillery is not responding" Why this appear? I do not have assumptions. 
Also error messages not will appears/  The message appears only in the my mission itself.
Before update 3.5.0. I had no problems with it

**Comment by mickeymen** [comment]
This error not ACE! This is error only Eden editor! 
I spent some time on tests without ACE. 
If player use EDEN editor then problems are present!
If player use 2D editor, then all works perfrctly. Thus this is BIS fault

**Comment by mickeymen** [comment]
Don't rush to bury this ticket. Maybe the ACE team can fix this problem in Eden editor?

**Comment by esteldunedain** [comment]
> Maybe the ACE team can fix this problem in Eden editor?

We won't. Report it to BIS.

**Comment by mickeymen** [comment]
Sad to me( but I will try

**Comment by commy2** [comment]
Can confirm. The module does work for me in 2D editor.
We can't fix that unfortunately.

**Comment by mickeymen** [comment]
Please support my ticket here 
https://forums.bistudio.com/topic/189134-eden-artillery-support-modules-no-works-properly/
