### ISSUE TITLE
At using Morphine appear error messages

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#3588]
Arma 3 Version: 1.56.134787 stable
CBA Version: 2.3.1
ACE3 Version: 3.5.0

**Mods:**
@CBA_A3
@ace
@DragonFyre

**Description:**
At using Morphine appear diferent error messages.

**Steps to reproduce:**
Not sure exact. Sometimes messages don't appear.

**Where did the issue occur?**
Editor

**Placed Modules:**
Advanced and Basic Medical

**RPT log file:**
https://yadi.sk/d/oKaRO_hKqBTCa

**Comment by PabstMirror** [comment]
Will be fixed in 3.5.1 via #3527

**Comment by mickeymen** [comment]
thanks
