### ISSUE TITLE
Function to return the light level on a position

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#359]
https://github.com/KoffeinFlummi/ACE3/blob/master/addons/map/functions/fnc_determineMapLight.sqf#L70

https://github.com/KoffeinFlummi/ACE3/blob/master/addons/common/functions/fnc_cachedCall.sqf
https://github.com/KoffeinFlummi/ACE3/blob/master/addons/map/functions/fnc_updateMapEffects.sqf#L24

**Comment by commy2** [comment]
done in https://github.com/acemod/ACE3/pull/377

**Comment by esteldunedain** [comment]
:+1: Excellent
