### ISSUE TITLE
Interaction menu cannot close/perform actions

### ISSUE THREAD

**Issue by KuriharaCR** [acemod/ACE3#3590]
**Arma 3 Version:** `1.56` stable
**CBA Version:** `2.3.1` stable 
**ACE3 Version:** `3.5.0` stable

**Mods:**
- `@CBA_A3`
- `@ace`
- `@Altis_Guerrilla_Wafrace`
- `@Ares`
- `CUP Terrains/Units/Vehicles`
- `@MCC Sandbox 4`
- `@Kunduz Afghanistan`

**Description:**
After pressing the default interaction key (Windows) the menu appears and cannot be closed. No actions can be performed either.

This only happens after creating a scenario in the 3D editor, if a scenario is made in the 2D editor the menu works as intended.

**Steps to reproduce:**
Go into the 3D editor, export to singleplayer or multiplayer 
Play the created scenario
Hold interaction key

**Where did the issue occur?**
Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) 

**Placed Modules:**
None

**RPT log file:**
- http://pastebin.com/Ze8f5x6Y
- http://pastebin.com/QQ6EHyL7

**Comment by commy2** [comment]
Retry again with only `@CBA_A3` and `@ace`
We also need the .rpt file, which can be found here:
`%LOCALAPPDATA%/Arma 3` (the newest file right after closing the game)

**Comment by KuriharaCR** [comment]
Here is with only `@CBA_A3` and `@ace`

**RTP:**
https://gist.github.com/KuriharaCR/c59a0921ca4128627e07

**Ace debug:**
http://pastebin.com/Z8XgztNi


It worked with only `@CBA_A3` and `@ace` running, tested on Altis.
I can assume it's a conflict with another mod then.

**Comment by commy2** [comment]
Most likely. Or the mission was made when 3den was broken. Would be super helpful if you could figure out what mod exactly causes this conflict.

**Comment by KuriharaCR** [comment]
I loaded each mod separately and tested each time, works just fine.

Cannot reproduce now, only appears on two previous scenarios I made.
Unless it's some kind of single item I placed down in the editor that causes it I am lost for what triggers it.

**Comment by commy2** [comment]
OK. I'm closing this then. Feel free to open a new issue if the problem persists or the exact cause is found. Keep in mind that the 3den editor had serious problems when it was first released and missions created with it keep having certain bugs.
