### ISSUE TITLE
AI of ACE3 not able avoid mines, if with mine detector. [Repro-Mission]

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#3598]
Arma 3 Version: 1.56.134787 stable
CBA Version: 2.3.1
ACE3 Version: 3.5.0

Mods:

@CBA_A3
@ace
@DragonFyre

Description:

Hi-ACE team! My friends I really appreciate the ACE3 mod, but each time I make sure the AI in this mod was completely destroyed!  In the ACE description, the AI-features are located in the chapter - "Realism" All please watch this: http://ace3mod.com/wiki/feature/
Please tell me what is real?

1. The AI is not able to treat self or other, activate, deactivate a mine 
https://github.com/acemod/ACE3/issues/2506#issuecomment-142511654

2. The AI is not able to report about his own injury
https://github.com/acemod/ACE3/issues/2786#issuecomment-151565244

3. The AI doesn't react to the near explosion (not switch to danger mode)
https://github.com/acemod/ACE3/issues/2654#issuecomment-144384923

4. And now I detected. AI not able avoid mines, if in the squad present detector!
This is without a doubt, I ran tests with ACE and without it. 

At BIS the all this points works!

Offer simple repro-mission:
 https://yadi.sk/d/UfJCXbbmqJi22
Note. Unit with the detector(commander) reports about a mine, However the group is not trying to bypass a dangerous site. My tests showed that from 12 tests 12 times the AI exploded at a detected mine.
As soon as I disable ACE mod, the AI bypasses mines

Most likely You will not fix bugs related to artificial intelligence.and so I have 2 questions: 
1) How can I return the vanilla AI? What files should be removed without subsequent problems for the ACE3 mod?
2) Can I use other AI mods along with ACE3, without negative consequences?

PS: Please in the ACE description of  AI-features to remove the word "Realism" because this is not fair and at least vanilla AI looks much more realistic. 
Thanks...

Steps to reproduce:
Play my repro with ACE and without ACE

Where did the issue occur?
Editor

Placed Modules:
None

RPT log file:
Not needed

**Comment by commy2** [comment]
>How can I return the vanilla AI? What files should be removed without subsequent problems for the ACE3 mod?
`ace_medial.pbo`, `ace_medical_menu.pbo` and `ace_explosives.pbo`

>Can I use other AI mods along with ACE3, without negative consequences?
Yes.

**Comment by mickeymen** [comment]
ok, thanks

**Comment by mickeymen** [comment]
But there is a way to save ACE -medicine and to remove ACE-AI?

**Comment by BaerMitUmlaut** [comment]
No.

**Comment by mickeymen** [comment]
Ok. Please tell me. I can use this Vcom AI mod with ACE3 mod without conflicts? May be someone had such experience.
Vcom mod here http://www.armaholic.com/page.php?id=25381

**Comment by BaerMitUmlaut** [comment]
Commy has already told you.

**Comment by mickeymen** [comment]
ok/ I ask because this is a complicated mod

**Comment by mickeymen** [comment]
thanks for your answers;)

**Comment by mickeymen** [comment]
@commy2 to disable the ACE AI you advise to remove ace_medical.pbo, ace_medical_menu.pbo and ace_explosives.pbo files/ However, you don't remember about - ace_ai.pbo

Your answer seems weird to me

**Comment by commy2** [comment]
ace_ai.pbo has nothing to do with how AI handles explosives or first aid kits.

**Comment by mickeymen** [comment]
@commy Before I asked you - " How can I return the vanilla AI? What files should be removed without subsequent problems for the ACE3 mod?" 
 
This means I wanted to remove any additional AI, that was added by ACE team to vanilla game.
Not only AI-explosives and AI-medical.

**Comment by mickeymen** [comment]
Also I could not find a decent AI mod. This is a big disappointment for me( 
ACE is the best mod, but the AI in it is bad

**Comment by commy2** [comment]
Then remove `ace_ai.pbo` as well. It won't bring back AI treating itself or dealing with mines however, because that has nothing to do with `ace_ai.pbo` at all.
