### ISSUE TITLE
Question: fries

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#3603]
how do i set the angle of the FRIES - Gantry?
it's said, that i have to manipulate the initPhase.
how do i do that in particular?

**Comment by esteldunedain** [comment]
@BaerMitUmlaut?

**Comment by BaerMitUmlaut** [comment]
Make a class that inherits from `ACE_friesGantry` and tweak the `rotateGantryLeft` and `rotateGantryLeft` animation sources. I'd recommend checking the config for the reverse gantry as an example for what I mean:
https://github.com/acemod/ACE3/blob/master/addons/fastroping/CfgVehicles.hpp#L128
If you need further help let me know.

**Comment by madpat3** [comment]
well,
first i have to say i know very Little about modding and config writing. but i try.
i edited the config of aplion's ec635 to make it fries compatible. but it doesn't work. no idea how to do that.
edited lines:
4362 until 4439
4487 until 4510
http://pastebin.com/3BCKgR1B

**Comment by madpat3** [comment]
i figured it out by myself,
thank you for your help. and thank you for this great mod. 
you guys do an incredible Job on this.

**Comment by bux578** [comment]
Thanks, glad you like it.

**Comment by BaerMitUmlaut** [comment]
Sorry, I forgot to reply! But :+1: on figuring it out.
