### ISSUE TITLE
There is no method to find values for rifles (muzzle length, bullet coeficient, rifle twist, ect) to input into the AtragMX

### ISSUE THREAD

**Issue by enderrrrrrrrrr** [acemod/ACE3#3604]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `stable` (stable / dev + commit hash)
**ACE3 Version:** `stable` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
In order to correctly input information for the AtragMX on guns outside of the normal information on the gun is necessary. There appears to be no way to gather that information.

**Steps to reproduce:**
Attempt to add a gun to the gunlist.

**Where did the issue occur?**
all

**Placed Modules:**
advanced ballistics

**RPT log file:**

**Comment by esteldunedain** [comment]
The way  @ulteq/Ruthberg designed it is to look for that information from real life sources, and verify it in game in a shooting range.

We might want to change this at some point, but there are no inmediate plans for that.

**Comment by enderrrrrrrrrr** [comment]
Roger that. My one worry is that the accuracy of the data inputed for
different rifles will not necessarily be comparable to real world.

**Comment by madpat3** [comment]
you could look it up in the weapon's config.cpp/bin.?

**Comment by enderrrrrrrrrr** [comment]
Ok thanks, will do that i guess.

**Comment by ulteq** [comment]
You can also use the range card output, it gives you:
* Correct muzzle velocity
* Twist rate
* Bore height
