### ISSUE TITLE
Map reading light too intense/visible from too far away

### ISSUE THREAD

**Issue by Danerad** [acemod/ACE3#3605]
**Arma 3 Version:** `Latest as per 16.03.2016` (stable / rc / dev)
**ACE3 Version:** `3.5.0` (stable / dev + commit hash)

**Description:**
- The supposedly red map reading light is visible from several hundred meters away at night. (See attached picture, towards the summit ). Some players thought a squad was in a firefight while in reality they were just checking their maps.

Normally, such red light will be visible within 100m only, at most.

Could this be tweaked?

![image](https://cloud.githubusercontent.com/assets/17959941/13903365/b5a6336e-ee77-11e5-8776-d07c59f446f8.png)

**Comment by esteldunedain** [comment]
To be honest, that doesn't look bad in my opinion. The 100m range applies for naked eye visibility, and instead you are looking through a magnifying optic, 

Besides that, the main issue is that lights in Arma do not behave like in real life, and visibility is not that easy to tweak. If someone proposes a better set of parameters we'll consider them for merging,

**Comment by voiperr** [comment]
I've heard several accounts of the lights being too bright for NVG. When I look into that I'll see if I can make it less glaring to the naked eye.
