### ISSUE TITLE
AB - Protractor : wrong indication

### ISSUE THREAD

**Issue by J3aLeiNe** [acemod/ACE3#3606]
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The zero and the angles of the protractor ("inclinomètre" in french) are not good. This isn't the same Indicator but the zero should be like this for example : [http://www.horusvision.com/asli.php](http://www.horusvision.com/asli.php)

**Steps to reproduce:**
- Just compare the protractor with a laser designator.

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Advanced Ballistics manually enabled.

**RPT log file:**
- Necessary for this bug ?

**Comment by J3aLeiNe** [comment]
The link don't work, sorry

**Comment by Glowbal** [comment]
Sorry, but what am I looking at?

**Comment by J3aLeiNe** [comment]
It's not the same value between the protractor and a laser designator. Two quick examples : if i read 0° in a laser designator, it will be approximately -5° on the protractor, if i read approximately +20° on the protractor, it will be + 30° in a laser designator. So, i suppose that the protractor is not calibrated correctly.

**Comment by esteldunedain** [comment]
Ok, I understand the problem. I'll take a look to see which one of the two is given the correct result and fix the other.

**Comment by J3aLeiNe** [comment]
This's a tiny bug, thanks to take the time to fix it.

**Comment by esteldunedain** [comment]
@J3aLeiNe, I did a quick check. The protractor is the one giving wrong results. I'll try to submit a fix soon.
