### ISSUE TITLE
AB - fnc_getMGRSdata.sqf updated with new maps, please ?

### ISSUE THREAD

**Issue by J3aLeiNe** [acemod/ACE3#3609]
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The "fnc_getMGRSdata.sqf" wasn't updated since a few time ago. "lingor" is "lingor3" now,
and we have got many beautiful maps with a big potential of long range shooting : bozcaada, IslaDuala3, abramia, Chernarus_Summer, imralispring, Sara_dbe1, SaraLite, vtr_porquerolles, australia and many more.

I'm not familiarized with github, a ACE member could take the time to update this sqf, please ?

**Steps to reproduce:**
- None.

**Where did the issue occur?**
- None

**Placed Modules:**
- None.

**RPT log file:**
- None.

**Comment by PabstMirror** [comment]
getMGRSdata will use the map's `longitude`, `latitude` and `elevationOffset` config values by default.  A lot of times these values  don't really make sense (`latitude` is often negative).

I will make lingor3 the same as lingor.

For all the other map, it would be extremely helpful if you can get a list of maps coordinates, elevation and the value of `worldName` from the debug console.

**Comment by J3aLeiNe** [comment]
np @PabstMirror , i will do my best.

Sorry but i don't understand something (you know my high level in english). 
I'm a little bit anxious suddenly, how will be calculated all earth effects on the bullet (coriolis and eotvos effect) after ? 
With the default latitude, -45° at Chernarus for example ?

**Comment by sargken** [comment]
Convert the negative to pos?

**Comment by esteldunedain** [comment]
@J3aLeiNe, ACE overrides the map latitude for a list of well know maps to fix them:

```sqf
if (_map in ["Chernarus", "Bootcamp_ACR", "Woodland_ACR", "utes"]) then { _lat = 50; _altitude = 0; };
if (_map in ["Altis", "Stratis"]) then { _lat = 40; _altitude = 0; };
if (_map in ["Takistan", "Zargabad", "Mountains_ACR"]) then { _lat = 35; _altitude = 2000; };
if (_map in ["Shapur_BAF", "ProvingGrounds_PMC"]) then { _lat = 35; _altitude = 100; };
if (_map in ["fallujah"]) then { _lat = 33; _altitude = 0; };
if (_map in ["fata", "Abbottabad"]) then { _lat = 30; _altitude = 1000; };
if (_map in ["sfp_wamako"]) then { _lat = 14; _altitude = 0; };
if (_map in ["sfp_sturko"]) then { _lat = 56; _altitude = 0; };
if (_map in ["Bornholm"]) then { _lat = 55; _altitude = 0; };
if (_map in ["Imrali"]) then { _lat = 40; _altitude = 0; };
if (_map in ["Caribou"]) then { _lat = 68; _altitude = 0; };
if (_map in ["Namalsk"]) then { _lat = 65; _altitude = 0; };
if (_map in ["MCN_Aliabad"]) then { _lat = 36; _altitude = 0; };
if (_map in ["Clafghan"]) then { _lat = 34; _altitude = 640; };
if (_map in ["Sangin", "hellskitchen"]) then { _lat = 32; _altitude = 0; };
if (_map in ["Sara"]) then { _lat = 40; _altitude = 0; };
if (_map in ["reshmaan"]) then { _lat = 35; _altitude = 2000; };
if (_map in ["Thirsk"]) then { _lat = 65; _altitude = 0; };
if (_map in ["lingor"]) then { _lat = -4; _altitude = 0; };
if (_map in ["Panthera3"]) then { _lat = 46; _altitude = 0; };
if (_map in ["Kunduz"]) then { _lat = 37; _altitude = 400; };
```

Otherwise it uses the `latitude` property of the map to compute Coriolis effect. Ideally if those values don't make sense you need to contact the map authors to correct them. We can also add the map names to the list above if you get the data @PabstMirror is asking for.

Latitude should be positive for the northern hemisphere.

**Comment by J3aLeiNe** [comment]
> Latitude should be positive for the northern hemisphere.

Except for BI, @esteldunedain   :-)

@PabstMirror, if i do like this example, it's ok for you ?

`if (_map in ["imrali", "imralispring"]) then { _lat = 40; _altitude = 0; };`

**Comment by jonpas** [comment]
PR with the additions would be most welcome.

**Comment by J3aLeiNe** [comment]
sorry @jonpas  but whay is PR ?

**Comment by jonpas** [comment]
A [pull request](https://help.github.com/articles/using-pull-requests/). :)

No worries, one of us can add it if you have the information needed.

**Comment by J3aLeiNe** [comment]
Oh my god ... 

Ok, i'm going to try it, what branch i must use ?

**Comment by jonpas** [comment]
Hop on Slack and we can go through the basics. :)

**Comment by jonpas** [comment]
Done in #3644
