### ISSUE TITLE
Can't extend ladder and cant rotate objects

### ISSUE THREAD

**Issue by AtomMrav** [acemod/ACE3#3610]
**Arma 3 Version:** `1.56.134787` (stable)
**CBA Version:** `2.3.1.160220` (stable)
**ACE3 Version:** `3.5.1` (stable)
**ACRE2 Versioan:**  `2.1.0.811` (stable)
**Mods:**
- `@CBA_A3`
- `@ace`
- `@acre2`

**Description:**
- When using ACRE 2, I can't rotate explosives while placing them, and can't extend ladder. Without ACRE 2 everything works fine.

**Steps to reproduce:**
- In editor place soldier and ammo box with ace2 ladder.
- Hit play, and try to extend ladder. Nothing happen when scrolling mouse wheel.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- none

**RPT log file:**
[RPT log file](http://pastebin.com/ikWG4rAG)
[ACE Debug](http://pastebin.com/3zYDaAtN)

**P.S.** 
- This may or may not be a problem with you. I just wanted you to know that conflicts occur when using `ACE3` and `ACRE2`.

**Comment by jonpas** [comment]
Can confirm with ACRE2 `2.1.0.871` as well.

**Comment by jonpas** [comment]
Talked with @Snippers from ACRE2, the following was found in the code:
```
// This is probably dangerous, need to find the better method. TODO. 
(findDisplay 46) displayRemoveAllEventHandlers "MouseZChanged"; 
```

Will be fixed in the next ACRE2 update.
