### ISSUE TITLE
Question: Equip FRIES by a trigger?

### ISSUE THREAD

**Issue by Radeni** [acemod/ACE3#3613]
Would it be possible for you guys to make the FRIES module apply to a unit by a trigger.For example if a helicopter is spawned without FRIES but then enters the trigger and the trigger applies the module to that helicopter.The idea came when i saw that some of the modules have an "apply to" menu where you can select a "Synced Trigger".Would this be possible to add to the FRIES module at all?

**Comment by 654wak654** [comment]
You could easily script that yourself in a trigger with `[_vehicle] call ace_fastroping_fnc_equipFRIES;`

**Comment by Radeni** [comment]
thanks alot!
