### ISSUE TITLE
ACE_Spectate UI persists when MP Mission is terminated by command

### ISSUE THREAD

**Issue by Briland5** [acemod/ACE3#3614]
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Spectator UI continues to persist over game UI elements after Dedicated server is force ended.
This does not occur if the mission ends gracefully with [endMission](https://community.bistudio.com/wiki/endMission)

Related to https://github.com/acemod/ACE3/issues/2592

**Steps to reproduce:**
1) Join dedicated server
2) Go into spectator
3) Force-end the server using server commands '#missions' or '#mission blah'

**Where did the issue occur?**
MP

**Placed Modules:**
none

**Comment by esteldunedain** [comment]
@SilentSpike, @commy2

**Comment by commy2** [comment]
Can someone set up a test server for this? With debug console enabled. I can't reproduce on local hosted MP.

**Comment by Briland5** [comment]
I have set up a test server for you and will PM you the details.
It might be important to note I am using 
```
true call ace_spectator_fnc_setSpectator;     
[player, true] call ace_spectator_fnc_stageSpectator;
```
to enter spectator not the respawn templates.

**Comment by BlackHawkPL** [comment]
It's important to note that this bug doesn't occur when mission is ended with endMission or failMission. It looks like ended eventhandler doesn't fire fire when mission is ended with a '#missions'. 
#2592

**Comment by Cyruz143** [comment]
^^ That's not correct, I've yet to find a way that kills spectator properly for everyone.

Checked with: 
`endMission "END1";`
`"end1" call BIS_fnc_endMission;`
`#missions`

Annoyingly seems intermittent, we've just gotten in the habit of pressing escape when spec freezes to kill the overlay.

**Comment by Briland5** [comment]
Executing `endMission "End1";` simultaneously on all machines using remoteExec seems to work for me.

**Comment by BlackHawkPL** [comment]
@Cyruz143 I was using global exec in debug console, you might want to check that.

**Comment by Cyruz143** [comment]
@BlackHawkPL Yeap that's what we're doing, how many players do you have?

**Comment by BlackHawkPL** [comment]
It was only me on server. I'd enter endMission "End1"; , press global exec, press esc to exit menu, then it'd show me end screen. I was using latest ACE and CBA.

Now I understand what was going on. When I'd press esc to exit menu, spectator would register that key press too and exit. You are right, endMission "End1" doesn't terminate spectator.

**Comment by Cyruz143** [comment]
Did some quick testing with 6 people in DS.

`endMission "END1";` - fails
`#missions' - fails
`"end1" call BIS_fnc_endMission;` - works

And I think you're right about the escape key press masking the issue for the person that executes the command. So I guess this can be closed and docs need to reflect using `BIS_fnc_endMission` to gracefully close spectator and end a mission.

**Comment by Cuel** [comment]
Should also write a report on BI issue tracker to have this event .. work

**Comment by BlackHawkPL** [comment]
'#missions' - fails
'endMission "END1";' - **works**
'"end1" call BIS_fnc_endMission;' - works

tested alone on dedi I hosted with version with that PR. As before used debug console.

**Comment by Cyruz143** [comment]
Didn't you just say

> Now I understand what was going on. When I'd press esc to exit menu, spectator would register that key press too and exit. You are right, endMission "End1" doesn't terminate spectator.

Also I messaged commy directly but this PR has no impact on the commands working, it works on release the same as it does with this PR.

**Comment by BlackHawkPL** [comment]
This time mission ended right after I pressed Global Exec, I didn't have to press esc.

For me it works fine with PR, #missions still doesn't work (ended eh doesn't fire after you kill mission with #missions if I remember correctly), but other methods work just fine.

When I find some test subjects I will post my results from test with several people.

**Comment by commy2** [comment]
^ this is exactly what I was expecting.
