### ISSUE TITLE
Strange laser pointer beam

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#362]
#TestingSession 06.04

There's that gap in the middle.

![2015-04-06_00008](https://cloud.githubusercontent.com/assets/1235520/7017495/7e000d90-dcf8-11e4-8617-9dc9b9090d69.jpg)

**Comment by esteldunedain** [comment]
@bux578, laser pointer is done with drawLine3D, which is only 1 pixel wide. I think what you're seeing is due to arma pp effects, messing with such a narrow feature. I do't think we can do much about that, at least while using drawLine3D.

**Comment by commy2** [comment]
The only thing I can do is to remove the drawLine3D. Y/N ?

**Comment by esteldunedain** [comment]
> The only thing I can do is to remove the drawLine3D. Y/N ?

I don't think so. We COULD try drawing a second line next to it to make it thicker.

**Comment by bux578** [comment]
It's a minor flaw. Push it to 3.1.0 if you want.

**Comment by commy2** [comment]
There was this video that showed a gun laser at night. The line was also interrupted. The laser looked way more impressive though.

**Comment by BullHorn7** [comment]
It's visible to all players http://i.imgur.com/m8UwTov.jpg

**Comment by licht-im-Norden87** [comment]
Is the laser beam already depending on the amount of fog. I think this could be a improvement related to the immersion.

**Comment by commy2** [comment]
No. With the commands we are given, it doesn't work like that. Those are the same debug lines BI uses in the VA mission. And they don't work during the night for example.

**Comment by commy2** [comment]
Removed the lines in https://github.com/acemod/ACE3/pull/570

The ir-laser is now toggleable by "Swich Laser / IR-Laser", default: Ctrl+L
