### ISSUE TITLE
ACE_Explosives_fnc_scriptedExplosive 

### ISSUE THREAD

**Issue by C0RAX** [acemod/ACE3#3621]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- CBA_A3
- ACE
- RHS
- UOMODS
- UOMAPS
- UOMAPSCUP
- ACRE

**Description:**
- when using "call ACE_Explosives_fnc_scriptedExplosive;" as described on the aCE3wiki the function gives an error(Error Undefined variable in expression: _dettime) line 6. 

full script code:
"_ied = _this select 0;      
			
			waitUntil {
					sleep 0.5;
					{((_x distance _ied < 10)) and (side _x == west) } count allUnits > 0;
				};
				[[_ied],1] call ACE_Explosives_fnc_scriptedExplosive;
"

**Steps to reproduce:**
- place  "ACE_IEDUrbanBig_Range"
- the placed ied has "null = [this] execVM "scripts\ied.sqf";" in the init field.
- uses above script code in ied.sqf
- approach ied till triggered

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- none

**RPT log file:**
- http://pastebin.com/aQvEyyYc 
- line 5857 for error
- http://pastebin.com/UTDmhWwc

**Comment by commy2** [comment]
The function is meant to be executed in unscheduled environment.

Try replacing:
´[[_ied],1] call ACE_Explosives_fnc_scriptedExplosive;`
with:
`[ACE_Explosives_fnc_scriptedExplosive, [[_ied],1]] call CBA_fnc_directCall`

**Comment by C0RAX** [comment]
Works great, thank you for the prompt response. 

would ask for this to be added and documented in the wiki as it's not immediately clear that it wont work in a scheduled environment.

**Comment by esteldunedain** [comment]
@C0RAX, scheduled environment is plain unreliable because, depending on the load your mission is having, the executed code may be interrupted at any moment. That's why ACE runs 95% of it's code in non-scheduled environment. 

Best practice would be to always call ACE API on non-sched (and the same for ACRE, TFAR, etc). You are right we should document that.

**Comment by bux578** [comment]
@esteldunedain I think @C0RAX is referring to this wiki page:
http://ace3mod.com/wiki/missionmaker/useful-functions.html

And yeah, it should be documented there or a better example should be used there.

**Comment by jonpas** [comment]
Reopening for #3633

**Comment by commy2** [comment]
fixed in #3633
