### ISSUE TITLE
Question: advanced medic system

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#3626]
with the ace-advanced-medic-system active, 
and with several different types of wounds on one bodypart,
which wound is bandaged first? 

because sometimes it looks, as if it's bandaged from top to bottom, 
other times from bottom to top and sometimes randomly. 

or am i doing something wrong, or is the medic system still WIP?

**Comment by Glowbal** [comment]
The wound that is bandaged first is the one that when removed, will have the largest effect upon the overal injury status from a patient.

This is calculated with the effectiveness. See: http://ace3mod.com/wiki/feature/medical-system.html#bandages-effectiveness

It takes into account; bleeding rate from an injury (current state, not original), amount of that injury that the used bandage can patch up, amount of bloodloss reduced by patching up the injury.
