### ISSUE TITLE
ATragMX Phone App for ACE 3

### ISSUE THREAD

**Issue by DeadshotCassidy** [acemod/ACE3#3630]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by DeadshotCassidy** [comment]
Sorry about that was new to posting. I was wondering if the ACE developers could build an ATragMX app go ACE 3 considering it would be more easier for marksmen to use their kestrel in game and record the information into the ATragMX app on their own phone. I remember at one point an ACE 2 ballistics calculator was made, it would still be nice however if y'all did implement an ACE 3 ballistics calculator , with all corresponding ammunition types in game for the Marksmen Rifles, Sniper Rifles, Sniper Rifle Variants, and Assault Rifles. Reason for Assault rifles being that my spotter and I have a natural habit of him having a Assault Rifle to back us up but still be able to provide adequate fire for mid range engagements.

**Comment by esteldunedain** [comment]
Feature requests should be posted in #3594.

This is out of the scope of ACE. You can use existing real life ballistic applications in your phone to the same effect.

**Comment by DeadshotCassidy** [comment]
Looking for a ballistic application that mirrors the AtragMX considering it would be much more relevant to ACE

**Comment by DeadshotCassidy** [comment]
Would be easier to post to the requests if ACE github was easier to navigate. It showed when I posted that it was on the right thread. Y'all decided to use the ATragMX ballistic. Calculator in ACE. I was asking for an android  or iPhone app of the ballistic calculator considering it is much more relevant to the data of the ballistics in your cfg files. I have found before that your ballistic calculator, and the one I was using on my phone were getting different results. If your able to code in the ballistics calculator I would believe it to be rather simple of y'all to do an app of such capacity

**Comment by bux578** [comment]
>  rather simple of y'all to do an app of such capacity

HAHA

**Comment by DeadshotCassidy** [comment]
It truly is, just easier for them because they already have the coding, and programmers to already make the program. Just because they simply don't want to, doesn't mean it is out of your scope. If you have the coding for the feature in ACE 3 then it shouldn't be too difficult for them to put it in another coding language for an app.

**Comment by bux578** [comment]
It is out of scope.
