### ISSUE TITLE
Using handledamage to prevent unit collision damage?

### ISSUE THREAD

**Issue by Tankbuster0** [acemod/ACE3#3636]
**Arma 3 Version:** `1.56 stable
**CBA Version:** `2.3.1` stable 
**ACE3 Version:** `3..5.1 stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
I'm trying to use a tried and tested technique for stopping dismounted civs getting injured or killed in road traffic accidents. Usually this code does this

`			_cfunit addEventHandler ["HandleDamage",
				{
				if (isNull (_this select 3))then
					{
					0;
					} else
					{ _this select 2; }; }];`
But when using ACE3, this code doesn't prevent the civs being killed by cars hitting them

**Steps to reproduce:**
Place a unit in the editor, add the above code to him, run him over with a car. In ACE3, he'll die, in vanilla, he'll live.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer /  Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
	"ace_captives",
	"ace_explosives",
	"ace_hearing",
	"ace_interaction",
	"ace_map",
	"ace_map_gestures",
	"ace_microdagr",
	"ace_mk6mortar",
	"ace_nametags",
	"ace_nightvision",
	"ace_finger",
	"ace_viewdistance",
	"ace_weather",
	"ace_cargo",
	"ace_repair",
	"ace_medical",
	"ace_advanced_ballistics",
	"ace_winddeflection"

**RPT log file:**
- No relevant entries in rpt

**Comment by PabstMirror** [comment]
Handle damage does not stack well, ace medical is designed to be the only thing to add handleDamage to units.

You could trying something like this, but I can't offer any guarentees:

```
_cfunit spawn {
    sleep 1; //Wait for ace to install it's eh
    _this removeAllEventHandlers "HandleDamage"; //remove ace's eh

    _this addEventHandler ["HandleDamage", {
        _return = 0;
        if (!isNull (_this select 3))then {
            _return = _this call ace_medical_fnc_handleDamage;
        };
        _return
    }];
};
```

**Comment by esteldunedain** [comment]
@PabstMirror, what about using this?:

```sqf
[_unit, "blockDamage", "saveTheCivilians", true] call ace_common_fnc_statusEffect_set;
```

Would it work for AI?

**Comment by PabstMirror** [comment]
That's going to block all damage.

I think Tankbuster0's `if (!isNull (_this select 3))then {` would block collision/physX damage, but still allow the units be shot.

**Comment by Tankbuster0** [comment]
Right. I'm rather embarrassed to admit.... that in vanilla, a vehicle collision is, in fact, returning the driver of the vehicle in select 3. This is new behaviour, in case of collision or fall, _select 3 ALWAYS came back as null. 

`civdude addEventHandler ["handledamage", {if (side (_this select 3) == west) then { 0 } else {_this select 2};}];`
The above code does, as now expected protect him from all west nastiness, including being run over and shot. While this isn't quite what I want, it's enough to close this ticket and for me to offer my apologies. :)

**Comment by PabstMirror** [comment]
@Tankbuster0 - I think they changed the "source" for collisions at some point, it think it used to always be null, but now it's often the vehicle or the driver of the vehicle.  Probably so they can track kill/friendly fire for roadkills.

**Comment by Tankbuster0** [comment]
Yes, you're right. For further information, _select 4 now returns "" for collisions. So now I'm going to put ACE3 back in the modline and see what happens

**Comment by Tankbuster0** [comment]
Update and perhaps the ticket should sta alive because the new check for __this select 4 == ""_ method works in vanilla but not in ACE3. I'll check the method pabtsmirror suggested for removing ACE handledamage and report back.

**Comment by Tankbuster0** [comment]
OK, the code supplied by pabstmirror, adapted to allow for the need to check _this select 4 instead of 3 doesn't work. The civs still die in traffic collisions. :(

`_cfunit spawn {
			    sleep 1; //Wait for ace to install it's eh
			    _this removeAllEventHandlers "HandleDamage"; //remove ace's eh

			    _this addEventHandler ["HandleDamage", {
			        _return = 0;
			        if (!isNull (_this select 3))then {
			            _return = _this call ace_medical_fnc_handleDamage;
			        };
			        _return
			    }];
			};`

**Comment by PabstMirror** [comment]
@Tankbuster0 

This code seems to be working ok for me. The civies will ragdoll and go limp and look dead but don't actually die.

But they then seem to be stuck in animationState `"unconscious"`.
We seem to block the `connectTo` on that animation (https://github.com/acemod/ACE3/blob/master/addons/common/CfgMoves.hpp#L65).

So here's a mess of code that should prevent collision damage and then reset their animation after they get hit and knocked down.

```
bob spawn {
    sleep 1; //Wait for ace to install it's eh

    diag_log text format ["Adding custom HD to %1", _this];
    _this removeAllEventHandlers "HandleDamage"; //remove ace's eh

    _this addEventHandler ["HandleDamage", {
        _return = 0;
        if ((_this select 4) != "") then {
            diag_log text format ["Badbeeef"];
            _return = _this call ace_medical_fnc_handleDamage;
        };
        _return
    }];

    _this addEventHandler ["AnimStateChanged", {
        params ["_unit", "_anim"];
        if (_anim == "unconscious") then {
            _unit spawn {
                sleep 5;
                diag_log "fixing anim";
                _this switchMove "Incapacitated";
                _this playMoveNow "amovppnemstpsnonwnondnon";
            };
        };
    }];
};
```

**Comment by Tankbuster0** [comment]
Thanks padstmirror, that's really appreciated, I'll try it in a few days (I'm away on holiday with the family ATM)
Perhaps I should write some more of what I found in the past week or so, as it might help shed some light on what's going on here?
If I removed the ACE medical modules the handledamage seemed to fire about half of the time, but it's { 0; } never worked. But then I lose the ability to modify any of ACE medical's settings.
So I was forced to use a killed EH to track when the civs die and if select 1 was kindof "SoldierWB" then I could assume they were killed by players and not punish players for it.
But even then, there was weird behaviour. More than half the time when I shot them dead, the killed EH reported select 0 and select 1 were the civ unit itself (ie, it died in a collision).

I guess the crux of it is; I understand ACE needs to use eventhandlers and that the game engine doesn't allow multiple ones to work gracefully. But way this is at the moment is preventing mission makers using eventhandlers in any meaningful way. I'm not having a complain at you guys, because this situation is not of your making, but I am asking if your code does all it does to lessen the impact? Is there more that can be done?

**Comment by nomisum** [comment]
Just wanted to express my interest for a solution / workaround for using the killed eventhandler.

Strangely enough it was working for some time fine with ACE medical (pre 3.4 if I had to guess).
My amateur theory is it wasnt anymore with this PR https://github.com/acemod/ACE3/pull/2876/files which applies damage via script and cant set the killer. Maybe it would be possible to setVariable the killer on the victim, so one could access it if necessary?

**Comment by esteldunedain** [comment]
> Maybe it would be possible to setVariable the killer on the victim, so one could access it if necessary?

That's already in; the varible is called `ACE_medical_lastDamageSource`, and points to the last unit to cause damage to the victim.

**Comment by nomisum** [comment]
Ah great, I think I read this somewhere and then forgot about that.

**Comment by Tankbuster0** [comment]
`_civunit addEventHandler ["killed", {if (((_this select 0) getVariable "ACE_medical_lastDamageSource") isKindOf "SoldierWB") then {civkillcount = civkillcount +1};}];`

This is incrementing if the civs are shot dead by me OR run down by a fellow civ in a car. :(

**Comment by jonpas** [comment]
@Tankbuster0 create a new ticket for the issue please.
