### ISSUE TITLE
Interaction menu

### ISSUE THREAD

**Issue by ckleinfelter** [acemod/ACE3#3637]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.
I was playing single player and went to use the interaction menu to place a M113 demo charge and cant the interaction menu and the self interaction menu only pop up a red circle that is it
**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
I honestly dont know how to replicaate it it may just be me i dont know

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal  Single player

**Comment by jonpas** [comment]
Please fill out the issue template fully, otherwise we are unable to help you. Thank you.

**Comment by Glowbal** [comment]
Please reopen once you have filled in the full issue template.
