### ISSUE TITLE
Floating IED's after placing on top of a vehicle

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#365]
Same version as in #TestingSession 06.04

C4 properly attaches to the vehicle.
Seems to be a thing with IED's?

![2015-04-07_00002](https://cloud.githubusercontent.com/assets/1235520/7017623/6e4270f8-dcfa-11e4-8db4-ea51fde65e88.jpg)

**Comment by CamoSteve** [comment]
I had same thing happen to me with a demolition charge. The charge was floating after I moved the ATV.
Btw, I also noticed that some explosives will stick to the vehicles even when they are moving as long as they are not activated by  timer or attached to a trigger.

**Comment by kripto202** [comment]
maybe instead placing the explosive on the vehicle, couldn't you make the vehicle an explosive? 
It can be an interaction to the vehicle to "attach explosive". It removes the charge you selected and considers the vehicle itself as a charge. When triggered, it spawns the charge under the vehicle and cause two explosions. Could also allow mine detectors detect cars with "attached explosive"

**Comment by jaynus** [comment]
@kripto202 Yes thats the easy way to implement this, which then mission makers could just do themselves instead. The solution is not up to the level of detail we are looking to implement.

**Comment by kripto202** [comment]
@jaynus yes it could be implemented by mission makers but as far as I know, those explosives aren't set up via ace explosive trigger, only by a trigger. Its just a thought that could be implemented to maybe have it set as a place holder till this problem could be solved.

**Comment by CorruptedHeart** [comment]
If someone is willing to switch explosives over to using the same attach code that Attach uses, that would probably help avoid potential errors like this.

**Comment by esteldunedain** [comment]
Fixed in #1902
