### ISSUE TITLE
ACE doesn't work after respawn

### ISSUE THREAD

**Issue by nonsindeads** [acemod/ACE3#3656]
**Arma 3 Version:** `stable
**CBA Version:** `2.3.1` 
**ACE3 Version:** `3.5.1` 

**Mods:**
-mod=@cba_a3\;@task_force_radio\;@rhsusaf\;@rhsafrf\;@bwa3\;@js_jc_fa18\;@usaf\;@ace

**Mission**
Altis Domination by Xeno - Modifyed by sAs an others 

**Description:**
if i died an dont be revived i can respawn on base. after spawn ace endurance doesn't work and it doesn't show wounding. So i have endless duration and can't heal me. If i go to lobby and back with same slot it works fine.
The revive script from domination mod is disabled!

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated Linux Server on Gentoo

**Placed Modules:**
- basic medical, advanced medical, advanced balistic and repair

**RPT log file:**
cant see anything but can post it if you need it.

**Comment by commy2** [comment]
You should bug Xeno about this. We can't change anything about that mission.

**Comment by nonsindeads** [comment]
is it a way to reinit ace on a player?

**Comment by nonsindeads** [comment]
or is it a way do fully disable ace medical and only use balistics and other stuff

**Comment by commy2** [comment]
No. The mission has to be fixed.
