### ISSUE TITLE
Advanced Ballistics - Protractor

### ISSUE THREAD

**Issue by Nagrach** [acemod/ACE3#3660]
Feature request - Activate the Protractor for all Weapons - specially Rocket/Missile Launchers - also when Aim Down Sights

Due the possible Back-blast damage with Ace its problematic to use Stingers/Titan AA on targets with an higher elevation.
Reason:
I would like to use the "protractor" to define an "save shooting angle" for our soldiers when engaging target in higher altitudes.

**Comment by bux578** [comment]
Hi, thank you for your request, but feature requests go into this ticket: https://github.com/acemod/ACE3/issues/3594/
