### ISSUE TITLE
ACE 3 vs devbranch

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#3661]
**Arma 3 Version:** `1.59` (dev)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Warning Message: Addon 'ace_main' requires addon 'a3_structures_f_exp_a'

**Steps to reproduce:**
- Use Devbranch, and try to alunch game with ace 3. Already tried to veryfing game files, all went good.

**Where did the issue occur?**
- game launching

**Placed Modules:**
- N/A

**RPT log file:**

[arma3_2016-04-04_17-48-11.zip](https://github.com/acemod/ACE3/files/202787/arma3_2016-04-04_17-48-11.zip)

**Comment by jonpas** [comment]
Could anyone verify if it happens on release candidate branch as well?

**Comment by PabstMirror** [comment]
RC is fine
`isClass (configfile >> "CfgPatches" >> "A3_Structures_F_Exp_A")` = true

**Comment by commy2** [comment]
1.59 dev
`isClass (configfile >> "CfgPatches" >> "A3_Structures_F_Exp_A")`
`-> false`

**Comment by commy2** [comment]
There is no config.cpp in `structures_f_exp_a.pbo`. Their binarizer probably errored out when making that PBO.
Close?

**Comment by PabstMirror** [comment]
1.60 is probably ~2 months out, we can reopen if it's still a problem in 1.60 RC

**Comment by jonpas** [comment]
Was fixed on dev-branch: https://forums.bistudio.com/topic/140837-development-branch-changelog/?p=3007694

> Tweaked: The empty config in the Structures_F_Exp_A addon was reintroduced for back-compat
