### ISSUE TITLE
Fastroping makes unit fall to death halfway through sliding down

### ISSUE THREAD

**Issue by PatricianVidya** [acemod/ACE3#3662]
Arma 3 Version: 1.56.134787 Stable
CBA Version: v2.3.1.160220 Stable
ACE3 Version: 3.5.1 Stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- While fastroping from a helicopter, my character "lets go" halfway through and plummets to his death. The animation plays and it's obvious the system is working, but after a few seconds the default falling animation plays and the character becomes damaged as they hit the ground.

**Steps to reproduce:**
- Get in a helicopter which has fastroping enabled
- Hover above area you want to fastrope down to
- Prepare and deploy the rope
- Use the Interaction Menu to slide down

**Where did the issue occur?**
- Singleplayer Editor, self-made mission

**Placed Modules:**
- None

**Comment by VurtualRuler98** [comment]
I had this problem with AI, and could prevent it by using attachto to fix the helicopter in place. It seems the AI wants to fly up to avoid the player, so the place you let go at ends up being in the air.

**Comment by Glowbal** [comment]
@BaerMitUmlaut can this be closed?

**Comment by BaerMitUmlaut** [comment]
Closing this, have not gotten any reports on this anymore.
