### ISSUE TITLE
Unload from vehicle cargo on the slope

### ISSUE THREAD

**Issue by lolkij** [acemod/ACE3#3667]
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
You cannot unload any item (for example spare parts) from the vehicle cargo, if the vehicle is on a slope. 
I understand that the script is looking for "safe place" or smthng to unload the item, but this limitation has a greatly affect for the gameplay: i.e. tank with destroyed tracks, standing on a hillside, becomes a useless heap of metal without the possibility to repair it

**Steps to reproduce:**
- Put the car or tank on the hillside, even with a slight angle
- Try to get the spare parts from the cargo section (wheel or track)
- Wasted!

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- none

**RPT log file:**
http://pastebin.com/dmB7qchh

**Comment by johnsmm** [comment]
i noticed same issue.
