### ISSUE TITLE
Comanche lock on

### ISSUE THREAD

**Issue by MrFies** [acemod/ACE3#3671]
Hello Guys , 

I cant lock with the rockets from the "RAH  Comanche" they are only flying straight.
And I cant activate the Laser.
Im using only ACE3 latest version and CBA latest version...

Greetings 

MrFies

**Comment by GitHawk** [comment]
Currently the Comanche has no own self designate laser and it can only lock on laser targets. Tagging @esteldunedain because he requested it and is reworking ace_laser.

**Comment by JudahH932** [comment]
Can we get the commanche patched back to just vanilla tab locking? It hasn't worked properly in forever and like the jet bombs of the last few patches, this is a really critical asset. It's better to have the crappy and unrealistic vanilla locking than a glorified littlebird with a gimble cannon.

**Comment by JudahHarvey** [comment]
Can we get the commanche patched back to just vanilla tab locking? It hasn't worked properly in forever and like the jet bombs of the last few patches, this is a really critical asset. It's better to have the crappy and unrealistic vanilla locking than a glorified littlebird with a gimble cannon.

**Comment by DLEGION** [comment]
agree! the main anti-tank asset does not work...i too vote for a "vanilla system" better than nothing.
