### ISSUE TITLE
Pressing Shift + ~ doesn't work on gunner seat in vehicle

### ISSUE THREAD

**Issue by ca1ek** [acemod/ACE3#3672]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- shift + ~ doesn't lock a weapon on a vehicle

**Steps to reproduce:**
- press shift + ~ while in the gunner seat in a vehicle 

**Where did the issue occur?**
- everywhere

**Placed Modules:**
- None

**RPT log file:**
n/a

**Comment by jonpas** [comment]
@ca1ek Please indicate versions of Arma 3, CBA and ACE3 in the first part of the issue.

**Comment by PabstMirror** [comment]
Pointing system only supports dismounted or static weapons.
In-vehicle interactions are tricky, in many cases your not in the same compartment, or using optics where pointing wouldn't make any sense.

Tagging  #1917
