### ISSUE TITLE
Interaction Menu Dev Question

### ISSUE THREAD

**Issue by johnsmm** [acemod/ACE3#3673]
Hey guys just want to say great job on this!
Did better than Bohemia!

Question!  We are making new BECTI mission and i was wondering if we can integrate our BECTI menu into your interaction menu! Which files do we need to work with or we can just call something out?

thank you!

**Comment by jonpas** [comment]
I suggest you jump on our public Slack, you can get an invite [here](http://slackin.ace3mod.com/).

**Comment by johnsmm** [comment]
we can donate some cash if one of the devs can help us out.

**Comment by PabstMirror** [comment]
@johnsmm take a look at http://ace3mod.com/wiki/framework/interactionMenu-framework.html
