### ISSUE TITLE
[AI] Helicopters with FRIES equipable (equiped or not) fails to land...

### ISSUE THREAD

**Issue by NoBullshit** [acemod/ACE3#3674]
**Arma 3 Version:** `1.56.134787` (stable)
**CBA Version:** `2.3.1.160220` (stable)
**ACE3 Version:** `3.5.1.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The AI FRIES equipable helicpoters (e.g: UH-80) have a not needed behaviour when they try to land on helipad. All of the landing waypoint types are concerned (_"GET OUT"_, _"LOAD/UNLOAD"_, the BI's scripted _"LAND"_ waypoint, etc...). The issue occur even if the _"Equip helicopter with FRIES"_ checkbox is unchecked...
- Detailed description of the helicopter behaviour:
  the helicopter gradualy decends to the helipad, but at 5-10m, the pilot abort the land and try to land on another point, the helicopter have approximately 1/2 chances to land correctly on this other landing point. If it fails, he will return to the helipad for another try, fails, and go again to the second point, and so on... This loop block the mission.

**Steps to reproduce:**
- go to the 3D editor;
- place an helipad randomly on the road;
- place an in fly UH-80 or other FRIES capable helicopter near the helipad;
- attach a _"LAND"_ waypoint to the helipad;
- place a player rifleman as observator;
- play the mission.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None.

**RPT log file:**
- N/A

**Workaround:**
- Delete the class attribute concerning the helicopter FRIES in the _mission.sqm_.
- Or edit the helicopter attributes in the 3D editor to change the object type with a non FRIES capable object, then reedit the object attributes to select back your FRIES capable helicopter. (In other words: use a non updated attribute menu for the edition.)

**Additional informations:**
- We should normaly be able to bypass the problem by using the FRIES module sync'ed to the debugged\* helicopter, and unsync' it before landing, but the command _"synchronyzeObjectRemove"_ don't remove the FRIES from the helicopter and the issue remains...

* see above

**Comment by NoBullshit** [comment]
PS: when I say "FRIES equipable", I mean "which have the _'Equip helicopter with FRIES'_ checkbox in his attribute menu".

**Comment by esteldunedain** [comment]
@BaerMitUmlaut, most probably having the FRIES attached messes up with the AI. Maybe we could try changing the object type of the object once more. Maybe make it some type of helper object?

**Comment by PabstMirror** [comment]
IIRC in 1.58 we can attach ropes to non-vehicles (from the refuel problem)

If we could just make them simple thingXs and maybe also use the new `createObject` command, I think it could really help with all the AI problems.

**Comment by esteldunedain** [comment]
That'd be nice.

**Comment by NoBullshit** [comment]
I that doesn't work, you can also simply add a function to remove the model of the FRIES, can't you ?

**Comment by esteldunedain** [comment]
@NoBullshit, that'd be possible, although clearly not-ideal.

**Comment by NoBullshit** [comment]
So in last resort...

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 160 days without any activity.

**Comment by Styles2304** [comment]
So this is still an issue. Is there any progress or update?

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
