### ISSUE TITLE
Question: Bandage efficiency advanced medic system

### ISSUE THREAD

**Issue by Meiestrix** [acemod/ACE3#3675]
Hi,
I have a question to the efficiency off the different types of bandages in the ACE version 3.5.1 with the advanced medic system.
Are the values for the different types of bandages and different types of wounds in this file the real values which are implemented in the 3.5.1 release? (For advanced Minor, Medium, Large)
https://github.com/acemod/ACE3/blob/master/addons/medical/ACE_Medical_Treatments.hpp#L692-L1444 
So you can create this table:
![image](https://cloud.githubusercontent.com/assets/8461758/14407018/53d212a4-feba-11e5-91e2-c153c0a42df9.png)

Which leads to this type of wound treatment?
![image](https://cloud.githubusercontent.com/assets/8461758/14407027/7a0da1fe-feba-11e5-9213-3b79fd615828.png)

**Comment by alganthe** [comment]
Yes they are.
