### ISSUE TITLE
Can't load uncunscious unit in helicopters with FastRope

### ISSUE THREAD

**Issue by kamkill01011** [acemod/ACE3#3686]
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- It's not possible to load a uncunscious unit (player or AI) in a helicopter that has FastRope system (even if the system is not prepared)

**Steps to reproduce:**
- Go next to a helicopter that has the FastRope system with a uncunscious AI or player and try loading the uncunscious unit in the helicopter, you will see the "Load patient" action but nothing happends. If you are already in the helicopter with the uncunscious unit and you try to unload it (from inside) it says "No Room to unload".

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer and maybe more

**Placed Modules:**
- Equip FRIES (but you can also use this script to add the FastRope system : [_heli] call ace_fastroping_fnc_equipFRIES)

**Comment by Stura7** [comment]
We can reproduce the issue and we localized the problem. The helicopters have a second interaction point (the fastrope object), so "load patient" try to load the patient in these object without seats. 
![Heli with 2 Interaction Points](http://i.imgur.com/DN4BBYA.jpg)

If we try to load the patient from the hear side, it only shows the normal interaction point and the loading works fine. 
![Heli with 1 Interaction Point from the rear](http://i.imgur.com/PIv3bhF.jpg)

So there is the second problem that you can load cargo into the fastrope interaction object.
