### ISSUE TITLE
[FRIES] The units lost their waypoints after been fast-roped by the "LET UNITS FAST ROPE" waypoint...

### ISSUE THREAD

**Issue by NoBullshit** [acemod/ACE3#3687]
**Arma 3 Version:** `1.56.134787` (stable)
**CBA Version:** `2.3.1.160220` (stable)
**ACE3 Version:** `3.5.1.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The _"LET UNITS FAST ROPE"_ waypoint cancels all waypoints of the fast-roped units. (It is not the case with the player units that using the intercation menu.) This issue has the effect to stop the progression of the fast-roped units...
- Detailed description:
  the waypoints disappear at the begining of the fast-roping procedure (for example, for a chinook, the waypoints will disappear when the cargo ramp will start to open).

**Steps to reproduce:**
- go to the 3D editor;
- place a chinnok in fly;
- place a player rifleman in the cargo;
- place a _"LET UNITS FAST ROPE"_ waypoint for the chinook;
- place some map visible waypoints for the rifleman;
- play the mission in cadet mode (to see your waypoints on the map);
- open your map, you will see your waypoints;
- wait for fast-roping (do not use the intercation menu);
- open your map after the fast-roping and find that your waypoints have simply disappeared.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None.

**RPT log file:**
- N/A

**Workaround:**
- May be by saving the waypoints in an array prior to fast-roping, and reload them after by a triggered action...

**Additional informations:**
- I also noticed that the AI units stay sometimes grabbed to the rope, even after touching ground... The helicopter stay hovering and cannot complete the waypoint. I'm sure that you already know this issue... If it's not the case, say it to me and I will post a detailed ticket...

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 160 days without any activity.

**Comment by bababoombatman** [comment]
Any news on this bug? Is still present and is very annoing

**Comment by Rafalsky001** [comment]
As March 2021 this bug still exists.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
