### ISSUE TITLE
Zeus spawned units have no name via ACE Interaction

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#3698]
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- No name is shown for zeus spawned units.
How it should look - http://i.imgur.com/gqrq3Kd.jpg
How it looks for zeus spawned units - http://i.imgur.com/H6A0BkY.jpg
Name command on that unit - http://i.imgur.com/6hSGd4B.jpg
Another example for the car - http://i.imgur.com/rqAbDkk.jpg

**Steps to reproduce:**
- Open zeus.
- Spawn friendly a unit. Try to diagnose him.

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- None.

**RPT log file:**
- https://gist.github.com/rebelvg/3cc787a1e6a24e51c9f433cec8b184db

**Comment by PabstMirror** [comment]
Should be fixed via #3634

**Comment by jonpas** [comment]
Correct, fixed by #3634.
