### ISSUE TITLE
BlueForceTracking not working properly on dedicated server

### ISSUE THREAD

**Issue by AtomMrav** [acemod/ACE3#3704]
**Arma 3 Version:** `1.56.134787` (stable)
**CBA Version:** `2.3.1.160220` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@rhsafrf`
- `@rhsusf`
- `@acre2`

**Description:**
- I want BFT to show custom group call signs, and everything works fin on local host. But on dedicated it shows default group callsigns (alfa 1-1, alfa 1-2 etc.)
- I have tried with arma 3 callsign module, tried with command in group leader init, tried in eden editor, and everything works on local host, but not on dedicated server.
- Commands i have used:

• group1 setGroupIdGlobal ["%GroupNames :=: %GroupColors","Instruktori","GroupColor1"];

• group1 setGroupId ["%GroupNames :=: %GroupColors","Instruktori","GroupColor1"];

• group player setGroupIdGlobal ["%GroupNames :=: %GroupColors","Instruktori","GroupColor1"];

• settings in eden http://prntscr.com/au9e1j 

• settings i BFT module: http://prntscr.com/au9eer

**Steps to reproduce:**
- Open MP eden editor, place 2 groups, place BFT module. In atributes menu of groups in callsign field type custom group name | place callsign module | in group leader init type some of obave commands. 
Hit play, and on map you can see custom names of groups.
When uploaded on dedicated server, it shows default group names...

**Where did the issue occur?**
- Dedicated 

**Placed Modules:**
- BFT
- Callsign module

**Comment by commy2** [comment]
Don't use the callsign module. It's from BI and most likely just doesn't work...
Just put `group this setGroupID xyz` in the init box.
There also is a `BFT_ShowPlayerNames` flag which should be disabled.

The marker text is adjusted locally in a loop here: https://github.com/acemod/ACE3/blob/master/addons/map/functions/fnc_blueForceTrackingUpdate.sqf#L58

Use the debug console to check if `groupID` is set correctly on the dedi.

**Comment by AtomMrav** [comment]
`group this setGroupID xyz` also not working

But I found that this `group this setGroupIdGlobal ["name of the group"];` works ond dedicated server.

Thank you all for the help. I really appreciate Your help.

**Comment by Jastreb** [comment]
`group this setGroupID xyz` < this will work in Hosted environment, in fact it will in this form:

`group this setGroupId ["xyz"];` but on dedicated it wont for some reason. No errors shown.

It will only work with `setGroupIdGlobal`

Guess not a bug, BI's fault? Or meant to work like this...

**Comment by jonpas** [comment]
`setGroupId` is a local command. 
`SetGroupIdGlobal` is a global command.

**Comment by Jastreb** [comment]
`setGroupId` used to work in MP. That has changed obviously. No reason to play cpt. obvious.

**Comment by jonpas** [comment]
`setGroupId` never worked globally, unless you used it in the init field in the editor, where it gets executed on each machine anyways.

**Comment by Jastreb** [comment]
Here @jonpas try this mission on dedicated and tell me if it worked for you. I already tried that what your saying and its not working, or I wont be commenting.


[bft_test.Stratis.pbo.zip](https://github.com/acemod/ACE3/files/229177/bft_test.Stratis.pbo.zip)

**Comment by commy2** [comment]
The problem here is, that `group _unit` returns `grpNull` when executed on init on remote units.

Try replacing
`group this setGroupID [""Instruktori""];`
with:
`0 = 0 spawn {group this setGroupID [""Instruktori""];};`
