### ISSUE TITLE
Arma 3 + ACE3 + Vehicle lock + Arsenal = problem

### ISSUE THREAD

**Issue by DominadorBR** [acemod/ACE3#3707]
**Arma 3 Version:** `1.56` (stable / rc / dev)
**CBA Version:** `2.3.1` (stable / dev + commit hash)
**ACE3 Version:** `3.5.1` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Ace Vehicle Lock not found in Arsenal

**Steps to reproduce:**
- https://youtu.be/FC8B10YssXk

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by commy2** [comment]
`ACE_key_customKeyMagazine` is a magazine (using magazine IDs) and those don't appear in BI's Arsenal. Not fixable without rewriting the arsenal which is a task for BI.
Close?

**Comment by kwinteng** [comment]
Commy, i'm sure they showed up before the 3.5.1 update under misc in the arsenal

**Comment by commy2** [comment]
@PabstMirror

**Comment by PabstMirror** [comment]
The problem is the virtual arsenal replaces all of your gear 

Starting (have a key and a mag with 1 round missing):
```
[["ACE_key_customKeyMagazine",1,false,-1,"Uniform"],["30Rnd_556x45_Stanag",29,false,-1,"Uniform"]]
["ACE Vehicle Key(1/1)[id/cr:10000361/0]","5.56mm 30Rnd Mag(29/30)[id/cr:10000099/0]"]
```

Enter aresenal and hit Close without touching anything:
```
[["ACE_key_customKeyMagazine",1,false,-1,"Uniform"],["30Rnd_556x45_Stanag",30,false,-1,"Uniform"]]
["ACE Vehicle Key(1/1)[id/cr:10000373/0]","5.56mm 30Rnd Mag(30/30)[id/cr:10000374/0]"]
```

So they must remove and re-add gear, which creates new unique IDs for the magazines which veh lock used. 

@Glowbal / @jonpas - This will effect BFT as well. 

I have some ideas, but for now just avoid the magic boxes 
or just use the simpler east/west color keys which wont' have this problem

**Comment by PabstMirror** [comment]
There is an event for arsenal open/close, but the player's gear is modifed before the open event.
```
    [missionnamespace, "arsenalOpened", {
        diag_log text format ["arsenalOpened - %1", magazinesDetail player]; //mags already replaced
    }] call bis_fnc_addScriptedEventHandler;
```

**Comment by jonpas** [comment]
Can we just rewrite the Arsenal function (not fully just what we need changed)?

**Comment by dedmen** [comment]
@alganthe Fixed?

**Comment by alganthe** [comment]
This is not a bug, vehicle lock keys should only be added via script (afaik) and thus are considered unique items in ace arsenal.

**Comment by dedmen** [comment]
Yeah. I mean they work in ACE Arsenal right? So this can be closed then.
as @jonpas suggestion was implemented (2 years later :D)

**Comment by jonpas** [comment]
I was pushing for it long enough for someone to finally do it! :laughing:
