### ISSUE TITLE
Possible .DLL issues crashing dedicated server? 

### ISSUE THREAD

**Issue by ender2078** [acemod/ACE3#3708]
**Arma 3 Version:** `1.56.134787` (stable / rc / dev)
**CBA Version:** `2.3.1` (stable / dev + commit hash)
**ACE3 Version:** `3.5.1` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@ALiVE`
-` @Alive_server`
-`@RHSUSF`
-`@RHSAFRF`

**Description:**
Hey guys, first off I am experiencing an issue only with Altis map specifically, we are running a whole bunch of custom mod pack stuff (just what you want to hear I know :P ) however, the issue only occurs on Altis and it seems like its specifically near the main Airfield on the map where the server crashes (this could be coincidence). Anyways the ACE3.dll files caught my eye right before the server crash/fault occurred, however after researching through other problems/solutions from you guys I read something about the server not needing the .DLL files, can you confirm if this might be a potential fix or should I remove them, if I do, will the server take a performance hit, etc? Maybe this isnt even the issue, but again, it is only happening on Altis Map. **Note BattleEye is NOT INSTALLED ON SERVER. 

**Steps to reproduce:**
- Load up a map with @ACE3 @CBA_A3, @ALIVE, @Alive_server, our custom mod packs (which are actually only consolidated mods into one folder for the most part) and run around for a little while.

Here is the part of the RPT that I am focused on at the moment, any feedback is greatly appreciated! Thank you! 

 ```
Extensions:

  ace_clipboard (C:\A3Server\@ENCore\ace_clipboard.dll) [3.5.0.0] [3.5.0.0]
  ace_fcs (C:\A3Server\@ENCore\ace_fcs.dll) [3.5.0.0] [3.5.0.0]
  ace_advanced_ballistics (C:\A3Server\@ENCore\ace_advanced_ballistics.dll) [3.5.0.0] [3.5.0.0]
  ace_medical (C:\A3Server\@ENCore\ace_medical.dll) [3.5.0.0] [3.5.0.0]
  ALiVEPlugIn (C:\A3Server\@AliveServer\ALiVEPlugIn.dll) [0.0.0.1] [0.0.0.1]
  ace_parse_imagepath (C:\A3Server\@ENCore\ace_parse_imagepath.dll) [3.5.0.0] [3.5.0.0]
  ace_break_line (C:\A3Server\@ENCore\ace_break_line.dll) [3.5.0.0] [3.5.0.0]
Distribution: 0
Version 1.56.134787
Fault time: 2016/04/19 19:21:11
Fault address:  00000001 00:00000001 Unknown module
file:     Siege_On_Altis
world:    Altis

Registers:
EAX:12E30520 EBX:FFFFFFFF
ECX:12E319C0 EDX:00AEEDA4
ESI:1A29F280 EDI:1A29F289
CS:EIP:0023:00000001
SS:ESP:002B:00AEED78  EBP:4F3E9F44
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010216
=======================================================
note: Minidump has been generated into the file 
```

**Where did the issue occur?**
- Dedicated Server.

**Placed Modules:**
- The Advanced Medical settings, advanced ballistics, set medic class as, were exported and plcaed into a description.ext so the mission does not actually have a majority of these modules, Modules that ARE in the mission include ACE3 Repair, ACE3 Interaction, many of the ACE3 modules are placed down. 

**RPT log file:**
- [https://gist.github.com/ender2078/8bc0002d910074a1bba0a54d8166eecc]

**Comment by ender2078** [comment]
Right after posting this I scrolled way up the RPT at the beginning of a long list and saw this:

`Exception code: C0000005 ACCESS_VIOLATION at 00000001`

Maybe its not ACE related afterall, idk you guys can maybe point me in the right direction. Thank you.

**Comment by commy2** [comment]
Arma always lists all dll files inside the main folder when crashing (or even just closing the game normally). It has nothing to do with the crash.

**Comment by commy2** [comment]
There is no script error here or anything else we could fix. If the game crashes BI has to solve that.
Close?
