### ISSUE TITLE
ACE3 - Save Gear Issue

### ISSUE THREAD

**Issue by rockurheart** [acemod/ACE3#3711]
**Arma 3 Version:** `1.57.134787` (stable / rc / dev)
**CBA Version:** `2.3.1.160220` (stable / dev + commit hash)
**ACE3 Version:** `3.5.1` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@tryk`
- `@asdj_jr`
- `@NATO_RUS_Weapons`
- `@RHARD_Mk18`
- `@ULTIMATE_SOLDIER2`
- `@fhq_accessories`
- `@task_force_radio`

**Description:**
Tried this with different mods, on and off, over 9 different loadouts, tryk, no tryk, launchers no launchers, this type of weapon and vanilla, nothing seems to work.

not sure how to go about this issue at all ive been pondering for hours,

After death, everything is saved yes. However, my guy drops the bag (ex. CarryAll) and the default bag (RT-1523G (ASIP)) when joining the server, appears, with some of the items that is supposedly in MY bag (ex. CarryAll) inside it.

And so I have to take my bag, and transfer the items from the RT-1523G back into my CarryAll.

I am not running modules on the mission, all of this is exported server side configuration.
Im running an invade and annex server, no extra parameters for ace on the description.ext (i can never get it right) and i couldn't find the option of Save Gear in the export settings in ACE OPTIONS.

I can't see to find the solution.. let alone the problem..

**Steps to reproduce:**
- Not quite sure here. Could join the server im trying to fix this is with the same mods and see what happens, could cooperated with the server files and try to see the issue.

**Where did the issue occur?**
- Rented Multiplayer Server (ftp access)

**Placed Modules:**
- None. All server side.

**RPT log file:**
(This is the latest one)
- http://pastebin.com/uAXLWR7W

**Comment by Glowbal** [comment]
Hi @rockurheart 

Are you trying to use the save gear on respawn option from ACE? You are talking about "when joining a server" and "on death". Could you clarify when and what the issue is you are experiencing?

Thanks in advance!

**Comment by rockurheart** [comment]
Hello, @Glowbal , thanks for the quick response

What I meant by "when joining a server" was the 'default loadout' everyone is given when doing so, here's a screenshot of what I mean~ http://prntscr.com/auyjpk ~And that particular bag would take over as I respawn, instead of me carrying the bag that I died with.

HOWEVER. I was able to fix this issue by adding **"tf_no_auto_long_range_radio = true"** to my Inif.sqf inside my mission folder! :D woot

**Comment by Glowbal** [comment]
Ah yes. That would be an issue from TFAR. Your solution for the problem is indeed the right one.
