### ISSUE TITLE
Client/Server Addon Mismatch.

### ISSUE THREAD

**Issue by rockurheart** [acemod/ACE3#3712]
**Arma 3 Version:** `1.58.135656` (stable / rc / dev)
**CBA Version:** `2.3.1.160220` (stable / dev + commit hash)
**ACE3 Version:** `3.5.1` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@tryk`
- `@asdj_jr`
- `@NATO_RUS_Weapons`
- `@RHARD_Mk18`
- `@ULTIMATE_SOLDIER2`
- `@fhq_accessories`
- `@task_force_radio`

**Description:**
- Joins server - Picks slot - Loading - When finally entering game, gives me this error.
"Client/Server Addon Mismatch. Client has extra addons: ["ace_winddeflection","ace_concertina_wire"]." , and then gets kicked out.

(There was also an instance where my friend got kicked out after maybe 10 minutes of playing normally without ACE3)

Heres a screenshot: http://prntscr.com/av3j1q

**Steps to reproduce:**
- Not quite sure what exactly to do, installed ace on the server, put the userconfig file, made the @aceServer folder, and everything

**Where did the issue occur?**
- Rented Multiplayer Server (ftp access)

**Placed Modules:**
- All server side, no ACE modules on the map.

**RPT log file:**
http://pastebin.com/zvqF1H5z

**Comment by commy2** [comment]
Do you also have the servers RPT file? It says that your server doesn't has `ace_winddeflection.pbo` and `ace_concertina_wire.pbo`

**Comment by rockurheart** [comment]
I quadruple checked and it does though :/

Im not sure where to find my servers RPT file either :(

**Comment by commy2** [comment]
`%LOCALAPPDATA%/Arma 3`

**Comment by commy2** [comment]
sorry. shitty windows:
`%LOCALAPPDATA%\Arma 3`

**Comment by bux578** [comment]
@commy2 
> Rented Multiplayer Server (ftp access)

**Comment by commy2** [comment]
Uhm? I'm not a server guy. That's the path programed in the game.

**Comment by rockurheart** [comment]
Hey guys, I reinstalled ace for the 4th time and it worked. for some reason. it didnt before.. but.. i have no idea, it works now and its solved, it might have been some issue with the transferring that went on in the FTP, anyways thank you!

**Comment by commy2** [comment]
yay
