### ISSUE TITLE
Being randomly kicked with no desc. 

### ISSUE THREAD

**Issue by rockurheart** [acemod/ACE3#3715]
**Arma 3 Version:** `1.58.135656` (stable / rc / dev)
**CBA Version:** `2.3.1.160220` (stable / dev + commit hash)
**ACE3 Version:** `3.5.1` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@tryk`
- `@asdj_jr`
- `@NATO_RUS_Weapons`
- `@RHARD_Mk18`
- `@ULTIMATE_SOLDIER2`
- `@fhq_accessories`
- `@task_force_radio`

**Description:**
- Can join without ACE3 and play. However, being AFK (not confirmed if AFK is the problem), at one point you will get kicked with no desc.
(Check PBO and all of those are set to warn once and disabled, so the server wont do anything even if you have the wrong version or dont have ACE3 at all)

- Join with ACE3, never experience the problem.

- When entering server without ACE3. --> Error: No entry " http://bin/config.bin/CfgWeapons.ACE_LMG_coax_MAG58_mem22'.
is given, could this be the reason for the kick?

- When kicked:
C2073775 (PlayerName) Kicked Off

(Screenshot) http://prnt.sc/av5ifi

**Steps to reproduce:**
- Can try to join my server without and with ACE3.

**Where did the issue occur?**
- Rented Multiplayer Server (ftp access)

**Placed Modules:**
- None. All server side.

**RPT log file:**
- https://gist.github.com/rockurheart/072f81f5c678228c3baf67372fae955d
(RPT is quite long)

**Comment by jonpas** [comment]
Did you update the server to 1.58? An update was released today.

**Comment by rockurheart** [comment]
Yes the server is updated to 1.58.

**Comment by commy2** [comment]
>10:48:00 Warning Message: No entry 'bin\config.bin/CfgMagazines.30Rnd_mas_556x45_Stanag'.

Someone connected with custom weapons that don't exist on the server. The server was only running CBA and ACE

This was `NATO SF\RUSSIAN SPETSNAZ WEAPONS` according to google. You need the _exact same mods on all clients and server_ regardless of what anyone tells you.

There also is a script error in `init.sqf`, line 292

**Comment by commy2** [comment]
I don't think this has anything to do with ACE. I think it's better if you ask questions about setting up a server on the BI forums. https://forums.bistudio.com/forum
It kinda doesn't belong here.
Close?

**Comment by rockurheart** [comment]
You're probably right, ill close this, thank you commy!
