### ISSUE TITLE
Interaction and self-interaction menu problems with aiming deadzone

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#3717]
**Arma 3 Version:** `1.58` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- There is very hard to choose action from self interaction menu when aiming deadzone is enabled in game. Mouse is moving slowly and hard. Also cursor (point of selection) start to move when character do, which should not happen, cursor should move independly of character.

**Steps to reproduce:**
- Turn ON Deadzone in game options, open and travel through self interaction menu.

**Where did the issue occur?**
- EVERYWHERE

**Placed Modules:**
- NONE.

**Comment by jonpas** [comment]
> Also cursor (point of selection) start to move when character do, which should not happen, cursor should move independly of character.

You can change that in ACE Settings.

**Comment by vlad8011** [comment]
I tried every setting, the cursoer allways move after the character rotate.

**Comment by kripto202** [comment]
I think he is talking about the mouse while using the interaction menu.

**Comment by vlad8011** [comment]
Yes i am.

**Comment by jonpas** [comment]
For self-interaction there is a setting "Always display cursor for self-interaction". For target interaction there is a setting "Always display cursor for interaction". Both do the same for different menus, make the cursor move independently from the controlled unit. I believe this is what you are looking for.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
