### ISSUE TITLE
Unable to use make.py

### ISSUE THREAD

**Issue by tteomaster4** [acemod/ACE3#3719]
I get this error everything I attempt to use the make.py . I have double checked that I have my path setup to include git. I have tried both the cmd and the bin paths and both result in the same error. Any help would be greatly appreciated. Thanks in advance.
```
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
=============== RESTART: P:\.git\acerework\ACE3\tools\make.py ===============

make.py for Arma, modified for Advanced Combat Environment v0.7

Check external references is set to False
ERROR: FAILED TO DETERMINE COMMIT ID.
Verify that \GIT\BIN or \GIT\CMD is in your system path or user path.
Traceback (most recent call last):
  File "P:\.git\acerework\ACE3\tools\make.py", line 1437, in <module>
    main(sys.argv)
  File "P:\.git\acerework\ACE3\tools\make.py", line 931, in main
    commit_id = get_commit_ID()
  File "P:\.git\acerework\ACE3\tools\make.py", line 683, in get_commit_ID
    assert os.path.exists(gitpath)
AssertionError
>>> 
```

**Comment by bux578** [comment]
`ERROR: FAILED TO DETERMINE COMMIT ID.`

That's your error.

Open the folder in a command line and try running `git rev-parse HEAD`.

My guess is: git is still not in your environment variable or you're not working on an ACE copy that is connected to a repo (either ours or your fork).

**Comment by Glowbal** [comment]
Hi,

You have your ACE source folder in a .git directory - that seems strange to me. Especially since that also appears to be on your P: drive. 

Here are our instructions to setting up our development environment: http://ace3mod.com/wiki/development/setting-up-the-development-environment.html

**Comment by tteomaster4** [comment]
Turns out that I had an extra version of ace in my arma3 folder. Thanks so much for all of the help and the quick response.
