### ISSUE TITLE
Unable to repair vehicles with defined repair facility

### ISSUE THREAD

**Issue by Opendome** [acemod/ACE3#3720]
**Arma 3 Version:** `x.xx` (stable / rc / dev) stable
**CBA Version:** `2.x.x` (stable / dev + commit hash) stable
**ACE3 Version:** `3.x.x` (stable / dev + commit hash) stable

**Mods:**
- `@CBA_A3` most recent
- `@ace` most recent

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.
Placed the Assign Repair Facility module and assigned Land_HelipadSquare_F as the repair facility, when a vehicle is damaged, moved a vehicle to the defined helipad and did not repair nor get the option when I went to interactions (only showed cargo and attach item), specifically this is with a A3 vanilla technical/M2 so I could test functionality without other modded vehicles. Also tried changing my unit to an engineer but with the same result.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

Currently Editor Multiplayer but developing a mission for a dedicated server

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

Most of the ACE modules\ Basic ALIVE modules

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by bux578** [comment]
Please follow the issue template.

We need a RPT file.

**Comment by Opendome** [comment]
My apologies here s my RPT

http://pastebin.com/index/fUFq925j

Thanks,

**Comment by bux578** [comment]
It's filled with alive errors.

Please try to reproduce it with only CBA and ACE3.

**Comment by PabstMirror** [comment]
@Opendome 

I tested with these settings:
![image](https://cloud.githubusercontent.com/assets/9376747/16329437/0323c752-39a8-11e6-9f88-836a1ab50e43.png)

And it was working fine.
- Make sure the repairer has a toolkit.
- You can use the sync modules or the new 3den attributes to set a repair faclity.
- Verify facility is set by testing `[player] call ace_repair_fnc_isInRepairFacility` = true

**Comment by esteldunedain** [comment]
Expired
