### ISSUE TITLE
Issues launching custom version of ace3

### ISSUE THREAD

**Issue by tteomaster4** [acemod/ACE3#3721]
Mods:
- `@CBA_A3`
- `@ace`

Description:
- when I try to launch arma  3 with my new version of @ace included I am met with this error.
Include file z\ace\addons\main\script_mod.hpp not found.

Steps to reproduce:
- Launch arma 3 with CBA and ace enabled

Where did the issue occur?
- Issue occurs during initializing addons phase of startup

**Comment by tteomaster4** [comment]
I was able to fix the problem, but Im not really sure how. If anyone ran in to the same problem and actually knows how they fixed it I would love to know otherwise I will close this thread in a couple of hours if I get no response.
ps. sorry about the repetitive posts

**Comment by commy2** [comment]
You have to add `*.hpp` to the "files to copy directly"

**Comment by tteomaster4** [comment]
awesome, thank you.
