### ISSUE TITLE
[ReloadLaunchers] Unable to initiate buddy-reload; only prompted to check ammo

### ISSUE THREAD

**Issue by headedhorseman101** [acemod/ACE3#3726]
**Arma 3 Version:** `1.54` Stable
**CBA Version:** `2.3.1` Stable
**ACE3 Version:** `3.5.1` Stable

**Mods:**
- `@CBA_A3`
- `@ace` 
- `@acre2`

**Description:**
- While testing the buddy reload from the `reloadlaunchers` module, was not prompted with option to reload the other player's weapon. Wouldn't allow me to get as far as selecting the ammo, as stated on the instructions of the features page of the wiki.

**Steps to reproduce:**
- In mission, have other player equip Titan(short/long)/RPG-32, ensure that it is their currently selected weapon.
- With corresponding ammo in backpack/vest, use interaction key to interact with Titan/RPG of other player. 
- If able to select weapon with interaction interface, observe the ability to only check the status of their ammo.

**Where did the issue occur?**
- Self-Hosted Multiplayer & Dedicated Server Multiplayer

**Placed Modules:**
- Medical Settings
- Advanced Medical Settings
- Revive Settings
- Repawn Settings

**RPT log file:**
-Unable to supply right now, will provide for self-hosted in next few days.

**Comment by PabstMirror** [comment]
I couldn't reproduce any problems.

In a test mission I put down 2 units, first unit has ammo with: 
```
removeAllWeapons this; [this, "launch_B_Titan_F", 3] call bis_fnc_addWeaponl
```
and a unit with no ammo:
```
removeAllWeapons this; [this, "launch_B_Titan_F", 0] call bis_fnc_addWeapon
```

The action showed up and reload worked.

**Comment by headedhorseman101** [comment]
Was unable to perform on a dedicated in multiplayer. It was not done on my PC, but on both a dedicated server and another person's PC, so I will have to contact one of the admins or the host of the local multiplayer to get an rpt for you.

**Comment by jonpas** [comment]
@headedhorseman101 What is the status on this?

**Comment by headedhorseman101** [comment]
@jonpas apologies for the extreme delay. Extenuating circumstances have kept me away from my home computer, where the rpt's are stored. Will update when I am able to.

**Comment by headedhorseman101** [comment]
Upon revisiting the issue, unable to reproduce again.
