### ISSUE TITLE
Wounds reopening too fast?

### ISSUE THREAD

**Issue by kripto202** [acemod/ACE3#3732]
While looking at the ACE_medical_treatments.hpp, i noticed that some wounds reopen within 10 seconds on line 749 for example. I'm sure that people would be more skilled in applying bandages that will stay on for at least 10 minutes. Is this a overlook or an actual feature?

**Comment by PARTYzanRnD** [comment]
just as an idea: Reopening should not be just random, reopening chance should be connected with players movement after injury (easy way - check stamina, hard way - exclude stamina drain by keeping breath).
