### ISSUE TITLE
Adding preset damage to units at begining of mission

### ISSUE THREAD

**Issue by Nimrandel** [acemod/ACE3#3735]
Hi,I want to make a mission where the team crashed and starts the mission with injuries from the crash. I was hoping someone could tell me how to add damage and also set a unit to unconscious in the editor.

**Comment by kripto202** [comment]
if you download 3den enhanced, you can use a slider on how damaged you want a certain body part to have. There is another script i have where i use to help train everyone on the advanced medical, https://www.youtube.com/watch?v=kEGAU20MGnc I'm sure you can use these files to work with something

**Comment by PabstMirror** [comment]
//Put in unit's init box in editor:
`nul = this execVM "damageAtStart.sqf";`

**damageAtStart.sqf:**
```
//We need to wait a little bit for settings to propagate down
//1 second is overkill, but it shouldn't really matter
sleep 1;

params ["_guy"];
if (!local _guy) exitWith {}; //only need to run where local

//This will do a small amount of damage to a random limb
_hit = selectRandom ["hand_r", "hand_l", "leg_r", "leg_l"];
[_guy, 0.2, _hit, "bullet"] call ace_medical_fnc_addDamageToUnit;

//Because of the oddities of HandleDamage, 
//we assume that multiple hits within a small window are from the same source
//So we need to sleep between hits, or the 2nd would be ignored
sleep 1;

//Again, do a small amount of damage to a random limb
_hit = selectRandom ["hand_r", "hand_l", "leg_r", "leg_l"];
[_guy, 0.2, _hit, "bullet"] call ace_medical_fnc_addDamageToUnit;
```
