### ISSUE TITLE
Self Interaction list empty.

### ISSUE THREAD

**Issue by Mevthlack** [acemod/ACE3#3737]
**Arma 3 Version:** 1.58 stable
**CBA Version:** 2.3.1 stable
**ACE3 Version:** 3.5.1.0 stable

**Mods:**
- @CBA_A3
- @ace

**Description:**
- When pressing self-interaction hotkeys the cursor appears but the list / radial menu is blank
All other features of ACE work , including interaction with other units / objects

**Steps to reproduce:**
- Load into Editor (3D or 2D) , Create any unit and attempt self interaction.

**Where did the issue occur?**
- Self - Hosted , MP , SP , Editor.

**Placed Modules:**
- None

**RPT log file:**
http://pastebin.com/RgTFna50

**Comment by Glowbal** [comment]
```
13:52:59 Error in expression </*-------------------------------------->
13:52:59   Error position: </*-------------------------------------->
13:52:59   Error Invalid number in expression
13:52:59 Error in expression </*-------------------------------------->
13:52:59   Error position: </*-------------------------------------->
13:52:59   Error Invalid number in expression
13:53:01 No owner
13:53:01 Error in expression </*-------------------------------------->
13:53:01   Error position: </*-------------------------------------->
13:53:01   Error Invalid number in expression
13:53:01 Error in expression </*-------------------------------------->
13:53:01   Error position: </*-------------------------------------->
13:53:01   Error Invalid number in expression
```

From the rpt log file posted. Maybe a weird mission file? 

@Mevthlack did this happen before the latest A3 update as well?

**Comment by Mevthlack** [comment]
I honestly wouldn't know , this is my first time back to arma in a few months. As for a mission file this is just in a blank editor , only one unit ( the playable one) spawned.

**Comment by jokoho48** [comment]
please reinstall your CBA you have files that are not any more in the CBA loaded

**Comment by Mevthlack** [comment]
Perfect , thanks alot Jokoho , I assume it was me merging two CBAs , rather than completely removing it first? Either way its all good now , thanks.
