### ISSUE TITLE
Error in "fnc_tagTestingThread.sqf"

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#3738]
**Arma 3 Version:** `1.58` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@Alive`

**Description:**
no steps to reproduce... only the error in the log...

**Where did the issue occur?**
- Dedicated

**RPT log file:**
Link to pastebin -> http://pastebin.com/Drf53J4L

**Comment by jonpas** [comment]
When does it happen? While tagging ground or an object (eg. house)?

**Comment by shukari** [comment]
We was testing that feature, so 8 guys tag everything on Takistan ;D

**Comment by jonpas** [comment]
I am afraid that doesn't help much.

**Comment by shukari** [comment]
Ah, ok... sry for wasting your time... i will try to reproduce it on takistan tomorrow.

**Comment by jonpas** [comment]
Keep the issue up, if you can reproduce it that would be great.

**Comment by commy2** [comment]
needs full RPT file. fragment is not sufficient

**Comment by shukari** [comment]
Serverlog: https://www.dropbox.com/s/1jcnpw53a2gfe9f/SERVER290416.rar?dl=0
(to long for pastbin ;D)

**Comment by jonpas** [comment]
Ah I see which error this is. Fixed in #3648, will be part of next release.
