### ISSUE TITLE
Cannot propperly set loadout in mission briefing.

### ISSUE THREAD

**Issue by Timlugia** [acemod/ACE3#3741]
**Arma 3 Version:** 
Game version: 1.59.135790
Branch: development

**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When playing single campaign, I cannot set a loadout during briefing: everytime I closed the window, my weapons would be returned to a default one

**Steps to reproduce:**
- Happened in many campaign missions, such as Breaking Even. Usually the missions with "minimal" gear requirement

**Where did the issue occur?**
- Single player campaign.

**Placed Modules:**
- none

**RPT log file:**
- The game did not crash.

**Comment by commy2** [comment]
>RPT log file:
>The game did not crash.

We still need a RPT file for this. It can be found here: `%LOCALAPPDATA%\Arma 3´

**Comment by Timlugia** [comment]
Excuse me, how do I attach a RPT file here?
I tried both RPT and docx but the site wouldn't allow it.

**Comment by commy2** [comment]
https://gist.github.com/
http://pastebin.com/

**Comment by Timlugia** [comment]
So after some testing, I found out that the conflict was by ace_disposable. The game works normally after I removed this pbo.

**Comment by commy2** [comment]
- still needing RPT file
- pretty sure this is bad coding of the mission, sorry but we don't support the single player campaign

close?
