### ISSUE TITLE
PAK vs SurgicalKit (Weight and Volume)

### ISSUE THREAD

**Issue by ZikiCZ** [acemod/ACE3#3742]
Space in inventory:
Surgical Kit need more space in the inventory, but can only stop the reopening wounds.

https://github.com/acemod/ACE3/blob/master/addons/medical/CfgWeapons.hpp#L217
https://github.com/acemod/ACE3/blob/master/addons/medical/CfgWeapons.hpp#L228

Weight
PAK have same weight like a Surgical Kit (approx 0.5kg). But PAK allows full recovery.
Weight of aid kits should be about 1-1.5kg.
SurgicalKit + 1x SalineIV(0,5l-1l) + 1x morphine + 1x epinephrine

By the way there's still no other option to heal burns then using the PAK.

**Comment by bux578** [comment]
I don't understand what you want here.

**Comment by jonpas** [comment]
He wants Surgical Kit to have less weight than PAK, because it can do less than PAK.

**Comment by ZikiCZ** [comment]
I was pointing out that there's no need to carry surgical kit as they weight the same as Personal aid kits but are less versatile then PAKs. And also the fact that there's no other option to heal burns then using PAKs.
In the Arma2 version of ace(ACE2) the PAK had around 1kg (maybe a little bit more than that).
I don't want the surgical kit to be lighter that would not make much sense ...yet making the PAKits heavier as it consists of SurgicalKit (approx 0.5kg) + 1x SalineIV(0,5l-1l) + 1x morphine + 1x epinephrine wich is more then a 0,5kg.

**Comment by grester** [comment]
PAK is sometimes seen as a placeholder for missing features or a "cheat" to lighten ACE's seriousness. PAK is sort of the equivalent of a FAK in the vanilla arma but for ACE.
Surgical kit is meant to be realistic and part of medical simulation and to be only used by medics unlike PAKs that are often given to common soldiers, thus why I personally don't see as a problem a surgical kit being heavier than a PAK, rather the opposite, it's good as it is.

**Comment by ZikiCZ** [comment]
No. Weight of PAK and surgical kit is the same. (approx 0.5kg)
But Surgical kit requires 50% more space in inventory than PAK.

We often play only with surgical kit and SalineIV. PAK is only used at the base.

**Comment by grester** [comment]
> No. Weight of PAK and surgical kit is the same. (approx 0.5kg)
But Surgical kit requires 50% more space in inventory than PAK.

That seems fair to me given the POV I've mentioned before.
