### ISSUE TITLE
No Heart Rate in Medical Menue

### ISSUE THREAD

**Issue by Zakant** [acemod/ACE3#3743]
**Arma 3 Version:** stable
**CBA Version:** stable (Workshop)
**ACE3 Version:** stable (Workshop)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When cheking the heart rate of an unit in the medical menue it occours that no heart rate is detected. However if you check the heart rate by using the 3D menue you get a heart rate. The heart rate is existing (i have checked the variable `ace_medical_heartRate`).

**Steps to reproduce:**
- Add a AI unit. Shoot it until it is in cardiac arrest. Check pulse from Medical Menue.

**Where did the issue occur?**
- Dedicated Multiplayer (Zeus mission)

**Placed Modules:**
- Advanced medical module.

**Comment by Glowbal** [comment]
Heart rate checking has some matter of chance to it - sometimes you will fail to find any heart rate if the hr is very low. Both menu and interaction menu use the same method of finding and reporting the heart rate. 

I do not think this is a bug.
