### ISSUE TITLE
CUP Mk19 RHIBs can't be pushed through ACE action

### ISSUE THREAD

**Issue by ChairborneIT** [acemod/ACE3#3744]
**Arma 3 Version:** `1.58 stable` (stable / rc / dev)
**CBA Version:** `latest stable` (stable / dev + commit hash)
**ACE3 Version:** `latest stable` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@cup (weapons+units+vehicles)`

**Description:**
- The Mk19 RHIB weights 2730.714kg, while the limit for pushing is 2600, would it be possible to raise that threshold so that the Mk19 RHIB is also compatible?

**Steps to reproduce:**
- Beach a Mk19 RHIB, no push action is available, do the same with the regular RHIB and the push action is there

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- n.a.

**RPT log file:**
- n.a.
- n.a.

**Comment by jonpas** [comment]
We discussed on Slack about this, I suggest a config `GVAR(canPush)` that also enables it, next to weight check (OR condition).

**Comment by esteldunedain** [comment]
Just to clarify, the entry should be:

```
ace_interaction_canPush = 1;
```
