### ISSUE TITLE
Mortar coordinates change depending on whether the mortar is loaded or not.

### ISSUE THREAD

**Issue by austinjames314** [acemod/ACE3#3757]
**Arma 3 Version:** `1.58` stable
**CBA Version:** `2.3.1` stable
**ACE3 Version:** `3.5.1` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The displayed azimuth and elevation of the ACE3 mortars changes depending on whether the mortar is loaded or not. The figures displayed when loaded are accurate, but when unloaded they are not. Makes it hard to aim each shot of a linear or any other other type of fire plan when you have to wait for the tube to be loaded before you can start to aim the next shot accurately. Additionally, this will be a serious issue once fire-on-drop is implemented, as you won't be able to aim at all.
- See video: https://youtu.be/tZuEZYaoMBE
Notice how the azimuth changes drastically when the load state changes.

**Steps to reproduce:**
- Start a mission with CBA and ACE3, and Zeus. Zeus in a mortar and put it on some slightly uneven ground. Aim the mortar. Load a round. Observe the coordinates change. Fire the mortar. Observe the coordinates change again.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- Require CBA
- Zeus gamemaster
- Mk6 Settings:
  - Air resistance: Enabled
  - Artillery Computer: Disabled
  - Compass: Enabled
  - Ammunition Handling: Enabled

**RPT log file:**
- Can't see any relevant errors but here you go:
- The dedicated server: http://pastebin.com/Apb7Lpnq
- My local client: http://pastebin.com/QNRHf4nS

**Comment by PabstMirror** [comment]
Rangefinder (`(ctrlText (_display displayCtrl 173))`) reads as infinity (`--`) when the mortar has no ammo,

**Comment by commy2** [comment]
Can we add an empty magazine instead of removing it?

**Comment by austinjames314** [comment]
Pushed back again! :disappointed:

**Comment by austinjames314** [comment]
Woohoo!!!
