### ISSUE TITLE
setHearingCapability - Both medical and Hearing modify sound levels

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#3765]
Ref discussion in #3710

**Comment by PabstMirror** [comment]
I looked at this as part of PR #3802 and I'm not sure if this is necessary.
Medical only modifies the hearing levels of voices from radio mods (ACRE/TFR).

**Comment by Glowbal** [comment]
https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_setHearingCapability.sqf
