### ISSUE TITLE
Medical problem

### ISSUE THREAD

**Issue by Silente13** [acemod/ACE3#3769]
Hello guys! I have a server arma 3. And yesterday i installed ace mod. but i want load it, i mean the server read the mod, but i can't setting the userconfig. Can you help me?

**Comment by esteldunedain** [comment]
Please read the documentation here:

http://ace3mod.com/wiki/framework/settings-framework.html

You need to copy the `ace_server.pbo` from the `optionals` folder to the `@aceserver/addons` folder for the userconfig file to be read.

If you need further information please join our public Slack chatroom.
