### ISSUE TITLE
ACE_Overheating: Weapon mass influences overheating

### ISSUE THREAD

**Issue by ir0n1e** [acemod/ACE3#3774]
**Arma 3 Version:** every
**CBA Version:** every
**ACE3 Version:** every

**Mods:**
- @CBA_A3
- @ace

**Description:**
- Heavier weapons never overheat. Cause heat up is calculated by weapon mass.

EFUNC(overheating,updateTemperature) line 30:
private _barrelMass = 0.50 * (getNumber (configFile >> "CfgWeapons" >> _weapon >> "WeaponSlotsInfo" >> "mass") / 22.0) max 1.0;

**Comment by esteldunedain** [comment]
That's by design. The barrel mass directly affects overheating IRL; we estimate barrel mass from total weapon mass to avoid having to add additional config entries for all weapons; of course that can fail for some atypical weapons, or for weapons with wrong config masses.

**Comment by ir0n1e** [comment]
@esteldunedain  Jab, knowing that, works for all weapons around 4kg, but weapons about 8kg it will not work. Have seen your pull request, it's the much better solution. Overheating calculated by barrel. Thumbs up!

**Comment by esteldunedain** [comment]
Sorry, what PR are you talking about?

**Comment by ir0n1e** [comment]
#3082 Sawing that their, I think.

**Comment by esteldunedain** [comment]
@ir0n1e, yes, that PR is merged and is how Overheating is currently calculated.

To be honest, I currently don't have better data to calculate barrel mass. If you are willing to do some homework, maybe that could change. What I'd need is a list, as comprehensive as possible, of weapon names, total mass and barrel mass. Using that data we might be able to generate a better regresion for estimating barrel masses, and hence improve the realism of overheating.

**Comment by ir0n1e** [comment]
@esteldunedain  Jab, will see what I can do.

**Comment by ir0n1e** [comment]
@esteldunedain Or, let the modders be on their own. Add an value (multiplier) to change overheat. For default weapons 1 and if modder decides to increase it, he can change it.

**Comment by esteldunedain** [comment]
> Or, let the modders be on their own

@ir0n1e, nah, that'd lead to even more inconsitency

**Comment by ir0n1e** [comment]
@esteldunedain Ok.

**Comment by ir0n1e** [comment]
@esteldunedain non official formula (Site in German formula in English)
http://lutzmoeller.net/Waffen/Technik/Lauflebensdauer.php
