### ISSUE TITLE
scope raticle movement gone

### ISSUE THREAD

**Issue by macfifa** [acemod/ACE3#3775]
**Arma 3 Version:** `1.56` (stable )
**CBA Version:** `2.3.1` 
**ACE3 Version:** `3.5.1` 

Mods:
- `@CBA_A3`
- `@ace`

**Description:**
- it is not error but the raticle movement is gone why ? it was very realistic and I like it hope you put it again

advanced ballistic

**Comment by macfifa** [comment]
I don't know that my old issue is opened again

**Comment by esteldunedain** [comment]
Duplicate

**Comment by commy2** [comment]
tag #3425

please don't create duplicate tickets. thanks
