### ISSUE TITLE
ACE_NoVoice not working dedicated?

### ISSUE THREAD

**Issue by MojoDog** [acemod/ACE3#3782]
Arma 3 Version: 1.58
Mods: CBA_A3, ace3, RHS, TFAR.

Description:
Am I doing something wrong with my dedicated server or why does the soldiers talk when I run my mission on my dedicated server, but not elsewhere.

Placed Modules:
Medical basic advanced, map gestures, name tags, pointing, spectator, weather.

**Comment by commy2** [comment]
What?

**Comment by MojoDog** [comment]
The "voice selection" in arsenal that makes the player not yell commands.
"4, move up!", that kind of thing.

**Comment by commy2** [comment]
Please post the clients and servers RPT file. Thanks.

**Comment by MojoDog** [comment]
[arma3_2016-05-11_20-40-38.txt](https://github.com/acemod/ACE3/files/260077/arma3_2016-05-11_20-40-38.txt)
[arma3server_2016-05-11_19-01-21.txt](https://github.com/acemod/ACE3/files/260078/arma3server_2016-05-11_19-01-21.txt)

**Comment by PabstMirror** [comment]
Server needs to run cba and ace

**Comment by commy2** [comment]
Server is not running ACE
```
19:01:31 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
19:01:31                                  Arma 3 DLC Bundle |            dlcbundle |       true |            NOT FOUND |                                          |           | 
19:01:31                                    Arma 3 Marksmen |                 mark |       true |             GAME DIR | df9d6bc2a3e8838b093c9f947dd445109f1bcd7a |  3029d3d1 | C:\Arma3Server\A3Master\mark
19:01:31                                 Arma 3 Helicopters |                 heli |       true |             GAME DIR | 5df833ca4645686712418acfd3808ac819a17407 |  c1e066a0 | C:\Arma3Server\A3Master\heli
19:01:31                                       Arma 3 Karts |                 kart |       true |             GAME DIR | e50cb946e3757a921b5c671ab3faf13ec85adb03 |  c94faf86 | C:\Arma3Server\A3Master\kart
19:01:31                                        Arma 3 Zeus |              curator |       true |             GAME DIR | cc81d5918598554d5ea7d4182c776a7aa6fcd7cb |  51f0ae65 | C:\Arma3Server\A3Master\curator
19:01:31                                             Arma 3 |                   A3 |       true |            NOT FOUND |                                          |           | 
19:01:31 ==========================================================================================================================================================================================================
```

**Comment by MojoDog** [comment]
Wtf.. it IS running cba and ace. I can put in earplugs and all.

http://i.imgur.com/7LbFlgf.jpg

**Comment by commy2** [comment]
Some features might appear to work regardless, (but they probably don't).

You have to use the absolute paths:
`-mod="C:\Arma3Server\A3Master\@cba_a3" -mod="C:\Arma3Server\A3Master\@ace3"`

or something similar like that.

**Comment by MojoDog** [comment]
Adding the paths did nothing.

Well, it may be some random mysterious Arma error. Maybe initiation order.
Soldiers always talk on my dedicated. Sometimes it shows the subtitles, sometimes not though. Seems really random.

Fuck it. I'll just have to download the MRT VoiceStop mod again.

Sorry for wasting your time devs.

**Comment by commy2** [comment]
>Soldiers always talk on my dedicated.

Um. NoRadio is only supposed to mute the player, not AIs.

**Comment by MojoDog** [comment]
Sorry. I meant soldiers as in "everyone".  Both AI and player talk.

**Comment by commy2** [comment]
I don't know why that would be in your case. Maybe try with only CBA and ACE enabled first?

**Comment by MojoDog** [comment]
Alright, I did some testing.

I made a simple mission with just CBA_A3 and ACE3 enabled.
All soldiers (including player) had this in their init:
`[this] call compile preprocessFile "loadout.sqf";`

loadout.sqf contains this (notice ACE_NoVoice at the bottom):

```
_unit = _this select 0;
if (!(local _unit)) exitWith {};

removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;

_unit forceAddUniform "U_B_CombatUniform_mcam";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 3 do {_unit addItemToUniform "9Rnd_45ACP_Mag";};
for "_i" from 1 to 2 do {_unit addItemToUniform "30Rnd_65x39_caseless_mag";};
_unit addVest "V_PlateCarrier1_blk";
for "_i" from 1 to 3 do {_unit addItemToVest "ACE_morphine";};
for "_i" from 1 to 4 do {_unit addItemToVest "ACE_fieldDressing";};
for "_i" from 1 to 2 do {_unit addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShell";};
for "_i" from 1 to 5 do {_unit addItemToVest "30Rnd_65x39_caseless_mag";};
for "_i" from 1 to 2 do {_unit addItemToVest "MiniGrenade";};
_unit addHeadgear "H_HelmetSpecB_blk";
_unit addGoggles "G_Tactical_Black";

_unit addWeapon "arifle_MX_Black_F";
_unit addPrimaryWeaponItem "acc_flashlight";
_unit addPrimaryWeaponItem "optic_Aco";
_unit addWeapon "hgun_ACPC2_F";
_unit addWeapon "Binocular";

_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ItemWatch";
_unit linkItem "ItemRadio";
_unit linkItem "ItemGPS";
_unit setSpeaker "ACE_NoVoice";
```

Tested running it IN EDITOR. All soldiers are quiet and they have their custom loadout.
Tested running it HOSTING A LISTEN (or whatever it is called, from the same computer). All soldiers are quiet and they have their custom loadout.

Moved that mission-pbo to my dedicated server.

Restarted the dedicated server with only CBA_A3 and ACE3 enabled.

Joined the server from my other computer and started the mission.

Now all soldiers (yes, player too) talk.
"3, STOP!" and "6, move up!" and stuff.

I even tried to put this in soldiers init in case it was a compile or preprocessFile bug:
`[this] call compile preprocessFile "loadout.sqf"; this setSpeaker "ACE_NoVoice";`



Just trying to help guys.

**Comment by Glowbal** [comment]
https://community.bistudio.com/wiki/setSpeaker

setSpeaker has local effect only.

**Comment by MojoDog** [comment]
You are right. It works if I use this in my loadout.sqf:

`[_unit, "ACE_NoVoice"] remoteExecCall ["setSpeaker", 0];`

How weird. I could have sworn I didn't have to do that before.

Sorry for wasting your time. Keep up the good work. Cheers and thanks a bunch.

**Comment by commy2** [comment]
Just to make sure. The player unit wasn't talking after all?

**Comment by commy2** [comment]
Another thing to note here is, that while `setSpeaker` is executed on every machine if put into the init box, the command fails on unit init (similar to `name`, `setFace` and a bunch of other "idendity" commands).
This is why wise people have invented `ACE_common_fnc_muteUnit` and `ACE_common_fnc_unmuteUnit` which always work.
