### ISSUE TITLE
Evaluate "Limping" over forceWalk for medical

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#3784]
https://forums.bistudio.com/topic/190675-limping-feedback/

**Comment by PabstMirror** [comment]
We don't use `forceWalk` in medical.
Currently the game forces the player to walk based on the "hitLegs" hitpoint; which looks like the same thing the new system will use.

Did a quick test on dev and it seems to be working great out of the box :sunglasses:

**Comment by bux578** [comment]
Awesome.
