### ISSUE TITLE
Killed EH broken

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#3790]
**Arma 3 Version:** `1.58` stable
**CBA Version:** `2.3.1.160220` stable
**ACE3 Version:** `3.5.1` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- I cannot use Killed EH in my mission, because both arguments are the same and contain only killed person, twice.

**Steps to reproduce:**
- Add this to init.sqf

`null = execVM "killTicker.sqf";`

- Create script killTicker.sqf with this content:
http://pastebin.com/TjCvmUH5

- Test mission and try killing someone
- When you kill somebody it will show that this person commited sucide (because _killer = _victim)

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- Advanced medical (same behaviour on basic)

**RPT log file:**
None

**Comment by gienkov** [comment]
Related https://github.com/acemod/ACE3/issues/3111

**Comment by PabstMirror** [comment]
See PR #3436

Check `_deadGuy getVariable ["ace_medical_lastDamageSource", objNull]`

**Comment by gienkov** [comment]
That fixes my headache :+1:

**Comment by gienkov** [comment]
Close?

**Comment by PabstMirror** [comment]
If someone is killed by bleeding it will list themselves as the killer, so this should fix problems with that.
Just be aware there are some edge cases for example: you shoot someone, and then much later they fall off a cliff, and the killer would be wrong.

**Comment by gienkov** [comment]
It's <NULL-object> for me/killer but works just fine on killed unit. What am I doing wrong?

**Comment by gienkov** [comment]
I mean killed unit get proper message.

**Comment by gienkov** [comment]
```
tlq_killTicker = { 

	_this addMPEventHandler ['MPKilled',{

		_unit = _this select 0;
		_killer = _unit getVariable ["ace_medical_lastDamageSource", objNull];

		_newKill = [_unit,_killer];

		if (count tlq_killArray > 100) then {tlq_killArray = []};

		tlq_killArray set [count tlq_killArray,_newKill call tlq_parseKill];

		[] spawn tlq_killList;
		if (player == _killer) then {_newKill spawn tlq_killPopUp};


	}
	];
	
};

```

**Comment by PabstMirror** [comment]
If you have a good input for killer just use that.
Only use `ace_medical_lastDamageSource` if you are getting bad data.

**Comment by gienkov** [comment]
It's `<NULL-object>` for me/killer

**Comment by gienkov** [comment]
I've tried checking for this variable manually and it doesn't seem to be working properly (never works for AI).

**Comment by Glowbal** [comment]
A few notes for future reference:
- lastDamageSource is only available local. It is not broadcasted over the net (and not intended to)
- The output may not always be reliable. You may have to combine it with the output of the `killed` eventhandler.

Example:
```sqf
_UNIT addEventhandler ["killed", { 
    params ["_unit" ,"_killer"]; 
    _killer = if (isNull _killer) then {
        _unit getVariable ["ace_medical_lastDamageSource", _killer];
   } else { _killer };

   // do your stuff
}];
```

If you need the damageSource on other clients, I'd suggest a globalEvent with the parameters `[_unit, _killer]` and handle the event on each client.
