### ISSUE TITLE
Error when trying to host a new session offline

### ISSUE THREAD

**Issue by Semper-r** [acemod/ACE3#3794]
ACE3 Version: 3.5.1 Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
 It appears it happens with any module configuration on the scenario.

**Description:**
* Starting the game while not conected to the internet and hosting a new session on lan makes an error appear just when the character appear; the error is this: 
"[ACE] ERROR: Extension ace_fcs.dll not installed" and i found it can also appear with "ace_clipboard.dll" or "ace_advanced_ballistics.dll" instead of "ace_fcs.dll" also i saw it appeared with i think the advanced medical system and it switched rapidly to one of the above but it changed fast and i couldnt read it very well. however i found this does not happen if i start the game when im conected  to the internet.

**Steps to reproduce:**
* turn off any wifi or ethernet conections so the computer is not conected to the internet and start the game (with CBA_A3 and ace) go to multiplayer, host a new session, on lan, start the game, play any mission and just when you are about to start controlling your character it appears.

**Where did the issue occur?**
* Multiplayer, or after editing a mission and previewing it on multiplayer, i did not try to reproduce it on singleplayer.

**RPT log file:**
http://pastebin.com/5pJW6GjB

**Comment by PabstMirror** [comment]
If you are offline you need to start without battleye or the dlls will be blocked

**Comment by PabstMirror** [comment]
Fairly sure battlei was just down at the time.
