### ISSUE TITLE
Ace Extension Issues

### ISSUE THREAD

**Issue by ProStashio** [acemod/ACE3#3799]
**Arma 3 Version:** `x.xx` (stable)
**CBA Version:** `2.x.x` (stable)
**ACE3 Version:** `3.x.x` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
-I load into editor & make a mission, when I try and play it, ace kicking off, spamming multiple messages, however the messages I can make out is the last ones it sends "Extension ace_fcs.dll not installed" & "Extension ace_advanced_ballistics.dll is not installed" hoever I was playing last night with ace installed both editing & multiplayer mission & had no issue..

**Where did the issue occur?**
- Editor (Singleplayer)

**Comment by commy2** [comment]
Battle Eye servers are down. If you use Battle Eye, you'll have to wait until they fix their servers.
