### ISSUE TITLE
Guidance Modularity Framework

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#380]
Laser tasks pulled from PR #3308
- [x] Reenable laser marker creation for the laser_selfdesignate (Comanche).
- [ ] Prefix laser codes differently for different factions.
- [ ] Make faction specific derivatives of laser designators.
- [ ] Make laser codes indicator fall back to a hint in every case in which there's no configured way to display the code in the hud.
- [ ] Guidance framework modularity for addon makers
  - [x] Laser code and designation framework
  - [x] Configuration reading for firing mechanics
  - [x] Configurable guidance functions from parameters
  - [x] Seeker/Guidance separation
  - [ ] Locking modes
- [ ] Attack Profiles
  - [x] Linear attack (DAGR missile)
  - [x] Top-down
  - [ ] HI
  - [ ] MED
  - [x] DIR
- [ ] Seeker Profiles
  - [x] SALH
  - [ ] SARH
  - [ ] LIDAR
  - [ ] Thermal
  - [x] Optic
    - [ ] SPIKE-mode live target feed
  - [ ] GPS
  - [ ] MCLOS
  - [ ] SACLOS

Documentation:

```
class CfgAmmo {
    class ACE_ExampleMissile {

       // Begin ACE guidance Configs
        class ACE_MissileGuidance {
            enabled = 1;

            minDeflection = 0.005;      // Minium flap deflection for guidance
            maxDeflection = 0.025;       // Maximum flap deflection for guidance
            incDeflection = 0.005;      // The incrmeent in which deflection adjusts.
            //minDeflection = 0.005; 
            //maxDeflection = 0.5;
            //incDeflection = 0.005;

            // Guidance type for munitions
            defaultSeekerType = "SALH";
            seekerTypes[] = { "SALH", "LIDAR", "SARH", "Optic", "Thermal", "GPS", "SACLOS", "MCLOS" };  

            defaultSeekerLockMode = "LOAL";
            seekerLockModes[] = { "LOAL", "LOBL" }; 

            seekerAngle = 90;           // Angle in front of the missile which can be searched
            seekerAccuracy = 1;         // seeker accuracy multiplier
            seekerIntercept = 1;        // enables seeker intercept calculations (lead target)
            seekerMinRange = 1;
            seekerMaxRange = 2500;      // Range from the missile which the seeker can visually search

            // Attack profile type selection
            defaultAttackProfile = "LIN";
            attackProfiles[] = { "LIN", "DIR", "MID", "HI", "TOP", "PYM" };
        };
    };
};
```

Custom seeker types and attack profiles

```
class GVAR(AttackProfiles) {
    class LIN {
        name = "";
        visualName = "";
        description = "";

        functionName = QFUNC(attackProfile_LIN);
    };
};

class GVAR(SeekerTypes) {
    class SALH {
        name = "";
        visualName = "";
        description = "";

        functionName = QFUNC(seekerType_SALH);
    };
};

```

**Comment by evromalarkey** [comment]
when using vehicle launchers from other mods or even BIS Pandur, the rocket flies totally away and not on the target. Build - https://github.com/acemod/ACE3/commit/5e766835a65627645b84e4fe952631f9fcd00518

**Comment by jaynus** [comment]
That is due to everyone inheriting from the Titan, i'll need to switch the way in which guidance is defined and enabled and change the config framework for this.

**Comment by dedmen** [comment]
Why is this still open?
https://github.com/acemod/ACE3/tree/master/addons/missileguidance
