### ISSUE TITLE
ACE3 - Scoreboard Kills broken after running server with ACE3

### ISSUE THREAD

**Issue by rockurheart** [acemod/ACE3#3801]
**Arma 3 Version:** `1.58.135656` (stable / rc / dev)
**CBA Version:** `2.3.1.160220` (stable / dev + commit hash)
**ACE3 Version:** `3.5.1` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@asr_ai3`

**Description:**
Scoreboard was working fine without ace.
I ran the server with ace and this happens: http://prntscr.com/b50onk
tried removing it, it became alright, and then added it again then same problem.

**Steps to reproduce:**
- Run a server with ASR_AI3 and with/without ACE3 to see if same problem still occurs

**Where did the issue occur?**
- Rented Multiplayer Server (ftp access)

**Placed Modules:**
- None. All server side.

**RPT log file:**
Rather large, will upload when requested

**Comment by bux578** [comment]
Duplicate #3111

**Comment by bux578** [comment]
That's due to the medical system. We recently introduced a custom event that contains the last damage source: https://github.com/acemod/ACE3/pull/3436

**Comment by rockurheart** [comment]
Copy, closing thread
