### ISSUE TITLE
Safe mode indicator broken when remote controlling a unit

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#3807]
**Arma 3 Version:** `1.58` stable
**CBA Version:** `2.3.1` stable
**ACE3 Version:** `3.5.1` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
When remote controlling a unit after putting your weapon on safe the firing mode indicator will stay empty, even though the weapon is not on safe.

**Steps to reproduce:**
- Be Zeus
- Put your weapon on safe
- Remote control a unit
- Press F, firing mode indicator stays empty even though you can fire your weapon
- Press keybind to put your weapon on safe _twice_
- Firing mode indicator reappears

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- On demand

**RPT log file:**
- On demand

**Comment by Glowbal** [comment]
3.7.0 ?

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 160 days without any activity.
