### ISSUE TITLE
Detecting body bag with player inside a marker

### ISSUE THREAD

**Issue by Zyles** [acemod/ACE3#3816]
I want to use body bags as a way to make a player respawn. We use perma death otherwise.

If the team managed to get a body bag into a marker position it should either:

1. Respawn the player
2. Add a ticket to the team using ticket counting so they can respawn

Now is this possible? How does one detect if there is a body bag with player inside a specific marker?

Also the count needs to only be done once per body bag so you can't abuse it.

**Comment by bux578** [comment]
Thank you for posting on the ACE3 issue tracker.
You're asking for general scripting help which is unrelated to ACE3 (it just happens that you want to use a bodybag). This would be better suited on the BI Forum in a separate thread or on the Arma3 Discord chat in the "#scripting" channel.

**Comment by PabstMirror** [comment]
I can get you started with the bodyBag events, but I'm not really sure what kind of respawn system your using so hopefully you can fill in the blanks:

Put down a static object like a flagpoll called `flagObject`

```
if (isServer) then {
    if (isNull flagObject) exitWith {systemChat "Need an object called 'flagObject'";};
    ["placedInBodyBag", {
        systemChat format ["placedInBodyBag eh %1", _this];
        params ["_deadGuy", "_bodyBag"];
        private _name = [_deadGuy] call ace_common_fnc_getName;
        _bodyBag setVariable ["BodyName", _name];
    }] call ace_common_fnc_addEventHandler;

    [] spawn {
        while {true} do {
            sleep 5;
            //Look for nearby bags within 10 meters:
            private _bags = flagObject nearObjects ["ACE_bodyBagObject", 10];
            {
                private _bodyBag = _x;
                if (!(_bodyBag getVariable ["processed", false])) then {
                    _bodyBag setVariable ["processed", true];
                    _name = _bodyBag getVariable ["BodyName", "err"];
                    systemChat format ["new bag [%1] found with Name [%2]", _x, _name];
                    // Should add a single respawn ticket
                    [missionNamespace, 1] call BIS_fnc_respawnTickets;

                    // Do something to respawn the guy via his name in var `_name`
                    // ???  - broadcast _name and if matches profileName then respawn now ??
                };
            } forEach _bags;
        };
    };
};
};
```

**Comment by commy2** [comment]
"placedInBodyBag" might not exist in 3.5
