### ISSUE TITLE
RHS M72a7 is replaced with AT4 when fired

### ISSUE THREAD

**Issue by j0zh94** [acemod/ACE3#3825]
**Arma 3 Version:** `Stable` (stable / rc / dev)
**CBA Version:** `Stable` (stable / dev + commit hash)
**ACE3 Version:** `Stable` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
-`@RHSUSAF`
-`@RHSAFRF`
-`@RHSGREF`

**Description:**
- The current ACE disposable script will replace the M72 LAW with an AT4 after firing whilst using the ACE_RHS compat pbo. 

**Steps to reproduce:**
- Fire the M72a7 found in RHSUSAF

**Where did the issue occur?**
- Across all

**Placed Modules:**
- None

**RPT log file:**
- N/A

**Comment by PabstMirror** [comment]
I couldn't reproduce, could you go into editor and check:
`getText (configfile >> "CfgWeapons" >> "rhs_weap_m72a7" >> "ACE_UsedTube")`
I was getting "" which means ace_disposables will do nothing.

```
class rhs_weap_M136: Launcher_Base_F
class rhs_weap_m72a7: rhs_weap_M136
```
and the only config we touch is `launch_NLAW_F`

Does the problem occur with only RHS?

**Comment by bux578** [comment]
Please upload a rpt file of the session where this happened.

**Comment by moonmanmove** [comment]
@j0zh94 if you are running the UO modpack, it is caused by inkos disposable
