### ISSUE TITLE
Question: How to hide the mouse cursor?

### ISSUE THREAD

**Issue by legman** [acemod/ACE3#3827]
This is a development question I have regarding the medical system in ACE 3.

How exactly did you hide the mouse cursor when the **DisableMouse_Dialog** is displayed whilst unconscious. Is this possible with a script alone?

I appreciate you taking the time to help me out.

**Comment by commy2** [comment]
There is a mouse cursor `ace_common_DisableMouse_Dialog` is shown. There is no way to disable that.

**Comment by legman** [comment]
oh my mistake - sorry!

**Comment by commy2** [comment]
np
