### ISSUE TITLE
Standard medical menu visible even when disabled and Medical Menu is enabled

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#3829]
**Arma 3 Version:** `1.58` (stable)
**CBA Version:** `2.3.1` (stable and dev `3d8ed8bcdf9f5637e49b2fe62fce92780a773484`)
**ACE3 Version:** `3.5.1` (stable and dev `37068a5247d5138490dec5342f181936625ce156`)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When Medical Menus enabled and standard menu is set to disabled both are still visible in self-interaction and passenger interaction, but not in target interaction.  
  http://i.imgur.com/ZjE7TBN.jpg  
  http://i.imgur.com/qSi1FWF.jpg  
  http://i.imgur.com/hMCuf0H.jpg  
  http://i.imgur.com/HIuQQmM.jpg  
  https://i.imgur.com/ADlAwBn.jpg (both menus set to "Disabled")

**Steps to reproduce:**
- Set "Style of menu (Medical)" to "Disabled"
- Set "Use Medical menu" to "Enabled" (or "Disabled" - however that's probably another thing that shouldn't happen, both menus be disabled, one should probably enable itself if both are disabled)
- Perform self-interact and passenger-interact

**Where did the issue occur?**
- Dedicated and Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- N/A

**Comment by Glowbal** [comment]
I will take this bug as an excuse to pull the medical actions from the interaction menu out of the config file and add them by script instead, using the same tech that the medical_menu component uses.

This will ensure that a) all configuration happens in one place and b) only the necessary actions are provided.

**Comment by jonpas** [comment]
Fixed in rewrite.
