### ISSUE TITLE
fadeSound will have bug with ACE3

### ISSUE THREAD

**Issue by GodofMonkeys** [acemod/ACE3#3830]
**Arma 3 Version:** `1.58` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Use fadeSound with ACE3 will have bug. If I use(0 fadeSound 0, mean 0 sec turn sound vol to level 0), then "0 fadeSound 0" only appears to work for about a millisecond and then the sound volume returns to 1 instantly. Any fade value (e.g. 5 fadeSound 0) also appears to have no effect whatsoever on sound volume.

When ACE not load, this script will be fine.

**Steps to reproduce:**
- 1.Load any mission
  2.Run the command "0 fadeSound 0;"
  3.Listen the sound.(like heli or gunfire)

**Where did the issue occur?**
- Whole game.

**Placed Modules:**
- None.

**RPT log file:**
- None.

**Comment by jonpas** [comment]
That is due to the following 2 functions using `fadeSound`:
https://github.com/acemod/ACE3/blob/03f3b1084d4e9d14617f159db14a7086b1af8682/addons/common/functions/fnc_setVolume.sqf
https://github.com/acemod/ACE3/blob/f69142dd45a9aaa8a318237a5b78185caa9c8c0b/addons/common/functions/fnc_setHearingCapability.sqf

You should be able to use that second function to do what you want, it will always force the lowest set setting to be the one, so you have full compatibility with ACE Hearing and whatever else changes it.

**Comment by PabstMirror** [comment]
This will require the next release of ace, or build current master

**Comment by GodofMonkeys** [comment]
Hi jonpas.
In your second url. That function seem like will set low all volume at same time.(sound,music,radio)
I only want to set low sound, because vehicle's sound(like heli), that sound is too loud, so my intro music will be hard to hear.
Can you got another slove?

**Comment by GodofMonkeys** [comment]
Hi jonpas.
I try to use *["earwax", 0.5, true] call ace_common_fnc_setHearingCapability*.
But it similar like fadeSound's bug, effect will instantly back to original setting.

**Comment by jonpas** [comment]
As @PabstMirror that will only be in the next ACE3 version or a build of current master branch, it's not in 3.5.1 yet, I missed that, my bad.

I don't think I have another solution as I am not sure what all is changing that in ACE3, I know of hearing component only.

**Comment by PabstMirror** [comment]
Try 
`ace_hearing_disableVolumeUpdate = true;`

That should disable hearing from trying to set `fadeSound`

**Comment by GodofMonkeys** [comment]
Hi @PabstMirror  @jonpas .
It work!!!!!
I use:
`ace_hearing_disableVolumeUpdate = true;
0 fadeSound 0;`

When music stop:
`ace_hearing_disableVolumeUpdate = false;`

Sound's volume will turn back to default.

This solution can let my wish come true.

Hope you can also make a specialized script for this or put fadeSound note to everybody know.

Thanks again. :)

**Comment by jonpas** [comment]
Good to hear!

`ace_common_fnc_setHearingCapability` will do exactly what you need it for in the next update, that will be official API, what you currently use might change in the future.
