### ISSUE TITLE
Arma 3 Ace Issue

### ISSUE THREAD

**Issue by CompChris666** [acemod/ACE3#3832]
**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Cannot open Interactive Menu

**Where did the issue occur?**
Singleplayer and Multiplayer

**Placed Modules:**
-None

**RPT log file:**
https://gist.github.com/CompChris666/c7fc7413eb363fde0d83276e9adbf7ee

**Comment by CompChris666** [comment]
IDK how or why but it started working again... so... no need for help but thanks anyways?

**Comment by jonpas** [comment]
You're welcome. :laughing:

**Comment by commy2** [comment]
There is a script error in your mission:

```
16:44:46 Error in expression <forceSize interpolate [150,150.1,-1,1]>
16:44:46   Error position: <forceSize interpolate [150,150.1,-1,1]>
16:44:46   Error Undefined variable in expression: forcesize
16:44:49 Error in expression < param [5, random 360, [0]];
_text = _x param [6, "", [""]];
_shadow = _x param >
16:44:49   Error position: <param [6, "", [""]];
_shadow = _x param >
16:44:49   Error Type Number, expected String
```

Unfortunately this script seems to use preprocessing without adding debug info, so IDK where it's from. Certainly not ACE.

**Comment by SilentSpike** [comment]
@commy2 I've seen the same error in the log while making my own missions, it's either BI or some other addon's fault

**Comment by commy2** [comment]
Yeah. Looks like simple expressions, so it must be from a config. That's why it gives no __file__ and __line__.

**Comment by commy2** [comment]
Found it:
```
class collisionEffect {
    class collisionVeh1 {
        simulation = "particles";
        type = "collisionVeh1";
        lifeTime = 0.2;
    };
    class collisionVeh2 {
        simulation = "particles";
        type = "collisionVeh2";
        lifeTime = 0.2;
    };
    class collisionVehSmoke {
        simulation = "particles";
        type = "collisionVehSmoke";
        enabled = "forceSize interpolate [150,150.1,-1,1]";
        lifeTime = 0.2;
    };
};
```

**Comment by commy2** [comment]
Must be either a bug in the vanilla game, or a corrupt game files.

**Comment by jonpas** [comment]
I've seen the `interpolate` part as well. Since last update.
