### ISSUE TITLE
Prevent instadeath doesn't work ? 

### ISSUE THREAD

**Issue by BreberaCZ** [acemod/ACE3#3833]
**Arma 3 Version:** `1.58` stable
**CBA Version:** `2.3.1` stable
**ACE3 Version:** `3.5.1 stable

**Mods:**
- `@CBA_A3`
- `@ace`
-  @rhsafrf
-  @rhsusaf
-  @rhsgref

**Description:**
- Function prevent instadeath doesn't work. You can get instakilled.

**Steps to reproduce:**
- Start the game → play →die

**Where did the issue occur?**
- Dedicated Multiplayer

**Placed Modules:**
- All Ace 3 medical modules. Review set on players only for 600 seconds. Advanced med.sys.

**RPT log file:**
- N/A

**Comment by SilentSpike** [comment]
Duplicate of #3538
