### ISSUE TITLE
'Author/' is not a value

### ISSUE THREAD

**Issue by ShocknAw3** [acemod/ACE3#3839]
**Arma 3 Version:** `1.60` stable 
**CBA Version:** `2.3.1` stable
**ACE3 Version:** `3.5.1` (stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
When placing units or modules created/modified by ACE in a mission and starting it (MP or SP), an error message appears "'author/' is not a value".

**Steps to reproduce:**
1) Place unit or module created/modified by ACE into the editor
2) Start the mission in multiplayer or singleplayer
3) Error message appears

**Where did the issue occur?**
- Self-Hosted Multiplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- Pretty much all modules

**RPT log file:**
This is the relevant line: 
17:29:25 Warning Message: 'author/' is not a value

**Comment by gienkov** [comment]
Yes I have the same on dedicated

**Comment by commy2** [comment]
Please upload the __full__ RPT file.

**Comment by PabstMirror** [comment]
`Warning Message: 'author/' is not a value`
Is only related rpt line I can see.

It seems to be related to CfgPatches's author config.
Swapping advanced_ballistics's config author to string instead of array seemed to fix:
`author[] = {"Ruthberg"};`
`author = "Ruthberg";`

**Comment by commy2** [comment]
`author[]` is supposed to be an array

**Comment by jonpas** [comment]
Yeah, probably became a problem due to BI reworking how CfgPatches work internally.

**Comment by commy2** [comment]
`author[]` is CBA API and not part of Vanilla though.

**Comment by PabstMirror** [comment]
![image](https://cloud.githubusercontent.com/assets/9376747/15659587/7f9c7ae6-2692-11e6-8635-4b28bba6b418.png)
I think it's related to this new system; and they decided to use author as a string:
```
class CfgPatches {
    class A3_3DEN_Language {
        author = "Bohemia Interactive";
```

**Comment by ShocknAw3** [comment]
I can confirm that PabstMirror's fix worked for other mods like TPWCAS and ACRE2 that produced the same bug.

**Comment by DLEGION** [comment]
Sorry guys, im a bit noob...what i should do exactly to fix this error ? (I know how edit pbo).
Thanks !

**Comment by bux578** [comment]
@DLEGION Nothing. Wait for the updates.

**Comment by DLEGION** [comment]
ah ok thanks man !
i noticed in my mission that M312 fixed machinegun create this error. whitout ACE3 it works fine, with no error.
maybe it helps!

**Comment by commy2** [comment]
@DLEGION 
No worries. We know what's up and the issue is already fixed in the master branch.

**Comment by DLEGION** [comment]
you are awesome guys!
