### ISSUE TITLE
Vanilla CCIP on A-10D Hydra rockets doesn't works with ACE3

### ISSUE THREAD

**Issue by drredfox** [acemod/ACE3#3841]
**Arma 3 Version:** `1.60` stable
**CBA Version:** `2.3.1` stable
**ACE3 Version:** `3.5.1` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The new CCIP introduced in 1.60 doesn't works with ACE3. The Impact Point for Rockets and Bombs remains static (up in the compass band).

**Steps to reproduce:**
- Just try an A-10D in the editor, with and without ACE.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- To edit with info

**RPT log file:**
- Attached below.

**Comment by jonpas** [comment]
Just tried with latest master and it works fine.

**Comment by drredfox** [comment]
I will try again with the new CBA.

**Comment by jonpas** [comment]
I tested with CBA 2.3.1 and ACE 3.5.1 and it worked fine.

**Comment by drredfox** [comment]
[http://i.imgur.com/HI4EzTx.jpg](url)
In this image you can see the calculated impact point with the cannon (this works fine). It moves following the vector of movement of the plane.

[http://i.imgur.com/nLp2yeq.jpg](url)
In this second image you can see the calculated impact point for rockets. The point doesn't matches the trajectory and doesn't moves with the vector of movement of the plane.

**Comment by drredfox** [comment]
Here's the .rpt of a quick fly on editor.
[arma3_2016-05-30_23-37-30.zip](https://github.com/acemod/ACE3/files/290112/arma3_2016-05-30_23-37-30.zip)

**Comment by jonpas** [comment]
You are not loading `@CBA_A3` and `@ace` only, you also load some compatibility PBOs without the mods for which they are made are present:
```
23:37:49 Warning Message: Addon 'bamse_ace3_rhs_add_huntir' requires addon 'rhsusf_c_weapons'
23:37:53 Warning Message: Addon 'ace_RH_acc_comp' requires addon 'RH_acc'
23:37:53 Warning Message: Addon 'ace_RH_de_cfg_comp' requires addon 'RH_de_cfg'
23:37:53 Warning Message: Addon 'ace_RH_m4_cfg_comp' requires addon 'RH_m4_cfg'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_weapons'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_troops'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_bmd'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_bmp'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_bmp3'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_a2port_armor'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_btr'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_sprut'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_t72'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_tanks'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_a2port_air'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_a2port_car'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_cars'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_2s3'
23:37:53 Warning Message: Addon 'ace_compat_rhs_afrf3' requires addon 'rhs_c_rva'
23:37:53 Warning Message: Addon 'ace_compat_rhs_usf3' requires addon 'rhsusf_c_weapons'
23:37:53 Warning Message: Addon 'ace_compat_rhs_usf3' requires addon 'rhsusf_c_troops'
23:37:53 Warning Message: Addon 'ace_compat_rhs_usf3' requires addon 'rhsusf_c_m1a1'
23:37:53 Warning Message: Addon 'ace_compat_rhs_usf3' requires addon 'rhsusf_c_m1a2'
23:37:53 Warning Message: Addon 'ace_compat_rhs_usf3' requires addon 'RHS_US_A2_AirImport'
23:37:53 Warning Message: Addon 'ace_compat_rhs_usf3' requires addon 'rhsusf_c_m109'
23:37:53 Warning Message: Addon 'ace_compat_rhs_usf3' requires addon 'rhsusf_c_hmmwv'
23:37:53 Warning Message: Addon 'ace_compat_rhs_usf3' requires addon 'rhsusf_c_rg33'
23:37:53 Warning Message: Addon 'ace_compat_rhs_usf3' requires addon 'rhsusf_c_fmtv'
23:37:53 Warning Message: Addon 'ace_compat_rhs_usf3' requires addon 'rhsusf_c_m113'
23:37:53 Warning Message: Addon 'ace_compat_rhs_usf3' requires addon 'RHS_US_A2Port_Armor'
23:37:53 Warning Message: Addon 'ace_ruPal_RHS_to_ACE' requires addon 'rhs_optics'
23:37:53 Warning Message: Addon 'ace_ruPal_RHS_to_ACE' requires addon 'rhsusf_optics'
23:37:53 Warning Message: Addon 'ace_ruPal_RHS_to_ACE' requires addon 'rhs_c_heavyweapons'
23:37:53 Warning Message: Addon 'ace_ruPal_RHS_to_ACE' requires addon 'rhsusf_c_statics'
```

**Comment by drredfox** [comment]
Same result without these extra pbos
[arma3_2016-05-31_00-20-53.zip](https://github.com/acemod/ACE3/files/290118/arma3_2016-05-31_00-20-53.zip)

**Comment by jonpas** [comment]
I have no idea anymore. Proof that it works for me with ACE 3.5.1 and CBA 2.3.1: http://i.imgur.com/npmyr7y.jpg

**Comment by drredfox** [comment]
Yeah, I see. I'm gonna try other things.

**Comment by drredfox** [comment]
Try with the Hydra rockets. Bombs and cannon are working. I'm sorry for the mistake.

**Comment by jonpas** [comment]
Aha, now I see, it's not on correct position.

**Comment by drredfox** [comment]
Sorry again. Too much ArmA today...
