### ISSUE TITLE
ACE Spectator map click doesn't work in new 1.60 update

### ISSUE THREAD

**Issue by Ma77h3hac83r** [acemod/ACE3#3842]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When calling the ACE spectator function via the debug console using the "[true] call ace_spectator_fnc_setSpectator" and opening the map to use the Alt + Click teleport option to move the camera it does not work in the new 1.60 update.

**Steps to reproduce:**
- Launch the 3D Editor, place a unit, launch the game. Open the Debug console and call the "[true] call ace_spectator_fnc_setSpectator". Try and use the Alt + Click and teleport the camera.

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor  #(Singleplayer

**Placed Modules:**
- None.

**RPT log file:**
- [pastebin](http://pastebin.com/DB0aRqjV)

**Comment by SilentSpike** [comment]
Perfect issue report :+1:

There have been issues with that functionality in the past so will have to see what's up with it

**Comment by Glowbal** [comment]
@SilentSpike, shall we move this up to 3.7.0 ?

**Comment by SilentSpike** [comment]
Yep, anything assigned to me that isn't done can safely be moved up
