### ISSUE TITLE
set climbing height

### ISSUE THREAD

**Issue by DLEGION** [acemod/ACE3#3845]
Hello all !
this is not an "issue", its just an idea i got, i'm really sorry if i'm somehow violating a rule of this forum but i really didnt found any other way to open a topic here about this!

playing some CQB me and a friend noticed that while "climbing" feature is awesome, its also pretty useless, becasue often you cannot "climb" on low objects, on some walls, and in general you cannot "climb" when you really need to.
so i put hand to code, menaged just to disable the "can_climb" check, so it always climb, but with unrealistic results (like "climbing" in (not "on" i mean "IN" solid walls ecc...). i was not able to adjust height.

so i'm here to ask if there's a way to adjust climbing height (for example i wish set it around 3 meters).
thanks for your help guys !

**Comment by jonpas** [comment]
This is a feature request so it should go to #3594 but since I was in the mood I just did it. It might or it might not be merged, up to other developers if they see it fit.

**Comment by DLEGION** [comment]
huge thanks !!

**Comment by DLEGION** [comment]
hello guys ! while its a bit "too parkour" for me, its more or less what i was searching!
http://www.armaholic.com/page.php?id=27224
i strongly think you guys should contact the mod creator and implement it in next ACE release!
keep up with the good work !

**Comment by jonpas** [comment]
Probably not, movement like that is very unrealistic  just think of the weight soldiers are carrying. I implemented climb setting only because functionality is there and it was rather easy to do.

**Comment by DLEGION** [comment]
yep i agree....feels too much to me too...but maybe restrict it only if weight is low, so one can consider dropping his backpack, climb somewhere, (optional--recover his backpack) and do something from an else unreachable spot ! 
personally i like the general idea, i just wish it was more realistic (weight calculation, if technically too hard, maybe just as multiplier of the time needed to perform the action -more weight = more time-).

**Comment by jonpas** [comment]
https://github.com/acemod/ACE3/pull/3847#issuecomment-223806249
