### ISSUE TITLE
Dead unit interaction broken, nametags still show

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#3846]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.0` (dev `eeacf23c55af0becd465d9cd366ff3ae7cb8513e`)
**ACE3 Version:** `3.5.1` (dev `d7b239f48733611fe2f6cbb4c28c1a06bae12dc0`)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Dead units retain their nametag and cannot be interacted with.  
http://i.imgur.com/pbVTrci.jpg

**Steps to reproduce:**
- Kill a unit

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- N/A

**Comment by jonpas** [comment]
False alarm, works fine now, must have had some settings for medical disabled I guess.

**Comment by esteldunedain** [comment]
Glad to hear it.
