### ISSUE TITLE
Using MapTools draws lines on map

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#3859]
![image](https://cloud.githubusercontent.com/assets/9376747/15734324/0bb70cf4-2854-11e6-9f14-c959f2ab10b1.png)

Ctrl-Drag both rotates mapTools and now draws lines in 1.60.

I'm not sure how we want to fix this?
 - Try to delete the created marker
 - Drop ace's line drawing feature and just use the 1.60 version.

Tagging @esteldunedain

**Comment by jonpas** [comment]
Drop our line drawing, BI's is superior, ours has served its purpose well.

**Comment by bux578** [comment]
Maptools should stay. We just need a different KeyBind.

**Comment by PabstMirror** [comment]
I forgot to add, assuming we drop map line drawing, we should be able to move map tools to alt+click

**Comment by jonpas** [comment]
Aye, that should work.

**Comment by Glowbal** [comment]
> I forgot to add, assuming we drop map line drawing, we should be able to move map tools to alt+click

:+1: Let's do that.

**Comment by madpat3** [comment]
after pressing ctrl+lmb, you can release ctrl while Holding down lmb and cicle maptool ;)

**Comment by wynarator** [comment]
OMG please don't do that! Today I finally sat down and tried to figure why map tools aren't working like they were used to.

Please don't remove line drawing! It's the only way to draw **straight** lines, and that is superimportant in measuring distances for forward observers and such. I always used map tool to draw a straight line from the center to the end, then I grabbed the tool and aligned side of the tool with the drawn line - and distance was easy to measure. It's very cumbersome to measure it without ability to draw straight lines :(

Here's an example (using old AF maptools) of calculating drop target firemission
http://i.imgur.com/7CipMTm.jpg

As you can see a lot of straight lines is involved.

New drawing system from BiS is really good for general and hasty plans like this
http://i.imgur.com/8LvTHFz.jpg

But it won't do in precise calculating. 

Is there any chance for this line-drawing feature to be restored?

**Comment by esteldunedain** [comment]
@wynarator, we know all that. We had to remove line drawing on ACE 3.6 because it clashed with BIS's. But it will be back eventually. Check #4153 for progress.

**Comment by wynarator** [comment]
Oh, sorry for unnecessary post and thank you very much for such a fast reply!
