### ISSUE TITLE
ACE3 Crashing Dedicated Server

### ISSUE THREAD

**Issue by JR-Robinson** [acemod/ACE3#3863]
Arma 3 Version: Stable
CBA Version:Latest
ACE3 Version: Latest

Mods:
@CBA_A3
@task_force_radio
@Mcc_sandbox
@asdg
@RHSAFRF
@RHSUSAF
@ace 

Description:
I have a dedicated server, when I try to add ACE to the startup Parameters for the server, it doesn't show up when I Direct connect to it. (Which means it crahes I guess) if I take it out, its up and running, I'm not sure what the problem is

Steps to reproduce:
^^

**Where did the issue occur?**
Dedicated Server

Placed Modules:
Standard ones, IE Advanced Ballistics, Basic Med, Revive, respawn etc.

RPT log file:
? I cannot get on the server TO see it

**Comment by jonpas** [comment]
As said in the contributing guide:
> It's not a valid to simply remove `@ace` from the mod list to confirm that ACE3 is the culprit.

Check if ACE3 is actually the cause by running **only** `@CBA_A3` and `@ace`.
Also, verify if your server actually crashes. I am not sure what you mean by `I cannot get on the server TO see it`.

Additionally `@asdg` functionality is integrated into CBA for quite some time now.

**Comment by Army0104** [comment]
I can confirm this issue. It even exists if only CBA and ACE are starting. 

> I cannot get on the server TO see it
The problem he means is that the server is not even (or at least not correctly) starting so that you are not able to find your server in the server browser or to direct connect to it.

I'll provide an RPT file tomorrow with more details.

**Comment by PabstMirror** [comment]
Last line is `19:04:21 [0,78.476,0,"XEH: PreStart started."]`

But it also looks like you are running `Advanced Combat Environment 3.5.0`

There might be some kind of compatiblity issue with that version of ace and 1.60/new cba?

I would try with ace 3.5.1 - https://github.com/acemod/ACE3/releases/latest

**Comment by Army0104** [comment]
Unfortunately it's still existing with version 3.5.1
[arma3server_2016-06-04_01-44-15.rpt.txt](https://github.com/acemod/ACE3/files/298562/arma3server_2016-06-04_01-44-15.rpt.txt)

**Comment by commy2** [comment]
Can you retry without these:
```
19:04:17 D:\home\sid_59241\arma3\@ace\addons\ace_compat_rhs_afrf3.pbo - e2c75762
19:04:17 D:\home\sid_59241\arma3\@ace\addons\ace_compat_rh_de.pbo - e2c75762
```

**Comment by Army0104** [comment]
It working!
I've removed

ace_compat_rhs_afrf3.pbo
ace_compat_rhs_usf3.pbo
ace_compat_rh_de.pbo

and now the server is starting correctly.

**Comment by commy2** [comment]
Nice. Don't use these files without RHS. What about @JR-Robinson?

**Comment by Army0104** [comment]
I think this error also appeared with RHS enabled. But I might be mistaken. Nevertheless I've decided to not use RHS at all because I wasn't using it that much. Thanks for the help.

**Comment by Glowbal** [comment]
> ace_compat_rh_de.pbo

This is not a RHS compatability pbo. That is probably why, if you are not loading with RH (weapons pack iirc).

**Comment by JR-Robinson** [comment]
I'm using RHS, so that doesn't apply to me :P

**Comment by JR-Robinson** [comment]
I don't actually have those PBOs in my folders, that might be my problem lmao

**Comment by commy2** [comment]
Uploading a server RPT file of a crashed session is required to figure this out.

**Comment by commy2** [comment]
You open:
```
%LOCALAPPDATA%\Arma 3
```
and select the correct *.rpt file. They are named after the session starting time.

You open that file with any texteditor and ctrl+a, ctrl+c the whole content.

You paste that into a gist:
https://gist.github.com/
Save it and send us the link here.

**Comment by JR-Robinson** [comment]
This right? 

https://gist.github.com/JR-Robinson/e3fe17f1af790452673d8339f74b2551

**Comment by JR-Robinson** [comment]
https://gist.github.com/JR-Robinson/498854f28daf7d8cc1072ede6a174b73

this one is loading without Rh is think so the Error shouldn't matter still doesn't load either way

**Comment by JR-Robinson** [comment]
I have since removed the RH mod and still not coming up

**Comment by JR-Robinson** [comment]
Current RPT

https://gist.github.com/JR-Robinson/c973453a817a46283e727ad6b7318517

**Comment by commy2** [comment]
What if you only start the game with CBA and ACE (no RHS and MCC) ?

**Comment by JR-Robinson** [comment]
I get the Error that I need RHS as I have the Compatibility PBOs which is normal that's about it

**Comment by JR-Robinson** [comment]
RPT for that

https://gist.github.com/JR-Robinson/326d2d58e26702cc1307c042b1ffd90e

**Comment by commy2** [comment]
Also disable:
```
19:40:30 C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@Ares\addons\ares_zeusextensions.pbo - unknown
19:40:30 C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@task_force_radio\addons\task_force_radio.pbo - unknown
19:40:30 C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@task_force_radio\addons\task_force_radio_items.pbo - unknown
```
and temporarily remove these files:
```
19:40:30 C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@ace\addons\ace_compat_rhs_afrf3.pbo - 0add2369
19:40:30 C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@ace\addons\ace_compat_rhs_usf3.pbo - 0add2369
```

**Comment by jonpas** [comment]
@JR-Robinson has this been resolved on your end?

**Comment by esteldunedain** [comment]
Closed due to lack of feedback
