### ISSUE TITLE
Disable ACE3 Helicopter Gun Stabilization

### ISSUE THREAD

**Issue by JudahHarvey** [acemod/ACE3#3866]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
-@FZA-Ah64 (Franze- NodUnit AH-64D longbow for ArmA 3

**Description:**
- The FZ-Ah64 already has it's own stabilization, which conflicts the with the ACE3 stabilization. This makes the helicopter's gunner seat exceptionally gittery in multiplayer. If we could disable the gun stabilization for ACE3, it may alleviate this issue tremendously. Doing this with a script command, so we could differentiate between vehicles we want to disable would be optimal.

**Steps to reproduce:**
- Place FZA-Ah64D with or withour radar
- Step into the gunner seat with another human flying.
- Attempt to zoom in past level 2, observer exceptional "Jitteryness" and instability.

**Where did the issue occur***
Dedicated Server, Listen Server.

**Placed Modules:**
Not Applicable.

**Comment by bux578** [comment]
Sounds like a desync between pilot and gunner. It's even worse if the pilot uses the "auto flight" option (Default key "X"). Happens in vanilla too. Could you record a video so that we get a better grasp of the "issue"?

**Comment by esteldunedain** [comment]
As far as I know, ACE does not stabilize the turret via scripting in any way. Instead it's done through config for the vanilla Comanche. The only way that could afect the modded AH64 is if it inherits from the vanilla unit, which it shouldn't.

Most likely it's not related to ACE

**Comment by PabstMirror** [comment]
I checked and their inheritance is fine (not off the comanche)
```
class fza_ah64base: Helicopter
```
@JudahHarvey - could this be due to changes in 1.60? Does it work correctly without ace?

**Comment by esteldunedain** [comment]
Closed due to lack of feedback.
