### ISSUE TITLE
ACE 3 No interaction Menue on Dedicated /Closed

### ISSUE THREAD

**Issue by MrBlack581** [acemod/ACE3#3875]
Arma 3 Version 1.60.136470 stabel
ACE3 Version: 3.5.1

**Mods:**
**@CBA_A3**
**@ace**
@RHSUSAF
@RHSAFRF
@task_force_radio
@TRYK Uniform Pack

**Description:**
I can´t use the Interaction Menue on the Server in one Mission. In self created Server I can use it with all Missions

Tried Self Interaction Menue (Left STRG + Windows) and Interaction Menue (Windows)

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

http://pastebin.com/09PVZuLm

**Comment by bux578** [comment]
> If you have found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using only @CBA_A3 and @ace on a newly created mission.

**Comment by commy2** [comment]
That is not a RPT file. We need an RPT file, preferably one of the client and server each.

**Comment by MrBlack581** [comment]
Okay, where I can find the Client/Server RPT File ? I am going to try it out (only ace and cba) when my windows computer fix the update problem (Failure configuring Windows updates.)

**Comment by commy2** [comment]
```
%LOCALAPPDATA%\Arma 3
```

**Comment by MrBlack581** [comment]
Okay, there are no RPT Files on the Server Client RPT File is on Pastebin: http://pastebin.com/QF6Gy0Cv Its only with CBA and ACE3

**Comment by MrBlack581** [comment]
Oh by the way if i start the server this error is comming up
![unbenannt](https://cloud.githubusercontent.com/assets/18558585/15807222/6d095fbe-2b58-11e6-9187-5cd4b0333eca.PNG)

**Comment by jonpas** [comment]
You have not uploaded the full client RPT file, but here is your issue:
> 19:59:18 [21651,650.461,0,"CBA_VERSIONING_SERVER: *cba=1.1.23.150604*, ace=3.5.1.0, "]

Update your CBA, there is already version 2.4.0 released: https://github.com/CBATeam/CBA_A3/releases/latest

**Comment by MrBlack581** [comment]
Okay, thank you very much, i downloadet cba from armaholic ... thanks for the help
