### ISSUE TITLE
Basics for beginners 

### ISSUE THREAD

**Issue by RoadhouseAndRoundhouse** [acemod/ACE3#3879]
Having just downloaded ACE and arma itself, and seeing myself sinking some serious hours into both, i was just wondering if you could add some official tutorials for both basic and advanced features of the mod on the main page, similar to dyslexics videos on the arma webpage. i've tried looking through youtube for comprehensive i understand, but cant find anything substantial. This might not be the place to put this request, but i just want to learn the right way, if that makes sense.

**Comment by ShizCalev** [comment]
http://ace3mod.com/wiki/feature/

**Comment by bux578** [comment]
This might be better in the forums: https://forums.bistudio.com/topic/181341-ace3-a-collaborative-merger-between-agm-cse-and-ace/
