### ISSUE TITLE
RHS M107 overheating bug

### ISSUE THREAD

**Issue by CAMPOste** [acemod/ACE3#3881]
**Arma 3 Version: last
**CBA Version: last
**ACE3 Version: last

**Mods:**
- `@CBA_A3`
- `@ace`
- '@RHS All

Barrett from RHS modification does not work well with the ACE. This is due to very rapid overheating of the gun barrel

**Comment by PabstMirror** [comment]
RHS has their M107 configured to weigh 91 grams, when it should be closer to 12900g.
I guess we could fix it in the RHS compat.

**Comment by esteldunedain** [comment]
> RHS has their M107 configured to weigh 91 grams, when it should be closer to 12900g.

@CAMPOste, idealy this should be reported to RHS

**Comment by commy2** [comment]
This is an obvious bug in RHS. The weight / mass of the M107 is unreasonably low. Close?

**Comment by PabstMirror** [comment]
http://feedback.rhsmods.org/view.php?id=2155
>Fixed in Version	0.4.1.1

**Comment by dramabeats** [comment]
mm this is still an issue

**Comment by PabstMirror** [comment]
Seems unchanged in RHS 4.1.1
Added note to their tracker
