### ISSUE TITLE
Instant death prevention and revive for AI in player squad or side only

### ISSUE THREAD

**Issue by taro8** [acemod/ACE3#3882]
Right now the instant death prevention seems to affect every AI including opposing faction. Is there any way to configure the revive, prevention of instant death and going unconscious so it only affects player and his squad or player side only?

**Comment by Glowbal** [comment]
Hi @taro8, 

You can set prevent instant death for specific units by using a variable `ace_medical_preventInstaDeath`.

Example:

```sqf
UNIT setvariable ["ace_medical_preventInstaDeath", true, true];
```

You would apply this to all units in your player squad.
