### ISSUE TITLE
character gets damage to all of his parts of the body, when he falls down

### ISSUE THREAD

**Issue by BlackburnUTG** [acemod/ACE3#3885]
Arma 3 Version: 1.60 (stable)
CBA Version: 2.3.1 (stable)
ACE3 Version: 3.5.1 (stable)

Mods:

    @CBA_A3
    @ace

**Description:**
when the character falls down from  the 4 meters heights: he gets damage to all of his parts of the body (head,left arm,right arm, right leg,left leg, body)
4meters is the minimum height, when the character starts to take damage, and I think this "minimum hight" must be increased. And why he doesnt takes damage to only the legs?
**Steps to reproduce:**
Launch the 3D Editor, place bunker and unit with rangefinder

**Where did the issue occur?**
Self-Hosted Multiplayer / Singleplayer / Editor #(Singleplayer)

**Placed Modules:**
None.
![20160607143639_1](https://cloud.githubusercontent.com/assets/19798113/15857788/711178ba-2cbd-11e6-9408-1b2490c8afce.jpg)
![20160607143601_1](https://cloud.githubusercontent.com/assets/19798113/15857787/710fd014-2cbd-11e6-8857-c961730ffde9.jpg)

**Comment by PabstMirror** [comment]
Fixed via #3629
