### ISSUE TITLE
Laserpointer is visible through NVG border

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#3886]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (dev `f9a05d3266da57a0e5dfb7ac4aba5d326f5a92d8`)
**ACE3 Version:** `3.5.1` (dev `1c95c883e0d9d2fe93970d826c9be413320e21fa`)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Laserpointer is visible through NVG border.  
  http://i.imgur.com/RZcwXTn.jpg

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
- N/A

**Comment by commy2** [comment]
I don't think this is fixable.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 130 days without any activity.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 273 days without any activity.

**Comment by commy2** [comment]
Yes, because there is no way to fix this. ^

**Comment by Neviothr** [comment]
@commy2 see #4694.

**Comment by commy2** [comment]
That PR has nothing to do with this.

**Comment by Neviothr** [comment]
> And will close #3886

**Comment by commy2** [comment]
I really doubt it.

**Comment by jokoho48** [comment]
@commy2 with #4694 there is no black border left. so yes it would close it

**Comment by Neviothr** [comment]
With ST NVG, the black nvm border is semi transparent, so this issue basically becomes a feature.

**Comment by commy2** [comment]
Yes, but ACE is modular, so the problem just disappears when using the new NVG component. It's still not solved on it's own.

**Comment by jonpas** [comment]
Fixed as much as we can fix.
