### ISSUE TITLE
Problem with the mortar table

### ISSUE THREAD

**Issue by voodoo23** [acemod/ACE3#3888]
**Arma 3 Version:** `1.60` stable
**CBA Version:** `2.4.1` stable
**ACE3 Version:** `3.5.1` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Discordance in the mortar table values between the virtual arsenal and altis/stratis. 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / solo

**Placed Modules:**
- none and the ace mortar module

**RPT log file:**
- N/A

**Comment by PabstMirror** [comment]
Are the tables wrong? How are the different in a normal mission compared with the virtual arsenal?

**Comment by voodoo23** [comment]
problem solved : tables are differents if you use air resistance or not.
