### ISSUE TITLE
Unknown Post-Init handler is taking way too long on Altis

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#389]
19:34:48 [20960,139.184,0,"WARNING: PostInit did not finish in a timely fashion"]

The post-init handler is taking 75+ seconds to load for Altis when spawning on editor in the middle of nowhere, on a hill.

This behavior does not replicate on Stratis or VR. So it appears a post-init is iterating objects or something, and causing it to drastically lag. I am not aware of a way to check which postinit handler is taking too long in ACE, so its anyones best guess at what is taking too long.

Has anyone written code which is iterating anything in PostInit? Specifically around the player?

Position on map I am spawning causing the issue:
[9598.42,12406.5,14.931]

**Comment by jaynus** [comment]
Uploaded bugged mission to slack: 
https://ace3mod.slack.com/files/jaynus/F04BQ54F1/hanging_mission.zip

Repro's every time. the mission has nothing in it.

**Comment by esteldunedain** [comment]
Sorry @jaynus, I stil cannot reproduce the issue, even with that mission.

**Comment by jaynus** [comment]
Most likely my setup then, we'll let this die.
