### ISSUE TITLE
Taser Kill Targets

### ISSUE THREAD

**Issue by r0lling** [acemod/ACE3#3896]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.0` (stable / dev + commit hash)
**ACE3 Version:** `3.5.1` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- @TFAR
- Own Mod Package
@Australia
@CUP 

**Description:**
- When Taser someone he gets killed

**Steps to reproduce:**
- Take Taser, Taser target, Target dead

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- there is no error in rpt file. cause i think the weapon makes damage what it should not do.

**Comment by Glowbal** [comment]
We have no tasers in ACE or in vanilla.
