### ISSUE TITLE
Ace optics causes textures flickering

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#3899]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Ace optics causes textures flickering after 1.60 arma patch. My friends helped me to test this and 6 out of 7 guys had this problem. One guy didn't have the problem actually, we don't know why. He was on an AMD card, but one of the other 6 guys had AMD too and had this bug, so I'm not totally sure if that's related.
Video.
https://www.youtube.com/watch?v=8s-JsJ3N0j8&feature=youtu.be
First part of the video is with optics pbo enabled.
Second part of the video (from 0:24) is with optics pbo disabled.

**Steps to reproduce:**
- Get in vehicle.
- Turn on PIP.
- Take a look around.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
With optics.
https://gist.github.com/rebelvg/7be66516e8bb727b4aa8a69bf542b23e
Without optics.
https://gist.github.com/rebelvg/50c19e16440796b8c98e1191c6f9aa62
Mission file used for video.
https://gist.github.com/rebelvg/d1c064a848968ad1de95c439b6677c64

**Comment by PabstMirror** [comment]
This is a fantastic bug report, and major thanks for tracking down the specific module.
TBH I've been annoyed by that slight flicker as well, I had no idea we were causing it.

**Comment by commy2** [comment]
Looks like BI broke this with the new shader.

**Comment by rebelvg** [comment]
Amazing job and thanks for the fix, love you guys!
