### ISSUE TITLE
Takistan, Zargabad, Chernarus weather data missing.

### ISSUE THREAD

**Issue by sargken** [acemod/ACE3#3906]
**Arma 3 Version:** `1.6` (stable / rc / dev)
**CBA Version:** `Newest` (stable / dev + commit hash)
**ACE3 Version:** `3.5.1` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- cup terrains

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.
If the weather for ACEs dynamic weather goes here it is missing these 3 popular maps. 
https://github.com/acemod/ACE3/blob/a2124a6b450695df76f6efb75006059af2f681aa/addons/weather/CfgWorlds.hpp

**Comment by jokoho48** [comment]
no they are not missing they are just not in the config to not create a dependency. they can found here: https://github.com/acemod/ACE3/blob/a2124a6b450695df76f6efb75006059af2f681aa/addons/weather/functions/fnc_getMapData.sqf

**Comment by PabstMirror** [comment]
Map weather can be stored in the config, but we also load settings via sqf lookup based on map name.

Check out:
https://github.com/acemod/ACE3/blob/master/addons/weather/functions/fnc_getMapData.sqf#L81

It's a little confusing, but I think the idea was that map makers can define weather via config.
But we need the sqf lookup for most maps, so we don't add configs for maps that might not exist.
