### ISSUE TITLE
UI / group bar re-appears on diary open

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#3907]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.5.1` (1136a57e4288f03bcc3f1cd5770982765acc1f2b)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Group menu from the left bottom corner re-appears when diary is opened and closed (default J key). Can be hidden by showHUD command again. If shouwHUD array exists in description ext, the showHUD command gets completely blocked (stops doing anything). Group menu can be hidden again on latest master when you switch to main weapon from any other weapon (not vise-versa).

**Steps to reproduce:**
- Place a group.
- Play as a leader.
- Open and close diary (J key).

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- N/A.

**Comment by rebelvg** [comment]
Actually diary not only reverts group menu bar, it reset whole showHUD array.

**Comment by jonpas** [comment]
> If shouwHUD array exists in description ext, the showHUD command gets completely blocked (stops doing anything).

That's meant to work like that, latest master will also print RPT warning in that case when using the module. I should probably completely block custom settings in that case though.

**Comment by rebelvg** [comment]
Another find. Zeus interface resets showHUD array on closing too.
