### ISSUE TITLE
Update wiki / documentation

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#391]
- [x] http://koffeinflummi.github.io/ACE3/wiki/missionMaker/modules.html
- [x] http://koffeinflummi.github.io/ACE3/wiki/user/shourtcuts.html
- [ ] The rest ...

**Comment by ViperMaul** [comment]
Status?

**Comment by ulteq** [comment]
Are there any new modules/shortcuts which need to be added?

**Comment by bux578** [comment]
I'd bet that neither the shortcuts nor the modules are up to date

**Comment by ulteq** [comment]
I updated these a few days ago:
* https://github.com/acemod/ACE3/blob/master/documentation/missionmaker/modules.md
* https://github.com/acemod/ACE3/blob/master/documentation/user/shortcuts.md

**Comment by Glowbal** [comment]
The medical section is incorrect. It's all from AGM.
