### ISSUE TITLE
Finger - No Way to change Keybind

### ISSUE THREAD

**Issue by sargken** [acemod/ACE3#3913]
**Arma 3 Version:** `Stable` (stable / rc / dev)
**CBA Version:** `Stable` (stable / dev + commit hash)
**ACE3 Version:** `Stable` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
-There is no control change option to change your Finger point key. From shift + `

**Comment by sargken** [comment]
May be Invalid as my mission developer forgot to place down the module.

**Comment by PabstMirror** [comment]
If the module's setting isn't enabled, we don't add the keybind.
Which is a little weird, not sure if we should just always add it.

https://github.com/acemod/ACE3/blob/master/addons/finger/XEH_postInit.sqf

**Comment by jonpas** [comment]
We add it everywhere else. And check if it's enabled on key press.
