### ISSUE TITLE
How to add custom objects to ACE3 for Dragging / Carrying?

### ISSUE THREAD

**Issue by DanUKGB** [acemod/ACE3#3918]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.5.1 ` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Maybe some may not class this as an issue, but simply put I have looked everywhere and have yet to find a tutorial on how to add custom objects into ACE3 for the dragging / carrying functionality. So, would anyone be able to enlighten me? As you are probably aware ACE3 allows the player to use their interaction key on reasonably sized objects (e.g. Traffic Cones, Ammo Boxes, Spare Wheels, etc.) and perform actions such as dragging / carrying, loading, etc. I wanted to know how I would allow custom objects to be interacted with in this way.

**Steps to reproduce:**
- Hover your interaction key over a custom object, yet as you will see no option comes up on it to interact with it, carry it, drag it, load it, etc.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- N/A.

**Extra Notes:**
- Thanks to anyone who can help me, would be brilliant.
- If you require any further information, please let me know, I will be watching this thread constantly!

**Comment by PabstMirror** [comment]
Take a look at http://ace3mod.com/wiki/framework/dragging-framework.html

**Comment by DanUKGB** [comment]
@PabstMirror Thanks for the quick reply, I've already looked at this, and in all honesty it doesn't really make sense to me. It doesn't tell me where the file is that I need to edit/use, and what exactly I need to be inputting. Thanks.

**Comment by DanUKGB** [comment]
@PabstMirror Because at least if that guide wants me to edit the **_config.bin_** file in the **_ace_dragging_** PBO then it is not possible as this file is binarized. When un-binarized i can add those lines of code, yet then the entire dragging system in ACE does not work. Thanks.

**Comment by PabstMirror** [comment]
Here is SQF that will make all "Camping Lanterns" (Props -> Things -> Lamps) able to be carried.  You would just put this into init.sqf for a mission:

```
_fnc_makeCarrayble = { 
    params ["_object"]; 
    diag_log text format ["Making %1 [%2] Carrable", _object, typeOf _object]; 
    [_object, true, [0,0.5,1], 0] call ace_dragging_fnc_setCarryable; 
};
["Land_Camping_Light_F", "init", _fnc_makeCarrayble, true, [], true] call CBA_fnc_addClassEventHandler; 
```

**Comment by DanUKGB** [comment]
@PabstMirror OK that's great, I'll give that a go. But would I be able to use that same script to make **custom objects** draggable / carryable? As in **modded objects** that **do not** come in the base game of ARMA 3? Thanks again.

**Comment by PabstMirror** [comment]
This method should work on most objects, no matter their source.
All you need is the classname (the `Land_Camping_Light_F`) part.
You can get it by hovering over the item when placing in 3den or just doing `typeOf cursorObject` when looking at it.

**Comment by DanUKGB** [comment]
OK I'll give that a try and feedback with what result I get. Thanks.

**Comment by DanUKGB** [comment]
Hmm, I tried doing what you said and whilst the camping lights works (making camping lights draggable / carryable), when trying to use custom (modded) objects, it does not work.

**Comment by DanUKGB** [comment]
@PabstMirror not sure if you saw my replies because I didnt use the '@'. :)

**Comment by PabstMirror** [comment]
CBA's XEH are disabled on some objects (like buildings and furniture), so I guess `CBA_fnc_addClassEventHandler` won't work on them.

In the editor you will need to goto each one's init box and add: 
```
[this, true, [0,0,1], 0] call ace_dragging_fnc_setCarryable;
```

Note the args:
```
 * 2: Position offset for attachTo command <ARRAY> (default: [0,1,1])
 * 3: Direction in degree to rotate the object after attachTo <NUMBER> (default: 0)
```

One example of an object that doesn't do XEH events are the Sun Chairs (Furniture > Beach).
Here is a demo `config.cpp` that you can build into a simple mod that would make them drag-able:

```
class CfgPatches {
    class SunFun {
        units[] = {};
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = {"CBA_XEH"};
    };
};

//External Ref from CBA XEH:
class CBA_Extended_EventHandlers;

class CfgVehicles {
    class ThingX;
    class Land_Sun_chair_F: ThingX {
        
        //This makes then CBA EH compatible:
        class EventHandlers {
            class CBA_Extended_EventHandlers: CBA_Extended_EventHandlers {};
        };

        //ACE_Dragging:
        ace_dragging_canDrag = 1;  // Can be dragged (0-no, 1-yes)
        ace_dragging_dragPosition[] = {0, 1.2, 0};  // Offset of the model from the body while dragging (same as attachTo)
        ace_dragging_dragDirection = 90;  // Model direction while dragging (same as setDir after attachTo)
    };
};
```

**Comment by DanUKGB** [comment]
@PabstMirror you're a genius - thank you so much, this works brilliantly! Can't thank you enough for your help, keep up the good work! :)

**Comment by jtgibson01** [comment]
@DanUKGB Fixing non-physicalised items would be more or less impossible without being creating a full mod to add physics properties to the item, including a physics "level of detail" model (which usually requires the model be distributed as part of an open source licence, as it doesn't work against binarised LODs).
