### ISSUE TITLE
Update main menu additions for new Apex menu

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#3926]
![http://i.imgur.com/7aGTVus.jpg](http://i.imgur.com/7aGTVus.jpg)

**Comment by jonpas** [comment]
CBA only: https://gyazo.com/a604ba01358b25a30cfb5f8b56fd3616
ACE3: https://gyazo.com/6fad9b0a198ed6e52b3421b2b42bb8e0

**Comment by sargken** [comment]
Why don't you guys make another big Box next to the other 3 that say ACE 3 or something?

**Comment by bux578** [comment]
https://community.bistudio.com/wiki/Arma_3_Main_Menu

**Comment by PabstMirror** [comment]
Perhaps we should just eliminate it?
Most people are probably either going to be running ace with 
- steam workshop, which will update automatically
- Group Mod repository which should be updated regularly

**Comment by commy2** [comment]
I think think this box is fine. It should just be moved either up or down to avoid occluding the xbox / playstation settings-esque menu with the map previews.

**Comment by esteldunedain** [comment]
I still like that the box provides easy access to changelogs (specially new features) and a link to report issues. Those things are still useful even if you didn't install ACE manually.

**Comment by jonpas** [comment]
Done in #4051, just website edits have to be merged on release.
