### ISSUE TITLE
Custom objects for Carrying do not 'drop' properly.

### ISSUE THREAD

**Issue by DanUKGB** [acemod/ACE3#3928]
**Arma 3 Version:** `1.6` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.5.1` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
In order to allow custom objects (e.g. a Red Traffic Cone from the [PLP Urban Pack](http://steamcommunity.com/sharedfiles/filedetails/?id=701300272&searchtext=PLP)) to be carried I used this piece of code:

`[this, true, [0,0,1], 0] call ace_dragging_fnc_setCarryable;`

This code was given to me by @PabstMirror very kindly, and works just how I initially intended it to. However, with a little further investigation, I found that when you actually drop/release the object (Left Click) it goes straight to the ground, not colliding with anything in it's path. However how I want it to drop is the same way as other objects in ACE3 do, by dropping with physics, colliding with what it 'touches.'

**Steps to reproduce:**
- Load up the 3den editor.
- Get an object (preferably custom) which is not compatible with ACE3 carrying and put it on the floor.
- Put `[this, true, [0,0,1], 0] call ace_dragging_fnc_setCarryable;` into the object's initialisation box.
- Carry the object using the ACE3 interaction key.
- Drop it on the floor using Left Click.
- You should notice that the object does not collide with anything below it, instead almost 'teleporting' straight to the ground.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- N/A.

**Comment by jonpas** [comment]
If the object is not a physics objects than we can't change that. We teleport it to ground because otherwise it would be floating mid-air.

**Comment by DanUKGB** [comment]
@jonpas right I see, so does that mean there is no way around the problem whatsoever? Simply the idea was that people would get trucks and then be able to load furniture onto the back using ACE3. With this problem that seems not so possible anymore. D:

**Comment by jonpas** [comment]
Use the cargo system in that case.

**Comment by DanUKGB** [comment]
@jonpas well I would however as it is going to be a roleplay server/community, the idea of physically loading things seemed much better.

**Comment by jonpas** [comment]
That's not going to work well due to how physics work in Arma.

**Comment by DanUKGB** [comment]
@jonpas well the idea was that there would be script on the truck which allows them to attach all the objects on the back so that way they wouldn't move an inch. Almost as though they were strapping them on.

**Comment by DanUKGB** [comment]
@jonpas would that not be a good idea?

**Comment by jonpas** [comment]
Sure it's not a bad idea, but I don't think there is any other fix for floating objects. You can find other ways to position them properly or simply use objects that support it correctly.

**Comment by DanUKGB** [comment]
@jonpas very true, other than furniture, lots of things do have collisions like boxes of bricks, etc. yet it's a shame that there is no way to add any sort of makeshift physics to an object, literally all it needs to be able to do is fall to the ground like every other kind of object, which is somewhat frustrating.

**Comment by esteldunedain** [comment]
This is not fixable on our end
