### ISSUE TITLE
RHS Ballistic Glasses - Need Tweak

### ISSUE THREAD

**Issue by sargken** [acemod/ACE3#3931]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `stable` (stable / dev + commit hash)
**ACE3 Version:** `stable` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
-@RHSUSAF
-@RHSAFRF

**Description:**
- RHS Ballistic Glasses that are colored don't shade what you are seeing, instead they have like a goggles look.
I can provide Images if needed.

**Comment by sargken** [comment]
@jonpas Can you point me to where I need to look so I could possibly do a pull myself. For glasses tinting your UI.

**Comment by esteldunedain** [comment]
@sargken: the config should look somethings like this:

https://github.com/acemod/ACE3/blob/master/addons/goggles/config.cpp#L24-L90

And it should go here:
https://github.com/acemod/ACE3/blob/master/optionals/compat_rhs_afrf3/config.cpp

or here:
https://github.com/acemod/ACE3/blob/master/optionals/compat_rhs_usf3/config.cpp

**Comment by commy2** [comment]
Closed by #3941
