### ISSUE TITLE
Advanced Medical script errors.

### ISSUE THREAD

**Issue by nekoboisam** [acemod/ACE3#3933]
**Arma 3 Version:** `1.62` Sneak Preview/Dev
**CBA Version:** `2.4.1` stable, Workshop Version
**ACE3 Version:** `3.5.1.0` stable, workshop version

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
When using advanced medical, any time you shoot some one you will get script errors and they take no damage.

**Steps to reproduce:**
Setup advanced medical and shoot an AI or player.

**Where did the issue occur?**
Self-Hosted Multiplayer, Singleplayer, Editor (Singleplayer) ,Editor (Multiplayer)

**Placed Modules:**
Medical_Settings
Advanced_Medical_Settings

**RPT log file:**
 [gist](https://gist.github.com/nekoboisam/357c0fd9a996d1ff760cccdfba1fe2d4)

**Comment by jonpas** [comment]
Already fixed on master https://github.com/acemod/ACE3/pull/3895

**Comment by Glowbal** [comment]
Indeed already fixed. Thanks for reporting it to us though @nekoboisam
