### ISSUE TITLE
ACE 3 Interaction Menu Bug

### ISSUE THREAD

**Issue by 123aqw** [acemod/ACE3#3934]
**Arma 3 Version:** `x.xx` (stable / rc / dev) STABLE/LATEST 1.60
**CBA Version:** `2.x.x` (stable / dev + commit hash) WORSHOP version
**ACE3 Version:** `3.x.x` (stable / dev + commit hash) WORKSHOP version

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

So, I have ACE installed, and for the most part it's working great. However, I'm running into an issue involving the interaction menu. I can't really explain what the issue is, so I'll provide an example; 
Say that Pvt Jenkins McGee gets shot in the knee and is now complaing that they are injured. When I try to use the interaction menu to treat that wound, I open the menu, highlight bandage and release the windows key. So far so good, but when I release the windows key, the menu doesn't go away, it stays open until I open the self interaction menu (which happens to work fine). After doing that, the bandage doesn't get applied, and the interaction menu doesn't open at all and Pvt Jenkins McGee has to try and walk off the bullet wound. Keep in mind that the self interaction menu still works just fine. Anyone have any ideas on how to fix this?

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

Multiplayer Hosting map/missions

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.
NONE

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

https://gist.github.com/123aqw/aa561a8a42af6f4a4d15c4432e5b4678

**Comment by bux578** [comment]
You've didn't add all the mods you're using to the issue description. I can see something like Dragonfyre and @101_editor and stuff like that in the RPT.

Please try it with ONLY cba and ace3.

**Comment by 123aqw** [comment]
my friend have the same mods as me and its working fine for him i dont know why otherwise he should have had the same problems right ?

**Comment by 123aqw** [comment]
ok cba and ace 3 worked should i just try put every mod on and see if it works or just try 1 and 1 :P xD ?

**Comment by bux578** [comment]
One of the mods is conflicting. You could try turning on one mod at a time and look which one is conflicting.

**Comment by 123aqw** [comment]
how does my friend not have this problem ? thats like fuckig miracle that he dont have a single problem

**Comment by jonpas** [comment]
Could be load order of the mods, in that case it's still that mod's fault - not being configured correctly.

**Comment by 123aqw** [comment]
ah ok soo just 1 mod can do this to me but not my friend weird o.O

**Comment by jonpas** [comment]
Yes, because your mods may load in a different order than for your friend. I don't know if that's the reason, but it could be.

**Comment by 123aqw** [comment]
i dont get it why i am the person that have more problems then my friend xD but its cool to talk to support of my favorit mod of all time :dancer:  :+1:

**Comment by 123aqw** [comment]
i am gonna use my time to remove 1 and 1 mod :+1:

**Comment by jonpas** [comment]
It's a tedious job but not much else any of us can do. Good luck!

**Comment by 123aqw** [comment]
THX good luck with the mod and help ppl out :D like u did for me :+1:  :+1:

**Comment by 123aqw** [comment]
i found out the mod that messed with ace 3 :+1:  :100: % IBUILD
http://www.armaholic.com/page.php?id=27078 if i did read right its an ALPHA Mod
