### ISSUE TITLE
Advanced Throwing Issue

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#3939]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.5.1` (eedb406ae5605c2dd5663fd0b2de2bb9bf501b6b with advancedThrowing branch)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- If the grenade you're cooking disappears (by exploding or just by time of life limit), grenade throwing interface will stay, only option to remove it is to press reload which triggers some fallback mechanism.
Video.
https://www.youtube.com/watch?v=KP1906ClP_E

**Steps to reproduce:**
- Take a flashbang.
- Cook it.
- Wait a few seconds.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- N/A.

**Comment by jonpas** [comment]
Fixed by 98aa9c6dc883dee7b8b0fe7bc114fecf366447c6
Removal of interface will be shortly delayed, that's because object is still not null for some time after explosion (at least in case of flashbang).
