### ISSUE TITLE
APEX Optics

### ISSUE THREAD

**Issue by xStormforgex** [acemod/ACE3#3942]
**Arma 3 Version:** `1.63.136975` (dev)
**CBA Version:** `2.4.1.160606` (?)
**ACE3 Version:** `3.5.1.0` (?)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- APEX optics not working with older vanilla weapons with ACE3 activated.

**Steps to reproduce:**
- Load ACE3 & CBA, open editor, place unit, open edit loadout, click on primary weapons and try to add an APEX optic. Same issue when item looted and trying to attach during a SP mission. Optics attach normally without ACE3.

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Virtual Arsenal

**Placed Modules:**
- None

[RPT log.txt](https://github.com/acemod/ACE3/files/321618/RPT.log.txt)

**Comment by bux578** [comment]
@xStormforgex thinking about it, the issue could be aswell with CBA. Could you please try it with only CBA (without ACE) and see if the error happens aswell?

**Comment by commy2** [comment]
Joint rails isn't updated for APEX

**Comment by xStormforgex** [comment]
Completely forgot Joint Rails was part of CBA now. Yeah that is my bad.
