### ISSUE TITLE
Handcuffed unit can't be freed properly after locality change

### ISSUE THREAD

**Issue by SzwedzikPL** [acemod/ACE3#3950]
**Arma 3 Version:** `1.60 (stable)`
**CBA Version:** `2.4.1`
**ACE3 Version:** `latest master`

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- If you handcuff playable unit without player (owned by server/headless) you can't free it properly when player enter this unit. This happens becouse variable with EH ID (AnimChaned) is local and it's stored only on machine that owned unit when it was handcuffed. I think making https://github.com/acemod/ACE3/blob/master/addons/captives/functions/fnc_setHandcuffed.sqf#L99 global will solve problem but it needs to be checked.

**Steps to reproduce:**
- Handcuff playable AI
- Make someone enter this slot
- Try to free him

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- Not relevant

**RPT log file:**
- None

**Comment by esteldunedain** [comment]
Although I'm not 100% sure, I don't think that's the cause of the bug.

**Comment by SzwedzikPL** [comment]
> Although I'm not 100% sure, I don't think that's the cause of the bug.

I solved this problem today with `player removeAllEventHandlers "AnimChanged";` so that's my first guess

**Comment by esteldunedain** [comment]
Oh, sorry, I think I understand the issue. The server is still running the event AnimChanged EH, so it inmediately restores the capture status when the liberation animation starts. 

I don't think making the handler public is enough. The AnimChanged EH has to be removed on the original machine that owned the unit.

**Comment by Glowbal** [comment]
I think we need a locality switched eventhandler to clear out the animChanged EH, or a exit for non local units in the AnimChanged call.

**Comment by esteldunedain** [comment]
> I think we need a locality switched eventhandler to clear out the animChanged EH, or a exit for non local units in the AnimChanged call.

Yes, exactly. We do something like that in medical iirc.

**Comment by esteldunedain** [comment]
I'm working on this ATM
