### ISSUE TITLE
Server - Ace Interactive Menu Not Showing + Missing .pbo?

### ISSUE THREAD

**Issue by commando241** [acemod/ACE3#3953]
Arma 3 1.60
CBA Release Candidate 7 Hotfix2
ACE3 3.5.1

Mods: in use CBA_A3, ace

The error had occurred when Ace interactive menu wasn't showing up in the server but would show up in Single Player. When in the server the Ace Menu would work but had no letters in the option menu besides the Debug, and Headbug fix.

Added the optional CBA cba_enable_auto_xeh.pbo, still nothing.

So I had naturally assumed the servers version was bugged or corrupted. Proceeded to remove all my mods from the command line and put CBA and Ace only to make sure it wasn't some mods conflicting. Sure enough the problems still occurred.

Went ahead and deleted Ace, and reuploaded after a fresh download.

I had now ran into a new problem with the server telling me I didn't have ace_realisticnames in the server. Which makes no sense since I had just put a fresh copy into the server. Proceeded to check if the pbo was in ace. Sure enough it was.

I also decided not to use the Ace Testing map and use it on a vanilia mission and the error still had occurred. 

If I nothing make sense please do tell me.

Unsure if I had put it up right.
https://gist.github.com/commando241/af31c984f05b59c97851ee64c278309f
@Note: I had misspelled a word for the server to use the regular mission file.

**Comment by commando241** [comment]
Forgot to label as Bug, or of some sorts.

**Comment by commy2** [comment]
You are using a 2 year old CBA.

`5:54:32                      Community Base Addons v1.1.23 |              @CBA_A3 |      false |             GAME DIR | 4f78fdd82a9df886fa334832c9e5f8ae6ceb1a79 |  847c5e95 | C:\TCAFiles\Users\JeffreyT1\14842\@CBA_A3`

Current version is v2.4.1. You are using v1.1.23.
Get the latest version here: https://github.com/CBATeam/CBA_A3/releases

>Forgot to label as Bug, or of some sorts.

Only admins can put labels
