### ISSUE TITLE
Can Fragmentation Framework work with Bomb or Canon?

### ISSUE THREAD

**Issue by GodofMonkeys** [acemod/ACE3#3956]
**Arma 3 Version:** `1.6` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When use bomb(like GBU) or canon(gunship 20mm canon or AA Tank's canon). When they explode, they don't have fragmentation simulator, so like GBU exploded around people like up to 10 meters, they just injured but not died. This effect is not real. Can it be fix or add more parameter to Explosive System module?

**Steps to reproduce:**
- In editor add gunship or big gun vehicle.
- Shot beside target's group.

**Where did the issue occur?**
- Whole game

**Placed Modules:**
- None

**Comment by GFShining** [comment]
Like this
[https://github.com/users/GFShining/emails/23159038/confirm_verification/292a7fca52315cb75f4cbf13f6728736bd99d79d](url)

**Comment by GFShining** [comment]
Like this
[img]http://i.imgur.com/RI7M962.jpg[/img]

**Comment by esteldunedain** [comment]
The ammo you mention might not be correctly configured. GBU should certainly produce frags. However, the 20mm cannon might not be feasible for performance reasons.

It would be very useful if you could provide a list of all the vehicles you have detected that have this problem, specially if you can provide their classnames.

**Comment by GodofMonkeys** [comment]
@esteldunedain ok. I will give list for you.

**Comment by GodofMonkeys** [comment]
Hi @esteldunedain, after test, beside 30mm.

We believe this happen on official GBU bomb.

Classname is (2Rnd_GBU12_LGB,2Rnd_GBU12_LGB_MI10,4Rnd_Bomb_04_F). 

You can try to use these bomb to hit a troop's group. The perform not very effective. Not like a true 250kg bomb should do damage and destruction.

Thank you^^

**Comment by commy2** [comment]
fragmentations won't work with spawned GBUs. Just making sure you aren't using createVehicle ...

**Comment by SilentSpike** [comment]
If you do need to spawn them, you can use `[objNull, _ammo, _projectile, true] call ace_frag_fnc_addPfhRound`

**Comment by lolkij** [comment]
Sorry for offtop.
Is there any command to trace fragments?
Like this one for bullets: `[player] spawn BIS_fnc_traceBullets;`
