### ISSUE TITLE
82mm Mortar Smoke_82mm_AMOS_White is to weak

### ISSUE THREAD

**Issue by Halifax007** [acemod/ACE3#3967]
Hello

I'd like to ask, if it's possible to add an ace setting for the "Smoke_82mm_AMOS_White"? Out of my sight are the "Smoke_82mm_AMOS_White" grenades definitely to weak. They should do a heavier smoke for being more realistic.

Ace changed also the Flare_82mm_AMOS_White in the ace_grenades.pbo:

class Flare_82mm_AMOS_White: FlareCore {
        intensity = 80000;
        flareSize = 12;
        timeToLive = 60;
    };

It would be great, if we can send heavier smoke-grenades with the 82mm MK6 Mortar in future.

Thanx

**Comment by bux578** [comment]
For Reference: https://github.com/acemod/ACE3/pull/3940

Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
