### ISSUE TITLE
Block backpack

### ISSUE THREAD

**Issue by Xawery94** [acemod/ACE3#3968]
ACE Team. I submit ideas to add functionality to **block the backpack** by the player. This functionality was in the "AGM" and it was very well checked, especially during PvP matches.

It would be nice to see this functionality again.

**Comment by bux578** [comment]
Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
