### ISSUE TITLE
Vector doesn't work in FFV turret

### ISSUE THREAD

**Issue by VKing6** [acemod/ACE3#398]
The Vector's functions do not work when attempting to use it from a vehicle.

**Comment by jaynus** [comment]
Vanilla laser designator doesnt work either, this may be an engine issue.

**Comment by VKing6** [comment]
Depends on how the Vector stuff works, since I don't think it uses an arma laser object.
@commy2 should comment about I think.

**Comment by esteldunedain** [comment]
I think it's just that we are ignoring the keypresses of the vector if player is on board; if I'm correct it's a very easy fix.

**Comment by commy2** [comment]
I'll check.

**Comment by esteldunedain** [comment]
@commy2, about keypresses while boarded. "isNotInside" condition/exception doesn't test for FFV turrets, so various actions don't work in those. We should change this somehow.

**Comment by esteldunedain** [comment]
It works since https://github.com/acemod/ACE3/issues/506

The issue was duplicated
