### ISSUE TITLE
top down dont work - FGM-148

### ISSUE THREAD

**Issue by SharonX4** [acemod/ACE3#3988]
**Arma 3 Version:** newest  
**CBA Version:** newest  
**ACE3 Version:** newest  
**Mods:**
@CBA_A3`
@ace`
RHS:USF
RHS:AFRF
RHS:GREF
**Description:**
switch to top down attack doesn't
**Steps to reproduce:**
**place javelin soldier  press ctrl+tab DONT Work**
**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
ALL the above
**Placed Modules:**
 Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules. **None**

**Comment by esteldunedain** [comment]
What launcher are you using? The one in vanilla or the one from RHS? Please try to replicate without RHS first.

**Comment by SharonX4** [comment]
I talking about the RHS javelin FGM-148
בתאריך 25 ביונ 2016 16:02,‏ "Nicolás Badano" <notifications@github.com> כתב:

What launcher are you using? The one in vanilla or the one from RHS? Please
try to replicate without RHS first.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/acemod/ACE3/issues/3988#issuecomment-228539425>, or mute
the thread
<https://github.com/notifications/unsubscribe/ANOdARggl1wnNhu-JAxN3zRt891aXLIFks5qPScBgaJpZM4I-Vdy>
.

**Comment by esteldunedain** [comment]
Are you sure you're loading the `ACE_Compat_RHS_USF3` pbo from ACE optionals folder? That pbo enables our guidance system for the RHS Javelin launcher.

**Comment by SharonX4** [comment]
how do i know if it enabled?
בתאריך 25 ביונ 2016 17:37,‏ "Nicolás Badano" <notifications@github.com> כתב:

**Comment by esteldunedain** [comment]
To enable them you need to copy the compat pbos for the RHS mods from ACE's optional folder to ACE's addons folder. If it's not there then most likely it's not enabled.

**Comment by SharonX4** [comment]
every one of the user need to change it or is enough on server side?

**Comment by esteldunedain** [comment]
everyone needs to have them

**Comment by SharonX4** [comment]
OK

**Comment by SharonX4** [comment]
its work thank you
mark as solved
