### ISSUE TITLE
Add UIDs to ACE Event Handlers

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#40]
@NouberNou, according to commy the ACE event handlers ID are reused, so they are not really unique.

Could they be wrapped like you did for CBA PFH, so they produce a unique ID?

This would make removing them much more safe. Also more consistent.

**Comment by ViperMaul** [comment]
Checking Status?

**Comment by esteldunedain** [comment]
@vipermaul, nobody's working on this, and we restructured the code so this is no currently needed. I'd close this on an move on.

**Comment by PabstMirror** [comment]
I guess we can close?

**Comment by commy2** [comment]
close
