### ISSUE TITLE
Escape and other keys need to be enabled while unconcious

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#400]
Happened two nights ago:

1- Press `Esc` to open the options menu
2- Get shot and fall unconscious
3- Input is disabled and options menu can't be closed

Once waken up everything work alright again

**Comment by Glowbal** [comment]
Unconscious should either close all menus that are currently open or pressing esc while unconscious should do it. I think the latter may be the better option, in case someone was modifying client settings? Don't want the user to have to start over again.

**Comment by esteldunedain** [comment]
In AGM we blocked most keys when unconscious, but not all. We allowed:
- Esc key
- Entering Zeus
- Team switching
- I believe also chat (optionally)

**Comment by commy2** [comment]
disableUserInput is still a thing. Should still work like in AGM.

**Comment by esteldunedain** [comment]
> disableUserInput is still a thing. Should still work like in AGM.

Ok, probably it's not detecting exceptions properly due to CBA and all that.

**Comment by commy2** [comment]
Could be that the key handle isn't attached to the "unconsciousness" display. Can't remember exactly how I've done that.

**Comment by Glowbal** [comment]
I will take a look and fix it this weekend.

**Comment by Glowbal** [comment]
I gave this a try and everything seems to be working as intended. Esc keys are enabled while unconcious.

**Comment by Glowbal** [comment]
#480
