### ISSUE TITLE
** SOLVED ** Dedicated Server Mission failing to recognize PBO's.

### ISSUE THREAD

**Issue by Kosmonautilus** [acemod/ACE3#4015]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
-  `@ace`
-  `@asdg_jr`
- `@BC-Phoenix`
- `@BC-Tracers`
- `@Bornholm`
- `@CBA_A3`
- `@RHSAFRF`
- `@RHSGREF`
- `@RHSUSAF`
- `@Vcom_Driving`

**Description:**
When I join my own dedicated server, the loading screen switches into the role selection and back repeatedly and I get the message: "Cannot play/edit this mission as it is dependent on downloadable content that has been deleted. ace_cargo; cba_xeh; ace_dragging; ace_explosives." The problem is that when I check for these pbos in both client and server directories, they are present, and I have no clue as to why it is happening.

**Where did the issue occur?**
- Dedicated server role selection menu.

**Placed Modules:**
None. (originally had ace medical basic, ace medical advanced, ace revive settings, ace maps, ace explosives.)

**RPT Log**
http://pastebin.com/RWAwYiYQ

** SOLVED **
The mission file itself seemed to be corrupted.

**Comment by bux578** [comment]
Could you add the whole rpt file, please?

**Comment by Kosmonautilus** [comment]
Sure!

**Comment by bux578** [comment]
What was the solution? It might help others who stumble upon this issue here.
