### ISSUE TITLE
Advanced Medical Settings wont work in Apex_sneak_preview branch.

### ISSUE THREAD

**Issue by Flixss** [acemod/ACE3#4016]
**Arma 3 Version:** `1.62` Apex_sneak_preview
**CBA Version:** `Newest from Workshop` Apex_sneak_preview
**ACE3 Version:** `Newest from Workshop` Apex_sneak_preview

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
there is some error with the damage finding

**Steps to reproduce:**
go into editor add advanced medical settings
and go into server with friends they wont get wounds but can go unconscious

**Where did the issue occur?**
Hosting via Game browser

**Placed Modules:**
medical settings / medical menu settings / basic menu settings / repair settings / refuel settings / ream settings / cargo settings / zeus settings / weather / wind defection / sitting / Night vision / Name tags / map hearing / captive / advanced / ballistic / TFAR - frequencies , enforce usage , side radio 

**RPT log file:**
N/A

**Comment by PabstMirror** [comment]
Fixed by #3895 - next release should be soon
