### ISSUE TITLE
Fix script error in tactical ladder

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#4017]
https://github.com/acemod/ACE3/blob/master/addons/tacticalladder/functions/fnc_cancelTLdeploy.sqf#L34

> commy2 [23:07]  
>And this is why we should always use `forEach` and not `count`!!!

**Comment by PabstMirror** [comment]
Oddly, the error was from ACEX and fixed via https://github.com/acemod/ACEX/commit/62254c4c367848f93f7c570df4a769a3bd15cfee

I think checkFiles broke the whole postInit chain. So `ace_tacticalLadder_ladder` was nil instead of objNull.

`count` is actually ok for animate
```
{ objNull animate [_x, 0] } count ["a", "b"]; // safe
{ nil animate [_x, 0] } count ["a", "b"]; //error
```

**Comment by commy2** [comment]
It said `encountered: nil, expected: bool`
This games error reports are completely useless.

**Comment by PabstMirror** [comment]
Probably the wrong kind of nil :smile:

**Comment by Glowbal** [comment]
> I think checkFiles broke the whole postInit chain

We should probably make checkFiles a bit more robust in that case. But good that it's fixed :+1:
