### ISSUE TITLE
ACE not functioning properly on dedicated server

### ISSUE THREAD

**Issue by Kosmonautilus** [acemod/ACE3#4025]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@aceServer`
- `@asdg_jr`
- `@bc-phoenix`
- `@bornholm`
- `@cariboufrontier`
- `@rhsafrf`
- `@rhsgref`
- `@rhsusaf`
- `@st_gi`
- `@prkz`
- `@st_nametags`
- `@sthud`
- `@Vcom_Driving`

**Description:**
For some odd reason ACE doesn't load properly when a mission is loaded. On the client side, ace options as well as the options to change keybinds are visible, but unable to be configured with, while the interaction menus, medical system, and ACE items are either defunct or missing.

**Steps to reproduce:**
Enter a mission with any box containing ACE items, use both self and normal interaction key to open each respective menu (as it shouldn't appear) as well as checking the box, (finding it to be empty.)

**Where did the issue occur?**
- Dedicated (Hosted)

**Placed Modules:**
None

**RPT log file:**
ACE Debug Clipboard - http://pastebin.com/nf5JNNYX
Clientside RPT - http://pastebin.com/zjndxQ2V
 *FRAGMENTED Serverside RPT - http://pastebin.com/MaiNegK8 | http://pastebin.com/svSEP6Q5 |

* The hosting service I use does not have FTP, but a log viewer, which is completely broken, but I tried to compile the RPT files from the date of the problem together to the best of my abilities.

**Comment by Glowbal** [comment]
Hi @Kosmonautilus,

According to your server RPT log provided, your server is not being launched with any modifications. This is probably the reason you are experiencing these issues. You need all modifications you use on your client to be loaded and available on your server as well.

Note that you are also running one CBA version behind. The latest CBA is 3.4.1. It is recommended you update your CBA as well, however that will not resolve the issues you reported here.

**Comment by commy2** [comment]
```
23:02:02 ============================================================================================= List of mods ===============================================================================================
23:02:02 modsReadOnly = false
23:02:02 safeModsActivated = false
23:02:02 customMods = false
23:02:02 hash = 'A8C688151ED5B306E7675E80CE00A64C904FFDC9'
23:02:02 hashShort = 'e7338d0'
23:02:02                                               name |               modDir |    default |               origin |                                     hash | hashShort | fullPath
23:02:02 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
23:02:02                                  Arma 3 DLC Bundle |            dlcbundle |       true |            NOT FOUND |                                          |           |
23:02:02                                    Arma 3 Marksmen |                 mark |       true |             GAME DIR | 8a8bc2a7d7ad8251bcc82f29aea6d3f34ebffb3d |  1c11a244 | C:\TCAFiles\Users\DaedraC\15640\mark
23:02:02                                 Arma 3 Helicopters |                 heli |       true |             GAME DIR | 1614a75b4d3cceb5d296ca4101a589fba596aa5e |  9a800f11 | C:\TCAFiles\Users\DaedraC\15640\heli
23:02:02                                       Arma 3 Karts |                 kart |       true |             GAME DIR | 41f70c200a668f39e52eedf55e0c6f494aef1903 |  c9867676 | C:\TCAFiles\Users\DaedraC\15640\kart
23:02:02                                        Arma 3 Zeus |              curator |       true |             GAME DIR | fb1eec1e78a39cd021a71a293ae4ae1e00c98686 |   44f886e | C:\TCAFiles\Users\DaedraC\15640\curator
23:02:02                                             Arma 3 |                   A3 |       true |            NOT FOUND |                                          |           |
23:02:02 ==========================================================================================================================================================================================================
```

No mods on the server. The server has to have the same mods as every client

**Comment by Kosmonautilus** [comment]
That's weird, because of the fact that RHS is on, and in the mission I spawn with an AKM.

**Comment by commy2** [comment]
They don't, hence all the missing class errors in the server RPT.
