### ISSUE TITLE
New Problems

### ISSUE THREAD

**Issue by Bloodplayer** [acemod/ACE3#4026]
**ACE3 Version:** `3.6.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHS: United State Forces`
- `@RHS: Armed Forces of the Russian Federation`
**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.
![img_20160629_222427_hdr](https://cloud.githubusercontent.com/assets/20213865/16473155/fa6df4ee-3e6a-11e6-8e7a-030a76431b2f.jpg)
-also the Ammunition left in the magazin is shown and cant be turned off

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

*

**Comment by commy2** [comment]
Please upload a RPT.

**Comment by SzwedzikPL** [comment]
@commy2 https://github.com/acemod/ACE3/pull/3624 ?

**Comment by commy2** [comment]
Yes, but can't provide help without RPT.

**Comment by Tzujam** [comment]
Seeing the same error, and solved it.

In the previous ACE version, the files ace_compat_rhs_afrf3.pbo and ace_compat_rhs_usf3.pbo appeared in the ace/addons directory. In the new version, they do not appear in the addons directory, but appear in the ace/optionals directory.

Copying those two files from /optionals to /addons fixes that error message.

**Comment by bux578** [comment]
@Tzujam ACE3 never! has been released with those two files in the addons folder. It was always required to move them from optionals to addons if you want to have compatibility.

**Comment by Tzujam** [comment]
My mistake, then! I must have looked at an altered copy.
