### ISSUE TITLE
fadeMusic Not Working

### ISSUE THREAD

**Issue by JasperRab** [acemod/ACE3#4029]
**Arma 3 Version:** `1.60` (stable / rc / dev)
**CBA Version:** `2.4.1` (stable / dev + commit hash)
**ACE3 Version:** `3.6.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
The command fadeMusic does not seem to work if running the game with CBA and ACE, if you remove ACE it works.

**Steps to reproduce:**
Load up the game with CBA & ACE,
Go in the singleplayer editor, place a unit down, spawn in.
Execute the command: `playmusic "LeadTrack01_F_EPB";`.
Let it play a few seconds.
Execute the command: `5 fadeMusic 0;`
The music doesn't stop, if you are using the command `playmusic "";` it will stop however.

If you redo this with only CBA it works fine.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
None

**RPT log file:**
CBA & ACE: http://pastebin.com/H3fQusx7
CBA Only: http://pastebin.com/CnQvQ6Nq

**Comment by esteldunedain** [comment]
ACE Hearing constantly updates sound and music volume according to the state of combat deafness of the current unit, overriding any manual value introduced by scripts. Unfortunately this is not fixable without introducing an API.

If you really want to use music like that in a mission you can disable combat deafness simulation, either by tweaking the `ace_hearing_enableCombatDeafness` setting or using the `ACE_Hearing` module.

**Comment by PabstMirror** [comment]
Put this in init.sqf:
```
ace_hearing_disableVolumeUpdate = true;
```
This will have ace_hearing skip touching `fadeMusic`.
You could also set it to false after the cutscene or whatever you are doing and it would be re-enabled.

**Comment by Belhun** [comment]
Thank you for this comment i was comeing across this issue and was confused AF, didnt even get to the point of an RFT log before finding this issue

**Comment by sape1** [comment]
For anyone coming across this issue, I can confirm that this still behaves exactly as described.
