### ISSUE TITLE
No interaction menu

### ISSUE THREAD

**Issue by 111Insats** [acemod/ACE3#4031]
**Arma 3 Version:** `1.60.` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.6.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Interaction and self-interaction menu not working or showing up, nor ACE Options settings.

**Steps to reproduce:**
- Left Ctrl+Windows key / Windows key / Esc>ACE Options

**Where did the issue occur?**
- Editor (Singleplayer), Virtual Arsenal

**Placed Modules:**
- None > All

**RPT log file:**
- https://gist.github.com/111Insats/ea8eb2a0d61a8e421999a4b0122f681b

**Comment by bux578** [comment]
You're CBA version is outdated.
Update this first and try again, please: https://github.com/CBATeam/CBA_A3/releases

**Comment by 111Insats** [comment]
Updated and it worked, thank you and I apologize for wasting your time.
