### ISSUE TITLE
Unconscious unit without pulse has to be treated twice with PAK

### ISSUE THREAD

**Issue by l4ndl0rd** [acemod/ACE3#4035]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.6.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When a unit is knocked unconscious and has no pulse, after bandaging the wounds, the medic has to treat the patient twice with the PAK. The first treatment resets the wounds and the patient comes to very briefly, before being knocked out again. After the second treatment the patient is fine again.

We had the issue when playing normally on our server, then to investigate he issue further we removed any mods besides CBA and ACE (we did however not remove the compat.pbos we use) and set up a fresh test mission.

**Steps to reproduce:**
- Place three units on the map (the medic, a bystander to assist with CPR and the patient)
- Place medical modules for advanced treatment
- Shoot the patient
- Let the medic treat the wounds, while the other guy does CPR
- Treat the patient with the PAK

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- Medical Settings
- Advanced Medical Settings
- Revive Settings

**RPT log file:**
- https://gist.github.com/l4ndl0rd/432756959900e1f0ed3f0c252ce35584

**Comment by bux578** [comment]
I can confirm, we had the same issue on our public server.

**Comment by jonpas** [comment]
Fixed by #4056
