### ISSUE TITLE
Error at the start

### ISSUE THREAD

**Issue by IIIDARTIII** [acemod/ACE3#4038]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.6.0` (stable )

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- I just start the game and in main menu have error "No entry 'bin\config.bin/CfgWeapons.Single'." and also when i download my singleplayer campaign i have same message. I have 2 other mods, but when i left only CBA and ACE i still have same message, and when i delete ace and left only CBA, i have no errors 

**Where did the issue occur?**
-  Singleplayer 

**Placed Modules:**
- 'None'

**Comment by PabstMirror** [comment]
Fixed via #3999 - Will be in next release which we hope to have close to apex launch.

**Comment by commy2** [comment]
1.62 is not supported atm.
