### ISSUE TITLE
Gunbag Only able to store DMR's

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#4042]
**Arma 3 Version:** `1.60`
**CBA Version:** `2.4.1` (stable / dev + commit hash)
**ACE3 Version:** `3.6.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
The gunbags mechanism is only able to store DMR's. When trying to run a DMR + SMG/Rifle without the gunbag you could store the SMG/Rifle in a big bag and would be forced to dump the DMR. The current gunbag setup simply reverses this issue. As a gunbag owner IRL straps are setup so you could fit anything in there within its size constraints.

Allowing all primary weapons to be stored in a gun bag would also allow a switch weapon feature. this effectively being the same as the double weapon feature of ACE2.

**Steps to reproduce:**
N/A

**Where did the issue occur?**
N/A

**Placed Modules:**
N/A

**RPT log file:**
N/A

**Comment by esteldunedain** [comment]
I agree

**Comment by brainslush** [comment]
Same here. First thing I did in our repository was to make every assault rifle compatible with the gunbag. Only then it has some proper use. Otherwise it would be useless for marksmen.

**Comment by DanielLarusso** [comment]
Does we have to define every gun by gun?https://github.com/acemod/ACE3/blob/master/addons/gunbag/CfgWeapons.hpp

**Comment by bux578** [comment]
@DanielLarusso read what @commy2 wrote in his Pull Request just directly above your answer.

**Comment by jonpas** [comment]
This has been changed in #4063 and released in 3.6.1.

**Comment by john681611** [comment]
Improvement is better thanks but there is still no way to swap weapons effectively forcing you to put your primary on the ground to get the weapon out of your bag. Is this designed in?

**Comment by jonpas** [comment]
Please discuss that in the respective issue #4119
