### ISSUE TITLE
Swap Barrel Action isn't working

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#4044]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.6.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- it isn't working. neither as a selfinteraction, nor as an assistant automatic rifleman
**Steps to reproduce:**
- place a automatic rifleman on map grab an additional Barrel and try to swap barrel
**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer)
**Placed Modules:**
- zeus
**RPT log file:**
- http://pastebin.com/H76zQeWU

**Comment by madpat3** [comment]
check for "reload-launchers" as well. i've noticed not being able to reload the launcher of my Buddy, when i played as a "playable unit".

**Comment by Hailstorm12** [comment]
Don't know if it is a related issue, but i also couldn't link belts with another person

**Comment by esteldunedain** [comment]
I did a quick check of the code, and "reload launchers" nor "link belts" seem to be affected by this bug. I didn't check yet, but if they are not working it should be due to a different issue.

**Comment by madpat3** [comment]
reload launcher:
 "playable unit" checked?

**Comment by jonpas** [comment]
This issue has been fixed by #4045, please open another issue for whatever else is problematic.
