### ISSUE TITLE
Common Compatibility files as separate mods

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#4046]
**Arma 3 Version:** `1.60` (stable / rc / dev)
**CBA Version:** `2.4.1` (stable / dev + commit hash)
**ACE3 Version:** `3.6.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Unless there is a better way. (I dunno some kind of mod checking and selective loading)
I'm thinking primarily the RHS  (as its the most common) set just to make it easier for players to have correct compatibility.

**Steps to reproduce:**
N/A

**Where did the issue occur?**
N/A

**Placed Modules:**
N/A

**RPT log file:**
N/A

**Comment by esteldunedain** [comment]
That has been discussed and the idea was to migrate to such solution at some point. There's no timeline for that though afaik.

Also, this probably qualifies as a feature request.

**Comment by commy2** [comment]
I'm for keeping this open as discussion.
I think this would be the prefered way. CUP is using this method with CUP_COMP_ACE (or whatever they call it).

**Comment by jonpas** [comment]
It is what we opted for as well I believe, we just said we need to work on tools to make the whole process easier, I forgot what exactly we decided to do though.

**Comment by sargken** [comment]
Can't u guy's detect if a mod is enabled and then include the config that apply's the values.

**Comment by kripto202** [comment]
I've already uploaded the current compatibility for both types of rhs mods. I'll try to keep it up-to-date as best as i can.

**Comment by esteldunedain** [comment]
> Can't u guy's detect if a mod is enabled and then include the config that apply's the values.

Unfortunately that's not possible.

**Comment by john681611** [comment]
What about the opposite? Load all the compatibility configs then use a check for the mod that toggles the use of scripts. I assume this affects performance and causes a ton of inheritance errors which is why its not used.

What are the requirements to split these files into their own mod? (our clan just shoves them in the right folder structure to run as a mod and it works fine)

Could we not change the file system of the compatibility optionals from a list of PBO's to a set of mod folders and then upload the most commonly used ones to PWS? I would be happy to implement this.

Side note: No RHS GREF compatibility?
