### ISSUE TITLE
Add Spare Parts not working

### ISSUE THREAD

**Issue by gbblaster** [acemod/ACE3#4048]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.6.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Have been using the module for a while on our missions, right adter updateing to 3.6.0 it stopped working, I rebuilt the mission, but that did not help, I then attempted to create a simple mission with one vehicle and the module, didn't work either. 

**Steps to reproduce:**
- Create a mission with the ACE Repair module, set to add spare parts to vehicles, start mission, no spare parts. .

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer).

**Placed Modules:**
- ACE Repair.

**RPT log file:**
- http://pastebin.com/NvkzWMHu

**Comment by PabstMirror** [comment]
Fixed via #4037
