### ISSUE TITLE
No actions menu (Taru)

### ISSUE THREAD

**Issue by NorXAengell** [acemod/ACE3#4050]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.6.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Taru helicopter doesn't have interactions points (action menu) in exterior or interior.

**Steps to reproduce:**
- Add a taru (every model) and try to get the interaction nodes in or out the helicopter.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**RPT log file:**
-N/A atm

**Comment by PabstMirror** [comment]
@commy2 - this is an XEH problem (really has nothing to do with ACE)

I honestly don't get why they aren't working, if you look at config viewer the CBA XEH are there.

**Comment by commy2** [comment]
Is this about the Taru-Pods again, or the actual helicopters?

**Comment by PabstMirror** [comment]
No the helicopters are effected. Oddly it, seems unrelated to the pods besides the name.

**Comment by commy2** [comment]
```
class CfgPatches {
    class Dummy_Test_Addon {
        units[] = {};
        weapons[] = {};
        requiredAddons[] = {/*"A3_Air_F_Heli_Heli_Transport_04"*/};
        requiredVersion = 0.1;
    };
};

class CfgVehicles {
    class Helicopter_Base_F;
    class Helicopter_Base_H: Helicopter_Base_F {
        class EventHandlers;
    };
    class Heli_Transport_04_base_F: Helicopter_Base_H {
        class EventHandlers: EventHandlers {
            init = "diag_log ['init', _this]";
            class TEST_EventHandlers {
                init = "diag_log ['ex init', _this]";
            };
        };
    };
};
```

If I use this config patch, no event handler will fire, unless I uncomment `A3_Air_F_Heli_Heli_Transport_04` to push it back in the loading order.

I expected that `'init'` doesn't fire, but I don't understand why `'ex init'` doesn't either, despite never beeing overwritten. Seems like the internals of these things are very weak.

**Comment by commy2** [comment]
Conclusion is, that despite these "extended" event handlers from BI being in extra classes, the extra classes have to be added after the original event handlers class is.

Current loading order:
```
 7:11:29 cba_xeh
...
 7:11:29 A3_Air_F_Heli_Heli_Transport_04
```

```
diag_log text "Export loading order:";
{
    diag_log text _x;
} forEach ("true" configClasses (configFile >> "CfgPatches") apply {configName _x})
```

Potential problem going ahead:
- this is difficult / maybe impossible to detect, so 3rd party "fix" addons that add compatibility to xeh to 4th party objects can get rid of our RPT warnings without actually fixing anything

Task:
- We have to add every vehicles config patch as required addon to CBA_XEH to push it back in the loading order

Note:
- this will very likely get rid of our stupid Taru Pod work around too.

**Comment by commy2** [comment]
And not even that fixed it.

**Comment by commy2** [comment]
What actually works is poking the init entry. (probably only works for init events)

```
    class Helicopter_Base_F;
    class Helicopter_Base_H: Helicopter_Base_F {
        class EventHandlers;
    };
    class Heli_Transport_04_base_F: Helicopter_Base_H {
        class EventHandlers: EventHandlers {
            init = "";
        };
    };
```

I have no idea anymore, fml.

**Comment by NorXAengell** [comment]
If it can help, at this time if i launch the leight opfor mod (http://www.armaholic.com/page.php?id=27353) with ace and cba.
I have some sort of "normal" interaction. I really don't know why it "work" with this mod but it can provide some idea for a fix...

**Comment by PabstMirror** [comment]
It's interesting, the leigh opfor pack probably triggers the fallback loop which will fix the problem.
We added a fix for CBA so this should be properly fixed in next CBA release.

In the meantime, adding this to description.ext or a mini mod should fix:
```
class Extended_PreInit_EventHandlers {
    class fixXEH {
        init = "diag_log 'manual start fallback'; call CBA_fnc_startFallbackLoop;"
    };
};
```

The fallback loop needs to be started at pre-init for it to work on non-xeh compatible vehicles.
