### ISSUE TITLE
ERROR: ACE_player == commander vehicle ACE_player}) exitWith {false}; ... ' Error Missing ; File z\ace\addons\weaponselect\XEH_postinit.sqf, line 190

### ISSUE THREAD

**Issue by Maseddu** [acemod/ACE3#4053]
**Arma 3 Version:** `1.60.136` 
**CBA Version:** `2.4.1` 
**ACE3 Version:** `3.6.0`

**Mods:**
- `@CBA_A3`
- `@Cup - Terrain :Core`
- `@ace`

**Description:**
- when i start a scenario created by me , after i updated the ace from 3.5 to 3.6 i recive an error :
 if !(ACE_player != vehicle ACE_player && {ACE_player == commander vehicle ACE_player}) exitWith {false};
 ... '
Error Missing ;
File z\ace\addons\weaponselect\XEH_postinit.sqf, line 190

**Steps to reproduce:**
- i really do not know ho to reproduce ,there are a lot of module and scripts in my scenario , but when i was with the 3.5.1 it worked awesome until the update.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**Placed Modules:**
- i placed more than half ace modules (meidcal (all modules) ,engineer , repair ,refuel , sit, 
zeus,balistics,hear, interaction, captive,respawn,traking bluefor, microdagr mapfill,map ,spare parts,repair facility and vehicles,loadable objects,explosive),and :chemlite , respawn vehicle, respawn infantry , open/close doors, game master,zeus,set(fuel,damage,ammo).

**RPT log file:**
- https://gist.github.com/Maseddu/342e29aee8a43cbef3e20eee93d67cb9
i inserted both files (ace debug+rpt)

- thisis a screen of the error ![ace error](https://cloud.githubusercontent.com/assets/20289150/16570588/b93eb9d6-4248-11e6-89ef-7ccbc5f6530c.jpg)

i hope you can help me i'm going mad about this.

**Comment by esteldunedain** [comment]
I think you are probably defining "commander" as a global variable in one of the scripts. Can you do a quick search to check if you are doing that somewhere?

**Comment by jonpas** [comment]
The RPT does not show the script error. Can you upload RPT of when it happens?

**Comment by Maseddu** [comment]
the errror come out in the map before to continue to the map loading.
I'll try to do a .rpt again asap ,estel i used "commander" on a playable character to assign him the zeus module , do you think it is the cause?

**Comment by Maseddu** [comment]
i think estel found the error , i changed the variable name and it seems to work , i have no more the error message, i hope it will not appear later, but for now it gone! thank you both a lot!

**Comment by esteldunedain** [comment]
I'm glad to hear it.

Arma lets you do stupid stuff like that. You basically overrode the `commander` command; unfortunately Arma lets you do that with a bunch of keywords. Hence try to avoid using too common names for your units.
