### ISSUE TITLE
ACE not working in multiplayer

### ISSUE THREAD

**Issue by Gunbeard** [acemod/ACE3#4054]
**Arma 3 Version:** `1.60` (stable / rc / dev)
**CBA Version:** `2.4.1` (stable / dev + commit hash)
**ACE3 Version:** `3.6.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHSAFRF`
- `@RHSUSAF`
- `@RHSGREF`
- `@task_force_radio`

**Description:**
- Reccently I updated ACE on my server and the Self Interaction and Interaction menus do not seem to be loading as well as other ACE functions. But in Singleplayer everything works without issue.
**Steps to reproduce:**
- Update ACE version

**Where did the issue occur?**
- Dedicated Multiplayer Server

**Placed Modules:**
- None

**RPT log file:**
https://gist.github.com/Gunbeard/0ea42a421376c27c2069d2c48b82641f

**Comment by PabstMirror** [comment]
It says you are running `Community Base Addons v1.1.23`
But you also have some CBA files from the new release, not sure why.

I would delete the `@CBA_A3` folder and reinstall with latest release https://github.com/CBATeam/CBA_A3/releases

**Comment by Gunbeard** [comment]
Not sure what happened with my CBA but reinstalling worked. Thanks for the assistance.
