### ISSUE TITLE
All bandages and medications have the same mass

### ISSUE THREAD

**Issue by DanielLarusso** [acemod/ACE3#4058]
**Arma 3 Version:** `1.60` (stable / rc / dev)
**CBA Version:** `2.4.1` (stable / dev + commit hash)
**ACE3 Version:** `3.6.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- All bandages and medications have the same mass. I would realy appreciate it if all bandages and medications have the correct mass value. As it is now, there is no reason why I should carry packing bandage instead of elastic bandage. but if the packing bandage has less mass than the elasic I would consider my loadout again.

**Steps to reproduce:**
- N/A

**Where did the issue occur?**
- N/A

**Placed Modules:**
- N/A

**RPT log file:**
- N/A
- N/A

**Comment by commy2** [comment]
Hello,
this issue tracker is meant for bugs. We have an issue for suggestions / feature requests

ref. #3594
