### ISSUE TITLE
Problem when trying to release a unit or place explosive. 

### ISSUE THREAD

**Issue by gbblaster** [acemod/ACE3#4066]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.6.0` (stable )

**Mods:**
           @rhs_gref |   
           @fallujah |   
           @sthud_a3 |   
        @AliveServer |   
              @ALiVE |   
@CUP_Weapons_ACE_compat |
               @Ares |   
                @mcc |   
            @A3CR1_7 |   
               @TFAR |   
            @RHSUSAF |   
            @RHSAFRF |   
               @MELB |   
             @LOPFOR |   
        @CUP_Weapons |   
       @CUP_Terrains |   
            @ASDG_JR |   
            @ASR_AI3 |   
               @ace3 |   
             @CBA_A3 |   

**Description:**
- So we've been having a problem and I want to check if it is something with our mod combo or a known issue as I haven't found anything on older threads. 

First problem is sometimes when you drag a unit the release function doesn't work, if the mouse is clicked the weapon fires. 

Second problem is, when placing explosives though the ACE menu the same thing happens instead of placing the device, the weapon fires. 

**Steps to reproduce:**
- It is kind of random. It just happens to some and not to others.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- All ACE related are on the map. 

**RPT log file:**
- I'll post an RPT if needed.

**Comment by esteldunedain** [comment]
RPTs are badly needed for this one. You need also try to repro with only CBA and ACE first.

**Comment by PabstMirror** [comment]
`removeAllActions player` is one possible cause of this

You might want to try removing mods until it doesn't happen

**Comment by alganthe** [comment]
10 :banana: it's due to MCC

**Comment by gbblaster** [comment]
I've updated with all mods running in the mission. And here I've attached an RPT from a mission we ran last night. I will run without the other mods and try to recreate ASAP. 

[arma3server_2016-07-06_21-59-35.txt](https://github.com/acemod/ACE3/files/352879/arma3server_2016-07-06_21-59-35.txt)

**Comment by commy2** [comment]
Try it in a new mission with only CBA and ACE enabled.

**Comment by gbblaster** [comment]
I will, tonight. And upload the RPT. Thanks.

**Comment by gbblaster** [comment]
We ran a mission last night with only ACE, CBA and Task Force Radio. We had some problems starting the mission but that is the missions fault. Once I got it running it seemed that no one had problems releasing dragged or carried units and I was able to place explosives even after respawning a few times. 

One issue I did not mention upon opening the thread and that is also annoying and did repeat itself is that sometimes when reviving a player, right when we inject the Epi-pen, the player dies. We use basic medic system without medics cause we are a small unit, also lives are set to unlimited. Let me know if this should go to a different thread. 

I have posted the new RPT but I guess the issue is with other mods and most likely MCC. 

[arma3server_2016-07-07_23-05-07.txt](https://github.com/acemod/ACE3/files/354436/arma3server_2016-07-07_23-05-07.txt)

**Comment by esteldunedain** [comment]
> I guess the issue is with other mods and most likely MCC.

Thanks for testing this.

> One issue I did not mention upon opening the thread and that is also annoying and did repeat itself is that sometimes when reviving a player, right when we inject the Epi-pen, the player dies. 

Please open a different ticket for that and try to provide all the required information. ACE Medical is due for a complete rewrite at the moment, so it's probable that bugs like this should go away anyway soon.
