### ISSUE TITLE
cant use explosives while running ace

### ISSUE THREAD

**Issue by ayo-monty** [acemod/ACE3#4068]
**Arma 3 Version:** `1.60.136470` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.6.0.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
-i have spent days trying to learn to use explosive charges such as the m112 demo block the satchel charge and so on. i have figured out how to bring up the interaction menu and can "place" the charge however i can not attach the firing device to the explosives and i can not mouse scroll wheel through the timer settings as they do not show up at all. i have removed ace 3 and CBA and i was able to place and detonate all vanilla explosives with no issues. i have also spent countless hours on google and youtube looking for a fix or work around and have found nothing.

**Steps to reproduce:**
- load CBA and ACE 3 into arma 3. put m112 demolition block into inventory and m57 firing device(yes i have tried all of them) ctrl+win for interation menu explosives-place-m112 demolition block. place the block and you can see there is no interface for the fireing device or the timer.
**Where did the issue occur?**
-  Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by esteldunedain** [comment]
In a nutshell, explosives in ace work like this:
1- Place explosive with the "Self interaction menu" (Ctrl-Win Key by default)
2- Interact *with the explosive* with the "Interaction Menu" (Win Key by default) to select the trigger mechanism

For timed explosives you don't any additional item. For manually detonated explosives you need to have a manual or remote detonator equiped.

For further information please search for tutorials online.

**Comment by esteldunedain** [comment]
Here's a video I just found online showing how to arm a Claymore in ACE3:

https://youtu.be/A6YxsDYFApE

**Comment by jonpas** [comment]
In case you haven't read this yet, do read it: http://ace3mod.com/wiki/feature/explosives.html :)

**Comment by ayo-monty** [comment]
Thank you a million times over i couldnt find the tutorials anywhere
On Jul 7, 2016 6:10 PM, "jonpas" <notifications@github.com> wrote:

In case you haven't read this yet, do read it:
http://ace3mod.com/wiki/feature/explosives.html :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/acemod/ACE3/issues/4068#issuecomment-231251265>, or mute
the thread
<https://github.com/notifications/unsubscribe/ATZ1spmrj38D9YtaoogSJanFoj5zUQSIks5qTaOCgaJpZM4JHkb7>
.
