### ISSUE TITLE
[question]Issue with CBA 2.4.1

### ISSUE THREAD

**Issue by leopard20** [acemod/ACE3#4071]
Arma 3 Version: '1.56` (stable)
CBA Version: `2.4.1` (stable)
ACE3 Version: `3.6.0` (stable)

I can't launch the mod properly with CBA 2.4.1(the inventory and modifier key don't work), it says 'cba_ui requires a3_ui_f_data'. However, the game launches fine with cba v2.3.1, but still some features don't work (besides the keys mentioned). ACE 3.5.1 works fine with this version of cba.
My question is , is there a way I can use ACE v3.6.0 with cba 2.3.1? I want to use the following addons:
Goggles, attach, aircraft, movement, frag, hearing, laser, interaction, medical system and scope, plus all required files, of course.(it would be nice if ballistics and advanced ballistics work too, but they're less important to me)
Or even better, can you suggest a way to fix the issue with cba 2.4.1? I know you're not the creators of cba but you should know how it works.
Thanks

**Comment by Glowbal** [comment]
ACE requires the latest version of CBA. ACE3 v3.6.0 does not work with earlier CBA versions.

We also do not support older versions of Arma 3 with the latest ACE release. We often use the latest available scripting commands within ACE, which means older A3 versions will not work.

I see you already reported this issue with CBA. They will address the issue of not being able to use the latest CBA version on older Arma3 versions. I will therefor close this.

If you need further help, please feel welcome to visit us on our public Slack chat (http://slackin.ace3mod.com).
