### ISSUE TITLE
Naval mines can't get defused

### ISSUE THREAD

**Issue by DanielLarusso** [acemod/ACE3#4074]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.6.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- If I place a naval mine into the water an try to defuse it. Nothing happend.
If I place a naval mine on the ground I can defuse it, but after that I'm able to defuse it again and again and again.

**Steps to reproduce:**
- Place a naval mine into the water and try to defuse it

**Where did the issue occur?**
- Editor (Singleplayer) /  Virtual Arsenal

**Placed Modules:**
- explosive system

**Comment by jonpas** [comment]
Fixed by #4078

**Comment by bux578** [comment]
The game has Naval Mines....? Nice

**Comment by esteldunedain** [comment]
I remember them being on one of the first showcase SP missions back in alpha. Never saw them again.

**Comment by jonpas** [comment]
I saw them one when @daishiknyte used them in the form of large apparent half-buried land mines...
