### ISSUE TITLE
Infinite medical supplies

### ISSUE THREAD

**Issue by leopard20** [acemod/ACE3#4075]
Arma 3 Version: `1.58` (stable)
CBA Version: `2.4.1` (stable)
ACE3 Version:`3.6.0` (stable)

I finally got ACE 3.6.0 working! (By updating ARMA to 1.58)
Anyway, I don't know why I have infinite medical supplies (bandages, morphine injectors,...) when I use them on my teammates (only tested in singleplayer).

**Comment by jonpas** [comment]
[ACE3 3.6.0 is **NOT** compatible with Arma 3 1.58, it requires 1.60.](https://github.com/acemod/ACE3/blob/release/addons/main/script_mod.hpp#L15)

**Comment by PabstMirror** [comment]
By default you use your target's supplies before your own.
It's a setting, just do 
`ace_medical_setting_allowSharedEquipment = false;`
