### ISSUE TITLE
Vector 21 rangefinder issue

### ISSUE THREAD

**Issue by Hailstorm12** [acemod/ACE3#4088]
**Arma 3 Version:** `1.62.137494` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.6.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@aceX`

**Description:**
Vector 21 range finder and azimuth no longer work after apex update. 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Editor (Singleplayer) 

**Placed Modules:**
- None

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

https://gist.github.com/Hailstorm12/63d348910b6acae25c2980b11af3cc3c#file-gistfile1-txt

**Comment by jonpas** [comment]
Fixed by #4096
