### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by NiiRoZz** [acemod/ACE3#4093]
Hello, i don't follow guidelines because my error not in the game,

When i compile Ace 3, when is interaction.pbo i have an error,

" [WinError 2] File doesn"t exist 'P:\\z\\ace\\release\\@ace\\addons\\interaction.pbo' --> 'P:\\z\\ace\\release\\@ace\\addons\\ace_interaction.pbo' "

It's only occur when i compiling Interaction, i have already reinstall 2 times ace, and addons interaction

Logs when pboproject : 

``` In File \z\ace\addons\interaction\CfgVehicles.hpp: Line 731 Expected class, define, or varname
ERROR: \z\ace\addons\interaction\config.cpp is faulty
The addon name for \z\ace\addons\interaction\XEH_preStart.sqf cannot be determined
In File z\ace\addons\interaction\CfgEventHandlers.hpp: Line 4 Rap: rebuild reqaddons failed ```

Cordially, NiiRoZz

**Comment by jonpas** [comment]
Open pboProject, go to Setup and disable "rebuild RequiredAddons[]=".

**Comment by NiiRoZz** [comment]
I don't have any rebuild RequiredAddons[]= inside setup of pboproject :[https://gyazo.com/8d152845faf64dd7d9ac94fe4310f519](url)

**Comment by PabstMirror** [comment]
on newer versions its the "rebuild cfgPatches" checkbox

**Comment by jonpas** [comment]
Oh, @NiiRoZz remove `*.hpp` from "Exclude From Pbo".

**Comment by NiiRoZz** [comment]
@jonpas it's the same with exclude ``` *.hpp ```

**Comment by commy2** [comment]
untick `rebuild cfgPatches`
it's broken and stupid

**Comment by NiiRoZz** [comment]
Already untick ``` rebuild cfgPatches ``` @commy2

**Comment by jonpas** [comment]
Not sure what could cause this, can you upload the whole pboProject interaction.pbo log file?

**Comment by NiiRoZz** [comment]
I close this because it's my fault,

Sorry for your lost time ..

Cordially NiiRoZz

**Comment by jonpas** [comment]
What was the issue?

**Comment by NiiRoZz** [comment]
I have just added "}" With no attention and do this error,

And i have the samedi error With option_menu but With this, i'veux needed to decompile again arma 3, because i don't have 2 paa inside a3 folder

**Comment by jonpas** [comment]
Ah I see. Glad you resolved it.
