### ISSUE TITLE
Qilin armed spawns with no ammo

### ISSUE THREAD

**Issue by abramsba** [acemod/ACE3#4098]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
When placing a Qilin in the game with 100% ammo. To make sure I tested with and without ACE and with CBA but no ACE. 

**Steps to reproduce:**
Start Arma up with ACE, put a Qilin down and spawn.
https://www.youtube.com/watch?v=mqYiU92fmjQ

**Where did the issue occur?**
Singleplayer and Listen Multiplayer

**Placed Modules:**
None

**Comment by kripto202** [comment]
If i remember correctly, ammo amount goes from 0-1 where 1 is 100%. can you do a test where you change the ammo to 0.5?

**Comment by commy2** [comment]
kriptp, no. It's a bug and pabst fixed it

**Comment by jonpas** [comment]
Fixed by #4099
