### ISSUE TITLE
Selective UI sometimes breaks with ALiVE

### ISSUE THREAD

**Issue by mihal190** [acemod/ACE3#4100]
**Arma 3 Version:** `1.62` stable
**CBA Version:** `2.5.0.160711` stable 
**ACE3 Version:** `3.6.2` stable

**Mods:**
- `@CBA_A3`
- `@ace`
- `@Alive`

**Description:**
Error apear sometimes, Editing Module didn't appear or only for 3/6 players or only for Host

**Steps to reproduce:**
-Just make mission with Alive

**Where did the issue occur?**
- Self-Hosted Multiplaye

**Placed Modules:**
- Everyone

**RPT log file:**
https://drive.google.com/file/d/0B24obh9IGKUgNEluMk4wejRuWGM/view?usp=sharing

**Comment by jonpas** [comment]
Explanation: selective UI is not respected when ALiVE is also running.

**Comment by jonpas** [comment]
Downloaded ALiVE 1.1.0, tested local-hosted multiplayer, all works fine for me.

**Comment by mihal190** [comment]
master jonpas, do you just downloaded and loaded mission with alive? if yes right this work but if place all required modules to init Alive it didnt work.

**Comment by mihal190** [comment]
![20160719112936_1](https://cloud.githubusercontent.com/assets/20427209/16945131/2c50d5d8-4da4-11e6-8556-5ea101c87d91.jpg)
![20160719112940_1](https://cloud.githubusercontent.com/assets/20427209/16945133/2c536c62-4da4-11e6-9214-0ada04c70d77.jpg)
![20160719112917_1](https://cloud.githubusercontent.com/assets/20427209/16945128/2c4f3fa2-4da4-11e6-9bbe-bb7770dfea16.jpg)
![20160719112921_1](https://cloud.githubusercontent.com/assets/20427209/16945129/2c504b22-4da4-11e6-80e5-555c1cff486f.jpg)
![20160719112846_1](https://cloud.githubusercontent.com/assets/20427209/16945130/2c50b1ac-4da4-11e6-9f6a-b3f679c95ac6.jpg)
![20160719112924_1](https://cloud.githubusercontent.com/assets/20427209/16945132/2c5266fa-4da4-11e6-9ebf-3c57df9c6d53.jpg)
![20160719112903_1](https://cloud.githubusercontent.com/assets/20427209/16945135/2c6b6538-4da4-11e6-8790-7ae75fa57186.jpg)
![20160719112928_1](https://cloud.githubusercontent.com/assets/20427209/16945136/2c6c8ad0-4da4-11e6-9b41-2c3b1b8681ca.jpg)
![20160719112908_1](https://cloud.githubusercontent.com/assets/20427209/16945137/2c6cd666-4da4-11e6-98a6-903bf9f94270.jpg)
![20160719112931_1](https://cloud.githubusercontent.com/assets/20427209/16945139/2c7540f8-4da4-11e6-82f5-4fabc254f766.jpg)
![20160719112913_1](https://cloud.githubusercontent.com/assets/20427209/16945138/2c6fa9cc-4da4-11e6-9a4e-6ebcd44bcdc5.jpg)

**Comment by bux578** [comment]
Or you could simply upload the test mission :smile:

**Comment by jonpas** [comment]
That wouldn't be bad indeed.

**Comment by mihal190** [comment]
https://drive.google.com/file/d/0B24obh9IGKUgYnoxQ0pkdzVfWGM/view?usp=sharing

**Comment by jonpas** [comment]
After removing "TAOR Marker" (which had `1` and there is no marker like that) it worked correctly, you even have a large error message when you load in telling you that.
