### ISSUE TITLE
Check ammo overidden by reload

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#4101]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `2.5.0` (stable)
**ACE3 Version:** `3.6.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Attempting to check ammo using CTRL+R just reloads your gun.

**Steps to reproduce:**
1. Get Weapon + Mags
2. Attempt to check ammo

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
N/A

**RPT log file:**
N/A

**Comment by esteldunedain** [comment]
This is a consequence of the reload mutex. idk @commy2 if this is fixable. If not I'd recommend reverting that PR.

**Comment by commy2** [comment]
Use `playAction` instead of `doGesture` directly and return `true` in the keybind so it overwrites vanilla behaviour.

**Comment by Meiestrix** [comment]
Same problem for clearing jamms.

**Comment by commy2** [comment]
Yes, known

**Comment by jonpas** [comment]
Fixed by #4096
