### ISSUE TITLE
Command mode not working correctly with ace3

### ISSUE THREAD

**Issue by Zachariah1061** [acemod/ACE3#4102]
**Arma 3 Version:** `1.62` (stable / rc / dev)
**CBA Version:** `from steam workshop cba_a3` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` steamworkshop version (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@acex`

**Description:**
- When giving certain commands in singleplayer the character simply wont give the command, e.g: Calling for ammo or medic will result in the character staying silent and not calling for ammo.

**Steps to reproduce:**
- press 5 then 3, no command or call out is made.

**Where did the issue occur?**
-  Singleplayer

**Comment by bux578** [comment]
This is actually by design and due to the ace_noRadio. Please try removing it from the ace/addons folder and test again.

**Comment by commy2** [comment]
file is called:
`\@ace3\addons\ace_noradio.pbo`
remove it from the folder or change the file extension

**Comment by PabstMirror** [comment]
This is from the changes to CfgActions,
e.g. medical does:
```
class CfgActions {
    class None;
    class Heal: None {
        show = 0;
    };
};
```
For many of these we need to remove the vanilla actions as they are incompatible with our versions.
You can remove pbos (e.g. ace_medical, ace_norearm....) to restore these actions.

ACE has a multiplayer focus, we would like to support commanding AI as best we can, but there are going to be conflicts.

**Comment by Zachariah1061** [comment]
Tried testing without noradio.pbo but same issue should have mentioned that the troops bar is missing as well its no stress though i can turn it off when in single player.

Thanks for the help gouys, much appreciated.!!!
