### ISSUE TITLE
No spare barrel available to add to inventory

### ISSUE THREAD

**Issue by Kozlon** [acemod/ACE3#4103]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `stable (2.5.0.1)` (stable / dev + commit hash)
**ACE3 Version:** `stable (3.61)` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Lack of spare barrel appearing in virtual arsenal, Spare barrel is also absent when trying to manually add to a unit in editor

**Steps to reproduce:**
- Launch the game and go into any virtual arsenal in an exported mission or editor testing, there's simply a lack of a spare barrel that's addable to a backpack, regardless of the gun equipped

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

All of the above

**Placed Modules:**
- Both None, and All of Ace's Modules, Along with just interactions placed etc.

**Comment by commy2** [comment]
This is because it's a magazine now. Magazines don't appear in the Arsenal.

**Comment by PabstMirror** [comment]
to add barrels do `this addMagazine "ACE_SpareBarrel"`

the item commands also work, e.g.:
```
this addBackpack "B_FieldPack_oli"; 
this addItemToBackpack "ACE_SpareBarrel";
```

Because it is a magazine, and VA does not show magazines you can't use it will not show up, there is nothing we can do about this.

**Comment by esteldunedain** [comment]
I think we could create a dummy item for the spare barrel, and replace it later for a magazine once the game is running.
