### ISSUE TITLE
ACE makes main menu unusable at certain resolutions

### ISSUE THREAD

**Issue by MusicalAnvil** [acemod/ACE3#4104]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `2.5.0` (stable)
**ACE3 Version:** `3.6.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Using ACE and CBA makes the main menu unclickable around the middle area. It seems that the "Intel" on screen looks to be preventing usage of the middle section of the menu, as shown by area in the screenshot below.

**Steps to reproduce:**
- Boot up game to main menu with ACE and CBA versions above

**Where did the issue occur?**
- Main menu

**Screenshot**
Red coloured area to demonstrate approximate unclickable area for menus.
http://i.imgur.com/aNm5Q0F.jpg

**Comment by Armilio** [comment]
The same for me. And "ACE Options" there makes hard navigate in the singleplayer menu.

**Comment by kripto202** [comment]
right now the only way to work around it is to use your arrow keys till it gets fixed. I have had the same problem with RHS causing the same problem but once I ran the compatibility mod for rhs, it fixed the problem. I do know that some units upload mods to your addons folder in your arma directory. I would make sure you don't have a unit that does that type of style of mods.

**Comment by jonpas** [comment]
Which "certain resolutions"?

**Comment by PabstMirror** [comment]
This was removed from ACE in 3.6.1
Are you running any other mods, I think TFR can cause this issue

**Comment by MusicalAnvil** [comment]
Tried isolating the issue again today since I was really tired last night. It's not ACE and I can confirm it's TFR.

(@jonpas That was actually an error when I was writing the ticket up and still testing where I thought that was the case, forgot to fix it.)

**Comment by vlad8011** [comment]
So how to disable that "intel"? Already tried disabling it in ace 3 settings, but its still visible.

**Comment by bux578** [comment]
@vlad8011 It's a problem with Task Force Radio. Not with ACE3
