### ISSUE TITLE
Command bar gone when commanding AI

### ISSUE THREAD

**Issue by spapineau** [acemod/ACE3#4105]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When Ace is enabled you do not see the command bar when commanding AI. The command bar is the list of units at the bottom of the screen that denotes their number, combat roles, etc.

**Steps to reproduce:**
- Drop some units down. Put yourself as the leader and observe

**Where did the issue occur?**
- SPl

**Placed Modules:**
-none

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by jonpas** [comment]
That is by design, by default ACE3 Selective UI disables command bar, you can enable it by going to ACE Settings -> User Interface -> Command Bar. The reason this is by default disabled is that ACE3 is still highly focused on coop and realism.

**Comment by spapineau** [comment]
sweet jesus. ty!
