### ISSUE TITLE
Apex Menu - Needs Support

### ISSUE THREAD

**Issue by sargken** [acemod/ACE3#4106]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace
- RHS - USAF and AFRF
- Spec4Gear
- USAF Mod
- ALIVE

**Description:**
There is the ACE options button that appears in the main menu and it when opened is displayed behind everything else. 
Also when hovering over the ACE 3 button in the bottom right there was no highlight like the other 2 buttons have. I don't know if this was intentional or not just figured i would report it. 
http://images.akamai.steamusercontent.com/ugc/280730548757698051/236D871419A948B561A83B80026A794EDE47B6D4/

**Comment by jokoho48** [comment]
close infavor of #4104
