### ISSUE TITLE
ACE 3 Logos next to Stock Maps

### ISSUE THREAD

**Issue by sargken** [acemod/ACE3#4108]
**Arma 3 Version:** `stable ` (stable / rc / dev)
**CBA Version:** `stable ` (stable / dev + commit hash)
**ACE3 Version:** `stable ` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
-RHS
-Spec4Gear
-Alive

**Description:**
- When in the editor map selection screen you can see the ACE3 logo next to the Stock BI maps. It covers up the Tanoa Expansion Logo. I don't know if its intentional but I don't think the maps are edited are they?

**Comment by jonpas** [comment]
That is due to how BI reads the author, it will show the mod whichever last edited some config of it and we modify it for weather entries. Nothing we can do about.
