### ISSUE TITLE
Using the Virtual Arsenal with a weapon in the gunbag causes the weapon to disappear from the bag

### ISSUE THREAD

**Issue by thecuban** [acemod/ACE3#4118]
**Arma 3 Version:** 1.62
**CBA Version:** 3.0.0.160713
**ACE3 Version:** 3.6.1

**Mods:**
- @CBA_A3
- @ace

**Description:**
- Using the Virtual Arsenal with a weapon already in the gunbag causes the weapon to disappear from the bag after leaving the arsenal.

**Steps to reproduce:**
- place a weapon into the gunbag
- open the BIS Virtual Arsenal
- close the arsenal
- the weapon will now have disappeared from the gunbag

**Where did the issue occur?**
- Self-Hosted Multiplayer, Singleplayer, Editor (Singleplayer), Editor (Multiplayer), Virtual Arsenal

**Placed Modules:**
- None

**Comment by PabstMirror** [comment]
Same core problem as #3707
The VA seems to reset all your gear just by opening it, so backpack will lose the setVariables.

**Comment by kripto202** [comment]
is it possible to create gun bags with guns already inside to help fix this problem?

**Comment by thecuban** [comment]
You would need too many different gun bags for all the weapons, plus you'd somehow have to add more bags for each new mod weapon

**Comment by esteldunedain** [comment]
@kripto202, AFAIK the weapon inside the gunbag can be defined using a setVariable statement on the unit init field. So it's not possible from the Arsenal, but it is possible through scripting.

**Comment by PabstMirror** [comment]
@kripto202 - see code in https://github.com/acemod/ACE3/issues/4417#issuecomment-247739575

 Closing and merging this issue with #3707

**Comment by madpat3** [comment]
still no workaround? 
this is realy sad, since i finally found out, how to work with the ATragMX.

ps. i didn't want to revive closed issues (just a reminder of this issue).

**Comment by dedmen** [comment]
Shouldn't have been merged with #3707. This is a different issue of not keeping variables on the gunbag.
