### ISSUE TITLE
Cant switch gunbag weapon with active primary weapon

### ISSUE THREAD

**Issue by thecuban** [acemod/ACE3#4119]
**Arma 3 Version:** 1.62
**CBA Version:** 3.0.0.160713
**ACE3 Version:** 3.6.1

**Mods:**
- @CBA_A3
- @ace

**Description Pt1:**
- There is no simple way to switch between the active primary weapon and the second primary weapon stored in the gunbag. In order to switch between the two weapons the player has to undergo a complicated "dance" of putting weapons on the ground and removing and replacing weapons from the gunbag. 

**Steps to reproduce: (aka the "dance")**
- place a weapon (shall be referred to as Gun1) into the gunbag
- select a second primary weapon (shall be referred to as Gun2) to be held in the hands of the character as the active primary
- place Gun2 on the ground
- remove Gun1 from the gunbag
- place Gun1 on the ground
- pick up Gun2 from the ground
- place Gun2 into the gunbag
- pick up Gun 1 from the ground
- you have now switched from Gun2 to Gun1 as the active primary while placing Gun2 into the gunbag

**Description Pt2:**
- This dance required to change primary weapons using the gunbag takes an unnecessary amount of time and energy, causes the player to lose immersion and can get the player killed if the player needs to change weapons while under enemy contact.

**Where did the issue occur?**
- All game modes

**Placed Modules:**
- None

**Requested Change:**
- add a function to the interaction menu that allows the player to directly switch the active primary weapon and the primary weapon stored in the gunbag without having to preform the aforementioned "dance". the time taken to switch weapons relative to just placing a single weapon into the bag could be slightly increased for balancing purposes if desired.

**Comment by alganthe** [comment]
I can confirm the issue
ACE3 3.6.2 RC1
CBA_A3 3.0.0

**Comment by esteldunedain** [comment]
> add a function to the interaction menu that allows the player to directly switch the active primary weapon and the primary weapon stored in the gunbag without having to preform the aforementioned "dance". the time taken to switch weapons relative to just placing a single weapon into the bag could be slightly increased for balancing purposes if desired.

I'd 100% love this to happen, with a short progress bar. 

IMO the action should also be available when using regular backpacks (as long as the current weapon fits there).

**Comment by thecuban** [comment]
It could also be interesting to have two sizes of gunbag, not for the carried weapon but for the extra gear.  The current gunbag could be considered the normal size, then there could be a larger gunbag with more "pouches" that would allow for more auxiliary gear to be carried.

**Comment by commy2** [comment]
^ not gonna happen. The pack is for carrying another weapon and nothing more

**Comment by brainslush** [comment]
I like it the way it is b/c it prevents people from fast swaping between long range weapon and assault rifle. IRL it takes time to swap between to weapons. Place backpack on ground. Take out weapon. Put other weapon inside. Assamble or disassemble side rail component or bipod and vice versa.

**Comment by thecuban** [comment]
I agree that fast swapping would be unrealistic, hence my suggestion to extend the time it takes to switch the weapons in the bag. Not advocating for any kind of fast swapping, just the ability to swap without the necessity of walking about from ground pile to ground pile in orderto switch weapons. In reality, while it does take time to switch weapons to and from a gunbag, it doesn't necessarily take a large amount of space nore does it require as much physical movement as it does in the game. The primary reason for my submitting the issue was caused by a heavy increase in sniper casualties as a result of having to move about excessively in order to change primary weapons once in a hide site.

**Comment by crowmium** [comment]
I don't understand the complaint here. OP's sequence of events is identical to how it would have to occur in real life. You can't hold or manipulate two guns simultaneously. You would have to put one on the ground to manipulate the other in any meaningful way other than just carrying it in your hand. You certainly could not do this swap on the move. The current behavior is perfectly reasonable.

**Comment by thecuban** [comment]
While I dont disagree with the realism of swapping with the current system, you have to consider that this is still a game and at the end of the day you have to tailor towards that. The arma ground inventory system is clunky at best and can cause problems when switching between weapons and equipment on the ground. As I stated previously...

"Not advocating for any kind of fast swapping, just the ability to swap without the necessity of walking about from ground pile to ground pile in orderto switch weapons. In reality, while it does take time to switch weapons to and from a gunbag, it doesn't necessarily take a large amount of space nore does it require as much physical movement as it does in the game. The primary reason for my submitting the issue was caused by a heavy increase in sniper casualties as a result of having to move about excessively in order to change primary weapons once in a hide site."
