### ISSUE TITLE
Comanche doesn't roll

### ISSUE THREAD

**Issue by WadeDP** [acemod/ACE3#412]
Issue: When in the gunner seat for the Comanche, taking controls and then flying, it doesn't show the helicopter rolling, only the ui.
Steps to reproduce: 
1. Go into the editor
2. Spawn yourself as a gunner in the Comanche
3. Take controls from gunner seat
4. Attempt to roll your helicopter

**Comment by esteldunedain** [comment]
True; this seems to be caused by an unforseen interaction between the turret stabilization code and the engine. The chopper actually develops lateral velocity when commanded to roll, but the 3d model doesn't actually rotates.

**Comment by PabstMirror** [comment]
It's really bizarre, from 3rd person it rotates, but 1st person is perfectly flat:

https://www.youtube.com/watch?v=b8Ja0Gybb4c

**Comment by jaynus** [comment]
I know exactly what it is, extra Parma was set in the external turret viewport that should not have been set.

Will change and fix shortly
