### ISSUE TITLE
My inventory gets deleted in the use of a bandage

### ISSUE THREAD

**Issue by Ursus67** [acemod/ACE3#4122]
**Arma 3 Version:** `1.62`
**CBA Version:** `v3.0.0.160713`
**ACE3 Version:** `3.6.2`

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- With advanced Ace, when I take my own tension or when I use a bandage on another person, my inventory gets deleted.

**Steps to reproduce:**
- Take my tension.
- Apply a bandage to an other one people.

**Where did the issue occur?**
- Dedicated (Multiplayer)

**Placed Modules:**
- ACE_moduleMedicalSettings; ACE_moduleMedicalMenuSettings; ACE_moduleAdvancedMedicalSettings.

**Comment by jonpas** [comment]
> ACE3 Version: `3.2.2`

Is that really what you are running? Latest version is 3.6.2. If that was a typo and you are indeed running latest then we will need full RPT file.

**Comment by Ursus67** [comment]
Sorry , he makes itself late home. I made it for a friend, I am going to tempt RPT to recoup the file into to the day in tomorrow.

**Comment by Ursus67** [comment]
hello , here is the request file: http://pastebin.com/Lw8Hr4Fy

**Comment by jonpas** [comment]
You are running a bunch of other mods, not only the ones you listed above. Please confirm bug with only CBA and ACE3 as written in contributing guide.

**Comment by UpperM** [comment]
Hi, 

We gonna to test whitout the rest of mod on clean server to be sure ;)

**Comment by vabene1111** [comment]
I had a similar Problem with an anti weapon script. Because ACE creates the "FakePrimaryWeapon" whenever you bandage someone (at least thats what i think it does) a safezone/anti weapon script will try to delete the Weapon and weird things will happen.

You might have a completely different Problem but it might help ...

**Comment by UpperM** [comment]
Thank it's fix. 

For peoples usiing Altis Life 4.4 just disable the restrict_medic_weapons ;) 

Thank all
