### ISSUE TITLE
Group Bar disabled by default

### ISSUE THREAD

**Issue by Wyqer** [acemod/ACE3#4123]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.6.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The Group Bar is default switched to off after the latest update. No real issue, you can manually enable it again in the ACE Setting -> User Interface, but maybe it confuses some people in the first place.

**Steps to reproduce:**
- Install ACE3 3.6.2
- Place a squad with player as squad leader
- Preview the mission and the group bar is not enabled
- Go to ACE Settings -> User Interface and enable the bar.
- "Issue" solved, but may I ask if this is an intented behaviour?

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- NTR

**Comment by jonpas** [comment]
That is by design, the reason is that ACE3 is still highly focused on coop and realism and that bar is just an imposter.
