### ISSUE TITLE
Weight values incorrect on detectors. 

### ISSUE THREAD

**Issue by Omnirock** [acemod/ACE3#4124]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.62` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Incorrect weight values displayed for VMM3 and VMH3. The VMM3 spec sheet lists it as 1.7 kg, and the VMH3 listed at 2.5 kg. The current values in arsenal show the VMM3 as weighing more. 

<ul>
<li>VMH3
http://www.vallon.de/products.lasso?a=mine-detection&b=2</li>
<li>VMM3
http://www.vallon.de/products.lasso?a=mine-detection&b=3</li>
</ul>

**Steps to reproduce:**
- Select the items within virtual arsenal or add them to your inventory to notice the weight changes. 

**Where did the issue occur?**
Virtual Arsenal/Single Player/Multi Player

**Placed Modules:**
- None

**Comment by VKing6** [comment]
From the product sheets:
VMM3: Complete detector set during operation: 3.5 kg
VMH3: Complete detector set during operation: 2.5 kg

**Comment by PabstMirror** [comment]
Ref http://www.vallon.de/pdf/VMM3_leaflet_01_2013.pdf?rnd=465C81D111a7c31BBBvvFE1D66F2

- Weight to be carried by hand: 1.7 kg
- Complete detector set during
operation (with batteries): 3.5 kg

Explains the difference between the 2 different listed weights
