### ISSUE TITLE
Javlin with RHS stopped working

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#4126]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.6.2` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHS Escalation`
**Description:**
- Rocket shooted with ACE compatibility mode from javelin never reach its target.
**Steps to reproduce:**
- Use RHS javelin together with ACE compat. files.

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- NON
[arma3_2016-07-16_17-30-44.zip](https://github.com/acemod/ACE3/files/367358/arma3_2016-07-16_17-30-44.zip)

**Comment by esteldunedain** [comment]
Might this be caused by load order, now that we changed pboProject's "inteligent" behaviour?

**Comment by vlad8011** [comment]
yyy, i loaded Ace as last on the list.

**Comment by Glowbal** [comment]
Doubtful @estel. We added the javelin component as a requirement.

**Comment by commy2** [comment]
>yyy, i loaded Ace as last on the list.

The Arma 3 launcher does not give full control over deciding the loading order. If this is really the case then only we can fix it.

Can someone else with RHS confirm this?

**Comment by vlad8011** [comment]
I remember someone was writing about it on RHS thread or on yours (BIF).

**Comment by commy2** [comment]
hearsay

**Comment by rebelvg** [comment]
This looks like the same issue.
https://github.com/acemod/ACE3/issues/3937
Only CBA and ACE.

**Comment by esteldunedain** [comment]
> This looks like the same issue.

I don't think so.
