### ISSUE TITLE
Ace compatibility files creates depedency in mission

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#4127]
**Arma 3 Version:** `1.6.2` (stable / rc / dev)
**CBA Version:** `3.0.0` (stable / dev + commit hash)
**ACE3 Version:** `3.6.2` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When saving any mission using compatibility files (for RHS) you cannot play mission without them. Even if you dont need those files, they are added as needed addons.

**Steps to reproduce:**
- add comp. files for RHS to ace/addons, save some scenario in editor, exit game, disable those comp. files, and try to launch this mission. 
**Where did the issue occur?**
- SP

**Comment by PabstMirror** [comment]
Tried adding 
```        
addonRootClass = "rhsusf_c_weapons";
```
to CfgPatches, but it didn't seem to work.

**Comment by commy2** [comment]
Use:
`addonRootClass = "A3_Characters_F";`

**Comment by PabstMirror** [comment]
AddonsMetaData adds `A3_Characters_F` and from 3den it doesn't show ace in the 3dne -> scenario -> show required addons.


But the sqm still has
```
addons[]=
{
	"rhsusf_c_troops",
	"rhsusf_c_m1a2",
	"ace_compat_rhs_usf3",
	"rhs_c_troops",
	"rhs_c_t72",
	"ace_compat_rhs_afrf3"
};
```
and it blocks loading a saved mission.

**Comment by commy2** [comment]
Then there is zilch we can do.

**Comment by vlad8011** [comment]
But as far as i remember it wasnt hapening before. Maybe its connected to some of changes you have recently made....

**Comment by jonpas** [comment]
No, it is connected to how Eden does dependencies.

**Comment by commy2** [comment]
I'm pretty sure `addons[]` was always recorded like this.

The simplest solution would be to just open the unbinarized mission and to manually delete the entries.
Also, why are you starting ACE with the RHS comp PBOs without RHS in the first place? There is a on screen warning for this for a reason.

**Comment by vlad8011** [comment]
I launch game with RHS, and few features from ACE (this which not require compatibility files)
![bez tytulu](https://cloud.githubusercontent.com/assets/14875602/16900191/1b8fa350-4c1e-11e6-9023-affe02d9fe0a.png)

**Comment by vlad8011** [comment]
And yes i opened game with thos comp. file loaded, changed all missions so they are unbinarised (God, why they apply this option in default!?) then edited all 59 mission files........ But will not do this in future.

**Comment by commy2** [comment]
>I launch game with RHS

There is your problem. If you make a mission while ModX is loaded, eventually it will be added the required addons. This is how Arma does it. This system has nothing with ACE and there is no API either, so we could band aid it.
You should put this onto the BI feedback tracker instead.

**Comment by SilentSpike** [comment]
It's a pity the editor doesn't just use the addon that loads first with any given classname, but I'm sure that would create other issues in some cases too.

**Comment by bux578** [comment]
close?
