### ISSUE TITLE
GL fired into water still spawns frags

### ISSUE THREAD

**Issue by BlackHawkPL** [acemod/ACE3#4134]
**Arma 3 Version:** `1.62` stable
**CBA Version:** `3.0.0` stable
**ACE3 Version:** `3.6.2` stable

**Mods:**
- `@CBA_A3`
- `@ace`
- `@ACRE`
- `rhs`
- `cup islands`
- `uo mods`

**Description:**
Vanilla GL fired into water creates frags, but doesn't explode.

**Steps to reproduce:**
"1Rnd_HE_Grenade_shell" + "arifle_SPAR_01_GL_khk_F" + ocean

**Where did the issue occur?**
Editor

**Placed Modules:**
none

**RPT log file:**
http://pastebin.com/wJ1xJjVf

**Comment by esteldunedain** [comment]
I thought that we'd fixed that already, but the code isn't fixed.
