### ISSUE TITLE
Weights of weapons are grossly incorrect 

### ISSUE THREAD

**Issue by thecuban** [acemod/ACE3#4135]
**Arma 3 Version: 1.62**
**CBA Version: 3.0.0.160713**
**ACE3 Version: 3.6.2**

**Mods:**

@CBA_A3
@ace

**Description:**

The weights of some weapons such as the M200 or the LWMMG vastly exceed the weights of their real life counterparts. Listed below are the weights of some of the common weapons I use in game compared to reality. This list does not reflect all the the weapons in game as I do not have the time to test and research each weapon individually. 

GW: Game Weight (lbs)
RW: Real Weight (lbs)

Note both weights (GW, RW) provided are for weapons which are NOT loaded or equipped with accessories.

M200 Intervention
-GW: 42
-RW: 31

GM6:
-GW: 48
-RW: 25.35

LWMMG:
-GW: 34
-RW: 24

Stoner 99 (aka LSAT LMG):
-GW: 22
-RW: 9.8

M14:
-GW: 14
-RW: 9.2

MK14:
-GW: 18
-RW: 11.24

As you can see the weights of these weapons are all incorrect and in some cases double what they should be. I don't know if the ace team has control over the weights of the vanilla weapons but if so the correction of this issue would go a long way to allowing the proper utilization of heavy weapons such as the GM6 or LWMMG.

**Steps to reproduce:**

-acquire weapon
-remove all accessories from weapon
-remove magazine from weapon
-note weight of character (using ace inventory function)
-drop weapon and note weight of character once again
-the difference in the weights is the weight of the weapon (ensure the no other equipment is dropped such as spare magazines or belts)

**Where did the issue occur?**

-All modes

**Placed Modules:**

None

**Comment by esteldunedain** [comment]
See #3868

**Comment by bux578** [comment]
> as I do not have the time to test and research each weapon individually
