### ISSUE TITLE
setMass 1, still can't lift

### ISSUE THREAD

**Issue by kdjay** [acemod/ACE3#4141]
I am using setMass 1;

still cannot carry box, "Item too heavy"

according to these docs it should work.
http://ace3mod.com/wiki/framework/dragging-framework.html
wtf

**Comment by kdjay** [comment]
I am calling setMass before calling ace_dragging_fnc_setDraggable;

**Comment by kdjay** [comment]
debug
http://pastebin.com/BQNs92x0

**Comment by PabstMirror** [comment]
You can check mass of box with:
`[cursorTarget] call ace_dragging_fnc_getweight;`

and then change the limits:
```
    ACE_maxWeightCarry = 600;
    ACE_maxWeightDrag = 800;
```

The weight of things inside of a box is the biggest source of weight.

**Comment by esteldunedain** [comment]
So in short using ` setMass` doesn't affect the weight of the **content** of the box. If the box is too full then you won't be able to carry it despite the command.
