### ISSUE TITLE
question : set captive without animation

### ISSUE THREAD

**Issue by SharonX4** [acemod/ACE3#4148]
i want unit set handcuffed but with my own animation and still interacted with ACE it is possible

**Comment by RSpeekenbrink** [comment]
put this in the init: 
`if (_value) then {[objNull,[_this],true] call ace_captives_fnc_moduleHandcuffed}`
Then add your animation by something like playmove or playaction. That should work I guess (not tested)

**Comment by esteldunedain** [comment]
> That should work I guess (not tested)

I don't think so. ACE automatically resets animations when a unit is handcuffed, to avoid units being able to escape the handcuffed state.

Unfortunately I don't think there's a way to do what you want without modifying ace's code. If you are willing to do that, I think you need to change:

lines 21 and 23 of `fnc_handleAnimChangedHandcuffed.sqf`

and 

line 63 of `fnc_setHandcuffed.sqf`
