### ISSUE TITLE
Request: Bring straight Line Drawing back

### ISSUE THREAD

**Issue by RSpeekenbrink** [acemod/ACE3#4153]
**Arma 3 Version:** 1.62 Stable 
**CBA Version:** `3.0.0` stable 
**ACE3 Version:** `3.6.2` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Alt click straight lines are gone or at least not working, would love to see them back in the game since they are such a handy tool, the tool in arma atm is not that good to draw straight lines with and you will need it for land navigation :)

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by PabstMirror** [comment]
I tried to work on something that would use the map tools to draw straight lines.
But there is enough delay the effect wasn't great (jagged lines).
https://www.youtube.com/watch?v=NfLgXsJW_3M
code: fe2ddbad3e6fcf71bbd3d63831ba003bb38643fd

If we had access to commands for the new markers, like `setMarkerPolylineArray` we could do this right.

**Comment by esteldunedain** [comment]
@PabstMirror, isn't it possible to just create a rotated rectangle like we used to?

**Comment by PabstMirror** [comment]
So if you draw a polyline along the edge of maptools
then
after drawing is finished, convert it to a shape marker

I think it would still be a native marker and synced by the engine, I will do some tests

**Comment by jonpas** [comment]
@PabstMirror that's what I recommended some time ago and I still think it would work perfectly, simply use `createMarkeLocal` if you don't want it synced.

**Comment by esteldunedain** [comment]
> So if you draw a polyline along the edge of maptools then after drawing is finished, convert it to a shape marker

Well, yes. I'd have the side effect of always requiring a roamer in order to draw straight lines, but that is kinda realistic.

Maybe we could add some keybind to auto align the roamer to two point to make it less of a hassle.

**Comment by PabstMirror** [comment]
It does seem to be working
![image](https://cloud.githubusercontent.com/assets/9376747/17086138/1bb79f80-51b0-11e6-89f3-40ae92538005.png)

and the marker is native, it will sync in mp
minor downside is it is harder to delete (needs to be center of line)
and the thickness doesn't match the other polylines

**Comment by commy2** [comment]
nice

**Comment by PabstMirror** [comment]
@cuel
Feature request that would make sense to add into this is to only allow people with map tools to draw on map.

Which would probably be just deleting the line after it's drawn.

**Comment by esteldunedain** [comment]
> Feature request that would make sense to add into this is to only allow people with map tools to draw on map.

Sure, optionally. 

I think we could tackle that later though, probably as part of the unique map framework.

**Comment by esteldunedain** [comment]
@PabstMirror, any chance of PRing this for 3.7.0?

**Comment by jonpas** [comment]
@esteldunedain definitely not 3.7.0 anymore.
