### ISSUE TITLE
ACE not working on my server. 

### ISSUE THREAD

**Issue by soldier809** [acemod/ACE3#4154]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
-

I am trying to set a server up using ACE medical and damage models. So I am using the new server hosting feature in ARMA. I have built my mission and placed the ACE module's (basic medical settings) (revive settings) (re spawn settings) and (medical settings). When i go to launch the server and have a couple friends ACE doesn't even seem to be active. All the bandages and medical supplies are in the boxes. We now can't revive any one because the standard revive system gets in the way. I have been trying to get this working for like two days and I am just burnt out.
Forgot to mention when I get hit it either instant kills me and sends me back to re spawn. Which I have to settings set not to perma death. OR I get hit and no one can revive me due to the fact that the standard revive system is interfering. Do I need to link the module's to something? I know its probably one easy step I am missing. Anyone's help would be great. 

**Steps to reproduce:**
n/a
**Where did the issue occur?**
Self-Hosted Multiplayer / Editor (Multiplayer)

**Placed Modules:**
(basic medical settings) (revive settings) (re spawn settings) and (medical settings)

**RPT log file:**
don't know how sorry.

**Comment by RSpeekenbrink** [comment]
Make sure the standard revive system is disabled on your mission template and that the mod is also running on the server

**Comment by esteldunedain** [comment]
Please provide the RPT logs of the server. My guess is that you are not properly running the ACE mod on the server.

**Comment by JudahHarvey** [comment]
Which mission are you trying to play?

**Comment by Glowbal** [comment]
No response for nearly a month. Please resubmit your bug report with all the requested information if you are still experiencing issues.
