### ISSUE TITLE
Better syncing between clinet and server mods.

### ISSUE THREAD

**Issue by isenhand** [acemod/ACE3#4156]
From server browser screen on client

If a mod has a red circle, I would like the option of clicking on the red circle and an automatic download and install function would install the correct mod on the client. The circle would them turn green and and I could start playing on the server. 

One of the major problems I have that consumes a vast amount of time is getting the right right mod with the right version to work between client and server. Making it more automatic would save a lot of time and frustration getting the right mod to play on a given server.

**Comment by jokoho48** [comment]
i think you miss understand this issue tracker. this is for the mod ACE3. i think you should better ask here: https://feedback.bistudio.com/

**Comment by isenhand** [comment]
Ah, yes. It appears I have. Thanks.
