### ISSUE TITLE
ACE_ModuleRespawn not working

### ISSUE THREAD

**Issue by Woods825** [acemod/ACE3#4157]
**Arma 3 Version:** `1.62.137494` (stable / rc / dev)
**CBA Version:** `3.0.0.160713` (stable / dev + commit hash)
**ACE3 Version:** `3.6.2` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- I have a mission with respawn set to BASE, a marker on the map named "respawn_west" and a playable BLUFOR unit (I edited his loadout to remove his vest and weapon). I have placed the ACE_ModuleRespawn down and set "Save Gear?" to "Enabled". I launch the mission in multiplayer, upon respawn the unit does not have the gear he had before his death, instead he has the gear that unit would normally have upon first being spawned in the editor (his vest and weapon are returned).

**Steps to reproduce:**
- Place ACE_ModuleRespawn
- Set "Save Gear?" to 'Enabled"
- Respawn with a custom loadout
- Unit respawns with original gear, not gear before death

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer

**Placed Modules:**
- ACE_ModuleRespawn

**Comment by bux578** [comment]
RPT please. I can't reproduce this. It works perfectly as always.

**Comment by Woods825** [comment]
When testing it on a dedicated server:
Server rpt: [http://pastebin.com/HrjvrBs2](url)
Player rpt: [http://pastebin.com/1NK9Uvw1](url)

When testing with player hosting the mission:
Player as host rpt: [http://pastebin.com/z7rRXY4S](url)

Here's the exact mission file those tests were done with: [https://www.dropbox.com/s/ufcy7d2cphbqyw6/ACE3_Respawn_Test.VR.pbo?dl=0](url)

**Comment by esteldunedain** [comment]
The RPTs don't seem to show anything anomalous and ACE's and CBA's versions are ok. I din't test the mission yet though.

**Comment by bux578** [comment]
So, i was able to reproduce it with your mission. The error though is in your description.ext file.
It only contains a simple `respawn = 3;` and I do believe that is not enough. 

For testing I've replaced your description.ext with one of the more "normal" ones (speak more entries)
```
class Header {
    gameType = Coop;
    minPlayers = 1; 
    maxPlayers = 20;
};

author = "bux578";
OnLoadName = "ACE Test";
OnLoadMission = "Zeus me around";
OnLoadMissionTime = 1;

enableDebugConsole = 2;

respawn = 3;
respawnDelay = 5;
respawnOnStart = 0;

/*disabledAi      = 1;*/
showGPS         = 1;
showNotepad     = 1;
showCompass     = 1;
showWatch       = 1;
debriefing      = 1;
```

And with this respawning works in your mission too.

@esteldunedain could it be the missing "delay" on respawning? Same frame operations?

**Comment by esteldunedain** [comment]
> @esteldunedain could it be the missing "delay" on respawning? Same frame operations?

That's a nice hypothesis. Maybe without delay the Respawn EH is being called before the Killed EH. That should be fairly easy to debug with a couple of traces or sideChats. If that's the case, delaying the content of handleRespawn a frame of a few ms could fix it.

**Comment by Woods825** [comment]
Well sure enough its the respawndelay. Must've been something that cropped up with Arma 1.60 (Respawn Overhaul), prior to that using "respawndelay = 0;" worked with the ACE save gear. Even setting the delay to 1 works properly now.

**Comment by commy2** [comment]
`respawnDelay = 0;` is different from omiting the entry entirely.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
