### ISSUE TITLE
Copy Map not working

### ISSUE THREAD

**Issue by RSpeekenbrink** [acemod/ACE3#4158]
**Arma 3 Version:** `1.62` stable
**CBA Version:** `3.0.0.160713` stable
**ACE3 Version:** `3.6.2` stable

**Mods:**
- `@CBA_A3`
- `@ace`
- `@CupTerrains`
- `@TFAR`
- `@RHS`

**Description:**
- Before you could copy someones map by going into the interaction menu, I can't get it to work now :$

**Steps to reproduce:**
- Make a template
- Start the template
- Make your buddy draw markers on his vehicle chat on the map
- cant copy map

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer  / Editor (Multiplayer) 

**Placed Modules:**
http://pastebin.com/hjmZamxe

**Comment by Pergor** [comment]
Wait, you're supposed to still be able to copy the map? That seems a little redundant if map drawing is possible in side, group or global channel, isn't it?

**Comment by jonpas** [comment]
Yes, that was removed when we removed ACE3's line drawing.

**Comment by RSpeekenbrink** [comment]
Well would love to see that back, since its kinda handy, same for the ACE 3 line drawing, because arma does not allow to draw straight lines, even though if you use a "ruler" like the map tools

**Comment by esteldunedain** [comment]
Map copying will be eventually, bigger and better, as part of #3601. That PRs makes markers unique to each map, so if you e.g. take a map from a dead unit you'll be able to see what he drew.
