### ISSUE TITLE
Bindings not working properly.

### ISSUE THREAD

**Issue by Wild-Dog** [acemod/ACE3#4160]
**Arma 3 Version:** `1.62` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
   @173rd_V17
   @ACE3
   @task_force_radio
   @CBA_A3
   @cup_terrains_core and @cup_terrains_maps
   @RHSUSAF
   @RHSAFRF
   @RHSGREF
   @leights_opfor
   @Simple Single Player Cheat Menu

**Description:**
I have R bound to both Clear Jam and Reload. 

I like that if there's a jam, it clears the jam without reloading. 

I also like how if the gun isn't jammed, I can press R to reload.

There's a glitch, where if I don't delete the Clear Jam binding and rebind it to R, pressing R when the gun is jammed clears the Jam and reloads the gun at the same time.

I don't like that.

**Steps to reproduce:**
Bind both Clear Jam and Reload to the R button, then start the Virtual Arsenal. 

Fire and Jam a Rifle. Clear the Jam. 

Reload the Virtual Arsenal and Fire the Rifle again until it Jams.

You will notice that the magazine is reloaded while the Jam is being cleared.

You will need to delete the Clear Jam binding and then rebind it to R to temporarily fix this.

Let's do the Time Warp again!

**Where did the issue occur?**
- Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- http://pastebin.com/Sh7PJqx2

- ~~~~~~~~~ACE Debug~~~~~~~~~
time = 76.354

------Performance------
diag_fps = 47.7612
count cba_common_waitAndExecArray = 7
count cba_common_waitUntilAndExecArray = 0
count cba_common_perFrameHandlerArray = 17 (max 17)
count diag_activeSQFScripts = 16
count diag_activeSQSScripts = 0
count diag_activeMissionFSMs = 1

------Player------
typeOf = C_man_1
animationState = amovpercmstpsraswpstdnon

------ACE Settings------
ace_common_forceAllSettings - false
ace_common_checkPBOsAction - 0
ace_common_checkPBOsCheckAll - false
ace_common_checkPBOsWhitelist - []
ace_common_settingFeedbackIcons - 1
ace_common_settingProgressBarLocation - 0
ace_common_displayTextColor - [0,0,0,0.1]
ace_common_displayTextFontColor - [1,1,1,1]
ace_finger_enabled - false
ace_finger_maxRange - 4
ace_finger_indicatorForSelf - true
ace_finger_indicatorColor - [0.83,0.68,0.21,0.75]
ace_frag_enabled - true
ace_frag_spallEnabled - false
ace_frag_reflectionsEnabled - false
ace_frag_maxTrack - 500
ace_frag_maxTrackPerFrame - 50
ace_frag_enableDebugTrace - false
ace_gforces_enabledFor - 1
ace_goggles_effects - 2
ace_goggles_showInThirdPerson - false
ace_hitreactions_minDamageToTrigger - 0.1
ace_interact_menu_alwaysUseCursorSelfInteraction - false
ace_interact_menu_cursorKeepCentered - false
ace_interact_menu_alwaysUseCursorInteraction - false
ace_interact_menu_useListMenu - false
ace_interact_menu_colorTextMax - [1,1,1,1]
ace_interact_menu_colorTextMin - [1,1,1,0.25]
ace_interact_menu_colorShadowMax - [0,0,0,1]
ace_interact_menu_colorShadowMin - [0,0,0,0.25]
ace_interact_menu_textSize - 2
ace_interact_menu_shadowSetting - 2
ace_interact_menu_actionOnKeyRelease - true
ace_interact_menu_menuBackground - 0
ace_interact_menu_addBuildingActions - false
ace_interact_menu_menuAnimationSpeed - 0
ace_interaction_enableTeamManagement - true
ace_interaction_enableMagazinePassing - true
ace_inventory_inventoryDisplaySize - 0
ace_laserpointer_enabled - true
ace_magazinerepack_timePerAmmo - 1.5
ace_magazinerepack_timePerMagazine - 2
ace_magazinerepack_timePerBeltLink - 8
ace_map_BFT_Interval - 1
ace_map_BFT_Enabled - false
ace_map_BFT_HideAiGroups - false
ace_map_BFT_ShowPlayerNames - false
ace_map_mapIllumination - true
ace_map_mapGlow - true
ace_map_mapShake - true
ace_map_mapLimitZoom - false
ace_map_mapShowCursorCoordinates - false
ace_map_defaultChannel - -1
ace_map_gestures_enabled - true
ace_map_gestures_maxRange - 7
ace_map_gestures_interval - 0.03
ace_map_gestures_nameTextColor - [0.2,0.2,0.2,0.3]
ace_map_gestures_defaultLeadColor - [1,0.88,0,0.95]
ace_map_gestures_defaultColor - [1,0.88,0,0.7]
ace_map_gestures_groupColorConfigurations - []
ace_map_gestures_groupColorConfigurationMapping - [[],[]]
ace_maptools_rotateModifierKey - 1
ace_medical_level - 1
ace_medical_medicSetting - 1
ace_medical_increaseTrainingInLocations - false
ace_medical_enableFor - 0
ace_medical_enableOverdosing - true
ace_medical_bleedingCoefficient - 1
ace_medical_painCoefficient - 1
ace_medical_enableAirway - false
ace_medical_enableFractures - false
ace_medical_enableAdvancedWounds - false
ace_medical_enableVehicleCrashes - true
ace_medical_enableScreams - true
ace_medical_playerDamageThreshold - 1
ace_medical_AIDamageThreshold - 1
ace_medical_enableUnconsciousnessAI - 1
ace_medical_remoteControlledAI - true
ace_medical_preventInstaDeath - false
ace_medical_enableRevive - 0
ace_medical_maxReviveTime - 120
ace_medical_amountOfReviveLives - -1
ace_medical_allowDeadBodyMovement - false
ace_medical_allowLitterCreation - true
ace_medical_litterSimulationDetail - 3
ace_medical_litterCleanUpDelay - 0
ace_medical_medicSetting_basicEpi - 1
ace_medical_medicSetting_PAK - 1
ace_medical_medicSetting_SurgicalKit - 1
ace_medical_consumeItem_PAK - 0
ace_medical_consumeItem_SurgicalKit - 0
ace_medical_useLocation_basicEpi - 0
ace_medical_useLocation_PAK - 3
ace_medical_useLocation_SurgicalKit - 2
ace_medical_useCondition_PAK - 0
ace_medical_useCondition_SurgicalKit - 0
ace_medical_keepLocalSettingsSynced - true
ace_medical_healHitPointAfterAdvBandage - false
ace_medical_painIsOnlySuppressed - true
ace_medical_painEffectType - 0
ace_medical_allowUnconsciousAnimationOnTreatment - false
ace_medical_moveUnitsFromGroupOnUnconscious - false
ace_medical_menuTypeStyle - 0
ace_medical_delayUnconCaptive - 3
ace_medical_menu_allow - 1
ace_medical_menu_useMenu - 0
ace_medical_menu_openAfterTreatment - true
ace_medical_menu_maxRange - 3
ace_microdagr_mapDataAvailable - 2
ace_missileguidance_enabled - 2
ace_mk6mortar_airResistanceEnabled - false
ace_mk6mortar_allowComputerRangefinder - true
ace_mk6mortar_allowCompass - true
ace_mk6mortar_useAmmoHandling - false
ace_movement_useImperial - false
ace_nametags_defaultNametagColor - [0.77,0.51,0.08,1]
ace_nametags_showPlayerNames - 1
ace_nametags_showPlayerRanks - true
ace_nametags_showVehicleCrewInfo - true
ace_nametags_showNamesForAI - false
ace_nametags_showCursorTagForVehicles - false
ace_nametags_showSoundWaves - 1
ace_nametags_playerNamesViewDistance - 5
ace_nametags_playerNamesMaxAlpha - 0.8
ace_nametags_tagSize - 2
ace_nightvision_disableNVGsWithSights - false
ace_optionsmenu_optionMenuDisplaySize - 0
ace_optionsmenu_showNewsOnMainMenu - true
ace_overheating_displayTextOnJam - true
ace_overheating_showParticleEffects - true
ace_overheating_showParticleEffectsForEveryone - false
ace_overheating_overheatingDispersion - true
ace_overheating_unJamOnreload - false
ace_overheating_unJamFailChance - 0.1
ace_overheating_enabled - true
ace_rearm_level - 0
ace_refuel_rate - 1
ace_reload_displayText - true
ace_repair_displayTextOnRepair - true
ace_repair_engineerSetting_repair - 1
ace_repair_engineerSetting_wheel - 0
ace_repair_repairDamageThreshold - 0.6
ace_repair_repairDamageThreshold_engineer - 0.4
ace_repair_consumeItem_toolKit - 0
ace_repair_fullRepairLocation - 2
ace_repair_engineerSetting_fullRepair - 2
ace_repair_addSpareParts - true
ace_repair_wheelRepairRequiredItems - 0
ace_repair_autoShutOffEngineWhenStartingRepair - false
ace_respawn_savePreDeathGear - false
ace_respawn_removeDeadBodiesDisconnected - true
ace_respawn_bodyRemoveTimer - 0
ace_sitting_enable - false
ace_spectator_filterUnits - 2
ace_spectator_filterSides - 0
ace_spectator_restrictModes - 0
ace_spectator_restrictVisions - 0
ace_switchunits_enableSwitchUnits - false
ace_switchunits_switchToWest - false
ace_switchunits_switchToEast - false
ace_switchunits_switchToIndependent - false
ace_switchunits_switchToCivilian - false
ace_switchunits_enableSafeZone - true
ace_switchunits_safeZoneRadius - 100
ace_ui_allowSelectiveUI - true
ace_ui_soldierVehicleWeaponInfo - true
ace_ui_vehicleRadar - true
ace_ui_vehicleCompass - true
ace_ui_commandMenu - true
ace_ui_groupBar - false
ace_ui_weaponName - true
ace_ui_weaponNameBackground - true
ace_ui_firingMode - true
ace_ui_ammoType - true
ace_ui_ammoCount - false
ace_ui_magCount - true
ace_ui_throwableName - true
ace_ui_throwableCount - true
ace_ui_zeroing - true
ace_ui_weaponLowerInfoBackground - true
ace_ui_stance - true
ace_ui_staminaBar - true
ace_ui_gunnerWeaponName - true
ace_ui_gunnerWeaponNameBackground - true
ace_ui_gunnerFiringMode - true
ace_ui_gunnerAmmoType - true
ace_ui_gunnerAmmoCount - true
ace_ui_gunnerMagCount - true
ace_ui_gunnerLaunchableName - true
ace_ui_gunnerLaunchableCount - true
ace_ui_gunnerZeroing - true
ace_ui_gunnerWeaponLowerInfoBackground - true
ace_ui_vehicleName - true
ace_ui_vehicleNameBackground - true
ace_ui_vehicleFuelBar - true
ace_ui_vehicleSpeed - true
ace_ui_vehicleAltitude - true
ace_ui_vehicleDamage - true
ace_ui_vehicleInfoBackground - true
ace_vehiclelock_defaultLockpickStrength - 10
ace_vehiclelock_lockVehicleInventory - false
ace_vehiclelock_vehicleStartingLockState - -1
ace_viewdistance_enabled - true
ace_viewdistance_viewDistanceOnFoot - 0
ace_viewdistance_viewDistanceLandVehicle - 0
ace_viewdistance_viewDistanceAirVehicle - 0
ace_viewdistance_limitViewDistance - 10000
ace_viewdistance_objectViewDistanceCoeff - 0
ace_weaponselect_displayText - true
ace_weather_enableServerController - true
ace_weather_useACEWeather - true
ace_weather_syncRain - true
ace_weather_syncWind - true
ace_weather_syncMisc - true
ace_weather_serverUpdateInterval - 60
ace_winddeflection_enabled - true
ace_winddeflection_vehicleEnabled - true
ace_winddeflection_simulationInterval - 0.05
ace_winddeflection_simulationRadius - 3000
ace_zeus_zeusAscension - false
ace_zeus_zeusBird - false
ace_zeus_remoteWind - false
ace_zeus_radioOrdnance - false
ace_zeus_revealMines - 0
ace_zeus_autoAddObjects - false
ace_captives_allowHandcuffOwnSide - true
ace_captives_requireSurrender - 1
ace_captives_allowSurrender - true
ace_cargo_enable - true
ace_explosives_requireSpecialist - false
ace_explosives_punishNonSpecialists - true
ace_explosives_explodeOnDefuse - true
ace_gestures_showOnInteractionMenu - 2
ace_hearing_enableCombatDeafness - true
ace_hearing_earplugsVolume - 0.5
ace_hearing_unconsciousnessVolume - 0.4
ace_hearing_disableEarRinging - false
ace_hearing_enabledForZeusUnits - true
ace_hearing_autoAddEarplugsToUnits - true
ace_advanced_ballistics_enabled - false
ace_advanced_ballistics_simulateForSnipers - true
ace_advanced_ballistics_simulateForGroupMembers - false
ace_advanced_ballistics_simulateForEveryone - false
ace_advanced_ballistics_disabledInFullAutoMode - false
ace_advanced_ballistics_ammoTemperatureEnabled - true
ace_advanced_ballistics_barrelLengthInfluenceEnabled - true
ace_advanced_ballistics_bulletTraceEnabled - true
ace_advanced_ballistics_simulationInterval - 0
ace_advanced_ballistics_simulationRadius - 3000

------Array Info (count >= 50)------
ace_common_settings - ARRAY SIZE: 249
ace_common_hexarray - ARRAY SIZE: 256
cba_wtab - ARRAY SIZE: 128
cba_ktab - ARRAY SIZE: 128
cba_common_pfhhandles - ARRAY SIZE: 110
cba_xeh_entities - ARRAY SIZE: 61
cba_keybinding_dikdectostringtable - ARRAY SIZE: 161
cba_keybinding_activebinds - ARRAY SIZE: 122
cba_events_keyupstates - ARRAY SIZE: 250
ace_optionsmenu_clientsideoptions - ARRAY SIZE: 78
cba_common_addons - ARRAY SIZE: 2706
cba_events_playerehinfo - ARRAY SIZE: 55
cba_events_keydownstates - ARRAY SIZE: 250
cba_xeh_alleventhandlers - ARRAY SIZE: 320
cba_ytab - ARRAY SIZE: 128

**Comment by esteldunedain** [comment]
Sorry, that's the way it's coded. You are assigning both actions to the same keybind, so you shouldn't be surprised that both actions happen simultaneously when both are applicable.

Also we can't reliably prevent the weapon from reloading when pressing R, so there's nothing we can do to fix this even if we agreed it makes sense.

**Comment by Wild-Dog** [comment]
Hmm. If I reset the binding it stays the way I like it.

You're telling me that condition can't be maintained through coding?
