### ISSUE TITLE
RHS repair script are available for BTR

### ISSUE THREAD

**Issue by lolkij** [acemod/ACE3#4164]
**Arma 3 Version:** 1.62 (stable)
**CBA Version:** 3.0.0 (stable)
**ACE3 Version:** 3.6.2 (stable)

**Mods:**
- `@CBA_A3`
- `@ace`+rhs compat files
- `@rhs v0.4.1.1

**Description:**
- As I know, ACE disable the RHS repair script (for wheels) for all usual vehicles. But if you shoot off the wheel of BTR - then you will be able to fix it via RHS "repair system". http://i.imgur.com/q5QBrE9.jpg
This happens with the BTR with spare wheels on the roof (default attribute option).

**Steps to reproduce:**
- Put in the editor any Russian BTR with a spare wheel on the roof. 
- Shoot off his wheel. 
- Replace the wheel using the RHS repair system. 

**Where did the issue occur?**
Everywhere

**Placed Modules:**
None

**RPT log file:**
Not relevant

**Comment by esteldunedain** [comment]
> As I know, ACE disable the RHS repair script (for wheels) for all usual vehicles

Mm, is that right? I couldn't find that anywhere in the code. @PabstMirror ,@jonpas, do you know something about this?

**Comment by commy2** [comment]
Seems like a feature of RHS.

**Comment by esteldunedain** [comment]
So @commy2, you think RHS is disabling their repair script if ACE is present?

**Comment by commy2** [comment]
No. They don't care about compatibility.

**Comment by jonpas** [comment]
No, we don't do anything like that.

**Comment by esteldunedain** [comment]
So in short @lolkij, we don't disable RHS repair on purpose and we have no idea why the repair action is shown only for the BTR. If you ask RHS itself please report back here..

**Comment by lolkij** [comment]
ok

**Comment by kwinteng** [comment]
As far as i know it's a feature of that BTR because it has wheels on the back.
If you repair (change) a wheel one wheel gets removed from the back of the BTR

**Comment by lolkij** [comment]
Yes, it is. So maybe add a feature in the "rhs compat" pbo that would remove these wheels, or did not allow them to use for repair?

**Comment by commy2** [comment]
Go ahead and make a pull request if you want to change that. We don't actively maintain the RHS comp pbos as we encourage 3rd party mod authors to implement compatibility themselves. We only host these out of courtesy as the RHS devs are not interested in compatibility of their stuff with anything.
