### ISSUE TITLE
All static weapons cannot be loaded in the vehicle cargo

### ISSUE THREAD

**Issue by lolkij** [acemod/ACE3#4165]
**Arma 3 Version**: 1.62 (stable)
**CBA Version**: 3.0.0 (stable)
**ACE3 Version**: 3.6.2 (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- All static weapons cannot be loaded in the vehicle cargo since v3.6.0. http://i.imgur.com/C1EzaJG.jpg
Option "ace_cargo_canLoad = 1; " for cfg's also does not work.
Statics can be load in vehicle only if synchronize it with the "Make Object Loadable" module. But this is not a solution in many situations.

**Steps to reproduce:**
- Place any static weapon and vehicle in the editor.
- Try to load this weapon in the vehicle cargo.
- Nothing happens

**Where did the issue occur?**
Everywhere

**Placed Modules:**
None

**RPT log file:**
Not relevant

**Comment by esteldunedain** [comment]
I think this is due to the Mortar not inheriting from LandVehicle, and hence skipping the init event handler that inits loadable classes. 

Probably Mortar_01_base_F should have an event handler too.

**Comment by commy2** [comment]
`All static weapons cannot be loaded `

Do you mean `Some static weapons cannot be loaded` ?

**Comment by lolkij** [comment]
I checked all the vanilla and RHS statics, so yes: all static weapons cannot be loaded =)

**Comment by esteldunedain** [comment]
Ok, so none of the static weapons are loadable by default?

@jonpas, did you properly test this: d931eb4e15ff70e0d94f01dd381fe0ad206010e2 ??

**Comment by jonpas** [comment]
It worked at the time, I checked StaticWeapon inheritance when I did that PR, maybe BI changed it?
