### ISSUE TITLE
Mismatch error rhs_compt

### ISSUE THREAD

**Issue by Tyeee3** [acemod/ACE3#4167]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.0.0 (stable / dev + commit hash)
**ACE3 Version:** `3.6.2` (stable / dev + commit hash)

**Mods:**
@cba_a3;@alive;@ace3;@acex_a3;@rhs_usf3;@rhs_gref;@rhs_afrf3;@ADF;@cup_terrains_core;@cup_terrains_maps;@task_force_radio;@cup_vehicles;@cup_weapons;@cup_units;@CUP_ACE_compatibility;@CUP_Vehicles_ACE_compat

**Description:**
Load into mission and get an error for, mismatch for client/server client has extra addon @rhs_compt_afrf3 /usf3
**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated server

**Placed Modules:**
most of the ace/alive modules 
**RPT log file:**
http://pastebin.com/BPVDfs2j
**Debug log file:**
http://pastebin.com/guiFRXJm

**Comment by commy2** [comment]
` 0:21:12 [ACE] (common) ERROR: File ace_rhs_c_weapons_comp.pbo is outdated.`

Delete this file:
`C:\TCAFiles\Users\WayneH\7724\@rhs_afrf3\addons\ace_compat_rhs_afrf3.pbo - bab33bfb`

**Comment by Tyeee3** [comment]
Do I delete client side aswell?

**Comment by Tyeee3** [comment]
FIXED DO NOT MAKE MISSIONS WHILE ace_compat_rhs_afrf3.pbo AND ace_compat_rhs_USF3.pbo 
ARE IN FOLDERS

**Comment by Tyeee3** [comment]
Okay so the mission will run for me but any one else it will kick, if they are or not using the ace_compt_afrf3 ace_compt_usf3
