### ISSUE TITLE
After latest updates, the Helmet (tankmen, pilot) killing almost all game sounds.

### ISSUE THREAD

**Issue by ghost** [acemod/ACE3#4173]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0.160713` (stable)
**ACE3 Version:** `3.6.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
I know that helmets(pilot, tankman) reduce the level of game sound , but the latest updates of ACE3, killed almost all sounds, that needs to hear the player.  When a player in the vehicles, he almost hears nothing! Moreover, now radio talks, also turned into a barely discernible sounds. For what reason, helmet now affects to radio communications? As seems to me this is not good. As soon as I remove the helmet, becoming perfectly!

I don't use file - "ace_noradio.PBO",  because I need the sound of the radio into my squad. Also I need the other sounds, when I in the vehicle. 

ACE team, Please tell me, how the player can solve the problem?  It may be possible to delete the particular file in order to normal hear the game? Or may be this issue, can be fixed in comming updates?

PS: It seems to me , that helmets (tankman, pilot) should not significantly reduce the surrounding sound. Not more than 30% in that time, as ACE3 reduces the sound > 60% !
When a player in the helmet, the Sound not should be much quieter, He needs to sound more muffled, but enough loud at the same time. Perhaps this issue, should be set-up with the equalizer. If you just decrease the volume of all sounds, it will not be a good solution.

**Steps to reproduce:**
play as tankmen, join the fight, do radio command to own subordinates. 

**Where did the issue occur?**
Editor (Singleplayer)

**Placed Modules:**
Only Advanced and Basic Medical Modules

**RPT log file:**
not needed

**Comment by esteldunedain** [comment]
Tank helmets should not affect the radio volume. It requires some refactoring of the code, but it's doable.

In the meantime, just disable ACE_Hearing if you are having troubles hearing the radio chatter. Or take off the helmet.

**Comment by mickeymen** [comment]
Thanks for the reply. As I understand it, file "ACE_Hearing" - will also influence on injury of hearing, during the shooting without ear plugs? So it will not work any more

**Comment by esteldunedain** [comment]
Yes, unfortunately disabling the module disables all that.

**Comment by Pergor** [comment]
One of the major problems with that is that ace_hearing_EarplugsVolume can sets the factor how much the volume is supposed to be reduced. Helmets have a fixed value for that, instead of using the value of ace_hearing_EarplugsVolume.
That means if ace_hearing_EarplugsVolume == 1 you wouldn't have any volume reduction for earplugs but you still got full reduction on helmets.
That should be changed.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 130 days without any activity.
