### ISSUE TITLE
No zeroing for statiс weapons

### ISSUE THREAD

**Issue by lolkij** [acemod/ACE3#4176]
**Arma 3 Version:** 1.62 (stable)
**CBA Version:** 3.0.0 (stable)
**ACE3 Version:** 3.6.2 (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@rhs` (optional)

**Description:**
- Since 3.6.0 zeroing for some statiс weapons (HMG and GMG) is gone.

I.e. Mk19 by RHS (look at the weapon info in the top right corner):
- Vanilla http://i.imgur.com/3ScOndy.jpg
- ACE 3.6.2 http://i.imgur.com/wK8a2jt.jpg
- ACE 3.5.1 http://i.imgur.com/7xiYO3G.jpg

It's the same with the vanilla static MG and GMG

**Steps to reproduce:**
- It should be noted that instead of changing zeroing (PgUp/PgDwn) began to work automatic setup of range button (T or Tab).

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- None

**RPT log file:**
- Not relevant

**Comment by bux578** [comment]
How about vanilla weapons?

**Comment by lolkij** [comment]
As I wrote above: It's the same with the vanilla static MG and GMG

**Comment by esteldunedain** [comment]
Most likely a problem with XEH, same as the the cargo issue.

**Comment by PabstMirror** [comment]
FCS set's gunnerZeroing in UI to false
On turrets where FCS is disabled, we probably want to leave it on

**Comment by jonpas** [comment]
Oh that thing, yeah my fault. Basically, instead of disabling it it needs to be a condition, because we want to disable it on some vanilla vehicles because we implement our own FCS UI element for those.
