### ISSUE TITLE
Reload mutex activates even if you have nothing to reload

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#4178]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.6.2` (76b04913cb6d9e676436658244d94335f35125cf)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- I understand that reload mutex just detects a key press and not an actual reload. So if you have no mags for your main weapon and press R mutex will activate. Not a major issue but I guess you can add a check if player has mags for his weapon in the inventory and only then activate switch isReloading to true.

**Steps to reproduce:**
- Press R when you have no mags for your current weapon (reload doesn't happen).
- Try to throw a grenade via advanced throwing module.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- N/A.

**Comment by jonpas** [comment]
Something like that should work. 
`!(((magazines player) arrayIntersect (getArray (configFile >> "CfgWeapons" >> "magazines"))) isEqualTo [])`

**Comment by commy2** [comment]
Sounds like unnecessary overhead to me

**Comment by jonpas** [comment]
The code I posted should be fairly quick, I'd say this is a needed fix.

**Comment by commy2** [comment]
`arrayIntersect` is case sensitive. The BI vanilla configs have magazine capitalization all over the place. Needs `apply {toLower _x}` on both sides

**Comment by jonpas** [comment]
Even that should be fairly fast. It will also be executed only if reload key is pressed and weapon is in hand.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 160 days without any activity.

**Comment by commy2** [comment]
vote for close

**Comment by commy2** [comment]
finally!
