### ISSUE TITLE
No option to limit vehicle ammo supply

### ISSUE THREAD

**Issue by OCDexter** [acemod/ACE3#4179]
**Arma 3 Version:** `1.62.137494` stable
**CBA Version:** `3.0.0.160713` stable
**ACE3 Version:** `3.6.2` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
When adding the re-arm module down to the map it only displays the option for how vehicles are refilled, via magazines, whole vehicle or caliber based. The option "Ammunition supply" does not show up on the attributes menu. I attempted to sync the module to the ammo truck and placed all other logistic modules down to no avail. 

**Steps to reproduce:**
- Spawn an ammo truck with an ACE rearm module
- Attempt to change the ammunition supply option via attributes

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- ace_rearm

**Comment by PabstMirror** [comment]
Tagging @GitHawk

**Comment by GitHawk** [comment]
Look like 'ACE_moduleRearmSettings' in 'CfgVehicles' is lacking the option - probably an error while merging code.

**Comment by GitHawk** [comment]
My branch still has the correct code in in [](https://github.com/GitHawk/ACE3/blob/rearm_supply/addons/rearm/CfgVehicles.hpp)

**Comment by jonpas** [comment]
Pull request with the changes was closed - https://github.com/acemod/ACE3/pull/3431

**Comment by GitHawk** [comment]
And in [3431](https://github.com/acemod/ACE3/pull/3431/files#diff-ef8826ab245037130e9d9db7cb37ab99R98) code for the module is still there!

**Comment by jonpas** [comment]
I think it's clear what happened from that PR, you clearly stated you won't work on it, so we pulled some changes but not supply limit. I am not sure why the documentation was ever merged, we should remove that until and if that functionality is on stable release.

**Comment by Glowbal** [comment]
- Documentation needs updating
- or if this is already done, close this issue.

**Comment by PabstMirror** [comment]
Fixed via #3431
