### ISSUE TITLE
Explosive Specialists of Viper and CTRG, do not have an activator M57

### ISSUE THREAD

**Issue by ghost** [acemod/ACE3#4181]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0.160713` (stable)
**ACE3 Version:** `3.6.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
These explosive specialists , do not have an activator M57(or another) of explosives. For this reason, can not use a distant detonation of explosives (Claymor, SLAM, C4 etc)

**Steps to reproduce:**
Play for explosive specialists of this faction

**Where did the issue occur?**
Editor (Singleplayer) / Editor (Multiplayer) 

**Placed Modules:**
Only Advanced and Basic Medical Modules

**RPT log file:**
not needed

**Comment by jonpas** [comment]
Those are new Apex factions right? CTRG being Pacific CTRG?

**Comment by SilentSpike** [comment]
Classnames are:

`B_CTRG_Soldier_Exp_tna_F` & `O_V_Soldier_Exp_ghex_F`

**Comment by commy2** [comment]
also `O_V_Soldier_Exp_hex_F` (note hex vs ghex)
