### ISSUE TITLE
Disable FCS for RHS ZSU-23-4

### ISSUE THREAD

**Issue by lolkij** [acemod/ACE3#4189]
Arma 3 Version: 1.62 (stable)
CBA Version: 3.0.0 (stable)
ACE3 Version: 3.6.2 (stable)

Mods:

@CBA_A3
@ace+rhs compat
`@rhs v0.4.1.1

Description:
Plz add this lines to rhs compat, because when you try to lock the aircraft at a long distance, ZSU most often captures the "sky" and the shots go much above the target. And since 0.4.1.1 ZSU-23-4 has its own firing system of shooting with anticipation. ACE FCS just breaks it.

`class rhs_zsutank_base: APC_Tracked_02_base_F
{               
ace_fcs_Enabled = 0;
    class Turrets: Turrets
    {
	class MainTurret: MainTurret
        {       
            ace_fcs_Enabled = 0;
        };
     };
};`

**Comment by commy2** [comment]
You could've made a pull request with less effort if you already went through the trouble of writing down the config.

**Comment by lolkij** [comment]
sorry, but the system of creating requests is too hard for me =) move this request where it should, if you please
