### ISSUE TITLE
Interaction with Huron Rearm Container Error

### ISSUE THREAD

**Issue by swissMAG** [acemod/ACE3#4193]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.6.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Whenever I try to use Interaction on the Huron Ammo Container, I get a script error popping up:

`15:44:18 Error in expression <tiveChildren pushBack _action;
};
nil
} count _dynamicChildren;
};
{
private _>
15:44:18   Error position: <count _dynamicChildren;
};
{
private _>
15:44:18   Error Generic error in expression
15:44:18 File z\ace\addons\interact_menu\functions\fnc_collectActiveActionTree.sqf, line 44`

The error does not appear in 3.6.1. CBA & ACE was freshly downloaded and only those activated to test it out.

**Steps to reproduce:**
- Place a Huron Ammo Container.
- Try to use interaction on the Ammo Container
- Script Error should appear

**Where did the issue occur?**
- Editor (EDEN/Singleplayer)

**Placed Modules:**
- N/A.

**RPT log file:**
- [RPT](http://pastebin.com/JCnir8S6)
- [Debug](http://pastebin.com/jeF98wPW)

Thanks :)

**Comment by commy2** [comment]
```
15:44:18 Error in expression <tiveChildren pushBack _action;
};
nil
} count _dynamicChildren;
};
 
 
{
private _>
15:44:18   Error position: <count _dynamicChildren;
};
 
 
{
private _>
15:44:18   Error count: Type Bool, expected Array
15:44:18 File z\ace\addons\interact_menu\functions\fnc_collectActiveActionTree.sqf, line 44
```

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_collectActiveActionTree.sqf#L52-L58

`_dynamicChildren` beeing a boolean

This comes from `_origAction(Action)` variable. My theory: wrong config or wrong `FUNC(addActionToClass/Object)`

@swissMAG is this reproducable with an empty mission?

**Comment by swissMAG** [comment]
Yes, I only tried it on complete empty missions except a player and the container

**Comment by swissMAG** [comment]
Just tried using the 3.6.1 version of ACE_Interact_Menu.pbo and it works fine.

**Comment by swissMAG** [comment]
After I replaced the 3.6.1 file with a fresh ACE_Interact_Menu.pbo from the 3.6.2 Zip file it seems to work...
Wierd and sorry for the troubles.

**Comment by commy2** [comment]
O.K.
