### ISSUE TITLE
RHS AFRF TrackX vehicles broken

### ISSUE THREAD

**Issue by MAD-BUG** [acemod/ACE3#4194]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.6.2` (stable )

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHS: AFRF`

**Description:**
ACE brokes all RHS AFRF swimming vehicles with TrackX simulation. In water they goes realy slow (BMP-3) or spinnig in one place(BMP-2).

**Steps to reproduce:**
- Place BMP-3 in editor (for slow speed test)/bmp-2 (for spinnig in one place test) near water and crew member
- Get in
- Ride into water

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
[- RPT](http://pastebin.com/HEXBZYY3)

**Comment by commy2** [comment]
But we don't change anything about these vehicles physx simulation. Also, tracked vehicles cannot swim in Arma, even after 1.62

**Comment by MAD-BUG** [comment]
They swim perfect without ace. And this starange movements was exact as they now for a long time. For like 2 arma stable releases.

**Comment by PabstMirror** [comment]
@MAD-BUG 
I did some tests with just RHS and no ACE or CBA (only `@RHSAFRF;@RHSUSAF;@RHSGREF;`)

https://www.youtube.com/watch?v=r_ITp-YuvkA

"rhs_bmp3_msv" did about 1 kph in water
"rhs_bmp2_msv" turned uncontrollably at the shore

Check RHS's bug tracker: http://feedback.rhsmods.org/view_all_bug_page.php

**Comment by lolkij** [comment]
TankX, not TrackX )

@esteldunedain, wait, plz
Just checked: BMP-2 (1986) is really swimming without ACE for 10-11 km/h, and 1 km/h with ACE.
But this BMP is one such. Other BMPs (1/2 (1980)/3) float with ACE and without for 1 km/h.

**Comment by commy2** [comment]
I repeat, we don't change anything about these vehicles physx simulation.

**Comment by PabstMirror** [comment]
If there is a problem we do want to fix it.

A mission where the issue always happens with ace but not without would be very helpful.
