### ISSUE TITLE
Limping from fire damage can only be healed with a PAK

### ISSUE THREAD

**Issue by Hawkeye104** [acemod/ACE3#4206]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.6.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Damage sustained to legs that cannot be bandaged (e.g. fire) causes limping and can only be healed with a PAK. Is this intended behavior?

**Steps to reproduce:**
1. Place vehicle in Zeus
2. Drag health to 0 to cause an explosion
3. Go prone and back up into the fire to damage the legs
4. Limp away

**Where did the issue occur?**
Editor/Dedicated

**Placed Modules:**
Medical Settings
Advanced Medical Settings
Revive

**Comment by PabstMirror** [comment]
Fire damage will trigger handleDamage_advanced which adds damage to `bodyPartStatus` but the incoming damage is usually small enough that it does not create new `openWounds`.

Because this now effects basic medical as well, we'll need to do something for this before 3.7

**Comment by aeroson** [comment]
You can also "heal" Limping by shooting person into his legs.

**Comment by Glowbal** [comment]
#4223
