### ISSUE TITLE
Remove keybinds for selecting weapons

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#421]
Key from vanilla now support weapon modes, so ours are no longer needed.

**Comment by VKing6** [comment]
Does the vanilla key for primary weapon toggle the GL? I.e. Semi->Full->GL->Semi etc?
Finding a way to separate the rifle part and the grenade launcher ala ACE2 would be nice.

**Comment by commy2** [comment]
Question was answered already, but for the record:

Vanilla switches between weapon modes (exactly like "next weapon mode").
Our system differentiates between GL and weapon.

Not sure if we want to keep ours anyway then.

**Comment by VKing6** [comment]
We want way to select the rifle and *not* select the GL unless you press a dedicated button.

**Comment by Mabbott** [comment]
My recommandation is the keys should stay but not be bound as to not interfere with existing binds since much of this feature is covered in vanilla A3 at this point.

**Comment by jonpas** [comment]
What Mabbott said, keep them in as long as they work but unbinded by default.

**Comment by commy2** [comment]
Alright I think we have a consensus:
>keep them in as long as they work but unbound by default.

https://github.com/acemod/ACE3/pull/762
