### ISSUE TITLE
Medical alerts nearby AI on hit/kill

### ISSUE THREAD

**Issue by freghar** [acemod/ACE3#4215]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable / dev + commit hash)
**ACE3 Version:** `3.6.2` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
When an AI gets hit, nearby AI units in other groups get alerted, tested in ~50m radius, behind or inside buildings, with subsonic ammo (ASP-1), even if the units gets killed in one shot. Removing `ace_medical.pbo` "fixes" the issue.

**Steps to reproduce:**
- https://drive.google.com/open?id=0B-VJDqVv2ipPUjdJVzNPSWFqanM (requires mark DLC due to ASP-1 Kir)
1. Load the mission
2. Switch ARCO zoom to 3x
3. Shoot a few bullets between the two soldiers, hitting the ground even ~10m away from them won't trigger an alert (not a ballistic issue)
4. Aim between feet of the soldier in front on the road, shoot (should one-shot-kill the soldier)
5. Open up Zeus, see the other unit in the town, behind a building, become alerted

**Where did the issue occur?**
- Tested on Dedicated / Editor (Singleplayer)

**Placed Modules:**
- None (But disabling AI unconsciousness didn't help)

**RPT log file:**
- https://gist.github.com/freghar/2b23952edcb1a0c442f7164157e15190

**Comment by Glowbal** [comment]
We do not modify any AI behaviour within medical. I've got no clue what would cause this from within medical.

Maybe the difference is the fact we use `setDamage` for killing an unit? If so, there won't be much we can do about this.

**Comment by freghar** [comment]
This seems to happen when a unit gets hit as well, not just on death. However overall, the reproducibility is about 80%, which I find kind of strange.

I just reduced the pbo set to the minimum necessary to get ace_medical working and the issue still seems to be happening. I also tried to `setDamage 0.9` from a script, but the unit didn't change its behaviour (some combination with `reveal` might be needed, I don't know).

If you have any ideas how to debug this further (incl. code patches), I'm all ears, thanks.

Ultimately, there could be a global "ignore all of ace_medical for AI" switch, like there's for stamina, I believe, if there's no better solution.

**Comment by crowmium** [comment]
Wouldn't this be related to Arma's normal behavior of alerting the entire squad when any single member becomes "aware" of the enemy? As far as I know, this behavior doesn't change even with silent kills. The only way to fix it would be to remove the unit from the squad prior to the point in the detection code where enemy awareness propagates and then administering the damage. With the way groups work, I'm not sure that would even be a good idea. It could cause some serious performance issues depending on how it has to be implemented.

**Comment by freghar** [comment]
The original report mentions "nearby AI units in other groups".

**Comment by freghar** [comment]
Just reporting that this issue still exists with ACE v3.12.2 and Arma3 v1.82.

If you have any code pointers that would allow me to ie. disable most of `ace_medical` for AI (or all) units to see if the behavior changes, please do share them.

I've tried (as suggested above) to kill units in vanilla with `setDamage` (using straight `1` or various values), but it never alters the `targets` list of any other units/groups. Shooting a unit with `ace_medical` enabled does put me on `_unit targets [true]` lists of all other nearby units, alerting them.

I even modified `muzzle_snds_*` classes (overriding `ace_ballistics`) to rule that out of the equation - shooting the sky 1 meter behind the AI doesn't trigger anything, but as soon as it actually hits/kills a unit, any nearby groups are alerted.

I've measured the distance and it is exactly 80 meters around the hit/killed unit.

Removing all runtime EH types (via `removeEventHandler` looping over all types) did not help.

Disabling the appropriate `PreStart`/`PreInit`/`PostInit` XEHs did not help (though it did disable most of medical stuff ingame).

**Comment by freghar** [comment]
So, experimenting further, and I think I figured it out. I was wrong about the XEH part; commenting it out fixes the issue on a minimal set of
```
ace_apl.pbo
ace_common.pbo
ace_interact_menu.pbo
ace_interaction.pbo
ace_main.pbo
ace_medical.pbo
ace_modules.pbo
```

Vanilla game alerts any nearby groups if a unit is hit, but not killed. This can easily be demonstrated by non-fatally hitting the unit. If the unit is killed instantly (headshot without a helmet), no alert is done.
Similarly, if `setDamage` is used, no alert is triggered.

However `ace_medical` prevents any hit from being an instant kill by
```sqf
// prevent death
if (_damageNew >= 0.9) then {
    _unit setDamage 0.9;
    [_unit] call FUNC(setDead);
} else {
    _unit setDamage _damageNew;
};
```
which would be okay, but then `setDead` does:
```sqf
//Delay a frame before killing the unit via scripted damage
//to avoid triggering the "Killed" Event twice (and having the wrong killer)

if (!_delaySetDamage) then {
    [_unit, 1] call FUNC(setStructuralDamage);
} else {
    [FUNC(setStructuralDamage), [_unit, 1]] call CBA_fnc_execNextFrame;
};
```
and that one frame makes all the difference (unit is alive and was hit).

**Comment by BaerMitUmlaut** [comment]
Does not occur in medical rewrite anymore. Tested with the following setup (units are 15m apart):

![20201102230925_1](https://user-images.githubusercontent.com/9693842/97924746-6e540c80-1d60-11eb-85d8-6dee2f9cf71e.jpg)
