### ISSUE TITLE
RHS and ACE Compatability?

### ISSUE THREAD

**Issue by DieselJC** [acemod/ACE3#4220]
Just have a simple question about running ACE3 and RHS is there a comaptability mod I need in order for these to work correctly on a dedicated server?
Currently running Stable version and mods are:
@CBA_A3
@ace3
@RHSUSAF

**Comment by jonpas** [comment]
Copy `ace_compat_rhs_usf3.pbo` and `ace_compat_rhs_usf3.bikey` from `optionals` to `addons`. If you also use AFRF also copy the respective compatibility PBO.

**Comment by DieselJC** [comment]
Thanks for the reply..much appreciated will give that a try..I noticed when I downloaded ace from here it is listed as @ace not @ace3..my client is @ace3 is that going to cause an issue?

**Comment by jonpas** [comment]
No, that won't be a problem.
