### ISSUE TITLE
ACE installed on Server - ACE Advanced medical / ACE Options not working for all players

### ISSUE THREAD

**Issue by JudahHarvey** [acemod/ACE3#4224]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `Current as of 2017-07-02 (Armaholic)` (stable / dev + commit hash)
**ACE3 Version:** `3.6.2` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- ACE3 Modules placed down in mission works in local hosted mission. All systems work properly. When loaded into Server, ACE advanced medical system, pointing system, and other functions do not work, ACE options menu is blank for all players.

**Steps to reproduce:**
- In ServerConfig.hpp 
class ace_common_forceAllSettings {
    value = 1;
    typeName = "BOOL";
};

-Try to open the ace options menu

**Solution**

Turn the Value to 0, your options menu comes back. Hurr.

**Where did the issue occur?**
- Following installation of ACE 3.6.2 following APEX update.

**Placed Modules:**
- ANY, all ACE modules change to their default function

**ADDITIONAL INFO**

Server is installed to a separate Folder from ACE3 Mod. Server folder does contain USERCONFIG folder just like a regular arma 3 installation. It is not a junction, but an actual installation. Server did have working settings before latest patch. -Filepatching is enabled. ACE_Server is installed to addons folder.

http://pastebin.com/yDCqAEdi

I've gone and removed as much stuff as possible from the modset, mission, and everything else, and I still get the same error that I get when I have all the other mods. When I test the mission played in single player, all of the ACE OPTIONS are working fine. When I test them in a server, they disappear for all players. Screenshot attached. The server has loaded the mods from the same repository that players do, and players all have working ace options unless they join  this particular server.
![107410_screenshots_20160813190644_1](https://cloud.githubusercontent.com/assets/16574249/17646128/83ec649e-6189-11e6-9b97-1706bfd3bd5d.jpg)

If it's any help. I have managed to fix the ACE3 serverside settings by removing the modules from the mission, and using class ace_common_forceAllSettings {}; and the appropriate userconfig settings. Advanced Medical is working now, as are the other functions. However, ACE3 Options are still not working as shown in the above screenshot. 

http://pastebin.com/UphNVSw3

This is an RPT from a client machine, running the same mods, which does see ACE3 Options working in a listen server and single player environment running the same mission.

**Comment by Glowbal** [comment]
Hi, could you please provide us with rpt log files from your server?

**Comment by JudahHarvey** [comment]
http://pastebin.com/HRJTUeV2

Just generated a new one, tried to cut down on some of the spam. I also just turned the 
class ACE_common_forceAllSettings {
    value = 1;
    typeName = "BOOL";
};
 to Value = 0; to see if there was an improvement. There was not. I can try and cut down on the RPT spam, if desired.

**Comment by bux578** [comment]
@JudahHarvey Please, just leave everything in there. Even "spam" could lead to a potential conflict, bug, etc ...

**Comment by JudahHarvey** [comment]
Gotcha, it was just reports from some scripts that we run mission side. Nothing major was removed.

**Comment by commy2** [comment]
The RPT does not match the error report.
```
Mods:

@CBA_A3
@ace
```
```
mod=C:\ArmA3Servers\ServerMods\@asm;C:\ArmA3Servers\ServerMods\@inidbi;C:\ArmA3Servers\ServerMods\242PublicModsV400\@242CPMv400;C:\ArmA3Servers\ServerMods\242PublicModsV400\@242sthudv400;C:\ArmA3Servers\ServerMods\242PublicModsV400\@242task_force_radiov470;C:\ArmA3Servers\ServerMods\242PublicModsV400\@242Aresv490;C:\ArmA3Servers\ServerMods\242PrivateModsV400\@242ARP2v400;C:\ArmA3Servers\ServerMods\242OverModsv400\@242ASRCompatsv466;C:\ArmA3Servers\ServerMods\242PrivateModsV400\@242AtlasLHDv4242016;C:\ArmA3Servers\ServerMods\242PrivateModsV400\@242AVmodsV482;C:\ArmA3Servers\ServerMods\242PrivateModsV400\@242babe_targetsv490;C:\ArmA3Servers\ServerMods\242Effects\@242BlastcoreV490;C:\ArmA3Servers\ServerMods\242PrivateModsV400\@242Cha_Lav25v490;C:\ArmA3Servers\ServerMods\242PrivateModsV400\@242FA18X_Black_Waspv400;C:\ArmA3Servers\Serve
```

https://github.com/acemod/ACE3/blob/master/.github/CONTRIBUTING.md
```
Before reporting

If you have found an issue with ACE3 please make sure that ACE3 really is the cause of the problem. To do this try to reproduce the issue with using only @CBA_A3 and @ace on a newly created mission.
```

_______

It looks like you are using at least one poorly made mod which breaks many things in the game.

**Comment by commy2** [comment]
>Nothing major was removed.

I don't think you are able to tell. If you need our help, then you have to provide a full error report.

**Comment by JudahHarvey** [comment]
I will generate a new RPT file with only the mods listed, Standby.

**Comment by JudahHarvey** [comment]
http://pastebin.com/yDCqAEdi

I've gone and removed as much stuff as possible from the modset, mission, and everything else, and I still get the same error that I get when I have all the other mods. When I test the mission played in single player, all of the ACE OPTIONS are working fine. When I test them in a server, they disappear for all players. Screenshot attached. The server has loaded the mods from the same repository that players do, and players all have working ace options unless they join  this particular server.
![107410_screenshots_20160813190644_1](https://cloud.githubusercontent.com/assets/16574249/17646128/83ec649e-6189-11e6-9b97-1706bfd3bd5d.jpg)

**Comment by commy2** [comment]
Fix this:
```
19:22:15 Error in expression <SS_NAMETAG_MISSION_DISABLE ="xyz";
call NS_FNC_CheckFaction;
call NS_FNC_vehicl>
19:22:15   Error position: <NS_FNC_CheckFaction;
call NS_FNC_vehicl>
19:22:15   Error Undefined variable in expression: ns_fnc_checkfaction
19:22:15 File mpmissions\__CUR_MP.Tanoa\initPlayerLocal.sqf, line 4
```

`NS_FNC_CheckFaction` is some kind of function, but undefined. Can you upload the mission? It's most likely a bug in there.

@PabstMirror ?
```
19:22:15 [ACE] (common) INFO: Settings received from server.
19:22:15 [ACE] (common) WARNING: Setting found but couldn't localize [acex_sitting_enable] (server has but we don't?)
19:22:15 [ACE] (common) WARNING: Setting found but couldn't localize [acex_viewrestriction_mode] (server has but we don't?)
19:22:15 [ACE] (common) WARNING: Setting found but couldn't localize [acex_viewrestriction_modeSelectiveFoot] (server has but we don't?)
19:22:15 [ACE] (common) WARNING: Setting found but couldn't localize [acex_viewrestriction_modeSelectiveLand] (server has but we don't?)
19:22:15 [ACE] (common) WARNING: Setting found but couldn't localize [acex_viewrestriction_modeSelectiveAir] (server has but we don't?)
19:22:15 [ACE] (common) WARNING: Setting found but couldn't localize [acex_viewrestriction_modeSelectiveSea] (server has but we don't?)
19:22:15 [ACE] (common) WARNING: Setting found but couldn't localize [acex_headless_Enabled] (server has but we don't?)
19:22:15 [ACE] (common) WARNING: Setting found but couldn't localize [acex_headless_Delay] (server has but we don't?)
19:22:15 [ACE] (common) WARNING: Setting found but couldn't localize [acex_headless_Log] (server has but we don't?)
19:22:15 [ACE] (common) INFO: Settings initialized.
```

**Comment by PabstMirror** [comment]
Server must be running acex but client isn't

**Comment by commy2** [comment]
Could that break it?

**Comment by PabstMirror** [comment]
Just tried, got the `Setting found` warnings, but the menu still opened and worked
That script error might be breaking the init chain?

Please hit the debug to clipboard button in the options menu and paste that into gist/pastebin.

**Comment by JudahHarvey** [comment]
The server and clients are all only running ACE3 and CBA, as shown in the RPT. There is no usage of ACEX anywhere in the server, or the client. When clients/server run ACEX in our normal usage, the problem persists.

MissionConfig functions do not affect the issue. The problem appears regardless of what mission is loaded, which mods are loaded on top of the ones described, etc.

http://pastebin.com/pnr182SY

This paste was generated using a blank mission file with nothing but a single NATO soldier placed down. Players using mods downloaded from the same repository report being able to open the Ace Options menu from single player with no issue. They also report being able to use it on other servers with no issue. This problem only occurs when players join this server.

**Comment by Glowbal** [comment]
Client side options do not show up in the options menu when forced. You are using the force all settings setting, which also includes forcing client settings.

**Comment by JudahHarvey** [comment]
The issue occured before I started using forceallsettings. The only problem is that the modules also did not work. Using ForceSettings was only done to re-enable the mission. I'll generate more RPTs of this issue with these settings removed.

**Comment by JudahHarvey** [comment]
AHA! T

That seems to have cleared up the issue, changing that forceAllSettings class to 0 . I've taken the setting to 0, and the functions still persist with the pointing and medical system, but the options menu is back. Somehow I must have set that setting to 1 thinking that it had done something else. Luckily now, everything is fixed. Thanks for your help Glowbal.
