### ISSUE TITLE
VTOL blackfish cannot be targeted by ACE3 action key (repaired too)

### ISSUE THREAD

**Issue by DLEGION** [acemod/ACE3#4233]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.6.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- the nato VTOL, the "blackfish" , due to its huge mass and too high "center point" , cannot be targeted by ACE3 interaction. Not for "virtual arsenal" and for repairs with ace3 mod too!

**Steps to reproduce:**
- open the editor, place a player, a nato VTOL , and damage it a bit, then try to repair it.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) 

**Placed Modules:**
- none

**Comment by jonpas** [comment]
Already aware, thanks for making the issue though. :+1:

**Comment by jonpas** [comment]
Not sure how to best go about it, simply lowering the main interaction point (by default slightly above the VTOL itself) doesn't work, there is something else blocking it and it doesn't seem to be distance. Using `FUNC(getVehiclePos)` that is used for helicopters and ships doesn't help either.
