### ISSUE TITLE
QUESTION: Re-adding addaction for fixing left mouseclick corruption

### ISSUE THREAD

**Issue by AlManiak** [acemod/ACE3#4235]
Hello, I hope its ok to just ask questions here.

I've been trying to fix the left mouseclick problem when playing Antistasi. Knowing that the problem is because of removeallactions player, I was wondering if I could manually add the necessary ace actions again afterwards as a hacky fix? I've been digging through the github a bit and tried some scripting commands, but have not had any luck at the moment.

Is there any way to do this? Or am I'm chasing shadows here?
Thanks in advance!

**Comment by jonpas** [comment]
What does that have to do with ACE3? We don't use `removeAllActions`, those actions that we do remove are replaced by our custom systems (such as refuel).

If you'd like general scripting help you are welcome on our [Slack](http://slackin.ace3mod.com/).

**Comment by PabstMirror** [comment]
@AlManiak Compatibility should be improved by #4079 which will be in next release as there won't be an action on all the time, only when it is in use.

For 3.6.2, this should recover after `removeAllActions player` is used:

```
player setVariable ["ace_interact_menu_AAEHID", nil];
player setVariable ["ace_action_defaultAction", nil];
[player, objNull] call ace_interact_menu_fnc_handlePlayerChanged;
```

No guarantees, it is very bad practice for a mod to be using the `removeAllActions` command.

**Comment by AlManiak** [comment]
That's great to hear!
I've tested it and it seems to work (mostly, but good enough for a hacky fix, at least we can place explosives now! :+1: )

I did not make the mission myself, so I'm working with what I've got in terms of code standards. It's a great mission though so I really wanted to have some kind of cheeky fix to play it with my mates.

Anyhow, thanks a bunch! Keep up the great work!
