### ISSUE TITLE
[Request] Add "M112 charge" to ace_compat_rhs_usf3.pbo

### ISSUE THREAD

**Issue by lolkij** [acemod/ACE3#4237]
**Arma 3 Version:** 1.62 (stable)
**CBA Version:** 3.0.0 (stable)
**ACE3 Version:** 3.6.2 (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@rhsusaf` + compat pbo

**Description:**
- Plz add the "M112 charge" and "M112 x4 charge pack" to RHS USAF compat pbo, because they use vanilla interaction with explosives.

Classnames:
rhsusf_m112_mag
rhsusf_m112x4_mag

**Comment by Giorgy32** [comment]
Yup guys..i was just ready to post as *new issue thatall RHS (explosive related) units dont use ACE system for their explosives. (thank search function :D )
Well ..the 1st solution was already mentioned-but i ll also be happy with replacing type of explosives when an "incompatible" unit is detected on mission initialization

Thanks again

**Comment by Saborknight** [comment]
Could we have a bump on this?

**Comment by dedmen** [comment]
Didn't know this ticket existed. Same problem here, people take RHS explosives by accident.
Then at target they see that it's the wrong one and say "oh... oh crap"
Not sure what's needed to make explosives ace compatible?

Guess these:
https://github.com/acemod/ACE3/blob/master/addons/explosives/CfgAmmo.hpp#L30-L33
https://github.com/acemod/ACE3/blob/master/addons/explosives/CfgMagazines.hpp#L50-L60
And the CfgVehicle classes mentioned in the CfgMagazines config
https://github.com/acemod/ACE3/blob/master/addons/explosives/CfgMagazines.hpp#L6

https://github.com/acemod/ACE3/blob/master/addons/explosives/CfgVehicles.hpp#L180

**Comment by Saborknight** [comment]
I would assume that it'd be more appropriate to have them added to the optional addons. Also, the ACE wiki has a section on how to add them, someone just needs to do it I guess xD

**Comment by Saborknight** [comment]
This should be closed, it's already merged into master according to this: https://github.com/acemod/ACE3/commit/cf389fba76a203b057acf26481020b24f6b561ed

**Comment by bux** [comment]
Thanks @Saborknight
