### ISSUE TITLE
Removing items handcuffed person

### ISSUE THREAD

**Issue by Ghost77788** [acemod/ACE3#424]
Frisking a person doesnt allow to remove any hidden threats, like handgun, explosives or known threats when you have cuffed a person with a primary or secondary weapon.

Have written a working version for this for AGM.
Where should i post these files?

**Comment by rlex** [comment]
:+1: this is a nice feature.

**Comment by Ghost77788** [comment]
Thank you, do you by any chance know where i should post the modified agm files

**Comment by rlex** [comment]
I'm gonna assume you should rewrite it for ACE and then send a pull request, however i'm not sure. 
Some of the devs should respond...

**Comment by Glowbal** [comment]
The proper way to go by this is to fork the repository and submit a pull request.

Ensure it complies with our coding [guidelines](http://acemod.github.io/ACE3/wiki/dev/coding-guidelines.html) and [practices](http://acemod.github.io/ACE3/wiki/dev/arma-3-scheduler-and-our-practices.html)

**Comment by Ghost77788** [comment]
Thank you both for the quick responses.

I will go over everything

**Comment by jaynus** [comment]
Closing.
