### ISSUE TITLE
AtragMX 7.62 M993/M118

### ISSUE THREAD

**Issue by dramabeats** [acemod/ACE3#4243]
**Arma 3 Version:** `1.62` (stable
**CBA Version:** Up to Date
**ACE3 Version:** Up to Date

**Mods:**
- `@CBA_A3`
- `@ace`
- @RHSUSAF

**Description:**

M993 and M118 ballistic data is inaccurate for the RHS Mk11. 

-Advanced ballistics enabled
-Entered Data from Kestral
-Used Vector 21 to record target data

Test the .408 and it works fine

Mainly inaccurate past 1000m

**Where did the issue occur?**
Single Player

**Placed Modules:**
Advanced Ballistcs

https://gist.github.com/dramabeats/c43b2774a313de376659fd1c4e77e59b

**Comment by bux578** [comment]
@J3aLeiNe

**Comment by dramabeats** [comment]
@bux578 added to bottom

**Comment by dramabeats** [comment]
The range card is spot, but the atragmx is spitting out a completely different firing solution:

At 1150 meters the Atrag gave me 25.23 MILs of elevation adjustment, inc angle C: .97 and D:-14

The range card said 16.8

The Atrag firing solution was 10+ meters high
Range table was a first round hit on target

**Comment by J3aLeiNe** [comment]
It cannot explain totally your problem but you are right,
the BC for the M993 in the compat_rhs_usf3 is not correct (0.377, should be 0.359).
Actually, the AtragMx has a bug with the firing solution on elevation https://github.com/acemod/ACE3/issues/3607, 
in fact, the best way is the range card in-game or a external ballistic software.
But i will recheck all values one more time. :)

**Comment by dramabeats** [comment]
@J3aLeiNe So this will have to adjusted in the next ACE update? I noticed the MK318 ammo has a similar issue. Not sure if it's all of 5.56 and 7.62

**Comment by dramabeats** [comment]
Also, I noticed using the RHS scopes, if you use ace to dial 1 mill at a time to say 17 mils, then use the .1mil adjustment up to 17.5, the smaller adjustments will change your "zero" in the upper right hand corner. I unbinded the default arma keys and turned off "zeroing" in ace, but it still occurs. Is this a RHS issue or a ACE issue?

**Comment by J3aLeiNe** [comment]
@dramabeats , I forgot that, the RHS scopes don't work correctly 
and it will be fixed in the next vesion : https://github.com/acemod/ACE3/issues/4162

I made a quick test with the M118 ammo and a LRPS and it is not bad, i think 
http://images.akamai.steamusercontent.com/ugc/269474483215694955/6C4E31944774628D37F6A14755EC50043C1E8B62/

http://images.akamai.steamusercontent.com/ugc/269474483215696628/1142961FA2F808D07436F1E8AFFE2CA9CC5FAE86/

**Comment by J3aLeiNe** [comment]
Same issue and same fix as here https://github.com/acemod/ACE3/issues/4162,
you can close if you want @bux578 .

**Comment by bux578** [comment]
Ok.

Fixed by #4028
