### ISSUE TITLE
Vehicle that is cooking off is able to shoot back

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#4244]
**Arma 3 Version:** `1.62 stable`
**CBA Version:** `3.0.0 stable`
**ACE3 Version:** `current dev` 223146408708e30e675e851fdf030a0cc0250406

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
A vehicle that is cooking off is able to shoot back. Barbecue can't shoot. :smile: 

**Steps to reproduce:**
https://youtu.be/atZWnZQh698

**Where did the issue occur?**
Editor (Singleplayer)

**Placed Modules:**
None

**RPT log file:**
http://pastebin.com/E4UN0kSk

(and: `11:35:46 [ACE] (cookoff) WARNING: no valid selection for cookoff found. O_APC_Wheeled_02_rcws_F File: z\ace\addons\cookoff\functions\fnc_cookOff.sqf Line: 31`)

**Comment by commy2** [comment]
How would you fix that? Ejecting the AI? Wouldn't stop players from doing this.

**Comment by SilentSpike** [comment]
Remove ammo?

**Comment by bux578** [comment]
`disableAI` and remove ammo as @SilentSpike wrote. Because the cook off is because off ammo burning.

**Comment by commy2** [comment]
You cannot use disableAi to stop the AI from firing.

**Comment by commy2** [comment]
Removing the magazines breaks the secondary explosions
https://github.com/acemod/ACE3/blob/master/addons/cookoff/functions/fnc_secondaryExplosions.sqf#L36

**Comment by jonpas** [comment]
Did AGM have the same bug?

**Comment by SilentSpike** [comment]
All I can think of is to write it such that any piece of code which needs the magazines should read them first, then you remove them.

**Comment by commy2** [comment]
I think so

**Comment by commy2** [comment]
I'll eject the AI

**Comment by SilentSpike** [comment]
Maybe even cache them as a variable on the vehicle if you have to

**Comment by jonpas** [comment]
Wait, does that only happen with AI? A player can't shoot inside cooking off vehicle?

**Comment by commy2** [comment]
No, but the players will have their vision obstructed by the flame pp effect. They'll probably eject.
I don't see why the vehicle burning would instantly disable the guns.
