### ISSUE TITLE
UAV terminal doesn't have GPS

### ISSUE THREAD

**Issue by rlex** [acemod/ACE3#425]
subj

**Comment by commy2** [comment]
I think I now whats up with that / want to rewrite the part that handles this anyway.

**Comment by rlex** [comment]
There was a ticket about it in AGM repo, something about inheritance issues.

**Comment by esteldunedain** [comment]
This has nothing to do with inheritance, but with this:

https://github.com/acemod/ACE3/blob/master/addons/common/scripts/assignedItemFix.sqf#L17

**Comment by commy2** [comment]
Exactly. This PFH can be replaced by an playerInventoryChanged handler.
Not sure how to handle third party addons, but I certainly want to disable the clock when you have an altimeter instead.

**Comment by CorruptedHeart** [comment]
Maybe [CBA_fnc_inheritsFrom](https://dev.withsix.com/docs/cba/files/common/fnc_inheritsFrom-sqf.html#CBA_fnc_inheritsFrom) can help?

**Comment by commy2** [comment]
IDK if we want to rely on that. I'd rather make a blacklist with an API function.

**Comment by commy2** [comment]
["ACE_Altimeter", "ItemWatch"] call EFUNC(common,disableAssignItemSlot);

or something like that.
