### ISSUE TITLE
Arma 3 Linux server extension dll not install

### ISSUE THREAD

**Issue by 00specter00** [acemod/ACE3#4253]
Arma 3 Version: 1.62 (stable)
CBA Version: 3.0.0.160713 (stable)
ACE3 Version: 3.6.2 (stable)

Mods:
- @CBA_A3
- @ace

Description:
Arma3 server in ubuntu. After the role selection screen and press continue. Before the screen brifing the following error appears in the log:

```
[ACE] (common) ERROR: Extension ace_break_line.dll not installed.
[ACE] (common) ERROR: Extension ace_parse_imagepath.dll not installed.
[ACE] (common) ERROR: Extension ace_clipboard.dll not installed.
[ACE] (common) ERROR: Extension ace_fcs.dll not installed.
[ACE] (common) ERROR: Extension ace_advanced_ballistics.dll not installed.
```

This occurs since the last update of Arma.

**Comment by commy2** [comment]
.dll s don't work for windows. none of these are needed on a dedicated server.

You can ignore these.

**Comment by PabstMirror** [comment]
Servers on the normal branch will work fine on linux,
but playing with the 1.58 port won't work
#3137

**Comment by commy2** [comment]
Report says 1.62 and Arma3 server (presume dedicated)

**Comment by 00specter00** [comment]
Indeed dedicated server is mounted on linux. I reviewed the log and another error that appears is this :

Mission directory : mpmissions \ __ cur_mp.Altis \
Can not find real path " a3 \ map_altis \ data \ roads \ roads.shp ": " No such file or directory"

**Comment by commy2** [comment]
I don't think these have anything to do with ACE. The first one isn't even an error.
