### ISSUE TITLE
ACE files missing

### ISSUE THREAD

**Issue by Cameron-Parris** [acemod/ACE3#4255]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / --> Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.
- CBA_A3, Military Gear Pack, Advanced AI Command, Advanced Rappelling, Advanced Sling Loading, Advanced Towing, Advanced Urban Rappelling, ALiVE, ASCZ Arsenal Ammobox, ATLAS LHD PLUS, Advanced Combat Environment 3.6.2, Advanced Combat Environment Extras 3.0.0, (both spelled exactly as written, downloaded straight from link), MGI Tactical Pack V3, and Hollow's Vehicle pack. All but 2 of those are downloaded straight from Steam Workshop.
**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

Pop-up window said this:  There is a missing file that's not installed when i dowloaded it from [](url)http://ace3mod.com/team.html. The file is Extension ace_fcs.dll is not installed, atleast when i start Tanoa Liberation 0.924 - Apex 2.0. 

Please help me fix this!

**Comment by bux578** [comment]
Please edit your issue to follow the guidelines we expect.
And please add the RPT file.

Otherwise, we can't help.

**Comment by RSpeekenbrink** [comment]
make sure that your anti-virus is not blocking the dll file

**Comment by ace3mod** [comment]
Hello!

We're automatically closing this issue since it has not received any updates or comments in the past 14 days. We therefore assume that the original reporter has lost interest or the issue has been resolved.

If this has been closed in error,  please create a comment below and we can reopen this issue. Note that you may need to provide additional information that was requested. 

Thanks!
