### ISSUE TITLE
FPS Issues with bodies

### ISSUE THREAD

**Issue by GuzzenVonLidl** [acemod/ACE3#427]
Problem:
Fps drops very quickly to more or less 0 after shooting multiple times within a short period of time.

First occurred when I tried the m134 on the ah9 shooting as some ai, after a few seconds my fps dropped from 60+ to 0-3 for 10 seconds and when back up to 60, after I tried the rockets and then the mk200

Version: 0.0.1 the first build that just got released on armaholic

**Comment by commy2** [comment]
Please upload the RPT-file @pastebin.com and post the link.

Also provide additional information:
- Did you test with the latest CBA and without any other modifications?
- Did you test in Single or Multiplayer?

**Comment by GuzzenVonLidl** [comment]
Only tested it in editor and only with cba & ace and yes latest

**Comment by GuzzenVonLidl** [comment]
http://pastebin.com/ShUB3Y5Z

**Comment by GuzzenVonLidl** [comment]
Update again, tested on a local dedi, result is even worse
Client seems to be more or less fine just a few fps drops.

Server dies, as in the fps goes down to 0 and never goes back up again(waited for 5 min)
I used the BIS Server fps (#monitor 5), after sometime it stops to update.

Also I used the test mission
call out again if you want the log for the server but doubt it will help

**Comment by Glowbal** [comment]
What were the settings you used?

**Comment by GuzzenVonLidl** [comment]
when you say settings, which ones exactly

**Comment by Glowbal** [comment]
Did you place down any modules or used a config file to adjust settings? Or where you just playing with default settings?

**Comment by GuzzenVonLidl** [comment]
nothing changed, as stated using version on armaholic, just booting that up and then loading the test mission that is included in the configs

**Comment by jaynus** [comment]
This could either be related to a missing isDedicated check somewhere. Most likely, though, its related to the test mission.

**Comment by alganthe** [comment]
no issue here, master branch latest commit being 1b5756d33c3a6d09452aa08a361d47bfa7784520

**Comment by bux578** [comment]
Going to close this ticket. OP should create a new ticket if it happens again.
