### ISSUE TITLE
Map tools deleting maps?

### ISSUE THREAD

**Issue by Zyles** [acemod/ACE3#4279]
**Arma 3 Version:** `1.62.137494` (stable)
**CBA Version:** `13 July` (stable)
**ACE3 Version:** `3.6.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**

I had a very weird occurance when I started using map tools. During a session it deleted my inventory map over 5 times (we spawned in new ones). I could still access the map but could not interact with it in any way. I could not move the map tools around either.

**Steps to reproduce:**
- Use map tools on your map
- Play a bit and do stuff (???)
- Map gets deleted

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- Zeus

**Comment by bux578** [comment]
RPT please.

**Comment by esteldunedain** [comment]
In my opinion this is most likely not related to the map tools. That code doesn't add/remove items from the inventory at any point.

**Comment by 50KAL0V** [comment]
We've been having a similar issue.

On mission start there is a 10% chance you don't have a map. Have been having this issue for a while now and just end up creating a box of maps with Zeus at the start of missions.

 Don't have the issue during missions thou, only at the start (map isn't even available at the briefing screen)

**Comment by bux578** [comment]
@50KAL0V 

> RPT please.

**Comment by lolkij** [comment]
Zyles, do you have "iteminfo.scope" pop-up error when arma starts? If so, then the problem is definitely not due to the map tools.

**Comment by Zyles** [comment]
@lolkij yes, what is it?

**Comment by lolkij** [comment]
This means that the deleting maps you should blame the another addon(s) that displays this error. Try to disable all addons (exept ACE and CBA) and enable them one by one until you find the problem one.

**Comment by bux578** [comment]
And please note. We can't and won't help until we get all the information requested. That includes a complete RPT file of the session where this issue occured.

**Comment by 50KAL0V** [comment]
understood @bux578 @lolkij , thanks for the help.

A lot of the big mods out there (NIArms, 3CB, RH, etc.) are still waiting on the "iteminfo.scope" changes. Good to know that will be the cause. Will standby for their fixes, but until then the map box will fix all.

Cheers guys.
