### ISSUE TITLE
"Lockpick vehicle" available even when vehicle is not locked

### ISSUE THREAD

**Issue by rlex** [acemod/ACE3#428]
ACE3 Version: master

**Mods:**
* @cba_a3
* @ace3
* @RHSUSF
* @RHSAFRF

**Placed ACE3 Modules:**
* None

**Description:**
* Even on non-locked vehicle, you still able to use lockpick kit to "lockpick" empty vehicle

**Steps to reproduce:**
* Open VR scenario 
* Add lockpick kit to inventory
* Spawn any vehicle
* Open interaction menu, "lockpick" will be here, but vehicle is not locked.

**Where did the issue occur?**
* SP, VR Scenario, also tried on MP.

**RPT log file:**
* None

**Comment by esteldunedain** [comment]
For future reference, all bug reports need to comply with this guidelines:

http://acemod.github.io/ACE3/wiki/user/how-to-report-an-issue.html

Due to the amount of traffic on the tracker we'll probably won't be considering anyone that doesn't..

**Comment by rlex** [comment]
adjusted.

**Comment by esteldunedain** [comment]
> adjusted.

Thanks.

**Comment by rlex** [comment]
Still a case on newly spawned transport (variable locked = nil on fresh vehicles?
