### ISSUE TITLE
ACE Refuel compatibility with Huron slingload fuel tank

### ISSUE THREAD

**Issue by tdiniz93** [acemod/ACE3#4284]
Right now I cannot grab a fuel hose off of the Huron slingload fuel tank, and it doesn't refuel like the gas stations on the map.

**Comment by jonpas** [comment]
Please use the issue template and simply fill it out. We at least need the RPT to be able to assist in any ways.

I just tried using Huron Fuel Container and it worked fine.

**Comment by tdiniz93** [comment]
I got it to work, I had to get really close to interact. You can close this.

**Comment by jonpas** [comment]
Yeah, you have to go close, which makes sense IMO.
