### ISSUE TITLE
Combat Engineering Vehicle System suggestion

### ISSUE THREAD

**Issue by tdiniz93** [acemod/ACE3#4287]
I'd like to suggest reusing the entrenching tool's code to allow the default ArmA 3 combat engineering vehicle (Nemmera) to build defenses like H-Barriers and earthen ramparts(spawn them just like the E-Tool does), with a module to change it between ArmA 3 and APEX expansion H-Barriers.

**Comment by bux578** [comment]
Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html

**Comment by tdiniz93** [comment]
Sorry about that. I'll go post it there.
