### ISSUE TITLE
Compatibility Files for inexperienced users of RHS.

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#4288]
Create a compatibility mod, instead, simply, compatibility files for the inexperienced RHS users. Because connect the additional addon via Steam launcher much easier, than to explain how and where to insert these files.

**Comment by jonpas** [comment]
We have some plans for that in the future, no ETA though.

**Comment by GalNa** [comment]
At least as a temporary solution.

**Comment by jonpas** [comment]
That wouldn't make any sense, there is a lot to do to keep a compatibility mod up and we have no intentions of doing it manually.

**Comment by PabstMirror** [comment]
This is what https://github.com/acemod/ACE3/pull/4163 was designed for.
We could setup the steamworkshop repo now from 3.6.2 release fairly easily.

**Comment by kripto202** [comment]
temporary solution: go to the steam workshop and download the rhs compatibility that I submitted. I have it individual for usaf and rfaf

**Comment by GalNa** [comment]
Can I use this addon as a client? Can I use this addon as a dedicated server without violating someone's rights?
http://steamcommunity.com/sharedfiles/filedetails/?id=698224854

**Comment by kripto202** [comment]
how ace has it that if you are running the compat and if the server isn't running the compat, you will get kicked as soon as you load the mission. I don't think it is updated (i could be wrong) for a while now. You have to make sure that the server is running the compat pbos too.
