### ISSUE TITLE
ACE3 Public Slack (Chatroom) Join Requests

### ISSUE THREAD

**Issue by kieran-s** [acemod/ACE3#429]
For anyone who wants to join the public ACE3 slack (it's basically a chatroom type thing), please follow these instructions and I will send you an invite.

Please do one of the following:
- Post your email as a comment to this issue
- OR
- Send me a PM on the BIS forums (http://forums.bistudio.com/member.php?102995-bux578) [[please post here to let us know you have sent me a PM]]

It's open for everyone/anyone to join. :)

**Comment by armyinf0703** [comment]
armyinf0703@hotmail.com

**Comment by Winter259** [comment]
simon@agius-muscat.net please

**Comment by kavinsky** [comment]
nmunozfernandez@gmail.com

**Comment by nic547** [comment]
nic547@outlook.com

**Comment by omar2205** [comment]
omar2205a@yahoo.com

**Comment by DaoudS** [comment]
daoud.sogoba@gmail.com

**Comment by Tachii** [comment]
zaveruha007@gmail.com

**Comment by CamoSteve** [comment]
I sent my email address via BI forums.

**Comment by Ricciardino** [comment]
petriccarcc@gmail.com

**Comment by jonpas** [comment]
Sent via BI forums.

**Comment by beaar** [comment]
Sent in BI forums PM. Thanks.

**Comment by Jastreb** [comment]
Sent on BI forums.
@kieran-s

**Comment by AiE-Architect** [comment]
eric.wohltman@gmail.com  Thanks!

**Comment by Ligthert** [comment]
sacha@ligthert.net

**Comment by nikolauska** [comment]
nikolauska1@gmail.com

**Comment by oscarmolinadev** [comment]
oscarmolinadev@gmail.com

**Comment by gienkov** [comment]
gienkov.grzegorz@gmail.com

**Comment by TomTucka** [comment]
tomtucka@gmail.com

**Comment by rlex** [comment]
me at lex.io please

**Comment by funar** [comment]
Requested via PM on BI Forums.

**Comment by gibonez** [comment]
naviles516@gmail.com

**Comment by Kllrt** [comment]
kllrtik@gmail.com ;)

**Comment by traumallama** [comment]
markofshame@gmail.com

**Comment by PhoenixSPM** [comment]
ace3chat@pxetech.com

**Comment by nomisum** [comment]
nomisum@gmail.com

**Comment by JonBons** [comment]
Sent via BI forums.

**Comment by LAxemann** [comment]
leon.beilmann@freenet.de

**Comment by meat147** [comment]
Invites sent!
Naviles516 (naviles516@gmail.com)
Kllrtik (kllrtik@gmail.com)
Markofshame (markofshame@gmail.com)
Ace3chat (ace3chat@pxetech.com)
Leon Beilmann (leon.beilmann@freenet.de)
Nomisum (nomisum@gmail.com)

**Comment by robalo** [comment]
Requested via BI forum pm.

**Comment by Cuel** [comment]
alleee@gmail.com

**Comment by kieran-s** [comment]
Sorry bout the delay guys, exams x_x
Will have the BI PM invites sent out soon!

**Comment by Heavygunner96** [comment]
nicoschneider1@gmx.net

**Comment by cptnnick** [comment]
cptnnick@gmail.com

**Comment by simon84** [comment]
Hi Kieran, I sent an PM on BI.

**Comment by iamthesux** [comment]
iamthesux@gmail.com

**Comment by Alex6511** [comment]
Alex6511Echeloned@gmail.com

**Comment by alganthe** [comment]
snurp

**Comment by jArmAhead** [comment]
afuturejarhead@gmail.com

**Comment by brainslush** [comment]
PM sent via BI-Forum

**Comment by Coren4** [comment]
coren4@gmail.com

**Comment by LorenLuke** [comment]
PM sent.

**Comment by Brisse89** [comment]
PM sent on BI forum.

**Comment by Zigomarvin** [comment]
Hi, sent a pm with my email via BI forum, thanks

**Comment by Rickyfox** [comment]
PM sent

**Comment by firefly2442** [comment]
PM sent.  Cheers.

**Comment by Trigger81** [comment]
Trigger@echo12.de

**Comment by R4ppiT** [comment]
Sent pm.

**Comment by FadiCBB** [comment]
rmoran36295@gmail.com

**Comment by Benargeez** [comment]
Email: Benargeez@gmail.com :+1:

**Comment by Dimaslg** [comment]
dimaslg@gmail.com

**Comment by Raspu86** [comment]
Sent pm

**Comment by sarakgaming** [comment]
Sent PM right now ;-)

**Comment by Thraxs** [comment]
PM sent

**Comment by wadiwatir** [comment]
PM sent via BI-Forum as wadiwatir

**Comment by pokertour** [comment]
I sent you a pm on BIS forum :)

**Comment by gibfender** [comment]
I would like to join the Slack channel please

thom.warren@me.com

**Comment by redoper** [comment]
I would like to join too please

davidrychly2@gmail.com

**Comment by TheConen** [comment]
theconen@gmail.com

Thanks in advance :)

**Comment by xPride** [comment]
pride.psy@gmail.com

thx

**Comment by cass944** [comment]
g.cassista@hotmail.ca

**Comment by nonferrousiron** [comment]
PM sent, many thanks

**Comment by Dash92** [comment]
erhardsinoz@gmail.com

Cheers :)

**Comment by SilentSpike** [comment]
SilentSpike100@gmail.com

Thanks

**Comment by jaynus** [comment]
Email invite sent.

**Comment by BlenderRUS** [comment]
sub7blender@gmail.com
Thanks.

**Comment by m32gunner** [comment]
dh6639@nate.com

Super Banana Bomb for ArmA3!

**Comment by Grollig** [comment]
PM send on BI Forums. Thx!

**Comment by gerseun** [comment]
PM on BIS forum

**Comment by seemax1991** [comment]
Gimme dis slack
seemax1991[at]gmail[dot]com

**Comment by codethirteen** [comment]
admin@codethirteen.com

**Comment by ramius86** [comment]
Pm sent on BiS forum

**Comment by Dom4n** [comment]
domanoid@gmail.com

**Comment by pmc-tyler** [comment]
pmc.tyler.v@gmail.com

**Comment by sargken** [comment]
kenny19982009@hotmail.com

**Comment by Grollig** [comment]
admin@stars4ever.de

**Comment by sargken** [comment]
It sent me and email but says email is not registered. kenny19982009@hotmail.com

Thanks

**Comment by SzwedzikPL** [comment]
szwedzikpl@gmail.com

**Comment by TMNFr33d0m** [comment]
salazar@a3milsim.com

**Comment by dharmab** [comment]
dharma.bellamkonda@gmail.com

**Comment by beiita** [comment]
PM sent of BI forums

**Comment by bux578** [comment]
@sargken Slack tells me that you're already registered thus can't invite you again.

**Comment by AbsconditusEminus** [comment]
snip

**Comment by jaynus** [comment]
invite sent

**Comment by hartzie** [comment]
dominik@szalanski.de

**Comment by m1ndgames** [comment]
florian.luettgens@gmail.com

**Comment by Gwynblade** [comment]
Pm sent on BIS forum.

**Comment by Davecatley** [comment]
davecatley@gmail.com

**Comment by SuN9491** [comment]
PM sent.

**Comment by Max255PL** [comment]
Sent PM @ BIF.

**Comment by Fedaykin-Wolf** [comment]
Sent PM

**Comment by SeriouslySerious** [comment]
handelh@gmail.com

**Comment by bux578** [comment]
@Grollig @ramius86 @beiita @Gwynblade @SuN9491 @Max255PL @Fedaykin-Wolf 

Please, resend your email addresses to http://forums.bistudio.com/member.php?102995-bux578

**Comment by vitaminderkach** [comment]
snip

**Comment by alef** [comment]
alefor@gmail.com

**Comment by HeinzMcDurgen** [comment]
pm sent

**Comment by Codingboy** [comment]
poke

**Comment by havena** [comment]
silveredenis@gmail.com

**Comment by voiperr** [comment]
PM sent.

**Comment by DevinGn** [comment]
Devingn@gmail.com
Thank you kindly!

**Comment by QuickDagger** [comment]
Hi Kieran, I sent an PM on BI.

**Comment by Scorch052** [comment]
misterhipster052@gmail.com

**Comment by alanford123** [comment]
ad.asd@mail.com

**Comment by Poulern** [comment]
Poulern@gmail.com

**Comment by KRDucky** [comment]
iancomings@gmail.com

**Comment by erikalm** [comment]
theechocode@gmail.com

**Comment by WALancer** [comment]
walancer@hotmail.com

**Comment by ShuraDE** [comment]
shura@gruppe-adler.de

**Comment by IRONXBAY** [comment]
la1jones@hotmail.com

**Comment by mistergoodson** [comment]
PM sent via BI forums.

**Comment by p1nga** [comment]
pastor399@gmail.com

**Comment by alduric** [comment]
alduric@o2.pl

/Thank you.

**Comment by ToasterBR** [comment]
jonathan.pereira@gmail.com

Thanks!

**Comment by Collumbus** [comment]
Thanks!

**Comment by Collumbus** [comment]
snip

Thanks!

[Done /bux]

**Comment by TDC-Insane** [comment]
send address via BIS forums

Thank you!

**Comment by Daishiknyte** [comment]
daishiknyte@gmail.com

Thanks y'all.

**Comment by Fusselwurm** [comment]
fusselwurm@gmail.com

thx :)

**Comment by TDC-Insane** [comment]
insane@tdcclan.de

**Comment by JRudy** [comment]
PM sent on BI Forums

**Comment by bux578** [comment]
@JRudy could you resend it please to me: http://forums.bistudio.com/member.php?102995-bux578

**Comment by JRudy** [comment]
Resent

**Comment by mA1N** [comment]
"@mA1NCS Prob. a rare edge case. No problems with #ACE3 on #Linux. Join our chat to discuss this with other Admins"

**Comment by bux578** [comment]
@mA1N please [follow the instructions](https://github.com/acemod/ACE3/issues/429#issue-67560587)

**Comment by mA1N** [comment]
@bux578 I sent u a PM with the same text on BIS.

**Comment by BrosidenTheKing** [comment]
andrbrks@gmail.com

**Comment by TigrisJK** [comment]
Please.

**Comment by HopeJohnson** [comment]
59hopejohnson@gmail.com

**Comment by coolcatks007** [comment]
karan.vir.singh.kvs@gmail.com -- Thank you!

**Comment by paullee18** [comment]
paul_lee_18@hotmail.com

Thanks!

**Comment by Williamson3011** [comment]
Sent you a PM.

Thanks!

**Comment by NummiE** [comment]
noa.kaskinen2@gmail.com

**Comment by MountainRat** [comment]
fubarferment@gmail.com

**Comment by MikeMatrix** [comment]
m.braun92@gmail.com

**Comment by J3aLeiNe** [comment]
Hi,
PM via BI forums

**Comment by headswe** [comment]
headswe92@gmail.com

**Comment by CraneSong** [comment]
songofthecrane@gmail.com

**Comment by Wishbone6061** [comment]
At suggestion of bux578 on the issue tracker.

codenamelackluster@gmail.com

**Comment by LtRyan** [comment]
PM via BI forums

**Comment by BryanBoru** [comment]
PM vis BI forums

**Comment by Yakavetta** [comment]
PM via BI Forums

**Comment by InnovationStudios101** [comment]
PM via BI Forums

**Comment by GitHawk** [comment]
slack@liitiad.de

**Comment by ArcanumSK** [comment]
lubos.len@gmail.com

**Comment by sgtBrowncoat** [comment]
Pm sent

**Comment by ColdEvul** [comment]
andreas.brostrom.ce@gmail.com

**Comment by AJCStriker** [comment]
striker.a@1st-rrf.com

Thanks!

**Comment by KoffeinFlummi** [comment]
### Update

New invites should be obtained using the slack button on [the website](http://ace3mod.com) or just by directly visiting http://slackin.koffeinflummi.de/.

**Comment by narrowsoul** [comment]
Slackin tool isn't working for me, may be broken? Regardless, is someone has a free moment I would like an invite.

**Comment by phumberdroz** [comment]
@narrowsoul I would need your mail adress

**Comment by narrowsoul** [comment]
Fragman001@gmail.com

Thanks!

**Comment by phumberdroz** [comment]
Did it work ? If you want you can snip the mail now.

**Comment by cass944** [comment]
i did put a request on the slack im not shure it worked. 

my adress is g.cassista@hotmail.ca

thanks

**Comment by bux578** [comment]
@cass944 
https://gyazo.com/e61eab92351750b58238a9ec3da0240e

**Comment by captainblaffer** [comment]
captblaffer@gmail.com

ty

**Comment by jonpas** [comment]
@captainblaffer check the first post, you can self-invite, this issue is long closed.

**Comment by captainblaffer** [comment]
Thanks, figured it out
