### ISSUE TITLE
Medical settings through config files

### ISSUE THREAD

**Issue by BillyNovel** [acemod/ACE3#4290]
**Arma 3 Version:** `1.62 Stable` (stable / rc / dev)
**CBA Version:** `3.0.0` (stable / dev + commit hash)
**ACE3 Version:** `3.6.2 Stable` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Trying to fully use ACE without creating dependency on a mission. Medical config via description.ext or even serverconfig.hpp leads to insta deaths, revive (epipen one) not activated, low inconsciousness rate.

**Steps to reproduce:**
- Follow this 3.2 http://ace3mod.com/wiki/framework/settings-framework.html
Enable basic revive and prevent insta deaths in the serverconfig.hpp.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer 

**Placed Modules:**
-  None

**RPT log file:**
- None

**Serverconfig.hpp:**
http://pastebin.com/tMp0vSSf

**Comment by Glowbal** [comment]
Hi @BillyNovel. Thanks for your report.

You are using `class ACE_Settings {` in your server config. This is not necessary. It is only required for the description.ext. If you remove that, you will find that your server config will start working.

Note that all you have to do to get all the settings into your serverconfig is hit the export button and copy past the results directly into your serverconfig, no other manual steps are required.

I will add a note to clarify this in our documentation. 

I will close this ticket, however please feel free to reopen if the above did not resolve your issues.
