### ISSUE TITLE
Medical RPT Error

### ISSUE THREAD

**Issue by tradari** [acemod/ACE3#4293]
**Arma 3 Version:** `Stable` (stable / rc / dev)
**CBA Version:** `2.4.1` (stable / dev + commit hash)
**ACE3 Version:** `3.6.2.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- @RHS 
- @CUP (ALL)
- @16aa Mods

**Description:**
- RPT Error only no issues found while playing
z\ace\addons\medical\data\littergeneric_gloves.p3d: No geometry and no visual shape

**Steps to reproduce:**
-Sorry no clue as was found in RPT over the operation

**Where did the issue occur?**
- Dedicated and error message found in Client RPT

**Placed Modules:**
- ermm 730 items, Global has 16aa pack and can work through him where needed im sure.

**RPT log file:**
- Full log
https://www.dropbox.com/s/ckgt08mp22fmqj6/arma3_2016-08-24_19-41-10.rpt?dl=0

**Comment by PabstMirror** [comment]
I will sometimes see this error with the non binerized dev version.
Could test by trying to open p3d from the depboed PBO.

```
19:43:31 [ACE] (common) WARNING: Setting found but couldn't localize [ace_medical_enableUnsconsiousnessAI] (server has but we don't?)
```
is very odd.

**Comment by tradari** [comment]
I've unpack the medical.pbo and tried to open the littergeneric_gloves.p3d with object builder and it wont open so i would say it is binerized

**Comment by Glowbal** [comment]
`WARNING: Setting found but couldn't localise` happens because of the serverconfig file that is used. Not an issue either way, but should be solved.

Are you maybe loading a packed version instead of binarized?

**Comment by tradari** [comment]
its a binarized version as it crashed object builder when i try to open the p3d file

**Comment by PabstMirror** [comment]
3.7 changed the way litter is created (`simpleObject`)
Let us know if you see the same errors with the new version

**Comment by bux578** [comment]
And reopen the ticket if the issue still persists.
