### ISSUE TITLE
I'm having issues setting up the developing area

### ISSUE THREAD

**Issue by SgtMartijnvs** [acemod/ACE3#4294]
Goodday

Im trying to get the developing erea to work but i don't want to use a p drive. I tried the manual install but it doesn't work for some reason. Can someone help?

kind regards,

Martijn

**Comment by PabstMirror** [comment]
You should be able to just do
```
mklink /D /J "C:\Program Files (x86)\Steam\steamapps\common\Arma 3\z\ace" "V:\ACE3"
```

where v:\ace3 is your git repo location

then launch the game with `@CBA_A3;z\ace;` as the mods

You will not be able to build without a p: drive (making pbos)
but you should be able to run it

**Comment by PabstMirror** [comment]
Let us know if you are still having issues
You can also join us on our public slack channel: http://slackin.ace3mod.com/
