### ISSUE TITLE
Question: scripting integration of ACE3 mine detector 

### ISSUE THREAD

**Issue by Vdauphin** [acemod/ACE3#4296]
Hello,

I am looking to improve the [Hearts and Minds IED](https://github.com/Vdauphin/HeartsAndMinds/issues/184) system by using your ACE3 mine detector . 

Actually, [Hearts and Minds IED](https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/ied/create.sqf)  works by spawning random objects (like wreck car, bags, barrels) and when player is close enough, it detonates a bomb. Player can approach carefully the IED, then interact by using ACE3 interaction and can check if it is an IED. 

Now, I am looking for a way to remove the check interaction and use the ACE3  mine detector . 

How could I make the objects spawning by Hearts and Minds detected by the [detectorloop function](https://github.com/acemod/ACE3/blob/master/addons/minedetector/functions/fnc_detectorLoop.sqf#L46) use by the  ACE3 mine detector  ?

Best regards

**Comment by PabstMirror** [comment]
The detector looks for `ace_minedetector_detectable = 1` on object's configs.
So you could do 
```
class barrel_bomb: barrel {
   ace_minedetector_detectable = 1;
};
```

We could also check a `getVariable` on objects?
You could also attach an actual bomb to the object, which should trigger the detector.

**Comment by Vdauphin** [comment]
I didn't said, IED spawned can be fake or real IED. So if I understood object's configs will not help me :/

> You could also attach an actual bomb to the object, which should trigger the detector.

I thought about it but this will create on more object and add performance issue.

> We could also check a `getVariable` on objects?

A `getvariable` is a nice solution.
