### ISSUE TITLE
Drag/carry on prisoners

### ISSUE THREAD

**Issue by rlex** [acemod/ACE3#430]
...Seems to be available in menu after you took someone (i tried VR entities) as prisoners, however, this won't do anything.

**Comment by rlex** [comment]
Also, tested that with medical module removed.

**Comment by Glowbal** [comment]
Version and rtp please.

**Comment by rlex** [comment]
Version from here: http://www.armaholic.com/page.php?id=28557
Not sure if VR scenario even writes RPT files.

**Comment by Glowbal** [comment]
VR scenario writes RPTs. Make certain you play without the `-nologs` parameter.

For future bug reports, please follow the template described [here](http://acemod.github.io/ACE3/wiki/user/how-to-report-an-issue.html).

**Comment by rlex** [comment]
I'll rewrite that issue and record video as well over the weekend. Please don't close.

**Comment by Glowbal** [comment]
Cannot reproduce.
