### ISSUE TITLE
Self interaction menu!

### ISSUE THREAD

**Issue by Luke1145** [acemod/ACE3#4305]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Ace self interaction menu does not work for myself. Although I can use the interaction menu on others. A red circle just appears and I get no options on myself. I have tried changing the key to multiple different ones but i still have no luck. I have seen other people with this issue on the forums before but their fix was for an older version. This is impacting my mill sim experience any help would be greatly appreciated.  

**Steps to reproduce:**
Launch game. Go into a server with mods attached. Try to use self interaction menu. No luck. Just a red circle.

**Where did the issue occur?**
Self hosted.

**Placed Modules:**
None 

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by PabstMirror** [comment]
Double check you have the most recent ACE and CBA
If you have many other mods, I would recomend trying just CBA and ACE and see if you can get anything working.

Please upload the full rpt, can find it at `%userprofile%\AppData\Local\Arma 3`

**Comment by PabstMirror** [comment]
Lets us know if you are still having issues with this, Please try with the latest ACE and CBA:
https://github.com/acemod/ACE3/releases/latest
https://github.com/CBATeam/CBA_A3/releases/latest
