### ISSUE TITLE
Question: make vehicle act as minedetector

### ISSUE THREAD

**Issue by kwinteng** [acemod/ACE3#4308]
**Arma 3 Version:** latest stable
**CBA Version:** latest stable
**ACE3 Version:** 3.6.2

Is it possible to make a vehicle act as mine (IED) detector?

**Comment by jonpas** [comment]
That is more of a feature request, so feel free to put it down in #3594. But since it's a question I'll tag it as a question, and the answer is currently no. It could be modded for sure, but it's not possible to do at the moment.

**Comment by kwinteng** [comment]
No jonpas it's fine, thank you. i thought it was as easy as adding a config line, thank you anyway
