### ISSUE TITLE
"Check temperature" issues

### ISSUE THREAD

**Issue by rlex** [acemod/ACE3#431]
1) Can be done even with no weapons
2) Will always show two (green) lines even if weapon was not fired at all (even if you have no weapons)

**Comment by commy2** [comment]
Well I assume on an artic map it would be one or zero bars?

**Comment by bux578** [comment]
The bars could aswell display the temperature difference between current environment temperature and weapon temperature.

Thinking about it ... this quite makes sense. IRL you wouldn't touch your weapon and go like "Hey my weapon has a temperature of 22.37°C", would you? It'd rather be "Hey, my weapon feels slightly warm."

Maybe for 3.1.0.

**Comment by esteldunedain** [comment]
IIRC weapon temperatures are already calculated as an offset from ambient temperature, e.g, weapon temperature 0 means ambient temperature.

The two bars are always show for weapon temperature 0. This should probably be changed.

**Comment by rlex** [comment]
Should i split that ticket into two separate?

**Comment by esteldunedain** [comment]
Nah, no need to.

**Comment by esteldunedain** [comment]
Ok, both things are fixed now.
