### ISSUE TITLE
Trivial: Classname header incorrect for Gunbag on the wiki

### ISSUE THREAD

**Issue by kwinteng** [acemod/ACE3#4312]
**ACE3 Version:** `3.6.2` (stable / dev + commit hash)

Trivial issue but for the sake of correctness:

in the wiki classnames (http://ace3mod.com/wiki/missionmaker/class-names.html#grenades)
the gunbags have the title "Grenades" as well, most likely a remnant from copying it from there

**Comment by bux578** [comment]
Thanks @kwinteng for the heads up.
