### ISSUE TITLE
Script error in common\xeh_postInit.sqf

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#4317]
**Arma 3 Version:** 1.62
**CBA Version:** current stable
**ACE3 Version:** dev c4d238300570489b8cd0423cdad6eb4e19074bae

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Running a mission from editor I got the following script error
```
12:06:42 Error in expression <_events_oldUnit", objNull])) then {
INFO("CBA_fnc_addPlayerEventHandler has alre>
12:06:42   Error position: <("CBA_fnc_addPlayerEventHandler has alre>
12:06:42   Error Missing ;
12:06:42 File z\ace\addons\common\XEH_postInit.sqf, line 301
12:06:42 Error in expression <_events_oldUnit", objNull])) then {
INFO("CBA_fnc_addPlayerEventHandler has alre>
12:06:42   Error position: <("CBA_fnc_addPlayerEventHandler has alre>
12:06:42   Error Missing ;
12:06:42 File z\ace\addons\common\XEH_postInit.sqf, line 301
```

**Steps to reproduce:**
- Place a unit in editor
- preview mission

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- http://pastebin.com/RXJsdA5g

**Comment by bux578** [comment]
iirc @PabstMirror added this.

**Comment by jonpas** [comment]
#4271 ?

**Comment by bux578** [comment]
https://github.com/acemod/ACE3/pull/4289

**Comment by jonpas** [comment]
Ah, I see.
