### ISSUE TITLE
ACE3 Interaction Menu Not working Properly/self interaction works fine

### ISSUE THREAD

**Issue by akth3bige** [acemod/ACE3#4322]
**Arma 3 Version:** `1.62` (stable / rc / dev)
**CBA Version:** `3.0.0.160713` (stable / dev + commit hash)
**ACE3 Version:** `3.6.2` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
-@ALiVE
-@Iraqi-Syrian conflict
-@RHS Escalation
@Mission Enhanced Little Bird
@ARC US PACK
@Ares Module
@Community Base Addons
@Cup Terrains
@Cup Terrains Core
@iWar
@Joint Rails 
@Low Grass
@Mission Control Center Sandbox 4 (mcc)
@Personal Arsenal
@RH Acc Pack
@Shacktac mods
@Specialist Military Arms
@TF47 Launchers
@TF47 Launchers RHS Patch
@Tryk's Multi-play Uniforms
@UH-60 A3 pack (EricJ)

**Description:**
Hi. I'm trying to set up my own ALiVE insurgency missions so me and my friends can play on it. I'm a first time so its a bit weird. Anyway, I've had a problem with the interaction menu not working correctly. The red interaction circle thing will show up but it won't go away until I either: open self interaction, hit escape is remove it, or just exit out of the game. !Self Interaction is NOT a problem! Interaction works just fine on other servers. CBA and ACE3 are updated. I am using playwithsix Client (not sync). I have not tested it with my friends as I have still been trying to set up the server. Map is Takistan (Cup Terrains)

**Steps to reproduce:**

**Where did the issue occur?**
- Self Hosted

**Placed Modules:**
- Alive Modules: Civ Placement, AI commander, Data, IED Threat, Civilian Population, Virtual AI, Player Options, c2ISTAR, CQB, AI Skill, Mil Placement. ACE: Advanced medical settings, Zeus settings, Respawn, MAP, Medical settings, Interaction settings

**RPT log file:** 
I do not know which one to grab (and how to grab the server file) 

ALSO: Problem seems almost off and on.. Most noticeable is that when TFAR doesn't load up right away (lets me walk around a little bit before loading it) thats when the problem occurs.

**Comment by jonpas** [comment]
> Lots of other ones, will specify if needed

Yes please.

> I do not know which one to grab (and how to grab the server file) 

Go to `%LOCALAPPDATA%\Arma 3` and grab the one with the correct time stamp of when you started the game.

**Comment by akth3bige** [comment]
ALSO: Problem seems almost off and on.. Most noticeable is that when TFAR doesn't load up right away (lets me walk around a little bit before loading it) thats when the problem occurs.

**Comment by akth3bige** [comment]
AAAAnnd another update: had a friend play with me, and once my interaction was not a problem anymore (stated above) he had the same problem as me. Self interaction worked fine but interaction didn't work.

**Comment by jonpas** [comment]
We need an RPT of when the issue happened to be able to help you.

**Comment by akth3bige** [comment]
RPT [http://pastebin.com/8VJUy1gF](url)

**Comment by gienkov** [comment]
You shouldn't be using @ASDG_JR as it did got integrated into newest CBA_A3.

**Comment by jonpas** [comment]
Please try to reproduce the issue with using only `@CBA_A3 and `@ace` on a newly created mission, as instructed on issue reporting guidelines.

There are so many errors and conflicts in that modset you have running that it makes it impossible to say anything. It is entirely possible one mod is conflicting, or the combination of mods are. I will close this, if you can reproduce only with CBA and ACE3, feel free to reopen the issue.
