### ISSUE TITLE
AI refusing to fast rope

### ISSUE THREAD

**Issue by JANXOL** [acemod/ACE3#4324]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.6.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- RHS 
- USAF
- Achilles

**Description:**
- In Zeus mode i give the AI orders to fast rope (as a waypoint). The helicopter flies at a really slow speed, stopping about 20 meters away from the waypoint and just hovers there. Waypoint is not deleted. If I move it, the heli will fly towards it and stop again. If I take control and manually apporach waypoint, AI in the back will fast rope. It happened both with vanilla units and RHS units.

**Steps to reproduce:**
- Enter Zeus mode
  -Spawn a heli
- Put infantry in the back
- Order them to fast rope

**Where did the issue occur?**
-  Self-Hosted Multiplayer 

**Placed Modules:**
- Medical settings, Advanced ballistics, Ace weather, Ace zeus config

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 160 days without any activity.

**Comment by GodofMonkeys** [comment]
Same with me, but I am in the Eden editor, I gave heli fast rope waypoint, but when I preview, he will not drop any guy on his heli.

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/blob/master/addons/fastroping/functions/fnc_deployAIWaypoint.sqf
```
    _commander doMove _position;
    waitUntil {_vehicle distance2D _position < 50};
```
From what I could tell AI in helicopters aren't always very precise about their move orders.
They seemed to only get within about 90m and then stop.

I'm thinking either give them a move order that overshoots where they need to be
and/or
be more flexible on the max distance.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 160 days without any activity.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
