### ISSUE TITLE
Issue with removing multiple fuel nozzles

### ISSUE THREAD

**Issue by nic547** [acemod/ACE3#4332]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable / dev + commit hash)
**ACE3 Version:** `3.7.0 RC2` (RC)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@bwa3`

**Description:**
Multiple fuel nozzles can be removed at the same time, of which only the last one can be removed. The other can't be removed from the player.

**Steps to reproduce:**
- https://www.youtube.com/watch?v=aaGNMVAtULs

**Where did the issue occur?**
- Singleplayer

**Placed Modules:**
- None

**Comment by jonpas** [comment]
You didn't return the first one back to the truck, which made the second one disappear. From what I see in the video, the only problem is that you can take a second one when already holding one. Am I missing something?

**Comment by nic547** [comment]
nope, thats what i meant, unless you want to support carrying multiple fuel nozzles.

**Comment by jonpas** [comment]
Ah, I just reread, that makes sense yes. Thanks for good the report. :+1:

**Comment by PabstMirror** [comment]
Closed by #4337
