### ISSUE TITLE
Zeus + ACE3 = return to mission selection on linux dedicated server.

### ISSUE THREAD

**Issue by ArtyomFR** [acemod/ACE3#4338]
**Arma 3 Version:** `1.62.137494` (stable)
**CBA Version:** `3.0.0.160713` (stable)
**ACE3 Version:** `3.6.2.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
On the same mission (just a zeus gamemaster add to one), server and modset: 
- CBA + Zeus module = Work
- CBA + ACE = Work
- CBA + ACE + Zeus module = Return to mission selection screen

**Steps to reproduce:**
First download the two missions in Anexe.
Then launch the mission named "TEST.Tanoa", the bug while be reproduce.
PS: The second mission is the same as the first, just zeus module less.

**Where did the issue occur?**
- The bug occur on dedicated Linux server (work fine on local windows client)

**Placed Modules:**
- Zeus GameMaster

**RPT log file:**
Not working, CBA + ACE + ZEUS: 
[rpt.2322[2016-09-05|19h34m].txt](https://github.com/acemod/ACE3/files/455457/rpt.2322.2016-09-05.19h34m.txt)
Working, CBA + ACE: 
[rpt.2322[2016-09-05|19h35m].txt](https://github.com/acemod/ACE3/files/455458/rpt.2322.2016-09-05.19h35m.txt)

**Anexe:**
Not working mission:
[TEST.Tanoa.zip](https://github.com/acemod/ACE3/files/455463/TEST.Tanoa.zip)
Working mission:
[TEST2.Tanoa.zip](https://github.com/acemod/ACE3/files/455464/TEST2.Tanoa.zip)

**Comment by jonpas** [comment]
You are loading RHS and R3F compatibility PBOs without RHS or R3F.

This doesn't seem like a problem of ACE3 or CBA at all, no idea how Zeus factors into that.

**Comment by ArtyomFR** [comment]
Thank to you, the mission work very well now.
I deleted the R3F pbo (we use the RHS one on our current server, but RHS wasn't active during the test).
For the zeus factor, i think zeus must load all class listed in mods, so when he want to load R3F class he crash because they missed.

**Comment by jonpas** [comment]
Glad you resolved it @ArtyomFR! That does make sense, too bad it's the case.
