### ISSUE TITLE
Can't put a prisoner on a boat

### ISSUE THREAD

**Issue by Armilio** [acemod/ACE3#4339]
**Arma 3 Version:** `1.62` stable 
**CBA Version:** `3.0.0` 
**ACE3 Version:** `3.6.2` 

**Mods:**
- `@CBA_A3`
- `@ace`
- @ RHS
- @ TFR

**Description:**
When you tie a prisoner, you can force him to get on board of a car/truck, helicopter, or even in submarine. But when you ask him to go on a boat, he remains foots on the ground. He really hates boats.

**Steps to reproduce:**
- On the editor, place on map a player unit; add ACE_CableTie to his inventory or place a box with ACE_CableTie inside.
- Place a boat.
- Place a IA.
- Start the mission, as you wish
- Use ACE_CableTie to tie the IA unit.
- Escort/move this prisoner/IA near a boat (RHS or vanilla, doesn't matter) and try to make him get on board.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Singleplayer) 

**Placed Modules:**
- None OR various module like ACE medicals, ACE explosive, TFR modules.

**Comment by jonpas** [comment]
Can you please attach an RPT file?

**Comment by commy2** [comment]
what boat?

**Comment by Armilio** [comment]
> what boat?

Sorry, boats. Every boat.


That's the RPT:

**Comment by PabstMirror** [comment]
`ACE_captives_fnc_findEmptyNonFFVCargoSeat` seems to be failing on the little inflatable boat.
Does work on the big minigun speedboat or the civ motorboat.

**Comment by Armilio** [comment]
Oh, i didn't think to the speedboat or the civ boat, sorry, but i'm sure that doesn't work also with the RHIB.
