### ISSUE TITLE
Performance Issues with the interaction menue

### ISSUE THREAD

**Issue by OnkelDisMaster** [acemod/ACE3#434]
Me and a couple others from my clan have noticed, that the FPS drops hard on opening the interaction menu. In my case it went from 65 to 23. Self interaction works flawlessly.

**Comment by esteldunedain** [comment]
The menu is indeed performance hungry; however you should not have such a pronounced impact. Please complete the bug report according to this guidelines:

http://acemod.github.io/ACE3/wiki/user/how-to-report-an-issue.html

A vid of the situation in wich you encountered the issue would be helpfull too.

**Comment by rlex** [comment]
Happened for me one time as well, but i was unable to reproduce it :(

**Comment by OnkelDisMaster** [comment]
It appeared on singleplayer, while interacting with an AI. On a dedicated Server it only appears on greater ammounts of players.

**Comment by Kllrt** [comment]
I'm having same issue in MP. For instance when I had 45FPS, after using interaction it dropped to 24FPS.

**Comment by OnkelDisMaster** [comment]
**Mods:**
* CBA A3
* ACE3
* BWMod
* RHS:Escalation
* IslaDualaA3

**Placed ACE3 Modules:**
None

**Description:**
Like Kllrt and rlex said the FPS drops extremely on opening the interaction menu.

**Steps to reproduce:**
Well, open the interaction menu i guess...

**Where did the issue occur?**
MP/SP

**Comment by esteldunedain** [comment]
I say again:

> The menu is indeed performance hungry; however you should not have such a pronounced impact. Please complete the bug report according to this guidelines:

> http://acemod.github.io/ACE3/wiki/user/how-to-report-an-issue.html

> A vid of the situation in wich you encountered the issue would be helpfull too.

Without a video of when/where this happens, an rpt log, the specs of the computer or something I really have zero relevant information to track this! 

You know, this doesn't happens to everyone nor in every situation.

**Comment by Kllrt** [comment]
I happened to make fast video
https://www.youtube.com/watch?v=XTlXWWN7yr4

**Comment by esteldunedain** [comment]
@Kllrt, could you post your computer specs? This may be a thing of GPU bound FPS vs CPU bounds fps. 

For example, I think I may have a worse GPU and a better CPU than you; my fps go from 34 without the menu to 33 when interactin with two nearby soldiers

**Comment by Kllrt** [comment]
Well I have i5-4670k @ 4GHz and GTX770.

**Comment by evromalarkey** [comment]
I got i5 3570k and GeForce 780 Ti and have the same issue.. during the testing we  also sometimes occur that interaction stop working on people, even after respawn, but that's an another issue

**Comment by esteldunedain** [comment]
Both of those processors are better than mine.

> It happens in MP, haven't tried SP yet.

The interact menu is 100% local. It doesn't have any kind of impact over the network, so performance is independent of SP and MP.

> Here's RPT
> https://gist.github.com/Kllrt/6ff221fea23487dc8bf9

I couldn't find anything relevant on the that log. It is however badly spammed by a lot of other addons, which probably degraded overall performance.

I may generate a more standarized test mission so we can eliminate variables. I'll let you know

**Comment by Kllrt** [comment]
Cool!

**Comment by evromalarkey** [comment]
I really wonder what the hell is 16:37:43 Unknown attribute .1, it's spamming clients on our server like hell o.O Could be mission or addon, but don't know if it's related to these performance issues

**Comment by esteldunedain** [comment]
Many addons are really broken due to the changes on inheritance of 1.42, creating a lot of "Updating base class" error. This leads to potentially inconsistent configs for different players due to load order and consequently all sort of problems.

I don't think this is related to the interact_menu performance, but it will surely give you worse overall performance for sure.

**Comment by bux578** [comment]
> If you've found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using only @cba_a3 and @ACE3 on a newly created mission.

**Comment by esteldunedain** [comment]
I've spent most of the day on and off trying to reproduce this issue. Haven't had any luck yet, either on  SP or MP. The most I've seen is 4~5 less fps for about 0.5s inmediately after opening the menu for the first time (medical actions are computed at that point, and then cached for as long as possible).

I've timed different parts of the algorithm and found no performance bottlenecks, but that is kinda obvious given that I couldn't observe the issue.

I assume you guys are using the unofficial version uploaded to Armaholic, right? The current version has a couple of tiny differences; I wouldn't expect them to have fixed the issue, but TBH I don't know what to think.

Keep your eyes peeled for any scenario in which this can be reproduced reliably. I could maybe provide a special build with additional debug logs to run in such an scenario on the next few days.

Cheers

**Comment by Kllrt** [comment]
>I assume you guys are using the unofficial version uploaded to Armaholic, right?

Evro and I had like half day old build.

**Comment by evromalarkey** [comment]
https://github.com/evromalarkey/ACE3/commit/7b0e7a1efb040f6373d6183108445a6b22a499b7
this was the latest commit on the build we were testing. We will update the build today and keep testing ;)

**Comment by bux578** [comment]
During our test yesterday I had fps dropping from 30fps to 20fps when opening the menu in base.

**Comment by Kllrt** [comment]
Which is pretty noticable drop.

**Comment by esteldunedain** [comment]
@bux578, they've sent me that mission already for testing. I'll do so tonight.

**Comment by bux578** [comment]
:+1:

**Comment by esteldunedain** [comment]
We introduced some fixes today that should significatively reduce the fps drop of the interact_menu. Please give the current master a try and report back.

**Comment by Kllrt** [comment]
Roger that.

**Comment by evromalarkey** [comment]
I tried todays build - https://github.com/acemod/ACE3/commit/bb2383cffd960fb01d7be37448df87706cf5fd60 and the interaction menu is completely broken now, FPS drop is huge and there is no text, only icons. Is this known issue?

**Comment by commy2** [comment]
You probably don't have the `ace_breakLine.dll` in your modfolder installed.

**Comment by PabstMirror** [comment]
make sure you have all the dlls in the folder

ace_advanced_ballistics.dll
ace_breakLine.dll
ace_fcs.dll

if problem persits, please upload an rpt somewhere

**Comment by esteldunedain** [comment]
> You probably don't have the ace_breakLine.dll in your @ace modfolder installed.

That's totally it.

**Comment by evromalarkey** [comment]
I guess that would be it, thanks guys!

**Comment by commy2** [comment]
We should really check all dlls on init or even on the main menu and exit the game with an error message.

**Comment by esteldunedain** [comment]
Yes, we just need to do dummy calls on postInit. If the dll is not found the return value is "", and we could log to the RPT.

**Comment by commy2** [comment]
Each .dll should return a version number when fed with "version" as string. And if it errors out, we close the game.

**Comment by esteldunedain** [comment]
Well, that'd work too.

**Comment by jaynus** [comment]
Add it to common extension library and call it from all RVExyensions

**Comment by commy2** [comment]
I don't speak C++ though.

**Comment by jaynus** [comment]
I'll do it.

**Comment by esteldunedain** [comment]
The fps drop on the interact_menu due to many objects being nearby should be now gone. Some performance impact may remain when many action points are simulataneously visible due to the time it takes to render them, but it should be much lower than it was.
