### ISSUE TITLE
Feature Request:Make Compatible with Exile

### ISSUE THREAD

**Issue by JM-Punisher** [acemod/ACE3#4342]
**Arma 3 Version:** `1.62` (stable / rc / dev)
**CBA Version:** `30.0` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
EXILE
MASSI NATO Rus Weapons
MASSI NATO Rus Vehicle
MASSI USSSCOM Vehicles Mas
EXTENDED BASE BUILDING
RHS: AFRF
RHS: USAF
L3-GPNVG18 PANORAMIC NIGHT VISION
CBA_A3
CUP: Weapons
CUP: Units
CUP: Vehicles

**Description:**
-Looking to make ACE3 compatible Exile Mod

**Where did the issue occur?**
- Dedicated

**Comment by Glowbal** [comment]
Hi @JM-Punisher, we will not add compatability for Exile. If a third party is willing to work on that, we welcome and support it, but we will not work on that ourselves.
