### ISSUE TITLE
Wounds do not stack anymore in advanced medical

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#4345]
**Arma 3 Version:** `1.64` RC
**CBA Version:** `3.0.0`
**ACE3 Version:** `3.7.0` release; commit: f3dc1afdbfc8dc05c6057a5d6806c1a7cc10e6db

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Wounds received in advanced medical do not stack anymore resulting in a massive list.
- http://puu.sh/r1lXx/f8c5244673.jpg

**Steps to reproduce:**
- inflict large amount of damage with advanced medical enabled and check the person.

**Where did the issue occur?**
- SP

**Placed Modules:**
- Medical settings
- Advanced medical settings

**RPT log file:**
- https://gist.github.com/alganthe/602f32524a75e0a24146ff334e37e6b0

**Comment by Glowbal** [comment]
This should be fixed for the 3.7.0 release.
