### ISSUE TITLE
Make tourniquet'd limbs show as a different colour

### ISSUE THREAD

**Issue by Hubok** [acemod/ACE3#4346]
Recently suggested in the medical channel on Slack, asking for a different colour on limbs in interact + medical menu, for easy recognition of tourniquets. This may also allow removing it from the triage card (unless it's actively causing pain) and help clear that up.

**Comment by PabstMirror** [comment]
I do like this, 
in real life you would easily be able to see the tourniquite but we have no way to show in 3d.

I will try to do a quick prototype of what it could look like.

**Comment by PabstMirror** [comment]
Not sure about the icon, but I was thinking of something like this:
![20160905213540_1](https://cloud.githubusercontent.com/assets/9376747/18260164/ce5efd1e-73b0-11e6-8cb2-74cb2a72be67.jpg)

Tourniquets do showup in the log (panel on the left), so i'm not positive if this is necessary.
But it's a fairly easy change.

**Comment by jonpas** [comment]
I thought the entire thing was to show it on the body, especially in medial menu. It does show in the log as well in both cases really, but you always first check the icon or medical menu body UI.

**Comment by esteldunedain** [comment]
:+1:
