### ISSUE TITLE
Static weapons interaction issue

### ISSUE THREAD

**Issue by rlex** [acemod/ACE3#435]
ACE3 Version: 0.0.1-master

**Mods:**
* @cba_a3
* @ace3
* @RHSAFRF
* @RHSUSF

**Placed ACE3 Modules:**
* None

**Description:**
* Interaction menu for turrets is misplaced in many ways and game sometimes crash when using drag/carry functions.

**Steps to reproduce:**
* Go to VR 
* Place XM*** / Titan / etc static weapon
* Try to drag carry. You'll notice misplacement of "interact" menu, as well as issues unlocking it
* Short video: https://www.youtube.com/watch?v=H9SauLYZl4U - i was forced to use Alt+Winkey combo to reach "Release" menu
* Sometimes you can get crash when issuing carry / drag actions...

**Where did the issue occur?**
* VR

**RPT log file:**
* No RPT since it was VR...

**Comment by bux578** [comment]
Video is private. Did you test it in Fullscreen or Windowed?

**Comment by rlex** [comment]
Some screenies, this is mostly noticable with low-profile tripods: imgur.com/a/qUlZj

**Comment by esteldunedain** [comment]
Video is private, so I cannot see it. Should be "unlisted". 

The misplacement is a known issue. It's actually a problem on the 3d models memory points. We'd like to workaround it at some point, but it's not that easy.

You can totally get RPT logs on VR

Crashes we've never had. Without more info they'll be hard to debug.

**Comment by rlex** [comment]
Yea indeed, my fault. Changed video visibility.

**Comment by rlex** [comment]
Fullscreen only.
