### ISSUE TITLE
Disabling realistic names

### ISSUE THREAD

**Issue by railgame1** [acemod/ACE3#4356]
I would like to request the possibility of disabling the realistic vehicle names and weapon names.

**Comment by PabstMirror** [comment]
Ace is modulear and made up of multiple pbos.
To remove this just goto

`@ace\addons\` folder and remove `ace_realisticnames.pbo`

**Comment by jonpas** [comment]
What @PabstMirror said. There is no way to make it togglable in-game, as they are all config changes which can't be changed once the game is running.
