### ISSUE TITLE
Leopard 2 SG front armor is too weak against 120mm and 125mm ap

### ISSUE THREAD

**Issue by OssifragA3** [acemod/ACE3#4357]
**Arma 3 Version:** 1.62 (stable)
**CBA Version:** 3.0.0 (stable)
**ACE3 Version:** 3.6.2 (stable)

**Mods:**
- @CBA_A3
- @ace

**Description:**
- you need 1 hit with 120mm/125mm ap on the armor in front of the drivers hatch to destroy a leopard.
- you need 3 to 5 hits with 120mm/125mm ap on the other tanks front armor to destroy them.

**Steps to reproduce:**
- place tanks in the editor and shoot at the front armor in front of the drivers hatch

**Where did the issue occur?**
-Editor (Singleplayer)

**Comment by BaerMitUmlaut** [comment]
We do not change the armor values, nor does ACE3 currently have a tank armor/damage component. This should be exactly the same in vanilla and is thus a vanilla issue.
