### ISSUE TITLE
Problem with the Interaction menu [Not visible]

### ISSUE THREAD

**Issue by omar2205** [acemod/ACE3#436]
When I try to use the Interaction menu nothing happens, but all the non-menu related feature works.

**Comment by jaynus** [comment]
More detail needed. Have you bound the key? Does it not appear? Do you have the keyboard key its default bound to? Have you changed this?

**Comment by esteldunedain** [comment]
Please complete the bug report according to this guidelines:

http://acemod.github.io/ACE3/wiki/user/how-to-report-an-issue.html

This issue is most probably due to the incorrect version of CBA being used

**Comment by omar2205** [comment]
Sorry forget to add this info
1- I have the latest CBA version
2- Tried changing the keys in the Config>Controls

**Comment by omar2205** [comment]
@cba_a3-1.1.20.150408
