### ISSUE TITLE
Problem with the Interaction menu [Not visible] #2

### ISSUE THREAD

**Issue by omar2205** [acemod/ACE3#437]
Mods:
* @cba_a3 [@cba_a3-1.1.20.150408 rc6]
* @ace3

When I try to open Interaction menu nothing happens, 

tried changing the keys the problem still...

**Comment by esteldunedain** [comment]
Sorry this report is still incomplete; it's missing the rpt log. Please follow 

http://acemod.github.io/ACE3/wiki/user/how-to-report-an-issue.html

to the letter. Otherwise there's really not enough info to find out what's going on!

**Comment by omar2205** [comment]
RPT file
http://pastebin.com/iakz4czU

**Comment by esteldunedain** [comment]
Nope, you need to run Arma 3 without the `-noLogs` parameter; otherwise the log doens't contain anything usefull.

**Comment by omar2205** [comment]
sorry forgot it

**Comment by omar2205** [comment]
rpt file
http://pastebin.com/NqmF98Tc

**Comment by esteldunedain** [comment]
Bingo. The current build of ACE3 requires version 1.42 of Arma 3. You're getting an error in the interact menu because you still have version 1.40.

You need to update arma.

**Comment by omar2205** [comment]
Ok, thanks mate
