### ISSUE TITLE
ACE3 replacement of addEventHandler ["HandleHeal", {}] 

### ISSUE THREAD

**Issue by Vdauphin** [acemod/ACE3#4372]
Hello,

I am currently using the ` addEventHandler ["HandleHeal", {}] ` to track player healing on AI civilian and gives reputation bonus for this good action. ([here is the code](https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/rep/add_eh.sqf#L5))

But now I am using the ACE3 medical on IA so I am looking for the ACE3 EH heal equivalent of the ` addEventHandler ["HandleHeal", {}] `.

I saw something related but I have no clue if it is what I am looking for ... (https://github.com/acemod/ACE3/blob/8f3907c03f1f763cfdacb091474517a12b074b85/tools/cba/addons/xeh/script_xeh.hpp#L33)

Best regards.

**Comment by Glowbal** [comment]
Hi @Vdauphin, we have an event handler available for that. 

Please take a look on our wiki: http://ace3mod.com/wiki/framework/events-framework.html

```sqf
["ace_treatmentSucceded", {
    params ["_caller", "_target", "_selectionName", "_className"];
}] call CBA_fnc_addEventHandler;
```

Where selectionName is the selection, classname is the classname of the ACE treatment action completed.

**Comment by Vdauphin** [comment]
Thanks ! I will take a look.
