### ISSUE TITLE
Adv. stamina does regenerate with game paused

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#4379]
**Arma 3 Version:** `1.62`
**CBA Version:** `3.0.0`
**ACE3 Version:** https://github.com/acemod/ACE3/commit/a9b82513f7de0e53003bad7187a466a36613da9b

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Stamina does regenerate with game paused

**Steps to reproduce:**
- Run for a while in editor to lose some or all of your stamina
- Pause the game with ESC
- Wait for a minute
- Unpause to see most of your stamina regenerated

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- Advanced Stamina

**RPT log file:**
- Will upload if needed

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/blob/master/addons/advanced_fatigue/XEH_postInit.sqf#L39

Per frame handler runs on `tickTime` and not `CBA_missionTime`. Needs some scaling.

**Comment by jonpas** [comment]
... I just got sniped by @commy2 !
