### ISSUE TITLE
Start Button Tabbing out. (WINDOWS 8)

### ISSUE THREAD

**Issue by 1tim64** [acemod/ACE3#438]
The start button for windows 8 tabs you out of the game, will there be an option to customize your controls?

**Comment by omar2205** [comment]
Config>Controls>configure Addons 
and change what cause you a problem

**Comment by jonpas** [comment]
There already is, using CBA's keybind system. Go to Options -> Controls -> Configure Addons.

**Comment by esteldunedain** [comment]
That's not an issue with ACE. You can change that behaviour in windows IIRC.

**Comment by 1tim64** [comment]
Thanks.
