### ISSUE TITLE
Advanced Ballistics cuts FPS in half

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#4386]
**Arma 3 Version:** `1.62`
**CBA Version:** `3.0.0`
**ACE3 Version:** `3.6.2`

**Mods:**
- `@CBA_A3`
- `@ace`
- '@CUP_Terrains'

**Description:**
- Having Adv. Bal. module enabled will cut your FPS in half even when not shooting.

**Steps to reproduce:**
- Place simple NATO rifleman on map
- Run preview and check your FPS

![](http://i.imgur.com/UHqlsbR.jpg)

- Place Adv. Bal. module and enable it
- Run preview and check your FPS and observe how low is it now

![](http://i.imgur.com/DgxzttT.jpg)

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- Advanced Ballistics

**RPT log file:**
- Nothing related inside

**Comment by commy2** [comment]
RPT

**Comment by gienkov** [comment]
http://pastebin.com/K25Asn5X

**Comment by commy2** [comment]
Cannot confirm.

!<http://i.imgur.com/ULr6qPa.jpg>

!<http://i.imgur.com/FhH44CO.jpg>

**Comment by gienkov** [comment]
Are you sure you've enabled it inside the module? It's off by default.

**Comment by commy2** [comment]
Yes. Set every bar to "enabled"

**Comment by gienkov** [comment]
Can you try it on one of CUP maps?

**Comment by gienkov** [comment]
Altis also works for me:

- OFF: 50 FPS
- ON: 35-40 FPS

**Comment by gienkov** [comment]
And CUP Takistan:

- OFF: 43 FPS
- ON: 30 FPS

**Comment by commy2** [comment]
I don't have CUP and can't DL a pack that size atm.

**Comment by gienkov** [comment]
Try it on Altis and closer to populated area.

**Comment by commy2** [comment]
![http://i.imgur.com/kZqL059.jpg](http://i.imgur.com/kZqL059.jpg)

![http://i.imgur.com/lYzikNV.png](http://i.imgur.com/lYzikNV.png)

![http://i.imgur.com/Fod7Ikk.jpg](http://i.imgur.com/Fod7Ikk.jpg)

I guess it's to be expected that it drains frames. That's why you can turn it off.

**Comment by PabstMirror** [comment]
AB has a terrain processor that runs at the beginning of a mission.
It's semi-expensive so it only does a bit each frame and can take some time to complete.

Chenarus has 95481 cells and it will do 50 each frame.
At 60 fps that will take 30 seconds to finish, 30 fps would take a full minute.

Altis has 379456 and could take you 2-3 minutes to finish!
Once a map is cached, it will not have to be redone if the same map is played again.

You can watch progress on this by watching variable `ace_advanced_ballistics_currentGrid`
If it's stable at 0, then the map has already been cached, otherwise you should see it climing over time until it finishes and stops.

Once it finished your FPS should return to normal
AB actually has zero code / PFEH running except when bullets are being fired.

**Comment by esteldunedain** [comment]
@PabstMirror is exactly right. That loop basically computes the roughness of the terrain, which takes into account buildings; terrain roughness then affects the variation of wind velocity with height. As buildings can technically be added in the editor, the roughness is always recomputed on mission start.

I guess there're a few of thing that could be done to mitigate this, although I'm not sure if they are worth it:
- Store the result in the profile namespace, and reuse.
- Compute less cells per frame (would take longer to complete)
- Couple both ideas above; load the last roughness from profile namespace and very slowly recompute it to account for editor placed buildings. Additionally, I think it would probably be possible to only recompute cells which have manually placed buildings.

**Comment by PabstMirror** [comment]
I am worried about writing megabytes of data to profileNamespace.
We could drop the compute rate, but I also think it's good to just get it over with as fast as possible.

I have a PR to add additional logging. But I think this can be closed for now.

@gienkov - Please let it sit on the map for a min or two and let us know if your fps doesn't stabilize back to normal.

**Comment by gienkov** [comment]
Yes FPS came back after about 2 minutes, didn't knew about that background computing.

**Comment by jonpas** [comment]
Awesome, this can be closed then. Another thing we could add to the documentation though.
