### ISSUE TITLE
Not able to fully uninstall ace mod

### ISSUE THREAD

**Issue by LittleCoach** [acemod/ACE3#4389]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.
When I delete the mod folder the Arma 3 game will give me an error that it cannot find folder. I don't want to use the mod at this time but I cannot use the game. 
**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
Deleted mod folder
Load game
Gives prompt that cannot find ace folder
**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.
None
**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by Glowbal** [comment]
Please provide some kind of explaination on why you cannot uninstall ACE and how you installed it. (it is as simple as deleting the `@ace` directory that came from installing ace).

I'm going to close this due to lack of information. Please feel free to reopen if you have more information so we can help you.
