### ISSUE TITLE
DMS Scope displayName not set

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#439]
ACE3 Version: Pre-3.0.0 4f5e63de7286912f40b250307815dcf8c533cd8d

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
`ACE_optic_DMS`'s `displayName` is set to `"LOCALIZE ACE DMS"` instead of a string from stringtable.

**Steps to reproduce:**
* /

**Where did the issue occur?**
/

**RPT log file:**
/

Can issue pull request if it was already decided what the actual name should be.

**Comment by jonpas** [comment]
I can fix it, just let me know what the full name should be. :)

**Comment by commy2** [comment]
It's actually just a test object I forgot to remove from the ammo box (scope = private)

**Comment by jonpas** [comment]
:+1: 

It's good to see all of you working again, it was getting lonely on AGM repo!

**Comment by esteldunedain** [comment]
:heart:

**Comment by commy2** [comment]
:banana:
