### ISSUE TITLE
ACE3 Bandage Values

### ISSUE THREAD

**Issue by narrowsoul** [acemod/ACE3#4392]
In the current state of advanced medical, the bandages do not make very much sense and don't seem to have any basis in reality. 

As I understand it, currently the system can be powergamed by only carrying elastic and basic bandages. Elastic closes basically all wounds really well, and basic prevents reopening. For starters, that's backwards, as in real life elastic bandages are pretty useless for hemorrhage control and are primarily used to secure other bandages or help stabilize fractures. 

My suggestions are as follows:

Quickclot should be the pinnacle of hemorrhage control for puncture/velocity wounds, as that's the precise function of quickclot. In previous iterations packing bandages have seemed to be better, while those would really only be to add extra filling to very large velocity wounds or avulsions. Quickclot is the only bandage with chitosan to accelerate clotting, so it doesn't make sense for anything else to be better for stopping bleeding in puncture and velocity wounds. _edit: After looking at the actual values, I was stunned to see Quickclot is by far the worst dressing for puncture and velocity wounds, which doesn't make any sense at all._

Elastic bandages should have very poor values for stopping any sort of bleeding, and great values for stopping reopening. To emulate reality, you should be able to teach players to bandage a wound with whatever appropriate bandage, and then apply an elastic bandage on top to secure the dressings. 

This is based on my training and 3.5 years of service as a US Army medic, so while I may be corrected by a flight medic or doctor, I am confident in my assessment.

**Comment by narrowsoul** [comment]
Here's my preliminary approach to what some more accurate values might be. Those more familiar with the ACE3 code (as I'm not familiar with it at all) may be able to offer some better insight, but this setup fixes some of the parts that are flat wrong with the current values. 

https://drive.google.com/open?id=0B3qy6tOzwzmZQ3h0dEtDempENU0

**Comment by commy2** [comment]
The time you took drawing the table, you could've spend entering the values into the actual config.
E.g. https://github.com/acemod/ACE3/pull/4367

**Comment by alganthe** [comment]
@commy2  the table is a copy of mine I use for the wiki, it has auto-coloring.
https://docs.google.com/spreadsheets/d/12cK9USqQIaM3MtfxxyzXc3uxCghCZSJssJcKyvNyXBQ/edit#gid=0

**Comment by narrowsoul** [comment]
@commy2 Thanks for the example, I will consult some more with a couple of medics I know and submit a PR. I must have overlooked that one, I searched a bit before submitting this issue.

**Comment by narrowsoul** [comment]
Closing issue, I've submitted a pull request for new values and gotten with Glowbal about the necessary changes to implement this system.

**Comment by bux578** [comment]
#4402
