### ISSUE TITLE
Question: optional-folder

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#4399]
in your optional folder, there are two pbo's, which i don't know what their functions are.

these are 
ace_noactionmenu
and 
ace_particles

**Comment by jonpas** [comment]
> ace_noactionmenu
https://github.com/acemod/ACE3/blob/master/optionals/noactionmenu/README.md

> ace_particles
https://github.com/acemod/ACE3/blob/master/optionals/particles/README.md
