### ISSUE TITLE
Overhaul Bandaging system

### ISSUE THREAD

**Issue by ghost** [acemod/ACE3#4400]
Request a change to the code in the current medical code so that the reopening chance is applied by the last bandage applied, rather than the last bandage used to close a wound.

This would be useful for using different bandages to "secure" dressings used to close wounds.

**Comment by sargken** [comment]
Then you could add in medical tape if such a thing.

**Comment by narrowsoul** [comment]
That would be awesome, but I didn't want to ask too much of the guys actually writing code and creating objects.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
