### ISSUE TITLE
Issues of blowing off turret effect to Merkava and T100

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#4404]
**Arma 3 Version:** `1.62` (stable )
**CBA Version:** `3.x.x` ( 3.0.0.160713 stable)
**ACE3 Version:** `ace3_3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Hey ACE guys! In the ACE 3.7.0, you have added new effects new effects of death for tanks. Yes, It's very cool!  It makes a maximal cool impression at the first times, but the more you play with it, the more isues, which prevents to enjoy with this effect fully.

Here's issues, what I noticed:
- There is no any randomization, for this death effect. All tanks have the same probability of 100 %. 
  Each tank will have these effects. Please try add randomization. When you explode a few tanks in a row, the effect similar to a mirror. Unfortunately it does not look realistic. Not all tanks should have the same effect death. You can deprive some tanks of such effects, or add other effects.
- When the tank-turret flies up into the air, in the fall it makes no any sound. 
  It does not look good, because the object is very large. Definitely, It should have a noticeable sound.
  Pleace try add any sound at falling.
- After falling to the ground, the tower sometimes has no realistic physics. Sometimes it just sticks to the ground in a completely non-realistic position or even can hangs above the ground surface in the void.  Please try improve this all, if possible.
- After falling to the ground, the tower has no physical impact on the vehicles and units. All soldiers or vehicles can pass through this tank-tower. Please note, in this case any player can to use the cheating if he hide self inside this tower.  Inside the this object such player, will be invisible to enemies and can shoot from there with impunity.  May be it is possible to use Collision Model to the falling tank turret?Any object must have a collision with the fallen turret and should to walk/drive around him.

I hope that these details can be polished.  Because, as seems to me, after all the every great work consists primarily of the fine details. ACE team Thanks for your awesome job!

**Steps to reproduce:**
Place in the map enemy tank and you as Missile Specialist (AT)
Shoot in the enemy tank and observe for effects

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- No required

**Comment by commy2** [comment]
2,3,4 don't seem feasible to me.
There are no impact sounds (impact on the ground) in the Arma sound engine. The model we use probably have no Fire Geometry LODs (what you call "Collision Model") and we can't modify the models, because they are protected intellectual property of Bohemia.

**Comment by ZeusWrath** [comment]
2,3,4 - very sad.  
In the point 2,  I can only assume that the sound can be added not to the falling turret but to the destroyed tank itself. Because the turret falls near the tank. This can be looks good.

And about collision.  If you would have your own model (not BI Model), then it is possible for her to make Collision ability or not?
Also,  I noticed that the sound of the flame from the turret very loud at big distances. I think it needs reducing.

**Comment by Glowbal** [comment]
1 is addressed for 3.8 and part of the cook off enhancements

**Comment by ZeusWrath** [comment]
Thanks.  
Some time before, when play in Arma,  I was surprised.  I as a player was able to climb on top of the fallen Merkava turret!  But before that, I definitely saw, how the player passes through the fallen turret of T100! Probably Collision Model still works, but it is not stable!? Or may be problem appears only at T100?
