### ISSUE TITLE
Crash when bandaging while carrying no weapons

### ISSUE THREAD

**Issue by alef** [acemod/ACE3#441]
ACE3 Version: 5ff1d9863d921b284428363aca6a27356c88e61a

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
* As by title
* It doesn't happen with triage, it did happen with morphine

**Steps to reproduce:**
* Create a VR mission with player as medic and another unit front of you
* Play as medic
* Kill the other unit
* Drop any weapon you have
* Bandage the patient
* Game CTD

**Steps to reproduce (2):**
* Drop any weapon you have
* Try bandage yourself

**Where did the issue occur?**
* SP

**RPT log file:**
http://pastebin.com/riJJt6kf with debug on modules plus medical enabled

**Comment by PabstMirror** [comment]
Reproduced, will take a look.

**Comment by Glowbal** [comment]
Did the crash happen after the progress bar was completed or before it appeared?

**Comment by alef** [comment]
It happens before I could see the bar.

**Comment by PabstMirror** [comment]
```
12:06:03 Do anim B Alpha 1-1:1 (Pabst Mirror) = AinvPknlMstpSlayWnonDnon_medic @<null>
```

One of the last things to happen is that it tries to play this animation.
But just doing `player playMove "AinvPknlMstpSlayWnonDnon_medic "` doesn't crash.

**Comment by commy2** [comment]
Whats with the space?

**Comment by PabstMirror** [comment]
Mistake in comments, in-game the animation played fine.

**Comment by commy2** [comment]
What line is that animation called?

**Comment by jaynus** [comment]
Could it be due to multiple animations in a PFH or something similiar?

**Comment by commy2** [comment]
Doubt it. Thats should work without issue. My guess would be an animChanged EH that triggers a script that uses switchMove and loops. Dunno if any animChanged or similar are used though.

**Comment by Glowbal** [comment]
These are the relevant lines for the animation code upon treatment: https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatment.sqf#L157-L173 

One issue I see here is that we are first parsing the animation string for the non weapon check, followed by the assignment of a fake weapon. This should be switched around. May not be the source of the issue however, but I will investigate more.

**Comment by Glowbal** [comment]
Reproduced. Appears to be related to `ACE_FakePrimaryWeapon`. 

Also reproducable for me through the following steps:
* Drop all weapons
* In debug console, execute: ```player addWeapon "ACE_FakePrimaryWeapon";```

**Comment by PabstMirror** [comment]
Fixing the model, seems to have fixed the problem.

**Comment by jonpas** [comment]
FYI, same thing broke AGM dragging, if anyone wants a fix, it's on my fork: jonpas/AGM@b61c1eabc2c94bc7bcd9a4f3b511ac48afefebdc

**Comment by commy2** [comment]
Known. AGM is no longer supported though.

**Comment by jonpas** [comment]
Yep I know, but ACE3 is not out yet either, so if anyone needs a fix there it is.
