### ISSUE TITLE
Cook off effect selections not defined correctly for RHS tanks

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#4412]
**Arma 3 Version:** `1.64` (RC)
**CBA Version:** `v3.0.0.160713` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHS Escalation`

**Description:**
- Cookoff effect is produced on only one hatch of Abrams tanks (RHS).

**Steps to reproduce:**
- Shot in ammo storage in abrams from RHS (M1A1 SA, didnt ckecked other vehicles yet)

**Where did the issue occur?**
- SP

**Comment by vlad8011** [comment]
But it is not RHS feature...

**Comment by commy2** [comment]
Cook off locations can be specified via config. Example:
https://github.com/acemod/ACE3/blob/master/addons/cookoff/CfgVehicles.hpp#L28

It's not our task to get compatibility with every addon though. I don't have RHS on my hard disk drive, so I won't search for the right selection or model space coordinates

**Comment by SilentSpike** [comment]
Cook off is looking at `QGVAR(cookoffSelections)` in the vehicle config to find the positions to use for these effects. Defaulting to `[0,-2,0]` if not defined. So it's a compatibility issue, if you find the appropriate positions you can submit a PR to add them to the respective RHS compatibility pbo.

(Ninja'd by commy while writing)

**Comment by vlad8011** [comment]
Ah, out of my skills, but thanks.

**Comment by sargken** [comment]
I can look into it, I don't know if i can find the proper selections.

**Comment by commy2** [comment]
might help:
https://community.bistudio.com/wiki/selectionNames

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Comment by johnb432** [comment]
I was not able to find the selection for the blowout panels - I don't think there is any.
