### ISSUE TITLE
FIX to low limb damage, explosives and cookoff

### ISSUE THREAD

**Issue by DLEGION** [acemod/ACE3#4414]
Hi all !    this is not an issue, a wish to help!

i wish to share with you my fixes for some problems/bugs that still afflict ACE3 (updated to 3.7.0)
i'm trying to be useful, hehe  :)

PROBLEM 1:  18 6.5mm shots to arms and legs and and soldier still not unconscious.
topic about issue is here:      https://github.com/acemod/ACE3/issues/3302
video about issue is here:     https://www.youtube.com/watch?v=EdGXU5PTXRg
FIX here in video description:  https://www.youtube.com/watch?v=LSdVwRQ5Grw
now a soldier hit by a bullet will realistically fall unconscious (not dead) in pain. 

PROBLEM 2:   Leopard tank from AAF faction cannot be killed by Comanche's DAGR missiles (shoot 24 of them) or by AG missiles from kajman CSAT helo (shoot 8 of them), or by kajman AP rounds (shoot the whole reserve).
topic about issue here :   https://github.com/acemod/ACE3/issues/4405
FIX here :                        http://www.mediafire.com/download/obylbzfiew3jqp3/ace_cookoff.pbo
now the leopard get properly killed by AG, DAGR,Titan AT missile and AP rounds from kajman helo. 

PROBLEM 3:   personally i didnt like the idea that explosive charge like M112 or a shaped charge like SLAM , when well place (and ONLY when well placed) could not incapacitate a tank. may be a personal taste, so take it only if you agree with this thought.
topic about issue here : https://github.com/acemod/ACE3/issues/3834
FIX here:                      http://www.mediafire.com/download/9eyft0nibwiwgdb/ace_explosives.pbo
now a really good placed charge (both M112 and SLAM) can kill a tank, just few inches in wrong place and tank will just be damaged.

i catch this occasion to point your attention to a problem ( a serious one in my opinion) :
this is the third time i post an issue, that get ignored or blamed as BI fault in few seconds whithout check, or postponed every patch to next milestone.
the strange thing is that a guy like me, with no knowledge of the code and often just bychanging some numbers, can fix them in few hours of try&test.
i'm 100% sure you can do 10 times better in a fraction of that time, but seems you like more to add new features instead fix old (often gamebreaking) ones.

anyway thanks for your awesome ACE3 mod (whithout it ARMA3 is just another game!) and for your continuous effort to get it better !
hopes this fixes help someone else in my situation!
bye !

**Comment by commy2** [comment]
Why do you keep creating duplicate issues? This will not speed up the fix for them. All you do is piss off the developers which makes it less likely that they actually take a look at your problems.

**Comment by DLEGION** [comment]
No wait....you are right about duplications, but this is not a duplicate ! Its a fix compilation for some troubles !

**Comment by DLEGION** [comment]
Its an everyone problem, and i dont want piss off anyone. Just mark it as "not an issue " or "fix " and let people who need it an easy way to find it. I just try to help.

**Comment by bux578** [comment]
@DLEGION This is not a forum.

**Comment by Glowbal** [comment]
@DLEGION could you please submit your suggested fixes as pull requests (one for each fix preferably). This will help us by getting a solution faster, as we will not have to manually download a pbo and look for any potential changes and figure out the what and the why.

Thanks in advance.
