### ISSUE TITLE
Prevents vehicles from exploding (3.7.0 feature) creating some problems of gameplay.

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#4416]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
 Hi guys! In patch 3.7.0 has been added to the prevent of explosions for light vehicles, when hit with armor-piercing bullets.  At least @commy2 reports about it here: https://github.com/acemod/ACE3/pull/4116

As it turned out, this feature has a negative impact.  At least I have a two not small problems for gameplay:
1. After this, some of missions have stopped working, because they had the task to destroy the vehicles by means tanks. Triggers completed the tasks of this missions only if the given vehicles of the enemy destroyed. In this cases the Tanks shoots at the UAV Stomper or Armored Fennek, which belong to the enemy, but are unable to destroy them even after 20-30 hits! For this reason, the triggers of mission completion don't work, because the vehicle the enemy can't be fully destroyed.
2. The AI perceives destroyed (but not exploded) of the vehicle as the still active enemy units and for this reason continues to shoot at the already destroyed vehicles, until run out of ammunition! At least from tank-HMG. It looks not good and spends the ammunition of the AI.

Please return the ability to the vehicles explode when hit with armor-piercing bullets.
The explosion may be after multiple hits, but in the end, such vehicle should be exploded,
This will save the game from at least two of the above problems.

**Steps to reproduce:**
Create a trigger that will be responsible for the destruction of enemy MRAPs. And use the several allied tanks against it. After destroying vehicle, triggers will not work, because vehicle can not be exploded and fully destroyed. Also the AI will continue to attack enemy vehicle from HMG, which did not explode.

**Where did the issue occur?**
 Editor (Singleplayer) 

**Placed Modules:**
 None

**RPT log file:**
Not required

**Comment by commy2** [comment]
>For this reason, the triggers of mission completion don't work, because the vehicle the enemy can't be fully destroyed.

Shoot it with an HE round. There will always be conflicts with missions if you change anything in the game.  I don't see how we could get around that. Disable cookoff if it doesn't work for your mission.

>The AI perceives destroyed (but not exploded) of the vehicle as the still active enemy units and for this reason continues to shoot at the already destroyed vehicles, until run out of ammunition! At least from tank-HMG. It looks not good and spends the ammunition of the AI.

The AI will leave the damaged vehicle and even if players are inside, they will die to the AP rounds. Once the vehicle is abandoned, the AI will no longer shoot it as it belongs to the civilian side.

**Comment by ZeusWrath** [comment]
> Shoot it with an HE round
Yes, I can do it, but my subordinate AI (or other allied tanks) will never be able to do it! 
Thus the influence of the all alied units will not have impact on the mission.

> Disable cookoff if it doesn't work for your mission.
As I understand I should remove only one - ace_cookoff.pbo ?

> The AI will leave the damaged vehicle and even if players are inside, they will die to the AP rounds. Once the vehicle is abandoned, the AI will no longer shoot it as it belongs to the civilian side.

But what happens when it comes to UAVs!? You can use the test. The AI will shoot in the such "destroyed" vehicle infinitely.  As I said above, it drains ammo allied tanks and besides, it looks not good.

**Comment by ZeusWrath** [comment]
Hey guys! what do you think guys?  this should to be fixed? 
 https://www.youtube.com/watch?v=sW7xs-gOGjI&feature=youtu.be 

As seems to me, yes. AI continues attack vehicle,  which has been already destroyed. 
In the game, attack-icon ot this vehicle is red. All ai-units reports about this vehicle, as about active enemy unit. The any vehicle should be be exploded, sooner or later, regardless of the weapons being used against him.  If it will be attacked later. If it doesn't explode even after 10 and more hits from a tank main cannon, then it does not look realistic.  If you don't want explode destroyed vehicle after one -two hits of AT- shells, then you can make the explosion after subsequent hits. This feature will save the game from many of the troubles described above and the same player will not see, what we see on my video example. This is not good.

**Comment by commy2** [comment]
Looks fine to me.

**Comment by ZeusWrath** [comment]
useless and endless shooting like you? I can't argue with you you are the master of mod...

**Comment by ZeusWrath** [comment]
Please tell me how I can remove this without other features ? 
 (car engine can ignite, blowing off the effect of the tower Merkava and T100, secondary explosions) This all - super features! only this (unexplosive vehicles) feature seems to me bad

**Comment by commy2** [comment]
You cannot turn them off individually.

**Comment by ZeusWrath** [comment]
Then, it's a pain in my ass .  It's a spoon of tar in my barrel of honey(

**Comment by commy2** [comment]
No worries. I'll fix it. I'm just messing with you.

**Comment by ZeusWrath** [comment]
hahahahahahaaaaaa! Super newS!

**Comment by ZeusWrath** [comment]
> No worries. I'll fix it. I'm just messing with you.

@commy2 probably you forgot fix it. In the 3.8.0 still not fixed

**Comment by jonpas** [comment]
As you can see this issue is tagged for 3.9.0, it has not been fixed in 3.8.0 and we know it, no one "forgot" about it, it was simply not done yet. :)

**Comment by nomisum** [comment]
excited to see this tackled with the upcoming setDamage param `object setDamage [damage, useEffects]` :D should make noplosions great again.
