### ISSUE TITLE
Spawn with weapon in gunbag

### ISSUE THREAD

**Issue by Backblast** [acemod/ACE3#4417]
Quick question. Is there a code one can place in a unit init or config that means on loading in they already have a weapon in their gunbag? Want to create a sniper unit loadout that begins with carbine in hand, and rifle in the gunbag, rather than spawning with rifle and empty gunbag, and have to manually put it in and pick up carbine.

**Comment by PabstMirror** [comment]
We don't have any offical api, and things might change internally in the future
but I think something like this should work for now:

```
player addBackpack "ace_gunbag";
private _gunbag = backpackContainer player; // This is the backpack object
_gunbag setVariable ["ace_gunbag_gunbagWeapon", ["srifle_EBR_F", ["","","optic_SOS",""], []], true];
```
