### ISSUE TITLE
Ambient Sounds not working

### ISSUE THREAD

**Issue by Iceman1991** [acemod/ACE3#4418]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- How do i get the Ambient Sounds working? 

**Placed Modules:**
- Ambient Sounds

**Comment by Glowbal** [comment]
Hi @Iceman1991, what are the issues you are having with ambient sounds?

**Comment by Iceman1991** [comment]
the description says, that i have to write in the sound classes i want to play during the mission. Problem is that i can write in whatever i want, but no sound is played. I believe that these sounds where in the game without placing any modules before - but now i dont get any ambient sounds sadly

**Comment by Glowbal** [comment]
Hi @Iceman1991,

you have to provide a comma seperated list of classnames from CfgSounds classes.

**Comment by Iceman1991** [comment]
hi @Glowbal,

thank you. do you have any examples? the classnames i wrote in the module dont work.

**Comment by commy2** [comment]
I can't get it to work either. Last change was 3 months ago though.

Btw, next Arma version will have something similar build in:
https://community.bistudio.com/wiki/getAllEnvSoundControllers

**Comment by Glowbal** [comment]
I will take a closer look.
