### ISSUE TITLE
Bandage requirement is abnornal [Medical Basic]

### ISSUE THREAD

**Issue by S1m31** [acemod/ACE3#4419]
**Arma 3 Version:** `1.62.137494` (stable)
**CBA Version:** `3.0.0.160713` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- In order to bandage a yellow injury to white the system requires 4 bandages, if the injury is red require minimum 10 bandages to white. This is a crazy number of bandages to put on the injured man.

**Where did the issue occur?**
- server dedicate d multiplayer

**Placed Modules:**
- file ace module 
  ![ace module report 18sep16](https://cloud.githubusercontent.com/assets/22255802/18608033/2587ffe2-7cde-11e6-82af-862c98eb8f43.jpg)

**RPT log file:**
- not avail

**Comment by Glowbal** [comment]
Could you please provide me with an rpt log file? We will look at this for our next release.

**Comment by S1m31** [comment]
I attach the rpt file. It is new but the error still persist
[arma3server1_2016-09-17_14-20-44.rpt.txt](https://github.com/acemod/ACE3/files/478143/arma3server1_2016-09-17_14-20-44.rpt.txt)

**Comment by RaiderSpectre** [comment]
I tested this bug with S1m31, and if we were only us two in the server, then bandage requirements seemed to work correctly (2 bandags to heal from red to yellow, and another two from yellow to white); but in a mission with 15 players, bandage need increased to 4-5 unit to heals from red to yellow and another 4-5 to heal from yellow to white.

TEST only 2 in the server: https://www.youtube.com/watch?v=tbJX0F1VpcE

**Comment by 654wak654** [comment]
Can also recreate the bug.

**Comment by RaiderSpectre** [comment]
any chance to resolve this bug? it still persist (it's 5 months now)

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 163 days without any activity.
