### ISSUE TITLE
Missile guidance and seeker script error

### ISSUE THREAD

**Issue by brainslush** [acemod/ACE3#4420]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHSUSF`
- `x\tss_units\addons\tss_units`

**Description:**
- Script error appears when launching a missile with ACE3 missile guidance from a helicopter with a mounted laser. Does only occur if laser is activated. 

**Steps to reproduce:**
- Add missile guidance config entry to the missile config of a helicopter (MELB AH-6 H) which I have taken from the documentation
```
        manualControl = 0;
        class ace_missileguidance {
            enabled = 1; // Enable missile guidance (0-disabled, 1-enabled)

            minDeflection = 0.00025;  // Minimum flap deflection for guidance
            maxDeflection = 0.001;  // Maximum flap deflection for guidance
            incDeflection = 0.0005;  // The increment in which deflection adjusts

            canVanillaLock = 0;  // Enable vanilla lock, only applicable to non-cadet modes, 'recruit' always uses vanilla locking (0-disabled, 1-enabled)

            defaultSeekerType = "SALH";  // Default seeker type
            seekerTypes[] = {"SALH"};  // Seeker types available

            defaultSeekerLockMode = "LOBL";  // Default seeker lock mode
            seekerLockModes[] = {"LOAL", "LOBL"};  // Seeker lock modes available

            seekerAngle = 90;  // Angle in front of the missile which can be searched
            seekerAccuracy = 1;  // Seeker accuracy multiplier

            seekerMinRange = 1;  // Minimum range from the missile which the seeker can visually search
            seekerMaxRange = 2500;  // Maximum from the missile which the seeker can visually search

            defaultAttackProfile = "LIN";  // Default attack profile
            attackProfiles[] = {"LIN", "DIR", "MID", "HI"};  // Attack profiles available
        };
    };
``` 
- Place Helicopter, Run Mission, Be gunner of the helicopter
- Enable mounted laser
- Launch missile (doesn't matter if you lock on or not)
- Script errors appear

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
[gist](https://gist.github.com/brainslush/783775e8230dba03425b6d0b2b06eae8)

**Comment by Glowbal** [comment]
Could be the result of our recent clean up in laser and/or missileguidance?

**Comment by PabstMirror** [comment]
I can try to take a closer look,
but I think the problem is that laser doesn't support vehicle based laser designators right now

**Comment by brainslush** [comment]
according to the comment here you might be right
[https://github.com/acemod/ACE3/blob/master/addons/laser/functions/fnc_vanillaLaserSeekerHandler.sqf](url)

**Comment by PabstMirror** [comment]
I'm going to try to take a deep look at laser

**Comment by brainslush** [comment]
Is testing needed?
