### ISSUE TITLE
Advanced fatigue - bar is not hiding when getting into vehicles.

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#4424]
**Arma 3 Version:** `3.64` RC
**CBA Version:** `v3.0.0.160713` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHS`

**Description:**
- After getting into vehicle, stamina bar keeps uncovered, and in wrong place - HUD element with weapon info is moving into the right when getting in vehicle, beacuse its covering state indicator (useless when inside car), but stamina bar (from ace) is staying in same place, where it was before we went into car.

**Steps to reproduce:**
- Turn ON advanced fatigue, spawn yourself next to some vehicle, observe stamina bar, while getting into vehicle. 

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- Advanced Fatigue

**Comment by BaerMitUmlaut** [comment]
How does vanilla behave compared to this?

**Comment by commy2** [comment]
the bar goes away since the whole control is replaced with the one from the vehicle. that does only happen for driver and gunner slots though. cargo still uses the infantry weapon info box.

I guess it can get misalligned if you set different positions for these two controls in the ui editor.
