### ISSUE TITLE
Dead Man's Switch Bug

### ISSUE THREAD

**Issue by CamoSteve** [acemod/ACE3#443]
ACE3 Version: 3.x.x

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
* For a brief description of the problem, There is bug regarding the Dead Man's switch when attached to a demolition charge. When attached, the self-interaction menu is unable to move.

**Steps to reproduce:**
* The steps needed to reproduce the bug is shown in the video. 
https://www.youtube.com/watch?v=bwDs4YlonlU

**Where did the issue occur?**
* Singleplayer

**RPT log file:**
* http://pastebin.com/B4E9kvAg

**Comment by Tachii** [comment]
it's not RPT log file.
You can find the actual RPT here:

Drive:\Users\YourUsername\AppData\Local\Arma 3

**Comment by PabstMirror** [comment]
I think this was fixed with #26d282c224dc98ba1c018bdc943b1c9942ef4117

**Comment by esteldunedain** [comment]
Yes

**Comment by CamoSteve** [comment]
Good to know it was fixed :)
