### ISSUE TITLE
Parachute cargo drop broken

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#4437]
**Arma 3 Version:** `1.62.137494` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
-can't parachute ammoboxes from the blackfish
 **Steps to reproduce:**
- place blackfish, small-ammobox, Player on map. load a box into blackfish via ace-interaction-menu. fly and drop the box via ace-interaction-menu. the box ejects parachute opens and then detaches from the box and the box falls to the ground to be destroyed.

**Where did the issue occur?**
- Editor (Singleplayer) 

**Placed Modules:**
- 'None' 

**RPT log file:**
- http://pastebin.com/LC42VDz2

**Comment by commy2** [comment]
Is this issue specific to the Blackfish?

**Comment by madpat3** [comment]
haven't noticed it to any other.

**Comment by madpat3** [comment]
by the way, storage room should be bigger for the vehicle Version and the infantrie Version. unless you haven't loaded a vehicle or infantry. it should depend on how much vehicles/passengers are inside the blackfish.

**Comment by commy2** [comment]
very difficult to do. you'd have to prevent units from entering later. I wanted to avoid that can of worms

**Comment by madpat3** [comment]
then leave the "box of Pandora" closed and just fix the issue of the parachute-thing

**Comment by commy2** [comment]
fml. I cannot debug it because I don't own Apex

**Comment by commy2** [comment]
ok. ´selectPlayer cursorTarget` to the rescue.
this is odd. maybe the parachute collides with the plane and dies?

**Comment by dvdbrewster** [comment]
This  Happens with UH 60 ghosthawk as well.

**Comment by commy2** [comment]
Issue happens to all helicopters, because the problem is not with any specific helicopter...

**Comment by austinjames314** [comment]
Tested in dedicated MP server. Working like a charm.
