### ISSUE TITLE
ACE3 Unable to run without internet dll error.

### ISSUE THREAD

**Issue by Ivanonpc22** [acemod/ACE3#4438]
Version:
Arma 3 Stable
ACE3 3.7.0 Latest
CBA 3.0.0 Latest

Mods:
CBA_A3
ACE3

When I run the Ace mod offline and play a mission it gives me "ace_advanced_ballistics.dll" not installed along with the other .dll's in the ace mod. If I run it online it works perfectly. If you can make it playable offline that would be great.

I cant play any mission or on my own LAN server without disabling Ace.

Tested with and without ace modules to check if that was the issue and it is not.

*FIX* Disable Battleye in the Arma 3 launcher, thanks commy2 for the comment.

**Comment by commy2** [comment]
Are you using Battle Eye? The Battle Eye Servers were having problems.

**Comment by Ivanonpc22** [comment]
Works with battleye disabled thanks for letting me know that is the one thing I forgot to try.

**Comment by commy2** [comment]
np, yw
