### ISSUE TITLE
Enable wind deflection (and advanced ballistics) for vehicle mounted weapons

### ISSUE THREAD

**Issue by ulteq** [acemod/ACE3#446]
Vehicles don't have a firedBIS event handler assigned.

**Comment by esteldunedain** [comment]
This will probably be best covered by https://github.com/acemod/ACE3/pull/350

But it's probably better to leave that for after 3.0.0. Maybe this issue should be postponed too.

**Comment by ulteq** [comment]
Obsolete, as of: https://github.com/acemod/ACE3/commit/d8b461db913a3ef596f5ce22a07374a0a766da8b
