### ISSUE TITLE
clientside cheating problem

### ISSUE THREAD

**Issue by DLEGION** [acemod/ACE3#4468]
**Arma 3 Version:** `1.64` stable
**CBA Version:** `3.0.0` stable 
**ACE3 Version:** `3.7.0` stable 

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
hi there.
here's the trouble:  on my dedicated server, with my "modded" version (for example: damage system, explosives values ecc...) everything seem to work fine. i mean bots and vehicles use the "modded values".

BUT...when a player with "unedited" default 3.7.0  join the server, the "modded values" seems to auto-revert to default 3.7.0, despite server has the "modded values" version !  
to be specific: 
the player with "modded" 3.7.0 will shoot other players and bots with "unedited" values
the player with "unedited" 3.7.0 shoot bots with "unedited" damage values, but shoot the "modded" player with modded values!!
its a huge problem, prone to cheating. i dont understand why its not the server ruling on players, but instead are the players forcing theyr own "clientside" (editable) values !!
if possible please explain how fix this, thanks!
PS: i disabled the medical system in ACE_settings.hpp  ...but dont seems to work !
please, how get vanilla ARMA3 damage ? 

**Steps to reproduce:**
edit something huge, like a demolition charge damage and range.
 join a dedicated server, notice your "modded values" being applied instead of the default ones. 

**Where did the issue occur?**
- Dedicated server

**Placed Modules:**
-none

**Comment by PabstMirror** [comment]
Server's only broadcast ace_settings
Code is not synced.
If server and clients are running different code/configs anything can happen.

Distribute your modifed pbos to all clients
Turn on key checking in server.cfg
```
verifySignatures = 2;
```

**Comment by DLEGION** [comment]
Ahh thanks for the explanation ! Now makes a bit of sense 😁 !
I will probably be forced to use your solution...anyway to better understand : if i set in medical ACE_settings.hpp "0" to "off / basic / advanced " it should disable the medical system, right ? I just wish to get the vanilla damage, is possible somehow ?
Huge thanks anyway !

**Comment by DLEGION** [comment]
The medical system seems off...but the damage its still the same (ace one, not vanilla ) 😞😞😞.

**Comment by PabstMirror** [comment]
ace_medical does several config changes and setting level to 0 is not supported at this time.

To get vanilla medical handling back, you need to remove ace_medical.pbo

**Comment by DLEGION** [comment]
Ah.. Ok...but removing it will screw compatibility anyway, right ? 
Well, huge thanks for your help man ! At least now i got a clear idea ! 😀 
Thx again, Bye !
