### ISSUE TITLE
Feature Request.: Add delay, status-bar at change positions inside vehicles (gunner,driver,commander) and at geting/exit

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#4471]
Hi guys! Exuse me, if I created the "request ticket" in the not right place.  But I have not found where this can be done more correctly.

In the vanilla Arma and in the ACE3 also, the player can get inside a tank or any armored vehicle, within 0.1 second.  The player can also change your position inside (gunner, driver, commander) within a less of one second! This feature always annoyed me, because this makes the simulation of Arma (inside armored) is far not good. 
I think, if in these cases, you will try add the status bar on the background of black screen and add sound of human movement, it would be much better and more realistic for the gameplay ACE3. 
For example to change the position of the driver --> gunner, the player should be spent - 5 sec. and change the position of the driver --> the commander may take already 7-8 seconds.
Such items can affect gameplay, and make this more realistic.
Any soldier should spend some time on the movement inside the tank, on the getting and also on the leaving the tank in emergency situations. This actions should take some time.  
**In this cases, the small delay for AI-units and status bar for player, would be a significant breakthrough for realism in the ACE mod.**

Thanks, I hope this idea will be implemented sooner or later.

**Comment by commy2** [comment]
Hello,
I personally would like to see this too, altough I have no idea how one would implement something like this atm.

Feature requests go here: https://github.com/acemod/ACE3/issues/3594

I'll close this ticket, but a link to it has already been automatically generated in our dedicated feautre request ticket.

**Comment by ZeusWrath** [comment]
thank you
