### ISSUE TITLE
Rain cannot be turned OFF

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#4472]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.0.0.160713` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- In EDEN rain cannot be turned off, even with manual overrrideing.

**Steps to reproduce:**
- Launch EDEN, set weather to cloudy (>70%), try to turn off the rain.

**Where did the issue occur?**
- EDEN, SP

**Placed Modules:**
- ace_weather

**Comment by commy2** [comment]
Does the same happen in vanilla? `setRain` command seems to do nothing in 1.64

**Comment by vlad8011** [comment]
need to check out but in RC it was possible, and steam didnt download anything since RC finished.

**Comment by vlad8011** [comment]
Vanilla works OK

**Comment by gienkov** [comment]
AFAIK overcast >49% will always spawn rain that cannot be turned off.

**Comment by vlad8011** [comment]
I checked it and it turns OFF everytime without problem.

**Comment by bux578** [comment]
@vlad8011 please make a screenshot of the settings in the ace_weather module.

**Comment by vlad8011** [comment]
Sorry for misunderstanding - i was using ace_weather.pbo, not module.

**Comment by bux578** [comment]
If you didn't change any default settings using the module, ACE will pick up the custom weather data for the map and will synch it every X seconds.
Turning off the rain with a command might not be enough to actually overwrite the rain synch loop in ace_weather (https://github.com/acemod/ACE3/blob/master/addons/weather/functions/fnc_updateAceWeather.sqf)
Probably a race condition you're experiencing here.

This could be wrong, but you might try this instead of `setRain `
```sqf
// ACE_RAIN_PARAMS = [_lastRain, GVAR(current_rain), _transitionTime];
ACE_RAIN_PARAMS = [0, 0, 1];
publicVariable "ACE_RAIN_PARAMS";
```

**Comment by vlad8011** [comment]
So i cant turn it off in weather settings (EDEN)?

**Comment by bux578** [comment]
>it

what do you mean by `it`?

**Comment by vlad8011** [comment]
rain

**Comment by bux578** [comment]
https://github.com/acemod/ACE3/issues/4472#issuecomment-250170387

**Comment by TheGrandVizier** [comment]
Yea, as far as i can tell, this has always been the case in vanilla.
Once overcast is above 70%, Rain is out of the users control.

**Comment by commy2** [comment]
So is this a ACE thing or not? I've heard different things now.

**Comment by vlad8011** [comment]
I have succesfully switched rain in vanilla, since RC 1.64, with ace i cannot do this.

**Comment by commy2** [comment]
And if you delete `ace_weather.pbo` it works again, @vlad8011 ?

**Comment by vlad8011** [comment]
Yes.

**Comment by esteldunedain** [comment]
Sorry, the discussion on this ticket is going in circles. Unless I'm mistaken, this is how ace_weather works:

1 - By default, ACE overrides the weather you define in the editor and simulates it's own, based on real world data assigned to the map. In this mode, whatever you set will be overriden.

2 - This can be turned off with settings, modules, etc. (`GVAR(useACEWeather) = 0`). Even if that is turned off, ACE will still sync server weather by default to clients. So whatever is set in the server will be forced on all clients (including rain, wind, fog, rainbows, lightnings, temperature, etc). On this mode `setRain` only works on the server, and the result is synced to all clients.

3 - This behaviour can also be turned off (`GVAR(enableServerController) = 0`, `GVAR(syncRain) = 0`, etc). When that is turned off, weather reverts to vanilla, and hence `setRain` should work without a hitch on any client.

**Comment by esteldunedain** [comment]
BTW, `Ace_weather` settings are a bit of a mess currently. We should probably fix them when switching to CBA.

Some settings combinations don't make sense. In particular `GVAR(enableServerController)` is unnecessary and should probably be killed with fire.

If `GVAR(enableServerController) = 0`, the server doesn't send any data, but clients still try to sync rain if `GVAR(syncRain) = 1`. Under this condition all clients will force the rain they had at the beginning of the mission.

**Comment by commy2** [comment]
Can we hijack Zeus to somehow make it work again?

**Comment by esteldunedain** [comment]
> make it work again?

What do you mean? I don't see any bug; behaviour seems perfectly reasonable to me.

**Comment by commy2** [comment]
Zeus has weather sliders. Ideally these should overwrite the servers values if `GVAR(useACEWeather) = 0`
And they should be disabed if `GVAR(useACEWeather) = 1`

**Comment by esteldunedain** [comment]
> Zeus has weather sliders. Ideally these should overwrite the servers values if GVAR(useACEWeather) = 0
And they should be disabed if GVAR(useACEWeather) = 1

I don't know how they work. If they set weather on the server or globally then they should already work when `GVAR(useACEWeather) = 0`. IDK if it's feasable to disable them when `GVAR(useACEWeather) = 1`

**Comment by Jaaxxxxon** [comment]
...works fine as long as you disable the ace_weather setting in the module, as that overrides the editor settings.
Can post screenshots of the settings I have for it working if needed.

**Comment by vlad8011** [comment]
If you can.... That would be usefull.

**Comment by Jaaxxxxon** [comment]
http://imgur.com/a/9mpZP

**Comment by vlad8011** [comment]
So thats nothing new, but thanks. Its just what i descibed.

**Comment by bux578** [comment]
@vlad8011 Then it's not an error but how ace_weather works.

**Comment by vlad8011** [comment]
Yes, that comes to an end.
