### ISSUE TITLE
Advanced Fatigue - Diving to the ground from a full sprint uses 20% - 60% of all stamina

### ISSUE THREAD

**Issue by Bummeri** [acemod/ACE3#4481]
**Arma 3 Version:** `1.64` stable
**CBA Version:** `3.0.0` stable
**ACE3 Version:** `3.7.0` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Your stamina wastes away in huge gulps as you dive prone to ground. The range of stamina loss is quite large. Most of the time you only lose 20%, but sometimes you can lose huge amounts like 60% at a time. The huge losses appear rarely and seem to perhaps be linked to doing a second dive soon after the first one.

**Steps to reproduce:**
Regardles of your gear weight or if you have a rifle on hand or not, do the following:
- Start full sprint and run for a few seconds
- Press z to dive to the ground
- Stop prone on the ground and watch your stamina plummet.

**Where did the issue occur?**
- Dedicated/ Editor (Singleplayer)

**Placed Modules:**
- None

**Comment by BaerMitUmlaut** [comment]
The issue is the animation. It accellerates the player to a stupid high speed for whatever reason. Not sure if we can do something about that, I'll take a look again.

**Comment by esteldunedain** [comment]
> The issue is the animation. It accellerates the player to a stupid high speed for whatever reason. Not sure if we can do something about that, I'll take a look again.

I guess it would be possible to add a check in the stamina code that reduces the stamina cost for that particular animation name. Or more generally (in case more anomalous anims exist), add a correction coefficient in config for all animations with a typical value of 1, but a lower value for that one.

**Comment by PabstMirror** [comment]
I bet it's using prone's big value for `GVAR(animDuty)` with the momentum from the run.

We might just want to add a max value for `_currentWork`

**Comment by BaerMitUmlaut** [comment]
A max value is a bad idea imo. There is a max speed value of 5m/s to filter similar stupidities, but I think an animation specific duty value might be best here.

**Comment by esteldunedain** [comment]
> I think an animation specific duty might be best here.

Rethinking my comment above, it'd probably be more compatible to formulate the config entry so a value of zero (or no entry) defaults to `GVAR(animDuty)`; that way it's less likely to run into any compat problem with mods adding new anims, etc. 

Maybe something like:

```sqf
private _duty = GVAR(animDuty) * (1.0 + _animCoef);
```

**Comment by commy2** [comment]
The issue is that the diving animation is recorded as prone stance (because stance switches instantaneously) while preserving the running speed. It's like you are super crawling.

**Comment by commy2** [comment]
Can't repro 60%, but it eats 20% for sure.

**Comment by Bummeri** [comment]
Losing more than 20% happens rarely. I cannot reliably repro it. However, I am able to see it happen a few times with maybe 10 minute testing. I will try and find a way to do it reliably.
