### ISSUE TITLE
Feature Request: Captive/Prisoner position on screen when moving

### ISSUE THREAD

**Issue by TGxhermano** [acemod/ACE3#4482]
**Arma 3 Version:** `1.64` 
**CBA Version:** `3.0.0`
**ACE3 Version:** `3.6.2` 

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- This is a feature request. When moving a captive/prisoner it's difficult to see, what you are walking into. The captive/prisoner is blocking most of the screen. It would be great to be able to move him on your left or right side. Also, when you are crouching/laying down the capitve/prisoner should do the same to prevent him from getting shot.

**Comment by jonpas** [comment]
As you said, this is a feature request and should go to #3594.

**Comment by TGxhermano** [comment]
Sorry, totally new here. Will do!
