### ISSUE TITLE
Captive/Prisoner position on screen when moving

### ISSUE THREAD

**Issue by TGxhermano** [acemod/ACE3#4483]
**Arma 3 Version:** `1.64.x`
**CBA Version:** `3.0.0`
**ACE3 Version:** `3.6.2` 

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
When moving a captive/prisoner it's difficult to see, what you are walking into. The captive/prisoner is blocking most of the screen. It would be great to be able to move him on your left or right side. Also, when you are crouching/laying down the capitve/prisoner should do the same to prevent him from getting shot.

**Comment by commy2** [comment]
#3594
