### ISSUE TITLE
with the latest cba-version

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#4493]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.0` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- since cba introducing jr for pistol-muzzles, only ace's muzzle-attachments work for the pistols(muzzleflash)

**Steps to reproduce:**
- put virtual-arsenalbox in your sp-editor and get p99 in your Hands. the only attachment for your muzzle is the flashhider from ace3, for it should also be the 9mm-silencer from vanilla.

**Where did the issue occur?**
- Singleplayer

**Placed Modules:**
- None

**RPT log file:**
not needed

**Comment by PabstMirror** [comment]
Fixed via #4208

Until ACE 3.8 is released I think the pistols and some of the 6.5mm weapons won't work with ace attachments.
