### ISSUE TITLE
RHS: USAF AH-64D Zeroing not working correctly with ACE

### ISSUE THREAD

**Issue by DoomDutch** [acemod/ACE3#4495]
**Arma 3 Version:** `1.64`
**CBA Version:** `3.1.0`
**ACE3 Version:** `3.7.0`

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHS: United States Forces` v0.4.1.1

**Description:**
- I have found out that the ACE targeting system interferes with the regular Arma 3/RHS zeroing system in such a way, that it will be impossible to get any accurate shots.
One of the way ACE intervenes, is through the UI for the zeroing. (Normally found on the top right of the UI) Whenever one uses 'tab' button to change zeroing or the manual page-up and down, the UI doesn't change to the correct number (i.e. it stays at the default position of 400m for the Apache) This, while the actual zeroing does change. 
Moreover, this messes with the AUTO-zero feature the Apache has when locking onto something. (Like your own laser) The AUTO-zero doesn't compensate for the ACE zeroing, thus making your gun 'inaccurate' and shoot short or over.

As of now, I do not know if the same problem occurs with other, similar, vehicles.

**Steps to reproduce:**
-Enable RHS USAF, ACE3 and CBA3 for Arma 3
-Use any RHS Apache helicopter and get into the gunner seat.
-Use the 'tab' button or the page up and down to use the ACE zeroing mechanism.
-See how the UI for the zeroing doesn't change.
-Test it also with AUTO-zeroing.

**Where did the issue occur?**
- Editor (Singleplayer) / Multiplayer

**Placed Modules:**
RHS: USAF AH-64D, any variant

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by jonpas** [comment]
Are you running the compatibility PBO for RHS-ACE3?

And please upload RPT.

**Comment by DoomDutch** [comment]
@jonpas 
The compatibility PBO for RHS-ACE3 on Armaholic is currently outdated, so no.

I do not know how to find the information for the RPT.

**Comment by jonpas** [comment]
Try the compatibility PBOs from ACE3 `optionals` folder included in the release package.

Read the end of your issue post and you'll see, the issue template includes the link on how to find the RPT. ;)

**Comment by PabstMirror** [comment]
`class RHS_AH64_base: Heli_Attack_01_base_F`

So it inherits the Comanche's FCS turret configs.
Should we disable FCS or fix the AH64's configs to make it work with FCS (`discreteDistance` stuff)?

**Comment by commy2** [comment]
Bad/lazy config on RHS side. The Apache is not a Comanche (Blackfoot).

Also, seems like another heli does this: http://class.rhsmods.org/rhsusaf/CfgVehicles_Heli_Attack_01_base_F.html

**Comment by DoomDutch** [comment]
@commy2 I've already put this issue at RHS, put they referred me to ACE... http://feedback.rhsmods.org/view.php?id=2695
@jonpas Which files from the _optionals_ folder should be put in the @ACE3 RHS compatibility files/addons folder? (The rhs_afrf3.pbo and rhs_usf3.pbo files?)

**Comment by commy2** [comment]
reyhard is wrong. We are not responsible for compatibility PBOs. RHS team will not do support on their own, so we are hosting these files out of courtesy. We don't actively update them though.

**Comment by jonpas** [comment]
> The rhs_afrf3.pbo and rhs_usf3.pbo files

afrf3 for Russian forces and usf3 for US forces, depends which you use, or both.

**Comment by DoomDutch** [comment]
@jonpas The PBO Does not fix the problem, unfortunately.

**Comment by cych** [comment]
Any way to bring back the ACE 2 features for AH64/AH1z (from RHS) ?


- Laser designator ON/OFF via mouse menu with auto lock (no need to press tab)
- Auto ranging system for the M230
- HUD symbology from ACE 2 (crosshair when lasering, lock-on ststus, TOF, 
- MFD for Hellfire trajectory selection, and laser code
- Autoairflow system when engine is damaged, turned OFF.
- ACE_SM (cannon sound, engine sound, hellfire sound)

and so on....


Where can I find back that features package ?  is it ACE team dependant or RHS dependant ?
