### ISSUE TITLE
Medical blood spurts issue

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#4498]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.0` (stable)
**ACE3 Version:** `3.7.0` (ddd036f5bd1468f1b3353687ac2403bf4702996f)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- On a very high damage blood spurts spawn incorrectly. http://i.imgur.com/XOImayF.jpg
https://github.com/acemod/ACE3/blob/master/addons/medical_blood/functions/fnc_spurt.sqf#L27
https://github.com/acemod/ACE3/blob/master/addons/medical_blood/functions/fnc_spurt.sqf#L32

**Steps to reproduce:**
- Pretty random to reproduce but use something high caliber and aim for the head.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None,

**RPT log file:**
- N/A.

**Comment by commy2** [comment]
I think the maximum damage handleDamage will report is 4. Maybe it's the same for `hit` (which is where the `_damage` value comes from) ?
MAXIMUM_DROPS is 4. So that would be 4 x 4 = 16 drops.

**Comment by commy2** [comment]
fixed in #4064
