### ISSUE TITLE
Inappropriate setting for the RHS BTR/M113 armor.

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#4500]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.0` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHSAFRF`
- `@RHSUSF`
- `@RHSGREF`

**Description:**
- BTR-80/M113 explodes due AP shells and lit with a torch. On vanilla RHS, AP shells do not explode APCs.

**Steps to reproduce:**
- Shoot any BTR using any BMP in editor or a mission. 

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / 

**Placed Modules:**
- 'None'

**Comment by Glowbal** [comment]
This sounds like either an issue with RHS or an issue with the compatability pbo.

This issue needs investigation and a confirmation. If this is a compatability issue, we are accepting PRs from the community to address it.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 167 days without any activity.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
