### ISSUE TITLE
Ships dont have speedlimiter

### ISSUE THREAD

**Issue by Ghost77788** [acemod/ACE3#4501]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.0.0` (stable )
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Seeing as boats have throttles i would like to see the implementation of speedlimiter to boats.
In addition lowering the minimum speed capable because boats have greater speed control.

**Steps to improve:**
from file XEH_postinit.sqf in the ace_vehicle.pbo
Starting at Line 17.
        // Conditions: canInteract
        if !([ACE_player, objNull, ["isnotinside"]] call EFUNC(common,canInteractWith)) exitWith {false};
        // Conditions: specific
        if !(ACE_player == driver vehicle ACE_player &&
        {vehicle ACE_player isKindOf 'Car' ||
            {vehicle ACE_player isKindOf 'Tank'} ||
            **_{vehicle ACE_player isKindOf 'Ship'}_**}) exitWith {false};

            GVAR(isUAV) = false;
        // Statement
        [ACE_player, vehicle ACE_player] call FUNC(speedLimiter);
        true
    };

And from file fnc_speedlimiter.sqf in the ace_vehicle.pbo
Starting at LINE 31.

private _maxSpeed = speed _vehicle max 10;  
_**if (_vehicle isKindOf "Ship") then {_maxSpeed = speed _vehicle max 5;};**_

**Where did the issue occur?** 
No Error

**Placed Modules:** 
None

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by commy2** [comment]
#3594
