### ISSUE TITLE
Frags and armored vehicles

### ISSUE THREAD

**Issue by lolkij** [acemod/ACE3#4504]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.0` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHS` (optional)

**Description:**
- Incorrect work of the fragmentation system with armored vehicles, basically APC. When you throw a grenade on the roof of vehicle - frags start the expansion not on the surface of the armor, but slightly below.  And some of the fragments passes through the armor and killing the crew.
  Tested on vanilla and RHS armored vehicles.

Few screenshots with tracers of the frags:
http://i.imgur.com/7zLnbQh.jpg
http://i.imgur.com/AmT6SmD.jpg
http://i.imgur.com/xnpP3Me.jpg

**Steps to reproduce:**
- Place any APC in the editor with crew.
- Throw a grenade (or shoot 40mm grenade) on the roof of the APC.
- If the throw is successful, the frags will kill the crew.

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- None.

**Comment by Glowbal** [comment]
We will need someone to confirm this issue. 

If this is still an issue, we are accepting PRs to fix this.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 160 days without any activity.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
