### ISSUE TITLE
Error on RPT : Error in expression <QUOTE([ARR_2(_player,'RED')] call DFUNC(joinT>

### ISSUE THREAD

**Issue by Alexandre-S** [acemod/ACE3#4510]
**Arma 3 Version:**  `1.64.138497` (stable)
**CBA Version:** `3.0.0.160713` (stable)
**ACE3 Version:** `3.7.0.6` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- RPT logs got spammed with an error i can't fix

**Steps to reproduce:**
- Launch a mission on server, join as client

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
- http://pastebin.com/yap6RanP

**Comment by commy2** [comment]
Please upload the _full_ RPT file.

**Comment by Alexandre-S** [comment]
Sure, there you go : http://pastebin.com/Qq7ypjXQ

**Comment by PabstMirror** [comment]
Is this from an official release or a custom built one?
The line is 
```
statement = QUOTE([ARR_2(_player,'RED')] call DFUNC(joinTeam));
```
Our build has the correct de-macroed: 
```
statement = "[_player,'RED'] call ace_interaction_fnc_joinTeam";
```

**Comment by commy2** [comment]
Looks like someone copy pasted the uncompiled code into a mission script without #include'ing the header file.

**Comment by Alexandre-S** [comment]
Official release, i've downloaded it from https://github.com/acemod/ACE3 

Here is the code with macroed functions 

https://github.com/acemod/ACE3/blob/master/addons/interaction/CfgVehicles.hpp

**Comment by Alexandre-S** [comment]
@commy2 what should i do then ?

**Comment by commy2** [comment]
Find the function that does it and remove it.

**Comment by bux578** [comment]
@Alexandre-S Did you download it from the repo or from the release page?
https://github.com/acemod/ACE3/releases

**Comment by Alexandre-S** [comment]
@bux578 release page. I just re download it, and extract ace3_3.7.0.zip

If i open then ace_interaction.pbo and open CfgVehicles.hpp, i have statement = QUOTE([ARR_2(_player,'RED')] call DFUNC(joinTeam));, not statement = "[_player,'RED'] call ace_interaction_fnc_joinTeam";

**Comment by Alexandre-S** [comment]
@commy2 could you please elaborate ? :)

**Comment by PabstMirror** [comment]
The hpp's don't get touched, but config.cpp from a depboed release will have the de-macro'ed code.

**Comment by commy2** [comment]
First of all you should try to reproduce it with only CBA and ACE enabled and on an empty mission (as described in how-to-report-an-issue).

**Comment by PabstMirror** [comment]
Config.cpp example:
```
				class ACE_TeamManagement
				{
					displayName = "$STR_ace_interaction_TeamManagement";
					condition = "[_player,_target] call ace_interaction_fnc_canJoinTeam&& {ace_interaction_EnableTeamManagement}";
					statement = "";
					showDisabled = 0;
					priority = 3.2;
					icon = "\z\ace\addons\interaction\UI\team\team_management_ca.paa";
					class ACE_AssignTeamRed
					{
						displayName = "$STR_ace_interaction_AssignTeamRed";
						condition = "[_player,_target] call ace_interaction_fnc_canJoinTeam";
						statement = "[_target,'RED'] call ace_interaction_fnc_joinTeam";
						showDisabled = 1;
						icon = "\z\ace\addons\interaction\UI\team\team_red_ca.paa";
						priority = 2.4;
					};
```

**Comment by Alexandre-S** [comment]
@PabstMirror Indeed, got this in config.cpp
http://i.imgur.com/L0EMcf4.png

@commy2 i'll try that tonight, but if there were a simple "activate this thing" solution, i'd rather ask :)

**Comment by Alexandre-S** [comment]
Issue solved, thanks
