### ISSUE TITLE
Ace menu behind Main menu

### ISSUE THREAD

**Issue by Pesoen** [acemod/ACE3#4512]
**Arma 3 Version:** `1.64.138510` (stable / rc / dev)
**CBA Version:** `3.0.0` (stable / dev + commit hash)
**ACE3 Version:** `3.7.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@CUP_Terrain`
- `@RFT`
- `@RHSAFRF`
- `@RHSGREF`
- `@RHSUSAF`
- `@task_force_radio`

**Description:**
- the ace configuration menu appears behind the Arma 3 apex menu, so i cannot edit anything.

**Steps to reproduce:**
- start the game
- click the ace configuration button in the top left of the screen.
- menu now appears behind the new apex menu in the middle.

**Where did the issue occur?**
- Main Menu

**Placed Modules:**
- None

**RPT log file:**
- not an RPT file, but the debug just after launching the game, and openning the menu: https://www.dropbox.com/s/xcc0ciqc3tz8u5k/Arma3%20Ace%20Debug.txt?dl=0
- here is a picture of the bug, so you can see what i am talking about.
https://www.dropbox.com/s/4mb0gejks5l696q/20161005191428_1.jpg?dl=0

**Atempted fixes**
- starting without other mods(only CBA and ACE)

**Comment by PabstMirror** [comment]
Will be fixed in next release via #4451
For now only use ace options in-game.

**Comment by Pesoen** [comment]
understood :)
