### ISSUE TITLE
Player medic cures AI automatically

### ISSUE THREAD

**Issue by alef** [acemod/ACE3#4513]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.0` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHS`
- `@ACRE`
- `@ASR AI3`
- `@MCC`

**Description:**
- When you approach a grounded AI, the action of curing him starts wihtout any player command. It seems like the player act as a medic AI would do.

**Steps to reproduce:**
- In mission editor, create a player medic and another soldier
- Shoot the AI
- Approach the grounded AI and you will automatically start curing him

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- ACE Medical Settings: level Basic, enable AI Unconsciouness and Prevent instant death.

**RPT log file:**
Debug To Clipboard: https://gist.github.com/alef/7a5f00b9750ee952950517833ddfea54

**Comment by PabstMirror** [comment]
I think this was fixed via #4444

**Comment by BaerMitUmlaut** [comment]
Oh you're right. Great!
