### ISSUE TITLE
Cook off. RHS BMPs, BTRs, Urals?

### ISSUE THREAD

**Issue by Blitzkreigery** [acemod/ACE3#4515]
**Arma 3 Version:** `x.xx` (stable)
**CBA Version:** `3.1.0` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- @CBA_A3
- @ace
- @acex
- @ RHS AFRF
- @ RHS USF

**Description:**
- Ever since the new ACE update, we have been having troubles with blowing up RHS BMPs, BTRs, and Urals. The error doesn't happen all the time, but has happened three times so far, twice within in the past week.

Basically whenever the vehicles are blown up, by explosives, rockets, ect. It causes a memory leak on the server, and the server freezes and we are forced to crash it.

**Steps to reproduce:**
- Does not happen every time. 

1). Spawn in RHS BMP, BTR, Ural.
2). Destroy

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
Cant seem to be able to upload to pastebin, so I just put it in a  google drive: https://drive.google.com/file/d/0B1TXjbrTA7oMN0ZacEhHaGM0VnM/view?usp=sharing

Here is a snip of the last lines of the RPT: 
17:31:07 [ACE] (cookoff) WARNING: no valid selection for cookoff found.  File: z\ace\addons\cookoff\functions\fnc_cookOff.sqf Line: 31
17:31:07 [ACE] (cookoff) WARNING: no valid selection for cookoff found.  File: z\ace\addons\cookoff\functions\fnc_cookOff.sqf Line: 31
17:31:23 Deinitialized shape [Class: "B_Soldier_F"; Shape: "a3\characters_f\blufor\b_soldier_01.p3d";]
17:32:49 Sound: Error: File: a3\ui_f\data\sound\onclick.wss not found !!

The cook off warning happened for a majority of the RPT.

**Note**
I know you guys dont like it, when we dont just test until we find the mod confliction, but the RPT is literally mainly just this:
17:31:07 [ACE] (cookoff) WARNING: no valid selection for cookoff found.  File: z\ace\addons\cookoff\functions\fnc_cookOff.sqf Line: 31

and I didn't see the need to go through the process of removing and adding mods on the private server.

**Comment by bux578** [comment]
```
17:26:46 WARNING: ace requires ace_compat_rhs_afrf3 (@compat_rhs_afrf3) at version [3,7,0,6] (or higher). You have none.
17:26:46 WARNING: ace requires ace_compat_rhs_usf3 (@compat_rhs_usf3) at version [3,7,0,6] (or higher). You have none.```

You have so many non ACE3 errors in that RPT.

There's not much we can do this way.

**Comment by Blitzkreigery** [comment]
The memory leak starts on the RPT at the line: 17:29:13 [ACE] (cookoff) WARNING: no valid selection for cookoff found. rhsgref_ins_bmp1p File: z\ace\addons\cookoff\functions\fnc_cookOff.sqf Line: 31

then for 2-3 minuites its just a repeating
 [ACE] (cookoff) WARNING: no valid selection for cookoff found.  File: z\ace\addons\cookoff\functions\fnc_cookOff.sqf Line: 31

I fail to see where it could be other mods, or how a ballistic compatability would help.

**Comment by commy2** [comment]
It's not a memory leak. You deleted a cooked of vehicle while someone lagged out. This was fixed in https://github.com/acemod/ACE3/pull/4487.
