### ISSUE TITLE
Frag addon findReflections log spamming

### ISSUE THREAD

**Issue by tomhylsan** [acemod/ACE3#4520]
**Arma 3 Version:** `1.64.137497` (stable)
**CBA Version:** `3.1.0` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
@3cb_baf_vehicles
@akp_spotlight
@cup_terrains
@cyp_autorun_a3
@gpnvg18
@murshun_cigs
@rhsafrf
@rhsusaf
@rhsgref
@tf47_launchers
@task_force_radio
@jsrs4apex
@foxfort

**Description:**
- Something seems to have caused the explosive frag simulation addon to fill the server log with 8GB of this: 

`_lastPos = >
 7:27:35   Error Max array size would be reached. Current size: 9999999, wanted size: 10000000.
 7:27:35 File z\ace\addons\frag\functions\fnc_findReflections.sqf, line 33
 7:27:35 Error in expression <es > 0) exitWith {
_test = false;
_nlos pushBack _lastPos;

};

_lastPos = >
 7:27:35   Error position: <pushBack _lastPos;

};
`
The logging continued after all players left the server.

**Steps to reproduce:**
- Not able to reproduce

**Where did the issue occur?**
- Dedicated Server, Linux

**Placed Modules:**
- None

**RPT log file:**
8GB repetition of message above.

**Comment by PabstMirror** [comment]
Should be fixed via #4475

For now you will want to disable frag reflections
ace setting: `ace_frag_ReflectionsEnabled`
