### ISSUE TITLE
Advanced Fatigue and underwater swimming issues

### ISSUE THREAD

**Issue by Jaaxxxxon** [acemod/ACE3#4530]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.0`
**ACE3 Version:** `3.7.0` (stable)
**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Wearing a wetsuit makes you fatigue very fast (45 - 90 seconds to be fully fatigued) due to increased swimming speed and having your weapon out. This kind of makes using a wetsuit impossible.
- Weight dramatically affects the rate at which you fatigue; while IRL weight may make underwater swimming slightly more tiring, you're mostly weightless since packs and gear are usually neutrally buoyant. (More of a feature request than a bug, but still applicable)
- When swimming without a wetsuit, it's nearly impossible to fatigue at all, even when holding the sprint key. For gameplay and realism purposes, swimming in normal clothing should tire you out more than wearing purpose-built diving attire.

**Steps to reproduce:**
- Spawn in as a diver
- Try swimming anywhere
- Switch diver's clothes to normal cammies, swim freely.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**Comment by BaerMitUmlaut** [comment]
I've done some things to improve it and wearing a wetsuit now makes a massive difference. Thank you for your feedback.

**Comment by WastedMike** [comment]
Why is it that when ever you go prone you lose all your stamina?
