### ISSUE TITLE
Units are not react on explosions of Incendiary Granades, near. (Not switch to Danger mode)

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#4532]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
If a player throws an incendiary grenade at the enemy, who does not see the player, then this unit, after explosion this grenade will not switch to the mode of danger, as it comes after a after the grenade explosion. He will not respond.  As seems to me, the solution of this issue is not complicated. You only need to create the same effect, as at standard grenades.

**Steps to reproduce:**

* Place in the map player with Incendiary Granades.
* Place near several enemy units, so that they did not see the player and not have instantly to shoot him. Should be deployed with back to the player. 
* Throw Incendiary Granades in the enemy. Enemy not will react to explosions and self damages.
Will continue to stand like a statue, even under fire.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- not needed

**Comment by commy2** [comment]
> As seems to me, the solution of this issue is not complicated. You only need to create the same effect, as at standard grenades.

Please make a pull request if it's that simple.

**Comment by PabstMirror** [comment]
Closed by #4534

**Comment by ZeusWrath** [comment]
> Please make a pull request if it's that simple.
not understand you

**Comment by commy2** [comment]
ACE is a open source project. If you want something changed, you can always download the source code, make your changes and upstream. I'm salty that you wrote "the solution of this issue is not complicated." when in reality it is not trivial at all.

**Comment by ZeusWrath** [comment]
Hi! When I say - "the solution of this issue is not complicated"  I means  - **not complicated for mod creators, but not for mod users**. Having the source code I hardly could understand how all works, because I am not mod maker of Arma

**Comment by commy2** [comment]
It was rather tricky... Should be fixed in 3.8.0 though.

**Comment by bux578** [comment]
> not complicated for mod creators, but not for mod users

that's often a wrong assumption

**Comment by ZeusWrath** [comment]
> that's often a wrong assumption

may be
