### ISSUE TITLE
ace_vector missing when loading up mission

### ISSUE THREAD

**Issue by Nimrandel** [acemod/ACE3#4540]
Hi, when I try to play missions with ace mod active I get a notice cannot play/edit mission ace_vector missing. I have tried to redownload ace a couple of times and I see an ace_vector.pbo file in my addons folder. If anyone could help that would be great.

**Comment by commy2** [comment]
Why did you delete the template? Please read: https://github.com/acemod/ACE3/blob/master/.github/CONTRIBUTING.md
and open a new issue
