### ISSUE TITLE
ACE3 mod features not working after installation of SOS Pure Sound mod

### ISSUE THREAD

**Issue by MoistFlute** [acemod/ACE3#4543]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.0.160928` (stable)
**ACE3 Version:** `3.70` (Not stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@TEI`
- `@USS Iowa BB-61`
- `@Advanced Rappelling`
- `@Advanced Urban Rappelling`
- `@Arma Enhanced Movement`
- `@Imperial Assault`
- `@task_force_radio`
- `@Zombies and Demons`

**Description:**
- So before I installed the SOS Pure Sound mod, all my mods were running fine, including the ACE3 mod. So after playing a bit I go to install the SOS mod. Right after it is finished, I go to the Launcher. Everything is checked but I can't seem to find my sound mod in the mods tab. Oddly enough I installed everything in the @ folder in the same place as my other mods (Which worked fine.) Upon opening the game and loading a mission, I am greeted with error signs for my ACE3 mod and Task Force radio mod. Apparently, they both don't work anymore. The only thing left of ACE3 were the models, weapons, equipment, etc. But no other features remained. I went to go unsubscribe from the workshop on Steam, and resubscribe. Nothing changed. So I removed the entire @ folder for the SOS sound mod, and literally backstepped my installation. The ACE3 mod is still not working (Same with the Task Force radio) and the SOS sound mod icon still remains on the list of mods and expansions in-game.

I am rather new to downloading mods and am not sure if it is something I did wrong or not (Probably is haha. I may have overlooked something important). I did as much research on adding mods as I could, and they have worked for all of them. Except the SOS mod. If there is anymore information on the matter that anyone needs to know, I'd be happy to provide the info (Not sure what info is needed to determine what the issue could be.) I apologize in advance if I posted this in the wrong place. Tried my best to look for the correct place to post my issue (New to github as well. Never used it). Any help would be greatly appreciated.

**Steps to reproduce:**
- Installed the ACE3 mod and CBA through Steam Workshop
- Manually installed the SOS Pure Sound Mod into my Arma 3 directory (C:\Program Files (x86)\Steam\steamapps\common\Arma 3)
- Both mods activated in the Launcher
- Began working on the Singleplayer Editor
- Attempted a test run of the mission I made
- Received a bunch of error signs for the ACE3 mode and from that point the features stopped working

**Where did the issue occur?**
- Singleplayer Editor

**Placed Modules:**
- None

**RPT log file:**
-  http://pastebin.com/t0LpUSZ3

**Comment by BaerMitUmlaut** [comment]
The RPT you posted contains no error messages from ACE (generally there's only one script error, probably from the mission itself, something about an SDV, and a bunch of animation errors) and the mods you launched with are not the same you listed above. Are you sure this is the newest RPT from a session where those errors happened?

There's no sign of SOS in the RPT by the way.

**Comment by MoistFlute** [comment]
My bad on the mod listing. I forgot that I didn't enable some of them and just listed ALL the mods I had on the launcher. 

I was trying to make a mission involving an SDV scuba team. And for the RPT,  I couldn't find the one from the first instance where the issue first occurred (I knew I overlooked something important). So I restarted it after trying to get rid of the SOS mod thinking that it would solve my problem. Although, there were still no functions from ACE that worked even after I removed SOS. (Like the interact menu and the options menu, advanced throwing, etc).

**Comment by BaerMitUmlaut** [comment]
Can you try just launching with CBA and ACE and see if that works?

**Comment by MoistFlute** [comment]
After launching with just CBA and ACE, I found that the features such as interaction menus and ACE mod mechanics work fine and have returned to normal. However, there is no ACE mod options menu anymore. It disappeared after this most recent attempt.

**Comment by BaerMitUmlaut** [comment]
When you go in game (so when actually controlling a character), do you still have no options menu?

**Comment by MoistFlute** [comment]
I hopped in-game and found that after 2 tries, the options menu appeared in-game (controlling the character in-game, that is). I don't appear to be having other issues with the mod anymore.

**Comment by sargken** [comment]
SOS is really outdated. I wouldn't recommend using anymore. Use JSRS.

**Comment by MoistFlute** [comment]
I'll certainly take a look at that one then. Thanks a ton for the suggestion.
