### ISSUE TITLE
Kestrel 4500 broken without advanced ballistics

### ISSUE THREAD

**Issue by Isaac-h-e** [acemod/ACE3#4544]
**Arma 3 Version:** `1.64.138732` (stable)
**CBA Version:** `3.1.0.160928` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The Kestrel 4500 impeller continuously spins at the same speed regardless of the direction the first person view is facing at and the instantaneous wind speed screen also displays a constant value regardless of the direction.

**Steps to reproduce:**
- Just equip the player with a Kestrel, set it to display instantaneous wind speed and rotate the player along the vertical axis.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None.

**Comment by Isaac-h-e** [comment]
Not a bug, I didn't added the advanced ballistic module, my fault, sorry about that.

**Comment by jonpas** [comment]
Glad you resolved it!

**Comment by PabstMirror** [comment]
I don't understand why it's so different without advanced ballistics enabled.
How do you tell determine the direction of the wind?

**Comment by J3aLeiNe** [comment]
@PabstMirror, in the headwind screen with AB enabled("+"or"-" wind speed). The Kestrel seems completely bugged with the default ballistic but works correctly with AB. It could be a good idea if you reopen this issue to fix this strange bug because the description above is just a part of that.

**Comment by ulteq** [comment]
> How do you determine the direction of the wind?

Without advanced ballistics: `Set reference heading` and the Kestrel will does the rest for you
With advanced ballistics: `Shift+K` -> followed by turning the Kestrel into the wind direction
