### ISSUE TITLE
Ballistic Data on the AtragMX Wrong with advanced ballistics for the M200 Intervention

### ISSUE THREAD

**Issue by Icekraks** [acemod/ACE3#4559]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.0` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Ballistic Data on the AtragMX wrong with advanced ballistics for the M200 Intervention and maybe other rifles.

**Steps to reproduce:**
- Setup on a 1km firing range. Zero using Vector, ATrag and Kestral, The Elevation ends up more than double what it states on the ATragMx. 3.04 vs 7.5(My Elevation)

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Placed Modules:**
- Advanced Ballistics
- Medical Settings
- Advanced Medical Settings
- Revive Settings
- Wind Deflection
- Advanced Throwing
- Advanced Fatigue
- Hearing
- Interaction System
- ACE Map
- Captives
- Check PBO
- Explosive Settings
- MicroDagr Fill
- Pointing
- NameTags
- Rallypoint System
- Night Vision
- Repair
- User Interface
- Vehicle Respawn

**RPT Log File**
http://pastebin.com/1gkgg7mX

**Comment by bux578** [comment]
RPT please

**Comment by Icekraks** [comment]
*Edited with RPT Log.

**Comment by J3aLeiNe** [comment]
Hi @Icekraks , could you post a screenshot of the AtragMx, please ?

**Comment by Icekraks** [comment]
![vlcsnap-2016-10-17-21h38m19s689](https://cloud.githubusercontent.com/assets/5193466/19434596/14f2c8f6-94b2-11e6-833e-f92b86911550.png)

**Comment by J3aLeiNe** [comment]
The IA (Inclination Angle) should be 0 in your case, not 60°. 
You have a wrong correction for this reason. :)

**Comment by Icekraks** [comment]
okay so the ballistics are right, but I'm gonna change what this Issue Ticket is, in regards to the ATrag auto defaulting.
