### ISSUE TITLE
[Bug] Unconscious AI still aim at you.

### ISSUE THREAD

**Issue by Khaosmatic** [acemod/ACE3#456]
The AI when unconscious like to track players at least while in the uncon animation.

As shown here the evilness of the CSAT causes the victim to point at the predator:
https://www.youtube.com/watch?v=6fwa5x2Q4VA&feature=youtu.be

**Comment by CamoSteve** [comment]
Possessed CSAT! 
Interesting ;)

**Comment by Khaosmatic** [comment]
Even though someone put up a post in much more detail than mine just now, I'll still leave this here for the video's sake.

**Comment by jaynus** [comment]
Please file a real ticket.

https://github.com/acemod/ACE3/blob/master/documentation/user/how-to-report-an-issue.md

**Comment by PabstMirror** [comment]
seems to be fixed (still some small head movements while unconc)
