### ISSUE TITLE
Disable "ace option" in escape menu

### ISSUE THREAD

**Issue by KR3KZ** [acemod/ACE3#4560]
Hello, i would like to disable the fact you can change the options of ace in the escape menu in multiplayer...

Do you have any idea ?

Thanks

**Comment by 654wak654** [comment]
You can force all settings.

**Comment by KR3KZ** [comment]
I tried, it still doesnt work :/

**Comment by PabstMirror** [comment]
Delete `ace_optionsmenu.pbo`

**Comment by KR3KZ** [comment]
Thanks
