### ISSUE TITLE
During self-treatment, the AI does not required his medications.

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#4563]
**Arma 3 Version:** `1.64` (stable )
**CBA Version:** `3.0.0.160713` (stable )
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- In version 3.7.0 was added self-treatment of AI, but AI can treat self infinitely, because when self-treatment AI does not spent your bandages, medication. Turns so, now the AI can make self treatment without any medication in general.

**Steps to reproduce:**
-Place in the map squad with player - commander.
-Shoot from pistol several times in the legs or hand of your subordinates
-After every hit, AI will be treat self, immidiatly. After several hits and ai-self treatments, open a subordinate Inventory of this soldier. All medications will not be consumed.

Or 

-Place in the map soldier without any medication.
-Shoot in the legs or hand of this soldier.
-AI will be treat self, immidiatly, despite the fact that he has no any medications.

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- Not required

**Comment by AACO** [comment]
Yeah, it looks like there should be a state/condition check to make sure the unit/the medic has the supplies needed to heal the unit, and then fnc_healSelf.sqf/fnc_healUnit.sqf should consume the supplies when the treatment is triggered.

**Comment by BaerMitUmlaut** [comment]
This has been done on purpose so mission makers don't have to create custom loadouts for AI units (which would cause incompatibility with the campaign for example and, especially in multiplayer, would cause some additional performance overhead for the server when spawning units).

**Comment by AACO** [comment]
It could be made compatible with vanilla medical gear. Checking/consuming PAKs, checking for medkits/medics and not consuming the med kits. That might go outside the scope though.

**Comment by Glowbal** [comment]
We are welcoming pull requests that will improve this as long as they keep the motivation behind the current behaviour in mind ("This has been done on purpose so mission makers don't have to create custom loadouts for AI units" from @BaerMitUmlaut ). Mind you, if you do start working on it, you will need to look into the medical rewrite, as a lot of the internals of medical have changed.

I do not see us (@acemod/maintainers) taking priority in working on this, however.

**Comment by ZeusWrath** [comment]
> by design

then it would be better if self-treatment is not was added in general. Unrealistic things in the realistic mod looks  ridiculous

**Comment by BaerMitUmlaut** [comment]
Feel free turn it off through the settings framework.
