### ISSUE TITLE
FRIES module - slippery when wet menu

### ISSUE THREAD

**Issue by wynarator** [acemod/ACE3#4564]
An idea for FRIES update - give players option to bind "Use ropes". When the option is accessed via ACE menu it sometimes gets flickery, and then it's easy to misclick cut ropes instead of use ropes, an example can be seen here: 

https://www.youtube.com/watch?v=YzfBX_6N5rA

Best regards
Wynarator

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
