### ISSUE TITLE
Ammo Vehicles dont cook off

### ISSUE THREAD

**Issue by Djzonk** [acemod/ACE3#4565]
**Arma 3 Version:** `1.64` stable
**CBA Version:** `3.8.0` stable
**ACE3 Version:** `3.1.1` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- None of the ammo vehicles cook off HEMTT, Typhoon, KamAZ, Taru.
- Same for Taru Ammo pod.
- Huron ammo container and vehicle ammo smoke but nothing else

**Steps to reproduce:**
- Place listed items in editor and blow up

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- https://gist.github.com/Djzonk/22b8c2baf8ddbf24464189e6d62e50de

**Comment by Djzonk** [comment]
**Reason fore closure and reopening.**
- accidentally had 2 versions of ace open wanted to retest.

**Comment by Glowbal** [comment]
Correct. The reason is that those vehicles do not really have any ammo but rather an ammo supply value. We should probably look at some kind of solution for this. Maybe an hardcoded list of ammo in the config, that will scale based on the ammo supply remaining?
