### ISSUE TITLE
[ACE] ERROR File ace_sitting.pbo outdated.

### ISSUE THREAD

**Issue by ADLewis1975** [acemod/ACE3#4566]
**Arma 3 Version:** `3.7.0` (stable / rc / dev)
**CBA Version:** `3.1.1` (stable / dev + commit hash)
**ACE3 Version:** `3.1.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
-'@acex'

**Description:**
-**[ACE] ERROR File ace_sitting.pbo outdated.**
-Numerous ACE related modules are in the mission, and the server is number of other mods.
-Both client and server versions of ACE and ACEX are synced.
-Occurs if the module is in the mission, or is not.
-Kicks player back out to lobby.

**Steps to reproduce:**
-See above.

**Where did the issue occur?**
- Dedicated 

**Placed Modules:**
-Occurs whether the sitting module is placed, or not.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by jonpas** [comment]
Duplicate https://github.com/acemod/ACEX/issues/39

Hotfix will be released soon!

**Comment by Glowbal** [comment]
Hi @ADLewis1975, thanks for the report. As @jonpas mentioned this issue is an issue from ACEX. We have since released here: https://github.com/acemod/ACEX/releases/tag/v3.1.1

Please update to ACEX v3.1.1, as this should resolve the issue you are having.

Thanks! :+1:
