### ISSUE TITLE
Question about saving damage to the database.

### ISSUE THREAD

**Issue by SithisSir** [acemod/ACE3#4568]
Hi guys, sorry for disturbing you.
Im now running arma 3 server with Exile, CBA, ACE 3.8 and Ryan's Zombies And Demons (modified by me to use ACE health system and correct hitpoints).
But i have a problem, damage taken by player is not saving to the database, so i hope some of you can help me with rewriting scripts of saving/loading from database. Attaching files that actually save and load from DB
[Load](http://pastebin.com/6rx5NUan)
[Insert](http://pastebin.com/UDrrdne8)
[Update](http://pastebin.com/P4zNm2m6)
Thank you.

**Comment by commy2** [comment]
Hello,

There currently is no function to serialize or deserialize the "medical properties" of objects. This is a planned feature of our upcoming rewrite of the medical system however. https://github.com/acemod/ACE3/projects/2

This is a issue tracker and not meant for feature requests. Feature requests go here: https://github.com/acemod/ACE3/issues/3594

Exile is using a NoDerivates licence: http://www.exilemod.com/topic/826-license/
This means that you and we are not allowed to make changes and to "distribute" them, even by showing them on GitHub.

**Comment by SithisSir** [comment]
Ok, sorry for that. Hope you will add this future)
