### ISSUE TITLE
I cant start the server with ACE and any Car mod at the same time

### ISSUE THREAD

**Issue by Korbinian0073** [acemod/ACE3#4569]
**Arma 3 Server Version:** `1.64` (stable)
**CBA Version:** `newest update` (stable)
**ACE3 Version:** `3.7.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@CUP_Weapons 1.7.1`
- `@DDOPP_Taser`
- `@extDB2`
- `@infiSTAR_A3`
- `@life_server`
- `@ivory cars`

[arma3server_2016-10-19_18-32-28.txt](https://github.com/acemod/ACE3/files/540037/arma3server_2016-10-19_18-32-28.txt)

**Description:**
- When I try to start the server (dedicated root) it says this: 
1:07 Roles assigned.
14:01:07 Reading mission ...
14:01:07 mpmissions\Tanoa_Life.Tanoa\mission.sqm/Mission/Entities/Item1643.type: Vehicle class ACE_ModuleInteraction no longer exists
14:01:07 Mission Tanoa_Life.Tanoa read from directory.

This repeats this again and again and the server doesnt really start.

**Steps to reproduce:**
- I added the mod ivory cars (I checked it it happens with ALL modded car mods)
i started the server 
The things told in Description happen

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
ACE_moduleRepairSettings
ACE_moduleRefuelSettings
ace_finger_moduleSettings
ACE_ModuleNameTags
ace_ui_module
ACE_ModuleExplosive
ACE_ModuleMap
ACE_ModuleHearing
ACE_moduleReviveSettings
ace_captives_moduleSettings
ACE_moduleMedicalMenuSettings
ACE_moduleAdvancedMedicalSettings
ACE_moduleMedicalSettings
ACE_ModuleInteraction

**RPT log file:**

[arma3server_2016-10-19_18-32-28.txt](https://github.com/acemod/ACE3/files/540037/arma3server_2016-10-19_18-32-28.txt)

**Comment by PabstMirror** [comment]
no ace pbos are being loaded
double check they are in `C:\server\A3Master\@ace`

**Comment by Korbinian0073** [comment]
@PabstMirror they are there before I added the vehicle mod everything worked very well. 
By the way: Thats my arma3server.exe line: 
C:\server\A3Master\arma3server.exe -autoinit -servermod=@extDB2;@life_server;@DDOPP_Taser;@infiSTAR_A3;@CUP_Weapons;@CBA_A3;@Jonzie Mega Mod Pack;@ace -config=server.cfg -bepath=C:\server\A3Master\battleye -profiles=C:\server\A3Master

**Comment by PabstMirror** [comment]
`@Jonzie Mega Mod Pack` has spaces in it, so arma see it as the end of the parameter
and tries to just load jonz and skips ace
```
@Jonzie |              @Jonzie |      false |            NOT FOUND |     
```

I would recommend not using spaces in mod folders,
or I think you can wrap the whole mod list in quotes

**Comment by Korbinian0073** [comment]
@PabstMirror  yeah thanks! 
It was the problem with the spaces :D
Its working now!
Thanks! 💃
