### ISSUE TITLE
When Javelin hits game crash

### ISSUE THREAD

**Issue by Grzechotnik** [acemod/ACE3#4571]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.1.1012` (stable)
**ACE3 Version:** `3.8.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- RHS + ACE comp (using this javelin
- NATO SF Both
- TFAR
- CUP
- Shactac

**Description:**
- i'm locking on peopl, then i shoot and just when the missile hits game crash

**Steps to reproduce:**
- Go to editor place some people, lock on them with RHS Javelin and shoot

**Where did the issue occur?**
- Editor Singleplayer

**Placed Modules:**

**RPT log file:**
http://pastebin.com/KAw1vB6s

**Comment by jonpas** [comment]
Can you reproduce only with ACE3 and CBA?

**Comment by ZeusWrath** [comment]
Hi, I have test. Can confirm this bug. At hit in man the game was frozen

> Can you reproduce only with ACE3 and CBA?

Yes! Only ACE3 and CBA.

**Comment by KingZogg** [comment]
Also confirmed.
ACE and CBA latest versions. 
NLAW hit shut down server.
