### ISSUE TITLE
v 3.8.0 - Please remove ugly sound of secondary explosions. (or explane, how player can do it)

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#4572]
**Arma 3 Version:** `1.64` (stable )
**CBA Version:** `3.1.1.161012` (stable)
**ACE3 Version:** `3.8.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**

https://www.youtube.com/watch?v=M0rzOCQBuVY&feature=youtu.be

Unfortunatelly, it is not clear why it was added. It is not clear what is the source of these sounds.  
If the player moves from destroyed tank, then the sound does not change its volume! At distanse 10 m and 100 m from destroyed tank, this sounds has almost the same volume! That this? 
Maybe it detonation of tank ammo?  In 3.7.0. was added a good secondary explosions, this was cool, but for that added a new strange sound is unclear.  ACE Guys, please have pity on my ears, I think, this new sounds of poor quality and is not like anything, what could explode in the tank,  it's more like a mechanical typewriter from the 80s.
May be ACE team thinks it's a good sound, but In any case, thanks for the recommendation, how do I get rid of this.

**Steps to reproduce:**
- Destroy several enemy tanks in the editor. then, your ears will swell.

**Where did the issue occur?**
-Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- Not needed

**Comment by jonpas** [comment]
It is very similar to real life: https://youtu.be/VvuwUxaJmlo?t=1m14s
I think you can disable it by disable ammo cook-off through settings.

This is not a bug report, it's more of a feature request/feature change request, so it should go to #3594

**Comment by ZeusWrath** [comment]
> It is very similar to real life

Hi, I think, sound from ACE, completely different. also, it does not change with distance from the object.

> I think you can disable it by disable ammo cook-off through settings.

!? In the ACE settings no exist such settings. Please tell me, where I can switch off this.

> If you can reproduce distance bug with only latest ACE3 and CBA please make a separate issue for it and only it. 

I don't have time to create multiple tickets. No need to create a new ticket. I already created a ticket and provided a video. You can watch the Sound does not change its volume with changes in distance. 
Your choice, fix it or leave as is.

**Comment by PabstMirror** [comment]
You can disable cookoff by setting
`ace_cookoff_enable` to 0 (false)
reference http://ace3mod.com/wiki/framework/settings-framework.html

**Comment by ZeusWrath** [comment]
thanks
