### ISSUE TITLE
No way to rearm static crew served weapons such as the XM312

### ISSUE THREAD

**Issue by thecuban** [acemod/ACE3#4573]
**Arma 3 Version:** 1.64
**CBA Version:** 3.1.1.161012
**ACE3 Version:** 3.8.0

**Mods:**
- @CBA_A3
- @ace

**Description:**
- There exists an option for static weapons such as the XM312 to check the amount of available ammo the weapon has remaining in its magazine/inventory. However once the weapon is out of ammunition there is no way to rearm the static hmg in the field.

**Steps to reproduce: (aka the "dance")**
- place a static crew served weapon such as the XM312
- shoot all of its ammo
- sit around because your SOL due to a lack of ammo

**Where did the issue occur?**
- All game modes

**Placed Modules:**
- None

**Requested Change:**
- add ammo cans full of ammo (ex. 100 rd 12.7x99mm ammo can (for XM312)) that can be carried in your inventory to rearm static crew served weapons similar to the way ammo is used on the MK-6 mortar with all the advanced functions enabled.

**Comment by kamkill01011** [comment]
You can rearm static weapons with ammo truck, as you can rearm vehicles.

**Comment by thecuban** [comment]
Yes I am aware of that, however that's not how it works in the real world. In the real world a machine gun team would carry belts of ammo on foot into the field. While it is obviously possible, the machine gun (or any other crew served weapon) team would not always have a vehicle at their disposal to carry ammo and equipment.

**Comment by PabstMirror** [comment]
Ideally it would work similar to the mk6 with ammo handling.
We would need to add vehicle ammo magazine items for each weapon.
E.G. A 100 round belt of 50 BMG that could then be loaded into a static mg.

**Comment by thecuban** [comment]
Yes exactly! That's what I suggested as a change to fix this issue.

**Comment by commy2** [comment]
feature request
