### ISSUE TITLE
AceSitting Module and Some Problems

### ISSUE THREAD

**Issue by MrPhrost** [acemod/ACE3#4575]
Hello we are a realism unit from Turkey.Everything was good until ace got update yesterday. We are using PlayWithSix so we updated from here.When we try to enter server , it gave us a problem "Ace-SittingModule..." so I opened mission.sqm delete all things including sitting.I opened mission from my editor it was OK. I put it our server computer Arma3server.exe  start giving APPCRASH  problem. We need help :(

**Comment by kripto202** [comment]
can you provide the mission and can you make sure it isn't binerized. I think there might be some remnants of old pbos. If you can provide the rpt file from your server?

**Comment by MrPhrost** [comment]
Thank you for answer,  I'll send ASAP

**Comment by MrPhrost** [comment]
http://s5.dosya.tc/server3/3ut9hy/Karlitepe.rar.html wait 5 second and then press "Indir" with green box

**Comment by BTY13** [comment]
http://s4.dosya.tc/server3/4w0y0l/Ace.rar.html wait 5 second and then press "Indir" with green box
RPTs

**Comment by gotopost** [comment]
Hello there. Im having a similar problem with my missions as well. I been making a series of sp missions that i put on the steam workshop. And been using Ace mod from the start. But after the last update it gives me a message about some "lost content - ace sitting" I cant even access my missions in the editor anymore, Note i made 12 missions and this is the case with 10 of the missions while 2 of them still work perfectly.

**Comment by MrPhrost** [comment]
@gotopost , maybe open new topic for ur problem ? They can help u faster

**Comment by bux578** [comment]
You have placed the ace_sitting module. We have deprecated ace_sitting for at least two versions now with warnings in the rpt log files.
ace_sitting has moved to ACEX as acex_sitting.

Try loading ACEX alongside.

@MrPhrost you probably made some mistakes while deleting from mission.sqm

**Comment by gotopost** [comment]
@bux578 Thanks. I will try that.

**Comment by gotopost** [comment]
@bux578 Thanks alot again! It worked! I was starting to get scared that i had to redo all of the missions lol

**Comment by arv187** [comment]
I have same issue, all people now must dowload ACEX too? what will be the next? download ACEZ?

**Comment by MrPhrost** [comment]
Ty for answer @bux578 we are trying

**Comment by arv187** [comment]
so.. @MrPhrost you have edited mission.sqm or downloaded ACEX? I obtain error if I delete in sqm ace_sitting.

**Comment by bux578** [comment]
@arv187 
> We have deprecated ace_sitting for at least two versions now with warnings in the RPT log files.

**Comment by arv187** [comment]
I know, but I could continue editing missions.
I do not want to download another addon that I will not use.
I delete this in mission.sqm:

```
"ace_sitting",

	
class Item11
		{
			className="ace_sitting";
			name="ACE3 - Sitting";
			author="ACE-Team";
			url="http://ace3mod.com/";
		};
```
But then I obtain error to load mission in editor.

**Comment by MrPhrost** [comment]
Ty for ur attention it worked when we download Acex . U saved us :)

**Comment by jonpas** [comment]
> I do not want to download another addon that I will not use.
@arv187 Then simply don't, remove `ace_sitting` and be done with it. If you want to use sitting you will have to use `acex_sitting`, otherwise simply don't use it if you don't want.

**Comment by arv187** [comment]
@jonpas then my error was delete this?

class Item11
        {
            className="ace_sitting";
            name="ACE3 - Sitting";
            author="ACE-Team";
            url="http://ace3mod.com/";
        };

Now I only delete "ace_sitting", at the beginning of the file and now missions load in editor.
I take note to future issues.
