### ISSUE TITLE
Pat on the back - unnecessary animation

### ISSUE THREAD

**Issue by wynarator** [acemod/ACE3#4577]
There is a great option of patting someone on the back as to let them know that you are behind them, and I love that I can have it bound on my keyboard (I am using TAB).

However this is slaughtered by unnecessary animation of soldier reaching to grab a guy he's tapping - in MOUT it's taking forever to play this clunky animation while in urban areas speed and keeping focus is the key.

1. Animation is way too long/slow and that makes it the exact opposite of what pat on the shoulder should be (superquick).
2. Animation isn't looking realistic (it's a "grabbing stuff" animation)
3. Visual/audio cue of being tapped would do just great without animations.
4. Audio cue could be a little louder, as in reality it is hard not to notice that you are being tapped (well, speaking of soldiers using correct tapping technique which considers vests and whatnot that might be suppresing your perception of touch - sometimes it is better to smack someone's ass instead of tapping his shoulder under superheavy vest :P)

Personally I see no reason to keep this animation and I found myself limiting usage of tapping beacuse of it's clunkiness :(

**Comment by commy2** [comment]
I agree. No animation was needed for this. Alternatively use a gesture that does not interrupt movement.
