### ISSUE TITLE
[ACE] ERROR: Extension ace_fcs.dll not installed.

### ISSUE THREAD

**Issue by Gizmo16thJSOC** [acemod/ACE3#4584]
**Arma 3 Version:** `1.64.138732` (stable)
**CBA Version:** `3.1.1.1012` (stable)
**ACE3 Version:** `3.8.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Repeated by myself (Massachusetts, USA) and one other (Edmonton, Alberta, Canada)
- Mission fails to load after reporting FCS is deleted/missing
- Error originally found with RHS and ACE RHS compat mods loaded; immediately replicated with just ACE and CBA loaded
- **May be direct the result of loss of connection to BattleEye services due to DDOS attacks on DNS in the United States**
       - Error is _not present_ with BattleEye disabled

**Steps to reproduce:**
- Run ace, cba
- launch with BattleEye enabled
- Go into editor, place a vanilla unit

- Play (preview) scenario as multiplayer
 - go through screens to spawn in as per usual, receive error

- OR,  Save mission, export to multiplayer
 - Go to server browser, host a server, select mission, go through screens to spawn in as per usual, receive error

(NOTE: There is a noticeable time difference in launching the hosted server than usual. Then error appears after "map/briefing" screen upon loading in.)

**Where did the issue occur?**
_with BattleEye Enabled_
Self-Hosted Multiplayer via Editor, Self-Hosted Multiplayer via Server Browser

**Placed Modules:**
- advanced ballistics
- advanced fatigue
- advanced throwing
- blue force tracking
- captive settings
- equip FRIES
- explosive system
- hearing
- interaction system
- make unit handcuffed
- make unit surrender
- map
- map gestures
- map gestures-group settings
- microDAGR mapfill
- mk6 settings
- nametags
- nightvision
- pointing settings
- respawn system
- spectator settings
- tagging
- user interface
- view distance limiter
- weather
- wind deflection
- zeus settings
- cargo settings
- rearm settings
- refuel settings
- repair settings
- advanced medical settings [ace]
- basic medical settings [ace]
- medical menu settings
- medical settings [ace]
- revive settings [ace]

**RPT log file:**
- Non-crash, no RPT.

- Image of error [http://images.akamai.steamusercontent.com/ugc/246962430144880343/C761DEA06F92E3004099BB1DE10DA2DBF6BBC1A6/](url)

**Comment by Djzonk** [comment]
if im not mistaken this is a battle eye problem. its not recognizing the files and stopping them from loading. sadly the ACE3 team has no way to fix. a tempt fix is disable Battle eye until the attacks are over

**Comment by commy2** [comment]
Upload the RPT please. Thanks.

**Comment by Gizmo16thJSOC** [comment]
I've attempted to force an RPT file to be created by hosting a server via the client, however only 'mpstatistics' files are being generated. Just going to assume its the result of BattleEye, as mentioned; going to give the servers time to recover from the DDoS attacks from today and see if it persists after confirming BattleEye is running properly again.

**Comment by Djzonk** [comment]
@Gizmo16thJSOC rpt files are generated every single time the game launches aslong as `-nolog` is not used be it server or client. Now crash dumps are only created when the client or server crashes. 
enter that into your file explorer to find them
%userprofile%\AppData\Local\Arma 3

**Comment by PabstMirror** [comment]
Don't worry about rpt, battleye server's are down, so ace can't load dlls that it needs to run
You can check status via the arma launcher:
![image](https://cloud.githubusercontent.com/assets/9376747/19616582/a29e2394-97dc-11e6-9b48-16d76c6d3c67.png)

**Comment by Alexandre-S** [comment]
Seems like Battleye indeed

Got this :

![imgur_ace_broken](http://i.imgur.com/GvekVml.png)

Here is the .rpt 
http://pastebin.com/aC2A6ALS

**Comment by PabstMirror** [comment]
If server doesn't require it, you can disable battleeye

**Comment by RyanWolfe556** [comment]
Just want to mention, got the same errors here.
