### ISSUE TITLE
Ace Interact Key Minimizes

### ISSUE THREAD

**Issue by MikeTemplar** [acemod/ACE3#4588]
**Arma 3 Version:** `1.64.138732` (stable)
**CBA Version:** `3.1.1` (stable + commit hash)
**ACE3 Version:** `3.6.2` (stable / dev + commit hash)

**Mods:**
@CBA_A3
@ace3mod 

**Description:**
Hitting the windows key minimizes the game

**Steps to reproduce:**
I'm not sure how to reproduce this, it just sort of happens. I've looked through out the internet for fixes with no luck. This is the last resort.

**Where did the issue occur?**
Multiplayer & Singleplayer Servers

**Placed Modules:**
None

**What I've tried**
Edit Registry
Launching through Arma Sync & Arma Launcher
Using a script to disable windows key using AutoHotKey  
Launching as admin
Changing profiles in Arma
Changing to full screen, windowed, full screen windowed
"Gaming Mode" on Razer Synapse
Switching to default keys in Arma
Deleting user config files and starting Arma
**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by commy2** [comment]
You'll have to reassign the interaction menu to a different key if your system does not support it.

**Comment by MikeTemplar** [comment]
It has supported it in the past until recently.

**Comment by commy2** [comment]
100% nothing we did. Maybe a driver update, maybe a Arma update. We can't control low level stuff like this.
I'm closing this, because there is nothing we can do about it.

**Comment by MikeTemplar** [comment]
Just FYI - A full wipe/reinstall of windows seemed to do the trick. 

Same programs, same mods, same servers. I guess a config file gets messed up somewhere.

**Comment by commy2** [comment]
weird
