### ISSUE TITLE
Adjusted stances cause low fatigue usage

### ISSUE THREAD

**Issue by Broileri-LDDK** [acemod/ACE3#4591]
**Arma 3 Version:** `1.64.138732` (stable)
**CBA Version:** `3.1.1.161012` (stable)
**ACE3 Version:** `3.8.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Advancing in the three default stances - prone, crouched, or standing up - causes fatigue as expected in relation to these three stances. The stances between them, controlled by Ctrl + W or Ctrl + S, cause unexpected results. Advancing in other than the default stances is fatigue-wise always more beneficial.

There are 9 stances in the game, and you can move in 8 of them:
9: standing up, high
8: standing up, default
7: standing up, low
6: crouching, high
5: crouching, default
4: crouching, low
3: prone, high,
2: prone, default
1: prone, low (cannot move)

Currently only stances 2, 5, and 8 work as they should in relation to each other when it comes to player fatigue.

To put it bluntly, if you have to advance under fire, it currently often makes sense to conserve energy by doing this instead of crawling: http://stream1.gifsoup.com/view1/4583806/dog-scoot-o.gif . If a whole platoon should advance like this, some players may think it takes away a degree of immersion.

**Steps to reproduce:**
1. Start Arma 3 with ACE3 and CBA.
2. Start the editor on any island, or join any dedicated server.
3. Play any mission or custom scenario with any soldier.
4. Run around a bit to lower your fatigue (see the fatigue indicator on the top right corner).
5. Go prone and crawl. See the fatigue indicator value decreasing further at a certain speed.
6. Press (the default key) Ctrl + W to raise yourself one step higher into the sitting shooting stance.
7. Advance by pressing W. See the fatigue indicator value decreasing at a much lower speed or, if you don't have much to carry, even increasing.
8. Try advacing using different stances (controlled by default with Ctrl + W and Ctrl + S) and notice that you tend to conserve energy if you use any other than the three default ones (default prone, crouch, or standing up). If you are carrying a lot of weight, you may not gain energy, but you will still lose it much slower, which makes it beneficial to not advance in the three default stances (2, 5, or 8 in the Description above).

**Where did the issue occur?**
- Dedicated, Editor (Singleplayer).

**Placed Modules:**
- None.

**Comment by BaerMitUmlaut** [comment]
>There are 9 stances in the game, and you can move in 8 of them

You can only move in 4 of them. If you adjust your stance and move you automatically switch back to the base stance whilst moving. Only the prone-up stance has custom movement animations.

>Advancing in other than the default stances is fatigue-wise always more beneficial.

It seems like those animations don't get detected properly because they're not marked as movement animations (anim name starts with "aadj" instead of "amov"). Thanks for the bug report.
