### ISSUE TITLE
Magazine Repack/Identical Magazine Reload

### ISSUE THREAD

**Issue by TheGrimPanda** [acemod/ACE3#4593]
Hi! So a constant problem continues to occur within Arma that I think could possible be fixed and upon discussion with fellow members of my community believe would be an excellent addition to Ace3. 

The Problem:
Within Arma there are hundreds of weapons (this is obviously referring to Arma with mods such as CUP or RHS) and each weapon tends to use specific magazines and cartridges. While the magazine types may differ, a lot of the time the caliber of the cartridges tend to stay the same, but have the down side of not being able to be  used with weapon systems that were created with different proprietary magazines. For example, the SA-58 and AKM use the exact same cartridge (7.62x39) but do not have compatible magazines, making any recovered magazines out in the field by an Arma Operator useless unless obtaining said weapon that uses said magazine. 

The Proposal:
Obviously since both magazines use the same cartridge yet have different feed lips sizes, shapes, etc, the said cartridges would be able to be removed and placed into the magazine of the Operators choice. Now understandably some people may think "well that seems a bit far fetched. Creating magazines out of thin air isn't something you can just do in reality," which I agree with. There is no ability in real life to just conjure up magazines out of thin air that accept the cartridge type that you like, however with that said almost 80% of the vest types within Arma have a rear molled dump pouch, making it possible so that an operator could save their spent magazines, instead of discarding them with no possibility of rearming them. 

This would mean that within the Operators inventory they would have "empty magazines" indicating that they had no ammunition left within the spent sets. While this would take up inventory space i suggest that instead of taking up an area that would be occupied by a full magazine the size and weight would be reduced by 1/6th in order to make it so that if operator were to find a magazine that used the same ammunition type as his or her weapon they would be able to do a repack of their spent magazines and replenish their stock. 

Not only could ace3 do this, but it could be built upon with "loose round" boxes that could be placed within vehicles that could be set to certain caliber types in order for users within the vehicles to replenish their magazines without having to simply discard partially used magazines. The possibilities for this would be greatly beneficial to the realism of arma and making it a better experience for its users in the long run! 

Thank you for your time, and i hope to hear back from those that find this interesting. 

((also apologies for putting this in the issue tracker, but i was unable to post this as a feature request for some strange reason.))
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Comment by BaerMitUmlaut** [comment]
Feature requests should go into #3594.
