### ISSUE TITLE
Game freezes by shooting rockets/ tank shells on units

### ISSUE THREAD

**Issue by XXLKlugey** [acemod/ACE3#4594]
**Arma 3 Version:** 1.64.138732 (stable)
**CBA Version:** 3.1.1.1012  (stable)
**ACE3 Version:** 3.8.0 (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- shooting a rocket or a shell on a person,  freezes the game
- only can be shut down through task manager, giving an 0x00000001 – UNABLE_TO_INIT_DXGI error

**Where did the issue occur?**
- tested in Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- None

**Comment by SimonEff** [comment]
Same problem here! 
Placed a civilian in the editor and shot at him with a nlaw or rpg-7. Both time the game froze.

**Comment by PabstMirror** [comment]
Will be fixed in next release, which should be soon 
#4574
