### ISSUE TITLE
vehicle attachments 

### ISSUE THREAD

**Issue by brycesuggs** [acemod/ACE3#4599]
kinda like the chemlights being able to attach a shovel, fireaxe, jerry cans, rifle, backpack would be cool to do to some of these vehicles vanilla and modded. i would suggest things cannot be moved unless the vehicle was unlocked. would bring a whole new thing to the server. im telling you if i had a humvee with a jerry can attached i would use the jerry can.

**Comment by bux578** [comment]
Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
