### ISSUE TITLE
Able to switch to weapon while carrying fuel nozzle

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#4601]
**Arma 3 Version:** `1.64` stable
**CBA Version:** `3.1.1` stable
**ACE3 Version:** `3.8.1` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
When carrying a fuel nozzle (from ACE Refuel) you are able to switch to any weapon, with the nozzle still attached to your hand.

**Steps to reproduce:**
- Place a refuel truck
- Pick up its fuel nozzle
- Switch to your primary (through action menu or keybind)

**Where did the issue occur?**
- Editor

**Placed Modules:**
- None

**Comment by jonpas** [comment]
Same for carrying.
