### ISSUE TITLE
Ace_sitting.pbo PROBLEM!

### ISSUE THREAD

**Issue by Hotseabr** [acemod/ACE3#4606]
The problem with ace_sitting.pbo still happening in Arma3.
Loaded Ace 3.8.1 and AceX 3.1.1, but my game hasn´t APEX dlc.

And the problem continues.

**Comment by PabstMirror** [comment]
Sitting was moved to ACEX
https://github.com/acemod/ACEX/releases

Installing that should allow you to open old missions that require ace_sitting

If you are still having issues please include a rpt.

**Comment by Hotseabr** [comment]
.rpt file loaded.

For more info. I don´t have APEX dlc.

[arma3_2016-10-28_11-57-28.zip](https://github.com/acemod/ACE3/files/558590/arma3_2016-10-28_11-57-28.zip)

**Comment by commy2** [comment]
Delete these two files:
```
C:\Arma3 MODS\@ace\addons\ace_laser_selfdesignate.pbo
C:\Arma3 MODS\@ace\addons\ace_sitting.pbo
```
and try again. In future, always delete the mod folder before updating. Otherwise the removed files will still be there.

**Comment by Hotseabr** [comment]
Thnx for the rapid answer and for new information about delete previous version of the mod, to install the newer.

And for all following this issue. Problem solved!
