### ISSUE TITLE
1.62 added a command to link demo charge to its deployer

### ISSUE THREAD

**Issue by DLEGION** [acemod/ACE3#4608]
SUGGESTION:

i heard from Xeno that 1.62 added a command to somehow "link" demo charge to its deployer.

my suggestion is that ace3 demo charges should give the player who placed it points and the kill(s).

thanks bye !

**Comment by commy2** [comment]
#3594

**Comment by commy2** [comment]
even with that command, the medic system would not make use of vanilla scores

**Comment by DLEGION** [comment]
my dear narrow-minded friend, its used also to determine who placed a demo charge to destroy a target BUILDING.

**Comment by Glowbal** [comment]
> my dear narrow-minded friend

We do not appreciate those kind of comments here @DLEGION. Moving forward, please drop the passive aggressive and offensive statements. This is not the place. I trust you understand this.

I will lock this conversation, as @commy2 rightly closed it. This is a feature request. No further discussion is necessary here.
