### ISSUE TITLE
Building release problem

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#462]
I think I have everything configured properly but I keep getting these errors when I execute make.py file:
http://i.imgur.com/zIQ9FbT.png

So some are build properly but some are not. Any ideas what I am doing wrong or what I am missing?

**Comment by jonpas** [comment]
Have you run `setup.py` or set it manually? Make sure hardlinks are set to P drive and your Arma 3 root folder (subfolder should then be `z\ace` when setup is done).

**Comment by PabstMirror** [comment]
Goto p:\temp\ and look at .log file of something that doesn't build like aircraft_packing.log

Look near bottom of file for an error or warning.

**Comment by gienkov** [comment]
aircraft_packing.log

Warning: rapWarning: **********missing file(s)***************
Warning: z\ace\addons\aircraft\config.cpp Line 5292: \A3\Weapons_F_Beta\Reticle\Heli_Attack_01_Optics_Gunner_wide_F
Warning: z\ace\addons\aircraft\config.cpp Line 5303: \A3\Weapons_F_Beta\Reticle\Heli_Attack_01_Optics_Gunner_medium_F
Warning: z\ace\addons\aircraft\config.cpp Line 5314: \A3\Weapons_F_Beta\Reticle\Heli_Attack_01_Optics_Gunner_narrow_F
Warning: z\ace\addons\aircraft\config.cpp Line 5325: \A3\Weapons_F_Beta\Reticle\Heli_Attack_01_Optics_Gunner_narrow_F
Warning: z\ace\addons\aircraft\config.cpp Line 6346: \A3\Ui_f\data\IGUI\Cfg\HelicopterHUD\border_line_ca.paa
Warning: z\ace\addons\aircraft\config.cpp Line 6355: \A3\Ui_f\data\IGUI\Cfg\HelicopterHUD\border_line_ca.paa
Warning: z\ace\addons\aircraft\config.cpp Line 6364: \A3\Ui_f\data\IGUI\Cfg\HelicopterHUD\border_line_ca.paa
Warning: z\ace\addons\aircraft\config.cpp Line 6373: \A3\Ui_f\data\IGUI\Cfg\HelicopterHUD\border_line_ca.paa
Warning: z\ace\addons\aircraft\config.cpp Line 6391: \A3\Ui_f\data\IGUI\Cfg\HelicopterHUD\altimeter_value_ca.paa
Warning: z\ace\addons\aircraft\config.cpp Line 6413: \A3\Ui_f\data\IGUI\Cfg\HelicopterHUD\UAVspeedLadder_ca.paa
Warning: z\ace\addons\aircraft\config.cpp Line 6431: \A3\Ui_f\data\IGUI\Cfg\HelicopterHUD\airspeed_value_ca.paa
Warning: z\ace\addons\aircraft\config.cpp Line 6454: \A3\Ui_f\data\IGUI\Cfg\HelicopterHUD\UAValtLadder_ca.paa
Warning: z\ace\addons\aircraft\config.cpp Line 6466: \A3\Ui_f\data\IGUI\Cfg\HelicopterHUD\horizon_ladder_ca.paa
Warning: z\ace\addons\aircraft\config.cpp Line 6475: \A3\Ui_f\data\IGUI\Cfg\HelicopterHUD\horizon_aircraft_ca.paa
rapWarning: **********missing file(s)***************

**Comment by esteldunedain** [comment]
Unless you add a command parameter to avoid checking external references you need all Arma 3 pbos unpacked on the P: drive

**Comment by PabstMirror** [comment]
"A properly setup P-drive"

You need a3 extracted on your p:
Grab ArmA3p from https://dev.withsix.com/projects/mikero-pbodll/files

**Comment by gienkov** [comment]
Extracting pbo's now, did not know what is "A properly setup P-drive" so I just mounted it from A3 Tools :D. Many thanks!
