### ISSUE TITLE
Feature Request: Separate Binding for Primary fire in Aircraft only?

### ISSUE THREAD

**Issue by Wild-Dog** [acemod/ACE3#4623]
It'd be nice if I didn't have to remove Space from the Primary fire keybind after every time I wanted to use the Space bar to fire in a Jet or Heli.

And I haven't found a separate mod for this yet.

**Comment by Wild-Dog** [comment]
I thought it said this was the feature request section.

**Comment by commy2** [comment]
ref: #3594

**Comment by Wild-Dog** [comment]
Ohhh. It was the comment section. Thanks,
