### ISSUE TITLE
Javelin problems

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#4625]
**Arma 3 Version:** `1.64 RC` 
**CBA Version:** `3.1.1` (stable / dev + commit hash)
**ACE3 Version:** `3.8.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `CSAT Modification (replacement)`

**Description:**
-There are problems with javelin. After usage of weapon, switching to other launcher, shooting, and getting back javelin, there is no way to lock target or change fire mode. It also happens after unit switch.
Also problem appear when whe go phrone while launcher is in our hands

**Steps to reproduce:**
- Shoot, phrone (right after shoot), stand reload, try to aquire target, change fire mode.
- Start game with javelin (or titan compact), fire some rounds to locked target, then change launcher to rpg (for example) , now fire few rounds, get new javelin or titan, try to lock targets, switch fire modes.
- Spawn t javelin AT specs, use javelin on first, then switch to second, try to use javelin.

**Where did the issue occur?**
- SP

**Placed Modules:**
- NONE
**RPT log file:**

**Comment by bux578** [comment]
@vlad8011 Please add the RPT file from that session.

**Comment by vlad8011** [comment]
[Arma 3.zip](https://github.com/acemod/ACE3/files/566544/Arma.3.zip)
Plus i meet this :
https://forums.bistudio.com/topic/183399-weapons-wont-fire/?access_token=36e06f16c2e206a7782e248065823cc697b568c5df7a5729df8a02ed8a5d7da7df0a2c6589f4c5c9750f12047387a9ad#036;b28155d3f4e4eeee0c1401b7d0eb1c00&refresh_token=07e6deda0f97e5553604cc1bdad182c85fc869b24828c5a3e6e2d938cbab0a072f910ab812f08d086ea4f5b2f0ada885&#036;5b3cddcab531e866aa19508559396b1f

And i dont know what triggered it.

**Comment by vlad8011** [comment]
From what i discovered - only way to make weapon working again is to put it down (drop it), and get it back.

**Comment by PabstMirror** [comment]
Will be fixed via #4580

**Comment by vlad8011** [comment]
Nice, thanks. What this game could be without you.....
