### ISSUE TITLE
Hearing damage module affects external listener, not shooter

### ISSUE THREAD

**Issue by BullHorn7** [acemod/ACE3#463]
When hearing a 50cal technical shooting, hearing damage is audible. When firing from that same 50cal technical yourself, no hearing damage occurs.

Possibly more vehicles/weapons are affected, wasn't tested yet.

**Comment by PabstMirror** [comment]
Seems like the FireNear doesn't trigger on CAManBase when mounted in a vehicle.
It does trigger on the vehicle.
