### ISSUE TITLE
Full Repair inconsistencies

### ISSUE THREAD

**Issue by ColonelCarston** [acemod/ACE3#4634]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.1` (stable)
**ACE3 Version:** `3.8.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The option to initiate a full repair on a vehicle is inconsistent depending on the damage it receives. Damaging the vehicle using the Health/Armor slider in the editor will always give the option to fully repair a vehicle if it meets the requirements (Repair Facility/Engineer/Toolkit/etc), however, vehicles can take multiple high caliber or explosives rounds, completely disabling modules, and the option for a full repair may never appear.

This specifically relates to the Full Repair option that can be found under the Interactions menu on vehicles, not to the individual repair hitpoints that can be found on their own.

**Steps to reproduce:**
- Place the necessary items for Full Repair (Engineer/Repair Facility/Toolkit/etc.)
- Place down a vehicle and set its Health/Armor slider below 100%, even 99% will work for this.
- Place down another vehicle.
- Test the scenario and notice the ability to fully repair the vehicle damaged in the editor.
- Damage the second vehicle in some way, preferably with the first vehicle.
- Notice the lack of a full repair option.

I've also included the scenario I was using to test this below. I was personally able to dump 200 HMG rounds into both Hunters, putting the Hull of one in the red, and the Engine of the other in the red and did not get a Full Repair option.

[Repair_Test.Stratis.zip](https://github.com/acemod/ACE3/files/571432/Repair_Test.Stratis.zip)

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer  / Editor (Singleplayer) / Editor (Multiplayer) 

**Placed Modules:**
- ACE Repair Settings

**RPT log file:**
I've included the RPT For completeness, though there are no script errors related to this bug.
[rpt.txt](https://github.com/acemod/ACE3/files/571430/rpt.txt)

**Comment by PabstMirror** [comment]
Should be fixed by #4621

**Comment by PabstMirror** [comment]
Closed thanks to @Dystopian
