### ISSUE TITLE
Dedicated server; simply cannot get ACE to run.

### ISSUE THREAD

**Issue by TheZamok** [acemod/ACE3#4635]
**Arma 3 Version:** `1.64.138732` (stable)
**CBA Version:** `3.1.1.161012` (stable)
**ACE3 Version:** `Version 3.8.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- I've been trying to set up a dedicated server but I can't figure out to how to get ACE and CBA to work correctly. I've tested all the "shortcuts" in-game and the only one that kinda works is the SHIFT+G, grenade cooking menu. There is no arc for the throw, hence when I press throw it just drops the grenade on the ground.

**Steps to reproduce:**
- Don't really know what to type here, I set up the path to the mod folder in the parameters as per usual and start the server in an attempt to use the mods.

**Here's how the path to mods looks:**

-port=2302 
-config=server.cfg 
-world=empty 
-mod=@CBA_A3;@ace;@ace_optionals

EDIT: I have also tried without the ace optionals

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
- [Server PASTEBIN](http://pastebin.com/4MjsujMP)
   [Client PASTEBIN](http://pastebin.com/U60sb0zs)

Thank you in advance.

**Comment by tbeswick96** [comment]
@TheZamok Hav you tried just using the parameters in the parameters file in-line instead of -par? 
e.g:  
``"C:\Servers\Arma\arma3server.exe" -port=2302 -config=server.cfg -world=empty -mod=@CBA_A3;@ace;@ace_optionals``

**Comment by TheZamok** [comment]
Yes that's what I did the first time around, I tried it again just in case but the issue still persists.

**Comment by commy2** [comment]
```
19:46:43                                     @ace_optionals |       @ace_optionals |      false |            NOT FOUND |                                          |           |
19:46:43                                               @ace |                 @ace |      false |            NOT FOUND |                                          |           |
19:46:43                                            @CBA_A3 |              @CBA_A3 |      false |            NOT FOUND |                                          |           |
```
game can't find the mod folders, wrong paths

**Comment by kripto202** [comment]
I would use tadst, at least that works for our server. Also make sure the mod folders are in the arma 3 directory and the content inside the folder is correct.

**Comment by RSpeekenbrink** [comment]
@TheZamok Are your mods in the same folder as the a3server.exe?

**Comment by Glowbal** [comment]
> game can't find the mod folders, wrong paths

This seems to be an user error rather than an issue with ACE.

Since this has not received any activity for 7 days, I assume this issue has been resolved. If not, here is a page that might help you: https://community.bistudio.com/wiki/Arma_3_Startup_Parameters#Modifications
