### ISSUE TITLE
Allow Repair : Anyone doesn't work

### ISSUE THREAD

**Issue by kamkill01011** [acemod/ACE3#4643]
**Arma 3 Version:** `1.64` stable
**CBA Version:** `3.8.1` stable
**ACE3 Version:** `3.1.1` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The parameter Allow Repair of the Repair Settings works like Engineer only when set to Anyone

**Steps to reproduce:**
- place a Rifleman, a backpack, a toolkit, a damaged vehicle (40% Health/Armor) and the Repair Settings; pick up the backpack and the toolkit, then try to repair the vehicle. 

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- Repair Settings

**Comment by PabstMirror** [comment]
![image](https://cloud.githubusercontent.com/assets/9376747/20192744/d503d0d0-a750-11e6-89b3-ea1a81af4c5c.png)

What this means is that a unit can only repair a hitpoint if the damage is above 0.6; and it will only repair it down to 0.6.

This is confusing as threshhold ratio is in damage done, not health.  (`1 - damage = health`)
So 40% health just happens to equal 0.6 damage which is the cutoff.

You may want to drop that setting down.
Can check current value with `[player] call ace_repair_fnc_getPostRepairDamage`
The min damage to repair also drops to 0 when near a repair vehicle or facility.

**Comment by kamkill01011** [comment]
I tested what you said and it seems to works. So if I want people to be able to fully repair a vehicle I need to set Repair Threshold to 0 and if I want Engineer to be able to only do small repair I set his param to something like 0.3. Thank you for your answer.
