### ISSUE TITLE
Broken comment in fnc_nonDedicatedFix.sqf

### ISSUE THREAD

**Issue by Neviothr** [acemod/ACE3#4644]
The word _then_ breaks the comment in line 27 for some reason. Could be a Poseidon Tools issue.
https://gyazo.com/dfe2b26ded57f6f929aa54f4b9b5c77b

A fix would be to remove the word _then_.
```[{
    if (isNil QGVAR(serverPriorFog)) exitWith {
        TRACE_1("Ending PFEH to handling non-dedicated server running effect",_this);
        [_this select 1] call CBA_fnc_removePerFrameHandler;
    };
    if (!GVAR(running)) then { // If we aren't running the effect ourselves, use the server's old fog value
        0 setFog GVAR(serverPriorFog);
    };
}, 0, []] call CBA_fnc_addPerFrameHandler;```

**Comment by jonpas** [comment]
How exactly does it break the comment? What's the consequence? 

We don't use poseidon tools.

**Comment by Glowbal** [comment]
Thanks for your report @Neviothr. Judging from the screenshot you provided, it appears that you may have to report the issue you experience to whoever maintance the Poseidon tools. 

This is not an issue that affects ACE.  `then` is sqf syntax and the proposed solution would break the script.
