### ISSUE TITLE
Chernarus Grid System

### ISSUE THREAD

**Issue by orthor** [acemod/ACE3#4645]
Good Morning! 
I'm a great fan of ACE since Arma and me and some friends are playing your mod alot. Thank you for that masterpiece!

We also still play Arma 2 / Ace 2 alot, because we like the enviorment and the the general scenario. We used to print out the Maps to work with a non digital map for better realism. Your mapsystem of chernarus changes the Vanilla Grid System to a real MGRS typ grid, whch is great but unfortunatly i cannot find a HiRes Picture to print it. Du you have a printable Map of Chernarus with the Ace 2 Grid System? 

thank you in advance!

**Comment by BaerMitUmlaut** [comment]
Feature requests should go into #3594.

**Comment by bux578** [comment]
@BaerMitUmlaut this is not a feature request

**Comment by bux578** [comment]
@orthor I assume that you're the same guy who has contacted us on facebook. I've sent you an answer there.

But for the sake of completenes:
Try this: http://killzonekid.com/arma-scripting-tutorials-how-to-export-topography/

**Comment by Nels0** [comment]
Is there a way to get textured/photo versions?
