### ISSUE TITLE
Stamina isn't working correctly, still

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#4646]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.1` (stable)
**ACE3 Version:** `3.8.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- stamina in prone state is reduced similar to sprinting

**Steps to reproduce:**
- go prone, see stamina being reduced very strong and fast. crawl along the ground, see losing much stamina.  

**Where did the issue occur?**
- Dedicated  / Editor (Singleplayer) 

**Placed Modules:**
- 'None'

**RPT log file:**
- http://pastebin.com/fvjrxm5U

**Comment by BaerMitUmlaut** [comment]
Nope, this is on purpose. Crawling with gear isn't as easy as it seems. I might reduce the factor a bit though, I agree it's a bit too strong right now.
