### ISSUE TITLE
Red marker frozen on my screen

### ISSUE THREAD

**Issue by NorfolkCops** [acemod/ACE3#4654]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
-@task_force_radio
-@EODS_Release
-@cTab
-@Civillian Units
-@Jonzie Mega Mod Pack
-@Lakeside
-@Demian2435 Police
-@ODA Server Mods
-@Personal Arsenal
-@Air Cav Vietnam
-@MCC Sandbox
-@RS Rain Textures
-@Advanced Rappeling
-@Advanced AI command
-@Advanced Towing
-@Advanced Urban Rappeling
-@ALiVE
-@SharkTac User Interface
-@Arma Enhanced Movement
-@Canadian Armed Forces

**Description:**
- All the time when I load up in my Arma3, I want to use ACE, so I go ahead and try to use it, but the       red cercle stays on my screen, preventing me to fire my weapon, etc, but rarely, it will work.

**Steps to reproduce:**
- Load up another game of Arma.

**Where did the issue occur?**
- Self Hosted Multiplayer

**Placed Modules:**
- N/A

**RPT log file:**
- Cannot find.

**Comment by jonpas** [comment]
Please fill out the issue template properly. The template also describes how to find the RPT file.

**Comment by NorfolkCops** [comment]
I looked in my games folder, but I couldn't find the RPT file

**Comment by PabstMirror** [comment]
RPT can be found at `%localappdata%/Arma 3/`

You have a lot of mods running.
Please try with just CBA and ACE and see if you have issues.

**Comment by NorfolkCops** [comment]
I finally found the issue, the mod MCC had the same keybindings with ACE, apparently glitching ACE, so I changed the keybinds for MCC and it works fine now.
