### ISSUE TITLE
[immersion sugestion] Ragdoll on unconsiousnes?

### ISSUE THREAD

**Issue by JSN33BOY** [acemod/ACE3#4657]
When players and AI go unconsious, couldn't the ragdoll state be used? Your weapon could be left on the ground since it was dropped anyway or kept not a huge deal.

atm you know when someone is dead if they ragdoll and are beyond saving.
No denying the insta flip animations are a turnoff and ragdoll is sweet? why dont you do this?

would be immersive

**Comment by jameslkingsley** [comment]
Oh boy..

**Comment by alganthe** [comment]
here we go again.

**Comment by commy2** [comment]
#3594
