### ISSUE TITLE
Bring back the (Shift + V) rangetables from ACE2

### ISSUE THREAD

**Issue by ulteq** [acemod/ACE3#466]
I would love to be able to use those in-game:

[12.7x108mm](https://www.dropbox.com/s/v7a0eatb61lfvqz/12.7x108mm.xls)
[.50 BMG M33](https://www.dropbox.com/s/qoa8au38d7sz5qs/M33.xls)
[.50 BMG A-Max](https://www.dropbox.com/s/f3m6z7uc2jc726f/.50 BMG A-Max.xls)
[.416 Barrett](https://www.dropbox.com/s/5m8rr7e3l3vvxsn/.416 Barret.xls)
[.408 CT](https://www.dropbox.com/s/0trrak1je8q27hm/.408 CT.xls)
[338 Lapua Mag](https://www.dropbox.com/s/n274fthghjfufbt/.338 LM.xls)
[.303 British](https://www.dropbox.com/s/yuzft3i56aegdi3/.303 British.xls?dl=0)
[7.62x54mm](https://www.dropbox.com/s/pvb681ymak3gplq/7.62x54mm.xls)
[M80](https://www.dropbox.com/s/tpjhxbxe514iec0/7.62x51mm M80.xls)
[M118LR](https://www.dropbox.com/s/z0t9trj2x9whwe5/M118LR.xls)
[Mk248 Mod 0](https://www.dropbox.com/s/aybyodc8yuoctyo/MK248 mod 0.xls)
[Mk248 Mod 1](https://www.dropbox.com/s/ftg3z35kxdzuzbc/MK248 mod 1.xls)
[.300 WM Berger Hybrid OTM](https://www.dropbox.com/s/j0lbpo4g9gohkau/.300 WM Berger Hybrid OTM.xls)
[7.62x39mm](https://www.dropbox.com/s/dcipo837wul73eu/7.62x39mm.xls)
[300 AAC Blackout](https://www.dropbox.com/s/bdwtedc0tbsv3oe/7.62x35mm (300 AAC Blackout).xls)
[6.5x47mm Lapua Scenar](https://www.dropbox.com/s/rk12pf88t4gmqh0/6.5x47mm Lapua Scenar.xls)
[6.5x39mm Grendel](https://www.dropbox.com/s/5dri7t3hi7kk152/6.5x39mm (Grendel).xls)
[5.56x45mm](https://www.dropbox.com/s/um5k8woye2ry13a/M885.xls)
[MK262](https://www.dropbox.com/s/r9j8q9yau8ivz3l/MK262.xls)
[MK318](https://www.dropbox.com/s/brimc79v3jfz7zh/MK318.xls)
[5.45x39mm](https://www.dropbox.com/s/9586znplpiojbwb/5.45x39mm.xls)

[Muzzle velocity variation table](https://www.dropbox.com/s/zt61od7t9apkut6/AB Muzzle Velocity Variation Table.xlsx)

[AB Calibrated Ammo Parameters (Actual BC & MV)](https://www.dropbox.com/s/1zbw9f0ielp8aed/AB Calibrated Ammo Parameters (Actual BC %26 MV).xlsx)

**Comment by commy2** [comment]
+1 from me

**Comment by KoffeinFlummi** [comment]
Still don't like ingame range tables...

**Comment by ulteq** [comment]
Why? And what about this: https://github.com/acemod/ACE3/issues/115 ?

**Comment by CamoSteve** [comment]
:+1:

**Comment by esteldunedain** [comment]
:+1:

**Comment by gibonez** [comment]
I like the AGM method better. Or the idea of having an in game ballistic computer like is used in Advanced ballistics the best.

Sniping should not be rendered easy by having a simple range table.

**Comment by ulteq** [comment]
a) We do have an in game ballistics computer (ATragMX)
b) In what way is using a ballistics table easier than using a ballistics computer?

**Comment by esteldunedain** [comment]
>  In what way is using a ballistics table easier than using a ballistics computer?

It's not in any way, but I'd like to have those for historical scenarios. Granted the player can do them on their own with pen&paper, which is the argument Flummi always used.

**Comment by commy2** [comment]
> Granted the player can do them on their own with pen&paper, which is the argument Flummi always used.

We should make some offical pdf files then.

**Comment by jaynus** [comment]
These are a good alternative from the perspective that until we implement the full artillery system, it gives us a method to provide mortars/arty while disabling the bitch click arty.

**Comment by ulteq** [comment]
> We should make some official pdf files then.
The links in the first post are pdf files.

**Comment by commy2** [comment]
Hmm. I got an excel file. Anyway, I suggest offically putting them on the ace3mod page then.

**Comment by KoffeinFlummi** [comment]
> We should make some official pdf files then.

I really don't think that's a good idea. Unless you're willing to take care of it, it's just another thing to maintain and worry about. People already have a ballistic calculator (two if we update Arma3Spotter to ACE3's ballistics), and people who play in historical scenarios like @esteldunedain pointed out - where such a calculator wouldn't be appropriate - wouldn't use vanilla weapons anyways, making those tables useless, unless we also started maintaining tables for IFA3 etc.

I think the only reason people want this is because ACE2 had it.

**Comment by ulteq** [comment]
I will start working on a framework that builds range cards automatically based on weapon/ammo class names.
