### ISSUE TITLE
Discussion: German translation

### ISSUE THREAD

**Issue by licht-im-Norden87** [acemod/ACE3#4660]
I'll write in german because non german speaking people have nothing todo with it and wont understand it.

Mir ist klar, dass beim Übersetzen leicht ein Denglisch (in grammatikalischer Hinsicht) ensteht und dies eigentlich auch fast nicht  zu vermeiden ist. Ich stelle immer wieder fest, dass Satzstrukturen, auch von mir, häufig 1 zu 1 übernommen werden und Komposita unter den Teppich fallen.
 Beispielhaft fällt mir "Radius der Aufgabe" ein. Besser Aufgabenradius. Ich bin der Meinung, dass eine verbindliche Regelung für die deutsche Übersetzung eingeführt werden sollte. 

Denn jeder übersetzt anders, sodass der Stil in keinster Weise homogen ist. Dies führt dazu, dass das lesen schwer fällt.

1) Festlegung bestimmter, häufig auftretener Begrifflichkeiten bzw. dessen Übersetzung
2) Ermutigung bzw. Erzwingung deutscher Satzstrukturen bzw. eine Komplettumstellung 
3) Freies Übersetzen. Transcription anstelle der Translation. Darunter fällt auch andere Wörter zu verwenden, als sie im Original stehen, wenn hierdurch der Lesefluss gefördert wird.
@bux578. Wir sollten uns da einmal dranmachen bzw. Ideen und Vorschläge sammeln und evtl. mit der Übersetzungsrichtlinie beginnen.

**Comment by bux578** [comment]
@licht-im-Norden87 Sowas gibt es z.B. schon für's Spanische:
http://ace3mod.com/wiki/development/how-to-translate-ace3.html

Ich freue mich auf Deinen Vorschlag.
