### ISSUE TITLE
Interaction menu not showing up

### ISSUE THREAD

**Issue by zigaliro** [acemod/ACE3#4665]
**Arma 3 Version:** `1.64.138732` 
**CBA Version:** `3.1.2` 
**ACE3 Version:** `3.8.1`

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When I press CTRL + Windows key, the interaction menu doesn`t show up, however ACE is apparently working, because I can see ACE options when i press ESC in-game.

**Steps to reproduce:**
-Press CTRL + Windows key in-game.

**Where did the issue occur?**
- Single player and Multi player.

**Placed Modules:**
- None

**RPT log file:**
https://www.dropbox.com/s/as202iqk1lmlh5w/RPT%20file.rar?dl=0

**Comment by commy2** [comment]
delete these:
```
addons\demian2435_police.pbo - unknown
addons\ravage-[coop]the_escape_ne.altis.pbo - unknown
```

**Comment by zigaliro** [comment]
I deleted them, but still the same issue.

**Comment by commy2** [comment]
Try rebinding to a different key. Make sure to also test in an empty mission in the editor.

**Comment by zigaliro** [comment]
Rebinding to a different key worked. Problem solved 👍

**Comment by PabstMirror** [comment]
Some keyboards have problems passing the windows key.
I think some gaming ones may have a switch in hardware or software to control it's use in games.
