### ISSUE TITLE
AtragMX Gun names only partially readable.

### ISSUE THREAD

**Issue by dedmen** [acemod/ACE3#4669]
**Arma 3 Version:** `1.64` stable
**ACE3 Version:** `3.8.1` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
The Gun names in AtragMX are cut off and there is no possibility to see the full name.
See:
![test](http://image.prntscr.com/image/20ede22e18ce4936a37cb3fa442dd83e.png)

It's hard to see the difference between different Gun's/Ammunitions because you can't see the full name.
Example ".300WM Mk24" is all you see in the Gun selection.. 
And when you select that it will show ".300WM Mk248 Mod" on the Top. But there are two ".300WM Mk248 Mod".
So to find the correct type i have to go into gun Properties and compare the bullet weight.

As there are atrag changes incoming anyway i wanted to make sure this is on the ToDo list.
Possibles fixes:
- Tooltips on Gun names.
- Bigger UI
- "Scrolling text"

**Comment by ulteq** [comment]
First attempts to solve the issue.

![tooltip-small](https://cloud.githubusercontent.com/assets/9437207/20304039/849803d2-ab2e-11e6-82e9-ef4eb867f85b.jpg)

![font_size_reduction-small](https://cloud.githubusercontent.com/assets/9437207/20304037/83282dec-ab2e-11e6-9422-0ae4d0f28235.jpg)

**Comment by dedmen** [comment]
I like the second one better.. Is that auto resizing? If yes longer names will get too small.. If not longer names will still be too long.
Currently the text is clearly readable so a combination between a little smaller Font and tool-tips should be perfect.

**Comment by ulteq** [comment]
> I like the second one better

Me too.

> Is that auto resizing?

No, trial and error.

> If not longer names will still be too long.

Default gun list entries won't ever be longer.

> a combination between a little smaller Font and tool-tips should be perfect.

I will try to make the font as large as possible without cutting anything, but no tooltips for now.

**Comment by dedmen** [comment]
I mean if people save own presets.. with too long names they are still cut off. 
Maybe only tooltips if the name is too long :X if Arma allows that

**Comment by ulteq** [comment]
> Maybe only tooltips if the name is too long :X if Arma allows that

Good idea.

**Comment by ulteq** [comment]
Slightly reduced font size with new text alignment:
![alignment-small](https://cloud.githubusercontent.com/assets/9437207/20304980/6c5f2250-ab33-11e6-9d13-7974104bad64.jpg)
