### ISSUE TITLE
[Script Error] Map Gestures

### ISSUE THREAD

**Issue by JHill29th** [acemod/ACE3#4676]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.8.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- 

**Steps to reproduce:**
- Click and hold left mouse button.  Script error shows.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
```
13:56:31 Error in expression <], []], [[]]], "_key"];

_key in (_hash select 1); 
>
13:56:31   Error position: <select 1); 
>
13:56:31   Error Zero divisor
13:56:31 File x\cba\addons\hashes\fnc_hashHasKey.sqf, line 11
13:56:31 Error in expression <gestures_defaultColor};
};


_mapHandle drawIcon ["\a3\ui_f\data\gui\cfg\Hints\i>
13:56:31   Error position: <drawIcon ["\a3\ui_f\data\gui\cfg\Hints\i>
13:56:31   Error 0 elements provided, 4 expected
13:56:31 File z\ace\addons\map_gestures\functions\fnc_drawMapGestures.sqf, line 42
```

**Comment by PabstMirror** [comment]
#4486
Will be fixed in next release

For now, you could check you ace settings for map gestures setting `ace_map_gestures_groupColorConfigurationMapping` and make sure it is not set
