### ISSUE TITLE
MELB Fastroping config for compat_rhs_usf3

### ISSUE THREAD

**Issue by Whigital** [acemod/ACE3#4683]
**Arma 3 Version:** `1.64` *stable*
**CBA Version:** `3.1.1` *stable*
**ACE3 Version:** `3.8.1.11` *stable*

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHSUSAF`

**Description:**

`compat_rhs_usf3`

For `config.cpp/CfgPatches`:

`requiredAddons[] = {"rhsusf_c_melb"};`

For `CfgVehicles.hpp/CfgVehicles`:

```
class RHS_MELB_base: Helicopter_Base_H {};

class RHS_MELB_MH6M: RHS_MELB_base
{
	ace_fastroping_enabled = 1; //EGVAR(fastroping,enabled) = 1;
	ace_fastroping_onCut = "ace_compat_rhs_usf3_fnc_onCut"; //EGVAR(fastroping,onCut) = QFUNC(onCut);
	ace_fastroping_onPrepare = "ace_compat_rhs_usf3_fnc_onPrepare"; //EGVAR(fastroping,onPrepare) = QFUNC(onPrepare);
	ace_fastroping_ropeOrigins[] = {{1.166, 0.79, -0.01}, {-1.166, 0.79, -0.01}}; //EGVAR(fastroping,ropeOrigins)[] = {{1.166, 0.79, -0.01}, {-1.166, 0.79, -0.01}};
};
```

**Steps to reproduce:**
`n/a`

**Where did the issue occur?**
`n/a`

**Placed Modules:**
`n/a`

**RPT log file:**
`n/a`

**Comment by Neviothr** [comment]
You should probably turn this into a pull request.
