### ISSUE TITLE
Optional Files are not listed as ACE_isOptional

### ISSUE THREAD

**Issue by Slowrider8** [acemod/ACE3#4684]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.8.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- All optional pbos included with ACE except from noactionmenu.pbo and nocrosshair.pbo do not include ACE_isOptional = 1;. This means that these addons are not excluded from fnc_checkFiles.sqf and therefore if the client is running them but the server is not, the client will be booted for Client/Server Addon Mismatch:

![unknown 1](https://cloud.githubusercontent.com/assets/1593099/20367268/b7ec4ad6-ac46-11e6-9185-0a57352804c3.png)

Such an action would make sense for the main files of ACE as running with or without them could cause strange issues, but if these optional files are actually optional, then they should be allowed to run without any objection by the server. For compatibility files, if the server is not running the base mod the file is supposed to make compatible, then it technically doesn't matter at all, and in most cases this will be reflected in the modset that the client is running.  

This may seem like a small issue, but it causes problems for two communities wishing to play together on the same server while using slightly different configurations of ACE. Usually this would be fine due to the server options file, but this does not affect optional PBOs.

**Comment by jonpas** [comment]
That is by design, `ACE_isOptional = 1;` means it's an optional client-side mod, one that does not have to be present in the server. Compatibility PBOs or particles/tracers or similar have to be installed on both client and server to function correctly.
