### ISSUE TITLE
How to Disable ACE3 Cookoff globally.

### ISSUE THREAD

**Issue by JudahHarvey** [acemod/ACE3#4686]
**Arma 3 Version:** `x.xx` (stable)
CBA Version:** `3.x.x` (stable)
ACE3 Version:** `3.8.1` (stable)

Mods:**
- `@CBA_A3`
- `@ace`
- @chaLAV25 
- @RHSUSAF

**Description:**
- The new ACE3 cookoff system has caused some problems with a few mods that my group uses, and we would like to temporarily disable this functionality for all vehicles without using a variable on that vehicle.

**Steps to reproduce:**
- Place a vehicle in ACE from CHA_LAV25 and destroy it.

**Where did the issue occur?**
- Self hosted multiplayer

**Placed Modules:**
- None

**Comment by 654wak654** [comment]
You can either set the value of `ace_cookoff_enable` to `false` or remove the ace_cookoff.pbo

**Comment by PabstMirror** [comment]
Also keep in mind that next release of ace will contain some fixes for cookoff,
so you may want to retest it at that point.

**Comment by geekwithbadge** [comment]
Can someone help me with this. I have ace_cookoff_enable=0; placed in my description.ext but it doesn't seem to work. We would really like to shut this off globally.

**Comment by PabstMirror** [comment]
@geekwithbadge 
In 3.9 how the settings works changed

`ace_cookoff_enable` (bool) controls the damage handling aspect of cookoff
`ace_cookoff_enableAmmoCookoff` (bool) controls the cookoff effect

They are independent, so enable can be false but enableAmmoCookoff would still default to true.
Set both to false to completely disable.
