### ISSUE TITLE
overpressure too much on 100mm / 125mm guns & rpgs

### ISSUE THREAD

**Issue by Aebian** [acemod/ACE3#4691]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `latest` (stable)
**ACE3 Version:** ` latest` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHS_AFRF`
- `@acre2`
- `Check RPT for more`

**Description:**
- If you are standing 20 meters near a tank or armored fighting vehicle and this is firing its 100 / 125mm gun then you will get overpressure damage. Even if you are behind the tank. In RealLife you need to be atleast 2 meters at front to the main gun to get that amount of damage.

- Same occurs for RPG Launchers. They overpressure damage is also too high. Since you can even fire that launcher from inside a house (e.g. all the videos from syria where soldiers are firing them inside a house with no damage)

**Steps to reproduce:**
- Place a tank or IFV on the map with advanced medical system active and let someone shot the canon while you are next to the tank (20 meters or closer). I even had a small hill between me and the tank and got damage for overpressure.

**Where did the issue occur?**
- Dedicated Server with 35 players including headless client

**Placed Modules:**
- MicroDAGR MapFill // ACE Medical System Advanced Modules.

**RPT log file:**
- https://gist.github.com/Aebian/aa61d10ce184f64edd49ee73a5565656

**Comment by commy2** [comment]
>Even if you are behind the tank.
really? What tank? The overpressure zone is directional.

**Comment by Aebian** [comment]
Well in our Mission we had a BMD-4M that caused us to report this issue. 

![image](https://img.knight-industries.org/bmd4m-overpressure.png)
The image above shows the BMD-4M and marked with white the positions where were positioned.
Even the guy at the end recieved damage alltough it should not do that.

**Comment by commy2** [comment]
The RHS unit probably not configured correctly.

**Comment by Aebian** [comment]
![Feedback_RHS](https://img.knight-industries.org/2016-11-20_23-43-04.png) What do mean by not configured properly? What kind of value is required?

**Comment by commy2** [comment]
http://ace3mod.com/wiki/framework/overpressure-framework.html

**Comment by ulteq** [comment]
This might be something we have to address in our compat pbos?

**Comment by coachwn** [comment]
Or maybe have RHS address the config issue entirely since they have more than one vehicle that isn't config'd properly as does CUP.

**Comment by PabstMirror** [comment]
The BMD-4's gun only shoots at about 300m/s, so I think it's overpressure configs should be lowered.

But overpressure should not effect units behind the gun's muzzle.
Keep in mind that it's shooting a giant HE-FRAG shell, so it might be shrapnel from ace_frag hitting those units.
