### ISSUE TITLE
Update version number on homepage (Last Step Before Release)

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#4692]
Don't close this issue, but rather move it to the next milestone.

**Comment by Glowbal** [comment]
This has been done for v3.8.2

**Comment by PabstMirror** [comment]
Done for 3.8.3 - 2151fcad8f426de558cfd4354cd073e646297abe

**Comment by Glowbal** [comment]
Done for 3.9.1.

**Comment by jonpas** [comment]
Done for 3.10.2 - 980e3d255edcb68632e9d6883a5d9ae299d64e2f

**Comment by bux** [comment]
Closing because of #5497
