### ISSUE TITLE
Personal modifications in PBO Config.bin(s) leading to error/Errors on extraction of pbo for personal adjustment only.

### ISSUE THREAD

**Issue by Wolfysharp** [acemod/ACE3#4693]
**Arma 3 Version:** Up to date version non beta (steam, stable.)
**CBA Version:** Steam workshop version
**ACE3 Version:** Steam Workshop version (stable, modified.)

**Mods:**
- `@CBA_A3`
- vsm warfighters
- zee identity
-spec4gear
-NIarms (full all weapon packs independently)
-Csat Russian Escelation
-acex 3.1.1
-KA Arsenal Everywhere
-bloodlust
-orthes forces
-elite warriors stamina carry capacity
-@I_immerse
-dynasound
-tac vests
-vsm vests and helmets
-GPNVG18 Night vision
-military gear pack
-CBRN Defense Units
-BAF weapons v2.0
-thermal vision goggles by Rad
-Barret M107 by Rad
-asdg jr
-slatts scar
-ggzersum M1 Garand
-$str_min_rf_mod
- `@ace`

**Description:**
I was trying to modify the default values in ace_advanced_fatigue.pbo and ace_medical.pbo configs. and settings, in their respective PBOs using eliteness, as I am not good enough with official tools yet and they are more complex and complicated. After modification and repbo-ing i came across multiple errors:
at first i had a problem with the config in both medical and advanced fatigue failing to find the XEH files. However, I found that at the end of the quotations there was a apostrophe and deleting that fixed the problem
 EX. Before changing quotes: "\z\ace\addons\medical\XEH_init.sqf'"
to
EX. After changing quotes: '\z\ace\addons\medical\XEH_init.sqf"

This problem occurs only with init, postinit, preinit, and preStart.sqf files in both advanced fatigue and medical PBOs.

I was able to fix the XEH problem by my self by changing "/blah /blah /blah.sqf'"; to '/blah/ blah /blah /blah.sqf";

The NEWEST problem however, which i don't know if it stems from the changes in the pbo. is that the UI files are not being found in the game upon trying to start editor or mission and, although just a texture error, it is causing the modules not to start or work at all in game. This error does not appear on the menus page and persists across editor and SP (haven't tested MP).

**Steps to reproduce:**
Using eliteness, simply extract the PBO and re-pbo the folders: Ace_medical.pbo and Ace_advanced_fatigue.pbo

No Modifications to anything, even the config is required to make these errors occur. Tested this and i think its an issue with eliteness, but im not too sure.

**Where did the issue occur?**
Editor
SP missions (Scenario, campaign, etc.)

Re-install works fine.

**Placed Modules:**
Ace_MedicalSettings
Ace_Medical
Ace_Advanced_Fatigue

**RPT log file:**
It does not cause a crash, and thus there is no RPT file.

However, i will post the details here about all my adjustments, and give the files and PBOs and if possible, would like you to take a look and see if you can adjust for me or at least help me out with correctly modifying your config.

DISCLAIMER: These adjustments are in no way to duplicate your mod, and will NEVER be posted on a public site for download without your consent. They are PURELY for SP, and AT MOST a small 4-5 person squad of friends. So no need to worry about me stealing your Mojo as one of the best mods. Any files presented here are error ridden and will not work correctly without re-downloading ace, and thus are useless to anyone downloading them from my Dropbox.

The file is too large for git hub, will be on Dropbox and Linked here.

Sincerely, Fenrisulfr Skarr.
SteamID: Fenrisúlfr Väinämöinen Skarr
Email(S): Primary: thomas0101-1@hotmail.com
Secondary: walwez03@yahoo.com

Files (full and with all adjustments.):

https://www.dropbox.com/s/4hmlpb7gtxmbnav/Test%20Settings%20%28Ace%29.zip?dl=0

P.S.: I'm aware of mismatched quotes. (EX. '\z\ace\addons\medical\UI\Icon_Module_Medical_ca.paa"; ) I tried making some adjustments to try and resolve the issue, spending all night (until 3:54 AM) trying to resolve the issue. So ive corrected them back to their original setting to where the errors kept taking place on my part without the XEH error.

P.S.S: You can see my adjustments in the config and settings for both, but they are not finished, so I'm hoping to be enlightened on steps or what to use in order to modify them of my own time, so im not reliant on here for information.

**Comment by Glowbal** [comment]
Hi @Wolfysharp, you are certainly trying the hard way to make changes to ACE.

What are you trying to adjust? A lot of the default behaviour of ACE is adjustable using our settings framework. If you need more freedom to tweak the behaviour of ACE, I'd suggest to fork the project and follow our development instructions to build a version yourself. Here are the instructions: http://ace3mod.com/wiki/development/setting-up-the-development-environment.html

Let us know if you need help with that.

Unpacking and editing a binarized pbo is not recommended.

**Comment by Wolfysharp** [comment]
@Glowbal Mostly just stamina adjustments and medical adjustments for scenarios involving fireteam or at most small squads of friends, though mostly being a solo operator as well.

I'm aware of the settings options and such, but that's currently non adjustable other than in editor, for me anyway, and i cant modify the campaign files or scenario files like dynamic patrol ops and etc in a timely fashion, so im just trying to modify the default values to apply the changes universally without needing to adjust every mission independently. I'm trying to achieve a more slow paced combat experience where long term injuries and short term blood loss, are going to be the main killer of a unit, not the direct immediate injuries. The stamina im still working with to try and find a better balance for jogging (as it seems to drain too fast for a enjoyable experience for a small group who cant compensate for sub classes like medics entirely. Especially on time limited events. Medically though, i have made it before where body armor is more reliable to prevent injuries, while leg,arm,lower body, etc injuries are not immedietly a threat, but rifle hits can lead to you falling unconscious within seconds and bleeding out shortly afterwards if your not patched up......In summary, effectively in a direct engagement you can survive 3~ish hits from a 556 threat without instantly dying immediately, Just falling into a bleed out phase with MASSIVE blood loss. I cant use the revive system as i want something more authentic than just falling on the ground and not being able to bring yourself around a corner before succumbing to wounds. That sort of thing.

Sorry for the long explanation, but in summary, just tweaks to the numbers on the default configs and settings in the .pbo to spare time and effort in the long run, as applying map after map and doing that much scripting eventually gets tiresome, so im trying to reflect this in a short term work span, and not need to worry about long term map scripting. If you catch my drift.

**Comment by Wolfysharp** [comment]
Also i will need a bit of assistance with building ace up from scratch as well, that would be nice, the instructions on your page are a little unclear as im not too experienced at making this from ground up.

**Comment by Wolfysharp** [comment]
@Glowbal I found a way around defaults, i used aceserver.pbo and its userconfig optionals and it works perfectly for adjusting for what i need for SP and small squads.
