### ISSUE TITLE
Order of operation for advanced medical treatments

### ISSUE THREAD

**Issue by GokouZWAR** [acemod/ACE3#4698]
**Feature Request:**
- When performing bandaging on a single body part with multiple injuries with varying types of injuries its difficult to figure out which injury will be worked on first. This can create problems if the injury worked on doesn't match the best available treatment when the system picks the injury to treat. 
- It would be very helpful to be able to determine which injury will be worked on first (determine which is the worst injury) and highlight that injury in red, the next injury to be worked on, yellow, and green and so forth, or perhaps a numbering system to visually show the order of operation.
- This way when the system goes to bandage the injury we can know we are applying the best treatment option for the injury.

An alternate suggestion would be to allow us to select which injury we'd like to work on first before starting treatments. This feature could also be enabled by a setting on the client ("Auto treatments" / "Manual Treatments") if the user doesn't want to have that level of control.

**Comment by bux578** [comment]
Thank you for your request, but this is a feature request. Please move it to the appropriate issue: #3594
