### ISSUE TITLE
Draging an AI crashes the game.

### ISSUE THREAD

**Issue by mal7house** [acemod/ACE3#471]

**Comment by Glowbal** [comment]
Please recreate the bug report according to this guidelines: [click](http://koffeinflummi.github.io/ACE3/wiki/user/how-to-report-an-issue.html).

**Comment by commy2** [comment]
Probably fixed by https://github.com/acemod/ACE3/issues/441

Dragging creates the same dummy weapon object in some cases that crashed bandaging.
