### ISSUE TITLE
Tracer and Particles out of date on Steam upload

### ISSUE THREAD

**Issue by TheGrimPanda** [acemod/ACE3#4717]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Trying to load a mission on a server or privately and we are getting an error saying "version out of date" even though we use the steam upload for ace and it seems to be missing the files.

**Steps to reproduce:**
download the ace stuff from steam...

**Where did the issue occur?**
upon loading any mission, single-player or multi-player

**Placed Modules:**
none

**Comment by PabstMirror** [comment]
tracers and particles are in the optional folder
if you are just copying over they won't be replaced

I would delete your ace folder and copy fresh

**Comment by TheGrimPanda** [comment]
yeah just realized what happened, sorry about that... still kinda new to updating ace.
