### ISSUE TITLE
Arma3 Client on Windows crashes with dedicated Linux Server ACE3

### ISSUE THREAD

**Issue by renalexster** [acemod/ACE3#4719]
**Arma 3 Version:** `1.64.138732` (stable / rc / dev)
**CBA Version:** `3.8.2` (stable / dev + commit hash)
**ACE3 Version:** `3.1.2` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Running only CBA and ACE on Linux Dedicated Server (Ubuntu), and a simple test mission with ace modules enabled. When the arma3 client (windows) attempts to start the mission, the game crashes (on the client only). However, if I open the editor with the mission before, and then try to connect in the mission, works.

**Steps to reproduce:**
- Try a simple mission on dedicated Linux server
- Put on mission ACE modules (medical, etc)
- Use Windows with ACE e CBA and try start a mission
- Client crashes on startup

**Where did the issue occur?**
- Client on Windows crashes with dedicated Linux Server

**Placed Modules:**
- Only ACE

**RPT log file:**
- RPT log http://pastebin.com/m5YBn0DK
- Mission SQM http://pastebin.com/76SaFWVF

**Comment by BaerMitUmlaut** [comment]
Can you try the same without ACE? I don't see how we could cause a CTD unless there something very wrong with the extension DLLs.

**Comment by renalexster** [comment]
I think I figured out the problem. I was copying the mission with the folder, not just the "pbo" file. I tested it with no addon and presented the same problem, when I copied the mission file worked.
