### ISSUE TITLE
Adjust overheating for modded weapons/ammo

### ISSUE THREAD

**Issue by kamkill01011** [acemod/ACE3#4723]
I have a weapon mod and the weapon overheat to quickly with standard 5.56 (1 bar after 1 mag) and even quicklier with its on modded ammo (1.5 bar after 1 mag), witch base class is standard 5.56; the weapon weight is about 4kg. What can I do ?

**Comment by jonpas** [comment]
You can adjust your mod with config values from ACE3 API - http://ace3mod.com/wiki/framework/overheating-framework.html

**Comment by kamkill01011** [comment]
Thank you for your quick responce but what is "ace_overheating_slowdownFactor" does is slow down overheating ? and what is "ace_overheating_dispersion" is it heat dispersion ? whitch one should I use ?

**Comment by kamkill01011** [comment]
I was testing ace_overheating_slowdownFactor and ace_overheating_dispersion for hours until I decided to test ace_overheating_allowSwapBarrel = 0; and realise that it does nothing (I'm still able top change the barrel). I'm placing it inside my weapon class : 
class SG553: SG55x {
    scope = 2;
    ace_overheating_allowSwapBarrel = 0;
    ...
maybe I misunderstod something, I don't know where else I should place it. Do you any idea ?

**Comment by PabstMirror** [comment]
Actual weapon temp is infulanced by 2 things
- Total weight of gun (we estimate barrel mass from this)
4 kg should mean your `"WeaponSlotsInfo" >> "mass"` is around 88?

- Heat from each bullet is based on muzzle energy (1/2 * mass * velocity^2)
Mass should be from `ACE_BulletMass` on ammo which is set for `B_556x45_Ball`, so as long as your custom ammo is inheriting from that it should be fine. I think initSpeed is on the magazine, a high speed/pressure ammo is going to heat up more.

Honestly 1 bar for a 30 round mag dump doesn't seem unreasonable and should be reasonably close to vanilla guns.  You could tweak the mass up a little.

**Comment by kamkill01011** [comment]
Thank you very much that's exactly what I was looking for. Yes my base weapon mass value is 90, but I also have a shorter and lighter version and this one was overheating way too much; my bullet was inheriting from BulletBase so I had to add ACE_BulletMass param and it fixed my problem, but what else for is ACE_BulletMass use ?  dose it also afect the lethality of the bullet ?

That is off the subject but I think the M249 is may be too heavy (11.79 kg empty).

Thank you again for your answer it really helped me.

**Comment by commy2** [comment]
>dose it also afect the lethality of the bullet ?
No.

**Comment by PabstMirror** [comment]
I highly recomend inheriting from `B_556x45_Ball` instead of `BulletBase `.
You can see all the config additions we make here: https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgAmmo.hpp#L9-L26

This primarily effect advanced ballistics.

**Comment by dedmen** [comment]
@terriblephrases 
>as it expands inwards and squeezes the bullet.

Nope. It expands outwards. Diameter get's bigger and the gases slip past. For it to expand inwards you'd have to compress the outside so that it can't expand outwards. Which usually isn't the case for gun barrels.

**Comment by terriblephrases** [comment]
Ah, thanks.

**Comment by DJ-Reticuli** [comment]
Problem with overheating in ACE is it wildly varies between guns and ammunition for no rhyme or reason.  Some overheat very quickly, while others are hard to overheat.  Almost seems like guns have arbitrary settings for overheating that's independent of caliber, muzzle velocity, and whether it's an open bolt or not.
