### ISSUE TITLE
Adding ammoxbox to cargo via editor/script?

### ISSUE THREAD

**Issue by DanielLarusso** [acemod/ACE3#4725]
Hey,

I need a little helping hand with the cargo stuff...
I try to add ammoboxes into a vehicles cargoslots via editor/script but I don't know how
nor if it's even possible.

Any suggestions?

greetings,
daniel

**Comment by DanielLarusso** [comment]
nobody? So it's not possible to add stuff to the ace logistic cargo?

**Comment by jonpas** [comment]
You can use `[object, vehicle] call ace_cargo_fnc_loadItem`. Although it's not public at the moment, we don't expect any changes in the near future.

**Comment by PabstMirror** [comment]
That should only be called on a single machine as it has global effects.
