### ISSUE TITLE
Maybe some changes to smokes? Question/Request

### ISSUE THREAD

**Issue by mihal190** [acemod/ACE3#4729]
as i remeber ACE team changed something in smokes... if no maybe its time to? we have nice that go with weather, nice ?? imagine you are fighting in city in hills you throw smoke to cover injured people, but smoke goes with wind... Maybe 2 versions of smoke normal that goes with wind. and second that create a "ball" of smoke that igonre the wind. i dont know is it realistic, probably not, but this can improve gameplay

**Comment by jonpas** [comment]
Already done, check `ace_particles` in `optionals` folder.

**Comment by mihal190** [comment]
as i remeber they have nice particles, and changed the time of smoke, but this still "goes on wind as f*ck"

**Comment by jonpas** [comment]
We won't be doing smoke that's not impacted by wind, out of scope, not realistic. Not sure how something unrealistic like that can improve gameplay?

**Comment by mihal190** [comment]
okay, unrealistic it can make smoke more usefull, not only for  mark the CAS or MEDEVAC it could be used for cover, when you are under fire

**Comment by BaerMitUmlaut** [comment]
There is wind. The particles don't move on their own.

**Comment by Glowbal** [comment]
Smoke is affected by wind. We won't change that within ACE. Since this is A) a feature request and B) not within the scope of ACE3, I will close this.

Thank you for your request. If you have additional questions, feel free to reopen (however we wont change our stance the smoke request).
