### ISSUE TITLE
Range Card Not Showing any info

### ISSUE THREAD

**Issue by NeoFraX** [acemod/ACE3#4733]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.1.2.161105` (stable)
**ACE3 Version:** `3.8.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@JSRS4 Apex`
- `@MCC Sandbox4`

**Description:**
- My range card is not showing any of the required info for me to adjust my shot. Yes I used the Vector 21 to get a range to my target (Exactly 100m away). Still nothing on the range card. Any Help?
Image of what the range card looks like: http://imgur.com/HXqfAtr

**Steps to reproduce:**
- Open the range card.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Placed Modules:**
- None

**Comment by kripto202** [comment]
You may want to check your modules. You may not have advanced ballistics turned on for snipers.

**Comment by bux578** [comment]
RPT from that session please.

**Comment by NeoFraX** [comment]
Okay so I debugged it in the ace options, here is the paste: http://pastebin.com/YQ6YpCCE
And I have advanced ballistics turned on :)

**Comment by bux578** [comment]
That's not the RPT file.

**Comment by NeoFraX** [comment]
http://pastebin.com/Xhgv4aLu

**Comment by ulteq** [comment]
> And I have advanced ballistics turned on :)

You don't: `ace_advanced_ballistics_enabled - false`
