### ISSUE TITLE
Blood error

### ISSUE THREAD

**Issue by kripto202** [acemod/ACE3#4739]
**Arma 3 Version:** 1.66 
**CBA Version:** stable
**ACE3 Version:** stable

Just reporting error
http://pastebin.com/npvduUmZ

![20161201162523_1](https://cloud.githubusercontent.com/assets/8568526/20813331/30d511b0-b7e3-11e6-9c24-00ddeadd02c0.jpg)

**Comment by jonpas** [comment]
Please fill out the issue template as requested. You are definitely not running only ACE3 and CBA.

**Comment by kripto202** [comment]
After switching to ace and cba only, i still got the same error.

**Comment by kripto202** [comment]
![20161201193129_1](https://cloud.githubusercontent.com/assets/8568526/20818611/c6359ca2-b7fc-11e6-966c-6cb10d4d8c5a.jpg)
![20161201193132_1](https://cloud.githubusercontent.com/assets/8568526/20818613/c8c9a0d0-b7fc-11e6-85bb-6d22d7398ffd.jpg)
![20161201193119_1](https://cloud.githubusercontent.com/assets/8568526/20818621/d3304b96-b7fc-11e6-8b62-62667ac10730.jpg)

medical modules
