### ISSUE TITLE
Error when using self interact without a mine detector

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#4741]
**Arma 3 Version:** `1.66` stable
**CBA Version:** `3.1.2` stable
**ACE3 Version:** `3.8.2` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When opening the self interact menu without a mine detector the aforementioned addon throws an error

**Steps to reproduce:**
- Self interact while not having a mine detector

**Where did the issue occur?**
- Editor

**Placed Modules:**
- None

**RPT log file:**
- https://gist.github.com/alganthe/b163165b84136507a7bde9353a2e14de line 762

**Comment by commy2** [comment]
```sqf
11:38:36 Error in expression <[];
};
ace_minedetector_detectorConfigs setVariable [_detectorType, _detectorCon>
11:38:36   Error position: <setVariable [_detectorType, _detectorCon>
11:38:36   Error Reserved variable in expression
11:38:36 File z\ace\addons\minedetector\functions\fnc_getDetectorConfig.sqf, line 19
11:38:37 Error in expression <[];
};
ace_minedetector_detectorConfigs setVariable [_detectorType, _detectorCon>
11:38:37   Error position: <setVariable [_detectorType, _detectorCon>
11:38:37   Error Reserved variable in expression
11:38:37 File z\ace\addons\minedetector\functions\fnc_getDetectorConfig.sqf, line 19
```
