### ISSUE TITLE
Pain in basic mode

### ISSUE THREAD

**Issue by OnkelDisMaster** [acemod/ACE3#475]
**Mods:**
* CBA A3 latest version
* ACE3
* TFAR
* BWMod
* RHS:Escalation

**Placed ACE3 Modules:**
* None

**Description:**
After giving morphine, the pain dissapears for a moment, then it comes back and you can give an infinite amount of morphine. 

**Steps to reproduce:**
Set Basic mode, then wound a person, then give morphine.

**Where did the issue occur?**
Multiplayer, after fully bandaging the other player

**Comment by KoffeinFlummi** [comment]
Had a similar issue myself with blood bags. Something overwrites `setVariable`...

**Comment by OnkelDisMaster** [comment]
I noticed, that if you set "Prevent instant death" to "no" the problem is fixed.

**Comment by kripto202** [comment]
also having prevent instant death on, the people who are knocked out, they take more than a clip to kill

**Comment by Glowbal** [comment]
Should be fixed in #861
