### ISSUE TITLE
Fuel sources

### ISSUE THREAD

**Issue by LawnDartLeo** [acemod/ACE3#4752]
**Arma 3 Version:** current with Steam
**CBA Version:**  current with Steam Workshop
**ACE3 Version:**  current with Steam Workshop

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Not relevant

**Steps to reproduce:**
Not relevant

**Where did the issue occur?**
Not relevant

**Placed Modules:**
Not relevant

**RPT log file:**
Not relevant

How about making the flexible fuel bladders and other containers useable as a source in the field (loadable with logistics and accessible via fuel interaction menu)

- FlexibleTank_01_forest_F
- FlexibleTank_01_sand_F
- StorageBladder_01_fuel_forest_F
- StorageBladder_01_fuel_sand_F
- B_Slingload_01_Fuel_F
- Land_CanisterFuel_F
- Land_Pod_Heli_Transport_04_fuel_F

**Comment by alganthe** [comment]
`B_Slingload_01_Fuel_F` OK
`Land_Pod_Heli_Transport_04_fuel_F` OK
`StorageBladder_01_fuel_forest_F` OK
`StorageBladder_01_fuel_sand_F` OK
`FlexibleTank_01_sand_F` NOPE
`FlexibleTank_01_forest_F` NOPE

only the two small flexible tanks don't have refueling enabled on them.

**Comment by LawnDartLeo** [comment]
Is this by default? I have no ACE interaction with any of the items noted

I guess I'll take that discussion to the BI forums or Slack.

If I may ask, why not on the small bladders?

**Comment by alganthe** [comment]
Yes this is by default.
I'm not the designer of the module, I won't be able to answer that.

**Comment by LawnDartLeo** [comment]
Seems i need to just take this to other more appropriate outlets for discussion. Thanks.
