### ISSUE TITLE
Update makefile for 64-bit DLLs

### ISSUE THREAD

**Issue by thojkooi** [acemod/ACE3#4758]
Rebuild all extensions for the 3.9.0 release.

**Comment by PabstMirror** [comment]
Tag #4764

- [ ] Update makefile for 64 bit builds

**Comment by bux** [comment]
status?

**Comment by jonpas** [comment]
This has all been done, no?
https://github.com/acemod/ACE3/blob/master/extensions/CMakeLists.txt#L18
