### ISSUE TITLE
Adds compatibility between ACE3 and RHS switched

### ISSUE THREAD

**Issue by eststar** [acemod/ACE3#4759]
**Arma 3 Version:** `1.66` (stable )
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.x.x` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
-'RHSmod: usaf'
-'RHSmod: afrf'
-'@ACE Compat - RHS United States Armed Forces'
-'@ACE Compat - RHS Armed Forces of the Russian Federation'

**Description:**
- ace and rhs compatibility error occurs and automatically disconnected. I found the uploaded files at the steam workshop of @ACE Compat - RHS United States Armed Forces and @ACE Compat - RHS Armed Forces of the Russian Federation had been switched.  I solved by take out files and make new addon folders. 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer 

**Placed Modules:**
- some medical modules and ballistics etc.

**Comment by PabstMirror** [comment]
There are several entries on steam workshop called "RHS ACE3 Compatibility", not all of them have updated
The 2 official ones that are created by "acemod" are
http://steamcommunity.com/sharedfiles/filedetails/?id=773131200
http://steamcommunity.com/sharedfiles/filedetails/?id=773125288

Please check that you are subscribed to those 2,
If still having problems please upload an rpt.

**Comment by PabstMirror** [comment]
opps, I guess tool had them mixed up

**Comment by eststar** [comment]
yeppp still looks like this img.

![image](https://cloud.githubusercontent.com/assets/24565245/21212773/0cd06ce2-c2d3-11e6-8903-3d5f4a8fb5e6.png)

watch the folder name and file name.

**Comment by coachwn** [comment]
Just found this problem today....http://steamcommunity.com/sharedfiles/filedetails/?id=818747036

Any idea on a fix?

**Comment by PabstMirror** [comment]
Just fixed the uploads. Please let me know if you have any problems

**Comment by coachwn** [comment]
so download from the steam community links?

**Comment by PabstMirror** [comment]
@coachwn - If you are using workshop that should be updated automatically.

If you are manually updating mods, check for where you have `ace_compat_rhs_afrf3` and make sure it's updated from the version in the optional's folder in ace.

**Comment by coachwn** [comment]
@PabstMirror already done and getting same error. Download is from Github on the server and the client and still getting same error.

For now we are going to roll back to the last version before the most recent update. We can't track this down right now.

**Comment by PabstMirror** [comment]
Uploading a RPT would be helpful
Often an old copy of `ace_compat_rhs_afrf3.pbo` is hiding either in `@ace` or a `@rhs` folder.

**Comment by coachwn** [comment]
Will see what I can do...I deleted the @ace folder entirely on the server and the client before we restarted it. Will look in the @RHSAFRF folder now.

**Comment by coachwn** [comment]
@PabstMirror This may not be a problem...checking on a possible solution since this may be due to an internal addon.

**Comment by coachwn** [comment]
@PabstMirror The error is due to the internal addon for our community. The mission maker put the older version files into the addon. We have to deconstruct that file and pull them out so we can move ahead.

**Comment by eststar** [comment]
It looks nice and clear now. Thank you for nice work!
