### ISSUE TITLE
Rebuild ACE3 DLLs for x64

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#4764]
**Arma 3 Version:** `1.67` (dev)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.8.3` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- ACE mod dont work on 64-bit Arma 3.

**Steps to reproduce:**
- Run ACE and CBA on a dev version of Arma 3.

**Comment by bux578** [comment]
@GalNa thx
