### ISSUE TITLE
Adv. Fatigue — Lowering weapon

### ISSUE THREAD

**Issue by Armilio** [acemod/ACE3#4767]
**Arma 3 Version:** `1.66 (stable )
**CBA Version:** `3.1.2` (stable )
**ACE3 Version:** `3.8.3` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- Acex
- SacVentral
- TaskForceRadio

**Description:**

I don't know if it's a bug or not, but... lower weapon now save something like 75% of the stamina usage. Holding the weapon low i can run basically forever in a flat terrain. It's supposed to work this way? Frankly i think it's too much.

**Steps to reproduce:**
- Useless to say

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer) / 

**Placed Modules:**
- Advanced Fatigue

**Comment by Armilio** [comment]
Sorry for the up, but I want to clarify that i just want to know if it's a setting there to stay or not. Because, if yes, i will throw away my clan adv. fatigue settings and start testing for new ones. Thanks.

**Comment by BaerMitUmlaut** [comment]
Yes, this is on purpose (75% sounds a bit high but it depends on gear weight and such). The added factor comes both from having the weapon low ready and from the movement speed - it's around 20% faster than jogging with your weapon lowered. Having it high ready is even more taxing.

The idea is to use lowered for longer movements, low ready in combat and high ready only when necessary, while clearing buildings and such.
