### ISSUE TITLE
Compatibility with ASDG Joint Rails

### ISSUE THREAD

**Issue by OnkelDisMaster** [acemod/ACE3#477]
The new attachments like scopes and pointers are incompatible with ASDG Joint Rails at the moment, which is making the player unable to use them in any way. ASDG changes the compatibleItems on all weapons, including the vanilla ones.

**Comment by commy2** [comment]
http://acemod.github.io/ACE3/wiki/user/how-to-report-an-issue.html

**Comment by OnkelDisMaster** [comment]
Well if the first one isn´t enough:

**Mods:**
* CBA
* ACE
* ASDG Joint Rails
* shitload of weapon addons that use ASDG JR :)
* BWMod
* RHS Escalation
* FHQ Accessories
* IanSky Optics

**Placed ACE3 Modules:**
None

**Description:**
The new ACE3 scope are not compatible with any of the Weapons, because they are not compatible with ASDG Joint rails.

**Steps to reproduce:**
Try to put an ACE3 scope on a weapon of your choice, which is configured for ASDG JR. 

**Where did the issue occur?**
MP/SP on every weapon, since almost all of the weapon mods utilize ASDG JR

**Comment by jonpas** [comment]
I think it's something that could much easily be done on ASDG JR side, Robalo has a bunch of custom compatibility configs as it is already.

**Comment by commy2** [comment]
You could make a pull request if you know how this is done. We would really appreciate if we get help with this stuff.

**Comment by bux578** [comment]
Can this be closed?

**Comment by OnkelDisMaster** [comment]
Yes i think so.
