### ISSUE TITLE
"SAFE MODE" hard locked to F key-RHS US/RU

### ISSUE THREAD

**Issue by Giorgy32** [acemod/ACE3#4771]
**Arma 3 Version:** `1.66.139586` (stable / rc / dev)
**CBA Version:** `3.2` (stable / dev + commit hash)
**ACE3 Version:** `3.8.3` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
-@RHS_US
-@RHS_RU
-@ACE_RHS_compatibility (taken from ACE3 optional and put as additional mod.
The Ready for use *3 files from Play with Six show outdated ADR settings-and send me to desctop-although the mentioned "safe mode" bug(?) appears just the same)  
**Description:**
- The F button 95% of times doesnt change firemodes on weapon but stucks the weapon in "safe mode"
Even if i changed the keys via Configure addons->ACE weapons and put it to i.e. Shift+S (for "safe")..the actual "F" button still keeping/returning the weapon in "Safe mode" -even if i erase it-
 To actually fire i should keep F pressed+L mouse button (lolz)

PS *I should add this also..on Vanilla units everything works as expected
**Steps to reproduce:**
- Put an RHS unit on map (doesnt matter on M4 or AK weapons)
-Fire and/or try to change firemode and fire again

**Where did the issue occur?**
- I had only chance to test on Singleplayer Editor

**Placed Modules:**
- none
**RPT log file:**
- http://pastebin.com/fLNavr1Z

**Comment by PabstMirror** [comment]
If it only effects RHS units, I suspect it's RHS's saftey mode for their weapons:

In-game, Hit Escape, RHS-Game Options and check the "Disable Weapon Safemode"
![image](https://cloud.githubusercontent.com/assets/9376747/21249052/f9a5d1ba-c300-11e6-9218-baf040205747.png)

I think it will take a mission-restart to have effect.

RHS's safe mode will change the weapon name to safe, and change the zeroing to red.

**Comment by Giorgy32** [comment]
I haven't tried that yet (because i m n00b again after 2 years of ArmA absence).
I have high hopes for your solution tho....although even if it works-the guys responsible
for the ACE_RHS compatiblity *department should probably  write some lines to disable RHS_SAFE 
feature when ACE is detected (imho)
Anyway..i l try the solution later..and right back to you guys.
Thank you

**Comment by commy2** [comment]
>the guys responsible for the ACE_RHS compatiblity 

We are explicitly not responsible for that, we host it out of courtesy for the community. That being said, if someone provides a solution as pull request, we would gladly merge it if it's done right.

**Comment by Giorgy32** [comment]
@We are explicitly not responsible for that

I m fully aware about that..and also find the chosen phrase "out of courtesy" most appropriate.
Thanks again
