### ISSUE TITLE
[Idea/Request/Question] Medical items?

### ISSUE THREAD

**Issue by mihal190** [acemod/ACE3#4773]
Okay so first of all i going to ask, next give idea. We have Unconscious soldier, and what? we have a medic, that come and use 1 MedKit or kinda that revive our squad member. of course i can setup we need to previously "Stabilize" but true is that we dont stabilize his at this point, maybe a "Bandaged" option will be more accurate. I have just a question is it possible to make waking up patient very hard? We have TONS of medical that is useless when we have Unconscious/Reive module. So we are using only a presonal medkit that revive our squad member, restore all blood, and more. My question is simple, you going to do something with that later? or i need to dig deeper for myself?

**Comment by Glowbal** [comment]
Hi @mihal190. We are currently working on our medical rewrite, which addresses a lot of the problems we have identified with the medical components. You can follow our progress here: https://github.com/acemod/ACE3/projects/2
