### ISSUE TITLE
Arma 3 ACE Problem  ["ace_compat_rhs_afrf3","ace_compat_rhs_usf3"] 

### ISSUE THREAD

**Issue by armamate2000** [acemod/ACE3#4777]
**Arma 3 Version: most up to date version
**CBA Version: 3.1.2 
**ACE3 Version:3.8.3 

**Mods:**
ace,@ACE Compat - RHS United States Armed Forces,@ACE Compat - RHS Armed Forces of the Russian Federation,TFR,F-18 Hornet mod,RHS:USAF,RHS:AFRF,CUP Terrains,NATO SF and Spetsnaz weapons,FHQ Weapons,Spec 4 gear,Cup Units,Cup Weapons,Cup Vehicles,Advanced sling loading,Advanced rappeling,Nimitz,Hidden identity pack,CBA

MY COMMAND LINE : @CBA_A3;@RHSUSAF;@RHSAFRF;@spec4gear.v4.6;@NATO_Rus_Weapons;@CUP_Weapons;@CUP_Vehicles;@CUP_Units;@AdvancedSlingLoading;@FHQ_Weapons;@JS_JC_FA18;@Nimitz;@HiddenIdentityPackV2;@ace;@CUP_Terrains;@task_force_radio;@AdvancedRappelling;@ACE Compat - RHS United States Armed Forces;@ACE Compat - RHS Armed Forces of the Russian Federation

**Description:**
On my server that i am hosting through i have installed the new version of ace with the rhs compatibility files  which i got from armaholic the mods above are what i am running on the server every thing els works accept for ace i got into my server past the player selection then right before it loads me in i get Client/Server addon mismatch.Client has extra addons  ["ace_compat_rhs_afrf3","ace_compat_rhs_usf3"] and then it kicks me from the server.
Please note I also have the compat files selected in my arma 3 launcher when i launch arma 3.

**Steps to reproduce:**
have all mods selected launch arma 3 with mods and compat files selected join server = ACE error.

**Where did the issue occur?**
on my server which i am hosting through Wombat servers

**Placed Modules:**
"none"
**RPT log file:**
10:41:20 [ACE] (common) INFO: Settings initialized.
10:41:20 [ACE] (common) INFO: 4 delayed functions running.
10:41:20 WARNING: ace requires ace_compat_rhs_afrf3 (@compat_rhs_afrf3) at version [3,8,3,14] (or higher). You have none.
10:41:20 WARNING: ace requires ace_compat_rhs_usf3 (@compat_rhs_usf3) at version [3,8,3,14] (or higher). You have none.
10:41:21 Strange convex component01 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component02 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component13 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component32 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component33 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component35 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component37 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component40 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component45 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component53 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component61 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component71 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component91 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component92 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component93 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component103 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component111 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component129 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component131 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component135 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component141 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component160 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component204 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component217 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component254 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component260 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component295 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component309 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:41:21 Strange convex component315 in a3\rocks_f\sharp\sharprock_wallv.p3d:geometryFire
10:43:37 Client: Remote object 3:0 not found

**Comment by PabstMirror** [comment]
`Client has extra addons`
It sounds like client has the RHS compats, but the server doesn't.
Could you upload the full rpt of the server

**Comment by armamate2000** [comment]
Client meaning me or the server exactly sorry im new to this stuff i am just learning . and sure thing 1 minute

**Comment by armamate2000** [comment]
it wouldn't let me upload it in the comment area so i uploaded it via google drive  https://drive.google.com/open?id=0B-9-Yb5RZxHoTERQeV9FWTV0QTA

**Comment by PabstMirror** [comment]
Because of the spaces in the mod folder `@ACE Compat - RHS United States Armed Forces;` it gets ignored and is not loaded.  I think this can be fixed by wrapping the entire mod list in quotes like this:

`mod="@CBA_A3;@RHSUSAF;@RHSAFRF;@spec4gear.v4.6;@NATO_Rus_Weapons;@CUP_Weapons;@CUP_Vehicles;@CUP_Units;@AdvancedSlingLoading;@FHQ_Weapons;@JS_JC_FA18;@Nimitz;@HiddenIdentityPackV2;@ace;@CUP_Terrains;@task_force_radio;@AdvancedRappelling;@ACE Compat - RHS United States Armed Forces;@ACE Compat - RHS Armed Forces of the Russian Federation"`

**Comment by armamate2000** [comment]
ok i will give that a try and report back to you in a few minutes

**Comment by armamate2000** [comment]
This worked Thanks i really Appreciate it !!

**Comment by LoneHeaven** [comment]
I'm having the same problem on my server and I've tried this just to try, but it doesn't work. Any other suggestions?

**Comment by linuxlocalinor** [comment]
I had same issue, I re-copied all the mod keys over to keys and Keys, fixed my issue (same message as above)

**Comment by linuxlocalinor** [comment]
In the root of the A3 server directory
