### ISSUE TITLE
[REQUEST] some ideas

### ISSUE THREAD

**Issue by mihal190** [acemod/ACE3#4781]
1 I dont know, maybe you have plans for it or its impossible whatever, Reloading Static MG or Veh ones :). we have to shoot all the ammo to reload, thats kinda stupid, maybe is it possible to be able switch magazine or draw from another or whatever

2 Next Idea is adding Head light for helmets, arma 3 base have plenty of these lights and useless lasers

3 Another one, bring from Alpha Lean in vehicle: https://www.youtube.com/watch?v=fmaheazu_Kg

4 Maybe a some improvments to disarming Ied section? like you have a 3D model on screen with some cables and you need to cut one of them, if have a ToolKit or Defusing kit, maybe this good will be a little glowing?

5 Next maybe you can fix or look at "free aim Feature" and fix it or make own

6 Maybe a new animation for Magazine check?

**Comment by kripto202** [comment]
#3594 any requests should go there
