### ISSUE TITLE
Some explosives fall inside rocks.

### ISSUE THREAD

**Issue by CamoSteve** [acemod/ACE3#479]
**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
* When placing explosives on rocks, they tend to fall inside.

**Steps to reproduce:**
* Find a big rock (the rocks on the sides of cliffs and shores tend to exhibit this)
* Place different types of explosives on it
* Watch some explosives fall inside.
* Screenshot 1: http://cloud-4.steamusercontent.com/ugc/531764507028826392/4EF6E0F778DC47B104D14A95FE898E566D736366/
* Screenshot 2: http://cloud-2.steamusercontent.com/ugc/531764507028826573/ED008307385D7C985B261CBB57EAE06E74BCC605/

**Where did the issue occur?**
* Singleplayer

**RPT log file:**
* none

**Comment by James2464** [comment]
You could ask BIS for a PhysX LOD to be added to the rocks as it's very quick. You simply duplicate the geometry LOD and remove the mass.

**Comment by CamoSteve** [comment]
@James2464  It is not my intention to deflect work, but I would rather have someone else who knows what they are doing to go report to BIS.

**Comment by James2464** [comment]
Vote/edit here: http://feedback.arma3.com/view.php?id=23725

**Comment by bux578** [comment]
Added: https://github.com/acemod/ACE3/blob/master/documentation/development/arma-3-issues.md

**Comment by CamoSteve** [comment]
:+1:  voted

**Comment by CorruptedHeart** [comment]
I'm going to close this issue since it seems to be a BIS issue and there's nothing we can do about it.
