### ISSUE TITLE
Wont complete interaction/will not allow further interaction on anything ACE

### ISSUE THREAD

**Issue by Aceboomdog** [acemod/ACE3#4796]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@MCC Sandbox 4- Mission Making The Easy Way`
- `@TFW Radios 1.2.2`
- `@ACEX`
- `@CUP Weapons`
- `@CUP Units`
- `@task_force_radio
- `@ShacTac User Interface`
- `@Marine Expeditionary Force`
- `@CUP Vehicles`
- `CUP Terrains-Core`
- `@CUP Terrains-Maps`
- `@Cha Lav25`
- `@NATO_Rus_Weapons`
- `@USMC_mas`

**Description:**
Whenever I use self interact or interact on others the menu gets brought up but when I release my keybinding the red circle stays and I can not execute the initial action or any further actions.

**Steps to reproduce:**
Self interact or Interact and the bug will occur 

**Where did the issue occur?**
Dedicated

**Placed Modules:**
ACE and MCC

**RPT log file:**
=====================================================================
== 

[Arma3Launcher_Exception_20161231T043741.txt](https://github.com/acemod/ACE3/files/679490/Arma3Launcher_Exception_20161231T043741.txt)

**Comment by PabstMirror** [comment]
Same as #4776

Does this happen on first load of a mission or only on restarts?
From what I can tell, MCC is trying to read keybinds before postInit finishes.

**Comment by Aceboomdog** [comment]
It would happen at any time I tried using it but Idk why I redownloaded ACE
for the 8th time and it worked and so far no issues

**Comment by Aceboomdog** [comment]
Same issue is happening... It worked at first for a while I put earplugs in but then when I went into medical menu during a mission ( replicating glitch right now then trying to find RPT file for you guys for a possible minor change? I dont know but the bug came back.

**Comment by commy2** [comment]
Upload RPT

**Comment by PabstMirror** [comment]
Heart of this issue is errors from MCC's code. I would report it to them.
