### ISSUE TITLE
ACE Incendiary Grenades not working correctly on dedicated servers

### ISSUE THREAD

**Issue by HarryA3G** [acemod/ACE3#4798]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.8.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@rhsafrf`
- `@rhsgref`
- `@rhsafrf`
- `@task_force_radio`
- `@ALiVE`

**Description:**
- Incendiary grenades fail to do constant damage to crates on dedicated servers.
- This was also tested and reproduced by @BaerMitUmlaut on a very light mod setup with the latest ACE.

**Steps to reproduce:**
- Place down any vanilla ammo crate in a dedicated server and throw an AN-M14 Incendiary grenade at it.
- The initial detonation of the grenade will slightly damage the crate, but will then fail to cook off/destroy the crate itself when the thermite effect begins (however this still does damage units and people)

**Where did the issue occur?**
- Dedicated only

**Placed Modules:**
- None

**RPT log file:**
- None

**Comment by BaerMitUmlaut** [comment]
Pic related:
![](http://i.imgur.com/8qHs052.jpg)

Works fine with local ammo boxes.

**Comment by PabstMirror** [comment]
Should be fixed via #4799
