### ISSUE TITLE
Medic gets "stuck" after ordering "Stop" or "Find cover"

### ISSUE THREAD

**Issue by Skully71** [acemod/ACE3#4805]
**Arma 3 Version:** `1.66.139586` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.8.3` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
When ordered to "Stop" or "Find cover" and someone requests the medic, it'll be unable to execute its `doMove`. This will result in `QGVAR(movingToInjured)` being set to `true` while the medic is not moving (nor going to move) to the injured.

**Workaround:**
Order the medic to move to the injured yourself. (This however will not work if you are down.)

**Steps to reproduce:**
1. Make a squad with at least 1 Combat Life Saver and a Rifleman.
2. Order the medic to "Stop".
3. Shoot the Rifleman in the foot.
4. Order the medic to move to another location (*not* the Rifleman).
5. Medic is now "stuck".
6. Shoot the Rifleman in the foot again to observe the bug.

**Where did the issue occur?**
- [ ] Dedicated
- [ ] Self-Hosted Multiplayer
- [ ] Singleplayer
- [x] Editor (Singleplayer)
- [x] Editor (Multiplayer)
- [ ] Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
Let me know if you need anything from it. :)

**Comment by Skully71** [comment]
Patch is inbound.

**Comment by Skully71** [comment]
It would probably be better to move the whole `QGVAR(movingToInjured)` switching into the state machine, but this forms a step in the right direction.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 160 days without any activity.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
