### ISSUE TITLE
No zeroing for tracked vehicles w/ MG or Mk19

### ISSUE THREAD

**Issue by lolkij** [acemod/ACE3#4808]
**Arma 3 Version:** `3.66` (stable)
**CBA Version:** `3.1.2.161105` (stable)
**ACE3 Version:** `3.8.2.13` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHS`/`@CUP` (or both)

**Description:**
- Same bug like this https://github.com/acemod/ACE3/issues/4176, but now it is relating only for tracked vehicles w/ MG or Mk19 (only with an iron sight, no optics)
https://wtf.jpg.wtf/2d/9a/1483617025-2d9a600cc650ea9a8c29dacdd7af0d3f.jpeg

**Steps to reproduce:**
The zeroing value is not visible for the gunner on М113 (RHS/CUP) or Bulldog (CUP), but when you pressing PgUp/PgDwn - you can hear the "clicks".

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- None.

**RPT log file:**
- Not relevant

**Comment by PabstMirror** [comment]
Found a bug with our RHS compat.

`"CUP_B_M113_USA" >> "Turrets" >> "MainTurret" >> "ace_fcs_Enabled" = 1;`
CUP will need to update their compat (fcs should be 0 for manually operated guns)

**Comment by PabstMirror** [comment]
Our RHS compat will be fixed in 3.9.1
I passed info on the CUP m113 conflcit to them
