### ISSUE TITLE
[Request/Question]

### ISSUE THREAD

**Issue by tierneyboy14** [acemod/ACE3#4809]
[**Arma] 3 Version:** `x.xx` (stable)
**CBA Version:** `3.x.x` (stable)
**ACE3 Version:** `3.x.x` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Could you add in a key bind for the detonate all option for explosives just to make it quicker to detonate them as going trough the menu can be a bit slow to do and when trying to use the deadmans hand with a car bomb i find myself overshooting the target trying to blow it up through the menu. Not very important but it would be nice.

**Comment by commy2** [comment]
#3594
