### ISSUE TITLE
Captive escort settings / Questions about Repair and Medical Vehicles

### ISSUE THREAD

**Issue by celticalliance** [acemod/ACE3#4810]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` 
**ACE3 Version:** `3.8.3` 

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
1. Is there a way to disable the option to escort captives by way of using setVariable in the unit's init? We would like to disable escorting of specific units but by scripting instead of using any applicable modules. How do we proceed to get this done?

2. Can any of you tell me how to use setVariable in a vehicle's init to set a vehicle as a medical vehicle and some other vehicles as repair vehicles?

3. How exactly do we have to use the vehicles set up as medical and repair vehicles? What are the requirements to use these vehicles as such?

**Placed Modules:**
- None

**Comment by PabstMirror** [comment]
1. Not sure if this is possible.  You can see the condition checks here https://github.com/acemod/ACE3/blob/master/addons/captives/functions/fnc_canEscortCaptive.sqf

2. `this setVariable ["ace_medical_medicClass", 1]` // make any vehicle a medical vehicle
`this setVariable ["ACE_isRepairVehicle", 1]`  // make any vehicle a repair vehicle

3. It largely depends on the settings used. For example, you can only allow "Full Repair" when near a repair vehicle. Similar options exist for medical treatments.

**Comment by celticalliance** [comment]
Thank you for the reply Pabst.

As for question #1, I mistook the intention of our mission creators in that regard. They want to know if it is possible to use setVariable to disable taking the unit prisoner. Some people like to take a certain unit prisoner and place him somewhere where it can't be found, which breaks a feature in the mission, and they want to prevent it by disabling the take prisoner option.

**Comment by celticalliance** [comment]
Also, and this is just a sidenote, it would be extremely helpful if there was a list with this sort of info. 

Right now we are going through all the code but don't even know where to start to find this info. It is quite frustrating to be honest.

**Comment by celticalliance** [comment]
Pabst, we figured out a solution to our issues. Thank you for your help :)
