### ISSUE TITLE
EntityKilled

### ISSUE THREAD

**Issue by Zeven90** [acemod/ACE3#4811]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.8.3` (stable )

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
ACE interferes with the "EntityKilled" event.
_killed will often equal _killer even when shot by somebody else.
 
I believe it has to do with "handleDamage" event since if all "handleDamage" handlers are removed then "EntityKilled" will trigger with the expected parameters.

**Steps to reproduce:**
Run this code then shoot somebody.

_id = addMissionEventHandler ["EntityKilled", {
    params ["_killed", "_killer", "_instigator"];
    hint format["_killed : %1, _killer: %2, _instigator: %3", _killed, _killer, _instigator];
 }];

**Where did the issue occur?**
Editor (Singleplayer) 

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.
ACE Revive (Needs to be enabled).

**Comment by commy2** [comment]
Nothing we can do about this. Reason for this is the customized medical system in ACE.

**Comment by PabstMirror** [comment]
See https://github.com/acemod/ACE3/issues/3790#issuecomment-219654741

Using `ace_medical_lastDamageSource` getVar you should be able to determine correct killer.
Keep in mind that var is only set where target is local

**Comment by bux** [comment]
#3790
