### ISSUE TITLE
Tactical Ladder script error

### ISSUE THREAD

**Issue by dedmen** [acemod/ACE3#4814]
**Arma 3 Version:** `1.66.139.630` (profv3)
**CBA Version:** `3.8.3` (stable)
**ACE3 Version:** `3.1.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@acex`

**Description:**
- Script error even when no Ladder anywhere near
- Probably related to #4017
- First that script shouldn't even be triggered by just right-clicking without a Ladder anywhere near
- Second `animate` should always return Nothing according to BIKI so the error should always be triggered. I don't know why it sometimes apparently returns something that count accepts as a bool.

**Steps to reproduce:**
- Open a completly empty 3DEN mission.
- Start the mission without any playable unit
- When in a camera hovering over the map press right-click.
- Error is triggered

**Where did the issue occur?**
- Editor (Singleplayer)

**RPT log file:**
too lazy
```
20:05:16 Error in expression <tate", 0];

{
ace_tacticalladder_ladder animate [_x, 0];
} count ["extract_1","e>
20:05:16   Error position: <animate [_x, 0];
} count ["extract_1","e>
20:05:16   Error Type Nothing, expected Bool
20:05:16 File z\ace\addons\tacticalladder\functions\fnc_cancelTLdeploy.sqf, line 18
```

**Comment by PabstMirror** [comment]
Full RPT would be helpful.
Just like #4017, this is probably caused by a initPost failure and unrelated to this module.
Error will occur if `ace_tacticalLadder_ladder` is nil. Could you check what this variable is?

**Comment by dedmen** [comment]
But even if it is unrelated.. according to BIKI animate always returns Nothing.. So it should never be a bool type.. so the error should always happen. Why count on undefined behavior returning a null type instead of a Nil type like it's supposed to.
Also I don't think that function should be called if I wasn't actually trying to deploy a ladder.
Very likely caused by MCC. Though i have never experienced that error before.
But yeah.. its correct.. According to RPT no postInit is happening.
ace_tacticalLadder_ladder is nil till the first right-click. after that it is objNull.
So yeah.. the final cause is a postInit fail. But the other points still remain.

RPT: http://pastebin.com/xawHpSXk
["ace_tacticalladder_ladder=",any] is my debug print that prints the current value of the var
There is no other script error besides that.. I have no clue why PostInit is not running.
Also I'm using a heavily stripped down version of MCC with most of the crap removed.

**Comment by PabstMirror** [comment]
`CBA_fnc_postInit` is never called when running with MCC (With no unit placed in a 3den preview)

**Comment by dedmen** [comment]
How can one mod cause another mods CfgFunctions postInit not to be executed... But yeah... I really only wanted to go for the Ace side script error not the other stuff that caused this error to become noticed.

**Comment by PabstMirror** [comment]
My guess is MCC isn't halting if it can't find a player or something like that, 
so arma stops all postInit?

**Comment by commy2** [comment]
You can stall postInit by using `waitUntil`, which is probably what MCC does.
The error message is wrong. Switching `count` for `forEach` does zilch. The variable is just undefined as Pabst said.

**Comment by dedmen** [comment]
from what i can see the errormessage is correct. count expects a bool and
"nil animate []" returns a Nil.. Nil != bool so error.. the problem is that
"objNull animate []" returns objNull.. although it should return Nil
according to biki. count can apparently convert objNull to a bool type and
thus doesn't throw an error. It's probably interpreting objNull as false.
So it is only not erroring always because of undocumented behaviour of the
animate command.

Am 12.01.2017 00:11 schrieb "commy2" <notifications@github.com>:

**Comment by commy2** [comment]
Can't reproduce

```sqf
{
    objNull animate [];
} count [0]{
```

**Comment by PabstMirror** [comment]
it's nil, not null

**Comment by PabstMirror** [comment]
```
{
      GVAR(ladder) animate [_x, 0];
  } count __ANIMS;
```
GVAR(ladder) is never defined because postInit didn't run

**Comment by dedmen** [comment]
Try in debug console.
objNull animate ["abc",0] returns objNull
nil animate ["abc",0] returns nil.
The script you have will not error out because it accepts objNull as bool.
But if you read biki to animate you can see that it should always return
Nil which should error out the count

Am 12.01.2017 00:33 schrieb "commy2" <notifications@github.com>:

**Comment by commy2** [comment]
```sqf
str [objNull animate ["", 0]]
-> "[<null>]"
```

```sqf
str [undefined animate ["", 0]]
-> "[nothing]"
```

**Comment by PabstMirror** [comment]
IIRC there are different types of nil, and that returns the wrong type of nil so it throws an error

**Comment by commy2** [comment]
Yeah. I'm trying to figure out which type it is. It's not OBJECT
```sqf
[vehicle nil]
[02871334]
```

**Comment by commy2** [comment]
Seems like commands without return value report a special type of `nil` that is not accepted by `count` if they are fed with `nil`. TIL

**Comment by commy2** [comment]
```sqf
[hideObject objNull, hideObject nil]
[<null>,nothing]
```
First one is accepted by `count`, second one isn't.

**Comment by dedmen** [comment]
I will investigate that tomorrow and post my findings. Im sure it will be
BItastic

Am 12.01.2017 00:48 schrieb "commy2" <notifications@github.com>:

**Comment by bux** [comment]
Sometimes happen with ALiVE as well
