### ISSUE TITLE
ACE fast rope options don't show up on ACE interaction

### ISSUE THREAD

**Issue by BloodSoakedBandit** [acemod/ACE3#4819]
**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHS USAF`
- `@RHS AFRF`

**Description:**
- ACE fast rope doesn't show up on any other helicopter in the interaction, except for Huron, Merlin, Chinook and Mi-8

**Steps to reproduce:**
1) Put down a helicopter in Zeus
2) Use ACE interaction to prepare and deploy FRIES.

**Where did the issue occur?**
- Dedicated / Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- With all ACE modules, without any modules.

**Comment by BloodSoakedBandit** [comment]
with
- `@Ares - Achilles Expansion`
I put down a Fast Rope order on an AI Ghost Hawk and then the fast rope option appeared, when I took control of one of the heli's crew. The system worked perfectly then. The FRIES options didn't show up before the order.

**Comment by 654wak654** [comment]
You need to add FRIES to most helicopters first, the ares module probably automatically does that.

**Comment by BloodSoakedBandit** [comment]
FRIES module is in Eden, so what you are saying is that you can't get it to work when spawning helis with Zeus editor?

**Comment by 654wak654** [comment]
A zeus module is coming in 3.9 #4597

**Comment by PabstMirror** [comment]
Fixed via #4597
