### ISSUE TITLE
Player view doesn't rotate upon adjusting scope when weapon is rested

### ISSUE THREAD

**Issue by agent509** [acemod/ACE3#482]
**Mods:**
- @cba_a3
- @ace3
  *@task_force_radio

**Placed ACE3 Modules:**
None

**Description:**
When adjusting the scope while looking through the optic, the player's view normally rotates. This does not occur when the weapon is rested.

**Steps to reproduce:**
1. Pick any rifle (I was using the Lynx), and scope (I was using LRPS).
2. rest the rifle and look through the scope
3. attempt to adjust the scope. The player's view doesn't rotate with the adjustment.

**Where did the issue occur?**
Editor Preview

**Comment by KoffeinFlummi** [comment]
Is `cameraView` different when rested?

**Comment by commy2** [comment]
No. It's "GUNNER" if you use the optic and "INTERNAL" or "EXTERNAL" otherwise.

there is a `isWeaponDeployed player` command though

**Comment by esteldunedain** [comment]
I fear it may not be possible to do, at least not in the same way we do normal scopes

**Comment by jonpas** [comment]
If it's not possible to do, anotger workaround could be ubdeployoing it when changing zeroing. A bit weird since you'd have to deploy again, but it would work (afaik there is a command for that).

**Comment by ElectroEsper** [comment]
Still a thing on my side. When rested, with and without mods, scope adjustment do not give a visual feedback (going up/down left/right).

When NOT rested, gives visual feedback only when doing left/right adjustment. Up/down does a quick move then reset back.

The actual adjustment works (bullet flight path and all), but makes scope adjustment tedious.

**-------------------------**

**Mods:**
@cba_a3
@ace3
@RHS (does it without also)

**Placed ACE3 Modules:**
None


**Steps to reproduce:**
Pick any rifle and long range scope.

Either:
1a-Rest the rifle and look through the scope.
1b-Attempt to adjust the scope. The player's view doesn't rotate with the adjustment.

2a-Do not rest the rifle and look through the scope.
2b-Attempt to adjust the scope. The player's view rotate only left/right; Does a quick tick up/down and reset the default up/down position.

**Where did the issue occur?**
Any playable environments

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
