### ISSUE TITLE
"Show names" keybind doesn't work

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#4822]
**Arma 3 Version:** `1.66.139968` (performance)
**CBA Version:** `3.1.2.161105`
**ACE3 Version:** `3.8.3.14`

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Basically **Only on Keypress** and **Only on Cursor and Keypress** options will not display player names no matter what. I have **Show names** button assigned to LCtrl but no matter what it will not display player names. I've also tried changing this button to something else but that also doesn't work.

**Steps to reproduce:**
- Place some AI in editor
- Go to preview and then go to ACE3 Settings
- Go to Nametags category
- Enable AI names so you can see their names
- Switch "Show player names" option to **Only on Keypress** or **Only on Cursor and Keypress**
- Try pressing LCtrl (default or check your binds) to see their names
- No names displayed

**Where did the issue occur?**
- Dedicated / Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- [pastebin](http://pastebin.com/biZaqYAG)

**Comment by commy2** [comment]
>assigned to LCtrl 

You cannot assign to modifier keys (ctrl, shift, alt). It's bugged.

**Comment by PabstMirror** [comment]
Will be fixed in next CBA release
