### ISSUE TITLE
Re-loadable Launcher Missiles Adding "Extra" weight from backpack to loaded.

### ISSUE THREAD

**Issue by SpookyToaster** [acemod/ACE3#4823]
**Arma 3 Version:** `x.xx` (stable)
**CBA Version:** `3.1.2.` (stable)
**ACE3 Version:** `3.8.3` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When loading a missile from backpack inventory to any re-loadable launcher (Titan, RPG, etc.) the weight of the missile is roughly doubled. Essentially making the weight of carrying more than 1 missile extremely encumbering

**Steps to reproduce:**
- Add backpack
-Add missile to backpack
-Add Compatible Launcher (Empty it)
-Load missile
-Observe "Extra" weight being added when going from backpack to launcher

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
- Unable to obtain.

**Comment by stafmoony** [comment]
From what I heard so far, this is a Vanilla Bug. Correct me if I'm wrong: https://feedback.bistudio.com/T121950

**Comment by SpookyToaster** [comment]
Ah, thanks for the correction. I appreciate it.
