### ISSUE TITLE
Resolve Missing Medical Setting Translations

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#4831]
Some translations are also missing: https://github.com/acemod/ACE3/blob/medical-rewrite/addons/medical/stringtable.xml#L2926-L2937

**Comment by jonpas** [comment]
I don't think we have to worry about translations at all, we have a very active translators here, but it's good to keep it on track! 👍

**Comment by ViperMaul** [comment]
@jonpas Valid point

**Comment by jonpas** [comment]
Track in https://github.com/acemod/ACE3/issues/367
