### ISSUE TITLE
Consider removing `minLethalDamage` from the extension

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#4832]
Feedback from a recent meeting:

>`minLethalDamage` can be removed from the extension
> Reference: https://github.com/acemod/ACE3/blob/medical-rewrite/addons/medical_damage/functions/fnc_parseConfigForInjuries.sqf#L82

**Comment by Glowbal** [comment]
What's the motivation behind this?

**Comment by commy2** [comment]
@Glowbal the number is always 1 and ulteq left an `@todo` in the code to clean up the extension.
Motivation is to remove "unreachable" code I suspect.

**Comment by jonpas** [comment]
Extension is not currently used, and if it wants to be it has to be updated either way. Shall we close this?
