### ISSUE TITLE
Consider Removing Dead Code from Medical Extension 

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#4833]
Feedback from a recent meeting:
> There is also some dead code in the medical extension. 
> All of this could be moved into the extension: 
> Reference: https://github.com/acemod/ACE3/blob/medical-rewrite/addons/medical_damage/functions/fnc_woundsHandler.sqf#L50-L69
> but I don't know if it is worth the effort.

**Comment by jonpas** [comment]
Extension is not currently used, and if it wants to be it has to be updated either way. Shall we close this?

**Comment by commy2** [comment]
Testing new label.
