### ISSUE TITLE
Confirm AI Behaves Properly In MP/HC

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#4835]
Make sure appropriate AI behavior is observed with respect to medical on both true dedicated server and Headless Client.
- [x] AI seems to engage unconscious units right now.  Confirm resolved 
- [x] Confirm AI appropriately heals themselves.
- [x] Confirm AI appropriately heals teammates.

**Comment by jonpas** [comment]
Can confirm all 3 work correctly:
- 1 is resolved
- 2 works fine, however there is one bug with morphine, they will overdose themselves -> #7551 
- 3 works perfectly.
