### ISSUE TITLE
ACE Medical and Apex Revive Issue

### ISSUE THREAD

**Issue by Niolad230** [acemod/ACE3#4840]
**Arma 3 Version:** Steam
**CBA Version:** `Steam Workshop
**ACE3 Version:** Steam Workshop

**Mods:**
- `@CBA_A3`
- `@ace`
- `@CUP_Weapons`
- `@CUP_Units`
- `@CUP_Vehicles`
- `@Cha_Lav25`
- `@NATO_Rus_Weapons`
- `@USMC_mas`
- `@task_force_radio`
- `@ShackTac_User_Interface`
- `@Marine_Expeditionnary_Force`
- `@MCC_Sandbox4`
- `@CUP_Core`
- `@CUP_Maps`
- `@Advanced_Towing`
- `@Advanced_Sling_Loading`
- `@Advanced_Rappelling`
- `@ACEX`
- `@DynaSound2`

**Description:**
- On our unit dedicated server, whenever someones get shot, he falls under the revive script introduced by the Apex DLC, and needs to be revive with it aswell as the Ace Medical way. We want to only use the Ace Medical without the Apex Revive.

**Steps to reproduce:**
- Shoot another player anywhere, he then falls and need to be revived by holding Space, and after patched with ace medical

**Where did the issue occur?**
- Dedicated

**Comment by PabstMirror** [comment]
Check the mission attributes

Attributes -> Multiplayer -> Revive

![image](https://cloud.githubusercontent.com/assets/9376747/22093455/62d33652-ddcb-11e6-81ee-50e107ed7aee.png)

**Comment by Niolad230** [comment]
The thing is it is disabled
