### ISSUE TITLE
82mm mortar rounds aren't visible in Virtual Arsenal

### ISSUE THREAD

**Issue by kripto202** [acemod/ACE3#4841]
None of the 82mm mortar rounds are visible in VA.

**Comment by thecuban** [comment]
I second this issue. the only way to obtain mortar ammo is to spawn a box

**Comment by PabstMirror** [comment]
Not sure how to solve this,
Seems like mags need to be `CA_Magazine` to show up in arsenal
but the mortar mags need to be `VehicleMagazine` to work in the weapon

**Comment by brainslush** [comment]
Arsenal only shows magazines for infantry weapons. Since the mortar is a vehicle it doesn't display those. It's BIS fault.
