### ISSUE TITLE
Vector 21 / Tab always pressed

### ISSUE THREAD

**Issue by AtomMrav** [acemod/ACE3#4845]
**Arma 3 Version:** `1.66.139586` (stable)
**CBA Version:** `CBA_A3 v3.1.2.161105` (stable)
**ACE3 Version:** `3.8.3` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
p.s. All mods are downloaded from steam workshop

**Description:**
- I have strange issue when I use Vector 21/ Vector 21 Night. Everything is ok until I use "tab" for azimuth. After I pres it, it's like I hold it pressed and I can't use other vector options. When I change key bind to another key, everything is back to normal.
I deleted all actions assigned to tab, so TAB is only for Ace 3 Vector 21

- Am I doing something wrong? Do I need to perform some additional setup?

**Steps to reproduce:**
- Open SP editor, place unit, give unit vector 21, measure azimuth

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- No modules

**RPT log file:**

[RPT File](http://pastebin.com/5kZktcGC)
[ACE Debug](http://pastebin.com/NuDSQpQS)

**Comment by commy2** [comment]
Nothing we or you can do. The game recognizes your tab key in a strange way. I don't see any solution other than using a different keybind.

**Comment by AtomMrav** [comment]
Ok. Thanks for answer. Is anyone else has same problem, or is it just me?
