### ISSUE TITLE
No Entry 'bin\config.bin/RscInGameUI/RscStaminaBar.idd'.

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#4852]
**Arma 3 Version:** 1.66.139586
**CBA Version:**  3.1.2.161105
**ACE3 Version:** 3.8.3.14
**Mods:**
- `@CBA_A3`
- `@ace`
@acex
@achiles
@arma enhanced movement
@advanced rappelling
@asdg
@advanced sling loading
@advanced towing
@advanced urban rappelling
@t47 launchers
@ctab
@FA18
@fhq
@hidden identity
@niarms
@thesis services
@rhpistols
@sma 
@shactac hud
@tfr
@tfw
@ussnimitz
@vcomai

**Description:**
- This error appears when you get to the main menu when loading the game. once it has appeared you cant click the close button for up to 3 minutes  http://i.imgur.com/WvD0m45.png

**Steps to reproduce:**
- Happens when running the game with Ace3 by its self and other mods

**Where did the issue occur?**
- Main Menu On Launch

**Comment by jonpas** [comment]
RPT required

**Comment by commy2** [comment]
Also, try to repro with only CBA and ACE enabled. If not possible, find out which mod causes the problem when used with ACE (or if it even is a problem with ACE at all).

**Comment by Whigital** [comment]
This has to do with ST UI Stamina bar. ShackTac Stamina bar deletes the default stamina bar resource and uses its own, so when ACE initializes and wants to use that resource, it cant be found. Suggest removing the ST UI stamina pbo.

https://github.com/acemod/ACE3/blob/master/addons/common/RscInfoType.hpp#L111

**Comment by commy2** [comment]
ST UI Stamina bar shouldn't delete a class. It should make the bar invisible instead (alpha 0, size 0).

**Comment by Snak3Doc** [comment]
Thanks heaps guys deleting the stui pbo worked, unfortunately it was what made me discover that theirs heaps of startup errors but it only shows you one of them

ps sorry for the late reply been busy
