### ISSUE TITLE
Dynamic Recon Ops overwriting serverconfig.hpp? I'm noob.

### ISSUE THREAD

**Issue by gaabrielfts** [acemod/ACE3#4853]
**Arma 3 Version:** Steam (v1.66.139586)
**CBA Version:** Steam Workshop (v3.1.2)
**ACE3 Version:** Steam Workshop (v3.8.3)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@Arma Enhanced Movement`
- `@CUP Terrains - Core`
- `@CUP Terrains - Maps`
- `@CUP Units`
- `@CUP Vehicles`
- `@CUP Weapons`
- `@RHSAFRF`
- `@RHSUSAF`
- `@RHSGREF`
- `@RHSSAF`
- `@ACE Compat - RHSUSAF`
- `@ACE Compat - RHSAFRF`
- `@Esseker`
- `@TRYK [TRYK's Multi-play Uniforms]`

**Description:**
- I'm editing serverconfig.hpp but when I try to play a Dynamic Recon Ops, ACE3 mod return to vanilla settings.
- Also if you guys are feeling kind enough to explain me how `description.ext` and that `ACE_Settings` works and where should I create these files it'll be appreciated :)

**Steps to reproduce:**
- Load any Dynamic Recon Ops
- Try to use Advanced Medical System
- Fail

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**Placed Modules:**
- [Serverconfig](http://pastebin.com/jYNyyTgZ)

**RPT log file:**
- [Here](http://pastebin.com/CMxRn5bk)

**Comment by jonpas** [comment]
How to use the settings framework: https://ace3mod.com/wiki/framework/settings-framework.html

That RPT is not the full RPT, we'll need the full one to help.

**Comment by gaabrielfts** [comment]
I read the framework settings upside down already and don't know how to fix yet =/
How can I find the full RPT? I just clicked Debug Export Menu something like that in ACE Options @jonpas

**Comment by BryanBoru** [comment]
**RPT log file:**
-  An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file.
