### ISSUE TITLE
Damage to Players

### ISSUE THREAD

**Issue by Frenki1** [acemod/ACE3#4858]
Arma 3 Version: 1.66
CBA Version: Last Available form Steam Workshop
ACE3 Version: Last Available form Steam Workshop

Mods:
- @CBA_A3
- @ace
- @TFAR

Description:
- Guys i have a problem with ACE Medical on my community server. We are using Basic Medical system and the problem is in that, that players wich are beeing shoot, eaven from small distances, 5 to 10 meters, with large calibers, like .408, directly in the face, they go unconscious, and they woke up after 10 seconds, and the wound is only geting low damage (yellow color cross). I did try to lower damage needed to kill player in ACE modules but it doesent change anything. We are playing on Veteran difficulty with no reduced damage to playes, and its still ocures. If we want for someone to go unconcious we need to hit him multiple times.

Where did the issue occur?
- Dedicated Server

Check out our serverconfig file wich is in the zip.

[server config.txt](https://github.com/acemod/ACE3/files/737508/server.config.txt)

**Comment by jslick007** [comment]
Happens in single player too. Makes players and AI invulnerable.

Arma 3 Version: 1.66 + 1.67.140241
CBA Version: Last Available form Steam Workshop
ACE3 Version: Last Available form Steam Workshop

Mods:
- @CBA_A3
- @ace 

Description:
- Removing ACE Medical and ACE Basic Medical settings alleviates, but does not eliminate problem completely. Occasionally, entities gain "invulnerability".

- Dev Branch v1.67.140241 additionally pops up debug message:

'...[_part, (_damageBodyParts select _part) |#|+ _newDamage]; 
_unit setVariable ["ace_m...'
Error Generic error in expression
File z\ace\addons\medical\functions\fnc_handleDamage_advanced.sqf, line 30

**Comment by TheMagnetar** [comment]
Fixed in rewrite
