### ISSUE TITLE
Crashes To Desktop With Different Maps Using Same Template/Mods On All Maps

### ISSUE THREAD

**Issue by Odysseus-USA** [acemod/ACE3#4861]
**Arma 3 Version:  1.66.139.586 - Stable
CBA Version:  3.1.2.161105 - Stable
ACE3 Version:  3.8.3 - Stable**

**Mods:**
CBA_A3
ace
CUP (all)

**Description:**

**Note: *ALL* programs/mods/scripts/etc. listed below are CURRENT as far as version information as of 01/30/2017.**

I have about 25 maps and ACE seems to 'work' with them all.  I use a template for MCC4 and I put down this template and then save it.  I play/create all missions from this '#1 save' file.

When using the latest Australia, Diyala, or Taunus (1.1) maps, when I load the 1st save file in, ARMA crashes to the desktop.

_This error started with the two version back of ACE  (example, current=3, issue started on v1)  I am not 100% sure on two versions back, it could have been one version back.  Reason why, I just quit playing this way on those maps and played 'working' maps instead._

I have gone as far as using just ARMA, CBA, CUP (all parts), the above map, and ACE.  Put a man down, save, reload right after save, and ARMA crashes to the desktop.  I have tried this only on the Taunus map, however, the other 2 do the same.

**Note:  As all three maps behave identical, I have not attempted to reproduce this on all three maps, just on the Taunus map has this been replicated at will.**

This does NOT occur on any other maps that require CUP or any other maps.  Maps such as Essker, Bornholm, Lingor, Isle Dula, Chernobyl, Helvantis, Clafghan, Panthera, and about 10-15 other maps.  (Forgive any map mis-spellings)

If I **JUST** take out ACE, I have **ZERO** issues with **ANY** map and this is what I am doing now sadly.

**Steps to reproduce:**
Use:  ARMA. CBA, Entire CUP mods, ACE, and one of:  Taunus, Australia, Dayala maps
Start ARMA
Go to editor
Place down a single BOHEMIA man
Save mission
Load mission up as to play
Once in created mission, save
After save, load back in the saved mission
Crashes to desktop

**Where did the issue occur?**
Single Player

**Placed Modules:**
None

**RPT log file:**
There is not a log file to see anything.  That was one of the first things I checked.  All you see are loaded items then the register values in the 'crash report'.  Every Report file is different.

As an example, using the same setup:

RPT #1:  abc
RPT #2:  sss
RPT #3:  xyz

**It is NEVER the same and ALWAYS COMPLETELY DIFFERENT for the EXACT SAME MISSION.**

**Comment by commy2** [comment]
What?

Needs RPT file.

**Comment by Odysseus-USA** [comment]
SECOND TIME:

**"It is NEVER the same and ALWAYS COMPLETELY DIFFERENT for the EXACT SAME MISSION."**

I will get ONE and update when obtained.

**Comment by BryanBoru** [comment]
It is confusing to see links to AGM issue reports, and it is confusing to see use of MCC but not list them as a mod you are running. 

I am not ACE team, but I can see how they are asking for more relevant information, you seem to have many of words and information but not much of it is an explanation or relevant.

**Comment by Odysseus-USA** [comment]
Hmmm...I stated **_EXACTLY_** what mods were being used!  It STARTED with using MCC4.

READ WHAT I POSTED BEFORE YOU COMMENT!!!!


_I have gone as far as using just ARMA, CBA, CUP (all parts), the above map, and ACE. Put a man down, save, reload right after save, and ARMA crashes to the desktop. I have tried this only on the Taunus map, however, the other 2 do the same._

**_(and this is "not much of it is an explanation" to quote you?)_**






_**Steps to reproduce**:
Use: ARMA. CBA, Entire CUP mods, ACE, and one of: Taunus, Australia, Dayala maps
Start ARMA
Go to editor
Place down a single BOHEMIA man
Save mission
Load mission up as to play
Once in created mission, save
After save, load back in the saved mission
Crashes to desktop_

**Do you SEE MCC4 LISTED In STEPS TO REPRODUCE OR IN THAT PART OF THE DESCRIPTION????  DO YOU????**


**What a moron and idiot you are!  And you complain about me?!?!?!  At least I CAN READ!!!**

**_And you're correct, you are NOT part of the team - SO BUTT OUT AND KEEP YOUR STUPID COMMENTS AND FALSE ACCUSATIONS TO YOURSELF!_**

**What a WASTE of my time reading your LIES!**

**Comment by KoffeinFlummi** [comment]
> ***And you're correct, you are NOT part of the team***

Yup, but I am. Don't come back.
