### ISSUE TITLE
Medical HandleDamage error on dev branch

### ISSUE THREAD

**Issue by Drift91** [acemod/ACE3#4863]
**Arma 3 Version:** `1.67` (dev)
**CBA Version:** `3.1.2` (stable + ed1feb3c)
**ACE3 Version:** `3.8.3` (stable + 0df98f79)

**Mods:**
- `@CBA_A3`
- `@ace`
- 56 other mods that I've tested without

**Description:**
- Whenever a player or AI gets shot in the vest or helmet the game throws an error and they take no damage. The error stays on screen until the entity dies. This just started happening within the past 24 hours. My friend blames the recent update to dev branch by BI.

**Steps to reproduce:**
- Load game. Go to virtual arsenal. Equip a weapon and vest. Click "try". Shoot VR entities in the vest. Note that this happens outside the virtual arsenal as well.

**Where did the issue occur?**
- Dedicated + Editor (Multiplayer) + Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- https://gist.github.com/Drift91/f550607bc56ebd8db82c2b9c7455f270
- "Debug To Clipboard" seems to have done nothing.

**Comment by jonpas** [comment]
This is because of:
> Tweaked: The HandleDamage Event Handler is now extended with the hitPoint name parameter

**Comment by commy2** [comment]
```
 4:52:25 Error in expression <[_part, (_damageBodyParts select _part) + _newDamage];
_unit setVariable ["ace_m>
 4:52:25   Error position: <+ _newDamage];
_unit setVariable ["ace_m>
 4:52:25   Error Generic error in expression
 4:52:25 File z\ace\addons\medical\functions\fnc_handleDamage_advanced.sqf, line 30
```
