### ISSUE TITLE
Consider renaming the steam workshop entry

### ISSUE THREAD

**Issue by Cephel** [acemod/ACE3#4864]
This may seem a little pedantic, but just "ace" looks a little bland. Mirroring the actual title such as "Advanced Combat Environment" would look much better.

**Comment by jonpas** [comment]
There is a reason we originally didn't name it that way, it's because the name directly influences the `@mod` name and we wanted to keep it the same. However, since then Steam Workshop has changed how it works with Arma and it now just uses symlinks, so we might as well name it properly.

**Comment by Cephel** [comment]
Just a reminder that this is still a thing.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
