### ISSUE TITLE
Cursor in interaction menu always enabled in vehicles

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#4868]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.1.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Cursor is always enabled for interaction menu in vehicles. The settings to not use the cursor mode work fine on foot, in vehicles they have no effect. Looks like a regression from not long ago, certainly not by design as this effectively destroys TrackIR (or any free-look) compatibility with the interaction menu in vehicles (where it is most needed due if flying with hand-off-mouse).

**Steps to reproduce:**
- Disable both "always show cursor for (self-)interaction menu" setting.
- Go into vehicle.
- Use self or target interaction menu.
- See the cursor!

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- None

**RPT log file:**
- N/A

**Comment by commy2** [comment]
You cannot turn your head (infinitely) in some vehicles. This is intentional.

**Comment by PabstMirror** [comment]
I think it's been like this forever.
https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_keyDown.sqf#L40

**Comment by jonpas** [comment]
So with the "move menu rather than pointer" it should work? It seems very anti-free-look to me, even if by design.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 160 days without any activity.

**Comment by commy2** [comment]
close?

**Comment by bux** [comment]
ok

**Comment by jonpas** [comment]
Since the release it was said ACE interaction is fully TrackIR friendly, I still think this should be a thing, I know I want it. :p

Even if you can't move infinitely, maybe move menu instead of cursor would work then.
