### ISSUE TITLE
dedicated server issues

### ISSUE THREAD

**Issue by Orydin21** [acemod/ACE3#4869]
Arma 3 Version: 1.66 (stable)
CBA Version: 3.1.2 (stable)
ACE3 Version: 3.1.2 (stable)

Mods:

@CBA_A3
@ace
Description:

On the dedicated server the interaction menu will not come up either for self or buddy aid, but ace is enabled because we can still get knocked unconscious and not out right die when shot several times.

Placed Modules:
Basic med

RPT log file:

N/A

**Comment by commy2** [comment]
Needs RPT file

**Comment by Orydin21** [comment]
It will not let me add the file for some reason I even packed it into a .zip and it still says can not support file
;;;;;;;;;;

**Comment by PabstMirror** [comment]
https://gist.github.com/
Should be able to drag it into there and post link here

**Comment by Orydin21** [comment]
https://gist.github.com/Orydin21/d28dcb9474ffe08d6244cd111bd9b57d

There are more mods then listed but All mods were used in the self host and the dedicated host. Nothing other than the type of host was changed.

**Comment by commy2** [comment]
than*

There is a reason why we say, the issue should be first reproduced with CBA and ACE only, btw.

```
13:59:06 [0,32.919,0,"XEH: PreStart started."]
13:59:07 Error in expression <efault {
_addedToUnit = false;
WARNING_2("Incorrect item type passed to %1, pass>
13:59:07   Error position: <("Incorrect item type passed to %1, pass>
13:59:07   Error Missing ;
13:59:07 File z\ace\addons\common\functions\fnc_addToInventory.sqf, line 119
```

**Comment by commy2** [comment]
CBA is outdated. The current version is 3.1.2. and that one is required.

```
13:59:02                       Community Base Addons v3.0.0 |              @CBA_A3 |      false |             GAME DIR | da39a3ee5e6b4b0d3255bfef95601890afd80709 |  11fdd19c | C:\TCAFiles\Users\josephC\273\@CBA_A3
13:59:02                  Advanced Combat Environment 3.8.3 |                 @ace |      false |             GAME DIR | da39a3ee5e6b4b0d3255bfef95601890afd80709 |  11fdd19c | C:\TCAFiles\Users\josephC\273\@ace
```

**Comment by commy2** [comment]
Remember to delete the old `@CBA_A3` folder before applying the path. The latest version of CBA can be found here: https://github.com/CBATeam/CBA_A3/releases

**Comment by Orydin21** [comment]
Thank you I thought I updated it but I see I was wrong
