### ISSUE TITLE
Washed out white effect when firing from prone

### ISSUE THREAD

**Issue by joonoro** [acemod/ACE3#4872]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.8.3` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When firing various rifles from prone a white effect happens where the entire screen becomes very bright and washed out. This does not occur when crouched or standing, only when firing from prone. I am not sure if this is intentional or not because it doesn't seem to be documented anywhere. There should be a way to disable it as it is distracting.
- Before shooting: https://i.imgur.com/5cSWEIl.jpg
- After shooting: https://i.imgur.com/VIpjl0W.jpg
- Happens with at least MX 6.5mm, Katiba, and TAR-21

**Steps to reproduce:**
- Open the editor on Stratis
- Place a NATO rifleman on the airfield runway as the player
- Go prone
- Switch to fully automatic and fire bursts
- Notice that the screen turns bright white and washed out

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- Not relevant

**Comment by PabstMirror** [comment]
This is from ace_goggles. It represents dust being kicked up while firing near dry ground.

There is a setting you can change `ace_goggles_effects` if you wish to remove.
- 2 does all Effects
- 1 will only do the color tinting
- 0 to completely disable
