### ISSUE TITLE
Exagerated stamina drop when going prone without weapon in hand

### ISSUE THREAD

**Issue by Javiervs** [acemod/ACE3#4880]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.8.3` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Massive stamina drop when going prone while running with no weapon in hands. It is exagerated compared to the stamina drop of the same action with a weapon on hands. You may lose more than half your stamina in just one action.

You can observe the animation makes a little "forward jump" just before hitting the floor that won't make when you have a gun. Maybe this has something to do with the stamina drop?

**Steps to reproduce:**
-Put your weapon on your back by pressing "0" or drop them all.
-Go sprinting with empty hands.
-While sprinting go prone.

**Where did the issue occur?**
Editor (Singleplayer)

**Placed Modules:**
- Fatigue system

**Comment by commy2** [comment]
I think this is a duplicate. Baer should know.

**Comment by BaerMitUmlaut** [comment]
Saw just now that this issue was already mentioned in #4516, but after it was merged which is probably why it did not get noticed.

**Comment by PabstMirror** [comment]
With no weapon, sprinting and going to prone
`stance player = "STAND"`
So the fix from #4516 won't work.
getMetabolicCosts is peaking around 3900 which will wipe out most of the stamina bar.

**Comment by WastedMike** [comment]
Why is it that when ever you go prone you lose all your stamina?

**Comment by commy2** [comment]
Because bug and computers.
