### ISSUE TITLE
Spawning new vitalLoop after each fullHeal

### ISSUE THREAD

**Issue by dedmen** [acemod/ACE3#4884]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `latest. lazy ...` (stable)
**ACE3 Version:** `3.8.3` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `others cuz I'm lazy`
**Description:**
After each fullHeal:
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatmentAdvanced_fullHealLocal.sqf#L50
Set's the addedToUnitLoop to false although there might still be a vitalLoop running.
Then when anything happens that would cause a vitalLoop to get added 
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_addVitalLoop.sqf#L25
this doesn't catch the duplicate anymore.

In my current game there are 101 vitalLoops running taking up to 50ms every few frames.

**Steps to reproduce:**
Get downed. Get full healed. get shot again.

**Where did the issue occur?**
- Dedicated

**Comment by Glowbal** [comment]
Thanks for your report @dedmen. We will fix this for 3.9.1.
