### ISSUE TITLE
Spare barrel is not visible in ammo box

### ISSUE THREAD

**Issue by kamkill01011** [acemod/ACE3#4890]
**Arma 3 Version:** `166` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.8.3` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The spare barrel is not visible in ammob box, it's not possible to add it in ammo box.

**Steps to reproduce:**
- Place the ACE Miscellaneous Items box in the editor try to fin the spare barrel in the Equipment Storage category (it's not there), then play the mission and open the box with a character and look for the spare barrel (you'll find it).

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Singleplayer)

**Placed Modules:**
- No modules.

**Comment by PabstMirror** [comment]
`ACE_SpareBarrel` is technically a magazine
as far as I can tell the Equipment Storage only shows magazines that can fit into an actual weapon

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 160 days without any activity.
