### ISSUE TITLE
I can't unload prisoners

### ISSUE THREAD

**Issue by majinisinpu** [acemod/ACE3#4891]
I can't unload prisoners because their Interact menus don't have "Unload Captive".

**Comment by bux** [comment]
Please take the time to fill out the issue template.
If not we ~won't~ can't help you.

**Comment by PabstMirror** [comment]
Is this related to #4862 - Do you see bandage/diagnose options for the unit?
Screenshot/RPT would help.

**Comment by majinisinpu** [comment]
Yes.
I see Bandage/diagnose options .

**Comment by PabstMirror** [comment]
We think the root cause is a mod load order problem.
If you can move ace up to the front, it may solve it.
e.g. `-mod=@CBA_A3;@ace;@otherMods....`

Otherwise we will have a proper fix in 3.9.1

**Comment by PabstMirror** [comment]
Dupe of #4862
Will be properly fixed in 3.9.1
