### ISSUE TITLE
Interaction Menu Issue on Dedicated

### ISSUE THREAD

**Issue by KubicaEsque** [acemod/ACE3#4894]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2.1611051` (stable)
**ACE3 Version:** `3.8.3` (stable)

**Mods:**
- `@CBA_A3`
- `@@Ares Mod - Achilles Expansion (Alpha 0.0.5)`
- `@ace`
- `@aceServer` (Contains the addons/ace_server.pbo within server files (serverconfig.hpp is also in userconfigs))
- `@task_force_radio`

**Description:**
- I have been able to launch the server with CBA, Achilles, ACE3, and TFAR all at once no crashes, and it would seem certain aspects of the ACE3 mod will work, ex. Fast roping, Hand Gestures, Climbing Ledges, and objects appear within the server. The only problem appears to be the interaction menu does not appear when pressed for anyone that joins the server. Interface works on single player, editor, local hosting.

**Where did the issue occur?**
- Dedicated HostHavoc Server

**Placed Modules:**
- None

**RPT log file:**
- [https://gist.github.com/KubicaEsque/09c05672d960726a20e32a75379e1f9b#file-arma3_2017-02-12_00-34-14-rpt](url)
- http://pastebin.com/qNEKyjeS

**Comment by PabstMirror** [comment]
`[ACE] (common) INFO: Waiting on settings from server...`
and ace_settings are empty in the debug dump

Can you verify ace is loading on server;  RPT from server would be helpful.

**Comment by PabstMirror** [comment]
btw, `aceServer.pbo` is only needed if using custom ace settings
and just running it on the server is not enough

**Comment by KubicaEsque** [comment]
Updated with Server RPT. Yeah, I was doing any possible fix I could find until now, aceServer.pbo was not the lone running.

**Comment by PabstMirror** [comment]
```
22:34:08 Unknown entity: '& {_x find "ace_" != 0} && {!(toLower _x in (missionNamespace getVariable ["ACE_Version_Whitelist", []]))}) then {
        _files pushBack _x'
22:34:08 Unknown entity: '& {!isNil "ACE_Version_ServerVersions"}
    }'
22:34:08 Unknown entity: 'ùìñ'ôÞþw¦¸'
```

This is very early in the RPT, above the updating base classes.
I honestly don't know what to make of it.

It could possibly be some kind of data coruption?
You might want to try verify the server's game cache / or re-run steamcmd with `validate`.
And try deleting and redownloading cba/ace.
If possible try launching with just CBA/ACE and upload rpt or see if there is that same error.

**Comment by KubicaEsque** [comment]
Alright, I re-installed ACE and CBA to the server, and they do work alone. And I can get the interface to come up with the other two mods on, Task Force Radio and Achilles Mod but text does not show up within the interface and it hits the frame rate pretty badly.
A bunch of error messages  flashed by when joining the server real fast and couldn't catch what they were for.

Just CBA_A3 and ACE3 Active: http://pastebin.com/5S8mmyrJ
W/ All 4 mods Active (CBA, ACE3, TFR, Achilles): http://pastebin.com/W9BMMNvU
