### ISSUE TITLE
Systematic Errors the ACE3, after loading the my old missions.

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#4896]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `-3.1.2.161105 (stable)
**ACE3 Version:** `ace3_3.8.2 or 3_3.8.3

**Mods:**
- `@CBA_A3`
- `@ace`
- @JSRS -sound mod
-@RealisticTankCrew

**Description:**
Hi! Since yesterday I get constant error associated with ACE3.
I can't open any my mission in the editor, who yesterday worked perfectly. I can't run any new mission!

http://images.vfl.ru/ii/1486933449/e1a04458/16069785.jpg

file -ace_fcs.dll is present in the ACE3 folder, however, the game says this file is not present.
Before everything worked fine! The weird thing is that ACE3 and BIS did not make any updates!?

**Steps to reproduce:**
- cannot open my missions
**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- 
**RPT log file:**
-

**Comment by PabstMirror** [comment]
This is often caused by battleeye blocking the dlls
Try launching with the arma launcher and checking the battleEye tab.
It should be something like "Starting BattlEye Service.... Updating Service"
It will list any dll blocks, or if it cannot update or connect.

**Comment by ZeusWrath** [comment]
Thanks/ I disabled the Checkbox BattleEye and the problem disappeared.  Yes! But What would be your recommendations? Yesterday I was working with BattleEye enabled! Why is this happening?

**Comment by PabstMirror** [comment]
BattlEye sometimes goes down.
I tried right now and it seems to be up and running.

Try running with it enabled and see what the specific error is on that tab in the launcher.

**Comment by ZeusWrath** [comment]
Thank you very much for your attention!
