### ISSUE TITLE
More than One Slideshow / overlap menus

### ISSUE THREAD

**Issue by Rocky83** [acemod/ACE3#4901]
**Arma 3 Version:** 1.66.139586 (stable)
**CBA Version:** latest
**ACE3 Version:** `latest befor 3.9.0

**Mods:**
- `@CBA_A3`
- `@ace`
- BWMod

**Description:**
Hi guys...sorry for my bad english (german). I hope that you understand the Problem and can help. 
We will place more then one Slideshow on the Map. All Slideshows have the same controller. When we interact with this controller, the Slides/Dias show corecctly but the next menu is on top. You cant read the text, because the letters are above the other word fromthe other slideshow. (PICTURE)
Why is Slide1 shown, when i select Slide2...and how can i rename "Dias"?

German:
Hallo liebes ACE-Team,
Wir wollen auf unserer Karte mehr als nur eine Slideshow mit dem selben Controller platzieren. Nun werden auf dem Controller auch alle Slideshows angezeigt...aber die Untermenüs "überlappen" mit der vorhergehenden Slideshow. Warum wird mir diese noch angezeigt wenn ich doch die andere gewählt habe? Und kann man die einträge "Dias" ersetzen, so das man dort eigenen Text verwenden kann?
das würde das Handling der Slideshows sehr erleichtern!

![20170214235709_1](https://cloud.githubusercontent.com/assets/25780710/22953896/98d719be-f313-11e6-99b5-a2417d479f5c.jpg)
 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer

**Placed Modules:**
- Slideshow

**Comment by jonpas** [comment]
Could you paste a screenshot of your module settings?

**Comment by Rocky83** [comment]
Setting of both Slide Moduls and Setting ACE Interaction
![20170215075653_1](https://cloud.githubusercontent.com/assets/25780710/22963753/ea153c0c-f354-11e6-9bc9-ed19c7528ef7.jpg)
![20170215075506_1](https://cloud.githubusercontent.com/assets/25780710/22963752/ea14d320-f354-11e6-901a-169c352110a3.jpg)
![20170215075518_1](https://cloud.githubusercontent.com/assets/25780710/22963754/ea161ad2-f354-11e6-8948-16906da59c9c.jpg)

**Comment by bux** [comment]
Hallo 5. JgKp. Ihr hier? 😁

Have you tried using a different view option for the interaction menu? How does it look when not choosing the "list" mode for it? Does it make a difference?

**Comment by commy2** [comment]
more than*

**Comment by Rocky83** [comment]
@bux Bin der neue, komm jetzt öfters. Bin gerade am basteln und niemand kann mir konkret in der Sache  weiterhelfen...deswegen dachte ich mir...fragst mal direkt!

I will try another Interaction Style (not List) ... its the same but another Problem :-)
It will shows all "Pictures/Folien" selected Slide1 and all "Pictures/Folien" from Slide2.

![20170215152709_1](https://cloud.githubusercontent.com/assets/25780710/22978591/969fdf5c-f393-11e6-99a5-23755c17be20.jpg)
![20170215152718_1](https://cloud.githubusercontent.com/assets/25780710/22978592/96a9cce2-f393-11e6-94b6-477fbde7acd0.jpg)

But when i select Slide 1 (Dias) then i will see only the Pictures which are in this Slideshow involved.

AND Dias (Slide1) and Dias (Slide2) ...its very tricky when more then 2 Slideshows :-)
I hope there is an Solution, that can we name the Slides. And the Program finds the different between the Slides...

Slide 1 = not Dias = for example: Briefing Mission 1
Slide 2 = not Dias = for example: Picture from Holidays :-)

**Comment by Rocky83** [comment]
@commy2 ... Sorry for my bad english ...long time ago...

**Comment by jonpas** [comment]
Can confirm, will look into it.

**Comment by jonpas** [comment]
I have fixed and improved this in #4904.
You can test it out using this PBO @Rocky83 (not signed, just for testing):
[ace_slideshow_fixMultiple.zip](https://github.com/acemod/ACE3/files/777463/ace_slideshow_fixMultiple.zip)

**Comment by Rocky83** [comment]
Great! I will test it tomorrow! Thx @all

**Comment by Rocky83** [comment]
@jonpas How can i test this pbo? When i replace it, ARMA say its outdated. I see that one Command is new...but i can test it ingame.
Great and Fast Work!! Thx

**Comment by jonpas** [comment]
@Rocky83 it should load fine with 3.9.0.

**Comment by Rocky83** [comment]
Great! It works fine! THX to all

**Comment by jonpas** [comment]
Thanks for testing @Rocky83. I suggest you don't use that PBO until it is released in 3.9.1 as it is a development build of it.

**Comment by Rocky83** [comment]
Problem!!! Show here... [https://github.com/acemod/ACE3/pull/4904](url)
