### ISSUE TITLE
ACE and revieved.sqf

### ISSUE THREAD

**Issue by coresync2k** [acemod/ACE3#4903]
I dont know if this is correct here i try to to use a "revieved.sqf" from Altis Life Framework for this

If a player died, i want to use a Defi to get him back  so i set this into the "revieved.sqf"

`player setVariable ["ACE_isUnconscious", true, true];` <- 
working, but the person dont come back, only with the personalfirstaidkit
we tried all morphine/epiniphrine all of it

and i want to set up damage to the person i tried this ->
			`[player, 0.50, "head", "stab"] call ace_medical_fnc_addDamageToUnit;`
			`[player, 0.65, "hand_r", "stab"] call ace_medical_fnc_addDamageToUnit;`
			`[player, 0.65, "hand_l", "stab"] call ace_medical_fnc_addDamageToUnit;`
			`[player, 0.75, "leg_l", "stab"] call ace_medical_fnc_addDamageToUnit;`
			`[player, 0.75, "leg_r", "stab"] call ace_medical_fnc_addDamageToUnit;`

But only the leg_r is damaged everytime, and ideas?
and sorry if i wrong here.

**Comment by PabstMirror** [comment]
Not sure about first part. You may want to try using this instead of the setVar
`[unit, true, 9999999, true] call ace_medical_fnc_setUnconscious;`


 `ace_medical_fnc_addDamageToUnit` requires some delay between calls; e.g.:
```
[player, 0.50, "head", "stab"] call ace_medical_fnc_addDamageToUnit;
sleep 0.2;
[player, 0.65, "hand_r", "stab"] call ace_medical_fnc_addDamageToUnit;
````

**Comment by coresync2k** [comment]
now it works with the changes, thx :)
