### ISSUE TITLE
NIGHT VISION SCOPES 

### ISSUE THREAD

**Issue by flarti4ok1991** [acemod/ACE3#4906]
Hello id like to suggest you guys a production of new night vision scopes that can operate with the wind deflection and direction like the lrps pip or 2d and add an option that sniper scopes from other known mods like rhs and on could also be custumized with wind deflection and add more calibers to the atragmx for example usuing rhs usaf i took the barret 50 and couldnt find the right bullet caliber in the atragmx and couldnt calculate the right things to put on my scopes and olso add a vector with night vision

**Comment by BaerMitUmlaut** [comment]
Feature requests belong into #3594.
