### ISSUE TITLE
LRPS/MOS (PIP) scopes have no outer PIP after using another PIP scope

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#4907]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (dev `dd3f3d0454fd6c65a77aaaa4e209ed0632685f85`)
**ACE3 Version:** `3.9.0` (dev `19d5fa0a4e2606ba5fe12b1c71293a772a028bc6`)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
`LRPS (PIP)` and `MOS (PIP)` have black surroundings unlike their 2D counterparts. I assume this is a legit bug, because what's the point of a PIP scope if you can't see anything around it.

MOS (Vanilla):
![mos](https://cloud.githubusercontent.com/assets/7935003/22997289/233d8e9e-f3d2-11e6-90d2-50f01db7ba46.jpg)
MOS (2D):
![mos_2d](https://cloud.githubusercontent.com/assets/7935003/22997288/233c9520-f3d2-11e6-9d9a-8b3bb91b2f48.jpg)
MOS (PIP):
![mos_pip](https://cloud.githubusercontent.com/assets/7935003/22997348/464ef0ee-f3d2-11e6-8521-f067cadc2501.jpg)

LRPS (Vanilla):
![lrps](https://cloud.githubusercontent.com/assets/7935003/22997290/23408a68-f3d2-11e6-8040-5e42889489b3.jpg)
LRPS (2D):
![lrps_2d](https://cloud.githubusercontent.com/assets/7935003/22997291/2344d1d6-f3d2-11e6-93f4-320cf1996ae1.jpg)
LRPS (PIP):
![lrps_pip](https://cloud.githubusercontent.com/assets/7935003/22997287/2332416a-f3d2-11e6-8762-e62ee0de13ef.jpg)

**Steps to reproduce:**
- Use the scope.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- N/A

**Comment by J3aLeiNe** [comment]
@jonpas , no problem for me with the PiP scopes, example with the MOS PiP :
http://images.akamai.steamusercontent.com/ugc/90473128338585956/12293431D0413BC192E01923008F1EE32484B4A4/
(Ultra video setting)

**Comment by jonpas** [comment]
Interesting, fairly sure my PIP setting is on ultra as well, works for all other scopes.

**Comment by jonpas** [comment]
I tried this again and on the first use of the LRPS/MOS (PIP) they both work fine.
However, upon using the MRCO (PIP) and then switching to LRPS/MOS (PIP) you get the black area.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 170 days without any activity.

**Comment by jonpas** [comment]
Seems to have been fixed at some point, probably with CBA Optics.
