### ISSUE TITLE
MOS 2D and PIP wrong zoom levels

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#4908]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (dev `dd3f3d0454fd6c65a77aaaa4e209ed0632685f85`)
**ACE3 Version:** `3.9.0` (dev `19d5fa0a4e2606ba5fe12b1c71293a772a028bc6`)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
`MOS (2D)` and `MOS (PIP)` have LRPS' zoom levels instead of the MOS'.

Screenshots of smallest zoom level.

Vanilla:
![mos](https://cloud.githubusercontent.com/assets/7935003/22997638/8b0136d8-f3d3-11e6-9c72-4c42f0887ffd.jpg)
ACE3 2D:
![mos_2d](https://cloud.githubusercontent.com/assets/7935003/22997639/8b06b4c8-f3d3-11e6-9e9b-76eff817c0b3.jpg)
ACE3 PIP:
![mos_pip](https://cloud.githubusercontent.com/assets/7935003/22997640/8b0a9c64-f3d3-11e6-8aff-95823c1591b9.jpg)

**Steps to reproduce:**
- Use the ACE3 MOS and vanilla MOS scope.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- N/A

**Comment by J3aLeiNe** [comment]
I just tried the MOS PiP scope and there is no problem for me :
http://images.akamai.steamusercontent.com/ugc/90473128338323076/757D6A18A5EBE7D35718516A49B299F96D23C083/

**Comment by jonpas** [comment]
The 2D and PIP MOS scopes have higher zoom levels than the vanilla one. I am not sure if it's meant to be like that, but they are all the same scope so they should have same zoom levels.

MOS says `2,5x-5x`, however the zoom is equivalent to LRPS' `6x-25x`. MOS' default zoom level is the same as the minimal zoom level, you can't zoom out, but you can zoom in to LRPS' maximum zoom level.

**Comment by J3aLeiNe** [comment]
Agree with you but, in this case, the opticsZoomMin is completely dependent of the reticle,
because a mRad rifle scope without a reticle correctly calibrated make no sens.

Why not a MOS with the vanilla magnifications but the reticle should be updated (*.paa ?).

A another solution could be a animated reticle (like the spotting scope) 
for each ACE scopes with their own magnifications,
do you think that it's possible ?

**Comment by jonpas** [comment]
Yeah, I get it that it's dependent, that's why I don't fix it myself, we have more capable people on that front. :)

I am not sure what the best way to go is, I just know it's not right as it is.

**Comment by commy2** [comment]
I got PS for stuff like this. Too bad you can't download artistic talent.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 170 days without any activity.

**Comment by johnb432** [comment]
If this hasn't already been fixed, #7273 fixes it with certainty.
