### ISSUE TITLE
AI using Defend Area command get stuck in aiming loop, don't shoot

### ISSUE THREAD

**Issue by ShizCalev** [acemod/ACE3#4909]
**Arma 3 Version:** `1.66.140341` (stable)
**CBA Version:** `3.1.2.161105` (stable)
**ACE3 Version:** `3.9.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Issued defend area command to AI. Units garrison buildings and the area as expected, however stationary units (such as those standing beside the buildings or inside them) will get stuck in a loop of drawing their weapon over and over, not firing unless the hostile unit comes within arm's length, and stay in that loop until they are killed or removed.

Video;
https://youtu.be/zrwmflTmeBE

**Steps to reproduce:**
- Place opfor AI squad on map
- Use ACE AI -> Defend Area command on SL
- Wait for units to garrison building
- Spawn blufor unit
- Have them run in front of opfor in the building
- Have them run in the building
- Have them hug the opfor AI

**Where did the issue occur?**
- Dedicated (with and without HC), Self-Hosted Multiplayer, Editor (Singleplayer)

**Placed Modules:**
- Game master 

**RPT log file:**
- http://pastebin.com/c6hxJdFG
- http://pastebin.com/9LegBRKy
- ACE rpt; http://pastebin.com/piNu26X8

**Comment by PabstMirror** [comment]
Ref https://github.com/CBATeam/CBA_A3/issues/551
Will will be fixed in next CBA release (3.2)
