### ISSUE TITLE
Script error when opening ATragMx

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#4910]
**ACE3 Version:** `3.9.0` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When opening the ATragMx a script error is shown
(possible old gun list?)

**Steps to reproduce:**
- Go into editor
- place down AB module
- take an ATragMx with you
- open the ATragMx

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- AB (with AB set to "Enabled")

**RPT log file:**
- http://pastebin.com/RBzfDp8a

**Comment by J3aLeiNe** [comment]
Personally, before each ACE's update, i delete my _"name.vars.Arma3Profile"_ because the Gun List is saved in this file. 
I don't know why but it seems to be necessary to avoid a possible conflit with AB.

**Comment by bux** [comment]
Yeah, that's what I'm assuming.
