### ISSUE TITLE
Titan and Javelin STILL do not fire (AI)

### ISSUE THREAD

**Issue by kendo01** [acemod/ACE3#4911]
RE: #4856 and #4857, the AI STILL do not fire either launcher. VERSION 3.9

**Comment by PabstMirror** [comment]
@kendo01 - Sorry the PR didn't make it into 3.9, but was tagged 3.9.0 so it was in the changelog.
It will for sure be in next release (3.9.1)

https://github.com/acemod/ACE3/blob/release-v3.9.0/addons/missileguidance/CfgAmmo.hpp#L72

**Comment by bux** [comment]
I've removed it from the github change log

> - AI were not properly taught on how to use the Titan or a Javelin (#4856)
