### ISSUE TITLE
Earplugs break if combat deafness is disabled

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#4912]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.9.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Earplugs break if combat deafness is disabled. Usually when the game starts variable ace_common_setHearingCapabilityMap contains ["ace_hearing",1], and then after putting earplugs in it changes to ["ace_hearing",0.5]. But if combat deafness is disabled array ace_common_setHearingCapabilityMap is empty at the start but as soon as you put your earplugs in it set's it to ["ace_hearing",1] and after removing them it resets it too ["ace_hearing",0.5] which produces reverse effect. Possible solution is probably just block the use of the earplugs action if deafness is disabled.

**Steps to reproduce:**
- Set earplugs in.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Hearing module with combat deafness disabled.

**RPT log file:**
- N/A.

**Comment by PabstMirror** [comment]
@rebelvg - Thanks for the excellent bug report.

**Comment by rebelvg** [comment]
@PabstMirror Glad to help!

**Comment by rebelvg** [comment]
I did some tests and found out something strange. When combat deafness is disabled ```ace_common_setHearingCapabilityMap``` is empty at start, but the actual volume is cut in half for all (sound, radio, music).
Quick repro.

Add hearing module.
Set combar deafness to disabled.
Launch the mission.
Launch some music.
Example - ```playMusic "LeadTrack04a_F";```
Execute - ```call ace_hearing_fnc_updateVolume;```
which will double up the volume bringing it in to the 1 level (as it is on the start of the game with combat deafness enabled).
