### ISSUE TITLE
High Command bug

### ISSUE THREAD

**Issue by JCae2798** [acemod/ACE3#4921]
**Arma 3 Version:** Version: 1.69.140442

**Mods:**
- `@CBA_A3` (Current release)
- `@ace` (see below)

**Description:**
ACE breaks High Command feature in ARMA.  Both current build and DEV build have bugs.  Current build throws below error, where current DEB build crashes ARMA.

Is it possible this is because my shortcut for HC is CRTL + SPACE as it is for ACE for opening doors slightly
?

**Steps to reproduce:**
REPO mission attached.  LOAD CBA and ACE
Repo mission download:  https://www.dropbox.com/s/crg4t2pvxozjsok/HCBug.VR.zip?dl=0

**Where did the issue occur?**
Single Player

**Placed Modules:**
NONE

**RPT log file:**
For current build, below is the error that occurs:
_intersections = lineIntersectsSurfaces [AGLToASL _positi>
10:37:32   Error position: <lineIntersectsSurfaces [AGLToASL _positi>
10:37:32   Error Type Any, expected Bool
10:37:32 File z\ace\addons\interaction\functions\fnc_getDoor.sqf, line 11

**Comment by JCae2798** [comment]
After further testing, if i clear the key shortcuts for opening doors with ACE, the HC feature works....So its strictly ACE related...and the opening door feature.

**Comment by PabstMirror** [comment]
Issue is only with dev (not RC) branch
IIRC killzone was working on `lineIntersectsSurfaces` to fix the count param.

**Comment by PabstMirror** [comment]
```
_p0 = positionCameraToWorld [0, 0, 0];
_p1 = positionCameraToWorld [0, 0, 50];
lineIntersectsSurfaces [_p0, _p1, player, objNull, true, 1, "GEOM"];
```
will throw error

**Comment by PabstMirror** [comment]
Should be fixed soonish on dev branch.

**Comment by commy2** [comment]
ref: https://forums.bistudio.com/topic/151099-scripting-discussion-dev-branch/?page=48#comment-3155273
