### ISSUE TITLE
ACE3 + RHS SMAW + ROCKET LOADED

### ISSUE THREAD

**Issue by Instrid3** [acemod/ACE3#4922]
**Arma 3 Version: Stable
**CBA Version: Stable
**ACE3 Version: 3,8,3

**Mods:**
CBA 3,1,2
ACE 3,8,3
RHS USAF, AFRAF, GREF
CUP_Terrains
TFAR 0,9,2

**Description:**
Rockets loaded into SMAW tubes in the RHS SMAWs duplicate(or more didn't do the math just watched the over exaggeration of weight) weight. Once you load a round into the tube the weight overall exceeds 21 kilos. If you look at the weights below a SMAW Gunner should be able to carry at least 1 HEAA loaded and 1 DP on his or her person to equal that weight. Once the gunner loads the rocket he or she is subjected to the stamina penalty and has to basically sit stationary for a certain amount of time before he or she can accurately fire.  This is a penalty only a player suffers. 

-Realistic Weights-
-SMAW loaded with HEAA = 14.09kg
-SMAW loaded with HEDP = 13.59kg
-SMAW unloaded with 9mm SPOT tracer = 8kg
-HEAA = 6.4kg
-HEDP = 5.9kg
Spot tracer = .31 kg

**Steps to reproduce:**
Aresnal, Live in game multiplayer and singleplayer. Editor

**Where did the issue occur?**
Virtual Aresnal, Multiplayer, SinglePlayer, Editor

**Placed Modules:**
None and even when placed did not alter the outcome. 

**RPT log file:**
N/A

**Comment by PabstMirror** [comment]
Sounds like same problem as #4745

**Comment by Instrid3** [comment]
Thanks PBR <3

 F Heineken

**Comment by PabstMirror** [comment]
Will be fixed in arma 1.68
