### ISSUE TITLE
Trenches White

### ISSUE THREAD

**Issue by JJATH** [acemod/ACE3#4925]
**Arma 3 Version:** `1.66.139586` stable
**CBA Version:** `3.1.2.161105` stable
**ACE3 Version:** `3.9.0` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When I made trenches they were white. I've placed them down in Stratis, Altis and Tanoa and they were all white.

**Steps to reproduce:**
- I wish I knew how to reproduce this. I just placed the trenches down. 
**Where did the issue occur?**
- Self-Hosted Multiplayer, Singleplayer, Editor (Singleplayer)

**Placed Modules:**
- None. 

**RPT log file:**
http://pastebin.com/aAGKd3A0

**Comment by Glowbal** [comment]
Hi @JJATH, thanks for your report. You have provided the debug output from the debug button in the ACE menu, however the pastbin is missing the RPT log information. Could you please provide that?

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 160 days without any activity.

**Comment by SilentSpike** [comment]
Closing this as inactive and not enough information to go on.
