### ISSUE TITLE
Chairs float after being picked up

### ISSUE THREAD

**Issue by dansta** [acemod/ACE3#4926]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**

Picking up a chair and placing it down elevates the chair one 'block' upwards where it remains. Repeating the process elevates it even more. You cannot bring it down again as a player.

Sitting in said chair once elevated puts the character in sitting position as intended but the chair is floating in its new position. The chair may now injure the player.

**Steps to reproduce:**
- Place a chair on the map.
- Spawn a player. 
- Pick up the chair.
- Place it back on the ground.
- Make it worse. Pick it up.
- Place it down again.

**Where did the issue occur?**
- Dedicated server

**Placed Modules:**
None, will complete later.

**RPT log file:**

Will complete the ticket with this later on. Currently unavailable.

- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by jonpas** [comment]
Will wait for you to attach the RPT and fill out the ticket.

**Comment by dansta** [comment]
Closing this ticket. The problem is resolved in later versions.
