### ISSUE TITLE
Placing rifle into gunbag consumes magazine

### ISSUE THREAD

**Issue by Nich10solo** [acemod/ACE3#4927]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When placing a rifle into a gunbag, the magazine in the rifle disappears. When the rifle is pulled out of the gun bag, it has a magazine already loaded, but the player's magazine count is reduced by 1.  This can be prevented by placing the magazine in the rifle in the player's inventory before placing the rifle in the gun bag. The magazine is not going into the inventory nor is it being left on the ground.

I have had multiple magazines disappear at one swap, but I haven't be able to reliably reproduce it without RHS also being loaded. With no other mods other than CBA and ACE, I've been able to reliably produce 1 magazine disappearing per placement in gunbag. 

**Steps to reproduce:**
- Get rifle, several magazines in inventory, and the ace gunbag
- Note magazine count
- Place rifle in gun bag
- Get rifle out of gun bag
- Note magazine count has been reduced by 1

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Placed Modules:**
- Virtual Arsenal

**Comment by commy2** [comment]
Problem is with `addWeapon`.
`setUnitLoadout` for this?

**Comment by PabstMirror** [comment]
`setUnitLoadout` will break unique magazines and uniform/vest/backpack variables

**Comment by commy2** [comment]
True. Other ideas? Readding the missing magazine I guess, but that might be a bit complicated.

**Comment by Nich10solo** [comment]
Thank you all!
