### ISSUE TITLE
Otokar Cook-off

### ISSUE THREAD

**Issue by OspreyLight** [acemod/ACE3#4928]
Otokar Arma APC cook-off after ATGM hit for no reason.
It doesn't have ammunition inside because it uses RCWS with integrated ammo boxes.
also, there is a fire effect on the screen in the passenger compartment (behind the door of the fighting compartment)

ps. are there any plans on implementing R.A.M. mod ?

**Comment by commy2** [comment]
>ps. are there any plans on implementing R.A.M. mod ?
No.

**Comment by Glowbal** [comment]
We are accepting PRs to address the Otokar cook off. As @commy mentioned, we have no intention to implement the R.A.M mod into ACE.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 160 days without any activity.

**Comment by xrufix** [comment]
@commy2  I think this issue can be closed.

Since Arma 1.82, the Otokar ARMA has multiple magazines stored inside instead of on the turret. So cooking of makes sense to me.

In most cases the APC will blow off with the first hit by an ATGM anyway.

**Comment by PabstMirror** [comment]
Should have been fixed by #5605
