### ISSUE TITLE
Disabling "prevent instant death" isn't working. Players cant be killed.

### ISSUE THREAD

**Issue by zafjr** [acemod/ACE3#4930]
**Arma 3 Version:** `1.66.139586` stable
**CBA Version:** `3.1.2.161105` stable
**ACE3 Version:** `3.9.0` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Disabling "prevent instant death" does not work (while ace_server.pbo is on). Players still stick to being unconscious no matter how much damage he/she takes.

**Steps to reproduce:**
- 1st try. Set ace_medical_preventInstaDeath to "0" in serverconfig.hpp. Make mission parameter to also set ace_medical_preventInstaDeath to "0". Try to kill yourself (wont happen, stuck in unconscious).
- 2nd try. This time add ACE Medical Settings module and also set Prevent instant death to "disabled". Try to kill yourself (wont happen, stuck in unconscious).

**Video:**
- https://youtu.be/L666B39ej7E

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer (tried both) 

**Placed Modules:**
- Zeus Game master on 1st try. Zeus Game master AND ACE Medical Settings on 2nd try.

**RPT log file:**
- http://pastebin.com/NbfXA4C2
**serverconfig.hpp:**
- http://pastebin.com/VWyT35Jg

**Comment by Glowbal** [comment]
You have revive enabled.

**Comment by zafjr** [comment]
oh.... Wish i could delete this issue now :-/

**Comment by commy2** [comment]
Only the Github site admins can do stuff like this and they don't usually do that.
