### ISSUE TITLE
How to judge the difference between the unconscious state and revive state?

### ISSUE THREAD

**Issue by GodofMonkeys** [acemod/ACE3#4934]
I read the ACE's medical system introduction, learn how to use Advanced Medical System, and comes up questions.

In my Basic Medical system experience, when somebody is unconscious and wounded, after we treat all wound and no pain and no blood loss, in this time will have two situation come in, one is he will wake up himself, another is he will need epinephrine to help him wake up.

So this is my assume, in the first situation , he is in unconscious state.
The second situation, he is in revive state.
Is my guess correct?

If is, my guess is:
1.Unconscious state: can wake up automatically, and can continue receive damage by bullet etc....
2.Revive state:can't wake up automatically, need another medicine help, can't receive any damage.

If there have any sign will show what state with patient? 

And in the Advanced Medical system, I see there is Cardiac arrest situation, is this will force patient into unconscious state? or revive state? 
Because these two will have different with PAK and CPR, unconscious state can heal him every wound and restore his heart rate by CPR, wait he wake up automatically, but in revive state we will use PAK to help him revive. (Like this #2785 )

And the last question is Medical Module, 
1."Prevent immediately die" will help who have serious injury into unconscious state or revive state?
2.If I turn off revive system, is unit will dead immediately even I turn on "Prevent immediately die"?

**Comment by GodofMonkeys** [comment]
Anothor question, what different about this two image?

Your official medical image:
![medical1](https://cloud.githubusercontent.com/assets/14052848/23224243/85df4e66-f968-11e6-8245-842de731f597.png)

And this is community:
![kahjvpc](https://cloud.githubusercontent.com/assets/14052848/23224267/9e369ef6-f968-11e6-86b3-83c8dfcfec3a.png)

What the image is correct about bandage effect?
And in first image, "Field dressing" is mean Bandage  (Basic)?

**Comment by jonpas** [comment]
Medical rewrite has no revive state anymore, so this has become redundant.

**Comment by Razzom** [comment]
https://cloud.githubusercontent.com/assets/5007509/16651304/62eb6e2e-4443-11e6-832a-5ca54b154307.png
https://github.com/acemod/ACE3/pull/4064
The revive state seems to be still part after the rewrite.
Ive got no clue though but I'm asking myself the same question.

**Comment by jonpas** [comment]
You are looking at a diagram from 2016.

**Comment by jonpas** [comment]
Our Slack right now, documentation is coming.

**Comment by commy2** [comment]
Pls don't revive months old issues.
