### ISSUE TITLE
Volume issues with combat deafness disabled

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#4935]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.9.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- This is a separate issue that is related to the hearing module. I did some tests and found out something strange. When combat deafness is disabled ```ace_common_setHearingCapabilityMap``` is empty at start, but the actual volume is cut in half for all (sound, radio, music).

**Steps to reproduce:**
- Add hearing module.
- Set combat deafness to disabled.
- Launch the mission.
- Launch some music, example - ```playMusic "LeadTrack04a_F";```
- Execute - ```call ace_hearing_fnc_updateVolume;``` which will double up the volume bringing it in to the 1 level (as it is on the start of the game with combat deafness enabled).

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Hearing module with combat deafness disabled.

**RPT log file:**
- N/A.

**Comment by PabstMirror** [comment]
I can reproduce in vanilla.

**Comment by rebelvg** [comment]
Oh wow, okay.

**Comment by PabstMirror** [comment]
Is fadeMusic supposed to start at 0.5 or is it bugged?
Should ear plugs even effect music?

**Comment by rebelvg** [comment]
Not sure. Gonna try this myself on vanilla.

**Comment by dedmen** [comment]
A comment to the `Should ear plugs even effect music` I don't think so. 
We are using Music in Missions like many People probably do. And we would sometimes like the Music not to be affected by the deafness.
@KiritoKun223 can tell more.
Also this breaks the Zeus Music Module's Volume setting. As the Volume is almost instantly getting reset by ACE hearing.

**Comment by rebelvg** [comment]
Did some tests. It seems that fadeSound starts at 1 in vanilla. But fadeMusic is at 0.5 for some reason.

**Comment by KiritoKun223** [comment]
as @dedmen said, also earplugs affect the music volume, but so do helmets, like the ones from RHS which have integrated earphones. When opening the music module of zeus, the sound is automatically set to like 50 percent with earplugs and to around 25 or less with the helmets. If you set it up, you can hear the volume jump to the point where you set it to, but nearly instantly going back to 50 or 25 percent, even though the volume slider doesnt move a bit. Re-opening the music module results in it being 50 or 25 percent again

**Comment by rebelvg** [comment]
So fadeMusic is 0.5 at start isn't a bug. It's a feature according to the wiki.
https://community.bistudio.com/wiki/fadeMusic

**Comment by PabstMirror** [comment]
I'm leaning towards ACE just ignoring `fadeMusic` and not touching it at all.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
