### ISSUE TITLE
Fire on Critical Hit [suggestion]

### ISSUE THREAD

**Issue by OspreyLight** [acemod/ACE3#4936]
Adding fire for certain types of vehicle critical hits.

**- Ground vehicles**
Fuel tank/engine critical hit:
**starts fire** >and leads to> **engine failure**/and/or/**ammo explosion if appropriate**/and/or/**crew injury if appropriate**
**- Aircraft**
Fuel tank/engine critical hit:
**starts fire in flight** >and leads to> **engine failure**/and/or/**systems failure**/and/or/**crew injury**

Fire triggering chance should be adjusted for different types of projectiles like AP and HE.
Crew injury and systems failure times after the start of fire should be adjusted for different vehicle configurations.

^edited^

**Comment by bux** [comment]
What's this?
Please take your time to formulate proper sentences.

**Comment by commy2** [comment]
This belongs in #3594 I think.

**Comment by bux** [comment]
You're right @commy2.

@OspreyLight Please move it to the appropriate ticket linked by @commy2.

**Comment by commy2** [comment]
No need to repeat it there. Github already linked them. Making another post would just duplicate it.
