### ISSUE TITLE
fnc_loadperson.sqf / fnc_loadpersonlocal.sqf

### ISSUE THREAD

**Issue by geroge-011** [acemod/ACE3#4937]
**Arma 3 Version:** `x.xx` (stable / rc / dev) *ALL
**CBA Version:** `3.x.x` (stable / dev + commit hash) *ALL
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)*ALL

**Mods:**
- `@CBA_A3`
- `@ace`
- '@rhs'

**Description:**
- Loading people into vehicles might not work that well for modded vehicles, (only checks for cargo and gunner.
- Rolling down windows on the RHS humvees will turn the seat from cargo into turret. (having to roll up to window to load a patient in is annoying) 

**Steps to reproduce:**
- fullcrew [rhs_uaz_open,"all",true] //[[<NULL-object>,"driver",-1,[],false],[<NULL-object>,"cargo",4,[],false],[<NULL-object>,"Turret",2,[0],true],[<NULL-object>,"Turret",5,[1],true],[<NULL-object>,"Turret",0,[2],true],[<NULL-object>,"Turret",1,[3],true],[<NULL-object>,"Turret",3,[4],true]]

So instead of using the method use right now, I offer a solution to use https://community.bistudio.com/wiki/fullCrew instead, with the combination of moveInTurret commad.

ALL SEATS IN VEHICLES ARE EQUAL. TREAT THEM AS EQUAL AND STOP TURRET SHAMING TODAY!

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
- EVERYWHERE

**Placed Modules:**
- none

**RPT log file:**
- not needed.

**Comment by PabstMirror** [comment]
Related to #2965 (but this is a separate issue)
I think there was a reason we kept knocked out people out of turrets, need to verify if that is still the case.

**Comment by commy2** [comment]
Use `fullCrew` where exactly?

**Comment by xJenny99x** [comment]
fullcrew to get the list of open seats instead of _x emptyPositions "gunner" > 0

**Comment by xJenny99x** [comment]
_FFVTurrets = allTurrets [_vehicle,true] - allTurrets [_vehicle,false];

It should just prioritize cargo over turrets over commander over gunner.

**Comment by Phyma** [comment]
So do we want to fix this? I see alot of maybe we should not fix this. But are we fixing this? Are we loading people  inside turrets as a last resort?
