### ISSUE TITLE
Move the "Check temperature" into the Equipment group and rename it "Weapon temperature"

### ISSUE THREAD

**Issue by CamoSteve** [acemod/ACE3#494]
* Consider placing the "check temperature" inside the "equipment group". It's a function that is not used much, and is taking up prime real estate in the self-interaction main menu. Also consider changing the name of it to "Weapon temperature" rather than "Check temperature". Some people get confused at first, thinking "Check temperature" is a medical function.

* screenshot example: http://s15.postimg.org/kgrasj3tn/test1jpg1.jpg

**Comment by Jastreb** [comment]
This feature actually has nothing to do with realism. You cant accurately measure temperature of a weapon in the field, you can just assume its heating up and needs to cool down. So this can be removed altogether or < insert proposal here >.

**Comment by esteldunedain** [comment]
@CamoSteve, those are good ideas. I'll do exactly that.

> You cant accurately measure temperature of a weapon in the field

We don't display accurate temperatures, just a bar from green empty to red full that goes from ambient temperature to scorching hell hot. That kind of info you DO get on the field, by putting your hand close to the barrel / touching it / hearing the gun sounds / seeing smoke, etc

**Comment by esteldunedain** [comment]
BTW, this is basically a feature request and should have been included on the correct thread. I'll let it slide because it's actually a good solution.

**Comment by jaynus** [comment]
BLASPHEMY! BURN IT!

:thumbsup:

**Comment by Jastreb** [comment]
Sorry I thought it displaying temperature in degrees, haven't actually checked. Fine by me, whatever its called.

**Comment by CamoSteve** [comment]
My bad, I was talking about this on the the medical slack group, and someone said to either make a ticket or post on the feature request post. ;)

**Comment by esteldunedain** [comment]
GIVE ME FIFTY PUSHUPS RIGHT NOOOOWWW.

Nah, no problem guys

**Comment by esteldunedain** [comment]
![arma3 2015-04-11 19-33-05-436](https://cloud.githubusercontent.com/assets/7674951/7103532/e1865130-e081-11e4-8076-17786dde2397.jpg)

**Comment by CamoSteve** [comment]
:+1:

**Comment by BryanBoru** [comment]
i actually thought it was ambient temperature first time i saw it. but sometimes i dumb alot.

**Comment by esteldunedain** [comment]
> I actually thought it was ambient temperature first time i saw it. 

I've seen youtubes videos in which they even speculated it was the body temperature. So yes, I think it was ambiguos enough to generate confusion, at least for those who didn't use AGM. I should be less confusing now.

**Comment by Jastreb** [comment]
Maybe you should add a new item for that.

![Image of Item](http://i.ebayimg.com/00/s/Njg5WDY4OQ==/z/L08AAMXQVT9SsTZC/$_35.JPG)

:trollface:

JK
