### ISSUE TITLE
IR Strobe detaches after time interval

### ISSUE THREAD

**Issue by dedmen** [acemod/ACE3#4946]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.9.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
The time seems to be around 10 minutes.
Bux said it might be the lifeTime of the strobe. But it still continues blinking after it detaches.
I sure sounds to me like the batteries of the strobe ran out and it should stop blinking. But it continues blinking for atleast 5 minutes.

After it detaches 
`player getVariable ["ace_attach_attached",true]`
returns `[[<NULL-object>,"B_IR_Grenade"]]`

**Steps to reproduce:**
- Attach vanilla Nato IR strobe
- Go afk for 10-20 minutes
- Move a few steps away and the IR strobe will be floating in the air behind you

**Where did the issue occur?**
- Dedicated

**Comment by Phyma** [comment]
```
player getVariable ["ace_attach_attached",true]
returns [[<NULL-object>,"B_IR_Grenade"]]
```
After about 4 minutes.

**Comment by Phyma** [comment]
Working on fix. Have made it disappear on self attach. But it will get removed after 5 minutes. Working on same bug for vehicles. 

Should it get removed or just refreshed?

**Comment by Phyma** [comment]
#5233

**Comment by bux** [comment]
Hm, one would need to research how long an IR grenade's battery life is

**Comment by Phyma** [comment]
Just a quick look around Google and I can't find a ir grenade. 
But a small strobe like http://www.eod-gear.com/eod-ir-strobe-light/
Is one AA battery and with max setting it will blink for 4h and 30 minutes. 
But the grenade is bigger that this thing so say about 8h?

**Comment by bux** [comment]
Agreed. As it's probably unlikely that a mission lasts 8h IR grenades probably should just get refreshed. Opinions?

**Comment by PabstMirror** [comment]
What about just tweaking the `timeToLive` config?

**Comment by Phyma** [comment]
yeah if we say refresh i say we just change the config.

**Comment by Drofseh** [comment]
I found this one that is closer to what is in game and has a battery life of up to 250hrs.
https://tnvc.com/shop/guardian-dual-function-infrared-beacon/

**Comment by Phyma** [comment]
Tried to set the B_IRStrobe to this below:
```
class CfgAmmo {

    class IRStrobeBase;

    class B_IRStrobe: IRStrobeBase {
        timeToLive = 1e10;
    };
};
```
The grenade still disappears and the B_IR_grenade dosent have a timetoLive (never had) and This config changes the values so it works. But dosent fix the issue.

Will fix the PR so it will refresh instead of destroy.

**Comment by Phyma** [comment]
Will make it refresh instead!

**Comment by dedmen** [comment]
IR strobe has hardcoded time limit of 30 minutes in the engine.

**Comment by Xyaren** [comment]
If they have such along battery life, you should be able to detach them and reuse them later.

**Comment by dedmen** [comment]
Please mark as BI's fault, for the engine hardcoded lifetime.
I'll see what I can do about that.

**Comment by commy2** [comment]
Well yeah. All you need is to keep a tracker running attaching a new one whenever the old one is swallowed by the engine.

Or dedmen fixes it in the game code instead.

Close?

**Comment by dedmen** [comment]
Close once I managed to fix it, then recheck if we need to do anything else.

**Comment by JasonO99** [comment]
Was a fix ever applied to the game engine or to ACE to stop this?
