### ISSUE TITLE
"Point a finger at" not working

### ISSUE THREAD

**Issue by QuentinIUT** [acemod/ACE3#4947]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2`
**ACE3 Version:** `3.8.3`

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
The function "point a finger at", previously included in an external mod, seems not to be working in Ace.

**Steps to reproduce:**
Go in game, check in your keybinds the key used by the function, then try to point a finger at something, nothing happens. The issue appears with or without other mods, whatever the key chosen is.

**Where did the issue occur?**
Anywhere in game.

**Placed Modules:**
None

**Comment by PabstMirror** [comment]
The setting for it is disabled by default.
You need to either place down the module (I think it's called ace pointing)
or enable the setting in ace_settings for the mission or server.

**Comment by QuentinIUT** [comment]
Oh I see, I saw the module but as the default choice when you place it is "enabled" I thought that it was the default behaviour, even when the module is not placed. Now all is working as expected, but I think it's something that should be mentionned in the wiki. Is it possible to modify the [Finger](https://ace3mod.com/wiki/feature/finger.html) article this way ?

**Comment by PabstMirror** [comment]
Whenever we switch to CBA settings, we could probably set the default to enabled
