### ISSUE TITLE
AtragMx : relative humidity calculation ineffective

### ISSUE THREAD

**Issue by Laid3acK** [acemod/ACE3#4951]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.9.0 / 3.8.3` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- AB enabled, AtragMx opened, the relative humidity calculation has no effect on the elevation.

**Steps to reproduce:**
- Open the AtragMx, choose a cartridge, enter a distance and play with the relative humidity by checking the elevation.

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- Advanced Ballistics module enabled manually.

**RPT log file:**
- https://gist.github.com/J3aLeiNe/bb953c60b042f5f3eb89d35c0025c7fe

**Comment by jonpas** [comment]
Possibly just not implemented yet. @ulteq

**Comment by J3aLeiNe** [comment]
Not implemented since the AB stand alone version if i remember correctly
and a tiny impact on the elevation.
Maybe negligible in fact but it should work well ?
