### ISSUE TITLE
"ace_tracers.pbo" incompatibility with RHS 7.62x39

### ISSUE THREAD

**Issue by GeorgRavioli** [acemod/ACE3#4953]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.9.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHSAFRF
```

**Description:**
- When using optional "ace_tracers.pbo" with RHS, AKM magazines (57-N-231 and 57-N-231(89)) have red reload tracers, instead of the proper green. AKM tracer magazines (57-N-231P) are fine, and show the green tracer.

**Steps to reproduce:**
- Run Arma 3 with mods mentioned above, and "ace_tracers.pbo" loaded. Go into Virtual Arsenal. Choose any 7.62 AK from RHS (AK-103, AK-104, AKM, AKMS, etc.). Load either 57-N-231 or 57-N-231(89) magazine. Fire all 30 rounds. Notice the color of the last 4 tracer rounds.

**Where did the issue occur?**
- Singleplayer / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- http://pastebin.com/TQ2rkJ0J

**Comment by Glowbal** [comment]
Hi @GeorgRavioli, thanks for your issue. We host the RHS compat pbo's in our repository but do not actively maintain them and expect the community to contribute to those.

We are accepting PRs to address the issue mentioned here. Please let us know if you need any assistance or directions on how to go about solving this, or join our Slack.

**Comment by 11RDP-LoupVert** [comment]
Would like to help but am not sure how to do it properly. Could you please provide directions @Glowbal ?

**Comment by Dystopian** [comment]
RHS bug. By default (without ACE) 57-N-231 and 57-N-231(89) magazines have **white** reload tracers, instead of green.
RHS should overwrite this parameter:
```
class CfgAmmo {
	class rhs_B_762x39_Ball: B_762x51_Ball {
		model = "\A3\Weapons_f\Data\bullettracer\tracer_green";
	};
};
```
Here is patch for fixing: https://yadi.sk/d/4JK4_SYi3GYaQG
