### ISSUE TITLE
CPR revive whitout PAK

### ISSUE THREAD

**Issue by Don79** [acemod/ACE3#4959]
**Arma 3 Version:** `1.66.139586` (**stable** / rc / dev)
**CBA Version:** `3.2.1.170227` (stable / dev + commit hash)
**ACE3 Version:** `3.9.0` (stable / dev + commit hash)

**Mods:**
```many :-)
- CBA_A3
- ace
```

**Description:**
**Advanched Medical System 3.7.0**
The issue is: CPR dont awake the patient!
Before the new wounds (3.7.0) patch, working fine.
Now must using the PAK (=cheat/respawn) to awake the patient.
Befor this patch i give 2-3 CPR and the patients heart rate goes from 0 to 40 bpm.
Now the issue is: - i give cpr and the pulse stay on 0 (zero)
-the patient have blood pressure but heart rate is 0 (zero) 
-the medical loop sets all heart rate under 60 to 0 again!
When i using PAK dont need to stable blood pressure, dont need morphine, epinephrin... just use the cheat (PAK) and everything is fine.
I dont understand when the wounded has blood pressure but no heart rate...what is this a zombie? No pusle = no blood pressure = DEAD!
Correct revive (reanimation) on real life: CPR 30/1min,1 Air insufflation (new age not need), CPR 30/1min... 3x-4x no reaction +Epinephrin and restart CPR 30/1min...
My question is why can i not revive with CPR and Epinephrin in game? (adv.medic)
My clan want to play very realistic, but the PAK isn't realistic.
The medik is a very good game in game, but with PAK revive dont need a medic post.
(defibrillator in game?) :-)
Who dont play realistic and dont have time, use PAK this is ok! 
But who playing very realistic an love medic role with CPR & epinephrin and hawe time, make him this possibility.
 

THX for reading my bad englisch!
I hope you understand my question!
Clan: M.A.R.K. (Hungarian Arma Realsim Group in englisch translate)
with regard Sándor Csicsó

**Comment by K4my** [comment]
Same Request here. I see no specific reason why at advanced medical isnt possibility to restart hearth rate by CPR.. PAK is big cheat in the game, and I really dont want to see it at realistic games, its ok if its used at vehicles or some medical centers ok, but on the field, nobody should have this possibility, i suppose even CLS should not have this possibility... Please ACE, do somethink with it

**Comment by commy2** [comment]
Dup #2728
