### ISSUE TITLE
No Usage Guide for updated AtragMX

### ISSUE THREAD

**Issue by ZKatz** [acemod/ACE3#4963]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Recent update 3.9.0 has changed some features of the AtragMX, however there is still no description of how usage has changed. There is also no description for usage and functions provided for the AtragMX at all by the ACE team (https://ace3mod.com/wiki/feature/atragmx.html). I do appreciate all the work that has gone into creating this system, but I would like to be better understand and be able to more accurately use the assets the ACE team has created. 

**Steps to reproduce:**
- NULL

**Where did the issue occur?**
- NULL

**Placed Modules:**
- Advanced Ballistics

**RPT log file:**
- NULL

**Comment by bux** [comment]
https://www.horusvision.com/download/manual_Horus_ATrag-v385.pdf

**Comment by Glowbal** [comment]
We are accepting help with improving the documentation on this.

**Comment by ZKatz** [comment]
Yes, sorry for not responding before. I've read over the document you sent
me. It's helped clear up some questions I had. Right now I'm in the middle
of midterms, next week is spring break. I can't promise they it will be
done by the end of spring break but I'll attempt to do so.

I only have one question which is in regards to the zeroing of every rifle.
It's my understanding that the last update made all rifles zero to 100 by
default with each scope. However, in different environments the zero is
bound to change, I wanted to ask if the base zero takes that into
consideration?

**Comment by PabstMirror** [comment]
Since 3.9 vanilla zeroing is always taken into account

Ref#4642

**Comment by J3aLeiNe** [comment]
The AtragMx can be "Ready to Fire" with 9 steps (with MV table updated if necessary, etc ...),
i can take the screenshots and make a quick explanation,
i can make a quick explanation for the truing tool too.
But i don't know how to update the AtragMx's wiki ...
There is certainly a documentation for that but i didn't find.

**Comment by bux** [comment]
@J3aLeiNe 
https://github.com/acemod/ACE3/blob/master/docs/wiki/feature/atragmx.md

Markdown Editor: http://dillinger.io/

**Comment by J3aLeiNe** [comment]
My god ...

**Comment by PabstMirror** [comment]
Thanks to @Laid3acK  
Closed by #5031
