### ISSUE TITLE
Question: How to make custom building become medical building via config.cpp?

### ISSUE THREAD

**Issue by GodofMonkeys** [acemod/ACE3#4966]
How to make custom building become medical building via config.cpp?

I make a custom medical tent, and want to add a ability to pack and unpack this tent via ACE interactive button.
So I want to define this building default is medical building when it spawn.

Have you any parameter can add on building's config.cpp ? (CfgVehicle)

**Comment by PabstMirror** [comment]
Ref https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_isInMedicalFacility.sqf

Right now we just use a look up table.
I think the main reason is that this allows us to be compatible with other terrains without requiring compat configs.

Two ways to get your building compatible,
- We can add your building's classname to the list
or
- Your building can run the init line of `(_this select 0) setVariable ["ace_medical_isMedicalFacility", true]`.

**Comment by GodofMonkeys** [comment]
@PabstMirror
Thanks for reply, I will use init to do that.

:)
