### ISSUE TITLE
Air burst ammunition to XM307 grenade machine gun 

### ISSUE THREAD

**Issue by sammaelio** [acemod/ACE3#4967]
Arma 3 Version: 1.66.139586
CBA Version: 3.2.1.170227 
ACE3 Version: 3.9.0

ACE3 already have Air burst ammunition  on ZSU-39 Tigris

Please add High Explosive Air Burst grenades to XM307 grenade machine gun 

https://en.wikipedia.org/wiki/XM307_Advanced_Crew_Served_Weapon

**Comment by commy2** [comment]
Feature requests go here: #3594

**Comment by CCRcmcpe** [comment]
That's definitely a good thing to have.

**Comment by Drofseh** [comment]
@CCRcmcpe please don't bump old closed issues or PRs, if you have a feature request is belongs in #3594
