### ISSUE TITLE
Map Markers and Waypoints

### ISSUE THREAD

**Issue by DevastatorCM** [acemod/ACE3#4970]
**Description:**
Is it possible to make map markers only transferable to other maps if both players are in a given distance and their maps are open?
Situation is following, although difficulty settings are high when ground units marks positions on the map the pilots are still able to see them which makes no sense to give coordinates..

BI has possibility to disable the waypoints which is fine but when it comes to pilots it should still allow them to use waypoints. Can it be done something in this direction? Planes have advanced navigation systems so seeing waypoints on screen is not killing the realism but it does by infantry

**Comment by commy2** [comment]
Feature requests go here: #3594
