### ISSUE TITLE
I have to raise some issues

### ISSUE THREAD

**Issue by ZiGitHo** [acemod/ACE3#4972]
1.The soldier's strength is not too bad, I think a normal soldier should have the ability to load continuous jogging at least more than 5 km distance, because a civilian can continuously running several kilometers in the circumstance

2.the leg injured soldiers cannot stand up , but he can run after bandaged, I think, these leg injured soldiers should only walking or crawling.

3.ace3 cannot support campaigns content，can you develop a campaign support mod

4.after walking a few meters to look at the telescope is like the neck movement

**Comment by GeorgRavioli** [comment]
1. ACE's stamina system can be adjusted per mission, there are fields within the module you can change to suit your liking.

2. ACE advanced medical has a closer desired effect with leg injuries (many times soldiers who have gunshot wounds/avulsions in the leg cannot run until bandaged, stitched, and/or given a Personal Aid Kit).

3. request

4. Holding a rifle steady is hard when you're encumbered and tired.

**Comment by commy2** [comment]
OK.
close?
