### ISSUE TITLE
Character let's go of fastrope to fast

### ISSUE THREAD

**Issue by MrMittensTheCat** [acemod/ACE3#4973]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
Latest stable
**CBA Version:** `3.x.x` (stable / dev + commit hash)
Latest stable
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)
Latest stable
(Every mod and it's version is managed by steam workshop)

**Mods:**
- CBA_A3
- ace
-Vcom Ai V2.81
-Ares mod Achilles(0.0.5)
- Some maps(CUP,...)
- All RHS 
-Ace Compat for RHS

**Description:**
- When I fastrope from a helicopter my character let's go of the rope to fast and falls to his death. This was only tested with an AI pilot and the helicopter has an altidude of 30m and the rope vissually touches the ground 

**Steps to reproduce:**
- AI chopper with flyinHeight 20 and FRIES enabled also some waypoints with a hold for allowing fastrope

**Where did the issue occur?**
- Editor(Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- If this is needed I will follow up with one when I get to my Arma computer

**Comment by Glowbal** [comment]
Thanks for your report @MrMittensTheCat.

**Comment by BaerMitUmlaut** [comment]
AI helicopter pilots have a mind of their own and can start ascending when you start fastroping. Because the helicopter picks up speed you let go of the rope.

It's not recommended to use AI pilots for fastroping.
