### ISSUE TITLE
Ace Pointing.

### ISSUE THREAD

**Issue by Goldham89** [acemod/ACE3#4974]
**Arma 3 Version:** `1.66` (stable / rc / dev)
**CBA Version:** `3.3.1.170227` (stable / dev + commit hash)
**ACE3 Version:** `3.9.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
-RHS
-TFAR
```

**Description:**
- Request to change the ace pointing animation from the karate chop to the actual point animation

**Steps to reproduce:**
- Point at something.

**Where did the issue occur?**
- N/A

**Placed Modules:**
- N/A

**RPT log file:**
- N/A

**Comment by Glowbal** [comment]
We are tracking feature requests in #3594.
