### ISSUE TITLE
Remove magic value occurances in the code base

### ISSUE THREAD

**Issue by thojkooi** [acemod/ACE3#4978]
We have some magic value occurances in various places in our code base. 

One of such examples is #4964. 

We should replace those magic values by macro defines. This would be an ongoing issue.

**Comment by commy2** [comment]
We almost exclusively use magic numbers without macros for IDC's in ACE:
https://github.com/acemod/ACE3/blob/98da86b74d4089bc3403d0b0c0074e6a46ce35d8/addons/optionsmenu/functions/fnc_onServerListBoxShowSelectionChanged.sqf#L33-L43

We also never use the DIK table for key codes:
`#include "\a3\ui_f\hpp\defineDIKCodes.inc"`

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
