### ISSUE TITLE
Arma 3 Server

### ISSUE THREAD

**Issue by JordehDevs** [acemod/ACE3#4980]
Okay, So this isn't much of an issue more of asking for help.

How could you please tell me how to install Ace into my server because I have been trying and trying and I couldnt find out how

**Comment by 654wak654** [comment]
It's not any different from installing on a client.

**Comment by PabstMirror** [comment]
Unzip CBA and ACE to your server's arma folder
Launch with `-mod=@CBA_a3;@ace`

Here is an example batch file (save as server.bat):
```
set ARMA3_PATH=C:\Arma3Dedicated
set CUSTOM_MODS="@CBA_A3;@ace;"
set DEFAULT_PARAMETERS=-port=2306 -nosound -nosplash -nopause -profiles=profiles -name=server

cd /D "%ARMA3_PATH%"
start "" arma3server.exe %DEFAULT_PARAMETERS% -mod=%CUSTOM_MODS%
exit 0
```

**Comment by JordehDevs** [comment]
I have installed it aswell as RHS mods, although I keep getting this stupid error, about ace_particals.pbo and I have done everything to try and make this work and nothing works, I have tried deleting the files, and restarting and have tried deleting the entire optional folder and I seriously cannot find it out

**Comment by bux** [comment]
@JordehDevs How about you paste the exact error you get here?

**Comment by JordehDevs** [comment]
https://gyazo.com/94fd8657e170aff5238a6c65f6b82f90

**Comment by bux** [comment]
https://community.bistudio.com/wiki/ArmA:_Addon_Signatures#Controlling_addon_signature_verification_on_the_server

There

**Comment by JordehDevs** [comment]
Ill take a look

**Comment by JordehDevs** [comment]
https://gyazo.com/c3c01eb8d27bc41a2577a6ec50772dce thats the new error

**Comment by commy2** [comment]
It pretty much says what you have to do.
Also, if the files _are_ there, make sure the versions of client and server match.

>I keep getting this stupid error

The error is not "stupid". You just might not be in the right mood for this if you name your folders "modsAndShit".

**Comment by JordehDevs** [comment]
xD I named that last night because I didnt know what to name it LOL
