### ISSUE TITLE
Ai can't use Mk6 mortars

### ISSUE THREAD

**Issue by brainslush** [acemod/ACE3#4981]
**Arma 3 Version:** `3.66` (stable)
**CBA Version:** `3.2.1.170227`
**ACE3 Version:** `3.9.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Ai can't use Mk6 Mortars b/c no ammo is loaded into the weapon. Also adding magazines via script to the weapon doesn't seem to fix the issue

**Steps to reproduce:**
- Open the editor place a player unit
- Place an AI target unit and an AI unit with a Mk6 mortar inside the boundaries of minimum and maximum fire distance
- For ease of use place a Game Master module  
- Run mission  
- Order unit in the static weapon to fire at the target unit
- Using the console one can check that the mortar has no magazine loaded

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- Mk6 Settings Module will have to pull the settings from the server later this day but basically everything is set to advanced or maximum realism.

**RPT log file:**
- Still collecting
- Still collecting

**Comment by AACO** [comment]
If you have the Mk6 settings modules cranked to full realism, you probably have ammo handling enabled. It actually replaces the standard mk6 mortar with the ACE mk6 mortar which takes separate magazines that are supposed to be hand loaded one by one through ACE interact.

If you only have AI using mortars I'd suggest just turning ammo handling off.
If that's not possible I'd suggest adding this to the mortar's init `this setVariable ['ace_mk6mortar_exclude',true];`
If for some reason that doesn't work, you can try to manually add the ace magazines to the mortar
```
ACE_1Rnd_82mm_Mo_HE
ACE_1Rnd_82mm_Mo_Smoke
ACE_1Rnd_82mm_Mo_Illum
ACE_1Rnd_82mm_Mo_HE_Guided
ACE_1Rnd_82mm_Mo_HE_LaserGuided
```

**Comment by brainslush** [comment]
Since we force all our module settings server side disabling is not an option but your suggestions work. Could be something for the Wiki
