### ISSUE TITLE
Nemmera (B_APC_Tracked_01_CRV_F) uses Vanilla rearm system

### ISSUE THREAD

**Issue by Gaspasar** [acemod/ACE3#4987]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.0` (stable)

**Mods:**
- CBA_A3
- ace

**Description:**
Nemmera still uses Vanilla rearm system.
i am not shure if this is intended. 
Driving Nemmera near another verhicle resupplies the ammunition automaticly. 
Refueling works like ACE should work. 
testet with seara and Sholef

**Steps to reproduce:**
Place a Nemmera and a sholef in the Editor.
Shoot some rounds with sholef.
Drive Nemmera near Sholef and get in Sholef. 
It Rearm itsel automaticly.

**Where did the issue occur?**
- Dedicated 
- Editor (Singleplayer) 

**Placed Modules:**
without any modules or with the rearm module placed.
Doesn't make difference.

**Comment by commy2** [comment]
Nemmera is the armored recovery vehicle?

**Comment by Gaspasar** [comment]
yes, you named it like that.
(In the real world i think its called Namera:
https://es.wikipedia.org/wiki/Namera)
The Vanilla name is CRV-6e Bobcat

the classname is:
B_APC_Tracked_01_CRV_F
