### ISSUE TITLE
Error in translation

### ISSUE THREAD

**Issue by DarkLordShade** [acemod/ACE3#4994]
**Arma 3 Version:** `1.66` (stable / rc / dev)
**CBA Version:** `3.2.1` (stable / dev + commit hash)
**ACE3 Version:** `3.9.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Error in translation of Russian language. Error in the name of the types of injuries. Error in ace_medical.pbo. STR_ACE_Medical_Wounds_Avulsion, STR_ACE_Medical_Wounds_Avulsion_Minor, STR_ACE_Medical_Wounds_Avulsion_Medium, STR_ACE_Medical_Wounds_Avulsion_Large.

 - I bad speak english, sorry =)

**Comment by PabstMirror** [comment]
Would "Отрыв" be better than "Рваная рана" for Avulsion?

**Comment by DarkLordShade** [comment]
You have two types of wounds translated as "Рваная рана". This is very confusing. Let Avulcia be "Авульсия".

**Comment by PabstMirror** [comment]
Will be fixed in medical-rewrite with 5f9f672f7f3e9bdad9148228af90bdf2cc66c3cc
