### ISSUE TITLE
Blackfoot Down Demo Placement Bug

### ISSUE THREAD

**Issue by conseanover** [acemod/ACE3#4996]
**Arma 3 Version:** `1.66` (stable / rc / dev)
**CBA Version:** `3.2.1` (stable / dev + commit hash)
**ACE3 Version:** `3.9.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- All RHS Mods w/ ACE3 Compat Patches
- Blastcore Phoenix 1.2
- Blastcore Tracers A3 FoxFort Edit
- All CUP mods w/ all ACE3 Compat Patches
- A-10
- F-14
- F-16
- F-15
- Cold War Crisis Mod Update 2
- Real World Weathers

**Description:**
-In SP mission "Blackfoot Down", cannot place explosives. I can navigate the menu normally, but when I try to place the explosives, he just drops them. I can arm explosives while they are on the ground, but the don't destroy the wreck, they just explode. If I do it twice, I fail the mission

**Steps to reproduce:**
- Try to place the explosives

**Where did the issue occur?**
- Singleplayer

**Placed Modules:**
- None

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by bux** [comment]
@conseanover I'm sorry, but we don't support the single player campaigns nor missions that aren't specifically desgined for ACE3.

It's because we change a lot of the vanilla systems (like explosives) and some of the scripts used in the campaigns aren't able to check for our changes.

Maybe you can disable ACE3 for this part and reenable it later.

**Comment by conseanover** [comment]
Thanks, I did that. Also remapped the self-interact menu buttons. Apparently some comps don't play well with the ctrl+window button, and mine was no different. The self interact menu would either stay on screen disabling my weapon, or the screen would go blurry as if the menu was up, but there would be no menu. Anyway, thanks for the help and thanks for this mod, it's extremely useful
