### ISSUE TITLE
Self Interact Menu Bugs in Cold War Crisis Mod Update 2

### ISSUE THREAD

**Issue by conseanover** [acemod/ACE3#4997]
**Arma 3 Version:** `1.66` (stable / rc / dev)
**CBA Version:** `3.2.1` (stable / dev + commit hash)
**ACE3 Version:** `3.9.` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- All RHS Mods w/ ACE3 Compat Patches
- Blastcore Phoenix 1.2
- Blastcore Tracers A3 FoxFort Edit
- All CUP mods w/ all ACE3 Compat Patches
- A-10
- F-14
- F-16
- F-15
- Cold War Crisis Mod Update 2
- Real World Weathers

**Description:**
- Menu either stays on screen permanently or does not appear at all

**Steps to reproduce:**
- Completely Random

**Where did the issue occur?**
- Singleplayer

**Placed Modules:**
- None.

**RPT log file:**
- None

**Comment by PabstMirror** [comment]
Need RPT

I tried it out with CBA/ACE/CUP/RHS + Cold War Crisis and couldn't reproduce.
Is there a specific mission it happens on or every map?

Perhaps you could try running with less mods and see if you can't work out the specific mod causing the problems.

**Comment by conseanover** [comment]
Sorry for taking so long to report back. Seems the problem was the default button mapping for the self-interact menu. After reading that some machines didn't really play well with that, I remapped it and haven't had the issue since. Thank you for the help

**Comment by PabstMirror** [comment]
Good to hear.
Some gaming keyboards will disable windows key in games. It may be a setting you can change in the driver/software of the keyboard.
