### ISSUE TITLE
Several GL automatic weapons - always noticeably destroys the game performance.

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5001]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.1.2.161105` (stable)
**ACE3 Version:** `3.9.0` (stable)

**Mods:**
- CBA_A3
- ace
- JSRS Sound Mod

**Description:**
Hi!
I really like the feature of ACE, in which almost all the weapons with the explosives have fragments. This is cool feature! However, if it is an automatic GL-weapon, then it noticeably slows down the game performance.  An automatic weapon has a great fire rate and thus gives rise to many fragments. Yes, the problem may not be noticeable if you only use a one automatic weapons and if the number of involved units is not high. But if player create a mission with several static automatic GL-turrets, several APC-Otokar ARMA, several MPAP Punisher(GMG), then the game is very much losing performance.  I don't mean a huge number of such units. Just add >=3 automatic units in the one battle and the problem can be visible.  I have a not weak PC, with CPU in 12 threads and 16 GB of RAM, but even I, in such moments notice a significant performance drop!

**Probably this problem can be solved by some tricks? Can be to add a smaller number of pieces for automatic weapons?  Or any other tricks.  Any solution to improve performance would significantly mitigate the problem.**

**Steps to reproduce:**
- place in the map (near big city) several automatic GL turrets (OPFOR)
- place in the map (near big city) several MRAPS (punisher) with GL turrets (OPFOR)
- place in the map (near big city) several APC (Otokar) with GL turrets (OPFOR)
- place several enemy Blufor vehicles (APC-Badger-IFV, MRAP-M-ATV(HMG) 
- go into battle

**Where did the issue occur?**
-  Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- none

**RPT log file:**
- not needed

**Comment by PabstMirror** [comment]
You probably want to look at changing the ace_setting `ace_frag_maxTrack`
It defaults to 500, but you might want it down to 1-3.
```
class ace_frag_maxTrack {
        typeName = "SCALAR";
        value = 2;
};
```

Internally we do probably want to reduce the chance of running the frag simulation on grenades from automatic launchers.

**Comment by ZeusWrath** [comment]
please tell me more precisely where exact I can change fragment numbers of all automatic GL? I'm not good in scripting

**Comment by PabstMirror** [comment]
Can take a look at https://ace3mod.com/wiki/framework/settings-framework.html
easiest way is to put this in the description.ext of a mission
```
class ACE_Settings {
  class ace_frag_maxTrack {
      typeName = "SCALAR";
      value = 2;
  };
};

**Comment by ZeusWrath** [comment]
Thank you!  If I understand you correctly ACE uses 500 fragments for each grenade shell!? As seems to me 500 is too many!  If you even made 250 it would be big enough/  Just think about it. This can increase performance and still remain fairly realistic

**Comment by PabstMirror** [comment]
maxTrack is the max number of rounds that can frag that are in flight that the system will track.
So if you can shoot 1 rounds a second and time of flight is 4 seconds, frag would be tracking 4 rounds.

**Comment by ZeusWrath** [comment]
Now after switching to 64 bit files the game got significantly better performance, smoother gameplay. FPS increased and the player enjoys the game, but only until automatic grenade launcher from ACE3-mod starts shooting!  At this moments, productivity falls by 80-90%.  Dear, ACE team, can't you see that this spoils the game? You need to optimize all automatic grenade launchers in the ACE3.  Minimum - it must not have a so many fragments.

**Comment by jonpas** [comment]
You have already been told how to lower the fragmentation, or even disable it.

If you want optimizations, you will have to make and pull request them, a system like that can hardly be optimized and that's why it's completely optional as well.

**Comment by ZeusWrath** [comment]
> You have already been told how to lower the fragmentation, or even disable it.

thank you for the personal leadership, but I'm not talking only about myself,  I'm talking about all users ACE3. As I said I have a pretty powerful computer and even I have trouble, this is not normal...

**Comment by ZeusWrath** [comment]
> easiest way is to put this in the description.ext of a mission

```
class ACE_Settings {
  class ace_frag_maxTrack {
      typeName = "SCALAR";
      value = 2;
  };
};

```
I tried this, but did not see noticeable difference. The game still slows down
