### ISSUE TITLE
Adding new magazines to LMG_Mk200_F?

### ISSUE THREAD

**Issue by Pergor** [acemod/ACE3#5002]
I'm trying to add a couple of newly configured magazines to the LMG_MK200_F, but it seems like ace_ballistics overwrites my addon. I don't really want to add a dependencie to ace_ballistics (since the mod is not supposed to be dependent on ace_ballistics) in the cfgPatches.
Is there any way to achieve that?
Current code (working without ace_ballistics):

`
class CfgPatches
{
    class mk200cfg
    {
        units[] = {};
        weapons[] = {};
        requiredVersion = 1.68;
        requiredAddons[] = {
			"A3_Weapons_F"
			,"A3_Weapons_F_Machineguns_M200"
		};
		version = "1.0";
    };
};

class cfgMagazines {
	class 200Rnd_65x39_cased_Box_Tracer;
	class 200Rnd_65x39_cased_Box_Tracer_red: 200Rnd_65x39_cased_Box_Tracer {
		displayName = "6.5 mm 200Rnd Tracer Box (Red)";
		descriptionShort = "6.5mm Tracer";
		ammo = "B_65x39_Caseless";
	};
	class 200Rnd_65x39_cased_Box_red: 200Rnd_65x39_cased_Box_Tracer_red {
		picture = "\A3\Weapons_F\Data\UI\M_200Rnd_65x39_CA.paa";
		displayName = "6.5 mm 200Rnd Box Reload Tracer (Red)";
		tracersEvery = 5;
		lastRoundsTracer = 3;
	};
};

class CfgWeapons
{
	class Rifle_Long_Base_F;
	
	class LMG_Mk200_F: Rifle_Long_Base_F {
		magazines[] += {"200Rnd_65x39_cased_Box_red","200Rnd_65x39_cased_Box_Tracer_red"};
	};
};
`

**Comment by PabstMirror** [comment]
1. Create a ace compat pbo for your mod that would add all 5.
2. We change ace to use the `magazines[] +=` config to add our magazine.
As far as I can tell this should be safe and it only really fails on inheritance, and `LMG_Mk200_F` shouldn't have any children with different mag configs.

**Comment by Pergor** [comment]
Ah, thanks for the clarification on point 2. I was really wondering about that.
