### ISSUE TITLE
ace_interact_menu_fnc_addActionToClass issue

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#5005]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.1` (rc1)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- ace_interact_menu_fnc_addActionToClass fails to add action if you're trying to add action while waiting for respawn.

**Steps to reproduce:**
Repro mission. https://www.dropbox.com/s/ylld7107gto91wp/ace_addaction_repro.VR.zip?dl=0
- Launch repro mission in multiplayer mode.
- Press repsawn.
- After respawn check self-interaction, only one action will be there.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- N/A.

**Comment by commy2** [comment]
`player` is null?

**Comment by rebelvg** [comment]
Nope.

**Comment by PabstMirror** [comment]
CBA bug, but a fix for now is to just do this:
```
addMissionEventHandler ["EntityKilled", {
    [] spawn {
        waitUntil {alive player};
        _action = ["custom_action_class", "ADD ACTION CLASS", "", {systemChat "custom_action_class";}, {true}, {}] call ace_interact_menu_fnc_createAction;
        ["CAManBase", 1, ["ACE_SelfActions"], _action, true] call ace_interact_menu_fnc_addActionToClass;
    };
}];
```

**Comment by commy2** [comment]
Should be fixed next CBA version.
