### ISSUE TITLE
extension ace_fcs.dll not installed

### ISSUE THREAD

**Issue by bennylin0823** [acemod/ACE3#5007]
sorry my English is not good 

Since arma 3 update after the emergence (extension ace_fcs.dll not installed) the error message as long as the map will be finished reading the game
![s_5806991935919](https://cloud.githubusercontent.com/assets/26524090/24081941/534cd4f2-0cf8-11e7-87c1-04998b1f8616.jpg)
![s_5807010568612](https://cloud.githubusercontent.com/assets/26524090/24081942/534f8d5a-0cf8-11e7-8202-dd9f6e4f3c5e.jpg)
![s_5807011370534](https://cloud.githubusercontent.com/assets/26524090/24081943/535948e0-0cf8-11e7-96be-71b6f778c3a0.jpg)

My mod is the latest version

**Comment by commy2** [comment]
Needs RPT file.

**Comment by PabstMirror** [comment]
Is this steam version of ace running on x64?

You can find rpt at `%localappdata%/Arma 3/`
e.g. `C:\Users\yourName\AppData\Local\Arma 3`
find most recent rpt and upload at https://gist.github.com/ and post link here.

**Comment by bennylin0823** [comment]
https://drive.google.com/drive/folders/0BwM1C2Q5prUzbmR4VmJKVTdJRUU
My RPT in here,thanks.

**Comment by PabstMirror** [comment]
Loading ace from `!Workshop\@ace`
```
22:41:53 Call extension 'ace_medical' could not be found
22:41:53 [ACE] (medical) INFO: Extension ace_medical.dll not installed.
```

Seems like there was some issue with publisher and 64 bit.

We are hoping to put out a new release very soon that should fix this.

Otherwise loading the mod from a normal folder should also fix.

**Comment by PabstMirror** [comment]
This should be fixed with today's release on steam.

Please let us know if you still have issues.
