### ISSUE TITLE
ace_interact_menu_fnc_removeActionFromClass issue

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#5009]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.1` (rc1)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The command doesn't delete action from the unit.

**Steps to reproduce:**
- Add this code into your mission.
```
_action = ["custom_action", "TEST ACTION", "", {systemChat "test action";}, {true}] call ace_interact_menu_fnc_createAction;
["CAManBase", 1, ["ACE_SelfActions"], _action, true] call ace_interact_menu_fnc_addActionToClass;

["CAManBase", 1, ["ACE_SelfActions", "custom_action"]] call ace_interact_menu_fnc_removeActionFromClass;
```
only this one works
```[typeOf player, 1, ["ACE_SelfActions", "custom_action"]] call ace_interact_menu_fnc_removeActionFromClass;```

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- N/A.

**Comment by PabstMirror** [comment]
removeActionFromClass doesn't support inheritance (for something like "CaManBase")
