### ISSUE TITLE
Not possible to change microdagr size and position.

### ISSUE THREAD

**Issue by Laho84** [acemod/ACE3#5012]
Arma 3 Version:1.68 stable
CBA Version:3.2.1.170227
ACE3 Version:3.9.0

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Microdagr gps opens up very large at the center of the screen. Minimap element is no longer resizable in the arma layout options. Not possible to change microdagr size and position.

**Steps to reproduce:**
New clean installation of arma. Open the microdagr.

**Comment by PabstMirror** [comment]
Looks like they are prepping new hud boxes for the Jets DLC and removed the GPS box layout.
But this means they also broke the ability to set the vanilla `ItemGPS` position :smile: 

We will have a proper fix in 3.10.
If it's really bugging you, you can try changing the position manually:
`profilenamespace setVariable ['IGUI_GRID_GPS_X', 0.1];` do for x,y,w,h

**Comment by LecksC** [comment]
New profiles don't have anything set in those variables, so to make the microdagr usable, you can use this (default old GPS position):
```
profilenamespace setVariable ['IGUI_GRID_GPS_X',1.38212];
profilenamespace setVariable ['IGUI_GRID_GPS_Y',0.589091];
profilenamespace setVariable ['IGUI_GRID_GPS_W',0.3];
profilenamespace setVariable ['IGUI_GRID_GPS_H',0.4];
saveProfileNamespace;
```

**Comment by commy2** [comment]
The `saveProfileNamespace` command does nothing.

**Comment by LecksC** [comment]
Good to know, Thanks. Edited.

**Comment by dundonator** [comment]
how do i do this>

**Comment by commy2** [comment]
Use the code from https://github.com/acemod/ACE3/issues/5012#issuecomment-289260737
in the editor debug console.
