### ISSUE TITLE
ACE TRACERS MISSING          ACE_isOptional = 1;

### ISSUE THREAD

**Issue by geroge-011** [acemod/ACE3#5015]
optional tracer pbo cannot be loaded if the server does not have it.

**Comment by jonpas** [comment]
Unless it is meant to be like that, aka global optional.

**Comment by xJenny99x** [comment]
It was client optional in ACE2. I figured it's the same intention for ACE3

**Comment by xJenny99x** [comment]
In ACE2, one would use ACE Clippy to enable tracers, which were client side only

**Comment by PabstMirror** [comment]
ace_tracers changes the `model` for ammo types.
I believe this can cause problems, and in general you want all machines to have the exact same configs.

There is also balance issues if one client runs tracers that are more/less visible.
So I think we want to keep it how it is.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
