### ISSUE TITLE
small adjust to the triage status names

### ISSUE THREAD

**Issue by PaxJaromeMalues** [acemod/ACE3#5016]
For Medical_Rewrite

**Description:**
in /medical/ui/triagecard.hpp the names for the triage stati are a bit out of date.
`selectTriageStatusMinor`
`selectTriageStatusDelayed`
`selectTriageStatusImmediate`
`selectTriageStatusDeceased`

**The in international TCCC defined categories are:**
`selectTriageStatusMinimal`
`selectTriageStatusDelayed`
`selectTriageStatusImmediate`
`selectTriageStatusExpectant`

`selectTriageStatusDeceased` If actually deemed necessary to include this status (Currently all deceased characters rag doll, right? Or has this been changed in the rewrite?)

Greetings and Thanks for all the hard work,
Pax

**Comment by mharis001** [comment]
Decided to only change `Minor` to `Minimal`.
