### ISSUE TITLE
Starting .editorconfig file with "." causes initialization issues

### ISSUE THREAD

**Issue by headedhorseman101** [acemod/ACE3#502]
The period infront of the .editorconfig and .gitignore files causes my computer to change their names to blank and make new file types. Please edit so that these have a name.

**Comment by PabstMirror** [comment]
They are called that because that's what they need to be called.
See https://help.github.com/articles/ignoring-files/.

I suggest you set your windows not show file extensions:
![image](https://cloud.githubusercontent.com/assets/9376747/7104207/9316dd08-e095-11e4-8bc2-9955d122baf2.png)

**Comment by headedhorseman101** [comment]
If my computer opens this with notepad, will this cause ACE 3 to not config properly?
