### ISSUE TITLE
DAGR, when adding WP its bearing still in DEG

### ISSUE THREAD

**Issue by omar2205** [acemod/ACE3#5024]
**Arma 3 Version:** stable
**CBA Version:**  stable 
**ACE3 Version:** `3.9.0` stable

**Mods:**
```
- CBA_A3
- ace
- Ares
- tfar
```

**Description:**
- When I add a WP in DAGR, (made sure I changed the DIR to mils) it still shows the direction in degrees

**Steps to reproduce:**
- Change the options direction to Mils
- Add a WP
- select GOTO WP and choose the WP
- check the DAGR
- Bearing is in DEG not mils

**Where did the issue occur?**
- Dedicated + Editor (Singleplayer)

**Comment by Churrofighter** [comment]
Just adding a picture of the bug: 
![arma3 2017-03-29 23-45-48-77](https://cloud.githubusercontent.com/assets/9594604/24478381/eb58b4e8-14da-11e7-976d-acaf0b4d956e.jpg)
