### ISSUE TITLE
x64 Freeze with TFAR

### ISSUE THREAD

**Issue by ilbinek** [acemod/ACE3#5025]
**Arma 3 Version:** `1.68` (stable / rc / dev)
**CBA Version:** `3.2.1` (stable / dev + commit hash)
**ACE3 Version:** `3.9.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- TFAR
- http://withsix.com/p/Arma-3/collections/gJ5WzecQaUGt0DJiAN30Dg/c-s-e-c---addony-na-server (All of these)
```

**Description:**
- Note that this happens only with TFAR activated. Games loads, freezes and stays freezed, whener you close it with TaskManager, error code - 0x00000001 – UNABLE_TO_INIT_DXGI. Which I believe is problem with ACE. The old x32 version works. Problem is occured whenever the x64 version is started. 

**Steps to reproduce:**
- Only start the game

**Where did the issue occur?**
- Main Menu

**Placed Modules:**
- Default

**RPT log file:**
- http://pastebin.com/21JrvCDy

**Comment by Robdemi** [comment]
I noticed that you are using @st_hud in the RPT log. Make sure you download the newest version. I had the same issue. Disabled St hud and it worked.

**Comment by ilbinek** [comment]
@Robdemi 
Thanks a lot! You just saved whole C.S.E.C. Milsim unit before using x32! You will be remembered as hero in our hearts!
