### ISSUE TITLE
ace_fcs.dll & ace_adcanced_balistics.dll error

### ISSUE THREAD

**Issue by BakaRed** [acemod/ACE3#5026]
**Arma 3 Version:** `1.68` (64-bit stable)
**CBA Version:** `3.2.1` (stable/`SteamVersion)
**ACE3 Version:** `3.9.1` (stable)

**Mods:**
```
- CBA_A3
- ace 
-TFR
```

**Description:**
- Extension ace_fcs.dll not installed. But the File is Installed.

**Steps to reproduce:**
- Don't know how this happense so the only thing im doing is to start Arma 3 with the mods and join on a Self-Hosted Multiplayer Server (they all using the same Mods like me)
![20170325003602_1](https://cloud.githubusercontent.com/assets/26662490/24317015/716069b4-10f3-11e7-8f42-68a4d04d8863.jpg)
![20170325003103_1](https://cloud.githubusercontent.com/assets/26662490/24317014/715cf48c-10f3-11e7-9211-c4cd4d522c31.jpg)

.

**Where did the issue occur?**
- Self-Hosted Multiplayer / Virtual Arsenal

**Placed Modules:**
- ACE3

**RPT log file:**
- https://github.com/BakaRed/BakaRed/commit/6303aae2bec1644464a7361320ca2cbe19d83c6e

**Comment by omar2205** [comment]
if you are using Arma3Launcher (BI's launcher)
check the **BattlEye** tab if **battleye** is actually  blocking the dlls

**Comment by BakaRed** [comment]
Nope BattleEye is not blocking the dlls ...

**Comment by majinisinpu** [comment]
I have same issue.
"fcs .dll"issue has not solved.
I'll tell you about my PC.
**Arma 3 Version:** Latest(not dev)
**CBA Version:**   3.2.1.1702272
**ACE3 Version:**   3.9.1

**Mods:**
http://withsix.com/p/arma-3/collections/hw_r40PGyUCaKcKDPwsaLQ/honhonhon-best
**PC specs**
HDD: 1TB
GPU: GTX 1060
RAM: 8GB
CPU: i7-4770

[Arma3_x64_2017-03-24_17-06-16.zip](https://github.com/acemod/ACE3/files/869653/Arma3_x64_2017-03-24_17-06-16.zip)

**Comment by commy2** [comment]
You need `ace_fcs_x64.dll` and not `ace_fcs.dll` if you're running the 64 bit executable. There is a bug with Steam were it does not copy DLL files correctly. You can get them by downloading ACE from github and not Steam.

**Comment by BakaRed** [comment]
They are both in the File 
![unbenannt](https://cloud.githubusercontent.com/assets/26662490/24321973/9aea463a-115a-11e7-9de7-79f4fe79dd03.PNG)

and here is a picture of my mods. 
![arma mods](https://cloud.githubusercontent.com/assets/26662490/24321974/a4db2038-115a-11e7-80d4-0ac1e142695c.PNG)

**Comment by commy2** [comment]
Make sure no anti virus software is blocking the dll's.

**Comment by BakaRed** [comment]
Nope Norton can't block games or won't block them.

**Comment by commy2** [comment]
There is nothing we (ACE Team) can do if your game can't read the dll files that are obviously present.

**Comment by BakaRed** [comment]
It work's now. I used the parameter

**Comment by omar2205** [comment]
may I ask what parameter option?

**Comment by Corsair556** [comment]
i fix that i use Arma 3 v1.68 CBA v3.3.1 and Ace v 3.9.2. i copy this files ace_advanced_ballistics.dll , ace_advanced_ballistics_x64.dll , ace_break_line.dll , ace_break_line_x64.dll , ace_clipboard.dll , ace_clipboard_x64.dll , ace_fcs.dll , ace_fcs_x64.dll , ace_medical.dll , ace_medical_x64.dll , ace_parse_imagepath.dll , ace_parse_imagepath_x64.dll ..... from C:\Users\user\Documents\Arma 3\@ace and copy past in main folder Arma 3.!!! That all
