### ISSUE TITLE
Can't load  prisoners into Vehicles?

### ISSUE THREAD

**Issue by JinougaF** [acemod/ACE3#503]
After I capture a prisoners,what to do to load him into Vehicles?I try to interactive the vehicles and can't find a option to load him?Is that we can't load prisoners now or I did something wrong?And what's the right way to load them?

And can't we load some items like bobybags or static weapon into a vehicle?

**Comment by esteldunedain** [comment]
It's not ready yet. Neither are logistics. Maybe it'll get implemented for the first release, maybe not.

Please follow proper procedures for bug reports in the future

Cheers
