### ISSUE TITLE
64-bit client crash during mission loading in MP

### ISSUE THREAD

**Issue by Gilatar** [acemod/ACE3#5033]
**Arma 3 Version:** `1.68.140.908` (Stable)
**CBA Version:** `3.9.1` (Stable)
**ACE3 Version:** `3..2.1.170227` (Stable)

**Mods:**
- ace
- CBA_A3

**Description:**
- I experience consistent game crashes on self-hosted and dedicated servers. While loading after joining or hosting a server and slotting up, the game will crash before reaching the briefing screen.

- Sometimes there are no mdmp or bidmp files generated.

- The only error message I get is the standard "[Arma 3 has stopped working](https://puu.sh/uYczg/197f88d1d9.png)".

- Tried to reproduce on 32-bit client and without addons but was unable to.

I am not running BattlEye, and, as far as I know, no anti-virus programs that would interfere with ACE's .dll files. Redownloaded both ACE and CBA, verified the game cache through Steam, updated graphic drivers along with .NET Framework and DirectX, but the issue still persists even though it's not 100% consistent.

**Steps to reproduce:**

**(Self-host)**
1. Launch game with only ACE and CBA loaded.
2. Go to the multiplayer server browser and host an internet/LAN server.
4. Select a slot and start loading.
5. 9 out of 10 times the game will crash before reaching briefing screen.

**(Dedicated server)**
1. Launch game with only ACE  and CBA loaded.
2. Go to the multiplayer server browser and connect to the dedicated server.
4. Select a slot and start loading.
5. 9 out of 10 times the game will crash before reaching briefing screen.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**Placed Modules:**
- None

**RPT log file:**
- [RPT File](http://pastebin.com/aRXD0FvL)
- [ArmA 3 Launcher Troubleshooting Report](https://www.dropbox.com/s/ardrylcqknjhd3d/ArmaReport_Log_20170325T200438_Gilatar.zip?dl=0)

**Comment by commy2** [comment]
Untick `-enableHT` and `-hugePages`. Otherwise ask BI support.

**Comment by Gilatar** [comment]
Disabled both but the game still crashes. Oh well.

I didn't even know -hugePages was a launch parameter and I certainly didn't enable it myself. Turns out the vanilla Arma 3 Launcher launches with it by default for some reason, as I'm not able to find the option anywhere on the launcher itself. Had to launch through ArmA3Sync, which I prefer anyway.

**Comment by jonpas** [comment]
Does it still happen after Arma 3 hotfix? If so, attach the minidump as well (`.mdmp` file next to RPT).

**Comment by commy2** [comment]
I'd say we close this as this is not something we can possibly fix and it has to be solved by BI.
