### ISSUE TITLE
Make use of setShotParents for adv throwing

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#5034]
**Arma 3 Version:** `1.68` (stable / rc / dev)
**CBA Version:** `3.2.1` (stable / dev + commit hash)
**ACE3 Version:** `3.9.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- New command ```setShotParents``` now allows to set the owner of the scripted grenade that should show up in the handleDamage EH as shooter and instigator.
Note: command accepts array with shooter and instigator, so instigator can be changed on pickup if someone else picks up your grenade and uses it incorrectly.
Note: setShotParents works for the grenade, but ace frag spawns shrapnel that doesn't have owner.

**Steps to reproduce:**
- N/A.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- N/A.

**Comment by commy2** [comment]
`setShotParents` only works on the server, but I have never got it to work in a MP environment whats-so-ever.

**Comment by rebelvg** [comment]
Just tried it on the dedicated server. Worked fine and reported the correct shooter and instigator in the Hit EH at least.
