### ISSUE TITLE
ace3 and infistar

### ISSUE THREAD

**Issue by neohlee** [acemod/ACE3#5035]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.1.2` (stable / dev + commit hash)
**ACE3 Version:** `3.9.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
-infistar
```

**Description:**
I installed ace3 on my server. I already had cba and other mods + infistar woking fine. But now i have this error : "BadButton on ESC: ACE Options (v0246)". And i probably guess it is what causes the infistar menu to not load. i cant use admin menu anymore.

**Steps to reproduce:**
Have a nice server with mods.
Try to enhanced the gameplay with ace3.
infistar admin menu not loading anymore.

**Where did the issue occur?**
- Dedicated 

my english is bad im sorry about it.
has any had this issue ? there must be a quick solution. i have seen many issue like this on forum. if anyone tells me how to fix this i can sharw with the french community.!
thanks in advance

**Comment by PabstMirror** [comment]
RPT might help, but it sounds like the issue is from infistar.
I think you should be able to run without `ace_optionsMenu.pbo` if that's the cause of the conflict.

**Comment by neohlee** [comment]
[gist](https://gist.github.com/neohlee/f20ccaff51c191f02148aee41dc39788)

**Comment by neohlee** [comment]
i also tried running serv/client without ace_optionsmenu, same thing :(

**Comment by commy2** [comment]
```
 7:25:45 Error in expression <isNull (findDisplay 46))};

if((__GETC__(life_medicLevel)) < 1) exitWith {
["Not>
 7:25:45   Error position: <(life_medicLevel)) < 1) exitWith {
["Not>
 7:25:45   Error Missing )
 7:25:45 File core\fn_initMedic.sqf [life_fnc_initMedic], line 71
 7:25:45 Error in expression <isNull (findDisplay 46))};

if((__GETC__(life_medicLevel)) < 1) exitWith {
["Not>
 7:25:45   Error position: <(life_medicLevel)) < 1) exitWith {
["Not>
 7:25:45   Error Missing )
 7:25:45 File core\fn_initMedic.sqf [life_fnc_initMedic], line 71
```

```
 7:25:43 Error in expression <aticModels setVariable [toLower (_array select ((count _array) - 2)), _cfgClass]>
 7:25:43   Error position: <select ((count _array) - 2)), _cfgClass]>
 7:25:43   Error Zero divisor
 7:25:43 File z\ace\addons\tagging\XEH_postInit.sqf, line 20
 7:25:43 Error in expression <aticModels setVariable [toLower (_array select ((count _array) - 2)), _cfgClass]>
 7:25:43   Error position: <select ((count _array) - 2)), _cfgClass]>
 7:25:43   Error Zero divisor
 7:25:43 File z\ace\addons\tagging\XEH_postInit.sqf, line 20
```

**Comment by commy2** [comment]
```
 7:25:49 Error in expression <bank setvariable ["robbed",false,true];
stash1 setvariable ["robbed",false,true]>
 7:25:49   Error position: <stash1 setvariable ["robbed",false,true]>
 7:25:49   Error Undefined variable in expression: stash1
```

Lots and lots of script errors in the mission.

**Comment by neohlee** [comment]
yes thanks for mentionning as it is not the point for why i came here.

**Comment by neohlee** [comment]
yes. this doesnt make infistar and ace3 work though haha

**Comment by commy2** [comment]
It could make them not work. One script error means *everything else* can exhibited unexpected behavior too.

**Comment by sargken** [comment]
Altis Life nube

**Comment by PabstMirror** [comment]
I don't think any of us have access to infistar; and I would bet it's obfuscated.

`BadButton on ESC: ACE Options (v0246)` 
All I can do is speculate, but I think infister might be searching for buttons on the escape menu as that's probably where hack/cheaters would put them.

There really isn't anything we can do, I would contact the mod's author and see if they can add compatibility for ace.
