### ISSUE TITLE
Format Optional pbos to be loadable in A3 Launcher

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#5036]
**Arma 3 Version:** `1.68` (stable / rc / dev)
**CBA Version:** `3.2.1` (stable / dev + commit hash)
**ACE3 Version:** `3.9.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
As per chat on slack #dev
A3 launcher seems to search for any folder named `addons` within your mods folder (no matter the level).  This means that formatting the optional mods  for example `optionals/ACE_RHSUSF_Compat/addons` would show. The 3CB guys already do a basic form of this.

+No more messing with compat files every update.
+If you don't use the A3 launcher the mods are prepacked to copy and paste out
+ Offical compat mod names makes server listings easier
-Potential spam of mods list (may want to limit to popular ones) 

**Steps to reproduce:**
_For example_
1. Create File structure `optionals/ACE_RHSUSF_Compat/addons`
2. Add pbo's in.
3. Load launcher and see it in the list

**Where did the issue occur?**
- Launcher

**Comment by commy2** [comment]
Good to know.

**Comment by john681611** [comment]
I'm too hungover to setup correctly but from what i can figure its change to `make.py` in `cleanup_optionals`
```python
file_name = "{}{}.pbo".format(pbo_name_prefix,dir_name)
                folder= "{}{}".format(pbo_name_prefix,dir_name)
                src_file_path = os.path.join(release_dir, project, "addons", file_name)
                dst_file_path = os.path.join(release_dir, project, "optionals",folder,"addons",file_name)

                sigFile_name = "{}.{}.bisign".format(file_name,key_name)
                src_sig_path = os.path.join(release_dir, project, "addons", sigFile_name)
                dst_sig_path = os.path.join(release_dir, project, "optionals",folder,"addons", sigFile_name)
```
something like that (I've never done file management with Python) You may need to make the folders first.
