### ISSUE TITLE
Any chance to let the players view locked in Interactive Menu?

### ISSUE THREAD

**Issue by JinougaF** [acemod/ACE3#504]
Hello,I noticed now when enter the Interactive menu the view of player could still move while move the mouse.Would ACE make the view locked after enter Interactive menu?It's really annoy 'cuz some time the view would move too far and can't see some options in interactive menu in screen.

But otherwise I like the new UI,outstanding work ACE team!Cheers!

**Comment by esteldunedain** [comment]
Please no questions on the tracker. For feature requests, use the appropiate thread. For discussion join in our public slack chat.
