### ISSUE TITLE
Weapon on Back and Holster dont work All Weapons

### ISSUE THREAD

**Issue by Sheppard85oc** [acemod/ACE3#5042]
**Arma 3 Version:** `1.68` and sometimes 1.66 stable
**CBA Version:** `3.2.1` stable
**ACE3 Version:** `3.9.1` stable

**Mods:**

- CBA_A3
- ace
RHS AFRF and USA
SMA 
and many Other. 
All Weapons...

**Description:**
Frist Time its some one with Arma version 1.66 and the Last RHS and ACE versions come. The Problem comes in the time not always. But since the Last Arma3 Update 1.68 Always. 
I and my Clan try to take our Rilfe on the Back. but thats dont work all have Standard Key Config. we Press 0 but nothing happend.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
1. Take a Rifle
2. Take a Pistol
3. Take a binocular
Do you have the Rifle in youre hand you press 0 "Nothing work" do you change to the Pistol and press 0 nothing happend. If you have a binocular, you can change with B thats workes normal but sometimes if you press 0 he Change to the binocular. But the First steps are more impotante. 

**Where did the issue occur?**
Its happend on All

**Placed Modules:**
its happend with and without Moduls on ALL maps. 

**RPT log file:**
Nothing Errors in RPT and Debug to find. No more Infos about that to find i am sorry.

**Comment by Sheppard85oc** [comment]
This here are all Mods we used in Clan too. A friend say me that he think thats Problem come from RHS AFRF if he trun off AFRF work all normal. But we have this Problem really since Version 1.68 and Ace 3.9.1 

http://www.armaholic.com/page.php?id=28557 ACE3
http://www.armaholic.com/page.php?id=31252 ACEX
http://www.armaholic.com/page.php?id=18767 Community Base addons A3
http://www.armaholic.com/page.php?id=23615 Task Force Radio
http://www.armaholic.com/page.php?id=24147 BW Mod
http://www.armaholic.com/page.php?id=27149 RHS US Armed Forces
http://www.armaholic.com/page.php?id=27150 RHS RARF
http://www.armaholic.com/page.php?id=31310 Project OPFOR
http://www.armaholic.com/page.php?id=30004 US Military Mod
http://www.armaholic.com/page.php?id=30045 Community Upgrade Project - Terrains Complet
http://www.armaholic.com/page.php?id=29949 Unsung Vietnam War Arma3
http://www.armaholic.com/page.php?id=20881 RH Pistol pack
http://www.armaholic.com/page.php?id=27146 HLC MP5 Pack
http://www.armaholic.com/page.php?id=28711 Chakra FN P90
http://www.armaholic.com/page.php?id=24621 HLC M60
http://www.armaholic.com/page.php?id=26428 SMA
http://www.armaholic.com/page.php?id=28645 3CB BAF Weapons
http://www.armaholic.com/page.php?id=23277 RH M4/M16 Pack
http://www.armaholic.com/page.php?id=27620 TF47 Launchers
http://www.armaholic.com/page.php?id=28246 TF47 Launchers- RHS Compatibility
http://www.armaholic.com/page.php?id=30614 Theseus Services
http://www.armaholic.com/page.php?id=26661 TRYK Multi Play Uniforms
http://www.armaholic.com/page.php?id=28647 FIR Pilots
http://www.armaholic.com/page.php?id=26419 Tac4Vests
http://www.armaholic.com/page.php?id=29622 TacVests
http://www.armaholic.com/page.php?id=27201 3CB BAF Units
http://www.armaholic.com/page.php?id=29033 3CB BAF Equipment
http://www.armaholic.com/page.php?id=30821 Smash Airborne Berets
http://www.armaholic.com/page.php?id=31349 Military Gear Pack
http://www.armaholic.com/page.php?id=27960 Huey Pack
http://www.armaholic.com/page.php?id=22594 F/A-18 Super Hornet
http://www.armaholic.com/page.php?id=25512 United States Air Force
http://www.armaholic.com/page.php?id=27203 3CB BAF Vehicles
http://www.armaholic.com/page.php?id=29663 F14D Standalone
http://www.armaholic.com/page.php?id=30025 F15 Standalone
http://www.armaholic.com/page.php?id=27766 F-16C Fighting Falcon Standalone
http://www.armaholic.com/page.php?id=31827 FIR A-10
http://www.armaholic.com/page.php?id=28903 Eurocopter EC-635
http://www.armaholic.com/page.php?id=28730 Arma2 C130J Port
http://www.armaholic.com/page.php?id=21614 Hidden Identity Pack [BETA]
http://www.armaholic.com/page.php?id=19689 ARP2 Objects
http://www.armaholic.com/page.php?id=27113 Camofaces
http://www.armaholic.com/page.php?id=28139 GAU-8/A Avenger
http://www.armaholic.com/page.php?id=30575 Advanced Towing
http://www.armaholic.com/page.php?id=31254 Advanced Rappelling [Fast roping]
http://www.armaholic.com/page.php?id=29929 Revo's Mine Detector
http://www.armaholic.com/page.php?id=29552 T-10 Parachutes
http://www.armaholic.com/page.php?id=27321 Wake Island
http://www.armaholic.com/page.php?id=27882 Kunduz Map
http://www.armaholic.com/page.php?id=12315 Fallujah
http://www.armaholic.com/page.php?id=19580 MCC4 - Sandbox

**Comment by PabstMirror** [comment]
I can't reproduce, but I think I could see how this could happen.
It would be a great help if you could try running the following code in the debug console (just launch the editor, put down a unit and hit preview, then hit escape to see)

```
player action ["SwitchWeapon", player, player, 99];
```

Let me know if that has any effect
if it doesn't try 999 instead of 99 and see if that does anything.

**Comment by Sheppard85oc** [comment]
Hi^^ 
I do what you say me 
player action ["SwitchWeapon", player, player, 99]; -> nothing happend
but with 

player action ["SwitchWeapon", player, player, 999]; -> he put weapon on holster. after code and click on Local. if you change the weapon after code 999 and click on local too

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/blob/master/addons/weaponselect/functions/fnc_putWeaponAway.sqf#L22

But also:
https://github.com/acemod/ACE3/blob/master/addons/weaponselect/functions/fnc_selectWeaponMode.sqf#L45
https://github.com/acemod/ACE3/blob/master/addons/weaponselect/functions/fnc_selectWeaponMuzzle.sqf#L45
https://github.com/acemod/ACE3/blob/master/addons/weaponselect/functions/fnc_selectWeaponVehicle.sqf#L34-L49

**Comment by commy2** [comment]
Also: https://github.com/CBATeam/CBA_A3/edit/master/addons/common/fnc_selectWeapon.sqf

**Comment by commy2** [comment]
@Sheppard85oc Can you try this too:
```sqf
player action ["SwitchWeapon", player, player, 250];
```
I want to know if 250 would be enough.

**Comment by Sheppard85oc** [comment]
Hi 
I have try to this too player action ["SwitchWeapon", player, player, 250];
I think thats the Speed of change the weapon right? 
I have it try with 250 150 50 and 350
I think 250 its enough

**Comment by commy2** [comment]
It's not the speed, it's a "weapon index". All equipped weapons, their muzzles (e.g. 5.56mm barrel vs. grenade launcher attachment) and their fire modes (semi, auto etc.) are listed in one large table and the way to holster a weapon is to select a mode beyond the last item in the table.

**Comment by Sheppard85oc** [comment]
Ahh okay i beginn to Understand. 
I test it with diffierent weapons and all 3 Slots of weapon 250 looks still fine.

**Comment by Sheppard85oc** [comment]
Hi^^
Can i still help? or maybe what testing for this error? ^^
