### ISSUE TITLE
Can load into ACE-Cargo of locked vehicles

### ISSUE THREAD

**Issue by McDiod** [acemod/ACE3#5048]
**Arma 3 Version:** `1.68.141112` stable
**CBA Version:** `3.2.1` stable
**ACE3 Version:** `3.9.1` stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
You can load stuff into the ACE-Cargo of locked vehicles. Once it's loaded you have to unlock the vehicle to retreive your things, since the main interaction node can't be accessed on locked vehicles.

**Steps to reproduce:**
1. Lock a vehicle
2. Put ammo box next to the vehicle
3. Load box into vehicle

**Where did the issue occur?**
Self-Hosted Multiplayer

**Placed Modules:**
None

**RPT log file:**
n/a

**Comment by Dystopian** [comment]
I'll fix it

**Comment by jonpas** [comment]
Marked with status/pending as per @Dystopian 's volunteering.
