### ISSUE TITLE
"script_mod.hpp not found" error on dedicated server launch

### ISSUE THREAD

**Issue by Oy-of-Mid-World** [acemod/ACE3#5051]
**Arma 3 Version:** `1.68.141112` (stable)
**CBA Version:** `3.21` (stable)
**ACE3 Version:** `3.9.1` (stable)

**Mods:**

- CBA_A3
- ace

- none other

**Description:**
Trying to set up a 64 bit dedicated server, using this command line: 

```
D:\ArmAServer\A3Master\arma3server_x64.exe -profiles=d:\ArmAServer\A3Master -port=2302 -config=CONFIG_Vanilla.cfg -world=empty -mod=@CBA_A3 -servermod=@aceServer
```

I get the following error message:

```
Include file z\ace\addons\main\script_mod.hpp not found.
```

during the addon initialization phase, followed by a crash (ArmA 3 has stopped working).

The server is set up correctly and works if I take away the "-servermod=@aceServer" section of the command line. "@ace" and "@aceServer" folders are set up in the ArmA main directory (D:\ArmAServer\A3Master), with the "ace_server.pbo" in the "@aceServer/addons" directory, all according to the ACE3 Installation guide and the Settings Framework page. The "serverconfig.hpp" is in place in "D:\ArmAServer\A3Master\userconfig\ace". 

I found this page:

https://github.com/acemod/ACE3/issues/3721

while searching for the issue, but it has not helped me at all, since I didn't change anything about the mod, just trying to run it as is. My best guess is that I forgot to put something in place, but I double checked everything and can't figure out what. I just think I'm missing something, since I'm fairly new to this. 

Any help or insight would be greatly appreciated.

Steam is not running, which is a requirement for launching the client on the same machine. It doesn't work with steam running either.

**Steps to reproduce:**
- Crashes every time. 

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
```
=====================================================================
== D:\ArmAServer\A3Master\arma3server_x64.exe
== "D:\ArmAServer\A3Master\arma3server_x64.exe" -profiles=d:\ArmAServer\A3Master -port=2302 -config=CONFIG_Vanilla.cfg -world=empty -mod=@CBA_A3 -servermod=@aceServer

Original output filename: Arma3Retail_Server_x64
Exe timestamp: 2017/03/28 17:18:21
Current time:  2017/04/02 21:05:31

Type: Public
Build: Stable
Version: 1.68.141112

Allocator: D:\ArmAServer\A3Master\Dll\tbb4malloc_bi_x64.dll
PhysMem: 7.9 GiB, VirtMem : 131072 GiB, AvailPhys : 5.8 GiB, AvailVirt : 131072 GiB, AvailPage : 13 GiB
=====================================================================

21:05:31 SteamAPI initialization failed. Steam features won't be accessible!
21:05:31 Source set
21:05:31 Initializing stats manager.
21:05:31 Stats config disabled.
21:05:31 sessionID: c543e7da8ed728ace2ef1bb7af6d50c8e5e3b20f
21:05:42 Unsupported language English in stringtable
ErrorMessage: Include file z\ace\addons\main\script_mod.hpp not found.
=======================================================
-------------------------------------------------------
Exception code: 0000DEAD  at A8CC7788
Version 1.68.141112
Fault time: 2017/04/02 21:05:46
Fault address:  A8CC7788 00:A8CC7788 Unknown module
file:     
world:    
Prev. code bytes: E8 07 55 06 00 48 8D 4C 24 20 FF 15 E0 08 13 00
Fault code bytes: 48 8B 8C 24 C0 00 00 00 48 33 CC E8 98 1A 06 00
=======================================================
note: Minidump has been generated into the file d:\ArmAServer\A3Master\arma3server_x64_2017-04-02_21-05-31.mdmp
```

**Comment by Glowbal** [comment]
You need to launch the server with ACE as well.

**Comment by Oy-of-Mid-World** [comment]
Okay...

Now I feel stupid, but am happy.... :-D 
It really makes sense when you put it that way. And of course it works. Thanks A LOT!
