### ISSUE TITLE
help with ace medical 

### ISSUE THREAD

**Issue by nat2741** [acemod/ACE3#5053]
so last night while we were doing a miss drop mission a few people got injured and collapsed that fine and all we have trained medics that can deal with this, but what we dont understand is this and how to deal with it.

we use the advanced medical and no inster death on are servers.

so up patch the injured  part of the body all cool 
cheek there stats they have no heart rate
but they have blood pressure, even when blood pressure comes back up you cant get a heart rate
and they never seem to wake up. even after giving CPR saline in the field eppi and yiu just caint get that heart rate.
cheek the video below to see what i mean 

https://www.twitch.tv/videos/132999154?t=01h26m30s

**Comment by Phyma** [comment]
I'm having problems understanding and video is now gone :( 
Have you experienced this problem again?

**Comment by BaerMitUmlaut** [comment]
The unit was in the revive state. Either disable the revive system or use a PAK to get him back up.
