### ISSUE TITLE
Request - Mk6 Mortar Round Fuses

### ISSUE THREAD

**Issue by minaelias** [acemod/ACE3#5058]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Please add Fuses to the Mk6 mortar rounds such as  Point-Detonating Fuzes, Timer fuze etc. 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
N/A
**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.
MK6 Mortar

**Comment by BaerMitUmlaut** [comment]
Feature requests belong into #3594.
