### ISSUE TITLE
Sound Muting (tank/pilot helmet, headphones, etc.) is not working good

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5059]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1.170227` (stable)
**ACE3 Version:** `3.9.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- JSRS soundmod
```
**Description:**

We all known, some helmets, or headgear with headphones muffle the sound in the game, but unfortunatelly it does not work good.  If the player in the helmet then all the game sound is evenly decreases, in percentage terms and even music.  Why does music have to do with it !?  If the player is wearing a helmet, then this should not affect the sound level of the music. It also seems to me, that this should not affect the sound level of the player's breathing, as the player hears his breathing from the inside. When I wear my helmet and I am running, I can't hear my breathing the game and it's not realistic. Even if the player is to plug your ears with ear plugs, it must still hear self own breathing!

In General muting of the player, too exaggerated. When I'm wearing a tank or pilot helmet, I can not practically hear the radio (I do not use ace_noradio.pbo).  So I can't hear what ally AI says!  The tank driver very weakly hears his tank engine or other sounds, etc.

 In the general The use of helmets should not only reduce the sound level, but it should also blur it.  Helmets must Do sound others, not only muted,  but when I wear my ACE3-helmet I just feel that someone invisible has reduced the sound level in my PC settings and it is all. Thus, that doesn't sound good. 

Dear ACE team, if you can not blur the sound, then please give more sound (when the player is wearing a tank, pilot helmet or headphones)  Also do not drown out background music, because music should not have attitude to helmets in the game

**Steps to reproduce:**
- play with the helmet (tankman or pilot) or headphones

**Where did the issue occur?**
-Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- none

**RPT log file:**
- not needed

**Comment by Pergor** [comment]
And while we're on the subject: The volume reduction by wearing a configured helmet is not modified by ace_hearing_earplugsVolume.
If you're setting ace_hearing_earplugsVolume to 1 the helmets should not lower the volume at all - just like earplugs.

**Comment by ZeusWrath** [comment]
> If you're setting ace_hearing_earplugsVolume to 1 the helmets should not lower the volume at all - just like earplugs.

Please explain where exact and how I can use this? There is no way to increase/decrease the multiplier for muting?

**Comment by Pergor** [comment]
There is, but not for helmets, only for earplugs.
https://ace3mod.com/wiki/framework/settings-framework.html

**Comment by ZeusWrath** [comment]
> There is, but not for helmets, only for earplugs.

Sorry. 

Worst of all it affects the radio chatter, the sound suppressed by 80-90%! 
In fact this is nonsense, because in a tank-helmet needs to be headphones and a radio headset. This should not reduce radio even 1 %!!!

**Comment by commy2** [comment]
Sounds like feature request to me. Most of what you're proposing is not feasible due to a lack of API from Bohemia. Close?

**Comment by ZeusWrath** [comment]
Hi @commy2!  Please tell me, what exact is not feasible ? 

Is there no possibility to adjust the sound separately for radio, separately for background music and, separately, for the effects!?  I can't believe it, because when I hear the sound of the radio (in the tank helmet), I understand that radio sound is not reduced in proportion to the other sounds,  this reduced much more than other sounds. This,  means that  you minimum, can affect the sound of the radio separately.

You need to consider this question yourself or with ACE team, but my humble opinion is:

1. The sound of the radio talks, should not be affected (because the helmet have a radio headset and earphone)
2. Game music should not be affected
3. Own Breathing of the player, should be almost not affected. (reduced not more multiplier - 0.85, 0.9)
4. Drowning out all other other sounds are reduced. (reduced not more multiplier - 0.7, 0.75)

**Comment by jonpas** [comment]
No, there is no possibility as you said. BI can do it because they can do it in-engine, we can't, end of story.

**Comment by Pergor** [comment]
As an idea, to offer the opportunity to adjust the volume reduction done by helmets, wouldn't it be possible to configure the helmets as if they were earplugs instead of them having non-configurable values on their own?

If a player wears ace_earplugs, his hearing is reduced depending on ace_hearing_earplugsVolume. So if the player wears a helmet with hearing reduction ace jumps in and puts 'virtual' ace_earplugs in his ears instead of lowering his game volume no matter what.

That way people being bothered with the volume reduction done by helmets can set ace_hearing_earplugsVolume to 1 and play as if nothing ever happened while still being able to have combat deafness and the other features.

**Comment by ZeusWrath** [comment]
> No, there is no possibility as you said. 

As there is no way!? You say no way, but the possibility is always there!

ACE reduced the total sound of the game (when the player is wearing a helmet) **using some multiplier** and ACE reduced the sound of radio talks (when the player is wearing a helmet) **using an even bigger multiplier**!  I say _even bigger multiplier_, because it seems to me that sound of radio talks much quieter just other sound.  Hence the conclusion that the ACE can adjust the multiplier the loss of sound for radio is separately. It's simple logic, or am I mistaken?

At least this seems to me, that radio talks, they are much more quieter than the other sounds. The problem is that radio communications do not interest the makers of ACE, because the mod uses the file - ace_noradio.pbo. It is not clear to me why this is necessary. Dear team ACE, temporarily disable file ace_noradio.pbo and adjust the volume of radio, for those who do not use ace_noradio.pbo (namely for singleplayer players)

Even if it is my delusion and radio conversations were not reduced more than the other sounds (it means that can not be set separately), then the ACE, still can reduce the all mute multiplier, mute, and increase the overall sound generally.

There is always a some solution

**Comment by commy2** [comment]
>You say no way, but the possibility is always there!

That is a lot of optimism for someone that doesn't understand how any of this works. Sorry, but this cannot be taken seriously.

**Comment by jonpas** [comment]
Yes you are indeed mistaken, you can change the volume by settings the following:
```
class GVAR(earplugsVolume) {
        value = 0.5;
};
```
And we won't change a multiplier that works for most, we can't satisfy everyone, that's why there are settings.

I like that idea @Pergor!

**Comment by ZeusWrath** [comment]
> That is a lot of optimism for someone that clearly doesn't understand how any of this works. Sorry, but this cannot be taken seriously.

Ok, I can't argue with the masters/

> class GVAR(earplugsVolume) {
>         value = 0.5;
> };


@jonpas as far as I understand, you suggest me to work on ear plugs! But what do I do with the radio!? It's impossible to hear normally when there is a fight! What I can do with helmets and musics?

**Comment by ZeusWrath** [comment]
Radio talks in the ACE are not reduced more than other sounds!?

**Comment by commy2** [comment]
No, they aren't.

**Comment by ZeusWrath** [comment]
> No, they aren't.

so I was wrong.

And what will be the output?
What about idea  of @Pergor? You try to implement it or not?

**Comment by ZeusWrath** [comment]
Hey Hey Hey!

I waited two days, them I will ask again:

> And what will be the output?
> What about idea of @Pergor? You try to implement it or not?

**Comment by jonpas** [comment]
Hey Hey Hey!

I waited for two days, then I will tell you again to kindly stop telling us what to do. A developer will get around to it if they'll to and have time to. In other case, you are free to create a pull request.

**Comment by ZeusWrath** [comment]
My friend I am not telling you what to do. I just want to know what I need to know, because it's my ticket/

**Comment by commy2** [comment]
I think this is a feature request and should be linked to the feature request issue and this one should be closed.

**Comment by ZeusWrath** [comment]
well if you are so hard to answer me on my question

> You try to implement it or not?

 and write two letters "yes" or "no", then nothing more remains to close this ticket

**Comment by jonpas** [comment]
I already told you, we don't know, if someone will pick it up (core dev or contributor) then yes, else no. Not much else we can say for anything unless the one saying has plans, which is clearly not the case here.
