### ISSUE TITLE
ACE 3 not interactable

### ISSUE THREAD

**Issue by TheatralicARTs** [acemod/ACE3#5061]
**Arma 3 Version:** `1.68` (Stable Branch)
**CBA Version:** `3.2.1` (Stable Branch)
**ACE3 Version:** `3.9.1` (Stable Branch)

**Mods:**
```
- CBA_A3
- ace
- MCC Sandbox
- RHS USAF
- RHS AFRG
- RHS SAF
- RHS AFRF
- RHS GREF
- Task Force Arrowhead radio (also not working)
- BWA 3
```

**Description:**
- ACE 3 is installed and the modules and items do show up in the game but none of the interactions work. Ear ringing along with ballistics and the medical Module all dont respond at all.

**Steps to reproduce:**
- Load Map
- Try Ear ringing by firing any firearm
- Try interacting with self/NPC

**Where did the issue occur?**
- Self-hosted MP / Singleplayer / Editor singleplayer
**Placed Modules:**
- All ACE 3 modules

**RPT log file:**
- https://pastebin.com/VbuHQ81N
- ACE 3 seems to be unable to output a debug.

**Comment by TheMagnetar** [comment]
Well, you have a lot of errors due to conflicting addons: you are launching the game with a lot of them, not only the ones that are listed: 

> mod=C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@JSRS4APEX;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CBA_A3;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@NIArms Core;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@st_gi;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@st_interact;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@st_map_autobrightness;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@st_nametags;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@st_stamina_bar;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@sthud;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@FFAA MOD;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@Jurassic Arma - Raptor Pack;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@task_force_radio;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@Are

One of those is causing the conflict like  in `Conflicting addon A3_Sounds_F in 'mm_buildings\prison\sounds\', previous definition in 'mm_bank\sound\'` or the errors shown later like

> 17:55:35 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.fireLightDiffuse'.
> 17:55:35 Warning Message: Size: '/' not an array
> 17:55:35 Warning Message: Size: '/' not an array

**Comment by TheatralicARTs** [comment]
Turns out ARMA was launching mods that weren't active. It's working fine now. Thanks for telling me.
