### ISSUE TITLE
Cannot Binarize own fork of ACE3

### ISSUE THREAD

**Issue by Hemius** [acemod/ACE3#5064]
Actually trying to make own fork of ACE3 based on ACE3-master but have problem with binarizing modules.
Some of them are ok and gone through this process but more than half fails to build...
-------
Example error code of one module:
Making zeus--------------------------------------------------------
Missing PBO file ace_zeus.pbo. Building...
Building: P:\z\ace\addons\zeus
Destination: P:\z\ace\release\@ace\addons
ERROR: pboProject return code == 1
ERROR: Module not successfully built/signed. Check your P:\temp\zeus_packing.log for more info.
Resuming build...
-------
Everything is set up, test builds are just fine and no errors on start and in-game... kinda stuck with this thing, was trying to fix it all day long.
Changed only settings of repair and medical modules.

**Comment by jonpas** [comment]
Well, did you `Check your P:\temp\zeus_packing.log for more info.` as it tells you to?

And you don't have to build your own ACE3 to change settings using the [Settings System](https://ace3mod.com/wiki/framework/settings-framework.html).

**Comment by PabstMirror** [comment]
Checking `P:\temp\zeus_packing.log` is a good first step.
Error is usually near the bottom of that file.
Upload it here if still having problems.

Also take a look at https://ace3mod.com/wiki/development/setting-up-the-development-environment.html

**Comment by Hemius** [comment]
The end of zeus_packing.log
#uninclude
Warning: rapWarning: **********missing file(s)***************
Warning: z\ace\addons\zeus\ui\RscAttributes.hpp Line 283: \a3\Ui_f\data\Map\Markers\NATO\b_unknown.paa
Warning: z\ace\addons\zeus\ui\RscAttributes.hpp Line 292: \a3\Ui_f\data\Map\Markers\NATO\o_unknown.paa
Warning: z\ace\addons\zeus\ui\RscAttributes.hpp Line 301: \a3\Ui_f\data\Map\Markers\NATO\n_unknown.paa
Warning: z\ace\addons\zeus\ui\RscAttributes.hpp Line 310: \a3\Ui_f\data\Map\Markers\NATO\n_unknown.paa
rapWarning: **********missing file(s)***************

fnc_addObjectToCurator.sqf 
fnc_bi_moduleCurator.sqf 
fnc_bi_moduleMine.sqf 
fnc_bi_moduleProjectile.sqf 
fnc_bi_moduleRemoteControl.sqf 
fnc_handleZeusUnitAssigned.sqf 
fnc_moduleAddOrRemoveFRIES.sqf 
fnc_moduleAddSpareTrack.sqf 
fnc_moduleAddSpareWheel.sqf 
fnc_moduleCaptive.sqf 
fnc_moduleGlobalSetSkill.sqf 
fnc_moduleGroupSide.sqf 
fnc_moduleSearchNearby.sqf 
fnc_moduleSetMedic.sqf 
fnc_moduleSetMedicalFacility.sqf 
fnc_moduleSetMedicalVehicle.sqf 
fnc_moduleSimulation.sqf 
fnc_moduleSurrender.sqf 
fnc_moduleTeleportPlayers.sqf 
fnc_moduleUnconscious.sqf 
fnc_moduleZeusSettings.sqf 
fnc_showMessage.sqf 
fnc_ui_attributeCargo.sqf 
fnc_ui_attributePosition.sqf 
fnc_ui_attributeRadius.sqf 
fnc_ui_defendArea.sqf 
fnc_ui_editableObjects.sqf 
fnc_ui_globalSetSkill.sqf 
fnc_ui_groupSide.sqf 
fnc_ui_patrolArea.sqf 
fnc_ui_searchArea.sqf 
fnc_ui_teleportPlayers.sqf 
fnc_zeusAttributes.sqf 
script_component.hpp 
README.md 
script_component.hpp 
stringtable.xml 
texHeaders.bin 
Icon_Module_Zeus_Captive_ca.paa 
Icon_Module_Zeus_Medic_ca.paa 
Icon_Module_Zeus_Settings_ca.paa 
Icon_Module_Zeus_Surrender_ca.paa 
Icon_Module_Zeus_Unconscious_ca.paa 
RscAttributes.hpp 
XEH_postInit.sqf 
XEH_preInit.sqf 
XEH_PREP.hpp 
XEH_preStart.sqf 
<scanning requiredaddons for config.bin>
no config found in pbo!!!

Kind frustrated with this...as no errors in-game and on start with test buils.. no changes in this files. took ACE from main dev branch

**Comment by PabstMirror** [comment]
`Warning: z\ace\addons\zeus\ui\RscAttributes.hpp Line 283: 
\a3\Ui_f\data\Map\Markers\NATO\b_unknown.paa`

Check your p-drive is setup correctly
Goto `P:\a3\ui_f\data\Map\Markers\NATO` and check that `b_unknown.paa` exists

**Comment by Hemius** [comment]
Thanks, the point was that there were some missing files from Arma 3 data) hope it will go fine now

**Comment by br1zey** [comment]
Hello i Have the Same Problem with Build ACE.
One addon make Problems 
the fastroping addon can't Pack

Error
```
Bis Binarise...
 Checking for binarised rtm...

Bis binarise failed to binarise some or all rtm files.
There was no skeleton that could be used.
Read the documentation

```
