### ISSUE TITLE
Ace self interact menu and interact menu wont show up

### ISSUE THREAD

**Issue by naton305** [acemod/ACE3#5071]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- when i am in game i try to open both of the menus but all that shows up is my cursor. I have tried re mapping the key binds and re installing the mod for arma 3 from the main website and steam both had the same issue .

**Steps to reproduce:**
- go into multiplayer or single wont work in either of them and trying to open either menu wont work.

**Where did the issue occur?**
- will not work in multiplayer or single player editor.

**Placed Modules:**
- none

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by commy2** [comment]
Needs RPT file

**Comment by Glowbal** [comment]
Missing rpt
