### ISSUE TITLE
ACE Medical Custom Vehicle dont work

### ISSUE THREAD

**Issue by coresync2k** [acemod/ACE3#5076]
**Arma 3 Version:** `1.68` (stable / rc / dev)
**CBA Version:** `3.2.1` (stable / dev + commit hash)
**ACE3 Version:** `3.9.1` (stable / dev + commit hash)

**Mods:**
Car Packs ( Jonzie )
- CBA_A3
- ace
```

**Description:**
- If i setup a ACE_moduleAssignMedicVehicle to a "Standart Arma3 Vehicle or Apex" it works, but if i 
add Jonzie_Ambulance it dont work. I set it on the map as map object and it dont work, with the normal arma 3 vehicle it works.

**Steps to reproduce:**
- Set the Module ACE_moduleAssignMedicVehicle and add as Medicalvehicle a Standart Arma 3 Vehicle
- Try to operate a Person -> WORKS
- Set the Module ACE_moduleAssignMedicVehicle and add a "custom" vehicle Like Jonzie_Ambulance
- Try to operate a Person -> Not Working

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer 

**Placed Modules:**
- All Modules

**Comment by Glowbal** [comment]
How do you set up the module? There are multiple ways.

**Comment by coresync2k** [comment]
i set it on the map in EDEN Editor.
Whats the other ways? :)

**Comment by Glowbal** [comment]
Do you use the synchronization tool or give the vehicle a name and use that name in the module?

**Comment by coresync2k** [comment]
the vehicle got a name, i used the classname. with arma 3 vehicle this work.

**Comment by commy2** [comment]
"med_vehicle" is not a classname. "B_Soldier_F" is a classname.

**Comment by Glowbal** [comment]
You don't fill in the classname, but the name you give the vehicle in the description.

**Comment by Glowbal** [comment]
Otherwise;

```sqf
this setVariable ["ACE_Medical_medicClass", 1];
```

**Comment by coresync2k** [comment]
@commy2 i mean if i use a "custom classname" it wouldnt work, that i mean "med_vehicle" is a custom classname if i write it down in the modfile :)

@glowbal the variable must be set when the vehicle spawn? or on a other point?

**Comment by commy2** [comment]
That is not what a classname is.

**Comment by coresync2k** [comment]
A Classname is a Name in a Vehicle / Map whatever pbo

and if i write "medic_vehicle" and use createvehicle "medic_vehicle" and its spawning, it is a classname?!

**Comment by commy2** [comment]
>and if i write "medic_vehicle" and use createvehicle "medic_vehicle" and its spawning, it is a classname?!

No, that is not a classname. It's a variable name.

**Comment by coresync2k** [comment]
mhm ok

**Comment by Glowbal** [comment]
Use this in the init box of the vehicle:

```sqf
this setVariable ["ACE_Medical_medicClass", 1];
```
