### ISSUE TITLE
Current CBA 3 v3.2.1 is broken and any current versions of ACE can not be used.

### ISSUE THREAD

**Issue by Xenotork** [acemod/ACE3#5078]
Just wanted to say that the current version of CBA 3 is broken, and will need to be fixed before any current versions of ACE can be used.

Don't know if its different for others but, i am not able to use anything from ACE, no UI or mechanics, with the new CBA version.

**Comment by jonpas** [comment]
Would you mind filling out the issue template that was handily prepared for you when you clicked "New issue"? We can't help you at all without all the information that is written to be added there.

**Comment by commy2** [comment]
CBA A3 v3.2.1 is not broken and ACE can be used just fine.

**Comment by Xenotork** [comment]
okay then. sorry for not using the template, ill copy it over on this. had to go somewhere during the first write so i just posted a quick desc.

Arma version : 1.68
CBA: 3.2.1
Ace: 3.9.1

Mods:
RHSUSAF
RHSAFRF
RHSSAF
RHSGREF
Enhanced Movement
CUP terrains - Core & Maps
Chernobyl zone & Winter theme
Advanced Rappeling & Sling Loading
Personal Arsenal
Ares Mod - Achilles
Project Opfor
Ace Compat - USAF, AFRF, & GREF
ZeroReal-NoSway_NoFatigueTest
Task_force_Radio
NATO_Rus_Weapons
USMC_mas
CBA 3
Ace

Desc.:
After loading all of the mods up and enter a single or multiplayer instance, I am unable to load the list of accessories for my weapons in the Arsenal and any that were on the selected weapon beforehand disappear. When i try to use Task Force Radio and Ace keybinds, none of them work for me, and i am unable to use their UI. However i am still affected by server settings using the Ace Modules. Damage and some mechanics still work to an extent, but not completely.

Reproduction:
I have no idea how to reproduce the steps needed to accomplish this issue.

Occurances:
Single/Multiplayer

Modules:
No modules are causing this issue.

Report files:
[ArmaReport_Log_20170410T225233_Bailey.zip](https://github.com/acemod/ACE3/files/914997/ArmaReport_Log_20170410T225233_Bailey.zip)

Sorry about the rushed Issue report i made. was almost late for a lunch meeting.

**Comment by commy2** [comment]
>ArmaReport_Log_20170410T225233_Bailey.zip
What is this? We cannot work with this. We need the RPT file. Please read where to find this. It's described in the issue template. It also says there that bugs should be reproduced with only CBA and ACE enabled. We cannot support and debug addon packs of multiple giga byte with code unknown to us. Sorry.

**Comment by Xenotork** [comment]
Got it. sorry for the confusion.

Here ya go:
[Report.txt](https://github.com/acemod/ACE3/files/915044/Report.txt)

(with just Ace and CBA 3)

**Comment by bux** [comment]
> It's described in the issue template. It also says there, that bugs should be reproduced with only CBA and ACE enabled. 

@Xenotork now please **only enable CBA and ACE** and see if the issue still exists.
If not then there's a problem with one of the other mods and you'd need to **enable them one by one** to see which one interferes with CBA and ACE.

**Comment by commy2** [comment]
Looks like the mission is broked too. Riddled with script errors. No surprise it's not working.
```
21:27:49 Error in expression <,
["put",     23]
];


private _ctrlList = _display displayctrl (          960 +       26);
{
>
21:27:49   Error position: <_display displayctrl (          960 +       26);
{
>
21:27:49   Error Nicht definierte Variable in Ausdruck: _display
21:27:49 File A3\functions_f_bootcamp\Inventory\fn_arsenal.sqf [BIS_fnc_arsenal], line 2122
```

```
21:34:18 Error in expression <icles" >> typeOf _vehicle >> "Turrets") select (_turret select 0);


if((getNumb>
21:34:18   Error position: <select (_turret select 0);


if((getNumb>
21:34:18   Error Allgemeiner Fehler in Ausdruck
21:34:18 File \rhsusf\addons\rhsusf_c_m113\scripts\rhs_turretAction.sqf [RHSUSF_fnc_turretAction], line 13
```

**Comment by Xenotork** [comment]
Yea, the issue still occurs with just CBA on the mod list. However i am not able to get a report off of that error for some reason, i only get a Access violation from using a 64 bit game, i checked the report off that error message to make sure, and i was unable to find the same diag readings relating to the issue. 

I have reason to believe that my game itself is not reading the mod and server correctly, even in the 32 bit version. I may have to reinstall the game entirely.

**Comment by Xenotork** [comment]
Yep, my suspicion was correct. Fixed the issue with a Reinstall of Arma 3. i guess the client didn't fully get updated along with the game.

you guys take care, and thanks for sorting things out.
