### ISSUE TITLE
Firemode Selection - Safety Switch Option 

### ISSUE THREAD

**Issue by PiZZAD0X** [acemod/ACE3#508]
Recommend implementation of ACE 2 style hijacking of firemode selection/ next weapon key for an overriding function of selecting firemode, safety, and muzzle separately.

Example with a 3 stage selector: Starting on semi automatic, pressing F would switch to fully automatic, a further press of F would engage the safety, and another press would take off the safety and return to semi automatic.

**Comment by esteldunedain** [comment]
Please follow the proper rules for feature requests as stated here https://github.com/acemod/ACE3/issues/414 and on the wiki.
