### ISSUE TITLE
Medical Level: Vanilla Feature

### ISSUE THREAD

**Issue by zafjr** [acemod/ACE3#5080]
**Arma 3 Version:** `1.68` stable
**CBA Version:** `3.2.1` stable 
**ACE3 Version:** `3.9.1` stable 

**Mods:**
- CBA_A3
- ace

For servers that jump between various mission types, i wish there was a "Medical Level: Vanilla/disabled" option to completely disable the ACE medical system without having to remove the pbo.

I love the ACE medical system, and 99 percent of the time, it is used. But sometimes we switch to missions that dont really call for it's use, especially to refresh/relax away from tedious realistic scenarios for just a short moment, but we still want to retain the rest of ACE's wonderful features. For example sometimes we play ENDGAME after a nice long coop mission, to relax. It's great with just vanilla revive. I have to restart the server and remove ACE from the commandline and ask all of my players (30+) to restart arma and do the same. Just for that one short PvP session. And then after that, go back and enable ACE again, and ask the same of my players again. Or sometimes maybe we want to play one of the various scenarios out there that are broken if ACE medical is used. Having a ACE MEDICAL:Disabled parameter would be a life-saver. This is in no way a slant on the medical system, it is fantastic and i love it very much.

**Comment by BaerMitUmlaut** [comment]
With the current system, this is not possible. Maybe after the rewrite. Also, this is a feature request and thus belongs into #3594.

**Comment by zafjr** [comment]
Oh my, sorry sorry didnt know.
