### ISSUE TITLE
Assign/Remove medic class

### ISSUE THREAD

**Issue by byjokese** [acemod/ACE3#5086]
Any way to assign and remove medic class to a player by command?

**Comment by AACO** [comment]
For ACE medical you should be able to set a unit as a medic using
`player setVariable ["ace_medical_medicClass", 1, true];`

and removing a unit as a medic using
`player setVariable ["ace_medical_medicClass", 0, true];`

**Comment by byjokese** [comment]
Good, I believe engineer has a class to right? Do you know which is it? Thanks BTW.

**Comment by PabstMirror** [comment]
`ace_isEngineer`

**Comment by 654wak654** [comment]
Should mention that the variable is called `ìsEngineer`, but the value isn't a boolean true/false. Same with medic, it goes like 0: not an engineer - 1: engineer - 2: repair specialist.

**Comment by byjokese** [comment]
Ok perfect thank you.
