### ISSUE TITLE
Can't change the option for ammunition handling for mortars

### ISSUE THREAD

**Issue by kripto202** [acemod/ACE3#5087]
**Arma 3 Version: stable
**CBA Version: 3.2.1.170227
**ACE3 Version: 3.9.1.17

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Can't change the option for ammunition handling. The drop down menu doesn't work.

**Steps to reproduce:**
- go into the editor, place down the mortar module and try to change the setting.

**Comment by commy2** [comment]
Editor bug. You have to change your ui size or wait for a fix from BI.
