### ISSUE TITLE
MicroDAGR GPS doesn't show buildings on the map

### ISSUE THREAD

**Issue by kripto202** [acemod/ACE3#5089]
**Arma 3 Version: stable
**CBA Version: 3.2.1.170227
**ACE3 Version: 3.9.1.17

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The MicroDAGR GPS doesn't show any buildings on the map even if you set the module to show buildings.

**Steps to reproduce:**
- add the module for MicroDAGR and change the setting to show buildings. Even if you don't have the module placed, the map doesn't change.

**Where did the issue occur?**
- everywhere

**Comment by cineafx** [comment]
You have to switch to satellite view to be able to view buildings 
https://ace3mod.com/wiki/feature/microdagr.html#25-switching-between-topographical-and-satellite-view
