### ISSUE TITLE
Mathematical error in fnc_calculateAirDensity

### ISSUE THREAD

**Issue by ChMaverickCh** [acemod/ACE3#5092]
**Arma 3 Version:** `1.68.141205` stable
**CBA Version:** `3.2.1.170227`
**ACE3 Version:** `3.9.1`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Mathematical calculation error in ACE3/addons/weather/functions/fnc_calculateAirDensity.sqf: the Saturation vapor pressure _pSat calculated in line 26 is in Millibar insted of Pascal(can also be seen in stated source for theory in comment on line 25). Since 1mbar = 1hPa = 100Pa, the pressure is of by a factor of 100. following in very inacurate air densities which in turn has a impact on things like mortar ballistic curves.

**Steps to reproduce:**
- Read the code (ACE3/addons/weather/functions/fnc_calculateAirDensity.sqf) on line 26;
**Where did the issue occur?**
- Git Repo

**Comment by PabstMirror** [comment]
These units are very confusing, good find.
Should have this fixed in 3.10

Ref https://github.com/acemod/ACE3/issues/4951
Fix PR: https://github.com/acemod/ACE3/pull/4956
