### ISSUE TITLE
G Forces apply to uav units

### ISSUE THREAD

**Issue by Zakant** [acemod/ACE3#5093]
**Arma 3 Version:** `stable` , tested on `dev`
**CBA Version:** `latest stable`
**ACE3 Version:** `latest sable`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
G Forces apply to uav controlled units as well. This means the uav ai could have a black or red out.

**Steps to reproduce:**
- Place a uav plane (new uvac is the best, as it have the highest top speed)
- Remote contoll the uav either from zeus or per UAV Terminal
- Fly a tight corner at high speed
- Get a black out

**Where did the issue occur?**
- Everywhere 

**RPT log file:**
Not relevant for this.

**Comment by commy2** [comment]
They are poor quality Chinese knock-offs.

**Comment by SilentSpike** [comment]
:rofl: Should be an easy fix

**Comment by Zakant** [comment]
Question who is faster... I already tried a few things... So I could probably provide a fix tomorrow. Unless you want to fix it ;)

**Comment by PabstMirror** [comment]
PR to fix: #5094
