### ISSUE TITLE
Add ability to disable remote detonation for explosives

### ISSUE THREAD

**Issue by Pergor** [acemod/ACE3#5101]
Hi guys!

I'm currently working on a jammer script that should add the ability to jam remote detonation of explosives/IEDs in a certain radius around a jammer vehicle. Unfortunately either I can't find a function to disable remote detonation (without actually defusing or detonating the explosive) or there actually isn't any.

That might be a feature to add, so jammers can be made.

**Comment by kripto202** [comment]
instead of disabling, you could greatly decrease the range.

**Comment by AACO** [comment]
The RHS DUKE system uses a work around where they disable the simulation of the explosive when the device is within range of the jamming system. However this comes with it's own set of issues, namely timers/pressure plates fail to work properly.

**Comment by Pergor** [comment]
If that'll disable the setDamage command on the explosive that's being triggered by the detonator, it should be a suitable workaround.
I'm looking into finding out how I can return the selected trigger type for a certain explosive.

**Comment by Pergor** [comment]
enableSimulation does not seem to disable setDamage on mines... So it's back to the drawing board. :(

**Comment by Pergor** [comment]
For everyone interested, finding out the kind of trigger used on a mine was actually pretty easy:

`{
	private _mine = _x;
	private _trigger = getText (configFile >> "cfgammo" >> typeOf _mine >> "mineTrigger";
	if ( toUpper _trigger isEqualTo "REMOTETRIGGER" ) then {
		//that's a mine with a remote trigger
	};
} count allMines;`

**Comment by PabstMirror** [comment]
Check out PR https://github.com/acemod/ACE3/pull/5115

That will be able to give the specific ace trigger.
A charge wired with a M57 clacker will have the same `typeOf` as one with a wireless M152.
