### ISSUE TITLE
RHS Littlebirds heckrotor don't hurt player

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#5103]
**Arma 3 Version:** `1.6.8` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- rhsafrf+compat.pbo
```

**Description:**
-player doesn't get hurt by the heckrotor, when playing with ace3 and the rhs-compatibillity addon.

**Steps to reproduce:**
-place melb-littlebird. start mission. start the engine. get out and run into the heckrotor.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**Comment by bux** [comment]
Not our issue

**Comment by commy2** [comment]
Not an ACE, but vanilla feature.

**Comment by madpat3** [comment]
just for better understanding. with "rhs-compatibillity addon", i meant **your** compatibillity .pbo inside the "optional" folder. 
as for commy's comment, i "read", that it is BI's fault?!
