### ISSUE TITLE
plane AI lands in front of the runway end crashes

### ISSUE THREAD

**Issue by xmastersrule** [acemod/ACE3#5104]
**Arma 3 Version:** `i dont know wat the version was but tha date  24/04/2017` 
**CBA Version:** `i dont know wat the version was but tha date  24/04/2017` 
**ACE3 Version:** `i dont know wat the version was but tha date  24/04/2017` 
**mods used:**
- CBA_A3
- ace
```

**Description:**
-it does not give an error. the AI it lands infront of the runway end i dont kow why. it looks like it goes to slow to land end then it stalls. i tested it with only CBA if the problem was in thare but it was a smooth landing 

**Steps to reproduce:**
-maybe increase the speed of the AI wile landing 

**Where did the issue occur?**
-wile an AI tries to land a plane on a runway 

**Placed Modules:**
- none only a plane with a land waypoint end 1 unit to look if he lands right (he does not)

**RPT log file:**
-none

**Comment by 654wak654** [comment]
> i dont know wat the version was but tha date 24/04/2017
This doesn't help.

Though I agree with the issue, my unit has also observed the same problem. Most likely caused by `ace_aircraft`.

**Comment by xmastersrule** [comment]
well im using the latest versions if im right end im only using workshop from steam so it should be the latest version. but do you know eny thing about why the AI do this end do other poeple have the same problem or is it just me??
