### ISSUE TITLE
linking belts just refills ammo, not add ammo

### ISSUE THREAD

**Issue by kripto202** [acemod/ACE3#5108]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
When linking ammo to your mg, it doesn't increase the number of rounds I.E. 200 -> 400 but instead, it just refills the box and uses a whole box. For example, shoot a round, have a buddy link the belts, buddy's box is removed, your box is full as a new box I.E. 199 -> 200 and buddy's box is gone.

**Comment by commy2** [comment]
Not 400 is expected as magazine size is limited by the engine.

**Comment by kripto202** [comment]
I thought it was limited by the magazine config.

**Comment by commy2** [comment]
Yes and that is set to 200.

**Comment by kripto202** [comment]
Is it possible to add extra magazine configs to make linking belts possible? Once you link a belt, it will replace the magazine to the 400 round magazine?

**Comment by commy2** [comment]
No, that would be a huge mess and almost impossible to maintain, especially with 3rd party addons and the arsenal which cannot hide magazines (scope=1 doesn't work for CfgMagazines).

**Comment by KiritoKun223** [comment]
As far as I know there is a possibility to add more ammo that actually fits into the magazine. If I remember right @dedmen once told me about it.

**Comment by dedmen** [comment]
AFAIK [setAmmo](https://community.bistudio.com/wiki/setAmmo) can set the current loaded magazine over 100% fill.

**Comment by jonpas** [comment]
> setUnitLoadout probably can do it

Yes it can, I have tried that by mistake and had a magazine with 5000 bullets. 😆 
The bad part is it's not really usable by us, it replaces all the inventory.

**Comment by dedmen** [comment]
Well. getUnitLoadout -> modify current magazine size -> setUnitLoadout. Will just set the same loadout again so shouldn't change anything. But it's quite time intensive.

**Comment by jonpas** [comment]
It's performance intensive, breaks overheating, thermals, magazine IDs... etc.

**Comment by kripto202** [comment]
How about instead of adding more rounds than the magazine cap, how about removing the necessary amount of ammo to refill the box instead of removing the full box.

**Comment by PabstMirror** [comment]
Right now ammo that can't be added gets returned.
A has 55/100 in his gun.
B links a full mag
A now has a 100/100 magazine loaded
B now has a 55/100 mag in inventory

I think this is the best we can do with the engine limitations

**Comment by kripto202** [comment]
wouldn't it be 45 rounds for mag B?

**Comment by PabstMirror** [comment]
B put 45 rounds into A's loaded mag and gets 55 back
Sum is 155 before and after

**Comment by Phyma** [comment]
Isnt the best thing that A ammo + B ammo <= fullmagcount?

**Comment by 654wak654** [comment]
> Isnt the best thing that A ammo + B ammo <= fullmagcount?
Did you event read above?

**Comment by Phyma** [comment]
If you mean this:

> Right now ammo that can't be added gets returned.
> A has 55/100 in his gun.
> B links a full mag
> A now has a 100/100 magazine loaded
> B now has a 55/100 mag in inventory

Then it is not the same and if you dont mean that then sorry must have missed it please point it out.

**Comment by Phyma** [comment]
I could also clarify:
A has 25/100. B has 25/100.
You do this and now you have C that has 50/100

If A has 25/100 and B has 80/100 then the result is nothing because you cant do it.

**Comment by Phyma** [comment]
Isnt is better to disable this functionality because magrepack still works on belts or?

**Comment by kripto202** [comment]
No it wouldn't, instead of having your machinegunner go through the long reloading animation, you can have your buddy that is carrying extra ammo for you and link the belt to your gun so you can keep laying fire without stopping.

**Comment by Phyma** [comment]
Okey, fine will try and fix then so this: 
Mag A (isingun) has 25/100. Mag B has 25/100.
You do this and now you have Mag A has 50/100 and B is destroyed.

If A (is in gun) has 25/100 and B has 100/100 then the result is A has 100/100 and B have 25/100.

But don't know if this is possible.

**Comment by PabstMirror** [comment]
I think it works exactly as you would want it to.
We use the `setAmmo` command to change the ammo in the gun (Magazine A)
As kripto said, with this system a machine gunner could fire thousands of rounds without reloading, assuming he has an assistant to link belts.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
