### ISSUE TITLE
Feature Request: Eden editor module to modify fuel consumption rate

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#5110]
Would it be possible to add an eden editor module that allows modifying the fuel consumption rate of vehicles globally or better yet by vehicle class? Especially in the case of aircraft, it could be a great way of balancing out their firepower in milsim ops by restricting their time on station cause at the moment the only reason to refuel is if the fuel tank was damaged.

**Comment by commy2** [comment]
Feature requests go here #3594
