### ISSUE TITLE
Fuel nozzle drops at terrain level / in sea

### ISSUE THREAD

**Issue by specop0** [acemod/ACE3#5112]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.0` (stable)

**Mods:**
```
- CBA_A3
- ACE
- CUP
- other stuff
```

**Description:**
Fuel nozzle is dropped at terrain level. On a carrier or mission build base above terrain level the fuel nozzle cannot be found because it is at terrain level. Therefore the fuel nozzle cannot be returned and a zeus must copy/paste the fuel truck to work again.

**Steps to reproduce:**
- Place carrier / build base above terrain level
- Take fuel nozzle
- Drop fuel nozzle / move away from truck
- Fuel nozzle cannot be found, because it is at terrain level

**Where did the issue occur?**
- Dedicated 

**Placed Modules:**
- Many: https://wiki.tacticalteam.de/index.php?title=Modulvorgaben#Serverseitig_gesetzt

**RPT log file:**
- None

**Code:**
https://github.com/acemod/ACE3/blob/master/addons/refuel/functions/fnc_dropNozzle.sqf#L28
The height / z position should be relative to the carrying unit, shouldn't it?

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/blob/master/addons/refuel/functions/fnc_dropNozzle.sqf#L28

But just switching to setPos wouldn't fix the issue. Needs a some sort of setPosAGLS that finds the correct layer.
