### ISSUE TITLE
Aircraft pbo zoom issue

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#5117]
**Arma 3 Version:** `1.68` (stable / rc / dev)
**CBA Version:** `3.2.1` (dev + fd04fcd399edeeee9f7f378fbdf07d1d8779b44c)
**ACE3 Version:** `3.9.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Aircraft gun camera turns 180 on zoom.
https://youtu.be/Wy6rQRTsp10
That first turn to the left on the video is automatic.
I'm not sure if it's intended or not, but right now it feels weird when it tries to aim at some random point every time you zoom in.

**Steps to reproduce:**
- Get into the chopper as a gunner, try zoom in using +.
Repro mission.
https://www.dropbox.com/s/ced99jukqqmb5us/repro.VR.zip?dl=0

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- https://gist.github.com/rebelvg/46eb28aeeba6f1e5390536ac0d3181f9

**Comment by PabstMirror** [comment]
There are 5 zoom levels
```
ACE_WideUnstabilized
ACE_Wide
ACE_Medium
ACE_Narrow
ACE_Narrower
```
When going from unstabilized to stabilized the game will aim at the last position that was stabilized.
On first use that seems to be `[0,0,0]` or something like that.

To fix, just be moving the mouse slightly when zooming in.

We could also remove the unstabilized zoom?

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
