### ISSUE TITLE
Are we allowed to upload a custom version for use on our Exile Server on Steam?

### ISSUE THREAD

**Issue by d0narnbl1tz** [acemod/ACE3#5118]
Hello,

Are we allowed to upload a custom version for use on our Exile Server on Steam?
Because of Exile we had to strip a few components.

Greetings
Daniel

**Comment by BaerMitUmlaut** [comment]
If your version is just a subset of ACE with no changes within the PBOs and especially no license changes, you can do that. Please mark it as a custom unofficial upload from your community to avoid any confusion.
