### ISSUE TITLE
Question: Slideshow Framework

### ISSUE THREAD

**Issue by SirBassi** [acemod/ACE3#5120]
Dear Team of ACE 3,
First of all great thanks for youre amazing work which youre Development spendet to the whole Arma 3 Community including me.

I have not a "real" problem or Bug but a queastion to youre "ace_slideshow_fnc_createSlideshow" function and I really don't know if here is the right place for it but found no other possibillity to contact you.

I wanna to use the Slideshow Framwork in following Scenario:
Players spwan after a Intro Sequence on a MP Dedicated Server in a Briefing Area, 
with a simple addaction a KI / AI General is starting a Voice Briefing.
While he is speaking the Slides should change. The Time between changing the Slides is different.
I think youre Slideshow Framework is optimized for a "Player briefing Players" Scenario but is there a possibillity to handle this? I think with addaction I can start the Slideshow by Script. But do I have to work with "sleep" times between every calling or spawing of the Slideshow FNC? 

Or is this an totally nonsense idea and I should work on my idea of Briefing with an regular couple of serval setObjectTextureGlobal commands.

I started just 3 months ago to learn the basics of Scripting explicit for Arma und so I hope you may can help me to learn the next step on my own way of building knowledge and I also hope my Skills in English Language is not as bad as I think.

Thanks for youre spended time and help.

**Comment by jonpas** [comment]
https://ace3mod.com/wiki/framework/slideshow-framework.html should help you set it up with duration of each slide (no variation between them though). You can't do exactly what you want with the framework, but very close to it.

**Comment by SirBassi** [comment]
Thanks. I with this description I can handle.
