### ISSUE TITLE
IR-Devices are ineffective

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#5121]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- the intensity of the light is very weak, compared to the vanilla IR-grenade

**Steps to reproduce:**
- place a unit with two IR-chemlights, an IR-strobe and two IR-grenades. throw an IR-chemlight and one IR-grenade; watch the difference. attach an IR-chemlight, than an IR-strobe and at last an IR-grenade to your body; watch the differencies.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- not necessary

https://www.dropbox.com/s/jo6atcr67xp71wm/20170501194843_1.jpg?dl=0
https://www.dropbox.com/s/jh121fu4xv02hes/20170501195940_1.jpg?dl=0
https://www.dropbox.com/s/16801s3o6ovoopp/20170501200028_1.jpg?dl=0

**Comment by thecuban** [comment]
Agreed, strobe needs to be brighter to be effectively seen

**Comment by bux** [comment]
This needs to be fixed. The IR Chemlight and IR Strobe are useless as of right now.

![20181011221039_1](https://user-images.githubusercontent.com/1235520/46831142-e084dd80-cda2-11e8-9245-3b70d3cfb51f.jpg)
