### ISSUE TITLE
Ace Adv Medical not working on Server

### ISSUE THREAD

**Issue by Zer0Cool0** [acemod/ACE3#5122]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- CUP Terrains - Core
- CUP Terrains - Maps
- RHSAFRF
- RHSSAF
- RHSUSAF
- Spec4Gear.v4.6
- Wake Island
- NIArms Core
- NIArms AR15 Rifles
- NIArms AR15 - RHS Compat
- NIArms Ar15 - ACE3 Compat
- ACE Compat - RHSAFRF
- ACE Compat - RHSUSAF
- Specialist Military Arms (SMA) Version 2.7.1
- Aspis Gear (Retextures)
- Enhanced Movemnt
- Kunduz, Afghanistan
- Spyder Addons

```

**Description:**
- When I was testing my new server with the mission I had created. I noticed a error in the RTP.

11:57:58 Error compiling '' in 'HitPelvis'
11:57:58 Error compiling '' in 'HitAbdomen'
11:57:58 Error compiling '' in 'HitDiaphragm'
11:57:58 Error compiling '' in 'HitChest'
11:57:58 Error compiling '' in 'HitArms'
11:57:58 Error compiling '' in 'HitLegs'

So upon seeing this, I shot an AI, and of course, adv medical wasnt working. Also upon shooting the AI this appeared in my RTP

12:03:38 [ACE] (medical) WARNING: No config for wound type [velocityWoundMedium] config base [bin\config.bin/ACE_Medical_Advanced/Treatment/Bandaging/Bandage] z\ace\addons\medical\functions\fnc_handleBandageOpening.sqf:55

12:03:52 [ACE] (medical) WARNING: No config for wound type [AvulsionsMedium] config base [bin\config.bin/ACE_Medical_Advanced/Treatment/Bandaging/Bandage] z\ace\addons\medical\functions\fnc_handleBandageOpening.sqf:55

I know for a fact all of the mods I have work together, I used to run off my local machine. No issues at all.

**Steps to reproduce:**
- Start server
- Shoot ai
- Check medical menu
- No advanced medical wounds

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- ace medical 
- Ace advanced medical

**RPT log file:**
- Full RTP -https://pastebin.com/eYHfeGrg
- ACE Debug - https://pastebin.com/dZ0XAK4L

**Comment by Zer0Cool0** [comment]
Just had a bud test it with me, it is working with players, not with the ai

**Comment by 654wak654** [comment]
That is because you have medical enabled only for players (line 88 of debug info). You can change that by using an editor module, or by using the [settings framework](https://ace3mod.com/wiki/framework/settings-framework.html).

**Comment by Zer0Cool0** [comment]
Okay, I figured that :\... Thanks for the help, but what are these errors that I am receiving? Or should I not worry?

**Comment by 654wak654** [comment]
The errors are rpt spam from BIS, everyone has some form of it in their rpt files 😞. About the ACE warnings, I don't know what they effect, but if they were show stoppers they'd be errors, not warnings.

**Comment by PabstMirror** [comment]
The `Error compiling '' in 'HitPelvis'` errors occur on vanilla and can be ignored.

The warning from handleBandageOpening is from medical_ai / fnc_treatmentAdvanced_bandageLocal.
It's calling handleBandageOpening, even when `enableFor = 0`; but only on dedicated machines!

This problem should be resolved automatically with the medical re-write as `enableFor` is being redone.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 196 days without any activity.

**Comment by PabstMirror** [comment]
Should be fixed in medical rewrite
