### ISSUE TITLE
FPS drop on mass killing

### ISSUE THREAD

**Issue by narekmargaryan** [acemod/ACE3#5123]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- This happens only when ace and cba_a3 mods are enabled. In the arsenal, when I shoot at a crowd of units from little bird, thus resulting in a massive number of hits/kills my fps drops from 60 to 20 instantly without having any cpu/gpu usage volatility. CPU i5 6500, GPU R9270X, 8GB RAM 2133MHz, running the game on ssd.

**Steps to reproduce:**
- Get into little bird in virtual arsenal and shoot at the 10-15 units that are near each other.

**Where did the issue occur?**
- Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by PabstMirror** [comment]
I'll see how this is working on the rewrite
one thing to keep in mind is the VR people have weird hitpoints, and medical has to do some complex lookup to handle them

**Comment by dedmen** [comment]
Experienced the same on the weekend.
We had a crowd of 50+ civilians infront of a church, when we exploded the church all civs died and literally everyone of the dozen players went to 2fps for about 20 seconds.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
