### ISSUE TITLE
Add the ability to go slower than than walking

### ISSUE THREAD

**Issue by Sitrepo** [acemod/ACE3#5124]
Is it possible for you guys to create a feature where you could go slower than the current walking speed? Maybe like half of it. As a milsim unit on dismounted operations we usually use walking to get to our destination. In urban and the really thick jungle terrain slower speeds are much better for visibility.

**Comment by SageNTitled** [comment]
Half the speed of walking is pretty much standing still.

**Comment by Cuel** [comment]
#3594
