### ISSUE TITLE
Can't load any SP or MP save games 

### ISSUE THREAD

**Issue by Cdeeks** [acemod/ACE3#5126]
**Mods:**Arma 3 Version: 1.62 (stable)
CBA Version: Steam Workshop
ACE3 Version: Steam Workshop

**Mods:**

    @CBA_A3
    @ace

**Description:**

   Can't seem to load any Save games while Ace is active, i have tried older versions and older versions of CBA. I tried a reinstall of Arma 3 and i even tried another PC with arma 3 APEX.  

Every time the game crashes to desktop with error codes. i see there was some issues on here from over a year ago and i tried to replace the code in those issues inside the 7 sqf files and still it breaks the game.  

I have only come back to ARMA 3 after 1 year and after 4 days of trying i give up and i won't play Arma without ACE as it just doesn't work for me.      

(I have searched sevral issues the same on here but all are outdated and no solid fix)

**Steps to reproduce:**

    Launch Arma 3 with ACE, Save any SP/MP Game and try and load it back up. 
Where did the issue occur?

    Always when try to load a save game.  I TRIED WITH VINALLA GAME WORKS PERFECT. 

Placed Modules:

    None. One unit Nato Rifle man or any unit for that matter 

![11](https://cloud.githubusercontent.com/assets/28351385/25664846/c58e599e-3013-11e7-89d9-44d58e54dad8.png)
![22](https://cloud.githubusercontent.com/assets/28351385/25664848/c5a5c6e2-3013-11e7-890d-736a8405453b.png)

[RPT FILE.zip](https://github.com/acemod/ACE3/files/973611/RPT.FILE.zip)

**Comment by Cdeeks** [comment]
UPDATE****  When i revert to CBA ver 3.2.1 i can load save games but my ace interaction menu gets stuck on screen when i press L-Windows key

**Comment by Cdeeks** [comment]
UPDATE*** Tested on Virtual reality map and it lets me save and load fine with all mods on. tested on other altis, ect and game will crash when load. bug is relatyed to maps. hope this narrows it down somewhat.

**Comment by commy2** [comment]
Ref: https://forums.bistudio.com/forums/topic/168277-cba-community-base-addons-arma-3/?page=41#comment-3184240

**Comment by Cdeeks** [comment]
UPDATE*** Works on Kunduz afghan map, Starting to suspect it's only BI maps that's conflicting with CBA.  Downloading more User map mods to test it.

**Comment by commy2** [comment]
https://github.com/CBATeam/CBA_A3/issues/661

No further help required atm. :)
