### ISSUE TITLE
Placed spotting scopes are only enterable from the front

### ISSUE THREAD

**Issue by KarlMoebius** [acemod/ACE3#5128]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.3.0` (stable / dev + commit hash)
**ACE3 Version:** `3.9.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Spotting scope can only be interacted with from the visible front of the device.

**Steps to reproduce:**
- have a spotting scope in the backpack. Place scope on ground. Back of scope faces player, but player is unable to interact with it. Move around to front of device, interact menu opens, getting in the gunner slot causes the player to teleport behind the device and lay down.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- https://pastebin.com/gkwg5sH2

**Comment by AACO** [comment]
"Man, all these people are super far away"
