### ISSUE TITLE
Automatic vehicle volume toggle turn off if open map

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#5129]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The automatic volume toggle turned off if you in a vehicle open your map.

**Steps to reproduce:**
- Turn on automatic vehicle volume toggle
- fade to 1 sec
- go in vehicle (helicopter for sound)
- open Map

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- to many

**Comment by jonpas** [comment]
This is an ACEX feature, not ACE3, can you remake the issue in https://github.com/acemod/ACEX?

And please attach RPT as instructed in template.
