### ISSUE TITLE
Screen goes messy when placing explosives

### ISSUE THREAD

**Issue by KILLAKAN10** [acemod/ACE3#5130]
# **PROBLEM RECTIFIED, TURNED OUT TO BE RECOLOUR**

**Arma 3 Version:** `steam version` (stable )
**CBA Version:** `steam version` (I don't know how to get this)
**ACE3 Version:** `Steam version` (I don't know how to get this) 
Time Stamp: **6/05/17**
**Mods:**
```
- CBA_A3
- ace
-RHS
-Civilian units
-personal arsenal
-advanced rappelling
-bloodlust
-c2 command and control
-Dynasound 2
enhanced soundscape
-ace compat AFRF, USAF
-ares mod- achillies expansion
-horror sounds and music pack
007: goldfinger
-bcombat
-ReColor
-More units mod
-ACEX
-Enhanced movement
-immersion Cigs
-Advanced train simulator
-Burnes Armories, LCU and LCAC
-RHSSAF
-RHSGREF
**Description:**
- messes with the screen whenever I try to place something, kinda like when you play something made in the source engine and you go outside of the map with noclip, basically makes placing impossible.
I know its RHS due to isolating everything but ace, cba and RHS.

**Steps to reproduce:**
- have RHS and ace installed.
- attempt to place explosive (all of them that you can rotate with mouse when placing will work like this)
- become blind

Screeenshot:
https://steamuserimages-a.akamaihd.net/ugc/818937339230556658/147A93D9D0B7303624871B9C41ACF99CAF46E178/

**Where did the issue occur?**
- single and mp, self hosted

**Placed Modules:**
- none, well, not to my knowledge

**RPT log file:**
- https://pastebin.com/Cu3whmQS

**Comment by PabstMirror** [comment]
What is the name of the explosive you are placing? or does it happen on all of them?
A screnshot might help, but it sounds like the p3d is displaying wrong / too close to screen.

**Comment by KILLAKAN10** [comment]
all of them, I should have written that.

**Comment by KILLAKAN10** [comment]
> What is the name of the explosive you are placing? or does it happen on all of them?
> A screnshot might help, but it sounds like the p3d is displaying wrong / too close to screen.

all of them, I should have written that.

**Comment by KILLAKAN10** [comment]
all of them, I should have written that.

**Comment by KILLAKAN10** [comment]
cheching

**Comment by KILLAKAN10** [comment]
yea, it works for all of them, I should have iterated
if you have multiple notifs, sorry about that, trying to see how the hell
to reply :P

**Comment by KILLAKAN10** [comment]
I think this is how replies work,
yes, all explosives are affected

**Comment by PabstMirror** [comment]
I've tried with CBA, ACE, RHS and can't reproduce
Screenshot would be helpful.
Is resolution odd (like ultra widescreen or tipple monitor)?

**Comment by KILLAKAN10** [comment]
Attempting screenshot, standby

**Comment by KILLAKAN10** [comment]
https://steamuserimages-a.akamaihd.net/ugc/818937339230556658/147A93D9D0B7303624871B9C41ACF99CAF46E178/

**Comment by KILLAKAN10** [comment]
https://steamuserimages-a.akamaihd.net/ugc/818937339230556658/147A93D9D0B7303624871B9C41ACF99CAF46E178/

Not sure which method of reply works :P

**Comment by KILLAKAN10** [comment]
Scratch that, the PMA-3 and the M4a1 slam does not have this bug.

**Comment by KILLAKAN10** [comment]
Scratch that, the PMA-3 and the M4a1 slam does not have this bug.

**Comment by KILLAKAN10** [comment]
Okay, it works when I use white(warm) on black(everythign else) thermal vision
