### ISSUE TITLE
Codes of explosions on the mouse wheel.

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#5135]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The explosion of explosives is still not assigned to the wheel menu. [ARMA 2 - A.C.E. Tutorials - Explosives Part 2 "C4 / Satchel Charge / IED / M86" ](https://youtu.be/iP0HNfI6i3g?t=42s)

**Steps to reproduce:**
- Put the explosive and try to blow it up as it was in ACE2 on ArmA 2.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by commy2** [comment]
The video is for Arma 2 and ACE 2 and not Arma 3 and ACE 3.

**Comment by GalNa** [comment]
This video shows that the current ACE is worse than the previous one.

**Comment by BaerMitUmlaut** [comment]
So you have a fature request, please use the appropriate collective issue for that (#3594). If you have anything useful to contribute, let us know.
