### ISSUE TITLE
Advanced Throwing bypass FiredMan event

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#5137]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace3
```

**Description:**
- I delete all projectiles with FiredMan but Advanced Throwing allow to throw nades outside of the eventhandler.

**Steps to reproduce:**
- add addEventhandler FiredMan
- use Advanced Throwing

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- to many

**RPT log file:**
- https://gist.github.com/shukari/53d309694e0f5c98c372893f88897826

**Comment by shukari** [comment]
Any possibility to also delete this nades?

**Comment by jonpas** [comment]
Advanced Throwing throws a Fired XEH you can use. Or `"ace_firedPlayer"` CBA event you maybe able to use.

**Comment by shukari** [comment]
so? -> ["ace_firedPlayer", {systemChat str _this}] call CBA_fnc_addEventHandler;

**Comment by jonpas** [comment]
Yes, with `_projectile` (`_this select 6`) being the actual grenade object.

Mind, this event is thrown when priming the grande (starting cooking), and NOT when it is being actually released from the hand, for that you can use [`"ace_throwableThrown"`](https://github.com/acemod/ACE3/blob/98da86b74d4089bc3403d0b0c0074e6a46ce35d8/addons/advanced_throwing/functions/fnc_throw.sqf#L58) event, however that might not happen at all if the player does not actively throw the grenade (eg. dies with it in hand, explodes in hand... etc).

**Comment by shukari** [comment]
Any possibility to only get not vanilla grenade with ace_firedPlayer... so only the adv. throwing grenades?

**Comment by shukari** [comment]
Ok, issue can be closed, thx for the help. ;D

**Comment by EM-Creations** [comment]
Thank you, found this when I was looking to expand our community's "Anti ND" module to cope with grenades thrown using advanced throwing. Catching it in ace_firedPlayer seems to work.
