### ISSUE TITLE
Ability for players moving themselves beetwen vehicles

### ISSUE THREAD

**Issue by NightIntruder** [acemod/ACE3#5138]
Feature request:
What I need and ask for, is something that would help creating rescue winch as shown on the movies, here:
https://www.youtube.com/watch?v=IHxBUvQQS6I 
and here: 
https://www.youtube.com/watch?v=1jeK9w7TvmM 
In these cases there are two vehicles - the helicopter and the basket/penetrator which is a vehicle (that has a passanger proxy or proxies) attached to the rope via ropeCreate. I need ACE function that will allow players moving themselves beetwen those two vehicles when the vehicles are close to each other. Also, I need another function that will allow a crew of the helicopter to load an unconscious patient from basket to cargo seat (or any available seat) of the helicopter.

**Comment by bux** [comment]
Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: https://ace3mod.com/wiki/user/how-to-make-a-feature-request.html

**Comment by PabstMirror** [comment]
Is the basket a vehicle? 
Would the guy show up in `crew basket` or is it just using `attachTo`?

**Comment by NightIntruder** [comment]
The basket is a vehicle. The guy is on his passenger seat in the basket.
