### ISSUE TITLE
Cargo size and cargo capacity

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#5139]
**Arma 3 Version:** `1.68` (stable / rc / dev)
**CBA Version:** `3.3.1` (stable / dev + commit hash)
**ACE3 Version:** `3.9.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- RHS
```

**Description:**
-The cargo size of the vehicle ammunition boxes are to small, compared to the size of spare wheels. It should be more like 10, instead of 2. And the the cargo space of the RHS Littlebirds is too big. I don't think you can load 8 spare tires into that bird.

**Steps to reproduce:**
- Place RHS Littlebird,  sparetires and vehicle ammoboxes on map and load em into the small helicopter.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- not needed.

one box is round about as big as 16 tires, but only uses the space of 2. you can load 8 tires or 4 boxes into the RHS Littlebird. 
![20170508235530_1](https://cloud.githubusercontent.com/assets/15272840/25827401/517a69e4-344b-11e7-8338-c77f694ca05b.jpg)

**Comment by bux** [comment]
![test](https://media.giphy.com/media/l2JeiapYMhPdGXKRa/giphy.gif)

**Comment by 654wak654** [comment]
Can item sizes be generated using `boundingBoxReal` and `getMass` or is that too idealistic?

**Comment by SilentSpike** [comment]
It's definitely possible (maybe could use as a backup and then override via config if necessary), though perhaps slightly idealistic as some models report totally inaccurate bounding boxes in my experience.

**Comment by 654wak654** [comment]
Quick test script: https://gist.github.com/654wak654/c19b2fa43bc2886e7a0343d202fb2265

All objects with an `ace_cargo_size` property have pretty accurate bounding boxes. Could probably use a function to pre-generate something like a `GVAR(volume)` config property, and switch to that.

**Comment by PabstMirror** [comment]
`boundingBoxReal` requires a real object but ace_cargo needs to work with virtual objects
e.g. by default we load the ace_wheel into cars without ever creating one

**Comment by 654wak654** [comment]
@PabstMirror The config would be pre-generated with a script, similar to how nouniformrestrictions does it: https://github.com/acemod/ACE3/blob/master/optionals/nouniformrestrictions/functions/fnc_exportConfig.sqf

**Comment by NightIntruder** [comment]
It would also be great to have the cargo's mass added to transporting vehicle via setMass (ie. newmass = CurrentVehicle setMass (currentVehicleMass+CargoMass)), but I guess it would only be useful for AFM-flyers. In basic FM and for land/sea vehicles it can produce unexpected results due to how those vehicles react on heavy cargo that was added: https://community.bistudio.com/wiki/setMass

**Comment by 654wak654** [comment]
Volumes calculated using the test script I posted before:
https://gist.github.com/654wak654/a665ba545db46913e98aebff148e5579

**Comment by kripto202** [comment]
Maybe we can base the size of the items and determine how much cargo it takes up. Then take that item and try to see how many times can that vehicle hold that item and that can determine the size of cargo that the vehicle can carry. I think this should be based more on size than weight.

**Comment by SilentSpike** [comment]
We should really have a standardised size to measure other items/vehicles relative to and list it on the wiki. Spare wheels is not a bad candidate.

**Comment by ColdEvul** [comment]
Is the idea to have a eyed size measurement or have some kind of string from the vehicle config?

Cause I could go through and size compare and make some kind of standardized system for it and post it on the wiki documentation. If needed :)

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
