### ISSUE TITLE
MicroDAGR accuracy should be better than 100m grids

### ISSUE THREAD

**Issue by VKing6** [acemod/ACE3#514]
The DAGR should be able to show your position in 10-digit grids.
Could maybe be implemented as an option. IMO 8 or 10 digits should be the default readout.

**Comment by Hammerr** [comment]
In my opinion for standard grid it should be 8 digit grid. It's 10x10m square and it's much better than 100x100. 1x1 square? Idk, should check this.

**Comment by VKing6** [comment]
I've never seen a GPS device that doesn't show the full ten digits.

@NouberNou the M109 already has code for finding the proper 10-digit grids on any map. Could we use that?

**Comment by Glowbal** [comment]
Closing this. Tracking on #1096
