### ISSUE TITLE
Disable Cookoff?

### ISSUE THREAD

**Issue by sargken** [acemod/ACE3#5142]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `stable` (stable / dev + commit hash)
**ACE3 Version:** `stable` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
-rhs
```
I was wondering if it was possible to disable the Vehicle cookoffs with a setting, as RHS has their own effects for vehicles that are damaged.

**Comment by jonpas** [comment]
Set `ace_cookoff_enable` using https://ace3mod.com/wiki/framework/settings-framework.html
