### ISSUE TITLE
UAV Yabhon refueling issue

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#5143]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.3.1` (stable)
**ACE3 Version:** `3.9.1` (stable)
 
**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Cannot connect the fuel nozzle with the Yabhon. 

**Steps to reproduce:**
- Place a fuel truck and a Yabhon UAV with bingo fuel on map. try to refuel the drone.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- not needed

![20170509233433_1](https://cloud.githubusercontent.com/assets/15272840/25874046/1282eb00-3511-11e7-8979-451a4fe7adae.jpg)
![20170509233437_1](https://cloud.githubusercontent.com/assets/15272840/25874049/17f15d06-3511-11e7-9020-a2ace48c2538.jpg)
![20170509233442_1](https://cloud.githubusercontent.com/assets/15272840/25874054/1c3a8dba-3511-11e7-9489-6dc426f4eaaf.jpg)

**Comment by Dystopian** [comment]
it works from some positions
![3](https://cloud.githubusercontent.com/assets/3867143/25878127/0165d81c-3531-11e7-8e47-ff7df9008fb3.jpg)

**Comment by PabstMirror** [comment]
I noticed this on a quad bike as well, I think the interaction scanning might have trouble with low vehicles.
