### ISSUE TITLE
Dubious comparison in `fnc_getDoorTurrets`

### ISSUE THREAD

**Issue by LordGolias** [acemod/ACE3#5159]
Hi guys and thank you for this great mod.

In `ACE3-3.9.1`, `common/functions/fnc_getDoorTurrets.sqf` line 26, we read

```
if (getNumber (_config >> "isCopilot" == 0) && {count getArray (_config >> "weapons") > 0}) then {
        _doorTurrets pushBack _x;
    };
```

I believe it should read

```
if (getNumber (_config >> "isCopilot") == 0 && {count getArray (_config >> "weapons") > 0}) then {
        _doorTurrets pushBack _x;
    };
```

as `_config >> "isCopilot" == 0` does not make sense.

This was found while I was testing the [SQF parser](https://github.com/LordGolias/sqf) in the ACE base code.

**Comment by commy2** [comment]
Based on this I'd say `ACE_common_fnc_getDoorTurrets` should fail every time with a script error.
I will test that.
