### ISSUE TITLE
Interaction is not working on players / units sometimes

### ISSUE THREAD

**Issue by evromalarkey** [acemod/ACE3#516]
**Mods:**
* @cba_a3
* @ace3
* @task_force_radio
* @alive
* @rhs_afrf
* @rhs_usaf
- Complete list of mods is in rpt log

**Placed ACE3 Modules:**
Medical, Blue force tracking

**Description:**
During the testing on our server, we sometimes got the problem that the interaction did not work on people. And even respawn did not help, what helped was changing the unit type. We were not able to reproduce it. But it definitely happened to someone sometimes.

BTW, I could interact with my dead body.*

**Steps to reproduce:**
Fooling around with people until it happen :D

**Where did the issue occur?**
Multiplayer, VTS 4.0 mission

**RPT log file:**
https://gist.github.com/evromalarkey/29892e07b8421038c473

**Comment by commy2** [comment]
Build is outdated.

Also:
15:15:55 [ACE] Full Version Number: 3.0.0.1-NOGIT-NOGIT

No commit ID - custom build.

You should retry:
- No other mods besides CBA and ACE enabled
- A newer build.

**Comment by evromalarkey** [comment]
will do ;)

**Comment by esteldunedain** [comment]
We had a few reports of this too. I have no idea what could cause this, apart of a CBA init EH not firing. If someone can repro this reliably please raise your hand.

**Comment by jaynus** [comment]
Most likely one of those option RHS units is bad.


@evromalarkey can you please get us the mission/types involved.

**Comment by esteldunedain** [comment]
In fact it happened with RHS too in our server, so it's likely related.

**Comment by evromalarkey** [comment]
We had normal vanilla units

**Comment by commy2** [comment]
Well. What unit type?

**Comment by MarcBook** [comment]
Today we had the same Problem:
Mods:

@cba_a3
@ace3
@task_force_radio
@bwa3
@rhs_afrf

Placed ACE3 Modules:
ACE_moduleMedicalSettings
ace_advanced_ballistics_ModuleSettings
ACE_ModuleHearing
ACE_moduleAssignMedicRoles
ACE_moduleTreatmentSettings
ACE_moduleAssignMedicVehicle

Description:
Sometimes we were able to fix this problem with leaving the team.
Reconnecting sometimes changed the units you can't interact with.

**Comment by jaynus** [comment]
We need unit classes please

**Comment by MarcBook** [comment]
Updated

**Comment by jaynus** [comment]
@koffeinflummi

**Comment by commy2** [comment]
Closing as dup, because there are now 2 of these and the other one is more recent.
