### ISSUE TITLE
Review realisticname

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#5166]
Realistic weapons in general could use a lookover

- We rename the "macer" to the maverick, jets expansion adds a "macer II"
- Some Renamed weapons are too long for some HUDs (e.g. "AIM-132 ASRAAM")
- Seems weird putting "9K121 Vikh" on a blufor vehicles compared to vanilla "Scalpel"
- Both vanilla "DAR" and "Shrieker" are now called Hydra

**Comment by JANXOL** [comment]
From what I have seen, some vehicle names have also reverted with jets expansion. Thunderbolt is wipeout again, kasatka is orca, etc.

**Comment by SilentSpike** [comment]
@JANXOL That has already been fixed in master :smiley: Will be in 3.10

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
