### ISSUE TITLE
Make Refuel capabilities dynamic

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#5173]
Entails:
- Dynamic interaction adding on init
- Ability to set any vehicle as ~~rearm~~/refuel vehicle easily (config and run-time)
- Proper API for 3rd party mods adding ~~rearm~~/refuel via simple config entries (currently have to copy all actions, which is just a mess)
- Follow Repair component way of doing it

**Comment by SilentSpike** [comment]
>Ability to set any vehicle as rearm/refuel vehicle easily (config and run-time)

For this point see #4780, I think all of the components that do this sort of publicly adjustable vehicle properties (for mission makers) combined with config properties (for addon makers) should be handling them in relatively the same manner. I have no idea what is the ideal way to do so, in that PR I just made it work based on the existing code :laughing:

**Comment by jonpas** [comment]
Sure, I mainly opened this this because I wanted to do this for a long time but just don't find the time and will to do it.

**Comment by jonpas** [comment]
Done for Rearm component in #5183.
