### ISSUE TITLE
Unable raise and lower some carryable objects 

### ISSUE THREAD

**Issue by StDIABLO** [acemod/ACE3#5174]
**Arma 3 Version:** `1.70` (stable)
**CBA Version:** `3.3.1` (stable)
**ACE3 Version:** `3.9.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**

- Can`t raise and lower some carryable objects (static weapons, empty ammobox, ace_dragging_fnc_setCarryable objects) when played on dedicated server.
On self hosted servers all works well.

**Steps to reproduce:**
- Create new mission with empty ammobox, try to raise / lower it on self hosted server and dedicated.

**Where did the issue occur?**
- Dedicated 

**Placed Modules:**
- 'None' .

**Comment by Phyma** [comment]
`_carriedItem setPosATL _position;` in fnc_handleScrollWheel dosent do anything on dedicated server

**Comment by Phyma** [comment]
Bug is if a item is remote or not.
If it is REMOTE then it cant change the position.

**Comment by Phyma** [comment]
Fix #5234
