### ISSUE TITLE
Titan Compact Missile Guidance Issue

### ISSUE THREAD

**Issue by Zareion** [acemod/ACE3#5178]
**Arma 3 Version:** `1.70.141764` stable
**CBA Version:** `3.3.1` stable 
**ACE3 Version:** `3.9.2` stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- When locked on with the Titan Compact on the dedicated server, the shot will fire keep flying upwards into the sky, rather than heading towards and striking the target.

**Steps to reproduce:**
Target with the Titan Compact, fire, look at the sky. Only happening on the dedicated server. It's working fine in the Editor. We're running the mission Antistasi.
https://youtu.be/2_oGc9NX9Cc

**Where did the issue occur?**
- Dedicated Server

**Placed Modules:**
- None

**RPT log file:**
https://pastebin.com/VCwH6NFh

**Comment by PabstMirror** [comment]
When connected to the server, could you goto ace's options menu and hit debug to clipboard.
And either posting the log, or checking the value of `ace_missileguidance_enabled`

**Comment by Zareion** [comment]
the value is set to 0. 

Debug Log:
https://pastebin.com/0qeFYySv

**Comment by PabstMirror** [comment]
The default value is 2 and it needs to be set to that for the javelins to work.
Contact the server admin and have them check their ace_server config and make sure to either not change `ace_missileguidance_enabled` or have it set to 2.

To be honest this probably shouldn't be a setting because it just causes problems; 
with missile guidance disabled javelins just don't work.

**Comment by Zareion** [comment]
Ok, that's actually me. So I don't actually have the server pbo file in there. I'm assuming I have to throw that in and just modify the hpp file?

**Comment by PabstMirror** [comment]
Hmm, that's strange.
The default should be 2, so if you don't have a server.pbo it should be using that.

It could also be set via the mission, you might want to check it's description.ext

**Comment by Zareion** [comment]
Doesn't look like it's set in there. Should I add the server config file to it and manage it through there?

**Comment by Zareion** [comment]
I just tried that, it didn't seem to fix it.

**Comment by PabstMirror** [comment]
I took a look at their mission file for "v1.7.5 (!BETA!)"
A3AS_Altis_(B).Altis -> description.ext:
```
class Params {
    #include "aceSettings.hpp"
};
```
aceSettings.hpp has:
```
    class ace_missileguidance_enabled {
        title = "Launchers";
        ACE_setting = 1;
        values[] = {0,1,2};
        texts[] = {"Off","On", "Not quite sure"};
        default = 0;
        typeName = "SCALAR";
        force = 1;
    };
```

**Comment by PabstMirror** [comment]
Remove that section or set the default to 2

**Comment by Zareion** [comment]
Ok, I had set it to 2 and it didn't seem to work. I'll try removing it.

**Comment by Zareion** [comment]
removing it seems to have fixed it, perfect! 

Thanks!

**Comment by PabstMirror** [comment]
Good to hear,
- ACE should look into removing that setting as it just causes problems
- It would be great if you could pass on this problem to the Antistasi devs as I'm sure others will have this same problem.
