### ISSUE TITLE
Kestrel headwind and crosswind computation wrong

### ISSUE THREAD

**Issue by senevoldsen** [acemod/ACE3#5181]
**Arma 3 Version:** `1.70` stable
**CBA Version:** `3.3.1` stable
**ACE3 Version:** `3.9.2` stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
The calculation for headwind and crosswind on the Kestrel is wrong.

**Steps to reproduce:**
For example, without advanced ballistics, set the runway/target direction to straight into the wind. The crosswind should be close to zero, and the headwind close to max, yet this is not the case. In fact from the calculation: `_textCenterBig = Str(round(cos(GVAR(RefHeading)) * _windSpeed * 10) / 10);` you can notice that the direction of the wind itself is not even used! Set the reference heading straight north, and you will get maximum headwind, set it straight east, you will get maximum crosswind; it does not matter where the wind blows, only how much.

Assume "unit circle" used by Arma going clockwise, and with 360 degrees. Assume the reference direction, R, is 0, and the wind is coming from relative X.

Then the head wind is:  `cos(X) * windSpeed`
And the cross wind is: `-sin(X) * windSpeed`

For example, lets say relative X is 30 and windspeed is 10,
then headwind becomes =  8.66 which fits because wind is coming from close to the reference direction,
and crosswind becomes = -5.00 which also fits since the wind is coming a bit to the right relative to the reference direction.

Now if the reference direction is not 0, then simply subtract R from X and modulo with 360 (which you technically don't have to), making the calculation:

headwind :  `cos(windFromDir - RefHeading) * windSpeed`
crosswind: `-sin(windFromDir - RefHeading) * windSpeed`

Currently the measurements are shown in absolute values. From the manual linked to on the ACE Features site, it seems at least tailwind is shown negative, so the absolute value should not be shown for that. Maybe the same applies for crosswind.

When running with advanced ballistics, the intention seems to be the player's direction also affects the measurement, which agree with the manual that states that you should turn the kestrel into the wind. So rather than always getting the true windspeed it should scaled by how well the player looks into the wind (the players direction is opposite where the wind is headed). And rather than the true wind direction the player's current direction (the player's guess of where the wind comes from) should be used. So for advanced ballistics the calculations become. 

headwind :  `cos(playerDir - RefHeading) * windSpeed * cos(playerDir - windFromDir)`
crosswind: `-sin(playerDir - RefHeading) * windSpeed * cos(playerDir - windFromDir)`

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

Editor (Singleplayer)

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

None

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by PabstMirror** [comment]
Some discussion on this in https://github.com/acemod/ACE3/pull/4552

**Comment by senevoldsen** [comment]
It seems there has been made two choices regarding advanced ballistics. When using advanced ballistics

1. The player has to look into the wind to get an accurate speed measurement.
2. The Kestrel reports the measured wind speed at the current direction it is being held, rather than magically showing the true wind direction.

For 1. the player's influence on the wind component is already included by MeasureWindSpeed depending on the mode. For 2. it is handled when displaying. However, the actual computation of the crosswind is still wrong.

Here is the current computation of the crosswind:

    if (missionNamespace getVariable [QEGVAR(advanced_ballistics,enabled), false]) then {
        _textCenterBig = Str(round(abs(sin(GVAR(RefHeading) - _playerDir) * _windSpeed) * 10) / 10);
        _textInfoLine1 = format["%1 m/s @ %2", round(_windSpeed * 10) / 10, round(_playerDir)];
    } else {
        _textCenterBig = Str(round(abs(sin(GVAR(RefHeading)) * _windSpeed) * 10) / 10);
        _textInfoLine1 = format["%1 m/s @ %2", round(_windSpeed * 10) / 10, round(_windDir)];
    };

The term `- _playerDir` has already been incorporated into `_windSpeed`, and should not be there. But what is missing is the interaction between the `RefHeading` and the wind. It should be:

    if (missionNamespace getVariable [QEGVAR(advanced_ballistics,enabled), false]) then {
        _textCenterBig = Str(round(abs(sin(GVAR(RefHeading) - _windDir) * _windSpeed) * 10) / 10);
        _textInfoLine1 = format["%1 m/s @ %2", round(_windSpeed * 10) / 10, round(_playerDir)];
    } else {
        _textCenterBig = Str(round(abs(sin(GVAR(RefHeading) - _windDir) * _windSpeed) * 10) / 10);
        _textInfoLine1 = format["%1 m/s @ %2", round(_windSpeed * 10) / 10, round(_windDir)];
    };

Same applies to headwind.

**Comment by Laid3acK** [comment]
I'm not scripter or programmer, so i won't comment your formula.
I just can say that the crosswind measurement is correct with the **Advanced ballistic module enabled**.

Two important points in my opinion:
- A Kestrel works with accuracy into the wind and only into the wind.
- Actually in-game and before all `HEADWIND` or `CROSSWIND` measurements, 
the Kestrel must be calibrated manually and correctly 
with the wind arrow and the `set heading` (`Auto Set`):
The `HEADWIND` must be full, the `CROSSWIND` must be zero:
- https://steamuserimages-a.akamaihd.net/ugc/773903676820845258/CFB7F6D510FD381E543A4CC60D28515B8ABB391A/

- https://steamuserimages-a.akamaihd.net/ugc/773903676820845650/7F02A677084054E151A6D8384F4414836C86CD71/

At this moment, the Kestrel can be used like in this video 
(`Auto Set` or `Manual Set` at your own convenience):
https://www.youtube.com/watch?v=4Q_qgXwlRqk

We haven't got an "Automatic" headwind or crosswind actually and, to be honest, those measurements aren't easy because we have a wind a little bit mad in-game, except if it's overwritten in the editor.

**Comment by senevoldsen** [comment]
**Yes with advanced ballistics I get the right readings when I use the Kestrel appropriately.** But when I use it inappropriately - do not look into the wind - the wrong value I get is wrong. When looking 90 degrees off the wind, the Kestrel should not measure anything since their is no wind towards it, instead it gives high values. Another example `set heading` about 45 degrees of the side of actual wind direction. And measure in that direction. You will of course get wrong (lower) values, because the wind is coming in to the Kestrel on an angle. But they are too low and not comparably low. Unless that is what your mean by your first bullet point? For example in this picture I have the heading set 45 degrees right of the wind, and am (incorrectly) measuring 45 degrees off the wind. Yet the computation for headwind remains 100% correct and the crosswind is 0% correct. Both should be the same (although not necessarily 100% or 50%). http://i.imgur.com/2XTr4e4.jpg

But without advanced ballistics the computations are always wrong.

**Comment by senevoldsen** [comment]
> Actually in-game and before all HEADWIND or CROSSWIND measurements,
the Kestrel must be calibrated manually and correctly
with the wind arrow and the set heading (Auto Set):
The HEADWIND must be full, the CROSSWIND must be zero:

Not sure exactly what you are saying here, but it sounds like you are saying  `set heading` should always be set into the wind. If that is so, then it is wrong. `set heading` should be set to the direction you want to measure head/cross-wind across. E.g. the wind is coming from 30 degrees I want to measure crosswind/headwind for 70 degrees, the `set heading` should be set to 70, and I should turn to 30 when measuring. https://github.com/acemod/ACE3/blob/master/extras/K4500_Instruction_Manual_English.pdf

**Comment by senevoldsen** [comment]
Okay, I see now how the computation with advanced ballistics does compute correctly, and my version of it was indeed a bit too correct (and cheating a very little bit). I am assuming that when running without advanced ballistics, the only difference is that you don't have to turn into the wind? In that case the formulas should be:

    if (missionNamespace getVariable [QEGVAR(advanced_ballistics,enabled), false]) then {
        _textCenterBig = Str(round(abs(sin(GVAR(RefHeading) - _playerDir) * _windSpeed) * 10) / 10);
        _textInfoLine1 = format["%1 m/s @ %2", round(_windSpeed * 10) / 10, round(_playerDir)];
    } else {
        _textCenterBig = Str(round(abs(sin(GVAR(RefHeading) - _windDir) * _windSpeed) * 10) / 10);
        _textInfoLine1 = format["%1 m/s @ %2", round(_windSpeed * 10) / 10, round(_windDir)];
    };

**Comment by Laid3acK** [comment]
> set heading should be set to the direction you want to measure head/cross-wind across.

You are totally right and if you use it like in the video above, you will have the correct head/crosswind with the Advanced Ballistic module enabled (and without my "calibration" purely cosmetic).

With the AB module disabled and the Wind Deflection module enabled, the Kestrel works with a "Magic" wind by design.

Personally, i think that an AB Kestrel Lite, with only the `User Screen 1`, the `HEADWIND` and `CROSSWIND` panels could be a better solution for the default ballistic (or ACE ballistic, i don't know how to call it correctly).

**Comment by senevoldsen** [comment]
What do you mean by a magic wind? With or without wind deflection my bullets are affected by the current wind in-game. Here I use no advanced ballistics, but have enabled wind deflection: http://imgur.com/a/x0Vxs  (the left kestrel shows the heading I set before measuring).

**Comment by Laid3acK** [comment]
> What do you mean by a magic wind?

Relative to the direct and full wind in the Kestrel when the AB module is disabled. :)

**Comment by ulteq** [comment]
Pretty much everything @senevoldsen said is correct. I will create a pull request that fixes the bug.
