### ISSUE TITLE
Missing Inventory on PlasticCases

### ISSUE THREAD

**Issue by Tress16** [acemod/ACE3#5186]
**Arma 3 Version:** `actual` (stable)
**CBA Version:** `3.3.1` (stable)
**ACE3 Version:** `3.9.2` (stable)

**Mods:**
-  CBA
-  ACE3
-  ACEX
-  ALiVE
-  Heros Survive
-  Task Force Radio
-  Enhanced Movement
-  Backpack on Chest
-  RHS:USF
-  ACE Compat RHS:USF
-  Specialist Military Arms
-  VSM - All in One collection

**Description:**
-  The addAction "Inventory" is lost.

**Steps to reproduce:**
-  Placing a Land_PlasticCase_01_large_F and try to open the inventory.

**Where did the issue occur?**
-  Dedicated Server

**Placed Modules:**
-  ACE handled with ACE-Server.pbo.

**Comment by jonpas** [comment]
We are experiencing that too, but it is not something we add, it seems like BI removed it from those boxes and a few others.

**Comment by Tress16** [comment]
Aaahh... I'm sad to hear that.
Hope that BI "fixed" it or bring it back.

**Comment by commy2** [comment]
What is "addAction Inventory"?

**Comment by jonpas** [comment]
"Inventory" action in action menu on an object.

**Comment by commy2** [comment]
That has nothing to do with `addAction`. That's just an action menu entry. `addAction` is the method to add items to the action menu via script. But there also is the useraction class for adding config based action menu entries. And this one is neither, it's a hard coded action from CfgActions.

**Comment by PabstMirror** [comment]
hotfix:
>Fixed: Some storage container inventories did not work properly (https://feedback.bistudio.com/T124837)
