### ISSUE TITLE
"Receiving IV [x ml]" only logged to medical menu, not activity view.

### ISSUE THREAD

**Issue by Pergor** [acemod/ACE3#5192]
**Arma 3 Version:** `1.70`
**CBA Version:** `3.3.1.170504`
**ACE3 Version:** `3.9.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
As mentioned in title: Giving an IV is only properly logged in the medical menu. In the regular activity view you can see that someone has received an IV, but the ml counter is not logged, neither on the receiving body part nor any other part.

**Steps to reproduce:**
- Hit someone.
- Give him an IV.
- Take a look at the body part: ml counter is not shown.
- Take a look at medical menu for the receiving unit: ml counter is being shown.

**Where did the issue occur?**
- everywhere.

**Placed Modules:**
- advanced medical of course.

**Comment by PabstMirror** [comment]
Fixed in rewrite, but we should probably pick this up for next release as it's a very small fix
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_displayPatientInformation.sqf#L71 
`_unit` instead of `_target`
