### ISSUE TITLE
Discussion: Advanced Fatigue Weapon Stance/Position Penalties

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#5194]
**Arma 3 Version:** `1.70 Jet DLC
**CBA Version:** `3.3.1.170504`
**ACE3 Version:** `3.9.2`

**Mods:**
- CBA_A3
- ace

**Description:**
- When moving around with advanced fatigue their appears to be different penalties set to fatigue drain rates, as well as the how fast and how much of the lost stamina you can recover (not sure what this is called) for the different weapon stances (weapon lowered (WL), non-combat pace (NCP), and combat pace(CP)).

When moving around in the WL weapon stance there is a huge reduction in stamina drain upwards of 70% (guessing) that or this is the baseline drain rate. This appears to simulate having your weapon on a sling/lowered therefore reducing stamina drain, because your body is able to move more naturally, ie swinging your arms by your sides/not holding onto the weapon. This is something I really like and seems to be at a good level.

My issue starts with the increased drain rates of CP and NCP in particular, the CP drain rate penalty, while still a bit too high in my opinion make sense because you're holding your weapon up at eye level and putting a lot of effort into keeping it stable, but the speed and in particular the amount you can recover while resting penalty seems way to high, maybe a 10-20% reduction in this recovery penalty 

The NCP drain rate penalty and recovery penalty on the other hand just seems insane to me, this is supposed to be simulating a trained soldier yet with a load of any wear between 30-50kg and an assault rifle, when jogging or sprinting a few hundred meters your guy will drain stamina likes it's pouring out of bullet wound and you will only recover maybe 50% (if your lucky (for comparison in WL you seem to recover about 85-95%)) of the lost stamina when you stop and rest.

I've spent a lot of time messing around with different module setting and these issues persist pretty much no matter what settings you use because they run at a higher level to the settings available in the module, bar making it so ridiculously high that you might as well just turn off fatigue completely.

I might be completely off base but I wanted to start a discussion about it to see what other people thought, or if someone can point me to the file names and lines were these penalties are defined in the .pbo 

**Steps to reproduce:**
- Place Advanced Fatigue module (default settings, this issue is the same with all settings) and a soldier with 30-50kg's of equipment and move around at different speeds (walking, jogging, sprinting) while changing your weapon stance from combat pace to non-combat pace and weapon lowered.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- Advanced Fatigue

**Comment by DracheTek** [comment]
For your reference: The average velocity of five kilometer cross-country racing with standard military loadout (30kg namely) should be 25 minutes.

**Comment by Armilio** [comment]
It would be nice to have a module setting that touch the multiplier (if there are ones) of NCP and CP stamina draining, yeah. I mean, i don't know if it's realistic or not, probably yes, but these settings force you to always walk if you want do some urban CQB with a pointed weapon without lose ton of stamina clearing two houses. 

I really like the idea of give more relevance to the weapon stance anyway, as i like force people to walk when needed and not always run and sprint, but i would like also some customization options because sometimes as a mission maker i have to find compromises.

**Comment by Drift91** [comment]
I couldn't agree more with @Snak3Doc and @Armilio. Also, I think these values are based on the new vanilla values that were added maybe 6 months or so before Apex came out. The way I see it when BI nerfed stamina they took it from one extreme to the other.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
