### ISSUE TITLE
RHS / ACE3 Compatability PBO prevents closing of CH-47 Ramp

### ISSUE THREAD

**Issue by AJCStriker** [acemod/ACE3#5196]
**Arma 3 Version:** `stble`
**CBA Version:** `Steam Workshop Latest (23MAY2017)` (stable / dev + commit hash)
**ACE3 Version:** `Steam Workshop Latest (23MAY2017)` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- RHS: USAF
- ACE / RHS USAF Optional Compatibility PBO
```

**Description:**
Enabling the RHS / ACE Optional pbo causes the CH-47 Ramp to be unable to close. An uneducated glance through the codebase shows that it could be to do with the canCloseDoor function? The ramp can be opened and levelled however the close ramp option is not available in the list when the ACE Compatibility pbo is active.

I hope that this isn't too large of an issue and is simply a misconfigured if statement as it would be a crying shame for these two great mods not to work well together!

**Steps to reproduce:**
- Load game without Ace / RHS compatibility PBO enabled
- Place CH-47
- Observe that once the ramp is open a "Close Ramp" option is available.
- Reload the game with the compatibility PBO
- Repeat the above steps and observe that the "Close Ramp" option is no longer present.

**Where did the issue occur?**
- Dedicated Multiplayer
- Solo Editor

**Placed Modules:**
None

**RPT log file:**
N/A right now - I will upload one later this week when I have another chance to test this

**Comment by PabstMirror** [comment]
Thanks for the great issue report,
problem was with canCloseDoor function
should be fixed with next ace release

**Comment by AJCStriker** [comment]
@PabstMirror Thanks for the quick turnaround. Is it rude to ask how long the ACE release window is - or perhaps if there is an ACE dev build we can use to test the fix?

**Comment by PabstMirror** [comment]
Shouldn't be too much longer (no guarentees)
We are working on making dev builds available.
