### ISSUE TITLE
Micro lags every 3 seconds in MP

### ISSUE THREAD

**Issue by OnkelDisMaster** [acemod/ACE3#520]
**Mods:**
* CBA
* ACE3
* BWMod
* RHS:Escalation
* IslaDuala3
* TFAR

**Placed ACE3 Modules:**
* Medical Settings
* Treatment Settings
* Blue Force Tracking 
* DAGR Map Fill
* Map
* Rallypoint System
* Wind Deflection
* Respawn System

**Description:**
When playing with greater ammounts of players on MP, the games starts to get small stills every 2-3 seconds, making it unplayable.

**Steps to reproduce:**
Playing with others on a dedicated Server, waiting a bit, then it occurs

**Where did the issue occur?**
MP only

**RPT**
The RPT is Spammed with:
17:59:34 Generating ST on the fly is very slow
then
18:23:02 Client: Network message 4677a (update info 87185b60) is pending

**Comment by PabstMirror** [comment]
Have you binerized arma (using make.py not build.py)?
`Generating ST on the fly is very slow` is caused by unbinerized p3ds according to http://forums.bistudio.com/showthread.php?72743-Generating-ST-on-the-fly

**Comment by OnkelDisMaster** [comment]
I´ve seen this post too, but there is no unbinarized p3d

**Comment by OnkelDisMaster** [comment]
It works in SP fine i think its some network issue, because 

"17:59:34 Generating ST on the fly is very slow" is spammed about 10 times and stops, "18:23:02 Client: Network message 4677a (update info 87185b60) is pending" keeps going forever when i´m on a Dedi server

**Comment by jaynus** [comment]
The binarization issue is specifically due to unbinarized PBO's over the network.  Please upload the full RPT so we can see versions.

**Comment by OnkelDisMaster** [comment]
UPDATE: Removed all the Modules except the Medicals, disabled litter, and turned off unit sync. WIth this workaround the problem was fixed.

**Comment by dedmen** [comment]
Still disabling Modules and changing standard parameters is just a workaround not a fix.
I also still have this problem on 3.0.1 in MP. Could not try the workaround yet.
