### ISSUE TITLE
ACE Stamina - Going prone whilst running unarmed

### ISSUE THREAD

**Issue by ZikiCZ** [acemod/ACE3#5200]
**Arma 3 Version:** `1.70+hotfix` (stable)
**CBA Version:** `3.3.1` (stable)
**ACE3 Version:** `3.7.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- There's a small issue with the stamina system. If you are unarmed and you go prone (whilst walking or running) your character runs for a second and then goes prone, problem is that this causes your stamina to drop extremely and even without any gear at all it takes at least a half away.
https://youtu.be/H8hl8lvooC4

**Steps to reproduce:**
- With default settings (ACE stamina system on) all that has to be done is to run unarmed and go prone.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Default settings (ACE stamina system on).

**RPT log file:**
- RTP:
[Arma3_x64_2017-05-25_16-27-52.txt](https://github.com/acemod/ACE3/files/1029299/Arma3_x64_2017-05-25_16-27-52.txt)

- ACE_debug: 
[ace_debug.txt](https://github.com/acemod/ACE3/files/1029284/ace_debug.txt)
.

**Comment by PabstMirror** [comment]
Ref https://github.com/acemod/ACE3/issues/4880
Should be fixed in next release
