### ISSUE TITLE
Zero divisor when advance throwing Chemlight (IR)

### ISSUE THREAD

**Issue by Phyma** [acemod/ACE3#5207]
**Arma 3 Version:** `Stable` (stable / rc / dev)
**CBA Version:** `3.3` (stable / dev + commit hash)
**ACE3 Version:** `3.9.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- When advance throwing a Chemlight IR there is a zero divisor  in fnc_exitThrowMode.sqf
`[QEGVAR(common,setShotParents), [_activeThrowable, _unit, (getShotParents _activeThrowable) select 1]] call CBA_fnc_serverEvent;`

variable _activeThrowable is in weird form: 8d881600# 178009.
While others are on the form 1779997.
So getShotParents returns a blank array.

The variable is being distorted in fnc_prime here: 
```

// Throw Fired XEH
[QGVAR(throwFiredXEH), [
    _unit, // unit
    "Throw", // weapon
    _muzzle, // muzzle
    _muzzle, // mode
    _throwableType, // ammo
    _throwableMag, // magazine
    _activeThrowable // projectile
]] call CBA_fnc_globalEvent;
```

**Steps to reproduce:**
- Open editor
- Spawn soldier with Chemlight IR
- Start advance throwing them

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by Phyma** [comment]
#5208 Prob fix!

**Comment by jonpas** [comment]
This was introduced in #5052 it seems.

**Comment by Phyma** [comment]
So CBA_fnc_addeventhandler is taking code as its second parameter.

Should it then be: _this call FUNC(throwFiredXEH) or just call FUNC(throwFiredXEH)?

Because now its just FUNC(throwFiredXEH)

**Comment by Phyma** [comment]
Also is CBA_fnc_serverEvent still a thing? or should it be CBA_fnc_globalEvent.
https://github.com/acemod/ACE3/blob/master/addons/advanced_throwing/functions/fnc_exitThrowMode.sqf#L37

**Comment by Phyma** [comment]
#5209 possible fix, missing call

**Comment by Phyma** [comment]
Hope you fix it with that. I still think its a mystery that QGVAR(activeThrowable) get changed in the global event: 
```

systemChat format ["Before globalevent getvar: %1",_unit getVariable [QGVAR(activeThrowable), objNull]];
// Throw Fired XEH
[QGVAR(throwFiredXEH), [
    _unit, // unit
    "Throw", // weapon
    _muzzle, // muzzle
    _muzzle, // mode
    _throwableType, // ammo
    _throwableMag, // magazine
    _activeThrowable // projectile
]] call CBA_fnc_globalEvent;
systemChat format ["After globalevent getvar: %1",_unit getVariable [QGVAR(activeThrowable), objNull]];
```
Picture of the logg:
https://drive.google.com/file/d/0B29KgFH6HzdIZ3JPNmNqak5HMDQ/view?usp=sharing

**Comment by PabstMirror** [comment]
Take a look at https://github.com/acemod/ACE3/blob/master/addons/chemlights/functions/fnc_throwIR.sqf

It deletes the old grenade, creates a new one
then changes the variable back in advanced throwing.

**Comment by Phyma** [comment]
Aa thanks.

That explains alot :)
