### ISSUE TITLE
Addon vehicles arn't effected by ace_cargo_size

### ISSUE THREAD

**Issue by Pasrules** [acemod/ACE3#5211]
ACE 3.9.2

`this setVariable ["ace_cargo_size", 20]` does not work on vehicles from addons. Tested on Vanilla (works), BAF, RHS (no change in inventory size). Compatibility for those mods were not used, script was used on vehicle init.

To reproduce place a vehicle with init: `this setVariable ["ace_cargo_size", 20]` and check the cargo size by interacting with it

**Comment by SilentSpike** [comment]
Would be fixed by #4780

**Comment by SilentSpike** [comment]
PR #4780 was merged which includes public functions to set the cargo size and space of objects/vehicles. These will add the necessary action menu information if an object's class isn't already set up with it.

As such, I'm closing this issue as resolved! :+1:
