### ISSUE TITLE
Add object support to zeus fnc_getModuleDestination

### ISSUE THREAD

**Issue by kymckay** [acemod/ACE3#5215]
**Description:**
- This issue is basically just a reminder for myself or anyone interested to look into. Currently `fnc_getModuleDestination` returns only position ASL, but it could be nice if it would (optionally?) return the object under the curator cursor when the destination is clicked. For example, `doSuppressiveFire` command used by the respective module supports the target being a unit and not just a position, would allow for more accurate suppression of moving units.

**Comment by chris579** [comment]
How does the AI behave when you assign an object for `doSuppressiveFire`? Will it still suppress the target even if it is not in line of sight (e.g. hidden by an house)? Would support the cheaty AI. However, a object param would indeed be nice.

My approach for the object param would be using nearestObjects or iterating through all players which is more hacky than stylish. Do you have a different approach for this?

**Comment by SilentSpike** [comment]
Yeah, zeus caches the target (object, group, waypoint or marker) currently under the cursor into a variable you can read:

`GETMVAR(bis_fnc_curatorObjectPlaced_mouseOver,[""])`

I believe the form is `["TYPE", data]` (e.g. `["OBJECT", objNull]`)

**Comment by SilentSpike** [comment]
To expand this issue further, we could actually allow the getModuleDestination function to take an array of allowed types. That way you could also target a group.

**Comment by chris579** [comment]
This could be integrated quite easily. For the callback I would return both the position and the object under the cursor.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
