### ISSUE TITLE
RC Units Inherit Player Damage Threshold

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#5218]
Is it possible to stop units that zeus remote controls from inheriting player medical settings, makes for some really awkward situations

**Comment by PabstMirror** [comment]
What is the specific problem with RC units?

There is a setting `ace_medical_remoteControlledAI` which controls if RC units can go unconscious.

**Comment by Snak3Doc** [comment]
When Zeus takes remote control of ai units the ai unit seems to inherit the "player medical settings", I normally have AI on 1 and players on 5  but when Zeus takes RC the ai take the same amount of damage as players before going down

**Comment by SilentSpike** [comment]
I do think we should just always be treating remote controlled units as AI in the rewrite, because it just seems like a random inconsistency to users and adds an extra setting which could be removed.

**Comment by Snak3Doc** [comment]
Ill try out your fix later this week, thanks man
