### ISSUE TITLE
MQ-12 Falcon can't be rearmed

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#5220]
**Arma 3 Version:** `1.7.0` (stable / rc / dev)
**CBA Version:** `3.3.1` (stable / dev + commit hash)
**ACE3 Version:** `3.9.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Can't be rearmed via ace interaction at an ammo truck.

**Steps to reproduce:**
- place a hemmt ammotruck and a mq 12 falcon on map. delete the ammo of the drone. try to rearm .

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- not needed, needs a config entry.

**Comment by PabstMirror** [comment]
Will be fixed by https://github.com/acemod/ACE3/pull/5183
