### ISSUE TITLE
The "CCIP" for the GAU-8 in the A-136 Wipeout is missing.

### ISSUE THREAD

**Issue by Exentenzed** [acemod/ACE3#5221]
**Arma 3 Version:** `1.70.141898` (stable)
**CBA Version:** `3.3.1.170504` (stable)
**ACE3 Version:** `3.9.2.18` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The predicted impact point of the main gun for the A-136 wipeout does not show up when playing with ace. Strangely enough the CCIP of the unguided rockets and GBU **does** show up.

**Steps to reproduce:**
Go into the editor and simply place a A-136 wipeout in the air, with player as pilot. And observe how the CCIP is missing when played with ace. (Only for the 30mm main gun)

**Where did the issue occur?**
Self-Hosted Multiplayer / Editor (Singleplayer)
Only tested it in these modes.

**Placed Modules:**
None

**Comment by PabstMirror** [comment]
Caused by
```
class 1000Rnd_Gatling_30mm_Plane_CAS_01_F: VehicleMagazine {
        ammo = "ACE_Gatling_30mm_HE_Plane_CAS_01_Deploy";
```
Which also causes `Submunition: ACE_Gatling_30mm_HE_Plane_CAS_01_Deploy`

Ref: https://github.com/KoffeinFlummi/AGM/issues/802
Seems like it was done to keep burst length consistent?

I think we should just drop this.
