### ISSUE TITLE
Cant slow open glassdoors

### ISSUE THREAD

**Issue by Phyma** [acemod/ACE3#5225]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Cant slow open glass doors with ACE. Ctrl+space with scroll wheel that is.

**Steps to reproduce:**
- Go to a glass door.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**Extra info:**
I will have a fix for this soon.

**Comment by PabstMirror** [comment]
LMB will open those doors

**Comment by Phyma** [comment]
#5226

**Comment by Phyma** [comment]
Got merged so closing this

**Comment by jonpas** [comment]
In the future just add "closes #5225" in PR description or commit message and it will close the issue automatically.
