### ISSUE TITLE
Show Kestrel not working

### ISSUE THREAD

**Issue by worsin** [acemod/ACE3#5227]
Latest everything

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Can open Kestrel cannot SHOW Kestrel. No hotkeys work.
**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by PabstMirror** [comment]
A common source of problems on the kestrel  is that it must be in uniform or vest (not backpack)

`if (!("ACE_Kestrel4500" in (uniformItems ACE_player)) && !("ACE_Kestrel4500" in (vestItems ACE_player))) exitWith { false };`

**Comment by Phyma** [comment]
Can't remake the problem on single player editor or dedicated server. 
Hot keys work just fine. But yeah as Pabst said in uniform or vest or nothing will work.

**Comment by PabstMirror** [comment]
Should be usable if placed in uniform or vets. Let us know if still having problems
