### ISSUE TITLE
only adminlvl 2> can see NUMBERS at checking bloodpressure/pulse via medical-menu - why??

### ISSUE THREAD

**Issue by DerBorny** [acemod/ACE3#5232]
Hi!
We have a problem with the medical menu... we use it on Tanoa Life 5.0 and only if the adminlevel is set above 2, the person can check blood pressure and pulse and can see NUMBERS... otherwise its something like "normal" "too high" etc

can someone help?
there is no way to set permissions for each admin level... so i think it has to be coded in ACE addons

**Comment by Phyma** [comment]
Have you made sure that the person is set as a medic? 
Because only medics can see the numbers.

**Comment by DerBorny** [comment]
yea, sure, we are both on medic level 20... all other things work...
i can see the numbers (with admin level 5) - he can't (with admin level 0, 1, 2)

**Comment by Glowbal** [comment]
Ace does not have anything with admin levels.. This sounds like an issue with Tanoa Life, not ACE3. You should ask their developers for help.

**Comment by PabstMirror** [comment]
I think he might mean `attendant`?
Or what ace uses to determine who is a medic?

Checking blood pressure, non-medics will see "Low/Normal/High", medics will see "XX/YY"

You can change this by setting
`player setVariable ["ace_medical_medicClass", 2]`
You can verify this by checking the results of `[player] call ace_medical_fnc_isMedic`

**Comment by PabstMirror** [comment]
There also is an ace setting `ace_medical_medicSetting`, you could set this to 0 to make everyone a medic
