### ISSUE TITLE
Orca/Kasatka minigun not working

### ISSUE THREAD

**Issue by JANXOL** [acemod/ACE3#5236]
**Arma 3 Version:** `1.7` (stable )
**CBA Version:** `3.3.1` (stable )
**ACE3 Version:** `3.9.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Minigun of kasatka/orca or whatever arma calls it (CSAT light heli) cannot be fired. Regardless of helis loadout, it cannot be selected as a weapon. For example, if the heli is equipped with minigun and dagr (as by default), pilot can only select DAGR as weapon.

**Steps to reproduce:**
- Go into editor or zeus, place a kasatka/orca (armed version). Get into pilot seat and attempt to fire minigun.

**Where did the issue occur?**
- Self-Hosted Multiplayer/ Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- Tried with both no modules, and a fully setup mission with all config modules

**Comment by Phyma** [comment]
From RPT:
```14:13:32 wrong 'pylonWeapon' in magazine:'PylonWeapon_2000Rnd_65x39_belt' this magazine cannot be used in weapon'LMG_Minigun_heli'
14:13:32 unable to create weapon for missile 'PylonWeapon_2000Rnd_65x39_belt', check config entry'pylonWeapon' ```
