### ISSUE TITLE
Feature discussion Medical: Interaction -> Medical

### ISSUE THREAD

**Issue by Phyma** [acemod/ACE3#5239]
**Description:**
- So I have been thinking about the self interaction and how to make the medical system easier to read. So I have been thinking of if you have a injury  - Yellow cross on body part. 
Then the first medical symbol should also be that color to show that, hey you are injured. 
So the Interaction -> Medical will  have the same color as the worst cross if you go one level down.

What are your thoughts about this?

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
