### ISSUE TITLE
False name for CH-67 Huron

### ISSUE THREAD

**Issue by Steev406** [acemod/ACE3#5241]
**Mods:**
- ace3 Real Name

**Description:**
The CH-67 Huron is not CH-47 Chinook in real name mod. The vanilla name don't need any modification.
It's a fictive helicopter based in the CH-47.
As was the Mi-290 Taru as based in the CH54 SkyCrane ( For real name mod the most reallistic is CH-74 SkyCrane )
Thanks for reading

**Comment by BlueNexus** [comment]
Wrong. The Taru is based on the Kamov Ka-226. 
https://en.wikipedia.org/wiki/Kamov_Ka-226

**Comment by bux** [comment]
Btw. we called it CH-47I not just CH-47
https://github.com/acemod/ACE3/blob/master/addons/realisticnames/stringtable.xml#L949

And @BlueNexus is right.
