### ISSUE TITLE
Is it possible to fix grenade launcher smoke grenades bouncing for 100's of metres?

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#5252]
As Im sure everyones aware smoke grenades have a tendency to bounce for 100's of meters especially when fired across fields (or the classic from a chopper in which case it can bounce for kilometers) and just generally behave weird.

Is it possible to fix this by limiting the retained velocity after each bounce/impact or something?

**Comment by Phyma** [comment]
Please fill in the way you should fill it in

```
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.
```

**Comment by Snak3Doc** [comment]
Sorry didn't think it was relevant considering its a well known vanilla bug since alpha just thought some the people here might have the skill to come up with a fix it

**Comment by jonpas** [comment]
There is: https://github.com/Theseus-Aegis/tac-a3-mods/blob/master/addons/ballistics/CfgAmmo.hpp

However, it does have some side effects, like rarer bouncing on closer shots.

**Comment by Snak3Doc** [comment]
Ahh thank you so much Jonpas, my CAS strikes wont hit 200m behind my target anymore ;)

**Comment by jonpas** [comment]
Heh, you are free to use the mod, you just need `main` and `ballistics` and it works on top of ACE3. I should probably rethink if something changed since I made it, maybe it's viable to do that in ACE3 itself now. @BaerMitUmlaut ?

**Comment by jonpas** [comment]
Ah I looked it up, #4648, using `shotSmoke` removes the sound (impact/bounce one I guess), that's why it's not in ACE3.

**Comment by Snak3Doc** [comment]
That sucks, thanks for the help though man
