### ISSUE TITLE
1st person/ 3rd person view - lighting ACE3 issue?

### ISSUE THREAD

**Issue by christiandjurberg** [acemod/ACE3#5257]
![arma 3 2017 06 07 - 00 00 15 13-1st-person](https://user-images.githubusercontent.com/29239987/26854761-dbcc6c4a-4b17-11e7-9276-6c20d47a9abe.png)
![arma 3 2017 06 07 - 00 00 23 14-3rd-person](https://user-images.githubusercontent.com/29239987/26854760-dbcaeee2-4b17-11e7-960c-cb734d6907a8.png)

**Arma 3 Version:**  1.70 stable 
**CBA Version:** 3.3.1.170504 
**ACE3 Version:** v3.9.2 stable 

**Mods:**
- CBA_A3
- ace
-SFP (I've tried SFP with and without ACE3 and with ACE3 the lighting between 1st person  and 3rd person is different. Without ACE3 its not)

-Reshade Turned OFF and removed from game dir folder.

**Description:**
- With ACE3 the lighting between 1st person and 3rd person view is different. Without ACE3 its not (please see attached screenshots). -Is this meant to be/ expected? Is it because communities using ACE usually do it hard core realism with Forced 1st person view?

**Steps to reproduce:**
- Not sure this is an issue/ defect. Meant to be? Anyway the colouring and lighting feels a bit strange in 1st person view I believe.

**Where did the issue occur?**
- Multiplayer and singleplayer. With or without other mods.

**Placed Modules:**
- None

**RPT log file:**
- Screenshots on Dropbox:
[](https://www.dropbox.com/sh/vyllhndkj9ss24s/AADV30WfxYAgVGVy1erqwyoqa?dl=0)

https://www.dropbox.com/sh/vyllhndkj9ss24s/AADV30WfxYAgVGVy1erqwyoqa?dl=0

**Comment by madpat3** [comment]
maybe you got your sunglasses on XD

**Comment by jonpas** [comment]
What @madpat3 said, put away your glasses/goggles. 😆

**Comment by PabstMirror** [comment]
ace_goggles has 2 settings you should take a look at.
- `ace_goggles_showInThirdPerson` is client settable. It will keep the picture constant if set to true 
(defaults to false)
- `ace_goggles_effects` allows you to remove the effects on glasses

**Comment by christiandjurberg** [comment]
Hahahahahaha OMG!!! 😂

You guys are the best! :) Thx a lot and thanks for ACE3! :) 👍

Den 7 juni 2017 1:40 fm skrev "PabstMirror" <notifications@github.com>:

**Comment by christiandjurberg** [comment]
In what file is this set?
ace_goggles_showInThirdPerson is client settable. It will keep the picture constant if set to true
(defaults to false)
ace_goggles_effects allows you to remove the effects on glasses

Is it in ace_goggles.pbo ?
ACE_Settings.hpp ?

**Comment by Whigital** [comment]
Esc. -> ACE3 Options.

Check https://ace3mod.com/wiki/framework/settings-framework.html for reference on using the settings framework
