### ISSUE TITLE
Large IEDs (pressure plate) exploding before defuse action is shown

### ISSUE THREAD

**Issue by redbery** [acemod/ACE3#5258]
**Arma 3 Version:** `1.70` (stable)
**CBA Version:** `3.3.1` (stable)
**ACE3 Version:** `3.9.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Large IEDs (both urban and land versions) with pressure plates can currently not be defused. The range in which the explosive is triggered appears to be larger than the range in which the defuse action is shown. Looking at the relevant code leads me to think it is an issue with defuse action being shown in a 1 meter range from the camera (same as for small IEDs) and the explosive trigger going off in a 2 meter range from presumably the player object (opposed to 1 meter for small IED).
- Recommend either increasing the defuse action range for large IEDs or making the large IED ammo use the smaller mineTrigger like the small IEDs

**Steps to reproduce:**
- Spawn a unit with defuse kit
- Spawn either a large IED urban (pressure plate) or large IED land (pressure plate)
- Crawl toward IED slowly while checking if the defuse option is available
- Get blown up before the action is shown
- (optional) Try with small IED to show that it is specifically large IEDs

**Where did the issue occur?**
- Dedicated 
- Editor (Singleplayer)
- Editor (Multiplayer)

**Placed Modules:**
- None

**RPT log file:**
- https://pastebin.com/JAiFjiYu

**Comment by kripto202** [comment]
You could just act like an actual EOD team and blow them up with other explosives

**Comment by 654wak654** [comment]
> You could just act like an actual EOD team and blow them up with other explosives

Solving explosive problems with more explosives since 2015

**Comment by kripto202** [comment]
![maxresdefault](https://user-images.githubusercontent.com/8568526/26899406-03ab091c-4b9d-11e7-9c98-c1b222d61c87.jpg)

**Comment by jonpas** [comment]
We actually have [large plate interaction distance at 1.5m](https://github.com/acemod/ACE3/blob/master/addons/explosives/CfgVehicles.hpp#L67), but it seems [this](https://github.com/acemod/ACE3/blob/98da86b74d4089bc3403d0b0c0074e6a46ce35d8/addons/explosives/functions/fnc_interactEH.sqf#L46-L50) doesn't work for those.
