### ISSUE TITLE
Use lineIntersectsSurfaces instead of lineIntersectsWith

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#5263]
Use `lineIntersectsSurfaces` instead of `lineIntersectsWith` where:
- Is useful (less code / optimization)
- Marked with a `TODO` (mostly first point)
- May be used underwater (LIS works underwater, LIW doesn't)

**Comment by dedmen** [comment]
https://github.com/acemod/ACE3/search?q=lineIntersectsWith&unscoped_q=lineIntersectsWith

**Comment by jonpas** [comment]
This has been implemented where it has been. No point keeping this open for the remaining 4 uses of LIW where this might not even apply.
