### ISSUE TITLE
Unconscious units shouldn't be put in another group

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#527]
Why do wo need this? This really messes things up. 

Team switch breaks, ST_HUD breaks, respawned units are no longer in their group, mission scripts that rely on side or group break. ...

Thoughts?

**Comment by esteldunedain** [comment]
I agree

**Comment by commy2** [comment]
Here is an example of what it does:

http://arma3.swec.se/game/data/7198741

**Comment by PabstMirror** [comment]
I have a similar problem with Become Leader in team managament.  It does a createGroup and moves all units into it.

It always breaks our BFT.

**Comment by commy2** [comment]
I think it's becasue there is no setLeader command.

**Comment by PabstMirror** [comment]
`selectLeader` - But I'm guessing it doesn't work right for some reason and there's a reason you guys created a new group.  But I'll try to look at it,

**Comment by commy2** [comment]
IDK. It was one of the first features in AGM and never reviewed since then.

**Comment by SilentSpike** [comment]
As far as I'm aware `selectLeader` works fine. Also +1 to not putting unconscious in a new group.

The only advantage I can see to doing so is that they won't show up on the player HUD (meaning it pays off to keep track of team members and that you won't instantly know where they went down). However I'm not sure if that validates the functionality problems mentioned in the issue.

**Comment by jaynus** [comment]
The unconcious unit shouldnt be moving groups, period. I don't see a reason for why this is implemented?

**Comment by Glowbal** [comment]
Unconscious units are moved to a seperate group because of AI. They would get stuck otherwise.

**Comment by jaynus** [comment]
AI would get stuck? Can't we just do an isPlayer then?

**Comment by PabstMirror** [comment]
Hmm, saw global's point after commit.  
"So the AI does not get stuck, we are moving the unit to a temp group on its own."

**Comment by Glowbal** [comment]
Yes, and moving the unit back to the original group once woken up. Also if the unit is alone in a group, it won't move the unit into a new group but stick with the original.

**Comment by Glowbal** [comment]
Ideally we would get AI treatment implemented, so they would treat unconscious units. That would solve this issue properly.

**Comment by commy2** [comment]
Will do that `selectLeader` ´stuff in #233

**Comment by PabstMirror** [comment]
@commy2 - I did the become leader stuff in 669dbe10c9afaa6ec641559216d0e894dd85a5f4

The one advantage the old system had was it reordered the member list, with the leader in first.  But something like STHUD is still going to show the leader icon on the right person.

**Comment by commy2** [comment]
thanks. Order doesn't matter in that ui tbh.

(We should kill that ui anyway as a setting or something)

**Comment by PabstMirror** [comment]
Isn't it a difficulty setting?

**Comment by esteldunedain** [comment]
> Isn't it a difficulty setting?

**Comment by commy2** [comment]
It wont go away on our server for the group leader

**Comment by esteldunedain** [comment]
> It wont go away on our server for the group leader

#568

**Comment by commy2** [comment]
Whats the status on this?
@KoffeinFlummi , @Glowbal ?

**Comment by Glowbal** [comment]
Nothing has been done for this on my part. I could make it a setting for the time being, default disabled?

**Comment by commy2** [comment]
>Unconscious units are moved to a seperate group because of AI. They would get stuck otherwise.

Can you elaborate how they get stuck? We never had the issue in AGM and didn't move them out of their group.

**Comment by Glowbal** [comment]
When a unit goes unconscious, the rest of that group will stay near the unconscious unit until he wakes up or dies. This is ok if they have the ability to actually do something about it; but at the moment they do not.

Due to the nature of AI in A3, this became very annoying in some sessions we played.

I agree, it isn't the nicest solution and it should be changed. The quick patch would be the setting for it, default disabled. After that, we got to look into medical treatment abilities for AI. But that will be next release I suppose.

**Comment by commy2** [comment]
So it's only for AI at the moment?

**Comment by esteldunedain** [comment]
Yes, the switching group thing is designed for AI groups; maybe a simple check to disable it if the unit is a player would suffice?

**Comment by Glowbal** [comment]
It is for AI in the group of the unit that goes unconscious.

**Comment by esteldunedain** [comment]
Oh, I didn't know that, corry.

**Comment by commy2** [comment]
That would do it then. I mean we don't have to worry about switching units in this case then. It's only a temporary work around.

**Comment by commy2** [comment]
Close this?

**Comment by Glowbal** [comment]
Leave it open. I will add the setting in medicalFixes and once that is done I will close it.
