### ISSUE TITLE
Battleye sometimes blocking x64.dll

### ISSUE THREAD

**Issue by RogueDGA** [acemod/ACE3#5273]
13/06/2017 11:03:03 AM - Starting BattlEye Service...

13/06/2017 11:03:04 AM - Launching the game...

13/06/2017 11:04:50 AM - BattlEye: Note that file blocks can be ignored if they don't cause problems with the game.

13/06/2017 11:04:50 AM - Blocked loading of file 'B:\Program Files (x86)\Steam\steamapps\workshop\content\107410\463939057\ace_advanced_ballistics_x64.dll'

It happens intermittently and with different .dll files, just thought I should report it, let me know if you need any more info.

**Comment by PabstMirror** [comment]
Was this 3.9.2 or 3.10 rc?

**Comment by RogueDGA** [comment]
This is 3.9.2 sorry I should have posted the version

**Comment by dedmen** [comment]
Was a widespread issue. Just battleye messing around again. Also affected TFAR and others.

**Comment by dedmen** [comment]
Seems to still be an issue for a few people. But it seems to be very limited. I got messaged by only half a dozen of several ten thousand users about that.
