### ISSUE TITLE
Arma crashes when ACE3 can't connect to ace3mod.com

### ISSUE THREAD

**Issue by TheLexoPlexx** [acemod/ACE3#5281]
**Arma 3 Version:** `1.70.141838`
**CBA Version:** `3.3.1`
**ACE3 Version:** `3.9.2`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Arma crashes on startup when `ace3mod.com` is blocked.

**Steps to reproduce:**
- block ace3mod.com in your hosts-files or firewall or whatever you like
- start Arma

**Where did the issue occur?**
- Starting Arma

**RPT log file:**
- ([RPT Log](https://gist.github.com/TheLexoPlexx/e31122808968579c440f52e1b3d9a7ae) or [pastebin]

**Comment by PabstMirror** [comment]
It just paused for a second when I tried, but it might work differently on other systems.
The core issue is more of a BIS problem (lockup on `htmlLoad`)
ACE has a setting, but obviously it's hard to set if game is crashing :smile: 

What you could do is start up a vanilla arma (no ace in modset)
open editor and run
```
profileNamespace setVariable ["ace_optionsmenu_showNewsOnMainMenu", false];
saveProfileNamespace
```

then start game up normally (with ace) and let us know if it's working.

**Comment by TheLexoPlexx** [comment]
And adding a check if ace3mod is not available and then setting that option to false on first startup?

**Comment by TheLexoPlexx** [comment]
Also, the above solution worked!

**Comment by PabstMirror** [comment]
`htmlLoad` should fail safe and I couldn't reproduce the lockup. 
If url is blocked it just didn't load but also didn't crash.

I believe the base game and TFAR both use this same method, so it might just be a weird edge case here?

**Comment by dedmen** [comment]
TFAR doesn't. And I think base game doesn't anymore since the new Main Menu.
But it's still a BI issue.
