### ISSUE TITLE
Implementing a custom rank system

### ISSUE THREAD

**Issue by chris579** [acemod/ACE3#5286]
**Description:**
- Currently it's possible to override the default rank icons via `ace_nametags_fnc_setFactionRankIcons`
- Problem: a lot of milsim clans have more than 7 ranks, the amount differs between 7 and 20
- Solution: implement an own rank system
    - Ranks would be set as a var on the unit's object
    - Nametags would be compatible by checking the custom rank along with a custom icon set by `ace_nametags_fnc_setFactionRankIcons`
    - This system could be used for different other purposes too

Generally I would like to ask whether such a system is desired. If so, I would like to implement it and create a pull request for it.

**Comment by Drofseh** [comment]
I'd love a system that allowed rank to be set independent of the vanilla rank.

I find that setting the vanilla rank in the editor tends to change the order the slots appear in the mission lobby, so these days I just set everyone except the group leader to private.

**Comment by kripto202** [comment]
If you want to make a feature request please put it in the feature request post #3594

**Comment by chris579** [comment]
Sorry my fault. Just noticed that after I posted the issue
