### ISSUE TITLE
Explosive fragmentation penetrating bunker walls

### ISSUE THREAD

**Issue by SlappyMoose** [acemod/ACE3#5288]
**Arma 3 Version:** `1.70` (stable)
**CBA Version:** `3.3` (stable)
**ACE3 Version:** `3.9.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS Weapons
- CUP Weapons
```

**Description:**
- Hand grenade explosions from inside sandbag bunkers (notably the Large Bunker) appear to kill people outside those bunkers, apparently via fragmentation.
- The effect seems to be most pronounced with the RHS mod M67 grenade. Other grenades, such as the CUP Mod L109A2, also have this issue, but perhaps to a lesser extent (thorough testing required). RHS Mod F-1 and RGD5 grenades, 
- Issue could be caused by the Large Bunker's (lack of) interior wall density.

**Steps to reproduce:**
- Throw an M67 (or any) grenade inside a Large Bunker, and stand/crouch/lay outside within ~20 meters. There is a high chance you will be injured, or killed.
- Screenshot album of the issue: http://imgur.com/a/L5qrz
- Video of the issue, as seen with fragmentation tracking: https://gfycat.com/JovialSpeedyBull

**Where did the issue occur?**
- Multiplayer / Virtual Arsenal

**Comment by kripto202** [comment]
those bunkers aren't impenetrable, https://youtu.be/cix07R1vlhI?t=10m40s talks about how bullet penetration works. Things like 7.62 and up, if close enough, will penetrate the bunker. So by the looks of the grenade, the shrapnel is as equivalent as a 7.62 or up penetrating the bunker.

**Comment by Stritt57** [comment]
If we're being honest... those sandbag walls should stop both the grenade shrapnel and 7.62x51NATO rounds. 
In the real world it only takes 2 sandbags thick to stop a .50cal, and a single bag can easily stop rounds 7.62x51NATO.
You can find countless videos of them stopping those rounds online.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
