### ISSUE TITLE
Toggle to change interaction menu style - Feature Request (can't set the label)

### ISSUE THREAD

**Issue by TheNick5527** [acemod/ACE3#529]
The 3D interaction menu is nice aesthetically, but it can be fidgety on someone who isn't prone, in the surrendered stance, standing without a weapon in their hands. Overlays become to close to other options, leading me to bandage a perfectly fine leg when I'm intending to bandage a bleeding arm.

It would be nice to have a flat, non-dynamic interaction menu to toggle to in regards to this. Something clean, that isn't going to move my aim around if I'm trying to pay attention to a certain area while bandaging myself or someone else, and that I can close by pressing Esc in the event I suddenly have to start shooting. Perhaps an option to use a modified version of the base CSE menu?

**Comment by jaynus** [comment]
Please post this in the correct feature request master issue.

http://acemod.github.io/ACE3/wiki/user/how-to-make-a-feature-request.html
