### ISSUE TITLE
Atropine Raises HR, doesn't lower.

### ISSUE THREAD

**Issue by RagingGamer** [acemod/ACE3#5293]
Under the medical system, the table under heading 2.2.1.12 states atropine lowers the HR. It actually raises it

**Comment by Drofseh** [comment]
https://github.com/acemod/ACE3/blob/master/addons/medical/ACE_Medical_Treatments.hpp#L1290

Looks like it should be lowering it.

**Comment by RagingGamer** [comment]
Well that's another issue then, too. Unless they're deliberately ignoring how medicine works IRL,

**Comment by commy2** [comment]
So the wiki is correct.

**Comment by Drofseh** [comment]
Wiki correctly reflects the code, but apparently IRL atropine raises HR.

"Atropine is a medication used to treat certain types of nerve agent and pesticide poisonings, some types of slow heart rate..."

**Comment by bux** [comment]
remove atropine?

**Comment by noKid** [comment]
At very low doses, Atropine is lowering HR.
Higher doses indeed raise HR.
In a military context, Atropine is usually used against nerve agents like gas, and therefore increase HR.
It should be corrected then.

**Comment by Robdemi** [comment]
![atropine](https://user-images.githubusercontent.com/19828557/27814037-f48e92ae-6047-11e7-9f4a-1ab843f3cb66.png)

There is a problem with one of the drugs in Ace_Medical
Atropine
Atropine IRL Increases cardiac output. Currently in the mod it looks like Atropine lowers the HR. It looks like it lowers B/P marginally but not really significant.
The pharmacology of Atropine is that it inhibits action of acetylcholine at parasympathetic sites in smooth muscle, meaning GI tract and respiratory muscles to put in short. It also increases cardiac output meaning it increases heart rate of the heart and dries secretions.

I don't know why the current version of ace still has Atropine to decrease HR. It doesn't make sense.

Picture Reference - Medscape

**Comment by Robdemi** [comment]
Please do NOT remove atropine.

**Comment by Garzog** [comment]
Why should they not remove atropine? Atropine IRL simply is used for something else, so why leave it in?
As a RL medic i can tell you that we are using lopresor or brevibloc. I don't know if that is the stuff they use in the military aswell, but at least it's realistic

**Comment by Robdemi** [comment]
Brevibloc and lopressor are both beta-blockers and are for anti-dysrethmia drugs. At least Brevibloc is. I believe you may have mixed up adenosine and atropine mixed up. Also we use HI-6 which is a combination of atropine and diazapam.

**Comment by Robdemi** [comment]
However Atropine by itself does speed up the heart

**Comment by Garzog** [comment]
Maybe you missunderstood me, i ment we are using lopresor and brevibloc to lower the HR. And since unintended tachykardie is a dysrethmia, they are applying. Or am i mxing something completly up?

**Comment by Robdemi** [comment]
Adenosine is used for things like A-fibb and supra ventricular tachycardia. It is used instead of cardioversion.

**Comment by Robdemi** [comment]
So I think you are mixing up your drugs

**Comment by Garzog** [comment]
Maybe there is an other platform then this to discuss these things.
But the a tachycardia is a dysrethmia, which in civilian life in germany we treat these with one of the two, or as you mentioned, with adenosine or a cardioversion if the medication doesn't help.
And according to my information at least lopresor is also usable on a reentry tachycardia.

**Comment by Robdemi** [comment]
For a rebound tachycardia? Not sure. But this is to be discussed somewhere else. Usually if a person goes back into tachycardia there is a different problem that is causing the issue. Happens with older people more. Like torsades/a-fibb if they get sick. It's a common thing for geriatrics. I can find out more info once I get home after my tasking but this has to be discussed somewhere else and not in this chat. But please do leave atropine in the mod. Just values need to be changed to increase HR rather than lower them.

**Comment by bux** [comment]
@Garzog @Robdemi feel free to join our chat at https://slackin.ace3mod.com/

**Comment by Robdemi** [comment]
Will do just can't commit to anything until my tasking is done.

**Comment by Robdemi** [comment]
@bux  I was not able to access the slack.

**Comment by bux** [comment]
@Robdemi it's an invite page where you should be able to enter your email address and get an invite to connect to the slack workspace. If it doesn't work for you feel free to send me an email containing your address and i will invite you myself.

**Comment by Robdemi** [comment]
@bux I have sent you an email containing my email address.

**Comment by Robdemi** [comment]
If people still have a hard time with this then please refer to this link [https://acls-algorithms.com/bradycardia/](url)

**Comment by kotaco** [comment]
This has often annoyed me about ACE medical in general (inaccurate treatment algorithms) and I decided to look and see if it was reported by others as well. 

As a Paramedic and Emergency Depart RN with TEMS and Critical Care Transport experience I felt I could provide some insight. 

Atropine is indeed used for symptomatic bradycardia. Meaning a heart rate <60 with hemodynamic compromise (Altered mental status, crappy vitals, clammy skin, etc). The recommended dose by the AHA is 0.5mg, but in practice we usually just give an amp (1mg prefilled syringe) which you can repeat 3 times to a total of 3mg. After that the treatment becomes transcutaneous pacing and/or an infusion of a chronotropic agent like Dopamine or Epinephrine.  This is strictly for problems of cardiac origin.

For trauma and massive bleeding leading to hypovolemic shock, a more appropriate drug would be push-dose epinephrine. Not only does epi raise the heart rate, but it also is a vasoconstrictor which will hopefully raise BP and cause vessels to constrict to (in a perfect world) lessen bleeding. 

Atropine is also used for organophosphate poisoning (like sarin) which cause a set of symptoms often called "SLUDGEM" (Salivation, Lacrimation, Urination, Diarrhea, GI distress, Emesis, Miosis). Atropine is an anticholinergic so it drys you up. However, this requires an extremely large dose you'll only find in specifically designed kits for personal use and treatment centers. You're standard medic doesn't carry this for everybody, in combat zones where sarin is a concern, soldiers are often assigned their own personal single-dose kits which are good for evacuation to a place where they can receive further treatment. 

Somebody had also mentioned Adenosine for A-Fib. That's only partially correct. Adenosine is used to "stop" the heart and allow it to reset into a normal sinus rhythm. It is used for a very specific kind of tachycardia called SVT in which the heart rate is > 150 bpm, narrow and regular. A-Fib with RVR and A-Flutter may mimic SVT but won't convert with Adenosine, Adenosine may slow the rate down enough to identify A-Fib/A-Flutter and allow us to switch to something like Cardizem or Digoxin to correct that properly.

**Comment by dedmen** [comment]
This is on the todo list for medical rewrite. Don't close this.

**Comment by SilentSpike** [comment]
Closing, we're removing this drug anyway in rewrite.
