### ISSUE TITLE
Request: Make it so that the Pardon system can be disabled

### ISSUE THREAD

**Issue by BlueNexus** [acemod/ACE3#5296]
Not a bug report, so I'm not following the normal template.

Being unable to turn off the pardon system has some serious downsides, for us. If you accidentally shoot someone in the dark, and you need to evac in an emergency, you can't get in the evac chopper until someone gets out and pardons you, by which time it could be too late.

tl;dr let us toggle the pardon system on or off.

**Comment by jonpas** [comment]
That's not what "Pardon" is for. What you are talking about is Arma's system, we simply add "Pardon" interaction as a workaround.

**Comment by PabstMirror** [comment]
If you want to remove the problem from vanilla you could add this to a mission's description.ext:
```
class Extended_InitPost_EventHandlers {
  class CAManBase {
    class FixFriendlyFire { init = "if (local (_this select 0)) then {(_this select 0) addRating 100000;};";};
  };
};
```

**Comment by commy2** [comment]
What jonpas said. And Pabst wrote a nice way to disable this vanilla system.
