### ISSUE TITLE
AH-9 Pawnee HUD Missing

### ISSUE THREAD

**Issue by bagellord** [acemod/ACE3#5299]
**Arma 3 Version:** `1.7.0` (stable)
**CBA Version:** `3.3.1` (stable)
**ACE3 Version:** `3.10.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The HUD that is supposed to be present as part of the Aircraft feature/PBO (helmet HUD, according to Slack) is missing

**Steps to reproduce:**
- Launch Arma 3, go into the game, and get into an AH-9 (little bird) - there will be no HUD

http://steamcommunity.com/sharedfiles/filedetails/?id=952214482

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer (Editor)

**Placed Modules:**
- None

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by PabstMirror** [comment]
As far as I can tell it was never in ace.
So just remove feature from wiki?

**Comment by jonpas** [comment]
I remember it being in ACE3. 🤔

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/commits/master/addons/aircraft/CfgVehicles.hpp
I think we only ever touched the Comanche mfd

**Comment by bagellord** [comment]
Strange that it's on the wiki, planned feature that got missed?

**Comment by bux** [comment]
There was definitly a HUD.

**Comment by MrFies** [comment]
please fix that ASAP !!!

**Comment by kripto202** [comment]
noticed Heli_light_01armed_base_F and heli_attack_01_base_F don't have showHMD = 1; that could be the problem in https://github.com/acemod/ACE3/blob/master/addons/aircraft/CfgVehicles.hpp

**Comment by kripto202** [comment]
@jonpas do you know which build had the hud?

**Comment by jonpas** [comment]
I am not sure.

**Comment by kripto202** [comment]
might just take the config of a heli that already has a hud and just copy and paste the code there.

**Comment by PabstMirror** [comment]
I'll tag #3594 feature requests if someone wants to tackle this,
but especially after pylon update huds are pretty complex and I'm not sure if this is something we would get to
