### ISSUE TITLE
Hellfire UI not working with UAVs

### ISSUE THREAD

**Issue by AceCorba** [acemod/ACE3#5301]
**Arma 3 Version:** Latest as of 22 Jun 17
**CBA Version:** Latest as of 22 Jun 17
**ACE3 Version:** Latest as of 22 Jun 17

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
1- Whilst using a UAV, there is no option to select the mode (LOBL/LOAL-H/LOAL-D/LOAL-L) or change the laser code. 
2- If you are sitting in an aircraft with a Hellfire pylon and using the UAV terminal, you can select different modes and codes however this affects the vehicle you sit in rather than the UAV.

**Steps to reproduce:**
1- Fly a UAV with Hellfires attached.
2 - Sit in an aircraft with hellfires attached then fly a UAV with hellfires attached.

**Where did the issue occur?**
- Editor (singleplayer)

**Placed Modules:**
- Zeus (Gamemaster)

**RPT log file:**
- Not present

**Comment by Snak3Doc** [comment]
can confirm this effects remote control laser designators and darters drones as well
