### ISSUE TITLE
Rearming: Don't work in dedicated MP, but in SP / local MP

### ISSUE THREAD

**Issue by Wyqer** [acemod/ACE3#5302]
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.3.1` (stable)
**ACE3 Version:** `3.10.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- BWMod
- RHS AFRF
- RHS USAF
- BWMod ACE Compat
- RHS AFRF ACE Compat
- RHS USAF ACE Compat
- ace_server
```

**Description:**
Rearming of vehicles won't work on a server at the moment. It work's well in SP (or local MP) with same mods, mission and serverconfig.hpp. Tried it with `ace_rearm_level` 2 and 0.

First I thought it could be an issue due to the locality of the vehicles but even after getting in as driver on the rearm truck and the "to be rearmed" vehicle, to ensure they're local to my machine, it won't apply.

I can take the rocket or ammo crate from the truck and also have the action to ream at the empty vehicle. But after the progress bar hit the end there's no hint and no rearming happened. Even with `ace_ream_level` 0 there comes the interaction on the truck and the progress bar starts, but no rearming happening at the end.

In a local MP from the editor or LAN it works without issues and as intended.

**Steps to reproduce:**
* Get a vehicle without ammo or partially ammo count
* Drive ammo truck near and start the rearming action via interaction menu
* Wait for the progress bar to finish
* Vehicle isn't rearmed at all

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None (using serverconfig.hpp with ace_server.pbo)

**RPT log file:**
No errors at the log.

serverconfig.hpp:
https://github.com/Wyqer/kp_liberation/blob/master/userconfig/ace/serverconfig.hpp

**Comment by LeiserGeist** [comment]
Same issue, same mods & everything, but there are errors in my log
https://gist.github.com/LeiserGeist/6caf433928bff947b7bbb6c30503efb0

I've tried it on two physical servers, same problem. The errors don't appear in SP or local MP.
