### ISSUE TITLE
Player > AI Killtracker.

### ISSUE THREAD

**Issue by 123B3n** [acemod/ACE3#5303]
**Arma 3 Version:** `1.72` (stable / rc / dev)
**CBA Version:** `3.3.1` (stable / dev + commit hash)
**ACE3 Version:** `3.10.1` stable /
**ACEX Version:** `3.10.1` stable /

**Mods:**
```
- CBA_A3
- ace
- acex
- alive
```

**Description:**
- Trying to track AI kills by player, just downloaded ACEX and made the config for the killtracker however still not tracking the kills. I need a way to track the kills with the advanced medicial system activated. Not sure if I missed something from ACEX, however I did exactly what the readme stated and yet nothng happens. I don't need anything special, I just need a simple way saying that this player killed 32 for example, not who, or anything fancy. Hopefully someone here knows a way to track them or knows what I've done wrong from the ACEX. I'm greatfull for any help I'll get!

**Steps to reproduce:**
- Spawn in, spawn an AI with zeus and shoot it, check the statistics board and see if you got any kills.

**Where did the issue occur?**
- Dedicated / Multiplayer

**Placed Modules:**
- 'None'

**RPT log file:**
No errors at the log.

**Comment by AACO** [comment]
Currently ACEX kill tracker only stores the kills/deaths in an array (`acex_killTracker_outputText `) which you can configure your missions to show on end (high the right arrow a few times on the end mission screen with the [added debriefing segment](https://github.com/acemod/ACEX/blob/master/addons/killtracker/README.md)). You could try to extend the kill tracker functionality by adding [addPlayerScores](https://community.bistudio.com/wiki/addPlayerScores) calls, but as the system isn't perfect I don't know if that should be the main stream behaivor.

**Comment by 123B3n** [comment]
I did this and it kinda worked when I tested it but now it no longer works. Anyone know why it doesn't always track kills from when I kill AIs?

`["CAManBase", "Killed", {
  params ["_unit", ["_killer", objNull]]; // "Killed" Event Handler
  if ((isNull _killer) || {_killer == _unit}) then {
    private _aceSource = _unit getVariable ["ace_medical_lastDamageSource", objNull];
    if ((!isNull _aceSource) && {_aceSource != _unit}) then {
        _killer = _aceSource;
        kills = kills + 1;
        };
    };
  };
}] call CBA_fnc_addClassEventHandler;`

**Comment by PabstMirror** [comment]
Take a look at https://github.com/acemod/ACEX/blob/master/addons/killtracker/XEH_postInit.sqf

`ace_medical_lastDamageSource` is only set where unit is local, so you will need to determin killer where unit is local as well and then pass that info back to the client that did the shooting

**Comment by 123B3n** [comment]
I'm not 100% sure I understood that, I mean I understood the local part but how would I determine who the killer was from an AI and then send it back to the killer so that his score could be tracked.

I mean I might understand it a bit better if I understood what `_unit getVariable ["ace_medical_lastDamageSource", objNull];` did return as well as what objNull argument were for.

Because right now that event handler is running on the client itself and not like we say `InitServer.sqf`.
If it would return the lastDamageSource as player wouldn't I just be able to confirm that with an if statment like `if (_killer == player) then {` etc and do a call to the player to store their score. I'm kinda lost to be honest.

Maybe you could share some lights for me, not asking for some one to give me a fully working code or anything like that. But preferable some what how to get it to work. I've gone over the killtracker in ACEX since I first attempted this, but never really understood all of the code besides the first part some what. So I went for that one and tested it out, however, only tested it with myself on the server and it worked fine till today when I tried it with a couple of friends.

**Comment by 123B3n** [comment]
I resolved it, thanks for all the help!
