### ISSUE TITLE
Bandages Field Dressing, QuikClot, missmatch since several month...

### ISSUE THREAD

**Issue by sam11hamilton** [acemod/ACE3#5311]
Hi everybody, (and sorry for my bad english)

I really like... love! ACE 3 a big tks to all's Dev for this project. But since several month now, all gamers who use ACE 3 advanced medical, came crazy... The Tuto of ACE 3 advanced Medical are really poor and not correct...
![](https://ace3mod.com/img/wiki/feature/medical1.jpg)
On this Table we can see "field dressing" "packing" "elastic" "quikclot" But in game we dont have packing, and "field dressing" and "quikclot" as the same bandage. So ? How to know who to use them?  

The same problem since a year or more:

**## Autoinjector 	Effect**
Morphine 	Decreases the blood viscosity, suppress pain
Epinephrine 	Raises the heart rate of the patient
**Adenosine 	Lowers the heart rate
Atropine 	        Lowers the heart rate of the patient**

Why we have to injector for the same use?

Iam not the only one to saw this missmatch I suppose. Somebody can help us? 
I hope the dev's will change this problem in the future to cause its a really disapointed problem.

With all my gratitude,

Best Regards,

Hamilton

**Comment by BaerMitUmlaut** [comment]
>But in game we dont have packing, and "field dressing" and "quikclot" as the same bandage.

You're using basic medical, this table is for advanced medical. Bandages are all the same in advanced medical.

Adenosine and atropine both exist to keep backwards compatibility. The effects of adenosine are discussed in other issues already.
