### ISSUE TITLE
Taru Cargo Pod can neither be loaded nor can one load boxes into them.

### ISSUE THREAD

**Issue by xrufix** [acemod/ACE3#5313]
**Arma 3 Version:** `1.72`
**CBA Version:** `3.3.1.170504`
**ACE3 Version:** `3.10.0` (also in earlier versions)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- One can not load ammoboxes etc. into Taru Cargo Pods albeit they have cargo space (20 by default).
- Taru Cargo Pods have the Cargo Space attribute in Eden and it's set to 2 as default. Should probably be much higher or not even possible at all.

**Steps to reproduce:**
- Place Taru Cargo Pod and ammobox or other loadable object in Editor.
- Try to load it. There is no "load" action shown in interaction menu.

**Where did the issue occur?**
- Singleplayer, self hosted multiplayer

**Placed Modules:**
- None

**Comment by xrufix** [comment]
Test setup (Only ACE3 + CBA loaded):
![2017 06 26-15 53](https://user-images.githubusercontent.com/29610495/27542585-f87f2ab0-5a87-11e7-8af1-b8a275519210.png)

Huron containers don't have ACE-Cargospace by default. I added one in 3den Attributes. Shows up as expected:
![2017 06 26-15 53_01](https://user-images.githubusercontent.com/29610495/27542583-f871503e-5a87-11e7-83d5-fe70e08304c3.png)
Taru has a cargo space of 20 by default, can be opened:
![2017 06 26-15 53_02](https://user-images.githubusercontent.com/29610495/27542584-f874f8c4-5a87-11e7-9dc9-5ad444064064.png)

Here's the problem: The box in the middle can neither be loaded in the Huron container nor in the Taru pod (no action shows up):
![action](https://user-images.githubusercontent.com/29610495/27542586-f884a6ac-5a87-11e7-84dc-9a24d1927a21.png)

**Comment by PabstMirror** [comment]
Loading of objects into pods will be fixed in next ace version - see #5274
I will have a PR to add proper cargo to huron containers (github is having problems now)
