### ISSUE TITLE
Only carry option for chairs, no sitting

### ISSUE THREAD

**Issue by JinougaF** [acemod/ACE3#5314]
Had ace3 and acex both installed, cant sit on chairs, not sit down option
http://i.imgur.com/R98pz43.jpg

**Comment by jonpas** [comment]
Did you enable it?

**Comment by JinougaF** [comment]
how to enable it? I didnt find the option

**Comment by jonpas** [comment]
https://ace3mod.com/wiki/framework/settings-framework.html

**Comment by PabstMirror** [comment]
There should also be a setting module you can place under acex
If you are still having problems open the ace seting menu, hit the debug to rpt button and then post your rpt.

**Comment by PabstMirror** [comment]
Let us know if it still isn't working after enabling the setting.
