### ISSUE TITLE
No maps work after ACE Update (Cargo var type)

### ISSUE THREAD

**Issue by SEALTeam10** [acemod/ACE3#5317]
None of our units maps work after the update and we get this error.  

http://imgur.com/a/s4WK8

We believe the issue is related to the green ammo crates as they appear to be the only objects that cause this issue.  Any ideas?

**Comment by PabstMirror** [comment]
Probably related to PR #5306

**Comment by SEALTeam10** [comment]
Any idea when there will be a fix for this?
