### ISSUE TITLE
Bug TiTan LOCK 

### ISSUE THREAD

**Issue by thirald** [acemod/ACE3#5319]
**Arma 3 Version:** `1.70` (stable)
**CBA Version:** `3.4.0` (stable / dev + commit hash)
**ACE3 Version:** `3.10.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Hello, I noticed that since the update ACE 64 bit, one can no longer use the Titan AC and AA to date with the latest version Ace 3.10.1 impossible to lock an air or terrestrial vehicle

As you could see the screenshot with Ace 3.10.1:

http://image.noelshack.com/fichiers/2017/26/4/1498743114-20170629145557-1.jpg

And without the Ace 3.10.1:

http://image.noelshack.com/fichiers/2017/26/4/1498743114-20170629114504-1.jpg

For the record, I'm not the only one has encountered the problem since passing 64 bit with ACE that's why, I'm updating the information for this bug

Thank you

**Comment by bux** [comment]
Current Arma 3 version is 1.72
You didn't supply an RPT file.

**Comment by AACO** [comment]
@thirald While aiming down the sights with the Titan compact, can you hit `n` to change the vision mode to thermals, and then hold `tab`while the target is centered on your screen. This should create a tracking tone and bracket the target. Once the target is locked it should be able to fire/track.

**Comment by thirald** [comment]
Ahhh Super Thanks @AACo This totally changes the vanilla version thanks
of your help
