### ISSUE TITLE
Strange "overflow" issue

### ISSUE THREAD

**Issue by rlex** [acemod/ACE3#532]
Not sure what mod is causing it, but i disabled ACE on one session and was able to play 2h, while with ace it "crashes" after 20-30 mins. We also played same mission with same modpack (but with AGM) and haven't experienced such issues.

I'm not even sure what happening - server is working, eating CPU as usual, but i'm not able to kill units/transport/etc and AI stops working.

Also, one time that happened when ALiVE spawned 2 AAF helis (wildcat unarmed) and they collided. Right after collide they got "frozen", as well as all units, same way as crash from that RPT, with same "overflow" log line. Might be just coincidence but still

Here is example RPT file: https://gist.github.com/rlex/7c5759946c450aec66f6

Crash happened right after that "overflow".

I'll fill proper bugreport a bit later, still digging around and going to sleep now, so this is more like a reminder...

**Comment by jaynus** [comment]
"Overflow" is caused by bad Physx objects, and most likely one of your other mods has bad Geometry LOD's; as this is what causes that error.

We have no objects to have Geometry overflow issues with.

I would investigate the stability of your models in your modpack.

**Comment by rlex** [comment]
But that mission only uses stock AAF units

**Comment by rlex** [comment]
Seems to be caused by RHS + ACE. Well since RHS is broken right now, i'll just wait for update and report problems if i find any..

**Comment by bux578** [comment]
Exactly why we put:

>If you've found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using only @cba_a3 and @ACE3 on a newly created mission.

http://acemod.github.io/ACE3/wiki/user/how-to-report-an-issue.html
