### ISSUE TITLE
Request to create rearm ammo boxes to store them somewhere

### ISSUE THREAD

**Issue by Mezilsa** [acemod/ACE3#5321]
**Arma 3 Version:** `1.72` (stable / rc / dev)
**CBA Version:** `3.3.1` (stable / dev + commit hash)
**ACE3 Version:** `3.10` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- You know it can be quite bothersome to handle a defense szenario and then to carry the whole HMG arround the whole base to the ammo truck instead of carrying the ammo to the hmg.

So my request would be, that you can either create or modify chests to be handeld as those ammunition boxes.

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/pull/4701

**Comment by PabstMirror** [comment]
Will track this on #3594
