### ISSUE TITLE
Self-interaction menu doesn't work since somewhere near CBA update

### ISSUE THREAD

**Issue by maximemoring** [acemod/ACE3#5323]
**Arma 3 Version:** `1.72.142223` stable
**CBA Version:** `3.4` stable
**ACE3 Version:** `3.10.1` stable

**Active Mods:**
```
- CBA_A3
- ace
- Tried with and without Overthrow
```

**Description:**
I only get a red circle when using the self-interaction menu. Has been working and was working up until sometime near the latest CBA update. I've been trying to play since yesterday and had played after the new map and Overthrow update successfully. I've tried reinstalling the mods, and eventually reinstalling Arma 3 while rebooting and trying with and without Overthrow in between each action. I originally had a several other mods (such as RHS's with the compatibility mods) and everything was working, I disabled them after this started happening. 

**Steps to reproduce:**
Open self-interaction menu. I cannot give any more detail as no other mod than the necessary is active.

**Where did the issue occur?**
Everywhere (Multi and Singleplayer)

**Placed Modules:**
A single soldier to take control of and try the self-interaction.
Also tried on Overthrow. I also tried on multiple maps.

**RPT log file:**
https://pastebin.com/wTJAqqDA
Ace Debug : https://pastebin.com/1W8qG4C9

**Error looking lines:**
```
7:30:43 Cannot update non class from class a3\ui_f\config.bin/RscCallSupport/Items/
7:30:43 Cannot update non class from class a3\ui_f\config.bin/RscRadio/Items/
[...]
7:30:58 [XEH]: ACE_Module does not support Extended Event Handlers! Addon: @ace
7:30:59 SimulWeather - Cloud Renderer - noise texture file is not specified!
7:31:04 Global namespace not passed during: _this call ace_common_fnc_handleEngine;
7:31:04 Error in expression <_this call ace_common_fnc_handleEngine;>
7:31:04   Error position: <ace_common_fnc_handleEngine;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_common_fnc_statusEffect_localEH;
7:31:04 Error in expression <_this call ace_common_fnc_statusEffect_localEH;>
7:31:04   Error position: <ace_common_fnc_statusEffect_localEH;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_interact_menu_fnc_compileMenu;_this call ace_interact_menu_fnc_compileMenuSelfAction;
7:31:04 Error in expression <_this call ace_interact_menu_fnc_compileMenu;_this >
7:31:04   Error position: <ace_interact_menu_fnc_compileMenu;_this >
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_common_fnc_restoreVariablesJIP;
7:31:04 Error in expression <_this call ace_common_fnc_restoreVariablesJIP;>
7:31:04   Error position: <ace_common_fnc_restoreVariablesJIP;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_common_fnc_setName;
7:31:04 Error in expression <_this call ace_common_fnc_setName;>
7:31:04   Error position: <ace_common_fnc_setName;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_common_fnc_resetAllDefaults;
7:31:04 Error in expression <_this call ace_common_fnc_resetAllDefaults;>
7:31:04   Error position: <ace_common_fnc_resetAllDefaults;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_common_fnc_statusEffect_respawnEH;
7:31:04 Error in expression <_this call ace_common_fnc_statusEffect_respawnEH;>
7:31:04   Error position: <ace_common_fnc_statusEffect_respawnEH;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_common_fnc_firedEH;
7:31:04 Error in expression <_this call ace_common_fnc_firedEH;>
7:31:04   Error position: <ace_common_fnc_firedEH;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_missileguidance_fnc_onFired;
7:31:04 Error in expression <_this call ace_missileguidance_fnc_onFired;>
7:31:04   Error position: <ace_missileguidance_fnc_onFired;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_missileguidance_fnc_onIncomingMissile;
7:31:04 Error in expression <_this call ace_missileguidance_fnc_onIncomingMissil>
7:31:04   Error position: <ace_missileguidance_fnc_onIncomingMissil>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_attach_fnc_handleGetOut;
7:31:04 Error in expression <_this call ace_attach_fnc_handleGetOut;>
7:31:04   Error position: <ace_attach_fnc_handleGetOut;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_captives_fnc_handleGetOut;
7:31:04 Error in expression <_this call ace_captives_fnc_handleGetOut;>
7:31:04   Error position: <ace_captives_fnc_handleGetOut;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_attach_fnc_handleGetIn;
7:31:04 Error in expression <_this call ace_attach_fnc_handleGetIn;>
7:31:04   Error position: <ace_attach_fnc_handleGetIn;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_captives_fnc_handleGetIn;
7:31:04 Error in expression <_this call ace_captives_fnc_handleGetIn;>
7:31:04   Error position: <ace_captives_fnc_handleGetIn;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: _this call ace_attach_fnc_handleKilled;
7:31:04 Error in expression <_this call ace_attach_fnc_handleKilled;>
7:31:04   Error position: <ace_attach_fnc_handleKilled;>
7:31:04   Error Local variable in global space
7:31:04 Global namespace not passed during: call ace_cargo_fnc_handleDestroyed;
7:31:04 Error in expression <call ace_cargo_fnc_handleDestroyed;>
7:31:04   Error position: <call ace_cargo_fnc_handleDestroyed;>
7:31:04   Error Local variable in global space
[...]
7:31:19 [XEH]: One or more children of class All do not support Extended Event Handlers. Fall back to loop.
```

Also please don't suggest that I install the mods without the workshop+launcher. Without it, I wouldn't be using mods.

**Comment by bux** [comment]
That's not the RPT file.

**Comment by maximemoring** [comment]
Oh, whoops, there it is : https://pastebin.com/wTJAqqDA

**Comment by jonpas** [comment]
```
 7:31:04 Global namespace not passed during: _this call ace_common_fnc_handleEngine;
 7:31:04 Error in expression <_this call ace_common_fnc_handleEngine;>
 7:31:04   Error position: <ace_common_fnc_handleEngine;>
 7:31:04   Error Local variable in global space
```

**Comment by PabstMirror** [comment]
I'm honestly not sure what the problem is on this, 

`Global namespace not passed during` seems to be related to mod.cpp issues 
and nothing I've read seems relevant for how it would be related to XEH errors.

- Verify ArmA in steam (https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335)
- Repair CBA and ACE in the ArmA Launcher (under mods open up CBA then hit the 3 dots button, then repair)
(CBA may have had issues with first workshop upload, so this might be the cause)
- Run the game, open up the editor, hit Ctrl+D to open debug console and paste this into one of the 4 boxes at the bottom:
`getText (configFile >> "Extended_Engine_EventHandlers" >> "All" >> "ace_common")`
and then let us know what it reuturns in the box below

**Comment by JustVincentHMN** [comment]
Sorry to butt-in, got the same problem and did `getText (configFile >> "Extended_Engine_EventHandlers" >> "All" >> "ace_common")` and the result was this 
`"_this call ace_common_fnc_handleEngine"`

**Comment by maximemoring** [comment]
I already did repair both mods and Arma 3 and unfortunately, it didn't work.
In both cases from inside the editor and from inside the game generated by the editor : "_this call ace_common_fnc_handleEngine"
I'm thinking it knows which call to do but the call itself wasn't given the global namespace.

**Comment by PabstMirror** [comment]
It might be worth a shot to try starting the game with a different profile
Start the game, make a new profile and then restart

**Comment by GringoMcGee** [comment]
I've had the same issue and been following this thread for a couple of days. 
Seeing as how it hasn't been updated, I wasn't sure if i should make a new a ticket.

I've tried all of the recommendations listed above short of reinstalling arma 3, nothing's worked so far.
using the latest versions of everything,
mods are workshop versions.
(im not sure how to get the debug info)

typed getText (configFile >> "Extended_Engine_EventHandlers" >> "All" >> "ace_common") into the box,
got "_this call ace_common_fnc_handleEngine" in response (same as above)

RPT file here: https://pastebin.com/WP0xG8QR

**Comment by maximemoring** [comment]
Creating a new profile works!

**Comment by PabstMirror** [comment]
I'm still baffled as to what the error `Global namespace not passed during` means in our context
Or why changing profiles worked.

But glad to hear it's fixed

**Comment by JustVincentHMN** [comment]
I went to Overthrow Discord and they told me not to use CBA from the workshop. So i went to CBA github and downloaded their latest and manually installed it. Somehow it worked for me.

**Comment by 654wak654** [comment]
Could this be the same thing with CBA's [#701](https://github.com/CBATeam/CBA_A3/pull/701) where the "random" bug is because of a specific keyboard layout?

**Comment by commy2** [comment]
Using an outdated CBA will not help you in the long run, as an update will become mandatory eventually.

**Comment by Tralin** [comment]
I'm experiencing this problem. Using only ACE and CBA (newest versions, downloaded them from GitHub last night) I cannot use the self-interaction menu at all. It's just a red circle.

Tried by using a Workshop missions, single player scenarios, and even made a new mission in the Editor.

Tried creating a new profile, same result. Tried both Workshop ACE and CBA, and GitHub versions, same result. Tried resetting all parameters in Arma 3 launcher, same result.

RPT file here: https://pastebin.com/87uaQMcD

**Comment by Tralin** [comment]
An observation:

Myself, the OP (maximemoring), and the TheAngryPacifist in #5328 are all using Overthrow. I've tried in-and-out of Overthrow, and I disabled Overthrow while testing. But it is similar to each of us.

I should mention that a friend of mine playing on my Overthrow server has no issues with it at all. He also has Overthrow installed.

**Comment by maximemoring** [comment]
I'm thinking it's not Overthrow itself, but the fact that along with playing Overthrow with ACE3, we surely all installed a bunch of other mods, which somehow can either corrupts something or confuse the game permanently for that profile.

I was also originally using a bunch of weapon/gear mods, which I reinstalled after seeing that creating a new profile worked, and it has yet to stop working like last time.

**Comment by Tralin** [comment]
I did have the NIArms stuff installed, but I disabled that and only had ACE and CBA enabled for further testing. Upon creating a new profile I still had the same issue.

**Comment by bux** [comment]
Try launching Arma with only CBA and ACE3 then creating a new profile.

After that launch the editor, place down a single unit and "preview" the mission.

**Comment by commy2** [comment]
What is "Overthrow"?

**Comment by PabstMirror** [comment]
https://github.com/ArmaOverthrow/Overthrow

From what I quickly saw in it, there is a psersistant save function that saves what might be a very large array to the profilenamespace.
Given that creating a new profile fixed the issue for 2, that might be the cause.

**Comment by PabstMirror** [comment]
Reproducing the error after doing a persistent save with overthrow mod
Now get script errors even when loading with no mods

https://github.com/ArmaOverthrow/Overthrow/blob/dev/addons/overthrow_main/functions/save/fn_saveGame.sqf#L47
is attempting to save allVariables on a logic to profileNamespace in a single gigantic variable (~40kb)


Somehow just having those errors breaks CBA XEH InitPost
```
((player getVariable "cba_xeh_initPost") select 5) 
isEqualTo 
{_this call ace_interact_menu_fnc_compileMenu;_this call ace_interact_menu_fnc_compileMenuSelfAction;}
```
returns true
 
`[player] call ((player getVariable "cba_xeh_initPost") select 5)`
has no effect, but
`[player] call {_this call ace_interact_menu_fnc_compileMenu;_this call ace_interact_menu_fnc_compileMenuSelfAction;}`
does work??????????


Tell the overthrow guys they should not be saving CBA_XEH vars to profile
If you want to fix your profile, you can run this code in debug console from editor
```
profileNamespace setVariable ["Overthrow.save.001", nil];
profileNamespace setVariable ["Overthrow.malden.001", nil];
profileNamespace setVariable ["Overthrow.altis.001", nil];
```

**Comment by Tralin** [comment]
@bux I did as you said but still just a red circle.

@PabstMirror Running that code broke my save for Overthrow (oh well, it's okay), but it did not fix only having a red circle.

**Comment by Tralin** [comment]
Going to uninstall Arma, remove all mods, remove the AppData folder for it, and clear the My Documents folders.

**Comment by Tralin** [comment]
After removing steamapps/common/Arma 3, Appdata/Local/Arma 3, and My Documents/Arma 3* and reinstalling everything, it works again.

**Comment by Juisebox** [comment]
@Tralin I did this yesterday, and it was a temporary fix, but the next time I loaded up the game the Self-Interaction menu was only a red circle again.

**Comment by dedmen** [comment]
Can someone please upload his ".vars.Arma3Profile" file for me? I'm suspecting there might be another variable from Overthrow in there that might break stuff. I'm not sure if profileNamespace contains any sensitive data. But it might. You can find me on ACE Slack or Arma Discord.

https://github.com/ArmaOverthrow/Overthrow/blob/dev/addons/overthrow_main/functions/save/fn_saveGame.sqf#L34-L39
Crap code.. Woohoo...

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
