### ISSUE TITLE
Spotting Scope gunner get In access wrong side

### ISSUE THREAD

**Issue by 0dr** [acemod/ACE3#5324]
Arma 3 Version: 1.72.142265 (Profiling)
CBA Version: 3.4.0.170627 6a1a8e7a (Workshop)
ACE3 Version: 3.10.1.21 7b91629f (Workshop)

Mods:

- CBA_A3
- ace

Description:

    Spotting scope can only be entered from the visible front of the device.

Copy of #5128 because #5132 only fixed the ACE action and not the arma interaction point. 
(Memory point in p3d)

Steps to reproduce:

    have a spotting scope in the backpack. Place scope on ground. Back of scope faces player, but player is unable to interact with it. Move around to front of device, interact menu opens, getting in the gunner slot causes the player to teleport behind the device and lay down.

Where did the issue occur?

    Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

Placed Modules:

    None

**Comment by Th3Cr0w** [comment]
Solution:
   

> Move the "pos_gunner_dir" ahead of the "pos_gunner" in the .p3d
