### ISSUE TITLE
Ace_Medical "ATROPINE"

### ISSUE THREAD

**Issue by Robdemi** [acemod/ACE3#5326]
![atropine](https://user-images.githubusercontent.com/19828557/27811729-60595de0-6037-11e7-9917-29bc5a2a8cef.png)
There is a problem with one of the drugs in Ace_Medical
Atropine
Atropine IRL Increases cardiac output. Currently in the mod it looks like Atropine lowers the HR. It looks like it lowers B/P marginally but not really significant. 
The pharmacology of Atropine is that it inhibits action of acetylcholine at parasympathetic sites in smooth muscle, meaning GI tract and respiratory muscles to put in short. It also increases cardiac output meaning it increases heart rate of the heart and dries secretions. 

I don't know why the current version of ace still has Atropine to decrease HR. It doesn't make sense.

**Comment by Robdemi** [comment]
Just found complaint and replied with same comment as above #5293

**Comment by thojkooi** [comment]
Closing as duplicate.
