### ISSUE TITLE
Vehicle Rearming interaction no longer rearms vehicle on dedicated

### ISSUE THREAD

**Issue by gibfender** [acemod/ACE3#5329]
**Arma 3 Version:** `1.72.142223`
**CBA Version:** `3.4.0.170627` 
**ACE3 Version:** `3.10.1`

**Mods:**
```
- CBA_A3
- ace
- ace server (DS only)
```

**Description:**
- Interacting with a vehicle ammobox and chosing "Rearm > weaponName" makes the loading progress bar appear but the vehicles ammo is not actually replenished. 

**Steps to reproduce:**
https://youtu.be/JsJ5jtzeyoc
Repro mission attached [ammotest.VR.pbo.zip](https://github.com/acemod/ACE3/files/1124545/ammotest.VR.pbo.zip)

**Where did the issue occur?**
- Dedicated only (works fine in SP/listen server)

**Placed Modules:**
- None

**RPT log file:**
- Server: https://pastebin.com/vvSZXA3i
- Client: https://pastebin.com/RGA2ChMJ

**Comment by gibfender** [comment]
Ignore, duplicate

**Comment by gibfender** [comment]
Ignore, duplicate

**Comment by bux** [comment]
made me smile
![image](https://user-images.githubusercontent.com/1235520/27865286-4ed096fe-6192-11e7-9de9-94f6a779b3b6.png)
