### ISSUE TITLE
Actions with Sheathe weapon

### ISSUE THREAD

**Issue by J4P032** [acemod/ACE3#533]
Hi! 
When I want to act as a medic, to avoid in every action to make the animation of putting the weapon to the shoulder and finished, going back to my hands.. I use the 0 key to Sheathe it to the shoulder.
Ok.. it should be there until I select it again with 2 key... BUT everytime I make an action of medic when finished he pick my weapon back to the hands.

Would be nice to just leave it where it was.. my shoulder

**Comment by jaynus** [comment]
Please follow the guidelines for feature requests and/or bug reports: http://acemod.github.io/ACE3/wiki/user/how-to-make-a-feature-request.html
http://acemod.github.io/ACE3/wiki/user/how-to-report-an-issue.html
