### ISSUE TITLE
ACE rail interaction will swap RHS rail attachments for ACE rail attachment

### ISSUE THREAD

**Issue by KarlMoebius** [acemod/ACE3#5331]
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.4.0` (stable)
**ACE3 Version:** `3.10.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHSUSAF
```

**Description:**
ACE3 changing the rail attachments to Laser Pointer (Red) when Ctrl-L is pressed. When RHS, ACE3, and CBA_A3 is loaded only, no compat file, when a RHS rail device is equipped, CTRL-L deletes the rail device, and then auto equips an ACE3 Laser Pointer (Red).

**Steps to reproduce:**
- Go into Virtual Arsenal
- Spawn any RHS rail device equippable weapon (RHS or Vanilla)
- Apply any RHS rail device to weapon
- Exit Arsenal
- CTRL-L to ACE interact with the Rail Device. Should do nothing to a non ACE rail device (RHS rail interaction is set to CTRL-C)
- RHS Rail Device is deleted and replaced with an ACE3 Laser Pointer (Red)

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- https://pastebin.com/EPwSSNCA

**Comment by bux** [comment]
That's not an RPT file.

**Comment by PabstMirror** [comment]
Will be fixed in next CBA release (3.4.1)
