### ISSUE TITLE
Floating above chairs with acex sitting

### ISSUE THREAD

**Issue by neetch1** [acemod/ACE3#5332]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acex
```

**Description:**
acex sitting only seems to work with plastic chairs. when using with foldable/camping chairs you float above the chair.

**Comment by neetch1** [comment]
its just the vanilla chairs. do you need class names for those?

**Comment by jonpas** [comment]
Yes, there are a bunch of chairs, it's easier if you list which ones are not correct.

**Comment by neetch1** [comment]
well there are only 6 chairs for ace and 2 of them works. the one im interested in is this one "Land_CampingChair_V2_F". the ones that work is the plastic chair and the rattan chair.

**Comment by jonpas** [comment]
They all work. Some of them are a bit too high, but there isn't much we can do about that as I just let the unit be touching the ground with the feet.

![20170706161059_1](https://user-images.githubusercontent.com/7935003/27915166-bcba794a-6265-11e7-855a-79cd89d30382.jpg)

**Comment by neetch1** [comment]
oh then it's just me who has the problem. thanks for testing it out. when i try to sit in other than the plastic or the rattan chair i float OVER the chair. not sure why or what the problem is.

**Comment by jonpas** [comment]
Are you on latest versions? What map? What unit?

**Comment by neetch1** [comment]
well i just tried testing it without ace in VR with MacRae's sitting script and i had the same problem.. i just use a vanilla blufor unit. when i make a unit spawn in the chair from the start there is no problem, but when i use the "sit down" interaction (on the chairs that doesn't work (for me)) i float above the chair.

**Comment by jonpas** [comment]
I don't see why this would happen.

(BTW, this is an ACEX feature, not ACE3. :P)

**Comment by neetch1** [comment]
i know. btw this is how it looks
![](https://image.prntscr.com/image/sR3iFVN-TneAAO8pkQmpWw.jpg)
i tried running ace/acex with non other then cba enabled and it worked fine, so for some reason one of the other mods (i have a hundred mods enabled) is making this bug happen

**Comment by jonpas** [comment]
Definitely a 3rd party mod causing it then, your best bet is to go mod by mod and find out which one it is.

**Comment by Knight1981** [comment]
We have the same problem :( we are floating above the chair as you can see in neetch1 comment.

Did you find a solution neetch1? Which mod could it be?

**Comment by jonpas** [comment]
Enhanced Movement causes that. I already informed the author about it, nothing we can do.

**Comment by neetch1** [comment]
I don't use enhanced movement, Walkable Moving Objects was the one that did it for me

**Comment by Knight1981** [comment]
Ah okay, thank you for the quick reply. We are using advanced movement :( 

That sucks. No workaround etc.?

**Comment by jonpas** [comment]
No, the author has to fix it. Anything using a helper object for whatever positioning might cause that.

**Comment by commy2** [comment]
ref https://github.com/acemod/ACEX/pull/88

**Comment by Knight1981** [comment]
Sitting module is broken again since your rework in 3.4.0 (the floating problem) so I have to use previous version.
