### ISSUE TITLE
Selection in 3D menu motion with trackir.

### ISSUE THREAD

**Issue by J4P032** [acemod/ACE3#534]
Hi!

Would be possible to just when pressing the ace button not to move the head? If for example I make a gesture my avatar can start from moving front to moving to ground. 
The problem is bigger if we have trackir, because with any movement of the real our head.. it moves the selector of the menus.

Would be nice to have an option in the config of ace3 that when we press the button, the view doesn't move.. but our cursor yes, so we can choose the one we want. As said, as an option.

Thanks!

**Comment by jaynus** [comment]
Please follow our guidelines for feature requests and use the official feature request ticket.

http://acemod.github.io/ACE3/wiki/user/how-to-make-a-feature-request.html
