### ISSUE TITLE
In open map, my GPS does not display the numbers

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5340]
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.3.1` (stable)
**ACE3 Version:** `3.10.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- JSRS sound mod
- ASR AI mod
```

**Description:**
- When I open the map, my GPS displays the coordinates not correctly. The figures fell down. Thus, there is no possibility to see the current coordinates.  http://images.vfl.ru/ii/1499448091/0380ea15/17848788.jpg

**Steps to reproduce:**
- Place in the map your squad. Open map and see GPS.

**Where did the issue occur?**
- editor

**Placed Modules:**
- none

**RPT log file:**
- not needed

**Comment by PabstMirror** [comment]
Recent arma hotfix broke the font, will be fixed by https://github.com/acemod/ACE3/pull/5337

**Comment by jonpas** [comment]
Hotbreak*

**Comment by ZeusWrath** [comment]
thanks
