### ISSUE TITLE
AI do not use Laser Designators on hostile vehicles.

### ISSUE THREAD

**Issue by Hybrid-V** [acemod/ACE3#5341]
**Arma 3 Version:** `1.72.142223 STABLE`
**CBA Version:** `3.4.0`
**ACE3 Version:** `3.10.1`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
The default behavior for AI is to mark enemy vehicles with a Laser Designator if available. 
With ACE active the AI will no longer use their Laser Designator. 

https://youtu.be/tZbQ50xh_-U

Video of issue.

**Steps to reproduce:**
- Open editor and launch VR Map
- Place AI spotter from Special Forces NATO
- Place CSAT Tank some distance away (about 150-200 meters)
- Watch as AI spotter will notice the enemy tank and not use his rangefinder

- Follow same steps with NO mods loaded and note as the spotter will use his rangefinder and lase the target.

**Where did the issue occur?**
- Tested on Singleplayer / Self-Hosted Multiplayer / Dedicated Server / Editor

**Placed Modules:**
- Tested with both Zeus and No Modules

**RPT log file:**
- None

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
