### ISSUE TITLE
ACE Spare Barrel Doesn't Show In Arsenal 

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#5343]
Arma 3 Version: 1.72.142223
CBA Version: 3.3.1.170504
ACE3 Version: 3.10.1

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The ACE spare barrel doesn't show in the arsenal under misc

**Steps to reproduce:**
- Put an arsenal down and look for spare barrel in misc

**Where did the issue occur?**
- Dedicated Windows Server

**Placed Modules:**
- None

**Comment by bux** [comment]
confirmed

**Comment by PabstMirror** [comment]
It's under the 3x Magazines Tab, near the bottom:
See screenshot in https://github.com/acemod/ACE3/pull/4328

**Comment by Snak3Doc** [comment]
Righto thanks, though the all mags list is a mess and all other ace stuff is in misc might make sense to keep it all uniformed

**Comment by jonpas** [comment]
We can't change it, spare barrels are magazines, thus Arsenal shows them in the Magazines tab, other items are items (mine detectors actually) and thus they show in Misc.
