### ISSUE TITLE
Assign Car Key Module Doesn't Assign Keys 

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#5344]
Arma 3 Version: 1.72.142223
CBA Version: 3.3.1.170504
ACE3 Version: 3.10.1

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Unless I'm doing it wrong (please inform of the correct way if I am), the ace assign key module doesn't assign keys to the player's inventory, also it should allow assigning lockpicks as well seeing as they keys and lockpicks aren't in the arsenal (for obvious reasons). 

I would just use the units init to add it but then people start spawning in with random numbers of the thing that were added (think its a BI bug)

**Steps to reproduce:**
- Place a group of player units and place the assign key module, using the sync to members of group or sync to individual members and then sync the module to the player units, host the mission in windows dedicated server, and check your inventory.

**Where did the issue occur?**
- Dedicated Windows Server

**Placed Modules:**
- Assign Vehicle Keys & Lock Vehicle Doors Modules

**Comment by HolgerBiebrach** [comment]
I would like to reopen this issue. I cant get vehicle unlock to work on a dedicated server with players linked to the modul. Also using the function does not work on a DS eg. [bob, car1, false] call ace_vehiclelock_fnc_addKeyForVehicle;
