### ISSUE TITLE
Script error in fnc_calculateBarrelLengthVelocityShift

### ISSUE THREAD

**Issue by Cuel** [acemod/ACE3#5346]
**Arma 3 Version:** `1.72.142223`
**CBA Version:** `3.4.0.170627` 
**ACE3 Version:** `3.10.1.21`

**Mods:**
```
- CBA_A3
- ace
- others
```

**Description:**
https://github.com/acemod/ACE3/blob/master/addons/advanced_ballistics/functions/fnc_calculateBarrelLengthVelocityShift.sqf#L46
```
20:48:40 Error in expression < _muzzleVelocity
};


if (_barrelLength <= (_barrelLengthTable select 0)) exitWi>
20:48:40   Error position: <<= (_barrelLengthTable select 0)) exitWi>
20:48:40   Error <=: Type String, expected Number,Not a Number
20:48:40 File z\ace\addons\advanced_ballistics\functions\fnc_calculateBarrelLengthVelocityShift.sqf, line 28
20:48:40 Error in expression < _muzzleVelocity
};
```

**Steps to reproduce:**
Guessing it's a badly configured weapon on our end, but it shouldn't be a script error? If needed I can try and figure out which weapon it was and find the culprit value.

For reference I got the error as (game logic) zeus when a player fired a specific weapon

**Where did the issue occur?**
MP

**Comment by bux** [comment]
> If needed I can try and figure out which weapon it was and find the culprit value.

yes please

**Comment by Cuel** [comment]
`"sfp_kpist_m45 "call ace_advanced_ballistics_fnc_readWeaponDataFromConfig`
> [0,1,0]

`"sfp_9x19_parrabellum" call  ace_advanced_ballistics_fnc_readAmmoDataFromConfig`
> `[-0.002,9.017,15.1892,6.73909,0.5,1,[0.158],[],"ASM",[-2.655,-2.547,-2.285,-2.012,-1.698,-1.28,-0.764,-0.153,0.596,1.517,2.619],[350,385,420],["4*25.4","4.7*25.4","9*25.4"]]`

Seems like  `["4*25.4","4.7*25.4","9*25.4"]` is the `_barrelLengthTable` passed into the function which explains `type String`

**Comment by PabstMirror** [comment]
I think the configs should just be numbers.
Call/Compiling strings is just wasted overhead if the values are constant.
