### ISSUE TITLE
Arma 3 ACE Fullheal AI

### ISSUE THREAD

**Issue by TBannon** [acemod/ACE3#5348]
So im making a mission where there is a hospital and there is a medic in the hospital. I want the player(s) to be able to go over to the medic and use "Ace Interactions Key" and hover over the interactions option and have it say something like "Full Heal" and then the action bar appears and when it completes it would completely heal the unit (pain, bleeding, heartrate, blood pressure, etc.) Anything helps. Thank you

**Comment by bux** [comment]
This is not an issue. You're requesting scripting help (not even that, you're requesting someone to write the script for you). For that either ask on our forum: https://forums.bistudio.com/topic/193161-ace3-a-collaborative-merger-between-agm-cse-and-ace/ or join our public chat: https://slackin.ace3mod.com/
