### ISSUE TITLE
Allow non-centered actions as Passenger actions

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#5350]
Adding `"isNotInside"` exception to actions that are not under `ACE_MainActions` (eg. `captives` and `dogtags`) will not render them inside `ACE_Passengers` (in the vehicle under "Passengers").

Being able to Take/Check a Dogtag inside a vehicle is something that would be nice, but there are reasons to support this for the future.

**Comment by PabstMirror** [comment]
Medical will add to both places with the correct condition checks

**Comment by dedmen** [comment]
Milestone is ongoing bad bot.
