### ISSUE TITLE
Blood fx and other screens in 3 screen configuration

### ISSUE THREAD

**Issue by J4P032** [acemod/ACE3#536]
Hi!

This is an old issue. If we have 3 screens playing ARMA3, and for example we are hurt or we have dust in the glasses.. or other fx.. the FX screens that appear are cut and you can see the cut bitmap with 3 screen configurations (I have 5040x1050 res).
The only one that is correct is the night vision googles that is correct. The black border is extended to all the resolution.

Would be nice to fix this one.

Thanks!

**Comment by jaynus** [comment]
This is an interesting one, given not many of us have the configuration and hardware to test and reproduce these. Can you provide screenshots and/or pictures of the different behaviors to show what your saying?

**Comment by PabstMirror** [comment]
At lot of our effects dialogs will use `safeZoneX` and `safeZoneW`, that are designed for getting position on the primary monitor.
There are also commands `safeZoneXAbs` and `safeZoneWAbs` that should cover all monitor space.  But without any way to test I have no idea how they really work.  For example, the diving googles adds a vignette, but I bet it would look odd stretched 3 times as wide.

**Comment by J4P032** [comment]
Ok.. here is an screenshot.[image: Imágenes integradas 1]


The green lines are the border of my screens.. so you can see how the
bitmap is extended a little but not full. This is more odd in gas masks (I
couldn't use any) or other stuff using same technique. No problem with
Night vision Googles.. the black border is full extended

Javier Rollón LECU
OGA0830 // Ivao: 120179 // Vatsim: 1277138

2015-04-13 5:01 GMT+02:00 jaynus <notifications@github.com>:

**Comment by bux578** [comment]
Close?
