### ISSUE TITLE
Position of player instead of preference for quick mounting

### ISSUE THREAD

**Issue by Pergor** [acemod/ACE3#5360]
I have a simple recommendation for the vehicle quick mounting system:

Currently you can set a preference for a seat category for quick mounting.
Instead I'd think it would be more practical to quick mount a vehicle according to the vehicle door the player is standing in front of (if the player stands in front of the driver's door, he should get in the driver slot, if he stands in front of one of the passenger doors he should get on the passenger seat and so on). If the seat is taken the next one to the door will be taken (standing in front of the driver's door with the driver's seat taken will move the player to the seat right behind the driver's seat and so on).

Alternatively that could be one of the preference options:
- Prefer driver seat
- Prefer commander seat
- Prefer gunner seat
- Prefer passenger seat
- Prefer seat according to entry point

That'd be a nice addition, if at all possible.

**Comment by commy2** [comment]
>Instead I'd think it would be more practical to quick mount a vehicle according to the vehicle door the player is standing in front of (if the player stands in front of the driver's door, he should get in the driver slot, if he stands in front of one of the passenger doors he should get on the passenger seat and so on).

But how would you do that? The models in Arma don't actually have doors. How would the game know which door you're looking at, if that information is not in the models?

**Comment by madpat3** [comment]
there was something in the past: https://www.youtube.com/watch?v=caym14R7ja4
bisforum: https://forums.bistudio.com/forums/topic/152734-advanced-cockpit-interaction/


an active mod is badbenson's "enhenced movement", where you can also, besides from other options, mount a vehicle from any position in opening a dialog via a hotkey and then mouseclick on the desired position.

http://www.armaholic.com/page.php?id=27224

**Comment by jonpas** [comment]
We know how those mods do it, manually, entering every single position for every single vehicle manually.

**Comment by PabstMirror** [comment]
Might be able to do something based on code from https://github.com/acemod/ACE3/pull/273
That had some doors it couldn't detect because of `selectionPosition` problems, but in general got pretty close. Which I think should be good enough for this quick mount. Even if it picks the wrong specific passenger seat, it should still get you inside.

**Comment by Pergor** [comment]
> Might be able to do something based on code from #273
That had some doors it couldn't detect because of selectionPosition problems, but in general got pretty close. Which I think should be good enough for this quick mount. Even if it picks the wrong specific passenger seat, it should still get you inside. <

Yeah, that's kind of what I had in mind.
A manual approach that needs a special config for every vehicle of course is not a good way. But maybe a workaround could be found - if not directly then maybe even something unconventional.
Surely, if a player stands in front of the driver's door, the driver's seat (or a dummy on this seat) is closer to the player than the gunner's seat. If the different distances to the seats could be used to check for the closest seat, that should help in finding a way to put the player in the closest seat.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
