### ISSUE TITLE
Advanced Fatigue Does not affect AI (It's not a fair system)

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5361]
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.4.0` (stable)
**ACE3 Version:** `3.10.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- JSRS4 (sound mod)
-ASR AI mod
```

**Description:**
- It seems that, the advanced fatigue system has an effect only on the player. It looks very stupid when the character of the player breathes heavily and moves to a walk (he is no longer able to run), while his squad, continues to run, run, runs far ahead.  It seems to me, that any system of fatigue should act absolutely for all infantrymen in the game. At least, then such a system **will be honest and fair.**

If advanced fatigue system only affects the player, any mission where the player is not the leader in the squad becomes a problem, since the leader and all members of the squad always run ahead and the player can not catch up with them.  But the main problem of this issue, in my opinion is not a fair game, because the opponents have no such system as well.

**Steps to reproduce:**

 _1) Place in the map any infantry squad (player is not squad leader)_
 _2) Give to this squad MOVE waypoint, with maximal speed_
 _3) Run game, and run with your squad, you will see, that soon the player will stop running and move to a walk, while all the members of his squad will continue to run and eventually move away from the player, far ahead._

**Where did the issue occur?**
- Editor (Multiplayer)

**Placed Modules:**
- None

**RPT log file:**
- not needed

**Comment by BaerMitUmlaut** [comment]
It's not viable in terms of performance.

Additionally AI are not affected by the "penalties" from AF the same way players are affected, which we can't do anything about.

If you want to play with AI, I'd just turn it off. If you want to play against AI and you think it's unfair, adjust their skill or your game difficulty.

**Comment by ZeusWrath** [comment]
Thanks for answer

> If you want to play against AI and you think it's unfair, adjust their skill or your game difficulty.

The game's difficulty settings do not have the slightest relation to this issue, because I speak **only** about ACE3 feature, which affects **only** player.  Yes, I will have to remove ACE fatigue system in both cases. (If to play against or with AI). For ACE part to make the system only for the human player is a poor decision...  Such a system is not fair and it is better not to use it in general.

**Comment by jonpas** [comment]
Then don't, simple as that.
