### ISSUE TITLE
2D Scopes overlay too small to non 16/9 resolutions

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#537]
Testing Session 2015 04 12

![2015-04-12_00012](https://cloud.githubusercontent.com/assets/1235520/7111788/c7d9dc50-e1c3-11e4-96d3-3c82efb855c9.jpg)

**Comment by commy2** [comment]
What are your graphics settings?

**Comment by bux578** [comment]
1920x1200 16:10 fullscreen

**Comment by commy2** [comment]
And that other thing that is usally at a 100% and can be more or less?

**Comment by bux578** [comment]
at 100%

**Comment by commy2** [comment]
k. making a seperate issue for the missing, as this is a seperate issue with cameras breaking PIP

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/issues/547

**Comment by Gwynblade** [comment]
I'm not 100% sure what closed means in this case, is this bug considered fixed? Just in case it is, I have the exact problem like the picture shows, on 1280x1024 resolution. Only 2D ARCO and MRCO are affected, RCO is completely fine. They all work fine on 1920x1080.
