### ISSUE TITLE
Changing the "interaction default key"

### ISSUE THREAD

**Issue by Coolboard** [acemod/ACE3#5377]
**Arma 3 Version:** `1.72.142223` (rc)
**CBA Version:** `3.4.0` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
-ASR AI3
- ace
```

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

=-> No errors, just a wish.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

=-> Needn't, or just play with mouse at left hand and num pad with right hand ;)

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

=-> I'm playing using Num_Pad (because i use the mouse with my left hand), and with @ace, i wish to use an other interaction default key, more useful for my ergonomy.
I wish use the Num_.  (dot) in place of Win_G or as secondary.
Does it available ? 

Thanks for your great work.

**Comment by Dystopian** [comment]
Esc - Options - Controls - Configure addons - ACE3 Common
