### ISSUE TITLE
Missing nametags for cargo units

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#538]
Testing Session 2015 04 12

![2015-04-12_00014](https://cloud.githubusercontent.com/assets/1235520/7111818/02bbf272-e1c4-11e4-960b-7477256efcd3.jpg)

In case this isn't by design.

**Comment by commy2** [comment]
Wouldn't work. all getPos / modelToWorld etc. commands return the position of the vehicle. All nametags would be at the same place in the center of the vehicle.

**Comment by commy2** [comment]
Wouldn't work. all getPos / modelToWorld etc. commands return the position of the vehicle. All nametags would be at the same place in the center of the vehicle.

**Comment by CorruptedHeart** [comment]
I know one mod that manages to show names for people in vehicles. [ZAM Show Names](http://forums.bistudio.com/showthread.php?185380-ZAM-ShowNames)

**Comment by jaynus** [comment]
It looks like it uses the boundingBox of the model, which may be a visual render location instead of position. 

This could actually prove useful in other places as well.

**Comment by adampiskorski** [comment]
In my mod it does show names in vehicles, and it works perfectly for stationary vehicles, but when you start moving then the positions get offset.

**Comment by esteldunedain** [comment]
> In my mod it does show names in vehicles, and it works perfectly for stationary vehicles, but when you start moving then the positions get offset.

That should be fixable. You probably need to apply this corection:

```sqf_corre

**Comment by adampiskorski** [comment]
Thanks for the tip!

**Comment by jaynus** [comment]
Can you clarify how its being done? Are you using visual model rendering positions bounding boxes or some other factor for it?

**Comment by adampiskorski** [comment]
It's been a while since I rewrote it, so I'll have to jog my memory, but my code is quite nicely commented (for me at least so that I can easily remember what I was doing) and it's nicely explained here: https://bitbucket.org/zulualpha/zam-shownames/src/fa3e5a18fd9f4cac45cd0fe121cfac29cf34941b/Addons/zam_shownames/functions/fn_showNames_OnEachFrame.sqf?at=default

**Comment by esteldunedain** [comment]
`fn_showNames_OnEachFrame.sqf` just uses `modelToWorldVisual`; @commy2 said it didn't work inside vehicles; he's either wrong or some other function is used for those cases

**Comment by adampiskorski** [comment]
Ill have to look into it, but if my mod doesn't show nametags in vehicles above the passengers heads, then this is the first I am hearing of it.

**Comment by jaynus** [comment]
modelToWorld and modelToWorldVisual may return completely different coordinate sets and not be documented. I'll test now.

**Comment by esteldunedain** [comment]
BTW, @adampiskorski sorry but the correction I posted above won't work in your code, as you already use `modelToWorldVisual`. IDK why they would lag then.

**Comment by adampiskorski** [comment]
I suspect because the position is only updated per frame and not per tick, so in a moving vehicle that won't be good enough.

**Comment by esteldunedain** [comment]
@adampiskorski, checking a bit more: To get fully consistent 3d positions with rendering positions you need to use `modelToWorldVisual` on an onDraw mission event, not on a onEachFrame event. Graphical transformations are applied in the engine between the two, so if you draw on onEachFrame the draw positions lag a frame. We had to fix that too.

**Comment by adampiskorski** [comment]
Thanks!

Also @jaynus I just tested it on my side and modelToWorldVisual and modelToWorld returned the same result to me, at least by casually putting them into the debug console when both in and out of the vehicle.

Just to make sure we are all in the same page, is this behavior what you guys are looking for? https://www.dropbox.com/s/ol9mdabcqr2e9o7/arma3%202015-04-16%2019-16-15-60.jpg?dl=0

**Comment by esteldunedain** [comment]
Ok, I think `modelToWorldVisual` should work. The only thing we need to do is iterate through units in vehicles; maybe only for units in your own vehicle or turned out units on nearby vehicles.

**Comment by jaynus** [comment]
Lets assign it and get it done; if it was just an incorrect assumption for modelToWorldVisual then lets do it. It should be a tiny change to the ace_nametags module to use it.

**Comment by adampiskorski** [comment]
Awesome to see you guys at work and thanks for the tips!

**Comment by esteldunedain** [comment]
I think it's safe to push this to 3.1, as it's really low priority
