### ISSUE TITLE
Mod Use

### ISSUE THREAD

**Issue by LordTrust** [acemod/ACE3#5380]
Hello,
Can I use the Mod in the Modpack from our Server? We wrote you in the Briefing from our mission.

Lg, Maik

**Comment by BaerMitUmlaut** [comment]
Of course you can. What good wood be a mod that you can't use?

**Comment by SilentSpike** [comment]
Refer to the license file: https://github.com/acemod/ACE3/blob/master/LICENSE

**Comment by dedmen** [comment]
If you want to upload it to Steam workshop please keep in mind [Steam subscriber Agreement](http://store.steampowered.com/subscriber_agreement/#6) §6D
