### ISSUE TITLE
Running a server for vanilla and ACE players

### ISSUE THREAD

**Issue by celticalliance** [acemod/ACE3#5382]
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.4.0` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
We would like to know if it is possible to run our server for ACE and vanilla players. Note that we are running ACE on our server but have disabled the file checks ACE performs because we believe it prevents server kicks and allows players without ACE to play on the server. The missions we run also do not use any ACE modules, but are set up in such a way ACE players can use ACE features if needed and vanilla players are not hindered in any way by it.

The current situation is though that people who are not running ACE are kicked from the server. Basically we would like to know how to make it possible that vanilla players can join and play on our server without being kicked, and allow ACE players to use ACE when they are running it.

**Steps to reproduce:**
None

**Where did the issue occur?**
- Dedicated 

**Placed Modules:**
None

**RPT log file:**
None

**Comment by jonpas** [comment]
I suggest not, ACE3 relies on everyone having the mod for various reasons, you are just asking for trouble otherwise.

**Comment by celticalliance** [comment]
Right. Well, we would just like to be accessible to vanilla and ACE players, to reach as many players as possible.

I'll report back my findings though. Thank you for the reply.

**Comment by jonpas** [comment]
And you won't succeed without big issues, I can almost assure you that. Unless you pick component by component which are all local, in which case you are left with less than half of the components.
