### ISSUE TITLE
Medic can't use PAK on himself

### ISSUE THREAD

**Issue by celticalliance** [acemod/ACE3#5383]
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.4.0` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
On our private training server we are using ACE server settings. We have added the ace_server pbo to its own folder and changed some settings in ACE's serverconfig file. For some reason though our Medics are not able to heal themselves with the PAK. Can you check the settings we use and tell us why it is not working? I have included a link to the ACE settings file we are using on the server.

Link: https://drive.google.com/open?id=0B1FOuoYQE7j2MkhJU09CUzRZWTg

**Steps to reproduce:**

**Where did the issue occur?**
- Dedicated

**Placed Modules:**

**RPT log file:**

**Comment by tbeswick96** [comment]
Might want to to put those settings into a [pastebin](https://pastebin.com/) or [gist](https://gist.github.com/) and just paste the link

**Comment by BlueNexus** [comment]
Not a bug. This is the intended behaviour.

**Comment by celticalliance** [comment]
Right. Another mystery solved then. Thank you :)

**Comment by commy2** [comment]
Close?
