### ISSUE TITLE
Arma 3 Ace Self Interaction Medical Menu Not Working

### ISSUE THREAD

**Issue by EstonianLama2** [acemod/ACE3#5387]
**Arma 3 Version:1.72 Stable
**CBA Version: 3.4.0 Stable
**ACE3 Version:3.10.2 Stable

**Mods:**
- @CBA_A3
- @ace

**Description:**
- When i press CTRL+Windows key a red empty red circle appears without any selection options

**Steps to reproduce:**
- Hold CTRL and Windows key

**Where did the issue occur?**
-  / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) /

**Placed Modules:**
- none

**RPT log file:**
- https://gist.github.com/EstonianLama2/c812de06a72a67825ad73fc7e7605210

**Comment by PabstMirror** [comment]
Issue looks similar to https://github.com/acemod/ACE3/issues/5323
```
 Global namespace not passed during: _this call ace_attach_fnc_handleGetOut;
 Error in expression <_this call ace_attach_fnc_handleGetOut;>
 Error position: <ace_attach_fnc_handleGetOut;>
 Error Local variable in global space
```

Have you used the overthrow mod on this profile?

**Comment by EstonianLama2** [comment]
Yes i have
