### ISSUE TITLE
Titan UI Issues #2

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#539]
Testing Session 2015 04 12

![2015-04-12_00025](https://cloud.githubusercontent.com/assets/1235520/7111862/76235066-e1c4-11e4-9092-3209e96c5ef1.jpg)

The "seek" lines move out of the display area. (left side in picture above).
(and I wasn't able to lock on to the chopper, but I haven't tried it again, as it was in the heat of battle)

**Comment by jaynus** [comment]
Your SEEK Icon is lit, so it means it locked - did it not tone OR show the lock box?

**Comment by VKing6** [comment]
* The launcher can currently enter SEEK mode even if there's no round loaded. This should be disabled, as the SEEK display is using the missile's internal camera.
* The WFOV light doesn't change to NFOV when you zoom in.

**Comment by jaynus** [comment]
All fixed in #579
