### ISSUE TITLE
german language fail at magazinerepack

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#5390]
**Arma 3 Version:** `stable`
**CBA Version:** `stable`
**ACE3 Version:** `stable`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- https://github.com/acemod/ACE3/blob/master/addons/magazinerepack/stringtable.xml#L135
- should be: %1 volle Magazine und %2 angefangene Magazine
- ALSO, you can only repack one type of magazine so there is 0 or 1 (most time) partial mag anytime, so the number for partial mags is not needed

**Steps to reproduce:**
- repack magazines

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- all

**RPT log file:**
- is not needed

**Comment by commy2** [comment]
You can edit these by clicking the pencil in the top right corner.

**Comment by dedmen** [comment]
But then the other languages translations would also be wrong.
German say "%2 bullets". English says "%2 partial magazines".
Which is kind of a big difference.

**Comment by shukari** [comment]
Yeah... that is fixed with this PR... in german is bullet in all other only full and partial... thid is a wrong translation in german.

**Comment by dedmen** [comment]
Forget what I said.. Apparently I'm to dumb to read diffs anymore.

**Comment by dedmen** [comment]
Blame #3303 btw
https://github.com/acemod/ACE3/pull/3303#r52473074
According to the Function that uses the string it always was partial magazines and never bullets.

**Comment by commy2** [comment]
I thought this was shown after you repack the magazines. Where
72 bullets become 2 magazines and one mag with 12 rounds.

**Comment by shukari** [comment]
That thing that @commy2 mentioned must be done... you will have in 99% of the cases x full and 1 partial with y rounds... not the info that this is 1 mag is important the amount of rounds is important...

**Comment by PabstMirror** [comment]
If you cancel repacking the number of partial mags could be greater than 1
![image](https://user-images.githubusercontent.com/9376747/29008164-aa7baefe-7ad7-11e7-8318-b8735f9689a3.png)

**Comment by shukari** [comment]
Because of this is the pull request already updated and newer... only successful repack shows now full + rounds... -> #5392
