### ISSUE TITLE
Self Interaction Menu Not Working

### ISSUE THREAD

**Issue by JHill29th** [acemod/ACE3#5391]
**Arma 3 Version:** `1.72.142223` (stable)
**CBA Version:** `3.4.0.170627` (stable)
**ACE3 Version:** `3.10.2.22` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Self Interaction menu does not work.

**Steps to reproduce:**
- Launch and try to use.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal -- All of above.

**Placed Modules:**
- N/A

**RPT log file:**
https://pastebin.com/ghU0k9pY

**Comment by PabstMirror** [comment]
see https://github.com/acemod/ACE3/issues/5323

**Comment by JHill29th** [comment]
Creating a new profile didn't work.
Re-installation of CBA and ACE did not help.
I don't even know what "Overthrow" is.
Tried a re-install of A3 as well.

**Comment by commy2** [comment]
Looks like the identical problem though.
```
12:19:53 Global namespace not passed during: _this call ace_attach_fnc_handleGetOut;
12:19:53 Error in expression <_this call ace_attach_fnc_handleGetOut;>
12:19:53   Error position: <ace_attach_fnc_handleGetOut;>
12:19:53   Error Local variable in global space
```
etc.

**Comment by commy2** [comment]
@PabstMirror Do you remember how to repro the error with Overthrow?

**Comment by PabstMirror** [comment]
They save `allVariables` on a logic object.
Which has a bunch of big XEH code vars`
So just a gigantic array with huge sections of code saved to profileNamespace.

My guess is arma is failing at quote escaping with the code, or something like that.

Ref https://github.com/ArmaOverthrow/Overthrow/blob/dev/addons/overthrow_main/functions/save/fn_saveGame.sqf#L47

**Comment by badkneegrow** [comment]
@JHill29th Are you sure new profile does not work?

**Comment by commy2** [comment]
Neither ACE nor CBA do store CODE in the profile. It's not very useful to do that and has other problems too...
Maybe it's a different mod that does the same thing?

**Comment by JHill29th** [comment]
@badkneegrow Creating a new profile did/does not work.

**Comment by PabstMirror** [comment]
I don't think anyone here really understands the  `Global namespace not passed` error.
It happens at a very odd time when no ace code is running.
The only way I was able to reproduce was corrupting my profile (https://github.com/acemod/ACE3/issues/5323#issuecomment-313145415)

To be honest you may want to contact BIS on this as I don't think there is much we can do to help.
I do still believe it may be a profile corruption thing, so if you want to you could try the following (this will remove all missions/saves/profiles you have)

- Uninstall in steam
- Delete game folder (`C:\Program Files (x86)\Steam\steamapps\common\Arma 3`)
- Delete Arma Profile Folders (My Documents \ `Arma 3` and `Arma 3 - Other Profiles`)
- Delete Arma UserData Folder (`%localappdata%/Arma 3/` which is same as `C:\Users\yourName\AppData\Local\Arma 3`)

Then reinstall

**Comment by The-Mighty-Spud** [comment]
I'm having the same issue when i try to load a SP save game.

**Comment by commy2** [comment]
@The-Mighty-Spud 
Reproduce it with just CBA and ACE and post the RPT log file.

**Comment by The-Mighty-Spud** [comment]
My apologies, It appears to only happen when CBA,ACE and C2-command and control are active.

**Comment by commy2** [comment]
ref https://steamcommunity.com/workshop/filedetails/discussion/491016790/1471967615884913725/?ctp=4#c1638675549022797744

Sadly, as this is only on Steam, I can't do a quick check, but it seems to me that it is likely that mods fault.

**Comment by dedmen** [comment]
> I don't think anyone here really understands the Global namespace not passed error.
Happens when CODE stored in profileNamespace is loaded, profileNamespace is loaded before the script evaluator is properly initialized, and thus it fails.

**Comment by commy2** [comment]
There sure is nothing that can be done about it from our side.

**Comment by The-Mighty-Spud** [comment]
Alright, thanks for taking the time to look into it guys! I appreciate it.
