### ISSUE TITLE
Forced zeus/curator interface blackscreen

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#5393]
**Arma 3 Version:** `1.72.142342` (performance)
**CBA Version:** `3.4.0` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- if you have a player with a connected zeus with forced interface... on a dedicated server (not eden multiplayer) after spawn there is only a blackscreen

**Steps to reproduce:**
- put repo on ds and join the slot -> [forcedZeusBlackscreen.Malden.zip](https://github.com/acemod/ACE3/files/1185382/forcedZeusBlackscreen.Malden.zip)

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- all in Repo placed

**RPT log file:**
- client -> [Arma3_x64_2017-07-30_02-28-15.txt](https://github.com/acemod/ACE3/files/1185383/Arma3_x64_2017-07-30_02-28-15.txt)
- server -> [arma3server_x64_2017-07-30_02-32-14.txt](https://github.com/acemod/ACE3/files/1185384/arma3server_x64_2017-07-30_02-32-14.txt)

**Comment by PabstMirror** [comment]
I couldn't reproduce when trying on a dedicated server.
Maybe see if the same thing happens on a similar mission without ace running.

You also have "Show Briefing" unchecked (attributes -> general -> states).
So there could be some kind of race condition that I'm just not getting.
Re-checking this might help.

**Comment by shukari** [comment]
Yeah i tested it with Briefing on also blackscreen and wirhout ace and also blackscreen.
Can you pls send me your server log (for params and that stuff) that i can track down the problem?

**Comment by shukari** [comment]
**BI bug with "-autoInit" parameter -> https://feedback.bistudio.com/T126350**

**Comment by commy2** [comment]
So unrelated to ACE?

**Comment by shukari** [comment]
Yeah unrelated... was a coincidence with the parameter sorry for the trouble.
