### ISSUE TITLE
Ace Interaction on House_Small_F

### ISSUE THREAD

**Issue by burnacid** [acemod/ACE3#5396]
**Arma 3 Version:** Latest (unknown at time of writing)
**CBA Version:** `3.4.0.170627` 
**ACE3 Version:** `3.10.2`

**Mods:**
```
- CBA_A3
- ace
- EODS (4thIB)
- Ares Achilles
```

**Description:**
- I hope I can ask more of a support question here. For a mod I'd like to add Ace Interaction to objects. Most work but it seems it's impossible to add interaction on anything static for example any House_Small_F doesn't work. Take for example Land_GarbageBin_01_F:House_Small_F

**Steps to reproduce:**
Current setup that works for objects doesn't work for "static" objects for example
```
class Land_GarbageBin_01_F:House_Small_F {
	#include "ACE_INTERACTION_EODS.hpp"
};
```

ACE_INTERACTION_EODS.hpp
```
class ACE_Actions {
    #define ACTION_CONDITION condition = true;
    class ACE_MainActions {
        class ACE_EODS {
            displayName = "EODS";
            distance = 2;
            ACTION_CONDITION
            statement = "";
            EXCEPTIONS
            showDisabled = 0;
            priority = 2;
            //icon = QPATHTOF(UI\icons\bandage.paa);
            class Inspect {
                displayName = "Inspect";
                distance = 2;
                condition = "!(_target call FNC_EODS_IEDS_OBJ_IS_INSPECTED)";
                statement = "[_target] execvm '\EODS_ieds\functions\PCU\EODS_PCU_INSPEC_OBJ.sqf'";
                EXCEPTIONS
                showDisabled = 0;
                priority = 2;
                //icon = QPATHTOF(UI\icons\bandage.paa);
            };

            class RevealIED {
                displayName = "Reveal IED";
                distance = 2;
                condition = "_target call FNC_EODS_IEDS_OBJ_IS_INSPECTED";
                statement = "[_target] execvm '\EODS_ieds\functions\PCU\EODS_PCU_REVEAL.sqf'";
                EXCEPTIONS
                showDisabled = 0;
                priority = 2;
                //icon = QPATHTOF(UI\icons\bandage.paa);
            };
        };
    };
};
```

**Where did the issue occur?**
- Selfhosted multiplayer and singleplayer

**Placed Modules:**
- None

**RPT log file:**
- No errors in RPT file

**Comment by shukari** [comment]
Was there not a ACE3 setting to allow the interaction menu on buildings... (ESC -> Ace settings)... because the performance the default is off... so try it with the setting on.

**Comment by burnacid** [comment]
@shukari you mean the option "Show actions for buildings"?
That's set enabled

**Comment by PabstMirror** [comment]
Init EH doesn't run on map objects (e.g. houses that show up on the map)
You can manually run them with something like
`["Land_GarbageBin_01_F"] call ace_interact_menu_fnc_compileMenu`

**Comment by burnacid** [comment]
Oke but that also goes for spawned objects?
Could I just add an init EH for the classes I guess? (a bit new to arma coding)

**Comment by commy2** [comment]
No, the only way to add eventhandlers to classes instead of specific object is by using `CBA_fnc_addClassEventHandler` and that system (called "XEH" == Extended Event Handlers) is disabled for all terrain objects generally and also for most of the building classes specifically.
If you're using a map placed object, you could enter the code into the objects init box in the editor.

**Comment by burnacid** [comment]
No I'm more talking about Zeus placed objects. Map/mission placed objects are not really a priority.

So lets say Zeus spawns a garbage pile (mostly used for this) class Land_GarbageBin_01_F:House_Small_F

**Comment by commy2** [comment]
You can manually enable XEH for a class by making a mod like this:
```cpp
class CBA_Extended_EventHandlers_base;

class CfgVehicles {
    class BaseClass;
    class Class: BaseClass {
        class CBA_Extended_EventHandlers: CBA_Extended_EventHandlers_base {};
    };
};
```

**Comment by burnacid** [comment]
I'll try this late thanks in advance. Will keep you posted on the results

**Comment by commy2** [comment]
I edited it, because it was slightly wrong.

**Comment by jonpas** [comment]
`House_Small_F` should already have ACE interactions since #5353. You have to inherit them from the parent (house) class.

**Comment by burnacid** [comment]
@jonpas but if that is the case shouldn't I already see an interaction menu? I now see nothing at all on those objects

**Comment by jonpas** [comment]
Main action alone doesn't show if it has no actions, if you inherit you'll inherit the main action correctly. Or you define it properly yourself.

**Comment by BaerMitUmlaut** [comment]
Close?
