### ISSUE TITLE
Airdropped cargo is sometimes bouncing off the ground and exploding

### ISSUE THREAD

**Issue by KarlMoebius** [acemod/ACE3#5399]
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.4.0` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- @RHSUSAF
- @RHSAFRF
- ACE compat for USAF/AFRF
```

**Description:**
- When a vehicle is air-dropped it spawns a parachute and drifts down. When the vehicle lands, it seems once the parachute attachment point of the vehicle and the terrain level are equal, the parachute lets go, which leaves some vehicles half or fully inside the terrain when the parachute lets go, and then arma physics take over. Once Arma takes over, the vehicle immediately bounces into the sky, lands and explodes.

**Steps to reproduce:**
- Put two vehicles in a flying vehicle via ACE3. (in my example a RHSAFRF BTR-80A inside a RHSUSAF C-130, manipulating the BTR to take 1 space, instead of -1 and unload able, so it loads and unloads quickly)
- Take off.
- @ 1000m indicated altitude/ ~300km/h indicated air speed, initiate airdrop through the ACE3 cargo interface. (Testing with lower altitudes has proven problematic, sometimes the vehicle's parachute spawns sideways or at an angle, and the vehicle does not straighten out, or oscillates back and forth during descent)
- Using zeus, or some other method, position yourself near the falling vehicles.
- Watch as some vehicles impact and keep going into the ground, but once the vehicle attachment point of the parachute is equal with the terrain, the parachute lets go.
- Arma physics takes over and bad things happen.

Is this only me?

**Where did the issue occur?**
- Dedicated / Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- none

**RPT log file:**
- https://pastebin.com/8qTnPFR1
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by KalleK-OPT** [comment]
SIMILAR problem regarding airdrops in general using latest ace3 and CUP-chernarus... except for the fact, that boxes and crates fall through the ground and are no longer reachable

https://www.youtube.com/watch?v=JlM43VIs7Eg&feature=youtu.be

**Comment by Bosenator** [comment]
Confirmed having the same issue on the object `B_supplyCrate_F`.

**Comment by jonpas** [comment]
This has been changed in #6238, please reopen if it's still an issue.
