### ISSUE TITLE
Can't switch between IR laser and visible laser pointer

### ISSUE THREAD

**Issue by Wiesore** [acemod/ACE3#5400]
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.4.0` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
After the latest update, I noticed I can't switch from IR laser to visible laser. I checked my controls and noticed that switch laser / IR laser entry is missing. Tried default keybinding to switch between lasers, but it didn't work.

http://imgur.com/a/SWBPj

**Steps to reproduce:**
Pick red laser pointer (default bis), try to change between laser modes. Check if keybind is missing in controls (ACE Weapons).

**Placed Modules:**
None

**Comment by jonpas** [comment]
Did you scroll down in case it loaded later? And made sure "ace_laserpointer.pbo" is there?

**Comment by Wiesore** [comment]
Yes, I scrolled down and checked below as well. Also searched for "Switch Laser / IR Laser" in other ACE menu's (ACE Common and others). Unless it's named differently now, then it's possible I missed it

All the .pbo's are there, and are completely untouched. Downloaded directly from https://ace3mod.com/

**Comment by commy2** [comment]
It's in "CBA Attachments" (or something like that) and not "ACE Common" etc.

**Comment by Wiesore** [comment]
You're right, it's now "Next rail item state" in CBA's menu. False alarm, and thank you.

One thing I noticed though, that CBA hint that appears (when switching between lasers) stays really long. 30 seconds until it starts to fade away, and 5 seconds until it completely fades. 

I know it's a bit nitpicking, but could you please shorten it if you get the chance?

**Comment by PabstMirror** [comment]
We were using ACE's displayText
CBA is just using `hintSilent` so it is just going to use BI's fading timing

So probably not something we can fix
