### ISSUE TITLE
The NLAW is too weak, AI not uses fire-modes?

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5403]
**Arma 3 Version:** `1.72` (stable )
**CBA Version:** `3.4.0` (stable  )
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
- CBA_A3
- ace
- JSRS4 sound mod

**Description:**

Hi ACE3 mod. First you made NLAW disposable, and now, after tweaks with attack-modes this weapon becoming almost useless.

Problems:

1) The Direct Attack mode of fire is not capable of killing even car! For example, after hit, the Punisher gets some damages but can not be fully destroyed. Then why is Direct Attack necessary at all, if an anti-tank missile can not kill a car? 

2) Only Top Attack mode is meaningful, but AI does not know how to use it!  If AI is uses  NLAW, then such a fighter is completely useless, since he will only use the default shooting - Direct.  As I said above, such attack mode can not even kill a Punisher.

3) Top Attack mode has a weak effect on tanks.  It is necessary to strengthen this.  For example, you can see how NLAW blows the tower of the tank T-72.  https://youtu.be/Nz2qCRNEyfE?t=201 
Given that NLAW is a one-time weapon, it should have a greater impact against tanks, because the soldier who carry it has the abbreviation - AT (Anti-Tank)

By my humble opinion, expected tweaks:

1. At Direct Attack, the NLAW missile, should have a more impact. at least car must be fully destroyed
2. AI firing from NLAW must use a more stronger Top Attack mode. If it's impossible to correct this during the game, then let it always use it.
3. At Top Attack, the NLAW missile must kill the tank, or at least cause much more damages.

**Steps to reproduce:**

1. Shoot at Punisher. The target will not be fully destroyed
2. Watch how your subordinate AI uses NLAW. AI not will be use more effective Top Attack.
3. Shoot at Tank (Top Attack mode). This attack will not be effective.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- none

**RPT log file:**
- not needed

**Comment by commy2** [comment]
I disagree with all of these points.

**Comment by CoxLedere** [comment]
@commy2 While I disagree on the Overfly Attack mode, he does have a point with the Direct.

In my testing, the Direct attack mode is unable to reliably damage anything above the Kamaz truck for CSAT. 

The Punisher can disabled by firing the missile directly at the front of the vehicle, which will knock out the engine. Any other location will fail to even disable the vehicle, and the passengers will be completely unharmed.

The ARMA simply cannot be disabled by a direct attack from an NLAW, with the possible exception of maybe popping all three tires from a side shot, but I was only able to pop two. In addition, any crew or passengers do not take damage, even if the shot is fired directly into the rear troop compartment.

The Typhoon truck also seems immune to the NLAW, as a shot fired directly at the engine compartment caused cosmetic damage to the entire truck, but no module damage to the engine.

Yet, the overfly attack mode will outright destroy all three of these vehicles (or cause the ARMA to cook-off, if it has that setting enabled. Disabled it does outright explode.) This is a very large divide between the two attack modes, as one is almost completely ineffective, and the other is pretty much a killshot for anything that isn't a tank.

As it currently stands the Direct attack mode is questionable at best, as, even if there was a situation where an Overfly could not be used, chances are a Direct attack would not cause any damage to the target.

**Comment by ZeusWrath** [comment]
This is simple example...
 
If a player shoot from NLAW at APC Otokar Arma (Top Attack mode), then he always destroy it, when the AI shoots at Otokar Arma, he can not destroy it.  Ai not uses top attack? Or another reasons, but this is not normal.  I'm not going to provide you with a personal video. Just do this test yourself.  

> I disagree with all of these points. 

1. Direct attack - does not make the slightest sense (Try this)
2. AI not able destroy targets, which player can destroy (Try this)
3. NLAW not effective against tanks (Try this)

with respect...

**Comment by commy2** [comment]
The NLAW is doing the same amount of damage in direct attack mode as it does in vanilla. ACE should not rebalance weapon damage as that will only lead to conflicts with 3rd party mods. If you feel like the NLAW is too weak, bug BI about it.

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/issues/3834

**Comment by ZeusWrath** [comment]
@commy2. 

Ok, If you can not edit the damage from an NLAW Direct attack, and if you think, that the Top attack against the tanks is enough (despite the fact that it is not capable of killing a tank) **then at least teach the AI to use always only Top Attack Mode**, because in Direct Attack mode the NLAW is much weaker. 
**There is no point in using weapons in weak mode.**

**Comment by AACO** [comment]
@commy2 the NLAW does get a small direct attack debuff from the NLAW module (400 from 500). Which I'd say for a player balances out the very powerful top attack mode.

@ZeusWrath Personally, a disposable LAT weapon shouldn't one hit a tank, so I feel the current damage system.

@PabstMirror in the onFired function for the NLAW module we check if the shooter is an ACE player, otherwise it's assumed to be AI and does some auto tracking calculations. At that point could we either have a boolean ACE setting to make it top attack, or use a CBA setting to give it a chance (0-100%) for AI to use top attack mode?

**Comment by ZeusWrath** [comment]
> @ZeusWrath Personally, a disposable LAT weapon shouldn't one hit a tank, so I feel the current damage system is pretty balanced.

Maybe you are right. But I would like to see a certain effect of randomness. I think sometimes weapons should have a chance to destroy the tank. Unfortunately in ACE3 we always get the same result

**Comment by ZeusWrath** [comment]
usefull info about NLAW:
http://saab.com/land/weapon-systems/support-weapons/NLAW/
It is worth noting that everywhere NLAW is positioned as a tank killer, however in Arma3 and in particular in ACE3 upon hit, it can never destroy the tank/

**Comment by tiapfy** [comment]
I tested the NLAW and I can say that in direct attack it is very inefficient. I shot an Otokar in the side and I didn't destroy a single wheel. Then I tested it with an Ifrit and I wasn't able to make it explode. After that, I shot a T-100 with the Top-Attack mode, I destroyed the turret and the tank "cooked-off".
It seems pretty clear that this launcher has to be balanced.

**Comment by bux** [comment]
```js
Vanilla
[
    ["HitBody","HitEngine","HitFuel","HitHull","HitLFWheel","HitLMWheel","HitLF2Wheel","HitRFWheel","HitRMWheel","HitRF2Wheel","HitRGlass","HitLGlass","HitGlass1","HitGlass2","HitGlass3","HitGlass4","HitGlass5","HitGlass6","HitLBWheel","HitRBWheel","",    "",     "",     "",     "",     "",     "HitTurret","HitGun","HitTurret","HitGun"],["karoserie","motor","palivo","palivo","wheel_1_1_steering","wheel_1_3_steering","wheel_1_2_steering","wheel_2_1_steering","wheel_2_3_steering","wheel_2_2_steering","","","","","","","","","","","light_l","light_l","light_l2","light_r","light_r","light_r2","otochlaven","otochlaven","",""],
    [1,         0,          1,        0.328238, 0.6,         0.6,         0.6,          0.624062,    1,           1,            0,          0,          0,          0,          0,          0,          0,          0,          0,           0,          0.697729,0.697729,0.686352,1,  1,      1,       0.228617,   0.228617,0,          0]
]

ACE3
[
    ["HitBody","HitEngine","HitFuel","HitHull","HitLFWheel","HitLMWheel","HitLF2Wheel","HitRFWheel","HitRMWheel","HitRF2Wheel","HitRGlass","HitLGlass","HitGlass1","HitGlass2","HitGlass3","HitGlass4","HitGlass5","HitGlass6","HitLBWheel","HitRBWheel","",    "",     "",     "",     "",     "",     "HitTurret","HitGun","HitTurret","HitGun"],["karoserie","motor","palivo","palivo","wheel_1_1_steering","wheel_1_3_steering","wheel_1_2_steering","wheel_2_1_steering","wheel_2_3_steering","wheel_2_2_steering","","","","","","","","","","","light_l","light_l","light_l2","light_r","light_r","light_r2","otochlaven","otochlaven","",""],
    [1,         0.360875,   0.839032, 0.209758, 0.8,         0.8,         0.8,          0.830055,    0.880362,    1,            0,          0,          0,          0,          0,          0,          0,          0,          0,           0,          1,     1,      1,      1,      1,      1,       0.406868,   0.406868,0,          0]
]
```
