### ISSUE TITLE
Rearming in Multiplayer seems broken

### ISSUE THREAD

**Issue by Mezilsa** [acemod/ACE3#5406]
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.3.1` (stable )
**ACE3 Version:** `3.10.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- ACRE
```

**Description:**
- It seems like that rearming in multiplayer seems broken in all three rearm settings.
- It works fine in singleplayer

**Steps to reproduce:**
- Create your 0815 Mission with a vehicle, soldier and rearmtruck
- shoot some ammo
- try to rearm and notice, that the succes hint after the loadingbar isn't appering in mp.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- none

**RPT log file:**
- can't acces rpt file

**Comment by PabstMirror** [comment]
This should be fixed via #5307 in the newer version 3.10.2

**Comment by Mezilsa** [comment]
That seems to work. Thanks for the fast answer.
