### ISSUE TITLE
Too much overcast causes automatic rain.

### ISSUE THREAD

**Issue by Devious780** [acemod/ACE3#5407]
**Arma 3 Version:** `1.72` (stable / rc / dev)
**CBA Version:** `3.4.0` (stable / dev + commit hash)
**ACE3 Version:** `3.10.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- Scenario (snow storm script)
```

**Description:**
- When trying to do a winter storm type of mission it seems that too much overcast is causing rain. I don't know if thats the actual issue but when running the snow storm script (link is below), and having Ace with CBA on then it rains along with the snow. But when I disabled ACE and ran the scenario again it worked beautifully. There was snow, wind and cool features that are supposed to happen. 

**Steps to reproduce:**
- 1. Have ace and CBA_A3 on.
 2. Download this script scenario. http://www.armaholic.com/page.php?id=31841
3. run the scenario.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Placed Modules:**
none

**Comment by kripto202** [comment]
I think that has always been an arma thing

**Comment by SilentSpike** [comment]
Overcast influences the likelihood of rain so the higher it is the more likely it will rain. Don't believe this is an ace issue, but I also don't know enough about our weather components to say for sure

**Comment by jonpas** [comment]
Arma thing, nothing we can do.
