### ISSUE TITLE
Map illumination breaks after restarting mission

### ISSUE THREAD

**Issue by yarhooty** [acemod/ACE3#5408]
**Arma 3 Version:** `1.72` (stable / rc / dev)
**CBA Version:** `3.4.0` (stable / dev + commit hash)
**ACE3 Version:** `3.10.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- RHS
- CUP
```

**Description:**
Upon restarting a single-player mission, or even loading a save, the map illumination feature does not seem to work at all. There is no dimming at night, and flashlights+map tools cannot be used. 

**Steps to reproduce:**
1. Play a single-player mission, such as Dynamic Recon Ops, at night. 
2. Verify the map is dimmed.
3. Restart the mission or load a previous save.
4. Observe that the map is no longer dimmed. 

**Where did the issue occur?**
- Single-player missions

**Comment by yarhooty** [comment]
Update: After removing NIArms Core (which I forgot to include) the issue MAY have been resolved

**Comment by yarhooty** [comment]
This issue continues to occur in Dynamic Recon Ops

**Comment by commy2** [comment]
To make sure, does this happen with only CBA and ACE on an unscripted mission?
If not, then what is the minimum requirement of mods and / or what mission does this occur?

**Comment by Xon2** [comment]
So this is happening on my side for the longest time also. I just tested this again with only CBA3 and ACE (both steam versions). If you start a mission, make a savegame and load that savegame from within the mission (without quitting to arma's main menu or quitting arma 3 alltogether, map illumination still works. But as soon as you quit the mission and resume it from arma's scenario menu, map illumination stops working. Its a really nice and immersive feature and it would be great to have this working even when finishing a mission the next day or whatever.
