### ISSUE TITLE
Medical: Repeatedly waking up for 2-3 seconds during treatment

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#541]
Testing Session 2015 04 12

When unconscious and beeing treated by someone the (curator, remote controlled) unit constantly woke and stood up for 2-3 seconds and immediately became unconscious again. Like 8-10 times in a row. Broke the carrying action.

**Comment by PabstMirror** [comment]
I think this is video of event: https://www.youtube.com/watch?v=z2RtS5btKo8
There maybe something in captivity that caused this as he stands up and starts to put his hands back.  He might be going into and out of conscious rapidly.

**Comment by Glowbal** [comment]
- [ ] Carry/Dragging should not stop when a unit wakes up (becomes very difficult to carry fading units)
- [ ] Improve adv fading in/out of unconscious in vitals.

This is a feature, but judging from that video it could be improved. Maybe keep the AI prone for a few more seconds before resetting the original unitPos.

**Comment by bux578** [comment]
> Maybe keep the AI prone

FYI: It was a remote controlled unit in that video.

**Comment by Glowbal** [comment]
Did the player stand up or did the character do that on it's own? If so, that was most likely surrender or captives.

**Comment by bux578** [comment]
> that was most likely surrender or captives.

I didn't try to stand up.

**Comment by Glowbal** [comment]
Should be fixed in #717
