### ISSUE TITLE
Incendiary grenades are unreliable on ammo boxes

### ISSUE THREAD

**Issue by CoxLedere** [acemod/ACE3#5410]
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.4.0` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
 AN-M14 Incendiary grenades are unreliable when it comes to destroying ammo boxes. Some of the larger ammo boxes such as NATO Supply Box (B_supplyCrate_F) or an FIA Ammo box with camo netting (Box_FIA family) will often times not be destroyed by incendiary grenades even when mere inches away from the box. The only way I've been able to increase the reliability of their use is to use advanced throwing to drop the grenade on top of the ammo box, but even this isn't a surefire way, as sometimes the grenade will clip through the model in odd ways, or will roll off of what appears to be an otherwise flat surface. (the NATO Supply Box is a perfect example of this, it's collision box appears to have an odd cone at the top of it instead of being flat)

With the Supply Box you can throw an incendiary grenade on one side, run to the other side and take damage from the incendiary grenade burning you, but the ammo box can come out untouched. You can roll a grenade underneath the camo netting of the FIA Boxes and the box will be untouched as the grenade burns.

**Steps to reproduce:**
1. Place down an Ammo Box, preferably a NATO Supply Box or one of the FIA variants with camo netting.
2. Throw an incendiary grenade at the box.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
No errors in the RPT, but I've included it for completeness.
[rpt.txt](https://github.com/acemod/ACE3/files/1206282/rpt.txt)

**Comment by JoramD0** [comment]
This was improved with the above referenced PR.
