### ISSUE TITLE
floating medical junk

### ISSUE THREAD

**Issue by badkneegrow** [acemod/ACE3#5412]
On all versions without no mods and all mods the medical junk does not drop/destroy when a building is destroyed.
Medical junk missing physx

http://i.imgur.com/VjsKqbO.jpg

**Comment by commy2** [comment]
Med junk will never have PhysX, but maybe there could be made a scripted work around using the https://community.bistudio.com/wiki/Arma_3:_Event_Handlers/addMissionEventHandler#BuildingChanged
event handler.
