### ISSUE TITLE
ace_ragdoll is outdated with the newest version.

### ISSUE THREAD

**Issue by Strompey** [acemod/ACE3#5417]
Whenever I spawn in a server of my own I keep on getting the "ace_ragdoll, PBO is outdated" even tho I installed the newest one, _twice_. I can't play for myself or even with others that have the mod installed.

What do I do to fix this "bug" if it even is one?

**Comment by kripto202** [comment]
Where are you downloading the mod? Are you hosting the server on your computer? Are you trying to connect to a dedicated server? When was the server last updated? Where did the server get the mod? Has anything changed in the files between you or the server?

**Comment by commy2** [comment]
Delete ace_ragdoll.pbo. To update a mod, don't drag and drop the new folder over the old. That way, removed files from the old version will be kept when they should have been deleted!
Always delete the folder of the old version first.

**Comment by ZeusWrath** [comment]
I remembered the old versions of ACE.  It looks like you've removed ace_ragdoll.pbo? 

 I'm sorry, because the old ACE3 versions did not allow to see the vanilla ugly animations of the soldiers nit-reaction. Please try to return ace_ragdoll.pbo!

**Comment by jonpas** [comment]
@Strompey did you resolve the issue?

**Comment by Strompey** [comment]
Sorry for not responding to anything. I couldn't log in for some reason.
I got everything to work once again. Whenever I did something Arma 3 said the mod file got corrupted and repeated the process with slight tweaks until it worked. 

Now the only problem that I can play with, is the RHS USAF and the russian one (can not remember the name, hence the fact I didn't say it) They are just outdated by .2 updates. Isn't a MUST fix, more like an "Ok but not required" fix.

@commy2's advice helped a bit, not everything, but some.

To answer @kripto202's questions, all I can say is I got them from the official site, but used the workshop version as a start and worked it up from there.

Thank all of you for trying to help me out.

-Strompey.

**Comment by jonpas** [comment]
> Now the only problem that I can play with, is the RHS USAF and the russian one (can not remember the name, hence the fact I didn't say it) They are just outdated by .2 updates. Isn't a MUST fix, more like an "Ok but not required" fix.

You have to copy those from the `optionals` folder to the `addons` folder, just like you did first time.

**Comment by PabstMirror** [comment]
Let us know if you are still having problems,
you can always get the latest version here: https://github.com/acemod/ACE3/releases/latest
Not a bad idea to delete the folder and extract a fresh copy for every update
