### ISSUE TITLE
Cannot use Designator or Rangefinder (Calculation of current Distance)

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5419]
**Arma 3 Version:**  1.74 (stable)
**CBA Version:** 3.4.0 (stable )
**ACE3 Version:** 3.10.2 (stable)

**Mods:**
- CBA_A3
- ace
- JSRS4 sound mod

**Description:**
- Before, in the ACE3, when I use the Laser Designator or Rangefinder, I could see the distance to the designated target, but now I can not see it.  Earlier this worked with the "Tab" or Left mouse button, but now I can not find a way to make these devices show me the current distance. In the ACE settings, I did not find these options. How can I calculate the distances to the goal? Or this is bug? 

**Steps to reproduce:**
- use these devices and try calculated range

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**

- not needed

**Comment by PabstMirror** [comment]
See https://github.com/acemod/ACE3/pull/5152

They are now handeld by vanilla arma, you need to press lase target key (I think T or shift T default)

**Comment by ZeusWrath** [comment]
> They are now handeld by vanilla arma, you need to press lase target key (I think T or shift T default)

No! this not will work

**Comment by ZeusWrath** [comment]
> See #5152

yes I understand. They just added a custom button.

Thank you, the ticket can be closed ...
