### ISSUE TITLE
Sometimes, the opened map, does not match the current time of day. (level of brightness)

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5420]
**Arma 3 Version:** 1.74 (stable)
**CBA Version:** 3.4.0 (stable )
**ACE3 Version:** 3.10.2 (stable)

**Mods:**
- CBA_A3
- ace
- JSRS4 sound mod

**Description:**
- I remember, the old versions of ACE3 did not have this issue. Simulation of the day  time on an opened map worked adequate. But now, (in the latest versions of ACE3), very often, the map does not match the current time of day at general.  
For example, in the dark (late evening or early dawn) the opened map is completely light, as during a bright day.  But as soon we leave the map mode, we see almost total darkness.

I made video:  https://www.youtube.com/watch?v=GjTdEIFbNWo&feature=youtu.be

**Steps to reproduce:**
- open your map at the sunrise or sunset. When it's almost dark or when it's already dark.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- none

**RPT log file:**
- not needed

**Comment by dedmen** [comment]
See last comment of https://community.bistudio.com/wiki/sunOrMoon
BI's Fault.

**Comment by commy2** [comment]
https://forums.bistudio.com/forums/topic/151099-scripting-discussion-dev-branch/?page=53#comment-3224827

**Comment by ZeusWrath** [comment]
Hey dudes can't fix it? 

https://www.youtube.com/watch?v=GjTdEIFbNWo&feature=youtu.be

**I don’t know why you wrote that it was BIS fault. I remember a time, when there was no such problem - So it’s possible to configure it correctly! The degree of dimming of the map has a sufficient numbers of gradations, you just need to create a time interconnection. If you can’t fix it, then just delete this blackout map as it looks really stupid...**

Thanks for your efforts!

**Comment by jonpas** [comment]
The command got broken in one of the updates. Nothing we can do.

**Comment by ZeusWrath** [comment]
Do you mean the BIS Scripting command? I hope you used feedback to report this

**Comment by jonpas** [comment]
Did you read the comments from other people above?

**Comment by dedmen** [comment]
The command is bugged, I already looked into it but couldn't fix it. So this command won't be fixed.

Instead there will be new script command which returns current ambient lighting, which will work much better and easier and more reliably.
