### ISSUE TITLE
Option to leave all intercom channels

### ISSUE THREAD

**Issue by Pergor** [acemod/ACE3#5425]
**ACE3 Version:** `3.10.2` (stable / dev + commit hash)

Currently you can only switch between crew and cargo in the intercom. 
An option to leave all intercom channels would be nice (for example if you have to use a radio while in a vehicle without wanting to hear all people babbling on and on).

**Comment by bux** [comment]
You might want to report that over at TFAR.

**Comment by Pergor** [comment]
Ha! I knew I clicked the wrong link. :D
