### ISSUE TITLE
How to explicite deleting things (objects) while they are stored in Cargo ?

### ISSUE THREAD

**Issue by markooff** [acemod/ACE3#5429]
Hello, 

I'm sorry if the solution for this problem is really very easy , but I've read the whole ACE3 Framework API documentation and couldn't find the answer . It looks like there is no such function at all , or there is, but not documented yet.... 

I've made the little (but nice :) ) logistic system for my team (and its training issues ) and I need to provide them with the containers which are filled up with the equipment I've chosen. Everithing works all right, but the problem is when I try to use the loop for repetively refilling this container, because the new things I've load in this loop succesively increase the amount of the cargo , and I only want to overwrite the old things with the new things on each loop pass. 

My loop (added to the init of the containeer) looks like : 
```
if (! isServer) exitWith {};

_container = _this select 0;
_refreshTime = 360;

while {alive _container} do
{

["Box_mas_ru_rifle_Wps_F", _container] call ace_cargo_fnc_loadItem;
["Box_mas_nw_rifle_Wps_F", _container] call ace_cargo_fnc_loadItem;
["Box_mas_us_rifle_Wps_F", _container] call ace_cargo_fnc_loadItem;
["Box_mas_all_rifle_Wps_F", _container] call ace_cargo_fnc_loadItem;
["TF_NATO_Radio_Crate", _container] call ace_cargo_fnc_loadItem;
["ACE_medicalSupplyCrate_advanced", _container] call ace_cargo_fnc_loadItem;
["ACE_medicalSupplyCrate", _container] call ace_cargo_fnc_loadItem;
["ACE_Box_Misc", _container] call ace_cargo_fnc_loadItem;
["ACE_Box_Ammo", _container] call ace_cargo_fnc_loadItem;
["Box_NATO_AmmoOrd_F", _container] call ace_cargo_fnc_loadItem;
["Box_NATO_Grenades_F", _container] call ace_cargo_fnc_loadItem;
["ACE_Box_Chemlights", _container] call ace_cargo_fnc_loadItem;
["Box_NATO_AmmoVeh_F", _container] call ace_cargo_fnc_loadItem;

sleep _refreshTime;
};
```

So I probably need to use first in my loop  the function similiar to 
`clearItemCargoGlobal _crate;` 
but this function comes from bohemia and works with objects like crate (box, etc)
and touches its inwentory , not  a cargo space. 

In the ACE Framework docs - I've found some very usefull  functions for loading , unloading, changing cargo space etc, but there's no fuction for deleting (cleaning up ) the whole cargo space , documented yet. 

And his is my question - if there is such function in ACE Cargo Framework and how to use it ?

Thank you from advance for help :)

//markooff

**Comment by bux** [comment]
You can get an idea from here:
https://github.com/acemod/ACE3/blob/master/addons/cargo/functions/fnc_handleDestroyed.sqf

**Comment by markooff** [comment]
Thank You very much **bux**,

I'll try with this function and hope it'll works pretty good :) 

THX

**Comment by bux** [comment]
This function will delete ALL objects stored in cargo and it's not designed to be called from external.

**Comment by markooff** [comment]
ehm , but i'm not sure if I'm using it in the right way, because I'm a bit newbe in SQF scripting (the language isn't as similiar to C++ or Java as I've thought before) 

I've tried to put this construction in my loop and now it looks like :  
`while {alive _container} do
{
//[_container, -1] call ace_cargo_fnc_setSize;
//sleep 2;
//[_container, 50] call ace_cargo_fnc_setSize;


private _loaded = _container getVariable [QGVAR(loaded), []];

if (_loaded ! isEqualTo []) {
			// TODO Do we want to be able to recover destroyed equipment?
			if (_x isEqualType objNull) then {
			deleteVehicle _x;
			};
			nil
		} count _loaded;

		[_container] call FUNC(validateCargoSpace);
		

sleep 5;

["Box_mas_ru_rifle_Wps_F", _container] call ace_cargo_fnc_loadItem;
["Box_mas_nw_rifle_Wps_F", _container] call ace_cargo_fnc_loadItem;
["Box_mas_us_rifle_Wps_F", _container] call ace_cargo_fnc_loadItem;
["Box_mas_all_rifle_Wps_F", _container] call ace_cargo_fnc_loadItem;
["TF_NATO_Radio_Crate", _container] call ace_cargo_fnc_loadItem;
["ACE_medicalSupplyCrate_advanced", _container] call ace_cargo_fnc_loadItem;
["ACE_medicalSupplyCrate", _container] call ace_cargo_fnc_loadItem;
["ACE_Box_Misc", _container] call ace_cargo_fnc_loadItem;
["ACE_Box_Ammo", _container] call ace_cargo_fnc_loadItem;
["Box_NATO_AmmoOrd_F", _container] call ace_cargo_fnc_loadItem;
["Box_NATO_Grenades_F", _container] call ace_cargo_fnc_loadItem;
["ACE_Box_Chemlights", _container] call ace_cargo_fnc_loadItem;
["Box_NATO_AmmoVeh_F", _container] call ace_cargo_fnc_loadItem;

sleep _refreshTime;
};`

Perhaps I didt it wrong way , but as I can understand the count sentence act as the sort of loop here 
and _x is the current element of each loop pass , isn't it ?

**Comment by 654wak654** [comment]
Some of the code you used like `QGVAR(loaded)` and `FUNC(validateCargoSpace)` are preprocessor macros, which work almost exactly the way they do in C++. Their usage is documented [here](https://ace3mod.com/wiki/development/coding-guidelines.html#21-modulepbo-specific-macro-usage). They are declared in ACE's header files, and unless you include the right headers too, those lines should throw script errors (You should [_really_ use](https://community.bistudio.com/wiki/Arma_3_Startup_Parameters#Developer_Options) `-showScriptErrors` when testing scripts!). The correct way to use that function would be to write `ace_cargo_fnc_validateCargoSpace` for you, and the string for getVariable would be `"ace_cargo_loaded"`.

**Comment by SilentSpike** [comment]
A public API function to do this operation should probably be added 👍

**Comment by 654wak654** [comment]
Think #5432 might close this.

**Comment by markooff** [comment]
Yes, sure things,
anyway thank you esp. for commenting my post and for all advices !

**Comment by jonpas** [comment]
@markooff I strongly suggest you join the ACE3 Slack (link on front page of this repository), as it is a lot easier to explain something when you can chat in real-time. ;)
