### ISSUE TITLE
The function to refill the fuel_truck or for transfer the fuel from one fuel tank to another

### ISSUE THREAD

**Issue by markooff** [acemod/ACE3#5434]
Hello again  :) 

For some time I think about the possibility to transfer the fuel , but not only as a refuel function (i.e. from the fuel truck fuel_Cargo space directly to the vehicle's fuel tank ) but also for a possibility to : 
**1) transfer some fuel from the bigger fuel cargo vehicle** (for instance "StorageBladder_01_fuel_forest_F" ) **to a smaller** (like "B_Truck_01_fuel_F" or "FlexibleTank_01_forest_F" ) 
and 
**2) transfer the fuel from fuel tank of one vehicle** ( big car, big boat - for instance "rhsusf_mkvsoc" ) witch can have a lot of fuel **directly into the fuel tank of smaller** boats(cars) like "B_SDV_01_F" or "B_Boat_Transport_01_F" or (on land) B_"Quadbike_01_F" etc ...

This will be a great improvements for logistic in Arma3 with ACE3 mod combination - because it shows more precisely what we can do with the fuelling in the real (military) world . 
The 2) functionality is more important if You 're working with the sea/undersea oriented forces and tasks (for instance in my team we have a small but very important sea assault and recon teams , and we have always problems with the range of SDV vehicles..... and because fuel truck cannot be 'attached' or put onto the Mk.V boats :) - so it is almost useless for us ) 

Anyway , there was a special function in ACE 2 mod - which works a bit like  the 2) - you can remember the possibility to transfer the fuel to and from the vehicle using the jerry can ... I (and a lots of people I know)  think - this was great ! Maybe there is a good reason to copy it and start using in ACE 3 mod ? 

Of course we (I mean - we, mission makers) sometimes  can deal with these issues using mixture of some sorts of triggers combined with the set/get fuel functions (and that's what we're really do) , but, i think there are a lots of people who cannot do this such way, and who could take a big advantage of such improvement. 

Thanks from advance :)

**Comment by Griiis** [comment]
Does anyone looked into this request? I very very require functional to refill fuel barrels and sipone fuel from cars.

**Comment by dedmen** [comment]
See https://github.com/acemod/ACE3/pull/7039
