### ISSUE TITLE
Help erquest: check if Blue Force Tracking is active

### ISSUE THREAD

**Issue by celticalliance** [acemod/ACE3#5435]
**Arma 3 Version:** `1.74` (stable)
**CBA Version:** `3.4.0` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
I am trying to discover how I can check if the Blue Force Tracking feature is running. The reason for this is we want to disable certain scripts if it is. I am aware of how to check if ACE modules are enabled and running, but I'm wondering if there is a similar way to check if Blue Force Tracking is enabled?

**Steps to reproduce:**
None

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
None

**RPT log file:**
None needed

**Comment by PabstMirror** [comment]
There will be a ace_setting variable for it: `ace_map_BFT_Enabled`
Settings aren't always final until a little bit after postInit, so here is an example to safely check:
```
["ace_settingsInitialized", {
    diag_log format ["ACE BFT enabled: %1", ace_map_BFT_Enabled];
}] call CBA_fnc_addEventHandler;
```
Could also do `[] spawn {sleep 1;  if (ace_map_BFT_Enabled) then {...}};`
