### ISSUE TITLE
How to place and configure ACE modules via script ?

### ISSUE THREAD

**Issue by Gemini69** [acemod/ACE3#5436]
Hi,

I would like to make ACE available as an option in a mission. For example, if ACE is installed on a server, then the mission switches from default ArmA medical system to ACE one.

Is it possible to do it in a script instead of using modules in the editor (which would create ACE dependency) ? Is there a way to activate ACE modules (ACE_moduleMedicalSettings...) and to set up relative parameters (medical simulation level...) ?

Maybe something like this:

if (isClass (configFile >> "CfgPatches" >> "ace_medical")) then 
{
ACE_moduleMedicalSettings = true; // to activate the module
ACE_moduleMedicalSettings_medicSetting = "advanced" // to select advanced system
};

_I suppose these variables and values are incorrect but it's for the example_.

That would be very helpfull.

Thank you very much for your help,

Gemini

**Comment by 654wak654** [comment]
You could use the [Settings Framework](https://ace3mod.com/wiki/framework/settings-framework.html).

**Comment by Gemini69** [comment]
That's precisely what I was looking for depiste my research. Thank you buddy.

**Comment by Gemini69** [comment]
I found that it's possible to enable/disable some ACE features just by changing a variable. Example: 
ace_nightvision_disableNVGsWithSights = 0; // optic + NVG is authorized 
ace_nightvision_disableNVGsWithSights = 1; // optic + NVG is not authorized

But some others don't work. Example: 
ace_goggles_effects = 0;
ace_goggles_effects = 2;
Whatever the value, it doesn't seem to have any effect.

So I wonder if it's possible to edit every ACE parameters "on-the-fly" ?

**Comment by jonpas** [comment]
> So I wonder if it's possible to edit every ACE parameters "on-the-fly" ?

No, it's not.

**Comment by SilentSpike** [comment]
When we switch to CBA settings it may be possible to change some on the fly. Depends on the final implementation.

**Comment by Gemini69** [comment]
Hi SilentSpike and thank you for your reply. 

I'm not sure to understand what you mean. The idea is to let the player enable/disable some ACE features through a customed parameters screen at mission start-up (because BI's one is not available for SP). So I would need to force some ACE variables according to player's choice... which works for some features (e.g.: NVG with sights) but doesn't for some others (e.g.: goggles effets, deafness...).

**Comment by commy2** [comment]
It's a hypothetical that's not possible atm.

**Comment by Gemini69** [comment]
OK I understand, thank you guys.
