### ISSUE TITLE
Captives: Error in rpt

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#544]
Testing Session 2015 04 12

```
23:45:47 1:59:53.227 (7300.02) [z\ace\addons\captives\functions\fnc_setHandcuffed.sqf:56] -ERROR- ERROR
23:45:47             Handcuff animation interrupted 
```

(probably interrupted due to waking up from unconsciousness)

**Comment by PabstMirror** [comment]
Shouldn't have been labeled as an ERROR, it's semi-normal for those messages to happen.
