### ISSUE TITLE
overheating system overhaul

### ISSUE THREAD

**Issue by kOepi123** [acemod/ACE3#5443]
**Arma 3 Version:** `stable
**CBA Version:** stable
**ACE3 Version:** `stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- This suggests a more realistic use of weapons and their capabilities, also balances
the game more.

**Issues with current overheating system:**
- overheating is depending on bullet mass
- it does not matter which weapon I choose, I run out of ammunition before overheating takes
effect. There is no point in using the spare barrel.

**Overview of overhaul**
1. make two more spare barrels with different weights. LMG, MMG and HMG
2. remove weapon temperature indicator and replace with text and / or overheating effects
3. replacing overheating with exponential function
a) add new ace component "ACE_barrel_weight", "ACE_cooling_coefficient" and "ACE_bore_surface" which has to be set in the weapon config
4. cooling with linear function

table: https://ibb.co/hK1OGk

optional ( or later ):
5. handguard too hot => inability to aim properly
6. hot barrel results in drastic drop of rate of fire 
( cartridge does not seal the barrel and gas system anymore )
7. barrel breaks according to the rupture values
8. make cooling coefficient and ace_bore_surface to reduce calculation ressources

** General understanding **
The values shown, balanced and compared are not 100% scientifically correct.
Differences in hardness, steel quality, ergo modern and classic weapon engineering
is not considered an important factor to be simulated.
E.G.: An M4 of the 90s will break quite a lot later than an M16A2 from those days, even
when the barrel is shorter and lighter.
- Overheating is calculated up to 840 °C, then it will fail by rupturing the barrel.
- Cooling is simplified to linear, since it only becomes really different above 630 °C
this punishes those who fire even higher than those temperatures, because it will take
forever to cool down
- the optimal barrel change temperature is designated as 200°C, which is not accurate, but the outcome is.
- the rupture value is a theoretical value with one continues burst.
- a continous use of changing barrel is deemed unrealistic. having a sustained rate of fire over a period
of 6 or 10 minutes and to let a hot barrel recover fully in that same period is not possible.
You can switch them again, but they wont be fully cooled down.
- the increments are measured in parts, instead of a temperature.
This simplifies calculations and can reduce needed calculations workload
So instead of 840°C, it would be:
current_barrel_energy / Energy_Max

1. spare barrel weights for LMGs, MMGs and HMGs:
1,445 kg, 3,05 kg and 10,9 kg.

2. texts like "cannot touch handguard", "spare barrel is hand temperature", "barrel is glowing"
indicate the temperature of the active barrel and the spare barrel.
As soon as the air above the active barrel starts flimmering indicates that the barrel is too hot to be
shot any further. Smoke effect can also indicate this.

3. Overheating function:
Energy amount until the barrel breaks/ruptures at 840°C:
Energy_Max [kJ] = rounds^1,0041
Energy_O_Incr [kJ/rd] = 1[rd] ^1,0041 = 1,0041 kJ/rd
Energy_Max [kJ] = 0,5  * ace_barrel_mass [kg] * 840 [°C]
Energy_Opt [kJ] or [rds] = 0,5 * ace_barrel_mass [kg] * 200 [°C] = continous round burst to reach 200°C

Update probably every shot or every second shot.

4. cooling function:
the weapon specific cooling factor can also be inherited in the weapon config: 
ace_cooling_coefficient = 1 / ace_barrel_mass [kg] * ace_bore_surface [m²]
ace_bore_surface [m²] = caliber [m] * 3,1416 * ACE_barrel_length [m]
Energy_C_Incr [J/sec] = ace_cooling_coefficient / 0,0093 * 301,3 [J/s]

Update with the active barrel: every second.
Update with the spare barrel: every minute.

5. the handguard temperature is roughly at 110 °C when the barrel temperature is at 840 °C.
suggested maximal handguard temperature to be able to fully operate the weapon would
be up to 40 °C.
6. reaching 71% of Energy_Max, the rate of fire would drop interpolated to half, when firing is continued.

7. when energy_max is reached weapon is broken, or the barrel is destroyed, but can still be swapped.

8. I think having precalculated new ace_values will minimize needed calculations to some extent.

edited:
If someone can make the framework for this, I can tweak and test the settings until they are perfect.

**Comment by commy2** [comment]
There is no need to update the barrels every second or minute, or at all in a loop.

**Comment by badkneegrow** [comment]
Can I put in a suggestion for overheating / jamming here?
I don't think these would be ~THAT~ hard to do...


Custom jamming values per guns?
Weather?
Terrain + wind? (sand on takistan with strong winds)
more sand when prone...

Ability to add oil to guns? (would not jam as much? decrease effect of sand)

Custom coef for settings (increase jamming / dispersion through module/setting/variable?)

**Comment by kOepi123** [comment]
@badkneegrow 
please do another ticket for this, this ticket is already very big and my jam suggestion ticket is not even part of it. 
Just a personal note:
how much of that would actually make a difference?
I doubt that you can repair a firing pin in the field.
A runaway gun or misfire would have way more impact in my opinion.

**Comment by badkneegrow** [comment]
> I doubt that you can repair a firing pin in the field.
Open up the gun and replace the firing pin. I guess it's fixing the problem not the firing pin. And yes, it can be done in any conditions. For most guns it can be done without a toolkit, just need a spare pin.

> Misfires
Aren't misfires are rare with modern firearms ?
A misfire if a gun is too hot, possibly...
