### ISSUE TITLE
Allow items to be used from inventory

### ISSUE THREAD

**Issue by Emton** [acemod/ACE3#5449]
Hello this is a feature request sorry if it's in the wrong place. I was thinking it would be cool to be able to use items from the inventory by double clicking on the item, stuff like the Kestrel, rangecard, ear plugs etc what you think of that too crazy?

**Comment by kripto202** [comment]
all feature requests goes here #3594

**Comment by jonpas** [comment]
It is already linked to that thread, so there is no need to post it there again. But for future request, #3594.
