### ISSUE TITLE
Entrenching Tool/ Sandbags not working on Malden 2035

### ISSUE THREAD

**Issue by Rixyl** [acemod/ACE3#5450]
Fully Updated

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
-Sandbags and Entrenching tool don't seem to be working on the new Malden 2035 map. Everywhere else it works perfectly fine.

**Where did the issue occur?**
- Singleplayer Malden 2035

**Comment by jonpas** [comment]
Different surfaces I assume.
