### ISSUE TITLE
fix to bleeding effect not showing up (sometimes)

### ISSUE THREAD

**Issue by Tennessee-Timmy** [acemod/ACE3#5451]
Sometimes player report bleeding effect not showing up on them, here's a fix

https://github.com/acemod/ACE3/blob/ffaa195fe576625f052eeee04b1af9f3f377434f/addons/medical/functions/fnc_showBloodEffect.sqf#L27

replace with
if (count _fxBloodControls != 3 || {(_fxBloodControls param [0]) isEqualTo controlNull}) then {

**Comment by dedmen** [comment]
>here's a fix

You know there are pull requests? Right?
