### ISSUE TITLE
AddItemCargoGlobal isn't working with ACE3 3.10.2

### ISSUE THREAD

**Issue by hoswell15** [acemod/ACE3#5454]
**Arma 3 Version:** `1.74.142559` (stable / rc / dev)
**CBA Version:** `3.4.0` (stable / dev + commit hash)
**ACE3 Version:** `3.10.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
This scripts below worked until ACE3 version 3.3.1, then i updated to 3.10.2 now not working.

// Only run for the server, the important part
if (!isServer) exitWith {};

//Clearing the box
clearWeaponCargoGlobal _this;
clearMagazineCargoGlobal _this;
ClearBackPackCargoGlobal _this;
ClearItemCargoGlobal _this;

//Ferramentas
_this additemcargoGlobal ["ToolKit",2];

//MedKits
_this addItemCargoGlobal ["ACE_fieldDressing", 20];
_this addItemCargoGlobal ["ACE_elasticBandage", 20];
_this addItemCargoGlobal ["ACE_packingBandage", 20];
_this addItemCargoGlobal ["ACE_quikclot", 20];
_this addItemCargoGlobal ["ACE_tourniquet", 20];
_this addItemCargoGlobal ["ACE_personalAidKit", 20]; 

**Steps to reproduce:**
- The scripts is in Vehicle init called by this code:
nul = this execVM "scripts\veiculo_transp.sqf";

Also i tried directly in vehicle init use code but not work:
this addItemCargoGlobal ["ACE_personalAidKit", 20]; 

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer) 

**Placed Modules:**
- None

**RPT log file:**
0:41:42 "[Auto-load ""Estepe"" in """"] : There is not enough space for this object in this vehicle !"
 0:41:42 "[Auto-load ""Estepe"" in """"] : There is not enough space for this object in this vehicle !"
 0:41:42 "[Auto-load ""Estepe"" in """"] : There is not enough space for this object in this vehicle !"
 0:41:42 "[Auto-load ""Estepe"" in """"] : There is not enough space for this object in this vehicle !"
 0:41:42 "[Auto-load ""Estepe"" in """"] : There is not enough space for this object in this vehicle !"
 0:41:42 "[Auto-load ""Estepe"" in """"] : There is not enough space for this object in this vehicle !"

It show when i join mission and in .rpt

**Comment by hoswell15** [comment]
I am running ACE, ALIVE, RHS, CUP, MCC.

**Comment by jonpas** [comment]
Try it with only CBA+ACE3, any mod could be a problem.

**Comment by hoswell15** [comment]
Ok i tried everything, all vehicles that have Cargo system show error the cargo has no space.. and i cant add any item to the vehicle, only rhs vehicles working loadouts because they dont have Cargo system.. 

So.. how i can change the cargo size? i tried everything

**Comment by hoswell15** [comment]
Fixed: Was the Vehicle Respawn.. was forced then the vehicle start without loadout ! :@
