### ISSUE TITLE
battleye ace_medical_x64.dll

### ISSUE THREAD

**Issue by blackvenom2** [acemod/ACE3#5458]
15:31:35: Starting BattlEye Service...

15:31:37: Launching game...
15:32:29: Note: File blocks can be ignored if they don't cause problems with the game.
15:32:29: [INFO] Blocked loading of file: "E:\Program Files (x86)\Steam\steamapps\common\Arma 3\@ace\ace_medical_x64.dll".

got this every start today,
any solution?

**Comment by blackvenom2** [comment]
add:

some more blocks in place

15:31:35: Starting BattlEye Service...

15:31:37: Launching game...
15:32:29: Note: File blocks can be ignored if they don't cause problems with the game.
15:32:29: [INFO] Blocked loading of file: "E:\Program Files (x86)\Steam\steamapps\common\Arma 3\@ace\ace_medical_x64.dll".
15:32:47: [INFO] Blocked loading of file: "E:\Program Files (x86)\Steam\steamapps\common\Arma 3\@ace\ace_break_line_x64.dll".
15:32:57: [INFO] Blocked loading of file: "E:\Program Files (x86)\Steam\steamapps\common\Arma 3\@ace\ace_parse_imagepath_x64.dll".
15:33:07: [INFO] Blocked loading of file: "E:\Program Files (x86)\Steam\steamapps\common\Arma 3\@ace\ace_clipboard_x64.dll".

**Comment by badkneegrow** [comment]
Have you tried disabling battleye?

If battleye is a must, this helped me:
1. Disable battleye
2. Run game
3. Close game
4. Enable battleye
5. Run game

**Comment by blackvenom2** [comment]
restarting arma about 10 times did get it to work somehow, and yes be is a must.

**Comment by badkneegrow** [comment]
Battleye is also used by popular game PUBG. (800k players peak every day)

I speculate that this is causing too much stress on BE servers and if BE can't confirm the DLL is legit, it is automatically BLOCKED!

**Comment by jonpas** [comment]
Answers can be found in old issues https://github.com/acemod/ACE3/issues?q=label%3A%22fault%2FBattle+Eye%22+is%3Aclosed. Nothing we can do about it, steps posted above by @badkneegrow is the best you can do, or just keep trying if the server runs BattlEye.
