### ISSUE TITLE
SSWT kit placement animation

### ISSUE THREAD

**Issue by neetch1** [acemod/ACE3#5460]
**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- I'd like to request a change of animation for the sswt kit into the standard placement animation. Right now the animation used very stuttery and not very smooth. Don't know if you will agree or not but hopefully you'll consider this.
Thanks

**Comment by Emton** [comment]
I agree it looks a bit choppy but the problem is it tips over easy on a lot of surfaces especially on rocks even if they're pretty flat, and it can tip over on you and hurt you! I got hit by the sswt and now I'm injured and the weapon sway is all over the place even after using a first aid kit.
