### ISSUE TITLE
How to get correct C1 coefficient for a gun?

### ISSUE THREAD

**Issue by Emton** [acemod/ACE3#5462]
The wiki says to go to 
configfile » “CfgAmmo” » “Range card cartridge” » “ACE_ballisticCoefficients” https://ace3mod.com/wiki/feature/atragmx.html#35-example-with-add-new-gun-in-gunlist
in the Eden config viewer but there is no "Range card cartridge" in the list. I'm trying to get the correct settings for the Mk11 and I think I got everything except C1 coefficient. Also do suppressors affect the ballistics and if so how do I take those into account?

**Comment by Laid3acK** [comment]
Hi,
the "range card cartridge" at the top left of your range card with the **Advanced Ballistics module enabled**.

-Example here `ACE_408_Ball` :
https://ace3mod.com/img/wiki/feature/atragmx5.png

Vanilla suppressors have no effect on the ballistic:
https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgWeapons.hpp#L643

If in a part of a mod, depends how they are configured.

**Comment by Emton** [comment]
Ohkay I still haven't tried changing the C1 coefficient number yet but I tried different ammo that gets better results, but that M118 I can't seem to get it correct not sure why. Also if you or anyone else knows, is there an entry in the Atrag for the barrel length? I don't think I've seen it (but I figured it would be important)

**Comment by Laid3acK** [comment]
>is there an entry in the Atrag for the barrel length? I don't think I've seen it (but I figured it would be important)

No, there isn't because the most important is the muzzle velocity which depends on many parameters.

**Comment by ulteq** [comment]
The predefined G1 coefficients are optimal. Adjustments only make sense if you want to shoot beyond the supersonic range.

**Comment by BaerMitUmlaut** [comment]
Can this be closed?

**Comment by bux** [comment]
yes
