### ISSUE TITLE
Script error on dogtag collection

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#5471]
**Arma 3 Version:** last version
**CBA Version:** ` last version
**ACE3 Version:** `3.10.2

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- when check dogtags has error script
http://joxi.ru/Vm64Zwoix0WWlA
http://joxi.ru/52aBgKlCGZQQOA

**Steps to reproduce:**
check dogtags

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**RPT log file:**
private _inputChar = _chars select (_index % _length);
_nums set [(_>
12:53:57   Error position: <select (_index % _length);
_nums set [(_>
12:53:57   Error РґРµР»РёС‚РµР»СЊ РЅСѓР»СЏ
12:53:57 File z\ace\addons\dogtags\functions\fnc_ssn.sqf, line 15
12:53:57 Error in expression <ength) do {
private _inputChar = _chars select (_index % _length);
_nums set [(_>
12:53:57   Error position: <select (_index % _length);
_nums set [(_>
12:53:57   Error РґРµР»РёС‚РµР»СЊ РЅСѓР»СЏ
12:53:57 File z\ace\addons\dogtags\functions\fnc_ssn.sqf, line 15
12:53:57 Error in expression <ength) do {
private _inputChar = _chars select (_index % _length);
_nums set [(_>
12:53:57   Error position: <select (_index % _length);
_nums set [(_>
12:53:57   Error РґРµР»РёС‚РµР»СЊ РЅСѓР»СЏ
12:53:57 File z\ace\addons\dogtags\functions\fnc_ssn.sqf, line 15
12:53:57 Error in expression <ength) do {
private _inputChar = _chars select (_index % _length);
_nums set [(_>
12:53:57   Error position: <select (_index % _length);
_nums set [(_>

**Comment by SilentSpike** [comment]
I believe this is related to how arma handles certain characters. The conversion of the name string `toArray` produces an array which doesn't match the length of the original string.

**Comment by commy2** [comment]
Please post the full RPT file and not just parts.
Can you copy paste the Arma name this happened with too? Thanks.

**Comment by topden** [comment]
https://yadi.sk/d/ELzuiqbd3MZKRd
total rpt

take AI from vanilla
kill him
check dogtags
play sp or mp without ace modules -default

**Comment by PabstMirror** [comment]
Cyrillic in arma is some kind of unicode hell
```
count "Р»СЏ" = 8
toArray "Р»СЏ" = [1056,187,1057,1039]
("Р»СЏ") select [0,1] = "�"
("Р»СЏ") select [1,1] = "�"
("Р»СЏ") select [0,2] = "Р"
```

Wouldn't be suprised if this breaks something else, so let us know.
