### ISSUE TITLE
russian text error

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#5472]
all last versions mods cba+ace

 i take "Adenosine" http://joxi.ru/EA44LwoiDZ5L3A ("аденозин" on rus),
 but **in game** Adenosine have russian name of Atropine http://joxi.ru/gmvlpEWTxBG54A 
Its bug, becouse when i use it, i can see this http://joxi.ru/DmBZ8dPUNPk00m (Adenosine )
Change pls атропин on аденазин in peronaly med-menu

**Comment by SilentSpike** [comment]
Already fixed: https://github.com/acemod/ACE3/pull/5430
