### ISSUE TITLE
Invisable weapon on respawn

### ISSUE THREAD

**Issue by GuruTom** [acemod/ACE3#5474]
**Arma 3 Version:** `1.77` DEV
**CBA Version:** `3.4.0` Stable
**ACE3 Version:** `3.1.0.2` Stable

**Mods:**
```
CBA_A3
ace
RHSAFRF
RHSUSAF
NIArms Core
ACRE2
ACEX
ACE Compat - RHS United States Armed Forces
ACE Compat - RHS Armed Forces of the Russian Federation
Project OPFOR
NIArms P226 Pistols
Specialist Military Arms (SMA) Version 2.7.1
CUP Terrains - Core
CUP Terrains - Maps
VSM - Uniforms
VSM - Accessory Pack
VSM - Vests and Helmets
Military Gear Pack
MBG Buildings Killhouses (Arma3 Remaster)
Enhanced Movement
Eden Objects
3CB BAF Vehicles
Blastcore Edited (standalone version)
ShackTac User Interface
DynaSound 2
Enhanced Soundscape
Immerse	Steam
Vcom AI V2.8.1
```

**Description:**
- When Killed with your primary weapon in backpack & holstered pistol you re-spawn with a blank primary weapon and an error for a missing texture

**Steps to reproduce:**
- Setting mission respawn to 5 second delay and respawn on custom position (respawn_west marker)
- Adding ACE Respawn Settings Module with both options set to enable.
- Place Primary Weapon In backpack
- Holster Pistol
- Get someone to shoot you
- Respawn

**Where did the issue occur?**
- Dedicated server, Multiplayer

**Comment by commy2** [comment]
RPT file please.

**Comment by alec-hs** [comment]
I was there when this happened - cannot currently reproduce using just ACE and CBA. Above mod list is not complete. Will test further to see if caused by other mods. 

Also repro steps should include:

- Setting mission respawn to 5 second delay and respawn on custom position (respawn_west marker)
- Adding ACE Respawn Settings Module with both options set to enable.

**Comment by PabstMirror** [comment]
probably related to the savePreDeathGear setting

**Comment by commy2** [comment]
@PabstMirror 
https://github.com/acemod/ACE3/blob/master/addons/common/CfgWeapons.hpp#L15

**Comment by GuruTom** [comment]
@commy2 Tried to replicate this last night on the dedi to get a fresh RPT, couldn't get it to happen. Will keep trying to replicate a shoot an RPT as soon as it happens

**Comment by commy2** [comment]
Try respawning while dragging something without primary weapon.

**Comment by GuruTom** [comment]
@commy2 @PabstMirror Just managed to replicate on the dedicated server with @alec-hs.

![4ff7ed86bac9dc9ed8e9528ceee6610e](https://user-images.githubusercontent.com/3950254/30125302-e8bcc58e-932f-11e7-8ca9-a8cf6f59757b.jpg)

Pastebin of my RPT: https://pastebin.com/h6vh3Vb0

A note to add, we could only replicate this bug when being shot by another player on the server, being shot by AI or re-spawning does not make this happen

**Comment by commy2** [comment]
Did you drag something?

**Comment by alec-hs** [comment]
Only before dying, drag weapon from main slot to backpack, holster pistol then get shot. Respawn and above happens.
