### ISSUE TITLE
ACE3 interferes with CBA's rail item state

### ISSUE THREAD

**Issue by Drift91** [acemod/ACE3#5475]
**Arma 3 Version:** `1.74` (stable / rc / dev)
**CBA Version:** `3.4.0` (stable / dev + commit hash)
**ACE3 Version:** `3.10.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF *or* SMA (tested with both separately)
```

**Description:**
- When using CBA's rail item state keybinds the rail item gets replaced with a laser pointer that looks like the vanilla one and disappears when I enter the arsenal to try to identify it. This doesn't happen when ACE3 is not installed.

**Steps to reproduce:**
- Enter virtual arsenal, add a PEQ-15 from either RHS or SMA to your weapon and click "try". Then hit ctrl + L and watch as the PEQ-15 gets replaced with the vanilla laser pointer.

**Where did the issue occur?**
- Dedicated + Editor (Multiplayer) + Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- https://gist.github.com/Drift91/b40e7eff5d3bce6e6dbc26916b4dd425

**Comment by jonpas** [comment]
Cause of https://github.com/acemod/ACE3/blob/master/addons/laserpointer/XEH_postInit.sqf#L21-L24?

**Comment by PabstMirror** [comment]
Should be fixed in next CBA release
https://github.com/CBATeam/CBA_A3/pull/722
