### ISSUE TITLE
Help Creating Custom Atrag Gun List For Group

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#5478]
Hi

I want to create a custom gun list for the atrag to push via sync to my group (just remove ammo/guns we don't use not looking at adding ammo just yet)
But I can't work out where the gun list is stored or if it's a patch you have to create to overwrite it, could someone point me in the right direction?

**Comment by ulteq** [comment]
The gun list is stored in the `profileNamespace`. You can overwrite it manually with the following code:

`profileNamespace setVariable ["ACE_ATragMX_gunList", GVAR(customGunList)];`

You can create a `customGunList` by making a copy of this predefined [`gunList`](https://github.com/acemod/ACE3/blob/master/addons/atragmx/functions/fnc_initGunList.sqf#L35-L79) and removing the lines you don't want.

**Comment by bux** [comment]
Note: `GVAR` is a macro.

**Comment by Snak3Doc** [comment]
Thanks, guys ill get back to you if I have any issues but it seems simple enough.

**Comment by bux** [comment]
For questions please join us on Slack: https://slackin.ace3mod.com/
