### ISSUE TITLE
Rearm doesn't rearm

### ISSUE THREAD

**Issue by milivojm** [acemod/ACE3#5479]
**Arma 3 Version:** `1.74` (stable)
**CBA Version:** `3.3.1` (stable)
**ACE3 Version:** `3.10.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Rearming doesn't resupply vehicles on dedicated server. Works in single player.

**Steps to reproduce:**
- Create a mission where ACE rearm settings are: Rearm Amount based on caliber, Ammunition supply unlimited. (mission is attached, ACE and CBA only)
- Put Zamak Ammo truck, AFV-4 Gorgon (or any vehicle) and one player soldier unit.
- Deploy mission on the dedicated server (ACE and CBA only is good enough)
- Run the mission and fire any gun from AFV-4
- Try to resupply from ammo truck. Procedure works correctly but vehicle is not rearmed.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- 'ACE Rearm'

Test mission attached.

[ace-rearm-bug.Stratis.pbo.zip](https://github.com/acemod/ACE3/files/1285110/ace-rearm-bug.Stratis.pbo.zip)

**Comment by AACO** [comment]
The up to date version of ACE3 is 3.10.2 https://github.com/acemod/ACE3/releases/tag/v3.10.2 which has a fix for rearm on dedicated ( https://github.com/acemod/ACE3/pull/5307 )

**Comment by jonpas** [comment]
You should definitely update your CBA to 3.4.0 and ACE3 to 3.10.2 and then report back if it works with those latest versions or not.

**Comment by milivojm** [comment]
It has been fixed in the latest version. Thanks!
