### ISSUE TITLE
Minedispenser not dispensing mines +(localisation)

### ISSUE THREAD

**Issue by Mezilsa** [acemod/ACE3#5484]
Arma 3 Version: 1.76 (stable)
CBA Version: 3.4.0 (stable )
ACE3 Version: 3.10.2 (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The new minedispenser isn't triggering when connected to detonator or timer. -> No happy mines with funny click you are dead - Sound

- localisation errors in german with new minedispenser and training mine (suspecting there are more what is kinda normal for new stuff)

**Steps to reproduce:**
- Open editor, place a box with mine dispenser and clacker
- Place minedispenser
- Connect the clacker to the dispenser
- activate the clacker
- watch how nothing happens

**Where did the issue occur?**
-  Singleplayer (editor)

**Placed Modules:**
- None

**Comment by commy2** [comment]
minedispenser?

**Comment by Mezilsa** [comment]
[https://arma3.com/assets/img/features/low/content/minedispenser.png](url)

Brand new with the LoW DLC
