### ISSUE TITLE
map

### ISSUE THREAD

**Issue by tecak** [acemod/ACE3#549]
At night in vehicle - dark, unlit map. Difficult to see the map. Also return the standard texture maps ! Please do as here http://www.armaholic.com/page.php?id=28351

**Comment by bux578** [comment]
Please follow our guidelines for feature requests and use the official feature request ticket.

http://acemod.github.io/ACE3/wiki/user/how-to-make-a-feature-request.html

**Comment by bux578** [comment]
Please follow our guidelines for feature requests and use the official feature request ticket.

http://acemod.github.io/ACE3/wiki/user/how-to-make-a-feature-request.html
