### ISSUE TITLE
incorrect weights in acre2 mod, Compatibility addon proposal

### ISSUE THREAD

**Issue by kOepi123** [acemod/ACE3#5495]
**Arma 3 Version:** `stable)
**CBA Version:** `stable)
**ACE3 Version:** `stable)

**Mods:**

- CBA_A3
- ace
- ACRE

**Description:**
- weights for radios are not correct
Due to mod makers and BI not following the same ingame mass/ real life mass ratio like ACE mods and instead is using some kind of a cross mass/volume ratio, containers and item weight,
the radios of the acre mods are currently disproportionally lightweight.
I want would like to allow mod makers to use realistic weights in their containers and create an optional acre2 compatibility addon, which adjusts the weights of each radio.

I proposed a direct change already in #393 ( https://github.com/IDI-Systems/acre2/pull/393 )
, but it was not agreed upon, because of the widespread disproportion, that would result in broken loadouts ( backpacks, vests too small ).

If this makes sense to you guys, I will make this addon and promote mod makers following your ingame mass/ real life weight ratio standard in the future.

**Steps to reproduce:**
- pick up any radio and compare them with real life weight, indicated in your inventory.

**Where did the issue occur?**
- anywhere

**Placed Modules:**
- none

**Comment by bux** [comment]
Firstly that rather sounds like a feature request than an issue with ACE3.
Secondly (IMHO) that has no place in ACE3 but would rather make a good custom compatibility mod that would fit in between ACE3 and ACRE2.

**Comment by jonpas** [comment]
This is a feature request, so should go into #3594.

To explain, @kOepi123 PR'ed mass changes to ACRE2, and we decided not to include them because how it is now is simply fine, we can't adjust weight and volume separately, so changing mass breaks either old loadouts or you are unable to put them in certain uniforms (IRL handhelds are strapped on anyways, so that's another thing that could be discussed). We said if some mod ever adds separate weight and volume (obviously ACE3 would be ideal for this) we would of course add support for that.

You can also make your own config mod that adjusts masses for how you see fit. I will close this, this ticket is automatically linked to the feature requests one so no need to post again.

**Comment by kOepi123** [comment]
@bux 
In my opinion it is an issue when ace is bringing in a mass/weight ratio into place, which other ace addons depend on, but is not aligning it with other mods, like acre2 which it is often used ( if not even most of the time ) in conjunction with. You cannot avoid this issue or workaround it by playing differently, unless you put some extra kilogramm of dead weight in your equipment, so it is even an organic issue to ace.

A feature request is something, in my opinion, that I want to see to be done, but cannot make myself and have to rely on others' time or approval. A feature request poses no problem/issue.
The topic line ( and this post ) is suggesting solely an optional compatibility addon between ace and acre, ace has a section for optional addons and this subject is inherently connected to ace mod.
Without ace mods this subject could not exist, because there would be no conversion between mass and real life weight.

Also: the feature request thread is not "allowing" discussions before approval and then will become an issue post, no idea how not discussing can work out on any subject, equally. Especially when there is a lot detail and complexity involved.

@jonpas 
I will make my own compat anyways, this post is intended just to see if people agree with me. 
I had no doubt that people would agree with me, so that is why I made a pull request before.
Obviously people disagreed with good and bad arguments, nevertheless
there is reasoning to not enforce this subject, no idea why an optional addon would even give grounds for discussion, as long as the values are correct. Leaving the argument of the future of addon making in  and for the ace community completely aside.
If people here dont agree, it will save time by making this addon according to my own standards.
Pushing this topic to the feature request thread is postponing and altering the intent of my post.
I dont want to request a change from anyone, I want to make the change happen and implement it for everyone.

**Comment by bux** [comment]
@kOepi123 I understand what you mean. Though, like I said having ACRE configs in ACE isn't possible because that would lead to a dependency on ACRE which is - obviously - not wanted.

Beside bringing our own realism features, ACE provides other mods with the possibilities to hook into some of those features e.g. custom config for Advanced Ballistics, custom configs for Repair, Reloading, Refueling, etc ...
But all those either reside in the third party mod or a custom compatibility mod for that mod. If a mod decides not to support ACE features we can't be held responsible for supplying this compatibility from our side. With thousand of mods out in the wild that would be a ridiculous task.

If you want to make a compatibility mod by yourself I'm unsure why you posted that on the ACE **issue** tracker. Maybe that's why there might some misunderstanding here.

**Comment by jonpas** [comment]
Point is, there is no point changing `mass` values without a proper system with volume and weight separation, as you will get inconsistency either way.

**Comment by kOepi123** [comment]
@bux 
leaving it to the end user whether they activate this compat makes a dependency?
When they have to manually drag the compat to the addon folder?
I cannot follow how that would make a dependency.

I follow your logic with the context of "the ridicolous task", but I dont want to suggest to make a compat for every mod that there is ( I want to **make** it for a single one ) and to provide an option for a commonly used mod, since the acre2 mod crew doesnt want to enforce it, which I agree on, on the short- to medium-term train of thought.

I posted it on here, because it is an issue with a commonly used mod, it will disproportion the gameplay when these mods are used together, the community and mod making will benefit when a standard ( that I did not set ) will consistently be recognized and agreed upon: where else do I open a proposal that is related to an issue, which solution would benefit ace and acre user?

@jonpas 
Besides that noone will ever make themselves that much work to give every single item a volume, so it will not happen what you are expecting to be present, especially when the current system works.
Besides that, there is no inconsistency if you align yourself with the mass ratio standard that ace has set long time ago. People just have to calculate their containers in real life mass, instead of real life volume.
There is disproportion at the moment, exactly because of no existing or no used standard before ace, people think that certain items will fit into a certain backpack and use the more logical dimension the volume or eye guesswork, if they would apply or would have applied that standard or would have even thought about how one would find a common standard throughout the communities and modmakers, then they would have come up with something else.
Ace sets a certain weight to a certain volume ratio, for all the items and that you can apply to every volume you can imagine, but it needs to be converted into mass.
If your vest has a pouch, that is there to hold a radio, then you take the weight from the radio in kg and divide it by 22 and then you have the load that needs to be available. simple as that.
If you dont want a radio in that pouch you can put some magazines or so in there, they will have the same proportion.
What did the acre mod base its mass values on?

Maybe there is no disproportion from the BI side, only from the individual modders, the assault packs are really just to small to hold a modern manpack radio and a caseless 30 round magazine is much lighter than a today's magazine.
------------------------------
That guy that ( maybe in ArmA 2 ) set once that weigth/mass ratio, has set a milestone for balancing the gameplay, a standard which everyone else ( that knows of the ace mods ) can work with and depend on and still is only partly enforced and recognized in the mod communities after 4 years of arma 3.

**Comment by SilentSpike** [comment]
https://xkcd.com/927

We cannot expect everyone to suddenly adopt a new convention when there's already a functional model that's used widespread.

Don't get me wrong, I agree that the mass value model used in arma is pretty obtuse and it'd be nicer if everything was reflective of real life. It's just a case of feasibility.

**Comment by kOepi123** [comment]
@SilentSpike 
This conversion is present since ArmA 2. There is no problem for anyone if you dont enforce the mass value standard. An optional addon would not enforce it.

The volume or mass system used by BI is fine.
In which case would it not be sufficient? In the case I have to load a 40 ton truck with supermarket items, which items change its specific density from 0.1 g/ccm to 8 g/ccm.
In arma we dont have those versatile objects, no huge difference of specific density, all the items go up to and around an approx. density from 0.6 g/ccm to 2,13 g/ccm.

regarding your illustration: there is only one standard and that is introduced by ace. everything else is just balancing more or less based on "it works for me in this configuration".

**Comment by bux** [comment]
>leaving it to the end user whether they activate this compat makes a dependency?
>When they have to manually drag the compat to the addon folder?
>I cannot follow how that would make a dependency.

@kOepi123 you misunderstood me. That's not what I've said.

> bux: Though, like I said having ACRE configs in ACE isn't possible because that would lead to a dependency on ACRE which is - obviously - not wanted.

But from reading further, it seems to me, that you want to make your own compatibility mod.

> I posted it on here, because it is an issue with a commonly used mod

No. It's not an issue with ACE.

> where else do I open a proposal that is related to an issue

https://forums.bistudio.com

And like @SilentSpike said: we can't force anyone to be compatible to ACE.
https://ace3mod.com/wiki/user/information-center.html#13-compatibility
