### ISSUE TITLE
Singleplayer saves issue.

### ISSUE THREAD

**Issue by ChaosPaladin** [acemod/ACE3#5499]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.0.170627` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- With enabled ACE3, save game not work. If save game w/o ACE3, but after enable ACE3 and try load save (what saved w/o ACE3) game load correct.

**Steps to reproduce:**
- Go to any campaign / single scenario game
- Save game (wait autosave)
- Die a character
- Load last savegame (manualy or autosave)
- After loading save you get static scene screen
![arma3_x64 2017-09-11 18-50-08-126](https://user-images.githubusercontent.com/10120702/30284911-0bc1d3b4-9725-11e7-8dd1-30c5ea8693e0.png)

**Where did the issue occur?**
- Singleplayer

**Placed Modules:**
- None

**RPT log file:**
- Arma 3 Log https://gist.github.com/ChaosPaladin/39ecc1888da2bd4e10ecb7099a211f33
- ACE DEBUG https://gist.github.com/ChaosPaladin/88b604f4dd564a747da8745c550b35df

**Comment by commy2** [comment]
Which mission? Needs full RPT file.

**Comment by ChaosPaladin** [comment]
For me its for all default campaigns and singleplayer missions. I cant get RPT from clickboard ACE debug, because this menu not work, he empty if load save.

**Comment by commy2** [comment]
The RPT file is in
```
%LOCALAPPDATA%\Arma 3
```

**Comment by ChaosPaladin** [comment]
Its empty for me https://gist.github.com/ChaosPaladin/39ecc1888da2bd4e10ecb7099a211f33
So, issue solved with fully delete Arma 3 profiles from Documents folder.
