### ISSUE TITLE
MineDetector works only on specific condition when located in inventory [11/09/2017]

### ISSUE THREAD

**Issue by RaiderSpectre** [acemod/ACE3#5500]
**Arma 3 Version:** `1.76` (stable / rc / dev)
**CBA Version:** `3.4.0` (stable / dev + commit hash)
**ACE3 Version:** `3.10.2` (stable / dev + commit hash)

**Mods:**

- CBA_A3
- ace3
- MCC Sandobox 4
- Zeus Eden Compositions
- TaskForce Radio 0.9.8

**Description:**
NOTE: My clanmate found this and **we don't deepen this issues.**
Case 1: when there is more than 1 item located in uniform and MineDetector is located in vest or backpack it does not detect mines at all unless they're spotted via "T".
Case 2: when there ISN'T ANY ITEM located in uniform and MineDetector is located in vest or backpack it will work correctly
Case 3: MineDetector will work randomly (it appears) if located in uniforms

**Steps to reproduce:**
https://www.youtube.com/watch?v=4o1dmrw4TMg&feature=youtu.be

**Where did the issue occur?**
- Editor (Multiplayer)

**Placed Modules:**
- Time Accelration, revive settings [ACE], set medic class [ACE], Advanced Fatigue, Medical Settings [ACE],  Captives settings, Name Tags, Respawn Systems, Game Master x 3

**RPT log file:**
none

**Comment by PabstMirror** [comment]
This will be fixed via #5502 in next release
We used to do
```
-    class ACE_ItemCore: ItemCore {
 -        type = 4096;//4;
 -        detectRange = -1;
 -        simulation = "ItemMineDetector";
 -    };
```
which seems to break the detection range.
In the future ace items won't be mine detectors at all.

**Comment by commy2** [comment]
The last minedetector picked up determines the detection range. Most ACE items are mine detectors with 0 detection range, so they can appear in the Virtual Arsenal.

**Comment by commy2** [comment]
The last mine detector picked up determines the detection range. Most ACE items are mine detectors with 0 detection range, so they can appear in the Virtual Arsenal.
