### ISSUE TITLE
Metal detectors still detecting ordnance that has been "removed"

### ISSUE THREAD

**Issue by ProfCupcake** [acemod/ACE3#5508]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.0.170627` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The Laws of War DLC's unexploded ordnance and launched anti-personnel mines work differently than others when defused. As far as I can tell, the object itself is not actually deleted, just made invisible. This means that the ACE metal detectors will still detect the object there, despite it having been removed, giving a false positive. 

**Steps to reproduce:**
- Place some unexploded ordnance, or launch mines from a mine dispenser. 
- Defuse it
- Use metal detector on location of defused explosive

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Placed Modules:**
- None

**RPT log file:**
- https://hastebin.com/eresehahop

**Comment by mr-bo-jangles** [comment]
In my testing on master it also appears that ACE3 isn't removing the defusal menu option from the location, however it does do the job of defusing as you can't still trigger the explosive.

**Comment by jonpas** [comment]
Can reproduce, object stays there, is just hidden.
