### ISSUE TITLE
Compatibility with other mods requiring agm_core

### ISSUE THREAD

**Issue by Tirpitz93** [acemod/ACE3#551]
Is there any way to either bypass this check or trick it somhow into accepting the new file structure?
if the function names/structure were still the same it should theoretically be possible to ignore the error and or create a dummy file to pass the check.
the other option is to use the old core file. but would this create issues with the new version.

**Comment by commy2** [comment]
No. If another mod requires AGM_core , then it requires AGM_core for a reason. You can remove the error meesage by creating dummy files, but then certain things won't work / break.

**Comment by jonpas** [comment]
One big thing is all variables and classes, AGM ones start with `AGM_`, ACE ones start with `ACE_`, so nothing would simply work out of the box. If it requires AGM_Core it means (or it should) it uses something from it.
