### ISSUE TITLE
Loading patients underwater does not work

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#5515]
**Arma 3 Version:** `1.76` stable
**CBA Version:** `3.4.1` stable
**ACE3 Version:** `3.10.2` dev df739bd36cd36f5a63d6cb8e56f5b2fda4cce770

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Load patient does not work underwater

**Steps to reproduce:**
- Try to load a patient in a SDV inland, then try underwater.

**Where did the issue occur?**
-Editor singleplayer

**Placed Modules:**
- None

**RPT log file:**
- Nothing of interest there.

**Comment by alganthe** [comment]
small correction, the loading / unloading of patients underwater seems finicky, there seems to be some detection issues, I am currently trying to find what produces that issue.

**Comment by Saborknight** [comment]
We've recently done some testing on our server for underwater combat capabilities, and it looks like Unconscious Patients are not able to be loaded again. It is possible to drag, but not load.

ACE version: 3.13.6
