### ISSUE TITLE
AI can be handcuffed, no matter what requireSurrender is set to

### ISSUE THREAD

**Issue by Keithenneu** [acemod/ACE3#5518]
**Arma 3 Version:** `1.76` profiling
**CBA Version:** `3.4.0` stable
**ACE3 Version:** `3.10.2` stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- AI can always be handcuffed without surrendering first. Captive settings don't matter.

**Steps to reproduce:**
- Place yourself (blufor) and add some CableTies.
- Place a civilian or an enemy (opfor) with no ammo.
- Set `Require Surrendering` to `Surrendering only` or `Surrendering or No weapon` in the module.
- Handcuff them for every combination of setting/side

**Where did the issue occur?**
- tested on Dedicated / Singleplayer (from Editor)

**Placed Modules:**
- Captives Settings

**RPT log file:**
- None

**What I think the issue is**

Being AI is ORed with requireSurrender Checks -> being AI is always enough.
https://github.com/acemod/ACE3/blob/master/addons/captives/functions/fnc_canApplyHandcuffs.sqf#L28

I would do a pull request, but am unsure of how it was supposed to work in the first place or what the intention of that check was.
Could be related: #2053
AI check was added in https://github.com/acemod/ACE3/commit/1c26f6c9f5e7093c335f362ddaece8521bb6176d .

**Comment by jonpas** [comment]
I believe that's by design, as AI can't really surrender. That setting is for players only.
