### ISSUE TITLE
Have Make.py copy important files into the release folder

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#552]
The binarization should copy inside de @ACE folder some important files, including:
- Extension dlls
- License file
- Authors
- Readme

Apparently extensions work inside the @ACE folder, so there's no need to dump them on the base game directory.

**Comment by KoffeinFlummi** [comment]
Will do.

**Comment by Glowbal** [comment]
Also:
* mod.cpp
* logo_ace3_ca.paa

**Comment by Kllrt** [comment]
Good idea.

**Comment by jonpas** [comment]
#slack-ideas

**Comment by commy2** [comment]
>#slack-ideas

oh god, please stop

**Comment by jonpas** [comment]
:grinning:

**Comment by meat147** [comment]
Optional files / server.pbo

**Comment by ViperMaul** [comment]
From discussion it was agreed to make "external file checks" False for pboProject. In other words, Default: don't check
