### ISSUE TITLE
Cannot unload injured from vehicle

### ISSUE THREAD

**Issue by Arcanum417** [acemod/ACE3#5525]
**Arma 3 Version:** `1.76,142872` (stable)
**CBA Version:** `3.4.1.170912` (stable)
**ACE3 Version:** `medical-rewrite bdea0fcdbab53d4d5a5d67652f41d37733523447` (dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- You always get error there is no space if you try to unload injured player from vehicle.
- inconsistent behaviour when trying to unload AI

**Steps to reproduce:**
- Create mission with two slots and one vehicle
- Start two instances of Arma3
- Host the mission on one instance, join with the other
- Shoot the player until he falls
- Load injured player into vehicle
- Mount the vehicle and try to unload the player
- Or try to unload the player from outside of vehicle

**Where did the issue occur?**
-  Self-Hosted Multiplayer

**Placed Modules:**
- none

**RPT log file:**
- ([gist](https://gist.github.com/f7d285d4b6e2f5d2d922a44292cfdf4d))

**Comment by bux** [comment]
https://i.gyazo.com/3aa61e3cde53d7177d6c2ae1b8316434.gif
Happens in current release 3.10.2 too

**Comment by bux** [comment]
Imho we could just remove the option to unload a patient while being inside a vehicle. It kinda doesn't make much sense.

**Comment by jonpas** [comment]
But you might have to get him out and into a medical vehicle for example, or a medical facility which you can't exactly drive into.

**Comment by jonpas** [comment]
Looks like finding unload position is failing. @PabstMirror ?

**Comment by bux** [comment]
@jonpas unloading from outside would be used for that. From a realism pov that makes more sense

**Comment by jonpas** [comment]
Ah, that's what you meant. Then yes, I agree.

**Comment by Arcanum417** [comment]
In master, you cannot unload if the caller is inside. With medical-rewrite, you cannot unload even if caller is outside, that was the original bug I wanted to report.

**Comment by Arcanum417** [comment]
Logs from clients
https://gist.github.com/8c3c25928648eb3e6139a51e72f9c61e
https://gist.github.com/7e960c981ef74909a2057ac406c401c6

**Comment by jonpas** [comment]
I "fixed" this on master as discussed above (by disabling unloading when inside vehicle, only from outside) in #5544. Will reopen this once PR gets merged because this is addressing `medical-rewrite`.

**Comment by PabstMirror** [comment]
Problem is in ace_common_fnc_unloadpersonLocal
I think this is related to the `setUnconscious` command usage.
` player action ["Eject", vehicle player];` has no effect

Even more bizarre is doing `setPos` on the unconscious unit
from uncon's prespective `getPos` and `vehicle unit` changes, but goes back to the vehicle after about 10 seconds
from the server's point of view the unit never left the vehicle.

Doing setPos on the server for the unit has global, permanent effects.

**Comment by jonpas** [comment]
`action` not having effect kind of makes sense, since it's supposed to simulate the unit actually doing the action.

**Comment by PabstMirror** [comment]
Should be fixed via 75e58a8dce1654f9f3dbb3125bea85fda3b636f1

Will need more testing in mp, but seems to work
looks funny because of the ragdoll but also simplifies a lot of things
