### ISSUE TITLE
The explosion of ammunition technicians

### ISSUE THREAD

**Issue by VDV2015** [acemod/ACE3#5527]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `stable` (stable / dev + commit hash)
**ACE3 Version:** `stable` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
With a large number of players on the server with the explosion of the ammunition technology, there is a drop server. Please add the module to shut off the explosion of ammunition technology.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
None

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by 654wak654** [comment]
You should use the [settings framework](https://ace3mod.com/wiki/framework/settings-framework.html). Most ace modules have missing settings, and some components (like ace_cookoff) don't have modules at all.

**Comment by jonpas** [comment]
Modules will eventually become deprecated after we switch to CBA Settings.

**Comment by commy2** [comment]
Doesn't this have a setting already?

**Comment by 654wak654** [comment]
> Doesn't this have a setting already?

It does, not in editor module form.

**Comment by PabstMirror** [comment]
You can also tone down the ammount of explosions instead of turning them completly off
```
class ACE_Settings {
    class ace_cookoff_ammoCookoffDuration {
        typeName = "SCALAR";
        value = 0.1;
    };
};
```

**Comment by Cuel** [comment]
is that a percentage value?

**Comment by PabstMirror** [comment]
It scales the amount of ammo in the vehicle that burns.
So smaller values will make the cookoff effect end faster.

**Comment by Cuel** [comment]
Got confused by the `duration` name 👍
