### ISSUE TITLE
[Discussion] ACE Cargo space system scaling rework

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#5540]
So i thought I would start this to see if I'm the only one who has this issue or not.

The current scaling of the ACE cargo system doesn't really make sense for the varying sizes of objects that can be loaded in. 
For example, the current system gives 4 cargo spaces to all cars, meaning you can only fit 4 of the smallest objects eg. NATO grenade box's into a cars ACE cargo (this is like saying I can only fit bottles of milk in the boot of my car), and in the case of the NATO supply crate, you cant fit it into any car, even though pretty much every car (bar some civ ones) has more than enough room for one of those.

I propose scaling up the available cargo space in pretty much all vehicles (cars, mid sized trucks, and helicopters are the main ones that annoy me personally) eg cars 4 > 6 or 8, this would then allow for better scaling of the space required value of objects, instead of going from 1 -  5 it could go from 1 - 6 or 8 to better represent the size of the objects in the game.

**Comment by olanguedoc** [comment]
If paradroping is managed by the cargo space system, maybe it would be a good idea to remove the time variation when paradroping different object. Right now it takes around 2 sec to paradrop a box, but like 8-10 to paradrop bigger objects. Also, if you are a pilot, you loose control of the plane or helicopter while the progress bar & interface is present (very dangerous! haha).

**Comment by austinjames314** [comment]
Yeah the delay / control lock while dropping at the moment is a huge pain in the ass.
As for scaling the capacity, and size of crates, it''s not just an ACE issue I think - it's also an issue for other mods that add vehicles, and their configs.
I think that the problem currently is that the numbers for Ace cargo are totally arbitrary. I think that the ACE team should pin down what these units mean, and post that publicly. E.g. 1 point = 100 kg. Then real life values can be used, and things should end up a bit closer to players' expectations.

**Comment by dedmen** [comment]
I completely agree with @Snak3Doc 
Also I'd like if we could just scale up the sizes by a factor of 10 in general. So that we can archive more granular control

**Comment by jonpas** [comment]
Changing scale requires changing it linearly with objects and vehicles. Additionally they should still use same values in config to not cause incompatibilities with mods that use this (float?).

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
