### ISSUE TITLE
Make a vehicle medical vehicle with a script

### ISSUE THREAD

**Issue by 1stLT** [acemod/ACE3#5545]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace3
- acex
```

**Description:**
I am using the command
[rpHmmwv] call ace_medical_fnc_isMedicalVehicle;
But it won't work, rpHmmwv is not turning into a medical vehicle.

**Steps to reproduce:**
Use the command 
[rpHmmwv] call ace_medical_fnc_isMedicalVehicle;

**Where did the issue occur?**
Dedicated

**Placed Modules:**
Advanced Medical Settings

**RPT log file:**

**Comment by PabstMirror** [comment]
use
`this setVariable ["ace_medical_medicClass", 1]`
