### ISSUE TITLE
Feature request: Move cook-off probability to config

### ISSUE THREAD

**Issue by BlueNexus** [acemod/ACE3#5555]
So, cook-off is actually much harder to cause IRL than it is in ACE, atm. We'd like the ability to modify the probability of cookoff occuring, for greater realism, using a configuration module. I know this wouldn't be particularly difficult - reference the following lines, where the numeric value could be replaced with a config setting
https://github.com/acemod/ACE3/blob/ffaa195fe576625f052eeee04b1af9f3f377434f/addons/cookoff/functions/fnc_handleDamage.sqf#L69

and https://github.com/acemod/ACE3/blob/ffaa195fe576625f052eeee04b1af9f3f377434f/addons/cookoff/functions/fnc_handleDamage.sqf#L73

I'd do it myself, but I'm not familiar with this particular programming language.

**Comment by tbeswick96** [comment]
I was thinking of doing something similar. I'm happy to make a PR for this

**Comment by Twelvecaliber** [comment]
These combined , would be such a good overhaul to the cookoff and bring greater compatibility with other mods #5212

**Comment by dedmen** [comment]
help wanted issues shouldn't be closed by the bot.
Neither should ongoing milestone issues.
