### ISSUE TITLE
Single 40mm grenade triggers ammo cookoff on certain vehicles with GMG and not on others

### ISSUE THREAD

**Issue by Pergor** [acemod/ACE3#5557]
**Arma 3 Version:** `1.76` stable
**CBA Version:** `3.4.1.170912` stable
**ACE3 Version:** `3.10.2`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- A single hit with a 40mm Grenade to the GMG of the following vehicles results in immediate cookoff and destruction of vehicle:
O_APC_Wheeled_02_rcws_F, B_APC_Tracked_01_CRV_F, B_APC_Tracked_01_rcws_F
It doesn't happen to any other vehicles with GMGs (eg. Hunter, Ifriit, Strider, Scorcher).

**Steps to reproduce:**
- Place O_APC_Wheeled_02_rcws_F in editor, place Grenadier in editor, shoot at GMG turret of aforementioned vehicle with 40mm. Boom -> cookoff.
- Place B_MBT_01_arty_F in editor, shoot at GMG turret with 40mm. Boom -> nothing.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer) / Editor (Singleplayer)

**Placed Modules:**
- None

**Comment by PabstMirror** [comment]
Hits to RCWS turrets should not cause cookoff as the weapon/ammo is outside of the vehicle
