### ISSUE TITLE
Loading screen and editor error

### ISSUE THREAD

**Issue by AceWinchester** [acemod/ACE3#5562]
**Arma 3 Version:** `1.76` 
**CBA Version:** `3.4.1.170912`
**ACE3 Version:** `v3.10.2` 

**Mods:**
```
- CBA_A3
- ace
-  @AdvancedRappelling 
-  @Ares 
 -  @CAF_AG1.5 
 -  @CBA_A3 
 -  @CUP_Terrains_Core 
 -  @CUP_Terrains_CWA
 -  @CUP_Terrains_Maps 
 -  @CUP_Units 
 -  @CUP_Vehicles 
 -  @CUP_Weapons 
 -  @FIR_AWS(AirWeaponSystem) 
 -  @MCC_Sandbox_4_-_Mission_Making_The_Easy_Way
-  @MilGearPack
- @PROJECT_UNCUT 
-  @RHSUSAF  
 -  @SMA_V2.7.1 
 -  @task_force_radio 
 -  @VSM_-_Accessory_Pack  
 -  @VSM_GearPack_v2_beta 
  -  @VSM_Uniforms 
-   @VSM_VestsHelmets


```

**Description:**
Tried to make a simple mission template, tested and got this error code. When adding it to my server just get a loading screen for 10 minutes then timeout when joining. 
Used to work fine 

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer) 

**Placed Modules:**
Respawn

**![20170927200047_1](https://user-images.githubusercontent.com/32327771/30908225-4cc6447e-a3c0-11e7-9f1c-b98c6f986f9a.jpg)**

**Comment by bux** [comment]
>If you have found an issue with ACE3 please make sure that ACE3 really is the cause of the problem. To do this try to reproduce the issue with using only @CBA_A3 and @ace on a newly created mission.

> If the error happens when using a third-party mod contact the author of the appropriate mod and report the issue there.

**Comment by Cuel** [comment]
It's an issue with MCC (based on previous issues)

**Comment by PabstMirror** [comment]
MCC does:
```
_nul = ["MCC_interactionEH", "onEachFrame", {
  // code
}, ""] call BIS_fnc_addStackedEventHandler;
```
which throws Type String, expected Array because of the params type checking
I think the BIS function was changed in 1.76

ACE has no effect on this; you'll want to talk to the MCC team

**Comment by AceWinchester** [comment]
Thanks for your help
