### ISSUE TITLE
Advanced Throwing throwable torque

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#5567]
Make grenades rotates in air, similar or better than in vanilla. Especially useful for WW2 German stick grenades. However some grenades have air stabilizer fins, so have to support both.

Opening this to discuss config entry requirements, so far thought of this (with ideas from below comments):
```cpp
class CfgAmmo {
    class SmokeShell;
    class ACE_G_Handflare_White: SmokeShell {
        // {} or {0,0,0} - disabled, {x, y, z} - torque vector
        ace_advanced_throwing_rotation = {100, 0, 0};
    };
};
```

It would also be enabled for all vanilla grenades with some default rotation, since they are all similar enough.

I didn't do any testing yet, but `addTorque` is applied as impulse, which means it should stop rotating relatively fast on very low torque vectors, thus simulating stabilizer fins.

**Comment by Dystopian** [comment]
Maybe no need in 2 config entries, `rotate = 0` -> `rotateTorque = {}`.

**Comment by jonpas** [comment]
Ooh yeah, either empty array of `{0, 0, 0}` since that would mean no rotation. Nice catch!

**Comment by commy2** [comment]
There should be some randomization.

**Comment by commy2** [comment]
```sqf
    class ACE_G_Handflare_White: SmokeShell {
        GVAR(torqueDirection) = {1, 0, 0};
        GVAR(torqueMagnitude) = random 100 + 50;
    };
```
```sqf
private _torque = getArray (missionConfigFile >> QGVAR(torqueDirection)) vectorMultiply getNumber (missionConfigFile >> QGVAR(torqueMagnitude));
```
This would make easy code and give enough freedom to the config I'd say.

**Comment by commy2** [comment]
Also:
```sqf
_grenade addTorque (_grenade vectorModelToWorld _torque);
```
Because the command is relative to the world axis, not the object axis.

**Comment by commy2** [comment]
```sqf
["ace_throwableThrown", { // local event 
    params ["", "_grenade"]; 
 
    private _torque = vectorNormalized [1,0,0] vectorMultiply (50 + random 100); 
 
    _grenade addTorque (_grenade vectorModelToWorld _torque); 
}] call CBA_fnc_addEventHandler;
```
This works great!

**Comment by commy2** [comment]
```sqf
["ace_throwableThrown", { // local event 
    params ["_unit", "_grenade"]; 
 
    private _torque = vectorNormalized [1,0,0] vectorMultiply (50 + random 100); 
 
    _grenade addTorque (_unit vectorModelToWorld _torque); 
}] call CBA_fnc_addEventHandler;
```
Actually, because `vectorModelToWorld` is broken for CfgAmmo.

**Comment by bux** [comment]
This was already added in v3.11.0
