### ISSUE TITLE
ACE3 IR strobe functions as a mine detector after Laws of War update

### ISSUE THREAD

**Issue by KarlMoebius** [acemod/ACE3#5575]
**Arma 3 Version:** `1.76.142872` (stable)
**CBA Version:** `3.4.1` (stable)
**ACE3 Version:** `3.10.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- After ARMA3 update (laws of war), which I have the DLC (I don't know if that helps), but IR strobes function as mine detectors. Probably brought up before by someone else, but I checked back a few pages of the issues and didn't see anything.

**Steps to reproduce:**
- have one IR strobe on person. 
- Use ] key to open mine detector.
- Open up inventory, remove IR strobe.
- Mine detector window disappears.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by PabstMirror** [comment]
Will be fixed by https://github.com/acemod/ACE3/pull/5502 in next release
