### ISSUE TITLE
spare barrel

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#5579]
**Arma 3 Version:** `last` (stable)
**CBA Version:** `last` (stable)
**ACE3 Version:** `last` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
neither in the arsenal, nor in the ace-box, there is a spare barrel for the machine gun, but in the game it is in the box by default.
http://joxi.ru/EA44LwoiDKeYOA   ace-box
http://joxi.ru/n2YXgExCjRga7m   box inventory-havent barrel
http://joxi.ru/82QLB8Kc1Ze7dm virt arsenal - havent barrel
http://joxi.ru/DmBZ8dPUNjel6m  in game

i want to add classname of spare barrel in my boxes, but i dont know how find it?))
(sry for my english)

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by madpat3** [comment]
it's a magazine.

**Comment by PabstMirror** [comment]
It should be in the ace box towards the bottom, near the chem lights
Classname is `ACE_SpareBarrel` and yeah it is a magazine, so `addMagazineCargoGlobal`
