### ISSUE TITLE
Firing Mk6 mortar causes injury

### ISSUE THREAD

**Issue by ppitm** [acemod/ACE3#559]
Repro: Place static Mk6 mortar and fire several rounds.
Firing rounds will usual cause pain and light bleeding to torso, with shaky screen.
As with most light injuries caused from explosives and shrapnel, the injured body part will often not be shaded in red on the medical UI, forcing the player to guess which body part to bandage.

Using unofficial build available on Play With Six.

**Comment by jonpas** [comment]
Please follow the guidelines for issue reporting: http://acemod.github.io/ACE3/wiki/user/how-to-report-an-issue.html
