### ISSUE TITLE
Requesting ace interactions for the Data Terminal

### ISSUE THREAD

**Issue by neetch1** [acemod/ACE3#5590]
Requesting interactions like "load" and "drag" for the Data terminal (Land_DataTerminal_01_F).

Would be very useful, especially when having scripts like SATCOM linked to the terminal.

For your consideration.

**Comment by bux** [comment]
@neetch1 After you clicked "New Issue" there was this giant warning above the issue field.
![image](https://user-images.githubusercontent.com/1235520/31219606-2a666a68-a9be-11e7-8728-832762628330.png)

Did you even care to read the guidelines?

If so you would have been redirected to this page: https://github.com/acemod/ACE3/blob/master/.github/CONTRIBUTING.md where it clearly says: 

>In order to avoid duplicates and keep the issue tracker organized, we have created a common issue for ACE3 Feature requests. Any and all relevant requests should be submitted there, where they will also get discussed and evaluated. Before adding a new one, make sure to check the previous entries from the thread and do a quick search for similar suggestions; please don't reiterate requests for features that had already been accepted for inclusion, or those which were disregarded earlier.

**Comment by neetch1** [comment]
saw titles in the issues tap named 'feature request' posted 10 days ago so thought i could post it here
