### ISSUE TITLE
"Fire Smoke Launcher" broken for some vehicles

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5591]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1.170912` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- JSRS sound mod
-ASR AI mod
```

**Description:**
- If I use ACE3 mod, then the smoke ability (I mean the countermeasures), at the some vehicles is not works.  I found problems with these tanks - **Leopard 2 SG, Merkave Mk 4 LIC, T100 Black Eagle.** For example when I uses the Merkave Mk 4 M or APC Badger IFV - I not see this problem! 

NOTE!  It is necessary to check all other vehicles, that have the ability to smoke, probably this will not work the same way. I did not check every one personally

**Steps to reproduce:**
- place into map the Leopard 2 SG or Merkave Mk 4 LIC or T100 Black Eagle (player as commander)  and activate the ability to smoke ("C" Button, by ACE3 deafault)  This will not work

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- not needed

**Comment by commy2** [comment]
>countermeasures
>the ability to smoke ("C" Button, by ACE3 deafault)

This is wrong, ACE does not have such a key called "Countermeasure". It is a key action from the base game (category "Weapons") instead:
![https://i.imgur.com/XX0Icgt.jpg](https://i.imgur.com/XX0Icgt.jpg)

ACE has a key called "Fire Smoke Launcher" (category "ACE Vehicles") and it got indeed broken by a game update:
![https://i.imgur.com/a7LqcrL.jpg](https://i.imgur.com/a7LqcrL.jpg)

Just unbind this key. Do not bind both to the same key, as the ACE one overwrites the vanilla one and so nothing will happen.

>"C" Button, by ACE3 deafault

This is wrong. The default of the ACE key is `9`, not `C`.

**Comment by commy2** [comment]
The reason for this being broken is, that `action ["SwitchWeapon"` apparently no longer work for vehicles.

**Comment by ZeusWrath** [comment]
> This is wrong, ACE does not have such a key called "Countermeasure"
this is only what I called it

> ACE has a key called "Fire Smoke Launcher" (category "ACE Vehicles") and it got indeed broken by a game 
Then it's completely unclear why this does not work ONLY for selected vehicles !?

> This is wrong. The default of the ACE key is 9, not C.
Okay, maybe I mixed up the settings of the vanilla game with ACE settings. I always used - "C"

> The reason for this being broken is, that action ["SwitchWeapon" apparently no longer work for vehicles.
I once again ask you to pay attention to the fact that the problem concerns only some vehicles. Then why do other vehicles not have this problem?

**Comment by ZeusWrath** [comment]
> Just unbind this key. Do not bind both to the same key, as the ACE one overwrites the vanilla one and so nothing will happen.

Yes!!! That helped. I am very grateful to you, thank you!

**Comment by commy2** [comment]
>I once again ask you to pay attention to the fact that the problem concerns only some vehicles. Then why do other vehicles not have this problem?

The function responsible for this key uses two methods. One for vehicles with the smoke launcher on the main turret / gunner turret, and one for it on the commander turret. You'll notice that it's only broken for vehicles that have the smoke launcher on the commander turret.

**Comment by ZeusWrath** [comment]
> The function responsible for this key uses two methods. One for vehicles with the smoke launcher on the main turret / gunner turret, and one for it on the commander turret. You'll notice that it's only broken for vehicles that have the smoke launcher on the commander turret.

now I understand. I think the ticket can be closed!

**Comment by commy2** [comment]
The bug is still there. I'm thinking about scraping this feature... It helped with a certain bug in MP, but now that it no longer works, might as well remove it. It was redundant outside of being a work-around anyway.

**Comment by GarudaThirteen** [comment]
Just like Zeus, unable to use smoke launcher on the merkava and most other vanilla vehicles.

**Comment by PabstMirror** [comment]
@GarudaThirteen can you be in the commander turret and run this debug code
`getText ((configOf vehicle player) >> "EventHandlers" >> "fired")`

I can't reproduce with just cba/ace

**Comment by GarudaThirteen** [comment]
@PabstMirror  I apologize for the late reply, here's what pops up.

""
![image_2023-03-16_103311385](https://user-images.githubusercontent.com/77281561/225495205-93c6fb6d-eb9c-40ce-930d-0edf0874e12a.png)

attached is the screenshot.

Most of the other vanilla tracked vehicles do not have working smoke launchers either on my end: Leopard II, Merkava and Merkava UP, T-100 Black Eagle, Namer, Nemerra, Sholef, Sochor, and T-14s.

**Comment by PabstMirror** [comment]
maybe check `configSourceAddonList  ((configOf vehicle player) >> "EventHandlers")`

but this really isn't an ace issue, it doesn't happen with just cba and ace
you can try removing mods and see if you can isolate the cause

**Comment by GarudaThirteen** [comment]
Will do! I'll check it out, if ever I'm trying to isolate what mod or mods that might be causing it. Thanks!

**Comment by johnb432** [comment]
As this is no longer an ACE issue, this is considered resolved.
