### ISSUE TITLE
button text in ace setting menu is misleading in german

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#5594]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- look at the marked "Schließen" button, it should be -> https://github.com/acemod/ACE3/blob/98da86b74d4089bc3403d0b0c0074e6a46ce35d8/addons/optionsmenu/stringtable.xml#L174
- but know its missleading, i was wondering why a close button doesnt close the window.... know i know it adds client settings ^^
![](https://steamuserimages-a.akamaihd.net/ugc/866239085623253425/597572EDE38FCA9D97BBBEE2F490D770106A31A5/)

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by commy2** [comment]
The menu is dead. Long live the new menu!
