### ISSUE TITLE
Unload cargo Position of the Pelican Drone is inside the drone in Dedicated

### ISSUE THREAD

**Issue by Mezilsa** [acemod/ACE3#5595]
Arma 3 Version: 1.76 stable
CBA Version: 3.4.1.170912 stable
ACE3 Version: 3.10.2

Mods:

- CBA_A3
- ace

Description:

The new Pelican Drone has a Cargo Inventory. If you unload in mp a box the box spawns inside the drone (which the drone isn't humoring). 
In singleplayer it seems to work finde.
Steps to reproduce:
Place a pelican drone
Insert a box
Load a box
Unload a box
watch a boncing drone/a little campfire with a box in the middle of it
  

Where did the issue occur?

    Dedicated

Placed Modules:

    None

**Comment by PabstMirror** [comment]
Cargo space will be removed from the drone in 3.11, so this is sort of fixed already
https://github.com/acemod/ACE3/blob/master/addons/cargo/CfgVehicles.hpp#L298

**Comment by Mezilsa** [comment]
Well. Kinda fixed indeed.
Same problem remains.
Is there a way to make shure that loaded objects are not clipping into the object (e.g. Hunter meets Blackfish and it goes boooooom)?
