### ISSUE TITLE
Rework ace_parachute (landing-animation / vanilla altimeter)

### ISSUE THREAD

**Issue by IanBones** [acemod/ACE3#5596]
**Arma 3 Version:** `1.76.143187` (stable)
**CBA Version:** `v3.4.1.170912` (stable)
**ACE3 Version:** `v3.10.2.22` (stable)

**Mods:**
```
- CBA_A3
- ACE3
- ACEX
- ACRE2
- HeadRangePlus
```

**Description:**
- The ACE Animation for landing a parachute was implemented to replace the horrible version of the vanilla game where you allways landed with your face in the dirt. Since then, the vanilla animation was overhauled and is now very nice and usable.
- Despite having the ACE_Altimeter linked in the inventory, the vanilla altitude and speed infobar at the top of the screen still is visible

**Steps to reproduce:**
- Place a playable unit with:
  - a parachute
  - sufficient height to freefall and open the chute
  - an altimeter watch
- preview the mission
  - recognize the vanilla altitude and speed infobar at the top of the screen
  - open the parachute and land
- repeat without mods
  - see how the parachute collapses behind the unit instead of disappearing
  - no bellyflop, "proper" landing 

**Where did the issue occur?**
- tested on Dedicated and in Editor (Singleplayer)

**Placed Modules:**
- None

**Comment by commy2** [comment]
The altitude is only hidden outside of `cadetMode`. So you might want to try to up your game difficulty.
Totally agree with getting rid of the animation tweak.

**Comment by commy2** [comment]
ref: https://github.com/acemod/ACE3/blob/master/addons/parachute/functions/fnc_handleInfoDisplayChanged.sqf#L20-L21

**Comment by IanBones** [comment]
Just tried it in the Editor with different difficulty settings but had no change.
Checking with
`if (cadetMode) then {hint"CADETMODE"} else {hint"NO"}`
allways tells me I'm in cadetMode

Our Server runs on Custom difficulty.

**Comment by bux** [comment]
Might be better to use https://community.bistudio.com/wiki/difficulty here

**Comment by cych** [comment]
Are the parachute still magically repacking itslf after landing ?
