### ISSUE TITLE
Advanced Fatigue doc first link is down

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#5602]
https://ace3mod.com/wiki/feature/advanced-fatigue.html

Link to Bohemia Interactive Simulations doc is down.

**Comment by BaerMitUmlaut** [comment]
>VBS Manuals are no longer online, please refer to the docs folder in your VBS product installation, or contact support if you have any questions or need further information.
https://bisimulations.com/support/manuals

Guess we'll just have to remove the link.
