### ISSUE TITLE
Cookoff

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#5604]
**Arma 3 Version:** `last stable 
**CBA Version:** `3-10-2
**ACE3 Version:** last

**Mods:**
```
- CBA_A3
- ace
```
mod cookoff very much change the armor of objects. may not even armor, but their blasting resistance. the idea with the ignition of ammunition is good, but no one plays with it, and those who play can not understand why cars (mostly lightweight class "car") become almost undestroyeble

You can try it in the editor yourself. about the compatibility with other modes such as RHS, I generally keep quiet. there "gas-tiger" or BTR-60-70-80 rus like as terminators. It's time to do something about it, it's a pity to throw out this idea all the time. and these sounds of scattered bullets - just horror))
(sry for my google-english)

fo rexample vanilla arma
https://www.youtube.com/watch?v=C3zX251WSfM&feature=youtu.be

**Comment by dedmen** [comment]
Your CBA version doesn't exist. If I interpret these dashes as dots.. Otherwise it's still incorrect.
What is the "last" ACE version for you? We need exact numbers.. Not someone that might be on a very outdated version saying "I'm on the last version".

**Comment by jonpas** [comment]
**Fill out the issue fully as per the template given, you are missing half of the things.**

ACE3 cookoff doesn't change armor of objects at all. Cars are definitely destroyable, they just won't cookoff because they have no ammo on them.

As for your second paragraph, we are not RHS, go to RHS issue tracker to report RHS issues. We don't change armor values of any of them, and never will, all we do is provide compatibility for some features out of courtesy (because they refuse to).

**Comment by topden** [comment]
ok

**Comment by KalleK-OPT** [comment]
Arma 3 Version: 1.80 (stable)
CBA Version: 3.6.0.180131 (stable)
ACE3 Version: 3.12.1 (stable)

Mods:

- CBA_A3
- ace3
- CUP Terrains 1.4.2.
- CUP Maps 1.4.2.

Description:

After various tests, we came to notice, that the vehicle damage (handledamage.sqf) coming into play with the general cookoff feature enabled (first box to tick in the cba-settings) brings about dramatic changes when it comes to the vanilla NATO AA-tank Cheetah in comparison with most other tanks (no matter which vanilla faction)...
While all other vehicles are destroyed with 1-4 rockets (no matter if RPG32, Titan or AG-missiles), the cheetah is still active after 14-25 rounds and even then will not explode (with most parts being in red or orange status)

Steps to reproduce:

enable ace cookoff (with related vehicle destruction effects) -> cook-off probability on a low value -> place cheetah/tanks in editor or on server -> fire at them in a good angle ... result as described above
disable ace cookoff (with related vehicle destruction effects) -> place cheetah/tanks in editor or on server 

-> fire at them in a good angle ... cheetah will blow as all other tanks

Where did the issue occur?

- Dedicated
- Editor

Placed Modules:
- None

related document:
https://i.imgur.com/xhTzgBj.png
