### ISSUE TITLE
ACE Linux server compatability

### ISSUE THREAD

**Issue by Kai-Holmes** [acemod/ACE3#5608]
Good afternoon, I'm attempting to run a server featuring ACE on a CentOS 7 server.

Will ACE fault due to the lack of .so or will it simply function through the use of .sqf and .pbo information?

**Comment by PabstMirror** [comment]
For dedicated servers, linux will work just fine
It will fallback to using sqf instead of dlls.

**Comment by Kai-Holmes** [comment]
Brilliant, thank you.
