### ISSUE TITLE
Quick Mount MP issues

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#5611]
Mods:
CBA - 3.4.1.170912
RHS 0.4.2.2
ACE - 3.10.2
Arma - Stable 
Windows Dedi Cloud Server

Think there may be an issue with ace quick mount and vehicles that have two gunner positions/weapons like the modern GAZ from RHS with the pkm and 40mm GL for the turret, the drivers seat, gunner seat, and front passenger/commander were all taken when I tried to quick mount the GAZ as they drove past and instead of putting me in a passenger seat at the back, I crossed the ethereal plane and merged my soul with the person who was already in the gunner seat, effectively I was put in first-person spectator mode of the gunner, only thing I could do was watch or hit ESC and DC.

Only been able to trigger it a few times since the feature was added to ace, seems to only happen in ops

**Comment by kneegrew** [comment]
Same happened, tried to get into the same vehicle /w someone. He used action menu, I used quickmount a bit after he used the action menu

**Comment by PabstMirror** [comment]
`rhs_tigr_sts_vdv` is fascinating, the pkm and asg are separate turrets
change weapons key is hooked to have player swap turrets and lock the other one
