### ISSUE TITLE
script error in frag/spall

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#5614]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- look RPT

**Steps to reproduce:**
- throw nade

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**RPT log file:**
- https://gist.github.com/shukari/972efd20bca34867bb11b5cc39c676a4

**Comment by Dystopian** [comment]
info: this script error was there at least 1 year ago, I didn't report it because spall code looked not finished and I just disabled spalling.

**Comment by badkneegrow** [comment]
if (!lineIntersects [_pos1, _pos2]) exitWith >
```sqf
23:20:27   Error position: <lineIntersects [_pos1, _pos2]) exitWith >
23:20:27   Error 0 elements provided, 3 expected
23:20:27 File z\ace\addons\frag\functions\fnc_doSpall.sqf, line 49
23:20:27 Error in expression <torMultiply (0.01 * (_i + 1)));
```

shooting at `I_Truck_02_ammo_f`

**Comment by badkneegrow** [comment]
Still get spalling bug 2018

**Comment by badkneegrow** [comment]
using vanilla weapons / ACRE2. But other mods loaded. Can post RPT

**Comment by dedmen** [comment]
https://github.com/acemod/ACE3/blob/81722abeac020654531ad853dda2ee8aa7b8d9f2/addons/frag/functions/fnc_doSpall.sqf#L63
Interesting that the line number is so far... Ah no.. Makes sense.
`_pos` can be nil I guess. I think I encountered that too in the Intercept port.

**Comment by dedmen** [comment]
Why close this if it's not fixed?

**Comment by shukari** [comment]
I suppose someone said that spall never was ready and is since years in WIP. So this issue will never finished.
Are im wrong?

**Comment by KHunter-Arma** [comment]
I still don't think closing is helpful. The module is included in the release, might as well have it remain on the list of things to resolve...

**Comment by shukari** [comment]
So then here... reopen for the backlog.

**Comment by Neviothr** [comment]
Happens with spall disabled as well.

**Comment by Dystopian** [comment]
> Happens with spall disabled as well.

since I disabled it months ago I didn't saw it.

**Comment by KHunter-Arma** [comment]
I confirm on my end I don't see the error since I disabled spall. You sure you have it disabled?

**Comment by KHunter-Arma** [comment]
Thanks for looking into this, but am I missing something or were these changes supposed to be a complete fix for this? Because I thought I'd give spall another go after the changes and I'm still seeing this spammed  :\

`if (!lineIntersects [_pos1, _pos2]) exitWith >
20:53:24   Error position: <lineIntersects [_pos1, _pos2]) exitWith >
20:53:24   Error 0 elements provided, 3 expected
20:53:24 File z\ace\addons\frag\functions\fnc_doSpall.sqf, line 53
20:53:24 Error in expression <torMultiply (0.01 * (_i + 1)));`
