### ISSUE TITLE
Fueling non-fuelable objects with JerryCan/Nozzle?

### ISSUE THREAD

**Issue by L01D** [acemod/ACE3#5616]
Fueling a generator with Jerry Can/Petrol Pump.

I have tried using the framework:

2.2 Make a jerry can
ace_refuel_fnc_makeJerryCan

Arguments	Type	Optional (default value)	 
0	My Object	Object	Required
1	Fuel amount (in liters)	Number	Optional (default: 20)
R	None	None	Return value
2.2.1 Example 1
[can] call ace_refuel_fnc_makeJerryCan;

Arguments	Explanation	 
0	can	My jerry can object
The jerry can will have the default 20 liters volume.

2.2.2 Example 2
[can, 200] call ace_refuel_fnc_makeJerryCan;

Arguments	Explanation	 
0	can	My jerry can object
1	200	Vehicle class name
The jerry can will now have a volume of 200 liters.

It seems you cannot fill a jerry can with another jerry can  any ideas?

**Comment by Dystopian** [comment]
You can not refuel non-vehicles.
Jerrycan can be refilled only with `ace_refuel_fnc_setFuel` function.
