### ISSUE TITLE
Can't treat myself

### ISSUE THREAD

**Issue by jedrekdomanski** [acemod/ACE3#5632]
**Arma 3 Version:** `1.76` stable
**CBA Version:** `3.4.1` stable
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.
I am unable to treat myself. Whenever I get shot and am bleeding no matter how many bandages, morhpine, epinephrine I use, I still bleed, my character moans, the screen gets blurry and gets red edges. None of the parts of my body are showing yellow on the self interaction 'Medical' menu so this means I am not hurt but my character still moans severely and has blood on my arms.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

Get shot, use bandages, morphine, etc.
Interestingly, this never happened on Multiplayer mode, only on Singleplayer mode.

**Where did the issue occur?**
After I got shot by NATO police.
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
Singleplayer

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.
Only CBA_A3 and ACE 3
**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

https://pastebin.com/Nh3w0vgL

- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by commy2** [comment]
```sqf
20:57:58 Error in expression <,false];
 
if(isNil "_identity" or count _identity == 0) then {
_identity = call >
20:57:58   Error position: <_identity == 0) then {
_identity = call >
20:57:58   Error Undefined variable in expression: _identity
20:57:58 File \ot\functions\virtualization\spawners\fn_spawnCivilians.sqf [OT_fnc_spawnCivilians], line 126
20:57:59 Error in expression <(_this select 0) setname (_this select 1)>
20:57:59   Error position: <setname (_this select 1)>
20:57:59   Error Type Any, expected String
20:57:59 Error in expression <ntity]"
params ["_unit","_identity"];
 
_identity params ["_face","_clothes","_n>
20:57:59   Error position: <_identity params ["_face","_clothes","_n>
20:57:59   Error Undefined variable in expression: _identity
20:57:59 File \ot\functions\AI\NPC\fn_applyIdentity.sqf [OT_fnc_applyIdentity], line 3
20:57:59 Error in expression <,_vest] call OT_fnc_initCriminal;
[_civ,_identity] call OT_fnc_applyIdentity;
[_>
20:57:59   Error position: <_identity] call OT_fnc_applyIdentity;
[_>
20:57:59   Error Undefined variable in expression: _identity
20:57:59 File \ot\functions\virtualization\spawners\fn_spawnCivilians.sqf [OT_fnc_spawnCivilians], line 131
```
The mission or a mod is broken. Retry without any other mods besides CBA_A3 and ACE on an empty mission (e.g. editor).

**Comment by dedmen** [comment]
>Mods: ACE,CBA

>"-mod=C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CBA_A3;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@ace;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Overthrow"

🤔

**Comment by commy2** [comment]
Looks like it.

**Comment by jedrekdomanski** [comment]
@commy2 I have tried in an Editor without any mods, I hurt myself and was able to treat myself fine.
