### ISSUE TITLE
"Broken Bones" occurs way too often

### ISSUE THREAD

**Issue by erenior** [acemod/ACE3#5638]
@CBA_A3 and @ace

I am not a scripter, nor a server owner. i play on two servers, both running ace and cba_a3 and both with a very similar kind of "issue" (not a real bug or glitch, but annoying as f***)

broken arms and/or legs happen way too often. players appreciate a hit to the head or torso way more as to the peripherals.

i know that broken bones can happen in a fight and i totally agree with the fact that this should stay implemented... but not in the actual manner.

therefore i do have different ideas on a solution

1. reduce via some sort of parameter the chance of getting a broken bone.

2. let ace3 check what the weapon was that caused the hit, smaller firearms should reduce the chance of getting a broken bone. ranging like from pistols to airstrikes if u know what i mean.

3. implement an item like "sam splint" for the medic class that can (temporarily) fix the broken bone, or at least reduce the effect of a broken bone by percentage

4. let ace3 check what the weapon was and what wound it created. example: you get shot by a 5.56, which is a medium firearms (so to say) and it usually creates medium wounds. medium wounds only have a 25% chance of breaking bones. 7.62 has a 50% chance of broken bones. a mortar of 90% etc the smaller the wound the less chance of getting a broken bone (but with this average assault rifles should do normal wounds)

my englisch isnt the best but i hope you get the point. to be honest, right now it just sucks... i love realism, but i bet i can shoot myself with a riflle in my arm and wont hit the bone at all =/

**Comment by Tittoffer** [comment]
I agree, broken bones are very annoying. This could however be tweaked in the Medical System Settings I believe. I like the idea of adding a sort of sam splint to arms and legs!

**Comment by dedmen** [comment]
The Arma/CBA/ACE versions you listed are wrong... wait... You didn't list any.
There is a issue template for a reason https://github.com/acemod/ACE3/blob/master/.github/ISSUE_TEMPLATE.md

Broken Arms? Arms cannot break. So I have no Idea what you are talking about. Also ACE doesn't simulate broken limbs at all.

**Comment by tbeswick96** [comment]
What you are saying is broken bones is really just injured limbs. If you take a round through the thigh the bone might not break, but you're damn well gonna be limping.

**Comment by Cuel** [comment]
Are you talking about limping? That's vanilla

**Comment by PabstMirror** [comment]
Do you use advanced medical?
If so there is a setting healHitPointAfterAdvBandage that might work great for you as it allows simple bandages to remove limping instead of requiring more advanced treatment.

**Comment by kripto202** [comment]
Or not get shot in the leg. The limping is vanilla.
