### ISSUE TITLE
Medsystem's ragdoll enchancement, gestures&shouldertap shortcuts.

### ISSUE THREAD

**Issue by Vestroso** [acemod/ACE3#564]
One thing that always rubbed me the wrong way, was the animation of a man remaining unconscious. Thanks to it, you could check whether your patient is dead or not, without even approaching to him. Is he lying on his stomach, with his hands in front of him? Well, there's a chance for him to be rescued! As far as I've read on some forums, there are ways to make a living player, a ragdoll,  eg. it's described here: http://killzonekid.com/arma-scripting-tutorials-forced-ragdoll/

I think, there's no need to write essays on the second point - there was a thing in AGM, that helped me maintain dynamism of my actions. These helpful things were shortcuts. With only two consecutive clicks, I could tap my friends' shoulders in CQC, or wave to my teammates, signaling something. I really missed it when playing on ACE3.

My apologies, if I adressed this topic to a wrong board, I was directed straight here. If there are some problems with it's emplacement, I'd humbly move it elsewhere.

Glad I could hopefully help,
Vestroso.

**Comment by jaynus** [comment]
please follow our feature request guidelines http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
