### ISSUE TITLE
[Interaction] give showDisabled functionality 

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#5642]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable
**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- showDisabled has no function atm -> https://github.com/acemod/ACE3/blob/ffaa195fe576625f052eeee04b1af9f3f377434f/addons/interact_menu/functions/fnc_collectActiveActionTree.sqf#L90
the only workaround is to use a fake statement like `statement = "_nothing = nil";`

**Steps to reproduce:**
- use it

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by jonpas** [comment]
This is really not needed for the ACE3 interaction menu, there are no greyed out interactions, it is a remnant of AGM's interaction system.

Why would you want an interaction without something happening when you select it though?

**Comment by shukari** [comment]
To show the mainaction if no childrens are active... the mainaction also has informations per modifier in my example...
They shouldnt grey... a group action should be marked as always shown so if no child is active.... you see that there is an action but no active childrens atm available...

**Comment by 654wak654** [comment]
So modify the base action's condition appropriately?

**Comment by shukari** [comment]
The base action will not show if it has no statement and no active childrens are there... i wrote down a workaround but this attribute is extra for this case... or?

**Comment by AACO** [comment]
Just curious, what's the use case if the node doesn't have any actions/active children? The action menu is... well.. action based. Each node either performs an action, or leads to an action. Having a leaf do nothing seems backwards to the system.

**Comment by shukari** [comment]
I need it quite often... to show the user that thing has an interaction menu but some things are missing....

**Comment by PabstMirror** [comment]
Just add a dummy statement and the action will show
action is hidden if no children and `_statementCode isEqualTo {}`
```
_condition = { true };
_statement = { private _z = 0; };
_action = ["MyActionBase","Base","",_statement,_condition] call ace_interact_menu_fnc_createAction;
[player, 1, ["ACE_SelfActions"], _action] call ace_interact_menu_fnc_addActionToObject;
```
