### ISSUE TITLE
Repair sound

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#5653]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- I've noticed, that the sound file of the repairing actions and wheel changing, is only played, when the weapon is shouldered, or you have no weapon at all.

**Steps to reproduce:**
- place a damaged vehicle and a repair specialist on map, start mission and repair the vehicle. you hear no sound during the repair action. do it all again, this time with you weapon shouldered. you hear sounds of the repair action.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Placed Modules:**
- None.

**RPT log file:**
- not needed

**Comment by Dystopian** [comment]
what I found: `player switchMove "Acts_carFixingWheel"` sometimes plays sound, sometimes not, I haven't managed to find stable repro.

**Comment by commy2** [comment]
Remove the sound from config and use `playSound3D`?

**Comment by Dystopian** [comment]
I'm working on it.
