### ISSUE TITLE
After or before carry/ dragging a static weapon, some time it is not possible to change the character stance.

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5655]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
-JSRS Sound mod
-ASR AI mod
```

**Description:**
- We know perfectly that AI (static weapons carriers) will not be able to instal a static weapons in the right direction, in relation to the enemy.  In this case, after the AI ​​has mounted the any static weapon, the player has to use the excellent ACE3 option - carry / drag of static weapon. Here can be problem for player if he comes under fire! 
 _Simple situation:_ 
You turned the static weapon in the right direction, but at this point the enemy is already shooting at you! You release of this weapon and at this moment player see the slow and not combat animation of transferring primary weapons from the back to the character's hands. Exactly at this moment, being under fire, you can not change the player stance. Player can not crouch/prone, but still he can move to the right, to the left!  Pay attention, it looks illogical! If the player is able to move to the right or left of the same must be able to change the stance, since under the fire this can be the most useful choice for the player.  
Changing the stance will also not work if the player tries to install the weapon. Namely before carry/ dragging. During animation of transferring primary weapons from the back to the character's hands. 
ACE team please give to the player the opportunity to control the character (change the stance) before or after carry/ dragging the static weapon.

**Steps to reproduce:**
1. carry/dragg any static weapon
2.  Imagine that you under fire and release this weapon and try change your stance to hide from bullets. This not will work/
At such moments I'm ready to break my keyboard...

or

1. approach the installed static weapon
2. use carry/dragg any static weapon
3. at this moment, Imagine that you under fire! Try change your stance.  This not will work/
At such moments I'm ready to break my keyboard...

In fact, the problem is that during the specific animation of transferring primary weapons from the back to the character's hands, there is no way to change the stance

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- none

**Comment by BaerMitUmlaut** [comment]
I remember you complaining about the instant transition with the medical animations, which would be the solution here. Unless you provide a better animation, of course.

Besides, static weapon are quite heavy, I think it's fair that it takes a while to position them.

**Comment by commy2** [comment]
I don't see what this has to do with putting down a weapon specifically. It's more like wanting to be able to go prone in the rifle-back-in-hands transition. I guess this is a good idea, but also a feature request.

**Comment by ZeusWrath** [comment]
> I remember you complaining about the instant transition with the medical animations, which would be the solution here. Unless you provide a better animation, of course.

Sorry but I can not remember what you're talking about

> Besides, static weapon are quite heavy, I think it's fair that it takes a while to position them.

Why are you a guy? If you put a static turret and you are being fired, can not you let it go, or at least just sit down? Near the player, grenades explode and bullets fly, but the player sees how his character sloooooooooooowly takes the weapon from the back, as if nothing happens!  What we see in this case is a bug and it needs to be fixed.

> I don't see what this has to do with putting down a weapon specifically. It's more like wanting to be able to go prone in the rifle-back-in-hands transition. I guess this is a good idea, but also a feature request.

The player can not - crouch/prone until he starts to install weapons and after the moment the weapon is already installed. There is a direct relationship. I have not tried to understand whether it works - crouch/prone at other moments of the game, when the player character just strolls with arms behind her back, since such moments practically do not happens in the game. In any case, if you can solve the problem of an uncontrolled character while moving his weapon from behind to your hands, then you can solve at least 2 problems at a time.
