### ISSUE TITLE
5.56mm Reload. Tracers don't work

### ISSUE THREAD

**Issue by tiapfy** [acemod/ACE3#5656]
Arma 3 Version: 1.76 stable
CBA Version: 3.4.1 stable
ACE3 Version: 3.10.2 stable

Mods:
- CBA_A3
- ace
- task_force_radio

Description:
Reload. Tracers for every 5.56mm assault rifle don't have tracers

Steps to reproduce:
- take any 5.56mm assault rifle;
- load Reload. Tracers of any color;
- start shooting.

Where did the issue occur?
- I tested it in a Dedicated server and in Editor (SP)

Placed Modules:
tested with no modules;
tested with:

- Adv. Fatigue;
- Captives Settings;
- Medical Settings;
- Respawn Settings;
- Revive Settings;
- Set Medic Class;

RPT log is not available.

**Comment by Dystopian** [comment]
works for me

**Comment by tiapfy** [comment]
> Works for me.
Add RPT file.

I used 5.56 mm 30rnd STANAG Reload Tracer Mag and I haven't seen any tracer.
I don't think RPT may explain this, I have done tests in the editor.

**Comment by Dystopian** [comment]
I used 5.56 mm 30rnd STANAG Reload Tracer Mag and I do have seen any tracer.

**Comment by RaiderSpectre** [comment]
i confirm this issue.

in this video i tested this magazines:
1- 5.56mm 30Rnd Mag <---no tracers at all
2- 5.56mm 30Rnd STANAG Reload Tracer (red)/(green) Mag <---no tracers at all, bugged?
3- 5.56mm 30Rnd Trader Mag  red/green   <--- only this one has tracers


https://www.youtube.com/watch?v=FwTQFhZjGyI

**Comment by Dystopian** [comment]
Sorry, I didn't even know about `STANAG Reload Tracer (Red) Mag` existence O_O.
In vanilla `5.56mm 30Rnd Mag` has yellow reload tracers, and `Reload red/green` mags just modify tracer color. In ACE STANAG reload tracers were disabled https://github.com/acemod/ACE3/blob/34849426805cdfa81180a53480c15e11cdea1ed2/addons/smallarms/CfgMagazines.hpp#L16 and red/green mag reload tracers were disabled by inheritance.
We can enable reload tracers just for red/green mags. Anyway we need someone responsible.
@KoffeinFlummi @commy2 ?

**Comment by commy2** [comment]
I copy pasted the relevant configs from the base game.
```cpp
class 30Rnd_556x45_Stanag: CA_Magazine {
	displayName = "5.56 mm 30rnd STANAG Reload Tracer (Yellow) Mag";
	tracersEvery = 0;
	lastRoundsTracer = 4;
};

class 30Rnd_556x45_Stanag_green: 30Rnd_556x45_Stanag {
	displayName = "5.56 mm 30rnd STANAG Reload Tracer (Green) Mag";
	ammo = "B_556x45_Ball_Tracer_Green";
};

class 30Rnd_556x45_Stanag_red: 30Rnd_556x45_Stanag {
	displayName = "5.56 mm 30rnd STANAG Reload Tracer (Red) Mag";
	ammo = "B_556x45_Ball_Tracer_Red";
};

class 30Rnd_556x45_Stanag_Tracer_Red: 30Rnd_556x45_Stanag {
	displayName = "5.56 mm 30rnd Tracer (Red) Mag";
	tracersEvery = 1;
};

class 30Rnd_556x45_Stanag_Tracer_Green: 30Rnd_556x45_Stanag {
	displayName = "5.56 mm 30rnd Tracer (Green) Mag";
	tracersEvery = 1;
};

class 30Rnd_556x45_Stanag_Tracer_Yellow: 30Rnd_556x45_Stanag {
	displayName = "5.56 mm 30rnd Tracer (Yellow) Mag";
	tracersEvery = 1;
};
```

`30Rnd_556x45_Stanag`, `30Rnd_556x45_Stanag_green` and `30Rnd_556x45_Stanag_red` all don't have tracers except for their last 4 rounds. ´This was removed at some point and probably because this behavior was not reflected by their display name.

The same applies to:
```cpp
class 30Rnd_9x21_Red_Mag: 30Rnd_9x21_Mag {};
class 30Rnd_9x21_Yellow_Mag: 30Rnd_9x21_Mag {};
class 30Rnd_9x21_Green_Mag: 30Rnd_9x21_Mag {};

class 30Rnd_9x21_Mag_SMG_02_Tracer_Red: 30Rnd_9x21_Mag_SMG_02 {};
class 30Rnd_9x21_Mag_SMG_02_Tracer_Yellow: 30Rnd_9x21_Mag_SMG_02 {};
class 30Rnd_9x21_Mag_SMG_02_Tracer_Green: 30Rnd_9x21_Mag_SMG_02 {};
class 16Rnd_9x21_red_Mag: 16Rnd_9x21_Mag {};
class 16Rnd_9x21_green_Mag: 16Rnd_9x21_Mag {};
class 16Rnd_9x21_yellow_Mag: 16Rnd_9x21_Mag {};

class 30Rnd_762x39_Mag_F: CA_Magazine {};
class 30Rnd_762x39_Mag_Green_F: 30Rnd_762x39_Mag_F {};

class 30Rnd_545x39_Mag_F: CA_Magazine {};
class 30Rnd_545x39_Mag_Green_F: 30Rnd_545x39_Mag_F {};
class 200Rnd_556x45_Box_F: CA_Magazine {};
class 200Rnd_556x45_Box_Red_F: 200Rnd_556x45_Box_F {};
```

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/blob/master/addons/smallarms/CfgMagazines.hpp#L126

From checking all the configs, the same should apply to: `30Rnd_9x21_Red_Mag`, `30Rnd_9x21_Yellow_Mag`. `30Rnd_9x21_Green_Mag`. Please also check all of these if you fix this issue.
I can't find any other, but may have missed something.

**Comment by commy2** [comment]
>We can enable reload tracers just for red/green mags.

`30Rnd_556x45_Stanag` is named `5.56 mm 30rnd STANAG Reload Tracer (Yellow) Mag`. Yellow is not mentioned in the classname, but the display name. The fix should apply to all three.

**Comment by commy2** [comment]
Magazines named "Reload Tracers" in the base game:
```cpp
class 30Rnd_9x21_Red_Mag: 30Rnd_9x21_Mag {};
class 30Rnd_9x21_Yellow_Mag: 30Rnd_9x21_Mag {};
class 30Rnd_9x21_Green_Mag: 30Rnd_9x21_Mag {};

class 30Rnd_9x21_Mag_SMG_02_Tracer_Red: 30Rnd_9x21_Mag_SMG_02 {};
class 30Rnd_9x21_Mag_SMG_02_Tracer_Yellow: 30Rnd_9x21_Mag_SMG_02 {};
class 30Rnd_9x21_Mag_SMG_02_Tracer_Green: 30Rnd_9x21_Mag_SMG_02 {};
class 16Rnd_9x21_red_Mag: 16Rnd_9x21_Mag {};
class 16Rnd_9x21_green_Mag: 16Rnd_9x21_Mag {};
class 16Rnd_9x21_yellow_Mag: 16Rnd_9x21_Mag {};

class 30Rnd_762x39_Mag_F: CA_Magazine {};
class 30Rnd_762x39_Mag_Green_F: 30Rnd_762x39_Mag_F {};

class 30Rnd_545x39_Mag_F: CA_Magazine {};
class 30Rnd_545x39_Mag_Green_F: 30Rnd_545x39_Mag_F {};
class 200Rnd_556x45_Box_F: CA_Magazine {};
class 200Rnd_556x45_Box_Red_F: 200Rnd_556x45_Box_F {};
```

______

From checking all the configs, the same **bug** should happen with: `30Rnd_9x21_Red_Mag`, `30Rnd_9x21_Yellow_Mag`. `30Rnd_9x21_Green_Mag`.

https://github.com/acemod/ACE3/blob/master/addons/smallarms/CfgMagazines.hpp#L126

Please also check all of these if you fix this issue.

I can't find any other, but may have missed something.

**Comment by RaiderSpectre** [comment]
i tested this ones, and it seems that **they all work correctly**:

https://youtu.be/YC5W9kjLUfM
9mm 30Rnd Reload Tracer (Green) Mag   /   "30Rnd_9x21_Mag_SMG_02_Tracer_Green"
9mm 30Rnd Reload Tracer (Yellow) Mag   /   "30Rnd_9x21_Mag_SMG_02_Tracer_Yellow"
9mm 30Rnd Reload Tracer (Red) Mag   /   "30Rnd_9x21_Mag_SMG_02_Tracer_Red"

https://youtu.be/bTF_0-6uIC4
9mm 30Rnd Reload Tracer (Red) Mag   /   "30Rnd_9x21_Red_Mag"
9mm 30Rnd Reload Tracer (Yellow) Mag   /   "30Rnd_9x21_Yellow_Mag"
9mm 30Rnd Reload Tracer (Green) Mag   /   "30Rnd_9x21_Green_Mag"

**Comment by commy2** [comment]
But what about `30Rnd_9x21_Mag` (no _Red_)?

**Comment by Dystopian** [comment]
`30Rnd_9x21_Mag` has no configured `lastRoundsTracer` in vanilla, so it's OK.
