### ISSUE TITLE
Changin box altitude teleports them to the ground of the sea

### ISSUE THREAD

**Issue by Mezilsa** [acemod/ACE3#5658]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- If you change the altitude of a box while over water the box changes position far down and leaves your hands and goes swimming ( I guess a little mixup of getPosATL and getPosASL)

**Steps to reproduce:**
- Place a object over water so you can walk.
- place a soldier and a box
- grab the box 
- move it down
- get a diver to move it back up next patch

**Where did the issue occur?**
- Dedicated Singleplayer / Editor (Singleplayer)

**Comment by commy2** [comment]
>I guess a little mixup of getPosATL and getPosASL

Sounds more like ATL vs. AGL.

**Comment by Mezilsa** [comment]
Aye. My bad.
