### ISSUE TITLE
Script z\ace\addons\wep_javelin\XEH_pre_init.sqf not found

### ISSUE THREAD

**Issue by MarcBook** [acemod/ACE3#566]
ACE3-Version newest Build

Error-Message on start:
Script z\ace\addons\wep_javelin\XEH_pre_init.sqf not found

**Comment by bux578** [comment]
There's no wep_javelin in master. Your build can't be that new, or you have some left overs in your addon folder.

For future reference, all bug reports need to comply with this guideline:
http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by PabstMirror** [comment]
Delete all .pbo files and rebuild.

**Comment by esteldunedain** [comment]
The binarizer script doesn't delete old pbos yet. So you're stuck with an old version of wep_javelin that doesn't exist any longer. Just delete it manually

**Comment by bux578** [comment]
He maybe should delete all *.pbo's... just in case

**Comment by MarcBook** [comment]
OK, it was an old *pbo.
Can close issue.
