### ISSUE TITLE
"Quick Tag" keybind only works after using ace menu first

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#5662]
Arma3 - stable
CBA - 3.4.1.170912
ACE - 3.10.2

**Mods:**
TFR - 1.-1.0.264
Lots of other shite...

**Description:**
- Quick-Tag keybind only works after you have placed a tag using the ace interaction menu first, after that it works fine

**Steps to reproduce:**
- Try placing a tag using the keybind method (it will not work) place a tag using the ace menu (it will work), now place another tag using your keybind (it will work)

**Where did the issue occur?**
- Dedicated Windows Cloud

**Comment by PabstMirror** [comment]
Check your ace settings for the Tagging - Quick Tag setting
If it's set to disabled it won't work at all
If it's set to last used it won't work until placed via interaction menu

**Comment by Snak3Doc** [comment]
Ahh i see how the "last used" works now, would it be possible to modify the function so if the player hasn't placed a tag through interaction yet it just uses the first spray paint color alphabetically in their inventory.

**Comment by Snak3Doc** [comment]
Thanks :)
