### ISSUE TITLE
Pylon Interface PixelGrid

### ISSUE THREAD

**Issue by tbeswick96** [acemod/ACE3#5663]
Change Pylons interface to use pixelGrid to solve layout issues as discussed in https://github.com/acemod/ACE3/pull/5661

**Comment by dedmen** [comment]
Milestone is ongoing. Thus don't close this you bot.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
