### ISSUE TITLE
Load Into Cargo Zeus Module is broken

### ISSUE THREAD

**Issue by kamkill01011** [acemod/ACE3#5668]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The "Load Into Cargo" Zeus Module works exacly the same as the "Suppressive Fire" Zeus Module.

**Steps to reproduce:**
- Just try the module (on a unit).

**Where did the issue occur?**
-Self-Hosted Multiplayer / Editor (Singleplayer)

**Placed Modules:**
- none

**Comment by jonpas** [comment]
Caused by https://github.com/acemod/ACE3/blob/f30727e5665b9691d268f6a344b1063ca8db9d69/addons/zeus/functions/fnc_moduleLoadIntoCargo.sqf#L20. 😆
