### ISSUE TITLE
Key binding configuration

### ISSUE THREAD

**Issue by kapersky71** [acemod/ACE3#567]
not sure if this is the right place but really need the ability to configure the interaction keys as if you are using windows 8 it is impossible to interact with others

**Comment by jonpas** [comment]
You can using CBA keybinds (Options->Controls->Configure Addons->drop-down menu select ACE3). You can also disable windows button function in Windows 8 as far as I am aware.

**Comment by kapersky71** [comment]
i didn't know that thanks

**Comment by jonpas** [comment]
No problem, happy to help.
