### ISSUE TITLE
Two rounds in mortar (single loading setting)

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#5671]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Two people can load the mortar at the same moment and the mortar had then 2 rounds. Is it possible to make a mutex for this

**Steps to reproduce:**
- 2 guys load mortar at the same moment
- 2 rounds in mortar

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by BaerMitUmlaut** [comment]
I think the mortar should just explode.

**Comment by SilentSpike** [comment]
Easy enough to fix this, though would like to change how the mk6 module is handling events and locality. I started working on it, but re-realised I hate how arma handles turrets and their magazines.

If anyone else wants to take this one feel free, but wouldn't be opposed to pushing the milestone back to give more time to work on it.

**Comment by shukari** [comment]
@SilentSpike are you currently working on mortars?

**Comment by SilentSpike** [comment]
@shukari I was working on this issue back then, but haven't since then because I wanted to fix it by refactoring the code to work more cleanly in terms of locality (still might at some point, but want to help with medical stuff right now).

Your PR looks like the perfect solution for the way the code currently is though 👍

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/pull/5652 has fully network safe ammo loading
it should eventually replace the mk6 loading code, 
but for now #6240 should fix most problems
