### ISSUE TITLE
Players not bleeding out on dedicated server w/ Basic Medical

### ISSUE THREAD

**Issue by Varnski** [acemod/ACE3#5674]
**Arma 3 Version:**  latest public build
**CBA Version:**  3.4.1
**ACE3 Version:** 3.10.2

**Mods:**
```
- CBA_A3
- ace
- Task Force Radio
- Achilles
- ALiVE

```

**Description:**
I just got back into Arma after a long time and am trying to learn mission making again. I am trying to set things up so that when a player takes a hit that would normally kill them, they drop into an unconscious state and require a medic to be revived. I am trying to set a timer so that if a medic does not get to them within a set amount of time, they will bleed out and die. I have been able to get things working on a Listen/LAN server just fine. The issue comes when I take it over to my group's dedicated server. The units go down and never bleed out. I had the revive timer set to 60 seconds just for testing and we sat there for several minutes and the injured player never bled out. 

I understand that things can work differently between a local and dedicated server, I just have no idea how to get the modules to do what I want them to on the dedicated server. 

**Steps to reproduce:**
- placed down ACE medical modules
- exported mission to Multiplayer
- upload to server
- shoot people
- they never bleed out

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- ACE Basic Medical Settings (Medics only, anywhere)
- Medical Settings (default except prevent instant death is enabled)
- Revive Settings (Players, 60, -1)

I also have the ACE Friendly Fire, Hearing, and Zeus modules down but I don't see how they could be causing this issue.

**Comment by coachwn** [comment]
Do you have instant death enabled or disabled? That might be the culprit with Basic...just a shot in the dark from my side. I haven't used Basic Medical in so long I can't remember the settings.

**Comment by Varnski** [comment]
As stated I do have Prevent Instant Death enabled. Most of my players are relatively new to a more "hardcore" style of shooter and the few times we've played already they tend to die a lot. I don't want them dying to one shot but I still want there to be repercussions for being shot.

**Comment by bux** [comment]
Please update the version numbers in your issue and provide us with the requested RPT file.

**Comment by Varnski** [comment]
I do not have access to RPT files and version numbers are whatever the current public build is for all items.

**Comment by bux** [comment]
We've updated ACE on tuesday... so we need to know in which version that issue occured.

**Comment by Varnski** [comment]
Version numbers updated for what is on the server, can't seem to find the version of ACE that I'm running on my machine. If there was an update, that might explain some things. I did my testing on the 24th and as far as I know none of the mods on the server were updated.

**Comment by bux** [comment]
Maybe you can try it with the newest ACE version v3.11.0:
https://github.com/acemod/ACE3/releases/tag/v3.11.0

**Comment by Varnski** [comment]
Alright, updated the server with the newest edition and that seems to have fixed the issues with the medical system. I guess you can consider this issue resolved
