### ISSUE TITLE
Taru and Huron ammo containers not compatible with ace_pylons

### ISSUE THREAD

**Issue by Pergor** [acemod/ACE3#5677]
**Arma 3 Version:** `current` (stable)
**CBA Version:** `3.4.1.170912`
**ACE3 Version:** `3.11.0`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Taru and Huron ammo containers don't offer the pylons menu from ace_pylons yet. The ammo trucks work fine, but the containers don't.

**Comment by aristenn** [comment]
I've seen them work, but you almost have to have the aircraft parked on top of the container (And for rotary wing aircraft, good luck taking off)

**Comment by jonpas** [comment]
> (And for rotary wing aircraft, good luck taking off)

Rotors are overrated.
