### ISSUE TITLE
Spare Barrel should be under miscs, not magazines

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#5678]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- in VA the spare barrel is found in the magazine slot, but would be better placed under miscs.

**Steps to reproduce:**
- seek spare barrel in the VA.

**Where did the issue occur?**
- everywhere.

**Placed Modules:**
- none.

**Comment by jonpas** [comment]
https://github.com/acemod/ACE3/issues/5579#issuecomment-333423829 your own comment. 😆 
We can't change it with vanilla Arsenal.

**Comment by alganthe** [comment]
because it actually is a magazine for some reasons

**Comment by madpat3** [comment]
magazine, magazine, magazine... i'm running out of ammo!
not, bad joke. 
give me my medicine (ace) XD

**Comment by dedmen** [comment]
>We can't change it with vanilla Arsenal.
We can with ACE Arsenal @alganthe ?

**Comment by jonpas** [comment]
Closing then.
