### ISSUE TITLE
Not loading settings from serversettings.cfg

### ISSUE THREAD

**Issue by ndfmoab** [acemod/ACE3#5679]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `v3.4.1` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Ace 3 not loading settings from userconfig/ace/serversettings.cfg. I exported our settings after the recent ace update and saved them to the serversettings.cfg. Noticed that wheather synchronisation and finger pointing didn't work even though I had it enabled in the serversettings.cfg

**Steps to reproduce:**
- Export ace settings via export menu
- start Server with ace, cba and ace_server.pbo

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**

**Comment by Dystopian** [comment]
its name is `serverconfig.hpp`

**Comment by PabstMirror** [comment]
We had a problem with ace_server.pbo being binerized
we re-uploaded a fixed version quickly, but you may have gotten an early copy

Try redownloading from https://github.com/acemod/ACE3/releases/download/v3.11.0/ace3_3.11.0.zip

Only ace_server.pbo changed (no change to clients pbos or keys)

**Comment by ndfmoab** [comment]
Issue was resolved by reuploading the new ace_server.pbo

The mentioned serversettings.cfg was a typo...I had it as .hpp on the server.
