### ISSUE TITLE
Grenade torque should vary with throw type

### ISSUE THREAD

**Issue by Drofseh** [acemod/ACE3#5680]
**Arma 3 Version:** `1.76.143187` (stable)
**CBA Version:** `3.4.1` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The new grenade torque is always the same regardless of the type of throw.

**Steps to reproduce:**
- Play as any loadout with a grenade, try the three different ACE throws, watch grenade spin.

I was talking to @jonpas about how the new grenade torque looks great for the stick grenades in the various WW2 mods and suggested to him that each throw type should have it's own rotation speed, he asked me to make an issue for it.

My suggestion would be:
Normal - quick rotation
High - slow to moderate rotation
Drop - very little rotation

**Comment by jonpas** [comment]
I suggest no further config entries, but just fixed percentage for high throw, and either very very low or none for drop.

**Comment by Drofseh** [comment]
if high throw divide torque by 2 and if drop divide torque by 4, something like that

**Comment by jonpas** [comment]
That would be 50% and 25%, still too high for drop at least IMO.

**Comment by Drofseh** [comment]
yah, actual numbers would very, I just mean use that method
