### ISSUE TITLE
Deploying fastropes more than once broken on Taru (Bench)

### ISSUE THREAD

**Issue by Max255PL** [acemod/ACE3#5686]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ACE
```

**Description:**
- On Taru with benches after deploying ropes once and then cutting them, the option to deploy them again is not there. 
Also broken on 3rd party helos without the system (eg. MELB).
Every other helo with FRIES/option to prepare the system works ok. 

**Steps to reproduce:**
- Deploy fastropes from a passenger spot in Taru (Bench) (needs pilot in MP or putting the helo on something elevated in the editor with clear space under the bench)
- Cut the ropes
- Try to deploy them again
- Notice the lack of action

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:** 
https://pastebin.com/7qaeLh77

**Comment by madpat3** [comment]
also happens with the wildcats and the mi48.

**Comment by Crielaard** [comment]
Please do fix it. issue hasnt been resolved yet
