### ISSUE TITLE
animationPatientUnconscious not executed for CPR

### ISSUE THREAD

**Issue by Pergor** [acemod/ACE3#5693]
**Arma 3 Version:** `current`
**CBA Version:** `3.4.1.170912`
**ACE3 Version:** `3.11.0`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Not a new bug, but the
animationPatientUnconscious = "AinjPpneMstpSnonWrflDnon_rolltoback";
for CPR is not being executed when using CPR.

**Steps to reproduce:**
- Get unit that can receive CPR.
- Do CPR.
- Notice no "AinjPpneMstpSnonWrflDnon_rolltoback" on patient.

**Placed Modules:**
- Advanced Medical of course.

**Comment by thojkooi** [comment]
This is done by design. By default, patient animations are turned off.

To turn it on, set the following setting to true:

```c++
    class ace_medical_allowUnconsciousAnimationOnTreatment {
        value = 1;
    };
```

**Comment by Pergor** [comment]
Ah... I always thought this was just meant for the idle animations of unconscious units while being treated and not for the explicit commanded animations that are supposed to happen upon a certain action. I'll take a look at that, thanks for the tip!
