### ISSUE TITLE
Make Explosives AI compatible

### ISSUE THREAD

**Issue by CorruptedHeart** [acemod/ACE3#57]
Currently explosives might not entirely be AI compatible, I have never done any testing in that regard though.

From what I've seen of CSE, the modules could come in handy from the mission maker's side in setting up explosives and triggermen for those explosives. I'm not sure if there are in game commands that players can issue to AI units to place/defuse explosives but those will need to be looked at. I think defuse commands will work fine. Since internally Explosives eventually uses BIS's stuff for defusing.

**Comment by mickeymen** [comment]
Please fix it as soon as possible! This detail breaks the unique ability Arma3

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
