### ISSUE TITLE
Enable map illumination from custom light sources

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#571]
Map illumination should take into account custom lightsources added in the editor

**Comment by lukrop** [comment]
It does. At least a quick test with a "Land_LampHalogen_F" did affect the map lightning as one would expect.

**Comment by commy2** [comment]
Thats not what he means. I think this is about `"#lightsource" createVehicle`, which is, afaik, undetectable with scripting commands.

**Comment by esteldunedain** [comment]
> Thats not what he means. I think this is about "#lightsource" createVehicle,

Yes

>  which is, afaik, undetectable with scripting commands.

Mmm, too bad. 

As a workaround, could we create custom ace light sources that somehow work with this?

**Comment by KoffeinFlummi** [comment]
A potential solution could be to have a global array that mission makers can add their light sources to if they want...

**Comment by commy2** [comment]
Well or a lightource object that gets treated differenty than #lightsource.

Unfortunately there aren't even commands to reaad the current properties of a lightsource (e.g. a `setBrightness` command vs `setLightBrightness`)

Only solution I see would be a custom function in common to create and edit light sources.

**Comment by esteldunedain** [comment]
> Only solution I see would be a custom function in common to create and edit light sources.

That's the solution ^. MIssion makers usually copy paste logic with `"#lightsource" createVehicle` statements, which is a pain. We could either suggest they change that to an api call (which spatially caches the lights) or create a dummy object to put on the editor, with proper icon, etc, which on mission start calls the api

**Comment by commy2** [comment]
>Those would get used, specially if we make them a nice icon that shows the light color, etc
And advertise them.

Dunno about an editor object. Becaue you have enter the parameters somehow. Maybe a module?

**Comment by esteldunedain** [comment]
The point of the editor object would be to provide icons for different light colors and light intensities, so you can see at first glance how the mission is illuminated. If you want to add a super specific light type then a module would be good to have too

**Comment by Salluci** [comment]
Addressed by #8343.
