### ISSUE TITLE
ACE Hearing settings do not get applied via a mod config

### ISSUE THREAD

**Issue by ryanparsons7** [acemod/ACE3#5713]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1.170912` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- Ace User-config Mod
```

**Description:**
- When using a custom mod to force disable ACE Hearing settings via a user config included in the config.cpp, the settings do not get applied and the default settings are still used. I tested with Medical settings ontop of the hearing settings and those get applied correctly.

I have uploaded below the mod that I use to force the settings for ace hearing.
[@ace_settings.zip](https://github.com/acemod/ACE3/files/1426988/ace_settings.zip)

**Steps to reproduce:**
- Launch Arma 3 with CBA_A3, ACE and a custom mod/pbo to disable ACE Hearing.
- Go into Editor, Place Unit and Play as unit in either Singleplayer or Local Multiplayer.
- Shoot gun on full auto
- Ears ring and player starts to become deaf, indicating that ACE hearing is still enabled.

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- ACE (Debug to Clipboard): https://pastebin.com/3hrPXNDA

**Comment by PabstMirror** [comment]
I think it may be a mod load order issue, try using
`requiredAddons[] = {"ace_hearing"};`

otherwise your mod could run first and then ace_hearing runs and changes it back to default

**Comment by ryanparsons7** [comment]
That has seemed to fix the issue, Thank you!

If I plan to add a full export (Including client settings), What would be the best way of ensuring that my config gets loaded after all of ACE?

Once again, Thank you.

**Comment by PabstMirror** [comment]
I think the only way to be guaranteed safe is to just include every ace addon that you modify settings for
if you modify setting `ace_abc_x`, then include `ace_abc` in required addons
`requiredAddons[] = {"ace_hearing", "ace_medical", "ace_abc"};`
