### ISSUE TITLE
Fortify module and Fortify tool missing (ACEX)

### ISSUE THREAD

**Issue by Baraz-Siriel** [acemod/ACE3#5716]
**Arma:** 1.76
**CBA:** v3.4.1.170912
**ACE3:** 3.11.0
**ACEX:** 3.2.0 (late oct. 2017)

**Mods:**
Even by removing all mods except CBA, ACE3, the issue does not change. 

**Description:**
- In Eden Editor and Zeus, the Fortify module (ACEX) does not exist.  Nor does the relevant tool in the Arsenal.  
- There is an ACEX menu in Eden Editor that shows three modules (Headless, Sitting, View Restriction).

**Where did the issue occur?**
- Anytime in Edit Editor on Stratis Map (did not check on other maps). 
- Tool is not visible anywhere in Arsenal, even if the only mods loaded are the two dependencies. 

**Placed Modules:**
The basic ACE3 modules, like medical, repair. 
Same issue if default blank mission with no editor modules.

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/pull/5676

looks like we merged the documentation on the wiki already
it will be in ACEX 3.3 which hasn't been released yet (should be out soonish)

**Comment by jonpas** [comment]
It says right on top of the page: https://i.imgur.com/Fegwo33.png
