### ISSUE TITLE
ace 3 user features wont work

### ISSUE THREAD

**Issue by jclick45** [acemod/ACE3#5724]
![20171031_170915_resized](https://user-images.githubusercontent.com/33334021/32354962-7eb81418-bfe9-11e7-91cd-8f4651224fd9.jpg)
**Arma 3 Version:** `1.76` (stable / rc / dev)         
**CBA Version:** `3.4.1` (stable / dev + commit hash)
**ACE3 Version:** `3.11.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```Dagger weapons
virtual arsenal 2.0

**Description:**
- cannot open menu with "cont - win". Tried rebinding keys. Set keybinds for rangecards, nothing happens. I'm not sure if its doing anything at all, none of the features seem to work. Arma menu screen constantly has error code of some type on it, screenshot included. What do these warnings mean?
![20171031_170915_resized](https://user-images.githubusercontent.com/33334021/32354929-5d9751f4-bfe9-11e7-9e4d-51816343c612.jpg)


**Steps to reproduce:**
- Always happens, has never worked. Tried deleting and reloading multiple times

**Where did the issue occur?**
Singleplayer, eidtor

**Placed Modules:**
Not sure what a module is, game is relatively new to me

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by shukari** [comment]
You need the compat pbos in the "optionals" folder in the "@ace" mod to be placed in the "addons" folder to active use it. 
For rhs (ace_compat_rhs_usf3.pbo and so on)...

No ace problem. Can be closed!

**Comment by jclick45** [comment]
Ok, steam installed it, it wasn't a local so I figured they put it in the right place! I'll try to do that,  thank you very much!


Sent from my T-Mobile 4G LTE Device-------- Original message --------From: shukari <notifications@github.com> Date: 11/2/2017  5:27 PM  (GMT-07:00) To: acemod/ACE3 <ACE3@noreply.github.com> Cc: jclick45 <jclick45@gmail.com>, Author <author@noreply.github.com> Subject: Re: [acemod/ACE3] ace 3 user features wont work (#5724) 
You need the compat pbos in the "optionals" folder in the "@ace" mod to be placed in the "addons" folder to active use it.

For rhs (ace_compat_rhs_usf3.pbo and so on)...
No ace problem. Can be closed!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/acemod/ACE3","title":"acemod/ACE3","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/acemod/ACE3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@shukari in #5724: You need the compat pbos in the \"optionals\" folder in the \"@ace\" mod to be placed in the \"addons\" folder to active use it. \r\nFor rhs (ace_compat_rhs_usf3.pbo and so on)...\r\n\r\nNo ace problem. Can be closed!"}],"action":{"name":"View Issue","url":"https://github.com/acemod/ACE3/issues/5724#issuecomment-341587701"}}}

**Comment by jclick45** [comment]
Did not work, please respond so I don't have to open another problem!


Sent from my T-Mobile 4G LTE Device-------- Original message --------From: shukari <notifications@github.com> Date: 11/2/2017  5:27 PM  (GMT-07:00) To: acemod/ACE3 <ACE3@noreply.github.com> Cc: jclick45 <jclick45@gmail.com>, Author <author@noreply.github.com> Subject: Re: [acemod/ACE3] ace 3 user features wont work (#5724) 
You need the compat pbos in the "optionals" folder in the "@ace" mod to be placed in the "addons" folder to active use it.

For rhs (ace_compat_rhs_usf3.pbo and so on)...
No ace problem. Can be closed!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/acemod/ACE3","title":"acemod/ACE3","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/acemod/ACE3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@shukari in #5724: You need the compat pbos in the \"optionals\" folder in the \"@ace\" mod to be placed in the \"addons\" folder to active use it. \r\nFor rhs (ace_compat_rhs_usf3.pbo and so on)...\r\n\r\nNo ace problem. Can be closed!"}],"action":{"name":"View Issue","url":"https://github.com/acemod/ACE3/issues/5724#issuecomment-341587701"}}}

**Comment by shukari** [comment]
Steam override the changes... create a local ace3 mod use the arma 3 launcher to do this an change it there!
