### ISSUE TITLE
Feature Request - Adding additional 'scalar' values for common ACE3 maths functions

### ISSUE THREAD

**Issue by Steve161st** [acemod/ACE3#5725]
Add additional 'scalar' values to ACE3 maths functions to give more variability to mod makers in customising their mods.
E.g. ACE3 has good, physical maths for overheating of weapons when adding a suppressor. However, not all suppressors have the same construction resulting in different back pressure down the barrel and hence different barrel heating effects. (E.g. OSS suppressors have significantly less back pressure but at the expense of high mass and inertia.)
The final, current barrel heating maths are;
_energyIncrement = _energyIncrement * _silencerCoef;
So adding an extra scalar coefficient that can be included in the config file of the item would allow further fine tuning by mod makers. (If the additional coefficient is not found in the addon config file, it can be set to 1 by default.)
So the final maths might be:
_energyIncrement = _energyIncrement * _silencerCoef * _addonsilencerCoef;

There is a danger these additional 'fudge factors' could be abused by mod makers but I would hope that all mod makers that want the additional realism that ACE3 brings would use these additional coefficients to further enhance realistic, physical properties of items for increased choices/compromises and not for abusing the maths! 
Mods are made because people want choices so allowing things like 'heavier vs. less overheat/jam chance' add yet further to the depth of what ACE3 and other 3rd party mods already do.

**Comment by jonpas** [comment]
Ref also #5850 - merging issues.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
