### ISSUE TITLE
Enable Micro Dagr and Maptools illumination

### ISSUE THREAD

**Issue by meat147** [acemod/ACE3#573]
as stated above.

**Comment by PabstMirror** [comment]
I'm not sure what needs to be done to mapTools.  I think they look fine at night as they're mostly transparent and the map brightness seems to apply nicely to it.

![2015-06-21_00001](https://cloud.githubusercontent.com/assets/9376747/8272642/b2589852-1810-11e5-9a95-0a3f48d45f81.jpg)
