### ISSUE TITLE
M6 SLAM mine (side attack) - Defuse not work

### ISSUE THREAD

**Issue by hanczzzzz** [acemod/ACE3#5732]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
- CBA_A3
- ace

**Description:**
- Mine exploded, only (side attack)

**Steps to reproduce:**
- Try in editor, with Defusal Kit

**Where did the issue occur?**
- Editor (Singleplayer) / Virtual Arsenal

**Placed Modules:**
- none

**RPT log file:**
- https://pastebin.com/EVAtzXUm

**Comment by BaerMitUmlaut** [comment]
They have an anti tampering device which detonates it once somebody tries to defuse it. You can disable that in the module.

**Comment by hanczzzzz** [comment]
OK, Thank you.
- BTW, AI can defuse without explosion. I Suppose it is possible set in module too...
Bye. H.
