### ISSUE TITLE
make.py omits \functions\defines.h

### ISSUE THREAD

**Issue by Best2nd** [acemod/ACE3#575]
Game fails to start due to "make.py" omitting \functions\defines.h from "ace_advanced_ballistics.pbo" and "ace_kestrel4500.pbo". Game starts fine without these two PBO's.

**Comment by Best2nd** [comment]
Update:

It's not "make.py" at fault. It's my "pboProject" that's failing to include it. I'll see if reinstall fixes the issue.

**Comment by Best2nd** [comment]
Update 2:

It works fine with "build.py", but if I use "make.py" game throws an error with those two PBO's. Tried reinstalling pboProject with no luck.

**Comment by commy2** [comment]
What error? That ight help.

**Comment by Best2nd** [comment]
![defineserror](https://cloud.githubusercontent.com/assets/11899042/7135835/ee037e62-e2aa-11e4-8b85-d47971fd12d3.jpg)

The error is the same for ballistics.

**Comment by gienkov** [comment]
Same issue here

**Comment by esteldunedain** [comment]
Should be fixed on c827c72
