### ISSUE TITLE
Can't speak when being dragged

### ISSUE THREAD

**Issue by Avokadomos** [acemod/ACE3#5758]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- Task Force Radio
```

**Description:**
If you happen to wake up when you are unconscious and being dragged, you still can't be heard when trying to speak.

**Steps to reproduce:**
- One player becomes unconscious.
- Another player drags the player. 
- The unconscious player wakes up and yells "I'M ALIVE, RELEASE ME" repeatedly.
- The player who drags doesn't hear him and continues dragging.
- A couple of minutes later they arrive at a safe spot and release the now conscious player.
- The player who couldn't be heard can now be heard.

**Where did the issue occur?**
Dedicated & Self-Hosted Multiplayer

**Placed Modules:**
None.

**Comment by commy2** [comment]
Sounds like a problem with tfar/acre, not ace.

**Comment by SageNTitled** [comment]
Isn't it ACE that mutes the player when unconscious?

**Comment by jonpas** [comment]
We handle that in ACE3 (https://github.com/acemod/ACE3/blob/master/addons/medical/XEH_postInit.sqf#L36-L51), but I don't see how it could cause that. Must be something else.

**Comment by commy2** [comment]
I think it has to do with attachTo.

**Comment by PabstMirror** [comment]
We delay waking up when being dragged
```
    // Wait until the unit isn't being carried anymore, so we won't end up with wierd animations
    if !(([_unit] call FUNC(isBeingCarried)) || ([_unit] call FUNC(isBeingDragged))) then {
```
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_unconsciousPFH.sqf#L56

**Comment by kripto202** [comment]
happens when being carried i've seen
