### ISSUE TITLE
Stamina is used up very fast when walking and running with binoculars on hand.

### ISSUE THREAD

**Issue by Bummeri** [acemod/ACE3#5769]
**Arma 3 Version:**  (latest stable)
**CBA Version:**  (latest stable)
**ACE3 Version:**  (latest stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Walking or running with binocular on hand drains stamina very fast.

**Steps to reproduce:**
- Walk or run with a weapon down.
- Then compare to walking or running with binoculars on hand.

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- none

**RPT log file:**
- Not relevant

**Comment by ulteq** [comment]
This is most likely caused by the way we currently calculate the duty factor of animations: https://github.com/acemod/ACE3/blob/master/addons/advanced_fatigue/functions/fnc_getAnimDuty.sqf

**Comment by Bummeri** [comment]
Well at least the binocular is much more lightweight than the rifle. So the penalty should be less than mowing with a rifle? At least the current implementation is flawed since it consumes stamina faster than with a rifle.

**Comment by Snak3Doc** [comment]
I'm not a 100% sure on this but I believe having your weapon on your back costs more stamina than weapon lowered.

**Comment by BaerMitUmlaut** [comment]
The only difference would be movement speed. So whichever is faster is more exhausting.

**Comment by SilentSpike** [comment]
If I understand right, you'd move further for the same amount of fatigue, so it doesn't actually cost more stamina.

**Comment by SilentSpike** [comment]
As for the original issue, to answer @ulteq's question: it kind of depends on the item, but I can't think of any other items you can hold in your hand besides binoculars (which are a weird weapon/item?).
