### ISSUE TITLE
ACE Spectator may drop virtual player unit into water with respawn types 1, 4 and 5

### ISSUE THREAD

**Issue by Bummeri** [acemod/ACE3#5775]
**Arma 3 Version:** (latest stable)
**CBA Version:**  (latest stable)
**ACE3 Version:** (latest stable)
TFAR: (Latest stable) 

**Mods:**
```
- CBA_A3
- ace
- TFAR
```

**Description:**
    // Position defaults to [0,0,0] if marker doesn't exist
    _unit setPos (markerPos QGVAR(respawn));

Can this be changed to look for a position on land? That way TFAR would not have sea effect added to spectator chat.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
- Not relevant

**Comment by dedmen** [comment]
How about moveing to 0,0,5 and disableSimulation?

**Comment by jonpas** [comment]
This looks like a TFAR issue to me, we call their API (as well as ACRE's) to enable spectator mode. I suggest you also report this to TFAR.

**Comment by dedmen** [comment]
I guess with sea effect you mean that you can't understand other people because they can't talk underwater?
If so.. Why are there people at 0,0,0 or do you mean other spectators?
If other spectators then that is already fixed in the next TFAR version

**Comment by Tikkasd** [comment]
fnc_compat_spectatorBI switches players to virtual spectators which are created to 0, 0, 0. fnc_compat_spectatorBI doesn't disable simulation so player falls under sea level.

**Comment by SilentSpike** [comment]
@Tikkasd is correct, that's the only scenario I can see where ace spectator would move the player (it's the function that runs for respawn modes where player is usually seagull).

The piece of code quoted in OP is part of a deprecated function.
