### ISSUE TITLE
At the FAST ROPE, the landing group always dies.

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5780]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `.4.1.170912` (stable )
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- TPW
-DragonFyre
```

**Description:**

- At the Fast Roping, the landing group will always die because the height of the helicopter above the ground does not match the length of the rope for descent. The rope is always shorter. For this reason, the  landing group will always falls down. 
https://www.youtube.com/watch?v=WIKbYLmLgUk&feature=youtu.be 

Maybe I'm doing something wrong. However, in the [ace description](https://ace3mod.com/wiki/feature/fastroping.html#2-usage) there is no any coherent instruction.

**Steps to reproduce:**

place a player on a map (civilian)
place Ka-60 helicopter Kasatka and create a waypoint for it - LET UNIT FAST ROPE
place any infanty group (landing party) and create a waypoint for the landing party - GET OUT 
place this group in the helicopter
synchronize Waypoints LET UNIT FAST ROPE and GET OUT
run game and watch via spectator

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- not needed

**Comment by BaerMitUmlaut** [comment]
It depends on the terrain below the helicopter. If there is any kind of obstacle there, even just a single bush, the helicopter AI will simply refuse to go lower than a certain point.

This is a known issue and cannot be fixed. It works fine on open terrain though.

**Comment by ZeusWrath** [comment]
hmm. Still, there's no way to drop the squad into the jungle ... That's all I wanted. 
What is the use of this in an open area? In the open area Such a detachment can be destroyed with ease. Unfortunatelly, a fast rope has no any value.

**Comment by ZeusWrath** [comment]
As seems to me, the problem is easily solved by lengthening the ropes, have you thought about this? If the rope is longer then the units are won't fall

**Comment by SanchezMilsim** [comment]
If you have a 37m rope and you are at 20m of altitude on helicopter, this reproduce too.

**Comment by commy2** [comment]
Please don't necro over 2 year old issues.
