### ISSUE TITLE
Feature Request: Goggles functions on helmets

### ISSUE THREAD

**Issue by Reidond** [acemod/ACE3#5784]
**Arma 3 Version:** `1.76` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- I think that this would be nice if you add these functions on helmets. Thanks

**Steps to reproduce:**
- None

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- None

**Comment by Drofseh** [comment]
https://github.com/acemod/ACE3/issues/3594

**Comment by bux** [comment]
Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
