### ISSUE TITLE
[false] call ace_spectator_fnc_setSpectator leaves player invisible

### ISSUE THREAD

**Issue by nomisum** [acemod/ACE3#5785]
**Arma 3 Version:** `1.76` stable
**CBA Version:** `3.4.1` stable
**ACE3 Version:** `3.11.0` stable

**Mods:**
```
- CBA_A3
- ace3
```

**Description:**
`[false] call ace_spectator_fnc_setSpectator` leaves player invisible. Should be visible again.

**Steps to reproduce:**
debugConsole:
`[true] call ace_spectator_fnc_setSpectator;`
`[false] call ace_spectator_fnc_setSpectator;`
watch in 3rd person

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Placed Modules:**
- none

**RPT log file:**
probably connected (happens after setting to false)
```
13:14:03 Error in expression <30625 ) then {
private _intersections = lineIntersectsSurfaces [_start, _end, _c>
13:14:03   Error position: <lineIntersectsSurfaces [_start, _end, _c>
13:14:03   Error Type Any, expected Object
13:14:03 File z\ace\addons\spectator\functions\fnc_ui_draw3D.sqf, line 18
```

**Comment by bux** [comment]
https://github.com/acemod/ACE3/pull/5699
