### ISSUE TITLE
Issues with old mods

### ISSUE THREAD

**Issue by Chinds1984** [acemod/ACE3#5788]
![img_2544](https://user-images.githubusercontent.com/33757568/32976667-2f0d0952-cbea-11e7-9b1e-bba372726b6d.JPG)
![img_2553](https://user-images.githubusercontent.com/33757568/32976668-34000fa4-cbea-11e7-858f-1474fb23aee6.JPG)
![img_2554](https://user-images.githubusercontent.com/33757568/32976669-38a17ec6-cbea-11e7-9018-60f4d63b7f17.JPG)
![img_2543](https://user-images.githubusercontent.com/33757568/32976674-3bbfd3c8-cbea-11e7-820e-b5b23a046cf3.JPG)
![img_2556](https://user-images.githubusercontent.com/33757568/32976675-3e04aa0a-cbea-11e7-9d47-e5515980f0b3.JPG)

**Comment by thojkooi** [comment]
You need to install the compatability pbos that it says you are missing. 

Also when updating ACE, first remove the old ACE3 installation before putting the new installation in place.

You are welcome to [join our Slack](https://slackin.ace3mod.com/) if you have further questions.

**Comment by Chinds1984** [comment]
Where do we update the newer ace versions

**Comment by PabstMirror** [comment]
You can always download from github here: https://github.com/acemod/ACE3/releases/latest
scroll down a bit and download `ace3_3.11.0.zip`

You should also make sure to delete your current `@ace` folder and then extract the zip

**Comment by Chinds1984** [comment]
Another issue i'm having is when I play some missions from the workshop its telling me to remove some files in the mod list or it can get buggy. Some missions are telling me I need to disable the Ace mod or the mission won't work I go ahead to remove the ace mod and then it gives me an error message "Extension ace_clipboard.dll not installed" then if I exit out of the game again and enable that mod it runs fine but I have a problem because then those other missions become buggy and wont let me complete it

**Comment by Cuel** [comment]
The in-game addon loader is very wonky. Just restart a3 without ace
