### ISSUE TITLE
Problem with slowly working ACE menu and map drawing.

### ISSUE THREAD

**Issue by LtBrogi** [acemod/ACE3#5797]
**Arma 3 Version:** 1.7.6
**CBA Version:** 3.4.1
**ACE3 Version:** 3.11.0

**Mods:**
```
- CBA_A3
- ACE3
- ACRE
```

**Description:**
- The ACE menu (interaction with yourself and surroundings), and drawing on the map is working very slowly. Closest thing I could compare it is lagging. Eg when I draw something on map (holding ctrl) the line is fallowing my cursor in a delay. The delay depends on time the ctrl is pressed and complexity of the drawing. When ctrl is released drawning continues unless it complets my moves (but in much delay). Same thing is with the interaction menu. After some time it spreads to common Arma controls, eg releasing W key dont stop the character, relesing Alt dont stop looking around (I have to wait 2-5 sec. before it stops). The issue occurs on clean mods (from Github), and on ACE with rhs compats, almost 
immediately with my clan full modset: [pastebin](https://pastebin.com/HVetirBz)
- FPS are on ~60+
- Mem usage ~70%
- CPU usage ~50%
- Arma sits on SSD, mods on 2 HDDs with RAID 0 (both with no errors)

**Steps to reproduce:**
- Nothing to add here it starts ~5 min after entering any multi/single map.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Singleplayer)

**Placed Modules:**
- Basic ACE modules, medical etc. [pastebin](https://pastebin.com/ckgrgQQX)

**What I did so far:**
- turned off FW
- dissabled vsync in graphic card
- tried Arma 32 and 64 bit
- running game wiht and without mallocs (tbb4 & je)
- running game in fullscreen and fullscreen windowed
- enabling/dissabling huge pages in launcher
- trying several launchers (vanilla, fsf, A3Sync)
- reseting the profile and all controls to default
- setting the performance stats (max mem, cpu count, ex threads, ht etc)

**RPT log file:**
- RPT: [pastebin](https://pastebin.com/ieH2K6AD)

**PC specs:**
* Core I5 4670K 3.4@4.5GHz + Zalman Performa * ASRock H87 Fatal1ty * 2x 4GB DDR3 GoodRam Play Red @1600MHz * GeForce GTX 760 Gigabyte 2GB OC * Kingstone 128 GB SSD 500/500 + Seagate Barracuda 7200.12 1TB * Zalman ZM500-GS 500W * 

Sorry for bad English, its not my native language ;)

**Comment by commy2** [comment]
>-nologs

Needs a proper RPT file (no use when nothing is logged)

**Comment by LtBrogi** [comment]
Sorry, my mistake. Proper RPT [pastebin](https://pastebin.com/uyAHCKDB). Its with all mods from my modset. I dont have access to server without bisigns checked for cba+ace+acre only.

Just realized that it happens when I use radio, or voicechat on map.
