### ISSUE TITLE
Bullet Trace Effect M200 not present

### ISSUE THREAD

**Issue by haydnbuzz** [acemod/ACE3#5801]
**Arma 3 Version: 1.7.6
**CBA Version: 3.4.1.1709122
**ACE3 Version: 3.11.0

Mods:
- CBA_A3
- ace

**Description:**
- Using the M200 the bullet trace effect doesn't appear to be present. Can't see any hint of it above or below 1000m shots. Apologies for the lack of detail this is my first post here and am certainly a casual player.

**Steps to reproduce:**
- Loaded only CBA A3, Ace, ACEX

**Where did the issue occur?**
 Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- None

**Comment by ulteq** [comment]
Did you enabled the 'Advanced Ballistics' module?

**Comment by haydnbuzz** [comment]
That was my mistake it's there once enabled. Thank you!
