### ISSUE TITLE
Refuel capability for Redd Marder 1A5

### ISSUE THREAD

**Issue by TTTRedd** [acemod/ACE3#5810]
**Arma 3 Version:** `1.76` (stable / rc / dev)
**CBA Version:** `3.4.1` (stable / dev + commit hash)
**ACE3 Version:** `3.1.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
-Redd'n'Tank Vehicles
```

**Description:**
- Redd Marder 1A5 is unable to be refueld via ACE

Hey guys I'm the developer of Redd'n'Tank Vehicles, what do I have to do make the MArder compatible with Ace refuel ? You could take a look in the config here: https://gitlab.com/TTTRedd/Redd_Vehicles/tree/master/Redd_Marder_1A5

**Comment by commy2** [comment]
https://github.com/BWMod/bwa3_comp_ace/blob/master/bwa3_comp_ace/CfgVehicles.hpp#L129-L130
https://github.com/BWMod/bwa3_comp_ace/blob/master/bwa3_comp_ace/CfgVehicles.hpp#L59

Don't change FUEL_FACTOR. It has some meaning despite me forgetting what exactly.

**Comment by jonpas** [comment]
https://github.com/acemod/ACE3/blob/8bc77a7b883c411e834a595090e4a2a31d6924ea/addons/refuel/functions/fnc_refuel.sqf#L30 @commy2

**Comment by TTTRedd** [comment]
> https://github.com/BWMod/bwa3_comp_ace/blob/master/bwa3_comp_ace/CfgVehicles.hpp#L129-L130
https://github.com/BWMod/bwa3_comp_ace/blob/master/bwa3_comp_ace/CfgVehicles.hpp#L59

Don't change FUEL_FACTOR. It has some meaning despite me forgetting what exactly.

Unfortunately this doesn't the trick

**Comment by jonpas** [comment]
Nothing seems to be wrong with your config. Upload the RPT, maybe there is a warning in there telling you what's wrong.

**Comment by TTTRedd** [comment]
Do I need a memorypoint in the model?

**Comment by jonpas** [comment]
No. Upload RPT and check in in-game config viewer if the values are set correctly.
`ace_refuel_canReceive` should be `1`.

**Comment by TTTRedd** [comment]
OK now it works fine, the config looks like this:

[CfgVehicles.txt](https://github.com/acemod/ACE3/files/1499734/CfgVehicles.txt)
[PhysX.txt](https://github.com/acemod/ACE3/files/1499735/PhysX.txt)

**Comment by madpat3** [comment]
hey redd,
maybe you can also make your vehicle compatible to the "ace-quick-mount" system. i have tried your mod, but you can only enter the vehicle vanilla-style (mouse wheel).

**Comment by TTTRedd** [comment]
Which position do want to enter? If it was a n cargo position it wouldn't work because the cargo is locked until you open the rear ramp.

**Comment by madpat3** [comment]
i mean the driver/gunner/commander position. i know the cargo positions are locked until someone's opened the rear hatch. but ace provides a feature, which lets you enter the vehicle by hot key.
it's called "quick mount" and is available on all vehicles, that inherit from vanilla classes. obviously your vehicle doesn't. i don't know how, but there must be a way to configure your vehicle(s) to use the quick mount feature, as well.

**Comment by TTTRedd** [comment]
I will have a look, as you can see I'am inheriting from Tank_F. Don't know why the Marder has this strange behaviour with ACE ;)

**Comment by madpat3** [comment]
i've noticed the rear hatch is actually a door, because it's working with "ace-incremental-door-opening"; don't know if it helps.

**Comment by dedmen** [comment]
>OK now it works fine

Close this issue then?
