### ISSUE TITLE
Buddy-Reload reload time

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#5813]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**ACE3 Version:** `3.11.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- I've already mentioned it in the Slack. Ace Buddy-Reload takes way to much time, compared to "Self-Reload". alganthe told me, this is due to how arma handles reloading via command. but i wanna give it a shot, maybe someone's got an idea to work around it. otherwise buddy-reload is obsolete.

**Steps to reproduce:**
- let someone reload your "bazooka" and count the time until your weapon is ready to fire. do the same, but reload the weapon by yourself.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**Comment by commy2** [comment]
`addWeaponItem` and `addSecondaryWeaponItem` are broken for launchers and add a default reload timer that cannot be avoided / shortened / circumvented in any way with anything in the SQF API.

**Comment by jonpas** [comment]
If there is a ticket open, please link it so we can add it [here](https://ace3mod.com/wiki/development/arma-3-issues.html) and close this issue, as it is not resolvable on our side.

**Comment by BaerMitUmlaut** [comment]
This should have been closed with #7605, right?
