### ISSUE TITLE
russian text (small request)

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#5816]
Hello. please right translate:
when the weapon is put on the fuse, it is necessary to write
 "ПОСТАВЛЕНО НА ПРЕДОХРАНИТЕЛЬ"  http://joxi.ru/52aBgKlCGqlY8A and, accordingly, 
when "СНЯТО С ПРЕДОХРАНИТЕЛЯ" http://joxi.ru/823vdwoc6lzYnm
Thx.

**Comment by commy2** [comment]
Does this look any good to you? https://github.com/acemod/ACE3/pull/5817/files

**Comment by topden** [comment]
yes.thx
