### ISSUE TITLE
Handcuffing a unit far away using rangefinder

### ISSUE THREAD

**Issue by RG-Helios** [acemod/ACE3#5822]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS
- Project OPFOR
-....
```

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- Use rangefinder
- look at a unit
- press the key to handcuff a unit

**Where did the issue occur?**
- Dedicated 

**Placed Modules:**
- all

**Comment by commy2** [comment]
o_O

**Comment by bux** [comment]
Thx @RG-Helios
