### ISSUE TITLE
[Question] Reconfigure Pylons needing toolkit

### ISSUE THREAD

**Issue by MrDj200** [acemod/ACE3#5824]
Hello, 
sorry to destroy the issue guidelines, however I just have a question regarding the Pylons.
On the [Wiki Page](https://ace3mod.com/wiki/feature/pylons.html) it says

> To configure pylons you need a Toolkit equipped [...] (Note: these requirements can be disabled)

but where do I disable it? I can't find a module regarding this. Do I need a script command?
I can't find it :(.

Again: Sorry to destroy the issue template, but I didn't know where to ask.

Kind regards
-Dj

**Comment by jonpas** [comment]
https://ace3mod.com/wiki/framework/settings-framework.html
https://github.com/acemod/ACE3/blob/master/addons/pylons/ACE_Settings.hpp

There is no module for it, because with 3.12 those settings will be changeable in CBA Settings.

**Comment by MrDj200** [comment]
Ahh, thank you very much! I think I'll just wat for the CBA Settings Update :D. 
Any Ideas on the Estimated Release Day?

Kind regards
-Dj

**Comment by BaerMitUmlaut** [comment]
You will always get the same answer to this question: soon.
