### ISSUE TITLE
Static SPIKE launcher wounds gunner

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#583]
Needs fixing.

**Comment by esteldunedain** [comment]
Probably not related to backblast; I'll investigate

**Comment by commy2** [comment]
Also check the auto grenade launcher. Had something similar with them 3 days ago.

**Comment by Glowbal** [comment]
Might be related #616

**Comment by jaynus** [comment]
I can't reproduce this anymore. Closing.
