### ISSUE TITLE
Torque doesn't work on IR grenades

### ISSUE THREAD

**Issue by Neviothr** [acemod/ACE3#5835]
**Arma 3 Version:** `1.78.143717` (stable)
**CBA Version:** `3.4.1.170912` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Upon throwing an IR grenade (CSAT/AAF/NATO), the below error will show up.

**Steps to reproduce:**
- Go into VA, throw any IR grenade

**Where did the issue occur?**
- Singleplayer

**Placed Modules:**
- None.

**RPT log file:**
- https://gist.github.com/Neviothr/e59bdc3c5cf4efc3d2e5eb2c58a4f626
Or if you don't feel like looking at a 1000 line file :man_shrugging:
```
16:39:38 Error in expression < _activeThrowable;
private _torqueDir = vectorNormalized (getArray (_config >> ">
16:39:38   Error position: <vectorNormalized (getArray (_config >> ">
16:39:38   Error 0 elements provided, 3 expected
16:39:38 File z\ace\addons\advanced_throwing\functions\fnc_throw.sqf, line 39
```

**Comment by jonpas** [comment]
I am assuming those IR grenades don't inherit from `Grenade`.

**Comment by commy2** [comment]
Should add default torque to `CA_Magazine` to fix this for everything else that might not inherit from `Grenade` either.

**Comment by commy2** [comment]
```cpp
		class B_IR_Grenade: CA_Magazine //inherits 19 parameters from bin\config.bin/CfgMagazines/CA_Magazine, sources - ["A3_Weapons_F"]
		class O_IR_Grenade: B_IR_Grenade //inherits 14 parameters from bin\config.bin/CfgMagazines/B_IR_Grenade, sources - ["A3_Weapons_F"]
		class I_IR_Grenade: B_IR_Grenade //inherits 14 parameters from bin\config.bin/CfgMagazines/B_IR_Grenade, sources - ["A3_Weapons_F"]
```

**Comment by Neviothr** [comment]
Thanks!
