### ISSUE TITLE
Blufor tracking allows move unit on the map

### ISSUE THREAD

**Issue by TheMagnetar** [acemod/ACE3#584]
Enabling the blue force tracking module allows to move the player to another location on the map by selecting the unit marker and (left alt)+(left mouse click) on any position on the map.

Modules enabled: ACE_BlueForceTracking (options: interval: 1; hide for AI: no).

Consider me at hand for anything else

**Comment by esteldunedain** [comment]
No, this is default behaviour in the editor. Happens with/without ACE
