### ISSUE TITLE
Misleading .338 magazine class name

### ISSUE THREAD

**Issue by ulteq** [acemod/ACE3#5852]
The `ACE_10Rnd_338_300gr_HPBT_Mag` magazine should be loaded with *.338 Sierra MatchKing HPBT 300 gr* instead of *.338 Lapua Scenar 300 gr*.

**Proposed fix:**

Add a new ammo class `ACE_338_HPBT_Ball` for the `ACE_10Rnd_338_300gr_HPBT_Mag` magazine.
Add a new magazine class `ACE_10Rnd_338_300gr_Scenar_Mag` for the `ACE_338_Ball` ammo.

This involves:
* Changes to the ATragMX gunlist
* Changes to the `airFriction` generator (https://github.com/acemod/ACE3/blob/master/tools/generate_airfriction_config.py#L493-L494)
* Changes to the ammo boxes (https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgVehicles.hpp)
* Changes to the stringtable (https://github.com/acemod/ACE3/blob/master/addons/ballistics/stringtable.xml#L1980-L2027)

Related with: https://github.com/acemod/ACE3/pull/5851

**Comment by dedmen** [comment]
Add "help wanted" label maybe?

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
