### ISSUE TITLE
Unit tags disappear after random time in free cam

### ISSUE THREAD

**Issue by Cyruz143** [acemod/ACE3#5856]
**Arma 3 Version:** `1.78` (stable)
**CBA Version:** `3.4.1.170912` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- acre
- Mission framework (https://github.com/kami-/hull3)
- Additional content (NI Arms/CUP)
```

**Description:**
- When the player first moves in to spectator, you can view unit tags in any of the vision modes, if you switch to free cam, unit tags work for a non-specific amount of time, then suddenly disable themselves. Going back to 3rd person brings them back but switching to free cam instantly disables them again.

It feels like a variable is being set after a condition is met that stops drawing them and remains set for the rest of the mission.

**Steps to reproduce:**
- Go in to spec, make sure unit tags are on, go to freecam, wait.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None, server.hpp below:

```
class ace_spectator_enableAI {
    value = 1;
    typeName = "BOOL";
    force =1 ;
};
class ace_spectator_restrictModes {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
class ace_spectator_restrictVisions {
    value = 0;
    typeName = "SCALAR";
    force = 1;
};
```

**RPT log file:**
- Nothing in the RPT

**Comment by SilentSpike** [comment]
I wonder if this has something to do with the draw3D weirdness surrounding the current player unit.

Is the player always dead when you've experienced this?

**Comment by Cyruz143** [comment]
Yes, I've only seen it when dead. It would be good to test when dead vs script call spec on alive units.

**Comment by Cyruz143** [comment]
@SilentSpike good guess. Just called spec manually, flew around for 5-10 minutes and tags remained working. Killed myself, had tags for around 30 seconds then they just stopped working.

This was testing on a dedicated server with me as the only player.

**Comment by SilentSpike** [comment]
Hmm, it's weird because the EG Spectator code doesn't do anything special to fix this so you'd think they would have the same issue.

Anyway, we can fix this doing what my old code did. I believe I was doing a `switchCamera` onto a living agent unit while in free cam. I still don't entirely understand why the engine causes this issue with `draw3D`, but the workaround works at least 😆

**Comment by PabstMirror** [comment]
Thanks to @AACO for looking at this, just posting his findings

https://github.com/acemod/ACE3/blob/master/addons/spectator/functions/fnc_compat_spectatorBI.sqf#L43
```
// Switch to a virtual unit so draw3D continues to work
private _grp = createGroup [sideLogic, true];
private _virtual = _grp createUnit [QGVAR(virtual),[0,0,0],[],0,"NONE"];
```
That's what fixes draw3d from breaking when the player dies

Looks like you are calling setSpectator directly after death which probably isn't switching the unit?

https://github.com/kami-/ark_inhouse/blob/master/ark_ace_spectator/client_preinit.sqf#L54

**Comment by Cyruz143** [comment]
Thanks @PabstMirror, I did think I was testing this without internal stuff loaded... Will check and see.

**Comment by SilentSpike** [comment]
Ah, of course, I never did ask what respawn mode you were using 👍

Yeah if it's a permadeath one you have to switch the player to a living unit so that it'll continue to work. We could probably add code that would make it work in this case regardless so that you don't have to worry about that when calling it manually.

**Comment by SilentSpike** [comment]
If you could, reproduce the issue and run this code while in free camera to see if it fixes:

`(createAgent ["ace_spectator_virtual", [0,0,0], [], 0, "NONE"]) switchCamera "INTERNAL"`

**Comment by Cyruz143** [comment]
Testing now, wait two.

**Comment by Cyruz143** [comment]
So it works, until you focus on something, then they vanish again, oddly...

https://gfycat.com/SpiffyCriminalCarp

**Comment by SilentSpike** [comment]
That's perfect (the reason it stops is because when you change the camera focus it removes the effect of the `switchCamera`). Should be able to use that to fix the issue so that your external code won't have to switch the player like the template does 👍

**Comment by Cyruz143** [comment]
Awesome, thanks all.
