### ISSUE TITLE
Updated Spectator feedback

### ISSUE THREAD

**Issue by Cyruz143** [acemod/ACE3#5857]
**Arma 3 Version:** `1.78` (stable)
**CBA Version:** `3.4.1.170912` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Feedback:**
- Missing compass from new UI
- 3rd person zoom limit isn't very large (could use expanding)
- Map is very small (perhaps use the same dimensions as the Splendid Cam map?)
- Some options aren't listed in the keybind section (p for projectiles etc)

**Notes:**
- I know this violates the bug reporting rules a bit here, feel free to close if deemed not acceptable.

**Comment by SilentSpike** [comment]
This ticket can serve as a discussion rather than a bug report per se 👍

Good feedback, to address why some things are certain ways (not necessarily justify them, just explain):

- While I liked the idea of including a compass UI element (like the one in zeus), it was ugly as hell and even very low res depending on the user's display. This was because I had to use images to build the compass unlike the engine driven zeus compass (which I'd love for BI to add a control type for).
- The current 3PP zoom limit is the same as EG spectator, I left it like that because it seemed as if it had been set with PvP in mind (to not show too much to dead players). Perhaps this is something a setting would be suitable for.
- Similar to above, the map dimensions are just the same as EG spectator. Could be made larger easily enough (would it be better to just make it fullscreen?).
- Keybind limitations, see here: https://github.com/acemod/ACE3/issues/4373

**Comment by Cyruz143** [comment]
Thanks for taking the time Spike.

- Shame about the lack of not being able to hook the Zeus compass but understandable.
- Never really thought about the competitive element in this regard, a setting to allow for wider viewing angles would be much appreciated.
- I'm fine will full screen, my general use case for the map is to jump around to look at far away units, current, it's open it and scroll lots to try and see the whole map.
- A slight misunderstanding there Spike, I wasn't asking to rebind it, just to add it to the 'F1' controls menu as most people aren't aware of these options!

**Comment by SilentSpike** [comment]
Ah yeah, in that case the concern is that the controls menu would grow too large and be overwhelming 😆

An issue I was aware of but unsure how to handle best. Currently that menu is updated contextually so it never grows too large, but those keys would always be available. I do have an experimental local branch where I add a second tab to the left hand list pane which switches to a controls/options menu with on-screen toggles and things, but it looks clunky. Would work better with the new menu control type, but that's broken and deletes itself from the display when you click anywhere.

**Comment by commy2** [comment]
>This was because I had to use images to build the compass unlike the engine driven zeus compass (which I'd love for BI to add a control type for).
While it is hardcoded, I was able to create this scripted solution: #5860
Maybe this helps?

**Comment by commy2** [comment]
>Keybind limitations

The day of the keybinding rewrite came already. You can add full support of all keybinds by copying what this function does for your display:
https://github.com/CBATeam/CBA_A3/blob/master/addons/events/fnc_initDisplayCurator.sqf

**Comment by SilentSpike** [comment]
Very nice work with that compass function 👍

As for the keybinding stuff, I'm not sure I'd necessarily want to enable *all* keybindings - just the ones specific to spectator.

**Comment by SilentSpike** [comment]
Some things I would like to add in future:

- [ ] Ability to filter the unit list by side & players only
- [ ] Bullet cam

I think maybe if I add a context menu to the list that'd be the best way to show the toggles and things (as mentioned above, wouldn't want to over-saturate the controls element in bottom right).

**Comment by dedmen** [comment]
This is still in ongoing milestone and isn't done. This should not be closed.
Also the bot should be ignoring things in milestones, that's apparently not working right
https://github.com/acemod/ACE3/blob/master/.github/stale.yml#L46

**Comment by Quailsnap** [comment]
Request: Add the 'compass' control, or whatever's use to render it, to the list of things that are automatically hidden when the UI is toggled.

Bugs me that it isn't hidden with the rest.

**Comment by Quailsnap** [comment]
Additionally -- why not include a "hide even more stuff" option. Like Zeus, where normal backspace hides the UI, but backspace+shift+ctrl hides the UI, the logo, everything.

Could place an invisible box over the text chat to hide it, etc, etc. Would be very handy for collecting mission footage, and doubly so if the feature request for "a camera smoothing option" is integrated later at some point.

**Comment by PaxJaromeMalues** [comment]
When the ACE Spectator is called manually like in my case from the init of a playerobject right at mission start and no manual delay of 2+secs is added it sorta shits its pants.
```
this spawn {
  waitUntil {alive _this};
  sleep 3;
  if (local _this && isPlayer _this && hasInterface && (!isServer)) then {
    [true, true, true] call ACE_spectator_fnc_setSpectator;
  };
};
```

**Comment by kymckay** [comment]
@PaxJaromeMalues Can you open an new issue report for that? 😃 

I'm going to close this issue as it's been around for ages and was more relevant when spectator was first reworked. Development habits have improved and it's nice to have a single ticket for each thing.
