### ISSUE TITLE
[Feature request] fix BI zeus and allow to set Direction on remote units

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#5859]
Would be nice if you can make the SHIFT+LeftMouse turning of units global... atm with a hc you cant turn units as curator because there are remote and https://community.bistudio.com/wiki/setDir needs a local unit.
Whould be a nice little fix ;D

**Comment by commy2** [comment]
Zeus doesn't use `setDir`, it's hard coded C++ land magic, but has the same problem. Since it's hard coded, it's a difficult fix and no one knows how to do that. You're not the first to bring this up.

**Comment by shukari** [comment]
I saw it in a mod ZISHC http://steamcommunity.com/sharedfiles/filedetails/?id=639965833
It look for the Shift and MouseEvent and then run a custom setDir or setFormationDir function.

**Comment by commy2** [comment]
Zeus doesn't have any mouse events and there is no setDir function to customize.

**Comment by commy2** [comment]
See: https://github.com/CBATeam/CBA_A3/pull/816
