### ISSUE TITLE
Keybind for ATragMX GUI, Kestrel 4500NV bigger GUI and smaller one

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#586]
Because you have to often switch between these two very handy tools for AB, it would be even better to get keybinds to show them up quicker, because using new action menu is kinda annoying after a while.

**Comment by ulteq** [comment]
Related to: https://github.com/acemod/ACE3/issues/426

**Comment by esteldunedain** [comment]
Feature request!
