### ISSUE TITLE
ACE Options not visible ISSUE/BUG

### ISSUE THREAD

**Issue by Alias-Me** [acemod/ACE3#5861]
**Arma 3 Version:** `1.78.143717`
**CBA Version:** `3.5.0`
**ACE3 Version:** `3.11.0`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
-When i open the "Ace Options" there are no visible buttons, only the colour options kinda work. 
This problem has come up before, but the fixes there didnt help me.

**Steps to reproduce:**
- Everytime I load the game

**Where did the issue occur?**
- Singleplayer

**Placed Modules:**
- None

**RPT log file:**
- https://pastebin.com/1idKNev9

**Comment by PabstMirror** [comment]
I'm not seeing any real problems in the rpt

Ace is switching to cba setting
and the ace options menu won't exist in the next release (ref https://github.com/acemod/ACE3/pull/5746)

So it should be "fixed" in 3.12

**Comment by PabstMirror** [comment]
Let us know if you are still having problems with 3.12 and the new cba options menu
