### ISSUE TITLE
Advanced Fatigue no longer works

### ISSUE THREAD

**Issue by ashtontf11** [acemod/ACE3#5862]
Arma 3 Version: v1.78 Stable
CBA Version: v3.5.0.171204 Stable
ACE3 Version: 3.11.0 Stable

Mods:
- CBA_A3
- ace

**Description:**
The 'Advanced Fatigue' Module no longer has an effect in game. When placing the module down and changing the values it has no effect within game as the stamina will deplete but in most cases not recover.

**Steps to reproduce:**
Create a new mission on a random map
Place the 'Advanced Fatigue Module'
Either save and run the mission from the editor or from SP
Observe that the stamina will go down and not recover, values on the module have no effect
Go back to editor and change the values around
Play again, and you will see the module has no effect on the player.

The values I originally used are: 
```
Terrain Gradient Factor: 1
Recovery Factor: 5
Load Factor: 1
Performance Factor: 4
```

The values I changed to are:
```
Terrain Gradient Factor:  2
Recovery Factor: 15
Load Factor: 2
Performance Factor: 6
```

**Where did the issue occur?**
- Dedicated 
- Singleplayer / 
- Editor (Singleplayer)

**Placed Modules:**
- Advanced Fatigue Module

**Comment by BaerMitUmlaut** [comment]
Please upload the RPT file.

**Comment by Armilio** [comment]
It makes this error after the last ArmA patch:

21:16:45 Error in expression <l "_loadCoef") then {
_loadCoef = _unit getUnitTrait "loadCoef";
_unit setVariab>
21:16:45   Error position: <getUnitTrait "loadCoef";
_unit setVariab>
21:16:45   Error Errore esterno: Unknown enum value: "loadCoef"
21:16:45 File z\ace\addons\movement\functions\fnc_handleVirtualMass.sqf, line 29


[arma3_x64_2017-12-06_21-16-04.zip](https://github.com/acemod/ACE3/files/1537201/arma3_x64_2017-12-06_21-16-04.zip)

**Comment by commy2** [comment]
@Armilio https://github.com/acemod/ACE3/issues/5833

**Comment by jonpas** [comment]
Duplicate of #5833 I believe, fixed on BI side, closing.
