### ISSUE TITLE
Can't display Kestrel 4500NV smaller GUI and ATragMX GUI at the same time

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#587]
As in title, I remember times when I could read informations about weather and enter them directly to ATragMX, I liked that method. Now when I have ATragMX GUI opened and want to show up Kestrel 4500NV, then ATragMX GUI closes, and vice versa.

**Comment by ulteq** [comment]
You can display both at the same time if you do the following:

Interaction Menu -> Show Kestrel 4500
Interaction Menu -> Open ATragMX
