### ISSUE TITLE
Please update the mod!

### ISSUE THREAD

**Issue by frootyninja** [acemod/ACE3#5875]
Please update ACE to work with the current version of arma 3 :( it sucks not being able to use ACE

**Comment by jonpas** [comment]
Fill out the template as it was given to you, this issue is useless to us, no information that would allow us to help you.

Besides, latest version has no critical bugs to prevent you from using ACE3.

**Comment by frootyninja** [comment]
I've tried it only using ACE and it doesn't work plus there are others saying to update it.

**Comment by jonpas** [comment]
That doesn't help us, I am not sure what to do if you don't understand that. We can not help you unless you fill out the template and provide the required information.

What makes "others" correct? 3.11.0 works fine with a few false-positive errors.

**Comment by frootyninja** [comment]
I'll fill it out one moment.

**Comment by frootyninja** [comment]
Ok i finally got it working, i had an old ACE enabled from a local file which i thought was the new one. My mistake...

**Comment by jonpas** [comment]
:)
