### ISSUE TITLE
Question: Can Advanced Fatigue be disabled on individual units/players

### ISSUE THREAD

**Issue by Joocebocks** [acemod/ACE3#5881]
**Arma 3 Version:** `1.80` (stable / rc / dev)
**CBA Version:** `3.5.0` (stable / dev + commit hash)
**ACE3 Version:** `3.11.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Advanced Fatigue uses setAnimSpeedCoef and as a result, I'm unable to use the command to change a player's run speed while the module is active. Would like to disable advanced fatigue on individual players if possible so that setAnimSpeedCoef can be used while the effects of the module are maintained on other players.

**Steps to reproduce:**
Enable ACE3 Advanced Fatigue

**Where did the issue occur?**
Tested in Editor Multiplayer

**Placed Modules:**
Fatigue

**RPT log file:**
N/A

**Comment by jonpas** [comment]
@BaerMitUmlaut
