### ISSUE TITLE
Add optional keybinds for certain actions

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#590]
I think this depends on CBA allowing this.

Allos actions not binded to any key by default.

**Comment by jonpas** [comment]
I am pretty sure TFAR has a couple of alternative keybinds not bound to anything by default.

**Comment by esteldunedain** [comment]
Apparently it is possible by creating the keybind with dik code = 0.

**Comment by jonpas** [comment]
Yay, I am being helpful for a change. :grin:

**Comment by bux578** [comment]
Can this be closed? I think that's already in (e.g. weapon select keys) @commy2 @esteldunedain

**Comment by jaynus** [comment]
Closing given there's no specific keys needed or called out. We now know we can set dik 0 :)

**Comment by jonpas** [comment]
Give me a :banana:
