### ISSUE TITLE
[3.12.0RC1] Arsenal override EdenArsenal without any otion to disable it (bug collection)

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#5904]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** 3.12.0RC1

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- first, the ace arsenal override the arsenal in eden... without any option to disable it...
- second... in the eden arsenal there is the weight wrong the frist is lb the second kg (http://steamcommunity.com/sharedfiles/filedetails/?id=1230556588)
- third, please add a setting to disable all buttons execept close... i have a own system for the management and i dont want that people save/load stuff in my mission

**Steps to reproduce:**
- rightclick -> arsenal -> Ace Arsenal

**Comment by commy2** [comment]
How is the weight wrong?

**Comment by shukari** [comment]
Oh god... the freaking / i supposed it was 47lb out of 20 kg like 9/10 points ^^

**Comment by bux** [comment]
not good UX then

**Comment by SilentSpike** [comment]
Yeah I can see how that `/` is confusing. Doesn't arma only use kg anyway?

**Comment by jonpas** [comment]
We add lb support in inventory @SilentSpike.

**Comment by bux** [comment]
> We add lb support in inventory @SilentSpike.

It's a toggled ace option though

**Comment by jonpas** [comment]
Yes, it is, but I think it makes more sense to display both (in inventory too).

**Comment by bux** [comment]
> display both

it's useless information for 95% of the people 😁

**Comment by jonpas** [comment]
I can't disagree that kg is the only proper unit of measurement in this case. 😆

**Comment by SilentSpike** [comment]
I think it should just respect the ace setting then, no need to show both at the same time.

**Comment by commy2** [comment]
Display it as:
54kg (28lb)

and as:
28lb (54kg)
if imperial units are enabled as setting?

**Comment by commy2** [comment]
Inverted the conversion factor, but you should get the idea.

**Comment by bux** [comment]
> Display it as:
> 54kg (28lb)

and remove the option?

**Comment by commy2** [comment]
The option could still be relevant for the inventory menu.

**Comment by bux** [comment]
It should be the same in ace arsenal and in the inventory. that's what I meant.

**Comment by commy2** [comment]
Sure, that's also an option. Always show both (with imperial in the brackets). Not sure the inventory display is big enough though.

**Comment by alganthe** [comment]
not like I told you when I was making it and YOU KEPT COMPLAINING but hey, i'll change it to:
current weight setting (other one)

**Comment by commy2** [comment]
That's life alganthe. Happens to me every day.

**Comment by alganthe** [comment]
actually i'll have it as:
kilos (lbs)
that way it's the same for everyone.

**Comment by alganthe** [comment]
- That's is intentional.
- https://github.com/acemod/ACE3/pull/5909
- I don't really understand what you're asking, if you don't want people to access ACE Arsenal don't add it to boxes.

**Comment by shukari** [comment]
@alganthe I want all enhancements like weight, bigger panels and that all... but i dont want this buttons.

**Comment by alganthe** [comment]
you mean the loadouts buttons?

**Comment by shukari** [comment]
Loadout, Export and Import

**Comment by alganthe** [comment]
Import doesn't work in multiplayer due to a BI safety on the clipboard, people can't obtain items that aren't in ACE Arsenal through ACE Arsenal, it will remove items that aren't available if you try to load a loadout, this is indicated by the loadout text being gray.

**Comment by shukari** [comment]
@commy2 only my two cents to the weight thing... i dont understand why i need to know the lb if i can activate lb if i want them... so there is a weight that i never need to know/see
@alganthe ok, the let the buttons... i will disable them on my own.

**Comment by Dystopian** [comment]
I also don't like showing both weights idea.
> Import doesn't work in multiplayer due to a BI safety on the clipboard

**commy2** made fantastic workaround for this in CBATeam/CBA_A3#832

**Comment by alganthe** [comment]
I won't add something like this before a release.

**Comment by shukari** [comment]
I dont know why its know forced at two locations that i need to see the imperial metrics.... but settings are to hard for something like that... show everybody stuff that they dont need to see.
Im out.

**Comment by commy2** [comment]
¯\\_(ツ)_/¯
