### ISSUE TITLE
Make movable markers work on briefing map

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#5921]
This #5397 don't work.

**Comment by jonpas** [comment]
Fill out the template! 🤣

**Comment by commy2** [comment]
Make me. Apparently it's "just" broken on the briefing screen.

**Comment by jonpas** [comment]
#5397's original comment says exactly that.
> You can only move markers on the main map and **nowhere else like briefing or zeus** (could be added when needed).

**Comment by chris579** [comment]
Tbh I just was too lazy to search for the right display for briefing and zeus.

**Comment by commy2** [comment]
Is merged.
