### ISSUE TITLE
Unable to successfully uninstall ACE3

### ISSUE THREAD

**Issue by tomahost1996** [acemod/ACE3#5925]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.11.0` (stable)

**Mods:**
```
- CBA_A3
- ACE3
- RHSAFRF
- RHSUSAF
- USAF
```

**Description:**
_- Add a detailed description of the error. This makes it easier for us to fix the issue._
I wanted to play Arma 3 without using ACE3 (due to some issues I'm having regarding explosion sounds but also because I want to keep Arma as stock as possible) but now I get some errors when I want to open scenarios in the Eden Editor. 

Errors I'm getting include **ace_gforces** and **ace_realisticnames**. I just want to know how I can properly uninstall the mod without corrupting my save files. I seems like some units are being reconfigured as being made by ACE3 (identified by the ACE3 logo next to their name).

**Steps to reproduce:**
_- Add the steps needed to reproduce the issue._
Create a scenario using ACE3 and place some units. Save and then delete the mod. Load the same scenario afterwards.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.
None

**RPT log file:**
N/A

**Comment by tomahost1996** [comment]
@commy2 I should have better explained myself, it's when I try to open a scenario. But I have found the solution, by saving the scenario as a non-binarized file I can delete the ACE entries under [Addons]. When I then try to open that file it works perfectly.

**Comment by commy2** [comment]
Close?

**Comment by tomahost1996** [comment]
Yeah, I think so. I should have researched a bit more before opening a ticket, sorry about that!

**Comment by commy2** [comment]
Np. It's inconvenient and we'd like to change it. But it's all BI's fault and a mod can't really change this behavior.

**Comment by tomahost1996** [comment]
I see. My Arma knowledge is very basic and I just like to experiment or create crazy scenarios (haven't even touched the campaign yet). But I can see why it's frustrating for mod creators like you, it seems like this is a simple thing (at least to me) to do (check whether or not the mod is active and then decide what to do with the mod's entries). Too bad I don't know anything about the coding aspect because that's where the real power lies of the editor.
