### ISSUE TITLE
RHS littlebird and Fries

### ISSUE THREAD

**Issue by Armilio** [acemod/ACE3#5933]
**Arma 3 Version:** `1.78` 
**CBA Version:** `3.5.0` 
**ACE3 Version:** `3.11.0` 

**Mods:**
```
- CBA_A3
- ace
- RHS
- Niarsenal
- Task force Radio
```
**Description:**
- RHS_MELB_MH6M (the littlebird with benches) does not support FRIES, but i suppose it should. I mean, Hollywood movies are a good source right? also photos on the internet. And https://github.com/acemod/ACE3/pull/4685 .

**Steps to reproduce:**
- Place a RHS_MELB_MH6M on a map in the editor.
- Double click, no "equip Fries" option.
- So try to sync the Fries module with the heli.
- Start the mission to see if it works.
- No option to "prepare the ropes" at all.
- Try with a UH-60 or any other helicopter and see that it works generally.

**Where did the issue occur?**
- Dedicated /  Editor (Singleplayer) / Editor (Multiplayer) / 

**RPT log file:**
https://pastebin.com/tBs2csf7

**Comment by Whigital** [comment]
MELB's have builtin fastrope gantries, so no FRIES needed. They support fastroping out of the box with optional ace_compat_rhs_usf3 loaded.

**Comment by Armilio** [comment]
Ok sorry i'm stupid, i was thinking that "prepare the ropes" action was always needed, but it's only when it's not builtin.
