### ISSUE TITLE
When disabling ace_explosives, disabling a mine triggers ace_frag

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5936]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0.171204` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- JSRS sound mod

```

**Description:**
Hi, for some reasons I not use files - _ace_explosives, ace_minedetector_ and I use vanilla system of explosives. Without ACE explosives all works well, however, at the disarming explosives, an invisible explosion takes place (without sound and effects) Mine can be disarmed, but at this moment the explosive fragments fly out and sometimes kill a near soldiers or personal mine-clearing soldier (explosive specialist) Probably the file responsible for the fragments still works! In the any case, it should not work if the mine has been defused  
VIDEO: https://www.youtube.com/watch?v=I9gYchGTaoo&feature=youtu.be

So there is the second problem. If you put the Claymore and is will behind him at a distance > 15-20 meters!, then the explosion of this mine can kill you or any person standing behind the activated mine! You know that this should not happen, since the striking space of Claymore is on the other side. Claymore must strike only ahead of itself (the curved part of the mine) but not in the back. 
VIDEO: https://www.youtube.com/watch?v=m3p8A2dDvaI&feature=youtu.be

Please solve this problems (the modularity of the ACE3 mod should work well) or tell me how I can solve it myself. Thanks in advance...

**Steps to reproduce:**
1)  Switch off files (to move to another place):
ace_explosives.pbo.ace_3.12.0.29-2ac191db.bisign
ace_minedetector.pbo.ace_3.12.0.29-2ac191db.bisign
ace_explosives.pbo
ace_minedetector.pbo
2) place in the map your as commander and explosive specialist (your subordinate)
3) tell the your subordinate (explosive specialist) to install Claymore
4) move to a distance of more than 15 meters (behind striking space of Claymore)
5) order to explosive specialist (your subordinate) - Disarm mine or Activate Mine
You will see that a soldier can die from an invisible explosion or you yourself will be killed / wounded.

**Where did the issue occur?**
-Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- None

**Comment by bux** [comment]
>So there is the second problem. If you put the Claymore and is will behind him at a distance > 20 meters!, then the explosion of this mine can kill you or any person standing behind the activated mine! You know that this should not happen, since the striking space of Claymore is on the other side. Claymore must strike only ahead of itself (the curved part of the mine) but not in the back.

This also happens in vanilla.

**Comment by ZeusWrath** [comment]
> This also happens in vanilla.

no, you're wrong. Yesterday I checked it.  I turned off ACE 3 and saw that there was no problem!  I even put a soldier at a distance of 5 meters behind the striking space of Claymore and he was alive

**Comment by jonpas** [comment]
Did you try it more than once? In exact same conditions?

A video or screenshots would help.

**Comment by ZeusWrath** [comment]
> Did you try it more than once? 

Of course I tried many times. In addition to the tests, several times I was killed in a mission this way.

>  A video or screenshots would help

VIdeo was added in main description, see two example

> Do we apply fragmentation to claymores?

Lol! You ask this from me? Of course you use fragmentation for Claymore and this is an irresistibly coll detail from ACE mod! Please do not disable fragmentation for Claymore or other mines which are have fragmentetion at explosion.  Just do so that it does not work during the demining!

> That would explain it if their fragmentation is not directional.

I can not call the fragmentation of Calymore not directed. After installation and during activation, it seems to me that this works correctly. But as seems to me,  the player (which is located behind mine) does not was kiled by meansl the fragments. Such player can be killed by means the radius of the explosion, which for some reason has a large range. This is a second problem.  
Not necessary Fragmentation has relation only to first problem (when soldier can disarm already installed mine)

**Comment by jonpas** [comment]
No, I am asking whoever knows.

And standing behind a claymore is lethal when it goes off as well AFAIK.

**Comment by bux** [comment]
>And standing behind a claymore is lethal when it goes off as well AFAIK.

depends on the distance

--- 

>Mine can be disarmed, but at this moment the explosive fragments fly out and sometimes kill a near soldiers or personal mine-clearing soldier (explosive specialist) Probably the file responsible for the fragments still works! In the any case, it should not work if the mine has been defused

can confirm


> So there is the second problem. If you put the Claymore and is will behind him at a distance > 15-20 meters!, then the explosion of this mine can kill you or any person standing behind the activated mine!

doesn't happen for me

**Comment by jonpas** [comment]
@bux 
> Switch off files (to move to another place):
> ace_explosives.pbo.ace_3.12.0.29-2ac191db.bisign
> ace_minedetector.pbo.ace_3.12.0.29-2ac191db.bisign
> ace_explosives.pbo
> ace_minedetector.pbo

**Comment by bux** [comment]
@jonpas 

![image](https://user-images.githubusercontent.com/1235520/34297144-aa2e5540-e716-11e7-9054-51219a5bcfe0.png)

**Comment by jonpas** [comment]
Well that was a fast reply. 😆

**Comment by ZeusWrath** [comment]
> doesn't happen for me

you can be protected by an armor / helmet. Remove the fucking helmet and repeat this -

https://www.youtube.com/watch?v=m3p8A2dDvaI

**Comment by jonpas** [comment]
Keep your comments civil or we are closing this.

**Comment by PabstMirror** [comment]
frag is triggering because there actually is a firedEH from "put"

**Comment by commy2** [comment]
Thank you bux for editing the issue title. Now it all makes sense.
