### ISSUE TITLE
ace modules?

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#5939]
**Arma 3 Version:** 1/78
**CBA Version:** `last
**ACE3 Version:** 3-12-0

**Mods:**
```
- CBA_A3
- ace
```
Sorry, but where i can see all ace modules? find only http://joxi.ru/DrlBgy0C46N6W2
could not find it http://joxi.ru/xAeBg3MCYvwK9r   logistic and medic parts

**Comment by bux** [comment]
We made multiple announcements already. Please subscribe to https://twitter.com/ACE3Mod or https://www.facebook.com/ACE3Mod/

https://ace3mod.com/2017/12/20/cba-settings.html
