### ISSUE TITLE
ACE Arsenal / BI (Vanilla) Arsenal loss of saved presets / cross compatibility

### ISSUE THREAD

**Issue by SkyeGuy** [acemod/ACE3#5940]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.0.29` (stable)
**Mods:**
```
- CBA_A3
- ace
```

**Description:**
This is more of a complaint than a bug, but it is a major concern for mission makers. ACE arsenal is used instead of BI Arsenal when attempting to set unit loadouts in editor - this would be fine except ACE arsenal doesn't pull saved loadouts from those saved in the BI Arsenal. 

**Steps to reproduce:**
- To replicate the arsenal issue just place a unit and attempt to edit loadout in editor. Existing saved presets in the vanilla VA are not there. This is a significant issue for those who literally have over a hundred presets saved for various missions. The perfect solution would be to allow cross-compatibility with the existing VA system. (i.e - move presets from VA to ACE VA)

**Where did the issue occur?**
- Dedicated and in editor

**Separate question**
- Out of curiosity (and the lack of documentation as to how to do this) - How do you initialize / set an object to use the new ACE Arsenal system? What line of code (if there is any) do you put in the object's init field?

**Comment by bux** [comment]
Please split the Arsenal issue into a separate issue here on github.

Here's the answer for the modules:

We made multiple announcements already. Please subscribe to https://twitter.com/ACE3Mod or https://www.facebook.com/ACE3Mod/ to recieve all important news.

https://ace3mod.com/2017/12/20/cba-settings.html

**Comment by bux** [comment]
#5941
