### ISSUE TITLE
ACE Arsenal - Issue for Mission Makers

### ISSUE THREAD

**Issue by SkyeGuy** [acemod/ACE3#5941]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.0.29` (stable)
**Mods:**
```
- CBA_A3
- ace
```

**Description:**
This is more of a complaint than a bug, but it is a major concern for mission makers. ACE arsenal is used instead of BI Arsenal when attempting to set unit loadouts in editor - this would be fine except ACE arsenal doesn't pull saved loadouts from those saved in the BI Arsenal. 

**Steps to reproduce:**
- To replicate the arsenal issue just place a unit and attempt to edit loadout in editor. Existing saved presets in the vanilla VA are not there. This is a significant issue for those who literally have over a hundred presets saved for various missions. The perfect solution would be to allow cross-compatibility with the existing VA system. (i.e - move presets from VA to ACE VA)

**Where did the issue occur?**
- Dedicated and in editor

**Separate question**
- Out of curiosity (and the lack of documentation as to how to do this) - How do you initialize / set an object to use the new ACE Arsenal system? What line of code (if there is any) do you put in the object's init field?

**Comment by bux** [comment]
>and the lack of documentation

https://ace3mod.com/wiki/framework/arsenal-framework.html

?

**Comment by bux** [comment]
And thanks for raising your concerns. There is already something implemented to change which arsenal is being used:

https://github.com/acemod/ACE3/pull/5932

**Comment by SkyeGuy** [comment]
Thanks bux - I didn't see the framework link on the website, apologies. I'll probably spend a few hours re-making the new presets, I definitely like the new system after working with it a bit.

**Comment by bux** [comment]
This soon to be merged feature documentation might help you as well: https://github.com/alganthe/ACE3ganthe/blob/46e24d378561cd37e82436e8a32438b3e07bdadf/docs/wiki/feature/arsenal.md#11-features

**Comment by SkyeGuy** [comment]
Thanks! Definitely going to push this to my other mission devs.

**Comment by shukari** [comment]
i said it in rc2 #5904

**Comment by alganthe** [comment]
I made a function to port over BI VA loadouts to ACE Arsenal, see:
https://forums.bistudio.com/forums/topic/193161-ace3-a-collaborative-merger-between-agm-cse-and-ace/?do=findComment&comment=3257898

**Comment by jonpas** [comment]
@shukari it seems discussion in #5904 went away from this issue, that is why it is better to make one issue per actual issue and not multiple in one.

**Comment by TheNightstalk3r** [comment]
Can we get a CBA settings to disable ACE3 Arsenal overall? Can't place a Virtual Arsenal anymore in Zeus, it all turns into ACE Arsenal, which my and my group really don't want to use. A choice in the matter would be a great addition as removing addons turns into problems with server/client mismatch

**Comment by jonpas** [comment]
> ACE Arsenal, which me and my group really don't want to use.

Reason(s)?

**Comment by TheNightstalk3r** [comment]
We already have a ton of presets in the VA, and importing them all to ACE3 Arsenal and then losing them when playing vanilla is far from favourable

**Comment by coachwn** [comment]
Agree with @TheNightstalk3r having a way to disable ACE3 Arsenal via CBA settings would be optimal for us...for apparently the same reason he stated as removing addons generally turns into problems and makes it so your players are either A) stuck only playing on your servers or B) they play with you once and then consider it a pain in the ass to always update to your modset whenever they play on your server and then never return after that first time because they have a compatibility issue somewhere else and don't like dickering around with files instead of just playing.

**Comment by dedmen** [comment]
How about being optionally be able to save loadouts to the vanilla Arsenal too? 
A checkbox in the save dialog?

**Comment by alganthe** [comment]
there's no save dialog, plus the save format is different and BI doesn't do loadout verification.

**Comment by dedmen** [comment]
That doesn't change anything about what I said.
There is a dialog that shows loadouts with a name input box and a SAVE button at the bottom. That's what I mean by save dialog.
We can convert to their format.
We don't care as you still use ACE arsenal and this doesn't change anything on that.

**Comment by alganthe** [comment]
So, your current issue is that you want to have access to BI VA when ACE Arsenal is loaded, however this is still possible I did not modify any BI function, they are still present.

Is it the "modification" of the add / remove full arsenal modules that is bothering you or the fact that the 3DEN "edit loadout" entry was modified to use ACE Arsenal?

**Comment by alganthe** [comment]
This issue should be fixed in the next release, both Virtual arsenal and ACE Arsenal are available in 3DEN in the current dev version, I also separated the zeus modules to add VA and ACE Arsenal to objects, only the "open arsenal" module for units is ACE Arsenal only.

**Comment by alganthe** [comment]
can be closed now that the changes are in stable.
