### ISSUE TITLE
Nearly all ace modules missing from the editor

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [acemod/ACE3#5942]
**Arma 3 Version:**  latest stable branch
**CBA Version:** `3.x.x` latest
**ACE3 Version:** `3.x.x` latest

**Mods:**
Ace
- CBA_A3
- ace
```

**Description:**
Nearly all Ace modules are missing from the editor! (must be a scope error in the cfg vehicles)
When I place a modules composition made in a former version, the modules do appear in the assets viewer.

**Steps to reproduce:**
- Open editor!
**Where did the issue occur?**
editor

**Comment by bux** [comment]
We made multiple announcements already. Please subscribe to https://twitter.com/ACE3Mod or https://www.facebook.com/ACE3Mod/ to recieve all important news.

https://ace3mod.com/2017/12/20/cba-settings.html

**Comment by MisterHLunaticwraith** [comment]
Ok thanks for the reply, I din't think it would imply the modules would disappear. For the record I think the modules were a simpler, plainer way of doing things and allowed easier control.
