### ISSUE TITLE
Rearm Entire Vehicle doesn't work

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#5944]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- rearming entire vehicle with pylons-system doesn't work.

**Steps to reproduce:**
- place an ah-littlebird, a vehicle rearm box and a soldier on map. set ammo of the heli to 0% and rearm settings to "entire vehicle". try to rearm the chopper.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- none.

**RPT log file:**
- https://www.dropbox.com/s/8fmhc0ziy9lst81/Arma3_x64_2017-12-21_16-03-47.rpt?dl=0

**Comment by jonpas** [comment]
How doesn't it work? No interaction? Interaction but nothing happens when using it?

**Comment by madpat3** [comment]
everything works, interaction, progressbar, etc.
but when you look at the rocket magazine, it's empty... you have no ammo.

**Comment by PSYKO-nz** [comment]
the same thing is happening to me, I have tried it on our server, in the editor and in sp

the vehicles I have tried to rearm are
BI little bird
Bi Wildcat
Bi Y-32
BI Comanche
Rhs ah64
RHS little bird
RHS Bradley
and a few others

the rearm points I have used
Nemera
HEMTT Ammo
huron ammo container

regardless of the mix of those and the way they are played (DS, editor or SP) the same thing happens

I am a full engineer with a full toolkit

I go through the normal rearm process, be near the rearm point, interact, rearm, unit
nothing happens, no bar or anything, 
check the vehicle, nothing, 
i have been hammering it on the interact process and when I do I have noticed that 90%of the time nothing happens 10% of the time I see a flash of the bar, but still no rearm

I have been through my settings and also the servers settings and nothing has helped

I'm not really sure what else there is to try, everything I have tried has failed. 
repair and refuel are working fine

hope this helps

**Comment by B-Erich** [comment]
I'd like to second that.
Encountered the Issue on our dedicated server setup running Liberation Malden, trying to rearm a CSAT Punisher (HMG) or M-ATV (HMG) with the HEMTT Ammo did just bring up the procedure but the ammo count in the target vehicle doesn't change.

**Comment by PSYKO-nz** [comment]
How much more info do we need to provide to get this past "status/need more info"?

I'm more than happy to find out the info and post it, what do we need?

i do know that this issue doesn't seem to be happening when set to calibre based rearming Wyqer over at the BI Forums said he wasn't having any issues when using the calibre rearming while playing the same issue, I will test and get back to you

**Comment by PSYKO-nz** [comment]
confirmed, the rearm works when done by calibre, no joy still on entire vehicle

**Comment by bux** [comment]
>How much more info do we need to provide to get this past "status/need more info"?

I blame christmas
