### ISSUE TITLE
ACE Settings Configuration - Save / Load function is nearly unusable, as well as Import / Export

### ISSUE THREAD

**Issue by SkyeGuy** [acemod/ACE3#5945]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.x.x` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description / Request:**

- Feature request / ease of usage tweak to replace existing functionality that is now absent with using the new CBA Settings system in place of using mission modules. Before with the old system if I wanted to make a new mission with a saved preset of my ACE settings, all you had to do was place down a custom composition of a bunch of pre-made and pre-configured ACE modules. This allowed mission makers to place down a template (and share ACE settings and configs) with other mission makers via importing / exporting from the compositions folder in Arma. 
- With the new system, there is no easily-available way to replicate this, not to mention when you "Save" you settings preset within the CBA Settings interface, and you go to load up said preset, it only loads the settings for the current config window you are on, not all the dropdowns and subcategories that you spent a long time pre-configuring. This is a large hindrance to those that make missions, and is a downgrade from the previous system on many levels. 
- For example, if you are in the ACE Arsenal settings screen and wish to load in a fully-configured preset, when you load it in it only changes the settings on the ACE Arsenal page. If you go to any other setting page they remain unchanged. What is the point of having saved presets if they are not applied across the board? Mission makers now have to go through every **single** dropdown and load in from a saved preset to change all the settings (this was never an issue with using compositions in the past, all you have to do was drop the composition on the mission and off to the races, all your settings are there).

- There also is the loss of sharing the settings as well - using the export feature copies to the clipboard, yes, but importing doesn't bring up a window to paste said exported code, it just imports from whatever is on the clipboard at that moment. While importing the settings seems to work for the "Server" tab options, it doesn't work globally for the "Mission" tab options. This doesn't really make sense, as a mission maker I want to be able to apply the saved settings to the mission, not my locally-hosted server, as the dedicated server has no way to import these ACE settings like this, it relies on whatever is encoded in the .pbo mission file.
- While I fundamentally like the import / export feature (copy / paste should technically be easier to share than the compositions), it doesn't work for applying settings globally, more specifically in the Mission tab where it matters.

**Steps to reproduce:**
- Steps are stated above.

**Where did the issue occur?**
- Dedicated / in-editor

**Placed Modules:**
- N/A - now irrelevant

**Suggested Fixes:**
- I'm not exactly sure how the CBA settings "save / load" and "import / export" functions work entirely, but perhaps have a "apply to all settings / load to all settings" button (using the Save/Load system) and a "global import to all settings" button would help with this issue, as well as bringing up a window to paste exported code. This would make sharing presets significantly easier, and give back previous functionality (regarding the global import and window).

**Comment by jonpas** [comment]
https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System#export-and-import-function

> but perhaps have a "apply to all settings / load to all settings" button (using the Save/Load system)

Is coming with next CBA update: https://github.com/CBATeam/CBA_A3/pull/832

> a "global import to all settings" button

I think that was already fixed/changed, but not sure. @commy2 ?

> it doesn't work ... in the Mission tab where it matters.

You should report this over at CBA.

**Comment by SkyeGuy** [comment]
lol thanks, will do!

**Comment by kamkill01011** [comment]
Since the last update I have almost no ACE module in the editor : [https://cdn.pbrd.co/images/GZiFz4F.png](url)

Also is there a way to convert old setting to new version ? I have all my ace settings in the userconfig/serverconfig.hpp and I want to import them in the new system.

**Comment by commy2** [comment]
>For example, if you are in the ACE Arsenal settings screen and wish to load in a fully-configured preset, when you load it in it only changes the settings on the ACE Arsenal page. If you go to any other setting page they remain unchanged. 

Didn't read the whole thing yet, but this is just a visual bug. If you close and reopen the menu, the ui is updated too.
And it will be fixed with the new import/export dialog in CBA_A3 v3.6.

**Comment by commy2** [comment]
Also, read the manual, because
>Mission makers now have to go through every single dropdown and load in from a saved preset to change all the settings 

is obviously just wrong.

**Comment by MisterHLunaticwraith** [comment]
Still the cba settings system transition bugs me too, and there are conflicts with user presets on missions configured the old way (I see nametags on AIs in mp but my friends in the same game don't so I'm guessing there's a conflict somewhere). +1 on the whole sharing/making custom modules composition.

**Comment by commy2** [comment]
User error. There is no going back.

**Comment by commy2** [comment]
You probably didn't make the mission overwrite the clients with that particular setting.
Using the cba_settings.sqf is definitely easier to manage than importing a module composition.

**Comment by MisterHLunaticwraith** [comment]
Yes I'm still exploring the new system and you're right, I shouldn't judge before extensive testing. ^^ My bad!

**Comment by SilentSpike** [comment]
We're aware that there will be a transitive period that will take everyone some time to get used to the new system (and that there may be issues/missing features in the new system).

If there is feedback you're best to leave it in an issue on the CBA repository 👍 Questions are also welcome provided the answer isn't obvious from the documentation

**Comment by SkyeGuy** [comment]
@commy2 So when you save / load the preset, it does apply to all the configured settings? If I were to exit out of the settings menu then go back it actually applies them, correct? If that is the case then no major qualms on my end except for the ability to properly globally import / export (for the purposes of sharing said settings w/other missions and mission makers).

**Comment by commy2** [comment]
That is how it works, but the ui got broken in an optimization change. It will be fixed with 3.6 though. And again, it's just a visual glitch.

**Comment by MisterHLunaticwraith** [comment]
yeah after some extensive testing I remain on my initial  opinion, modules were better and clearer. Importing or loading a configuration in the cba menu only loads/imports the config for the selected category, you have to exit and come back to the addons options to refresh the list and then yes it does show all the settings for all categories (not very clear at first, expect a lot of complaints from people who like me didn't read the whole documentation ;-) ). Which yields another problem it also exports the configs for other mods. For mission makers who use different modsets for different missions it might cause a few headaches... Same issues for cba_settings.sqf . On the plus side going through every little setting made me discover new functionalities I was not aware of. And except for the transition to cba, all the new stuff is cool and ace is and remains a must have.

**Comment by commy2** [comment]
>Importing or loading a configuration in the cba menu only loads/imports the config for the selected category.

No it doesn't. It's a visual glitch...

**Comment by SilentSpike** [comment]
@MisterHLunaticwraith Can I ask what made modules better in your opinion (excepting the visual bug with importing settings)? Constructive feedback is always useful and maybe there's something we could improve
 based on it 👍

**Comment by MisterHLunaticwraith** [comment]
Sure first let me tell you that inside my community opinions are divided on the matter so it's not all black and white. My concerns are mostly that cba settings are excellent when you have only a few options to change, so many options in one menu makes for poor readability and I prefer going through separate modules one by one.  And I think the whole point of modules  in arma III is to make the editor more user friendly, modules are simple to handle and simple to place (that's why BI put them here instead of just letting mission makers do everything by code). For apprentice mission makers the learning curve will be steeper if they have to figure out how the cba_settings.sqf works etc. To be honest the power of habit is also a factor  in this but hey I'd be the first to admit it's not a valid point ;-) 

Still this is constructive criticism, I've been working on making mods recently and I have used this github almost as a reference guide, when I don't know how to do something I ask myself "hey how did the ace guys do it?" and browse though your files to have a look, and I'm always impressed by what I see. I know first hand what a long and difficult work this is so I'm sorry if my earlier comments came off a bit blunt!

**Comment by SilentSpike** [comment]
I can understand the preference to some extent (though personally I feel like categories achieve the same effect as separate modules). On the topic of UX I would point out that BI themselves decided to largely replaced modules with attributes with the introduction of the 3D editor 😝 In essence the CBA settings system is just mirroring that shift.

I'd say it's pretty unlikely that settings modules will be reintroduced, but you're certainly not the only one to have given us this feedback. Hopefully with time and familiarity the new system is suitable for everyone (especially once that visual bug is fixed) because from a development standpoint it's so much more friendly.

**Comment by commy2** [comment]
I think with the reworked export dialog from the CBA pull request I linked, it should be more user friendly to edit. The fact that you "discovered new functionalities you were not aware of" shows that it already is an improvement imo.

**Comment by MisterHLunaticwraith** [comment]
> The fact that you "discovered new functionalities you were not aware of" shows that it already is an improvement imo.

That's true :-)

**Comment by treendy** [comment]
Is this all working now? I read the CBA guide, logged in as admin on server, created a preset, saved it (adjusted so only explosive specialist can use explosives).... I restarted the mission.... i was able to place and set of a charge?

I would rather just have the settings in a file I can save on the server... as that worked well, but now we have no ace medical working at all : (

Searching everwhere for a guide to set this up incase im doing something wrong, but nothing found

**Comment by bux** [comment]
close?
