### ISSUE TITLE
RPT Error in editor after applying ACE Settings - seems insignificant

### ISSUE THREAD

**Issue by SkyeGuy** [acemod/ACE3#5946]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.x.x` (stable) - newest release as of 12/21/17
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**

- <...alue, _priority]] call CBA_fnc_hashSet;
|#|set3DENMissionAttributes [["Scenario", "...'
Error Foreign error: Unknown enum value: "cba_settings_hash"
File x\cba\addons\settins\fnc_set.sqf, line 60>

**Steps to reproduce:**
- Change any setting in the ACE Settings, then click ok. RPT error shows up for 5-10 seconds while in-editor, and also when previewing mpmission in multiplayer. Functionality of the mission doesn't seem to be significantly affected in any way so far.

**Where did the issue occur?**
- Editor / Multiplayer (likely present in dedicated RPT as well, though not tested)

**Placed Modules:**
- N/A - irrelevant

**Comment by alganthe** [comment]
BI issue, fixed in the dev branch and perf branch, ignore this.

**Comment by jonpas** [comment]
BI issue, can be ignored. Same thing as #5833.
