### ISSUE TITLE
ACE Modules no longer showing in Mission Editor

### ISSUE THREAD

**Issue by obrien979** [acemod/ACE3#5948]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** 3.5.0.171204 (stable)
**ACE3 Version:** `3.12.0.29 (stable)

**Mods:**
```
- CBA_A3
- ace
- CUP_Weapons
- CUP_Units
- RHSUSAF
- RHSAFRF
- RHSGREF
- RHSSAF
- CUP_VEHICLES
- CUP_Terrians-Core
- CUP_Terrians-Maps
- Task_Force_Radio
- VSM_ALL_IN_ONE_COLLECTION

```

**Description:**
I was working on a SP mission this afternoon with all the ACE modules showing and working.  I placed a few on the map, saved the game and then shut down the game for a while.  When I came back recently to it tonight, I noticed that Steam was updating ARMA 3.  Once the updates were finished I went back to the same map that I just saved and proceeded to continue with my SP mission design.  I then noticed that in the Modules tab, under ACE and ACE Modules....the ones that originally shown were no longer then.  I am referring to Advanced Medical, Spawn AI, Advanced Ballistics, etc..  The modules I originally placed on map are still there, I am just unable to put new ones down. 

**Steps to reproduce:**
Loaded SP Editor and looked in Modules tab.

**Where did the issue occur?**
 Editor (Single player)

**Placed Modules:**
SPAWN AI, SECTOR TACTIC, GAME LOGIC

**Comment by jonpas** [comment]
Please read the description on the release page: https://github.com/acemod/ACE3/releases/tag/v3.12.0
