### ISSUE TITLE
New NV vision mode much to dark

### ISSUE THREAD

**Issue by ir0n1e** [acemod/ACE3#5949]
Arma 3 Version: 1.80
CBA Version: current
**ACE3 Version:**current

Mods:
CBA RHS BWA3 ACE

Description:

It is not possible to see things at night with NV attached
Steps to reproduce:

Play it
Where did the issue occur?

Everware
Well the new view is quit cool, but in real it is the 100m view... At 5m you can see you buddy with smallest light source. And the main problem is the KI sees more then you. It is A2 like trees ans KI...

**Comment by jonpas** [comment]
This is by design. NVGs have no light to enhance if there is no light coming in (or very small amount).

You can change settings to make them easier, or keep them realistic and use flashlights in very dark nights.

**Comment by ir0n1e** [comment]
Useless "Restlichtverstärker" - don't code it just play it!

**Comment by jonpas** [comment]
I have no clue what that is supposed to mean, I don't speak German. And I didn't code it, but I have played it.

I will say again:
> You can change settings to make them easier

**Comment by dedmen** [comment]
This was in testing/feedback phase for about a full year. Everyone was fine with it. And it's realistic and that's what ACE is about.

**Comment by ir0n1e** [comment]
Well, if the KI have the same one it will be great.

**Comment by dedmen** [comment]
I completly agree. Please join BI and do that.
