### ISSUE TITLE
ACE OPTIONS button unresponsive -world=empty

### ISSUE THREAD

**Issue by 2old2bagamer** [acemod/ACE3#595]
I've noticed that the ACE OPTIONS button on the main menu doesn't work when you launch Arma 3 with the -world=empty launch parameter. Does this have something to do with how the menu is rendered?

**Comment by PabstMirror** [comment]
Known issue.  I will try to add something to hide the menu if there is no world loaded

**Comment by 2old2bagamer** [comment]
Cool thanks! I tried searching before I posted this, but didn't see it reported on here.

Just out of pure curiosity, do you know what it is about loading a blank world that may cause this?

**Comment by commy2** [comment]
There is no missionNamespace (the namespace all global variables are saved in) on the loading screen if there is no mission running.

Also, CBA functions are PREP'd on pre init, which happens during mission start. Therefore the functions aren't even compiled in all other available namespaces. This is gonna change in a future update of CBA though AFAIK.

**Comment by 2old2bagamer** [comment]
Ahh ok, thanks for the info!
