### ISSUE TITLE
Screen Flickers Black When Firing With NVGs

### ISSUE THREAD

**Issue by hurtles** [acemod/ACE3#5951]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS AFRF, USAF, GREF, and SAF
- Ace RHS compatibility files
```

**Description:**
- When firing a weapon at nighttime whilst using NVGs the screen flickers black occasionally. Sometimes it is half the screen other times it is the full screen

**Steps to reproduce:**
- Load Editor
- Set time to night
- Use any NVGs
- Fire Weapon and observe flickering screen

**Where did the issue occur?**
- Dedicated / Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**Comment by jonpas** [comment]
That is by design, more information in this video at this timestamp: https://youtu.be/sOrUP0Rq6Jg?t=8m30s

**Comment by hurtles** [comment]
My apologies. Thank you for your response.

**Comment by jonpas** [comment]
No problem, it should've been on our wiki. Enjoy!

**Comment by SilentSpike** [comment]
Hmm, I wonder if we could implement a better abstraction closer to the white artefact. I'm thinking creating a local light source briefly at the players feet 🤔

**Comment by jonpas** [comment]
Sounds intensive to do @SilentSpike, especially for a small thing like this.

**Comment by SilentSpike** [comment]
Yeah was just thinking that, but we could have the lightsource ready to go and just toggle the `setLightBrightness` which would be less so

**Comment by jonpas** [comment]
That could work.
