### ISSUE TITLE
Arsenal llm01 listenig with scpe 0

### ISSUE THREAD

**Issue by ir0n1e** [acemod/ACE3#5952]
Arma 3 Version: 1.80
CBA Version: current
**ACE3 Version:**current
Mods:
CBA RHS BWA3 ACE
Description:
It is not possible to see things at night with NV attached
Steps to reproduce:
Play it
Where did the issue occur?
Everware
My Items have scope = 0. Why are thy listed in the arsenal list? 
bwa3 LLm01 is listed 5 till 6 times now...

**Comment by dedmen** [comment]
Your description is invalid.
Your Versions are invalid.
Your `Where did the issue occur` is invalid.
Sorry. Try again.

**Comment by SilentSpike** [comment]
Please don't spam the issue tracker. Thanks.

**Comment by dedmen** [comment]
![notepad _2017-12-22_03-31-09](https://user-images.githubusercontent.com/3768165/34282812-92f4554e-e6c8-11e7-8cfd-89b813c35e86.png)
They are not scope 0.
