### ISSUE TITLE
The new NV system(black mask) covers the action menu of the UI, Action menu, HUD (It is impossible to manage subordinate AI)

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5954]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0.171204` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- JSRS sound mod

```

**Description:**

 The new effects (v 3.12.0) of the new NightVision look good, but only in parts. New NV-system creates a whole host of additional problems. Now the action menu, icons of subordinates and the HUD in general are completely closed  for vision of player! Besides that it looks silly, now the player does not see what orders to give to his AI-subordinates! How does a player play single missions? This becomes impossible!
Yes, the mask is a little transparent, but on the dark backgrounds or in the other dark plaсes the action menu remains completely indistinguishable for the player vision. The player during the battle, just do not have time to adjust the viewing angle to a light background! Please do something, the action menu, subordinate icons and HUD are should not bе covered a black mask.
In addition, the transparency of the mask (black zone) is an extremely unrealistic feature, as the player does not need to see through parts of the NV that do not have optical glasses. We all know - Black Mask - this is not the transparent part that simulates the shape of NV goggles

**Steps to reproduce:**

Play at night with NV goggles and AI-subordinates  in the dark places (away from light sources, indoors)

**Where did the issue occur?**

Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**

 None

**RPT log file:**

Not required

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/blob/master/addons/nightvision/functions/fnc_setupDisplayEffects.sqf#L54
Should be `createDisplay`.

**Comment by ZeusWrath** [comment]
Unfortunately I'm not strong at script writing. Please clarify more precisely. Where should I insert this script block? 

I also care about the question. You will not make it work by default? The previous NV-system did not create such problems. Black background existed under the necessary interface. It was possible!

**Comment by Armilio** [comment]
Maybe a simpler solution is to use the NVG_wide.

**Comment by jonpas** [comment]
This is more or less by design even, read [here](https://github.com/acemod/ACE3/pull/4694#issuecomment-263766246).

**Comment by Manticore9** [comment]
My opinion about the new NV

https://www.youtube.com/watch?v=ylWHvrCtczk

**Comment by ZeusWrath** [comment]
> Maybe a simpler solution for you is to use the NVG_wide.

Within a singleplayer missions, the player does not always have a choice. For example when playing in community singleplayer missions, vanilla singleplayer, TacOps DLC,  etc 

> This is more or less by design even, read

Ok I read there it:

> Covering of the UI and Action menu is a notable downside to this. But the more time I spent with the system, the less of a problem I thought it would be. The border is still semi-transprent so you can still read the UI through the mask.

Is the fact that the border is semi-transparent is normal?  Why no one disputes this? Excuse me but the black mask should not be transparent even by 5%! The black part is just a simulation of the shape of the NV glasses.  In addition, transparency of black mask - is strange feature and do not need in general,  also it is impossible to see anything through the dark part. What then is the meaning of this transparency?

In the description, PabstMirror reports:

> It does seem faint in screenshot, but I think it's different in-game as you eye's get used to the darkness.

I can tell,  Not in the game exactly as in this screenshot! [https://cloud.githubusercontent.com/assets/9376747/20737555/0ddf8aa8-b673-11e6-8133-061cccae2427.jpg](url)  In dark places of the map at the night, it is impossible to discern anything from action menu

Still, I do not understand how the player can solve the problem? How and where to use it? Please explain me  more understandable

> Should be createDisplay.

**Comment by commy2** [comment]
Not every note I left here is made for players. You can't change this on your own (without fixing and building the addon yourself) and I never said you could.

**Comment by ZeusWrath** [comment]
The player сan not  fix it themselves? 
The player must endure this...
then unfortunately I will have to remove ACE NVision it is impossible to play with this


By the way! Can the player use the file responsible for NVision from the previous build 3.11? Can this create problems?

**Comment by jonpas** [comment]
> Is the fact that the border is semi-transparent is normal?

Yes, we can't simulate them as realistically as we would want, compromises must be made.

It is definitely possible to see through the dark part, I can see everything fine on that screenshot even. Turn up your monitor brightness maybe.

> then unfortunately I will have to remove ACE NVision it is impossible to play with this

Then do so, thanks for the feedback, even though it would be much more useful during the year of testing ST NVG.

> By the way! Can the player use the file responsible for NVision from the previous build 3.11? Can this create problems?

It will not work.

**Comment by ZeusWrath** [comment]
ACE team Thanks for the your attention and answers! 

Excuse me, still to be honest, I have to say that ACE3 does not only make the game better it always adds additional problems,  which seems strange to me, 
If I were in your place, I would never use additional options capable of destroying something else,  because one step forward and one step back this is not progress.

**Comment by jonpas** [comment]
You are welcome to create your own ACE3 if you think you can do better. Or simply not use what you think destroys something.

**Comment by PabstMirror** [comment]
@ZeusWrath - Just change the NightVision setting "Effect Scaling" to 0 and the border will be disabled (mission restart will be required)

**Comment by ZeusWrath** [comment]
Please do not take offense at my thoughts. But I see that so you have it

> You are welcome to create your own ACE3 if you think you can do better

Unfortunately I'm not good at writing scripts, It is unlikely

> @ZeusWrath - Just change the NightVision setting "Effect Scaling" to 0 and the border will be disabled (mission restart will be required)

Thank you @PabstMirror I will try
