### ISSUE TITLE
Export code from new ACE Arsenal

### ISSUE THREAD

**Issue by Bubbus** [acemod/ACE3#5955]
**ACE3 Version:** `3.12.0`

**Description:**
First off, the new ACE Arsenal is very cool and I wanted to give my thanks up front.  It's got some nice additions but there's one little change which has got me stuck.  With that said:

- The old BI arsenal produced code of this form when you press the `EXPORT` button:

```
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

this forceAddUniform "U_LIB_GER_Unterofficer";
for "_i" from 1 to 6 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_morphine";};
for "_i" from 1 to 3 do {this addItemToUniform "LIB_8Rnd_9x19_P08";};
this addVest "fow_v_heer_k98";
for "_i" from 1 to 5 do {this addItemToVest "fow_5Rnd_792x57";};
this addItemToVest "LIB_shg24";
for "_i" from 1 to 3 do {this addItemToVest "LIB_8Rnd_9x19_P08";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addHeadgear "fow_h_ger_feldmutze";

this addWeapon "fow_w_k98";
this addWeapon "LIB_P08";
this addWeapon "LIB_Binocular_GER";

this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
```

This was incredibly convenient for mission-making: I could use the arsenal to build loadouts very quickly, and then export the loadout to SQF and use it as a template for player and AI loadouts.

The new ACE arsenal export code looks like this:

```
[
    ["HLC_wp_M134Painless","","acc_pointer_IR","optic_Aco",[],[],""],
    ["rhs_weap_smaw_green","","","",["rhs_mag_smaw_HEAA",1],[],""],
    [],
    ["xmas_santa_uniform",[["ACE_fieldDressing",10],["ACE_bloodIV",2],["ACRE_PRC152",1],["ACE_epinephrine",4],["ACE_morphine",10],["ACE_Banana",1]]],
    ["VSM_LBT6094_breacher_AOR1",[["ACE_10Rnd_338_API526_Mag",2,10]]],
    ["UK3CB_BAF_B_Carryall_Arctic",[["rhs_mag_smaw_HEDP",2,1]]],
    "H_HelmetB_grass",
    "UK3CB_BAF_G_Tactical_Black",
    [],
    ["ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_urb_F"]
]
```

This cannot be used for the same purpose.

I have tried to adapt to this by looking in your codebase for a function which takes a player parameter and a data parameter, and applies the loadout data to the player.  The closest I've found are `fnc_buttonLoadoutsLoad` and `fnc_buttonImport` which contain the appropriate logic but are only usable for their specific intended purposes.

For me to continue making my mission, I need to either:

1. Exit Arma, disable ACE3 and re-enter Arma.  Then Exit and re-enable ACE3 when I want to test my mission.
2. Find a way to temporarily disable ACE Arsenal in-game.
3. Find a way to use this new export-code with a server/global function call to populate a player/AI's loadout. Ideally a call like `[player, loadoutData] call ace_arsenal_fnc_applyLoadoutToPlayer;`.

Option 1 is really slow and chunky but it's what I'm doing at the moment.  Can anyone help me achieve Option 2 or Option 3?

Thanks all.

**Steps to reproduce:**
1. Go into ACE Arsenal and create a loadout.
2. Press the Export button and paste into Notepad.
3. The exported code is very different!

**Where did the issue occur?**
- Eden editor.

**Comment by jonpas** [comment]
What ACE Arsenal outputs can be directly used with `setUnitLoadout` command, which is a lot faster than what Virtual Arsenal gives you.

**Comment by Bubbus** [comment]
I've just given that a try in singleplayer and you're right, it works very well.  It's listed as global in biki so I'll assume it works perfectly on dedis too.

I can update my mission framework to use this instead.  Thanks for the help!

**Comment by jonpas** [comment]
It does indeed, make sure to only call it from one machine to not cause multiple executions. :)
