### ISSUE TITLE
RHS Ah 64 can't be armed with Ace' Hellfire

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#5956]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- ace-rhs-compats
```

**Description:**
- in versions of the apache there is no option to mount the Ace-Hellfire.  

**Steps to reproduce:**
- place apache, open attributes and try to arm with the ace-hellfire.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer).

**Placed Modules:**
- none.

**Comment by madpat3** [comment]
tried the RC. no change.

**Comment by madpat3** [comment]
please, don't forget it.

**Comment by Cephel** [comment]
Is it possible to also make ace hellfires the default hellfires for all editor placable variants? I think RHS comes with a bunch of variants by default with various pylon configurations.

**Comment by Cephel** [comment]
What about the Cobras?

**Comment by madpat3** [comment]
if you mean ah1-z, they can be armed with the ace hellfires, already
