### ISSUE TITLE
RHS AH6 Littlebird can't be armed with dual-pylon-Ace3 Hellfire

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#5957]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- ace-rhs-compats
```

**Description:**
- the rhs littlebirds can carry 4 rhs hellfire rockets (two on each side), but with ace hellfire rockets, you only have the option of two (one on each side).
**Steps to reproduce:**
- place rhs littlebird, open attributes and arm with the ace-hellfire.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer).

**Placed Modules:**
- none.

**Comment by PabstMirror** [comment]
I didn't have models for a double hellfire.
I guess I could use RHS's model and add a 2x mount in the compat pbo

**Comment by madpat3** [comment]
tried the RC. no change.

**Comment by madpat3** [comment]
please, don't forget it.

**Comment by dedmen** [comment]
Bad bot

**Comment by jonpas** [comment]
@PabstMirror was that ever added?

**Comment by madpat3** [comment]
please (not pushing) just saying, please.

**Comment by dedmen** [comment]
Can we add a milestone?
