### ISSUE TITLE
ACE Arsenal pan camera mouse control reversed from BI Arsenal

### ISSUE THREAD

**Issue by Drofseh** [acemod/ACE3#5960]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- When holding LMB and dragging to pan the scene in BIS the character follows the movement of the mouse pointer.
https://gyazo.com/26e27040d295c42843595af17e92be8f

- In ACE Arsenal the character moves in the opposite direction of the mouse pointer.
https://gyazo.com/be6a586af2a1ba396fbea07f9ed39821

**Steps to reproduce:**
- Open BI Arsenal, pan camera, open ACE arsenal, pan camera

**Where did the issue occur?**
- Editor (Singleplayer) / Virtual Arsenal

**Placed Modules:**
- None

**Comment by alganthe** [comment]
There's a setting to invert the horizontal controls.

**Comment by Drofseh** [comment]
`There's a setting to invert the horizontal controls.`

Do you mean the vanilla setting in `Options -> Controls -> Mouse -> General`?
Or is it an ACE specific setting for the arsenal?

**Comment by alganthe** [comment]
ACE Arsenal setting

**Comment by PabstMirror** [comment]
"Invert camera controls"
https://github.com/acemod/ACE3/blob/master/addons/arsenal/XEH_preInit.sqf#L12

**Comment by Drofseh** [comment]
> ACE Arsenal setting

Perfect, thanks!
