### ISSUE TITLE
ACE NVG rolling shutter simulation changes colour of NVG visual

### ISSUE THREAD

**Issue by Drofseh** [acemod/ACE3#5961]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- When a muzzle flash activates the rolling shutter simulation the colour of the NVG picture changes from green to green/yellow.
https://gyazo.com/b0bf07b338e698f4658227982f79af95

**Steps to reproduce:**
- Set time to night, equip NVGs, fire weapon until rolling shutter effect happens

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**Comment by jonpas** [comment]
Does it go back to original colour after some time?

**Comment by Drofseh** [comment]
> Does it go back to original colour after some time?

Not that I've noticed. I've speed time up to 4x and let it sit for a couple minutes.
