### ISSUE TITLE
Feature request: Add ability to search loadouts in ACE Arsenal

### ISSUE THREAD

**Issue by SkyeGuy** [acemod/ACE3#5965]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.x.x` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Feature Suggestion:**
- Add the ability to search both "My Loadouts" and "Default Loadouts" in the ACE Arsenal via search boxes (just like the ones for weapons and equipment).

**Justification:**
- This would be an incredibly helpful feature for mission makers, as well as the general populace - there are quite a few of us that have a large number of loadouts saved and being able to search for them would be very helpful / save time.
- It seems that y'all were able to put search boxes for the equipment (a massive help, thanks!) but this was just something that seemed fairly simple to implement and also in-line with what was done with the equipment and weapons.

**Comment by alganthe** [comment]
> It seems that y'all were able to put search boxes for the equipment

I remade arsenal from scratch, I didn't just edit it out.

I'll see what I can do.

**Comment by jonpas** [comment]
There is a specific issue for feature requests: #3594

But I will leave this open for now since it's already planned/WIP.
