### ISSUE TITLE
Addons configuration menu

### ISSUE THREAD

**Issue by Lyaskavka** [acemod/ACE3#5966]
**Mods:**
- CBA_A3
- ace

**Description:**
- Dear ACE team, I understand that switching to configuration addon menu is technically much better than modules...but it does not work. I mean, its buggy, its clutchy, its simply uncomfortable. Even if you save the preset of configs - its uncomfortable to load it every mission you edit. Its uncomfortable to search for required parameters. I dont need every folder of every ace config, i just want to place modules i need. Your steam page is just full of people asking for module system and i am one of the many. Please, return old modular system. Thanks.
Would be great to have optional config to turn off ACE arsenal, because it causes me endless loadings even on empty map (virtual) with no mods (game started, in the editor mode it works fine).

**Steps to reproduce:**
- Return back old module-system.

**Where did the issue occur?**
- Mission editing and configuration

**Comment by jonpas** [comment]
No, we are not switching back. You don't even seem to understand how CBA Settings work so read the documentation: https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System

> Would be great to have optional config to turn off ACE arsenal, because it causes me endless loadings even on empty map (virtual) with no mods (game started, in the editor mode it works fine).

Simply delete the PBO. Create a separate issue for the bug, it has nothing to do with the tile or main topic of this one.
