### ISSUE TITLE
Question: NVGs and AI with them.

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [acemod/ACE3#5972]
Question: since the (very cool) NVG filters make it much harder for players at night, does it also impact AIs using nvgs in any way eg. reduce their spot distance/ awareness proportionally to the handicap the players are having?

**Comment by jonpas** [comment]
No, it is up to mission makers to adjust accordingly. We don't want to modify AI in any way to not cause incompatibilities with various AI mods.
