### ISSUE TITLE
Disabling advanced fatigue via cba_settings_fnc_set doesn't have effect

### ISSUE THREAD

**Issue by MiatWarp** [acemod/ACE3#5975]
**Arma 3 Version:** `1.78` (stable)
**CBA Version:** `3.x.x` (stable)
**ACE3 Version:** `3.1.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Hello. I'm tried to call `["ace_advanced_fatigue_enabled", false, true, "server"] call CBA_settings_fnc_set;`, to disable fatigue. CBA option was changed, but fatigue remain active. I'm trying to make addon that disable fatigue. How can i disable fatigue? I must use CBA pre-init or post-init event? And which command?

**Steps to reproduce:**
- Open editor
- Go to options -> addon options
- Enable ACE Advanced Fatigue
- Start any mission
- Try to disable fatigue in addon options or via script command
- Fatigue still remain

**Where did the issue occur?**
-  Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- none

**Comment by jonpas** [comment]
Advanced Fatigue does not support toggling it on the fly, as most settings from ACE3 don't yet.

You should also not use that function as it is not public API, and you won't be given support for using it. If you want an addon to disable it, read the documentation on [CBA Settings](https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System).
