### ISSUE TITLE
mapAnimAdd, mapAnimCommit and related commands not functional

### ISSUE THREAD

**Issue by Alpha993** [acemod/ACE3#598]
The commands do not work whatsoever with the ACE mod enabled. The commands are just skipped and the map remains unaffected. The commands worked as expected with ACE disabled.

**Comment by jaynus** [comment]
Although we appriciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html
