### ISSUE TITLE
after move a marker marking on map is toggled on

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#5980]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
after move a marker with ALT+mouseclick... marking on map is toggled on you need to mouseclick to turn off again

**Steps to reproduce:**
- Place marker
- move the marker with ALT+mouse
- the yellow map marking is active after moving
- need to click on map to disable

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by SilentSpike** [comment]
I believe #5922 intends to fix this

**Comment by commy2** [comment]
^ Yes, although it's not in yet.
