### ISSUE TITLE
Fortify function call

### ISSUE THREAD

**Issue by JCae2798** [acemod/ACE3#5981]
**Arma 3 Version:** `1.80.143869` (stable)
**CBA Version:** `3.5` (stable)
**ACE3 Version:** `3.12` (stable)

**Mods:**
- CBA_A3
- ace
-ACEX

**Description:**
https://forums.bistudio.com/forums/topic/193161-ace3-a-collaborative-merger-between-agm-cse-and-ace/?do=findComment&comment=3258926

When loading plain mission and calling the below code in DEBUG Console, the UI is missing and does not work for fortify objects:

CODE:
player addItemToVest "ACE_Fortify";
[side player, 5000, [["Sandbag", 5], ["Bunker", 50]]] call acex_fortify_fnc_registerObjects;

Screenshot:
http://steamcommunity.com/sharedfiles/filedetails/?id=1245220970

**Steps to reproduce:**
-Load Eden editor, and place down single unit
-Load mission and call the above code in DEBUG
-Test actions in UI and you will see the bug from SS.

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / 

**Placed Modules:**
- NONE

**RPT log file:**
- If required i will post extire file, but no obvious errors that i can find to report:
 8:18:51 [CBA] (settings) INFO: Checking mission settings file ...
 8:18:51 Script 'cba_settings.sqf' not found
 8:18:51 Starting mission:
 8:18:51  Mission file: tempMissionSP
 8:18:51  Mission world: VR
 8:18:51  Mission directory: C:\Users\Frantz Cadet\Documents\Arma 3 - Other Profiles\John%2eC\missions\tempMissionSP.VR\
 8:18:52 "John.C/BIS_fnc_log: [preInit] ""DeltaTime computation started"""
 8:18:52 [2059,46.22,0,"XEH: PreInit started. v3.5.0.171204"]
 8:18:53 [ACE] (common) INFO: Parsed Settings Configs [93.0 ms]
 8:18:53 [ACE] (medical) INFO: Extension version: ace_medical: 3.8.4-ef4d289
 8:18:53 [2059,46.919,0,"XEH: PreInit finished."]
 8:18:53 [2061,47.281,0,"XEH: PostInit started. MISSIONINIT: missionName=tempMissionSP, missionVersion=53, worldName=VR, isMultiplayer=false, isServer=true, isDedicated=false, CBA_isHeadlessClient=false, hasInterface=true, didJIP=false"]
 8:18:53 [2061,47.3,0,"CBA_VERSIONING: cba=3.5.0.171204, ace=3.12.0.29, acex=3.3.0.6, "]
 8:18:53 [ACE] (common) INFO: ACE is version 3.12.0.29.
 8:18:53 [ACE] (common) INFO: CBA is version 3.5.0.171204 (min required 3.5.0)
 8:18:53 CallExtension loaded: ace_break_line (C:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@ace\ace_break_line_x64.dll) [`¥û0]

 8:18:53 [ACE] (common) INFO: Extension version: ace_break_line: 3.8.4-ef4d289
 8:18:53 CallExtension loaded: ace_parse_imagepath (C:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@ace\ace_parse_imagepath_x64.dll) [rÕY]

 8:18:53 [ACE] (common) INFO: Extension version: ace_parse_imagepath: 3.8.4-ef4d289
 8:18:53 CallExtension loaded: ace_clipboard (C:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@ace\ace_clipboard_x64.dll) [rÕY]

 8:18:53 [ACE] (common) INFO: Extension version: ace_clipboard: 3.8.4-ef4d289
 8:18:53 CallExtension loaded: ace_fcs (C:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@ace\ace_fcs_x64.dll) [rÕY]

 8:18:53 [ACE] (common) INFO: Extension version: ace_fcs: 3.8.4-ef4d289
 8:18:53 CallExtension loaded: ace_advanced_ballistics (C:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@ace\ace_advanced_ballistics_x64.dll) [3.12.0-8ddde18]

 8:18:53 [ACE] (common) INFO: Extension version: ace_advanced_ballistics: 3.12.0-8ddde18
 8:18:54 [2061,47.803,0,"XEH: PostInit finished."]
 8:18:54 [ACE] (common) TRACE: 2062 Reading missionConfigFile params: _paramsArray=[] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:23
 8:18:54 [ACE] (common) INFO: Settings initialized.
 8:18:54 [ACE] (common) INFO: 2 delayed functions running.
 8:18:54  Mission id: ae76de327c8788882939738dcf287a07c1fc54f2
 8:18:54 No speaker given for 
 8:19:02 Cannot create non-ai vehicle Sandbag,  //(****OCCURS WHEN TRYING TO SELECT MISSING ACTION FROM UI)

**Comment by jonpas** [comment]
This is actually an ACEX feature, not ACE3 -> https://github.com/acemod/ACEX/issues

**Comment by PabstMirror** [comment]
Need to use actual classnames from CfgVehicles (can get from tooltip in editor)
```
[west, 5000, [["Land_BagFence_Long_F", 5], ["Land_BagBunker_Small_F", 50]]] call acex_fortify_fnc_registerObjects
```
Function header had non-working example, will be fixed via https://github.com/acemod/ACEX/pull/100

**Comment by JCae2798** [comment]
Whoops, sorry for posting it in wrong location.

As for classname notes, thank you!  FYI, that was pulled directly off ACEX Wiki
