### ISSUE TITLE
ACE3 Modules Missing from Eden Editor

### ISSUE THREAD

**Issue by smithtj3** [acemod/ACE3#5982]
**Arma 3 Version:** `1.80.143869` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Many of the ACE3 modules are no visible in the Eden Editor. ACE3 modules placed in missions prior to v3.12.0 are still present and functioning in game as intended.

**Steps to reproduce:**
- Load ACE3 and CBA3 and enter the Eden Editor. View available modules.

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- none

**RPT log file:**
![ace3](https://user-images.githubusercontent.com/34893646/34388051-7cd106d0-eb29-11e7-9852-806d97c60e97.jpg)

**Comment by jonpas** [comment]
This is not a bug, please read the description above the last release change log.
