### ISSUE TITLE
Duplicate items in ACE Arsenal

### ISSUE THREAD

**Issue by neilzar** [acemod/ACE3#5983]
**Arma 3 Version:** `1.80` (stable / rc / dev)
**CBA Version:** `3.5.0` (stable / dev + commit hash)
**ACE3 Version:** `3.12.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- NIArms All-in-One
- and a bunch more...
```

**Description:**
- NIA has weapons with different models for the same gun, but with different magazines. Currently these weapons get duplicated in the ACE Arsenal. Example is the G36C, it has a regular 30 round mag model and a 100 round mag model. Both are displayed in the arsenal, but the only difference is the icon of the weapon.
- This does not happen in the BI Arsenal

**Steps to reproduce:**
- Load the ACE Arsenal with NIArms AIO loaded.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- N/A

**RPT log file:**
- [gist](https://gist.github.com/neilzar/ea96679261992d33ee80d0751bc6b6d8)

**Comment by jonpas** [comment]
Example: `hlc_rifle_G36A1` vs `hlc_rifle_G36A1_CMAG`

Those special mag variants (eg. CMAG above) of NIArms weapons are `scopeArsenal = 0` and are only used with magazine switch script that comes with NIArms. We shouldn't be showing those as the author explicitly doesn't want it to be shown.

**Comment by dedmen** [comment]
ACE Arsenal ignores `scopeArsenal`. I can't see why anymore because Slack doesn't allow me to view old messages.

**Comment by PabstMirror** [comment]
`} foreach configProperties [_configCfgWeapons, "isClass _x && {2 == (if (isNumber (_x >> 'scopeArsenal')) then {getNumber (_x >> 'scopeArsenal')} else {getNumber (_x >> 'scope')})} && {getNumber (_x >> 'ace_arsenal_hide') != 1}", true];
`

**Comment by dedmen** [comment]
@PabstMirror That could display stuff with scope=0.

**Comment by PabstMirror** [comment]
Are there any guns with scopeArsenal =2 but scope = 0?
This is from bis's arsenal which works
```
_scope = if (isnumber (_class >> "scopeArsenal")) then {getnumber (_class >> "scopeArsenal")} else {getnumber (_class >> "scope")};
if (_scope == 2 ....
```

**Comment by dedmen** [comment]
I could imagine many modders who make very basic subclasses that only changes the model path or a texture would just use `scope=0` to hide that class and expect it to be hidden everywhere.
The base class still has `scopeArsenal=2` though.
