### ISSUE TITLE
Tripwire Flare Issue

### ISSUE THREAD

**Issue by Zycorge** [acemod/ACE3#5997]
**Arma 3 Version:** `1.80` (Stable)
**CBA Version:** `3.50` (Stable)
**ACE3 Version:** `3.12` (stable)

**Mods:**
- CUP Terrains
- CBA_A3
- ace
- RHS
- SMA

**Description:**
- ACE Tripwire flare just drops a flare on the ground at the detonation location rather than shooting a flare into the sky.

**Steps to reproduce:**
- Setup ACE Tripwire flare. 
- Run over the tripwire

**Where did the issue occur?**
- Editor (Multiplayer)

**Placed Modules:**
- None

**RPT log file:**
- N/A
Screeshots:
https://i.imgur.com/tsRS9s6.jpg
https://i.imgur.com/WXxFcaT.jpg

**Comment by alganthe** [comment]
I reproduced the issue successfully with CBA stable and ACE3 stable.

**Comment by alganthe** [comment]
Sidenote, the white circle the flare creates is a BI issue, I can reproduce it in vanilla and it's even worse due to the amount of smoke they produce there...

**Comment by commy2** [comment]
Which is?

**Comment by Drofseh** [comment]
tripflare burning at ground level is realistic.
https://www.youtube.com/watch?v=v_rBOxc9Has

I wouldn't mind a launched version as well though.

**Comment by PabstMirror** [comment]
Most trip flares I saw were just ground bursting.

Ground level flares are simpler, make it easier to spot the location of the trip, and won't illuminate friendly observers.

I'll tag as feature request if someone wants to add a 2nd type: https://github.com/acemod/ACE3/issues/3594
