### ISSUE TITLE
ACE Arsenal switches camera to edited unit on exit when fnc_openBox is used on not player unit

### ISSUE THREAD

**Issue by 10Dozen** [acemod/ACE3#5998]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5` (stable)
**ACE3 Version:** `3.12.0.29` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Vanilla Arsenal can be opened on AI unit (actually on other players too) using next syntax:
`["Open",[true,objNull, AI_Unit_1]] call bis_fnc_arsenal;`
And it is extremly useful in Zeus games.

But if I open ACE Arsenal on AI using:
`[player, AI_Unit_1, true] call ace_arsenal_fnc_openBox` or `[AI_Unit_1, AI_Unit_1, true] call ace_arsenal_fnc_openBox`
Then after Close button is pressed - camera sticks to edited AI unit.

It will be awesome, to make ACE Arsenal (which is much faster than vanilla) usable on AI.

**Steps to reproduce:**
- Start mission with AI unit name AI_Unit_1
- Execute `[AI_Unit_1, AI_Unit_1, true] call ace_arsenal_fnc_openBox`
- Click 'Close' button

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Comment by 10Dozen** [comment]
UPD:  Checked from Zeus interface - works ok, on close - returns to Zeus.

**Comment by alganthe** [comment]
Can confirm, will look into it.

**Comment by alganthe** [comment]
Fixed in #5996
