### ISSUE TITLE
ACE3 Nightvision And Enemy AI

### ISSUE THREAD

**Issue by TheNightstalk3r** [acemod/ACE3#6004]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5` (stable)
**ACE3 Version:** `3.12.0.29` (stable)

**Mods:**
```
- CBA_A3
- ace
- ACEX
- RHS USAF, UFRF
- VSM AIO
- Few other mods that don't touch/have NVGs or ACE3 Mechanics
```

**Description:**
Nightvision effects are only applied to players. Enemy AI is not affected by any of it.

**Steps to reproduce:**
Place player and enemy 200m apart with the lightest setting for ACE3 Nightvision. Player will not be able to see anything beyond 50m, the AI however will see the player coming from over 200m and open fire. This does not give a realistic immersion into the game.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None (CBA Settings used)

**Comment by commy2** [comment]
By design. The mission maker can adjust the AI skill, and that is way better than ace interfering with AI mods again.
