### ISSUE TITLE
Feature Request: Change ace_map_defaultChannel and ace_vehicle_vehicleStartingLockState from Slider to Dropdown list

### ISSUE THREAD

**Issue by BrenSilent** [acemod/ACE3#6014]
**CBA Version:** `3.x.x` (stable)
**ACE3 Version:** `3.12` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Currently the Setting for the default Channel is a Slider with Values from -001 to 005. I am pretty sure that it would be quite easier to just have a dropdown menu with the channelnames. Anybody who never had to modify channels probably has to google which number refers to which channel.

- Same idea for the Vehicle Lock. 

**Steps to reproduce:**
- Open CBA Settings and go to "Ace Map" or "Ace Vehicle Lock" Category

**Where did the issue occur?**
- Dedicated/ Editor

**Comment by PabstMirror** [comment]
Will be fixed by #5984

**Comment by BrenSilent** [comment]
As far as i could see in that PR that only fixes the "Map" category. I couldn´t find a PR for the vehicle category so i am leaving another comment here...

**Comment by dedmen** [comment]
For reference: https://github.com/acemod/ACE3/blob/master/addons/vehiclelock/ACE_Settings.hpp#L23
