### ISSUE TITLE
[German Translation] Typos and possible improvements

### ISSUE THREAD

**Issue by Lujan1405** [acemod/ACE3#6015]
**CBA Version:** `3.x.x` (stable)
**ACE3 Version:** `3.12` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- As the issue is the german translation i will write this issue in German. Obviously not all of them are wrong but may be improved. Which are changed are obviously up to you guys and i probably missed the one or other thing. But here goes my list(Sorted by category and not by error). They are all Ace errors so i will drop the "ace" infront of all the category names.

1. Allgemein:
- Im TT(Tooltipp) für "Textfarbe der Hinweise" Standartfarbe -> Standar[d]farbe
2. Arsenal:
- Alle TTs sind englisch
3. Aufmunitionierung
- "Aufmunitioniermenge" steht im Widerspruch zum TT "Wie schnell...". 
- "Munitionsvorat" -> Munitionsvor[r]at" Fehler ist mehrfach aufgetreten
4. Cook off
- Kategoriename ist englisch
- "Munitionsselbstzündungdauer" -> "Munitionsselbstzündung[s]dauer" sowohl Name als auch TT
- Cook-off probability coedff -> Übersetzung fehlt
5. Fingerzeig
- TT für Reichweite "Standart" -> "Standar[d]"
6. Gehör
- Bei ace_hearing_earplugsVolume und ace_hearing_unconsciusnessVolume fehlt die deutsche Übersetzung. Respektive es werden die Attribut Namen direkt angezeigt
7. Interaktion
- Im TT für negative Bewertungen: "erhalten Spieler nur positive Bewerungen" -> "Bewer[t]ungen"
8. Karte
- "Zeigen Sie die Namen der Spieler?" Attributname klingt komisch im Vergleich zu den anderen. Ich würde den Attributnamen wie den (fehlerfreien) TT nennen: "Zeige einzelne Spielernamen". Der TT könnte dann zu "Zeigt die Namen der einzelnen Spieler an" geändert werden. 
9. Logistik
- "Erweiterer Pionier" hieß früher "Reparaturspezialist" IIRC. Das klingt auch deutlich schöner. Zu finden in den Dropdownmenüs.
- ace_repair_autoShutOffEngineWhenStartingRepair steht als Attributname da. 
10. Magazine Repack
- Kategoriename ist englisch. 
11. Markierungssystem
- Der Name des Attributs lautet "Schnelle Markierung". Das ist in meinen Augen äußerst missverständlich da der Großteil von einer Kartenmarkierung ausgeht. Auch wenn es unschön ist würde ich entweder ein "Spraydose" hinter Kategorie- und Attributname setzen oder Ausnahmsweise beim englischen "tagging" bleiben
- Dropdown Einträge "Zufall X" und "Zufall" sollten vielleicht im TT des Attributs erklärt werden.
12. Ace Nightvision
- Übersetzung fehlt komplett
13. Ace Pylons
- Übersetzung fehlt komplett
14. Sanitäter
- ace_medical_enableOverdosing, _allowDeadBodyMovement, _allowUnconsciousAnimationOnTreatment, _moveUnitsFromGroupOnUnconscious, _ai_enabledFor, _menu_maxRange sind die Attributnamen
- Einige der Dropdowns sind englisch
15. Switch Units
- Kategoriename ist englisch
- ace_switchUnits_enableSwitchUnits ist der Attributname
- Der TT des Sicherheitszonenradius gibt als Standard 200m an. Der Wert ist Standardmäßig jedoch 100m
16. Uncategorized
- Kategoriename ist englisch
- "Gforces Effekte" -> "Effekte der G-Kräfte"
- "Min Damage to trigger falling" fehlt die Übersetzung
17. Vehicle Lock
- Kategoriename ist englisch
- "Standard-Pick-Stärke" ist als Attributname unklar da es um die Geschwindigkeit geht. Der TT klärt das zwar auf aber der Name könnte besser gewählt werden. Mir selbst fällt aber nichts besseres ein daher kann der Punkt auch gerne ignoriert werden 👍 
18. Waffen
- "Persistent weapon laserpointer/flashlight" für Name und TT fehlt die Übersetzung
19. Zeige Spielernamen
- ace_nametags_showCursorTagforVehicles, _playerNamesViewDistance, _playerNamesMaxAlpha sind Attributnamen
20. Zuschauer
- Kameramodus <-> Sichtmodi. Beide sollten gleich benannt sein. 

Sicherlich ist die Liste nicht vollständig und vermutlich hab ich selbst den ein oder anderen Typo eingebaut. Aber ich hoffe das hilft erstmal 👍 

**Where did the issue occur?**
- Settings Menu

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**Comment by xrufix** [comment]
Ich kann mir das gerne mal anschauen.

**Comment by BrenSilent** [comment]
Ich habe mich um den Großteil der Stringtables mittlerweile selbst gekümmert. Was noch fehlt sind sämtliche ace_xxx_xxx Attributnamen da man denen erstmal ne ID in der Stringtable zuweisen müsste und ich den Code selbst nicht anfassen wollte. 
Desweiteren sind noch die englischen Dropdown Einträge im Medicmenü zu fixen. Die sind aktuell hardcoded in der medical Ace_settings.hpp: https://github.com/acemod/ACE3/blob/master/addons/medical/ACE_Settings.hpp#L31

**Comment by jonpas** [comment]
Closed by #6016
