### ISSUE TITLE
NVG grain goes to full in darkness after pausing the game

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#6017]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (dev `a28ebb1b8dec345ab9aa12b50af5ed20038276dc`)
**ACE3 Version:** `3.12.0` (dev 71909a9be33c9fbbe87bfb91a152729382100e3c)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Resuming game with NVGs on during a dark night sticks grain to full (like when it is paused) while it should set it back to pre-pause value.

Pre-pause:
![20180103190938_1](https://user-images.githubusercontent.com/7935003/34533330-169235a6-f0ba-11e7-8f70-704d613efd1d.jpg)
Post-resume:
![20180103190942_1](https://user-images.githubusercontent.com/7935003/34533333-176aeda6-f0ba-11e7-89ff-0f4bdb3f6001.jpg)

**Steps to reproduce:**
- Set night time (doesn't seem to happen when there is visibility without artificial lights)
- Put on NVGs (`NVGoggles`)
- Turn on NVGs
- Pause game
- Resume game
- Observe insane grain

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- N/A

**Comment by Drofseh** [comment]
Does turning the goggles off and then back on reset it?

**Comment by jonpas** [comment]
Yes it does, forgot to mention that.
