### ISSUE TITLE
Medical AI not healing self and bleeding to death

### ISSUE THREAD

**Issue by NinjaRider600** [acemod/ACE3#6020]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
With the Basic Medical system running from ACE, the AI ignore their injuries and simply bleed to death upon injury. I've tried isolating the issue but even after reinstalling the game, the AI never heals itself with ACE Medical enable on basic setting.

**Steps to reproduce:**
1. Place any squad with a player in the editor.
2. Shoot friendly in the leg.
3. AI does not attempt to heal self and bleeds to death.

**Where did the issue occur?**
Tested on Dedicated, Self-Hosted Multiplayer, Singleplayer and Editor (Singleplayer)

**Placed Modules:**
None, AI configured to heal self through Addon settings of the mission.

**RPT log file:**
https://pastebin.com/GwDD8fRr

**Comment by dedmen** [comment]
That is not a RPT log file. https://community.bistudio.com/wiki/Crash_Files#Arma_3

**Comment by NinjaRider600** [comment]
Yeah the game doesn't crash as the issue is really just about AI not using their healing behavior with Basic medical enabled for them.

**Comment by commy2** [comment]
RPT is a log file. BI just has bad naming habits that extend to their documentation.

**Comment by NinjaRider600** [comment]
I can try to snatch one if it's gonna help.

**Comment by NinjaRider600** [comment]
@commy2 @dedmen I have updated the post and included my RPT log file recorded when I tested the issue again.

**Comment by NinjaRider600** [comment]
Issue fixed when I made a new profile.

**Comment by Qlay** [comment]
I have the exact same issue, the AI just wouldn't heal.
Made a new profile and that fixed it.
Once I loaded an old mission it stopped working again, AI is back on not being able to heal once more in all instances.

**Comment by NinjaRider600** [comment]
@Qlay I pinpointed the problem in the profile setting I had. What caused the AI to stop healing themselves was the "Medical Enabled" setting that must be set on "player" or "disabled" as, by its description found by keeping the mouse on it, is a setting concerning the ADVANCED medical system only which is not designed for AI. Setting that setting to "Player and AI" was the cause of the issue in the end.
