### ISSUE TITLE
ACE Overpressure settings are missing from CBA settings menu.

### ISSUE THREAD

**Issue by Drofseh** [acemod/ACE3#6026]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- ACE Overpressure CBA settings don't appear in the menu
https://gyazo.com/9d863448df9ba3e27e918d893d047606
- Overpressure Distance Coefficient appears under ACE Uncategorized.
https://gyazo.com/99489b0b325428d9a7352b8d902ee437

**Steps to reproduce:**
- Go the the new ACE settings, there is no ACE Overpressure entry.

**Where did the issue occur?**
- Dedicated Multiplayer / Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- https://pastebin.com/8eG3pXn5

**Comment by PabstMirror** [comment]
We already add a ton of categories, I think it would just get more crowded if we add a new one for each addon; the drop down category selection is already awkward to use.

So for now I think lesser used, non-client settings will probably get stuck in the Uncategorized group.

**Comment by SilentSpike** [comment]
Hmm, there is a slight advantage to categorising based on addon in that users can see which addon settings they're actually editing. Though for some it would literally be a single setting to a category.

**Comment by Drofseh** [comment]
I assumed that overpressure being missing was an oversight, not design.

Personally I'd strongly prefer a category for each addon, and have all setting (even server only ones) available there.

**Comment by dedmen** [comment]
Milestone > ongoing

**Comment by jonpas** [comment]
Closing as we're getting nowhere with this. Accepting PRs to group them nicer, but one setting per category is redundant.
