### ISSUE TITLE
some DIR error on Javelin/Titan

### ISSUE THREAD

**Issue by Arkblade2015** [acemod/ACE3#603]
**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
ace_javelin
ace_missileguidance

**Description:**
it still once change fire mode to DIR, can't change back anymore.

and DIR mode can't seem to hit normally.

it can't destroy tank even if use behind them.
target distance is irrelevant.

**Steps to reproduce:**
lock on and fire

**Where did the issue occur?**
"Singleplayer"*

**Comment by rlex** [comment]
In addition:
1) When you change attack mode, you can't load rockets to titan. It "loads", available in inventory interface and can be seen in tube, but HUD is red and i can't fire

**Comment by Arkblade2015** [comment]
fire mode fixed, thanks.

but still DIR mode can't seem to hit normally.

it can't destroy tank even if use behind them.
i have 3 shot to NATO APC and it didn't get any damage.
target distance is irrelevant.
