### ISSUE TITLE
Fries off the ground

### ISSUE THREAD

**Issue by Arma3marine** [acemod/ACE3#6032]
I am having trouble with the AI and the Fries system. For 1 I can not make the ai use the Fries system and whenever I deploy it from an ai controlled helicopter it never touches the ground.

**Comment by bux** [comment]
Is this a bug report? If yes you ought to fill out the issue template we provide when clicking "New Issue".

**Comment by BaerMitUmlaut** [comment]
There's a waypoint in the editor you can use. Place it on an open, flat area, AI will not go low enough over buildings or other obstructions. This is a limitation of Arma's AI we can't do anything about. If you want better advice for your specific scenario (which I don't know) I'd suggest filling out the template you deleted when opening this issue.
