### ISSUE TITLE
ACE addons in Zeus

### ISSUE THREAD

**Issue by Maruviell** [acemod/ACE3#6035]
Arma 3 Version: Stable
CBA Version: Stable
ACE3 Version: Stable

Mods:

- CBA_A3
- ace

Description:

    ACE addons are no longer available in Zeus.

Steps to reproduce:

    Zeus

Where did the issue occur?

    Zeus

**Comment by PabstMirror** [comment]
Make sure the zeus module is set like below (the "all addons" is not default)

![x](https://user-images.githubusercontent.com/9376747/34655631-904a79c4-f3d2-11e7-8e2d-61e16c2503b9.png)

**Comment by SilentSpike** [comment]
It's possible I broke the logic in this function (which removes modules based on which components of ace are loaded). However, it still looks to be correct.

https://github.com/acemod/ACE3/blob/master/addons/zeus/functions/fnc_handleZeusUnitAssigned.sqf

**Comment by dedmen** [comment]
@SilentSpike Sounds unlikely. I'd think if it was generally broken that somebody would have noticed in the last 20 days since the update is out.

May I request a proper issue report? Proper version numbers, steps to reproduce and clarificiation on what "addons" are? Modules? Items? Both? Maybe even a RPT to check if the mods you list are really what you are running.

**Comment by BmanDesignsCanada** [comment]
I am also getting this issue. The modules are not even visible in the Editor. I have a script that created an ACE_moduleReviveSettings module and that isn't working either. I'm on the most recent CBA 3.5.0.171204 and ACE 3.12.1

**Comment by jonpas** [comment]
Again, modules have been deprecated in favor of CBA Settings! That is normal behaviour as of 3.12.0, there was/is a news post describing the it.

**Comment by BmanDesignsCanada** [comment]
Cool, that's what I thought but this issue had me second guessing.

**Comment by dedmen** [comment]
For reference: Zeus and Eden are completly different things.
We are btw still waiting for a proper issue report for this. If anyone also has the issue. Please help.

**Comment by PabstMirror** [comment]
@Maruviell - if you are still having issues reopen this issue with a rpt
