### ISSUE TITLE
ACE rearm not working

### ISSUE THREAD

**Issue by franbiren** [acemod/ACE3#6037]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- setting the rearm amount parameter to entire vehicle makes all vehicle ammo source unable to rearm any kind of vehicle, be it land vehicles and airplanes

**Steps to reproduce:**
- just set the "rearm amount" parameter to "entire vehicle", empty a vehicle ammo throught editor or firing its ammo and try to rearm it with any kind of vehicle ammo source

**Where did the issue occur?**
- it happened it both my own local server, a friend local server, singleplayer/multiplayer editor and exported singleplayer/multipleyer missions
**Placed Modules:**
- since ACE settings are now configured throught CBA, this is unimportant

**Notes**
-video demostrating the problem here: https://youtu.be/XJeKfc09BRM

**Comment by madpat3** [comment]
https://github.com/acemod/ACE3/issues/5944

fixed in 3.12.1 RC
