### ISSUE TITLE
Nigth Vision (2018) not responding to laser frequencies.

### ISSUE THREAD

**Issue by sciencetechworks** [acemod/ACE3#6038]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
New night vision module creates a lot of noise on the image making it very difficult to use. When in a closed room it goes completely pitch black, which would be understandable in extreme low light conditions. Real night vision does detect the light from the infrared pointer and turning it on into an enclosed area works as a valuable source of light, infrared lanterns, most of them integrated in the device, are also widely used. 

On the other hand, AI does see much better than players do when wearing night vision equipment. The wiki does not explain how to enhance/tweak the effects clearly. Realism is welcome, but not being able to illuminate the area is clearly a lack of realism. Flares were used to help during the fight, they did not affect the image quality of the devices.

**Steps to reproduce:**
Get into a dark room and switch the infrared laser pointer, that should make the room completely light, but it remains absolutely dark. 

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
Dedicated

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by dedmen** [comment]
https://github.com/acemod/ACE3/blob/master/addons/laserpointer/functions/fnc_drawLaserpoint.sqf#L86
create scripted lightsource when laser is turned on and delete when turned off. Add CBA eh for when nightvision state changes and turn light off when NV is off to make it a "IR" light. Not sure if you can just turn the lightsource on/off or if you need to delete/recreate. Both would be fine I guess.

**Comment by sciencetechworks** [comment]
As long as I understand, that would make the enemy able to see you (the soldier) no matter if he (the enemy) is wearing night vision or not... Wouldn't it be better to make the night vision script to account for the new light and enhance its levels up? Any chance adding values to the script that can be managed externally in real time? Night vision was tested during a mission in clear night and it was way easier to spot the enemy without the glasses than with them on. The simulation is giving worse results than real gen 1 (1980) technology no matter if the chosen NV was gen 4. I admit that it is difficult to see further away when wearing real night vision devices due to fixed focus lenses and limited range, Vanilla NV is too charming. Noise is well simulated and the limited FOV too, but it has been taken to a extreme that realism went out of the window and makes Night Vision useless and non-realistically frustrating.

**Comment by Cuel** [comment]
You can edit the fog/effect scaling settings to suit your needs

**Comment by sciencetechworks** [comment]
Sorry to ask, but how I do it for a device loaded from the arsenal during a mission? Base values are too low.

**Comment by jonpas** [comment]
If it's possible someone will eventually do it, @dedmen is looking into IR and other illumination as we speak, but it's not a trivial task at all. It has been discussed already.

> Noise is well simulated and the limited FOV too, but it has been taken to an extreme that realism went out of the window and makes Night Vision useless and (non-realistically) frustrating.
> Base values are too low.

That's entirely subjective, it works very well for a lot of communities, settings are there to fit your needs.

I think this should be closed as feature request, @bux?

**Comment by sciencetechworks** [comment]
Please, close it. Thank you everyone!
