### ISSUE TITLE
Hellfire LOBL-mode activation through interact menu

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#6039]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.1` (dev)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- in an attack helicopter, you can choose between three different attack types with the interaction menu: LOAL HI, LOAL LO and LOAL Dir. with the helicopter's internal lasermarker set to "on", LOAL Dir automaticly changes to LOBL in the weapon-info-display. imo, there should be a fourth types of attack mode available: LOAL HI, LOAL LO and LOAL Dir, LOBL Dir.

**Steps to reproduce:**
- place a helicopter with pilot and player as gunner on map (flying). tap ace-interaction key. you have 
two types of attack modes available, besides from the one that is already elected and displayed in the weapon's info. set to e.g. LOAL HI. tap ace-interaction key again. you have LOAL LO and LOAL Dir available. choose LOAL Dir. now the weapon's info displays LOAL Dir. do it allover again, but with laser designator "on". now when you choose LOAL Dir, weapon's info displays LOBL Dir, which is a bit disturbing.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- not needed.

**Comment by PabstMirror** [comment]
From what I had read the difference between LOAL-Dir and LOBL-Dir is just based on laser delay.
So if your laser is on when firing they would have almost the same flight path.

You can delay laser activation to make it fly the more level LOAL-DIR flight path.
Safe delay time varies based on distance to target.

**Comment by madpat3** [comment]
it's just about the ace-interaction menu, what i'm talking about. 

**everything works as intendet,** 

but you cannot choose "LOBL" with the interaction menu.
