### ISSUE TITLE
AtragMX Bullet Weight 

### ISSUE THREAD

**Issue by SgtKrunch** [acemod/ACE3#6040]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.12.0` stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- When entering bullet weight into the AtragMX for custom entries, I've noticed that when switching between gr and gm, gr usually loses a little weight because of the conversion between the two. It doesn't allow for decimal entries, it just rounds up to the next whole number.

**Steps to reproduce:**
- Enter the gr of a bullet when under the Emperial system in the AtragMX, then switch to the the Metric system, then back to the emperial system and the bullet will have lost weight.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Advanced Ballistics, wind deflection

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by ulteq** [comment]
I will look into it.
