### ISSUE TITLE
Unconscious units set to civilian

### ISSUE THREAD

**Issue by cdgea3** [acemod/ACE3#6043]
For whatever reason whenever a unit, AI or Player, is made unconscious they remain apart of the faction they were originally assigned to. Instead of being set to civilian while unconscious they stay BluFor/OpFor ect. and because of that, the AI will not stop shooting unconscious players. It become rather bizarre because if another player is to go in the line of sight of the AI that is firing on the unconscious player they will have no interest in them and continue firing on the unconscious player and will not react to seeing an enemy or even being shot at. 

So if someone can tell me how to change it back to where unconscious units are set as civilians, that would be rather nice, thank you.

**Comment by BaerMitUmlaut** [comment]
See #5987. We don't use `setCaptive` anymore, because setting units to civilian has some side effects we'd like to avoid. After the upcoming patch, AI will not shoot unconscious players anymore, even without `setCaptive`.
