### ISSUE TITLE
acex_sitting

### ISSUE THREAD

**Issue by SayHeyD** [acemod/ACE3#6045]
**Arma 3 Version:** `1.80.143869` (latest steam version)
**CBA Version:** `3.5.0.171204` (stable)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
- RHSUSAF
- RHSAFRF
- Jbad
- LYTHIUM
- Specialist Military Arms (SMA) Version 2.7.1
- Project OPFOR
- ASR AI3
- ACE Compat - RHS Armed Forces of the Russian Federation
- ACE Compat - RHS United States Armed Forces
- Advanced Towing
- BackpackOnChest
- Enhanced Movement
- Advanced Urban Rappeling
- Task Force Arrowhead Radio 0.9.12
```

**Description:**
- I created a Mission for our clan to do trainigs on. Everything works fine when i run it from the editor everything works fine (with acex) When I start the Server after a While it loops this in the [Console Log](https://pastebin.com/GR1qVk7c).

- I've tried to reinstall ace3 and acex on client and server and it still comes up with the same error.
The acex_sitting.pbo and ace_sitting bsign file are both in the ACEX addon folder.

**Where did the issue occur?**
- Dedicated Arma3 Server (32-bit) (Ubuntu Server 17.10 64-bit) (Self-Hostet) mission start

**Placed Modules:**
- No Modules Placed everything is controlled over the addon-settings (also tried it with the acex module, no success)

(Im new to arma3 mission creating, googled for about 2 weeks and found nothing)

**Comment by Cuel** [comment]
Wrong repo
https://github.com/acemod/ACEX/issues

**Comment by commy2** [comment]
Looks like ACEX is missing on the server, but not sure, because that's not the full rpt file.

**Comment by SayHeyD** [comment]
Thx for the redirection bux
