### ISSUE TITLE
config_style_checker.py does not check complete style

### ISSUE THREAD

**Issue by TheMysteriousVincent** [acemod/ACE3#6047]
`config_style_checker.py` does not check for `;` or `,` errors.
Maybe this can improve the error search of careless mistakes.

For example this wouldn't be an error:
```cpp
class test {
  testValue = 0;; //<- double semicolon
  testValue[] = {
    0,
    1, //<- "additional" comma
  };
};
```

CI's then could be tricked to deploy a release containing fatal errors.

**Comment by SilentSpike** [comment]
Same deal as #5979 will be made obsolete by #5468

Though this one is fairly easier to fix so we could do it in the meantime

**Comment by dedmen** [comment]
Waiting for #5468
