### ISSUE TITLE
About jamming weapons and medical features

### ISSUE THREAD

**Issue by JohnMcpudding** [acemod/ACE3#6050]
About jamming weapons.
During my mandatory military service we got to work with one specific AK variant known for reliability. Almost every time it jammed (quite rare with our rifles though), solution was usually simple as pulling the bolt back and let her run again. So I figured out, since there was already thing which allows you to clear jams, could there be similar alternative jam ''clearing'' method which I mentioned? Perhaps shorter time for exchange of less successful jam clear? 

Second thing about suggestion for new medical item and an feature(s).
''pneumothorax'' and ''pressure pneumothorax''. Do I need to say more?
Then to the medical item, and perhaps completely new feature. I got sort of combat life saver training during my service. There we got bit of information of this thing called ''hemostatic powder''. In a nutshell, you just pour it in vast open wounds to slow down/stop bleeding completely. And as far as I know, it is extremely effective, but makes surgeries tad bit harder. 

I hope you eventually actually look at this mad man's nonsense. 
And perhaps even consider implementing these things into you fantastic mod.
(I don't know how to github proper)

**Comment by BaerMitUmlaut** [comment]
Feature requests belong into #3594.
