### ISSUE TITLE
Nightvision script error when changing settings

### ISSUE THREAD

**Issue by chris579** [acemod/ACE3#6051]
**Arma 3 Version:** `1.80` (stable)  
**CBA Version:** `3.5.0.171204` (stable)  
**ACE3 Version:** `3.12.0` (stable)  

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- While being on our server this error appeared every time nightvision server settings changed. Nightvision generation 4 has been used.

**Where did the issue occur?**
- Dedicated

![](https://i.imgur.com/U3SoXJ9.jpg)

**Comment by PabstMirror** [comment]
You should be seeing a warning like this:
![image](https://user-images.githubusercontent.com/9376747/34932087-2d7ef462-f997-11e7-9fb9-fac60cc5fa93.png)

**Comment by chris579** [comment]
Yeah, that’s right. However, a mission restart is not required to see changes made to settings. Also this happened on just one machine but it still refreshed the view and applied the settings.

**Comment by jonpas** [comment]
Yes, as it says, restart required to prevent issues, and this is an issue you reported. :p

**Comment by chris579** [comment]
You're kinda right but I interpret this message more in that way that you should restart the mission if you have issues that settings don't get applied. This shouldn't throw script errors in any situation, shoud it?

**Comment by commy2** [comment]
It shouldn't. My opinion.

**Comment by PabstMirror** [comment]
You will only have problems when changing setting from 0 to non-zero or non-zero to 0.
(e.g. if you want to disable mid-mission, just drop to 0.01)

ACE has a lot of global settings like this that are just not designed to be changed mid mission
We had non-removable XEH or run specific code paths based on settings at mission start.
Making these settings changable on the fly is not trivial.

**Comment by KarlMoebius** [comment]
> ACE has a lot of global settings like this that are just not designed to be changed mid mission


Is it possible to mark, indent, color code, or otherwise differentiate those in the settings to help distinguish them from semi-changeable settings?

**Comment by chris579** [comment]
> ACE has a lot of global settings like this that are just not designed to be changed mid mission

Now as CBA settings have been introduced they maybe should be adjusted to be able to change them mid mission.

**Comment by jonpas** [comment]
> Now as CBA settings have been introduced they maybe should be adjusted to be able to change them mid mission.

And you should continue reading after that statement. ;)
