### ISSUE TITLE
DAGR mass too high?

### ISSUE THREAD

**Issue by KarlMoebius** [acemod/ACE3#6052]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The DAGR in ace3 has a mass of 10, 
From CfgWeapons.hpp

        class ItemInfo: CBA_MiscItem_ItemInfo {
            mass = 10;

- MicroDAGR has a mass of 2
From CfgWeapons.hpp

        class ItemInfo: CBA_MiscItem_ItemInfo {
            mass = 2;

- The equipment size seems (relatively) the same in game
- IRL DAGR (apparently) weighs ~1lb, and MicroDAGR is ~.5lb w/ batteries
- Is there more attached equipment to the DAGR inflating the weight?
- While I would suggest DAGR mass of 2 and MicroDAGR mass of 1, at the current 10 is very bulky/heavy for a seemingly small device.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by KarlMoebius** [comment]
Huh, I didn't think about it like that. As it is in game, the DAGR is the less featured, smaller (interface wise), and heavier/bulkier brother to the MicroDAGR. Strictly going by IRL weights should change, but from a gameplay perspective, would making the DAGR light as or lighter incentivize use over the micro for people that don't need all the capabilities of the micro?

**Comment by Drofseh** [comment]
Personally I'd rather they had the correct real world weights because I would choose one or the other based on the time period the mission is set in.
