### ISSUE TITLE
Questions/ feature requests about ace arsenal.

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [acemod/ACE3#6053]
Question: is there a function to equip a player/unit with exported ace format arsenal loadout something like.
[player, [ARSENALGENERATEDEXPORTCODE]] cal ace_fnc_something ?

Feature request: possibility to lock loadouts to premade mission default loadouts (players could only use mission defined loadouts and not use /load their own preset loadouts.

Feature request: Possibility to export loadout in default arma arsenal format.

**Comment by jonpas** [comment]
setUnitLoadout

There is a designated issue for feature requests.

**Comment by dedmen** [comment]
Why do you want the default arma arsenal format? The setUnitLoadout format is far more efficient and easier to export/use.

**Comment by MisterHLunaticwraith** [comment]
Just because it's nice to have the choice to choose wether you want to use a feature or not (plus I didnt't know the created array was in setUnitLoadout compatible format.

**Comment by alganthe** [comment]
I won't add an export for the "vanilla" loadout format, it's a 30+ lines script they export that doesn't support containers within containers, weapons within containers, and it's extremely inefficient.

The unitLoadout format is just plain superior.

**Comment by BaerMitUmlaut** [comment]
Closing as the main question has been answered. Feature requests can be put in #3594 as usual.

**Comment by BaerMitUmlaut** [comment]
@alganthe `setUnitLoadout` should be mentioned in the doc page to avoid this question in the future.
