### ISSUE TITLE
RHS AH-64 has no pylon loadout option for ace hellfires.

### ISSUE THREAD

**Issue by Cephel** [acemod/ACE3#6055]
**Arma 3 Version:** `1.80.143869` stable
**CBA Version:** `3.5.0.171204` stable
**ACE3 Version:** `3.12.1` stable

**Mods:**
```
- CBA_A3
- ace
- RHS
```

**Description:**
When editing the pylon configuration of the helicopter, there is no entry to add the proper ace hellfire missiles to the helicopter.

**Steps to reproduce:**
Go to editor, put down AH-64, go to pylon config.

**Where did the issue occur?**
Editor / Everywhere

**Placed Modules:**
None

**RPT log file:**
Not applicable

**Comment by madpat3** [comment]
duplicate https://github.com/acemod/ACE3/issues/5956

**Comment by Cephel** [comment]
This can be closed, search didn't show this ticket.
