### ISSUE TITLE
Map tools do not work

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#606]
ACE3 Version: 3.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* * NONE

**Description:**
Except dragging lines around the map the map tools do not work on the map. I tried every button and was not able to mesure the distance and shit on the map. The map tools don't even appear on the map.

**Steps to reproduce:**
1. Get the Map Tools.
2. They do not work.

**Where did the issue occur?**
Editor

**Comment by bux578** [comment]
Please update your issue following the guidlines mentioned here: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by gienkov** [comment]
They do work. All functions. You have to use self action menu for them on map screen. Issue invalid.

**Comment by kieran-s** [comment]
I can also confirm using self-interaction on the map brings up the map protractor thingy.
So appears to work for me.
