### ISSUE TITLE
Arsenal import not working in MP

### ISSUE THREAD

**Issue by chris579** [acemod/ACE3#6061]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Importing a previously exported loadout will result in the message `Wrong format provided`. This only happens in multiplayer as `copyFromClipboard` is being used for import.

**Where did the issue occur?**
- Dedicated

**Comment by dedmen** [comment]
And as `copyToClipboard` is being used. Which doesn't work in MP because BI intentionally blocked it...
BI's fault.

Or we make a UI with text box where you can paste stuff in. You can paste stuff in although clipboard is disabled right?

**Comment by Cuel** [comment]
Pasting should work fine

**Comment by chris579** [comment]
> And as copyToClipboard is being used. Which doesn't work in MP because BI intentionally blocked it...
BI's fault.

As there is already ace_clipboard reading from clipboard could be added there and then be used instead of BI's commands. Beside of that, if something is not working by design the user should not be able to interact with it. This error is just confusing because you could think it's a fault on your end.

**Comment by dedmen** [comment]
I'm completly against adding import to ace_clipboard. For the same reason why it was not added when it was created.

**Comment by alganthe** [comment]
true, added to my todo list.

**Comment by PabstMirror** [comment]
Closed by #6083
