### ISSUE TITLE
Arsenal exit prompt is missing cancel button

### ISSUE THREAD

**Issue by chris579** [acemod/ACE3#6062]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The prompt when exiting arsenal is missing a cancel button. Currently it's just possible to abort when pressing escape.

![](https://steamuserimages-a.akamaihd.net/ugc/940558122279527245/65CC4B82E1F5BB53776BBD158A1911644CBABCBE/)

**Comment by alganthe** [comment]
tagging @commy2
