### ISSUE TITLE
Com/supports menu disabled in ACE as well as the scroll menu

### ISSUE THREAD

**Issue by LT-DANG** [acemod/ACE3#6063]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```Star Wars opposition and related mods
- CBA_A3
- ace
```

**Description:**
- I don't think this is an error, I think these features are just disabled, specifically the 0,8 radio menu and mouse scroll menu.  I'm part of the DUWS-R team and am making a version for star wars opposition.  DUWS-R gameplay relies heavily on the radio menu for activating supports like arty and CAS.  I'm new to ACE and have figured out how to get the AI units hud back but can't seem to find anything related to radio menu in the ace options.  I tried to get around this using a new DUWS-R feature adding supports to the mouse scroll menu but that has dissappeared as well.  Is there a way around this to bring them back?

**Where did the issue occur?**
 Editor (Singleplayer)

**Comment by Cuel** [comment]
I actually have the same issue but luckily I've never had to use the radio menu.

**Comment by LT-DANG** [comment]
Actually it still works, you just have to use the tilde key (left of 1) to go to radio.  Its really clunky though, in ACE the zero key slings your weapon, is there a way to change the key?

**Comment by Cuel** [comment]
Yeah tilde doesn't work for me. You should be able to rebind weapon on back under Controls > addon options > some ace3 category

**Comment by LT-DANG** [comment]
yeah there's only 3 categories under configure addons, didn't see it in there

**Comment by Cuel** [comment]
https://github.com/acemod/ACE3/blob/master/addons/weaponselect/XEH_postInit.sqf#L98

Should be under "ACE3 Weapons" category, called "Holster weapon"

**Comment by alganthe** [comment]
Those were rebound by BI a while ago, they're on F1-F9 now afaik.

**Comment by LT-DANG** [comment]
Oh god thanks, I was trying to configure the Ace controls whilst in the Arma menu.  I found then in game when going to congfigure.  All good now....CASE CLOSED!.......Although I'm sure more questions will be coming as ace seems to be playing a bit of havoc with DUWS-R code and I havent even tested the revive system conflicts that could happen.  Speak to you soon, but hopefully not.  Thanks for the help everyone.

**Comment by LT-DANG** [comment]
Oh yeah and I would just not use ace but star wars opposition mod has an ace dependency.  Neglected to mention that earlier.
