### ISSUE TITLE
Ear Plugs not appearing in Self Interaction Equipment

### ISSUE THREAD

**Issue by VileAce** [acemod/ACE3#6066]
**Arma 3 Version:** `1.80 Stable` (stable / rc / dev)
**CBA Version:** `3.5` (stable / dev + commit hash)
**ACE3 Version:** `3.12.1` (stable / dev + commit hash)

**Mods:**
CUP Weapons 1.10
CUP Units 1.10
CUP Vehicles 1.10
CUP Weapons ACE Compatibility 1.10.1
CUP Vehicles ACE Compatibility 1.10.1
SMA
VSM All-in-One
Task Force Arrowhead Radio 0.9.12
- CBA_A3
- ace
```

**Description:**
-Added earplugs into inventory. Earplugs do not appear in the Self Interaction Menu under equipment.

**Steps to reproduce:**
- Add earplugs in inventory
- Confirm Earplugs are in the inventory
- Open self interaction menu
- Select Equipment
- Earplugs does not appear

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer) 

**Placed Modules:**
Relevant hearing settings
force ace_hearing_enableCombatDeafness = false;
force ace_hearing_earplugsVolume = 0.416493;
force ace_hearing_unconsciousnessVolume = 0.4;
force ace_hearing_disableEarRinging = true;
force ace_hearing_enabledForZeusUnits = false;
force ace_hearing_autoAddEarplugsToUnits = true;

**RPT log file:**
No Error generated,

**Comment by PabstMirror** [comment]
Earplugs require the EnableCombatDeafness setting to be enabled

**Comment by VileAce** [comment]
Thank you.  Then I would recommend changing the description for combat deafness. Right now it says something along the lines of : loose hearing as hit points decrease.

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 19, 2018 at 8:52 PM, PabstMirror<notifications@github.com> wrote:   
Earplugs require the EnableCombatDeafness setting to be enabled

**Comment by dedmen** [comment]
>Reduces the hearing ability as the player takes hearing damage
Seems correct to me.

**Comment by VileAce** [comment]
If it is required for ear plugs to work, then it should state that somewhere, but that's up to you,  obviously. I do not want to nitpick, but that is my biggest concern with ACE is the poor descriptions or total lack of descriptions.  I know as a coder you need to prioritize, I hope that at some point you consider improving the descriptions.

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 22, 2018 at 7:14 AM, Dedmen Miller<notifications@github.com> wrote:   

Reduces the hearing ability as the player takes hearing damage
Seems correct to me.

**Comment by PabstMirror** [comment]
You might want to look at the ACEX Volume Feature
https://ace3mod.com/wiki/featurex/volume.html
