### ISSUE TITLE
Chemlight not seen by everyone

### ISSUE THREAD

**Issue by jaakkoijas** [acemod/ACE3#6067]
Arma 3 Version: 1.80 Stable (stable / rc / dev)
CBA Version: 3.5 (stable / dev + commit hash)
ACE3 Version: 3.12.1 (stable / dev + commit hash)

**Mods:**
- CBA_A3
- ace

**Description:**
- When attaching chemlight to self, not everyone can see the light in multiplayer mission. Example player1 sees his own light and player2's light. P2 sees P3's light, but not P1's and P3 sees only P1 light and so on. After chemlight wears out, attaching new light might affect again how and other player sees it.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Comment by 0dr** [comment]
Have you checked that the players "dynamic lights" settings is not the cause, had seen similar years before but linked it to arma handling light(sources) badly.

**Comment by jaakkoijas** [comment]
Where is Dynamic light settings? Are you referring Options -> Video settings -> ...

**Comment by 0dr** [comment]
Yes video settings, afaik this is fault/BI

**Comment by jaakkoijas** [comment]
I checked and 'Dynamic lights' setting was at 'Ultra' (highest).

**Comment by dedmen** [comment]
Can confirm that. Don't know what causes it but we had one night mission where everyone had chemlights. And we had about a dozen occurences of someone telling someone else that he can't see his chemlight. Detaching and reattaching solved it.
I think it happens when you attach the chemlight, while outside visual range for the other player.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
