### ISSUE TITLE
Missing FRIES option/broken FRIES position (RHS compat)

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#6068]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHSUSAF
```

**Description:**
UH 1Y                      - Hasn't got a FRIES checkbox in 3den editor
UH 1Y (unarmed)    - Hasn't got a FRIES checkbox in 3den editor 
UH 60 MEV             - FRIES Bar has incorrect attachment point
UH 60                      - FRIES Bar can't be equipped ingame via "Configure Pylon"
UH 60 (unarmed)    - FRIES Bar has incorrect attachment point and
                                  FRIES Bar can't be equipped ingame via "Configure Pylon"
UH 60 (EWS)           - FRIES Bar has incorrect attachment point
UH 60 (ESSS)           - FRIES Bar has incorrect attachment point
UH 60 MEV (ESSS)  - Hasn't got a FRIES checkbox in 3den editor and                                                   
                                  FRIES Bar can't be equipped ingame via "Configure Pylon"
UH 80                     - FRIES Bar can't be equipped ingame via "Configure Pylon"
AW 159 (unarmed) - FRIES Bar can't be equipped ingame via "Configure Pylon"

for the ones, that can't be equipped ingame, this is maybe because they got no pylons,
but the UH 60 (MEV) can be equipped ingame, though it hasn't got pylons, either.

**Steps to reproduce:**
- Place those helicopters around an ammo truck and configure pylons. And check out 3den attributes.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**Comment by BaerMitUmlaut** [comment]
That's odd. I don't have those helicopters if I start with the mods you listed.

**Comment by madpat3** [comment]
XD
yeah, forgotten the RHS-usaf

**Comment by Vdauphin** [comment]
Hello, may be it is because of [this](https://github.com/Vdauphin/HeartsAndMinds/pull/460#issuecomment-355272520) for the `RHS_UH1Y_d`

**Comment by dedmen** [comment]
This is a bug.

**Comment by Whigital** [comment]
I've fixed the UH1Y, but can't really see anything wrong with the UH-60's, apart from the UH 60 MEV (ESSS) that has it explicitly disabled.
