### ISSUE TITLE
3D scope is acctually the 2D scope

### ISSUE THREAD

**Issue by xJenny99x** [acemod/ACE3#607]
ACE3 Version: 3.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
NONE

**Description:**
Found a wierd bug ... The 3d Scopes are not really 3d scopes. They are 2d scopes with a pip effect.

This is either a bug with the files that are directed to a 2D scope instead of a 3D one or just the case of having a misleading name.

**Steps to reproduce:**
1. Get a so called "3d scope"
2. Not have a 3D scope
3. Cry

**Where did the issue occur?**
Editor

**Comment by bux578** [comment]
Here again, please update your issue following the guidlines mentioned here: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by Best2nd** [comment]
ACE did not add any 3d scopes, only 2d and PiP variants of existing vanilla scopes.

Just what is this so called "3d scope"?

**Comment by gienkov** [comment]
Only addon that I know that adds scope with "3D" in name is RHS. So issue invalid.

**Comment by bux578** [comment]
The OP stated cba, ace as the only mods used.

**Comment by commy2** [comment]
But, there are no "3D-Scopes" from ACE?

**Comment by Heavygunner96** [comment]
OP is just taking the PIP-scopes as 3D scopes.
Don't know how they are named/advertised at the moment but they are, as already pointed out, not 3D scopes.

**Comment by commy2** [comment]
They are called (PiP) instead of (2D).

Maybe OP was drunk? Closing this.
