### ISSUE TITLE
Script error with camouflageCoef

### ISSUE THREAD

**Issue by JHill29th** [acemod/ACE3#6072]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0.171204` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**

| Mod Name                     | Version          | Steam  Workshop Mod ID |
| ---------------------------- | -----------------| ---------------------- |
| 29th Infantry Division       | 0.3.4            | 585738428              |
| ACE 3                        | 3.12.1           | 463939057              |
| ACE 3 Compat. RHS USAF       | 3.12.1           | 773125288              |
| ACE 3 Compat. RHS AFRF       | 3.12.1           | 773131200              |
| ACE 3 Compat. RHS GREF       | 3.12.1           | 884966711              |
| CBA_A3                       | 3.5.0.171204     | 450814997              |
| GRAD Trenches                | 1.3              | 1224892496             |
| RHS: AFRF                    | 0.4.5            | 843425103              |
| RHS: USAF                    | 0.4.5            | 843577117              |
| RHS: GREF                    | 0.4.5            | 843593391              |
| Task Force Radio (TFAR)      | 0.9.13           | 620019431              |
| CUP Terrains Core (t)        | 1.4.2            | 583496184              |
| CUP Terrains Maps (t)        | 1.4.2            | 583544987              |
| Sugar Lake (t)               | 1.320            | 550757941              |
| Gorgona (t)                  | 1.500.01         | 380892330              |
| G-O-S Leskovets (t)          | 0.2              | 855464203              |

**Description:**
```SQF
15:01:24 Error in expression <e_common_oldVisibility", _vis];
_object setUnitTrait ["camouflageCoef", _vis];
}>
15:01:24   Error position: <setUnitTrait ["camouflageCoef", _vis];
}>
15:01:24   Error Type Any, expected Number,Bool
15:01:24 File z\ace\addons\common\XEH_postInit.sqf, line 64
```

**Steps to reproduce:**
- Use Ace

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- Several Curator GM modules
- 1 Infantry respawn module per side
- TFAR settings module

**RPT log file:**
- [Arma3_x64_2018-01-21_13-38-51.7z](https://www.dropbox.com/s/y1gcew5v0svmhg5/Arma3_x64_2018-01-21_13-38-51.7z?dl=0)

**Comment by dedmen** [comment]
>Task Force Radio (TFAR) | 0.9.13

That version doesn't exist.
You forgot Ares and ShackTac HUD.

>13:49:34 Performance warning: SimpleSerialization::Write 'CBAs' is using type of ',CONTROL' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types

That is interesting... 
>13:54:34 WARNING: Function 'name' - grn_11 has no unit
The unit that setHidden was called on was dead/not fully existent. So the getVariable probably failed because of that.

>cba_versioning - grad_trenches - Version Mismatch!
