### ISSUE TITLE
Medical AI not healing self or others

### ISSUE THREAD

**Issue by Qlay** [acemod/ACE3#6073]
**Arma 3 Version:** `1.80`stable
**CBA Version:** ` 3.5.0` stable 
**ACE3 Version:** `3.12.1` stable

**Mods:**
```
- CBA_A3
- ace

and with and without
-asr ai
-vcom
```

**Description:**
- Had the same issue as (https://github.com/acemod/ACE3/issues/6020), making a new profile fixed it for a while. But after loading a former WIP editor mission the issue is back and AI stopped healing across the board. Making a new profile after that fixed it again for a bit, but it returned and AI stopped healing on all sides.

**Steps to reproduce:**
- Place units in Editor, shoot them in the leg. Play a mission, get shot, etc.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer). Tested on all acounts

**Placed Modules:**
- None

**RPT log file:**
- https://pastebin.com/gqZfWbXx

**Comment by BaerMitUmlaut** [comment]
That's not an RPT file. The server and HC (if you use one) would be useful in this case.

See https://community.bistudio.com/wiki/Crash_Files#Arma_3 for more info.

**Comment by Qlay** [comment]
Hope it helps!

Singleplayer (Editor):
Ace Debug: https://pastebin.com/kESzN3j5
RPT: https://pastebin.com/B2Q0VgGy

Self Hosted Multiplayer (Headhunters Vanilla on Stratis, on internet)
Ace Debug: https://pastebin.com/e1qgPGiR
RPT: https://pastebin.com/uqpdGBaU

Headless Client: (Editor placed BLUFOR vs OPFOR AI duking it out):
Ace Debug: https://pastebin.com/eFThvBGm
RPT: https://pastebin.com/Bg3PbShw

**Comment by AACO** [comment]
@BaerMitUmlaut it looks like medical AI exits if ace_medical_enabledFor == 1 (player and AI)
https://github.com/acemod/ACE3/blob/master/addons/medical_ai/XEH_postInit.sqf#L9
https://github.com/acemod/ACE3/blob/master/addons/medical/ACE_Settings.hpp#L31

Should this check be for  if ace_medical_enabledFor == 0 (players only)?

Looking at the posted RPTs, that's what appears to be killing medical AI for @Qlay

**Comment by BaerMitUmlaut** [comment]
The enableFor setting only applies to advanced medical, so it should be ignored when basic is used. So yes, that if needs a change. Good find, once again!

**Comment by jonpas** [comment]
Fixed by #6077
