### ISSUE TITLE
Feature request: please allow to disable the SELF medical menu through self action

### ISSUE THREAD

**Issue by Lorenz94B** [acemod/ACE3#6074]
Hello,
As title states, I would like to have the possibility to disable the "medical" (not "medical menu") action from the selfaction menu, so that medical stuff is accessible only with the menu by pressing H.

Is this possible? Thank you.

**Comment by jonpas** [comment]
Similar to https://github.com/acemod/ACE3/issues/3829 ?

Please fill out the issue ticket though, otherwise it's not a useful report at all.

**Comment by Lorenz94B** [comment]
Same exact thing. Sorry it didn't show up with the little research I did. Please refer to that report!

Thank you.
