### ISSUE TITLE
Issue with ace_tracers.pbo file

### ISSUE THREAD

**Issue by l3gitwargam3r** [acemod/ACE3#6076]
Arma 3 Version: 1.80.143869
CBA Version: 3.5.0
ACE3 Version: 3.12.1

**Mods:**
- ace

**Description:**
My issue is just today, I went hop on Arma 3 to test some things for a server I am wanting to open using ACE, but when I went to set up a private server, a message popped up stating that a few of my ACE compatibility mods were outdated. I fixed them, then it said that my ace tracers.pbo files were outdated. I searched for the most recent version of ACE, I downloaded it and it still tells me that my tracers.pbo for ace is outdated. I hope this issue can be resolved. I love this mod and it has made Arma for me that much more entertaining.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
Self-Hosted Multiplayer and VR arsenal

**Comment by BaerMitUmlaut** [comment]
The ace_tracers.pbo is located in the optionals folder of the release. Replace your old version with that one.

**Comment by l3gitwargam3r** [comment]
I have done that, but I still run into the same issue.

**Comment by PabstMirror** [comment]
Try deleting the entire `@ace` folder on client and server and then use fresh copy from github release page
