### ISSUE TITLE
ACE Arsenal hiding items

### ISSUE THREAD

**Issue by Eogos** [acemod/ACE3#6082]
**Arma 3 Version:** Whatever the latest stable version is
**CBA Version:** 3.5
**ACE3 Version:** 3.12.1

**Mods:**
```
- CBA_A3
- ace
- Unsung
```

**Description:**
- When in ACE Arsenal items from some mods (in this case Unsung) are missing/hidden for no discernible reason. Items can still be seen and used just fine when loaded into BIS Arsenal but trying to find them in ACE Arsenal will return nothing and if you import a kit that has a item that is missing in ACE Arsenal it will be removed from the kit. In this case, every single backpack from Unsung is missing. I know Unsung isn't the only mod this happens with, as I've heard other people in our community comment about missing things from other mods before as well but this is the biggest case of it happening.

**Steps to reproduce:**
1. Load ACE Arsenal
2. Try to find Unsung backpacks

**Where did the issue occur?**
- Dedicated / Editor (Multiplayer) / ACE Arsenal

**Placed Modules:**
None

**RPT log file:**
https://gist.github.com/Eogos/5db2bcce1e2d9aad49c49464257daf81 
Note: I did move some stuff in editor and what not before going into ACE Arse to start making kits when I noticed the severe lack of backpacks.

**Comment by jonpas** [comment]
@alganthe was this not fixed with 3.12.1?

> ACE Arse

That component is WIP. :P

**Comment by Yin-Yue** [comment]
I can add my own experience to this as well. CUP has a magazine for spotting rifle ammunition for its Mk153 SMAW launcher. While the magazines appear normally in VA, they are flat-out gone in ACE Arsenal. In addition, RHS has a versiopn of the Mk153 launcher also using spotting rifle magazines. These do appear within the ACE Arsenal list for ammunition, but cannot be loaded into the player inventory.

Screenshots can be obtained if necessary.

**Comment by alganthe** [comment]
Unsung backpacks (outside of 3 of them out of maybe 15+) don't have "non filled" classes, and thus are filtered out just like vanilla backpacks.

**Comment by Eogos** [comment]
Is there a way to disable this filter? Cause it's kind of an issue.

**Comment by alganthe** [comment]
it's not really a filter, it's just bad config on unsung's part, they're all scope 1 on top of that.

**Comment by alganthe** [comment]
oh, and on top of that they have their own vehicleClass for some reason, go figure.

**Comment by alganthe** [comment]
i'll change the condition, vehicleClass is indeed not an universal solution, however backpacks that can deploy respawn points will also appear (those tent ones), they also appear in VA, so I guess that'll fix it.

**Comment by alganthe** [comment]
@Yin-Yue that mag is `CUP_SMAW_Spotting` and is scope 1, thus not showing up.

**Comment by kripto202** [comment]
happens with optre too

**Comment by jonpas** [comment]
`CUP_SMAW_Spotting` is intentionally hidden (source: CUP Team).

**Comment by PabstMirror** [comment]
Closed by #6083
