### ISSUE TITLE
RHS Helicopters Pylons Configuration Ghost Pylons

### ISSUE THREAD

**Issue by Grizzly58** [acemod/ACE3#6088]
**Arma 3 Version:** `1.80.143869' (stable)

**CBA Version:** `3.5` (stable)

**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHSUSAF
- RHSAFRF
- RHSGREF
- RHSSAF
```

**Description:**
- When using Configure Pylons on RHS helicopters, any previous pylons that are removed are still in the weapon selection when cycling weapons. I.e. equip Hellfires, unequip Hellfires, Hellfires still appear in weapon selection but with no ammo.

**Steps to reproduce:**
- Load mods
- Place down RHS helicopter in editor (ex. AH-64D or AH-1Z) and a HEMTT Ammo Truck
- Configure pylons and change pylon or remove pylon armament
- Get into pilot or gunner seat and cycle weapons

**Where did the issue occur?**
- Dedicated, Self Hosted Multiplayer, and Editor

**Placed Modules:**
- None

**Comment by madpat3** [comment]
also, sometimes after rearming/changing, the pylons of the UH 60 (ESSS), it looses it's outer pylons, becomming some kind of (EWS) version. (Dedicated MP)
