### ISSUE TITLE
set it to advanced medic but is basic

### ISSUE THREAD

**Issue by JohannesW99** [acemod/ACE3#6089]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
So I make a mission and set it to advanced medic. but i put it on my dedicated server and it is basic. but when i run it on my pc the mission has advanced. pls Help
**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer /Editor (Multiplayer)

**Comment by JohannesW99** [comment]
I dont have any setting on the server the should interfere

**Comment by PabstMirror** [comment]
While connected to server, check the following 3 things in the debug console
```
["ace_medical_level"] call CBA_settings_fnc_priority
["ace_medical_level"] call CBA_settings_fnc_get
["ace_medical_level", "mission"] call CBA_settings_fnc_get
```
Priority should be "mission"

**Comment by JohannesW99** [comment]
I fix it. if any one has the same problem. join the server and press ESC and go to configuration and addon options and its in ace medic tab
