### ISSUE TITLE
Addons configuration menu do not work, SP

### ISSUE THREAD

**Issue by Ilias48rus** [acemod/ACE3#6091]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
In default campaigns missions' available,the interface's tabs do not filling with ACE options and game using default values (server's "overwrite mission" do not helping).
(previous verson with own menu working)

**Steps to reproduce:**

**Where did the issue occur?**
- Singleplayer

**Placed Modules:**
- 'None'

**RPT log file:**

**Comment by PabstMirror** [comment]
Escape menu -> Options -> Addon Options
Should list all ace options, worked for me in the SP campaign.

Mission restart may be required for some settings change to take effect.
I'm not sure, but re-loading a save may not be enough, it might require full mission restart.

If still having issues, please attach an RPT.

**Comment by Ilias48rus** [comment]
@PabstMirror Y, restart helped,
feels like kind of imcompabilty :) , but thanks for help
