### ISSUE TITLE
Connecting to HuntIr while it is getting deleted "breaks" game.

### ISSUE THREAD

**Issue by BrenSilent** [acemod/ACE3#6093]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
- BwMod
- several other will report complete list if asked for.
```

**Description:**
- I tried to connect to a HuntIr which was in air for quite some time. After searching it there briefly was shown the "connecting..." message. Afterwards i saw my own view through the HuntIR monitor. I probably hit the spot where the HuntIr was available for connection but got deleted before the screen was put up.
Album here:
https://imgur.com/a/dUmGX

After closing the Monitor my view kept the grey filter and i had the HIR compass still in the middle of the screen. Upon reopening HuntIR and searching again the message "searching" switched with "Skalar NaN" (or something similar) and it couldnt connect. Didnt get a screenshot as it changed quite fast and i didn´t think about reporting it at that stage. I had to rejoin the server to get my vision back to normal.

And if someone has a more appropriate title please change it, i wasnt sure how to call that bug.

**Steps to reproduce:**
- Couldnt reproduce as i wasnt able to get the timing right :(

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- As the error was spammed so much to the RPT i deleted around 7000 lines with the error message to be able to upload to pastebin. 
- https://pastebin.com/2ZnDWMQT

**Comment by dedmen** [comment]
>As the error was spammed so much to the RPT i deleted around 7000 lines with the error message to be able to upload to pastebin.

Did you know you can also attach files directly? Read the text under the text box. It tells you how to directly upload files. Probably doesn't support RPT but a zip archive for sure. That way you don't have the pastebin sizelimit issue.

Thanks for the good report.

Now following general advice that is not directly related to the issue but might still be of value.

Looking at the RPT `-exThreads=0 -enableHT` you should remove these unless you explicitly want your Arma to perform worse for some reason.

`19:06:26 "TFAR - tf_lr_frequency already set, might be assigning a group (B B-4) to multiple frequency modules."`
Please tell your missionmaker that he apparently doesn't understand how the TFAR frequency module works.

`19:22:05 mpmissions\__CUR_MP.xcam_taunus\mission.sqm/Mission/Entities/Item470/Entities/Item6.type: Unknown enum value BWA3_Task_Attack` Could that be a BW bug? Haven't seen that yet? 

`Performance warning: Very large search for 4629443 (>400 m)` There is now a "Hide terrain objects" module.

`Warning Message: Script \x\cba\addons\keybinding\dikDecToString.sqf not found` what?

**Comment by BrenSilent** [comment]
Thanks for the tipps. 

The TFAR thing would be my problem, but i checked that several times and i am pretty sure i am not assigning any frequencies via script or any other way and there is only one module. Furthermore that error only gets shown for units that are placed in the editor but arent used in the mission. (Our template mission has 4 groups but we only play with 3 due to our numbers)

BWA3_Task_Attack is from a mod that commy wrote for us... 1.5(?) years ago? Basically it adds 3 scripted waypoints and a "disableAi "move"" checkbox in the attributes. Nothing too relevant here but it makes missionbuilding faster and easier for us therefore we ignore that error.

For the performance warning. He did use the new module but for some reason still had a gamelogic with ids. Told him not to do it again.

This error appears upon opening the field manual. 

https://imgur.com/a/elPvz

As i didn´t open the field manual intentionally for years i never thought about reporting it.
