### ISSUE TITLE
Surgicalkit

### ISSUE THREAD

**Issue by C0kkie** [acemod/ACE3#6103]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0.171204` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Description:**
- Is it possible that you include into the medical system that you can use the surgicalKit not only on the torsor?

**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0.171204` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Description:**
- Is it possible that you include into the medical system that you can use the surgicalKit not only on the torsor?

**Comment by badkneegrow** [comment]
To add to that. A setting to allow surgical kit to fix hitPart (broken limb / shaky hand / broken leg)

**Comment by C0kkie** [comment]
Good idea badkneegrow

**Comment by dedmen** [comment]
No it's currently not possible. But it sounds like something that could be a #3594

**Comment by C0kkie** [comment]
Didnt know that site

**Comment by dedmen** [comment]
When you open a new issue it tells you
>Before you open an issue please review the contributing guidelines for this repository. 

Which links you to https://github.com/acemod/ACE3/blob/master/.github/CONTRIBUTING.md

**Comment by C0kkie** [comment]
sorry.
