### ISSUE TITLE
Enhance simplified zeroing

### ISSUE THREAD

**Issue by Ilias48rus** [acemod/ACE3#6104]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5` (stable)
**ACE3 Version:** `3.12.1` (stable)
**Mods:**

**Description:**
Its suggestion, mainly about adding horizontal adjustments.
This would allow to use "simplified zeroing" with wind and ACE's advanced ballistic in addition to arma3's default
(for letting to remove requirement to take or memorize rangeCard for each weapon you use).

**i.**
("simplified zeroing" currently do not have any horizontal adjustments)
I want to mention 2 **kinds** in which it can be added (while there still can be other):

0. "m/s" (representing speed of wind): 
for ,selected on scope, wind speed it would auto adjust in mils ,for sellected range, depending on used ammo and weapon;
1. "Mils": just same one as in full ("scope adjustments") system, it would be enough (it would still remove most of info you should know for used weapon, and horizontal adjustment can be made approximate even without rangeCard); ;

One important thing to do not forget about is **temperature**:
think it would be good to have setting for "simplified zeroing" ,which would allow to define: will adjustments be translated on mils

0. depending on temperature
1. or just for temperature with which the scope was nulled (because correct additional adjustments can be made approximate, and some more attention will be required for shooter to remember all the values for all the temperatures (keeping meaning of range cards even with simplified system)); ;

**p.s.**
And small question: where ,in ACE's files, heat vision is removed from laser designators ? ;

**Steps to reproduce:**
**Where did the issue occur?**
**Placed Modules:**
**RPT log file:**

**Comment by dedmen** [comment]
Suggestion? Aka [Feature request](https://github.com/acemod/ACE3/issues/3594)?

What is `L.D.s ? ;`

**Comment by Ilias48rus** [comment]
@dedmen y, thanks, moving

**Comment by BaerMitUmlaut** [comment]
I don't understand what you want. You're asking about horizontal zeroing but then refer to the range card. Can you try explaining again?

**Comment by Ilias48rus** [comment]
@BaerMitUmlaut simplified zeroing used to avoid requirement to use rangecards, asking to add horizontal scrolling or this could be applicable not only to default ballistic.

**Comment by dedmen** [comment]
Ahh I understand I think.
Simplified zeroing add's back the 100m increment zeroing like vanilla has. Instead of the MIL zeroing. But it doesn't support side-ways zeroing to counter wind drift.

That's how I understand it. Didn't know that it doesn't support side-ways zeroing. Or maybe is sideways zero still in MIL but @Ilias48rus want's in meters or degrees or something?

**Comment by Ilias48rus** [comment]
@dedmen as i just added to descripton, in mils is fine (same as in full system)
(and ACE's simplified zeroing adding 50m adjustments)

**Comment by BaerMitUmlaut** [comment]
What would the adjustments be? Adjusting for 1m/s wind would depend on the range for example.

**Comment by Ilias48rus** [comment]
@BaerMitUmlaut in case of "m/s" kind ,i guess change could be based on both adjustments "horizontal*vertical", but AS I SAID there is no need in such thing, just same as in full system would be fine !

**Comment by Ilias48rus** [comment]
*edited 1st post

**Comment by ulteq** [comment]
> or just for temperature with which the scope was nulled

That's how it works right now. The `simplified zeroing` feature is based off those atmosphere settings: https://github.com/acemod/ACE3/blob/e6683e8077ee283ab9d772eef5768be5dc82c395/addons/scopes/ACE_Settings.hpp#L44-L68

**Comment by Ilias48rus** [comment]
Would be logically to add feature/suggestion issues as exceptions for the bot.
