### ISSUE TITLE
Improve Lack of events / modifiers for common events / functionality

### ISSUE THREAD

**Issue by Tennessee-Timmy** [acemod/ACE3#6108]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
This way mission designers can make their missions more unique and improve on the awesome functionality.
For ex. can check if weapon was an ak and add dispersion and jam rate. Or check training lvl of a fighter and adjust accordingly. 

**Steps to reproduce:**
- nil

**Where did the issue occur?**
- nil

**Placed Modules:**
- nil

**RPT log file:**
- nil
- nil

EXAMPLES / REQUESTS:
EX1
https://github.com/acemod/ACE3/blob/db93a42891d0198feaa071e74a1b2f828932f960/addons/overheating/functions/fnc_firedEH.sqf#L44
```sqf
    _dispersion = (_dispersion * 0.28125 * (_scaledTemperature^2)) + (_unit getVariable ["ace_overheating_extraDispersion",(missionNamespace getVariable ["ace_overheating_extraDispersion",0])]);
```
Allowing per unit / mission change for dispersion.

EX2
https://github.com/acemod/ACE3/blob/db93a42891d0198feaa071e74a1b2f828932f960/addons/overheating/functions/fnc_firedEH.sqf#L100
```sqf
_jamChance = _jamChance + (_unit getVariable ["ace_overheating_extraJamChance",(missionNamespace getVariable ["ace_overheating_extraJamChance",0.0])]);
```
Allowing per unit / mission change for jamming rate.

**Comment by SilentSpike** [comment]
I'd say this should either be a pull request or much less broad of an issue.

**Comment by dedmen** [comment]
Ofcause we can make EVERYTHING configurable. But.. Why if no one or only a handful of people use it?
Also I like my performance :x

**Comment by badkneegrow** [comment]
Some simple things. Not everything. 
I guess most people don't even configure the ace settings, so that's true. No one would use them.

**Comment by thojkooi** [comment]
We will accept PR's for any events that are missing that you'd require. We won't actively add additional events ourselves unless we need those for functionality developed for ACE3.
