### ISSUE TITLE
Options for stop auto decomposition and manual decomposition for BIS's FAK and Medkit

### ISSUE THREAD

**Issue by Arkblade2015** [acemod/ACE3#611]
for the some Compatibility issue. (especially mission built-in revive scripts)

**Comment by bux578** [comment]
Thank you for your request, but this a feature request. Move it to the appropiate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html

**Comment by Arkblade2015** [comment]
sorry. i'll read guideline.
