### ISSUE TITLE
storage of intravenous infusion supplies

### ISSUE THREAD

**Issue by PaxJaromeMalues** [acemod/ACE3#6113]
**Arma 3 Version:** `stable`
**CBA Version:** `stable`
**ACE3 Version:** `stable`

**Mods:**
```
- CBA_A3
- ace*
- community modifications
```

**Description:**
Currentley it is possible to store infusion supplies of all types and sizes in your uniform, vest and backpack. While storing 250ml supplies of saline in uniform or vest is plausible it is not for the remainder of infusion supplies.
Plasma and blood of any size should be limited to `backpack` only as their transport in non-conditioned environment is rather unlikely to ever be met in combat circumstances.
While 250ml saline storage should be possible in `uniform` & `vest` limiting all 1000ml infusion supply types to `backpack`.
This likely will mess up some load outs to a, from my POV, negligible degree.
Storage of supplies in other storage elements like crates or vehicles should remain as is.

Considering the current mass/weight system and its values for ace medical supplies, which I guess are unlikely to change, this might be a way to add to more realistic infantry logistics w/o being in need to touch these complicated values at all.

This suggestion does NOT consider that some special equipment is available (like attachable leg bags) which would allow for storage of one or two 1000ml infusion bags. I think this can be neglected as well considering the fact that the combat application of such unhandy equipment is unlikely.

**Steps to reproduce:**
- Start ArmA.
- Go into Arsenal.
- Stuff 1000ml infusion bag in underpants for bonus cooling perk.
- datfaceindesert.jpg

**Where did the issue occur?**
- All

**Placed Modules:**
- ACE Medical Settings: Advanced

**Comment by SilentSpike** [comment]
I think this is a valid suggestion, we may want to include it with the rewrite since it may break some existing loadouts

**Comment by kotaco** [comment]
A unit of plasma is about 250ml. A unit of pRBC is about 300ml.  A unit of whole blood is closer to around 500ml. Any of those could fit in a vest in theory. However, blood products are only good for 4 hours outside of a color.. so there is some suspension of disbelief if you're carrying blood around at all.

**Comment by Drofseh** [comment]
While it does make sense that fluids go in a backpack, where they would be carried IRL, I personally really dislike objects that prevent me from putting them where I want them to be.

Given that:

- ACE doesn't currently simulate the storage requirements of any of the medical fluids;
- the confusion it will bring when suddenly people can't put them in their vests (and the fact that it may break loadouts);
- and that I just don't like being told where i can put my items;

I think this should not be implemented.

**Comment by Drofseh** [comment]
It is realistic that medics normally carry fluids in a backpack IRL, but there's nothing preventing them from carrying it in a vest pouch if they wanted to IRL.
And some mods, like IFA3 and FOW have medic vests that were designed specifically for that.
https://gyazo.com/53db30ec88fa5fe3ea6c0dbd9f5204e2

Some weapons can't be placed in uniforms/vests, but others can be.
I've definitely played PvP missions where we were insurgents who hid pistols in our uniforms/vests and then pulled them out during an assassination.

**Comment by jonpas** [comment]
That makes sense then.

I didn't say pistols specifically, but some weapons. It's restricted on config level.

**Comment by PaxJaromeMalues** [comment]
Kotaco, I am not exactly sure about what you are reffering to. Are these the in field used supplies by medics? Is there a standard what should be carried in operation? If you have some info about that stuff input would be highly appriciated.

I can see Drofsehs point about the pouches in IFA3 and FOW. Though I know advanced methods of IV therapy existed prior to 1945 I have no sources or any idea if they were actually used for first aid and or field care at that time.

If there is no easy way like auto assigning a value to vest items by their item name to automatically exclude pouches or bags form this change mechanic, this could indeed cause issues with some mods. I am sadly not too much into SQF scripting to know the full blowny capabilities we have with the ace framework to navigate this issue. Maybe someone else knows.

On the other hand we could change this to simply restrict blood and plasma to cooled devices like boxes, crates and some vehicles, while saline is still available for backpack and vest carrying. Unsure at this point.

**Comment by kotaco** [comment]
In my post I was talking about the standard sizes of blood products. Blood doesn't come in 1000ml bags. 

So that was in reference to the comment about blood products fitting in vests. Yes they will, pRBC (packed red blood cells) and whole blood and even plasma can all fit in vests. Though this is more realistically done with normal saline and similar fluids (isolyte, normosol, lactated ringers) and there are many vests that are preconfigured to do this/ have molle attachments for this. 

However, the caveat being that blood is transported in coolers because once it is outside of a cooler it is only viable for 4 hours before it has to be discarded.

**Comment by PaxJaromeMalues** [comment]
Sorry, misclicked

**Comment by dedmen** [comment]
Move to rewrite milestone?

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
