### ISSUE TITLE
AGM-114N Destroys Heavy Armor

### ISSUE THREAD

**Issue by jrdnmdhl** [acemod/ACE3#6114]
**Arma 3 Version:** `1.8.143869` stable
**CBA Version:** `3.5.0` stable
**ACE3 Version:** `3.12.1` stable

**Mods:**
```
- CBA_A3
- ace
- acex
- RHS USAF
- RHS AFRF
- RHS Compat - RHS AFRF
- RHS Compat - RHS USAF
```

**Description:**
- The ACE AGM-114N is capable of destroying the A3 default T-100, as well as all Russian armor from AFRF
- This is presumably unintended, given that the [AGM-114N is only considered effective vs. light armor](https://www.globalsecurity.org/military/systems/munitions/agm-114n.htm)

**Steps to reproduce:**
- Place a MELB with AGM-114N
- Place an RHS T-90, or A3 T-100
- Fire the AGM-114N at the target
- Fire a second (if necessary)
- Watch the fireworks

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- N/A

**Comment by PabstMirror** [comment]
@tbeswick96 - any thoughts?
I'd say we just drop the `hit` down quite a bit, maybe ~400?

**Comment by tbeswick96** [comment]
Yeah should be fine
