### ISSUE TITLE
Set nametags based on database via function.

### ISSUE THREAD

**Issue by 123B3n** [acemod/ACE3#6115]
Hi there,

I'm looking for a function to set players nametags, like loading them from a database and setting their nametag based on that name.

All I need is a function for it, the only one I've been able to found so far is `ace_nametags_fnc_setText` however, I'm not sure if it will work or how ACE is even reading the names, like for example would it work just setting the players name with the `setName` function for arma itself, would really appriciate someone who knows a bit more to give me a bit more info.

Cheers!

**Comment by dedmen** [comment]
It uses https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_getName.sqf to get the name. As you can see you can probably use `ACE_NameRaw` or `ACE_Name` to set it.

Also please have a read on https://github.com/acemod/ACE3/blob/master/.github/CONTRIBUTING.md
