### ISSUE TITLE
delete Ace Items in Mission.sqm

### ISSUE THREAD

**Issue by EliasOriley** [acemod/ACE3#6117]
Hello, got some interesting question.

My Company runs a publicserver and we want to get the ability to join without mods.
In the past we deletet the ACE Items out of the Mission.sqm. 

The goal is, to get new players on the server and tell them which mods they need to play the full mission.

Is there any way to get clients on the server which dont have ace?

Thanks, Elias ORiley

**Comment by PabstMirror** [comment]
Save the mission without binerization. Then open the mission.sqm with notepad.
Look for `addons[]` near the top and modify it it to remove all `ace_*` references (make sure the commas still make sense.)

so 
```
addons[]=
{
	"ace_repair",
	"ace_dragging",
	"A3_Characters_F"
};
```
to 
```
addons[]=
{
	"A3_Characters_F"
};
```

No guarantees on what will happen, clients might have several errors they need to click through.
In general you want server and all clients to have the exact same modset and you might get problems that effect everyone connected.
