### ISSUE TITLE
Set unconscious player as captive/civilian

### ISSUE THREAD

**Issue by JANXOL** [acemod/ACE3#6118]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**

Please bring back the option for unconscious players to be put back into captive state (purple icon). Or at least an option to choose whether they are supposed to be set to captive or remain BLUFOR/OPFOR. Player icons turning purple was a MASSIVE help while being zeus. You could easily spot someone being downed, now its nearly impossible - you need to keep a much closer eye on everything instead of seeing it at a first glance.

**Comment by BaerMitUmlaut** [comment]
Setting the unit to captive has some side effects we wanted to avoid. You could emulate the old behaviour with the following snippet (put it in the `initPlayerLocal.sqf` for example):
```sqf
["ace_unconscious", {
    params ["_unit", "_unconscious"];
    if (!local _unit) exitWith {};
    _unit setCaptive _unconscious;
}] call CBA_fnc_addEventHandler;
```
