### ISSUE TITLE
NVG Effects - Reduce epilepsy seizure risk to players

### ISSUE THREAD

**Issue by thraxjor** [acemod/ACE3#6119]
Hi guys I'd like to bring this to your attention as the recent NVG changes poise a risk to players health who are light sensitive.

I believe there is a risk when the following conditions are meet.

- Player is looking down iron sights, zoomed in temporary, entire screen area effected by muzzle flash effect.
- Player is not looking down iron sights, zoomed in temporary, entire screen area effected by muzzle flash effect.

I know it would be easier to just turn off the NVG effects, however maybe create a toggle to disable the muzzle flash strobe effect under the CBA settings in a hotfix or major release?

**Comment by BaerMitUmlaut** [comment]
I don't think the flashes are more intense than the muzzle flashes when shooting in the dark. Besides, there's an epilepsy warning on page two of Arma's manual, and with explosions and other flashy things happening in the game, that seems sensible. Do you personally suffer from epilepsy? Is normal gameplay not an issue?

**Comment by thraxjor** [comment]
I don't suffer from epilepsy personally, however a member our milsim unit does, and brought it to our attention. 

However in the the base games there isn't a effect that makes the screen blackout and then fills it with light in rapid secession i.e the strobe effect with using NVGs when using automatic weapons.

This is just a bit of empathy on my part about the welfare of players that aren't diagnosed who could be exposed.

**Comment by dedmen** [comment]
Talking about https://github.com/acemod/ACE3/blob/master/addons/nightvision/functions/fnc_onFiredPlayer.sqf#L58-L61 I guess.

The blackout is important from a gameplay perspective so disabling it could count as a difficulty setting and thus shouldn't be a clientside setting. But Groups might want to have it enabled by default but only allow players that have problems with it to disable it.

Maybe one could instead of blacking out the screen just blur it so much that you can't make out anything. which would create the same "can't see" effect without causing severe flashing.

**Comment by Pergor** [comment]
If it helps at all, I got the feedback from some players (maybe with a history of epilepsy) that the new nvg effects cause heavy nausea for some. Some even told of unusual experiences of exhaustion after roundabout two hours of gameplay without heavy changes to the ace_nightvision-settings.
That might be related to the concentration that is necessary to focus on the smaller fov in combination with the grizzled screen and the flashes.

All in all, while the negative feedback hasn't gained in quantity, it has indeed gained intensity. While the old grizzle and fov has been a tolerable nuissance for the nay-sayers, it has become an immense drawback for those players.

**Comment by xrufix** [comment]
@Pergor What causes grizzling is the noise effect. I get uncomfortable when looking at it in merely some seconds. But that issue is adressed in #6059

**Comment by 0dr** [comment]
Just to point out this is not that uncommon, I am affected too by this and think it needs a toggle.
I only didn't bring it up yet because NVG's are usless with the default Settings. I haven't used one since the update because I can see better without.
