### ISSUE TITLE
Going Prone with AT/AA Launcher

### ISSUE THREAD

**Issue by MickWick** [acemod/ACE3#6122]
**Arma 3 Version:** `x.xx` (stable )
**CBA Version:** `3.x.x` (stable)
**ACE3 Version:** `3.x.x` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Unable to lay down with a launcher to fire which is easily done in real life, animation is already in game.

**Steps to reproduce:**
Get launcher,
Attempt to lay down.

**Comment by commy2** [comment]
#3594

**Comment by PabstMirror** [comment]
Animations configs are pretty complex to modify and probably outside our scope.

**Comment by commy2** [comment]
Last time I checked there were missing transitional animations / incomplete animations so I gave up.
