### ISSUE TITLE
BUG with more than two pictures in slideshow (through code)

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [acemod/ACE3#6125]
**Arma 3 Version:**  latest/stable
**CBA Version:** `3.x.x` latest/stable
**ACE3 Version:** `3.x.x`latest/stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Using ace_slideshow_fnc_createSlideshow; with more than two pictures won't work. It does work when 2 pictures or 1 are set.

**Steps to reproduce:**
[[object1, object2], [controller1], ["images\image1.paa", "images\image2.paa"], ["Action1", "Action2"], 5, "My Slides"] call ace_slideshow_fnc_createSlideshow; ==> works

[[object1, object2], [controller1], ["images\image1.paa", "images\image2.paa","images\image3.paa"], ["Action1", "Action2"], 5, "My Slides"] call ace_slideshow_fnc_createSlideshow; ==> doesn't work
**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual 

**Placed Modules:**
- This is true when calling the function from a script I haven't tested it with the editor module.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by dedmen** [comment]
"won't work" Means? Game crashes instantly, nothing happens, nuclear fallout?
No. You get a error in RPT(Which you btw didn't upload.. Like the issue template says)

https://github.com/acemod/ACE3/blob/master/addons/slideshow/functions/fnc_createSlideshow.sqf#L37

**Comment by MisterHLunaticwraith** [comment]
Thanks that answers my question/solves my problem (I should have read the function ''s header but in my defense it doesn't say anything about the actions here: https://ace3mod.com/wiki/framework/slideshow-framework.html )
