### ISSUE TITLE
Simplified zeroing breaks pistols

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#6126]
**Arma 3 Version:** `1.80`
**CBA Version:** `3.5.0`
**ACE3 Version:** current master

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Enabling simplified zeroing causes pistols to shoot high.

**Steps to reproduce:**
- Enable ace_scopes_simplifiedZeroing
- Shoot at a persons head - you will miss
- Shoot center mass - you will hit the head/neck area

**Where did the issue occur?**
- Editor

**Comment by PabstMirror** [comment]
same as #6123?

**Comment by BaerMitUmlaut** [comment]
Nope.
