### ISSUE TITLE
Invisible Driver

### ISSUE THREAD

**Issue by C0kkie** [acemod/ACE3#6137]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.12.1` (stable)
**ACE3 Version:** `3.6.1.180131` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Since we've installed ace we got the problem thats sometimes not possible to get into a vehicle as driver (like the driver seat is blocked). I also cant get in with something like moveInDriver or assignAsDriver. Its like there is a invisible person in.

**Steps to reproduce:**
- Not really possible, since in different cases

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayed

**Comment by PabstMirror** [comment]
Does this happen on specific vehicles?
Does it happen after using quick mount keybind?

I've never really seen anything like this, so any information you can give would be helpful, preferably steps to reproduce.

**Comment by C0kkie** [comment]
The problem is i also cant reproduce it because there is no specific action, its completly random.

**Comment by C0kkie** [comment]
Few guys said the problem is random if there are players on the east playside online

**Comment by Cuel** [comment]
Are you playing liberation?

**Comment by C0kkie** [comment]
? We playing life

**Comment by C0kkie** [comment]
We created us workaround now

_action = ["Enterasdriver", "Enter as driver", "", {_target lockDriver false; player action ["getInDriver", _target]}, {locked _target isEqualTo 0 && {driver _target isequalto objnull} && {!(_target in blacklistedvariableace)} && {!(typeof _target in blacklistedtypeoface)}}] call ace_interact_menu_fnc_createAction;
		  ["LandVehicle", 0, ["ACE_MainActions"], _action, true] call ace_interact_menu_fnc_addActionToClass;
