### ISSUE TITLE
Katiba uses wrong magazines

### ISSUE THREAD

**Issue by Best2nd** [acemod/ACE3#614]
ACE3 Version: 3.0.0.

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
nil

**Description:**
Katiba uses MX magazines (30Rnd_65x39_caseless_mag) instead of green ones (30Rnd_65x39_caseless_green)

**Steps to reproduce:**
Place down OPFOR rifleman. Notice his Katiba is unloaded. Now spawn a NATO ammo box and notice you can load MX magazines.

**Where did the issue occur?**
SP editor

**RPT log file:**
nil

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by ulteq** [comment]
Fixed: https://github.com/acemod/ACE3/commit/42dbd8f
