### ISSUE TITLE
ACE 3 Arsenal UI Size Issue

### ISSUE THREAD

**Issue by BSherb** [acemod/ACE3#6146]
**Arma 3 Version:** stable
**CBA Version:** `v3.5` (stable / dev + commit hash)
**ACE3 Version:** `3.12.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Opening Ace Arsenal has an incredibly small UI. I sit roughly 8feet from computer and have no other issues with UI in game. Therefore requires a pair of binoculars attached to a microscope in order to read any of the words in the arsenal. Does not change based on game setting UI scaled.

**Steps to reproduce:**
- Open Arsenal, Look at Screen. (I have a 1360x768 monitor)

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- none

**RPT log file:**
- If absolutely necessary I'll upload if ask.
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard. (Same for this as I'm unsure if this is an already known bug or not. Picture soon to come.)

**Comment by BSherb** [comment]
![image](https://user-images.githubusercontent.com/20545982/36229848-8d4d054c-11a6-11e8-8629-23a046685fea.png)

**Comment by BSherb** [comment]
For scale
![image](https://user-images.githubusercontent.com/20545982/36229962-de5bf272-11a6-11e8-842a-e2b19a5b05f7.png)

**Comment by dedmen** [comment]
First screenshot looks completly normal to me.
You can increase the text size in the Arsenal Settings.

**Comment by BSherb** [comment]
This will work for now. But the UI needs a scalability with the font. Not having enough UI for text and mod icons is a bit silly.
![image](https://user-images.githubusercontent.com/20545982/36266717-296a5b3e-1240-11e8-8b69-c227d0ba4a9e.png)

**Comment by Justice-Molton** [comment]
please stop spamming. more than 200 mails...
