### ISSUE TITLE
ATragMX off slightly. Not sure if user error.

### ISSUE THREAD

**Issue by WreckWolf** [acemod/ACE3#6147]
**Arma 3 Version:** 1.80.143869
**CBA Version:** `3.6.1.180131`
**ACE3 Version:** `3.12.1? It is a custom version, and the readme file says that.`

**Mods:**
```
- CBA_A3
- 43rd ACE (very, very slightly [modified](url) version of ACE)
```

**Description:**
- I have set up the ATragMX, then made the adjustments to my optic that the ATragMX suggests. When I shoot, however, the round lands slightly off every time. 
The first time this happened, yesterday, the round was high and right by about 7 inches at 400m.
The second time, today, the round was left of the target about 6 inches, and above by 4.
The ATragMX settings for today's results are in the image,

**Where did the issue occur?**
- Dedicated Server

**Placed Modules:**
- Not sure, but advanced ballistics IS on.

**Comment by bux** [comment]
Sorry, we can't give support for customized versions.

**Comment by WreckWolf** [comment]
Was about to post those pictures, but yall cant even point me in the right direction if I do? tell me if anything is glaring user error or anything?
![20180215_012347](https://user-images.githubusercontent.com/36498728/36245916-ebcc527a-11f2-11e8-8326-093ef72511cf.jpg)
![20180215_012332](https://user-images.githubusercontent.com/36498728/36245918-ecf8926c-11f2-11e8-8984-7d78028f2eec.jpg)

**Comment by WreckWolf** [comment]
Sorry for low quality. My steam account wont load screenshots for some reason

**Comment by ulteq** [comment]
The ATragMX elevation and windage output in your screenshot it shown in `Clicks` but you want `MILs`.

You should be able to fix that problem by clicking once on `Clicks`.

**Comment by dedmen** [comment]
>ACE3 Version: `3.12.1? It is a custom version, and the readme file says that.`
That doesn't match up with your screenshots.

You entered the G7 coefficient as C1 coefficient in the AtragMX. It doesn't work like that you have to convert it properly.

Looks like it's purely the fault of your "custom version".
