### ISSUE TITLE
No twist on rangecard

### ISSUE THREAD

**Issue by Mikino917** [acemod/ACE3#6153]
**Arma 3 Version:** `1.80`
**CBA Version:** `3.61` (stable / dev + commit hash)
**ACE3 Version:** `3.12` (stable / dev + commit hash)

**Mods:**
```
- Kickass weapons
- CBA_A3
- ace
```
**Description:**
- Hi, I got quite a simple problem. The range card does not show the rifle twist for some KA weapons. Can I ask for help how to find it in game files? 
![image](https://user-images.githubusercontent.com/36592160/36350604-90e24102-149b-11e8-9027-1c5c7a698513.png)

**Comment by dedmen** [comment]
Maybe these KA weapons don't have any rifle twist?

**Comment by terriblephrases** [comment]
dedmen is dead on. I had a look, and the mod just hasn't defined the rifle twist for this weapon.

@Mikino917 Unpbo the .pbo file of the weapon you're interested in, then use the Arma 3 Tools' CfgConvert on config.bin to transform it to text. Under `ACE_barrelLength=800;` you can then add `ACE_barrelTwist = 178;` with whatever twist you think is appropriate, in millimeters. Now just convert the file back to .bin and overwrite the original.

@BaerMitUmlaut I think you can just close this issue. Not a problem with ACE.
