### ISSUE TITLE
feature request/qustion: disable unconscious state for players

### ISSUE THREAD

**Issue by BlackburnUTG** [acemod/ACE3#6158]
So. There is a option to disable unconscious state for AI. But what about players?
how can I disable unconscious state for players without disabling entire ace medicine?

**Comment by PabstMirror** [comment]
Under CBA Setting (Addon Options)
ACE Medical -> AI Unconsciousness: Set to disabled

**Comment by BlackburnUTG** [comment]
but it dissabling only  AI Unconsciousness.
players still have  Unconsciousness state

**Comment by Cuel** [comment]
```
["ace_unconscious", {
    params ["_unit", "_state"];
    if (_unit isEqualTo player && _state) then {player setDamage 1};
}] call CBA_fnc_addEventHandler;
```

**Comment by SilentSpike** [comment]
This seems like something we could add a setting for in the rewrite (hell, we could have a setting to enable/disable each state in the state machine).

**Comment by nk3nny** [comment]
As a workaround it is possible with the current settings to drastically increase player bleedout speed.

**Comment by thojkooi** [comment]
@Cuel provided a solution for the current version of ACE medical.

We will consider this for the medical rewrite project.

**Comment by jonpas** [comment]
This will _not_ be implemented in the rewrite due to the obscurity of the setting.

One can use https://github.com/acemod/ACE3/issues/6158#issuecomment-366906840 if they really want that, but we will not support it in ACE3.
