### ISSUE TITLE
Feature request boarding ladder

### ISSUE THREAD

**Issue by nobilisgkill4** [acemod/ACE3#6161]
**Description:**
Due to the naveral aspekt of Arma 3, it would be great to have an boarding ladder like that: https://s-media-cache-ak0.pinimg.com/originals/a4/df/d1/a4dfd1a1d76e23b3b1dcb7a494ce234e.jpg

Could be like the other ladder from ACE, but it should be attachable to an object (like explosives for example) and deployable from the water. To get it more realistic, an other laddermodel would be great.

Alternative: A rope ladder is used for that as well, but it may be more realistic for scaling purposes and inventory transport. http://kampfschwimmer-association.de/wp-content/uploads/2014/07/Finnen_3.jpg

Optional: It may be cool if it could be deployed from a passenger slot and be used as an "exit" from the vehicle directly on the ladder.

**Comment by dedmen** [comment]
https://github.com/acemod/ACE3/blob/master/.github/CONTRIBUTING.md
>In order to avoid duplicates and keep the issue tracker organized, we have created a common issue for [ACE3 Feature requests](https://github.com/acemod/ACE3/issues/3594).

Please post feature requests in the feature request issue.
