### ISSUE TITLE
ace requires ace_compat_rhs_gref3 Error

### ISSUE THREAD

**Issue by Pouflex** [acemod/ACE3#6166]
Hello, 

Mods 
`CBA
RHS addons
CUP addons
Ares
Task Force Radio
ACE`

I recently have installed the mod ACE3 and its RHS compatibilty mods which I transferred via FileZila .
This the error I get 
![ace3error](https://user-images.githubusercontent.com/15001789/36633139-c6ef3514-1998-11e8-9590-06250c592aac.PNG)

How should I name the two others addons that come with Ace3 mod ?
This how I named them, but it may come from that. 
![ace3](https://user-images.githubusercontent.com/15001789/36633148-e1869354-1998-11e8-936d-53f452bc3190.PNG)

**Comment by dedmen** [comment]
Please use the issue template and provide a full RPT like the issue template tells you to.
That is not an error it's just a warning.

**Comment by PabstMirror** [comment]
I think since 3.12 the file format of the compats has changed slightly
e.g.
`@ace\optionals\@ace_compat_rhs_afrf3\addons\ace_compat_rhs_afrf3.pbo`

to make this work for your folder layout just copy the pbo and bisigns from the 3 compats to your
`@ACE3 Compat\addons` folder so you get

`@ACE3 Compat\addons\ace_compat_rhs_afrf3.pbo`

**Comment by Pouflex** [comment]
Ok, so after thousand of tries, I still get nothing. I did like you suggested, dedmen, I did.
Also did what you said, PabstMirror.
It says the files are outdated, and needs 3.12.1 same as the ACE version. Only these mods download offer me only the 3.8 version in armoholic which is why it doesnt work.
Thanks in advance.

**Comment by commy2** [comment]
Needs full issue template, e.g. proper RPT file.

**Comment by PabstMirror** [comment]
Download the version from github: https://github.com/acemod/ACE3/releases/latest
From that zip file, the compats will be in `@ace\optionals`

**Comment by dedmen** [comment]
>I did like you suggested, dedmen, I did.

Really?
>Please use the issue template and provide a full RPT like the issue template tells you to.

Didn't happen.
>Is that screenshot server or client log?

No answer.
>You have spaces in your mod folder name. Do you escape the -mod parameter correctly?


No answer.

**Comment by iceball117** [comment]
i am to having this issue and can not seem to figure it out. explain exactly what you need from me and i will try to get it. i am learning so lets use stupid words for me.

**Comment by commy2** [comment]
ref #6543
