### ISSUE TITLE
How do I edit the multiplier of damage for the ACE medical module

### ISSUE THREAD

**Issue by KoRaLLL** [acemod/ACE3#6168]
This is less-so an issue and moreso a question

I'm finding that body shots are more efficient than headshots in my current playthrough, and I'm wondering how I would go about reversing these multiplier or something?

I've set the AI damage threshold to 3. It takes 2/3 headshots to kill an AI but only one bodyshot still, so I was wondering if there was a way to reverse it as it seems silly headshots are doing less damage. Thanks!

**Comment by thojkooi** [comment]
If you are still having this question, please join us on [Slack](https://slackin.ace3mod.com/) in the #medical channel.
