### ISSUE TITLE
Barrel can be swapped on weapons with no ace_overheating_allowSwapBarrel entry.

### ISSUE THREAD

**Issue by Drofseh** [acemod/ACE3#6169]
**Arma 3 Version:** `1.80`
**CBA Version:** `3.5.0`
**ACE3 Version:** `3.12.1`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- If a weapon has no ace_overheating_allowSwapBarrel entry then the barrel can be swapped.
- Expected behaviour is to only allow swapping if entry is present and == 1
![](https://i.gyazo.com/7efea4a9c073bce596c3ffa4f64fc10b.png)

**Steps to reproduce:**
- Have a spare barrel
- Have a friend with any weapon that has no ace_overheating_allowSwapBarrel
- Change your friends barrel

**Where did the issue occur?**
- Noticed on Dedicated, tested in Editor (Singleplayer)

**Placed Modules:**
- None

**Comment by dedmen** [comment]
https://github.com/acemod/ACE3/blob/ffaa195fe576625f052eeee04b1af9f3f377434f/addons/overheating/functions/fnc_canSwapBarrel.sqf#L21
getNumber should return 0 though if entry is not present and thus fail that check and exit there.

**Comment by shukari** [comment]
The problem is the && only if it is turned off THEN it check for 0... else if it is enabled then the null check get skipped! Need to be || or im totaly confused?
