### ISSUE TITLE
No text, only icons for interaction menu

### ISSUE THREAD

**Issue by Best2nd** [acemod/ACE3#617]
ACE3 Version: 3.0.0.1-NOGIT

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
nil

**Description:**
https://youtu.be/7x_jRphZKb8
If "use list menu" is disabled there is no text for interaction menu. If "use list menu" is enabled text displays fine.

**Steps to reproduce:**
Set "Display interaction menus as lists" to "No" and use the interaction menu.

**Where did the issue occur?**
SP editor

**RPT log file:**
nil

**Comment by esteldunedain** [comment]
The interact menu requires a dll since yesterday `ace_breakLine.dll`. That isw only used for the radial menu, and not for the list menu. You're surely missing that dll or it's not located on the correct folder.
