### ISSUE TITLE
Imperial units of measure to Kestrel 4500

### ISSUE THREAD

**Issue by mattrhodes11b** [acemod/ACE3#6172]
Units of measure implemented into the kestrel 4500, or a separate one in the game that specifically has wind speed in MPH, barometric pressure in in/hg, temperature in Fahrenheit, altitude and density altitude in feet. Making it much easier to use the ATRAG

**Comment by bux** [comment]
Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: https://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
