### ISSUE TITLE
ace_frag - way too overpowered

### ISSUE THREAD

**Issue by severgun** [acemod/ACE3#6174]
**Arma 3 Version:** `1.80` (stable / rc / dev)
**CBA Version:** `3.5` (stable / dev + commit hash)
**ACE3 Version:** `3.12.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
ace_frag - way too overpowered. It is impossible to throw M67 and be safe at open area. 
WIKI: The M67 can be thrown **30 to 35 metres** by the average male soldier. Steel fragments (not to be confused with shrapnel) are provided by the grenade body and produce an **injury radius of 15 metres** , with a **fatality radius of 5 metres**. Yes, fragments can travel much more than 15m but not every time and they should not deal so much damage.

**Steps to reproduce:**
Throw M67 grenade at open area and don't take cover. Get hit almost 100% chance at 40m throw

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- None

Frags did not hit or flyby near camera even on failed throw
https://www.youtube.com/watch?v=VkyLGHpys68
https://www.youtube.com/watch?v=FXPeWdmazPI

**Comment by severgun** [comment]
Seems like dispersion of self-guided fragments should be increased

**Comment by severgun** [comment]
May be it was during development as idea. But in current release self-guided fragments is here to kill or injure units and not to scare them.
 Now they are shooting like 'snipers' at 30m-40m you have really big chance to get hit. 
All user manuals for hand grenades say that radius of injure hit is 15-20m.
So at 15m it should hit units with 90-100% chance but at 30-40m chance should be much less.
Because there is single fragmets and not wall of them flying towards units I call this dispersion, not density.
```#define FRAG_VEC_VAR 0.004```
I think this one should be tuned may be to 0.01 or even more(need testing with debug tracers)

**Comment by commy2** [comment]
>But in current release self-guided fragments is here to kill or injure units and not to scare them.

Where did you got this from? And how would a shrapnel not headed towards a unit injure the unit?

**Comment by severgun** [comment]
> Where did you got this from?

Enabled debug tracers, logic and slack chat.

> And how would a shrapnel not headed towards a unit injure the unit?

I'm not talking about projectiles not heading to unit. This solution is good. But they are too accurate at long range.
Effective range of regular grenade 15-20m.

Let's do some math.
Grenade have 210 gramm metal shell. 2+gramm frags are actually capable to really injure.
So let's say that all 210g split into equal 2 gramm fragments(of course it will not). We have 105 fragments flying away as sphere.

Surface area of a sphere with radius **20m** is (S = 4πR^2) 5026.548m2
105/5026.548 = **0.020 frags per m2**
Man profile avg. 1.8m*0.5m = 0.9m2
**0.01872 frags per 0.9m2**
So **1.8%** chance to get frag in standing man profile. At 20m.

At 50m - (105/(4*pi*50^2))*0.9 = **0.3%**
Now I got ~70%...

Correct me if my thoughts are wrong.

> What you want is to decrease the density, the number of frags alltogether.

Density of 1 fragment?
Every unit(50 units is the coded limit?) have 1 frag flying into his body. If you turn on debug tracers and throw 10 grenades you will see "cone" of 10 red lines going towards you. Cone is pretty narrow. I think that if increase dispersion of this projectiles, cone will be wider. And because there is one frag at a time, there will be more chance that it will miss your body profile at long range.
https://imgur.com/a/nuqvR
0 hits on second image. Still lethal at 10m

IMHO Grenades should hit ~100% with 5m. and ~1% with 30m. That is what I'm asking about.
Name it how you like it.

**Comment by severgun** [comment]
Frags needs total rewrite... 👎 
https://imgur.com/WpPcB8I

**Comment by dedmen** [comment]
You mean like https://github.com/dedmen/ACE3/commits/InterceptFrag ? :D 
Yes we already know it does.

**Comment by jonpas** [comment]
You only see actually simulated fragments, there are others, we just don't simulate them for performance reasons, nothing is there, so no one cares if something goes there.

**Comment by severgun** [comment]
> You only see actually simulated fragments, there are others

is there a way to see them for debug?

I just want to show that now if behind your back there is group of people in radius **480m!**(insane for grenade) you will be ripped in parts by shrapnel. When, as i calc earlier, there should be 0.02 framents per m2 at 20m and even less at 30m.

**Comment by jonpas** [comment]
No, they are not simulated at all, basically imagine them. I am not saying dispersion/amount overall is correct, just that you have to take into account that only those in path towards objects are calculated.

**Comment by SilentSpike** [comment]
@severgun I haven't looked at the code myself, but if I understand right the fragments aren't "selfguided", the physics calculations are all being done normally and then only the fragments that are heading toward targets actually get created

@jonpas can confirm if I've got that right

**Comment by jonpas** [comment]
Yeah, well described @SilentSpike 👍
