### ISSUE TITLE
REARM_ACTION_DISTANCE REARM_ACTION_DISTANCE_SQR default values are too low.

### ISSUE THREAD

**Issue by severgun** [acemod/ACE3#6177]
**Arma 3 Version:** `1.80` (stable / rc / dev)
**CBA Version:** `3.5` (stable / dev + commit hash)
**ACE3 Version:** `3.12.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
ace_rearm not working on big vehicles due to small default values of
```
#define REARM_ACTION_DISTANCE 7
#define REARM_ACTION_DISTANCE_SQR 49
```
For example VTOL V-44. You can't get closer than ~8 and ~64.

**Steps to reproduce:**
Place empty V-44 gunship. Try to rearm.

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- None

**Comment by jokoho48** [comment]
when you want to have REARM_ACTION_DISTANCE at 8 then REARM_ACTION_DISTANCE_SQR must be the square of that...

**Comment by severgun** [comment]
@jokoho48 I got it. Symbol ~ means 'approximately'.
Let me just show.
https://i.imgur.com/9VLK0LV.jpg
Point not in actual numbers, but in that I can't reach them.

**Comment by jonpas** [comment]
Should be changed to use the common functions that return distance based on vehicle size.

**Comment by commy2** [comment]
I'm personally a fan of sizeOf:
```sqf
sizeOf typeOf _vehicle
```

**Comment by PabstMirror** [comment]
Will look into swapping to `ace_interaction_fnc_getInteractionDistance`
