### ISSUE TITLE
Launcher Buddy Reload Delay

### ISSUE THREAD

**Issue by 111Insats** [acemod/ACE3#6179]
**Arma 3 Version:** `1.80.143869`
**CBA Version:** `3.6.1.180131`
**ACE3 Version:** `3.12.1.31` 

**Mods:**
```
- CBA_A3
- ace
- (Optional) RHS:USAF
- (Optional) RHS:USAF ACE Compatibility
```

**Description:**
- The buddy reload for launchers takes far too long for it to be effective, after having completed the ACE Interaction action, there is still a significant delay before the launcher can be fired.

**Steps to reproduce:**
- Requires two people.
- One man with an empty launcher, one with ammunition for said launcher.
- Loader reloads the launcher for the gunner via ACE Interaction.
- Long delay between progress bar completion and when launcher can fire.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**Placed Modules:**
- Default.

**RPT log file:**
- No RPT available.

**Comment by dedmen** [comment]
Duplicate https://github.com/acemod/ACE3/issues/5813
