### ISSUE TITLE
Game freeze upon opening interaction menus

### ISSUE THREAD

**Issue by 111Insats** [acemod/ACE3#6182]
**Arma 3 Version:** `1.80.143869` (stable)
**CBA Version:** `3.6.1.180131` (stable)
**ACE3 Version:** `3.12.1.31` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Arma 3 freezes up for anywhere between 2-10 minutes when trying to open either self-interaction or interaction menu.

**Steps to reproduce:**
- Go into Virtual Arsenal.
- Try to open any of the interaction menus.

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Virtual Arsenal

**Placed Modules:**
- Default.

**RPT log file:**
- [RPT](https://gist.github.com/111Insats/0295e95d2af18596f8f8ab2bac98f26a)

**Comment by dedmen** [comment]
This calls for my script profiler. If it's a unscheduled script going crazy it would show that.. Sadly it's broken-ish currently.

You are running `3.12.1.31` Where does that come from? Current version is `3.12.1`.
At what timestamp in your RPT did the freeze happen?
I'm guessing `9:59:58` ?

**Comment by 111Insats** [comment]
@dedmen Always reproductible. The version numbers are from the main menu in Arma 3. Timestamp is unknown, but it occured twice (once for interaction, once for self-interaction). Looks like it froze the timestamps as well.

**Comment by BaerMitUmlaut** [comment]
Closing as requested.
Could imagine this was an increased loading time for an image maybe? Is your hard drive alright?

**Comment by jonpas** [comment]
@dedmen that's a build number, and is correct.

**Comment by 111Insats** [comment]
@BaerMitUmlaut Hah, likely not, it's from 2010 and has had to be revived twice already. It may have been an increased loading time for an image, considering the mouse cursor was always okay and could move around perfectly fine, but the rest of the game froze up.
