### ISSUE TITLE
AAA Airburst rounds useless without radar target tracking/ranging

### ISSUE THREAD

**Issue by thecuban** [acemod/ACE3#6185]
**Description:**
- Airburst rounds explode at the zeroed distance for the gun. Zeroing the gun on a dynamically moving aircraft that is evading ground fire and engaging targets is next to impossible and unrealistic. Modern AAA use fire control radar that lock onto a target and continuously adjust zeroing and burst distance on the fly while the gunner engages the target. All the gunner should have to do is radar lock the target and fire with cross hairs directly on target, the FCS should handle everything else (especially burst distance calculations on airburst rounds).

**Steps to reproduce:**
- Place AAA
-Shoot at something that flies
-*miss*

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by bux** [comment]
It's very usefull when engaging ground targets.

What you're writing here is a feature request and should go to the appropriate issue. That's why I'm closing it.
