### ISSUE TITLE
sqf_validator.py fails on remoteExec variant

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#6186]
The `sqf_validator.py` script fails when encountering a certain variant of `remoteExec`.

https://community.bistudio.com/wiki/remoteExec#Examples
Example 8
`{player setAmmo [primaryWeapon player, 1];} remoteExec ["bis_fnc_call", 0];`

When validating this will throw the following error:
`ERROR: Possible missing semi-column ';' detected` (_also note the typo -> semicolon_)

**Comment by commy2** [comment]
Why not put two newlines? It would look better  thaz way.

**Comment by bux** [comment]
It doesn't matter to the validator.
