### ISSUE TITLE
ACE Switch units not working

### ISSUE THREAD

**Issue by Bummeri** [acemod/ACE3#6188]
**Arma 3 Version:** latest stable
**CBA Version:** v3.6.1.180131
**ACE3 Version:** `Version 3.12.1

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Ace switch units is not working. When I change the ace switch unit settings from the new menu, there is some scripterror shown. Also the units cannot be switched to.

**Steps to reproduce:**
- Add units on map
- add `this setVariable ["ACE_CanSwitchUnits", true];` to units you want to switch to
- Change ACE settings to enable switch units and disable range setting
- Start mission  and try to change units via the map by clicking on them

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
https://pastebin.com/5pyHU4vc Shows the script errors in the end.

**Comment by commy2** [comment]
From the [CBA changelog](https://github.com/CBATeam/CBA_A3/releases)
>There is a script error popup when saving mission settings in the editor. The settings are saved correctly and the error message can be ignored. See: https://feedback.bistudio.com/T127247

**Comment by Bummeri** [comment]
Also the whole functionality is not working. I cannot switch to the units as per this instruction:
https://ace3mod.com/wiki/feature/switchunits.html#21-switching-to-a-unit

**Comment by Bummeri** [comment]
Can someone else repro this or am I doing something wrong?

**Comment by Uberpanik** [comment]
@Bummeri  I did manage to reproduce it. In my case it didn't show script errors as CBA bug apparently had been fixed, but the situation was the same.
After tinkering with ace_switchunits.pbo I think problem is revolved around handling map clicks or AI validation. However due my limited programming skills take this assumption with a pinch of salt

**Comment by dedmen** [comment]
issue needs bug label.
