### ISSUE TITLE
Is possible to change damage taken in ace 3?

### ISSUE THREAD

**Issue by x4NickU** [acemod/ACE3#6189]
Anyone know if is possible to change the damage take by shot(or general) in ace 3?
With a 9mm pistol if i shot 1 time to a person he go down(without vest and everywhere), is possible to set 2 or 3 shot?

**Comment by Whigital** [comment]
The quick and dirty way is to change the damage multipliers in the medical settings (`playerDamageThreshold` and/or `AIDamageThreshold`).

**Comment by BaerMitUmlaut** [comment]
I assume this has been a sufficient answer?
