### ISSUE TITLE
Stop using audibleFire for hearing

### ISSUE THREAD

**Issue by KoffeinFlummi** [acemod/ACE3#619]
To prevent AI mods and shitty Arma 2 ports from breaking hearing, use some kind of cocktail of `CfgAmmo` parameters to determine the volume of a shot instead of `audibleFire`.

This is probably a case for our master of graphs, correlations and also Star Trek. Setting as 3.0.0 for now, can probably be moved back if desired.

**Comment by esteldunedain** [comment]
I have a rough correlation for projectiles inheriting from bulletBase, but I want to expand it to other projectile types. I'll try to get it in for 3.0.0, but no promises yet

**Comment by commy2** [comment]
Please take a look at combat deafness from ACE2 when you rewrite what we have.

**Comment by OnkelDisMaster** [comment]
Would appreciate that! audibleFire is also set by ASR AI, so this would grant compatiblilty with it

**Comment by esteldunedain** [comment]
I'd propose pushing this to 3.1.0 and working on integrating the better ACE2 system.

**Comment by bux578** [comment]
> I'd propose pushing this to 3.1.0 and working on integrating the better ACE2 system.

:+1:

**Comment by ViperMaul** [comment]
Moving this to the next milestone based on Dev recommendations.
