### ISSUE TITLE
change rear tire of typhoon is impossible

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#6196]
**Arma 3 Version:1.80 `` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- chaging rear tire of the typhoon (truck) is not possible.

**Steps to reproduce:**
- place typhoon on map, destroy the rear tire (3rd axis) and try to change the tire.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None.

**Comment by severgun** [comment]
May be because of this one?
https://github.com/acemod/ACE3/issues/6177

**Comment by Dystopian** [comment]
can't repro in SP editor and dedicated
![3](https://user-images.githubusercontent.com/3867143/37623469-dc827fd6-2bd5-11e8-8139-59dafbe2f0f9.jpg)

**Comment by madpat3** [comment]
it does the animation and the progressbar, but in the end, there is no new tire.

**Comment by Dystopian** [comment]
I'll take it
