### ISSUE TITLE
Arsenal: Camera jumps to sea surface when editing units under water.

### ISSUE THREAD

**Issue by xrufix** [acemod/ACE3#6197]
**Arma 3 Version:** 1.80.143869, Stable
**CBA Version:** 3.6.1.180131
**ACE3 Version:** 3.12.1.31

**Mods:**
```
- CBA_A3
- ace
- some others irrelevant to ace arsenal
```

**Description:**
- When you edit a unit's loadout under water, moving the camera with the mouse moves the camera to sea surface. moving it under sea surface is impossible.

**Steps to reproduce:**
- Place infantry unit in 3den
- move under water surface
- edit loadout
- left-click-and-drag
- see sea surface.

**Where did the issue occur?**
- 3den Editor (SP)

**Placed Modules:**
- n.a.

**RPT log file:**
- will provide if needed.

**Comment by bux** [comment]
@alganthe

**Comment by alganthe** [comment]
I have a general idea of what's causing it, will investiguate.

**Comment by alganthe** [comment]
Fixed by allowing the camera to clip through rocks and other surfaces that aren't the terrain, that fixes the issue.
Fixed in #6192
