### ISSUE TITLE
Titan AA requires AT locking and shouldn't

### ISSUE THREAD

**Issue by Arkblade2015** [acemod/ACE3#620]
Mods:

    @cba_a3
    @ace3

Placed ACE3 Modules:
ace_javelin
ace_missileguidance

Description:
launchers can't fire except titan AT/AP

Steps to reproduce:
none

Where did the issue occur?
"Singleplayer"*

**Comment by rlex** [comment]
looks like dupe of #603

**Comment by Arkblade2015** [comment]
titan AA, RPG32, others....

**Comment by jaynus** [comment]
No repro in latest master on any launchers except the Titan AA. The Titan AA is a wierd case, because its all the exact same shit and it really shouldn't be.  

Renaming ticket to figure out some mythical air locking method to use for this.

**Comment by Arkblade2015** [comment]
i also No repro in latest master on any launchers except the Titan AA.
thank you.
