### ISSUE TITLE
Missing ace_server.pbo file

### ISSUE THREAD

**Issue by Fadderson** [acemod/ACE3#6210]
Hey guys,

the ace_server.pbo file should be located in "@ace\optionals" according to: https://ace3mod.com/wiki/framework/settings-framework.html#using-the-exported-settings-in-the-mission-descriptionext. 

Somehow, I am missing the ace_server.pbo. I did not move it. I even re-downloaded Ace3 3.12.1, but the file doesnt seem to be there.

Does anyone know why this could happen?

**Comment by PabstMirror** [comment]
It's been removed, we switched to cba settings in 3.12

**Comment by bux** [comment]
@Fadderson Did you miss the red box on top?
![asd](https://i.imgur.com/6fTEZkF.jpg)
