### ISSUE TITLE
Ace Medical PAK Restrictions

### ISSUE THREAD

**Issue by KyleGas** [acemod/ACE3#6216]
Hello.

Is there a way to restrict paks to use one wounded units who are not only awake but also have a normal pulse, bloodpreasure and are not bleeding? I can only find restrictions as in: PAKs are used up or can only be used in medical vehicles/facilities.

Thanks for help

**Comment by Drofseh** [comment]
![](https://i.gyazo.com/b0a30929819f8534c31f1847ac3f231b.png)

`Condition PAK` is what you want, near the bottom of the medical settings.

**Comment by KyleGas** [comment]
Hm, i tried that and it still just healed up everything when the soldier was kicking... with low blood preasure and low heart rate.... just what is considered stable? i couldnt find it on the medical documentation (hope im not blind)

**Comment by BaerMitUmlaut** [comment]
Stable = not bleeding.
What's the point of a PAK if the soldier is absolutely fine?

**Comment by Drofseh** [comment]
> What's the point of a PAK if the soldier is absolutely fine?
If you have `healHitPointAfterAdvBandage` turned off then a PAK is the only way to remove the limp/walk condition, even if HR and BP are normal, blood level is good, and all wounds are bandaged and stiched.
