### ISSUE TITLE
CSAT Viper operatives do not get injuired when shot in limbs (legs, arms)

### ISSUE THREAD

**Issue by ramblasos** [acemod/ACE3#6221]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- CSAT Viper operatives do not get injuired when shot in limbs (legs, arms)

**Steps to reproduce:**
- [video link](https://youtu.be/AwBq0IcwzmU)

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- 'None'

**RPT log file:**
- [RPT file](https://pastebin.com/WaM77c36)
- [ACE Debug](https://pastebin.com/7qWLSP9g)

**Comment by bux** [comment]
Your RPT file is incomplete. Please disable the `-noLogs` parameter.

**Comment by ramblasos** [comment]
Oops.. Updated the report with full RPT file.

**Comment by ramblasos** [comment]
I did some further testing with `ACE3 3.12.2` and `CBA 3.7.0`. And I noticed that if you execute `getAllHitPointsDamage` on Viper and non-Viper units you will get different results.

```
O_V_Soldier_ghex_F
[["hitface","hitneck","hithead","hitpelvis","hitabdomen","hitdiaphragm","hitchest","hitbody","hitarms","hithands","hitlegs","incapacitated"],["face_hub","neck","head","pelvis","spine1","spine2","spine3","body","arms","hands","legs","body"],[0,0,0,0,0,0,0,0,0,0,0,0]]
```

```
O_T_Soldier_AR_F
[["hitface","hitneck","hithead","hitpelvis","hitabdomen","hitdiaphragm","hitchest","hitbody","hitarms","hithands","hitlegs","incapacitated","hitleftarm","hitrightarm","hitleftleg","hitrightleg"],["face_hub","neck","head","pelvis","spine1","spine2","spine3","body","arms","hands","legs","body","hand_l","hand_r","leg_l","leg_r"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]
```

However I also noticed that if a non-Viper unit wears a Viper uniform his limbs become invulnerable. 

Hope this helps to single out the problem.

**Comment by commy2** [comment]
They need configs like this: https://github.com/acemod/ACE3/blob/master/addons/medical/CfgVehicles.hpp#L620-L624
