### ISSUE TITLE
ace3 slow moving vehicle help

### ISSUE THREAD

**Issue by blackrhino121** [acemod/ACE3#6225]
**Arma 3 Version:** `1.80` (stable / rc / dev)
**CBA Version:** `3.6.1` (stable / dev + commit hash)
**ACE3 Version:** ` 3.12.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
problem is vehicles barely move they dont even go 1km/h wont even turn.

**Steps to reproduce:**
loaded ace3 fresh and now am having slow vehicles that dont move
**Where did the issue occur?**
- Dedicated 
**Placed Modules:**
no

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

https://pastebin.com/w6a9kjXk

- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by PabstMirror** [comment]
Doesn't look like you are running ace or cba in that rpt.

```
 7:51:30 B_Truck_01_medical_F: pedal_brake - unknown animation source brake
 7:51:30 unable to connect anim. source "Hit" to hitpoint "HitLFWheel" in B_Truck_01_medical_F
```
Since you are just running vanilla arma, these errors don't make any sense.
I would verify game files in steam; see https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335

**Comment by blackrhino121** [comment]
will do will check into the dedicated machine

**Comment by blackrhino121** [comment]
i know i have mods installed..maybe not right though i put both cba and ace in the root folder and also in the documents arma folder

**Comment by dedmen** [comment]
The server RPT won't help us much with your clientside problems. Please upload the client RPT.
