### ISSUE TITLE
"Unconscious" interpolation to "ACE_UnconsciousOutProne" causes unexpected animation behaviors

### ISSUE THREAD

**Issue by derbismarck** [acemod/ACE3#6227]
**Arma 3 Version:** `1.80`
**CBA Version:** `3.6.1`
**ACE3 Version:** `medical-rewrite` (state of the branch, as of https://github.com/acemod/ACE3/commit/306c4499864e7d4de283f8a0555419743f9b9f1e)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Currently, the method used at https://github.com/acemod/ACE3/blob/medical-rewrite/addons/medical_engine/CfgMoves.hpp#L16 which interpolates the `Unconscious` animation to `ACE_UnconsciousOutProne` is flawed. This implementation results in, for one example, players being thrown to the ground when leaving a ladder.

**Steps to reproduce:**
- On the `medical-rewrite` branch, climb onto a ladder and then get off of it. You will transition into prone (`ACE_UnconsciousOutProne`) unexpectedly. If you edit the aforementioned line back to the default: `InterpolateTo[] = {"DeadState",0.1};` you'll note that the issue with diving to prone upon leaving ladders is no longer present. I have personally been able to find a few other animations that result in an unexpected/undesired transition to `ACE_UnconsciousOutProne`, but this one with ladders is by far the most impactful to gameplay.

**Where did the issue occur?**
- N/A, all environments

**Placed Modules:**
- N/A

**RPT log file:**
- N/A

**Comment by commy2** [comment]
`LadderCivilDownOff`, `LadderCivilTopOff`, `LadderRifleDownOff`, `LadderRifleTopOff`
