### ISSUE TITLE
Generate presets for the AtragMx is there a function do do that?

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [acemod/ACE3#6228]
Some mods (like RHSUSAF) have weapons that are properly configured for ace advanced ballistics, however they have no class ACE_ATragMX_Presets as shown here: https://ace3mod.com/wiki/framework/atragmx.html
Is there a function available to generate the presets? A workaround other than to manually add the presets using the range card?

**Comment by Laid3acK** [comment]
> Is there a function available to generate the presets?

Automatically you mean ? Actually no, as far as i know.
I'm afraid that you have to do it manually according with the AtragMx framework.

With RHS, all Advanced Ballistic entries are a copy/past from the ACE3 entries.
I think that it should be relatively easy to make your own AtragMx presets from the [AtragMx initGunList](https://github.com/acemod/ACE3/blob/master/addons/atragmx/functions/fnc_initGunList.sqf).

(not relevant with AB enabled but just take care about the `airFriction` : RHS airFriction used in-game)

**Comment by MisterHLunaticwraith** [comment]
I have started writing my own function to do that, it browses the config files to find all the intel but some data I don't know where to retrieve:
`class yourTestPreset1 {
        // Profile Name, Muzzle Velocity, Zero Range, Scope Base Angle, AirFriction, Bore Height, Scope Unit, Scope Click Unit, Scope Click Number, Maximum Elevation, Dialed Elevation, Dialed Windage, Mass, Bullet Diameter, Rifle Twist, BC, Drag Model, Atmosphere Model, Muzzle Velocity vs. Temperature Interpolation, C1 Ballistic Coefficient vs. Distance Interpolation
        preset[] = {"testPreset1", 810, 100, 0.0679, -0.0010350, 3.81, 0, 2, 10, 120, 0, 0, 9.525, 7.82, 25.40, 0.393, 1, "ICAO", {{-15,0},{0,0},{10,0},{15,0},{25,0},{30,0},{35,0}}, {{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}}};`

Where will I find: scope unit, scope click unit, scope click numerber, max elevation, dialed elevation and dialed windage?

What is BC? and where will I find it?

I can get the Muzzle Velocities array and the temperature interpolation, but is there a function to calculate "Muzzle Velocity vs. Temperature Interpolation"? 

Same question for "C1 Ballistic Coefficient vs. Distance Interpolation"?

The rest I have found/ figured out on my own.

**Comment by dedmen** [comment]
>Where will I find: scope unit, scope click unit, scope click numerber, max elevation, dialed elevation and dialed windage?

First 4 in the Scopes config. Aka CfgWeapons
