### ISSUE TITLE
PAK & Surgical Kit not working in Advanced mode

### ISSUE THREAD

**Issue by colormeblind23** [acemod/ACE3#6233]
**Arma 3 Version:** `1.80.14` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Cannot use PAK or Surgical Kit at all I have tried for the last 16 hours to fix this issue. I even used the 2d editor to create a mission and add cba_settings.sqf to the mission to try to override any conflicting settings to NO avail. PLEASE help me out guys my unit wants to use Ace3 Advanced Medical settings but without the PAK or Surgical kit we can't do a full heal. I will try to be as thorough as possible; I have created a plain ace3 mission and used the default settings without advanced on, that works. I used the same mission to turn on advanced medical settings, it still works except for using PAK or Surgical kit, I made sure to have a medic with the setting to have them recognized as a medic by double clicking on them and clicking the little checkbox in the ace settings "is a medic". I also made a medical facility and medical vehicle both empty, both with the same "is a medical facility/vehicle" respectively. Even with all that I did and tried to do to get the settings to allow use of PAK or surgical kit it WILL NOT allow it. I saw there was some script errors during the creation process but I wasn't able to find them in any logs and they don't stay on screen long enough to write them down. Screenshotting doesn't seem to help either since my screenshot folder is buried by steam. I apologize if this is a duplicate I did a search for this issue and didn't find any from searching through the issue tracker.

**Steps to reproduce:**
Create a ace3 altis mission, save it, place a medic, place a medical vehicle, place a medical facility, set all to be recognized by ace3 that they are treated as medics/medical vehicles/medical facilities respectively. Injure yourself or someone else (PC not AI) and then heal them up. When it comes time to use the PAK or Surgical Kit on the torso it will not allow it.

**Where did the issue occur?**
- Dedicated  / Editor (Singleplayer)

**Placed Modules:**
None

**RPT log file:**
https://pastebin.com/XdyqvGCN

**Comment by colormeblind23** [comment]
New development, same plain ace3 mission will no longer allow advanced medical system to work. The settings are all correctly set too. Advanced is completely disabled now even when I create a brand new mission and place all the necessary items/vehicles/buildings. I've taken steps already to make sure its not on my end. Full re-install of arma 3 and ace 3 and cba and it still has no effect, ace3 advanced medical still won't work.

**Comment by BaerMitUmlaut** [comment]
Please upload the mission you made.

**Comment by colormeblind23** [comment]
Feel free to close this, forgot to come back and say it was just a bug on my end. For some reason it was running the server in some sort of debug mode which apparently breaks certain mod features. Not entirely sure why it happened or what checkbox I forgot to tick but it seems to work when it feels like it now
