### ISSUE TITLE
Simplified Zeroing in Ace Scopes causes pistol calibers to be zeroed incorrectly

### ISSUE THREAD

**Issue by mikeisbad2** [acemod/ACE3#6236]
**Arma 3 Version**: 1.80.14 (stable)
**CBA Version:** 3.6.1 (stable)
**ACE3 Version:** 3.12.1 (stable)

**Mods:**
```
- CBA_A3
- ace
-RHS, etc. any mod with .45 ACP or 9mm weapons
```

**Description:**
- When using a .45 ACP or 9mm pistol or SMG with ironsights or any optic, zeroing becomes incredibly inaccurate, with bullets often landing around 500m when zeroed for 100m. Only occurs when Simplified Zeroing is enabled.

**Steps to reproduce:**
- Go into the virtual arsenal or any scenario with simplified zeroing enabled and fire a .45 or 9mm weapon.

**Where did the issue occur?**
- Self-Hosted Multiplayer / Virtual Arsenal

**Placed Modules:**
- None

IMAGES
One shot of an FNX-45 without Simplified Zeroing at 100m Target
![withoutsz](https://user-images.githubusercontent.com/38191709/38472165-ed4e206e-3b38-11e8-97e2-760920ab3936.jpg)
One shot of an FNX-45 with Simplified Zeroing at 100m Target
![withsz](https://user-images.githubusercontent.com/38191709/38472166-f0803b1e-3b38-11e8-90bd-5d558ab388b1.jpg)

Edit:Added Arma 3 and CBA version

**Comment by BaerMitUmlaut** [comment]
Duplicate and already fixed (#6126).
