### ISSUE TITLE
helicopter airdrop bugs out of the world

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#6237]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
- rhsusaf
- ares
```

**Description:**
- drop a container out of a helicopter and look how it goes to the ground
- Video: https://youtu.be/0ADEBPhaOS0
- Information: also my own script airdrop bugs out of the world.... so i suppose in the last update something changed!

**Steps to reproduce:**
- heli with cargo
- drop while in the air
- follow the cargo
- the cargo goes in the ground

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by shukari** [comment]
Yes this was only for the video... was the hole time in the last mission from bigger height on another map

**Comment by shukari** [comment]
i suppose the problem is this line https://github.com/acemod/ACE3/blob/845f3656d4c877d5b054f37330479d5237ccff1b/addons/cargo/functions/fnc_paradropItem.sqf#L68

Because it will add the item 1m below the parachute.... that is the distance in the ground if its on the ground.... i use +1 as value there....

**Comment by Dystopian** [comment]
looks similar to problem with dead body weapon dropping which I have to make a [workaround](https://github.com/acemod/ACE3/pull/6029/files#diff-217c5f71b8b8063398658b5e5aff7a26R75) for
