### ISSUE TITLE
Units inside armored vehicles take no damage at all

### ISSUE THREAD

**Issue by Boersencrash321** [acemod/ACE3#6245]
**Arma 3 Version:** `stable`
**CBA Version:** `stable`
**ACE3 Version:** `stable`

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
Players and npc's in armored vehicles take no damage when being shot at by AP rockets of any kind.
This happens also to light armored vehicles like the Karatel. It is possible to completely destroy the vehicles (except for the final explosion) and every person inside is still alive and unharmed. 
In unarmored vehicles the persons instantly die as intended.
In addition to that, any rifle can kill the units inside easily if shot at.

**Steps to reproduce:**
- Get a Karatel and 2 players, one armed with a RPG7
- One player entes the vehicle as driver, the other shoots at the front window
- The vehicle gets destroyed and the player inside is still alive

**Where did the issue occur?**
- Dedicated MP server

**Placed Modules:**
- Ace Debug with settings: https://pastebin.com/puz94BsH , nothing else placed

**Comment by Armilio** [comment]
I can confirm that this issue exist. Injuring/killing the crew it's a big part of the 1.82 update. The same shot that makes ~0.50 damage to the crewmen without ACE, with ACE seems deal no damage. 

Maybe it's related to the vehicle surfaces armor.bisurf or armor_x.bisurf that when are hit deal damage to the crew, i readed something about that in the dev branch forum topic, it can be that it's handled badly by the ACE_medical handleDamage, like if you try to use setdamage 0.5 with ACE_medical has no effect on the bodyparts, but i'm just guessing.

**Comment by Boersencrash321** [comment]
This issue gets worse when the cookoff system is enabled. Not only are units in vehicles invincible, the vehicle iself sometimes doesn't take damage beyond a certain threshold. 
In practise that means that you can shoot >10 HEAT rockets at a tank and it is sometimes still able to turn the turret towards you and shoot back.

**Comment by SilentSpike** [comment]
We would advise to disable cookoff for the time being, it needs to be reworked to work with the new armour system BI implemented

**Comment by dedmen** [comment]
Should be labeled as bug to prevent the bot from closing unfixed issues.
