### ISSUE TITLE
AI Mortars break on advanced ammo handling

### ISSUE THREAD

**Issue by Neciota** [acemod/ACE3#6249]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ACE3
- ACE3_optionals
```

**Description:**
- When turning advanced ammo handling on in the Mk6 options it says in the tooltip that this should not affect AI mortars but it does; it removes the ammo. 

**Steps to reproduce:**
- Place player unit in the editor.
- Place an AI mortar of the same side next to it.
- Give the AI a fire mission waypoint. 
- Hit play, the AI will fire.

Now do the same but also turn on advanced ammo handling; the AI will not fire.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- [rpt](https://pastebin.com/z2gdRTKg).
- [debug](https://pastebin.com/yDyCKahs)

**Comment by BaerMitUmlaut** [comment]
Duplicate #6173
