### ISSUE TITLE
ACE3 & Achilles: Ensure a Consistent Modification of Vanilla Modules

### ISSUE THREAD

**Issue by oOKexOo** [acemod/ACE3#6253]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.1` (stable)
**Achilles:** `1.0.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- Achilles
```

**Description:**
- ACE3 as well as Achilles are modifying the same vanilla modules in a few cases. This is a review thread to discuss changes in both mods in order to ensure a consistent behaviour of these modules with and without the other mod.

**Affected Modules (incomplete)**:
- [ ] `ModuleMine_F`
- [ ] `ModuleRemoteControl_f`
- [x] `ModuleArsenal_F` (possibly affected in future)

**Links to Relevant Folders**:
- ACE3: 
    - [ACE3/addons/zeus](https://github.com/acemod/ACE3/tree/master/addons/zeus)
- Achilles: 
    - [Achilles/@AresModAchillesExpansion/addons/modules_f_achilles/Replacement](https://github.com/ArmaAchilles/Achilles/tree/master/%40AresModAchillesExpansion/addons/modules_f_achilles/Replacement)

**Cross Reference:**
- [ArmaAchilles/Achilles/#291](https://github.com/ArmaAchilles/Achilles/issues/291)

**Comment by BaerMitUmlaut** [comment]
Which ones?

**Comment by oOKexOo** [comment]
I havent looked into it in detail yet, but `ModuleMine_F` comes me to mind.

**Comment by oOKexOo** [comment]
Well, in both instances we got requests to get rid of it.
This would mean to get it consistent (independent of the order the addons are loaded), the code for Achilles should check for the ACE settings such that it has the same behaviour.

**Comment by oOKexOo** [comment]
Regarding the arsenal we are not yet sure what to do. There is on the one hand the arsenal module, which is currently only modified by ACE and there is the attribute window button provided by Achilles. While the former only uses ACE arsenal, the latter only uses vanilla arsenal. The thing is that we realized that our users prefer to have vanilla as well as ACE arsenal at their disposal. It would be better to have the same approach for both the module as well as the button.

**Comment by alganthe** [comment]
^ use the current master branch instead of stable, or the 3.12.2 RC, i've split up the arsenal module for BI VA and ACE Arsenal.

**Comment by oOKexOo** [comment]
Good, so there will be no problem with the Arsenal module.

**Comment by PabstMirror** [comment]
If we don't want to worry about mod load order or seperate compats then I think the best solution would be to write a standard function that does what we both want it to do. And then have both mods just set the function to that.

something like 
```
// bis code
if (isClass (configFile >> "cfgPatches" >> "ace_zeus") then {
 // ace code
};
if (isClass (configFile >> "cfgPatches" >> "achilies") then {
 // ares code
};
```
Can also use ace settings that may not exist safely with stuff like `getVarriable ["ace_setting_x", false]`

Are there any conflicts in the changes that we both make?

**Comment by bux** [comment]
> hell, at that point why not make an api and add it to CBA^?

agreed

**Comment by oOKexOo** [comment]
No longer relevant as Achilles is deprecated.
