### ISSUE TITLE
ACE Hellfires No longer Usable.

### ISSUE THREAD

**Issue by Twelvecaliber** [acemod/ACE3#6256]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.6.1` (stable )
**ACE3 Version:** `3.12.1` (stable )

**Mods:**
```
- CBA_A3
- ace
-RHS
-CUP Terrains
```

**Description:**
- ACE Hellfires are no longer selectable as a weapon post Tanks DLC. They can still be equip via the pylons menu and equip to the aircraft, however when you get in the position that should have access to them you cannot switch to them. Affects both vanilla and addon vehicles.

**Steps to reproduce:**
- Place NATO pawnee and equip with ACE AGM-114K/N
- Try to select AGM from either the pilot or co-pilot seats.

**Where did the issue occur?**
- Everywhere.

**Comment by tbeswick96** [comment]
Can confirm experiencing the same
