### ISSUE TITLE
ACE arsenal : player identity overwrites Goggles

### ISSUE THREAD

**Issue by Sparfell** [acemod/ACE3#6258]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
When you create player (player or playable) loadouts with ace arsenal in 3DEN, the selected goggles will be overwritten by player identity at mission launch. In singleplayer and multiplayer. This can be especially annoying in case of diving goggles because all diver player will be gogglesless.
The issue is also true using arma 3 vanilla VA.

I also tried in "Editor (Singleplayer)" with 3.12.2 RC

**Steps to reproduce:**
- place a player unit in 3DEN
- modify its loadout using ace arsenal
- choose some unexpected goggles (G_EyeProtectors_F for instance)
- save the mission
- try the loadout in single and multiplayer

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- None

**Comment by bux** [comment]
@alganthe

**Comment by alganthe** [comment]
as @Drofseh said, player indentity takes priority over everything else, it's not a bug but a feature from BI.

**Comment by Sparfell** [comment]
Could this feature be easily bypassed by ace arsenal ? I understand the purpose of the feature for faces but, as said, this is kind of "game breaking" as far as goggles are concerned because, for instance diving goggles and ace_goggles  are linked to gameplay features.

**Comment by alganthe** [comment]
No, that would require messing with identities, which I don't want to do.

**Comment by Drofseh** [comment]
The only way around it is to add the goggles afterwards using a script in your mission.

```
removeGoggles player;
player addGoggles "goggleClassname";
```

**Comment by Sparfell** [comment]
Ok, thanks for you answers guys.
@Drofseh Yes, I used to use a loadout script, thanks.

**Comment by Drofseh** [comment]
@bux add fault/BI label?
