### ISSUE TITLE
ACE actions randomly get stuck

### ISSUE THREAD

**Issue by PeterS234** [acemod/ACE3#6267]
**Arma 3 Version:** `1.82.144647
**CBA Version:** `3.6.1
**ACE3 Version:** `3.12.1

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
<details>
<summary>Original text here</summary>
Hello guys, first of all sorry if my english is not the best ;)  Im a player from a Portuguese community, and like 2/3 week ago i started to get a problem with my game. I really dont know how to explain this but, When i log into the server sometines like randomly i got like a bug. When i try to do something related with ace menu i cant, for example when i try do apply a bandage i cant the loading bar dont go, the bar appears saying bandaging but the green color dont go all the way and it stays "doing" the action i chose non stop infinitely.
When i try to dig a trench the same think happens, and when i go unsconcious when my mates bring me back i saw everything very white on my monitor.
I've already unnistalled the game, and unsubcribe all the mods and reinstall everything2/3 times but the bug keeps on.
I can give you an example yesterday i went to the server i looged everything was just fine then i needed to restart the game cause my pc crashed then i got in again and i had the bug.
In 45 players only 2 of us got this problem.
</details><br>

- Some ACE actions (like bandaging) with a progress bar randomly don't finish with the progress bar being stuck
- "when i go unsconcious when my mates bring me back i saw everything very white on my monitor"
- 2 out of 45 players had these problems

**Steps to reproduce:**
- Open ace Menu
- Choose one of ace actions

**Where did the issue occur?**
- Dedicated 

**Placed Modules:**
ace
ACE Compat - RHS Armed Forces of the Russian Federation
ACE Compat - RHS United States Armed Forces
ACEX
ALiVE
CBA_A3
cTab V2.2.1
CUP Terrains - Core
CUP Terrains - Maps
Enhanced Movement
JSRS SOUNDMOD
JSRS SOUNDMOD - RHS AFRF Mod Pack Sound Support
JSRS SOUNDMOD - RHS USAF Mod Pack Sound Support
JSRS SOUNDMOD - Specialist Military Arms Mod Sound Support
Project OPFOR
R3F Advance Logistics [BETA]
RHSAFRF
RHSUSAF
ShackTac User Interface
Spyder Addons
task_force_radio
Vcom AI V2.94 

**RPT log file:**
- None

**Comment by BaerMitUmlaut** [comment]
Can you upload both a client and a server RPT?

**Comment by PeterS234** [comment]
I have no RPT from the day of the bug.

**Comment by BaerMitUmlaut** [comment]
Well, we need one, otherwise this is just guesswork. Since this is not an issue that occurs to other people (that we know of), you'll have to help us here. If the issue occurs again make sure to save the RPT file.

**Comment by PeterS234** [comment]
OK will do ;) Thank you

**Comment by Zero3** [comment]
@PeterS234 I currently suffer from this issue in my game as well:

> Some ACE actions (like bandaging) with a progress bar randomly don't finish with the progress bar being stuck

Even restarting the game and rejoining the server does not work. Did you ever find a fix?

**Comment by Zero3** [comment]
Weirdly, I discovered that the progress bar actually makes progress when the game is minimized... But not while playing :open_mouth:

**Comment by BaerMitUmlaut** [comment]
If you have this problem, please make a new issue. This one is old enough to be in school.
