### ISSUE TITLE
Jets DLC planes cannot use their laser guided bombs

### ISSUE THREAD

**Issue by Agent556** [acemod/ACE3#6268]
**Arma 3 Version:** `1.82` stable
**CBA Version:** `3.6.1` 
**ACE3 Version:** `3.12.1` 
**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- All jets from Jets DLC cannot use LGBs even when mounted to pylon.
Pressing F to cycle through weapons skips over the GBU-12 or FAB-250 like it was never there.
After the Tanks DLC update, the LGBs used for the Jets DLC planes shows a "LOAL" fire mode in vanilla arma. This update to the weapon may be causing this effect. 

- The LGBs of non DLC planes do not show the LOAL fire mode after tanks DLC and they still work in ACE. 
In addition, the cluster munitions also do not show the new LOAL fire mode and also still function in ACE.
The Rhino's laser guided ATGM still functions in LOAL mode with any vehicle mounted laser designator.

- Additional note: JSRS Soundmod also causes this problem with the jets DLC LGBs. Might be something to look at. 

**Steps to reproduce:**
- Open Arma3
- Launch Editor or Arsenal
- Get in a Black Wasp II, Shikra, or Gripen
- Try to switch to the GBU-12 or FAB-250

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- https://gist.github.com/Agent556/17e0e4444759ff116016bc4b5ecb475d

**Comment by LEGION001** [comment]
I have a simillar issue, though for me its not just the Jets DLC jets and not just the LGB's. For me its every jet cannot use LGB's or Cluster Bombs except for the CSAT jets which can use LGB's but not cluster bombs. 

I managed to trace the issue to at least two pbo's, by removing and adding them back in. The ace_frag.pbo and the ace_rearm.pbo. Removing both of those allows the jets to use bombs again.  

Same Mods, same ACE version, same CBA version, same Arma version as the OP.

**Comment by PabstMirror** [comment]
bomb's changed inheritance in 1.82
Fixed via https://github.com/acemod/ACE3/pull/6201 which will be in 3.12.2
