### ISSUE TITLE
Switch Units addon is broken

### ISSUE THREAD

**Issue by Uberpanik** [acemod/ACE3#6274]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The Switch Unit module is not working properly. Designated player loses his equipment, ability to run, see AI units on the map and become invulnerable as intended. However clicking on the map, near units does not do anything.
- `Ace_switchunits_enableSwitchUnits` checkbox in addon options menu is missing string

**Steps to reproduce:**
- Open editor and place some BLUFOR units
- Change one of them to 'Player' and execute `this setVariable ["ACE_CanSwitchUnits", true];` on init
- In add-on settings go to "ACE Switch Units" and check `Ace_switchunits_enableSwitchUnits` and `Switch to West`
- Play the scenario and try to switch units on the map. You will see map marker of "Map gesture" addon, confirming clicks, but no actual switch going to happen

**Where did the issue occur?**
- Self-Hosted Multiplayer, Singleplayer, Editor (Singleplayer), Editor (Multiplayer)

**Placed Modules:**
- None.

**RPT log file:**
- https://pastebin.com/ShSNsUrv

**Sample mission**
- [SwitchUnitsBug.VR.zip](https://github.com/acemod/ACE3/files/1912963/SwitchUnitsBug.VR.zip)
- Unzip in Documents\Arma 3\missions\ and open via editor

**Comment by bux** [comment]
https://github.com/acemod/ACE3/issues/6188
