### ISSUE TITLE
AGM-114K and AGM-114N not working

### ISSUE THREAD

**Issue by MASACR99** [acemod/ACE3#6281]
**Arma 3 Version:** `1.82` (stable / rc / dev)
**CBA Version:** `3.6.1` (stable / dev + commit hash)
**ACE3 Version:** `3.12.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
-RHS:USAF
-Ace compat: RHS USAF
```

**Description:**
- When trying to use (already or zeus spawned) AGMs-114K or N they are not selectable from any seat

**Steps to reproduce:**
- Open any mission
- Place AGM-114K
- Not able to select one

**Where did the issue occur?**
- Dedicated server and singleplayer

**Placed Modules:**
- None

**Comment by PabstMirror** [comment]
Same as #6256
Will be fixed in next release
