### ISSUE TITLE
ACE Pylons are missing in the Addon Settings Menu

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#6285]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- I'm missing ACE Pylons in the addon settings. Double checked (downloaded the zip file twice to be shure)

**Steps to reproduce:**
- open editor open addon options = no ACE Pylons option

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**Comment by PabstMirror** [comment]
I checked and zip does contain ace_pylons.pbo
can you check `isClass (configFile >> "ace_settings" >> "ace_pylons_enabled")` in editor
rpt would be useful

**Comment by madpat3** [comment]
the pbo **IS** inside the download. 
but when you use the cba settings ( ESC>Addon Options) there is no "ACE Pylon" tab.

**Comment by madpat3** [comment]
https://www.dropbox.com/s/44nnw86wv93mh46/Arma3_x64_2018-04-19_21-12-04.rpt?dl=0

**Comment by Meiestrix** [comment]
Have you looked up the correct Name?
For the german translation it is ACE Außenlaststationen
