### ISSUE TITLE
ACE Zeus-Modules not present on first mission start

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#6286]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- When starting a mission, first time, the ace-zeus-modules are not present. 

**Steps to reproduce:**
- open VR sp editor, place a soldier and the game master module on map. start mission hit zeus key. click modules = ace modules are not there. click on restart mission, open zeus click on modules = ace modules are there

**Where did the issue occur?**
- SP Editor.

**Placed Modules:**
- Zeus Module.

**RPT log file:**
- https://www.dropbox.com/s/v53a29vrmemvr15/Arma3_x64_2018-04-19_20-15-10.rpt?dl=0.

**Comment by PabstMirror** [comment]
Make sure to set module to: all addons (+ unoffical); it's not the default setting
![image](https://user-images.githubusercontent.com/9376747/39012284-a4d8f3dc-43d9-11e8-8c8c-1669b12d5946.png)

**Comment by PabstMirror** [comment]
I guess we could change the default in the module config
not sure why it doesn't include all by default

**Comment by commy2** [comment]
Alternatively, you could add all config patches into a custom subclass of CfgAddons\PreloadedAddons.
https://git.koffeinflummi.de/bwmod-team/bwa3-public/blob/master/bwa3_common/CfgAddons.hpp
That will make them show up in Zeus by default and every time.

**Comment by jonpas** [comment]
Is apparently what ACRE2 does as well. I was wondering what that thing was for! 😆

**Comment by bux** [comment]
> I guess we could change the default in the module config

That, either by us or by CBA.
