### ISSUE TITLE
Merkava Inconsistencies

### ISSUE THREAD

**Issue by xContextual** [acemod/ACE3#6293]
**Arma 3 Version:** `1.82.1` (Current) 
**CBA Version:** `3.6.1`
**ACE3 Version:** `3.12.1`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
    Ammo Inconsistency :
Both Merkava versions ammo loadouts (in ACE) do not match vanilla profiles:
 
UP-Armored Merkava:
- ACE : 40 APFSDS-T, 20 HEAT-MP-T, 2000 x2 COAX 7.62. |
- Vanilla : 24 APFSDS-T / 12 HEAT-MP-T / 12 HE-T / 200 x20 COAX 7.62.
 
Standard Merkava:
- ACE :  32 APFSDS-T, 16 HE-T, 2000 x2 COAX 7.62.
- Vanilla : 24 APFSDS-T / 12 HEAT-MP-T / 12 HE-T / 200 x20 COAX 7.62.  (same as above).
 
Ace ammo count should remain consistent with new vanilla loadouts.
____________________
 
    Gun Bore Mismatch :
- ACE UP-Armored Merkava has 105mm cannon, as opposed to the 120mm Vanilla Up-Armored.
Unknown if this affects performance, or is just a clerical error.
____________________
 
    Ammo Count Display :
Internal Ammo Readouts for the Gunner positions in both standard and UP-Armored Merkavas displays incorrectly.
Readouts of APFSDS-T are consistent with what is loaded, while the secondary round type (HEAT-MP-T for the UP) is listed as HE-T regardless. Count is still accurate. Both versions then display the current coaxial magazine as the number of HEAT-MP-T rounds, stating that the tank has 2000 HEAT shells. COAX readout appears consistent, still displays current coaxial magazine count. The incorrect HEAT shell count decreases accordingly to COAX ammo count.
____________________
 
    Incorrect Name Truncation :
APFSDS-T shell incorrectly truncated on the HUD to "AP-T" (AP-T being an entirely disparate category of shot).

**Steps to reproduce:**
- Launch with ACE3
- Spawn Merkava Standard/UP

**Where did the issue occur?**
- Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- None

**Comment by xContextual** [comment]
Sorry if this is a bit of an improper dump, but I felt that these issues are all related.

**Comment by PabstMirror** [comment]
Should be fixed in latest release (3.12.2)

**Comment by dedmen** [comment]
>Should be fixed in latest release (3.12.2)
Is it?
