### ISSUE TITLE
AI kills don't increase score when using revive for players only

### ISSUE THREAD

**Issue by Boersencrash321** [acemod/ACE3#6304]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- No kill points are being awarded for ai kills when setting "Enable revive" to "players only".
It is only possible to get points when killing vehicles - and only for the vehicle itself, not the ai's inside it.
When setting revive to off, kills are counting. (Not every time when killing ai's but I belive thats another issue with the medical system as damage source )

**Steps to reproduce:**
- In editor: 
->Set the medical module "Enable revive" setting to"players only". 
->Place a player (blufor) and a static AT launcher somewhere.
->Place some enemy AI foot units and a car (opfor) somewhere else where they can be shot by the player. -> Start as MP.
  In game: 
-> Shoot the foot units. Check the scoreboard, no points awarded.
-> Shoot the vehicle with the AT launcher. Check the scoreboard again, only one kill (vehicle) and 2 points awarded. Still no foot unit kills.

--- Repeat the process with revive off, you should get kills for foot units now. ---

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer /  Editor (Multiplayer)

**Placed Modules:**
- Ace Medical

**RPT log file:**
https://0bin.net/paste/T2UKHZuUJOBOkcPS#3n7Ir+ndtA7Hq7g0D0qIbrNRZIW4UX7s0KUTYOz9duG

**Comment by BaerMitUmlaut** [comment]
We can't influence the scoreboard, see #3111.
