### ISSUE TITLE
Random fnc_doSpall.sqf error during firefights

### ISSUE THREAD

**Issue by Neviothr** [acemod/ACE3#6308]
**Arma 3 Version:** `1.82.144709` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS: Serbian Armed Forces
- RHS: GREF
- RHS: United States Forces
- RHS: Armed Forces of the Russian Federation
- Neviothr's Mod Pack (https://github.com/Neviothr/ArmA/tree/master/Nev)
```

**Description:**
- An error in fnc_doSpall will occur randomly during firefights.

**Steps to reproduce:**
- No clue, I was unable to reproduce at will.

**Where did the issue occur?**
- Singleplayer

**Placed Modules:**
- None.

**RPT log file:**
- https://gist.github.com/Neviothr/ed07c17e35ee8603295730b1deee4eba

**Comment by Neviothr** [comment]
@commy2 - done.

**Comment by dedmen** [comment]
Duplicate #5614

**Comment by Neviothr** [comment]
@dedmen - closed.

**Comment by Neviothr** [comment]
@dedmen - closed.
