### ISSUE TITLE
Ace AGM-65L and KH-25ML dive into the ground directly before impact.

### ISSUE THREAD

**Issue by Xon2** [acemod/ACE3#6311]
**Arma 3 Version:** `1.82.144647` stable (stable / rc / dev)
**CBA Version:** `3.6.1.180133` stable steam version(stable / dev + commit hash)
**ACE3 Version:** `3.12.233` stable steam (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```
fresh ace installation except for ace config/keybindings  

**Description:**
Ace AGM-65L and KH-25ML when in laser targeting mode make a sharp, steep dive shortly before impact hitting the ground  mostly 5m before the lased target. In normal IR mode with vanilla LOBL lockon mode they fly the like the vanilla AGM-65G (Macer) and KH-25MTP impacting straight from above with not sudden dive before impact. This happens when self lasing from A-10D or other aircraft. External laser from laser turret did not really provide better results, it had other issues. Did not test this in multiplayer with another human lasing.

I uploaded a video to youtube, the KH-25ML behaviour is the same. Is that the intended attack pattern or indeed a bug?

https://youtu.be/4Zs9067oezM

Oukej posted links to the updated wiki entries at:

https://community.bistudio.com/wiki/Arma_3_Missile_flight_profiles

https://community.bistudio.com/wiki/A3_Targeting_config_reference

If i am not mistaken, the AGM missles have not been updated since February and the Tanks DLC changed some stuff concerning missle flight profiles etc. and as it seem added a bunch of new script entries. Let me know whether you can reproduce this and i not. BTW, can ai pilots employ these missles when i lase for them from the ground?

**Steps to reproduce:**
1.) - Add static or moving tanks/artillery/vehicle+A-10D or Yak-130 and equip these with Ace AGM-65L or  
       KH-25ML in EDEN
2.) - Turn on own aircraft laser and go into pilot camera and stabilize pilot camera 
     - slew pilot camera over static or moving enemy vehicle and wait for point track mode or keep manual      
        track of enemy vehicle centre
     - select either above mentioned missle types and fire either in LOAL-DIR or LOBL-DIR (locking the laser        
        not the vehicle if hot) from sufficient distance 
     - watch missle dive shortly before reaching target impacting into the ground mostly a couple of  
        meters before requiring multiple attempts for one kill

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
None

**RPT log file:**
https://gist.github.com/Xon2/b3529cfb0c6e0cc24c1f882ea5eac39e
Ace debug copied in that split second the missle does its weird thing :)

**Comment by tbeswick96** [comment]
Experiencing this too, and this was happening before Tanks DLC

**Comment by Xon2** [comment]
ha...and i thought i was imagining things...but i kinda feel this was not working corretly before tanks dlc, too! I just figured i remembered it wrong since i didn't use the Ace agms for quite some time...i guess i didn't get good results last time but forgot about it, and figured it must have been the tanks dlc.

**Comment by xrufix** [comment]
Most likely not connected to Tanks DLC, but to the guidance function used.

I'll try to investigate further.

**Comment by mwpowellhtx** [comment]
On the plus side, wheeled vics get their wheels burned off. But still... :+1:
