### ISSUE TITLE
Arsenal is missing a get function for stored items

### ISSUE THREAD

**Issue by Boersencrash321** [acemod/ACE3#6312]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Feature request:**
- The ACE virtual arsenal is missing a get function to get an array of all items that are stored inside, just like the vanilla arsenal functions https://community.bistudio.com/wiki/BIS_fnc_getVirtualWeaponCargo provide.

**Comment by BaerMitUmlaut** [comment]
Feature requests belong into #3594. Besides, although not a function you can access those virtual items already through `_box getVariable "ace_arsenal_virtualItems` as far as I can see:
https://github.com/acemod/ACE3/blob/master/addons/arsenal/functions/fnc_addVirtualItems.sqf#L27-L46

**Comment by alganthe** [comment]
That is correct @BaerMitUmlaut
