### ISSUE TITLE
AI won't die

### ISSUE THREAD

**Issue by FlyerMan1996** [acemod/ACE3#6316]
After about 15-30 minutes while playing Dynamic Recon Ops on any map the AI will suddenly become invincible, I haven't had this issue before the November of 2017.

The way it goes is the AI won't die, my pause menu options are missing, & ACE is very slow to respond for example I would check my mag and 2 minutes later he checks it. Everything in the game is delayed but the worst part is the AI just wont die.

I have disabled ACE medical and I still have this issue

**Comment by BaerMitUmlaut** [comment]
Please follow our issue template: https://raw.githubusercontent.com/acemod/ACE3/master/.github/ISSUE_TEMPLATE.md

**Comment by FlyerMan1996** [comment]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
After about 15-30 minutes while playing Dynamic Recon Ops on any map the AI will suddenly become invincible, I haven't had this issue before the November of 2017.
The way it goes is the AI won't die, my pause menu options are missing, & ACE is very slow to respond for example I would check my mag and 2 minutes later he checks it. Everything in the game is delayed but the worst part is the AI just wont die.

**Steps to reproduce:**
Play any Dynamic Recon Ops on any map

**Where did the issue occur?**
Dedicated (Local LAN) Multiplayer Server

**Placed Modules:**
All the modules that come with the latest version of ACE

**RPT log file:**

**Comment by PabstMirror** [comment]
RPT is available from folder `%localappdata%/Arma 3/` look for most recent rpt, should be after a mission were the problem happens
I think you can just drag the file into the text box or upload it somewhere like https://gist.github.com

**Comment by FlyerMan1996** [comment]
Here is my RPT from the latest op
=====================================================================

== D:\SteamLibrary\steamapps\common\Arma 3\Arma3_x64.exe

== "D:\SteamLibrary\steamapps\common\Arma 3\Arma3_x64.exe" -skipIntro -noSplash -name=PO1.M.Stanford -noLogs -noSplash -skipIntro -cpuCount=32 -exThreads=7 -enableHT -malloc=tbb4malloc_bi_x64 -hugePages -maxmem=16269 -maxvram=8192 -filePatching -loadMissionToMemory -noCB "-mod=D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@CBA_A3;D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@CUP Weapons;D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@RHSUSAF;D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@RHSAFRF;D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@NIArms Core;D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@CUP Units;D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@Specialist Military Arms (SMA) Version 2.7.1;D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@RHSGREF;D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@RHSSAF;D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@NIArms AR15 Rifles;D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@NATO_Rus_Vehicle;D:\SteamLibrary\steamapps\commo

Original output filename: Arma3Retail_DX11_x64

Exe timestamp: 2018/04/10 14:51:04

Current time:  2018/04/30 08:57:02



Type: Public

Build: Stable

Version: 1.82.144647



Allocator: D:\SteamLibrary\steamapps\common\Arma 3\Dll\tbb4malloc_bi_x64.dll [2017.0.0.0] [2017.0.0.0]

PhysMem: 16 GiB, VirtMem : 131072 GiB, AvailPhys : 13 GiB, AvailVirt : 131072 GiB, AvailPage : 18 GiB

=====================================================================



 8:57:02 Detected number of DLCs: 20

 8:57:02 DLC index:3 - unable to get DLC data

 8:57:02 ----------------------------------------- Dlcs -----------------------------------------

 8:57:02                                 name      appId   owned  installed  available   isDlc

 8:57:02                               Arma 3     107410     yes        yes        yes      no

 8:57:02                              Unknown         -1      no         no         no     yes

 8:57:02                          Arma 3 Zeus     275700     yes        yes        yes     yes

 8:57:02                   Arma 3 Helicopters     304380      no         no        yes     yes

 8:57:02                   Arma 3 Laws of War     571710      no         no        yes     yes

 8:57:02                  Arma 3 DLC Bundle 2     612480      no         no        yes     yes

 8:57:02                        Arma 3 Malden     639600     yes        yes        yes     yes

 8:57:02                         Arma 3 Tanks     798390      no         no        yes     yes

 8:57:02      Arma 3 Alpha Lite - expires now     228800      no         no         no     yes

 8:57:02                        Arma 3 Server     233780     yes        yes         no     yes

 8:57:02                    Arma 3 Soundtrack     249860      no         no         no     yes

 8:57:02                  Arma 3 DLC Bundle 1     304400      no         no         no     yes

 8:57:02                       Arma 3 Samples     390500     yes        yes         no     yes

 8:57:02                          Arma 3 Apex     395180     yes        yes        yes     yes

 8:57:02                          Arma 3 Jets     601670     yes        yes        yes     yes

 8:57:02          Arma 3 Tac-Ops Mission Pack     744950      no         no        yes     yes

 8:57:02                          Arma 3 Maps     249861      no         no         no     yes

 8:57:02                Arma 3 Tactical Guide     249862      no         no         no     yes

 8:57:02                         Arma 3 Tools     233800     yes        yes         no     yes

 8:57:02                         Arma 3 Karts     288520      no         no        yes     yes

 8:57:02                      Arma 3 Marksmen     332350      no         no        yes     yes

 8:57:02 ----------------------------------------------------------------------------------------

 8:57:02 Entering off-line mode. Callbacks and content list updates will not work.


I will post my full mod list (195+) here soon

**Comment by commy2** [comment]
You disabled logging via `-noLogs`, which makes this RPT file useless. You will have to try again without `-noLogs`.
You also wrote the mods were CBA and ACE, but now it's >195 mods. You're supposed to reproduce the issue with only CBA and ACE enabled on an empty mission. How do we even know this is an issue related to ACE if you have about 200 (!!!) mods running?
Pray that it is some kind of scripting error that is logged, and that your setup isn't so screwed up already that it's possible to find. Otherwise you will have to manually disable all other mods and reenable them to find the broken combination.

**Comment by ligmabalzzzz** [comment]
how did you fix it?

**Comment by BaerMitUmlaut** [comment]
This issue is 4 years old and the OP stopped replying before the problem was solved. If you have a similar issue, open a new one.
