### ISSUE TITLE
AI interaction issues/questions 

### ISSUE THREAD

**Issue by KidIrie** [acemod/ACE3#6319]
**Arma 3 Version:** `1.82.144647` (stable / rc / dev)
**CBA Version:** `3.6.1` (stable / dev + commit hash)
**ACE3 Version:** `3.12.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- AI Medics will not give morphine or blood transfusions to victims in basic
- Unable to give orders to AI Medics to heal other units
- Unable to give orders to any AI units to plant explosives

**Steps to reproduce:**
- Place units in Editor, shoot em up, see how the medics react. Units in pain and with blood loss will not be treated, even though medics have the necessary items to heal.
- Place a unit in Editor. Give him the necessary explosives and stand him next to a target. Try going into his action menu, but there's no action to allow him to drop down or place his explosives.

**Where did the issue occur?**
- Editor (Singleplayer) / Dynamic Recon Ops missions

**Note**
- Sorry guys, I know these might not be "bugs" and it's possible the AI with ACE is just not meant to do these things. I looked all over the web but couldn't confirm this, so thought I'd go straight to the source.

**Comment by BaerMitUmlaut** [comment]
>AI Medics will not give morphine or blood transfusions to victims in basic

They will give units morphine, but only if they have enough pain. They don't do blood transfusions though.

>Unable to give orders to AI Medics to heal other units

AI medics will automatically heal other units within their squad when they feel both they themselves and the injured unit are safe enough to do so. There is no need to order them around.

>Unable to give orders to any AI units to plant explosives

You can remove ACE explosives if you want to do that. AI does not know how to use a clacker.

>Sorry guys, I know these might not be "bugs" and it's possible the AI with ACE is just not meant to do these things. I looked all over the web but couldn't confirm this, so thought I'd go straight to the source.

No worries! You can join our Slack too if you have any further questions.

**Comment by KidIrie** [comment]
Got it. Thanks for the speedy reply. Any plans for the AI medics being able to perform blood transfusions in basic then? If they're going to be on automatic, without options to be given orders, I'll need to depend on them to do it all. And having to switch perspective and play them in order to make it happen kinda breaks the immersion.

Other then that, ACE is the best!

**Comment by BaerMitUmlaut** [comment]
Sorry, I forgot answering. AI making blood transfusions should be possible.

**Comment by KidIrie** [comment]
Hi there. Been a while so just thought I'd check in to see if AI blood transfusions is still on the table. If so, any type of timeframe? The missions I tend to play don't allow switching units, so single players like myself are unable to use the ACE medical system if there's nobody around to give blood. Thanks!

**Comment by thojkooi** [comment]
I cannot give you a time frame unfortunately but I see the benefit of it for single player. It may be resolved with the medical rewrite.

**Comment by KidIrie** [comment]
OK. Another question then, is there any way to allow a regular soldier to perform a blood transfusion in Basic Medical? I didn't see any options in the settings. Since I can't switch units, my idea would be to just have my medic throw the blood on the ground and then I'd just do it.

**Comment by BaerMitUmlaut** [comment]
You can set the medic setting to make basically every soldier a medic.

**Comment by PabstMirror** [comment]
blood has ` allowSelfTreatment = 0;`, which I think should be made into a setting

**Comment by KidIrie** [comment]
@PabstMirror : Excuse my newbness, but I don't think I want to mess with mission file coding, which I think is what you're hinting at.

@BaerMitUmlaut : I've been through the Game Options/AddOn Settings/Ace Medical, and "enabled" all medic settings that seemed appropriate. Is there another particular place you're referring to?
