### ISSUE TITLE
ACE Arsenal item stat window shows incorrect weight for NVGs

### ISSUE THREAD

**Issue by Blutze** [acemod/ACE3#6320]
**Arma 3 Version:** `1.82.144647 stable`
**CBA Version:** `3.7.0.180430 stable`
**ACE3 Version:** `3.12.2 stable`

**Mods:**
```
- CBA_A3
- ace
- Various gear mods (RHS, 3cb, TRYK), but also happens with just CBA and ACE.
```

**Description:**
That little item statistics display in the top left shows only weight and nothing about generation/field of view (if it ever did that). The weight is also incorrect - its always 0.45 kg / 1 lbs, when it should be 20 mass for most vanilla items, 30 mass for ENVGs, and 2 or 4 mass for 3cb and TRYK pieces. Total loadout weight in the bottom left of the ACE Arsenal screen and the inventory display added by ACE update correctly.

**Steps to reproduce:**
- Start the ACE Arsenal mission thingy
- Open NVG tab
- Behold, 10 mass

**Where did the issue occur?**
- ACE Arsenal
- Also occurs on my group's server, with a bunch of other mods and opening the Arsenal through interacting with an object. Have very little under the hood info about that mission template though.

**Placed Modules:**
- None, aside from whatever you guys use in that mission.

**RPT log file:**
- rpt: https://pastebin.com/NRMmvQjT
- ACE debug: https://pastebin.com/hUWXDYuv

**Comment by alganthe** [comment]
I don't use configExtremes for mass @dedmen see:
https://github.com/acemod/ACE3/blob/master/addons/arsenal/functions/fnc_statTextStatement_mass.sqf

for the reason why that happens.... no idea.

>That little item statistics display in the top left shows only weight and nothing about generation/field of view (if it ever did that).

It never did and since nobody, not even ACE, uses the config entry for those I can't really add them.

**Comment by alganthe** [comment]
Nevermind checking the config viewer reveals why, for some god forsaken reason NVGs have a WeaponSlotInfo config entry O.o

**Comment by PabstMirror** [comment]
NVGs are only item type I could find that has this problem.

```
{
    _config = _x;
    private _mass = getNumber (_config >> "mass");
    private _a = getNumber (_config >> "WeaponSlotsInfo" >> "mass");
    private _b = getNumber (_config >> "itemInfo" >> "mass");
    if (_mass == 0 && {_a != 0} && {_b != 0} && {_a != _b}) then {
        diag_log text format ["conflict - %1 [%2-%3]", _config, _a, _b];
    };
} forEach configProperties [configFile >> "CfgWeapons", "isClass _x", true];

conflict - bin\config.bin/CfgWeapons/NVGoggles [10-20]
conflict - bin\config.bin/CfgWeapons/NVGoggles_OPFOR [10-20]
conflict - bin\config.bin/CfgWeapons/NVGoggles_INDEP [10-20]
conflict - bin\config.bin/CfgWeapons/Integrated_NVG_F [10-20]
conflict - bin\config.bin/CfgWeapons/Integrated_NVG_TI_0_F [10-20]
conflict - bin\config.bin/CfgWeapons/Integrated_NVG_TI_1_F [10-20]
conflict - bin\config.bin/CfgWeapons/CUP_NVG_PVS7 [10-4]
conflict - bin\config.bin/CfgWeapons/CUP_NVG_HMNVS [10-4]
conflict - bin\config.bin/CfgWeapons/CUP_NVG_PVS14 [10-4]
conflict - bin\config.bin/CfgWeapons/O_NVGoggles_hex_F [10-20]
conflict - bin\config.bin/CfgWeapons/O_NVGoggles_urb_F [10-20]
conflict - bin\config.bin/CfgWeapons/O_NVGoggles_ghex_F [10-20]
conflict - bin\config.bin/CfgWeapons/NVGoggles_tna_F [10-20]
conflict - bin\config.bin/CfgWeapons/NVGogglesB_blk_F [10-30]
conflict - bin\config.bin/CfgWeapons/NVGogglesB_grn_F [10-30]
conflict - bin\config.bin/CfgWeapons/NVGogglesB_gry_F [10-30]
conflict - bin\config.bin/CfgWeapons/rhsusf_ANPVS_14 [10-20]
conflict - bin\config.bin/CfgWeapons/rhsusf_ANPVS_15 [10-20]
conflict - bin\config.bin/CfgWeapons/rhsusf_Rhino [10-5]
conflict - bin\config.bin/CfgWeapons/rhsusf_anvis_nvg_bc_caps [10-4]
conflict - bin\config.bin/CfgWeapons/rhsusf_ANVIS [10-20]
conflict - bin\config.bin/CfgWeapons/rhs_1PN138 [10-15]
conflict - bin\config.bin/CfgWeapons/ACE_NVG_Gen1 [10-20]
conflict - bin\config.bin/CfgWeapons/ACE_NVG_Gen2 [10-20]
conflict - bin\config.bin/CfgWeapons/ACE_NVG_Gen4 [10-20]
conflict - bin\config.bin/CfgWeapons/ACE_NVG_Wide [10-20]
conflict - bin\config.bin/CfgWeapons/ACE_NVG_Biocular [10-20]
conflict - bin\config.bin/CfgWeapons/ACE_NVG_Monocular [10-20]
conflict - bin\config.bin/CfgWeapons/ACE_NVG_Binocular [10-20]
conflict - bin\config.bin/CfgWeapons/ACE_NVG_Quadocular [10-20]
```
