### ISSUE TITLE
Arma3 (v1.82) & ACE3 (v3.12.2) = Spam of Errors

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#6321]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.6.1.180131` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- After update I have a many errors notifications. They are repeated many times but it seems that the errors are only two:

http://images.vfl.ru/ii/1525299079/cf676d97/21592406.jpg
http://images.vfl.ru/ii/1525299103/728f4568/21592408.jpg

**Steps to reproduce:**
- play in ACE3 3.12.2 in single-player missions which are were made before 3.12.2

**Where did the issue occur?**
- \Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
-

**Comment by BaerMitUmlaut** [comment]
Looks like something is wrong with spalling. You can disable it as a temporary fix.

**Comment by jokoho48** [comment]
Duplicate #5614
