### ISSUE TITLE
Interaction Menu Doesn't Work

### ISSUE THREAD

**Issue by JackSowrd** [acemod/ACE3#6328]
**Arma 3 Version:** Up To Date
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
When trying to use the self interaction menu it just shows a red circle. The menu works while in vehicles.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
Singlepayer

**Placed Modules:**
Default

**RPT log file:**
https://pastebin.com/ZRzwdKAZ

**Comment by JackSowrd** [comment]
The menu opens but its just a red circle, i used the windows key. The weird thing is ace used to work.

**Comment by commy2** [comment]
The default keybind for the self interaction menu is `Ctrl + Win`, not `Win` iirc.
`Win` is the default keybind for the interaction menu, which is a different one and obviously empty when there is nothing in front of you.
