### ISSUE TITLE
Missing framework for setAnimSpeedCoef and setCustomAimCoef

### ISSUE THREAD

**Issue by mihal190** [acemod/ACE3#6335]
**Arma 3 Version:** `1.82` stable
**CBA Version:** `latest
**ACE3 Version:** `3.12.2`

**Mods:**
```
- CBA_A3
- ace
- Faster_movement
```

**Description:**
- Advanced fatigue blocks changing animation speed or aimprecison "sway"

**Steps to reproduce:**
- Try to loop any comand that changes one of these things, reapply it with sleep 1; and see movement sped

**Where did the issue occur?**
- Everywhere

**Comment by xrufix** [comment]
AimCoef Framework is added in #5828
