### ISSUE TITLE
Pylons Menu unavailable for Zeus when disabled for players.

### ISSUE THREAD

**Issue by xrufix** [acemod/ACE3#6336]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.0.180430` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- Multiple, but should not make a difference
```

**Description:**
- When disabling Pylons Menu in settings, Pylons Menu is also unavailable to Zeus.

**Expected Behaviour:**
- Zeus can change pylon loadouts even if it is disabled for players.

**Steps to reproduce:**
- Disable Pylons Menu in mission settings and force on client.
- Play the mission and use Zeus module "Configure Pylons" on a plane or helicopter.
- Nothing happens.

**Where did the issue occur?**
- Dedicated

**Comment by dedmen** [comment]
https://github.com/acemod/ACE3/blob/master/addons/zeus/functions/fnc_moduleConfigurePylons.sqf#L37 calls
https://github.com/acemod/ACE3/blob/master/addons/pylons/functions/fnc_showDialog.sqf#L21and exits there.

Problem is though that disabling pylons
https://github.com/acemod/ACE3/blob/master/addons/pylons/XEH_postInit.sqf#L4
Really disables the whole pylon module. It doesn't just "disallow" it for the clients. 
even if you change showDialog the namespace and events are not there.

**Comment by 654wak654** [comment]
Think the best to handle this is way is we get rid of the "enabled" setting and instead add "enabled from ammo trucks" & "enabled for zeus" settings instead. Should also move it over to CBA settings while I'm at it.
