### ISSUE TITLE
Prevent instadeath = 0 does not work when revive enabled

### ISSUE THREAD

**Issue by tyl3r99** [acemod/ACE3#6337]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `CBA_A3 v3.7.0.180430` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace 
- RHS (us/rus)
- VSM all in one
- ACRE2
- Warfare Thai EX 
- ADV - ACE CPR 
```

**Description:**
- Prevent insta death = 0 and enablerevive = 1 
I want to make it so the player can still die from realistic wounds straight away i.e. shot in the head by heavy calibre or blown up by a explosion etc. however with these settings set as stated above no matter what i do i only go unconscious. ADV Ace CPR mod only works when revive is enabled and I love the idea of CPR actually working and the defibrillator being able to get a heart rate to return without the magical PAK. 
i tried tweaking the player damage values but no luck
**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
1. set prevent insta death = 0
2. enable revive = players only / 300 seconds
3. i left the player damage set to 1 but tried (0.5 / 1 / 1.8 / 4)
4. spawn in on a MP enviroment i.e. LAN
5. enable yourself zeus access 
6. access zeus and spawn any armed unit
7. remote control spawned unit, and shoot yourself in the head with a 5.56 round or higher
8. or skip step six and blow yourself up with a satchel charge or tank shell 

**Where did the issue occur?**
- all area's 

**Placed Modules:**
- No modules placed only tweaked CBA settings

**RPT log file:**
no script errors

**Comment by tyl3r99** [comment]
https://forums.bohemia.net/forums/topic/203195-adv-ace-cpr/?page=4&tab=comments#comment-3289944

basically a mod we're looking into using only works when revive setting is enabled, however I am also looking into removing the preventinstadeath setting so it would add more immersion in the aspect of danger of dying from lets say a tank or heavy caliber or even getting blown up in a tank would insta kill you.

i found that it kills immersion when falling from 3000m and only going unconcious lol

**Comment by tyl3r99** [comment]
// ACE Medical
force ace_medical_ai_enabledFor = 2;
force ace_medical_AIDamageThreshold = 1;
force ace_medical_allowLitterCreation = true;
force ace_medical_allowUnconsciousAnimationOnTreatment = true;
force ace_medical_amountOfReviveLives = -1;
force ace_medical_bleedingCoefficient = 1.2;
force ace_medical_blood_enabledFor = 2;
force ace_medical_consumeItem_PAK = 1;
force ace_medical_consumeItem_SurgicalKit = 0;
force ace_medical_delayUnconCaptive = 3;
force ace_medical_enableAdvancedWounds = true;
force ace_medical_enableFor = 0;
force ace_medical_enableOverdosing = true;
force ace_medical_enableRevive = 0;
force ace_medical_enableScreams = true;
force ace_medical_enableUnconsciousnessAI = 1;
force ace_medical_enableVehicleCrashes = true;
force ace_medical_healHitPointAfterAdvBandage = false;
force ace_medical_increaseTrainingInLocations = false;
force ace_medical_keepLocalSettingsSynced = true;
force ace_medical_level = 2;
force ace_medical_litterCleanUpDelay = 0;
force ace_medical_litterSimulationDetail = 0;
force ace_medical_maxReviveTime = 300;
force ace_medical_medicSetting = 2;
force ace_medical_medicSetting_basicEpi = 0;
force ace_medical_medicSetting_PAK = 1;
force ace_medical_medicSetting_SurgicalKit = 1;
force ace_medical_menu_allow = 1;
force ace_medical_menu_maxRange = 3;
force ace_medical_menu_openAfterTreatment = true;
force ace_medical_menu_useMenu = 1;
force ace_medical_menuTypeStyle = 0;
force ace_medical_moveUnitsFromGroupOnUnconscious = false;
force ace_medical_painCoefficient = 1.2;
force ace_medical_painEffectType = 1;
force ace_medical_painIsOnlySuppressed = true;
force ace_medical_playerDamageThreshold = 1;
force ace_medical_preventInstaDeath = false;
force ace_medical_remoteControlledAI = true;
force ace_medical_useCondition_PAK = 1;
force ace_medical_useCondition_SurgicalKit = 1;
force ace_medical_useLocation_basicEpi = 0;
force ace_medical_useLocation_PAK = 0;
force ace_medical_useLocation_SurgicalKit = 0;

**Comment by senevoldsen** [comment]
Enabling revive means that whenever you would normally die, you instead just go into a special unconscious state where you cannot take any damage, and must be revived before your timer runs out.

I can see why it might be confusing, but the features are orthogonal. `instadeath` is merely one option to specify one method of *how* you die. Where as revive simply redefine dying from normal Arma dying into going into revive state instead.

Look at [2.1.3 and 2.1.4](https://ace3mod.com/wiki/feature/medical-system.html#213-additional-informations) and [2.2.5](https://ace3mod.com/wiki/feature/medical-system.html#225-revive-advanced-medical).

**Comment by SilentSpike** [comment]
Thank you for a very good explanation @senevoldsen 👍 (nice use of orthogonal)

The revive and instant death settings are quite confusing. I'm hoping we are able to address all of the medical settings UX in the rewrite so that it's obvious what they do and how they interplay.

**Comment by BaerMitUmlaut** [comment]
Everything working as intended. If you want to be able to die completely from a single shot you need to disable the revive system.
