### ISSUE TITLE
ACE NLAW doesn't damage vehicles

### ISSUE THREAD

**Issue by MAD-BUG** [acemod/ACE3#6341]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.0` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- ACE NLAW not inflicting damage or do very small amount of expected damage. Possible BIS fault cause right now vanilla PCML not damaging vehicles if not locked.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)
**RPT**
- https://pastebin.com/KnGQtDPL

**Comment by AACO** [comment]
Is this direct attack, flyover topdown, or both (also as usual please include your RPT)?

**Comment by PabstMirror** [comment]
Might have to do the the 1.82 warhead//penetration changes

**Comment by BaerMitUmlaut** [comment]
Did you enable cookoff?

**Comment by MAD-BUG** [comment]
Both attack modes. Default settings for modules. Ddded RPT.

**Comment by BaerMitUmlaut** [comment]
Why did you close this?

**Comment by MAD-BUG** [comment]
After retest i found out that NLAW in reality do damage but for something like Varsuk damage in most situations is eaten by some parts of hull or tower without damaging hull or turret respectively. But if you hit hull of kamysh it explodes momentarily
![20180611060900_1](https://user-images.githubusercontent.com/15111884/41211397-b1241aba-6d3f-11e8-9664-5f79093121e5.jpg)
