### ISSUE TITLE
Vannilla actions presented to activate dropped or defused mines.

### ISSUE THREAD

**Issue by MAD-BUG** [acemod/ACE3#6342]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.0` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- After dropping or defusing mine vanilla options to activate and then took off mine appears.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)
**RPT log file:**
- https://pastebin.com/Wted7rKb

**Comment by BaerMitUmlaut** [comment]
Confirmed and fixed in #6353, thank you.
