### ISSUE TITLE
How to tweak the overheating rate in custom weapon?

### ISSUE THREAD

**Issue by JinougaF** [acemod/ACE3#6343]
Hi, I'm working on a weapon mod, and in test with ACE installed, the weapon is way too much easy to jam due to overheating too fast, which value in weapon config do i need to change to make it not overheating too fast? Any suggestion?

**Comment by Drofseh** [comment]
https://ace3mod.com/wiki/framework/overheating-framework.html

**Comment by JinougaF** [comment]
already used this, nothing has changed

**Comment by commy2** [comment]
Thermal energy increment is based on the bullets mass and velocity. Bullet mass is read from the `ACE_BulletMass` config entry, and if that one doesn't exist, it is estimated by it's `hit` and `caliber` values. Unit should be gramms, but not sure. Maybe search and compare "ACE_BulletMass" from a few weapon configs on this repository.

https://github.com/acemod/ACE3/blob/master/addons/overheating/functions/fnc_overheat.sqf#L29-L44

**Comment by commy2** [comment]
The next important thing is the weapons heat capacity, which is based on it's barrel mass, which is estimated by the `mass` parameter (item inventory size).
https://github.com/acemod/ACE3/blob/master/addons/overheating/functions/fnc_updateTemperature.sqf#L30
This determines how much energy is needed to increase or decrease the temperature per Joule energy, and therefore determines heating up and cooling rates.

**Comment by JinougaF** [comment]
so more mass mean more easy to heating up or less mass?

**Comment by commy2** [comment]
More bullet mass (`ACE_BulletMass`) means more thermal energy, more barrel/weapon `mass` means less thermal energy is required to change the temperature.

**Comment by JinougaF** [comment]
so from my logical is, I reduce the bullet mass and weapon mass would decrease the overheating rate?

**Comment by JinougaF** [comment]
so reduce bullet mass = reduce thermal energy, reduce barrel/weapon mass= increase the thermal energy to change temperature, I think i get the idea

**Comment by JinougaF** [comment]
ok just make sure I put all the realistic value, now I think the issue is out of the value I put in, should be in the config I made may have texting error, anyway thanks for hlep.
