### ISSUE TITLE
Cargo loading framework with custom vehicle

### ISSUE THREAD

**Issue by IBasterreche** [acemod/ACE3#6344]
Arma 3 Version: 1.82.144647 (stable / rc / dev)
CBA Version: 3.6.1 (stable / dev + commit hash)
ACE3 Version: 3.12.2 (stable / dev + commit hash)

Mods:
- CBA_A3
- ace

Description:
So I was working with a model of a stretcher and I tried to make it loadable to a vehicle. Nonetheless, the model functions as a vehicle and I'm having issues to such vehicle loadable to the virtual inventory of a truck, for example. So I was wondering if I could get some help with how I could make the code work. So basically, Im trying to load a vehicle into a vehicle in ACE.

At the moment I tried with this code:

"class classname-of-the-sretcher {
    class CfgVehicles {
        ace_cargo_size = 4;  
        ace_cargo_canLoad = 1;  
    };
};"

Where did the issue occur?
Editor (Singleplayer)

Note
Sorry if it is a stupid question but I'm not experienced with coding in Arma. Thanks

**Comment by BaerMitUmlaut** [comment]
Your Stretcher class needs to be within CfgVehicles. You should already have such a class if you got it in game yet.

**Comment by dedmen** [comment]
>"class classname-of-the-sretcher {
class CfgVehicles {
ace_cargo_size = 4;
ace_cargo_canLoad = 1;
};
};"

swapped classes
