### ISSUE TITLE
Unconscious unit under the vehicle

### ISSUE THREAD

**Issue by YoannFR** [acemod/ACE3#6358]
**Arma 3 Version:** `1.82` (stable / rc / dev)
**CBA Version:** `3.6.0` (stable / dev + commit hash)
**ACE3 Version:** `3.11.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- Ivory_rs4 ( for example ) 
```

**Description:**
- When i load a unconscious unit with modded vehicle, the unit is under the vehicle

**Steps to reproduce:**
- Load a unconscious unit in the modded vehicle

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Medical Modules

** RPT LOGS**
No errors in the logs.

![20180520180230_1](https://user-images.githubusercontent.com/27434438/40280731-2103d774-5c58-11e8-858f-9ac879444146.jpg)

**Comment by YoannFR** [comment]
Sorry, i'have edit the message.

So, with the vanilla vehicles i don't have any problems...
I load the unit with the Windows Menu -> Load Patient Into

**Comment by YoannFR** [comment]
https://i.gyazo.com/ac318032fe925551e3ddd199768eaf93.mp4
When i load the unit, it's very rapid ! But i don't have the problem when the unit it's not inconscious and handcuffed.

**Comment by dedmen** [comment]
Considering it's only happening with exactly these modded vehicles and neither with vanilla vehicles or vehicles from other mods. I'd say it's not a ACE bug.

**Comment by BaerMitUmlaut** [comment]
There's something wrong with the animation config for the passenger then. What happens when somebody dies within that vehicle?

**Comment by YoannFR** [comment]
When the unit dies in the vehicle, even problem ! 
So, do you have a solution ?

**Comment by jokoho48** [comment]
contact the Author of the mod and report him that is Animation config is broken.
I would go with dedmen, not an ACE bug

**Comment by YoannFR** [comment]
Ok, thank you for your help ! ;)

**Comment by BaerMitUmlaut** [comment]
ACE does the same animation as the death animation, which is broken too it seems, so not ACE3's fault - closing.

**Comment by PabstMirror** [comment]
This may work differently in medical rewrite anyway as it's using the unconc command instead of looking up animations

**Comment by BaerMitUmlaut** [comment]
Pretty sure it would have the same issue, since it already is broken with dead units.
