### ISSUE TITLE
Empty swayFactor in module advanced fatigue

### ISSUE THREAD

**Issue by by1e11** [acemod/ACE3#6359]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.12.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The swayFactor in advanced fatigue module was never assigned a value, which leads to very weak weapon sway effect.

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) tested, but presumably, it will occur everywhere

**Placed Modules:**
- advanced fatigue

**Comment by BaerMitUmlaut** [comment]
It's nil because the initSettings isn't uncommented yet...

**Comment by BaerMitUmlaut** [comment]
Fix is underway (#6360), thanks for reporting.
