### ISSUE TITLE
Gen3 NVG / Vanilla NVG Oval FOV to Full-Screen FOV with ACE3 NVG effects disabled

### ISSUE THREAD

**Issue by TheNightstalk3r** [acemod/ACE3#6367]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.0` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Per default, the ACE3 Nightvision effects are enabled. If one chooses to disable these effects (fog, effects, blur), the vanilla nightvision goggles (presumed to be Gen3s) become full-screen NVGs instead of the vanilla and (intact) ENVG oval FOV.

**Steps to reproduce:**
Play at night (SP/MP) with ENVGs, Gen3 NVGs and compare

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal (all of them)

**Placed Modules:**
No modules placed, CBA Settings; all ACE3 Nightvision effects disabled

**Comment by BaerMitUmlaut** [comment]
Nothing we can really do about since the NVG overlay is disabled through config. You can delete the PBO if you want vanilla NVGs.
