### ISSUE TITLE
Giving an AI a scripted gun shot wound

### ISSUE THREAD

**Issue by Hellostop** [acemod/ACE3#6373]
A3 Ver - 1.82.144710
CBA - 3.7
ACE - 3.12.2

**Mods:**
```
- CBA_A3
- ace
-CUP - Core & Maps & ACE Compatability
-DynaSound 2
-Enhanced Movement
-Enhanced Soundscape
-JSRS
-MCC
-Project OPFOR
-RHS AFRF/USAF/GREF
-ShackTac UI
-US Forces 2000s
-VSM AIO
-3CB BAF Vehicles/Weapons/Unit/Equipment & Comparability patch for ACE
-TAC Vests
-Spyder Addons
```

**Description:**
- I'm attempting to give an AI a gunshot wound to his right leg; however, no matter how many different form post on Reddit and on here I try I cannot get it to work. I have additionally tried looking through the functions myself and tried all of the related ones, yet still to no avail. Some functions I tried worked to an extent, Once I move the damage variable up high enough in the function the AI will die; however, even after they die you can see no injuries in the interaction menu.  I'm sure the posts are correct; however, i'm ~~probably~~ just doing something wrong. Help is greatly appreciated as always. :)

**Where did the issue occur?**
- Eden

**Placed Modules:**
- None

**Comment by commy2** [comment]
```sqf
[{
    [_this, 0.8, "leg_l", "bullet"] call ace_medical_fnc_addDamageToUnit;
}, soldier1] call CBA_fnc_execNextFrame;
```
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_addDamageToUnit.sqf

**Comment by Hellostop** [comment]
Thanks for your help! Worked like a charm :)
