### ISSUE TITLE
RHS RGO/RGN scripted grenades does not have ACE frags.

### ISSUE THREAD

**Issue by severgun** [acemod/ACE3#6380]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.0` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- ace rhs compat
- RHS 0.4.5
```

**Description:**
RGO/RGN grenades have config entries for ace_frag support but it doesn't work.

**Steps to reproduce:**
Throw RGO and try to hear or catch fragments.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**Comment by commy2** [comment]
Do you have frags enabled in addon options?

**Comment by severgun** [comment]
Of course it is.
RHS RGD-5 have them.

**Comment by commy2** [comment]
Missed the "RHS" part.

**Comment by PabstMirror** [comment]
RHS RGO/RGN grenades are scripted "impact" grenades.
RHS does
```
// Delete parent grenade
deleteVehicle _grenade;

// Create new submunition grenade with parent's position and velocity
_grenade = createVehicle [_sub, _pos, [], 0, "CAN_COLLIDE"];
```
which means ace_frag can't track the original thrown object

**Comment by Blutze** [comment]
> RHS RGO/RGN grenades are scripted "impact" grenades.

- With only RHS loaded, I do get that behavior.
- With CBA and ACE, straight from the SWS without pushing compat files around, they change to a timed fuse, but don't bounce and don't have fragmentation yet.
- With our custom ACE upload (supposedly just activating some optional files, otherwise identical to the official upload, frag and compat PBOs are version 3.12.2.33 according to the keys), they behave like any other frag grenade: timed, bouncing, causing fragmentation.

Always thought the "impact" in the ammo display name was just a mislabel...

**Comment by severgun** [comment]
> Always thought the "impact" in the ammo display name was just a mislabel...

No. something broken on your side. On my tests it explodes on impact or on timer if dropped from high distance.

**Comment by commy2** [comment]
Please @Blutze and @severgun upload your RPT files to e.g. pastebin. I'd like to compare them, thanks.

**Comment by Blutze** [comment]
@commy2 
No mods other than mentioned on the descriptions; all official SWS uploads up to date on 3rd June '18.

[AFRF only](https://pastebin.com/7KGN1RdK)
[CBA, ACE, AFRF, no compat](https://pastebin.com/JPeGUkCj)
[CBA, ACE, AFRF, compat](https://pastebin.com/hhX522pa)

Same behavior as before. ACE changes fuse from impact to regular timed, compatibility re-adds regular bouncing and adds fragmentation.

**Comment by commy2** [comment]
No compat is just a fauly setup, so it can be ignored.
So RHS+ACE+compat turns then from impact to timed grenades?
But frag works correctly, right?

**Comment by commy2** [comment]
I think the RHS grenades are scripted.

**Comment by severgun** [comment]
Yes. RHS grenades are scripted.
Yes. If you are using adv. throwing they will change class to regular timedelayed grenades.
No. There is no ace frags on regular throw.
Who ever use adv throwing during firefight?

**Comment by Dystopian** [comment]
> Who ever use adv throwing during firefight?

I always use it. I just assigned both throws to one key.
