### ISSUE TITLE
NVG, commitment between technical realism or adapted realism.

### ISSUE THREAD

**Issue by Legolasindar** [acemod/ACE3#6383]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `v3.7.0.180430` 
**ACE3 Version:** `3.12.2`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**

ACE 3's NVG are really good. I can see how there's been a good deal of research and coding into it.

But in my humble opinion, I think they're maybe a tad too accurate which can degrade a bit the gameplay experience. 

The field of view delivered by ACE’s NVG is accurate to the point, but one must remember that some people play in small screens which can make it harder to see as we would through actual NVG.

You must consider that the game’s field of view is already a scaled down depiction of what a human can see in real life. When the mod’s NVG reduces the display image even further then for some it becomes impossible to distinguish anything at all. 

I think it would be good to compromise a bit this time and ponder the possibility to add different sized NVG frame scales, or even the option to remove it altogether. I understand it wouldn’t be as accurate, but it would allow a better gameplay while keeping some of the ACE’s NVG features.

**Comment by TheNightstalk3r** [comment]
I second this. Some people have a hard time seeing and orientating themselves on smaller resolution screen. Even though the NVG (wide) exists, I think it would make gameplay a lot better if users could change the size of the overlay (increase/decrease the FOV)

**Comment by commy2** [comment]
>You must consider that the game’s field of view is already a scaled down depiction of what a human can see in real life. 

This is irrelevant if the FOV of the night vision is the same as it is in real life. You're limited by the minimum of either the monitor or the NVG, but if the real thing already is smaller than the monitor, this doesn't matter anymore.

**Comment by severgun** [comment]
> I think it would make gameplay a lot better if users could change the size of the overlay (increase/decrease the FOV)

Legal cheats? Who ever would play narrowed overlay if you can stetch it to fullscreen?

**Comment by Legolasindar** [comment]
> This is irrelevant if the FOV of the ingame night vision is the same as it is in real life. You're limited by the minimum of either the monitor or the ingame night vision, but if the real thing already is smaller than the monitor, this doesn't matter anymore.

Technically, the angle of vision of the NVG in the ACE may be correct.
But, that is correct at a technical level, does not mean that it is the most recommended option.

In real life, you have NVGs stuck in your eyes. The size of the screen will be 1:1.

https://i.imgur.com/CkzRNlS.jpg

In our missions, we have the monitor at some distance from our eyes, so we will see the smaller image. Yes, the angle remains the same, but not the size and therefore the image quality.

https://i.imgur.com/ySHadit.jpg

Also, not all of us have monitors of the same size. The bigger the monitor, the bigger the image. Yes, the angle remains the same, but a small angle, seen by a normal monitor that reduces the image much in its size, results in a tiny image.

ACE 3 allows us to adjust the distance of vision as we want. Is it real to have the distance of vision at 4000 meters? No. Is it real to have it at 10000 meters? Do not.
It is cheating that some players have it to 2000 and others to 8000. It may be, but we must make concessions to adapt to the environment in which we play.

I do not suggest that an equal framework be made for everyone. I suggest that in this case we are given options, so that we are the players themselves that we can adapt the NVG a bit to our technical limitations, just as it is done with the distance of vision :)

**Comment by BaerMitUmlaut** [comment]
This is a feature request and thus belongs into #3594.

Since the wide screen NVGs exist I don't see the issue here.
