### ISSUE TITLE
ACE Hearing - Unconscious Volume doesn't work for incoming incoming radio transmissions

### ISSUE THREAD

**Issue by Churrofighter** [acemod/ACE3#6392]
**Arma 3 Version:** `1.82.144710` (stable)
**CBA Version:** `3.7.1.180604` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- ACRE2 (or TFAR)
```

**Description:**
ACE Hearing: Unconscious Volume doesn't work for incoming incoming radio transmissions

**Steps to reproduce:**
- Set Unconscious Volume to 0
- Get shot
- Hear all the radio transmissions you want but not the person next to you talking in direct speech

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**Comment by jonpas** [comment]
> Set Unconscious Volume to 0

I forgot this exists! :D

**Comment by dedmen** [comment]
https://github.com/acemod/ACE3/blob/ffaa195fe576625f052eeee04b1af9f3f377434f/addons/common/functions/fnc_setVolume.sqf This is setting the volumes. And afaik that's the only place. It only has two levels. I don't know how it would only mute direct speech but not radios

**Comment by Phyma** [comment]
or we could put a isDisabled check in if the player should be muted? @jonpas 

https://github.com/IDI-Systems/acre2/blob/master/addons/sys_core/fnc_isMuted.sqf#L26-L31

**Comment by thojkooi** [comment]
Is this still an issue?

**Comment by jonpas** [comment]
ACRE2 v2.6.2 should have a fix for this, ref. https://github.com/IDI-Systems/acre2/pull/600
