### ISSUE TITLE
ACE Compat files required

### ISSUE THREAD

**Issue by WastedMike** [acemod/ACE3#6398]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
-I have an issue with ACE3 where it required the RHS compat files to join but I don't have them on the server. I have also tried deleting the optional folder in ace on the server and there is no change.

**Steps to reproduce:**
- Run the server requiring CBA and ACE
- Use the Arma 3 launcher to view the server
- Noticed that the RHS compat files are under suggested even though the server isn't running them.

**Where did the issue occur?**
- Dedicated Server, Multiplayer

**Placed Modules:**
- None

**RPT log file:**
- https://pastebin.com/ZijQspmg

Is there a way to remove the ACE compat requirement for those that want to join my server while still using ACE?

(https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by commy2** [comment]
If you use RHS and ACE, you need RHS_compat_ACE.

**Comment by dedmen** [comment]
"It says I need the files but I don't have them"
"I even tried deleting them"
Deleting files that you need is not the best idea.

You should be using them.

**Comment by commy2** [comment]
^ Sounds reasonable to me.

**Comment by severgun** [comment]
By "use" they mean that you need to move files from optionals to addons folder.

**Comment by dedmen** [comment]
Yes. Or load the mod from the optionals folder.

**Comment by commy2** [comment]
Close?
