### ISSUE TITLE
ACE Arsenal Framework question

### ISSUE THREAD

**Issue by Doctor-Butts** [acemod/ACE3#6409]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Question:
What is the ACE Arsenal Framework analogue to the following BIS function?
bis_fnc_saveInventory_data

Or, how can I call up a player's private/local saved ACE Arsenal loadouts?

**Comment by alganthe** [comment]
> What is the ACE Arsenal Framework analogue to the following BIS function?
bis_fnc_saveInventory_data

This doesn't exist in ace arsenal.

> Or, how can I call up a player's private/local saved ACE Arsenal loadouts?

Very easy:
```
profileNamespace getVariable ["ace_arsenal_saved_loadouts", []]
```
This obviously has to be ran locally.

**Comment by Doctor-Butts** [comment]
Dang. Can't get it to work in the mission I'm editing. Thanks for the info, though!

**Comment by jonpas** [comment]
Instead of `bis_fnc_saveInventory_data` ACE Arsenal just uses `get/setUnitLoadout`, which is way more straightforward. :)

**Comment by mwpowellhtx** [comment]
Kindly, excuse the questions here, I know it's been a minute, but it seemed like the most appropriate issue to contribute toward.

Q: about the shapes of the data... obviously just visual inspection, the shapes seem a bit different. are these documented. obviously IIRC, BIS has docs for it. is it documented for ACE? Trimmed for brevity, the differences are apparent very early on...

Taking `"BIS_fnc_saveInventory_data"` for instance, which I think is mainly a flat array of array of _key/value pairs_, i.e. `[_key, _value, _key, _value, ...]`, `_key` being the loadout name, `_value` being the loadout itself. Shape is another animal entirely at this level discussion.

```
"bis loadout #1",[["U_B_CombatUniform_mcam",["FirstAidKit","Chemlight_green" ...
```

Whereas, by contrast, ACE appears to be persisting along similar, but slightly different, NVP lines, `[[_key, _value], [_key, _value], ...]`.

```
["ace loadout #1",[[["rhs_weap_sr25","rhsusf_acc_SR25S","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_USMC",["rhsusf_20Rnd_762x51_SR25_m993_Mag",20],[],"bipod_03_F_blk"],[],...
```

Or is loadout generally interchangeable, and I just need to be able to match each entry based one what I find... i.e. from `[_uniform, ...]` in one instance, to `[_primaryWeapon, ...]`, in the next instance?

Thanks...
