### ISSUE TITLE
NLAW causes "Picture not found" error message.

### ISSUE THREAD

**Issue by dpottavio** [acemod/ACE3#6410]
**Arma 3 Version:** `1.82.144710` (stable / rc / dev)
**CBA Version:** `3.7.1` (stable / dev + commit hash)
**ACE3 Version:** `3.12.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
If a player is equipped with an NLAW launcher, the first time access to the inventory menus is met with the following error message dialog box:

Picture equip\m\m_a3\ui_f\data\igui\cfg\targeting\empty_ca.paa.paa not found 

This only happens once.  Any subsequent access to the inventory does not produce this message.

**Steps to reproduce:**

1. Create an empty mission.
2. Add a Riflemen
3. Equip Riflemen with a NLAW from ACE Arsenal
4. Play as Riflemen and access the inventory.

**Where did the issue occur?**
This issues occurs in all environments.

**Placed Modules:**
None

**RPT log file:**
https://gist.github.com/dpottavio/95a764b0735a405a0d20297a2f07d85b

Line #908 contains the error message described in this ticket.

**Comment by dpottavio** [comment]
@commy2 I did notice the cfg definition you cited, but it's not clear to me what I can do.  Is there a way I can resolve this on my end?

**Comment by bux** [comment]
@dpottavio treat this as a "note to self"

**Comment by dedmen** [comment]
missing \ prefix?
https://github.com/acemod/ACE3/commit/90f92db01d4e463fc04dd0075039eb7f83989ff1#diff-28c619cce62f92ccf476c336b9bbfbe9R12 That too then.

**Comment by commy2** [comment]
Also note the `.paa.paa` in the error message.

>Is there a way I can resolve this on my end?

No, sorry. Just posting relevant stuff. I treat this as a bug tracker and less than a help forum.
