### ISSUE TITLE
Nyx (Autocannon) reload problems

### ISSUE THREAD

**Issue by MAD-BUG** [acemod/ACE3#6414]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.1` (stable / dev + commit hash)
**ACE3 Version:** `3.12.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- When reload setting is set to reload based on caliber size two things happens:
  1. In available ammo there are two lines named "20mm Shells" without identification of what type they are.
  2. When Nyx (Autocannon) reloaded with box of AP rounds it adds 400 rounds.
It could possibly be that problem lies somewhere here:
"2:25:19 "[ACE] ERROR: Undefined Ammo [B_20mm_AP : bin\config.bin/CfgAmmo/BulletBase]""

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer)

**RPT log file:**
https://pastebin.com/SyTx1Ees

**Comment by MAD-BUG** [comment]
Also this happen with this round "B_127x99_Ball". Also adds 400 rounds.

**Comment by ImplicitDeny** [comment]
A similar problem may have been spotted recently on the Marshall APC, with the coaxial machinegun : at the end of a mission, while resupplying our APC, we noticed that after loading only one MG rounds box in the vehicle, the gunner jumped from 15 rounds left to 415 rounds. But more tests are needed to firmly confirm this.
