### ISSUE TITLE
ACE Laser Guided Mavericks trajectory

### ISSUE THREAD

**Issue by mwpowellhtx** [acemod/ACE3#6416]
* For LOAL DIR, the AG missile takes a nasty curve at the very end of it's journey and misses the target entirely hitting the ground. It may disable tires on things like GAZ, etc, but it would miss armored units altogether.

Methinks this trajectory is probably a bug.

* Also, how do I change the LOAL?

Typical scenario for me is KP Liberation with ACE.

Thanks!

**Comment by bux** [comment]
Why did you delete the issue template and don’t give as ANY information on which versions you are using and the RPT file we request?

**Comment by tbeswick96** [comment]
Has been fixed, will be in next version https://github.com/acemod/ACE3/pull/6315

**Comment by mwpowellhtx** [comment]
@bux Excuse me? Latest ACE version, as far as I know, as published (and subscribed) via Steam. My problem description is as much as I can provide.

@tbeswick96 Thanks for the update. @bux Would the authors consider the PR please? Thanks!

**Comment by tbeswick96** [comment]
If you look at the linked PR, it has been merged, and will be in 3.13.0

**Comment by mwpowellhtx** [comment]
@tbeswick96 Any idea as to a time frame for 3.13.0 release?

**Comment by tbeswick96** [comment]
Nope, when it's ready :)

**Comment by jonpas** [comment]
Closing as duplicate of #6311.

**Comment by mwpowellhtx** [comment]
@jonpas Fair enough; I will be anxiously awaiting. This is a pretty gnarly one, IMO, to have sitting dormant in master.
