### ISSUE TITLE
Task: add recoil to mk6 mortar

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#6417]
after firing the mk6 mortar we need to account for the recoil of the tube in changing the ELEV and azimuth by a certain (random) number. IRL e.g. during a salvo the gunner has to recheck azimuth and ELEV after every shot.

charge 0 -> lesser recoil
charge 2 -> more recoil

whereas the first shot after assembling/moving produces the strongest recoil as the base plate is being pressed into the ground (maybe check for type of ground beneath the mortar)

**Comment by 654wak654** [comment]
[Recoil ](https://i.imgur.com/UJGbDoc.gifv) you say?

**Comment by bux** [comment]
> Recoil you say?

![https://i.kym-cdn.com/entries/icons/mobile/000/022/900/704.jpg](https://i.kym-cdn.com/entries/icons/mobile/000/022/900/704.jpg)

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
