### ISSUE TITLE
Players in virtual ace spectator slots cannot hear alive players

### ISSUE THREAD

**Issue by Bummeri** [acemod/ACE3#6418]
**Arma 3 Version:** latest stable
**CBA Version:** 3.7.1.180604
**ACE3 Version:** 3.12.2

**Mods:**
```
- CBA_A3
- ace
-TFAR - Version 1.0.295
```

Let me start by saying that I am not really sure if the problem lies in TFAR or ACE or both. I know @dedmen frequents ACE3 github also so I started by posting about it here.

**Description:**
-Players in virtual ace spectator slots cannot hear alive players when using TFAR. This differs from player who die and are taken to ace spectator. They can hear alive players.

**Steps to reproduce:**
- Add ace virtual spectator slot to the mission
- Take the slot
- Test hearing alive players

**Where did the issue occur?**
- Dedicated

**Comment by dedmen** [comment]
TFAR bug.

**Comment by dedmen** [comment]
>I know @dedmen frequents ACE3 github also so I started by posting about it here.

Yeah... But I'm a tiiiiny bit more present at TFAR github.
