### ISSUE TITLE
Fences, that do not work with the wire cutter

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#6420]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.1` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- australia map
```

**Description:**
- Some fences from Vanilla and Apex-DLC can't be cut with the wire cutter. And fences on the australian map, which use the same 3d-model of vanilla can't be cut, as well.

here the 3d models + classnames (Vanilla):
netfence_01_m_4m_f.p3d "Land_NetFence_01_m_4m_F"
netfence_01_m_8m_f.p3d "Land_NetFence_01_m_8m_F"
netfence_02_m_2m_f.p3d "Land_NetFence_02_m_2m_F"
netfence_02_m_4m_f.p3d "Land_NetFence_02_m_4m_F"
netfence_02_m_8m_f.p3d "Land_NetFence_02_m_8m_F"
wiredfence_01_4m_f.p3d "Land_WiredFence_01_4m_F"
wiredfence_01_8m_f.p3d "Land_WiredFence_01_8m_F"
wiredfence_01_16m_f.p3d "Land_WiredFence_01_16m_F"
slums01_8m.p3d "Land_Slums01_8m"

(Australia-Map):
indfnc_3_f.p3d "xcam_IndFnc_3_F"
indfnc_3_hole_f.p3d "xcam_IndFnc_3_Hole_F"
indfnc_9_f.p3d "xcam_IndFnc_9_F"
indfnc_corner_f.p3d "xcam_IndFnc_Corner_F"
mil_wiredfence_f.p3d "xcam_Mil_WiredFence_F"
net_fence_4m_f.p3d "xcam_Net_Fence_4m_F"
net_fence_8m_f.p3d "xcam_Net_Fence_8m_F"
new_wiredfence_5m_f.p3d "xcam_New_WiredFence_5m_F"
new_wiredfence_10m_f.p3d "xcam_New_WiredFence_10m_F"
slums01_8m.p3d "xcam_Slums01_8m"
sportground_fence_f.p3d "xcam_SportGround_fence_F"
sportground_fence_nolc_f.p3d "xcam_SportGround_fence_noLC_F"
plot_provizorni.p3d "WireFence"
plp_ctm_partitioningfencegrey.p3d "plp_ctm_PartitioningFenceGrey"
fence.p3d "Land_Fence"

**Comment by shukari** [comment]
Added:
- Land_NetFence_01_
- Land_WiredFence_01_
- all xcam Australia things

Discussion:
- [Land_NetFence_02_](https://community.bistudio.com/wikidata/images/1/1e/Land_NetFence_02_m_2m_F.jpg) (50% netfence, 50% beton, i dont know if this is ok)

**Comment by madpat3** [comment]
i wasn't quite sure about it, either.
the idea was, that you could at least cut through the fence and climb between the iron frame bars. 
well, in arma the whole wall would collapse, because of engine limitations.
