### ISSUE TITLE
Difficult to defuse naval mines in first person.

### ISSUE THREAD

**Issue by senevoldsen** [acemod/ACE3#6427]
**Arma 3 Version:** `1.82` stable
**CBA Version:** `3.7.1` stable
**ACE3 Version:** `3.12.2` stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
It is very difficult to defuse the Moored Mine in first person as a diver if you have a weapon. You have to get really close and touch the mine. This is all but impossible if you have a weapon since you cannot lower it, and it pushes you away when you try to interact. The best "workaround" is to get on the side of it, press interact, then look to your side onto the mine using freelook and then you can activate it.

**Steps to reproduce:**
Place moored mine. Go as diver (with engineering/defuse ability). Try to Defuse mine in first person with a weapon in hand.

**Where did the issue occur?**
Editor (Singleplayer)

**Placed Modules:**
None

**RPT log file:**
This is a usability issue, so I have omitted RPT.

**Comment by shukari** [comment]
Here a snippet for a custom workaround with custom range:
```
["ACE_DefuseObject", 0, ["ACE_Defuse"]] call ace_interact_menu_fnc_removeActionFromClass;
["ACE_DefuseObject_Large", 0, ["ACE_Defuse"]] call ace_interact_menu_fnc_removeActionFromClass;
["ACE_DefuseObject", 0, [], [ 
    "ACE_Defuse", 
    "Defuse", 
    "\z\ace\addons\explosives\UI\Defuse_ca.paa", 
    {[_player, _target] call ace_explosives_fnc_startDefuse}, 
    {[_player, _target] call ace_explosives_fnc_canDefuse}, 
    nil, 
    nil, 
    nil, 
    4
] call ace_interact_menu_fnc_createAction, true] call ace_interact_menu_fnc_addActionToClass;
```
The range is the 4 at the penultimate code line ^^

**Comment by senevoldsen** [comment]
Thanks, that is actually very useful workaround, since I might need the ability soon for a session.

Though, I still hope the ACE team will see this, and consider tweaking the range a bit. I think it might be because `GVAR(size)` is not set to `1` in the config. If it was, it looks like the interact range would be 2m rather than 1m (though why not make it a range instead if non-zero?).
