### ISSUE TITLE
changing the role of first-aid kit and surgical set

### ISSUE THREAD

**Issue by SimichRE** [acemod/ACE3#6431]
**Arma 3 Version:** `1.82.144710` (stable)
**CBA Version:** `3.7.1.180604` (stable)
**ACE3 Version:** `3.12.2.33 (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The surgical set heals not completely
leaves lameness and swing of hands
First aid kit eliminates all effects completely
it may be worth changing their roles among themselves?

**Comment by dedmen** [comment]
>it may be worth changing their roles among themselves?

No. If you stitch your wounds so they don't reopen. Are you automatically completely healed and all your pain goes away?

**Comment by SimichRE** [comment]
but surgical kit is more professional stuff as for me. Field medic can use first aid kit in battlefield to heal all wounds and pain, but to heal lameness and trembling hands he should to evacuate a fighter to the hospital where sergion with surgical kit can fully regain health including lameness and trembling hands etc. It looks more believable as for me.

**Comment by BaerMitUmlaut** [comment]
We won't suddenly switch what two items do.
