### ISSUE TITLE
AI is delaying fleeing because of uconsciousness

### ISSUE THREAD

**Issue by freghar** [acemod/ACE3#6433]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.1` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
The way ACE3 handles unconsciousness (camouflage) interferes with the (engine-based) AI decision making, in particular the "courage" setting. When an AI group takes losses, it is more likely to retreat (flee), however it would seem that units in ACE3's unconsciousness don't count as losses, so the group rarely retreats.

Not sure what the correct solution would be here, maybe using the vanilla `setUnconscious` which changes `lifeState`?

**Steps to reproduce:**
- Have AI unconsciousness enabled in medical settings
- Spawn two opposing groups of AI soldiers
- Set their courage skill to some average value (0.5)
- Make sure they engage in combat
- Set waypoints away from the combat area
- Observe when the units throw smokes / start fleeing

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**Comment by SilentSpike** [comment]
Rewrite is using `setUnconscious` so hopefully fixed there 👍

**Comment by PabstMirror** [comment]
Will double check later, but I think we are using `setUnconscious` so this issue should be closeable

**Comment by SilentSpike** [comment]
We are using `setUnconscious`
