### ISSUE TITLE
Comanche Script Error

### ISSUE THREAD

**Issue by meat147** [acemod/ACE3#644]
ACE3 Version: 3.x.x - e54d8d

**Mods:**
* @cba_a3
* @ace3
* TFAR

**Placed ACE3 Modules:**
* *None

**Description:**
Script error when disabling/enabling Laser Marker in the ACE Comanche.

**Steps to reproduce:**
Go into the Editor
Place the ACE_Comanche_Test
Select player as Gunner

**RPT log file:**
http://pastebin.com/JWTLyQvE
Line 658 / 693

**Comment by PabstMirror** [comment]
There was an extra space in a macro, that often causes `Local variable in global space`.  I think it's fixed but cannot verify.

**Comment by meat147** [comment]
will do

**Comment by meat147** [comment]
@PabstMirror fixed can be closed

**Comment by jaynus** [comment]
thx @PabstMirror
