### ISSUE TITLE
ACE frag enabled on RHS flashbang ect

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#6445]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `v3.7.1.180604` (stable)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS RBG
- + lots of other stuff
```

**Description:**
- ACE frag is enabled on RHS flash, CS, and Concussion grenades

**Steps to reproduce:**
- run with rhs, ace, and the rhs compat, throw a cs (or one of the other 2) grenade and get frag damage and you will receive frag damage. 

**Where did the issue occur?**
- Dedi

**Placed Modules:**
- None

**Comment by dedmen** [comment]
Shouldn't be <https://github.com/acemod/ACE3/blob/master/optionals/compat_rhs_usf3/CfgAmmo.hpp#L250-L264> 🤔

**Comment by Snak3Doc** [comment]
Yea checked that before reporting, but we regularly have to heal ai and players from flashbangs or sometimes it outright kills ai especially those with no form of armor, maybe it's not frag per say but there is definitely some damage happening and it's not minor scapes.

**Comment by jokoho48** [comment]
that is not a Frag bug nor an Ace bug. that is an RHS issue. all those RHS grenades make a very small amount of damage even with just RHS loaded and the ACE Medical system just gets triggered by that damage.
also, the Concussion grenade is currently broken and makes full damage like a full hand grenade

**Comment by PabstMirror** [comment]
frag isn't enabled,
you take damage as well without ace loaded
