### ISSUE TITLE
Advanced Throwing does not work on a fresh loadout load

### ISSUE THREAD

**Issue by FUZZYMANBOOB98** [acemod/ACE3#6457]
**Arma 3 Version:** `1.82` stable
**CBA Version:** `3.7.1' stable
**ACE3 Version:** `3.12.2' stable

**Mods:**
```
- CBA_A3
- ace
- RHS AFRF
- RHS USAF
- RHS GREF
- ace compat (for RHS mods)
- ace_grenades was removed from the version we are playing to reduce redundancy
```

**Description:**
-    While playing Antistasi, my friend and I cannot use advanced throwing on a fresh spawn loadout from the arsenal, confirmed that the loadout includes grenades. When pressing "CTRL+G" to bring up advanced throwing, a small model of the grenade appears in red and the menu is never brought up. 
     This is true for grenades added by RHS mods and vanilla grenades, on the condition that they are from a loadout. If I apply the loadout, then drop the grenade on the ground, put it in a vehicle, or otherwise remove it from my inventory then pick it back up, advanced throwing begins working again.
     This was also true back in version 3.10 for us.

**Steps to reproduce:**
- Create a loadout including grenades, save the loadout. Die, respawn, then load the loadout from the arsenal. Advanced throwing will not work until a grenade is removed the returned to the inventory.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Placed Modules:**
- None

**Comment by alganthe** [comment]
Can you reproduce the issue with only ace and cba?
Do you have a reproduction scenario that doesn't include a heavily scripted mission like antistasi?

**Comment by FUZZYMANBOOB98** [comment]
Could not reproduce the issue at all while I hosted server, both in Antistasi and mission editor, with all mods and with only ace + CBA.

I meant BI Virtual Arsenal, not ACE Arsenal. Will attempt to reproduce with friend hosting.

**Comment by PabstMirror** [comment]
I think there might be bugs with `currentThrowable` if the items are removed.
Does the correct grenade type show up in the weapon info pannel? Does the vanilla cycle greande keybind fix the problem?
