### ISSUE TITLE
AI vehicle gunners continue to fire despite unconscious 

### ISSUE THREAD

**Issue by GingerNinju** [acemod/ACE3#6460]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.1` (stable / dev + commit hash)
**ACE3 Version:** `3.12.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Shooting an AI that is mounting/controlling a gun in a vehicle, rendering him unconscious, will not make his gun cease operating. Continues to aim, fire and reload just fine, until the AI has bled out. 

**Steps to reproduce:**
- 1. Enable revive for AI
- 2. Shoot AI gunner in vehicle
- 3. Despite being unconsious the AI gunner continues to fire.

Video: https://youtu.be/les093WTOBg (Warning! Loud Gunfire!)

**Where did the issue occur?**
-  Singleplayer / Editor (Singleplayer) 

**Placed Modules:**
None

**Comment by alganthe** [comment]
That gunner isn't unconscious, he's dead.

I'm sorry to tell you this but your arma 3 install needs an exorcism.

**Comment by GingerNinju** [comment]
I wanted to be able to revive my AI teammates in the campaign. Seems I can't turn that on for just my team, as far as I can tell. With revive on everyone goes to revive state everytime until they bleed out. I'm starting to think it's not worth it. Seems a little wonky.... So the gunner goes to revive state, and I guess his muscle memory kicks in and he just continues to fire.

Isn't it supposed to behave like this with those settings? (apart from the muscle memory ofc) So I don't think it's my arma 3 install... But hell, I could call a priest and see if he can sort it out.

**Comment by alganthe** [comment]
No, AI gunners shouldn't be able to keep firing and operating their turret thanks to the power of CSAT magic, there seem to be an issue.

The AI goes unconscious but for some reason they retain their ability to fire

**Comment by GingerNinju** [comment]
I tried out the same with an HMG Fennek as well. Fairly certain I shot the gunner through the window till his head was hanging. Turret on top was still operating as usual.

**Comment by alganthe** [comment]
Correction, issue happens on all vehicles, medical rewrite is around the corner, not sure if it's worth fixing.

**Comment by DavidosWolfe667** [comment]
What the fuck do you mean 'not worth it', the AI can just continue mowing people down from cars while being knocked out, do you have any idea how broken that is?!

**Comment by commy2** [comment]
Rude language.
