### ISSUE TITLE
Weird damage stacking in medical rewrite

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#6463]
**Arma 3 Version:** `1.82` stable
**CBA Version:** `3.7.1` stable
**ACE3 Version:** `3.12.3` medical-rewrite branch 10a988836d6a31dfcc43d790d1d36bb50888169b

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- You can shoot a person in the torso, legs and arms, an unlimited amount of time, they will not die from either the bleeding nor cardiac arrest nor damage, however head wounds seem to work.

**Steps to reproduce:**
- Get shot, a lot.

**Where did the issue occur?**
- SP

**Placed Modules:**
- (maybe we should update this part)

**RPT log file:**
- https://gist.github.com/alganthe/58d1e68f3ce93bbcdd8cf1119003e48b RPT and medical settings (default but we never know)
- https://imgur.com/a/peKNcwg imgur album

**Comment by PabstMirror** [comment]
see https://github.com/acemod/ACE3/issues/5510

**Comment by alganthe** [comment]
I'm pretty sure someone who has absolutely no fluid in their body would be dead, or that has enough velocity wounds that they don't have a chest anymore.

Please look at the amount of wounds and their vitals, i'm pretty sure this isn't normal.

![image](https://i.imgur.com/K6i0CPN.png)
![imag2](https://i.imgur.com/jPazWjQ.png)

**Comment by SilentSpike** [comment]
Duplicate issue, please use #5510
