### ISSUE TITLE
Tourniquet has the same icon as bandages on medical-rewrite branch

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#6464]
**Arma 3 Version:** `1.82` stable
**CBA Version:** `3.7.1` stable
**ACE3 Version:** `3.12.3` medical-rewrite branch 10a988836d6a31dfcc43d790d1d36bb50888169b

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The tourniquet have the incorrect icon

**Steps to reproduce:**
- Try to apply a bandage via interaction / self interaction

**Where did the issue occur?**
- SP

**Placed Modules:**
- (maybe we should update this part)

**RPT log file:**
Not needed

**Comment by mharis001** [comment]
Will be fixed by #6831 .
