### ISSUE TITLE
Mines armed with ace appear at different height in the ground to other clients

### ISSUE THREAD

**Issue by Snak3Doc** [acemod/ACE3#6469]
Arma 3 Version: 1.82 (stable)
CBA Version: v3.7.1.180604 (stable)
ACE3 Version: 3.12.2 (stable)

Mods:

- CBA
- ACE
- TFAR
- RHS RBG
- Lots of other stuff

**Description:**
When a player arms an AT/AP mine, it will appear at a different height (y axis) in the ground to all other clients on the server, it's at the correct height in the ground for the person who arms it but everyone sees it lower in the ground (barely visible) or its completely underground, although the other clients can detect it and defuse it.

Spot the difference ;) https://i.imgur.com/mPuos05.jpg (LH Picture was taken by the person who armed the two M15's)

PS: 
- It effects all AT/AP mines, but not ied's. 
- The only ones that are visible to other clients are the taller models eg the RHS TM62-M (orange 
         top) in the above image.

**Steps to reproduce:**
- Connect to a dedi server with multiple clients.
- Place two M15 AT mines on the ground arm one with ACE and the other with Scroll Wheel.
- The mine armed with vanilla will only have the inner ring visible for both the person who armed it and 
   the other clients > https://i.imgur.com/CXp2ifN.png
- The mine armed with ace will have the outer ring visible and sit only just in the ground for the person 
  who armed it > https://i.imgur.com/8tnKKxY.png but will be completely underground to other clients.
- Repeat process with other mines = same results.
- I haven't tested if this happens with Zeus placed mines as well.

**Where did the issue occur?** 
- Dedicated

**Placed Modules:**
- Fortify

**RPT log file:**
- Will add later

**Comment by 654wak654** [comment]
Could this have been by design? Whoever made this could've done it as a gameplay mechanic, where the mines get "buried". Since the person who put them down know where they are, they're still visible to them.

**Comment by Snak3Doc** [comment]
If that's the case it makes no sense (not sure if that's what jonpas means). 
The engineer sees it practically sitting on the surface, but for everyone else it's invisible.. The amount of FF incidents I've seen with the engi getting blamed for bad directions when in reality the other players had no hope of seeing the mines he's placed.

**Comment by Snak3Doc** [comment]
All mines from vanilla and rhs, the hight of the model effects if it's completely buried or visible for other clients (why i think its a bug) 
eg:
-The M15 is invisible when placed through ace, but the VS50 has just the tip of the pressure plate showing (looks like a sticker on the ground) for the people who didn't place it.
-The bouncing betty is higher for other players than the person who placed it.
-The RHS PFM-1 is floating for other clients but is on the surface for the person who arms it.

**Comment by 654wak654** [comment]
If it's that sporadic + if there is nothing in the code that differentiates local and global, I don't think my train of thought is valid anymore. Though if communicated correctly it did sound like a cool idea.

**Comment by Phyma** [comment]
Since the author of the issue stated that this does not happen to IEDs then i think it's `_digDistance` that messes somethings up.

https://github.com/acemod/ACE3/blob/81e02a73369d341ef21d0b8fc1ad9c62e1688f2e/addons/explosives/functions/fnc_placeExplosive.sqf#L67

**Comment by Nemesi-BDR** [comment]
Any hope or plan to have this issue fixed? This issue makes mines unusable especially for TvT ops (as already someone commented in the closed ticket)!

**Comment by Nemesi-BDR** [comment]
Along with 

> If it's that sporadic + if there is nothing in the code that differentiates local and global, my train of thought isn't valid anymore. Though if done correctly it is still a cool idea.

I think it could be a cool idea if it could be possible to differentiate between surfaces, i.e. you can bury the mine (= mines are invisible, still visible to those who placed them) on dirty roads or grass, but not on asphalt or concrete. That would be very cool!

**Comment by johnb432** [comment]
I'm unable to reproduce any of the described issues, be it in self-hosted or dedicated MP (ACE 3.17.1 and current master).
I'm going to consider it no longer an issue. If it is, reopen a new issue with reproduction steps with CBA + ACE only.
