### ISSUE TITLE
Explosive: ACE placing explosive throw errors

### ISSUE THREAD

**Issue by Vdauphin** [acemod/ACE3#6475]
**Arma 3 Version:** `1.82.144710` (stable)
**CBA Version:** `3.8.0` (RC2)
**ACE3 Version:** `3.12.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Errors when you place an explosive with ace 3 interaction system

**Steps to reproduce:**
- Take an explosive
- Interact with you 
- Select the explosive you want to place
- Errors appearing:
```
17:09:20 Error in expression <







































params [["_baseFOV", 0.75, [0]]];

priva>
17:09:20   Error position: <params [["_baseFOV", 0.75, [0]]];

priva>
17:09:20   Error Params: Type Tableau, Nombre attendu
17:09:20 File \x\cba\addons\ui\fnc_getFov.sqf [CBA_fnc_getFov], line 5736
17:09:20 Error in expression <
```

**Where did the issue occur?**
- Tested on Dedicated

**Placed Modules:**
- None

**RPT log file:**
- [Arma3_x64_2018-07-28_16-08-50.zip](https://github.com/acemod/ACE3/files/2238208/Arma3_x64_2018-07-28_16-08-50.zip)

**Comment by PabstMirror** [comment]
https://github.com/CBATeam/CBA_A3/pull/944

ACE does `(call CBA_fnc_getFov)` which implicitly passes `_this` which isn't a number
Before CBA checked `private _zoomRef = if (IS_SCALAR(_this)) then {_this} else {0.75};`
Now it throws params error
