### ISSUE TITLE
Singleplayer saves

### ISSUE THREAD

**Issue by Samwangyan** [acemod/ACE3#6477]
**Arma 3 Version:** `1.82.144710` (stable / rc / dev)
**CBA Version:** `3.7.1` (stable / dev + commit hash)
**ACE3 Version:** `3.12.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- enabled ACE3, save game not work. When save game w/o ACE3, game load save correctly.

**Steps to reproduce:**
- in any campaign / single scenario game
- Save game (manually or auto)
- Load last save game
- After loading there is a black & white static scene screen

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Singleplayer

**RPT log file:**

[Arma3_x64_2018-07-29_10-32-05.rpt.txt](https://github.com/acemod/ACE3/files/2238630/Arma3_x64_2018-07-29_10-32-05.rpt.txt)

**Comment by Samwangyan** [comment]
- retry with just ace3 and cba, same result

[Arma3_x64_2018-07-29_11-48-25.rpt.txt](https://github.com/acemod/ACE3/files/2238649/Arma3_x64_2018-07-29_11-48-25.rpt.txt)

**Comment by alganthe** [comment]
You have logging disabled, this RPT is unfortunately not of any use,

**Comment by dedmen** [comment]
Btw the parameters `cpuCount=8 -exThreads=7 -enableHT -maxmem=16269 -maxvram=8192` are all useless.

**Comment by commy2** [comment]
No proper log. Also not tried the same with only CBA vs CBA + ACE.

**Comment by Samwangyan** [comment]
Problem Solved:
Enable the logging through Launcher option
save and load the game, same problem occurred with the notice that game lack of some pbo files, 
download the necessary mods and re-try,
bingo.
