### ISSUE TITLE
Basic medical: Inject plasma actions are displayed

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#648]
Medical System Level: Basic
Prevent insta death: true

I always got actions available to inject plasma, even when I wasn't carrying the item and was in basic medical. This actions should be removed.

**Comment by commy2** [comment]
Self menu also got entries for check pulse / blood pressure. Doubt they do anything in basic.

**Comment by esteldunedain** [comment]
Will be fixed in 9670267d2001cf7bd8aeb61f65546d250a2e3f63 as soon as it gets merged.

**Comment by Glowbal** [comment]
Fixed in #717
