### ISSUE TITLE
"H" not opening patient's medical menu

### ISSUE THREAD

**Issue by TauMaxim** [acemod/ACE3#6488]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.1` (stable / Steam release)
**ACE3 Version:** `3.12.2` (stable / Steam release)

**Mods:**
```
https://steamcommunity.com/sharedfiles/filedetails/?id=1423382205
```

**Description:**
- The error came out of no where. One day the medical menu was working just fine, but then the next day it didn't work like it's supposed to. When ever I press H to open the medical menu, it just shows my own menu instead of the patient's. I have the medical menu turned on, I have not rebound the key to open the menu, and it works for the rest of my unit. I can open the medical menu by interacting with the patient through the interaction menu, but that leaves me selecting the wrong thing far too often and really isn't a good workaround. 

I have deleted Arma and reinstalled it, but the but still persist.

UPDATE: Seems like it's not only me that's having this problem in my unit, others seem to have it as well.

**Steps to reproduce:**
- N/A

**Where did the issue occur?**
- Dedicated

**RPT log file:**
https://pastebin.com/WQAti0Tq
https://pastebin.com/EVKUfFWM

**Comment by PabstMirror** [comment]
medical menu still uses `cursorTarget`, we might want to swap it for `cursorObject`

if you immediately go up to a unit, your character sometimes doesn't have enough knowledge about a unit and cursorTarget will return null; but there also are cases where `cursorTarget` works better, like when looking to the side of a object

![20180802095618_1](https://user-images.githubusercontent.com/9376747/43592158-909e91ac-963a-11e8-829b-6986e705e3a7.jpg)

**Comment by TauMaxim** [comment]
"your character sometimes doesn't have enough knowledge about a unit "

Could you be so kind and elaborate? And is there an ETA on this change? Also on a side note, is it possible to dissable certain ACE nodes on characters? I'm fine with H not working properly, but using the interaction menu often leads to me clicking something else than the medical menu.

**Comment by PabstMirror** [comment]
https://community.bistudio.com/wiki/cursorTarget

>Returns the target pointed at by the player (usually with cross-hairs). The target has to be known to the player to some degree (knowsAbout > 0). If target is completely unknown, command returns objNull. 

Fix should be easy, 
check cursorObject, 
if bad check cursorTarget, 
if bad use player
