### ISSUE TITLE
ACE and Real Life

### ISSUE THREAD

**Issue by antonome** [acemod/ACE3#6489]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Hi there

I have been a paramedic for a number of years, have a degree in Emergency Medicine and Rescue. Just wanted to give some feedback regarding some of the ACE Medical procedures:

For a resus (patient unconscious with no heart rate) I think the procedure should be the following to revive them:
Establish the patient is in a unconscious and no heart rate state
As the patient is in this state due to bleeding and hence hypovolaemic shock, wounds should be bandaged first to stop the bleeding
An Infusion of some kind need to happen before the patient goes in a state where he can be revived
CPR should be performed to prolong the revivable state
After the IV and Bandages, the patient is now in a revivale state. It is virtually impossible to revive someone with only CPR and Epinephrine.
A sequence of Shocks via a defibrilator should be delivered to get the heart started at 360J
For ingame I would suggest:

Deliver 1st Shock (25% chance of revival)
Give epinephrine
Deliver 2nd Shock (50% chance of revival)
Give Epinephrine
Deliver 3rd Shock (75% chance of revival)
Give Amiodorone, as the patient is now in a persistant Ventricular Fibrilation.
Deliver 4th Shock (100% chance of revival)
Adenosine does not slow the heart, it actually stops the heart for 10 seconds. This is usually a treatment for a very specific supraventricular tachycardia and is not useful in a trauma case. Atropine does not slow the heart, it actually increases the heart rate by blocking the parasympathetic nervous system. Also never used in a trauma case.

Epinephrine by injection should not be used to increase the BP. If given via IV, it will probably kill a live patient, and given IntraMuscular (like we do in ARMA) it is almost impossible to know what the effect is. I would recommend that BP can be increased by IV. Epinephrine can be used to increase BP, but only if you titrate it through an IV and can manage it per drop rate.

ACE Medical is a great MOD! Keep up the good work!

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by dedmen** [comment]
>I would recommend that BP can be increased by IV.

You could just hold the IV in the hand and press on it right?

**Comment by TheMagnetar** [comment]
Hmmm, regarding the chances of revival. You would always recover a unit no mater what after 4 shocks...

**Comment by severgun** [comment]
@TheMagnetar I think this is just concept. It can be rescaled to 10% 25% 50% 75% or less.

**Comment by antonome** [comment]
Exactly. it is only a concept.  @dedmen That would be nice, however I am only suggesting some improvements within the limitations of the game.  Of course injecting Epinephrine is more practical to get the BP up in game.  Doing an IV takes a bit longer.  Question is do be more gamey or more Milsim I guess.

**Comment by commy2** [comment]
Horrible issue name.
