### ISSUE TITLE
Basic medical: Check pressure actions are displayed

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#650]
Medical System Level: Basic
Prevent insta death: true

Check pressure actions are displayed in various limbs. AFAIK this actions have no use on the basic medical system. I assume the "check pulse" action should be use instead to distinguish between dead and alive units, right? In that case I think the "check pressure" actions should be hidden

**Comment by KoffeinFlummi** [comment]
"Check pressure" is used to determine how much blood a unit has lost; That's needed in basic as well.
