### ISSUE TITLE
ace arsenal: trouble with uav terminals

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#6501]
**Arma 3 Version:** `1.84` stable
**CBA Version:** `3.8.0` stable
**ACE3 Version:** `3.12.2` stable

**Mods:**
```
- CBA_A3
- ace
- TFAR
- Enhanced Soundscape
- Dynasound
```

**Description:**
UAV Terminals aren't selected properly
![image](https://user-images.githubusercontent.com/1235520/43676352-c0d4396a-97ef-11e8-9e9d-99f85f5083e4.png)

**Where did the issue occur?**
- Dedicated

@alganthe

**Comment by alganthe** [comment]
BI seems to have added back NVGoggles to assignedItems and changed the terminal simulation type
