### ISSUE TITLE
Question: custom actions overlapping with dragging action

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [acemod/ACE3#6505]
I am trying to add custom actions to an object via config, and also make it draggable. Trouble is the actions overlap in game. I must be doing something wrong but I don't know what and the wiki only has examples of self actions for config actions. Some help and light on my issue would be greatly appreciated! Here's what I have in my cfg vehicles:

class Land_Map_blank_F;
class MRH_MapObject: Land_Map_blank_F {
	author = "Mr H";
	scope = 2;
	scopeCurator = 2;
	displayName = "MRH_MapObject";

	ace_dragging_canDrag = 1;  // Can be dragged (0-no, 1-yes)
        ace_dragging_dragPosition[] = {0, 1.2, 0};  // Offset of the model from the body while dragging (same as attachTo)
        ace_dragging_dragDirection = 0;  // Model direction while dragging (same as setDir after attachTo)

        // Carrying
        ace_dragging_canCarry = 1;  // Can be carried (0-no, 1-yes)
        ace_dragging_carryPosition[] = {0, 1.2, 0};  // Offset of the model from the body while dragging (same as attachTo)
        ace_dragging_carryDirection = 0;  // Model direction while dragging (same as setDir after attachTo)
		class EventHandlers {
		init = "_this call MRH_fnc_MilsimTools_EnhancedMap_setMapTexture;";
		
	};
	/////
	
	class ACE_Actions {
		
		class ACE_MRH_MapActions 
		{
			displayName = "Map actions";
			icon = "";
			distance = 2;
			selection = "mem01";
				class LookAt {
					displayName = "Look at the map";
					condition = "true";
					exceptions[] = {};
					statement = "call MRH_fnc_MilsimTools_EnhancedMap_lookAtMap";
					icon = "";
					//selection = "mem01";
					//distance = 2;
				};
				
				class Fold {
					displayName = "Fold and collect map";
					condition = "true";
					exceptions[] = {};
					statement = "[_target] call MRH_MilsimTools_EnhancedMap_collectMap;";
					icon = "";
					//selection = "mem01";
					//distance = 2;
				};
		}; 
	};
	
	

};

**Comment by Dystopian** [comment]
maybe you wanted `ACE_MainActions` class like here:
https://github.com/acemod/ACE3/blob/240046ceeeaf4ecfd52d3b6f8daf7c205ef7e33e/addons/reload/CfgVehicles.hpp#L26-L28

Anyway for such questions use [ACE slack](https://slackin.ace3mod.com/).

**Comment by MisterHLunaticwraith** [comment]
I have tried and it doesn't work (I might have done something wrong) anyway I'll do as you say and take it to the ace slack
