### ISSUE TITLE
setUnconscious force switching firing mode to Single.

### ISSUE THREAD

**Issue by severgun** [acemod/ACE3#6506]
**Arma 3 Version:** `1.84` (stable / rc / dev)
**CBA Version:** `3.7.1` (stable / dev + commit hash)
**ACE3 Version:** `3.12.2` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
ace_medical_fnc_setUnconscious force unit to change current weapon to primary one. This cause firing mode switch to "Single".

I think if you cover https://github.com/acemod/ACE3/blob/240046ceeeaf4ecfd52d3b6f8daf7c205ef7e33e/addons/medical/functions/fnc_setUnconscious.sqf#L76-L79
with `if (currentWeapon _unit != primaryWeapon _unit) then { ...` then it will work more gentle when unit already have primary weapon.

**Steps to reproduce:**
- Set primary weapon to Burst.
- call [player, true] ace_medical_fnc_setUnconscious;
- call [player, false] ace_medical_fnc_setUnconscious;
- Primary weapon at Single mode.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**Comment by commy2** [comment]
I don't see how the proposed line would solve this issue. It would infact introduce a different one. `currentWeapon`, despite it's name, reports the current muzzle and not the current weapon (grenade launchers etc.). `primaryWeapon` does always report a weapon. These would be incompatible with a `==` check.
The real fix should be reapplying the correct weapon mode and muzzle using `CBA_fnc_selectWeapon` or a similar implementation.

**Comment by severgun** [comment]
> I don't see how the proposed line would solve this issue.

Don't switch weapon if it is already primary. Not switched weapon will stay in selected mode.

> It would infact introduce a different one. currentWeapon, despite it's name, reports the current muzzle and not the current weapon (grenade launchers etc.).

That is why I did not make pull request and just suggest.

**Comment by Phyma** [comment]
@commy2 so there is no difference between currentWeapon and currentMuzzle?

That sounds like Bis bug that should be fixed.
