### ISSUE TITLE
Add replacement medic convenience setting

### ISSUE THREAD

**Issue by SilentSpike** [acemod/ACE3#6507]
We removed the old medic setting because it was ambiguous and the way in which it works was a little confusing (see [here](https://github.com/acemod/ACE3/issues/6452#issuecomment-406735649) and [here](https://github.com/acemod/ACE3/pull/6493)).

However, it's purpose was fairly convenient for cases where you want nobody/everybody to be able to perform all medical treatment by default.

**Comment by SilentSpike** [comment]
In private we discussed a setting more along the lines of who can perform treatment (everyone/medics/nobody) as it's more explicit to the user what it actually controls.

**Comment by jonpas** [comment]
Decided to not move forward with this, due to new clearer settings structure.
