### ISSUE TITLE
RHS marine units have incorrect positions for the leg selections

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#651]
The leg action points are displayed below the ground, as it used to happen for all models. I report it here because I'm not sure who needs to fix this, as it apaprently still happens on some vanilla unit too (e.g., blufor pilot). Maybe it's just that they are inheriting from the wrong class.

This issue is game breaking, cause it makes very difficult to correctly treat leg wounds. Maybe we should prevent those selection points to ever go below ground, but it would need an ugly hack.

**Comment by PabstMirror** [comment]
I don't think it got issued, but we found the same with either the a3 blufor pilot/crew uniform.

**Comment by jaynus** [comment]
I think a relative ATL check wouldn't be too hacky would it?

Additionally - how are leg wounds being treated standing? :p that mayto be looked at more so ....

It would make this not a big, at least

**Comment by esteldunedain** [comment]
> Additionally - how are leg wounds being treated standing?

The selections are way below ground (~0.5 m) even when the unit is prone/unconscious

**Comment by jaynus** [comment]
We should probably do a relative ATL check on all selections anyways; it would help avoid this, and could prevent future issues

**Comment by jaynus** [comment]
And it's 1 coordinate transform, that can't be very intensive or hacky? If ATL < 0.1 set it to 0.1

**Comment by esteldunedain** [comment]
> And it's 1 coordinate transform, that can't be very intensive or hacky? If ATL < 0.1 set it to 0.1

That hack could be included, although it's not perfect (what if the unit is on a two story building, climbed to a rock, underwater, paradropping, etc9.

There's an associated issue though: at least on RHS, when unconscious, the leg selections are shown below the center of mass of the units (as if it where standing), which is nowhere near the place the are supposed to be. That could maybe be hacked to, but things get more complicated.

**Comment by jaynus** [comment]
That sounds like genuine problems with the models then, which we should pass on to RHS.

I think a below ground check, now, is a bad idea - the models should be fixed by their creators. And we almost need to not hack it so they know it needs fixing.

Your right :) let's pass this to RHS and see if they'll fix it

**Comment by Jastreb** [comment]
By marine you mean USMC? I am not sure but I think that faction is still WIP.

https://dl.dropboxusercontent.com/u/8632965/USFinfographic3.pdf

point 04

**Comment by headedhorseman101** [comment]
I don't think it is RHS's fault, not saying it is the ACE team's either (I think it is BIS's fault), but I was having the same issue while using only @CBA_A3 v.RC6 and @ace3 (version present on armaholic for download) while placing vanilla items in Zeus Occured when trying to place small vanilla objects such as the docments, photos, top secret documents, and gaming console objects on top of the office desk (empty/objects[furniture]) and on the floor of the barracks structure at the military range on Stratis.

**Comment by esteldunedain** [comment]
> The objects seemed to rest on a point a couple inches below the desk and the floor, while I had no issues with the CSAT units I was placing.

That's totally unrelated. The bug was on bi config, and it was fixed for most units per our request. RHS is probably either inheriting from a broken BI class (they are stil some broken) or had copied the wrong configs from back then

**Comment by commy2** [comment]
>BIS's fault

**Comment by NouberNou** [comment]
This issue has been reopened: http://feedback.arma3.com/view.php?id=20761

Closing for now since this is technically not our bug, nor RHS's bug.

**Comment by esteldunedain** [comment]
:+1:

**Comment by jaynus** [comment]
RHS has fixed this on their end and SoulAssassin has provided fix details on the A3 tracker
