### ISSUE TITLE
Enabling quick mount should be a one-step process

### ISSUE THREAD

**Issue by jameslkingsley** [acemod/ACE3#6516]
Simple little suggestion for quick mount: at the moment to enable using quick mount the client has to bind the hotkey _and_ enable it in their ACE settings. Most people I run into have the issue of not knowing they need to enable it. Ideally it should just work off of the hotkey - dunno why I didn't make it like that from the start, but nevertheless it would be sweet.

**Comment by jameslkingsley** [comment]
That's an icky fix though

**Comment by dedmen** [comment]
Is there anything that speaks against "enabled by default" ?
