### ISSUE TITLE
Titan DIR mode can't deal any damage to enemy in some condition

### ISSUE THREAD

**Issue by Arkblade2015** [acemod/ACE3#652]
Mods:

@cba_a3
@ace3

Placed ACE3 Modules:
ace_javelin
ace_missileguidance

Description:
Titan DIR mode can't deal any damage to enemy in some condition.

Steps to reproduce:
goto editor (VR), place missile specialist (AT) to center.
place Namer to his front.
lock on and fire.

Where did the issue occur?
"Singleplayer"*

**Comment by jaynus** [comment]
Thanks. I've noticed this, the vehicles are getting hit but not exploding. They are receiving damage, but I think the hitpoint penetration is off.

@noubernou I was meaning to add slight frag to these rounds and the AP rounds; do you think frag would help penetration on the points?

**Comment by jaynus** [comment]
This is an issue with vanilla vehicle damage, and will be resolved once a new vehicle damage system is implemented.

Currently in some vehicles, it is landing under the bed of the vehicle (trucks) and not damaging it.
