### ISSUE TITLE
Portable lights' "turn on" function doesn't work on dedicated

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#6520]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.8.0` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- when on dedicated server, you can turn off portable lights (single/double), but you can't turn them on again.

**Steps to reproduce:**
- place portable lights (single and double) and a man on map and play the mission on a dedicated server. turn off the lights and try to turn them back on.

**Where did the issue occur?**
- Dedicated 

**Placed Modules:**
- None.

**RPT log file:**
[arma3server_6_2018-08-11_21-56-06.txt](https://github.com/acemod/ACE3/files/2280521/arma3server_6_2018-08-11_21-56-06.txt)

**Comment by Dystopian** [comment]
reproduced, I'll take it
