### ISSUE TITLE
Zeus does not get kick prompt as result of PBO Checking

### ISSUE THREAD

**Issue by neilzar** [acemod/ACE3#6526]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.8.0` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
- Any other mod not on the PBO whitelist
```

**Description:**
On our server we have the PBO Checking enabled to Check all and to kick on detecting an error. However, when someone is in a virtual Zeus slot (logic gamemaster slot) they will not get the prompt saying they are running the wrong mods. Therefore the Zeus cannot get kicked for using non-whitelisted mods. The script runs, as the systemchat error, listing the mods, does pop up.

It is important to note that due to the number of mods we have loaded, load times for Zeuses are quite high and the systemchat error shows up when the Zeus interface hasn't been loaded yet. I assume the error occurs because the interface is incorrect or is not loaded, but I don't know which interfaces are loaded for Zeus.

**Steps to reproduce:**
- Load a mod that isn't whitelisted
- Load into a Logic Game Master slot
- Observe error message in sidechat before Zeus display is visible.
- Once the display is loaded have no prompt show up.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
- [RPT Gist](https://gist.github.com/neilzar/acec857fd3bcd8d109c5f26b3e54ffe2)

**Comment by neilzar** [comment]
This is fixed, somehow. I do not see any changes to the code for PBO and file checking, but Zeus does get kicked from the interface and then shown the error message. I will have to check again in a mission, but loading into an empty server as Zeus has the desired effect.

**Comment by jonpas** [comment]
Closing then, please reopen if it still happens under some circumstance.
