### ISSUE TITLE
Main weapon is drawn out after any medical treatment

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#653]
Medical System Level: Basic
Prevent insta death: true

After medical treatment the main weapon is drawn out again even if no weapon was selected on the first place.

**Comment by Glowbal** [comment]
- [ ] store selected weapon when entering treatment.
- [ ] Select stored weapon in callback.

**Comment by Glowbal** [comment]
Fixed in #717. Caller will select weapon from before treatment upon success or failure.
