### ISSUE TITLE
time delta is incorrectly large when exiting cardiac arrest

### ISSUE THREAD

**Issue by SilentSpike** [acemod/ACE3#6530]
Issue revealed and discussed as part of #6523

Basically because vitals loop isn't ran as part of the cardiac arrest state, when you recover the time delta becomes large because the previously stored time was back before you entered cardiac arrest. This leads to some values trying to incorrectly change massively.

I see two potential solutions:
1. Run the vitals loop while in cardiac arrest (I think we might need to do this anyway because it looks like it updates some values unrelated to the heart rate)
2. Update the stored `GVAR(lastTimeUpdated)` value on the unit when exiting cardiac arrest

**Comment by thojkooi** [comment]
I think we should go with approach 1.

**Comment by SilentSpike** [comment]
For reference: https://github.com/acemod/ACE3/blob/c012941af02921d51eb6c2d73503fd2760eeb704/addons/medical_statemachine/functions/fnc_leftStateCardiacArrest.sqf#L24

**Comment by SilentSpike** [comment]
Refreshed my memory on this one.

The issue is that in statemachine, the cardiac arrest state doesn't have an `onState` function like the others which is where the calls are made to `EFUNC(medical_vitals,handleUnitVitals)`. This results in the time tracking used by that function not updating the variable on the unit - which leads to the big time delta if the unit becomes stable again.

The temporary fix currently implemented (see above) isn't even a valid fix because it should be `QEGVAR(medical_vitals,lastTimeUpdated)` 😄 I imagine the variable changed and that wasn't originally broken.

In terms of the solution to this, it depends whether handleUnitVitals updates anything independent of heart rate (although CPR also causes heart rate so that might be untrue). If it doesn't, then the "temporary fix" is enough because the loop doesn't need to be ran since we know nothing is changing while HR=0.

If it does, the fix would be to add an `onState` to cardiac arrest to call the vitals function and update the function so that only relevant code is executed while in cardiac arrest.

**Comment by commy2** [comment]
It bothers me that this issue is named "fix", but is not a pull request.

**Comment by SilentSpike** [comment]
Fixed by #7060
