### ISSUE TITLE
Vannilla action IS STILL presented to activate dropped or defused mines.

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#6534]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.8.0` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- referring to the issue: https://github.com/acemod/ACE3/issues/6342 and the pull request: https://github.com/acemod/ACE3/pull/6353, it should be fixed already, but isn't.
 
the scrollwheel action is still present on every mine, except for the "dummy mine" where it works as expected.
and by the way the "M4A1 SLAM" can't be defused savely, whether it was activated by scrollwheel or by ACE interaction.

**Steps to reproduce:**
- place an explosive specialist on map. give him a "bergen backpack" and put every type of explosive charge in it + a defuse kit.
now lay any type of mine on the ground, by just taking it out of your inventory. see the scrollwheel option, except for the case you chose the "dummy mine".

do this again, but now use the ace interaction for placing and activating the mine. see no scrollwheel option. but after defusing the mine, the scrollwheel option reappears, except for the case you chose the "dummy mine".

while the "M4A1 SLAM" behaves different, than all the other mines on defusing. it always explodes.

**Where did the issue occur?**
- Singleplayer.

**Placed Modules:**
- None.

**RPT log file:**
- [Arma3_x64_2018-08-16_11-46-37.txt](https://github.com/acemod/ACE3/files/2293353/Arma3_x64_2018-08-16_11-46-37.txt).

**Comment by BaerMitUmlaut** [comment]
I can't replicate this. Please reopen if this is still an issue and update your repro steps.

![20201102232100_1](https://user-images.githubusercontent.com/9693842/97925642-10c0bf80-1d62-11eb-8545-6382804c8f47.jpg)
