### ISSUE TITLE
ACE 3 User Interface - Overrides Server Profile Difficulty

### ISSUE THREAD

**Issue by BriCro** [acemod/ACE3#6537]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.8.0` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
- ACEX
- RHSUSAF
- RHSAFRF
- ACE COMPAT RHSUSAF
- ACE COMPAT RHSAFRF
- CUP Core
- CUP Terrains
- Project Opfor
- Old but gold Map Pack
- Task_force_Radio
- BackpackOnChest
- Isla Abramia
- Isla Duala
- Island Panthera
- Immersion Cigs
- ILBE Assault Pack
- Enhanced Movement
- Advanced Slingloading 
- NIArms All in One
- Wake Island
- Kunduz, Afghanistan - Fixed Doors
- GSTAVOs M16a2
- US MILITARY MOD
- Military Gear Pack
```

**Description:**
Since ACE's update bringing its modules and options into CBA (I apologize if this is termed incorrectly), the UI overrides a CUSTOM Difficulty Setup that is in the Dedicated Server Profile.. Specifically a Fade option. The ACE UI is either OFF or ON with no option. Short of removing the PBO from everyone's game of the UI I'm hoping I'm doing this wrong or missing something.

For example: in the Server's Profile (See below) I have the UI so that it fades. The Player's UI appears when in use; Reloading, Grenade Changes, Zeroing etc. Again I suspect that ACE UI setting's override the Server's Profile Difficulty (which is custom).

```
version=1;
blood=1;
singleVoice=0;
gamma=1;
brightness=1;
maxSamplesPlayed=96;
class DifficultyPresets
{
	class Custom
	{
		class Options
		{
			reducedDamage=0;
			groupIndicators=0;
			friendlyTags=0;
			enemyTags=0;
			detectedMines=0;
			commands=1;
			waypoints=0;
			tacticalPing=0;
			weaponInfo=1;
			stanceIndicator=1;
			staminaBar=0;
			weaponCrosshair=0;
			visionAid=0;
			thirdPersonView=0;
			cameraShake=1;
			scoreTable=1;
			deathMessages=0;
			vonID=1;
			mapContent=0;
			autoReport=0;
			multipleSaves=0;
		};
		aiLevelPreset=3;
	};
	class CustomAILevel
	{
		skillAI=0.75;
		precisionAI=0.40000001;
	};
};

playedKeys[]=
{
	"BIS_EXP_m01.Tanoa_done"
};
sceneComplexity=400000;
shadowZDistance=100;
viewDistance=4000;
preferredObjectViewDistance=2000;
terrainGrid=25;
volumeCD=10;
volumeFX=10;
volumeSpeech=10;
volumeVoN=10;
vonRecThreshold=0.029999999;
```

**Steps to reproduce:**
- Our Server Config UI has not changed, and was working before the ACE update (unsure of what Patch# it was) now it overrides it.
- Load with ACE installed on Server and Clients and start any mission - UI is either OFF or ON with selections.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer /  Editor (Multiplayer) /

Thank you

**Comment by dedmen** [comment]
>Since ACE's update bringing its modules and options into CBA

Relevant changes
https://github.com/acemod/ACE3/commit/cd30b09b4f8517ab3f075def26ee0cd4c37e366c#diff-734eeef6bab651bcb11e7788af5d4e9aL20
#6459

I don't see anything in there though.

Here is the check @jonpas talked about

https://github.com/acemod/ACE3/blob/05d30c55732b95cfe38d145c738f3fdc227aec18/addons/ui/functions/fnc_setAdvancedElement.sqf#L26

Though

https://github.com/acemod/ACE3/blob/98da86b74d4089bc3403d0b0c0074e6a46ce35d8/addons/ui/XEH_clientInit.sqf#L22
Does set _force.

**Comment by commy2** [comment]
```sqf
 private _force = [true, false] select (GVAR(allowSelectiveUI)); 
```
That's super awkward. I would have written:
```sqf
 private _force = GVAR(allowSelectiveUI) > 0;
```

**Comment by dedmen** [comment]
@commy2 both are nonsense. allowSelectiveUI is a boolean.

**Comment by jonpas** [comment]
I can claim you are still weird @dedmen! :rofl:

**Comment by LinkIsGrim** [comment]
Can't reproduce. Haven't seen this since 2019.
