### ISSUE TITLE
Ace isn't allowing for use of Advanced modules. Steam based addon.

### ISSUE THREAD

**Issue by BobLeeSwagg** [acemod/ACE3#6539]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- RHS
- SMA
- 3CB's mods
- Dagger sniper mod
```

**Description:**
- I'm trying to learn to shoot using ace's advanced ballistics but when I open the ATragMX the reset and update buttons aren't visible. I then try opening the editor to put down the modules and ace's modules aren't there. i'm using all my mods through steam. 

**Steps to reproduce:**
- I don't know, I've tried using both ace and cba as local mods to see if that effects it but nothing happens.

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None. The modules for ace aren't showing, yet I can use the menus and interactions.

**Comment by Drofseh** [comment]
I don't know what's going on with the ATrag, but ACE stopped using editor modules last December in v3.12.0.
https://ace3mod.com/2017/12/20/cba-settings.html

**Comment by Drofseh** [comment]
It would also probably help if you filled out the issue template correctly, including the version numbers you're using and your RPT file.

**Comment by dedmen** [comment]
>Arma 3 Version: x.xx (stable / rc / dev)

invalid
>CBA Version: 3.x.x (stable / dev + commit hash)

invalid
>ACE3 Version: 3.x.x (stable / dev + commit hash)

invalid

How are we supposed to help you if we can't know what's going on?

**Comment by commy2** [comment]
Works as intended for me.

**Comment by PabstMirror** [comment]
Last year we switched from modules and ace settings to CBA's system.
Refer to the guide here: https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System

So instead of putting down an advanced ballistics module, open cba settings for a mission and enable it that way.
