### ISSUE TITLE
Only display medical interactions if the player holstered their weapon

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#654]
I propose forcing the player to holster their weapons to enable various interactions, specially medical.

Reasons:
- It's a bit weird to see people pointing their guns at person or a body. They might be trying to treat them, but it just doesn't look that way at all, which detract from the whole 3d space. 
- Holstering/drawing the weapon is fast an I don't think it would be cumbersome.
- This would cut down 90% of the actions during normal combat, making the interaction system much for fluid to use in for actions in general (tapping shoulders, opening doors, taking prisoners, etc). 

Other things:
- Maybe the "check pulse" action should remain; maybe some sort of diagnosing too.
- Maybe the "holster weapon" key should be made more accesible; probably add it to self interaction too to prevent people who forgot their keybind from treating.
- To the very minimum the weapon should be lowered to allow treatment.
- I'm not sure you can holster while prone, so maybe should still be able to treat with your weapon on that stance.
- This could be a setting too

We already do this for surrendering, but I think this idea could be used for other things too.

**Comment by jaynus** [comment]
I'd recommend forcing lowering instead of holstering. Double tapping ctrl is a known vanilla action, versus a whole other feature

**Comment by dixon13** [comment]
+1 jaynus's idea

**Comment by commy2** [comment]
Problem is, that it still plays that ugly weapon-to-back animation then.

**Comment by meat147** [comment]
I prefer ed version can we make this optional default opt out ?

**Comment by Codingboy** [comment]
+1 jaynus's idea

**Comment by esteldunedain** [comment]
Obviously people have different opinions about this one. People preferences may also be related to what medical level they use. Safest option (not necesarilly the best) would be to provide the three alternatives: 
- Always show medical actions
- Hide medical actions when weapon is raised
- Hide medical actions with weapon in hands

The discussion would then be which we designate as default.

**Comment by jaynus** [comment]
#2 default, 3 choice setting

**Comment by jonpas** [comment]
Agreed on above.

**Comment by alganthe** [comment]
with the new animation on dev branch (air stitching) you won't get the weapon on back animation loop so forcing weapon holstered by default would be a good idea on advanced.

**Comment by KoffeinFlummi** [comment]
#2 or #3 should **not** be the default settings.

This makes sense and is somewhat intuitive for surrendering, but for something that is in no direct correlation with your weapon, it would be a usability nightmare and lead to a shitton of confusion and frustration. I'm fine with providing the setting for communities to enforce, but the default should remain #1.

Alternatively we could simply force-lower the weapon when the interaction menu is opened, although that could be considered too invasive.

**Comment by esteldunedain** [comment]
> #2 or #3 should not be the default settings.

I'd be fine with that.

The setting would be nice to have though. I'll make a PR at some point if nobody else does it first.

> Alternatively we could simply force-lower the weapon when the interaction menu is opened, although that could be considered too invasive.

If that's possible we could experiment how that feels, it could work.

**Comment by Legolasindar** [comment]
For me the idea of esteldunedain is very good. I think the 2 or 3 options are great.
In this case, think that some actions are more complicated than others.

- Put a bandage requires having completely hands free.
- Use a self-injectable Morphine can be done with one hand on the gun.

It is possible therefore that the best option (if we want to be as realistic as possible) is that some actions require the gun down, and others requiring gun in the back.

**Comment by dixon13** [comment]
I'm going to have to agree with @KoffeinFlummi here. The default should be #1. I don't mind having to lower my weapon but putting my weapon on my back is a bit invasive as @KoffeinFlummi put it. I think #1 is perfect for default and #2 should be an optional thing under the medical system. Although, @KoffeinFlummi makes a good point about this being an interface decision rather than a mechanical one.

**Comment by headedhorseman101** [comment]
Just as an outside opinion, I agree with force holster ring. I have never seen anyone do anything remotely effictively such as bandaging, removing clothing to expose wounds, etc. with just one hand. Also, pulling out rifle animation is cumbersome and gets me killed sometimes with agm (my unit is waiting for ACE's first official release to switch).
