### ISSUE TITLE
RHS Compat - Hellfires

### ISSUE THREAD

**Issue by Toshi9003** [acemod/ACE3#6541]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- RHS
- ACE Compat - RHS United States Armed Forces v3.12.3.36
```

**Description:**
RHS Hellfire not working properly while locking on to laser and shows two different types hellfire while in RHS AH-6 Littlebird. 

When two pylons of hellfire are installed it will show 2 missiles of hellfire L and 4 missiles of hellfire K.
-  Hellfire L tracked to laser targets correctly.
-  Hellfire K in shoot into air and stop. 

( I understand RHS just updated just giving you guys info)

**Steps to reproduce:**
-Place RHS AH-6M
-Change Pylons to AGM-114k 2x
- Pilot shows 2 AGM-114L and 4 AGM-114k
- Laser Lock works fine on 114L missiles track
- 114k shoots into air and freezes. 

**Where did the issue occur?**
- Dedicated Server

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by PabstMirror** [comment]
Can you reproduce without ace running?

The only guidance we should be adjusting is the pylon missiles that have a `[ACE]` tag on them (and you get a code display in-game).

The L shouldn't be laser tracking, it's radar guided.
RHS also added attack modes, make sure you are trying lobl first and seeing if you can get that working.

**Comment by Toshi9003** [comment]
My apologies for the incomplete information, this is my first time and I did not see the section on top. 

This issue can be closed. After further testing I found the issue to be with the ACE3 RHS Missile Guidance Сcompatibility Mod which I recently discovered is not produced by Ace.

**Comment by PabstMirror** [comment]
for ref http://www.armaholic.com/page.php?id=33415
