### ISSUE TITLE
ACE "Open / Close Door" keybind causes wooden Shoothouse walls to dissappear in pieces

### ISSUE THREAD

**Issue by Max255PL** [acemod/ACE3#6544]
**Arma 3 Version:** `1.84` (profiling build)
**CBA Version:** `3.8.0` (stable)
**ACE3 Version:** `3.12.3` (master - d8b54a8)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- As described in title, when using the keybind on the shoothouse wall, the pieces start dissapearing one by one.

**Steps to reproduce:**
Vid: https://streamable.com/nmxp5

- Place a vanilla Shoothouse Wall.
- approach it and use the ACE action "Open / Close Door", default Ctrl+Space
- the looked at segment of the wall will dissappear

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Placed Modules:**
- None.

**RPT log file:**
- https://pastebin.com/DMs5ASvC (nothing interesting from what I gathered)

**Comment by jonpas** [comment]
Is that wall just animated that way?

**Comment by alganthe** [comment]
Yes, those anim sources are also named.
![](https://i.imgur.com/cnxUa9H.png)
