### ISSUE TITLE
ACE Arsenal not listing RHS PKM/PKP ammo

### ISSUE THREAD

**Issue by Doctor-Butts** [acemod/ACE3#6545]
**Mods:**
```
RHS: AFRF Version 0.4.7
```

**Description:**
- Trying to customize a loadout using ACE arsenal in latest version of ACE/CBA/ARMA 3
![pk-1](https://user-images.githubusercontent.com/22239077/44472713-b281e900-a5fc-11e8-8bd7-e66bd74638ba.jpg)
![pk-2](https://user-images.githubusercontent.com/22239077/44472717-b6ae0680-a5fc-11e8-8286-16ebc7a04b7d.jpg)

**Steps to reproduce:**
- Opened ACE arsenal to modify loadout with both RHS PKP/PKM, no ammo is listed. An ammobox appears attached to the gun in the screenshot, but it has zero ammo.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**Comment by PabstMirror** [comment]
Will be fixed by #6529

**Comment by dedmen** [comment]
#6529 has been merged. Need to confirm fix
