### ISSUE TITLE
Can't repair track on USMC RHS M1A1

### ISSUE THREAD

**Issue by armyinf0703** [acemod/ACE3#6546]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `stable` (stable / dev + commit hash)
**ACE3 Version:** `stable` (stable / dev + commit hash)

**Mods:**
```
-RHS All 4
- CBA_A3
- ace
```

**Description:**
- Can't repair track of USMC M1A1 Either model/ Woodland/ Desert

**Steps to reproduce:**
- Spawn an m1a1 with broken left or right track, even as engineer, toolkit etc, unable to repair track.. Works on Army version M1A1
**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
All

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.
Here is an export of our cba settings 
https://pastebin.com/dM2U4ZAj
**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by PabstMirror** [comment]
Couldn't reproduce
Tank with health slider at 20% and repair specialist with ace track placed:
![20180828092511_1](https://user-images.githubusercontent.com/9376747/44729409-5e678080-aaa4-11e8-8ae2-1c4943c6f248.jpg)

**Comment by commy2** [comment]
Missing RPT file.

**Comment by dedmen** [comment]
All versions are invalid. `stable` is not a valid version.

**Comment by PabstMirror** [comment]
Let us know if this is still an issue with current RHS release
