### ISSUE TITLE
Can't use static launcher AT

### ISSUE THREAD

**Issue by Arkblade2015** [acemod/ACE3#655]
Mods:

@cba_a3
@ace3

Placed ACE3 Modules:
ace_javelin
ace_missileguidance

Description:
Can't use static launcher AT. it can't lock on enemy using ace method.

Steps to reproduce:
none

Where did the issue occur?
"Singleplayer"*

**Comment by jaynus** [comment]
Known. Static, AA and AP are not implemented yet.

**Comment by jaynus** [comment]
This was worked on and closed by #677
