### ISSUE TITLE
Rhino MGS has 7.62mm gun instead of .338 gun

### ISSUE THREAD

**Issue by Aebian** [acemod/ACE3#6554]
**Arma 3 Version:** `1.84.144923` (stable)
**CBA Version:** `3.3.1` (stable)
**ACE3 Version:** `3.10.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The Rhino MGS has a 7.62mm instead of the .338 gun. Sound is also not the .338 one

**Steps to reproduce:**
- Start A3 with CBA_A3 and ACE3, place a Rhino MGS and voila...

**Where did the issue occur?**
- Everywhere in A3

**Placed Modules:**
- None

**RPT log file:**
- idk if that is necessary here.
- 24/7

**Comment by Aebian** [comment]
Oh and since its more of a futuristic vehicle the weapon in my opinion is not a Denzel MG4 since its chambered .338. I would say its rather a https://en.wikipedia.org/wiki/Lightweight_Medium_Machine_Gun

**Comment by xrufix** [comment]
The Rooikat had a prototype version using exactly that turret. It is not futuristic, it just didn't go into production. All Rooikats are fitted with the Denzel MG4 and this gun uses 7.62 NATO rounds.

Because of those facts, changing the calibre is not an issue, I did this intentionally. Ace did also change calibres on some other vehicles where the 6.5 mm gun was exchanged for 7.62.

The sound might be an issue. Can you provide a video where the problems are shown?

**Comment by Aebian** [comment]
Arma is not meant to be accurate / realistic. Since its set to year 2035 is completely reasonable to use the Prototype Version because Arma already did by fitting the vehicle with a .338 gun instead.

And of course is the 7.62 sound different then the.338 sherlock 
In vanilla the sound matches the one of the NATO MMG that is also chambered .338

So my point here is that it's okay to change the name but not the weapon. The point of playing with vanilla vehicles is to have also vanilla weapons in place. Also it is fact that Arma use prototype stuff sometimes... and that's one!

Just because someone else changed also vanilla weapons on vehicles it's no excuse to do it here also. Just remove the weapon change part in the config and rename the gun to the prototype Version and the sound will then be the .338 again like on the vanilla MMG

**Comment by bux** [comment]
> Arma is not meant to be accurate / realistic

ACE, though, is (at least increase the authenticity / realism). So that's not a valid point for this discussion.

**Comment by Aebian** [comment]
Yes ACE aims to add realism, but by changing the weapon to something completely different its not realistic. Arma used the Prototype variant of the vehicle , therefore the .338 gun and not the in-serive version is in-place.

Even if we take the realism part completely off I still would love the old weapon back, because its just part of the vehicle in Arma. 

Names can be the "real" ones but my opinion is that weapons should be kept vanilla in terms of caliber. ACE can modify the systems behind the weapon to make it more realistic yes, but general the weapon used on the vehicles here there for a reason. I mean my would every tank, apc get a 7.62mm? Whats the benefit? I vehicle with a .338 part from all the other "same" LMG's out there would be cool and Arma vanilla did exactly that.

If the BI devs would tought otherwise they would have been applying the 7.62mm instaead on the Rhino MGS but they decided to use the nice .338

**Comment by xrufix** [comment]
So the sound fits the 7.62 MG? If so, this is intended. At first, I thought it was missing or so. But if it is there, everything is fine imho and there is no reason to change anything.

**Comment by Aebian** [comment]
There is, revert back to the original? Why did you even touch this? The sound is crap but that's another topic. 

The vehicle was intended to have the .338 not 7.62mm...

Just because some in-service vehicle has another gun thats no proof to change it in Arma. As said ACE does things more realistic and its ofc intended in doing that but changing a weapon to something completly different which is not part of the vehicle is not realistic at all.

**Comment by Dystopian** [comment]
Maybe all vanilla vehicle weapons changes should be moved to its own addon like `realisticweapons` to simplify its disabling.

**Comment by severgun** [comment]
>Name Changes != Weapon Changes

https://github.com/acemod/ACE3/tree/master/addons/vehicles

**Comment by Dystopian** [comment]
> If you don't like.(You are only one)

I don't like it too but I don't play vanilla. If I played I would create PR to move this to another addon and then just moved it from my ACE folder.

**Comment by Aebian** [comment]
@severgun I'm not agressive, I just don't like the weapon setup and try to convince ACE to change it. But you are right, I probably need to create a compat addon to replace the weapon with the correct (vanilla) one .  Since this thread is not reaching the end.

**Comment by Aebian** [comment]
Soo, just to get things clear and maybe some text I wrote wasn't quite  polite:

The reason for this request is:
`` I like the .338 GUN and its sound and it was nice that BIS made finally a armored vehicle that had exactly this MG and sound as secondary weapon``

The vehicle is special in some way and the MG setup is one of many aspects the vehicle has. 
Now ACE came and changed exactly this weapon I was so happy about to have it. 

My reaction after I found out: I was upset. So sorry for the harsh text at first.
I would just love to have the orignal weapon back into the Rhino MGS thats all.

For the time being I will probably create a compat mod but a general rethinking would be nice aswell. 

Over and Out,

Aebian

**Comment by severgun** [comment]
> Yes ACE aims to add **realism**,
--- 
> **All Rooikats are fitted with the Denzel MG4 and this gun uses 7.62 NATO rounds.**
---
> I just don't like the weapon setup and try to **convince ACE** to change it.

SRSLY?

**Comment by Aebian** [comment]
The .338 is the gap filler between ``7.62`` and ``.50 BMG``. Yes everyone on the web says that 7.62 is the god of all rounds but certainly that's not true.
Also a prototype version of the vehicle exists that uses the .338 round. So  Arma probably used this real-life prototype as reference so it would still be realistic to have the Rooikats with a .338 gun

**Comment by Aebian** [comment]
Just because something in real-life isn't in service. it can be in Arma. I mean like NATO forces and Merkava vehicle fleet? Exists in Arma but not in real-life since the only operator of Merkava vehicles mostly is Israel Defence Forces only.

**Comment by MasonOfGermany** [comment]
It's quite amazing how severgun says to not be that aggressive, yet seems pissed himself.
If he prefers it so then what's the issue? It's a game not IRL

**Comment by natioh** [comment]
I'm also no big fan of the 7.62. The .338 was fine all along.

I remember back in Arma 2 there was no such change of weapons on vanilla vehicles. I mean sure they were named like their real-life parts but still. 

I'm not sure whats such a big deal to just remove the code that changes the Rhino weapon? ¯\_(ツ)_/¯
Some people just don't like it. If you are really into the "REAL" not prototype version why you are not creating another version of it? I'm not sure but I think Arma 2 ACE did this also for another vehicle.

**Comment by MasonOfGermany** [comment]
Agreed. Arma 3's vanilla assets are already unrealistic as is, as in, the MX Rifles don't even exist, the US military uses vehicles made for the Israel Defense Force, prototype vehicles such as the Commanche are widely used. So I don't see the issue with experimental weaponry, or making a separate vehicle with this experimental weapon while having another vehicle with the mainstream weapon. 

That way, both sides could benefit. After all, ACE 3's medic system is highly customizable for a reason too. You aren't forcing people to play with the most realistic and complex settings either.

**Comment by xrufix** [comment]
> Also a prototype version of the vehicle exists that uses the .338 round. So Arma probably used this real-life prototype as reference so it would still be realistic to have the Rooikats with a .338 gun

@Aebian Can you please give us a source to this?

**Comment by Aebian** [comment]
@xrufix Why would I? I said "probably" because I assumed it so this is no fact. So no proof needed here. 
Also vanilla vehicles are not created for being 100% accurate like in-service variants. 

So changing a weapon of the base game just because the real-life version has a different gun has nothing to-do with realism. 

Its realistic that the .338 is used ingame because BI developers created the car with the .338 gun and not with 7.62.  

Its not even proven that the original in-service Rookait was used as reference, so whats the point here?

**Comment by xrufix** [comment]
You may have misunderstood my request. It was this proposition I asked you to give us a source for:

> a prototype version of the vehicle exists that uses the .338 round
