### ISSUE TITLE
Ace3 Savegame and loading+ join mp problem 

### ISSUE THREAD

**Issue by Monsen007** [acemod/ACE3#6555]
**Arma 3 Version:** 1.84.144923 (stable / rc / dev)

**CBA Version:** `CBA_A3 v3.8.0.180801 (stable / dev + commit hash)

**ACE3 Version:** `Version 3.12.3 (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
![arma3 bug](https://user-images.githubusercontent.com/42822662/44831047-10c65180-ac25-11e8-9a79-e8e1e10a0d31.png)
![arma3bug2](https://user-images.githubusercontent.com/42822662/44831051-13c14200-ac25-11e8-83bd-31e9f0d74fc5.png)

Global setting ace _vehiclelock_vehicleStartingLockState changed mid-missio. Mission restart may required to prevent issues

and the old error message before the latest patch

Have problem ...
had to first another error message after the patch was the way but for a new have now what synonymous of arma turned on by launcher and zack the next message.

before everything was okey with us in the clan as far as the mission was concerned where the modules were still to place and now we have the problem with unterander the if we save and joins new and continue the only me so the host what can take from boxes the others get hardly anything out times it's just ammo times it's only medic stuff but both is not anymore.

I'm my Latin at the end do not know what it is, have only cba_a3 in it and ace3 and the same

maybe one can help me ...

and sry google translator xD

write again in german :)

and I'm new here xD do not know me the equivalent xD

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- it's the configuration in Addon Options

**RPT file:**

> https://pastebin.com/cKDa7TMU

--------------

Habe problem ...
hatte zu erst eine andere fehler meldung nach den patch war die weg aber dafür eine neue hab jetzt auch was von arma angemacht per launcher und zack gleich die nächste meldung .

vorher war alles okey bei uns im clan was die mission angeht wo die module noch so zu platzieren waren und jetzt haben wir das problem mit unterandern das wenn wir speichern und neu joinen und fortfahren das nur ich also der host was aus kisten nehmen kann die andern bekommen kaum was raus mal sind es nur ammo mal is es nur medic zeug aber beides ist nicht mehr .

bin mir mein latein am ende weiss nicht woran es liegt ,hab nur cba_a3 drin und ace3 und das selbe

viellicht kann mir einer helfen ...

und sry google übersetzer xD

schreibe aber nochmal in deutsch :)

und bin neu hier xD kenn mir dem entsprechen nicht hier aus xD

**Comment by thojkooi** [comment]
The error message looks like you need to either provide a valid key from ACE3 to the server or remove old pbo's with old signature files. You can do the latter by simply removing your ACE3 install and installating it again (or manually remove the old files).

You can find additional information about [signature checking on the BI wiki](https://community.bistudio.com/wiki/ArmA:_Addon_Signatures).
