### ISSUE TITLE
ACE Arsenal treats crew-served, inventory-fed weapon mags differently than Vanilla Arsenal

### ISSUE THREAD

**Issue by Blutze** [acemod/ACE3#6557]
**Arma 3 Version:** `1.84.144923` (stable)
**CBA Version:** `3.8.0` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
- NIArms
- 3cb BAF
```

**Description:**
Some weapons are using magazines derived from those meant for vehicle-mounted or otherwise vehicle-style weapons, but expect the user to carry them in the inventory. Examples include:
- NIArms handheld minigun
- 3cb BAF mortars
- 3cb BAF Barrett .50 cal rifle

Modmakers then simply set `scope` on their new magazines to 2, which makes the Vanilla Arsenal show them properly. The ACE Arsenal however appears to also hide magazines with `type = 0` instead of 256 like on normal rifle mags. Changing the type fixes the issue, but I have to do that for every single one we add to our modpack.

**Steps to reproduce:**
- Select weapon, it shows the magazine appearing behind the Arsenal UI
- Go in, the weapon is loaded
- Back to Arsenal
- Check magazine tab on weapon (its empty)
- Check magazine tab on backpack (its empty)
- Check all magazines tab on backpack, search for "81" and "500" (nothing shows up)
- Go in, the weapon is now empty

**Where did the issue occur?**
- Tested in Dedicated, Singleplayer and ACE Arsenal

**Placed Modules:**
- Nothing I placed myself.

**RPT log file:**
- [On ACE Arsenal](https://pastebin.com/Smn3BsPR)
- [On Vanilla Arsenal](https://pastebin.com/1Zb4i3e6)

**Comment by alganthe** [comment]
Type 0 mags are vehicle mags, that's why.

I won't add vehicle mags (type 0) support to ace arsenal.

**Comment by Blutze** [comment]
So your stance is that those magazines are incorrectly configured, and the Vanilla Arsenal shouldn't show them either?

Guess I'm gonna slap some modmakers with that.

**Comment by alganthe** [comment]
Yes, them showing up in vanilla arsenal is very likely a bug related to their whitelisting (the mag must be getting whitelisted because it's loaded in the weapon).

You can add them to the whitelist in ACE Arsenal and they'll work fine, but I can't make them appear by default, otherwise you end up with ... other magazines that REALLY shouldn't be there.
