### ISSUE TITLE
ace_zeus_arsenal.pbo outdated

### ISSUE THREAD

**Issue by TestingHydra** [acemod/ACE3#6562]
**Arma 3 Version:** `1.84.144923` (stable)
**CBA Version:** `3.8.0` (stableh)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
- ace no medical
```

**Description:**
I get an Error message saying "ace_zeus_arsenal.pbo is outdated" and then I am forced out of anything I was in.

**Steps to reproduce:**
Unknown

**Where did the issue occur?**
Multiplayer, VR Arsenal

**Placed Modules:**
None

**RPT log file:**
None

**Comment by dedmen** [comment]
>- ace
>- ace no medical

So you are loading ACE twice?
`ace_zeus_arsenal.pbo` That is not a ACE pbo. Ask whoever made that thing. It's using a ACE prefix in CfgPatches which is why ACE complains about it.

**Comment by dedmen** [comment]
Don't think anything's gonna happen here. He created the account on the day the issue was created. Seems to be abandoned now. Probably solved issue by himself.

**Comment by PabstMirror** [comment]
If still having issues, best bet is to totally wipe the `@ace` folder and install fresh from a zip from https://github.com/acemod/ACE3/releases/latest
