### ISSUE TITLE
Group Side Module changes group attributes

### ISSUE THREAD

**Issue by synixebrett** [acemod/ACE3#6568]
**ACE3 Version:** `3.12.3` stable

**Description:**
- Using the Group Side module changes the group's name and the assigned team of each member is reset.

**Steps to reproduce:**
- Be in a group with a custom callsign
- Set your team color
- Have Zeus use the Group Side module
- Callsign has been changed to a vanilla callsign and everyone is on the main team.

I am willing to write the code preserving these details for groups with human players, if the ACE team thinks that will be a good addition and would merge the PR.

I know it would be for my group, as our modded radios are linked to group names and team colors. You'll go from being on Block 2 Channel 4 as Bravo-3 (Blue Team) to being Block 16 Channel 1 as Alpha 1-1 (White).

**Comment by commy2** [comment]
Group Side module?

**Comment by synixebrett** [comment]
https://github.com/acemod/ACE3/blob/e5a15d200f44df5fccc0bc5575d18d80b35538dd/addons/zeus/functions/fnc_moduleGroupSide.sqf

**Comment by synixebrett** [comment]
It simply creates a group on the new side and has everyone silentJoin it. This causes the group information to be lost.

**Comment by commy2** [comment]
I'd merge a PR for this.
