### ISSUE TITLE
Can't load into the server due to ace

### ISSUE THREAD

**Issue by TWOyourDEATH522** [acemod/ACE3#6578]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ACEX
- Opposition [ACE3]
- ACE 3 EXTENSION ANIMATION [OPPOSITION ACE- STAR WARS]
- ACHILLES
- CTAB- COMMANDER'S TABLET 
- CUP TERRAINS- CORE
- CUP TERRAINS- MAPS
- CUP TERRAINS- CWA
- EARPLUGS 
- EDEN OBJECTS
- ENHANCED MOVEMENT 
- ENHANCED TRENCHES 
- MCC SANDBOX 4- MISSION MAKING THE EASY WAY
- NAM 
- NO WEAPON SWAY
- OCEAN MAP
- OPERATION: TREBUCHET 
- PANDORA 
- PERSONAL ARSENAL 
- SHACKTAC USER INTERFACE 
- STAR WARS: WEAPONS OF THE REPUBLIC 
- STAR WARS: 212TH AUXILIARY ASSETS
- STAR WARS: OPPOSITION MOD (MAIN)
- STAR WARS: OPPOSTITION MOD (MAPS)
- SW: LEGION ARMORY BETA RELEASE 0.9.4 
- TACTICAL WEAPON SWAP
- TASK_FORCE_RADIO
- X-CAM-TAUNUS (VERSION 1.1)
- ADV- ACE CPR
- BACKPACKONCHEST
- REMOVE STAMINA- ACE3

**Description:**
 - Everytime I try to load in to the server I will get an error stating "CLIENT/SERVER ADDON MISMATCH. CLIENT HAS EXTRA ADDONS: ["ACE_NOUNIFORMRESTRICTIONS"]. When I click on it I get kicked back to the server lobby. That's without regular ACE on and only SWOP ACE on. When I have ACE on I get to the same spot but the error report reads: CLIENT/SERVER ADDON MISMATCH. CLIENT HAS EXTRA ADDONS: ["ACE_COOKOFF,"ACE_DISPOSABLE","ACE_GEFORCES","ACE_NIGHTVISION","ACE_NOUNIFORMRESTRICTIONS","ACE_OPTICS","ACE_SLIDESHOW","ACE_SMALLARMS","ACE_ADVANCED_FATIGUE","ACE_HEARING","ACE_HELLFIRE"]. Once I click on it I will again be kicked back to the lobby. I have checked all my folders and all the PBO's that need to be there are there, I'm not missing any files and have done a fresh restart to confirm so.

**Steps to reproduce:**
- load my modlist and then join the 104th wolfpack training server (I can't give out the IP and password for obvious reasons) but if you contact them on discord I'm sure they'll be able to give you the info https://discord.gg/XhSjQX

**Where did the issue occur?**
- Dedicated 

**Placed Modules:**
- I don't know, it's not my server

**RPT log file:**
-unable to upload RTP log

**Comment by TheMagnetar** [comment]
This is because you are loading a different modset than the server.

**Comment by TWOyourDEATH522** [comment]
I loaded all the mods off of their required mod list and got rid of any and all mods that were not on the list just to be safe. When I look on the server info I have all of the recommended mods loaded that they ask for

**Comment by commy2** [comment]
>-unable to upload RTP log 

Needs RPT file

**Comment by dedmen** [comment]
>Arma 3 Version: x.xx (stable / rc / dev)
CBA Version: 3.x.x (stable / dev + commit hash)
ACE3 Version: 3.x.x (stable / dev + commit hash)

This stuff is important you know?
>-unable to upload RTP log 

Why? put in zip file. Drag&Drop into text box. Done.
>That's without regular ACE on and only SWOP ACE on.

So you are getting the error with someone elses specially modified ACE build? I'd say we can't give you support for that. Ask them

**Comment by TWOyourDEATH522** [comment]
[Arma3_x64_2018-09-16_22-59-58.zip](https://github.com/acemod/ACE3/files/2389476/Arma3_x64_2018-09-16_22-59-58.zip)

**Comment by TWOyourDEATH522** [comment]
Arma 3 Version: 1.84.144923 (stable)
CBA Version: 3.8.0.180801 (stable)
ACE3 Version: 3.3.1.8 (unstable)

**Comment by TWOyourDEATH522** [comment]
![20180915222930_1](https://user-images.githubusercontent.com/43331014/45637978-a7d23c80-ba60-11e8-9f2b-1975461a5bab.jpg)

With Regular Ace on

**Comment by TWOyourDEATH522** [comment]
![20180916084615_1](https://user-images.githubusercontent.com/43331014/45638005-b91b4900-ba60-11e8-9fec-1101c765a66f.jpg)

With regular Ace off and SWOP ACE on only.

**Comment by TWOyourDEATH522** [comment]
I went through all of their files and all the install guides and still get the errors, it's an ace issue at it's core, that is why I came here to ask for help

**Comment by Drofseh** [comment]
On line 834 of your RPT file it shows you're loading `ace_nouniformrestrictions.pbo`
`23:01:39 D:\Steam\steamapps\common\Arma 3\@SWOP_Main\addons\ace_nouniformrestrictions.pbo - cd980dc2`

The server doesn't want you do load that pbo, that's why you're getting the error.
Try deleting it and see if you can join.

It looks to me like the mod uploader either accidentally included that pbo or that the server owner accidentally deleted it.

**Comment by Cuel** [comment]
> I went through all of their files and all the install guides and still get the errors, it's an ace issue at it's core, that is why I came here to ask for help

No, the ace uniform restrictions pbo is not included in the default download. It's up to the server owner to allow optional pbos

**Comment by commy2** [comment]
>it's an ace issue at it's core

No, it really isn't.

**Comment by PabstMirror** [comment]
delete your folder and start from scratch
people often run into issues where they copy new files onto an old installation

**Comment by BaerMitUmlaut** [comment]
Closing because user error, no more responses.
