### ISSUE TITLE
overheating -- increase jam chance?

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#658]
Straight out of the TS meeting we had.

MX, Standing:

Firing one shot:
Temperature: 0.00159763 - JamChance: 1.43787e-006

Full auto 29 shots, last shot:
Temperature: 0.0477155 - JamChance: 4.29439e-005

**Comment by commy2** [comment]
So for the MX it basically went from 
0.000143787 %
to
0.004%
each shot after firing one mag full auto.

**Comment by bux578** [comment]
Last night during the testing session I've been supressing a fire team section with constant 20-30 round bursts from the Stoner LMG. Burning through multiple (6+) belts I haven't had a single jam.

If the jam chances are too realistic / low a jam probably won't happen during a 2h-3h mission. (Speaking of milsim, might be different for KOTH :smile: )

**Comment by commy2** [comment]
Well we first nerfed the chance after AGM's were too frequent and then ED reworked the temperature calculation. Currently the chance is 0 on a cold weapon.

Doesn't make any sense at all. Especially because temperature is no where near the reason a weapon usually jams.

Maybe this whole thing needs rethinking. Why is jaming and overheating in one PBO anyway?

**Comment by bux578** [comment]
:+1: 

> because temperature is no where near the reason a weapon usually jams.

not the **only** reason.

- laying down, crawling on sand / dust / dry underground
- helicopter downwash / close proximity explosions (dust)
- rain / swimming

**Comment by commy2** [comment]
Weapons don't work underwater (except that one), and being prone already increases the chance up to 200% depending on the surface type.

**Comment by bux578** [comment]
> Weapons don't work underwater

you don't say.

I was thinking about tracking these conditions somehow like increase jam chance by a flat 10% when the unit has been crawling on dust or increase jam chance for 15minutes when the unit has been swimming with his weapon.

**Comment by esteldunedain** [comment]
@commy2, @bux578, I'm deeply against this. The previous values were based IRL data (MRBS) for operational temperatures whenever possible (not for vanilla weapons, but I addopted for those similar values than for other weapons). 

Now for operational temperatures **the probabilities are multiplied by almost 20 just because**.

Plus obviously the thing was issues and changed on a 1 hour period.

>Doesn't make any sense at all. Especially because temperature is no where near the reason a weapon usually jams.

As I said, all those factors are baked in the jam chances.

**Comment by commy2** [comment]
>were based IRL data (MRBS) for operational temperatures whenever possible

The jam chances? I really can't remember that. I thought I just used some values.

For example currently the chance starts @ 0% and even stays at 0 until the scaled temperature reaches 0.33.
After basing the heating up increment on RL data of ammo and rifle, assault rifles for example heat up really slowly. It's practically impossible to go over 0.5 for the scaled temperature without taking tons of extra magazines.

My issues with this are:
- that currently the jam chance is way to dependant on the temperature
- Starts at 0 and for rifle_long_base even stays at 0 for basically ever.

**Comment by esteldunedain** [comment]
> After basing the heating up increment on RL data of ammo and rifle, assault rifles for example heat up really slowly. It's practically impossible to go over 0.5 for the scaled temperature without taking tons of extra magazines.

Half the scale is 500ºC, that's hot as hell already. For that temp Rifle_long_base has 1 in 1000 chance of jamming for every bullet, which doesn't sound terribly unreasonable (although I admit it's a bit low). That is 1 in 500 if proned.

I agree some extra environmental factor could improve this and add a bit more depths. Besides that, maybe we could assume lower reliabilty data for the vanilla weapons and give zero temps a small jam change too

**Comment by commy2** [comment]
>Half the scale is 500ºC

I didn't know that. We might want to adjust the check temperature action then.

>For that temp Rifle_long_base has 1 in 1000 chance of jamming for every bullet

The values for high temperatures seem to fit. Although these are never reached. The issue is with the low temperatures I think.

>The first interval in the array represented the typical operational temperature of the barrel, so having the jam chance == MRBS on that interval makes the most sense.

Does it? Because it starts out at 0% and ends at 1 in 3333.3 @ 0.33*500 = 167°C
A third of the bar is currently never reached on arifles, unless you use up 8 mags I think. (Will retest that and post actual numbers)

**Comment by esteldunedain** [comment]
Just to clarify how jam chances were derived, cause I don't think I've written this before.To associate MRBS with temperatures I did the following:
- For some common weapons (not in vanilla) (if IIRC the M60 MG, AR15 and the AK74 rifles) I simulated the temperatures they reach while firing at their reported Sustained Rate of Fire.
- I found that for all those weapons that temperature was around 300º, which corresponds quite nicely with the second point of the array.
- It stands to reason that during tests to get MRBS, weapons are fired near their sustained rate of fire, so I associated MRBS to that temperature.

That's how I got 1/MRBS chances for the second value on the arrange (333ºC). For the first value I assumed 0, and for the remaining values I increase the chances x5 for every additional 333ºC. That gave consistent jam chances for the M60 at higher temps, but besides that is not firmly grounded on RL tests, so we could tweak them.

> Does it? Because it starts out at 0% and ends at 1 in 3333.3 @ 0.33*500 = 167°C
The full scale is 1000º, so 33% is 333º

**Comment by commy2** [comment]
I didn't know you made the values. You probably edited what I made. I really can't remember that.

**Comment by esteldunedain** [comment]
Yes, sorry. I changed those values during the PR of the heating system (https://github.com/KoffeinFlummi/AGM/pull/1347), but that was not described on much depth.

**Comment by commy2** [comment]
>The full scale is 1000º, so 33% is 333º

We really have to adjust the check temperature action then. Because 333°C would still be in the green.(4 bars out of 12)

**Comment by esteldunedain** [comment]
> We really have to adjust the check temperature action then. Because 333°C would still be in the green.(4 bars out of 12)

Agreed, the feedback we give does not reflect how a weapon so hot looks and sounds like; I could dig up videos of that if we find it usefull.

---------------------------------
Current jam chances:
`[0, 1/MRBS, 5/MRBS, 25/MRBS]` corresponding to 0º, 333º, 666º, 1000º

Reevaluating the test data to try to increase jam chance:

- Increasing the 0-temp jam chance like this:
`[0.5/MRBS, 1/MRBS, 5/MRBS, 25/MRBS]` corresponding to 0º, 333º, 666º, 1000º

- Furthermore, assuming the MRBS are the mean jam chance on the 0~333º interval, which would yield:
`[0.5/MRBS, 1.5/MRBS, 7.5/MRBS, 37.5/MRBS]` corresponding to 0º, 333º, 666º, 1000º

That's probably as far as you can bend the test data to increase the jam chance. I'd totally fine with those models, as they are still consistent with the data.

**Comment by commy2** [comment]
>Agreed, the feedback we give does not reflect how a weapon so hot looks and sounds like; I could dig up videos of that if we find it usefull.

Please do that. The SFX has to be tweaked tooI think.

Do you still have the data for MRBS?
For the M4 I found values of 600 and 3600 (advertised).

**Comment by esteldunedain** [comment]
For the M4 I've fopund those values: https://github.com/KoffeinFlummi/AGM_Compatibility/blob/master/AGM_Comp_RHS_USF/config.cpp#L93

**Comment by commy2** [comment]
The value 1923 sounds reasonable, but then again. The weapon will probably never be at 333°C

**Comment by commy2** [comment]
Closed in favor of https://github.com/acemod/ACE3/pull/146

**Comment by commy2** [comment]
Solutions found, misunderstandings cleared up, plan to solve issues made, agreement made.

https://github.com/acemod/ACE3/pull/146

**Comment by esteldunedain** [comment]
> Solutions found, misunderstandings cleared up, issues isolated, agreement made.

Lol
