### ISSUE TITLE
script error fnc_bi_moduleProjectile

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#6581]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
the var `_dirVar` https://github.com/acemod/ACE3/blob/e2ac18a05d5f646bc7cbc043bcc148fde4c0f5dd/addons/zeus/functions/fnc_bi_moduleProjectile.sqf#L160 was comment out here https://github.com/acemod/ACE3/blob/e2ac18a05d5f646bc7cbc043bcc148fde4c0f5dd/addons/zeus/functions/fnc_bi_moduleProjectile.sqf#L37-L40 so that error is triggered

```
20:03:03 Error in expression <n _logic;
missionnamespace setvariable [_dirVar,_dir];
};
sleep 0.1;
isnull _pro>
20:03:03   Error position: <_dirVar,_dir];
};
sleep 0.1;
isnull _pro>
20:03:03   Error Undefined variable in expression: fnc_bi_moduleProjectile
20:03:03 File z\ace\addons\zeus\functions\fnc_bi_moduleProjectile.sqf, line 142
```

**Steps to reproduce:**
- go in zeus
- place 82mm mortar fire support
- change the position of the marker as zeus
- error pop up

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- RPT: https://gist.github.com/shukari/738a5d5e79b6d36385add9189b0e16c2

**Comment by bux** [comment]
Could you describe the error a little more in detail please? Maybe a short video of it if it's easier for you.

**Comment by shukari** [comment]
No, there is no more info... it is only a local variable that is not any longer defined because it was comment out... i cant make a pr because im on a trip ^^

**Comment by dedmen** [comment]
>20:03:03 File z\ace\addons\zeus\functions\fnc_bi_moduleProjectile.sqf, line 142

https://github.com/acemod/ACE3/blob/e2ac18a05d5f646bc7cbc043bcc148fde4c0f5dd/addons/zeus/functions/fnc_bi_moduleProjectile.sqf#L142

#6407 ┬─┬ ノ( ゜-゜ノ)

**Comment by dedmen** [comment]
Fault @SilentSpike #5888
https://github.com/acemod/ACE3/pull/5888/files#diff-545b87e05c356aef688526463c884185L43

Also
https://github.com/acemod/ACE3/pull/5888/files#diff-545b87e05c356aef688526463c884185L164
WTF BI?
