### ISSUE TITLE
ATragMX Phone App

### ISSUE THREAD

**Issue by THEDJMX** [acemod/ACE3#6588]
So I was wondering: 

How hard would it be to make a functioning ATragMX emulator that would run on an android device ? My codding experience is limited however it seems like a cool project. Any input is welcome!

**Comment by dedmen** [comment]
Why tho?
Why not just use a real ballistic calculator app like Strelok. Instead of trying to re-make something that would be way more limiting than it has to be?

**Comment by Blutze** [comment]
Intermediate ballistics settings (usually meaning basic but with wind and non-horizontally) come to mind, and maybe there is gonna be a deviation even on advanced ballistics.

**Comment by bux** [comment]
As this is not an issue with ACE
