### ISSUE TITLE
Slight Glitch with CBA Settings involving ACE3 Settings

### ISSUE THREAD

**Issue by TheNightstalk3r** [acemod/ACE3#6592]
**Arma 3 Version:** `1.82` 
**CBA Version:** `3.8.0` (Steam workshop)
**ACE3 Version:** `3.12.3` (Steam workshop)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
ACE3 ends mission ("Client has extra mods") for people using the optional mods "Tracers" and "Particles" with CBA settings:

// ACE Common
force ace_common_allowFadeMusic = true;
force force ace_common_checkPBOsAction = 0;
force force ace_common_checkPBOsCheckAll = false;
force force ace_common_checkPBOsWhitelist = "[""ace_particles"",""ace_tracers""]";
force force ace_noradio_enabled = true;

**Steps to reproduce:**
Set provided CBA settings on server, load into said server with Tracers and Particles optional mods.
Server will end mission for player with "Client has extra mods"

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
None

**Comment by jonpas** [comment]
Does parsing fail?

I use this (single quotes inside):
```sqf
force force ace_common_checkPBOsWhitelist = "['ace_particles', 'ace_tracers']";
```

**Comment by TheNightstalk3r** [comment]
I'll give that one a try! No parsing errors like that in the RPT or in script error when doing SP. With the current settings, shouldn't the whole checking be disabled since
force force ace_common_checkPBOsAction = 0;
force force ace_common_checkPBOsCheckAll = false; ? It happens too when the ace_common_checkPBOsWhitelist is empty.

**Comment by TheNightstalk3r** [comment]
force force ace_common_checkPBOsWhitelist = "[""ace_particles"",""ace_tracers""]";

that line comes from exporting the CBA settings, so maybe that may need some looking into too

**Comment by TheNightstalk3r** [comment]
@jonpas your solution line unfortunately didn't work. I'll give it a shot with 
```
force force ace_common_checkPBOsWhitelist = "["ace_particles', 'ace_tracers"]";```

ACE3 ends the mission with "Extra mods on client: ["ace_particles', 'ace_tracers"].".

**Comment by commy2** [comment]
What if you leave out the setting, and enter it as logging in admin instead?

**Comment by TheNightstalk3r** [comment]
@commy2 I've commented out the settings as you asked and logged in as admin when starting the mission. ACE3 still ends the mission for me because I have particles and tracers enabled. 
![107410_20180922190944_1](https://user-images.githubusercontent.com/17759038/45919771-1c5f0e00-be9b-11e8-829a-02c0406729c5.png)

**Comment by TheNightstalk3r** [comment]
![107410_20180922190944_1](https://user-images.githubusercontent.com/17759038/45920679-5b479080-bea8-11e8-93b3-d529c81ce502.png)
Maybe something here gives it away (This is with CUP Terrains Core, CUP Terrains Maps, CBA and ACE3)

**Comment by TheNightstalk3r** [comment]
Any news on this little bug? :D I'd rather not add some 3rd party reupload of ACE Tracers & Particles to play with the two optional mods :(

**Comment by TheNightstalk3r** [comment]
Ah, that makes a lot more sense than a parsing error indeed
