### ISSUE TITLE
Vector21 has got wrong zoom factor

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#6601]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.8.0` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The zoom factor of the vector21 is too low, compared with it's real counterpart (according to this: [https://www.safran-vectronix.com/product/vector-21/](url)).

**Steps to reproduce:**
- take a vector21 and a rifle with a 5x zoom scope (e.g. MOS). see that the zoom factor of the 5x scope is bigger than the zoom factor of the vector.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**Comment by dedmen** [comment]
https://github.com/acemod/ACE3/blob/master/addons/vector/CfgWeapons.hpp#L12

5x zoom would be 0.05 and higher zoom should be smaller value.
So we definitely have less than 5x zoom in there.

Arma binocular's 4x zoom is `0.0625` and Vector has even less zoom than that.

6x would be `0.042` from `optic_LRPS`

I don't know the math for these.

**Comment by commy2** [comment]
BWA3's Vector has the correct Magnification and mil dots (at least on non 5:4 screens).
But I would have to port the optics system from there.

**Comment by bux** [comment]
I'd prefer commy's solution
