### ISSUE TITLE
Load a unconscious

### ISSUE THREAD

**Issue by YoannFR** [acemod/ACE3#6603]
**Arma 3 Version:** `1.84` (stable / rc / dev)
**CBA Version:** `3.8.0` (stable / dev + commit hash)
**ACE3 Version:** `3.12.3` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- When you want load a unconscious body into a vehicle and you have in the ACE3 menu many vehicles, the body it's load in a aleatory vehicle..

**Steps to reproduce:**
- Take a unconscious body and load into a vehicle

**Where did the issue occur?**
- Editor / Multiplayer

**Placed Modules:**
- None

**Comment by commy2** [comment]
Holy shit, I have never in my life heard the word "aleatory".

**Comment by YoannFR** [comment]
This word exist, if you search ;)

**Comment by xetra11** [comment]
@YoannFR what did you googled for? 
"super rare and fancy term to tell something is pretty dangerous to do"

**Comment by YoannFR** [comment]
Aleatory = random

I'm french and aleatory it's "Aléatoire" in french and if you search, the translation of "aléatoire" = aleatory

**Comment by thojkooi** [comment]
It will load it into the nearest available vehicle. This is in relation to the body.

We're happy to take on suggestions for improvements to this system.

**Comment by jonpas** [comment]
@thojkooi I believe it was changed to actually display all vehicles. But judging by this report, when there is too many of them (?), it doesn't work?

**Comment by PabstMirror** [comment]
You should get a sub-menu like this:
![20190101200320_1b](https://user-images.githubusercontent.com/9376747/50578481-7a877f80-0e00-11e9-9723-8cb6a5afe70c.jpg)
Allowing you to pick the specific vehicle they get loaded into, if you just select the base action it will pick one.

I have a PR that adds a hint for the vehicle they get loaded into.

**Comment by dedmen** [comment]
Did you mean to close this?
