### ISSUE TITLE
Weapon Select Feature "0" plays x2 Animation

### ISSUE THREAD

**Issue by JHill29th** [acemod/ACE3#6610]
**Arma 3 Version:** `1.84.0.144923` (stable)
**CBA Version:** `3.8.0.180801` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Using `0` to put weapon away plays animation twice.  
Might have something to do with [`fnc_fixLoweredRifleAnimation.sqf`](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_fixLoweredRifleAnimation.sqf) being called immediately before the `switchWeapon` in [`fnc_putWeaponAway.sqf`](https://github.com/acemod/ACE3/blob/master/addons/weaponselect/functions/fnc_putWeaponAway.sqf)?

**Steps to reproduce:**
- Line up some people in front of you and ask them to press `0`.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
- N/A

**Comment by alganthe** [comment]
There's nothing stopping multiple presses in quick succession, meaning that if you press it twice you'll put the weapon on your back and then in your hands again.

Not sure if it can be considered a bug or a design flaw.

**Comment by commy2** [comment]
alganthe, I think BI at some point changed how `switchMove` works in MP. This component just needs some maintenance.

**Comment by alganthe** [comment]
The actions seem to be queued now^

**Comment by JHill29th** [comment]
[A video example.](https://youtu.be/rKt-bJRqZsA?t=23)
