### ISSUE TITLE
ace_cargo_fnc_canLoadItemIn makes it impossible to load things into a flying vehicle

### ISSUE THREAD

**Issue by Zumiii** [acemod/ACE3#6616]
**Arma 3 Version:** `1.84` (stable / rc / dev)
**CBA Version:** `3.8.0` (stable / dev + commit hash)
**ACE3 Version:** `3.12.3` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
The function ace_cargo_fnc_canLoadItemIn does prevent you from virtually loadinging items into ACE Cargo in case the vehicle that should be loaded is driving / flying. Even though the third param (2: Ignore interaction distance <BOOL>) set to true should let you load things by script, the script exits because of this line:

if (speed _vehicle > 1 || {((getPos _vehicle) select 2) > 3}) exitWith {TRACE_1("vehicle not stable",_vehicle); false};

Could that be changed so it lets you load things in by script using for example ["item_to_load_in", vehicle_to_load_item_into, true] call ace_cargo_fnc_loadItem? Would be glad!

**Steps to reproduce:**
- Try to load Cargoitems into a flying plane.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Placed Modules:**
- None

**RPT log file:**
- Not needed

**Comment by dedmen** [comment]
I think we should just remove the height check. For example if a helicopter is flying next to the roof of a house. And people standing on the roof of the house want to load items into it. The speed check will succeed but the height check won't.
Or maybe we want height difference to players height?

**Comment by alganthe** [comment]
height difference to the object's height imho^

**Comment by dedmen** [comment]
Just don't know if you'd want that be related to the interactionDistance setting, or add a new setting for that one.
So far it has been hardcoded so I'd personally leave it like that.

**Comment by Zumiii** [comment]
@dedmen I think when ignoring interaction distance (which is mainly used by scriptbased cargomanipulation imo) it simply does not make sense to check for vehicle speed and height because of the mentioned issue. Having it check height difference only would make sense if a player wants to load stuff in from a roof, as you said. So i suggest: Case: Ignoring interaction distance: Ignore object speed / height. Case: Check interaction distance: Check for height difference to players height.

**Comment by Zumiii** [comment]
Perfect. Issue closed. Thanks a lot @PabstMirror

**Comment by Yordanorn** [comment]
Hi !
Im' sorry but I have the same problem.
I create a script for spawn supply and Vehicles.
I setup all cargo space etc...
But it's impossible to load supply crate on Vehicle because I'm 400m high.
I don't understand what to do for enable cargo on height.
If I understand framework & this issues, I need to add on my script : _ignoreInteraction
But what params for ? Bollean ? Scalar ? just a _ignoreInteraction = true; ? I don't really understand X)

**Comment by Drofseh** [comment]
> Hi ! Im' sorry but I have the same problem. I create a script for spawn supply and Vehicles. I setup all cargo space etc... But it's impossible to load supply crate on Vehicle because I'm 400m high. I don't understand what to do for enable cargo on height. If I understand framework & this issues, I need to add on my script : _ignoreInteraction But what params for ? Bollean ? Scalar ? just a _ignoreInteraction = true; ? I don't really understand X)

https://ace3.acemod.org/wiki/framework/cargo-framework.html#44-load-cargo-into-vehicle

`[object, vehicle, true] call ace_cargo_fnc_loadItem`

**Comment by Yordanorn** [comment]
Thank's !
You confirm I need put this call for all crates for all Vehicles in my script, right ?

**Comment by rautamiekka** [comment]
I use the `loadItem` one in a mission (a script run through the debug console), yes, you run it on every object you wanna load to cargo, as the source code reveals it only accepts a single object/string.

Note that you must ensure there's enough cargo space cuz the function won't forcibly shove it in there. Simplest is to add a stupid amount of space, then
1. manually load 1 of 1 type of item.
2. note the diff between the space before and after loading
3. unload the item.
4. repeat from 1 until all types have been checked.
5. change the space to only afford those (or whatever is appropriate for your mission).

However, the easiest way (which my script uses) to load many is to place a never-activating trigger, place all the items within it, name the trigger, name the vehicle, and use the [`list`](https://community.bistudio.com/wiki/list) scripting command in `forEach`:
```sqf
{
    [_x, _vehicle, true] call ace_cargo_fnc_loadItem;
} forEach list _trigger;
```
