### ISSUE TITLE
Add jerry can setting field to vehicle attributes

### ISSUE THREAD

**Issue by severgun** [acemod/ACE3#6624]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.x.x` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
...
```

**Description:**
- Add abbility to add jerry cans to vehicles by attributes window.
![20181006225918_1_cr](https://user-images.githubusercontent.com/1197314/46575318-07669c80-c9bc-11e8-95f7-81cefba86267.png)

**Comment by Drofseh** [comment]
#3594
