### ISSUE TITLE
isDeadPlayer no reset after respawn

### ISSUE THREAD

**Issue by C0kkie** [acemod/ACE3#6634]
**Mods:**
```
- CBA_A3
- ace
and more
```

**Description:**
- If you are dead via ace and you respawn, the isdeadplayer variable is still on true

**Steps to reproduce:**
-  use setdead function, respawn, variable will not reset

**Comment by commy2** [comment]
And?

**Comment by commy2** [comment]
Ref: https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_setDead.sqf#L52
This line is obsolete. You're not supposed to use that variable. Although we should clean it up as it is currently dead weight network traffic and JIP stack.

**Comment by C0kkie** [comment]
Why exactly is that obsolete?
I mean if i was unconscious and after that i am finally dead i cant check with alive player if i am dead or not. Thats why i checked via isdeadplayer

**Comment by commy2** [comment]
`alive` reports `true` when unconscious.

**Comment by commy2** [comment]
Close?

**Comment by BaerMitUmlaut** [comment]
Close. Not public API, not necessary either.
