### ISSUE TITLE
Vehicle Lock Assign Module  Clarification

### ISSUE THREAD

**Issue by Fletch43** [acemod/ACE3#6637]
Hey guys. Just wanted to ask how exactly do you use this feature? Now what I am trying to accomplish is I'm making a coop multiplayer type map with Alive. I want to restrict a certain pilot to use a certain plane. So that if anybody comes in that is not that specific pilot it would be locked to them.  I have seen you have a Vehicle Lock Assign module and just need a little help understanding how to use this. 

Looking at the "usage" on the framework link it says " Sync the module **with** vehicles and players. Custom keys will be handed to players for every synced vehicle. It is only valid for objects present at mission start."

    -I understood this as to sync the vehicle to the module as well as the specific player(s) to the module then the specific keys will be given out? Am I right on that? When I start the mission there is an error bottom left of my screen that the module has not been synced to a vehicle and no keys are givin out.

Thanks for any info.

Fletcher

https://ace3mod.com/wiki/feature/vehiclelock.html

https://ace3mod.com/wiki/framework/vehiclelock-framework.html

**Comment by commy2** [comment]
... you have to synch the module to the plane and the pilot?

**Comment by Fletch43** [comment]
Did that doesn't work. Says module is not sync'd to a vehicle.
On 10/12/2018 00:31:55, commy2 <notifications@github.com> wrote:
... you have to synch the module to the plane and the pilot?

**Comment by alganthe** [comment]
like this:

![image](https://i.imgur.com/dzvFPoZ.png)

**Comment by Fletch43** [comment]
I had done that before, but I'll check again. Thanks.

**Comment by Fletch43** [comment]
This is with CBA and ACE only. My thinking was that if I synced the pilots to their planes that only they will have access to their planes. So I test 3 planes with 3 pilots. 


https://1drv.ms/u/s!Ah7_Vhm6Z1k3gZAyANlRead_qg2cjA

When I spawned in I went to the other plane and got access to somebody else's plane.
https://1drv.ms/v/s!Ah7_Vhm6Z1k3gZAzCpdnzlsQ5pgn4Q

Finding a way to lock the jets/vehicles, in a multiplayer scenario, so people won't steal non-assigned vehicles.


Thanks.

**Comment by commy2** [comment]
I don't exactly know how this component operates, but looking at this: https://github.com/acemod/ACE3/blob/master/addons/vehiclelock/functions/fnc_moduleSync.sqf#L30-L32 it seems it only works with Cars, Tanks and Helicopters for some reason.
Does it work for you with a tank instead of a plane?

**Comment by Fletch43** [comment]
Yup u are right! Planes don't work. Ugh. I wasn't smart enough to look at the component scripting. :)


https://drive.google.com/file/d/1e99Yf5nhBHfIYNgJHjfxt2Pip2Q4GAK6/view?usp=sharing

**Comment by commy2** [comment]
I don't see why we couldn't add Plane class for this module. Will change that.
