### ISSUE TITLE
flashlights stay turned on when switching weapons

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#6640]
**Arma 3 Version:** `1.84` (stable / rc / dev)
**CBA Version:** `3.9.0` (stable / dev + commit hash)
**ACE3 Version:** `3.12.3` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Switching weapons when a flashlight is technically available on both will keep the light on, now you might ask "why is this an issue?" well, the flashlight parameters aren't re-checked, so with the daylight laser that technically has an invisible flashlight it suddenly becomes visible.

it is currently not possible (1.84) to switch a player flashlight or IR laser ON / OFF without making it switch to it's primary.

**Steps to reproduce:**
- Get a primary with a daylight laser and a handgun with a flashlight, turn on flashlight, switch weapon.

**Where did the issue occur?**
- BI issue

**RPT log file:**
- BI issue

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
