### ISSUE TITLE
drag dead body (offer)

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#6662]
hi. can you add to drug dead body function? playing with AI often have to disassemble a bunch of corpses to get to equipment. I understand that it can be done with additional scripts, but I think it’s not a problem to do it permanently in ACE, moreover, you can even drag a live stand-up bot 
http://joxi.ru/D2Pdz7LcpZaY02

**Comment by Dystopian** [comment]
Access to dead bodies equipment should be easier after #6029. Also feature requests go #3594.
