### ISSUE TITLE
NVS scope has blur

### ISSUE THREAD

**Issue by kamkill01011** [acemod/ACE3#6666]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.9.0` (stable)
**ACE3 Version:** `3.12.3` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- When you aim down the NVS (vanilla scope with integrated night vision) the screen is blurred like when you aim down any normal sight with NVG, however when looking in binoculars with night vision (like the Vector nite) the screen is not blurred; ithink NVS shouldn't be blurred.

Vector : https://i.imgur.com/DPakw0u.jpg
NVS : https://i.imgur.com/QNccjJ2.jpg

**Steps to reproduce:**
- Place a unit, give him the NVS, aim down the sight.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Placed Modules:**
- 

**RPT log file:**
-

**Comment by jonpas** [comment]
Same happens with `pilotCamera` cameras in planes and helicopters.

**Comment by xrufix** [comment]
@jonpas `pilotCamera` seems to be fine for me, compare the following screenshots (`ace_nightvision_aimdownsightsblur == 2`):

![20181112085644_1](https://user-images.githubusercontent.com/29610495/48333864-2a3e3d80-e659-11e8-93e5-de600dceae76.jpg)

![20181112085553_1](https://user-images.githubusercontent.com/29610495/48333842-214d6c00-e659-11e8-8a01-476e50890f44.jpg)
