### ISSUE TITLE
Is there a way to disable ACE fall damage only?

### ISSUE THREAD

**Issue by JinougaF** [acemod/ACE3#6668]
I have a mission perset I need to disable only the falling damage, but still allow player to be damaged by weapons, or road killed by vehicles etc, how can I make this work?

**Comment by JinougaF** [comment]
> I've used this to block fall damage, not sure about roadkill
> It's kinda hacky, but it should get you started
> 
> ```
> [] spawn {
>     waitUntil {time > 5};
>     {
>         _x removeAllEventHandlers "HandleDamage";
>     } forEach allUnits;
>     if (hasInterface) then {
>         waitUntil {player == player};
>         waitUntil {alive player};
>         player addEventHandler ["HandleDamage", {
>             diag_log text format ["HD: %1", _this];
>             _type = _this select 4;
>             if (_type == "") then {
>                 0
>             } else {
>                 _this call ACE_medical_fnc_handleDamage
>             };
>         }];
>     };
> };
> ```

So this one affect all unit in mission or only the player units?

**Comment by commy2** [comment]
The local player only. And it will disable collision damage as well.

**Comment by JinougaF** [comment]
> The local player only. And it will disable collision damage as well.

So where should I put this script in? In player units' init or in mission sqf?

**Comment by commy2** [comment]
initPlayerLocal.sqf

**Comment by JinougaF** [comment]
> initPlayerLocal.sqf



> I've used this to block fall damage, not sure about roadkill
> It's kinda hacky, but it should get you started
> 
> ```
> [] spawn {
>     waitUntil {time > 5};
>     {
>         _x removeAllEventHandlers "HandleDamage";
>     } forEach allUnits;
>     if (hasInterface) then {
>         waitUntil {player == player};
>         waitUntil {alive player};
>         player addEventHandler ["HandleDamage", {
>             diag_log text format ["HD: %1", _this];
>             _type = _this select 4;
>             if (_type == "") then {
>                 0
>             } else {
>                 _this call ACE_medical_fnc_handleDamage
>             };
>         }];
>     };
> };
> ```

thanks guys, it worked!
