### ISSUE TITLE
Atragmx and drag/microdrag dosent connect

### ISSUE THREAD

**Issue by xkozyr** [acemod/ACE3#6685]
Vector 21 dosent send data to dagr/microdagr even if it says connected

atragmx is in fahrenheit
kestral 4500 is in celsius WTF?
there is no option to change that

now i have to put in distance, dir of fire manualy and convert fahrenheit to celsius on some webside
this is bullshit

**Comment by dedmen** [comment]
I used vector with microdagr last week. All fine.

>atragmx is in fahrenheit

Yeah. So what? Just change it to metric if you want metric.
https://ace3mod.com/wiki/feature/atragmx.html

> distance, dir of fire manualy

You have to do that. Yes. So what?

>this is bullshit

Please have a read of https://github.com/acemod/ACE3/blob/master/.github/CONTRIBUTING.md and figure out what is actually the bullshit here.

**Comment by jonpas** [comment]
Closing, open a new issue with properly filled out report if you want audience.
