### ISSUE TITLE
Arsenal: Unable to edit loadouts of remote AI in multiplayer

### ISSUE THREAD

**Issue by xrufix** [acemod/ACE3#6701]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.9` (stable)
**ACE3 Version:** `3.12` (stable)

**Mods:**
```
many, please refer to RPT
```

**Description:**
- AI that is remote (in this case, spawned in Zeus and then transfered to HC via script) is not compatible with ACE arsenal. Some equipment can be changed (e.g. uniform, vest) but the weapon cannot. When changing it, the selected weapon shows for just one frame and then is changed back to the default one.

**Steps to reproduce:**
- Start a mission with Zeus,
- place a unit and transfer it to the HC or Server,
- use Arsenal module

**Where did the issue occur?**
- Dedicated

**Additional information:**
- probably related to #6428
- mission file: [[GrpW]_TvT128_xru_ZGM_17v05.Altis.pbo.zip](https://github.com/acemod/ACE3/files/2600492/GrpW._TvT128_xru_ZGM_17v05.Altis.pbo.zip)

**RPT log file:**
- [arma3_x64_2018-11-20_15-31-28.txt](https://github.com/acemod/ACE3/files/2600502/arma3_x64_2018-11-20_15-31-28.txt)

**Comment by commy2** [comment]
Imo ownership should be transferred to the Arsenal machine and maybe back afterwards.

**Comment by alganthe** [comment]
i'm not sure if changing ownership is a good idea, but neither is spamming the network with REs since addWeaponGlobal is broken.

**Comment by xrufix** [comment]
Maybe RCing the unit while editing it's loadout would be a solution?
