### ISSUE TITLE
Move map marker feature only works locally

### ISSUE THREAD

**Issue by micahwhitsel** [acemod/ACE3#6702]
**Arma 3 Version:** `x.xx` (stable)
**CBA Version:** `3.9.0` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
https://docs.google.com/document/d/1OpNiwUVECKjwV-4XzDbfrpS6dbIGOoWQkWBWvZw9njw/edit?usp=sharing

**Description:**
- I have been attempting to use the move map marker feature but can only get it to change locally on my end. Anybody else in server seems unable to see any change. I cannot find any see to change this

**Steps to reproduce:**
- 2 players in a dedicated server. We could each place and see a map marker, and could move them on our screen, but could not see any change when moved by the other player

**Where did the issue occur?**
- Dedicated Multiplayer

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- https://pastebin.com/ANj3Exxx

**Comment by dedmen** [comment]
Please fill out the issue template.
Versions of mods and game, list of all mods. RPT.

**Comment by micahwhitsel** [comment]
@dedmen Updated with the full issue template

**Comment by dedmen** [comment]
>Arma 3 Version: x.xx

99% full.

You are running tons of mods. Including ones that extend ACE. Can you reproduce it with just CBA+ACE?


>14:57:15   Error Undefined variable in expression: cba_events_eventnamespacejip

WTF. Yeah something is breaking CBA.

>Warning Message: Embedded skeleton m3maaws_base in 'tf47_launchers\m3maaws\m3maaws.p3d' has different [ bones count ] in different p3d files. Skeleton/model 'rhsusf\addons\rhsusf_weapons2\m3maaws\m3maaws.p3d' will probably not work correctly.

Why do you have 2 m3maaws in your modpack? Where one is broken.

>WARNING: Usage of deprecated CBA_fnc_addLocalEventHandler backwards_comp.sqf:76

And you have some outdated mod.

**Comment by commy2** [comment]
It will. The implementation of moving markers wasn't done right.

**Comment by Blutze** [comment]
@dedmen 
> Why do you have 2 m3maaws in your modpack? Where one is broken.

Because RHS still, about a year after they acquired the TF47 model, haven't added the timed airburst feature or native compat with ACE backblast to turn their AT-4s into the Confined Space variant. The model names not including a mod name prefix seems to be originally a TF47 mistake, but RHS left that in for some reason.

Or rather, I have my thoughts about why they did it... just don't wanna get political.
