### ISSUE TITLE
HiOrange_Chemlight has error stopping loading of missions on dedicated server

### ISSUE THREAD

**Issue by Megahurt** [acemod/ACE3#6707]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by commy2** [comment]
Please fill out the template.

**Comment by Megahurt** [comment]
HiOrange_Chemlight has error stopping loading of missions on dedicated server. Missions that include this in an arsenal or ammo crate or loadout will not load on dedicated server .
We use verify signatures 2 .

**Comment by dedmen** [comment]
Fill. out. the. template. Please.

**Comment by Megahurt** [comment]
**Description**
The dedicated server rejects missions citing "Bad Vehicle type Chemlight_HiOrange."

**Steps to reproduce**
Missions that have Chemlight_Hi Orange in the sqm will not load on a dedicated server. 

**Additional information**
When Chemlight_HiOrange is removed from the sqm manually the mission will load but still returns the error "Bad Vehicle type Chemlight_HiOrange"  on startup.

Logfile 
I have found no reference to the error in the rpt file.

**Comment by MisterHLunaticwraith** [comment]
same here: here's a full rpt from the server: https://pastebin.com/8dwYVEs2
and rpt from my client: https://pastebin.com/9tbCutjD
This is a major issue since hey we cannot play on our dedi ;-)

**Comment by MisterHLunaticwraith** [comment]
> Opening the mission in 3DEN and pressing save will fix this issue

It didn't solve the issue for me @alganthe

**Comment by MisterHLunaticwraith** [comment]
However, removing any mention to the class from mission.sqm and the reopening it in the editor (do not save it!) as mentioned by @Megahurt did fix the issue.

**Comment by Meiestrix** [comment]
For me, the problem was the "ACE_Box_Misc", which contains the object "ACE_chemlight_HiOrange".
After deleting the chemlight the mission works fine again.

**Comment by diveyez** [comment]
I dont have those in any boxes and still get this error. What is going on?

**Comment by commy2** [comment]
Maybe wrong version on the server. No point in guessing though, as the answer is written in the RPT log files.
