### ISSUE TITLE
Titan-Launcher cannot attack far targets (Missile will always explode before hit target )

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#6711]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.9.0.181012` (stable)
**ACE3 Version:** `3.12.4` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- I do not know this is a vanilla game problem or an ACE problem, but I know that ACE3 has its own shooting and guidance system for Titan Launcher, so I’m contacting you.  

If I shoot by means Titan Launcher at far enemy vehicles (approximately >= 1 km) then the AT-missile or AP-missile,  will explode in the air, before it reaches the target. 
It looks strange, as if it is limited by the game-balance, but it does not look realistic. There is no reason for a missile explode in the air, until it touches any physical object. 

If the missile explosion is caused by a restriction for the balance of the game, make it impossible to aim for long distances. But if the missile was already launched from the launcher, then it should not explode in the void, it looks stupid. 
 
ACE team, If it possible, please correct this...

**Steps to reproduce:**
- shoot at far targets.

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by bux** [comment]
Feature Requests go to #3594

**Comment by ZeusWrath** [comment]
THIS IS NOT Feature Requests!

**Comment by ZeusWrath** [comment]
This is looks like a BUG!

**Comment by ZeusWrath** [comment]
Hey where are you ? Do you think this is not a bug?
ACE have self Missile launcher system. So I, as a user, have a reason to fix this bug. But instead of an adequate response, you called my ticket - Feature Requests and immediately closed it :/
