### ISSUE TITLE
AI Heal Without Bandages

### ISSUE THREAD

**Issue by distractor2004** [acemod/ACE3#6713]
**Arma 3 Version:** `1.84` Stable 
**ACE3 Version:** `3.12.4` Stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- AI will heal themselves even if they do not have bandages.

**Steps to reproduce:**
- Start editor and add an AI with ACE Medical AI enabled. Remove all bandages and then inflict a wound on the AI that does not cause it to go unconscious. The AI will heal itself even if there are no bandages in it

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer)

**Additional information:**
- I propose that the AI should check if they have bandages in their inventory, then consume a bandage if present to heal themselves. Otherwise, the AI should call for a medic in their group, or request that a non-medical AI with bandages heal them if a medic is unavailable.

**Comment by commy2** [comment]
This is intended behavior apparently.

**Comment by BaerMitUmlaut** [comment]
AI don't usually have custom loadouts with enough medical supplies, this is intended behaviour.

**Comment by Italiandrache** [comment]
I really think that the choice should be left to the mission maker..... At least as a script command.
An example of a ruined mission concept: https://forums.bohemia.net/forums/topic/229050-need-help-disabling-ace-ai-healing-only-in-a-specific-unit/
