### ISSUE TITLE
No entry 'bin\config.bin/CfgMagazines.ACE_Chemlight_HiOrange' .

### ISSUE THREAD

**Issue by diveyez** [acemod/ACE3#6716]
**Arma 3 Version:** `1.84.xxx` (stable [X]/ rc / dev)
**CBA Version:** `3.x.x` (stable[X] / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable[X] / dev + commit hash)

**Mods:**
```
[X] CBA_A3
[X] ace
```

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.
No entry 'bin\config.bin/CfgMagazines.ACE_Chemlight_HiOrange' .
When loading mission files on dedicated server, even a new mission file with NOTHING in it.
**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
When loading mission files on dedicated server, even a new mission file with NOTHING in it.
**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
DEDICATED WINDOWS SERVER x64
**Additional information:**
- Provide any additional information that will help us solve this issue.
No entry 'bin\config.bin/CfgMagazines.ACE_Chemlight_HiOrange' .
**RPT log file:**
- Do not have a log file at the moment, will update
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by commy2** [comment]
Needs RPT file.
