### ISSUE TITLE
ps90 fire mode

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#6720]
**Arma 3 Version:** `1.86` (stable /
**CBA Version:** `3.12.5` (stable / 
**ACE3 Version:** `3.9.0` (stable / 

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
all p90 have single\full shooting mode of fire. WHY PS90 HAVEN'T?????

**Steps to reproduce:**
CHECK arsenal
http://joxi.ru/YmE3zZMF0XLVPA

**Comment by Drofseh** [comment]
The P90 is a fully automatic version for military and police.
The PS90 is a semiautomatic version for civilians.
This is the way they are in real life.
