### ISSUE TITLE
Ace requiring Arma 3 loadorder

### ISSUE THREAD

**Issue by Rich513** [acemod/ACE3#6724]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- On start up get error message as shown in image. Ace_main requires addon 'A3_data_Fmod_loadorder'

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- When starting Arma
![2018_12_08_error]
(https://user-images.githubusercontent.com/18681374/49700778-d74c9d00-fba8-11e8-848c-b287b4bf815e.png)

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by commy2** [comment]
Please upload your RPT file.

**Comment by dedmen** [comment]
Don't load the ADR-97 mod from the workshop, and verify your Arma files via Steam.

**Comment by MyHobos** [comment]
Been running into the same issue on a dedicated server, no issues client-side but can't seem to run any missions with ACE in the mission file. Posting this below so as not to make an extra thread for y'all to get a headache over. No ADR-97 mod, already verified Arma files on both client and server.

**Arma 3 Version:** Stable, latest.
**CBA Version:** Stable, latest.
**ACE3 Version:** Stable, latest.

**Mods:**
-CBA_A3
-ace
Have also tried this with various combinations including the RHS collection and TFAR.

**Description:**

On server start up get error message as shown in image above from OP. 
(ace_main requires addon 'A3_data_Fmod_loadorder')
When trying to load missions with ACE modules or any new mission templates made with ACE loaded, reverts back to load/mission screen after pushing past the map/briefing screen.

**Steps to reproduce:**

Literally just turning on the server for the first error.
Attempting to load any mission with ACE with the second error after pushing past the briefing screen. 

**Where did the issue occur?**

All scenarios for the first error.
Any scenario with ACE for the second error.

**Additional information:**

[arma3server_x64_2018-12-24_21-10-18.txt](https://github.com/acemod/ACE3/files/2708163/arma3server_x64_2018-12-24_21-10-18.txt)

Uploaded RPT file of just a regular boot, not loading any scenarios. Please let me know if you need more; just trying to narrow down where the fatal error is. Cheers, and Merry Christmas!

**Comment by MyHobos** [comment]
Cheers lads, much appreciated. Happy Holidays!
