### ISSUE TITLE
AI need to take damage while unconscious or Delay Cease Fire Unconciousness needs to be changed

### ISSUE THREAD

**Issue by KidIrie** [acemod/ACE3#6725]
**Arma 3 Version:** 1.82.144647 (stable / rc / dev)
**CBA Version:** 3.6.1 (stable / dev + commit hash)
**ACE3 Version:** 3.12.2 (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Friendly AI units continue to blast away at unconscious enemy units until revive timer is finished. This becomes a problem if I need to search the downed enemy or even be nearby since their firing ends up hitting me (through ricochets) or each other (when they step into each other's line of fire). Grenades are also thrown at close range (which obviously injures everybody), they burn through magazines. and it just looks plain silly...

From what I understand, unconscious units don't ever take damage. I like to play with a long revive time, but the "Delay Cease Fire of AI for Unconsciousness" setting maxes out at 30 seconds. I believe these are the issues, correct? I'm basically coding illiterate, so changing the delay cease fire setting in the mission files is probably out unless it's super easy. For realism sake, I think it would be much better to have a "units take damage while unconscious" enable/disable setting available.

**Steps to reproduce:**
Set Max Revive Time in setting to 300 seconds. Place friendly and enemy units in Editor and have them shoot each other up. Advance and hover around an unconscious unit with your squad around and watch them blast away at the downed unit (and at you and themselves accidentally) almost non-stop for the full 300 seconds.

**Where did the issue occur?**
- Everywhere

**Comment by KidIrie** [comment]
Yeah, I tried setting that Delay Cease Fire to 30 and 0, but got the same results. 

So 0 is supposed to make unconscious AI hidden? If that's the case, maybe I've got some other ACE settings that are interfering with it? I'm walking a fine line, because I still want to be able to treat my own unconscious AI (and have plenty of time to do so), but I'm not opposed to them ignoring unconscious enemy AI if need be.

Thanks for any help anybody can give me!

**Comment by KidIrie** [comment]
I was hoping one of the devs would jump in & comment on this issue. I'd like to find out if: A) others aren't experiencing this problem, so there's something wrong with my settings or B) it's a glitch in the AI or Revive programming and hopefully will be corrected in the near future. 

Again, my thoughts are that unconscious AI should be able to take damage. Why would a downed person suddenly become invincible? It also makes sense to be able to "finish off" the enemy.

**Comment by alganthe** [comment]
You enabled revive for both AI and players, revive stops people from dying until the timer runs off.

This is working as intended and is by design.

Since your AI friendlies are spotting the downed units they're just emptying mag after mag into them because they're expecting them to die.

**Comment by KidIrie** [comment]
Thanks alganthe, but a little confused here. As a single player, I want to be able to have myself and my friendly AI units enabled for revive. Is there a way to allow friendly AI to be revived but turn it off for enemy AI? 

If not then I'm stuck with the issue, which is extremely annoying (and potentially deadly). If that's by design, then I could really use a way to enable (at least enemy) units to take damage while downed - a more realistic option anyway IMO.

Or another commented that the Delay Cease Fire of AI for Unconsciousness setting was intended to make downed units "invisible". I'd settle for that if that were the case, since I could then set Delay Cease Fire longer then the Max Revive Time.

**Comment by commy2** [comment]
"Delay Cease Fire of AI for Unconsciousness" sounds to me like it sets how long it takes for the downed units to become invisible, not how long they stay invisible.

**Comment by commy2** [comment]
Probably because the player avatar spots the downed enemy AI, and thus they are revealed for the friendly AI group members as well.

The unkillable AI setting just doesn't work for SP they way you want to. Issue title is misleading.

**Comment by KidIrie** [comment]
OK, so I guess I got it then. In single player, if I want myself and my friendly AI to able to revive, it must also be so for the enemy. No settings will change this. While downed and waiting to be revived, all units become invincible (can't take any damage). No setting will change this. Friendly AI can't determine the enemy is invincible so will keep firing at them until the revive time runs out and the enemy dies on his own. No setting will changes this.

I can set Delay Cease Fire of AI for Unconsciousness to 0, which will make all downed units become invisible. However if I get too close to a downed enemy, he is looked at as "a threat" again and the friendly AI goes back into their endless firing loop. No settings will change this.

Thanks for getting me through this guys, but it is a bummer. I know Arma is primarily designed for the multiplayer market, where this wouldn't be an issue, but it would be nice if us single players got a little love too! My new years wish then will be to hope that any one of those "no settings will change this" mentioned above could have a setting that can be tweaked by the user. I'm not a programmer so I'm sure some or all might require a ton of work, but I'll keep hoping just the same.

**Comment by KidIrie** [comment]
@commy2 
It wasn't clear in this post that my dilemma was ever acknowledged or would ever be considered now or anytime in the future by the devs. I tried to bring it up again (but in a clearer fashion) under ticket #6725, but you shut me down there.

I have the utmost respect for what the devs at ace have done for the arma community. However the issue I've brought up has risen to the top of my frustration list, so I thought I'd bring it up again in a more focused manner. If it's something you guys don't want to deal with because it's not an issue with your target market, then just tell me and I'll reluctantly accept it for what it is.

**Comment by commy2** [comment]
Don't think there is ill will in me closing the other ticket, but I think there should be only one for every issue. The comments you wrote in the other ticket are still linked here, so nothing is lost.

**Comment by KidIrie** [comment]
Not having a setting to allow AI to take damage while unconscious is still a very big pet peeve with ACE for me. Myself and my AI teammates often times get shot and killed by a friendly AI unit who opens fire at close range on an unconscious enemy unit. Also, if playing a mission which requires you to kill a particular unit or clear an area of enemy units who are knocked unconscious, I have to wait around helplessly while the unconscious unit(s) bleeds out because I can't deliver a "killing shot".

I know this is an old post, but is this issue even a consideration for the devs?

**Comment by Drofseh** [comment]
Medical is currently in the process of being completely rewritten.
