### ISSUE TITLE
Arsenal - TFAR radio being lost

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#6727]
**Arma 3 Version:** `1.88` (stable / rc / dev)
**CBA Version:** `3.9.0` (stable / dev + commit hash)
**ACE3 Version:** `3.12.5` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- TFAR (Stable)
```

**Description:**
-Using Ace arsenal when you have a TFAR radio in your kit and you select the `communications` tab and your radio gets wiped. 
Noticed that it does not save TFAR radio (or load them in) and on respawn

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Virtual Arsenal

**Additional information:**
- The effect seems to be caused by the way TFAR hides the real radio class.

**Comment by dedmen** [comment]
Use TFAR 1.0 beta.
Not a ACE issue.
