### ISSUE TITLE
Stamina bar visible when disabled in CBA Settings

### ISSUE THREAD

**Issue by TheNightstalk3r** [acemod/ACE3#6729]
**Arma 3 Version:** `1.88` stable
**CBA Version:** `3.9.0` stable
**ACE3 Version:** `3.12.5` stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
The player stamina bar is visible to player even if the player setting and the server (enforced) setting has it disabled.

**Steps to reproduce:**
Set following settings in CBA for dedicated server
```// ACE User Interface
force force force ace_ui_allowSelectiveUI = true;
force force ace_ui_staminaBar = false;
```
And do the same for the client settings.
Place soldier in editor, start sprinting. Stamina bar will become visible.

**Where did the issue occur?**
- Dedicated, Self-Hosted Multiplayer, Singleplayer, Editor (Singleplayer), Editor (Multiplayer), Virtual Arsenal

**Comment by jonpas** [comment]
Isn't that vanilla stamina bar that is still visible, and not the ACE3 on?

**Comment by TheNightstalk3r** [comment]
Shouldn't be it since the custom difficulty the mission uses is defined in the server profile as ```class DifficultyPresets
{
	class CustomDifficulty
	{
		class Options
		{
			reducedDamage=0;
			groupIndicators=2;
			friendlyTags=0;
			enemyTags=0;
			detectedMines=0;
			commands=1;
			waypoints=1;
			tacticalPing=0;
			weaponInfo=1;
			stanceIndicator=0;
			staminaBar=0;
			weaponCrosshair=0;
			visionAid=0;
			thirdPersonView=1;
			cameraShake=1;
			scoreTable=0;
			deathMessages=0;
			vonID=0;
			mapContent=0;
			autoReport=0;
			multipleSaves=0;
		};
		aiLevelPreset=3;
	};
	class CustomAILevel
	{
		skillAI=0.75;
		precisionAI=0.55000001;
	};
};```

**Comment by BaerMitUmlaut** [comment]
Advanced fatigue has its own stamina bar setting: `ace_advanced_fatigue_enableStaminaBar`.

**Comment by TheNightstalk3r** [comment]
//toomanystaminabars!aaaaah!!

thanks for the hint @BaerMitUmlaut 
That should solve it.

**Comment by jonpas** [comment]
Oh I didn't even realize you were modifying the UI component one!
