### ISSUE TITLE
ACE SERVER MISSING ADDONS

### ISSUE THREAD

**Issue by Tio91101** [acemod/ACE3#6739]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.9.0` (stable)
**ACE3 Version:** `3.12.5` (stable)

**Mods:**
```
- CBA_A3
- ace
- A3-Antistasi Altis BLUFOR
-Enhanced Movement
-ShackTac User Interface
-Advanced Towing
-Advanced Urban Rappelling
-ACE Compat -RHS United States Armed Forces
-ACE Compat - RHS Armed Forces of the Russian Federation
-Immerse
-Enhanced Soundscape
-DynaSound 2
-RHSAFRF
-RHSUSAF
-RHSGREF
-ACE Compat - RHS: GREF
-Align
-Cartridge Cases
```

**Description:**
- My friends are getting an ace version mismatch on some specific things when someone tries to join a server I host.

**Steps to reproduce:**
- I host a server, (both me and friend have the exact same modset loaded), he simply joins the server, ACE VERSION MISMATCH.

**Where did the issue occur?**
- Self-Hosted Multiplayer
**Additional information:**
- I've tried reinstalling the game several times, including the mods. Nothing seems to work. This is a last resort for me, I have no idea how to resolve this.
**RPT log file:**
![arma 3 issue](https://user-images.githubusercontent.com/45951558/50115861-9bec4700-0216-11e9-888e-4322ddd95f8b.jpg)

**Comment by Tio91101** [comment]
https://gist.github.com/Tio91101/64dfb273f3c1df1296d0c2a2a9bd28c1 @bux

**Comment by commy2** [comment]
Script error, probably broken module:
```
15:51:19 Error in expression <};
_leader = _possibleLeaders select 0;
_leader setvariable ["BIS_HC_scope",_log>
15:51:19   Error position: <_leader setvariable ["BIS_HC_scope",_log>
15:51:19   Error Undefined variable in expression: _leader
15:51:19 File A3\modules_f\HC\data\scripts\hc.sqf, line 71
```
But I don't think that's the issue here.

>15:51:18 [42848,168.536,0,"XEH: PostInit started. MISSIONINIT: missionName=A3-Antistasi%20Altis%20BLUFOR, missionVersion=53, worldName=Altis, isMultiplayer=true, isServer=true, isDedicated=false, CBA_isHeadlessClient=false, hasInterface=true, didJIP=false"]

Local hosted MP as the OP says, but I can't see any refs to the apparently connecting clients missing any addons the server has. Maybe those are not logged can't remember.

I can't find anyone named "Evan" connecting though.

>both me and friend have the exact same modset loaded

Looks to me like you don't have the same modset loaded. Would need the RPT from one of your buddies to show the differences.

Maybe also try on a mission with less scripts, but afaik it should work anywhere as long as everyone has the same addons.

**Comment by Tio91101** [comment]
https://gist.github.com/Tio91101/9b66428062e8e8285a22e20ca4d00423

@commy2 

This is the crash report from my buddy. We played locally BTW.

**Comment by commy2** [comment]
Try again with only CBA and ACE started on an empty mission / freshly created mission.

**Comment by Tio91101** [comment]
@commy2 

I tried testing a few different scenarios to get the error.

First, with all 17 mods loaded, I tried to host an empty mission file. My friend joined and there was NO error.

Second, with all 17 mods loaded, I tried to host an Antistasi mission, we get this error.
![arma 3 issue](https://user-images.githubusercontent.com/45951558/50240683-628d1600-0393-11e9-8d7e-b236e63de0a2.jpg)

Third, with only ACE and CBA_A3, I tried to host an Antistasi mission, and got this error.
![arma 3 issue 2](https://user-images.githubusercontent.com/45951558/50240720-818ba800-0393-11e9-9489-39d6c0716073.jpg)

So the problem has boiled down to an issue between the Antistasi mission and ACE. Is there any way to fix this??

**Comment by commy2** [comment]
I note that the message is different between only CBA/ACE and the full mod set.

You forgot to test the whole modset with a fresh mission.

>So the problem has boiled down to an issue between the Antistasi mission and ACE.

Probably. Seems so.

>Is there any way to fix this??

There always is, but it requires effort and time and someone skilled to look into it. Probably alterations to that mission or maybe even a pull request for ACE.

**Comment by Tio91101** [comment]
@commy2 

What do you suggest I do to help fix it?

**Comment by Jaegerhaus** [comment]
Our group had the same issue running Antistasi with different mods but including ACE on a dedicated server.

We got around it by setting `ace_common_checkpboscheckall` to `false` in the mission addon settings - easiest way is: edit the mission and go Settings > Addons > ACE Common and tick the override box to the right of "Check All".

Seems like some race condition with `ace_settingsInitialized` EH running `fnc_checkPBOs` but that's just a hunch.

Hope that helps!

**Comment by commy2** [comment]
Anyone upload that mission? The only thing I can think of is the mission breaking postInit by putting a waitUntil or sleep in there in the main scope.

**Comment by Tio91101** [comment]
@Jaegerhaus , Thank you for the advice. I will try this ASAP, I'll let you know if it worked!

**Comment by TheMagnetar** [comment]
Since this has not been updated, I guess that the given solution has worked. Closing it.
