### ISSUE TITLE
CBA keybinding triggers all non-set keys on 0 input

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#674]
Still not fixed. onKeyDown triggers with DIK 0 on each frame which causes every non-set hotkey to fire repeatedaly.

**Comment by ViperMaul** [comment]
Is this believed to be a CBA issue?

**Comment by commy2** [comment]
Yes.

**Comment by NouberNou** [comment]
I have no idea how to fix this. The keyhandler exits if DIK 0 is received, and I have no means to reproduce your situation Commy.

**Comment by commy2** [comment]
I'll take a look with the depbo'd files.

**Comment by commy2** [comment]
Can't reproduce anymore with updated repository. Was probably an outdated CBA version.
