### ISSUE TITLE
Add treatment location in Activity Log in Medical Menu

### ISSUE THREAD

**Issue by Will-Nichols** [acemod/ACE3#6740]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.x.x` (stable)
**ACE3 Version:** `3.x.x` (stable)

**Mods:**
```
- ace
```

**[Feature Request] Change to how Activity Log in Medical Menu shows information:**
- Instead of the current way that ACE Medical tells you as a person providing medical care in the game the standard "Nichols has bandaged patient" or whoever the medic is that did the bandaging, morphine, tourniquet, etc... As shown in this image:

[https://steamcommunity.com/sharedfiles/filedetails/?id=1594595034](https://steamcommunity.com/sharedfiles/filedetails/?id=1594595034) 

It would be nice for the Activity Log to show where exactly and what type of bandage was placed on the patient for either that medic or the next one should something happen to the original one; so that they aren't just redoing the same things over and over.

**Steps to reproduce:**
- No need to reproduce as this is a Feature Request to change how the Activity log displays information.

**Comment by Drofseh** [comment]
https://github.com/acemod/ACE3/issues/3594

**Comment by bux** [comment]
@Drofseh it's fine

**Comment by Drofseh** [comment]
That steam community hyperlink takes you to the ace issues page.

**Comment by Will-Nichols** [comment]
>           That steam community hyperlink takes you to the ace issues page.

Takes you to the image of the activity log. Its the same picture I showed to @alganthe on Slack yesterday. I didn't know this page was here yesterday after searching for it while I was working on some real money work. 

Sorry @Drofseh 👍 will get it right now that I have the link in the future.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
