### ISSUE TITLE
ace error: chemlights.pbo out of date

### ISSUE THREAD

**Issue by diveyez** [acemod/ACE3#6748]
**Arma 3 Version:** `Updated Today` (stable)
**CBA Version:** `Updated Today` (stable)
**ACE3 Version:** `Updated Today` (stable)

**Mods:**
```
- CBA_A3
- ace
- others
```

**Description:**
- Today it said some mods updated, ace among them, now I make a new scenario launch and it says 
![image]()

**Steps to reproduce:**
- Add the steps needed to reproduce the issue: Launch a brand new scenario.

**Where did the issue occur?**
- 3den
**Additional information:**
- I have no idea.
**RPT log file:**
-not at computer anymore, can give later.

**Comment by BaerMitUmlaut** [comment]
That PBO is outdated, as the error says. I don't know how you manage your mods, but whatever you use, it missed that PBO.
