### ISSUE TITLE
Wondering about an issue with the results of getAllHitPointsDamage...

### ISSUE THREAD

**Issue by morgoth0** [acemod/ACE3#6753]
**Arma 3 Version:** `1.88.145285` (stable / rc / dev)
**CBA Version:** `3.9.0.181012` (stable / dev + commit hash)
**ACE3 Version:** `3.12.5.40` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- Tested with mods, vanilla A3 and A3 with just CBA_A3 and ACE3
```

**Description:**
So I have added a bug report to BI on this issue: https://feedback.bistudio.com/T135846

The basic issue is that certain A3 vanilla uniforms seem to screw the hit selection entries returned by getAllHitPointsDamage. Wondering whether this is an issue for ACE?

For example, in the following, the three entries are the return from that function for a Civilian CUP uniform, then a vanilla ARMA3 ghillie, then switching to one of the new CUP UBACS uniforms:

CUP Civilian Uniform:
[["hitface","hitneck","hithead","hitpelvis","hitabdomen","hitdiaphragm","hitchest","hitbody","hitarms","hithands","hitlegs","hitleftarm","hitrightarm","hitleftleg","hitrightleg"],["face_hub","neck","head","pelvis","spine1","spine2","spine3","body","arms","hands","legs","hand_l","hand_r","leg_l","leg_r"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]

ARMA Vanilla Ghillie:
[["hitface","hitneck","hithead","hitpelvis","hitabdomen","hitdiaphragm","hitchest","hitbody","hitarms","hithands","hitlegs","hitleftarm","hitrightarm","hitleftleg","hitrightleg"],["face_hub","neck","head","pelvis","spine1","spine2","spine3","body","arms","head_hit","hand_r","hands","leg_l","legs","hand_l"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]

CUP BAF UBACS Uniform:
[["hitface","hitneck","hithead","hitpelvis","hitabdomen","hitdiaphragm","hitchest","hitbody","hitarms","hithands","hitlegs","hitleftarm","hitrightarm","hitleftleg","hitrightleg"],["","neck","head","pelvis","spine1","spine2","spine3","body","","hands","legs","hand_l","hand_r","leg_l","leg_r"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]

All were taken in game without a logout

**Steps to reproduce:**
In the virtual arsenal just switch uniforms and in the deug console run getAllHitPointsDamage player.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Virtual Arsenal

**Comment by dedmen** [comment]
And the ACE bug in here is..... what?

**Comment by commy2** [comment]
I don't get it, but I like the username.

**Comment by morgoth0** [comment]
I wasn't sure whether the values returned in the hit selection array not matching their equivalents position in the hit point name array would cause any inconsistencies in hit reporting. For example I am displaying a broken leg icon in the HUD based on damage to the leg, but in the array hitrightleg is associated with the hand_l selection.

If it is actually not an issue and hit point damage will be reported correctly then that is good despite the inconsistency then that is good.

**Comment by commy2** [comment]
Yeah, that sniper suit is probably fucked up. I remember, a long time ago, the helicopter pilot suits had problems as well. It probably breaks something, but since this is an issue with the Ghillie model itself, or maybe its config, no one here will do anything about it. No one should ever wear these butt ugly things anyway. They even glow and make you stand out from the terrain, because alpha textures and bad materials.
