### ISSUE TITLE
Text is too big in several places

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#676]
Here you can see that text is too big and don't fit into UI:
http://i.imgur.com/kUomc99.png

**Comment by jaynus** [comment]
Your aspect ratio scale looks wrong. Your upper right window is not on the far-right alignment like it should be.

Please fix your video and graphics settings under Video->Display and get the calibration images correct.

Also, please follow the reporting bug guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by ruPaladin** [comment]
ACE3 Version: custom 14.04.2015

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
No

Description:
I have a monitor 19" 1280x1024 (5:4) and my ACE config screen looks like that:
http://i.imgur.com/kUomc99.png
Upper right window is placed there for my personal taste via game settings (Settings-Game).
Also I found that text on map is too big:
http://i.imgur.com/Fh36cpm.png
Here is my video settings:
http://i.imgur.com/P8Stfqv.png

Steps to reproduce:
Probably you will need 19" 1280x1024 monitor with Russian translation enabled.

Where did the issue occur?
In game when you can go to ACE settings.

RPT log file:
No
