### ISSUE TITLE
vanilla altimeter still displayed / disabling it doesn't work

### ISSUE THREAD

**Issue by Marcel1802** [acemod/ACE3#6762]
**Arma 3 Version:** `1.88.145285 stable`
**CBA Version:** `3.9.0` stable
**ACE3 Version:** `3.12.5` stable

**Mods:**
```
- CBA_A3
- ace
- RHSUSAF
- RHSSAF
- RHSAFRF
- RHSGREF
- the 3 compability mods (rhs & ace)
```

**Description:**
- the vanilla altimeter / speed is still shown at the top of the screen even is I disabled it in the addon config on the server (not mission file or client)
- the arma3.vars.ArmA3Profile says 'force force ace_parachute_hideAltimeter = true;'

**Where did the issue occur?**
- multiplayer / dedicated server

**Additional information:**
- tried to disable and enable it, restartet the server etc.

**Comment by mharis001** [comment]
I believe this was fixed by #6721 .

**Comment by alganthe** [comment]
This is indeed the case @mharis001

**Comment by PabstMirror** [comment]
Will be fixed in next release
