### ISSUE TITLE
Unable to lock-on with the NLAW

### ISSUE THREAD

**Issue by Elkin369** [acemod/ACE3#6765]
**Arma 3 Version:** Stable  (stable / rc / dev)
**CBA Version:** `3.9.0` (stable / dev + commit hash)
**ACE3 Version:** `3.12.5` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
-3CB BAF Equipment
-3CB BAF Units
-3CB BAF Verticals
-3CB BAF Weapons
-RHSAFRF
-RHSUSAF 
```

**Description:**
Unable to use the lock-on feature of the NLAW Vanilla and 3CB. The square/diamond and tone dont appear when holding the lock key as they used to.
I have checked the keybinding hasn't changed.

**Steps to reproduce:**
Point the NLAW at a vehicle and hold lock key and nothing happens.

**Where did the issue occur?**
All of these - Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
The issue has only come about in the last couple ACE versions.

I am able to add anything else if needed.

**Comment by bux** [comment]
You omitted the RPT file.

**Comment by Elkin369** [comment]
Full modded game - https://pastebin.com/UkzsUjAE
Just CBA and ACE - https://pastebin.com/LpXyJR7B

**Comment by Blutze** [comment]
Am I missing something here? ACE is supposed to remove the magical vanilla locking system and replace it with https://ace3mod.com/wiki/feature/nlaw.html, and the 3cb NLAW has native compatibility to use the ACE system if both mods are running. Sooo... everything working as intended?

**Comment by Elkin369** [comment]
Okay that makes sense so it is deliberate then. Was just confused how the feature disappeared all of a sudden. Thank you very much :)
