### ISSUE TITLE
How to randomize player damage?

### ISSUE THREAD

**Issue by RangerOfTheOrder** [acemod/ACE3#6767]
This is not an issue but rather a question
How do I inflict randomized damage to players? The reason I ask is I would like to modify ALIAScartoons' "Strigoi" script to be compatible with ACE damage.

https://steamcommunity.com/sharedfiles/filedetails/?id=1395604511

Currently the script uses
_player setDamage ((getdammage player) + _damage_strig);_
to inflict damage. "_damage_strig" is a modifiable parameter that determines how much damage the strigoi inflicts per hit. I know I can use 
[player, 0.1, "SELECTION", "bite"] call ace_medical_fnc_addDamageToUnit
to an an avulsion to the player, but I need to know how to randomize the SELECTION

**Comment by RangerOfTheOrder** [comment]
I figured it out, i ended up using
_selection = selectRandom ["body","head","hand_r","hand_l","leg_r","leg_l"];

[player, 0.2, _selection, "stab"] call ace_medical_fnc_addDamageToUnit;

**Comment by PabstMirror** [comment]
looks good, one thing to keep in mind is add damage to unit needs to be called where unit is local,
so for a zombie script you would want to do something like this:
```
// Run on all machinese:
["pabst_addDamPass", {_this call ace_medical_fnc_addDamageToUnit}] call CBA_fnc_addEventHandler;


// Add damage to unit
private _spot = selectRandom ["hand_l", "hand_r", "leg_l", "leg_r", "leg_l", "leg_r"];
["pabst_addDamPass", [_target, 0.8, _spot, "stab"], _target] call CBA_fnc_targetEvent;
```
That will allow passing damage from where the zombie is running (probably the server) to the client's machine
