### ISSUE TITLE
NV overlay disappears in optic view in FFV seats

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#6769]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.9.1` (stable)
**ACE3 Version:** `3.12.5` (stable)

**Mods:**
```
- CBA_A3
- ace
- Other mods (didn't test with CBA + ACE3 alone yet)
```

**Description:**
- NVG overlay disappears when scoping in (using optics) in FFV seats (occured in Assault Boat).

**Steps to reproduce:**
- Scope in with NVGs in FFV seat.

**Where did the issue occur?**
- Dedicated

**Additional information:**
- N/A

**RPT log file:**
- N/A

**Comment by jonpas** [comment]
Didn't test with CBA+ACE3 alone yet, I'd just forget about it if I wouldn't open this issue.

**Comment by alganthe** [comment]
Reproduced with:
CBA 3.9.1 stable
ACE 3.12.5 stable

Only happens when scoped in, all vehicle types.
