### ISSUE TITLE
Generation 4 Night vision effect for all Compact NVG and ENVG-II models and more FOV for ENVG-II

### ISSUE THREAD

**Issue by trockengranulat** [acemod/ACE3#6775]
**Arma 3 Version:** `1.88.145285` (stable)
**CBA Version:** `3.9.1` (stable)
**ACE3 Version:** `3.12.5` (stable)

**Mods:**
- CBA_A3
- ace

**Description:**
- All APEX Compact NVG and ENVG-II NVGs only have a Generation 3 Night vision effect, what feels too weak for this kind of equipment (especially in relation to the "NV Goggles (Gen4)" from ACE). It also would be more realstic if the ENVG-II would get a slightly higher FOV due to the distance betweeen the lenses.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
- I already have "fixed" the generation 4 effect by myself with this small modification in the CfgWeapons.hpp:

    };
    class O_NVGoggles_hex_F: NVGoggles { // APEX NVG with multiple lenses (spider eyes)
        modelOptics = "";
        GVAR(border) = QPATHTOF(data\nvg_mask_quad_4096.paa); // Use quad tube mask
        GVAR(bluRadius) = 0.26;
		GVAR(generation) = 4;
    };
	class NVGogglesB_blk_F: NVGoggles { // APEX NVG/Thermal
        modelOptics = "\A3\weapons_f_exp\reticle\ENVG.p3d"; // use vanilla modelOptics so it will show in IR mode
		GVAR(generation) = 4;
    };
    class NVGogglesB_grn_F: NVGoggles {
        modelOptics = "\A3\weapons_f_exp\reticle\ENVG.p3d";
		GVAR(generation) = 4;
    };
    class NVGogglesB_gry_F: NVGoggles {
        modelOptics = "\A3\weapons_f_exp\reticle\ENVG.p3d";
		GVAR(generation) = 4;
    };

and config.bin:

	};
	class O_NVGoggles_hex_F: NVGoggles
	{
		modelOptics="";
		ace_nightvision_border="\z\ace\addons\nightvision\data\nvg_mask_quad_4096.paa";
		ace_nightvision_bluRadius=0.25999999;
		ace_nightvision_generation=4;
	};
	class NVGogglesB_blk_F: NVGoggles
	{
		modelOptics="\A3\weapons_f_exp\reticle\ENVG.p3d";
		ace_nightvision_generation=4;
	};
	class NVGogglesB_grn_F: NVGoggles
	{
		modelOptics="\A3\weapons_f_exp\reticle\ENVG.p3d";
		ace_nightvision_generation=4;
	};
	class NVGogglesB_gry_F: NVGoggles
	{
		modelOptics="\A3\weapons_f_exp\reticle\ENVG.p3d";
		ace_nightvision_generation=4;
	};

But it would be awesome if that could be standard after the next updates.

**Comment by dedmen** [comment]
If you already have the code ready, why not make a PR?
https://github.com/acemod/ACE3/blob/86a243d3cc76287aabb78b9d03c97e061015f6d7/addons/nightvision/CfgWeapons.hpp#L9-L19
Config classes except the _blk_ one are already there.
Seems weird that we are missing the blk one 🤔

**Comment by LinkIsGrim** [comment]
Gen 4 effect handled by #9369. I think ENVG FOV is fine as it is.
