### ISSUE TITLE
Text is too big in several places

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#678]
ACE3 Version: custom 14.04.2015

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
No

Description:
I have a monitor 19" 1280x1024 (5:4) and my ACE config screen looks like that:
http://i.imgur.com/kUomc99.png
Upper right window is placed there for my personal taste via game settings (Settings-Game-Layout).
Also I found that text on map is too big:
http://i.imgur.com/Fh36cpm.png
I think it will be good to have possibility to change text size on map, btw.
Here is my video settings:
http://i.imgur.com/P8Stfqv.png

Steps to reproduce:
Probably you will need 19" 1280x1024 monitor with Russian translation enabled.

Where did the issue occur?
In game when you can go to ACE settings.

RPT log file:
No

**Comment by PabstMirror** [comment]
Thanks for the screenshot of your video settings.
Looks like we were missing text height in config.

As for the map

In ace_map we change sizeExLevel = 0.03; from 0.02
and sizeExGrid = 0.032; from 0.02

You can change interface to small (Маленький) to shrink the size of these numbers.

**Comment by ruPaladin** [comment]
Problem solved.
