### ISSUE TITLE
missing ace files

### ISSUE THREAD

**Issue by colmaniac** [acemod/ACE3#6781]
I have an error pooping up shortly after getting into game.  Says :- Noentry bin\config.bin/cfgweapons.ACE_M84

I have done a fresh install.  Deleted all mods and started again.  I am running current up-to-date ARMA3,  running up-to-date C2 command&control,ace,cba A_3, A3-Antistasi Altis BLUFOR

**Comment by commy2** [comment]
Needs RPT file.

**Comment by colmaniac** [comment]
sorry can you give me more info please?

**Comment by commy2** [comment]
**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by colmaniac** [comment]
[Arma3_x64_2019-01-20_09-54-04 - Copy.zip](https://github.com/acemod/ACE3/files/2776972/Arma3_x64_2019-01-20_09-54-04.-.Copy.zip)

**Comment by colmaniac** [comment]
rename the file as .rpt,  it wont let me upload original file

**Comment by commy2** [comment]
ZIP seems broken.
```
---------------------------
Error
---------------------------
C:\Downloads\Arma3_x64_2019-01-20_09-54-04.-.Copy.zip
The archive is either in unknown format or damaged
---------------------------
OK   
---------------------------
```

**Comment by Zakant** [comment]
It's not a zip file but a renamed .rpt. Just change the file extension ;)

**Comment by commy2** [comment]
`player addWeaponCargoGlobal ["ACE_M84", 1]`
->
`Warning Message: No entry 'bin\config.bin/CfgWeapons.ACE_M84'.`

Because it is a mag and not a weapon. No missing files, just a broken third party script. Close?

**Comment by colmaniac** [comment]
Hi, on raiding outposts and looting the stashes there is blank spaces but numbered where you see the items in the list. how do I alter the line to repair/remove the error?  Thanks

**Comment by bux** [comment]
Don't hijack closed issues.

**Comment by colmaniac** [comment]
Do I need to modify a file to fix the problem?

**Comment by commy2** [comment]
Probably the mission, but it may be an addon as well, in which case you can only disable it, unless you are the author.

**Comment by colmaniac** [comment]
ok, thanks, ill have a look there :)
