### ISSUE TITLE
Radar/SAM Sites do not fire

### ISSUE THREAD

**Issue by BSherb** [acemod/ACE3#6782]
**Arma 3 Version:** `1.88` (stable / rc / dev)
**CBA Version:** `3.9.1`
**ACE3 Version:** `3.12.5.40`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Static AA for CSAT (Specifically the RADAR, and SAM sites) do not work as intended. SAM sites track targets but do not fire, RADAR site occasionally tracks target but otherwise stays idle. (Possible that other factions have similar issues)

**Steps to reproduce:**
- Place Radar
- Place SAM Launchers
- Place Enemy Helicopters
- Watch nothing get shot

**Where did the issue occur?**
- Dedicated/Singleplayer

**Comment by alganthe** [comment]
You have to group the radar with the launchers.

This is not an ACE related issue, closing.

**Comment by BSherb** [comment]
I did this 2x, once in full vanilla. Once with only ACE/ACEX/CBA
Both times I did it the same way with the Radar and SAM's ungrouped.
In vanilla they work absolutely fine, just place them down and they work. Once ace is added, that is not the case.
I've tried grouping them and they still don't fire.
