### ISSUE TITLE
Arrest pow?

### ISSUE THREAD

**Issue by colmaniac** [acemod/ACE3#6785]
I am running current up-to-date ARMA3, running up-to-date C2 command&control,ace,cba A_3, A3-Antistasi Altis BLUFOR

In ACE I should have the ability to arrest a pow and escort them.  How do I arrest them?  I have read I need to press the "windows" key then select arrest.  I have pressed and held down the winkey on a solder that surrendered, and get a radial come up on the body parts but there is no arrest icon.  are there any video`s that show how to do it?

**Comment by bux** [comment]
I'm closing this because of your repeated laziness to fill out our issue template. Please provide the information necessary or you can't expect help.
