### ISSUE TITLE
Laser pointer renders in the first raycasted object for observer

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#6786]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.9.1` (stable)
**ACE3 Version:** `3.12.5` (stable)

**Mods:**
```
- CBA_A3
- ace
- Other mods (didn't test with CBA + ACE3 alone yet)
```

**Description:**
- Laser pointer renders in the first raycasted object, instead of being hidden behind it.

![20190119161143_1](https://user-images.githubusercontent.com/7935003/51548316-65829700-1e68-11e9-9f96-7d1906b3793c.jpg)
![20190119161142_1](https://user-images.githubusercontent.com/7935003/51548327-674c5a80-1e68-11e9-9f33-f288c9c3759e.jpg)
_Note: Player next to the wall is not intersecting the laser! Not the ideal screenshots._

**Steps to reproduce:**
- Make an X player turn on laser pointer and aim it at a wall.
- Look at it from 45° from player X
- Make another player Z stand between you and the wall.
- Observe laser now being on the player Z instead of where it's pointed at by the laser player X.

**Where did the issue occur?**
- Dedicated

**Additional information:**
- Only visible like that to observer.

**RPT log file:**
- N/A

**Comment by jonpas** [comment]
Courtesy of @Drofseh:
![](https://i.gyazo.com/8a3578aee21e8313a0aea94e5da6d857.png)

**Comment by dedmen** [comment]
Would be explained if we ray traced from the observer to the target. Which doesn't happen.

https://github.com/acemod/ACE3/blob/master/addons/laserpointer/functions/fnc_drawLaserpoint.sqf
The code is raytracing from the target, in his weapon direction and takes the first intersection.
It's not tracing from the local player. It only takes position and directions from the target (the origin unit who holds the laser)


https://github.com/acemod/ACE3/blob/master/addons/laserpointer/functions/fnc_drawLaserpoint.sqf#L47
That is weird. _unit is the player, and it's in the ignore list.
Meaning the laser will just pass through the player? Like if the origin is behind you and he's shining through you. Then it will not consider the intersection on your own body.
That's kinda dumb.

**Comment by jonpas** [comment]
Another case, marked this time:
![](https://i.imgur.com/Cin3xSm.png)

It shouldn't render in this case at all and it should be a lot smaller.

**Comment by jonpas** [comment]
This is still an issue in 3.13.0. Laser point/dot is also way too big at certain distances.

**Comment by PabstMirror** [comment]
To do this correctly we need 2 ray casts,
1: from laser forward to see where dot should be
2: from player view to laser dot to see if we have visibility to it

**Comment by LinkIsGrim** [comment]
ACE laserpointer was nuked in #9411
