### ISSUE TITLE
Interaction Menu stuck

### ISSUE THREAD

**Issue by jgp3199** [acemod/ACE3#6795]
**Arma 3 Version:** `stable up to date` (stable / rc / dev)
**CBA Version:** `stable up to date` (stable / dev + commit hash)
**ACE3 Version:** `3.12.5 stable` (stable / dev + commit hash)
.
**Mods:**
Too many to list
- CBA_A3
- ace
```

**Description:**
- The interaction menu gets stuck even when I release the key. Self interaction menu works fine though. 
**Steps to reproduce:**
- Enter any mission and hold windows key, then let go. 

**Where did the issue occur?**
- Editor singleplayer

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- Not sure what this part is but i don't believe it applies to this situation as the game continues to run fine.

**Comment by PabstMirror** [comment]
Some gaming keyboards will semi-disable the windows key, you might want to try rebinding ace's interaction key to something else and see if it improves at all.

**Comment by jgp3199** [comment]
> Some gaming keyboards will semi-disable the windows key, you might want to try rebinding ace's interaction key to something else and see if it improves at all.

That worked! Much appreciated man, thank you!

**Comment by PabstMirror** [comment]
great, I think I've some keyboard have a little switch to turn the feature on or off
it might also be from a keyboard driver software, and that might have an option to turn off
