### ISSUE TITLE
ACE map breaks user made waypoints on map. 

### ISSUE THREAD

**Issue by ZEROxxxCOOL** [acemod/ACE3#6798]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
users can see the way point IN GAME but not ON MAP, makes finding them to delete them a nightmare

**Steps to reproduce:**
turn on ace and try to make a way point marker

**Where did the issue occur?**
- Dedicated 

**Additional information:**
tried a server difficulty override to force way points to work, no go, 
**RPT log file:**
reports show NO errors, simply the little white/black dot that appears when a player hit "SHIFT + RIGHT CLICK

**Comment by bux** [comment]
If you want help, please take the time and fill out the issue template correctly.

**Comment by ZEROxxxCOOL** [comment]
latest Arma version stable
latest CBA version stable
latest Ace version stable

MODS
HAFM Core+Boats+Subs
Exile
Extended Base
Cup weapons
Cup vehicles
Cup units
CBA3
Ace
Ace Attachment switching
Ace Extended menu
Immersion

DESCRIPTION 
users can see the way point IN GAME but not ON MAP, makes finding them to delete them a nightmare
the "SHIFT+RIGHT CLICK" player made distance marker.

steps to reproduce;
it always happens, cant get it to work correctly and show both on map and in first person

WHERE
on my dedicated server.

ADDITIONAL INFO
no errors show up on INFISTAR. and the way point DOES show, only during game play, not once a player has opened his map, none show ON MAP.

REPORT LOG
ill attach one later when i get home and have access, but there are no signs of any errors that would cause this.

**Comment by ZEROxxxCOOL** [comment]
MORE ACCURATE MOD LIST

advanced towing
immerse
jsrs
jsrs cup weapons
jsrs cup vehicles
HAFM subs
HAFM boats
HAFM core
cup weapons
cup units
cup vehicles
cup terrains map
cup terrains core
extended base
ace interaction menu expansion
ace attatchment switching
ace 3.12.6
cba3 3.10.1
exile

**Comment by ZEROxxxCOOL** [comment]
sorry this problem aint like a game breaker, trying to solve this at work on my free time. dont have access to the server till later in the day
