### ISSUE TITLE
ACE_AI.pbo outdated

### ISSUE THREAD

**Issue by xmastersrule** [acemod/ACE3#6812]
**Arma 3 Version:** `x.xx` (stable  )
**latest steam vesion CBA3:** `3.x.x` (stable)
**latest steam vesion ACE 3:** `3.x.x` (stable )

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
(sorry for bad english)
i made a mission on the map chanarus redux (does it on every map)
added the modules from ravage 
but if i load in the mision i get an ace error it sais (file ACE_AI.PBO is outdated)
i can only choose the option ok end it closes the mission 

**Steps to reproduce:**
- look at the file for errors ?.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) 

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
i hope this is the one
-https://gist.github.com/xmastersrule/fe18f887beace16758722df7f8bc4a21

**Comment by commy2** [comment]
You are loading two copies of ACE. `@ace` and `@ACE - Antistasi Edition`. I suggest you remove either of these.

**Comment by TheMagnetar** [comment]
The question has been answered and the thread has not been active for more than a month. Closing. If any relevant questions arise, don't hesitate to post in here. In that case the issue will be reopened.
