### ISSUE TITLE
RHS MAAWs overpressure is too much

### ISSUE THREAD

**Issue by armyinf0703** [acemod/ACE3#6817]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
RHS
ACE RHS Compat
```

**Description:**
- The M3 MAAWS backblast in the compat is set at     rhs_weap_maaws: Launcher_Base_F {
        ace_reloadlaunchers_enabled = 1;
        ace_overpressure_range = 15;
        ace_overpressure_angle = 70;
        ace_overpressure_damage = 0.75;

This in game translates to what is compared to even the vanilla maaws or any other AT weapon a huge difference in safety measures needed to ensure the Back blast doesn't knock/ kill friendlies. 

Setting it at 60 which is the default for just about every other launcher.. would be a huge difference and a huge step up for Quality of life, as it currently stands your hard pressed to find a good "safety" zone. 
**Steps to reproduce:**
- Go in game and test it out. 

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by Drofseh** [comment]
According to `B-GL-317-006/PT-001 (WEAPONS VOLUME 6 - SHORT RANGE ANTI-ARMOUR WEAPON (MEDIUM))`

> Backblast.
> Because the gun is recoilless it produces, at the moment of firing, a distinct flash and blast rearwards. The danger area extends 30 meters rearward at an angle of 800 mils to either flank of the line of fire. This area must be clear of any troops, equipment or obstruction at the moment of firing. When siting the weapon it must be realized that the arc of fire will determine the overall backblast area. The gun can be fired from wooded areas as long as there are no major obstacles in the backblast area

So if anything it should be more like 
```sqf
ace_overpressure_range = 30;
ace_overpressure_angle = 90;
```
The Carl Gustaf has a huge backblast IRL because it's a recoilless rifle, not a rocket launcher.

**Comment by Whigital** [comment]
When adding this, I derived the values from the vanilla RPG32, and cranked them up a bit for the _Gustav_. But they should definitely not be decreased as @Drofseh says, rather increased. Check this live firing, wouldn't wanna be anywhere in atleast a 90 deg. cone behind that.

https://www.youtube.com/watch?v=0XyDbQ9rRB8&feature=youtu.be&t=159
