### ISSUE TITLE
NVG: The overlay covers Weapon info, etc.

### ISSUE THREAD

**Issue by Leopard20** [acemod/ACE3#6819]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.9.1` (stable)
**ACE3 Version:** `3.12.5` (stable)

The NVG overlay covers the player status (stance, stamina, mag count, etc, which by default is in the top right corner)

Is it possible to break the NVG overlay into more parts? For example, make the left and right sides of the overlay lighter (reduce alpha), then cover it later with additional CutRsc's according to where the "weapon info" ~CutRsc~ is located.

If you guys don't mind, I'd like to make a request as well. Can you make the overlay size adjustable so we can set how much of the screen we want to cover?

**Comment by commy2** [comment]
WeaponInfo does not use cutX.

**Comment by leopard20** [comment]
Really? Sorry. I thought it did! Nevertheless, what I meant was finding its position and size and avoid covering that area.

**Comment by commy2** [comment]
Yes, valid issue, but that detail was just wrong.

**Comment by leopard20** [comment]
There has to be a way to fix this. Anyone?!
P.S: I found a couple of NVGs that don't have this problem. I don't remember which ATM but I think they were the ones the CTRG and Viper units use.

**Comment by leopard20** [comment]
...

**Comment by GoldJohnKing** [comment]
Yes, this really breaks gameplay... we cant even see the action if it isn't too long...

![image](https://user-images.githubusercontent.com/26923626/123532373-437b5600-d73f-11eb-8405-4604ebac4fcd.png)

**Comment by Salluci** [comment]
Needs support for rendering `cutX` below game UI to be fixed. Gotta bug BI about it.
