### ISSUE TITLE
Color change on ACE menu?

### ISSUE THREAD

**Issue by 2old2bagamer** [acemod/ACE3#682]
I play with a couple folks with less than perfect vision (myself included). Is it possible to put in an option to change the color of the items on the interaction menu so they stand out more? Or if any of the contributors can point me in the right direction, I'd be happy to try to make those changes myself. I'm just not sure where to look.

**Comment by jaynus** [comment]
Let's get this banged out guys; it's along the lines of our considerations for sound issues - we need to consider vision; the menu also needs to consider colorblind types as well as ease-of-reading

**Comment by PabstMirror** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/9376747/7195169/deea07b6-e480-11e4-9999-e846d99e61fa.jpg)

I played around with adding a generic backgroud before drawing all the interaction text.
I think it should decrease the conrtrast//effects of camo and makes text easier to read.
The `tap shoulder` is hard to read in vanilla (left), but really stands out with a white background.  With the negative effect of looking odd, but this can be a user setting.

**Comment by PabstMirror** [comment]
Using colors instead of transparency to show different menu paths.
![2015-04-16_00007](https://cloud.githubusercontent.com/assets/9376747/7195375/1d9372ba-e484-11e4-992c-ff9bfcd509ba.jpg)

**Comment by Jastreb** [comment]
Can you make the color of interaction/self interaction menu adjustable (user setting) by adding RGB sliders and transparency to ACE settings? Similar to one for adjusting the color of weapon temperature check ( I think )?

**Comment by BaerMitUmlaut** [comment]
Currently the text has a shadow, but with setting shadow to 2 it becomes outlined. This would probably also increase readability and contrast.

**Comment by Jastreb** [comment]
See #787, use alpha for better visibility or change color if you prefer more.
