### ISSUE TITLE
[ACE Medical] Units that die switch to their default loadout

### ISSUE THREAD

**Issue by leopard20** [acemod/ACE3#6826]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.9.1` (stable)
**ACE3 Version:** `3.12.5` (stable)

I'm working on a dynamic mission which has a "kit" based system (similar to Squad and Project Reality). I use a base Rifleman "X_Soldier_F" (X is one of B, O, I) to create AI and then change their loadout according to the "kit" they select. 

The problem is, when a unit dies, he switches to the default Rifleman loadout. I was wondering whether it's a bug or is intentional. ~I think you guys delete the old unit and place a new one using its "typeOf", am I right?~
On second thought, even if they don't die completely but rather become "unconscious" they still switch to their default loadout, so I guess you don't delete them!

**Comment by bux** [comment]
When a unit dies and respawns it uses the loadout it's supposed to have - That's vanilla behavior.

When a unit goes unconcious nothing happens with the loadout. At least from ACE's side.

**Comment by leopard20** [comment]
Well, whatever the reason is, I'm sure ACE Medical has something to do with it, because without it everything works fine.
Also, the units are AI and I use a custom respawn system. But regardless of that, this issue happens as soon as the unit "dies" (but it really doesn't because I use a handleDamage EH to make the unit unconscious).
I'll capture a video or something tomorrow.

**Comment by bux** [comment]
maybe you provide all the information we request in the issue template. And please test it with only CBA and ACE on a newly created mission file without any scripts.

**Comment by leopard20** [comment]
As I said, the issue only occurs on my mission, no matter what mods I have loaded. If you think it's not a bug and everything is fine, feel free to close the issue.
