### ISSUE TITLE
Vehiclelock -1 state on setting is misleading

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#6828]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
The first setting is "Default" but i should be named "vehiclelock off" or "off".
If you dont know that it didnt init the vehiclelock on vehicles where is the difference between "Default" and "As is". In my opinion "Default" is misleading.

**Comment by dedmen** [comment]
help wanted label? Should be a easy stringtable fix

**Comment by shukari** [comment]
Fix it... I forgot this issue.
