### ISSUE TITLE
Ace user interface settings interfiere with reticles of scopes and binoculars

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#6834]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.9.1` (stable)
**ACE3 Version:** `3.12.5` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- With "ace_ui_soldierVehicleWeaponInfo" disabled, the overlay masks of scopes and binoculars are unusable.

**Steps to reproduce:**
- Place a soldier with a MOS-scope on his rifle and a rangefinder in his inventory on map.
Start mission. Look through scope and rangefinder. Evethings O.K.
Now disable "ace_ui_soldierVehicleWeaponInfo" in the CBA-Settings configuration and do it again.
The scope's "mask" including reticle has disappeared and the infos about distance, azimut and vision modes of the rangefinder, too.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Additional information:**
![20190225134345_1](https://user-images.githubusercontent.com/15272840/53339011-6003eb00-3905-11e9-99ee-67d266ce1c98.jpg)
![20190225134357_1](https://user-images.githubusercontent.com/15272840/53339012-6003eb00-3905-11e9-86fe-32df86221ac2.jpg)
![20190225134407_1](https://user-images.githubusercontent.com/15272840/53339013-6003eb00-3905-11e9-9dbb-87ce16fda7a0.jpg)
![20190225134427_1](https://user-images.githubusercontent.com/15272840/53339015-609c8180-3905-11e9-93e6-7d73ebcbca5c.jpg)
![20190225134435_1](https://user-images.githubusercontent.com/15272840/53339010-5f6b5480-3905-11e9-967c-e1ca91728eb4.jpg)

**Comment by jonpas** [comment]
Must be attached to that then.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
