### ISSUE TITLE
Walking Animation

### ISSUE THREAD

**Issue by JordanTMeek** [acemod/ACE3#6839]
Simply put, and I know I'm late to the party here, the old animation for walking was more realistic. I know because I walk with an M4 in full battle rattle on the regular. The vanilla method is how we walk. I only bring this up because the patch notes mention that the new animation is more realistic. But with our slings it's simply not.

**Comment by bux** [comment]
You must have taken a wrong turn somewhere. This is ACE3.
If not your issue lacks all the requested information and I don't have a clue what you're talking about.

**Comment by commy2** [comment]
We had this in AGM: https://github.com/KoffeinFlummi/AGM/blob/master/AGM_Movement/config.cpp#L153-L194

But there is no such thing in ACE as far as I can tell.
https://github.com/acemod/ACE3/blob/master/addons/movement/CfgMoves.hpp

Dunno if OP refers to that.

**Comment by jones140** [comment]
Might be because wiki 
referees to Minor Animation tweaks 
https://i.gyazo.com/b71abde98a50e621c485e3d79575432a.png

**Comment by JordanTMeek** [comment]
Regarding Jones' response, that was what I was referring to. I took that to mean that the walking, weapon lowered animation was an ACE change. If that is not the case then I was mistaken.

**Comment by Max255PL** [comment]
It was an ACE change before but then BI changed it themselfs. It's vanilla now.
