### ISSUE TITLE
Unrealistic flaws with Ace3 medical and suggestions to add

### ISSUE THREAD

**Issue by SirMedic** [acemod/ACE3#6840]
This isn't a bug issue. This is to suggest ideas to make Ace3 more realistic. 
I'm a combat medic from Finland.

Unrealistic problems:
1.) Chest seal is the ONLY bandage for chest gunshot wounds (above stomach chest). 
2.) You shouldn't be able to put packing bandage in the chest. 
3.) You shouldn't be able to put packing bandage in the head.
4.) You shouldn't pass out from getting shot in the arm or leg.
(All the major unrealistic flaws i can think of at this moment.)
Eh). Certain blood type per person but i don't think this is a big deal, idc about that. Another thing that isn't that big of a deal like when to give medicine depending on the patients state.

Medical equipment that could be added and have a use:
Chest seal, Tension Pneumothorax Access Kit, suction for airways whether it's a Laerder Suction Unit or other type of suction equipment (to clear airways). 

I'm not suggesting to make a combat medical simulation mod, but you can make it a little more realistic. 

It should be apart of Ace Medical Advanced that you must check and open a patients airways after putting tourniquets on limbs or you'd hear the patients breathing possibly getting worse that could be fatal. 

SUGGESTION EXAMPLE: If a player is blown up by a IED, blood could start to fill and clog the airways as you work to stop catastrophic bleeding, requiring suction (which you would know because you'd hear his breathing getting worse). 

SUGGESTION EXAMPLE: When a player gets shot in the lung/chest, most likely air will escape the lung hole into the chest space for each breath causing pressure/air to build up outside the lung in the chest crushing the lung which would end in suffocation and death, which would require a TPAK or two or 3. (You would know because you'd hear the patients breathing getting worse, and slowly only one side of the chest lifting for every inhale because the other side of the chests lung gets crushed until it cannot inhale).

These kinds of features could be in Ace medical Advanced. I would love to actually have to use cABC DE medical procedure steps in stabilizing a patient. 

Though there are a lot of other medical equipment, some that wouldn't suit a game well (like a thermal blanket), nose tube etc, idk how to suggest a way to implement that to work in game.

**Comment by SirMedic** [comment]
About packing bandage, I mean you don't pack it in the head lol, but you can wrap it around a head wound x_x So i take that back, it isn't a issue.

**Comment by BaerMitUmlaut** [comment]
Please post this here: #3134

**Comment by SirMedic** [comment]
Yo. I just found the email today
