### ISSUE TITLE
Self killed because of uav

### ISSUE THREAD

**Issue by C0kkie** [acemod/ACE3#6841]
**Arma 3 Version:** `1.88` (stable / rc / dev)
**CBA Version:** `3.9.1.181229` (stable / dev + commit hash)
**ACE3 Version:** `3.12.5` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Today i tried to use the uav terminal and controlled a B_UAV_01_backpack_F
then the uav got detroyed and the medical killed eventhandler got triggered and i got killed too. Multiple of my friends reported that too

**Steps to reproduce:**
- Place a B_UAV_01_backpack_F
- destroy it
- you get killed too

**Where did the issue occur?**
- Self-Hosted Multiplaye

**Additional information:**
-  We use advanced medical system
- After i modifed my ace and replaced the !local _unit in handleKilled with
if (!local _unit || {!(_unit isEqualTo player)}) exitWith {};

then it works perfectly and only the uav get killed and not me

**Comment by commy2** [comment]
"medical killed eventhandler"
I am pretty sure there is no such thing.

**Comment by commy2** [comment]
This is how handleKilled is executed:
https://github.com/acemod/ACE3/blob/master/addons/medical/XEH_preInit.sqf#L44

And this is what the function does:
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_handleKilled.sqf#L21-L26

I don't see how the Killed event setting the hearth rate of the UAV dummy to 0 kills the avatar. You need to explain that.

Using the `player` command is absolute poison (here and in most places). That would mean the function loses Zeus compatibility, but it also means the function stops working for AI entirely.

**Comment by TheMagnetar** [comment]
Any new info?

**Comment by C0kkie** [comment]
i will test it later again and try to reproduce it

**Comment by C0kkie** [comment]
You can close this, i wasnt able to reproduce it again
