### ISSUE TITLE
NVGs on Lythium result in pitch black terrain

### ISSUE THREAD

**Issue by Maseddu** [acemod/ACE3#6842]
**Arma 3 Version:** `1.88.145285 ` (stable)
**CBA Version:** `3.9.1` (stable)
**ACE3 Version:** `3.12.5` (stable)

**Mods: **
```
- CBA_A3
- ace
- Lythium
- Jbad
```

**Description:**
- On Lythium all the night vision goggles does not work properly, it is like having just the green color effect and no more, sky is ok, terrain is pitch black, in presence of bright light, full of stars sky and flashlights, still pitch black. When i put the nvg on it start with good brightness then the brightness go down quickly and terrain become total dark.
**Steps to reproduce:**
- Just use any of the NVGs on Lythium on night .
- All the NVGs setting of the ACE gave same issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer).

**Additional information:**
- I asked to Lythium's modders they said "ask to ACE3", i read some comments about Lythium overwriting ACE3 settings, and i saw only two video with nvgs working properly, but they are german and i do not understand german .
- I tried modded night vision goggles that use ACE3 settings.
- I do not tried this map without ACE3.

**RPT log file:**
- I have no log file, i'm sorry, only settings line :
force ace_nightvision_disableNVGsWithSights = false;
force ace_nightvision_fogScaling = 0;
force ace_nightvision_effectScaling = 0.1;
force ace_nightvision_noiseScaling = 0.1;
force ace_nightvision_aimDownSightsBlur = 0;

**Comment by Max255PL** [comment]
I'll pitch in saying that we had the same issue recently BUT apparently one person could see just fine. I'm assuming it's related to graphics settings/GPU generation. 
But yeah, totally terrains fault, I know they had a lot of issues and complaints with the new lighting system.

**Comment by TheMagnetar** [comment]
It looks normal to me.

**Comment by Maseddu** [comment]
an NVG of latest generation have to operate in the lowest light condition, giving the user great visibility in no moon situation.. dark terrain with clear sky full of stars is not so right.... Gen 2 nvg can do better job of the actual situation at least giving a good visibility in 30-60 meters or a bit more.
On lythium with medium/high settings i got total black in 30 cm.

**Comment by alganthe** [comment]
Could you please provide a screenshot, an RPT, and if possible your in game brightness settings.

**Comment by Maseddu** [comment]
I'll provide those info soon...

**Comment by Maseddu** [comment]
Some screen :
https://www.mediafire.com/view/6xln309dba4i3k4/20190303232807_1.jpg/file
https://www.mediafire.com/view/1xe051a4uzlnvkm/20190304003052_1.jpg/file
https://www.mediafire.com/view/02keoysnwbt8zy1/20190303232706_1.jpg/file
https://www.mediafire.com/view/31s2bspu844n312/20190303232711_1.jpg/file
https://www.mediafire.com/view/f5djyjlugyze2r6/20190303232903_1.jpg/file

**Comment by Max255PL** [comment]
Check the date and moon phase, that looks normal for moonless night.

**Comment by alganthe** [comment]
That looks perfectly fine to me for a moonless night, also be aware that the effects appear a lot worse in screenshot than in actual gameplay.

**Comment by GoldJohnKing** [comment]
Our server got the same problem, we had to disable ACE nightvision feature.

At first player enable the nightvision, everything works fine,but after a
short while, no matter staying at a place or moving around, the vision suddenly grow dark, could barely see anything. Players need to shut the nightvision then re-enable it to have it work normally again, but after a short while it goes wrong again...

**Comment by Maseddu** [comment]
You  know guys that is not normal at all? It just apply the green overlay no night vision at all! Goldjhonking got it, we got the same problem...

**Comment by TheMagnetar** [comment]
Can you provide the RPT as well? Note that this is purely client side so it does not depend on the server

**Comment by Maseddu** [comment]
I'm a bit buisy i'll try to up a rpt soon

**Comment by GoldJohnKing** [comment]
@TheMagnetar https://github.com/acemod/ACE3/issues/6842#issuecomment-470259928

I was busy to fix the problems caused by the silly 1.90 update yesterday, sorry to be not detailed.

I think no related info would be shown in rpt file, because I'm pretty sure it's not an typical 'erorr'.

It seems that LYTHIUM has an extra HDR function than valllina HDR, that it will try to raise or lower the average brightness of players to a certain rate after a short delay. If you have doubt about it, please download LYTHIUM and pay attention to the strong HDR difference between LYTHIUM and vallina Altis.

I think that may have conflict with some ACE nightvision function. Once player enables ACE nightvision and have nightvision on, then after a few seconds, the LYTHIUM HDR makes the whole brightness down to a low level, while ACE nightvision down the brightness too, this cause objects and terrains becomes really dark but still can be barely seen. You can see that the birghter the scene is, the darker the objects and terrains would be with ACE nightvision on, which is just opposite to normal circumstances.

Though it shall be LYTHIUM's falut, I personally believe that what ACE should do is to change the method of detection of brightness, based on players' actural brightness, but not on scene brightness (though it seems to be impossible), in case of preventing similar 'potential' issues in advance.

**Comment by PabstMirror** [comment]
Do you happen to know if it's config or script based?
I tried taking a look but I think the pbo was obfuskcated
IIRC the `setApature` command can cause issues, but I'm not sure if that's the problem
A short term fix might be to just add a blacklist of worlds and disable effects on them

**Comment by Maseddu** [comment]
> @TheMagnetar [#6842 (comment)](https://github.com/acemod/ACE3/issues/6842#issuecomment-470259928)
> 
> I was busy to fix the problems caused by the silly 1.90 update yesterday, sorry to be not detailed.
> 
> I think no related info would be shown in rpt file, because I'm pretty sure it's not an typical 'erorr'.
> 
> It seems that LYTHIUM has an extra HDR function than valllina HDR, that it will try to raise or lower the average brightness of players to a certain rate after a short delay. If you have doubt about it, please download LYTHIUM and pay attention to the strong HDR difference between LYTHIUM and vallina Altis.
> 
> I think that may have conflict with some ACE nightvision function. Once player enables ACE nightvision and have nightvision on, then after a few seconds, the LYTHIUM HDR makes the whole brightness down to a low level, while ACE nightvision down the brightness too, this cause objects and terrains becomes really dark but still can be barely seen. You can see that the birghter the scene is, the darker the objects and terrains would be with ACE nightvision on, which is just opposite to normal circumstances.
> 
> Though it shall be LYTHIUM's falut, I personally believe that what ACE should do is to change the method of detection of brightness, based on players' actural brightness, but not on scene brightness (though it seems to be impossible), in case of preventing similar 'potential' issues in advance.

You hit the point, and this happen exactly in the same way to me and to other member of my community, we got differnts pc configs, so this is not a just my problem.

**Comment by alganthe** [comment]
Tested it again, the effect is pretty subtle under good conditions but it is indeed present.

**Comment by MisterHLunaticwraith** [comment]
My unit uses RHSUSAF nvgs and GPNGV18 on Lythium on a daily basis and have had no issues whatsoever.

**Comment by Constance68W** [comment]
Just chiming in, we'd been on Lythium for just under a year playing Liberation with ACE/RHS/Etc and never had this issue.

**Comment by commy2** [comment]
No one seems to be able to reproduce. Close?

**Comment by GoldJohnKing** [comment]
> No one seems to be able to reproduce. Close?

alganthe seems to reproduce the issue: https://github.com/acemod/ACE3/issues/6842#issuecomment-471271273

To reproduce the issue, please be sure to: using ACE NVGs at highlight areas on Lythium, stay still, keep it on and wait for a while, then the picture will encounter a sudden drop of  brightness.

**Comment by Constance68W** [comment]
That's still a negative from me.
No issue for me or the other two I was playing with..

Pulled from the server's CBASettings
// ACE Nightvision
force force ace_nightvision_aimDownSightsBlur = 0;
force force ace_nightvision_disableNVGsWithSights = false;
force force ace_nightvision_effectScaling = 0;
force force ace_nightvision_fogScaling = 0;
force force ace_nightvision_noiseScaling = 0;
force force ace_nightvision_shutterEffects = true;

**Comment by GoldJohnKing** [comment]
Hi, Constance 68W:
According to your settings, you did not enable ACE NVG function.

**Comment by Constance68W** [comment]
Yeah, I realized that a day or so after I posted.

Went back in and tested with OP's settings..
force ace_nightvision_disableNVGsWithSights = false;
force ace_nightvision_fogScaling = 0;
force ace_nightvision_effectScaling = 0.1;
force ace_nightvision_noiseScaling = 0.1;
force ace_nightvision_aimDownSightsBlur = 0;

Either way, still unable to reproduce the issue with brightness/sudden darkness.

**Comment by oldLucke** [comment]
We are having the same problem on our server. Adjusting HDR in the video settings to low helps.

**Comment by Steve161st** [comment]
Our group seems to suffer from this a lot.
I've tried to re-produce this by hosting one of our missions on my own machine.
Initially when joining NVGs work absolutely fine.
A short while later, I have the effect that is described above - on first lowering NVGs, they are OK but quickly fade out. (Our normal issue.)
I've done 2 things between NVGs behaving normally or not - alt tabbing out and into the game and toggling removing/wearing NVGs many times. 

For info, I can confirm that oldLucke's work around of setting HDR settings to low helps dramatically.
(Although breaks my white phosphor overlay effect!)

**Comment by Steve161st** [comment]
Hmmm. Neither of these steps seem to repeatably break the NVG effects.
The issue may be related to the amount of light in the scene - it almost appears that if the scene is quite dark, light levels drop significantly but don't then recover when you go back to lighter places.
I'll keep testing though as I'm not convinced it's as simple as this.

**Comment by Steve161st** [comment]
Actually - it might be the other way round - look at something bright, the HDR effects drop the brightness and this does not revert back when looking somewhere dark.
So what seems to be repeatable for me in this scenario is put on NVGs, look up at the sky for a few seconds. (Initially, the sky is quite bright but after a second or two, there's effects like the auto gating so the scene darkens and more detail can be seen in the sky.) If I then look back at the terrain, it's very dark and does not seem to increase in brightness until I remove and re-fit NVGs.
However, even this effect seems variable based on the time of day/level of overall brightness so is most obvious around 10pm (Oct 2015!)

**Comment by Steve161st** [comment]
OK - one further piece of info, the cloudier it is, the more dramatic the dimming effect is when looking up at the clouds. It seems the clouds are very bright which then causes the NVGs to dim. They don't brighten again when looking away from the sky until you toggle NVG on and off.

**Comment by commy2** [comment]
Why is this on this tracker if it's a problem with the game or the map?

**Comment by Steve161st** [comment]
I guess because it's only an issue when using ACE3 Night vision and Lythium?
The problem doesn't exist with Vanilla NVGs.

**Comment by FrostByte2282** [comment]
I have a similar problem when I'm in a server, but not the host. On a clear, ideal ambient light night sky, with ace settings on, the terrain & objects are all basically indistinguishable & in shadow. Then, with the ace settings off, the night vision is standard vanilla view, but the night sky is washed out in an almost bright white non existent light.

**Comment by brezerk** [comment]
+1 We are able to reproduce this issue :(

This seems to be depend on clouds and Lythium lighting (moon and stars). With clouds being set to >=0.8 you literally can see nothing, unless using some source of light (lighting shells or flashlight)

**Comment by unhappytroll** [comment]
https://youtu.be/W23LrdJZWZ8
this is how it looks like.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
