### ISSUE TITLE
Certain Zeus ACE Interactions not working

### ISSUE THREAD

**Issue by DragonHunter003** [acemod/ACE3#6847]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.9.1` (stable)
**ACE3 Version:** `3.12.5` (stable)

**Mods:**
```
- CBA_A3
- ACE
- ACEX
```

**Description:**
- Specific Zeus ACE Interactions while selecting units did not work properly. The Interactions I couldn't get working were: Rearm and Repair of vehicles and Remote Controlling any unit. Changing combat stance, speed, awareness and formations were are working as expected.

**Steps to reproduce:**
- Open a blank mission file in the editor and place a single character which has access to the Zeus interface.  
- Load the mission, open the Zeus interface and spawn in any unit and vehicle.  
- Attempt to use the ACE Interactions while having any unit selected.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer Editor (Multiplayer)

**Additional information:**
- I have recorded the issue and uploaded it on youtube, the video can be found [here](https://youtu.be/2tecnBvVr3w).

**RPT log file:**
-[pastebin](https://pastebin.com/jYNRhpA9) (Client RPT File)

**Comment by Dystopian** [comment]
`RC` should be fixed in the next release (#6733). `Repair` and `Rearm` are broken in release build time, config is cut off:
`statement = "{ if (_x isKindOf 'AllVehicles' && {!(_x isKindOf 'Man')}";`
I think it will be fixed in the next release too.

**Comment by PabstMirror** [comment]
Should be fixed by those prs
Also on the "game master" module, make sure you have the setting set to
"all addons (unoffical)"
to enable repair/rearm actions
