### ISSUE TITLE
M84 looks gash in advanced throwing

### ISSUE THREAD

**Issue by bovine3dom** [acemod/ACE3#6851]
![look, it's awful](https://i.imgur.com/UAS8L79.png)

dedmen and jonpas suggest it might be an LOD issue.

![this is less bad](https://i.imgur.com/5wuWM5Z.png)

Opening it in Oxygen seems to confirm it - it seems to be using LOD 7:

![oh god why](https://i.imgur.com/MjraOid.png)

**Comment by commy2** [comment]
Delete all distance LODs to fix this.

**Comment by dedmen** [comment]
I'll try to find a better fix. I'll take care of this.

**Comment by commy2** [comment]
Narrator: "He didn't find a better fix."
