### ISSUE TITLE
Sometimes the Titan Launcher Fire mode does not match the icons inside the scope

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#6852]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.9.1.181229` (stable)
**ACE3 Version:** `3.12.5` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- If the player changes the weapon from Titan-Launcher (must be the current Top fire mode) to the primary weapon, and again to the Titan Launcher, then the icons inside scope of Titan Launcher do not correspond to the current fire mode.  Namelly the player's Top fire mode, which is set in the lower right screen corner (small triangle), but the icon inside the Titan Launcher's sight will show the DIR fire mode.

http://images.vfl.ru/ii/1552079353/4c358012/25687883.jpg

 
Video Example - https://www.youtube.com/watch?v=lcpbM6mzKXQ&feature=youtu.be

But If a player changes weapons from Titan-Launcher (currently Direct fire mode) to the primary weapon, then the icons will correspond to their fire mode!

 It seems, that the problem depends on the currently Fire-mode in which the player will change his launcher to the primary weapon.

**Comment by PabstMirror** [comment]
Should be fixed by #6732

**Comment by ZeusWrath** [comment]
Thanks for answer, I hope this issue will fixed
