### ISSUE TITLE
Disarming Caching problem

### ISSUE THREAD

**Issue by C0kkie** [acemod/ACE3#6857]
**Arma 3 Version:** `1.90` (stable / rc / dev)
**CBA Version:** `3.9.1.181229` (stable / dev + commit hash)
**ACE3 Version:** `3.12.5` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- multiple building & car mods
```

**Description:**
- Since we added ace disarming to our server we noticed that it sometimes happen, that if someone looks into the gear from a other guy, that he can see sometimes more items that a player has. For example he see that the player has 20 magazines. if the players check which get disarm he has only 16 magazines (he had 20 few minutes ago but not now)

So in some cases is there a sync problem or caching problem

**Steps to reproduce:**
- We dont now how exactly to reproduce it, we just got multiple reports about that

**Where did the issue occur?**
- Dedicated

**Comment by commy2** [comment]
>looks into the gear from a other guy
???

**Comment by C0kkie** [comment]
I mean if he opens the dialog to see the inventory from the other guy

**Comment by commy2** [comment]
The backpack?

**Comment by C0kkie** [comment]
What you mean with "the backpack" ?

**Comment by Drofseh** [comment]
@commy2 I believe @C0kkie is referring to there being synchronization issues in this UI.

![](https://i.gyazo.com/be52de203dd5c4ae63a1097129a03496.png)

**Comment by C0kkie** [comment]
Exactlly

**Comment by jonpas** [comment]
There are also major synchronization issues with boxes and JIP, I don't think there is much we can do.

**Comment by C0kkie** [comment]
So this is a known arma issue?

**Comment by PabstMirror** [comment]
Does desync happen before or after removing items?

**Comment by C0kkie** [comment]
Befor, its already desync if you open the dialog (but not always, sometimes its synced)
