### ISSUE TITLE
Overheating. Loud and unused sounds

### ISSUE THREAD

**Issue by severgun** [acemod/ACE3#6861]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.9` (prev stable)
**ACE3 Version:** `3.12.5` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS
...
```

**Description:**
1.  ACE Overheating module have very loud(far audible) jamming sound which can be heared I think ~100m away.
2.  There is unused files and config defined sounds

**Steps to reproduce:**
- Go multiplayer. Get weapon jam event. Listen from far away.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
Define 10m or so?
https://github.com/acemod/ACE3/blob/842f9e5d3bedf18d69974950908c328ddb10bcb0/addons/overheating/functions/fnc_jamWeapon.sqf#L58

**Comment by dedmen** [comment]
Easy fix. Set distance parameter to 10-15m

```sqf
playSound3D ["a3\sounds_f\weapons\Other\dry9.wss", _this select 0, false, [0,0,0], 1, 1, 15]; 
```

**Comment by severgun** [comment]
Yes. What about dead files and code?
