### ISSUE TITLE
Always civ side after handcuffed

### ISSUE THREAD

**Issue by C0kkie** [acemod/ACE3#6867]
**Arma 3 Version:** `1.90` (stable / rc / dev)
**CBA Version:** `3.9.1.181229` (stable / dev + commit hash)
**ACE3 Version:** `3.12.5` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Today i noticed that if i get handcuffed on west side, that if i check via (side player) it returns CIV but if i check via playerside it returns WEST
If the handcuffs get removed it returns west again via side player

I am not 100% sure if its because of ace or a problem with another mod. But it happens if i use the handcuff function from ace.

**Steps to reproduce:**
- Handcuff a Person and check via side player and playerside command

**Where did the issue occur?**
- Dedicated

**Comment by alganthe** [comment]
This is part of the feature, firing at cuffed / surrendered people is against the laws of war.

**Comment by C0kkie** [comment]
What has that firing at cuffed people to do with that they switch side if you handcuff them? Can you show me the part in the code where it is doing that? I cant find that and i want to disable the sideswitch

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/blob/master/addons/captives/functions/fnc_setHandcuffed.sqf#L43

**Comment by C0kkie** [comment]
So just remove that will fix the "problem" ? Has that any other impact?

**Comment by C0kkie** [comment]
ah i think i found it, is it this?

https://community.bistudio.com/wiki/setCaptive

**Comment by alganthe** [comment]
Yes, setCaptive is used.

By default the civ side is friendly to everyone, no unit will fire at them.

**Comment by C0kkie** [comment]
Alright thanks i will try that
