### ISSUE TITLE
ace_hot.pbo is outdated error, just today

### ISSUE THREAD

**Issue by aah11b** [acemod/ACE3#6870]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by PabstMirror** [comment]
need rpt

**Comment by bux** [comment]
Might be the same guy: https://twitter.com/IbissTeam/status/1106361769193324549

**Comment by alganthe** [comment]
Every release it's the same thing, someone who didn't update ACE3 properly or is also loading an older version opens an issue complaining about outdated PBOs.

Every . single . one

@aah11b make sure you're not loading an older version along with it, when updating ACE3 DELETE the older folder, do NOT drag the new one over the old one.

**Comment by commy2** [comment]
Adding this message was the best thing we ever came up with. Imagine if people played with their broken installations without being notified about it.

**Comment by aah11b** [comment]
Ive been using ACE for four days, now, and Arma for only two months.

**Comment by aah11b** [comment]
Cut me some slack, Jack.

**Comment by commy2** [comment]
I think it's just frustration from reading the same supposed problem over and over again for many years. Anyway, if you post the RPT file, it should be easy to figure out what went wrong with your installation.

**Comment by PabstMirror** [comment]
I think the only way this error could happen is if someone has a copy of 3.12.6 and then applied a copy of 3.12.5 on top of it.
ace_hot didn't exist in 3.12.5 so it wouldn't be downgraded

Make sure you have only one copy of ace in your mod list and make sure it is a clean version from github (delete the existing `@ace` folder and then re-extract)

if using steam workshop, from arma launcher click on ace and then hit the 3 dots and hit repair

**Comment by TheMagnetar** [comment]
The question has been answered and the thread has not been active for more than 10 days. Closing. If any relevant questions arise, don't hesitate to post in here. In that case the issue will be reopened.
