### ISSUE TITLE
Q:Removing All interaction on a unit/Object

### ISSUE THREAD

**Issue by jones140** [acemod/ACE3#6873]
**Arma 3 Version:** `stable ` 
**CBA Version:** `3.9.1` 
**ACE3 Version:** `3.12.5` 

**Description:**
- Looking for a Simple Way to remove Interactions on Objects and units as i have 1 object i am using for a arsenal and would like to clear all actions around it to avoid confusions 
-See attached Img for better explination [[https://i.imgur.com/TDRJbYb.jpg](https://i.imgur.com/TDRJbYb.jpg)]

**Steps to reproduce:**
- N/A

**Where did the issue occur?**
- N/A

**Additional information:**
- N/A

**RPT log file:**
- N/A.

**Comment by PabstMirror** [comment]
This might not be ideal, but it should work.
1. Add arsenal like normal (ie, this code doesn't add virtual items)
2. Claim the object, blocking other actions (including the normal arsenal action)
3. Re-add a new arsenal action that will always run

```
[bob, bob] call ace_common_fnc_claim; // should prevent any other action that checks canInteractWith

private _action = ["myArsenal", localize "STR_A3_Arsenal", "", {
    params ["_target", "_player"];
    [_target, _player] call ace_arsenal_fnc_openBox;
}, {
    true // don't check canInteractWith
}] call ace_interact_menu_fnc_createAction;

[bob, 0, ["ACE_MainActions"], _action] call ace_interact_menu_fnc_addActionToObject;
```

**Comment by jones140** [comment]
probably should of explained those interactions are from 3 different objects.
looking for just simple way to remove it from 2 of the objects 
it inst a propriety of actions problem 
eg 1 is a seat with acex sit-down action.
2 is a unit would like to remove all action from him 

obj 3 that i have arsenal on is Invisible Wall and is working fine

**Comment by Whigital** [comment]
Looked through the interact code for this too but couldn't find a magic variable.

Maybe add something like:
```
if (!(_target getVariable ["ace_interact_interactable", false])) exitWith {false};
```
to `ace_common_canInteractWith`. That would enable the option to set `ace_interact_interactable` on objects/units to disable interaction.

**Comment by commy2** [comment]
Pabst posted the answer already. Close?

**Comment by jones140** [comment]
sadly 
even trying Whigital  idea i cannot get a unit to not have any interactions 
maybe this could be looked at for part of ace options in eden as a check box

**Comment by commy2** [comment]
What's wrong with what Pabst posted?

**Comment by jones140** [comment]
i believe what he posted is if it was same object and other actions were in way on one object How ever i just need to remove all Actions from a different object as i stated in my reply [Maybe i am interpreting it improperly sorry]

**Comment by commy2** [comment]
He posted how to remove all actions from an object. Via init box it would look like this:
```sqf
[this, this] call ace_common_fnc_claim;
```

**Comment by jones140** [comment]
works perfectly cant believe how stupid i was being 
thank you again
