### ISSUE TITLE
problem with setting to "videosettings" with ace_viewdistance

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#6874]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- with ace viewdistance setting to "videosettings" it is always 1600 on a dedicated server. It wont use your own videosettings of the ingame menu

**Steps to reproduce:**
- set in addon option under "ace viewdistance" any values to "videosettings"
- then go an a server
- check your viewdistance in your videosettings menu and the viewdistance with the command `viewdistance` it wont match

**Where did the issue occur?**
- Dedicated

**Comment by alganthe** [comment]
The server owner is enforcing that view distance.

**Comment by shukari** [comment]
How? It is not the viewdistance of the serverprofile. Is this only set per command in the mission.

But than the setting is missleading in multiplayer.

**Comment by jonpas** [comment]
But that's exactly what vanilla settings says as well. :thinking:

**Comment by BloodSoakedBandit** [comment]
The group I'm with haa that problem as well.

**Comment by TheMagnetar** [comment]
The question has been answered and the thread has not been active for more than 10 days. Closing. If any relevant questions arise, don't hesitate to post in here. In that case the issue will be reopened.
