### ISSUE TITLE
Temperature change

### ISSUE THREAD

**Issue by BDPWarrior** [acemod/ACE3#6877]
Hi, I wanted to ask if there is any way of changing the environment temperature in ACE 3 mod. I'm currently making a mission for my unit on Chernarus Winter and it would be weird to have all the snow around but 15 degrees Celsius.

**Comment by severgun** [comment]
I think you need to create PBO with config entries like this
https://github.com/acemod/ACE3/blob/master/addons/weather/CfgWorlds.hpp

**Comment by diwako** [comment]
You can use `ace_weather_temperatureShift` to subtract or add temperature. If you want to make it colder, assign a minus value to this variable on all machines.

**Comment by TheMagnetar** [comment]
The question has been answered and the thread has not been active for more than 10 days. Closing. If any relevant questions arise, don't hesitate to post in here. In that case the issue will be reopened.
