### ISSUE TITLE
RHS RGN & RGO grenades bug

### ISSUE THREAD

**Issue by Ranz2** [acemod/ACE3#6878]
**Arma 3 Version:** `1.90` (stable / rc / dev)
**CBA Version:** `3.10.1` (stable / dev + commit hash)
**ACE3 Version:** `3.12.6` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
-RHSAFRFDEV
-RHSUSAFDEV
-RHSGREFDEV
-RHSSAFDEV
```

**Description:**
- As of RHS' dev builds, the RGO and RGN impact grenades will not detonate when thrown using ACE Advanced Throwing, but will act normally if the vanilla throwing mechanic. 

**Steps to reproduce:**
- Simply throwing the grenades using Advanced Throwing.

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Virtual Arsenal

**Additional information:**
- I did report this issue with their team first, and they told me to report the issue to the ACE devs.

**RPT log file:**
https://pastebin.com/itpGAC4J

**Comment by commy2** [comment]
That's not the RPT file.

**Comment by PabstMirror** [comment]
don't worry about rpt,
rhs changed inheritance and scripts, 
but its actually good news, see PR

**Comment by Ranz2** [comment]
Thanks

**Comment by commy2** [comment]
Close when PR is merged.
