### ISSUE TITLE
RHS helmet incorrect hearing protection values

### ISSUE THREAD

**Issue by Slatery** [acemod/ACE3#6884]
**Arma 3 Version:** `1.90` (**stable** )
**CBA Version:** `3.10.1.190316` (stable)
**ACE3 Version:** ` 3.12.6` (stable)
**ACEX Version** `3.4.2` (stable)
**Mods:**
```
- CBA_A3
- ACE
- ACEX
- ACE Compat - RHSUSAF
- RHSUSAF
```

**Description:**
- The MICH 2000 (Semi-Arid/Norotos/ARC), (rhsusf_mich_bare_norotos_arc_semi), has unwarranted hearing protection, even though the model does not include any sort of Ear-pro.
Similarly, the FAST Ballistic (Multicam Cover/Headset/NSW) (rhssusf_opscore_mc_cover_pelt_nsw),FAST Ballistic (Urban Tan/Headset/NSW) (rhssusf_opscore_ut_pelt_nsw), and IHADSS (rhsusf_ihadss) have no hearing protection.

**Steps to reproduce:**
1. Start with selected mods: ACE, ACEX, RHSUSAF, ACE Compat - RHSUSAF
2. equip one of the above mentioned helmets

**Where did the issue occur?**
- All known places

**RPT log file:**
converted to txt file for upload
[Arma3_x64_2019-03-22_18-54-10.txt](https://github.com/acemod/ACE3/files/2995650/Arma3_x64_2019-03-22_18-54-10.txt)

**Comment by PabstMirror** [comment]
Thanks for a great report
