### ISSUE TITLE
How to configure ACE3 within the mission file?

### ISSUE THREAD

**Issue by AnimatekdeCuba** [acemod/ACE3#6886]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.10.1` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Description:**
- Excuse me for doing this here

I need you to refer me to some guide for dummies to add additional configurations for the ACE3 within the mission file.
For example:
- Define which boxes and objects should be able to move with the ACE3 interaction menu and which ones can not.
- How to call the levels of hunger, thirst and stamina to save them in a DB based on SQL.
- Register kills, deaths and Revives for statistics and Killfeed.

(my goal is to integrate it with AgentRev / ArmA3_A3Wasteland)
The wiki of the page is not completely updated, it does not cover all the modules and the information is limited.

For help, even if it's a forum where developers, or fans, can give me a clue.

**Comment by Drofseh** [comment]
Come ask questions like this in the Ace3 Slack
https://slackin.ace3mod.com/

**Comment by AnimatekdeCuba** [comment]
thanks! I will try with some vpn, because I am from a country embargoed. LOL
