### ISSUE TITLE
AGM-88C HARM LOAL broken

### ISSUE THREAD

**Issue by ArwynFr** [acemod/ACE3#6899]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.10.1` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- When fired without a target, HARM missiles are expected to search for a radar source target
- This behavior works correctly in vanilla mode, missiles will lock to opportunist targets
- When ACE is enabled, the missile will ignore any radar source and fly straight
- Works OK with ACE in LOBL mode (lock first, fire second)

**Steps to reproduce:**
- Create an editor mission
- Place a R-750 Cronus Radar and a F/A-181 Back Wasp II facing each other
- Equip the F/A-181 with two AGM-88C HARM missiles
- Play the mission as the F/A-181 pilot
- Select the AGM-88C HARM missiles
- Without locking the target, fire a missile towards the Cronus
- The missile will fly straight
- Works OK in vanilla

**Where did the issue occur?**
- Editor (singleplayer)
- Dedicated

**Additional information:**
- NA

**RPT log file:**
- NA

**Comment by bux** [comment]
Report misses the RPT file

**Comment by ArwynFr** [comment]
Tried again tonight in order to provide an RPT but this time it worked ...
Closing the issue.
