### ISSUE TITLE
Add translations for adv. medical

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#690]
https://github.com/acemod/ACE3/blob/5d8dd701d27008af4b651cb71e72161aa476063e/addons/medical/ACE_Medical_Treatments.hpp#L301-L502

should be translated aswell.

**Comment by bux578** [comment]
Also: 
#708
http://i.imgur.com/WrL1bPR.png
http://i.imgur.com/x0eo0Tx.png

**Comment by ruPaladin** [comment]
Also cannot find this: http://i.imgur.com/nLUshur.png

**Comment by bux578** [comment]
cyrillic is awesome for spotting strings with no translation :)

**Comment by ruPaladin** [comment]
Yeap :+1:

**Comment by meat147** [comment]
CfgVehicles.hpp & ACE_Settings.hpp should be translated aswell

**Comment by ruPaladin** [comment]
Found new text:
1. History of medical manipulations http://i.imgur.com/b6VhYRs.jpg
2. Triage card on self interaction is ok http://i.imgur.com/f1IhZje.png
But when you try to check it on other persons it is untranslated: http://i.imgur.com/677lSWt.jpg
3. Triage card is not translated too: http://i.imgur.com/HHy9U9I.png
