### ISSUE TITLE
Adjusting "ACE_GForceCoef" on individual unit via scripts?

### ISSUE THREAD

**Issue by Drift91** [acemod/ACE3#6908]
First off I apologize if this is the wrong place to post this.

I've been looking at the code of ace_gforces.pbo and was wondering if there's any way that I can set "ACE_GForceCoef=" on an individual unit/player via 3DEN/mission scripts or even on the fly via the debug console or a script. I'd assume something along the lines of `_unit setGForceCoef 0.3` or `[_unit,0.3] execVM ace_fnc_setGFoceCoef` if the functionality is already built into ACE3; Otherwise maybe a more complicated way of overriding the unit class for that individual unit via script. Is this possible or would I need to make a feature request for the former example?

**Comment by 654wak654** [comment]
You need to set the variable `ACE_GForceCoef` on the unit.

````sqf
_unit setVariable ["ACE_GForceCoef", 0.3, true];
```

**Comment by Drift91** [comment]
@654wak654 Thank you, I'll try that out. Also I take it that'll override the value set in CfgVehicles but not CfgWeapons, correct?
