### ISSUE TITLE
When disabling the "Enable Damage" switch or using "allowDamage false", you can remove wheels indefinitely from a vehicle

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#6923]
**Arma 3 Version:** 1.90
**CBA Version:** `3.10.1`
**ACE3 Version:** `3.12.6`

**Mods:**
```
CBA_A3
ACE3
ACRE2
RHSAFRF
RHSUSAF
ace_compat_rhs_afrf3
ace_compat_rhs_usf3
```

**Description:**
- One is able to use the Interaction "Remove Wheel" multiple times (more than 4) on that vehicle on the same wheel

![20190405084826_1](https://user-images.githubusercontent.com/1235520/55608873-ac9dda00-577f-11e9-86a5-20b60560cd70.jpg)

**Where did the issue occur?**
- Dedicated 

**RPT log file:**
https://hastebin.com/raw/ayirihizof

**Comment by Dystopian** [comment]
I would like to take the issue.

**Comment by bux** [comment]
Go for it @Dystopian

**Comment by Dystopian** [comment]
Can't repro with just ACE and RHS.
RPT https://hastebin.com/raw/egufuyamoz (almost the same lines for addons).

**Comment by bux** [comment]
Now that I think of it, it might be one of those switches:
![image](https://user-images.githubusercontent.com/1235520/55664815-dbc25300-5834-11e9-9c4e-245a90cf0d42.png)

**Comment by bux** [comment]
Yep, it's the "Enable Damage" switch.

![20190406063206_1](https://user-images.githubusercontent.com/1235520/55664866-c1d54000-5835-11e9-996a-10193ad53424.jpg)

Either disable the remove wheel action if it is set, or enable _dammage_ - remove wheel - and disable _dammage_ .

**Comment by commy2** [comment]
I think I know how to fix that.
