### ISSUE TITLE
Land_PortableLight_single_F turn around when trying to change height

### ISSUE THREAD

**Issue by severgun** [acemod/ACE3#6926]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.10.1` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS
- ...
```

**Description:**
- When you try to carry Land_PortableLight_single_F(maybe other objects) and change height, it will turn around facing to you. I would like to see turn action(as in ace_fortify) or keep direction as it was at start carrying or at least turn it in players direction.

**Steps to reproduce:**
- Start carry lamp.
- Check lamp direction.
- Scroll mouse wheel to change height.
- Check lamp direction.

**Where did the issue occur?**
- Dedicated

**Comment by alganthe** [comment]
Could you provide an RPT or a debug dump of your settings ? 

I'm unable to reproduce the issue.

**Comment by dedmen** [comment]
Is that the about human-height worklight lamp? I experienced same issue too. But it seemed rather random to me.

**Comment by severgun** [comment]
https://community.bistudio.com/wiki/File:Arma3_CfgVehicles_Land_PortableLight_single_F.jpg

**Comment by dedmen** [comment]
>https://community.bistudio.com/wiki/File:Arma3_CfgVehicles_Land_PortableLight_single_F.jpg

I had the problem with the double variant of that. I assume it's the same

**Comment by alganthe** [comment]
That bug is fickle, managed to reproduce it, most likely related to CBA EHs.

**Comment by severgun** [comment]
For me it can be reproduced ONLY on dedicated. 
At editor (SP/MP) when I try to carry lamp it attach to me facing forward. On dedicated it is always facing to me and change direction with some delay after drop. Also, some kind of surface placing/intersection involved.

https://youtu.be/lhB-PLgTH2M

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
