### ISSUE TITLE
XM307 Static can't be rearmed, when settings are "rearm whole magazine"

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#6928]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.10.1` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Title.

**Steps to reproduce:**
- Place a man, an ammo truck and a static XM307 on map. Empty the magazine of the weapon by attributes. Set Ace-logistic-settings to "rearm whole magazine". Now start the mission and try to rearm the weapon. Well in fact, you can do all the interaction stuff and all progress bars run through, but in the end, there won't be ammo in the weapon.  

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Additional information:**
- Happens to all versions of the weapon. With XM312 (HMG) it works just fine.

**Comment by jonpas** [comment]
Fixed in #7609.
