### ISSUE TITLE
RHS Vehicle Interior Lights

### ISSUE THREAD

**Issue by sargken** [acemod/ACE3#6934]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `3.12.6` (stable / dev + commit hash)
**ACE3 Version:** `3.10.1.190316` (stable / dev + commit hash)

**Mods:**
- RHS USAF, AFRF, GREF, SAF
- CBA_A3
- ace3 & ACE/RHS Compats

**Description:**
- Running ACE 3 with RHS will break scripted lighting on RHS vehicles, either the high beams don't work or Toggle Interior Lights in Helicopters and the C-130 does nothing. 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
- Spawn a CH-47 and turn on the Lights and try to toggle the interior lights nothing works. 
**Where did the issue occur?**
Editor / Multiplayer

**Additional information:**
- Base Class or Unit Config

**Comment by dedmen** [comment]
Can confirm interior lights not working in my modpack. But that could have all kinds of causes. No idea if my issue is caused by ACE

**Comment by Constance68W** [comment]
Interior lighting works with RHS and ACE in the mod set that I use.

**Comment by commy2** [comment]
Close?
