### ISSUE TITLE
Spotting Rifle produces backblast.

### ISSUE THREAD

**Issue by Neciota** [acemod/ACE3#6943]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.10.1` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ACE3
- CUP Weapons
- CUP Units
- CUP Vehicles
- Custom LAW80.
```

**Description:**
- The spotting rifle on a custom LAW80 and the CUP SMAW produces backblast, despite having backblack values set to 0 in config, in the spotting scope entry subclass of the weapon.

**Steps to reproduce:**
- Go into editor as USMC AT Specialist (SMAW).
- Point weapon in sky.
- Fire.
- Be unconscious with bleeding legs.

**Where did the issue occur?**
- Editor (Singleplayer)

**Additional information:**
- I guess the muzzle entry needs to be checked when executing backblast code?

**Comment by commy2** [comment]
>in the spotting scope entry subclass of the weapon

These entries are only read from the main class.

>spotting rifle on the CUP SMAW

I was searching for this info, thanks.

**Comment by dedmen** [comment]
The SMAW has a seperate spotting ammunition type.
http://tikka.ws/class/index.php?b=cfgMagazines&c=rhs_mag_smaw_SR&conf=1

>These entries are only read from the main class.

Should be read from magazine.

**Comment by commy2** [comment]
So the SMAW is from RHS and not CUP. Or is it in both?

>Should be read from magazine.

They are read from the weapon and that's good, but to handle launchers with secondary muzzles, we have to change it so you can specify them in the muzzle config too, and then those take precedence.
No idea what's going on in the link you posted. RHS has ACE config entries? If so, these are wrong.

**Comment by severgun** [comment]
> No idea what's going on in the link you posted. RHS has ACE config entries? If so, these are wrong.

This is class browser of AFI modpack
http://tikka.ws/class/index.php

ace settings from here
https://github.com/acemod/ACE3/blob/17f4af37faa583daccc1a28804a8f1886e8cd4ad/optionals/compat_rhs_usf3/CfgMagazines.hpp#L20

**Comment by commy2** [comment]
CUP SMAW will be fixed in the next update. This is just a matter of making the configs compatible with ACE.
Here is an example of how the CUP Team did it:
```cpp
  class CUP_SMAW_Spotting: CA_Magazine
  {
    scope = 2;
    author = "$STR_CUP_AUTHOR_STRING";
    dlc = "CommunityUpgradeProject";
    displayName = $STR_CUP_dn_smaw_spotting_M;
    descriptionshort = $STR_CUP_dss_smaw_spotting_M;
    picture = "\CUP\Weapons\CUP_Weapons_Ammunition\data\ui\m_as50_ca.paa";
    ammo = "CUP_R_SMAW_Spotting";
    count = 5;
    mass = 10;
    initspeed = 220;
    ace_overpressure_angle = 0;
    ace_overpressure_range = 0;
    ace_overpressure_damage = 0;
    ace_overpressure_priority = 99;
  };
```
