### ISSUE TITLE
Problem with fuel nozzle (when it fall uder some objects)

### ISSUE THREAD

**Issue by markooff** [acemod/ACE3#6944]
**Arma 3 Version:** 1.90 (stable)
**CBA Version:** 3.9.1 (stable)
**ACE3 Version:** 3.12.5 (stable)

**Mods:**
- CBA_A3
- ace
- TFAR
- RHS USAF, AFRF, GREF
- CUP Core, maps
- Enchanced Movements

**Description:**
- Error in positioning of the fuel nozzle (after it has been dropped) on such things like carrier board , narbour pier, etc..

**Steps to reproduce:**
- It is simple - just take the fuel nozzle , go a few steps and then drop it. 
Then You cannot take it back because it has fallen under the deck (or through the deck)

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
ALL OF THEM 

**Additional information:**
- Here you 've got some screens ilustrating this issue: 
1) after I have dropped previously taken fuel nozzle (taken from zeus) 
http://markooff.net/obrazki/PGM/bledy_army_ACE_itp/blad_ginaca_wylewka/Arma3_x64_2019-04-15_18-01-26-86.jpg
2) when I try to catch it anyway (using ACE_Interaction Menu - from the first person view)
http://markooff.net/obrazki/PGM/bledy_army_ACE_itp/blad_ginaca_wylewka/Arma3_x64_2019-04-15_18-01-39-63.jpg
3) I cannot bring it back using the ACE_Interaction_Menu on the object (fuel_bladder) 
http://markooff.net/obrazki/PGM/bledy_army_ACE_itp/blad_ginaca_wylewka/Arma3_x64_2019-04-15_18-01-49-36.jpg

The solution could be 
- a bit better positioning of the dropped down fuel nozzle
or
- adding an extra function to the fyel menu - for arbitrally bringing it back (when it is lost or hidden behind any object) 

I've tried to solve the problem using Zeus BIND VALUE + EXECUTE CODE Module and one of ACE3 function like 
[player, fuelTruck] call ace_refuel_fnc_returnNozzle
[player, cursorObject] call ace_refuel_fnc_takeNozzle
bot none of them can help at this time.

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/blob/master/addons/refuel/functions/fnc_dropNozzle.sqf#L36

Does LIS with carrier GEOM Lod report []?
In that case getTerrainHeightASL reports dept of sea floor.

**Comment by markooff** [comment]
Yes, but it happen also on shallowwater , so deep level isn't the clue I think .
Anyway I cannot find the hnadle for a fuel nozzleitself to change it height by any meaning

**Comment by markooff** [comment]
So maybe it is possibile to add an extra function to the fuel menu for bringing back the fuel nozzle ?

**Comment by commy2** [comment]
No, just fix drop nozzle.

**Comment by markooff** [comment]
OK, if You can do this :) 
But I think , it may be a bit buggy - because of for instance some problems with the harbour piers and some object like those.
