### ISSUE TITLE
Vector 21 documentation missing functionality (minor)

### ISSUE THREAD

**Issue by P-Hudson** [acemod/ACE3#6945]
Not reliant on version or mod info - sections removed.

A minor issue with the wiki documentation

**Description:**
- in the online documentation, directions to measure angle between two objects is missing, though that function exists in the list of Vector 21 capabilities at the top of the page in section 1.1

One might assume it is the opposite of the method to measure distance between two points, but that should show up in documentation.  Or, if the capability doesn't exist, remove it from list in section 1.1

**Where did the issue occur?**
https://ace3mod.com/wiki/feature/vector.html

Thank you!

**Comment by bux** [comment]
It should be: https://ace3mod.com/wiki/feature/vector.html#28-horizontal-distance-and-azimuth-between-two-points

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
