### ISSUE TITLE
ACE arsenal hiding ammo

### ISSUE THREAD

**Issue by Gunner117** [acemod/ACE3#6946]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- BAF
https://steamcommunity.com/sharedfiles/filedetails/?id=1572627279&searchtext=first+contact
- Operation: TREBUCHET First Contact 
https://steamcommunity.com/sharedfiles/filedetails/?id=1572627279&searchtext=first+contact
```

**Description:**
-  When using the ACE arsenal ammo for the 60mm M6 light mortar from the BAF mod and the ARC-920 Railgun from Operation: TREBUCHET First Contact are not shown. if a load out is saved with ammo for ether of these weapons and then loaded the ammo doesn't load with them.
I'm unsure if this is a ace issues but since it happens with items fro
m 2 different mods it seams the likely case

**Steps to reproduce:**
- try and grab ammo for the M60 or ARC-920 Railgun in the ace arsenal

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal -all of the above

**Additional information:**
-https://cdn.discordapp.com/attachments/493694295996366870/567849451490639872/20190416191030_1.jpg

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by PabstMirror** [comment]
I haven't looked at either mod in detail, but they might want to look into using the
`ace_arsenal_hide = -1;` config on the magazine to force it to show in the ace arsenal

**Comment by Drofseh** [comment]
They are probably vehicle magazines which are normally hidden in the arsenal IIRC.

**Comment by commy2** [comment]
Are these shown in the BI Arsenal?

**Comment by commy2** [comment]
Why do you need vehicle magazines in inventory when they cannot be used in any weapon?

**Comment by Gunner117** [comment]
Yes there in the BI Arsenal an no they are not vehicle weapons both are carried and used by infantry in the link posted in additional information I am carrying both

**Comment by Blutze** [comment]
>Why do you need vehicle magazines in inventory when they cannot be used in any weapon?

Its a 60mm light mortar. There are a number of IRL militaries with a gunner for these organic to companies or even platoons of light infantry, and everybody who has a kilogram or two to spare carries rounds for them in his backpack when paradropping or marching on foot.

81mms are debatable, but 60mms should definitely be available in the arsenal. Isn't this exactly the kind of case that `ace_arsenal_hide` was introduced for? Not to mention that with 3CB, all crew served weapons work off of the normal infantry inventory - MMGs, HMGs, GMGs, ATGMs, vehicle mounted or static.

Both of these mods are in active development, and at least 3CB actively encourages running ACE (this particular mortar's built-in range table only works with air resistance enabled). So I agree with Pabst: let the 3CB/OPTRE teams add the little property to those mags, or make a minor compat mod for your community.

https://gist.github.com/Blutze/5d98189eaa850afd8c66bb84e94bea6b

**Comment by Gunner117** [comment]
Thanks
