### ISSUE TITLE
Units crash a helo then go unconscious is still in awake animation after helo touching ground and ejected.

### ISSUE THREAD

**Issue by GoldJohnKing** [acemod/ACE3#6952]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.10.1` (stable)
**ACE3 Version:** `Version 3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- When helos with players are destroyed, players would be ejected out of the helo once the destroyed helo touch the ground. However, sometimes the ejected players are in unconscious status, while their animation (appearance) are not set into unconscious mode.
- I found this in RPT file:
`15:46:54 [ACE] (common) WARNING: Could not find unload pos btc_veh_19-ASL: [550.124,9930.22,6.78306] isTouchingGround: true Speed: -4.08746 z\ace\addons\common\functions\fnc_unloadPersonLocal.sqf:30`
- I've run several tests, this mostly happens especially helos are crashed at a very steep angle, or it touch a tree or collision with something when it touch the ground. Though it seems to happen in above situations, I still can't be sure about it, because it also happens on some "normal" circumstances, even happens several times when ground vehicles and boats destroyed.
- I've read possibly related issues, and only found this one kind of similar: https://github.com/acemod/ACE3/issues/691 .
- I'll provide screenshots in below "Additional Information" sector.

**Steps to reproduce:**
- Drive a helo.
- Having it crash at a very steep angle, better collision with a tree.
- Error occour, you'll find unit unconscious with awake animation.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / 

**Additional Information**
Before crash, please notice the steep angle and the tree it crash into.
![107410_20190419164934_1](https://user-images.githubusercontent.com/26923626/56420035-fda8e480-62ce-11e9-920a-9903e00b1ce1.png)

After crash, unit is unconscious but still remains awake animation.
![107410_20190419162716_1](https://user-images.githubusercontent.com/26923626/56420103-419be980-62cf-11e9-827f-fa203e094a4f.png)

Let's see it more clearly in Zeus interface (the unit's animation is overridden by Zeus animation now).
![107410_20190419162728_1](https://user-images.githubusercontent.com/26923626/56420140-5c6e5e00-62cf-11e9-824f-88c54f6d4d30.png)

**Comment by bux** [comment]
This also happens with land vehicles.

**Comment by PabstMirror** [comment]
Should be fixed by medical rewrite and changes to uncon animation system

**Comment by GoldJohnKing** [comment]
> Should be fixed by medical rewrite and changes to uncon animation system

Yes, tested for a long time and this should be fixed by medical rewrite. Close this issue as resolved.
