### ISSUE TITLE
Disposable launcher with spotting rifle lacks magazines.

### ISSUE THREAD

**Issue by Neciota** [acemod/ACE3#6954]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.10.1` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ACE3
- CUP Weapons
- CUP Units
- CUP Vehicles
- Custom LAW80
```

**Description:**
- When a disposable launcher with spotting rifle is added to a ammo crate in the editor, it may lack either the spotting round magazine or the normal rocket magazine when picked up in game. Presumably an issue with it being disposable. Similarly, you have to add both spotting rifle magazine and rocket magazine to the unit configuration magazine array or it will lack what you don't add, while on a regular disposable launcher you only have to add the weapon, not the magazine.

**Steps to reproduce:**
- Launch editor.
- Add a box with a disposable launcher with spotting rifle.
- Go in game.
- Take launcher.
- Lack spotting rifle magazine or rocket magazine.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer).

**Comment by commy2** [comment]
Disposable system is deprecated and will be replaced by https://github.com/CBATeam/CBA_A3/pull/1116

Closing.
