### ISSUE TITLE
No framework for dragging wounded or using bodybags

### ISSUE THREAD

**Issue by pognivet** [acemod/ACE3#6959]
**Arma 3 Version:** All
**CBA Version:** All
**ACE3 Version:** All

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Still no framework to have AI drag/carry wounded or to force players to do the same. No framework to force AI or players to place a dead body in a body bag and drag it.

**Steps to reproduce:**
- Play the game

**Where did the issue occur?**
- Everywhere

**Additional information:**
- Extremely frustrating

**RPT log file:**
Irrelevant

**Comment by thecogdoctor** [comment]
This is not really within the scope of ACE and it isn't an ACE issue either. This is a feature largely for a mod dedicated to AI improvement such as VCOM AI or ASR AI.

On another note I agree that being able to drag body-bags would be convenient, but as stated earlier: this is not really relevant to ACE in any way shape or form outside of being tangentially related to the ACE medical system.

**Comment by dedmen** [comment]
If this is a feature request then please put it into the feature request issue:
https://github.com/acemod/ACE3/issues/3594

>RPT log file: Irrelevant

RPT is never irrelevant,

>Where did the issue occur?
    Everywhere

Why is there AI in your main menu?

>Arma 3 Version: All

That's nonsense. ACE3 didn't exist back then.

>CBA Version: All

Nonsense. The current ACE version is not compatible with that.

>ACE3 Version: All

We only really take issue reports for the latest ACE version and not for older ones.

**Comment by BaerMitUmlaut** [comment]
AI units can't do dragging. I doubt they can even walk backwards, which would be a requirement in the first place.
