### ISSUE TITLE
AI won't rearm at crates

### ISSUE THREAD

**Issue by pognivet** [acemod/ACE3#6960]
**Arma 3 Version:** All
**CBA Version:** All
**ACE3 Version:** All

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- AI will never get more ammo from supply crates.
- AI vehicles will never rearm or refuel at such points.

**Steps to reproduce:**
- Play the game.

**Where did the issue occur?**
- All

**Additional information:**
- Extremely frustrating

**RPT log file:**
None required.

**Comment by thecogdoctor** [comment]
This is not really within the scope of ACE and it isn't an ACE issue either. This is a feature largely for a mod dedicated to AI improvement such as VCOM AI or ASR AI.

**Comment by dedmen** [comment]
If this is a feature request then please put it into the feature request issue:
#3594
