### ISSUE TITLE
ACE Interact Menu closes all type of dialogs

### ISSUE THREAD

**Issue by nflug** [acemod/ACE3#6967]
**Arma 3 Version:** newest
**CBA Version:** newest
**ACE3 Version:** newest

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Everytime you go into a dialog created with "createDialog" and press the interact key, to open the interaction menu, ace closes automaticly the opened dialog. How can I stop or disable this?

**Steps to reproduce:**
- Open dialog
- Press ace interact key
- Dialog gets closed by interaction menu

**Where did the issue occur?**
- Dedicated

**Comment by commy2** [comment]
What do you want instead? Have your display and the interaction menu or disable the interaction menu from appearing? What display do you use?

**Comment by nflug** [comment]
> 
> 
> What do you want instead? Have your display and the interaction menu or disable the interaction menu from appearing? What display do you use?

Disable the interaction menu from appearing & the behaviour that the apperring closes the dialog. But I dont know if there is any option for this or any type of script function.

**Comment by commy2** [comment]
And what display is this?

**Comment by nflug** [comment]
> 
> 
> And what display is this?
What do you mean with that?

It's just on custom created dialogs and dialogs from altislife. As example I created a shop where you can buy some items and for that I'm using createDialog.

**Comment by commy2** [comment]
```sqf
// init,sqf
["nflug_displayShown", {!isNull (uiNamespace getVariable ["nflug_myDisplay", displayNull])}] call ace_common_fnc_addCanInteractWithCondition;
```
Where `nflug_myDisplay` is your display stored in ui namespace.

**Comment by nflug** [comment]
Ok thanks you. Is something like ["nflug_displayShown", {!dialog}] call ace_common_fnc_addCanInteractWithCondition;

working too?

**Comment by commy2** [comment]
No that would break everything.
