### ISSUE TITLE
ACE Interaction/Self-interaction not working inside vehicles

### ISSUE THREAD

**Issue by Luxey012** [acemod/ACE3#6968]
**Arma 3 Version:** 1.90.145471 stable
**CBA Version:** 3.10.1 stable
**ACE3 Version:** 3.12.6 stable

**Mods:**

-Tested-
CBA_A3
ace

-Proper use-
@Black Retexture of Vurtual's HMMWVs [Key Fix] 
2035: Russian Armed Forces 
3CB BAF Equipment
3CB BAF Units 
3CB BAF Units (ACE compatibility) 
3CB BAF Units (RHS compatibility)
3CB BAF Vehicles
3CB BAF Vehicles (RHS reskins) 
3CB BAF Vehicles (Servicing extension) 
3CB BAF Weapons 
3CB BAF Weapons (RHS ammo compatibility) 
3CB Factions
3den Enhanced
ace 
ACE 3 Extension (Animations and Actions) 
ACE Compat - RHS Armed Forces of the Russian Federation 
ACE Compat - RHS United States Armed Forces 
ACE Compat - RHS: GREF 
ACEX
Achilles 
Advanced Sling Loading
Advanced Towing
Advanced Urban Rappelling 
BackpackOnChest 
Beketov 
Blastcore Edited (standalone version) 
Caucasus Insurgency 
CBA_A3 
CLA CLAFGHAN 
cTab 
CUP Terrains - Core 
CUP Terrains - CWA
CUP Terrains - Maps 
Enhanced Movement 
Enhanced Video Settings 
Fallujah V1.2 
FIREWILL Aviation Pack (Complete) 
G.O.S Gunkizli 
G.O.S N'ziwasogo 
G.O.S Song Bin Tanh 2.0 (APEX) 
GRAD Trenches 
Island Panthera 
Kidal 
MBG Buildings 3 (Arma2 Legacy) 
MBG Celle 2 (Arma2 Legacy)
MLO All-In-One Collection 
PMC Vehicles Mod 
Project OPFOR 
RHSAFRF 
RHSGREF 
RHSSAF 
RHSUSAF 
RKSL Studios: Attachments v3.00 
Rosche, Germany 
ShackTac User Interface 
SMA RHS compatibility Patch 
Specialist Military Arms (SMA) Version 2.7.1 
SU-35 Flanker E 
task_force_radio 
The CSAT Modification Project
Titus
Vcom AI V3.3.0 
Vurtual's Helicopters 
Vurtual's HMMWVs

**Description:**
- Can not use ACE interact/ACE self interact while inside vehicle (Boat, Ground vehicle, Helicopter, etc.)

**Steps to reproduce:**
- Load Arma3 with ACE/CBA3 (Either alone or with other mods)
- Load either into a server or editor
- Try and access self-interact/interact options outside a vehicle. It should work normally
- Get into a vehicle
- Try to access interact/self-interact option inside a vehicle. Interact wheels should appear, but not allow interaction *SEE LINKED VIDEO*

**Where did the issue occur?**
- Multiplayer server, Singleplayer editor

**Additional information:**
- This issue occurs regardless of installed mods
- Issue seems to be isolated. Others do not seem to experience this issue, and can not determine why it occurs
-Video of issue - https://drive.google.com/file/d/1I4pjXBc2TKSbP3lme4BhdN987-3VvwpC/view?usp=sharing

**RPT log file:**
https://drive.google.com/open?id=1h5KCJHkRkGWR8YdXHGSJoVzyTwwnj7-M

**Comment by thecogdoctor** [comment]
Is the RPT log of the full modpack you listed or just the CBA and ACE3 versions?

**Comment by Luxey012** [comment]
> Is the RPT log of the full modpack you listed or just the CBA and ACE3 versions?

Only of the test with Arma/CBA/ACE

**Comment by thecogdoctor** [comment]
> Try to access interact/self-interact option inside a vehicle. Interact wheels should appear, but not allow interaction _SEE LINKED VIDEO_

Looking at the video I'm not seeing anything wrong. Is there a specific interaction missing? If that's the issue then you didn't specify which interaction was missing and or why you believe it to be an issue etc.

Cheers.

**Comment by Luxey012** [comment]
> > Try to access interact/self-interact option inside a vehicle. Interact wheels should appear, but not allow interaction _SEE LINKED VIDEO_
> 
> Looking at the video I'm not seeing anything wrong. Is there a specific interaction missing? If that's the issue then you didn't specify which interaction was missing and or why you believe it to be an issue etc.
> 
> Cheers.

And that's the super odd thing, and the reason I think something's broken. Usually, as shown outside the vehicle, you just look at the option you want, let go of the interact key, and it 'selects' the option. Inside the vehicle, it doesn't do that. The menu just sits on my screen, with nothing interactable, clickable, etc. Only way I get rid of the menu is by hitting ESC

**Comment by commy2** [comment]
Go into ADDON OPTIONS, ACE Interaction Menu and untick "Doaction when releasing menu key".
From now on, use LMB to confirm an action.

**Comment by Luxey012** [comment]
> Go into ADDON OPTIONS, ACE Interaction Menu and untick "Doaction when releasing menu key".
> From now on, use LMB to confirm an action.

OMG, you're amazing! Instantly fixed my problem. Seriously, my entire group had no idea why I couldn't use interaction stuff in vehicles.

Thanks all! Issue can be closed now.

**Comment by commy2** [comment]
Well, I still don't know what went wrong for you, but this is a fine work around I guess.
Can you maybe post a screenshot of the second tab in the VIDEO options?

**Comment by Luxey012** [comment]
> Well, I still don't know what went wrong for you, but this is a fine work around I guess.
> Can you maybe post a screenshot of the second tab in the VIDEO options?

![Arma3_x64 2019-04-28 14-33-32-38](https://user-images.githubusercontent.com/29606050/56869171-b0a9ca00-69c2-11e9-9564-cc4d6aa5daf1.jpg)

There you go

**Comment by commy2** [comment]
Thanks, but I still don't know why releasing LMB doesn't work for you.

**Comment by Luxey012** [comment]
> Thanks, but I still don't know why releasing LMB doesn't work for you.

The LMB fix works for me. What wasn't working was releasing the interact/self-interact button I had bound, while inside a vehicle. But, it should have been working, considering under the same circumstances this fix works perfectly

**Comment by commy2** [comment]
Yeah, that was what I meant. Idk why that doesn't work.

**Comment by severgun** [comment]
Maybe some kind of cross binds on menu key?
