### ISSUE TITLE
DAGR micro GPS lag

### ISSUE THREAD

**Issue by highwave70** [acemod/ACE3#6969]
**Arma 3 Version:** `1.92` (stable / rc / dev)
**CBA Version:** `3.10.1` (stable / dev + commit hash)
**ACE3 Version:** `3.12.6` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace


**Description:**
- Since arma 1.92 update, DAGR GPS compass is laggy as hell

**Steps to reproduce:**
- Launch arma with only ACE and CBA latest version, and try it in Eden editor

**Where did the issue occur?**
- Dedicated 
- Self-Hosted Multiplayer 
- Editor (Singleplayer)
- Editor (Multiplayer)

**Additional information:**
- Reproduced on multiple players / computers

**RPT log file:**
- None

**Comment by derbismarck** [comment]
This is most likely to due the usage of CBA_fnc_headDir in the DAGR Micro GPS code, which is broken as of 1.92: https://github.com/CBATeam/CBA_A3/issues/1128

**Comment by PabstMirror** [comment]
Should be fixed with recent cba update: https://github.com/CBATeam/CBA_A3/releases/latest
