### ISSUE TITLE
Several questions about medicine and nametags

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#697]
I am totally noob in scripting. I found several parameters in stringtables:
***addons/medical/stringtable.xml

"STR_ACE_Medical_Head"
"STR_ACE_Medical_Torso"
"STR_ACE_Medical_LeftArm"
"STR_ACE_Medical_RightArm"
"STR_ACE_Medical_LeftLeg"
"STR_ACE_Medical_RightLeg"
and 
"STR_ACE_Medical_HeavilyWounded"
"STR_ACE_Medical_LightlyWounded"
"STR_ACE_Medical_VeryLightlyWounded"

Is it true that in medical system (window on the left, which shows damage) they are combined like that:
"STR_ACE_Medical_HeavilyWounded" + "STR_ACE_Medical_Head"
"STR_ACE_Medical_VeryLightlyWounded" + "STR_ACE_Medical_RightLeg"
and so on? Are they used separately somewhere else?  It is importatnt for translation purposes.

***addons/nametags/stringtable.xml
What does this parameter "Show SoundWaves (requires player names)" mean? Also important for translation purposes.

**Comment by commy2** [comment]
"Show SoundWaves"
When a player is talking via VON, ACRE2 or TFAR there is a squiggly line shown below the nametag if that is enabled.

No idea about medical.

**Comment by ruPaladin** [comment]
Thank you, commy2!

**Comment by ruPaladin** [comment]
Found the answer. 
"STR_ACE_Medical_Head"
"STR_ACE_Medical_Torso"
"STR_ACE_Medical_LeftArm"
"STR_ACE_Medical_RightArm"
"STR_ACE_Medical_LeftLeg"
"STR_ACE_Medical_RightLeg"
and
"STR_ACE_Medical_HeavilyWounded"
"STR_ACE_Medical_LightlyWounded"
"STR_ACE_Medical_VeryLightlyWounded"

Are used only together and only for patient status.
