### ISSUE TITLE
Handling of custom FirstAidKits and MedKits

### ISSUE THREAD

**Issue by AxeriusNetwork** [acemod/ACE3#6971]
**Arma 3 Version:** `1.92` (stable / rc / dev)
**CBA Version:** `3.10.1` (stable / dev + commit hash)
**ACE3 Version:** `3.12.6` (stable / dev + commit hash)

**Mods:**
```
- Global Mobilization
- CBA_A3
- ace
```

**Description:**
- GM has two new FAK's, gm_ge_army_burnBandage & gm_ge_army_gauzeBandage. These need to be changed into medical supplies

**Steps to reproduce:**
- Load GM, go into campaign or play as a unit with vanilla loadout.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
`while {({_x == "gm_ge_army_burnBandage"} count items _unit) > 0} do {
    _unit removeItem "gm_ge_army_burnBandage";
    if (GVAR(convertItems) == 0) then {
        if (GVAR(level) >= 2) then {
            _unit addItem "ACE_fieldDressing";
            _unit addItem "ACE_packingBandage";
            _unit addItem "ACE_morphine";
            _unit addItem "ACE_tourniquet";
        } else {
            _unit addItem "ACE_fieldDressing";
            _unit addItem "ACE_fieldDressing";
            _unit addItem "ACE_morphine";
        };
    };
};`
`while {({_x == "gm_ge_army_gauzeBandage"} count items _unit) > 0} do {
    _unit removeItem "gm_ge_army_gauzeBandage";
    if (GVAR(convertItems) == 0) then {
        if (GVAR(level) >= 2) then {
            _unit addItem "ACE_fieldDressing";
            _unit addItem "ACE_packingBandage";
            _unit addItem "ACE_morphine";
            _unit addItem "ACE_tourniquet";
        } else {
            _unit addItem "ACE_fieldDressing";
            _unit addItem "ACE_fieldDressing";
            _unit addItem "ACE_morphine";
        };
    };
};` https://github.com/acemod/ACE3/blob/v3.12.6/addons/medical/functions/fnc_itemCheck.sqf

**Comment by commy2** [comment]
Instead of hard coding more and more classnames into script, what actually should be done is parsing the config for all MedKit and FirstAidKit simulation type items and the replace those accordingly regardless of classnames.

**Comment by Drofseh** [comment]
There are several other mods that have medical items as well. Faces of War and CSA38 come to mind. I think IFA3 might as well.

**Comment by ElTyranos** [comment]
@Drofseh AFAIK we don't have custom medical stuff.

**Comment by Drofseh** [comment]
Must've all been from FoW/CSA then.

**Comment by jones140** [comment]
I believe unsung reskins vanilla items no class changes

**Comment by ImplicitDeny** [comment]
Custom medical items would be a good thing anyway. I'm thinking of some custom backpacks which are visually designed for medics. If they could be considered as proper healing items, that would be great.

We already have such a thing for wirecutters : it is possible for a modder to make a backpack considered by ACE as carrying a wirecutter, even if there is no such item in the backpack.

**Comment by Drofseh** [comment]
A problem I see with that ^ is that, unlike wire cutter, healing supplies get used up.

**Comment by ImplicitDeny** [comment]
Oh I forgot that detail. My team is never using the "consume item" feature. We tends to consider medkits and toolkits as virtually reusable material (either we can assume that we are in a safe place containing virtually unlimited healing ressources, or we consider that the object is containing enough material to handle a standard mission where we should not be hurt often).

Could this feature be handled in an other way ? For example with a new property like "ace_medical_usageLeft = -1", with any value bellow 0 meaning unlimited. Items cannot have properties but backpacks can.

**Comment by commy2** [comment]
Last 3 posts are off topic, belong in #3594

**Comment by PabstMirror** [comment]
notes from meeting, add new replace array
```
class ace_medical_replacement {
  class gdrVerband {
    replaceWith[] = {{"bandage", 4}};
};

**Comment by SilentSpike** [comment]
alternative:

```
class ace_medical_replacement {
  gdrVerband[] = {{"bandage", 4}};
};
```

**Comment by LinkIsGrim** [comment]
Item replacement for medical is now done by item type and not class. Close?
