### ISSUE TITLE
ace_winddeflection has unnecessary ace_weather dependency

### ISSUE THREAD

**Issue by derbismarck** [acemod/ACE3#6972]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.10.1` (stable)
**ACE3 Version:** 0e09879528e99a8fa7a0bc78329af773cec867c8 (current state of `master`)

**Mods:**
```
- CBA_A3
- ACE3
```

**Description:**
ACE WindDeflection has an unnecessary dependency on ACE Weather. ACE Weather isn't referenced whatsoever in ACE WindDeflection.

**Steps to reproduce:** N/A

**Where did the issue occur?** N/A

**Additional information:** N/A

**RPT log file:** N/A

**Comment by dedmen** [comment]
Code that depended on weather was removed in #5710
