### ISSUE TITLE
ace ammo cook off  in vehicles bug (floating rockets)

### ISSUE THREAD

**Issue by AirShark07** [acemod/ACE3#6978]
**Arma 3 Version:*latest* `1.92` (stable)
**CBA Version:** `3.11 latest` (stable)
**ACE3 Version:** `3.12.6 latest` (stable)
[https://imgur.com/oGcNLI0](url)

**Mods:**
- CBA_A3
- ace
- RHS mod pack

**Description:**
- sometimes it happens sometimes not...Random

**Steps to reproduce:**
- Destroy a tank that carry ATGM or rocket or something like that

**Where did the issue occur?**
-  Singleplayer

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by AirShark07** [comment]
image "https://imgur.com/ZCx6i2j"

**Comment by commy2** [comment]
What makes you think this is a bug in ACE and not simply a bug of the wreck model?

**Comment by AirShark07** [comment]
because it happens only when using ammo cook off i guess   ...also i noticed that it happens with missiles in the airplanes ...i will test the vanilla once if that is the case

**Comment by tbeswick96** [comment]
Have noticed this with tank shells as well. Occasionally during cook-off a tank shell tracer appears but freezes on the vehicle

**Comment by jones140** [comment]
Can confirm happens alot eventually the round will disappear like it's waiting to cook off that ammo

**Comment by AirShark07** [comment]
after more tests it seems that rockets are just an example and it happens with vanilla vehicles as well
