### ISSUE TITLE
ACE Advanced Medical for specific units only

### ISSUE THREAD

**Issue by ZaellixA** [acemod/ACE3#6985]
**Arma 3 Version:** `latest` (stable)
**CBA Version:** `3.11.1` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- I have implemented a script to create wounded units to act as medical practice mannequins. Due to the fact that we use advanced medical we would like to practice on advanced medical, but if I don't enable advanced medical for the AI, the mannequins don't take "advanced medical injuries" (no bleeding, stable vitals, etc.). The script will be running on a persistent mission so, if I turn advanced medical on for the AI, the rest of the units on the map (where we hope a lot of fighting will be happening) will not be able to heal themselves.
So, I am looking for a way to enable advanced medical to only my mannequins. Is there a way to do it, or maybe another workaround?

**Where did the issue occur?**
- Editor (Multiplayer)

**Comment by commy2** [comment]
No and there is no work around.

**Comment by ZaellixA** [comment]
Thanks for the quick reply.

It's good to know that. At least now I know that I should look for another way.

Thanks again,

Achilles.

P.S.: Please let me know if I should close the issue or you'll close it.

**Comment by TrainDoctor** [comment]
Since your question has been answered, it's fair to say it's good to close.

**Comment by PabstMirror** [comment]
This shouldn't be a problem after the medical rewrite (current ace development)
