### ISSUE TITLE
PBO Check should log addon mismatches to RPT

### ISSUE THREAD

**Issue by gozulio** [acemod/ACE3#6991]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.11.1` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Description:**
PBO Check framework reports addon mismatches into global chat, but it does not appear to log addon mismatches to RPT or any other form of server log when it really should.

If i want to use ACE PBO check to report mismatches in mods used between my dedicated server and the 40+ clients connected to it, I or another server admin has to connect ahead of time.Not to mention if the server shuts down or restarts you can't just check the logs for players with mismatched mods.

**Comment by dedmen** [comment]
https://github.com/acemod/ACE3/blob/0a4d3d5b653da4fc72073ca60de4a113a8af3c37/addons/common/scripts/checkVersionNumber.sqf#L134

It is already diag_log'ing to RPT.
