### ISSUE TITLE
Some samples of Official Mod Weapons (PS90) don't have automatic fire mode

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#6992]
**Arma 3 Version:** `1.92` (stable )
**CBA Version:** `3.10.1.190316` (stable )
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- In the ACE3 some samples of Oficial Mod Weapons (PS90) don't have automatic fire mode. 

> PS90 with short barrel supports automatic fire 
> PS90 with long barrel does not support automatic fire

If player disable ACE3, then everything becomes normal.
It looks weird. The same weapon, which differs only in the long barrel can not use both modes of fire.  

In general, PDW (with 50 bullets in magazine) without automatic fire is nonsense!

**Comment by commy2** [comment]
Needs RPT file.

https://github.com/acemod/ACE3/pull/6667#issuecomment-437455070
https://github.com/acemod/ACE3/pull/6667#issuecomment-437468257

Close?

**Comment by jonpas** [comment]
> Since 2005, a semi-automatic version has been offered to civilian users as the PS90.

P**S**90 - it's literally in the name.

However, why does the short barrel have auto-fire (unless you mean P90 without S)? 

> Yeah, TR is the civilian version with long barrel, semi-only.

TR does not mean semi-auto or not, but it means "triple rail", which P90 TR features.

**Comment by dedmen** [comment]
So the real bug here is the short barrel variant supporting automatic fire.
I'm all for fixing it and making it semi only.

**Comment by jonpas** [comment]
Re-reading my magwell comment, it might be wrong naming, never really checked out all variants in the game (there is only one proper P90!).

**Comment by commy2** [comment]
I'll assign you, @jonpas then :P 

Or you tell me what to do, because idk what would be right.

**Comment by Blutze** [comment]
Don't see anything wrong ingame.

- All "P-Semi-90s" have 10% higher `initSpeed`, `modes[] = {"Single"};`, the longbarreled model and `mass = 50`.
- All weapons without the "Semi" part in the name have normal `initSpeed`, `modes[] = {"Single","FullAuto"};`, the shortbarreled model and `mass = 40`.
- Railed variants still obey those rules.

> In general, PDW (with 50 bullets in magazine) without automatic fire is nonsense!

And yet, there seem to be enough US civilians interested in it for FN to offer such a configuration. I've even heard of security organizations in Europe issuing semiauto MP7s... Not a tactically sound decision, but people make it.

Oooooooh, now I see what is happening here. @jonpas: That line about "PS90 with short barrel" in the original ticket must be a typo.

**Comment by jonpas** [comment]
Thanks Blutze, there is no issue then. Close?

**Comment by ZeusWrath** [comment]
Someone tell me which ACE3 file I have to delete in order to return its vanilla properties (all have PS90 automatic fire) ?

**Comment by commy2** [comment]
ace_ballistics.pbo

**Comment by ZeusWrath** [comment]
@commy2  Thank you for you answer!
