### ISSUE TITLE
make turret blow off compatible with an animationSource

### ISSUE THREAD

**Issue by ElTyranos** [acemod/ACE3#6993]
**Description:**
https://github.com/acemod/ACE3/blob/master/addons/cookoff/functions/fnc_blowOffTurret.sqf

Currently, it will only work with  `destrType = "DestructWreck";`
This requires an useless turretless hull model to be made.

It would be cool to have it work with an hide animationSource too when `destrType = "DestructDefault";` is active. This way, one can assign turret and gun to a namedSelection, hide it, and let the turret model spawn in the air. This would have the big advantage to be hiddenselection friendly by keeping the hull customisations (texture, amovible parts, etc.)

**Comment by commy2** [comment]
Can you give me an example of how this would work?

As far as I can tell you can do this already by adding a the addTurretToEditable event to the server machine that checks the vehicle classname and does the hiding.

```sqf
if (isServer) then {
    ["ace_cookoff_addTurretToEditable", {
        params ["_vehicle", "_turret"];

        if (_vehicle isKindOf "My_AwesomeCar") then {
            // hide _vehicle something
        };
    }] call CBA_fnc_addClassEventHandler;
};
```

The event has a weird name, but that could be changed if you want to go this route.

**Comment by ElTyranos** [comment]
@commy2: there would be a simple check to add to the script itself (to avoid external manipulation). IF ACE_HideTurret exist in the vehicle's cfg AnimationSources THEN the script would trigger it (animationState=1) before spawning the turret as it is now. ELSE it would work as it is now.

**Comment by commy2** [comment]
What do you mean by "external manipulation"? Do you want to avoid putting a script in your mod?

**Comment by ElTyranos** [comment]
Ok we included it internally https://github.com/bux/IFA3_ACE_COMPAT/pull/46

(sorry but I don't talk SQF so I don't have much insights :D

**Comment by commy2** [comment]
That was what I was thinking of. I think however that I want to make an official/public event for this with a better name. I'll recycle this ticket as a reminder.
