### ISSUE TITLE
Some visual glitches with progress bar

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#700]
ACE3 Version: custom 17.04.2015

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
No

Description:
1.Here you may see that text is a little bit higher (or misaligned) than progress bar:
http://i.imgur.com/AUbfNwX.png
2. Don't know is it a glitch.
Here is original image:
http://i.imgur.com/hcIoNu9.png
Here is edited with GIMP:
http://i.imgur.com/mnM8yWM.png
You may see several  misalignedrectangular forms (green bar, yellow and red). Don't know is it a glitch or not.

Steps to reproduce:
Just make something to progress bar appear.

Where did the issue occur?
Every time when you see progress bar

RPT log file:
No

**Comment by PabstMirror** [comment]
Text should be properly centered now.

**Comment by ruPaladin** [comment]
New progress bar is great!
