### ISSUE TITLE
NVG Blur when Aiming without scopes 

### ISSUE THREAD

**Issue by AirShark07** [acemod/ACE3#7000]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- RHS

**Description:**
- I think there is a feature where when aiming with scopes things will get Blury to simulate Real life NVGs but the problem its happening even with iron sights and scopeless weapons maybe adding a script to check if current weapon is scoped to add the Blur effect is better.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by commy2** [comment]
>maybe adding a script to check if current weapon is scoped
Can you provide such a script?

**Comment by commy2** [comment]
Related: #6942 #6977

**Comment by bux** [comment]
There's no difference if you look through scopes or use iron sights.

The focal length of NVGs is pretty much fixed to a certain distance to get a sharp image and usually it's not the 10-20 cm in front of your head that is important to a wearer.

_IRL you can adjust the focal length but it's a tediuos process and I'm assuming that's not something one would do often during an operation_

**Comment by PabstMirror** [comment]
I am curious if anyone knows about how Holographic or Red Dot scopes work with NVG
I believe they use laser/coherent light, which I think has some special effects
e.g. you don't have to focus on the dot, it's virtually focused at infinity?
so I'm not positive if it would be blurred with nvg?
I could be totally wrong on this

**Comment by jonpas** [comment]
@PabstMirror that is correct, red dots/holos should work to a lot better extent than they currently do with the setting enabled.

https://youtu.be/DqaEDqXp0VU?t=108

**Comment by severgun** [comment]
There is no difference iron sight, collimator or zoom. All of them are close to face so when NVG focused to infinity you will not be able to focus on close objects.

It is not a bug

**Comment by Drofseh** [comment]
Pabst is correct, reflex/holographic/red dot sights can be used with NVGs.
Many include brightness modes specifically for use with night vision.
https://www.youtube.com/watch?v=DqaEDqXp0VU&t=87s

The other thing you can do with NVGs is use a single tube for night vision on one eye while looking through the sight with your non-amplified eye. This superimposes the dot in the your amplified vision.
This gives a sight picture similar to this.
https://i.gyazo.com/f8164721d04686866e353001b8a95aee.png

Severgun is also correct, NVGs do not work well with irons, collimators, or magnified optics, but red dots don't use the same tech as those types of sights.

**Comment by severgun** [comment]
> but red dots don't use the same tech as those types of sights.
red dot = collimator
You can use it, but in my opinion, dot itself will be blured, because it is reflection on close located surface

**Comment by bux** [comment]
One would usually use an IR laser for such scenarios. (hoping that the enemy doesn't have NVGs themselves)

**Comment by brainslush** [comment]
> 
> 
> One would usually use an IR laser for such scenarios. (hoping that the enemy doesn't have NVGs themselves)
That's why you have to train laser management. Only turn on when needed, to shoot. Point the weapon prior to switching the leaser on slightly below the target, switch the laser on and guide the weapon  to the head/torso. After firing disable the laser unless you expect a continuous fire fight.

Regarding the topic, head mounted nvgs can be used with some optics as was discussed prior but the real challenge is to line up both your nvg and scope to be able to shoot. With a an pvs 14 mounted on the rail in front or behind the scope this is much easier.

**Comment by AirShark07** [comment]
https://www.youtube.com/watch?v=hlGmEMQR68Y

**Comment by AirShark07** [comment]
engine Limitation
