### ISSUE TITLE
Client hangs in loading screen when connecting to Linux dedicated server

### ISSUE THREAD

**Issue by krieghof** [acemod/ACE3#7006]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** ` 3.11.2.190515` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- I created an server on linux with "./arma3server -mod="@CBA_A3;@ace". On an windows machine on the same network i started Arma3 with the two mods loaded and tried to join the server but i get stuck in the loading screen forever.
I could not find any error in the .rpt logs.
Maybe I'm just doing something wrong hope you guys can help me.

**Steps to reproduce:**
- start a linux server with "./arma3server -mod="@CBA_A3;@ace"
- try to join with a client

**Where did the issue occur?**
- Dedicated Linux

**Additional information:**
- I tried different load orders and I tried to join the server with a running mission (Antistasi)

**RPT log file:**
Client: https://gist.github.com/krieghof/b513f937f9ad3935bce31c6d7ed92b58
Server : https://gist.github.com/krieghof/3cd6e53ae4f92c6752cfea5a6c85d6d8

**Comment by dedmen** [comment]
Fix: Disable battleye on server.
Battleyes fault.

**Comment by krieghof** [comment]
It works thanks for helping me out :)
