### ISSUE TITLE
Request: Fix Atropine

### ISSUE THREAD

**Issue by Bicardi** [acemod/ACE3#7007]
Atropine in its current form is not used in any fashion to fix Tachycardia. It is used to treat CBRN/NBC contamination and Bradycardia. If it were to do something like provide a temporary quick boost to the PT's Heart Rate to more quickly counter the effects of Morphine OD's I think it would be more useful

Thanks,
A Combat Medic

**Comment by Drofseh** [comment]
duplicate of #5293 ?
