### ISSUE TITLE
Mk41 VSL does not filter on laser codes

### ISSUE THREAD

**Issue by mwpowellhtx** [acemod/ACE3#7008]
The [Mk41 VSL](https://en.wikipedia.org/wiki/Mark_41_Vertical_Launching_System) locks on to any available laser targeting. No ability to filter on the laser handshake, i.e. ``Ctrl+Alt+Q/E`` to *adjust up/down*. In my opinion, it should be handshaking just like any other ACE enabled laser/weapon system handshake.

**Comment by BaerMitUmlaut** [comment]
#3594
