### ISSUE TITLE
Move to a lay down conscious before go uncosncious, with adequate settings (pain, bleeding, wound entities)

### ISSUE THREAD

**Issue by Maseddu** [acemod/ACE3#7009]
I do not know if i can request something and where i have to put the request, i'll try to put my request here.

I was wondering if it's possible to have one more state of knockdown (when someone gets hit and go unconscious) before the classic uncoscious state, when someone get a lot of medium wounds, go in a not unconscious state where the patient lay down stationary, but can still talk with others (TFAR)
and if it get a more heavy wound or continue to bleed go unconscious, tweaking this using the quantity felt of pain too.
I think it is a big work, but i thougt that will add a lot mor eimmersion than just pass directly to unconscious.
Thanks for the great job you all guy did till now!

**Comment by BaerMitUmlaut** [comment]
#3594
