### ISSUE TITLE
Could You remove the yellow light from vehicles dropped by paradrop ? (cargo module)

### ISSUE THREAD

**Issue by markooff** [acemod/ACE3#7011]
[init.zip](https://github.com/acemod/ACE3/files/3198261/init.zip)

**Arma 3 Version:** `1.90` (stable / rc / dev)
**CBA Version:** `3.11.2` (stable )
**ACE3 Version:** `3.12.6.43.` (stable )

**Mods:**
```
- CBA_A3
- ace
- tfar
- RHS (USAF, ARFR , GREF) 
- CUP Core
- CUP Maps
```

**Description:**
- THIS is not an error, but the small modification request.
Problem is located in  ACE3/addons/cargo/functions/fnc_paradropItem.sqf 
lines 72-73 
`private _light = "Chemlight_yellow" createVehicle [0,0,0];
_light attachTo [_item, [0,0,0]]; `

The problem occurs when you paradrop obcject OTHER than supply crates (or similiar objects) - just as example - when you paradrop vehicles like quads, or similiar  from C-130 or CH-47 or CH-53. Everything works OK (the paradrop funtion works good) but after all there is the nasty yellow light attachet to the every dropped vehicle and it does not dissapear - even after some seconds or minutes ! As an addition - you (AS A PLAYER) have absolutelly no possibillities to swith it off ....
Let's imagine - that you can drop 3 quads for support your troops in deep forrest near the AO. There is a dark beautifull night. And when your troops reach the dropped vehicles they cannot use them securely, because of bright yellow lights which are attached to them. And they light and light with no ending..
Could you make some changes in this setting ? (wI write the proposition below) 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
1. USE MOD LIST like above 
2. make a simple mission MP in EDEN 
3. add the init.sqf which cover all the changes in the cargo/logistic values of somevehicles classes . [I put it as an attachment] 
4. Run the mission - with nighttime as a starting time (time of day) 
Take (Spawn) a C-130 and get a few QUADs into his cargo 
5. Take off
6. Put C-130 into a level flight (on height of 100-250 m.) 
7. Using Cargo/Paradrop menu drop all those quads 
8. Land your C-130 and go at the place where paradropped vehicles have touched the ground. Then you can see that they all have a nasty yellow lights , which are completely unreallistic with night-missions and may even cause death of your troops (while using the enlighted quads ) 

**Where did the issue occur?**
- ALL (SP/MP/Ded) with properly configured **PGM Logistic System for transporting vehicles** (in mission init - not in separate mod at this time in case of doing tests) 

**Additional information:**
- I suggest not to get rid of this functionallity at all (i.e. yellow lights attached to the dropped vehicles) but at least remove them from all Vehicle classes (i.e. cars,quads, trucks and so on) or boat calsses .... Or leave the decision (if the dropped object SHOULD light OR NOT ) in the ACE3 mod addon config entry. In that case everybody who make modifications like me (and prepare own logistics a bit more sophisticated than what we get with ACE3 :) ) have an opportunity for decide - IF HE WANTs to have objects lighting like a small stars ...or not. 

**RPT log file:**
- There is NO rpt file cause it is not an error issue.

**Comment by markooff** [comment]
[init.zip](https://github.com/acemod/ACE3/files/3198263/init.zip)
my examplenary init.sqf - which covers all PGM Logistics for transporting vehicels and paradropping them

**Comment by Drofseh** [comment]
#3594

**Comment by markooff** [comment]
OK, thx , but I wasn't sure where exactly put this issue - because it is rathe small modification of EXISTING code that ADING a PRETTY NEW ONE .

so if You still think that the will be better to put it there ...

**Comment by commy2** [comment]
"Feature request" doesn't imply a new feature being added. Could also be a feature being expanded.

**Comment by RSpeekenbrink** [comment]
Is it not possible to attach the effects in such a way that the player is able to detach them from a vehicle like when attaching a chemlight and then detaching it via the ace interaction menu? It would be petty to completely remove the effects. (Or maybe add a mission var for removing effects)
