### ISSUE TITLE
AT-Counter Measures not effective (in vanilla game it looks more effective)

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#7012]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.10.1.190316` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
- JSRS sound mod
```

**Description:**

At first I thought it was a problem in the vanilla game. However, when I turned off ACE3, I saw that it worked more effective in a vanilla game. 

**When I try to protect my vehicle from Guided AT-Missiles, I launch a smoke screen, however this does not help me. Always and always the missile will find my tank or APC and I will be destroyed.** 

I tried to run a smoke screen and change the position of my vehicle. In this case, the AT-missiles should lose the target and continue fly to the place where my vehicle was originally, but the always and always AT-missile still finds my vehicle, even if I shifted the location! I tried dozens of times, but it seems to me that the effectiveness of such counter measures is zero. Please make counter measures effective.

**Steps to reproduce:**
 Try defend your vehicle (Merkava Tank or Badger APC) from Guided AT-Misseles:

_a) Missile Specialist (man) - Titan Launcher
b) APC AT-Missile (OPFOR APC - BM 2T Stalker) AT-Missile (Mini-Spike)
c) Independent Jet (JAS 39 Gripen) AT-Missile (Maverick)
d) OPFOR Helicopter Mi-48 Kaiman AT-Missile (9k 121 Vikhr)_

repeat test without ACE3

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by commy2** [comment]
I don't think there is any difference between vanilla and ACE here. Seems to be placebo.

**Comment by ZeusWrath** [comment]
> I don't think there is any difference between vanilla and ACE here. Seems to be placebo.

That is, ACE3 did not work on countermeasures in general? 
I know that ACE have your own AT-Missile system, really there is no any impact?

**Comment by commy2** [comment]
>That is, ACE3 did not work on countermeasures in general?

ACE doesn't change anything about counter measures.

>I know that ACE have your own AT-Missile system, really there is no any impact?

`missileguidance` component does not change the base game missiles, it adds new ones.

**Comment by ZeusWrath** [comment]
I am surprised. So it really is a placebo?I do not know what to think...
If ACE3 didn’t change anything, then does the fact that it works in vanilla suit you?

Just now, my tank was hit after I released two smoke and after this changed the initial position. 
The missile was supposed to get into the original place, where my tank was originally from, but the missile still found my tank, even in double smoke and even after change initial position! This is normal for counter measures?

**Comment by ZeusWrath** [comment]
If such not effectiveness, this is the norm for a vanilla game, then please try to work on it! Arma3 needs an effective counter measures, while we have no active protection systems at all
