### ISSUE TITLE
file types are .cpp and .sqf when they should be PBO and BISIGN types right?

### ISSUE THREAD

**Issue by SRosales0520** [acemod/ACE3#7018]
**Arma 3 Version:** `N/A` (have played and is stable)
**CBA Version:** `v3.11.2.190515` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- I don't know if this is a dumb question with an obvious answer but my error is not actually in the complete mod but before the mod can actually happen. when I extract the .zip file, all the files in the folder are either .cpp, .sqf, etc. but what my arma needs is it to be PBO or BISIGN. I have tried redownloading it and re-extracting it and everything but I don't understand how everyone else is PBO and BISIGN whereas mine are the .cpp and .sqfI have also scoured the internet before coming here because I know this is quite an informal issue post but this is kind of my last hope

**Steps to reproduce:**
- I'm just downloading ace and cba like the instructions say and not doing anything different but it still says the files are .cpp and .sqf

**Where did the issue occur?**
- this issue occurs when I try to import the mod via the local mod import function in the arma launcher. it says that it cannot read the mod file because there are no PBO and other such files to actual run/compile the mod in arma

**Additional information:**
- Now this may be the problem but I doubt it because it seems like my file types are always different from youtube tutorials but I am using a "non-steam" version of arma 3 which I got from somewhere else but is the full-fledged game because I've been playing it for a day and a half already. unless arma started using .cpp files and .sqf files for mods, I don't think this should affect my situation too heavily. this is also the reason why I put N/A for the arma version because i am not entirely sure.

again, I apologize if this is very unstructured and possibly frowned upon because of the non-steam game but I seriously just want to play your mod, especially the sniping tools(atragmx, kestrel), and experience that kind of fighting/mathematical skill fighting:)

**Comment by PabstMirror** [comment]
goto https://github.com/acemod/ACE3/releases
scroll down a bit and download the file `ace3_3.12.6.zip      112 MB`
that will have the pbos the game wants, 
the other zips like the button on the main github are source code for developers

**Comment by SRosales0520** [comment]
ahhhh that would be it! I will try that asap! sorry for the long issue for such a short solution but I really appreciate the lightning fast response either way:)
