### ISSUE TITLE
ACE 3 medical death problem

### ISSUE THREAD

**Issue by GhostFrenchy** [acemod/ACE3#7019]
Arma 3 Version: 1.92 (stable)
 
**Mods [Everythings is update] :**
- CBA_A3 Version: 3.11.2 (stable)
- ACE3 Version: 3.12.6 (stable)
- ACEX 
- CBA A3
- all the RHS
- all the 3CB (include 3CB Factions)
- FFAA mod
- Task force radio
- R3F
- ADV - Ace medical
- ACE 3 Animation

**Description:**
- The problem is that when I play on a private server hosted by a friend, we can not die, we automatically fall unconscious and we can not die even if we take 200 bullets in the head.  We configured ACE 3 medical in advanced and we did not check "prevent instant death".

**Steps to reproduce :**
1 - host a server yourself and invite friends.
2 - configure ACE medical in advance (do not check "prevent instant death").  
3 - Try to kill someone (a player) without falling unconscious.

**Where did the issue occur?**
- Self-Hosted Multiplayer / Eden Editor (Singleplayer)

**Comment by TheMagnetar** [comment]
1) Did you check revive?
2) if not 1 then reproduce de issue with only ace and cba

**Comment by TheMagnetar** [comment]
1) Did you check revive?
2) if not 1 then reproduce de issue with only ace and cba

**Comment by alganthe** [comment]
You have revive enabled, it will put you in cardiac arrest and will let you take an infinite amount of damage until the revive timer runs out.

I think you want prevent instant death which would let you take only one bullet that would've otherwise killed you.
