### ISSUE TITLE
Dlls blocked by battleye

### ISSUE THREAD

**Issue by Vabramov15** [acemod/ACE3#7020]
Hello,

    I'm having a problem ace wich is blocked by battl
[ArmaReport_Log_20190527T125557_colin.zip](https://github.com/acemod/ACE3/files/3223945/ArmaReport_Log_20190527T125557_colin.zip)
eye

What I do

I run my game from the launcher via steam, the mods of the Altislife server I want to play are activated. When I connect, I have a message [ACE ERROR] (see screen) and I'm kick.
What I want

    Log in

What I get

    See screens: https://imgur.com/a/om7lehw 7

Server version: v3.1.4.8? v5? v4.4r3?
Operating system: Windows

What I try:

Checking Arma 3 Files
Update windows
CCleaner
Resettlement of Arma
Opening of steam ports (27015 to 27030)
Removing problematic ACE files and repairing via the Arma launcher
Delete the Battleye folder and check the Arma 3 files

Here are the logs of Arma 3 Launcher: https://pastebin.com/dVk1TTWs 3

and Arma 3: https://pastebin.com/nMEUVGGa

I downloaded with the mod workshop of the server I want to play: https://steamcommunity.com/sharedfiles/filedetails/?id=1570074499

Then I tried with a GitHub version: https://github.com/acemod/ACE3

I also tried taking the files of someone who manages to play.

Thank you in advance and sorry for bad english.

**Comment by dedmen** [comment]
What happened to the issue template.
Can you please fill out the issue template?


It's probably just battleye randomly blocking things. It does that once or twice per month. Not our fault.

**Comment by Vabramov15** [comment]
**Arma 3 Version:** 
Launcher version: 1.5.145631

Game version: 1.92.145639

Branch: main / beta branch not specified
` (stable)
**ACE3 Version:** `3.12.6, dowloaded from https://github.com/acemod/ACE3 (stable)

**Mods:**
```
- ace
```

**Description:**
- https://imgur.com/a/om7lehw 7

**Steps to reproduce:**
- Launch arma 3 from Arma 3 Launcher
**Where did the issue occur?**
- Dedicated / Singleplayer / Editor (Singleplayer) 

**Additional information:**
- What I tried:

Checking Arma 3 Files
Update windows
CCleaner
Resettlement of Arma
Opening of steam ports (27015 to 27030)
Removing problematic ACE files and repairing via the Arma launcher
Delete the Battleye folder and check the Arma 3 files

**RPT log file:**
- Here are the logs of Arma 3 Launcher: https://pastebin.com/dVk1TTWs 3

and Arma 3: https://pastebin.com/nMEUVGGa



I have this problem since 3 days, i have done every update i could but still not working

Thanks

**Comment by barman75** [comment]
I unable to run some missions with ACE on linux server with Battleye ON since Arma 1.92 i guess.
I could not find out a pattern or solution. Not a BI ports issue in my case.

**Comment by alganthe** [comment]
The DLLs haven't been recompiled since 2 years ago, 3 for some of them, if there is any issue it's unfortunately on Battleye's side or BI.

**Comment by dedmen** [comment]
@barman75 battleye on linux with mods is bugged on the battleye side. Server just freezes at startup and doesn't let anyone connect. That has nothing to do with ACE.

**Comment by barman75** [comment]
@dedmen Yes, it looks so, because such issue is not only with ACE, but CUP, RHS, CBA, etc

**Comment by Vabramov15** [comment]
Its probably because of BE but, i don't understand why hundreds of people can connect with the same mods but not me ? Its BE react false positive, why it does'nt do it with others people playing on the server.

**Comment by barman75** [comment]
That because BE possibly reacts on some suspicious activity in your RAM, such as resident program, a service, a keyboard macro software, or a viral activity. Check your game Arma files first. Try to reinstall Battleye. Check your PC for viruses. Try to turn off unnecesary programs and services. Try to connect to any other server which uses ACE mod. Let's see what happened.

**Comment by Vabramov15** [comment]
I tried a clean reinstallation of Arma 3 but still not working. I even reinstalled windows while cleaning my harddrive. Battleye block the DLL when starting the game, not when connecting to a server so it didn't changed anything. 

To reinstall battleye : I went to Arma 3 --> Battleye and ran "Uninstall Battleye" and then used "Reinstall Battleye". Any other ways to do it ?

**Comment by hmarcbower** [comment]
Not sure it's a Battleye issue:

Call extension 'ace_break_line' could not be loaded: Ressources syst鮥 insuffisantes pour terminer le service demand鮍

14:55:05 [ACE] (common) ERROR: Extension ace_break_line_x64.dll not found. z\ace\addons\common\functions\fnc_checkFiles.sqf:93

**Comment by Vabramov15** [comment]
It is : If an extension is not whitelisted with BattlEye (see Extensions for more info) it will be blocked on clients running with enabled BattlEye protection. RPT message outputted however is a little obscure:
21:35:04 Call extension 'MyExtension' could not be loaded: Insufficient system resources exist to complete the requested service (https://community.bistudio.com/wiki/callExtension)

However, i don't understand the second error  ace_break_line_x64.dll not found. z\ace\addons\common\functions\fnc_checkFiles.sqf:93. I don't know where is z\ace files on my computer or what is it

**Comment by dedmen** [comment]
>Not sure it's a Battleye issue:

It's a battleye issue.

**Comment by Vabramov15** [comment]
So their are no ways i can fix it by myself ?

**Comment by hmarcbower** [comment]
Then that's a stupid error message. :) like something Microsoft would
write.

**Comment by dedmen** [comment]
>like something Microsoft would
write.
…

It's from microsoft.

**Comment by hmarcbower** [comment]
Perfect. :)
