### ISSUE TITLE
AtragMx Muz Vel Table

### ISSUE THREAD

**Issue by JPBraz92** [acemod/ACE3#7027]
When opening AtragMx, both the muzzle velocity table and the drag coefficient table, when selected it just doesn't do anything. Stays on the first page.

I do have the range table with me.

Help.

**Comment by Blutze** [comment]
Simulation of those phenomena is only happening with ACE Advanced Ballistics enabled. The AtragMX and rangecard are available and useful in both basic and advanced, but you need to keep the profiles separate. In fact, the default profiles already have the muzzle velocity table filled out and can be misleading with basic ballistics.

If these menus are not opening _with_ advanced ballistics, fill out the issue template (versions, other mods, rpt etc).
