### ISSUE TITLE
ACE3 View Distance Limiter - Dynamic Object View Distance Reset

### ISSUE THREAD

**Issue by Quailsnap** [acemod/ACE3#7031]
**Arma 3 Version:** `1.92` (stable - steam)
**CBA Version:** `3.11.2` (stable - workshop)
**ACE3 Version:** `3.12.6` (stable - workshop)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- ACE View Distance Limiter's Dynamic Object View Distance does not remember the 'Minimum' object view distance set after a mission restart.
- My current use-case for the Dynamic Object View Distance limiter is detailed below, under 'Steps to Reproduce', and I am concerned my use-case may not be something the devs had in mind.

**Steps to reproduce:**
1. Enter a singleplayer game in the editor. Any map, any unit. Under CBA Settings, turn ACE View Distance Limiter settings to default. Press okay to confirm.
2. Open the CBA Settings again and turn ACE View Distance Limiter Client View Distance (foot, land vehicle, air vehicle) each to 10000. Ensure the server is not capping you any lower.
3. Turn the Dynamic Object View Distance to "Very Low", which corresponds to 20% of the total, which will give you a static Object View Distance of 2000m. Press okay.
4. Press Escape. Ensure your dialog console is accessible, and enter "getObjectViewDistance" in one of the watch fields. The first number in the array, your Object View Distance, should be 2000.
5. Go back to CBA Settings and turn Dynamic Object View Distance to "FoV Based." This will take your current Object View Distance and make it the minimum, and it will scale it up depending on how far you zoom in.
6. Enjoy a cool mission with a very dynamically scaling viewdistance and a beautiful vista-worthy maximum render distance. You can, again, check the listener (with ESC) as you go to see how much your Object View Distance is scaled to at any moment.
7. Exit back to the editor and restart the mission. Do not touch any settings, simply restart.
8. Your Object View Distance is now a different value. I got 4769.88 as my default. My settings remain unchanged.

**Where did the issue occur?**
- Dedicated Servers, A Same-Machine Dedicated Server, Self-Hosted Multiplayer, and Singleplayer, repeatedly for about eight months now.

**Additional information:**
- I have no idea why I didn't report this sooner. It's the bane of my existence and the reason I open the CBA settings menu before the end of briefing for every single op I've played for almost a year.

**RPT log file:**
- (Not relevant).

**Comment by Quailsnap** [comment]
a tl;dr -- Clients cannot use Dynamic Object View Distance without having to manually set it up every time they load into a mission.

**Comment by jonpas** [comment]
I can confirm that is a bug.

**Comment by Quailsnap** [comment]
Any milestone target / plan to fix?

Problem **(may)** be in here: https://github.com/acemod/ACE3/blob/master/addons/viewdistance/functions/fnc_changeViewDistance.sqf
... or a result of an issue with CBA settings somewhere.

**Comment by jonpas** [comment]
I don't have time to work on this right now.

**Comment by Lorenz94B** [comment]
Hello, is this issue still unresolved? Thanks!

**Comment by Quailsnap** [comment]
It is.

**Comment by Lorenz94B** [comment]
Please let me know if I'm wrong:
would a displayLoad EH hooked to the debriefing display (or an unload kind hooked to the main display) do the job of triggering an event to reset the objectViewDistance to the initial value (saved into a variable at mission start)?

Anyway, what happens if the game is closed? Are settings kept as set from the user or not?

Thank you!

**Comment by Quailsnap** [comment]
As far as I know (re: game closing) every mission load I need to follow the "steps to reproduce" in order to get my intended Dynamic FoV View Distance behavior back.

**Comment by Lorenz94B** [comment]
please, can this be added in the 3.13.5 milestone?

**Comment by AWanderingMage** [comment]
Just realized today I am also having this bug, where changing vehicles or points of view, or joining any new game will reset the view distance to default regardless of what the settings were previously.

**Comment by Mike-MF** [comment]
Should be fixed by #9140

**Comment by Quailsnap** [comment]
Does not appear to be fixed in `3.16.0`.
