### ISSUE TITLE
improve Armed vehicles crew (feature request)

### ISSUE THREAD

**Issue by AirShark07** [acemod/ACE3#7032]
**Arma 3 Version:** `Latest` (stable / rc / dev)
**CBA Version:** `Latest` (stable / dev + commit hash)
**ACE3 Version:** `Latest` (stable / dev + commit hash)

**Mods:**
```RHS
- CBA_A3
- ace
```

**Description:**
-I don't know if you guys are in depth with Ai's but I wonder if you can improve Ai Armed vehicles crew, like Tank crew by obliging them to stay on their armed vehicles if any enemies nearby when the vehicle is damaged... sometimes for small scratch like damaged tracks will force them to disembark and get their selfs killed...
-my suggestion is to force them to stay in their vehicles unless Fatal explosion will happen or there is no spotted enemy nearby when the armed vehicle is damaged.

**Steps to reproduce:**
feature request

**Where did the issue occur?**
feature request

**Additional information:**
for realism purposes and gameplay 

**RPT log file:**
feature request

**Comment by TheMagnetar** [comment]
This is out of the scope of ace3. There are better mods to hold this feature like VCOMAI or ASR AI 3

**Comment by PabstMirror** [comment]
can stick this a mod or a mission description.ext
```
class Extended_InitPost_EventHandlers {
    class Car {
        class NoFear { init = "(_this select 0) allowCrewInImmobile true;"; };
    };
    class Tank {
        class NoFear { init = "(_this select 0) allowCrewInImmobile true;"; };
    };
};
```

**Comment by bux** [comment]
>KnowNoFear

![](https://i.ytimg.com/vi/18moPwvPkIQ/hqdefault.jpg)
