### ISSUE TITLE
Tank Danger zone (feature request)

### ISSUE THREAD

**Issue by AirShark07** [acemod/ACE3#7034]
**Arma 3 Version:** `latest` (stable / rc / dev)
**CBA Version:** `latest` (stable / dev + commit hash)
**ACE3 Version:** `latest` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
-RHS
```

**Description:**
iirc ace or ace 2 had a very nice feature called Tanks Danger zone where any one will be close to a tank when shooting will get hurts or injured...

**Steps to reproduce:**
feature request

**Where did the issue occur?**
feature request

**Additional information:**
![M256_danger](https://user-images.githubusercontent.com/50262446/58964183-66c4b880-87a6-11e9-8960-ec9d0d1b7329.png)

**RPT log file:**
feature request

**Comment by bux** [comment]
Feature Requests have their own place on github.

And overpressure is already added to ace3 ...
https://github.com/acemod/ACE3/tree/master/addons/overpressure
