### ISSUE TITLE
AtragMX, Kestrel, Rangecard not working from backpack

### ISSUE THREAD

**Issue by Blutze** [acemod/ACE3#7035]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.11.2` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
AtragMX, Kestrel and Rangecard cannot be opened when they are held in the backpack. Other ACE gadgets I tested (wirecutter, mortar rangetable, **MicroDAGR**, entrenching tool, explosives w/ military clackers, defusal kit, cable ties) are not affected.
They don't open when the hotkey (both _open_ and _show_, in the case of the Kestrel) is pressed, and are not available in the self interaction menu.
Moving them to the vest fixes this, moving them back to the backpack removes them from the self interaction menu and disables the opening/showing hotkeys. I did not test leaving them while moving them to the backpack.

**Steps to reproduce:**
- Carry AtragMX, Kestrel and Rangecard in your backpack
- Press hotkeys to open these menus, nothing happens
- Open self interaction menu, equipment category: the gadgets are not listed there

**Where did the issue occur?**
- Dedicated / Singleplayer / Virtual Arsenal

**Additional information:**
[This file](https://github.com/acemod/ACE3/blob/master/addons/atragmx/initKeybinds.sqf) is not used in the MicroDAGR addon. The "Add deviceKey entry" code for the MicroDAGR is in XEH_clientInit.sqf instead, and there doesn't seem to be any call to `CBA_fnc_addKeybind`.

**RPT log file:**
https://gist.github.com/Blutze/0c1cf00ceba8dea127a9cbc05070339a

**Comment by dedmen** [comment]
I think that's intended, can't look at thing lying in the bottom of your backpack behind your back.

I think the bug is rather that rangetable, microDagr, clackers work.

wirecutter (you kneel down anyway and use it, it's realistic that you grab behind your back and quickly pull it out)
explosives (same, you kneel down)
defusal kit (same)
cable ties I'm not sure, There is no timer for applying cable ties, I think they shouldn't be allowed in backpack, but you might have them hanging on the outside of your backpack, which then would be fine.

**Comment by Blutze** [comment]
I can see that balancing/realism approach, even though I'd be very careful with making specifically explosives and wirecutters front-pouch-only. If you are running slightly bigger ammo and a low-capacity vest, you might end up unable to properly use them.

It needs to be documented and clearly recognizable as intended behaviour however. A note on the wiki pages wouldn't be sufficient really, it should be obvious in use during a mission.

**Comment by bux** [comment]
It's intended.
As @dedmen said the other tools might need to be reworked in that regard.

Feel free to add the info to the documentation 👍

**Comment by dedmen** [comment]
>I'd be very careful with making specifically explosives and wirecutters front-pouch-only

Same. I would not do that. Through the timer that runs we have enough time that the player might realistically take them out of his backpack.

**Comment by PabstMirror** [comment]
This might be slightly more realistic, 
but it's a requirement that isn't always intuitive and not documented all that well.
I think we should just drop it and just use the `uniqueItems` func

**Comment by jonpas** [comment]
Agreed. Technically you can mount gadgets on backpack straps so they are instantly accessible as well. Arma inventory is just too generalized to bother with details like that.

**Comment by Laid3acK** [comment]
It's like that since the beginning,
it's more like a feature request than an issue.
And seriously guys, the range card in the backpack ?

**Comment by Drofseh** [comment]
I also dislike items being unusable in the backpack.

**Comment by bux** [comment]
I agree with @Laid3acK 
We model e.g. the Eötvös effect for a bullet but some are in favor of dropping a realistic feature?

**Comment by jonpas** [comment]
>  We model e.g. the Eötvös effect for a bullet but some are in favor of dropping a realistic feature?

How is this a realistic feature? I can put a range card on the strap of my backpack and access it very easily. That's still a backpack in terms of Arma.

**Comment by bux** [comment]
> very easily

please ...

**Comment by jonpas** [comment]
https://cdn.vitecimagingsolutions.com/pub/media/catalog/product/cache/e4d64343b1bc593f1c5348fe05efa4a6/p/h/phone-pouch-protactic-phone-pouch-lp37225-on-backpack-strap-rgb.jpg

How is this harder to retrieve than in your vest or uniform?

**Comment by PabstMirror** [comment]
```
ace_common_fnc_itemAccessable = {
    params ["_unit", "_item"];
    if (GVAR(noBackpackItems)) then { 
        (_item in (uniformItems _unit)) || {_item in (vestItems _unit)}
     } else {
         _item in (_unit call EFUNC(common,uniqueItems))
     };
};
```

**Comment by jonpas** [comment]
Decision made: remove requirement to use the item from uniform or vest only, should be available from anywhere.
