### ISSUE TITLE
ace3 error loadorder

### ISSUE THREAD

**Issue by zambino12** [acemod/ACE3#7036]
**Arma 3 Version:** latest
**CBA Version:** latest
**ACE3 Version:** latest (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- when starting up arma 3 gives me this error 
![lame](https://user-images.githubusercontent.com/47878215/59058538-7b668680-8862-11e9-8fa1-052e34f4e8a7.PNG)

**Steps to reproduce:**
-start up

**Additional information:**
- dont know if this is important but hell

![killme](https://user-images.githubusercontent.com/47878215/59058716-d9936980-8862-11e9-961a-bf676e94115a.PNG)

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by alganthe** [comment]
Two things:

- Did you load the ADR-97 "official mod" ? it has been added to vanilla and thus would cause issues.
- Can you post an RPT ? (see the bottom of your comment)

**Comment by zambino12** [comment]
> Two things:
> 
> * Did you load the ADR-97 "official mod" ? it has been added to vanilla and thus would cause issues.
> * Can you post an RPT ? (see the bottom of your comment)

yes i did load the adr-97 mod and i have been trying to get a RPT and its very confusing as to where i need to go to get it me no tech man

**Comment by zambino12** [comment]
but it is fixed now
