### ISSUE TITLE
ACE interaction with the Civilians

### ISSUE THREAD

**Issue by Papagon2** [acemod/ACE3#7037]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Add order "Go/Run Away" and "Get Down!" with interaction to the civilians / AI.

**Steps to reproduce:**
- unknown

**Where did the issue occur?**
- No issue. Only missing. 

**Additional information:**
- Like added in description. Wish for interaction's with the AI where we can Tell them to "Go/Run Away" and "Get Down!" .

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by bux** [comment]
Lazy issue writing and feature request.

**Comment by commy2** [comment]
Isn't this already in?

**Comment by PabstMirror** [comment]
If you want to disable this feature, there is an ace setting for it

**Comment by commy2** [comment]
Maybe Papagon disabled these actions.

**Comment by Papagon2** [comment]
I did not disable anything. I requested this because its missing. When we ace interact with a civilian we can only Hnadcuff and than search or escort prisoner. but there is no feauture that says we can tell the civilian/AI to go/run away or Get down!.
this is why I ask for the request because I try find out how to do fix this myself but have not been able to figure out how. And many ppl. I askt do wish it was implemented.

Sorry for bad English.

**Comment by commy2** [comment]
But those actions are in fact in ACE already. See:
![https://i.imgur.com/kRrjJ2i.png](https://i.imgur.com/kRrjJ2i.png)
(ignore the debugging stuff)

**Comment by Papagon2** [comment]
okay? so how do I tun it on than? because I spawn AI down and there is no go away order or any of that. :o

**Comment by Papagon2** [comment]
nvm my issiue than. It was the ALIVE module that makes the "Go Away" "Get down" to go away. So I belive this is an ALIVE issiue than. other words something ALIVE need to implement?
