### ISSUE TITLE
HandleDamage causes cookoff game crash

### ISSUE THREAD

**Issue by MidnightGH** [acemod/ACE3#7043]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.11.2.190515` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Modifying damage taken to vehicles with "HandleDamage" event handler causes vehicles to duplicate cookoff explosions/missiles by a lot. Crashes the game.

**Steps to reproduce:**
- Add the handler to a vehicle like the commanche, reduce the incoming damage with the handler by half for example. Crash, lots of missiles, death of game.

**Where did the issue occur?**
- Singleplayer

**Additional information:**
- Unsure if this has to do with how damage is handled with ace in contrast to the vanilla. But I can no longer use the two together as a result.

**RPT log file:**
- https://pastebin.com/3VLaKyDd

**Comment by MidnightGH** [comment]
here is the code I used in specific on veh:
`(vehicle player) addEventHandler["HandleDamage", 
{ 
 diag_log str _this; 
 params["_veh","_selection","_damage","_source"]; 
 if(_selection != "" && _source != objNull) then { 
  hintSilent format["%1 %2",_selection,_source]; 
 }; 
 _damage / 2; 
}];`

**Comment by MidnightGH** [comment]
Here is a video demonstrating: https://www.youtube.com/watch?v=vByYg_rtbbA&feature=youtu.be

**Comment by severgun** [comment]
Quote from BIKI

> "HandleDamage" will continue to trigger even if the unit is already dead.

Maybe you should check `alive _veh` too?

**Comment by BaerMitUmlaut** [comment]
HandleDamage is one of the weirdest EHs. I'm not surprised that something breaks when you stack it.

**Comment by commy2** [comment]
Dividing the total damage by two makes the vehicle invincible.

**Comment by MidnightGH** [comment]
Haven't really pondered some of these responses. It surprised me immensely either way. As it was very loud, very quick. Threw my headset on the ground in response.

**Comment by dedmen** [comment]
Just had a report of this on Arma discord, Was reported as a "memory leak" but also on vehicle explosion when hit by a missile, seems to be same issue.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
