### ISSUE TITLE
RHS ACOGs can be adjusted like sniper scope.

### ISSUE THREAD

**Issue by acknowledge14** [acemod/ACE3#7055]
Arma 3 Version: 1.94 (stable )
CBA Version: 3.11.2.190515-cec0e465
ACE3 Version: 3.12.6.43-7d9a4f47

Mods:
--All 4 RHS mods + 3 lastest offical ACE compats
--CBA_A3
--ace 

Discription:
All the ACOGs from RHS can be adjusted  horizontally and vertically in mils, is it intentionally?
On the contrary，RHS Spectre DR scopes do not have this feature.

Image:
https://imgchr.com/i/V7G53d

**Comment by CCRcmcpe** [comment]
It should be adjustable according to the [ACOG's operator manual](https://github.com/acemod/ACE3/files/7834035/A1j5Y2GYQVS.pdf).
