### ISSUE TITLE
Mag proxies need to be updated to match vanilla. MX cannot use MX mags with different camo

### ISSUE THREAD

**Issue by cmasonw0070** [acemod/ACE3#7056]
**Arma 3 Version:**latest
**CBA Version:** `latest
**ACE3 Version:** `latest
(As of 6/16/2019)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The MX cannot use other variant's magazines. ie: not green mag with tracers for black MX

**Steps to reproduce:**
- Add MX. Try to load magazines in question

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal- All of the Above

**Additional information:**
- No additional info needed

**Comment by alganthe** [comment]
Fix has already been merged both in CBA and ACE3, closing.

**Comment by cmasonw0070** [comment]
Well the bug is still present. Will this be fixed in a coming update?

**Comment by commy2** [comment]
That's what alganthe said, yes.
