### ISSUE TITLE
Question / Wish

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#7065]
Hello . I wanted to know a couple of questions:
1.  Is it possible to duplicate the "fix bug" from main menu to the player action menu?
2.  Is it possible to add role to the nicknames overhead, such as if in the mission someone is called “commander”, “pilot” or "bla-bla" and so on. And to do this in the settings enabled or disabled by the function, as with nicknames and the display of the conversation. As in this script for example
http://joxi.ru/D2Pdz7LcqapPx2
http://joxi.ru/4Aklg1qToRypPr
https://github.com/Quailsnap/WHA-Nametags

**Comment by dedmen** [comment]
>Wish

https://github.com/acemod/ACE3/issues/3594
