### ISSUE TITLE
Map Tools ruler-side drawing - Remove please

### ISSUE THREAD

**Issue by Saborknight** [acemod/ACE3#7070]
**Arma 3 Version:** `1.94` (stable / rc / dev)
**CBA Version:** `3.11.2` (stable / dev + commit hash)
**ACE3 Version:** `3.12.6` (stable / dev + commit hash)

**Description:**
- Not an issue, but a request to remove a feature.
- The map tools, when drawing along its ruler, will put a map marker down. This is a rather thick map marker, and the drawing itself is quite glitchy (mouse being forced a specific way down the edge of the ruler). I understand that, in the past, Arma 3 didn't allow for straight lines being drawn, and that being the reason the map tools had this functionality implemented. However, now that we're capable of drawing straight lines that are not only thinner and more accurate, but also easier to use, could we not just remove the drawing functionality of the map tools ruler?

**Comment by Saborknight** [comment]
![107410_20190627163426_1](https://user-images.githubusercontent.com/9272259/60242658-83619580-98f9-11e9-927f-811ec2e3aadd.png)
Screenshot of the difference between the map tools line and the vanilla line

**Comment by dedmen** [comment]
>now that we're capable of drawing straight lines that are not only thinner and more accurate

What? how? didn't know that was possible.
Also don't see need to remove a feature, it's still good if you want thicker lines.

**Comment by Saborknight** [comment]
It would be, if it were optional. The issue is, for navigation and things that require precision, the thick lines offer a higher degree of inprecision than the vanilla straight lines.
Could there at least be a CBA option to disable it?

And for the record, hold Ctrl+Shift for striaght lines in vanilla @dedmen ;)

**Comment by jonpas** [comment]
We would have used vanilla straight drawing of there would be useful API IIRC from early discussions when that was added to vanilla.

I don't see the need to remove that at all, it's very nice for drawing straight lines on specific bearings and so on.

We could possibly make them thinner though.
