### ISSUE TITLE
Fatal Professional Mistakes in Advanced Medical

### ISSUE THREAD

**Issue by laoyi198336** [acemod/ACE3#7071]
**Arma 3 Version:** `1.92` (stable)
**ACE3 Version:** `3.12.6` (stable )

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- I have found a few fatal professional mistakes in Advanced Medical.First, atropine increases heart rate,but not lowers it.Secondly, the normal systolic blood pressure was 90 to 139 mmHg, and the normal diastolic blood pressure was 60-89mmHg，not  like the blood pressure values described on ace3mod's website.I hope the authorities can correct these mistakes, thank you!

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by laoyi198336** [comment]
I made a mistake. Small doses of atropine do slow down the heart rate, and large doses do increase the heart rate.But I insist on my objection to the blood pressure value.

**Comment by bux** [comment]
I'm closing this because the medical system has already been completely rewritten.
Please create a new issue after the medical rewrite has been released (no ETA).

**Comment by dedmen** [comment]
I think the problem was just incorrect numbers in ace wiki

**Comment by jonpas** [comment]
Besides, atropine is getting removed in rewrite.

**Comment by laoyi198336** [comment]
> I'm closing this because the medical system has already been completely rewritten.
> If this issue persist (unlikely) please create a new issue after the medical rewrite has been released (no ETA).

THANKS A LOT!
