### ISSUE TITLE
Missing grenade impact sounds

### ISSUE THREAD

**Issue by Gwynblade** [acemod/ACE3#7073]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.11.2` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
With ACE running, you get grenade pin pull sounds, but no grenade impact sounds (when grenade hits the floor or wall for example). 
With no mods loaded, you get grenade impact sounds, but no pull pin sounds (since ACE adds that).

**Steps to reproduce:**
https://www.youtube.com/watch?v=vbAb25obxCM&feature=youtu.be
Comparison with, and without ACE

**Where did the issue occur?**
Everywhere

**Comment by jonpas** [comment]
Are we not spawning the correct projectile? :thinking: 

@PabstMirror clues?

**Comment by commy2** [comment]
There may be a difference between an engine created and createVehicle'd ammo object.
This is not about advanced throwing, right? So it should be the engine created projectile anyway.

**Comment by jonpas** [comment]
I can't tell from the video if it's using advanced throwing or not. @Gwynblade ?

#4648 would have removed those sounds, but that was never merged.

**Comment by Gwynblade** [comment]
I just tested to be sure, and it's the same with normal and advanced throws.

Could this be it: https://github.com/acemod/ACE3/pull/3923 ?
It mentions something about removing clinking sounds.

**Comment by jonpas** [comment]
That could be it, it sets:
```cpp
impactGroundSoft[] = {};
```

**Comment by jonpas** [comment]
@commy2 you commented on that https://github.com/acemod/ACE3/pull/3923#discussion_r66970449, any clue why that was done?

**Comment by commy2** [comment]
I just commented that instead of setting `soundImpactSoft1[]` to `20` to `{"",1,1,1}`, one could just empty the array that references all these array tokens. Which is true.

Probably should just delete that config entry and restore the "ridiculous" vanilla sounds. I never had a problem with them.

**Comment by commy2** [comment]
Can't have impact sound that does not play on projectile creation, which sounds dumb when throwing the grenade.
