### ISSUE TITLE
Mine defusal role

### ISSUE THREAD

**Issue by anfo55** [acemod/ACE3#7077]
Hi, no problem to report, just a question about an ACE functionality.
Presently, any blufor with a defusal kit, engineer or not, can defuse a trip mine. Is this by design?

**Comment by mharis001** [comment]
The `ace_explosives_requireSpecialist` setting controls whether the unit must an EOD to be able to defuse an explosive. [reference](https://github.com/acemod/ACE3/blob/master/addons/explosives/functions/fnc_canDefuse.sqf#L29)

An EOD is a unit which has the `ACE_isEOD` variable set on it as `true` or has the `explosiveSpecialist` unit trait. [reference](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_isEOD.sqf#L23)

If you want to require being an EOD to be able to defuse, enable the require specialist setting and assign your EOD by setting the `ACE_isEOD` variable to true on it.

Hope that helps.

**Comment by anfo55** [comment]
Thank you @mharis001 for your reply
I'm really sorry to ask since your explanation is worded in such way that I should understand, but I'm still a bit lost with where to put the information you've supplied. If 1 unit out of 8 is to be EOD, in practical terms, which code would go where please?

**Comment by commy2** [comment]
Isn't this a checkbox in the editor?

**Comment by mharis001** [comment]
@anfo55 you could put `this setVariable ["ACE_isEOD", true];` in the init box of the unit. #7080 will add a 3DEN attribute for this.

**Comment by anfo55** [comment]
Thankyou @mharis001 , I hope my little question and the new plan to implement into 3DEN is a popular choice and worth your effort. :)
If this helps with your implementation, I applied the `this setVariable ["ACE_isEOD", true];` to an already ACE Engineer player intended for the EOD role, and he was able to defuse, as you would expect, a regular trip and APERS mine. However, a small issue appears to remain, that another player -without- the `this setVariable ["ACE_isEOD", true];` can still defuse.

**Comment by commy2** [comment]
Replace true with false for the unit that is not supposed to diffuse.

**Comment by anfo55** [comment]
Ah, whoops! I wrongly assumed the true attribute on one unit, would make all others instantly false. Thanks @commy2

**Comment by anfo55** [comment]
Didn't work unfortunately. Fire away with more questions if it helps you get to the bottom of this :)

**Comment by commy2** [comment]
In the server settings, enable ace_explosives_RequireSpecialist.

**Comment by anfo55** [comment]
Do you mean `[player] call ACE_Explosives_fnc_canDefuse` in init.sqf?

**Comment by commy2** [comment]
No, open the ADDON OPTIONS menu and tick the approiate setting under the SERVER tab.

**Comment by anfo55** [comment]
Oh ok, a little above my pay grade! I'll check with an admin in my group to look into that.
