### ISSUE TITLE
MakeLoadable replacement

### ISSUE THREAD

**Issue by anfo55** [acemod/ACE3#7081]
Quite a while ago we used a (deprecated since ACE 3.12.0) logic called `ace_cargo_makeLoadable`, to prevent cargo from being mistakenly loaded into a vehicle.
May I inquire, is there a different function that has replaced this?

**Comment by bux** [comment]
For questions like these please join our public chat:
https://slackin.ace3mod.com/

**Comment by anfo55** [comment]
Oh sorry, will do

**Comment by jonpas** [comment]
Just set cargo size, the rest happens automagically. All this info can be found on wiki.
