### ISSUE TITLE
When will be Armor Damage System ACE2?

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#7085]
The system of computing logic based on hit points. The system expects that trial reservation and assigned damage in accordance with a typical incident and scene will be detected.
Features:
Works for all tracked and wheeled armored vehicles.
The system is based on real data on armor thickness and test capabilities of ammunition.
The system takes into account the angle of hitting test armor with a low probability.
Simulation of dynamic protection and lattice screens
Simulation of emergency run, fire systems and vehicle fires
Crew damage simulation
Machine guns / automatic guns are capable of trying light armor in certain places.
Armor is invulnerable to small arms.
Limitations:
The system depends on the settings of hit points in the model. For example, a tower instead of a shell. The system works quite accurately.
ACE for better modeling (the second option - the system can work with vehicles and without parameters), but then it is very likely that the behavior of the armor will differ from the real characteristics). It can be found in ace_sys_vehicledamage \ documents for example.
The system will not work with createvehicle'd (what is it?), Which can be used in some missile complexes. In this case, the place of entry is chosen randomly.

Система логики вычислений, основанная на хитпоинтах. Система рассчитывает на то, что пробные брони и назначенные повреждения в соответствии с типичным происшествием и местом происшествия будут обнаружены.
Особенности:
Работает для всех гусеничных и колесных бронированных транспортных средств
Система основана на реальных данных о толщине брони и пробных способностях боеприпасов
Система учитывает угол попадания в пробную броню с низкой вероятностью
Моделирование динамической защиты и решетчатых экранов
Моделирование аварийного хода, огневых систем и возгорания транспортного средства
Моделирование ущерба экипажу
Пулеметы / автоматические пушки способны пробовать легкую броню в определенных местах
Броня неуязвима для стрелкового оружия.
Ограничения:
Система зависит от настроек хитпоинтов в модели. Например, башня вместо корпуса. Система работает довольно точно.
ACE для лучшего моделирования (второй вариант - система может работать с транспортными средствами и без параметров), но тогда очень вероятно, что поведение брони будет отличаться от реальных характеристик). Можно найти в ace_sys_vehicledamage \ документы для примера.
Система не будет работать с createvehicle'd (что это?), Которые могут быть использованы в некоторых ракетных комплексах. В этом случае место попадания выбирается случайно.

**Comment by commy2** [comment]
#3594
