### ISSUE TITLE
Command Bar is still missing in 2019

### ISSUE THREAD

**Issue by ItayNoyman** [acemod/ACE3#7087]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.12.6` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
So i did a research and i found out that the command bar is still a problem till this day. i myself cant see it while using ace3 mod and its only visible if you get on spectator mod and get back. it has been about 4 years and this problem isnt solved.

**Steps to reproduce:**
log in the game, at any game mode it doesnt work.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
the command bar works when you go to spectator and than get back to your character.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by jonpas** [comment]
Read https://ace3mod.com/wiki/feature/ui.html. You will see it's a setting and disabled by default.

> it has been about 4 years and this problem isnt solved.
Because there is no problem, one just has to read the documentation or change log with releases, where it was clearly stated. :)

**Comment by dedmen** [comment]
>Additional information:
the command bar works when you go to spectator and than get back to your character.

I guess that's a bug?

**Comment by commy2** [comment]
Yeah, seems like a bug to me.
