### ISSUE TITLE
Question about cargo framework

### ISSUE THREAD

**Issue by HE4TO** [acemod/ACE3#7089]
Will try to explain in simple way.
I have an item with ID "box1". When on mission, I load it in cargo of some vehicle. When the vehicle is destoyed i need {alive box1} to return false. But on dedicated server it returns true. Have no idea what to do. Will appreciate any help.

**Comment by Drofseh** [comment]
Come ask in the Ace3 Slack. This is an area for issue reports not questions.

https://slackin.ace3mod.com/
