### ISSUE TITLE
Optic ranging is broken when advanced scopes is disabled

### ISSUE THREAD

**Issue by JoramD0** [acemod/ACE3#7096]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.12.0` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
- CUP Weapons
- CUP Units
- CUP Vehicles
- CUP Terrains - Core
- CUP Terrains - Maps
- CUP ACE3 Compatibility Addon - Weapons
- CUP ACE3 Compatibility Addon - Vehicles
- CUP ACE3 Compatibility Addon - Terrains
- NIArms All in One
- NIArms All in One - CUP Compatibility
- NIArms All in One- ACE Compatibility
- MLO All-In-One Collection
- [MELB] Mission Enhanced Little Bird
- Achilles
- ShackTac User Interface
- Enhanced Movement
- BackpackOnChest
```

**Description:**
- When advanced ballistics and advanced scopes are turned off it is not possible to change range on vanilla optics, they are all stuck to 100m. On modded optics the ranging does seem to work.

**Steps to reproduce:**
- Turn off advanced ballistics/scopes and try changing the ranging.

**Where did the issue occur?**
- Dedicated

**Additional information:**
- Here are the [ACE server settings](https://gist.github.com/JoramD0/66136b80ec5810fc77c8d32ff45aecf9), maybe I messed something up myself.

**RPT log file:**
- [RPT](https://gist.github.com/JoramD0/5c3df965bd1be6ebf23fe45bc1d64fd2)
- [ACE Debug](https://gist.github.com/JoramD0/b9a27171ef0284534cb97025d92da71c)

**Comment by commy2** [comment]
You have to delete ace_scopes.pbo from your repository do that. The discreteDistance config entry is config only and cannot be changed by scripting, thus you have to remove the config manually.
