### ISSUE TITLE
Issue with microdagr/wind indicator updating directional display correctly

### ISSUE THREAD

**Issue by ZKatz** [acemod/ACE3#7102]
**Arma 3 Version:** `3.26` (stable)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The wind indicator (activated by shift+k) only updates every 90 degrees rather than by the clock dial. This also applies to the microdagr where the degree indicator only updates every 90 degrees from where you were first facing.

**Steps to reproduce:**
- Load up empty mission with cba and ace3.
- equip microdagr or don't , if you want to test it. 
- press shift+k to open wind dial in a windy area.
- turn and check wind direction.

**Where did the issue occur?**
- All: Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Additional information:**
- Noticed it about a 3 months ago.

**RPT log file:**

[RPT.txt](https://github.com/acemod/ACE3/files/3390656/RPT.txt)

**Images displaying issue:** - making small turns and showing compass barring vs what is displayed by microdagr and wind indicator.
![20190714214307_1](https://user-images.githubusercontent.com/26122900/61192383-ea18da00-a681-11e9-9be1-8a851de3e5c3.jpg)
![20190714214311_1](https://user-images.githubusercontent.com/26122900/61192384-eab17080-a681-11e9-8539-b98f90f080b2.jpg)
![20190714214256_1](https://user-images.githubusercontent.com/26122900/61192385-eab17080-a681-11e9-8afa-20ba2201d183.jpg)
![20190714214258_1](https://user-images.githubusercontent.com/26122900/61192386-eab17080-a681-11e9-8f31-0eadf51030a8.jpg)

**Comment by PabstMirror** [comment]
make sure your cba is updated
https://github.com/CBATeam/CBA_A3/releases/latest

**Comment by ZKatz** [comment]
Tested, you are correct that was the issue. Thanks for the assistance.
