### ISSUE TITLE
BP loss not linked to HR in Advanced Medical

### ISSUE THREAD

**Issue by micahwhitsel** [acemod/ACE3#7108]
**Arma 3 Version:** 1.92.145369 (stable)
**CBA Version:** V3.12.0 (stable)
**ACE3 Version:** 3.12.6 (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- When using ACE advanced medical, Blood Pressure loss (rate blood drains) does not seem to be linked to the Heart Rate. First noticed this on a more extensive modpack on a dedicated server and decided to test in a more controlled environment and got the same result. Is this intentionally scripted this way, an oversight, or an error in testing methodology?

**Steps to reproduce:**
- Shot an AI in the arm to cause a bleed. Measured the rate of BP loss. Induced cardiac arrest using adenosine and then continued to measure the rate of BP loss, witnessed no change.

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer)

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
-https://pastebin.com/j5gPQsRN

**Comment by BaerMitUmlaut** [comment]
Blood loss is linked to hear rate in medical rewrite, which will be in the next major update (3.13).

**Comment by micahwhitsel** [comment]
Thank you for clearing up the matter. I look forward to 3.13
