### ISSUE TITLE
Key binding don't work with the artillery range table

### ISSUE THREAD

**Issue by Elgin675** [acemod/ACE3#7116]
**Arma 3 Version:** `1.94.145903`
**CBA Version:** `3.11.2`
**ACE3 Version:** `3.12.6`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The keybinding in ACE Equipement for the range table don't work correctly :
It's ok for sniping range table, but don't work with artillery range table.

**Steps to reproduce:**
- Just bind a key for range table, and try ;).

**Where did the issue occur?**
- Multiplayer and Singleplayer

PS : sorry for my bad english

**Comment by commy2** [comment]
By design?

**Comment by Elgin675** [comment]
> 
> 
> By design?

Indeed!
I must have been confused at the time.
I'm sorry, this "issue" is useless, yes.
I'll close it ;).

**Comment by PabstMirror** [comment]
somethign that you open and close a lot might be a good candidate for a keybind
just like the gun rangetables

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
