### ISSUE TITLE
AtragMX increasing velocity glitch

### ISSUE THREAD

**Issue by ZKatz** [acemod/ACE3#7117]
**Arma 3 Version:** `1.94.145903` (stable)
**CBA Version:** `3.12.0.190708` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- When using the Atrag, opening and closing the tab using the home key will increase the current muzzle velocity in the Atrag's gun tab. I.e. opening and closing it will increase the value by a half, or at least appears to as opening and closing the Atrag twice will increase the listed muzzle velocity by one. This also increases the muzzle velocity array's values by the same amount each time.
- Happens only in Advanced Ballistics as far as I've seen, and it occurs randomly, but I will try to upload a video of the issue occuring.

**Steps to reproduce:**
- Load into empty mission.
- Grab a uniform and get AtragMX, Kestrel4500NV, and range card.
- Open AtragMX and check current values.
- Toggle AtragMX by either opening and closing with home twice or more.
- Pay attention to MV under GUN as it steadily increases.

**Where did the issue occur?**
- Dedicated / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Additional information:**
- Somehow seems like even toggling into the main AtragMX screen can increase that loadout's muzzle velocity.

**Video:**
https://vimeo.com/350863474

**Comment by Laid3acK** [comment]
Confirmed.

A very strange bug, the AtragMx doesn't like the temperature 14.5 °C (seems ok with other temp values),
when apply in the Tmp field, the MV increases +1 m/s after close/open the AtragMx two times.
I tried with 14.51 °C and 14.49 °C it's ok, but with exactly 14.5 : bug.

I tried also with different ammos, same bug.

The correct video link if you want to check it yourself:
https://vimeo.com/user68580496

**Comment by commy2** [comment]
Are you sure it is not simply the temperature rising slowly? It is high noon by default in Arma (and therefore most missions). What you see may just be rounding.

**Comment by ZKatz** [comment]
Temperature is something you manually put in.. it wouldn't automatically update by opening and closing the Atrag. Also thanks Laid3acK for figuring out the temperature was the catalyst. I'll play around to see if it's other temperatures but if it's that then it can at least be avoided.

**Comment by ZKatz** [comment]
So I took another look at the temperature and it's for any temp at #.5 degrees.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
