### ISSUE TITLE
Advanced Medical System - NPC spawn

### ISSUE THREAD

**Issue by BlackIce931** [acemod/ACE3#7121]
**Arma 3 Version:** `1.94.145.903` (stable)
**CBA Version:** `3.12.0.190708` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHSUSAF
- RHSUSAF - ACE Compatibility
- ADV - CPR
- ADV - Ace Medical
- ITARMY_LITE mas
- ITSOF_LITE mas
- TFAR (Beta)
```

**Description:**
- When NPC is spawned he most of the times dies or he does not bleed nor feels pain.

**Steps to reproduce:**
- Interacting with an object to call the script via addAction.

**Where did the issue occur?**
- Editor (Multiplayer)

**Additional information:**
- `'B_Survivor_F' createUnit [getMarkerPos "PatientSpawn_01", _grp,'tizio1=this; dostop tizio1'];

tizio1 disableAI "path";

[tizio1, selectRandom[0.3,0.5], "leg_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "leg_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "leg_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "leg_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "leg_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "leg_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "leg_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "leg_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "leg_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "leg_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "body", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "body", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "body", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "body", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "body", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "head", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "head", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "head", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "head", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "head", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "hand_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "hand_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "hand_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "hand_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "hand_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "hand_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "hand_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "hand_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "hand_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
[tizio1, selectRandom[0.3,0.5], "hand_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;.`

**RPT log file:**
- https://pastebin.com/f7sdeiNi even if not really necessary

**Comment by commy2** [comment]
wtf?

**Comment by BlackIce931** [comment]
What's the problem with that?

**Comment by dedmen** [comment]
https://forums.bohemia.net/forums/topic/224629-advanced-medic-ace-3

**Comment by BlackIce931** [comment]
Wow m8, great solution you gave me. I will defo try it!!
Best idea ever.

**Comment by PabstMirror** [comment]
with medical from last stable release, you need to have a delay between calls to `ace_medical_fnc_addDamageToUnit` or the engine will see all the damage as coming from the same source. This is not an issue on the medical rewrite

e.g.
```
[] spawn {
[tizio1, selectRandom[0.3,0.5], "head", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
sleep 0.25;
[tizio1, selectRandom[0.3,0.5], "head", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
};
```

**Comment by BlackIce931** [comment]
@PabstMirror is that 0.25 a generic time or the minimum suggested?

**Comment by PabstMirror** [comment]
I think it actually uses 3 or 4 frames, so you do a delay based on that, 
0.25 sec is just a simple and safe number.

**Comment by BlackIce931** [comment]
Cool.
Just tried but still nothing.

Most of the time the NPC dies, but always he does not feel pain nor bleed.

**Comment by dedmen** [comment]
>Wow m8, great solution you gave me. I will defo try it!!
As I wrote.. "Context". Never said it's any solution and it wasn't meant to be either..

**Comment by BlackIce931** [comment]
Accept my apologies, then.
I thought that, after the first message, that wanted to be a kind of a joke.



For the rest it is correct, units are dying instead of going unconscious and they do not bleed and the do not feel pain.

**Comment by SilentSpike** [comment]
Fixed in rewrite?

**Comment by PabstMirror** [comment]
I don't think you need the delay anymore because it's event based
