### ISSUE TITLE
Map light doesn't detect laser/light attachments

### ISSUE THREAD

**Issue by dedmen** [acemod/ACE3#7130]
**Arma 3 Version:** `1.94` stable
**CBA Version:** `3.12.0.190708` stable
**ACE3 Version:** `3.12.6` stable

**Mods:**
```
- CBA_A3
- ace
- TONS OF OTTHER MODS YA FUQ
```

**Description:**
- You cannot use a Laser/Light weapon attachment as Maplight if it's not currently switched to Light mod.

**Steps to reproduce:**
- Take laser/light attachment onto gun
- Can't use it as maplight

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
- Cuz it checks only the current attachment, which is currently a laser only. Thought as you can switch directly over, it would make sense that you can just switch it. Instead of first having to switch to your pistol, then switch to flashlight, then switch back to main weapon, then go to map and then enable the light.

**RPT log file:**
N/A

**Comment by commy2** [comment]
just switch to flashlight mode you lazy bum

**Comment by dedmen** [comment]
Why BI's fault?
Its our fault that maplight doesn't check if current weapon attachment, is CBA switchable, and whether the switchable states have light support.

Thats rather trivial to fix.
When checking for maplight, check if attachment has switching, and check the other states for light.
We don't need to actually switch the mode over I think.

**Comment by commy2** [comment]
>just switch to flashlight mode you lazy bum

**Comment by jonpas** [comment]
This is terrible UX, user should at least know it's possible with the item they have.

**Comment by dedmen** [comment]
> just switch to flashlight mode you lazy bum

Sure. This definitely doesn't have any priority. But I still don't think it makes sense to close this, as this is definitely fixable.

**Comment by veteran29** [comment]
I agree with Dedmen, reopen? 😬

**Comment by commy2** [comment]
^ helper function

**Comment by dedmen** [comment]
> ^ helper function

still needs implementation of that in ACE then. Please reopen the ticket
