### ISSUE TITLE
ArmA 3 Startup CBA Error

### ISSUE THREAD

**Issue by Robbie-ED** [acemod/ACE3#7139]
**Arma 3 Version:** `1.94.145977` (stable)
**CBA Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
- ADR Official Mod
- Enhanced Movement
- All CUP
- All RHS
- All 3CB
- ShackTac User Interface
- Achillies
- Eden Enhanced
- ALIVE
...............
```

**Description:**
Upon "Initializing Addons" during A3 startup I get:
"addon cba_common requires addon a3_data_f_mod_loadorder"

Fix is to remove ADR Official Mod from the mod load list.

**Steps to reproduce:**
- Load your normal mods
- Include ADR Official Mod
- "Play with MODS"
- Wait until "Initializing addons"

**Where did the issue occur?**
- Arma 3 game startup

**Additional information:**
- This error appeared just after the latest update. Only CBA was updated and since then I cannot play unless I disable the ADR Mod.
I mean I can play but error pops up all the time.

**Comment by PabstMirror** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=669962280
```
ATTENTION: The ADR-97 weapon pack, our official mod, has been improved, polished and integrated into the vanilla game together with the Update 1.86. That means server hosts and content creators can now include it in their arsenal without needing to worry about whether players are subscribed to the mod on the Steam Workshop. Mods based on the ADR-97 can now be used directly with the vanilla game.

The Arma 3 Official Mod is now deprecated and its data have been removed from Steam Workshop. An empty mod has been retained to preserve all the links and information about the Official Mod's original purpose.
```
I would just uninstall the mod, it's now part of the base game

**Comment by alganthe** [comment]
the ADR-97 mod is now part of the base game and causes load order errors, remove it and all the compatibility mods that rely on it (we removed ours in 3.12.5

**Comment by Robbie-ED** [comment]
Ah nice, missed that.

Thank you for your help. Quick as always!
