### ISSUE TITLE
Blurred NVG

### ISSUE THREAD

**Issue by brandai38** [acemod/ACE3#7145]
Mods
- CBA_A3
- ace

Description:
When we turn on the night vision device and give the focus to zoom in, the image is blurred. The image should remain after 3-4 sec. sharpened to simulate manual sharpening on the device. Common sense suggests that it is better to have a sharp image at a distance where the enemy is at the expense of a blurred weapon than a razor-sharp weapon and making it impossible to recognize the target.

**Comment by commy2** [comment]
#3594?
