### ISSUE TITLE
RHS ACE compatibility

### ISSUE THREAD

**Issue by BloodSoakedBandit** [acemod/ACE3#7146]
**Arma 3 Version:** `1.94` (stable)
**CBA Version:** `3.12.1` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- RHS Version: `0.4.9` (stable)
```

**Description:**
- After the last RHS update. There are some compatibility issues. Like no ACE mags for updated weapons etc.

**Steps to reproduce:**
- Open Arma 3 ACE Arsenal
- Pick either Mk.11 or Mk.17
- Open the Ammo slot to see no ACE magazines

**Where did the issue occur?**
- Dedicated Multiplayer / Virtual Arsenal

**Comment by Blutze** [comment]
The vanilla and ACE 20rnd 7.62x51 mags shouldn't fit three different gun families (M14, HK417, fictional upscaled americanized SG550) in the first place, so extending that to SR-25 and SCAR-H would be a step in the wrong direction. The RHS SCARs have rather messy muzzle velocity configs as well, making this a balancing headache to boot.

There are gaps and mistakes in RHS's magWell usage, but they aren't specifically an ACE Compat concern.

**Comment by alganthe** [comment]
Mod issue then ?

**Comment by Blutze** [comment]
If there wasn't anything else besides the Mk 11 and the SCAR, then there was no issue at all.

**Comment by BloodSoakedBandit** [comment]
It was just that and I only brought it up, because you guys did it earlier with all the 7.62 NATO 20rnd platforms and honestly from a mission file author point of view it made a lot easier when setting things up.

**Comment by Chinook450** [comment]
As for game purposes I think the all 20 rnds 7.62 vanilla and ace mags should be included to fit the RHS SR-25 platform.      He are some facts http://www.biggerhammer.net/stoner/sr25var10/ar10vsr25.html
