### ISSUE TITLE
Inventory weight doesn't work with subordinates

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#7150]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.94`
- **CBA:** `3.12.1`
- **ACE3:** `weapon-on-back` Branch

**Description:**
When opening the inventory of subordinates, the name and weight of the player is shown in the titlebar, not the one of the subordinate.

**Steps to reproduce:**
- Place down two units, with the player being the group leader of the two
- Go in game, press backspace, F2, select "Action", "Open subordinate's inventory"
- See titlebar of the inventory

**Suggested fix:**
Wait until the `InventoryOpened` EH runs, first parameter is the unit.
Alternatively, compare the old text of the titlebar, check if it's the player's name. If it isn't, iterate through the group members until you find one with the correct name.

**Where did the issue occur?**
- Singleplayer

**Screenshots:**
![20190825161046_1](https://user-images.githubusercontent.com/9693842/63651237-e8e3ce00-c752-11e9-8616-cf6aa6914c92.jpg)

**Comment by M-Davies** [comment]
Easily reproduced on my build. Will look into this

**Comment by BaerMitUmlaut** [comment]
If you want to fix this, `InventoryOpened` runs before the dialog is opened, so just saving the unit that's passed in there in a GVAR would work.

**Comment by M-Davies** [comment]
Where is it ran from? Sorry, I'm quite new to the project and still am still figuring out how the codebase is set out

**Comment by BaerMitUmlaut** [comment]
There is no event handler for that event yet. I would add one like it's done here:
https://github.com/acemod/ACE3/blob/001942b2ed6b56f10b2b79b56d67dd0cc5bf62a4/addons/vehiclelock/XEH_postInit.sqf#L11

**Comment by M-Davies** [comment]
Potentially, we could create one in here: 
https://github.com/acemod/ACE3/blob/42042059082ded2802a35f7655c8230e4624b94e/addons/inventory/XEH_postInit.sqf#L1

I'm not sure what would be the best route of doing however. We could perhaps pass an extra parameter (the player), compare with the unit and go from there?

**Comment by commy2** [comment]
`InventoryOpened` is AL (despite what the wiki says), so you can just store the name of `_container` in a global and apply that name to the control.
(or apply the name to the control, whichever executes first, InventoryOpened or DisplayLoad).

**Comment by M-Davies** [comment]
DisplayLoad appears to open first. 

https://github.com/acemod/ACE3/blob/master/addons/inventory/functions/fnc_inventoryDisplayLoad.sqf

**Comment by M-Davies** [comment]
```
PREP(addCustomFilter);
PREP(currentItemListBox);
PREP(forceItemListUpdate);
PREP(inventoryDisplayLoad);
PREP(onLBSelChanged);

PREP(filterWeapons);
PREP(filterMagazines);
PREP(filterItems);
PREP(filterHeadgear);
PREP(filterUniforms);
PREP(filterVests);
PREP(filterBackpacks);
PREP(filterGrenades);
PREP(filterMedical);
```

**Comment by commy2** [comment]
?

**Comment by M-Davies** [comment]
So DisplayLoad is prepared first so I can apply _container to this?

**Comment by commy2** [comment]
Which function is preped first has no influence on what event handler triggers first.

**Comment by M-Davies** [comment]
Just double checked. It's still DisplayLoad. Sorry for the confusion

**Comment by commy2** [comment]
Then use InventoryOpened to overwrite the control.
Display is stored in uiNamespace as RscDisplayInventory.

**Comment by M-Davies** [comment]
In here? https://github.com/acemod/ACE3/blob/07a467e6cc012f920a755cea0b02312cba50b569/addons/inventory/CfgEventHandlers.hpp#L22

**Comment by commy2** [comment]
That's DisplayLoad.

https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#InventoryOpened

**Comment by M-Davies** [comment]
So something like this: 
```
GVAR(Unit_Opening_Inventory) = uiNamespace getVariable _unit;
```
in
https://github.com/acemod/ACE3/blob/001942b2ed6b56f10b2b79b56d67dd0cc5bf62a4/addons/inventory/XEH_postInit.sqf

**Comment by M-Davies** [comment]
I've gotten a little swamped in my day job lately so if anyone wants to have a crack at this issue feel free

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
