### ISSUE TITLE
AI armor vehicle didnt act to javelin(titan) missile?

### ISSUE THREAD

**Issue by IgarashiInaba** [acemod/ACE3#7159]
I found that use TITAN AT to attack AI armor vehicle, they wont pop smoke to jamming missle, and drongo's active protection is also cant intercept too.
then i delete ace_javelin and ace_missileguidence, it's back to normal, AI can pop smoke, and APS can intercept missile.
Is this a bug or what?

**Comment by synixebrett** [comment]
Use the full template, it sounds like you are using other mods

**Comment by IgarashiInaba** [comment]
> Use the full template, it sounds like you are using other mods

Nope, i test with cobalt ACE and original ACE are still same problem, and play commander by myself then pop smoke cant jamming missile too, its work when play vanilla game.
maybe you can try it, very strange

**Comment by Drofseh** [comment]
Like synixebrett said, use the full template.

**Comment by IgarashiInaba** [comment]
> Like synixebrett said, use the full template.

it's full template, i am using workshop version and didnt change anything

**Comment by Drofseh** [comment]
@IgarashiInaba Here is a copy of the full template that you need to fill out.

```
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
A clear and concise description of what the bug is.

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**
A clear and concise description of what you expected to happen.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**
Add any other context about the problem here.

**Screenshots:**
If applicable, add screenshots to help explain your problem.
```

**Comment by IgarashiInaba** [comment]
> **Mods (complete and add to the following information):**
> - **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
> - **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
> - **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]
> _Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_
> 
> **Description:**
> A clear and concise description of what the bug is.
> 
> **Steps to reproduce:**
> - Go to ...
> - Click ...
> - See ...
> 
> **Expected behavior:**
> A clear and concise description of what you expected to happen.
> 
> **Where did the issue occur?**
> - Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
> 
> **Log Files:**
> - Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
> 
> **Additional context:**
> Add any other context about the problem here.
> 
> **Screenshots:**
> If applicable, add screenshots to help explain your problem.

oh sorry i misunderstand, here is template.


**Mods (complete and add to the following information):**
- ARMA3 1.94.145977
- CBA_A3 3.12.1
- ACE3 3.12.6


**Description:**
when i aim to AI tank,then fire to them, they didnt use smoke. if i delete ace_javelin and ace_missileguidence, they use smoke again.
not just nato M2 tank, the csat T100 and T14 is same problem

**Steps to reproduce:**
1.start game
2.play in editor
3.place nato M2 tank and csat AT missile soilder,then play as a csat AT man
4.Aim to  tank then launch
5.Tank didnt use smoke then hit by titan missile

**Expected behavior:**
AI should pop out smoke to let titan missile miss target. like vanilla game.
Player as commander use smoke should let missile miss target too(i have try serveral time and almost everytime is success jamming missile)

**Where did the issue occur?**
singleplay in editor,didnt try multiplay yet.

**Log Files:**
[https://docs.google.com/document/d/10p_oKwerpM5LGFAIBsMX_6BtqtMiiySnDHuQJV2ShGA/edit?usp=sharing](url)

**Additional context:**
AI armor vehicle didnt act to javelin(titan) missile, they didnt pop out smoke.
The armor vehicle smoke is also cant jamming TITAN too. in vanilla it can let missile lost target and miss.

**Screenshots:**
Nope

**Comment by alganthe** [comment]
You do not seem to want your issue fixed, closing.

**Comment by IgarashiInaba** [comment]
> You do not seem to want your issue fixed, closing.

wait,what?is that didnt clear enough?

**Comment by Dystopian** [comment]
@IgarashiInaba see #6116

**Comment by alganthe** [comment]
Sorry @IgarashiInaba I skipped past the rest of your comment after seeing the entire unfilled template by habit.

As per the link dystopian gave, we cannot trigger the vanilla missile detection system.

**Comment by IgarashiInaba** [comment]
> @IgarashiInaba see #6116

ok...

**Comment by IgarashiInaba** [comment]
> Sorry @IgarashiInaba I skipped past the rest of your comment after seeing the entire unfilled template by habit.
> 
> As per the link dystopian gave, we cannot trigger the vanilla missile detection system.

it's fine. :)
