### ISSUE TITLE
No check respone status on progress bar

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#716]
ACE3 Version: custom 17.04.2015

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
No

Description:
Try to check response on any AI (Head - Check response), you will see progress bar, but no text on it ("Checking response ..." or something): http://i.imgur.com/agRowTa.png
Probably it should look like: http://i.imgur.com/clOxodb.png

Steps to reproduce:
Try to check response on any AI

Where did the issue occur?
Every time

RPT log file:
No

**Comment by Jastreb** [comment]
Same here, maybe there shouldn't be any? I get notification on the right but no text in progress bar either.

http://www.dodaj.rs/f/1P/13y/3zD6ncrk/arma320150418013707676.png

**Comment by ruPaladin** [comment]
They same problem with:
Check blood pressure
Check pulse

**Comment by Glowbal** [comment]
Should be fixed by  #907
