### ISSUE TITLE
[BUG]Ace Interaction menu; Keep Arrow Centered + Always display cursor for interaction does not take resolution scaling into account

### ISSUE THREAD

**Issue by Nixxen** [acemod/ACE3#7165]
**Mods (complete and add to the following information):**
- **Arma 3: 1.94.145977 (latest Steam release as of 03.09.19)
- **CBA:** `3.12.1 (don't know where to find hash)
- **ACE3:** `3.12.6` community modified version for medical (don't know where to find hash)

**Description:**
When interacting with a player or object using ACE interact, the menu disappears to the top left out of the screen.

**Steps to reproduce:**
- In settings for ACE Interaction menu enable "Keep Arrow Centered" and "Always display cursor for interaction"
- In game graphics setting, set Scale to for instance 125%
- Try to interact with another player and observe the mouse lock lower right compared to center of screen, and the interaction menu disappear off to the top left.

**Expected behavior:**
ACE Interact with something and the menu stays put.

**Where did the issue occur?**
- Dedicated 

**Log Files:**
https://gist.github.com/Nixxen/bde583f0056137543d401f252e66dda4
Log is from a community gamenight warmup with additional addons running. It's the best I could make since I am not very familiar (at all) with editors and uploading maps to servers.
I don't think the log will be helpful for this particular issue though.

**Additional context:**
Disabling either of the arrow related settings or turning the scaling back to 100% will make the issue go away.

**Screenshots:**
Screenshot is not applicable since it's not possible to capture the menu disappearing.

**Comment by commy2** [comment]
Duplicate https://github.com/acemod/ACE3/issues/2414
Duplicate https://github.com/acemod/ACE3/issues/5084
