### ISSUE TITLE
ace_break_line.dll is flagged for containing trojan code.

### ISSUE THREAD

**Issue by bringrainfire** [acemod/ACE3#7177]
**Description:**
When subscribing to on the workshop, or trying to download the dll from this git repo it is blocked.

**Steps to reproduce:**
have immunet (https://www.immunet.com/index) installed.

**Expected behavior:**
When downloading all code is scanned by immunet for threat identification. It should pass and be allowed to download.

**Screenshots:**

![image]https://cdn.discordapp.com/attachments/570114320814571530/621433490323275776/unknown.png

![image](https://user-images.githubusercontent.com/2898231/64731259-6d9a5000-d4a6-11e9-84b6-350f38858dbb.png)

**Comment by bux** [comment]
Feel free to test with https://www.virustotal.com/gui/home
It's a false positive of this immunet

**Comment by dedmen** [comment]
Guess use this to report the false positive to them:
https://www.immunet.com/faq#How_do_I_submit_a_suspicious_file_to_Immunet_

**Comment by bringrainfire** [comment]
sweet, submitting that over now

**Comment by bux** [comment]
I will close this issue now. Please keep us updated nontheless.
