### ISSUE TITLE
MX rifles are not compatible with ACE laser pointers

### ISSUE THREAD

**Issue by taro8** [acemod/ACE3#7182]
ACE (3.12.6)
CBA (3.12.2)
nothing else

All of the MX rifles seem to have improperly configured side rail. They cannot mount ACE laser pointer. When you switch the Laser Module mode using the vanilla laser module that is available to the MX, the module gets completely and permanently deleted off the rifle.
My guess is the script tries to add the attachment with different mode, but since the MX can't mount it the module just gets deleted.

This might be an issue with CBA rails config.

Steps to reproduce: go into arsenal > equip any MX rifle > attach the laser module > test > press the laser module mode switch key > _poof_ the module is gone

**Comment by dedmen** [comment]
Correct, CBA doesn't add the side rail
https://github.com/CBATeam/CBA_A3/blob/6fcd51eb768b0562f6fadf0aadf83a90099c5cf4/addons/jr/CfgWeapons.hpp#L395
