### ISSUE TITLE
Change Tactical Run Animation

### ISSUE THREAD

**Issue by Zumiii** [acemod/ACE3#7184]
I think that the community misses out on some great animations for idle Jogging

I would like to have the following line in CfgMovesMaleSDR from advancedfatigue
file = "\A3\anims_f\Data\Anim\Sdr\Mov\Erc\run\low\Rfl\AmovPercMrunSlowWrflDf";
replaced by:
file = "\A3\anims_f\Data\Anim\Sdr\Mov\Erc\tac\low\Rfl\AmovPercMtacSlowWrflDfl.rtm";

Speed should be adjusted to:
speed = 1.4;

It looks awesome. Thx for considering

**Comment by commy2** [comment]
#3594
