### ISSUE TITLE
ACE Arsenal VR Targets duplicating when killed

### ISSUE THREAD

**Issue by Slatery** [acemod/ACE3#7185]
**Mods :**
- **Arma 3:** 1.94.145977` 
- **CBA:** `CBA_A3 v3.12.2.190909 [workshop release]` 
- **ACE3:** `master branch commit 92b7ba1`
**Description:**
VR Targets in ACE Arsenal duplicate after "respawning"

**Steps to reproduce:**
- Go to ACE Arsenal from main menu
- Kill VR target

**Expected behavior:**
A single VR target appears

**Where did the issue occur?**
- ACE Arsenal

**Log Files:**
RPT - https://pastebin.com/RPqckjX5 note, made a new build of ACE from master branch on 2019/09/21 ACST and placed it into Zakant's nightly build for ease of loading

**Additional context:**
has existed for a few commits now, was apparent in [Zakant's nightly build from 2019/08/09](https://steamcommunity.com/sharedfiles/filedetails/?id=1461430193)

**Screenshots:**
[Video of it occurring made on 2019/09/21 ACST](https://www.youtube.com/watch?v=gRWGfNaraNI&feature=youtu.be)

**Comment by alganthe** [comment]
medical rewrite related @BaerMitUmlaut ?

**Comment by Blutze** [comment]
> medical rewrite related?

Not necessarily. While I've never seen it happening on every single kill with just small arms, its been around pretty much since I started playing ~2.5 years ago. Usually triggers on big explosions.

**Comment by Drofseh** [comment]
It's not new #6772

**Comment by commy2** [comment]
That mission is scripted scheduled, so this is exactly what I would expect.

**Comment by PabstMirror** [comment]
Related to https://github.com/acemod/ACE3/pull/7061
baer had previously mentioned using `objNull`, which I think would fix this issue
but I'm not sure about killed EH order, will investigate
