### ISSUE TITLE
Leaving spectator does not restore HUD elements

### ISSUE THREAD

**Issue by diwako** [acemod/ACE3#7186]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.94`
- **CBA:** `3.12.2`
- **ACE3:** `3.12.6`

**Description:**
When leaving ACE spectator all vanilla HUD elements stay hidden.

**Steps to reproduce:**
- Create mission
- place down player unit and some other units marked as playable
- use these CBA settings
```sqf
// ACE Spect
force ace_spectator_enableAI = false;
force ace_spectator_restrictModes = 1;
force ace_spectator_restrictVisions = 0;
```
- Enter and leave ace spectator
```sqf
[{
    [true] call ace_spectator_fnc_setSpectator;
}, [], 2] call CBA_fnc_waitAndExecute;
[{
    [false] call ace_spectator_fnc_setSpectator;
}, [], 4] call CBA_fnc_waitAndExecute;
```
- Doing this while alive seems to be important to reproduce this issue

**Expected behavior:**
Normally all HUD elements will be restored, in this case those will not

**Where did the issue occur?**
- Dedicated
- Editor (Singleplayer)

**Additional context:**
This happened during an OP of mine, players complained about missing HUD after respawn. Recreated the issue in 3den with steps above.

**Comment by diwako** [comment]
[ace_spectator_bug.VR.zip](https://github.com/acemod/ACE3/files/3639722/ace_spectator_bug.VR.zip)
Mission file

**Comment by zharf** [comment]
Seems like ace_spectator_fnc_cam_setCameraMode hides the HUD and it never gets restored afterwards; doing `[] call ace_common_fnc_showHud;` after `[false] call ace_spectator_fnc_setSpectator;` brings back the HUD, for me at least
