### ISSUE TITLE
Adding an option to the Advanced Throwing system

### ISSUE THREAD

**Issue by Italiandrache** [acemod/ACE3#7187]
It would be nice to have the option to switch the mode in which the advanced throwing system menages where to throw the grenades.
While using the aiming deadzone option cranked up, often, when wanting to throw a grenade using the advanced throwing system, the weapon goes into the line of sight. If the possibility to choose, and maybe even rapidly switch via a combination of keys, between the grenade being thrown where one looks or being thrown where one aims will be added, that issue wouldn't manifest itself anymore.

I don't know if this is the right place to post this, I'm new to this kind of things.

**Comment by Slatery** [comment]
post this over in #3594

**Comment by jonpas** [comment]
Feature request -> #3594 

But to answer you, you can just lower your weapon as well.
