### ISSUE TITLE
How to enumerate available (enabled) load outs

### ISSUE THREAD

**Issue by mwpowellhtx** [acemod/ACE3#7192]
Well, I would [follow the URL to the wiki](https://ace3mod.com/wiki/user/how-to-make-a-feature-request.html), but it ain't there, so...

I see the API to [save/update a loadout](/acemod/ACE3/blob/e2ac18a05d5f646bc7cbc043bcc148fde4c0f5dd/addons/arsenal/functions/fnc_addDefaultLoadout.sqf), but I was wondering that the API might be if I actually wanted to enumerate the load outs I have available?

Parameters might include whether to include public load outs. And return data might include the state of whether the load out was enabled or disabled given the arsenal virtual item list, and the items in the load out.

Upon further review, I see functions to interact with the arsenal UI, that sort of thing, so I suspect that an enumerate feature might be buried in there somewhere just waiting to be exposed.

**Comment by alganthe** [comment]
Personal loadouts are saved in ProfileNamespace, Default loadouts in mission.sqm in a hidden EDEN category and shared loadouts in missionNamespace (shared via CBA EH), all are stored in the order they were added and later sorted alphabetically (different array than the saved one) when the loadout page control is loaded.

There is no bespoke enumerate func but you could copy what is present in ace_arsenal_fnc_fillLoadoutsList.

The wiki page for ace_arsenal APIs is https://ace3mod.com/wiki/framework/arsenal-framework.html

**Comment by mwpowellhtx** [comment]
@alganthe Appreciate the feedback, thanks. Seems kind of [tightly coupled](/acemod/ACE3/blob/e2ac18a05d5f646bc7cbc043bcc148fde4c0f5dd/addons/arsenal/functions/fnc_fillLoadoutsList.sqf) with the UI itself. If I can reasonably decouple an enumerate function, I'll post it back here.

**Comment by mwpowellhtx** [comment]
What is a [`QGVAR(saved_loadouts)`](/acemod/ACE3/blob/e2ac18a05d5f646bc7cbc043bcc148fde4c0f5dd/addons/arsenal/functions/fnc_fillLoadoutsList.sqf#L34)? I assume `COMPONENT` is [arsenal](/acemod/ACE3/blob/e2ac18a05d5f646bc7cbc043bcc148fde4c0f5dd/addons/arsenal/script_component.hpp#L1)? Prefix is what? `ace`? So, if I understand the [`DOUBLES(x,y)`](/acemod/ACE3/blob/2d0c61a8744cbb9ab482e9cf0dedcd142acc6a96/include/x/cba/addons/main/script_macros_common.hpp#L54) macro, that yields `ace_arsenal_saved_loadouts`?

When we have ACE included among our mods, we can just use the `QGVAR(saved_loadouts)` shorthand?

**Comment by synixebrett** [comment]
You can not, macros only work inside the add-on itself, you'll need to use `ace_arsenal_saved_loadouts`

**Comment by synixebrett** [comment]
```sqf
{
  params ["_name", "_data"];

} foreach ace_arsenal_saved_loadouts;
```
This should be all you want, then you can use `setUnitLoadout` with _data for example

**Comment by mwpowellhtx** [comment]
Interesting, let me see if I understand the deconstructed tuple, then...

```SQF
_data params ["_loadout", "_nullItemsAmount", "_unavailableItemsAmount", "_nullItemsList", "_unavailableItemsList"];
```

`_loadout` is the load out itself? We should be able to set that on the `player` or `unit` as the case may be via the usual *Arma 3 API*?

What is a `_nullItemsList`?

I assume `_unavailableItemsList` is actually any items in the load out that are not loaded in with the current mod set? In other words, which would result in a disabled load out in the ACE arsenal screen, for instance?

And the `_*Amount` bits?

Actually, with the *Arma 3* `params` tuple deconstruction, that's even easier to work with than I had expected at first.

Seems fairly straightforward otherwise. Thanks!

**Comment by mwpowellhtx** [comment]
Alright, so I promised to circle around on this, and here I am.

'Hub would not let me upload an `.sqf` file apparently, so here's the text file.

[fnc_ace_arsenals_verifyLoadout.txt](https://github.com/acemod/ACE3/files/3798904/fnc_ace_arsenals_verifyLoadout.txt)

Some noteworthy changes/improvements.

1. First and foremost, decouples from the object. Provide only the `_loadout` in question and the reference `_virtualItems`.

1. Returns only the requested metrics. No need to return the `_loadout` itself, since we assume that the caller already has this in hand.

1. Returned metrics may include a go/no-go metric, and/or counts, and/or detailed. Default is to return simply the go/no-go and the counts.

1. The core functions that facilitates verification are the *tally* functions, *tally null* or *tally unavailable*, given an `_item`, a `_predicate`, and a caller provided `_effect` callback. There also a `_line` for debugging purposes, but technically this is extraneous, except for debugging purposes.

1. Which also has the added benefit, when executed, of dropping the use of cryptically defined macros. Everything you need is right there in front of you, no need to guess what names are there, how brittle the macros are, etc. Fairly self-explanatory.

1. We started off defining private variables for many of the indices, but these could just be local module definitions. Still self-documenting, and no need to refactor to `defines.hpp`, we think.

1. With perhaps a couple of exceptions, the caller pattern simplifies to simply *if item is not null then item may be unavailable*, along these lines.

1. Employs an `if exitWith` pattern in select areas as well.

I pasted in the macros for reference getting started, and subsequently distilled the *tally* functions with caller injected conditions. Also, I started by allowing for condition callback, but eventually decided to just pass in the Boolean condition itself, so that could be further optimized.

Practical usage by `Arsenal API` subscribers would be along the lines of `[_loadout, _virtualItems] call ace_arsenal_verifyLoadout`. That's it. Pretty simple. Here's an example where we transform the saved loadouts for internal usage:

```SQF
private _verified_loadouts = _saved_loadouts apply {
    _x params ["_name", "_loadout"];

    private _verified = [_loadout, _virtual_items] call fnc_ace_arsenals_verifyLoadout;

    // TODO: TBD: with plans to allow for "default loadouts" and "shared loadouts" in the future.
    // i.e. LOADOUT_KIND_DEFAULT, LOADOUT_KIND_SHARED
    [LOADOUT_KIND_PLAYER, DEFAULT_CONTRIBUTOR_NAME] + [_name, _loadout] + _verified;
};
```

Where definitions are:

```SQF
#define LOADOUT_KIND_PLAYER 0
#define LOADOUT_KIND_DEFAULT 1
#define LOADOUT_KIND_SHARED 2

#define DEFAULT_CONTRIBUTOR_NAME ""
```

Internally, we turn around and set these as variables on dialog assets, that sort of thing.

Cheers, happy to help make the `ACE3 Arsenals` framework a little better with this. I do not have the bandwidth to clone the repo and do any PR's myself, but I can at least do this. If someone does merge it in, be sure to give credit where it is due for the lion's share of the adaptation effort.

I may also post a follow up comment, or full fledged issue, recommending decoupling the application of the verified loadouts to the underlying `ListNBox`, that would allow for use in alternate scenarios than the *ACE3 virtual arsenal UI*.

**Comment by mwpowellhtx** [comment]
Also, please excuse the strategic diagnostic logging. Feel free to strip those out and/or adapt to ACE-isms as necessary.

**Comment by commy2** [comment]
Close?

**Comment by mwpowellhtx** [comment]
It's here if someone more intimately familiar with the framework would like to expose this as an API improvement.

**Comment by commy2** [comment]
There are clear rules about this. This is an issue tracker. Bugs go here and anyone has to fill out the template. It is courtesy on our part to not immediately close some first timer's questions without reply.
Feature requests go here: https://github.com/acemod/ACE3/issues/3594.
I don't think anyone familiar with SQF would base anything on what you wrote. It is pretty trash.
All you had to do was to properly communicate what your goal was, and then - maybe - someone competent would've been willing to implemented it.
After 5 weeks I still have no idea what you're trying to accomplish here. My best guess is validating the contents of a loadouts array. As in predicting if the array would be accepted by the game on a unit without any imperfections.
That would've nothing to do with the ACE Arsenal. It would maybe qualify for ACE common or CBA, or some gist that could be brought up in the unlikely case that anyone would need something like that (which hasn't happened in 5 years).
I see no reason to keep this issue open, so I'll close it.

**Comment by mwpowellhtx** [comment]
@commy2 You read nothing whatsoever and comprehended even less.

**Comment by mwpowellhtx** [comment]
@commy2 Deleted my contribution since clearly y'all don't know how to use Github, let alone its issue tracker. Good luck comrade!
