### ISSUE TITLE
How to add/remove hierarchical menus

### ISSUE THREAD

**Issue by mwpowellhtx** [acemod/ACE3#7193]
Hello, if we wanted to add or remove hierarchical menus, how would we go about doing that exactly? Let's say self interaction, I want to add an "Fancypants Actions" item, and in their I wanted to add "Bellbottoms Action".

How to [create an action](https://ace3mod.com/wiki/framework/interactionMenu-framework.html#31-fnc_createaction) and how to [add an action](https://ace3mod.com/wiki/framework/interactionMenu-framework.html#33-fnc_addactiontoobject) is documented.

But, when it came time to remove the action, I need an *action path*? What is that exactly? Also, presumably invoking `ace_interact_menu_fnc_removeActionFromObject`?

**Comment by mwpowellhtx** [comment]
I'm sort of getting the hang of it, sifting through the ACE pattern of class names, etc. I have a question, how do I signal to the action whether it should be visible to whom? In particular, I only want the player himself to be able to see it. Scenario in mind, player has a group of AI, I want to add ACE menus to the AI that only the player can see. This is a function of `condition`? What are the parameters that `condition` takes?

**Comment by mwpowellhtx** [comment]
I am trying to remove a hierarchical menu from a unit. I can add them in okay, but removing is not working.

```SQF
[_x, 0, ["ACE_MainActions", "ACE_TeamManagement", "Loadout"]] call ace_interact_menu_fnc_removeActionFromObject; 
```

Where `_x` is the unit object, and I have the menu in the `Interactions >> Team Management >> Loadout` menu.

**Comment by mwpowellhtx** [comment]
I think I am sort it out, the tricky part for me is knowing the *action type* as compared or contrasted to the menu path. Especially whether we are talking about a `"ACE_SelfActions"` or a `"ACE_MainActions"`. In my specific case, I was looking for type `0` (other) and `["ACE_MainActions", "ACE_TeamManagement"]`, on unit members in my team. Then combined with a *condition* which allowed only the team leader access.

Behind that is I want to generated a dynamic menu behind that one. Not sure yet quite how to manage that aspect. Specifically, for each unit, I want to interact them, and share one of my saved load outs with them. The list of load outs may change from interaction to interaction.

**Comment by Drofseh** [comment]
Hey @mwpowellhtx, this is an issue tracker, not a help service.
If you have questions I strongly recommend joining the Ace3 Slack and asking there.
http://slackin.ace3mod.com/

**Comment by mwpowellhtx** [comment]
Wasn't aware until now. Thanks I appreciate that.
