### ISSUE TITLE
Listing of available icons and their paths

### ISSUE THREAD

**Issue by mwpowellhtx** [acemod/ACE3#7194]
Hello, I am looking for a comprehensive listing of available icons and their paths. Or do I just search the code base for things like `.png` or `.jpg`? Thanks!

**Comment by dedmen** [comment]
As you were told literally 3 minutes before you created this issue:
> this is an issue tracker, not a help service.
> If you have questions I strongly recommend joining the Ace3 Slack and asking there.
> http://slackin.ace3mod.com/
