### ISSUE TITLE
Get CBA PFH working natively on the briefing screen

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#72]
PFH don't work on the briefing screen because they depend on the onDraw event of a CfgTitle shown with cutRsc, and cutRsc doesn't work on the briefing screen.

Having PFH working there would be usefull, at least to keep the coding style consistent; if not we need a bunch of spawns for certain things.

We checked the latest cba code and added a hack in ace_common that solves this by ticking the PFH with an onEachFrame event during the briefing:

97ee63a3494734b6c9e546550ebf2d42e9dd60b2

However, something like this could be landed directly on CBA.

**Comment by jaynus** [comment]
This is expanded and actually should be possible all the way from game start. Need to work on this.

**Comment by ViperMaul** [comment]
@commy2 your request is noted.

**Comment by jaynus** [comment]
This is implemented in CBA.
