### ISSUE TITLE
Investigate lack of wounding and damage caused by some sources

### ISSUE THREAD

**Issue by kymckay** [acemod/ACE3#7203]
Task from our last meeting. Some damage events in medical don't seem to cause any/as much damage as they should. Hasn't been tested in depth so confirmation should be sought to check if these behaviours are consistent.

As this issue is also present in existing medical, it's not super important to get it fixed before the rewrite release (although that would be nice if someone wants to do it).

I know that the Shack Tac guys were looking at helicopter crashes last time we spoke (some time ago). May be something to follow up on.

- Weird damage events reported
  - Vehicle crashes/explosions (helicopter/plane) not causing damage to all
  - Jumping off high tower only causing brief unconsciousness

**Comment by SilentSpike** [comment]
Some of the discussion on this old PR of mine (the code for environmental damage detection is all the same still) pertains to this:
https://github.com/acemod/ACE3/pull/6515#discussion_r209906605
https://github.com/acemod/ACE3/pull/6515#issuecomment-412961912

**Comment by SilentSpike** [comment]
Vehicle crashes: #7305

**Comment by kymckay** [comment]
This may be partially alleviated with https://github.com/acemod/ACE3/commit/73a7dbdc1ed90d3bbb41d453817263f99fc247b0

A follow up PR for vehicle explosion handling (deemed out of scope for the PR) may resolve this issue.

**Comment by LinkIsGrim** [comment]
Should have been handled by #9246. Are there any other damage sources not causing wounds?

**Comment by kymckay** [comment]
Good flag, this can now (finally) be closed! :tada:

**Comment by LinkIsGrim** [comment]
One down, 73 to go.
