### ISSUE TITLE
Add a setting to disable the ACE medical system

### ISSUE THREAD

**Issue by kymckay** [acemod/ACE3#7204]
Task we discussed at our last meeting. This is a long requested option which we think may be possible to implement with the changes that have now been made to medical.

We just need to take care about other components/external mods which may be checking for the presence of medical or using unit variables not guaranteed to be present if medical is disabled.

Ideally we would want to implement this before the release of the rewrite since it could be a breaking change for external addons (and we want to try and keep all breaking changes to the rewrite release).

My bullet notes on this from the meeting:
- Setting to disable medical
  - Initially thought that it may be impossible because we have to change item types here which would stop them functioning in the vanilla system https://github.com/acemod/ACE3/blob/a53a2725e9bd07551f0180c8dcc78af2b93e251f/addons/medical_engine/CfgWeapons.hpp#L2-L11
  - However, we think we don't actually need this config change anymore. We don't care about hiding items from arsenal and as for AI healing themselves...
  - Use healing event handler to prevent vanilla healing when medical is active (even if it were to occur we don't think it would be a big issue)
  - Need to remember to change other components which are loking for `(["ACE_Medical"] call EFUNC(common,isModLoaded))`
  - See if some 3rd party mods are also checking for the presence of medical
  - Check for places where unit variables are being accessed in other components and ensure it's being done safely for the case when medical isn't running
- If medical is disabled then:
  - Damage handling shouldn't ever be added
  - Statemachine shouldn't run
  - Treatment actions shouldn't be added
  - Item replacement shouldn't occur

**Comment by soryy708** [comment]
> Ideally we would want to implement this before the release of the rewrite
Apparently it wasn't?

**Comment by jonpas** [comment]
It was not.

**Comment by igorpc1** [comment]
Is it still work in progress or abandoned?

**Comment by kymckay** [comment]
@igorpc1 The issue is still open so it hasn't necessarily been ruled out, but nobody has felt strongly enough to pursue it. We may need to revaluate the idea as it could be quite a disruptive change and context has now changed, but I'd say it currently falls under "if you want it, do it"

The caveat with this one is it hasn't been proven 100% feasible yet (we just thought so at the time of creation)

**Comment by juks01** [comment]
When searching for this option I found out that it could be done by deleting medical related pbo's. Well I definetely don't want to make it work that way so I was wondering could this be done simply by using some if -sentenced in every/some of those script files inside medical pbo's?

**Comment by commy2** [comment]
No.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
