### ISSUE TITLE
Implement incoming damage normalization

### ISSUE THREAD

**Issue by SilentSpike** [acemod/ACE3#7205]
A task discussed at our last meeting. The background is that we're pretty certain each body part receives differently scaled damage (by the engine) from identical incoming damage events.

The basic idea is to normalise these values onto the same scale for comparison and so that wound damage is consistent (we perform comparison between the damage to each body part to decide where a wound is applied for example).

If implemented this should be heavily tested to see the results produced by different damage sources compared to the current behaviour. Ideally they should remain roughly the same if not make more sense (wound size, etc.). As such, this task doesn't have to happen before the release of the rewrite.

Baer came up with these scaling values (divisors) for damage:
```
hithead: 1
hitbody: 1.00001
hitarms: 0.0540424
hitlegs: 0.333338
```
using the following code
```sqf
fn_test = {
    params ["_mempoint", "_hitpoint"];
    private _target = "B_Soldier_F" createVehicle position player;
    _target setUnitLoadout getUnitLoadout (configFile >> "EmptyLoadout");
    private _mempointPos = _target modelToWorldVisualWorld (_target selectionPosition _mempoint);
    private _rayOrigin = _mempointPos vectorAdd [0, -1, 0];
    private _intersects = lineIntersectsSurfaces [_rayOrigin, _mempointPos, objNull, objNull, true, 1, "FIRE"];
    private _intersectPos = _intersects#0#0;
    if (_intersects isEqualTo []) exitWith {
        systemChat ("No intersection with " + _mempoint);
    };
    [{
        params ["_intersectPos"];
        private _bullet = "B_556x45_Ball" createVehicle [0, 0, 10];
        _bullet setPosASL (_intersectPos vectorAdd [0, 0, 0]);
        _bullet setVelocity [0, 100, 0];
    }, [_intersectPos], 1] call CBA_fnc_waitAndExecute;
    [{
        params ["_hitpoint", "_target"];
        diag_log formatText ["%1: %2", _hitpoint, (_target getHitPointDamage _hitpoint) / 0.489123];
        systemChat format ["%1: %2", _hitpoint, (_target getHitPointDamage _hitpoint) / 0.489123];
        deleteVehicle _target;
    }, [_hitpoint, _target], 2] call CBA_fnc_waitAndExecute;
};
diag_log text "-------------------";
{
    [fn_test, _x, 3 * _forEachIndex] call CBA_fnc_waitAndExecute;
} forEach [
    ["pilot", "hithead"],
    ["pelvis", "hitbody"],
    ["relbow", "hitarms"],
    ["rknee", "hitlegs"]
];
```

Some notes:
  - Damage can be scaled as early as possible within the damage handler here (values will then pass through to wounding): https://github.com/acemod/ACE3/blob/a53a2725e9bd07551f0180c8dcc78af2b93e251f/addons/medical_engine/functions/fnc_handleDamage.sqf#L73-L80
  - Should allow using a single value for worst wounding here: https://github.com/acemod/ACE3/blob/a53a2725e9bd07551f0180c8dcc78af2b93e251f/addons/medical_damage/functions/fnc_woundsHandlerSQF.sqf#L98
  - May allow us to remove the head prioritisation code in the damage handler: https://github.com/acemod/ACE3/blob/a53a2725e9bd07551f0180c8dcc78af2b93e251f/addons/medical_engine/functions/fnc_handleDamage.sqf#L85-L89

**Comment by PabstMirror** [comment]
With high armor vests, damage that should go to body will often be put on arms, 
making it difficult to kill units.
![unknown](https://user-images.githubusercontent.com/9376747/67248866-59ddf400-f42b-11e9-84fd-31a0305ac59a.jpg)

**Comment by SilentSpike** [comment]
This may actually be due to the effects of over penetration (i.e. round penetrates all the way through arm so less damage is dumped if the arm is hit) - which might also explain why shooting a unit directly with a tank shell can result in surprisingly small damage (because it penetrates through).

Relevant quote from https://community.bistudio.com/wiki/Arma_3_Damage_Description: 
>the projectile completely penetrates the FG. Only a portion of the directDamage of the projectile will be dealt to the Hitpoint. The portion of damage depends on the amount of speed the projectile lost during penetration. The formula for this is unknown and also seems to be nonlinear. This means that very thin firegeometry will cause low amount of damage in most cases (as many projectiles will fully penetrate).

Not really sure how we can account for this system when damage is unexpectedly low.

**Comment by jonpas** [comment]
Is this still relevant?

**Comment by commy2** [comment]
ref  #7415  will solve this

**Comment by SilentSpike** [comment]
See my latest comment, this ticket was opened (I believe) after misunderstanding why we were seeing seemingly differently scaled damage to different hitpoints. I think it's due to the pass through system. Not sure there's really anything we can do about it.

**Comment by commy2** [comment]
passThrough means, if a hit increases damage on a selection from a to b (delta = b - a), then delta * passThrough is added to structural damage of the unit.

**Comment by commy2** [comment]
Structural damage is not a thing in ACE Medical, so passThrough does not matter.

**Comment by SilentSpike** [comment]
@commy That's my mistake then, I meant to say over penetration. See quote and link in https://github.com/acemod/ACE3/issues/7205#issuecomment-581671847

So if the same projectile hits two different bodyparts with different geometry you can see significantly different damage values (which directly influences the wound received) due to projectile losing different amounts of speed (think this may also be tied to why higher calibre projectiles can result in very little wounding when in reality they would probably give you a bigger wound, e.g. direct hit with an APC cannon round just goes straight through you and loses little speed). Currently the woundHandler scales damage differently per bodypart which was an empirical effort to account for this without understanding why it was happening.
