### ISSUE TITLE
Interaction problem

### ISSUE THREAD

**Issue by Wolfy1129** [acemod/ACE3#722]
![2015-04-17_00001](https://cloud.githubusercontent.com/assets/11918682/7212134/e45d6a98-e530-11e4-9bb9-9e1f67ada032.jpg)

I hold my left windows key to bring up the interaction menu but then a second later the name of person, Examine, and Exit Menu get in the way and I can't perform medical until I exit the menu which then makes it normal like I never interacted with the player/AI. Any ideas? Also, can someone tell me what self interaction button is? I tried App Menu key but no luck /: Thanks in advance! ^_^)

**Comment by PabstMirror** [comment]
Looks like another mod/mission is using the same key.
Make sure to try just cba and ace and try a vanilla mission.

**Comment by PabstMirror** [comment]
Also please review http://ace3mod.com/wiki/user/how-to-report-an-issue.html
