### ISSUE TITLE
Battleye blocking ace

### ISSUE THREAD

**Issue by Bo0g1eMaN** [acemod/ACE3#7222]
**Mods (CBA_A3, ace):**
Arma, CBA, and ACE are all on the most up to date versions as of writing

**Description:**
Battleye is blocking ace for an unknown reason

**Steps to reproduce:**
Just starting up the game and getting to the main menu will show abunch of battleye logs 

**Expected behavior:**
Battleye to block ace

**Where did the issue occur?**
Main menu/arma launcher
**Log Files:**
there is no logs other than the battleye log which will be included in the screenshot
**Additional context:**
Spoke to battleye and was told "It should be whitelisted by our system.

These issues can be caused by corrupted files (in which case I'd suggest a reinstall of the software) or by your Internet connection, which causes BE to be unable to check these whitelisted files.

Please make sure that BEService.exe in your BE Service directory (usually “C:\Program Files (x86)\Common Files\BattlEye”) is not blocked by your firewall in any way and try to update your network drivers, check your modem/router or contact your ISP for help."
I've tried reinstalling the whole game and unsubscribing from all addons as well as turning off firewall and av, I also tried everything battleye said to do.

**Screenshots:**
![image](https://user-images.githubusercontent.com/51394308/66096142-dbd6ad80-e54e-11e9-973f-c2cb4aa75e76.png)

**Comment by dedmen** [comment]
Battleye's fault, it just randomly starts blocking files. Not our fault and nothing we can do about that.

> Additional context

wtf?
Is that just a copy-paste from https://obsproject.com/forum/threads/win10-x64-creators-update-and-playerunknowns-battlegrounds-blocked-battleye.66872/
?

Can be closed, not our fault. Just wait till BE unfucks itself.

**Comment by Bo0g1eMaN** [comment]
It's not randomly doing it it's been blocking ace for over a month, and I guess so it is a copy and paste.
