### ISSUE TITLE
CBA 3.9.0?

### ISSUE THREAD

**Issue by JordannDev** [acemod/ACE3#7226]
Hi guys,

I just had a question, where can I find CBA version 3.9.0? I literally cannot find it anywhere, I'm pretty sure I have the latest version so I'm wondering how I can find CBA 3.9.0?

Here is the output from the server:
```
[ACE] (common) INFO: ACE is version 3.12.6.43.
[ACE] (common) INFO: CBA is version 3.12.2.190909 (min required 3.9.0)
```

Server Information:
```
Distro: Centos 7
ACE Version: 3.12.6.43
CBA Version: 3.12.2
Arma 3 Version: Latest (literally installed last night)
```

Spent a good chunk of time trying to debug it (seeing as you know, Arma3 Server with mods like shit on Linux). 

Any help is greatly appreciated.

**Comment by jonpas** [comment]
> **min**

It means "minimal". You are seeing "INFO" logs, no error or warning, you are fine.

**Comment by commy2** [comment]
That just tells you that ACE 3.12.6.43 requires CBA 3.9.0 or newer, and you have CBA 3.12.2.190909.
Not a bug just log.

**Comment by PabstMirror** [comment]
3.12.2 is higher than 3.9.0
It might look strange if you aren't used to it, but that's how versioning numbers work

**Comment by JordannDev** [comment]
I see now. Thanks. Yeah I thought 3.9 was like 90, not literally 9. 

Thanks.
