### ISSUE TITLE
LOW DLC The Guerrilla broken ACE 

### ISSUE THREAD

**Issue by Bluscream** [acemod/ACE3#7229]
**Mods (complete and add to the following information):**
- **Arma 3:** `any` 
- **CBA:** `any` 
- **ACE3:** `any` 

**Description:**
- The mission doesn't detect mines placed with ACE as placed and therefor doesn't advance at a certain point

**Steps to reproduce:**
- Start the mission
- Continue until you're told to place the mines
- Place a mine

**Expected behavior:**
The narrator keeps talking and the story advances

[![](http://img.youtube.com/vi/AOUN-NozPkg/0.jpg)](http://www.youtube.com/watch?v=AOUN-NozPkg?t=472)

**Where did the issue occur?**
- Single player

**Log Files:**
- Provided when necessary

**Additional context:**
N/A

**Screenshots:**
N/A

**Comment by alganthe** [comment]
ACE is not meant to be compatible with official single player scenarios.

**Comment by Bluscream** [comment]
Why is that?

**Comment by Bluscream** [comment]
@alganthe you even provide a "Singleplayer" option in the issue template...

**Comment by alganthe** [comment]
> Why is that?

Because that would require modifying every single scenario made by bohemia interactive to make them compatible with our features.

**Comment by Bluscream** [comment]
> Because that would require modifying every single scenario made by bohemia interactive to make them compatible with our features.

Couldn't you do something like "fire the BI `mine placed` event" when a detonator is assigned with ACE?

**Comment by commy2** [comment]
No, we can't.
