### ISSUE TITLE
Self packed ace pbo ends mission, because it is outdated

### ISSUE THREAD

**Issue by Tomcat-SG** [acemod/ACE3#7230]
- **Arma 3:** `1.94` 
- ACE is version 3.12.6.43.
- CBA is version 3.11.1.190503 (min required 3.9.0)

**Description:**
I edited an if statement in the disarming mod and want to pack it with pboProject. I can pack it but if i will test it in the editor it say, that the pbo is outdated

**Steps to reproduce:**
- repack the pbo from git source

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Log Files/Error:**
13:47:46 [ACE] (common) ERROR: File ace_disarming.pbo is outdated. z\ace\addons\common\functions\fnc_checkFiles.sqf:50

The changed file and the rpt are uploaded here.
[Arma3_x64_2019-10-06_14-24-19.txt](https://github.com/acemod/ACE3/files/3694459/Arma3_x64_2019-10-06_14-24-19.txt)

[fnc_showItemsInListbox.zip](https://github.com/acemod/ACE3/files/3694461/fnc_showItemsInListbox.zip)

**Comment by bux** [comment]
Sorry, we can't offer support for custom versions.

**Comment by PabstMirror** [comment]
ace is really meant to be built together
the problem is because the `versionStr` in cfgPatches is different from the one in ace_main.pbo
make sure it's not relying on a macro that doesn't exist

**Comment by jonpas** [comment]
You must use the same version of CBA it was used for other PBOs. It is recommended to rebuild in full (all PBOs) for custom versions.
