### ISSUE TITLE
AF: Bar visible in Cutscenes etc.

### ISSUE THREAD

**Issue by Blutze** [acemod/ACE3#7241]
**Mods:**
- **Arma 3:** `1.94 stable`
- **CBA:** `3.12.2 stable`
- **ACE3:** `3.12.6 stable` as well as the dev environment for #6911

**Description:**
If the transparency of the Advanced Fatigue bar is less than 100%, either because fade is turned off or simply because you are not on full stamina, it is visible in cutscenes and fade-to-black sequences, such as during the campaign.

**Steps to reproduce with FADE OFF:**
- Start mission "Common Denominator" in the prologue campaign.
- There is a bright white stamina bar floating in the top "cinematic bar", even though the rest of the UI is hidden.

**Steps to reproduce with FADE ON:**
- Play through mission "Diplomatic Relations", until just before you arrive at the "incident" compound.
- Change Performance & Recovery to 0, and Load Factor & Terrain Factor to 5.
- Stop the vehicle ASAP, get out, and sprint around.
- There is a bright red, almost empty, stamina bar floating in the top "cinematic bar", even though the rest of the UI is hidden.

**Expected behavior:**
Stamina bar to be hidden with all the other normal UI parts.
Is there something like a z-index to put the bar behind these overlays? Otherwise, maybe an eventhandler or a check in `fnc_handleStaminaBar` to uncreate or set `ctrlFade = 1`.

**Where did the issue occur?**
- Singleplayer

**Log Files:**
- Report file from FADE ON with 3.12.6 stable: https://gist.github.com/Blutze/423b6f5e449bd3d07848b7424c61bf6a

**Additional context:**
While the solid stamina project is probably going to make this problem more noticable, as the... "accidental workaround" of just being on full stamina for a full fade doesn't apply anymore, this is kinda out of scope of my project, and honestly I wouldn't even know where to start fixing this.

**Screenshots:**
FADE OFF, dev environment:
![image](https://user-images.githubusercontent.com/37950828/66712751-995c6e80-eda1-11e9-8d13-b55851d36481.png)

FADE ON, stable:
![image](https://user-images.githubusercontent.com/37950828/66712746-8a75bc00-eda1-11e9-8a7c-84cfef61328c.png)

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
