### ISSUE TITLE
addons ace balictic not found 

### ISSUE THREAD

**Issue by jura1cz** [acemod/ACE3#7242]
How do I solve a problem with arma 3 mod ace 3 when ace 3 balistic not found still pops up?

**Comment by commy2** [comment]
Install again.

**Comment by severgun** [comment]
why issuers assign labels?

**Comment by jonpas** [comment]
> why issuers assign labels?

Issue templates. It is automatic and intentional.

**Comment by commy2** [comment]
Close?
