### ISSUE TITLE
RHS Compat. Stryker doesn't have repair points for turret and optics.

### ISSUE THREAD

**Issue by severgun** [acemod/ACE3#7245]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.94` stable
- **CBA:** `3.12.2` stable
- **ACE3:** `3.12.6` stable

**Description:**
RHS Strykers does not have some repair points. For example turret and optics.
Maybe something else.

**Steps to reproduce:**
- Place `rhsusf_stryker_m1126_m2_wd`
- Place engineer with repair kit
- `stryker setHitPointDamage ["hitturret",1];`
- Try to find repair point

- Try `[] execVM "\z\ace\addons\repair\dev\draw_showRepairInfo.sqf";`

![20191020140436_1](https://user-images.githubusercontent.com/1197314/67158764-dd70e580-f344-11e9-94a1-2cf725254fb9.jpg)

**Comment by Blutze** [comment]
![image](https://user-images.githubusercontent.com/37950828/67808808-a5ca1200-fa97-11e9-9815-9b8cd91b1ba3.png)
How on earth they managed that is beyond me, but I'd guess it is why these don't show up in the selection part of `getAllHitPointsDamage`.

**Comment by severgun** [comment]
> That is defo a bug that RHS team should care about. Thats definitely wrong :D 

I did same ticket on RHS bug tracker. It was closed almost immediately "Changes not required" 🤦‍♂

**Comment by topden** [comment]
many other mods, not only rhs, do not have repair points when playing with ace3. Tell me, authors, please, what should the hit points in the config be called correctly so that the ace shows them in the game? Please give a sample hitpoint text in full. We will remake these mods ourselves

**Comment by severgun** [comment]
Just check hitpoints config on vehicles with working repair points.

rhs bmp
```
class HitHull: HitHull
				{
					armor = 0.4;
					material = -1;
					**name = "telo";**
					visual = "zbytek";
					passThrough = 0;
					minimalHit = 0.54;
					explosionShielding = 0.15;
					radius = 0.15;
				};
				class HitEngine: HitEngine
				{
					material = -1;
					**name = "motor";**
					visual = "zbytek";
					passThrough = 0;
					minimalHit = 0.139;
					explosionShielding = 0.009;
					class DestructionEffects
					{
						ammoExplosionEffect = "";
						class RHS_Engine_Smoke
						{
							simulation = "particles";
							type = "SmallWreckSmoke";
							position = "vyfuk start";
							intensity = 0.5;
							interval = 1;
							lifeTime = 60;
						};
						class RHS_Engine_Fire: RHS_Engine_Smoke
						{
							type = "SmallFireFPlace";
						};
						class RHS_Engine_Sparks: RHS_Engine_Smoke
						{
							type = "FireSparks";
						};
						class RHS_Engine_Sounds: RHS_Engine_Smoke
						{
							simulation = "sound";
							type = "Fire";
						};
					};
					armor = 0.5;
					radius = 0.15;
				};
				class HitLTrack: HitLTrack
				{
					armor = -150;
					material = -1;
					**name = "pas_L";**
					passThrough = 0;
					minimalHit = -0.25;
					explosionShielding = 0.15;
					radius = 0.3;
				};
				class HitRTrack: HitRTrack
				{
					armor = -150;
					material = -1;
					**name = "pas_P";**
					passThrough = 0;
					minimalHit = -0.25;
					explosionShielding = 0.15;
					radius = 0.3;
				};
				class HitFuel
				{
					armor = 1;
					explosionShielding = 1;
					material = -1;
					passThrough = 1;
					**name = "palivo";**
					visual = "-";
					radius = 0.11;
				};
```

**Comment by topden** [comment]
thx

**Comment by PabstMirror** [comment]
Just for ref, turrets have their own `class hitpoints`
it get's messy when the gunner and commander turrets both use the same hitpoint name like "HitTurret"
this was standard for a long time in arma, I think with tanks/jets dlc they started to change and there is now a Vanilla Warning: `Duplicate HitPoint name 'HitTurretCom' in 'rhsgref_cdf_b_2s1'`
(could maybe determine turret config based on _forEachIndex in getAllHitpoint)

the strykers conig for example:
```
class Turrets: Turrets {
    class MainTurret: MainTurret {
        class Hitpoints {
            class HitTurret {
                name = "";
                armorComponent = "Hit_Turret"
```
Repair had filtered hitpoints with no selection, but that hitpoint is valid (it does take damage)

I tried adding all hitpoints with valid armorComponents, but got all kinds of weird stuff like wheels that don't exist. I think for now it's best to just add the turrets that couldn't be repaired.

Will track optics issue in #7290
