### ISSUE TITLE
Headless clients can be interacted with

### ISSUE THREAD

**Issue by synixebrett** [acemod/ACE3#7248]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.94`
- **CBA:** `3.12.2`
- **ACE3:** `3.12.6`
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
Headless clients are able to be interacted with

**Steps to reproduce:**
- Go to headless client
- Interact with it

**Expected behavior:**
The headless client should not be interact-able

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**Screenshots:**
![image](https://user-images.githubusercontent.com/3946739/67620616-10442f00-f7c6-11e9-830f-f1149f482c25.png)

**Comment by commy2** [comment]
Classname?

**Comment by synixebrett** [comment]
`HeadlessClient_F`
