### ISSUE TITLE
Nightvision on 4k screens

### ISSUE THREAD

**Issue by shukari** [acemod/ACE3#7249]
**Mods (complete and add to the following information):**
- **Arma 3:** stable
- **CBA:** stable
- **ACE3:** stable

**Description:**
on a 4k ultra-wide screen the view area of NVs is very small... is there a solution?
![image](https://tacticalbacon.de/gallery/userImages/47/283-47a9f301-large.jpg)

**Steps to reproduce:**
- use a NV on a 4k ultra-wide screen

**Expected behavior:**
a littlebit bigger view area ^^

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by Drofseh** [comment]
lol, honestly if anything that's more realistic!

**Comment by severgun** [comment]
1) that is not about resolution. Regular 4k looks OK.
2) use vanilla NV

**Comment by jonpas** [comment]
Vanilla already gives that advantage, that's a moot point.

**Comment by shukari** [comment]
Thank you for telling me what I know.
I wanted to help and report a problem that is on the Ace3 NV but not the vanilla NV.

**Comment by commy2** [comment]
wtf?
