### ISSUE TITLE
Fast Roping Stuck on Rope

### ISSUE THREAD

**Issue by tristanxh** [acemod/ACE3#7250]
**Mods:**
- **Arma 3:** Stable
- **CBA:** Stable
- **ACE3:** Stable
- **RHS:** Stable
- **CUP Terrains:** Stable

**Description:**
Fast roping, approximately one in ten people get stuck on the FRIES system and won't come down until ropes are cut at which point they fall to their death. At least one of them has reported that on his screen he went all the way down to the ground and then it teleported him back up to the top of the rope and started spinning.

**Steps to reproduce:**
- Be on a multiplayer server
- Get in a helicopter with a dozen other players.
- Start flying
- Set up ACE 3 fast roping system
- Tell them to fast rope
- Watch as one gets stuck at the top of the rope.

**Expected behavior:**
People shouldn't get stuck at the top of the rope.

**Where did the issue occur?**
- Dedicated Server

**Additional context:**
We were using the fast roping system where you needed a rope on you.

**Screenshots:**
https://www.youtube.com/watch?v=ZnYJEoD02Yk

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
