### ISSUE TITLE
Cook off broken

### ISSUE THREAD

**Issue by emilnoren** [acemod/ACE3#7264]
Vehicles with the risk to cook off always cook off when destroyed, ignoring the probability coefficient completely. Unless it's set to 0, then no cook offs happen.
This ruins a good module, since 4-5 simultaneous cook offs get pretty damn annoying.

I am only using CBA and ACE3.

**Comment by dedmen** [comment]
Invalid report, please fill out the issue template correctly.

**Comment by severgun** [comment]
It is also known and duplicate.
https://github.com/acemod/ACE3/pull/6264 and others mentioned inside it.

Probability coefficient correct by code. But every hit generate multiple(unpredictable) ammount of HandleDamage events. Each event start "blowup lottery" and obviously one or more of them "win".

Hope in Arma 4 there would be "ammo" hit box required mandatory for some vehicle classes.
