### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by SpartanD39** [acemod/ACE3#7266]
The following page provides seems to provide inaccurate instructions to enable/disable ammunition cook off:
[Cook Off Framework](https://ace3mod.com/wiki/framework/cookoff-framework.html)

As an example, the following is suggested to disable cook off dynamically:
`VEHICLE setVariable ["ace_cookoff_enable", false, true];`

On testing in-editor, the affected object still cooks off when destroyed. Using 'allVariables' on that object shows there is no variable ace_cookoff_enable available. On disabling the 3DEN object attribute for ACE cook off and utilizing 'allVariables' the following variable is set with a value of false:

`ace_cookoff_enableammocookoff`

It should be noted that if ACE cook off is enabled in the 3DEN object attributes, there does not appear to be a related variable set on the object per 'allVariables':

Cook off disabled in 3DEN attributes:

`["ace_dragging_candrag","cba_xeh_incomingmissile","ace_cookoff_enableammocookoff","cba_xeh_getin","ace_dragging_carryposition","cba_xeh_local","cba_xeh_isprocessed","cba_xeh_init","cba_xeh_fired","cba_xeh_initpost","ace_dragging_dragposition","cba_xeh_engine","cba_xeh_respawn","ace_dragging_dragdirection","ace_dragging_cancarry","cba_xeh_killed","ace_dragging_carrydirection","cba_xeh_getout","cba_xeh_isinitialized","ace_dragging_ignoreweightdrag","ace_dragging_ignoreweightcarry"]`

Cook off enabled in 3DEN attributes:

`["ace_dragging_candrag","cba_xeh_incomingmissile","cba_xeh_getin","ace_dragging_carryposition","cba_xeh_local","cba_xeh_isprocessed","cba_xeh_init","cba_xeh_fired","cba_xeh_initpost","ace_dragging_dragposition","cba_xeh_engine","cba_xeh_respawn","ace_dragging_dragdirection","ace_dragging_cancarry","cba_xeh_killed","ace_dragging_carrydirection","cba_xeh_getout","cba_xeh_isinitialized","ace_dragging_ignoreweightdrag","ace_dragging_ignoreweightcarry"]`

Using the following will disable cook off in scripts:
`VEHICLE setVariable ["ace_cookoff_enableammocookoff", false, true];`

Using the following will enable cook off in scripts:
`VEHICLE setVariable ["ace_cookoff_enableammocookoff", nil, true];`

**Comment by commy2** [comment]
>Using 'allVariables' on that object shows there is no variable ace_cookoff_enable available.

Irrelevant. Variable can still be read with default return.

I agree that `ace_cookoff_enable` should be changed to `ace_cookoff_enableAmmoCookoff` in the doc.

**Comment by SpartanD39** [comment]
> > VEHICLE setVariable ["ace_cookoff_enableammocookoff", nil, true];
> 
> Should be false, not nil.

Apologies if I miscommunicated that point. That variable is set to nil to remove it, since that variable doesn't exist on an object with cook off enabled if you check 'allVariables', simplest way of making something work is copying how it is by default after all. As you mentioned that's defined somewhere else as true by default so it's moot, but it works. The below is tested as a working methods to set cook off states in scripts:

Disable cook-off:
`VEHICLE setVariable ["ace_cookoff_enableammocookoff", false, true];`

Enable cook off:
`VEHICLE setVariable ["ace_cookoff_enableammocookoff", true, true];`

Thank you.

**Comment by jonpas** [comment]
Please make those changes in a form of pull request. You can find the files [here](https://github.com/acemod/ACE3/tree/master/docs/wiki). Thanks!
