### ISSUE TITLE
windSimulation too loud

### ISSUE THREAD

**Issue by LAxemann** [acemod/ACE3#7269]
**Mods (complete and add to the following information):**
- **Arma 3:** `
- **CBA:** `3.12.2`
- **ACE3:** `3.12.6`
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
It seems as if ACE either adds new wind sounds or uses existing A3 wind sounds in order to give more audible feedback for weather. As an audio guy, I like the idea but noticed that the wind sounds are way too loud and tend to drown the soundscape, making even gunshots sound less powerful and quiet due to the increased "wind" noise floor.

**Steps to reproduce:**
Open the editor, place a unit, preview.

**Expected behavior:**
I expect a reasonable-volumed wind sound.

**Where did the issue occur?**
- Anywhere in-game

**Comment by commy2** [comment]
There are no wind sounds in ACE.

**Comment by LAxemann** [comment]
> 
> 
> There are no wind sounds in ACE.

Then some changes to the weather/wind settings force wind sounds to play in a weird way. It's 100% reproducable, a large difference between starting up a clean mission with and without ACE.

**Comment by dedmen** [comment]
> Open the editor, place a unit, preview.
Maybe ACE weather just causes the standard weather to have wind going on, while vanilla direct editor preview does not.

**Comment by commy2** [comment]
Disable wind synchronization in ACE weather settings?

**Comment by LAxemann** [comment]
> 
> 
> Disable wind synchronization in ACE weather settings?

Disabling ace_weather_windSimulation "fixes" the issue for me. Might still be worth looking into what causes the wind to play this heavily. Aslo noticed that, for some reason, enabling the option causes the "high altitude" wind sounds to play at ground level.

**Comment by commy2** [comment]
It's just setting the wind to a global value that is the same everywhere in MP. There are no additional sounds playing, that is how wind sounds in the game.
If you want to change the volume etc. then find out how to change that and create a pull request. No such changes are in ACE.

**Comment by LAxemann** [comment]
> 
> 
> It's just setting the wind to a global value that is the same everywhere in MP. There are no additional sounds playing, that is how wind sounds in the game.
> If you want to change the volume etc. then find out how to change that and create a pull request. No such changes are in ACE.

Wind volume/intensity changes dramatically when enabling map wind simulation, period. Whatever the module does, it at least increases the default wind intensity to almost maximum by default.

It's super easy to replicate - Go on malden, listen to the wind, then turn wind simulation off, restart the mission as the hint suggests and notice that it's a night/day difference.

**Comment by commy2** [comment]
>Whatever the module does, it at least increases the default wind intensity to almost maximum by default.

Doubt this. There is the `wind` command to read the wind.

I don't see the problem. If you don't like the wind synchronization, turn it off.

**Comment by LAxemann** [comment]
> 
> 
> > Whatever the module does, it at least increases the default wind intensity to almost maximum by default.
> 
> Doubt this. There is the `wind` command to read the wind.
> 
> I don't see the problem. If you don't like the wind synchronization, turn it off.

It's not wind synchronization, it's the wind SIMULATION module, found in the same category (weather).

**Comment by jones140** [comment]
I have to agree with  laxman i sadly have never used the wind module because of this exact issue it always sounds like your in a gale

**Comment by Max255PL** [comment]
Same experience here (I did brought it up last year in Slack iirc, but ended up just not using the ACE wind simulation).

**Comment by bux** [comment]
https://github.com/acemod/ACE3/blob/master/addons/weather/CfgWorlds.hpp

Is missing an entry for Livionia, that's probably the reason for the abnormal amounts of wind

**Comment by commy2** [comment]
Nobody in this thread mentioned "Livionia" though.

**Comment by severgun** [comment]
So it is BIS fault that wind is so loud?

**Comment by commy2** [comment]
Loud on what map?

**Comment by severgun** [comment]
Every.
Malden as an example was suggested here.

**Comment by bux** [comment]
I only experience really loud wind on Livonia.
Maybe wind syncing could be disabled for maps that don't have the necessary entries.

**Comment by LAxemann** [comment]
Okay, to go a bit into detail and looking at what things do:

It's not weather sync, but "wind simulation", which is a seperate option in ACE weather. The description states that it calculates wind based on terrain, which in and on itself is great.
The thing we're experiencing is most likely that the wind simulation's calculated output value always ends up near the maximum (indicated by the sound, which is linked to the "wind" controller).

**Comment by severgun** [comment]
@LAxemann as @commy2 said volume is not related to ACE3 directly. I think this is map CfgEnvSounds
 `volume` formula issue.
As I understand "ace wind simulation" should return and apply wind speed values based on real meteo data. No sound modifiers applied.
Calculated values should be checked to be sure. Worlds configs have volume formulas(ex. `volume = "(1-hills)*windy*0.5";`). Probably they lead to very loud sound even at moderate wind speed.

**Comment by LAxemann** [comment]
> 
> 
> @LAxemann as @commy2 said volume is not related to ACE3 directly. I think this is map CfgEnvSounds
> `volume` formula issue.
> As I understand "ace wind simulation" should return and apply wind speed values based on real meteo data. No sound modifiers applied.
> Calculated values should be checked to be sure that they are not going wild. Worlds configs have volume formulas(ex. `volume = "(1-hills)*windy*0.5";`). Probably they lead to very loud sound even at moderate wind speed.
> 
> There is also sound shaders
> 
> ```
> class Wind_Low_SoundShader {
>     samples[] = {{"A3\Sounds_F_Exp\Environment\elements\winds\wind_generic_low", 1}};
>     volume = "0.2 * (windy factor[0,1.2]) * (altitudeGround factor [1000, 0])";
> };
> class Wind_High_SoundShader {
>     samples[] = {{"A3\Sounds_F_Exp\Environment\elements\winds\wind_generic_high", 1}};
>     volume = "0.3 * (windy factor[0,1.2]) * (altitudesea factor [0,1000])";
> };
> ```

Yes and no, the "wind" soundController is 1 to 1 linked to the "wind" value in the game (called "windy" in the soundController"). So, if the ingame wind is set to 1, the "windy" soundController is set to 1.

So, the soundControllers work fine and as expected as they just take the map's current wind value.
windy factor[0,1.2]
Means the sound value will be 0 when the wind is 0 and 1 when the wind is 1.2.

Those soundControllers can't be changed via script or anything, it's just the calculated wind value.

**Comment by severgun** [comment]
But overall formula and multipliers can be changed.
So, I think, if you draw graphs based on volume formulas, you will see pretty steep climbing line.

**Comment by LAxemann** [comment]
> 
> 
> But overall formula and multipliers can be changed.
> So, I think, if you draw graphs based on volume formulas, you will see pretty steep climbing line.
> At low wind volume is OK, but more wind speed lead more noise. Sounds pretty logical, but I agree that it is unrealistically loud even at moderate speed.

Yup, as I've written above - the ACE wind calculation output would have to be overhauled. Changing the sounds and their formulas themselves would be a bad solution, as their formulas were designed to sound natural "by default" - which, again, indicates that the output values of the wind simulation are simply too high.

**Comment by severgun** [comment]
How they can be too high if they are in meters per second based on real meteo data for real life geo locations?

Do you have test results that show that ace results are wrong here:
https://github.com/acemod/ACE3/blob/80879da2415d7d21b275e86163cf1acd168c02a5/addons/weather/functions/fnc_updateWind.sqf#L21
?

**Comment by LAxemann** [comment]
> 
> 
> Do you have test results that show that ace results are wrong here?:
> 
> https://github.com/acemod/ACE3/blob/80879da2415d7d21b275e86163cf1acd168c02a5/addons/weather/functions/fnc_updateWind.sqf#L21
> 
> I tend to believe that BIS or terrain maker formulas unrealisticaly reproduce wind speed to volume ratio.

Maybe, we / I don't know. Pretty sure the game calculates an overall multiplier value out of the wind speeds. I guess the value simply becomes "1" at very low speeds already.

**Comment by severgun** [comment]
setWind [0,10,true] and setWind [0,20,true] on malden's beach sounds equal to me.
IRL 10 m/s not a storm.
