### ISSUE TITLE
Code give advanced medical for script?

### ISSUE THREAD

**Issue by diaverso** [acemod/ACE3#7270]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96` [e.g. 1.00 stable, rc,  dev]
- **CBA:** ` 3.12.2` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.12.6` [eg. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
We make our own script, which assigns a uuid to each user that enters the server and stays registered in a database.
Through this uuid you activate the resources that you have available in your user.
Example: User 1145 has the licenses of AT, Physician, Engineer.
So, we are looking for the code, so that the advanced doctor and the advanced engineer are activated.

**Where did the issue occur?**
- Dedicated

**Comment by bux** [comment]
https://ace3mod.com/wiki/

**Comment by commy2** [comment]
You sure it is on the wiki for medical?

**Comment by diaverso** [comment]
No, it's not, and I don't know how to make it work, so I asked

**Comment by diaverso** [comment]
> 
> 
> You sure it is on the wiki for medical?

No, it's not, and I don't know how to make it work, so I asked

**Comment by commy2** [comment]
this setVariable ["ACE_Medical_medicClass", 1];

**Comment by diaverso** [comment]
This code would work?

if (_x == "Medico") then {
            _tio setUnitTrait ["ACE_Medical_medicClass", true];
        };

**Comment by commy2** [comment]
No.
