### ISSUE TITLE
Arsenal Default Loadouts doesn't support items hidden from arsenal

### ISSUE THREAD

**Issue by Grezvany13** [acemod/ACE3#7275]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96 stable`
- **CBA:** `3.12.2 stable`
- **ACE3:** `3.12.6 stable`
Mods downloaded from Steam Workshop and up-to-date.
No other mods were used for the test-case.

**Description:**
When creating a Default Loadout based on an unit with weapons or backpacks which are not visible in the Arsenal (no `scope = 2`, or using `baseWeapon = "other_class"`), the items will not show up in the loadout list and won't be given to the player when selected. Or is inconsistent in results (eg. some backpacks with contents do work, some don't. Weapons never seem to show up).

**Steps to reproduce:**
- In 3DEN place a Repair Specialist (B_soldier_repair_F) and a random container with ACE Arsenal:
```
// init
[this, true] call ace_arsenal_fnc_initBox;
```
- Load the mission (SP or MP).
- Check the current output of `getUnitLoadout` on the player:
```
// debug console
_loadout = (getUnitLoadout player);
_loadout
```
- You will see that the unit has weapon `arifle_MX_Holo_pointer_F` with 2 attachments (`acc_pointer_IR` and `optic_Holosight`).
- Add the current loadout of the player to the Default Loadouts:
```
// debug console
_loadout = (getUnitLoadout player);
["<TEST>", _loadout] call ace_arsenal_fnc_addDefaultLoadout;
```
- Open ACE Arsenal on the container and go to Loadouts >> Default Loadouts.
- You wil see a loadout called `<TEST>`, but does *not* have a primary weapon.
- Select the loadout, give it to yourself and exit ACE Arsenal.
- You will now see that the unit does not have a primary weapon, the rest of the items are present.
- Check the new output of `getUnitLoadout` on the player:
```
// debug console
_loadout = (getUnitLoadout player);
_loadout
```
- You will now see that the primary weapon. the attachments and loaded magazine are gone from the array. All other items are present.

- The log file does show the following message when opening the Default Loadouts tab in ACE Arsenal:
```
16:27:54 ACE_Arsenal - Loadout:
    Name: <TEST>
    Missing items: []
    Unavailable items: ["arifle_MX_Holo_pointer_F"]
```

**Expected behavior:**
I expect that the full loadout which is saved is also available and loaded correctly on the player, unless the items do not exist in the configs (eg. modded content while mod is disabled).
It should ignore visibility and scope (unless `scope = 0`), or find the parent (eg, with `BIS_fnc_baseWeapon`) and retrieve the correct item, attachments and contents.

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)
- not tested in other environments, but should be everywhere

**Log Files:**
https://pastebin.com/rC6dh0V7

**Additional context:**

**Screenshots:**

**Comment by commy2** [comment]
I disagree with the expected behavior and think it currently works exactly as intended.

**Comment by Grezvany13** [comment]
However both vanilla Arsenal and ACE Arsenal do recognize the parent items and are able to properly show the used weapon with attachments and backpack with contents, even though the configs state they are hidden.
This means that both Arsenals do it as I expect, and don't filter out items without checking for the base items. So only the saved loadouts have this mechanic in place which is different.

**Comment by commy2** [comment]
Yes, because you're supposed to be able to open the arsenal with any loadout. Loadout of an object is unambiguous, even if preequipped classes are used.

Doesn't mean you should enter ambiguous preequipped classes when using the save loadout function.

**Comment by commy2** [comment]
Tag as question and close?

**Comment by alganthe** [comment]
No, he's right.

That function isn't the one used to store default loadouts internally, wak seems to have forgotten part of it so the weapon isn't swapped for the default one.

Since the weapon isn't whitelisted anymore because it isn't in your hands when you open ACE arsenal (those weapons with pre-added attachments are scope 1), the loadout manager doesn't give it to you.
