### ISSUE TITLE
White-listing Magazines unable to remove RHS magazines

### ISSUE THREAD

**Issue by jones140** [acemod/ACE3#7278]
**ACE RHS RHS COMPAT:**
- **Arma 3:** Stable
- **CBA:** `3.12.6
- **ACE3:** `v3.12.2
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
White-listing Magazines unable to remove RHS magazines

**Steps to reproduce:**
- Go to editor
- open a object and try to whitelist a weapons with 5.56 that uses mag wells 
- click play see you can pick from RHS magazines even if you haven't added them to white-list  

**Expected behavior:**
Only magazines  that you whit-list should be in there 

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal all

**Log Files:**
- NA?

**Screenshots:**
https://i.gyazo.com/6b6cff62c0fa3c4b7a1a5cf6a705eba4.png

**Comment by commy2** [comment]
user error?

**Comment by jones140** [comment]
I dont understand how it  can be my error 
I am not listing these mags to be used yet they show up in list

**Comment by alganthe** [comment]
I tested both vanilla and modded weapons (that weren't RHS though) on master and last release, I could not reproduce the issue.

can you:
- only whitelist this weapon.
- open the debug console, type
`["ace_arsenal_displayOpened", {copyToClipboard str (ace_arsenal_virtualItems select 2)}] call CBA_fnc_addEventHandler;` and press enter.
- Open ACE Arsenal and paste the result here ?

**Comment by jones140** [comment]
OK i have found issue 
steps 
add f200
- add compatible magazines
- clear so no mags should be available 
then you will still end up with these.
["rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Green","rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Yellow","rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Orange","rhs_mag_30Rnd_556x45_M855A1_Stanag_No_Tracer","rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Green","rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Yellow","rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Orange"]

**Comment by LinkIsGrim** [comment]
Since fixed, but can't track down the cause. Maybe #9040?
