### ISSUE TITLE
No PBO files in update

### ISSUE THREAD

**Issue by eagleye100** [acemod/ACE3#729]
Hi guys, First of all i wish you a very good luck in the process. 

After 17th April's update i don't see the .pbo file in it could you please fix this?

Regards

**Comment by meat147** [comment]
Wish update where ?

**Comment by eagleye100** [comment]
on armaholic http://www.armaholic.com/page.php?id=28557

**Comment by eagleye100** [comment]
I guess armaholic has updated again because i can see pbo files now. thanks very much for your time.

**Comment by jaynus** [comment]
These are not official releases and we cannot help with them.

**Comment by eagleye100** [comment]
ok thanks for mail but i have one question, when i try to modify ace control keys i'm not able to locate Ace mod in list even though its enabled and i can see its logo, also Ace's  orange  active title on top left corner of main screen disappears every time game starts.any help would be grateful.

Regards

Date: Fri, 17 Apr 2015 17:58:40 -0700

**Comment by jaynus** [comment]
You probably need to go in game to do your settings, not hte main menu. 

You cannot do settings/controls from the main menu if you use -world=empty.

Again, we won't support unofficial ACE builds when setup, build and compilation are completely out of our control. 

Sorry.

**Comment by eagleye100** [comment]
Thanks alot sir.

Regards

Date: Fri, 17 Apr 2015 19:44:46 -0700
