### ISSUE TITLE
Repair - look into making it possible to repair optics // (compability) rhs m2a3 bredley repair bug

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#7290]
**Mods (complete and add to the following information):**
Arma 3: Stable
CBA: `3.12.6
ACE3: `v3.12.2

**Description:**
if you destroy the sight in a ravings, then after a full or partial repair the sight is not restored.
a full repair fixes it, but there is no module repair.
http://joxi.ru/EA44Lwoioe5MWA

USE: rhsusaf, cba, ace

p/s/  I think you need to revise the repair script, because in many mods hit points are not completely specified so that your script works. now we are faced with a choice. either play without ace, or get out of these situations yourself. I think this problem is like a ticket
**RHS Compat. Stryker doesn't have repair points for turret and optics. #7245**

**Comment by PabstMirror** [comment]
We normally filter glass/optics/periscopes as these would be harder to fix
Full repair should fix them
Perhaps we could add an option to do a "repair optics" action

**Comment by LinkIsGrim** [comment]
Fixed in #8347.
