### ISSUE TITLE
ace_cargo. Loaded objects taking damage.

### ISSUE THREAD

**Issue by severgun** [acemod/ACE3#7295]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96` stable
- **CBA:** `3.13.0` stable
- **ACE3:** `3.12.6` stable
- **RHS**
- **...**

**Description:**
Objects loaded **as objects**(not classnames) start taking damage from falling(I think) after `hideObjectGlobal` event
https://github.com/acemod/ACE3/blob/3333b41dfb1392d4fb9dc6ff9bcfc05307653a01/addons/cargo/functions/fnc_loadItem.sqf#L39

**Steps to reproduce:**
- Go to editor
- Place unit, static weapon and HEMTT
- Load and wait some time. (it start taking periodical damage after some time). You can start onEachFrame hint and check object damage.
- Unload and check damage 

**Expected behavior:**
Block damage for hided items

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Comment by severgun** [comment]
Tests shows, that if attach at -34 here
https://github.com/acemod/ACE3/blob/80879da2415d7d21b275e86163cf1acd168c02a5/addons/cargo/functions/fnc_loadItem.sqf#L38
then damage not applied.
Maybe damage should be blocked by blockDamage ace statusEffect. Not sure.

**Comment by Mecaguy03** [comment]
Can confirm this is happening on multiple different maps, although it seems to be somewhat inconsistent.

**Comment by Panisher** [comment]
> Can confirm this is happening on multiple different maps, although it seems to be somewhat inconsistent. Possibly related to what elevation you are at on the map?

Any map

**Comment by severgun** [comment]
1.98 new PhysX. Bug still exist
