### ISSUE TITLE
Common/Medical - AI aiming/shooting at hidden/unconscious units

### ISSUE THREAD

**Issue by Coryf88** [acemod/ACE3#7299]
**Mods:**
- **Arma 3:** `1.96.146114 stable`
- **CBA:** `3.13.0 stable`
- **ACE3:** `3.12.6 stable`/`3.13.0 stable`/`3.13.1 stable`

**Description:**
AI aims/shoots at hidden/unconscious units.

**Steps to reproduce:**
- Have a player and enemy AI unit where line-of-sight is blocked.
- Execute `[player, "setHidden", "aiAimShootTest", true] call ace_common_fnc_statusEffect_set;`
- Run around/*touch* the enemy AI.
- Notice the AI will aim/shoot at the player.

**Expected behavior:**
AI to not aim/shoot at hidden/unconscious units.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer)

**Log Files:**
- N/A

**Additional context:**
`player setUnitTrait ["audibleCoef", 0];` stops the behavior.

**Screenshots:**
Unconscious: https://youtu.be/DJIYrEVqecY

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
