### ISSUE TITLE
ATRAGMX - Bad data saved in profileNamespace

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#730]
On mission start (no item in inventory):

```
Error in expression <d((ace_atragmx_workingMemory select 13) * 1000) / 1000)];
};
if ((missionNamespa>
Error position: <* 1000) / 1000)];
};
if ((missionNamespa>
Error *: Type String, expected Number,Not a Number
File z\ace\addons\atragmx\functions\fnc_update_gun_ammo_data.sqf, line 21
Error in expression <d((ace_atragmx_workingMemory select 13) * 1000) / 1000)];
};
if ((missionNamespa>
Error position: <* 1000) / 1000)];
};
if ((missionNamespa>
Error Generic error in expression
File z\ace\addons\atragmx\functions\fnc_update_gun_ammo_data.sqf, line 21
```

Dumping GVAR(workingMemory): 
[18] - ["12.7x108mm",820,100,0.0659,-0.00086,3.81,0,0.338,0.338,120,0,0,48.28,"B_127x108_Ball","5Rnd_127x108_Mag",0.7,1,"ASM"]
so there was a string in index 13 and it expects a number.

Seems like it was loading old, bad data from profileNamespace
doing 
`profileNamespace setVariable ["ACE_ATragMX_gunList", nil];` seems to be needed to fix.

Maybe do a count/typeName sanity check on profile data to make sure it makes sense.

I also don't understand why update_gun_ammo_data.sqf is running at mission start.  It seems to be filling out a display that does not exist.

**Comment by jaynus** [comment]
We need to implement a profileNamespace recovery method, to fix issues like this. Also, we all need to be really careful saving things in profileNamespace. Why is this saving there?

**Comment by commy2** [comment]
I'm still for nuking all our variables if the game detects a newer build than playing the last time.

```
{
  if (toLower _x find "ace_" == 0) then {
    profileNamespace setVariable [_x, nil];
  };
} forEach allVariables profileNamespace;
```

**Comment by jaynus** [comment]
Let's do this. Can we do it along with a new setting for requiring all pbo by default? (Setting to turn on check pbo)

**Comment by commy2** [comment]
Yeah. I'm currently rethinking the version checking as a whole with the goal to simplify it. (And to prevent disasters like my community had on thursday)

Maybe even kicking players which don't have the correct version similar to:
https://github.com/acemod/ACE3/pull/728

**Comment by ulteq** [comment]
The ATragMX now automatically overrides deprecated profileNamespace data:
https://github.com/acemod/ACE3/commit/fc39b81c958284193b78afbee69d72025b774569

**Comment by esteldunedain** [comment]
> The ATragMX now automatically overrides deprecated profileNamespace data: fc39b81
:+1:

**Comment by ulteq** [comment]
>I also don't understand why update_gun_ammo_data.sqf is running at mission start. It seems to be >filling out a display that does not exist.
I will take a look at it.
