### ISSUE TITLE
worldToScreenBounds - error if target off screen

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#731]
![image](https://cloud.githubusercontent.com/assets/9376747/7213583/64d1eb96-e549-11e4-91a1-4bd4ed90a0c7.png)
```
Error in expression <_pposX = _ppos select 0;
_pposY = _ppos select 1;
if (_pposX < _minX) then {_min>
Error position: <select 1;
if (_pposX < _minX) then {_min>
Error Zero divisor
File z\ace\addons\common\functions\fnc_worldToScreenBounds.sqf, line 45
```

`worldToScreen` "If a specified position is not within the current screen view, an empty array is returned."  So the select's fail.

Can easily stop error by skipping corners that are offscreen, 
but logic wise I'm not sure what we want to do with the returnValue if a corner of a target is offscreen?

**Comment by bux578** [comment]
@PabstMirror can this be closed?

**Comment by PabstMirror** [comment]
I just wanted to leave a note if worldToScreenBounds broke after the fix.  As far as I know it's working fine, so this can be closed.
