### ISSUE TITLE
Check response shows "No" but patient is alive

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#732]
ACE3 Version: custom 17.04.2015

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
No, checked in VR

Description:
Try to check response on any unconcious AI (Head - Check response). It will show "No response" but patient is actually alive (normal blood pressure and pulse is ok).

Steps to reproduce:
Try to check response on any unconcious AI

Where did the issue occur?
Every time

RPT log file:
No

**Comment by PabstMirror** [comment]
```
if ([_target] call EFUNC(common,isAwake)) then {
    _output = "STR_ACE_MEDICAL_CHECK_REPONSE_RESPONSIVE";
} else {
    _output = "STR_ACE_MEDICAL_CHECK_REPONSE_UNRESPONSIVE";
};
```

`Check response` is just testing if the target is awake//conscious.

So I believe this is working as intended

**Comment by ruPaladin** [comment]
Thank you. Closing then.
