### ISSUE TITLE
Tourniquet animation is too slow comparing with bandaging one

### ISSUE THREAD

**Issue by unhappytroll** [acemod/ACE3#7325]
- **Arma 3:1.96.146114 
- **CBA:** 3.13.0
- **ACE3:** 3.13.0 RC1

**Is your enhancement related to a problem?**
Animation speed for bandaging is faster than animation for applying tourniquet. It makes tourniquet rather useless imo, because applying three-four bandages is faster with RC1 and usually resolve most damage.

**Solution you'd like:**
Applying tourniquet should be fastest animation, and bandaging should be slower at least one and a half times.

**Comment by commy2** [comment]
Animation speed was adjusted. There is no reason why a tourniquet should be faster than a single bandage, A tourniquet still stops bleeding on a limb completely while multiple bandages may be needed.
