### ISSUE TITLE
Vanilla sniper wrong type with `BIS_fnc_itemType`

### ISSUE THREAD

**Issue by mattyimperator** [acemod/ACE3#7326]
Hi,during my tests i've find a bug.
if I use BIS_fnc_itemType with rifles: GM6 Lynx and M200 Intervention results is "assaultrifle".
I try with CBA,ACE3.
If i use arma3 vanilla,this 2 rifles are "sniper rifle"

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/blame/e5a15d200f44df5fccc0bc5575d18d80b35538dd/addons/smallarms/CfgWeapons.hpp#L194

**Comment by mattyimperator** [comment]
sorry i dont understand, what you mean?

**Comment by mattyimperator** [comment]
![photo_2019-12-23_23-43-28](https://user-images.githubusercontent.com/59142137/71383746-0a0fda80-25de-11ea-8007-308698c8d72a.jpg)

**Comment by mattyimperator** [comment]
with CBA & ACE on the  "srifle_GM6_F" i have assault rifle

**Comment by mattyimperator** [comment]
![photo_2019-12-23_23-47-31](https://user-images.githubusercontent.com/59142137/71383863-9b7f4c80-25de-11ea-94ec-295edbc6a776.jpg)

**Comment by mattyimperator** [comment]
and in vanilla i have a sniper rifle ..... why ?

**Comment by commy2** [comment]
>why 

https://github.com/acemod/ACE3/issues/7326#issuecomment-568280612

**Comment by mattyimperator** [comment]
so you tell me it is not an issue and ACE3 team don't want to change it?

**Comment by commy2** [comment]
what?

**Comment by mattyimperator** [comment]
can you explain what you mean in best word?

**Comment by dedmen** [comment]
He linked the code that causes your issue. Thats what we'll have to fix.

**Comment by mattyimperator** [comment]
ok now i understand thank you dedmen

**Comment by PabstMirror** [comment]
Why is ACE changing it?
`cursor = "srifle";` is vanilla, which seems like a much better fit
Perhaps it used to be something else in vanilla?
This looks like it's a AGM thing that might not make sense to keep anymore

**Comment by commy2** [comment]
I very _very_ vaguely remember Flummi telling me in a one-off sentence on Teamspeak over 6 years ago that he changed the crosshairs of some weapons, because they were better somehow.
But I may be misremembering, I didn't pay attention.

**Comment by jonpas** [comment]
Why are we changing crosshair when nobody plays on a difficulty that shows them? XD

**Comment by commy2** [comment]
Next time fill out the issue template and don't spam the issue with single sentence replies. Thanks.
