### ISSUE TITLE
If patient is unconcious his head slightly moves

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#733]
If patient is unconcious his head slightly moves. Looks like idle animation. Don't know is it a bug or feature. Just want to let you know.

**Comment by commy2** [comment]
Will check if we can do anything about this.

It's not actually an idle animation, it's standard idle movement. You can see it aswell on the animations with lowered weapon (those don't have idle animations with ace_noidle)

**Comment by commy2** [comment]
I don't think there is anything in the config that can turn this off.

Also, in future please follow: http://ace3mod.com/wiki/user/how-to-report-an-issue.html when reporting an issue.
