### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by Joshuwat** [acemod/ACE3#7334]
Before anything is said, yes I have followed the Settings Framework on the ACE3 site. My problem, while trying to setup a dedicated server and while wanting to set up custom parameters in the addon, is that when following the settings framework, it states that 

> The server config setting entries are done through our optional ace_server.pbo, which can be found in the optionals folder of @ace. It also contains a userconfig folder, which inside contains the file ace\serverconfig.hpp. This is the location where ACE3 settings are placed. There is no need for a sub-class. Once the settings file is updated everything should be copied to the Arma 3\userconfig folder. When loaded ace_server.pbo will try to read the settings from the following path Arma 3\userconfig\ace\serverconfig.hpp.

 Now, it says this, however, from trying ACE from the steam workshop and the ACE website itself, none of these are available in the "Options" folder. This is an issue that I cannot find a work around, and I do not see a configuration for ace. The only thing that ive seen is possible is the editing of the pbo files which I do not personally know/want to do.

If there is something I am missing please let me know, I would like to use ace with my specific settings on my dedicated server, and I cannot do this when I am missing a required folder from both download locations.

**Comment by Vdauphin** [comment]
Hello,

>If there is something I am missing please let me know,

[Settings Framework on the ACE3 site](https://ace3mod.com/wiki/framework/settings-framework.html) has also note saying:
> Deprecated and replaced with [CBA Settings System](https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System) in 3.12.0!

Also consider https://slackin.ace3mod.com/ for faster and better help.

Cheers
