### ISSUE TITLE
Interaction Key does not work.

### ISSUE THREAD

**Issue by Pharo2** [acemod/ACE3#7339]
The title is self-explanatory. 

Every time I launch up Arma 3, no matter which mission I am using the interaction key isn't working. 
The red circle doesn't even show up, other Ace3 modules do work for me and multiplayer works fine. Other people in my game can use the interact fine, just I cannot.

Mods I am using :

Ace3
CBA_A3 (GitHub version and Steam version)
Overthrow 
Achilles

Things I have tried : 

Delete entire addons folder and reinstall
Use GitHub version of CBA_A3
Reinstall all mods
Repair mods using Arma3 launcher
Use different missions
Reinstall Arma3
Restart Computer
Uninstall mods I'm not using
Make a new profile

Any ideas?

**Comment by PabstMirror** [comment]
Some keyboards have problems passing the windows key.
I think some gaming ones may have a switch in hardware or software to control it's use in games.

otherwise I think overthrow had problems in the past, see: https://github.com/acemod/ACE3/issues/5323#issuecomment-313145415

>If you want to fix your profile, you can run this code in debug console from editor
```
profileNamespace setVariable ["Overthrow.save.001", nil];
profileNamespace setVariable ["Overthrow.malden.001", nil];
profileNamespace setVariable ["Overthrow.altis.001", nil];
```
there might be others if it was played on other maps?

**Comment by Pharo2** [comment]
Hey! Thanks for such a quick response, I forgot to add the new profile attempt. That didn't work for me either.

**Comment by Pharo2** [comment]
Just pasted those commands. This still isn't working for me. It had actually fixed itself last night but when I launched it up this morning it stopped working. I had cleared the addons folder and reinstalled it for that to work, I tried it again and still isn't working.

**Comment by PabstMirror** [comment]
maybe try just CBA/ACE, then create a new temp profile and see if you can get that working
if it does, then add all other mods besides overthrow and test

**Comment by Pharo2** [comment]
Remove Overthrow and Achilles, created a new temp profile. Still doesn't work. I'm beginning to wonder if I have somehow unbound the key?

**Comment by PabstMirror** [comment]
also make sure to try a key besides the windows key,

**Comment by Pharo2** [comment]
Where do I bind it?

**Comment by Pharo2** [comment]
I rebound it, it works now. This makes me completely confused, what would make this problem happen? Thank you!

**Comment by PabstMirror** [comment]
some keyboards or gaming software try to protect you from hitting the win key

**Comment by Pharo2** [comment]
Makes total, sense. Thank you so much for this.
