### ISSUE TITLE
Practice Ammunition

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#734]
Add practice ammunition that allow proper TvT training scenarios with hit display.

http://simunition.com/en/

> ulteq [13:06] 
> I think we could add those easily
> Reduced muzzle velocity, relatively high airFriction, hit value of 0
> And for the visual feedback we would have to add a special hit eventhandler on the players
> Which checks if you got hit by it, and then shakes the camera a bit
> We could add a module for it

**Comment by bux578** [comment]
@ulteq

**Comment by commy2** [comment]
Flummi is gonna be so mad about this.

**Comment by Heavygunner96** [comment]
I don't really get the purpose of this request but neither I understand why Flummi would be mad about it?^^

**Comment by KoffeinFlummi** [comment]
https://github.com/acemod/ACE3/issues/414 ;)

**Comment by bux578** [comment]
> #414 

That's the link for the public feature requests.

**Comment by alganthe** [comment]
someone didn't read #414

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
