### ISSUE TITLE
ML300L - FakeMagazine's .paa missing

### ISSUE THREAD

**Issue by Blutze** [acemod/ACE3#7352]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96.14611`
- **CBA:** `3.13.0`
- **ACE3:** `3.13.0 release`

**Description:**
When equipping the ML300L from the Arsenal, it is loaded with a `FakeMagazine`. Opening the Arsenal's magazine tab removes it, but skipping that step leaves the magazine in. Opening the inventory now throws an error message `Warning Message: Picture equip\m\m_fakemagazine.paa not found`, and the loaded magazine does not show an icon.

**Expected behavior:**
The flashlight also works without any magazine. Is there a way to always make it spawn unloaded?

**Where did the issue occur?**
Editor (Singleplayer) / Virtual ACE Arsenal

**Log Files:**
RPT: https://gist.github.com/Blutze/93259739d7ff740169c3ae7c9415547c

**Additional context:**
Not exactly related to the issue itself, but the maplight beam is smaller than the regular maglite's. Depending on the shape of the cone, that might be realistic, but gutfeeling would be expecting a more powerful effect from a heavier, bigger, dedicated item.

**Comment by commy2** [comment]
Just replace it with the empty_ca.paa from the base game files. Should be already used in ACE a bunch.
