### ISSUE TITLE
Inconsistent behavior of pain multiplier

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#7357]
Pain multiplier does not act on normal injuries.
Related to #7227.

**Comment by PabstMirror** [comment]
Ref: https://github.com/acemod/ACE3/pull/7231

**Comment by LinkIsGrim** [comment]
https://github.com/acemod/ACE3/blob/master/addons/medical_status/functions/fnc_adjustPainLevel.sqf#L26 close?
