### ISSUE TITLE
Unable to 'Use Surgical Kit'/Stitch wounded patients

### ISSUE THREAD

**Issue by WolffeUS** [acemod/ACE3#7369]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96 stable`
- **CBA:** `3.13.0`
- **ACE3:** `3.13.0`

**Description:**
Upon being shot and injured, after a Player/AI has bandaged their wounds and applied a splint(if applicable), Medics and Doctors are not able use the Surgical Kit to stitch patients as the interaction option does not show up on any limbs or as an option within the Medical Menu.

**Steps to reproduce:**
- Be a Medic/Doctor.
- Rush immediately to your wounded comrade.
- Apply bandages/splints/tourniquets where necessary.
- Confirm the limb is now blue and none other immediate medical attention is needed.
- Attempt to look for the 'Use Surgical Kit' option on either the affected limb, the torso, or within 'Advanced Treatments' within the Medical Menu.
- [PepeHands](https://external-preview.redd.it/jvnDpmaqO-r5IU5j2XgwhblfExiQE36a6iMNA9oblQs.png?auto=webp&s=c89ac763a5c6d380099666bf65fb303d029ce0ee) when you realize the option isn't there and you don't have a PAK to reset their medical history/Full Heal.

(OPTIONAL)
- Take a gun.
- Shoot a person.
- Proceed from Step 3.

**Expected behavior:**
- Be a Medic/Doctor.
- Rush immediately to your wounded comrade.
- Apply bandages/splints/tourniquets where necessary.
- Confirm the limb is now blue and none other immediate medical attention is needed.
- Attempt to look for the 'Use Surgical Kit' option on either the affected limb, the torso, or within 'Advanced Treatments' within the Medical Menu.
- Find the option and finish giving the patient the high quality medical care they deserve.
- [FeelsHappyMan](https://i.imgur.com/UJHWDtD.jpg) at a job well done.

(OPTIONAL)
- Take a gun.
- Shoot a person.
- Proceed from Step 3.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Log Files:**
[.rpt Log](https://pastebin.com/YRknqETR)

**Comment by mharis001** [comment]
Can you provide the medical settings that you are using.

**Comment by WolffeUS** [comment]
> 
> 
> Can you provide the medical settings that you are using.

> // ACE Medical
ace_medical_ai_enabledFor = 2;
ace_medical_AIDamageThreshold = 1;
ace_medical_bleedingCoefficient = 1;
ace_medical_blood_bloodLifetime = 900;
ace_medical_blood_enabledFor = 2;
ace_medical_blood_maxBloodObjects = 500;
ace_medical_fatalDamageSource = 0;
ace_medical_feedback_painEffectType = 0;
ace_medical_fractures = 1;
ace_medical_gui_enableActions = 0;
ace_medical_gui_enableMedicalMenu = 1;
ace_medical_gui_enableSelfActions = true;
ace_medical_gui_maxDistance = 3;
ace_medical_gui_openAfterTreatment = true;
ace_medical_ivFlowRate = 1;
ace_medical_limping = 1;
ace_medical_painCoefficient = 1;
ace_medical_playerDamageThreshold = 1;
ace_medical_spontaneousWakeUpChance = 0.05;
ace_medical_spontaneousWakeUpEpinephrineBoost = 1;
ace_medical_statemachine_AIUnconsciousness = true;
ace_medical_statemachine_cardiacArrestTime = 30;
ace_medical_statemachine_fatalInjuriesAI = 0;
ace_medical_statemachine_fatalInjuriesPlayer = 0;
ace_medical_treatment_advancedBandages = true;
ace_medical_treatment_advancedDiagnose = true;
ace_medical_treatment_advancedMedication = true;
ace_medical_treatment_allowLitterCreation = true;
ace_medical_treatment_allowSelfIV = 1;
force ace_medical_treatment_allowSelfStitch = 1;
ace_medical_treatment_allowSharedEquipment = 0;
ace_medical_treatment_clearTraumaAfterBandage = false;
ace_medical_treatment_consumePAK = 0;
ace_medical_treatment_consumeSurgicalKit = 0;
ace_medical_treatment_convertItems = 0;
ace_medical_treatment_cprSuccessChance = 0.4;
ace_medical_treatment_holsterRequired = 0;
ace_medical_treatment_litterCleanupDelay = 600;
ace_medical_treatment_locationEpinephrine = 0;
force ace_medical_treatment_locationPAK = 0;
ace_medical_treatment_locationsBoostTraining = false;
force ace_medical_treatment_locationSurgicalKit = 0;
ace_medical_treatment_maxLitterObjects = 500;
ace_medical_treatment_medicEpinephrine = 0;
force ace_medical_treatment_medicPAK = 0;
force ace_medical_treatment_medicSurgicalKit = 0;
ace_medical_treatment_timeCoefficientPAK = 1;
ace_medical_treatment_woundReopening = false;

**Comment by mharis001** [comment]
Both "Advanced Bandages" and "Wound Reopening" are required in order to be able to stitch wounds. You may see that in the injuries list the bandaged wounds are grey instead of red.

I think it may be better to not add these wounds to the injury list at all to prevent confusion.

**Comment by WolffeUS** [comment]
> 
> 
> Both "Advanced Bandages" and "Wound Reopening" are required in order to be able to stitch wounds. You may see that in the injuries list the bandaged wounds are grey instead of red.
> 
> I think it may be better to not add these wounds to the injury list at all to prevent confusion.

I see, thank you for the assistance.
