### ISSUE TITLE
deprecated atropine!

### ISSUE THREAD

**Issue by grenadier2510** [acemod/ACE3#7376]
good morning

I updated ace and I realized, with regret that you have removed the atropine!
I know bitter because in a few days I will be out with a new version of my GREN EVO mod and inside you will find a module for nerve gas contamination. The only antidote, apart from the use of the gas mask, is atropine but now that there is no longer a fundamental element missing.
Speerado that it is only a forgetfulness I sincerely hope that it will become part of the drug kit.
sorry for my English

Best Regards

**Comment by jonpas** [comment]
You can re-add it in your mod using the following config: https://github.com/acemod/ACE3/pull/7212/files

ACE3 will not be re-adding it, hope this helps.
