### ISSUE TITLE
AI self-treatment with no material/bandages

### ISSUE THREAD

**Issue by ojemineh** [acemod/ACE3#7377]
**Mods:**
- **Arma 3:** `1.96.146114`
- **CBA:** `3.13.0`
- **ACE3:** `3.13.0`
- **ACEX:** `3.5.0`

**Description:**
AI bandages his wounds without having material in his inventory.

**Steps to reproduce:**
- Start ArmA3 with CBA, ACE & ACEX
- Open editor
- Place 1 playable unit + 1 ai unit (with no uniform, backpack, etc -> empty inventory)
- Play mission in multiplayer
- Shoot ai in a leg or something

**Expected behavior:**
AI can't bandage his wounds because of missing material/bandages.

**Where did the issue occur?**
- Editor (Multiplayer)

**Log Files:**
- [pastebin](https://pastebin.com/F0jpj3KG)

**Video:**
- [youtube](https://www.youtube.com/watch?v=oPx296YxgNY&feature=youtu.be)

**Comment by dedmen** [comment]
Confirmed
Vid: https://youtu.be/Hr-vIBmJhi4

**Comment by bux** [comment]
@BaerMitUmlaut this was by design, wasn't it?

**Comment by BaerMitUmlaut** [comment]
Yes, this is by design as you would have to run loadout scripts on all AI, which is not only another burden for the mission maker but also quite performance intensive.

**Comment by dedmen** [comment]
For AI's we could just check if they have either medical items, or vanilla FirstAidKit/Full medical kit in inventory, and let them heal themselves without using that stuff up.
That way its atleast somewhat correct.

**Comment by ojemineh** [comment]
I would welcome that, especially since it could then be prevented that ki can miraculously heal itself without bandages. possibly with a corresponding cba-settings option.

**Comment by BaerMitUmlaut** [comment]
You can already disable the medical AI through a setting, what's the point?

**Comment by ojemineh** [comment]
The point is that with "Medical AI" turned on, the mission builder can determine that units - if injured - may or may not bandage themselves. The dependency therefore lies with the individual unit (with or without dressing material) and not generally with the cba option.
