### ISSUE TITLE
Make revive timer that is different from cardiac arrest.

### ISSUE THREAD

**Issue by DPillow** [acemod/ACE3#7379]
Problem:
From what I can underestand, when cardiac arrest timer is on, people are still able to pick wounded up, even when they have no blood pressure (in most situations=dead dead). It messes with people who hate revive, beacuse we want cardiac arrest, but without picking up guys that are dead as far as we consider. We need some indicator if we can still pick up people.

Solution:
Make cardiac arrest timer that works only when player has blood, and revive timer that turns on when player has no blood. This will make cardiac arrest usefull for some people, and rest would be able to use revive.

So:
No blood pressure=dead dead, no cardiac arrest timer, posible revive.
No heart rate, blood pressure present= cardiac arrest timer, no revive timer
heart rate, blood pressure present= no cardiac arrest timer, no revive timer

Thanks for reading.

**Comment by KHunter-Arma** [comment]
For a lot of communities any such "indicator" is an immersion-killer and unwanted. If anything of this sort gets taken into consideration, it has to be optional. Plus your suggestion about "No heart rate, blood pressure present" makes no sense. You can't read blood pressure if there's no pulse...

**Comment by DPillow** [comment]
Ok, there shows my lack of knowledge. I've based that on old medical, where no blood pressure with revive off= dead. Thank you for claryfing that.

**Comment by SilentSpike** [comment]
One of our main goals in the rewrite was to remove the "revive" system because it caused so much confusion. Part of the idea behind cardiac arrest is that it fills that role while also being more realistic.

As such, I don't foresee us adding a revive state back in. However, if there are issues with the cardiac arrest state itself then feel free to open such issues 👍

**Comment by IllidanS4** [comment]
As if updating an essential addon without any clear indication how to use the original mechanics (and in many places without even including such a possibility) caused no confusion at all.

**Comment by commy2** [comment]
This is not a chat.
