### ISSUE TITLE
Interact_menu: hide farther action points if occluded by nearer ones

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#738]
Not actually a bug.

ACE3 Version: custom 17.04.2015

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
No

Description:
Here you may see that I have opened interaction menu: http://i.imgur.com/0o8oAv2.jpg
And here you may see the distance: http://i.imgur.com/0U8HfBQ.png
As you can see it is pretty great to second soldier. Because such distance may cause to open interaction menu for more than one soldiers (pic. 1), it also cause more fps drop.
Don't know if this need fixing or not because of gameplay impact.

Steps to reproduce:
Place two or three bots close to each other and press windows key.

Where did the issue occur?
Always

RPT log file:
No

**Comment by alganthe** [comment]
It also means we air stitch people, reducing it would be nice.

**Comment by esteldunedain** [comment]
The medical actions are displayed up to a maximum distance of 1.5m between your head and the action. Although this could obviously be patched by reducing that distance, it was kept like that for usability purposes, cause movement in arma is sometimes wonky and it's not always as easy as it should be to get really close to the bodypart you want to treat.

Potentially I'd like to make the interact menu smarter implementing some kind of occlusion, so if you have varios very near action points it just skips drawing points behind them, as your intent should be to use those action point nearest to you. This however needs experimenting and iterating until it feels right, so it's most probably not be on the first version.

I'll keep the issue around to document that.
