### ISSUE TITLE
CPR extends cardiac arrest timer

### ISSUE THREAD

**Issue by DPillow** [acemod/ACE3#7380]
Problem:
CPR should extend cardiac arrest timer, beacuse when you do it, you pump blood manually.

Solution:
Make new options in addon options+implement feature.
1. CPR extends Cardiac Arrest Time (Yes/No)
2. Slider with time extended

**Comment by SilentSpike** [comment]
We actually do this already:
https://github.com/acemod/ACE3/blob/97d8be94ce64a57c6db6e19a7caf09db299f19a2/addons/medical_statemachine/functions/fnc_handleStateCardiacArrest.sqf#L33-L35

**Comment by DPillow** [comment]
Didn't know about that, thanks!

**Comment by ArwynFr** [comment]
How about a configurable ratio ?
How about different ratios depending on médical skill ?
