### ISSUE TITLE
ace_interactMenuClosed does not fire when menu is closed without KeyUp being raised

### ISSUE THREAD

**Issue by BlackburnUTG** [acemod/ACE3#7381]
ace self-interaction menu background didn't work
background  in interecation menu works fine, but not in self-interaction menu.
plus: if open interaction menu (hold Windows key), and after that hold leftCtrl - backgrond will stuck backgrond stuck on your display even if you not holding any button

**Comment by mharis001** [comment]
The settings for "Interaction" and "Self-Interaction" were split up in the latest update. Double check your settings - the [default is disabled](https://github.com/acemod/ACE3/blob/master/addons/interact_menu/initSettings.sqf#L79).

**Comment by BlackburnUTG** [comment]
yeah.. my bad.. but the stuck bakground bug is still here:
it apears only when your backgrounds are not the same (example: black-self interaction, blur-interaction)
https://www.youtube.com/watch?v=CJ0g_iT6HV0&feature=youtu.be

**Comment by commy2** [comment]
```
IntMenu Background: none
IntMenu Background (self): none
-> works as intended
```

```
IntMenu Background: blur
IntMenu Background (self): blur
-> works as intended
```

**Comment by commy2** [comment]
```
IntMenu Background: none
IntMenu Background (self): blur or black
-> works as intended
```
```
IntMenu Background: blur or black
IntMenu Background (self): none
-> broken as described
```

**Comment by commy2** [comment]
```sqf
["ace_interactMenuClosed", {systemChat str [diag_tickTime, _this#0]}] call CBA_fnc_addEventHandler;
```
Close Self Menu -> fires with 1
Close Inter Menu -> fires with 0
Replacing Self Menu with Inter Menu -> fires with 1
Replacing Self Menu with Inter Menu -> **nothing happens**

**Comment by commy2** [comment]
Analysis shows two problems:
- MenuClosed does not fire when interaction menu is replaced by self interaction menu (i.e. holding down Win, then later holding down Ctrl as well) (major bug)
- black fade effect is repeated despite the screen already blacked out (minor sfx bug)

**Comment by commy2** [comment]
No symetry for MenuOpened event. Fires as expected on open regardless of fresh or replace.

**Comment by commy2** [comment]
Switching the keybinds of Self and Interact menu reverses this effect.
