### ISSUE TITLE
Speed limiter not working

### ISSUE THREAD

**Issue by eagleye100** [acemod/ACE3#739]
Hi guys, i'm not sure if this is issue being already dealt but i experienced speed limiter function is not working.

Also can i ask if you can interact with vehicles yet ?

Thanks in advance :)

**Comment by alganthe** [comment]
I'm able to use this on all vehicles compatible with it as of the ACE3 2015-04-18 master branch
Check if you're not using an other key for it or if you're not pressing shift while pressing delete.

**Comment by eagleye100** [comment]
let me check

**Comment by KoffeinFlummi** [comment]
This was fixed in this commit: https://github.com/acemod/ACE3/commit/9b80245479f32a9fbb358c84a5a1004016c5937d

You're probably using an old build; closing.

**Comment by eagleye100** [comment]
I suggest upon activating speed limiter it should maintain the speed on its own without using W key

**Comment by commy2** [comment]
That doesn't work. It would push the vehicle through buildings etc. I've tried that already, but I see currently no way to do that.
If you find something relyable, then feel free to make a pull request.

**Comment by eagleye100** [comment]
Alright thanks for putting your effort
