### ISSUE TITLE
AI Accuracy Unaffected by Fractures / Open Wounds

### ISSUE THREAD

**Issue by frankplow** [acemod/ACE3#7391]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96 stable`
- **CBA:** `3.13.0`
- **ACE3:** `3.13.0`

**Description:**
When an AI unit receives a fracture or open wound to the arm, their accuracy is unaffected.

**Steps to reproduce:**
1. Cause a fracture on an AI unit either by modifying VAR_FRACTURES or simply shooting them.
2. Observe no decrease in AI accuracy (can be verified with `skill`)

**Expected behavior:**
When AI units have unbandaged wounds or untreated fractures, their accuracy should be reduced.

**Where did the issue occur?**
Editor (Singleplayer)

**Additional context:**
The current mechanism to reduce the accuracy of a unit when it receives a fracture is based around `ACE_setCustomAimCoef`, which wraps the vanilla `setCustomAimCoef`, which has no impact on AI units, only players (to verify, disable ACE advanced fatigue and set the aim coef of AI to something ridiculous like 1000000 and observe no difference in accuracy).

**Comment by frankplow** [comment]
Here is a mission file which more repeatedly recreates the issue (make sure to disable Medical AI in ACE settings):
[ace_ai_accuracy_test.VR.zip](https://github.com/acemod/ACE3/files/4023516/ace_ai_accuracy_test.VR.zip)

It may also be worth mentioning that vanilla ArmA decreases AI units' accuracy as they get more damaged without affecting their skill, however ACE seems to stop this working.

**Comment by zharf** [comment]
in vanilla AI `skill`/`skillFinal` aren't changed with damage to unit either but there is a clear decrease in accuracy as damage on the unit increases. ACE medical currently prevents any damage to be seen by the engine on the unit (`damage` returns 0) until they're dead, which I assume is why their accuracy isn't really affected by limb damage.

**Comment by zharf** [comment]
This might work as a workaround for now:
```sqf
private _updateDamage = {
    params ["_unit"];
    if (!isPlayer _unit && alive _unit) then {
        [_unit, (_unit getHitPointDamage "HitHands") min 0.99] call ace_medical_engine_fnc_setStructuralDamage;
    };
};
["ace_medical_injured", _updateDamage] call CBA_fnc_addEventHandler;
["ace_medical_treatment_bandageLocal", _updateDamage] call CBA_fnc_addEventHandler;
["ace_medical_treatment_splintLocal", _updateDamage] call CBA_fnc_addEventHandler;
```
I think a better solution could be made as currently this doesn't actually scale with the amount or size of wounds on the unit's arms, rather with just whatever ACE deems as appropriate visuals for damaged arms at the time (which seems to be 0 or 0.45, but I might be wrong about that). AI accuracy seems to start to go down at roughly 0.35 damage, so this does make the AI less accurate with damaged arms

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
