### ISSUE TITLE
ACE 3 Surgical Kit cannot be used on Patient

### ISSUE THREAD

**Issue by ErwinNoppe** [acemod/ACE3#7394]
Like written in at the Top ACE 3 Surgical Kit cannot be used on Patient. I tried multiple things and options, but nothing worked. The Option dosent show up both in the medical menu and the 3D Menu.

**Comment by ErwinNoppe** [comment]
Mods:

CBA: 3.13.0
ACE3: 3.13.0

Tried with other mods that does not affect ACE and just loaded ACE and CBA

It appears on Server, Editor, and testrange in the Arenal

**Comment by mharis001** [comment]
What are the medical settings that you are using?

**Comment by ErwinNoppe** [comment]
force force ace_medical_ai_enabledFor = 2;
force force ace_medical_AIDamageThreshold = 0.5;
force force ace_medical_bleedingCoefficient = 0.5;
force force ace_medical_blood_bloodLifetime = 900;
force force ace_medical_blood_enabledFor = 2;
force force ace_medical_blood_maxBloodObjects = 300;
force force ace_medical_fatalDamageSource = 2;
force force ace_medical_feedback_painEffectType = 1;
force force ace_medical_fractures = 2;
force force ace_medical_gui_enableActions = 0;
force force ace_medical_gui_enableMedicalMenu = 1;
force force ace_medical_gui_enableSelfActions = true;
force force ace_medical_gui_maxDistance = 10;
force force ace_medical_gui_openAfterTreatment = true;
force force ace_medical_ivFlowRate = 3;
force force ace_medical_limping = 2;
force force ace_medical_painCoefficient = 1;
force force ace_medical_playerDamageThreshold = 1;
force force ace_medical_spontaneousWakeUpChance = 0.35;
force force ace_medical_spontaneousWakeUpEpinephrineBoost = 1;
force force ace_medical_statemachine_AIUnconsciousness = true;
force force ace_medical_statemachine_cardiacArrestTime = 420;
force force ace_medical_statemachine_fatalInjuriesAI = 0;
force force ace_medical_statemachine_fatalInjuriesPlayer = 0;
force force ace_medical_treatment_advancedBandages = true;
force force ace_medical_treatment_advancedDiagnose = true;
force force ace_medical_treatment_advancedMedication = true;
force force ace_medical_treatment_allowLitterCreation = true;
force force ace_medical_treatment_allowSelfIV = 1;
force force ace_medical_treatment_allowSelfStitch = 1;
force force ace_medical_treatment_allowSharedEquipment = 0;
force force ace_medical_treatment_clearTraumaAfterBandage = false;
force force ace_medical_treatment_consumePAK = 0;
force force ace_medical_treatment_consumeSurgicalKit = 0;
force force ace_medical_treatment_convertItems = 0;
force force ace_medical_treatment_cprSuccessChance = 0.4;
force force ace_medical_treatment_holsterRequired = 0;
force force ace_medical_treatment_litterCleanupDelay = 600;
force force ace_medical_treatment_locationEpinephrine = 0;
force force ace_medical_treatment_locationPAK = 0;
force force ace_medical_treatment_locationsBoostTraining = false;
force force ace_medical_treatment_locationSurgicalKit = 0;
force force ace_medical_treatment_maxLitterObjects = 300;
force force ace_medical_treatment_medicEpinephrine = 0;
force force ace_medical_treatment_medicPAK = 0;
force force ace_medical_treatment_medicSurgicalKit = 0;
force force ace_medical_treatment_timeCoefficientPAK = 1;
force force ace_medical_treatment_woundReopening = false;


Location: Everyone
Rank: Everyone
SurgicalKit: Enabled

**Comment by mharis001** [comment]
This was [discussed in another issue](https://github.com/acemod/ACE3/issues/7369#issuecomment-570443580) - stitching requires wound reopening, which requires advanced bandages. I can see how this can be confusing, PR #7392 will correct this.

**Comment by ErwinNoppe** [comment]
Ok, thanks. Its not confusing its actually simple if you know it xD.

**Comment by mharis001** [comment]
Confusing in that you see bandaged wounds (grey instead of red) and expect to be able to stitch them, however, these aren't actually bandaged wounds but open wounds with amount of zero.
