### ISSUE TITLE
Non-medic players can no longer check pulse/bloodpressure numerical values

### ISSUE THREAD

**Issue by Grtwatkins** [acemod/ACE3#7395]
If I recall correctly in the previous versions there was a setting allowing all players to perform "advanced" medical tasks (start IVs and check pulse with a numerical result rather than a "normal/strong/weak heart rate" result) regardless of their "medic" status. With the rewrite this option seems to have been removed. Is the only way to accomplish this now to make all playable characters "medic" in the unit's settings, or is there a new setting that I'm missing?

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
