### ISSUE TITLE
Ability to unload casualty from a vehicle

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#740]
ACE 3 2015-04-18 master branch build.

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
ace medical: medical settings.

**Description:**
You are able to unload a casualty from inside a vehicle but not from outside.

**Steps to reproduce:**
Get a player or an AI in an unconscious state.
Load the casualty in a vehicle.
Try to unload it from outside.

**Comment by commy2** [comment]
I think this feature isn't implemented yet.
@Glowbal ?

**Comment by esteldunedain** [comment]
I AFAIK the interact_menu part of it is not implemented; I guess the actual unloding function would work from the outside too

**Comment by Glowbal** [comment]
The function for unloading will work fine, regardless of being inside or outside a vehicle. The interface (interaction actions) for it is not implemented yet however.
