### ISSUE TITLE
Use a veriable in unit namespace to enable/disable Medical AI

### ISSUE THREAD

**Issue by leopard20** [acemod/ACE3#7404]
Your current medical AI implementation is a bit frustrating to work with for an AI programmer like myself.
The Medical AI module always gives AI commands and overrides anything I order them to do.

So it would be better if you checked a certain variable (e.g. _unit getVariable ["ACE_medicalAI_Enabled", true]) before giving them commands. That way, AI programmers can find it easier to work with your Medical AI.

The only option right now is to ask users to remove ace_medical_ai.PBO

**Comment by bux** [comment]
Feature Requests go into: #3594

**Comment by bux** [comment]
![image](https://user-images.githubusercontent.com/1235520/71781423-1416dd80-2fcf-11ea-9fdd-61d2b364e820.png)
Try this
