### ISSUE TITLE
Speed limiter locking the wheels at limited speed.

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#741]
ACE3 2015-04-18 master branch

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None

**Description:**
at the limited speed (if you limit it at 40 for example) the  limiter will lock the wheels of the vehicle if you try to change direction.
 from then you are unable to slow down turn or use any input until the speed limiter is off or it decides to let you go.

**Steps to reproduce:**
place a rifleman and a hunter
enter the hunter
drive around at 45 for example and turn the limiter on
try to quickly change direction at 45

be advised that this is more difficult to reproduce at higher speeds.

**video:**
https://www.youtube.com/watch?v=luIfKxCwLtg&feature=youtu.be

sorry for potato quality have potato upload so I had to keep it as light as possible.
 between 0 and 45s it shows the normal behavior the next 15s show the abnormal one.

**Comment by eagleye100** [comment]
i tried few vehicles but i dont have this problem, check your keyboard cable

**Comment by alganthe** [comment]
issue is definitly not comming from me, uploading a video later

**Comment by eagleye100** [comment]
ok i verify you issue is legit, because i was driving punisher at speed around 27km, after reaching speed limiter's max speed you just lose control of vehicle, can't turn or slow down.

**Comment by commy2** [comment]
Damn. It's due to the new PhysX library I believe. I'll see if I can find a work around.

**Comment by commy2** [comment]
I changed something. Please test if that solves the issue.

I know it looks jittery in 3rd person, because forward force is building up and slightly tilds the vehicle in forward direction, but this is the best I can do with the current state of the game.

**Comment by alganthe** [comment]
Just tested it, still happening but I noticed that's it's harder to get "stuck" in the first place.
speaking of the jittery nature of the limiter seems to have been reduce significantly with this fix.
it's butter smooth unless you're accelerating in a huge downwards slope with the limiter set at a low speed.
