### ISSUE TITLE
Usage of Advence Medication where the class change is not possible

### ISSUE THREAD

**Issue by afyldrm** [acemod/ACE3#7412]
I am trying to play a scenario made by someone else with my friends. It is not possible to change player class via scripts at this time. There is options to alter the usage of epinephrine or paks etc. but not for iv's, adenosine, atropine or surgical kit. Our medics suffer heavily because they cannot use any of essential tools available for advance medication, so we are desperately suffering heavy causalities. Is there a way to enable them for anyone or change a player class without altering pbo files, it would save my day. Also having a button to make them available to anyone could be handy feature. Thanks in advance.

**Comment by severgun** [comment]
1) What is the point in medic role if everyone is medic?
2)
 ```
\\ Medic Levels: 0 - None, 1 - Medic, 2 - Doctor
_unit setVariable ["ace_medical_medicClass", 1, true];
```
