### ISSUE TITLE
ACE Medical: Taking damage from backblast even though allowDamage is false

### ISSUE THREAD

**Issue by leopard20** [acemod/ACE3#7429]
allowDamage is set to false, but I take damage from backblast of ATs (tested RPG-42) when, e.g. my back is against a wall.

**Comment by diwako** [comment]
Can confirm.
Over pressure (launcher and tank shots) is using function `addDamageToUnit`, which passes the damage over an event to function `woundsHandlerActive`
Both `woundsHandler` functions do not check if a unit can receive damage.

**Comment by commy2** [comment]
addDamageToUnit and woundsHandler should not check for allowed damage, but the backblast function should.

**Comment by diwako** [comment]
Ironically it checks for allowed damage if ACE medical is not present. I guess this was left in as in the previous medical version you could disable this damage by setting the variable `ace_medical_allowDamage` on a unit to `false`.

**Comment by commy2** [comment]
Yeah, it seems like an oversight from changing the damage handling internals.
