### ISSUE TITLE
PROFILENAME.vars.Arma3Profile has to be deleted after newest ATragMX update

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#743]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None*

**Description:**
PROFILENAME.vars.Arma3Profile has to be deleted after newest ATragMX update
Otherwise you will get this script error at start:

http://cloud-4.steamusercontent.com/ugc/37495060022182864/01004C51802945E384FCA4BADF975160826DECA0/

And you will experience many issues, like self interaction menu not working, blank options menu, yielding game ACE3 non functional,

http://cloud-4.steamusercontent.com/ugc/37495060022314108/33304860B4920D621ADD8659A9C4EDF41B788845/

**Steps to reproduce:**
* *Start the game with -showscripterrors*
* *Open editor, place soldier, preview and try using self interaction menu, or go to options, none will work*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**

**Comment by esteldunedain** [comment]
We need to put some safeguard to delete the outdated atragmx variables from the profile or just use rename them.

**Comment by commy2** [comment]
Same as https://github.com/acemod/ACE3/issues/730
