### ISSUE TITLE
ACE Medical:  Successful CPR immediately sets the heart rate to 80 bpm.

### ISSUE THREAD

**Issue by LockAndLoafCat** [acemod/ACE3#7434]
**Mods (complete and add to the following information):**
- **Arma 3:** v1.96.146114
- **CBA:** v3.13.0
- **ACE3:** v3.13.0

**Description:**
Successful CPR sets the heart rate to 80bpm. This occurs regardless of the success chance of CPR. I have tested on 20%, 40% and 100% chance. 

If this is intentional and not a bug, I suggest changing it as it makes little sense. Currently, one can be unconscious with a perfect heart rate and perfect blood pressure. Realistically, CPR alone will not restart the heart. For the sake of enjoyable gameplay, it should simply bring the heart rate to a low bpm.

**Steps to reproduce:**
- Ensure an unconscious patient has no heart rate and then ensure they are not bleeding.
- Perform CPR until the heart rate returns (setting CPR success chance to 100% will make this easier).
- The patient's heart rate will be set to 80bpm immediately.

**Expected behavior:**
The patient's heart rate after successful CPR should be set to a low heart rate of around 20bpm.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Additional context:**
Personally, I believe a defibrillator would be a good addition to the game as it could be used in medical camps. Again, I do not know if this is a bug or not, but if it is intentional, I suggest amending it.

**Comment by SilentSpike** [comment]
>Personally, I believe a defibrillator would be a good addition to the game as it could be used in medical camps.

So an item to treat cardiac arrest is an idea we also had. It's actually part of the reason for the CPR success chance setting - the thinking being if people want more realistic CPR they can set it to 0 so CPR only extends the cardiac arrest timer and never restarts the heart.

**Comment by LockAndLoafCat** [comment]
> The thinking being if people want more realistic CPR they can set it to 0 so CPR only extends the cardiac arrest timer and never restarts the heart.

Sure, I understand that, and it's obviously good to have more options. But wouldn't it make more sense that instead of CPR not restarting the heart, it simply raises it to a low bpm and epinephrine can be used to increase it further?

**Comment by SilentSpike** [comment]
I haven't looked at this specific code in a while (just contributing to the discussion right now), but if everything is as you describe then I think that's not a bad idea which we could look into. Would be interested to hear other thoughts on this.

**Comment by SilentSpike** [comment]
Looking at the code a bit now, it actually looks like what's meant to happen is on entering cardiac arrest the HR is set to 0 and on exiting it is set to 40 BPM:
https://github.com/acemod/ACE3/blob/9833bfd37d7b9d8b24cb74409e26fef428e8173c/addons/medical_status/functions/fnc_setCardiacArrestState.sqf#L27-L29

CPR success actually just raises the event which tells the statemachine to transition from cardiac arrest to unconsciousness and in that transition the above function is called to set the HR to 40 BPM. From there the vitals loops should take over in updating the HR. If it's jumping straight to 80 BPM then that sounds intentional (as the code comment says "low heart rate if revived").

**Comment by LockAndLoafCat** [comment]
> If it's jumping straight to 80 BPM then that sounds unintentional (as the code comment says "low heart rate if revived").

Like I said, I've had this occur several times in gameplay and without failure in testing. So maybe I'm just a top quality medic. In all seriousness, I've had this happen every time where the heart rate is set to 80 bpm upon successful CPR. I guess the best bet is to wait for others to reply.

**Comment by BaerMitUmlaut** [comment]
>I believe a defibrillator would be a good addition to the game as it could be used in medical camps

A defibrillator does not help against cardiac arrest.

**Comment by ArwynFr** [comment]
> A defibrillator does not help against cardiac arrest.

A defibrillator can be used in case of ventricular fibrillation, to stop the anarchic behavior of ventricles. If artificial circulation was good enough to prevent necrosis, the heart can restore a stable pulse. CPR cannot restore a pulse by itself, it merely acts as an artificial circulation mechanism, preventing necrosis until either defibrillation or death happens.

Of course neither CPR nor defibrillators are useful in case of flat electrocardiograms. However my understanding of ACE cardiac arrest state is that it denotes fibrillation and ragdoll respawn is when pulse went flat.

https://en.wikipedia.org/wiki/Defibrillation
https://en.wikipedia.org/wiki/Cardiopulmonary_resuscitation

**Comment by BaerMitUmlaut** [comment]
Ventricular fibrillation does not happen due to combat injuries, but most commonly due to heart diseases or genetic diseases and is thus completely irrelevant for ACE3.

https://en.wikipedia.org/wiki/Defibrillation#Society_and_culture

**Comment by LockAndLoafCat** [comment]
> A defibrillator does not help against cardiac arrest.

Except it quite literally does - https://www.nhlbi.nih.gov/health-topics/defibrillators

"Different types of defibrillators work in different ways. Automated external defibrillators (AEDs), which are in many public spaces, were developed to save the lives of people experiencing sudden cardiac arrest. Even untrained bystanders can use these devices in an emergency."

**Comment by BaerMitUmlaut** [comment]
Where do you live that cardiac arrests caused by combat injuries are a thing in public places?

In all seriousness, those are useful, because again, they help in certain cases, but not in the ones relevant for Arma.

**Comment by LockAndLoafCat** [comment]
> In all seriousness, those are useful, because again, they help in certain cases, but not in the ones relevant for Arma.

Okay, except the military literally uses AEDs.

"Whether you are a government employee or a military member, you may be called on to respond to a sudden cardiac arrest (SCA)."

"Public access defibrillation programs are ideal solutions for military bases with busy public areas such as hospitals, clinics, housing, barracks, and commissaries."

"Here are some of the reasons why more and more government agencies and military units are investing in AEDs and making early defibrillation a part of their emergency response plans:"

- https://www.cardiacscience.com/solutions/government-military/

**Comment by BaerMitUmlaut** [comment]
It might shock you, but people in the military get heart attacks, too. Please start reading in what cases defibrillation actually works and when those cases appear.

**Comment by LockAndLoafCat** [comment]
> It might shock you, but people in the military get heart attacks, too. Please start reading in what cases defibrillation actually works and when those cases appear.

This isn't even relevant to the original post anymore. The main point of the post is that CPR is setting the heart rate to 80 bpm immediately. I just posted to get that issue solved.

The point about AED was just a suggestion. Really, you shouldn't be going into unconscious states with zero bpm everytime you're shot, but currently, that seems to be the case.

I'm aware of the differences between using AED and CPR, it's not difficult to find. 
- http://www.aed.com/blog/is-it-a-heart-attack-or-cardiac-arrest/

**Comment by BaerMitUmlaut** [comment]
I've marked the irrelevant posts as off-topic.

**Comment by zharf** [comment]
I can't find anywhere in the code where the `VAR_HEART_RATE` would be used as an array.
The heart rate does seem to be around 20-40 when CPR succeeds but it immediately starts acting as if everything's normal and very quickly ramps (couple of seconds) up to target heart rate, which depends on blood volume and perceived pain level.

As I understand it right after being revived the unconscious state handler takes over and the heart rate acts as if cardiac arrest was never really a thing. Technically it seems correct to me (although medically there might be a huge amount of possible issues that wouldn't let the heart do that, but I'm not a medical professional either so I don't know) but maybe the transition is too quick.

https://streamable.com/siuoi

**Comment by SilentSpike** [comment]
A lot has been discussed here, I will say that while use of a defib in combat injury situation may not be entirely realistic, it might still be a good abstraction as folks associate defibrillator with cardiac arrest and it allows a more realistic style of treatment for gameplay (grunts can keep someone alive with CPR until medic arrives with item required to treat). Unless someone can think of a more suitable item to treat cardiac arrest that would fill this role.

Anyway, onto the original issue. @zharf has it right. We may want to look at slowing the ramp up of heart rate, one way we could do that is to just alter the calculation slightly for a set item period after cardiac arrest to emulate a recovering heart.

**Comment by LockAndLoafCat** [comment]
Thank you for the measured response, Spike. I really appreciate the continued feedback. As for the defibrillator, the way I see it, if people don't want to use it, they won't have to. There was a mod that worked with ace before the rewrite, and it was a nice addition for my friends and I to use within a barracks of field hospital. It may not be fully realistic, sure, but this is Arma and no system will ever be perfect.

As for the topic of the original post, I would agree that the speed for it to ramp up should be lowered drastically. I'm not personally a medical professional, but I've been unconscious a few times due to a condition I used to have, and I could not simply jump to my feet upon waking up. Again, really appreciate all the work you guys are doing!

**Comment by ArwynFr** [comment]
In France we have an experimental ECPR device that is portable and used for prehospital care of cardiac arrest since 2017. Takes 10 minutes to install and was successfully used on patients in asystole with efficient CPR for 30 minutes. Might consider it generally available by 2035 and replace the defibrillator with it in ACE ?

https://www.youtube.com/watch?v=34U8mW8EbX8

**Comment by Grezvany13** [comment]
The LUCAS is also used in The Netherlands and can be found in a decent amount of ambulances by now (with success).
In short it's an automated CPR machine, but even EMT uses it in combination with an AED due to the types of cardiac arrests found in "common" life.

To be fair; the people in that video had no urge to perform CPR since it was a dummy, and that demonstration was very chaotic. A better video is https://www.youtube.com/watch?v=8m42t2-8xAY (also a dummy, but more realistic).

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
