### ISSUE TITLE
Language is forced english on server

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#744]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *None*

**Description:**
*Options on multiplayer are in english, some of them are in polish tho*
http://cloud-4.steamusercontent.com/ugc/37495060022591115/94FBF6F60C6A520A8372DC2A55683DC64F9CA60F/

**Steps to reproduce:**
* *Set game language to PL*
* *Start server and join it*
* *Open settings menu*
* *Options are still in english, some are in PL tho*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
Not required I think.

**Comment by jonpas** [comment]
Sure that's not simply because it hasn't been translated yet?

**Comment by gienkov** [comment]
I have that option names in Polish on singleplayer.

**Comment by commy2** [comment]
Maybe the server sends data that is already localized. I've no idea how the interact menu works though. Can you take a look @Glowbal ?

**Comment by gienkov** [comment]
Maybe I have to change my server language? Didn't tried that, did not have to, yet.

**Comment by Glowbal** [comment]
Those should be localized in your config. I will take a look, see what's up.

**Comment by esteldunedain** [comment]
Settings still use the localization of the **server** for all clients. It's a known issue that we need to fix at some point.

**Comment by commy2** [comment]
>Maybe I have to change my server language? Didn't tried that, did not have to, yet.

That would help in your case, but then everyone would have the polish translation instead. Not sure if you want that.

**Comment by gienkov** [comment]
That can be issue for public servers, but we all there are from poland so we doesn't mind. Still, this should use client language I think.
