### ISSUE TITLE
[Friendly Fire Module] Script error on respawn

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#745]
ACE3 Version: 3.x.x

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *ace_friendlyfiremessages*

**Description:**
*After doing respawn in MP game will show script error.*
http://cloud-4.steamusercontent.com/ugc/37495060022606002/4727FB69273A17F9C5E44454B0EC6A85DB4E595D/

**Steps to reproduce:**
* *Launch MP mission with respawn on.*
* *Try respawning, script error shows up*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
This below is what shows on respawn:

16:58:02 Error in expression <ents = _this select 0;
_function = call compile (_this select 1);
_unit = _this >
16:58:02   Error position: <compile (_this select 1);
_unit = _this >
16:58:02   Error compile: Typ code, potrzebny ĹaĹ„cuch
16:58:02 File z\ace\addons\common\functions\fnc_execRemoteFnc.sqf, line 9

**Comment by commy2** [comment]
First of all, what does this:
` 16:58:02 Error compile: Typ code, potrzebny Ĺ�aĹ„cuch`
translate too?

I have a rquest to solve this faster. Can you reproduce this with the debug console enabled?
If it then happens, please c&p
`allVariables missionNamespace`
and
`allVariables player`
bring up.

**Comment by gienkov** [comment]
Type code, needed string, i think. I just discovered that this script error happens when I die too, with respawn of course.

**Comment by gienkov** [comment]
I am using this mission to test ACE3 and ACRE2 in general so feel free to download it and check for yourself:
http://www.armaholic.com/page.php?id=18841

**Comment by commy2** [comment]
I can't reproduce it. Haven't tested that mission though.

**Comment by gienkov** [comment]
Maybe it is related to VTS, will check this.

**Comment by commy2** [comment]
Yes. Please try to reproduce this with only CBA and ACE, INCLUDING on a mission without extended scripting framework.

**Comment by commy2** [comment]
I spawn on the lower left edge of Altis and the mission instantly ends. Am I missing something?

**Comment by gienkov** [comment]
You should launch it from multiplayer (host lan server).

**Comment by gienkov** [comment]
Does not happen on simple mission with:
respawn = 3;

**Comment by commy2** [comment]
OK. Played the mission and pressed RESPAWN 3 times. - No error occured.

After I used up all my lives the mission ended with:

No entry 'mpmissions\__cur_mp.Altis\description.ext/KEGsRscSpectate/controls/menuCamerasLB.ListScrollBar'.

Which is not related to ACE though.

**Comment by gienkov** [comment]
You have to switch one of mission parameters (you change them on slot's screen):

Respawn / Revive - Game basic respawn (Revive off)

**Comment by commy2** [comment]
It would really help if you use the debug console in the mission to print `ace_common_remoteFnc` after the error occurs.

Output on my machine:
`[[user1,0],"{(_this select 0) setCaptive (_this select 1)}",user1]`

Picture on how it should look:
![http://i.imgur.com/9uZEn1I.png](http://i.imgur.com/9uZEn1I.png)

**Comment by gienkov** [comment]
Will try that now.

**Comment by commy2** [comment]
Welp. Thats exactly what I have. I'll try again to reproduce it with move lives.

**Comment by commy2** [comment]
10 respawns later and I still don't get the error. *shrug*

**Comment by gienkov** [comment]
Found it! It is actually Friendly Fire Module that is causing that script error. Check for yourself: create mission with respawn = 3;, place FF Module, get killed by AI - script error :)

**Comment by jaynus** [comment]
Reproduced. the bug is in the friendly fire module in respawn\fnc\fnc_moduleFriendlyFire.sqf

**Comment by commy2** [comment]
Alright. I guess you modified your mission from VTS then I guess. Should've told me that.
