### ISSUE TITLE
ACE Logistics partial repair explodes ERA

### ISSUE THREAD

**Issue by Eogos** [acemod/ACE3#7452]
**Mods (complete and add to the following information):**
- Arma 3 (Latest Stable as of this post
- ACE (3.13.0)
- CBA (3.13.0.191116)

**Description:**
When doing a partial repair on a vehicle with ERA blocks they will blow up after every partial repair, the only way to not have ERA blow up on repair is with a full repair. 

**Steps to reproduce:**
- Destroy the ERA blocks on a vehicle and knock out the gun or something unrelated to the ERA
- Repair the gun or other module
- Observe ERA blocks blowing up again on partial repair

**Expected behavior:**
ERA blocks should either be ignored from these repairs or be fully repairable in the field, not constantly exploding every time any repairs are done to a vehicle

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Log Files:**
- https://gist.github.com/Eogos/f4f7e449a5a65b4ef4b1fc0d3731cfb6

**Additional context:**
The above log shows with CUP loaded but I have tried with just ACE and vanilla as well.

**Comment by commy2** [comment]
>Mods (complete and add to the following information)

Not complete according to log file.

**Comment by Eogos** [comment]
> 
> 
> > Mods (complete and add to the following information)
> 
> Not complete according to log file.

"The above log shows with CUP loaded but I have tried with just ACE and vanilla as well."

**Comment by commy2** [comment]
>Mods (complete and add to the following information):
>    Arma 3 (Latest Stable as of this post
>    ACE (3.13.0)
>    CBA (3.13.0.191116)

I don't see CUP anywhere here.
