### ISSUE TITLE
'ace_medical_fnc_treatmentAdvanced_fullHeal' no longer working

### ISSUE THREAD

**Issue by Kicillof** [acemod/ACE3#7454]
Hi there! I've been using the ace_medical_fnc_treatmentAdvanced_fullHeal to fully heal players using an addaction, just like this (pretty standard): 

> `this addAction ["<t color='#fb0000'>Recibir tratamiento medico</t>","call ace_medical_fnc_treatmentAdvanced_fullHeal"];`

The thing is, since the last update that function doesn't work anymore. This is the error that I'm getting. Did it get replaced by another one?

![imagen](https://user-images.githubusercontent.com/38118007/72214383-6a0fe780-34df-11ea-95ee-2016adccecb9.png)

**Comment by commy2** [comment]
That function was never public, so always subject to change. It is now named differently:
https://github.com/acemod/ACE3/blob/master/addons/medical_treatment/functions/fnc_fullHeal.sqf#L14
