### ISSUE TITLE
Fall Damage is not fatal

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#7459]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96 [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.12.2` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.0` [eg. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
Players seem to be very tanky at taking falls. Vertical drops from 250m does not nock out or kill.
Dropped from 3km up and not dead or even uncon. seems there is a max to fall damage.

**Steps to reproduce:**
1. Eject from helo at increasing hights
1. Observe lack of damage

**Expected behavior:**
Death or uncon

**Where did the issue occur?**
- Dedicated

**Log Files:**
NA

**Additional context:**
NA

**Screenshots:**

**Comment by Gikerl** [comment]
In our testing, we also tested falling from various heights. We noticed that the behaviour is not very consistent. We experienced an equal amount of unconscious and conscious people after the fall. The damage was never fatal no matter the height.

**Comment by hobnob11** [comment]
Was just about to open A bug myself on this, https://www.youtube.com/watch?v=9rr1t4ppjGg
Seems pretty consistent in my testing to be relatively unharmed from fall damage.

**Comment by dedmen** [comment]
I remember jumping from a shipping crane on saturday. I dropped 15m broke my legs, made a loud crunching sound, and continued walking around with broken legs just fine. Thats not that realistic.

**Comment by jonpas** [comment]
Should be improved with #7629, re-open if it continues to not be damaging enough after 3.13.2 releases.
