### ISSUE TITLE
Mini-Spike (AT) is shown as Mini-Spike (AA)

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#746]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *None*

**Description:**
*Mini-Spike (AT) is shown as Mini-Spike (AA) in game. They are translated correctly in stringtable.*
http://cloud-4.steamusercontent.com/ugc/37495060022692634/B6CEAC533905D79FED71BF00BCA9B83ABDDF4011/

**Steps to reproduce:**
* *Open VA and get Spike (AT), but all of them are named (AA).*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*Not required*

**Comment by alganthe** [comment]
Might be an issue on the localization I have no issue here (both names are correct be it in game or in VA)

**Comment by gienkov** [comment]
Did not saw that one, thanks!
