### ISSUE TITLE
Damage to the leg will not cause unconsciousness

### ISSUE THREAD

**Issue by Gikerl** [acemod/ACE3#7465]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.92` 
- **CBA:** `3.12.2`
- **ACE3:** `3.13.0`

**Description:**
Any damage to the legs seems to be irrelevant as long as they are tourniquetted. A player will neither go unconscious nor die from any damage to the legs.  

**Steps to reproduce:**
- Apply  tourniquets to the legs
- Shoot the legs with any weapon
- Wounds pile up but the player will not go unconscious or die

**Expected behavior:**
Players should go unconscious when receiving a sufficient amount of damage to the legs.

**Where did the issue occur?**
- Dedicated Multiplayer

**Additional context:**
We tested the same with tourniquetted arms. Here the player will go unconscious rather quickly as to be expected!

**CBA settings:**
https://gist.github.com/Gikerl/439b214e56fe1e9dcaa53aa504a71ba3

**Video:**
https://www.youtube.com/watch?v=U_N3EMpWfeU

**Comment by Gikerl** [comment]
This seems to be an inconsistent bug. I could not reproduce this today. Yesterday this issue was persistent.

**Comment by TCPicker** [comment]
Not a bug. 
ace_medical_damage\functions\fnc_handleIncapacitation.sqf


> if ((_headDamage > _damageThreshold / 2) || {_bodyDamage > _damageThreshold} || {(_painLevel >= PAIN_UNCONSCIOUS) && {random 1 < 0.1}}) then {[QEGVAR(medical,CriticalInjury), _unit] call CBA_fnc_localEvent; };

If (HeadDamage > Threshold/2, or BodyDamage > Threshold, or Perceived Pain > .5) AND 10% Chance, then Uncon.
Threshold is Managed by Player Critical Wounds Settings

In Human Terms: Incapacitation rules specify only Velocity, Puncture, and Avulsion causing wounds to the Torso or Head have a 10% chance, based on your Threshold settings and the patient's pain, to knock you out.

**Comment by Gikerl** [comment]
Thank you very much for the input!
