### ISSUE TITLE
Backblast damage is too small

### ISSUE THREAD

**Issue by Gikerl** [acemod/ACE3#7467]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.92` 
- **CBA:** `3.12.2`
- **ACE3:** `3.13.0`

**Description:**
The damage caused by the backblast of launchers is minimal and has not managed to knock anyone unconscious. In the previous version of ACE this behaviour was different and regularly caused people to go unconscious when standing in or near the backblast. Right now 3-5 minor cuts and maybe 1-2 avulsion wounds are being caused.

**Steps to reproduce:**
- Stand directly behind the launcher
- Fire the launcher
- Receive 3-5 minor cuts 

**Expected behavior:**
Players should receive more damage and be knocked unconscious.

**Where did the issue occur?**
- Dedicated Multiplayer

**Additional context:**
The same applies for backblast yourself by standing close a wall. Also here barely any damage is being received. 

**CBA settings:**
This CBA setting might contain further mods. But I verified it with just ACE & CBA running.
https://gist.github.com/Gikerl/439b214e56fe1e9dcaa53aa504a71ba3

**Comment by FileUploadAlpha** [comment]
no, it isn't

**Comment by Blutze** [comment]
You should probably mention which weapon you are talking about. The framework allows wildly differing strengths and areas, just like the launchers IRL can range from 50 meters of serious injury to the equivalent of packing peanuts being dropped on your head. At least the 3CB ILAW for instance has always been CS enough to not damage you with a reflection at all.

**Comment by AirShark07** [comment]
i  noticed the same, i tested the RHS RPG it wont damage units behind unless it is way to close, and kill them only if there are straight behind

**Comment by commy2** [comment]
>RHS

Test a vanilla weapon, bavkblast is weapon specific.

**Comment by Gikerl** [comment]
Is this a compat file issue and coould it be adjusted there?

**Comment by commy2** [comment]
Maybe.
