### ISSUE TITLE
Zeus toggle unconscious cannot wake up player anymore which were in a cardiac arrest

### ISSUE THREAD

**Issue by Gikerl** [acemod/ACE3#7468]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.92` 
- **CBA:** `3.12.2`
- **ACE3:** `3.13.0`

**Description:**
When a player goes unconscious and into cardiac arrest, which is then resolved by performing CPR, that player then is just unconscious. The Zeus command 'Toggle Unconscious' will not be able to wake this person up anymore.

**Steps to reproduce:**
- Fix a cardiac arrest on a downed person
- Use the 'Toggle Unconscious' Zeus ability
- The player is still unconscious

**Expected behavior:**
The player should become conscious.

**Where did the issue occur?**
- Dedicated Multiplayer

**Additional context:**
 'Toggle Unconscious' still works to put somebody into the unconscious state and can then also be used to make that player conscious again!

**CBA settings:**
https://gist.github.com/Gikerl/439b214e56fe1e9dcaa53aa504a71ba3

**Comment by Blutze** [comment]
Your settings are including way more mods than you are listing in the issue template, at least one of which extensively deals with zeus modules. On this particular issue posting the rpt would certainly be helpful, on your others you should add them just in case.

Those things are listed in the template for a reason.

**Comment by Gikerl** [comment]
You are completely correct this is an Archilles function that has not been updated yet!
