### ISSUE TITLE
Zeus artillery doesn't spawn shrapnels

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#747]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *None*

**Description:**
*Spawning artillery strikes through Zeus will not cause explosions to spawn shrapnels*
Check out this video I made:
https://youtu.be/aZpzg3qwk10

**Steps to reproduce:**
* *Call in Zeus artillery strike of any kind*
* *Round explode but not shrapnels*

**Where did the issue occur?**
*"Multiplayer"*

**RPT log file:**
Nothing worth looking into inside it.

**Comment by alganthe** [comment]
can't find the mortars in the configs so I guess it hasn't been worked on yet.

**Comment by commy2** [comment]
That might be a limitation on how the projectiles are fired with zeus.
They aren't actually fired (and therefore trigger the approriate `fired eventhandler`, but the projectiles are spawned via `createVehicle`. Don't think we can do anything about it, unless we rewrite zeus.

**Comment by alganthe** [comment]
"unless we rewrite zeus." oh yes go forth and fix the broken PITA that zeus is.

**Comment by commy2** [comment]
I think zeus has more lines of code than ACE has though. (All the ui scripting hurts my brain)

**Comment by SilentSpike** [comment]
You would have to overwrite the module (ModuleOrdnance_F) function (BIS_fnc_moduleProjectile) with your own one

As an aside, the zeus UI framework is actually really nicely designed even if entirely undocumented :stuck_out_tongue_closed_eyes:
Was just complimenting Moricky on it the other week

**Comment by commy2** [comment]
Sure.

After:
`_projectile = createvehicle [_ammo,_posAmmo,[],0,"none"];`
Putting:
`[[player, "", "", "", _ammo, "", _projectile], "ace_frag_fnc_fired", 2] call ace_common_fnc_execRemoteFnc;`
might emulate the behavior. Not tested though.

**Comment by jaynus** [comment]
Duplicates #342

**Comment by esteldunedain** [comment]
No @jaynus, its not a duplicate! Frag requires the config entries, but also that the ammo shells have an attached  PFH. That's the difficult thing to do on Zeus spawned rounds.

**Comment by commy2** [comment]
I'm not sure my work-around is relyable in MP. `createVehicle` is really shitty with `CfgAmmo`. I suspect that the round isn't created when the remote function executes and therefore the projetile will be an null-object.

**Comment by NouberNou** [comment]
`createVehicle` works fine with ammo, its the only way to spawn ammo. You don't need to remotely execute the frag function either, just use the `addManualTrack` function on the projectile. As long as the projectile is local to where you called it all is fine.

**Comment by commy2** [comment]
Didn't know that.

>`_projectile = createvehicle [_ammo,_posAmmo,[],0,"none"];`
`[player, "", "", "", _ammo, "", _projectile] call ace_frag_fnc_fired;`

Might solve the issue then. No idea how to overwrite `BIS_fnc_moduleProjectile` though.

**Comment by Glowbal** [comment]
I will take a look @commy2 We are already doing that for one module function anyway.

**Comment by SilentSpike** [comment]
You can no longer overwrite BIS functions with the latest version of arma. However you can just edit the module in cfgVehicles to use your own function.

**Comment by Glowbal** [comment]
This is done in #784
