### ISSUE TITLE
Fractures values not provided

### ISSUE THREAD

**Issue by thegreattarkhon** [acemod/ACE3#7470]
Hi i love yours ace system but 
some data for new incoming updates not provided.
of example, healing values ​​of fractures according to bandages.

https://hizliresim.com/EOvlmq

the table shown in the link is old.
Fractures rates not here and please add  healing values ​​of fractures according to bandages.
Thanks.
Tarık Kaan Alemdağ

**Comment by TCPicker** [comment]
Fractures are not repaired by bandages. They are repaired by use of SPLINTS.
