### ISSUE TITLE
How to hide interaction menu dynamically?

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#7471]
tell me if there is a variable or a command to disable and enable the interaction menu in scripts (for example, when a player sits or lies, I want to disable the interaction menu with myself)
for example:
 player setvariable ["disable_ace_menu", false];
 player setvariable ["disable_ace_menu", true];
something like that. thanks.

**Comment by commy2** [comment]
```sqf
// init.sqf
["disable_ace_menu", {
    params ["_unir", "_target"];
    _unit != _target || {!(_unit getVariable ["disable_ace_menu", false])}
}] call ace_common_fnc_addCanInteractWithCondition;

// whenever
player setvariable ["disable_ace_menu", false];
player setvariable ["disable_ace_menu", true];
```

**Comment by topden** [comment]
thanks a lot
