### ISSUE TITLE
ACE3 Tagging not working

### ISSUE THREAD

**Issue by SolvageSD** [acemod/ACE3#7476]
I've been using ACE3 for quite some time however, this newest update that has just been released has caused some issue with my game not acknowledging that I have "Spray paint" in my inventory and does not allow me to see it in the Self-interaction menu. I have tested this issue out while only using CBA_A3 and ACE3 and the issue remains. I found this bug while playing Overthrow on Arma 3.

**Comment by djafrika** [comment]
I have the same issue..

**Comment by bux** [comment]
![image](https://user-images.githubusercontent.com/1235520/106383519-e0230d00-63c6-11eb-9305-d98bb2f3eb4c.png)

Works fine for me.
ACE and CBA from Workshop.
New mission.

**Comment by djafrika** [comment]
Only the green spray works...

**Comment by Drofseh** [comment]
They all work for me

![](https://i.gyazo.com/622b203127645229b67a797ffe7644d8.png)
