### ISSUE TITLE
Vehicle crew immune to destruction

### ISSUE THREAD

**Issue by KHunter-Arma** [acemod/ACE3#7480]
(Sorry if this has already been reported, didn't see anything when I looked)

**Mods:**
- **Arma 3:** 1.96.146114 (stable)
- **CBA:** 3.13.0.191116 (stable)
- **ACE3:** 3.13.0.45 (stable)

**Description:**
Vehicle crew gets ejected and does not take damage when their vehicle explodes (is destroyed).

**Steps to reproduce:**
- Create a new mission in the editor with default medical settings and place yourself inside any land vehicle. 
- _vehicle setdamage 1; (Or observe the same effect by placing an enemy with an RPG)
- You will see that you (and any other occupants) only get ejected and you won't die/bleed unless there's a secondary explosion as soon as you eject. The primary explosion while you're inside the vehicle will never inflict any damage.

**Expected behavior:**
A vehicle exploding like it does when it's destroyed in Arma is a catastrophic situation for a crewman/passenger. It should kill everyone on board (like it used to before the medical rewrite).

**Where did the issue occur?**
- Editor (Singleplayer) and Dedicated

**Log Files:**
- https://gist.github.com/KHunter-Arma/042831830eceb06dc996fddc48c5aa45

**Additional context:**

**Screenshots:**

**Comment by zharf** [comment]
See #7305

**Comment by JNoXK** [comment]
Issue still present.

**Comment by commy2** [comment]
Duplicate to the other issue, which seems more insightful.
