### ISSUE TITLE
Reload/Unload vehicles weapons

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#7482]
Add the ability to reload weapons while in the car. Implementations of the slot "loader"

Used on M1A1, Leopard, M60

**Comment by severgun** [comment]
There is also dozens of vehicles with MGs and GLs which should be included in CSW implementation.

**Comment by BaerMitUmlaut** [comment]
#3594

**Comment by PabstMirror** [comment]
CSW was written so that it could eventually be adapted to any vehicle
so this may eventually be possible
