### ISSUE TITLE
CSW Ammo doesnt show up in zeus

### ISSUE THREAD

**Issue by JANXOL** [acemod/ACE3#7486]
When using CSW, zeus is able to spawn the weapons themselves as inventory items (gun and bipod that go into launcher slot), but not the ammo. The ammo cannot be added to inventories of boxes. Since the weapons themselves spawn without ammo it's  making it difficult to use via zeus.

**Solution you'd like:**
Add the ammo items for all CSW weapons to zeus interface so that zeus cann add them to boxes and vehicle cargo. It would also be nice if the proper ammo showed up in arsenal in "ammo" rather than "all ammo" tab if proper CSW weapon is carried in launcher slot - would make it easier to know which ammo is to be used.

**Alternatives you've considered:**
The ammo can be added to boxes via a script but it requires knowing the classname and executing a bit of code via zeus.

**Additional context:**
CSW ammo can be added to soldier loadout via ACE arsenal (all ammo tab), but cannot be added to inventories. If it is manually put into a box the box still appears as if its empty in zeus interface.
Demonstration of this problem should be in this video:

https://youtu.be/BgND5ush2ng

**Comment by Whigital** [comment]
Quick and dirty to get the corresponding mags to show up when static bag equipped:

https://github.com/Whigital/ACE3/commit/8c0c8c6ffc7052f280158689cd224b0f9c10fad2

Haven't had any luck getting either mags or weapons to show up when editing a container through Zeus though. Was thinking adding supplyboxes with the ammo, similar to `mk6_mortar`.

**Comment by JANXOL** [comment]
The weapons do actually show up in inventory in zeus (at least most of them). It's just the ammo that is missing.
