### ISSUE TITLE
Any variable/functions that I can apply to a fence to prevent wirecutters from working on it?

### ISSUE THREAD

**Issue by Drift91** [acemod/ACE3#7487]
I'm wondering if there's any functions similar to `ace_dragging_fnc_setCarryable` or `ace_dragging_fnc_setDraggable` that I can put in the init field of a fence object in Eden to prevent players from destroying it with wire cutters. Last night I spent a bunch of time making sure vehicles can't knock fences over at a base only to have a player immediately cut the fence down almost as soon as the mission started.

**Comment by BaerMitUmlaut** [comment]
You can make an object "occupied" by calling the `claim` function. You could make the object occupied by itself which means nobody could interact with it anymore:
```
[_fence, _fence] call ace_common_fnc_claim;
```
