### ISSUE TITLE
Some modded uniforms makes user invincible

### ISSUE THREAD

**Issue by JasperRab** [acemod/ACE3#7488]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96`
- **CBA:** `3.13.0.191116` 
- **ACE3:** `3.13.0`
- **Armed Forces:UK VIRTUS BODY ARMOUR V1.61**

**Description:**
Uniforms from Armed Forces:UK VIRTUS BODY ARMOUR makes the player and or AI invincible. Seems to have happened after the medical update.

**Steps to reproduce:**
1. Create single player scenario with player and AI using any weapon an any uniform from the mod.
2. Play scenario and shoot the AI and see he's not taking damage after checking his medical menu.
3. Go back to editor and swap AI's uniform to any other vanilla uniform.
4. Play scenario and shoot the AI and see he's taking damage or dies.

**Expected behavior:**
All uniforms shouldn't make the user invincible.

**Where did the issue occur?**
Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional context:**
Also happens for uniforms from There is Only War Mod. 3CB and RHS seem fine, maybe more mods have this issue or not, however would be great knowing where to look as mod creator if this is their fault so we can help them further.

**Comment by PabstMirror** [comment]
could really use the rpt,
ace runs a diagnostic on uniforms to ensure hitpoints are correct

**Comment by JasperRab** [comment]
I had an look before and couldn't see anything happening or showing about it in the logs so didn't post it then.

I hope this is enough. https://pastebin.com/NhFaZwGa

If I need to run it with more logging tell me.

**Comment by celticalliance** [comment]
We had the same issue some time ago while using the 3CB uniforms. Bullets fired by enemy AI seemed to just bounce off and we couldn't get killed.

This was before the medical rewrite btw. And we didn't experience the issue anymore for quite some time already.

**Comment by burn0ut7** [comment]
It seems that ace medical in single player is broken. The fucntion _ace_medical_damage_fnc_determineIfFatal_ doesn't have any of necessary global variables define, they are all nil.

see:
HEAD_DAMAGE_THRESHOLD
ORGAN_DAMAGE_THRESHOLD
HEART_HIT_CHANCE
FATAL_SUM_DAMAGE_WEIBULL_L
FATAL_SUM_DAMAGE_WEIBULL_K

**Comment by LinkIsGrim** [comment]
Since fixed. Hitpoints were broken by bad inheritance.
