### ISSUE TITLE
New settings for explosive min/max timers not working?

### ISSUE THREAD

**Issue by Kavlar** [acemod/ACE3#7495]
After checking, I believe there is to be a new timer added (for demo blocks, etc) and the user cannot set lower than 60 seconds. After looking quite thoroughly I don't see any new settings nor does this appear to work? Any ideas pls. Cheers

**Comment by Whigital** [comment]
`ace_explosives_customTimerMin = <your_min_value (s)>` 
_and_
`ace_explosives_customTimerMax = <your_max_value (s)>`

See the original pull -> https://github.com/acemod/ACE3/pull/6882

Vars are picked up here:
https://github.com/acemod/ACE3/blob/7c296c96ac387e1d5bb7be9f22ffb9bff8177f75/addons/explosives/functions/fnc_openTimerUI.sqf#L18-L19

**Comment by mharis001** [comment]
Closing as question has been answered.
