### ISSUE TITLE
Ctrl+L don't work in planes.

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#7498]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96` [stable]
- **CBA:** `3.13.0` [stable]
- **ACE3:** `3.13.0` [stable]

**Description:**
The key combination "Right Ctrl + L" lifting the pylons does not work in airplanes.

**Comment by commy2** [comment]
Is that a base game action or from ACE?

**Comment by GalNa** [comment]
> 
> 
> Is that a base game action or from ACE?

[See screenshot](https://steamuserimages-a.akamaihd.net/ugc/782999385811441135/65F71CA3816D9DA4E24790350D31A9FD90D113B9/)

**Comment by commy2** [comment]
Well, unbind whatever action you set to Ctrl+L under CONFIGURE ADDONS. Then report which action that was, in case it is a bad default value.

**Comment by GalNa** [comment]
> 
> 
> Well, unbind whatever action you set to Ctrl+L under CONFIGURE ADDONS. Then report which action that was, in case it is a bad default value.

[Yes, it was CBA settings](https://steamuserimages-a.akamaihd.net/ugc/782999385811862543/FC0B1ED2AF0AAD225AEA3C3DAF71CD2586E37EF7/)

**Comment by bux** [comment]
"Right Ctrl" vs. just "Ctrl". Hm, shouldn't be a problem.

**Comment by commy2** [comment]
@GalNa So to be clear, you unbound "Next rail item state" and then you were again able to use "Flaps Up"?

Is Ctrl+L the default value of "Flaps Up" or did you bind it to that yourself?

Why did you report this on this tracker if it has nothing to do with ACE? (As far as I can tell, it does happen without ACE as well).

**Comment by commy2** [comment]
@bux Nope. Vanilla binds have LCtrl and RCtrl. Addon binds only have Ctrl, which covers both keys.

**Comment by bux** [comment]
Oversight or not possible to differentiate?

**Comment by commy2** [comment]
Impossible.

**Comment by GalNa** [comment]
> @GalNa So to be clear, you unbound "Next rail item state" and then you were again able to use "Flaps Up"?
Yes. 

> Is Ctrl+L the default value of "Flaps Up" or did you bind it to that yourself?
RCtrl+L is the defolt value.

> Why did you report this on this tracker if it has nothing to do with ACE? (As far as I can tell, it does happen without ACE as well).
I did not know that, I never played with pure cba

**Comment by commy2** [comment]
A fix I can see is changing these key action handlers:
https://github.com/CBATeam/CBA_A3/blob/master/addons/accessory/XEH_preInitClient.sqf#L5

To pass false, should the player sit in a vehicle in a non firing from vehicle position. That would be a change in CBA though.

**Comment by commy2** [comment]
Change in CBA merged.
