### ISSUE TITLE
ACE 3 features become slow when missions run for longer periods

### ISSUE THREAD

**Issue by celticalliance** [acemod/ACE3#7501]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96` 
- **CBA:** `3.13.0` 
- **ACE3:** `3.13.0`

**Description:**
This issue has been bugging us for quite some time already, and we can't figure out what's causing ACE3 to behave the way it does. We are running an Insurgency mission with quite a few areas to clear and search for ammo caches etc., so it usually runs for a fair amount of time. This is because we are a small group and don't always have time to play. We have noticed that when the mission has run for (I think) one to two weeks that ACE3 starts to act rather odd. One of the best examples of ACE3 not acting as it should is the progress bar of the medical system. The filling up becomes rather jerky and it can take quite a long time to completely fill up, while normally the bar would fill up rather quickly. Other features also become slow to respond. For example checking the ammo with CTRL + R. The icon either shows up very late or not at all. I'm sure there are more examples that I am not aware of at this stage. A reboot of the server fixes everything and ACE3 acts as normal.

I would like to know if anyone knows why ACE behaves this way? Is there something we can do to prevent this issue? For some time we rebooted the server weekly, preventing the issue, but we were not able to finish the mission properly which sort of defeats the purpose of the mission.

**Steps to reproduce:**
- Run a mission for quite a fair amount of time. At least one to two weeks
- ACE3 becomes slow to respond

**Expected behavior:**

**Where did the issue occur?**
- Dedicated

**Log Files:**

**Additional context:**

**Screenshots:**

**Comment by commy2** [comment]
The mission time is recorded in seconds. All numbers in Arma script SQF are stored as floats. If your mission runs for 1E7 seconds, or about 11,5 days, the floating point imprecission affects the mission time. All time based scripts will jump in seconds.

The fix is to restart the mission. There is no feasable solution otherwise. 

Close?

**Comment by celticalliance** [comment]
Right. Thanks for clearing that up.

Yes, this issue may be closed.
