### ISSUE TITLE
M992 Illumination IR Flare is Visible without NVGs

### ISSUE THREAD

**Issue by Lairdd1989** [acemod/ACE3#7511]
**Mods:**
- **Arma 3:** `1.96` [stable,]
- **CBA:** `3.13.0` [stable]
- **ACE3:** `3.13.0` [stable]

**Description:**
The M992 Illumination IR Flare is Visible without NVGs  
`ACE_40mm_Flare_ir`

**Steps to reproduce:**
- In any scenario at night
- Fire M992 Illumination IR Flare from any UGL rifle
- See Flare round burn white without NVGs

**Expected behavior:**
The M992 Illumination IR Flare only visible when using NVGs.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- N/A

**Additional context:**
The Round behaves the same as the Vanilla IR UGL Round  
`UGL_FlareCIR_F`

**Screenshots:**
https://imgur.com/a/8yj3FWx

**Comment by dedmen** [comment]
https://github.com/acemod/ACE3/blob/60a901bf103b841877b38a723241e7fe5cea168b/addons/grenades/CfgAmmo.hpp#L33

Not sure what else to do.

**Comment by commy2** [comment]
Nothing else can be done. This bug should apply to all nvg only flares in game. Anyone bother to check?

**Comment by Lairdd1989** [comment]
So this is a BI Fault?

**Comment by commy2** [comment]
I said idk.

>Anyone bother to check?

**Comment by Lairdd1989** [comment]
This seems to work as intended now.
The Vanilla IR round still has this issue but M992 Illumination IR Flare does provide NVG only illumination.
