### ISSUE TITLE
Replace ACE medical cheat sheet in the wiki with an updated version

### ISSUE THREAD

**Issue by ComboTombo** [acemod/ACE3#7513]
**Is your enhancement related to a problem?**
A clear and concise description of what the enhancement entails. Ex. [...] would improve user experience.

Replace the medical cheat sheet in the wiki with [this](https://i.gyazo.com/e25c6c032ffe0af13d7c4ce32c2c55d4.png) to update information since there are multiple cheat sheets floating around

**Solution you'd like:**

[this](https://i.gyazo.com/e25c6c032ffe0af13d7c4ce32c2c55d4.png)

**Alternatives you've considered:**
A clear and concise description of any alternative solutions or ideas you've considered.

**Additional context:**
Add any other context or screenshots about the enhancement here.

**Comment by zharf** [comment]
honestly, I think these cheat sheets should show the estimated reopen time, otherwise why would you ever use packing bandages over elastics?

Here's what I made for my unit to refer to: https://docs.google.com/spreadsheets/d/1HrECNl92LXAj_AlAhPCvLDduKHzlPEOiZ9euIsvjrzc/

**Comment by commy2** [comment]
Should be SVG. If not, a higher resolution picture. Exported by print to file, and not with a screencap tool.

**Comment by TCPicker** [comment]
Ace Medical Chart: https://docs.google.com/spreadsheets/d/1qihwEGGbp9AwTGpDHOaZ6ocrNiLOlIoVrNdJPu22Lww/edit?usp=sharing
@zharf @ComboTombo 
You both could stand to include more information

**Comment by frankplow** [comment]
I wrote a script to extract bandages information from the .hpp into a .csv a while back and used it to make this: https://docs.google.com/spreadsheets/d/1zBd1OEOhSKvBhNrj5x6j1ldHgayKx7oUXBhcGxLoImw/edit?usp=sharing
Not as pretty as the ones others have posted but the avg. time to reopen might be useful info to have on there.
