### ISSUE TITLE
ACE Interaction while unconscious

### ISSUE THREAD

**Issue by GCrane93** [acemod/ACE3#7514]
During this op I was shot and lost a lot of blood, leaving me in an unconscious state while the medics were waiting for me to wake up, and use a personal aid kit.
During this time, and sometime previous games I have been able to "look around" being only aware of this by the shac tac in game overlay, if a player was in close enough vicinity to my body I was able to tap them on the shoulder, as an example.
[Historical Mod Pack.txt](https://github.com/acemod/ACE3/files/4167692/HistoricalModPack.txt)
![Ingame screenshot showing ACE Interaction while down](https://user-images.githubusercontent.com/6993169/73977872-0e404f00-4923-11ea-8e40-edce0e1268bd.jpg)

**Comment by SilentSpike** [comment]
This sounds like it's probably a duplicate of: #7448

Which should hopefully be fixed in latest master branch (and next release), just needs to be confirmed in-game.

**Comment by GCrane93** [comment]
huh, apologies - didn't see this when searching for "unconscious" or in the "this looks like" part.. will close
