### ISSUE TITLE
Ace cookoff

### ISSUE THREAD

**Issue by ianderrick80** [acemod/ACE3#7525]
Hi, I’ve been trying to get vehicles to cook off (burning from inside out and flames spewing out) but I can’t seem to get this feature to perform. I’m not sure if this is a bug or if this feature was taken out? Could anyone help I would appreciate it!

My mods installed with ace3 are:
Blastcore edited by foxtrot with ace compatibility 
Jsrs sound mod
Rhs mods with ace compatibility
Vcom with ace compatibility

**Comment by TheCandianVendingMachine** [comment]
afaik the issue with the current cook-off implementation is that it makes some vehicles invulnerable. Because of that its disabled by default

**Comment by ianderrick80** [comment]
> afaik the issue with the current cook-off implementation is that it makes some vehicles invulnerable. Because of that its disabled by default

Is there a way to re-enable it manually?

**Comment by ianderrick80** [comment]
<script src="https://gist.github.com/ianderrick80/130677c479cd196f872b9c1ddfafb3fe.js"></script>

**Comment by Blutze** [comment]
https://github.com/acemod/ACE3/blob/master/addons/cookoff/functions/fnc_handleDamage.sqf#L28

I guess the left hand part of the AND is only true for the "players only" setting, and not for "players and ai". Should probably be changed to `setting > 0` instead of `setting == 1`.

**Comment by commy2** [comment]
I think it is already fixed in https://github.com/acemod/ACE3/pull/7419.
Close as duplicate?
