### ISSUE TITLE
Crew does not take damage while inside WY-55 Czapla

### ISSUE THREAD

**Issue by chakflying** [acemod/ACE3#7526]
**Mods:**
- **Arma 3:** `1.96`
- **CBA:** `3.14.0`
- **ACE3:** `3.13.0`

**Description:**
Crew does not take damage when getting shot inside the WY-55 Czapla

**Steps to reproduce:**
- Place down a WY-55 Czapla in the editor
- blast the pilot with a 50cal until the hull is red but the pilot is still fine

**Expected behavior:**
He should take damage.

**Where did the issue occur?**
- Editor (Singleplayer)

**Comment by commy2** [comment]
The pilot (anyone wearing this uniform) is immortal with or without vehicle.
