### ISSUE TITLE
removeAllMissionEventHandlers "Draw3D" breaks ACE Interact

### ISSUE THREAD

**Issue by Herbiie** [acemod/ACE3#7530]
**Mods (complete and add to the following information):**
Latest ACE/CBA/ArmA - No Dev

**Description:**
If you use the script
removeAllMissionEventHandlers "Draw3d"

You will also disable the ACE Interaction UI.

This isn't documented anywhere and would be nice to have known and saved me many hours of bug hunting.

**Comment by commy2** [comment]
This is pretty obvious. It is also not a bug in ACE, as `removeAllMissionEventHandlers` breaks all mods, scripts, missions, campaigns, w/e that uses mission event handlers. If anything, this should be documented on the BI wiki.

**Comment by Herbiie** [comment]
Except that most things don't use missionEventHandlers

**Comment by commy2** [comment]
And nobody should use removeAllX.
