### ISSUE TITLE
For some non-vanilla statics, "Check ammo" doesn't work right

### ISSUE THREAD

**Issue by klausman** [acemod/ACE3#7540]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96.146114` (current stable)
- **CBA:** `3.14.0`
- **ACE3:** `3.13.0`
- [RHS:AFRF](https://steamcommunity.com/sharedfiles/filedetails/?id=843425103): `v0.5.0`

(plus the current version of TFAR, 1.0.325, but that shouldn't matter here)

**Description:**
On an XM307 (from the base game), the check ammo display looks like it does on rifles and pistols:

https://i.imgur.com/VEzriXV.png

i.e. it has Ammo type and a bar showing how much ammo is left. Doing the same on a KORD from RHS:AFRF yields only the ammo type, `1x` and no bar:

https://i.imgur.com/zzQp9p7.png

I am not sure if this is an overflow problem (the longer test with 1x in it pushing the bar to an invisible area) or if the RHS statics have weird magazine configurations.

**Steps to reproduce:**

Place a KORD in the editor, go into mission, use ACE interact to check the ammo of the KORD.

**Expected behavior:**

A bar showing the state of the KORD magazine.

**Where did the issue occur?**
- I can reproduce this in editor-launched, server side and single player missions.

**Comment by TheCandianVendingMachine** [comment]
Either ARMA introduced a bug in a recent update or this was broken since forever. For some reason `currentMuzzle weapon` doesn't ever return the correct value for static weapons without a person inside, and even if it does have a person inside it still wouldn't work. I'll fix this soon

**Comment by commy2** [comment]
>For some reason currentMuzzle weapon doesn't ever return the correct value for static weapons without a person inside

Has been the case for a long time. Should report something after you leave it though.

**Comment by PabstMirror** [comment]
for a long time currentWeapon was also broken until a unit entered and exited the weapon, 
they fixed that but I guess it's still broken for muzzle
