### ISSUE TITLE
Medical AI - Morphine overdosing

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#7551]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96`
- **CBA:** `3.14.0`
- **ACE3:** `3.13.0`

**Description:**
AI overdoses with Morphine when healing himself.

**Steps to reproduce:**
- Damage an AI
- Stabilise AI
- Watch AI overdoes himself and enter cardiac arrest as soon as he wakes up an heals himself.

**Expected behavior:**
AI not overdosing.

**Where did the issue occur?**
- Dedicated

**Log Files:**
- N/A

**Additional context:**
/

**Screenshots:**
/

Related to #4835.

**Comment by jonpas** [comment]
Not sure if pain scale got changed and check [here](https://github.com/acemod/ACE3/blob/master/addons/medical_ai/functions/fnc_healingLogic.sqf#L102) is using an old one (`0-1`)?

**Comment by LinkIsGrim** [comment]
Is this still an issue? Can't reproduce.
