### ISSUE TITLE
Bug of the bleeding preassure

### ISSUE THREAD

**Issue by hey123456789** [acemod/ACE3#7553]
**Mods (complete and add to the following information):**
- **Arma 3:** 1.96.146114
- **CBA:** 3.14
- **ACE3:** 3.13.0

**Description:**
Hello, we are a group of people that plays arma 3 as a military simmulation. Well, the last mission we did, we use the newest version of ace3. We configured all the medical configuration as we think it was the best. 
1. When someone of us get shooted we automaticly tried to heath his injures because the bleeding it's something important that should be trated as fast as u can. Well, the last day, when we used the last ace 3 version, when someone got shooted and healed, the pressure values were normals, but if you wait some seconds, it decrease a lot. Example: a person of us got injured and the bleading pressure was something like 100/70, but in just seconds (without been bleading) the pressure got down to 60-65. Do you know any solution to this? 
The bleading tase is 0.3.
2. If your hearth beat were less than 60 you can't go up of this value. If you inject your self 50 ephinefrines you will never get more cardiac pulsations.

**Steps to reproduce:**
I think this is caused of a bad configuration so I think this is just my problem because I didn't seen anyone with this issue. 

**Expected behavior:**
I expected that everything was fine. But bro... in the last version if you got less than 75 of bleed presure, you will get unconscious.

**Where did the issue occur?**
singleplayer and multiplayer

**Log Files:**
- I don't know what to put in here. I am new over here and I don't know how these things work.
Sorry for my bad english
If you need more information please let me know, thank you

**Comment by Blutze** [comment]
> The bleading tase is 0.3.

Not sure what this is supposed to mean. Everything else is reasonably clear.

For the log files:
- After the mission, have the affected players paste `%userprofile%\AppData\Local\Arma 3` into the address field in windows explorer. 
- There will be up to ten .rpt files with a date and time in their filenames.
- Find the one with the timestamp matching your mission.
- Open the file with any text editor.
- Upload the contents of the file to something like [pastebin](pastebin.com), then link them here.

For this particular issue the settings export could also be helpful. Open the addon settings menu ingame, switch to the server tab, click Export, copy that text and upload it the same way as the .rpt files.

**Comment by LinkIsGrim** [comment]
Stale, can't repro
