### ISSUE TITLE
ACE3 6,5 Magazines only for one of the 3 MXM

### ISSUE THREAD

**Issue by Laid3acK** [acemod/ACE3#7559]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96` [stable]
- **CBA:** `3.14` [stable]
- **ACE3:** `3.13.0` [stable]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
The ACE3 magazines (Cred, Scenar) are only available for the `arifle_MXM_F`, not the `arifle_MXC_Black_F` and the `arifle_MXM_khk_F`. They should either be available for all three, or for none of them.

**Steps to reproduce:**
- Go to the Virtual Arsenal and check.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by commy2** [comment]
Is this sentence descriptive or prescriptive?
If the former, I wonder how, and if the later I ask: "Why?"

**Comment by Laid3acK** [comment]
I don't know how you want to manage that.
Personally i'm not sure that the `class CBA_65C_AR10` is the best solution actually.
How the MXMs could share their mags with the chinese QBU ?

**Comment by commy2** [comment]
Okay, but you skipped the "why".

**Comment by Laid3acK** [comment]
As i did with the Contact rifles https://github.com/acemod/ACE3/pull/7156, i would like to completely clean up the `magazines[]` with this PR https://github.com/acemod/ACE3/pull/7557
