### ISSUE TITLE
ACE Compats RHS missing Barrel Length/Twist Values.

### ISSUE THREAD

**Issue by Lazejun** [acemod/ACE3#7560]
**Mods (complete and add to the following information):**
- **Arma 3:** [stable]
- **CBA:**  [stable]
- **ACE3:**  [stable]
- **RHSUSAF:** [0.50]
- **RHSAFRF:** [0.50]
- **RHSSAF:** [0.50]
- **RHSGREF:** [0.50]
- **ACE Compats RHSUSAF/AFRF/GREF:** [Stable]
**Description:**
The Ace Compats are missing Values for the Following Weapons:
Barrel Twist and Barrel Length.
Ingame Name/Classname

RHS USAF:
Mk17 MOD 0 (STD) "rhs_weap_mk17_STD".
Mk17 MOD 0 (LB) "rhs_weap_mk17_LB".
Mk17 MOD 0 (CQC) "rhs_weap_mk17_CQC".
Scar-H (USA/CQC) "rhs_weap_SCARH_USA_CQC".
Scar-H (USA/LB) "rhs_weap_SCARH_USA_LB".
Scar-H (USA/STD) "rhs_weap_SCARH_USA_STD".

RHS Gref:
L1A1 (Polymer) "rhs_weap_l1a1".
L1A1 (Wood) "rhs_weap_l1a1_wood".
M1 Garand "rhs_weap_m1garand_sa43".
MG42 "rhs_weap_mg42".
MP44 "rhs_weap_MP44".
VHS-D2 "rhs_weap_vhsd2".
VHS-D2 (CT-1.5x) "rhs_weap_vhsd2_ct15x".
VHS-D2 (VHS-BG) "rhs_weap_vhsd2_bg".
VHS-D2 (VHS-BG/CT-1.5x) "rhs_weap_vhsd2_bg_ct15x".
VHS-K2 "rhs_weap_vhsk2".

RHS SAF:
SCAR-H (CQC) "rhs_weap_SCARH_CQC".
SCAR-H (CQC) "rhs_weap_SCARH_FDE_CQC".
SCAR-H (LB) "rhs_weap_SCARH_FDE_LB".
SCAR-H (LB) "rhs_weap_SCARH_LB".
SCAR-H (STD) "rhs_weap_SCARH_STD".
SCAR-H (STD) "rhs_weap_SCARH_FDE_STD".
**Steps to reproduce:**
Check Ace Arsenal Weapon State/Range Cards.

**Expected behavior:**

It should have their Values but its missing them, allready checked for Classnames and the normal modelname, Compats are completly missing them.

**Comment by dedmen** [comment]
barrel length/twist is missing.
RailHeightAboveBore too?

**Comment by commy2** [comment]
Then add them? How is this a bug.
Hosting the RHS compat files was a mistake.

**Comment by Lazejun** [comment]
Well to be fair their wasnt realy a Missing things Category :P

**Comment by commy2** [comment]
Feature request imo

**Comment by PabstMirror** [comment]
Fixed by #7702
