### ISSUE TITLE
Deactivate vehicle explosions

### ISSUE THREAD

**Issue by YuriZoko** [acemod/ACE3#7573]
Hello,

How to deactivate vehicle explosions? At the slightest shock my vehicles explode.

**Comment by commy2** [comment]
Mine don't.

**Comment by YuriZoko** [comment]
I tried with version 3.13, the vehicles explode at the slightest shock.

I tried with the 3.11, the vehicles don't explode

**Comment by commy2** [comment]
I tried with 3.13 and remember 3.11, and they never explode like that.

**Comment by YuriZoko** [comment]
in 3.11 I rush against a tree at 130km / h the vehicle does not eject me and does not explode. in 3.13 with the same vehicle and the same speed, the vehicle ejects and explodes

**Comment by commy2** [comment]
And without ACE?

**Comment by Whigital** [comment]
> 
> At the slightest shock my vehicles explode.

>
>in 3.11 I rush against a tree at 130km / h the vehicle does not eject me and does not explode. in 3.13 with the same vehicle and the same speed, the vehicle ejects and explodes

I sense a discrepancy here ....
