### ISSUE TITLE
People dying instantly

### ISSUE THREAD

**Issue by azuriph** [acemod/ACE3#7574]
**Mods (complete and add to the following information):**
- **CBA:** 3.14
- **ACE3:** 3.13
**Description:**
People die instantly instead of going unconscious (no matter how he died).

**Steps to reproduce:**
-Install CBA and ACE,go to a dedicated server and try to shoot on a player 

**Expected behavior:**
People going unconscious so the medics can save him

**Where did the issue occur?**
- Dedicated (i tried with an older version of ace, but nothing changed)

**Comment by bux** [comment]
please fill out the issue template

**Comment by azuriph** [comment]
up

**Comment by commy2** [comment]
I don't see it.

**Comment by commy2** [comment]
Sorry, I meant this requires an RPT file.

**Comment by YuriZoko** [comment]
https://streamable.com/glwqq

**Comment by commy2** [comment]
I don't.
Videos are useless. Needs RPT file.

**Comment by YuriZoko** [comment]
RPT Server : https://paste-me.net/onuna
RPT Client : https://paste-me.net/miyef

On editor it work... On AltisLife 5.0 doesn't work. I have a new video if u want

https://streamable.com/ukhe8

**Comment by bux** [comment]
@YuriZoko That's not the complete RPT. We need the complete content of that file.

**Comment by YuriZoko** [comment]
https://paste-me.net/wafat

**Comment by commy2** [comment]
![https://raw.githubusercontent.com/acemod/ACE3/c77ad64c63cb5008f606cf8c04896f546542c700/docs/img/wiki/development/issue_flowchart.png](https://raw.githubusercontent.com/acemod/ACE3/c77ad64c63cb5008f606cf8c04896f546542c700/docs/img/wiki/development/issue_flowchart.png)

**Comment by YuriZoko** [comment]
Without any mod juste ace + cba

server : https://paste-me.net/qabic
Client : https://paste-me.net/yaxic

**Comment by bux** [comment]
Do they still die instantly? with just cba and ace? if yes, please don't use the altis life mission but create an empty one.

**Comment by YuriZoko** [comment]
Without Altis Life no die instantly, with Altis Life die ...

**Comment by YuriZoko** [comment]
With Altis Life mission on Editor no die instantly, in dedicated server with same mission, die instantly, why

**Comment by bux** [comment]
Please contact the author of this Altis Life mission. It's not an ACE issue then.

**Comment by commy2** [comment]
I think it is AL using HandleDamage event handler with return value, thus killing the AI with Engine damage despite ACE.

There is probably a way to skript around this, but idk anything about AL, so I can't write anything for sure.

Close?

**Comment by bux** [comment]
@commy2 we still need to wait for OP. Yuri only hijacked this issue 😄

**Comment by YuriZoko** [comment]
https://prnt.sc/recjjz 

Death from fatal injury => never

a ball and the player dies

**Comment by commy2** [comment]
Did you not read my comment, Yuri? AL mission is killing you. Nothing we can do about it, even if we tried.

**Comment by YuriZoko** [comment]
okay, thanks dude
