### ISSUE TITLE
Unable to open self-interaction menu when standing on undigable ground with Entrenching tool in inventory.

### ISSUE THREAD

**Issue by rundabollen** [acemod/ACE3#7576]
**Mods**
- **Arma 3:** `1.96.146114` Main Branch
- **CBA:** `3.14.0.200207` 
- **ACE3:** `3.13.0`
- **CUP Terrains - Core:** `1.14.0`
- **CUP Terrains - Maps:** `1.14.0`
- **CUP Terrains ACE Compatibility:** `1.12.0`

**Description:**
Standing on "undigable" ground with the entrenching tool in player's inventory will cause the self-interaction menu not to appear on key press and in singleplayer will show the error message:
` Error position: <&& {[ACE_player,  _target,  []] call ace>
 Error &&: Type Number, expected Bool`

**Steps to reproduce:**
-Place a player unit and add the Entrenching Tool to player's inventory
-Stand on ground unfit for digging (see Additional context)
-Attempt to open self interaction menu
-Observe menu elements not appearing

**Expected behavior:**
Self interaction menu to display correctly but, as for most undigable surfaces, not display the Entrenching Tool options.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Log Files:**
- .rpt file of attempting to self interact on CUP map proving grounds: https://pastebin.com/1nqSvSpe

**Additional context:**
One issue seems to be that only certain undigable ground is affected, myself I have only seen the problem on CUP maps (Proving Grounds and the Sahrani Maps) but acording to Commy2 in the Slack the issue has been reported to occur on Altis as well. (Reason I'm posting it here rather than to CUP's error tracker). Coordinates used for the test of the .rpt file: Proving Grounds, [713.768,1199.34,0.00143814].

**Comment by severgun** [comment]
Hmm there is no such condition statement in ACE. Isn't it?
https://github.com/acemod/ACE3/search?q=canDigTrench&unscoped_q=canDigTrench

**Comment by PabstMirror** [comment]
Should be fixed by #7516
