### ISSUE TITLE
Endless loading on medical error

### ISSUE THREAD

**Issue by smitt14ua** [acemod/ACE3#7577]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96.146114 stable`
- **CBA:** `3.14.0.200207 stable`
- **ACE3:** `3.13.0.45 stable`
- **TFAR:** `0.9.12 stable`
- **RHSAFRF:** `0.5.0 stable`
- **RHSGREF:** `0.5.0 stable`
- **RHSSAF:** `0.5.0 stable`
- **RHSUSAF:** `0.5.0 stable`

**Description:**
Endless loading. Randomly this error happens when start SP mission via editor.
`[ACE] (medical_engine) ERROR: Unit not local or null`

**Steps to reproduce:**
- Go to editor
- Place vehicle and unit inside it
- Click to play and wait randomly error

**Expected behavior:**
Display error message and show me previous screen.

**Where did the issue occur?**
- Editor (Singleplayer)

**Log Files:**
- [pastebin](https://pastebin.com/AZZ3uYzF)

**Comment by commy2** [comment]
Can you explain this in one or two sentences? I mean, seriously, what the hell.

Btw, just because the last message is from ACE does not mean that the error is caused by ACE. This is why you're supposed to try with only CBA and ACE in an empty mission first.

**Comment by smitt14ua** [comment]
I created a mission, put the bot in the car and launched the mission. There was an endless loading screen.
It was happened twice and all time last message from ACE medical about error.

I do not know what else to write.
What I must to think after second message about this error?

Maybe error handle only reporting about error and doesn't stops some loop (or FSM)?

**Comment by commy2** [comment]
Try with only CBA and ACE in an empty mission first.

>and all time last message from ACE medical about error.

Doesn't mean anything.

**Comment by commy2** [comment]
>Maybe error handle only reporting about error and doesn't stops some loop (or FSM)?

That message does not stop any loop.
