### ISSUE TITLE
CSW - Script Error for Some (All?) Ammo Types

### ISSUE THREAD

**Issue by 654wak654** [acemod/ACE3#7579]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96`
- **CBA:** `3.14.0`
- **ACE3:** `3.13.1.rc1` _(With lots of modules removed, check rpt)_
<details>
<summary>Rest of the mods</summary>

- **A3AdditionalMeasurements:** `1.3.0`
- **ACEX:** `3.5.1.rc1` _(With lots of modules removed, check rpt)_
- **AI Driving Control:** `2.6`
- **Advanced Weapon Mounting:** `1.0.4`
- **ArmaForces - No Actions:** `27APR2019`
- **CUP ACE Compatibility - Terrains:** `1.12.0`
- **CUP ACE Compatibility - Vehicles:** `1.12.0`
- **CUP ACE Compatibility - Weapons:** `1.13.0`
- **CUP Terrains Core:** `1.14.0`
- **CUP Terrains Maps:** `1.14.0`
- **CUP Terrains Maps_2.0:** `1.0.0 `
- **CUP Units:** `1.13.0`
- **CUP Vehicles:** `1.13.0`
- **CUP Weapons:** `1.13.1`
- **DUI:** `1.6.0`
- **FRXA's TFAR Extra Retextured Equipment:** `01JAN2019`
- **Immerse:** `2.23`
- **JSRS:** `CE.19.1119`
- **LambsDanger:** `2.2.1`
- **NIArms Core:** `1.51`
- **NIArms FN Minimi:** `1.4`
- **NIArms HK416 :** `1.0`
- **Suppress:** `2.04`
- **TFAR:** `1.-1.0.325`
- **ZEN:**  `1.6.1`
</details>

**Description:**
Trying to rearm a mk6 mortar from an ammo truck causes a script error while using the "take x ammo" action. No ammo is given to the player.

**Steps to reproduce:**
- Use the CSW bags to assemble a mk6 mortar.
- Create an ammo truck by it.
- Try to use the ammo truck's rearm actions.

**Expected behavior:**
To actually receive CSW ammo.

**Where did the issue occur?**
- Dedicated

**Log Files:**
https://pastebin.com/1FX6hQBx

**Additional context:**
Here is the specific error message:
```
22:47:12 "[ACE] ERROR: Undefined Ammo [ : ]"
22:47:12 Error in expression <;
private _fullMagazines = floor (_ammo / _carryMaxAmmo);
private _bulletsRemain>
22:47:12   Error position: </ _carryMaxAmmo);
private _bulletsRemain>
22:47:12   Error Zero divisor
22:47:12 File z\ace\addons\csw\functions\fnc_reload_handleReturnAmmo.sqf..., line 24
```
And the server's csw settings:
```
// ACE Crew Served Weapons
force force ace_csw_ammoHandling = 1;
force force ace_csw_defaultAssemblyMode = true;
force force ace_csw_dragAfterDeploy = false;
force force ace_csw_handleExtraMagazines = true;
force force ace_csw_progressBarTimeCoefficent = 0.7;
```

**Comment by PabstMirror** [comment]
Not using mk6 pbo, which is where `ACE_1Rnd_82mm_Mo_HE` is defined

**Comment by commy2** [comment]
Should either add as dependency or handle this case imo.

**Comment by xxsogramboxx** [comment]
Why is finding the correct ammo type for CSW static weapons so difficult. You literally have to go on wikipedia and search up Kornet missiles on wikipedia instead of just searching "CSW" in the arsenal in magazines. It makes these weapons way more difficult to use than they need to be.

**Comment by commy2** [comment]
Please keep unrelated feedback out of the issue tracker.
