### ISSUE TITLE
IR Grenades detaching on unconscious

### ISSUE THREAD

**Issue by dedmen** [acemod/ACE3#7580]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96`
- **CBA:** `3.13.0`
- **ACE3:** `3.12.1`

**Description:**
When you get shot uncon, the attached IR gren floats in the air above you, afaik not a problem pre-rewrite.

**Steps to reproduce:**
TBD, reported by my unit, atleast 6 people experiencing same issue.

**Expected behavior:**
IR gren stays attached on player lying on ground

**Where did the issue occur?**
- Dedicated

**Log Files:**
Need to repro myself, don't expect script errors ho.

**Additional context:**
TBD

**Screenshots:**
TBD

**Comment by Whigital** [comment]
Also observed pre-rewrite when players ragdoll (killed). Strobe stationary mid-air, body on the ground. 

PhysX related ?

**Comment by dedmen** [comment]
> Also observed pre-rewrite when players ragdoll (killed). Strobe stationary mid-air, body on the ground.

That's the same thing then, you ragdoll when going uncon. Maybe we need to reattach?
If the strobe "dies" when you ragdoll and we loose the reference to it, we should detach before ragdoll, and reattach on ground?

**Comment by Beeperz** [comment]
Still no solution? Have this issue, is there some temporary solution? May be disable ragdoll (somehow?), etc.

**Comment by Beeperz** [comment]
IDK, i have write fix loop to delete them by my mission, so can't say.
My code:
`{if (isNull attachedTo _x) then {deleteVehicle _x;};} forEach entities [["ACE_IR_Strobe_Effect"], [], true, true];`

**Comment by johnb432** [comment]
Do you mind testing without your code?

**Comment by johnb432** [comment]
Given that I can't replicate it and that I haven't heard anything more on this, I'm considering this to be resolved. If it isn't, I can reopen the issue.
