### ISSUE TITLE
Artillery Rangetables Wrong

### ISSUE THREAD

**Issue by Kyjo12347** [acemod/ACE3#7581]
**Mods (complete and add to the following information):**
Arma 3
CBA
ACE3
RHSUSAF
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
When trying to manual fire any 105mm or 155mm howitzer, whether towed or self propelled, all the range table values are the same no matter the gun and are all severely off target as well as the dispersion is extremely excessive

**Steps to reproduce:**
spawn any howitzer, RHS or not
try fire mission with range table
watch rounds fall everywhere except your target

**Expected behavior:**
shots should land within 10m

**Where did the issue occur?**
Singleplayer editor and Multiplayer in mission

**should also add that the issue does NOT exist with the vanilla 82mm mortar, only howitzers and RHS guns**

**Comment by battleshipfree** [comment]
As far as I know, ACE artys have the same dispersion as vanilla, so they won't be accurate enough to be within 10 meters.

**Comment by severgun** [comment]
> shots should land within 10m
they should not
regular ammo for regular artillery have precision 10-50m.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
