### ISSUE TITLE
ACE3 Arsenal acts as SP mission

### ISSUE THREAD

**Issue by TheNightstalk3r** [acemod/ACE3#7584]
![107410_20200309190706_1](https://user-images.githubusercontent.com/17759038/76244556-983d4980-623a-11ea-8068-792559d87268.png)
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96` 
- **CBA:** `3.14.0`
- **ACE3:** `3.13.1`
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
The ACE3 Arsenal acts like a singleplayer mission in terms of functionality. Whilst the UI seems to be fine, the button "Try" has been replaced by "Close", and once trying out a loadout, there is no way to return to the Loadout Arsenal screen. The only option is to "Save and Quit". Moreover when in the loadout screen, the background is not empty; the virtual vehicles and obstacles are visible. When trying out the loadout, the AI targets are not present.

**Steps to reproduce:**
- Go to ACE3 Arsenal .
-> "Try" button is missing.
- Click "Close" to proceed testing the loadout.
- Click Escape.
- See that "Arsenal" button has been replaced with "Save and Quit".

**Expected behavior:**
The buttons "Try" and "Arsenal" as described above should be present to achieve Virtual Arsenal functionality.

**Where did the issue occur?**
ACE3 Virtual Arsenal

**Log Files:**
Attached. 

EDIT: Turns out the archive w/ RPT log wasn't attached after all. 
Pastebin link: https://pastebin.com/gE98MG1D

**Comment by TheNightstalk3r** [comment]
Related script error?

`18:24:18 Error in expression <et = ["O_Soldier_VR_F", _position] call ace_arsenal_fnc_createTarget;

_target s>
18:24:18   Error position: <ace_arsenal_fnc_createTarget;

_target s>
18:24:18   Error Undefined variable in expression: ace_arsenal_fnc_createtarget
18:24:18 File z\ace\addons\arsenal\missions\Arsenal.VR\initPlayerLocal.sqf..., line 34`

**Comment by commy2** [comment]
Arsenal from main menu, ingame or the editor?

**Comment by TheNightstalk3r** [comment]
This would be the arsenal from the main menu @commy2
