### ISSUE TITLE
[Config] Reopening chance of large Abrasion with QuickClot

### ISSUE THREAD

**Issue by CaptFacepalm** [acemod/ACE3#7585]
In ACE_Medical_Treatment.hpp Line 443:
`reopeningChance = 5;`
should be
`reopeningChance = 0.5;`

Found in the Workshop Version 3.13.1

**Comment by mharis001** [comment]
This was fixed in 3.13.1 by #7383, it is already `0.5` [reference](https://github.com/acemod/ACE3/blob/master/addons/medical_treatment/ACE_Medical_Treatment.hpp#L443).
