### ISSUE TITLE
Wound reopening not working at all

### ISSUE THREAD

**Issue by ArmedVeteran** [acemod/ACE3#7586]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96.146114`
- **CBA:** `3.14.0`
- **ACE3:** `3.13.1`

**Description:**
After the recent update, despite having appropriate settings, wound reopening does not work anymore. After a wound is bandaged it disappears from the list instead of staying there as [B] (bandaged, not stitched). Although the coresponding body part remains blue-ish, as if the wound was not fully healed (this I have set in the settings, although I'm not sure if it is connected with reopening, which is a separate setting). I made sure the settings did not change after the update, I'm pasting them below. Reproduced it a couple of times on a clean scenario with only CBA and ACE loaded.

**Steps to reproduce:**
- Make sure you have settings allowing wounds to require stitching
- Inflict damage to yourself or anyone else (not checked on AI, only players) with any weapon / throwable
- Bandage any wound and watch it disappear from the list, not being able to stitch it

**Expected behavior:**
All of the wounds should stay on the list of wounds of the selected body part after bandaging, requiring additional stitching with Surgical kit, to not reopen.

**Where did the issue occur?**
First we encountered it on dedicated server, with more mods loaded. Then I reproduced it on a localy hosted multiplayer game with clean, new scenario.

**Log Files:**
https://pastebin.com/WdTY7K4B

**Additional context:**
Medical settings export:
force force ace_medical_ai_enabledFor = 0;
force force ace_medical_AIDamageThreshold = 0;
force force ace_medical_bleedingCoefficient = 0.5;
force force ace_medical_blood_bloodLifetime = 900;
force force ace_medical_blood_enabledFor = 2;
force force ace_medical_blood_maxBloodObjects = 500;
force force ace_medical_fatalDamageSource = 1;
force force ace_medical_feedback_bloodVolumeEffectType = 2;
force force ace_medical_feedback_painEffectType = 2;
force force ace_medical_fractureChance = 0.8;
force force ace_medical_fractures = 2;
force force ace_medical_gui_enableActions = 0;
force force ace_medical_gui_enableMedicalMenu = 1;
force force ace_medical_gui_enableSelfActions = true;
force force ace_medical_gui_maxDistance = 3;
force force ace_medical_gui_openAfterTreatment = true;
force force ace_medical_ivFlowRate = 1;
force force ace_medical_limping = 1;
force force ace_medical_painCoefficient = 1;
force force ace_medical_playerDamageThreshold = 2;
force force ace_medical_spontaneousWakeUpChance = 1;
force force ace_medical_spontaneousWakeUpEpinephrineBoost = 1;
force force ace_medical_statemachine_AIUnconsciousness = false;
force force ace_medical_statemachine_cardiacArrestTime = 150;
force force ace_medical_statemachine_fatalInjuriesAI = 0;
force force ace_medical_statemachine_fatalInjuriesPlayer = 0;
force force ace_medical_treatment_advancedBandages = 1;
force force ace_medical_treatment_advancedDiagnose = true;
force force ace_medical_treatment_advancedMedication = true;
force force ace_medical_treatment_allowLitterCreation = true;
force force ace_medical_treatment_allowSelfIV = 1;
force force ace_medical_treatment_allowSelfPAK = 1;
force force ace_medical_treatment_allowSelfStitch = 1;
force force ace_medical_treatment_allowSharedEquipment = 0;
force force ace_medical_treatment_clearTraumaAfterBandage = false;
force force ace_medical_treatment_consumePAK = 1;
force force ace_medical_treatment_consumeSurgicalKit = 0;
force force ace_medical_treatment_convertItems = 0;
force force ace_medical_treatment_cprSuccessChance = 0.4;
force force ace_medical_treatment_holsterRequired = 4;
force force ace_medical_treatment_litterCleanupDelay = 600;
force force ace_medical_treatment_locationEpinephrine = 0;
force force ace_medical_treatment_locationPAK = 3;
force force ace_medical_treatment_locationsBoostTraining = true;
force force ace_medical_treatment_locationSurgicalKit = 0;
force force ace_medical_treatment_maxLitterObjects = 500;
force force ace_medical_treatment_medicEpinephrine = 0;
force force ace_medical_treatment_medicIV = 1;
force force ace_medical_treatment_medicPAK = 1;
force force ace_medical_treatment_medicSurgicalKit = 1;
force force ace_medical_treatment_timeCoefficientPAK = 1;

**Comment by mharis001** [comment]
You have `force force ace_medical_treatment_advancedBandages = 1;`, this setting must be `2` to enable bandage reopening.

**Comment by ArmedVeteran** [comment]
Ah, so it did change itself after the update. I had to miss it, while rechecking. Thanks, closing it.
