### ISSUE TITLE
PKP missing ACE_Overheating_allowSwapBarrel in ACE/RHS compatibility

### ISSUE THREAD

**Issue by AndrewKopczynski** [acemod/ACE3#7589]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96.146114`
- **CBA:** `3.14.0`
- **ACE3:** `3.13.0`

**Description:**
The RHS PKP machine gun `rhs_weap_pkp` is missing `ACE_Overheating_allowSwapBarrel = 1;`, which would allow you to swap barrels on it using ACE Interaction

**Steps to reproduce:**
- Go to `ACE3/optionals/compat_rhs_afrf3/CfgWeapons.hpp`
- Check line `61`-`64` for the following code snippet
```
class rhs_weap_pkp: rhs_pkp_base {
    ACE_barrelTwist = 240.03;
    ACE_barrelLength = 657.86;
};
```
- Note that the statement `ACE_Overheating_allowSwapBarrel = 1;` is missing.

**Expected behavior:**
- You should be able to use ACE Interaction to swap barrels on the RHS PKP machine gun.

**Where did the issue occur?**
- Local SP, MP, and dedicated MP.

**Log Files:**
- No errors or log files are generated, but here's a link to the specific file. https://github.com/acemod/ACE3/blob/master/optionals/compat_rhs_afrf3/CfgWeapons.hpp

**Additional context:**
- Related to #6653

**Screenshots:**
- N/A

**Comment by Drofseh** [comment]
The PKP has a non-removable barrel IRL.

**Comment by AndrewKopczynski** [comment]
ah

disregard
