### ISSUE TITLE
An error ace_advanced_ballistics_x64.dll is not found.

### ISSUE THREAD

**Issue by zVERoNoID** [acemod/ACE3#7591]
An error is appearing when buddy is trying to launch the mission (arsenal too). We have tryed re-install the game, the mod (steam and git both). And my buddy is only one in party with this issue. The .dll files is in the folder. The antimalware is not triggered by files, the path is endlish word only.

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/issues/5273

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/issues/3113
https://github.com/acemod/ACE3/issues/3332
https://github.com/acemod/ACE3/issues/4757

https://github.com/acemod/ACE3/search?q=dll+not+found&unscoped_q=dll+not+found&type=Issues

**Comment by Boberro** [comment]
Unsubscribe, delete all ace files, subscribe again. For some reason it didn't download for me neither

**Comment by zVERoNoID** [comment]
> Unsubscribe, delete all ace files, subscribe again. For some reason it didn't download for me neither

It didn't work. Even the reinstalled the game and cleared registry.

**Comment by zVERoNoID** [comment]
> #5273

BattlEye is just fine. We have tryed disable it. And it's still .dll missing error.

**Comment by Boberro** [comment]
But is the file there? It is in currently uploaded version so the question is if steam downloaded all the files.

**Comment by quasarea** [comment]
you have unicode char in path, that blocks loading of the dll
