### ISSUE TITLE
Request Medic Altis Life 5.0

### ISSUE THREAD

**Issue by YuriZoko** [acemod/ACE3#7592]
Hello ! How to add a request medic button when a player is unconscious in Altis Life 5.0?

Thanks bro

**Comment by bux** [comment]
Please contact the author of Altis Life to implement this feature.

**Comment by YuriZoko** [comment]
I find this

`["ace_unconscious", {
	params ["_unit", "_state"]; 
	[{
		[life_fnc_onPlayerUnconscious, _this] call CBA_fnc_execNextFrame;
	},[_unit,_state], 1] call CBA_fnc_waitAndExecute;
}] call `CBA_fnc_addEventHandler;``

But where paste it ?
