### ISSUE TITLE
CBA Event 

### ISSUE THREAD

**Issue by YuriZoko** [acemod/ACE3#7593]
Hello,

I found a code to add a CBA_EVENT, I can't find where to insert it

`["ace_unconscious", {
	params ["_unit", "_state"]; 
	[{
		[life_fnc_onPlayerUnconscious, _this] call CBA_fnc_execNextFrame;
	},[_unit,_state], 1] call CBA_fnc_waitAndExecute;
}] call CBA_fnc_addEventHandler;`

**Comment by BaerMitUmlaut** [comment]
`initServer.sqf` would probably work for your use case, idk if `life_fnc_onPlayerUnconscious` requires the unit to be local.

**Comment by YuriZoko** [comment]
I paste in the initserver.sqf

Do I have to do anything else?

**Comment by commy2** [comment]
Nobody here knows what `life_fnc_onPlayerUnconscious` is, so /shrug.
Ask on a Life discord or something.
