### ISSUE TITLE
ACE3 Tire Duplication

### ISSUE THREAD

**Issue by Quailsnap** [acemod/ACE3#7598]
It's been here for a while and it needs no introduction.

If two players in MP, vanilla + CBACE or otherwise, both repair two different tire nodes SIMULTANEOUSLY, it can potentially only use one tire object to create two fresh tires on the car.

Infinite tires.

I am assuming this is not intended behavior, but it is a pretty common practice -- at least in a few units I have been with. I suppose there's no issue because nobody wants to be a party pooper.

Note that this is unrelated to: #2461
https://github.com/acemod/ACE3/issues/2461

**Comment by PabstMirror** [comment]
Maybe time to actually use https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_claimSafeServer.sqf

**Comment by jonpas** [comment]
Fixed by #8460.
