### ISSUE TITLE
Medical-Settings Add Setting for PAK and Operationsset if Patient unstable

### ISSUE THREAD

**Issue by Sheppard85oc** [acemod/ACE3#7603]
Hello, Dear ACE Team
**Is your enhancement related to a problem?**
Nice to have a setting like that in the new Medical system

**Solution you'd like:**
we have some problems with our ACE, so we´d like to ask if you could somehow do some settings so that you could still use the "Personal aid kit" and "Operationsset" when the patient is unstable
We look forward to your reply

**Alternatives you've considered:**
/

**Additional context:**
No Screens no RTP Log

**Comment by Drofseh** [comment]
#3594

**Comment by severgun** [comment]
https://github.com/acemod/ACE3/issues/7370
