### ISSUE TITLE
Field rations and Advanced Fatigue

### ISSUE THREAD

**Issue by teemo0803** [acemod/ACE3#7606]
it seems that the acex feature "ration" is not listed in acex wiki
my purpose is to figure out how to recover ace fatigue by drinking REDBULL
thanks all :)

**Comment by Whigital** [comment]
https://ace3mod.com/wiki/frameworkx/field-rations-framework.html

https://github.com/acemod/ACEX/issues

**Comment by BaerMitUmlaut** [comment]
ACEX field rations don't influence advanced fatigue, you would have to script that yourself. Advanced fatigue does not provide public API to directly influence stamina, however you can add a duty factor lower than one using this function:
https://github.com/acemod/ACE3/blob/master/addons/advanced_fatigue/functions/fnc_addDutyFactor.sqf

This duty factor can also be removed using the `removeDutyFactor` function. A duty factor is multiplied with the current amount of power required to move. You can find some usage examples here:
https://github.com/acemod/ACE3/blob/fa910a7fd806fd26dd77c0ce89a1b4d135b89724/addons/advanced_fatigue/XEH_postInit.sqf#L46-L63

A duty factor lower than one would decrease the current work load and thus allow you to sprint or jog further. If you want instant recovery, you would need a deeper knowledge of the system and fiddle around with internal variables, which I would not recommend.

**Comment by teemo0803** [comment]
thanks a lot
