### ISSUE TITLE
ACE Cargo load not working on crates

### ISSUE THREAD

**Issue by micahwhitsel** [acemod/ACE3#7612]
Using current versions of everything with RHS and ACE. 

Attempting to have ammo crates preloaded into vehicles at mission start using ace_cargo_fnc_loadItem. The same exact call is working on other objects such as cones, but ammo crates do not seem to respond to this command in the same way. Objects are able to be loaded by hand in game as there is space and the objects are loadable, just not on mission initialization.

https://i.gyazo.com/8b10ad0085585915dde8c680510d67cf.png

**Comment by commy2** [comment]
```sqf
if (isServer) then {
    [object, vehicle, true] call ace_cargo_fnc_loadItem;
};
```

**Comment by micahwhitsel** [comment]
> ```sqf
> if (isServer) then {
>     [object, vehicle, true] call ace_cargo_fnc_loadItem;
> };
> ```

So I attempted this to no avail. To clarify, I used

```if (isServer) then {
[this, Apollo_AIO_d_1, true] call ace_cargo_fnc_loadItem;
};```

on an ammo box ('Box_NATO_Ammo_F') init in Eden, with ApolloAIO_d_1 being the variable name of my vehicle. The ammo box is loadable and the vehicle does have adequate cargo space. 

I'm currently attempting to run this in local multiplayer on my machine from Eden, but have also tried that solution on a dedicated server previously without success.

**Comment by bux** [comment]
The command works flawlessly with just CBA and ACE3 on a newly created mission.

Please fill out the issue template, add all the requested information most importantly the RPT file.

**Comment by micahwhitsel** [comment]
> The command works flawlessly with just CBA and ACE3 on a newly created mission.
> 
> Please fill out the issue template and add all the requested information most importantly the RPT file.
> 
> Mission I used to test:
> [cargo_load.VR.zip](https://github.com/acemod/ACE3/files/4370481/cargo_load.VR.zip)

Thank you. I'm going to do some iterative testing to figure out what my issue is then
