### ISSUE TITLE
Single Player preset

### ISSUE THREAD

**Issue by Kahotika** [acemod/ACE3#7614]
Hello,

I enjoy ACE 3 a lot but unfortunately some features are not compatible with Arma 3 campaigns.

The best way to fix this would be to let the user enable/disable any modules and maybe save some presets.
As far as I'm concerned the explosive module is creating conflicts with a mission and I can't find a way to disable it.

**Comment by commy2** [comment]
Remove ace_explosive.pbo.

**Comment by Kahotika** [comment]
Thank you very much for your answer but I can’t find the pbo

**Comment by commy2** [comment]
Mine is here:
`C:\Arma 3\@ace\addons\ace_explosives.pbo`
But it depends on your installation path.

**Comment by Kahotika** [comment]
You’re right! Incredible I didn’t see that…
Thank you very much

Provenance : Courrier pour Windows 10

De : commy2
Envoyé le :vendredi, 27 mars 2020 18:25
À : acemod/ACE3
Cc : Kahotika; Author
Objet :Re: [acemod/ACE3] Single Player preset (#7614)

Mine is here:
C:\Arma 3\@ace\addons\ace_explosives.pbo
But it depends on your installation path.
