### ISSUE TITLE
Unable to move when dragging a wounded unit if the player is in combat pace

### ISSUE THREAD

**Issue by Ivanowicz** [acemod/ACE3#7616]
- **Arma 3:** `1.92`
- **CBA:** ` 3.14.0`
- **ACE3:** `3.13.1`

**Description:**
As in the title - if the player enters combat pace before attempting to drag a wounded person, they are unable to move while in dragging position (they can still rotate). The problem does not occur when not in combat pace.

**Steps to reproduce:**
- Place 2 units in editor.
- Knock the other unit unconscious.
- Enter combat pace and attempt to drag the unconscious unit.

**Expected behavior:**
Ability to drag a person without having to turn off combat pace beforehand - or, if for some reason the problem is not fixable, a mention of the solution on the wiki page.

**Where did the issue occur?**
The problem appears both on a dedicated server and in singlepleyer.

**.rpt file**
https://pastebin.com/181jLeKJ

**Comment by Blutze** [comment]
Also applies to dragging boxes etc.

> and the player can not switch combat pace while dragging.

Can't reproduce this detail. Its been like this for years, and I've never heard of anyone having that particular problem.

Ticket is missing rpt file as well.

**Comment by commy2** [comment]
Same happens with hurt legs. BI does not have the animations set up for this. Idk if it is possible to fix by editing the animation config or if it is some hard coded thing though.

**Comment by Drofseh** [comment]
Could we force the player out of combat pace when they initiate the drag action?

**Comment by commy2** [comment]
How?

**Comment by Ivanowicz** [comment]
@Blutze Welp, you're right, it works, for some reason I just never stopped holding S when switching combat pace. As for the solution could we not just use the same animation with combat pace on and off? I kinda understand that with hurt legs, but still, the lack of feedback is a bit confusing.

**Comment by commy2** [comment]
>As for the solution could we not just use the same animation with combat pace on and off?

How?

**Comment by Ivanowicz** [comment]
Ok, after re-reading your comment (and guessing from the "how?" comments) I think I can safely assume it's not as simple as my question would imply.

**Comment by Drofseh** [comment]
> > Could we force the player out of combat pace when they initiate the drag action?

> How?

I was just wondering if it was possible

**Comment by BaerMitUmlaut** [comment]
If I remember correctly, years ago someone sent @bux a fix, maybe through twitter. I have tried finding it again but failed so far. It was a one liner.

**Comment by bux** [comment]
I don't remember

**Comment by BaerMitUmlaut** [comment]
I don't blame you, that was like 3 years ago or something. I only remember it was a twitter DM.

**Comment by BaerMitUmlaut** [comment]
bux found the message 🎉
