### ISSUE TITLE
Nightvision post processing effects active in normal vision with UAVs

### ISSUE THREAD

**Issue by LalaAU** [acemod/ACE3#7618]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96.146114` stable
- **CBA:** `3.14.0` stable
- **ACE3:** `3.13.1` stable
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
When night vision is active, switch to UAV and notice that post processing effects are still active in colour vision mode.

**Steps to reproduce:**
Switch NV on for unit (can be in vehicle to such as tank gunner/commander in their optics while the unit themselves doesn't have nv goggles)
Control UAV (can be driver/gunner)
Observe
- See https://streamable.com/ua8iw

**Expected behavior:**
Post processing effects should be removed as the UAV is not in night vision mode, same with overlay of nv goggles when in nv mode

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Log Files:**
- Link to https://gist.github.com/LalaAU/b4f84b6b1f66b9e6f46d74cf7ad283d0.

**Additional context:**
Working on a vision enhancement mod that applies to colour vision

**Screenshots:**
![image](https://user-images.githubusercontent.com/30714521/77968305-bde9da00-7332-11ea-8786-80654f1fa90d.png)

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
