### ISSUE TITLE
Respawn GUI Sometimes Inaccessible

### ISSUE THREAD

**Issue by 173rdairbornemilsim** [acemod/ACE3#7620]
The current issue that we are experiencing with Ace is when it comes to respawning. The issue is that when killed and attempting to spawn, the respawn GUI is not intractable. The map cannot be clicked on, the respawn button cannot be pressed, it is as if one is stuck in the ace interaction menu but with no options. This issue only occurs some of the time and the only fix when stuck in the respawn screen is to completely restarts one's game. 

Standard respawning works just fine, it seems that this only occurs when being killed by the enemy based on our independent testing of the issue. 

It also seems that this issue was mentioned previously on January 2nd of this year, the link to the previous issue thread is here: https://github.com/acemod/ACE3/issues/7356

**Comment by dedmen** [comment]
You didn't fill out the issue template. Please do so, mods and their versions + RPT.

**Comment by 173rdairbornemilsim** [comment]
I'm not seeing any issue template as you are stating, can you link it to me?

**Comment by Drofseh** [comment]
It's what you deleted when you wrote your paragraphs.

```
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
A clear and concise description of what the bug is.

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**
A clear and concise description of what you expected to happen.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**
Add any other context about the problem here.

**Screenshots:**
If applicable, add screenshots to help explain your problem.

```

**Comment by Lorenz94B** [comment]
Arma 3: 1.98 stable
CBA: 3.15.0 stable
ACE3: 3.13.3 stable

Description:
Respawning in local hosted MP game will get you stuck at the respawn dialog.

Steps to reproduce:
Start a MP in 3DEN editor, then try to respaw.

Where did the issue occur?
Self-hosted MP game

Additional context:
description.ext contains what follows
`respawn = 3;
respawnDialog = 0;
respawnOnStart = 0;
respawnDelay = 5;
respawnTemplates[] = {"MenuPosition"};`

Thank you!

**Comment by Whigital** [comment]
You have to create a spawn marker (eg. `respawn_west`), otherwise you have nowhere to spawn. This is not related to __ACE__, since it doesn't even work with those settings in vanilla Arma.

Reference https://community.bistudio.com/wiki/Arma_3_Respawn for more info ....

**Comment by Lorenz94B** [comment]
You're right, I forgot to mention that, I'm sorry. The marker was set up, it happened to me to experience the freeze at the respawn screen where you can't interact with anything.

**Comment by Whigital** [comment]
Worked fine for me after the respawn marker was added.
