### ISSUE TITLE
NLAW not works (impossible to capture target)

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#7621]
**Mods (ACE3, JSRS Sound Mod, CBA3):**
- **Arma 3:** `1.96` [stable]
- **CBA:** `3.14.0` [stable]
- **ACE3:** `3.13.1` [stable]

**Description:**
NLAW missile does not fly at the target. cannot capture the target like a Titan missile does. As a result, it is impossible to get into a moving target. I followed your advice - https://ace3mod.com/wiki/feature/nlaw.html but no results. When i press the button - “NLAW Track Target” nothing happens, there are no sound or visual signals indicating that the NLAW missile captures the target. If I shoot after this, then the NLAW missile flies in an unpredictable direction

**Steps to reproduce:**
Shoot from NLAW at moving target

**Expected behavior:**
the NLAW missile must capture the target and follow it

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by jonpas** [comment]
It's in the word, it's "Track Target", not "Lock Target".

Did you follow the procedure as described? Hold down the button, track the target with your mouse for 2-3 seconds and then fire. Missile will NOT lock the target, it will only follow the calculated path of your tracking.

**Comment by ZeusWrath** [comment]
Probably I do not understand how it works. 

> Hold down the button, track the target with your mouse for 2-3 seconds and then fire. Missile will NOT lock the target, it will only follow the calculated path of your tracking.

What is the point of this? Any other launcher, without a guided missile, will do the same. I mean RPG-7, RPG-32 etc. the Missile will fly where it was directed.

How do I hit a moving target with NLAW?

**Comment by jonpas** [comment]
No, not every other launcher will calculate a path of flight and follow it.

**Comment by ZeusWrath** [comment]
> How do I hit a moving target with NLAW?

give an answer please. What is the advantage of NLAW over standard Launchers (without tracking)?
I tried to shoot at a moving target and did not see any advantages, I saw only the IMPOSSIBILITY of hitting the target

**Comment by PabstMirror** [comment]
https://www.youtube.com/watch?v=0o3yTq36_AU

**Comment by ZeusWrath** [comment]
When I shot, I did the same. The only difference is that after the shot I continued to move the NLAW (Pointing at the target) relative to the moving target.

Probably in ACE3 when the player fired, he should not move his NLAW, the player [should not aim him at the target](https://youtu.be/0o3yTq36_AU?t=5) , it all looks very strange. 
Other than this, there are no sounds or visual markers warning the shooter that now the selected target is being tracked - at least some kind of sign!
 In the second example ([Top Attack](https://youtu.be/0o3yTq36_AU?t=19)) the tracked target does not move at all! Does this mean that it is impossible to destroy a moving target in Top Attack mode? **Why is the target moving in the first video example and not moving in the second?**

PS: In my opinion, the NLAW system works poorly, please try to improve this. It would be better if
1) NLAW signaled target tracking (sound or visual rhombus) or maybe something other.
2) After shot, the player could control the flight of the missile  as it does 9M135 Vorona is a 130 mm missile launcher.
3) In Top Attack mode, there is no visual FX characterizing an explosion from above the target. Nothing is visible there! If it possible, Just try to add this.

**Comment by Drofseh** [comment]
I've just been trying it out, and it's definitely difficult to master but the system seems to be working as intended.

There is an audible click when tracking starts and when switching to/from top attack mode, and the top attack flight path is obviously different from direct attack.

Close?

**Comment by jonpas** [comment]
That is how NLAW works, you want it to work unrealistically, just use other launchers if you want locking or fly-by-wire guidance.

We accept PRs for enhancements but not changes to how it works.

**Comment by BaerMitUmlaut** [comment]
I visual indicator of what is happening is reasonable. I couldn't find any references, but we can make something up.

**Comment by commy2** [comment]
At least remove that scrollbar.

**Comment by BaerMitUmlaut** [comment]
That's from ACRE.

**Comment by BaerMitUmlaut** [comment]
Turns out the NLAW uses an ACOG variant with a V instead of a chevron (yes, this is the correct orientation):
![grafik](https://user-images.githubusercontent.com/9693842/78581928-d6775a00-7834-11ea-9e03-ea0af563a87d.png)

So there should actually not be any visual indicator of tracking or attack mode in the sight.

**Comment by PabstMirror** [comment]
Current in-game optic has ranging lines, which make no sense given that it's stabilized so we might want to switch optics model.

**Comment by BaerMitUmlaut** [comment]
Found more info: The sight used in Arma 3 is a Knights Armament Co. (KAC) UNS-T (-Micro?):

![grafik](https://user-images.githubusercontent.com/9693842/78781719-06dc0700-79a1-11ea-8997-d8238fe17ef0.png)

![grafik](https://user-images.githubusercontent.com/9693842/78781840-44409480-79a1-11ea-99a3-cfbd55c15dc6.png)

It has a selectable reticles with 3 variants, of which I could not find any images yet.

**Comment by Drofseh** [comment]
I've made an account on this website and sent this guy a message to see if he still owns and can send photos of the reticle. If he can send them I will post them.
<https://forum.snipershide.com/threads/kac-uns-t.6961123/>

**Comment by Drofseh** [comment]
So the one he has isn't a stand along device, it's meant to be placed in front of another optic, and it does not have its own reticle.

This [website](http://www.knesekguns.com/commercial/product_info.php?products_id=861) sells it and it mentions `Reticles: Optional` so perhaps there are two versions, one with and one without reticles.

**Comment by BaerMitUmlaut** [comment]
Ah, that makes sense, thanks a lot for trying.

**Comment by ZeusWrath** [comment]
there was no answer how to hit a moving target using NLAW (Top attack mode) 
[Video ](https://www.youtube.com/watch?v=0o3yTq36_AU) does not demonstrate this
I tried to hit a moving target from above, but my attempts were unsuccessful. Looks like guys NLAW in ACE3 are still not working fine :/

**Comment by BaerMitUmlaut** [comment]
Works fine for me, are you using Ctrl + Tab to switch the attack profile? Looks like there is a leftover firemode that should be removed from vanilla.

**Comment by ZeusWrath** [comment]
Hei @Drofseh What are you poking dislikes !? Better show the video how NLAW from ACE3 mod can kill a moving target

> Works fine for me, are you using Ctrl + Tab to switch the attack profile? 
Yes, I switch attack modes. But the problem is not that I cannot switch attack mode. My problem is that NLAW missile will not track the moving target during the flight (after my shot).  It always flies in an unpredictable direction. I hold the Tab-button dozens of times and tracked the moving target, but always the missile does not hit the target. NLAW is generally a meaningless weapon in my case

**Comment by ArwynFr** [comment]
NLAW cannot *lock* a target and will not *track* it, actually, as the device does not have a missile guidance ability.

It will only read the target speed and direction when you use the tracking key, and then calculate an interception course assuming the target speed and direction will stay constant during the missile flight. When you fire, the missile will follow that pre-calculated interception course in straight line without any ability to change the missile direction during the flight. Of course, this behavior can be easily defeated by the target vehicle, by changing its speed or/and direction if the flight time and crew reaction time permits.

**This is how the actual device works IRL.**

This device is still an improvement compared to simple launchers which require the gunner to do the trajectory estimation without assistance. NLAWS are obviously outmoded by modern launchers and missiles, which provide missile guidance (missile locks on the launcher's embedded laser designator) or even fire-and-forget systems (usually thermal locked missile, such as the Titan/Javelin). However these devices and missiles are usually a lot more expansive, that's why some armed forces still rely on NLAWS or similar launchers when ambushing convoys and the terrain permits close range engagement.

**Comment by BaerMitUmlaut** [comment]
>I'm shooting a CSAT Punisher at MOVE Waypoint
>Missile can't track it

![nlaw](https://user-images.githubusercontent.com/9693842/79464064-e8f25000-7ff9-11ea-800a-a94bf7d19c57.gif)


As you can see, it works just fine. It's harder to do with fast moving vehicles like this, obviously, but you should be able to hit your target after a couple tries.

**Comment by commy2** [comment]
What about this:

>Looks like there is a leftover firemode that should be removed from vanilla.

**Comment by ZeusWrath** [comment]
> NLAW cannot lock a target and will not track it, actually, as the device does not have a missile guidance ability.
> 
> It will only read the target speed and direction when you use the tracking key, and then calculate an interception course assuming the target speed and direction will stay constant during the missile flight. When you fire, the missile will follow that pre-calculated interception course in straight line without any ability to change the missile direction during the flight. Of course, this behavior can be easily defeated by the target vehicle, by changing its speed or/and direction if the flight time and crew reaction time permits.
> 
> This is how the actual device works IRL.
> 
> This device is still an improvement compared to simple launchers which require the gunner to do the trajectory estimation without assistance. NLAWS are obviously outmoded by modern launchers and missiles, which provide missile guidance (missile locks on the launcher's embedded laser designator) or even fire-and-forget systems (usually thermal locked missile, such as the Titan/Javelin). However these devices and missiles are usually a lot more expansive, that's why some armed forces still rely on NLAWS or similar launchers when ambushing convoys and the terrain permits close range engagement.

@ArwynFr thank you for this detailed description, Now I understand how it should work!

> As you can see, it works just fine. It's harder to do with fast moving vehicles like this, obviously, but you should be able to hit your target after a couple tries. 

@BaerMitUmlaut 
Thank you for the video. But I still haven’t managed to hit the target. I will try again and again

> Looks like there is a leftover firemode that should be removed from vanilla.
@commy2

"should be removed from vanilla" - Here I do not understand you. Do you mean that I need to delete the assigned vanilla button in the settings?
