### ISSUE TITLE
[Medical] allowDamage is false but unit goes into unconscious state when vehicle is destroyed

### ISSUE THREAD

**Issue by Leopard20** [acemod/ACE3#7623]
As the title says, if damage is disabled for a unit and his vehicle is destroyed, he goes into unconscious state.

**Comment by commy2** [comment]
ref #7429

**Comment by Leopard20** [comment]
No clue. If you can't reproduce it then I guess it's fixed and it can be closed.

**Comment by johnb432** [comment]
> No clue. If you can't reproduce it then I guess it's fixed and it can be closed. Since it's linked to the other issue about back blast which is fixed, I think this is fixed too (just forgotten to be closed)

I suggest trying to replicate it on your end, as I'm not fully sure what the reproduction steps are.

However, trying it on AI and players in SP and self-hosted MP suggests that it's been fixed.

If you deem the issue to be fixed, I guess we ought to close the issue.
