### ISSUE TITLE
Mistake in the Mk6 Mortar Wiki page regarding elevation

### ISSUE THREAD

**Issue by javathezone** [acemod/ACE3#7628]
**Is your enhancement related to a problem?**
On the wiki page for the Mk6 Mortar it states that:
> The lower the elevation the closer to you it will land.

Mortars belong to the high-angle group of indirect firing systems therefore the opposite is true. 

**Solution you'd like:**
Change that sentence to:

> The higher the elevation the closer to you it will land.

Additionally, move that sentence one tier up in the bullet point hierarchy.

**Alternatives you've considered:**
Change that sentence to:

> The lower the elevation the farther from you it will land.

**Additional context:**
Direct link to wiki page:
https://ace3mod.com/wiki/feature/mk6mortar.html

**Comment by BaerMitUmlaut** [comment]
That would be an easy pull request, you can find the source of that page here:
https://github.com/acemod/ACE3/blob/master/docs/wiki/feature/mk6mortar.md

**Comment by javathezone** [comment]
Thank you Bär,
I am new to GitHub, I will try to inform myself on what that means and then take appropriate actions.

**Comment by BaerMitUmlaut** [comment]
Great :+1: 
If you want the easy route, you can just click the small pencil icon on that page.

**Comment by javathezone** [comment]
So I tried to do what you asked me too, I hope that was correct.
