### ISSUE TITLE
Error adding items from addon

### ISSUE THREAD

**Issue by Derienzo** [acemod/ACE3#763]
I was wondering if it was possible to add ace items to a backpack... I was using this code to add it:

player addbackpack "b_kitbag_base";
(unitBackpack player) addItemCargo ["ACE_plasmaIVItem",1];
(unitBackpack player) additemCargo ["ACE_salineIVItem",1];
(unitBackpack player) additemCargo ["item_ACE_plamaIVItem",1];
(unitBackpack player) additemCargo ["ACE_packingBandageItem",1];
(unitBackpack player) additemCargo ["ACE_epinephrineItem",1];
(unitBackpack player) additemCargo ["ACE_epinephrineItem",1];
(unitBackpack player) additemCargo ["ACE_bloodIVItem",1];
(unitBackpack player) additemCargo ["ACE_quikClotItem",1];
(unitBackpack player) additemCargo ["ACE_atropineItem",1];
(unitBackpack player) additemCargo ["ACE_fieldDressingItem",1];
(unitBackpack player) additemCargo ["ACE_elasticBandageItem",1];

and this code in the inventory of the box...

this addAction["<t color='#ff1111'>Medical Backpacks</t>", "addbackpack.sqf"];  clearWeaponCargoGlobal MedBox; clearItemCargoGlobal MedBox; clearMagazineCargo MedBox; clearBackpackCargo MedBox;

But it is not adding any of the ACE items to the player backpack... is this my side or something that is with the classnames that I found in the top right corner of the Arma 3 editor window. ACE works regularly if I wat to just add something in to the server.

Thank you.

Derienzo

**Comment by jaynus** [comment]
you need to use addItemCargoGlobal

**Comment by Derienzo** [comment]
Sir, nothing is showing up in the backpack still..

unsure why.

**Comment by bux578** [comment]
For backpack: [`addItemToBackpack`](https://community.bistudio.com/wiki/addItemToBackpack)

for boxes [`addItemCargoGlobal`](https://community.bistudio.com/wiki/addItemCargoGlobal)

**Comment by commy2** [comment]
Bux, you can add to a units backpack or the backpack container directly. It doesn't matter.The issue are the classnames as described in https://github.com/acemod/ACE3/issues/764
