### ISSUE TITLE
ACE Whitelist invalid value

### ISSUE THREAD

**Issue by fire-391** [acemod/ACE3#7632]
**Mods (complete and add to the following information):**
- **Arma 3:** 1.96 stable
- **CBA:** 3.15.0 stable
- **ACE3:** 3.13.1 stable
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
ace_common_checkPBOsWhitelist not working

**Steps to reproduce:**
Run server with ACE and CBA with jsrs entry's in the whitelist run jsrs (for example) on client

**Expected behavior:**
Not be kicked by server, no "missing addons" errors

**Where did the issue occur?**
- Dedicated

**Log Files:**
- Server - https://pastebin.com/gJRsrdrZ
- Client - https://pastebin.com/WJ9tqVR0

**Additional context:**
Related CBA settings:

force force ace_common_checkPBOsAction = 2;
force force ace_common_checkPBOsCheckAll = true;
force force ace_common_checkPBOsWhitelist = 
"["jsrs_soundmod_complete_edition","jsrs_soundmod_boats","jsrs_soundmod_sonic_cracks","jsrs_soundmod_weapons","jsrs_soundmod_environment","jsrs_soundmod_explosions","jsrs_soundmod_framework","jsrs_soundmod_landvehicles","jsrs_soundmod_movement","jsrs_soundmod_bullethits","jsrs_soundmod_helicopters"]";

Notable RPT error:

2020/04/10,  9:59:41 [CBA] (settings) WARNING: Invalid value any for setting ace_common_checkPBOsWhitelist. Fall back to default value.

**Screenshots:**
N/A

**Comment by jonpas** [comment]
That's not a bug, you have an invalid sytanx for `checkPBOsWhitelist`. Did you use the export or wrote this yourself?

Should be:
```sqf
force force ace_common_checkPBOsWhitelist =
"['jsrs_soundmod_complete_edition','jsrs_soundmod_boats','jsrs_soundmod_sonic_cracks','jsrs_soundmod_weapons','jsrs_soundmod_environment','jsrs_soundmod_explosions','jsrs_soundmod_framework','jsrs_soundmod_landvehicles','jsrs_soundmod_movement','jsrs_soundmod_bullethits','jsrs_soundmod_helicopters']";
```
or double double quotes.

**Comment by fire-391** [comment]
Was originally single quotes when it broke, changed to double to attempt a fix, just tried yours and got the same error.

**Comment by fire-391** [comment]
I have tried the solution given and got the same errors.

**Comment by bux** [comment]
Working example

```
ace_common_checkPBOsWhitelist = "[""jsrs_soundmod_complete_edition"",""jsrs_soundmod_complete_edition_soundfiles"",""jsrs_soundmod_boats"",""jsrs_soundmod_sonic_cracks"",""jsrs_soundmod_weapons"",""jsrs_soundmod_environment"",""jsrs_soundmod_explosions"",""jsrs_soundmod_framework"",""jsrs_soundmod_landvehicles"",""jsrs_soundmod_movement"",""jsrs_soundmod_bullethits"",""jsrs_soundmod_helicopters""]";
```

**Comment by jonpas** [comment]
Where are you setting this? My example works in static settings mod as well as mission completely fine.

**Comment by fire-391** [comment]
In cba_settings.sqf located in the userconfig file in the root folder of arma on the server. @bux's example worked.

**Comment by bux** [comment]
![image](https://user-images.githubusercontent.com/1235520/79046885-a7d1f880-7c13-11ea-9746-d7b593505439.png)

We have the best examples!
