### ISSUE TITLE
Range card doesn't fits in the screen

### ISSUE THREAD

**Issue by bababoombatman** [acemod/ACE3#7638]
**Mods:**
- **Arma 3:** `1.98`
- **CBA:** `3.5.0`
- **ACE3:** `3.13.1`

**Description:**
I don't know if it's a problem of my resolution (1600x900) or screen size (20"), but whenever i use the range card i can't see the bottom line (the one where you see how many inch the optic is above the line of bore). This can be annoying where doing some maths for a long range shot.

**Steps to reproduce:**
- Go to virtual arsenal
- Equip a range card
- Open it

**Screenshots:**
![Arma 3 14_04_2020 14_00_10](https://user-images.githubusercontent.com/14316469/79224128-e4dbfc00-7e5a-11ea-8850-71aeb26aeece.png)

**Expected behavior:**
![expected behavior](https://user-images.githubusercontent.com/14316469/79224056-c6760080-7e5a-11ea-8916-c507ded217ef.png)

**Where did the issue occur?**
- Everywhere

Maybe an option to resize the range card or another variant that shows corrections only up to 2000m would do the job.

**Comment by FalcoGer** [comment]
Would be nice if this were fixed. it's still an issue.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
