### ISSUE TITLE
Changed to additemCargoGlobal, still doesn't work

### ISSUE THREAD

**Issue by Derienzo** [acemod/ACE3#764]
I was wondering if it was possible to add ace items to a backpack... I was using this code to add it:

player addbackpack "b_kitbag_base";
(unitBackpack player) addItemCargoGlobal ["ACE_plasmaIVItem",1];
(unitBackpack player) addItemCargoGlobal ["ACE_plasmaIVItem",1];
(unitBackpack player) additemCargoGlobal ["ACE_salineIVItem",1];
(unitBackpack player) additemCargoGlobal ["ACE_plamaIVItem",1];
(unitBackpack player) additemCargoGlobal ["ACE_packingBandageItem",1];
(unitBackpack player) additemCargoGlobal ["ACE_epinephrineItem",1];
(unitBackpack player) additemCargoGlobal ["ACE_epinephrineItem",1];
(unitBackpack player) additemCargoGlobal ["ACE_bloodIVItem",1];
(unitBackpack player) additemCargoGlobal ["ACE_quikClotItem",1];
(unitBackpack player) additemCargoGlobal ["ACE_atropineItem",1];
(unitBackpack player) additemCargoGlobal ["ACE_fieldDressingItem",1];
(unitBackpack player) additemCargoGlobal ["ACE_elasticBandageItem",1];

and this code in the inventory of the box...

this addAction["Medical Backpacks", "addbackpack.sqf"]; clearWeaponCargoGlobal MedBox; clearItemCargoGlobal MedBox; clearMagazineCargo MedBox; clearBackpackCargo MedBox;

But it is not adding any of the ACE items to the player backpack... is this my side or something that is with the classnames that I found in the top right corner of the Arma 3 editor window. ACE works regularly if I wat to just add something in to the server.

Thank you.

Derienzo

**Comment by Derienzo** [comment]
Sorry for this post again... just still doesn't work.

Thanks

**Comment by commy2** [comment]
You are using the command wrong. All inventory commands expect classes from `CfgWeapons`, `CfgMagazines` or `CfgGlasses`, but you tried to add the weapon holders from `CfgVehicles`. Probably because you found them in the editor.

This issue tracker isn't meant to ask questions. Please use the BI forums or the public slack the next time for that.

```
A = "toLower configName _x find 'ace_' == 0" configClasses (configFile >> "CfgWeapons");
A = [A, {configName _this}] call ace_common_fnc_map;
```

```
["ACE_ItemCore","ACE_FakePrimaryWeapon","ACE_Banana","ACE_launch_NLAW_Used_F","ACE_muzzle_mzls_H","ACE_muzzle_mzls_B","ACE_muzzle_mzls_L","ACE_muzzle_mzls_smg_01","ACE_muzzle_mzls_smg_02","ACE_muzzle_mzls_338","ACE_muzzle_mzls_93mmg","ACE_acc_pointer_red","ACE_acc_pointer_green_IR","ACE_acc_pointer_green","ACE_UAVBattery","ACE_wirecutter","ACE_MapTools","ACE_microDAGR","ACE_NVG_Gen1","ACE_NVG_Gen2","ACE_NVG_Gen4","ACE_NVG_Wide","ACE_optic_Hamr_2D","ACE_optic_Hamr_PIP","ACE_optic_Arco_2D","ACE_optic_Arco_PIP","ACE_optic_MRCO_2D","ACE_optic_MRCO_PIP","ACE_optic_SOS_2D","ACE_optic_SOS_PIP","ACE_optic_LRPS_2D","ACE_optic_LRPS_PIP","ACE_SpareBarrel","ACE_Altimeter","ACE_LMG_coax_MBT_01","ACE_LMG_coax_APC_Tracked_03","ACE_Vector","ACE_key_master","ACE_key_lockpick","ACE_key_west","ACE_key_east","ACE_key_indp","ACE_key_civ","ACE_AIR_SAFETY","ACE_gatling_20mm_Comanche","ACE_ATragMX","ACE_IR_Strobe_Item","ACE_CableTie","ACE_DebugPotato","ACE_ExplosiveItem","ACE_Clacker","ACE_M26_Clacker","ACE_DefusalKit","ACE_DeadManSwitch","ACE_Cellphone","ACE_EarPlugs","ACE_Kestrel4500","ACE_fieldDressing","ACE_packingBandage","ACE_elasticBandage","ACE_tourniquet","ACE_morphine","ACE_atropine","ACE_epinephrine","ACE_plasmaIV","ACE_plasmaIV_500","ACE_plasmaIV_250","ACE_bloodIV","ACE_bloodIV_500","ACE_bloodIV_250","ACE_salineIV","ACE_salineIV_500","ACE_salineIV_250","ACE_quikclot","ACE_personalAidKit","ACE_surgicalKit","ACE_bodyBag"]
```
