### ISSUE TITLE
Ammo count still visible in weapon info

### ISSUE THREAD

**Issue by lividsubset3** [acemod/ACE3#7647]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98.*` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.0` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.1` [eg. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
So, this is running on a dedicated but what really bugs me is in the top left you have an ammo count that shows how many you have remaining in the mag, I remember that it does not show how many exact, as of you would have to use `CTRL + R` to show how many you have etc.

I'm wondering if this is just a bug, or if its a server side config I need to change. And as well as, on the same server but different PBO it does not show anything, and thats the way I need and want.

This is using Iron Front AIO Lite, and not sure if its because of this mod or not.

Could it be the map or the mod the map is on?

**Steps to reproduce:**
Cant tell or say on how I can reproduce this problem - But this is what I see
![20200417171127_1](https://user-images.githubusercontent.com/22203332/79670268-f1c05e80-817e-11ea-83b8-eef447579cf7.jpg)

**Expected behavior:**
And this is what I really want
![20200417171404_1](https://user-images.githubusercontent.com/22203332/79670271-f4bb4f00-817e-11ea-92b1-fef36d198f77.jpg)

**Where did the issue occur?**
- Dedicated / Editor (Eden only on the modded maps)

**Comment by BaerMitUmlaut** [comment]
>This is using Iron Front AIO Lite, and not sure if its because of this mod or not.

Why don't you find out? It even tells you in the issue template to try to reproduce this issue with just CBA and ACE3.

**Comment by commy2** [comment]
>Could it be the map or the mod the map is on?

Map is irrelevant, mission unlikely, mod very likely.

**Comment by Drofseh** [comment]
This was an issue with IFA3, not ACE
