### ISSUE TITLE
ACE 3 Medical documentation

### ISSUE THREAD

**Issue by jospanner** [acemod/ACE3#7659]
Hi,
Considering that ACE3 is meant to be used by the general user base of ArmA 3, I think that digging through code to understand how to use it is not such a good idea.

The existing documentation for the old system has been taken down, but it is replaced with nothing. As it is, we have no idea how the system works other than by trial and error, which for a complex system is not good at all.

Consider the following use case:
"There are four types of bandages. Which one do I use?"
As it is, there is no way to find this out other than by digging through source code.

Or other questions that someone might have: 
"What does Adenosine do?" 
"What makes someone wake up?" 
"What is a 'doctor' level medic for?"

It might not be glamorous, but documentation is essential if the idea is for people to actually use the thing that you've put so much effort into. It should be considered to be as important as the code itself.

**Comment by Drofseh** [comment]
#7657

**Comment by jonpas** [comment]
> It might not be glamorous, but documentation is essential if the idea is for people to actually use the thing that you've put so much effort into. It should be considered to be as important as the code itself.

Sure, but as we all do this as it fits in our free time, nobody can be made to do anything. :)

We are aware of this, one contributor in #7657 already stepped up, so it is pending. Expansion on it is always welcome.
