### ISSUE TITLE
Crew always survive vehicle destruction

### ISSUE THREAD

**Issue by far2proh** [acemod/ACE3#7665]
(I looked for other users with the same issue as me but they never described the bug i think is happening to me)

**Mods**

- Arma 3:   1.98.146303    (stable)
- CBA:    current at time of posting
- ACE3: current at time of posting

(sorry for not getting exact numbers, not sure where to find them but they are both off the steam workshop and up to date)

**Description:**
crew will survive any destruction of any vehicle. this includes, aircraft, cars, helicopters, tanks, ect.
they will also survive the fall if they jump out from any altitude, not sure if that is related to this bug or a separate one. 

**Steps to reproduce:**
blow up any vehicle with crew in it.

**Expected behavior:**
crew should be killed or severely wounded

**Where did the issue occur?**
- Dedicated and editor singleplayer

**Log Files:**
- https://pastebin.com/UsiRhHDR

**Additional context:**
first video is from our antistasi server where we have many mods,

second video is just ace3 and cba in an editor mission.

(also sorry if i have done something wrong here, never made a post on github before)

**Screenshots:**
https://youtu.be/d3vLdGwWOHg

https://youtu.be/U3m1a9jUeks

**Comment by commy2** [comment]
ref: #7480
