### ISSUE TITLE
ACE FCS not working on dedicated server.

### ISSUE THREAD

**Issue by severgun** [acemod/ACE3#7666]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98` [stable]
- **CBA:** `3.15.1` [stable]
- **ACE3:** `3.13.2` [stable]

**Description:**
ACE FCS not working on dedicated server.

**Steps to reproduce:**
- Create mission with `B_APC_Tracked_01_AA_F` and any target.
- Save and export to Multiplayer
- Start dedicated server and launch mission
- As a gunner press Tab to lase and shoot at different distance.

**Expected behavior:**
Elevation and leading should change projectile path

**Where did the issue occur?**
- Dedicated

**Additional context:**
Seems like this PR break it.
https://github.com/acemod/ACE3/pull/6965
Prior that PR firedEH was created on all clients and server. Now only on server due to
https://github.com/acemod/ACE3/blob/a9a69ac4ff5c04a0ab7a4c1a4be26a3d8adccd3f/addons/fcs/CfgEventHandlers.hpp#L21-L25

**Comment by commy2** [comment]
@PabstMirror
