### ISSUE TITLE
open Dialog with SelfInteraction

### ISSUE THREAD

**Issue by Sonic47** [acemod/ACE3#7677]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98 stable` 
- **CBA:** `3.15.0`
- **ACE3:** `3.13.2` 

**Description:**
Try to open a BIS Dialog (Dynamic Group) with ace interaction.
On execution game crash without an .rpt error or any other message.
with addacion it work.

**Steps to reproduce:**
setup mission with [Arma_3_Dynamic_Groups](https://community.bistudio.com/wiki/Arma_3_Dynamic_Groups)
Execute that in the Debug consol

> _action = ["GroupMenu","Group Menu","",{([] call BIS_fnc_displayMission) createDisplay "RscDisplayDynamicGroups";},{true}] call ace_interact_menu_fnc_createAction;
> [(typeOf player), 1, ["ACE_SelfActions"], _action] call ace_interact_menu_fnc_addActionToClass;

**Expected behavior:**
I expect that the Dynamic Group Menu pops up

**Where did the issue occur?**
Editor (Singleplayer) / Editor (Multiplayer)

**Log Files:**
None

**Additional context:**

**Screenshots:**

**Comment by commy2** [comment]
Arma crashes when you create a display from inside another display unload event. Wrap your code in execNextFrame and it will work:
```sqf
_action = ["GroupMenu","Group Menu","",{
    {
        ([] call BIS_fnc_displayMission) createDisplay "RscDisplayDynamicGroups";
    } call CBA_fnc_execNextFrame;
},{true}] call ace_interact_menu_fnc_createAction;
[typeOf player, 1, ["ACE_SelfActions"], _action] call ace_interact_menu_fnc_addActionToClass;
```

**Comment by Sonic47** [comment]
Great Thanks. it worked
Didnt know that.
