### ISSUE TITLE
Addon Mismatch. Client has extra addons: "ace_medical_menu"

### ISSUE THREAD

**Issue by Harry666cz** [acemod/ACE3#7678]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98.146373`
- **CBA:** `3.15.1`
- **ACE3:** `3.13.2` 

**Description:**
I tried to connect on friends server but server keeps kicking me out for some reason of Addon mismatch
 
**Steps to reproduce:**
- ubsubscibe/delete all mods
- connect to server, server asked for mods, download them(to be sure that are the same as on server) 
- connect to server, get in lobby, get in game
- after all loadings i am in game but i get (screen1) error, after click ok i got kicked to lobby again

**Expected behavior:**
get ingame?
**Where did the issue occur?**
friend-hosted server

**Log Files:**
https://gist.github.com/Harry666cz/c9db25ff827644a1ba7f46bf20c27a7e

**Additional context:**

**Screenshots:**
error
![IMG_20200502_145543](https://user-images.githubusercontent.com/64694965/80867574-1e9f6600-8c95-11ea-80e0-ed62d5d50e26.jpg)
mods on server
![Bez názvu](https://user-images.githubusercontent.com/64694965/80867600-4262ac00-8c95-11ea-9180-39d1bfdd8a37.png)
![Bez názvu2](https://user-images.githubusercontent.com/64694965/80867640-8c4b9200-8c95-11ea-9a2c-11679ff54c55.png)
![Bez názvu3](https://user-images.githubusercontent.com/64694965/80867723-fa905480-8c95-11ea-8a00-bc41549b75a4.png)

**Comment by commy2** [comment]
```
17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_damage.pbo - a17f108e
17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_engine.pbo - a17f108e
17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_feedback.pbo - a17f108e
17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_gui.pbo - a17f108e
17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_menu.pbo - 7d9a4f47
17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_statemachine.pbo - a17f108e
17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_status.pbo - a17f108e
17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_treatment.pbo - a17f108e
```

`ace_medical_menu.pbo` is a file deleted from a recent update. It is still present in your @mod/addon folder. See build hash: `7d9a4f47` compared to `a17f108e` from the rest.

Delete `M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_menu.pbo` to fix.
Complain to Valve that their Steam Workshop does not work.

**Comment by Harry666cz** [comment]
> ```
> 17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_damage.pbo - a17f108e
> 17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_engine.pbo - a17f108e
> 17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_feedback.pbo - a17f108e
> 17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_gui.pbo - a17f108e
> 17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_menu.pbo - 7d9a4f47
> 17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_statemachine.pbo - a17f108e
> 17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_status.pbo - a17f108e
> 17:02:42 M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_treatment.pbo - a17f108e
> ```
> 
> `ace_medical_menu.pbo` is a file deleted from a recent update. It is still present in your @mod/addon folder. See build hash: `7d9a4f47` compared to `a17f108e` from the rest.
> 
> Delete `M:\!Gamez\steamapps\common\Arma 3\!Workshop\@ace\addons\ace_medical_menu.pbo` to fix.
> Complain to Valve that their Steam Workshop does not work.

Thank you, i didnt know that.

**Comment by Harry666cz** [comment]
Work as a charm btw
