### ISSUE TITLE
Ace Medical Prevent Instant Death bugged

### ISSUE THREAD

**Issue by JBrewer2016** [acemod/ACE3#7681]
Alright so I have been reading multiple closed items about this, all stating back to event handler's. I have attempted utilizing the script listed below.

> _ehid = player addEventHandler ["handleDamage", {}];
> systemChat str _ehid;
> copyToClipboard str _ehid;

So now to go on and explain what I have performed as far as a failed attempt to troubleshoot my problems before coming here and reading off of other tickets similar to this.

Custom set ACE Medical settings on server side along with mission side, which prevent instant death isn't FULLY working.

I.E. 30mm BTR round will kill a player instantly, while small arms fire will down a player unless shot after "uncon" then they die. Which I am trying to make it to were players do not die once "uncon" yes still possibility of bleeding out but not being forced to respawn by getting shot over and over.

Looked into the servers .vars.profile file (Fully dedicated server, Actual Machine) still no joy on fix. 

I need to know what file's to upload to help whom ever can help me get this fixed for my community. Much appreciated for whoever does attempt to help and I will be fully cooperative for this as some people aren't but I am at a loss here for knowledge of fixing this and admit my ignorance at it.

**Comment by commy2** [comment]
Ok, but this is not a forum.
