### ISSUE TITLE
Options menu missing last option

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#769]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *None*

**Description:**
*Options menu is missing last option, at least for me:*
http://steamcommunity.com/sharedfiles/filedetails/?id=428427732

**Steps to reproduce:**
* *Open options menu, last option for setting Pain effect is missing*
* *Litter simulation detail is also missing*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*No script errors found*

**Comment by Glowbal** [comment]
This is fixed by aad8d6b

**Comment by jaynus** [comment]
👍
