### ISSUE TITLE
Fragments wound ppl at extreme distance from explosion.

### ISSUE THREAD

**Issue by PvtKellly** [acemod/ACE3#7691]
Mods:

    ACE3: 3.13.2

Description:

Fragments wound ppl at extreme distance from explosion.

fnc_frago.sqf, Lines 48-49:
private _indirectHitRange = getNumber(configFile >> "CfgAmmo" >> _shellType >> "indirecthitrange");
private _fragRange = 20 * _indirectHitRange * 4;

So 80 x indirecthitrange. Is it a bug or based on something?

Steps to reproduce:

	Just throw some grenades in virtual arsenal.

Expected behavior:
ACE 2 has indirecthitrange x 4 frag radius, feels about to be right.

Where did the issue occur?

    Dedicated / Singleplayer

**Comment by Blutze** [comment]
For performance reasons, frag generates less projectiles than would be realistic and then prioritizes them towards potential targets. The variable you found is used simply for the [radius of that search](https://github.com/acemod/ACE3/blob/master/addons/frag/functions/fnc_frago.sqf#L83), the trajectory of the individual projectiles is left to the engine via an initial vector ([here](https://github.com/acemod/ACE3/blob/master/addons/frag/functions/fnc_frago.sqf#L146-L150) and [here](https://github.com/acemod/ACE3/blob/master/addons/frag/functions/fnc_frago.sqf#L179-L182)) and an [airfriction value](https://github.com/acemod/ACE3/blob/master/addons/frag/CfgAmmo.hpp#L291).

The velocities in ACE are already conservative (using the same formula as real-life estimates and then [multiplying by 0.8](https://github.com/acemod/ACE3/blob/master/addons/frag/functions/fnc_frago.sqf#L74)). If you have sources for flight ranges, feel free to tweak the airfriction values of the fragment ammo classes (especially `tiny_hd`, `small_hd` and `medium_hd`, the only ones used in handgrenades) and report back. Those are simple config entries, you can easily do this through a config patch mod.

**Comment by PvtKellly** [comment]
> 
> 
> For performance reasons, frag generates less projectiles than would be realistic and then prioritizes them towards potential targets. The variable you found is used simply for the [radius of that search]
> 
Yep. I figured out how its works.

> If you have sources for flight ranges, feel free to tweak the airfriction values of the fragment ammo classes (especially `tiny_hd`, `small_hd` and `medium_hd`, the only ones used in handgrenades) and report back. Those are simple config entries, you can easily do this through a config patch mod.
> 

Will look a bit later.

> I do agree that 320-480 meters for that search radius on handgrenades is a bit optimistic though.

Not just "a bit optimistic", but put absolutely unnecessary search/trace load on CPU (since chance to hit/kill at such distance is effectively nil). Think is much better to trace 50 fragments in 30m radius instead of 10 fragments quarter of a mile.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
