### ISSUE TITLE
ACE Range card not populating fully/correctly

### ISSUE THREAD

**Issue by Harzach** [acemod/ACE3#7693]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98.146373 stable`
- **CBA:** `3.15.1.200418 stable`
- **ACE3:** `3.13.2.49 stable`

**Description:**
The ACE range card does not populate correctly. Only the 10 degree Celsius columns populate, all other columns are filled with # symbols. Screenshot attached.

**Steps to reproduce:**
- Create a simple mission on any terrain with one unit, an arsenal, and with Advanced Ballistics enabled
- Play mission
- Take any rifle, any supported high-powered scope, and any supported ammunition, along with a range card and a Kestrel
- Open Kestrel, take readings, open range card

**Expected behavior:**
Range card should populate fully, with elevation and windage values for all temperatures

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Log Files:**
- https://gist.github.com/Harzach/6e048097b87881785b6892893da35490#file-arma3_x64_2020-05-07_16-40-14-rpt

**Additional context:**
n/a

**Screenshots:**
![rangecard](https://user-images.githubusercontent.com/64987966/81346260-fe521b80-9087-11ea-89e4-a283c0ec6370.png)

**Comment by Harzach** [comment]
`Enable Ammo Temperature Simulation` was disabled and I didn't see it. I'm an idiot.

**Comment by jonpas** [comment]
Hahaha. :D
