### ISSUE TITLE
ACE AIR MFD

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#77]
ACE had a small MFD for apache target and laser code selection and designation. Need to re-do this for Laser code selection. Currently, all lasers and missiles utilize laser code 1001.

**Comment by AtomicTim** [comment]
Is there anyway to override the PIP distance limit? Especially for aircraft...for example the Lowlands apache mod has an option to show the gunner view for the pilot, but it is useless in most cases.

**Comment by esteldunedain** [comment]
> Is there anyway to override the PIP distance limit?

@AtomicTim, not that we know of.

**Comment by AtomicTim** [comment]
Shame

**Comment by PabstMirror** [comment]
#3594
