### ISSUE TITLE
Flashbang is making pain through walls

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#770]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *Advanced medical system*

**Description:**
*Flashbang grenades are making pain to players through walls.*

**Steps to reproduce:**
* *Get some flashbangs*
* *Smash a window and throw flashbang through it OR throw it over obstacle*
* *Get to cover, not too close, not too far from where you thrown it*
* *Bang! And you are in pain*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*Not needed*

**Comment by PabstMirror** [comment]
Where you getting the screen whiteout effects as well or just pain?

**Comment by gienkov** [comment]
White borders and I was in pain.

**Comment by PabstMirror** [comment]
Prevented adding pain if the strength is low.
The other possibility is the LOS check is failing and saying there is LOS through a wall.  We might need to change line 59 to 
`if (_losCount <= 1) then {`

**Comment by alganthe** [comment]
Still happening, the LOS check seems to fail indeed, and the grenade emit a small trail of smoke now.
