### ISSUE TITLE
Make realistic names optional

### ISSUE THREAD

**Issue by felixlinker** [acemod/ACE3#7703]
**Is your enhancement related to a problem?**
My community and I get confused over realistic names. Some only know Vanilla names; others only know ACE names. We often have problems communicating. Also, we don't see much value in realistic names.

**Solution you'd like:**
Make realistic names optional.

**Comment by commy2** [comment]
Remove the PBO file. It cannot be made optional without removing the PBO file.

**Comment by felixlinker** [comment]
We tried that. However, our server admin mentioned that upon loading the preview in the editor, i.e. going "in-game", he was prompted the error: `"ace_realisticnames out of date"` and then thrown back into the editor. I wasn't able to reproduce this. Do you have any idea what could cause this?

**Comment by commy2** [comment]
OoD will not throw you back into the editor.
