### ISSUE TITLE
ACE Door Opening – Opens Unrelated Doors

### ISSUE THREAD

**Issue by Quailsnap** [acemod/ACE3#7707]
**Mods (complete and add to the following information):**
- **Arma 3:** steam stable (as of date)
- **CBA:** as above
- **ACE3:** as above
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_ ✔️

**Description:**
Using ACE incremental door opening on certain buildings, chiefly this popular Livonia building (vanilla), opens multiple unrelated doors at once. Vanilla behavior (scroll menu) does **NOT** do this.

**Steps to reproduce:**
- place a unit near any instance of this building on Livonia
- interact with the left front door with ACE incremental door opening
- notice two other doors in the building opening along with it

**Where did the issue occur?**
- Singleplayer

**Video:**
https://youtu.be/r0x30unJI-Q

**Comment by ColdEvul** [comment]
Using the Zen door open moduel it's easy to replicate this  this behavior as well. Seams only to be isolated to Levonia buildings.
