### ISSUE TITLE
RHS USAF ACE Compatibility Mod Error - no entry 'bin\config.bin/CfgVehicles/RHS_CH47F/UserActions/OpenCargoDoor.displayName'.

### ISSUE THREAD

**Issue by SkyeGuy** [acemod/ACE3#7708]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96'
- **CBA:** `stable'
- **ACE3:** `stable'
- **RHS USAF**
- **ACE Compat - RHS United States Armed Forces**

**Description:**
There is a popup error message in editor and in the dedicated server console if a RHS USAF CH-47F Chinook is placed in-editor, or if a mission file with a Chinook entity present is loaded-in.

'bin/config.bin/CfgVehicles/RHS_CH47F/UserActions/OpenCargoDoor.displayName' .

**Steps to reproduce:**
- Load / open Arma 3 with above mods.
- Open editor.
- Place RHS USAF US Army Chinook CH-47F. Receive error.
- Load previously saved mission with Chinook - Receive error.

**Expected behavior:**
No error to occur when placing / loading saved missions.

**Where did the issue occur?**
- Occurs during the dedicated server bootup. Occurs in editor. I don't believe the player sees it directly when connecting to dedicated server or when loading into mission.

**Additional context:**
Seems like a minor, harmless error message as it doesn't prevent players from joining nor does it prevent the server from loading the mission file completely; however it is still an error message.

I have already filed an issue tracker with the RHS USAF devs and we determined that it was this compatibility mod that was the culprit after further testing. If you test WITHOUT the compat mod (just CBA, ACE, RHS USAF) - no error occurs.
http://feedback.rhsmods.org/view.php?id=5676

**Comment by commy2** [comment]
Needs RPT log file.

**Comment by SkyeGuy** [comment]
I will have to get back with y'all tonight or tmrw on the RPT server logs but I can at least give y'all a screenshot of the popup that fires off in editor, as that is also part of the issue.

![RHSUSAF_ACE_Compat_editor_error](https://user-images.githubusercontent.com/20469914/81757041-1dcfb680-9483-11ea-8f60-dd8b2fd9249d.png)

**Comment by SkyeGuy** [comment]
The issue also occurs when booting Arma 3 fresh, opening a new mission, and placing down a CH-47F Chinook from the RHS USAF -> US Army -> Helis faction.

**Comment by ramius86** [comment]
https://pastebin.com/gCGGBqJx
Line 1248
`13:34:33 Warning Message: No entry 'bin\config.bin/CfgVehicles/RHS_CH_47F/UserActions/OpenCargoDoor.displayName'.
13:34:33 Warning Message: '/' is not a value
13:34:33 Warning Message: No entry 'bin\config.bin/CfgVehicles/RHS_CH_47F/UserActions/OpenCargoDoor.radius'.
13:34:33 Warning Message: '/' is not a value
13:34:33 Warning Message: No entry 'bin\config.bin/CfgVehicles/RHS_CH_47F/UserActions/OpenCargoDoor.condition'.
13:34:33 Warning Message: '/' is not a value
13:34:33 Warning Message: No entry 'bin\config.bin/CfgVehicles/RHS_CH_47F/UserActions/OpenCargoDoor.statement'.
13:34:33 Warning Message: '/' is not a value
13:34:33 Warning Message: No entry 'bin\config.bin/CfgVehicles/RHS_CH_47F/UserActions/OpenCargoDoor.onlyForPlayer'.
13:34:33 Warning Message: '/' is not a value
13:34:33 Warning Message: No entry 'bin\config.bin/CfgVehicles/RHS_CH_47F/UserActions/OpenCargoDoor.position'.
13:34:33 Warning Message: '/' is not a value
13:34:33 Warning Message: No entry 'bin\config.bin/CfgVehicles/RHS_CH_47F/UserActions/CloseCargoDoor.displayName'.
13:34:33 Warning Message: '/' is not a value
13:34:33 Warning Message: No entry 'bin\config.bin/CfgVehicles/RHS_CH_47F/UserActions/CloseCargoDoor.radius'.
13:34:33 Warning Message: '/' is not a value
13:34:33 Warning Message: No entry 'bin\config.bin/CfgVehicles/RHS_CH_47F/UserActions/CloseCargoDoor.statement'.
13:34:33 Warning Message: '/' is not a value
13:34:33 Warning Message: No entry 'bin\config.bin/CfgVehicles/RHS_CH_47F/UserActions/CloseCargoDoor.onlyForPlayer'.
13:34:33 Warning Message: '/' is not a value
13:34:33 Warning Message: No entry 'bin\config.bin/CfgVehicles/RHS_CH_47F/UserActions/CloseCargoDoor.position'.
13:34:33 Warning Message: '/' is not a value`

**Comment by Fyuran** [comment]
RHS_CH_47F in @ace_compat_rhs_usf3 does not seem to inherit the subclass UserActions of RHS_CH_47F_base
