### ISSUE TITLE
Explosives from the RHS mod not compatible with ACE mod. 

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#7714]
**Mods (complete and add to the following information): @RHSSAF,@RHSAFRF**
- **Arma 3:** `1.96` stable
- **CBA:** `3.15` stable
- **ACE3:** `3.13` stable

**Description:**
TM-100/200/500 and in general all explosives from the RHSSAF/RHSAFRF mod do not have a matching explosives interface. 

**Steps to reproduce:**
- Take in VRAsenal TM-500, TNT or other any mine from RHS mod
- Place it like a C4 charge
- See what is no any interactions

**Comment by Whigital** [comment]
**RHS:AFRF** explosives should be fully compatible with the above pull, however, there currently isn't a compat for **RHS:SAF**.

**Comment by Whigital** [comment]
Added compatibility for **RHS:GREF** too ....

**Comment by Whigital** [comment]
Remaining incompatible explosives from **RHS:USAF** also added ....

**Comment by mharis001** [comment]
Closing as fixed by #7734 , #7735 , and #7736 .
