### ISSUE TITLE
WIKI - Coding guidelines (Section 5.4) incorrect example

### ISSUE THREAD

**Issue by EM-Creations** [acemod/ACE3#7717]
**Mods (complete and add to the following information):**
- **Arma 3:** N/A
- **CBA:** N/A
- **ACE3:** N/A

**Description:**
[This wiki page](https://ace3mod.com/wiki/development/coding-guidelines.html#211-func-macros-call-tracing-and-non-ace3anonymous-functions) has an incorrect example. It looks like this has happened during a copy and paste to post a real "bad" example. **Section 5.4**, the first "Bad" example is an exact duplicate of the preceeding "Good" example, so naturally is quite confusing to the reader.

**Steps to reproduce:**
- Go to [this wiki page](https://ace3mod.com/wiki/development/coding-guidelines.html#211-func-macros-call-tracing-and-non-ace3anonymous-functions) and scroll to **Section 5.4**.
- Read

**Expected behavior:**
Correct examples are given.

**Where did the issue occur?**
- N/A

**Log Files:**
- N/A

**Additional context:**
No.

**Screenshots:**
![image](https://user-images.githubusercontent.com/8123733/82357390-f3d74080-99fc-11ea-8ad9-09b714fcfb44.png)

**Comment by EM-Creations** [comment]
Ignore this, I was being dumb.

**Comment by jonpas** [comment]
It's talking about comments. :D
