### ISSUE TITLE
Spalling script error

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#7727]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98` [stable]
- **CBA:** `3.15.1.200418` [stable]
- **ACE3:** `ace3_3.13.2` [stable]

**Description:**
Hi, for many recent ACE3 versions  [I see an error message](https://drive.google.com/file/d/1-l8a6NSO-HVEqbr4Mj5cRPqHZqpmfpY3/view?usp=sharing) 
I was hoping this would be fixed, but for more than half a year now I have been seeing this.
However, this may be my fault.
I use ACE3 modularly.  I remove  ace_ai.pbo and was forced to remove also  ace_zeus.pbo because they are interconnected with ace_ai.

a) This error message related to removing some PBOs or not? If so, then there should not be an error because ACE is a modular mod, parts of which the player can switch off. If I'm wrong, then correct me.

b) If the error is not related to switch off some modules, then please correct this error

**Steps to reproduce:**
play ACE3

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Screenshots:**
https://drive.google.com/file/d/1-l8a6NSO-HVEqbr4Mj5cRPqHZqpmfpY3/view?usp=sharing

**Comment by dedmen** [comment]
Needs RPT I think.

**Comment by commy2** [comment]
Nah, you're supposed to type out the screenshot, silly.

**Comment by ZeusWrath** [comment]
> Nah, you're supposed to type out the screenshot, silly

dude this isn't just a screenshot. There is indicated the path and line number on which the error is. It is not silly for this reason already. I thought you could understand what this error is about. If this information is not enough for you, then I will try to wait until the moment when I receive this error again and provide you with RPT, ok

**Comment by commy2** [comment]
That would be sweet.

**Comment by ZeusWrath** [comment]
Hi! 

I was able to get my rpt and your errors at the same time - https://drive.google.com/file/d/1qHc4cZa7YYgILKz9gNSQE-mXywZ8XETg/view?usp=sharing

An error with a link to ace3 fragmentation appears quite often (every 5 minutes), I also get a drop in game performance, @commy2 Please see my file, maybe this is due to this error?

probably this info can be useful: 

if (!lineIntersects [_pos1, _pos2]) exitWith >
 0:49:28   Error position: <lineIntersects [_pos1, _pos2]) exitWith >
 0:49:28   Error 0 elements provided, 3 expected
 0:49:28 File z\ace\addons\frag\functions\fnc_doSpall.sqf..., line 67
 0:49:28 Error in expression <torMultiply (0.01 * (_i + 1)));

**Comment by ZeusWrath** [comment]
hi @ commy2, did you track the bug?

**Comment by commy2** [comment]
I don't maintain the component. I always tell people to turn it off.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
