### ISSUE TITLE
Possible Muzzle Velocity ammo mismatch between AtragMX and Ballistics database

### ISSUE THREAD

**Issue by regiregi22** [acemod/ACE3#7732]
**Mods (complete and add to the following information):**
-Arma - 1.98.146373
-CBA - 3.15.1.200418
-ACE3 - 3.13.2.49

**Description:**
Muzzle Velocity don't match between the AtragMX gun profile and value set in Ballistics for the M200 Intervertion (srifle_LRR_F) when using .408 7Rnd Mag (7Rnd_408_Mag,) (419gr ammo, B_408_Ball).

If updated, G1 drag coefficient **"may"** have to be updated too, as muzzle velocity is an involved parameter when converting a coefficient from G7 to G1 (as AtragMX only accepts G1, and this ammo is defined in Ballistics as G7):
http://www.jbmballistics.com/cgi-bin/jbmgf-5.1.cgi
(Checked here on convert from G1 to G7: https://ace3mod.com/wiki/feature/atragmx.html)

**Steps to reproduce:**
-On a freshly made mission, open the AtragMX and load ".408 CheyTac 419gr" profile, it shows MV: 859.
It could be checked against values shown on ACE Arsenal for this rifle and magazine, it shows MV: 867.

-It can be checked in Ballistics that MV is set at 867 (B_408_Ball) Line 519:
https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgAmmo.hpp
ACE_muzzleVelocities[]={867};

-In magazines (7Rnd_408_Mag) Line 403:
https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgMagazines.hpp
initSpeed = 867;

-Weapon (LRR_base_F) Line 23:
https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgWeapons.hpp
initSpeed = -1.0;

AtragMX gun profile (.408 CheyTac 419gr) Line 45:
https://github.com/acemod/ACE3/blob/master/addons/atragmx/functions/fnc_initGunList.sqf
"[".408 CheyTac 419gr",  859,"

**Expected behavior:**
Muzzle velocity values for standard atmospheric values should match between what is defined on the AtragMX gun profile and the real value as defined in Ballistics (when having initSpeed = -1.0 in the weapon).

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
-Not needed.

**Additional context:**

**Screenshots:**

**Comment by Blutze** [comment]
`initSpeed` on weapon and magazine are for vanilla ballistics, and are supposed to model the average temperature on Altis, ~21°C. Advanced ballistics uses `ACE_barrelLength` on the gun and an interpolation between `ACE_barrelLengths[]` and `ACE_muzzleVelocities[]`.

> "[".408 CheyTac 419gr", 859,"

This first value is just a fallback for 15°C, in case the following is not defined:
> // Profile Name, Muzzle Velocity, Zero Range, Scope Base Angle, AirFriction, Bore Height, Scope Unit, Scope Click Unit, Scope Click Number, Maximum Elevation, Dialed Elevation, Dialed Windage, Mass, Bullet Diameter, Rifle Twist, BC, Drag Model, Atmosphere Model, **Muzzle Velocity vs. Temperature Interpolation**, C1 Ballistic Coefficient vs. Distance Interpolation, Persistent`

`[[-15,840],[0,847],[10,854],[15,859],[25,873],[30,882],[35,893]]`
If you set the temperature on the Atrag to 21°, you will see the muzzle velocity jump to 867 m/s.

The real issues here are that 1) the Atrag does temperature interpolation even when Advanced Ballistics is disabled, and 2) the ACE Arsenal displays Advanced Ballistics values as the only truth, when there actually are two truths.

**Comment by regiregi22** [comment]
OK, now I understand it.
I have just tested it, ACE Arsenal shows the muzzle velocity equivalent to 21ºC, while ATragMX (by default) is set up at 15ºC. 
As soon as I set ATragMX temperature at 21ºC, it jumps to 867!

Thank you for the explanation, I will close this case.
