### ISSUE TITLE
Consume surgical kit

### ISSUE THREAD

**Issue by Tress16** [acemod/ACE3#7737]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.1.200418` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.2.49` [eg. 3.0.0 stable, commit hash]

**Description:**
If you stop sewing bevor end, the surgical kit will not be consumed and you can use it endless.

**Comment by BaerMitUmlaut** [comment]
The surgical kit stitches wounds while you use it. I suppose it should disappear when the first wound is stitched?

**Comment by Tress16** [comment]
If you stop bevore the last wound is stitched the surgical kit will not be consumed.
Maybe the best way would be to remove the kit before sewing for the first time?

**Comment by veteran29** [comment]
Making it a magazine and removing ammunition from it for every wound sewed could work well.

**Comment by Drofseh** [comment]
> Making it a magazine and removing ammunition from it for every stitched wound could work well.

That might be the best solution.
Removing it near the beginning of the action doesn't seem fair for medics whose stitching is interrupted involuntarily by things beyond their control.

**Comment by BaerMitUmlaut** [comment]
This would be a completely different behaviour to the current state, which allows one application of the kit, whether you close 1 or 100 wounds. I personally think that would be a good idea, but someone out there might not.

**Comment by dedmen** [comment]
> but someone out there might not.

config option?

**Comment by veteran29** [comment]
Do we even have commands to manage ammo of the mag in inventory?

**Comment by BaerMitUmlaut** [comment]
You can remove all of the surgical kit magazines, then readd them with one having one less ammo. It's quite hacky but I've done it before for a scuba prototype.

**Comment by SilentSpike** [comment]
How about, remove the surgical kit on treatment start. Then if treatment ends before halfway through, re-add it?

**Comment by BaerMitUmlaut** [comment]
If you'd abort before the first wound is closed you'd still lose the kit. I'm not sure if that's a good idea from a gameplay perspective. 

If we think of it like a pack of latex gloves, you'd put them on when starting the action, then dispose of them when you abort. Then it _would_ make sense that you'd lose them, but it might seem unfair to the player.

>Making surgical kit last for X number of wounds (requires some system of tracking number and storing it per kit item)

That's the whole idea behind magazine surgical kits.

**Comment by veteran29** [comment]
We could also remove progressive stitching if kit removal is enabled and stitch all wounds at the end. But that is not ideal either.

**Comment by SilentSpike** [comment]
We could keep progressive stitching, but reopen the wounds if treatment is aborted/interrupted and the consumption setting is enabled

**Comment by NeTrox0** [comment]
> reopen the wounds if treatment is aborted/interrupted and the consumption setting is enabled

Not really sure if wounds should just reopen if you have stitched them. 
In this case the progresive stitching would be a waste? I do really like that feature.

> * Remove kit on start and accept that players need to ensure they're safe before starting surgery (or risk wasting their kit)

I think, if the kit is to be consumed remove it after the first wound has ben progressivly stitched.
But as stated before this would likely waste the kit if not secure before stitching is started. 
Alltho this seems like a question when to start stitching at all?

**Comment by Tress16** [comment]
Will we get a solution for this?
It is really important for us and our mission.

**Comment by Drofseh** [comment]
Could make the setting have 3 states:

Do not consume
Consume at start
Consume at end

Then communities can choose which suits them best. 

Not as good as removing after X wounds, but much easier to implement.

**Comment by LinkIsGrim** [comment]
Alternate solution made available by #9020. Not really any good way to fix this.
