### ISSUE TITLE
Task: MicroDAGR - use ctrlSetAngle instead of Map Control

### ISSUE THREAD

**Issue by bux** [acemod/ACE3#7738]
**Is your enhancement related to a problem?**
Under some circumstances map markers are visible on the microDAGR compass

**Solution you'd like:**

commy:
>Using a map control is a technique introduced by the shacktak squad radar (popularized at least, no idea who came up with it first) to rotate a control.

**Additional context:**
![20200527191002_1](https://user-images.githubusercontent.com/1235520/83102256-5c38b880-a0b4-11ea-80ad-dc1e9a3989b3.jpg)
https://github.com/KillahPotatoes/KP-Liberation/issues/801

**Comment by PabstMirror** [comment]
`#define DUMMY_POS [-1,-1]` 
can probably just change this to [-3000 or something way out there
