### ISSUE TITLE
Static Titan AT still can't guidance to enemy

### ISSUE THREAD

**Issue by Arkblade2015** [acemod/ACE3#774]
Mods:

@cba_a3
@ace3

Placed ACE3 Modules:
ace_javelin
ace_missileguidance

Description:
Static Titan AT still can't guidance to enemy.
missiles are gone to somewhere when lock on and fire.

Steps to reproduce:
none

Where did the issue occur?
"Singleplayer"*

**Comment by jaynus** [comment]
Is this with latest build? What class name? Are you sure its AT with AT missiles?

**Comment by Arkblade2015** [comment]
yes, i using latest build. and i just use "blufor" > "nato" > "static" > mini-spike launcher (AT)

**Comment by jaynus** [comment]
No repro for me, i placed all the AT launchers and they work - every single one of them. AA launchers do not.

Tested:
I_static_AT_F
O_static_AT_F
B_static_AT_F

**Comment by Arkblade2015** [comment]
need to be fire.
they can lock on. but fired missiles are can't guidance to enemy.
if you need movie, i can put it.

**Comment by bux578** [comment]
> if you need movie, i can put it.

Yes, please.

**Comment by Arkblade2015** [comment]
https://www.youtube.com/watch?v=T9ufoY1ep_c

i using latest build from master.
