### ISSUE TITLE
Increasing the player critical damage threshold or disable player unconsciousness

### ISSUE THREAD

**Issue by JACates** [acemod/ACE3#7743]
Hello,

I would like the ability to be able to push the player critical damage threshold higher than 25 or find a way to disable player unconsciousness. The situation I am trying to create is that the only way for a player to die is from purely blood loss causing the heart to stop. I figure the best way to achieve that in the current system is making player critical damage so high that nothing can put the player into the unconscious state or disabling unconsciousness all together however I cannot seem to find a way to do that. Thank you for all the hard work you guys do!

PS: I am part of a Space Marine unit and am trying to replicate their toughness while still using all the cool features of ACE.

**Comment by severgun** [comment]
>The situation I am trying to create is that the only way for a player to die is from purely blood loss causing the heart to stop.

Don't treat wounds and you will die because of blood loss.
