### ISSUE TITLE
Let units fastrope waypoint seems to get skipped if you change seat while it's active or if you join the vehicle while it's active

### ISSUE THREAD

**Issue by FluffyGhoster** [acemod/ACE3#7754]
**Mods (complete and add to the following information):**
- **Arma 3:** `steam latest`
- **CBA:** `steam latest`
- **ACE3:** `steam latest`

**Description:**
If one helicopter mained by an AI pilot have a Let units fastrope waypoint and only one player is inside the helicopter and the player change seat with the ACE interaction menu, or if the waypoint gets assigned and no player is inside it (even if the player gets inside after), the helicopter will stop in air and not move toward the waypoint

**Steps to reproduce:**
-  Place an helicopter that can fastrope and give it a fastrope waypoint, after a stop waypoint that will get skip on trigger
- Enter the helicopter and skip the trigger, the helicopter will takeoff and move toward the waypoint
- Use ACE interaction to change seat
- The helicopter will perform a full stop and say in air, it will not reach the waypoint

**Expected behavior:**
The unit will reach the waypoint and then move to the next one, if there are people inside it it will not skip the waypoint in any case

**Where did the issue occur?**
- Editor (Singleplayer)

**Log Files:**
- [https://pastebin.com/EhK5S6AX](https://pastebin.com/EhK5S6AX)

**Screenshots:**
![image](https://user-images.githubusercontent.com/65877598/84558246-b468ef00-ad31-11ea-817f-604fd2f1285c.png)
![image](https://user-images.githubusercontent.com/65877598/84558271-eb3f0500-ad31-11ea-8c5e-b3418bc97d31.png)

**Comment by EvilItalianK** [comment]
Sorry I just noticed the editor had not picked up part of the text, i have fixed the issue description and the steps to reproduce

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
