### ISSUE TITLE
Laggy MicroDAGR when in helis/planes

### ISSUE THREAD

**Issue by rlex** [acemod/ACE3#777]
ACE3 Version: https://github.com/acemod/ACE3/commit/f928f37e264bdbb7b476e1c4a5d9f8d958a0d7b3

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
* MicroDAGR lags in map mode when you move in planes / helis (or maybe just fast?)

**Steps to reproduce:**
* Open editor
* Place heli (i used Little Bird for example)
* Open microdagr, switch it to map mode
* Fly around. Notice lagging on map display.

**Where did the issue occur?**
* VR, SP

**RPT log file:**
* (absent from my gaming PC now, cannot provide RPT right now)

**Comment by esteldunedain** [comment]
This not technically a bug: our microDAGR is programmed to update every 0.1s, which looks bad for fast moving vehicles.

Maybe that makes sense for the text indicators (velocity, coordinates, etc), but we should adjust the map position every frame, changing the `GVAR(gpsPositionASL)` directly on the `mapOnDrawEH` function. 

IDK how fast does the RL thing updates, but even my cheap car gps fluidly scrolls the display while driving.

**Comment by jaynus** [comment]
This is correct; the positional updates should pull every frame no matter what; while the rest of the updates can be behind.

**Comment by rlex** [comment]
i'm going to assume there is no need for RPT, then?

**Comment by jaynus** [comment]
Correct - we don't need it :thumbsup:

**Comment by rlex** [comment]
Good. MicroDAGR is so much better than A3 GPS, and it also allows to carry both UAV and GPS.

**Comment by PabstMirror** [comment]
I think I had plants for signal interference//jamming//spoofing at one point, but probably not going to do anything like that for a while.

In reality gps can't update every frame, BUT it would also do interpolation to give a smooth path which I wasn't doing.
