### ISSUE TITLE
Repair Issue (Realted to ACE Logistics settings)

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#7779]
**Mods (ACE, CBA, JSRS-Soundmod):**
- **Arma 3:** `1.98` [stable]
- **CBA:** `3.x.x` [3.15.1.200418 stable]
- **ACE3:** `3.13.2` [stable]

**Description:**

Good day.

ACE Logistics settings

http://images.vfl.ru/ii/1593368440/1f23d3b3/30936836.jpg

Repair Treshold - 0.6
Repair Treshold (Engineer) - 0.4

The description says, that this determines the _maximum amount of damage that can be repaired by means ToolKit_.  

I tried to vary these values - It seems that this settings does not have any obvious result, since regardless of the level of damages the repair ability by means ToolKit is always available, even if the damage threshold is higher than what the settings require.  This is looks as error, otherwise, there is no point for these repair treshold settings.

**Steps to reproduce:**
Change repair settings in ACE logistics and have a subordinate engineer and order to him repair a critically damaged vehicle. Order to repair will be always available. It looks contradictory, please try to fix it. 

**Expected behavior:**

If the damage threshold is higher than the maximum threshold in the ACE logistics settings, then the repair by means ToolKit  should not be available, for both - the player and AI.   AI must respond - "Negative" to execute for inaccessible repair  or any other solution. Also ACE team, if this possible, please extend the repair time in any way possible, since so small time - (5 second for any damage!) seems absurd for any repair operation.

**Comment by ZeusWrath** [comment]
I thought, maybe the "Repair Treshold" settings only work for the human player, and ignore the AI. In this case, the ai-repair ability must be disabled  (accept the order), if the damage threshold is higher than that specified in the ACE losistic settings. It might be a good solution

**Comment by BaerMitUmlaut** [comment]
AI uses the vanilla repair system, not the ACE system, because AI cannot use ACE interaction system.

**Comment by ZeusWrath** [comment]
> AI uses the vanilla repair system, not the ACE system, because AI cannot use ACE interaction system.

Is this fair? 
Please create a balance in which Human player = AI player, or at least simulate this, as Arma - this AI in the game is of great importance.  
**You can’t just block the ability of AI to repair, if the degree of vehicle damage > than the maximum treshold value?**
This will restore the balance between human Player and AI player

**Comment by BaerMitUmlaut** [comment]
> You can’t just block the ability of AI to repair, if the degree of vehicle damage > than the maximum treshold value?

Nope, not possible.
AI will not repair vehicles on their own, so the AI has no advantage against the player, rather a disadvantage.

**Comment by ZeusWrath** [comment]
> Nope, not possible.
> AI will not repair vehicles on their own, 

Dude, you don't understand what I'm talking about? Your answer is completely off topic;D 
I do not urge you to force AI to repair vehicles yourself. I urge you to block the AI ability to repair, if the threshold does not match the ACE Logistic settings - it's so easy to understand. For example, so that the player commander could not use the AI for repair if the damage threshold does not match the ACE Logistic settings. 

For example, so that the player-commander could not use the AI for repair if the damage threshold does not match the ACE Logistic settings. 

> so the AI has no advantage against the player, rather a disadvantage.

Lol! Can't you see an advantage!?  There are not even one but several:

**First advantage** - AI will repair any vehicle in 5 seconds, while the human player will repair the tool much longer! 
 First, one wheel, then a turret, then a hull, then the main gun, and so on - this is how repair works for a human player in ACE.

**The second and main advantage** of AI, is its independence from ACE Logistic settings.  If the player depends on this, then there is no AI. For example, if the maximum Damage Threshold that a player can repair using ToolKit may be 0.6, if the damage is above this threshold, the player will no longer be able to repair vehicle, while the AI do not give a damn about these settings. He will repair any vehicle with any threshold of damages!

You do not understand what I'm talking about?  so trying to explain to you)))

**You can easily fix this - just block the repair ability for the AI, according to the ACE Logistics settings.**

Do you understand now?

**Comment by BaerMitUmlaut** [comment]
I understood very well what you meant. It's not possible to use the damage threshold from the setting for AI repairs. This is a hardcoded vanilla action that cannot be modified.

And again, AI does not repair vehicles on their own. They will only repair vehicles when the player commands them to. If the player wants to cheat himself, that's fine by me, there is no way to stop that.

**Comment by ZeusWrath** [comment]
> 
I understood very well what you meant. It's not possible to use the damage threshold from the setting for AI repairs. This is a hardcoded vanilla action that cannot be modified.

ok i can't argue with you, because you know better

> And again, AI does not repair vehicles on their own. They will only repair vehicles when the player commands them to.

but here you are wrong. **AI will always repair independently (!without player) any vehicles, if there is an engineer or repair specialist in AI-squad.**  This is how Arma3 works, but the problem that I mentioned above will create an imbalance between the player and the AI player.

Good luck!

**Comment by BaerMitUmlaut** [comment]
Looks like you're right about the AI repairing. I've literally never seen that happen before, very interesting.
