### ISSUE TITLE
No interactions with TM-100/200/500

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#7785]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98`
- **CBA:** `3.15.0`
- **ACE3:** `3.13.3` 

**Description:**
Explosives TM-100/200/500 from mod RHS not working, it is look like any interactions was missed. 

**Steps to reproduce:**
- take 'rhssaf_tm200_mag'
- try place it

**Comment by Whigital** [comment]
What are the thoughts about adding an RHS:SAF compat ?

I can handle the explosives, but that's about it, unless *someone* wants contribute.

Haven't looked at any of the SAF configs, but since it depends on USAF & AFRF, weapons, ammo, mag, vehivles etc might get compat values inherited already.

**Comment by Blutze** [comment]
There are already at least some SAF weapons referenced in the GREF compat component: https://github.com/acemod/ACE3/blob/master/optionals/compat_rhs_gref3/CfgWeapons.hpp#L65-L79
Somehow, loading that without SAF doesn't give any errors on loading into the game or into a mission, but I would assume anything that iterates over all weapons checking for a config property would error out, so... shouldn't the component require SAF already?

- M84 is included in GREF compat, and its belt inherits from the PKM mags
- Skorpion does not inherit from vz 61, but uses those magazines and ammo; theres no compat stuff for that one anyway
- RBR-M80 (singleshot disposable launcher) does not inherit from M72, but its magazine and ammo inherit from the RPG26
- CZ99 and its magazines do not inherit from M9, but it uses ammo from USAF
- BRK antitank handgrenade classes do not inherit from the ones in AFRF, except for the penetrator
- All RHS flashbangs etc. inherit ACE frag from the vanilla handgrenade, making them more less-lethal than non-lethal
- Other SAF grenades don't inherit from anything in the RHS packs, but do inherit sensible stats from vanilla items
- MRUD claymores can be ACE-set to a pressure plate trigger that is located arount the body of the mine for the tripwire variants; no clue where it is for the "remote" variant
- PMA and TMA mines inherit apparently correct pressure plate behavior from somewhere; TMA correctly ignores personnel
- The tracer mag for the M76 is in SAF for some reason, GREF only has ball
- No pilot helmets, goggles or NVGs, no wirecutter backpacks, at least none that are `scope=2` and visible in the arsenal
- Medics inherit from some very basic base class, not AAF/CSAT medics, but apparently we don't need to touch them anyway
- Mig29 pilots inherit from AFRF helo pilots, but _those_ have a better gforce coeff than vanilla helo pilots

Couldn't find anything else that wasn't just effectively a reskin, so it boils down to... C4, claymores, G36s and a PKM.

**Comment by Whigital** [comment]
Seems there are a lot of duplicates between GREF and SAF. I've loaded up UASF, AFRF and SAF, and the M21, G36, M70 i've added is already in the GREF compat, so there is overlap between GREF and SAF.

**Comment by Blutze** [comment]
`rhs_weap_m21a_pr_pbg40`, `rhs_weap_m84` and the G36s are SAF only and should be migrated to SAF compat.
`rhs_weap_m21` is not a thing at all and can be removed from GREF compat.
The remainder of existing M21 and M70 related code should be duplicated between the two compats.

Looks like I missed something in my initial trawl: `rhssaf_ammo_762x39_m82_api` inherits from `rhs_B_762x39_Ball`, which probably has different ballistic properties.

I don't see anything else M21 or M70 related that needs to be added.

**Comment by Whigital** [comment]
Yeah, I'll leave GREF compat out of this completely and make a separate PR for the cleanup. I've tested loading both (GREF and SAF) with compats loaded, and couldn't see anything breaking, so I'll focus on getting the SAF compat finished.

**Comment by Whigital** [comment]
Fixed in https://github.com/acemod/ACE3/pull/7793

**Comment by bux** [comment]
Can we close this issue then?

**Comment by Whigital** [comment]
Can't speak for the author of the issue, but yes, the issue was resolved in the above mentioned PR.
