### ISSUE TITLE
Pain doesnt go away and damage stays after death

### ISSUE THREAD

**Issue by E3VL** [acemod/ACE3#7787]
Me and friends downloaded star wars mods and i noticed a problem during a mission i setup for us to play... If you get shot, you can bandage and it work but if you use morphine and the star wars version of morphine the pain doesnt go away.. it stays. Another problem, say you get shot in the chest and then die, upon respawn that damage stays so you die instantly again. We did some testing and tried troubleshooting but cant find the problem. It was only after these mods were downloaded that these problems occured. I have messaged other people in the Star Wars milsim arma community and none of them have this problem so i have no clue as to what the problem is. Please help, much appreciated.

**Comment by bux** [comment]
Please fill out the provided template. And supply as much information as possible.

**Comment by BaerMitUmlaut** [comment]
OP doesn't respond after a month+, closing.
