### ISSUE TITLE
Mismatch Error with server/clients

### ISSUE THREAD

**Issue by itsmarsl** [acemod/ACE3#7789]
Our Arma server has a newer version from ACE (ace_3.13.3.52) automatically downloaded (06/30/2020). But all players/clients still have the version ace_3.13.2.49 but everyone has downloaded the newest version of ACE in the workshop.
Every player deleted and reinstalled ACE and CBA through the workshop but the players/clients still get kicked from the server because of the mismatch error. (Screenshot)
![unknown](https://user-images.githubusercontent.com/52171680/86296533-49585d00-bbf9-11ea-9f4f-b94741362cde.png)

**Comment by PabstMirror** [comment]
- Make sure they are subscribed to **our** version - https://steamcommunity.com/sharedfiles/filedetails/?id=463939057
- From arma launcher, hit the 3 dots on the mod and try repair
- You can double check the version by going to `Arma 3\!Workshop\@ace\addons`
and check the names of the bisigns, e.g. it should be `ace_advanced_ballistics.pbo.ace_3.13.3.52-231d52a7.bisign`

**Comment by itsmarsl** [comment]
One of the player tested it. The version name of the bisign in the @ace folder is the same you wrote. But still this error doesn't disappear. The players still get kicked after pressing the "OK" button you can see in the screenshot.
We already tried the repair feature and we're all subscribed to the real @ace mod you sent.

**Comment by commy2** [comment]
The server and client RPT's say why. Without them, no one can know.

**Comment by itsmarsl** [comment]
The problem is solved now because there was an update for CSF compatibility and now all players can join without mistakes. But I'm still grateful for your help!
