### ISSUE TITLE
ACE Medical script error

### ISSUE THREAD

**Issue by Warhawk20** [acemod/ACE3#7794]
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
I created a SP mission in ARMA 3 with ACE Mod. Have an AI Combat Medic. When healing, been getting this error:

**Steps to reproduce:**
- _Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_
- Go to ...
- Click ...
- See ...

**Expected behavior:**

**Where did the issue occur?**
- SinglePlayer

[ARMA 3 Error ACE.txt](https://github.com/acemod/ACE3/files/4867015/ARMA.3.Error.ACE.txt)

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**

**Comment by PabstMirror** [comment]
Is there anything in the mission that changes or sets ace medical values?

I could reproduce with `player setVariable ["ace_medical_fractures", []]` but that shouldn't ever happen in ace as it should always use a good default value before setting.

**Comment by Warhawk20** [comment]
Nope...the AI Combat Medic settings are default.

**Comment by BaerMitUmlaut** [comment]
Please fill out the template.

**Comment by severgun** [comment]
@PabstMirror 
Is this variable overlap?
https://github.com/acemod/ACE3/blob/d7f12eb49adce1414e6733e0d857578c25d33956/addons/medical/initSettings.sqf#L13
https://github.com/acemod/ACE3/blob/a84af7ba9a41a9eb2646be4dd70465f679322932/addons/medical_engine/functions/fnc_updateDamageEffects.sqf#L25
https://github.com/acemod/ACE3/blob/eb8856e7c5a78a1282e4684a8d1af869098d9083/addons/medical_engine/script_macros_medical.hpp#L161

**Comment by Warhawk20** [comment]
I just had it happen again but I saw why: I shot an OPFOR unit and my AI squad member attempted to heal the OPFOR unit. Then the error popped up.

**Comment by BaerMitUmlaut** [comment]
I'm closing this until you fill out the template.
