### ISSUE TITLE
document carry/drag config values for mod makers

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#780]
See https://github.com/acemod/ACE3/blob/master/addons/dragging/CfgVehicles.hpp

        GVAR(canCarry) = 1;
        GVAR(carryPosition[]) = {0,1.2,0};
        GVAR(carryDirection) = 0;

        GVAR(canDrag) = 1;
        GVAR(dragPosition[]) = {0,1.2,0};
        GVAR(dragDirection) = 0;

Needs documenting in the wiki.

**Comment by commy2** [comment]
ace_dragging_canDrag := this object can be dragged; 1 yes, 0 no (0 default)
ace_dragging_dragPosition[] := Offset of the model from the body while dragging, comparable to the offset in attachTo (It's the same actually)
ace_dragging_dragDirection := how much degrees is the model rotatated after dragging it (a global setDir after attachTo)

ace_dragging_canCarry := this object can be carried; 1 yes, 0 no (0 default)
ace_dragging_carryPosition[] := Same as drag, but for carrying objects
ace_dragging_carryDirection := Same as drag, but for carrying objects

**Comment by jaynus** [comment]
Copied to wiki http://ace3mod.com/wiki/framework/carry-drag.html

**Comment by commy2** [comment]
Thank you!
