### ISSUE TITLE
cant join a friend or even do a single player game with ace.

### ISSUE THREAD

**Issue by jdego866** [acemod/ACE3#7802]
![arma ace1](https://user-images.githubusercontent.com/67983731/86851526-bc8a2500-c078-11ea-81b0-61b817ab681f.png)
![arma ace2](https://user-images.githubusercontent.com/67983731/86851542-c449c980-c078-11ea-96d5-b17bad0aa03a.png)
![20200707171914_1](https://user-images.githubusercontent.com/67983731/86851742-15f25400-c079-11ea-882f-8f6f4fef4fbc.jpg)
![20200707172303_1](https://user-images.githubusercontent.com/67983731/86851752-1a1e7180-c079-11ea-85c1-6b4fd1e8a59b.jpg)
![20200707172741_1](https://user-images.githubusercontent.com/67983731/86851759-1d196200-c079-11ea-86a7-cc3f4bf24fb6.jpg)

**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
i have downloaded this mod from steam and that didn't work then i deleted the mod completely out of every spot including unsubing. even had my friend copy all his ace3 files and compress them and send them to me to see if i had a missing file but that still didn't work. then i downloaded the mod from ace3 site off github and that still gave me the same issue. the errors that i get are either the "ace_medical_menu","ace_ifa3mortar"  error when trying to join my friend and we have both went through the files and we match up completely. when i try to so a single player game i get the "ace_medical_menu.pbo" is outdated even though the file is not in the ace files at all, i know that the menu was taken out in a previous update. i have even tried to just play on Zeus and it stops me and gives me the outdated pbo when i take over an ai. Any help at all would be much appreciated. Thanks

**Steps to reproduce:**
none

**Expected behavior:**
i would like it to let me play but errors stop everything.

**Where did the issue occur?**
Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) all of these

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**
i have posted the screenshots from the server with my friend and the shots from my single player games. 

**Screenshots:**

**Comment by PabstMirror** [comment]
somehow ace_medical_menu.pbo is being loaded
RPT will be helpful, see [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3) for more info on where to find it
(goto `%localappdata%/Arma 3/` and look for the most recent *.rpt file)

**Comment by jdego866** [comment]
[Arma3_x64_2020-07-06_14-20-24.txt](https://github.com/acemod/ACE3/files/4887864/Arma3_x64_2020-07-06_14-20-24.txt)
There is the report for today when we ran into the error, hope this helps.

**Comment by PabstMirror** [comment]
`addons\ace_medical_menu.pbo`
not sure how it got in that folder but goto 
`C:\Program Files (x86)\Steam\steamapps\common\Arma 3\addons` and delete `ace_medical_menu.pbo`

`ace_ifa3mortar` is from @IFA3 liberation ACE on the workshop

**Comment by jdego866** [comment]
alright thanks much we got it fixed.
