### ISSUE TITLE
ace_medical_menu pbo outdated

### ISSUE THREAD

**Issue by Thecatgod77** [acemod/ACE3#7803]
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
I can not play arma with the ace mod enabled outside of the editor. 

**Where did the issue occur?**
 Self-Hosted Multiplayer 

**Additional context:**
I have read the previous post made about the issue but the outdated pbo is not in the same location and i can't find it at all. Previous post I read through: https://github.com/acemod/ACE3/issues/7802

**Comment by PabstMirror** [comment]
lets see the rpt

**Comment by Thecatgod77** [comment]
I'm sorry I'm still new to this. what is an rpt

**Comment by PabstMirror** [comment]
RPT will be helpful, see [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3) for more info on where to find it
(goto `%localappdata%/Arma 3/` and look for the most recent *.rpt file)

**Comment by Thecatgod77** [comment]
I have been looking and there isn't an rpt i can give you.

**Comment by BaerMitUmlaut** [comment]
Then you're staring your game with the -noLogs parameter. You shoudn't use that parameter.

**Comment by Thecatgod77** [comment]
So the no logs parameter was never used but it still won't produce an rpt

**Comment by commy2** [comment]
That's not true. You're looking at the wrong place. Find the RPT and fixing the issue is trivial. Without the RPT, this issue will have to be closed unresolved.

**Comment by PabstMirror** [comment]
try doing a search for ace_medical_menu.pbo on your computer

**Comment by rome080817** [comment]
im having this issue as well my i get some help

**Comment by rome080817** [comment]
i deleted the file then repaired the mod for a fresh file and still a no go i dont know what to do anymore

**Comment by BaerMitUmlaut** [comment]
We can't help you without an RPT. Please create a new issue, fill out the template and upload your RPT file.
