### ISSUE TITLE
ace_medical.pbo outdated.

### ISSUE THREAD

**Issue by Vyesnaa** [acemod/ACE3#7813]
Hello, I came here recently and downloaded the most recent version of ACE cause I was having issues with the version that was on the steam workshop. I downloaded and got it loaded but im still getting the "ace_medical.pbo is outdated" issue and it wont let me lauch anything unless i launch without any ACE mods. I have the .rpt file and I'm unsure of where to go from here as I am pretty new to all of this. Any assistance would be highly appreciated. (I went ahead and converted it all into a .txt file cause it wouldnt allow me to upload the actual RPT file).
[rpt_file_07-18-2020.txt](https://github.com/acemod/ACE3/files/4943019/rpt_file_07-18-2020.txt)

**Comment by Whigital** [comment]
The problem is that you're loading the obsolete `ace_medical_menu.pbo` through `@CSF - ACE RHS COMPATIBILITY`

<details><summary>Loading at line 1811</summary>

```
18:55:43 D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@CSF - ACE RHS COMPATIBILITY\addons\ace_medical_menu.pbo - 7d9a4f47
```

</details>

<details><summary>Error at line 8346</summary>

```
18:57:41 [ACE] (common) ERROR: File ace_medical_menu.pbo is outdated.
```

</details>

Remove that mod and try again ....

**Comment by Vyesnaa** [comment]
That seems to have fixed my issue, thank you!
