### ISSUE TITLE
ACE3 slideshow bug

### ISSUE THREAD

**Issue by TheGentlemanGamer** [acemod/ACE3#7814]
**Mods (complete and add to the following information):**
- **Arma 3:** `Up to date as of 7/21/2020` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.1` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.3` [eg. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**

**Steps to reproduce:**
- _Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_
- Go to ... Eden, place down the things to make a slideshow, set up everything properly. Host a server and invite someone to it with your screen, remote and pictures set up
- See ... One person will see the image shown, only when they select it, the other person will either see blank or invisible screen.

**Expected behavior:**
Expected everyone to see the same image on the screen.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file.
 An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
N/A
**Additional context:**

**Screenshots:**
![bad screen](https://user-images.githubusercontent.com/64657657/88095941-2283ab80-cb53-11ea-9058-a2645bd5633a.png)
![Ok screen](https://user-images.githubusercontent.com/64657657/88095949-23b4d880-cb53-11ea-83e0-b6341dc83686.png)

**Comment by BaerMitUmlaut** [comment]
Please upload your mission. I cannot reproduce your problem.

**Comment by TheGentlemanGamer** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2173466415 That is the link

**Comment by BaerMitUmlaut** [comment]
https://feedback.bistudio.com/T80668
Linked in the big fat red warning box.
