### ISSUE TITLE
ace_medical_bodyPartStatus no work

### ISSUE THREAD

**Issue by grenadier2510** [acemod/ACE3#7817]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98.146373` 
- **CBA:** `3.15.1.200418`
- **ACE3:** `3.13.3.52`

**Description:**
ace_medical_bodyPartStatus seems to no longer work. how to solve?

**Expected behavior:**
_damageVar 	= player getvariable ["ace_medical_bodyPartStatus", true];
this is what I used to do.

**Where did the issue occur?**
does not release any value

**Comment by Whigital** [comment]
Not sure what that var used to hold, but there is a new var that holds the damage for each bodypart: `ace_medical_bodyPartDamage`.

https://github.com/acemod/ACE3/blob/a9a69ac4ff5c04a0ab7a4c1a4be26a3d8adccd3f/addons/medical_gui/functions/fnc_updateBodyImage.sqf#L24

https://github.com/acemod/ACE3/blob/a9a69ac4ff5c04a0ab7a4c1a4be26a3d8adccd3f/addons/medical_gui/functions/fnc_updateBodyImage.sqf#L75-L82

| Index  | Bodypart |
| ------------- | ------------- |
| 0 | Head |
| 1 | Torso |
| 2 | ArmLeft |
| 3 | ArmRight |
| 4 | LegLeft |
| 5 | LegRight |

**Comment by grenadier2510** [comment]
it works, thank you very much!
