### ISSUE TITLE
ACE_isUnconscious no work

### ISSUE THREAD

**Issue by grenadier2510** [acemod/ACE3#7818]
Mods (complete and add to the following information):

Arma 3: 1.98.146373
CBA: 3.15.1.200418
ACE3: 3.13.3.52
Description:
ACE_isUnconscious seems to no longer work. how to solve?

Expected behavior:
_test=player getVariable ["ACE_isUnconscious", false]; 

Where did the issue occur?
does not release any value

**Comment by Vdauphin** [comment]
Hello,

Use `_test = [player] call ace_common_fnc_isAwake;`

Cheers

**Comment by grenadier2510** [comment]
fantastic! 

thank you
