### ISSUE TITLE
View distance limiter should not require reload

### ISSUE THREAD

**Issue by Avokadomos** [acemod/ACE3#7821]
The view distance limiter has an option to use "Video Settings" for infantry, vehicle and aircraft view distances. However, this setting only updates once the mission is reloaded.

The option doesn't make much sense if it doesn't match the view distance in my video settings. Therefore, it would be a big improvement if the view distance limiter matched the video settings immediately after a change is made.

**Comment by Sheppard85oc** [comment]
why you not used the TAW View Distance Script? in my opinion this does a good job for what you are request for @Avokadomos

**Comment by Avokadomos** [comment]
Because that's a workaround rather than a solution to the problem. If dynamic view distance didn't exist in ACE, I would. That's like saying "why don't you just use a bluetooth speaker" when your car's stereo is broken. 🤷

**Comment by Sheppard85oc** [comment]
Ahhh now i got what you mean, so far was my thinking about it not really. But you Right! 👍
