### ISSUE TITLE
View distance keybinds

### ISSUE THREAD

**Issue by Avokadomos** [acemod/ACE3#7822]
The view distance limiter is great in that you can set up different view distances for different modes of gameplay, but sometimes you require quick changes due to FPS or other reasons.

Navigating to the view distance settings in addon options is quite an adventure. I would much prefer if there was keybind options for increasing and decreasing the view distance for the current mode (inf/veh/air), by 500 m intervals or so.

**Comment by BaerMitUmlaut** [comment]
#3594
