### ISSUE TITLE
[Ballistics] RFB SDAR zero'd above 100m shoots ground

### ISSUE THREAD

**Issue by Coryf88** [acemod/ACE3#7832]
**Mods:**
- **Arma 3:** `1.98.146373` [stable]
- **CBA:** `3.15.1` [stable]
- **ACE3:** `3.13.3` [stable]

**Description:**
Changing the RFB SDAR zero to above 100m causes the bullet to be fired as if the zero was lowered. At 400m, the bullet shoots almost straight down.

**Steps to reproduce:**
- Play as an Assault Diver unit
- Execute `[player] spawn BIS_fnc_traceBullets;`
- Shoot at different zeros
- Notice > 100m zero trajectories.

**Expected behavior:**
Zeros above 100m to range further.

**Where did the issue occur?**
Dedicated / Editor (Singleplayer)

**Log Files:**
N/A

**Additional context:**
None

**Screenshots:**
Left to right: 30m, 100m, 200m, 300m, 400m (Chemlight marks where 400m hit)
![20200801124341_1](https://user-images.githubusercontent.com/204475/89107165-b4fa3980-d3f4-11ea-8fc9-b5dff363e2bb.jpg)

**Comment by BaerMitUmlaut** [comment]
I investigated this and the problem are the underwater bullets/darts (B_556x45_dual). The weapon works fine with normal 5.56 magazines. All our ballistics for this ammo type are inherited from normal 5.56 even though it has ~15 times more air friction, which probably causes the issue.
