### ISSUE TITLE
All Optional Modules on Steam Workshop

### ISSUE THREAD

**Issue by Dystroxic** [acemod/ACE3#7834]
**Is your enhancement related to a problem?**
I think this is a pretty common one. Our community wants to use several of the optional modules for our events. We use Steam Workshop with HTML templates for importing the mod configuration. Since enabling optional modules requires manually moving those folders from the `optionals` directory to the main install directory, this makes it much harder to use Steam (has to be re-done by each player with each new release).

**Solution you'd like:**
Similarly to how you have the various compat optionals (e.g. RHS compat) as separate releases on Steam Workshop, I would like the other optional modules (noactionmenu, nocrosshair, particles, etc.) to also be separate releases that can be specified in an HTML template.

**Alternatives you've considered:**
Re-packaging ACE3 with optional PBOs copied into the main `addons` directory, but we can't publish that on Steam Workshop without violating the TOS.

**Additional context:**
The need for this is already known, since it's already done with the RHS compat optionals, so I'd be surprised to see opposition to this.

**Comment by jonpas** [comment]
> Re-packaging ACE3 with optional PBOs copied into the main addons directory, but we can't publish that on Steam Workshop without violating the TOS.

I am no lawyer, but from our side, you xan re-upload as much as you want to as long as you make it clear it's not official. :) Many units do that. 

Managing multiple optionals gets tedious, that's why we only keep it to the most popular ones.

**Comment by Dystroxic** [comment]
@jonpas Is your deployment system (pushing to Steam Workshop) entirely manual then? I see that you're already using GitHub Workflows/Actions for the build/release; it wouldn't be too difficult to add an automatic publish to Steam Workshop to that workflow (automatically publishing each optional module as well). I'd be happy to help with that if you like.

**Comment by jonpas** [comment]
No, `tools/publish.py` is used. It is partly automated, but needs to be created first to get the IDs.

Automatic publish from GitHub directly doesn't help until you have a full binarized build on that system.

**Comment by Dystroxic** [comment]
Got it. So after creating the initial publish manually and the IDs to the build/deploy config, is it any extra work to maintain? I would sure be a massive help to a lot of us who rely on workshop templates.

**Comment by PabstMirror** [comment]
For today's (3.13.4) release:

#compat_r3f: r3 - https://steamcommunity.com/sharedfiles/filedetails/?id=2202404402
#compat_rh_acc: - https://steamcommunity.com/sharedfiles/filedetails/?id=2202407118
#compat_rh_de: - https://steamcommunity.com/sharedfiles/filedetails/?id=2202407963
#compat_rh_m4: - https://steamcommunity.com/sharedfiles/filedetails/?id=2202408647
#compat_rh_pdw: - https://steamcommunity.com/sharedfiles/filedetails/?id=2202409303
#ace_compat_rhs_afrf3: RHS Russians - http://steamcommunity.com/sharedfiles/filedetails/?id=773131200
#ace_compat_rhs_gref3: RHS GREF - http://steamcommunity.com/sharedfiles/filedetails/?id=884966711
#ace_compat_rhs_saf3: RHS SAF - http://steamcommunity.com/sharedfiles/filedetails/?id=2174495332
#ace_compat_rhs_usf3: RHS USA - http://steamcommunity.com/sharedfiles/filedetails/?id=773125288
#compat_rksl_pm_ii: - https://steamcommunity.com/sharedfiles/filedetails/?id=2202410630
#compat_sma3_iansky: - https://steamcommunity.com/sharedfiles/filedetails/?id=2202411104
#noactionmenu: - https://steamcommunity.com/sharedfiles/filedetails/?id=2202412030
#nocrosshair: - https://steamcommunity.com/sharedfiles/filedetails/?id=2202412481
#nouniformrestrictions: - https://steamcommunity.com/sharedfiles/filedetails/?id=2202413047
#particles: - https://steamcommunity.com/sharedfiles/filedetails/?id=2202413537
#realisticdispersion: - https://steamcommunity.com/sharedfiles/filedetails/?id=2202414018
#tracers: - https://steamcommunity.com/sharedfiles/filedetails/?id=2202414450
