### ISSUE TITLE
Medical Inaccuracies

### ISSUE THREAD

**Issue by Tiberius99** [acemod/ACE3#7840]
Hello,

I'm a US paramedic and can't help but notice a large amount of inaccurate medical info and mechanics in ace3. Too much for me to list here.
I'd love to offer solutions but I have no coding experience. If you are interested you can contact me at taydanj@gmail.com any time. I'd be happy to talk with the development team over discord as well

**Comment by BaerMitUmlaut** [comment]
We don'z contact people over e-mail. We have a public Slack channel: https://slackin.ace3mod.com/
