### ISSUE TITLE
ace_common_fnc_claim break CSW vanilla disassembly block

### ISSUE THREAD

**Issue by severgun** [acemod/ACE3#7842]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98` [stable]
- **CBA:** `3.15.1` [stable]
- **ACE3:** `3.13.3` [stable]

**Description:**
If vanilla disassembly turned off by CSW setting it can be turned back on by dragging pre-assembled weapon.

**Steps to reproduce:**
- Disable vanilla disassembly in CSW settings
- Place already assembled CSW static weapon
- Drag and drop it
- Action menu available now

**Expected behavior:**
Action menu should not be available

**Additional context:**
With a quick look at sources this behavior seems like happen because `ace_common_fnc_claim` do  
`_target enableWeaponDisassembly true;`
`ace_csw_assemblyMode`  is nil till you reassemble it. Here https://github.com/acemod/ACE3/blob/ebb1ef628f62b289371c31fda2b82b5af7fbdefe/addons/common/functions/fnc_claim.sqf#L33
So condition is true and `claim` reset `enableWeaponDisassembly`.

**Comment by commy2** [comment]
There is no getter for `enableWeaponDisassembly`, but it has to be disabled on drag.

**Comment by severgun** [comment]
I think something similar should be done on static weapon init. And not only after advanced assembly
https://github.com/acemod/ACE3/blob/ebb1ef628f62b289371c31fda2b82b5af7fbdefe/addons/csw/functions/fnc_assemble_deployWeapon.sqf#L46-L51
Or condition should be changed

**Comment by severgun** [comment]
By design variable should be set by this macro. But it is not used https://github.com/acemod/ACE3/blob/ebb1ef628f62b289371c31fda2b82b5af7fbdefe/addons/csw/script_config_macros_csw.hpp
