### ISSUE TITLE
More documentation on ACE scopes variables

### ISSUE THREAD

**Issue by simkas** [acemod/ACE3#7846]
Currently, ACE scopes appears to add three extra variables to all weapons - ACE_RailHeightAboveBore, ACE_RailBaseAngle, ACE_IronSightBaseAngle. There doesn't appear to be any documentation on what these variable mean and how they should be set, which causes issues with misaligned sights on custom weapons when those variables are not set correctly. This appears to mostly appear when "simplified zeroing" is turned on. I would like some more info on how these variable were calculated for the weapons that ACE handles (vanilla or RHS for example) and how I could calculate them myself so I could set them correctly.

**Comment by dedmen** [comment]
ACE_RailHeightAboveBore
height difference between bore center (where the bullet comes out of) and the rail attachment memory point.
