### ISSUE TITLE
Global ACE Arsenal White/Blacklisting

### ISSUE THREAD

**Issue by Dystroxic** [acemod/ACE3#7847]
**Is your enhancement related to a problem?**
There are some vanilla assets that I never want any of the players to have access to. I don't want to have to explicitly blacklist them on every item that has ACE Arsenal.

**Solution you'd like:**
A way to configure (preferrably in CBA Settings; if not there, then by script in the mission file) a global whitelist and blacklist for all ACE arsenals.

**Alternatives you've considered:**
I've considered adding a script in a server-side mod that finds all items on the map that have ACE arsenal enabled and then running the `ace_arsenal_fnc_removeVirtualItems` function on each one, but (1) I don't think there's any way to find all objects with ACE arsenal, and (2) that doesn't handle ACE arsenal being added to objects during the game by Zeus.

I've also considered using an event handler (possibly `ace_arsenal_displayOpened`) to remove the blacklisted items whenever someone opens the arsenal (which would solve the issue with Arsenals added by Zeus), but that requires adding the handler to each object with Arsenal, and there's no event handler for detecting when an arsenal is created.

**Additional context:**
I'm open to all idea of how to do this, including server and/or client mods, mission scripts, etc. Any ideas would be appreciated. Even if there is another workaround though, this would still be a great core ACE enhancement.

**Comment by Dystroxic** [comment]
Update: I've found a workaround solution to this. Add the following event handler to every player, locally (I'm doing it in `initPlayerLocal.sqf`):

```
ace_arsenal_blacklist_handler = ["ace_arsenal_displayOpened", {
	// An array of items to blacklist from all ACE arsenals in the mission
	_items = ["rhs_weap_ak103"];

	{
		if (_forEachIndex isEqualTo 0) then {
			ace_arsenal_virtualItems set [_forEachIndex, [(_x select 0) - _items, (_x select 1) - _items, (_x select 2) - _items]];
		} else {
			if (_forEachIndex isEqualTo 1) then {
				ace_arsenal_virtualItems set [_forEachIndex, [(_x select 0) - _items, (_x select 1) - _items, (_x select 2) - _items, (_x select 3) - _items]];
			} else {
				ace_arsenal_virtualItems set [ace_arsenal_virtualItems find _x, _x - _items];
			};
		};
	} foreach ace_arsenal_virtualItems;
}] call CBA_fnc_addEventHandler;
```

This modifies the `virtualItems` global variable in `fnc_onArsenalOpen.sqf` prior to the lists of items being generated in the display. Since it does this filtering dynamically, it will work for any Arsenal that is created after mission start by Zeus as well.

I'll be putting the `_items` value in a CBA setting in a custom addon, so the global blacklist will apply to all missions we run for our group events, regardless of the mission itself.

**Comment by BaerMitUmlaut** [comment]
You could just write your own wrapper function for initBox which handles the white and blacklisting itself. That would be the easiest option in my opinion.

**Comment by Dystroxic** [comment]
@BaerMitUmlaut That would work too, but doesn't handle the case of the `ace_arsenal_fnc_openBox` function being called directly (e.g. by a user action); numerous popular missions, such as KP Liberation, use this approach to make an area arsenal-enabled instead of making an object arsenal-enabled.

**Comment by BaerMitUmlaut** [comment]
#3594

**Comment by BadDad1776** [comment]
> Update: I've found a workaround solution to this. Add the following event handler to every player, locally (I'm doing it in `initPlayerLocal.sqf`):
> 
> ```
> ace_arsenal_blacklist_handler = ["ace_arsenal_displayOpened", {
> 	// An array of items to blacklist from all ACE arsenals in the mission
> 	_items = ["rhs_weap_ak103"];
> 
> 	{
> 		if (_forEachIndex isEqualTo 0) then {
> 			ace_arsenal_virtualItems set [_forEachIndex, [(_x select 0) - _items, (_x select 1) - _items, (_x select 2) - _items]];
> 		} else {
> 			if (_forEachIndex isEqualTo 1) then {
> 				ace_arsenal_virtualItems set [_forEachIndex, [(_x select 0) - _items, (_x select 1) - _items, (_x select 2) - _items, (_x select 3) - _items]];
> 			} else {
> 				ace_arsenal_virtualItems set [ace_arsenal_virtualItems find _x, _x - _items];
> 			};
> 		};
> 	} foreach ace_arsenal_virtualItems;
> }] call CBA_fnc_addEventHandler;
> ```
> 
> This modifies the `virtualItems` global variable in `fnc_onArsenalOpen.sqf` prior to the lists of items being generated in the display. The inner code is copied from `fnc_removeVirtualItems.sqf`. Since it does this filtering dynamically, it will work for any Arsenal that is created after mission start by Zeus as well.
> 
> I'll be putting the `_items` value in a CBA setting in a custom addon, so the global blacklist will apply to all missions we run for our group events, regardless of the mission itself.

I was using this method for a long time... a few updates ago it stopped working and freezes the person that openend the arsenal ... basically they get stuck in the arsenal and cvany exit it... did you ever update this script?

**Comment by BaerMitUmlaut** [comment]
This issue was closed 3 years ago. Please make a new one or join our Discord.
