### ISSUE TITLE
Feature request: Make ace_medical_fnc_setUnconscious do not cause AI unit instant death even AI unconscious is disallowed in settings.

### ISSUE THREAD

**Issue by GoldJohnKing** [acemod/ACE3#7848]
**Is your enhancement related to a problem?**
Since some missions makers would use `ace_medical_fnc_setUnconscious` as a way to spawn some "wating to be rescued" AIs, I think it's an enhancement to make directly call of `ace_medical_fnc_setUnconscious` on a AI unit not cause AI unit instant death, even AI unconscious is disallowed in settings.

**Solution you'd like:**
Even if AI Unconscious is off in ACE Medical Settings, when there's a direct call of `ace_medical_fnc_setUnconscious` on a AI unit, don't make the AI dies.

**Alternatives you've considered:**
Add another optional parameter on this function to force the unit alive should be good.

**Additional context:**
No at this time.

**Comment by Quailsnap** [comment]
I do believe this would require a low-level change. Perhaps just make the AI surrender, or become captive, or force them into a 'sleeping' animation to be removed when players arrive?

**Comment by GoldJohnKing** [comment]
I'm now using the captive as a work around, would you please explain what is 'sleeping' animation and how can I execute it on a unit to prevent it moving around?
