### ISSUE TITLE
Addon icons missing from right-side column for uniform/vest/backpack

### ISSUE THREAD

**Issue by Dystroxic** [acemod/ACE3#7853]
**Mods:**
- **Arma 3:** `1.98.146373`
- **CBA:** `3.15.1`
- **ACE3:** `3.13.3`

**Description:**
In ACE arsenal, the icon of the addon that an item in the right column (weapon attachment, magazine, etc.) is from (e.g. RHS USAF, Contact DLC) appears properly when in the Primary Weapon or Secondary Weapon selection tab. When in the uniform/vest/backpack selection tab, the associated mod symbol is not shown.

**Steps to reproduce:**
- Start a new mission with nothing but an ACE Arsenal
- Open the ACE Arsenal
- Click the "Rifles" tab in the top left
- Note that the attachments in the right column show their addon icon ([screenshot](https://i.imgur.com/iWuBjxB.png) - see green highlight)
- Click the "Uniforms" tab on the left
- Click the "Sights" tab in the top right
- Note that the attachments in the right column _do not_ show their addon icon ([screenshot](https://i.imgur.com/R7QxSkg.png) - see green highlight)

**Expected behavior:**
The addon icons for each item should always be present in the right column.

**Where did the issue occur?**
- All server types (SP, MP local, MP dedicated) in ACE Arsenal.

**Log Files:**
[RPT](https://gist.github.com/Dystroxic/11a8f02f42e083e1fea12853521c15e8)

**Comment by johnb432** [comment]
They aren't shown, because
1. there is the `+` button on the left
2. there is no real need. If you want to see from what mod an item comes from, you can select the item in question and look in the bottom right.
