### ISSUE TITLE
Add "Sort by Mod" to right-side column

### ISSUE THREAD

**Issue by Dystroxic** [acemod/ACE3#7854]
**Is your enhancement related to a problem?**
No.

**Solution you'd like:**
The left-side column has a "sort by mod" option in the sort drop-down. It would be great to have this same option in the right-side column (attachments/magazines/items).

**Alternatives you've considered:**
N/A

**Additional context:**
This enhancement request is tangentally related to issue #7853 .

**Comment by synixebrett** [comment]
Could easily be done with #7719

**Comment by synixebrett** [comment]
Closed by #7719
