### ISSUE TITLE
Can't use medical items in ACE 3 interaction menu

### ISSUE THREAD

**Issue by MrLee762x51** [acemod/ACE3#7855]
**Mods**
- **Arma 3:** '1.98' [stable]
- **CBA:** '3.15' [stable]
- **ACE3:** `3.13` [stable]

**Description:**
When I use the interaction menu wether that on myself or an NPC, it does not allow me to use any of the medical items I have in my inventory when I hover over a limb. Usually, I hover over say my leg, it would then present me with items such as bandages, tourniquets, and syringes. Now when I hover over a limb nothing appears at all despite having all of these items in my inventory. I have tried uninstalling ACE and CBA and reinstalling and the problem persisted. There doesn't seem to be any information about this issue online so perhaps it is something I did wrong in the settings but I can't seem to find anything. Any help would be much appreciated. 

**Steps to reproduce:**
- Go to Eden Editor
- Use keybind to access self interaction menu (Ctrl + Tab) for me
- Move cursor to the medical menu 
-Move cursor over any extremity (legs, arms, torso, head)
-Notice that no options to use any healing items will appear. 

**Expected behavior:**
When attempting to heal a part of body with medical items in inventory, there will be no option to do so when moving cursor over a limb.

**Where did the issue occur?**
- Singleplayer Editor 

**Additional context:**
I'm not a developer by any means and haven't touched the source code of the game in any way

**Screenshots:**
I tried to screenshot the exact problem but it will not allow me to screenshot while holding the self-interaction keys

**Comment by MrLee762x51** [comment]
I just noticed that there are a few file blocks happening in the BattleEye Log messages

**Comment by BaerMitUmlaut** [comment]
Missing RPT.

**Comment by MrLee762x51** [comment]
> Missing RPT.

<script src="https://gist.github.com/MrLee762x51/21b9cd10b2584ece0779f21014ee7541.js"></script>

**Comment by MrLee762x51** [comment]
> Missing RPT.

https://gist.github.com/MrLee762x51/21b9cd10b2584ece0779f21014ee7541

**Comment by commy2** [comment]
Maybe add some screenshots. This appears to be user error tbh.

**Comment by MrLee762x51** [comment]
> Maybe add some screenshots. This appears to be user error tbh.

I wasn't able to screenshot because in order to replicate the issue I have to hold down ctrl+q and I can't screenshot while doing it. Its not user error either I havent done anything to the settings and ive done it the same way every time. It could be user error but i'd at least like some help.

**Comment by MrLee762x51** [comment]
nvm it was user error im so stupid. Thanks anyway
