### ISSUE TITLE
Pain inducing Bullets

### ISSUE THREAD

**Issue by Tarus5** [acemod/ACE3#7856]
So i am trying to script/implement a mod, when specific Ammo damages a unit it will induce pain.
Now i do not have any real experience with arma scripting or any proper knowledge how ace pain system works. I tried looking up the files and try to find something usable. So my ideas for now have been: either put a class Eventhandler into the class ammo and try to say the ammotype to induce pain with maybe the "painReduce = -0.1". Although i doubt that the value can be negative or can even be used on ammo damage effect. Another option i thought of is with the Eventhandler: when a unit gets hit by Ammo x it will raise its Pain level:
this addEventHandler ["HitPart", {
    params ["_ammo"];
"add ace pain effect to this" ;
}];
Sadly i don't know really how to properly do any of this, so i thought maybe someone here can help me out.

**Comment by Whigital** [comment]
Quick and dirty, without any guarantees to work, but should point you in the right direction ....

```sqf
["ace_medical_woundReceived", {
    params ["_unit", "_woundedHitPoint", "_receivedDamage", "_shooter", "_ammo"];
    
    if (_ammo isEqualTo "<your_ammo_class>") then {
        private _painToInflict = (getNumber (configFile >> "CfgAmmo" >> _ammo >> "<your_pain_config_attribute>"));
        
        if (_painToInflict > 0) exitWith {
            ["ace_medical_injured", [_unit, _painToInflict]] call CBA_fnc_localEvent;
        };
    };
}] call CBA_fnc_addEventHandler;
```
