### ISSUE TITLE
Ace3 + Antistasi: Vehicles won't move

### ISSUE THREAD

**Issue by dodgycoffee** [acemod/ACE3#7857]
**Mods (complete and add to the following information):**
_**All @latest (verified and checked)**_
Antistasi - Altis - Community Version
CBA_A3
Enhanced Movement
Quick Loot to Vehicle
Radio Animations for Task Force Radio
ShackTac User Interface
ace3
task_force_radio

**Description:**
Vehicles don't move. They slowly move forward, show speed of 0km/h, and then drift lazily to a direction when exiting indefinitely. New vehicles, stored ones, ones picked up on the road. Doesn't matter.

**Steps to reproduce:**
- Have working server with above mods (no issues)
- Install/activate ace3
- Broken vehicles

**Expected behavior:**
Ace runs and vehicles actually move.

**Where did the issue occur?**
- Dedicated Server (debian 9)

**Log Files:**
https://pastebin.com/jryywyW8

**Additional context:**
I messed around with mod combos to rule out everything else. Stripped out everything except antistasi and it is definitely something between that and ace. I made sure that both mods were completely up to date, and using the version of antistasi that is compatible with ace3. The few threads I found online basically had no real fix.

Remove ace3 from list, everything is fine. All other mods work as intended as well. I even tried stripping out the vehicle add-ons of ace3 and see if that affected it, no such luck.

I'm newish to arma3 servers, but not new to servers in general. I've ruled out everything else I could before submitting the report. If it's something I'm missing, then I'm happy for a fix. If it's a legitimate bug then great as I haven't seen anything reported so far. If this is something on the antistasi end then I can submit something to them as well. But since it occurs exclusively after activating this mod, it seemed like a good spot to start.

**Comment by Blutze** [comment]
The segment from line 131 to line 589 is supposed to include .pbo files from mods as well. The segment from 601 to 620 also loudly proclaims those files to be `NOT FOUND`, including the Antistasi stuff.

Either that is not the .rpt you wanted to show, or you should sit down and fix that problem.

**Comment by dodgycoffee** [comment]
@Blutze Good shout. Taking a look now at why it's partially loading and that stuff is missing. Will report back.
