### ISSUE TITLE
Can you separate movement and stamina into 2 different pbos?

### ISSUE THREAD

**Issue by Tachii** [acemod/ACE3#786]
So this could be a separate pbo, instead of being a part of ace_movement?
https://github.com/acemod/ACE3/blob/master/addons/movement/CfgFatigue.hpp

**Comment by Jastreb** [comment]
What are you trying to achieve by separating those? This should be in #414

**Comment by Tachii** [comment]
It's not a feature request, it's modularity. I want to use vanilla stamina but without loosing all other functionality

**Comment by esteldunedain** [comment]
#414
