### ISSUE TITLE
Fuel nozzle get stuck in destroyed vehicle rendering vehicle immobile

### ISSUE THREAD

**Issue by igorpc1** [acemod/ACE3#7861]
Mods
- **Arma 3**: `1.98.146373`
- **CBA:** `3.15.1`
- **ACE3:** `3.13.3`

**Description:**
If you start to refuel some vehicle with another vehicle (ex. HEMTT Refuel), when the first vehicle gets destroyed HEMTT cannot move because nozzle is still there destroyed that you cannot pick up.

**Steps to reproduce:**
- Place HEMTT Refuel and another vehicle in editor
- Start refueling vehicle
- Destroy vehicle that have been refueling
- Try to move with HEMTT Refuel

**Expected behavior:**
Some way to move even after nozzle got destroyed or retrack nozzle somehow.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by Whigital** [comment]
Going through the code and contemplating adding a `handleKilled` function, stumbled across this statement:

https://github.com/acemod/ACE3/blob/e9b2087faf30724cb50335a489a5d364a7c0cb45/addons/refuel/functions/fnc_refuel.sqf#L42

Remove the lazyeval to catch if _either_ of the involed vehicles/objects gets destroyed and problem solved ?

**Comment by dedmen** [comment]
Last weekend someone dropped a fuel nozzle into a destroyed building, bricking the fueltruck too.
