### ISSUE TITLE
NVG overlay overlaps devices

### ISSUE THREAD

**Issue by ColdEvul** [acemod/ACE3#7873]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98` stable
- **CBA:** `v3.15.1.200418`
- **ACE3:** `3.13.3`
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
Eyewere overlay shadow over the microdager. Zooming move it out

**Steps to reproduce:**
- Open Microdager 
- Apply Night Vision Googles or partly covering eyewearfilter
- Magic zoom your eyes

**Expected behavior:**
Not to shadow over or get out of shadow.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- *Visual*

**Additional context:**
- This is most visible for the RHS or other "circle" filter eyewear

**Screenshots:**
![20200824213143_1](https://user-images.githubusercontent.com/13811113/91090884-10b38d80-e656-11ea-9252-76f5df0d215b.jpg) ![20200824213145_1](https://user-images.githubusercontent.com/13811113/91090889-11e4ba80-e656-11ea-83f7-d90ac1e94196.jpg)

**Comment by BaerMitUmlaut** [comment]
This is by design and not a bug. Maybe we could add a setting for that? @jonpas

**Comment by Whigital** [comment]
Ref. https://github.com/acemod/ACE3/issues/6819 ....

**Comment by jonpas** [comment]
Duplicate of #6819.

This can't be fixed without a major rework, overlay (NVG model) is on top of everything.

**Comment by ColdEvul** [comment]
Just stubble over it. It's fine and it's not that annoying figured it was worth documenting.

**Comment by jonpas** [comment]
Forgot to close this as duplicate apparently (same root cause, so we don't need 2 issues open).
