### ISSUE TITLE
Spectator nightvision mode does not work in first person POV for non-local units

### ISSUE THREAD

**Issue by derbismarck** [acemod/ACE3#7881]
**Mods:**
- **Arma 3:** `1.98 stable`
- **CBA:** `3.14.0 stable`
- **ACE3:** `3.13.0 stable`

**Description:**
When in ACE3 spectator, nightvision modes do not function while spectating any non-local unit in first person perspective.

**Steps to reproduce:**
- Spectate another player from ACE3 spectator
- Have the player enable NVGs
- Watch the other player in first person
- See that NVG state of the spectated player isn't respected
- See that a short pulse of NVG occurs every ~18.5 seconds

**Expected behavior:**
- NV state should turn on when the spectated player has NVGs on, and turn off when the spectated player has NVGs off

**Where did the issue occur?**
- Dedicated environment and local multiplayer

**Additional context:**
This is **fault/BI** -- see https://feedback.bistudio.com/T122792 -- in EGS, they use the same `switchCamera` method on a `camCurator` camera, and it fails in the exact same manner.

**Comment by derbismarck** [comment]
After wrestling with this onet, I came up with a solution that seems to be working with POTATO spectate: simply use `spectatorCameraTargetUnit action ["nvGoggles", spectatorCameraTargetUnit` (or `NVGogglesOff`). The action only has a local effect when run on the spectating client, and it gets rid of the flashing issue as well. Only needs to be run every time the spectated unit enables/disables their NVGs, though unfortunately I can't find any NVG-related events, so handling for that has to involve a bit of network traffic.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
