### ISSUE TITLE
ace_common_fnc_progressBar underwater

### ISSUE THREAD

**Issue by grenadier2510** [acemod/ACE3#7882]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98` 
- **CBA:** `3.15.1.200418` 
- **ACE3:** `3.13.3.52'

**Description:**
ace_common_fnc_progressBar underwater no work.
How do i solve, thanks

**Comment by mharis001** [comment]
`ace_common_fnc_progressBar` checks if the [player can interact](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_progressBar.sqf#L62) in addition to the provided condition code. There is a [`isNotSwimming`](https://github.com/acemod/ACE3/blob/master/addons/interaction/XEH_postInit.sqf#L128) can interact with condition. 

This is likely the reason why the progress bar fails for you when the player is underwater. To correct this, you can specify `isNotSwimming` as an exception when calling `ace_common_fnc_progressBar`.

**Comment by grenadier2510** [comment]
thank you!
