### ISSUE TITLE
ACE Arsenal - Auto-change magazine priority not working

### ISSUE THREAD

**Issue by Warden3-8** [acemod/ACE3#7894]
**Mods (complete and add to the following information):** ACE/CBA
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]Latest version
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]Latest version
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]Latest version
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

Using ACE3, CBA and other mods but the issues don't appear on BI Virtual Arsenal that using ACE, CBA and other mods. It only appear using ACE Virtual Arsenal so clearly an issue linked to it.

**Description:**
Each weapon can have different camo. Same thing for mags. BI Arsenal automatically switch to the mag camo that fit the selected weapon camo. ACE Arsenal don't do it anymore in a certain situation (explained after)

**Steps to reproduce:**
- Start ArmA 3.
- On Main Menu, click to open ACE Arsenal.
- Select a weapon that have camo variants, for exemple MX rifles (but not only these one, all weapons have the same issue).

Now it's more particular. There is two different steps that leads to different situation.

- Situation 01 : Select the black MX rifle. A black mag is added. Then, without changing to any other weapon, select another MX rifle that uses the same mags (magazines and magazineWell) like the green MX rifle. Instead of having the green camo magazine loaded, the black one stays. You have to manually change the magazine to see it loaded.

- Situation 02 : Select the black MX rifle. A black mag is added. Then, change to any other weapon, select an F2000 rifle for example. Then select another MX rifle again but with another camo like the green one. This time, by changing the weapon type, you have the correct green camo mag loaded.

Note: The same issue happened with different capacity mags. For example, following the Situation 01, MX rifles always load the first mag loaded matching the first rifle selected at 30 rounds capacity even if it's technically determined in config files that it's a 100 rounds one that must be loaded. So, if the black MX rifle is selected, it's always the black MX mag 30 rounds that is loaded to all MX rifles until you change to another weapon (Situation 02) and select the other MX rifle that finally see the correct default mag type loaded.

**Expected behavior:**

The expected behaviour is that the ACE Arsenal should load the correct camo and capacity mag in each weapons each time we select a new weapon even of the same type.

**Where did the issue occur?**

Always with ACE Arsenal.

**Log Files:**

N/A

**Additional context:**

N/A

**Screenshots:**

N/A

**Comment by Dystopian** [comment]
I like current implementation. Sometimes you first choose magazine (e.g. tracer one) and after it you switch weapon. So please don't fix it or add checkbox/setting/etc.
As for issue - you can always switch to weapon (F2000 instead of MX) and back to get correct magazine in MX.

**Comment by Warden3-8** [comment]
> I like current implementation [...] So please don't fix it

Sorry but it's a problem that needs to be fixed. It's not the actual and normal way the arsenal must work. And it's not only because you like this problem that it must not be fixed.

But fix this issue and after that add an alternate option is still possible. But currently, it's not constructive to asking for an issue to not being fixed.

**Comment by Warden3-8** [comment]
Not agreed. Original BI Arsenal works in the normal way that it automatically add the magazine that is the first in the "magazines[]" line in config files.

So if that don't work like expected, it's an issue, not a feature. It can work as a feature if you add an alternative option like you mentioned it.

**Comment by Warden3-8** [comment]
I'm really tired of this. It's like internet is just full of people who just wants to always confront people who report something that has to be fixed.

ACE Arsenal worked like BI Arsenal. It just add features that makes it a more complete version. Like I already said (but it seems that nobody read and just stick to what they want) in the config files for each weapon, the magazine type loaded by default when we select a weapon in the Arsenal is define in the "magazines[]" line. So, if the Arsenal take this info into consideration, there is a reason. If that don't work like expected, it's because there is any issue. And that was a good thing to have the first magazine (majorly the most adapted one) to be selected after being defined in the "magazines[]" line in the config file.

I'm here to report what I find to be an issue, not reading that I have to stop asking for this just because that don't fit your tastes. Now, leave me alone and let someone from ACE Team answer to my question. If ACE Team said the will not change it, I will accept it and just stop using ACE Arsenal. Really, it's getting harder and harder to stay in peace in internet these time.

**Comment by jonpas** [comment]
Anyone can give their opinion just like you can.

BI Arsenal magically switching items is just bad user experience, this among other things was probably done on purpose without magical changes.

Other contributors to ACE Arsenal component can most likely confirm.

**Comment by Warden3-8** [comment]
It's a bug report site, and as far as I know, we are here to report issues and not giving any opinion. This is for chats or forums about ACE mod. But not here. If the situation had been reversed and I had given my opinion regarding another report, I would certainly have been told that this is not the subject and that I am out of it.

The thing is it's not about BI Arsenal, this one working good. ACE Arsenal is the problem actually because... Well, already explained above. Saying that it's "just bad user experience" is pretty easy. The fact is that it's not supposed to work like this.

But if you're not interested about bug reports, no problem, I will not take the time to report anything in the future.

Since I seem to be disturbing, I would avoid coming back to bother you. Good continuation.

**Comment by jonpas** [comment]
I am sorry, but you don't decide what's an issue/bug and what isn't.

First of all, ACE Arsenal is not trying to have equivalent features or how they work as BI Arsenal. That's why it's optional.

Second, this isn't a clear bug, it warranted discussion and people gave their opinion, this is why comments are possible here. What you are describing is an off-topic discussion, this one is exactly on topic of this "issue". No idea where you got "no opinion" rule from.
