### ISSUE TITLE
AI patients get kicked out of vehicle when player loads

### ISSUE THREAD

**Issue by DieNakies** [acemod/ACE3#7897]
**ACE3 and CBA3 tested along with noticing it with many other mods**
**Description:**
if you have an unconscious AI, stabilize them, load them on a vehicle for MEDEVAC they get kicked out if you get in the same vehicle, like it doesn't recognize when a loaded patient AI is occupying a slot

**Steps to reproduce:**
Load Patient onto vehicle
board vehicle
if you selected the same seat (or if you board the vehicle from the ramp where you don't get to pick spot) the patient gets dumped onto the ground and you take their seat

**Expected behavior:**
board the vehicle in the next available seat accounting for patients

**Where did the issue occur?**
Self hosted multiplayer, Eden Editor

**Comment by DieNakies** [comment]
I'm sure the intent for this feature was multiplayer, but I want my AI squad to live as well

**Comment by BaerMitUmlaut** [comment]
Tested, this seems to be vanilla behaviour. AI units that are unconscious either switch seats or are ejected if you occupy their seat. I don't think we can prevent this behaviour unfortunately.
