### ISSUE TITLE
Medical - Units inside exploding vehicle don't take enough damage

### ISSUE THREAD

**Issue by mjc4wilton** [acemod/ACE3#7898]
**Is your enhancement related to a problem?**
If a player or AI is inside a vehicle when it explodes, they are mostly fine and often times can walk away, albeit limping. Same issue is across ground and air vehicles, most likely why helicopter / plane crashes are underwhelming.

**Solution you'd like:**
Increase the damage a crew receives when inside a vehicle.

**Alternatives you've considered:**
None

**Additional context:**
Does not matter if the player wears body armor or what vehicle they were in. Effect is still minimal

**Comment by Vdauphin** [comment]
See https://github.com/acemod/ACE3/issues/7305

**Comment by kymckay** [comment]
Closing in favour of keeping conversation to #7305
