### ISSUE TITLE
port the ACE 2 wireguided missile guidances and sounds to ACE 3

### ISSUE THREAD

**Issue by cych** [acemod/ACE3#790]
When Using the RHS escalation mod, all the vehicles has the vanila arma 2 missile guidance and sound effect, who are terribles.

could you port the ACE 2 ace_sysmissileguidance to ACE 3 ?

**Comment by jaynus** [comment]
#414 missile guidance is already slowly being re-written. RHS, however, will be using their own/vanilla systems and may or may not implement ACE AMG. http://ace3mod.com/wiki/framework/advanced-missile-guidance.html
