### ISSUE TITLE
Surgical Kit not working

### ISSUE THREAD

**Issue by asdzxc485263** [acemod/ACE3#7903]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98
- **CBA:** `3.15.1
- **ACE3:** `3.13.14
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
surgical kit not working

**Steps to reproduce:**
I cannot use surgical kit, I can use PAK only when in facility ticked as medical facility in editor

**Expected behavior:**
I cannot use surgical kit, I can use PAK only when in facility ticked as medical facility in editor

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

ACE medical cba 

force force   ace_medical_ai_enabledFor = 2;
force force ace_medical_AIDamageThreshold   = 1;
force force   ace_medical_bleedingCoefficient = 0.5;
force force   ace_medical_blood_bloodLifetime = 900;
force force ace_medical_blood_enabledFor   = 2;
force force   ace_medical_blood_maxBloodObjects = 500;
force force ace_medical_fatalDamageSource   = 1;
force force   ace_medical_feedback_painEffectType = 0;
force force ace_medical_fractures = 1;
force force ace_medical_gui_enableActions   = 0;
force force   ace_medical_gui_enableMedicalMenu = 1;
force force   ace_medical_gui_enableSelfActions = true;
force force ace_medical_gui_maxDistance =   3;
force force   ace_medical_gui_openAfterTreatment = true;
force force ace_medical_ivFlowRate = 10;
force force ace_medical_limping = 1;
force force ace_medical_painCoefficient =   1;
force force   ace_medical_playerDamageThreshold = 25;
force force   ace_medical_spontaneousWakeUpChance = 0.5;
force force   ace_medical_spontaneousWakeUpEpinephrineBoost = 30;
force force   ace_medical_statemachine_AIUnconsciousness = true;
force force   ace_medical_statemachine_cardiacArrestTime = 900;
force force   ace_medical_statemachine_fatalInjuriesAI = 0;
force force   ace_medical_statemachine_fatalInjuriesPlayer = ;
force force   ace_medical_treatment_advancedBandages = true;
force force   ace_medical_treatment_advancedDiagnose = true;
force force   ace_medical_treatment_advancedMedication = true;
force force   ace_medical_treatment_allowLitterCreation = true;
force force   ace_medical_treatment_allowSelfIV = 1;
force force   ace_medical_treatment_allowSelfStitch = 1;
force force   ace_medical_treatment_allowSharedEquipment = 0;
force force   ace_medical_treatment_clearTraumaAfterBandage = true;
force force   ace_medical_treatment_consumePAK = 0;
force force   ace_medical_treatment_consumeSurgicalKit = 0;
force force   ace_medical_treatment_convertItems = 0;
force force   ace_medical_treatment_cprSuccessChance = 1.0;
force force   ace_medical_treatment_holsterRequired = 0;
force force   ace_medical_treatment_litterCleanupDelay = 600;
force force   ace_medical_treatment_locationEpinephrine = 0;
force force   ace_medical_treatment_locationPAK = 0;
force force   ace_medical_treatment_locationsBoostTraining = true;
force force   ace_medical_treatment_locationSurgicalKit = 0;
force force   ace_medical_treatment_maxLitterObjects = 500;
force force   ace_medical_treatment_medicEpinephrine = 0;
force force   ace_medical_treatment_medicPAK = 1;
force force   ace_medical_treatment_medicSurgicalKit = 1;
force force   ace_medical_treatment_timeCoefficientPAK = 1;
force force   ace_medical_treatment_woundReopening = true;

**Comment by mharis001** [comment]
Your value for the `ace_medical_treatment_advancedBandages` setting is `true`. This setting is now a number and a value of `2` enables bandage reopening which is required to be able to stitch wounds.
