### ISSUE TITLE
Add ability to use speed limiter while driving vehicle from gunner/commander seat

### ISSUE THREAD

**Issue by GordonWeedman** [acemod/ACE3#7906]
**Is your enhancement related to a problem?**
Right now the speed limiter is only usable from the driver seat, which can be a nuisance when using AI to manually drive while seated in a gunner or commander seat, and you want to drive at a specific speed.

**Solution you'd like:**
A way to use the speed limiter while driving a vehicle through an AI from a gunner or commander seat.

**Comment by BaerMitUmlaut** [comment]
#3594
