### ISSUE TITLE
ACE View Distance should probably be part of ACEX

### ISSUE THREAD

**Issue by Freddo3000** [acemod/ACE3#7908]
**Is your enhancement related to a problem?**
The scope of it seems similar to ACEX View Restriction and ACEX Volume, which are part of ACEX. There's also currently some issues regarding setting view distance via script, such as this one: https://feedback.bistudio.com/T150535

Additionally the presence of ACE View Distance seems to be poorly communicated, as in my experience new players often complain about their view distance sliders not working and everything being behind a fog wall.

**Solution you'd like:**
Move ACE View Distance to ACEX

**Additional context:**
Not sure how feasible this is seeing as it has been in ACE for quite some time now.

**Comment by BaerMitUmlaut** [comment]
I don't think this is a good idea because of backwards compatibility.

**Comment by jonpas** [comment]
Agreed with @BaerMitUmlaut. I think it fits ACE3 fairly well anyways.
