### ISSUE TITLE
ace3mod.com use ALIAS/CNAME for redirect

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#791]

**Comment by jaynus** [comment]
I've followed the instructions at https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/

I dont understand what the different setup you want is. An ALIAS record? I cant do alias records on my dns

**Comment by bux578** [comment]
The A Record redirect seems to be only a 302 redirect. And google hates those. Can't do anything with it (e.g. submit a sitemap.xml or verify certain services).

only solution is to change from an A-Record to either

ALIAS http://subosito.com/github-hosted-redirect

or CNAME http://stackoverflow.com/a/20942470

**Comment by jaynus** [comment]
http://ace3mod.github.io/ or acemod.github.io?

**Comment by jaynus** [comment]
Also, I dont much understand how an A record is a 302 redirect; its not, its a direct DNS entry. but whatever. Now our domain isn't actually ace3mod.com anymroe again, its forwarding to github again.

**Comment by bux578** [comment]
I don't understand it aswell just pointing to some stuff i've found online.

**Comment by bux578** [comment]
```
Remote Address:192.161.48.106:80
Request URL:http://ace3mod.com/
Request Method:GET
Status Code:301 Moved Permanently (from cache)

Response Headers
Content-Length:193
Content-Type:text/html
Date:Sat, 11 Apr 2015 06:09:24 GMT
Location:http://acemod.github.io/ACE3/
Server:nginx/1.4.6 (Ubuntu)
```

**Comment by bux578** [comment]
Now it seems to work

```
Remote Address:23.235.43.133:80
Request URL:http://ace3mod.com/
Request Method:GET
Status Code:200 OK
```
