### ISSUE TITLE
Create ACE3 action on doors

### ISSUE THREAD

**Issue by Tress16** [acemod/ACE3#7911]
I'm trying to create a ace3 action on a door (selectionName = "door_3") but it does not work.
The action is not on the door but on the building.

I have placed a building in 3ditor (Varname = MyHouse) an run follow code in cosole:
`private _action = ["iV_DoorActions", "Breaching", "", {hint "DONE!"}, {true}, {}, [MyHouse], {MyHouse selectionPosition "door_3"}] call ace_interact_menu_fnc_createAction;
[MyHouse, 0, ["ACE_MainActions"], _action] call ace_interact_menu_fnc_addActionToObject;`

I have tried all of the 3 options (Code for position, position array and selectionName string). 
Maybe there is a bug inside the code or in the description how to use it?

**Comment by commy2** [comment]
The way you wrote this you're creating a subaction on the ACE_MainActions node. There likely is no such node, so it is created at the default position being the object center.

```sqf
private _action = ["iV_DoorActions", "Breaching", "", {hint "DONE!"}, {true}, {}, [MyHouse], {_target selectionPosition "door_3"}] call ace_interact_menu_fnc_createAction;
[MyHouse, 0, [], _action] call ace_interact_menu_fnc_addActionToObject;
```

instead.

This is not a bug, why is it on the issue tracker?

**Comment by Tress16** [comment]
I wasn't sure if it was a bug.
Since i had been working on it for over 15 hours
and there was no solution in sight it could have been a bug.

Sorry

**Comment by PabstMirror** [comment]
@Tress16 - Checkout this code https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_userActions_addHouseActions.sqf#L82-L92

It creates a dummy invisible object and puts it at the memory point you want on the house and adds actions to the new object.
The whole file is adding actions to doors based on vanilla userActions, which may be close to what you want

**Comment by Tress16** [comment]
OK, thanks. Will take a look.
