### ISSUE TITLE
CBA/ACE Server mismatch

### ISSUE THREAD

**Issue by ndanilo8** [acemod/ACE3#7912]
**Mods (complete and add to the following information):**
- **Arma 3:** `Launcher version: 1.5.146373 Game version: 1.98.146373
- **CBA:** ` 3.15.1.200418`
- **ACE3:** `3.12.3.36` 
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
So we updated the server's ACE version from 3.12.3.36 to the latest Version 3.13.4
After doing that, we couldn't join the server anymore. After reviewing the .rpt files we noticed the following: 
```
21:16:22 [ACE] (common) INFO: ACE is version 3.12.3.36.
21:16:22 [ACE] (common) INFO: CBA is version 3.15.1.200418 (min required 3.8.0)
```
It made us think it didn't actually update, we tried unsubscribing CBA and ACE from steam and re-installing.. but still:
` 17:16:25 [ACE] (common) ERROR: Client/Server Version Mismatch. Server: 3.12.3.36, Client: 3.13.4.55`
It keeps thinking that it still the other previous version and not the newest.
We repeated (re-subscribing) from steam but we deleted the !Workshop/ACE and !Workshop/CBA folders. but still it gave us the same error 
` 17:16:25 [ACE] (common) ERROR: Client/Server Version Mismatch. Server: 3.12.3.36, Client: 3.13.4.55`

**Expected behavior:**
It should have updated ACE and CBA all together without any issue whatsoever.

**Where did the issue occur?**
- Dedicated server (ServerBlend)

**Log Files:**
https://pastebin.pl/view/e857c419

**Comment by commy2** [comment]
OP is wrong. There are a shitton more mods active than just CBA and ACE. You should only try with CBA and ACE.

You're running multiple versions of ACE, at least two:

17:37:17 C:\TCAFiles\Users\daniel17\11032\@1609526995\addons\ace_common.pbo - cd980dc2
17:37:17 C:\TCAFiles\Users\daniel17\11032\@463939057\addons\ace_medical.pbo - 434b0b9a

This cannot work.

This is a bug tracker. If you want help setting up your server, you're better of asking on a forum/Slack/Discord.
