### ISSUE TITLE
Colorblind Options

### ISSUE THREAD

**Issue by Wolfe-glg** [acemod/ACE3#7915]
Hello!

Is it possible to add an option to adjust the coloration of the medical menu or the medical symbols that show up in the Interaction Menu?

I see the option to adjust the text color for the Interaction Menu, but there is no option to adjust the medical menu coloration. For someone who is color blind, it is difficult to visually see the difference between light wound on limbs and bandages wounds on the Patient Status Diagram of the Medical Menu. As well as some of the text is hard to read.

**Comment by commy2** [comment]
#3594
