### ISSUE TITLE
Ability to use primary weapons as CSW components

### ISSUE THREAD

**Issue by simkas** [acemod/ACE3#7917]
Right now, it appears that CSW weapons can only be assembled using items that go in a unit's launcher slot. It would be great if that was also possible with items that were in a player's primary weapon slot. This would allow for situations like if you have a player who is an MMG gunner, you could have his assistant carry a tripod and make it possible to then put that MMG on the tripod and have it turn into a static emplacement if there's a turret set up for it. Perhaps this could be achieved if this check would instead checked for all weapons a player has, instead of just secondaryWeapon? https://github.com/acemod/ACE3/blob/38baa8dc6cb4ab00818100b5e7e0320db47654ca/addons/csw/functions/fnc_assemble_canDeployWeapon.sqf#L20

**Comment by severgun** [comment]
nice feature to have. But most of the time bipods are enough and it is not worth to carry tripod.

**Comment by Whigital** [comment]
The CSW items assemble into existing static weapons. To be able to mount a L/MG (or any other primary weapon for that matter), there would have to be static weapons for that combo of tripod/weapon.

3CB has that functionality for their GPMG's, but implementing that would be a huge undertaking, and probably out of the scope for ACE.

If you want to _mount_ your L/MG, just bring a `SSWT Kit` (`ACE_Item_Tripod`), that should be good enough 😃

**Comment by simkas** [comment]
I know it would require an appropriate static weapon, I'm not asking for the static weapons themselves to be added, I'd just like to have the functionality in ACE so other mods can do things like 3CB does without needing to include the scripts for it in the mod. Would just adding the possibility of doing that as a framework be a lot of work?

**Comment by Blutze** [comment]
> If you want to mount your L/MG, just bring a SSWT Kit

That'd be worse than finding a rock or a trench, because it is always standing instead of crouching. And no, bipod usage does not compare to the level of recoil control you'd get from a static weapon.

**Comment by MivinaTraktor** [comment]
An addition to this post. It would be very helpful to make identical ammunition interchangeable between infantry and stationary weapons. I.e. to load PKM ammo into a door mounted PKT in a Mi-8 or in a tank and vice versa.

**Comment by 10Dozen** [comment]
I made a mod for MG tripods [spoiler]https://github.com/10Dozen/dzn_MG_Tripod[/spoiler] -- it's work more like bipod with some scripted boost. Something like this in ACE may be an option.

But the general idea of ticket is interesting.
For example RHS and CUP has Metis ATGM, which is designed to use both from tripod and hands/rest. In both mods Metis launcher and Metis mountable tube are 2 separate items. But it will be awesome if we can use launcher from hands when it's needed or to mount the very same launcher on the tripod. Same may be performed with russian/soviet heavy mgs -- e.g. KORD may be used from bipods or be mounted on tripod.

**Comment by Drofseh** [comment]
@10Dozen your link is broken with the spoiler tag
