### ISSUE TITLE
Players falling from fast rope 

### ISSUE THREAD

**Issue by sevn10** [acemod/ACE3#7920]
**Mods:**
- **Arma 3:** `1.98.146728 Profiling`
- **CBA:** `3.15.1`
- **ACE3:** `3.13.4`
- **Achilles:** `1.3.1`
- **3den Enhanced:** `5.5`

**Description:**
When fast roping players are falling off the ropes near the bottom 1/3rd. 

**Steps to reproduce:**
Have fries enabled on Ghost Hawk
Have helo hover at 30m or lower
Prep fast rope
Deploy 36m rope
Fast rope
Fall near the bottom resulting in an injury

**Expected behavior:**
Not releasing the rope until player's feet hit the ground. 

**Where did the issue occur?**
Dedicated, Self-Hosted Multiplayer, Singleplayer, Editor (Singleplayer), and Editor (Multiplayer)

**Comment by BaerMitUmlaut** [comment]
Are you using AI pilots?

**Comment by sevn10** [comment]
Yes, I was for these tests.

**Comment by BaerMitUmlaut** [comment]
There's your problem.
