### ISSUE TITLE
ARMA3/CBA ERROR "include file \a3\functions_f\Debug\fn_isDebugConsoleAllowed.sqf

### ISSUE THREAD

**Issue by roguewarrior-maker** [acemod/ACE3#7926]
i opened the game with CBA and i get this error i look all over the internet for a solution but i couldnt find one can someone help me please

**Comment by PabstMirror** [comment]
Verify arma in steam, make sure you are on version 1.98

**Comment by AnudaPasandul567** [comment]
its easy to fix the problem just goto doucuments>Arma 3> you will see some files and some scipts just copy the files ex: Composision,missions,Mpmissions,Saved,usersaved . only copy that files and paste it some where. Now delete all files in arma 3 folder then paste that files you copy now delete CBA mod play !

**Comment by AnudaPasandul567** [comment]
I have fixed the error and allso played using cba and ace

**Comment by AnudaPasandul567** [comment]
Download cba version 2.4.1 if you want ace too then download ace version 3.6.1 enjoy i will send link asap to downlad ace and cba

**Comment by BaerMitUmlaut** [comment]
@AnudaPasandul567 your advice is bad and you're commenting on an issue that was closed in 2020 with advice how to actually fix it. Please stop.
