### ISSUE TITLE
Medical Ace problem

### ISSUE THREAD

**Issue by santiaskt258** [acemod/ACE3#7949]
Hello

I have a issue with the medical ace mod, noce porque no me funciona en el servidor.
se no hay bugeado todo, eso que esta configurado
![Captura de pantalla (33)](https://user-images.githubusercontent.com/72516325/95360885-6bb9e080-08a2-11eb-8cbd-5a2d4189a8fd.png)

**Comment by jokoho48** [comment]
1. English Please
2. Please fill out the issue template
3. We do not support the usage of mods that steal content like Star Wars: Opposition Mod.

**Comment by santiaskt258** [comment]
i saw, thanks, you have a coleccion in steam worshop of star wars?

**Comment by BaerMitUmlaut** [comment]
No.
