### ISSUE TITLE
Open/Show MicroDAGR GPS keybinds

### ISSUE THREAD

**Issue by Greedforce** [acemod/ACE3#7961]
**Is your enhancement related to a problem?**
There are no keybindings to Open or Show the MicroDAGR specifically (like with the Kestral for instance). My suggestion is to simply add these keybindings, as the MicroDAGR is frequently used by JTAC/TACP for 8 and 10 digit grid coords. I know this would significantly improve the experience of my unit, at the very least.

**Solution you'd like:**
Add "Open MicroDAGR GPS" and "Show MicroDAGR GPS" keybind options, that would work much like the "Open Kestral 4500" and "Show Kestral 4500" options.

**Alternatives you've considered:**
The DAGR keybindings does not currently apply to the MicroDAGR. Perhaps having them use the same keybindings could be an option?

**Additional context:**
There is currently a way of opening and closing the MicroDAGR via the Toggle/Close/Cycle Handheld Device options, however since both the Kestral 4500 and ATragMX have their own specific keybinds, even though they can also be opened this way, I think it's only fair for the MicroDAGR to be given similar options. I also think the specific keybinds are a lot more streamlined than the ones that cycle between the 3.

Screenshots of the options I reference in this post:
![microDAGR keybind missing](https://user-images.githubusercontent.com/45170392/96376644-80d71f00-1180-11eb-9a7c-768ba413fd78.PNG)
![microDAGR keybind missing2](https://user-images.githubusercontent.com/45170392/96376645-82a0e280-1180-11eb-8b83-0d1ec52fb21e.PNG)

**Comment by jokoho48** [comment]
feature requests belong here #3594
