### ISSUE TITLE
Spray Paint - Quick Tag functionality

### ISSUE THREAD

**Issue by Greedforce** [acemod/ACE3#7962]
**Is your enhancement related to a problem?**
I propose that upon holding down the "Spray Paint - Quick Tag" keybinding, while having multiple spray paint colors in your inventory, it should bring up a ace interact menu with the different color options to allow you to pick the color.

**Solution you'd like:**
Implement a ace interaction menu that allows you to pick the color for your "Quick Tag" keybind, either upon use of the feature, or to set a default before hand.

**Alternatives you've considered:**
Being able to set a default would also be a good way of implementing this, if you don't want to make the "Quick Tag" slower.

**Additional context:**
Currently the "Spray Paint - Quick Tag" keybind seems to pick a color at random, making it pretty much useless when carrying multiple colors.

**Comment by jokoho48** [comment]
feature requests belong here #3594
