### ISSUE TITLE
Losing command role to AI

### ISSUE THREAD

**Issue by TLP020** [acemod/ACE3#7963]
Very sorry upfront if I'm not following the rules, I just want to know if someone else has maybe run into this issue and has a satisfying answer for it.

I installed ACE today, and the RHS and RHS Compat mods. I only play SP, hosting Antistasi Community Version for myself to play. I own basegame and Apex. 

When I get injured, I lose my teamleader role and have no idea how to get it back. It makes Antistasi unplayable for me.

Anyone have any idea how to solve this issue? 

Thanks!

**Comment by Drofseh** [comment]
You need to fill out the issue template in full.

**Comment by TLP020** [comment]
I understand, but as I said I tried this to look for other experiences - not a full blown troubleshoot. I know other people have run into this, just need to know if it can be fixed.

Sorry for the hassle, remove at your discretion.
