### ISSUE TITLE
Using settings & keybindings in singleplayer

### ISSUE THREAD

**Issue by jacombobf** [acemod/ACE3#7964]
**Mods: **
- **Arma 3:** `1.98.146303`
- **CBA:** `3.15.1` 
- **ACE3:** `3.13.4` 

**Description:**
I've installed the those mods in a different folder from the game itself, so, when i'm going to config the keybindings or config the add on for the campaign itself it says that i've must start a mission first. I've tried creating missions or servers and nothing changes...

What can i do or how can i fix this? I'll appreciate any help.
Thanks in advance.

**Steps to reproduce:**
- Go to Settings
- Click ADDON settings
- See "You need first to start a mission"

**Expected behavior:**
Well, to use ACE3 mod, and its features

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Virtual Arsenal

**Screenshots:**
![image](https://user-images.githubusercontent.com/73255077/96786593-232c1800-13b6-11eb-8af7-73654c0c2c46.png)
As you can see, it's all grayed out and can't be modified. What can i do?

**Comment by BaerMitUmlaut** [comment]
I don't see "You need first to start a mission" in your screenshot? You are the server in single player, and that tab is accessible.
