### ISSUE TITLE
High command interface interferes with several ACE map features

### ISSUE THREAD

**Issue by ComboTombo** [acemod/ACE3#7971]
**Mods (complete and add to the following information):** None
- **Arma 3:** `2.0` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.1` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.4` [eg. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
When interacting with the map through the High Command interface, many features of ACE Map will stop working. Sometimes, you will not be able to move map markers around or edit their text/color/symbol. If you're at night and you use a flashlight on your map, the flashlight could get stuck at the last position it was at before you enter the HC interface. If you're using the map tool, you won't be able to move it around the map and it will be stuck.

**Steps to reproduce:**
- Go to the editor and setup your HC module
- Place down a squad and make sure you can control it with HC
- Enter the scenario, place down map markers, play around with the map tool, turn on your flashlight
- Enter the HC interface, order your units around, click on em, etc
- Leave the HC interface and attempt to do the previous interactions

**Expected behavior:**

**Where did the issue occur?**
- Dedicated

**Log Files:**
- Unable to

**Additional context:**
Sometimes, these bugs do not occur. Sometimes they do, but return to normal after some time.

**Screenshots:**
N/A.

**Comment by BaerMitUmlaut** [comment]
I cannot reproduce this in SP, can you? An RPT file would be helpful.

**Comment by krieghof** [comment]
I found a reliable way to reproduce this bug.
Basically it happens when you lose control of the HC. So make sure your controlled squad gets killed and you don't have  access to the HC GUI anymore.

**Comment by krieghof** [comment]
The .zip should contain all necessary files for the example mission. I also made a small video where I show the maptool and the map gesture (yellow point), after I lost HC. If there is something else I could do, please let me know.

https://youtu.be/ga_gAc3HJUQ
[hc_ace_bug.zip](https://github.com/acemod/ACE3/files/5812473/hc_ace_bug.zip)

**Comment by BaerMitUmlaut** [comment]
Found the culprit (`A3\modules_f\HC\data\scripts\HC_local.sqf`):
```sqf
{
	(uinamespace getvariable "_map") ctrlSetEventHandler [_x, ""];
} foreach ["mousemoving","mouseholding","mousebuttondown","mousebuttonup","keydown","keyup"];
```

These lines remove all event handlers that any mod adds to the map. This is not something we can fix and is a bug within BIs code.

**Comment by bux** [comment]
@dedmen ^

**Comment by commy2** [comment]
```sqf
uinamespace getvariable "_map"
```
This code gave me cancer.

**Comment by BaerMitUmlaut** [comment]
Then I'd recommend you to not look at the rest of it, it's like that throughout.

**Comment by dedmen** [comment]
Made a ticket for 2.04, though I have no idea if that stuff is needed for anything, or if it serves a purpose.
If its required for something we won't remove that.

**Comment by BaerMitUmlaut** [comment]
The event handlers are saved within a different function and can be removed normally (and actually are removed at some point, however I didn't look when exactly that is done).

**Comment by dedmen** [comment]
Is there a different solution you can think of? like scriptedEH after it removed these eventhandlers so you can add them back?
Would rather not touch this old delicate code, one wrong move and everything falls apart.

**Comment by BeriloJr** [comment]
A function alike would be more than appreciated to reassemble those EH, then we can just call it and all EH are re-established. My HC can control its unities on the battlefield and all ace 3 map tools are useless after that, would be nice to have it working again.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Comment by xDNKx** [comment]
Found a way to reproduce this bug 100% times on up-to-date MP game session (playing Antistasi Ultimate + Ace + RHS):
- As a Commander, hire any emplacement squad, and send them to desired position
- Right after emplacement task complete, all ACE map tools/features stop working for Commander.

Tried: keeping another HC squad as a reserve; Not looking at the map/turning off HC mode while squad finishing emplacement - nothing helps.

Many pardons if this is something to do with AU, than ACE ^_^

**Comment by BaerMitUmlaut** [comment]
We know what the problem is, we can't fix it though.
