### ISSUE TITLE
RHS Armor values with ACE Compat patches are broken.

### ISSUE THREAD

**Issue by crimzonmartin** [acemod/ACE3#7972]
Mods (complete and add to the following information): 

    Arma 3: 2.0
    CBA: 3.15.1 (workshop)
    ACE3: 3.14.3 (workshop)
    RHSUSAF: 0.5.4 (workshop)
    Ace Compat - RHS United States Armed Forces: stable (workshop)

   

Description:
Normal Arma 3 armor works as intended, but when you shoot someone with most RHS armors, they take about 30 shots to kill. RHS without ACE3 works fine, but with ACE the armor values are incredibly high. Not sure what more there is to say, but the compatibility patches don't fix the issue. It occurs with both US and Russian units with plate carriers.

Steps to reproduce:

    Go to the editor and view an RHS unit's arsenal
    Compared chest armor to vanilla armor values
    Test weapons against armor and see that it takes 29-30 shots to kill to the chest with RHS armor.

Expected behavior:
Armor would block 3-5 rounds before incapacitating.

Where did the issue occur?

   Editor, Local Multiplayer

Additional context:
Been having this issue for months, it seems like not all of the armors have ridiculous protection. 

Screenshots: 
https://steamuserimages-a.akamaihd.net/ugc/1695002886404760282/7E3C48E8651947845869309B1EC55EF5998FDA13/
https://steamuserimages-a.akamaihd.net/ugc/1695002886404759755/1B0D875F3EF560EB6F56A467362D3BE19E3942E1/

**Comment by Drofseh** [comment]
Fill out the issue template properly.

**Comment by BaerMitUmlaut** [comment]
We don't change those armor values nor the amount of damage RHS weapons do.

**Comment by crimzonmartin** [comment]
If you don't change those values, then why do the armors function as intended without ace, but don't function as expected with ace enabled? If there is an issue here, shouldn't the compat patch fix it?

**Comment by commy2** [comment]
Because RHS is a total conversion, acording to the developers, and not intended to work with base game content, or moded content made compatible with base game content.

**Comment by crimzonmartin** [comment]
What's the point of the compatibility patch then if it isn't supposed to make the two mods COMPATIBLE?

**Comment by commy2** [comment]
Probably to fix the most egregious errors, but not everything may be feasible. I don't maintain it, as I never use RHS myself in my comm.

**Comment by crimzonmartin** [comment]
Is it not supported anymore since it wasn't updated since 2016?

**Comment by Drofseh** [comment]
RHS compats were updated on August 31st

**Comment by crimzonmartin** [comment]
Well is this not an issue that needs to be fixed with the compat patch? I feel like enemies with crazy armor is something that needs to be looked at, because either players have to find a replacement for RHS or skip using ACE.

**Comment by BaerMitUmlaut** [comment]
We can't fix the armor on all vests and the damage on all weapons from such a large mod. That's just not feasible.
