### ISSUE TITLE
Ace Medical Player Re spawning After Getting Shot While Unconscious

### ISSUE THREAD

**Issue by TheParadoxNinja** [acemod/ACE3#7979]
**Mods (Ace, RHS, Zeus Enhanced W/Ace Compat):**
- **Arma 3:** `2.00`
- **CBA:** `3.15.1'
- **ACE3:** `3.13.4` 
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!

**Description:**
A while ago our milsim unit had Ace setup so that a player could only die after a certain amount of time being unconcious. For example a player could get 100000 while unconcious and not die until the 10 minute timer ran out. Now if a player gets shot they will die after taking enough damage even though player death is set to never.

**Steps to reproduce:**
Set player death to never unless cardiac arrest timer runs out. Shoot player while unconscious with a few dozen rounds and wait a few seconds.

**Expected behavior:**
Player will not die until cardiac arrest timer runs out.

**Where did the issue occur?**
-Self-Hosted Multiplayer 

**Screenshots:**
![dcefbd496ad6eca15f31748523910857](https://user-images.githubusercontent.com/73822398/97851806-b6185c80-1caa-11eb-8df5-715c94aadae7.png)

**Comment by BaerMitUmlaut** [comment]
Fixed by #7547.

**Comment by TheParadoxNinja** [comment]
> Fixed by #7547.

Excuse my ignorance but if i'm interpreting this correctly there is no way to get that old revive system back where you can only die but the timer is that correct?

**Comment by BaerMitUmlaut** [comment]
Right now in this very moment? No. You can still bleed out. The PR linked above adds a setting to prevent that.

**Comment by TheParadoxNinja** [comment]
> Right now in this very moment? No. You can still bleed out. The PR linked above adds a setting to prevent that.

How would I implement that, I noticed it changes and HPP file, but im not sure how to add that setting?

**Comment by TheParadoxNinja** [comment]
> > Right now in this very moment? No. You can still bleed out. The PR linked above adds a setting to prevent that.
> 
> How would I implement that, I noticed it changes an HPP file, but im not sure how to add that setting?

Whenever I try to download this edited version it doesnt download the addons as pbos.

**Comment by BaerMitUmlaut** [comment]
That's because the PBOs need to be built first. If you have no experience with this, I would recommend waiting for it to be released. You can also consult our wiki and our Slack for more information on how to build ACE, but in this case, a single patch PBO would be a better idea. Again, join Slack and I can explain everything in detail.
