### ISSUE TITLE
Profiling Branch - Marker Creation Game Crash

### ISSUE THREAD

**Issue by Khaosmatic** [acemod/ACE3#7992]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00.146898 PROFILING Branch`
- **CBA:** `v3.15.0.200404`
- **ACE3:** `3.13.4`

**Description:**
Game crash when opening map and trying to double click/place marker. Possible a conflict with map gestures and the profiling build? I realise the profiling build does not represent the stable branch, but whatever causes this issue may get put onto the stable branch.

**Steps to reproduce:**
- While running the Profiling branch go to Eden editor on any map and place down a single unit and preview the mission.
- Open the map and try to double click/place a marker.
- Game should crash out.

**Expected behavior:**
As soon as I double click on the map to place a marker the game immediately crashes and prompts to report an error log.

**Where did the issue occur?**
- Singleplayer/Eden editor.

**Log Files:**
[ArmaReport_Log_20201106T192044_afokh.zip](https://github.com/acemod/ACE3/files/5503087/ArmaReport_Log_20201106T192044_afokh.zip)

**Additional context:**
As mentioned above, it is on the profiling branch but whatever causes this issue may be put onto the stable branch and then cause this issue there as well. Testing it on the stable branch is fine and the error only occurs whilst running CBA and ACE. I believe this issue has only started happening as of the update to the profiling branch on the 06/11/2020.

**Comment by PabstMirror** [comment]
seems to be ace_markers_fnc_initInsertMarker around line 300
` _aceShapeLB lbSetCurSel _curSelShape;`   
no debug code fires after this line, but I see nothing wrong with it

**Comment by PabstMirror** [comment]
```
diag_log text format ["Test: %1 - %2 - %3", isNull _aceShapeLB, lbSize _aceShapeLB, _curSelShape];
 _aceShapeLB lbSetCurSel _curSelShape;
diag_log text format ["After"];
```
Test: false - 75 - 0,
commenting out that line allows it to reach "After" and not crash

so I don't think we're doing anything wrong, probably have to wait for bis to fix

**Comment by PabstMirror** [comment]
Tag @dedmen

**Comment by Brojustuserandomgenerationusername** [comment]
Yeah, it happens after a profiling branch update so its at the end of the day a Bohemia thing, yet an ACE compatibility issue.

**Comment by dedmen** [comment]
will check on monday, we changed lots of markery stuff.
But I cant repro on internal build (profiling changes + more)

**Comment by dedmen** [comment]
Diwakos crash is in DisplayInsertMarker::OnLBSelChanged when he selected the 5th item in a combobox, I assume there was no item in that slot.
Are you custom filling the combobox? might be marker channel?

Oh no marker channel is the custom thing ACE added right?
I need to look at it I don't remember :D

**Comment by dedmen** [comment]
Yeah I found it, though I'm not sure why that suddenly is an issue.
https://github.com/acemod/ACE3/blob/42f4edc9b71d752b22b91a10beba197cd7b224e4/addons/markers/functions/fnc_initInsertMarker.sqf#L232
crash here, you select element 0 in the MarkerShape combobox.
But that triggers the parents OnLBSelChanged handler.
which thinks that the LB is the channel select box, but the channel box is currently empty, and it tries to fetch the first element in a empty combobox.

**Comment by dedmen** [comment]
Found it, Programmer reworking disabledChannels and chat channel access rights and stuff, added check in marker to disable OK button when you select a blocked channel.
But, he assumed that the marker insert display only has a single combobox.

**Comment by dedmen** [comment]
Fix in profiling v5 probably this week. Thanks

**Comment by dedmen** [comment]
Fix is up
