### ISSUE TITLE
Player's medical state is sometimes not reset to Default from Dead on respawn

### ISSUE THREAD

**Issue by zharf** [acemod/ACE3#7996]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00 stable`
- **CBA:** `3.15.1`
- **ACE3:** `3.13.4`

**Description:**
After respawn player is sometimes left in Dead state in medical statemachine leaving them invincible.

**Steps to reproduce:**
- Die
- Respawn
- Observe state

**Expected behavior:**
Player state is properly reset to Default when respawned

**Where did the issue occur?**
- Dedicated

**Log Files:**
https://gist.github.com/zharf/dcc4cb8a5c1bc146a4f9cb8cdbdd3136 (just saying there's nothing in it indicating that this problem ever happened)

**Additional context:**
According to BaerMitUmlaut, the unit that you're given might not be local to the client for a few frames after respawning which is likely the cause of this issue as [`ace_medical_statemachine_fnc_resetStateDefault`](https://github.com/acemod/ACE3/blob/master/addons/medical_statemachine/functions/fnc_resetStateDefault.sqf) checks for `local _unit`.
We never (to my knowledge) had this issue prior to Arma's 2.00 update, since then it's been observed in every operation.
Could not reproduce the issue by just killing myself on the server without anyone else connected, I suspect the frequency of the locality issue is increased with player count and any other load that the server might be experiencing.

**Screenshots:**
https://www.twitch.tv/zharf/clip/HandsomeComfortableGarageArsonNoSexy
![deadornot](https://user-images.githubusercontent.com/1835646/98481645-5539d880-2204-11eb-801c-ba3fbe2ee9eb.png)

**Comment by BaerMitUmlaut** [comment]
The respawn EH should only trigger on the client that respawns, so I think we could just remove the local check here and we would be safe.
