### ISSUE TITLE
ACE Compats missing keys folder and .bikey file

### ISSUE THREAD

**Issue by nobodyshome** [acemod/ACE3#8004]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00.146773`
- **CBA:** `3.15.2.201119` 
- **ACE3:** `3.13.5`

**Description:**
The ACE Compat workshop mods for AFRF, USAF and GREF are all missing bikeys related to the latest update (19/11/2020)

**Steps to reproduce:**
- Subscribe to each compat on workshop
- Check the folder for the .bikey and/or keys folder

**Expected behaviour:**
.bikey file to be included for each of the compat mods

**Where did the issue occur?**
- Dedicated

**Log Files:**
- N/A

**Screenshots:**

**Comment by PabstMirror** [comment]
The original release of 3.13.5 had extra .bisigns in all of the `/optional` folders
We have issueed a re-released to fix (uploaded on a steam, there is a new zip on github)

I'm not sure if there is a need for each optional to have a `/keys` folder as **all** pbos are signed by the same key as the main ace mod
