### ISSUE TITLE
Rearm costs incorrect on limited supply based on ammo.

### ISSUE THREAD

**Issue by bennyboy-13** [acemod/ACE3#8005]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00.146773` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.2.201119` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.5` [eg. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
When you take ammo from a truck it should give you 'Number of rounds per box' (ie 1 Sabot shell or 1 bomb, or 400 7.62)  and charge you (in ammo supply costs) 'calibre in mm'.
It does not, it gives you 'Number of rounds' and charges you from the supply source 'calibre in mm' divided by magazine size.
This means a vehicle with a double the size magazine than another vehicle with the same calibre costs half the amount for each 'amount of rounds'
This is present in something like a  plane where if you install a pylon with 2 missiles, it will cost you half the amount to fill one missile than a pylon with a single missile
A single 105mm tank round should cost 105 supply for any 105mm capable vehicle - A tank that uses a different magazine size for its main turret (any mod-example 3CB Factions abrams with 28 rnd 105mm magazine) costs only a few points for one round as its magazine size is 28. Irrespective of changing it's calibre with ace_rearm_caliber it will always divide the cost by it's magazine size.
**Steps to reproduce:**
Find vehicles with the same calibre ammunition but differing mag size, This could also be planes with a differing amount of  missile capacity on a pylon. Empty the ammunition and start to resupply from a truck. Check how much the ammunition is costing for different sized magazines.
 Also check the differing cost for 35mm in a GM FlakPanzer. Needless to say because of the magazine size for HE being 16 times larger than AP. It cost 16 times less for it's 'calibre in mm' cost.

**Expected behavior:**
For any magazine that has it's calibre cost set by ace_rearm_caliber or by it's default calibre of magazine if not set, should cost exactly the same for each round or rounds of ammunition. 40 rounds of 25mm ammo should cost the same for any vehicle.
35mm rounds in a GM FlakPanzer should cost the same whether HE or AP. at the moment they wildly do not as one is a magazine of 640, and the other a magazine of 40.

**Where did the issue occur?**
Any game mode

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**
The last hurdle between me and finishing my mission ha! Keep up the support and good work

**Screenshots:**

**Comment by Drofseh** [comment]
@bennyboy-13 please put in the version numbers you are using, don't leave them as xx

**Comment by bennyboy-13** [comment]
> @bennyboy-13 please put in the version numbers you are using, don't leave them as xx

Apologies corrected. Latest on all.
Script that is to be looked at is fnc_removeMagazineFromSupply.sqf
I can see exactly how it happened.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
