### ISSUE TITLE
Ace Error: ace medical gui pbo is outdated

### ISSUE THREAD

**Issue by Mister-Bones** [acemod/ACE3#8006]
**Mods (complete and add to the following information):**

- **ACE3:** ace_medical_gui pbo is outdated

**Description:**
Anytime I load into eden editor and attempt to test it I get hit with an Ace Error: ace_medical_gui pbo is outdated

**Steps to reproduce:**
Unkown

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by bux** [comment]
Please fill out the complete issue template and provide the RPT file.

**Comment by Mister-Bones** [comment]
I've never used github before and made my account 40 minutes ago i dont know what you mean

**Comment by bux** [comment]
It's literally written in the template you deleted how to obtain the log files.
