### ISSUE TITLE
The Carrier Special Rig and Carrier GL Rig seemingly have swapped ballistic defense values

### ISSUE THREAD

**Issue by Dudejo** [acemod/ACE3#8008]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00`
- **CBA:** `3.15.2`
- **ACE3:** `3.13.5`

**Description:**
In spite of the in-game ballistic defense rating (not explosive), the Special rig does not stop bullets as efficiently (sometimes not at all) as the GL rig, even though the latter has lower ballistic defense.

**Steps to reproduce:**
1. Set up AI victims with both the Special rig and GL rig to shoot at.
2. Shoot AI victims until they die.

**Expected behavior:**
- I expected the AI victims with the Special rig to survive bullets for longer than those with the GL rig

**Where did the issue occur?**
- Editor (Singleplayer) as test environment

**Log Files:**
- [https://pastebin.com/aGmb4LSp](url)

**Additional context:**
- I'm running the medical setting "Only large hits to vital organs" and Critical Damage Threshold (both AI and Player) of 0.00

**Screenshots:**
<details>
<summary>GL rig screenshot</summary>

![20201120093934_1](https://user-images.githubusercontent.com/38837115/99875774-2afef800-2bc0-11eb-9790-0b7676c25dcd.jpg)
</details>
<details>
<summary>Special rig screenshot</summary>

![20201120093832_1](https://user-images.githubusercontent.com/38837115/99875748-ee330100-2bbf-11eb-8f9b-43bc42ccb204.jpg)
</details>

**Comment by bux** [comment]
Please provide the requested log file(s)

**Comment by Dudejo** [comment]
I posted the most recent file I have

**Comment by Salluci** [comment]
See #7799.

**Comment by Dudejo** [comment]
In that case, are there any plans to adjust the Special Rig's other statistics to compensate for the weaker defense?
