### ISSUE TITLE
Sorting backpacks by load causes an error message

### ISSUE THREAD

**Issue by Dudejo** [acemod/ACE3#8009]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.2` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.5` [eg. 3.0.0 stable, commit hash]

**Description:**
In the Arsenal, selecting "Sort by load" does not work and causes an error message to appear.

**Steps to reproduce:**

1. Open the Arsenal
2. Select the Backpack menu
3. Select "Sort by Load"
4. An error message black box appears while the list fails to sort

**Expected behavior:**
I expected the list to sort itself by load capacity with no issues.

**Where did the issue occur?**
- Virtual Arsenal

**Log Files:**
- https://pastebin.com/z96DJKgt

**Additional context:**
- The Arsenal was accessed from the map editor

**Screenshots:**
<details>
<summary>expand screenshot</summary>

![20201120101742_1](https://user-images.githubusercontent.com/38837115/99875614-06565080-2bbf-11eb-89d7-746d0327f438.jpg)
</details>

**Comment by bux** [comment]
Please provide the requested log file(s)

**Comment by Dudejo** [comment]
I posted the most recent file I have
