### ISSUE TITLE
Unconscious Unit Immune To Drowning

### ISSUE THREAD

**Issue by ong-yinggao98** [acemod/ACE3#8010]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00 stable`
- **CBA:** `3.15.2 stable`
- **ACE3:** `3.13.5 stable`

**Description:**
A unit that is unconscious will not drown in water no matter how long he has been submerged (provided he does not bleed out).

**Steps to reproduce:**

1. Start a new scenario with the following criteria:
   1. One player character and one NPC.
   1. Area must be near a water body.
   1. Player must have sufficient medical items.
   1. Unconscious unit wake-up chance must be 0% (only to prevent him from waking up and resurfacing halfway through testing).
1. Knock the NPC out without killing him.
1. Heal him completely.
1. Drag the NPC into the water.
1. Wait for 3-4 minutes (drowning usually happens around the 1 minute mark).
1. Pull the NPC out of the water.
1. Check vitals (NPC is stable).

**Expected behavior:**
The NPC should have died underwater as if he were finished off on land.

**Where did the issue occur?**
Editor (Singleplayer)

**Log Files:**
https://pastebin.com/fPdmHd3P

**Additional context:**
N/A

**Screenshots:**
This screenshot is from the time I first found this issue (the unit had been chilling in the Tanoan harbour for a good few minutes). I had already replicated the steps above in Stratis without any external mods by the time I've raised this issue (RPT file).
![20201121012021_1](https://user-images.githubusercontent.com/52755148/100052774-91527780-2e59-11eb-8358-4f806b5d26b6.jpg)

**Comment by Italiandrache** [comment]
Mhm, it sounds odd to me. I've once drowned while unconscious, albeit in multiplayer and with a slightly older version of ace. Can't remember which however.

**Comment by StopTakingAllTheNames** [comment]
> 
> 
> Mhm, it sounds odd to me. I've once drowned while unconscious, albeit in multiplayer and with a slightly older version of ace. Can't remember which however.

Same, I've sworn the same had happened at one point to me too, which is why I was surprised that these NPCs weren't dying when I dumped their unconscious bodies into the sea one day while messing around in the editor.

**Comment by Italiandrache** [comment]
> > Mhm, it sounds odd to me. I've once drowned while unconscious, albeit in multiplayer and with a slightly older version of ace. Can't remember which however.
> 
> Same, I've sworn the same had happened at one point to me too, which is why I was surprised that these NPCs weren't dying when I dumped their unconscious bodies into the sea one day while messing around in the editor.

It may be a stupid question, but can NPC's drown in arma vanilla in the first place? I think they should but have never tested it.

**Comment by StopTakingAllTheNames** [comment]
> It may be a stupid question, but can NPC's drown in arma vanilla in the first place? I think they should but have never tested it.

Yep, they sure do: 
[![](http://img.youtube.com/vi/PK0OxdHEFrk/0.jpg)](http://www.youtube.com/watch?v=PK0OxdHEFrk "")

**Comment by ZeusWrath** [comment]
Unfortunately the unconscious has many problems in ACE3:

> the unconscious will never drown in water like you said
> the unconscious will never be fired upon by the enemy,
> the unconscious will have ridiculous animations (rotation of the torso and head, twitching),
> the unconscious will talk and take orders, report the enemy, see enemy

I dream of getting an option to enable / disable unconscious, but this is not. As far as I remember, there was such an option in ACE3, but then it was removed.  

ACE3 team! please create such an option, the player will be able to turn off the unconscious for any problems in the future...
