### ISSUE TITLE
ACE Explosives CBA Settings tab gone

### ISSUE THREAD

**Issue by Max255PL** [acemod/ACE3#8014]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00`
- **CBA:** `3.15.2`
- **ACE3:** `3.13.5`

**Description:**
ACE Explosives CBA Settings tab is gone in newest version of ACE.

**Steps to reproduce:**
1. Load newest CBA and ACE.
2. Go to editor.
3. Go into Addon Settings.
4. Search for ACE Explosives tab.

**Expected behavior:**
- Well, it should be there as it was before

**Where did the issue occur?**
- Self-Hosted Multiplayer / Editor (Singleplayer)

**Log Files:**
- RPT: https://gist.github.com/Max255PL/bd2a57b7797a109d8534b0502d9b8809

**Additional context:**
Checked with all combinations of ACE 3.13.4, 3.13.5, CBA 3.15.1 and 3.15.2. Only gone with ACE 3.13.5.

**Screenshots:**
ACE 3.13.4: https://steamuserimages-a.akamaihd.net/ugc/1658976384877314911/847A8118D1965F7B8420739542393B631DC65915/

ACE 3.13.5: https://steamuserimages-a.akamaihd.net/ugc/1658976384877298610/BF7F86A4E9CAAEFDE3CEC173EE937407A6713E5C/

**Comment by veteran29** [comment]
It's there for me. I don't see any errors in your RPT. Are you sure you're not overwriting something with `-filepatching`? Pleasy try without the parameter.

**Comment by Max255PL** [comment]
Ok, so removing `-filePatching` did make it appear again. 
Issue is with any `cba_settings.sqf` file. At first I thought it was something in mine, but exported a fresh one with just CBA+ACE and loaded Arma with it and Explosived tab was still gone.

**Comment by Max255PL** [comment]
Fixed with latest version (3.13.6).
