### ISSUE TITLE
All Unconscious soldiers have wacky movements or twitching and even talk!

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#8019]
- **Arma 3:** `2.00` [stable]
- **CBA:** `3` [stable, last version, Steam subscribe]
- **ACE3:** `3.13.5` [stable]
- **A3 Thermal Improvement** 
- **Bullet Casing** 
- **Tactical Position Ready** 
- **Magazine Simulation A3** 

**Description:**
Unconscious units (player and AI together) have inappropriate behavior. They should not have any behavior in general, but the place of this unconscious units, in the absence of consciousness, has animation of movement - rotation or lifting of the body, twitching, movement and rotation of the head and arms  etc, etc.  
In addition, when a unit is unconscious, it continues to talk and responds to the commander's orders - ""Copy", "I take command", "Attacking" etc

All this together looks like a bad dream!

I made this [video example](https://www.youtube.com/watch?v=7RWsNpkkE4Y) so that you understand how it looks ugly.

I didn't catch moments for a long time, this is the second example that I get in the game, after 5 minutes of my test

I don't use ace_noradio.pbo, which is probably why I hear them (voices of Unconscious). 

I know that many people don't use ace_noradio.pbo also, when play in singleplayer games.  
Please just turn off any motion animations and voices (without ace_noradio.pbo also) for them, the unconscious ones should look adequate.

**Steps to reproduce:**

Places in the editor of 2 squads of opposing infantry fighters, turn on the spectator and watch the unconscious units within 2-5 min.

**Expected behavior:**
Unconscious soldiers shouldn't talk or have rotation or lifting of the body, twitching, movement and rotation of the head and arms  etc

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by milivojm** [comment]
This is a bug that prevents stealth missions. Players can try really hard to stay undetected but unconscious enemy AI will still communicate with their team members and reveal players.

**Comment by ZeusWrath** [comment]
> This is a bug that prevents stealth missions. Players can try really hard to stay undetected but unconscious enemy AI will still communicate with their team members and reveal players

yes, I noticed it. They keep recieve orders and reporting opponents. But the worst of all is not this, but the fact that it looks absurdly when they rotate on the ground.

**Comment by ZeusWrath** [comment]
ACE Team please add disabling option for the "Unconscious  condition" as it did before in old version your mod. This could help the player avoid any problems with unconsciousness now or in the future. You needlessly removed this feature from your mod

**Comment by ZeusWrath** [comment]
> ACE Team please add disabling option for the "Unconscious condition" as it did before in old version your mod

Or maybe there is still a some/another way? Can anyone tell me if the player can somehow turn off the unconscious ability in order do not meet this problem?

**Comment by YetheSamartaka** [comment]
> 
> 
> > ACE Team please add disabling option for the "Unconscious condition" as it did before in old version your mod
> 
> Or maybe there is still a some/another way? Can anyone tell me if the player can somehow turn off the unconscious ability in order do not meet this problem?

You can disable AI unconsciousness in addon options/cba_settings.

**Comment by ZeusWrath** [comment]
> You can disable AI unconsciousness in addon options/cba_settings.

OMG! I have not seen these settings, although I was looking for them!
I'll look again, thanks for the info

**Comment by ZeusWrath** [comment]
> You can disable AI unconsciousness in addon options/cba_settings.

where are these settings? CBA3 does not have these personal settings.
ACE3 Medical has no unconscious **on / off** settings also

I only see - checkbox **_AI unconscious_**

How can I disable unconscious for the Player?
