### ISSUE TITLE
AI opponents will not attack enemy unconscious

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#8020]
- **Arma 3:** `2.00` [stable]
- **CBA:** `3` [stable, last version, Steam subscribe]
- **ACE3:** `3.13.5` [stable]
- **A3 Thermal Improvement** 
- **Bullet Casing** 
- **Tactical Position Ready** 
- **Magazine Simulation A3** 

**Description:**

I watched the AI opponents for several days, but I never saw them shoot at the unconscious. They'll just ignore them
It doesn't look natural, especially with [this problem](https://github.com/acemod/ACE3/issues/8019).

**Steps to reproduce:**

Places in the editor of 2 squads of opposing infantry fighters, turn on the camera and watch the unconscious units.

**Expected behavior:**
AI has to shoot at the unconscious. If someone doesn't like it, you can make a selection setting in Medical Settings. Many other mods have this settings

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by BaerMitUmlaut** [comment]
This is intentional.

**Comment by ZeusWrath** [comment]
> This is intentional.

If the enemy does not shoot at the unconscious, it looks unnatural. **Why can't the setting be turned on / off?  Some mods have a setting - to shoot unconscious or not.**

**Comment by BaerMitUmlaut** [comment]
Because an unconscious unit is not a threat.

**Comment by ZeusWrath** [comment]
OK, Thank you for answer

**Comment by gripen888** [comment]
I have got exactly opposite problem. Unconscious unit is sometimes not changed to civilian side and ai will continue to fire at patient. Sometimes 1/4 of mag, other times 2 mags in row.

**Comment by BaerMitUmlaut** [comment]
Unconscious units do not change to civilian anymore. It's likely that this is an AI script interfering. If you don't use such a thing and can replicate this with just CBA and ACE, please create a new issue.
