### ISSUE TITLE
Please try to make blood of adequate color (ace_medical_blood)

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#8021]
**Is your enhancement related to a problem?**

The improvement is related to the visual effect.  
The blood in ACE3 Medical does not look natural. It's like a children's cartoon, it looks like paint, but not blood. When I play ACE3 it looks extremely unrealistic

Example here

http://images.vfl.ru/ii/1606520302/5f9e4960/32465890.jpg

**Solution you'd like:**
Please try make it more, more darker and some transparent, as in the vanilla game.
Transparency demonstrates the absorbency in surfaces onto which it is poured.

**Comment by BaerMitUmlaut** [comment]
#3594
