### ISSUE TITLE
Ability to enable/use vanilla repair

### ISSUE THREAD

**Issue by Raptoid** [acemod/ACE3#8026]
**Is your enhancement related to a problem?**
Not for ACE itself. Some mods do not allow repair for their vehicles from the ACE repair menu on helicopters, such as "Operation: Trebuchet"  and "UH-60 Pack A3." Would also be a nice feature to have for different types of missions.

**Solution you'd like:**
The ability to define specific vehicles for vanilla repair, perhaps in its attributes box or a toggle box within the CBA Ace Logistics settings menu in order enable vanilla repair for vehicles.

**Alternatives you've considered:**
Perhaps a generic simple repair option for all vehicles through ace interact that acts kind of like vanilla, like another CBA toggle setting maybe named "Simple Repair" which you can hover over the vehicle icon, next to cargo or seat interactions. The ACE options unit's efficiency attribute could still apply to this perhaps.

**Additional context:**
The actual problem stems from none of the helicopter parts showing up on ace interact, for example fuel tank, rotors, hull, etc.  Both mods tested alone, of which OPTRE was tested with their own team's ACE compatibility patch. I think in the long run it could help with mod compatibility for some smaller mods.

**Comment by BaerMitUmlaut** [comment]
You can just the delete the PBO for now. See also #7040
