### ISSUE TITLE
Ace3 on GeForce Now

### ISSUE THREAD

**Issue by geoduck112** [acemod/ACE3#8027]
There might have been many of reports related to the issue I'm having but just in case I want to report it anyway. Let me explain something first, GeForce Now is a cloud gaming service where people can play games such as Arma 3 at 60fps but sometimes it fails to do so. It doesn't give you full desktop access but only will give you the Arma 3 launcher and game but it still works good. Now to the main issue, I can load and update Ace3 just fine but when I launch the game, it will crash the session. This only happens with Ace3 which I need for a lot of mods I use.  I read online about due to how Ace changes the games settings and stuff GFN causes it to crash. You can feel free to test this out yourself as GeForce now is free but you can only use for 1 hour per session

**Comment by jonpas** [comment]
Most likely blocked because of extensions. Can you try removing all extensions (`.dll`) files from ACE3?

**Comment by PabstMirror** [comment]
This is from my testing a month ago
>just like they said it throws some kind of error, but I think it was before it goes full screen, so I think before preStart even
we don't do any extension stuff until preInit, so I don't think it's that

But I'm not sure. The session closes when there is a problem, so there is no RPT to check.
I sorta hacked open a file browser in the geforce session, but there doesn't seem to be any file system at all?

So the only way to try to figure out this problem is brute guess and test, 
and with a 15? minute queue time for me it really unfun to do.

If someone is willing to do the legwork, 
- start with a ace full release, 
- strip out the dlls and everything besides ace_main and ace_common.pbo, 
- upload it to steam WS and see if it will boot. 

Then re-add pbos and dlls, reupload and retest and retest until we find a failure point.

**Comment by geoduck112** [comment]
> Most likely blocked because of extensions. Can you try removing all extensions (`.dll`) files from ACE3?

The game launches but heading into eden editor and starting the scenario will cause the session to crash. Also GFN will doesn't exactly support access to files so I had to do the whole thing through CMD and hypothetically if the method did work i would have to do it over and over again whenever I start a new session

**Comment by PabstMirror** [comment]
Can you try another mod with extensions, like just CBA+ACRE (I'm not sure how acre will handle the TS install)

**Comment by geoduck112** [comment]
> This is from my testing a month ago
> 
> > just like they said it throws some kind of error, but I think it was before it goes full screen, so I think before preStart even
> > we don't do any extension stuff until preInit, so I don't think it's that
> 
> But I'm not sure. The session closes when there is a problem, so there is no RPT to check.
> I sorta hacked open a file browser in the geforce session, but there doesn't seem to be any file system at all?
> 
> So the only way to try to figure out this problem is brute guess and test,
> and with a 15? minute queue time for me it really unfun to do.
> 
> If someone is willing to do the legwork,
> 
> * start with a ace full release,
> * strip out the dlls and everything besides ace_main and ace_common.pbo,
> * upload it to steam WS and see if it will boot.
> 
> Then re-add pbos and dlls, reupload and retest and retest until we find a failure point.

I have founders so i can try taking out the dlls and pbos and testing it. If it works I will do the same on my main pc and upload the edited version to the workshop

**Comment by BaerMitUmlaut** [comment]
Unfortunately a some stuff might break if you just remove the DLLs (I don't think advanced ballistics works without extensions for example). But it would be great to know if they are the main cause of this problem.

**Comment by geoduck112** [comment]
just checked and there is no pbos 
![Arma 3 2020 11 30 - 16 21 22 02](https://user-images.githubusercontent.com/75275462/100667326-5c966280-3328-11eb-8ade-3b2eb4de43e1.png)

**Comment by geoduck112** [comment]
![Arma 3 2020 11 30 - 16 27 23 03](https://user-images.githubusercontent.com/75275462/100667780-f3631f00-3328-11eb-8415-e8c9e89b0603.png)
big problem, in order to delete the pbos i have to go through everything unless theres a shorter way through cmd. Though i can try doing it on my main pc

**Comment by Vdauphin** [comment]
I think the best solution is to subscribe to a cloud computing service like Shadow Tech since most Arma community use radio mod which require a Teamspeak local to Arma

**Comment by geoduck112** [comment]
I found the solution to the problem. I tried testing if i can get more disk space for arma mods by opening arma on a steam session instead of directly and it worked! I was able to load every cup mod and a lot more. Idk if steam sessions give more space or its the fact i downloaded DCS before going to arma but whatever. I decided to also check if ACE would work as well and once i launched the game, it also worked!

**Comment by geoduck112** [comment]
got my hopes up didnt work

**Comment by commy2** [comment]
There is nothing we can do about bugs in this service. Since it is a paid service, there will be a customer support. You should ask those people about your problem. They are paid to do that.

Close?

**Comment by jonpas** [comment]
Leave open (for now), we can at least track it in one issue.

Anf it's not a fully paid service if there are free tiers (which I assume nobody uses for Arma though).

**Comment by geoduck112** [comment]
Customer support wont help at all. I've asked about mods before and they just said, "Mods aren't supported" which doesn't stop anyone from using them. If I ask about ace they're just gonna give me some BS answer. I might get boosteroid instead, its customer support is way better thought the service is a bit more expensive

**Comment by commy2** [comment]
Well there you go. Mods are not supported. Nothing we can do.

I'm for closing this.

**Comment by geoduck112** [comment]
I think its time i closed this because the discussion is dead and nvidia just made it so that you cant get workshop mods in GFN. Thanks to anyone who tried to help

**Comment by commy2** [comment]
Did they change that today?

**Comment by geoduck112** [comment]
not today but i think 3 or 4 days ago.

**Comment by BaerMitUmlaut** [comment]
Wow that sucks. Oh well.

**Comment by commy2** [comment]
As I said, they never intended to. The bug was letting people download mods in the first place.  If I were renting my machines, I wouldn't want people to download unsecure software from Steam either.

**Comment by BaerMitUmlaut** [comment]
Please create a new issue with as much info as possible. An RPT would be very helpful.

**Comment by synapssex** [comment]
honestly just give it up,  all we can do is save for a good pc but nanner the youtube arma 3 remaster 115 mods all work with no issue. what I can  say from the time i have been playing arma 3 is that ACE is the only mod that crashes the game

**Comment by BaerMitUmlaut** [comment]
@synapssex We cannot analyze the problem without RPTs. Please read my last comment.

Locking because apparently reading is hard.
