### ISSUE TITLE
Ace map gestures are global even during briefing map, before starting the mission.

### ISSUE THREAD

**Issue by Italiandrache** [acemod/ACE3#8028]
**Mods:**
- **Arma 3:** `2.00`
- **CBA:** `3.15.2`
- **ACE3:** `3.13.5`

**Description:**
When displaying the map before a mission start, map gestures have global effect. This is very annoying -- and, in my opinion, of serious concern -- as in TvT missions it could ruin the planning completely.

**Steps to reproduce:**
Host a TvT mission with two players on different sides. If one player uses map gestures (whilst on a channel different than global), the other player will see them, even if on a different chat channel.

**Expected behavior:**
Its visibility should be treated the same way as markers'.

**Where did the issue occur?**
Dedicated Server.

**Comment by jonpas** [comment]
Did you look at the settings? There is one called "Briefing Mode".

**Comment by Italiandrache** [comment]
> Did you look at the settings? There is one called "Briefing Mode".

Mhm, I might have missed that. I'll try this evening and let you know.

**Comment by Italiandrache** [comment]
> Did you look at the settings? There is one called "Briefing Mode".

It was the option indeed, I'm closing the issue. Thank you!
