### ISSUE TITLE
Remove team management on dead bodies.

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#803]
Reminder

Also needed to fix: https://github.com/acemod/ACE3/issues/223

**Comment by esteldunedain** [comment]
@commy2, maybe don't do this. I'd create another shortcut for diagnosing dead patients

**Comment by Glowbal** [comment]
Maybe instead adjust it to allow team management for conscious units only?

**Comment by esteldunedain** [comment]
> Maybe instead adjust it to allow team management for conscious units only?

Yeah, that totally makes sense. +1 for that!
