### ISSUE TITLE
Advanced Throwing - Ways to disable pickup on specific throwables

### ISSUE THREAD

**Issue by Zman6258** [acemod/ACE3#8030]
While working on a recent mission, I came across an incredibly tiny issue that I doubt many people have run into - creating chemlights attached to a specific object that I don't want to be removable. I don't want to disable the ability to pick up attached grenades, as my players have made use of it in the past with IR strobes, but at the same time I don't want players being able to pick up and toss away a chemlight that's been spawned through `createVehicle` at mission start and `attachTo`'d a specific mission objective. I can also see potential usage for things like scripted flares or smoke grenades, ones which are created through mission logic that mission designers might not want players to touch, but don't want to attach them to anything at all. If there's already a way to do this, then it doesn't seem to be documented anywhere on the wiki, and I couldn't find anything that might have such effects browsing through Github here (though admittedly, I'm a mediocre scripter and may have missed something obvious).

**Comment by jonpas** [comment]
We could add an object variable for this.
