### ISSUE TITLE
A3 Medical menu not working

### ISSUE THREAD

**Issue by youmad122** [acemod/ACE3#8032]
**Mods (complete and add to the following information):**
CBA_A3
ace
bettIR
freestylescrashlandings
blastcore tracers A3 forfort edit
blascore tracers A3 forfort edit A3
task force radio
remove stamina
remove stamina A3

**Description:**
When on a dedicated server trying to interact with the A3 medical menu presents the progress bar but never goes up.

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. go into the server
2.  spawn with a friend
3. try to interact with them for example: give them a bandage or morphine.

**Expected behavior:**
the progress bar to fill up and for the action to be completed

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**Log Files:**
https://gist.github.com/youmad122/592a0e083acc3950ac05d5d9b52f5d7d

**Additional context:**
Seems to only happen on this server

**Comment by PabstMirror** [comment]
I think it's same as https://github.com/acemod/ACE3/issues/6661#issuecomment-437036652

**Comment by LinkIsGrim** [comment]
Stale, can't repro
