### ISSUE TITLE
Medical - Add option to disable cardiac arrest on Fatal Injuries

### ISSUE THREAD

**Issue by Salluci** [acemod/ACE3#8044]
**Is your enhancement related to a problem?**
With the rewrite, my unit has noticed that pretty much every time a player ends up unconscious, they're in cardiac arrest, due to how Fatal Injuries are handled. This essentially negates any chance of a player getting back up on their own, which used to be a common occurence previously.

**Solution you'd like:**
Add an option to the CBA Settings menu to disable Cardiac Arrest on Fatal Injuries, essentially adding an option to bring back the old "Prevent Instant Death" functionality without the revive timer.

**Alternatives you've considered:**
I've tried my hand at writing this on my own, but alas, SQF and I don't get along very well.

**Comment by BaerMitUmlaut** [comment]
So when you receive a tank round to the head you just shrug it off? Nope, not going to happen.

**Comment by kymckay** [comment]
I don't object for the reason above, I think if people want to play that way there's no reason to stop them.

However, there already is a setting for this - it sounds like you should just disable fatal injuries. The whole point of them is to kill the unit, putting them into cardiac arrest is the middle ground and disabling them is the equivalent of "prevent instant death".
