### ISSUE TITLE
AGM-65 Maverick Range

### ISSUE THREAD

**Issue by Diesel5187** [acemod/ACE3#8050]
**Is your enhancement related to a problem?**
Maverick missile self destructs and does not reach the target, if the distance to target is anything greater than approx 16km.

**Solution you'd like:**
I would like the Maverick to have a realistic range, to increase target standoff, and aircraft survivability.

**Alternatives you've considered:**
None, at this time.

**Additional context:**
I have done kills with the Rhea system at 27km+ with a network of RHS radars. You have to know where the target is and you can launch in the general direction and it will hit the target.

The Maverick was tracking the target even if I did not get an initial indication of it seeing the laser, it LOAL and began to track only to self detonate a few km before the target in the air.

UCAV Sentinel flying at 5000m, 20k view distance.

Thank you

**Comment by commy2** [comment]
#3594
