### ISSUE TITLE
Frame rate drops significantly with the RCO (PIP) scope attached on any gun

### ISSUE THREAD

**Issue by ghost** [acemod/ACE3#8052]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00` [steam, prof/perf branch]
- **CBA:** `3.15.1` [steam workshop]
- **ACE3:** `3.13.5` [steam workshop]

**Description:**
When using the RCO (PIP) scope, the frame rate drops significantly whilst the gun is not holstered.
When you holster the gun, the frame rate returns back to normal.

**Steps to reproduce:**

1. Create a new mission, spawn a Rifleman and change the scope to RCO (PIP).
2. Play the session and observe your frame rate with the gun holstered using software such as Afterburner.
3. Take the gun out and observe a significant drop in frame rate.

**Expected behavior:**
The frame rate should drop, if at all, by only a couple of frames.

**Where did the issue occur?**
- Singleplayer / Self-hosted multiplayer

**Log Files:**
- https://pastebin.com/GW8Yk4NE

**Additional context:**
- Although I am using the dev branch, I was able to recreate this issue in the stable branch.
- Others have been able to recreate this issue.

**Comment by commy2** [comment]
Yes, PIP has a computational cost. Where's the bug though?

**Comment by BritLieutenant** [comment]
PIP has a computational cost, yes. However I don't think it has a computational cost of 40+ FPS.
Furthermore, other PIP scopes don't repeat this behaviour. I get little to no FPS drop with other PIP scopes.

**Comment by commy2** [comment]
hmm

**Comment by dedmen** [comment]
Disabling pip also didn't help

commy2 <notifications@github.com> schrieb am Sa., 2. Jan. 2021, 19:39:

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Comment by LloydZastro** [comment]
why does pip scope in shooting games drop fps but a rearview mirror plus 2 side mirrors in dirt rally barely affect fps?
