### ISSUE TITLE
Stamina Calculator and Individualization

### ISSUE THREAD

**Issue by Mikejminer** [acemod/ACE3#8053]
### Do not post feature requests here!
So I'm trying to create very customized units for a sci fi mission series. However, Given its sci fi setting, I'm trying to alter various aspects of the units. Units include Robots, Bio engineered soldiers, Generic infantry, Power armor, and Super soldiers. I would very much like to individualize them, starting with stamina. For example, a Robot has stamina outright disabled, Where the Infantry has typical stamina, the power trooper is significantly faster and can carry more gear, and the super soldier is well beyond superhuman endurance. What I am proposing is simple. First is the stamia calculator, this tells you how long you can sprint for, walk for, test times, etc based on your current loadout. Next would be a bit more optional. A way to individualize aspects of ACE on a per unit basis. For example, the "robot" unit can still suffer injuries same as a person, but it doesn't bleed out or feel pain. Overall this is a meh idea and i'm open for alterations.

Learn how to make a feature request [here](https://ace3mod.com/wiki/user/how-to-make-a-feature-request.html).

**Comment by BaerMitUmlaut** [comment]
Stamina depends on a lot of factors such as terrain and loadout weight. This cannot easily be calculated.

This is also not the place to post ideas.
