### ISSUE TITLE
Config Help

### ISSUE THREAD

**Issue by Melrian** [acemod/ACE3#8056]
So, this is less of an issue, and more of a request for clarification.  From what I understand, in the server settings, the ACE Weather function causes the weather to change automatically based on humidity, heat, etc.  It also has a windage function which does affect ACE Ballistics that is able to be checked separately from the weather option.  Would unchecking Weather but keeping Windage checked stop the autonomous weather updates whilst preserving the wind's effect on ballistics?  If not, is there a way to accomplish this?

**Comment by BrettMayson** [comment]
You should join the ACE slack or post in [the discussions](https://github.com/acemod/ACE3/discussions) rather than create an issue
