### ISSUE TITLE
Add a global version definitions for SQF, hpp and C++ across the board for usage

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#806]
@ViperMaul @KoffeinFlummi 

Currently I'm not sure how make.py gets its versioning info or where it writes it, but we need the following:

- [ ] a global VERSION.txt in the root of the project for fetching full version (3.0.1)
- [x] Use git revision for build 
- [ ] Definitions in .hpp land in the addon to utilize for versioning with definitions for
    - [ ] ACE_FULL_VERSION {3.0.1-asdf1233}
    - [ ] ACE_VERSION {3.0.1}
- [x] Version in the cmake build infastructure to read the file and use correct versions
- [ ] The extension loading framework needs to check extension build/versions to match.

**Comment by ViperMaul** [comment]
@jaynus,
```python
commit_id = subprocess.check_output(["git", "rev-parse", "HEAD"])
commit_id = str(commit_id, "utf-8")[:8]
key_name = str(key_name+"-"+commit_id)
```

The result is config.cpp is updated at build time to look like the following from CfgPatches
version = "3.0.0.1-0c6786a1";
versionStr = "3.0.0.1-0c6786a1";

**Comment by jaynus** [comment]
Where does key_name come from that its 3.0.0.1?

**Comment by ViperMaul** [comment]
@jaynus,
key_name initially comes from make.cfg and if that file is missing the default currently is from a line that will be added to make.py in the ### globals ### section
key_name = "ace_preAlpha"

**Now your next question is a loaded one...**
The short answer is 3.0.0.1 is already there in the config.cpp source files of the example I used which is ace_common\config.cpp

But to trace the main source you have walk down the macro definition rabbit hole. 
You've done this before in your sleep I know? But for anyone who hasn't, here we go... 

Starting with ace3 commons config.cpp...
- https://github.com/acemod/ACE3/blob/master/addons/common/config.cpp#L11
- We see this VERSION_CONFIG that we need to find the definition for. So we look at the include statements
- https://github.com/acemod/ACE3/blob/master/addons/common/script_component.hpp
- https://github.com/acemod/ACE3/blob/master/addons/main/script_mod.hpp#L6-L12
- It is is in this main/script_mod where you see in lines 6-9 where the numbers 3 0 0 1 comes from
- #define VERSION MAJOR.MINOR.PATCHLVL.BUILD
- #define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD
- https://github.com/acemod/ACE3/blob/master/addons/common/script_component.hpp#L14
- https://github.com/acemod/ACE3/blob/master/addons/main/script_macros.hpp#L1
- https://dev.withsix.com/projects/cba-a3/repository/revisions/develop/entry/addons/main/script_macros_common.hpp#L62

So we end up with our final answer pointing to Line 62-64 

```
#ifndef VERSION_CONFIG
   #define VERSION_CONFIG version = VERSION; \ 
                versionStr = QUOTE(VERSION);  \
                versionAr[] = {VERSION_AR}
#endif

**Comment by jaynus** [comment]
We may want to import the solution in ACRE; this provides a VERSION file in which all versions are read and derived from. I'll see if it's worth the time.

**Comment by bux578** [comment]
3.0.0 or 3.1.0?

**Comment by jaynus** [comment]
Backlog, this is an ongoing build integration item

**Comment by bux578** [comment]
Can we close this?

**Comment by Glowbal** [comment]
This doesn't seem to be necessary anymore.
