### ISSUE TITLE
Wrong latest version in main menu and on the website

### ISSUE THREAD

**Issue by krieghof** [acemod/ACE3#8068]
**Mods:**
- Arma 3: 2.00.146773
- CBA: 3.15.2 (Workshop)
- ACE3: 3.13.5 (Workshop)

**Description:**
In the main menu - bottom right corner - the latest version is wrong

**Steps to reproduce:**
1. Launch Arma 3 with ace3
2. Check the version in the bottom right corner

**Expected behavior:**
Show the correct version. 

**Log Files:**
https://pastebin.com/yGG5Xgzw

**Additional context:**
The "Get ACE3" button on https://ace3mod.com/ also shows the wrong version.

**Screenshots:**
![main_menu](https://user-images.githubusercontent.com/17674464/104551660-994bbe00-5637-11eb-8b04-f9a95258f15a.jpg)

**Comment by bux** [comment]
Closed in #8069 

Thanks for the report
