### ISSUE TITLE
Advanced throwing doesn't work while holding a Launcher

### ISSUE THREAD

**Issue by krieghof** [acemod/ACE3#8072]
Mods:
- Arma 3: 2.00.146773
- CBA: 3.15.2 (Workshop)
- ACE3: 3.13.5 (Workshop)

Description:
While holding some kind of Launcher for example the "Titan MPRL Compact", Shift+G is not working. The grenade just gets thrown like I pressed G.

**Steps to reproduce:**
1. Take "Titan MPRL Compact" in the hand with "3".
2. Try to throw a grenade with SHIFT+G.

**Expected behavior:**
The Advanced Throwing UI gets shown.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) 
-  But I think everywhere

**Log Files:**
https://pastebin.com/PBQTZ35b

**Video:**
https://youtu.be/KeE7gn02eCs

**Comment by jonpas** [comment]
That is intentional, holding a launcher and throwing grenades is not feasible.

The reason you do a normal throw is because you have vanilla throwing bound to the same key, just unbind it or bind it to something else.

**Comment by krieghof** [comment]
If it is intentional, I suggest SHIFT+G should do nothing or maybe show a hint that advanced throwing is not available. 

Right now the grenade just gets thrown and this can lead to really dangerous situations when the player is not awaire of that behavior.
I didn't knew it and I nearly killed 3 of my own people.

**Comment by commy2** [comment]
Rebind your throw key.

**Comment by jonpas** [comment]
Advanced Throwing does not activate, you most likely have your **vanilla"" throwing on the same key, rebind it.

**Comment by krieghof** [comment]
Thanks rebinding the key does indeed work.
