### ISSUE TITLE
Frag caused by unexploded 40 mm projectile

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#8073]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00`
- **CBA:** `3.15.2`
- **ACE3:** `3.13.5`

**Description:**
When shooting a 40 mm grenade at the ground at a distance near the minimum grenade activation distance, shrapnel will be spawned once the projectile despawns.

**Steps to reproduce:**

1. Shoot a grenade at the ground roughly 10-15 m away from you (as far as possible without it exploding)
2. Wait for the projectile to despawn
3. Get hit by frag

**Expected behavior:**
No shrapnel should be spawned.

**Where did the issue occur?**
- Editor (Singleplayer)

**Comment by Lairdd1989** [comment]
I have experienced this issue to in Multiplayer.

I think it occurs when the projectile - before despawn - drops to the terrain causing the projectile to reach its activation distance thus detonating the 40 mm.

**Steps to reproduce:**
1. Shoot a grenade at a tall wall or building several meters above the ground 10-15 m away from you (as far as possible without it exploding) 
2. The projectile will be stuck in the wall a few seconds then drop to the terrain detonating the 40 mm

**Comment by BaerMitUmlaut** [comment]
To clarify: There's no detonation sound or particle effect. If the round actually explodes with its effects, then shrapnel _should_ spawn.

**Comment by Salluci** [comment]
Caused by [frag_fnc_pfhRound](https://github.com/acemod/ACE3/blob/baff363915c176566b6d676322b67581cbdb448c/addons/frag/functions/fnc_pfhRound.sqf) checking for `!alive _round` for frag effects.
