### ISSUE TITLE
The ACE3 medical system makes the some of vests are not pierced through

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#8075]
- **Arma 3:** `2.00` [stable]
- **CBA:** `3` [stable, last version, Steam subscribe]
- **ACE3:** `3.13.5` [stable]
- **A3 Thermal Improvement** 
- **Bullet Casing** 
- **Tactical Position Ready** 
- **Magazine Simulation A3** 

**Description:**

If I disable all ACE3 medical files then the problem goes away.

The ACE3 medical system makes the some of vests are not pierced through.
Thus, soldiers in such vests cannot be killed through the vest! 
I have not tested every vest, but as far as I understand, **only heavy vests** have a problem (Please check all vests!)
I did not overlay the text on the video, but you can understand - the first part of the video, when it takes 3 hits to kill a soldier, without ACE3 medicine, the second part of the video with ACE3 medicine and how you can see the soldier cannot be killed!

[Video Example Here](https://youtu.be/dqgmvR9-RmY)

**Steps to reproduce:**

Place in the VA player with heavy vest (from my description) and shoot AI.
Those vests are tested and causes problem:

Carrier GL Rig (all colours) (NATO)
Carrier Special Rig (all colours) (NATO)
GA Carrier GL Rig (all colours) (AAF)

**Expected behavior:**
Heavy vests definitely have to withstand more hits, yes, but they shouldn't make the soldier immortal. I think that they should not withstand 20 or more bullet hits, even if they are 5.45 bullets. The soldier must be fatally injured and die.

A separate but closely related topic:

It would be great to make a random indicator for killing a soldier if the bullet hit the vest. The vanilla game uses stable 3 hits as we can see. If ACE3 could create a random number of death-inflicting hits, that would be great! For example, if death occurs between a 8-15 hits into a heavy vest, that would be great. Please try think about!

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by Dudejo** [comment]
That's because the current system only allows Large wounds to matter.
