### ISSUE TITLE
 Static Titan AT still can't guidance to enemy

### ISSUE THREAD

**Issue by Arkblade2015** [acemod/ACE3#808]
Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
ace_javelin
ace_missileguidance

Description:
Static Titan AT missile still can't guidance to enemy.
missiles are gone to somewhere when lock on and fire.
i using latest build from master.

Steps to reproduce:
https://www.youtube.com/watch?v=T9ufoY1ep_c

Where did the issue occur?
"Singleplayer"*

**Comment by jaynus** [comment]
What latest build? Is AMG enabled in the ACE Settings menu? 

I just re-tested, again, with all 3 launcher types:

https://www.youtube.com/watch?v=G7QKO_ghXLw&feature=youtu.be

I also retested with static being placed with unit, as per your video, and it also works.

**Comment by Arkblade2015** [comment]
both yes.
i check when AMG disabled, it made missiles fly straight and unguided.

**Comment by jaynus** [comment]
Reproduced. Sorry about that.

**Comment by jaynus** [comment]
This was caused by difficulty targetting and the use of ACE_player vs. vehicles.
