### ISSUE TITLE
How to find which Addon/-s require a certain one ?

### ISSUE THREAD

**Issue by irvnriir** [acemod/ACE3#8080]
Each Mission launch, i get "No entry <<..>> .ace_ai'." message, how to find in the dozens of .pbo-s, which one/-s is requiring it ?

I didn't find the answer on the Wiki , so if its possible it should be added there . I'll highly appreciate help in solving the issue .

**Comment by commy2** [comment]
?

**Comment by irvnriir** [comment]
@commy2 `No entry <<..>> cfgPathes.ace_ai`

**Comment by PabstMirror** [comment]
our wiki will show requirements: 
e.g. https://ace3mod.com/wiki/feature/zeus.html requires ai

you can also run this code to get full list (including external mods)
```
{ 
    private _reqAddons = getArray (_x >> "requiredAddons"); 
    if (_reqAddons findIf {_x == "ace_ai"} != -1) then { 
        systemChat format ["R %1 - %2", configName _x, _reqAddons]; 
    }; 
} forEach ("true" configClasses (configfile >> "CfgPatches"))
```
ace_zeus - ["ace_common","ace_ai"]
ace_zeus_captives - ["ace_common","ace_ai"] //most of these are submodules inside ace_zeus.pbo
ace_zeus_medical - ["ace_common","ace_ai"]
ace_zeus_cargo - ["ace_common","ace_ai"]
ace_zeus_repair - ["ace_common","ace_ai"]
ace_zeus_cargoAndRepair - ["ace_common","ace_ai"]
ace_zeus_fastroping - ["ace_common","ace_ai"]
ace_zeus_pylons - ["ace_common","ace_ai"]
ace_zeus_arsenal - ["ace_common","ace_ai"]

**Comment by irvnriir** [comment]
The way on wiki require to check every page, so is not basically different from examining .pbo-s .

The code is what i was looking for, thanks .
Why ace_zeus requires it ?, doesn't seem that any of the Zeus AI functions are available outside of it .

**Comment by PabstMirror** [comment]
imho this is a fair point
ace_zeus_fnc_moduleGarrison uses EFUNC(ai,garrison);

but fastrope, cargo, captives, repair all just do something like
```
if !(["ace_cargo"] call EFUNC(common,isModLoaded) && ["ace_repair"] call EFUNC(common,isModLoaded)) then {
    [LSTRING(RequiresAddon)] call FUNC(showMessage);
```
so they don't have a hard requirement

**Comment by jonpas** [comment]
> The way on wiki require to check every page, so is not basically different from examining .pbo-s .

The goal was to also have all dependencies on a separate page, with an overview of everything, as in tree structures, but I never got around to that and probably won't.

**Comment by kymckay** [comment]
>imho this is a fair point
>ace_zeus_fnc_moduleGarrison uses EFUNC(ai,garrison);
>
>but fastrope, cargo, captives, repair all just do something like

To be honest, we may have structured our zeus models the wrong way round to begin with. It may have made more sense to make ace_zeus a more central component and have these other addons use the common module code from it as a hard dependency (since it's features can all be disabled in-game anyway).

**Comment by jonpas** [comment]
Yeah I can see that. It was after all a huge afterthought because Zeus didn't exist before.
