### ISSUE TITLE
ace_zeus_autoAddObjects ignores many

### ISSUE THREAD

**Issue by irvnriir** [acemod/ACE3#8082]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `last` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `last` [eg. 3.0.0 stable, commit hash]

**Description:**
example spawn :
 ```
_posASL = [12850.4,6707.37,59.5125];
_object0 = createVehicle ["Land_WoodenCrate_01_F", [0, 0, 0], [], 0, "CAN_COLLIDE"];
_object0 setVectorDirAndUp [[-0.0663712,-0.975955,-0.207623],[0.0844467,-0.21283,0.973433]];
_object0 setPosASL _posASL;
```
;

I use the function to workaround that loading from Zeus Enhanced 's Export Mission SQF doesn't add the assets to Zeus .
It also would be good to remove the adding of environmental entities, they obstruct the view with no use .

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
