### ISSUE TITLE
(RHSUSAF Compat) - AN/PEQ-15 and -16 do not have visible laser modes.

### ISSUE THREAD

**Issue by ajwubbin** [acemod/ACE3#8086]
Pretty much what's said in the title. In real life, both of these laser modules have visible laser, IR laser, and IR illuminator modes. Not having IR illumination is understandable, as this is a feature simply not included in the mod, but ACE has the ability for visible laserpointers, is there a reason there aren't any on the RHS modules?

**Comment by dedmen** [comment]
The reason mostly being that visible laser modules are actually seperate items with seperate classnames.
Not sure what the implications are with implementing new items in a compat, there might be issues with that.
But feel free to make a PR

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
