### ISSUE TITLE
non-fading Stamina Bar disappears upon player respawn

### ISSUE THREAD

**Issue by atlas1205** [acemod/ACE3#8094]
Upon respawn in MP, tested with code:
_staminaBarContainer = uiNamespace getVariable ["ace_advanced_fatigue_staminabarcontainer", controlNull]; 
            ctrlFade _staminaBarContainer;

Always returns 1 so the bar remains perpetually hidden. With auto-fade on, the value decreases properly.

Fix suggestion: detect if the player is using non-fading stamina bar. If yes, then (bar ctrl) ctrlSetFade 0 upon MPRespawn event.

**Comment by BaerMitUmlaut** [comment]
Please fill out the issue template.
