### ISSUE TITLE
ACE PBO Checker

### ISSUE THREAD

**Issue by Lufian12345** [acemod/ACE3#8096]
saying "emr.main." is not on the server, but not" emr.main.pbo"

**Comment by BaerMitUmlaut** [comment]
I have no idea what you're trying to say. Fill out the issue template and try again.

**Comment by PabstMirror** [comment]
Enhanced Movement Rework  is not part of ace
Sounds like you have the checkPBOsCheckAll setting enabled

either disable that setting
or install the mod on the server as well

**Comment by Lufian12345** [comment]
Yeah I know Enhance Movement Rework isn't part of ace, the issue is I already have the mod installed on the server and installed on my side. But it is still saying that I am missing the mod.

**Comment by Lufian12345** [comment]
22:57:14 [ACE] billy: ERROR server missing addon(s): emr_main. 
this is what comes up on the web console on my server
