### ISSUE TITLE
RHS AFRF  :   Vest to much armor

### ISSUE THREAD

**Issue by bobzap** [acemod/ACE3#8101]
Hi every body,

The problem : all ia who wear the 6B23 vest need to more than 20 bullets in 5.56mmIt is normal or there is a patch or anything else ?

When i use RHS without ace everything work properly, but with ace i have this problem...

**Steps To Reproduce |** 
Ace arsenal
Wear "6B23 summer" vest for exemple  
Test and compare with differents weapons and munitions : 5.56 , 7.62 ...

**Mods Use :** 
_Ace
Cba3
RHSAFRF
Ace Compat RHSAFRF_
All my mods are updated..

Thank you in advance ! =))

**Comment by Goldwep** [comment]
The new armors that were just added also have this problem. over 60 rounds from a 240B to kill Opfors new 6b45 vests. Needs to be fixed in the Compatibility mod

**Comment by commy2** [comment]
See #8274 for a reason for this be closed.
