### ISSUE TITLE
When using Ammo vic to rearm, display indicates 8X is being re-armed when only 1 rocket is armed per re-arm cycle.

### ISSUE THREAD

**Issue by Kavlar** [acemod/ACE3#8107]
Re-Arming 2S6M Tunguska AAA

**Steps To Repro:**

1. Expend all rockets
2. Attempt re-arm of rockets

Ammo box states X8 rockets are contained in the re-supply box, yet only 1 rocket is loaded per cycle.

**Mods:**

ACE3 - 3.13.5
3CB - 4.0.0

**ARMA 3 Ver.**

Latest ARMA 3 version on Steam

**Notes:**

Raised on 3CB here - https://steamcommunity.com/workshop/filedetails/discussion/1673456286/4939856028570199051/

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
