### ISSUE TITLE
prohibit wheel removal  when the enemy is in the vehicle 

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#8108]
many players trade in this. remove the wheels when the enemy is in the vehicle and force the AI to leave it. can you make a check, if the enemy is in the vehicle, then do not give the opportunity to unscrew the wheel?

**Comment by topden** [comment]
I asked something forbidden? Why did you close the ticket without an answer?

**Comment by jonpas** [comment]
Fill out the template.
