### ISSUE TITLE
prohibit wheel removal when the enemy is in the vehicle (request)

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#8113]
**Is your enhancement related to a problem?**
-no bug

**Solution you'd like:**
many players trade in this. remove the wheels when the enemy is in the vehicle and force the AI to leave it. 

**Alternatives you've considered:**
can you make a verification in scripts , if the enemy is in the vehicle, then do not  open the wheel removal menu ?

**Additional context:**
http://joxi.ru/8AnbE8qTyG1ebA

**Comment by Fernir2000** [comment]
I would say that removing wheels from enemy crewed vehicles should be possible as theoretically you could at least unscrew wheels from a vehicle without alerting the crew.
