### ISSUE TITLE
Red Circle when i press Self interaction Key.

### ISSUE THREAD

**Issue by NeonS0** [acemod/ACE3#8114]
Arma 3 Version: 1.56.134787
CBA Version: 3.15.1
ACE3 Version: 3.13.5

Mods:

CBA_A3
ace

Description:
I get a Red Circle When i Press my the Interact key and its only for the Self interaction, I can use it on cars and AI, I have tried a lot of things they have not worked.

Where did the issue occur?
Editor only.

RPT log file:

https://pastebin.com/T4RWmFwc

**Comment by commy2** [comment]
Rebind it.

**Comment by NeonS0** [comment]
I tried that and it did not Work.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
