### ISSUE TITLE
incorrect description of actions with the canister 

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#8115]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00.146.773` [stable]
- **CBA:** `3.15.2.201119` [stable]
- **ACE3:** `3.13.5` [stable]

**Description:**
1. the description of actions with the "canister" is the same as the description of actions with the "ace_refuel_fuelNozzle"
2.  can you make the canister change to empty after filling? 

**Steps to reproduce:**
go to the editor and fill the car with a canister 

**Expected behavior:**
it would be nice to make a separate description for the actions for the canister 

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
no

**Additional context:**
no

**Screenshots:**
http://joxi.ru/RmzoE6ZHMNd7D2

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
