### ISSUE TITLE
Ace conflicting with Zeus Enhanced even with the Ace/Zen Compat Mod, (Singleplayer Editor)

### ISSUE THREAD

**Issue by Aitoheiwa** [acemod/ACE3#8120]
After spawning Zeus Interface In Eden Editor and spawning into a character, I recieve an error of a line of code which prevents my Zeus from popping up (Hotkey for me is Y), only way for me to fix this is disabling ACE and it's compat patch. 
![Capture](https://user-images.githubusercontent.com/79400263/108621679-079c5100-742c-11eb-9e73-df697d86dddf.PNG)

**Comment by mharis001** [comment]
Can't reproduce and don't think this is an ACE issue. Also, needs RPT to investigate further.
