### ISSUE TITLE
Medical action should be disallowed on vehicles crews if current player is outside the vehicle.

### ISSUE THREAD

**Issue by GoldJohnKing** [acemod/ACE3#8121]
**Is your enhancement related to a problem?**
Medical action on vehicle crews, for example, morphine, is currently allowed for players outside vehicles. This allow players inject morphine to vehicle crews (especially enemy units) inside vehicles and kill them due to overdose. This really destroy immersion.

**Solution you'd like:**
Medical action should be disallowed on vehicles crews if current player is outside the vehicle, which means, players outside the vehicle can not open medical action menu of vehicle crews.

**Alternatives you've considered:**
Let server admin choose if to enable above feature in CBA settings, for example:
Allow medical action on vehicle crews when player is outside vehicle:
- Allowed
- Friendly units only (include civilian)
- Friendly units only (exclude civilian)
- Disallowed

**Additional context:**
Please notice that friendly units includes both
- Units on player side
- Units on sides which are friendly to player side

**Comment by rautamiekka** [comment]
The alternative is the only way to go.

When I saw the title I thought the better way for a hardcoded prevention would be tanks and planes since getting to the victim will be next to impossible without at least the driver getting out in at least some tanks.

**Comment by Nerexis** [comment]
Confirmed on my server ACE3 3.13.6 version.
