### ISSUE TITLE
APR and Rebreather overlays are upside down

### ISSUE THREAD

**Issue by ASO-TheM** [acemod/ACE3#8127]
**Mods (complete and add to the following information): no other mods**
- **Arma 3:** `2.02` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.2.201119` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.5` [eg. 3.0.0 stable, commit hash]

**Description:**
APR and Rebreather overlays are upside down

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. _Go to the Arsenal
2. _Select either the APR or Rebreather
3. _See the inverted HUD

**Expected behavior:**
The Overlay should be right side up

**Where did the issue occur?**
-  Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
Not sure if a log is necessary

**Additional context:**

**Screenshots:**
![20210223184848_1](https://user-images.githubusercontent.com/32593804/108886444-450a0580-7609-11eb-96c8-2da63cddbbe2.jpg)

**Comment by Salluci** [comment]
BI issue. Overlays are pulled from Enoch files. [https://github.com/acemod/ACE3/blob/master/addons/goggles/config.cpp](url)

Lines 233-245: `class G_AirPurifyingRespirator_01_base_F: None {
        ACE_Overlay = "a3\ui_f_enoch\data\objects\data\optics_apr_ca.paa";
        ACE_OverlayCracked = "";
        ACE_Resistance = 2;
        ACE_Protection = 1;
    };
    class G_AirPurifyingRespirator_02_base_F: G_AirPurifyingRespirator_01_base_F {
        ACE_Overlay = "a3\ui_f_enoch\data\objects\data\optics_APR_02_CA.paa";
    };
    class G_RegulatorMask_base_F: None {
        ACE_Overlay = "a3\ui_f_enoch\data\objects\data\optics_regulator_ca.paa";
    };`
