### ISSUE TITLE
ACE Movement Can't climb

### ISSUE THREAD

**Issue by Kartaviy** [acemod/ACE3#8144]
**Mods (complete and add to the following information):**
- **Arma 3:** `actual`
- **CBA:** `actual`
- **ACE3:** `actual`

**Description:**
ace_movement does not work correctly. I cannot climb the simplest obstacles

**Where did the issue occur?**
- everywhere

**Screenshots:**
Toy can see my video - https://youtu.be/hgZxv1xijTQ

**Comment by Drofseh** [comment]
Please fill out the template properly.

**Comment by BaerMitUmlaut** [comment]
Climbing walls is not possible with ACE.
