### ISSUE TITLE
Switch off sighting in prone pose

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#8148]
Make a button in the settings that would disable the ability to use the sights from [this unit's pose](https://cdn.discordapp.com/attachments/189399686766002176/817386182702399528/a1a74c1b27a29128.jpg).
In the game there is no ballistic suitable for the rifle being tilted.

**Comment by commy2** [comment]
It is not possible to make this a "button", because disabling the weapon in that animation is a config entry that cannot be changed with effect while the game is running.

**Comment by kymckay** [comment]
Closing as per above

**Comment by GalNa** [comment]
> 
> 
> It is not possible to make this a "button", because disabling the weapon in that animation is a config entry that cannot be changed with effect while the game is running.

In any case, make an option that would return this pose as it is on vanilla. It doesn't matter if it's a setting or even a separate compatibility addon.  In vanilla arma, there is no way to aim from this position. And it looks like cheating or buggusing.
