### ISSUE TITLE
Make.py should create signature keys by default. 

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#815]
- [x] Create signature keys by default. 
- [x] append the SHA-1 number to the signature key
- [x] Check for missing keys and rebuild them. 
- [x] if a new private key is created then remove all old signature key files.
- [x] Make sure Optionals get signed too.

**Comment by jaynus** [comment]
I'd really like to just have a new private key per build or at least minor version automatically. We should have per build right now

**Comment by ViperMaul** [comment]
@jaynus, because we will append the SHA-1 number to the signature key that will already happen.

**Comment by Glowbal** [comment]
Optionals should probably be signed seperatly.

**Comment by jaynus** [comment]
Server needs the root key tho :p
