### ISSUE TITLE
Incorrect reopening chance due to unnecessary line in code

### ISSUE THREAD

**Issue by MivinaTraktor** [acemod/ACE3#8155]
Minor cuts have a higher reopening chance (0.3) than medium and large (0.2) due to an unnecessary line in code

**Comment by commy2** [comment]
Which line?

**Comment by MivinaTraktor** [comment]
https://github.com/acemod/ACE3/blob/master/addons/medical_treatment/ACE_Medical_Treatment.hpp
line 496

**Comment by Drofseh** [comment]
https://github.com/acemod/ACE3/blob/dcfb5aa22415c30866cb7067efe21659bac561ce/addons/medical_treatment/ACE_Medical_Treatment.hpp#L491-L497

**Comment by MivinaTraktor** [comment]
497 then, it's overwriting the original class which has 0.2 reopening chance
