### ISSUE TITLE
Error when starting Arma Server using Latest Workshop Version

### ISSUE THREAD

**Issue by kieranirving** [acemod/ACE3#8159]
When starting an ArmA server using the latest version of the CBA_A3 from the workshop, the server will throw the error "cba common requires addon a3_data_f_aow_loadorder" and prevent the server from starting correctly.
This was tested with two different modlists, with the latest version of 233780 -beta.

**Comment by PabstMirror** [comment]
cba issue here: https://github.com/CBATeam/CBA_A3/issues/1435
