### ISSUE TITLE
Make.py Key folder should be inside the release\@ace project folder

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#816]
- [x] Key folder containing the Public Key should be inside the release\@ace project folder not outside. 
- [x] The private key is currently created in the same directory as the Addon's folder. This should be changed to somewhere outside the repo area. My current thinking is in folder called Private_Keys in the root directory of the work_drive, by default this would mean P:\Private_Keys
- [x] Update Make.cfg to allow changing P:\Private_keys to a location of the users choosing.

**Comment by lukrop** [comment]
Why? I think that would only provoke that someday, somewhere a private key ends up in a repository.

**Comment by bux578** [comment]
It already is ...
https://github.com/acemod/ACE3/blob/master/.gitignore#L1

**Comment by ViperMaul** [comment]
@lukrop, 
This never meant Private Key. 
The release directory is meant to be immediately archived for distribution. And we would never intend on distributing the private key. And as bux already noted the release directory is already excluded from ever being committed into any 

I will update the first post to be clear.
