### ISSUE TITLE
Make reload times for launchers favor assisted ACE/reloadlaunchers

### ISSUE THREAD

**Issue by brainslush** [acemod/ACE3#817]
You got this nice module ACE/reloadlaunchers. To actually get people to use this why not make the reload times longer when one reloads the launcher on his own than the assistant reloads the tube.

**Comment by esteldunedain** [comment]
No, I don't think so. We'd have to slow all the animations and they'd probably look bad. I think that what we can do is reduce the time it takes for the assisted reload instead. There's a technical problem there (a BIS command not working well enough), but I think it can be worked around.

**Comment by Dobakjang** [comment]
Or making new reload animation if could

I highly recomend to watch operation flashpoint red reiver to see how the launcher loaded

If custom reload animations are implented.

**Comment by esteldunedain** [comment]
> Or making new reload animation if could

It's not possible

**Comment by Dobakjang** [comment]
is it not possible cause no ppl to do that or the code reason? seems like RHS did some custom animation for rpg

**Comment by esteldunedain** [comment]
> is it not possible cause no ppl to do that or the code reason? seems like RHS did some custom animation for rpg

AFAIK the animation is defined along the weapon, so only the original authors of each weapon can do that (legally).

**Comment by Glowbal** [comment]
Closing. See @esteldunedain comment
