### ISSUE TITLE
7.62x39mm does not produce enough heat

### ISSUE THREAD

**Issue by VallisS** [acemod/ACE3#8173]
Guns that use this round (7.62x39mm) do not overheat nearly as much as they realistically should. For example, if you shoot a rifle that fires 5.56x45mm in full auto, after 2-3 mags the rifle will heat up far more than a weapon firing 7.62x39mm (i.e AKM, AK-12, etc).

I'm not sure if this is intentional, but this seems very backwards to me.

**Comment by BaerMitUmlaut** [comment]
I read out the internal values and compared the vanilla HK416 and the vanilla AKM and AK-15 (using ACE Realistic Names). Both AKs got considerably warmer (up to 25%!) than the HK416 after dumping one magazine.
