### ISSUE TITLE
A-10D Thunderbolt II - Ballistics/UI - Gunsight misaligned

### ISSUE THREAD

**Issue by Raykage** [acemod/ACE3#8178]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.02 Stable` 
- **CBA:** `3.15.3` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.6`

**Description:**
The A10-D/A-164 Wipeout Gunsight is either misaligned or does not correctly calculate ballistics. Shots go higher than where the gunsight is placed. 

This issue is particularly pronounced at low speeds, low dive-angles and/or large distances (>2km) to target. It is even more apparent when using the targeting pod to aim the gun centre on the target. 

**Steps to reproduce:**
1. Create new mission in Eden; Place A-10D at 2,000m height and a target (e.g. Kamaz) on ground. Move A-10D 5-6km out from target.
2. Start mission, navigate A-10D to target.
3. At 3,500 meter from target place gunsight on target and start a straight dive for it, this should result in an optimal dive angle of 30°. 
4. With the target fixed start shooting the gun. 
5. Notice how the impacts are higher than the reticule, particularly when further away that the ideal range of 1,200 km (4,000 feet) slant range. 
6. Repeat steps 1-4 but idle throttle and deploy speed brakes when starting the dive, aiming for ~350km/h. Notice how bullets hit even higher than before. 
7. Repeat steps 1-4, but this time aim for a shallower dive angle, e.g. 10°. Notice how bullets high significantly higher than where the gunsight indicates. 

Optional step 8: Repeat steps 1-4, aiming for top speed. Notice how bullets high much closer to target. 

**Expected behavior:**
The gunsight should correctly indicate where bullets will hit, even when outside of the ideal range/dive angle. 

**Where did the issue occur?**
Verified in Editor (Singleplayer), but also confirmed on Multiplayer. 

**Log Files:**
N/A

**Additional context:**
N/A

**Screenshots:**
![Gau-8_misaligned_lowdive](https://user-images.githubusercontent.com/69323673/111871544-a44a0400-8982-11eb-954e-2c06e14cae92.jpg)
![Gau-8_misaligned_1](https://user-images.githubusercontent.com/69323673/111871545-a4e29a80-8982-11eb-8854-565cee769c07.jpg)
![Gau-8_misaligned_3](https://user-images.githubusercontent.com/69323673/111871553-b3c94d00-8982-11eb-85c0-defaa276d1a2.png)
![Gau-8_misaligned_2](https://user-images.githubusercontent.com/69323673/111871555-b461e380-8982-11eb-80f2-99ecc017e585.png)

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
