### ISSUE TITLE
Get in interaction works from too far away, lets players take any seat

### ISSUE THREAD

**Issue by MivinaTraktor** [acemod/ACE3#8179]
**Description:**
Ace Interact Get in option allows players to get inside the vehicle from too far away, wherever the Interact is visible. It also lets them take any free seat (driver, pilot, gunner, etc.), even if you have to be at a specific place to occupy them.

**Steps to reproduce:**
1. Stand under the tail of any helicopter. As far as possible, while still seeing ace interact option.
2. Navigate to Interact -> Get in -> any seat
3. Teleport

**Expected behavior:**
Get in working only near entrances and only for available seats. I.e. you should be at the driver's door to get in as a driver. It should inherit vanilla scroll menu logic.

**Comment by Sienihemmo** [comment]
I always thought of the ACE function as a backup in case the proper entrypoint cant be accessed, for example if the driver side door ends up pressed against a wall. Because realistically with most vehicles you'd be able to get inside through any entrypoint and clamber through the vehicle to get to the proper seat.

If it was limited to only work when you're near the correct entrypoint, then why not just use the vanilla one? It is a lot faster after all, especially if the vehicle has lots of seats.

**Comment by rautamiekka** [comment]
Amen to all of @Sienihemmo's, the feature is a mandatory one until the game fixes the problem.

**Comment by MivinaTraktor** [comment]
Well, I don't think that looking at a heli's tail, opening ACE interaction and getting in a pilot seat is fine. Also, there is already a function to change seats when you're inside. You don't exactly go through all the "clambering through" process when using this function, you immediately jump into it in zero time and thought process. I think the entrypoints were added for a reason. Say, to extract people from a small LZ in a chinook the pilot would have to back into it carefully, but they don't need to if anyone can just get inside by looking at the windshield and using the ACE feature. Same thing with many other vehicles. I say that there is much more harm than good in this.

**Comment by Dystopian** [comment]
@MivinaTraktor `Get in` interaction was implemented as addition to `Quick Mount` system and hotkey which is enabled by default. We can't reliably get entry points positions due to engine limitations. You can always disable `Quick Mount` system or set menu setting in settings per mission and server.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
