### ISSUE TITLE
Mk14 Mod 1 EBR has no full-auto fire mode.

### ISSUE THREAD

**Issue by N0va339** [acemod/ACE3#8180]
**Is your enhancement related to a problem?**
For some reason with ACE3 every Mk14 weapon becomes semi-auto only.
ACE renames default ArmA's Mk14 (Marksmen DLC) to M14, but it adds its own Mk14.
I've tested Mk14 from CUP and RHS and they are also have only semi-auto, without ACE fire mode on this weapons can be changed to full-auto (tried with compats and without them, result is the same).
Default ArmA's M14 from Marksmen DLC still have full-auto mode.
I think it's a problem, because sometimes you don't have enought firepower to kill enemy without full-auto fire mode.
P.S. Also this enhancement will make ACE a little more realistic, I think it is a main goal of this mod.

**Solution you'd like:**
I would be more realistic if player could change fire rate to full-auto on Mk14 MOD 1 & MOD 0.
At least it's strange that M14 can fire full-auto, but Mk14 cannot.

**Alternatives you've considered:**
If ACE3 would not change names of default Mk14 (Marksmen DLC) I guess this problem would not appear.
But I think the better way to fix this is to add fire mode change option to Mk14 from ACE.

**Additional context:**
Screenshot attached.
![1](https://user-images.githubusercontent.com/64166361/112203520-4d129080-8c1b-11eb-9892-3588caa54eed.png)
![2](https://user-images.githubusercontent.com/64166361/112203533-526fdb00-8c1b-11eb-9abe-5992fec6231f.png)
![3](https://user-images.githubusercontent.com/64166361/112203557-57cd2580-8c1b-11eb-9b22-17d2052efc5b.png)

**Comment by Salluci** [comment]
Reasoning for this is mentioned inside `weapons` addon. EBR's are typically issued in semi-auto, select-fire variants are very rare.

**Comment by jonpas** [comment]
Changing name has nothing to do with that.

CUP Mk14 is just a retexture of the vanilla Mk14 as far as I know. We change it for the reason @Salluci gave, CUP simply inherits that change as well.

**Comment by N0va339** [comment]
> Changing name has nothing to do with that.
> 
> CUP Mk14 is just a retexture of the vanilla Mk14 as far as I know. We change it for the reason @Salluci gave, CUP simply inherits that change as well.

Oh, didn't know, thanks for the explanation. Just interesting if this feature can be turned off separately from ACE?
I really would like to have the Mk14 full-auto variant in my arsenal but without turning off main ACE.

Also want to ask if there a chance to this feature become optional in "addon options" settings in future?
Thank you in advance!

**Comment by Drofseh** [comment]
> Oh, didn't know, thanks for the explanation. Just interesting if this feature can be turned off separately from ACE?
> I really would like to have the Mk14 full-auto variant in my arsenal but without turning off main ACE.
Config level changes can't be selectively turned of without deleting the pbo that contains them.

**Comment by N0va339** [comment]
> > Oh, didn't know, thanks for the explanation. Just interesting if this feature can be turned off separately from ACE?
> > I really would like to have the Mk14 full-auto variant in my arsenal but without turning off main ACE.
> 
> Config level changes can't be selectively turned of without deleting the pbo that contains them.

That's unfortunate. Just love this gun so much, it's sad that I can't set it to full-auto with ace.
Thanks for the info and explanation anyway!

**Comment by bux** [comment]
@N0va339 You could create your own tiny addon to revert the changes made in ACE and set it to have a dependency on ACE.

**Comment by N0va339** [comment]
> @N0va339 You could create your own tiny addon to revert the changes made in ACE and set it to have a dependency on ACE. That way you'd still be able to use ACE but have the MK14 have full auto.

I've thought about it, but unfortunately I have no experience in mod/addon creation.
Because of this I've created this issue post, had a hope that maybe in future will appear option which allow to this feature be optional for noobs in coding like me :)

**Comment by Drofseh** [comment]
@N0va339 
Create a folder with whatever the name you want your mod to be, YourModName.
Create a folder inside called Addons
Create a folder inside Addons called YourModName
Create a text file inside that last folder and rename it to `config.cpp`
Make sure it doesn't have .txt at the end!
Open it with something like Notepad++ and paste the code below inside.
Replace YourModName and Your Name with, well, you know.
Save the file.
Download the Arma Tools on steam.
Run them and open Addon Builder.
Select `\YourModName\Addons\YourModName` as the Addon Source Directory and click Pack.


```
class CfgPatches {
    class YourModName {
        name = "Your Mod Name";
        units[] = {};
        weapons[] = {};
        requiredAddons[] = {"ace_smallarms"};
        author = "Your Name";
        authors[] = {"Your Name"};
    };
};

class CfgWeapons {
    class Rifle_Long_Base_F;

    class EBR_base_F: Rifle_Long_Base_F {
        modes[] = {"Single","FullAuto","single_close_optics1","single_medium_optics1","single_far_optics1","fullauto_medium"};
    };
};
```

**Comment by N0va339** [comment]
@Drofseh Oh my, thank you a lot, this is definitely what I was looking for.
You are the best!

Thanks everyone for the help, good luck with ACE 3 further improvement!
