### ISSUE TITLE
Optionals: Script error from particles

### ISSUE THREAD

**Issue by Cyruz143** [acemod/ACE3#8183]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.02` [stable]
- **CBA:** `3.15.3` [stable]
- **ACE3:** `3.13.6` [stable]

**Description:**
Script error from ace_particles.pbo

**Steps to reproduce:**

1. Have optional particles loaded
2. Throw smoke on/near water
3. `Warning Message: No entry 'bin\config.bin.ACE_SmokeAfterWater##White'.`

**Expected behavior:**
Looks like https://github.com/acemod/ACE3/blob/8e7f9b6db53a279432a2372c04be311807d1193b/optionals/particles/script_component.hpp#L46-L50 doesn't resolve properly.

**Where did the issue occur?**
- Dedicated

**Log Files:**
- N/A

**Additional context:**

**Comment by jonpas** [comment]
Fixed by #8214.
