### ISSUE TITLE
I suspect fragmentation uses advanced ballistics, which has several issues

### ISSUE THREAD

**Issue by Brisse89** [acemod/ACE3#819]
From line 270 in:
ACE3/addons/frag/CfgAmmo.hpp

CfgAmmo for fragments inherit "class B_65x39_Caseless;". 
Problem is that advanced ballistics is enabled for this class. 
There are two issues with this. 
1. Negative impact on performance
2. Changing AirFriction will not do anything because advanced ballistics uses ballistic coefficient instead. 

If this is the case, then I suggest inheriting from "class BulletBase" instead. 

Thoughts anyone? Maybe I got it all wrong, but I don't have the knowledge to find out if AB really is enabled for frag.

**Comment by brainslush** [comment]
I think you are right
Even inheriting from "BulletBase" won't make the trick.
See https://github.com/acemod/ACE3/blob/master/addons/advanced_ballistics/functions/fnc_handleFired.sqf#L36
It must be disabled for both AB and winddeflection.

**Comment by Glowbal** [comment]
Fragmentation does not trigger the fired EH, it won't activate AB or WD for it.

https://github.com/acemod/ACE3/blob/master/addons/frag/functions/fnc_doSpall.sqf#L157-L159

**Comment by esteldunedain** [comment]
> Problem is that advanced ballistics is enabled for this class. 

No, AB is only activated on the fire EH, which does not trigger for frags. This is a non-issue
