### ISSUE TITLE
Extend Range Tables for ATragMX

### ISSUE THREAD

**Issue by Samma-L** [acemod/ACE3#8191]
Right now it not show RC above 3000m distance. I input all ammo data in ballistic calculator for android named "Strelok Pro" and it have correct  MRAD numbers that work in game for range about 4500m.  From this I conclude that in the ACE 3 ATragMX  have  a range limitation. Please increase the MAX distance

**Comment by BaerMitUmlaut** [comment]
The maximum range of the AtragMX is 3700 m.
https://github.com/acemod/ACE3/blob/master/extras/manual_Horus_ATrag-v385.pdf
