### ISSUE TITLE
Crash - Respawning while unconscious with Team switch enabled

### ISSUE THREAD

**Issue by nKeee** [acemod/ACE3#8194]
**Mods:**
- **Arma 3:** `2.02` [stable]
- **CBA:** `3.15.3` [stable]
- **ACE3:** `3.13.6` [stable]

**Description:**
Being unconscious and clicking "Respawn" causes a crash when "Team Switch" is enabled for multiplayer.

**Steps to reproduce:**

1. Enable "Switch to side member" respawn option for mp in editor
2. Spawn a squad of AI and make them playable
3. Start the scenario in MP
4. Fall unconscious
5. Click respawn

**Expected behavior:**
Game crashes with C0000005 ACCESS_VIOLATION

**Where did the issue occur?**
- Self-Hosted Multiplayer / Editor (Multiplayer) 

**Log Files:**
https://gist.github.com/nKeee/515913699bafe7c658a8937cf65cd16d

**Comment by bux** [comment]
Please remove the `noLog` startup parameter and also give us the RPT file

**Comment by nKeee** [comment]
> Please remove the `noLog` startup parameter and also give us the RPT file
Whoops, my bad.

Heres the logs: https://gist.github.com/nKeee/515913699bafe7c658a8937cf65cd16d

**Comment by BaerMitUmlaut** [comment]
Tagging @dedmen since this is about a game crash.

**Comment by dedmen** [comment]
There is a ButtonClick eventhandler that deletes the button that was clicked.
The button click EH can return true/false to stop processing, but it doesn't do that.
It deletes the button and tells it to continue processing, which it of course tries to do, but fails because the button is gone.

_idd = 49

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
