### ISSUE TITLE
Twisted balance for the unconscious (AI / Player), if unconscious is disabled for AI.

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#8196]
**Is your enhancement related to a problem?**
In ACE3 medicine, many settings are very valuable. However, there is no way to disable unconsciousness for the player, while there is an option to disable unconsciousness for the AI. This looks strange, since the mission conditions for all fighters should be the same and none of them should have any advantages.

A simple example - If the player turns off the unconscious for the AI, (this may be necessary for the purposes of the game type), then the player himself will still fall into the unconscious. This distorts the balance, in the case of playing with/against AI, since without falling into unconsciousness the AI-unit will have an advantage before human unit. Even if someone says that there is no advantage, then why the hell will one soldier fall into the unconscious, and the other will never fall! This will not be fair, especially when playing single player.

Please level all players in ACE3 medicine. Disabling and enabling unconsciousness should be the same for everyone. Or at least please give to ACE3 player a way to disable the unconscious for himself, just as it is done for the AI-units.

**Solution you'd like:**
The best and fairest solution is to level all soldiers (AI and Player) and make one checkbox for all (Unconscious on / off)

**Alternatives you've considered:**
If ACE3, for reasons unknown to me, still needs to separate the unconscious between (AI and the Player), then Please give the opportunity to turn off the unconscious state for the player separately. We have always appreciated ACE3 for its flexibility in settings! such an option would be very valuable.

**Additional context:**

A checkbox next to an AI checkbox would look great:
http://images.vfl.ru/ii/1617653753/88b45cf8/33961903.jpg

**Comment by BaerMitUmlaut** [comment]
We are not concerned about balancing the game. If you dislike the setting, don't use it.

**Comment by ZeusWrath** [comment]
> If you dislike the setting, don't use it.

what are you talking about don't use? What should I not use,  your mod? Wouldn't it be easier to add one damn checkbox?
If you've made a checkbox for the AI, add it for the players also or Is this a devilishly difficult task?

> We are not concerned about balancing the game. 
It looks strange

**Comment by BaerMitUmlaut** [comment]
If you think that setting makes it to easy for players, then don't enable that setting. Now you have perfect balance again.

If you don't want unconsciousness for players and AI, that's basically vanilla medical. At that point, yes, just disable ACE.

**Comment by ZeusWrath** [comment]
> If you think that setting makes it to easy for players, then don't enable that setting. Now you have perfect balance again

Dude, let's get out!

If I turn on the "AI unconscious" checkbox, then the AI will fall into unconscious, but I can't use that because ACE3 unconscious is full of bugs!  I already posted about this here -  https://github.com/acemod/ACE3/issues/8019
Blood is coming from my eyes, I can't play with it!

What is left for me? Then, I turn off the "AI unconscious" and see the imbalance - The player still falls into unconsciousness and the AI will not fall.  It interferes with the game, don't you understand?

**Please add that damn button! Let everyone go unconscious or let everyone not go there!**

> If you don't want unconsciousness for players and AI, that's basically vanilla medical. At that point, yes, just disable ACE.

I'm tired of playing vanilla medicine, you know yourself it's boring

**Comment by ZeusWrath** [comment]
@BaerMitUmlaut  just think about what I'm talking about, don't rush to refuse

**Comment by BaerMitUmlaut** [comment]
> Blood is coming from my eyes, I can't play with it!

That does not sound healthy, you should maybe consult a doctor about that.

Here's a little script that does what you want. You can put it in initPlayerLocal.sqf for example:

```sqf
["ace_unconscious", { _this#0 setDamage 1 }] call CBA_fnc_addEventHandler;
```

**Comment by ZeusWrath** [comment]
> That does not sound healthy, you should maybe consult a doctor about that.

I sure, a doctor needs to be consulted by someone who made [such unconscious soldiers](https://www.youtube.com/watch?v=7RWsNpkkE4Y) for modification, which is called a ["realism mod" ](http://images.vfl.ru/ii/1606735348/f9c8429c/32491481.jpg)

> Here's a little script that does what you want. You can put it in initPlayerLocal.sqf for example:

However, thanks for trying the help

**Comment by ZeusWrath** [comment]
> This kind of behaviour is exactly what got your last account banned. Do you want to be banned again?

No I do not want. I don't understand, am I wrong about something? 
What I showed. I look exactly as if it was not done by a mentally healthy person. 

My logic is simple and logical - If you called yourself a "mod of realism" then you are liable. This means that nonsense should not be present in your mod. Right?
I said that "my eyes are bleeding." This means I cannot see ugliness in my gameplay. Instead, you recommend that I see a doctor. And you wanna ban me? For what reason!? 

I said everything correctly, it is not me who should go to the doctor, but the one who admits / ignores such deformities in the gameplay, continuing to call his gameplay realistic.

**Comment by ZeusWrath** [comment]
> ["ace_unconscious", { _this#0 setDamage 1 }] call CBA_fnc_addEventHandler;

By the way, it doesn't work.
I added the player to the init, he will still fall into the unconscious...
YA lish' khochu chtoby ACE3 vyglyadil adekdvatno i sbalansirovano. Kakoy tvoy otvet? Ty zakryvayesh' moy topik i ugrozhayesh' mne banom! Eto normal'no?
140 / 5000
Результаты перевода
I just want ACE3 to look adequate and balanced. What's your answer? You close my topic and threaten me with a ban! This is normal?

**Comment by ZeusWrath** [comment]
I still don't understand. For whatever reason you do not want to level the player with the AI and make the unconscious state the same for everyone (AI and the Player) Just explain to me ...

You are stubbornly silent and do not explain!

 Write something: "I can't level them, because" or "I don't want to level them because ...."
If you give a logical explanation of WHY this is so, then I wish you good luck! But I can't even guess any logical answer. In my understanding, it will logically level them, but not make them different

**Comment by commy2** [comment]
So basically, this is a duplicate #8019.

**Comment by ZeusWrath** [comment]
> So basically, this is a duplicate #8019.

no my friend this is not a duplicate. These are two completely different topics.

**Comment by commy2** [comment]
Imbalance will never be a concern. You have been provided code to kill any unit that falls unconscious. It's your responsibility to get it to work. At best this is a feature request for a setting that kills players instead of letting them fall unconscious.

**Comment by ZeusWrath** [comment]
> Imbalance will never be a concern. You have been provided code to kill any unit that falls unconscious. It's your responsibility to get it to work. At best this is a feature request for a setting that kills players instead of letting them fall unconscious.

There will always be an imbalance if the AI does not fall into unconsciousness (your settings), and the Player always falls into this state!  But still I would like to understand the main thing! You are constantly talking not about what I would like to hear.

**Please explain to me the reason why  you don't want to do this damn unconscious checkbox for the player the same way it did for the AI ?**

**Or for whatever reason why you do not want to turn on / off the unconscious for everyone (AI and Players)?**

Is it technically difficult?

**Comment by commy2** [comment]
> There will always be an imbalance

And it's not a concern and will never be.

> Please explain to me the reason why you don't want to do this damn unconscious checkbox for the player the same way it did for the AI ?

Never said this.

**Comment by ZeusWrath** [comment]
> And it's not a concern and will never be.

I will not continue to argue with you if **you do not see the obvious**. 

Good luck!

**Comment by jonpas** [comment]
Frankly, we do not have to deal with your disrespecting comments, constant demanding and unwillingness to understand anything. Good bye, don't make another account.
