### ISSUE TITLE
CBA problem

### ISSUE THREAD

**Issue by marssssssssssssss** [acemod/ACE3#8197]
I'm getting a cba problem saying
![bob](https://user-images.githubusercontent.com/82012659/113657170-43fed600-9695-11eb-8272-1f0873265982.PNG)

I'm not sure how to fix it. I already uninstalled the mod and then installed it. 
I have searched the internet and found no fix to it.

**Comment by BaerMitUmlaut** [comment]
You are using an outdated version of ACE. Update to the same version the server is using and the issue will be gone.

**Comment by marssssssssssssss** [comment]
> You are using an outdated version of ACE. Update to the same version the server is using and the issue will be gone.

yeah i already done that
