### ISSUE TITLE
BMP-2 can be endlessly rearmed while the gunner is turned out

### ISSUE THREAD

**Issue by PentruCaBlana** [acemod/ACE3#8198]
**Mods (complete and add to the following information):**
- **Arma 3:** latest steam version
- **CBA:** v3.15.1.200418
- **ACE3:** 3.13.5

**Description:**
When rearming a BMP-2 when the gunner is turned out using an ammo vehicle the BMP-2 can be rearmed endlessly.

**Steps to reproduce:**

1. Spawn a rearm vehicle and a BMP-2
2. Expend a few rounds from the BMP-2
3. Gunner turns out
4. Attempt to rearm BMP-2
5. BMP-2 gets rearmed but you can rearm it endlessly

**Expected behavior:**
Once rearming the BMP-2 to max capacity the ammo vehicle should no longer give a prompt to rearm the BMP-2.

**Where did the issue occur?**
- Dedicated and Self-Hosted Multiplayer

**Notes**:
This issue has not been tested with other vehicles with the same gunner turn out mechanic as the BMP-2 but I suspect the issue could be reproduced with those vehicles as well.

**Comment by bux** [comment]
No RPT and not the complete mod list ... because there's no BMP in Arma 3
