### ISSUE TITLE
ParadropItem inconsistency between SP and MP

### ISSUE THREAD

**Issue by LupusTheCanine** [acemod/ACE3#8199]
**Mods (complete and add to the following information):**
- **Arma 3:** 2.02.147359
- **CBA:** 3.15.3
- **ACE3:** 3.13.6

**Description:**
Crates airdropped in SP are properly ([as scripted](https://github.com/acemod/ACE3/blob/76676eee462cb0bbe400a482561c148d8652b550/addons/cargo/functions/fnc_paradropItem.sqf#L53)) ejected from vehicle while in MP airdropping cargo results in crate spawning at correct position but with no velocity. Also parachute deploys before the crate can descend at all. It causes significantly different aiming requirements between SP and MP to hit the same spot.

**Steps to reproduce:**
1. For ease of testing set paradropTimeCoefficient to something low like 0.1 or 0.0.
2. Create a mission with GhostHawk and a crate that can be loaded into its cargo preferably in VR.
3. Run the mission in SP.
4. Load the crate into the helicopter.
5. Takeoff and hover 50m+
6. Airdrop the crate
7. Observe the crate go on a ballistic trajectory behind the helicopter until it starts drifting when parachute deploys.
8. Repeat steps 4.-6. in MP on dedicated server
9. Observe crate falling straight down before parachute opens

**Expected behavior:**
I would expect the crate to fall the same way in SP and MP.
**Where did the issue occur?**
-Dedicated vs Single Player
**Log Files:**
Not relevant

**Additional context:**
I observed this when working on airdropping tables.
**Screenshots:**
[Video](https://youtu.be/coppZnKVWsM) test on our (PGM) server with additional mods,  identical results were obtained on a locally hosted dedicated server with ACE and CBA only.

**Comment by LupusTheCanine** [comment]
Further testing indicates that the issue might be at least partially caused by server load as I was unable to reproduce it on empty mission but the issue reliably happens on our server where a lot of objects are placed.
Another possible culprit might be adding items by classname vs adding objects.

**Comment by LupusTheCanine** [comment]
Another test indicates that the issue is related to differences between handling items added using classname and manually loaded, as manually added crates behave as shown in the video while ones added by classname behave correctly.

**Comment by BaerMitUmlaut** [comment]
This might be a locality issue with setVelocity.

**Comment by markooff** [comment]
Hmm...,
 but we all (a few guys on the server) have seen them landing obviously in the same place, Baer . 
 And also when we went close to them - where they have landed - they were all at the same place ... 
 So I think , it cannot rather be the problem of locality because we were all on the same dedicated server , and it has to (and after a long while - managed to) populate the movement and place when the boxes landed ...

**Comment by BaerMitUmlaut** [comment]
setVelocity is AL, so if the paradropped box is not local, it won't do anything. Position of non-local items is always synched.

**Comment by markooff** [comment]
Hmm, but we have tested it on our dedicated server - using things (crates, boxes, palettes) which obviously weren't local - because they all came from mod PGMLS (PGM Logistic System) 
https://steamcommunity.com/sharedfiles/filedetails/?id=2120189955
and they all were placed globally and managed by server .

That was the base of our MP tests ... 
So assuming what You have written , they should be positioned correctly - because they weren't local objects

**Comment by BaerMitUmlaut** [comment]
Locality can change during the lifetime of an object.

**Comment by markooff** [comment]
so You suggest that the change (global/local) should be made at the end  inside some ACE functions because I always use createVehicle which is GLOBAL and we only use ACE3 function for loading them (boxes, crates and so on) into the chopper ... And after the all crates were loaded the paradrop function was used ...

**Comment by BaerMitUmlaut** [comment]
I don't think you quite understand locality and that's alright. It is definitely an issue on our side and we'll fix it.

**Comment by markooff** [comment]
Perhaps ...
I usually like simple (hard typing and consequent languages like C,C++ Java and so on ...) and sqf can still amaze me ...in so many ways :) 
Anyway, as usuall, - thank You for Your valuable help @BaerMitUmlaut

**Comment by commy2** [comment]
Locality has nothing to do with SQF. You have these issues in all server-client games or programs for that matter.

**Comment by markooff** [comment]
Yes, but I have no problems with locality (i.e. variable scopes ) in such language than C++ or php or few others , but here, in SQF there are so many inconsequencies and - to be frank - stupid and "quick&dirty" solutions , that year by year I cannot stop of being surprized ...

**Comment by BaerMitUmlaut** [comment]
You're mixing up network locality and variable scopes. But this is getting off topic.

**Comment by markooff** [comment]
I think taht variable copes (i.e public, private , protected) is somehow close enough to the types of variables in SQF ( _this vs this and so on) That was what I was saying... 

Network locality i client-server architexture is something different

**Comment by markooff** [comment]
But, I have another question - what do You think about https://github.com/acemod/ACE3/issues/3594#issuecomment-815389035 ?? Is it possibile to solve this issue/feature request ??

Best Regards

**Comment by BaerMitUmlaut** [comment]
Please stay on topic, thanks.

**Comment by markooff** [comment]
So let me know, please, WHERE I can ask about the https://github.com/acemod/ACE3/issues/3594#issuecomment-815389035 and the possibility (even in far future) of doing such things ?
You haven't open the issue like "questions about new feature request" , yet ... :)

**Comment by BaerMitUmlaut** [comment]
You can talk about it on our Slack.

**Comment by LupusTheCanine** [comment]
I did a test, all crates that were added using [classname, vehicle, count] addCargoItem deployed correctly ejecting backwards, but all manually loaded crates dropped straight down.
My script that reports dropped object and its owner showed that manually loaded crates are called <<typical object reference>> REMOTE while those added using classname are not.

**Comment by commy2** [comment]
Double check with another person. It may look right for you, but still be broken for them.

**Comment by LupusTheCanine** [comment]
[Video](https://youtu.be/KHqnqhkpbHQ) another test, this time two clients on a locally hosted server shown side by side.
If crate is REMOTE on a dropping client its velocity is not set at all.
I have a solution but it might be ugly.

1. split serverUnload into serverUnload and serverParadrop which takes additional argument _dropVelocity or _vehicle
2. serverParadrop remoteExecCall a function to execute setVelocity wrapped in a function called something like remoteParadrop(SetVelocity).

**Comment by commy2** [comment]
It is appreciated that you're thinking about a solution, but before we split any functions or use RE (lmfao) I'd just replace [L53](https://github.com/acemod/ACE3/blob/master/addons/cargo/functions/fnc_paradropItem.sqf#L53) and [L70](https://github.com/acemod/ACE3/blob/master/addons/cargo/functions/fnc_paradropItem.sqf#L70) with an `QEGVAR(common,setVelocity)` targetEvent.

**Comment by LupusTheCanine** [comment]
At 

> It is appreciated that you're thinking about a solution, but before we split any functions or use RE (lmfao) I'd just replace [L53](https://github.com/acemod/ACE3/blob/master/addons/cargo/functions/fnc_paradropItem.sqf#L53) and [L70](https://github.com/acemod/ACE3/blob/master/addons/cargo/functions/fnc_paradropItem.sqf#L70) with an `QEGVAR(common,setVelocity)` targetEvent.

At L70 parachute is local because it was just created, setting velocity doesn't have to be executed by target event.
