### ISSUE TITLE
Deleted grenades spawn shrapnel

### ISSUE THREAD

**Issue by Cuel** [acemod/ACE3#820]
ACE3 Version:  3.0.0.1-0cf23744

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
Some servers have grenade protection near bases etc, along the lines of
```
player addEventHandler ["Fired", {
	if (_this select 2 == "HandGrenadeMuzzle") then {
		deleteVehicle (_this select 6);
	};
}];
```

**Steps to reproduce:**
Execute above
Throw grenade
Grenade is deleted, player is hurt by shrapnel

**Where did the issue occur?**
Any

**Comment by Cuel** [comment]
I'm guessing a solution would be to just move the grenade to [0,0,0], but maybe there's another fix?.

**Comment by esteldunedain** [comment]
> A solution would be to just move the grenade to [0,0,0], but maybe there's another fix?.Since it's not "normal behaviour"

I think that fix is the only viable alternative. AFAIK we can't distingish easily when a grenade "died" because it was deleted and when it "died" because it exploded.

**Comment by Glowbal** [comment]
There is `ace_frag_fnc_addBlackList` to add a round to the fragmentation blacklist.

```[round] call ace_frag_fnc_addblacklist;```

Delete the grenade a couple frames later and it should work fine. @NouberNou  or @jaynus could correct me if I am mistaken here.

**Comment by jaynus** [comment]
You are correct; this is how I prevented frag from spawning at UO for the exact scenario he is talking about; I temporarily added the frag round to the blacklist on the fired event.

**Comment by jaynus** [comment]
player addEventHandler ["Fired", {
    [_this select 6] call ace_frag_fnc_addBlackList;
    if (_this select 2 == "HandGrenadeMuzzle") then {
        deleteVehicle (_this select 6);
    };
}];

**Comment by Brisse89** [comment]
Another problem related to this one: 
Throw a grenade into the sea, and watch as shrapnel spawn as the grenade hits the water surface, without detonating.

**Comment by commy2** [comment]
Please make a seperate issue for unrelated bugs. Otherwise it's way to easy to miss one.

**Comment by NouberNou** [comment]
This really isn't our problem. If people are deleting ordnance then they need to take into account fragmentation. We have no ability to check if something has exploded or been deleted sadly. Backlog for now.
