### ISSUE TITLE
Injury sounds not playing at higher altitudes

### ISSUE THREAD

**Issue by PhiJaSko** [acemod/ACE3#8208]
When the player is above a certain altitude, the injury sounds from `ace_medical_feedback_fnc_playInjuredSound` do no longer play locally. They are probably also not broadcasted to other players in the vicinity.

The reason is that `inAreaArray` (introduced to the ACE function in commit e9c1f5e18fe99b65c88eb882fbd00f879f11d408) seems to take a 3DPosition in AGL format while being provided a 3DPosition in the raw world coordinate system. This causes the array of target players to possibly be completely empty if the altitude is higher than the distance the sound is supposed to be played at.

This can be confirmed by checking the content of the following array while standing on top of a higher building's roof or while swimming in deeper water and by changing the function to get the player's position:
`allPlayers inAreaArray [getPosWorld player, 2, 2, 0, false, 2];`
(replace `getPosWorld` with `getPos`, `getPosATL`, `getPosASL`, `getPosASLW`, ... - see https://community.bistudio.com/wiki/Position)

For a working solution this array should contain the player under all circumstances.

A solution might be a change from `getPosWorld _unit` to `ASLToAGL getPosASL _unit`, as this seems to be the easiest way to get a position in AGL format.

**Comment by PhiJaSko** [comment]
Looks like commy was onto something here:
https://github.com/acemod/ACE3/pull/7521#issuecomment-643606997

**Comment by commy2** [comment]
I like you already.

**Comment by BaerMitUmlaut** [comment]
Could you make a PR to fix this? Sounds like you've got this figured out already.

**Comment by PhiJaSko** [comment]
I might find the time to setup the dev environment sometime this weekend.

**Comment by commy2** [comment]
No need to for just this.

**Comment by commy2** [comment]
Maybe I will **finally** be able to hear these sounds in an op. T_T
