### ISSUE TITLE
I got some problem when I am walking with my weapon lowered

### ISSUE THREAD

**Issue by DemandeAtamere** [acemod/ACE3#8211]
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]

**Description:**
Hello! I am having a problem with the walking animation. When I lower my weapon by hitting ctrlx2 and by changing to walking pace, I cant walk bacwards and then my character to walk on its own.

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. _Go to ..._
2. _Click ..._
3. _See ..._

**Expected behavior:**
I expected that when I toggle to the walking pace I could walk backwards.
**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
- It occured on a singleplayer eden editor level
Im sorry for any misunderstanding, its my first comment on this site.
Thank you so much and have a nice day!
**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**

**Comment by jonpas** [comment]
@DemandeAtamere That sounds like just Arma being Arma, this is not something ACE3 changes. But if you want more help/information, you will have to fill the issue fully.

**Comment by DemandeAtamere** [comment]
> @DemandeAtamere That sounds like just Arma being Arma, this is not something ACE3 changes. But if you want more help/information, you will have to fill the issue fully.

Thank you
