### ISSUE TITLE
FPS Benchmark comparison between Vanilla and ACE3

### ISSUE THREAD

**Issue by Legolasindar** [acemod/ACE3#823]
# FPS Benchmark comparison between Vanilla and ACE3

In my tests with ACE3, I have experienced a considerable reduction in FPS. In part this comes from the AGM itself, where performance and those reductions were [reported](https://github.com/KoffeinFlummi/AGM/issues/2027).

![map_mission_bench](https://cloud.githubusercontent.com/assets/7848222/7298347/4ee81b4a-e9cf-11e4-80b9-4ccdffa48629.jpg)

But with the ACE3, loss of performance is even more pronounced. That is why I created a test mission with a controlled environment. Two missions, one with vanilla units you see on screen, no scripts or modules of any kind. And just another mission, but with ACE3 modules I've seen that could affect performance and it was very likely that users will use.
Some modules have their default settings, and other modules are activated features of likely use would lower FPS.

![modul_advballis](https://cloud.githubusercontent.com/assets/7848222/7298353/5df74f5c-e9cf-11e4-99c1-202284a57a2f.jpg)
![modul_hearing](https://cloud.githubusercontent.com/assets/7848222/7298354/5df7cf90-e9cf-11e4-94dc-ae2bac293109.jpg)
![modul_medicalset](https://cloud.githubusercontent.com/assets/7848222/7298355/5df9ed7a-e9cf-11e4-94a5-87cae7be85b4.jpg)
![modul_treatmentset](https://cloud.githubusercontent.com/assets/7848222/7298357/5dfd3eda-e9cf-11e4-8f63-388b2648e715.jpg)
![modul_winddef](https://cloud.githubusercontent.com/assets/7848222/7298356/5dfb8c7a-e9cf-11e4-8096-96c72fa6aca5.jpg)

For testing, I have run the simulation of these 6 ways.
- Arma 3 vanilla without mods and singleplayer mission without modules.
- Arma 3 vanilla without mods and multiplayer mission without modules.
- Arma 3 + CBA + ACE3 with no modules in singleplayer mission.
- Arma 3 + CBA + ACE3 with no modules in multiplayer mission.
- Arma 3 + CBA + ACE3 with modules in singleplayer mission.
- Arma 3 + CBA + ACE3 with modules in multiplayer mission.

To do this use the latest version of CBA 1.1.20.150416 RC6 and ACE3 compiled version of the April 21.
### My test equipment specs is:

MB: Asus P8H67
CPU: Intel i7-2600 3,4 Ghz
Graphic: Nvidia Gigabyte GTX 970 WF3OC 4GB
RAM: 16 GB G.Skill
### Results

To measure the performance I used the latest version of FRAPS, with options, FPS, frametimes and Min. Max. Avg. FPS.
#### The results can be downloaded from [this link](http://www.cavallersdelcel.cat/magatzem/ArmA/edicio/addons/ace3/benchmark/Benchmarks.zip)

_NOTE: Tests conducted with VSYNC enabled 60FPS Max_
Can download my test mission from [here](http://www.cavallersdelcel.cat/magatzem/ArmA/edicio/addons/ace3/benchmark/ACE3_FPS_benchmark_mission.Altis.zip).

For resume, i make this barchat. In can be seen that the performance impact is severe.

![a3_ace3_fps_avg_comp](https://cloud.githubusercontent.com/assets/7848222/7298416/bf6776b8-e9cf-11e4-82ef-0d58bd26ffd7.png)

Comment that the **Minimum** FPS with no mods Arma 3 Vanilla (52 FPS), are higher than the **Maximum** FPS with ArmA 3 + CBA + ACE3 WITHOUT modules (42 FPS) in multiplayer.

Also say that I have noticed a marked loss of FPS using Zeus. The simulator is much aground when moving the camera Zeus, micro-stutters if my bad english allows me to make me understand. This does not happen with Vanilla.
### Conclusions

We all know that the performance of the simulator Arma 3 sel is far from correct. It is an old graphics engine, running on 32-bit and a very poor use of multi-cores.
But that should not relax in our efforts to improve the performance of ACE3, especially in view of the results.
Since the AGM longer needed try to improve performance, little as possible, but now with additional features such as advanced ballistics consumes much power is needed most.
You are doing an excellent job, and that's why I wanted to do this comparison, to try to further improve your excellent work.

**Comment by esteldunedain** [comment]
@Legolasindar, we'll be analizing this data in detail, but at first glance your evaluation is somewhat flawed. 

Some pointers:
- The focus on ACE optimization was to improve the performance for MP with large player counts.

- Under those conditions, the performance is network bound! (the amount of fps you get is directly proportional to how much data is transfered to/from your client). That means that sending information across the network is what should be minimized, and that was our priority; to do so we need to do extra calculations on each client, which lowers FPS when you're processor bound (e.g. very small scale MP).

- The other big focus of ACE3 is on reliability. To do so we need to incur in some extra computational costs by doing things on non-scheduled environments; this not only makes ACE3 as responsive as the game itself but also frees engine resources for scheduler heavy tasks, like large AI counts, mission side scripts, sound mods, etc. Of course that creates a negative impact on sintetic tests like this one.

Last but not least; the simulation with and without ACE plays out in  different ways, hence the engine is computing different things; firefigths may be lasting longer, units falling unconscious instead of dying, etc.

But yeah, don't worry we'll look into it; we are very determined to make ACE3 as fast as possible. Could you send us that test mission?

Cheers

**Comment by commy2** [comment]
More interesting would be the comparision between:
Arma 3 + CBA
and:
Arma 3 + CBA + ACE3

instead of ACE vs Vanilla.

**Comment by esteldunedain** [comment]
@Legolasindar, please double check your not getting RPT spam on ace either (debug traces and/or error messages). Writting to the rpt is a certain fps killer, and debug things are often turned on/off on master this days, errors created/fixed too.

**Comment by Legolasindar** [comment]
My synthetic analysis has been motivated because in normal missions have noticed the drop in performance with ACE3. We do not make great missions, we are usually about 12 players against AI. And in these conditions we have noticed a significant drop in FPS, not only from Vanilla to ACE3, also from AGM to ACE3.
So I am worried about the performance of ACE3, is a magnificent mod, very useful and realistic, and I really worried about not being able to use it because the FPS are too low.
I do not know anything about programming, so hopefully understand my concern from ignorance ;)

Can download my test mission from [here](http://www.cavallersdelcel.cat/magatzem/ArmA/edicio/addons/ace3/benchmark/ACE3_FPS_benchmark_mission.Altis.zip).

**Comment by firefly2442** [comment]
Not sure how helpful these are for benchmarking but:

* [diag_captureFrame](https://community.bistudio.com/wiki/diag_captureFrame)
* [diag_captureFrame screen](https://resources.bisimulations.com/wiki/diag_captureFrame)
* [Performance Profiling](https://community.bistudio.com/wiki/Performance_Profiling)

**Comment by jaynus** [comment]
We have our own profiling framework that is a lot more detailed and specific but thanks

**Comment by ulteq** [comment]
@https://github.com/acemod/ACE3/issues/823#issuecomment-95609180, 40 infantry units fighting against each other on Stratis:
![cba-ace-infantery-benchmark](https://cloud.githubusercontent.com/assets/9437207/7427906/09411976-efe6-11e4-85e6-7be71a80b70a.png)

**Comment by ulteq** [comment]
Branch: Stable
Version: 1.44.130654
Commit: d87797d83df2819dd8147a776824ff3bfc31a727
Mission: [Benchmark.Stratis.zip](http://www45.zippyshare.com/v/IEmxJJPn/file.html)

![cba_ace_benchmark](https://cloud.githubusercontent.com/assets/9437207/7553931/e4a8a26e-f710-11e4-864c-21111bc390ee.png)

**Comment by esteldunedain** [comment]
Excellent @ulteq! @Legolasindar, regarding the new results, we found a nasty bug that was degrading performance during firefights. It is now fixed in master. Thank you for the report.

Keep in mind that the vanilla game performance on the same firefight seems to have degraded measurably from 1.42 to 1.44, so in  any case you'd need to repeat the vanilla banchemark.

**Comment by alanford123** [comment]
Hi. I don't wan't to sound pushy, but have you looked at optimising ACE further? AGM managed to run at a relatively marginal FPS loss, while ACE eats about half of my FPS. Do you think there's a chance this will ever improve?

Obviously I am not expecting you to find a miraculous bug that will fix the FPS issue, but any small gain would be nice.

**Comment by JamesTheClarke** [comment]
Our community has noticed significant performance drops during fire fights since the 1.54 update (with and without ACE3). Has anyone else been running into this as well?

**Comment by captainblaffer** [comment]
If I recall correctly having mods like JSRS dragonfyre running will cause frame rate issues in firefights, even when only a few clients are locally using it. You sure this is not the case?
I'll keep an eye on FPS myself

**Comment by commy2** [comment]
>with and without ACE3

Well, then my guess is that it's a problem wut

**Comment by commy2** [comment]
oops

**Comment by captainblaffer** [comment]
For the fire fight related issues, there was an arma 3 bug sound introduced in 1.54, when using 'incorrect' sound settings in Windows.

http://dev.arma3.com/known-issues
If you experience stuttering during scenes with a lot of sound effects after the 1.54 update, you can try configuring your Windows sound Default Format to 16 bit, 44100 Hz as a temporary work-around.

**Comment by Glowbal** [comment]
Clean up of old issues.
