### ISSUE TITLE
[Zeus] Defend Area -- Module

### ISSUE THREAD

**Issue by irvnriir** [acemod/ACE3#8230]
It would be helpful to have ability to put the Module on ground and define a radius to include groups from .

### See also
https://github.com/CBATeam/CBA_A3/issues/1448

**Comment by BaerMitUmlaut** [comment]
#3594

**Comment by irvnriir** [comment]
#8231 -- Ability to use `findDisplay 312 createDisplay "ace_zeus_RscDefendArea";` for targeting `curatorSelected select 0` . That can be added to Zeus Enhanced and/or other .
