### ISSUE TITLE
Help to create ACE compatibility mod

### ISSUE THREAD

**Issue by pablogsalto** [acemod/ACE3#8238]
Hello guys... A little context, I was editing a mission using "MOD MLV PROYECTO 1982" and then I realize that units wearing mod uniforms and helmets are immortal if you shot at them (tried every weapon), this only happens when the ace mod is loaded. I tried with another uniforms (CUP and RHS) and the ACE works fine. The point is I need to create a mod to fix this compatibility issue with the addon "MOD MLV PROYECTO 1982", is there a code template or something? Please help

 

MOD MLV PROYECTO 1982 https://steamcommunity.com/sharedfiles/filedetails/?id=1266670664 

Mission file https://drive.google.com/file/d/1L1jxLbMwtTdyiX0fhG7xRItTXWlXlbWh/view?usp=sharing

Addons preset for the mission https://drive.google.com/file/d/1dP-cbQc8G8BulpdwhVYsSvsTY1MdORgh/view?usp=sharing

**Comment by pablogsalto** [comment]
""RPT file here""


[Arma 3.zip](https://github.com/acemod/ACE3/files/6434969/Arma.3.zip)

**Comment by BaerMitUmlaut** [comment]
You started the game with the `noLogs` parameter, that makes the RPT file useless. Disable that parameter and try again.

**Comment by pablogsalto** [comment]
[Arma3_x64_2021-05-06_19-25-33.zip](https://github.com/acemod/ACE3/files/6437951/Arma3_x64_2021-05-06_19-25-33.zip)

Sorry about that, here's the correct rpt file, arma 3 launched with the addon preset, loaded mission in eden editor and played on LAN

**Comment by commy2** [comment]
> L1836 19:27:11 Warning Message: No entry 'bin\config.bin/CfgWeapons.'.

Does the mod always start with `bin\config.bin/CfgWeapons.` pop-up or was that caused by your compat addon?

Also, can you please debug this with ONLY the mod and your compat? The mod startup line is already 5 lines long and I am not going to downloads gigabytes upon gigabytes of mods I don't even want to have just to debug this.

**Comment by pablogsalto** [comment]
[Arma3_x64_2021-05-07_13-46-32.log](https://github.com/acemod/ACE3/files/6443164/Arma3_x64_2021-05-07_13-46-32.log)
