### ISSUE TITLE
Clean up ace_frag

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#824]
- [ ] Add headers for functions
- [x] Some function calls have the `nou_` prefix; those are surely not working right atm (but it's probably debug stuff)
- [x] Replace `player` by `ACE_player` on various places
- [x] Remove obsolete functions (e.g., `fnc_vectorDiffFast`)
- [x] Replace some vector functions (e.g., `BIS_fnc_magnitude`)
- [x] Use ACE_Settings to enable/disable frags
- [ ] Probably add some comments to functions

**Comment by Glowbal** [comment]
A lot of this is already done in #784

**Comment by esteldunedain** [comment]
> A lot of this is already done in #784

Excellent, even better! tbh I missed that PR
