### ISSUE TITLE
AI do not spawn with the medical supplies they require for the Medical AI System

### ISSUE THREAD

**Issue by Lankercool** [acemod/ACE3#8240]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.3` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.6` [eg. 3.0.0 stable, commit hash]

**Description:**
AI will not spawn with ACE medical supplies that they need in order to use the Medical AI system to patch themselves and each other up.

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. _Enable Medical AI setting and start a new scenario_
2. _Deploy any AI unit_
3. _See that they spawn with vanilla FAK/Medkit and do not have them converted into ace supplies that they require for the medical AI system to work._

**Expected behavior:**
The medical items should convert to the ACE ones otherwise the AI cannot patch themselves up and the Medical AI system becomes irrelevant, unless you go one by one and swap out the medical supplies on the AI or use custom made loadouts on them.

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer)

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**
Medical AI system checks for ACE medical items in the inventory, if there are none the AI cannot patch themselves up, and the medics can't help up their AI squadmates.

**Screenshots:**

**Comment by BaerMitUmlaut** [comment]
> Medical AI system checks for ACE medical items in the inventory

That is incorrect. Injure the unit and it will treat itself just fine.
