### ISSUE TITLE
using ace with kp liberation on hosted server explosions wont explode 

### ISSUE THREAD

**Issue by kill4meeeeee** [acemod/ACE3#8241]
hey guys so while on a dedicated server explosions wont go off while using ace, if i goto single player they explode like normal but in the multiplayer server they do not, mission is kp liberation if i didnt do this right let me know

**Comment by bux** [comment]
Please fill out the bug template.

**Comment by Fulgurofist** [comment]
oui je confirme, j'ai le même soucis....mais pas que sur Kp liberation, Liberation RX me fait la même chose.... et si je joue en solo et non sur le serveur, tout marche nikel

**Comment by BaerMitUmlaut** [comment]
Nous ne parlons pas français.
