### ISSUE TITLE
Adding the ACE2 for Arma 2 interaction menu

### ISSUE THREAD

**Issue by WastedMike** [acemod/ACE3#825]
As the mod stands now the current interaction menu is good, but is not as polished as the Arma 2 Ace2 interaction system. I request that within the ACE setting you add a feature to enable the interaction menu from Arma 2 Ace 2 with the dialog box and mouse setup. Currently using the interaction system relies on looking at a precise location on the body or vehicle to do a simple action causing longer times to heal and other tasks. Adding the Ace 2 menu will make using the interaction system much easier and likable for the players.

**Comment by kripto202** [comment]
I can see this being a module than anything else. If one person is using the ACE2 interaction menu, he would have a better advantage than everyone else that isn't using the ACE2 interaction menu. Also #414

**Comment by KoffeinFlummi** [comment]
https://github.com/acemod/ACE3/issues/414
