### ISSUE TITLE
SOG PF default loadouts backpacks disappearing (returns scope 1) 

### ISSUE THREAD

**Issue by tyl3r99** [acemod/ACE3#8252]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04` 
- **CBA:** `v3.15.3.210310` 
- **ACE3:** `3.13.6` 

**Description:**
See video attached.
Loading default loadouts, the backpack disappears after the arsenal is refreshed. 
attached is 4 default loadouts, I believe 2 of them work okay. 

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. Load the game with the following mods loaded 
- ACE 
- CBA
- TFAR BETA 
2. Go on to Virtual Reality map in the editor and then place down a NATO Survivor 
3. Attached to this bug report are a few exported loadouts. import and save them as a default loadout
4. You will see eventually that the icons for the backpacks disappear, and if you try and load these in. The bags are in fact gone. 

**Expected behavior:**
Loadouts to load with the exported items.

**Where did the issue occur?**
- Editor + MP Lan reproduced also

**Log Files:**
- https://pastebin.com/AvFnM1Dc

**Additional context:**

[default loadouts.zip](https://github.com/acemod/ACE3/files/6447936/default.loadouts.zip)

Video: https://youtu.be/0rdTqkTKa_c

`getNumber ("vn_b_pack_02_medic_m45_pl" call CBA_fnc_getItemConfig >> "scope")` returned "1" (hidden)

`[[["vn_m45","","","",["vn_m45_t_mag",36],[],""],[],["vn_hp","","","",["vn_hp_mag",13],[],""],["vn_b_uniform_sog_01_01",[["ACE_elasticBandage",20],["ACE_packingBandage",10],["ACE_fieldDressing",15],["ACE_bloodIV_250",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",5],["ACE_splint",4],["ACE_tourniquet",4]]],["vn_b_vest_sog_02",[["vn_hp_mag",2,13],["vn_m45_mag",5,36],["vn_v40_grenade_mag",3,3],["vn_m18_green_mag",3,1]]],["vn_b_pack_02_medic_m45_pl",[["ACE_EntrenchingTool",1],["ACE_elasticBandage",50],["ACE_packingBandage",30],["ACE_fieldDressing",15],["ACE_bloodIV_500",5],["ACE_bloodIV",10],["ACE_EarPlugs",3],["ACE_epinephrine",10],["ACE_surgicalKit",1],["ACE_splint",5],["ACE_tourniquet",6],["ACE_morphine",15],["ACE_personalAidKit",1]]],"vn_b_helmet_m1_03_01","",["vn_m19_binocs_grn","","","",[],[],""],["vn_b_item_map","","","vn_b_item_compass_sog","TFAR_microdagr",""]]] call ace_arsenal_fnc_verifyLoadout`
returned...
`[[["vn_m45","","","",["vn_m45_t_mag",36],[],""],[],["vn_hp","","","",["vn_hp_mag",13],[],""],["vn_b_uniform_sog_01_01",[["ACE_elasticBandage",20],["ACE_packingBandage",10],["ACE_fieldDressing",15],["ACE_bloodIV_250",2],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",5],["ACE_splint",4],["ACE_tourniquet",4]]],["vn_b_vest_sog_02",[["vn_hp_mag",2,13],["vn_m45_mag",5,36],["vn_v40_grenade_mag",3,3],["vn_m18_green_mag",3,1]]],["vn_b_pack_02_medic_m45_pl",[["ACE_EntrenchingTool",1],["ACE_elasticBandage",50],["ACE_packingBandage",30],["ACE_fieldDressing",15],["ACE_bloodIV_500",5],["ACE_bloodIV",10],["ACE_EarPlugs",3],["ACE_epinephrine",10],["ACE_surgicalKit",1],["ACE_splint",5],["ACE_tourniquet",6],["ACE_morphine",15],["ACE_personalAidKit",1]]],"vn_b_helmet_m1_03_01","",["vn_m19_binocs_grn","","","",[],[],""],["vn_b_item_map","","","vn_b_item_compass_sog","TFAR_microdagr",""]],0,0,[],[]]`

SOG PF Bug ticket - https://feedback.bistudio.com/T158447

**Screenshots:**
N/a

**Comment by tyl3r99** [comment]
added Video of bug

**Comment by tyl3r99** [comment]
![image](https://user-images.githubusercontent.com/7946533/117579406-9b57f200-b0ea-11eb-8703-e64e1d501ec5.png)

**Comment by tyl3r99** [comment]
![image](https://user-images.githubusercontent.com/7946533/117579695-f4745580-b0eb-11eb-9d46-8433cee299bb.png)

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/blob/master/addons/arsenal/functions/fnc_scanConfig.sqf#L167

**Comment by tyl3r99** [comment]
so after further investigation 

it seems that my friend (who gave me those loadout codes) spawned in AI and saved their equipment. Potentially saving pre loaded backpacks that are not shown in the arsenal.

**Comment by commy2** [comment]
Do not close. This seems like a weird edge-case that could be handled better easily.

> ace_arsenal_fnc_verifyLoadout should replace prefilled backpacks.
