### ISSUE TITLE
Advanced Ballistics DLL not found

### ISSUE THREAD

**Issue by Minidean97** [acemod/ACE3#8268]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.xx` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.6` [eg. 3.0.0 stable, commit hash]

**Description:**
When I try to play scenarios that I have created with ACE active, It says that Ace Ballistics can not be found, so I'm not able to play them.

**Where did the issue occur?**
Singleplayer / Editor (Singleplayer)

**Additional context:**
I was able to play all of these missions a couple days ago.

**Screenshots:**
![Arma 3 5_29_2021 14_39_46](https://user-images.githubusercontent.com/85032588/120083101-1712e200-c08c-11eb-9f36-f2f7e8958723.png)

**Comment by BaerMitUmlaut** [comment]
Please try disabling BattlEye, sometimes it blocks DLLs if their servers are acting up.
