### ISSUE TITLE
New RHS Vests and Helmets Inherited MAX Armor Values 

### ISSUE THREAD

**Issue by Goldwep** [acemod/ACE3#8274]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `Live version as of June 1` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `Current Steam Workshop Live Version` [eg. 3.0.0 stable, commit hash]

**Description:**
RHS has released the 6b45 vests along with other modern AFRF gear which seem to have inherited maximum armor values as they are not in the ACE compat yet most likely. This has led to communities and public servers running ACE and RHS to not use the new content until it is fixed as Opfor have more armor than MRAPs now.
**Steps to reproduce:**

1. _Go to any scenario with new RHS version armors and shoot them with all calibers. damage nullification is huge in ACE.

**Expected behavior:**
RHS Armors/Helmets should likely take 3 rounds to deal bleed damage or kill/uncon to the head and not upwards of 30+
**Where did the issue occur?**
- Dedicated Server

**Log Files:**
- N/A
**Additional context:**
N/A
**Screenshots:**
N/A

**Comment by Blutze** [comment]
What maximum? There is no maximum for protection from body armor, and these are still a far cry from the vanilla EOD vests.
What inheritance? Ace doesn't make any changes to body armor that could be inherited (or not inherited) by the wrong classes.
Why is this such a big issue suddenly? The new 6b45 is weaker than the 6b13, the IOTV and some of the SPCs that have been in RHS for years.

**Comment by Goldwep** [comment]
Im working on a video now to show what im talking about. Essentially the new 6b45s are taking entire magazines of 5.56 and even 7.62 dealing only minor bruises until the 10th or even the 20th shot. Players are not triggering the fatal wound threshold for headshots surviving multiple high power rounds to the head and only getting minor wounds. I'm not versed in the technicalities so im not sure what's causing this with these new vests

**Comment by commy2** [comment]
I fail to see what this (or #8101) has to do with ACE.

If you expect the compat PBOs to adjust armor values, then you will be waiting forever. Not going to happen.

**Comment by BaerMitUmlaut** [comment]
We won't change armor values in compats. We can't fix other mods.

**Comment by Goldwep** [comment]
Ah gotcha sorry about that i thought the ACE team managed the ACE compats ill go bug the RHS guys. Thanks for your time gents!

**Comment by Blutze** [comment]
We do manage the compat mods, which is why they are hosted here, with the code accessible for you to check and potentially even contribute. What Bär said is that this particular interaction, and specifically the armor config, is not something we will address in the compats.

In the end, 1) the RHS values are out of scale compared to almost any other mod, and 2) _this isn't even an issue_. This is what high level platecarriers do.
