### ISSUE TITLE
Unloading a wheel damages it

### ISSUE THREAD

**Issue by gamingzeether** [acemod/ACE3#8277]
**Mods:**
- **Arma 3:** `2.04` stable
- **CBA:** `3.15.3` stable
- **ACE3:** `3.13.6` stable

**Description:**
Unloading a spare wheel from a vehicle causes the wheel to be damaged.

**Steps to reproduce:**

1. Place vehicle and player
2. Open ace cargo menu of the vehicle
3. Unload spare wheel
4. Check health of wheel by using ace interact on it
5. Wheel is damaged

**Expected behavior:**
The wheel should not be damaged just from unloading it.

**Where did the issue occur?**
- Editor (Singleplayer)

**Log Files:**
- https://gist.github.com/gamingzeether/5ce8608b15f6f3d3ebe24f0619794b3d

**Comment by severgun** [comment]
@BaerMitUmlaut why not to use same approach?
https://github.com/acemod/ACE3/blob/76676eee462cb0bbe400a482561c148d8652b550/addons/repair/functions/fnc_spawnObject.sqf#L31

**Comment by BaerMitUmlaut** [comment]
Not a bad idea, PRs welcome.
