### ISSUE TITLE
Explosives arming menu flashes

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#828]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *None*

**Description:**
*Trying to use arming menu in MP causes constant flashing of it, making it unable to select primer, however using it fast enough will arm explosive properly.*

https://youtu.be/bimlgKHNHkY

**Steps to reproduce:**
* *Place any mine*
* *Try to arm it - menu flashes*

**Where did the issue occur?**
*"Multiplayer" and Singleplayer too*

**RPT log file:**
*Nuthing related to explosives inside*

**Comment by alganthe** [comment]
still happening on the last master branch as of 2015-04-26

**Comment by jonpas** [comment]
I can confirm this as well, build from about an hour ago.

**Comment by PabstMirror** [comment]
This is due to something with caching the actionPoints in interact menu

**Comment by PabstMirror** [comment]
```
if ([_target, _action] call FUNC(renderBaseMenu)) then {
    _numInteractions = _numInteractions + 1;
    GVAR(foundActions) pushBack [_target, _action];
};
```
_target was getting overwritten somewhere in that call, adding all privates seems to fix.

**Comment by esteldunedain** [comment]
Excellent; thank you @PabstMirror.
