### ISSUE TITLE
Compatibility with Adjustable Walking Speed mod.

### ISSUE THREAD

**Issue by Radeni** [acemod/ACE3#8280]
Hello ace team. I apologize in advance for not using your template for making issues, but I don't think that this is a regular issue.

I have recently released a mod called [Adjustable Walking Speed](https://steamcommunity.com/sharedfiles/filedetails/?id=2513253040) that functions using `setAnimSpeedCoef`. Players have let me know that ACE seems to break the functionality because, from how I understand it, it always changes the speed coef back to 1.

Is there a way that I can prevent ACE from doing this or is this needed for certain things in ACE to function properly? I want to make the two mods compatible but I need to know if it's even possible, and some pointers if it is.

**Comment by mharis001** [comment]
The incompatibility likely results from the `advanced_fatigue` module, specifically these lines:

https://github.com/acemod/ACE3/blob/c8812e093a366187355b8581bb0da83197cd6f95/addons/advanced_fatigue/functions/fnc_handleEffects.sqf#L61-L78

You could do what ACE medical does and add a set anim exclusion (do note that this will stop `advanced_fatigue` from applying its own `setAnimSpeedCoef`):

https://github.com/acemod/ACE3/blob/c8812e093a366187355b8581bb0da83197cd6f95/addons/medical_treatment/functions/fnc_treatment.sqf#L130-L132

**Comment by Radeni** [comment]
> You could do what ACE medical does and add a set anim exclusion (do note that this will stop `advanced_fatigue` from applying its own `setAnimSpeedCoef`):
> 
> https://github.com/acemod/ACE3/blob/c8812e093a366187355b8581bb0da83197cd6f95/addons/medical_treatment/functions/fnc_treatment.sqf#L130-L132

Could you give me an example of how to exclude an animation using this code as I'm unfamiliar with ACE Functions? Also, does this need to be executed globally or locally?

**Comment by rautamiekka** [comment]
Why close this ticket ?

**Comment by Radeni** [comment]
> Why close this ticket ?

Because I figured out how to use setAnimExclusions and now my mod works even with ACE enabled.
