### ISSUE TITLE
Turrets comprised of multiple magazines of the same type that have max round count of 1 do not get rearmed to full when Rearm Level > 0

### ISSUE THREAD

**Issue by yannisli** [acemod/ACE3#8286]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.0.4.147719`
- **CBA:** `3.15.3`
- **ACE3:** `3.13.6`
- **ITC Land Systems:** `1.2`

**Description:**
When using ITC Land Systems Paladin, a bug with Rearm when it is set to "Entire Magazine" or "Amount based on caliber" is observed in which a successful rearm does not actually replenish the ammo stores.

The Paladin is setup in which ammo is stored in multiple magazines of the same type and the magazines have a round count of 1. Each magazine correlates to one shell in the stores.

i.e. From `magazinesTurret`

```
[["itc_land_m109smo",1],["itc_land_m109smo",1],["itc_land_m109smo",1],["itc_land_m109smo",1],["itc_land_m109smo",1],["itc_land_m109ill",1],["itc_land_m109ill",1],["itc_land_m109ill",1],["itc_land_m109ill",1],["itc_land_m109ill",1],["itc_land_m109icm",1],["itc_land_m109icm",1],["itc_land_m109map",1],["itc_land_m109mat",1],["itc_land_m109pgm",1],["itc_land_m109pgm",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1],["itc_land_m109hex",1]]
```

**Steps to reproduce:**

1. With ACE Rearm set to "Amount based on caliber"
2. Load into editor with a vehicle that has a turret in which the magazines are setup that there are multiple of the same type, with 1 ammo count each. (ITC Land Systems Mod Paladin is where the bug was observed)
3. Fire any shell from the Paladin
4. Attempt to Rearm the spent shell
5. Observe that the Rearm says success
6. Get back into Gunner
7. Observe that the ammo was not actually resupplied

**Expected behavior:**
Expected behavior is that upon successful rearm, another magazine is added back to the turret.

**Where did the issue occur?**
- Singleplayer and Multiplayer Dedicated Server

**Additional context:**

When traced down via local with a 1:1 copy and paste of `addons/rearm/functions/fnc_rearmSuccessLocal.sqf`, it is observed that there can be a result with a conditional in which the function to add or update the magazines in the turret is not executed.

https://github.com/acemod/ACE3/blob/cc0d2424d4f917a5679abd30a9ca0aee8e2b12d2/addons/rearm/functions/fnc_rearmSuccessLocal.sqf#L62-L69

`_arrayModified` remains false, as the first loop does not evaluate `1 < 1` to be true (remember, these magazines have a max count of 1).

https://github.com/acemod/ACE3/blob/cc0d2424d4f917a5679abd30a9ca0aee8e2b12d2/addons/rearm/functions/fnc_rearmSuccessLocal.sqf#L72-L83

As `_arrayModified` remains false, during the next while loop, we push to `_ammoCounts`, however we do *NOT* add the magazine to the turret, as that conditional requires `_arrayModified == true`

https://github.com/acemod/ACE3/blob/cc0d2424d4f917a5679abd30a9ca0aee8e2b12d2/addons/rearm/functions/fnc_rearmSuccessLocal.sqf#L85-L87

As `_arrayModified == false` the next part to check if it should call `setTurretMagazineAmmo` evaluates to false, thus ammo is not refilled.

The exact problem exists within this conditional statement.
https://github.com/acemod/ACE3/blob/cc0d2424d4f917a5679abd30a9ca0aee8e2b12d2/addons/rearm/functions/fnc_rearmSuccessLocal.sqf#L77

A simple change of removing the `!` to change the conditional to be `if (_arrayModified) then {` should solve this issue and have desired behavior.

EDITS: Fix formatting and typos.

**Comment by PabstMirror** [comment]
This is a fantastic explanation of the problem, and thanks for the fix
