### ISSUE TITLE
Explosion of vehicle causes no damage to player and AI

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#829]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *Advanced medical for players and AI*
* *Advanced wounds - yes*
* *Vehicle crashes - yes*
* *Enable screams - yes*
* *Player/AI damage - 1*
* *AI Unconsciousness - enabled*
* *Prevent instant death - no*
* *Bleeding coef - 1*
* *Sync wounds - yes*

* *Medics setting - advanced*
* *Max revive time - 120*
* *-||- lives = -1*
* *Overdosing - yes*
* *Litter - yes*
* *LT of litter - 1800*
* *Allow PAK (Adv) - Medics only*
* *Remove PAK on use - Yes*
* *Locations PAK (Adv) - anywhere*
* *Allow Surgical kit (Adv) - Medics only*
* *Remove -||- - yes*
* *Locations -||- - anywhere*

**Description:**
*Vehicle explosion will not kill player inside of vehicle, instead he will be thrown out of vehicle and left unharmed. There is "harm" effect however but it looks the same as vanilla one. Indentical thing happens to AI too. Pretty critical bug I would say.*

http://youtu.be/J8dBxG8Oq0I

**Steps to reproduce:**
* *Place satchel charge under vehicle and arm it*
* *Get in that vehicle and detonate yourself*
* *Vehicle explodes but you are unharmed*

**Where did the issue occur?**
*"Multiplayer" and "Singleplayer"*

**RPT log file:**
*Again nothing inside of it, no script errors too*

**Comment by alganthe** [comment]
Just tried this with the same modules, version as of 2015-04-23.
Aaaand you hear that you are hurt, you get the pain but you survive without a scratch.

**Comment by ViperMaul** [comment]
Let's get a repo of this with the latest version.

**Comment by alganthe** [comment]
Just saw the need testing, the problem is still appearing with the advanced medical model.
with the basic it's working as intended (you die)

**Comment by bux578** [comment]
@alganthe 
So it's the same like in this issue #683 ?

**Comment by alganthe** [comment]
Nope bux both are caused by different things.
