### ISSUE TITLE
Interaction menu cursor vs menu centering

### ISSUE THREAD

**Issue by mwpowellhtx** [acemod/ACE3#8292]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04`
- **CBA:** `3.15.3`
- **ACE3:** `3.13.6`

**Description:**
`Always display cursor for interaction` is misleading, does not represent what is actually going on. That and the cursor being there just feels clunky, out of place, and is rather jumpy anyway.

**Expected behavior:**
I kinda like the ACE3 interaction menu circle. It is kind of a hallmark of ACE3 interaction menus, could be trademarked, IMO. No reason to abandon that for the core effect of this option.

The core effect here should simply be, `Keep menu centered`. Actually, it would be better, IMO, if the two options, this, and `Keep cursor centered` were collapsed into a single drop down or list option.

```
Keep menu centered
Keep cursor centered
```

Of, if you prefer, the behavior is _one or the other_, really and truly, a checkbox. Either the cursor is being centered (`true`), or the menu is when the cursor is not (`false`).

Several options there to chew on, kindly. Personally, kinda leaning toward the simplified option. Just remove the _Always_ option and have the interaction be an _either cursor or menu_ re: centering.

Adjusting for any peripheral concerns impacted by the request.

**Comment by BaerMitUmlaut** [comment]
Which part of this is a bug?

**Comment by mwpowellhtx** [comment]
@BaerMitUmlaut Up to you how you'd like to handle it.

**Comment by rautamiekka** [comment]
> @BaerMitUmlaut Up to you how you'd like to handle it.

Not quite the right answer to "where's the bug?".
