### ISSUE TITLE
Intuitive wind info is not available while under a parachute

### ISSUE THREAD

**Issue by ImplicitDeny** [acemod/ACE3#8306]
**Is your enhancement related to a problem?**
Wind info display is absolutely awesome in all sorts of contexts : quick&dirty check before long range shooting, useful glance before deploying a smoke screen, etc. However, when skydiving, it is not that useful : wind info is displayed during freefalling, but as soon as the player open his/her parachute (entering the parachute vehicle) the wind info disappears. This is due to this line :
https://github.com/acemod/ACE3/blob/8bd755e40a4b34d5d530c0b5e888af88570981dc/addons/weather/functions/fnc_displayWindInfo.sqf#L38
`!([ACE_player, ACE_player, []] call EFUNC(common,canInteractWith))` becomes true whenever the player enters any vehicle, thus canceling the display.

**Solution you'd like:**
This condition should be improved so that if the `vehicle ACE_player` is inheriting from `ParachuteBase`, the whole condition is false and `exitWith` is skipped, making the wind display available under the parachute.

**Alternatives you've considered:**
If this is not possible and this is a desired behaviour, maybe a similar function dedicated to skydiving would be possible ?

**Comment by ImplicitDeny** [comment]
Tweaking may also be required on this function :
https://github.com/acemod/ACE3/blob/8bd755e40a4b34d5d530c0b5e888af88570981dc/addons/weather/functions/fnc_calculateWindSpeed.sqf#L68

Indeed, the parachute itself is considered as an obstacle, leading to a zero wind when displaying wind info (with a tweaked version of `ace_weather_fnc_displayWindInfo`.

**Comment by Drofseh** [comment]
I'm not sure you'd be reasonably able to read the wind while sailing down through it...

**Comment by bux** [comment]
_"Sir, there's a lot of wind coming from down below." 🪂_

**Comment by Drofseh** [comment]
> read wind direction and speed while freefalling

That should probably be removed
