### ISSUE TITLE
Surrender option missing

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#831]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *None*

**Description:**
*I remember few commits ago that option was under self interaction menu, now it is missing.*

**Steps to reproduce:**
* *Try to surrender, you can't*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*Not needed*

**Comment by PabstMirror** [comment]
Hit 0 to put weapon on back and it should show up.

**Comment by gienkov** [comment]
It shows up, thanks!
