### ISSUE TITLE
Interaction with Firing Target overlaps

### ISSUE THREAD

**Issue by Teax20** [acemod/ACE3#8312]
**Is your enhancement related to a problem?**
The firing scoreboard from the target "TargetBootcampHuman_F" is automatic added to the ACE Interaction wich is great.
If you add another interaction menu it overlaps with the default score board action. Even if you add multiple action without a parent path they'll all overlap. Show actions for buildings in ACE Interaction Menu has to be turned on.

**Solution you'd like:**
Proper listing of all actions without overlapping.

**Alternatives you've considered:**
A way to disable those build-in actions, so i could add the score board actiony myself without overlapping.

**Additional context:**
Wanted to make a firing range only with ace interactions, added following code in the playerlocal.sqf to reset the scoreboard.
private _statement = {
    ["resetShootersData", [_target]] call BIS_fnc_target;
};
private _action = ["coverbullets","Cover Bullets","", _statement, {true}] call ace_interact_menu_fnc_createAction;
["TargetBootcampHuman_F", 0, [], _action] call ace_interact_menu_fnc_addActionToClass;

**Comment by Drofseh** [comment]
`["TargetBootcampHuman_F", 0, ["ACE_MainActions"], _action] call ace_interact_menu_fnc_addActionToClass;`

**Comment by Teax20** [comment]
Will not solve the issue with overlapping. The "Score Board" interaction wich is ace selfadded due to its building interactions option has no "parent path" in it, 
Did some further testings and found out it is not the interaction with the score board itself, its a issue with all interactions on buildings without a parent path. 
Tested it with a Single Stand aswell and added 2 actions without "ACE_MainActions" to it, same overlapping as stated above. 
As long as one action it without a parent path there will be an overlapping. 
All Building interactions created by this building ace interaction setting are without the "ACE_MainActions"  parenth path. Wich i logically understand because u have to interact with those things quick.

![interactionoverlap](https://user-images.githubusercontent.com/16085299/125064788-4e27da80-e0b1-11eb-87fb-6912ccbf60af.jpg)
As you can see, at different angles and ranges only one of 2 interactions are shown wich make it playable, at closer distance both interactions are overlapping.
