### ISSUE TITLE
No damage to highly armored targets

### ISSUE THREAD

**Issue by ProXeN** [acemod/ACE3#8315]
**Mods (complete and add to the following information):**
- **Arma 3:** `stable` 
- **CBA:** `3.15.4` 
- **ACE3:** `3.13.6` 

**Description:**
It takes a ridiculous amount of bullets to kill an AI with a high armor vest like a 'GA Carrier GL Rig' or a 'Carrier Special Rig', even surviving more than 4 bullets from a M200 Intervention. 5.45 can't even penetrate regular Plate Carriers.

**Steps to reproduce:**

1. Place an AI and equip it with a high armor vest.
2. Try to kill it with an APEX 416 or AKS-74U

**Expected behavior:**
AI should probably go down within 4-5 or even 6 bullets? 10? 

**Actual behavior:**
You can dump the whole mag and the AI doesn't even care, even when using 7.62 or .308.

**Where did the issue occur?**
- Editor (Singleplayer) / Virtual Arsenal

**Log Files:**
- https://pastebin.com/E72UZ0bF

**Comment by rautamiekka** [comment]
There's simply no point in such armors if you can't take more shots ...

I wonder if you're lowering their damage thresholds or something.

**Comment by ProXeN** [comment]
Most vests require 2 bullets on the chest to kill someone. I agree that a heavy vest should resist more than that, 4 maybe 5, but eating a whole mag and just getting a minor bruise? That's just ridiculous.

Also, damage thresholds don't make a difference from what I've been testing.

**Comment by rautamiekka** [comment]
That's the whole point of the 2035 armies using heavy armor.

I did notice in my own tests the mentioned vests don't have a huge problem taking entire mags, even 7.62 and bigger, from 5-15m distance (tested 5, 10, 15). Handguns <=9mm, and any buckshot and slug, were worthless, which I can see being a good design decision.

Admittedly, I suppose there's some point in a whole 7.62, or bigger, 30-bullet mags being rather a lot to bring someone down, especially when considering the armor doesn't look all that fancy.

**Comment by ProXeN** [comment]
Yup, 9mm and buckshots wouldn't make a dent probably, but taking a full 5.45 mag and not going down is nonsense. Even if the bullet doesn't penetrate the kinetic force of bullet would be enough to bring anyone down from just a few shots. Gameplay-wise I agree it should take more shots than with lighter armors, but having bullet sponges in Arma I don't think it's a feature but a bug.

**Comment by Dudejo** [comment]
The biggest issue is that getting shot doesn't stun you at all.

https://www.youtube.com/watch?v=GxjhykzHP8o

some people might remember this video from a while ago. While the soldier clearly survives, he still got knocked right on his ass. That video needs to happen in the game.

**Comment by LupusTheCanine** [comment]
Maybe add high dose of fast decaying pain to KO player or bot for few seconds with a certain chance.

**Comment by ProXeN** [comment]
The issue here is that some really popular mods (RHS, CUP) have vests with slightly higher armor values than regular vanilla vests (20 or 22 instead of 16) and even with that small difference that means that you go from getting killed from 2/3 shots to be able to tank 20+ 5.56 bullets, which makes fighting against something other than talibans completely absurd.

**Comment by CCRcmcpe** [comment]
Yes, people wearing IOTV took 30 M80A1 rounds from point blank range without losing conscious is completely nonsense.

**Comment by LIMUNADE** [comment]
This is bs
[ace_wtf_medical_system_CONVnvenc265_q30 CONVvp9 q35.webm](https://github.com/acemod/ACE3/assets/20593218/747ff354-ea31-4626-9765-85c0e7390cd4)
