### ISSUE TITLE
CPW's recoil is way too high for a 9mm SMG

### ISSUE THREAD

**Issue by fxt1996** [acemod/ACE3#8316]
Not sure if it's intentional or not, the CPW's muzzle climb is too much compare to other 9mm SMGs, it's even worse than some high caliber rifles, will be great if it gets tuned down a bit

**Comment by Dudejo** [comment]
To be fair, it's a short, light machine pistol with a crappy stock. Not the best platform to control recoil with, even with 9mm.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
