### ISSUE TITLE
ACE Nametags - Player names view dist. Radius not working 

### ISSUE THREAD

**Issue by tyl3r99** [acemod/ACE3#8317]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04?` [Stable as of 17th July 21]
- **CBA:** `3.15.5.210713` [Stable]
- **ACE3:** `3.13.6` [Stable - Official version]

**Description:**
Ace nametag "player view dist" does not seem to be working correctly. We have had many occasions where we have our distance set to 15m and quite often, we wont be able to see them unless we are 5m away from each other. 

I have checked CBA settings and it has a GREEN tick with both mission and server boxes checked. (forcing the setting across all clients who join) 

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. Load ACE and CBA 
2. Apply nametag settings including AI nametags, with a rough distance of 25m? 
3. (I am having great trouble finding a 100% repro... not going to lie so if there's anything I can do that I'm missing please say so I can obtain this info for you. our whole groups been having this issue for a long time but never had enough information to really make a report without looking stupid) 
4. go in editor and place units down including a player 
5. test on LAN hosted
6. see if the nametags function as they should? 

**Expected behavior:**
ACE Nametag distance to be consistent when CBA settings are applied on the server and overwriting clients. 

**Where did the issue occur?**
- Editor / LAN / Dedicated Server

**Log Files:**

**Additional context:**
// ACE Name Tags
ace_nametags_defaultNametagColor = [1,0.911458,0.206611,1];
ace_nametags_nametagColorBlue = [0.67,0.67,1,1];
ace_nametags_nametagColorGreen = [0.67,1,0.67,1];
ace_nametags_nametagColorMain = [1,1,1,1];
ace_nametags_nametagColorRed = [1,0,0,0.701618];
ace_nametags_nametagColorYellow = [1,1,0.67,1];
force force ace_nametags_playerNamesMaxAlpha = 0.701618;
force force ace_nametags_playerNamesViewDistance = 23;
force force ace_nametags_showCursorTagForVehicles = true;
force force ace_nametags_showNamesForAI = true;
force force ace_nametags_showPlayerNames = 1;
force force ace_nametags_showPlayerRanks = false;
force force ace_nametags_showSoundWaves = 0;
force force ace_nametags_showVehicleCrewInfo = false;
force force ace_nametags_tagSize = 3;

In the photos supplied, you can see my ace nametag viewdist is quite high yet im standing roughly 5m away from the AI (AI name tags enabled for this debugging)

Our group DOES use DUI/ALiVE.
however.. DUI nametags are off and that is forced across all clients also when joining the server. (with GREEN tick) 
ALiVE nametag module is not placed or enabled. 

I will see if it happens on just CBA and ACE. Will update as soon as I can.

**Screenshots:**
![20210717170459_1](https://user-images.githubusercontent.com/7946533/126043136-c69ccb71-9e87-4543-8a22-e84431a610e6.jpg)
![20210717170446_1](https://user-images.githubusercontent.com/7946533/126043139-24bc3552-5e21-49cc-8a26-324c8ea9885c.jpg)

**Comment by tyl3r99** [comment]
Info: Unloaded DUI, problem still occurs

**Comment by tyl3r99** [comment]
More info: 
Slowly loading my modpack 1 by 1 testing as i go 
ALiVE, TFAR Beta, 3den enhanced, DUI, Our own SAS mod 

NO affect on ACE nametags, they are working as intended here on a new mission file. 
![20210717175534_1](https://user-images.githubusercontent.com/7946533/126044300-a38ef318-6fb8-417f-af03-02d9cf364d2c.jpg)
![20210717175528_1](https://user-images.githubusercontent.com/7946533/126044306-920ca9a2-c005-4c2c-9b28-93aa23d9b2c1.jpg)

Very Very odd.. will keep digging

**Comment by tyl3r99** [comment]
Loaded full modpack no issues, I dont get it.. :( 
on my other mission its skewiff

**Comment by tyl3r99** [comment]
loaded up my mission, ace nametags only show up 5m 

Please find attached zip file which includes..
Mission file, RPT, modpack if you are interested, maybe it will happen for you as well. (no rhs or cup)

[SAS_Complete_Vanilla_editor_mods.zip](https://github.com/acemod/ACE3/files/6835042/SAS_Complete_Vanilla_editor_mods.zip)

**Mod list**
![image](https://user-images.githubusercontent.com/7946533/126044780-c6603041-12f1-41e7-a754-31644141d573.png)

**Comment by severgun** [comment]
Your new mission have different lighting conditions.

https://github.com/acemod/ACE3/blob/e870e2f1f96be967ea589e6907b980a9fbf8349d/addons/nametags/functions/fnc_getCachedFlags.sqf#L54

**Comment by tyl3r99** [comment]
Wait brightness is a thing? 
Is there a setting that can tweak the coefficient of how much brightness will affect it?

**Comment by severgun** [comment]
>  Is there a setting that can tweak the coefficient of how much brightness will affect it?

No.
At least now.

**Comment by tyl3r99** [comment]
I've added a feature request for the additional setting. 

I literally had no idea that was a thing lol
