### ISSUE TITLE
Dragging injured may cause client to disapear

### ISSUE THREAD

**Issue by AndreasBrostrom** [acemod/ACE3#8320]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04.147719`
- **CBA:** `3.15.5.210713`
- **ACE3:** `3.13.6`

![image](https://user-images.githubusercontent.com/13811113/126361311-fec75d5b-c745-4d81-a8a1-15e241daa50d.png)

**Description:**
Client may lose location of downed friendly unit when dragging is being made. This results in the client disapearing and returning to its start dragging positon. (If using Squad Radar mods this is vissable). Friendly client is not shown in the 3D space and is not possible to be interacted with or sean. ACRE comuntication with the individual also stops working and is only communicatable via Radio.  The client is vissable for other clients and is just effecting the dragger initzialiser.
If the client ace throw a grenade or smoke this will magicaly appear from thin air. 

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. _Have downed friendly player_
2. _Select drag via ace interact_
3. _Drop later on IF person disaper while you drag yoru acived it_

**Expected behavior:**
Be able to drag drop individual when injured 

**Where did the issue occur?**
- Dedicated

**Log Files:**
- N/A

**Additional context:**
This does not happen everytime and seams to be semi random.

**Screenshots:**
Shows 3 individuals on the Squad radar you can see 3 blue dots it should be 4. The 4th client is according to my client 300 meters north west.
![unknown](https://user-images.githubusercontent.com/13811113/126360828-868b3be2-dfba-4399-9974-653f465809bb.png)

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
