### ISSUE TITLE
Common - addToInventory replaces weapons

### ISSUE THREAD

**Issue by JoramD0** [acemod/ACE3#8328]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04 stable`
- **CBA:** `3.15.5`
- **ACE3:** `3.3.16`

**Description:**
If you add a weapon through [addToInventory](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_addToInventory.sqf) while having enough space for the weapon but not the available weapon slot it will replace the weapon currently in that slot. This is not happening when you add it to a specific container.

**Steps to reproduce:**
1. Get a big enough backpack to fit a weapon and equip weapons.
2. Add another weapon with [addToInventory](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_addToInventory.sqf).
3. See that currently equipped weapon got replaced

**Expected behavior:**
To have the weapon go into the inventory or drop on the ground instead.

**Where did the issue occur?**
- Editor (Singleplayer)

**Log Files:**
- [rpt](https://gist.github.com/JoramD0/032eebc18843d78bcb35e3c1d6748cf2)

**Additional context:**
Cause of the issue:
CBA returns the weapon can fit into the inventory ([here](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_addToInventory.sqf#L40)), then ACE adds the weapon with [addWeaponGlobal](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_addToInventory.sqf#L60) which replaces the currently equipped weapon.

I tried thinking of a solution myself but couldn't think of anything good.

**Screenshots:**
N/A

**Comment by jonpas** [comment]
In addition to `CBA_fnc_canAddItem` we would have to get the slot the weapon goes in (primary, secondary  or handgun) and check if that slot is empty.
```sqf
_canAdd = [_unit, _classname] call CBA_fnc_canAddItem;
if (_canAdd && <is weapon>) then { // config check?
    private _slot = <get slot weapon fits in>; // however you can do that
    switch (_slot) do {
        case "primary": {
            _canAdd = primaryWeapon _unit == "";
        };
        case "secondary": {
            _canAdd = secondaryWeapon _unit == "";
        };
        case "handgun": {
            _canAdd = handgunWeapon _unit == "";
        };
    };
};
```
