### ISSUE TITLE
Shooting limbs on AI will not kill them

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#833]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *Advanced medical for players and AI*
* *Advanced wounds - yes*
* *Vehicle crashes - yes*
* *Enable screams - yes*
* *Player/AI damage - 1*
* *AI Unconsciousness - enabled*
* *Prevent instant death - no*
* *Bleeding coef - 1*
* *Sync wounds - yes*
* *Medics setting - advanced*
* *Max revive time - 120*
* *-||- lives = -1*
* *Overdosing - yes*
* *Litter - yes*
* *LT of litter - 1800*
* *Allow PAK (Adv) - Medics only*
* *Remove PAK on use - Yes*
* *Locations PAK (Adv) - anywhere*
* *Allow Surgical kit (Adv) - Medics only*
* *Remove -||- - yes*
* *Locations -||- - anywhere*

**Description:**
*Shooting limb on AI with above settings (not tested others) will not kill them that quickly as one would think. It will not kill them at all. Even biggest caliber will only put them unconcious and you can shoot as many rounds as you want on those limbs - it will not kill him. Shooting torso or head however will kill them pretty quickly.*

*I think it should be looked into asap as one would have to make precise headshots or always hit torso to put down AI quickly. Please don't tell me this is made intentional. They should sustain more bullets maybe but get big penalty to aiming (arms hit) or movement speed (leg hit) which is working from what I saw already.*

*It's worth mentioning that I have Prevent instant death set to disabled. Enjoy watching videos below:*

*Warning, violent videos below! This was done for testing only, I'm not a sadist!*
http://youtu.be/f9e8wWJp2Co
http://youtu.be/mU9CeFggjvM
*Different wounds are showing on limbs properly:*
http://youtu.be/Vv4nMkDg46A

**Steps to reproduce:**
* *Place medical module set as described above*
* *Place AI to shoot at*
* *Shoot at his limbs*
* *After 1-2 shots he will be unconcious*
* *Shooting many more on limbs will not kill him*
* *He will die due to bleeding*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*Nothing inside*

**Comment by alganthe** [comment]
Same settings as yours, here's my results:
target: CSAT rifleman, classname "O_Soldier_F"

- 6,5 x 39 STANAG
one or two center of mass put him unconscious, the next one kills him.
sometimes he also die in one hit.

-7,62 x 52 NATO
one hit kill, all the time

**Comment by gienkov** [comment]
It's worth mentioning, that I spawned AI using VTS console, not preplaced in editor.

**Comment by alganthe** [comment]
above comment updated, ai limbs seems to be made of depleted uranium.

**Comment by jaynus** [comment]
Are these tested dedicated, mp self host or sp? Zeus AI or mission AI?

**Comment by alganthe** [comment]
on my case tested in editor with pre-placed units, setCaptive true in my unit init.

**Comment by gienkov** [comment]
I was testing on dedi and then hosted. Spawning AI using Zeus and VTS console. I suspect same effect on SP.

**Comment by jaynus** [comment]
Please test again in dedicated mission spawned. MP Zeus is not MP; the AI is still local to your system.

I suspect this is an AI locality issue for non-dedicated

**Comment by gienkov** [comment]
VTS console spawns them on server so they are not local to me then. And same things happens.

**Comment by jaynus** [comment]
Ok thanks will investigate

**Comment by gienkov** [comment]
No problem. I hope this will be fixed before first release :).

**Comment by ulteq** [comment]
> you can shoot as many rounds as you want on those limbs - it will not kill him

I can not replicate that on SP.

**Comment by alganthe** [comment]
what branch are you on ulteq ? 
Because I can replicate that pretty easily, they only die from losing too much blood..

**Comment by jaynus** [comment]
I cannot replicate here or in the medical improvements branch

**Comment by Glowbal** [comment]
Please provide a version number, including commit hash.

**Comment by ulteq** [comment]
This issue is about `Advanced medical for players and AI`:
> I managed to inflict 63 wounds on an ai and he was still alive, he died of blood loss 1 minute later.

This sounds pretty legitimate.

**Comment by alganthe** [comment]
The issue ulteq is that the ai can only sustain 2 wounds on the chest before dying, so 63 on the right leg seems to be a "bit" too much in comparison.
I had to inflict around 10 to 20 wounds before the ai passed out with 6.5 at point blank range.

**Comment by esteldunedain** [comment]
> they seem to bleed out faster now, but the sheer amount of wounds I can inflict on limbs without them dying is just insane.

I'm not an expert or anything, but I believe you can outright severe a leg and still have the patient survive for at least a minute. Shooting a leg a zillion times won't make it bleed any faster than just cutting it so I think this is legit.

**Comment by alganthe** [comment]
The problem again is that you can take someone out in 3 shots otherwise by shooting in the chest.
1-2 to make the guy unconscious and again 1-2 to kill him.
it's not really consistent.

**Comment by esteldunedain** [comment]
> The problem again is that you can take someone out in 3 shots otherwise by shooting in the chest.
1-2 to make the guy unconscious and again 1-2 to kill him.
it's not really consistent.

Neither is reality. All your vital organs are located on the chest and head. None in the legs or arms.

**Comment by gienkov** [comment]
@esteldunedain Makes some sense, that can give more situations when you have to check lying bodies of enemy to know if they are alive or dead.

**Comment by ulteq** [comment]
> Still, there should be some "threshold" of how many wound there can be

I've always suggested that.

**Comment by jaynus** [comment]
Limbs can only bleed so much, and a minute sounds tbh too fast for advanced medical.

A person can survive a severed, mutilated leg - at this point you are more worried about shock than bleeding.

I think this can be closed, pending the planned shock trauma implementation in 3.1

**Comment by Glowbal** [comment]
I agree. I have implemented a few minor adjustments on the medicalImprovements branch, but I think any other tweaks have to be done after 3.0.0 release.
