### ISSUE TITLE
Allow "Create Zeus" for unconscious players

### ISSUE THREAD

**Issue by mollybeam** [acemod/ACE3#8330]
Currently, players that have the ability to use Create Zeus cannot do so while unconscious. This is an issue if they have to revive themselves and have not already activated Create Zeus

Ideally, it would be possible to detect when a player has the ability to use Create Zeus while unconscious, and allow them to access the self-interact menu, but only be able to access that option. 

Alternatively, could Create Zeus be placed in the pause menu?

**Comment by dedmen** [comment]
Similar issue with spectator. If you have access to enter spectator via debug console, its useless when unconscious as input is blocked and you cannot move the spectator cam

**Comment by rautamiekka** [comment]
Would be a hugely useful feature.

**Comment by Mike-MF** [comment]
This is a feature request, not an issue.
