### ISSUE TITLE
Fast Rope spins and throws people off

### ISSUE THREAD

**Issue by Slatery** [acemod/ACE3#8336]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04.147719`
- **CBA:** `3.15.3`
- **ACE3:** `3.13.6`

**Description:**
Fast ropes when deployed, will spin from their spawn point and throw people off when trying to rappel. 

**Steps to reproduce:**
1. Create new mission
2. Place Ghost hawk
3. Equip with FRIES from Attributes
4. Start mission from a player in a passenger seat
5. deploy ropes
6. Observe spinning
7. Attempt to rappel
8. Be thrown off
9. If left alone, occasionally they will spin fast enough to break themselves

**Expected behavior:**
Player can rappel safely and ropes do not spin

**Where did the issue occur?**
- Observed on Dedicated, replicated in Editor (Singleplayer)

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**
Initially observed this happening with the H-60 pack blackhawks where we used a custom fast rope point in multiplayer games. Replicated it with the vanilla ghost hawk, both with our mods and with only CBA + ACE

**Screenshots:**
https://youtu.be/T66TqxMY6z0

**Comment by BaerMitUmlaut** [comment]
Spinning is a side effect of PhysX. You're thrown off because the AI starts flying away.

**Comment by Slatery** [comment]
The AI are perfectly still in the video. You can see that the shadow isn't moving at the end. I can recreate the scenario with no ai to eliminate that issue.

Please don't just assume with prior bias

**Comment by Slatery** [comment]
As mentioned, this issue originally occurred in a multiplayer player controlled environment. If a player or an ai who are both not moving are unable to be still enough to not buck a player off then perhaps tolerances need to be reviewed

**Comment by BaerMitUmlaut** [comment]
The AI is not perfectly still in the video. You can hear the increase in collective and you can clearly see that the ends of the ropes are far from touching the ground.

![grafik](https://user-images.githubusercontent.com/9693842/126947555-51de00d8-db43-40b0-b089-ce882277de97.png)

The tolerance is 5 m/s or 18 km/h in any direction (that includes upwards). If your player pilot cannot stay that steady then maybe they should just use autohover.

**Comment by Slatery** [comment]
https://youtu.be/eIfmsA7cmdw

**Comment by Slatery** [comment]
every single person who went down the rope, got injured as they get thrown off right at the bottom, I know it's not with only CBA and ACE

**Comment by BaerMitUmlaut** [comment]
Can you point me to where anyone is being thrown off the rope? Because that's not happening here.
