### ISSUE TITLE
Repacking result is not fully visible

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#834]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *None related*

**Description:**
*Repacking magazines should show results at the end but I think hint window is too small, cause of that not all informations are visible, if more should show up. I remember I translated result string and I just cannot see it.*
http://i.imgur.com/TEttBwG.jpg

**Steps to reproduce:**
* *Repack magazines, see result*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*Not needed*

**Comment by jaynus** [comment]
So is this saying the hints are too small?

**Comment by gienkov** [comment]
Yes. Exactly.

**Comment by jaynus** [comment]
@glowbal is this scaled to interface size like the interactions? That may be something to consider.

**Comment by Glowbal** [comment]
Yes they are, but not to the length of the string.

Ideally we would calculate the height of the box using the amount of characters. For that we would need a font with a consistent width across each character, or figure out the width for each character ourselves.

A rough estimate will sort of work, but might end up looking really odd in some cases, as evident by the CSE hints.

**Comment by commy2** [comment]
It did work out with the info box size in AGM, but I guess it was shrinked in ACE.

**Comment by Glowbal** [comment]
The AGM box size was very wide and high; it's quite a bit smaller in ACE. For messages that have a lot of text or an image, we should use the size parameter and it should work out ok in most cases. Unless localized text becomes that much longer, I guess.

**Comment by commy2** [comment]
Maybe a simple count ? Works now with strings.

**Comment by Glowbal** [comment]
I assume this is now fixed.

A count will have the same result; we do not have accurate width of characters afaik. @jaynus and I discussed this a while back. We should get a proper font for these things. But that is something for the next milestone I think.
