### ISSUE TITLE
Having X primers of same type in inventory will display them X times

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#835]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *None*

**Description:**
*Not really an big issue, but something worth mentioning. Having for example three Dead Man's Switch and using them to fuse an IED will then show three Dead Man's Switches in Detonating menu. I as mission maker always give one primer to players and found this one by accident. Maybe it should show only one primer even with multiple primers of same type?*

**Steps to reproduce:**
* *Get X primers of same type*
* *Fuse bomb using one*
* *Open detonation menu, you will see one and the same primer X times you have it in inventory*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*Not needed*

**Comment by alganthe** [comment]
Isn't that... normal behavior ?

**Comment by gienkov** [comment]
Yup, it just shows multiple primers for detonating the same explosive.
Its just a feedback.

**Comment by CorruptedHeart** [comment]
https://github.com/acemod/ACE3/blob/master/addons/explosives/functions/fnc_getDetonators.sqf#L22-L27
Just needs a
```sqf
if (getNumber (_config >> "ACE_Detonator") == 1 && {!(_x in _result)}) then {
```
