### ISSUE TITLE
Cannot zero when looking through optics of static weapons and vehicle mg/gmg

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#836]
ACE3 Version: 3.0.0

**Mods:**
* @cba_a3
* @ace3
* @acre2

**Placed ACE3 Modules:**
* *None*

**Description:**
*Trying to use Page Up / Down inside of static mg/gmg or vehicle mounted mg/gmg while looking through optics will not zero optics as it should. It will make "click" sound. However while not looking through optics you are able to use Page Up / Down to change zero (it changes below weapon name tab).*

**Steps to reproduce:**
* *Try to zero using PgUp/Down while looking through optics of static mg/gmg or vehicle mg/gmg.*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*Not needed*

**Comment by ulteq** [comment]
I can't reproduce this issue. What vehicle did you use for testing?

**Comment by commy2** [comment]
Repro steps:

1. Spawn as / near an empty `B_HMG_01_F`
2. Use the optics (!)
3. Pg Up / Down seems to use the weapon zeroing similar to the primary weapon.

Does not happen when not using the optics mode.

**Comment by commy2** [comment]
Caused by the FCS

https://github.com/acemod/ACE3/blame/master/addons/fcs/initKeybinds.sqf#L38
