### ISSUE TITLE
BMP-2 displays incorrect loading options when rearming if gunner is turned out. 

### ISSUE THREAD

**Issue by Kavlar** [acemod/ACE3#8377]
1. Spawn BMP-2
2. Spawn ammo vic
3. Expend some BMP-2 rounds
4. Have gunner turn out
5. Observe you can now grab any resupply including rounds that weren't expended

**Comment by Drofseh** [comment]
Fill out the issue template that you deleted

**Comment by BaerMitUmlaut** [comment]
Vanilla has no BMP-2, so no idea what you're talking about. As Drofseh already said, fill out the template, we have it for a good reason.
