### ISSUE TITLE
Medical Dependency Tree Issue

### ISSUE THREAD

**Issue by kymckay** [acemod/ACE3#8389]
Just reviewing some of the items from the draft changelog. I don't believe this PR should have been merged as is, medical engine cannot depend on a setting from medical damage due to the dependency tree of those components.

Either medical engine must now depend on medical damage (creating a loop in the dependency graph) or this setting should be moved to medical engine where it takes effect.

Fwiw, there was some reason this setting was removed in the rewrite, but I forget what it was. I think it may be because there's no way to consistently detect all vehicle crashes (as reflected in the code comments).

_Originally posted by @kymckay in https://github.com/acemod/ACE3/issues/8149#issuecomment-893415500_

**Comment by kymckay** [comment]
Marked critical since it introduces an implicit dependency and should be fixed before next release, in reality it's unlikely anyone would ever load one without the other.

**Comment by jonpas** [comment]
> this setting should be moved to medical engine where it takes effect.

This.

**Comment by Salluci** [comment]
Would moving it to main medical component work instead? medical engine has no settings file currently.

**Comment by kymckay** [comment]
@Salluci There's a graphic somewhere for the medical rewrite dependency tree, the idea was to split the responsibilities in a logical way.

If I remember right medical engine is the root node and "medical" is the lowest leaf node (not sure if it worked out this way, but the idea was for that component to house public API stuff)
