### ISSUE TITLE
ACE Compat - RHS: AFRF CSW tripod missing for some weapons

### ISSUE THREAD

**Issue by Saborknight** [acemod/ACE3#8393]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04.147719`
- **CBA:** `3.15.5`
- **ACE3:** `3.13.6`

**Description:**
The following CSW weapons don't have any tripod associated with them when equipped in the launcher slot:
- `ace_compat_rhs_afrf3_metis_carry`
- `ace_compat_rhs_afrf3_kornet_carry`

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. _Equip CSW Metis Launcher or CSW Kornet Launcher in the Launcher slot_
2. _Attempt to place on any CSW Tripod_

**Expected behavior:**
At least be able to mount on to the 6P57 tripod, if not others. 

**Where did the issue occur?**
- Dedicated

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**

**Comment by TheCandianVendingMachine** [comment]
The Metis in real life and in-game can be (should be able to be) deployed without any associated tripod. The Kornet does need one however

**Comment by Saborknight** [comment]
Huh, did not know that. But doesn't the CSW system require a tripod to deploy and use it? Otherwise it's just in a bag...

**Comment by BaerMitUmlaut** [comment]
No, the CSW system doesn't require a tripod.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
