### ISSUE TITLE
Binoculars have wrong visual and does not zoom

### ISSUE THREAD

**Issue by darknightx33x** [acemod/ACE3#8402]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04` stable
- **CBA:** `3.15.5.210713` stable 
- **ACE3:** `3.13.6` stable 

**Description:**
interacting with the binoculars to look at something will have the wrong "reticle" or scope for the binoculars. Additionally, the zoom in function does not work.

**Steps to reproduce:**
1. Equip a pair of binoculars.
2. Press B (Default) to pull out binoculars
3. Mouse right click (default) to interact with item
Incorrect display will be visible. Looks like a zoomed in scope reticle instead that is partially off screen.
4. Hold mouse right click (default) to zoom
Fails to zoom in.

**Expected behavior:**
1. Equip a pair of binoculars.
2. Press B (Default) to pull out binoculars
3. Mouse right click (default) to interact with item
See binocular display
4. Hold mouse right click (default) to zoom
Zoom in view.

**Where did the issue occur?**
-  Editor (Singleplayer) / Virtual Arsenal / Multiplayer

**Log Files:**
Does not crash game.

**Additional context:**
Possible useful bit of information: When narrowing down this issue to the source, I started with an additional mod called 'operation trebuchet.' They have a 'unsc binoculars' item which is basically a retextured binoculars. This item also experienced the same issue. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/44118889/131275816-dba8063e-786a-4a76-ace9-0d575fdde50d.png)

**Comment by commy2** [comment]
What you describe as expected behavior does not match what I expect from these.

**Comment by BaerMitUmlaut** [comment]
This is an intetnional change.
