### ISSUE TITLE
Advanced Fatigue - Medical overrides `swayFactor` setting

### ISSUE THREAD

**Issue by Whigital** [acemod/ACE3#8407]
**Mods:**
- **Arma 3:** `2.04.147716`
- **CBA:** `3.15.5.210713`
- **ACE3:** `3.13.6` (https://github.com/acemod/ACE3/commit/8bd4922fccc86b53bae25d43a8c95b77c9b75f54)

**Description:**
Setting Adv. Fatigue sway factor lower than 1 gets overridden by hardcoded Medical sway factor

**Steps to reproduce:**

1. Enable Adv. Fatigue.
2. Set `ace_advanced_fatigue_swayFactor` to anything lower than `1`, `0.5` in this case.
3. Inspect the returns from the sway calcs:

```sqf
private _aimHash = (missionNamespace getVariable ["ACE_setCustomAimCoef", nil]);

{
    private _hashCode = [_aimHash, _x] call CBA_fnc_hashGet;

    diag_log text format ["%1 sway value: %2", _x, call _hashCode];
} forEach ([_aimHash] call CBA_fnc_hashKeys);

private _swayMax = [missionNamespace, "ACE_setCustomAimCoef", "max"] call ace_common_fnc_arithmeticGetResult;

diag_log text format ["Sway value from arithmeticGetResult: %1", _swayMax];
```

```
21:47:53 ace_advanced_fatigue sway value: 0.782006
21:47:53 ace_medical sway value: 1
21:47:53 Sway value from arithmeticGetResult: 1
```

**Expected behavior:**
Sway/amingCoef affected by `ace_advanced_fatigue_swayFactor` setting.

**Where did the issue occur?**
Anywhere

**Additional context:**
https://github.com/acemod/ACE3/blob/76676eee462cb0bbe400a482561c148d8652b550/addons/advanced_fatigue/XEH_postInit.sqf#L5-L20

https://github.com/acemod/ACE3/blob/76676eee462cb0bbe400a482561c148d8652b550/addons/medical/XEH_postInit.sqf#L8-L10

Overwriting the `ace_medical` `ACE_setCustomAimCoef` codeblock with `ace_advanced_fatigue_swayFactor` incorporated solves the issue, don't know if it's the best solution though:

```sqf
[missionNamespace, "ACE_setCustomAimCoef", "ace_medical", {
    ((linearConversion [0, 1, (0 max ((ACE_player getVariable ["ace_medical_pain", 0]) - (ACE_player getVariable ["ace_medical_painSuppress", 0])) min 1), 1, 5, true]) + (ACE_player getVariable ["ace_medical_engine_aimFracture", 0])) * ace_advanced_fatigue_swayFactor
}] call ace_common_fnc_arithmeticSetSource;
```

**Comment by severgun** [comment]
I think you trying to compare sway coef value vs factor.
Factor is multiplier so it define HOW FAST coefficient will change. When factor 0 you can run as much as you want, sway coef will not rise. With 0.3 it rise very slowly.

**Comment by Whigital** [comment]
Not comparing anything, simply sharing the observation that with Adv. Fatigue enabled and the sway factor (setting name,  `setCustomAimCoef` command being used) lowered, it doesn't have any affect, since the Medical `ACE_setCustomAimCoef` set doesn't take the lowered value into account.

Maybe add the sway factor multiplier at the end of `ace_advanced_fatigue_fnc_handleEffect` where the sway is actually updated

https://github.com/acemod/ACE3/blob/ee4431980146091fa816b7b9da87dde6e3ca3094/addons/advanced_fatigue/functions/fnc_handleEffects.sqf#L99

and remove the `GVAR(swayFactor)` multiplier from the `ACE_setCustomAimCoef` set, that way it's kept within the module, but still effective ?

From what i could find scanning through the codebase, `ace_advanced_fatigue_fnc_handleEffect` is the only place `setCustomAimCoef` is called, and can't find any calls to `ace_common_fnc_setAimCoef` either, so the sway isn't even updated
unless Adv. Fatigue is enabled ?

**Comment by severgun** [comment]
> it doesn't have any affect

When fatigue sway value hit `1.0` it will be taken into setCustomAimCoef over medical

**Comment by Whigital** [comment]
So you're saying it's expected behavior that a setting, which you can set below 1.0, has no effect below 1.0 ?

Doesn't make any sense ....

**Comment by severgun** [comment]
> has no effect below 1.0 ?

Factor define not only base level but HOW FAST value will change.
– Does factor 0.3 affect how fast fatigue sway rising?
– Yes.
– Can you feel the difference?
– Yes. You can run more and get less sway.
– If you can feel difference, does it mean sway is affected by this factor?
– Yes.

https://www.desmos.com/calculator/l8rka85p0g

Again.
1,5 to 0,5 here and done.
```sqf
(linearConversion [0, 1, GET_PAIN_PERCEIVED(ACE_player), 1, 5, true]) + (ACE_player getVariable [QEGVAR(medical_engine,aimFracture), 0])
```

**Comment by Whigital** [comment]
I think you've misunderstood the whole reasoning.

- `ace_advanced_fatigue_swayFactor` is used in the modification of the aiming coefficient of the player, where 1 being default.
- The coefficient is calculated by extracting the max value from the `ACE_setCustomAimCoef` array, using the function `ace_common_fnc_arithmeticGetResult`.
- If the `ace_advanced_fatigue_swayFactor`, the value return by `ace_common_fnc_arithmeticGetResult` will always be based on the `ace_medical` calculation, since that is hard coded to always return at least 1.
- To get `ace_advanced_fatigue_swayFactor` to have any effect, the coefficient returned from `ace_common_fnc_arithmeticGetResult` needs to be modified by `ace_advanced_fatigue_swayFactor`.

This returns 1, even if `ace_advanced_fatigue_swayFactor` is set to say 0.25, because of the points laid out above:
https://github.com/acemod/ACE3/blob/ee4431980146091fa816b7b9da87dde6e3ca3094/addons/advanced_fatigue/functions/fnc_handleEffects.sqf#L98-L99

Maybe it's by design, maybe it's a bug.

If it's by design, `ace_advanced_fatigue_swayFactor` should have a range of 1-5, since it has no effect under 1 and is misleading.

If it's a bug, then the `ace_advanced_fatigue_swayFactor` should be applied after the coefficient has been extracted so it has an effect on the `setCustomAimCoef` command.
