### ISSUE TITLE
Fast Rope System

### ISSUE THREAD

**Issue by Sopa1** [acemod/ACE3#8439]
My request is simple, i had done make some test and notice that if you use a NPC pilot to fast rope, when you exit in the rope the pilot detects an obstacle, the solution to this is simple, if sets disableIA "PATH" to the heli pilot, this problem is solved, but, the NPC dont gona make the route if you dont set the path to enable. My solution to this is when the rope system is deployed, automatic sets the pilot path to disable and when you hide or  cut the ropes the path is enable again

**Comment by BaerMitUmlaut** [comment]
This already happens if you use the fastroping waypoint (although we use `MOVE`, not `PATH`). If you don't want to use that, it's the responsibility of the mission maker to provide his own fix. We cannot implicitly disable AI pathing in case the mission maker has some other plans.
