### ISSUE TITLE
Medical - Some aspects don't work Underwater

### ISSUE THREAD

**Issue by Saborknight** [acemod/ACE3#8440]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.5` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.6` [eg. 3.0.0 stable, commit hash]

**Description:**
Applying Bandages and Tourniquets don't complete. The medical menu shows, the bandage/tourniquet will start applying via the loading bar. As soon as the loading bar reaches ~90% it cancels out and the item is not applied. This makes using the medical system impossible underwater unless they can be loaded into an SVD... which you can't do with unconscious people though, as mentioned in https://github.com/acemod/ACE3/issues/5515#issuecomment-919487324

**Steps to reproduce:**
1. Go underwater with full diving kit and usual medical equipment (Bandages, Tourniquets, Wetsuit, Diving Goggles, Rebreather)
2. Get injured
3. Access medical menu and select injured part and bandage/tourniquet
4. Watch the progress bar work... then suddenly disappear
5. Check the medical menu, and see that nothing has changed

**Expected behavior:**
The injury to be bandaged as it would have been above ground

**Where did the issue occur?**
- Dedicated

**Log Files:**

**Additional context:**
Interestingly, drugs do apply though

**Screenshots:**

**Comment by Salluci** [comment]
Do the items get consumed?

**Comment by Saborknight** [comment]
Good question, I'll check

**Comment by Saborknight** [comment]
Whoops, I got the answer ages ago and never posted it here.

Yes, Doing this will indeed use up that bandage or whatever is used

**Comment by Drofseh** [comment]
It make sense that you can't bandage underwater, but imo the action should just not show.

**Comment by Saborknight** [comment]
Not entirely. You can still apply shit to your body no matter what environment you're in. 

And more crucially, being able to medic underwater is something that makes or breaks a potential underwater op. So many people in our unit have been hesitant about doing any underwater ops for the simple fact that medicine doesn't work. Picking up and putting an unconscious person in a vehicle doesn't work.

I've since managed to fix the unconscious deal on our side, and people had a great time doing shit underwater, but relied so heavily on lumping people into SDVs that it's difficult to work with.

**Comment by Drofseh** [comment]
My point is that a bandage soaked with water won't be effective at stopping bleeding.
A TQ should work just as well though.

**Comment by rautamiekka** [comment]
Tq only works with limbs, and a single wound in either the head or torso is enough to likely prevent waking up.

How about a compromise ? You'll have to spend way more, like 5-8x, more bandages for the same effect.

**Comment by johnb432** [comment]
This can be closed, as it was addressed in #9096.
