### ISSUE TITLE
Make the cellphone ring on the caller's end as well as the explosive's end

### ISSUE THREAD

**Issue by M-Davies** [acemod/ACE3#8441]
**Is your enhancement related to a problem?**
Somewhat. I would like there to be an audible notification of the phone ringing on the caller's side as well as on the receiver's side. Reason being is that it actually sounds like you're trying to be connected rather than just silence.

**Solution you'd like:**
A dial tone sound when calling an IED or other explosive device until the call ends and the receiver explodes. Optional request but would be cool if it was added: the sound is able to be heard by nearby players, so they know when someone is calling an explosive.

**Alternatives you've considered:**
Scripting/triggers. This is possible with some clever conditional statements but hard to do if you are not a programmer, it would be easier for non-technical users if it was shipped as part of ace.

**Comment by BaerMitUmlaut** [comment]
#3594
