### ISSUE TITLE
ACE UserInterface overrides "weaponInfo=1" on a dedicated server.

### ISSUE THREAD

**Issue by rowdy14HH** [acemod/ACE3#8446]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04` 
- **CBA:** `3.14` 
- **ACE3:** `3.13` 

**Description:**
Whilst having ace loaded (works fine in vanilla) on a dedicated server, I cannot seem to find a way to be able to have the hud face in and out. Instead it is either forced on, or forced off. I have tried resetting ace to default and it still does not work. Setting the allowselectiveui to false was supposed to be the fix, however this did nothing.

**Steps to reproduce:**

1. Set weaponInfo to 1(Fade) in your server difficulty config.
2. Load ace.
3. See that it does not fade. 

**Expected behavior:**
To be able to have the hud fade in and out.

**Where did the issue occur?**
- Dedicated 

**Log Files:**

**Additional context:**
Works on my friends server and yet I have even tried using his configs. However I have seen that someone made an issue report here about the same issue, and to my understanding they were not helped. 

**Screenshots:**

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
