### ISSUE TITLE
Advanced Fatigue - Recover stamina

### ISSUE THREAD

**Issue by igorpc1** [acemod/ACE3#8451]
**Is your enhancement related to a problem?**
Currently, after a long operations there might be a situation, that you physically cant run and the only solution for that would be suicide. It would be nice to have an item that recover lost stamina.

**Solution you'd like:**
With ACEX being merged with ACE, maybe food should recover stamina.

**Comment by severgun** [comment]
What? Just take a rest.

**Comment by BaerMitUmlaut** [comment]
You're probably running into this bug: #6163

**Comment by igorpc1** [comment]
I just thought that at some you wouldn't be able to regen any. Maybe I just can't read the code.

**Comment by BaerMitUmlaut** [comment]
Muscle damage does not regenerate, but it would only really have a big impact after playing for more than a day continuously.

There are three power reserves, with different supply and recovery speed and reserve size. If you deplete the slow recovery reserves, you will feel the impact of them and it will reduce your short term stamina, but I doubt that there ever would be a situation where you fully deplete them and you can't run anymore. Again, this would probably take multiple days.
