### ISSUE TITLE
Server/Mission Linked arsenals

### ISSUE THREAD

**Issue by Jerry442** [acemod/ACE3#8455]
**Is your enhancement related to a problem?**
My problem is just mission file size.

**Solution you'd like:**
I'd love a way to reduce my mission file sizes by having limited arsenals linked in some way to avoid repeats of the entire whitelist list being in the mission.sqm

A way I think this could be done is having an external config list that is bound to a name or identifier and if you ever set this identifier the arsenal would just load with that list of items. This would also allow units to just tell the zeus's to put that variable in and when on the server it would be linked instantly to an up to date limited arsenal.

**Alternatives you've considered:**
I've considered scripting an workaround, but unfortunately am not familiar enough with the language and your api to work out a resolution on my own.

**Additional context:**
N/A

**Comment by Salluci** [comment]
See https://ace3mod.com/wiki/framework/arsenal-framework.html. Create your limited arsenal on a dummy/hidden object, then create an interaction executing [`ace_arsenal_fnc_openBox`](https://github.com/acemod/ACE3/blob/07184dc763ee9d806b8539336bae6cd17db8115b/addons/arsenal/functions/fnc_openBox.sqf) with your dummy as `_object` param. Add that interaction to anything you want to have the same items as the limited arsenal.

**Comment by Salluci** [comment]
@jonpas could add `OBJECT` support to `ace_arsenal_fnc_initBox` so it passes other box as reference when creating the interaction.

**Comment by jonpas** [comment]
What happens if referenced box gets removed?

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
