### ISSUE TITLE
Version check script idling in scheduler during singleplayer.

### ISSUE THREAD

**Issue by NouberNou** [acemod/ACE3#847]
The script ace\addons\common\scripts\Version\checkVersionNumber.sqf is spawned in common post-init and idles in the scheduler as it waits for a non-existent server in single player.

**Comment by commy2** [comment]
Are you sure about that? The only `waitUntil` seems to be behind a `!isServer`.
I thought `isServer` is always true in SP.

https://github.com/acemod/ACE3/blob/master/addons/common/scripts/Version/checkVersionNumber.sqf#L63-L68

**Comment by commy2** [comment]
Can't reproduce.

I added some debug markers:
```
diag_log "0";
// Begin client version check
if (!isServer) then {
  // Wait for server to send the servers files and version numbers
  waitUntil {diag_log "1";
    sleep 1;
    !isNil "ACE_Version_ClientVersions" && {!isNil "ACE_Version_ServerVersions"}
  };diag_log "2";
```

But the RPT shows:
```
 4:59:17 [ACE] Full Version Number: 3.0.0.1
 4:59:17 [ACE] Server: ACE_Common is Version 3.
 4:59:17 "0"
EOF
```

No idling.

Am I missing something?

**Comment by NouberNou** [comment]
Woops, was looking at the wrong thing, this was another spawn, that has now been fixed.
