### ISSUE TITLE
Kill feed not showing AI kills at mission end

### ISSUE THREAD

**Issue by johnb432** [acemod/ACE3#8490]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06` profiling (broken on stable too, reported by friends)
- **CBA:** `3.15.6` workshop release
- **ACE3:** `3.13.6` workshop release

**Description:**
At mission end, the kill statistics show no AI kills (I haven't tested player kills) even if you have killed AI.

**Steps to reproduce:**
1. Place down 2x AI in editor, control one.
2. Shoot the other AI until dead.
3. Using the zeus interface or `endMission "END1"` end the mission.
4. See nothing in the kill feed.

**Expected behavior:**
The kills to show in the kill feed.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Log Files:**
- [Pastebin](https://pastebin.com/eU3Xz2tr)

**Screenshots:**
![20211007222531_1](https://user-images.githubusercontent.com/58661205/136457457-04fd0fca-ac8c-499c-bbc5-24e4d3723ecd.jpg)

**Comment by PabstMirror** [comment]
Will be fixed via #8397

**Comment by Brenner650** [comment]
This is still the issue in 3.14.1.65
Loaded CBA_A3 3.15.6.211004 and Ace3 3.14.1.65
Put single BLUEFOR and a single OPFOR unit in editor
Selected play in MP as BLUEFOR
Killed (not incapacitate) OPFOR unit.
Scoreboard still does not show kill.
![20211128110218_1](https://user-images.githubusercontent.com/41375066/143763674-080dc742-6d00-49e7-a8e5-e8185f7650bc.jpg)
