### ISSUE TITLE
I have to select AI one by one in ZEUS to change their posture and state.

### ISSUE THREAD

**Issue by setlef12341** [acemod/ACE3#8512]
**Mods: i use ZEN and CBA but i have turned both off and the issue still exists.

**Description:**
I need to select squads one by one to change their orders, posture or state.

**Expected behavior:**
Normaly i can select multiple squads and give them orders or change posture etc

**Where did the issue occur?**
In Zeus

**Comment by Drofseh** [comment]
Fill out the issue template properly please. Dont skip things.

**Comment by BaerMitUmlaut** [comment]
Maybe third time's the charm.
