### ISSUE TITLE
Categories for settings

### ISSUE THREAD

**Issue by Glowbal** [acemod/ACE3#852]
We are getting a lot of new settings and I forsee us adding more in the near future. With this huge list, it might be difficult to sort them all out for clients (and server admins using server export).

It may be useful to provide categories for our settings in the options menu, so clients only view a selected sub set, instead of the entire thing.

**Comment by commy2** [comment]
I fully agree.

The same could be set about the keyinputs.

**Comment by alganthe** [comment]
TBH, server export should also add a diary entry with each setting.

**Comment by esteldunedain** [comment]
> It may be useful to provide categories for our settings in the options menu, so clients only view a selected sub set, instead of the entire thing.

I agree; I'm not sure on how to make that as streamlined as possible though. Maybe just a new category entry inside the client settable classes?

**Comment by alganthe** [comment]
for medical settings it's perfect as it is in #861

**Comment by SilentSpike** [comment]
:+1: Was thinking this myself not long ago

**Comment by PabstMirror** [comment]
Closed By #2058
