### ISSUE TITLE
View Distance - Not returning to video settings

### ISSUE THREAD

**Issue by Mike-MF** [acemod/ACE3#8535]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06`
- **CBA:** `3.15.6`
- **ACE3:** `3.14.0`

**Description:**
Setting view distance using 0 for video settings does not switch if view distance has been set previously by ACE view distance.

**Steps to reproduce:**
1. Set Video settings view distance to 3000
2. Set ACE View distance to 1 (or whatever really.)
3. Set ACE view distance to 0

**Expected behavior:**
Should change to default video settings.

**Where did the issue occur?**
- Dedicated & Self-Hosted Multiplayer

**Comment by Whigital** [comment]
Fixed with https://github.com/acemod/ACE3/pull/9140 ?
