### ISSUE TITLE
Loading captives does not work

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#854]
built 2015-04-25:15:30 UTC+1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
none

**Description:**
Loading captives does not work, even if the function actually return true.

**Steps to reproduce:**
* place a player BLUFOR rifleman with "this setCaptive true:" in the init and call him unit1
* place a CSAT rifleman and call him unit2
* place a vehicle and call it vehicle1
* place an ammobox with cables ties
* restrain the CSAT rifleman and press escape
* type under one of the watch boxes
```
[unit1, unit2, vehicle1] call ACE_captives_fnc_canLoadCaptive;
```
try to escort the unit, check the value returned
try to not escort the unit, check the value returned
notice that you are unable to load the unit when you escort them even if you should.

also notice that you can call  "fnc_doLoadCaptive.sqf" and it actually does work, so I guess the text is just missing ?
**Where did the issue occur?**
everywhere, SP, MP, editor

**RPT log file:**
none

**Comment by PabstMirror** [comment]
Should be fixed, and you should be able to see the interaction points on the vehicle now while escorting.

**Comment by alganthe** [comment]
working like a charm, thanks for the fix.
