### ISSUE TITLE
RH M4 compatibility

### ISSUE THREAD

**Issue by jayjay213** [acemod/ACE3#855]
There are some M16 Versions that are not working with ACE at the moment. So far, i noticed all M16 Versions after M16A2 (A3, A4, Matech...) do not function correctly. You can't use magazines with the weapon and in virtual arsenal you also can't choose the weapon, because it is not in the list. And yes, i am using the optional rh m4 pbo. 

My first impression of ACE3 is really great! Lots of improvements compared to AGM. I like the new interaction system, but sometimes it gets a bit chaotic, especially when there is more than one body lying on the floor.

**Comment by alganthe** [comment]
use [this form](http://ace3mod.com/wiki/user/how-to-report-an-issue.html) to report issues.

**Comment by NouberNou** [comment]
Waiting for more info on if using compat pbo.

**Comment by ulteq** [comment]
I was able to reproduce the bug (using the optional ace_compat_rh_m4.pbo).
