### ISSUE TITLE
GME classnames in your GM Compat

### ISSUE THREAD

**Issue by sancron** [acemod/ACE3#8556]
I am pleased when changes or work from my project are adopted here in ACE.
https://github.com/vpzbrig21/gme

But I doubt that the GME classes in the CfgMagazines.hpp are useful, as they only work in conjunction with my modification. Since they were also written specifically for use with my modification.
https://github.com/acemod/ACE3/blob/master/optionals/compat_gm/CfgMagazines.hpp

Line 98 to 125 this code isn't necessary

**Comment by rautamiekka** [comment]
Doesn't hurt anything, does it ?

**Comment by sancron** [comment]
> 
> 
> Doesn't hurt anything, does it ?

It just doesn't make sense to have the GME classes in the code. Especially if you load GME, the ACE-Comp is redundant anyway. Because GME does the same as GM-ACE-Comp and more.

And without GME, the class makes no sense because it is not used. Since it was created specifically for a reconfiguration of the German Marder infantry fighting vehicle in the GME mod.

**Comment by sancron** [comment]
#7835 The two classes from my work are already present in this merge and only work with my modification.

Even if I look at the syntax of how things are structured in the configuration, some of the structure was simply copied from my work. At least it seems that way.
