### ISSUE TITLE
Wirecutting sound is not interrupted properly

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#856]
built 2015-04-25 at 18h

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
none

**Description:**
When wire cutting if you interrupt the action the sound doesn't get interrupted and play entirely/

**Steps to reproduce:**
* place a player unit
* get a wirecutter  
* start cutting a fence then interrupt the action (press escape)

**Where did the issue occur?**
SP, MP, editor

**RPT log file:**
no error there.

**Comment by PabstMirror** [comment]
Can't reproduce, do you have the latest version of ace (is it a 'power-saw' sound effect or many little clips)?

**Comment by alganthe** [comment]
power saw, going to do a fetch and rebuild just in case.

**Comment by commy2** [comment]
It is:
https://github.com/acemod/ACE3/blob/master/addons/logistics_wirecutter/functions/fnc_cutDownFence.sqf#L34

Haven't tested myself, but if you are hearing the old sounds, then you're having outdated files.
Make sure you disable file patching (-noFilePatching) if you have ACE3 unbinarized on your P:/ drive.

**Comment by alganthe** [comment]
I do have the exact same files but i'm still hearing the old sounds, file patching is disabled.
if someone else could try that would be nice.

**Comment by commy2** [comment]
Just tested it. I don't hear the old sounds anymore.

**Comment by PabstMirror** [comment]
Recommend deleting everything and rebuilding from a fresh download.
