### ISSUE TITLE
Add Peral's A10C and lala14's Targeting Pod (TGP)

### ISSUE THREAD

**Issue by cych** [acemod/ACE3#860]
Peral made a very good A10-C. it  works really well with the lala14's TGP feature for GBU12 laser guidance.  

Maybe ACE devs should make an agreement with these authors to integrate their work into the ACE 3 project.  

A-10C : http://www.armaholic.com/page.php?id=24582

TGP : http://www.armaholic.com/page.php?id=25763

**Comment by Glowbal** [comment]
Thank you for your request, but this a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
