### ISSUE TITLE
Wheel repair points on Stomper are offset

### ISSUE THREAD

**Issue by dedmen** [acemod/ACE3#8609]
The wheel repair points on the stomper are not at the center of the wheel.

The points are here:
![Arma3Retail_DX11_x64_bwMwcI08Ch](https://user-images.githubusercontent.com/3768165/138602899-690001a3-4e5f-4bcf-8c45-97a20c01db6b.png)

This is because
https://github.com/acemod/ACE3/blob/095fe2b874a090919986009be4bcf4d84c9f50bb/addons/repair/functions/fnc_addRepairActions.sqf#L55
selectionPosition returns the position of the first point in a selection.

The stomper wheel selections each have 16 points though, the correct wheel position would be the center of the wheel selection, but the script command only returns the first point.

selectionPosition command would need a alt syntax that returns the center of a selection with multiple points

P.S.: Please add BI's fault tag, I will add new syntax that returns center/bounding box of selections that will let us fix this properly.

**Comment by dedmen** [comment]
2.08 selectionPosition gets new parameter true/1 means center position of all faces/points in selection.

![Arma3NoOptInt_DX11_x64_AdEqkaISVz](https://user-images.githubusercontent.com/3768165/150993740-e0ccc10f-6b2f-46d4-adf1-cefd268f9a57.png)

**Comment by dedmen** [comment]
Not entirely sure about this syntax yet.


`stomper selectionPosition ["wheel_1_1", "HitPoints", 0];` (Default, first point in selection)
`[-0.774058,0.860854,-1.40365]`

`stomper selectionPosition ["wheel_1_1", "HitPoints", 1];` (Average of all points)
`[-0.597142,1.35486,-1.58345]`

`stomper selectionPosition ["wheel_1_1", "HitPoints", 2];` (bounding box of all points)
`[[-0.774058,0.860854,-2.07746],[-0.420225,1.84887,-1.08944]]`

**Comment by 654wak654** [comment]
Wouldn't making those parameters strings be better?

**Comment by dedmen** [comment]
![Arma3NoOptInt_DX11_x64_cJl9SsUaj2](https://user-images.githubusercontent.com/3768165/151151571-f3d5b1a2-feb5-4997-8f02-97f4d35867c1.png)


"FirstPoint", "AveragePoint", "BoundingBox"
