### ISSUE TITLE
Vehicle speed limiter not working correctly at low speeds

### ISSUE THREAD

**Issue by GeorgeBAS** [acemod/ACE3#8615]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06`
- **CBA:** `Latest stable`
- **ACE3:** `3.14 stable`

**Description:**
With the new speed limiter, at low speed (around ~10km/h) vehicle speed sometimes dip well below the set speed causing the vehicle to stutter

**Steps to reproduce:**
1. Open single player scenario
2. Place Badger IFV (Haven't tested with other vehicles, but has been reported to be happening with the puma via Commy2 on Slack)
3. Set speed limit to around ~10km/h
4. Hold drive forward key

**Expected behavior:**
Speed should max out at ~10km/h

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) 

**Screenshots:**
In the attached video you can see evidence of the bug. Despite holding W, the vehicle stutters between two speeds and engine RPM jumps like crazy

https://www.youtube.com/watch?v=CkH0FBUMMNs

**Comment by veteran29** [comment]
This might need BI Feedback tracker ticket, it looks like the PID controller used for the new command does not work well for small speeds.

cc: @dedmen
