### ISSUE TITLE
Make ACE full heal also extinguish the unit if on fire

### ISSUE THREAD

**Issue by Crowdedlight** [acemod/ACE3#8621]
**Is your enhancement related to a problem?**
Make the full-heal put out units on fire as well as heal them. This would make it possible for Zeus to actually heal units on fire and stop the fire. Currently, when Zeus healing they get healed and then instantly damaged by the burning. 

**Solution you'd like:**
Make the full heal function check if the unit is burning then put it out before healing. 

**Alternatives you've considered:**
Additional Zeus module to put out fires, but seems like overkill. 

**Additional context:**

**Comment by PabstMirror** [comment]
Closed by #8622
