### ISSUE TITLE
ACE RHS Compat should take into account ace_tracers presence.

### ISSUE THREAD

**Issue by VyMajoris** [acemod/ACE3#8627]
RHS configs define the tracer models for some reason. This is overwriting ace_tracers.

Would be nice if the ACE compact addon for RHS could work around this to enable ace_tracers for all RHS weapons.

@RHSUSAF\addons\rhsusf_c_weapons\config.cpp
 ```sqf
 
 class rhs_ammo_556x45_M855_Ball: B_556x45_Ball
	{
		model="\A3\Weapons_f\Data\bullettracer\tracer_red";
		cartridge="RHS_Cartridge_556x45_m855";
		hit=9;
		typicalSpeed=948.84241;
		airFriction=-0.00076000002;
		caliber=0.44;
		deflecting=21;
		visibleFire=3;
		audibleFire=7;
	};
 ```

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
