### ISSUE TITLE
You can be put on fire when standing next to burning unit even if allowDamage is disabled

### ISSUE THREAD

**Issue by Crowdedlight** [acemod/ACE3#8631]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06 stable`
- **CBA:** `v3.15.6.211004 stable` 
- **ACE3:** `master branch` commit hash: 08dff76  

**Description:**
If unit is set on fire and you stand close to it while "allowDamage" is set to false, you will still be put on fire after a moment. 

**Steps to reproduce:**
1. spawn 1 units and yourself as player. disable ai ``move/path`` abilities to avoid it running away
2. disable damage for yourself
3. Put one unit on fire, stand next to it
4. After the normal interval you will be put on fire and take damage

**Expected behavior:**
I expect that if damage is disabled the fire would not propergate and catch myself on fire. 

**Where did the issue occur?**
self-hosted multiplayer, if needed can validate on dedicated server. 

**Log Files:**
https://gist.github.com/Crowdedlight/6349771d7ea8036ae27b9c2d4e0ce5df

**Additional context:**
The fire propagation code does not take into account if damage is allowed on the unit its about to spread to.

**Comment by LinkIsGrim** [comment]
Fixed in #8632.
