### ISSUE TITLE
Add Azimuth, Charge, and Elevation to RHS Rocket artillery

### ISSUE THREAD

**Issue by grimsurgent** [acemod/ACE3#8636]
**Is your enhancement related to a problem?**
With the ACE Compats, most RHS artillery such as the M109 and 2S3 gets AZ, CH, and ELEV added so players can use them effectively if the computer is disabled. The BM-21 and the HIMARS don't have these, which makes them unusable with the ACE artillery table.

**Solution you'd like:**
Azimuth, Charge, and Elevation added to the RHS rocket artillery (BM-21 and HIMARS)

**Alternatives you've considered:**
Right now, they can only effectively be used by AI if computer is disabled.

**Additional context:**
2S3 with Azimuth, Charge, and Elevation
![](https://cdn.discordapp.com/attachments/460561001125773312/902776706803331092/unknown.png)
BM-21 without it
![](https://cdn.discordapp.com/attachments/460561001125773312/902776762214285332/unknown.png)

**Comment by johnb432** [comment]
Because we aren't in the `GUNNER` view (it's `INTERNAL`), it doesn't show the UI:
https://github.com/acemod/ACE3/blob/master/addons/artillerytables/functions/fnc_turretPFEH.sqf#L33-L35

**Comment by johnb432** [comment]
> I'll try to track down what is different in the rhs version

The difference between the RHS and CUP BM-21 is that the CUP variant has a gunner view (it's worth nothing, but it exists), whereas the RHS version has nothing.
