### ISSUE TITLE
Hand signals enhancement

### ISSUE THREAD

**Issue by Zigomarvin** [acemod/ACE3#865]
Hi, i've been invited to formulate my request here so here we go.

I posted few days ago a message on bis forum ACE3 thread talking about a THS Mod integration has a remplacement for the current hand signals system.

THS is a hand signals mod we've created ourselves in response to our needs and the lack of good quality mod about hand gestures. THS allows the player to execute quick hand signals made in the purpose of being recognizable and tacticaly efficient in most circumstances. THS uses keyboard shortcuts that lets you trigger hand signals in a fast and simple fashion, even at the heart of action.

Would you like to integrate THS to ACE3, as a remplacement of the current system. We would be thrilled to contribute to the ACE3 project and we would gladly work together with the ACE3 team to adapt THS to ACE3 specific needs, in technical terms as well as gameplay terms.

original message : http://forums.bistudio.com/showthread.php?190433-ACE3-A-collaborative-merger-between-AGM-CSE-and-ACE&p=2924847&viewfull=1#post2924847

**Comment by Zigomarvin** [comment]
link as requested : http://forums.bistudio.com/showthread.php?188817-Tactical-Hand-Signals-%28THS%29

**Comment by jokoho48** [comment]
i port this in my old Comunity for ACE3 and i could port this for ACE3 now officially

**Comment by gienkov** [comment]
Don't forget to change default keybinds - they conflict with weapon select
from ACE3.
10 sie 2015 20:36 "Joko" <notifications@github.com> napisał(a):

**Comment by jokoho48** [comment]
i know i had add it to the ACE menu

**Comment by gienkov** [comment]
Keybinds are faster IMO so they should be preserved too but changed to something like SHIFT + numbers.

**Comment by jokoho48** [comment]
i could add some but i think i let they free

**Comment by Pergor** [comment]
Overall the hand signals should be somehow accessible via keybinds rather than via the self interaction menu. It takes far too long to acces the hand signals this way.

**Comment by Zigomarvin** [comment]
Hi, glad to see that someone has taken the lead, I'm available again and would be happy to help. keybinds are primodiale, without her gestures are too difficult to use and end up in the dustbin. Have you integrated the tapshoulder too ?

**Comment by jokoho48** [comment]
shuolder tapping is allready in ACE included

**Comment by bux578** [comment]
@Zigomarvin If you have a better animation for the tapping, feel free to do a PR.

**Comment by Zigomarvin** [comment]
@jokoho48 as it already has getures but it suffers of the same problem, @bux578 to me this is not about the animation, this is about how the action is triggered, the interaction menu make it unusable, even more than for animations, should i make a new pr since shoulder tapping was also a part of the ths ?

**Comment by Glowbal** [comment]
Done with  #2219
