### ISSUE TITLE
ace_sitting doesn't work since ACEX migration into ACE

### ISSUE THREAD

**Issue by jannes-io** [acemod/ACE3#8654]
**Mods (complete and add to the following information):**
- **Arma 3:** `stable`
- **CBA:** `stable`
- **ACE3:** `3.14.0` stable

**Description:**
ACEX migration into ACE broke ACE_sitting.

**Steps to reproduce:**
Create a new mission, place down a chair, try to interact with it, sitting is not an option.

**Expected behavior:**
An option to sit down shows up like it did with ACEX

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

all of the above

**Log Files:**
irrelevant

**Additional context:**
Saw multiple people having this problem but no github issue yet so decided to make one.

`acex_sitting_enable` is set to `true` in cba settings.

**Comment by 654wak654** [comment]
Fix is already merged https://github.com/acemod/ACE3/pull/8577
