### ISSUE TITLE
Ace Capture have cooling weapon on same point with no weapon in hand

### ISSUE THREAD

**Issue by Sheppard85oc** [acemod/ACE3#8657]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.6` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.14.0` [eg. 3.0.0 stable, commit hash]

**Description:**
ACE Capture its on the same interaktions point with weapon cooling in the Interaktions Menu
So if you want capture a AI you have on the same point two "Options"

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. _Go to MP/Editor/Aktiv the ACE Capture modul place a AI with and No Weapons
2. _Click go to AI and try to Capture
3. _See you will see this point.

**Expected behavior:**
I think if you have a AI without weapon should not give the Option to Cooling a Weapon coz if weapon its the Option a bit otherplaced.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / 

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**
https://ibb.co/ngYpRQ5
https://ibb.co/frh5FmJ
https://ibb.co/nDjGYDB
https://ibb.co/mcdnbvr
https://ibb.co/FH1FKRH

**Comment by PabstMirror** [comment]
Fixed in #8617
