### ISSUE TITLE
ACE3 v3.14.0 for the first time the mod modularity is broken?

### ISSUE THREAD

**Issue by 211345082311111** [acemod/ACE3#8660]
- **Arma 2:06`stable`
- **CBA:**[stable version, Steam]
- **ACE3:** `3.14` [stable]

**Description:**

Good afternoon!
I don't know if this is a error or if this is an intentional solution, I hope you can tell me about it. Excuse me, if I am posting it in the wrong place.

I have been using ACE3 for many years, due to the modularity of this mod and the ability to disable PBO files that are not suitable for any reason for the specific gameplay of the Arma3 user. The flexibility - is the ACE3 feature that I have always appreciated the most, but in version 3.14, I first encountered a problem, that I never had before. 

Now, ACE3 user cannot disable PBO modules related to ACE3 medicine. Previously, in all versions of ACE3, I always moved medical files into another location and the mod worked fine, but now in version 3.14.0, I cannot disable medical files, with the "ace_medical" prefix.  If I will do this, then game will constantly report errors like that - the addon with name"X" requires medical addon "Y". Those. the new version has a dependency that was not there before. Then the game crashes.

I do not know what is the reason - a mistake or an intentional decision, but I have a request to bring back the ACE3 modularity  - this was a awesome feature! The flexibility of ACE3 (fine tuning and modularity) has always been a hallmark, please don't break your traditions, make your mod still modular as before.

**Steps to reproduce:**
Move all medical files with the "ace_medical_" prefix to another location and start the game

**Expected behavior:**
The mod should be independent of disabling specific modules (pbo-files), the basic modules should not have dependencies as it was over 8 years of life of Ace and Arma3. In all previous versions Ace3 I have often turned on/off various modules (not only medical) and have never seen a problem with this.

**Where did the issue occur?**
-  Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Comment by veteran29** [comment]
Some modules might depend on other modules. If you're removing ACE Medical components you also need to remove Fire component as it's dependent on it.

**Comment by 211345082311111** [comment]
> You also can't remove just one of the medical PBOs as they depend on eachother.
But who told you that I removed ONE medical PBOs? I've never said that. I said that before, I disabled ACE3 medicine by completely disabling all medical files

> Some modules might depend on other modules.
I know about this, but before Ace3 medicine was not related to such modules

> If you're removing ACE Medical components you also need to remove Fire component as it's dependent on it.
I do not understand what this is about? What are Fire Components?

**Comment by 211345082311111** [comment]
> We've never done any change to "it's modular" philosophy.

This is not true, there are words in the description of ACE3 that say otherwise. I remember reading this. Just don't make me look for this description, I still won't argue with you

**Comment by jonpas** [comment]
`fire` component depends on `medical_engine`. You must remove `fire` in order to remove `medical`.

**Comment by 211345082311111** [comment]
> fire component depends on medical_engine.

I disabled ace_fire but the game still told me that "ace addon killtracker required ace_medical" then I disabled "killtracker" and I was able to start the game
Thank you @jonpas ! 

Thank you guys all of you, I love ACE3 for your customization flexibility and modularity. The player can adjust this to suit his needs, keep your work!
