### ISSUE TITLE
Sitting down on chairs is gone

### ISSUE THREAD

**Issue by FloppyCDdrive** [acemod/ACE3#8661]
Since the merge from ACEX to ACE sitting on chairs doesn't work anymore :(
used to be a really neat feature.

**Comment by Whigital** [comment]
Already fixed with https://github.com/acemod/ACE3/pull/8577

**Comment by FloppyCDdrive** [comment]
nice, didn't find that post for some reason when searching^^ but then again haven't used github in quite some time.
But it's not pushed to steam yet?

**Comment by bux** [comment]
Correct. Needs a new release.
