### ISSUE TITLE
Disable Gamma boosting

### ISSUE THREAD

**Issue by KRDucky** [acemod/ACE3#867]
Can you implement an option in the ACE3 settings to block gamma boosting? Currently, anyone can gamma boost to remove the need for NVGs which makes a PvP mission unbalanced as hell. Maybe something that blocks attempts to change the gamma and brightness in-game. Like a preset to stock 0:0 setting.

**Comment by commy2** [comment]
http://acemod.github.io/ACE3/wiki/user/how-to-make-a-feature-request.html

**Comment by bux578** [comment]
Thank you for your request, but this a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html
