### ISSUE TITLE
Suppressor not influencing Muzzle Velocity

### ISSUE THREAD

**Issue by derl30n** [acemod/ACE3#8673]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06.148221`
- **CBA:** `3.15.6`
- **ACE3:** `3.14.0`

**Description:**
ACE3 Advanced Ballistics seem to not respect the presence of a suppressor when calculating muzzle velocity.
I've checked this via a script with and without using ace. Without ace, muzzle velocity is correctly influenced by the presence of a suppressor.

**Steps to reproduce:**
1. Launch Arma with only CBA and ACE3
2. Create a new mission and place a unit (with a suppressor already on the weapon)
3. Load the mission
4. Execute debugging code to get bullet exit velocity `[player, 1] execVM "evel.sqf";`
5. Shoot with suppressor
6. Remove suppressor
7. Shoot without suppressor (no difference in bullet velocity)
8. Repeat steps 2 to 7 without any mods (notice difference in bullet velocity from step 5 to 7)

**Expected behavior:**
When using a suppressor I'd expect the muzzle velocity to increase due to the suppressor extending the length of the barrel.

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Log Files:**
_on request as I see them not necessary_

**Additional context:**
<details>
  <summary>Debugging code (evel.sqf)</summary>

   ```sqf
   params
[
	["_shooter",objNull,[objNull]],
	["_maxLines",1,[1]]
];

_shooter removeEventHandler ["FiredMan", _shooter getVariable ["evelEhi",-1]];

if (isNil {_shooter getVariable "evelEhi"}) then {
	_shooter setVariable ["evelEhi", -1];
};
if (_maxLines isEqualTo 0) then {
	_shooter setVariable ["evelEhi", -1];
} else {
	evel =
	{
		params ["_round"];
		
		private _v = velocityModelSpace _round # 1;
		
		hint format ["projectile exit velocity\n%1m/s", _v toFixed 2];
	};
	
	private _ehIndex = _shooter addEventHandler ["FiredMan", {[_this # 6] call evel}];
	
	_shooter setVariable ["evelEhi", _ehIndex];
};
```
</details>

**Screenshots:**

|  | without any mods | with cba, ace and advanced ballistics |
| --- | --- | --- |
| without suppressor | 920 m/s![image](https://user-images.githubusercontent.com/1857322/141042480-1c58994f-3f57-4e35-ab2d-0cbb437507ba.png) | 774 m/s ![image](https://user-images.githubusercontent.com/1857322/141042636-7e1218fa-ba70-404a-8d1f-a14ebf6a2a98.png) |
| with suppressor | 966 m/s ![image](https://user-images.githubusercontent.com/1857322/141042262-820e37ab-170c-48a5-a880-5451355bad58.png) | 774 m/s ![image](https://user-images.githubusercontent.com/1857322/141042744-d9c2db70-f8e3-4d09-99d3-5be7feb80614.png) |

***My Settings:***

![image](https://user-images.githubusercontent.com/1857322/141043162-4ef78bc5-45a5-45cc-b808-80c530b07d2f.png)

![image](https://user-images.githubusercontent.com/1857322/141043265-8c3bde90-9435-4308-817f-713f5c92ea3a.png)

**Comment by Salluci** [comment]
This is intentional via the `ballistics` component which removes suppressors' effect on muzzle velocity. Whether that should be the case or not, would need to be discussed.

**Comment by derl30n** [comment]
***Issue***
There are different types of muzzle attachments which all serve a different purpose.
I am right now just focusing on the suppressor itself.


***Thoughts***
Oversimplified: the suppressor increases the barrels length and therefore gives the bullet more distance to accelerate, hence higher muzzle velocity. (the base game gets this right)

Imho removing effects of muzzle devices on muzzle velocity isn't a solution.

Taking a look at Escape from Tarkovs  muzzle devoice mechanics and physics to get some references.
Ofc realistic muzzle devoice mechanics are absolutely out of scope for this issue.

***Suggestion***
Use either the vanilla approach and use a performance factor for the muzzle device like the base game
or
try to figure out a more advanced system.

***Additionally***
Either way I'd start by adding a simple system like arma 3 vanilla system.

I've gathered some more data from the base game:
29 out of 37 barrel lengths which support suppressors modify bullet velocity with a performance factor of 1,05 the rest use a performance factor of 1,00.

<html>
<body>
<google-sheets-html-origin>

weapon name | velocity without suppressor in m/s | velocity with suppressor in m/s | supressor performance factor
-- | -- | -- | --
ak12 | 730,00 | 766,50 | 1,05
ak12 - gl | 730,00 | 766,50 | 1,05
aku | 572,00 | 600,60 | 1,05
car-95-1 | 970,00 | 1018,5 | 1,05
car-95 | 930,00 | 976,50 | 1,05
cmr-76 | 980,00 | 1.029,00 | 1,05
cyrus | 870,00 | 870,00 | 1
katiba | 900,00 | 945,00 | 1,05
katiba carabine | 820,00 | 861,00 | 1,05
lim-85 | 915,00 | 960,75 | 1,05
mar-10 | 915,00 | 915,00 | 1
mk1-emr | 940,00 | 987,00 | 1,05
mk14 | 850,00 | 850,00 | 1
mk18 | 850,00 | 850,00 | 1
mk20 | 900,00 | 945,00 | 1,05
mk20c | 820,00 | 861,00 | 1,05
mk200 | 920,00 | 920,00 | 1
mx | 800,00 | 840,00 | 1,05
mxc | 720,00 | 756,00 | 1,05
mxsw | 880,00 | 924,00 | 1,05
mxm | 920,00 | 966,00 | 1,05
navid | 785,00 | 785,00 | 1
pdw2000 | 420,00 | 441,00 | 1,05
promet | 840,00 | 882,00 | 1,05
prometmr | 900,00 | 945,00 | 1,05
protector | 375,00 | 393,75 | 1,05
rahim | 830,00 | 830,00 | 1
rpk-12 | 786,50 | 825,83 | 1,05
spar-16 | 800,00 | 840,00 | 1,05
spar-16s | 880,00 | 924,00 | 1,05
spar-17 | 900,00 | 945,00 | 1,05
spmg | 807,00 | 807,00 | 1
sting | 370,00 | 388,50 | 1,05
trg-20 | 840,00 | 882,00 | 1,05
trg-21 | 920,00 | 966,00 | 1,05
type 115 | 900,00 | 945,00 | 1,05
vermin smg | 280,00 | 294,00 | 1,05


</body>
</html>

**Comment by Drofseh** [comment]
I would support keeping the influence removed.

While suppressors can influence velocity irl, it's typically very small (0.1% to 1%), and it can be an increase or a decrease depending on caliber, barrel length, and the suppressor itself.

**Comment by severgun** [comment]
> Oversimplified: the suppressor increases the barrels length and therefore gives the bullet more distance to accelerate, hence higher muzzle velocity. (the base game gets this right)

At same time suppressor's job to reduce gas pressure via empty chambers, so acceleration will be less.

**Comment by jonpas** [comment]
But it can also provide more acceleration due to longer time spent under gas pressure. It all comes down to specific suppressor and load you are shooting.

**Comment by Drofseh** [comment]
> Actually less acceleration makes no sense, suppressor just let's gases expand slower, it can't make the bullet slower.

I was surprised by this as well, but I've watched a video of a guy shoot unsuppressed and then shoot the same ammo out of the same gun and have the velocity go down with a suppresor.

**Comment by jonpas** [comment]
But how did he measure it? You have to measure at the same distance. Maybe he measure at barrel end first and then at suppressor end (which is additional distance)?

**Comment by Drofseh** [comment]
> But how did he measure it? You have to measure at the same distance. Maybe he measured at barrel end first and then at suppressor end (which is additional distance)?

https://www.youtube.com/watch?v=D4GOf7BRw9Y

**Comment by jonpas** [comment]
Look at his table at 2:12, those results (for super-sonic ammo) are way too close together to come to any conclusion after only 3 shots. That's easily just measurement error.

**Comment by derl30n** [comment]
It really comes down to what kind of suppressor you use and what type of ammo and caliber.

Modern suppressors have a potential to increase muzzle velocity ~2 to 5% but it is also heavily dependent on which caliber and ammo type.

What suppressor are really great at is decrease recoil / make the weapon more usable.

**Comment by DJ-Reticuli** [comment]
Additional barrel length doesn't always increase muzzle velocity, and can even decrease it.  There is an optimal barrel length for a given round, twist used, and beyond this there can be rapid diminishing returns, no additional increase, or even regressing with worsening muzzle velocity.

If I recall correctly, I thought I heard that ACE gives no increase in muzzle velocity with normal suppressors, and a slight loss of muzzle velocity with stealth suppressors.

I'm curious what the blanket decrease in audibility by AI is for supersonic rounds when using suppressors.  I think this decrease should probably be more for normal suppressors, since thermal suppressors need to have some type of trade-off to account for whatever the heck they're doing, whether increasing overheating, jamming, audibility, or all of the above etc.

I personally already turn up ACE overheating consequences for suppressors.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
