### ISSUE TITLE
Punji traps causing no damage in MP

### ISSUE THREAD

**Issue by wjviant** [acemod/ACE3#8679]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06.148478` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.6` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.14.0` [eg. 3.0.0 stable, commit hash]

**Description:**
The SOG punji sticks only cause damage when the ammo is located locally to the player.  If it is remote, then a scream is heard, but no damage is taken

**Steps to reproduce:**
Launch a dedicated server and player client
Place down a punji pick via Zeus
Have the player walk on the pit

**Expected behavior:**
It is expected that the player is damaged, but they remain undamaged

**Where did the issue occur?**
When a player stands on a punji pit

**Log Files:**

**Additional context:**

**Screenshots:**

**Comment by Salluci** [comment]
Addressed in next release.

**Comment by PabstMirror** [comment]
bis example for the training mine
```
class Eventhandlers {
    class BIS_TrainingMine {
        AmmoHit="_this remoteExec ['bis_fnc_activateTrainingMine']";
```
Looks like it only runs where mine is local?  So we just have to send the event to other machines
