### ISSUE TITLE
Uncon. AI units still want me to "fucking cease fire" when shooting them

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#868]
ACE3 Version: 71f29466d71f8db944ffa7a5cd1a74798292304d

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* Medical set to advanced

**Description:**
AI talks even when unconscious.

**Steps to reproduce:**
* Place AI
* Shoot AI in the limbs till it gets unconscious
* Put more bullets into the AI's limb
* AI says sth. like "Fucking cease fire"

**Comment by commy2** [comment]
[_unit, "isUnconscious"] call EFUNC(common,muteUnit);
[_unit, "isUnconscious"] call EFUNC(common,unmuteUnit);

**Comment by commy2** [comment]
fix in https://github.com/acemod/ACE3/pull/872

**Comment by commy2** [comment]
@bux, please test te PR and report if it solves the issue.

**Comment by commy2** [comment]
PR merged.

**Comment by alganthe** [comment]
issue fixed, no more voices when you fire at downed ai or try to join the group of a downed ai.

issue can be closed

**Comment by commy2** [comment]
:+1: for NoRadio.PBO
