### ISSUE TITLE
Ace advanced vehicle damage / cookoff creates smoke pillar in wrong location

### ISSUE THREAD

**Issue by SEB556x45** [acemod/ACE3#8683]
Mods (complete and add to the following information):

    Arma 3: 2.06.148221
    CBA: 3.15.6
    ACE3: 3.14.0

Description:
Ace 3 cookoff creates an additional smoke pillars slightly in front of a vehicle when it is destroyed via cookoff
Smoke rises from the vehicle hull and from the gun (intended) but there is an aditional smoke source floating in front of the vehicle

Steps to reproduce:
place tank of ifv
destroy it to cause cookoff
a smoke pillar will be created ca. 1m in front of the vehicle

Expected behavior:
Smoke should rise from the vehicle hull and gun (intended)
Smoke should not rise from in front of the vehicle

Where did the issue occur?
When an armored vehicle cooks off, both vanilla and modded (RHS) vehicles are affected

Screenshots:
examples of the bug appearing when various vehicles cook of
as you can see there is an additional smoke pillar in front of the vehicle that should not be present
APC - smoke rises from gun and hull additional bugged smoke source in fromt of vehicle
![20211114164506_1](https://user-images.githubusercontent.com/94306849/141688615-7866fce8-daa0-412a-8646-cd3b20f78b09.jpg)
Tank - smoke rises from gun and hull and end of barrel - bugged smoke source half way down the barrel
![20211114163245_1](https://user-images.githubusercontent.com/94306849/141688629-67d8b59b-4a9b-4dac-a41d-e4e34005835b.jpg)
IFV -  smoke rises from gun and hull additional bugged smoke source in fromt of vehicle
![20211114163229_1](https://user-images.githubusercontent.com/94306849/141688632-43872418-449a-4da8-ad6d-c4121b2aea76.jpg)

**Comment by TheCandianVendingMachine** [comment]
The selections of the vehicles are configured wrong. The smoke is supposed to come out of the barrel and engine, but BI configured those selections wrong

**Comment by dedmen** [comment]
> but BI configured those selections wrong

I doubt that? probably using wrong selection name?
Whats the name of the selections?

**Comment by severgun** [comment]
Probably this
https://github.com/acemod/ACE3/blob/9c946727cce62913cf3ab0eb59e1b9521dbdd99d/addons/cookoff/functions/fnc_smoke.sqf#L22
https://github.com/acemod/ACE3/blob/d43cd8a4586075a6934b07c7dd0a3c0435d214b2/addons/cookoff/CfgVehicles.hpp#L21

**Comment by OssifragA3** [comment]
The problem seems to be within fnc_engineFire.sqf, the smokestack was gone after i removed this file.
