### ISSUE TITLE
ACE Sitting (in chairs) no longer working since ACEX integration

### ISSUE THREAD

**Issue by Rockfrog** [acemod/ACE3#8686]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06.148470`
- **CBA:** `3.15.6.211004`
- **ACE3:** `3.14.0.63`

**Description:**
Since ACEX integrated into ACE, sitting in chairs is no longer presented as an interaction option for stock games chairs such as **Land_CampingChair_V1_F**, **Land_CampingChair_V2_F**, **Land_ChairPlastic_F** etc.

Only the carry option is presented as an ACE interaction option.

**Steps to reproduce:**
1. Launch Arma with only CBA & ACE3
2. Create a new mission, place a unit and a selection of stock game chairs
3. Ensure ACE Sitting is enabled in Addon Options
4. Load mission
5. Interact with chair - no sitting option

**Expected behavior:**
Sitting option is listed as an interaction option; player can sit in chair.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Log Files:**
[sitting test log.txt](https://github.com/acemod/ACE3/files/7554459/sitting.test.log.txt)

**Additional context:**
Sitting worked fine under ACEX - literally broke with the integration into ACE.

**Screenshots:**
![carry_only](https://user-images.githubusercontent.com/13402860/142195783-3bbcb3e6-4d96-41d7-9511-b4de46fef7da.png)
![server_settings](https://user-images.githubusercontent.com/13402860/142195853-102fe52f-e53b-4251-9b22-24929ae426d1.png)
![mission_settings](https://user-images.githubusercontent.com/13402860/142195898-5ade6c2a-6928-47a9-b29b-e310bd1aeeea.png)

**Comment by bux** [comment]
Fix is already merged #8577
