### ISSUE TITLE
Towing underwater with weapon spawns infinte ropes and locks animation

### ISSUE THREAD

**Issue by FishAI** [acemod/ACE3#8689]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06.148470 stable` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.6 stable` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.14.0 stable` [eg. 3.0.0 stable, commit hash]

**Description:**
When attaching a rope to a sunk vehicle while swimming, the rope will attach fine. But when swimming towards the land, on the transition from swimming to walking,  the character will lock in its animation and become unmovable. The text field "Attaching Cancelled" will appear continously. Also ropes are spawning below the character continuously. At this point, only respawning can fix the issue.
This behaviour will only appear if the character has a main weapon.

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. Open a new mission in the Eden Editor
2. Spawn a vehicle on the water without crew, e.g. Polaris DAGOR, so it can sink on mission start below the water surface
3. Add a playable character with backpack and ropes, e.g. Rope 36.6m, in his inventory
4. Give the character a main weapon, e.g. Tavor TAR21
5. Start the mission, the vehicle will sink below the surface
6. Swim to the vehicle
7. Open the Ace Interaction Menu on the sunken vehicle
8. Select Interactions => Towing => Attach Rope
9. Left click on the vehicle to attach the rope
10. Swim towards the land
11. On the transition from swimming to walking the character draws his weapon and becomes animation locked. Infinte ropes are spawning below him.

**Expected behavior:**
If the rope is long enough and the character is reaching the land he can walk on land and attach the rope to another vehicle. He then can tow the sunken vehicle out of the water. The character should not get locked and ropes should not be spawning. Just like it does if the character has no main weapon.

**Where did the issue occur?**
- Dedicated Multiplayer, Singleplayer, Editor (Singleplayer)

**Log Files:**
https://gist.github.com/FishAI/68fef1c7aa1cafaf31a796743a4459e7

**Additional context:**
None

**Screenshots:**
1: Choosing rope to tow sunken vehicle
![1](https://user-images.githubusercontent.com/54666184/142620984-47e0558e-aae2-4952-91a0-aed8a3772f10.jpg)

2: Attaching rope to sunken vehicle
![2](https://user-images.githubusercontent.com/54666184/142620976-2996c443-06cf-4c86-8633-2005a1529fdb.jpg)

3: Animation locked position
![3](https://user-images.githubusercontent.com/54666184/142620982-5331b26e-a32e-4f44-876e-640709dde2c0.jpg)

**Comment by johnb432** [comment]
The issue of spawning infinite tow ropes seems to be fixed, as I cannot replicate the behaviour with the reproduction steps.

However, when you are swimming and you exit the water, it will cancel the towing - something that needs to be worked on.
