### ISSUE TITLE
ACE Range Card doesn't update when modifying humidity/barometric pressure

### ISSUE THREAD

**Issue by Yakavetta** [acemod/ACE3#8690]
Mods (complete and add to the following information):

    Arma 3: 2.06.148470 stable
    CBA: 3.15.6 stable
    ACE3: 3.14.0 stable 
    CUP Terrains Core: 1.17
    CUP Terrains Maps: 1.16
    Esbekistan: 12 Nov 2017 

Description:
Current ACE Range Card does not update when modifying barometric pressure/humidity in ACE Scope settings.  Most leave this as default of 0% relative humidity, and 1013.25hPA, however in some maps the humidity and barometric pressure changes significantly from default.  When changing these server, mission or client side, the range card does not update these values.  However, during troubleshooting, when you disable and re-enable ACE Ballistics in the ACE Ballistics menu, the range card does update.  

Steps to reproduce:

Open a new mission in the Eden Editor
Select a new mission with a map that has a significant pressure/humidity difference (I've been using Esbekistan, average pressure is 763hPA, humidity is ~65%
Add a playable character with a precision rifle and accessories, Kestrel 4500 and ACE Range Card
Start the mission
Open Kestrel, change screen to relative humidity, temp and barometric pressure
Open range card, note current range card is for 1013.25hPA
Close range card
Open Addon Options -> ACE Scopes, change humidity and barometric pressure to values noted
Close Addon Options
Re-open range card, note values do not change, but barometric pressure value in the top lines do change

Expected behavior:
When changing values in the humidity/pressure options in ACE Scopes, the range card should update

Where did the issue occur?

    Dedicated Multiplayer, Singleplayer, Editor (Singleplayer)

Log Files:
N/A, no errors produced

Additional context:
Two key notes:  After changing values in ACE Scopes, disabling ACE Ballistics in the Configure Addons menu, and re-enabling ACE Ballistics updates the Range Card

After further testing, I’m fairly confident the issue is in the “fnc_updateRangeCard” script.  Namely, where the private _cachedEntry = missionNamespace variable is set, it’s only set once and then all functions after that rely on isNil {_cachedEntry} in order to write the range card.  By clearing the {_cachedEntry} with a nil after the function is completed, it would enable players to adjust the barometric pressure and humidity and have those values show up in the range card

Also playing with this some more, I suggest changing the values in the ace_scopes pbo for barometric pressure, humidity, and default zero to not be “isGlobal” 2, but rather 0 by default in order for players to adjust their range cards in game. It’s in the initsettings.sqf.  Mission makers and server devs can still lock this as needed.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
