### ISSUE TITLE
Organize Whitelisted ACE Arsenal by Mod in Eden Editor

### ISSUE THREAD

**Issue by BeachheadARMA** [acemod/ACE3#8700]
**Is your enhancement related to a problem?**
When creating whitelisted ACE arsenals, it can be extremely time consuming to scroll through many different items, often leaving some items out or creating incompatibilities, etc.

**Solution you'd like:**
It would be nice if there were a way to sort by mod while creating the whitelist. As of right now there is no way to sort other than by category.

**Alternatives you've considered:**
No alternatives that I am aware of other than spending many an hour creating whitelisted arsenals.

**Additional context:**
Image attached to illustrate.
![image](https://user-images.githubusercontent.com/24300448/143178712-9b86c38f-19f6-40f2-974f-96f15d63ee26.png)

**Comment by rautamiekka** [comment]
Not to mention: the search box seen in the bottom left corner of that pic doesn't search the class names, which seriously limits its usefulness.

**Comment by johnb432** [comment]
> Not to mention: the search box seen in the bottom left corner of that pic doesn't search the class names, which seriously limits its usefulness.

This part has been addressed in #9040.
