### ISSUE TITLE
Include Safety Mode for Advanced Grenade Throwing

### ISSUE THREAD

**Issue by JamesTheClarke** [acemod/ACE3#8701]
**Is your enhancement related to a problem?**
In order to avoid accidental misfires or griefing at base in public servers we want to set limitations to the ability of players regarding firing primary or secondary weapons, UGLs, launchers and grenades. Currently however players can circumvent `ace_safemode_fnc_setWeaponSafety` (or similar methods) by using advanced grenade throwing because ACE just creates the grenade object and imparts momentum to it, the grenade is never "fired" from a `Throw` weapon of the player, like vanilla throwing would do. ACE advanced grenade throwing also doesn't have any weapon safety (like primary/secondary weapons do).

**Solution you'd like:**
A safety mode that can be enforced on all players via a function which we can use in scripts (for example tied to a specific trigger zone).

**Alternatives you've considered:**
Disabling advanced throwing, though that's a non-starter because of its immense usefulness.

**Comment by jonpas** [comment]
> he grenade is never "fired" from a `Throw` weapon of the player, like vanilla throwing would do

Correct, but if it's of any help, we do throw a CBA XEH `Fired` event you can use in addition of vanilla `Throw`.

> A safety mode that can be enforced on all players via a function which we can use in scripts (for example tied to a specific trigger zone).

You can use an ACE status effect `blockThrow` to block Advanced Throwing without disabling it.
```
[_unit, "blockThrow", "my_mod", true] call ace_common_fnc_statusEffect_set;
[_unit, "blockThrow", "my_mod", false] call ace_common_fnc_statusEffect_set;
```

I don't think hooking general weapon safety to grenades make sense, as that safety is meant to represent physical safety on guns, obviously, grenades don't have such a thing.

**Comment by JamesTheClarke** [comment]
Yeah I agree, physical safety for grenades is definetly not needed. Basically what I meant would be it would be nice to have a simple ACE function to call which would disable throwing any weapons or firing UGLs and Rocket Launchers without having to delete every bullet from every player weapon as that could interfere with custom mission scripts. But after talking to some of our coding guys internally I'm beginning to realise that this would be way harder to implement than I thought.

**Comment by commy2** [comment]
This is a massive rabbit hole.

**Comment by BaerMitUmlaut** [comment]
Closing this since blocking grenades can be done using jonpas' code and blocking bullets is imo out of scope.
