### ISSUE TITLE
Some players cant interact with some others

### ISSUE THREAD

**Issue by OnkelDisMaster** [acemod/ACE3#871]
ACE3 Version: 3.0.0.1 ( Master from 26.04.2015 15:00 GMT)

**Mods:**
* ACE3
* CBA
* TFAR
* BWMod
* RHS 
* HLC Weapons
* RH Weapons
* POMI PMC
* IslaDuala

**Placed ACE3 Modules:**
* Medical settings
* Treatment settings
* Rallypoint system
* Respawn system
* BlueForce Tracking

**Description:**
Some players have no interaction menu on some other players, but on objects. The players affected by this are completely random. After rejoining the server its sometimes fixed, but not for evey player.
These players can interact with themselves, and we made sure that everybody has the same version.

**Steps to reproduce:**
Were not able to reproduce this, because its completely random. Were just joining on our server, and some people cant interact.

**Where did the issue occur?**
MP on dedicated server

**Comment by commy2** [comment]
Please upload the RPT @pastebin.com and post the link.

**Comment by OnkelDisMaster** [comment]
which one? server, client or the client the problem is appearing?

**Comment by commy2** [comment]
All of them. Labled if possible.

**Comment by esteldunedain** [comment]
Duplicate of #516.

**Comment by OnkelDisMaster** [comment]
then lets close this since the other one is more up to date...

**Comment by commy2** [comment]
It's not. Please post the RPT.

**Comment by esteldunedain** [comment]
Yeah, no need to close it, but I'm almost sure it's a duplicate.

Apparently sometimes the interact menu either fails to init for some random class or somehow the corresponding variable is overwritten by an empty array. It happened to a comrade ofmine while we were testing, but I could not ever reproduce it myself. I looked at the code too but could not find any possible cause (besides init EH not firing, which shouldn't happen).

**Comment by commy2** [comment]
BW units are fully XEH comptible.

**Comment by esteldunedain** [comment]
I don't think this related to BWMod; in fact it happened to us using RHS, and others reported the same with vanilla units. I think it may be init XEH not working reliably or something wrong in our code.

**Comment by OnkelDisMaster** [comment]
Were using BWMod units and vanilla units....RPTs are coming later

**Comment by jaynus** [comment]
CBA may be missing an init on a unit or two still; this has happened in the past. Can you provide the full test mission, or the list of unit classnames?

**Comment by OnkelDisMaster** [comment]
https://onedrive.live.com/?cid=769EDA8293139C35&id=769EDA8293139C35%21130 is a test mission

**Comment by commy2** [comment]
Just placed everyone with

```
a = "configName _x isKindOf 'CAManBase'" configClasses (configFile >> "CFGVehicles");

_pos = position player;
{
    _pos = _pos vectorAdd [2,0,0];
    configName _x createUnit [_pos, createGroup west];
} forEach a;
```

Worked fine on everyone. Except that the init laged out on some of them. (They changed their hats when revealing them via right click). After that, no issues.

**Comment by esteldunedain** [comment]
> init laged out on some of them.

Isn't init supposed to happen on non-shed environments? Why would it lag? Maybe that's related

**Comment by OnkelDisMaster** [comment]
This code goes into init.sqf am i getting it right?

**Comment by esteldunedain** [comment]
> > init laged out on some of them.

> Isn't init supposed to happen on non-shed environments? Why would it lag? Maybe that's related

@jaynus, @commy2, @NouberNou 

I was checking the public slack conversation about this, and @OnkelDisMaster mentioned it was a bit more reproducible for the player which had the slowest machine. This, plus the lag @commy2 observed, make me think that we may be trying to run too many heavy init XEH on mission start, and maybe at some point CBA or Arma give up and some classes fail to be initialized. I can think of a few workarounds:

- Instead of compiling a separate interact menu for each CAManBase subclass just assume all CAMabBase children share the same actions (which is 99.999% true)

- On the init XEH during mission start, just collect all the classes that need menus and initialize them gradually on a pfh during the first few seconds instead of trying to do it all at the same time

- A bit more risky: make a workaround at runtime; if a player detects a nearby man without interact menu it should reinit it. It would break things if people manually removed all actions through API, but could work as a workaround.

Anyway, we may want to log init XEH on CBA and see if we can explain why the init XEH may be being dropped before it completes execution.

------------------

Unrelated to ACE, I've have observed a delay before init XEH executes during the startup of heavy missions. Is this by design on CBA? Is it the engine?

**Comment by commy2** [comment]
>Instead of compiling a separate interact menu for each CAManBase subclass just assume all CAMabBase children share the same actions

Sure. Makes sense.

I have no idea how CBA does init. I know that the loadout scripts for civilians are spawn'ed.

**Comment by OnkelDisMaster** [comment]
Alright I got a bit further....removing the Modules: BFT, Respawn System and Rallypoint system semms to fix it temporaryly

**Comment by commy2** [comment]
Weird. I don't see any connection between these and the interaction menu.

**Comment by OnkelDisMaster** [comment]
Also with these modules we got lags every 2 seconds.....i already stated that bug. This is getting fix by removing them either.

**Comment by commy2** [comment]
Please post the RPTs. It's impossible to say anything certain witout them.

**Comment by jaynus** [comment]
We may want to look into a delayed init system as Ed recommended. It could probably be used elsewhere anyways as there is a lot of post init operation that doesn't REALLY need to be exactly post init

**Comment by OnkelDisMaster** [comment]
*Client RPT*
https://gist.githubusercontent.com/OnkelDisMaster/de9a640c179687384d7b/raw/arma3_2015-04-26_14-19-51.rpt its a bit large but thats a whole afternoon and evening playing on our server

**Comment by commy2** [comment]
Now it gets interesting.
It seems that either your selection of mods or the mission itself is completely broken. Probably both.

I've told you this before and you didn't listen, but here we go again:
You should really think about what mods and scripts you use in your mission. The RPT is filled with errors and that to a point, that no one can guarantee that anything works at all.

It's not only the sheer amount of errors, but also the quality of them. For example.
>bis_fnc_rsclayer, bwa3_fnc_setkeydefault, CBA_fnc_defaultParam

All these are functions that are defined by BI's CfgFunctions config class. They are all not defined on your machine. I have no idea why that happens, but it is certainly not caused by ACE or CBA (or BWA3 for that matter). There is no guarantee that the units are initialized correctly.

>DragonFyre

Great Example. Remove. That. Immediately.
I'm sure that fixes 99% of your issues.

**Comment by commy2** [comment]
I'm for closing this issue. If someone can reproduce this with sane mods enabled, then we can always make another one.
Reason is that this never happened to anyone in my community since we are testing ACE.

**Comment by KoffeinFlummi** [comment]
That RPT is the Arma equivalent of a unicorn. There are things in there I have never seen before...

But this probably explains your issue:
```
18:50:23 File x\cba\addons\xeh\fnc_init_enum.sqf, line 47
18:50:23 Error in expression < (_this) select 4; ;

{
if (configName (_configFile/_x) != SLX_XEH_STR) then {
_>
18:50:23   Error position: <_configFile/_x) != SLX_XEH_STR) then {
_>
18:50:23   Error Nicht definierte Variable in Ausdruck: _configfile
18:50:23 File x\cba\addons\xeh\fnc_init_enum.sqf, line 47
18:50:23 Error in expression < (_this) select 4; ;

{
if (configName (_configFile/_x) != SLX_XEH_STR) then {
_>
18:50:23   Error position: <_configFile/_x) != SLX_XEH_STR) then {
_>
18:50:23   Error Nicht definierte Variable in Ausdruck: _configfile
18:50:23 File x\cba\addons\xeh\fnc_init_enum.sqf, line 47
18:50:23 Error in expression < (_this) select 4; ;

{
if (configName (_configFile/_x) != SLX_XEH_STR) then {
_>
18:50:23   Error position: <_configFile/_x) != SLX_XEH_STR) then {
_>
18:50:23   Error Nicht definierte Variable in Ausdruck: _configfile
```
et cetera.

One of those shitty mods probably managed to destroy the Extended_Eventhandlers class of CAManBase or something. As commy said, throw out JSRS, Blastcore, fix your missions etc.

**Comment by bux578** [comment]
http://ace3mod.com/wiki/user/how-to-report-an-issue.html
That's why we say:
> If you've found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using **only @cba_a3 and @ACE3 on a newly created mission**.

**Comment by commy2** [comment]
`compile preprocessfile "x\cba\addons\xeh\fnc_init_enum.sqf"`

```
{

private [
"_fSetInit", "_onRespawn", "_useEH", "_inits", "_i", "_t", "_name", "_idx", "_names", "_init", "_clientInit", "_serverInit",
"_cfgEntry", "_respawnEntry", "_scopeEntry", "_initEntry", "_serverInitEntry", "_clientInitEntry",
"_excludeEntry", "_excludeClass", "_excludeClasses", "_replaceDEH", "_replaceEntry", "_flatInits"
];



_fSetInit = {
private ["_cur"];
	private ["_idx","_init","_type"]; 	_idx = if ((if (isNil {(_this)}) then { false } else { (typeName ((_this))) == "ARRAY" })) then { (_this) select 0 } else { _this }; _init = (_this) select 1; _type = (_this) select 2; ;

_cur = _inits select _idx;
if (isNil"_cur")then{ _cur = [nil, nil, nil]; _inits set [_idx, _cur] };
_cur set [_type, _init];
};






_onRespawn=false;
_useEH = { if (_isRespawn) then { _onRespawn } else { true } };






_names = [];	
_inits = [];	


_excludeClass = SLX_XEH_STR;
_excludeClasses = [];
_isExcluded = { (_unitClass isKindOf _excludeClass) || {({ _unitClass isKindOf _x } count _excludeClasses > 0)} };

	private ["_configFile","_unitClass","_classes","_useDEHinit","_isRespawn"]; 	_configFile = if ((if (isNil {(_this)}) then { false } else { (typeName ((_this))) == "ARRAY" })) then { (_this) select 0 } else { _this }; _unitClass = (_this) select 1; _classes = (_this) select 2; _useDEHinit = (_this) select 3; _isRespawn = (_this) select 4; ;

{
if (configName (_configFile/_x) != SLX_XEH_STR) then {
_i = 0;
_t = count (_configFile/_x);
while { _i < _t } do {
_cfgEntry = (_configFile/_x) select _i;
_name = configName _cfgEntry;
_idx = _names find _name;
if (_idx < 0) then {


_idx = count _inits;
_names set [_idx, _name];
};

if (isText _cfgEntry && {(call _useEH)}) then {
_init = compile(getText _cfgEntry);
[_idx, _init, 0] call _fSetInit;
} else {

if (isClass _cfgEntry) then {
_scopeEntry = _cfgEntry / "scope";
_initEntry = _cfgEntry / "init";
_serverInitEntry = _cfgEntry / "serverInit";
_clientInitEntry = _cfgEntry / "clientInit";
_excludeEntry = _cfgEntry / "exclude";
_respawnEntry = _cfgEntry / "onRespawn";
_replaceEntry = _cfgEntry / "replaceDEH";
_excludeClasses = [];
_excludeClass = SLX_XEH_STR;
if (isText _excludeEntry) then {
_excludeClass = (getText _excludeEntry);
} else {
if (isArray _excludeEntry) then {
_excludeClasses = (getArray _excludeEntry);
};
};
_onRespawn = false;
if (isText _respawnEntry) then {
_onRespawn = ({ (getText _respawnEntry) == _x } count["1", "true"] > 0);
} else {
if (isNumber _respawnEntry) then {
_onRespawn = ((getNumber _respawnEntry) == 1);
};
};
_replaceDEH = false;
if (isText _replaceEntry) then {
_replaceDEH = ({ (getText _replaceEntry) == _x }count["1", "true"] > 0);
} else {
if (isNumber _replaceEntry) then {
_replaceDEH = ((getNumber _replaceEntry) == 1);
};
};
_scope = if (isNumber _scopeEntry) then { getNumber _scopeEntry } else { 2 };
if !(_scope == 0 && {_unitClass != _x}) then {
if (!(call _isExcluded) && {call _useEH}) then {
if (isText _initEntry) then {





_init = compile(getText _initEntry);
if (_useDEHinit && {_replaceDEH}) then {
[0, _init, 0] call _fSetInit;
} else {
[_idx, _init, 0] call _fSetInit;
};
};
if (SLX_XEH_MACHINE select 3 && {isText _serverInitEntry}) then {
_serverInit = compile(getText _serverInitEntry);
[_idx, _serverInit, 1] call _fSetInit;
};
if (SLX_XEH_MACHINE select 0 && {isText _clientInitEntry}) then {
_clientInit = compile(getText _clientInitEntry);
[_idx, _clientInit, 2] call _fSetInit;
};
};
};
};
};
_i = (_i) + 1;
};
};
} forEach _classes;

_flatInits = [];
{

if !(isNil "_x") then { {if !(isNil "_x") then { (_flatInits) pushBack (_x) } } forEach _x };
} forEach _inits;

_flatInits;
}
```

**Comment by OnkelDisMaster** [comment]
Alright im going to throw them out and report back afterwards...

**Comment by OnkelDisMaster** [comment]
So I removed everything that i dont need and this the new list of addons im using:

*TFAR
*BWA3
*CBA
*ASDG JR
*HIDDEN IDENTITY
*HLC (everythig except FAL)
*USP Patches
*RKSL Attachments
*RH M4
*RH Pistols
*RH ACC
*AlZab Mighty GAU8
*ASR AI
*Kimis HMD´s
*MRT ACC Fncs
*TAW View Distance
*XLA Fixed Arsenal
*Head Range Plus
*AiA Terrain Pack + IslaDuala + Panthera + Wake Island
*Dingo for A3
*JSJC FA18
*JSJC SU35
*Leights Opfor Pack
*RHS AFRF
*RHS USF

Does anyone see something that can conflict or cause the stated issues?

**Comment by Glowbal** [comment]
...

> http://ace3mod.com/wiki/user/how-to-report-an-issue.html
> That's why we say:

> >  If you've found an issue with ACE3 please make sure that ACE3 is really the cause of the problem. To do this try to reproduce the issue with using **only @cba_a3 and @ACE3 on a newly created mission.**

**Comment by OnkelDisMaster** [comment]
Yes I read that, and i will only report new issues that way, but I´m not playing Arma "only with CBA and ACE3" but thats another thing i guess.

**Comment by jaynus** [comment]
This would explain excessive init times. Btw, Kimis is in ACE and will conflict

**Comment by OnkelDisMaster** [comment]
Alright thats why i posted the list thaks @jaynus

**Comment by jonpas** [comment]
> but I´m not playing Arma "only with CBA and ACE3"

Most don't I guess, but that's not the point, the point is that ACE3 is such a large project it's impossible to make sure it works with every other tiny mod out there. It is up to the smaller mods to make it work with ACE3 (or in collaboration if issues come from ACE3) and not the other way around. That's why issues posted here should only be done by testing CBA and ACE3 only.

In fact, if compatibility was to be ensured with every tiny mod, there would be no ACE.
