### ISSUE TITLE
RHS Jerry Can WATER issues

### ISSUE THREAD

**Issue by Rockfrog** [acemod/ACE3#8710]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06.148470`
- **CBA:** `3.15.6.211004`
- **ACE3:** `3.14.1.65`
- **RHS: United States Forces:** `0.5.6`
- **ACE Compat - RHS USAF:** ` 3.14.1`

**Description:**
- **rhsusf_props_ScepterMWC_OD**  (RHS WATER jerry can OLIVE)
- **rhsusf_props_ScepterMWC_D**  (RHS WATER jerry can TAN)

How to carry items is unclear/misleading (regular drag/carry options do not appear), interactions are not consistent.

WITHOUT CHANGING item ACE Options in Eden:
1. Items are not pre-configured as 20L water holding items unlike other hydration devices (water bottles etc)
2. In order to carry RHS Water Jerry cans: ACE Interactions > Refuel > Take Fuel Nozzle ... is very confusing for grunts, not even Marines drink fuel :)
3. Cannot select any ACE water interactions

CHANGING item ACE Options in Eden to **Water Supply 20**:
1. ACE Refuel & Water interactions now overlayed on one another, requiring lots of mousing over to try and get the right interaction to pop depending on need to carry items (take **fuel nozzle**...), or utilise ACE water interactions.

**Steps to reproduce:**
1. Launch Arma with only CBA, ACE3, RHS USAF, ACE Compat RHS USAF
2. Create a new mission, place a unit and a Things>Tool>Jerry Can (Water)
3. Load mission
4. Interact with Jerry Can Water

**Expected behavior:**
1. Items should be pre-configured as 20L water devices without editting (as other water devices)
2. Carrying or dragging devices should be more logically accessed and named/titled
3. Carrying & water use interactions should not overlay in the same 'space'

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Screenshots:**
Stock items are not pre-configured water supply devices:
![107410_20211128141101_1](https://user-images.githubusercontent.com/13402860/143772296-c89698cf-c8de-4008-bbe6-941fa12a4514.png)

Carry devices is confusing/misleading:
![107410_20211128141029_1](https://user-images.githubusercontent.com/13402860/143772311-e6e33e6c-f010-48bc-837a-05054cafb2e2.png)

Adding 20L water:
![107410_20211128141112_1](https://user-images.githubusercontent.com/13402860/143772321-a652f087-6114-4d86-986a-f182438a6595.png)

ACE fuel device and ACE water device interactions overlaying on one another:
![107410_20211128141135_1](https://user-images.githubusercontent.com/13402860/143772348-18558814-d72a-4237-9fe5-09696877f7fa.png)

Repetitively mousing on and off can eventually get you to the Water Source options:
![107410_20211128141144_1](https://user-images.githubusercontent.com/13402860/143772368-114a18e3-83de-4b60-87c6-2c07ace65336.png)

Repetitively mousing on and off can eventually get you to the "carrying" options (take fuel nozzle):
![107410_20211128141152_1](https://user-images.githubusercontent.com/13402860/143772372-fb84c2eb-5302-49d0-ab23-0c3134f3c59a.png)

**Comment by Drofseh** [comment]
I'd recommend not adding fuel and water to the same jerry can (-1 fuel is infinite fuel iirc).

**Comment by Rockfrog** [comment]
-1 is disabled, -10 is infinite

For both fuel or water, per my screenies above.  At least according to the tooltip...

By default both fuel and water jerry cans are set to -1 disabled in both categories, however... the fuel jerry cans clearly have fuel in them.  You just can't check the fuel remaining, it's like they're fuel items without fuel.

**Comment by Drofseh** [comment]
Oh my mistake, I was thinking that -1 was both infinite and accidentally the default for that object.
