### ISSUE TITLE
Everytime I try to launch arma 3 through the arma 3 launcher, i get this error

### ISSUE THREAD

**Issue by CaptainBoockvar** [acemod/ACE3#8713]
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]

**Description:**

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. _Go to ..._
2. _Click ..._
3. _See ..._

**Expected behavior:**

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

File z\ace\addons\fortify\CfgVehicles.hpp, line 28: /CfgVehicles/: ‘(‘ encountered instead of ‘{‘
**Screenshots:**

**Comment by Drofseh** [comment]
please fill out the tempalte in full
