### ISSUE TITLE
Setting To Completely Destroy Vehicles After Cooking-Off/Burning

### ISSUE THREAD

**Issue by LuizBarros99** [acemod/ACE3#8715]
**Is your enhancement related to a problem?**
In a way it is yes related to a problem. In short the problem is the possibility to easily repair vehicles that have cooked-off/burnt (after the cook-off/burning ends)

**Solution you'd like:**
My suggestion is to completely destroy the vehicle after/once it cooks-off/burns. This would prevent the vehicle from being easily repaired.

**Alternatives you've considered:**
Some alternatives that I have considered relate to WHEN to completely destroy the vehicle. Alternatives are at the start of the cook-off, at the middle of cook-off, at the end of cook-off. These different alternatives could be considered to simulate the vehicle being damaged over time from burning/cooking-off, or even to simulate a sudden catastrophic ammo detonation.

**Additional context:**
This would simulate the vehicle being damaged beyond repair when cooking-off/burning, and would prevent it from being easily repaired.

**Comment by ZluskeN** [comment]
there is already a variable called `_detonateAfterCookoff` here: [https://github.com/acemod/ACE3/blob/9c946727cce62913cf3ab0eb59e1b9521dbdd99d/addons/vehicle_damage/functions/fnc_handleCookoff.sqf#L34](url)
However it seems the probability is too low to ever realistically happen. A good way to improve this could be to make this probability approach 1 with subsequent cookoffs (or even consecutive hits). 

Additionally, this line [https://github.com/acemod/ACE3/blob/f75bfd4cef3617c9de45b274e82a9841ed293f9f/addons/cookoff/functions/fnc_cookOff.sqf#L73](url) could be altered to use alternative syntax `setDamage [1, false];` to destroy the vehicle without triggering a Catastrophic kill effect if there is no ammo left to cook off/explode

**Comment by RufusVulpecula** [comment]
So, what would the line _detonateAfterCookoff needs to be in order for the cook-off to always result in a catastrophic kill?

**Comment by ZluskeN** [comment]
Well, you could just change it to `private _detonateAfterCookoff = true;` but that means the `detonationDuringFireProb` config entry of the vehicles will be bypassed entirely. Maybe this should be a user setting?

**Comment by RufusVulpecula** [comment]
I can try that, thanks. I believe this as well as a cumulative damage threshold for instant catastrophic kill should be an option. I admire the system for what it's trying to achieve but I don't think this implementation is the best way to go.

**Comment by LuizBarros99** [comment]
> there is already a variable called `_detonateAfterCookoff` defined here:
> 
> https://github.com/acemod/ACE3/blob/9c946727cce62913cf3ab0eb59e1b9521dbdd99d/addons/vehicle_damage/functions/fnc_handleCookoff.sqf#L34
> 
> However it seems the probability is too low to ever realistically happen.
> One way to improve this could be to make this probability approach 1 with subsequent cookoffs (or even consecutive hits).
> Additionally, this line
> 
> https://github.com/acemod/ACE3/blob/f75bfd4cef3617c9de45b274e82a9841ed293f9f/addons/cookoff/functions/fnc_cookOff.sqf#L73
> 
> could be altered to use alternative syntax `_vehicle setDamage [1, false];` to destroy the vehicle without triggering a Catastrophic kill effect if there is no ammo left to cook off/explode

Yeah, a setting to increase the chance of a catastrophic vehicle detonation with consecutive hits could be really interesting.
Basically right now I can keep firing Titan MPRL Compact ATs at an armored vehicle, and it will just refuse to suffer a catastrophic (ammo) detonation.
 Chances are that such top attack AT missile would eventually hit (unprotected) ammo, and this would eventually manage to detonate it (specially if there are still HE/HEAT/HEMP/MP shells inside of the vehicle).

Not to mention that the current situation also creates a problem of you not being able to use simple "alive _x" checks for a vehicle, as it is REALLY hard to completely destroy armored vehicles. And this can make it super hard to complete any objective that require the complete destruction of the vehicle.

**Comment by LuizBarros99** [comment]
Ah, and something that I even forgot to take into consideration is that cook-off does not seem to take into consideration if the ammo of a vehicle is protected or not (basically the simulation of blowout panels)
So it should still be reasonable to expect the vehicle to suffer a catastrophic ammo detonation during cook-off of unprotected ammo (specially if the vehicle still has a lot of ammo)

**Comment by jonpas** [comment]
This was released in 3.15.1 by #8734.
