### ISSUE TITLE
RHS FFV rockets have more drop than previously.

### ISSUE THREAD

**Issue by Vexmockingbird** [acemod/ACE3#8716]
**Mods**

- Arma 3: 2.06.148470
- CBA: 3.15.6.211004
- ACE3: 3.14.1
- ACE Compat - RHS USAF: 3.14.1
- RHS: United States Forces: 0.5.6

**Description:**
RHS FFV rockets (FFV441 HE, FFV502 HEDP, FFV751 HEAT) have more drop than the previous ace patch.  (Advanced ACE ballistics is turned off)

To hit a target using 'FFV751 HEAT' from 500m you have to range to 720m (roughly) 
To hit a target using 'FFV502 HEDP' from 500m you have to range to 1000m (roughly) 
To hit a target using 'FFV441 HE' from 500m you have to range to 720m (roughly) 

This happens to all MAAWS variations regardless of the sight it is using.

**Steps to reproduce:**

1. Open any mission/scenario (I used Virtual reality)
2. Equip a unit with any MAAWS from the 'Tanks DLC' and select and use any 'RHS FFV Rocket'
3. Range and fire at a target using any of the following rounds.
4. Specified rockets should fall short by 150m - 300m. 

**Expected behavior:**

- The FFV751 HEAT should be one to one regarding ranging, it shouldn't have any vertical drop off.
- The FFV502 HEDP should fall around 150m - 250m short of the range of a target (accounting for vertical drop off values that it had in the last patch of ace)
- The FFV441 HE should have similar values to the FFV502 HEDP. 

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) 

**Log Files:**
- https://gist.github.com/Vexmockingbird/0a961091a7a97b9282a770b6432c8601    (good chance the log isn't required)

**Additional context:**
The FFV rockets have a huge amount of increased drop off in the latest patch of ace. For example using the 'FFV502 HEDP' in the previous ace patch at a target 300 meters away you would have to range to 450m - 500m in order to hit it, however in 'ACE 3.14.1' the same exact rocket now requires you to aim for 700m (roughly).   

The previous patch's FFV502 HEDP behaviour has now been inherited by the 'FFV751 HEAT' in the current version.

I've read the ACE patch notes and nothing mentioning the weight or ballistic changes regarding RHS (unless I missed it), and RHS has not had an update recently prior to this bug report. 

Using the MAAWS at ranges more than 500 meters is almost impossible now, unsure if this in intentional or not.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
