### ISSUE TITLE
ACE nametag drawIcon3D parameter error when player controlled unit dies

### ISSUE THREAD

**Issue by GoldJohnKing** [acemod/ACE3#8719]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.6` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.14.1` [eg. 3.0.0 stable, commit hash]

**Description:**
After recent update (I believe it should be since 3.14.0), I got this error when player disconnect / lose connection / return to lobby, if the player's nametag can be seen by me (in draw range).
```
20:19:12 Error in expression <ctorAdd [0,0,(_heightOffset + .3)])];


drawIcon3D _parameters;
>
20:19:12   Error position: <drawIcon3D _parameters;
>
20:19:12   Error type any，string expected
20:19:12 File z\ace\addons\nametags\functions\fnc_drawNameTagIcon.sqf..., line 93
```

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. 2 players join into the server, and can see each other's nametag.
2. One player disconnect / lose connection / return to lobby.
3. Another player can see the error pops up, or can see the error log in rpt file.

**Expected behavior:**
The error should not happen. I believe I do not have the issue before ace 3.14.0 version.

**Where did the issue occur?**
- Dedicated

**Log Files:**

- Log too large, so I uploaded the zip here.
[Arma3_x64_2021-11-29_20-12-03.zip](https://github.com/acemod/ACE3/files/7631370/Arma3_x64_2021-11-29_20-12-03.zip)

**Comment by Vdauphin** [comment]
https://github.com/acemod/ACE3/blob/af86109c2b3c9ec05d134561cf99691b84c832ff/addons/nametags/functions/fnc_drawNameTagIcon.sqf#L37-L46
I am not entirely sure but if `_icon` is nil and `rank _target != ""` is false then `_icon` will be `nil` when called by `drawIcon3D`. This may trigger the error

A simple fix would be: https://github.com/acemod/ACE3/compare/master...Vdauphin:patch-5

I may try to test it next year
