### ISSUE TITLE
Grenade config does not change

### ISSUE THREAD

**Issue by OncE5053** [acemod/ACE3#8723]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06.148470` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.6.211004` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.14.1` [eg. 3.0.0 stable, commit hash]

**Description:**
was using well with changed config but after recent acemod update, config doesn't apply.

    class ACE_G_CTS9: ACE_G_M84 {
        GVAR(flashbang) = 1;
        GVAR(flashbangBangs) = 9;
        `GVAR(flashbangInterval) = 0.5 -> 0.25;`
        `GVAR(flashbangIntervalMaxDeviation) = 0.35 -> 0.05;`
        model = QPATHTOF(models\ACE_CTS_9bang_thrown.p3d);
        `explosionTime = 1.5 -> 1;`
        `timeToLive = 10 -> 8;`
        
this value is what i use for my team. after published, the values didn't changed, set back to normal value.

**Where did the issue occur?**
- ace_grenades .PBO CfgAmmo.hpp config edit

**Comment by severgun** [comment]
what is `requiredAddons[]` array in your `CfgPatches` section?

**Comment by OncE5053** [comment]
> 

oops i didn't check config.cpp file after update my bad. PROB SOLVED!
