### ISSUE TITLE
Medical AI not performing CPR, Infinit looping using an injector

### ISSUE THREAD

**Issue by Kusinagie** [acemod/ACE3#8724]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06.148470 stable` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.6 stable` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.14.1 stable` [eg. 3.0.0 stable, commit hash]

**Description:**
If a player or AI squad-mate go into cardiac arrest. The medic AI will perform their role in bandaging etc. Then they will get stuck in a loop injecting something (based on animation) and never perform CPR, until the cardiac arrest timer runs out. 
The injector of choice may be Epi, Diagnosing the downed soldier shows they are in pain the whole time so it must not be morphine. 

**Steps to reproduce:**
Create a new scenario with CBA and Ace loaded with three soldiers (one playable, another a medic, and a third of any). Play the scenario as single player or multi or even load it in a dedicated server (I tested all three ways). For ease turn  "AI Fatal Injuries" to Never so its guaranteed to go right into cardiac arrest then watch the medic.  

**Expected behavior:**
Medic should perform all necessary actions including CPR (Am I even correct in assuming Medic AI perform CPR?) 

**Where did the issue occur?**
- First noticed in a modded Scenario play-through on dedicated server, then tested with CBA and ACE only in Editor (Single player & Multiplayer) then tested the newly created test scenario on a dedicated server. 

**Log Files:**
Nothing new shows up in any log files. Is there a command I can use with further testing to show any useful debug info for this??

**Additional context:**
Advanced Diagnose, Medication, Bandages are all off (basic). I have tried with Advanced Diagnose with both enabled options with no difference.

**Screenshots:**

**Comment by Salluci** [comment]
`fnc_healingLogic` doesn't handle CPR treatment.
