### ISSUE TITLE
Lingering Battle SFX 

### ISSUE THREAD

**Issue by distractor2004** [acemod/ACE3#8725]
I am requesting a feature that would generate battle effects based that would be created due to high volumes of gunfire and explosives.

The inspiration comes partially from a feature in the Arma 2 SLX mod suite that generated lingering ambient dust based on the volume of gunfire in a certain area.

Further inspiration would also come from the smaller fire effects created by mods such as BlastFX and the Ace mod itself when a vehicle is destroyed.

I refer to the area that particles are determined to be generated as a Sphere Of Action, or SOA. The amount and lifetime of the particles would adjust for performance based on the size of a particular SOA and overall number of SOAs.

All particles would be attached to non-interactive objects, such as buildings, terrain, and wrecks, which will compliment any particles generated by interactive objects, such as vehicle engine smoke or ammo cookoffs already present within the Ace mod.

The fire particles would be visual/non-damaging only, while possibly only some of the dust would block the view, or be so thin that it is also just for visuals.

PARTICLE TYPES AND EXAMPLES OF USE:

All particle lifetimes and sizes would be based on the volume of gunfire in a short amount of time and small space or various types/multiple explosions.

Various amounts of lingering dust (volumetric maybe?) that varies in size and lifetime. The dust would be spread out between larger SOAs and be removed altogether or not generated at all from smaller SOAs if they are within the area of larger ones.

Lingering small fires and smoke pillars. These could be assumed created from single grenades or a high volume of bullets within a small are, and would also be the last lingering effects of HE explosions.

Large smoke pillars. These would be generated from heavy explosives, such as HE artillery and tank shells, IEDs, satchel charges, RPGs, or a high volume of grenades within a confined area such as an alleyway or interior.

Low volumes of non-HE gunfire below a certain caliber would not generate particles, so precision shots from snipers or single fire pot shots may not generate anything, but unloading an AR or MG, or even mag dump from an SMG, within a small area, or a single shot of large caliber incendiary/HE ammo could cause small fires and smoke. 

A high volume of non-explosive bullets from a fireteam may cause a small fire or two, but would definitely stir up dust around the area of impact.

SUGGESTED SCRIPT PARAMETERS AND USER CONFIGURABLE PARAMETERS:

Similar to other features in ACE, a user should be able to tweak various parameters that adjust between best performance and best visual quality. 

Some suggested parameters may include but are not limited to:

Lifetime of large smoke pillars.
Lifetime of lingering dust.
Lifetime of small smoke.
Lifetime of small fires.
Max amount of each effects generated.
Max amount of SOA's generated containing effects.
A flag or adjustment for maintaining a minimum amount of particles througout there respective max lifetimes within the combined number of SOAs.
An adjustment for dust density, density dissipation lifetime, and whether dense dust will affect AI visibility.

To maintain ambience when the maximums limits are reached, I think it would be best to reduce particles among all SOAs rather than just delete an entire SOA of particles, and that the highest volume of new particles would be generated within the newest SOA near a player or team. 

There should also be a prioritization of which and how many particle types are deleted first. Perhaps a method of prioritization would be for smaller/newer/nearer SOAs to take particles from larger/older/more distant SOAs, and for larger/newer/nearer SOAs to take particles from smaller/older/more distant SOAs.

EXAMPLE SCENARIO:

For example, let's say part of a town is shelled prior to a player's team moving in. The initial SOA, SOA1, would generate all types of particles, so there would be large smoke pillars, lingering dusk, and numerous small fires with there own small smoke pillars within the blast radius.

When the team moves into the village, they encounter an enemy team and a firefight ensues, creating SOA2. Some of the small fires from SOA1 are removed and concentrated into the smaller SOA2 created by the firefight due to bullets and grenades. The ambient dust dissipates from SOA1 while concentrating around the smaller SOA2.

At one point, an RPG is fired through the window of a house, creating SOA3. Depending on the amount and type of remaining particles in SOA1 & SOA2, the resulting explosion may borrow at least one smoke pillar from SOA1 and borrows some small fires/smoke first from SOA1 and then from SOA2,while adhering to the minimum lingering amount of particles in each SOA and overall.

The enemy then counter attacks with its own artillery over a much larger area of the town than occurred in SOA1, creating SOA4. The amount of particles generated by SOA4 require it to borrow from the prior SOAs. Due to SOA4 being larger and newer, it takes a few fire particles first from SOA3, then SOA2, and lastly from SOA1 if the SOA1's minimum has not been reached. Since the one smoke pillar generated in SOA3 is the minimum limit, SOA4 will either borrow from SOA2 or SOA1, or not generate another smoke pillar at all.

Due to SOA4 being the largest SOA, the ambient dust is spread out over SOA4 and merges with the radius of SOA1. Since the area of SOA1 & SOA4 encompass the areas of SOA2 & SOA3, then the dust would dissipate quickly in SOA2 & SOA3 due to the overlap.

SPOILER FOR NON-ACE MEMBERS, DO NOT READ THE NEXT PARTS IF YOU HAVE NOT PLAYED THE INFANTRY SHOWCASE OR MAIN STORY CAMPAIGN YET IN ARMA 3 

Some visualized examples of the feature would be at the end of the Infantry Showcase scenario in Arma 3, where you are tasked with fleeing from a village coming under heavy artillery fire. At one point, some of the houses start to emit scripted smoke pillars.

There is another example in the game, but I do not remember where it is located, in which you come across an FIA vehicle that has been ambushed. There are permanent small fires and smoke around the vehicles that remain there permanently.

Thank you for reading and I hope I was able to adequately explain my vision for what I believe could be a killer app feature within ACE. If there is any interest, I would be glad to further clarify any of the above details. I am not an expert coder, but I could possibly also create videos using the Arma 3 editor that could visualize the above scenario as well.

**Comment by Drofseh** [comment]
All feature requests must go in the feature request issue. #3594

**Comment by distractor2004** [comment]
Closing due to posting to wrong section of GitHub. Request is now properly posted to Comments of Feature Request and on ACE thread of BI Forums.

**Comment by distractor2004** [comment]
Thank you for the correction and I've closed the erroneous issue after
reposting to correct Feature Request comment.

Cheers!
