### ISSUE TITLE
SOGPF - SOGPF M576 Buckshot round in M79 40mm GL has the wrong trajectory when fired

### ISSUE THREAD

**Issue by bcrutc01** [acemod/ACE3#8730]
**Mods:**
- **Arma 3:** `2.06.148470`
- **CBA:** `3.15.6.211004` 
- **ACE3:** `3.14.1`
- **ACE3 Compat - SOG:** `3.14.1`
- **Creator DLC: S.O.G. Prairie Fire:** `1.1`

**Description:**
When firing a M576 Buckshot round from the M79 40mm GL (both round and primary weapon from the S.O.G. PF CDLC), the round is fired in a sharp upward trajectory rather than straight forward as observed when the CDLC is loaded without ACE3.

**Steps to reproduce:**

1. Spawn in as a unit equipped with the M79 primary GL + M576 Buckshot round loaded in the secondary ammunition slot
2. Change firing type to the M576 Buckshot
3. Fire the round forward (it is better observed when firing inside a roofed structure as you can see the impact of the buckshot land above)
4. Compare to behavior in the CDLC without ACE3

**Expected behavior:**
The buckshot round should shoot fire its projectiles forward, as observed when fired in the CDLC without ACE3 loaded.

**Where did the issue occur?**
- Editor (Singleplayer)

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
