### ISSUE TITLE
AtragMX bug - MuzVel table values increasing by one on every access of the page

### ISSUE THREAD

**Issue by Pipulci** [acemod/ACE3#8733]
**Mods (complete and add to the following information):**
- **Arma 3:** `Performance build - Build ID: 7855429 - Up to date as of 09/12/2021'
- **CBA:** `3.15.6.211004 stable'
- **ACE3:** `3.14.1 stable'

**Description:**
When setting up the AtragMX, in the Muzzle Velocity (MuzVel) table - if two entries are set at 10 and 15 respectively in the left column, AND the ir corresponding valures on the right column are exactly 5 units apart - the MuzVel values in the right column will each increase by 1 upon leaving and re-rentering the MuzVel screen.
The issue persists even if the entries are moved around, no matter what the value is on the right, as long as the left bears 10 and 15, and the right values are 5 units apart.

Video of the bug happening: https://youtu.be/9We3b6RnpuI

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

(Flowchart image missing, btw)
1. _Open the AtragMX ballistic calculator
2. _Click on Gunlist
3. _Click on Add New Gun
4. _Click on MV
5. _Click on the slot right of the entry '10'
6. _Set to a value n
7. _Click on the slot right of the entry '15'
8. _Set to a value n+5
9. _Click on Done
10. _Click on MV
11. _See that n and n+5 are now n+1 and n+6

**Expected behavior:**
The values in the right column all increase by 1 every time 

**Where did the issue occur?**
- Editor (Singleplayer) /ACE Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**
No additional context

**Screenshots:**
Video of the bug happening: https://youtu.be/9We3b6RnpuI

**Comment by Laid3acK** [comment]
Known bug with temperature xx.5°C: https://github.com/acemod/ACE3/issues/7117
