### ISSUE TITLE
Vehicles will only cook off once

### ISSUE THREAD

**Issue by R-moe** [acemod/ACE3#8736]
**Mods:**
- **Arma 3:** `2.06.148470 stable`
- **CBA:** `3.15.6.211004 stable`
- **ACE3:** `3.14.1 stable`

**Description:**
If a vehicle cooks off, then repair and rearm it, it will not cook off again.

If Enable ammunition cook off is active it can happen 2 things:
The vehicle cooks off, you can then repair and rearm it, if its hit again the vehicle won't cook off, but ther will be an ammunition cook off and the vehicle ammo and the ammo in the inventory will still be there. Some times the ammo cooks off at the same time as the vehicle.

or

There is an ammunition cook off, the vehicle ammo and the ammo in the inventory will still be there and the vehicle will not cook off again.

**Steps to reproduce:**
1. place a tank in the editor
2. shoot it until it cooks off, to get only an ammo cook off try to not hit any module in the vehicle, but its not reliable.
3. repair and rearm it
4.  shoot at it again

**Expected behavior:**
The vehicle should cook off as normal.

**Where did the issue occur?**
- Dedicated and Editor (Singleplayer)

**Additional context:**
I have seen it on vanilla and RHS vehicles. On dedicated it was tested with several mods and in a liberation. On editor the vehicles were repaired and rearmed with Zeus.

Edit:
Tested again on dedicated just with CBA and ACE, still happening. I don't know if i'm explaining the difference between vehicle and ammo cook off right.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
