### ISSUE TITLE
Bugs with mods

### ISSUE THREAD

**Issue by Arabic4512** [acemod/ACE3#8737]
![image](https://user-images.githubusercontent.com/85995110/145691996-7b7ae423-9fc6-4a88-b068-a30a41b120e7.png)
idk what hapening i have all mods

**Comment by Arabic4512** [comment]
i have actual versions for all but game is still show this up and i cant play

**Comment by Drofseh** [comment]
You need to fill out the issue template properly.

And why are you on Arma3 v2.02? Current game version is v2.06.

**Comment by commy2** [comment]
This is an issue tracker, not a support forum. I suggest you ask on the Slack.

**Comment by commy2** [comment]
> And why are you on Arma3 v2.02? Current game version is v2.06.

Because it's pirated.
