### ISSUE TITLE
ACE Volume Option to (not) Affect Music

### ISSUE THREAD

**Issue by Quailsnap** [acemod/ACE3#8738]
**Is your enhancement related to a problem?**
ACE Volume lowers music when I'd prefer it not. Plenty of operations lately using music, and when I use ACE Volume to turn down effects so I can hear the music, I can't hear either.

**Solution you'd like:**
CBA Setting for ACE Volume to not lower music. 

**Alternatives you've considered:**
There is already an ACE Common setting to prevent music lowering in ACE Hearing, but it is a server setting (and doesn't affect Volume).

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
