### ISSUE TITLE
Play Over And Over NonStop Error

### ISSUE THREAD

**Issue by LievreAI** [acemod/ACE3#8743]
hey guys i have strange error that i face with i have a sound that i want it to get play
its play nicely but i discover now that its repeat the sound once by one like nonstop
over and over its not even finish and yet its looping one by one 
if its help this is the mission ext file
and the module paramater in the game is

SOUND : siren
MINIMAL DISTANCE : 10
MAXIMUM DISTANCE : 170
MINIMAL DELAY : 3
MAXIMUM DELAY: 13
Follow Players : ENABLE
Volume : 600

**Comment by bux** [comment]
you deleted the template and don't provide the requested information
