### ISSUE TITLE
Wiki enhancement: List all unit traits/variables that can be used in scripting.

### ISSUE THREAD

**Issue by Radeni** [acemod/ACE3#8766]
Apologies for doing this trough github, I don't know of another way to contact the team.

I am working on a custom loadout menu and I'd like the loadouts to have ACE compatible roles.
It would be really convenient if there was a list/table on the wiki page that contains all of the varnames, what roles they represent and what are the possible values.
This is the documentation available for the repair framework but I can't find the same for Medics and EOD.
![image](https://user-images.githubusercontent.com/16863311/148396548-ff45c719-dcc3-4523-b47b-9aa11a305684.png)

**Comment by Drofseh** [comment]
#3594

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
