### ISSUE TITLE
Bug.Lameness without body damage.

### ISSUE THREAD

**Issue by NikkaKatajainen** [acemod/ACE3#8767]
Hello, I am from Russia and my English may be bad. I ran into such a problem. My character starts limping after hitting any part of the body. I tried to fix it in the "Add-Ons Settings" by disabling "Lameness". I limp absolutely without damage to my body or leg.
Here is a link to the video where this problem is shown: https://youtu.be/h0aF5uPhAUY

**Comment by rautamiekka** [comment]
> https://youtu.be/h0aF5uPhAUY

"This video has been removed by the uploader"
