### ISSUE TITLE
Controls & Respawn UI Disabled When Dead Body is Damaged

### ISSUE THREAD

**Issue by Punchington** [acemod/ACE3#8772]
**Mods:**
- **Arma 3:** `2.06` stable
- **CBA:** `3.15.6` stable
- **ACE3:** `3.14.1` stable

**Description:**
What I call "the overkill bug": when a player is killed and if their body takes further damage before they can respawn, their whole respawn UI will be closed, and all controls (with the exceptions noted below) are disabled.  This can affect both the host and any clients / other players on the server.  Server can be either a listen server hosted from the main menu of Arma, or a dedicated server.

The only controls that do not seem to be disabled are:
"/" for text chat
"," and "." to change channel
"y" to open the Zeus interface*

*note that, since the player is dead, the Zeus interface will immediately close; this does not fix the bug.

The only known solution is ALT+F4 and restart the game, which is not ideal when hosting a listen server.

**Steps to reproduce:**
   1. Open the Eden editor and create a MP scenario featuring at least one playable unit and some way to deal damage after force-respawn or death (i.e. another player's gun [a] or fall damage from ejecting from a helicopter [b]).
   2. Make sure to enable respawns on custom positions, selectable spawn position & inventory, but disable respawn counter.
   3. Set the respawn time to something reasonable (eg. 5 seconds) and place a respawn point for the side of the playable units.
   4. Host the scenario, either as a listen server or as a dedicated server.
   5. Select a playable unit in the role assignment screen.
   6. Start the scenario.

   7a. In the case of using another player to cause damage, force-respawn.
   8a. While dead and in the respawn menu, have the other player shoot at your corpse (ideally the torso or head).

   7b. In the case of using fall damage to cause damage, board the helicopter and get some altitude and momentum.
   8b. Once you're high enough and moving fast enough to be sure you will take a fatal amount of fall damage, eject from the aircraft.
   9b. Immediately force-respawn before you hit the ground (while still high enough to inflict fall damage).
   10b. Wait in the respawn menu until your body smacks the ground.
   
   Result: you will be "overkilled".  Might not happen every single time, but _very_ frequently - you're _lucky_ if it doesn't happen.

**Expected behavior:**
Taking damage while dead should have no effect; you should remain in the respawn menu, all controls still unlocked, and be able to return to the main menu or respawn, oblivious to your body taking further damage.

**Where did the issue occur?**
- Dedicated
- Self-Hosted Multiplayer

**Log Files:**
- https://gist.github.com/Punchington/c659204e723a30fd5fdc2f1a8f7dccc3

**Additional context:**
I've been using TADST to launch dedicated servers.

While my addon options / ACE settings are not their default values, I know this bug isn't very old; months ago I took a long break from Arma, and in that time I believe there may have been an update for ACE.  Upon returning to the game, with the same settings as before, this bug started occurring.  It's gone on long enough and no one else seems to have reported it.

Upon request I can provide my addon settings, especially if no one else is experiencing this bug and it's somehow my combo of settings causing this.  This bug has caused many sessions to come to a halt; I've made this GitHub account for this reason.

**Videos:**
https://youtu.be/cbRnzB44naw

**Comment by Salluci** [comment]
Does this only happen with damage after a forced respawn?

**Comment by Salluci** [comment]
Cause: dead units can still have their uncon state toggled if enough damage is applied. (Why?)

**Comment by Salluci** [comment]
Congrats, you found a big one.

**Comment by Punchington** [comment]
No, it doesn't need you to force-respawn, that's just an easier way to cause it as it skips unconsciousness.  For example, whenever one of my friends tries to "put me out" and accidentally shoots a couple rounds extra into me, they "overkill" me.

And sorry, I wasn't really sure where to find the versions, just used what I could find in the main menu.

**Comment by Punchington** [comment]
Fixed the version mix-up.

I also tried resetting my addon options to their default values last night, and found that the bug still persisted, so I don't think it's my custom combo of ACE settings..

**Comment by Salluci** [comment]
It's definitely in the project's end. A band-aid fix is easy enough, but I'm looking into the root of the issue to make sure nothing else like this pops up.

**Comment by Salluci** [comment]
Can you post an export of just your ACE Medical settings? Want to confirm a theory.

**Comment by Punchington** [comment]
Alright gimme a few minutes, I'll edit this comment with them.

**Comment by Salluci** [comment]
Good news and bad news.

Good news: this bug only happens when `ace_medical_statemachine_fatalInjuriesPlayer` is set to 0.

Bad news: above means fixing it will take a bit.

**Comment by Punchington** [comment]
Alright, I'll change that to 1 for the time being and will test it with a trigger-happy friend sometime soon to confirm if that works.

Do you want me to edit the post and add a "Workaround" section at the top for anyone else experiencing this?

**Comment by Salluci** [comment]
No need, as it doesn't cover all the possible cases of the bug happening. I'll make some time on the weekend to address this.
