### ISSUE TITLE
Bandage Treatment Time Coefficient

### ISSUE THREAD

**Issue by Punchington** [acemod/ACE3#8773]
**Is your enhancement related to a problem?**
ACE Medical settings cover a lot of stuff, **except** there is presently no way to adjust/customize the treatment time for bandages.  Meanwhile, every other treatment has time/coefficient settings; when trying to simplify the medical system for a scenario, bandages will remain the most time-consuming treatment when everything else can be set to take only a second.

**Solution you'd like:**
A slider-type setting for a bandaging treatment time coefficient available under the ACE Medical settings.

**Alternatives you've considered:**
Could have coefficients for each type of bandage - that way one can _kind of_ customize each type of bandage to some extent.  Not sure if that's necessary or worth the trouble, though.

**Additional context:**
I am aware that the bandage treatment time isn't fixed - it's based on injury.  From what I understand each bandage type also treats at different speeds and different amounts.  This is why a customizable coefficient would be nice, which is already present for others treatments and formulas (eg. the "Time Coefficient PAK" setting).

**Comment by severgun** [comment]
https://github.com/acemod/ACE3/discussions/8404

**Comment by DJ-Reticuli** [comment]
Very annoying, and recent changes to Ace also broke the mods to change the speed.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
