### ISSUE TITLE
Separate Player and AI Bleeding Coefficients

### ISSUE THREAD

**Issue by Punchington** [acemod/ACE3#8774]
**Is your enhancement related to a problem?**
Not exactly a problem with ACE itself, but a limitation for a mission maker's ability to control the difficulty of their scenario.

**Solution you'd like:**
Split the bleeding coefficient slider setting into two separate ones, one for players and one for AI.

**Alternatives you've considered:**
Two separate wake up chance settings, one for players and one for AI, would also help, though less preferable.

Both solutions together would be great if possible.

**Additional context:**
Since I host for a small friend group and we're going for a bit more of an "arcade" experience rather than a hardcore one, I've wanted to make unconsciousness a little more... "forgiving", as my friends would rather respawn than wait to be revived or wake up.

I've dramatically increased the _Unconscious Wake Up Chance_ and lowered the _Bleeding Coefficient_ by a lot, but now what happens is, while players are now more likely to wake up sooner (especially if one is still stable from an unconsciousness-inducing injury), this also applies to AI.

As a result, AI are frequently getting back up after being shot down as they aren't losing blood fast enough to not wake up.  While these changes have made unconsciousness a _little_ more "bearable" for my friends, it has also made the scenarios much, much harder than intended.  Such is why this enhancement would be much appreciated, as I could then make AI less likely to spontaneously wake back up with a vengeance.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
