### ISSUE TITLE
(UPDATE I figured it out, it is one of the mods) .FIRST TIME USING GITHUB ! Arma 3, Acemod giving error, "File ace_intelitems.pbo is outdated" whenever I try loading up with it. Have tried re-installing all the mods related to Ace. Repairing the mods via Arma launcher, downloading the mod off of their official website. I've looked at every thread I could find and nothing is working, ever PBO is up to date. And this just started happening after I installed about 40 or 30 mods, so that may be part of the problem.

### ISSUE THREAD

**Issue by DNRVAPORIZE** [acemod/ACE3#8783]
**Mods
- **Arma 3:** Downloaded from Steam (have mods downloaded on SSD and HDD).
- **CBA:** up to date, workshop version
- **ACE3:** up to date, workshop version
- Other mods but I have about 240 so it would be stupid to list them all.

Downloaded about 30 or 40 mods, went to play next day. And whenever I start up a scenario and try playing, it says "File ace_intelitems.pbo is outdated". Have tried deleting the pbo and other pbo's and each time it says the same thing but with another pbo (all of which do exist in the ace addons folder).

**Expected behavior:**
Wanted my game to work per usual.

**Where did the issue occur?**
- Singleplayer

**Log Files:**
https://gist.github.com/DNRVAPORIZE/8fd517f5518ef1617f27bf88e24d5dfd

![image](https://user-images.githubusercontent.com/97922581/149847429-b2df160d-75b2-4b6e-8830-455e224797d5.png)

**Comment by veteran29** [comment]
Please use the issue template.

**Comment by DNRVAPORIZE** [comment]
Sorry this is my first time using this so I will figure out how to do that

**Comment by PabstMirror** [comment]
make sure you are not subscribed to the old acex

**Comment by DNRVAPORIZE** [comment]
I do not think I am but how would I find that out

**Comment by DNRVAPORIZE** [comment]
https://gist.github.com/DNRVAPORIZE/8fd517f5518ef1617f27bf88e24d5dfd


that's the link for the RPT I believe

**Comment by DNRVAPORIZE** [comment]
> 

I know I am probably being annoying saying all this stuff, but how do I change the label to 'issue' ?.

**Comment by Salluci** [comment]
Holy title, Batman.

**Comment by severgun** [comment]
disable @OPERATION COBALT- The Walking Dead Addon For Ravage

**Comment by Whigital** [comment]
As @severgun pointed out, `@OPERATION COBALT- The Walking Dead Addon For Ravage` is bundeled with obsolete versions of ACE (`3.13.5`) and ACEX (`3.5.4`).

And my god that mod list and log file .... _Arma Life_ 🤦
