### ISSUE TITLE
ACE_player does not update when using remoteControl to take over AI, breaks when manually setting ACE_player

### ISSUE THREAD

**Issue by HelloThere91** [acemod/ACE3#8784]
**Mods (complete and add to the following information):**
- **Arma 3:** 2.06
- **CBA:** 3.15.6
- **ACE3:** 3.14.1

**Description:**
When using the remoteControl function/command without being set as a zeus, ACE_player continues to point at the original unit.  if ACE_player is manually set to the remote controlled unit it breaks ACE interaction entirely for that unit
**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. spawn 2 infantry units in the editor, set the variable names to "unit1" and "unit2" respectively
2. put `unit1 remoteControl unit2; unit2 switchCamera "internal";` into the init field of unit1
3. start the scenario as unit1
4. you should now be controlling unit2
5. shoot unit1, which will either cause you to go unconscious or receive an injury in your ACE menu.

**Expected behavior:**
ACE_player updating correctly when using the remoteControl command to take over AI without being set as zeus.

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Log Files:**
https://pastebin.com/mYckEPhj

**Additional context:**
-

**Screenshots:**
-

**Comment by PabstMirror** [comment]
Add
`missionNamespace setVariable ["bis_fnc_moduleRemoteControl_unit", unit2 ];`

**Comment by HelloThere91** [comment]
that works.
it's just important to set it back to nil before switching back to unit1, otherwise the exact same issue occurs, just with the roles reversed.
