### ISSUE TITLE
Have the MicroDAGR sharing waypoints list with other players.

### ISSUE THREAD

**Issue by Maxsword** [acemod/ACE3#8785]
**Is your enhancement related to a problem?**
No, It is not really a problem but it may help coordination among players in a very fast way.

**Solution you'd like:**
I'd like to have a dropdown menu showing the list of players to choose from with multiple tickmarks in order to share the waypoints. Also, have the possibility to choose e specific group.

**Alternatives you've considered:**
The only alternative is to keep doing this manually and each player uses its own MicroDagr.

**Additional context:**
A typical scenario: mission planning for aviation group, the group leader decides the route and target position all with waypoints and share the plan with others in one click in a real time-saving manner, for those vehicles able to import waypoints from MicroDAGR and in general very useful for everybody.

**Comment by Drofseh** [comment]
All feature requests go here: #3594

**Comment by severgun** [comment]
Also as much as I know IRL MicroDAGR does not have such option.

**Comment by BrettMayson** [comment]
This would something better seen in TFAR/ACRE, as radios are what provide data sharing for these kinds of devices

**Comment by Maxsword** [comment]
Why the issue was closed?

**Comment by rautamiekka** [comment]
> Why the issue was closed?

You were told the devices don't even have this feature IRL, and that TFAR/ACRE radios, if any, should be doing it.

_Personally I wouldn't mind going the fantasy route in this case if the Server can change a setting to allow it._

**Comment by Maxsword** [comment]
> This would something better seen in TFAR/ACRE, as radios are what provide data sharing for these kinds of devices

Well.. I don't think that some radio datalink through TFAR/ACRE will come up in the future, I'd stick with the ACE possibilities.

**Comment by Maxsword** [comment]
If I write here it means that I'd like to have it as an ACE feature. You are saying that it should be done by someone else (TFAR/ACRE).

**Comment by bux** [comment]
It was closed, because all feature requests have to go into this ticket here:
https://github.com/acemod/ACE3/issues/3594

**Comment by Maxsword** [comment]
All right, thank you for the explanation, Now I see the post on that page. The fact that it is still closed there is due to what reason? It is not going to be considered or what? Thank You in advance for the answer.

**Comment by bux** [comment]
Only speaking for myself here:
As the device doesn't have this functionality in real life, I wouldn't get my hopes up, that someone would add this feature. But this can be up for discussion.
Though, nothing is hindering you from adding this feature in your own additional mod alongside ACE.

https://github.com/acemod/ACE3/blob/master/addons/microdagr/functions/fnc_deviceAddWaypoint.sqf
Read the variable containing the waypoints from one player and save it on another player -> waypoints shared.
