### ISSUE TITLE
Improve DAGR rocket

### ISSUE THREAD

**Issue by CCRcmcpe** [acemod/ACE3#8787]
**Is your enhancement related to a problem?**
I think vanilla DAGR is unrealistic and underpowered. But ACE DAGR is inconvenient to add (and have some other problems).

**Solution you'd like:**
1. Make DAGR support Dynamic Loadout.
2. Enable mode select UI for DAGR launcher.
3. `6Rnd_ACE_Hydra70_DAGR` should be replaced to `7Rnd_ACE_Hydra70_DAGR`. Same for the other magazines. AFAIK US military don't use 6-tube rocket pods. And change the name to realistic ones, for example, `6 Round DAGR` should be `DAGR M423 LAU-131/A 7 Rounds`.

**Alternatives you've considered:**
Add a new addon named `dagr_rocket` (as `dagr` is already used) and move ACE's DAGR to the addon.
For compatity considerations `6Rnd_ACE_Hydra70_DAGR` can be preserved.

**Additional context:**
I referenced FIR's APKWS and `ace_hellfire`. FIR did a good job, except... they forgot to add this to the launcher:

```
        GVAR(enabled) = 1; // handle adding interactions and adding Laser Designator
        EGVAR(laser,canSelect) = 1; // can ace_laser lock (allows switching laser code)
        EGVAR(laser,showHud) = 1; // show attack profile / lock on hud
```

Which makes the APKWS have no mode select UI, however ACE's DAGR also lack this.
Also, according to [Wikipedia](https://en.wikipedia.org/wiki/Direct_Attack_Guided_Rocket), DAGR has LOAL capability.

**Comment by Drofseh** [comment]
Feature requests go in #3594

**Comment by CCRcmcpe** [comment]
> Feature requests go in #3594

Edited "Solution you'd like". My first thought is to add Dynamic Loadout capability to DAGR, forgot to mention it clearly. But it leads to a complex solution. Anyway, can't tell whether it's a enhancement or a feature request.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
