### ISSUE TITLE
RHS FN Minimi and it's Variants are based on the wrong parent class.

### ISSUE THREAD

**Issue by MacbainSP** [acemod/ACE3#8790]
**Is your enhancement related to a problem?**
FN Minimi and its variants should be open bolt guns.
The way they are currently set up make them cook off without being jammed.

**Solution you'd like:**
While checking out the overheating settings I found out that the FN Minimi and the variants based on it cook off despite not being jammed.
Upon further research I found out that they are wrongly based on the Rifle_Base_F class when instead they should be based on the Rifle_Long_Base_F class.
I want all FN Minimi and its variants be based on the Rifle_Long_Base_F class.
The fix should be to change ACE3/extras/CfgWeaponsReference.hpp 

    class R3F_Minimi: Rifle_Base_F
    {
        ACE_barrelTwist=177.8;
        ACE_barrelLength=347.98;
    };

Should be:

    class R3F_Minimi: Rifle_Long_Base_F
    {
        ACE_barrelTwist=177.8;
        ACE_barrelLength=347.98;
    };

**Alternatives you've considered:**
The CUP versions function correctly. I can use them, but the RHS ones are wrong. And that can't be.

**Additional context:**
You can see it is open bolt in this official US Army video at 1:33 https://youtu.be/BP-N1Dt9rGY?t=93
After racking the handle the bolt stays in the backwards position.
Also see this video where the open bolt section is linked: https://www.youtube.com/watch?v=NQSfFvaztdc&t=61s
This FAS article also describes it as being open bolt: https://man.fas.org/dod-101/sys/land/m249.htm

**Comment by MacbainSP** [comment]
The same goes for the MG42 in ACE3/optionals/compat_rhs_gref3/CfgWeapons.hpp

    class rhs_weap_mg42_base: Rifle_Base_F {
        ACE_Overheating_allowSwapBarrel = 1;
        ACE_barrelTwist = 305.0;
        ACE_barrelLength = 530.0;
    };

Should look like this:

    class rhs_weap_mg42_base: Rifle_Long_Base_F {
        ACE_Overheating_allowSwapBarrel = 1;
        ACE_barrelTwist = 305.0;
        ACE_barrelLength = 530.0;
    };

**Comment by Laid3acK** [comment]
The R3F config has a `R3F_Minimi` inherited from `Rifle_Base_F` since the beginning.
Changing with `Rifle_Long_Base_F` means UBC (Updating base class).
If you "want" something else, ask directly to the R3F team.

However, it's possible to fix that easy. I will make a PR, with also all correct `mass`.

**Comment by Salluci** [comment]
ACE3/extras/CfgWeaponsReference.hpp isn't used for anything. It's just a reference file.

Are you talking about RHS or R3F here?

rhs_weap_saw_base inherits from Rifle_Base_F in RHSUSAF. UBCs are bad practice. Same deal for the mg42.

**Comment by MacbainSP** [comment]
Thanks for your insights.
I just started today taking a look into the ACE structure. So I am not sure where those changes need to be made.
I "want" the RHS machineguns (FN Minimi, MG42) to work as intended - as open bolt guns.

Sorry that I can't be more helpful.

**Comment by Whigital** [comment]
Added a PR for the RHS LMG's, so only the R3F to fix @Laid3acK
