### ISSUE TITLE
Common cleanup & Modularity and PBO Structure

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#88]
Make stuff follow:
https://github.com/KoffeinFlummi/ACE3/wiki/Modularity-and-PBO-Structure

partially depends on https://github.com/KoffeinFlummi/ACE3/pull/63

My personal checklist:

- [x] ai
- [x] aircraft
- [x] attach
- [x] backblast
- [x] ballistics
- [x] common
- [x] difficulties
- [x] disposable
- [x] fcs
- [x] flashsuppressors
- [x] frag
- [x] interaction
- [x] inventory
- [x] laserpointer
- [x] lockbackpacks
- [x] magazinerepack
- [x] magazines
- [x] main
- [x] map
- [x] markers
- [x] missileguidance
- [x] movement
- [x] nametags
- [x] nightvision
- [x] noradio
- [x] optionsmenu
- [x] overheating
- [x] protection
- [x] ragdolls
- [x] realisticnames
- [x] recoil
- [x] reload
- [x] respawn
- [x] resting
- [x] safemode
- [x] scopes
- [x] smallarms
- [x] switchunits
- [x] thermals
- [x] vector
- [x] vehicles
- [x] weaponselect
- [x] weather
- [x] wep_dragon
- [x] wep_javelin

**Comment by commy2** [comment]
This issue covers disposable: https://github.com/acemod/ACE3/issues/17

**Comment by ViperMaul** [comment]
Looks like we are so close with this one. 
Status?

**Comment by commy2** [comment]
Nothing more to do here.
