### ISSUE TITLE
ACE Version 3.14.1 gets detected as a threat by the Microsoft Defender

### ISSUE THREAD

**Issue by Meiestrix** [acemod/ACE3#8804]
**Mods (complete and add to the following information):**
- **ACE3:** `3.14.1x` [eg. 3.0.0 stable, commit hash]

**Description:**
Sorry if this is not the right place for this error, but I couldn't find any report of this issue else were.
Right after the download of the latest ACE Version (3.14.1) from Github the download gets deleted, because the Microsoft Defender detects is as a threat. I an using Windows 10 with all latest Updates. A friend of mine has exactly the same problem.
Version 3.14.0 works without any problems.

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. Download the latest 3.14.1 release from github.
2. Click on downloaded file and see what happens.
3. With Chrome i dont even have to click the file.

**Screenshots:**
![image](https://user-images.githubusercontent.com/8461758/151433461-4857ccf3-d802-4b64-a87b-5ad42c9b9e45.png)
![image](https://user-images.githubusercontent.com/8461758/151434426-c9807251-dc6d-4c9e-9070-ba5bb6a214c4.png)

**Comment by bux** [comment]
Thanks for bringing this to our attention.

I've submitted a false positive report
![image](https://user-images.githubusercontent.com/1235520/151491957-708254e9-d397-45d2-bef0-55a307026261.png)

**Comment by LinkIsGrim** [comment]
Addressed.
