### ISSUE TITLE
Arma 3 ACE RHS - USAF compat 50cal turret CSW

### ISSUE THREAD

**Issue by DevotedLynx** [acemod/ACE3#8807]
**Mods (complete and add to the following information):**
- **Arma 3:** 2.06.148470 latest stable
- **CBA:** 3.15.6
- **ACE3:** latest stable steam workshop release
- **ACE3 - RHS USAF:** latest stable steam workshop release
- **RHS-USAF:** latest stable steam workshop release

**Description:**
emptying all the mags and ammunition on the m2 50cal turret does not allow loading crew served weapons

**Steps to reproduce:**
1 load vr with blank mission file
2 place in eden usa - army - w -> turrets -> m2 (aa) and a huron ammo and player (large enough bag for CSW 100rnd 50cal box)
3 ensure CSW in ace is enabled
4 mount turret and expend all mags to 0
5 pull 50cal box from CSW in huron ammo
6 attempt to load box (interaction missing when looking at the ammo box)

**Expected behavior:**
step 6 should show the interaction as it does if you were to remove the box before the initialised magazines run to complete 0

**Where did the issue occur?**
- singleplayer have seen happen on multi steps above verified in single after encountering in multi

**Log Files:**
https://pastebin.com/kW00KqjD

**Additional context:**
if you keep one bullet in the last mag and unload it using CSW unload then load a CSW belt you can run it to 0 and still get the load option issue only occurs running 0 on the weapons initialised mag.

**Comment by severgun** [comment]
I can not reproduce it.

**Comment by DevotedLynx** [comment]
I will provide a video and more screen shots

**Comment by severgun** [comment]
maybe specific CSW settings?

**Comment by DevotedLynx** [comment]
Are you sure your running the ammunition it spawns with to 0 rounds and 0 mags spare

**Comment by LinkIsGrim** [comment]
Can't reproduce.
