### ISSUE TITLE
Wind info is closed when open map

### ISSUE THREAD

**Issue by ilias-7565** [acemod/ACE3#8812]
**Description:**

When play, i use the map and the gauge. Having to press 2 keys each time to close a map, just doesn't let to play.

**Steps to reproduce:**
1. Open with "Show Wind Info (Toggle)" key .
2. Open map

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Comment by Salluci** [comment]
Needs by design tag, not actually a bug.

**Comment by ilias-7565** [comment]
Tracking open/close of map and restoring the last state ?

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
