### ISSUE TITLE
addMissionEventHandler always returns "_killed" as "side CIV" with ACE mod

### ISSUE THREAD

**Issue by HonzaVinCZ** [acemod/ACE3#8826]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06`
- **CBA:** `3.15.6`
- **ACE3:** ` 3.14.1`

**Description:**
During my mission making I noticed that my script that punishes players for killing civilians does not work as it is supposed to. I investigated it and setup a simple debug script;

> addMissionEventHandler ["EntityKilled", 
{
    params ["_killed", "_killer", "_instigator"];
    _instigator = _killed getVariable ["ace_medical_lastDamageSource", objNull];
    systemChat format ["%1 (%2) killed by %3 (%4)", name _killed, side _killed, name _instigator, side _instigator];
}];

The problem is that **with ACE** it always returns _killed as side CIV even though I turned off ACE medical AI unconsciouness and AI Medical completely with no effect. 

![20220220160711_1](https://user-images.githubusercontent.com/29098779/154849856-e13290d4-7c9e-4e4b-a135-970d8c5c7343.jpg)

**Steps to reproduce:**
Open editor, setup MP mission, add AIs of any sides, shoot them, see results. 

**Expected behavior:**
addMissionEventHandler _killed should return true side of _killed, not CIV.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Comment by severgun** [comment]
So why this is ACE issue if _killed entity passed by arma event handler?
It is fully repeatable in vanilla arma

**Comment by Vdauphin** [comment]
https://community.bistudio.com/wiki/side
> side of a captive or dead unit is [civilian](https://community.bistudio.com/wiki/civilian). Use [side]() [group](https://community.bistudio.com/wiki/group) _unit to get the underlying side (see Example 2)

Not a bug from A3 or ACE

**Comment by kymckay** [comment]
`side group _killed`

**Comment by HonzaVinCZ** [comment]
I see, thank you for explaining.
