### ISSUE TITLE
Surigcal Kit doesn't Work anymore

### ISSUE THREAD

**Issue by DerBro11** [acemod/ACE3#8829]
Hello,

Well, im Working on my MilSim Server and i cant use the Operation Kit,

My Addon-Options:
- Everyone can use the Kit
- Anywhere you can use the Kit

I treat persons that they doesn't bleed anymore but when i click at Advanced Treatment they doesn't show me Use Surigcal Kit

**Comment by Salluci** [comment]
Fill out the issue template you deleted and attach a rpt file.

**Comment by DerBro11** [comment]
Mods
- Arma 3: 2.06 stable
- CBA: 3.15.6 stable
- ACE3: 3.14.1 stable

Description:
When a Person is wounded, i treat them that all wounded Body Parts are Blue, then i try to use the Surigcal Kit but i can't choose it because the Medic Menu doesn't show me this option.

Steps to reproduce:
1. Make a Person wounded
2. Go to the Person and Open the Medical Menu(or directly at the Person)
3. Treat the Person that all wounded Body Parts are Blue
4. Try to use the Surigcal Kit

Expected behavior:
i expec that i can use the Surigcal Kit

Where did the issue occur
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsena

RPT File:
[Arma3_x64_2022-02-24_13-39-53.txt](https://github.com/acemod/ACE3/files/8132652/Arma3_x64_2022-02-24_13-39-53.txt)

Addon Options:
[Addon-Options.txt](https://github.com/acemod/ACE3/files/8132660/Addon-Options.txt)

Scre
![20220224141108_1](https://user-images.githubusercontent.com/62098210/155530488-f332dcc0-0ba3-4a49-9bf6-c661a3eee923.jpg)
enshot:

**Comment by rautamiekka** [comment]
Did you patch his torso or either leg, since the legs are blue ? If either leg, then show a screenshot after clicking the one you patched.

**Comment by DerBro11** [comment]
![20220224151937_1](https://user-images.githubusercontent.com/62098210/155541568-30592b94-0ec9-4771-a51c-3435337417c3.jpg)

**Comment by Salluci** [comment]
`ace_medical_treatment_advancedBandages` is set to 1. Stitching is only needed when it is set to 2.
