### ISSUE TITLE
Incorrect Hellfire missile model

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [acemod/ACE3#8830]
Mods (complete and add to the following information):

Arma 3: 2.06.148470 latest stable
CBA: 3.15.6
ACE3: latest stable steam workshop release
RHS USAF
RHS USAF ACE COMPAT
Description:
Ace Hellfire model on RHS AH64 is wrong
screenshots:
![20220225145728_1](https://user-images.githubusercontent.com/88520881/155669305-a4619c99-daad-48a3-be10-997f44492ff5.jpg)
![20220225145738_1](https://user-images.githubusercontent.com/88520881/155669313-ceeed35b-1b9e-409a-9075-c5725b09cbc3.jpg)
![2-image-AGM-114-Hellfire-II](https://user-images.githubusercontent.com/88520881/155669522-55a5db9a-eb4e-4a45-b366-280a12f4ba34.jpg)

**Comment by acknowledge14** [comment]
Maybe someone good enough can make model proxy mods like UAS did.
[UAS-CUP Vehicle Proxy Patch ]https://steamcommunity.com/sharedfiles/filedetails/?id=2433763326
[UAS-RHS Vehicle Proxy Patch] (https://steamcommunity.com/sharedfiles/filedetails/?id=2433826261)

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
