### ISSUE TITLE
Armor Kill not showing in score.

### ISSUE THREAD

**Issue by HBO1705** [acemod/ACE3#8831]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06` stable
- **CBA:** `3.15.6` stable
- **ACE3:** `3.14.1` stable

**Description:**
In score armored vehicles kills are not updated when using ACE3. Apparently the mod is making the own vehicle the killed unit and the killer, in Killed EH or EntityKilled mission EH. Other types of vehicles such as planes and cars (categorized as soft vehicles) works as intended.

**Steps to reproduce:**

1. _Create a mission (Multiplayer)_
2. _Try to destroy any armored vehicle in one shot with launcher (I used the AWC Nyx)_
3. _Check the scoreboard (did not changed)_

**Expected behavior:**
Return the right killer param on Killed EH, not the entity that was destroyed.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer

**Log Files:**
- None.

**Additional context:**
- This problem was found when i tried to get the unit that destroyed a tank.

**Screenshots:**
- The result of the Killed EH on armored vehicles. (Nyx is killer and Nyx is killed)
![image](https://user-images.githubusercontent.com/83477377/155768150-5b9bab2e-926e-4467-a1fa-607cc8a11406.png)

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
