### ISSUE TITLE
ACE 3 Rangecard dont show any info

### ISSUE THREAD

**Issue by FerHuaiqui** [acemod/ACE3#8836]
**Mods (complete and add to the following information):**
- **Arma 3:** `3.14.1`
- **CBA:** `v3.15.6.211004`
- **ACE3:** `Version 3.14.1`

**Description:**
I can't use the range card when using the ArmA editor or when using the Virtual Arsenal, but when I join an online game, on my clan's server, it works perfectly.

The issue is the distance card does not show the information, I am going to upload some screenshots so that it is better understood, and if necessary, a video.

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. Go to Virtual Arsenal on main menu.
2. Equip a rifle and rangecard.
3. Use self interaction menu to open the rangecard.
4. The range card don`t show any information.
5. Other: Go to single player.
6. Go to the editor.
7. Select a map.
8. Put a playable infantry element.
9. Put a Game Director from the Zeus modules.
10. Double click on the module.
11. Go to Default Addons and select "all extras" (including unofficial ones).
12. To accept.
13. Start the stage.
14. On stage: Incia Zeus.
15. Select from the ACE Utility module: Update Editable Objects.
16. Put it near your character and hit accept.
17. Select from the Zeus module: Arsenal.
18. Put it on your character, the virtual arsenal will open, equip it with the range card.
19. Close the Zeus and try to open the range card with the self-interaction menu.
20. The range card does not show any information.

**Expected behavior:**
just make it work properly.

**Where did the issue occur?**
-Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- [download RPT archive](https://www.mediafire.com/file/wmxwlo2mycyv0ud/Arma3_x64_2022-03-05_22-17-24.rpt/file)

**Additional context:**

**Screenshots:**
[The problem.](https://i.imgur.com/8qMxdfs.jpg)

Please tell me if you need more information or archives, i dont speak in english and i dont know about gist or pastebin, sorry,.

**Comment by Salluci** [comment]
You haven't enabled Advanced Ballistics locally.
