### ISSUE TITLE
SOG Compat - SOG statics from backpacks cannot be disassembled

### ISSUE THREAD

**Issue by GeorgRavioli** [acemod/ACE3#8837]
When you use the SOG PF backpacks to assemble any static weapon (using weapon base backpack and e.g. M2 mortar backpack), you can assemble the static weapon with the backpacks, but cannot disassemble it back into the backpacks. You can only disassemble it into the ACE CSW pieces.

I realize this may be intended function, but I would like to avoid using the giant brown bags for carrying any static weapon.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
