### ISSUE TITLE
Ammo calibre mislabeled (RHS AFRF, ACE3 & COMPATS)

### ISSUE THREAD

**Issue by Zelinskie** [acemod/ACE3#8843]
Mods : ACE3, ACE3 RHS AFRF Compat, RHS AFRF

**Mods (complete and add to the following information):**
- **Arma 3:** `2.08` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash], No clue but most recent one
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash], again no clue but most recent one

**Description:**

It's not that much of a bug, just that the 2b14-1 "Podnos" mortar in RHS AFRF W/ ACE & ace compat for it, has a mislabeled ammo caliber as 155mm instead of the correct caliber of the mortar which is 82mm

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. _Go to virtual arsenal / anywhere where you can get a 2b14-1 "podnos" mortar
2. _Click on "gunner" seat of the 2b14-1 "podnos" mortar
3. _See top right corner caliber as 155mm instead of correct 82mm

**Expected behavior:**
n/a, 
**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
All
**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
n/a, since its a minor issue
**Additional context:**
N/A
**Screenshots:**
![image](https://user-images.githubusercontent.com/101350046/157707338-06113cb6-085d-46e8-bb01-923eead72dda.png)

**Comment by Salluci** [comment]
Fill out version info properly (can be found in main menu by hovering over the mod icons on the lower left) and provide classname for the mortar and ammo used, please.

**Comment by SkippieDippie** [comment]
The problem is still present with those versions:
- **Arma 3:** `2.10 stable`
- **CBA:** `3.15.8 stable`
- **ACE3:** `3.15.1 stable`
- **RHS AFRF:** `0.5.6 stable`
- **ACE3 - RHS AFRF Compat** `3.15.1 stable`

The classnames of the mortaars are:
`rhs_2b14_82mm_msv`
`rhs_2b14_82mm_vdv`
`rhs_2b14_82mm_vmf`
their parent is `rhs_2b14_82mm_Base`

The ammunition used is labeled as _'HE 3VO18'_ (the magazine classname should be `rhs_mag_3vo18_10`, can't be sure).
I can recreate the issue if you need me to.

**Comment by Mike-MF** [comment]
Far as I can see ACE or RHS compats don't actually change the `displayNameShort` property to do this. I also haven't downloaded RHS to test. My guess is it's like this with standard RHS as the issue doesn't state otherwise.
