### ISSUE TITLE
ACE_compat_RHSUSAF: RHS249 over_heating_cookoff behaves as "closed bolt" instead of "open bolt".

### ISSUE THREAD

**Issue by CidKiron** [acemod/ACE3#8845]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.08.148892` stable
- **CBA:** `3.15.6` stable
- **ACE3:** `3.14.1` stable
- **RHS:USAF** stable, from workshop
- **ACE_COMPAT_RHSUSAF** stable, from workshop

**Description:**
regarding oveheating cookoff, any RHS M249 behave as "close bolt" as an M4A despite it operating as "open bolt" in reality, like the M240.

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_
1. _Fire any RHS M249 until cookoff starts. Usually 600 rounds is enougth_

**Expected behavior:**
Any M249 should behave as the M240, as both operate from an "open bolt".
No matter the temperature, cook off should not occur except when a missfire happens (bullets is placed into the barrel but not fired).
In this tipe of weapons which operates from an open bolt, the bullet is not placed into the chamber until is going to be fired.

Instead it behaves as an M4A1, which operates from a closed bolt.
When above certain temperature, cook off happens, as if the bullets are sistematically being placed into the chamber before being fired, and consecuently exposed to the barrel heat.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
All of the above

**Log Files:**
(No error apears as it is a config problem)

**Additional context:**
[ACE3](https://github.com/acemod/ACE3)/[addons](https://github.com/acemod/ACE3/tree/master/addons)/[overheating](https://github.com/acemod/ACE3/tree/master/addons/overheating)/[functions](https://github.com/acemod/ACE3/tree/master/addons/overheating/functions)/fnc_getWeaponData.sqf
line 82
private _closedBolt = getNumber (configFile >> "CfgWeapons" >> _weapon >> QGVAR(closedBolt));

I guess "closedBolt" ACE variable is set to TRUE for RHS M249 instead of FALSE

**Screenshots:**
No info

**Comment by CidKiron** [comment]
Thank you very much.

**Comment by Whigital** [comment]
ref: https://github.com/acemod/ACE3/issues/8790

**Comment by LinkIsGrim** [comment]
Fixed in #8793.
