### ISSUE TITLE
Update Towing with disableBrakes

### ISSUE THREAD

**Issue by Cathode88** [acemod/ACE3#8846]
**Is your enhancement related to a problem?**
Towing is currently extremely slow and only viable for getting unstuck.

**Solution you'd like:**
Add support for [disableBrakes](https://community.bistudio.com/wiki/disableBrakes) added in 2.08.

**Comment by jonpas** [comment]
That is automatically done with the towing SQF commands. Make sure you use it properly, attach the cable to the towing vehicle first, then to the towed vehicle.
