### ISSUE TITLE
Map - Ability to add vehicles to the BFT system

### ISSUE THREAD

**Issue by Zman6258** [acemod/ACE3#8847]
**Is your enhancement related to a problem?**
ACE BFT is an excellent tool for helping command elements coordinate troop positions, but binding the tracker to groups can often make things almost too game-y and reduce a squad's need to actually read the map and figure out their position on it. This can also lead to problems when a vehicle crew is embedded with a squad, such as an infantry section and an APC as part of the same group having only one BFT marker on the group leader.

**Solution you'd like:**
It would be nice to have a vehicle-based BFT mode, where a mission maker can designate certain vehicles as having a blufor tracker, allowing that to show up on the map instead of a group. This would also passively help with keeping track of vehicles after dismounting. Some way for a group to add a tracker "on the fly", in the case of replacement vehicles or commandeered enemy equipment, would be helpful but not necessary as long as there's some way for mission makers to script their own solutions for adding the necessary variables to vehicles on the fly.

**Alternatives you've considered:**
An alternate BFT mode isn't explicitly necessary, as long as there's some method for adding objects/vehicles to the BFT system. That way, a mission maker can simply disable the BFT for infantry groups and assign it to vehicles, or even allow vehicles and groups to both have a tracker.

**Additional context:**
N/A

**Comment by BaerMitUmlaut** [comment]
#3594
