### ISSUE TITLE
interrupt-able gun reloading without penalty.

### ISSUE THREAD

**Issue by john681611** [acemod/ACE3#885]
I'm not sure if you could do this but it would be awesome if you could.

IRL: reloading any gun with a magazine or belt has a few separate steps that go into reloading:
Extract empty mag (or open feed if belt)
Load new mag or belt
(belt only) feed belt into gun
Cock or release bolt catch (some guns don't need this)

If it where allowed to stop at each of these stages it means I could start reloading, quickly switch to my secondary to deal with something then switch back and continue the process. Just a idea from a gun nut that has died allot because he keeps interrupting a reload.

**Comment by alganthe** [comment]
feature requests go to #414
