### ISSUE TITLE
Aligning mapTools with current compass heading does only work for vanilla compass

### ISSUE THREAD

**Issue by b-mayr-1984** [acemod/ACE3#8851]
The mapTools feature of aligning the tool with the current compass heading does only work if the player is equipped with a vanilla compass (`'ItemCompass'`). 

- In case you are playing with the GM DLC this will not work because it uses a different compass (might cause problems with other DLCs as well).
- A vehicle gunner with powerful optics but without a compass equipped does also not get the option to align the map tool with himself (which doesn't make sense IMHO).

So the AND condition in below mentiond LOC does more harm than good. **I recommend to remove it.** The only damage being done in doing so is that infanterists and low tech vehicle gunners with map tools but without a compass (who does that anyways) will be able to align the map tools with their own heading.

https://github.com/acemod/ACE3/blob/d1353713198720fda42a134d6d1a6e23e4c4d4c2/addons/maptools/CfgVehicles.hpp#L55

Let me know what you think. I can remove it since I am currently already working on mapTools, but I want to hear your feedback first.

**Comment by b-mayr-1984** [comment]
Some more info compass names of GM. 
![image](https://user-images.githubusercontent.com/76476468/159017364-f7a12c54-abbc-4c2d-b589-8436506043bd.png)

**Comment by Salluci** [comment]
Can check for presence of item in `assignedItems` maybe?

**Comment by b-mayr-1984** [comment]
> Can check for presence of any item in specfic `assignedItems` slot maybe?

I already tried that. The problem here is that the lack of a compass is not indicated by an `""` or `null`. Instead the array is skipping over the entry that would be taken by a compass.

I've discussed this with @diwako. He said his DUI uses a caching mechanism upfront to find all possible compasses.
`GVAR(compassWhitelist) = "getText (_x >> 'simulation') == 'ItemCompass'" configClasses (configFile >> "CfgWeapons") apply {configName _x};`
But even this wouldn't work for a vehicle crew that does not carry a compass and instead uses the vehicle equipment or a GPS.

So I still think it is best to just skip any check for a compass because the likelihood of one having maptools but no compass is smaller than all the other cases were the current behaviour can be considered a bug.

**Comment by b-mayr-1984** [comment]
Something else that prevent's the map tool from showing the align-to-compass menu entry is this constellation.
![image](https://user-images.githubusercontent.com/76476468/159032029-917e92ea-5d39-4164-aa9a-1827c93d4411.png)
Here I dropped the compass but still get a heading from the GPS. 
![image](https://user-images.githubusercontent.com/76476468/159032275-0258735b-48ba-4794-b065-848aaccc8788.png)

This is just another example that shows that the good intention of not showing this menu entry causes more problematic constellations than it prevents problematic constellations (at least in my estimation).

**Comment by commy2** [comment]
Just take a compass with you. That's the only way to physically align it irl too.

**Comment by BrettMayson** [comment]
I don't see an issue with a common function `canTellDirection` or something, that returns true if they have any compass or a GPS

**Comment by b-mayr-1984** [comment]
> Just take a compass with you. That's the only way to physically align it irl too.

I tried to explain this in the issue description @commy2 . It does only work for the vanilla compass (`ItemCompass`).
If you bring another compass (like the GM compasses) it doesn't work because these compasses don't satisfy the `AND` condition mentioned in my initial post.

**Comment by commy2** [comment]
```sqf
private _hasCompass = getUnitLoadout _unit param [9, []] param [3, ""] != "";
```

**Comment by b-mayr-1984** [comment]
> ```sqf
> private _hasCompass = getUnitLoadout _unit param [9, []] param [3, ""] != "";
> ```

I will give it a try and provide feedback. Thanks @commy2 :-)

**Comment by Akzuu** [comment]
Thumbled upon to this thread and I have another fix suggestion for the map tools.

Currently, you can not use map tools without the default map. I noticed this issue when playing Prairie Fire dlc and the problem is basicly the same as with the compass. The item names for Prairie Fire maps are `vn_o_item_map` and `vn_b_item_map`.

The problematic condition can be found from `acemod/ACE3/addons/maptools/functions/fnc_canUseMapTools.sqf` line 20. I think the fix should be implemented to optional Prairie Fire compat, but I'm too unfamiliar with the codebase to figure out a proper solution to this issue. Do you mind checking this problem too while you are at it with the compass @b-mayr-1984  ?

Ps. the compass item names for Prairie Fire are `vn_b_item_compass_sog` and  `vn_b_item_compass`
