### ISSUE TITLE
Ace cookoff ignores "ace_cookoff_enable" and always cooks off.

### ISSUE THREAD

**Issue by IR0NSIGHT** [acemod/ACE3#8853]
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
Type: Public
Build: Stable
Version: 2.08.149049
- Used mods: ACE3, CBA, Zeus Enhanced, Zeus Enhanced Ace compat.
VERSIONING:cba=3.15.6.211004, zen=1.12.1.29, ace=3.14.1.65

**Description:**
I noticed that the cookoff probability setting doesnt seem to do anything. So i placed 10 vanilla APCs in on malden, disabled cookoff with ```this setVariable ["ace_cookoff_enable",  false, true];``` for half of them and killed them in Zeus by pressing "end" key.
All of them cook off (i can hear the ammo cooking). Repeated this a couple times, same result. Tried by shooting with a merkava tank, same result.

**Steps to reproduce:**
place 10 vanilla apcs, destroy them. 

**Expected behavior:**
this setVariable ["ace_cookoff_enable",  false, true]; should stop any cookoff behaviour on vehicle destruction.

**Where did the issue occur?**
Singleplayer

**Log Files:**
https://pastebin.com/NvA4Qrzg

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Comment by johnb432** [comment]
> **Expected behavior:** this setVariable ["ace_cookoff_enable", false, true]; should stop any cookoff behaviour on vehicle destruction.

It's currently not clearly marked in the documentation, but `this setVariable ["ace_cookoff_enable",  false, true]` only affects the fire effects (visual & sounds). It does not prevent ammunition cook-off.

If you want to prevent ammunition cook-off, you must use `this setVariable ["ace_cookoff_enableAmmoCookoff", false, true]`
