### ISSUE TITLE
Help, AI won't die

### ISSUE THREAD

**Issue by ligmabalzzzz** [acemod/ACE3#8854]
My AI won't die and only become unconscious.I read thats an ace bug,is there a way to fix it?

**Comment by BrettMayson** [comment]
You need to fill out the template that you deleted.

You should ask on the ACE slack or the Arma 3 Discord, the problem is either your settings or mods.

**Comment by LiGmAbAlZzZ** [comment]
> You need to fill out the template that you deleted.
> 
> You should ask on the ACE slack or the Arma 3 Discord, the problem is either your settings or mods.

I haven't changed the ace settings and i don't think i have any mod conflicts, but i will fill the correct template

**Comment by ligmabalzzzz** [comment]
**Mods (complete and add to the following information):**
https://ufile.io/rtvihohc

**Description:**
My ai just won't die

**Expected behavior:**
I expect the ai to die???

**Where did the issue occur?**
Singleplayer

**Log Files:**
https://ufile.io/v6chmty8

**Comment by commy2** [comment]
129k lines rpt file ¯\\\_(ツ)\_/¯

**Comment by Drofseh** [comment]
You need to fill out the *whole* template, not just parts of it

**Comment by BrettMayson** [comment]
Try with just CBA and ACE, if the issue is gone then you'll know it's one of your mods.

**Comment by ligmabalzzzz** [comment]
> Try with just CBA and ACE, if the issue is gone then you'll know it's one of your mods.

Seems that a mod is causing a conflict thanks for the help!
