### ISSUE TITLE
Unable to speak while surrendered or restrained.

### ISSUE THREAD

**Issue by robertbarton212** [acemod/ACE3#8863]
**Mods (complete and add to the following information):**
- **Arma 3:** 1.00 (Current version)
- **CBA:**  3.0.0 (Current version)
- **ACE3:** 3.0.0 (Current version)
- **ACRE or TFAR** (Current version)
-
**Description:**
While surrendering and/or restrained the player or controlled AI is unable to speak using either ACRE or TFAR since the newest ace update. Therefore, there is either a feature added that prevents this or a compatibility issue.

**Steps to reproduce:**

1. Load any mission with the mods listed.
2. Surrender your character and observe you are unable to transmit on your teamspeak tfar or acre channel.

**Expected behavior:**
No transmission will be recorded on ts.

**Where did the issue occur?**
- Dedicated / Self-hosted multiplayer

**Log Files:**
- N/A

**Additional context: **
N/A

**Screenshots:**
N/A

**Comments:**
Doing this on my phone so am unable to follow the set format. However, due to the simplicity of the problem I don’t believe it is required.

**Comment by jonpas** [comment]
Known, fixed for next ACRE2 and ACE3 releases.

**Comment by jonpas** [comment]
Fixed in #8659 and https://github.com/IDI-Systems/acre2/pull/1159.
