### ISSUE TITLE
ACE prevents vanilla spectator from closing properly

### ISSUE THREAD

**Issue by Avokadomos** [acemod/ACE3#8864]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.08`
- **CBA:** `3.15.6`
- **ACE3:** `3.14.1`

**Description:**
When using `["Terminate"] call BIS_fnc_EGSpectator` to close the spectator view, there is a remnant display with ID #-1 that blocks any input from happening (can't press ESC). This happens when the player dies after being unconscious.

**Steps to reproduce:**
1. _Make player unconscious_
2. _Kill player_
3. _Initialize spectator_
4. _Terminate spectator_
5. _You now have a rogue display (#-1) in `allDisplays`_

**Expected behavior:**
The spectator display should be gone and there should not be a rogue display (#-1). Something in ACE prevents the spectator display from closing entirely. Works fine in vanilla.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**Log Files:**
- [Link to RPT and sample mission](https://drive.google.com/drive/folders/1C54QXPmK5Z3Y7mnZqoJ2WuiN3E0HFleb?usp=sharing)

**Additional context:**
Launch the sample mission as multiplayer and watch the demonstration. Everything happens in steps in **initPlayerLocal.sqf**. The respawn menu is there for demonstrating that you can't use any input after the spectator view is closed.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
