### ISSUE TITLE
https://ace3mod.com/ is not working?

### ISSUE THREAD

**Issue by DevotedLynx** [acemod/ACE3#8865]
as the title says https://ace3mod.com/ is down and i do not know how to reach anyone from ace other than git at the moment
feel free to delete just wanted to let yall know

**Comment by jonpas** [comment]
It is known: https://twitter.com/ACE3Mod/status/1511437642914795534

> do not know how to reach anyone from ace other than git

Slack

**Comment by osfrance** [comment]
Hi, The website is down for 14 days now ... :-(

**Comment by jonpas** [comment]
We are on a new domain, see https://twitter.com/ACE3Mod/status/1514694841527160846.

**Comment by osfrance** [comment]
Great, many thanks !!!!
