### ISSUE TITLE
[Question] Retextured Titan AT does not inherit Javelin framework

### ISSUE THREAD

**Issue by TheNightstalk3r** [acemod/ACE3#8884]
Arma 3: 2.08.149102 stable
CBA: 3.15.6.211004 stable
ACE3: 3.14.1 stable

**Description**

Retextured Titan AT launchers do not inherit the Javelin Framework (i.e. the launchers retain their vanilla optics instead of ACE3 overlay and do not lockon to heat signatures when in WHOT or BHOT modes).

**Expected behaviour**

Retextured launcher inherits everything except the texture, so I expected it to also inherit the Javelin Framework.

**Where did the issue occur?**

ACE Arsenal, BIS Arsenal, 3DEN editor

**Additional context**
I noticed this in mods that contains retexture-only Titan AT launchers like Aegis and France 2035.

**Comment by BaerMitUmlaut** [comment]
Make sure you have no "updating base class"-errors in your RPT. Your config inheritance is probably the problem.

Please reopen if that does not fix your issue. You can also join our Discord to get support.
