### ISSUE TITLE
Can't open interaction menu

### ISSUE THREAD

**Issue by KingSilva957** [acemod/ACE3#8889]
So I have been having this problem for a bit where everything works but the interaction menu. I have uninstalled and only used CBA & Ace. just yesterday It was working but now after just reinstalling the game it has broken once more and was hoping to get some help from here.

https://pastebin.pl/view/91f5b99e This being the Rpt and at the moment I am not using any other mods

**Comment by FinLynx** [comment]
I have noticed this too. Everything seems to work fine until after some random loading session the interaction menu doesn't show up anymore. I have also noticed that when the menu has disappeared there is no ACE in "controls menu" either. 

I have also deleted all mods and loaded ACE again and after that it works. Just disabling/activating the mod doesn't help.

**Comment by KingSilva957** [comment]
I have tried deleting all of the mods already, sadly even after doing so with a new download of everything nothing would still work.

**Comment by Drofseh** [comment]
Fill out the issue template

**Comment by BaerMitUmlaut** [comment]
A common cause for this is that some gaming keyboards block the Windows key while a game is open. Try rebinding the key. If that resolves the issue, check if you can disable that behaviour in your keyboards driver.

That said, the issue teplate is still not filled out, so I'm closing this for now.
