### ISSUE TITLE
Definitively test excessive XEH handlers

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#889]
Pre and post init are suspected of failing&availing if the runtime is excessive.

Need to scope this out, check CBA and determine if this is the case.  

IF it is, we have a required work item of PFH staggering long inits.

Refs #871

**Comment by NouberNou** [comment]
CBA wont stop executing these, it just bitches if it takes longer than a certain amount of time.

**Comment by jaynus** [comment]
https://dev.withsix.com/issues/21982

It runs post-init with non-initialized player if > 10 seconds. Refs #1171
