### ISSUE TITLE
All basic ballistics should correct for weapon resting relative gravity angle

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#890]
I think both we and BI forgot that with weapon resting, not all rifles shoot parrelel to gravity now. We should appropriately compensate for this in everything including vehicles. See image.

-----------
![image](https://cloud.githubusercontent.com/assets/2880909/7365010/298462ee-ed41-11e4-853f-326e2938976d.jpg)

Is there any chance for fix or any enhancements for "new BIS" weapon resting system?

With advanced balistics it is actualy game braking, because of...maybe i will show it with a picture -> 
wr
This bullet path will mess up all of the calcuations made for snipers.

Maybe we could get back old AGM resting system, with some updates to new BIS reality- that would add ability to rest weapon on backpack as it was in AGM(someone asked about that feature above this post).

When i want to test Advanced Balistics in ACE3 it is actualy the most anoying part - running aroud to find flat spot to rest my weapon. I feel it like the most game breaking thing in curent ARMA3+ACE3.

Out of topic:
1). I'm not even sure if it is game feature request...because when i was testing ACE, it felt like a Critical Bug for me. It is not ACE3 team fault, but still it will change much more in game experience with AdvBalistics that in vanila arma.
2) Sory for ugly pic.
3) About BIS: Seriously in what kind of world do they live? They acutaly had to assign someone to script that insane weapon alignment to the ground. Someone spent hours...or actualy acording to BIS propably days or weeks to script that completely out of logic thing.

**Comment by jaynus** [comment]
Is this as easy of a fix as I think it is? Can we 3.0 this? It should just be an extra variable to projectile setVectorDir

**Comment by ulteq** [comment]
A true fix for this would be to rotate the gun.

**Comment by jonpas** [comment]
Sounds like something BI could easily fix by adding setVectorDir on the weapon with deployment.

**Comment by sunrrrise** [comment]
To be frank I don't see the mentioned problem:
![2015-04-28_00002](https://cloud.githubusercontent.com/assets/12071586/7365637/6c0429a0-ed92-11e4-981c-c4ede2de5c07.jpg)
![2015-04-28_00001](https://cloud.githubusercontent.com/assets/12071586/7365638/6c1e54d8-ed92-11e4-83d5-83f938a88431.jpg)

ntioned error.

**Comment by gienkov** [comment]
Rest your weapon on a slope and see then.

**Comment by sunrrrise** [comment]
I did it: the upper screen is done with weapon rest on the slope (no wind). The tracer did not "follow" vertical line of the reticle.

**Comment by Coren4** [comment]
@sunrrrise there is absolutly no point to aim in some kind of creepy angle, you should always keep your weapon straight, and that is what every bipod can do.

**Comment by gienkov** [comment]
Yup, that's not how you aim.

**Comment by jonpas** [comment]
In that case, simply make it so it positions straight all the time? With a limit of how steep the slope can be of course.

**Comment by Coren4** [comment]
@jonpas limit when you can or can not prone on slope will be enough

**Comment by sunrrrise** [comment]
I thought we were talking about bullet drop according to the gravity, not about the way that BIS implemented weapon resting, bipods and so on.

**Comment by Coren4** [comment]
We are talking about game immersion, so it is all connected.

**Comment by jonpas** [comment]
You can go prone on very steep slopes, but it's the question of how far can one leg of the bipod extend to support that inclination.

**Comment by gienkov** [comment]
![Extended bipod](http://forum.lowiecki.pl/download.php/12,211850,4334/100_1348.JPG)

**Comment by gienkov** [comment]
Can you simply rotate player body to be parallel with the horizon? It may look odd cause I assume legs of bipods can do advanced things like extend one leg more than the other, but that would fix all problems.

**Comment by ulteq** [comment]
> Can you simply rotate player body to be parallel with the horizon?
That would be the only adequate solution. But it is not possible afaik.

**Comment by Coren4** [comment]
Can we get back old AGM resting weapon system? So we could use it instead of BIS system? Because it worked really well.

**Comment by Dobbie93** [comment]
From my experience, bipods on snipers especially have an ability to rotate left and right, so even if the bipod legs cannot be adjusted, the rifle still sits vertical. On smaller weapon/LMG bipods, long range accuracy is less of an issue, so having the rifle on a cant is not a problem.

**Comment by ulteq** [comment]
The problem is that we can not rotate the deployed gun via script commands.

**Comment by Legolasindar** [comment]
@jaynus your image of the pivot of a bipod is not entirely correct. Walkers, at least those that are well thought out, has a pivot axis in order to tilt the gun. So no need to complicate to adjust the legs of the bipod.

This is how works the bipods (note the humor of the image :D):

![Bipod pivots](http://i.imgur.com/6OMNLJ7.jpg "Bipod pivots")

You can see this pivots in this videos.

2:24 minut - https://www.youtube.com/watch?v=_v-WkipfKzo
3:04 minut - https://www.youtube.com/watch?v=xlUnl-oiQ7Q
0:10 minut - https://www.youtube.com/watch?v=ZVVe3dkwv7w

**Comment by Coren4** [comment]
@Legolasindar 
First of all it is my image
Second...watch your videos...every tripod has legs that can be extended...so acutaly my image is correct, because in most cases shooter will extend bipod legs, because it will give him beter stability, that pivot under weapon will be used for small corections. - What you changed on my image is actualy very inacurate and inappropriate, because center of the mass of your gun is even further than the base of a leg...that would most likely cause all setup to flip over.

**Comment by Legolasindar** [comment]
@Coren4 of course you can also adjust the height of the legs of the bipod. I did not deny it. But in the simulator, if we talk about a quick and automatic unfolding of the bipod on an sloping surface, it is more logical to apply the pivot gun, no variation in the legs of the bipod.
Ideally, you can do both.

**Comment by Coren4** [comment]
@Legolasindar in real world sniper/marksman doesn't change his position every 30 seconds, he lie and shit himself for hours to keep not moving, while extending legs will give him much more stability and comfort - in my opinion he will extend his legs more often than using just a pivot. For the game it actualy pointles, it doesn't matter if there will be bipod with pivot, or if you will be able to place bipods with extended legs...BIS just need to straighten your view it is such small thing, that it doesn't mater how it will be done....we just need BIS to do it proper way...i hope they will fix it before Arma 4.

**Comment by Wolfiy** [comment]
Three things can be done:
1. Compensate for angle of shot.
2. Bring a portable rest. (Included in ACE 3)
3. Find flat ground or a building.

**Comment by ace3mod** [comment]
Hello @acemod/maintainers. This ticket has been open for over 452 days without any activity.

**Comment by Glowbal** [comment]
Engine issue that we cannot fix in any acceptable manner within ACE.
