### ISSUE TITLE
Log menu 

### ISSUE THREAD

**Issue by SanyaGood** [acemod/ACE3#8901]
Hello, the log interferes with the game, there are no other mods, only ACE 3 and additions to it, what can it be?
Screenshots: (https://ibb.co/GMVtpQx)

**Comment by PabstMirror** [comment]
error is in "@dynamic camo system" not ace,
please post full issue template

**Comment by SanyaGood** [comment]
> error is in "@dynamic camo system" not ace, please post full issue template

And how to fix it, I just don’t want to clog up with a bunch of questions, I just need to find the answer
