### ISSUE TITLE
error is in "dynamic camo system"

### ISSUE THREAD

**Issue by SanyaGood** [acemod/ACE3#8902]
How to fix this error please help   
Screenshots: https://ibb.co/GMVtpQx

**Comment by kymckay** [comment]
Don't spam our issue tracker or you will be blocked.

**Comment by SanyaGood** [comment]
> Don't spam our issue tracker or you will be blocked.

wtf, I was told in the last appeal to create a new request

**Comment by jonpas** [comment]
> error is "dynamic camo system" not ace

You have been told, this is an issue yo are having with another mod.
