### ISSUE TITLE
ACE3 freezes when loading into the main menu on Linux Proton

### ISSUE THREAD

**Issue by Freddo3000** [acemod/ACE3#8911]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.08` (profiling and stable)
- **CBA:** `3.15.6`
- **ACE3:** `3.14.1`

**Description:**
Arma gets stuck permanently when loading into the main menu due to the old ACE options menu URL not being updated which was resolved in #8875. I'm opening this issue as it completely prevents Proton users from playing the game with ACE (or at least on servers with battleye/version checking, or without messing with hosts/DNS) until a patch has been released, and thus would probably warrant a hotfix.

**Steps to reproduce:**

1. Try to launch Arma with ACE and CBA loaded through Proton
2. Get stuck permanently on the Arma load screen logo

**Expected behaviour:**
Being able to get to the main menu and play the game.

**Where did the issue occur?**
- Arma 3 run through Proton

**Log Files:**
n/a

**Additional context:**
n/a

**Screenshots:**
n/a

**Comment by PabstMirror** [comment]
Should be fixed with new release
