### ISSUE TITLE
ACE Burning/Unconscious Respawn Bug

### ISSUE THREAD

**Issue by Goldwep** [acemod/ACE3#8922]
**Mods (complete and add to the following information):**
- **Arma 3:** Current Live Build as of 5/24/2022
- 
- **ACE3:** Newest update released 5/24/2022 

**Description:**
When a player controlled unit burns to death (currently 100% of the time on my machine if its from the M14 Incendiary), the respawn menu no longer recognizes user input on the respawn UI. 

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. _(First respawn and enable autorespawn) Go to a Player Unit_
2. _Throw a incendiary grenade or Burn Unit in zeus
3. _See that the mouse pointer no longer registers in the respawn menu

**Expected behavior:**
Be able to input mouse clicks on the respawn UI

**Where did the issue occur?**
- Dedicated Server

**Log Files:**
- Unable to provide at this time.

**Additional context:**
Reproduced with 100% reliability when killed from burning while under unconsciousness 

**Screenshots:**

**Comment by LinkIsGrim** [comment]
Fixed in #9053.
