### ISSUE TITLE
Ace Intel items cant open if you dont have a map

### ISSUE THREAD

**Issue by L3gion-cmd** [acemod/ACE3#8930]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.08 stable branch`
- **CBA:** `3.15.7 stable branch`
- **ACE3:** `3.15.0 stable branch` 

**Description:**
Hi. So i was creating escape room kind of mission and i noticed that you cant access the notepad/Photo/Documents from inventory if you dont have a map. So i placed notepad item, photo item, and documents item on the table and pickthem up. When player has the map i am able to acces  them with self interaction on map screen. But when i put the map down i cant acces them.

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. Place down these assets on the ground in eden Editor [acex_intelitems_notepad,acex_intelitems_document,acex_intelitems_photo]
2. Enter in Play mode in eden editor and on the Player / controled unit Remove the map from inventory.
3. Pickup the items and try to acces them in the map screen (even the map is missing).

**Expected behavior:**
I expected to see the intel items or access them even if the player dosent have a map to see them.

**Where did the issue occur?**
- Editor (Multiplayer)

**Screenshots:**
https://i.imgur.com/HaFlaDt.png
https://i.imgur.com/AQf9dCg.png
https://i.imgur.com/bVgxc6K.png

**Comment by lsvalmont** [comment]
Would be optimal if ACE has its own customizable UI that includes the notes/intel implementation but that can be easily expanded upon.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.

**Comment by L00Cyph3r** [comment]
Issue is still relevant. It seems there is no ability to self-interact when there is no map.
