### ISSUE TITLE
Medical Menu UI - Injury display 

### ISSUE THREAD

**Issue by thamex** [acemod/ACE3#8932]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.08.149102` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.7` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.15.0` [eg. 3.0.0 stable, commit hash]

**Description:**
There is a bug in the Medical Menu UI when showing the injury on a body part. Instead of showing 1x large xxx it shows 1x.
So it's impossible to see which injury has the parts

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. Spawn
2. Get a hit
3. Open medical menu
4. Check the body parts

**Expected behavior:**
It's suppose to show the type of injury next to the amount of it.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Log Files:**
I got no Rpt file for that type of issues

**Additional context:**
I tried in different languages, but it's still the same bug.

**Screenshots:**
![image](https://user-images.githubusercontent.com/12872513/171994179-4b1ca71e-29d3-44d6-aed6-acb802e3ab3e.png)

**Comment by PabstMirror** [comment]
Are you running KAT?
if so make sure it's an updated version

**Comment by thamex** [comment]
No, but I think my mod files was corrupted. I have deleted all the file and download them again and now it works.
