### ISSUE TITLE
Bullets causing large amounts of wounds to torso and head when not going through armor (vest or helmet)

### ISSUE THREAD

**Issue by Ivanowicz** [acemod/ACE3#8938]
**Mods:**
- **Arma 3:** `2.08 stable`
- **CBA:** `3.15.7 stable`
- **ACE3:** `3.15.0 stable`

**Description:**
As per title - bullets seem to be causing disproportionate amounts of wounds when not hitting any armor. This is something that I noticed after the latest update, so it might have something to do with #8278.

Results of my testing of torso wounds with no armor and 2 different vests (listed wounds happened majority of time - sometimes instead of Velocity Wounds, the bullets caused Avulsions):
- F2000 (5.56)
vs No Armor: 2x Large Avulsions
vs Tactical Vest: 1x Medium Velocity Wound
vs Carrier Rig: 1x Small Velocity Wound
- HK417 (7.62)
vs No Armor: 2-3x Large Avulsions
vs Tactical Vest: 1x Large Velocity Wound/Avulsion
vs Carrier Rig: 1x Medium Velocity Wound
- AH6 Lynx (12.7)
vs No Armor: 7-8x Large Avulsions
vs Tactical Vest: 1-2x Large Avulsions
vs Carrier Rig: 1x Large Velocity Wound/Avulsion

I have not tested the head wounds quite as much, but from what I've seen the *No Armor* wounds are identical between torso and head, and with a helmet the results are similar to the *Tactical Vest*. Interestingly, there seems to be no issues when it comes to limbs - even 12.7 causes only a single large wound + a bruise.

This happens both in Sinleplayer and Multiplayer, persists with mod weapons and armor (RHS, CUP), but the tests were performed with only CBA and ACE enabled.

**Expected behavior:**
(Another Edit - I missed a portion of the discussion in #8278, which made me think the behavior above is not intentional)
Before the latest update, IIRC, in most cases a single bullet caused a single wound. The change means that anybody hit in an unarmored area (even a fully armored person hit in the face) requires anywhere from 2 to 8 times more bandages to stop the bleeding. I see this is an intentional change, but I would argue it's a bad one balance-wise, specially without any options to modify it.

While it is not really an issue for communities playing with standard settings (if person dies from a headshot, it doesn't really matter if they have 1 or 8 wounds), for those playing with *Fatal Injuries* set to *Never* this is quite nightmarish - beforehand we could easily play with quite unrealistic settings and still get fun, more in depth medical gameplay, while not having to use massive amounts of bandages per person. It also seems that any missions with no or limited armor, such as WW2 or early Cold War will now simply become unplayable with the aforementioned settings - e.g. a quick MG42 burst will easily cause 10+ Large Avulsions, which I'd argue is simply not fun, given the massive amount of time and resources every wounded will now require.

While I'd love to see an option to switch back to old wounding system, I assume this solution is simply not practical. Would it be possible to have some sort of *Wound Modifier* slider?

**Where did the issue occur?**
Dedicated Multiplayer / Singleplayer

**Log Files:**
https://pastebin.com/t8zGABBW

**Comment by Ivanowicz** [comment]
First off, I would like to ask for a change of issue label if possible - I should’ve tagged it as *kind/enhancement* or *kind/feature request*, given that it is an intentional design choice that simply doesn't seem to be working well for our particular group (my bad, when I started writing the issue I did not realize the change is not a bug and forgot to change it).   

An update of my experiences after playing with ACE with a small group of people for another month. As above, our main non-standard setting is _Player Fatal Injuries_ set to _Never_.

The behavior of the new damage model in a standard Arma scenario (soldiers with armored vests and helmets) is for the most part solid, if a bit harsher than before. Grenades and other explosives work great and better wound variety is appreciated.

However, there are issues around larger calibers (especially .50 cal, which is pretty much a default vehicle/static mg) - an armored vest or helmet reduces the damage anywhere from 4-8 times, which seems a bit much, especially for a simple ballistic helmet or a kevlar vest. As above, the difference for other calibers isn't as massive, but still means around 3 times less damage.

This is one of our main frustrations with the change - the large discrepancy between the armored and unarmored damage. While in a WW2 scenario we could just increase the damage threshold by a few times, in scenarios with partial armor we either have to increase it so much that hits to the armored areas basically don't matter, or leave it as is, and have hits to unarmored areas be way more deadly than we would like.

Our second big issue is the massive increase in bandage usage - in this case we don't have any way to speed up bandaging or make the bandages more effective to account for the great increase in wounds in unarmored scenarios, meaning medics have to spend more time and resources on every player, and non-medic players are less able to heal themselves or one another.

I don't have any solid ideas on how our first problem could be solved, but I think the bandage issue could be solved by adding _**Bandage Effectiveness**_ and/or _**Bandaging Speed**_ sliders to the medical settings (and those would further improve one the strengths of ACE, which is it's customizability).

**Comment by gripen888** [comment]
I have to agree with my colleague. In our clan, we use a similar medical setup to him and rather than let these "fatal" injuries kill our players, we leave them unconscious - let our medics have some fun. On the other hand, if they leave 10x as many bandages on such a player - it complicates the game quite a bit. This way we are forced to either use a huge amount of bandages, or switch to a more realistic setting and use more respawns. (However, this is not possible in one life missions.) 

As Ivanowicz writes: We need at least one (ideally all) of the following settings:
**Slider for Bandage Effectiveness
Slider for Bandaging Speed
Option to switch back to a less realistic (original) effect of large-caliber damage on exposed body parts.**

**Comment by Mike-MF** [comment]
This is a feature request, not an issue.
