### ISSUE TITLE
Top dawn mode is broken?

### ISSUE THREAD

**Issue by Eni0** [acemod/ACE3#8939]
All good? Then proceed and fill out the items below.
-->

Mods
Arma 3 stable
CBA stable
ACE3  stable

Description:
for me Top dawn mode doesn't work or works in a very strange manner. Regardless of the choice of launch mode (top or direct), the rocket always flies to the center of the tank in the gap under the turret. The difference is only a few degrees of the angle of the rocket between top or direct mode. 

**Steps to reproduce:**
Place a unit in 3eden with Titan AT and shoot  into different tanks at different distances. Same result with RHS mod and ACE compats - Javelin flies to the center of the tank in the gap under the turret. The difference is only a few degrees of the angle of the rocket between top or direct mode. 

Expected behavior:
As far as I remember, Javelin  hit target  at an angle of about 45 in top down mode

Additional context:
As far as I remember, the arma3   game update month ago broke the top down mode and the problem was fixed with the update and everything worked. Now it doesn't work again

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
