### ISSUE TITLE
Problema para instalar los ACE y ACE3

### ISSUE THREAD

**Issue by JMartin27** [acemod/ACE3#8944]
![Error 1](https://user-images.githubusercontent.com/83242752/174912044-8a3afc64-c4b3-4fed-b3bf-ec5e9893719f.png)
![Error 2](https://user-images.githubusercontent.com/83242752/174912078-3fa004f0-2807-453b-9055-96d7fb7d5c50.png)
Saludos, descomprimo los archivos, pego las carpetas @ACE y @ACE3 en la carpeta raiz del juego, pero me salen esos dos errores, como podría solucionarlo?

**Comment by PabstMirror** [comment]
actualizar ArmA en steam
no admitimos versiones antiguas

**Comment by JMartin27** [comment]
> actualizar ArmA en steam no admitimos versiones antiguas

Es decir que mi ARMA 3 es muy antiguo para esos addons?
