### ISSUE TITLE
Ace Weapons "select binoculars" should remain empty!

### ISSUE THREAD

**Issue by STyx2909** [acemod/ACE3#8946]
- **Arma 3:** 2.08
- **CBA:** 0.5.6
- **ACE3:** `3.15.0

Hello!

- If you assign a key to this action; it doesn't allow to put back the binoculars. You must use the default ARMA 3 key bind (default "B").

- If you assign the "B" key to this ACE action (I did), it breaks the ARMA 3 default bind... I had to set binoculars to CTRL B.

Took me 2h30 to figure this.

Hope it helps.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer /  Virtual Arsenal / In Game

**Comment by LinkIsGrim** [comment]
Keybinds in weapon select aren't intended to be a direct replacement of vanilla keybinds. `Select Weapon` means "switch to this weapon", not "switch to this weapon or put it away if it's already equipped".
