### ISSUE TITLE
Bullet did not do the damage to some vest

### ISSUE THREAD

**Issue by 0321RECON** [acemod/ACE3#8956]
Mods 

ARMA 3: Current Live Build as of 5/24/2022
ACE3: Version 3.15.0
CBA:v3.15.7.220517
Description:
When I do some shooting in the ACE Arsenal ，I find some small arms can not do the damage to some vest .I shoot the  3 mags of ammo to some vest but in medical menu it only turn blue .You can not heal the body.
![This is an image](https://user-images.githubusercontent.com/108707667/177241744-a67a5723-a77f-474d-a9f0-57cbfe7446d6.jpg)
Small Velocity Wound for 轻度挫伤
Where did the issue occur?

 Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
Log Files:
~~~~~~~~~ACE Debug~~~~~~~~~
[Time: 47.4] [CBA_missionTime: 47.2] [tickTime: 89.1]
------Performance------
diag_fps = 58.3942
count cba_common_waitAndExecArray = 4
count cba_common_waitUntilAndExecArray = 0
count cba_common_perFrameHandlerArray = 14 (max 128)
count diag_activeSQFScripts = 3
count diag_activeSQSScripts = 0
count diag_activeMissionFSMs = 1

------Player------
typeOf = C_man_1
animationState = amovpercmstpsraswrfldnon

------ACE's CBA Settings [569 Total] [Only Non-Defaults]------
ace_advanced_ballistics_enabled - true
ace_nightvision_aimDownSightsBlur - 0.284092
ace_nightvision_noiseScaling - 0.266685
ace_overheating_enabled - false
acex_headless_enabled - true

------Array Info (count >= 100)------
ace_medical_blood_blooddrops - ARRAY SIZE: 128
ace_common_hexarray - ARRAY SIZE: 256
cba_wtab - ARRAY SIZE: 128
ace_medical_gui_selfinteractionactions - ARRAY SIZE: 128
cba_ktab - ARRAY SIZE: 128
cba_common_pfhhandles - ARRAY SIZE: 128
cba_events_keyupstates - ARRAY SIZE: 270
ace_common_clearcache_ace_interact_menu_clearconditioncaches - ARRAY SIZE: 216
cba_common_addons - ARRAY SIZE: 1669
cba_settings_allsettings - ARRAY SIZE: 578
cba_events_keydownstates - ARRAY SIZE: 270
cba_xeh_alleventhandlers - ARRAY SIZE: 347
ace_casings_casings - ARRAY SIZE: 108
ace_interact_menu_inheritedactionsman - ARRAY SIZE: 256
cba_settings_needrestart - ARRAY SIZE: 168
cba_ytab - ARRAY SIZE: 128

**Comment by rautamiekka** [comment]
That's exactly how the GA vest works (at least in-game), it protects very well against 556, only resulting in bruising a lotta (all ?) the time.

There was already a ticket about the same thing.

**Comment by 0321RECON** [comment]
> That's exactly how the GA vest works (at least in-game), it protects very well against 556, only resulting in bruising a lotta (all ?) the time. You can fix bruising with the PAK (personal aid kit) if your Server/mission ACE Medical addon options allow the use of PAK.
> 
> There was already a ticket about the same thing.

I am pretty sure this is a bug.Try shooting 70 rounds 556 in your ACE Arsenal,you will get different result.
