### ISSUE TITLE
RHS Compat Bradley is indestructible 

### ISSUE THREAD

**Issue by Willparker666** [acemod/ACE3#8957]
**Mods (complete and add to the following information):**
- **Arma 3: v2.08 Profiling
- **CBA: v3.15.7
- **ACE3: v3.15.0
- RHSUSAF: v0.5.6
- ACE Compat - RHS USAF 3.15.0

**Description:**
The RHS USAF M2A3 BUSKIII is almost indestructible. The other M2A3's are soaking up as many tank shells and RPGs as it want.
Only the javelin can kill it, perhaps because the slat amour is not added in the ace compat.

**Steps to reproduce:**
1. Turn on advanced vehicle damage in ACE3.
2. Spawn M2A3 BUSKIII.
3. Shoot as much as you like.

**Expected behavior:**
I'd expect the Bradley to blow up after being shot by a tank several times.

**Where did the issue occur?**
- Dedicated and SP

**Log Files:**
- Sorry no log files, but should be easy to reproduce.

**Additional context:**
I tried adding the SLAT hitpoints to the BUSKIII in my own ace compat version but it didn't quite work.

**Screenshots:**

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
