### ISSUE TITLE
'M240Recoil/' is not a class

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#896]
ACE3 Version: custom 28.04.2015

Mods:
@cba_a3
@ace3
@RHSAFRF
@RHSUSAF

Placed ACE3 Modules:
No, checked in VR

Description:

ACE3 Version: custom 17.04.2015

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
No, checked in VR

Description:
http://i.imgur.com/mGmcVzF.png

Steps to reproduce:
1. Go to VR
2. Paste this:
this addWeapon "rhs_m4a1_m320_compm4";
and give some underbarrel grenades
3. Shoot underbarrel grenade launcher.

Where did the issue occur?
First time when tou use it

RPT log file:
No

Steps to reproduce:
Try to check response on any unconcious AI

Where did the issue occur?
Every time

RPT log file:
No

**Comment by alganthe** [comment]
This is NOT a RHS compatibility issue, I can reproduce it whithout RHS nor compatibility pbo

**Comment by ruPaladin** [comment]
Then post an issue what are you waiting for :frowning:

**Comment by alganthe** [comment]
you can rename yours !!!1111elven

**Comment by ruPaladin** [comment]
Done, but it will be better if you post stept to reproduce without RHS.

**Comment by alganthe** [comment]
ACE3 version 3.0.0.1 last commit: a4fd621bd0e9eb4f38c5fd92f79a4b0a4af4aaf2

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
none

**Description:**
When firing with a grenade launcher an error pop 
```
'M240Recoil/' is not a class ('kickBack'accessed)
```

**Steps to reproduce:**

* Place a grenadier in the editor
*  fire with the grenade launcher
