### ISSUE TITLE
Terribly low FPS only when using ACE3 with SOG Prarie Fire DLC 

### ISSUE THREAD

**Issue by 211345082311111** [acemod/ACE3#8965]
**Mods ():**
- **Arma 3:** `2.08` [stable]
- **CBA:** [stable]
- **ACE3:** `3.13 or 3.14 or 3.15` [stable]

**Description:**

Hi to ACE3 team! 

I've never experienced ACE3 performance issues together with any other DLC or addon, for me ACE3 always had excellent performance! But it wasn't until I got the Prarie Fire DLC a week ago, that I realized those two addons are completely incompatible. I have tried three versions of ACE3 (3.13 or 3.14 or 3.15) and they all confirmed that ACE3 cannot be used with DLC Prarie Fire, as it cuts my FPS in half.  As soon as I disable ACE3 I get smooth and great gameplay of Prarie Fire.

Even if I put one squad anywhere on the Kam Lao Nam map, when there is no any battle I get a noticeably low FPS, but if a fight starts with a small number of units, (only 2-3 squads) I get a catastrophic low FPS. Please Note! The negative impact of ACE3 takes place immediately, even when there is no any battle. As if the map itself, in ACE3 mode, significantly loads the system and of course the fight, will make this impact worse.

For comparison:

without ACE3 my FPS in the Kam Lao Nam junglies will be 43-47
with ACE3 my FPS in Kam Lao Nam junglies will be 25-38

without ACE3 my FPS in the Kam Lao Nam junglies durring fight will be 25-35
with ACE3 my FPS in Kam Lao Nam junglies will be 9-16!

I've searched for any compatibility mods on Steam, but I haven't found any compatibility addons for Prarie Fire.  
There is no compatibility addon! I don't understand what could be the problem? 
Why there is no compatibility or at least there are no mods for compatibility? Or Prarie Fire cannot be combined so that they work properly? 

ACE3 Team please make this compatibility, just like with other addons or DLC.

**Steps to reproduce:**
Play in Prarie Fire with ACE3 and without ACE3. Try compare game performance

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer), Coop Missions

**Comment by Mike-MF** [comment]
This is a feature request, not an issue. SOG Compatibility is also already done.
