### ISSUE TITLE
rhssaf_tm100_mag, rhssaf_tm200_mag, rhssaf_tm500_mag placeable from scroll menu

### ISSUE THREAD

**Issue by GalNa** [acemod/ACE3#8980]
**Mods:** @ace;@cba;@rhsusaf;@rhsafrf;@rhsgref;@rhssaf;@ACE Compat - RHS AFRF;@ACE Compat - RHS- GREF;@ACE Compat - RHS- SAF;@ACE Compat - RHS USAF
- **Arma 3:** `2.08` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.7` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.15.0` [eg. 3.0.0 stable, commit hash]

**Description:**
'rhssaf_tm100_mag', 'rhssaf_tm200_mag', 'rhssaf_tm500_mag' can be placed from scroll menu.

**Expected behavior:**
Placing it only from ACE menu.

**Comment by Drofseh** [comment]
Please fill out the issue template correctly
