### ISSUE TITLE
CSW - Unable to load mortar with ammo located in vehicle

### ISSUE THREAD

**Issue by Timi007** [acemod/ACE3#8986]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.08`
- **CBA:** `3.15.7`
- **ACE3:** `3.15.0`

**Description:**
Normally you're able to load e.g. the MK6 mortar with shells located in an ammo create near the mortar. If the shells are located in the inventory of a vehicle, the action for loading the mortar is shown and can be executed. After the progress bar the loading fails silently (except RPT error).

**Steps to reproduce:**
1. Go into the editor and place a vehicle (i used a quadbike) and a mk6 mortar next to it.
2. Activate `ace_mk6mortar_useAmmoHandling` CBA setting.
4. Add mortar shells to the quadbike (`this addMagazineCargo ["ACE_1Rnd_82mm_Mo_HE", 10];`).
5. You will see the ACE action to load the 82mm HE shell.
6. Execute the load action. Wait for progress bar to finish.
7. Check ammo of mortar and inventory of quadbike. Nothing changed. Mortar was not loaded.

**Expected behavior:**
Mortar can be loaded with ammo located in a vehicle's inventory. After executing the action, one shell should be deleted from the inventory and loaded into the mortar.

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Log Files:**
- [RPT](https://pastebin.com/GfPL841d)
- Line 947 is logged after step 6.: `[ACE] (csw) ERROR: No ammo [any - -1]?`

**Additional context:**
The error is logged [here](https://github.com/acemod/ACE3/blob/df3a9de7cd6e56374e1346d7f8b7de06e586362e/addons/csw/functions/fnc_reload_loadMagazine.sqf#L50) in the code. The problem is that if `_magSource` is a vehicle, `magazinesAmmo` will not retrieve the shells in the inventory. But the [`reload_canLoadMagazine`](https://github.com/acemod/ACE3/blob/df3a9de7cd6e56374e1346d7f8b7de06e586362e/addons/csw/functions/fnc_reload_canLoadMagazine.sqf) function correctly finds the shells. Therefore showing the action but not loading correctly.

**Comment by Salluci** [comment]
_Should_ be a simple fix to just change [magazinesAmmo](https://github.com/acemod/ACE3/blob/df3a9de7cd6e56374e1346d7f8b7de06e586362e/addons/csw/functions/fnc_reload_loadMagazine.sqf#L50) to `magazinesAmmoCargo`, but I'm not entirely sure if that works with regular container objects.
