### ISSUE TITLE
Position of interaction on weapon (reloadlaunchers)?

### ISSUE THREAD

**Issue by Stiltman** [acemod/ACE3#902]
Hi, ive been looking at the reloadlaunchers function and a Carl Gustaf launcher and i am wondering if there is anything i can do to edit the position of the weapons load ammo interaction point so the loader would aim at the back of the launcher to see the interaction menu point.
and if not any chance of seeing it as a feature, for example if i add a memory point on the weapon.

**Comment by jaynus** [comment]
#414

**Comment by esteldunedain** [comment]
@Stiltman, sorry that's not possible ATM. We cannot read memory points for weapons, so we are just applying an offset from the right hand, but it's obviously not perfect and it fits some weapons better than others.

**Comment by jaynus** [comment]
@esteldunedain: We could probably actually offset it differently if its a type of LauncherBase couldn't we?

**Comment by Stiltman** [comment]
@jaynus maybe a possibility to add a offset value in the config.cpp? like ace_reloadlaunchers_offset ""; where one could setup the offset for each launcher individually.

**Comment by commy2** [comment]
Thats not possible, because you never know in which direction the launcher points.

**Comment by esteldunedain** [comment]
Yes @jaynus, we can do that. In fact we could allow offsets to be read from
config for the current weapon.

I like the idea. Could you create a ticket for that?
