### ISSUE TITLE
Doctor ace role is breaking stamina

### ISSUE THREAD

**Issue by Wileker** [acemod/ACE3#9028]
**Mods (complete and add to the following information):**
- Ace

**Description:**
any slot with the doctor role stamina breaks and is stuck on

**Steps to reproduce:**
-Have doctor role

**Expected behavior:**
have no stamina issue

**Where did the issue occur?**
everywhere

**Log Files:**
- https://cdn.discordapp.com/attachments/1000159373936578731/1005316930648940687/Arma3_x64_2022-07-31_16-17-31.rpt

**Additional context:**

**Screenshots:**

**Comment by Drofseh** [comment]
Please test again using *only* CBA and Ace3
