### ISSUE TITLE
ace_xm157.pbo is outdated.... anyone else?

### ISSUE THREAD

**Issue by NavyMidshipman** [acemod/ACE3#9032]
**Mods (complete and add to the following information):**
- **Arma 3:2.10.149879
- **CBA:** `3.15.8.220912 
- **ACE3:** `3.15.1

**Description:**
I wanted to ask about the ace_xm157 mod? I'm getting an "ace_xm157.pbo is outdated" error... However, everything has been updated. 

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. _Go to ..._
2. _Click ..._
3. _See ..._

**Expected behavior:**
The mission file loads and I don't get an error when waiting to spawn.

**Where did the issue occur?**
-Self Hosted Multiplayer

**Log Files:**
?

**Additional context:**
We ran a mission flawlessly (without changes to the mod list) last Thursday. on 9/13, we tried loading in and got the above error. We're not too sure how to proceed?

**Screenshots:**
N/A

**Comment by Drofseh** [comment]
upload your RPT file

**Comment by NavyMidshipman** [comment]
Hello! Where might I find that?

**Comment by NavyMidshipman** [comment]
[Arma3_x64_2022-09-14_00-24-51.zip](https://github.com/acemod/ACE3/files/9563104/Arma3_x64_2022-09-14_00-24-51.zip)

I found it! hopefully this is what you needed.

**Comment by Drofseh** [comment]
You are loading a large number of mods, in the future please test bugs with only CBA and the official Ace3 release loaded.

It looks like you are loading some ace PBOs from `!Workshop\@ace` and some ace PBOs from `!Workshop\@ACE3 for Project injury Reaction (PiR)`.

These are probably conflicting.

**Comment by Gillo41** [comment]
I still having the problem of ace_xm157.pbo outdated, i put the RBT file in Arma and i don't have the PiR mod installed, What else i need to fix to play Arma?

**Comment by Drofseh** [comment]
> I still having the problem of ace_xm157.pbo outdated, i put the RBT file in Arma and i don't have the PiR mod installed, What else i need to fix to play Arma?

@Gillo41 please make a seperate issue or join the Ace discord server instead of resurrecting an old closed issue.
