### ISSUE TITLE
ACE Arsenal - 'SHIFT + IMPORT' feature not importing data from clipboard

### ISSUE THREAD

**Issue by SkyeGuy** [acemod/ACE3#9035]
**MODS USED:**
- **Arma 3**: Public release build, `version 2.10`
- **CBA:** `3.15.8`
- **ACE3:** `3.15.1`
-> Issue was replicated with only these two mods loaded on a new scratch-built 3DEN editor mission made on 9/14/22.

**Description:**
ACE Arsenal - the "SHIFT + IMPORT" feature is not importing DEFAULT loadout data from clipboard. "SHIFT + EXPORT" seems to be working correctly in exporting the data to clipboard.

**Steps to reproduce:**

1. Load mission in 3DEN editor with playable unit down. Right click -> Edit Loadout -> ACE Arsenal.
2. Click LOADOUTS -> DEFAULT LOADOUTS at bottom.
3. Save kit as loadout with name. Hit CLOSE to return to ACE Arsenal.
4. Open Notepad or other raw text editor program, to paste the data.
5. Hit "LEFT SHIFT + CLICK 'EXPORT'" button to export the saved default loadout to clipboard.
6. CTRL+V on Notepad to paste data.
7. Go back to ACE Arsenal; go into the DEFAULT LOADOUTS screen again and delete the saved loadout to test the import. Hit CLOSE.
8. Go to Notepad .txt file; hit 'CTRL+A' to select all, then 'CTRL+C' to copy data.
9. Back to Arsenal - hit "LEFT SHIFT + CLICK 'IMPORT'" to import the data from clipboard. 
10. Navigate to DEFAULT LOADOUTS screen. **No imported data is present.**

**Expected behavior:**
When importing previously saved & exported default loadout arrays, the SHIFT + IMPORT function should import the data.

**Where did the issue occur?**
- Editor (Singleplayer & Multiplayer), in ACE ARSENAL

**Log Files:**
- No logs applicable for this scenario that I am aware of, unless there are logs that ACE Arsenal functions output somewhere.

**Video:**
There is a video I recorded locally demonstrating the bug, see the Google Drive link below.
https://drive.google.com/file/d/1xtyjRXJnxQTLzhXufTBdj6v4aFwM76so/view?usp=sharing

**Comment by johnb432** [comment]
I think it's due to [this](https://github.com/acemod/ACE3/blob/22586fc137aa434286f948f9226336e9587d6c6f/addons/arsenal/functions/fnc_buttonImport.sqf#L32) not accommodating for CBA extended loadouts.
I have a PR coming soon that *should* address this amongst things.

**Comment by LinkIsGrim** [comment]
Addressed in #9040.
