### ISSUE TITLE
Cannot move Map Tools on the map.

### ISSUE THREAD

**Issue by Komon277** [acemod/ACE3#9037]
**Mods (complete and add to the following information):**
Arma 3
CBA
ACE
KP liberation scenario.

**Description:**
For some reason when I use windows key+ctrl to place the protractor from map tools on my map, I cannot move the map tool. I can still move my compass and gps using only a left click but I cannot move the map tools protractor. I have attempted to use multiple other key commands with the left click to no avail.

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. Open map on Arma 3 with ACE mod installed
2. Use windows key+shift to use the action menu and pull out the map tool. Normal or small tool provide same issue.
3. Left click to drag the map tool around your map. In my case I cannot drag it. 

**Expected behavior:**
I expected the map tool to be able to be left clicked and dragged around once placed upon the map using the self-action menu whilst in the map.

**Where did the issue occur?**
Self-Hosted multiplayer with friends.

**Log Files:**
non-existent crash.

**Additional context:**
My arma 3 is the base game installed with 3 mods total. The CBA mod, ACE mod, and KP liberation scenario. Not sure if this helps but hope it does. I also own all DLC.

**Screenshots:**
I had not taken a screenshot.

**Comment by Drofseh** [comment]
Please test without other mods enabled, as the required by the flowchart
https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp

**Comment by LinkIsGrim** [comment]
Cannot reproduce with provided information.
