### ISSUE TITLE
UGL impossible to zero if weapon is equipped with adjustable scope

### ISSUE THREAD

**Issue by Brisse89** [acemod/ACE3#904]
Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
ace advanced ballistics

Description: Equip a weapon with under-barrel grenade launcher. Now put an adjustable scope on it. Select the grenade launcher, and try to adjust it's zero. You will notice that it does not change, but your optic for the primary weapon does instead. 

Tested on a build made today (2015-04-28) using F2000 EGLM with MOS scope.

**Comment by alganthe** [comment]
first use [this form] (http://ace3mod.com/wiki/user/how-to-report-an-issue.html) 
second, erm.... don't use a scope that has the lenght of the barrel on that weapons ? I got no issue here.

**Comment by Brisse89** [comment]
Bring out your popcorn. Bug has been caught on video. 
https://youtu.be/t4kcH1mTd8c
