### ISSUE TITLE
ACE arsenal will not save kits. Guns get deleted. Radios get deleted. 

### ISSUE THREAD

**Issue by Tansimmo2** [acemod/ACE3#9042]
**Mods (complete and add to the following information):**
only ace loaded
- **Arma 3:** `Current version
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** current version

**Description:**
Can not save kits it breaks and will not keep any updated items. If make a new kit deletes everything inside
**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

Grab any gun, uniform, backpack,
Grab a 343 in your backpack
Save the kit
See how it breaks

If this doesn't work load acre, ace, cba. Make a kit with a gun a uniform backpack and a rifle. Add a 343 to your kit and then save the kit. You should see it break.

**Expected behavior:**
Not to lose all items

**Where did the issue occur?**
- dedicated server, ace arsenal in main menu

**Log Files:**
[Arma3_x64_2022-09-18_10-05-59.txt](https://github.com/acemod/ACE3/files/9594277/Arma3_x64_2022-09-18_10-05-59.txt)

**Additional context:**

**Screenshots:**
![20220918091729_1](https://user-images.githubusercontent.com/113842725/190913613-11113352-8c20-4d9a-bbcb-60b75dba717c.jpg)
![20220918091801_1](https://user-images.githubusercontent.com/113842725/190913615-7e62886a-fdfb-40bf-a2b7-a31719cc5b53.jpg)
![20220918091727_1](https://user-images.githubusercontent.com/113842725/190913616-33c0dba2-61c6-404f-b2e8-c822163dfdda.jpg)

**Comment by Tansimmo2** [comment]
Do you see how the bottom image shows my guns and all items. When I press save they all disappear. Certain items also do not save so if I were to load that kit they would be gone. Example acre radios.

**Comment by Moltag12** [comment]
Me and my whole unit have the same problem, i've even tried downloading v. 3.15.0 and it's still not saving/loading loadouts

**Comment by zharf** [comment]
Tried testing this a little bit, only thing I saw was the equipment icons in loadouts list disappearing when saving but the loadout was still what I had built and the loadouts list had all the icons again when I reopened the view...

**Comment by Tansimmo2** [comment]
yeah so certain items keep but certain don't. I don't know how it determines what. But if you have acre downloaded and add acre radios they do not save and will disappear. Also if you load the kit right after saving it also deletes your primary gun. Again idk why or what determines it to do this but my unit to is also having issues with this

**Comment by Tansimmo2** [comment]
If it helps my discord is 𝕽𝖆𝖉𝖎𝖈𝖆𝕷#4326 and im in the ace discord. If you want me to stream and show you I can. Just dm or ping me

**Comment by PulsarNeutronStar** [comment]
https://www.youtube.com/watch?v=f8JOc6OALrE

Ace arsenal loadouts removes acre radio#s that are not "fresh out of the box" seen here with the "ch: 1". If oyu use a "blank" and save it during equipping it, it will save the item in the loadout.

**Comment by Tansimmo2** [comment]
Hey thanks for using a video, so we save the radios as soon as they are grabbed from the arsenal not after they are used. So sadly this did not fix the issue. Also when you save a normal load out your guns do not disappear however ours do so that is odd.

**Comment by PulsarNeutronStar** [comment]
Even Vanilla mods? what mod do you use for guns?
when do you save the loadout? are you talking ace loadouts inside the arsenal screen or sth else?
