### ISSUE TITLE
Old Man Scenario

### ISSUE THREAD

**Issue by cultysdaop** [acemod/ACE3#9046]
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]

**Description:**

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. _Go to ..._
2. _Click ..._
3. _See ..._

**Expected behavior:**
Old Man Scenario bug, I have black screen when i wanna play Old man scenario, only mods i have is just latest ACE/CBA versions.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/114610726/192856113-2eb0789b-27ac-43ba-9bac-3b87a64a06e7.png)
![083968dc-2312-4e8a-b3d1-16b71bf551bf](https://user-images.githubusercontent.com/114610726/192856282-d14b6058-19b9-4ca2-ae77-2f193059f268.png)

**Comment by acknowledge14** [comment]
Try to save then reload the game.

**Comment by cultysdaop** [comment]
I will try, But I dont think it will change sometimes.
Did you tried it, did it work?

**Comment by cultysdaop** [comment]
> Try to save then reload the game.

I will try, But I dont think it will change sometimes.
Did you tried it, did it work?

**Comment by jonpas** [comment]
Fill out the issue template fully and reopen once you do. You did not even provide an RPT file.
