### ISSUE TITLE
ace insignia

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#906]
https://github.com/acemod/ACE3/issues/414

definitely requirered for 3.0.0

**Comment by kripto202** [comment]
ill get this done

**Comment by kripto202** [comment]
already done where do i put it?

**Comment by commy2** [comment]
mega, mediafire, google drive?

Don't put them on imgur. They tend to convert stuff to .jpgs.

**Comment by kripto202** [comment]
https://dl.dropboxusercontent.com/u/109788043/ace%20patch.zip no need do anything its fully done already

**Comment by commy2** [comment]
![http://i.imgur.com/sT1MYyB.png](http://i.imgur.com/sT1MYyB.png)

I think it needs a background, just like:

![https://cloud.githubusercontent.com/assets/8568526/7381514/096e724c-edd2-11e4-96fb-d5b603970a62.png](https://cloud.githubusercontent.com/assets/8568526/7381514/096e724c-edd2-11e4-96fb-d5b603970a62.png)

I also think 256x256 is a bit much for such a tiny graphic. Maybe 128x128? Dunno what the other insignias use.

**Comment by kripto202** [comment]
it will still get stretched even if its 128x128 ill add a shadow or do you want me to do something like that badge?

**Comment by commy2** [comment]
A badge.

**Comment by kripto202** [comment]
got ya already on it

**Comment by commy2** [comment]
Will implement it tmomorrow. 3am...

**Comment by kripto202** [comment]
![ace3](https://cloud.githubusercontent.com/assets/8568526/7383273/a68164fa-edea-11e4-954b-0bbb41350f84.png)

**Comment by kripto202** [comment]
need to move the letters around but you get the idea

**Comment by kripto202** [comment]
![ace3_1](https://cloud.githubusercontent.com/assets/8568526/7383329/5fb0ee5a-edeb-11e4-8d8b-63c1a519d6b8.png)

**Comment by kripto202** [comment]
https://dl.dropboxusercontent.com/u/109788043/ace%20patch.zip

**Comment by PabstMirror** [comment]
![ace_patch2](https://cloud.githubusercontent.com/assets/9376747/7384409/2b980de4-edf8-11e4-8227-754a9a3d272f.png)

**Comment by Jastreb** [comment]
Something like this would be nice ![ACE2](http://dslyecxi.com/images/arma/ttp/ace_logo.jpg)

**Comment by bux578** [comment]
I don't approve vandalizing the logo.

**Comment by cych** [comment]
Jastreb Logo was the ACE 2 official One.

it may be better to make the logo to evolute to differenciate each ACE version.

the current ACE 3 logo seems good :

http://www.armaholic.com/datas/users/ace3-header_4.png

**Comment by Tachii** [comment]
Well it still must an insignia, not just a logo. It must have some clothing background

**Comment by bux578** [comment]
I'll take care of it

**Comment by commy2** [comment]
![http://i.imgur.com/6IlIy1F.png](http://i.imgur.com/6IlIy1F.png)

I approve of this one.

**Comment by bux578** [comment]
I'm gonna throw that one out. :stuck_out_tongue:

**Comment by commy2** [comment]
Nooooo. You can add a new one.

**Comment by kripto202** [comment]
Nothing says you only can have one

**Comment by alganthe** [comment]
moar insignias MOAR

**Comment by kripto202** [comment]
I hope you don't mind me adding my insignia to my "kommunity" insigias

**Comment by VyMajoris** [comment]
I did this: ![Imgur](http://i.imgur.com/vzANPNJ.png)
https://www.dropbox.com/s/37hzsllchr2ma3g/ace3-logo-white-patch-oldschool-v1.psd?dl=0
I got the fabric pattern for the texture from(don't know if the .PSD file incorporates third party pattenrs) here:http://wegraphics.net/wg-downloads/free/textures/wg_fabric_patterns_sample.zip

Also you guys should probably fix the sloppy job I did on removing the background.

**Comment by kripto202** [comment]
@VyMajoris thank you for the texture

**Comment by Jastreb** [comment]
:+1:

**Comment by SilentSpike** [comment]
Could use a little cleaning up but I like it! :+1:

**Comment by Gruntin** [comment]
![1f44d](https://cloud.githubusercontent.com/assets/8108758/7405749/41b68344-eec5-11e4-8e71-dd973f933697.png)

**Comment by bux578** [comment]
![1](http://i.imgur.com/8Sl8muD.jpg)
![1](http://i.imgur.com/A72DRON.jpg)

**Comment by Jastreb** [comment]
No skull? Meh Ill do my own config.

**Comment by kripto202** [comment]
@Jastreb if you want, send me your insignia and ill add it on the next update for my mod

**Comment by cych** [comment]
VyMajoris's one is exactly  what i was expecting.  the Bones, the skull, the "ACE" and a red "3"

**Comment by Jastreb** [comment]
@kripto202 what @cych said use texture provided by @VyMajoris
