### ISSUE TITLE
Texture missing

### ISSUE THREAD

**Issue by HestiqWolf** [acemod/ACE3#9068]
Hello,
 I have a problem it seems that Ace has something outdated  that crash my game then make me go back to the Eden editor(2 second after the game launch) i try to repair the mod with the Arma 3 Launcher but doesn't seem to solve the problem is there any way i could fix it and if i can how could i do it?

![20221010195606_1](https://user-images.githubusercontent.com/115497129/194928977-12887aee-a855-4bdb-a54a-592fbcdf178e.jpg)

(Black square were my contacts on discord wish to just mask it)

Have a nice day

**Comment by Drofseh** [comment]
Please fill out the issue template correctly in the future.

Always test with *only* CBA and Ace3 loaded.

You are probably loading a 2nd copy of Ace3, please uoload your RPT as required by the issue template and i will have a look.

**Comment by jonpas** [comment]
Reopen when issue template is filled.
