### ISSUE TITLE
Banana clacker not showing on ACE Interaction Menu

### ISSUE THREAD

**Issue by Eughenos** [acemod/ACE3#9072]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10.0.149973`
- **CBA:** `v3.15.8.220912` 
- **ACE3:** `3.15.2` 

**Description:**

Create a "**banana_clacker**" copy pasting the Explosives Framework ACE3. The detonator appears as an item everywhere but when you try to trigger the banana_clacker to an explosive charge through ACE INTERACTION MENU the detonator is not listed.

**Steps to reproduce:**

1) Create a config.cpp with the banana_clacker code (copy paste from https://ace3.acemod.org/wiki/framework/explosives-framework.html#)
2) Launch Arma with only CBA and ACE3
3) Add the banana_clacker as an item and any explosive charge (already known as 100% compatible) to a bot and play that bot
4) Place the charge through MENU ACE (Ctrl + Win -> Explosive -> Place charge)
5) Interact with the placed charge to trigger the detonator (Win -> Interactions -> Select a Trigger)

**Expected behavior:**

When you want to select a trigger (step 5) the banana clacker doesn't appear. Only Timer is available.

**Where did the issue occur?**

It appears on all types of Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**

No logs uploaded but very easy to understand and reproduce.

**Additional context:**

Tried together with MikeMF (discord moderator) and he suggested me to open an issue topic here,

**Screenshots:**

No screenshot available

**Comment by Eughenos** [comment]
After 29 days I am still stuck on this problem/bug

**Comment by bux** [comment]
Please join discord and use the help channels

**Comment by Eughenos** [comment]
MIkeMF sent me here form discord...
