### ISSUE TITLE
Enemy and friendly AI sliding along the floor when unconscious

### ISSUE THREAD

**Issue by Xanderarizona** [acemod/ACE3#9073]
It's easy to reproduce and I've narrowed it down to just being Ace but for some reason if you hit an enemy regardless of settings there is a small chance they will fall to the ground and the unconscious position yet still be able to Fire and move around making it extremely difficult to hit them or determine if anyone's dead or not, they will often be stuck Frozen looking somewhat like this while sliding around just face down on the ground
![simple-dark-green-plastic-toy-soldier-holding-a-pistol-and-a-machine-gun-in-hands-holding-them-up-in-a-victory-gesture-infantry-figure-object-isolated-2BCNTAT](https://user-images.githubusercontent.com/94261177/195986764-99e24b10-7a3b-4c6d-a131-107e575c40ed.jpg)

It does not matter if I set the AI to die instantly from being shot not allowed to go unconscious or anything else it seems that it happens no matter what settings are put in

**Comment by Drofseh** [comment]
Please fill out the issue template correctly.

**Comment by jonpas** [comment]
Reopen when issue template is filled.
