### ISSUE TITLE
Zeus Symbol

### ISSUE THREAD

**Issue by Philipp-00** [acemod/ACE3#9075]
Hey guys,

quick question, does anyone know how the logo disappears? This is visible to all players, Zeus or not.
![20221016172947_1](https://user-images.githubusercontent.com/115901608/196044093-7e74cab8-9709-4433-9ebe-653c04ae3f90.jpg)

**Comment by jonpas** [comment]
This probably has nothing to do with ACE.

Fill out the issue template if you want someone to even attempt to help you.
