### ISSUE TITLE
View restrictions

### ISSUE THREAD

**Issue by Philipp-00** [acemod/ACE3#9076]
Our view settings work fine when creating a virtual server in the editor. Once the mission is on the main server, nothing works anymore and only the first person is on.
ArmA3 vanilla setting:
Difficulty: Custom
Third persons allowed.

Our Ace-Settings
https://pastebin.com/G5USUBEp

![unknown](https://user-images.githubusercontent.com/115901608/196052521-f2c8e887-76f4-4ff1-9b5f-3f5fd7d6cfef.png)

**Comment by Drofseh** [comment]
Please fill out the issue template

**Comment by Philipp-00** [comment]
What the....?
What more should I write about that? I mean, except that we first fixed the bug ourselves, then an ACE update came and broke everything up again. There's not much to reproduce or search for. Everything that has fixed the error so far or all settings for the error are there. From my point of view, the ACE settings are not compatible with ArmA3 Vanilla in this case.
I can tell you what I said above...
current ACE version freshly updated
current ArmA3 version
before the update everything worked fine. Since the update, ACE has been regularly shooting up the missions.

**Comment by jonpas** [comment]
We cannot provide help withour an RPT file or any other details that you can provide as listed in the template.

Don't reopen until provided.

**Comment by Philipp-00** [comment]
[RPT1.txt](https://github.com/acemod/ACE3/files/9946959/RPT1.txt)
[RPT2.txt](https://github.com/acemod/ACE3/files/9946960/RPT2.txt)

In the meantime we have fixed all ACE settings ourselves. The only bug that is still open is the view restriction. Despite settings, the 3rd person view in vehicles is denied.
