### ISSUE TITLE
Weapon UnHolster after Carrying Object

### ISSUE THREAD

**Issue by Holgerhollebolle** [acemod/ACE3#9077]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.8` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.15.2` [eg. 3.0.0 stable, commit hash]

**Description:**
Currently if you have a Weapon holstered and carry a Box the Weapon gets unholstered when you drop the box. 
Same issue when you go into a virtual Arsenal. When you leave the Weapon gets unholstered.
This is very anyoing especially when you do a lot of logistics.

**Steps to reproduce:**

1. Holster your Weapon
2. Carry any Item (ACE Logistics)
3. Drop the Item
4. --> Weapon gets unholstered

**Expected behavior:**
The Weaon should stay in Holstered state after droping an Item/leave an Arsenal

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by Dystopian** [comment]
will be fixed in #9052

**Comment by LinkIsGrim** [comment]
Fixed in #9052.
