### ISSUE TITLE
Holstering Weapon lets Unit Slide when moving

### ISSUE THREAD

**Issue by Holgerhollebolle** [acemod/ACE3#9078]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.8` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.15.2` [eg. 3.0.0 stable, commit hash]

**Description:**
When you move forward while holstering the Weapon the Unit is sliding on the Ground. This breaks immersion quite a bit.
Holstering needs to stop the movement of a Unit until the Animation is finished.

**Steps to reproduce:**

1. Holster Weapon and quickly move forward
2. --> Unit is moving without walk animation

**Expected behavior:**
While Holstering the Forward walking should be disabled until the Animation of Holstering is finished.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
