### ISSUE TITLE
Micro Dagr support for (air) Vehicle sensors

### ISSUE THREAD

**Issue by TheExiledCat** [acemod/ACE3#9083]
Certain vehicles in arma have camera sensors or FLIRs that dont show grid coordinates of the point you are looking at with them as they dont use the basic arma sensor system. it would be cool if (like with the vector 21) the micro dagr could connect to a locked laser point (just the regular laser point inside of the targets sensor where you can cycle trough available targets, radar signatures etc.) and then give the grid coordinate of that point as the vector 21 would. oobviously this wouldnt just be for vehicles but it would have a positive effect on them. ground users or JTACs could use this to their advantage too if they had to both lase and range find at the same time as there is no laser Rangefinder combo in vanilla. this way the jtac could lase a target and at the same time get the grid of that point using the laser designator.

**Comment by Drofseh** [comment]
All feature request must go in the Feature Requests issue #3594
