### ISSUE TITLE
ELCAN SpecterOS (PIP) Optic drops Framerate a lot

### ISSUE THREAD

**Issue by Holgerhollebolle** [acemod/ACE3#9087]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.8` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.15.2` [eg. 3.0.0 stable, commit hash]

**Description:**
ELCAN SpecterOS (PIP) Optic drops Framerate a lot.

**Steps to reproduce:**
- Create a new Mission in EdenEditor on Altis or Malden
- Create a Riffleman
- Change Optic to ELCAN SpecterOS (PIP)
- Run Mission in Editor
--> Very low Framerate (I have 9 FPS here)

**Expected behavior:**
Framerate should not drop

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by BaerMitUmlaut** [comment]
PIP is very performance intensive. Nothing we can do here.

**Comment by Holgerhollebolle** [comment]
I am not talking about a little performance drop. It’s dropping from 60fos to 9 fps. Making it unusable. I have not had this issue earlier with other PIP scopes.

**Comment by GeorgeBAS** [comment]
I have had the same experience running only ACE and CBA, it only occurs with this PiP scope, and not with any mods either.
