### ISSUE TITLE
BattleEye Triggering on DLLs.

### ISSUE THREAD

**Issue by jeff7890110** [acemod/ACE3#9088]
**Mods (complete and add to the following information):**
- **Arma 3:** "profiling, and stable base Arma 3, from Steam" [e.g. 1.00 stable, rc,  dev]
- **CBA:** `Current Version from Steam, Last Updated Sept 13th.`
- **ACE3:** `Current Version from Steam, Last Updated 9/27/22`

**Description:**
BattleEye is blocking of loading the DLLs for ACE.

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. _Load ACE and CBA inside the launcher_
2. _Click Play with mods, while watching the BattleEye window inside the launcher._
3. _Look at the battleeye log._

**Expected behavior:**
Shouldn't be blocking

**Where did the issue occur?**
- I started in multiplayer, then it moved to being inside the eden editor, now I can't even load Arma 3.

**Log Files:**
- 

**Additional context:**
- If I start Arma 3, without BattleEye, no issues arise. It still loads perfectly fine.

**Screenshots:**
![image](https://user-images.githubusercontent.com/71680995/199325599-224637a8-2eff-4dca-b772-6f3890080ece.png)

**Comment by BaerMitUmlaut** [comment]
This is a BattlEye issue.
The easiest way to fix this is to disable BattlEye. If that's not an option, make sure that no firewall or antivirus software is blocking BattlEye.
