### ISSUE TITLE
Deactivation of Vanilla GPS as an option

### ISSUE THREAD

**Issue by STyx2909** [acemod/ACE3#9090]
### Do not post feature requests here!

Learn how to make a feature request [here](https://ace3.acemod.org/wiki/user/how-to-make-a-feature-request.html).

Would it be possible to add an option in ACE settings to allow/not allow use of vanilla GPS?
A MilSim immersion would only rely on other type of GPS.

**Comment by Drofseh** [comment]
> ### Do not post feature requests here!
> Learn how to make a feature request [here](https://ace3.acemod.org/wiki/user/how-to-make-a-feature-request.html).

Did you not read?
