### ISSUE TITLE
AI shooting unconscious player

### ISSUE THREAD

**Issue by TheFrostyPyro** [acemod/ACE3#9093]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10` 
- **CBA:** `v3.15.8.220912` 
- **ACE3:** `3.15.2` 

**Description:**
During gameplay when a player goes unconscious AI will continue to shoot the player. Normally in all previous versions of ACE as far as I remember when a player goes down their Zeus Icon will change to purple as opposed to blue and AI will cease fire and no longer recognize them as enemy. Oddly this issue does not occur all of the time even with the same reproduction steps. However, when it does happen, it will continue to happen until the server or editor is restarted.

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. _Go to any Dedicated, Eden or Self-Hosted Multiplayer server
2. _Enter Zeus and Spawn any Opfor ground unit as BluFor
3. _Let the enemy units damage the player until the unit goes unconcious
4. _See if the AI will continue to engage

**Expected behavior:**
OpFor AI will continue to see and shoot unconcious player from considerable distances, even when the currently engaged units are deleted and new OpFor are spawned in. Occurs roughly 75% of the time.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Singleplayer)

**Additional context:**
Issue was successfully reproduced with only CBA and ACE3.

Additionally as discussed in discord I was attempting to mitigate the issue by using event handlers. I apologize if this is the wrong location to ask however the event handler I came up with is {
  
  if (local _x  _ace_unconcious) then { _x setCaptive _object; };
} forEach group0;

This is my first time using event handlers, if it would take effort to check that handler for errors please ignore it. Thank you very much for your help.

**Comment by rautamiekka** [comment]
I see multiple problems with your code:
```sqf
{
    if (local _x _ace_unconcious) then { _x setCaptive _object; };
} forEach group0;
```
->
```sqf
{
    if (_x getVariable ['ACE_isUnconscious', false]) then { _x setCaptive true; };
} forEach (units group0 select {local _x});
```
Not sure if you meant set not captive (`_x setCaptive false`) or set captive (`_x setCaptive true`) cuz `_object` doesn't say way or another; [`setCaptive`](https://community.bistudio.com/wiki/setCaptive) requires either a boolean or an integer.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
