### ISSUE TITLE
Fortify categories

### ISSUE THREAD

**Issue by ZoltanGris** [acemod/ACE3#9097]
When using the "My Preset" in the fortify module and putting this script in the description.ext file - 
class ACEX_Fortify_Presets {
    class myMissionObjects {
        displayName = "My Preset";
        objects[] = {
            {"Land_BagFence_Long_F", 10},
            {"Land_CamoNet_NATO_EP1", 30},
	    {"Land_BagBunker_Small_F", 160},
	    {"Land_BagBunker_Large_F", 320},
        };
    };
};

Is it possible to create sub categories so we can add a multitude of objects without the menu being to cluttered

**Comment by Deviss72** [comment]
Im  interested too in this feature, any update on this ?
