### ISSUE TITLE
Interaction menu for setting trigger on explosives is glitchy

### ISSUE THREAD

**Issue by kerckasha** [acemod/ACE3#910]
ACE3 Version: 3.x.x

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None

**Description:**
When you place an explosive on the ground and attempt to interact with it, when highlighting the trigger the interaction menu stops working and causes it to 'flicker'.

This happens regardless of menu settings or using mouse cursor.

**Video:**
http://a.pomf.se/rlotss.webm

**Steps to reproduce:**
Place explosive on the ground, attempt to set a trigger.

**Where did the issue occur?**
Singleplayer, Editor

**RPT log file:**
http://pastebin.com/E2e4urNx

**Comment by bux578** [comment]
#828

**Comment by commy2** [comment]
404 mine not found
