### ISSUE TITLE
No belt linking for static weapons. 

### ISSUE THREAD

**Issue by BeeTeaArr** [acemod/ACE3#9103]
Mods (complete and add to the following information): cba + ace, also tested with cba + ace + SOG compat. 
- **Arma 3:** 2.10.149954, main. 
- **CBA:** 3.15.8 stable
- **ACE3:** 3.15.2 stable

**Description:**
Crew Served weapons do not allow external linking of belts as was possible in earlier versions of ACE3. 

**Steps to reproduce:**

1. Set up or assemble any crew served weapon in any environment. 
2. Carry additional exact matching ammo type that is loaded in the CSW. 
3. Fire a short or a long burst.
4. Attempt to link ammo belt while not manning the weapon.
5. -----> No prompt to link belts appears. 

**Expected behavior:**
Expected behaviour is to have a prompt to link belts which then "tops up" loaded magazine in the CSW while replacing personal inventory item with the used magazine. 

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer).

**Additional context:**
Issue was successfully reproduced with only CBA and ACE3. Initially identified in SOG compat but tested with RHS compats too. Discussed and confirmed as an bug by BaerMitUmlaut in Ace3 discord.

**Comment by BaerMitUmlaut** [comment]
@Salluci I think this line is now looking at the wrong config:
https://github.com/acemod/ACE3/blob/master/addons/csw/functions/fnc_reload_canLoadMagazine.sqf#L56

**Comment by Salluci** [comment]
I'll take a look as soon as I have computer access again.
