### ISSUE TITLE
fnc_registerItemReplacement have awkward behavior while in Arsenal

### ISSUE THREAD

**Issue by C0NS03L** [acemod/ACE3#9104]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10 profiling`
- **CBA:** `3.15.8 stable`
- **ACE3:** `3.15.2 stable`

**Description:**
When a mission/mods uses fnc_registerItemReplacement to replace an item (A) with another (B)
Let's call Item we want to replace: A
and replaced item(s): B
arsenal will have weird behavior where the count of A stays at 1 and the count of B stays at 0 but the weight increase when you add more of A. It seems like item were converted but the count of B are not updated until you leave and re-enter the arsenal.

Furthermore, having count of A stays at 1 seems odd to the players if they want to add multiple of A. Or players accidentally add more than they actually want but they can't remove it directly because the item are already converted

An built in example of this would be vanilla IFAK which would be converted to bandages and some other medical stuff

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. Enable replace vanilla items in ACE Medical Settings
2. Enter ACE Arsenal
3. Add First Aid Kit to the player

**Expected behavior:**
Not replacing items while user is in arsenal

**Where did the issue occur?**
- Self Hosted Multiplayer
- Single Player

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- https://pastebin.com/1GXLfcyw

**Additional context:**
Found this problem with KAT Advance Medical mod where painkillers are hard to access since it is in Magazines Catagory due to technical limitations. So the devs uses ace_common_fnc_registerItemReplacement to put a pseudo item in "misc" catagory and replace it with the real painkiller box.

**Screenshots:**
[If applicable, add screenshots to help explain your problem.]
https://user-images.githubusercontent.com/58496201/204175161-e7b4422a-4eab-41e7-8501-b8af895af0aa.mp4

**Comment by BaerMitUmlaut** [comment]
> **Expected behavior:**
Not replacing items while user is in arsenal

While the display is open? While the mission is running? What if the replacement occupies more inventory space than the original item? I don't think that is a viable alternative.

**Comment by C0NS03L** [comment]
> > **Expected behavior:**
> Not replacing items while user is in arsenal
> 
> While the display is open? While the mission is running? What if the replacement occupies more inventory space than the original item? I don't think that is a viable alternative.

Didn't thought about the inventory space, how does the function currently handles it when converted item does not fit?

Another alternative would be updating the replacement item count correctly, but would not be ideal for players if they changed their mind or something. Also the count of replaced item would probably stays at 1

Do you have any suggestions of a solution to this?

**Comment by BaerMitUmlaut** [comment]
No, I was hoping you would have one 😅
