### ISSUE TITLE
ACE Cargo actions don't show up under special circumstances with JIP

### ISSUE THREAD

**Issue by y0014984** [acemod/ACE3#9109]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10` profiling
- **CBA:** `3.15.8`
- **ACE3:** `3.15.2`

**Description:**
If the ACE cargo status for an item is changed mid-mission (turn on and then turn off), a new JIP player won't see further changes of the ACE Cargo status of that item, see steps to reproduce. If the status for that item wasn't changed before the new player joins, the problem doesn't occur. If there are no JIP players (all players logged in since server start) the problem also doesn't occur.

**Steps to reproduce:**
1. Start Empty Mission (containing only a random object and 2 player slots) in dedicated mp **or hosted mp**
2. join player1 (or start mission with already joinded player1)
3. enable ace cargo for object via debug console on player1 ( `[cursorObject, 1] call ace_cargo_fnc_setSize;` )
4. disable ace cargo for object via debug console on player1 ( `[cursorObject, -1] call ace_cargo_fnc_setSize;` )
5. join player2
6. enable ace cargo for object via debug console on player1 ( `[cursorObject, 1] call ace_cargo_fnc_setSize;` )

**Expected behavior:**
The JIP player2 should see the ACE3 Cargo interactions that player1 had enabled (Cargo and/or Rename)

**Where did the issue occur?**
- Dedicated / Hosted MP

**Log Files:**
- [client RPT](https://gist.github.com/y0014984/0b5fa41875a63bf84b06c94f9af15256)

**Additional context:**
I think the variable `ace_cargo_setSize_jipID` set on the object prohibits the expected behavior. If I execute the following command (deleting the var) on player1 right before enabling ACE3 Cargo, the problem never occurs:
```sqf
cursorObject setVariable ["ace_cargo_setSize_jipID", nil, true];
```

**Screenshots:**
There are no helpful screenshots, except showing the missing interactions.

**Comment by johnb432** [comment]
@y0014984 Your reproduction steps for the issue you describe make no sense.
`[cursorObject, -1] call ace_cargo_fnc_setSize;` disables cargo interactions, which disables both loading and renaming.

I ran your reproduction steps and everything worked as expected.

**Comment by y0014984** [comment]
@johnb432 Sorry for that. The last step (step 7) makes no sense. You are right. I modified the issue accordingly. I have tested that behavior right now with ACE3 3.16.1 and I still can reproduce it. If the player1 changed cargo feature by activating and then deactivating it then any next change (enabling again) will not be available/visable for JIP players.

**Comment by y0014984** [comment]
I created this video to illustrate the issue. I hope that helps. https://www.youtube.com/watch?v=1TZNOgBXq-8

**Comment by johnb432** [comment]
So I can reproduce the issue you describe, but only for specific objects (e.g. `"Land_VergeRock_01_F"`). Those don't have cargo enabled by default.
I'll look into it.

**Comment by johnb432** [comment]
I found the problem. As I'm working on a refactor of the cargo module, I'm going to include it there.
