### ISSUE TITLE
Laser pointed into sky issue

### ISSUE THREAD

**Issue by darknightx33x** [acemod/ACE3#9125]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10` [Main]
- **CBA:** `v3.15.8.220912` [Main]
- **ACE3:** `3.15.2` [Main]

**Description:**
When using a weapon IR laser. It normally produces a laser beam extending from your gun that is easily visible with a set of NVGs on. If you move the laser pointer around on the ground, it works without issue. However, as soon as you point it upwards and not at any land, the laser beam will just disappear. Pointing it again back at land and it will reappear.

**Steps to reproduce:**
1. Go into editor and pick any map
2. Place a unit with any weapon and vanilla IR laser, and NVGs
3. Set time to night
4. In game, turn on NVGs and laser. 
5. Point laser into sky to see it disappear
6. Point laser out ground to see it reappear.

**Expected behavior:**
Laser beam is visible regardless of what/where it is pointed. See vanilla arma clip

**Where did the issue occur?**
Singleplayer / Editor (Singleplayer)

**Additional context:**

Vanilla arma laser test
https://user-images.githubusercontent.com/44118889/212521498-3080dfb2-5870-47ae-b6fc-c28744044646.mp4

Ace arma laser test
https://user-images.githubusercontent.com/44118889/212521502-a3142b02-71ed-4125-915d-6b2d109c2e0d.mp4

**Comment by darknightx33x** [comment]
> Please add an RPT, cannot reproduce.

You're asking

**Comment by darknightx33x** [comment]
> Please add an RPT, cannot reproduce.

You're asking for a crash report when it doesn't crash the game. 
I got people reproduce the exact steps above and reproduced it without issue. 

please reread the issue, and follow the above steps.

**Comment by darknightx33x** [comment]
Ok. I think I got the rpt to file to work. I converted it to a txt file. 

[Arma3_x64_2023-01-22_12-05-37.txt](https://github.com/acemod/ACE3/files/10475026/Arma3_x64_2023-01-22_12-05-37.txt)

**Comment by BaerMitUmlaut** [comment]
> I got people follow the exact steps above and reproduced the bug without issue.
please reread the issue, and follow the above steps.

![107410_20230122212117_1](https://user-images.githubusercontent.com/9693842/213938438-8fb7a842-154b-494d-bb43-506a84099f8d.png)

**Comment by darknightx33x** [comment]
https://www.youtube.com/watch?v=0MBNd1NY91M

**Comment by darknightx33x** [comment]
I wish it just worked like that. If you are doing something different to get it to work. I would love to know. Are you on a different version of ACE? A dev branch version if you guys have it? Your image at least shows you are at least on different build of arma.

**Comment by Mike-MF** [comment]
I managed to replicate this on a fresh profile only with CBA/ACE enabled.

It was working perfectly fine until i turned pretty much all my video settings to low / disabled. Once I'd done that i can replicate it pretty easily.

**Comment by PabstMirror** [comment]
possibly related to https://github.com/acemod/ACE3/blob/master/addons/nightvision/CfgIRLaserSettings.hpp
```
class CfgIRLaserSettings {
    maxNumberOfRays = 64; // Default is 24.
```

**Comment by BaerMitUmlaut** [comment]
Sounds like an Arma bug to me. We certainly don't toggle the laser on or off.

**Comment by darknightx33x** [comment]
Mike-MF is right. 

Adjusting view distance fixed it. My view was 500m but just buried in the ace view distance in addon options instead of the 1 or 2km I had in options.
