### ISSUE TITLE
How to disable Weapon cooked off! messages

### ISSUE THREAD

**Issue by mwpowellhtx** [acemod/ACE3#9126]
AFAIK, latest mods in everything. I am not even in game and I am receiving spurious `Weapon cooked off!` messages. How do I disable this entirely for weapons? Although still possibly interested in vehicle cook offs i.e. on detonation. Are they similar, overlap, or if I disable one does it also disable the other? In any event, the WCO not ready for prime time in its current condition.

**Comment by BaerMitUmlaut** [comment]
Please fill out the issue template.
