### ISSUE TITLE
Fire does not spread when carried

### ISSUE THREAD

**Issue by mjc4wilton** [acemod/ACE3#9127]
**Mods:**
- **Arma 3:** `2.10`
- **CBA:** `3.15.8`
- **ACE3:** `3.15.2`

**Description:**
When a unit picks up / carries a unit that is on fire, the carrying unit does not catch fire.

**Steps to reproduce:**
1. Have player 2 catch fire
2. Player 1 picks up player 2
3. Player 1 is not on fire

**Expected behavior:**
If you pick up someone who is on fire as another flammable human, you should also catch fire.

**Where did the issue occur?**
Dedicated Server

**Log Files:**
N/A

**Comment by LinkIsGrim** [comment]
Seems to have been handled in #8632? Works now anyway.
