### ISSUE TITLE
fakeprimaryweapon available in the arsenal

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#913]
ACE3 Version: 3.0.0.1 last commit d149db61e8ca98384a19e7b1381c9bc2f68452a5

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* none

**Description:**
* The weapon fakeprimaryweapon is available in the arsenal (a blank above empty)

**Steps to reproduce:**
first method
go to virtual arsenal and click on the blank.

second method
access arsenal everywhere else and notice it's there.

**Where did the issue occur?**
SP,editor,VR

**RPT log file:**
nothin'

**Comment by Glowbal** [comment]
It should be fixed now but I cannot test.

**Comment by alganthe** [comment]
fixed in #913 closing
