### ISSUE TITLE
Ace error

### ISSUE THREAD

**Issue by Blamp26** [acemod/ACE3#9136]
CBA version 3.13.0.191116 is outdated (required 3.15.7)

**Comment by Blamp26** [comment]
[Arma3_x64_2023-01-28_13-07-32.zip](https://github.com/acemod/ACE3/files/10527093/Arma3_x64_2023-01-28_13-07-32.zip)
rpt issue file

**Comment by PabstMirror** [comment]
`D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@Pain of Donbass2- Debaltseve\addons\cba_main.pbo - 43ac212e`
looks like this mod has an old version of CBA 3.13 built into it and is breaking the loading of the real CBA
