### ISSUE TITLE
Transparent line at the left side of the screen in Vector 21 optic

### ISSUE THREAD

**Issue by Timi007** [acemod/ACE3#9141]
**Mods:**
- **Arma 3:** `2.10`
- **CBA:** `3.15.8`
- **ACE3:** `3.15.2`

**Description:**
There is a transparent line at the left side of the screen when looking throught the Vector 21 optic. See screenshot below. This problem also occurs with the Vector 21 Nite varient.

**Steps to reproduce:**

1. Equip Vector 21
3. Look through the optic
4. See transparent line at the left of the screen

**Expected behavior:**
Complete black vignette at the edges of the screen just like at the right side.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer)

**Log Files:**
- [RPT](https://pastebin.com/T3h8G572)

**Additional context:**
- Display mode: Fullscreen Window
- Resolution: 2560x1440 (16:9)
- Interface size: Very small
- It seems to me, the black rectangle at the left edge should just be one or two pixel wider.

**Screenshots:**

![vector21](https://user-images.githubusercontent.com/9505872/216475647-f6c12087-b955-46be-9b9f-34ddd8c05a84.jpg)

**Comment by BrettMayson** [comment]
Closing as this was a CBA bug that will be fixed with the next CBA release
