### ISSUE TITLE
Seat switch limitation for some MBTs, IFVs, APCs

### ISSUE THREAD

**Issue by cych** [acemod/ACE3#915]
Maybe it's already implemented, but  ACE important feature was the seat switch restriction for some vehicles.  Vehicles that don't have the possibility IRL to let the crew to change seat (from driver to gun, or vice-verca).  follwing vehciles : Abrams, T72, T90, BMP2, BMD-1, BMD-2  don't have the possibility to switch seat from driver ot other seats.  meaning the player is forced to get out to change seat.

also, during the ACE 2 developpement I posted a feature request concerning seat switch delay for vehciles, avoiding the magical instantaneous seat switch : 

here was the ticket :  http://dev.withsix.com/issues/29279

**Comment by jaynus** [comment]
None of those vehicles exist in vanilla ArmA3. This would be a framework we would supply to other mod makers, and implement somehow on the imaginary future vehicles.

#414
