### ISSUE TITLE
Zeus cannot respawn if dying while in Zeus interface

### ISSUE THREAD

**Issue by warlocc** [acemod/ACE3#9151]
https://github.com/acemod/ACE3/issues/7356 has not been fixed.

**Comment by BaerMitUmlaut** [comment]
Please fill out the issue template.

**Comment by warlocc** [comment]
It was filled out in the issue linked.

**Comment by BaerMitUmlaut** [comment]
The linked issue uses outdated versions of Arma, CBA and ACE. Please upgrade to the newest versions if your issue is identical.

**Comment by warlocc** [comment]
Issue still exists in the newest version. Thus "hasn't been fixed".

**Comment by BaerMitUmlaut** [comment]
Which is why a new issue is necessary.
