### ISSUE TITLE
ace_common_fnc_getInPosition throwing an error

### ISSUE THREAD

**Issue by Zumiii** [acemod/ACE3#9155]
https://github.com/acemod/ACE3/blob/4de8487db0beeeafecbb316abebdf2941ebb508f/addons/common/functions/fnc_getInPosition.sqf#L177

The function is being called by passing the type of the vehicle to the function, where instead there should be the vehicle itself.

**Comment by Drofseh** [comment]
https://github.com/acemod/ACE3/blob/4de8487db0beeeafecbb316abebdf2941ebb508f/addons/common/functions/fnc_getVehicleCargo.sqf#L7

**Comment by PabstMirror** [comment]
Header says string but `params` says object 😄 
seems like this is vestigial code that doesn't get used by anything in ace (ie not used by quickmount)

**Comment by Zumiii** [comment]
Thanks! I use this for a persistency script, so I discovered it by accident.
