### ISSUE TITLE
Global Mobilization border fences can't be cut with the wire cutter

### ISSUE THREAD

**Issue by Nomas-X** [acemod/ACE3#9165]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.12` Stable
- **CBA:** `3.15.8` Stable
- **ACE3:** `3.15.2` Stable

**Description:**
Border fences on the Weferlingen maps in the Global Mobilization CDLC can not be cut with with the wire cutter as there is no interaction to do so.

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. _Go into a mission on the Weferlingen map or place a unit in the editor with the wire cutter._
2. _Walk up to one of the border fences._
3. _Attempt to interact with it via ACE Interaction to cut it down._

**Expected behavior:**
I expected the "Cut Fence" interaction to appear somewhere on the fence, and to be able to execute said interaction to cut down the fence.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer

**Log Files:**
- https://gist.github.com/Nomas-X/0842c4ecd5c32056f2ee22942678f068

**Additional context:**
N/A

**Screenshots:**
No screenshots however I have a video:
https://cdn.discordapp.com/attachments/976224710385877002/1082611474704371722/2023-03-07_13-29-54.mp4

**Comment by mdx97** [comment]
Looks like support was intended to be added by whitelisting the model's P3D ([see here](https://github.com/acemod/ACE3/blob/eab93f739a17a2a40a10042f08bbf8909de228a5/addons/logistics_wirecutter/script_component.hpp#L60-L71C31)), but with the way [`ace_logistics_wirecutter_fnc_isFence` is written](https://github.com/acemod/ACE3/blob/master/addons/logistics_wirecutter/functions/fnc_isFence.sqf), that list will not even be checked if the `configOf` the fence is not null. I tested it, and this is the problem.

I think there's two options to fix:
- Update `ace_compat_gm` to add `EGVAR(logistics_wirecutter,isFence) = 1;` to all the relevant fences.
- Update `isFence` to also check the P3D whitelist even if there is a config entry found for the fence and `ace_logistics_wirecutter_isFence` has not been set on it.

**Comment by mdx97** [comment]
I opened a PR that implements option 2. Seems like the better choice here.

**Comment by rautamiekka** [comment]
Devs will be lazy no matter what, but such a list is still 1 step to the right direction cuz even if the list is incomplete it still makes it faster+easier to add `isFence` to the missing ones.

**Comment by Nomas-X** [comment]
So now we just wait for an update.
