### ISSUE TITLE
Spanish translation guide

### ISSUE THREAD

**Issue by Legolasindar** [acemod/ACE3#917]
# Spanish translation guide / Guía de traducción al español

**Please keep this thread open, it is a guide to unify and group tips and methods to translate correctly.
For convenience for translators, the thread will be in Spanish.**

Como ya somos varios los usuarios que ayudamos en la traducción al español del ACE 3, para poder mantener una traducción uniforme y ayudar a los usuarios nuevos que quieran contribuir, usaremos esta guía como ayuda. Se trata de incluir en la guía pautas comunes de traducción, consejos, y términos claves que creamos necesiten ser fijados.

Sentiros libres de contribuir a la guía para mejorarla. La idea es que entre todos creemos una buena documentación de ayuda y una solida traducción.

### Apoyarnos entre todos

El trabajo en equipo lo hace todo mas complejo, pero al mismo tiempo si se hace bien nos da un producto mejor acabado. Prestad atención al trabajo de los demás y ser receptivos sobre correcciones que os hagan a vuestro trabajo. La idea es que entre todos hagamos la mejor traducción posible.

### Antes de enviar la traducción, actualizar el master

Como buena practica, siempre que vayáis a traducir algo, justo antes actualizar vuestra copia. Haced un merge para aseguraros que tenéis la ultima versión, si podríais estar traduciendo sobre una versión antigua. Es importante porque ya ha pasado esto.

Os recomiendo seguir la [guiá oficial de traducción](https://github.com/acemod/ACE3/blob/master/documentation/development/how-to-translate-ace3.md).

### Tipo de español

El español se habla en muchos sitios, no solo en España, es por eso que deberemos usar un español neutro, intentando usar términos comunes, globales, y evitando así palabras que pueden ser de uso común en un país pero no en otro. Por poner solo un ejemplo practico, de un caso que se nos dio anteriormente, para el termino en ingles **_Cable Tie_** se propuso **_Bridas_**, pero debido a que era un termino desconocido al parecer en América latina, se optó por el termino **_Precinto_**, que es valido en ambos casos.
Aun así puede ser difícil saber cual es el mejor termino, por ello en caso de indecisión, como norma se optaría por seguir la RAE.

No todos los que traducen al español son españoles, y dentro de España también se habla de diferentes maneras el español, al igual que en Sudamérica según el país, es por eso que debemos crear un documento lo mas global posible.

### Traducción correcta, no interpretación

Es importante que a la hora de traducir, no modifiquemos el mensaje original. Nos hemos de centrar exclusivamente en lo que pone, si añadir ni eliminar nada del mensaje, salvó para que sea entendible en español. Esto quiere decir por ejemplo, que si el termino en ingles es **_Give Blood_**, no lo traduzcamos como **_Administrar bolsa de sangre_**, la palabra bolsa no aparece en el original, mantengámonos los mas precisos al original, en este caso **_Administrar sangre_**.

### Capitalización

Este es un error habitual al que debemos prestar atención. En ingles, las palabras se capitalizan, es decir, pueden poner la primera letra de cada palabra en mayúsculas siguiendo sus normas ortográficas. En español en cambio no se capitaliza. Así, y siguiendo el ejemplo anterior **_Give Blood_** No seria **_Administrar Sangre_**, si no **_Administrar sangre_**.
Recordad que si se pueden utilizar mayúsculas cuando son nombres propios, marcas, modelos, etc...

### Mantener modelos o marcas

Es posible que nos encontremos ante casos de marca que podrían tener una traducción. Para hacerme entender pondré como ejemplo en el caso que me inspiro. En Medical, tenemos las **_QuickClot_**, que son un tipo de vendajes hemostáticos coagulantes. Se hubiera podido traducir como **_Vendaje coagulante_** o **_Compresa coagulante_**, pero debido a que **_QuickClot_** es una marca comercial, se a mantenido el termino en inglés.

### Traducciones cortas

Ya sabemos que el texto en ingles suele ser mas corto que en español, esto puede hacer que a veces el texto descuadre, es decir quede fuera de su marco. Para evitar este tipo de situaciones y no complicar mucho la vida a los programadores, intentemos mantener las traducciones lo mas cortas posibles, sin que ello conlleve una traducción extraña.
Siguiendo con los ejemplos en el termino en inglés **_Show vehicle crew info_** primero se sugirió **_Mostrar información de la tripulación del vehículo_**, pero aunque era una traducción totalmente correcta, después se optó por la opción **_Mostrar tripulantes_**.

### Términos acordados

Aquí tenéis la solución que se ha acordado optar a la hora de traducir algunos términos.

Cable tie = Precinto
Wirecutter = Tenazas
QuickClot = QuickClot
Triage card = Tarjeta de clasificación
Cut Fence = Cortar alambrado

**Comment by bux578** [comment]
Could you please make a gist out of it and I'll add it to the http://ace3mod.com/wiki/development/how-to-translate-ace3.html page. Issues are not a place for guides. sorry.
