### ISSUE TITLE
RHS USAF specific vests with Ace compatibility makes torso's invulnerable to damage apart from being bruised 

### ISSUE THREAD

**Issue by PapaHuts** [acemod/ACE3#9175]
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]
- RHS USAF, AFRF, GREF, SAF 
- ACE Compat's for USAF, AFRF, GREF, SAF

**Description:**
When putting USAF SPC, MBAV, SPCS and IOTV Vests on any unit, any small arms fire against their torso region only bruises the unit in the torso region, it doesn't injure them at all. The Vests ballistic protections are also all the way up compared to other vests like the plate carrier vest. 

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. Put one of the vests on a unit in Zeus or 3D editor with arsenal.
2. Use any sort of small arms (Pistol, MG, Rifle like M4 or AK) against unit wearing one of the vests
3. Use Ace Medical to see that their torso regions are only bruised after a full clip dumped into it

**Expected behavior:**
Like any other unit and their vests, I expected the unit to actually be injured and have wounds on their torso, and not just be fully bruised after a full clip.

**Where did the issue occur?**
- This happens in self-hosted multiplayer games, and also in singleplayer editor games as well 

**Log Files:**
- [Arma3_x64_2023-03-25_14-00-54.zip](https://github.com/acemod/ACE3/files/11069725/Arma3_x64_2023-03-25_14-00-54.zip)

**Additional context:**
Nothing I believe to add

**Screenshots:**
![20230325134350_1](https://user-images.githubusercontent.com/109446149/227733896-86930be7-4ebb-47c4-b0b7-57b3a1e5af23.jpg)
![20230325134358_1](https://user-images.githubusercontent.com/109446149/227733899-3dd51409-fd9e-4e9c-a0dd-567c5ec7020a.jpg)
![20230325134405_1](https://user-images.githubusercontent.com/109446149/227733900-af2f5998-f16d-471e-9574-623ae21229b2.jpg)
![20230325134416_1](https://user-images.githubusercontent.com/109446149/227733901-12b301da-1c4b-446c-be25-4e9e19912ac5.jpg)

**Comment by BaerMitUmlaut** [comment]
Duplicate of #9044.
