### ISSUE TITLE
Advanced vehicle damage hitpoints can not be repaired by an engineer

### ISSUE THREAD

**Issue by StormCircuit** [acemod/ACE3#9177]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.12.150301` 
- **CBA:** `3.15.8` 
- **ACE3:** `3.15.2` 

**Description:**
Individual hitpoints for vehicles are gone even with advanced vehicle damage turned on. This is to say, if I knock my offroad's headlights out and then jump out to repair (as an engineer with a toolkit of course) I do not see the headlight marker anymore when observing using ACE interaction. I can, however, see the engine when it is damaged as well as any other part that typically can be seen without advanced vehicle damage turned on.

I tried enabling advanced car damage but having it on/off doesn't appear to change anything.

Another ACE team member by the name of BaerMitUmlaut replicated the issue in discord and asked I make a report.

**Steps to reproduce:**
Spawn in as an engineer with toolkit in any scenario
Spawn any vanilla vehicle
Shoot headlights out
Observe lack of hitpoint marker in ace interaction menu when attempting to repair

**Expected behavior:**
I can repair individual hitpoints that are damaged. Example: I hit a wall and break headlights, I should be able to hop out with a toolkit and repair one or more of the lights

**Where did the issue occur?**
Dedicated and self hosted LAN multiplayer

**Log Files:**
I was told RPT will not matter as I do not have any sort of crash but I would be more then happy to provide all the RPTs from the machines I tried on just ask please, it's a headache for me to round them up.

**Additional context:**
First noticed issue in Overthrow Tanoa, replicated it in NMD Sandbox as I am not very familiar with mission creation or scripting and figured any sandbox mission would be fine.

**Screenshots:**
3 image album of my tests:
https://imgur.com/a/1i13WNi

**Comment by LinkIsGrim** [comment]
Headlights aren't repairable individually, they're ignored when adding repair actions.
