### ISSUE TITLE
MRCO missing PiP version?

### ISSUE THREAD

**Issue by rlex** [acemod/ACE3#918]
ACE3 Version: master

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
* Not sure if bug, but all other A3/ACE optics have 2D, 3D and PiP version, while MRCO have only 3D and 2D.

**Steps to reproduce:**
* Open Arsenal anywhere
* Try to find PiP MRCO
* It's not here!

**Where did the issue occur?**
* VR

**RPT log file:**
* None ATM

**Comment by alganthe** [comment]
use [this form] (http://ace3mod.com/wiki/user/how-to-report-an-issue.html) to report issues.

**Comment by rlex** [comment]
adjusted

**Comment by alganthe** [comment]
Confirmed the MRCO PIP is not available in arsenal

**Comment by rlex** [comment]
https://github.com/acemod/ACE3/blob/master/addons/optics/config.cpp - it's commented out

**Comment by PabstMirror** [comment]
`ACE_optic_MRCO_PIP` is functional, but has some small texture problems

**Comment by commy2** [comment]
It is commentented out, because the graphics don't fit with the PiP model. It will get implemented maybe later.
