### ISSUE TITLE
AI can walk through fortify constructions

### ISSUE THREAD

**Issue by ArwynFr** [acemod/ACE3#9195]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.12`
- **CBA:** `3.15.2`
- **ACE3:** `3.15.8`

**Description:**
AI can walk through fortify constructions

**Steps to reproduce:**

1. Place a building in Eden
2. Build a fortify object on the front door
3. Place AI and give order to move inside

**Expected behavior:**
AI should not be able to walk through the object

**Where did the issue occur?**
- Dedicated
- Self-Hosted Multiplayer
- Editor (Multiplayer)

**Log Files:**
- https://pastebin.com/ymRRFhsn

**Comment by veteran29** [comment]
When AI is moving path LOD/building path the collisions are ignored.
