### ISSUE TITLE
Scripted ACE self-interactions stopped working

### ISSUE THREAD

**Issue by wik-z** [acemod/ACE3#9198]
**Mods (complete and add to the following information):**

Arma 3: 2.12.150301
CBA: 3.15.8
ACE3: 3.15.2.69
**Description:**
The self-interactions added via scripts are not showing up. Running a very simple interaction creation script as attached has no effect, running scripts that used to work in the past doesn't bring any effects either.

**Steps to reproduce:**
1. Run:

```
_unit = player;
_BettIR_Root_Interaction = ["BettIR", "BettIR", "", {}, {true}] call ace_interact_menu_fnc_createAction;
[_unit, 1, ["ACE_SelfActions"], _BettIR_Root_Interaction] call ace_interact_menu_fnc_addActionToObject;
```
2. Open self-interaction menu
3. Observe that there is no interaction "BettIR" when self interaction menu is opened

**Expected behavior:**
The added incteraction successfully shows in the interaction menu

**Where did the issue occur?**
N/A

**Comment by PabstMirror** [comment]
If the statement is empty the action won't show
https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_collectActiveActionTree.sqf#L98C7-L99

you can add anything to make it show like `{6}`

**Comment by wik-z** [comment]
@PabstMirror thanks a lot, that makes sense. It works now.
