### ISSUE TITLE
[arsenal] Load inventory opportunity bug feature not sure which

### ISSUE THREAD

**Issue by mwpowellhtx** [acemod/ACE3#9208]
**Mods:**
- **Arma 3:** `2.12` stable
- **CBA:** `3.15.8` stable
- **ACE3:** `3.15.2` stable

**Description:**
Looking for the ACE analog to the BIS function `BIS_fnc_loadInventory`, if any.

Absent that, looking for a function, or set of functions, which facilitates transformation of the loadouts as they were saved in the `profileNamespace`, `"ace_arsenal_saved_loadouts"` variable.

Failing that, I need to know the ACE loadout inventory shape, ostensibly indexes mapping from the ACE animal to the BIS animal.

For instance, here is a BIS sample as lifted directly out of the namespace. Sorting beyond the top level KVP structure, i.e. `[[_name, _inventory], [_name, _inventory], ...]`; I understand that much.

```
[
["bis test loadout",[["U_B_CombatUniform_mcam",["FirstAidKit","Chemlight_green","10Rnd_762x54_Mag","10Rnd_762x54_Mag","10Rnd_762x54_Mag"]],["V_BandollierB_rgr",["11Rnd_45ACP_Mag","11Rnd_45ACP_Mag","SmokeShell","SmokeShellGreen","Chemlight_green","10Rnd_762x54_Mag","10Rnd_762x54_Mag"]],["B_AssaultPack_khk",["10Rnd_762x54_Mag","10Rnd_762x54_Mag","10Rnd_762x54_Mag","10Rnd_762x54_Mag","10Rnd_762x54_Mag","10Rnd_762x54_Mag"]],"H_HelmetSpecB_snakeskin","G_Tactical_Black","Rangefinder",["srifle_DMR_01_F",["muzzle_snds_B","acc_flashlight","optic_DMS","bipod_01_F_blk"],"10Rnd_762x54_Mag"],["launch_B_Titan_short_F",["","","",""],"Titan_AT"],["hgun_Pistol_heavy_01_F",["muzzle_snds_acp","acc_flashlight_pistol","optic_MRD",""],"11Rnd_45ACP_Mag"],["ItemMap","ItemCompass","ItemWatch","ItemRadio","ItemGPS","NVGogglesB_grn_F"],["WhiteHead_06","male04eng",""]]]
, ...]
```

Compare contrast that with the ACE sample, what I need to know is the `_inventory` mapping making it BIS friendly.

```
[
["ace test loadout",[[["rhs_weap_sr25","rhsusf_acc_SR25S","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_USMC",["rhsusf_20Rnd_762x51_SR25_m993_Mag",20],[],"bipod_03_F_blk"],[],["meu_weap_glock_19","rhsusf_acc_omega9k","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["rhs_uniform_FROG01_wd",[["ACE_EarPlugs",1],["ACE_CableTie",4],[],["ACE_fieldDressing",4],["ACE_elasticBandage",4],["ACE_packingBandage",4],["rhsusf_mag_17Rnd_9x19_FMJ",1,17],["Laserbatteries",1,1]]],["V_TacVest_oli",[["ACE_packingBandage",6],["ACE_fieldDressing",6],["ACE_quikclot",6],["ACE_elasticBandage",6],["ACE_Kestrel4500",1],["ACE_EntrenchingTool",1],["rhsusf_20Rnd_762x51_SR25_m993_Mag",1,20],["SmokeShell",4,1],["rhsusf_mag_17Rnd_9x19_FMJ",1,17]]],["B_Carryall_cbr",[["rhsusf_20Rnd_762x51_SR25_m993_Mag",8,20]]],"H_HelmetSpecB_snakeskin","G_Tactical_Black",["Laserdesignator_03","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","ItemRadioAcreFlagged","ItemCompass","ItemWatch","NVGogglesB_blk_F"]],[]]]
, ...]
```

At face value, obviously, the two shapes do not agree, `[_uniform, ...]` in the BIS example, what looks like `[_primweap, ...]` in the ACE example, to start with.

Best case, I should be able to take the `_inventory` as-is and simply feed it to `setUnitLoadout`, i.e.

```sqf
player setUnitLoadout (_inventory select 1);
```

And an opportunity to follow on with this, assuming this is on track, more/better framework notes around these aspects of things would be a great idea, I think, i.e. what is being persistently saved, in what shape, etc.

**Comment by BrettMayson** [comment]
It is a CBA Extended Loadout.

It is stored as `[<name>, <CBA Extended Loadout>]`
A CBA Extended Loadout is just `[<Vanilla Unit Loadout Array>, <Extra Values>]`

```sqf
[player, _loadout select 1] call CBA_fnc_setLoadout;
```
or this, but it will lose any of the extended information
```sqf
player setUnitLoadout (_loadout select 1 select 0);
```

**Comment by mwpowellhtx** [comment]
Fantastic, that's what I needed.
