### ISSUE TITLE
Atragmx and  numbers paper not appearing in lodout

### ISSUE THREAD

**Issue by Gerry80** [acemod/ACE3#9211]
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]

**Description:**
Atragmx and the number paper (doesnt know the name) doesn't appear in lodout. Other thinks like morphine and earplugs yes it does.
It happens in every character i create

**Expected behavior:**
To see the objetcs i need to play like a sniper.

**Where did the issue occur?**
Editor SIngeplayer

**Screenshots:**
![image](https://github.com/acemod/ACE3/assets/135668717/49502828-48a0-41b6-891d-c846aeb9ef6e)
![image](https://github.com/acemod/ACE3/assets/135668717/59fad172-56cf-46a9-a7c0-3a65bab9764a)

**Comment by BaerMitUmlaut** [comment]
Those items aren't added automatically. You can add them through the arsenal.

**Comment by Gerry80** [comment]
It doesn't appear me in the arsenal.

**Comment by BaerMitUmlaut** [comment]
Please take a screenshot of your arsenal and upload an RPT.
