### ISSUE TITLE
Medical Engine - Look into switching to `HitPart` EH

### ISSUE THREAD

**Issue by LinkIsGrim** [acemod/ACE3#9224]
https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#HitPart has weird locality but might potentially remove need for damage sorting/ACE_HDBracket. Locality could potentially be solved with CBA Events, performance impact needs to be checked.

**Comment by BaerMitUmlaut** [comment]
Sending events for every bullet hit will definitely impact network performance. This would be fine for tanks for example, but not for infantry.

**Comment by veteran29** [comment]
I think Project Injury Reaction is using HitPart but IDK how it behaves in large scale MP.

**Comment by LinkIsGrim** [comment]
Not viable. Network clogging and convoluted remote event structure result in a performance and code quality net loss.
