### ISSUE TITLE
Spanish translation guide / Guía de traducción al español ROUND TWO!

### ISSUE THREAD

**Issue by Legolasindar** [acemod/ACE3#925]
# Spanish translation guide / Guía de traducción al español

**Following [this instructions](https://github.com/acemod/ACE3/issues/917#issuecomment-97462056)**

### Actualiza el mod antes de enviar una traducción

Siempre que vayas a traducir algo, actualiza primero tu copia del mod, así te aseguras de tener la ultima versión. Para saber como hacerlo, sigue la [guiá general de traducción](https://github.com/acemod/ACE3/blob/master/documentation/development/how-to-translate-ace3.md).

### Que lenguaje debes usar

Hay diferentes tipos de español que se hablan en varios países del mundo. Para traducir usa un español neutro, intentando usar términos comunes y evitando regionalismos. Ejemplo:
_En ingles **Cable Tie** se puede traducir como **Precinto** pero no como **Bridas**._
En caso de indecisión, consulta la [RAE](http://www.rae.es).

### Traduce, no interpretes

Es importante que a la hora de traducir, no modifiques el mensaje original. No añadas ni elimines nada, salvo que sea gramaticalmente necesario. Ejemplo:
_En ingles **Give Blood**, se puede traducir como **Administrar sangre** pero no como **Administrar bolsa de sangre**._

### Capitalización

En ingles, las palabras se pueden capitalizan, es decir, pueden poner la primera letra de cada palabra en mayúsculas siguiendo sus normas ortográficas. En español en cambio no se capitaliza. Ejemplo:
_**Give Blood** se puede traducir como  **Administrar sangre** pero no como **Administrar sangre**._
Recuerda que si se pueden utilizar mayúsculas cuando son nombres propios, marcas, modelos, etc...

### Nombres propios

Las marcas, modelos, nombres de personas, etc... son nombres propios, no los traduzcas, dejalos como aparecen. Ejemplo:
_**QuickClot**, es una marca de vendaje coagulante, mantén el nombre comercial y no lo traduzcas._

### Usa traducciones cortas

Como el texto original se basa en el ingles, la interfaz también. La traducción al español suele ser mas larga, por lo que intenta acotarla lo máximo posible sin que el resultado parezca extraño o cueste entenderlo. Así evitaras que descuadre. Ejemplo:
_En inglés **Show vehicle crew info** se puede traducir como **Mostrar tripulantes** mejor que como **Mostrar información de la tripulación del vehículo**._

**Comment by bux578** [comment]
https://gist.github.com/ That's where I meant you should put your file. Not to create a new issue :smile:

**Comment by Legolasindar** [comment]
Ok, i created this file.
https://gist.github.com/bf8a3b09cb835f72501f.git

**Comment by bux578** [comment]
:+1:
