### ISSUE TITLE
tagModel for Sprays isn’t working

### ISSUE THREAD

**Issue by CCSparrow** [acemod/ACE3#9359]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14 RC`
- **CBA:** `3.15`
- **ACE3:** `3.15.2`

**Description:**
I was looking to make a spray can that sprayed down a large landing pad for use in missions. I got the spray can item and the spray texture itself working, but wanted to apply it to a larger surface. I used the tagModel part of the framework to put the class name of the 10m usertexture model. Upon testing the texture didn’t change size. I tried using the p3d path of the model, still didn’t work. After testing I put in a post on the discord and was told there was a problem that has resulted in this ticket being made.

**Steps to reproduce:**
```cpp
class ACE_Tags
{
    class Aux187_Landing_Pad_Spray
    {
        displayName="Landing Pad 10m";
        requiredItem="ACE_SpraypaintBlack";
        materials[]={"@"};
        textures[]=
        {
            "@\a3\UI_F_Orange\Data\CfgMarkers\b_Ordnance_ca.paa"
        };
        tagModel = "UserTexture10m_F";
        icon="";
    };
    class Aux187_Landing_Pad_Spray1: Aux187_Landing_Pad_Spray
    {
        displayName="Landing Pad 1m";
        tagModel = "UserTexture1m_F";
    };
};
```

**Expected behavior:**
10m model should be used.

**Where did the issue occur?**
- Editor (Singleplayer)

**Comment by BaerMitUmlaut** [comment]
https://github.com/acemod/ACE3/blob/master/addons/tagging/functions/fnc_compileTagAction.sqf#L38
