### ISSUE TITLE
Updating base class 3.0.0

### ISSUE THREAD

**Issue by commy2** [acemod/ACE3#938]
- [x] G_40mm_HE->GrenadeBase, by z\addons\ace\frag\config.cpp/CfgAmmo/G_40mm_HEDP/
- [x] Sh_155mm_AMOS->ShellBase, by z\addons\ace\frag\config.cpp/CfgAmmo/Sh_82mm_AMOS/
- [ ] AnimationSources->AnimationSources, by z\addons\ace\aircraft\config.cpp/CfgVehicles/Heli_Attack_01_base_F/AnimationSources/

**Comment by commy2** [comment]
No idea how to fix `Heli_Attack_01_base_F`. That thing is cursed.

**Comment by jokoho48** [comment]
https://github.com/acemod/ACE3/blob/master/addons/aircraft/CfgVehicles.hpp#L47 
Add There 
class AnimationSources;

**Comment by commy2** [comment]
But `Heli_Light_01_base_F` has nothing to do with `Heli_Attack_01_base_F`. That can't be it.
