### ISSUE TITLE
Markers - Marker UI resets active channel back to group

### ISSUE THREAD

**Issue by MildlyInterested** [acemod/ACE3#9382]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14.150962`
- **CBA:** `3.15.8`
- **ACE3:** `3.15.2`

**Description:**

**Steps to reproduce:**

1. Create custom channel 
```sqf
//initServer.sqf
l6AA_AirCommandChannelID = radioChannelCreate [[0.3, 0.3, 0.5, 1], "Air Command", "%UNIT_NAME", [], true];
```
and add players to it
```sqf
//initPlayerLocal.sqf
l6AA_AirCommandChannelID radioChannelAdd [player];
[{setCurrentChannel (l6AA_AirCommandChannelID + 5);},nil,3] call CBA_fnc_waitAndExecute;
```
2. Open map, current active channel is `Air Command`.
3. Double click on map to create marker, channel gets reverted to `Group chat`.

**Expected behavior:**
Use currently active channel, do not modify.

**Where did the issue occur?**
- Editor (Multiplayer)

**Log Files:**
[Arma3_x64_2023-09-09_21-47-58.rpt.txt](https://github.com/acemod/ACE3/files/12566692/Arma3_x64_2023-09-09_21-47-58.rpt.txt)

**Screenshots:**
https://imgur.com/VSZr9Te

**Comment by LinkIsGrim** [comment]
Relevant block: https://github.com/acemod/ACE3/blob/master/addons/markers/functions/fnc_initInsertMarker.sqf#L207

**Comment by LinkIsGrim** [comment]
Can fix it by utilizing https://community.bistudio.com/wiki/radioChannelInfo and https://community.bistudio.com/wiki/channelEnabled in [fnc_getEnabledChannels](https://github.com/acemod/ACE3/blob/master/addons/markers/functions/fnc_getEnabledChannels.sqf)
