### ISSUE TITLE
ACE_Comanche_Test

### ISSUE THREAD

**Issue by rlex** [acemod/ACE3#943]
ACE3 Version: master

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
* ACE_Comanche_Test available in vehicle spawner. Seems like some of your testing stuff?

**Steps to reproduce:**
* Open mission with VVS
* Test heli will be here in list

**Where did the issue occur?**
* SP, MP

**RPT log file:**
* No RPT atm

**Comment by commy2** [comment]
Fixed?

**Comment by rlex** [comment]
Will build and check it now

**Comment by rlex** [comment]
Yep it's gone now. Thanks!

**Comment by commy2** [comment]
k. Leaving this open, beause IDK what the objects is/was used for.

**Comment by jaynus** [comment]
Leftover, my bad.

**Comment by rlex** [comment]
Found it again. Zeus, NATO -> Air
