### ISSUE TITLE
Interact Menu - Self interactions aren't merged into the list or radial menu.

### ISSUE THREAD

**Issue by Mike-MF** [acemod/ACE3#9440]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14`
- **CBA:** `3.16.0-RC1`
- **ACE3:** `3.16.0-RC1`

**Description:**
Creating an ACE self action and adding it to `ace_player` creates the action, but it's not added to the menus. It's just floating off to the side somewhere.

This was tested using `initPlayerLocal` originally with my groups pack, switched to just ACE/CBA and it still occurs.

**Steps to reproduce:**
Video!

https://github.com/acemod/ACE3/assets/29175040/4ca5d755-c70d-4fa3-9d06-a09284bd4e3e

**Expected behavior:**
Should be attached to the radial/list menu with other actions.

**Where did the issue occur?**
- Self-Hosted Multiplayer & Singleplayer & Editor (Singleplayer) & Editor (Multiplayer) & Virtual Arsenal

**Log Files:**
- https://gist.github.com/Mike-MF/1be01b217244253917c58586f2536ab5

**Comment by Mike-MF** [comment]
Closing because I'm big dumb and used `ACE_MainActions` instead of `ACE_SelfActions`

**Comment by BrettMayson** [comment]
`ACE_SelfActions` not `ACE_MainActions`

Seems kinda pointless this was ever possible, couldn't the code just have previously assumed that anything with a root of `ACE_SelfActions` was a self interaction, everything else is a regular action.

Seems like a warning or something could pop up if this is used this way, can't mess with backwards compatibility now.
