### ISSUE TITLE
Create Zeus - BIS_fnc_activateAddons error

### ISSUE THREAD

**Issue by PulsarNeutronStar** [acemod/ACE3#9445]
**Description:**
When using Ace Self Interaction to create Zeus (for example, in editor) you're welcomed with the following prompt 

![107410_20230929141807_1](https://github.com/acemod/ACE3/assets/56258612/1ba1c3f4-5ffa-4ecb-bea6-e69f3e9a8cbe)

Everything *seems* to work without issues and i wasnt able to find a related report in the RPT.

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

Load CBA + ACE, no DLC's.

Make editor mission with one unit, play
(potentially enable the addon option)
Ace Self interact -> create zeus
read message

**Expected behavior:**
The same, but without the mentioned error message

**Where did the issue occur?**
Editor (Singleplayer)

**Log Files:**

client SP editor rpt
([gist](https://gist.github.com/PulsarNeutronStar/03158d40f0dd391c6bc3b05e428ed2ab)

**Additional context:**

**Screenshots:**
![107410_20230929141807_1](https://github.com/acemod/ACE3/assets/56258612/1ba1c3f4-5ffa-4ecb-bea6-e69f3e9a8cbe)

**Comment by Dystopian** [comment]
This error exists since the feature implementation. I tried to find a way to suppress it but failed. Also I didn't meet any issues except it.

**Comment by PulsarNeutronStar** [comment]
ive been using create zeus since a while and only recently started to notice that. maybe i was just blind before but i have the impression it only started recently, hence the issue.

**Comment by PulsarNeutronStar** [comment]
i cant tell if this has sth to do with this issue here in the past
https://github.com/acemod/ACE3/pull/1209
