### ISSUE TITLE
Medical UI - Medical status peek shows selection outline

### ISSUE THREAD

**Issue by veteran29** [acemod/ACE3#9510]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14`
- **CBA:** `3.16.0`
- **ACE3:** `3.16.0`

**Description:**
 Medical status peek shows selection outline while it should not.

**Screenshots:**
![image](https://github.com/acemod/ACE3/assets/4293906/bef6eba2-4161-46b9-9ac1-8fd0eb12eefa)

**Comment by PabstMirror** [comment]
I'm not sure, the peak shows when you start looking at a specific limb,
it's just showing that same limb on the peak

**Comment by veteran29** [comment]
It's the keybind/on hit one. The new thingy (CTRL+H)

**Comment by SGTdanny50567** [comment]
I think this is intentional [Link](https://github.com/acemod/ACE3/pull/9503) and [Link](https://github.com/acemod/ACE3/pull/9471)

**Comment by veteran29** [comment]
You can't have a selection on something that's non-interactive.

**Comment by amsteadrayle** [comment]
In the current implementation, it's not possible to not have a body part selected in that display. The existing self-interact medical category thing defaults to showing the head, so I just went that same default for the peek.

![image](https://github.com/acemod/ACE3/assets/2516219/69201846-2b72-4533-a0c4-91398adcf84d)

**Comment by LinkIsGrim** [comment]
Should refactor the patient display to allow for an overall view.
