### ISSUE TITLE
passThourgh still cannot penetrate the RHS armor

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [acemod/ACE3#9516]
**Mods (complete and add to the following information):**
- **Arma stable
- **CBA: v3.16.0.231017
- **ACE3: Version 3.16.0
- **RHSUSAF
- **RHSAFRF
- **RHSGREF

**Description:**
The new ace version uses passthrough, but during the actual game, players still cannot use RHS weapons and ammunition to penetrate Russian armor

**Steps to reproduce:**
1. Load the above mods,
2. select an M4 or HK standard 556 NATO gun, select any RHS ammunition,
3. Hit the chest of the AI wearing Russian armor,
4. still blue after 100 shots

**Expected behavior:**
normal armor behavior

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by ZHANGTIANYAO1** [comment]
https://youtu.be/H42A3hBQAwU

**Comment by Ivanowicz** [comment]
AFAIK passThrough is about balancing armor so there's nothing with too extreme armor values - not making them possible to be penetrated by any gun. I'd argue that those vests completely stopping all 5.56 bullets does make sense - of course, they probably shouldn't stop an infinite amount of them, but there's no armor degradation system. 7.62 NATO seem to be (barely) able to penetrate those vests, which seems reasonable.

With default Damage Threshold values units in those vests will die after ~10 rounds of 5.56 to the chest - if that's too much, you can lower the Damage Threshold. (That's assuming Sum Of Trauma or Either as Fatal Damage Source)

What I feel is a bit of an issue, is that with default pain threshold (0.5) I was completely unable to knockout anyone with pain from bruises only. I had to lower the threshold to .35 to knockout with Large Bruises and to .30 with Medium Bruises. I think that could be helped by either lowering the default pain threshold or further increasing pain from bruises.

Additional note - I recall reading that testing stuff in Virtual Arsenal is not the best idea, I think it's better to test stuff by putting down a few units in Eden Editor. (Actually, is that still the case?)

**Comment by LinkIsGrim** [comment]
Yes, because Arsenal dummies don't have uniforms, and that influences damage taken.

**Comment by ZHANGTIANYAO1** [comment]
> AFAIK passThrough is about balancing armor so there's nothing with too extreme armor values - not making them possible to be penetrated by any gun. I'd argue that those vests completely stopping all 5.56 bullets does make sense - of course, they probably shouldn't stop an infinite amount of them, but there's no armor degradation system. 7.62 NATO seem to be (barely) able to penetrate those vests, which seems reasonable.
> 
> With default Damage Threshold values units in those vests will die after ~10 rounds of 5.56 to the chest - if that's too much, you can lower the Damage Threshold. (That's assuming Sum Of Trauma or Either as Fatal Damage Source)
> 
> What I feel is a bit of an issue, is that with default pain threshold (0.5) I was completely unable to knockout anyone with pain from bruises only, no matter how many rounds I shot them with. I had to lower the threshold to .35 to knockout with Large Bruises and to .30 with Medium Bruises. I think that could be helped by either lowering the default pain threshold or further increasing pain from bruises.
> 
> Additional note - I recall reading that testing stuff in Virtual Arsenal is not the best idea, I think it's better to test stuff by putting down a few units in Eden Editor. (Actually, is that still the case?)

Yes I also tested in Eden the situation is the same, I agree that hose vests completely stopping all 5.56 bullets does make sense but as you said it can stop the infinite number of bullets doesn't; make sense I would say stop 4-5 bullets before dead is a reasonable value. All test is under default settings

**Comment by LinkIsGrim** [comment]
Default settings means shots will only kill upon penetration. They *will* die to sum of trauma.

**Comment by ZHANGTIANYAO1** [comment]
> Default settings means shots will only kill upon penetration. They _will_ die to sum of trauma, but you need to change that setting.

So the idea plan is to add armor degradation system right? but now only solution is to change setting to sum of trauma but is setting will cause ai die due to non-lethal part damages？

**Comment by LinkIsGrim** [comment]
#9524
