### ISSUE TITLE
Car repair takes too long

### ISSUE THREAD

**Issue by 512mbram** [acemod/ACE3#9521]
- **Arma stable
- **CBA: v3.16.0.231017
- **ACE3: Version 3.16.0

**Description:**
After the last update of ace3 mod the car repair time increased from 15 seconds to 360 seconds which is too much

**Steps to reproduce:**

1. Take a tool kit
2. Repair a car

**Expected behavior:**
Adjustable repair time

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by LinkIsGrim** [comment]
Check your settings.

![107410_20231018125951_1](https://github.com/acemod/ACE3/assets/69561145/d03bb99e-6ede-47a1-bf57-d17942b3b0fd)
