### ISSUE TITLE
Patient status dropdown not aligned

### ISSUE THREAD

**Issue by Grezvany13** [acemod/ACE3#9526]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14` (latest stable from Steam)
- **CBA:** `3.16.0` (latest stable from Steam WS)
- **ACE3:** `3.16.0`  (latest stable from Steam WS)

**Description:**
The patient status dropdown in the medical menu is slightly off (see attached screenshot).

**Steps to reproduce:**
1. Click [H] to open medical menu on self
2. Check the medical status ('NONE' by default)
3. See that the options below it are not aligned with the current status

**Expected behavior:**
It's expected that the statuses are aligned correctly under the current medical status

**Where did the issue occur?**
- Tested in 3den, Singleplayer

**Log Files:**
*No issues logged in .rpt* 
https://textdoc.co/l5yE0RFjNehzMnJG

**Additional context:**
(possible related) video settings are:
- Display Mode: Fullscreen Window
- Resolution: 2560x1440 (16:9)
- Aspect Ratio: Auto (Stretch) (16:9)
- Interface size: Very small

**Screenshots:**
![acemed](https://github.com/acemod/ACE3/assets/1245173/615cf68a-068c-4dc4-9d73-5479c21f625f)

**Comment by LinkIsGrim** [comment]
Fixed in #9515
