### ISSUE TITLE
Spearhead grenades do not activate properly when thrown with precision throw.

### ISSUE THREAD

**Issue by Cryptozooform** [acemod/ACE3#9532]
Mods used
ACE3
Spearhead CDLC

**Description:**
When thrown with precision throw, spearhead grenades do not activate the incredibly convenient feature of a small smoke and spark trail, alongside a mild hissing sound in some grenades. When you simply press "G" they do so.

**Steps to reproduce:**
1. Use any role, of any side.
2. Press G
3. Note the smoke trail and sparks.
4. Press SHIFT + G 
5. Note the lack of above smoke trail and sparks.

**Expected behavior:**
All grenade throwing methods create the smoke trail and sparks.

**Where did the issue occur?**
Editor, Multiplayer (dedicated), Singleplayer Campaign

**Comment by jonpas** [comment]
I assume you mean Advanced Throwing when you say precision throw.
