### ISSUE TITLE
Ace Arsenal Lockpick and Key issue

### ISSUE THREAD

**Issue by fav-MBMC** [acemod/ACE3#9540]
**Mods:**
- **Arma 3:** 2.14.151082 stable || 2.14.151082 performance branch v6
- **CBA:** 3.16.0
- **ACE3:** 3.16.0.231017

**Description:**
After the last update for the ACE Arsenal, these items ("ACE_key_lockpick","ACE_key_master","ACE_key_west","ACE_key_east","ACE_key_indp","ACE_key_civ") can no longer be found in the ACE Arsenal (editor, main menu ACE Arsenal or in own mission). 
Despite adding the items with the command [_player,_items] call ace_arsenal_fnc_addVirtualItems in own scripts, the items are not found.
Before the update it worked fine.

**Steps to reproduce:**
1. Go to Tutorials
2.  then Ace-Arsenal
3. search for the items in the different categories

**Expected behavior:**
That these items "ACE_key_lockpick","ACE_key_master","ACE_key_west","ACE_key_east","ACE_key_indp","ACE_key_civ" are available in the arsenal and mayby in the categorie Tools (ACE_isTool = 1)

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional context:**
- Probably it has something to do with the categories update. Arsenal - Categories for Tools ( #9247) 
- Or with the recognition and classification of the items

**Comment by LinkIsGrim** [comment]
Since #9040 items with scopeArsenal = 0 cannot be added to the Arsenal. This is a design decision.

**Comment by fav-MBMC** [comment]
Okay, thx for the Info. 
Do you have plans to change the config for this itmes or not?

**Comment by LinkIsGrim** [comment]
No.
