### ISSUE TITLE
All arsenal loadouts have vanished and new loadouts will not save.

### ISSUE THREAD

**Issue by tastychunks** [acemod/ACE3#9548]
- **Arma 3:** 2.14.150957
- **CBA:** `[v3.16.0.231017]
- **ACE3:** [3.16.0]

**Description:**
All of my arsenal loadouts are not appearing in the load list and when attempting to save new loadouts they do not re-appear in the load menu after being saved. None of the files or folders in my A3 profile folder in My Documents is read only.

Enter any ACE Arsenal
Save a loadout
When clicking load nothing will appear in the list as if nothing were saved earlier.

I expected to be able to have my previous loadouts and failing that; I expect to be able to save new loadouts to replace the missing ones.

Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by jonpas** [comment]
Fixed by #9562.
