### ISSUE TITLE
Server/Client Mismatch extra Addons?

### ISSUE THREAD

**Issue by CommyDuck** [acemod/ACE3#9550]
**MODS:**
* Arma3 [up tp date]
* CBA [A3 up to date]
* ACE3 [up to date]

**Description**
After the latest ACE update, I've run into the issue of being kicked out of mission when loading in due to a Server/Client Addon mismatch. It says I have extra Addons when I've only gone in with our servers dependencies. "ace_fieldmanual" "ace_irlight" and "ace_zeus_trenches" are the classnames I get.

**Steps to Reproduce**
* Attempt to load into mission with ACE loaded in your modlist...
* Cry

**Expected Behavior**
A work around that can fix this if it's on my end. A solution from the mod if it's on yours.

**Where did this issue occur**
Dedicated unit server

**Log Files**
We don't keep those

**Screenshot**
[I already tried by removing the SOG DLC, still can't load]
![image](https://github.com/acemod/ACE3/assets/88029769/7f9b35cc-e238-42e0-8fc2-b632f8d72d3e)

**Comment by LinkIsGrim** [comment]
Update your server properly. Upload server RPT.

**Comment by jonpas** [comment]
Issues without log files?
> We don't keep those
