### ISSUE TITLE
ACE 3.16.0 - Client Side Mismatched Varients Issue

### ISSUE THREAD

**Issue by releasethekraken12** [acemod/ACE3#9551]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `v3.16.0.231017` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.16.0` [eg. 3.0.0 stable, commit hash]

**Description:**
I have found an issue with the latest ACE version where if someone downloads it fresh, it takes multiple hours for Arma itself to register that ACE is running  the current version. I have had three other friends reproduce the same issue. They will install ACE and CBA fresh (all three have never installed ACE before) and when loading into a server it will come up with an error saying that that person is running ACE Version "3.15.2.69" however I have verified that they are running 3.16 of both CBA and ACE. The only fix I have had is for when they shut down their PC's for the night, the following day the game registers the correct version. Of a total of 6 Members (Including myself) three of us have found that to be the only fix. My other three friends have not had a change in status yet. One is a brand new install as of 10/20/23 @4:00PM PST and two were last night 10/19/23 @9:00PM PST

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. Run a Fresh Install of ACE/CBA
2. Join a Server with the same versions of ACE/CBA
3. Upon Loading in, see if the server will kick you for mismatched ACE Versions.
    -You may be able to see the orange outline of the Main Menu Error showing the outdated ACE Version.

**Expected behavior:**
I expect that the server will kick you saying 

**Where did the issue occur?**
- Private Dedicated Server hosted through BisectHosting. Verified updated version is current.

**Log Files:**
- Mine is working now, however if required I can try to get a friends logfile

**Additional context:**
No other context

**Screenshots:**
Main Menu:
![Screenshot_13](https://github.com/acemod/ACE3/assets/148594315/92cc4279-c132-4203-b218-25fee0dd344a)

Error Report from game:
![Screenshot_14](https://github.com/acemod/ACE3/assets/148594315/9c49a626-e0a3-46f6-868f-528da36d7cd2)

**Comment by rautamiekka** [comment]
Did you read the release notes ?

**Comment by releasethekraken12** [comment]
> Did you read the release notes honestly no. Never in the many years have I thought that the release notes would have information on a bug or issue. I'd always think that would be it's own announcement. I will check it though

**Comment by releasethekraken12** [comment]
> Did you read the release notes ?

I just read through the whole thing. Unless I'm blind I didn't see anything about the issues I'm going through. Can you tell me what in the release notes tells me about the issue I am having please?

**Comment by Cardboardboxx** [comment]
I've been having the same issue only using ace and cba and it's client side and sever side both pop up with a error message then kicks

**Comment by LinkIsGrim** [comment]
Upload RPTs.

**Comment by releasethekraken12** [comment]
> Upload RPTs.

RPT's?

**Comment by jonpas** [comment]
You deleted the instructions from the issue template...
> **Log Files:**
> - Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by Cardboardboxx** [comment]
[RTP.pdf](https://github.com/acemod/ACE3/files/13078614/RTP.pdf)

**Comment by LinkIsGrim** [comment]
Gotta admit, rpt in a pdf is a new one.

**Comment by LinkIsGrim** [comment]
> [RTP.pdf](https://github.com/acemod/ACE3/files/13078614/RTP.pdf)

ACE isn't even loaded in that log.

**Comment by releasethekraken12** [comment]
> You deleted the instructions from the issue template...
> 
> > **Log Files:**
> > 
> > * Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

Ohhh thought it was suppose to be deleted honestly. I saw others doing the same thing. Thank you haha.
Give me a moment I'm working on it now

**Comment by releasethekraken12** [comment]
> Upload RPTs.

Hope I did it right

https://gist.github.com/releasethekraken12/0af3376b430cbbbcce9e1558819c844d

**Comment by releasethekraken12** [comment]
If I did it right let me know. I will have one of my friends do the same process who is having the issues connecting to the server.

**Comment by releasethekraken12** [comment]
> Remove @ace no stamina

Ok I'll have one of my guys try it. Do I need to remove it from the server itself as well?

**Comment by LinkIsGrim** [comment]
You shouldn't have two versions of ACE loaded at the same time. You can just disable Advanced Fatigue in settings and vanilla stamina through the difficulty options.

**Comment by releasethekraken12** [comment]
> You shouldn't have two versions of ACE loaded at the same time. You can just disable Advanced Fatigue in settings and vanilla stamina through the difficulty options.

Ohhhh ok! I will test it out then! Thank you I had no idea!

**Comment by releasethekraken12** [comment]
Sorry for the delay. Was sick. But it was fixed! Thank you guys very much for the help
