### ISSUE TITLE
The game closes when I restart the current game

### ISSUE THREAD

**Issue by Bibi1506** [acemod/ACE3#9559]
**Mods :**
- **Arma 3:** `2.06`
- **CBA:** `3.15.7` 
- **ACE3:** `3.15.0` 

**Description:**
I create a mission in the 3D editor by placing military units on the Stratis map, and the mission works correctly.
However, when I restart the mission I've just created, the game displays the mission loading screen for a few seconds, then closes, taking me back to the desktop without an error message. The same thing happens when I'm in the Virtual Arsenal.
The problem sometimes occurs when I click on "Play scenario" in the 3D editor.
This doesn't happen when I only place civilians.
The problem disappears when I play without the ACE mod.

**Steps to reproduce:**
1. _Create a new mission in the 3D editor_
2. _Placing military units_
3. _Start the game_
4. _Press the escape key_
5. _Click on restart_
6. _Click on yes_

**Expected behavior:**
The mission should restart normally without the game closing.

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Virtual Arsenal

**Log Files:**
https://pastebin.com/CA4cDg43

**Additional context:**
I played Arma 3 on this same computer last year with the same mods and never had this problem until I reinstalled it a few days ago.

**Comment by PabstMirror** [comment]
> Version: 2.06.148470

Make sure you game is updated on steam 🤔

**Comment by BaerMitUmlaut** [comment]
Don't use cracked Arma.
