### ISSUE TITLE
Ace Medical issue with CUP AI 

### ISSUE THREAD

**Issue by aproyaloak** [acemod/ACE3#9578]
Mods 
- Arma 3: `2.14.150957` 
- CBA:`3.16.0.231017` 
- ACE3: `3.16.0`
- CUP Weapons " 1.17.1"
- CUP Units "1.17.1"
- CUP Vehicles "1.17.1"
- CUP ACE3 Compatability Addon "1.17.0" 

Contrary to the Vanilla AI, when you shoot CUP AI in the Head (Even direct hits without any armor) they dont die, but go unconcious, and if you shoot them in the leg when they go unconcious, they suddenly wake up and start shooting at you. 

Steps to reproduce: 

Play a Editor Mission with the Mods loaded and shoot the CUP AI in the head 

Expected behavior:
the AI should drop dead from headshots like any other AI does. Also shooting the unconcious AI in the legs shouldnt wake them up again.

Where did the issue occur?
Editor (Singleplayer)

**Comment by LinkIsGrim** [comment]
Don't delete the issue template. Upload your RPT.

**Comment by aproyaloak** [comment]
> Don't delete the issue template. Upload your RPT.
> 
> (Though this should get fixed by #9524 if it's a real issue)

https://pastebin.com/KeJNrb8c this is the RPT file and i also uploaded a vid to show the problem better https://www.youtube.com/watch?v=jrDWRA9zjzw&ab_channel=wasser

**Comment by Daburnell112** [comment]
Potentially this is broken with players too. We have "explosion" and "punch" damage impacting players on some custom coded NPC's, or from shooting a grenade launcher - with them immediately healing upon getting hit with a grenade, with a bunch of errors being thrown.

**Comment by Daburnell112** [comment]
Confirmed that this happens with nades as well, if you grenade yourself you'll be healed instantly.

**Comment by aproyaloak** [comment]
i think the CUP weapons are broken in general, since they also overheat way faster than the Vanilla or even RHS weapons. the Compatability mod probably needs to be fixed

**Comment by LinkIsGrim** [comment]
@aproyaloak is this still happening after the update?

**Comment by aproyaloak** [comment]
yes just tested it right now still the same unfortunately, the game doesnt differentiate between the Armor and the body, (shot to the face has the same effect as shot on the helmet and in general the CUP ai armor seems to be a little bit too strong) this is kinda funny because online i read CUP uses vanilla Armor but somehow this doesnt happen to vanilla Ai only CUP AI

**Comment by LinkIsGrim** [comment]
I can't reproduce this. Can you upload your debug info as well? Press ESC ingame, Options -> ACE Debug to Clipboard. Uploading RPT or clipboard output directly is fine.

**Comment by aproyaloak** [comment]
Arma 3 upadted and now it seems to be mostly fixed, except for the Armed Forces of the Russian Federation Men( Modern MSV - Beige Digital) it does happen every now and then with the other factions, but they dont stand up anymore, they just bleed out.

**Comment by LinkIsGrim** [comment]
https://github.com/acemod/ACE3/pull/9524
