### ISSUE TITLE
Issues with fatal injury death chance / damage with sum of trauma 

### ISSUE THREAD

**Issue by alanriddell** [acemod/ACE3#9595]
**Mods (complete and add to the following information):**
- **Arma 3:** 2.14.150957 stable
- **CBA:**  3.16.1.231025
- **ACE3:** 3.16.1.74

**Description:**
People die to low levels of light injury to head or torso. ACE medical settings appear to have no effect. Death is instant (not unconscious first). 

It also feels weird that there is a straight jump from bruised and in pain to instant death rather than being unconscious at any point.

**Steps to reproduce:**
- Create new mission in editor add two people one with a pistol the other with body armour.
- Play as the pistol character and shoot the AI in the chest armor until they are dead.
- ACE medical settings to be Fatal Damage source as "Either" or "Sum of Trauma"
- Count number of shots.
- Restart change the ace medical settings to lower chance of fatal injury and repeat.
- Alternative : Use other low damage weapons that should wound and not instantly kill seem to have a high chance of instant death on chest / torso. 

**Expected behavior:**
I would expect it to take a LOT of pistol rounds to the chest good body armor to instantly kill them. Certainly changing medical settings should be able to lower this chance. People with high injuries should at least have a chance to be knocked unconscious before death.

12 shots with pistol killed :
![image](https://github.com/acemod/ACE3/assets/16252482/e30f0048-98fd-46c9-83d9-034305af8372)

Medical settings for the above kill :
![image](https://github.com/acemod/ACE3/assets/16252482/8a1e523a-21d9-4976-85d3-68ca54e2b39e)

Change medical settings to make death less likely :

![image](https://github.com/acemod/ACE3/assets/16252482/bae6b70f-5280-48a6-89bf-3fdecfb02f7d)

shot until death is the same.

**Where did the issue occur?**
Editor (Singleplayer)

**Log Files:**
https://pastebin.com/tLtP7csz

**Additional context:**
Issue started from playing with RHS mods and noticing a lot more instant deaths from weapons that should just be causing KOs. But appears to be there with just ACE

**Comment by alanriddell** [comment]
ah maybe I mis-undestood settings

"fatal injury death chance" does not apply to "sum of trauma".

only 

"critical damage threshold"

Maybe just a tool tip update then?

I'll have to double check if turning "sum of trauma" off fixes everything

**Comment by alanriddell** [comment]
it still feels like after the recent update the chance of death from trauma (and maybe critical injury) is higher but don't have concrete data to back that up.

**Comment by LinkIsGrim** [comment]
Fatal Injury death chance does not apply to deaths by sum of trauma. Increase critical damage threshold if you'd like units to be harder to kill via that method.

Vests have received a slight nerf due to the new damage handling. You can use the "Armor Passthrough Effect" slider to tweak that in relation to 3.16.0 damage. 0% is exactly the same as pre-update behavior.
