### ISSUE TITLE
show should I solvet his problem?

### ISSUE THREAD

**Issue by dk724truel** [acemod/ACE3#9600]
![bug](https://github.com/acemod/ACE3/assets/149216330/a6ecd8ea-4c8a-46ed-ba92-810d174589cc)

**Comment by PabstMirror** [comment]
unsubscribe from https://steamcommunity.com/sharedfiles/filedetails/?id=1956960252

**Comment by dk724truel** [comment]
![20231028_114558](https://github.com/acemod/ACE3/assets/149216330/81aad251-e158-4dfd-a2da-5b53e4a845e6)
keeps happening

**Comment by dk724truel** [comment]
![20231028_114558](https://github.com/acemod/ACE3/assets/149216330/7c773e61-47ba-4f69-8f68-5a8a223a3dc4)
keeps happening
