### ISSUE TITLE
Can't unload large objects from the Cargo space

### ISSUE THREAD

**Issue by ilias-7565** [acemod/ACE3#9607]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.16.1` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.16.1` [eg. 3.0.0 stable, commit hash]

**Description:**
When trying to unload different objects, a `<<name>> could not be unloaded` message is shown. Even if the loaded object can be Carried.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Comment by Dystopian** [comment]
Can happen on steep slopes, bridges.

**Comment by ilias-7565** [comment]
It can happen due to limitation on range from container. Also on short look, [this](https://github.com/acemod/ACE3/blob/5ae5e514b12ab0c51598ba662167675ed0a5aaac/addons/common/functions/fnc_findUnloadPosition.sqf) seemed to use the Cargo size instead of bounding box. And regardless, the object needs to be unloaded by attaching to the player each time if it can be Carried or Dragged.

**Comment by LinkIsGrim** [comment]
Need consistent repro: vehicle and loaded object combination where this happens.

**Comment by ilias-7565** [comment]
@LinkIsGrim No its not needed. If Cargo size affects ability to unload -- that can cause a bug and needs to be removed. If the placement script can't provide position in each case when there is enough free space on the map, then unloading by attaching to the player needs to be added.

If you want, you can repro it with loading any object of Huron Container or larger size. If that doesn't happen then increase the size and space values.

**Comment by LinkIsGrim** [comment]
Easier for you to just say what you did to make this happen so we can spend less time looking for it and more time fixing it. Or just make the PR yourself if you have a solution.

**Comment by ilias-7565** [comment]
@LinkIsGrim
> If you want, you can repro it with loading any object of Huron Container or larger size. If that doesn't happen, set the size and space values to int32.MaxValue.

And i said exactly what needs fixing.

**Comment by BaerMitUmlaut** [comment]
Cargo affecting the size to unload is an intentional feature. Attaching things to the player is neither feasible (object collision) nor realistic (remember, this is a realism mod). Since apparently you know exactly what needs to be done, feel free to fork ACE and do it yourself.
