### ISSUE TITLE
ACE key-binds still active on player when using remoteControl command.

### ISSUE THREAD

**Issue by Fearmonger** [acemod/ACE3#9629]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14.150957` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.16.1` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.16.1` [eg. 3.0.0 stable, commit hash]

**Description:**
When player uses remoteControl command to take control of an AI unit ACE key binds used during that remote control session are still run on the players original body.
**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. In editor place a player and then place any friendly AI a few feet across from the player, facing each other.
2. Set the Variable Name for the AI to test.
3. Start Scenario.
4. Press ESC
5. In the debug console run the following
test switchCamera "INTERNAL";
player remoteControl test;
6. You will now be in control of the friendly AI.
7. Press "CTRL+5[NUM]" (Default setting for Rally up action).
8. Gesture will be done by body that started as player.

**Expected behavior:**
I would expect the body being controlled to make the gesture.
**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
Singleplayer Editor
**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**
![image](https://github.com/acemod/ACE3/assets/47377659/a67ee5f7-03fb-4822-924b-05324e5b3236)

**Comment by PabstMirror** [comment]
I guess this is a CBA issue because "unit" player event isn't firing
there is a brand new command we could be using in 2.14 - https://community.bistudio.com/wiki/remoteControlled

but what I would recommend for you for now is to just set
```
missionNamespace setVariable ["bis_fnc_moduleRemoteControl_unit", test];
```
that is what the zeus-rc module is doing and is what cba and ace are expecting

**Comment by Fearmonger** [comment]
Thank you very much, that fixed it!!
