### ISSUE TITLE
Function "ace_medical_fnc_serializeState" ERROR. Cannot extract variable "ace_medical_openwounds".  typeName seems wrong. Worked previously.

### ISSUE THREAD

**Issue by bendy101** [acemod/ACE3#9631]
**Description:**
When using the "ace_medical_fnc_serializeState" function, the variable returned for "ace_medical_openwounds" cannot be extracted like previous versions of ACE. The typeName comes up as a "LOCATION" type variable instead of an "ARRAY".

**Mods :**
- **Arma 3** `2.14.150957` [stable]  (latest)
- **CBA:** `3.16.1` [stable] (latest)
- **ACE3:** `3.16.1` [stable] (latest)

**Steps to reproduce:**
1. test with this code on a unit:
```
					private _jsonStr = _unit call ace_medical_fnc_serializeState;
					private _json = [_jsonStr] call CBA_fnc_parseJSON;
					private _wounds = _json getVariable "ace_medical_openwounds";
```
2. cannot extract data from "ace_medical_openwounds". 
The var "_wounds" coming up error: "Location CBA_NamespaceDummy at -1000, -1000"
the "_wounds" var has typeName as a "LOCATION" type instead of an "ARRAY".

**Where did the issue occur?**
- Editor (Multiplayer)

**Comment by PabstMirror** [comment]
this should make parseJSON return native hashes
```
private _jsonStr = player call ace_medical_fnc_serializeState; 
private _json = [_jsonStr, 2] call CBA_fnc_parseJSON;  // 2nd arg will get native hashMaps
_json get "ace_medical_openwounds"; // get instead of getVariable 
```

alternatively you can convert what it returns
```
private _jsonStr = player call ace_medical_fnc_serializeState; 
private _json = [_jsonStr] call CBA_fnc_parseJSON;
private _wounds = _json getVariable "ace_medical_openwounds";

private _keys = allVariables _wounds;
private _values = _keys apply {_wounds getVariable _x};
private _woundsHash = _keys createHashMapFromArray _values;
```

**Comment by bendy101** [comment]
> this should make parseJSON return native hashes
> 
> ```
> private _jsonStr = player call ace_medical_fnc_serializeState; 
> private _json = [_jsonStr, 2] call CBA_fnc_parseJSON;  // 2nd arg will get native hashMaps
> _json get "ace_medical_openwounds"; // get instead of getVariable 
> ```
> 
> alternatively you can convert locations into hashes ref https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_deserializeState.sqf#L61-L63
> 
> ```
> private _jsonStr = player call ace_medical_fnc_serializeState; 
> private _json = [_jsonStr] call CBA_fnc_parseJSON;
> private _wounds = _json getVariable "ace_medical_openwounds";
> 
> private _keys = allVariables _wounds;
> private _values = _keys apply {_wounds getVariable _x};
> private _woundsHash = _keys createHashMapFromArray _values;
> ```

great, that seems to work now, however I am failing to send data back to ace_medical_fnc_deserializeState, here:

`		_json setVariable ["ace_medical_openwounds", _wounds apply {
			_x params ["_class", "_bodyPartIndex", "_amountOf", "_bleeding", "_damage"];
			[_class, _bodyPartIndex, _amountOf, 0, _damage];
		}];
		_json setVariable ["ace_medical_bloodvolume", [
			4 max (_json getVariable "ace_medical_bloodvolume"),
			6
		] call BIS_fnc_randomNum];
		_json setVariable ["ace_medical_bloodpressure", [
			[70, 80] call BIS_fnc_randomInt,
			[110, 120] call BIS_fnc_randomInt
		]];
		_json setVariable ["ace_medical_heartrate", [70, 120] call BIS_fnc_randomInt];
		_json setVariable ["ace_medical_statemachinestate", "Injured"];

		private _newJsonStr = [_json] call CBA_fnc_encodeJSON;
		_json call CBA_fnc_deleteNamespace;
		[_incap, _newJsonStr] call ace_medical_fnc_deserializeState;`
		
	This worked for previous ACE

**Comment by PabstMirror** [comment]
```
{ 
    private _woundsOnLimb = _y; 
    { 
        // new format: [_class, _amountOf, _bleeding, _damage]; 
        _x set [2, 0]; 
    } forEach _woundsOnLimb; 
} forEach _woundsHash;
```
use this to zero out the bleeding on all wounds in the woundhash

**Comment by bendy101** [comment]
cheers, so have to use hashmaps.
