### ISSUE TITLE
Error Zero divisor when unit shot

### ISSUE THREAD

**Issue by szpolny** [acemod/ACE3#9632]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14.150957` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.16.1` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.16.1` [eg. 3.0.0 stable, commit hash]

**Description:**
I have custom unit with custom model from this mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2781344095. When i shoot this model it gives me this error. 
![obraz](https://github.com/acemod/ACE3/assets/43553431/7c29c657-f283-497b-b616-112f31c70a39)

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. _Go to editor place playable unit and "mutant" model from mentioned above mod.
2. _Shoot to mutant
3. _This error occurres

**Expected behavior:**
Ace medical handle unit 

**Where did the issue occur?**
- Editor (Singleplayer) 

**Log Files:**
```
12:08:48 Error in expression <) then {
    private _armorCoef = _armor/_armorScaled;
    private _damageCoef =>
12:08:48   Error position: </_armorScaled;
    private _damageCoef =>
12:08:48   Error Zero divisor
12:08:48 File /z/ace/addons/medical_engine/functions/fnc_handleDamage.sqf..., line 430
```

**Additional context:**
Is there a way to fix it? I know that this is no ace problem, but problem specific to the mutant's mod. Maybe override these values, by editing these problematic values

**Comment by johnb432** [comment]
> Is there a way to fix it? I know that this is no ace problem, but problem specific to the mutant's mod. Maybe override these values, by editing these problematic values

No, it's at least partially ACE problem.

@LinkIsGrim 

https://github.com/acemod/ACE3/blob/4fb9da7b084f5db4724685561178b0f67f96b2ad/addons/medical_engine/functions/fnc_getHitpointArmor.sqf#L47
We should be checking if `_armor` is 0.

Might be even safer fixing this instead:

https://github.com/acemod/ACE3/blob/4fb9da7b084f5db4724685561178b0f67f96b2ad/addons/medical_engine/functions/fnc_getItemArmor.sqf#L66

We should make sure that is can't return 0. Minimum armor is 1.

**Comment by LinkIsGrim** [comment]
Hitpoint armor should be armor max 1, item armor should be armor max 0 because an item can not cover a hitpoint
