### ISSUE TITLE
Enable Barrel Length Simulation have no effect on muzzle velocity

### ISSUE THREAD

**Issue by PlayerBotPro** [acemod/ACE3#9669]
**Mods:**
- **Arma 3:** `2.14.150957 Steam`
- **CBA:** `3.16.1, Steam Workshop`
- **ACE3:** `3.16.1, Steam Workshop`

**Description:**
Turn Enable Barrel Length Simulation on or off doesn't change muzzle velocity.

**Steps to reproduce:**

1. _Open ACE ARSENAL, pick a MX rifle and a range card_
2. _Click TRY_
3. _Turn on Addon Options->ACE Advanced Ballistics->Advanced Ballistics_
4. _Check range card after switching on and off Addon Options->ACE Advanced Ballistics->Enable Barrel Length Simulation_
5. _Range card shows that Muzzle velocity in 25°C is 758 no matter Enable Barrel Length Simulation is on or off_
6. _When using addEventHandler to read muzzle velocity, the number is 752.5 no matter Enable Barrel Length Simulation is on or off_

**Expected behavior:**
When Enable Barrel Length Simulation is off, the muzzle velocity of MX rifle should be 800:

in vanilla game, when MX(arifle_MX_F) shooting a 30rnd_65x39_caseless, muzzle velocity is 800.

use
https://github.com/acemod/ACE3/blob/acca95d204fc9af5dae3f5db569739116aabd282/addons/advanced_ballistics/functions/fnc_handleFired.sqf#L82

and parameters
https://github.com/acemod/ACE3/blob/acca95d204fc9af5dae3f5db569739116aabd282/addons/ballistics/CfgWeapons.hpp#L186-L187
https://github.com/acemod/ACE3/blob/acca95d204fc9af5dae3f5db569739116aabd282/addons/ballistics/CfgAmmo.hpp#L235-L236

to calculateBarrelLengthVelocityShift:
```
[368.3, [730, 760, 788, 800, 810, 830], [254.0, 406.4, 508.0, 609.6, 660.4, 762.0], 800] call ace_advanced_ballistics_fnc_calculateBarrelLengthVelocityShift
```

it returns -47.5, 800-47.5=752.5.

So muzzle velocity is nothing wrong when Enable Barrel Length Simulation is on, but it should be 800 when its off.

**Where did the issue occur?**
- Editor (Singleplayer)
- Editor (Multiplayer)
- Virtual Arsenal

**Log Files:**
Log after `[] call ace_advanced_ballistics_fnc_diagnoseWeapons` executed:
https://gist.github.com/PlayerBotPro/5075f354dcadfd5e09f3c0afa070fa32

**Additional context:**
Code of addEventHandler to read muzzle velocity:
```
player addEventHandler[ 
 Fired', { 
  _projectile=_this select 6; 
  _bulletVelocity=velocity _projectile; 
  _muzzleVelocity=vectorMagnitude _bulletVelocity; 
  systemChat str(_muzzleVelocity); 
 } 
]
```

**Screenshots:**
No

**Comment by LinkIsGrim** [comment]
Because of changes made in `smallarms`/`ballistics` components, muzzle velocity on the MX being the same regardless of the setting is actually expected behavior (even if obtuse, IMO). I did find some places where the overall AB toggle and barrel length settings weren't taken into account while looking into this, though, but it's mostly display issues.
