### ISSUE TITLE
More realistic laser codes

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#967]
ACE3 Version: 3.0.0.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *None*

**Description:**
*I think in reality there is a range of allowable laser codes that can be set inside SOFLAM and GBU-12 or other laser guided bombs. This is how it works in DCS: A-10C:*
* *Codes from 1111 to 1688 are valid. The first digit must be 1, the second 1-6, and the third and forth 1-8. - DCS: A-10C Manual*
* *Reading the manual with some rigor it says that the L and LSS codes for the TGP have to be of the form ABCC (A=1, B=1-7, C=1-8). That's not to say that the GBU-10/12 valid codes have to be of this same set as the TGP is capable. Valid LGB codes seem to be of the form ABBB (A=1, B=1-7). It does appear that the code 1688 is invalid according to what's possible to set in the INV page. If JTAC is lasing 1688 then one cannot drop an LGB directly and would have to LSS for it and then self-designate. Perhaps this is intentional procedure to use an "unbombable" code? - Post on DCS forum*

*Maybe it is worth to pre-enter all valid combinations and just make player switch between them using Laser Code Up/Down?*
*Right now it will feel pretty basic way its implemented.*

**Steps to reproduce:**
* *Grab SOFLAM, you can set any laser code*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*Not needed*

**Comment by Ocelottr** [comment]
Relevant information from the US Army 2005 AH-64D Operators' manual.

CODE RANGE. 

The CODE RANGE indicates
the laser code ranges which are supported by the laser
keywords resident on the DTC. 

The helicopter is capable
of supporting the Tri -Service pulse repetition frequency
(PRF) laser codes and USAF, Hellfire and Copperhead
pulse interval modulation (PIM) laser codes. 

In order for
the LRFD, [ MT LST] and Hellfire subsystem to use a
PIM laser code the appropriate keyword, for the specific
code range, is required:

1111 - 1788 Tri -Service . . . . . . PRF
2111 - 2888 USAF . . . . . . . . . . . PIM
4111 - 4288 Hellfire-A . . . . . . . PIM
4311 - 4488 Hellfire-B . . . . . . . . PIM
4511 - 4688 Hellfire-C . . . . . . . PIM
4711 - 4888 Hellfire-D . . . . . . . PIM
5111 - 5288 Copperhead-A . . . PIM
5311 - 5488 Copperhead-B . . . PIM
5511 - 5688 Copperhead-C . . . PIM
5711 - 5888 Copperhead-D . . . PIM
