### ISSUE TITLE
ACE Medical FFV Damage Hang

### ISSUE THREAD

**Issue by lambdatiger** [acemod/ACE3#9674]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14 Stable`
- **CBA:** `3.16.1 Stable`
- **ACE3:** `3.16.1 Stable`

**Description:**
When hitting units in FFV with large/overkill amounts of damage (i.e., main tank gun), Arma will hang for a few seconds.

**Steps to reproduce:**

1. Launch attached demo mission. 
1a. Alternatively, in the editor place a units in FFV seats that are easily hit and a vehicle with a large caliber controllable gun.
2. Shoot through FFV units with large caliber round (i.e., AP tank rounds)
3. Experience a few seconds of hang

**Expected behavior:**
Normally I'd expect minimal overhead from ACE medical

**Where did the issue occur?**
- Dedicated MP & Editor (Singleplayer)

**Log Files:**
https://pastebin.com/xMspFEVE
Also in attached zip.

**Additional context:**
[Demo mission and rpt zip](https://github.com/acemod/ACE3/files/13623134/Demo.mission.and.rpt.zip)

This does not occur with infantry not in a vehicle, but will for those in an FFV seat. I did not check normal passenger seats. Appears to be related to `ace_medical_damage_fnc_woundsHandleBase` or the medical state machine, see screenshot below using current steam versions of intercept and ASP to take a look.

**Screenshots:**
![image-1](https://github.com/acemod/ACE3/assets/11843718/d09bc2d7-ac70-47e3-94dc-945e0268dee4)

https://github.com/acemod/ACE3/assets/11843718/b810936e-33a1-4198-a434-6335d30a42aa

**Comment by LinkIsGrim** [comment]
Issue lies in https://github.com/acemod/ACE3/blob/d70fbd576527da300b26a82d51573f7950b163ab/addons/medical_engine/functions/fnc_handleDamage.sqf#L82-L90

We need to filter out direct hits to units in vehicles.
