### ISSUE TITLE
ace_optionsmenu not listed as dependency of ace_cargo and ace_refuel, silently break the interactions when not loaded

### ISSUE THREAD

**Issue by bangbambang** [acemod/ACE3#9676]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14.150957`
- **CBA:** `3.16.1.231025`
- **ACE3:** `3.16.1`

**Description:**

The documentation [mentioned](https://ace3.acemod.org/wiki/feature/optionsmenu) that `ace_optionsmenu` was deprecated, and neither `ace_cargo` or `ace_refuel` list `ace_optionsmenu` as dependency. However, some settings still refer to optionsmenu's strings (e.g in [common/initSettings.inc.sqf](https://github.com/acemod/ACE3/blob/fdc145d0e76f9f4d19485cdf34fdeca47e26dc8b/addons/common/initSettings.inc.sqf#L45) ). Should the pbo be removed, it silently breaks multiple interactions. Some that I found out before tracking down the dependency and adding the required pbo:

- Interacting with vehicle cargo will fail silently. This includes opening vehicle cargo and/ or adding things to the cargo.
- Taking out nozzle for refuel will fail due to failure in building a progress bar. The message would display "Time left: scalar NaN" and stuck until interaction is cancelled.

**Steps to reproduce:**
_Follow [this flowchart](https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp)!_

1. Remove `ace_optionsmenu.pbo`
2. Launch the game, there will be no warning shown about missing pbo.
3. Open Addon Options, the list for "Progress bar location" would contain template strings rather than Top & Bottom
4. Launch editor, spawn a fuel truck and BLUFOR engineer (or any unit with toolkit in inventory), set said unit as gamemaster and play the scenario.
5. remove one wheel of the fuel truck, should be successful with proper progress bar showing.
6. load the removed wheel to cargo, should fail silently.
7. try to access truck's cargo, should fail silently.
8. Take out fuel nozzle from the truck, should stuck with message `Taking fuel nozzle... Time left: scalar NaN`, 
9. cancel interaction to regain control, game should return to playable state with no apparent error.

**Expected behavior:**

`ace_optionsmenu` should be mentioned as (transitive) dependency.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**

Not applicable since the game work properly apart from those interaction failures.

**Additional context:**

I tried to explore the mechanic added by ACE part-by-part (stamina system, medical, vehicle, etc). Hence rather than removing pbos, I tried to build minimal subset of pbos using [dependency list](https://ace3.acemod.org/wiki/development/dependencies) from documentation.

**Screenshots:**

Will add later if requested

**Comment by johnb432** [comment]
>ace_optionsmenu should be mentioned as (transitive) dependency.

Considering it's only a single missing string, I don't think making it a dependency is a good idea.

>[dependency list](https://ace3.acemod.org/wiki/development/dependencies) from documentation

Seems to be out-of-date, cargo isn't even mentioned on that page. (It's also not alphabetically ordered, reee.)
I wouldn't trust that page fully until it can be fully rectified and verified.

---

Good find, thank you for reporting it.
