### ISSUE TITLE
Mismatch of breathing in Advanced Fatigue (with and without aiming)

### ISSUE THREAD

**Issue by 211345082311111** [acemod/ACE3#9686]
- **Arma 3:** `2.14` [stable]
- **CBA:** `3.` [today last steam version, stable]
- **ACE3:** `3.16.1` [stable]

**Description:**

Good day ACE3!  Every time player enjoy the Advanced Fatigue, unfortunately, He can notice, a lack of logic. When the player's power scale is used up and he cannot longer run, Advanced Fatigue does not have head sway, what should the chest movement cause (when man heavy breathing), but has a very noteciable weapon sway at aiming  , which is essentially must be caused namelly by chest movement, durring  heavy breathing. At that moment, the player is not 1000 percent short of head sway!

 I made a video of what it should look like in my mind - https://www.youtube.com/watch?v=_RwNCRdiG2A
**Maybe you can add head sway during a player's inability to run?**

That would be super immersive and logical, since the swinging of the weapon should be caused by the movement of the chest and head.

**Steps to reproduce:**
Run to exhaustion and then weapon aim, after that remove the aiming. 
With aiming you will see the big sway of the weapon, without aiming you won't see even the slightest head sway.

**Expected behavior:**
Expected behavior - in my video - https://www.youtube.com/watch?v=_RwNCRdiG2A

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by BaerMitUmlaut** [comment]
Feature requests belong into #3594.
