### ISSUE TITLE
[Captives] Loading surrenderee into vehicle blocks player entry

### ISSUE THREAD

**Issue by mwpowellhtx** [acemod/ACE3#9688]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14` stable
- **CBA:** `3.16.1.231025` stable
- **ACE3:** `3.16.1.74` stable

**Description:**
Loading _zip tied surrenderee_ into a vehicle, player cannot enter vehicle in any position, driver, cargo, etc. Tried to enter vehicle using both _ACE Get In_ action menu, the action does not respond, and no vanilla options are available to get in, either. See steps etc below.

Unit is still `captive` (`true`), side is `civilian` after loading and unloading. Not sure what else you need to know; something does not seem right there. If I have to, I can upload a video, perhaps, of my interaction; or even share my screen over _discord_, if it helps. Not sure what else and/or kosher I need to do in order to be able to still interact with the vehicle.

**Steps to reproduce:**
Load _zip tied surrenderee_ into vehicle, either via ACE, or custom integrated, difference between loading into a default `cargo` role, or the first available `turret` role, for instance, in a HEMTT transport.

_Surrenderee_ is also made a member of the `group player` responding to the ACE `"sethandcuffed"` event.

When player unloads the _surrenderee_, then player can get into the vehicle as expected, but it defeats the purpose of loading captives into the vehicle in the first place.

**Expected behavior:**
Would not expect the unit being among the vehicle crew block players from entering the vehicle.

**Additional logging:**
Seems like somehow during the course of events, ACE may be trying to re-surrender the unit, finding these repeatedly in the logs.

```
17:06:50 [ACE] (captives) WARNING: Cannot surrender while handcuffed
17:06:50 [KP LIBERATION] [1708.63] [CAPTIVES] [fn_captives_onAceCaptiveStatusChanged] Entering: [alive _unit, name _unit, _state, _reason, _side, side _unit, _uuid]: [true,"Abdul-Basir Muhtaram",true,"SetSurrendered",EAST,CIV,"3905308546d6f4a328b5e5277f64b928"]
```

Could not tell you why that is the case.

**Comment by mwpowellhtx** [comment]
Cleared the deck from the log, that was my statemachine bouncing errantly between states. Resolved that condition, now no longer the case.

```
17:06:50 [ACE] (captives) WARNING: Cannot surrender while handcuffed
```

However, the core issue blocking vehicle entry, still an issue.

**Comment by LinkIsGrim** [comment]
I assume you mean loading a captive, as a unit cannot be surrendering and zip-tied at the same time.

**Comment by LinkIsGrim** [comment]
Can't reproduce with CBA + ACE. You've got something weird going on in your scripting or Liberation. `ace_captives_fnc_setSurrendered` should not be run on units after they've been handcuffed, and that's the only reason for that warning to pop up in your RPT.

**Comment by mwpowellhtx** [comment]
Appreciate the feedback... Further digging, I wonder there is not something intrinsic going on with _Arma_ itself, groups, units, whatever else might be influencing them. At least for the moment, I do not think it is anything _ACE_ in particular that is causing the mechanical break down.
