### ISSUE TITLE
Arsenal - Un-hiding interface force shows stats and actions boxes

### ISSUE THREAD

**Issue by LinkIsGrim** [acemod/ACE3#9722]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14`
- **CBA:** `3.16.1`
- **ACE3:** `3.16.2 RC1`

**Description:**
Title.  Page change arrows are also force-shown, even if only a single action is available.

**Steps to reproduce:**

1. Hide the arsenal interface
2. Unhide the arsenal interface
3. Arsenal will show action/stats box with last shown action/stats data, regardless if it would be visible for that item or left panel. If there is no last action data, a black actions box will be shown instead.

**Expected behavior:**
Returning all controls to previous shown state upon unhiding the interface.

**Where did the issue occur?**
- Virtual Arsenal

**Log Files:**
Irrelevant.

**Additional context:**
https://github.com/acemod/ACE3/blob/master/addons/arsenal/XEH_preInit.sqf#L15-L31
https://github.com/acemod/ACE3/blob/master/addons/arsenal/XEH_preInit.sqf#L49-L65

**Screenshots:**
Screenshot taken after cycling interface, using https://github.com/mjc4wilton/BackpackOnChestRedux/pull/12. Stats will suffer from the same issue, should an item without stats be selected.

![107410_20240108184508_1](https://github.com/acemod/ACE3/assets/69561145/66ff90ce-b6a3-42e9-9bd8-b3ab7bdb5680)

**Comment by johnb432** [comment]
I see the bug with the actions, but how do you repro it for stats? Stats seem to work fine for me.

**Comment by LinkIsGrim** [comment]
It's convoluted, either create a new item which fails all stat conditions, or force the conditions to false.

I'll add repro code when able
