### ISSUE TITLE
Cook off bugged

### ISSUE THREAD

**Issue by Vereenn** [acemod/ACE3#9742]
Description:
Cook off doesn't seem to be working properly. It occurs continuously with short breaks, and sometimes it also looks bugged like some kind of star pattern.

![image](https://github.com/acemod/ACE3/assets/122136527/d0bdb348-e52f-49e8-9307-8888622d2708)

The vehicle will never explode even though the "destroy vehicles after cook off" is selected. Advanced vehicle damage is on as well.

Steps to reproduce:
Launch Arma, with ace
Spawn vehicle using zeus, attempt to destroy it via various means.

Expected behavior:
Cook off will never end, the vehicle will never explode.

Where did the issue occur?
Both in our modded liberation multiplayer campaign, and in almost vanilla single player editor test.

![image](https://github.com/acemod/ACE3/assets/122136527/02c78c59-14ab-4c49-8fbf-975d2461b9b4)

**Comment by Drofseh** [comment]
Please fill out the template in full and attach the requested rpt log files and then reopen this issue.
