### ISSUE TITLE
Cook off bug - vehicle never explodes, and cook off flame occurs multiple times.

### ISSUE THREAD

**Issue by Vereenn** [acemod/ACE3#9743]
**Mods:**
- **Arma 3:** `2.14 profiling
- **CBA:** `3.16.1
- **ACE3:** `3.16.2 stable

**Description:**
Cook off doesn't seem to be working properly. It occurs continuously with short breaks, and sometimes it also looks bugged like some kind of star pattern. The vehicle will never explode even though the "destroy vehicles after cook off" is selected. Advanced vehicle damage is on as well.

**Steps to reproduce:**
Launch Arma, with ace
Spawn vehicle using zeus, attempt to destroy it via various means.

**Expected behavior:**
I expected the vehicle to cook off and then explode.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) - the issue occurs in every of these cases.

**Log Files:**
https://pastebin.com/7QJe48ie

**Additional context:**
None.

**Screenshots:**
![image](https://github.com/acemod/ACE3/assets/122136527/9d5f1f9e-bb80-42fe-8011-82bb05cbad87)
![image](https://github.com/acemod/ACE3/assets/122136527/2b4a4813-4f1b-4020-9dae-ad04ff63074f)

**Comment by johnb432** [comment]
Can you post all CBA settings from cookoff and advanced vehicle damage?

> 2:45:12 [ACE] (cookoff) WARNING: no valid selection for cookoff found. O_APC_Tracked_02_cannon_F
That might be the issue, but need the settings to understand further.

**Comment by Vereenn** [comment]
> > It occurs continuously with short breaks
> 
> That's intended. Star pattern is also intended, but it shouldn't remain (those effects should last 20 seconds max if I recall correctly).
> 
> Can you post all CBA settings from cookoff and advanced vehicle damage?
> 
> > 2:45:12 [ACE] (cookoff) WARNING: no valid selection for cookoff found. O_APC_Tracked_02_cannon_F
> 
> That might be the issue, but need the settings to understand further.

![image](https://github.com/acemod/ACE3/assets/122136527/b8c63e53-5264-4e4e-8ab7-da6997e642f5)
![image](https://github.com/acemod/ACE3/assets/122136527/57737537-7dfa-4d27-a5de-4673938eec6e)

**Comment by johnb432** [comment]
It can take a while for a vehicle to fully burn through its ammo and have finished its cook-off, only then does the vehicle get destroyed. How long did you wait?

> sometimes it also looks bugged like some kind of star pattern

Can you elaborate on this further? How did it stay stuck - frozen flames or did the flames never stop?

**Comment by Vereenn** [comment]
> It can take a while for a vehicle to fully burn through its ammo and have finished its cook-off, only then does the vehicle get destroyed. How long did you wait?

I left the game running in the background for about 10 minutes and it was still cooking off. I remember that some ACE versions ago it used to cook off once then explode.

> Can you elaborate on this further? How did it stay stuck - frozen flames or did the flames never stop?

The flames stop for a brief moment, and then the cook off flame begins again.

**Comment by johnb432** [comment]
> The flames stop for a brief moment, and then the cook off flame begins again.

That's expected behaviour, from a code point of view.

I suggest playing with the settings to get something you like.

**Comment by johnb432** [comment]
> It will keep cooking off, even though there's no ammo inside at all

In the code, that isn't what governs the destruction of a vehicle. If you give it enough time, it will destroy the vehicle after the cook-off has finished. For me it was 2-3 minutes.

I would advise turning off advanced vehicle damage, if you want to avoid such behaviour.

**Comment by Vereenn** [comment]
That's what I thought but the dumb vanilla "explode after receiving x damage" is even worse. I wouldn't have any problems with cook off if it wasn't for the fact that it takes so long. 

> In the code, that isn't what governs the destruction of a vehicle. If you give it enough time, it will destroy the vehicle after the cook-off has finished. For me it was 2-3 minutes.

What governs the destruction of vehicle then?
Now that I think about it, is it possible at all to one shot explode vehicle with cook off and advanced vehicle damage enabled?

**Comment by johnb432** [comment]
> Now that I think about it, is it possible at all to one shot explode vehicle with cook off and advanced vehicle damage enabled?

Yes, if you do enough damage in one hit, see: https://github.com/acemod/ACE3/blob/4756bb6f8ce63790f358b70f60707d8948a28c83/addons/vehicle_damage/functions/fnc_processHit.sqf#L36

or an engine hit, see: https://github.com/acemod/ACE3/blob/4756bb6f8ce63790f358b70f60707d8948a28c83/addons/vehicle_damage/functions/fnc_processHit.sqf#L194

---

> What governs the destruction of vehicle then?

The intensity of the cook-off, see:
https://github.com/acemod/ACE3/blob/4756bb6f8ce63790f358b70f60707d8948a28c83/addons/cookoff/functions/fnc_cookOff.sqf#L63

That's determined in https://github.com/acemod/ACE3/blob/master/addons/vehicle_damage/functions/fnc_processHit.sqf.
There are 4 hitpoints that cause cook-off when hit: Engine, hull, turret and fuel. The cook-off intensity in each case depends on different aspects (e..g. fuel depends on how much fuel is left, turret depends on how much explosive ammo is left).

**Comment by johnb432** [comment]
Because this isn't a bug, this is now closed.

**Comment by acknowledge14** [comment]
Could we expect more (CBA) settings for Advanced vehicle damage / cookoff, so that we can more easily made heavy armors totally destroyed with multiple fatal hits?
