### ISSUE TITLE
Towing inoperable

### ISSUE THREAD

**Issue by matthawkins2** [acemod/ACE3#9768]
**Mods:**
- **Arma 3:** `2.14.150957 Stable` 
- **CBA:** `3.16.1.231025 Stable`
- **ACE3:** `3.16.3.79 Stable` 

**Description:**
When you attempt to tow a vehicle, the towed vehicle does not move and remains stationary. An error is produced when you attempt to complete the tow rope connection with the towed vehicle.

**Steps to reproduce:**
1. Have two vehicles (lead and following vehicle)
2. Have rope
3. Interact on lead vehicle and place rope on rear bumper
4. Interact on following vehicle and place rope on front bumper

**Expected behavior:**
- Connect rope to vehicle 1 (lead vehicle)
- Connect rope to vehicle 2 (following vehicle)
- Drive lead vehicle and have following vehicle move

**Where did the issue occur?**
- Singleplayer, also occurs in Dedicated MP

**Log Files:**
- [https://pastebin.com/8yQ1c8sD](https://pastebin.com/8yQ1c8sD)

```
14:37:33 Error in expression < ["ace_towing_hook", objNull];

_parent removeEventHandler ["Deleted", _hook get>
14:37:33   Error position: <removeEventHandler ["Deleted", _hook get>
14:37:33   Error Type Any, expected Number
14:37:33 File /z/ace/addons/towing/functions/fnc_detach.sqf..., line 315
14:37:33  ➥ Context: 	[] L446 (/z/ace/addons/towing/functions/fnc_towStateMachinePFH.sqf)
	[] L336 (/z/ace/addons/towing/functions/fnc_detach.sqf)
	[] L291 (/x/cba/addons/events/fnc_targetEvent.sqf)
```

**Additional context:**
There is a related issue report specific to multiplayer towing here: #9619 
There is a potentially related pending PR related to towing here: #9007 

**Screenshots:**
N/A

**Comment by LinkIsGrim** [comment]
Solved in #9007
