### ISSUE TITLE
Nightvision - Inconsistent Layer behaviour

### ISSUE THREAD

**Issue by EinfachJul** [acemod/ACE3#9781]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14 stable` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.16.1 stable` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.16.3 stable` [eg. 3.0.0 stable, commit hash]

**Description:**
The Nightvision module rscTitles are not properly initialised within its postInitEXH.
This results in other layers (e.g. the microDAGR) being displayed beneath the nvg layer, if the nightvision is activated after.

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. Start a mission with a unit equipped with a nvg and microDAGR equipped
2. activate nvg via hotkey
3. open the microDagr.
4. reload mission
5. repeat 2 and 3 in reversed order
6. compare

**Expected behavior:**
The nightvision layer should be initialised postInit for a reliable rendering of following rscTitles

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Log Files:**
- None

**Additional context:**
**allCutLayers** returns
`["","cba_optics_pauseOpticLayer","ace_field_rations_hud","ace_goggles_GogglesEffectsLayer","ace_goggles_GogglesLayer","HealthPP_blood","HealthPP_dirt","HealthPP_fire","HealthPP_black"]`
upon mission start

**allCutLayers** after picture 1 (steps 2-3) returns:
`["","cba_optics_pauseOpticLayer","ace_field_rations_hud","ace_goggles_GogglesEffectsLayer","ace_goggles_GogglesLayer","HealthPP_blood","HealthPP_dirt","HealthPP_fire","HealthPP_black","ace_nightvision_display","ace_nightvision_turnOnEffect","ace_microdagr_TheRscTitleDisplay"]`

**allCutLayers** after picture 2 (steps 5-6) returns:
`["","cba_optics_pauseOpticLayer","ace_field_rations_hud","ace_goggles_GogglesEffectsLayer","ace_goggles_GogglesLayer","HealthPP_blood","HealthPP_dirt","HealthPP_fire","HealthPP_black","ace_microdagr_TheRscTitleDisplay","ace_nightvision_display","ace_nightvision_turnOnEffect"]`

**Screenshots:**
![20240208203555_1](https://github.com/acemod/ACE3/assets/15852319/a074cf2f-567c-4ae2-987a-685f554c883d)
![20240208204343_1](https://github.com/acemod/ACE3/assets/15852319/d4638c33-a787-4ce1-b9ee-2adbb398fbab)

**Comment by LinkIsGrim** [comment]
Ref https://github.com/acemod/ACE3/blob/master/addons/nightvision/XEH_postInit.sqf#L46-L47
