### ISSUE TITLE
Scopes/AB - Look into nil values for weapons without AB configs

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#9840]
e.g. sog SKS
`ace_scopes_fnc_calculateZeroAngleCorrection` line 69
```
    _zeroAngle = "ace_advanced_ballistics" callExtension format ["calcZeroAB:%1:%2:%3:%4:%5:%6:%7:%8:%9", _newZeroRange, _initSpeed, _boreHeight, GVAR(zeroReferenceTemperature), GVAR(zeroReferenceBarometricPressure), GVAR(zeroReferenceHumidity), _ballisticCoefficients select 0, _dragModel, _atmosphereModel];
    (parseNumber _zeroAngle)
```

`_ballisticCoefficients select 0` will select from empty array
results in 
`parseNumber "-nan(ind)"`  from extension return

on profiling branch this is causing errors, but it's something we should fix ourselves
look at rust - https://github.com/acemod/ACE3/pull/9015

**Comment by IllicLanthresh** [comment]
> look at rust - #9015

Sorry for interfering, our clan recently suffered from these errors and someone sent me this issue and took a look at the code out of curiosity, and to check if I could maybe open a PR.

I fail to see why the rust PR is relevant in this issue, I checked the changes on `fnc_calculateZeroAngleCorrection.sqf` and the call is being made in the same way, using the same argument for the coefficient (`_ballisticCoefficients select 0`).

I also compared the C++ code and the Rust code and I don't see any new special case behavior when there's no coefficient passed to the calculate function.
