### ISSUE TITLE
Medical/Dragging - Failing to drag/carry a player breaks medical interactions

### ISSUE THREAD

**Issue by Zman6258** [acemod/ACE3#9857]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14.150957 stable (latest)`
- **CBA:** `3.16.1 stable (latest)`
- **ACE3:** `3.16.3 stable (latest)`

**Description:**
Attempting and failing to drag an overweight player breaks their medical menu, and the ability for others to drag/carry them. This is most likely caused by the "claim" system in the drag/carry framework failing to clear the "owner" of the other player when a drag is initiated but immediately fails.

**Steps to reproduce:**
1. (Optional) Increase the Dragging weight coefficient to 2 to make it easier to overload
2. Get at least three players in multiplayer (tested with clients for player-hosted and dedicated multiplayer)
3. Load (or, with scripting, overload) one player [Player A] with as much weight as possible (full armor with 36m ropes is ideal)
4. Render Player A unconscious in any way
5. Player B should attempt to drag/carry Player A's downed body, which should fail with a popup stating "Item too heavy"
6. Wake up Player A from unconsciousness in any way
7. Player A attempts to open their own medical menu, which fails
8. Player B attempts to open Player A's medical menu, which succeeds
9. Player C attempts to open Player A's medical menu, which fails

**Expected behavior:**
When failing to drag a player, the claim is removed properly, and others can continue accessing their medical menu or attempt to drag/carry them.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**Log Files:**
https://gist.github.com/Zman6258/0c12640af01e62ffcafba53df1a140fc

**Additional context:**
The problem inconsistently persists even through respawning. It can, however, be consistently resolved by successfully dragging/carrying the person again (usually by having them drop most of their equipment before being knocked down). The problem DOES NOT occur with AI that are local to the player's machine, nor does it occur with other draggable/carryable items such as crates, which makes me think that it's specifically related to the state not being transferred over network correctly.

**Comment by PabstMirror** [comment]
I've seen this before in #9465
I knew it was something to do with claim and `ace_common_owner` being set
But having full reproduction steps will be a huge help

**Comment by johnb432** [comment]
https://github.com/acemod/ACE3/blob/5e1771aecdf55f359e6cc90a811e9a2a245e66ff/addons/dragging/functions/fnc_startCarryLocal.sqf#L34 is where we need to relinquish the claim on the object.
