### ISSUE TITLE
Sway Factor still applies even when ACE3 Advanced Fatigue is disabled

### ISSUE THREAD

**Issue by Uncle-Sagbag** [acemod/ACE3#9862]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14.150957`
- **CBA:** `v3.16.1.231025`
- **ACE3:** `3.16.3`

**Description:**
Sway factor still applies to the player and is unchangeable regardless whether ACE Advanced Fatigue is enabled or disabled. Even at the default sway factor of 1.0, the CustomAimCoef is set to 1.5. Changing the sway factor slider, even when ACE Advanced Fatigue is disabled, changes the CustomAimCoef.

The current workaround is to change the sway factor slider even when ACE Advanced Fatigue is not enabled.

**Steps to reproduce:**

1. Open the Eden Editor
2. Select and load into Virtual Reality
3. Open Addon Options and disable ACE Advanced Fatigue under Server
4. Place any unit such as NATO, Men, Ammo Bearer
5. Play as Ammo Bearer in Singleplayer Preview
6. Open the Esc Menu
7. Check Sway Factor by running the following command in Debug Console:
`getCustomAimCoef player` which will return `1.5`
8. Change Sway Factor by running another command:
`player setCustomAimCoef 2500`
9. Check Sway Factor by running the following command in Debug Console:
`getCustomAimCoef player` which will return `2500`
10. Close the Esc Menu
11. Open the Esc Menu
12. Check Sway Factor by running the following command in Debug Console:
`getCustomAimCoef player` which will return `1.5`

**Expected behavior:**
When I disable ACE Advanced Fatigue, I expect CustomAimCoef to remain at the vanilla value 1. Then, running commands like `player setCustomAimCoef 2500` would apply and stay on the player when I exit the Esc Menu.

**Where did the issue occur?**
- Dedicated
- Editor (Singleplayer)
- Virtual Arsenal

**Log Files:**
- https://pastebin.com/eP67ubqC

**Additional context:**
This was discovered until users started reporting it during the winter, around January/February 2024.

**Screenshots:**
N/A

**Comment by BaerMitUmlaut** [comment]
Disabling Advanced Fatigue requires a mission restart. There's a hint that tells you just that.

Additionally, medical will also impact weapon sway. If you need to do your own adjustments, use [ace_common_fnc_addSwayFactor](https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_addSwayFactor.sqf).

**Comment by Uncle-Sagbag** [comment]
I repeated the steps but re-loaded the mission right after disabling Advanced Fatigue. It was the same result: the Sway Factor slider influenced the AimCoef.

In fact, setting Sway Factor to 0 sets the AimCoef to 0 as well. This rules out the possibility that ACE Medical is the sole module affecting it.

Is it by design that sliders under ACE Advanced Fatigue still affect the client even when Advanced Fatigue is disabled? I thought the Enable checkbox at the top of addon setting sections makes every slider ineffective for that section. If that is not the case, that Sway Factor slider is meant to affect clients regardless of ACE Advanced Fatigue status, then everything is by design.

**Comment by johnb432** [comment]
Sway is independent of if the setting is enabled or not. We'll have to discuss it internally if we want the `enable` setting to affect sway or not.

**Comment by johnb432** [comment]
If `enabled` is off, we should turn off the sway.
