### ISSUE TITLE
Low SPO2 breaks CPR

### ISSUE THREAD

**Issue by Callum511** [acemod/ACE3#9914]
**Mods (complete and add to the following information):**
- **Arma 3:** 2.16 stable
- **CBA:** 3.17 stable
- **ACE3:** 3.17 stable

**Description:**
If SPO2 drops too low while a patient is in cardiac arrest, CPR will not be able to revive them as their heart rate will spike above the critical threshold on success.

**Steps to reproduce:**

1. Set the Cardiac arrest death timer to a high value (15 mins worked for me)
2. Stop someones heart
3. Wait for their SPO2 to hit 0
4. Repeatedly try to CPR them and observe the results

**Expected behavior:**
Heart rate should not spike above critical threshold on CPR success with low SP02

**Comment by OverlordZorn** [comment]
lot of discussion and potentially more details can be found here:
https://discord.com/channels/976165959041679380/1225075656640040981
