### ISSUE TITLE
ACE Spearhead 1944 Compatibility: Mortars not using Assembly & Ammunition Handling framework

### ISSUE THREAD

**Issue by Coldfront15** [acemod/ACE3#9940]
**Mods (complete and add to the following information):**
- **Arma 3:** 2.16 stable
- **CBA:** 3.17 stable
- **ACE3:** 3.17 stable
- **CDLC, Spearhead 1944** 

**Description:**
When utilizing the M1 81, GrW 278/1 or the Mle. 27/31 mortar systems from Spearhead 1944 - I am unable to use the advanced assembly/disassembly or ace ammo handling frameworks when they are enabled.

**Steps to reproduce:**

1. Enter Editor.
2. Click on Settings > Addon Options > 'ACE CSW' && 'ACE Artillery'.
3. Enable Advanced Assembly Options, Enable Ammunition Handling.
4. Place either 'M1 81mm Mortar', 'GrW 278/1 Mortar' or the 'Mle. 27/31 Mortar' from Spearhead 1944.
5. Play, attempt to disassemble using ACE. 
6. Play, attempt to load using ACE. 

**Expected behavior:**
Expecting the ability to disassemble, reassemble similar to the Mk 6 Mortar & loading system similar to the Mk 6 Mortar.

**Where did the issue occur?**
- Dedicated
- Editor (Singleplayer)

**Log Files:**
- https://gist.github.com/Coldfront15/f8f1de3a960e6f942a542f92ad1bbac9

**Additional context:**
None necessary.

**Screenshots:**
None necessary.

**Comment by johnb432** [comment]
https://github.com/acemod/ACE3/pull/9292#discussion_r1327738181
It's currently not enabled as it's a todo, we still need to figure out how to best add CSW support.

As it's not a bug, this will be closed.
