### ISSUE TITLE
3.17.0 - The new Cook Off sounds sound worse, than the previous ones.

### ISSUE THREAD

**Issue by 211345082311111** [acemod/ACE3#9958]
**Description:**

Sorry if I'm posting this topic in the wrong place, but I just couldn't find a better place.

In version 3.17.0 Cookoff - ammo detonation sounds were added and supposedly "improved". But it sounds worse now. As seems to me, they sound too quiet, if the player is close. In general, the sounds should be different at distances (Close, Medium, Far) But instead, the player hears one and the same sound, with the with fading volume. Unfortunately, this update not sounds like improved sound, it just looks like a not successful replacement. 

**Expected behavior:**
At a distance, preferably 10-20 meters, it should sound at least twice as loud. The Close and Far distance sound, must have different samples. 

**Where did the issue occur?**
- Editor (Singleplayer)

**Comment by Drofseh** [comment]
If you believe this is a bug, please fill out the issue template correctly and then reopen this issue.

**Comment by 211345082311111** [comment]
> If you believe this is a bug, please fill out the issue template correctly and then reopen this issue.

No, dude, it's not a bug, I just didn't find where to put it. I don't think it should be placed in the "Feature request".  I just had to click "New Issue"
