### ISSUE TITLE
Cargo - Go over config values again

### ISSUE THREAD

**Issue by LinkIsGrim** [acemod/ACE3#9964]
Cargo refactor changed it so `GVAR(hasCargo)` needs to be explicit (either through inheritance or just set in class).

Need to go over configs again and make sure that's the case where it should be.

Sizes/spaces are also messed up. Some objects allow for bags of holding: https://github.com/acemod/ACE3/blob/master/addons/cargo/CfgVehicles.hpp#L778-L785

Other have `GVAR(hasCargo)` set to over 1: https://github.com/acemod/ACE3/blob/master/addons/cargo/CfgVehicles.hpp#L512-L513 should still work, but should just be 1

@johnb432 @Mike-MF @LinkIsGrim

**Comment by johnb432** [comment]
>should still work, but should just be 1
No it doesn't, as it checks for `1` specifically.

**Comment by johnb432** [comment]
> Sizes/spaces are also messed up. Some objects allow for bags of holding: https://github.com/acemod/ACE3/blob/master/addons/cargo/CfgVehicles.hpp#L778-L785

I'm fairly confident that's intentional.

**Comment by johnb432** [comment]
https://github.com/acemod/ACE3/pull/9994#issuecomment-2103445879

We won't change stuff for BWC, meaning this issue has been fully addressed.
