### ISSUE TITLE
AI Medic will stop moving/refuse orders when it has no Splints in Inventar

### ISSUE THREAD

**Issue by Holgerhollebolle** [acemod/ACE3#9970]
**Mods (complete and add to the following information):**
- **Arma 3:** 2.16.151618 stable 
- **CBA:** v3.17.0 stable
- **ACE3:** 3.17.0  stable

**Description:**
When an AI Medic has no Splints in the Inventar and a Teammate gets a broken leg the Medic gets stuck in a function and does not move anymore. Any orders given to the Medic will not get executed anymore.

**Steps to reproduce:**

1. Create a group in the Editor with a Medic. 
2. Remove any Splints from Medic Loadout.
3. Play as teamleader
4.  Shoot a teammate in the Legs (maybe increase Fracture chance to provoke Fratureing faster)
--> When the Teammate has a Fracture the AI Medic will start treating but than stops (as it can not treat the fracture) and than it stops doing anything. The medic is stuck and There is no way to get it back to do anything.
Also the Unit the got treated is not moving anymore.

**Expected behavior:**

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
No Logfiles needed as there is no errors in the log. If you need a Logfile anyways please let me know.

**Additional context:**
You need to enable AI medic in the Settings. 

**Screenshots:**
No Screenshot.

**Comment by Holgerhollebolle** [comment]
btw. When you add a Splint to the Stuck Medic Inventar it will move again. Its like a function is waiting for a splint in the Inventar to get finished.

**Comment by johnb432** [comment]
This stems from a more general problem: if the healer doesn't have the requires item, it will skip trying to heal in the healing logic. However, the medical state machine keeps seeing the unit to be healed as injured, so it remains in the healing logic, which blocks the healer and injured from moving.
