### ISSUE TITLE
Some switchMove animations stop playing

### ISSUE THREAD

**Issue by Apricot-ale** [acemod/ACE3#9972]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.16 stable` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.17.1 stable` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.17.0 stable` [e.g. 3.0.0 stable, commit hash]

**Description:**
Animations such as "Acts_AidlPercMstpSnonWnonDnon_warmup_3_loop" played correctly in vanilla environments and up to ACE 3.16.3. However, since 3.17.0 Unit will "pauses" as soon as the animation starts playing and does not play correctly.

**Steps to reproduce:**
_Follow [this flowchart](https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp)!_

1. _Open 3den, place rifleman(nato) x2 (one is player, one is AI)_
2. _Start mission(in editor), Press ESC and open debug console_
3. _Execute this code ```_unit = player;
_move = "Acts_AidlPercMstpSnonWnonDnon_warmup_3_loop";
_unit switchMove _move;```_
4. _See in spectator or 3rdPersonView, check player unit movement. then close spectator._
5. _Point crosshair to AI then Open debug console_
6. _Execute this code ```_unit = cursorTarget;
_move = "Acts_AidlPercMstpSnonWnonDnon_warmup_3_loop";
_unit switchMove _move;```_
7. _See and check AI unit movement._

**Expected behavior:**
In vanilla(and CBA), animation is works fine (it's moves rifle).
In ACE3, animation is switched but motion will stop immediately.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
almost any.

**Log Files:**
[Arma3_x64_2024-04-25_01-41-08.rpt.txt](https://github.com/acemod/ACE3/files/15097754/Arma3_x64_2024-04-25_01-41-08.rpt.txt)

**Additional context:**
https://steamcommunity.com/sharedfiles/filedetails/?id=766491311
I first noticed this bug when using it in multiplayer.
It was working correctly before(3.16.3), but I noticed that from 3.17.0 the behavior is different than before.
In the end, this occurred even when I try "switchMove" without this mod, so ACE was identified as the cause.

**Screenshots:**
N/A

**Comment by johnb432** [comment]
Bug was introduced by #9846. I'm looking into a fix.
